ML: MLAPI::LoadBalanceOperator Class Reference
MLAPI::LoadBalanceOperator Class Reference
Public Member Functions
LoadBalanceOperator ()
Default constructor.
LoadBalanceOperator (const Space &DomainSpace, const Space &RangeSpace, ML_Operator *Op, bool Ownership=true, Teuchos::RefCountPtr< ML_Operator_Box > AuxOp=Teuchos::null)
Constructor with given already computed ML_Operator pointer.
LoadBalanceOperator (const Space &DomainSpace, const Space &RangeSpace, Epetra_RowMatrix *Matrix, bool Ownership=true, Teuchos::RefCountPtr< ML_Operator_Box > AuxOp=Teuchos::null)
Constructor with given already FillComplete()'d object.
LoadBalanceOperator (const LoadBalanceOperator &RHS)
Copy constructor.
~LoadBalanceOperator ()
Destructor.
void Reshape ()
Resets this object.
void Reshape (const Space &DomainSpace, const Space &RangeSpace, ML_Operator *Op, bool Ownership=true, Teuchos::RefCountPtr< ML_Operator_Box > AuxOp=Teuchos::null)
Reshape with given already computed ML_Operator pointer.
void Reshape (const Space &DomainSpace, const Space &RangeSpace, Epetra_RowMatrix *Matrix, bool Ownership=true, Teuchos::RCP< ML_Operator_Box > AuxOp=Teuchos::null)
Reshape with given already FillComplete()'d object.
LoadBalanceOperator & operator= (const LoadBalanceOperator &RHS)
Makes this object equivalent to RHS.
Operator & operator= (const std::string &Label)
Sets the label of this object.
virtual bool GetParticipation () const
Returns a bool indicating whether this proc participates in the operator application.
const Space GetOperatorDomainSpace () const
Returns a reference to the internally stored domain space.
const Space GetOperatorRangeSpace () const
Returns a reference to the internally stored range space.
const Space GetDomainSpace () const
Returns a reference to the internally stored domain space.
const Space GetRangeSpace () const
Returns a reference to the internally stored range space.
const Space GetColumnSpace () const
Returns a reference to the internally stored column space.
int GetNumGlobalRows () const
Returns the number of global rows.
int GetNumMyRows () const
Returns the number of local rows.
int GetNumGlobalCols () const
Returns the number of global columns.
int GetNumMyCols () const
Returns the number of local columns.
int GetNumGlobalNonzeros () const
Returns the global number of nonzeros.
int GetNumMyNonzeros () const
Returns the local number of nonzeros.
const Epetra_RowMatrix * GetRowMatrix () const
Returns the RefCountPtr of OperatorBox_.
ML_Operator * GetML_Operator () const
Returns the RefCountPtr of OperatorBox_.
const Teuchos::RCP< ML_Operator_Box > & GetRCPOperatorBox () const
Returns the RefCountPtr of OperatorBox_.
const Teuchos::RCP< ML_Operator_Box > & GetRCPAuxOperatorBox () const
Returns the RefCountPtr of AuxOperatorBox_.
const Teuchos::RCP< Epetra_RowMatrix > & GetRCPRowMatrix () const
Returns the RefCountPtr of RowMatrix_.
int GetGRID (const int LRID) const
Returns the global ID of local row ID LRID.
int GetGCID (const int LCID) const
Returns the global ID of local column ID LCID.
int Apply (const MultiVector &X, MultiVector &Y) const
Applies this operator to LHS, returns the result in RHS.
std::ostream & Print (std::ostream &os, const bool verbose=true) const
Prints basic information about this object.
void BuildColumnSpace ()
Build the column space, by computing the GID of all local columns.
Public Member Functions inherited from MLAPI::Operator
Operator ()
Default constructor.
Operator (const Space &DomainSpace, const Space &RangeSpace, ML_Operator *Op, bool Ownership=true, Teuchos::RefCountPtr< ML_Operator_Box > AuxOp=Teuchos::null)
Constructor with given already computed ML_Operator pointer.
Operator (const Space &DomainSpace, const Space &RangeSpace, Epetra_RowMatrix *Matrix, bool Ownership=true, Teuchos::RefCountPtr< ML_Operator_Box > AuxOp=Teuchos::null)
Constructor with given already FillComplete()'d object.
Operator (const Operator &RHS)
Copy constructor.
~Operator ()
Destructor.
void Reshape ()
Resets this object.
void Reshape (const Space &DomainSpace, const Space &RangeSpace, ML_Operator *Op, bool Ownership=true, Teuchos::RefCountPtr< ML_Operator_Box > AuxOp=Teuchos::null)
Reshape with given already computed ML_Operator pointer.
void Reshape (const Space &DomainSpace, const Space &RangeSpace, Epetra_RowMatrix *Matrix, bool Ownership=true, Teuchos::RefCountPtr< ML_Operator_Box > AuxOp=Teuchos::null)
Reshape with given already FillComplete()'d object.
Operator & operator= (const Operator &RHS)
Makes this object equivalent to RHS.
Operator & operator= (const std::string &Label)
Sets the label of this object.
const Space GetOperatorDomainSpace () const
Returns a reference to the internally stored domain space.
const Space GetOperatorRangeSpace () const
Returns a reference to the internally stored range space.
const Space GetDomainSpace () const
Returns a reference to the internally stored domain space.
const Space GetRangeSpace () const
Returns a reference to the internally stored range space.
const Space GetColumnSpace () const
Returns a reference to the internally stored column space.
int GetNumGlobalRows () const
Returns the number of global rows.
int GetNumMyRows () const
Returns the number of local rows.
int GetNumGlobalCols () const
Returns the number of global columns.
int GetNumMyCols () const
Returns the number of local columns.
int GetNumGlobalNonzeros () const
Returns the global number of nonzeros.
int GetNumMyNonzeros () const
Returns the local number of nonzeros.
const Epetra_RowMatrix * GetRowMatrix () const
Returns the RefCountPtr of OperatorBox_.
ML_Operator * GetML_Operator () const
Returns the RefCountPtr of OperatorBox_.
const Teuchos::RefCountPtr< ML_Operator_Box > & GetRCPOperatorBox () const
Returns the RefCountPtr of OperatorBox_.
const Teuchos::RefCountPtr< ML_Operator_Box > & GetRCPAuxOperatorBox () const
Returns the RefCountPtr of AuxOperatorBox_.
const Teuchos::RefCountPtr< Epetra_RowMatrix > & GetRCPRowMatrix () const
Returns the RefCountPtr of RowMatrix_.
int GetGRID (const int LRID) const
Returns the global ID of local row ID LRID.
int GetGCID (const int LCID) const
Returns the global ID of local column ID LCID.
int Apply (const MultiVector &X, MultiVector &Y) const
Applies this operator to LHS, returns the result in RHS.
std::ostream & Print (std::ostream &os, const bool verbose=true) const
Prints basic information about this object.
void BuildColumnSpace ()
Build the column space, by computing the GID of all local columns.
Public Member Functions inherited from MLAPI::BaseOperator
virtual ~BaseOperator ()
Virtual destructor.
Public Member Functions inherited from MLAPI::BaseObject
BaseObject ()
Constructor with empty label.
BaseObject (const std::string &Label)
Constructor with given Label.
virtual ~BaseObject ()
Destructor.
void SetLabel (const std::string &Label)
Sets the Label of this object to Label.
const std::string & GetLabel () const
Returns the Label of this object.
Public Member Functions inherited from MLAPI::CompObject
CompObject ()
Constructor, set counter to 0.0.
~CompObject ()
Destructor.
double GetFlops () const
Returns the internal counter of flops.
void SetFlops (double Flops) const
Sets internal counter to Flops.
void UpdateFlops (double Flops) const
Updates internal counter by summing Flops.
Public Member Functions inherited from MLAPI::TimeObject
TimeObject ()
Constructor, set counter to 0.0.
~TimeObject ()
Destructor.
void ResetTimer () const
Resets the internal timer.
void UpdateTime () const
Updates the internal timer with the time spent since the last call to ResetTimer().
void UpdateTime (double t) const
Updates the internal timer with input value t.
double GetTime () const
Returns the internally stored counter.
Additional Inherited Members
Protected Attributes inherited from MLAPI::TimeObject
Epetra_Time Time_
Object used to track time.
double TotalTime_
Internal counter.
Member Function Documentation
Apply()
int MLAPI::LoadBalanceOperator::Apply (const MultiVector & X, MultiVector & Y) const inline virtual
Applies this operator to LHS, returns the result in RHS.
Implements MLAPI::BaseOperator.
References GetDomainSpace(), GetML_Operator(), MLAPI::MultiVector::GetMyLength(), GetNumGlobalNonzeros(), MLAPI::MultiVector::GetNumVectors(), GetRangeSpace(), MLAPI::MultiVector::GetVectorSpace(), MLAPI::TimeObject::ResetTimer(), MLAPI::CompObject::UpdateFlops(), and MLAPI::TimeObject::UpdateTime().
GetOperatorDomainSpace()
const Space MLAPI::LoadBalanceOperator::GetOperatorDomainSpace () const inline virtual
Returns a reference to the internally stored domain space.
Implements MLAPI::BaseOperator.
GetOperatorRangeSpace()
const Space MLAPI::LoadBalanceOperator::GetOperatorRangeSpace () const inline virtual
Returns a reference to the internally stored range space.
Implements MLAPI::BaseOperator.
Print()
std::ostream & MLAPI::LoadBalanceOperator::Print (std::ostream & os, const bool verbose = true) const inline virtual
Prints basic information about this object.
Implements MLAPI::BaseObject.
References MLAPI::Barrier(), GetDomainSpace(), MLAPI::CompObject::GetFlops(), MLAPI::BaseObject::GetLabel(), GetML_Operator(), MLAPI::GetMyPID(), MLAPI::Space::GetNumGlobalElements(), MLAPI::GetNumProcs(), GetRangeSpace(), GetRCPOperatorBox(), GetRowMatrix(), MLAPI::TimeObject::GetTime(), Epetra_BlockMap::GID(), and Epetra_RowMatrix::RowMatrixColMap().
The documentation for this class was generated from the following file:
MLAPI_LoadBalanceOperator.h