ML: MLAPI::InverseOperator Class Reference
MLAPI::InverseOperator Class Reference
InverseOperator: basic class to define smoother and coarse solvers.
#include <MLAPI_LoadBalanceInverseOperator.h>
Public Member Functions
InverseOperator ()
Empty constructor.
InverseOperator (const Operator &Op, const std::string Type)
Constructor for a given Operator and type, and default parameters.
InverseOperator (const Operator &Op, const std::string Type, Teuchos::ParameterList &List)
Constructor for a given Operator, type and parameters.
InverseOperator (const InverseOperator &RHS)
Copy constructor.
~InverseOperator ()
Destructor.
InverseOperator & operator= (const InverseOperator &RHS)
Operator =.
void Reshape ()
Resets this object.
void Reshape (const Operator &Op, const std::string Type)
Reshapes the object with default values.
void Reshape (const Operator &Op, const std::string Type, Teuchos::ParameterList &List, Teuchos::ParameterList *pushlist=NULL)
Reshapes the object by setting the Operator and the specified type.
void Reshape (Ifpack_Preconditioner *prec, const Operator &Op, const bool ownership)
Reshape with preconstructed smoother as Ifpack_Preconditioner.
const Space GetOperatorRangeSpace () const
Returns a reference to the range space of this object.
const Space GetOperatorDomainSpace () const
Returns a reference to the domain space of this object.
const Space GetRangeSpace () const
Returns a reference to the range space of this object.
const Space GetDomainSpace () const
Returns a reference to the domain space of this object.
const Teuchos::RefCountPtr< Epetra_RowMatrix > RCPRowMatrix () const
Returns pointer of the internally stored ML_Epetra::RowMatrix object.
Epetra_RowMatrix * RowMatrix () const
Returns pointer of the internally stored ML_Epetra::RowMatrix object.
const Operator & GetOperator () const
Returns a reference to the Operator of which this object defines the inverse.
Teuchos::RefCountPtr< Ifpack_Preconditioner > & GetRCPData ()
Returns a pointer to the internally stored IFPACK preconditioner.
Teuchos::RefCountPtr< ML_Epetra::MultiLevelPreconditioner > & GetRCPMLPrec ()
Returns a pointer to the internally stored IFPACK preconditioner.
const Teuchos::RefCountPtr< Ifpack_Preconditioner > & GetRCPData () const
Returns a pointer to the internally stored IFPACK preconditioner.
const Teuchos::RefCountPtr< ML_Epetra::MultiLevelPreconditioner > & GetRCPMLPrec () const
Returns a pointer to the internally stored ML preconditioner.
int Apply (const MultiVector &x, MultiVector &y) const
Applies this object to vector lhs, returns values in rhs.
MultiVector operator() (const MultiVector &LHS)
Applies the operator to LHS, returns the results.
MultiVector operator() (const MultiVector &LHS, const MultiVector &RHS)
Applies the operator to LHS using RHS as initial solution, returns the results.
std::ostream & Print (std::ostream &os, const bool verbose=true) const
Prints out basic information about this object.
Public Member Functions inherited from MLAPI::BaseOperator
virtual ~BaseOperator ()
Virtual destructor.
Public Member Functions inherited from MLAPI::BaseObject
BaseObject ()
Constructor with empty label.
BaseObject (const std::string &Label)
Constructor with given Label.
virtual ~BaseObject ()
Destructor.
void SetLabel (const std::string &Label)
Sets the Label of this object to Label.
const std::string & GetLabel () const
Returns the Label of this object.
Public Member Functions inherited from MLAPI::CompObject
CompObject ()
Constructor, set counter to 0.0.
~CompObject ()
Destructor.
double GetFlops () const
Returns the internal counter of flops.
void SetFlops (double Flops) const
Sets internal counter to Flops.
void UpdateFlops (double Flops) const
Updates internal counter by summing Flops.
Public Member Functions inherited from MLAPI::TimeObject
TimeObject ()
Constructor, set counter to 0.0.
~TimeObject ()
Destructor.
void ResetTimer () const
Resets the internal timer.
void UpdateTime () const
Updates the internal timer with the time spent since the last call to ResetTimer().
void UpdateTime (double t) const
Updates the internal timer with input value t.
double GetTime () const
Returns the internally stored counter.
Additional Inherited Members
Protected Attributes inherited from MLAPI::TimeObject
Epetra_Time Time_
Object used to track time.
double TotalTime_
Internal counter.
Detailed Description
InverseOperator: basic class to define smoother and coarse solvers.
Author
Marzio Sala, D-INFK/ETHZ.
Date
Last updated on Mar-06.
Member Function Documentation
Apply()
int MLAPI::InverseOperator::Apply (const MultiVector & x, MultiVector & y) const virtual
Applies this object to vector lhs, returns values in rhs.
Implements MLAPI::BaseOperator.
Reimplemented in MLAPI::LoadBalanceInverseOperator.
Referenced by MLAPI::MultiLevelAdaptiveSA::SetupInitialNullSpace(), MLAPI::MultiLevelAdaptiveSA::SolveMultiLevelSA(), and MLAPI::MultiLevelSA::SolveMultiLevelSA().
GetOperatorDomainSpace()
const Space MLAPI::InverseOperator::GetOperatorDomainSpace () const virtual
Returns a reference to the domain space of this object.
Implements MLAPI::BaseOperator.
Reimplemented in MLAPI::LoadBalanceInverseOperator.
GetOperatorRangeSpace()
const Space MLAPI::InverseOperator::GetOperatorRangeSpace () const virtual
Returns a reference to the range space of this object.
Implements MLAPI::BaseOperator.
Reimplemented in MLAPI::LoadBalanceInverseOperator.
Print()
std::ostream & MLAPI::InverseOperator::Print (std::ostream & os, const bool verbose = true) const virtual
Prints out basic information about this object.
Implements MLAPI::BaseObject.
Reimplemented in MLAPI::LoadBalanceInverseOperator.
The documentation for this class was generated from the following file:
MLAPI_InverseOperator.h