ML: MLAPI::EpetraBaseOperator Class Reference
MLAPI::EpetraBaseOperator Class Reference
Basic class to wrap MLAPI::InverseOperator into Epetra_Operator.
#include <MLAPI_EpetraBaseOperator.h>
Public Member Functions
EpetraBaseOperator (const Epetra_Map &inMap, const BaseOperator &Op)
Constructor.
virtual ~EpetraBaseOperator ()
Destructor.
int ApplyInverse (const Epetra_MultiVector &X_Epetra, Epetra_MultiVector &Y_Epetra) const
Applies the operator to X, returns the results in Y.
virtual int SetUseTranspose (bool)
Sets the use of tranpose (NOT IMPLEMENTED).
virtual int Apply (const Epetra_MultiVector &X_Epetra, Epetra_MultiVector &Y_Epetra) const
Applies the operator to X, returns the results in Y.
virtual double NormInf () const
NOT IMPLEMENTED.
virtual const char * Label () const
Returns the label of this object.
virtual bool UseTranspose () const
Returns false.
virtual bool HasNormInf () const
NOT IMPLEMENTED.
virtual const Epetra_Comm & Comm () const
Returns a reference to the communicator object.
virtual const Epetra_Map & OperatorDomainMap () const
Returns a reference to the OperatorDomainMap.
virtual const Epetra_Map & OperatorRangeMap () const
Returns a reference to the OperatorRangeMap.
virtual const Epetra_Map & Map () const
Returns a reference to the Map of this object.
const BaseOperator & GetBaseOperator () const
Detailed Description
Basic class to wrap MLAPI::InverseOperator into Epetra_Operator.
Author
Marzio Sala, SNL 9214.
Date
Last updated on Feb-05.
Member Function Documentation
Apply()
virtual int MLAPI::EpetraBaseOperator::Apply (const Epetra_MultiVector & X_Epetra, Epetra_MultiVector & Y_Epetra) const inline virtual
Applies the operator to X, returns the results in Y.
Implements Epetra_Operator.
References MLAPI::BaseOperator::Apply(), MLAPI::BaseOperator::GetOperatorDomainSpace(), MLAPI::BaseOperator::GetOperatorRangeSpace(), MLAPI::MultiVector::GetValues(), Epetra_MultiVector::MyLength(), and Epetra_MultiVector::NumVectors().
Referenced by ApplyInverse().
ApplyInverse()
int MLAPI::EpetraBaseOperator::ApplyInverse (const Epetra_MultiVector & X_Epetra, Epetra_MultiVector & Y_Epetra) const inline virtual
Applies the operator to X, returns the results in Y.
Note
Apply() and ApplyInverse() are the SAME function!
Implements Epetra_Operator.
References Apply().
Comm()
virtual const Epetra_Comm & MLAPI::EpetraBaseOperator::Comm () const inline virtual
Returns a reference to the communicator object.
Implements Epetra_Operator.
References MLAPI::GetEpetra_Comm().
HasNormInf()
virtual bool MLAPI::EpetraBaseOperator::HasNormInf () const inline virtual
NOT IMPLEMENTED.
Implements Epetra_Operator.
Label()
virtual const char * MLAPI::EpetraBaseOperator::Label () const inline virtual
Returns the label of this object.
Implements Epetra_Operator.
References MLAPI::BaseObject::GetLabel().
NormInf()
virtual double MLAPI::EpetraBaseOperator::NormInf () const inline virtual
NOT IMPLEMENTED.
Implements Epetra_Operator.
OperatorDomainMap()
virtual const Epetra_Map & MLAPI::EpetraBaseOperator::OperatorDomainMap () const inline virtual
Returns a reference to the OperatorDomainMap.
Implements Epetra_Operator.
OperatorRangeMap()
virtual const Epetra_Map & MLAPI::EpetraBaseOperator::OperatorRangeMap () const inline virtual
Returns a reference to the OperatorRangeMap.
Implements Epetra_Operator.
SetUseTranspose()
virtual int MLAPI::EpetraBaseOperator::SetUseTranspose (bool) inline virtual
Sets the use of tranpose (NOT IMPLEMENTED).
Implements Epetra_Operator.
UseTranspose()
virtual bool MLAPI::EpetraBaseOperator::UseTranspose () const inline virtual
Returns false.
Implements Epetra_Operator.
The documentation for this class was generated from the following file:
MLAPI_EpetraBaseOperator.h