ML: MLAPI::MultiLevelSA Class Reference
MLAPI::MultiLevelSA Class Reference
Black-box multilevel smoothed aggregation preconditioner.
#include <MLAPI_MultiLevelSA.h>
Public Member Functions
MultiLevelSA (const Operator &FineMatrix, Teuchos::ParameterList &List, const bool ConstructNow=true)
Constructs the hierarchy for given Operator and parameters.
virtual ~MultiLevelSA ()
Destructor.
const Space GetOperatorDomainSpace () const
Returns a copy of the internally stored domain space.
const Space GetOperatorRangeSpace () const
Returns a copy of the internally stored range space.
const Space GetDomainSpace () const
Returns a copy of the internally stored domain space.
const Space GetRangeSpace () const
Returns a copy of the internally stored range space.
const Operator & R (const int i) const
Returns a reference to the restriction operator of level i.
const Operator & A (const int i) const
Returns a reference to the operator of level i.
const Operator & P (const int i) const
Returns a reference to the prolongator operator of level i.
const InverseOperator & S (const int i) const
Returns a reference to the inverse operator of level i.
int GetMaxLevels () const
Returns the actual number of levels.
bool IsComputed () const
Returns true if the hierarchy has been successfully computed, false otherwise.
void Compute ()
Computes the hierarchy.
int Apply (const MultiVector &b_f, MultiVector &x_f) const
Applies the preconditioner to b_f, returns the result in x_f.
int SolveMultiLevelSA (const MultiVector &b_f, MultiVector &x_f, int level) const
Recursively called core of the multi level preconditioner.
std::ostream & Print (std::ostream &os, const bool verbose=true) const
Prints basic information about this preconditioner.
Public Member Functions inherited from MLAPI::BaseOperator
virtual ~BaseOperator ()
Virtual destructor.
Public Member Functions inherited from MLAPI::BaseObject
BaseObject ()
Constructor with empty label.
BaseObject (const std::string &Label)
Constructor with given Label.
virtual ~BaseObject ()
Destructor.
void SetLabel (const std::string &Label)
Sets the Label of this object to Label.
const std::string & GetLabel () const
Returns the Label of this object.
Public Member Functions inherited from MLAPI::CompObject
CompObject ()
Constructor, set counter to 0.0.
~CompObject ()
Destructor.
double GetFlops () const
Returns the internal counter of flops.
void SetFlops (double Flops) const
Sets internal counter to Flops.
void UpdateFlops (double Flops) const
Updates internal counter by summing Flops.
Public Member Functions inherited from MLAPI::TimeObject
TimeObject ()
Constructor, set counter to 0.0.
~TimeObject ()
Destructor.
void ResetTimer () const
Resets the internal timer.
void UpdateTime () const
Updates the internal timer with the time spent since the last call to ResetTimer().
void UpdateTime (double t) const
Updates the internal timer with input value t.
double GetTime () const
Returns the internally stored counter.
Additional Inherited Members
Protected Attributes inherited from MLAPI::TimeObject
Epetra_Time Time_
Object used to track time.
double TotalTime_
Internal counter.
Detailed Description
Black-box multilevel smoothed aggregation preconditioner.
Author
Marzio Sala, SNL 9214
Date
Last updated on Feb-05.
Member Function Documentation
Apply()
int MLAPI::MultiLevelSA::Apply (const MultiVector & b_f, MultiVector & x_f) const inline virtual
Applies the preconditioner to b_f, returns the result in x_f.
Implements MLAPI::BaseOperator.
References IsComputed(), MLAPI::TimeObject::ResetTimer(), SolveMultiLevelSA(), and MLAPI::TimeObject::UpdateTime().
GetOperatorDomainSpace()
const Space MLAPI::MultiLevelSA::GetOperatorDomainSpace () const inline virtual
Returns a copy of the internally stored domain space.
Implements MLAPI::BaseOperator.
References MLAPI::Operator::GetDomainSpace().
GetOperatorRangeSpace()
const Space MLAPI::MultiLevelSA::GetOperatorRangeSpace () const inline virtual
Returns a copy of the internally stored range space.
Implements MLAPI::BaseOperator.
References MLAPI::Operator::GetRangeSpace().
Print()
std::ostream & MLAPI::MultiLevelSA::Print (std::ostream & os, const bool verbose = true) const inline virtual
Prints basic information about this preconditioner.
Implements MLAPI::BaseObject.
References MLAPI::CompObject::GetFlops(), MLAPI::BaseObject::GetLabel(), GetMaxLevels(), MLAPI::GetMyPID(), and MLAPI::TimeObject::GetTime().
The documentation for this class was generated from the following file:
MLAPI_MultiLevelSA.h