ML: MLAPI::BaseOperator Class Reference
MLAPI::BaseOperator Class Reference abstract
Base class for all MLAPI objects.
#include <MLAPI_BaseOperator.h>
Public Member Functions
virtual ~BaseOperator ()
Virtual destructor.
virtual int Apply (const MultiVector &LHS, MultiVector &RHS) const =0
Applies the operator to X, using Y as starting solution. Returns the solution in Y.
virtual const Space GetOperatorDomainSpace () const =0
Returns a copy of the domain space of this object.
virtual const Space GetOperatorRangeSpace () const =0
Returns a copy of the range space of this object.
Public Member Functions inherited from MLAPI::BaseObject
BaseObject ()
Constructor with empty label.
BaseObject (const std::string &Label)
Constructor with given Label.
virtual ~BaseObject ()
Destructor.
void SetLabel (const std::string &Label)
Sets the Label of this object to Label.
const std::string & GetLabel () const
Returns the Label of this object.
virtual std::ostream & Print (std::ostream &os, const bool Verbose=true) const =0
Prints information on stream.
Detailed Description
Base class for all MLAPI objects.
Author
Marzio Sala, SNL 9214.
Date
Last modified on Feb-05.
Member Function Documentation
Apply()
virtual int MLAPI::BaseOperator::Apply (const MultiVector & LHS, MultiVector & RHS) const pure virtual
Applies the operator to X, using Y as starting solution. Returns the solution in Y.
Implemented in MLAPI::MultiLevelAdaptiveSA, MLAPI::MultiLevelSA, MLAPI::DistributedMatrix, MLAPI::InverseOperator, MLAPI::LoadBalanceInverseOperator, MLAPI::LoadBalanceOperator, and MLAPI::Operator.
Referenced by MLAPI::EpetraBaseOperator::Apply().
GetOperatorDomainSpace()
virtual const Space MLAPI::BaseOperator::GetOperatorDomainSpace () const pure virtual
Returns a copy of the domain space of this object.
Implemented in MLAPI::InverseOperator, MLAPI::LoadBalanceInverseOperator, MLAPI::LoadBalanceOperator, MLAPI::MultiLevelAdaptiveSA, MLAPI::MultiLevelSA, and MLAPI::Operator.
Referenced by MLAPI::EpetraBaseOperator::Apply().
GetOperatorRangeSpace()
virtual const Space MLAPI::BaseOperator::GetOperatorRangeSpace () const pure virtual
Returns a copy of the range space of this object.
Implemented in MLAPI::InverseOperator, MLAPI::LoadBalanceInverseOperator, MLAPI::LoadBalanceOperator, MLAPI::MultiLevelAdaptiveSA, MLAPI::MultiLevelSA, and MLAPI::Operator.
Referenced by MLAPI::EpetraBaseOperator::Apply().
The documentation for this class was generated from the following file:
MLAPI_BaseOperator.h