ML: MLAPI::Space Class Reference
MLAPI::Space Class Reference
Specifies the number and distribution among processes of elements.
#include <MLAPI_Space.h>
Public Member Functions
Space ()
Default constructor, defines an empty space.
Space (const int NumGlobalElements, const int NumMyElements=-1)
Constructor with specified number of global and local elements.
Space (const Epetra_Map &Map)
Constructor with specified Epetra_Map.
Space (const int NumGlobalElements, const int NumMyElements, const int *MyGlobalElements)
Constructor for non-linear distributions.
Space (const Space &RHS)
Copy constructor.
~Space ()
Destructor.
void Reshape ()
Resets this object.
void Reshape (const int NumGlobalElements, const int NumMyElements=-1)
Resets the dimension of the space by specifying the local number of elements.
void Reshape (const int NumGlobalElements, const int NumMyElements, const int *MyGlobalElements)
Reset the dimension of the space by specifying the local number of elements and their global numbering (starting from 0).
Space & operator= (const Space &RHS)
Operator =.
bool operator== (const Space &RHS) const
Returns true if this Space is equivalent to RHS.
bool operator!= (const Space &RHS) const
Returns true if this Space is not equivalent to RHS.
Space & operator= (const std::string &Label)
Sets the Label of this object.
int operator() (int i) const
Returns the global ID of local element i.
int GetNumMyElements () const
Returns the local number of elements on the calling process.
int GetNumGlobalElements () const
Returns the global number of elements.
int GetOffset () const
Returns the global ID of the first element on the calling process (for linear distributions only).
bool IsLinear () const
Returns true if the decomposition among processors is linear.
const Teuchos::RefCountPtr< Epetra_IntSerialDenseVector > GetRCPMyGlobalElements () const
Returns a pointer to the list of global nodes.
std::ostream & Print (std::ostream &os, const bool verbose=true) const
Prints on std::ostream basic information about this object.
Public Member Functions inherited from MLAPI::BaseObject
BaseObject ()
Constructor with empty label.
BaseObject (const std::string &Label)
Constructor with given Label.
virtual ~BaseObject ()
Destructor.
void SetLabel (const std::string &Label)
Sets the Label of this object to Label.
const std::string & GetLabel () const
Returns the Label of this object.
Detailed Description
Specifies the number and distribution among processes of elements.
Author
Marzio Sala, SNL 9214
Date
Last updated on Feb-05.
Constructor & Destructor Documentation
Space() [1/2]
MLAPI::Space::Space (const int NumGlobalElements, const int NumMyElements = -1) inline
Constructor with specified number of global and local elements.
Constructs a space with linear distribution.
Parameters
NumGlobalElements - (In) number of global elements.
NumMyElements - (In) number of local elements. If different from -1, then eithere NumGlobalElements == -1, or the sum across of processors of NumMyElements equals NumGlobalElements
References Reshape().
Space() [2/2]
MLAPI::Space::Space (const int NumGlobalElements, const int NumMyElements, const int * MyGlobalElements) inline
Constructor for non-linear distributions.
Parameters
NumGlobalElements - (In) number of global elements. Set to -1 to compute it automatically.
NumMyElements - (In) number of local elements. Cannot be set to -1.
MyGlobalElements - (In) contains the global ID of each local node.
Note
Global ID always starts from 0.
References Reshape().
Member Function Documentation
Print()
std::ostream & MLAPI::Space::Print (std::ostream & os, const bool verbose = true) const inline virtual
Prints on std::ostream basic information about this object.
Implements MLAPI::BaseObject.
References MLAPI::Barrier(), MLAPI::BaseObject::GetLabel(), MLAPI::GetMyPID(), GetNumGlobalElements(), GetNumMyElements(), MLAPI::GetNumProcs(), GetOffset(), and IsLinear().
The documentation for this class was generated from the following file:
MLAPI_Space.h