Epetra: Epetra_LongLongSerialDenseMatrix Class Reference
Epetra_LongLongSerialDenseMatrix Class Reference
Epetra_LongLongSerialDenseMatrix: A class for constructing and using general dense integer matrices.
#include <Epetra_LongLongSerialDenseMatrix.h>
Public Member Functions
Constructor/Destructor Methods
Epetra_LongLongSerialDenseMatrix ()
Default constructor; defines a zero size object.
Epetra_LongLongSerialDenseMatrix (int NumRows, int NumCols)
Shaped constructor; defines a variable-sized object.
Epetra_LongLongSerialDenseMatrix (Epetra_DataAccess CV, long long *A, int LDA, int NumRows, int NumCols)
Set object values from two-dimensional array.
Epetra_LongLongSerialDenseMatrix (const Epetra_LongLongSerialDenseMatrix &Source)
Epetra_LongLongSerialDenseMatrix copy constructor.
virtual ~Epetra_LongLongSerialDenseMatrix ()
Epetra_LongLongSerialDenseMatrix destructor.
Shaping/sizing Methods
int Shape (int NumRows, int NumCols)
Set dimensions of a Epetra_LongLongSerialDenseMatrix object; init values to zero.
int Reshape (int NumRows, int NumCols)
Reshape a Epetra_LongLongSerialDenseMatrix object.
Data Accessor methods
virtual long long OneNorm ()
Computes the 1-Norm of the this matrix.
virtual long long InfNorm ()
Computes the Infinity-Norm of the this matrix.
Epetra_LongLongSerialDenseMatrix & operator= (const Epetra_LongLongSerialDenseMatrix &Source)
Copy from one matrix to another.
bool operator== (const Epetra_LongLongSerialDenseMatrix &rhs) const
Comparison operator.
bool operator!= (const Epetra_LongLongSerialDenseMatrix &rhs) const
Inequality operator.
long long & operator() (int RowIndex, int ColIndex)
Element access function.
const long long & operator() (int RowIndex, int ColIndex) const
Element access function.
long long * operator[] (int ColIndex)
Column access function.
const long long * operator[] (int ColIndex) const
Column access function.
int Random ()
Set matrix values to random numbers.
int M () const
Returns row dimension of system.
int N () const
Returns column dimension of system.
const long long * A () const
Returns const pointer to the this matrix.
long long * A ()
Returns pointer to the this matrix.
int LDA () const
Returns the leading dimension of the this matrix.
Epetra_DataAccess CV () const
Returns the data access mode of the this matrix.
I/O methods
virtual void Print (std::ostream &os) const
Print service methods; defines behavior of ostream << operator.
Public Member Functions inherited from Epetra_Object
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object Constructor.
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object Constructor.
Epetra_Object (const Epetra_Object &Object)
Epetra_Object Copy Constructor.
virtual ~Epetra_Object ()
Epetra_Object Destructor.
virtual int ReportError (const std::string Message, int ErrorCode) const
Error reporting method.
virtual void SetLabel (const char *const Label)
Epetra_Object Label definition using char *.
virtual const char * Label () const
Epetra_Object Label access funtion.
Expert-only unsupported methods
Epetra_DataAccess CV_
bool A_Copied_
int M_
int N_
int LDA_
long long * A_
int MakeViewOf (const Epetra_LongLongSerialDenseMatrix &Source)
Reset an existing LongLongSerialDenseMatrix to point to another Matrix.
void CopyMat (long long *Source, int Source_LDA, int NumRows, int NumCols, long long *Target, int Target_LDA)
void CleanupData ()
Additional Inherited Members
Static Public Member Functions inherited from Epetra_Object
static void SetTracebackMode (int TracebackModeValue)
Set the value of the Epetra_Object error traceback report mode.
static int GetTracebackMode ()
Get the value of the Epetra_Object error report mode.
static std::ostream & GetTracebackStream ()
Get the output stream for error reporting.
Static Public Attributes inherited from Epetra_Object
static int TracebackMode
Protected Member Functions inherited from Epetra_Object
std::string toString (const int &x) const
std::string toString (const long long &x) const
std::string toString (const double &x) const
Detailed Description
Epetra_LongLongSerialDenseMatrix: A class for constructing and using general dense integer matrices.
The Epetra_LongLongSerialDenseMatrix class enables the construction and use of integer-valued, general dense matrices.
The Epetra_LongLongSerialDenseMatrix class is intended to provide very basic support for dense rectangular matrices.
Constructing Epetra_LongLongSerialDenseMatrix Objects
There are four Epetra_LongLongSerialDenseMatrix constructors. The first constructs a zero-sized object which should be made to appropriate length using the Shape() or Reshape() functions and then filled with the [] or () operators. The second constructs an object sized to the dimensions specified, which should be filled with the [] or () operators. The third is a constructor that accepts user data as a 2D array, and the fourth is a copy constructor. The third constructor has two data access modes (specified by the Epetra_DataAccess argument):
Copy mode - Allocates memory and makes a copy of the user-provided data. In this case, the user data is not needed after construction.
View mode - Creates a "view" of the user data. In this case, the user data is required to remain intact for the life of the object.
Warning
View mode is extremely dangerous from a data hiding perspective. Therefore, we strongly encourage users to develop code using Copy mode first and only use the View mode in a secondary optimization phase.
Epetra_LongLongSerialDenseMatrix constructors will throw an exception if an error occurrs. These exceptions will alway be negative integer values as follows:
-1 Invalid dimension specified.
-2 Shape returned non-zero.
-3 Null pointer specified for user's data.
-99 Internal Epetra_LongLongSerialDenseMatrix error. Contact developer.
Other Epetra_LongLongSerialDenseMatrix functions that do not return an integer error code (such as operators () and []) will throw an exception if an error occurrs. These exceptions will be integer values as follows:
-1 Invalid row specified.
-2 Invalid column specified.
-5 Invalid assignment (type mismatch).
-99 Internal Epetra_LongLongSerialDenseMatrix error. Contact developer.
bExtracting Data from Epetra_LongLongSerialDenseMatrix Objects
Once a Epetra_LongLongSerialDenseMatrix is constructed, it is possible to view the data via access functions.
Warning
Use of these access functions cam be extremely dangerous from a data hiding perspective.
Vector and Utility Functions
Once a Epetra_LongLongSerialDenseMatrix is constructed, several mathematical functions can be applied to the object. Specifically:
Multiplication.
Norms.
Constructor & Destructor Documentation
Epetra_LongLongSerialDenseMatrix() [1/4]
Epetra_LongLongSerialDenseMatrix::Epetra_LongLongSerialDenseMatrix ()
Default constructor; defines a zero size object.
Epetra_LongLongSerialDenseMatrix objects defined by the default constructor should be sized with the Shape() or Reshape functions. Values should be defined by using the [] or () operators.
Epetra_LongLongSerialDenseMatrix() [2/4]
Epetra_LongLongSerialDenseMatrix::Epetra_LongLongSerialDenseMatrix (int NumRows, int NumCols)
Shaped constructor; defines a variable-sized object.
Parameters
In NumRows - Number of rows in object.
In NumCols - Number of columns in object.
Epetra_SerialDenseMatrix objects defined by the shaped constructor are already shaped to the dimensions given as a parameters. All values are initialized to 0. Calling this constructor is equivalent to using the default constructor, and then calling the Shape function on it. Values should be defined by using the [] or () operators.
Epetra_LongLongSerialDenseMatrix() [3/4]
Epetra_LongLongSerialDenseMatrix::Epetra_LongLongSerialDenseMatrix (Epetra_DataAccess CV, long long * A, int LDA, int NumRows, int NumCols)
Set object values from two-dimensional array.
Parameters
In Epetra_DataAccess - Enumerated type set to Copy or View.
In A - Pointer to an array of integer numbers. The first vector starts at A. The second vector starts at A+LDA, the third at A+2*LDA, and so on.
In LDA - The "Leading Dimension", or stride between vectors in memory.
In NumRows - Number of rows in object.
In NumCols - Number of columns in object.
See Detailed Description section for further discussion.
Epetra_LongLongSerialDenseMatrix() [4/4]
Epetra_LongLongSerialDenseMatrix::Epetra_LongLongSerialDenseMatrix (const Epetra_LongLongSerialDenseMatrix & Source)
Epetra_LongLongSerialDenseMatrix copy constructor.
This matrix will take on the data access mode of the Source matrix.
Member Function Documentation
MakeViewOf()
int Epetra_LongLongSerialDenseMatrix::MakeViewOf (const Epetra_LongLongSerialDenseMatrix & Source)
Reset an existing LongLongSerialDenseMatrix to point to another Matrix.
Allows an existing LongLongSerialDenseMatrix to become a View of another matrix's data, regardless of the DataAccess mode of the Source matrix. It is assumed that the Source matrix is an independent matrix, and no checking is done to verify this.
This is used by Epetra_CrsGraph in the OptimizeStorage method. It is used so that an existing (Copy) matrix can be converted to a View. This frees up memory that CrsGraph no longer needs.
Parameters
Source The LongLongSerialDenseMatrix this will become a view of.
Returns
Integer error code, set to 0 if successful, and set to -1 if a type mismatch occured.
Warning
This method is extremely dangerous and should only be used by experts.
OneNorm()
virtual long long Epetra_LongLongSerialDenseMatrix::OneNorm () virtual
Computes the 1-Norm of the this matrix.
Returns
Integer error code, set to 0 if successful.
operator!=()
bool Epetra_LongLongSerialDenseMatrix::operator!= (const Epetra_LongLongSerialDenseMatrix & rhs) const inline
Inequality operator.
operator!= simply returns the negation of operator==.
operator()() [1/2]
long long & Epetra_LongLongSerialDenseMatrix::operator() (int RowIndex, int ColIndex) inline
Element access function.
The parentheses operator returns the element in the ith row and jth column if A(i,j) is specified, the expression A[j][i] (note that i and j are reversed) will return the same element. Thus, A(i,j) = A[j][i] for all valid i and j.
Returns
Element from the specified row and column.
Warning
No bounds checking is done unless Epetra is compiled with HAVE_EPETRA_ARRAY_BOUNDS_CHECK.
References Epetra_Object::ReportError().
operator()() [2/2]
const long long & Epetra_LongLongSerialDenseMatrix::operator() (int RowIndex, int ColIndex) const inline
Element access function.
The parentheses operator returns the element in the ith row and jth column if A(i,j) is specified, the expression A[j][i] (note that i and j are reversed) will return the same element. Thus, A(i,j) = A[j][i] for all valid i and j.
Returns
Element from the specified row and column.
Warning
No bounds checking is done unless Epetra is compiled with HAVE_EPETRA_ARRAY_BOUNDS_CHECK.
References Epetra_Object::ReportError().
operator=()
Epetra_LongLongSerialDenseMatrix & Epetra_LongLongSerialDenseMatrix::operator= (const Epetra_LongLongSerialDenseMatrix & Source)
Copy from one matrix to another.
The operator= allows one to copy the values from one existing LongLongSerialDenseMatrix to another. The left hand side matrix will take on the data access mode of the right hand side matrix.
Returns
Values of the left hand side matrix are modified by the values of the right hand side matrix.
operator==()
bool Epetra_LongLongSerialDenseMatrix::operator== (const Epetra_LongLongSerialDenseMatrix & rhs) const
Comparison operator.
operator== compares two Epetra_LongLongSerialDenseMatrix objects, returns false if sizes are different, or if any coefficients differ.
operator[]() [1/2]
long long * Epetra_LongLongSerialDenseMatrix::operator[] (int ColIndex) inline
Column access function.
The parentheses operator returns the element in the ith row and jth column if A(i,j) is specified, the expression A[j][i] (note that i and j are reversed) will return the same element. Thus, A(i,j) = A[j][i] for all valid i and j.
Returns
Pointer to address of specified column.
Warning
No bounds checking can be done for the index i in the expression A[j][i].
No bounds checking is done unless Epetra is compiled with HAVE_EPETRA_ARRAY_BOUNDS_CHECK.
References Epetra_Object::ReportError().
operator[]() [2/2]
const long long * Epetra_LongLongSerialDenseMatrix::operator[] (int ColIndex) const inline
Column access function.
The parentheses operator returns the element in the ith row and jth column if A(i,j) is specified, the expression A[j][i] (note that i and j are reversed) will return the same element. Thus, A(i,j) = A[j][i] for all valid i and j.
Returns
Pointer to address of specified column.
Warning
No bounds checking can be done for the index i in the expression A[j][i].
No bounds checking is done unless Epetra is compiled with HAVE_EPETRA_ARRAY_BOUNDS_CHECK.
References Epetra_Object::ReportError().
Print()
virtual void Epetra_LongLongSerialDenseMatrix::Print (std::ostream & os) const virtual
Print service methods; defines behavior of ostream << operator.
Reimplemented from Epetra_Object.
Reimplemented in Epetra_LongLongSerialDenseVector.
Random()
int Epetra_LongLongSerialDenseMatrix::Random ()
Set matrix values to random numbers.
LongLongSerialDenseMatrix uses the random number generator provided by Epetra_Util. The matrix values will be set to random values on the interval (0, 2^31 - 1).
Returns
Integer error code, set to 0 if successful.
Reshape()
int Epetra_LongLongSerialDenseMatrix::Reshape (int NumRows, int NumCols)
Reshape a Epetra_LongLongSerialDenseMatrix object.
Parameters
In NumRows - Number of rows in object.
In NumCols - Number of columns in object.
Allows user to define the dimensions of a Epetra_LongLongSerialDenseMatrix at any point. This function can be called at any point after construction. Any values that were previously in this object are copied into the new shape. If the new shape is smaller than the original, the upper left portion of the original matrix (the principal submatrix) is copied to the new matrix.
Returns
Integer error code, set to 0 if successful.
Referenced by Epetra_LongLongSerialDenseVector::Resize().
Shape()
int Epetra_LongLongSerialDenseMatrix::Shape (int NumRows, int NumCols)
Set dimensions of a Epetra_LongLongSerialDenseMatrix object; init values to zero.
Parameters
In NumRows - Number of rows in object.
In NumCols - Number of columns in object.
Allows user to define the dimensions of a Epetra_LongLongSerialDenseMatrix at any point. This function can be called at any point after construction. Any values that were previously in this object are destroyed and the resized matrix starts off with all zero values.
Returns
Integer error code, set to 0 if successful.
Referenced by Epetra_LongLongSerialDenseVector::Size().
The documentation for this class was generated from the following file:
Epetra_LongLongSerialDenseMatrix.h