Epetra: Epetra_SerialComm Class Reference
Epetra_SerialComm Class Reference
Epetra_SerialComm: The Epetra Serial Communication Class.
#include <Epetra_SerialComm.h>
Public Member Functions
Constructor/Destructor Methods
Epetra_SerialComm ()
Epetra_SerialComm Serial Constructor.
Epetra_SerialComm (const Epetra_SerialComm &Comm)
Epetra_SerialComm Copy Constructor.
Epetra_Comm * Clone () const
Clone method.
virtual ~Epetra_SerialComm ()
Epetra_SerialComm Destructor.
Barrier Methods
void Barrier () const
Epetra_SerialComm Barrier function.
Broadcast Methods
int Broadcast (double *MyVals, int Count, int Root) const
Epetra_SerialComm Broadcast function.
int Broadcast (int *MyVals, int Count, int Root) const
Epetra_SerialComm Broadcast function.
int Broadcast (long *MyVals, int Count, int Root) const
Epetra_SerialComm Broadcast function.
int Broadcast (long long *MyVals, int Count, int Root) const
Epetra_SerialComm Broadcast function.
int Broadcast (char *MyVals, int Count, int Root) const
Epetra_SerialComm Broadcast function.
Gather Methods
int GatherAll (double *MyVals, double *AllVals, int Count) const
Epetra_SerialComm All Gather function.
int GatherAll (int *MyVals, int *AllVals, int Count) const
Epetra_SerialComm All Gather function.
int GatherAll (long *MyVals, long *AllVals, int Count) const
Epetra_SerialComm All Gather function.
int GatherAll (long long *MyVals, long long *AllVals, int Count) const
Epetra_SerialComm All Gather function.
Sum Methods
int SumAll (double *PartialSums, double *GlobalSums, int Count) const
Epetra_SerialComm Global Sum function.
int SumAll (int *PartialSums, int *GlobalSums, int Count) const
Epetra_SerialComm Global Sum function.
int SumAll (long *PartialSums, long *GlobalSums, int Count) const
Epetra_SerialComm Global Sum function.
int SumAll (long long *PartialSums, long long *GlobalSums, int Count) const
Epetra_SerialComm Global Sum function.
Max/Min Methods
int MaxAll (double *PartialMaxs, double *GlobalMaxs, int Count) const
Epetra_SerialComm Global Max function.
int MaxAll (int *PartialMaxs, int *GlobalMaxs, int Count) const
Epetra_SerialComm Global Max function.
int MaxAll (long *PartialMaxs, long *GlobalMaxs, int Count) const
Epetra_SerialComm Global Max function.
int MaxAll (long long *PartialMaxs, long long *GlobalMaxs, int Count) const
Epetra_SerialComm Global Max function.
int MinAll (double *PartialMins, double *GlobalMins, int Count) const
Epetra_SerialComm Global Min function.
int MinAll (int *PartialMins, int *GlobalMins, int Count) const
Epetra_SerialComm Global Min function.
int MinAll (long *PartialMins, long *GlobalMins, int Count) const
Epetra_SerialComm Global Min function.
int MinAll (long long *PartialMins, long long *GlobalMins, int Count) const
Epetra_SerialComm Global Min function.
Parallel Prefix Methods
int ScanSum (double *MyVals, double *ScanSums, int Count) const
Epetra_SerialComm Scan Sum function.
int ScanSum (int *MyVals, int *ScanSums, int Count) const
Epetra_SerialComm Scan Sum function.
int ScanSum (long *MyVals, long *ScanSums, int Count) const
Epetra_SerialComm Scan Sum function.
int ScanSum (long long *MyVals, long long *ScanSums, int Count) const
Epetra_SerialComm Scan Sum function.
Attribute Accessor Methods
int MyPID () const
Return my process ID.
int NumProc () const
Returns total number of processes (always returns 1 for SerialComm).
Gather/Scatter and Directory Constructors
Epetra_Distributor * CreateDistributor () const
Create a distributor object.
Epetra_Directory * CreateDirectory (const Epetra_BlockMap &Map) const
Create a directory object for the given Epetra_BlockMap.
Print object to an output stream
void Print (std::ostream &os) const
Print method that implements Epetra_Object virtual Print method.
void PrintInfo (std::ostream &os) const
Print method that implements Epetra_Comm virtual PrintInfo method.
Public Member Functions inherited from Epetra_Object
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object Constructor.
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object Constructor.
Epetra_Object (const Epetra_Object &Object)
Epetra_Object Copy Constructor.
virtual ~Epetra_Object ()
Epetra_Object Destructor.
virtual int ReportError (const std::string Message, int ErrorCode) const
Error reporting method.
virtual void SetLabel (const char *const Label)
Epetra_Object Label definition using char *.
virtual const char * Label () const
Epetra_Object Label access funtion.
Public Member Functions inherited from Epetra_Comm
virtual ~Epetra_Comm ()
Epetra_Comm Destructor.
Expert Users and Developers Only
int ReferenceCount () const
Returns the reference count of SerialCommData.
const Epetra_SerialCommData * DataPtr () const
Returns a pointer to the SerialCommData instance this SerialComm uses.
Epetra_SerialComm & operator= (const Epetra_SerialComm &Comm)
Assignment Operator.
Additional Inherited Members
Static Public Member Functions inherited from Epetra_Object
static void SetTracebackMode (int TracebackModeValue)
Set the value of the Epetra_Object error traceback report mode.
static int GetTracebackMode ()
Get the value of the Epetra_Object error report mode.
static std::ostream & GetTracebackStream ()
Get the output stream for error reporting.
Static Public Attributes inherited from Epetra_Object
static int TracebackMode
Protected Member Functions inherited from Epetra_Object
std::string toString (const int &x) const
std::string toString (const long long &x) const
std::string toString (const double &x) const
Detailed Description
Epetra_SerialComm: The Epetra Serial Communication Class.
The Epetra_SerialComm class is an implementation of Epetra_Comm, providing the general information and services needed for other Epetra classes to run on a serial computer.
Constructor & Destructor Documentation
Epetra_SerialComm() [1/2]
Epetra_SerialComm::Epetra_SerialComm ()
Epetra_SerialComm Serial Constructor.
Builds an instance of a serial communicator. Even if the application is running in parallel via MPI, this communicator will execute in serial. The access functions return the number of processors to be 1 and the processor ID to be 0.
Epetra_SerialComm() [2/2]
Epetra_SerialComm::Epetra_SerialComm (const Epetra_SerialComm & Comm)
Epetra_SerialComm Copy Constructor.
Makes an exact copy of an existing Epetra_SerialComm instance.
~Epetra_SerialComm()
virtual Epetra_SerialComm::~Epetra_SerialComm () virtual
Epetra_SerialComm Destructor.
Completely deletes a Epetra_SerialComm object.
Warning
Note: All objects that depend on a Epetra_SerialComm instance should be destroyed prior to calling this function.
Member Function Documentation
Barrier()
void Epetra_SerialComm::Barrier () const virtual
Epetra_SerialComm Barrier function.
A no-op for a serial communicator.
Implements Epetra_Comm.
Broadcast() [1/5]
int Epetra_SerialComm::Broadcast (char * MyVals, int Count, int Root) const virtual
Epetra_SerialComm Broadcast function.
A no-op for a serial communicator.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of MyVals.
Root In On entry, contains the processor from which all processors will receive a copy of MyVals.
Implements Epetra_Comm.
Broadcast() [2/5]
int Epetra_SerialComm::Broadcast (double * MyVals, int Count, int Root) const virtual
Epetra_SerialComm Broadcast function.
A no-op for a serial communicator.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of MyVals.
Root In On entry, contains the processor from which all processors will receive a copy of MyVals.
Implements Epetra_Comm.
Broadcast() [3/5]
int Epetra_SerialComm::Broadcast (int * MyVals, int Count, int Root) const virtual
Epetra_SerialComm Broadcast function.
A no-op for a serial communicator.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of MyVals.
Root In On entry, contains the processor from which all processors will receive a copy of MyVals.
Implements Epetra_Comm.
Broadcast() [4/5]
int Epetra_SerialComm::Broadcast (long * MyVals, int Count, int Root) const virtual
Epetra_SerialComm Broadcast function.
A no-op for a serial communicator.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of MyVals.
Root In On entry, contains the processor from which all processors will receive a copy of MyVals.
Implements Epetra_Comm.
Broadcast() [5/5]
int Epetra_SerialComm::Broadcast (long long * MyVals, int Count, int Root) const virtual
Epetra_SerialComm Broadcast function.
A no-op for a serial communicator.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of MyVals.
Root In On entry, contains the processor from which all processors will receive a copy of MyVals.
Implements Epetra_Comm.
Clone()
Epetra_Comm * Epetra_SerialComm::Clone () const inline virtual
Clone method.
Implements Epetra_Comm.
CreateDirectory()
Epetra_Directory * Epetra_SerialComm::CreateDirectory (const Epetra_BlockMap & Map) const virtual
Create a directory object for the given Epetra_BlockMap.
Implements Epetra_Comm.
CreateDistributor()
Epetra_Distributor * Epetra_SerialComm::CreateDistributor () const virtual
Create a distributor object.
Implements Epetra_Comm.
DataPtr()
const Epetra_SerialCommData * Epetra_SerialComm::DataPtr () const inline
Returns a pointer to the SerialCommData instance this SerialComm uses.
(Intended for developer use only for testing purposes.)
GatherAll() [1/4]
int Epetra_SerialComm::GatherAll (double * MyVals, double * AllVals, int Count) const virtual
Epetra_SerialComm All Gather function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values, to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must by of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implements Epetra_Comm.
GatherAll() [2/4]
int Epetra_SerialComm::GatherAll (int * MyVals, int * AllVals, int Count) const virtual
Epetra_SerialComm All Gather function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values, to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must by of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implements Epetra_Comm.
GatherAll() [3/4]
int Epetra_SerialComm::GatherAll (long * MyVals, long * AllVals, int Count) const virtual
Epetra_SerialComm All Gather function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values, to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must by of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implements Epetra_Comm.
GatherAll() [4/4]
int Epetra_SerialComm::GatherAll (long long * MyVals, long long * AllVals, int Count) const virtual
Epetra_SerialComm All Gather function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values, to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must by of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implements Epetra_Comm.
MaxAll() [1/4]
int Epetra_SerialComm::MaxAll (double * PartialMaxs, double * GlobalMaxs, int Count) const virtual
Epetra_SerialComm Global Max function.
A copy for a serial communicator.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally, using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MaxAll() [2/4]
int Epetra_SerialComm::MaxAll (int * PartialMaxs, int * GlobalMaxs, int Count) const virtual
Epetra_SerialComm Global Max function.
A copy for a serial communicator.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally; using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MaxAll() [3/4]
int Epetra_SerialComm::MaxAll (long * PartialMaxs, long * GlobalMaxs, int Count) const virtual
Epetra_SerialComm Global Max function.
A copy for a serial communicator.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally; using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MaxAll() [4/4]
int Epetra_SerialComm::MaxAll (long long * PartialMaxs, long long * GlobalMaxs, int Count) const virtual
Epetra_SerialComm Global Max function.
A copy for a serial communicator.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally; using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MinAll() [1/4]
int Epetra_SerialComm::MinAll (double * PartialMins, double * GlobalMins, int Count) const virtual
Epetra_SerialComm Global Min function.
A copy for a serial communicator.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MinAll() [2/4]
int Epetra_SerialComm::MinAll (int * PartialMins, int * GlobalMins, int Count) const virtual
Epetra_SerialComm Global Min function.
A copy for a serial communicator.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MinAll() [3/4]
int Epetra_SerialComm::MinAll (long * PartialMins, long * GlobalMins, int Count) const virtual
Epetra_SerialComm Global Min function.
A copy for a serial communicator.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MinAll() [4/4]
int Epetra_SerialComm::MinAll (long long * PartialMins, long long * GlobalMins, int Count) const virtual
Epetra_SerialComm Global Min function.
A copy for a serial communicator.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
MyPID()
int Epetra_SerialComm::MyPID () const inline virtual
Return my process ID.
In MPI mode returns the rank of the calling process. In serial mode returns 0.
Implements Epetra_Comm.
NumProc()
int Epetra_SerialComm::NumProc () const inline virtual
Returns total number of processes (always returns 1 for SerialComm).
Implements Epetra_Comm.
Print()
void Epetra_SerialComm::Print (std::ostream & os) const inline virtual
Print method that implements Epetra_Object virtual Print method.
Reimplemented from Epetra_Object.
References Epetra_Comm::MyPID(), and Epetra_Comm::NumProc().
Referenced by PrintInfo().
PrintInfo()
void Epetra_SerialComm::PrintInfo (std::ostream & os) const inline virtual
Print method that implements Epetra_Comm virtual PrintInfo method.
Implements Epetra_Comm.
References Print().
ReferenceCount()
int Epetra_SerialComm::ReferenceCount () const
Returns the reference count of SerialCommData.
(Intended for testing purposes.)
ScanSum() [1/4]
int Epetra_SerialComm::ScanSum (double * MyVals, double * ScanSums, int Count) const virtual
Epetra_SerialComm Scan Sum function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
ScanSum() [2/4]
int Epetra_SerialComm::ScanSum (int * MyVals, int * ScanSums, int Count) const virtual
Epetra_SerialComm Scan Sum function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
ScanSum() [3/4]
int Epetra_SerialComm::ScanSum (long * MyVals, long * ScanSums, int Count) const virtual
Epetra_SerialComm Scan Sum function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
ScanSum() [4/4]
int Epetra_SerialComm::ScanSum (long long * MyVals, long long * ScanSums, int Count) const virtual
Epetra_SerialComm Scan Sum function.
A copy for a serial communicator.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
SumAll() [1/4]
int Epetra_SerialComm::SumAll (double * PartialSums, double * GlobalSums, int Count) const virtual
Epetra_SerialComm Global Sum function.
A copy for a serial communicator.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
SumAll() [2/4]
int Epetra_SerialComm::SumAll (int * PartialSums, int * GlobalSums, int Count) const virtual
Epetra_SerialComm Global Sum function.
A copy for a serial communicator.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
SumAll() [3/4]
int Epetra_SerialComm::SumAll (long * PartialSums, long * GlobalSums, int Count) const virtual
Epetra_SerialComm Global Sum function.
A copy for a serial communicator.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
SumAll() [4/4]
int Epetra_SerialComm::SumAll (long long * PartialSums, long long * GlobalSums, int Count) const virtual
Epetra_SerialComm Global Sum function.
A copy for a serial communicator.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implements Epetra_Comm.
The documentation for this class was generated from the following file:
Epetra_SerialComm.h