Epetra: Epetra_VbrMatrix Class Reference
Epetra_VbrMatrix Class Reference
Epetra_VbrMatrix: A class for the construction and use of real-valued double-precision variable block-row sparse matrices.
#include <Epetra_VbrMatrix.h>
Public Member Functions
Constructors/Destructor
Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap &RowMap, int *NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with variable number of indices per row.
Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap &RowMap, int NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with fixed number of indices per row.
Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap &RowMap, const Epetra_BlockMap &ColMap, int *NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with variable number of indices per row.
Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap &RowMap, const Epetra_BlockMap &ColMap, int NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with fixed number of indices per row.
Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_CrsGraph &Graph)
Construct a matrix using an existing Epetra_CrsGraph object.
Epetra_VbrMatrix (const Epetra_VbrMatrix &Matrix)
Copy constructor.
virtual ~Epetra_VbrMatrix ()
Epetra_VbrMatrix Destructor.
Insertion/Replace/SumInto methods
Epetra_VbrMatrix & operator= (const Epetra_VbrMatrix &src)
int PutScalar (double ScalarConstant)
Initialize all values in graph of the matrix with constant value.
int Scale (double ScalarConstant)
Multiply all values in the matrix by a constant value (in place: A <- ScalarConstant * A).
int DirectSubmitBlockEntry (int GlobalBlockRow, int GlobalBlockCol, const double *values, int LDA, int NumRows, int NumCols, bool sum_into)
Submit a block-entry directly into the matrix (without using a begin/end sequence)
int BeginInsertGlobalValues (int BlockRow, int NumBlockEntries, int *BlockIndices)
Initiate insertion of a list of elements in a given global row of the matrix, values are inserted via SubmitEntry().
int BeginInsertMyValues (int BlockRow, int NumBlockEntries, int *BlockIndices)
Initiate insertion of a list of elements in a given local row of the matrix, values are inserted via SubmitEntry().
int BeginReplaceGlobalValues (int BlockRow, int NumBlockEntries, int *BlockIndices)
Initiate replacement of current values with this list of entries for a given global row of the matrix, values are replaced via SubmitEntry()
int BeginReplaceMyValues (int BlockRow, int NumBlockEntries, int *BlockIndices)
Initiate replacement of current values with this list of entries for a given local row of the matrix, values are replaced via SubmitEntry()
int BeginSumIntoGlobalValues (int BlockRow, int NumBlockEntries, int *BlockIndices)
Initiate summing into current values with this list of entries for a given global row of the matrix, values are replaced via SubmitEntry()
int BeginSumIntoMyValues (int BlockRow, int NumBlockEntries, int *BlockIndices)
Initiate summing into current values with this list of entries for a given local row of the matrix, values are replaced via SubmitEntry()
int SubmitBlockEntry (double *Values, int LDA, int NumRows, int NumCols)
Submit a block entry to the indicated block row and column specified in the Begin routine.
int SubmitBlockEntry (Epetra_SerialDenseMatrix &Mat)
Submit a block entry to the indicated block row and column specified in the Begin routine.
int EndSubmitEntries ()
Completes processing of all data passed in for the current block row.
int ReplaceDiagonalValues (const Epetra_Vector &Diagonal)
Replaces diagonal values of the with those in the user-provided vector.
int FillComplete ()
Signal that data entry is complete, perform transformations to local index space.
int FillComplete (const Epetra_BlockMap &DomainMap, const Epetra_BlockMap &RangeMap)
Signal that data entry is complete, perform transformations to local index space.
bool Filled () const
If FillComplete() has been called, this query returns true, otherwise it returns false.
Extraction methods
int ExtractGlobalBlockRowPointers (int BlockRow, int MaxNumBlockEntries, int &RowDim, int &NumBlockEntries, int *BlockIndices, Epetra_SerialDenseMatrix **&Values) const
Copy the block indices into user-provided array, set pointers for rest of data for specified global block row.
int ExtractMyBlockRowPointers (int BlockRow, int MaxNumBlockEntries, int &RowDim, int &NumBlockEntries, int *BlockIndices, Epetra_SerialDenseMatrix **&Values) const
Copy the block indices into user-provided array, set pointers for rest of data for specified local block row.
int BeginExtractGlobalBlockRowCopy (int BlockRow, int MaxNumBlockEntries, int &RowDim, int &NumBlockEntries, int *BlockIndices, int *ColDims) const
Initiates a copy of the specified global row in user-provided arrays.
int BeginExtractMyBlockRowCopy (int BlockRow, int MaxNumBlockEntries, int &RowDim, int &NumBlockEntries, int *BlockIndices, int *ColDims) const
Initiates a copy of the specified local row in user-provided arrays.
int ExtractEntryCopy (int SizeOfValues, double *Values, int LDA, bool SumInto) const
Extract a copy of an entry from the block row specified by one of the BeginExtract routines.
int BeginExtractGlobalBlockRowView (int BlockRow, int &RowDim, int &NumBlockEntries, int *&BlockIndices) const
Initiates a view of the specified global row, only works if matrix indices are in global mode.
int BeginExtractMyBlockRowView (int BlockRow, int &RowDim, int &NumBlockEntries, int *&BlockIndices) const
Initiates a view of the specified local row, only works if matrix indices are in local mode.
int ExtractEntryView (Epetra_SerialDenseMatrix *&entry) const
Returns a pointer to the current block entry.
int ExtractGlobalBlockRowView (int BlockRow, int &RowDim, int &NumBlockEntries, int *&BlockIndices, Epetra_SerialDenseMatrix **&Values) const
Initiates a view of the specified global row, only works if matrix indices are in global mode.
int ExtractMyBlockRowView (int BlockRow, int &RowDim, int &NumBlockEntries, int *&BlockIndices, Epetra_SerialDenseMatrix **&Values) const
Initiates a view of the specified local row, only works if matrix indices are in local mode.
int ExtractDiagonalCopy (Epetra_Vector &Diagonal) const
Returns a copy of the main diagonal in a user-provided vector.
int BeginExtractBlockDiagonalCopy (int MaxNumBlockDiagonalEntries, int &NumBlockDiagonalEntries, int *RowColDims) const
Initiates a copy of the block diagonal entries to user-provided arrays.
int ExtractBlockDiagonalEntryCopy (int SizeOfValues, double *Values, int LDA, bool SumInto) const
Extract a copy of a block diagonal entry from the matrix.
int BeginExtractBlockDiagonalView (int &NumBlockDiagonalEntries, int *&RowColDims) const
Initiates a view of the block diagonal entries.
int ExtractBlockDiagonalEntryView (double *&Values, int &LDA) const
Extract a view of a block diagonal entry from the matrix.
Computational methods
int Multiply1 (bool TransA, const Epetra_Vector &x, Epetra_Vector &y) const
Returns the result of a Epetra_VbrMatrix multiplied by a Epetra_Vector x in y.
int Multiply (bool TransA, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_VbrMatrix multiplied by a Epetra_MultiVector X in Y.
int Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_Vector &x, Epetra_Vector &y) const
Returns the result of a solve using the Epetra_VbrMatrix on a Epetra_Vector x in y.
int Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_VbrMatrix multiplied by a Epetra_MultiVector X in Y.
int InvRowSums (Epetra_Vector &x) const
Computes the sum of absolute values of the rows of the Epetra_VbrMatrix, results returned in x.
int LeftScale (const Epetra_Vector &x)
Scales the Epetra_VbrMatrix on the left with a Epetra_Vector x.
int InvColSums (Epetra_Vector &x) const
Computes the sum of absolute values of the columns of the Epetra_VbrMatrix, results returned in x.
int RightScale (const Epetra_Vector &x)
Scales the Epetra_VbrMatrix on the right with a Epetra_Vector x.
Matrix Properties Query Methods
int OptimizeStorage ()
Eliminates memory that is used for construction. Make consecutive row index sections contiguous.
bool StorageOptimized () const
If OptimizeStorage() has been called, this query returns true, otherwise it returns false.
bool IndicesAreGlobal () const
If matrix indices has not been transformed to local, this query returns true, otherwise it returns false.
bool IndicesAreLocal () const
If matrix indices has been transformed to local, this query returns true, otherwise it returns false.
bool IndicesAreContiguous () const
If matrix indices are packed into single array (done in OptimizeStorage()) return true, otherwise false.
bool LowerTriangular () const
If matrix is lower triangular in local index space, this query returns true, otherwise it returns false.
bool UpperTriangular () const
If matrix is upper triangular in local index space, this query returns true, otherwise it returns false.
bool NoDiagonal () const
If matrix has no diagonal entries based on global row/column index comparisons, this query returns true, otherwise it returns false.
Attribute access functions
double NormInf () const
Returns the infinity norm of the global matrix.
double NormOne () const
Returns the one norm of the global matrix.
double NormFrobenius () const
Returns the frobenius norm of the global matrix.
int MaxRowDim () const
Returns the maximum row dimension of all block entries on this processor.
int MaxColDim () const
Returns the maximum column dimension of all block entries on this processor.
int GlobalMaxRowDim () const
Returns the maximum row dimension of all block entries across all processors.
int GlobalMaxColDim () const
Returns the maximum column dimension of all block entries across all processors.
int NumMyRows () const
Returns the number of matrix rows owned by the calling processor.
int NumMyCols () const
Returns the number of matrix columns owned by the calling processor.
int NumMyNonzeros () const
Returns the number of nonzero entriesowned by the calling processor .
int NumGlobalRows () const
Returns the number of global matrix rows.
long long NumGlobalRows64 () const
int NumGlobalCols () const
Returns the number of global matrix columns.
long long NumGlobalCols64 () const
int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global matrix.
long long NumGlobalNonzeros64 () const
int NumMyBlockRows () const
Returns the number of Block matrix rows owned by the calling processor.
int NumMyBlockCols () const
Returns the number of Block matrix columns owned by the calling processor.
int NumMyBlockEntries () const
Returns the number of nonzero block entries in the calling processor's portion of the matrix.
int NumMyBlockDiagonals () const
Returns the number of local nonzero block diagonal entries, based on global row/column index comparisons.
int NumMyDiagonals () const
Returns the number of local nonzero diagonal entries, based on global row/column index comparisons.
int NumGlobalBlockRows () const
Returns the number of global Block matrix rows.
long long NumGlobalBlockRows64 () const
int NumGlobalBlockCols () const
Returns the number of global Block matrix columns.
long long NumGlobalBlockCols64 () const
int NumGlobalBlockEntries () const
Returns the number of nonzero block entries in the global matrix.
long long NumGlobalBlockEntries64 () const
int NumGlobalBlockDiagonals () const
Returns the number of global nonzero block diagonal entries, based on global row/column index comparisions.
long long NumGlobalBlockDiagonals64 () const
int NumGlobalDiagonals () const
Returns the number of global nonzero diagonal entries, based on global row/column index comparisions.
long long NumGlobalDiagonals64 () const
int NumGlobalBlockEntries (int Row) const
Returns the current number of nonzero Block entries in specified global row on this processor.
int NumAllocatedGlobalBlockEntries (int Row) const
Returns the allocated number of nonzero Block entries in specified global row on this processor.
int MaxNumBlockEntries () const
Returns the maximum number of nonzero entries across all rows on this processor.
int GlobalMaxNumBlockEntries () const
Returns the maximum number of nonzero entries across all rows on this processor.
int NumMyBlockEntries (int Row) const
Returns the current number of nonzero Block entries in specified local row on this processor.
int NumAllocatedMyBlockEntries (int Row) const
Returns the allocated number of nonzero Block entries in specified local row on this processor.
int MaxNumNonzeros () const
Returns the maximum number of nonzero entries across all block rows on this processor.
int GlobalMaxNumNonzeros () const
Returns the maximum number of nonzero entries across all block rows on all processors.
int IndexBase () const
Returns the index base for row and column indices for this graph.
long long IndexBase64 () const
const Epetra_CrsGraph & Graph () const
Returns a pointer to the Epetra_CrsGraph object associated with this matrix.
const Epetra_Import * Importer () const
Returns the Epetra_Import object that contains the import operations for distributed operations.
const Epetra_Export * Exporter () const
Returns the Epetra_Export object that contains the export operations for distributed operations.
const Epetra_BlockMap & DomainMap () const
Returns the Epetra_BlockMap object associated with the domain of this matrix operator.
const Epetra_BlockMap & RangeMap () const
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
const Epetra_BlockMap & RowMap () const
Returns the RowMap object as an Epetra_BlockMap (the Epetra_Map base class) needed for implementing Epetra_RowMatrix.
const Epetra_BlockMap & ColMap () const
Returns the ColMap as an Epetra_BlockMap (the Epetra_Map base class) needed for implementing Epetra_RowMatrix.
const Epetra_Comm & Comm () const
Fills a matrix with rows from a source matrix based on the specified importer.
Local/Global ID methods
int LRID (int GRID_in) const
Returns the local row index for given global row index, returns -1 if no local row for this global row.
int LRID (long long GRID_in) const
int GRID (int LRID_in) const
Returns the global row index for give local row index, returns IndexBase-1 if we don't have this local row.
long long GRID64 (int LRID_in) const
int LCID (int GCID_in) const
Returns the local column index for given global column index, returns -1 if no local column for this global column.
int LCID (long long GCID_in) const
int GCID (int LCID_in) const
Returns the global column index for give local column index, returns IndexBase-1 if we don't have this local column.
long long GCID64 (int LCID_in) const
bool MyGRID (int GRID_in) const
Returns true if the GRID passed in belongs to the calling processor in this map, otherwise returns false.
bool MyGRID (long long GRID_in) const
bool MyLRID (int LRID_in) const
Returns true if the LRID passed in belongs to the calling processor in this map, otherwise returns false.
bool MyGCID (int GCID_in) const
Returns true if the GCID passed in belongs to the calling processor in this map, otherwise returns false.
bool MyGCID (long long GCID_in) const
bool MyLCID (int LCID_in) const
Returns true if the LRID passed in belongs to the calling processor in this map, otherwise returns false.
bool MyGlobalBlockRow (int GID) const
Returns true of GID is owned by the calling processor, otherwise it returns false.
bool MyGlobalBlockRow (long long GID) const
I/O Methods
virtual void Print (std::ostream &os) const
Print method.
Additional methods required to support the Epetra_Operator interface
const char * Label () const
Returns a character string describing the operator.
int SetUseTranspose (bool UseTranspose_in)
If set true, transpose of this operator will be applied.
int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector X in Y.
int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector X in Y.
bool HasNormInf () const
Returns true because this class can compute an Inf-norm.
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this matrix operator.
const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this matrix operator.
Additional methods required to implement RowMatrix interface
int ExtractGlobalRowCopy (int GlobalRow, int Length, int &NumEntries, double *Values, int *Indices) const
Returns a copy of the specified global row in user-provided arrays.
int ExtractMyRowCopy (int MyRow, int Length, int &NumEntries, double *Values, int *Indices) const
Returns a copy of the specified local row in user-provided arrays.
int NumMyRowEntries (int MyRow, int &NumEntries) const
Return the current number of values stored for the specified local row.
int MaxNumEntries () const
Returns the maximum of NumMyRowEntries() over all rows.
const Epetra_BlockMap & Map () const
Map() method inherited from Epetra_DistObject.
const Epetra_Map & RowMatrixRowMap () const
Returns the EpetraMap object associated with the rows of this matrix.
const Epetra_Map & RowMatrixColMap () const
Returns the Epetra_Map object associated with columns of this matrix.
const Epetra_Import * RowMatrixImporter () const
Returns the Epetra_Import object that contains the import operations for distributed operations.
Public Member Functions inherited from Epetra_DistObject
Epetra_DistObject (const Epetra_BlockMap &Map)
Basic Epetra_DistObject constuctor.
Epetra_DistObject (const Epetra_BlockMap &Map, const char *const Label)
Epetra_DistObject (const Epetra_DistObject &Source)
Epetra_DistObject copy constructor.
virtual ~Epetra_DistObject ()
Epetra_DistObject destructor.
int Import (const Epetra_SrcDistObject &A, const Epetra_Import &Importer, Epetra_CombineMode CombineMode, const Epetra_OffsetIndex *Indexor=0)
Imports an Epetra_DistObject using the Epetra_Import object.
int Import (const Epetra_SrcDistObject &A, const Epetra_Export &Exporter, Epetra_CombineMode CombineMode, const Epetra_OffsetIndex *Indexor=0)
Imports an Epetra_DistObject using the Epetra_Export object.
int Export (const Epetra_SrcDistObject &A, const Epetra_Import &Importer, Epetra_CombineMode CombineMode, const Epetra_OffsetIndex *Indexor=0)
Exports an Epetra_DistObject using the Epetra_Import object.
int Export (const Epetra_SrcDistObject &A, const Epetra_Export &Exporter, Epetra_CombineMode CombineMode, const Epetra_OffsetIndex *Indexor=0)
Exports an Epetra_DistObject using the Epetra_Export object.
const Epetra_Comm & Comm () const
Returns the address of the Epetra_Comm for this multi-vector.
bool DistributedGlobal () const
Returns true if this multi-vector is distributed global, i.e., not local replicated.
Public Member Functions inherited from Epetra_Object
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object Constructor.
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object Constructor.
Epetra_Object (const Epetra_Object &Object)
Epetra_Object Copy Constructor.
virtual ~Epetra_Object ()
Epetra_Object Destructor.
virtual int ReportError (const std::string Message, int ErrorCode) const
Error reporting method.
virtual void SetLabel (const char *const Label)
Epetra_Object Label definition using char *.
Public Member Functions inherited from Epetra_SrcDistObject
virtual ~Epetra_SrcDistObject ()
Epetra_SrcDistObject destructor.
Public Member Functions inherited from Epetra_CompObject
Epetra_CompObject ()
Basic Epetra_CompObject constuctor.
Epetra_CompObject (const Epetra_CompObject &Source)
Epetra_CompObject copy constructor.
virtual ~Epetra_CompObject ()
Epetra_CompObject destructor.
void SetFlopCounter (const Epetra_Flops &FlopCounter_in)
Set the internal Epetra_Flops() pointer.
void SetFlopCounter (const Epetra_CompObject &CompObject)
Set the internal Epetra_Flops() pointer to the flop counter of another Epetra_CompObject.
void UnsetFlopCounter ()
Set the internal Epetra_Flops() pointer to 0 (no flops counted).
Epetra_Flops * GetFlopCounter () const
Get the pointer to the Epetra_Flops() object associated with this object, returns 0 if none.
void ResetFlops () const
Resets the number of floating point operations to zero for this multi-vector.
double Flops () const
Returns the number of floating point operations with this multi-vector.
void UpdateFlops (int Flops_in) const
Increment Flop count for this object.
void UpdateFlops (long int Flops_in) const
Increment Flop count for this object.
void UpdateFlops (long long Flops_in) const
Increment Flop count for this object.
void UpdateFlops (double Flops_in) const
Increment Flop count for this object.
void UpdateFlops (float Flops_in) const
Increment Flop count for this object.
Epetra_CompObject & operator= (const Epetra_CompObject &src)
Public Member Functions inherited from Epetra_BLAS
Epetra_BLAS (void)
Epetra_BLAS Constructor.
Epetra_BLAS (const Epetra_BLAS &BLAS)
Epetra_BLAS Copy Constructor.
virtual ~Epetra_BLAS (void)
Epetra_BLAS Destructor.
float ASUM (const int N, const float *X, const int INCX=1) const
Epetra_BLAS one norm function (SASUM).
double ASUM (const int N, const double *X, const int INCX=1) const
Epetra_BLAS one norm function (DASUM).
float DOT (const int N, const float *X, const float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS dot product function (SDOT).
double DOT (const int N, const double *X, const double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS dot product function (DDOT).
float NRM2 (const int N, const float *X, const int INCX=1) const
Epetra_BLAS norm function (SNRM2).
double NRM2 (const int N, const double *X, const int INCX=1) const
Epetra_BLAS norm function (DNRM2).
void SCAL (const int N, const float ALPHA, float *X, const int INCX=1) const
Epetra_BLAS vector scale function (SSCAL)
void SCAL (const int N, const double ALPHA, double *X, const int INCX=1) const
Epetra_BLAS vector scale function (DSCAL)
void COPY (const int N, const float *X, float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector copy function (SCOPY)
void COPY (const int N, const double *X, double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector scale function (DCOPY)
int IAMAX (const int N, const float *X, const int INCX=1) const
Epetra_BLAS arg maximum of absolute value function (ISAMAX)
int IAMAX (const int N, const double *X, const int INCX=1) const
Epetra_BLAS arg maximum of absolute value function (IDAMAX)
void AXPY (const int N, const float ALPHA, const float *X, float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector update function (SAXPY)
void AXPY (const int N, const double ALPHA, const double *X, double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector update function (DAXPY)
void GEMV (const char TRANS, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *X, const float BETA, float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS matrix-vector multiply function (SGEMV)
void GEMV (const char TRANS, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *X, const double BETA, double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS matrix-vector multiply function (DGEMV)
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
Epetra_BLAS matrix-matrix multiply function (SGEMM)
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
Epetra_BLAS matrix-matrix multiply function (DGEMM)
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
Epetra_BLAS symmetric matrix-matrix multiply function (SSYMM)
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
Epetra_BLAS matrix-matrix multiply function (DSYMM)
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const float ALPHA, const float *A, const int LDA, float *B, const int LDB) const
Epetra_BLAS triangular matrix-matrix multiply function (STRMM)
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const double ALPHA, const double *A, const int LDA, double *B, const int LDB) const
Epetra_BLAS triangular matrix-matrix multiply function (DTRMM)
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float BETA, float *C, const int LDC) const
Eperta_BLAS symetric rank k funtion (ssyrk)
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double BETA, double *C, const int LDC) const
Eperta_BLAS symetric rank k funtion (dsyrk)
Public Member Functions inherited from Epetra_RowMatrix
virtual ~Epetra_RowMatrix ()
Destructor.
Public Member Functions inherited from Epetra_Operator
virtual ~Epetra_Operator ()
Destructor.
Deprecated methods: These methods still work, but will be removed in a future version
Epetra_CrsGraph * Graph_
bool Allocated_
bool StaticGraph_
bool UseTranspose_
bool constructedWithFilledGraph_
bool matrixFillCompleteCalled_
bool StorageOptimized_
int NumMyBlockRows_
Epetra_DataAccess CV_
int * NumBlockEntriesPerRow_
int * NumAllocatedBlockEntriesPerRow_
int ** Indices_
int * ElementSizeList_
int * FirstPointInElementList_
Epetra_SerialDenseMatrix *** Entries_
double * All_Values_Orig_
double * All_Values_
double NormInf_
double NormOne_
double NormFrob_
Epetra_MultiVector * ImportVector_
Epetra_MultiVector * ExportVector_
int * TempRowDims_
Epetra_SerialDenseMatrix ** TempEntries_
int LenTemps_
int CurBlockRow_
int CurNumBlockEntries_
int * CurBlockIndices_
int CurEntry_
bool CurIndicesAreLocal_
Epetra_CombineMode CurSubmitMode_
int CurExtractBlockRow_
int CurExtractEntry_
int CurExtractNumBlockEntries_
bool CurExtractIndicesAreLocal_
bool CurExtractView_
int CurRowDim_
int CurBlockDiag_
Epetra_Map * RowMatrixRowMap_
Epetra_Map * RowMatrixColMap_
Epetra_Import * RowMatrixImporter_
Epetra_Map * OperatorDomainMap_
Epetra_Map * OperatorRangeMap_
Epetra_MultiVector * OperatorX_
Epetra_MultiVector * OperatorY_
bool HavePointObjects_
bool squareFillCompleteCalled_
const Epetra_BlockMap & BlockImportMap () const
Use BlockColMap() instead.
int TransformToLocal ()
Use FillComplete() instead.
int TransformToLocal (const Epetra_BlockMap *DomainMap, const Epetra_BlockMap *RangeMap)
Use FillComplete(const Epetra_BlockMap& DomainMap, const Epetra_BlockMap& RangeMap) instead.
void DeleteMemory ()
bool Allocated () const
int SetAllocated (bool Flag)
Epetra_SerialDenseMatrix *** Values () const
int DoMultiply (bool TransA, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
int DoSolve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
void InitializeDefaults ()
int Allocate ()
int BeginInsertValues (int BlockRow, int NumBlockEntries, int *BlockIndices, bool IndicesAreLocal)
int BeginReplaceValues (int BlockRow, int NumBlockEntries, int *BlockIndices, bool IndicesAreLocal)
int BeginSumIntoValues (int BlockRow, int NumBlockEntries, int *BlockIndices, bool IndicesAreLocal)
int SetupForSubmits (int BlockRow, int NumBlockEntries, int *BlockIndices, bool IndicesAreLocal, Epetra_CombineMode SubmitMode)
int EndReplaceSumIntoValues ()
int EndInsertValues ()
int CopyMat (double *A, int LDA, int NumRows, int NumCols, double *B, int LDB, bool SumInto) const
int BeginExtractBlockRowCopy (int BlockRow, int MaxNumBlockEntries, int &RowDim, int &NumBlockEntries, int *BlockIndices, int *ColDims, bool IndicesAreLocal) const
int SetupForExtracts (int BlockRow, int &RowDim, int NumBlockEntries, bool ExtractView, bool IndicesAreLocal) const
int ExtractBlockDimsCopy (int NumBlockEntries, int *ColDims) const
int ExtractBlockRowPointers (int BlockRow, int MaxNumBlockEntries, int &RowDim, int &NumBlockEntries, int *BlockIndices, Epetra_SerialDenseMatrix **&Values, bool IndicesAreLocal) const
int BeginExtractBlockRowView (int BlockRow, int &RowDim, int &NumBlockEntries, int *&BlockIndices, bool IndicesAreLocal) const
int CopyMatDiag (double *A, int LDA, int NumRows, int NumCols, double *Diagonal) const
int ReplaceMatDiag (double *A, int LDA, int NumRows, int NumCols, double *Diagonal)
void BlockRowMultiply (bool TransA, int RowDim, int NumEntries, int *BlockIndices, int RowOff, int *FirstPointInElementList, int *ElementSizeList, double Alpha, Epetra_SerialDenseMatrix **As, double **X, double Beta, double **Y, int NumVectors) const
void BlockRowMultiply (bool TransA, int RowDim, int NumEntries, int *BlockIndices, int RowOff, int *FirstPointInElementList, int *ElementSizeList, Epetra_SerialDenseMatrix **As, double **X, double **Y, int NumVectors) const
void FastBlockRowMultiply (bool TransA, int RowDim, int NumEntries, int *BlockIndices, int RowOff, int *FirstPointInElementList, int *ElementSizeList, Epetra_SerialDenseMatrix **As, double **X, double **Y, int NumVectors) const
int InverseSums (bool DoRows, Epetra_Vector &x) const
int Scale (bool DoRows, const Epetra_Vector &x)
void BlockRowNormInf (int RowDim, int NumEntries, Epetra_SerialDenseMatrix **As, double *Y) const
void BlockRowNormOne (int RowDim, int NumEntries, int *BlockRowIndices, Epetra_SerialDenseMatrix **As, int *ColFirstPointInElementList, double *x) const
void SetStaticGraph (bool Flag)
int CheckSizes (const Epetra_SrcDistObject &A)
Allows the source and target (this) objects to be compared for compatibility, return nonzero if not.
int CopyAndPermute (const Epetra_SrcDistObject &Source, int NumSameIDs, int NumPermuteIDs, int *PermuteToLIDs, int *PermuteFromLIDs, const Epetra_OffsetIndex *Indexor, Epetra_CombineMode CombineMode=Zero)
Perform ID copies and permutations that are on processor.
int PackAndPrepare (const Epetra_SrcDistObject &Source, int NumExportIDs, int *ExportLIDs, int &LenExports, char *&Exports, int &SizeOfPacket, int *Sizes, bool &VarSizes, Epetra_Distributor &Distor)
Perform any packing or preparation required for call to DoTransfer().
int UnpackAndCombine (const Epetra_SrcDistObject &Source, int NumImportIDs, int *ImportLIDs, int LenImports, char *Imports, int &SizeOfPacket, Epetra_Distributor &Distor, Epetra_CombineMode CombineMode, const Epetra_OffsetIndex *Indexor)
Perform any unpacking and combining after call to DoTransfer().
int SortEntries ()
Sort column entries, row-by-row, in ascending order.
bool Sorted () const
If SortEntries() has been called, this query returns true, otherwise it returns false.
int MergeRedundantEntries ()
Add entries that have the same column index. Remove redundant entries from list.
bool NoRedundancies () const
If MergeRedundantEntries() has been called, this query returns true, otherwise it returns false.
bool StaticGraph () const
int GeneratePointObjects () const
int BlockMap2PointMap (const Epetra_BlockMap &BlockMap, Epetra_Map *&PointMap) const
int UpdateOperatorXY (const Epetra_MultiVector &X, const Epetra_MultiVector &Y) const
Additional Inherited Members
Static Public Member Functions inherited from Epetra_Object
static void SetTracebackMode (int TracebackModeValue)
Set the value of the Epetra_Object error traceback report mode.
static int GetTracebackMode ()
Get the value of the Epetra_Object error report mode.
static std::ostream & GetTracebackStream ()
Get the output stream for error reporting.
Static Public Attributes inherited from Epetra_Object
static int TracebackMode
Protected Member Functions inherited from Epetra_DistObject
virtual int DoTransfer (const Epetra_SrcDistObject &A, Epetra_CombineMode CombineMode, int NumSameIDs, int NumPermuteIDs, int NumRemoteIDs, int NumExportIDs, int *PermuteToLIDs, int *PermuteFromLIDs, int *RemoteLIDs, int *ExportLIDs, int &LenExports, char *&Exports, int &LenImports, char *&Imports, Epetra_Distributor &Distor, bool DoReverse, const Epetra_OffsetIndex *Indexor)
Perform actual transfer (redistribution) of data across memory images, using Epetra_Distributor object.
Protected Member Functions inherited from Epetra_Object
std::string toString (const int &x) const
std::string toString (const long long &x) const
std::string toString (const double &x) const
Protected Attributes inherited from Epetra_DistObject
Epetra_BlockMap Map_
const Epetra_Comm * Comm_
char * Exports_
char * Imports_
int LenExports_
int LenImports_
int * Sizes_
Protected Attributes inherited from Epetra_CompObject
Epetra_Flops * FlopCounter_
Detailed Description
Epetra_VbrMatrix: A class for the construction and use of real-valued double-precision variable block-row sparse matrices.
The Epetra_VbrMatrix class is a sparse variable block row matrix object. This matrix can be used in a parallel setting, with data distribution described by Epetra_Map attributes. The structure or graph of the matrix is defined by an Epetra_CrsGraph attribute.
In addition to coefficient access, the primary operations provided by Epetra_VbrMatrix are matrix times vector and matrix times multi-vector multiplication.
Creating and filling Epetra_VbrMatrix objects
Constructing Epetra_VbrMatrix objects is a multi-step process. The basic steps are as follows:
Create Epetra_VbrMatrix instance via one of the constructors:
Constructor that accepts one Epetra_Map object, a row-map defining the distribution of matrix rows.
Constructor that accepts two Epetra_Map objects. (The second map is a column-map, and describes the set of column-indices that appear in each processor's portion of the matrix. Generally these are overlapping sets – column-indices may appear on more than one processor.)
Constructor that accepts an Epetra_CrsGraph object, defining the non-zero structure of the matrix.
Input coefficient values (more detail on this below).
Complete construction by calling FillComplete.
Note that even after FillComplete() has been called, it is possible to update existing matrix entries but it is not possible to create new entries.
Using Epetra_VbrMatrix as an Epetra_RowMatrix
Although Epetra_VbrMatrix does inherit from Epetra_RowMatrix, a design flaw in the inheritance structure of Epetra prohibits the use of an Epetra_VbrMatrix object as an Epetra_RowMatrix in some important situations. Therefore we recommend the use of the Epetra_VbrRowMatrix class to wrap an Epetra_VbrMatrix object for use as an Epetra_RowMatrix. The Epetra_VbrRowMatrix object does not duplicate data in the Epetra_VbrMatrix object, but uses it to satisfy the Epetra_RowMatrix interface.
Epetra_Map attributes
Epetra_VbrMatrix objects have four Epetra_Map attributes, which are held by the Epetra_CrsGraph attribute.
The Epetra_Map attributes can be obtained via these accessor methods:
RowMap() Describes the numbering and distribution of the rows of the matrix. The row-map exists and is valid for the entire life of the matrix. The set of matrix rows is defined by the row-map and may not be changed. Rows may not be inserted or deleted by the user. The only change that may be made is that the user can replace the row-map with a compatible row-map (which is the same except for re-numbering) by calling the ReplaceRowMap() method.
ColMap() Describes the set of column-indices that appear in the rows in each processor's portion of the matrix. Unless provided by the user at construction time, a valid column-map doesn't exist until FillComplete() is called.
RangeMap() Describes the range of the matrix operator. e.g., for a matrix-vector product operation, the result vector's map must be compatible with the range-map of this matrix. The range-map is usually the same as the row-map. The range-map is set equal to the row-map at matrix creation time, but may be specified by the user when FillComplete() is called.
DomainMap() Describes the domain of the matrix operator. The domain-map can be specified by the user when FillComplete() is called. Until then, it is set equal to the row-map.
It is important to note that while the row-map and the range-map are often the same, the column-map and the domain-map are almost never the same. The set of entries in a distributed column-map almost always form overlapping sets, with entries being associated with more than one processor. A domain-map, on the other hand, must be a 1-to-1 map, with entries being associated with only a single processor.
Local versus Global Indices
Epetra_VbrMatrix has query functions IndicesAreLocal() and IndicesAreGlobal(), which are used to determine whether the underlying Epetra_CrsGraph attribute's column-indices have been transformed into a local index space or not. (This transformation occurs when the method Epetra_CrsGraph::FillComplete() is called, which happens when the method Epetra_VbrMatrix::FillComplete() is called.) The state of the indices in the graph determines the behavior of many Epetra_VbrMatrix methods. If an Epetra_VbrMatrix instance is constructed using one of the constructors that does not accept a pre-existing Epetra_CrsGraph object, then an Epetra_CrsGraph attribute is created internally and its indices remain untransformed (IndicesAreGlobal()==true) until Epetra_VbrMatrix::FillComplete() is called. The query function Epetra_VbrMatrix::Filled() returns true if Epetra_VbrMatrix::FillComplete() has been called.
Inputting coefficient values
The process for inputting block-entry coefficients is as follows:
Indicate that values for a specified row are about to be provided by calling one of these methods which specify a block-row and a list of block-column-indices:
BeginInsertGlobalValues()
BeginInsertMyValues()
BeginReplaceGlobalValues()
BeginReplaceMyValues()
BeginSumIntoGlobalValues()
BeginSumIntoMyValues()
Loop over the list of block-column-indices and pass each block-entry to the matrix using the method SubmitBlockEntry().
Complete the process for the specified block-row by calling the method EndSubmitEntries().
Note that the 'GlobalValues' methods have the precondition that IndicesAreGlobal() must be true, and the 'MyValues' methods have the precondition that IndicesAreLocal() must be true. Furthermore, the 'SumInto' and 'Replace' methods may only be used to update matrix entries which already exist, and the 'Insert' methods may only be used if IndicesAreContiguous() is false.
Counting Floating Point Operations
Each Epetra_VbrMatrix object keeps track of the number of serial floating point operations performed using the specified object as the this argument to the function. The Flops() function returns this number as a double precision number. Using this information, in conjunction with the Epetra_Time class, one can get accurate parallel performance numbers. The ResetFlops() function resets the floating point counter.
Constructor & Destructor Documentation
Epetra_VbrMatrix() [1/5]
Epetra_VbrMatrix::Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap & RowMap, int * NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with variable number of indices per row.
Creates a Epetra_VbrMatrix object and allocates storage.
Parameters
In CV - A Epetra_DataAccess enumerated type set to Copy or View.
In RowMap - A Epetra_BlockMap listing the block rows that this processor will contribute to.
In NumBlockEntriesPerRow - An integer array of length NumRows such that NumBlockEntriesPerRow[i] indicates the (approximate) number of Block entries in the ith row.
Epetra_VbrMatrix() [2/5]
Epetra_VbrMatrix::Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap & RowMap, int NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with fixed number of indices per row.
Creates a Epetra_VbrMatrix object and allocates storage.
Parameters
In CV - A Epetra_DataAccess enumerated type set to Copy or View.
In RowMap - An Epetra_BlockMap listing the block rows that this processor will contribute to.
In NumBlockEntriesPerRow - An integer that indicates the (approximate) number of Block entries in the each Block row. Note that it is possible to use 0 for this value and let fill occur during the insertion phase.
Epetra_VbrMatrix() [3/5]
Epetra_VbrMatrix::Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap & RowMap, const Epetra_BlockMap & ColMap, int * NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with variable number of indices per row.
Creates a Epetra_VbrMatrix object and allocates storage.
Parameters
In CV - A Epetra_DataAccess enumerated type set to Copy or View.
In RowMap - A Epetra_BlockMap listing the block rows that this processor will contribute to.
In ColMap - A Epetra_BlockMap.
In NumBlockEntriesPerRow - An integer array of length NumRows such that NumBlockEntriesPerRow[i] indicates the (approximate) number of Block entries in the ith row.
Epetra_VbrMatrix() [4/5]
Epetra_VbrMatrix::Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_BlockMap & RowMap, const Epetra_BlockMap & ColMap, int NumBlockEntriesPerRow)
Epetra_VbrMatrix constuctor with fixed number of indices per row.
Creates a Epetra_VbrMatrix object and allocates storage.
Parameters
In CV - A Epetra_DataAccess enumerated type set to Copy or View.
In RowMap - A Epetra_BlockMap listing the block rows that this processor will contribute to.
In ColMap - An Epetra_BlockMap listing the block columns that this processor will contribute to.
In NumBlockEntriesPerRow - An integer that indicates the (approximate) number of Block entries in the each Block row. Note that it is possible to use 0 for this value and let fill occur during the insertion phase.
Epetra_VbrMatrix() [5/5]
Epetra_VbrMatrix::Epetra_VbrMatrix (Epetra_DataAccess CV, const Epetra_CrsGraph & Graph)
Construct a matrix using an existing Epetra_CrsGraph object.
Allows the nonzero structure from another matrix, or a structure that was constructed independently, to be used for this matrix.
Parameters
In CV - A Epetra_DataAccess enumerated type set to Copy or View.
In Graph - A Epetra_CrsGraph object, extracted from another Epetra matrix object or constructed directly from using the Epetra_CrsGraph constructors.
Member Function Documentation
Apply()
int Epetra_VbrMatrix::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector X in Y.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
ApplyInverse()
int Epetra_VbrMatrix::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector X in Y.
In this implementation, we use several existing attributes to determine how virtual method ApplyInverse() should call the concrete method Solve(). We pass in the UpperTriangular(), the Epetra_VbrMatrix::UseTranspose(), and NoDiagonal() methods. The most notable warning is that if a matrix has no diagonal values we assume that there is an implicit unit diagonal that should be accounted for when doing a triangular solve.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
BeginExtractBlockDiagonalCopy()
int Epetra_VbrMatrix::BeginExtractBlockDiagonalCopy (int MaxNumBlockDiagonalEntries, int & NumBlockDiagonalEntries, int * RowColDims) const
Initiates a copy of the block diagonal entries to user-provided arrays.
Parameters
In MaxNumBlockDiagonalEntries - Length of user-provided RowColDims array.
Out NumBlockDiagonalEntries - Number of block diagonal entries that can actually be extracted.
Out RowColDim - List of row and column dimension for corresponding block diagonal entries.
Returns
Integer error code, set to 0 if successful.
BeginExtractBlockDiagonalView()
int Epetra_VbrMatrix::BeginExtractBlockDiagonalView (int & NumBlockDiagonalEntries, int *& RowColDims) const
Initiates a view of the block diagonal entries.
Parameters
Out NumBlockDiagonalEntries - Number of block diagonal entries that can be viewed.
Out RowColDim - Pointer to list of row and column dimension for corresponding block diagonal entries.
Returns
Integer error code, set to 0 if successful.
BeginExtractGlobalBlockRowCopy()
int Epetra_VbrMatrix::BeginExtractGlobalBlockRowCopy (int BlockRow, int MaxNumBlockEntries, int & RowDim, int & NumBlockEntries, int * BlockIndices, int * ColDims) const
Initiates a copy of the specified global row in user-provided arrays.
Parameters
In BlockRow - Global block row to extract.
In MaxNumBlockEntries - Length of user-provided BlockIndices, ColDims, and LDAs arrays.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries actually extracted.
Out BlockIndices - Extracted global column indices for the corresponding block entries.
Out ColDim - List of column dimensions for each corresponding block entry that will be extracted.
Returns
Integer error code, set to 0 if successful.
BeginExtractGlobalBlockRowView()
int Epetra_VbrMatrix::BeginExtractGlobalBlockRowView (int BlockRow, int & RowDim, int & NumBlockEntries, int *& BlockIndices) const
Initiates a view of the specified global row, only works if matrix indices are in global mode.
Parameters
In BlockRow - Global block row to view.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries to be viewed.
Out BlockIndices - Pointer to global column indices for the corresponding block entries.
Returns
Integer error code, set to 0 if successful.
BeginExtractMyBlockRowCopy()
int Epetra_VbrMatrix::BeginExtractMyBlockRowCopy (int BlockRow, int MaxNumBlockEntries, int & RowDim, int & NumBlockEntries, int * BlockIndices, int * ColDims) const
Initiates a copy of the specified local row in user-provided arrays.
Parameters
In BlockRow - Local block row to extract.
In MaxNumBlockEntries - Length of user-provided BlockIndices, ColDims, and LDAs arrays.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries actually extracted.
Out BlockIndices - Extracted local column indices for the corresponding block entries.
Out ColDim - List of column dimensions for each corresponding block entry that will be extracted.
Returns
Integer error code, set to 0 if successful.
BeginExtractMyBlockRowView()
int Epetra_VbrMatrix::BeginExtractMyBlockRowView (int BlockRow, int & RowDim, int & NumBlockEntries, int *& BlockIndices) const
Initiates a view of the specified local row, only works if matrix indices are in local mode.
Parameters
In BlockRow - Local block row to view.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries to be viewed.
Out BlockIndices - Pointer to local column indices for the corresponding block entries.
Returns
Integer error code, set to 0 if successful.
BeginInsertGlobalValues()
int Epetra_VbrMatrix::BeginInsertGlobalValues (int BlockRow, int NumBlockEntries, int * BlockIndices)
Initiate insertion of a list of elements in a given global row of the matrix, values are inserted via SubmitEntry().
Parameters
In BlockRow - Block Row number (in global coordinates) to put elements.
In NumBlockEntries - Number of entries.
In Indices - Global column indices corresponding to values.
Returns
Integer error code, set to 0 if successful.
BeginInsertMyValues()
int Epetra_VbrMatrix::BeginInsertMyValues (int BlockRow, int NumBlockEntries, int * BlockIndices)
Initiate insertion of a list of elements in a given local row of the matrix, values are inserted via SubmitEntry().
Parameters
In BlockRow - Block Row number (in local coordinates) to put elements.
In NumBlockEntries - Number of entries.
In Indices - Local column indices corresponding to values.
Returns
Integer error code, set to 0 if successful.
BeginReplaceGlobalValues()
int Epetra_VbrMatrix::BeginReplaceGlobalValues (int BlockRow, int NumBlockEntries, int * BlockIndices)
Initiate replacement of current values with this list of entries for a given global row of the matrix, values are replaced via SubmitEntry()
Parameters
In Row - Block Row number (in global coordinates) to put elements.
In NumBlockEntries - Number of entries.
In Indices - Global column indices corresponding to values.
Returns
Integer error code, set to 0 if successful.
BeginReplaceMyValues()
int Epetra_VbrMatrix::BeginReplaceMyValues (int BlockRow, int NumBlockEntries, int * BlockIndices)
Initiate replacement of current values with this list of entries for a given local row of the matrix, values are replaced via SubmitEntry()
Parameters
In Row - Block Row number (in local coordinates) to put elements.
In NumBlockEntries - Number of entries.
In Indices - Local column indices corresponding to values.
Returns
Integer error code, set to 0 if successful.
BeginSumIntoGlobalValues()
int Epetra_VbrMatrix::BeginSumIntoGlobalValues (int BlockRow, int NumBlockEntries, int * BlockIndices)
Initiate summing into current values with this list of entries for a given global row of the matrix, values are replaced via SubmitEntry()
Parameters
In Row - Block Row number (in global coordinates) to put elements.
In NumBlockEntries - Number of entries.
In Indices - Global column indices corresponding to values.
Returns
Integer error code, set to 0 if successful.
BeginSumIntoMyValues()
int Epetra_VbrMatrix::BeginSumIntoMyValues (int BlockRow, int NumBlockEntries, int * BlockIndices)
Initiate summing into current values with this list of entries for a given local row of the matrix, values are replaced via SubmitEntry()
Parameters
In Row - Block Row number (in local coordinates) to put elements.
In NumBlockEntries - Number of entries.
In Indices - Local column indices corresponding to values.
Returns
Integer error code, set to 0 if successful.
CheckSizes()
int Epetra_VbrMatrix::CheckSizes (const Epetra_SrcDistObject & Source) protected virtual
Allows the source and target (this) objects to be compared for compatibility, return nonzero if not.
Implements Epetra_DistObject.
Comm()
const Epetra_Comm & Epetra_VbrMatrix::Comm () const inline virtual
Fills a matrix with rows from a source matrix based on the specified importer.
Returns a pointer to the Epetra_Comm communicator associated with this matrix.
Implements Epetra_Operator.
CopyAndPermute()
int Epetra_VbrMatrix::CopyAndPermute (const Epetra_SrcDistObject & Source, int NumSameIDs, int NumPermuteIDs, int * PermuteToLIDs, int * PermuteFromLIDs, const Epetra_OffsetIndex * Indexor, Epetra_CombineMode CombineMode = Zero) protected virtual
Perform ID copies and permutations that are on processor.
Implements Epetra_DistObject.
DirectSubmitBlockEntry()
int Epetra_VbrMatrix::DirectSubmitBlockEntry (int GlobalBlockRow, int GlobalBlockCol, const double * values, int LDA, int NumRows, int NumCols, bool sum_into)
Submit a block-entry directly into the matrix (without using a begin/end sequence)
Experimental method which allows submitting a block-entry without first calling BeginInsertGlobalValues. This method copies the input data directly into the matrix storage. The block-entry is specified by global block-row and block-col indices.
EndSubmitEntries()
int Epetra_VbrMatrix::EndSubmitEntries ()
Completes processing of all data passed in for the current block row.
This function completes the processing of all block entries submitted via SubmitBlockEntry(). It also checks to make sure that SubmitBlockEntry was called the correct number of times as specified by the Begin routine that initiated the entry process.
ExtractBlockDiagonalEntryCopy()
int Epetra_VbrMatrix::ExtractBlockDiagonalEntryCopy (int SizeOfValues, double * Values, int LDA, bool SumInto) const
Extract a copy of a block diagonal entry from the matrix.
Once BeginExtractBlockDiagonalCopy() is called, you can extract the block diagonal entries one-entry-at-a-time. The entries will be extracted in ascending order.
Parameters
In SizeOfValues - Amount of memory associated with Values. This must be at least as big as LDA*NumCol, where NumCol is the column dimension of the block entry being copied
InOut Values - Starting location where the block entry will be copied.
In LDA - Specifies the stride that will be used when copying columns into Values.
In SumInto - If set to true, the block entry values will be summed into existing values.
ExtractBlockDiagonalEntryView()
int Epetra_VbrMatrix::ExtractBlockDiagonalEntryView (double *& Values, int & LDA) const
Extract a view of a block diagonal entry from the matrix.
Once BeginExtractBlockDiagonalView() is called, you can extract a view of the block diagonal entries one-entry-at-a-time. The views will be extracted in ascending order.
Parameters
Out Values - Pointer to internal copy of block entry.
Out LDA - Column stride of Values.
ExtractDiagonalCopy()
int Epetra_VbrMatrix::ExtractDiagonalCopy (Epetra_Vector & Diagonal) const virtual
Returns a copy of the main diagonal in a user-provided vector.
Parameters
Out Diagonal - Extracted main diagonal.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
ExtractEntryCopy()
int Epetra_VbrMatrix::ExtractEntryCopy (int SizeOfValues, double * Values, int LDA, bool SumInto) const
Extract a copy of an entry from the block row specified by one of the BeginExtract routines.
Once BeginExtractGlobalBlockRowCopy() or BeginExtractMyBlockRowCopy() is called, you can extract the block entries of specified block row one-entry-at-a-time. The entries will be extracted in an order corresponding to the BlockIndices list that was returned by the BeginExtract routine.
Parameters
In SizeOfValues - Amount of memory associated with Values. This must be at least as big as LDA*NumCol, where NumCol is the column dimension of the block entry being copied
InOut Values - Starting location where the block entry will be copied.
In LDA - Specifies the stride that will be used when copying columns into Values.
In SumInto - If set to true, the block entry values will be summed into existing values.
ExtractEntryView()
int Epetra_VbrMatrix::ExtractEntryView (Epetra_SerialDenseMatrix *& entry) const
Returns a pointer to the current block entry.
After a call to BeginExtractGlobal() or BlockRowViewBeginExtractMyBlockRowView(), ExtractEntryView() can be called up to NumBlockEntries times to get each block entry in the specified block row.
Parameters
InOut entry - A pointer that will be set to the current block entry.
ExtractGlobalBlockRowPointers()
int Epetra_VbrMatrix::ExtractGlobalBlockRowPointers (int BlockRow, int MaxNumBlockEntries, int & RowDim, int & NumBlockEntries, int * BlockIndices, Epetra_SerialDenseMatrix **& Values) const
Copy the block indices into user-provided array, set pointers for rest of data for specified global block row.
This function provides the lightest weight approach to accessing a global block row when the matrix may be be stored in local or global index space. In other words, this function will always work because the block indices are returned in user-provided space. All other array arguments are independent of whether or not indices are local or global. Other than the BlockIndices array, all other array argument are returned as pointers to internal data.
Parameters
In BlockRow - Global block row to extract.
In MaxNumBlockEntries - Length of user-provided BlockIndices array.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries actually extracted.
Out BlockIndices - Extracted global column indices for the corresponding block entries.
Out Values - Pointer to list of pointers to block entries. Note that the actual values are not copied.
Returns
Integer error code, set to 0 if successful.
ExtractGlobalBlockRowView()
int Epetra_VbrMatrix::ExtractGlobalBlockRowView (int BlockRow, int & RowDim, int & NumBlockEntries, int *& BlockIndices, Epetra_SerialDenseMatrix **& Values) const
Initiates a view of the specified global row, only works if matrix indices are in global mode.
Parameters
In BlockRow - Global block row to view.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries to be viewed.
Out BlockIndices - Pointer to global column indices for the corresponding block entries.
Out Values - Pointer to an array of pointers to the block entries in the specified block row.
Returns
Integer error code, set to 0 if successful.
ExtractGlobalRowCopy()
int Epetra_VbrMatrix::ExtractGlobalRowCopy (int GlobalRow, int Length, int & NumEntries, double * Values, int * Indices) const
Returns a copy of the specified global row in user-provided arrays.
Parameters
In GlobalRow - Global row to extract.
In Length - Length of Values and Indices.
Out NumEntries - Number of nonzero entries extracted.
Out Values - Extracted values for this row.
Out Indices - Extracted global column indices for the corresponding values.
Returns
Integer error code, set to 0 if successful.
ExtractMyBlockRowPointers()
int Epetra_VbrMatrix::ExtractMyBlockRowPointers (int BlockRow, int MaxNumBlockEntries, int & RowDim, int & NumBlockEntries, int * BlockIndices, Epetra_SerialDenseMatrix **& Values) const
Copy the block indices into user-provided array, set pointers for rest of data for specified local block row.
This function provides the lightest weight approach to accessing a local block row when the matrix may be be stored in local or global index space. In other words, this function will always work because the block indices are returned in user-provided space. All other array arguments are independent of whether or not indices are local or global. Other than the BlockIndices array, all other array argument are returned as pointers to internal data.
Parameters
In BlockRow - Local block row to extract.
In MaxNumBlockEntries - Length of user-provided BlockIndices array.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries actually extracted.
Out BlockIndices - Extracted local column indices for the corresponding block entries.
Out Values - Pointer to list of pointers to block entries. Note that the actual values are not copied.
Returns
Integer error code, set to 0 if successful.
ExtractMyBlockRowView()
int Epetra_VbrMatrix::ExtractMyBlockRowView (int BlockRow, int & RowDim, int & NumBlockEntries, int *& BlockIndices, Epetra_SerialDenseMatrix **& Values) const
Initiates a view of the specified local row, only works if matrix indices are in local mode.
Parameters
In BlockRow - Local block row to view.
Out RowDim - Number of equations in the requested block row.
Out NumBlockEntries - Number of nonzero entries to be viewed.
Out BlockIndices - Pointer to local column indices for the corresponding block entries.
Out Values - Pointer to an array of pointers to the block entries in the specified block row.
Returns
Integer error code, set to 0 if successful.
ExtractMyRowCopy()
int Epetra_VbrMatrix::ExtractMyRowCopy (int MyRow, int Length, int & NumEntries, double * Values, int * Indices) const virtual
Returns a copy of the specified local row in user-provided arrays.
Parameters
In MyRow - Local row to extract.
In Length - Length of Values and Indices.
Out NumEntries - Number of nonzero entries extracted.
Out Values - Extracted values for this row.
Out Indices - Extracted local column indices for the corresponding values.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::ExtractMyRowCopy().
Filled()
bool Epetra_VbrMatrix::Filled () const inline virtual
If FillComplete() has been called, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::Epetra_VbrRowMatrix().
GlobalMaxNumNonzeros()
int Epetra_VbrMatrix::GlobalMaxNumNonzeros () const inline
Returns the maximum number of nonzero entries across all block rows on all processors.
This function returns the max over all processor of MaxNumNonzeros().
HasNormInf()
bool Epetra_VbrMatrix::HasNormInf () const inline virtual
Returns true because this class can compute an Inf-norm.
Implements Epetra_Operator.
IndexBase()
int Epetra_VbrMatrix::IndexBase () const inline
Returns the index base for row and column indices for this graph.
Index base for this map.
InvColSums()
int Epetra_VbrMatrix::InvColSums (Epetra_Vector & x) const virtual
Computes the sum of absolute values of the columns of the Epetra_VbrMatrix, results returned in x.
The vector x will return such that x[j] will contain the inverse of sum of the absolute values of the this matrix will be sca such that A(i,j) = x(j)*A(i,j) where i denotes the global row number of A and j denotes the global column number of A. Using the resulting vector from this function as input to RighttScale() will make the one norm of the resulting matrix exactly 1.
Parameters
Out x -A Epetra_Vector containing the column sums of the this matrix.
Warning
It is assumed that the distribution of x is the same as the rows of this.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
InvRowSums()
int Epetra_VbrMatrix::InvRowSums (Epetra_Vector & x) const virtual
Computes the sum of absolute values of the rows of the Epetra_VbrMatrix, results returned in x.
The vector x will return such that x[i] will contain the inverse of sum of the absolute values of the this matrix will be scaled such that A(i,j) = x(i)*A(i,j) where i denotes the global row number of A and j denotes the global column number of A. Using the resulting vector from this function as input to LeftScale() will make the infinity norm of the resulting matrix exactly 1.
Parameters
Out x -A Epetra_Vector containing the row sums of the this matrix.
Warning
It is assumed that the distribution of x is the same as the rows of this.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Label()
const char * Epetra_VbrMatrix::Label () const inline virtual
Returns a character string describing the operator.
Reimplemented from Epetra_Object.
References Epetra_Object::Label().
LeftScale()
int Epetra_VbrMatrix::LeftScale (const Epetra_Vector & x) virtual
Scales the Epetra_VbrMatrix on the left with a Epetra_Vector x.
The this matrix will be scaled such that A(i,j) = x(i)*A(i,j) where i denotes the row number of A and j denotes the column number of A.
Parameters
In x -A Epetra_Vector to solve for.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::LeftScale().
LowerTriangular()
bool Epetra_VbrMatrix::LowerTriangular () const inline virtual
If matrix is lower triangular in local index space, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
Map()
const Epetra_BlockMap & Epetra_VbrMatrix::Map () const inline virtual
Map() method inherited from Epetra_DistObject.
Reimplemented from Epetra_DistObject.
References Epetra_DistObject::Map().
MaxNumEntries()
int Epetra_VbrMatrix::MaxNumEntries () const virtual
Returns the maximum of NumMyRowEntries() over all rows.
Implements Epetra_RowMatrix.
MaxNumNonzeros()
int Epetra_VbrMatrix::MaxNumNonzeros () const inline
Returns the maximum number of nonzero entries across all block rows on this processor.
Let ki = the number of nonzero values in the ith block row of the VbrMatrix object. For example, if the ith block row had 5 block entries and the size of each entry was 4-by-4, ki would be 80. Then this function return the max over all ki for all row on this processor.
Multiply()
int Epetra_VbrMatrix::Multiply (bool TransA, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Epetra_VbrMatrix multiplied by a Epetra_MultiVector X in Y.
Parameters
In TransA -If true, multiply by the transpose of matrix, otherwise just use matrix.
In X - A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Out Y -A Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::Multiply().
Multiply1()
int Epetra_VbrMatrix::Multiply1 (bool TransA, const Epetra_Vector & x, Epetra_Vector & y) const
Returns the result of a Epetra_VbrMatrix multiplied by a Epetra_Vector x in y.
Parameters
In TransA - If true, multiply by the transpose of matrix, otherwise just use matrix.
In x - A Epetra_Vector to multiply by.
Out y - A Epetra_Vector containing result.
Returns
Integer error code, set to 0 if successful.
NormInf()
double Epetra_VbrMatrix::NormInf () const virtual
Returns the infinity norm of the global matrix.
Implements Epetra_RowMatrix.
NormOne()
double Epetra_VbrMatrix::NormOne () const virtual
Returns the one norm of the global matrix.
Implements Epetra_RowMatrix.
NumGlobalCols()
int Epetra_VbrMatrix::NumGlobalCols () const inline virtual
Returns the number of global matrix columns.
Implements Epetra_RowMatrix.
NumGlobalCols64()
long long Epetra_VbrMatrix::NumGlobalCols64 () const inline virtual
Implements Epetra_RowMatrix.
NumGlobalDiagonals()
int Epetra_VbrMatrix::NumGlobalDiagonals () const inline virtual
Returns the number of global nonzero diagonal entries, based on global row/column index comparisions.
Implements Epetra_RowMatrix.
NumGlobalDiagonals64()
long long Epetra_VbrMatrix::NumGlobalDiagonals64 () const inline virtual
Implements Epetra_RowMatrix.
NumGlobalNonzeros()
int Epetra_VbrMatrix::NumGlobalNonzeros () const inline virtual
Returns the number of nonzero entries in the global matrix.
Implements Epetra_RowMatrix.
NumGlobalNonzeros64()
long long Epetra_VbrMatrix::NumGlobalNonzeros64 () const inline virtual
Implements Epetra_RowMatrix.
NumGlobalRows()
int Epetra_VbrMatrix::NumGlobalRows () const inline virtual
Returns the number of global matrix rows.
Implements Epetra_RowMatrix.
NumGlobalRows64()
long long Epetra_VbrMatrix::NumGlobalRows64 () const inline virtual
Implements Epetra_RowMatrix.
NumMyCols()
int Epetra_VbrMatrix::NumMyCols () const inline virtual
Returns the number of matrix columns owned by the calling processor.
Implements Epetra_RowMatrix.
NumMyDiagonals()
int Epetra_VbrMatrix::NumMyDiagonals () const inline virtual
Returns the number of local nonzero diagonal entries, based on global row/column index comparisons.
Implements Epetra_RowMatrix.
NumMyNonzeros()
int Epetra_VbrMatrix::NumMyNonzeros () const inline virtual
Returns the number of nonzero entriesowned by the calling processor .
Implements Epetra_RowMatrix.
NumMyRowEntries()
int Epetra_VbrMatrix::NumMyRowEntries (int MyRow, int & NumEntries) const virtual
Return the current number of values stored for the specified local row.
Parameters
In MyRow - Local row.
Out NumEntries - Number of nonzero values.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::NumMyRowEntries().
NumMyRows()
int Epetra_VbrMatrix::NumMyRows () const inline virtual
Returns the number of matrix rows owned by the calling processor.
Implements Epetra_RowMatrix.
OperatorDomainMap()
const Epetra_Map & Epetra_VbrMatrix::OperatorDomainMap () const inline virtual
Returns the Epetra_Map object associated with the domain of this matrix operator.
Implements Epetra_Operator.
References Epetra_Operator::UseTranspose().
Referenced by Epetra_VbrRowMatrix::Epetra_VbrRowMatrix().
OperatorRangeMap()
const Epetra_Map & Epetra_VbrMatrix::OperatorRangeMap () const inline virtual
Returns the Epetra_Map object associated with the range of this matrix operator.
Implements Epetra_Operator.
References Epetra_Operator::UseTranspose().
Referenced by Epetra_VbrRowMatrix::Epetra_VbrRowMatrix().
PackAndPrepare()
int Epetra_VbrMatrix::PackAndPrepare (const Epetra_SrcDistObject & Source, int NumExportIDs, int * ExportLIDs, int & LenExports, char *& Exports, int & SizeOfPacket, int * Sizes, bool & VarSizes, Epetra_Distributor & Distor) protected virtual
Perform any packing or preparation required for call to DoTransfer().
Implements Epetra_DistObject.
Print()
virtual void Epetra_VbrMatrix::Print (std::ostream & os) const virtual
Print method.
Reimplemented from Epetra_DistObject.
PutScalar()
int Epetra_VbrMatrix::PutScalar (double ScalarConstant)
Initialize all values in graph of the matrix with constant value.
Parameters
In ScalarConstant - Value to use.
Returns
Integer error code, set to 0 if successful.
ReplaceDiagonalValues()
int Epetra_VbrMatrix::ReplaceDiagonalValues (const Epetra_Vector & Diagonal)
Replaces diagonal values of the with those in the user-provided vector.
This routine is meant to allow replacement of existing diagonal values. If a diagonal value does not exist for a given row, the corresponding value in the input Epetra_Vector will be ignored and the return code will be set to 1.
The Epetra_Map associated with the input Epetra_Vector must be compatible with the RowMap of the matrix.
Parameters
Diagonal (In) - New values to be placed in the main diagonal.
Returns
Integer error code, set to 0 if successful, 1 of one or more diagonal entries not present in matrix.
RightScale()
int Epetra_VbrMatrix::RightScale (const Epetra_Vector & x) virtual
Scales the Epetra_VbrMatrix on the right with a Epetra_Vector x.
The this matrix will be scaled such that A(i,j) = x(j)*A(i,j) where i denotes the global row number of A and j denotes the global column number of A.
Parameters
In x -The Epetra_Vector used for scaling this.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::RightScale().
RowMatrixColMap()
const Epetra_Map & Epetra_VbrMatrix::RowMatrixColMap () const inline virtual
Returns the Epetra_Map object associated with columns of this matrix.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::Epetra_VbrRowMatrix().
RowMatrixImporter()
const Epetra_Import * Epetra_VbrMatrix::RowMatrixImporter () const inline virtual
Returns the Epetra_Import object that contains the import operations for distributed operations.
Implements Epetra_RowMatrix.
RowMatrixRowMap()
const Epetra_Map & Epetra_VbrMatrix::RowMatrixRowMap () const inline virtual
Returns the EpetraMap object associated with the rows of this matrix.
Implements Epetra_RowMatrix.
Referenced by Epetra_VbrRowMatrix::Epetra_VbrRowMatrix().
Scale()
int Epetra_VbrMatrix::Scale (double ScalarConstant)
Multiply all values in the matrix by a constant value (in place: A <- ScalarConstant * A).
Parameters
In ScalarConstant - Value to use.
Returns
Integer error code, set to 0 if successful.
SetUseTranspose()
int Epetra_VbrMatrix::SetUseTranspose (bool UseTranspose_in) inline virtual
If set true, transpose of this operator will be applied.
This flag allows the transpose of the given operator to be used implicitly. Setting this flag affects only the Apply() and ApplyInverse() methods. If the implementation of this interface does not support transpose use, this method should return a value of -1.
Parameters
In UseTranspose -If true, multiply by the transpose of operator, otherwise just use operator.
Returns
Always returns 0.
Implements Epetra_Operator.
Solve() [1/2]
int Epetra_VbrMatrix::Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Epetra_VbrMatrix multiplied by a Epetra_MultiVector X in Y.
Parameters
In Upper -If true, solve Ux = y, otherwise solve Lx = y.
In Trans -If true, solve transpose problem.
In UnitDiagonal -If true, assume diagonal is unit (whether it's stored or not).
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Solve() [2/2]
int Epetra_VbrMatrix::Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_Vector & x, Epetra_Vector & y) const
Returns the result of a solve using the Epetra_VbrMatrix on a Epetra_Vector x in y.
Parameters
In Upper -If true, solve Ux = y, otherwise solve Lx = y.
In Trans -If true, solve transpose problem.
In UnitDiagonal -If true, assume diagonal is unit (whether it's stored or not).
In x -A Epetra_Vector to solve for.
Out y -A Epetra_Vector containing result.
Returns
Integer error code, set to 0 if successful.
Referenced by Epetra_VbrRowMatrix::Solve().
UnpackAndCombine()
int Epetra_VbrMatrix::UnpackAndCombine (const Epetra_SrcDistObject & Source, int NumImportIDs, int * ImportLIDs, int LenImports, char * Imports, int & SizeOfPacket, Epetra_Distributor & Distor, Epetra_CombineMode CombineMode, const Epetra_OffsetIndex * Indexor) protected virtual
Perform any unpacking and combining after call to DoTransfer().
Implements Epetra_DistObject.
UpperTriangular()
bool Epetra_VbrMatrix::UpperTriangular () const inline virtual
If matrix is upper triangular in local index space, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
UseTranspose()
bool Epetra_VbrMatrix::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
The documentation for this class was generated from the following file:
Epetra_VbrMatrix.h