Epetra: Epetra_Object Class Reference
Epetra_Object Class Reference
Epetra_Object: The base Epetra class.
#include <Epetra_Object.h>
Public Member Functions
Constructors/destructor
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object Constructor.
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object Constructor.
Epetra_Object (const Epetra_Object &Object)
Epetra_Object Copy Constructor.
virtual ~Epetra_Object ()
Epetra_Object Destructor.
Miscellaneous
static int TracebackMode
virtual void Print (std::ostream &os) const
virtual int ReportError (const std::string Message, int ErrorCode) const
Error reporting method.
std::string toString (const int &x) const
std::string toString (const long long &x) const
std::string toString (const double &x) const
Attribute set/get methods
virtual void SetLabel (const char *const Label)
Epetra_Object Label definition using char *.
virtual const char * Label () const
Epetra_Object Label access funtion.
static void SetTracebackMode (int TracebackModeValue)
Set the value of the Epetra_Object error traceback report mode.
static int GetTracebackMode ()
Get the value of the Epetra_Object error report mode.
static std::ostream & GetTracebackStream ()
Get the output stream for error reporting.
Detailed Description
Epetra_Object: The base Epetra class.
The Epetra_Object class provides capabilities common to all Epetra objects, such as a label that identifies an object instance, constant definitions, enum types.
Constructor & Destructor Documentation
Epetra_Object() [1/3]
Epetra_Object::Epetra_Object (int TracebackModeIn = -1, bool set_label = true)
Epetra_Object Constructor.
Epetra_Object is the primary base class in Epetra. All Epetra class are derived from it, directly or indirectly. This class is seldom used explictly.
Epetra_Object() [2/3]
Epetra_Object::Epetra_Object (const char *const Label, int TracebackModeIn = -1)
Epetra_Object Constructor.
Creates a Epetra_Object with the given label.
Epetra_Object() [3/3]
Epetra_Object::Epetra_Object (const Epetra_Object & Object)
Epetra_Object Copy Constructor.
Makes an exact copy of an existing Epetra_Object instance.
~Epetra_Object()
virtual Epetra_Object::~Epetra_Object () virtual
Epetra_Object Destructor.
Completely deletes a Epetra_Object object.
Member Function Documentation
Label()
virtual const char * Epetra_Object::Label () const virtual
Epetra_Object Label access funtion.
Returns the string used to define this object.
Reimplemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_SerialDenseMatrix, Epetra_SerialDenseSVD, and Epetra_VbrMatrix.
Referenced by Epetra_MsrMatrix::Label(), Epetra_BasicRowMatrix::Label(), Epetra_CrsMatrix::Label(), Epetra_SerialDenseMatrix::Label(), Epetra_SerialDenseSVD::Label(), and Epetra_VbrMatrix::Label().
Print()
virtual void Epetra_Object::Print (std::ostream & os) const virtual
Print object to an output stream Print method
Reimplemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_BlockMap, Epetra_CrsGraph, Epetra_CrsMatrix, Epetra_DistObject, Epetra_Export, Epetra_FECrsMatrix, Epetra_Import, Epetra_IntMultiVector, Epetra_IntSerialDenseMatrix, Epetra_IntSerialDenseVector, Epetra_IntVector, Epetra_LongLongSerialDenseMatrix, Epetra_LongLongSerialDenseVector, Epetra_LongLongVector, Epetra_MapColoring, Epetra_MpiComm, Epetra_MpiDistributor, Epetra_MultiVector, Epetra_OffsetIndex, Epetra_SerialComm, Epetra_SerialDenseMatrix, Epetra_SerialDenseSolver, Epetra_SerialDenseSVD, Epetra_SerialDenseVector, Epetra_SerialDistributor, and Epetra_VbrMatrix.
SetLabel()
virtual void Epetra_Object::SetLabel (const char *const Label) virtual
Epetra_Object Label definition using char *.
Defines the label used to describe the this object.
Referenced by Epetra_VbrRowMatrix::Epetra_VbrRowMatrix().
SetTracebackMode()
static void Epetra_Object::SetTracebackMode (int TracebackModeValue) static
Set the value of the Epetra_Object error traceback report mode.
Sets the integer error traceback behavior. TracebackMode controls whether or not traceback information is printed when run time integer errors are detected:
<= 0 - No information report
= 1 - Fatal (negative) values are reported
>= 2 - All values (except zero) reported.
Default is set to 1.
The documentation for this class was generated from the following file:
Epetra_Object.h