Epetra: Epetra_Comm Class Reference
Epetra_Comm Class Reference abstract
Epetra_Comm: The Epetra Communication Abstract Base Class.
#include <Epetra_Comm.h>
Public Member Functions
Constructor / Destructor
virtual Epetra_Comm * Clone () const =0
Epetra_Comm clone constructor.
virtual ~Epetra_Comm ()
Epetra_Comm Destructor.
Barrier Methods
virtual void Barrier () const =0
Epetra_Comm Barrier function.
Broadcast Methods
virtual int Broadcast (double *MyVals, int Count, int Root) const =0
Epetra_Comm Broadcast function.
virtual int Broadcast (int *MyVals, int Count, int Root) const =0
Epetra_Comm Broadcast function.
virtual int Broadcast (long *MyVals, int Count, int Root) const =0
Epetra_Comm Broadcast function.
virtual int Broadcast (long long *MyVals, int Count, int Root) const =0
Epetra_Comm Broadcast function.
virtual int Broadcast (char *MyVals, int Count, int Root) const =0
Epetra_Comm Broadcast function.
Gather Methods
virtual int GatherAll (double *MyVals, double *AllVals, int Count) const =0
Epetra_Comm All Gather function.
virtual int GatherAll (int *MyVals, int *AllVals, int Count) const =0
Epetra_Comm All Gather function.
virtual int GatherAll (long *MyVals, long *AllVals, int Count) const =0
Epetra_Comm All Gather function.
virtual int GatherAll (long long *MyVals, long long *AllVals, int Count) const =0
Epetra_Comm All Gather function.
Sum Methods
virtual int SumAll (double *PartialSums, double *GlobalSums, int Count) const =0
Epetra_Comm Global Sum function.
virtual int SumAll (int *PartialSums, int *GlobalSums, int Count) const =0
Epetra_Comm Global Sum function.
virtual int SumAll (long *PartialSums, long *GlobalSums, int Count) const =0
Epetra_Comm Global Sum function.
virtual int SumAll (long long *PartialSums, long long *GlobalSums, int Count) const =0
Epetra_Comm Global Sum function.
Max/Min Methods
virtual int MaxAll (double *PartialMaxs, double *GlobalMaxs, int Count) const =0
Epetra_Comm Global Max function.
virtual int MaxAll (int *PartialMaxs, int *GlobalMaxs, int Count) const =0
Epetra_Comm Global Max function.
virtual int MaxAll (long *PartialMaxs, long *GlobalMaxs, int Count) const =0
Epetra_Comm Global Max function.
virtual int MaxAll (long long *PartialMaxs, long long *GlobalMaxs, int Count) const =0
Epetra_Comm Global Max function.
virtual int MinAll (double *PartialMins, double *GlobalMins, int Count) const =0
Epetra_Comm Global Min function.
virtual int MinAll (int *PartialMins, int *GlobalMins, int Count) const =0
Epetra_Comm Global Min function.
virtual int MinAll (long *PartialMins, long *GlobalMins, int Count) const =0
Epetra_Comm Global Min function.
virtual int MinAll (long long *PartialMins, long long *GlobalMins, int Count) const =0
Parallel Prefix Methods
virtual int ScanSum (double *MyVals, double *ScanSums, int Count) const =0
Epetra_Comm Scan Sum function.
virtual int ScanSum (int *MyVals, int *ScanSums, int Count) const =0
Epetra_Comm Scan Sum function.
virtual int ScanSum (long *MyVals, long *ScanSums, int Count) const =0
Epetra_Comm Scan Sum function.
virtual int ScanSum (long long *MyVals, long long *ScanSums, int Count) const =0
Epetra_Comm Scan Sum function.
Attribute Accessor Methods
virtual int MyPID () const =0
Return my process ID.
virtual int NumProc () const =0
Returns total number of processes.
Gather/Scatter and Directory Constructors
virtual Epetra_Distributor * CreateDistributor () const =0
Create a distributor object.
virtual Epetra_Directory * CreateDirectory (const Epetra_BlockMap &Map) const =0
Create a directory object for the given Epetra_BlockMap.
I/O methods
virtual void PrintInfo (std::ostream &os) const =0
Print object to an output stream.
Detailed Description
Epetra_Comm: The Epetra Communication Abstract Base Class.
The Epetra_Comm class is an interface that encapsulates the general information and services needed for other Epetra classes to run on a parallel computer. An Epetra_Comm object is required for building all Epetra Map objects, which in turn are required for all other Epetra classes.
Epetra_Comm has default implementations, via Epetra_SerialComm and Epetra_MpiComm, for both serial execution and MPI distributed memory execution. It is meant to insulate the user from the specifics of communication that are not required for normal manipulation of linear algebra objects. Most Epetra_Comm interfaces are similar to MPI interfaces, except that the type of data is not required as an argument since C++ can bind to the appropriate interface based on argument typing.
Any implementation of the Epetra_Comm interface is also responsible for generating an Epetra_Distributor and Epetra_Directory object.
Member Function Documentation
Barrier()
virtual void Epetra_Comm::Barrier () const pure virtual
Epetra_Comm Barrier function.
Each processor must wait at the point the barrier is called until all processors have arrived.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Broadcast() [1/5]
virtual int Epetra_Comm::Broadcast (char * MyVals, int Count, int Root) const pure virtual
Epetra_Comm Broadcast function.
Take list of input values from the root processor and sends to all other processors.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of Values.
Root In On entry, contains the processor from which all processors will receive a copy of Values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Broadcast() [2/5]
virtual int Epetra_Comm::Broadcast (double * MyVals, int Count, int Root) const pure virtual
Epetra_Comm Broadcast function.
Take list of input values from the root processor and sends to all other processors.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of Values.
Root In On entry, contains the processor from which all processors will receive a copy of Values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Broadcast() [3/5]
virtual int Epetra_Comm::Broadcast (int * MyVals, int Count, int Root) const pure virtual
Epetra_Comm Broadcast function.
Take list of input values from the root processor and sends to all other processors.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of Values.
Root In On entry, contains the processor from which all processors will receive a copy of Values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Broadcast() [4/5]
virtual int Epetra_Comm::Broadcast (long * MyVals, int Count, int Root) const pure virtual
Epetra_Comm Broadcast function.
Take list of input values from the root processor and sends to all other processors.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of Values.
Root In On entry, contains the processor from which all processors will receive a copy of Values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Broadcast() [5/5]
virtual int Epetra_Comm::Broadcast (long long * MyVals, int Count, int Root) const pure virtual
Epetra_Comm Broadcast function.
Take list of input values from the root processor and sends to all other processors.
Parameters
MyVals InOut On entry, the root processor contains the list of values. On exit, all processors will have the same list of values. Note that values must be allocated on all processor before the broadcast.
Count In On entry, contains the length of the list of Values.
Root In On entry, contains the processor from which all processors will receive a copy of Values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Clone()
virtual Epetra_Comm * Epetra_Comm::Clone () const pure virtual
Epetra_Comm clone constructor.
The clone function will return a new heap-allocated Comm instance. It is the responsibility of the caller to ensure that this new instance is properly destroyed.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
CreateDirectory()
virtual Epetra_Directory * Epetra_Comm::CreateDirectory (const Epetra_BlockMap & Map) const pure virtual
Create a directory object for the given Epetra_BlockMap.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
CreateDistributor()
virtual Epetra_Distributor * Epetra_Comm::CreateDistributor () const pure virtual
Create a distributor object.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
GatherAll() [1/4]
virtual int Epetra_Comm::GatherAll (double * MyVals, double * AllVals, int Count) const pure virtual
Epetra_Comm All Gather function.
Take list of input values from all processors in the communicator and creates an ordered contiguous list of those values on each processor.
Parameters
MyVals In On entry, contains the list of values to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must be of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
GatherAll() [2/4]
virtual int Epetra_Comm::GatherAll (int * MyVals, int * AllVals, int Count) const pure virtual
Epetra_Comm All Gather function.
Take list of input values from all processors in the communicator and creates an ordered contiguous list of those values on each processor.
Parameters
MyVals In On entry, contains the list of values to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must be of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
GatherAll() [3/4]
virtual int Epetra_Comm::GatherAll (long * MyVals, long * AllVals, int Count) const pure virtual
Epetra_Comm All Gather function.
Take list of input values from all processors in the communicator and creates an ordered contiguous list of those values on each processor.
Parameters
MyVals In On entry, contains the list of values to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must be of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
GatherAll() [4/4]
virtual int Epetra_Comm::GatherAll (long long * MyVals, long long * AllVals, int Count) const pure virtual
Epetra_Comm All Gather function.
Take list of input values from all processors in the communicator and creates an ordered contiguous list of those values on each processor.
Parameters
MyVals In On entry, contains the list of values to be sent to all processors.
AllVals Out On exit, contains the list of values from all processors. Must be of size NumProc*Count.
Count In On entry, contains the length of the list of MyVals.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MaxAll() [1/4]
virtual int Epetra_Comm::MaxAll (double * PartialMaxs, double * GlobalMaxs, int Count) const pure virtual
Epetra_Comm Global Max function.
Take list of input values from all processors in the communicator, computes the max and returns the max to all processors.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally; using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MaxAll() [2/4]
virtual int Epetra_Comm::MaxAll (int * PartialMaxs, int * GlobalMaxs, int Count) const pure virtual
Epetra_Comm Global Max function.
Take list of input values from all processors in the communicator, computes the max and returns the max to all processors.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally; using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MaxAll() [3/4]
virtual int Epetra_Comm::MaxAll (long * PartialMaxs, long * GlobalMaxs, int Count) const pure virtual
Epetra_Comm Global Max function.
Take list of input values from all processors in the communicator, computes the max and returns the max to all processors.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally; using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MaxAll() [4/4]
virtual int Epetra_Comm::MaxAll (long long * PartialMaxs, long long * GlobalMaxs, int Count) const pure virtual
Epetra_Comm Global Max function.
Take list of input values from all processors in the communicator, computes the max and returns the max to all processors.
Parameters
PartialMaxs In On entry, contains the list of values, usually partial maxs computed locally; using these Partial Maxs, the max across all processors will be computed.
GlobalMaxs Out On exit, contains the list of maxs computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MinAll() [1/4]
virtual int Epetra_Comm::MinAll (double * PartialMins, double * GlobalMins, int Count) const pure virtual
Epetra_Comm Global Min function.
Take list of input values from all processors in the communicator, computes the min and returns the min to all processors.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MinAll() [2/4]
virtual int Epetra_Comm::MinAll (int * PartialMins, int * GlobalMins, int Count) const pure virtual
Epetra_Comm Global Min function.
Take list of input values from all processors in the communicator, computes the min and returns the min to all processors.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MinAll() [3/4]
virtual int Epetra_Comm::MinAll (long * PartialMins, long * GlobalMins, int Count) const pure virtual
Epetra_Comm Global Min function.
Take list of input values from all processors in the communicator, computes the min and returns the min to all processors.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MinAll() [4/4]
virtual int Epetra_Comm::MinAll (long long * PartialMins, long long * GlobalMins, int Count) const pure virtual
Take list of input values from all processors in the communicator, computes the min and returns the min to all processors.
Parameters
PartialMins In On entry, contains the list of values, usually partial mins computed locally; using these Partial Mins, the min across all processors will be computed.
GlobalMins Out On exit, contains the list of mins computed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
MyPID()
virtual int Epetra_Comm::MyPID () const pure virtual
Return my process ID.
In MPI mode returns the rank of the calling process. In serial mode returns 0.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Referenced by Epetra_MpiComm::Print(), and Epetra_SerialComm::Print().
NumProc()
virtual int Epetra_Comm::NumProc () const pure virtual
Returns total number of processes.
In MPI mode returns the size of the MPI communicator. In serial mode returns 1.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
Referenced by Epetra_MpiComm::Print(), and Epetra_SerialComm::Print().
PrintInfo()
virtual void Epetra_Comm::PrintInfo (std::ostream & os) const pure virtual
Print object to an output stream.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
ScanSum() [1/4]
virtual int Epetra_Comm::ScanSum (double * MyVals, double * ScanSums, int Count) const pure virtual
Epetra_Comm Scan Sum function.
Take list of input values from all processors in the communicator, computes the scan sum and returns it to all processors such that processor i contains the sum of values from processor 0 up to and including processor i.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
ScanSum() [2/4]
virtual int Epetra_Comm::ScanSum (int * MyVals, int * ScanSums, int Count) const pure virtual
Epetra_Comm Scan Sum function.
Take list of input values from all processors in the communicator, computes the scan sum and returns it to all processors such that processor i contains the sum of values from processor 0 up to and including processor i.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
ScanSum() [3/4]
virtual int Epetra_Comm::ScanSum (long * MyVals, long * ScanSums, int Count) const pure virtual
Epetra_Comm Scan Sum function.
Take list of input values from all processors in the communicator, computes the scan sum and returns it to all processors such that processor i contains the sum of values from processor 0 up to and including processor i.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
ScanSum() [4/4]
virtual int Epetra_Comm::ScanSum (long long * MyVals, long long * ScanSums, int Count) const pure virtual
Epetra_Comm Scan Sum function.
Take list of input values from all processors in the communicator, computes the scan sum and returns it to all processors such that processor i contains the sum of values from processor 0 up to and including processor i.
Parameters
MyVals In On entry, contains the list of values to be summed across all processors.
ScanSums Out On exit, contains the list of values summed across processors 0 through i.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
SumAll() [1/4]
virtual int Epetra_Comm::SumAll (double * PartialSums, double * GlobalSums, int Count) const pure virtual
Epetra_Comm Global Sum function.
Take list of input values from all processors in the communicator, computes the sum and returns the sum to all processors.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
SumAll() [2/4]
virtual int Epetra_Comm::SumAll (int * PartialSums, int * GlobalSums, int Count) const pure virtual
Epetra_Comm Global Sum function.
Take list of input values from all processors in the communicator, computes the sum and returns the sum to all processors.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
SumAll() [3/4]
virtual int Epetra_Comm::SumAll (long * PartialSums, long * GlobalSums, int Count) const pure virtual
Epetra_Comm Global Sum function.
Take list of input values from all processors in the communicator, computes the sum and returns the sum to all processors.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
SumAll() [4/4]
virtual int Epetra_Comm::SumAll (long long * PartialSums, long long * GlobalSums, int Count) const pure virtual
Epetra_Comm Global Sum function.
Take list of input values from all processors in the communicator, computes the sum and returns the sum to all processors.
Parameters
PartialSums In On entry, contains the list of values, usually partial sums computed locally, to be summed across all processors.
GlobalSums Out On exit, contains the list of values summed across all processors.
Count In On entry, contains the length of the list of values.
Implemented in Epetra_MpiComm, and Epetra_SerialComm.
The documentation for this class was generated from the following file:
Epetra_Comm.h