Epetra: Epetra_SerialSymDenseMatrix Class Reference
Epetra_SerialSymDenseMatrix Class Reference
Epetra_SerialSymDenseMatrix: A class for constructing and using symmetric positive definite dense matrices.
#include <Epetra_SerialSymDenseMatrix.h>
Public Member Functions
Constructor/Destructor Methods
Epetra_SerialSymDenseMatrix (void)
Default constructor; defines a zero size object.
Epetra_SerialSymDenseMatrix (Epetra_DataAccess CV, double *A, int LDA, int NumRowsCols)
Set object values from two-dimensional array.
Epetra_SerialSymDenseMatrix (const Epetra_SerialSymDenseMatrix &Source)
Epetra_SerialSymDenseMatrix copy constructor.
virtual ~Epetra_SerialSymDenseMatrix ()
Epetra_SerialSymDenseMatrix destructor.
Set Methods
int Shape (int NumRowsCols)
Set dimensions of a Epetra_SerialSymDenseMatrix object; init values to zero.
int Reshape (int NumRowsCols)
Reshape a Epetra_SerialSymDenseMatrix object.
void SetLower ()
Specify that the lower triangle of the this matrix should be used.
void SetUpper ()
Specify that the upper triangle of the this matrix should be used.
int Shape (int NumRows, int NumCols)
Set dimensions of a Epetra_SerialDenseMatrix object; init values to zero.
int Reshape (int NumRows, int NumCols)
Reshape a Epetra_SerialDenseMatrix object.
Query methods
bool Upper () const
Returns true if upper triangle of this matrix has and will be used.
char UPLO () const
Returns character value of UPLO used by LAPACK routines.
Mathematical Methods
int Scale (double ScalarA)
Inplace scalar-matrix product A = a A.
double NormOne () const
Computes the 1-Norm of the this matrix.
double NormInf () const
Computes the Infinity-Norm of the this matrix.
void CopyUPLOMat (bool Upper, double *A, int LDA, int NumRows)
Public Member Functions inherited from Epetra_SerialDenseMatrix
Epetra_SerialDenseMatrix (bool set_object_label=true)
Default constructor; defines a zero size object.
Epetra_SerialDenseMatrix (int NumRows, int NumCols, bool set_object_label=true)
Shaped constructor; defines a variable-sized object.
Epetra_SerialDenseMatrix (Epetra_DataAccess CV, double *A_in, int LDA_in, int NumRows, int NumCols, bool set_object_label=true)
Set object values from two-dimensional array.
Epetra_SerialDenseMatrix (const Epetra_SerialDenseMatrix &Source)
Epetra_SerialDenseMatrix copy constructor.
virtual ~Epetra_SerialDenseMatrix ()
Epetra_SerialDenseMatrix destructor.
int Shape (int NumRows, int NumCols)
Set dimensions of a Epetra_SerialDenseMatrix object; init values to zero.
int Reshape (int NumRows, int NumCols)
Reshape a Epetra_SerialDenseMatrix object.
int Multiply (char TransA, char TransB, double ScalarAB, const Epetra_SerialDenseMatrix &A, const Epetra_SerialDenseMatrix &B, double ScalarThis)
Matrix-Matrix multiplication, this = ScalarThis*this + ScalarAB*A*B.
int Multiply (bool transA, const Epetra_SerialDenseMatrix &x, Epetra_SerialDenseMatrix &y)
Matrix-Vector multiplication, y = A*x, where 'this' == A.
int Multiply (char SideA, double ScalarAB, const Epetra_SerialSymDenseMatrix &A, const Epetra_SerialDenseMatrix &B, double ScalarThis)
Matrix-Matrix multiplication with a symmetric matrix A.
int Scale (double ScalarA)
Inplace scalar-matrix product A = a A.
Epetra_SerialDenseMatrix & operator= (const Epetra_SerialDenseMatrix &Source)
Value copy from one matrix to another.
bool operator== (const Epetra_SerialDenseMatrix &rhs) const
Comparison operator.
bool operator!= (const Epetra_SerialDenseMatrix &rhs) const
Inequality operator.
Epetra_SerialDenseMatrix & operator+= (const Epetra_SerialDenseMatrix &Source)
Add one matrix to another.
double & operator() (int RowIndex, int ColIndex)
Element access function.
const double & operator() (int RowIndex, int ColIndex) const
Element access function.
double * operator[] (int ColIndex)
Column access function.
const double * operator[] (int ColIndex) const
Column access function.
int Random ()
Set matrix values to random numbers.
int M () const
Returns row dimension of system.
int N () const
Returns column dimension of system.
double * A () const
Returns pointer to the this matrix.
double * A ()
Returns pointer to the this matrix.
int LDA () const
Returns the leading dimension of the this matrix.
Epetra_DataAccess CV () const
Returns the data access mode of the this matrix.
virtual void Print (std::ostream &os) const
Print service methods; defines behavior of ostream << operator.
virtual int SetUseTranspose (bool UseTranspose_in)
If set true, transpose of this operator will be applied.
virtual int Apply (const Epetra_SerialDenseMatrix &X, Epetra_SerialDenseMatrix &Y)
Returns the result of a Epetra_SerialDenseOperator applied to a Epetra_SerialDenseMatrix X in Y.
virtual int ApplyInverse (const Epetra_SerialDenseMatrix &X, Epetra_SerialDenseMatrix &Y)
Returns the result of a Epetra_SerialDenseOperator inverse applied to an Epetra_SerialDenseMatrix X in Y.
virtual const char * Label () const
Returns a character string describing the operator.
virtual bool UseTranspose () const
Returns the current UseTranspose setting.
virtual bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
virtual int RowDim () const
Returns the row dimension of operator.
virtual int ColDim () const
Returns the column dimension of operator.
Public Member Functions inherited from Epetra_CompObject
Epetra_CompObject ()
Basic Epetra_CompObject constuctor.
Epetra_CompObject (const Epetra_CompObject &Source)
Epetra_CompObject copy constructor.
virtual ~Epetra_CompObject ()
Epetra_CompObject destructor.
void SetFlopCounter (const Epetra_Flops &FlopCounter_in)
Set the internal Epetra_Flops() pointer.
void SetFlopCounter (const Epetra_CompObject &CompObject)
Set the internal Epetra_Flops() pointer to the flop counter of another Epetra_CompObject.
void UnsetFlopCounter ()
Set the internal Epetra_Flops() pointer to 0 (no flops counted).
Epetra_Flops * GetFlopCounter () const
Get the pointer to the Epetra_Flops() object associated with this object, returns 0 if none.
void ResetFlops () const
Resets the number of floating point operations to zero for this multi-vector.
double Flops () const
Returns the number of floating point operations with this multi-vector.
void UpdateFlops (int Flops_in) const
Increment Flop count for this object.
void UpdateFlops (long int Flops_in) const
Increment Flop count for this object.
void UpdateFlops (long long Flops_in) const
Increment Flop count for this object.
void UpdateFlops (double Flops_in) const
Increment Flop count for this object.
void UpdateFlops (float Flops_in) const
Increment Flop count for this object.
Epetra_CompObject & operator= (const Epetra_CompObject &src)
Public Member Functions inherited from Epetra_Object
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object Constructor.
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object Constructor.
Epetra_Object (const Epetra_Object &Object)
Epetra_Object Copy Constructor.
virtual ~Epetra_Object ()
Epetra_Object Destructor.
virtual int ReportError (const std::string Message, int ErrorCode) const
Error reporting method.
virtual void SetLabel (const char *const Label)
Epetra_Object Label definition using char *.
Public Member Functions inherited from Epetra_SerialDenseOperator
virtual ~Epetra_SerialDenseOperator ()
Destructor.
Public Member Functions inherited from Epetra_BLAS
Epetra_BLAS (void)
Epetra_BLAS Constructor.
Epetra_BLAS (const Epetra_BLAS &BLAS)
Epetra_BLAS Copy Constructor.
virtual ~Epetra_BLAS (void)
Epetra_BLAS Destructor.
float ASUM (const int N, const float *X, const int INCX=1) const
Epetra_BLAS one norm function (SASUM).
double ASUM (const int N, const double *X, const int INCX=1) const
Epetra_BLAS one norm function (DASUM).
float DOT (const int N, const float *X, const float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS dot product function (SDOT).
double DOT (const int N, const double *X, const double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS dot product function (DDOT).
float NRM2 (const int N, const float *X, const int INCX=1) const
Epetra_BLAS norm function (SNRM2).
double NRM2 (const int N, const double *X, const int INCX=1) const
Epetra_BLAS norm function (DNRM2).
void SCAL (const int N, const float ALPHA, float *X, const int INCX=1) const
Epetra_BLAS vector scale function (SSCAL)
void SCAL (const int N, const double ALPHA, double *X, const int INCX=1) const
Epetra_BLAS vector scale function (DSCAL)
void COPY (const int N, const float *X, float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector copy function (SCOPY)
void COPY (const int N, const double *X, double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector scale function (DCOPY)
int IAMAX (const int N, const float *X, const int INCX=1) const
Epetra_BLAS arg maximum of absolute value function (ISAMAX)
int IAMAX (const int N, const double *X, const int INCX=1) const
Epetra_BLAS arg maximum of absolute value function (IDAMAX)
void AXPY (const int N, const float ALPHA, const float *X, float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector update function (SAXPY)
void AXPY (const int N, const double ALPHA, const double *X, double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS vector update function (DAXPY)
void GEMV (const char TRANS, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *X, const float BETA, float *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS matrix-vector multiply function (SGEMV)
void GEMV (const char TRANS, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *X, const double BETA, double *Y, const int INCX=1, const int INCY=1) const
Epetra_BLAS matrix-vector multiply function (DGEMV)
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
Epetra_BLAS matrix-matrix multiply function (SGEMM)
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
Epetra_BLAS matrix-matrix multiply function (DGEMM)
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
Epetra_BLAS symmetric matrix-matrix multiply function (SSYMM)
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
Epetra_BLAS matrix-matrix multiply function (DSYMM)
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const float ALPHA, const float *A, const int LDA, float *B, const int LDB) const
Epetra_BLAS triangular matrix-matrix multiply function (STRMM)
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const double ALPHA, const double *A, const int LDA, double *B, const int LDB) const
Epetra_BLAS triangular matrix-matrix multiply function (DTRMM)
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float BETA, float *C, const int LDC) const
Eperta_BLAS symetric rank k funtion (ssyrk)
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double BETA, double *C, const int LDC) const
Eperta_BLAS symetric rank k funtion (dsyrk)
Deprecated methods (will be removed in later versions of this class)
double OneNorm () const
Computes the 1-Norm of the this matrix (identical to NormOne() method).
double InfNorm () const
Computes the Infinity-Norm of the this matrix (identical to NormInf() method).
Additional Inherited Members
Static Public Member Functions inherited from Epetra_Object
static void SetTracebackMode (int TracebackModeValue)
Set the value of the Epetra_Object error traceback report mode.
static int GetTracebackMode ()
Get the value of the Epetra_Object error report mode.
static std::ostream & GetTracebackStream ()
Get the output stream for error reporting.
Static Public Attributes inherited from Epetra_Object
static int TracebackMode
Protected Member Functions inherited from Epetra_SerialDenseMatrix
void CopyMat (const double *Source, int Source_LDA, int NumRows, int NumCols, double *Target, int Target_LDA, bool add=false)
void CleanupData ()
Protected Member Functions inherited from Epetra_Object
std::string toString (const int &x) const
std::string toString (const long long &x) const
std::string toString (const double &x) const
Protected Attributes inherited from Epetra_SerialDenseMatrix
int M_
int N_
bool A_Copied_
Epetra_DataAccess CV_
int LDA_
double * A_
bool UseTranspose_
Protected Attributes inherited from Epetra_CompObject
Epetra_Flops * FlopCounter_
Detailed Description
Epetra_SerialSymDenseMatrix: A class for constructing and using symmetric positive definite dense matrices.
The Epetra_SerialSymDenseMatrix class enables the construction and use of real-valued, symmetric positive definite, double-precision dense matrices. It is built on the Epetra_SerialDenseMatrix class which in turn is built on the BLAS via the Epetra_BLAS class.
The Epetra_SerialSymDenseMatrix class is intended to provide full-featured support for solving linear and eigen system problems for symmetric positive definite matrices. It is written on top of BLAS and LAPACK and thus has excellent performance and numerical capabilities. Using this class, one can either perform simple factorizations and solves or apply all the tricks available in LAPACK to get the best possible solution for very ill-conditioned problems.
Epetra_SerialSymDenseMatrix vs. Epetra_LAPACK
The Epetra_LAPACK class provides access to most of the same functionality as Epetra_SerialSymDenseMatrix. The primary difference is that Epetra_LAPACK is a "thin" layer on top of LAPACK and Epetra_SerialSymDenseMatrix attempts to provide easy access to the more sophisticated aspects of solving dense linear and eigensystems.
When you should use Epetra_LAPACK: If you are simply looking for a convenient wrapper around the Fortran LAPACK routines and you have a well-conditioned problem, you should probably use Epetra_LAPACK directly.
When you should use Epetra_SerialSymDenseMatrix: If you want to (or potentially want to) solve ill-conditioned problems or want to work with a more object-oriented interface, you should probably use Epetra_SerialSymDenseMatrix.
Constructing Epetra_SerialSymDenseMatrix Objects
There are three Epetra_DenseMatrix constructors. The first constructs a zero-sized object which should be made to appropriate length using the Shape() or Reshape() functions and then filled with the [] or () operators. The second is a constructor that accepts user data as a 2D array, the third is a copy constructor. The second constructor has two data access modes (specified by the Epetra_DataAccess argument):
Copy mode - Allocates memory and makes a copy of the user-provided data. In this case, the user data is not needed after construction.
View mode - Creates a "view" of the user data. In this case, the user data is required to remain intact for the life of the object.
Warning
View mode is extremely dangerous from a data hiding perspective. Therefore, we strongly encourage users to develop code using Copy mode first and only use the View mode in a secondary optimization phase.
Extracting Data from Epetra_SerialSymDenseMatrix Objects
Once a Epetra_SerialSymDenseMatrix is constructed, it is possible to view the data via access functions.
Warning
Use of these access functions cam be extremely dangerous from a data hiding perspective.
Vector and Utility Functions
Once a Epetra_SerialSymDenseMatrix is constructed, several mathematical functions can be applied to the object. Specifically:
Multiplication.
Norms.
Counting floating point operations The Epetra_SerialSymDenseMatrix class has Epetra_CompObject as a base class. Thus, floating point operations are counted and accumulated in the Epetra_Flop object (if any) that was set using the SetFlopCounter() method in the Epetra_CompObject base class.
Constructor & Destructor Documentation
Epetra_SerialSymDenseMatrix() [1/2]
Epetra_SerialSymDenseMatrix::Epetra_SerialSymDenseMatrix (void)
Default constructor; defines a zero size object.
Epetra_SerialSymDenseMatrix objects defined by the default constructor should be sized with the Shape() or Reshape() functions. Values should be defined by using the [] or ()operators.
Note: By default the active part of the matrix is assumed to be in the lower triangle. To set the upper part as active, call SetUpper(). See Detailed Description section for further discussion.
Epetra_SerialSymDenseMatrix() [2/2]
Epetra_SerialSymDenseMatrix::Epetra_SerialSymDenseMatrix (Epetra_DataAccess CV, double * A, int LDA, int NumRowsCols)
Set object values from two-dimensional array.
Parameters
In Epetra_DataAccess - Enumerated type set to Copy or View.
In A - Pointer to an array of double precision numbers. The first vector starts at A. The second vector starts at A+LDA, the third at A+2*LDA, and so on.
In LDA - The "Leading Dimension", or stride between vectors in memory.
In NumRowsCols - Number of rows and columns in object.
Note: By default the active part of the matrix is assumed to be in the lower triangle. To set the upper part as active, call SetUpper(). See Detailed Description section for further discussion.
Member Function Documentation
InfNorm()
double Epetra_SerialSymDenseMatrix::InfNorm () const inline virtual
Computes the Infinity-Norm of the this matrix (identical to NormInf() method).
Reimplemented from Epetra_SerialDenseMatrix.
References NormInf().
NormInf()
double Epetra_SerialSymDenseMatrix::NormInf () const virtual
Computes the Infinity-Norm of the this matrix.
Reimplemented from Epetra_SerialDenseMatrix.
Referenced by InfNorm().
NormOne()
double Epetra_SerialSymDenseMatrix::NormOne () const virtual
Computes the 1-Norm of the this matrix.
Returns
Integer error code, set to 0 if successful.
Reimplemented from Epetra_SerialDenseMatrix.
Referenced by OneNorm().
OneNorm()
double Epetra_SerialSymDenseMatrix::OneNorm () const inline virtual
Computes the 1-Norm of the this matrix (identical to NormOne() method).
Returns
Integer error code, set to 0 if successful.
Reimplemented from Epetra_SerialDenseMatrix.
References NormOne().
Reshape() [1/2]
int Epetra_SerialDenseMatrix::Reshape (int NumRows, int NumCols)
Reshape a Epetra_SerialDenseMatrix object.
Parameters
In NumRows - Number of rows in object.
In NumCols - Number of columns in object.
Allows user to define the dimensions of a Epetra_SerialDenseMatrix at any point. This function can be called at any point after construction. Any values that were previously in this object are copied into the new shape. If the new shape is smaller than the original, the upper left portion of the original matrix (the principal submatrix) is copied to the new matrix.
Returns
Integer error code, set to 0 if successful.
Reshape() [2/2]
int Epetra_SerialSymDenseMatrix::Reshape (int NumRowsCols) inline
Reshape a Epetra_SerialSymDenseMatrix object.
Parameters
In NumRowsCols - Number of rows and columns in object.
Allows user to define the dimensions of a Epetra_SerialSymDenseMatrix at any point. This function can be called at any point after construction. Any values that were previously in this object are copied into the new shape. If the new shape is smaller than the original, the upper left portion of the original matrix (the principal submatrix) is copied to the new matrix.
Returns
Integer error code, set to 0 if successful.
References Epetra_SerialDenseMatrix::Reshape().
Scale()
int Epetra_SerialSymDenseMatrix::Scale (double ScalarA)
Inplace scalar-matrix product A = a A.
Scale a matrix, entry-by-entry using the value ScalarA. This method is sensitive to the UPLO() parameter.
Parameters
ScalarA (In) Scalar to multiply with A.
Returns
Integer error code, set to 0 if successful.
Shape() [1/2]
int Epetra_SerialDenseMatrix::Shape (int NumRows, int NumCols)
Set dimensions of a Epetra_SerialDenseMatrix object; init values to zero.
Parameters
In NumRows - Number of rows in object.
In NumCols - Number of columns in object.
Allows user to define the dimensions of a Epetra_SerialDenseMatrix at any point. This function can be called at any point after construction. Any values that were previously in this object are destroyed and the resized matrix starts off with all zero values.
Returns
Integer error code, set to 0 if successful.
Shape() [2/2]
int Epetra_SerialSymDenseMatrix::Shape (int NumRowsCols) inline
Set dimensions of a Epetra_SerialSymDenseMatrix object; init values to zero.
Parameters
In NumRowsCols - Number of rows and columns in object.
Allows user to define the dimensions of a Epetra_DenseMatrix at any point. This function can be called at any point after construction. Any values that were previously in this object are destroyed and the resized matrix starts off with all zero values.
Returns
Integer error code, set to 0 if successful.
References Epetra_SerialDenseMatrix::Shape().
The documentation for this class was generated from the following file:
Epetra_SerialSymDenseMatrix.h