Epetra: Epetra_BasicRowMatrix Class Reference
Epetra_BasicRowMatrix Class Reference abstract
Epetra_BasicRowMatrix: A class for simplifying the development of Epetra_RowMatrix adapters.
#include <Epetra_BasicRowMatrix.h>
Public Member Functions
Constructor/Destructor
Epetra_BasicRowMatrix (const Epetra_Comm &Comm)
Epetra_BasicRowMatrix constructor.
virtual ~Epetra_BasicRowMatrix ()
Epetra_BasicRowMatrix Destructor.
Setup functions
void SetMaps (const Epetra_Map &RowMap, const Epetra_Map &ColMap)
Set maps (Version 1); call this function or the next, but not both.
void SetMaps (const Epetra_Map &RowMap, const Epetra_Map &ColMap, const Epetra_Map &DomainMap, const Epetra_Map &RangeMap)
Set maps (Version 2); call this function or the previous, but not both.
User-required implementation methods
virtual int ExtractMyRowCopy (int MyRow, int Length, int &NumEntries, double *Values, int *Indices) const =0
Returns a copy of the specified local row in user-provided arrays.
virtual int ExtractMyEntryView (int CurEntry, double *&Value, int &RowIndex, int &ColIndex)=0
Returns a reference to the ith entry in the matrix, along with its row and column index.
virtual int ExtractMyEntryView (int CurEntry, double const *&Value, int &RowIndex, int &ColIndex) const =0
Returns a const reference to the ith entry in the matrix, along with its row and column index.
virtual int NumMyRowEntries (int MyRow, int &NumEntries) const =0
Return the current number of values stored for the specified local row.
Computational methods
virtual int Multiply (bool TransA, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_BasicRowMatrix multiplied by a Epetra_MultiVector X in Y.
virtual int Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_BasicRowMatrix solve with a Epetra_MultiVector X in Y (not implemented).
virtual int ExtractDiagonalCopy (Epetra_Vector &Diagonal) const
Returns a copy of the main diagonal in a user-provided vector.
virtual int InvRowSums (Epetra_Vector &x) const
Computes the sum of absolute values of the rows of the Epetra_BasicRowMatrix, results returned in x.
virtual int LeftScale (const Epetra_Vector &x)
Scales the Epetra_BasicRowMatrix on the left with a Epetra_Vector x.
virtual int InvColSums (Epetra_Vector &x) const
Computes the sum of absolute values of the columns of the Epetra_BasicRowMatrix, results returned in x.
virtual int RightScale (const Epetra_Vector &x)
Scales the Epetra_BasicRowMatrix on the right with a Epetra_Vector x.
Matrix Properties Query Methods
virtual bool Filled () const
If FillComplete() has been called, this query returns true, otherwise it returns false, presently always returns true.
bool LowerTriangular () const
If matrix is lower triangular, this query returns true, otherwise it returns false.
virtual bool UpperTriangular () const
If matrix is upper triangular, this query returns true, otherwise it returns false.
Attribute access functions
virtual double NormInf () const
Returns the infinity norm of the global matrix.
virtual double NormOne () const
Returns the one norm of the global matrix.
virtual int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global matrix.
virtual long long NumGlobalNonzeros64 () const
virtual int NumGlobalRows () const
Returns the number of global matrix rows.
virtual long long NumGlobalRows64 () const
virtual int NumGlobalCols () const
Returns the number of global matrix columns.
virtual long long NumGlobalCols64 () const
virtual int NumGlobalDiagonals () const
Returns the number of global nonzero diagonal entries.
virtual long long NumGlobalDiagonals64 () const
virtual int NumMyNonzeros () const
Returns the number of nonzero entries in the calling processor's portion of the matrix.
virtual int NumMyRows () const
Returns the number of matrix rows owned by the calling processor.
virtual int NumMyCols () const
Returns the number of matrix columns owned by the calling processor.
virtual int NumMyDiagonals () const
Returns the number of local nonzero diagonal entries.
virtual int MaxNumEntries () const
Returns the maximum number of nonzero entries across all rows on this processor.
virtual const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
virtual const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator (same as domain).
virtual const Epetra_BlockMap & Map () const
Implement the Epetra_SrcDistObjec::Map() function.
virtual const Epetra_Map & RowMatrixRowMap () const
Returns the Row Map object needed for implementing Epetra_RowMatrix.
virtual const Epetra_Map & RowMatrixColMap () const
Returns the Column Map object needed for implementing Epetra_RowMatrix.
virtual const Epetra_Import * RowMatrixImporter () const
Returns the Epetra_Import object that contains the import operations for distributed operations.
virtual const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this matrix.
I/O Methods
virtual void Print (std::ostream &os) const
Print method.
Additional methods required to support the Epetra_RowMatrix interface
virtual int SetUseTranspose (bool use_transpose)
If set true, transpose of this operator will be applied.
virtual const char * Label () const
Returns a character string describing the operator.
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_RowMatrix applied to a Epetra_MultiVector X in Y.
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_RowMatrix inverse applied to an Epetra_MultiVector X in Y.
bool HasNormInf () const
Returns true because this class can compute an Inf-norm.
virtual bool UseTranspose () const
Returns the current UseTranspose setting.
Additional accessor methods
virtual const Epetra_Import * Importer () const
Returns the Epetra_Import object that contains the import operations for distributed operations, returns zero if none.
virtual const Epetra_Export * Exporter () const
Returns the Epetra_Export object that contains the export operations for distributed operations, returns zero if none.
Public Member Functions inherited from Epetra_CompObject
Epetra_CompObject ()
Basic Epetra_CompObject constuctor.
Epetra_CompObject (const Epetra_CompObject &Source)
Epetra_CompObject copy constructor.
virtual ~Epetra_CompObject ()
Epetra_CompObject destructor.
void SetFlopCounter (const Epetra_Flops &FlopCounter_in)
Set the internal Epetra_Flops() pointer.
void SetFlopCounter (const Epetra_CompObject &CompObject)
Set the internal Epetra_Flops() pointer to the flop counter of another Epetra_CompObject.
void UnsetFlopCounter ()
Set the internal Epetra_Flops() pointer to 0 (no flops counted).
Epetra_Flops * GetFlopCounter () const
Get the pointer to the Epetra_Flops() object associated with this object, returns 0 if none.
void ResetFlops () const
Resets the number of floating point operations to zero for this multi-vector.
double Flops () const
Returns the number of floating point operations with this multi-vector.
void UpdateFlops (int Flops_in) const
Increment Flop count for this object.
void UpdateFlops (long int Flops_in) const
Increment Flop count for this object.
void UpdateFlops (long long Flops_in) const
Increment Flop count for this object.
void UpdateFlops (double Flops_in) const
Increment Flop count for this object.
void UpdateFlops (float Flops_in) const
Increment Flop count for this object.
Epetra_CompObject & operator= (const Epetra_CompObject &src)
Public Member Functions inherited from Epetra_Object
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object Constructor.
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object Constructor.
Epetra_Object (const Epetra_Object &Object)
Epetra_Object Copy Constructor.
virtual ~Epetra_Object ()
Epetra_Object Destructor.
virtual int ReportError (const std::string Message, int ErrorCode) const
Error reporting method.
virtual void SetLabel (const char *const Label)
Epetra_Object Label definition using char *.
Public Member Functions inherited from Epetra_RowMatrix
virtual ~Epetra_RowMatrix ()
Destructor.
Public Member Functions inherited from Epetra_Operator
virtual ~Epetra_Operator ()
Destructor.
Public Member Functions inherited from Epetra_SrcDistObject
virtual ~Epetra_SrcDistObject ()
Epetra_SrcDistObject destructor.
Post-construction modifications
Epetra_Comm * Comm_
Epetra_Map OperatorDomainMap_
Epetra_Map OperatorRangeMap_
Epetra_Map RowMatrixRowMap_
Epetra_Map RowMatrixColMap_
int NumMyNonzeros_
long long NumGlobalNonzeros_
int MaxNumEntries_
double NormInf_
double NormOne_
int NumMyRows_
int NumMyCols_
bool UseTranspose_
bool HasNormInf_
bool LowerTriangular_
bool UpperTriangular_
bool HaveStructureConstants_
bool HaveNumericConstants_
bool HaveMaps_
Epetra_MultiVector * ImportVector_
Epetra_MultiVector * ExportVector_
Epetra_Import * Importer_
Epetra_Export * Exporter_
virtual void ComputeStructureConstants () const
Update the constants associated with the structure of the matrix: Call only if structure changes from the initial RowMatrix.
virtual void ComputeNumericConstants () const
Update the constants associated with the values of the matrix: Call only if values changes from the initial RowMatrix.
void Setup ()
void UpdateImportVector (int NumVectors) const
void UpdateExportVector (int NumVectors) const
void SetImportExport ()
Additional Inherited Members
Static Public Member Functions inherited from Epetra_Object
static void SetTracebackMode (int TracebackModeValue)
Set the value of the Epetra_Object error traceback report mode.
static int GetTracebackMode ()
Get the value of the Epetra_Object error report mode.
static std::ostream & GetTracebackStream ()
Get the output stream for error reporting.
Static Public Attributes inherited from Epetra_Object
static int TracebackMode
Protected Member Functions inherited from Epetra_Object
std::string toString (const int &x) const
std::string toString (const long long &x) const
std::string toString (const double &x) const
Protected Attributes inherited from Epetra_CompObject
Epetra_Flops * FlopCounter_
Detailed Description
Epetra_BasicRowMatrix: A class for simplifying the development of Epetra_RowMatrix adapters.
The Epetra_BasicRowMatrix is an adapter class for Epetra_RowMatrix that implements most of the Epetra_RowMatrix methods using reasonable default implementations. The Epetra_RowMatrix class has 39 pure virtual methods, requiring the adapter class to implement all of them. Epetra_BasicRowMatrix has only 4 pure virtual methods that must be implemented (See Epetra_JadMatrix for an example):
ExtractMyRowCopy: Provide a row of values and indices for a specified local row.
ExtractMyEntryView (const and non-const versions): Provide the memory address of the ith nonzero term stored on the calling processor, along with its corresponding local row and column index, where i goes from 0 to the NumMyNonzeros()-1. The order in which the nonzeros are traversed is not specified and is up to the adapter implementation.
NumMyRowEntries: Provide the number of entries for a specified local row.
 An alternative is possible if you do not want to provide a non-trivial implementation of the ExtraMyEntryView
 methods (See Epetra_VbrRowMatrix for an example):
Implement ExtractMyRowCopy and NumMyRowEntries as above.
Implement ExtractMyEntryView (both versions) returning a -1 integer code with no other executable code.
Implement the RightScale and LeftScale methods non-trivially.
In addition, most adapters will probably re-implement the Multiply() method and perhaps the Solve() method, although one or the other may be implemented to return -1, signaling that there is no valid implementation. By default, the Multiply() method is implemented using ExtractMyRowCopy, which can usual be improved upon. By default Solve() and ApplyInverse() are implemented to return -1 (not implemented).
All other implemented methods in Epetra_BasicRowMatrix should not exhibit a signficant performance degradation, either because they are relatively small and fast, or because they are not a significant portion of the runtime for most codes. All methods are virtual, so they can be re-implemented by the adapter.
In addition to implementing the above methods, an adapter must inherit the Epetra_BasicRowMatrix interface and call the Epetra_BasicRowMatrix constructor as part of the adapter constructor. There are two constructors. The first requires the user to pass in the RowMap and ColMap, both of which are Epetra_Map objects. On each processor the RowMap (ColMap) must contain the global IDs (GIDs) of the rows (columns) that the processor cares about. The first constructor requires only these two maps, assuming that the RowMap will also serve as the DomainMap and RangeMap. In this case, the RowMap must be 1-to-1, meaning that if a global ID appears on one processor, it appears only once on that processor and does not appear on any other processor. For many sparse matrix data structures, it is the case that a given row is completely owned by one processor and that the global matrix is square. The first constructor is for this situation.
The second constructor allows the caller to specify all four maps. In this case the DomainMap, the layout of multivectors/vectors that are in the domain of the matrix (the x vector if computing y = A*x), must be 1-to-1. Also, the RangeMap, the layout of y must be 1-to-1. The RowMap and ColMap do not need to be 1-to-1, but the GIDs must be found in the RangeMap and DomainMap, respectively.
Note that Epetra_Operator is a base class for Epetra_RowMatrix, so any adapter for Epetra_BasicRowMatrix (or Epetra_RowMatrix) is also an adapter for Epetra_Operator.
An example of how to provide an adapter for Epetra_BasicRowMatrix can be found by looking at Epetra_JadMatrix.
Constructor & Destructor Documentation
Epetra_BasicRowMatrix()
Epetra_BasicRowMatrix::Epetra_BasicRowMatrix (const Epetra_Comm & Comm)
Epetra_BasicRowMatrix constructor.
This constructor requires a valid Epetra_Comm object as its only argument. The constructor will use Comm to build Epetra_Maps objects: RowMap, ColMap, DomainMap and RangeMap. However, these will be zero-length (trivial) maps that must be reset by calling one of the two SetMap() methods listed below.
Parameters
Comm [in] An Epetra_Comm containing a valid Comm object.
Member Function Documentation
Apply()
virtual int Epetra_BasicRowMatrix::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_RowMatrix applied to a Epetra_MultiVector X in Y.
Parameters
X (In) - A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Y (Out) - A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
References Epetra_RowMatrix::Multiply(), and UseTranspose().
ApplyInverse()
virtual int Epetra_BasicRowMatrix::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_RowMatrix inverse applied to an Epetra_MultiVector X in Y.
Parameters
X (In) - A Epetra_MultiVector of dimension NumVectors to solve for.
Y (Out) - A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code = -1.
Warning
This method is NOT supported.
Implements Epetra_Operator.
Comm()
virtual const Epetra_Comm & Epetra_BasicRowMatrix::Comm () const inline virtual
Returns a pointer to the Epetra_Comm communicator associated with this matrix.
Implements Epetra_Operator.
Exporter()
virtual const Epetra_Export * Epetra_BasicRowMatrix::Exporter () const inline virtual
Returns the Epetra_Export object that contains the export operations for distributed operations, returns zero if none.
If RowMatrixRowMap!=OperatorRangeMap, then this method returns a pointer to an Epetra_Export object that exports objects from an RowMatrixRowMap layout to a OperatorRangeMap layout. This operation is needed for sparse matrix-vector multiplication, y = Ax, to scatter-add y elements generated during local multiplication operations.
If RowMatrixRowMap==OperatorRangeMap, then the pointer will be returned as 0. For a typical Epetra_RowMatrix object, this pointer will be zero since it is often the case that RowMatrixRowMap==OperatorRangeMap.
Returns
Raw pointer to exporter. This exporter will be valid as long as the Epetra_RowMatrix object is valid.
ExtractDiagonalCopy()
virtual int Epetra_BasicRowMatrix::ExtractDiagonalCopy (Epetra_Vector & Diagonal) const virtual
Returns a copy of the main diagonal in a user-provided vector.
Parameters
Diagonal (Out) - Extracted main diagonal.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
ExtractMyEntryView() [1/2]
virtual int Epetra_BasicRowMatrix::ExtractMyEntryView (int CurEntry, double *& Value, int & RowIndex, int & ColIndex) pure virtual
Returns a reference to the ith entry in the matrix, along with its row and column index.
Parameters
CurEntry (In) - Index of local entry (from 0 to NumMyNonzeros()-1) to extract.
Value (Out) - Extracted reference to current values.
RowIndex (Out) - Row index for current entry.
ColIndex (Out) - Column index for current entry.
Returns
Integer error code, set to 0 if successful, set to -1 if CurEntry not valid.
Implemented in Epetra_JadMatrix, and Epetra_VbrRowMatrix.
ExtractMyEntryView() [2/2]
virtual int Epetra_BasicRowMatrix::ExtractMyEntryView (int CurEntry, double const *& Value, int & RowIndex, int & ColIndex) const pure virtual
Returns a const reference to the ith entry in the matrix, along with its row and column index.
Parameters
CurEntry (In) - Index of local entry (from 0 to NumMyNonzeros()-1) to extract.
Value (Out) - Extracted reference to current values.
RowIndex (Out) - Row index for current entry.
ColIndex (Out) - Column index for current entry.
Returns
Integer error code, set to 0 if successful, set to -1 if CurEntry not valid.
Implemented in Epetra_JadMatrix, and Epetra_VbrRowMatrix.
ExtractMyRowCopy()
virtual int Epetra_BasicRowMatrix::ExtractMyRowCopy (int MyRow, int Length, int & NumEntries, double * Values, int * Indices) const pure virtual
Returns a copy of the specified local row in user-provided arrays.
Parameters
MyRow (In) - Local row to extract.
Length (In) - Length of Values and Indices.
NumEntries (Out) - Number of nonzero entries extracted.
Values (Out) - Extracted values for this row.
Indices (Out) - Extracted global column indices for the corresponding values.
Returns
Integer error code, set to 0 if successful, set to -1 if MyRow not valid, -2 if Length is too short (NumEntries will have required length).
Implements Epetra_RowMatrix.
Implemented in Epetra_JadMatrix, and Epetra_VbrRowMatrix.
Filled()
virtual bool Epetra_BasicRowMatrix::Filled () const inline virtual
If FillComplete() has been called, this query returns true, otherwise it returns false, presently always returns true.
Implements Epetra_RowMatrix.
HasNormInf()
bool Epetra_BasicRowMatrix::HasNormInf () const inline virtual
Returns true because this class can compute an Inf-norm.
Implements Epetra_Operator.
Importer()
virtual const Epetra_Import * Epetra_BasicRowMatrix::Importer () const inline virtual
Returns the Epetra_Import object that contains the import operations for distributed operations, returns zero if none.
If RowMatrixColMap!=OperatorDomainMap, then this method returns a pointer to an Epetra_Import object that imports objects from an OperatorDomainMap layout to a RowMatrixColMap layout. This operation is needed for sparse matrix-vector multiplication, y = Ax, to gather x elements for local multiplication operations.
If RowMatrixColMap==OperatorDomainMap, then the pointer will be returned as 0.
Returns
Raw pointer to importer. This importer will be valid as long as the Epetra_RowMatrix object is valid.
InvColSums()
virtual int Epetra_BasicRowMatrix::InvColSums (Epetra_Vector & x) const virtual
Computes the sum of absolute values of the columns of the Epetra_BasicRowMatrix, results returned in x.
The vector x will return such that x[j] will contain the inverse of sum of the absolute values of the this matrix will be sca such that A(i,j) = x(j)*A(i,j) where i denotes the global row number of A and j denotes the global column number of A. Using the resulting vector from this function as input to RighttScale() will make the one norm of the resulting matrix exactly 1.
Parameters
x (Out) - An Epetra_Vector containing the column sums of the this matrix.
Warning
It is assumed that the distribution of x is the same as the rows of this.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
InvRowSums()
virtual int Epetra_BasicRowMatrix::InvRowSums (Epetra_Vector & x) const virtual
Computes the sum of absolute values of the rows of the Epetra_BasicRowMatrix, results returned in x.
The vector x will return such that x[i] will contain the inverse of sum of the absolute values of the this matrix will be scaled such that A(i,j) = x(i)*A(i,j) where i denotes the global row number of A and j denotes the global column number of A. Using the resulting vector from this function as input to LeftScale() will make the infinity norm of the resulting matrix exactly 1.
Parameters
x (Out) - An Epetra_Vector containing the row sums of the this matrix.
Warning
It is assumed that the distribution of x is the same as the rows of this.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Label()
virtual const char * Epetra_BasicRowMatrix::Label () const inline virtual
Returns a character string describing the operator.
Reimplemented from Epetra_Object.
References Epetra_Object::Label().
LeftScale()
virtual int Epetra_BasicRowMatrix::LeftScale (const Epetra_Vector & x) virtual
Scales the Epetra_BasicRowMatrix on the left with a Epetra_Vector x.
The this matrix will be scaled such that A(i,j) = x(i)*A(i,j) where i denotes the row number of A and j denotes the column number of A.
Parameters
x (In) - An Epetra_Vector to solve for.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Reimplemented in Epetra_VbrRowMatrix.
LowerTriangular()
bool Epetra_BasicRowMatrix::LowerTriangular () const inline virtual
If matrix is lower triangular, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
Map()
virtual const Epetra_BlockMap & Epetra_BasicRowMatrix::Map () const inline virtual
Implement the Epetra_SrcDistObjec::Map() function.
Implements Epetra_SrcDistObject.
References Epetra_RowMatrix::RowMatrixRowMap().
MaxNumEntries()
virtual int Epetra_BasicRowMatrix::MaxNumEntries () const inline virtual
Returns the maximum number of nonzero entries across all rows on this processor.
Implements Epetra_RowMatrix.
Multiply()
virtual int Epetra_BasicRowMatrix::Multiply (bool TransA, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Epetra_BasicRowMatrix multiplied by a Epetra_MultiVector X in Y.
Parameters
TransA (In) - If true, multiply by the transpose of matrix, otherwise just use matrix.
X (Out) - An Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Y (Out) - An Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Reimplemented in Epetra_JadMatrix, and Epetra_VbrRowMatrix.
NormInf()
virtual double Epetra_BasicRowMatrix::NormInf () const inline virtual
Returns the infinity norm of the global matrix.
Returns the quantity such that
.
Warning
This method is supported if and only if the Epetra_RowMatrix Object that was used to create this supports this method.
Implements Epetra_RowMatrix.
NormOne()
virtual double Epetra_BasicRowMatrix::NormOne () const inline virtual
Returns the one norm of the global matrix.
Returns the quantity such that
.
Warning
This method is supported if and only if the Epetra_RowMatrix Object that was used to create this supports this method.
Implements Epetra_RowMatrix.
NumGlobalCols()
virtual int Epetra_BasicRowMatrix::NumGlobalCols () const inline virtual
Returns the number of global matrix columns.
Implements Epetra_RowMatrix.
References Epetra_Operator::OperatorDomainMap().
NumGlobalCols64()
virtual long long Epetra_BasicRowMatrix::NumGlobalCols64 () const inline virtual
Implements Epetra_RowMatrix.
NumGlobalDiagonals()
virtual int Epetra_BasicRowMatrix::NumGlobalDiagonals () const inline virtual
Returns the number of global nonzero diagonal entries.
Implements Epetra_RowMatrix.
References Epetra_Operator::OperatorDomainMap().
NumGlobalDiagonals64()
virtual long long Epetra_BasicRowMatrix::NumGlobalDiagonals64 () const inline virtual
Implements Epetra_RowMatrix.
NumGlobalNonzeros()
virtual int Epetra_BasicRowMatrix::NumGlobalNonzeros () const inline virtual
Returns the number of nonzero entries in the global matrix.
Note that if the data decomposition is defined such that some nonzeros appear on multiple processors, then those nonzeros will be counted multiple times.
Implements Epetra_RowMatrix.
References Epetra_Operator::OperatorDomainMap(), and Epetra_Operator::OperatorRangeMap().
Referenced by Epetra_VbrRowMatrix::LeftScale(), and Epetra_VbrRowMatrix::RightScale().
NumGlobalNonzeros64()
virtual long long Epetra_BasicRowMatrix::NumGlobalNonzeros64 () const inline virtual
Implements Epetra_RowMatrix.
NumGlobalRows()
virtual int Epetra_BasicRowMatrix::NumGlobalRows () const inline virtual
Returns the number of global matrix rows.
Implements Epetra_RowMatrix.
References Epetra_Operator::OperatorRangeMap().
NumGlobalRows64()
virtual long long Epetra_BasicRowMatrix::NumGlobalRows64 () const inline virtual
Implements Epetra_RowMatrix.
NumMyCols()
virtual int Epetra_BasicRowMatrix::NumMyCols () const inline virtual
Returns the number of matrix columns owned by the calling processor.
Implements Epetra_RowMatrix.
References Epetra_RowMatrix::RowMatrixColMap().
NumMyDiagonals()
virtual int Epetra_BasicRowMatrix::NumMyDiagonals () const inline virtual
Returns the number of local nonzero diagonal entries.
Implements Epetra_RowMatrix.
References Epetra_Operator::OperatorRangeMap().
NumMyNonzeros()
virtual int Epetra_BasicRowMatrix::NumMyNonzeros () const inline virtual
Returns the number of nonzero entries in the calling processor's portion of the matrix.
Implements Epetra_RowMatrix.
NumMyRowEntries()
virtual int Epetra_BasicRowMatrix::NumMyRowEntries (int MyRow, int & NumEntries) const pure virtual
Return the current number of values stored for the specified local row.
Similar to NumMyEntries() except NumEntries is returned as an argument and error checking is done on the input value MyRow.
Parameters
MyRow (In) - Local row.
NumEntries (Out) - Number of nonzero values.
Returns
Integer error code, set to 0 if successful, set to -1 if MyRow not valid.
Implements Epetra_RowMatrix.
Implemented in Epetra_JadMatrix, and Epetra_VbrRowMatrix.
NumMyRows()
virtual int Epetra_BasicRowMatrix::NumMyRows () const inline virtual
Returns the number of matrix rows owned by the calling processor.
Implements Epetra_RowMatrix.
References Epetra_Operator::OperatorRangeMap().
OperatorDomainMap()
virtual const Epetra_Map & Epetra_BasicRowMatrix::OperatorDomainMap () const inline virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
OperatorRangeMap()
virtual const Epetra_Map & Epetra_BasicRowMatrix::OperatorRangeMap () const inline virtual
Returns the Epetra_Map object associated with the range of this operator (same as domain).
Implements Epetra_Operator.
Print()
virtual void Epetra_BasicRowMatrix::Print (std::ostream & os) const virtual
Print method.
Reimplemented from Epetra_Object.
RightScale()
virtual int Epetra_BasicRowMatrix::RightScale (const Epetra_Vector & x) virtual
Scales the Epetra_BasicRowMatrix on the right with a Epetra_Vector x.
The this matrix will be scaled such that A(i,j) = x(j)*A(i,j) where i denotes the global row number of A and j denotes the global column number of A.
Parameters
x (In) - The Epetra_Vector used for scaling this.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Reimplemented in Epetra_VbrRowMatrix.
RowMatrixColMap()
virtual const Epetra_Map & Epetra_BasicRowMatrix::RowMatrixColMap () const inline virtual
Returns the Column Map object needed for implementing Epetra_RowMatrix.
Implements Epetra_RowMatrix.
RowMatrixImporter()
virtual const Epetra_Import * Epetra_BasicRowMatrix::RowMatrixImporter () const inline virtual
Returns the Epetra_Import object that contains the import operations for distributed operations.
Implements Epetra_RowMatrix.
RowMatrixRowMap()
virtual const Epetra_Map & Epetra_BasicRowMatrix::RowMatrixRowMap () const inline virtual
Returns the Row Map object needed for implementing Epetra_RowMatrix.
Implements Epetra_RowMatrix.
SetMaps() [1/2]
void Epetra_BasicRowMatrix::SetMaps (const Epetra_Map & RowMap, const Epetra_Map & ColMap)
Set maps (Version 1); call this function or the next, but not both.
This method takes a row and column map. On each processor these maps describe the global rows and columns, resp, that the processor will care about. Note that the ColMap does not have to be one-to-one. In other words, a column ID can appear on more than one processor. The RowMap must be 1-to-1.
Parameters
RowMap [in] An Epetra_Map containing on each processor a list of GIDs of rows that the processor cares about.
ColMap [in] An Epetra_Map containing on each processor a list of GIDs of columns that the processor cares about.
In this method, the domain and range maps are assumed to be the same as the row map. Note that this requires that the global matrix be square. If the matrix is not square, or the domain vectors or range vectors do not have the same layout as the rows, then the second constructor should be called.
Referenced by Epetra_VbrRowMatrix::Epetra_VbrRowMatrix().
SetMaps() [2/2]
void Epetra_BasicRowMatrix::SetMaps (const Epetra_Map & RowMap, const Epetra_Map & ColMap, const Epetra_Map & DomainMap, const Epetra_Map & RangeMap)
Set maps (Version 2); call this function or the previous, but not both.
This constructor takes a row, column, domain and range map. On each processor these maps describe the global rows, columns, domain and range, resp, that the processor will care about. The domain and range maps must be one-to-one, but note that the row and column maps do not have to be one-to-one. In other words, a row ID can appear on more than one processor, as can a column ID.
Parameters
RowMap [in] An Epetra_Map containing on each processor a list of GIDs of rows that the processor cares about.
ColMap [in] An Epetra_Map containing on each processor a list of GIDs of columns that the processor cares about.
DomainMap [in] An Epetra_Map describing the distribution of domain vectors and multivectors.
RangeMap [in] An Epetra_Map describing the distribution of range vectors and multivectors.
SetUseTranspose()
virtual int Epetra_BasicRowMatrix::SetUseTranspose (bool use_transpose) inline virtual
If set true, transpose of this operator will be applied.
This flag allows the transpose of the given operator to be used implicitly. Setting this flag affects only the Apply() and ApplyInverse() methods. If the implementation of this interface does not support transpose use, this method should return a value of -1.
Parameters
use_transpose (In) - If true, multiply by the transpose of operator, otherwise just use operator.
Returns
Always returns 0.
Implements Epetra_Operator.
Solve()
virtual int Epetra_BasicRowMatrix::Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_BasicRowMatrix solve with a Epetra_MultiVector X in Y (not implemented).
Parameters
Upper (In) - If true, solve Ux = y, otherwise solve Lx = y.
Trans (In) - If true, solve transpose problem.
UnitDiagonal (In) - If true, assume diagonal is unit (whether it's stored or not).
X (In) - An Epetra_MultiVector of dimension NumVectors to solve for.
Y (Out) - An Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Reimplemented in Epetra_JadMatrix, and Epetra_VbrRowMatrix.
UpperTriangular()
virtual bool Epetra_BasicRowMatrix::UpperTriangular () const inline virtual
If matrix is upper triangular, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
UseTranspose()
virtual bool Epetra_BasicRowMatrix::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Referenced by Apply().
The documentation for this class was generated from the following file:
Epetra_BasicRowMatrix.h