Epetra: Epetra_InvOperator Class Reference
Epetra_InvOperator Class Reference
Epetra_InvOperator: An implementation of the Epetra_Operator class that reverses the role of Apply() and ApplyInverse() methods.
#include <Epetra_InvOperator.h>
Public Member Functions
Constructor
Epetra_InvOperator (Epetra_Operator *operatorIn)
Uses an Epetra_Operator instance to implement the Epetra_Operator interface.
virtual ~Epetra_InvOperator ()
Destructor.
Attribute set methods
int SetUseTranspose (bool UseTranspose_in)
If set true, transpose of this operator will be applied.
Mathematical functions
int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_InvOperator applied to a Epetra_MultiVector X in Y.
int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_InvOperator inverse applied to an Epetra_MultiVector X in Y.
double NormInf () const
Returns the infinity norm of the global matrix.
Public Member Functions inherited from Epetra_Operator
virtual ~Epetra_Operator ()
Destructor.
Attribute access functions
Epetra_Operator * operator_
std::string Label_
const char * Label () const
Returns a character std::string describing the operator.
Epetra_Operator * Operator () const
Returns a pointer to the Epetra_Operator operator object that was used to create this Epetra_InvOperator object.
bool UseTranspose () const
Returns the current UseTranspose setting.
bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_BlockMap object associated with the domain of this matrix operator.
const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Detailed Description
Epetra_InvOperator: An implementation of the Epetra_Operator class that reverses the role of Apply() and ApplyInverse() methods.
The Epetra_InvOperator class implements Epetra_Operator using another pre-constructed Epetra_Operator object. Once constructed, an Epetra_InvOperator can be used as the inverse of the input operator object as long as the appropriate Apply and ApplyInverse methods are implemented in the original Epetra_Operator object.
Constructor & Destructor Documentation
Epetra_InvOperator()
Epetra_InvOperator::Epetra_InvOperator (Epetra_Operator * operatorIn) inline
Uses an Epetra_Operator instance to implement the Epetra_Operator interface.
Facilitates the use of an Epetra_Operator instance as an inverse operator.
Parameters
In - A fully-constructed Epetra_Operator object.
References Epetra_Operator::Label().
Member Function Documentation
Apply()
int Epetra_InvOperator::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_InvOperator applied to a Epetra_MultiVector X in Y.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Warning
- This method has no effect and returns -1 as error code.
Implements Epetra_Operator.
References Epetra_Operator::ApplyInverse().
ApplyInverse()
int Epetra_InvOperator::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_InvOperator inverse applied to an Epetra_MultiVector X in Y.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
References Epetra_Operator::Apply().
Comm()
const Epetra_Comm & Epetra_InvOperator::Comm () const inline virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Epetra_Operator.
References Epetra_Operator::Comm().
HasNormInf()
bool Epetra_InvOperator::HasNormInf () const inline virtual
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
Implements Epetra_Operator.
References Epetra_Operator::HasNormInf().
Label()
const char * Epetra_InvOperator::Label () const inline virtual
Returns a character std::string describing the operator.
Implements Epetra_Operator.
NormInf()
double Epetra_InvOperator::NormInf () const inline virtual
Returns the infinity norm of the global matrix.
Implements Epetra_Operator.
References Epetra_Operator::NormInf().
OperatorDomainMap()
const Epetra_Map & Epetra_InvOperator::OperatorDomainMap () const inline virtual
Returns the Epetra_BlockMap object associated with the domain of this matrix operator.
Implements Epetra_Operator.
References Epetra_Operator::OperatorDomainMap(), Epetra_Operator::OperatorRangeMap(), and UseTranspose().
OperatorRangeMap()
const Epetra_Map & Epetra_InvOperator::OperatorRangeMap () const inline virtual
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Implements Epetra_Operator.
References Epetra_Operator::OperatorDomainMap(), Epetra_Operator::OperatorRangeMap(), and UseTranspose().
SetUseTranspose()
int Epetra_InvOperator::SetUseTranspose (bool UseTranspose_in) inline virtual
If set true, transpose of this operator will be applied.
This flag allows the transpose of the given operator to be used implicitly. Setting this flag affects only the Apply() and ApplyInverse() methods. If the implementation of this interface does not support transpose use, this method should return a value of -1.
Parameters
In UseTranspose_in - If true, multiply by the transpose of operator, otherwise just use operator.
Warning
- This method has no effect and returns -1 as error code.
Implements Epetra_Operator.
References Epetra_Operator::SetUseTranspose().
UseTranspose()
bool Epetra_InvOperator::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
References Epetra_Operator::UseTranspose().
Referenced by OperatorDomainMap(), and OperatorRangeMap().
The documentation for this class was generated from the following file:
Epetra_InvOperator.h