Epetra: Epetra_Operator Class Reference
Epetra_Operator Class Reference abstract
Epetra_Operator: A pure virtual class for using real-valued double-precision operators.
#include <Epetra_Operator.h>
Public Member Functions
Destructor
virtual ~Epetra_Operator ()
Destructor.
Attribute set methods
virtual int SetUseTranspose (bool UseTranspose)=0
If set true, transpose of this operator will be applied.
Mathematical functions
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const =0
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector X in Y.
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const =0
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector X in Y.
virtual double NormInf () const =0
Returns the infinity norm of the global matrix.
Attribute access functions
virtual const char * Label () const =0
Returns a character string describing the operator.
virtual bool UseTranspose () const =0
Returns the current UseTranspose setting.
virtual bool HasNormInf () const =0
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
virtual const Epetra_Comm & Comm () const =0
Returns a pointer to the Epetra_Comm communicator associated with this operator.
virtual const Epetra_Map & OperatorDomainMap () const =0
Returns the Epetra_Map object associated with the domain of this operator.
virtual const Epetra_Map & OperatorRangeMap () const =0
Returns the Epetra_Map object associated with the range of this operator.
Detailed Description
Epetra_Operator: A pure virtual class for using real-valued double-precision operators.
The Epetra_Operator class is a pure virtual class (specifies interface only) that enable the use of real-valued double-precision operators. It is currently implemented by both the Epetra_CrsMatrix and Epetra_VbrMatrix classes and the Ifpack_CrsRiluk preconditioner class.
Member Function Documentation
Apply()
virtual int Epetra_Operator::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const pure virtual
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector X in Y.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_InvOperator::ApplyInverse().
ApplyInverse()
virtual int Epetra_Operator::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const pure virtual
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector X in Y.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Warning
In order to work with AztecOO, any implementation of this method must support the case where X and Y are the same object.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_InvOperator::Apply().
Comm()
virtual const Epetra_Comm & Epetra_Operator::Comm () const pure virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_InvOperator::Comm().
HasNormInf()
virtual bool Epetra_Operator::HasNormInf () const pure virtual
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_InvOperator::HasNormInf().
Label()
virtual const char * Epetra_Operator::Label () const pure virtual
Returns a character string describing the operator.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_InvOperator::Epetra_InvOperator().
NormInf()
virtual double Epetra_Operator::NormInf () const pure virtual
Returns the infinity norm of the global matrix.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, Epetra_VbrMatrix, and Epetra_RowMatrix.
Referenced by Epetra_InvOperator::NormInf().
OperatorDomainMap()
virtual const Epetra_Map & Epetra_Operator::OperatorDomainMap () const pure virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_BasicRowMatrix::NumGlobalCols(), Epetra_BasicRowMatrix::NumGlobalDiagonals(), Epetra_BasicRowMatrix::NumGlobalNonzeros(), Epetra_InvOperator::OperatorDomainMap(), and Epetra_InvOperator::OperatorRangeMap().
OperatorRangeMap()
virtual const Epetra_Map & Epetra_Operator::OperatorRangeMap () const pure virtual
Returns the Epetra_Map object associated with the range of this operator.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_BasicRowMatrix::NumGlobalNonzeros(), Epetra_BasicRowMatrix::NumGlobalRows(), Epetra_BasicRowMatrix::NumMyDiagonals(), Epetra_BasicRowMatrix::NumMyRows(), Epetra_InvOperator::OperatorDomainMap(), and Epetra_InvOperator::OperatorRangeMap().
SetUseTranspose()
virtual int Epetra_Operator::SetUseTranspose (bool UseTranspose) pure virtual
If set true, transpose of this operator will be applied.
This flag allows the transpose of the given operator to be used implicitly. Setting this flag affects only the Apply() and ApplyInverse() methods. If the implementation of this interface does not support transpose use, this method should return a value of -1.
Parameters
In UseTranspose -If true, multiply by the transpose of operator, otherwise just use operator.
Returns
Integer error code, set to 0 if successful. Set to -1 if this implementation does not support transpose.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_FastCrsOperator, Epetra_CrsMatrix, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_InvOperator::SetUseTranspose().
UseTranspose()
virtual bool Epetra_Operator::UseTranspose () const pure virtual
Returns the current UseTranspose setting.
Implemented in Epetra_MsrMatrix, Epetra_BasicRowMatrix, Epetra_CrsMatrix, Epetra_FastCrsOperator, Epetra_InvOperator, and Epetra_VbrMatrix.
Referenced by Epetra_CrsMatrix::OperatorDomainMap(), Epetra_VbrMatrix::OperatorDomainMap(), Epetra_CrsMatrix::OperatorRangeMap(), Epetra_VbrMatrix::OperatorRangeMap(), and Epetra_InvOperator::UseTranspose().
The documentation for this class was generated from the following file:
Epetra_Operator.h