Phalanx: PHX::Evaluator< Traits > Class Template Reference
PHX::Evaluator< Traits > Class Template Reference abstract
#include <Phalanx_Evaluator.hpp>
Public Types
typedef PHX::Device execution_space
Public Member Functions
Evaluator ()
Ctor.
virtual ~Evaluator ()
Dtor.
virtual void postRegistrationSetup (typename Traits::SetupData d, PHX::FieldManager< Traits > &vm)=0
Allows providers to grab pointers to data arrays.
virtual const std::vector< Teuchos::RCP< FieldTag > > & evaluatedFields () const =0
Returns vector of fields that this object evaluates.
virtual const std::vector< Teuchos::RCP< FieldTag > > & contributedFields () const =0
Returns vector of fields that contribute partially to the evaluation of a field. This allows users to spread the evaluation of a field over multiple evaluators.
virtual const std::vector< Teuchos::RCP< FieldTag > > & dependentFields () const =0
Returns vector of fields needed to compute the evaluated fields.
virtual const std::vector< Teuchos::RCP< FieldTag > > & unsharedFields () const =0
Returns vector of fields that are not allowed to share memory with other fields.
virtual void evaluateFields (typename Traits::EvalData d)=0
Evaluate all fields that the provider supplies.
virtual void preEvaluate (typename Traits::PreEvalData d)=0
This routine is called before each residual/Jacobian fill.
virtual void postEvaluate (typename Traits::PostEvalData d)=0
This routine is called after each residual/Jacobian fill.
virtual const std::string & getName () const =0
Returns the name/identifier of this provider.
virtual void bindField (const PHX::FieldTag &ft, const std::any &f)=0
Binds memory to a field. WARNING: this is a POWER-USER function. Only use this if you understand the memory binding sequence (see detailed description for more information).
Device DAG Methods
Methods required for optional Device DAG cpability. The Device DAG capability allows for the entire DAG to be evaluated on device from a single kernel launch with a Kokkos::parallel_for. This capability requires that evaluators implement a stripped down PHX::DeviceEvaluator inside the standard evaluator that is suitable for constructing and executing on all device architectures of interest.
virtual PHX::DeviceEvaluator< Traits > * createDeviceEvaluator () const =0
Returns a DeviceEvaluator object instantiated on the Device using malloc and placement new so that vtable works properly. Only used for Device DAG support.
virtual void rebuildDeviceEvaluator (PHX::DeviceEvaluator< Traits > *e) const =0
Call dtor and then call placement new on the memory to rebind data. Needed to rebind unmanaged fields that are set after DeviceEvaluator is constructed in postRegistrationSetup(). Only used for Device DAG support.
virtual void deleteDeviceEvaluator (PHX::DeviceEvaluator< Traits > *e) const =0
Call dtor and delete device memory. Only used for Device DAG support.
virtual void printFieldValues (std::ostream &os) const =0
Print the field values for all fields in the evaluator.
Detailed Description
template<typename Traits>
class PHX::Evaluator< Traits >
Pure virtual base class that provides field evaluation routines to the FieldManager.
Member Function Documentation
bindField()
template<typename Traits > virtual void PHX::Evaluator< Traits >::bindField (const PHX::FieldTag & ft, const std::any & f) pure virtual
Binds memory to a field. WARNING: this is a POWER-USER function. Only use this if you understand the memory binding sequence (see detailed description for more information).
WARNING: This is a power user function. It sets/swaps the field memory for the supplied field (either an externally defined user managed field or an internally managed from the FieldManager). All evaluators that evaluate or depend on this field should be bound to the same memory. Otherwise you will get undefined results. To use this consistently, do not call this directly. Instead, bind all memory through calls to the PHX::FieldManager class.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
contributedFields()
template<typename Traits > virtual const std::vector< Teuchos::RCP< FieldTag > > & PHX::Evaluator< Traits >::contributedFields () const pure virtual
Returns vector of fields that contribute partially to the evaluation of a field. This allows users to spread the evaluation of a field over multiple evaluators.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
Referenced by PHX::DagManager< Traits >::printEvaluator().
createDeviceEvaluator()
template<typename Traits > virtual PHX::DeviceEvaluator< Traits > * PHX::Evaluator< Traits >::createDeviceEvaluator () const pure virtual
Returns a DeviceEvaluator object instantiated on the Device using malloc and placement new so that vtable works properly. Only used for Device DAG support.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
deleteDeviceEvaluator()
template<typename Traits > virtual void PHX::Evaluator< Traits >::deleteDeviceEvaluator (PHX::DeviceEvaluator< Traits > * e) const pure virtual
Call dtor and delete device memory. Only used for Device DAG support.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
dependentFields()
template<typename Traits > virtual const std::vector< Teuchos::RCP< FieldTag > > & PHX::Evaluator< Traits >::dependentFields () const pure virtual
Returns vector of fields needed to compute the evaluated fields.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
Referenced by PHX::DagManager< Traits >::printEvaluator().
evaluatedFields()
template<typename Traits > virtual const std::vector< Teuchos::RCP< FieldTag > > & PHX::Evaluator< Traits >::evaluatedFields () const pure virtual
Returns vector of fields that this object evaluates.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
Referenced by PHX::DagManager< Traits >::printEvaluator().
evaluateFields()
template<typename Traits > virtual void PHX::Evaluator< Traits >::evaluateFields (typename Traits::EvalData d) pure virtual
Evaluate all fields that the provider supplies.
Input:
Parameters
d - user defined data object defined by the EvalData typedef in the traits class.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >, PHX::AliasField< EvalT, Traits >, and PHX::UnmanagedFieldDummy< EvalT, Traits, FieldT >.
getName()
template<typename Traits > virtual const std::string & PHX::Evaluator< Traits >::getName () const pure virtual
Returns the name/identifier of this provider.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
Referenced by PHX::DagManager< Traits >::printEvaluator().
postEvaluate()
template<typename Traits > virtual void PHX::Evaluator< Traits >::postEvaluate (typename Traits::PostEvalData d) pure virtual
This routine is called after each residual/Jacobian fill.
This routine is called ONCE on the provider after the fill loop over cells is completed. This allows us to evaluate any post fill data. An example is to print out some statistics such as the maximum grid peclet number in a cell.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
postRegistrationSetup()
template<typename Traits > virtual void PHX::Evaluator< Traits >::postRegistrationSetup (typename Traits::SetupData d, PHX::FieldManager< Traits > & vm) pure virtual
Allows providers to grab pointers to data arrays.
Called once all providers are registered with the manager.
Once the field manager has allocated all data arrays, this method passes the field manager to the providers to allow each provider to grab and store pointers to the field data arrays. Grabbing the data arrays from the variable manager during an actual call to evaluateFields call is too slow due to the map lookup and FieldTag comparison (which uses a string compare). So lookups on field data are only allowed during this setup phase.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >, and PHX::AliasField< EvalT, Traits >.
preEvaluate()
template<typename Traits > virtual void PHX::Evaluator< Traits >::preEvaluate (typename Traits::PreEvalData d) pure virtual
This routine is called before each residual/Jacobian fill.
This routine is called ONCE on the provider before the fill loop over cells is started. This allows us to reset global objects between each fill. An example is to reset a provider that monitors the maximum grid peclet number in a cell. This call would zero out the maximum for a new fill.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
printFieldValues()
template<typename Traits > virtual void PHX::Evaluator< Traits >::printFieldValues (std::ostream & os) const pure virtual
Print the field values for all fields in the evaluator.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
rebuildDeviceEvaluator()
template<typename Traits > virtual void PHX::Evaluator< Traits >::rebuildDeviceEvaluator (PHX::DeviceEvaluator< Traits > * e) const pure virtual
Call dtor and then call placement new on the memory to rebind data. Needed to rebind unmanaged fields that are set after DeviceEvaluator is constructed in postRegistrationSetup(). Only used for Device DAG support.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
unsharedFields()
template<typename Traits > virtual const std::vector< Teuchos::RCP< FieldTag > > & PHX::Evaluator< Traits >::unsharedFields () const pure virtual
Returns vector of fields that are not allowed to share memory with other fields.
Implemented in PHX::EvaluatorWithBaseImpl< Traits >.
Referenced by PHX::DagManager< Traits >::printEvaluator().
The documentation for this class was generated from the following file:
Phalanx_Evaluator.hpp