Phalanx: PHX::EvaluatorWithBaseImpl< Traits > Class Template Reference
PHX::EvaluatorWithBaseImpl< Traits > Class Template Reference abstract
Class that implements helper functions for the pure virtual PHX::Evaluator class.
#include <Phalanx_Evaluator_WithBaseImpl.hpp>
Public Member Functions
EvaluatorWithBaseImpl (const std::string &evaluator_name)
virtual void addEvaluatedField (const PHX::FieldTag &ft)
template<typename DataT , typename... Props>
void addEvaluatedField (const PHX::MDField< DataT, Props... > &f)
template<typename DataT , int Rank, typename Layout >
void addEvaluatedField (const PHX::Field< DataT, Rank, Layout > &f)
template<typename DataT , typename... Props>
void addEvaluatedField (const PHX::FieldTag &ft, const Kokkos::View< DataT, Props... > &f)
virtual void addContributedField (const PHX::FieldTag &ft)
template<typename DataT , typename... Props>
void addContributedField (const PHX::MDField< DataT, Props... > &f)
template<typename DataT , int Rank, typename Layout >
void addContributedField (const PHX::Field< DataT, Rank, Layout > &f)
template<typename DataT , typename... Properties>
void addContributedField (const PHX::FieldTag &ft, const Kokkos::View< DataT, Properties... > &f)
virtual void addDependentField (const PHX::FieldTag &ft)
template<typename DataT , typename... Props>
void addNonConstDependentField (const PHX::MDField< DataT, Props... > &f)
template<typename DataT , typename... Props>
void addDependentField (const PHX::MDField< const DataT, Props... > &f)
template<typename DataT , int Rank, typename Layout >
void addDependentField (const PHX::Field< const DataT, Rank, Layout > &f)
template<typename DataT , typename... Properties>
void addDependentField (const PHX::FieldTag &ft, const Kokkos::View< DataT, Properties... > &f)
void addUnsharedField (const Teuchos::RCP< PHX::FieldTag > &ft)
virtual void setName (const std::string &name)
virtual void postRegistrationSetup (typename Traits::SetupData d, PHX::FieldManager< Traits > &vm) override
Allows providers to grab pointers to data arrays.
virtual const std::vector< Teuchos::RCP< FieldTag > > & evaluatedFields () const override
Returns vector of fields that this object evaluates.
virtual const std::vector< Teuchos::RCP< FieldTag > > & contributedFields () const override
Returns vector of fields that contribute partially to the evaluation of a field. This allows users to spread the evaluation of a field over multiple evaluators.
virtual const std::vector< Teuchos::RCP< FieldTag > > & dependentFields () const override
Returns vector of fields needed to compute the evaluated fields.
virtual const std::vector< Teuchos::RCP< FieldTag > > & unsharedFields () const override
Returns vector of fields that are not allowed to share memory with other fields.
virtual void evaluateFields (typename Traits::EvalData d) override=0
Evaluate all fields that the provider supplies.
virtual void preEvaluate (typename Traits::PreEvalData d) override
This routine is called before each residual/Jacobian fill.
virtual void postEvaluate (typename Traits::PostEvalData d) override
This routine is called after each residual/Jacobian fill.
virtual const std::string & getName () const override
Returns the name/identifier of this provider.
virtual void bindField (const PHX::FieldTag &ft, const std::any &f) override
Binds memory to a field. WARNING: this is a POWER-USER function. Only use this if you understand the memory binding sequence (see detailed description for more information).
virtual PHX::DeviceEvaluator< Traits > * createDeviceEvaluator () const override
Returns a DeviceEvaluator object instantiated on the Device using malloc and placement new so that vtable works properly. Only used for Device DAG support.
virtual void rebuildDeviceEvaluator (PHX::DeviceEvaluator< Traits > *e) const override
Call dtor and then call placement new on the memory to rebind data. Needed to rebind unmanaged fields that are set after DeviceEvaluator is constructed in postRegistrationSetup(). Only used for Device DAG support.
virtual void deleteDeviceEvaluator (PHX::DeviceEvaluator< Traits > *e) const override
Call dtor and delete device memory. Only used for Device DAG support.
virtual void printFieldValues (std::ostream &os) const override
Print the field values for all fields in the evaluator.
template<class DataT , class... Properties>
void addEvaluatedField (const PHX::FieldTag &ft, const Kokkos::View< DataT, Properties... > &f)
Public Member Functions inherited from PHX::Evaluator< Traits >
Evaluator ()
Ctor.
virtual ~Evaluator ()
Dtor.
Protected Member Functions
void addEvaluatedFieldTagIfNotAlreadyRegistered (const PHX::FieldTag &ft)
void addContributedFieldTagIfNotAlreadyRegistered (const PHX::FieldTag &ft)
void addDependentFieldTagIfNotAlreadyRegistered (const PHX::FieldTag &ft)
Additional Inherited Members
Public Types inherited from PHX::Evaluator< Traits >
typedef PHX::Device execution_space
Detailed Description
template<typename Traits>
class PHX::EvaluatorWithBaseImpl< Traits >
Class that implements helper functions for the pure virtual PHX::Evaluator class.
This class implements code that would essentially be repeated in each Evaluator class, making it quicker for developers to add new evaluators. All field evaluators should inherit from this class if possible instead of the base class so they don't have to code the same boilerplate in all evaluators, but this is not mandatory.
Member Function Documentation
addDependentField()
template<typename Traits > template<typename DataT , typename... Properties> void PHX::EvaluatorWithBaseImpl< Traits >::addDependentField (const PHX::FieldTag & ft, const Kokkos::View< DataT, Properties... > & f)
Add dependent field using raw Kokkos::View, DataT must be const.
NOTE: Since DataT is not a true scalar (it contains rank information as well), the template deduction fails if we try to enforce const on the DataT within the view (as we do for the other addDependentField() methods). We will enforce with a static_assert within this function instead. Not ideal. Could also work around with SFINAE but debugging would be more difficult.
References PHX::FieldTag::identifier().
addNonConstDependentField()
template<typename Traits > template<typename DataT , typename... Props> void PHX::EvaluatorWithBaseImpl< Traits >::addNonConstDependentField (const PHX::MDField< DataT, Props... > & f)
Add a non-const dependent field. Dependent fields should normally be const, but there are use cases that make this difficult. This method should only be used as a last resort.
References PHX::FieldTag::identifier().
addUnsharedField()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::addUnsharedField (const Teuchos::RCP< PHX::FieldTag > & ft)
Tells the field manager to NOT share this field's memory with any other field. Typically used for performance (e.g. don't have to zero out off diagonal components of derivative array).
bindField()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::bindField (const PHX::FieldTag & ft, const std::any & f) override virtual
Binds memory to a field. WARNING: this is a POWER-USER function. Only use this if you understand the memory binding sequence (see detailed description for more information).
WARNING: This is a power user function. It sets/swaps the field memory for the supplied field (either an externally defined user managed field or an internally managed from the FieldManager). All evaluators that evaluate or depend on this field should be bound to the same memory. Otherwise you will get undefined results. To use this consistently, do not call this directly. Instead, bind all memory through calls to the PHX::FieldManager class.
Implements PHX::Evaluator< Traits >.
References PHX::FieldTag::identifier().
contributedFields()
template<typename Traits > const std::vector< Teuchos::RCP< PHX::FieldTag > > & PHX::EvaluatorWithBaseImpl< Traits >::contributedFields () const override virtual
Returns vector of fields that contribute partially to the evaluation of a field. This allows users to spread the evaluation of a field over multiple evaluators.
Implements PHX::Evaluator< Traits >.
createDeviceEvaluator()
template<typename Traits > PHX::DeviceEvaluator< Traits > * PHX::EvaluatorWithBaseImpl< Traits >::createDeviceEvaluator () const override virtual
Returns a DeviceEvaluator object instantiated on the Device using malloc and placement new so that vtable works properly. Only used for Device DAG support.
Implements PHX::Evaluator< Traits >.
deleteDeviceEvaluator()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::deleteDeviceEvaluator (PHX::DeviceEvaluator< Traits > * e) const override virtual
Call dtor and delete device memory. Only used for Device DAG support.
Implements PHX::Evaluator< Traits >.
dependentFields()
template<typename Traits > const std::vector< Teuchos::RCP< PHX::FieldTag > > & PHX::EvaluatorWithBaseImpl< Traits >::dependentFields () const override virtual
Returns vector of fields needed to compute the evaluated fields.
Implements PHX::Evaluator< Traits >.
evaluatedFields()
template<typename Traits > const std::vector< Teuchos::RCP< PHX::FieldTag > > & PHX::EvaluatorWithBaseImpl< Traits >::evaluatedFields () const override virtual
Returns vector of fields that this object evaluates.
Implements PHX::Evaluator< Traits >.
evaluateFields()
template<typename Traits > virtual void PHX::EvaluatorWithBaseImpl< Traits >::evaluateFields (typename Traits::EvalData d) override pure virtual
Evaluate all fields that the provider supplies.
Input:
Parameters
d - user defined data object defined by the EvalData typedef in the traits class.
Implements PHX::Evaluator< Traits >.
Implemented in PHX::AliasField< EvalT, Traits >, and PHX::UnmanagedFieldDummy< EvalT, Traits, FieldT >.
getName()
template<typename Traits > const std::string & PHX::EvaluatorWithBaseImpl< Traits >::getName () const override virtual
Returns the name/identifier of this provider.
Implements PHX::Evaluator< Traits >.
postEvaluate()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::postEvaluate (typename Traits::PostEvalData d) override virtual
This routine is called after each residual/Jacobian fill.
This routine is called ONCE on the provider after the fill loop over cells is completed. This allows us to evaluate any post fill data. An example is to print out some statistics such as the maximum grid peclet number in a cell.
Implements PHX::Evaluator< Traits >.
postRegistrationSetup()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::postRegistrationSetup (typename Traits::SetupData d, PHX::FieldManager< Traits > & vm) override virtual
Allows providers to grab pointers to data arrays.
Called once all providers are registered with the manager.
Once the field manager has allocated all data arrays, this method passes the field manager to the providers to allow each provider to grab and store pointers to the field data arrays. Grabbing the data arrays from the variable manager during an actual call to evaluateFields call is too slow due to the map lookup and FieldTag comparison (which uses a string compare). So lookups on field data are only allowed during this setup phase.
Implements PHX::Evaluator< Traits >.
Reimplemented in PHX::AliasField< EvalT, Traits >.
preEvaluate()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::preEvaluate (typename Traits::PreEvalData d) override virtual
This routine is called before each residual/Jacobian fill.
This routine is called ONCE on the provider before the fill loop over cells is started. This allows us to reset global objects between each fill. An example is to reset a provider that monitors the maximum grid peclet number in a cell. This call would zero out the maximum for a new fill.
Implements PHX::Evaluator< Traits >.
printFieldValues()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::printFieldValues (std::ostream & os) const override virtual
Print the field values for all fields in the evaluator.
Implements PHX::Evaluator< Traits >.
rebuildDeviceEvaluator()
template<typename Traits > void PHX::EvaluatorWithBaseImpl< Traits >::rebuildDeviceEvaluator (PHX::DeviceEvaluator< Traits > * e) const override virtual
Call dtor and then call placement new on the memory to rebind data. Needed to rebind unmanaged fields that are set after DeviceEvaluator is constructed in postRegistrationSetup(). Only used for Device DAG support.
Implements PHX::Evaluator< Traits >.
unsharedFields()
template<typename Traits > const std::vector< Teuchos::RCP< PHX::FieldTag > > & PHX::EvaluatorWithBaseImpl< Traits >::unsharedFields () const override virtual
Returns vector of fields that are not allowed to share memory with other fields.
Implements PHX::Evaluator< Traits >.
The documentation for this class was generated from the following files:
Phalanx_Evaluator_WithBaseImpl.hpp
Phalanx_Evaluator_WithBaseImpl_Def.hpp