Phalanx: PHX::FieldTag Class Reference
PHX::FieldTag Class Reference abstract
Public Member Functions
virtual Teuchos::RCP< FieldTag > clone () const =0
virtual bool operator== (const FieldTag &t) const =0
virtual bool operator!= (const FieldTag &t) const
virtual const std::string & name () const =0
virtual const PHX::DataLayout & dataLayout () const =0
virtual PHX::DataLayout & nonConstDataLayout ()=0
virtual const std::type_info & dataTypeInfo () const =0
virtual const std::string identifier () const =0
Unique name identifier that can be used for strict weak ordering in stl std::map keys.
virtual void print (std::ostream &os) const =0
Member Function Documentation
identifier()
virtual const std::string PHX::FieldTag::identifier () const pure virtual
Unique name identifier that can be used for strict weak ordering in stl std::map keys.
Implemented in PHX::Tag< DataT >.
Referenced by PHX::EvaluatorWithBaseImpl< Traits >::addDependentField(), PHX::EvaluatorWithBaseImpl< Traits >::addNonConstDependentField(), PHX::EvaluationContainer< EvalT, Traits >::bindField(), PHX::EvaluatorWithBaseImpl< Traits >::bindField(), PHX::MemoryManager::createView(), PHX::MemoryManager::createViewFromAllocationTracker(), PHX::DagManager< Traits >::getEvaluatorsBindingField(), and PHX::EvaluationContainer< EvalT, Traits >::setUnmanagedField().
The documentation for this class was generated from the following file:
Phalanx_FieldTag.hpp