IFPACK: Ifpack_PointRelaxation Class Reference
Ifpack_PointRelaxation Class Reference
Ifpack_PointRelaxation: a class to define point relaxation preconditioners of for Epetra_RowMatrix's.
#include <Ifpack_PointRelaxation.h>
Public Member Functions
Ifpack_PointRelaxation (const Epetra_RowMatrix *Matrix)
Ifpack_PointRelaxation constructor with given Epetra_RowMatrix.
virtual ~Ifpack_PointRelaxation ()
Destructor.
virtual int SetUseTranspose (bool UseTranspose_in)
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Applies the matrix to an Epetra_MultiVector.
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Applies the preconditioner to X, returns the result in Y.
virtual double NormInf () const
Returns the infinity norm of the global matrix (not implemented)
virtual const char * Label () const
virtual bool UseTranspose () const
Returns the current UseTranspose setting.
virtual bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
virtual const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
virtual const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
virtual const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
virtual int Initialize ()
Computes all it is necessary to initialize the preconditioner.
virtual bool IsInitialized () const
Returns true if the preconditioner has been successfully initialized, false otherwise.
virtual bool IsComputed () const
Returns true if the preconditioner has been successfully computed.
virtual int Compute ()
Computes the preconditioners.
virtual const Epetra_RowMatrix & Matrix () const
Returns a pointer to the matrix to be preconditioned.
virtual double Condest (const Ifpack_CondestType CT=Ifpack_Cheap, const int MaxIters=1550, const double Tol=1e-9, Epetra_RowMatrix *Matrix=0)
Computes the condition number estimates and returns the value.
virtual double Condest () const
Returns the condition number estimate, or -1.0 if not computed.
virtual int SetParameters (Teuchos::ParameterList &List)
Sets all the parameters for the preconditioner.
virtual std::ostream & Print (std::ostream &os) const
Prints object to an output stream.
virtual int NumInitialize () const
Returns the number of calls to Initialize().
virtual int NumCompute () const
Returns the number of calls to Compute().
virtual int NumApplyInverse () const
Returns the number of calls to ApplyInverse().
virtual double InitializeTime () const
Returns the time spent in Initialize().
virtual double ComputeTime () const
Returns the time spent in Compute().
virtual double ApplyInverseTime () const
Returns the time spent in ApplyInverse().
virtual double InitializeFlops () const
Returns the number of flops in the initialization phase.
virtual double ComputeFlops () const
Returns the number of flops in the computation phase.
virtual double ApplyInverseFlops () const
Returns the number of flops for the application of the preconditioner.
Detailed Description
Ifpack_PointRelaxation: a class to define point relaxation preconditioners of for Epetra_RowMatrix's.
The Ifpack_PointRelaxation class enables the construction of point relaxation preconditioners of an Epetra_RowMatrix. Ifpack_PointRelaxation is derived from the Ifpack_Preconditioner class, which is itself derived from Epetra_Operator. Therefore this object can be used as preconditioner everywhere an ApplyInverse() method is required in the preconditioning step.
This class enables the construction of the following simple preconditioners:
Jacobi;
Gauss-Seidel;
symmetric Gauss-Seidel.
We now briefly describe the main features of the above preconditioners. Consider a linear system of type
\[ A x = b, \]
where \(A\) is a square, real matrix, and \(x, b\) are two real vectors. We begin with the decomposition
\[ A = D - E - F \]
where \(D\) is the diagonal of A, \(-E\) is the strict lower part, and \(-F\) is the strict upper part. It is assumed that the diagonal entries of \(A\) are different from zero.
Given an starting solution \(x_0\), an iteration of the (damped) Jacobi method can be written in matrix form as follows:
\[ x_{k+1} = \omega D^{-1}(E + F) x_k + D_{-1}b, \]
for \(k < k_{max}\), and \(\omega \) a damping parameter.
Using Ifpack_Jacobi, the user can apply the specified number of sweeps (\(k_{max}\)), and the damping parameter. If only one sweep is used, then the class simply applies the inverse of the diagonal of A to the input vector.
Given an starting solution \(x_0\), an iteration of the (damped) GaussSeidel method can be written in matrix form as follows:
\[ (D - E) x_{k+1} = \omega F x_k + b, \]
for \(k < k_{max}\), and \(\omega \) a damping parameter. Equivalently, the Gauss-Seidel preconditioner can be defined as
\[ P_{GS}^{-1} = (D - E)^{-1}. \]
Clearly, the role of E and F can be interchanged. However, Ifpack_GaussSeidel does not consider backward Gauss-Seidel methods.
For a list of supported parameters, please refer to page List of Supported Parameters.
The complete list of supported parameters is reported in page List of Supported Parameters. For a presentation of basic relaxation schemes, please refer to page Ifpack_PointRelaxation.
Author
Marzio Sala, SNL 9214.
Date
Last modified on 22-Jan-05.
Definition at line 136 of file Ifpack_PointRelaxation.h.
Constructor & Destructor Documentation
Ifpack_PointRelaxation()
Ifpack_PointRelaxation::Ifpack_PointRelaxation (const Epetra_RowMatrix * Matrix)
Ifpack_PointRelaxation constructor with given Epetra_RowMatrix.
Creates an instance of Ifpack_PointRelaxation class.
Parameters
Matrix - (In) Pointer to matrix to precondition.
Definition at line 62 of file Ifpack_PointRelaxation.cpp.
~Ifpack_PointRelaxation()
virtual Ifpack_PointRelaxation::~Ifpack_PointRelaxation () inline virtual
Destructor.
Definition at line 149 of file Ifpack_PointRelaxation.h.
Member Function Documentation
Apply()
virtual int Ifpack_PointRelaxation::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Applies the matrix to an Epetra_MultiVector.
Parameters
X - (In) A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Y - (Out) A Epetra_MultiVector of dimension NumVectors containing the result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
Definition at line 178 of file Ifpack_PointRelaxation.h.
References IsComputed(), Epetra_MultiVector::NumVectors(), and UseTranspose().
ApplyInverse()
int Ifpack_PointRelaxation::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Applies the preconditioner to X, returns the result in Y.
Parameters
X - (In) A Epetra_MultiVector of dimension NumVectors to be preconditioned.
Y - (InOut) A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Warning
This routine is NOT AztecOO complaint.
Implements Ifpack_Preconditioner.
Definition at line 413 of file Ifpack_PointRelaxation.cpp.
References IsComputed(), Epetra_MultiVector::NumVectors(), and Epetra_MultiVector::Pointers().
ApplyInverseFlops()
virtual double Ifpack_PointRelaxation::ApplyInverseFlops () const inline virtual
Returns the number of flops for the application of the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 334 of file Ifpack_PointRelaxation.h.
ApplyInverseTime()
virtual double Ifpack_PointRelaxation::ApplyInverseTime () const inline virtual
Returns the time spent in ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 316 of file Ifpack_PointRelaxation.h.
Comm()
const Epetra_Comm & Ifpack_PointRelaxation::Comm () const virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Epetra_Operator.
Definition at line 153 of file Ifpack_PointRelaxation.cpp.
Referenced by Initialize(), Print(), and SetParameters().
Compute()
int Ifpack_PointRelaxation::Compute () virtual
Computes the preconditioners.
Implements Ifpack_Preconditioner.
Definition at line 201 of file Ifpack_PointRelaxation.cpp.
References Initialize(), IsInitialized(), Matrix(), Epetra_RowMatrix::MaxNumEntries(), and Epetra_VbrMatrix::RowMap().
ComputeFlops()
virtual double Ifpack_PointRelaxation::ComputeFlops () const inline virtual
Returns the number of flops in the computation phase.
Implements Ifpack_Preconditioner.
Definition at line 328 of file Ifpack_PointRelaxation.h.
ComputeTime()
virtual double Ifpack_PointRelaxation::ComputeTime () const inline virtual
Returns the time spent in Compute().
Implements Ifpack_Preconditioner.
Definition at line 310 of file Ifpack_PointRelaxation.h.
Condest() [1/2]
virtual double Ifpack_PointRelaxation::Condest () const inline virtual
Returns the condition number estimate, or -1.0 if not computed.
Implements Ifpack_Preconditioner.
Definition at line 270 of file Ifpack_PointRelaxation.h.
Referenced by Print().
Condest() [2/2]
double Ifpack_PointRelaxation::Condest (const Ifpack_CondestType CT = Ifpack_Cheap, const int MaxIters = 1550, const double Tol = 1e-9, Epetra_RowMatrix * Matrix = 0) virtual
Computes the condition number estimates and returns the value.
Implements Ifpack_Preconditioner.
Definition at line 368 of file Ifpack_PointRelaxation.cpp.
References IsComputed().
HasNormInf()
virtual bool Ifpack_PointRelaxation::HasNormInf () const inline virtual
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
Implements Epetra_Operator.
Definition at line 224 of file Ifpack_PointRelaxation.h.
Initialize()
int Ifpack_PointRelaxation::Initialize () virtual
Computes all it is necessary to initialize the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 171 of file Ifpack_PointRelaxation.cpp.
References Comm(), and Matrix().
Referenced by Compute().
InitializeFlops()
virtual double Ifpack_PointRelaxation::InitializeFlops () const inline virtual
Returns the number of flops in the initialization phase.
Implements Ifpack_Preconditioner.
Definition at line 322 of file Ifpack_PointRelaxation.h.
InitializeTime()
virtual double Ifpack_PointRelaxation::InitializeTime () const inline virtual
Returns the time spent in Initialize().
Implements Ifpack_Preconditioner.
Definition at line 304 of file Ifpack_PointRelaxation.h.
IsComputed()
virtual bool Ifpack_PointRelaxation::IsComputed () const inline virtual
Returns true if the preconditioner has been successfully computed.
Implements Ifpack_Preconditioner.
Definition at line 246 of file Ifpack_PointRelaxation.h.
Referenced by Apply(), ApplyInverse(), and Condest().
IsInitialized()
virtual bool Ifpack_PointRelaxation::IsInitialized () const inline virtual
Returns true if the preconditioner has been successfully initialized, false otherwise.
Implements Ifpack_Preconditioner.
Definition at line 240 of file Ifpack_PointRelaxation.h.
Referenced by Compute().
Label()
virtual const char * Ifpack_PointRelaxation::Label () const inline virtual
Implements Epetra_Operator.
Definition at line 212 of file Ifpack_PointRelaxation.h.
Matrix()
virtual const Epetra_RowMatrix & Ifpack_PointRelaxation::Matrix () const inline virtual
Returns a pointer to the matrix to be preconditioned.
Implements Ifpack_Preconditioner.
Definition at line 258 of file Ifpack_PointRelaxation.h.
Referenced by Compute(), and Initialize().
NormInf()
virtual double Ifpack_PointRelaxation::NormInf () const inline virtual
Returns the infinity norm of the global matrix (not implemented)
Implements Epetra_Operator.
Definition at line 204 of file Ifpack_PointRelaxation.h.
NumApplyInverse()
virtual int Ifpack_PointRelaxation::NumApplyInverse () const inline virtual
Returns the number of calls to ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 298 of file Ifpack_PointRelaxation.h.
NumCompute()
virtual int Ifpack_PointRelaxation::NumCompute () const inline virtual
Returns the number of calls to Compute().
Implements Ifpack_Preconditioner.
Definition at line 292 of file Ifpack_PointRelaxation.h.
NumInitialize()
virtual int Ifpack_PointRelaxation::NumInitialize () const inline virtual
Returns the number of calls to Initialize().
Implements Ifpack_Preconditioner.
Definition at line 286 of file Ifpack_PointRelaxation.h.
OperatorDomainMap()
const Epetra_Map & Ifpack_PointRelaxation::OperatorDomainMap () const virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
Definition at line 159 of file Ifpack_PointRelaxation.cpp.
OperatorRangeMap()
const Epetra_Map & Ifpack_PointRelaxation::OperatorRangeMap () const virtual
Returns the Epetra_Map object associated with the range of this operator.
Implements Epetra_Operator.
Definition at line 165 of file Ifpack_PointRelaxation.cpp.
Print()
std::ostream & Ifpack_PointRelaxation::Print (std::ostream & os) const virtual
Prints object to an output stream.
Implements Ifpack_Preconditioner.
Definition at line 302 of file Ifpack_PointRelaxation.cpp.
References Comm(), Condest(), and Epetra_Comm::MinAll().
SetParameters()
int Ifpack_PointRelaxation::SetParameters (Teuchos::ParameterList & List) virtual
Sets all the parameters for the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 97 of file Ifpack_PointRelaxation.cpp.
References Comm().
SetUseTranspose()
virtual int Ifpack_PointRelaxation::SetUseTranspose (bool UseTranspose_in) inline virtual
This flag can be used to apply the preconditioner to the transpose of the input operator.
Returns
Integer error code, set to 0 if successful. Set to -1 if this implementation does not support transpose.
Implements Epetra_Operator.
Definition at line 159 of file Ifpack_PointRelaxation.h.
UseTranspose()
virtual bool Ifpack_PointRelaxation::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Definition at line 218 of file Ifpack_PointRelaxation.h.
Referenced by Apply().
The documentation for this class was generated from the following files:
Ifpack_PointRelaxation.h
Ifpack_PointRelaxation.cpp