IFPACK: Ifpack Class Reference
Ifpack Class Reference
Ifpack: a function class to define Ifpack preconditioners.
#include <Ifpack.h>
Public Types
enum parameter {
absolute_threshold , relative_threshold , drop_tolerance , fill_tolerance ,
relax_value , level_fill , level_overlap , num_steps ,
use_reciprocal , overlap_mode
}
enum EPrecType {
POINT_RELAXATION , POINT_RELAXATION_STAND_ALONE , BLOCK_RELAXATION , BLOCK_RELAXATION_STAND_ALONE ,
BLOCK_RELAXATION_STAND_ALONE_ILU , BLOCK_RELAXATION_STAND_ALONE_ILUT , BLOCK_RELAXATION_STAND_ALONE_IC , BLOCK_RELAXATION_STAND_ALONE_SILU ,
BLOCK_RELAXATION_STAND_ALONE_AMESOS , BLOCK_RELAXATION_AMESOS , AMESOS , AMESOS_STAND_ALONE ,
IC , IC_STAND_ALONE , ICT , ICT_STAND_ALONE ,
ILU , ILU_STAND_ALONE , ILUT , ILUT_STAND_ALONE ,
SILU , CHEBYSHEV , POLYNOMIAL , KRYLOV ,
IHSS , SORA , TRIDI_RELAXATION , TRIDI_RELAXATION_STAND_ALONE
}
Enum for the type of preconditioner.
Public Member Functions
Ifpack_Preconditioner * Create (const std::string PrecType, Epetra_RowMatrix *Matrix, const int overlap=0, bool overrideSerialDefault=false)
Creates an instance of Ifpack_Preconditioner given the std::string name of the preconditioner type (can fail with bad input).
int SetParameters (int argc, char *argv[], Teuchos::ParameterList &List, std::string &PrecType, int &Overlap)
Sets the options in List from the command line.
Static Public Member Functions
static const char * toString (const EPrecType precType)
Function that gives the std::string name for preconditioner given its enumerication value.
static Ifpack_Preconditioner * Create (EPrecType PrecType, Epetra_RowMatrix *Matrix, const int overlap=0, bool overrideSerialDefault=false)
Creates an instance of Ifpack_Preconditioner given the enum value of the preconditioner type (can not fail, no bad input possible).
Static Public Attributes
static const int numPrecTypes
static const EPrecType precTypeValues [numPrecTypes]
List of the preconditioner types as enum values .
static const char * precTypeNames [numPrecTypes]
List of preconditioner types as std::string values.
static const bool supportsUnsymmetric [numPrecTypes]
List of bools that determines if the preconditioner type supports unsymmetric matrices.
Detailed Description
Ifpack: a function class to define Ifpack preconditioners.
Class Ifpack is a function class, that contains just one method: Create(). Using Create(), users can easily define a variety of IFPACK preconditioners.
Create requires 3 arguments:
a std::string, indicating the preconditioner to be built;
a pointer to an Epetra_RowMatrix, representing the matrix to be used to define the preconditioner;
an interger (defaulted to 0), that specifies the amount of overlap among the processes.
The first argument can assume the following values:
"point relaxation" : returns an instance of Ifpack_AdditiveSchwarz<Ifpack_PointRelaxation> (no Additive Schwarz in serial)
"point relaxation stand-alone" : returns an instance of Ifpack_PointRelaxation (value of overlap is ignored).
"block relaxation" : returns an instance of Ifpack_AdditiveSchwarz<Ifpack_BlockRelaxation> (no Additive Schwarz in serial)
"block relaxation stand-alone)" : returns an instance of Ifpack_BlockRelaxation.
"Amesos" : returns an instance of Ifpack_AdditiveSchwarz<Ifpack_Amesos> (no Additive Schwarz in serial)
"Amesos stand-alone" : returns an instance of Ifpack_Amesos.
"IC" : returns an instance of Ifpack_AdditiveSchwarz<Ifpack_IC> (no Additive Schwarz in serial)
"IC stand-alone" : returns an instance of Ifpack_IC.
"ICT" : returns an instance of Ifpack_AdditiveSchwarz<Ifpack_ICT> (no Additive Schwarz in serial)
"ICT stand-alone" : returns an instance of Ifpack_ICT.
"ILU" : returns an instance of Ifpack_AdditiveSchwarz<Ifpack_ILU> (no Additive Schwarz in serial)
"ILU stand-alone" : returns an instance of Ifpack_ILU.
"ILUT" : returns an instance of Ifpack_AdditiveSchwarz<Ifpack_ILUT> (no Additive Schwarz in serial)
"ILUT stand-alone" : returns an instance of Ifpack_ILUT.
otherwise, Create() returns 0.
Note
Objects in stand-alone mode cannot use reordering, variable overlap, and singleton filters. However, their construction can be slightly faster than the non stand-alone counterpart.
The following fragment of code shows the basic usage of this class.
#include "Ifpack.h"
...
Ifpack Factory;
Epetra_RowMatrix* A; // A is FillComplete()'d.
std::string PrecType = "ILU"; // use incomplete LU on each process
int OverlapLevel = 1; // one row of overlap among the processes
Ifpack_Preconditioner* Prec = Factory.Create(PrecType, A, OverlapLevel);
assert (Prec != 0);
Teuchos::ParameterList List;
List.set("fact: level-of-fill", 5); // use ILU(5)
IFPACK_CHK_ERR(Prec->SetParameters(List));
IFPACK_CHK_ERR(Prec->Initialize());
IFPACK_CHK_ERR(Prec->Compute());
// now Prec can be used as AztecOO preconditioner
// like for instance
AztecOO AztecOOSolver(*Problem);
// specify solver
AztecOOSolver.SetAztecOption(AZ_solver,AZ_gmres);
AztecOOSolver.SetAztecOption(AZ_output,32);
// Set Prec as preconditioning operator
AztecOOSolver.SetPrecOperator(Prec);
// Call the solver
AztecOOSolver.Iterate(1550,1e-8);
// print information on stdout
cout << *Prec;
// delete the preconditioner
delete Prec;
Author
Marzio Sala, (formally) SNL org. 1414
Date
Last updated on 25-Jan-05.
Definition at line 144 of file Ifpack.h.
Member Enumeration Documentation
EPrecType
enum Ifpack::EPrecType
Enum for the type of preconditioner.
Definition at line 148 of file Ifpack.h.
parameter
enum Ifpack::parameter
Definition at line 63 of file ifp_parameters.h.
Member Function Documentation
Create() [1/2]
Ifpack_Preconditioner * Ifpack::Create (const std::string PrecType, Epetra_RowMatrix * Matrix, const int overlap = 0, bool overrideSerialDefault = false)
Creates an instance of Ifpack_Preconditioner given the std::string name of the preconditioner type (can fail with bad input).
Parameters
PrecType (In) - String name of preconditioner type to be created.
Matrix (In) - Matrix used to define the preconditioner
overlap (In) - specified overlap, defaulted to 0.
Returns 0 if the preconditioner with that input name does not exist. Otherwise, return a newly created preconditioner object. Note that the client is responsible for calling delete on the returned object once it is finished using it!
Definition at line 393 of file Ifpack.cpp.
References Create().
Create() [2/2]
Ifpack_Preconditioner * Ifpack::Create (EPrecType PrecType, Epetra_RowMatrix * Matrix, const int overlap = 0, bool overrideSerialDefault = false) static
Creates an instance of Ifpack_Preconditioner given the enum value of the preconditioner type (can not fail, no bad input possible).
Parameters
PrecType (In) - Enum value of preconditioner type to be created.
Matrix (In) - Matrix used to define the preconditioner
overlap (In) - specified overlap, defaulted to 0.
Definition at line 253 of file Ifpack.cpp.
References Epetra_Operator::Comm(), Create(), and Epetra_Comm::NumProc().
Referenced by Create(), and Create().
SetParameters()
int Ifpack::SetParameters (int argc, char * argv[], Teuchos::ParameterList & List, std::string & PrecType, int & Overlap)
Sets the options in List from the command line.
Note: If you want full support for all parameters, consider reading in a parameter list from an XML file as supported by the Teuchos helper function Teuchos::updateParametersFromXmlFile() or Teuchos::updateParametersFromXmlStream().
Definition at line 413 of file Ifpack.cpp.
References SetParameters().
Referenced by SetParameters().
toString()
static const char * Ifpack::toString (const EPrecType precType) inline static
Function that gives the std::string name for preconditioner given its enumerication value.
Definition at line 240 of file Ifpack.h.
Member Data Documentation
numPrecTypes
const int Ifpack::numPrecTypes static
Initial value:
=
    +7
    +4
    +8
    +2
    +7
Definition at line 201 of file Ifpack.h.
precTypeNames
const char * Ifpack::precTypeNames static
List of preconditioner types as std::string values.
Definition at line 145 of file Ifpack.h.
precTypeValues
const Ifpack::EPrecType Ifpack::precTypeValues static
List of the preconditioner types as enum values .
Definition at line 91 of file Ifpack.h.
supportsUnsymmetric
const bool Ifpack::supportsUnsymmetric static
List of bools that determines if the preconditioner type supports unsymmetric matrices.
Definition at line 199 of file Ifpack.h.
The documentation for this class was generated from the following files:
Ifpack.h
ifp_parameters.h
Ifpack.cpp