IFPACK: Ifpack_ReorderFilter Class Reference
Ifpack_ReorderFilter Class Reference
Ifpack_ReorderFilter: a class for light-weight reorder of local rows and columns of an Epetra_RowMatrix.
#include <Ifpack_ReorderFilter.h>
Public Member Functions
Ifpack_ReorderFilter (const Teuchos::RefCountPtr< Epetra_RowMatrix > &Matrix_in, const Teuchos::RefCountPtr< Ifpack_Reordering > &Reordering_in)
Ifpack_ReorderFilter (const Ifpack_ReorderFilter &RHS)
Copy constructor.
virtual ~Ifpack_ReorderFilter ()
Destructor.
Ifpack_ReorderFilter & operator= (const Ifpack_ReorderFilter &RHS)
Operator assignment.
virtual int NumMyRowEntries (int MyRow, int &NumEntries) const
Returns the number of local row entries.
virtual int MaxNumEntries () const
Returns maximum num entries.
virtual int ExtractMyRowCopy (int MyRow, int Length, int &NumEntries, double *Values, int *Indices) const
virtual int ExtractDiagonalCopy (Epetra_Vector &Diagonal) const
Extracts a copy of the diagonal of the reordered matrix.
virtual int Multiply (bool TransA, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Multiplies multi-vector X with the reordered matrix, returns result in Y.
virtual int Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Solve, not implemented.
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Applies the reordered matrix to multi-vector X, returns the result in Y.
virtual int ApplyInverse (const Epetra_MultiVector &, Epetra_MultiVector &) const
Applies the inverse of this operator (not implemented).
virtual int InvRowSums (Epetra_Vector &) const
Inverse of row sums (not implemented).
virtual int LeftScale (const Epetra_Vector &)
Left scale of the matrix (not implemented).
virtual int InvColSums (Epetra_Vector &) const
Inverse of column sums (not implemented).
virtual int RightScale (const Epetra_Vector &)
Right scale of the matrix (not implemented).
virtual bool Filled () const
Returns true is the matrix called FillComplete().
virtual double NormInf () const
Returns the infinite-norm.
virtual double NormOne () const
Returns the 1-norm.
virtual int NumGlobalNonzeros () const
Returns the number of global nonzero elements.
virtual int NumGlobalRows () const
Returns the number of global rows.
virtual int NumGlobalCols () const
Returns the number of global columns.
virtual int NumGlobalDiagonals () const
Returns the number of global diagonals.
virtual long long NumGlobalNonzeros64 () const
Returns the number of global nonzero elements.
virtual long long NumGlobalRows64 () const
Returns the number of global rows.
virtual long long NumGlobalCols64 () const
Returns the number of global columns.
virtual long long NumGlobalDiagonals64 () const
Returns the number of global diagonals.
virtual int NumMyNonzeros () const
Returns the number of local nonzero elements.
virtual int NumMyRows () const
Returns the number of local rows.
virtual int NumMyCols () const
Returns the number of local columns.
virtual int NumMyDiagonals () const
Returns the number of local diagonals.
virtual bool LowerTriangular () const
Returns true is the reordered matrix is lower triangular.
virtual bool UpperTriangular () const
Returns true is the reordered matrix is upper triangular.
virtual const Epetra_Map & RowMatrixRowMap () const
Returns the row matrix of the non-reordered matrix.
virtual const Epetra_Map & RowMatrixColMap () const
Returns the column matrix of the non-reordered matrix.
virtual const Epetra_Import * RowMatrixImporter () const
Returns the importer of the non-reordered matrix.
int SetUseTranspose (bool UseTranspose_in)
Sets the use of the transpose.
bool UseTranspose () const
Returns true if the transpose of this matrix is used.
bool HasNormInf () const
Returns true if this matrix has the infinite norm.
const Epetra_Comm & Comm () const
Returns the communicator.
const Epetra_Map & OperatorDomainMap () const
Returns the operator domain map of the non-reordered matrix.
const Epetra_Map & OperatorRangeMap () const
Returns the operator domain range of the non-reordered matrix.
const Epetra_BlockMap & Map () const
Returns the map of the non-reordered matrix.
const char * Label () const
Returns the label of this object.
Teuchos::RefCountPtr< Epetra_RowMatrix > Matrix () const
Returns a reference-counted pointer to the internally stored pointer to Epetra_RowMatrix.
Teuchos::RefCountPtr< Ifpack_Reordering > Reordering () const
Returns a reference-counted pointer to the internally stored pointer to Ifpack_Reordering..
Detailed Description
Ifpack_ReorderFilter: a class for light-weight reorder of local rows and columns of an Epetra_RowMatrix.
Class Ifpack_ReorderFilter enables a light-weight construction of reordered matrices.
This class is used in Ifpack_AdditiveSchwarz to reorder (if required by the user) the localized matrix. As the localized matrix is defined on a serial communicator only, all maps are trivial (as all elements reside on the same process). This class does not attemp to define properly reordered maps, hence it should not be used for distributed matrices.
To improve the performances of Ifpack_AdditiveSchwarz, some operations are not performed in the construction phase (like for instance the computation of the 1-norm and infinite-norm, of check whether the reordered matrix is lower/upper triangular or not).
Author
Marzio Sala, SNL 9214.
Date
Last modified: Oct-04.
Definition at line 87 of file Ifpack_ReorderFilter.h.
Constructor & Destructor Documentation
Ifpack_ReorderFilter() [1/2]
Ifpack_ReorderFilter::Ifpack_ReorderFilter (const Teuchos::RefCountPtr< Epetra_RowMatrix > & Matrix_in, const Teuchos::RefCountPtr< Ifpack_Reordering > & Reordering_in)
Definition at line 54 of file Ifpack_ReorderFilter.cpp.
Ifpack_ReorderFilter() [2/2]
Ifpack_ReorderFilter::Ifpack_ReorderFilter (const Ifpack_ReorderFilter & RHS)
Copy constructor.
Definition at line 64 of file Ifpack_ReorderFilter.cpp.
~Ifpack_ReorderFilter()
virtual Ifpack_ReorderFilter::~Ifpack_ReorderFilter () inline virtual
Destructor.
Definition at line 98 of file Ifpack_ReorderFilter.h.
Member Function Documentation
Apply()
int Ifpack_ReorderFilter::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Applies the reordered matrix to multi-vector X, returns the result in Y.
Implements Epetra_Operator.
Definition at line 147 of file Ifpack_ReorderFilter.cpp.
References Multiply(), and UseTranspose().
ApplyInverse()
virtual int Ifpack_ReorderFilter::ApplyInverse (const Epetra_MultiVector & , Epetra_MultiVector &) const inline virtual
Applies the inverse of this operator (not implemented).
Implements Epetra_Operator.
Definition at line 135 of file Ifpack_ReorderFilter.h.
Comm()
const Epetra_Comm & Ifpack_ReorderFilter::Comm () const inline virtual
Returns the communicator.
Implements Epetra_Operator.
Definition at line 307 of file Ifpack_ReorderFilter.h.
References Comm(), and Matrix().
Referenced by Comm().
ExtractDiagonalCopy()
int Ifpack_ReorderFilter::ExtractDiagonalCopy (Epetra_Vector & Diagonal) const virtual
Extracts a copy of the diagonal of the reordered matrix.
Implements Epetra_RowMatrix.
Definition at line 110 of file Ifpack_ReorderFilter.cpp.
References ExtractDiagonalCopy(), Epetra_DistObject::Map(), and Matrix().
Referenced by ExtractDiagonalCopy().
ExtractMyRowCopy()
int Ifpack_ReorderFilter::ExtractMyRowCopy (int MyRow, int Length, int & NumEntries, double * Values, int * Indices) const virtual
Implements Epetra_RowMatrix.
Definition at line 91 of file Ifpack_ReorderFilter.cpp.
Filled()
virtual bool Ifpack_ReorderFilter::Filled () const inline virtual
Returns true is the matrix called FillComplete().
Implements Epetra_RowMatrix.
Definition at line 166 of file Ifpack_ReorderFilter.h.
References Filled(), and Matrix().
Referenced by Filled().
HasNormInf()
bool Ifpack_ReorderFilter::HasNormInf () const inline virtual
Returns true if this matrix has the infinite norm.
Implements Epetra_Operator.
Definition at line 301 of file Ifpack_ReorderFilter.h.
InvColSums()
virtual int Ifpack_ReorderFilter::InvColSums (Epetra_Vector &) const inline virtual
Inverse of column sums (not implemented).
Implements Epetra_RowMatrix.
Definition at line 154 of file Ifpack_ReorderFilter.h.
InvRowSums()
virtual int Ifpack_ReorderFilter::InvRowSums (Epetra_Vector &) const inline virtual
Inverse of row sums (not implemented).
Implements Epetra_RowMatrix.
Definition at line 142 of file Ifpack_ReorderFilter.h.
Label()
const char * Ifpack_ReorderFilter::Label () const inline virtual
Returns the label of this object.
Implements Epetra_Operator.
Definition at line 331 of file Ifpack_ReorderFilter.h.
LeftScale()
virtual int Ifpack_ReorderFilter::LeftScale (const Epetra_Vector &) inline virtual
Left scale of the matrix (not implemented).
Implements Epetra_RowMatrix.
Definition at line 148 of file Ifpack_ReorderFilter.h.
LowerTriangular()
virtual bool Ifpack_ReorderFilter::LowerTriangular () const inline virtual
Returns true is the reordered matrix is lower triangular.
Implements Epetra_RowMatrix.
Definition at line 259 of file Ifpack_ReorderFilter.h.
Map()
const Epetra_BlockMap & Ifpack_ReorderFilter::Map () const inline virtual
Returns the map of the non-reordered matrix.
Implements Epetra_SrcDistObject.
Definition at line 325 of file Ifpack_ReorderFilter.h.
References Map(), and Matrix().
Referenced by Map().
Matrix()
Teuchos::RefCountPtr< Epetra_RowMatrix > Ifpack_ReorderFilter::Matrix () const inline
Returns a reference-counted pointer to the internally stored pointer to Epetra_RowMatrix.
Definition at line 336 of file Ifpack_ReorderFilter.h.
Referenced by Comm(), ExtractDiagonalCopy(), Filled(), Map(), Multiply(), NumGlobalCols(), NumGlobalCols64(), NumGlobalDiagonals(), NumGlobalDiagonals64(), NumGlobalNonzeros(), NumGlobalNonzeros64(), NumGlobalRows(), NumGlobalRows64(), NumMyCols(), NumMyDiagonals(), NumMyNonzeros(), NumMyRowEntries(), NumMyRows(), OperatorDomainMap(), OperatorRangeMap(), RowMatrixColMap(), RowMatrixImporter(), RowMatrixRowMap(), SetUseTranspose(), and UseTranspose().
MaxNumEntries()
virtual int Ifpack_ReorderFilter::MaxNumEntries () const inline virtual
Returns maximum num entries.
Implements Epetra_RowMatrix.
Definition at line 110 of file Ifpack_ReorderFilter.h.
Multiply()
int Ifpack_ReorderFilter::Multiply (bool TransA, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Multiplies multi-vector X with the reordered matrix, returns result in Y.
Implements Epetra_RowMatrix.
Definition at line 120 of file Ifpack_ReorderFilter.cpp.
References Epetra_DistObject::Map(), Matrix(), Multiply(), and Epetra_MultiVector::NumVectors().
Referenced by Apply(), and Multiply().
NormInf()
virtual double Ifpack_ReorderFilter::NormInf () const inline virtual
Returns the infinite-norm.
Implements Epetra_RowMatrix.
Definition at line 172 of file Ifpack_ReorderFilter.h.
NormOne()
virtual double Ifpack_ReorderFilter::NormOne () const inline virtual
Returns the 1-norm.
Implements Epetra_RowMatrix.
Definition at line 178 of file Ifpack_ReorderFilter.h.
NumGlobalCols()
virtual int Ifpack_ReorderFilter::NumGlobalCols () const inline virtual
Returns the number of global columns.
Implements Epetra_RowMatrix.
Definition at line 198 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalCols().
Referenced by NumGlobalCols().
NumGlobalCols64()
virtual long long Ifpack_ReorderFilter::NumGlobalCols64 () const inline virtual
Returns the number of global columns.
Definition at line 223 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalCols64().
Referenced by NumGlobalCols64().
NumGlobalDiagonals()
virtual int Ifpack_ReorderFilter::NumGlobalDiagonals () const inline virtual
Returns the number of global diagonals.
Implements Epetra_RowMatrix.
Definition at line 204 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalDiagonals().
Referenced by NumGlobalDiagonals().
NumGlobalDiagonals64()
virtual long long Ifpack_ReorderFilter::NumGlobalDiagonals64 () const inline virtual
Returns the number of global diagonals.
Definition at line 229 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalDiagonals64().
Referenced by NumGlobalDiagonals64().
NumGlobalNonzeros()
virtual int Ifpack_ReorderFilter::NumGlobalNonzeros () const inline virtual
Returns the number of global nonzero elements.
Implements Epetra_RowMatrix.
Definition at line 186 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalNonzeros().
Referenced by NumGlobalNonzeros().
NumGlobalNonzeros64()
virtual long long Ifpack_ReorderFilter::NumGlobalNonzeros64 () const inline virtual
Returns the number of global nonzero elements.
Definition at line 211 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalNonzeros64().
Referenced by NumGlobalNonzeros64().
NumGlobalRows()
virtual int Ifpack_ReorderFilter::NumGlobalRows () const inline virtual
Returns the number of global rows.
Implements Epetra_RowMatrix.
Definition at line 192 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalRows().
Referenced by NumGlobalRows().
NumGlobalRows64()
virtual long long Ifpack_ReorderFilter::NumGlobalRows64 () const inline virtual
Returns the number of global rows.
Definition at line 217 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumGlobalRows64().
Referenced by NumGlobalRows64().
NumMyCols()
virtual int Ifpack_ReorderFilter::NumMyCols () const inline virtual
Returns the number of local columns.
Implements Epetra_RowMatrix.
Definition at line 247 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumMyCols().
Referenced by NumMyCols().
NumMyDiagonals()
virtual int Ifpack_ReorderFilter::NumMyDiagonals () const inline virtual
Returns the number of local diagonals.
Implements Epetra_RowMatrix.
Definition at line 253 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumMyDiagonals().
Referenced by NumMyDiagonals().
NumMyNonzeros()
virtual int Ifpack_ReorderFilter::NumMyNonzeros () const inline virtual
Returns the number of local nonzero elements.
Implements Epetra_RowMatrix.
Definition at line 235 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumMyNonzeros().
Referenced by NumMyNonzeros().
NumMyRowEntries()
virtual int Ifpack_ReorderFilter::NumMyRowEntries (int MyRow, int & NumEntries) const inline virtual
Returns the number of local row entries.
Implements Epetra_RowMatrix.
Definition at line 104 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumMyRowEntries().
Referenced by NumMyRowEntries().
NumMyRows()
virtual int Ifpack_ReorderFilter::NumMyRows () const inline virtual
Returns the number of local rows.
Implements Epetra_RowMatrix.
Definition at line 241 of file Ifpack_ReorderFilter.h.
References Matrix(), and NumMyRows().
Referenced by NumMyRows().
operator=()
Ifpack_ReorderFilter & Ifpack_ReorderFilter::operator= (const Ifpack_ReorderFilter & RHS)
Operator assignment.
Definition at line 75 of file Ifpack_ReorderFilter.cpp.
OperatorDomainMap()
const Epetra_Map & Ifpack_ReorderFilter::OperatorDomainMap () const inline virtual
Returns the operator domain map of the non-reordered matrix.
Implements Epetra_Operator.
Definition at line 313 of file Ifpack_ReorderFilter.h.
References Matrix(), and OperatorDomainMap().
Referenced by OperatorDomainMap().
OperatorRangeMap()
const Epetra_Map & Ifpack_ReorderFilter::OperatorRangeMap () const inline virtual
Returns the operator domain range of the non-reordered matrix.
Implements Epetra_Operator.
Definition at line 319 of file Ifpack_ReorderFilter.h.
References Matrix(), and OperatorRangeMap().
Referenced by OperatorRangeMap().
Reordering()
Teuchos::RefCountPtr< Ifpack_Reordering > Ifpack_ReorderFilter::Reordering () const inline
Returns a reference-counted pointer to the internally stored pointer to Ifpack_Reordering..
Definition at line 341 of file Ifpack_ReorderFilter.h.
RightScale()
virtual int Ifpack_ReorderFilter::RightScale (const Epetra_Vector &) inline virtual
Right scale of the matrix (not implemented).
Implements Epetra_RowMatrix.
Definition at line 160 of file Ifpack_ReorderFilter.h.
RowMatrixColMap()
virtual const Epetra_Map & Ifpack_ReorderFilter::RowMatrixColMap () const inline virtual
Returns the column matrix of the non-reordered matrix.
Implements Epetra_RowMatrix.
Definition at line 277 of file Ifpack_ReorderFilter.h.
References Matrix(), and RowMatrixColMap().
Referenced by RowMatrixColMap().
RowMatrixImporter()
virtual const Epetra_Import * Ifpack_ReorderFilter::RowMatrixImporter () const inline virtual
Returns the importer of the non-reordered matrix.
Implements Epetra_RowMatrix.
Definition at line 283 of file Ifpack_ReorderFilter.h.
References Matrix(), and RowMatrixImporter().
Referenced by RowMatrixImporter().
RowMatrixRowMap()
virtual const Epetra_Map & Ifpack_ReorderFilter::RowMatrixRowMap () const inline virtual
Returns the row matrix of the non-reordered matrix.
Implements Epetra_RowMatrix.
Definition at line 271 of file Ifpack_ReorderFilter.h.
References Matrix(), and RowMatrixRowMap().
Referenced by RowMatrixRowMap().
SetUseTranspose()
int Ifpack_ReorderFilter::SetUseTranspose (bool UseTranspose_in) inline virtual
Sets the use of the transpose.
Implements Epetra_Operator.
Definition at line 289 of file Ifpack_ReorderFilter.h.
References Matrix(), and SetUseTranspose().
Referenced by SetUseTranspose().
Solve()
int Ifpack_ReorderFilter::Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Solve, not implemented.
Implements Epetra_RowMatrix.
Definition at line 139 of file Ifpack_ReorderFilter.cpp.
UpperTriangular()
virtual bool Ifpack_ReorderFilter::UpperTriangular () const inline virtual
Returns true is the reordered matrix is upper triangular.
Implements Epetra_RowMatrix.
Definition at line 265 of file Ifpack_ReorderFilter.h.
UseTranspose()
bool Ifpack_ReorderFilter::UseTranspose () const inline virtual
Returns true if the transpose of this matrix is used.
Implements Epetra_Operator.
Definition at line 295 of file Ifpack_ReorderFilter.h.
References Matrix(), and UseTranspose().
Referenced by Apply(), and UseTranspose().
The documentation for this class was generated from the following files:
Ifpack_ReorderFilter.h
Ifpack_ReorderFilter.cpp