IFPACK: Ifpack_DiagonalFilter Class Reference
Ifpack_DiagonalFilter Class Reference
Ifpack_DiagonalFilter: Filter to modify the diagonal entries of a given Epetra_RowMatrix.
#include <Ifpack_DiagonalFilter.h>
Public Member Functions
Ifpack_DiagonalFilter (const Teuchos::RefCountPtr< Epetra_RowMatrix > &Matrix, double AbsoluteThreshold, double RelativeThreshold)
Constructor.
virtual ~Ifpack_DiagonalFilter ()
Destructor.
virtual int NumMyRowEntries (int MyRow, int &NumEntries) const
Returns the number of entries in MyRow.
virtual int MaxNumEntries () const
Returns the maximum number of entries.
virtual int ExtractMyRowCopy (int MyRow, int Length, int &NumEntries, double *Values, int *Indices) const
virtual int ExtractDiagonalCopy (Epetra_Vector &Diagonal) const
virtual int Multiply (bool TransA, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
virtual int Solve (bool, bool, bool, const Epetra_MultiVector &, Epetra_MultiVector &) const
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
virtual int ApplyInverse (const Epetra_MultiVector &, Epetra_MultiVector &) const
virtual int InvRowSums (Epetra_Vector &) const
virtual int LeftScale (const Epetra_Vector &x)
virtual int InvColSums (Epetra_Vector &) const
virtual int RightScale (const Epetra_Vector &x)
virtual bool Filled () const
virtual double NormInf () const
Not implemented for efficiency reasons.
virtual double NormOne () const
Not implemented for efficiency reasons.
virtual int NumGlobalNonzeros () const
virtual int NumGlobalRows () const
virtual int NumGlobalCols () const
virtual int NumGlobalDiagonals () const
virtual long long NumGlobalNonzeros64 () const
virtual long long NumGlobalRows64 () const
virtual long long NumGlobalCols64 () const
virtual long long NumGlobalDiagonals64 () const
virtual int NumMyNonzeros () const
virtual int NumMyRows () const
virtual int NumMyCols () const
virtual int NumMyDiagonals () const
virtual bool LowerTriangular () const
virtual bool UpperTriangular () const
virtual const Epetra_Map & RowMatrixRowMap () const
virtual const Epetra_Map & RowMatrixColMap () const
virtual const Epetra_Import * RowMatrixImporter () const
int SetUseTranspose (bool UseTranspose_in)
bool UseTranspose () const
bool HasNormInf () const
Not implemented for efficiency reasons.
const Epetra_Comm & Comm () const
const Epetra_Map & OperatorDomainMap () const
const Epetra_Map & OperatorRangeMap () const
const Epetra_BlockMap & Map () const
const char * Label () const
Detailed Description
Ifpack_DiagonalFilter: Filter to modify the diagonal entries of a given Epetra_RowMatrix.
Ifpack_DiagonalFilter modifies the elements on the diagonal.
A typical use is as follows:
Teuchos::RefCountPtr<Epetra_RowMatrix> A;
// creates a matrix B such that
// B(i,i) = AbsoluteThreshold * sgn(B(i,i)) +
//          RelativeThreshold * B(i,i)
double AbsoluteThreshold = 1e-3;
double RelativeThreshold = 1.01;
Ifpack_DiagonalFilter B(A, AbsoluteThreshold, RelativeThreshold);
Author
Marzio Sala, SNL 9214.
\data Last modified on 24-Jan-05.
Definition at line 86 of file Ifpack_DiagonalFilter.h.
Constructor & Destructor Documentation
Ifpack_DiagonalFilter()
Ifpack_DiagonalFilter::Ifpack_DiagonalFilter (const Teuchos::RefCountPtr< Epetra_RowMatrix > & Matrix, double AbsoluteThreshold, double RelativeThreshold)
Constructor.
Definition at line 53 of file Ifpack_DiagonalFilter.cpp.
References Epetra_Time::ElapsedTime(), and MaxNumEntries().
~Ifpack_DiagonalFilter()
virtual Ifpack_DiagonalFilter::~Ifpack_DiagonalFilter () inline virtual
Destructor.
Definition at line 95 of file Ifpack_DiagonalFilter.h.
Member Function Documentation
Apply()
virtual int Ifpack_DiagonalFilter::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Implements Epetra_Operator.
Definition at line 128 of file Ifpack_DiagonalFilter.h.
ApplyInverse()
virtual int Ifpack_DiagonalFilter::ApplyInverse (const Epetra_MultiVector & , Epetra_MultiVector &) const inline virtual
Implements Epetra_Operator.
Definition at line 135 of file Ifpack_DiagonalFilter.h.
Comm()
const Epetra_Comm & Ifpack_DiagonalFilter::Comm () const inline virtual
Implements Epetra_Operator.
Definition at line 281 of file Ifpack_DiagonalFilter.h.
ExtractDiagonalCopy()
virtual int Ifpack_DiagonalFilter::ExtractDiagonalCopy (Epetra_Vector & Diagonal) const inline virtual
Implements Epetra_RowMatrix.
Definition at line 112 of file Ifpack_DiagonalFilter.h.
ExtractMyRowCopy()
int Ifpack_DiagonalFilter::ExtractMyRowCopy (int MyRow, int Length, int & NumEntries, double * Values, int * Indices) const inline virtual
Implements Epetra_RowMatrix.
Definition at line 94 of file Ifpack_DiagonalFilter.cpp.
Filled()
virtual bool Ifpack_DiagonalFilter::Filled () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 161 of file Ifpack_DiagonalFilter.h.
HasNormInf()
bool Ifpack_DiagonalFilter::HasNormInf () const inline virtual
Not implemented for efficiency reasons.
Implements Epetra_Operator.
Definition at line 276 of file Ifpack_DiagonalFilter.h.
InvColSums()
virtual int Ifpack_DiagonalFilter::InvColSums (Epetra_Vector &) const inline virtual
Implements Epetra_RowMatrix.
Definition at line 151 of file Ifpack_DiagonalFilter.h.
InvRowSums()
virtual int Ifpack_DiagonalFilter::InvRowSums (Epetra_Vector &) const inline virtual
Implements Epetra_RowMatrix.
Definition at line 141 of file Ifpack_DiagonalFilter.h.
Label()
const char * Ifpack_DiagonalFilter::Label () const inline virtual
Implements Epetra_Operator.
Definition at line 301 of file Ifpack_DiagonalFilter.h.
LeftScale()
virtual int Ifpack_DiagonalFilter::LeftScale (const Epetra_Vector & x) inline virtual
Implements Epetra_RowMatrix.
Definition at line 146 of file Ifpack_DiagonalFilter.h.
LowerTriangular()
virtual bool Ifpack_DiagonalFilter::LowerTriangular () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 240 of file Ifpack_DiagonalFilter.h.
Map()
const Epetra_BlockMap & Ifpack_DiagonalFilter::Map () const inline virtual
Implements Epetra_SrcDistObject.
Definition at line 296 of file Ifpack_DiagonalFilter.h.
MaxNumEntries()
virtual int Ifpack_DiagonalFilter::MaxNumEntries () const inline virtual
Returns the maximum number of entries.
Implements Epetra_RowMatrix.
Definition at line 104 of file Ifpack_DiagonalFilter.h.
Referenced by Ifpack_DiagonalFilter().
Multiply()
int Ifpack_DiagonalFilter::Multiply (bool TransA, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Implements Epetra_RowMatrix.
Definition at line 109 of file Ifpack_DiagonalFilter.cpp.
NormInf()
virtual double Ifpack_DiagonalFilter::NormInf () const inline virtual
Not implemented for efficiency reasons.
Implements Epetra_RowMatrix.
Definition at line 167 of file Ifpack_DiagonalFilter.h.
NormOne()
virtual double Ifpack_DiagonalFilter::NormOne () const inline virtual
Not implemented for efficiency reasons.
Implements Epetra_RowMatrix.
Definition at line 173 of file Ifpack_DiagonalFilter.h.
NumGlobalCols()
virtual int Ifpack_DiagonalFilter::NumGlobalCols () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 189 of file Ifpack_DiagonalFilter.h.
NumGlobalCols64()
virtual long long Ifpack_DiagonalFilter::NumGlobalCols64 () const inline virtual
Definition at line 210 of file Ifpack_DiagonalFilter.h.
NumGlobalDiagonals()
virtual int Ifpack_DiagonalFilter::NumGlobalDiagonals () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 194 of file Ifpack_DiagonalFilter.h.
NumGlobalDiagonals64()
virtual long long Ifpack_DiagonalFilter::NumGlobalDiagonals64 () const inline virtual
Definition at line 215 of file Ifpack_DiagonalFilter.h.
NumGlobalNonzeros()
virtual int Ifpack_DiagonalFilter::NumGlobalNonzeros () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 179 of file Ifpack_DiagonalFilter.h.
NumGlobalNonzeros64()
virtual long long Ifpack_DiagonalFilter::NumGlobalNonzeros64 () const inline virtual
Definition at line 200 of file Ifpack_DiagonalFilter.h.
NumGlobalRows()
virtual int Ifpack_DiagonalFilter::NumGlobalRows () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 184 of file Ifpack_DiagonalFilter.h.
NumGlobalRows64()
virtual long long Ifpack_DiagonalFilter::NumGlobalRows64 () const inline virtual
Definition at line 205 of file Ifpack_DiagonalFilter.h.
NumMyCols()
virtual int Ifpack_DiagonalFilter::NumMyCols () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 230 of file Ifpack_DiagonalFilter.h.
NumMyDiagonals()
virtual int Ifpack_DiagonalFilter::NumMyDiagonals () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 235 of file Ifpack_DiagonalFilter.h.
NumMyNonzeros()
virtual int Ifpack_DiagonalFilter::NumMyNonzeros () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 220 of file Ifpack_DiagonalFilter.h.
NumMyRowEntries()
virtual int Ifpack_DiagonalFilter::NumMyRowEntries (int MyRow, int & NumEntries) const inline virtual
Returns the number of entries in MyRow.
Implements Epetra_RowMatrix.
Definition at line 98 of file Ifpack_DiagonalFilter.h.
NumMyRows()
virtual int Ifpack_DiagonalFilter::NumMyRows () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 225 of file Ifpack_DiagonalFilter.h.
OperatorDomainMap()
const Epetra_Map & Ifpack_DiagonalFilter::OperatorDomainMap () const inline virtual
Implements Epetra_Operator.
Definition at line 286 of file Ifpack_DiagonalFilter.h.
OperatorRangeMap()
const Epetra_Map & Ifpack_DiagonalFilter::OperatorRangeMap () const inline virtual
Implements Epetra_Operator.
Definition at line 291 of file Ifpack_DiagonalFilter.h.
RightScale()
virtual int Ifpack_DiagonalFilter::RightScale (const Epetra_Vector & x) inline virtual
Implements Epetra_RowMatrix.
Definition at line 156 of file Ifpack_DiagonalFilter.h.
RowMatrixColMap()
virtual const Epetra_Map & Ifpack_DiagonalFilter::RowMatrixColMap () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 255 of file Ifpack_DiagonalFilter.h.
RowMatrixImporter()
virtual const Epetra_Import * Ifpack_DiagonalFilter::RowMatrixImporter () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 260 of file Ifpack_DiagonalFilter.h.
RowMatrixRowMap()
virtual const Epetra_Map & Ifpack_DiagonalFilter::RowMatrixRowMap () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 250 of file Ifpack_DiagonalFilter.h.
SetUseTranspose()
int Ifpack_DiagonalFilter::SetUseTranspose (bool UseTranspose_in) inline virtual
Implements Epetra_Operator.
Definition at line 265 of file Ifpack_DiagonalFilter.h.
Solve()
virtual int Ifpack_DiagonalFilter::Solve (bool , bool , bool , const Epetra_MultiVector & , Epetra_MultiVector &) const inline virtual
Implements Epetra_RowMatrix.
Definition at line 121 of file Ifpack_DiagonalFilter.h.
UpperTriangular()
virtual bool Ifpack_DiagonalFilter::UpperTriangular () const inline virtual
Implements Epetra_RowMatrix.
Definition at line 245 of file Ifpack_DiagonalFilter.h.
UseTranspose()
bool Ifpack_DiagonalFilter::UseTranspose () const inline virtual
Implements Epetra_Operator.
Definition at line 270 of file Ifpack_DiagonalFilter.h.
The documentation for this class was generated from the following files:
Ifpack_DiagonalFilter.h
Ifpack_DiagonalFilter.cpp