IFPACK: Ifpack_ICT Class Reference
Ifpack_ICT Class Reference
Ifpack_ICT: A class for constructing and using an incomplete Cholesky factorization of a given Epetra_RowMatrix.
#include <Ifpack_ICT.h>
Public Member Functions
Ifpack_ICT (const Epetra_RowMatrix *A)
Ifpack_ICT constuctor with variable number of indices per row.
virtual ~Ifpack_ICT ()
Ifpack_ICT Destructor.
int SetParameters (Teuchos::ParameterList &parameterlis)
Set parameters using a Teuchos::ParameterList object.
const Epetra_RowMatrix & Matrix () const
Returns a reference to the matrix to be preconditioned.
bool IsInitialized () const
Returns true is the preconditioner has been successfully initialized.
int Initialize ()
Initialize L and U with values from user matrix A.
int Compute ()
Compute IC factor U using the specified graph, diagonal perturbation thresholds and relaxation parameters.
bool IsComputed () const
If factor is completed, this query returns true, otherwise it returns false.
int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Ifpack_ICT forward/back solve on a Epetra_MultiVector X in Y.
int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
double Condest (const Ifpack_CondestType CT=Ifpack_Cheap, const int MaxIters=1550, const double Tol=1e-9, Epetra_RowMatrix *Matrix_in=0)
Returns the maximum over all the condition number estimate for each local ILU set of factors.
double Condest () const
Returns the computed condition number estimate, or -1.0 if not computed.
int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global graph.
long long NumGlobalNonzeros64 () const
int NumMyNonzeros () const
Returns the number of nonzero entries in the local graph.
const Epetra_CrsMatrix & H () const
Returns the address of the D factor associated with this factored matrix.
int SetUseTranspose (bool UseTranspose_in)
If set true, transpose of this operator will be applied.
double NormInf () const
Returns 0.0 because this class cannot compute Inf-norm.
bool HasNormInf () const
Returns false because this class cannot compute an Inf-norm.
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
const Epetra_Comm & Comm () const
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
const char * Label () const
int SetLabel (const char *Label_in)
virtual std::ostream & Print (std::ostream &os) const
Prints basic information on iostream. This function is used by operator<<.
virtual int NumInitialize () const
Returns the number of calls to Initialize().
virtual int NumCompute () const
Returns the number of calls to Compute().
virtual int NumApplyInverse () const
Returns the number of calls to ApplyInverse().
virtual double InitializeTime () const
Returns the time spent in Initialize().
virtual double ComputeTime () const
Returns the time spent in Compute().
virtual double ApplyInverseTime () const
Returns the time spent in ApplyInverse().
virtual double InitializeFlops () const
Returns the number of flops in the initialization phase.
virtual double ComputeFlops () const
Returns the number of flops in all applications of Compute().
virtual double ApplyInverseFlops () const
Returns the number of flops in all applications of ApplyInverse().
double LevelOfFill () const
Returns the level-of-fill.
double AbsoluteThreshold () const
Returns the absolute threshold.
double RelativeThreshold () const
Returns the relative threshold.
double RelaxValue () const
Returns the relaxation value.
double DropTolerance () const
Returns the drop threshold.
Detailed Description
Ifpack_ICT: A class for constructing and using an incomplete Cholesky factorization of a given Epetra_RowMatrix.
The Ifpack_ICT class computes a threshold based incomplete LDL^T factorization of a given Epetra_RowMatrix. The factorization that is produced is a function of several parameters:
Maximum number of entries per row/column in factor - The factorization will contain at most this number of nonzero terms in each row/column of the factorization.
Diagonal perturbation - Prior to computing the factorization, it is possible to modify the diagonal entries of the matrix for which the factorization will be computing. If the absolute and relative perturbation values are zero and one, respectively, the factorization will be compute for the original user matrix A. Otherwise, the factorization will computed for a matrix that differs from the original user matrix in the diagonal values only. Details can be found in ifp_diag_pert.
Definition at line 89 of file Ifpack_ICT.h.
Constructor & Destructor Documentation
Ifpack_ICT()
Ifpack_ICT::Ifpack_ICT (const Epetra_RowMatrix * A)
Ifpack_ICT constuctor with variable number of indices per row.
Creates a Ifpack_ICT object and allocates storage.
Parameters
In A - User matrix to be factored.
In Graph - Graph generated by Ifpack_IlukGraph.
Definition at line 63 of file Ifpack_ICT.cpp.
~Ifpack_ICT()
Ifpack_ICT::~Ifpack_ICT () virtual
Ifpack_ICT Destructor.
Definition at line 91 of file Ifpack_ICT.cpp.
Member Function Documentation
AbsoluteThreshold()
double Ifpack_ICT::AbsoluteThreshold () const inline
Returns the absolute threshold.
Definition at line 311 of file Ifpack_ICT.h.
Referenced by Print(), and SetParameters().
Apply()
int Ifpack_ICT::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Implements Epetra_Operator.
Definition at line 494 of file Ifpack_ICT.cpp.
ApplyInverse()
int Ifpack_ICT::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Ifpack_ICT forward/back solve on a Epetra_MultiVector X in Y.
Parameters
In Trans -If true, solve transpose problem.
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
Implements Ifpack_Preconditioner.
Definition at line 455 of file Ifpack_ICT.cpp.
References Epetra_Time::ElapsedTime(), IsComputed(), Epetra_MultiVector::NumVectors(), Epetra_MultiVector::Pointers(), and Epetra_Time::ResetStartTime().
ApplyInverseFlops()
virtual double Ifpack_ICT::ApplyInverseFlops () const inline virtual
Returns the number of flops in all applications of ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 296 of file Ifpack_ICT.h.
Referenced by Print().
ApplyInverseTime()
virtual double Ifpack_ICT::ApplyInverseTime () const inline virtual
Returns the time spent in ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 278 of file Ifpack_ICT.h.
Referenced by Print().
Comm()
const Epetra_Comm & Ifpack_ICT::Comm () const inline virtual
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Implements Epetra_Operator.
Definition at line 230 of file Ifpack_ICT.h.
Referenced by Initialize(), and Print().
Compute()
int Ifpack_ICT::Compute () virtual
Compute IC factor U using the specified graph, diagonal perturbation thresholds and relaxation parameters.
This function computes the RILU(k) factors L and U using the current:
Ifpack_IlukGraph specifying the structure of L and U.
Value for the RILU(k) relaxation parameter.
Value for the a priori diagonal threshold values.
InitValues() must be called before the factorization can proceed.
Implements Ifpack_Preconditioner.
Definition at line 438 of file Ifpack_ICT.cpp.
References Epetra_BlockMap::GlobalIndicesInt(), Epetra_BlockMap::GlobalIndicesLongLong(), and Epetra_RowMatrix::RowMatrixRowMap().
ComputeFlops()
virtual double Ifpack_ICT::ComputeFlops () const inline virtual
Returns the number of flops in all applications of Compute().
Implements Ifpack_Preconditioner.
Definition at line 290 of file Ifpack_ICT.h.
Referenced by Print().
ComputeTime()
virtual double Ifpack_ICT::ComputeTime () const inline virtual
Returns the time spent in Compute().
Implements Ifpack_Preconditioner.
Definition at line 272 of file Ifpack_ICT.h.
Referenced by Print().
Condest() [1/2]
double Ifpack_ICT::Condest () const inline virtual
Returns the computed condition number estimate, or -1.0 if not computed.
Implements Ifpack_Preconditioner.
Definition at line 181 of file Ifpack_ICT.h.
Referenced by Print().
Condest() [2/2]
double Ifpack_ICT::Condest (const Ifpack_CondestType CT = Ifpack_Cheap, const int MaxIters = 1550, const double Tol = 1e-9, Epetra_RowMatrix * Matrix_in = 0) virtual
Returns the maximum over all the condition number estimate for each local ILU set of factors.
This functions computes a local condition number estimate on each processor and return the maximum over all processor of the estimate.
Parameters
In Trans -If true, solve transpose problem.
Out ConditionNumberEstimate - The maximum across all processors of the infinity-norm estimate of the condition number of the inverse of LDU.
Implements Ifpack_Preconditioner.
Definition at line 502 of file Ifpack_ICT.cpp.
References IsComputed().
DropTolerance()
double Ifpack_ICT::DropTolerance () const inline
Returns the drop threshold.
Definition at line 329 of file Ifpack_ICT.h.
Referenced by SetParameters().
H()
const Epetra_CrsMatrix & Ifpack_ICT::H () const inline
Returns the address of the D factor associated with this factored matrix.
Definition at line 198 of file Ifpack_ICT.h.
Referenced by NumGlobalNonzeros(), and NumMyNonzeros().
HasNormInf()
bool Ifpack_ICT::HasNormInf () const inline virtual
Returns false because this class cannot compute an Inf-norm.
Implements Epetra_Operator.
Definition at line 218 of file Ifpack_ICT.h.
Initialize()
int Ifpack_ICT::Initialize () virtual
Initialize L and U with values from user matrix A.
Copies values from the user's matrix into the nonzero pattern of L and U.
Parameters
In A - User matrix to be factored.
Warning
The graph of A must be identical to the graph passed in to Ifpack_IlukGraph constructor.
Implements Ifpack_Preconditioner.
Definition at line 138 of file Ifpack_ICT.cpp.
References Comm(), Epetra_Time::ElapsedTime(), Matrix(), Epetra_RowMatrix::NumMyRows(), and Epetra_Time::ResetStartTime().
InitializeFlops()
virtual double Ifpack_ICT::InitializeFlops () const inline virtual
Returns the number of flops in the initialization phase.
Implements Ifpack_Preconditioner.
Definition at line 284 of file Ifpack_ICT.h.
InitializeTime()
virtual double Ifpack_ICT::InitializeTime () const inline virtual
Returns the time spent in Initialize().
Implements Ifpack_Preconditioner.
Definition at line 266 of file Ifpack_ICT.h.
Referenced by Print().
IsComputed()
bool Ifpack_ICT::IsComputed () const inline virtual
If factor is completed, this query returns true, otherwise it returns false.
Implements Ifpack_Preconditioner.
Definition at line 148 of file Ifpack_ICT.h.
Referenced by ApplyInverse(), and Condest().
IsInitialized()
bool Ifpack_ICT::IsInitialized () const inline virtual
Returns true is the preconditioner has been successfully initialized.
Implements Ifpack_Preconditioner.
Definition at line 122 of file Ifpack_ICT.h.
Label()
const char * Ifpack_ICT::Label () const inline virtual
Implements Epetra_Operator.
Definition at line 233 of file Ifpack_ICT.h.
LevelOfFill()
double Ifpack_ICT::LevelOfFill () const inline
Returns the level-of-fill.
Note
: if 1.0, then the factored matrix contains approximatively the same number of elements of A.
Definition at line 305 of file Ifpack_ICT.h.
Referenced by Print(), and SetParameters().
Matrix()
const Epetra_RowMatrix & Ifpack_ICT::Matrix () const inline virtual
Returns a reference to the matrix to be preconditioned.
Implements Ifpack_Preconditioner.
Definition at line 116 of file Ifpack_ICT.h.
Referenced by Initialize(), and Print().
NormInf()
double Ifpack_ICT::NormInf () const inline virtual
Returns 0.0 because this class cannot compute Inf-norm.
Implements Epetra_Operator.
Definition at line 215 of file Ifpack_ICT.h.
NumApplyInverse()
virtual int Ifpack_ICT::NumApplyInverse () const inline virtual
Returns the number of calls to ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 260 of file Ifpack_ICT.h.
Referenced by Print().
NumCompute()
virtual int Ifpack_ICT::NumCompute () const inline virtual
Returns the number of calls to Compute().
Implements Ifpack_Preconditioner.
Definition at line 254 of file Ifpack_ICT.h.
Referenced by Print().
NumGlobalNonzeros()
int Ifpack_ICT::NumGlobalNonzeros () const inline
Returns the number of nonzero entries in the global graph.
Definition at line 190 of file Ifpack_ICT.h.
References H(), and NumGlobalNonzeros().
Referenced by NumGlobalNonzeros().
NumGlobalNonzeros64()
long long Ifpack_ICT::NumGlobalNonzeros64 () const inline
Definition at line 192 of file Ifpack_ICT.h.
NumInitialize()
virtual int Ifpack_ICT::NumInitialize () const inline virtual
Returns the number of calls to Initialize().
Implements Ifpack_Preconditioner.
Definition at line 248 of file Ifpack_ICT.h.
Referenced by Print().
NumMyNonzeros()
int Ifpack_ICT::NumMyNonzeros () const inline
Returns the number of nonzero entries in the local graph.
Definition at line 195 of file Ifpack_ICT.h.
References H(), and NumMyNonzeros().
Referenced by NumMyNonzeros().
OperatorDomainMap()
const Epetra_Map & Ifpack_ICT::OperatorDomainMap () const inline virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
Definition at line 224 of file Ifpack_ICT.h.
References Epetra_Operator::OperatorDomainMap().
OperatorRangeMap()
const Epetra_Map & Ifpack_ICT::OperatorRangeMap () const inline virtual
Returns the Epetra_Map object associated with the range of this operator.
Implements Epetra_Operator.
Definition at line 227 of file Ifpack_ICT.h.
References Epetra_Operator::OperatorRangeMap().
Print()
std::ostream & Ifpack_ICT::Print (std::ostream & os) const virtual
Prints basic information on iostream. This function is used by operator<<.
Implements Ifpack_Preconditioner.
Definition at line 518 of file Ifpack_ICT.cpp.
References AbsoluteThreshold(), ApplyInverseFlops(), ApplyInverseTime(), Comm(), ComputeFlops(), ComputeTime(), Condest(), InitializeTime(), LevelOfFill(), Matrix(), NumApplyInverse(), NumCompute(), NumInitialize(), RelativeThreshold(), and RelaxValue().
RelativeThreshold()
double Ifpack_ICT::RelativeThreshold () const inline
Returns the relative threshold.
Definition at line 317 of file Ifpack_ICT.h.
Referenced by Print(), and SetParameters().
RelaxValue()
double Ifpack_ICT::RelaxValue () const inline
Returns the relaxation value.
Definition at line 323 of file Ifpack_ICT.h.
Referenced by Print(), and SetParameters().
SetLabel()
int Ifpack_ICT::SetLabel (const char * Label_in) inline
Definition at line 238 of file Ifpack_ICT.h.
SetParameters()
int Ifpack_ICT::SetParameters (Teuchos::ParameterList & parameterlis) virtual
Set parameters using a Teuchos::ParameterList object.
Implements Ifpack_Preconditioner.
Definition at line 104 of file Ifpack_ICT.cpp.
References AbsoluteThreshold(), DropTolerance(), LevelOfFill(), RelativeThreshold(), and RelaxValue().
SetUseTranspose()
int Ifpack_ICT::SetUseTranspose (bool UseTranspose_in) inline virtual
If set true, transpose of this operator will be applied.
This flag allows the transpose of the given operator to be used implicitly. Setting this flag affects only the Apply() and ApplyInverse() methods. If the implementation of this interface does not support transpose use, this method should return a value of -1.
Parameters
In UseTranspose_in -If true, multiply by the transpose of operator, otherwise just use operator.
Returns
Always returns 0.
Implements Epetra_Operator.
Definition at line 212 of file Ifpack_ICT.h.
UseTranspose()
bool Ifpack_ICT::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Definition at line 221 of file Ifpack_ICT.h.
The documentation for this class was generated from the following files:
Ifpack_ICT.h
Ifpack_ICT.cpp