IFPACK: Ifpack_RCMReordering Class Reference
Ifpack_RCMReordering Class Reference
Ifpack_RCMReordering: reverse Cuthill-McKee reordering.
#include <Ifpack_RCMReordering.h>
Public Member Functions
Ifpack_RCMReordering ()
Constructor for Ifpack_Graph's.
Ifpack_RCMReordering (const Ifpack_RCMReordering &RHS)
Copy Constructor.
Ifpack_RCMReordering & operator= (const Ifpack_RCMReordering &RHS)
Assignment operator.
virtual ~Ifpack_RCMReordering ()
Destructor.
virtual int SetParameter (const std::string Name, const int Value)
Sets integer parameters ‘Name’.
virtual int SetParameter (const std::string Name, const double Value)
Sets double parameters ‘Name’.
virtual int SetParameters (Teuchos::ParameterList &List)
Sets all parameters.
virtual int Compute (const Ifpack_Graph &Graph)
Computes all it is necessary to initialize the reordering object.
virtual int Compute (const Epetra_RowMatrix &Matrix)
Computes all it is necessary to initialize the reordering object.
virtual bool IsComputed () const
Returns true is the reordering object has been successfully initialized, false otherwise.
virtual int Reorder (const int i) const
Returns the reordered index of row i.
virtual int InvReorder (const int i) const
Returns the inverse reordered index of row i.
virtual int P (const Epetra_MultiVector &Xorig, Epetra_MultiVector &Xreord) const
Applies reordering to multivector X, whose local length equals the number of local rows.
virtual int Pinv (const Epetra_MultiVector &Xorig, Epetra_MultiVector &Xinvreord) const
Applies inverse reordering to multivector X, whose local length equals the number of local rows.
virtual std::ostream & Print (std::ostream &os) const
Prints basic information on iostream. This function is used by operator<<.
virtual int NumMyRows () const
Returns the number of local rows.
virtual int RootNode () const
Returns the root node.
Public Member Functions inherited from Ifpack_Reordering
virtual ~Ifpack_Reordering ()
Destructor.
Detailed Description
Ifpack_RCMReordering: reverse Cuthill-McKee reordering.
Definition at line 64 of file Ifpack_RCMReordering.h.
Constructor & Destructor Documentation
Ifpack_RCMReordering() [1/2]
Ifpack_RCMReordering::Ifpack_RCMReordering ()
Constructor for Ifpack_Graph's.
Definition at line 53 of file Ifpack_RCMReordering.cpp.
Ifpack_RCMReordering() [2/2]
Ifpack_RCMReordering::Ifpack_RCMReordering (const Ifpack_RCMReordering & RHS)
Copy Constructor.
Definition at line 62 of file Ifpack_RCMReordering.cpp.
References NumMyRows().
~Ifpack_RCMReordering()
virtual Ifpack_RCMReordering::~Ifpack_RCMReordering () inline virtual
Destructor.
Definition at line 78 of file Ifpack_RCMReordering.h.
Member Function Documentation
Compute() [1/2]
int Ifpack_RCMReordering::Compute (const Epetra_RowMatrix & Matrix) virtual
Computes all it is necessary to initialize the reordering object.
Implements Ifpack_Reordering.
Definition at line 124 of file Ifpack_RCMReordering.cpp.
References Compute().
Compute() [2/2]
int Ifpack_RCMReordering::Compute (const Ifpack_Graph & Graph) virtual
Computes all it is necessary to initialize the reordering object.
Implements Ifpack_Reordering.
Definition at line 134 of file Ifpack_RCMReordering.cpp.
Referenced by Compute().
InvReorder()
int Ifpack_RCMReordering::InvReorder (const int i) const virtual
Returns the inverse reordered index of row i.
Implements Ifpack_Reordering.
Definition at line 250 of file Ifpack_RCMReordering.cpp.
References IsComputed().
IsComputed()
virtual bool Ifpack_RCMReordering::IsComputed () const inline virtual
Returns true is the reordering object has been successfully initialized, false otherwise.
Implements Ifpack_Reordering.
Definition at line 96 of file Ifpack_RCMReordering.h.
Referenced by InvReorder(), operator=(), Print(), and Reorder().
NumMyRows()
virtual int Ifpack_RCMReordering::NumMyRows () const inline virtual
Returns the number of local rows.
Definition at line 120 of file Ifpack_RCMReordering.h.
Referenced by Ifpack_RCMReordering(), and operator=().
operator=()
Ifpack_RCMReordering & Ifpack_RCMReordering::operator= (const Ifpack_RCMReordering & RHS)
Assignment operator.
Definition at line 77 of file Ifpack_RCMReordering.cpp.
References IsComputed(), and NumMyRows().
P()
int Ifpack_RCMReordering::P (const Epetra_MultiVector & Xorig, Epetra_MultiVector & Xreord) const virtual
Applies reordering to multivector X, whose local length equals the number of local rows.
Implements Ifpack_Reordering.
Definition at line 262 of file Ifpack_RCMReordering.cpp.
References Epetra_MultiVector::NumVectors().
Pinv()
int Ifpack_RCMReordering::Pinv (const Epetra_MultiVector & Xorig, Epetra_MultiVector & Xinvreord) const virtual
Applies inverse reordering to multivector X, whose local length equals the number of local rows.
Implements Ifpack_Reordering.
Definition at line 278 of file Ifpack_RCMReordering.cpp.
References Epetra_MultiVector::NumVectors().
Print()
std::ostream & Ifpack_RCMReordering::Print (std::ostream & os) const virtual
Prints basic information on iostream. This function is used by operator<<.
Implements Ifpack_Reordering.
Definition at line 294 of file Ifpack_RCMReordering.cpp.
References IsComputed().
Reorder()
int Ifpack_RCMReordering::Reorder (const int i) const virtual
Returns the reordered index of row i.
Implements Ifpack_Reordering.
Definition at line 237 of file Ifpack_RCMReordering.cpp.
References IsComputed().
RootNode()
virtual int Ifpack_RCMReordering::RootNode () const inline virtual
Returns the root node.
Definition at line 126 of file Ifpack_RCMReordering.h.
SetParameter() [1/2]
int Ifpack_RCMReordering::SetParameter (const std::string Name, const double Value) virtual
Sets double parameters ‘Name’.
Implements Ifpack_Reordering.
Definition at line 109 of file Ifpack_RCMReordering.cpp.
SetParameter() [2/2]
int Ifpack_RCMReordering::SetParameter (const std::string Name, const int Value) virtual
Sets integer parameters ‘Name’.
Implements Ifpack_Reordering.
Definition at line 100 of file Ifpack_RCMReordering.cpp.
SetParameters()
int Ifpack_RCMReordering::SetParameters (Teuchos::ParameterList & List) virtual
Sets all parameters.
Implements Ifpack_Reordering.
Definition at line 116 of file Ifpack_RCMReordering.cpp.
The documentation for this class was generated from the following files:
Ifpack_RCMReordering.h
Ifpack_RCMReordering.cpp