IFPACK: Ifpack_DenseContainer Class Reference
Ifpack_DenseContainer Class Reference
Ifpack_DenseContainer: a class to define containers for dense matrices.
#include <Ifpack_DenseContainer.h>
Public Member Functions
Ifpack_DenseContainer (const int NumRows_in, const int NumVectors_in=1)
Default constructor.
Ifpack_DenseContainer (const Ifpack_DenseContainer &rhs)
Copy constructor.
virtual ~Ifpack_DenseContainer ()
Destructor.
Ifpack_DenseContainer & operator= (const Ifpack_DenseContainer &rhs)
Operator=.
virtual int NumRows () const
Returns the number of rows of the matrix and LHS/RHS.
virtual int NumVectors () const
Returns the number of vectors in LHS/RHS.
virtual int SetNumVectors (const int NumVectors_in)
Sets the number of vectors for LHS/RHS.
virtual double & LHS (const int i, const int Vector=0)
Returns the i-th component of the vector Vector of LHS.
virtual double & RHS (const int i, const int Vector=0)
Returns the i-th component of the vector Vector of RHS.
virtual int & ID (const int i)
Returns the ID associated to local row i.
virtual int SetMatrixElement (const int row, const int col, const double value)
Set the matrix element (row,col) to value.
virtual int SetParameters (Teuchos::ParameterList &)
Sets all necessary parameters.
virtual bool IsInitialized () const
Returns true is the container has been successfully initialized.
virtual bool IsComputed () const
Returns true is the container has been successfully computed.
virtual const char * Label () const
Returns the label of this container.
virtual int SetKeepNonFactoredMatrix (const bool flag)
If flag is true, keeps a copy of the non-factored matrix.
virtual bool KeepNonFactoredMatrix () const
Returns KeepNonFactoredMatrix_.
virtual const Epetra_SerialDenseMatrix & LHS () const
Returns the dense vector containing the LHS.
virtual const Epetra_SerialDenseMatrix & RHS () const
Returns the dense vector containing the RHS.
virtual const Epetra_SerialDenseMatrix & Matrix () const
Returns the dense matrix or its factors.
virtual const Epetra_SerialDenseMatrix & NonFactoredMatrix () const
Returns the non-factored dense matrix (only if stored).
virtual const Epetra_IntSerialDenseVector & ID () const
Returns the integer dense vector of IDs.
virtual int Initialize ()
Initialize the container.
virtual int Compute (const Epetra_RowMatrix &Matrix_in)
Finalizes the linear system matrix and prepares for the application of the inverse.
virtual int Apply ()
Apply the matrix to RHS, results are stored in LHS.
virtual int ApplyInverse ()
Apply the inverse of the matrix to RHS, results are stored in LHS.
virtual double InitializeFlops () const
Returns the flops in Initialize().
virtual double ComputeFlops () const
Returns the flops in Compute().
virtual double ApplyFlops () const
Returns the flops in Apply().
virtual double ApplyInverseFlops () const
Returns the flops in ApplyInverse().
virtual std::ostream & Print (std::ostream &os) const
Prints basic information on iostream. This function is used by operator<<.
Public Member Functions inherited from Ifpack_Container
virtual ~Ifpack_Container ()
Destructor.
Detailed Description
Ifpack_DenseContainer: a class to define containers for dense matrices.
To understand what an IFPACK container is, please refer to the documentation of the pure virtual class Ifpack_Container. Currently, containers are used by class Ifpack_BlockRelaxation.
Using block methods, one needs to store all diagonal blocks and to be also to apply the inverse of each diagonal block. Using class Ifpack_DenseContainer, one can store the blocks as dense matrices, which can be advantageous when the blocks are small. Otherwise, class Ifpack_SparseContainer is probably more appropriate.
A typical use of a container is as follows:
#include "Ifpack_DenseContainer.h"
...
// local matrix of (5,5), with two vectors for solution and rhs.
Ifpack_Container* Container = new
  Ifpack_DenseContainer(5,5);
// assign local rows 1, 5, 12, 13, 16 to this container
Container(0) = 1;
Container(1) = 5;
Container(2) = 12;
Container(3) = 13;
Container(4) = 16;
// Now extract the submatrix corresponding to rows and columns:
// 1. initialize the container.
Container.Initialize();
// 2. extract matrix values from an Epetra_RowMatrix A,
// and compute LU factors of the submatrix identified by rows
// and columns 1, 5, 12, 13 and 16 using LAPACK
Container.Compute(A);
// We can set the RHS as follows:
Container.RHS(0) = 1.0;
Container.RHS(1) = 2.0;
Container.RHS(2) = 3.0;
Container.RHS(3) = 4.0;
Container.RHS(4) = 5.0;
// The linear system with the submatrix is solved as follows:
Container.ApplyInverse().
A call to Compute() computes the LU factorization of the linear system matrix, using LAPACK (more precisely, by calling the corresponding routines in Epetra_SerialDenseSolver). The default behavior is to store the matrix factors by overwriting the linear system matrix itself. This way, method Apply() fails, as the original matrix does no longer exists. An alternative is to call KeepNonFactoredMatrix(true), which forces Ifpack_DenseContainer to maintain in memory a copy of the non-factored matrix.
Author
Marzio Sala, SNL 9214.
Date
Last update Nov-04.
Definition at line 123 of file Ifpack_DenseContainer.h.
Constructor & Destructor Documentation
Ifpack_DenseContainer() [1/2]
Ifpack_DenseContainer::Ifpack_DenseContainer (const int NumRows_in, const int NumVectors_in = 1) inline
Default constructor.
Definition at line 130 of file Ifpack_DenseContainer.h.
Ifpack_DenseContainer() [2/2]
Ifpack_DenseContainer::Ifpack_DenseContainer (const Ifpack_DenseContainer & rhs) inline
Copy constructor.
Definition at line 142 of file Ifpack_DenseContainer.h.
References ID(), LHS(), Matrix(), NonFactoredMatrix(), and RHS().
~Ifpack_DenseContainer()
virtual Ifpack_DenseContainer::~Ifpack_DenseContainer () inline virtual
Destructor.
Definition at line 158 of file Ifpack_DenseContainer.h.
Member Function Documentation
Apply()
int Ifpack_DenseContainer::Apply () virtual
Apply the matrix to RHS, results are stored in LHS.
Implements Ifpack_Container.
Definition at line 236 of file Ifpack_DenseContainer.cpp.
References IsComputed(), and Epetra_SerialDenseMatrix::Multiply().
ApplyFlops()
virtual double Ifpack_DenseContainer::ApplyFlops () const inline virtual
Returns the flops in Apply().
Implements Ifpack_Container.
Definition at line 335 of file Ifpack_DenseContainer.h.
ApplyInverse()
int Ifpack_DenseContainer::ApplyInverse () virtual
Apply the inverse of the matrix to RHS, results are stored in LHS.
Implements Ifpack_Container.
Definition at line 124 of file Ifpack_DenseContainer.cpp.
References IsComputed(), and Epetra_SerialDenseSolver::Solve().
ApplyInverseFlops()
virtual double Ifpack_DenseContainer::ApplyInverseFlops () const inline virtual
Returns the flops in ApplyInverse().
Implements Ifpack_Container.
Definition at line 340 of file Ifpack_DenseContainer.h.
Referenced by Print().
Compute()
int Ifpack_DenseContainer::Compute (const Epetra_RowMatrix & Matrix_in) virtual
Finalizes the linear system matrix and prepares for the application of the inverse.
Implements Ifpack_Container.
Definition at line 204 of file Ifpack_DenseContainer.cpp.
References Epetra_SerialDenseSolver::Factor(), Initialize(), and IsInitialized().
ComputeFlops()
virtual double Ifpack_DenseContainer::ComputeFlops () const inline virtual
Returns the flops in Compute().
Implements Ifpack_Container.
Definition at line 330 of file Ifpack_DenseContainer.h.
Referenced by Print().
ID() [1/2]
virtual const Epetra_IntSerialDenseVector & Ifpack_DenseContainer::ID () const inline virtual
Returns the integer dense vector of IDs.
Definition at line 303 of file Ifpack_DenseContainer.h.
ID() [2/2]
int & Ifpack_DenseContainer::ID (const int i) virtual
Returns the ID associated to local row i.
The set of (local) rows assigned to this container is defined by calling ID(i) = j, where i (from 0 to NumRows()) indicates the container-row, and j indicates the local row in the calling process.
This is usually used to recorder the local row ID (on calling process) of the i-th row in the container.
Implements Ifpack_Container.
Definition at line 141 of file Ifpack_DenseContainer.cpp.
Referenced by Ifpack_DenseContainer(), and operator=().
Initialize()
int Ifpack_DenseContainer::Initialize () virtual
Initialize the container.
Implements Ifpack_Container.
Definition at line 54 of file Ifpack_DenseContainer.cpp.
References Epetra_IntSerialDenseMatrix::Reshape(), Epetra_SerialDenseMatrix::Reshape(), Epetra_SerialDenseSolver::SetMatrix(), and Epetra_SerialDenseSolver::SetVectors().
Referenced by Compute(), and SetMatrixElement().
InitializeFlops()
virtual double Ifpack_DenseContainer::InitializeFlops () const inline virtual
Returns the flops in Initialize().
Implements Ifpack_Container.
Definition at line 325 of file Ifpack_DenseContainer.h.
IsComputed()
virtual bool Ifpack_DenseContainer::IsComputed () const inline virtual
Returns true is the container has been successfully computed.
Implements Ifpack_Container.
Definition at line 254 of file Ifpack_DenseContainer.h.
Referenced by Apply(), ApplyInverse(), operator=(), and Print().
IsInitialized()
virtual bool Ifpack_DenseContainer::IsInitialized () const inline virtual
Returns true is the container has been successfully initialized.
Implements Ifpack_Container.
Definition at line 248 of file Ifpack_DenseContainer.h.
Referenced by Compute(), Print(), and SetMatrixElement().
KeepNonFactoredMatrix()
virtual bool Ifpack_DenseContainer::KeepNonFactoredMatrix () const inline virtual
Returns KeepNonFactoredMatrix_.
Definition at line 273 of file Ifpack_DenseContainer.h.
Referenced by operator=().
Label()
virtual const char * Ifpack_DenseContainer::Label () const inline virtual
Returns the label of this container.
Implements Ifpack_Container.
Definition at line 260 of file Ifpack_DenseContainer.h.
LHS() [1/2]
virtual const Epetra_SerialDenseMatrix & Ifpack_DenseContainer::LHS () const inline virtual
Returns the dense vector containing the LHS.
Definition at line 279 of file Ifpack_DenseContainer.h.
LHS() [2/2]
double & Ifpack_DenseContainer::LHS (const int i, const int Vector = 0) virtual
Returns the i-th component of the vector Vector of LHS.
Implements Ifpack_Container.
Definition at line 91 of file Ifpack_DenseContainer.cpp.
References Epetra_SerialDenseMatrix::A().
Referenced by Ifpack_DenseContainer(), and operator=().
Matrix()
virtual const Epetra_SerialDenseMatrix & Ifpack_DenseContainer::Matrix () const inline virtual
Returns the dense matrix or its factors.
Definition at line 291 of file Ifpack_DenseContainer.h.
Referenced by Ifpack_DenseContainer(), and operator=().
NonFactoredMatrix()
virtual const Epetra_SerialDenseMatrix & Ifpack_DenseContainer::NonFactoredMatrix () const inline virtual
Returns the non-factored dense matrix (only if stored).
Definition at line 297 of file Ifpack_DenseContainer.h.
Referenced by Ifpack_DenseContainer(), and operator=().
NumRows()
int Ifpack_DenseContainer::NumRows () const virtual
Returns the number of rows of the matrix and LHS/RHS.
Implements Ifpack_Container.
Definition at line 48 of file Ifpack_DenseContainer.cpp.
Referenced by operator=(), Print(), and SetMatrixElement().
NumVectors()
virtual int Ifpack_DenseContainer::NumVectors () const inline virtual
Returns the number of vectors in LHS/RHS.
Implements Ifpack_Container.
Definition at line 192 of file Ifpack_DenseContainer.h.
Referenced by operator=(), and Print().
operator=()
Ifpack_DenseContainer & Ifpack_DenseContainer::operator= (const Ifpack_DenseContainer & rhs) inline
Operator=.
Definition at line 165 of file Ifpack_DenseContainer.h.
References ID(), IsComputed(), KeepNonFactoredMatrix(), LHS(), Matrix(), NonFactoredMatrix(), NumRows(), NumVectors(), and RHS().
Print()
std::ostream & Ifpack_DenseContainer::Print (std::ostream & os) const virtual
Prints basic information on iostream. This function is used by operator<<.
Implements Ifpack_Container.
Definition at line 254 of file Ifpack_DenseContainer.cpp.
References ApplyInverseFlops(), ComputeFlops(), IsComputed(), IsInitialized(), NumRows(), and NumVectors().
RHS() [1/2]
virtual const Epetra_SerialDenseMatrix & Ifpack_DenseContainer::RHS () const inline virtual
Returns the dense vector containing the RHS.
Definition at line 285 of file Ifpack_DenseContainer.h.
RHS() [2/2]
double & Ifpack_DenseContainer::RHS (const int i, const int Vector = 0) virtual
Returns the i-th component of the vector Vector of RHS.
Implements Ifpack_Container.
Definition at line 97 of file Ifpack_DenseContainer.cpp.
References Epetra_SerialDenseMatrix::A().
Referenced by Ifpack_DenseContainer(), and operator=().
SetKeepNonFactoredMatrix()
virtual int Ifpack_DenseContainer::SetKeepNonFactoredMatrix (const bool flag) inline virtual
If flag is true, keeps a copy of the non-factored matrix.
Definition at line 266 of file Ifpack_DenseContainer.h.
SetMatrixElement()
int Ifpack_DenseContainer::SetMatrixElement (const int row, const int col, const double value) virtual
Set the matrix element (row,col) to value.
Implements Ifpack_Container.
Definition at line 103 of file Ifpack_DenseContainer.cpp.
References Initialize(), IsInitialized(), and NumRows().
SetNumVectors()
virtual int Ifpack_DenseContainer::SetNumVectors (const int NumVectors_in) inline virtual
Sets the number of vectors for LHS/RHS.
Implements Ifpack_Container.
Definition at line 198 of file Ifpack_DenseContainer.h.
References Epetra_SerialDenseMatrix::Reshape(), and Epetra_SerialDenseSolver::SetVectors().
SetParameters()
virtual int Ifpack_DenseContainer::SetParameters (Teuchos::ParameterList &) inline virtual
Sets all necessary parameters.
Implements Ifpack_Container.
Definition at line 242 of file Ifpack_DenseContainer.h.
The documentation for this class was generated from the following files:
Ifpack_DenseContainer.h
Ifpack_DenseContainer.cpp