IFPACK: Ifpack_Amesos Class Reference
Ifpack_Amesos Class Reference
Ifpack_Amesos: a class to use Amesos' factorizations as preconditioners.
#include <Ifpack_Amesos.h>
Public Member Functions
Ifpack_Amesos (Epetra_RowMatrix *Matrix)
Constructor.
Ifpack_Amesos (const Ifpack_Amesos &rhs)
Copy constructor.
Ifpack_Amesos & operator= (const Ifpack_Amesos &rhs)
Operator=.
virtual ~Ifpack_Amesos ()
Destructor.
virtual int SetUseTranspose (bool UseTranspose_in)
If set true, transpose of this operator will be applied (not implemented).
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Applies the matrix to an Epetra_MultiVector.
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Applies the preconditioner to X, returns the result in Y.
virtual double NormInf () const
Returns the infinity norm of the global matrix (not implemented)
virtual const char * Label () const
Returns a character string describing the operator.
virtual bool UseTranspose () const
Returns the current UseTranspose setting.
virtual bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
virtual const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
virtual const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
virtual const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
virtual bool IsInitialized () const
Returns true is the preconditioner has been successfully initialized.
virtual int Initialize ()
Initializes the preconditioners.
virtual bool IsComputed () const
Returns true if the preconditioner has been successfully computed.
virtual int Compute ()
Computes the preconditioners.
virtual int SetParameters (Teuchos::ParameterList &List)
Sets all the parameters for the preconditioner.
virtual const Epetra_RowMatrix & Matrix () const
Returns a const reference to the internally stored matrix.
virtual double Condest (const Ifpack_CondestType CT=Ifpack_Cheap, const int MaxIters=1550, const double Tol=1e-9, Epetra_RowMatrix *Matrix_in=0)
Returns the estimated condition number, computes it if necessary.
virtual double Condest () const
Returns the estimated condition number, never computes it.
virtual int NumInitialize () const
Returns the number of calls to Initialize().
virtual int NumCompute () const
Returns the number of calls to Compute().
virtual int NumApplyInverse () const
Returns the number of calls to ApplyInverse().
virtual double InitializeTime () const
Returns the total time spent in Initialize().
virtual double ComputeTime () const
Returns the total time spent in Compute().
virtual double ApplyInverseTime () const
Returns the total time spent in ApplyInverse().
virtual double InitializeFlops () const
Returns the number of flops in the initialization phase.
virtual double ComputeFlops () const
Returns the total number of flops to computate the preconditioner.
virtual double ApplyInverseFlops () const
Returns the total number of flops to apply the preconditioner.
virtual const Teuchos::ParameterList & List () const
virtual std::ostream & Print (std::ostream &os) const
Prints on ostream basic information about this object.
Protected Member Functions
void SetLabel (const char *Label_in)
Sets the label.
void SetIsInitialized (const bool IsInitialized_in)
Sets IsInitialized_.
void SetIsComputed (const int IsComputed_in)
Sets IsComputed_.
void SetNumInitialize (const int NumInitialize_in)
Sets NumInitialize_.
void SetNumCompute (const int NumCompute_in)
Sets NumCompute_.
void SetNumApplyInverse (const int NumApplyInverse_in)
Sets NumApplyInverse_.
void SetInitializeTime (const double InitializeTime_in)
Sets InitializeTime_.
void SetComputeTime (const double ComputeTime_in)
Sets ComputeTime_.
void SetApplyInverseTime (const double ApplyInverseTime_in)
Sets ApplyInverseTime_.
void SetComputeFlops (const double ComputeFlops_in)
Sets ComputeFlops_.
void SetApplyInverseFlops (const double ApplyInverseFlops_in)
Sets ComputeFlops_.
void SetList (const Teuchos::ParameterList &List_in)
Set List_.
Detailed Description
Ifpack_Amesos: a class to use Amesos' factorizations as preconditioners.
Class Ifpack_Amesos enables the use of Amesos' factorizations as Ifpack_Preconditioners.
Ifpack_Amesos is just a bare-bone wrap to Amesos. Currently, the only parameter required recognized by SetParameters() is "amesos: solver type" (defaulted to "Amesos_Klu"), which defined the Amesos solver. The Teuchos list in input to SetParameters() is copied, then the copied list is used to set the parameters of the Amesos object.
This class works with matrices whose communicator contains only one process, that is, either serial matrices, or Ifpack_LocalFilter'd matrices.
Warning
The number of flops is NOT updated.
Author
Marzio Sala, SNL 9214.
Date
Last update Oct-04.
Definition at line 87 of file Ifpack_Amesos.h.
Constructor & Destructor Documentation
Ifpack_Amesos() [1/2]
Ifpack_Amesos::Ifpack_Amesos (Epetra_RowMatrix * Matrix)
Constructor.
Definition at line 59 of file Ifpack_Amesos.cpp.
Ifpack_Amesos() [2/2]
Ifpack_Amesos::Ifpack_Amesos (const Ifpack_Amesos & rhs)
Copy constructor.
Definition at line 80 of file Ifpack_Amesos.cpp.
References Compute(), Initialize(), IsComputed(), and IsInitialized().
~Ifpack_Amesos()
virtual Ifpack_Amesos::~Ifpack_Amesos () inline virtual
Destructor.
Definition at line 104 of file Ifpack_Amesos.h.
Member Function Documentation
Apply()
int Ifpack_Amesos::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Applies the matrix to an Epetra_MultiVector.
Parameters
X - (In) A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Y - (Out) A Epetra_MultiVector of dimension NumVectors containing the result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
Definition at line 251 of file Ifpack_Amesos.cpp.
ApplyInverse()
int Ifpack_Amesos::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Applies the preconditioner to X, returns the result in Y.
Parameters
X - (In) A Epetra_MultiVector of dimension NumVectors to be preconditioned.
Y - (Out) A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Warning
In order to work with AztecOO, any implementation of this method must support the case where X and Y are the same object.
Implements Ifpack_Preconditioner.
Definition at line 260 of file Ifpack_Amesos.cpp.
References IsComputed(), Epetra_MultiVector::NumVectors(), and Epetra_MultiVector::Pointers().
ApplyInverseFlops()
virtual double Ifpack_Amesos::ApplyInverseFlops () const inline virtual
Returns the total number of flops to apply the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 283 of file Ifpack_Amesos.h.
ApplyInverseTime()
virtual double Ifpack_Amesos::ApplyInverseTime () const inline virtual
Returns the total time spent in ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 265 of file Ifpack_Amesos.h.
Comm()
const Epetra_Comm & Ifpack_Amesos::Comm () const virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Epetra_Operator.
Definition at line 319 of file Ifpack_Amesos.cpp.
Referenced by Initialize(), and Print().
Compute()
int Ifpack_Amesos::Compute () virtual
Computes the preconditioners.
Returns
0 if successful, 1 if problems occurred.
Implements Ifpack_Preconditioner.
Definition at line 212 of file Ifpack_Amesos.cpp.
References Initialize(), and IsInitialized().
Referenced by Ifpack_Amesos().
ComputeFlops()
virtual double Ifpack_Amesos::ComputeFlops () const inline virtual
Returns the total number of flops to computate the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 277 of file Ifpack_Amesos.h.
ComputeTime()
virtual double Ifpack_Amesos::ComputeTime () const inline virtual
Returns the total time spent in Compute().
Implements Ifpack_Preconditioner.
Definition at line 259 of file Ifpack_Amesos.h.
Condest() [1/2]
virtual double Ifpack_Amesos::Condest () const inline virtual
Returns the estimated condition number, never computes it.
Implements Ifpack_Preconditioner.
Definition at line 229 of file Ifpack_Amesos.h.
Referenced by Print().
Condest() [2/2]
double Ifpack_Amesos::Condest (const Ifpack_CondestType CT = Ifpack_Cheap, const int MaxIters = 1550, const double Tol = 1e-9, Epetra_RowMatrix * Matrix_in = 0) virtual
Returns the estimated condition number, computes it if necessary.
Implements Ifpack_Preconditioner.
Definition at line 337 of file Ifpack_Amesos.cpp.
References IsComputed().
HasNormInf()
bool Ifpack_Amesos::HasNormInf () const virtual
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
Implements Epetra_Operator.
Definition at line 313 of file Ifpack_Amesos.cpp.
Initialize()
int Ifpack_Amesos::Initialize () virtual
Initializes the preconditioners.
Returns
0 if successful, 1 if problems occurred.
Implements Ifpack_Preconditioner.
Definition at line 126 of file Ifpack_Amesos.cpp.
References Comm().
Referenced by Compute(), and Ifpack_Amesos().
InitializeFlops()
virtual double Ifpack_Amesos::InitializeFlops () const inline virtual
Returns the number of flops in the initialization phase.
Implements Ifpack_Preconditioner.
Definition at line 271 of file Ifpack_Amesos.h.
InitializeTime()
virtual double Ifpack_Amesos::InitializeTime () const inline virtual
Returns the total time spent in Initialize().
Implements Ifpack_Preconditioner.
Definition at line 253 of file Ifpack_Amesos.h.
IsComputed()
virtual bool Ifpack_Amesos::IsComputed () const inline virtual
Returns true if the preconditioner has been successfully computed.
Implements Ifpack_Preconditioner.
Definition at line 191 of file Ifpack_Amesos.h.
Referenced by ApplyInverse(), Condest(), and Ifpack_Amesos().
IsInitialized()
virtual bool Ifpack_Amesos::IsInitialized () const inline virtual
Returns true is the preconditioner has been successfully initialized.
Implements Ifpack_Preconditioner.
Definition at line 179 of file Ifpack_Amesos.h.
Referenced by Compute(), and Ifpack_Amesos().
Label()
const char * Ifpack_Amesos::Label () const virtual
Returns a character string describing the operator.
Implements Epetra_Operator.
Definition at line 301 of file Ifpack_Amesos.cpp.
Referenced by Print().
List()
virtual const Teuchos::ParameterList & Ifpack_Amesos::List () const inline virtual
Definition at line 289 of file Ifpack_Amesos.h.
Matrix()
virtual const Epetra_RowMatrix & Ifpack_Amesos::Matrix () const inline virtual
Returns a const reference to the internally stored matrix.
Implements Ifpack_Preconditioner.
Definition at line 217 of file Ifpack_Amesos.h.
NormInf()
double Ifpack_Amesos::NormInf () const virtual
Returns the infinity norm of the global matrix (not implemented)
Implements Epetra_Operator.
Definition at line 295 of file Ifpack_Amesos.cpp.
NumApplyInverse()
virtual int Ifpack_Amesos::NumApplyInverse () const inline virtual
Returns the number of calls to ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 247 of file Ifpack_Amesos.h.
NumCompute()
virtual int Ifpack_Amesos::NumCompute () const inline virtual
Returns the number of calls to Compute().
Implements Ifpack_Preconditioner.
Definition at line 241 of file Ifpack_Amesos.h.
NumInitialize()
virtual int Ifpack_Amesos::NumInitialize () const inline virtual
Returns the number of calls to Initialize().
Implements Ifpack_Preconditioner.
Definition at line 235 of file Ifpack_Amesos.h.
OperatorDomainMap()
const Epetra_Map & Ifpack_Amesos::OperatorDomainMap () const virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
Definition at line 325 of file Ifpack_Amesos.cpp.
OperatorRangeMap()
const Epetra_Map & Ifpack_Amesos::OperatorRangeMap () const virtual
Returns the Epetra_Map object associated with the range of this operator.
Implements Epetra_Operator.
Definition at line 331 of file Ifpack_Amesos.cpp.
Print()
std::ostream & Ifpack_Amesos::Print (std::ostream & os) const virtual
Prints on ostream basic information about this object.
Implements Ifpack_Preconditioner.
Definition at line 352 of file Ifpack_Amesos.cpp.
References Comm(), Condest(), and Label().
SetApplyInverseFlops()
void Ifpack_Amesos::SetApplyInverseFlops (const double ApplyInverseFlops_in) inline protected
Sets ComputeFlops_.
Definition at line 364 of file Ifpack_Amesos.h.
SetApplyInverseTime()
void Ifpack_Amesos::SetApplyInverseTime (const double ApplyInverseTime_in) inline protected
Sets ApplyInverseTime_.
Definition at line 352 of file Ifpack_Amesos.h.
SetComputeFlops()
void Ifpack_Amesos::SetComputeFlops (const double ComputeFlops_in) inline protected
Sets ComputeFlops_.
Definition at line 358 of file Ifpack_Amesos.h.
SetComputeTime()
void Ifpack_Amesos::SetComputeTime (const double ComputeTime_in) inline protected
Sets ComputeTime_.
Definition at line 346 of file Ifpack_Amesos.h.
SetInitializeTime()
void Ifpack_Amesos::SetInitializeTime (const double InitializeTime_in) inline protected
Sets InitializeTime_.
Definition at line 340 of file Ifpack_Amesos.h.
SetIsComputed()
void Ifpack_Amesos::SetIsComputed (const int IsComputed_in) inline protected
Sets IsComputed_.
Definition at line 316 of file Ifpack_Amesos.h.
SetIsInitialized()
void Ifpack_Amesos::SetIsInitialized (const bool IsInitialized_in) inline protected
Sets IsInitialized_.
Definition at line 310 of file Ifpack_Amesos.h.
SetLabel()
void Ifpack_Amesos::SetLabel (const char * Label_in) inline protected
Sets the label.
Definition at line 304 of file Ifpack_Amesos.h.
SetList()
void Ifpack_Amesos::SetList (const Teuchos::ParameterList & List_in) inline protected
Set List_.
Definition at line 370 of file Ifpack_Amesos.h.
SetNumApplyInverse()
void Ifpack_Amesos::SetNumApplyInverse (const int NumApplyInverse_in) inline protected
Sets NumApplyInverse_.
Definition at line 334 of file Ifpack_Amesos.h.
SetNumCompute()
void Ifpack_Amesos::SetNumCompute (const int NumCompute_in) inline protected
Sets NumCompute_.
Definition at line 328 of file Ifpack_Amesos.h.
SetNumInitialize()
void Ifpack_Amesos::SetNumInitialize (const int NumInitialize_in) inline protected
Sets NumInitialize_.
Definition at line 322 of file Ifpack_Amesos.h.
SetParameters()
int Ifpack_Amesos::SetParameters (Teuchos::ParameterList & List) virtual
Sets all the parameters for the preconditioner.
Parameters currently supported:
"amesos: solver type" : Specifies the solver type for Amesos. Default: Amesos_Klu.
The input list will be copied, then passed to the Amesos object through Amesos::SetParameters().
Implements Ifpack_Preconditioner.
Definition at line 117 of file Ifpack_Amesos.cpp.
SetUseTranspose()
int Ifpack_Amesos::SetUseTranspose (bool UseTranspose_in) virtual
If set true, transpose of this operator will be applied (not implemented).
This flag allows the transpose of the given operator to be used implicitly.
Parameters
UseTranspose_in - (In) If true, multiply by the transpose of operator, otherwise just use operator.
Returns
Integer error code, set to 0 if successful. Set to -1 if this implementation does not support transpose.
Implements Epetra_Operator.
Definition at line 239 of file Ifpack_Amesos.cpp.
UseTranspose()
bool Ifpack_Amesos::UseTranspose () const virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Definition at line 307 of file Ifpack_Amesos.cpp.
The documentation for this class was generated from the following files:
Ifpack_Amesos.h
Ifpack_Amesos.cpp