IFPACK: Ifpack_IlukGraph Class Reference
Ifpack_IlukGraph Class Reference
Ifpack_IlukGraph: A class for constructing level filled graphs for use with ILU(k) class preconditioners.
#include <Ifpack_IlukGraph.h>
Public Member Functions
Ifpack_IlukGraph (const Epetra_CrsGraph &Graph_in, int LevelFill_in, int LevelOverlap_in)
Ifpack_IlukGraph constuctor.
Ifpack_IlukGraph (const Ifpack_IlukGraph &Graph_in)
Copy constructor.
virtual ~Ifpack_IlukGraph ()
Ifpack_IlukGraph Destructor.
int SetParameters (const Teuchos::ParameterList &parameterlist, bool cerr_warning_if_unused=false)
Set parameters using Teuchos::ParameterList object.
virtual int ConstructFilledGraph ()
Does the actual construction of the graph.
virtual int ConstructOverlapGraph ()
Does the actual construction of the overlap matrix graph.
virtual int LevelFill () const
Returns the level of fill used to construct this graph.
virtual int LevelOverlap () const
Returns the level of overlap used to construct this graph.
int NumGlobalBlockRows () const
Returns the number of global matrix rows.
int NumGlobalBlockCols () const
Returns the number of global matrix columns.
int NumGlobalRows () const
Returns the number of global matrix rows.
int NumGlobalCols () const
Returns the number of global matrix columns.
int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global graph.
virtual int NumGlobalBlockDiagonals () const
Returns the number of diagonal entries found in the global input graph.
long long NumGlobalBlockRows64 () const
Returns the number of global matrix rows.
long long NumGlobalBlockCols64 () const
Returns the number of global matrix columns.
long long NumGlobalRows64 () const
Returns the number of global matrix rows.
long long NumGlobalCols64 () const
Returns the number of global matrix columns.
long long NumGlobalNonzeros64 () const
Returns the number of nonzero entries in the global graph.
virtual long long NumGlobalBlockDiagonals64 () const
Returns the number of diagonal entries found in the global input graph.
int NumMyBlockRows () const
Returns the number of local matrix rows.
int NumMyBlockCols () const
Returns the number of local matrix columns.
int NumMyRows () const
Returns the number of local matrix rows.
int NumMyCols () const
Returns the number of local matrix columns.
int NumMyNonzeros () const
Returns the number of nonzero entries in the local graph.
virtual int NumMyBlockDiagonals () const
Returns the number of diagonal entries found in the local input graph.
int IndexBase () const
Returns the index base for row and column indices for this graph.
long long IndexBase64 () const
virtual Epetra_CrsGraph & L_Graph ()
Returns the graph of lower triangle of the ILU(k) graph as a Epetra_CrsGraph.
virtual Epetra_CrsGraph & U_Graph ()
Returns the graph of upper triangle of the ILU(k) graph as a Epetra_CrsGraph.
virtual Epetra_CrsGraph & L_Graph () const
Returns the graph of lower triangle of the ILU(k) graph as a Epetra_CrsGraph.
virtual Epetra_CrsGraph & U_Graph () const
Returns the graph of upper triangle of the ILU(k) graph as a Epetra_CrsGraph.
virtual Epetra_Import * OverlapImporter () const
Returns the importer used to create the overlapped graph.
virtual Epetra_CrsGraph * OverlapGraph () const
Returns the the overlapped graph.
virtual const Epetra_BlockMap & DomainMap () const
Returns the Epetra_BlockMap object associated with the domain of this matrix operator.
virtual const Epetra_BlockMap & RangeMap () const
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
virtual const Epetra_Comm & Comm () const
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Friends
std::ostream & operator<< (std::ostream &os, const Ifpack_IlukGraph &A)
<< operator will work for Ifpack_IlukGraph.
Detailed Description
Ifpack_IlukGraph: A class for constructing level filled graphs for use with ILU(k) class preconditioners.
The Ifpack_IlukGraph class enable the construction matrix graphs using level-fill algorithms. The only function required for construction is an ExtractRowView capability, i.e., the matrix that is passed in to the constructor must implement the Ifpack_CrsGraph interface defined in Ifpack_CrsMatrix.h
Constructing Ifpack_IlukGraph objects
Constructing Ifpack_IlukGraph objects is usually a two step process of passing in a Ifpack_CrsGraph object and an integer indicating the desired level of fill and then calling the ConstructFilledGraph function to complete the process. This allows warning error codes to be returned to the calling routine.
It is worth noting that an Ifpack_IlukGraph object has two Epetra_CrsGraph objects containing L and U, the graphs for the lower and upper triangular parts of the ILU(k) graph. Thus, it is possible to manually insert and delete graph entries in L and U via the Epetra_CrsGraph InsertIndices and RemoveIndices functions. However, in this case FillComplete must be called before the graph is used for subsequent operations.
Definition at line 83 of file Ifpack_IlukGraph.h.
Constructor & Destructor Documentation
Ifpack_IlukGraph() [1/2]
Ifpack_IlukGraph::Ifpack_IlukGraph (const Epetra_CrsGraph & Graph_in, int LevelFill_in, int LevelOverlap_in)
Ifpack_IlukGraph constuctor.
Creates a Ifpack_IlukGraph object using the input graph and specified level of fill.
Parameters
In Graph_in - An existing Ifpack_CrsGraph. This object must implement the Ifpack_CrsGraph functions that provide graph dimension and pattern information.
In LevelFill_in - The level of fill to compute via ILU(k) algorithm.
In LevelOverlap_in - The level of between subdomains.
Warning
Actual construction occurs in ConstructFilledGraph. This allows error codes to be passed back to the user.
Definition at line 52 of file Ifpack_IlukGraph.cpp.
Ifpack_IlukGraph() [2/2]
Ifpack_IlukGraph::Ifpack_IlukGraph (const Ifpack_IlukGraph & Graph_in)
Copy constructor.
Definition at line 78 of file Ifpack_IlukGraph.cpp.
References L_Graph(), and U_Graph().
~Ifpack_IlukGraph()
Ifpack_IlukGraph::~Ifpack_IlukGraph () virtual
Ifpack_IlukGraph Destructor.
Definition at line 111 of file Ifpack_IlukGraph.cpp.
Member Function Documentation
Comm()
virtual const Epetra_Comm & Ifpack_IlukGraph::Comm () const inline virtual
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Definition at line 262 of file Ifpack_IlukGraph.h.
ConstructFilledGraph()
int Ifpack_IlukGraph::ConstructFilledGraph () virtual
Does the actual construction of the graph.
Definition at line 177 of file Ifpack_IlukGraph.cpp.
References ConstructOverlapGraph(), Copy, Epetra_CrsGraph::DomainMap(), and Epetra_CrsGraph::RangeMap().
ConstructOverlapGraph()
int Ifpack_IlukGraph::ConstructOverlapGraph () virtual
Does the actual construction of the overlap matrix graph.
Definition at line 131 of file Ifpack_IlukGraph.cpp.
References Copy, Epetra_BlockMap::DistributedGlobal(), Epetra_CrsGraph::DomainMap(), Insert, Epetra_CrsGraph::RangeMap(), and Epetra_CrsGraph::RowMap().
Referenced by ConstructFilledGraph().
DomainMap()
virtual const Epetra_BlockMap & Ifpack_IlukGraph::DomainMap () const inline virtual
Returns the Epetra_BlockMap object associated with the domain of this matrix operator.
Definition at line 256 of file Ifpack_IlukGraph.h.
Referenced by Ifpack_CrsRiluk::Ifpack_CrsRiluk().
IndexBase()
int Ifpack_IlukGraph::IndexBase () const inline
Returns the index base for row and column indices for this graph.
Definition at line 229 of file Ifpack_IlukGraph.h.
References Epetra_BlockMap::GlobalIndicesInt(), and Epetra_CrsGraph::RowMap().
IndexBase64()
long long Ifpack_IlukGraph::IndexBase64 () const inline
Definition at line 235 of file Ifpack_IlukGraph.h.
L_Graph() [1/2]
virtual Epetra_CrsGraph & Ifpack_IlukGraph::L_Graph () inline virtual
Returns the graph of lower triangle of the ILU(k) graph as a Epetra_CrsGraph.
Definition at line 238 of file Ifpack_IlukGraph.h.
Referenced by Ifpack_CrsRick::Factor(), Ifpack_CrsRiluk::Factor(), Ifpack_CrsRick::Ifpack_CrsRick(), Ifpack_IlukGraph(), Ifpack_CrsRick::InitValues(), Ifpack_CrsRick::Multiply(), Ifpack_CrsRick::Solve(), and Ifpack_CrsRick::Solve().
L_Graph() [2/2]
virtual Epetra_CrsGraph & Ifpack_IlukGraph::L_Graph () const inline virtual
Returns the graph of lower triangle of the ILU(k) graph as a Epetra_CrsGraph.
Definition at line 244 of file Ifpack_IlukGraph.h.
LevelFill()
virtual int Ifpack_IlukGraph::LevelFill () const inline virtual
Returns the level of fill used to construct this graph.
Definition at line 137 of file Ifpack_IlukGraph.h.
LevelOverlap()
virtual int Ifpack_IlukGraph::LevelOverlap () const inline virtual
Returns the level of overlap used to construct this graph.
Definition at line 140 of file Ifpack_IlukGraph.h.
Referenced by Ifpack_CrsRiluk::Ifpack_CrsRiluk(), Ifpack_CrsRick::InitValues(), Ifpack_CrsRick::Multiply(), Ifpack_CrsRick::Solve(), and Ifpack_CrsRick::Solve().
NumGlobalBlockCols()
int Ifpack_IlukGraph::NumGlobalBlockCols () const inline
Returns the number of global matrix columns.
Definition at line 152 of file Ifpack_IlukGraph.h.
References Epetra_BlockMap::GlobalIndicesInt(), and Epetra_CrsGraph::RowMap().
NumGlobalBlockCols64()
long long Ifpack_IlukGraph::NumGlobalBlockCols64 () const inline
Returns the number of global matrix columns.
Definition at line 195 of file Ifpack_IlukGraph.h.
NumGlobalBlockDiagonals()
virtual int Ifpack_IlukGraph::NumGlobalBlockDiagonals () const inline virtual
Returns the number of diagonal entries found in the global input graph.
Definition at line 183 of file Ifpack_IlukGraph.h.
References Epetra_BlockMap::GlobalIndicesInt(), and Epetra_CrsGraph::RowMap().
NumGlobalBlockDiagonals64()
virtual long long Ifpack_IlukGraph::NumGlobalBlockDiagonals64 () const inline virtual
Returns the number of diagonal entries found in the global input graph.
Definition at line 206 of file Ifpack_IlukGraph.h.
NumGlobalBlockRows()
int Ifpack_IlukGraph::NumGlobalBlockRows () const inline
Returns the number of global matrix rows.
Definition at line 144 of file Ifpack_IlukGraph.h.
References Epetra_BlockMap::GlobalIndicesInt(), and Epetra_CrsGraph::RowMap().
NumGlobalBlockRows64()
long long Ifpack_IlukGraph::NumGlobalBlockRows64 () const inline
Returns the number of global matrix rows.
Definition at line 192 of file Ifpack_IlukGraph.h.
NumGlobalCols()
int Ifpack_IlukGraph::NumGlobalCols () const inline
Returns the number of global matrix columns.
Definition at line 168 of file Ifpack_IlukGraph.h.
References Epetra_BlockMap::GlobalIndicesInt(), and Epetra_CrsGraph::RowMap().
NumGlobalCols64()
long long Ifpack_IlukGraph::NumGlobalCols64 () const inline
Returns the number of global matrix columns.
Definition at line 201 of file Ifpack_IlukGraph.h.
NumGlobalNonzeros()
int Ifpack_IlukGraph::NumGlobalNonzeros () const inline
Returns the number of nonzero entries in the global graph.
Definition at line 175 of file Ifpack_IlukGraph.h.
References Epetra_BlockMap::GlobalIndicesInt(), and Epetra_CrsGraph::RowMap().
NumGlobalNonzeros64()
long long Ifpack_IlukGraph::NumGlobalNonzeros64 () const inline
Returns the number of nonzero entries in the global graph.
Definition at line 203 of file Ifpack_IlukGraph.h.
NumGlobalRows()
int Ifpack_IlukGraph::NumGlobalRows () const inline
Returns the number of global matrix rows.
Definition at line 160 of file Ifpack_IlukGraph.h.
References Epetra_BlockMap::GlobalIndicesInt(), and Epetra_CrsGraph::RowMap().
NumGlobalRows64()
long long Ifpack_IlukGraph::NumGlobalRows64 () const inline
Returns the number of global matrix rows.
Definition at line 198 of file Ifpack_IlukGraph.h.
NumMyBlockCols()
int Ifpack_IlukGraph::NumMyBlockCols () const inline
Returns the number of local matrix columns.
Definition at line 212 of file Ifpack_IlukGraph.h.
NumMyBlockDiagonals()
virtual int Ifpack_IlukGraph::NumMyBlockDiagonals () const inline virtual
Returns the number of diagonal entries found in the local input graph.
Definition at line 225 of file Ifpack_IlukGraph.h.
NumMyBlockRows()
int Ifpack_IlukGraph::NumMyBlockRows () const inline
Returns the number of local matrix rows.
Definition at line 209 of file Ifpack_IlukGraph.h.
NumMyCols()
int Ifpack_IlukGraph::NumMyCols () const inline
Returns the number of local matrix columns.
Definition at line 219 of file Ifpack_IlukGraph.h.
NumMyNonzeros()
int Ifpack_IlukGraph::NumMyNonzeros () const inline
Returns the number of nonzero entries in the local graph.
Definition at line 222 of file Ifpack_IlukGraph.h.
NumMyRows()
int Ifpack_IlukGraph::NumMyRows () const inline
Returns the number of local matrix rows.
Definition at line 216 of file Ifpack_IlukGraph.h.
OverlapGraph()
virtual Epetra_CrsGraph * Ifpack_IlukGraph::OverlapGraph () const inline virtual
Returns the the overlapped graph.
Definition at line 253 of file Ifpack_IlukGraph.h.
Referenced by Ifpack_CrsRick::InitValues(), Ifpack_CrsRiluk::InitValues(), Ifpack_CrsRiluk::InitValues(), Ifpack_CrsRick::Multiply(), Ifpack_CrsRick::Solve(), and Ifpack_CrsRick::Solve().
OverlapImporter()
virtual Epetra_Import * Ifpack_IlukGraph::OverlapImporter () const inline virtual
Returns the importer used to create the overlapped graph.
Definition at line 250 of file Ifpack_IlukGraph.h.
Referenced by Ifpack_CrsRick::InitValues(), Ifpack_CrsRiluk::InitValues(), Ifpack_CrsRiluk::InitValues(), Ifpack_CrsRick::Multiply(), Ifpack_CrsRick::Solve(), and Ifpack_CrsRick::Solve().
RangeMap()
virtual const Epetra_BlockMap & Ifpack_IlukGraph::RangeMap () const inline virtual
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Definition at line 259 of file Ifpack_IlukGraph.h.
SetParameters()
int Ifpack_IlukGraph::SetParameters (const Teuchos::ParameterList & parameterlist, bool cerr_warning_if_unused = false)
Set parameters using Teuchos::ParameterList object.
Definition at line 116 of file Ifpack_IlukGraph.cpp.
U_Graph() [1/2]
virtual Epetra_CrsGraph & Ifpack_IlukGraph::U_Graph () inline virtual
Returns the graph of upper triangle of the ILU(k) graph as a Epetra_CrsGraph.
Definition at line 241 of file Ifpack_IlukGraph.h.
Referenced by Ifpack_IlukGraph(), and Ifpack_CrsRick::InitValues().
U_Graph() [2/2]
virtual Epetra_CrsGraph & Ifpack_IlukGraph::U_Graph () const inline virtual
Returns the graph of upper triangle of the ILU(k) graph as a Epetra_CrsGraph.
Definition at line 247 of file Ifpack_IlukGraph.h.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Ifpack_IlukGraph & A) friend
<< operator will work for Ifpack_IlukGraph.
Definition at line 422 of file Ifpack_IlukGraph.cpp.
The documentation for this class was generated from the following files:
Ifpack_IlukGraph.h
Ifpack_IlukGraph.cpp