IFPACK: Ifpack_OverlappingRowMatrix Class Reference
Ifpack_OverlappingRowMatrix Class Reference
Ifpack_OverlappingRowMatrix: matrix with ghost rows, based on Epetra_RowMatrix.
#include <Ifpack_OverlappingRowMatrix.h>
Public Member Functions
Ifpack_OverlappingRowMatrix (const Teuchos::RefCountPtr< const Epetra_RowMatrix > &Matrix_in, int OverlapLevel_in)
virtual int NumMyRowEntries (int MyRow, int &NumEntries) const
Returns the number of nonzero entries in MyRow.
virtual int MaxNumEntries () const
Returns the maximum of NumMyRowEntries() over all rows.
virtual int ExtractMyRowCopy (int MyRow, int Length, int &NumEntries, double *Values, int *Indices) const
Returns a copy of the specified local row in user-provided arrays.
virtual int ExtractDiagonalCopy (Epetra_Vector &Diagonal) const
Returns a copy of the main diagonal in a user-provided vector.
virtual int Multiply (bool TransA, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_RowMatrix multiplied by a Epetra_MultiVector X in Y.
virtual int Solve (bool, bool, bool, const Epetra_MultiVector &, Epetra_MultiVector &) const
Returns result of a local-only solve using a triangular Epetra_RowMatrix with Epetra_MultiVectors X and Y (NOT IMPLEMENTED).
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
virtual int InvRowSums (Epetra_Vector &) const
Computes the sum of absolute values of the rows of the Epetra_RowMatrix, results returned in x (NOT IMPLEMENTED).
virtual int LeftScale (const Epetra_Vector &)
Scales the Epetra_RowMatrix on the left with a Epetra_Vector x (NOT IMPLEMENTED).
virtual int InvColSums (Epetra_Vector &) const
Computes the sum of absolute values of the columns of the Epetra_RowMatrix, results returned in x (NOT IMPLEMENTED).
virtual int RightScale (const Epetra_Vector &)
Scales the Epetra_RowMatrix on the right with a Epetra_Vector x (NOT IMPLEMENTED).
virtual bool Filled () const
If FillComplete() has been called, this query returns true, otherwise it returns false.
virtual double NormInf () const
Returns the infinity norm of the global matrix.
virtual double NormOne () const
Returns the one norm of the global matrix.
virtual int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global matrix.
virtual int NumGlobalRows () const
Returns the number of global matrix rows.
virtual int NumGlobalCols () const
Returns the number of global matrix columns.
virtual int NumGlobalDiagonals () const
Returns the number of global nonzero diagonal entries, based on global row/column index comparisons.
virtual long long NumGlobalNonzeros64 () const
Returns the number of nonzero entries in the global matrix.
virtual long long NumGlobalRows64 () const
Returns the number of global matrix rows.
virtual long long NumGlobalCols64 () const
Returns the number of global matrix columns.
virtual long long NumGlobalDiagonals64 () const
Returns the number of global nonzero diagonal entries, based on global row/column index comparisons.
virtual int NumMyNonzeros () const
Returns the number of nonzero entries in the calling processor's portion of the matrix.
virtual int NumMyRows () const
Returns the number of matrix rows owned by the calling processor.
virtual int NumMyCols () const
Returns the number of matrix columns owned by the calling processor.
virtual int NumMyDiagonals () const
Returns the number of local nonzero diagonal entries, based on global row/column index comparisons.
virtual bool LowerTriangular () const
If matrix is lower triangular in local index space, this query returns true, otherwise it returns false.
virtual bool UpperTriangular () const
If matrix is upper triangular in local index space, this query returns true, otherwise it returns false.
virtual const Epetra_Map & RowMatrixRowMap () const
Returns the Epetra_Map object associated with the rows of this matrix.
virtual const Epetra_Map & RowMatrixColMap () const
Returns the Epetra_Map object associated with the columns of this matrix.
virtual const Epetra_Import * RowMatrixImporter () const
Returns the Epetra_Import object that contains the import operations for distributed operations.
int SetOwnership (bool)
Sets ownership.
int SetUseTranspose (bool UseTranspose_in)
Sets use transpose (not implemented).
bool UseTranspose () const
Returns the current UseTranspose setting.
bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
const Epetra_BlockMap & Map () const
const char * Label () const
int OverlapLevel () const
int ImportMultiVector (const Epetra_MultiVector &X, Epetra_MultiVector &OvX, Epetra_CombineMode CM=Insert)
int ExportMultiVector (const Epetra_MultiVector &OvX, Epetra_MultiVector &X, Epetra_CombineMode CM=Add)
Detailed Description
Ifpack_OverlappingRowMatrix: matrix with ghost rows, based on Epetra_RowMatrix.
Definition at line 74 of file Ifpack_OverlappingRowMatrix.h.
Constructor & Destructor Documentation
Ifpack_OverlappingRowMatrix()
Ifpack_OverlappingRowMatrix::Ifpack_OverlappingRowMatrix (const Teuchos::RefCountPtr< const Epetra_RowMatrix > & Matrix_in, int OverlapLevel_in)
Definition at line 164 of file Ifpack_OverlappingRowMatrix.cpp.
~Ifpack_OverlappingRowMatrix()
Ifpack_OverlappingRowMatrix::~Ifpack_OverlappingRowMatrix () inline
Definition at line 97 of file Ifpack_OverlappingRowMatrix.h.
Member Function Documentation
Apply()
int Ifpack_OverlappingRowMatrix::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Implements Epetra_Operator.
Definition at line 1771 of file Ifpack_OverlappingRowMatrix.cpp.
ApplyInverse()
int Ifpack_OverlappingRowMatrix::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Implements Epetra_Operator.
Definition at line 1779 of file Ifpack_OverlappingRowMatrix.cpp.
Comm()
const Epetra_Comm & Ifpack_OverlappingRowMatrix::Comm () const inline virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Epetra_Operator.
Definition at line 378 of file Ifpack_OverlappingRowMatrix.h.
References Comm().
Referenced by Comm().
ExportMultiVector()
int Ifpack_OverlappingRowMatrix::ExportMultiVector (const Epetra_MultiVector & OvX, Epetra_MultiVector & X, Epetra_CombineMode CM = Add)
Definition at line 1810 of file Ifpack_OverlappingRowMatrix.cpp.
ExtractDiagonalCopy()
int Ifpack_OverlappingRowMatrix::ExtractDiagonalCopy (Epetra_Vector & Diagonal) const virtual
Returns a copy of the main diagonal in a user-provided vector.
Parameters
Diagonal - (Out) Extracted main diagonal.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Definition at line 1727 of file Ifpack_OverlappingRowMatrix.cpp.
ExtractMyRowCopy()
int Ifpack_OverlappingRowMatrix::ExtractMyRowCopy (int MyRow, int Length, int & NumEntries, double * Values, int * Indices) const virtual
Returns a copy of the specified local row in user-provided arrays.
Parameters
MyRow - (In) Local row to extract.
Length - (In) Length of Values and Indices.
NumEntries - (Out) Number of nonzero entries extracted.
Values - (Out) Extracted values for this row.
Indices - (Out) Extracted global column indices for the corresponding values.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Definition at line 1710 of file Ifpack_OverlappingRowMatrix.cpp.
References Epetra_RowMatrix::ExtractMyRowCopy().
Referenced by Multiply().
Filled()
virtual bool Ifpack_OverlappingRowMatrix::Filled () const inline virtual
If FillComplete() has been called, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
Definition at line 212 of file Ifpack_OverlappingRowMatrix.h.
HasNormInf()
bool Ifpack_OverlappingRowMatrix::HasNormInf () const inline virtual
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
Implements Epetra_Operator.
Definition at line 372 of file Ifpack_OverlappingRowMatrix.h.
References HasNormInf().
Referenced by HasNormInf().
ImportMultiVector()
int Ifpack_OverlappingRowMatrix::ImportMultiVector (const Epetra_MultiVector & X, Epetra_MultiVector & OvX, Epetra_CombineMode CM = Insert)
Definition at line 1801 of file Ifpack_OverlappingRowMatrix.cpp.
InvColSums()
virtual int Ifpack_OverlappingRowMatrix::InvColSums (Epetra_Vector &) const inline virtual
Computes the sum of absolute values of the columns of the Epetra_RowMatrix, results returned in x (NOT IMPLEMENTED).
Implements Epetra_RowMatrix.
Definition at line 195 of file Ifpack_OverlappingRowMatrix.h.
InvRowSums()
virtual int Ifpack_OverlappingRowMatrix::InvRowSums (Epetra_Vector &) const inline virtual
Computes the sum of absolute values of the rows of the Epetra_RowMatrix, results returned in x (NOT IMPLEMENTED).
Implements Epetra_RowMatrix.
Definition at line 183 of file Ifpack_OverlappingRowMatrix.h.
Label()
const char * Ifpack_OverlappingRowMatrix::Label () const inline virtual
Implements Epetra_Operator.
Definition at line 398 of file Ifpack_OverlappingRowMatrix.h.
LeftScale()
virtual int Ifpack_OverlappingRowMatrix::LeftScale (const Epetra_Vector &) inline virtual
Scales the Epetra_RowMatrix on the left with a Epetra_Vector x (NOT IMPLEMENTED).
Implements Epetra_RowMatrix.
Definition at line 189 of file Ifpack_OverlappingRowMatrix.h.
LowerTriangular()
virtual bool Ifpack_OverlappingRowMatrix::LowerTriangular () const inline virtual
If matrix is lower triangular in local index space, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
Definition at line 312 of file Ifpack_OverlappingRowMatrix.h.
References LowerTriangular().
Referenced by LowerTriangular().
Map()
const Epetra_BlockMap & Ifpack_OverlappingRowMatrix::Map () const virtual
Implements Epetra_SrcDistObject.
Definition at line 1795 of file Ifpack_OverlappingRowMatrix.cpp.
MaxNumEntries()
virtual int Ifpack_OverlappingRowMatrix::MaxNumEntries () const inline virtual
Returns the maximum of NumMyRowEntries() over all rows.
Implements Epetra_RowMatrix.
Definition at line 116 of file Ifpack_OverlappingRowMatrix.h.
Multiply()
int Ifpack_OverlappingRowMatrix::Multiply (bool TransA, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Epetra_RowMatrix multiplied by a Epetra_MultiVector X in Y.
Parameters
TransA -(In) If true, multiply by the transpose of matrix, otherwise just use matrix.
X - (In) A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Y -(Out) A Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Definition at line 1735 of file Ifpack_OverlappingRowMatrix.cpp.
References ExtractMyRowCopy(), Epetra_MultiVector::NumVectors(), and Epetra_MultiVector::PutScalar().
NormInf()
virtual double Ifpack_OverlappingRowMatrix::NormInf () const inline virtual
Returns the infinity norm of the global matrix.
Implements Epetra_RowMatrix.
Definition at line 221 of file Ifpack_OverlappingRowMatrix.h.
References NormInf().
Referenced by NormInf().
NormOne()
virtual double Ifpack_OverlappingRowMatrix::NormOne () const inline virtual
Returns the one norm of the global matrix.
Implements Epetra_RowMatrix.
Definition at line 230 of file Ifpack_OverlappingRowMatrix.h.
References NormOne().
Referenced by NormOne().
NumGlobalCols()
virtual int Ifpack_OverlappingRowMatrix::NumGlobalCols () const inline virtual
Returns the number of global matrix columns.
Implements Epetra_RowMatrix.
Definition at line 252 of file Ifpack_OverlappingRowMatrix.h.
References NumGlobalCols().
Referenced by NumGlobalCols().
NumGlobalCols64()
virtual long long Ifpack_OverlappingRowMatrix::NumGlobalCols64 () const inline virtual
Returns the number of global matrix columns.
Definition at line 276 of file Ifpack_OverlappingRowMatrix.h.
References NumGlobalCols64().
Referenced by NumGlobalCols64().
NumGlobalDiagonals()
virtual int Ifpack_OverlappingRowMatrix::NumGlobalDiagonals () const inline virtual
Returns the number of global nonzero diagonal entries, based on global row/column index comparisons.
Implements Epetra_RowMatrix.
Definition at line 258 of file Ifpack_OverlappingRowMatrix.h.
References NumGlobalDiagonals().
Referenced by NumGlobalDiagonals().
NumGlobalDiagonals64()
virtual long long Ifpack_OverlappingRowMatrix::NumGlobalDiagonals64 () const inline virtual
Returns the number of global nonzero diagonal entries, based on global row/column index comparisons.
Definition at line 282 of file Ifpack_OverlappingRowMatrix.h.
References NumGlobalDiagonals64().
Referenced by NumGlobalDiagonals64().
NumGlobalNonzeros()
virtual int Ifpack_OverlappingRowMatrix::NumGlobalNonzeros () const inline virtual
Returns the number of nonzero entries in the global matrix.
Implements Epetra_RowMatrix.
Definition at line 237 of file Ifpack_OverlappingRowMatrix.h.
References RowMatrixRowMap().
NumGlobalNonzeros64()
virtual long long Ifpack_OverlappingRowMatrix::NumGlobalNonzeros64 () const inline virtual
Returns the number of nonzero entries in the global matrix.
Definition at line 264 of file Ifpack_OverlappingRowMatrix.h.
NumGlobalRows()
virtual int Ifpack_OverlappingRowMatrix::NumGlobalRows () const inline virtual
Returns the number of global matrix rows.
Implements Epetra_RowMatrix.
Definition at line 246 of file Ifpack_OverlappingRowMatrix.h.
References NumGlobalRows().
Referenced by NumGlobalRows().
NumGlobalRows64()
virtual long long Ifpack_OverlappingRowMatrix::NumGlobalRows64 () const inline virtual
Returns the number of global matrix rows.
Definition at line 270 of file Ifpack_OverlappingRowMatrix.h.
References NumGlobalRows64().
Referenced by NumGlobalRows64().
NumMyCols()
virtual int Ifpack_OverlappingRowMatrix::NumMyCols () const inline virtual
Returns the number of matrix columns owned by the calling processor.
Implements Epetra_RowMatrix.
Definition at line 300 of file Ifpack_OverlappingRowMatrix.h.
NumMyDiagonals()
virtual int Ifpack_OverlappingRowMatrix::NumMyDiagonals () const inline virtual
Returns the number of local nonzero diagonal entries, based on global row/column index comparisons.
Implements Epetra_RowMatrix.
Definition at line 306 of file Ifpack_OverlappingRowMatrix.h.
NumMyNonzeros()
virtual int Ifpack_OverlappingRowMatrix::NumMyNonzeros () const inline virtual
Returns the number of nonzero entries in the calling processor's portion of the matrix.
Implements Epetra_RowMatrix.
Definition at line 288 of file Ifpack_OverlappingRowMatrix.h.
NumMyRowEntries()
int Ifpack_OverlappingRowMatrix::NumMyRowEntries (int MyRow, int & NumEntries) const virtual
Returns the number of nonzero entries in MyRow.
Parameters
MyRow - (In) Local row.
NumEntries - (Out) Number of nonzero values present.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_RowMatrix.
Definition at line 1601 of file Ifpack_OverlappingRowMatrix.cpp.
References NumMyRowEntries().
Referenced by NumMyRowEntries().
NumMyRows()
virtual int Ifpack_OverlappingRowMatrix::NumMyRows () const inline virtual
Returns the number of matrix rows owned by the calling processor.
Implements Epetra_RowMatrix.
Definition at line 294 of file Ifpack_OverlappingRowMatrix.h.
OperatorDomainMap()
const Epetra_Map & Ifpack_OverlappingRowMatrix::OperatorDomainMap () const inline virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
Definition at line 384 of file Ifpack_OverlappingRowMatrix.h.
OperatorRangeMap()
const Epetra_Map & Ifpack_OverlappingRowMatrix::OperatorRangeMap () const inline virtual
Returns the Epetra_Map object associated with the range of this operator.
Implements Epetra_Operator.
Definition at line 390 of file Ifpack_OverlappingRowMatrix.h.
OverlapLevel()
int Ifpack_OverlappingRowMatrix::OverlapLevel () const inline
Definition at line 402 of file Ifpack_OverlappingRowMatrix.h.
RightScale()
virtual int Ifpack_OverlappingRowMatrix::RightScale (const Epetra_Vector &) inline virtual
Scales the Epetra_RowMatrix on the right with a Epetra_Vector x (NOT IMPLEMENTED).
Implements Epetra_RowMatrix.
Definition at line 202 of file Ifpack_OverlappingRowMatrix.h.
RowMatrixColMap()
virtual const Epetra_Map & Ifpack_OverlappingRowMatrix::RowMatrixColMap () const inline virtual
Returns the Epetra_Map object associated with the columns of this matrix.
Implements Epetra_RowMatrix.
Definition at line 330 of file Ifpack_OverlappingRowMatrix.h.
RowMatrixImporter()
virtual const Epetra_Import * Ifpack_OverlappingRowMatrix::RowMatrixImporter () const inline virtual
Returns the Epetra_Import object that contains the import operations for distributed operations.
Implements Epetra_RowMatrix.
Definition at line 344 of file Ifpack_OverlappingRowMatrix.h.
RowMatrixRowMap()
virtual const Epetra_Map & Ifpack_OverlappingRowMatrix::RowMatrixRowMap () const inline virtual
Returns the Epetra_Map object associated with the rows of this matrix.
Implements Epetra_RowMatrix.
Definition at line 324 of file Ifpack_OverlappingRowMatrix.h.
Referenced by NumGlobalNonzeros().
SetOwnership()
int Ifpack_OverlappingRowMatrix::SetOwnership (bool) inline
Sets ownership.
Definition at line 353 of file Ifpack_OverlappingRowMatrix.h.
SetUseTranspose()
int Ifpack_OverlappingRowMatrix::SetUseTranspose (bool UseTranspose_in) inline virtual
Sets use transpose (not implemented).
Implements Epetra_Operator.
Definition at line 359 of file Ifpack_OverlappingRowMatrix.h.
Solve()
virtual int Ifpack_OverlappingRowMatrix::Solve (bool , bool , bool , const Epetra_MultiVector & , Epetra_MultiVector &) const inline virtual
Returns result of a local-only solve using a triangular Epetra_RowMatrix with Epetra_MultiVectors X and Y (NOT IMPLEMENTED).
Implements Epetra_RowMatrix.
Definition at line 171 of file Ifpack_OverlappingRowMatrix.h.
UpperTriangular()
virtual bool Ifpack_OverlappingRowMatrix::UpperTriangular () const inline virtual
If matrix is upper triangular in local index space, this query returns true, otherwise it returns false.
Implements Epetra_RowMatrix.
Definition at line 318 of file Ifpack_OverlappingRowMatrix.h.
References UpperTriangular().
Referenced by UpperTriangular().
UseTranspose()
bool Ifpack_OverlappingRowMatrix::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Definition at line 366 of file Ifpack_OverlappingRowMatrix.h.
The documentation for this class was generated from the following files:
Ifpack_OverlappingRowMatrix.h
Ifpack_OverlappingRowMatrix.cpp