IFPACK: Ifpack_METISReordering Class Reference
Ifpack_METISReordering Class Reference
Ifpack_METISReordering: A class to reorder a graph using METIS.
#include <Ifpack_METISReordering.h>
Public Member Functions
Ifpack_METISReordering ()
Constructor.
virtual ~Ifpack_METISReordering ()
Destructor.
virtual int SetParameter (const std::string Name, const int Value)
Sets integer parameters ‘Name’.
virtual int SetParameter (const std::string, const double)
Sets double parameters ‘Name’.
virtual int SetParameters (Teuchos::ParameterList &List)
Sets all the parameters for the partitioner (none at moment).
virtual int Compute (const Ifpack_Graph &Graph)
Computes all it is necessary to initialize the reordering object.
virtual int Compute (const Epetra_RowMatrix &Matrix)
Computes all it is necessary to initialize the reordering object.
virtual bool IsComputed () const
Returns true is the reordering object has been successfully initialized, false otherwise.
virtual int Reorder (const int i) const
Returns the reordered index of row i.
virtual int InvReorder (const int i) const
Returns the inverse reordered index of row i.
virtual int P (const Epetra_MultiVector &Xorig, Epetra_MultiVector &X) const
Applies reordering to multivector Xorig, whose local length equals the number of local rows, stores result in X.
virtual int Pinv (const Epetra_MultiVector &Xorig, Epetra_MultiVector &X) const
Applies inverse reordering to multivector Xorig, whose local length equals the number of local rows, stores result in X.
virtual std::ostream & Print (std::ostream &os) const
Prints basic information on iostream. This function is used by operator<<.
Public Member Functions inherited from Ifpack_Reordering
virtual ~Ifpack_Reordering ()
Destructor.
Detailed Description
Ifpack_METISReordering: A class to reorder a graph using METIS.
Definition at line 66 of file Ifpack_METISReordering.h.
Constructor & Destructor Documentation
Ifpack_METISReordering()
Ifpack_METISReordering::Ifpack_METISReordering ()
Constructor.
Definition at line 64 of file Ifpack_METISReordering.cpp.
~Ifpack_METISReordering()
virtual Ifpack_METISReordering::~Ifpack_METISReordering () inline virtual
Destructor.
Definition at line 74 of file Ifpack_METISReordering.h.
Member Function Documentation
Compute() [1/2]
int Ifpack_METISReordering::Compute (const Epetra_RowMatrix & Matrix) virtual
Computes all it is necessary to initialize the reordering object.
Implements Ifpack_Reordering.
Definition at line 216 of file Ifpack_METISReordering.cpp.
References Compute().
Compute() [2/2]
int Ifpack_METISReordering::Compute (const Ifpack_Graph & Graph) virtual
Computes all it is necessary to initialize the reordering object.
Implements Ifpack_Reordering.
Definition at line 78 of file Ifpack_METISReordering.cpp.
References Copy.
Referenced by Compute().
InvReorder()
int Ifpack_METISReordering::InvReorder (const int i) const virtual
Returns the inverse reordered index of row i.
Implements Ifpack_Reordering.
Definition at line 239 of file Ifpack_METISReordering.cpp.
References IsComputed().
IsComputed()
virtual bool Ifpack_METISReordering::IsComputed () const inline virtual
Returns true is the reordering object has been successfully initialized, false otherwise.
Implements Ifpack_Reordering.
Definition at line 106 of file Ifpack_METISReordering.h.
Referenced by InvReorder(), Print(), and Reorder().
P()
int Ifpack_METISReordering::P (const Epetra_MultiVector & Xorig, Epetra_MultiVector & X) const virtual
Applies reordering to multivector Xorig, whose local length equals the number of local rows, stores result in X.
Implements Ifpack_Reordering.
Definition at line 251 of file Ifpack_METISReordering.cpp.
References Epetra_MultiVector::NumVectors().
Pinv()
int Ifpack_METISReordering::Pinv (const Epetra_MultiVector & Xorig, Epetra_MultiVector & X) const virtual
Applies inverse reordering to multivector Xorig, whose local length equals the number of local rows, stores result in X.
Implements Ifpack_Reordering.
Definition at line 267 of file Ifpack_METISReordering.cpp.
References Epetra_MultiVector::NumVectors().
Print()
std::ostream & Ifpack_METISReordering::Print (std::ostream & os) const virtual
Prints basic information on iostream. This function is used by operator<<.
Implements Ifpack_Reordering.
Definition at line 283 of file Ifpack_METISReordering.cpp.
References IsComputed().
Reorder()
int Ifpack_METISReordering::Reorder (const int i) const virtual
Returns the reordered index of row i.
Implements Ifpack_Reordering.
Definition at line 226 of file Ifpack_METISReordering.cpp.
References IsComputed().
SetParameter() [1/2]
virtual int Ifpack_METISReordering::SetParameter (const std::string Name, const int Value) inline virtual
Sets integer parameters ‘Name’.
Implements Ifpack_Reordering.
Definition at line 77 of file Ifpack_METISReordering.h.
SetParameter() [2/2]
virtual int Ifpack_METISReordering::SetParameter (const std::string , const double) inline virtual
Sets double parameters ‘Name’.
Implements Ifpack_Reordering.
Definition at line 85 of file Ifpack_METISReordering.h.
SetParameters()
virtual int Ifpack_METISReordering::SetParameters (Teuchos::ParameterList & List) inline virtual
Sets all the parameters for the partitioner (none at moment).
Implements Ifpack_Reordering.
Definition at line 91 of file Ifpack_METISReordering.h.
The documentation for this class was generated from the following files:
Ifpack_METISReordering.h
Ifpack_METISReordering.cpp