IFPACK: Ifpack_Graph Class Reference
Ifpack_Graph Class Reference abstract
Ifpack_Graph: a pure virtual class that defines graphs for IFPACK.
#include <Ifpack_Graph.h>
Public Member Functions
virtual ~Ifpack_Graph ()
Destructor.
virtual int NumMyRows () const =0
Returns the number of local rows.
virtual int NumMyCols () const =0
Returns the number of local columns.
virtual int NumGlobalRows () const =0
Returns the number of global rows.
virtual int NumGlobalCols () const =0
Returns the number of global columns.
virtual long long NumGlobalRows64 () const =0
virtual long long NumGlobalCols64 () const =0
virtual int MaxMyNumEntries () const =0
Returns the maximun number of entries for row.
virtual int NumMyNonzeros () const =0
Returns the number of local nonzero entries.
virtual bool Filled () const =0
Returns true is graph is filled.
virtual int GRID (int) const =0
Returns the global row ID of input local row.
virtual int GCID (int) const =0
Returns the global column ID of input local column.
virtual long long GRID64 (int) const =0
virtual long long GCID64 (int) const =0
Returns the global column ID of input local column.
virtual int LRID (int) const =0
Returns the local row ID of input global row.
virtual int LCID (int) const =0
Returns the local column ID of input global column.
virtual int LRID (long long) const =0
Returns the local row ID of input global row.
virtual int LCID (long long) const =0
Returns the local column ID of input global column.
virtual int ExtractMyRowCopy (int MyRow, int LenOfIndices, int &NumIndices, int *Indices) const =0
Extracts a copy of input local row.
virtual const Epetra_Comm & Comm () const =0
Returns the communicator object of the graph.
virtual std::ostream & Print (std::ostream &os) const =0
Prints basic information about the graph object.
Detailed Description
Ifpack_Graph: a pure virtual class that defines graphs for IFPACK.
Class Ifpack_Graph defines the abstract interface to use graphs in IFPACK. This class contains all the functions that are required by IFPACK classes.
Author
Marzio Sala, SNL 9214.
Date
Last modified on Nov-04.
Definition at line 67 of file Ifpack_Graph.h.
Constructor & Destructor Documentation
~Ifpack_Graph()
virtual Ifpack_Graph::~Ifpack_Graph () inline virtual
Destructor.
Definition at line 72 of file Ifpack_Graph.h.
Member Function Documentation
Comm()
virtual const Epetra_Comm & Ifpack_Graph::Comm () const pure virtual
Returns the communicator object of the graph.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
Referenced by Ifpack_OverlappingPartitioner::Comm(), and Ifpack_METISPartitioner::ComputePartitions().
ExtractMyRowCopy()
virtual int Ifpack_Graph::ExtractMyRowCopy (int MyRow, int LenOfIndices, int & NumIndices, int * Indices) const pure virtual
Extracts a copy of input local row.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
Referenced by Ifpack_OverlappingPartitioner::ComputeOverlappingPartitions(), Ifpack_GreedyPartitioner::ComputePartitions(), and Ifpack_METISPartitioner::ComputePartitions().
Filled()
virtual bool Ifpack_Graph::Filled () const pure virtual
Returns true is graph is filled.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
Referenced by Ifpack_OverlappingPartitioner::Compute().
GCID()
virtual int Ifpack_Graph::GCID (int) const pure virtual
Returns the global column ID of input local column.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
GCID64()
virtual long long Ifpack_Graph::GCID64 (int) const pure virtual
Returns the global column ID of input local column.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
GRID()
virtual int Ifpack_Graph::GRID (int) const pure virtual
Returns the global row ID of input local row.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
LCID() [1/2]
virtual int Ifpack_Graph::LCID (int) const pure virtual
Returns the local column ID of input global column.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
LCID() [2/2]
virtual int Ifpack_Graph::LCID (long long) const pure virtual
Returns the local column ID of input global column.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
LRID() [1/2]
virtual int Ifpack_Graph::LRID (int) const pure virtual
Returns the local row ID of input global row.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
LRID() [2/2]
virtual int Ifpack_Graph::LRID (long long) const pure virtual
Returns the local row ID of input global row.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
MaxMyNumEntries()
virtual int Ifpack_Graph::MaxMyNumEntries () const pure virtual
Returns the maximun number of entries for row.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
Referenced by Ifpack_OverlappingPartitioner::ComputeOverlappingPartitions(), and Ifpack_OverlappingPartitioner::MaxNumEntries().
NumGlobalCols()
virtual int Ifpack_Graph::NumGlobalCols () const pure virtual
Returns the number of global columns.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
NumGlobalRows()
virtual int Ifpack_Graph::NumGlobalRows () const pure virtual
Returns the number of global rows.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
Referenced by Ifpack_OverlappingPartitioner::NumGlobalRows().
NumMyCols()
virtual int Ifpack_Graph::NumMyCols () const pure virtual
Returns the number of local columns.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
NumMyNonzeros()
virtual int Ifpack_Graph::NumMyNonzeros () const pure virtual
Returns the number of local nonzero entries.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
Referenced by Ifpack_OverlappingPartitioner::NumMyNonzeros().
NumMyRows()
virtual int Ifpack_Graph::NumMyRows () const pure virtual
Returns the number of local rows.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
Referenced by Ifpack_OverlappingPartitioner::NumMyRows(), Ifpack_OverlappingPartitioner::Print(), and Ifpack_OverlappingPartitioner::SetParameters().
Print()
virtual std::ostream & Ifpack_Graph::Print (std::ostream & os) const pure virtual
Prints basic information about the graph object.
Implemented in Ifpack_Graph_Epetra_CrsGraph, and Ifpack_Graph_Epetra_RowMatrix.
The documentation for this class was generated from the following file:
Ifpack_Graph.h