IFPACK: Ifpack_SerialTriDiSolver Class Reference
Ifpack_SerialTriDiSolver Class Reference
Ifpack_SerialTriDiSolver: A class for solving TriDi linear problems.
#include <Ifpack_SerialTriDiSolver.h>
Public Member Functions
Constructor/Destructor Methods
Ifpack_SerialTriDiSolver ()
Default constructor; matrix should be set using SetMatrix(), LHS and RHS set with SetVectors().
virtual ~Ifpack_SerialTriDiSolver ()
Ifpack_SerialTriDiSolver destructor.
Set Methods
int SetMatrix (Ifpack_SerialTriDiMatrix &A)
Sets the pointers for coefficient matrix.
int SetVectors (Epetra_SerialDenseMatrix &X, Epetra_SerialDenseMatrix &B)
Sets the pointers for left and right hand side vector(s).
Strategy modifying Methods
void SolveWithTranspose (bool Flag)
Causes equilibration to be called just before the matrix factorization as part of the call to Factor.
void SolveToRefinedSolution (bool Flag)
Causes all solves to compute solution to best ability using iterative refinement.
void EstimateSolutionErrors (bool Flag)
Causes all solves to estimate the forward and backward solution error.
Factor/Solve/Invert Methods
virtual int Factor (void)
Computes the in-place LU factorization of the matrix using the LAPACK routine DGETRF.
virtual int Solve (void)
Computes the solution X to AX = B for the this matrix and the B provided to SetVectors()..
virtual int Invert (void)
Inverts the this matrix.
virtual int ApplyRefinement (void)
Apply Iterative Refinement.
virtual int ReciprocalConditionEstimate (double &Value)
Unscales the solution vectors if equilibration was used to solve the system.
Query methods
bool Transpose ()
Returns true if transpose of this matrix has and will be used.
bool Factored ()
Returns true if matrix is factored (factor available via AF() and LDAF()).
bool SolutionErrorsEstimated ()
Returns true if forward and backward error estimated have been computed (available via FERR() and BERR()).
bool Inverted ()
Returns true if matrix inverse has been computed (inverse available via AF() and LDAF()).
bool ReciprocalConditionEstimated ()
Returns true if the condition number of the this matrix has been computed (value available via ReciprocalConditionEstimate()).
bool Solved ()
Returns true if the current set of vectors has been solved.
bool SolutionRefined ()
Returns true if the current set of vectors has been refined.
Data Accessor methods
Ifpack_SerialTriDiMatrix * Matrix () const
Returns pointer to current matrix.
Ifpack_SerialTriDiMatrix * FactoredMatrix () const
Returns pointer to factored matrix (assuming factorization has been performed).
Epetra_SerialDenseMatrix * LHS () const
Returns pointer to current LHS.
Epetra_SerialDenseMatrix * RHS () const
Returns pointer to current RHS.
int N () const
Returns column dimension of system.
double * A () const
Returns pointer to the this matrix.
int LDA () const
Returns the leading dimension of the this matrix.
double * B () const
Returns pointer to current RHS.
int LDB () const
Returns the leading dimension of the RHS.
int NRHS () const
Returns the number of current right hand sides and solution vectors.
double * X () const
Returns pointer to current solution.
int LDX () const
Returns the leading dimension of the solution.
double * AF () const
Returns pointer to the factored matrix (may be the same as A() if factorization done in place).
int LDAF () const
Returns the leading dimension of the factored matrix.
int * IPIV () const
Returns pointer to pivot vector (if factorization has been computed), zero otherwise.
double ANORM () const
Returns the 1-Norm of the this matrix (returns -1 if not yet computed).
double RCOND () const
Returns the reciprocal of the condition number of the this matrix (returns -1 if not yet computed).
double ROWCND () const
Ratio of smallest to largest row scale factors for the this matrix (returns -1 if not yet computed).
double COLCND () const
Ratio of smallest to largest column scale factors for the this matrix (returns -1 if not yet computed).
double AMAX () const
Returns the absolute value of the largest entry of the this matrix (returns -1 if not yet computed).
double * FERR () const
Returns a pointer to the forward error estimates computed by LAPACK.
double * BERR () const
Returns a pointer to the backward error estimates computed by LAPACK.
Public Member Functions inherited from Epetra_CompObject
Epetra_CompObject (const Epetra_CompObject &Source)
void SetFlopCounter (const Epetra_Flops &FlopCounter_in)
void SetFlopCounter (const Epetra_CompObject &CompObject)
void UnsetFlopCounter ()
Epetra_Flops * GetFlopCounter () const
void ResetFlops () const
double Flops () const
void UpdateFlops (int Flops_in) const
void UpdateFlops (long int Flops_in) const
void UpdateFlops (long long Flops_in) const
void UpdateFlops (double Flops_in) const
void UpdateFlops (float Flops_in) const
Epetra_CompObject (const Epetra_CompObject &Source)
void SetFlopCounter (const Epetra_Flops &FlopCounter_in)
void SetFlopCounter (const Epetra_CompObject &CompObject)
void UnsetFlopCounter ()
Epetra_Flops * GetFlopCounter () const
void ResetFlops () const
double Flops () const
Public Member Functions inherited from Epetra_BLAS
Epetra_BLAS (const Epetra_BLAS &BLAS)
float ASUM (const int N, const float *X, const int INCX=1) const
double ASUM (const int N, const double *X, const int INCX=1) const
float DOT (const int N, const float *X, const float *Y, const int INCX=1, const int INCY=1) const
double DOT (const int N, const double *X, const double *Y, const int INCX=1, const int INCY=1) const
float NRM2 (const int N, const float *X, const int INCX=1) const
double NRM2 (const int N, const double *X, const int INCX=1) const
void SCAL (const int N, const float ALPHA, float *X, const int INCX=1) const
void SCAL (const int N, const double ALPHA, double *X, const int INCX=1) const
void COPY (const int N, const float *X, float *Y, const int INCX=1, const int INCY=1) const
void COPY (const int N, const double *X, double *Y, const int INCX=1, const int INCY=1) const
int IAMAX (const int N, const float *X, const int INCX=1) const
int IAMAX (const int N, const double *X, const int INCX=1) const
void AXPY (const int N, const float ALPHA, const float *X, float *Y, const int INCX=1, const int INCY=1) const
void AXPY (const int N, const double ALPHA, const double *X, double *Y, const int INCX=1, const int INCY=1) const
void GEMV (const char TRANS, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *X, const float BETA, float *Y, const int INCX=1, const int INCY=1) const
void GEMV (const char TRANS, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *X, const double BETA, double *Y, const int INCX=1, const int INCY=1) const
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const float ALPHA, const float *A, const int LDA, float *B, const int LDB) const
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const double ALPHA, const double *A, const int LDA, double *B, const int LDB) const
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float BETA, float *C, const int LDC) const
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double BETA, double *C, const int LDC) const
Epetra_BLAS (const Epetra_BLAS &BLAS)
float ASUM (const int N, const float *X, const int INCX=1) const
double ASUM (const int N, const double *X, const int INCX=1) const
float DOT (const int N, const float *X, const float *Y, const int INCX=1, const int INCY=1) const
double DOT (const int N, const double *X, const double *Y, const int INCX=1, const int INCY=1) const
float NRM2 (const int N, const float *X, const int INCX=1) const
double NRM2 (const int N, const double *X, const int INCX=1) const
void SCAL (const int N, const float ALPHA, float *X, const int INCX=1) const
void SCAL (const int N, const double ALPHA, double *X, const int INCX=1) const
void COPY (const int N, const float *X, float *Y, const int INCX=1, const int INCY=1) const
void COPY (const int N, const double *X, double *Y, const int INCX=1, const int INCY=1) const
int IAMAX (const int N, const float *X, const int INCX=1) const
int IAMAX (const int N, const double *X, const int INCX=1) const
void AXPY (const int N, const float ALPHA, const float *X, float *Y, const int INCX=1, const int INCY=1) const
void AXPY (const int N, const double ALPHA, const double *X, double *Y, const int INCX=1, const int INCY=1) const
void GEMV (const char TRANS, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *X, const float BETA, float *Y, const int INCX=1, const int INCY=1) const
void GEMV (const char TRANS, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *X, const double BETA, double *Y, const int INCX=1, const int INCY=1) const
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
void GEMM (const char TRANSA, const char TRANSB, const int M, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const float ALPHA, const float *A, const int LDA, const float *B, const int LDB, const float BETA, float *C, const int LDC) const
void SYMM (const char SIDE, const char UPLO, const int M, const int N, const double ALPHA, const double *A, const int LDA, const double *B, const int LDB, const double BETA, double *C, const int LDC) const
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const float ALPHA, const float *A, const int LDA, float *B, const int LDB) const
void TRMM (const char SIDE, const char UPLO, const char TRANSA, const char DIAG, const int M, const int N, const double ALPHA, const double *A, const int LDA, double *B, const int LDB) const
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const float ALPHA, const float *A, const int LDA, const float BETA, float *C, const int LDC) const
void SYRK (const char UPLO, const char TRANS, const int N, const int K, const double ALPHA, const double *A, const int LDA, const double BETA, double *C, const int LDC) const
Public Member Functions inherited from Epetra_Object
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object (const Epetra_Object &Object)
virtual int ReportError (const std::string Message, int ErrorCode) const
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object (const Epetra_Object &Object)
virtual void SetLabel (const char *const Label)
virtual const char * Label () const
I/O methods
bool Transpose_
bool Factored_
bool EstimateSolutionErrors_
bool SolutionErrorsEstimated_
bool Solved_
bool Inverted_
bool ReciprocalConditionEstimated_
bool RefineSolution_
bool SolutionRefined_
char TRANS_
int N_
int Min_MN_
int NRHS_
int LDA_
int LDAF_
int LDB_
int LDX_
int INFO_
int LWORK_
int * IPIV_
int * IWORK_
double ANORM_
double RCOND_
double ROWCND_
double COLCND_
double AMAX_
Ifpack_SerialTriDiMatrix * Matrix_
Epetra_SerialDenseMatrix * LHS_
Epetra_SerialDenseMatrix * RHS_
Ifpack_SerialTriDiMatrix * Factor_
double * A_
double * FERR_
double * BERR_
double * AF_
double * WORK_
double * B_
double * X_
virtual void Print (std::ostream &os) const
Print service methods; defines behavior of ostream << operator.
void AllocateWORK ()
void AllocateIWORK ()
void InitPointers ()
void DeleteArrays ()
void ResetMatrix ()
void ResetVectors ()
Additional Inherited Members
Static Public Member Functions inherited from Epetra_Object
static void SetTracebackMode (int TracebackModeValue)
static int GetTracebackMode ()
static std::ostream & GetTracebackStream ()
Detailed Description
Ifpack_SerialTriDiSolver: A class for solving TriDi linear problems.
The Ifpack_SerialTriDiSolver class enables the definition, in terms of Ifpack_SerialTriDiMatrix and Ifpack_SerialTriDiVector objects, of a TriDi linear problem, followed by the solution of that problem via the most sophisticated techniques available in LAPACK.
The Ifpack_SerialTriDiSolver class is intended to provide full-featured support for solving linear problems for general TriDi rectangular (or square) matrices. It is written on top of BLAS and LAPACK and thus has excellent performance and numerical capabilities. Using this class, one can either perform simple factorizations and solves or apply all the tricks available in LAPACK to get the best possible solution for very ill-conditioned problems.
Ifpack_SerialTriDiSolver vs. Epetra_LAPACK
The Epetra_LAPACK class provides access to most of the same functionality as Ifpack_SerialTriDiSolver. The primary difference is that Epetra_LAPACK is a "thin" layer on top of LAPACK and Ifpack_SerialTriDiSolver attempts to provide easy access to the more sophisticated aspects of solving TriDi linear and eigensystems.
When you should use Epetra_LAPACK: If you are simply looking for a convenient wrapper around the Fortran LAPACK routines and you have a well-conditioned problem, you should probably use Epetra_LAPACK directly.
When you should use Ifpack_SerialTriDiSolver: If you want to (or potentially want to) solve ill-conditioned problems or want to work with a more object-oriented interface, you should probably use Ifpack_SerialTriDiSolver.
Constructing Ifpack_SerialTriDiSolver Objects
There is a single Ifpack_SerialTriDiSolver constructor. However, the matrix, right hand side and solution vectors must be set prior to executing most methods in this class.
Setting vectors used for linear solves
The matrix A, the left hand side X and the right hand side B (when solving AX = B, for X), can be set by appropriate set methods. Each of these three objects must be an Ifpack_SerialTriDiMatrix or and Epetra_SerialDenseVector object. The set methods are as follows:
SetMatrix() - Sets the matrix.
SetVectors() - Sets the left and right hand side vector(s).
Vector and Utility Functions
Once a Ifpack_SerialTriDiSolver is constructed, several mathematical functions can be applied to the object. Specifically:
Factorizations.
Solves.
Condition estimates.
Equilibration.
Norms.
Counting floating point operations The Ifpack_SerialTriDiSolver class has Epetra_CompObject as a base class. Thus, floating point operations are counted and accumulated in the Epetra_Flop object (if any) that was set using the SetFlopCounter() method in the Epetra_CompObject base class.
Strategies for Solving Linear Systems In many cases, linear systems can be accurately solved by simply computing the LU factorization of the matrix and then performing a forward back solve with a given set of right hand side vectors. However, in some instances, the factorization may be very poorly conditioned and this simple approach may not work. In these situations, equilibration and iterative refinement may improve the accuracy, or prevent a breakdown in the factorization.
LAPACK does not provide an equilibration functionality for tridiagonal data structures.
Ifpack_SerialTriDiSolver will use iterative refinement after a forward/back solve if you call SolveToRefinedSolution(true). It will also compute forward and backward error estimates if you call EstimateSolutionErrors(true). Access to the forward (back) error estimates is available via FERR() (BERR()).
Examples using Ifpack_SerialTriDiSolver can be found in the Epetra test directories.
Definition at line 136 of file Ifpack_SerialTriDiSolver.h.
Constructor & Destructor Documentation
Ifpack_SerialTriDiSolver()
Ifpack_SerialTriDiSolver::Ifpack_SerialTriDiSolver ()
Default constructor; matrix should be set using SetMatrix(), LHS and RHS set with SetVectors().
Definition at line 48 of file Ifpack_SerialTriDiSolver.cpp.
~Ifpack_SerialTriDiSolver()
Ifpack_SerialTriDiSolver::~Ifpack_SerialTriDiSolver () virtual
Ifpack_SerialTriDiSolver destructor.
Definition at line 93 of file Ifpack_SerialTriDiSolver.cpp.
Member Function Documentation
A()
double * Ifpack_SerialTriDiSolver::A () const inline
Returns pointer to the this matrix.
Definition at line 273 of file Ifpack_SerialTriDiSolver.h.
AF()
double * Ifpack_SerialTriDiSolver::AF () const inline
Returns pointer to the factored matrix (may be the same as A() if factorization done in place).
Definition at line 294 of file Ifpack_SerialTriDiSolver.h.
AllocateIWORK()
void Ifpack_SerialTriDiSolver::AllocateIWORK () inline protected
Definition at line 337 of file Ifpack_SerialTriDiSolver.h.
AllocateWORK()
void Ifpack_SerialTriDiSolver::AllocateWORK () inline protected
Definition at line 336 of file Ifpack_SerialTriDiSolver.h.
AMAX()
double Ifpack_SerialTriDiSolver::AMAX () const inline
Returns the absolute value of the largest entry of the this matrix (returns -1 if not yet computed).
Definition at line 319 of file Ifpack_SerialTriDiSolver.h.
ANORM()
double Ifpack_SerialTriDiSolver::ANORM () const inline
Returns the 1-Norm of the this matrix (returns -1 if not yet computed).
Definition at line 303 of file Ifpack_SerialTriDiSolver.h.
ApplyRefinement()
int Ifpack_SerialTriDiSolver::ApplyRefinement (void) virtual
Apply Iterative Refinement.
Returns
Integer error code, set to 0 if successful. Otherwise returns the LAPACK error code INFO.
Definition at line 295 of file Ifpack_SerialTriDiSolver.cpp.
Referenced by Solve().
B()
double * Ifpack_SerialTriDiSolver::B () const inline
Returns pointer to current RHS.
Definition at line 279 of file Ifpack_SerialTriDiSolver.h.
BERR()
double * Ifpack_SerialTriDiSolver::BERR () const inline
Returns a pointer to the backward error estimates computed by LAPACK.
Definition at line 325 of file Ifpack_SerialTriDiSolver.h.
COLCND()
double Ifpack_SerialTriDiSolver::COLCND () const inline
Ratio of smallest to largest column scale factors for the this matrix (returns -1 if not yet computed).
If COLCND() is >= 0.1 then equilibration is not needed.
Definition at line 316 of file Ifpack_SerialTriDiSolver.h.
DeleteArrays()
void Ifpack_SerialTriDiSolver::DeleteArrays () protected
Definition at line 112 of file Ifpack_SerialTriDiSolver.cpp.
EstimateSolutionErrors()
void Ifpack_SerialTriDiSolver::EstimateSolutionErrors (bool Flag)
Causes all solves to estimate the forward and backward solution error.
Error estimates will be in the arrays FERR and BERR, resp, after the solve step is complete. These arrays are accessible via the FERR() and BERR() access functions.
Definition at line 192 of file Ifpack_SerialTriDiSolver.cpp.
Factor()
int Ifpack_SerialTriDiSolver::Factor (void) virtual
Computes the in-place LU factorization of the matrix using the LAPACK routine DGETRF.
Returns
Integer error code, set to 0 if successful.
Definition at line 199 of file Ifpack_SerialTriDiSolver.cpp.
References Ifpack_SerialTriDiMatrix::A(), Ifpack_SerialTriDiMatrix::DL(), Factored(), Inverted(), Ifpack_SerialTriDiMatrix::OneNorm(), and Epetra_CompObject::UpdateFlops().
Referenced by Ifpack_TriDiContainer::Compute(), Invert(), ReciprocalConditionEstimate(), and Solve().
Factored()
bool Ifpack_SerialTriDiSolver::Factored () inline
Returns true if matrix is factored (factor available via AF() and LDAF()).
Definition at line 236 of file Ifpack_SerialTriDiSolver.h.
Referenced by Factor(), Invert(), ReciprocalConditionEstimate(), and Solve().
FactoredMatrix()
Ifpack_SerialTriDiMatrix * Ifpack_SerialTriDiSolver::FactoredMatrix () const inline
Returns pointer to factored matrix (assuming factorization has been performed).
Definition at line 261 of file Ifpack_SerialTriDiSolver.h.
FERR()
double * Ifpack_SerialTriDiSolver::FERR () const inline
Returns a pointer to the forward error estimates computed by LAPACK.
Definition at line 322 of file Ifpack_SerialTriDiSolver.h.
InitPointers()
void Ifpack_SerialTriDiSolver::InitPointers () protected
Definition at line 98 of file Ifpack_SerialTriDiSolver.cpp.
Invert()
int Ifpack_SerialTriDiSolver::Invert (void) virtual
Inverts the this matrix.
Returns
Integer error code, set to 0 if successful. Otherwise returns the LAPACK error code INFO.
Definition at line 303 of file Ifpack_SerialTriDiSolver.cpp.
References Factor(), Factored(), and Epetra_CompObject::UpdateFlops().
Inverted()
bool Ifpack_SerialTriDiSolver::Inverted () inline
Returns true if matrix inverse has been computed (inverse available via AF() and LDAF()).
Definition at line 242 of file Ifpack_SerialTriDiSolver.h.
Referenced by Factor(), and Solve().
IPIV()
int * Ifpack_SerialTriDiSolver::IPIV () const inline
Returns pointer to pivot vector (if factorization has been computed), zero otherwise.
Definition at line 300 of file Ifpack_SerialTriDiSolver.h.
LDA()
int Ifpack_SerialTriDiSolver::LDA () const inline
Returns the leading dimension of the this matrix.
Definition at line 276 of file Ifpack_SerialTriDiSolver.h.
LDAF()
int Ifpack_SerialTriDiSolver::LDAF () const inline
Returns the leading dimension of the factored matrix.
Definition at line 297 of file Ifpack_SerialTriDiSolver.h.
LDB()
int Ifpack_SerialTriDiSolver::LDB () const inline
Returns the leading dimension of the RHS.
Definition at line 282 of file Ifpack_SerialTriDiSolver.h.
LDX()
int Ifpack_SerialTriDiSolver::LDX () const inline
Returns the leading dimension of the solution.
Definition at line 291 of file Ifpack_SerialTriDiSolver.h.
LHS()
Epetra_SerialDenseMatrix * Ifpack_SerialTriDiSolver::LHS () const inline
Returns pointer to current LHS.
Definition at line 264 of file Ifpack_SerialTriDiSolver.h.
Matrix()
Ifpack_SerialTriDiMatrix * Ifpack_SerialTriDiSolver::Matrix () const inline
Returns pointer to current matrix.
Definition at line 258 of file Ifpack_SerialTriDiSolver.h.
N()
int Ifpack_SerialTriDiSolver::N () const inline
Returns column dimension of system.
Definition at line 270 of file Ifpack_SerialTriDiSolver.h.
NRHS()
int Ifpack_SerialTriDiSolver::NRHS () const inline
Returns the number of current right hand sides and solution vectors.
Definition at line 285 of file Ifpack_SerialTriDiSolver.h.
Print()
void Ifpack_SerialTriDiSolver::Print (std::ostream & os) const virtual
Print service methods; defines behavior of ostream << operator.
Reimplemented from Epetra_Object.
Definition at line 345 of file Ifpack_SerialTriDiSolver.cpp.
RCOND()
double Ifpack_SerialTriDiSolver::RCOND () const inline
Returns the reciprocal of the condition number of the this matrix (returns -1 if not yet computed).
Definition at line 306 of file Ifpack_SerialTriDiSolver.h.
ReciprocalConditionEstimate()
int Ifpack_SerialTriDiSolver::ReciprocalConditionEstimate (double & Value) virtual
Unscales the solution vectors if equilibration was used to solve the system.
Returns
Integer error code, set to 0 if successful. Otherwise returns the LAPACK error code INFO. Returns the reciprocal of the 1-norm condition number of the this matrix.
Parameters
Value Out On return contains the reciprocal of the 1-norm condition number of the this matrix.
Returns
Integer error code, set to 0 if successful. Otherwise returns the LAPACK error code INFO.
Definition at line 322 of file Ifpack_SerialTriDiSolver.cpp.
References Factor(), Factored(), Ifpack_SerialTriDiMatrix::OneNorm(), ReciprocalConditionEstimated(), and Epetra_CompObject::UpdateFlops().
ReciprocalConditionEstimated()
bool Ifpack_SerialTriDiSolver::ReciprocalConditionEstimated () inline
Returns true if the condition number of the this matrix has been computed (value available via ReciprocalConditionEstimate()).
Definition at line 245 of file Ifpack_SerialTriDiSolver.h.
Referenced by ReciprocalConditionEstimate().
ResetMatrix()
void Ifpack_SerialTriDiSolver::ResetMatrix () protected
Definition at line 129 of file Ifpack_SerialTriDiSolver.cpp.
ResetVectors()
void Ifpack_SerialTriDiSolver::ResetVectors () protected
Definition at line 161 of file Ifpack_SerialTriDiSolver.cpp.
RHS()
Epetra_SerialDenseMatrix * Ifpack_SerialTriDiSolver::RHS () const inline
Returns pointer to current RHS.
Definition at line 267 of file Ifpack_SerialTriDiSolver.h.
ROWCND()
double Ifpack_SerialTriDiSolver::ROWCND () const inline
Ratio of smallest to largest row scale factors for the this matrix (returns -1 if not yet computed).
If ROWCND() is >= 0.1 and AMAX() is not close to overflow or underflow, then equilibration is not needed.
Definition at line 311 of file Ifpack_SerialTriDiSolver.h.
SetMatrix()
int Ifpack_SerialTriDiSolver::SetMatrix (Ifpack_SerialTriDiMatrix & A)
Sets the pointers for coefficient matrix.
Definition at line 149 of file Ifpack_SerialTriDiSolver.cpp.
References Ifpack_SerialTriDiMatrix::A(), and Ifpack_SerialTriDiMatrix::N().
Referenced by Ifpack_TriDiContainer::Initialize().
SetVectors()
int Ifpack_SerialTriDiSolver::SetVectors (Epetra_SerialDenseMatrix & X, Epetra_SerialDenseMatrix & B)
Sets the pointers for left and right hand side vector(s).
Row dimension of X must match column dimension of matrix A, row dimension of B must match row dimension of A. X and B must have the same dimensions.
Definition at line 176 of file Ifpack_SerialTriDiSolver.cpp.
References Epetra_SerialDenseMatrix::A(), and Epetra_SerialDenseMatrix::N().
Referenced by Ifpack_TriDiContainer::Initialize(), and Ifpack_TriDiContainer::SetNumVectors().
SolutionErrorsEstimated()
bool Ifpack_SerialTriDiSolver::SolutionErrorsEstimated () inline
Returns true if forward and backward error estimated have been computed (available via FERR() and BERR()).
Definition at line 239 of file Ifpack_SerialTriDiSolver.h.
SolutionRefined()
bool Ifpack_SerialTriDiSolver::SolutionRefined () inline
Returns true if the current set of vectors has been refined.
Definition at line 251 of file Ifpack_SerialTriDiSolver.h.
Solve()
int Ifpack_SerialTriDiSolver::Solve (void) virtual
Computes the solution X to AX = B for the this matrix and the B provided to SetVectors()..
Returns
Integer error code, set to 0 if successful.
Definition at line 237 of file Ifpack_SerialTriDiSolver.cpp.
References Epetra_SerialDenseMatrix::A(), ApplyRefinement(), Ifpack_SerialTriDiMatrix::DL(), Factor(), Factored(), Inverted(), and Epetra_CompObject::UpdateFlops().
Referenced by Ifpack_TriDiContainer::ApplyInverse().
Solved()
bool Ifpack_SerialTriDiSolver::Solved () inline
Returns true if the current set of vectors has been solved.
Definition at line 248 of file Ifpack_SerialTriDiSolver.h.
SolveToRefinedSolution()
void Ifpack_SerialTriDiSolver::SolveToRefinedSolution (bool Flag) inline
Causes all solves to compute solution to best ability using iterative refinement.
Definition at line 177 of file Ifpack_SerialTriDiSolver.h.
SolveWithTranspose()
void Ifpack_SerialTriDiSolver::SolveWithTranspose (bool Flag) inline
Causes equilibration to be called just before the matrix factorization as part of the call to Factor.
This function must be called before the factorization is performed. If Flag is true, causes all subsequent function calls to work with the transpose of this matrix, otherwise not.
Definition at line 174 of file Ifpack_SerialTriDiSolver.h.
Transpose()
bool Ifpack_SerialTriDiSolver::Transpose () inline
Returns true if transpose of this matrix has and will be used.
Definition at line 233 of file Ifpack_SerialTriDiSolver.h.
X()
double * Ifpack_SerialTriDiSolver::X () const inline
Returns pointer to current solution.
Definition at line 288 of file Ifpack_SerialTriDiSolver.h.
Member Data Documentation
A_
double* Ifpack_SerialTriDiSolver::A_ protected
Definition at line 379 of file Ifpack_SerialTriDiSolver.h.
AF_
double* Ifpack_SerialTriDiSolver::AF_ protected
Definition at line 382 of file Ifpack_SerialTriDiSolver.h.
AMAX_
double Ifpack_SerialTriDiSolver::AMAX_ protected
Definition at line 372 of file Ifpack_SerialTriDiSolver.h.
ANORM_
double Ifpack_SerialTriDiSolver::ANORM_ protected
Definition at line 368 of file Ifpack_SerialTriDiSolver.h.
B_
double* Ifpack_SerialTriDiSolver::B_ protected
Definition at line 385 of file Ifpack_SerialTriDiSolver.h.
BERR_
double* Ifpack_SerialTriDiSolver::BERR_ protected
Definition at line 381 of file Ifpack_SerialTriDiSolver.h.
COLCND_
double Ifpack_SerialTriDiSolver::COLCND_ protected
Definition at line 371 of file Ifpack_SerialTriDiSolver.h.
EstimateSolutionErrors_
bool Ifpack_SerialTriDiSolver::EstimateSolutionErrors_ protected
Definition at line 345 of file Ifpack_SerialTriDiSolver.h.
Factor_
Ifpack_SerialTriDiMatrix* Ifpack_SerialTriDiSolver::Factor_ protected
Definition at line 377 of file Ifpack_SerialTriDiSolver.h.
Factored_
bool Ifpack_SerialTriDiSolver::Factored_ protected
Definition at line 344 of file Ifpack_SerialTriDiSolver.h.
FERR_
double* Ifpack_SerialTriDiSolver::FERR_ protected
Definition at line 380 of file Ifpack_SerialTriDiSolver.h.
INFO_
int Ifpack_SerialTriDiSolver::INFO_ protected
Definition at line 362 of file Ifpack_SerialTriDiSolver.h.
Inverted_
bool Ifpack_SerialTriDiSolver::Inverted_ protected
Definition at line 348 of file Ifpack_SerialTriDiSolver.h.
IPIV_
int* Ifpack_SerialTriDiSolver::IPIV_ protected
Definition at line 365 of file Ifpack_SerialTriDiSolver.h.
IWORK_
int* Ifpack_SerialTriDiSolver::IWORK_ protected
Definition at line 366 of file Ifpack_SerialTriDiSolver.h.
LDA_
int Ifpack_SerialTriDiSolver::LDA_ protected
Definition at line 358 of file Ifpack_SerialTriDiSolver.h.
LDAF_
int Ifpack_SerialTriDiSolver::LDAF_ protected
Definition at line 359 of file Ifpack_SerialTriDiSolver.h.
LDB_
int Ifpack_SerialTriDiSolver::LDB_ protected
Definition at line 360 of file Ifpack_SerialTriDiSolver.h.
LDX_
int Ifpack_SerialTriDiSolver::LDX_ protected
Definition at line 361 of file Ifpack_SerialTriDiSolver.h.
LHS_
Epetra_SerialDenseMatrix* Ifpack_SerialTriDiSolver::LHS_ protected
Definition at line 375 of file Ifpack_SerialTriDiSolver.h.
LWORK_
int Ifpack_SerialTriDiSolver::LWORK_ protected
Definition at line 363 of file Ifpack_SerialTriDiSolver.h.
Matrix_
Ifpack_SerialTriDiMatrix* Ifpack_SerialTriDiSolver::Matrix_ protected
Definition at line 374 of file Ifpack_SerialTriDiSolver.h.
Min_MN_
int Ifpack_SerialTriDiSolver::Min_MN_ protected
Definition at line 356 of file Ifpack_SerialTriDiSolver.h.
N_
int Ifpack_SerialTriDiSolver::N_ protected
Definition at line 355 of file Ifpack_SerialTriDiSolver.h.
NRHS_
int Ifpack_SerialTriDiSolver::NRHS_ protected
Definition at line 357 of file Ifpack_SerialTriDiSolver.h.
RCOND_
double Ifpack_SerialTriDiSolver::RCOND_ protected
Definition at line 369 of file Ifpack_SerialTriDiSolver.h.
ReciprocalConditionEstimated_
bool Ifpack_SerialTriDiSolver::ReciprocalConditionEstimated_ protected
Definition at line 349 of file Ifpack_SerialTriDiSolver.h.
RefineSolution_
bool Ifpack_SerialTriDiSolver::RefineSolution_ protected
Definition at line 350 of file Ifpack_SerialTriDiSolver.h.
RHS_
Epetra_SerialDenseMatrix* Ifpack_SerialTriDiSolver::RHS_ protected
Definition at line 376 of file Ifpack_SerialTriDiSolver.h.
ROWCND_
double Ifpack_SerialTriDiSolver::ROWCND_ protected
Definition at line 370 of file Ifpack_SerialTriDiSolver.h.
SolutionErrorsEstimated_
bool Ifpack_SerialTriDiSolver::SolutionErrorsEstimated_ protected
Definition at line 346 of file Ifpack_SerialTriDiSolver.h.
SolutionRefined_
bool Ifpack_SerialTriDiSolver::SolutionRefined_ protected
Definition at line 351 of file Ifpack_SerialTriDiSolver.h.
Solved_
bool Ifpack_SerialTriDiSolver::Solved_ protected
Definition at line 347 of file Ifpack_SerialTriDiSolver.h.
TRANS_
char Ifpack_SerialTriDiSolver::TRANS_ protected
Definition at line 353 of file Ifpack_SerialTriDiSolver.h.
Transpose_
bool Ifpack_SerialTriDiSolver::Transpose_ protected
Definition at line 343 of file Ifpack_SerialTriDiSolver.h.
WORK_
double* Ifpack_SerialTriDiSolver::WORK_ protected
Definition at line 383 of file Ifpack_SerialTriDiSolver.h.
X_
double* Ifpack_SerialTriDiSolver::X_ protected
Definition at line 386 of file Ifpack_SerialTriDiSolver.h.
The documentation for this class was generated from the following files:
Ifpack_SerialTriDiSolver.h
Ifpack_SerialTriDiSolver.cpp