IFPACK: Ifpack_AMDReordering Class Reference
Ifpack_AMDReordering Class Reference
Ifpack_AMDReordering: approximate minimum degree reordering.
#include <Ifpack_AMDReordering.h>
Public Member Functions
Ifpack_AMDReordering ()
Constructor for Ifpack_Graph's.
Ifpack_AMDReordering (const Ifpack_AMDReordering &RHS)
Copy Constructor.
Ifpack_AMDReordering & operator= (const Ifpack_AMDReordering &RHS)
Assignment operator.
virtual ~Ifpack_AMDReordering ()
Destructor.
int SetParameter (const std::string Name, const int Value)
Sets integer parameters ‘Name’.
int SetParameter (const std::string Name, const double Value)
Sets double parameters ‘Name’.
int SetParameters (Teuchos::ParameterList &List)
Sets all parameters.
int Compute (const Ifpack_Graph &Graph)
Computes all it is necessary to initialize the reordering object.
int Compute (const Epetra_RowMatrix &Matrix)
Computes all it is necessary to initialize the reordering object.
bool IsComputed () const
Returns true is the reordering object has been successfully initialized, false otherwise.
int Reorder (const int i) const
Returns the reordered index of row i.
int InvReorder (const int i) const
Returns the inverse reordered index of row i.
int P (const Epetra_MultiVector &Xorig, Epetra_MultiVector &Xreord) const
Applies reordering to multivector X, whose local length equals the number of local rows.
int Pinv (const Epetra_MultiVector &Xorig, Epetra_MultiVector &Xinvreord) const
Applies inverse reordering to multivector X, whose local length equals the number of local rows.
std::ostream & Print (std::ostream &os) const
Prints basic information on iostream. This function is used by operator<<.
int NumMyRows () const
Returns the number of local rows.
Public Member Functions inherited from Ifpack_Reordering
virtual ~Ifpack_Reordering ()
Destructor.
Detailed Description
Ifpack_AMDReordering: approximate minimum degree reordering.
Definition at line 64 of file Ifpack_AMDReordering.h.
Constructor & Destructor Documentation
Ifpack_AMDReordering() [1/2]
Ifpack_AMDReordering::Ifpack_AMDReordering ()
Constructor for Ifpack_Graph's.
Definition at line 57 of file Ifpack_AMDReordering.cpp.
Ifpack_AMDReordering() [2/2]
Ifpack_AMDReordering::Ifpack_AMDReordering (const Ifpack_AMDReordering & RHS)
Copy Constructor.
Definition at line 65 of file Ifpack_AMDReordering.cpp.
References NumMyRows().
~Ifpack_AMDReordering()
virtual Ifpack_AMDReordering::~Ifpack_AMDReordering () inline virtual
Destructor.
Definition at line 78 of file Ifpack_AMDReordering.h.
Member Function Documentation
Compute() [1/2]
int Ifpack_AMDReordering::Compute (const Epetra_RowMatrix & Matrix) virtual
Computes all it is necessary to initialize the reordering object.
Implements Ifpack_Reordering.
Definition at line 122 of file Ifpack_AMDReordering.cpp.
References Compute().
Compute() [2/2]
int Ifpack_AMDReordering::Compute (const Ifpack_Graph & Graph) virtual
Computes all it is necessary to initialize the reordering object.
Implements Ifpack_Reordering.
Definition at line 132 of file Ifpack_AMDReordering.cpp.
Referenced by Compute().
InvReorder()
int Ifpack_AMDReordering::InvReorder (const int i) const virtual
Returns the inverse reordered index of row i.
Implements Ifpack_Reordering.
Definition at line 213 of file Ifpack_AMDReordering.cpp.
References IsComputed().
IsComputed()
bool Ifpack_AMDReordering::IsComputed () const inline virtual
Returns true is the reordering object has been successfully initialized, false otherwise.
Implements Ifpack_Reordering.
Definition at line 96 of file Ifpack_AMDReordering.h.
Referenced by InvReorder(), operator=(), Print(), and Reorder().
NumMyRows()
int Ifpack_AMDReordering::NumMyRows () const inline
Returns the number of local rows.
Definition at line 120 of file Ifpack_AMDReordering.h.
Referenced by Ifpack_AMDReordering(), and operator=().
operator=()
Ifpack_AMDReordering & Ifpack_AMDReordering::operator= (const Ifpack_AMDReordering & RHS)
Assignment operator.
Definition at line 79 of file Ifpack_AMDReordering.cpp.
References IsComputed(), and NumMyRows().
P()
int Ifpack_AMDReordering::P (const Epetra_MultiVector & Xorig, Epetra_MultiVector & Xreord) const virtual
Applies reordering to multivector X, whose local length equals the number of local rows.
Implements Ifpack_Reordering.
Definition at line 225 of file Ifpack_AMDReordering.cpp.
References Epetra_MultiVector::NumVectors().
Pinv()
int Ifpack_AMDReordering::Pinv (const Epetra_MultiVector & Xorig, Epetra_MultiVector & Xinvreord) const virtual
Applies inverse reordering to multivector X, whose local length equals the number of local rows.
Implements Ifpack_Reordering.
Definition at line 241 of file Ifpack_AMDReordering.cpp.
References Epetra_MultiVector::NumVectors().
Print()
std::ostream & Ifpack_AMDReordering::Print (std::ostream & os) const virtual
Prints basic information on iostream. This function is used by operator<<.
Implements Ifpack_Reordering.
Definition at line 257 of file Ifpack_AMDReordering.cpp.
References IsComputed().
Reorder()
int Ifpack_AMDReordering::Reorder (const int i) const virtual
Returns the reordered index of row i.
Implements Ifpack_Reordering.
Definition at line 200 of file Ifpack_AMDReordering.cpp.
References IsComputed().
SetParameter() [1/2]
int Ifpack_AMDReordering::SetParameter (const std::string Name, const double Value) virtual
Sets double parameters ‘Name’.
Implements Ifpack_Reordering.
Definition at line 108 of file Ifpack_AMDReordering.cpp.
SetParameter() [2/2]
int Ifpack_AMDReordering::SetParameter (const std::string Name, const int Value) virtual
Sets integer parameters ‘Name’.
Implements Ifpack_Reordering.
Definition at line 101 of file Ifpack_AMDReordering.cpp.
SetParameters()
int Ifpack_AMDReordering::SetParameters (Teuchos::ParameterList & List) virtual
Sets all parameters.
Implements Ifpack_Reordering.
Definition at line 115 of file Ifpack_AMDReordering.cpp.
The documentation for this class was generated from the following files:
Ifpack_AMDReordering.h
Ifpack_AMDReordering.cpp