IFPACK: Ifpack_IC Class Reference
Ifpack_IC Class Reference
Ifpack_IC: A class for constructing and using an incomplete Cholesky factorization of a given Epetra_RowMatrix.
#include <Ifpack_IC.h>
Public Member Functions
Ifpack_IC (Epetra_RowMatrix *A)
Ifpack_IC constuctor with variable number of indices per row.
virtual ~Ifpack_IC ()
Ifpack_IC Destructor.
void SetAbsoluteThreshold (double Athresh)
Set absolute threshold value.
void SetRelativeThreshold (double Rthresh)
Set relative threshold value.
int SetParameters (Teuchos::ParameterList &parameterlis)
Set parameters using a Teuchos::ParameterList object.
int SetParameter (const std::string, const int)
int SetParameter (const std::string, const double)
const Epetra_RowMatrix & Matrix () const
Returns a pointer to the matrix to be preconditioned.
Epetra_RowMatrix & Matrix ()
bool IsInitialized () const
Returns true if the preconditioner has been successfully initialized, false otherwise.
int Initialize ()
Initialize L and U with values from user matrix A.
int Compute ()
Compute IC factor U using the specified graph, diagonal perturbation thresholds and relaxation parameters.
int ComputeSetup ()
bool IsComputed () const
If factor is completed, this query returns true, otherwise it returns false.
int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Ifpack_IC forward/back solve on a Epetra_MultiVector X in Y.
int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
double Condest (const Ifpack_CondestType CT=Ifpack_Cheap, const int MaxIters=1550, const double Tol=1e-9, Epetra_RowMatrix *Matrix_in=0)
Returns the maximum over all the condition number estimate for each local ILU set of factors.
double Condest () const
Returns the computed condition number estimate, or -1.0 if not computed.
double GetAbsoluteThreshold ()
Get absolute threshold value.
double GetRelativeThreshold ()
Get relative threshold value.
int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global graph.
long long NumGlobalNonzeros64 () const
int NumMyNonzeros () const
Returns the number of nonzero entries in the local graph.
const Epetra_Vector & D () const
Returns the address of the D factor associated with this factored matrix.
const Epetra_CrsMatrix & U () const
Returns the address of the U factor associated with this factored matrix.
int SetUseTranspose (bool UseTranspose_in)
If set true, transpose of this operator will be applied.
double NormInf () const
Returns 0.0 because this class cannot compute Inf-norm.
bool HasNormInf () const
Returns false because this class cannot compute an Inf-norm.
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
const Epetra_Comm & Comm () const
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
const char * Label () const
int SetLabel (const char *Label_in)
virtual std::ostream & Print (std::ostream &os) const
Prints basic information on iostream. This function is used by operator<<.
virtual int NumInitialize () const
Returns the number of calls to Initialize().
virtual int NumCompute () const
Returns the number of calls to Compute().
virtual int NumApplyInverse () const
Returns the number of calls to ApplyInverse().
virtual double InitializeTime () const
Returns the time spent in Initialize().
virtual double ComputeTime () const
Returns the time spent in Compute().
virtual double ApplyInverseTime () const
Returns the time spent in ApplyInverse().
virtual double InitializeFlops () const
Returns the number of flops in the initialization phase.
virtual double ComputeFlops () const
Returns the number of flops in the computation phase.
virtual double ApplyInverseFlops () const
Returns the number of flops in the application of the preconditioner.
Detailed Description
Ifpack_IC: A class for constructing and using an incomplete Cholesky factorization of a given Epetra_RowMatrix.
The Ifpack_IC class computes a threshold (not level) based incomplete LDL^T factorization of a given Epetra_RowMatrix. The factorization that is produced is a function of several parameters:
Level of fill ratio. This defines the maximum number of entries per row/column in the factor, relative to the average number of nonzeros per row/col in A. The default value of 1.0 keeps the IC factor as sparse as A.
Diagonal perturbation - Prior to computing the factorization, it is possible to modify the diagonal entries of the matrix for which the factorization will be computing. If the absolute and relative perturbation values are zero and one, respectively, the factorization will be compute for the original user matrix A. Otherwise, the factorization will computed for a matrix that differs from the original user matrix in the diagonal values only. Details can be found in ifp_diag_pert.
Definition at line 86 of file Ifpack_IC.h.
Constructor & Destructor Documentation
Ifpack_IC()
Ifpack_IC::Ifpack_IC (Epetra_RowMatrix * A)
Ifpack_IC constuctor with variable number of indices per row.
Creates a Ifpack_IC object and allocates storage.
Parameters
In A - User matrix to be factored.
In Graph - Graph generated by Ifpack_IlukGraph.
Definition at line 61 of file Ifpack_IC.cpp.
References SetParameters().
~Ifpack_IC()
Ifpack_IC::~Ifpack_IC () virtual
Ifpack_IC Destructor.
Definition at line 90 of file Ifpack_IC.cpp.
Member Function Documentation
Apply()
int Ifpack_IC::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Implements Epetra_Operator.
Definition at line 350 of file Ifpack_IC.cpp.
ApplyInverse()
int Ifpack_IC::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Ifpack_IC forward/back solve on a Epetra_MultiVector X in Y.
Parameters
In Trans -If true, solve transpose problem.
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
Implements Ifpack_Preconditioner.
Definition at line 309 of file Ifpack_IC.cpp.
References Epetra_Time::ElapsedTime(), IsComputed(), Epetra_MultiVector::Multiply(), Epetra_MultiVector::NumVectors(), Epetra_MultiVector::Pointers(), and Epetra_Time::ResetStartTime().
ApplyInverseFlops()
virtual double Ifpack_IC::ApplyInverseFlops () const inline virtual
Returns the number of flops in the application of the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 318 of file Ifpack_IC.h.
Referenced by Print().
ApplyInverseTime()
virtual double Ifpack_IC::ApplyInverseTime () const inline virtual
Returns the time spent in ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 302 of file Ifpack_IC.h.
Referenced by Print().
Comm()
const Epetra_Comm & Ifpack_IC::Comm () const inline virtual
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Implements Epetra_Operator.
Definition at line 254 of file Ifpack_IC.h.
Referenced by Print().
Compute()
int Ifpack_IC::Compute () virtual
Compute IC factor U using the specified graph, diagonal perturbation thresholds and relaxation parameters.
This function computes the RILU(k) factors L and U using the current:
Ifpack_IlukGraph specifying the structure of L and U.
Value for the RILU(k) relaxation parameter.
Value for the a priori diagonal threshold values.
InitValues() must be called before the factorization can proceed.
Implements Ifpack_Preconditioner.
Definition at line 214 of file Ifpack_IC.cpp.
References Epetra_Time::ElapsedTime(), Initialize(), IsInitialized(), Epetra_Time::ResetStartTime(), and View.
ComputeFlops()
virtual double Ifpack_IC::ComputeFlops () const inline virtual
Returns the number of flops in the computation phase.
Implements Ifpack_Preconditioner.
Definition at line 313 of file Ifpack_IC.h.
Referenced by Print().
ComputeSetup()
int Ifpack_IC::ComputeSetup ()
Definition at line 139 of file Ifpack_IC.cpp.
ComputeTime()
virtual double Ifpack_IC::ComputeTime () const inline virtual
Returns the time spent in Compute().
Implements Ifpack_Preconditioner.
Definition at line 296 of file Ifpack_IC.h.
Referenced by Print().
Condest() [1/2]
double Ifpack_IC::Condest () const inline virtual
Returns the computed condition number estimate, or -1.0 if not computed.
Implements Ifpack_Preconditioner.
Definition at line 197 of file Ifpack_IC.h.
Referenced by Print().
Condest() [2/2]
double Ifpack_IC::Condest (const Ifpack_CondestType CT = Ifpack_Cheap, const int MaxIters = 1550, const double Tol = 1e-9, Epetra_RowMatrix * Matrix_in = 0) virtual
Returns the maximum over all the condition number estimate for each local ILU set of factors.
This functions computes a local condition number estimate on each processor and return the maximum over all processor of the estimate.
Parameters
In Trans -If true, solve transpose problem.
Out ConditionNumberEstimate - The maximum across all processors of the infinity-norm estimate of the condition number of the inverse of LDU.
Implements Ifpack_Preconditioner.
Definition at line 370 of file Ifpack_IC.cpp.
References IsComputed().
D()
const Epetra_Vector & Ifpack_IC::D () const inline
Returns the address of the D factor associated with this factored matrix.
Definition at line 219 of file Ifpack_IC.h.
Referenced by NumGlobalNonzeros(), and NumMyNonzeros().
GetAbsoluteThreshold()
double Ifpack_IC::GetAbsoluteThreshold () inline
Get absolute threshold value.
Definition at line 205 of file Ifpack_IC.h.
GetRelativeThreshold()
double Ifpack_IC::GetRelativeThreshold () inline
Get relative threshold value.
Definition at line 208 of file Ifpack_IC.h.
HasNormInf()
bool Ifpack_IC::HasNormInf () const inline virtual
Returns false because this class cannot compute an Inf-norm.
Implements Epetra_Operator.
Definition at line 242 of file Ifpack_IC.h.
Initialize()
int Ifpack_IC::Initialize () virtual
Initialize L and U with values from user matrix A.
Copies values from the user's matrix into the nonzero pattern of L and U.
Parameters
In A - User matrix to be factored.
Warning
The graph of A must be identical to the graph passed in to Ifpack_IlukGraph constructor.
Implements Ifpack_Preconditioner.
Definition at line 126 of file Ifpack_IC.cpp.
Referenced by Compute().
InitializeFlops()
virtual double Ifpack_IC::InitializeFlops () const inline virtual
Returns the number of flops in the initialization phase.
Implements Ifpack_Preconditioner.
Definition at line 308 of file Ifpack_IC.h.
InitializeTime()
virtual double Ifpack_IC::InitializeTime () const inline virtual
Returns the time spent in Initialize().
Implements Ifpack_Preconditioner.
Definition at line 290 of file Ifpack_IC.h.
Referenced by Print().
IsComputed()
bool Ifpack_IC::IsComputed () const inline virtual
If factor is completed, this query returns true, otherwise it returns false.
Implements Ifpack_Preconditioner.
Definition at line 164 of file Ifpack_IC.h.
Referenced by ApplyInverse(), and Condest().
IsInitialized()
bool Ifpack_IC::IsInitialized () const inline virtual
Returns true if the preconditioner has been successfully initialized, false otherwise.
Implements Ifpack_Preconditioner.
Definition at line 137 of file Ifpack_IC.h.
Referenced by Compute().
Label()
const char * Ifpack_IC::Label () const inline virtual
Implements Epetra_Operator.
Definition at line 257 of file Ifpack_IC.h.
Matrix() [1/2]
Epetra_RowMatrix & Ifpack_IC::Matrix () inline
Definition at line 132 of file Ifpack_IC.h.
Matrix() [2/2]
const Epetra_RowMatrix & Ifpack_IC::Matrix () const inline virtual
Returns a pointer to the matrix to be preconditioned.
Implements Ifpack_Preconditioner.
Definition at line 127 of file Ifpack_IC.h.
NormInf()
double Ifpack_IC::NormInf () const inline virtual
Returns 0.0 because this class cannot compute Inf-norm.
Implements Epetra_Operator.
Definition at line 239 of file Ifpack_IC.h.
NumApplyInverse()
virtual int Ifpack_IC::NumApplyInverse () const inline virtual
Returns the number of calls to ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 284 of file Ifpack_IC.h.
Referenced by Print().
NumCompute()
virtual int Ifpack_IC::NumCompute () const inline virtual
Returns the number of calls to Compute().
Implements Ifpack_Preconditioner.
Definition at line 278 of file Ifpack_IC.h.
Referenced by Print().
NumGlobalNonzeros()
int Ifpack_IC::NumGlobalNonzeros () const inline
Returns the number of nonzero entries in the global graph.
Definition at line 212 of file Ifpack_IC.h.
References D(), NumGlobalNonzeros(), and U().
Referenced by NumGlobalNonzeros().
NumGlobalNonzeros64()
long long Ifpack_IC::NumGlobalNonzeros64 () const inline
Definition at line 214 of file Ifpack_IC.h.
NumInitialize()
virtual int Ifpack_IC::NumInitialize () const inline virtual
Returns the number of calls to Initialize().
Implements Ifpack_Preconditioner.
Definition at line 272 of file Ifpack_IC.h.
Referenced by Print().
NumMyNonzeros()
int Ifpack_IC::NumMyNonzeros () const inline
Returns the number of nonzero entries in the local graph.
Definition at line 217 of file Ifpack_IC.h.
References D(), NumMyNonzeros(), and U().
Referenced by NumMyNonzeros().
OperatorDomainMap()
const Epetra_Map & Ifpack_IC::OperatorDomainMap () const inline virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
Definition at line 248 of file Ifpack_IC.h.
OperatorRangeMap()
const Epetra_Map & Ifpack_IC::OperatorRangeMap () const inline virtual
Returns the Epetra_Map object associated with the range of this operator.
Implements Epetra_Operator.
Definition at line 251 of file Ifpack_IC.h.
Print()
std::ostream & Ifpack_IC::Print (std::ostream & os) const virtual
Prints basic information on iostream. This function is used by operator<<.
Implements Ifpack_Preconditioner.
Definition at line 385 of file Ifpack_IC.cpp.
References ApplyInverseFlops(), ApplyInverseTime(), Comm(), ComputeFlops(), ComputeTime(), Condest(), InitializeTime(), NumApplyInverse(), NumCompute(), and NumInitialize().
SetAbsoluteThreshold()
void Ifpack_IC::SetAbsoluteThreshold (double Athresh) inline
Set absolute threshold value.
Definition at line 103 of file Ifpack_IC.h.
SetLabel()
int Ifpack_IC::SetLabel (const char * Label_in) inline
Definition at line 262 of file Ifpack_IC.h.
SetParameter() [1/2]
int Ifpack_IC::SetParameter (const std::string , const double) inline
Definition at line 122 of file Ifpack_IC.h.
SetParameter() [2/2]
int Ifpack_IC::SetParameter (const std::string , const int) inline
Definition at line 118 of file Ifpack_IC.h.
SetParameters()
int Ifpack_IC::SetParameters (Teuchos::ParameterList & parameterlis) virtual
Set parameters using a Teuchos::ParameterList object.
Implements Ifpack_Preconditioner.
Definition at line 110 of file Ifpack_IC.cpp.
Referenced by Ifpack_IC().
SetRelativeThreshold()
void Ifpack_IC::SetRelativeThreshold (double Rthresh) inline
Set relative threshold value.
Definition at line 106 of file Ifpack_IC.h.
SetUseTranspose()
int Ifpack_IC::SetUseTranspose (bool UseTranspose_in) inline virtual
If set true, transpose of this operator will be applied.
This flag allows the transpose of the given operator to be used implicitly. Setting this flag affects only the Apply() and ApplyInverse() methods. If the implementation of this interface does not support transpose use, this method should return a value of -1.
Parameters
In UseTranspose_in -If true, multiply by the transpose of operator, otherwise just use operator.
Returns
Always returns 0.
Implements Epetra_Operator.
Definition at line 236 of file Ifpack_IC.h.
U()
const Epetra_CrsMatrix & Ifpack_IC::U () const inline
Returns the address of the U factor associated with this factored matrix.
Definition at line 222 of file Ifpack_IC.h.
Referenced by NumGlobalNonzeros(), and NumMyNonzeros().
UseTranspose()
bool Ifpack_IC::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Definition at line 245 of file Ifpack_IC.h.
The documentation for this class was generated from the following files:
Ifpack_IC.h
Ifpack_IC.cpp