IFPACK: Ifpack_CrsRiluk Class Reference
Ifpack_CrsRiluk Class Reference
Ifpack_CrsRiluk: A class for constructing and using an incomplete lower/upper (ILU) factorization of a given Epetra_RowMatrix.
#include <Ifpack_CrsRiluk.h>
Public Member Functions
Ifpack_CrsRiluk (const Ifpack_IlukGraph &Graph_in)
Ifpack_CrsRiluk constuctor with variable number of indices per row.
Ifpack_CrsRiluk (const Ifpack_CrsRiluk &Matrix)
Copy constructor.
virtual ~Ifpack_CrsRiluk ()
Ifpack_CrsRiluk Destructor.
int InitValues (const Epetra_CrsMatrix &A)
Initialize L and U with values from user matrix A.
int InitValues (const Epetra_VbrMatrix &A)
Initialize L and U with values from user matrix A.
bool ValuesInitialized () const
If values have been initialized, this query returns true, otherwise it returns false.
void SetRelaxValue (double RelaxValue)
Set RILU(k) relaxation parameter.
void SetAbsoluteThreshold (double Athresh)
Set absolute threshold value.
void SetRelativeThreshold (double Rthresh)
Set relative threshold value.
void SetOverlapMode (Epetra_CombineMode OverlapMode)
Set overlap mode type.
int SetParameters (const Teuchos::ParameterList &parameterlist, bool cerr_warning_if_unused=false)
Set parameters using a Teuchos::ParameterList object.
int Factor ()
Compute ILU factors L and U using the specified graph, diagonal perturbation thresholds and relaxation parameters.
bool Factored () const
If factor is completed, this query returns true, otherwise it returns false.
int Solve (bool Trans, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Ifpack_CrsRiluk forward/back solve on a Epetra_MultiVector X in Y (works for Epetra_Vectors also).
int Multiply (bool Trans, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of multiplying U, D and L in that order on an Epetra_MultiVector X in Y.
int Condest (bool Trans, double &ConditionNumberEstimate) const
Returns the maximum over all the condition number estimate for each local ILU set of factors.
double GetRelaxValue ()
Get RILU(k) relaxation parameter.
double GetAbsoluteThreshold ()
Get absolute threshold value.
double GetRelativeThreshold ()
Get relative threshold value.
Epetra_CombineMode GetOverlapMode ()
Get overlap mode type.
int NumGlobalRows () const
Returns the number of global matrix rows.
int NumGlobalCols () const
Returns the number of global matrix columns.
int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global graph.
virtual int NumGlobalBlockDiagonals () const
Returns the number of diagonal entries found in the global input graph.
long long NumGlobalRows64 () const
long long NumGlobalCols64 () const
long long NumGlobalNonzeros64 () const
virtual long long NumGlobalBlockDiagonals64 () const
int NumMyRows () const
Returns the number of local matrix rows.
int NumMyCols () const
Returns the number of local matrix columns.
int NumMyNonzeros () const
Returns the number of nonzero entries in the local graph.
virtual int NumMyBlockDiagonals () const
Returns the number of diagonal entries found in the local input graph.
virtual int NumMyDiagonals () const
Returns the number of nonzero diagonal values found in matrix.
int IndexBase () const
Returns the index base for row and column indices for this graph.
long long IndexBase64 () const
const Ifpack_IlukGraph & Graph () const
returns the address of the Ifpack_IlukGraph associated with this factored matrix.
const Epetra_CrsMatrix & L () const
Returns the address of the L factor associated with this factored matrix.
const Epetra_Vector & D () const
Returns the address of the D factor associated with this factored matrix.
const Epetra_CrsMatrix & U () const
Returns the address of the L factor associated with this factored matrix.
const char * Label () const
Returns a character string describing the operator.
int SetUseTranspose (bool UseTranspose_in)
If set true, transpose of this operator will be applied.
int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector X in Y.
int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector X in Y.
double NormInf () const
Returns 0.0 because this class cannot compute Inf-norm.
bool HasNormInf () const
Returns false because this class cannot compute an Inf-norm.
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
const Epetra_Comm & Comm () const
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Public Member Functions inherited from Epetra_Object
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object (const Epetra_Object &Object)
virtual void Print (std::ostream &os) const
virtual int ReportError (const std::string Message, int ErrorCode) const
Epetra_Object (int TracebackModeIn=-1, bool set_label=true)
Epetra_Object (const char *const Label, int TracebackModeIn=-1)
Epetra_Object (const Epetra_Object &Object)
virtual void SetLabel (const char *const Label)
Public Member Functions inherited from Epetra_CompObject
Epetra_CompObject (const Epetra_CompObject &Source)
void SetFlopCounter (const Epetra_Flops &FlopCounter_in)
void SetFlopCounter (const Epetra_CompObject &CompObject)
void UnsetFlopCounter ()
Epetra_Flops * GetFlopCounter () const
void ResetFlops () const
double Flops () const
void UpdateFlops (int Flops_in) const
void UpdateFlops (long int Flops_in) const
void UpdateFlops (long long Flops_in) const
void UpdateFlops (double Flops_in) const
void UpdateFlops (float Flops_in) const
Epetra_CompObject (const Epetra_CompObject &Source)
void SetFlopCounter (const Epetra_Flops &FlopCounter_in)
void SetFlopCounter (const Epetra_CompObject &CompObject)
void UnsetFlopCounter ()
Epetra_Flops * GetFlopCounter () const
void ResetFlops () const
double Flops () const
Protected Member Functions
void SetFactored (bool Flag)
void SetValuesInitialized (bool Flag)
bool Allocated () const
int SetAllocated (bool Flag)
int BlockGraph2PointGraph (const Epetra_CrsGraph &BG, Epetra_CrsGraph &PG, bool Upper)
Friends
std::ostream & operator<< (std::ostream &os, const Ifpack_CrsRiluk &A)
<< operator will work for Ifpack_CrsRiluk.
Additional Inherited Members
Static Public Member Functions inherited from Epetra_Object
static void SetTracebackMode (int TracebackModeValue)
static int GetTracebackMode ()
static std::ostream & GetTracebackStream ()
Detailed Description
Ifpack_CrsRiluk: A class for constructing and using an incomplete lower/upper (ILU) factorization of a given Epetra_RowMatrix.
The Ifpack_CrsRiluk class computes a "Relaxed" ILU factorization with level k fill of a given Epetra_CrsMatrix. The factorization that is produced is a function of several parameters:
The pattern of the matrix - All fill is derived from the original matrix nonzero structure. Level zero fill is defined as the original matrix pattern (nonzero structure), even if the matrix value at an entry is stored as a zero. (Thus it is possible to add entries to the ILU factors by adding zero entries the original matrix.)
Level of fill - Starting with the original matrix pattern as level fill of zero, the next level of fill is determined by analyzing the graph of the previous level and determining nonzero fill that is a result of combining entries that were from previous level only (not the current level). This rule limits fill to entries that are direct decendents from the previous level graph. Fill for level k is determined by applying this rule recursively. For sufficiently large values of k, the fill would eventually be complete and an exact LU factorization would be computed. Level of fill is defined during the construction of the Ifpack_IlukGraph object.
Level of overlap - All Ifpack preconditioners work on parallel distributed memory computers by using the row partitioning the user input matrix to determine the partitioning for local ILU factors. If the level of overlap is set to zero, the rows of the user matrix that are stored on a given processor are treated as a self-contained local matrix and all column entries that reach to off-processor entries are ignored. Setting the level of overlap to one tells Ifpack to increase the size of the local matrix by adding rows that are reached to by rows owned by this processor. Increasing levels of overlap are defined recursively in the same way. For sufficiently large levels of overlap, the entire matrix would be part of each processor's local ILU factorization process. Level of overlap is defined during the construction of the Ifpack_IlukGraph object.
Once the factorization is computed, applying the factorization (LUy = x) results in redundant approximations for any elements of y that correspond to rows that are part of more than one local ILU factor. The OverlapMode (changed by calling SetOverlapMode()) defines how these redundancies are handled using the Epetra_CombineMode enum. The default is to zero out all values of y for rows that were not part of the original matrix row distribution.
Fraction of relaxation - Ifpack_CrsRiluk computes the ILU factorization row-by-row. As entries at a given row are computed, some number of them will be dropped because they do match the prescribed sparsity pattern. The relaxation factor determines how these dropped values will be handled. If the RelaxValue (changed by calling SetRelaxValue()) is zero, then these extra entries will by dropped. This is a classical ILU approach. If the RelaxValue is 1, then the sum of the extra entries will be added to the diagonal. This is a classical Modified ILU (MILU) approach. If RelaxValue is between 0 and 1, then RelaxValue times the sum of extra entries will be added to the diagonal.
For most situations, RelaxValue should be set to zero. For certain kinds of problems, e.g., reservoir modeling, there is a conservation principle involved such that any operator should obey a zero row-sum property. MILU was designed for these cases and you should set the RelaxValue to 1. For other situations, setting RelaxValue to some nonzero value may improve the stability of factorization, and can be used if the computed ILU factors are poorly conditioned.
Diagonal perturbation - Prior to computing the factorization, it is possible to modify the diagonal entries of the matrix for which the factorization will be computing. If the absolute and relative perturbation values are zero and one, respectively, the factorization will be compute for the original user matrix A. Otherwise, the factorization will computed for a matrix that differs from the original user matrix in the diagonal values only. Below we discuss the details of diagonal perturbations. The absolute and relative threshold values are set by calling SetAbsoluteThreshold() and SetRelativeThreshold(), respectively.
Estimating Preconditioner Condition Numbers
For ill-conditioned matrices, we often have difficulty computing usable incomplete factorizations. The most common source of problems is that the factorization may encounter a small or zero pivot, in which case the factorization can fail, or even if the factorization succeeds, the factors may be so poorly conditioned that use of them in the iterative phase produces meaningless results. Before we can fix this problem, we must be able to detect it. To this end, we use a simple but effective condition number estimate for \((LU)^{-1}\).
The condition of a matrix \(B\), called \(cond_p(B)\), is defined as \(cond_p(B) = \|B\|_p\|B^{-1}\|_p\) in some appropriate norm \(p\). \(cond_p(B)\) gives some indication of how many accurate floating point digits can be expected from operations involving the matrix and its inverse. A condition number approaching the accuracy of a given floating point number system, about 15 decimal digits in IEEE double precision, means that any results involving \(B\) or \(B^{-1}\) may be meaningless.
The \(\infty\)-norm of a vector \(y\) is defined as the maximum of the absolute values of the vector entries, and the \(\infty\)-norm of a matrix C is defined as \(\|C\|_\infty = \max_{\|y\|_\infty = 1} \|Cy\|_\infty\). A crude lower bound for the \(cond_\infty(C)\) is \(\|C^{-1}e\|_\infty\) where \(e = (1, 1, \ldots, 1)^T\). It is a lower bound because \(cond_\infty(C) = \|C\|_\infty\|C^{-1}\|_\infty \ge \|C^{-1}\|_\infty \ge |C^{-1}e\|_\infty\).
For our purposes, we want to estimate \(cond_\infty(LU)\), where \(L\) and \(U\) are our incomplete factors. Edmond in his Ph.D. thesis demonstrates that \(\|(LU)^{-1}e\|_\infty\) provides an effective estimate for \(cond_\infty(LU)\). Furthermore, since finding \(z\) such that \(LUz = y\) is a basic kernel for applying the preconditioner, computing this estimate of \(cond_\infty(LU)\) is performed by setting \(y = e\), calling the solve kernel to compute \(z\) and then computing \(\|z\|_\infty\).
A priori Diagonal Perturbations
Given the above method to estimate the conditioning of the incomplete factors, if we detect that our factorization is too ill-conditioned we can improve the conditioning by perturbing the matrix diagonal and restarting the factorization using this more diagonally dominant matrix. In order to apply perturbation, prior to starting the factorization, we compute a diagonal perturbation of our matrix \(A\) and perform the factorization on this perturbed matrix. The overhead cost of perturbing the diagonal is minimal since the first step in computing the incomplete factors is to copy the matrix \(A\) into the memory space for the incomplete factors. We simply compute the perturbed diagonal at this point.
The actual perturbation values we use are the diagonal values \((d_1, d_2, \ldots, d_n)\) with \(d_i = sgn(d_i)\alpha + d_i\rho\), \(i=1, 2, \ldots, n\), where \(n\) is the matrix dimension and \(sgn(d_i)\) returns the sign of the diagonal entry. This has the effect of forcing the diagonal values to have minimal magnitude of \(\alpha\) and to increase each by an amount proportional to \(\rho\), and still keep the sign of the original diagonal entry.
Constructing Ifpack_CrsRiluk objects
Constructing Ifpack_CrsRiluk objects is a multi-step process. The basic steps are as follows:
Create Ifpack_CrsRiluk instance, including storage, via constructor.
Enter values via one or more Put or SumInto functions.
Complete construction via FillComplete call.
Note that, even after a matrix is constructed, it is possible to update existing matrix entries. It is not possible to create new entries.
Counting Floating Point Operations
Each Ifpack_CrsRiluk object keep track of the number of serial floating point operations performed using the specified object as the this argument to the function. The Flops() function returns this number as a double precision number. Using this information, in conjunction with the Epetra_Time class, one can get accurate parallel performance numbers. The ResetFlops() function resets the floating point counter.
Warning
A Epetra_Map is required for the Ifpack_CrsRiluk constructor.
Definition at line 216 of file Ifpack_CrsRiluk.h.
Constructor & Destructor Documentation
Ifpack_CrsRiluk() [1/2]
Ifpack_CrsRiluk::Ifpack_CrsRiluk (const Ifpack_IlukGraph & Graph_in)
Ifpack_CrsRiluk constuctor with variable number of indices per row.
Creates a Ifpack_CrsRiluk object and allocates storage.
Parameters
In Graph_in - Graph generated by Ifpack_IlukGraph.
Definition at line 55 of file Ifpack_CrsRiluk.cpp.
References Epetra_BlockMap::DistributedGlobal(), Ifpack_IlukGraph::DomainMap(), Ifpack_IlukGraph::LevelOverlap(), and Zero.
Ifpack_CrsRiluk() [2/2]
Ifpack_CrsRiluk::Ifpack_CrsRiluk (const Ifpack_CrsRiluk & Matrix)
Copy constructor.
Definition at line 76 of file Ifpack_CrsRiluk.cpp.
References D(), L(), and U().
~Ifpack_CrsRiluk()
Ifpack_CrsRiluk::~Ifpack_CrsRiluk () virtual
Ifpack_CrsRiluk Destructor.
Definition at line 105 of file Ifpack_CrsRiluk.cpp.
Member Function Documentation
Allocated()
bool Ifpack_CrsRiluk::Allocated () const inline protected
Definition at line 475 of file Ifpack_CrsRiluk.h.
Apply()
int Ifpack_CrsRiluk::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector X in Y.
Note that this implementation of Apply does NOT perform a forward back solve with the LDU factorization. Instead it applies these operators via multiplication with U, D and L respectively. The ApplyInverse() method performs a solve.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
Definition at line 433 of file Ifpack_CrsRiluk.h.
References Multiply(), and UseTranspose().
ApplyInverse()
int Ifpack_CrsRiluk::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector X in Y.
In this implementation, we use several existing attributes to determine how virtual method ApplyInverse() should call the concrete method Solve(). We pass in the UpperTriangular(), the Epetra_CrsMatrix::UseTranspose(), and NoDiagonal() methods. The most notable warning is that if a matrix has no diagonal values we assume that there is an implicit unit diagonal that should be accounted for when doing a triangular solve.
Parameters
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
Definition at line 450 of file Ifpack_CrsRiluk.h.
References Solve(), and UseTranspose().
BlockGraph2PointGraph()
int Ifpack_CrsRiluk::BlockGraph2PointGraph (const Epetra_CrsGraph & BG, Epetra_CrsGraph & PG, bool Upper) protected
Definition at line 614 of file Ifpack_CrsRiluk.cpp.
Comm()
const Epetra_Comm & Ifpack_CrsRiluk::Comm () const inline virtual
Returns the Epetra_BlockMap object associated with the range of this matrix operator.
Implements Epetra_Operator.
Definition at line 469 of file Ifpack_CrsRiluk.h.
Condest()
int Ifpack_CrsRiluk::Condest (bool Trans, double & ConditionNumberEstimate) const
Returns the maximum over all the condition number estimate for each local ILU set of factors.
This functions computes a local condition number estimate on each processor and return the maximum over all processor of the estimate.
Parameters
In Trans -If true, solve transpose problem.
Out ConditionNumberEstimate - The maximum across all processors of the infinity-norm estimate of the condition number of the inverse of LDU.
Definition at line 596 of file Ifpack_CrsRiluk.cpp.
References Epetra_MultiVector::Abs(), Epetra_MultiVector::MaxValue(), Epetra_MultiVector::PutScalar(), and Solve().
D()
const Epetra_Vector & Ifpack_CrsRiluk::D () const inline
Returns the address of the D factor associated with this factored matrix.
Definition at line 399 of file Ifpack_CrsRiluk.h.
Referenced by Ifpack_CrsRiluk().
Factor()
int Ifpack_CrsRiluk::Factor ()
Compute ILU factors L and U using the specified graph, diagonal perturbation thresholds and relaxation parameters.
This function computes the RILU(k) factors L and U using the current:
Ifpack_IlukGraph specifying the structure of L and U.
Value for the RILU(k) relaxation parameter.
Value for the a priori diagonal threshold values.
InitValues() must be called before the factorization can proceed.
Definition at line 361 of file Ifpack_CrsRiluk.cpp.
References Epetra_BlockMap::Comm(), Factored(), Ifpack_IlukGraph::L_Graph(), NumMyCols(), NumMyRows(), Epetra_CrsGraph::RowMap(), Epetra_Comm::SumAll(), Epetra_CompObject::UpdateFlops(), and ValuesInitialized().
Factored()
bool Ifpack_CrsRiluk::Factored () const inline
If factor is completed, this query returns true, otherwise it returns false.
Definition at line 295 of file Ifpack_CrsRiluk.h.
Referenced by Factor().
GetAbsoluteThreshold()
double Ifpack_CrsRiluk::GetAbsoluteThreshold () inline
Get absolute threshold value.
Definition at line 343 of file Ifpack_CrsRiluk.h.
GetOverlapMode()
Epetra_CombineMode Ifpack_CrsRiluk::GetOverlapMode () inline
Get overlap mode type.
Definition at line 349 of file Ifpack_CrsRiluk.h.
GetRelativeThreshold()
double Ifpack_CrsRiluk::GetRelativeThreshold () inline
Get relative threshold value.
Definition at line 346 of file Ifpack_CrsRiluk.h.
GetRelaxValue()
double Ifpack_CrsRiluk::GetRelaxValue () inline
Get RILU(k) relaxation parameter.
Definition at line 340 of file Ifpack_CrsRiluk.h.
Graph()
const Ifpack_IlukGraph & Ifpack_CrsRiluk::Graph () const inline
returns the address of the Ifpack_IlukGraph associated with this factored matrix.
Definition at line 393 of file Ifpack_CrsRiluk.h.
Referenced by IndexBase(), NumGlobalBlockDiagonals(), NumGlobalCols(), NumGlobalRows(), NumMyBlockDiagonals(), NumMyCols(), and NumMyRows().
HasNormInf()
bool Ifpack_CrsRiluk::HasNormInf () const inline virtual
Returns false because this class cannot compute an Inf-norm.
Implements Epetra_Operator.
Definition at line 457 of file Ifpack_CrsRiluk.h.
IndexBase()
int Ifpack_CrsRiluk::IndexBase () const inline
Returns the index base for row and column indices for this graph.
Definition at line 388 of file Ifpack_CrsRiluk.h.
References Graph(), and IndexBase().
Referenced by IndexBase().
IndexBase64()
long long Ifpack_CrsRiluk::IndexBase64 () const inline
Definition at line 390 of file Ifpack_CrsRiluk.h.
InitValues() [1/2]
int Ifpack_CrsRiluk::InitValues (const Epetra_CrsMatrix & A)
Initialize L and U with values from user matrix A.
Copies values from the user's matrix into the nonzero pattern of L and U.
Parameters
In A - User matrix to be factored.
Warning
The graph of A must be identical to the graph passed in to Ifpack_IlukGraph constructor.
Definition at line 182 of file Ifpack_CrsRiluk.cpp.
References Copy, Epetra_CrsMatrix::DomainMap(), Insert, Ifpack_IlukGraph::OverlapGraph(), Ifpack_IlukGraph::OverlapImporter(), and Epetra_CrsMatrix::RangeMap().
InitValues() [2/2]
int Ifpack_CrsRiluk::InitValues (const Epetra_VbrMatrix & A)
Initialize L and U with values from user matrix A.
Copies values from the user's matrix into the nonzero pattern of L and U.
Parameters
In A - User matrix to be factored.
Warning
The graph of A must be identical to the graph passed in to Ifpack_IlukGraph constructor.
Definition at line 212 of file Ifpack_CrsRiluk.cpp.
References Copy, Insert, Ifpack_IlukGraph::OverlapGraph(), and Ifpack_IlukGraph::OverlapImporter().
L()
const Epetra_CrsMatrix & Ifpack_CrsRiluk::L () const inline
Returns the address of the L factor associated with this factored matrix.
Definition at line 396 of file Ifpack_CrsRiluk.h.
Referenced by Ifpack_CrsRiluk(), NumGlobalNonzeros(), and NumMyNonzeros().
Label()
const char * Ifpack_CrsRiluk::Label () const inline virtual
Returns a character string describing the operator.
Reimplemented from Epetra_Object.
Definition at line 407 of file Ifpack_CrsRiluk.h.
References Epetra_Object::Label().
Multiply()
int Ifpack_CrsRiluk::Multiply (bool Trans, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const
Returns the result of multiplying U, D and L in that order on an Epetra_MultiVector X in Y.
Parameters
In Trans -If true, multiply by L^T, D and U^T in that order.
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
Definition at line 554 of file Ifpack_CrsRiluk.cpp.
References Epetra_DistObject::Export(), and Epetra_CompObject::GetFlopCounter().
Referenced by Apply().
NormInf()
double Ifpack_CrsRiluk::NormInf () const inline virtual
Returns 0.0 because this class cannot compute Inf-norm.
Implements Epetra_Operator.
Definition at line 454 of file Ifpack_CrsRiluk.h.
NumGlobalBlockDiagonals()
virtual int Ifpack_CrsRiluk::NumGlobalBlockDiagonals () const inline virtual
Returns the number of diagonal entries found in the global input graph.
Definition at line 363 of file Ifpack_CrsRiluk.h.
References Graph(), and NumGlobalBlockDiagonals().
Referenced by NumGlobalBlockDiagonals().
NumGlobalBlockDiagonals64()
virtual long long Ifpack_CrsRiluk::NumGlobalBlockDiagonals64 () const inline virtual
Definition at line 369 of file Ifpack_CrsRiluk.h.
NumGlobalCols()
int Ifpack_CrsRiluk::NumGlobalCols () const inline
Returns the number of global matrix columns.
Definition at line 357 of file Ifpack_CrsRiluk.h.
References Graph(), and NumGlobalCols().
Referenced by NumGlobalCols().
NumGlobalCols64()
long long Ifpack_CrsRiluk::NumGlobalCols64 () const inline
Definition at line 367 of file Ifpack_CrsRiluk.h.
NumGlobalNonzeros()
int Ifpack_CrsRiluk::NumGlobalNonzeros () const inline
Returns the number of nonzero entries in the global graph.
Definition at line 360 of file Ifpack_CrsRiluk.h.
References L(), NumGlobalNonzeros(), and U().
Referenced by NumGlobalNonzeros().
NumGlobalNonzeros64()
long long Ifpack_CrsRiluk::NumGlobalNonzeros64 () const inline
Definition at line 368 of file Ifpack_CrsRiluk.h.
NumGlobalRows()
int Ifpack_CrsRiluk::NumGlobalRows () const inline
Returns the number of global matrix rows.
Definition at line 354 of file Ifpack_CrsRiluk.h.
References Graph(), and NumGlobalRows().
Referenced by NumGlobalRows().
NumGlobalRows64()
long long Ifpack_CrsRiluk::NumGlobalRows64 () const inline
Definition at line 366 of file Ifpack_CrsRiluk.h.
NumMyBlockDiagonals()
virtual int Ifpack_CrsRiluk::NumMyBlockDiagonals () const inline virtual
Returns the number of diagonal entries found in the local input graph.
Definition at line 381 of file Ifpack_CrsRiluk.h.
References Graph(), and NumMyBlockDiagonals().
Referenced by NumMyBlockDiagonals().
NumMyCols()
int Ifpack_CrsRiluk::NumMyCols () const inline
Returns the number of local matrix columns.
Definition at line 375 of file Ifpack_CrsRiluk.h.
References Graph(), and NumMyCols().
Referenced by Factor(), and NumMyCols().
NumMyDiagonals()
virtual int Ifpack_CrsRiluk::NumMyDiagonals () const inline virtual
Returns the number of nonzero diagonal values found in matrix.
Definition at line 384 of file Ifpack_CrsRiluk.h.
NumMyNonzeros()
int Ifpack_CrsRiluk::NumMyNonzeros () const inline
Returns the number of nonzero entries in the local graph.
Definition at line 378 of file Ifpack_CrsRiluk.h.
References L(), NumMyNonzeros(), and U().
Referenced by NumMyNonzeros().
NumMyRows()
int Ifpack_CrsRiluk::NumMyRows () const inline
Returns the number of local matrix rows.
Definition at line 372 of file Ifpack_CrsRiluk.h.
References Graph(), and NumMyRows().
Referenced by Factor(), and NumMyRows().
OperatorDomainMap()
const Epetra_Map & Ifpack_CrsRiluk::OperatorDomainMap () const inline virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
Definition at line 463 of file Ifpack_CrsRiluk.h.
OperatorRangeMap()
const Epetra_Map & Ifpack_CrsRiluk::OperatorRangeMap () const inline virtual
Returns the Epetra_Map object associated with the range of this operator.
Implements Epetra_Operator.
Definition at line 466 of file Ifpack_CrsRiluk.h.
SetAbsoluteThreshold()
void Ifpack_CrsRiluk::SetAbsoluteThreshold (double Athresh) inline
Set absolute threshold value.
Definition at line 264 of file Ifpack_CrsRiluk.h.
SetAllocated()
int Ifpack_CrsRiluk::SetAllocated (bool Flag) inline protected
Definition at line 476 of file Ifpack_CrsRiluk.h.
SetFactored()
void Ifpack_CrsRiluk::SetFactored (bool Flag) inline protected
Definition at line 473 of file Ifpack_CrsRiluk.h.
SetOverlapMode()
void Ifpack_CrsRiluk::SetOverlapMode (Epetra_CombineMode OverlapMode) inline
Set overlap mode type.
Definition at line 270 of file Ifpack_CrsRiluk.h.
SetParameters()
int Ifpack_CrsRiluk::SetParameters (const Teuchos::ParameterList & parameterlist, bool cerr_warning_if_unused = false)
Set parameters using a Teuchos::ParameterList object.
Definition at line 162 of file Ifpack_CrsRiluk.cpp.
SetRelativeThreshold()
void Ifpack_CrsRiluk::SetRelativeThreshold (double Rthresh) inline
Set relative threshold value.
Definition at line 267 of file Ifpack_CrsRiluk.h.
SetRelaxValue()
void Ifpack_CrsRiluk::SetRelaxValue (double RelaxValue) inline
Set RILU(k) relaxation parameter.
Definition at line 261 of file Ifpack_CrsRiluk.h.
SetUseTranspose()
int Ifpack_CrsRiluk::SetUseTranspose (bool UseTranspose_in) inline virtual
If set true, transpose of this operator will be applied.
This flag allows the transpose of the given operator to be used implicitly. Setting this flag affects only the Apply() and ApplyInverse() methods. If the implementation of this interface does not support transpose use, this method should return a value of -1.
Parameters
In UseTranspose_in -If true, multiply by the transpose of operator, otherwise just use operator.
Returns
Always returns 0.
Implements Epetra_Operator.
Definition at line 419 of file Ifpack_CrsRiluk.h.
SetValuesInitialized()
void Ifpack_CrsRiluk::SetValuesInitialized (bool Flag) inline protected
Definition at line 474 of file Ifpack_CrsRiluk.h.
Solve()
int Ifpack_CrsRiluk::Solve (bool Trans, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const
Returns the result of a Ifpack_CrsRiluk forward/back solve on a Epetra_MultiVector X in Y (works for Epetra_Vectors also).
Parameters
In Trans -If true, solve transpose problem.
In X - A Epetra_MultiVector of dimension NumVectors to solve for.
Out Y -A Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
Definition at line 513 of file Ifpack_CrsRiluk.cpp.
References Epetra_DistObject::Export(), and Epetra_CompObject::GetFlopCounter().
Referenced by ApplyInverse(), and Condest().
U()
const Epetra_CrsMatrix & Ifpack_CrsRiluk::U () const inline
Returns the address of the L factor associated with this factored matrix.
Definition at line 402 of file Ifpack_CrsRiluk.h.
Referenced by Ifpack_CrsRiluk(), NumGlobalNonzeros(), and NumMyNonzeros().
UseTranspose()
bool Ifpack_CrsRiluk::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Definition at line 460 of file Ifpack_CrsRiluk.h.
Referenced by Apply(), and ApplyInverse().
ValuesInitialized()
bool Ifpack_CrsRiluk::ValuesInitialized () const inline
If values have been initialized, this query returns true, otherwise it returns false.
Definition at line 258 of file Ifpack_CrsRiluk.h.
Referenced by Factor().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Ifpack_CrsRiluk & A) friend
<< operator will work for Ifpack_CrsRiluk.
Definition at line 795 of file Ifpack_CrsRiluk.cpp.
The documentation for this class was generated from the following files:
Ifpack_CrsRiluk.h
Ifpack_CrsRiluk.cpp