IFPACK: Ifpack_Krylov Class Reference
Ifpack_Krylov Class Reference
Ifpack_Krylov: class for smoothing with Krylov solvers in Ifpack.
#include <Ifpack_Krylov.h>
Public Member Functions
Ifpack_Krylov (Epetra_Operator *Matrix)
Ifpack_Krylov (Epetra_RowMatrix *Matrix)
Ifpack_Krylov constructor with given Epetra_Operator/Epetra_RowMatrix.
virtual ~Ifpack_Krylov ()
Destructor.
virtual int SetUseTranspose (bool UseTranspose_in)
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Applies the matrix to an Epetra_MultiVector.
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Applies the preconditioner to X, returns the result in Y.
virtual double NormInf () const
Returns the infinity norm of the global matrix (not implemented)
virtual const char * Label () const
virtual bool UseTranspose () const
Returns the current UseTranspose setting.
virtual bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
virtual const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
virtual const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
virtual const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
virtual int Initialize ()
Computes all it is necessary to initialize the preconditioner.
virtual bool IsInitialized () const
Returns true if the preconditioner has been successfully initialized, false otherwise.
virtual bool IsComputed () const
Returns true if the preconditioner has been successfully computed.
virtual int Compute ()
Computes the preconditioners.
virtual const Epetra_RowMatrix & Matrix () const
Returns a pointer to the matrix to be preconditioned.
virtual double Condest (const Ifpack_CondestType CT=Ifpack_Cheap, const int MaxIters=1550, const double Tol=1e-9, Epetra_RowMatrix *Matrix_in=0)
Computes the condition number estimates and returns the value.
virtual double Condest () const
Returns the condition number estimate, or -1.0 if not computed.
virtual int SetParameters (Teuchos::ParameterList &List)
Sets all the parameters for the preconditioner.
virtual std::ostream & Print (std::ostream &os) const
Prints object to an output stream.
virtual int NumInitialize () const
Returns the number of calls to Initialize().
virtual int NumCompute () const
Returns the number of calls to Compute().
virtual int NumApplyInverse () const
Returns the number of calls to ApplyInverse().
virtual double InitializeTime () const
Returns the time spent in Initialize().
virtual double ComputeTime () const
Returns the time spent in Compute().
virtual double ApplyInverseTime () const
Returns the time spent in ApplyInverse().
virtual double InitializeFlops () const
Returns the number of flops in the initialization phase.
virtual double ComputeFlops () const
Returns the number of flops in the computation phase.
virtual double ApplyInverseFlops () const
Returns the number of flops for the application of the preconditioner.
Detailed Description
Ifpack_Krylov: class for smoothing with Krylov solvers in Ifpack.
Definition at line 87 of file Ifpack_Krylov.h.
Constructor & Destructor Documentation
Ifpack_Krylov() [1/2]
Ifpack_Krylov::Ifpack_Krylov (Epetra_Operator * Matrix)
Definition at line 67 of file Ifpack_Krylov.cpp.
Ifpack_Krylov() [2/2]
Ifpack_Krylov::Ifpack_Krylov (Epetra_RowMatrix * Matrix)
Ifpack_Krylov constructor with given Epetra_Operator/Epetra_RowMatrix.
Definition at line 109 of file Ifpack_Krylov.cpp.
~Ifpack_Krylov()
virtual Ifpack_Krylov::~Ifpack_Krylov () inline virtual
Destructor.
Definition at line 103 of file Ifpack_Krylov.h.
Member Function Documentation
Apply()
int Ifpack_Krylov::Apply (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Applies the matrix to an Epetra_MultiVector.
Parameters
X - (In) A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Y - (Out) A Epetra_MultiVector of dimension NumVectors containing the result.
Returns
Integer error code, set to 0 if successful.
Implements Epetra_Operator.
Definition at line 177 of file Ifpack_Krylov.cpp.
References IsComputed(), Epetra_MultiVector::NumVectors(), and UseTranspose().
ApplyInverse()
int Ifpack_Krylov::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Applies the preconditioner to X, returns the result in Y.
Parameters
X - (In) A Epetra_MultiVector of dimension NumVectors to be preconditioned.
Y - (InOut) A Epetra_MultiVector of dimension NumVectors containing result.
Returns
Integer error code, set to 0 if successful.
Warning
This routine is NOT AztecOO complaint.
Implements Ifpack_Preconditioner.
Definition at line 379 of file Ifpack_Krylov.cpp.
References IsComputed(), Epetra_MultiVector::NumVectors(), and Epetra_MultiVector::PutScalar().
ApplyInverseFlops()
virtual double Ifpack_Krylov::ApplyInverseFlops () const inline virtual
Returns the number of flops for the application of the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 274 of file Ifpack_Krylov.h.
ApplyInverseTime()
virtual double Ifpack_Krylov::ApplyInverseTime () const inline virtual
Returns the time spent in ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 256 of file Ifpack_Krylov.h.
Comm()
const Epetra_Comm & Ifpack_Krylov::Comm () const virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Epetra_Operator.
Definition at line 159 of file Ifpack_Krylov.cpp.
Referenced by Initialize(), and Print().
Compute()
int Ifpack_Krylov::Compute () virtual
Computes the preconditioners.
Implements Ifpack_Preconditioner.
Definition at line 233 of file Ifpack_Krylov.cpp.
References Compute(), Initialize(), IsInitialized(), and SetParameters().
Referenced by Compute().
ComputeFlops()
virtual double Ifpack_Krylov::ComputeFlops () const inline virtual
Returns the number of flops in the computation phase.
Implements Ifpack_Preconditioner.
Definition at line 268 of file Ifpack_Krylov.h.
ComputeTime()
virtual double Ifpack_Krylov::ComputeTime () const inline virtual
Returns the time spent in Compute().
Implements Ifpack_Preconditioner.
Definition at line 250 of file Ifpack_Krylov.h.
Condest() [1/2]
virtual double Ifpack_Krylov::Condest () const inline virtual
Returns the condition number estimate, or -1.0 if not computed.
Implements Ifpack_Preconditioner.
Definition at line 210 of file Ifpack_Krylov.h.
Referenced by Print().
Condest() [2/2]
double Ifpack_Krylov::Condest (const Ifpack_CondestType CT = Ifpack_Cheap, const int MaxIters = 1550, const double Tol = 1e-9, Epetra_RowMatrix * Matrix_in = 0) virtual
Computes the condition number estimates and returns the value.
Implements Ifpack_Preconditioner.
Definition at line 357 of file Ifpack_Krylov.cpp.
References IsComputed().
HasNormInf()
virtual bool Ifpack_Krylov::HasNormInf () const inline virtual
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
Implements Epetra_Operator.
Definition at line 168 of file Ifpack_Krylov.h.
Initialize()
int Ifpack_Krylov::Initialize () virtual
Computes all it is necessary to initialize the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 199 of file Ifpack_Krylov.cpp.
References Comm(), and Matrix().
Referenced by Compute().
InitializeFlops()
virtual double Ifpack_Krylov::InitializeFlops () const inline virtual
Returns the number of flops in the initialization phase.
Implements Ifpack_Preconditioner.
Definition at line 262 of file Ifpack_Krylov.h.
InitializeTime()
virtual double Ifpack_Krylov::InitializeTime () const inline virtual
Returns the time spent in Initialize().
Implements Ifpack_Preconditioner.
Definition at line 244 of file Ifpack_Krylov.h.
IsComputed()
virtual bool Ifpack_Krylov::IsComputed () const inline virtual
Returns true if the preconditioner has been successfully computed.
Implements Ifpack_Preconditioner.
Definition at line 190 of file Ifpack_Krylov.h.
Referenced by Apply(), ApplyInverse(), and Condest().
IsInitialized()
virtual bool Ifpack_Krylov::IsInitialized () const inline virtual
Returns true if the preconditioner has been successfully initialized, false otherwise.
Implements Ifpack_Preconditioner.
Definition at line 184 of file Ifpack_Krylov.h.
Referenced by Compute().
Label()
virtual const char * Ifpack_Krylov::Label () const inline virtual
Implements Epetra_Operator.
Definition at line 156 of file Ifpack_Krylov.h.
Matrix()
virtual const Epetra_RowMatrix & Ifpack_Krylov::Matrix () const inline virtual
Returns a pointer to the matrix to be preconditioned.
Implements Ifpack_Preconditioner.
Definition at line 198 of file Ifpack_Krylov.h.
Referenced by Initialize().
NormInf()
virtual double Ifpack_Krylov::NormInf () const inline virtual
Returns the infinity norm of the global matrix (not implemented)
Implements Epetra_Operator.
Definition at line 148 of file Ifpack_Krylov.h.
NumApplyInverse()
virtual int Ifpack_Krylov::NumApplyInverse () const inline virtual
Returns the number of calls to ApplyInverse().
Implements Ifpack_Preconditioner.
Definition at line 238 of file Ifpack_Krylov.h.
NumCompute()
virtual int Ifpack_Krylov::NumCompute () const inline virtual
Returns the number of calls to Compute().
Implements Ifpack_Preconditioner.
Definition at line 232 of file Ifpack_Krylov.h.
NumInitialize()
virtual int Ifpack_Krylov::NumInitialize () const inline virtual
Returns the number of calls to Initialize().
Implements Ifpack_Preconditioner.
Definition at line 226 of file Ifpack_Krylov.h.
OperatorDomainMap()
const Epetra_Map & Ifpack_Krylov::OperatorDomainMap () const virtual
Returns the Epetra_Map object associated with the domain of this operator.
Implements Epetra_Operator.
Definition at line 165 of file Ifpack_Krylov.cpp.
OperatorRangeMap()
const Epetra_Map & Ifpack_Krylov::OperatorRangeMap () const virtual
Returns the Epetra_Map object associated with the range of this operator.
Implements Epetra_Operator.
Definition at line 171 of file Ifpack_Krylov.cpp.
Print()
std::ostream & Ifpack_Krylov::Print (std::ostream & os) const virtual
Prints object to an output stream.
Implements Ifpack_Preconditioner.
Definition at line 310 of file Ifpack_Krylov.cpp.
References Comm(), and Condest().
SetParameters()
int Ifpack_Krylov::SetParameters (Teuchos::ParameterList & List) virtual
Sets all the parameters for the preconditioner.
Implements Ifpack_Preconditioner.
Definition at line 144 of file Ifpack_Krylov.cpp.
Referenced by Compute().
SetUseTranspose()
virtual int Ifpack_Krylov::SetUseTranspose (bool UseTranspose_in) inline virtual
This flag can be used to apply the preconditioner to the transpose of the input operator.
Returns
Integer error code, set to 0 if successful. Set to -1 if this implementation does not support transpose.
Implements Epetra_Operator.
Definition at line 113 of file Ifpack_Krylov.h.
UseTranspose()
virtual bool Ifpack_Krylov::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
Definition at line 162 of file Ifpack_Krylov.h.
Referenced by Apply().
The documentation for this class was generated from the following files:
Ifpack_Krylov.h
Ifpack_Krylov.cpp