IFPACK: Ifpack_Utils.h File Reference
Ifpack_Utils.h File Reference
#include "Ifpack_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "unistd.h"
Classes
class Ifpack_Element
Functions
void Ifpack_PrintLine ()
Prints a line of ‘=’ on cout.
void Ifpack_BreakForDebugger (Epetra_Comm &Comm)
Stops the execution of code, so that a debugger can be attached.
Epetra_CrsMatrix * Ifpack_CreateOverlappingCrsMatrix (const Epetra_RowMatrix *Matrix, const int OverlappingLevel)
Creates an overlapping Epetra_CrsMatrix. Returns 0 if OverlappingLevel is 0.
Epetra_CrsGraph * Ifpack_CreateOverlappingCrsMatrix (const Epetra_CrsGraph *Graph, const int OverlappingLevel)
Creates an overlapping Epetra_CrsGraph. Returns 0 if OverlappingLevel is 0.
std::string Ifpack_toString (const int &x)
Converts an integer to std::string.
std::string Ifpack_toString (const double &x)
Converts a double to std::string.
int Ifpack_PrintResidual (char *Label, const Epetra_RowMatrix &A, const Epetra_MultiVector &X, const Epetra_MultiVector &Y)
Prints on cout the true residual.
int Ifpack_PrintResidual (const int iter, const Epetra_RowMatrix &A, const Epetra_MultiVector &X, const Epetra_MultiVector &Y)
void Ifpack_PrintSparsity_Simple (const Epetra_RowMatrix &A)
int Ifpack_Analyze (const Epetra_RowMatrix &A, const bool Cheap=false, const int NumPDEEqns=1)
Analyzes the basic properties of the input matrix A; see Usage of Ifpack_Analyze()..
int Ifpack_AnalyzeMatrixElements (const Epetra_RowMatrix &A, const bool abs=false, const int steps=10)
Analyzes the distribution of values of the input matrix A.
int Ifpack_AnalyzeVectorElements (const Epetra_Vector &Diagonal, const bool abs=false, const int steps=10)
Analyzes the distribution of values of the input vector Diagonal.
Largely inspired from Yousef Saad's SPARSKIT plot function.
Plots the sparsity pattern of an Epetra_RowMatrix into a PS file.
Parameters
A (In) - Epetra_RowMatrix whose sparsity pattern will be plotted.
FileName (In) - char std::string containing the filename. If 0, then the matrix label is used as file name, after appending .ps.
NumPDEEqns (In) - number of PDE equations. The function will plot the block structure of the matrix if NumPDEEqns > 1
int Ifpack_PrintSparsity (const Epetra_RowMatrix &A, const char *FileName=0, const int NumPDEEqns=1)
Function Documentation
Ifpack_Analyze()
int Ifpack_Analyze (const Epetra_RowMatrix & A, const bool Cheap = false, const int NumPDEEqns = 1)
Analyzes the basic properties of the input matrix A; see Usage of Ifpack_Analyze()..
Definition at line 418 of file Ifpack_Utils.cpp.
References Epetra_MultiVector::Abs(), Epetra_Operator::Comm(), Copy, Epetra_RowMatrix::ExtractMyRowCopy(), Epetra_CrsMatrix::FillComplete(), Epetra_BlockMap::GID(), Epetra_BlockMap::GlobalIndicesInt(), Epetra_BlockMap::GlobalIndicesLongLong(), Epetra_MultiVector::GlobalLength64(), Epetra_FECrsMatrix::InsertGlobalValues(), Epetra_Operator::Label(), Epetra_Comm::MaxAll(), Epetra_RowMatrix::MaxNumEntries(), Epetra_MultiVector::MaxValue(), Epetra_MultiVector::MeanValue(), Epetra_Comm::MinAll(), Epetra_MultiVector::MinValue(), Epetra_MultiVector::MyLength(), Epetra_Comm::MyPID(), Epetra_CrsMatrix::NormInf(), Epetra_RowMatrix::NormInf(), Epetra_CrsMatrix::NormOne(), Epetra_RowMatrix::NormOne(), Epetra_RowMatrix::NumMyRows(), Epetra_MultiVector::PutScalar(), Epetra_RowMatrix::RowMatrixColMap(), Epetra_RowMatrix::RowMatrixRowMap(), Epetra_CrsMatrix::Scale(), Epetra_Comm::SumAll(), and Epetra_FECrsMatrix::SumIntoGlobalValues().
Ifpack_AnalyzeMatrixElements()
int Ifpack_AnalyzeMatrixElements (const Epetra_RowMatrix & A, const bool abs = false, const int steps = 10)
Analyzes the distribution of values of the input matrix A.
Parameters
A - (In) matrix to be analyzed.
abs - (In) if true, the function will analyze matrix B, whose elements are defined as \(B_{i,i} = | A_{i,i}| \).
steps - (In) number of intervals for the analysis.
An example of output is reported Usage of Ifpack_AnalyzeMatrixElements().
Definition at line 900 of file Ifpack_Utils.cpp.
References Epetra_Operator::Comm(), Epetra_RowMatrix::ExtractMyRowCopy(), Epetra_Operator::Label(), Epetra_RowMatrix::MaxNumEntries(), Epetra_Comm::MyPID(), Epetra_RowMatrix::NumMyRows(), and Epetra_Comm::SumAll().
Ifpack_AnalyzeVectorElements()
int Ifpack_AnalyzeVectorElements (const Epetra_Vector & Diagonal, const bool abs = false, const int steps = 10)
Analyzes the distribution of values of the input vector Diagonal.
Parameters
Diagonal - (In) Vector to be analyzed.
abs - (In) if true, the function will analyze vector B, whose elements are defined as \(B_{i} = | D_{i}| \).
steps - (In) number of intervals for the analysis.
An example of output is reported Usage of Ifpack_AnalyzeVectorElements().
Definition at line 841 of file Ifpack_Utils.cpp.
References Epetra_DistObject::Comm(), Epetra_MultiVector::GlobalLength64(), Epetra_Object::Label(), Epetra_MultiVector::MyLength(), Epetra_Comm::MyPID(), and Epetra_Comm::SumAll().
Ifpack_BreakForDebugger()
void Ifpack_BreakForDebugger (Epetra_Comm & Comm)
Stops the execution of code, so that a debugger can be attached.
Definition at line 61 of file Ifpack_Utils.cpp.
References Epetra_Comm::Barrier(), Epetra_Comm::MyPID(), and Epetra_Comm::NumProc().
Ifpack_CreateOverlappingCrsMatrix() [1/2]
Epetra_CrsGraph * Ifpack_CreateOverlappingCrsMatrix (const Epetra_CrsGraph * Graph, const int OverlappingLevel)
Creates an overlapping Epetra_CrsGraph. Returns 0 if OverlappingLevel is 0.
Definition at line 182 of file Ifpack_Utils.cpp.
References Copy, Epetra_CrsGraph::FillComplete(), Epetra_DistObject::Import(), Epetra_CrsGraph::Importer(), Insert, and Epetra_Import::TargetMap().
Ifpack_CreateOverlappingCrsMatrix() [2/2]
Epetra_CrsMatrix * Ifpack_CreateOverlappingCrsMatrix (const Epetra_RowMatrix * Matrix, const int OverlappingLevel)
Creates an overlapping Epetra_CrsMatrix. Returns 0 if OverlappingLevel is 0.
Definition at line 102 of file Ifpack_Utils.cpp.
References Epetra_Operator::Comm(), Copy, Epetra_CrsMatrix::FillComplete(), Epetra_BlockMap::GlobalIndicesInt(), Epetra_BlockMap::GlobalIndicesLongLong(), Epetra_DistObject::Import(), Insert, Epetra_BlockMap::MyGlobalElements(), Epetra_BlockMap::NumMyElements(), Epetra_Comm::NumProc(), Epetra_Operator::OperatorDomainMap(), Epetra_Operator::OperatorRangeMap(), Epetra_RowMatrix::RowMatrixImporter(), Epetra_RowMatrix::RowMatrixRowMap(), and Epetra_Import::TargetMap().
Ifpack_PrintLine()
void Ifpack_PrintLine ()
Prints a line of ‘=’ on cout.
Definition at line 55 of file Ifpack_Utils.cpp.
Ifpack_PrintResidual() [1/2]
int Ifpack_PrintResidual (char * Label, const Epetra_RowMatrix & A, const Epetra_MultiVector & X, const Epetra_MultiVector & Y)
Prints on cout the true residual.
Definition at line 258 of file Ifpack_Utils.cpp.
References Epetra_DistObject::Comm(), and Epetra_Comm::MyPID().
Ifpack_PrintResidual() [2/2]
int Ifpack_PrintResidual (const int iter, const Epetra_RowMatrix & A, const Epetra_MultiVector & X, const Epetra_MultiVector & Y)
Definition at line 273 of file Ifpack_Utils.cpp.
Ifpack_PrintSparsity()
int Ifpack_PrintSparsity (const Epetra_RowMatrix & A, const char * FileName = 0, const int NumPDEEqns = 1)
Definition at line 975 of file Ifpack_Utils.cpp.
Ifpack_PrintSparsity_Simple()
void Ifpack_PrintSparsity_Simple (const Epetra_RowMatrix & A)
Definition at line 299 of file Ifpack_Utils.cpp.
Ifpack_toString() [1/2]
std::string Ifpack_toString (const double & x)
Converts a double to std::string.
Definition at line 250 of file Ifpack_Utils.cpp.
Ifpack_toString() [2/2]
std::string Ifpack_toString (const int & x)
Converts an integer to std::string.
Definition at line 242 of file Ifpack_Utils.cpp.