Galeri: Galeri::core::Object Class Reference
Galeri::core::Object Class Reference
Basic class for all Galeri/pfem objects.
#include <Galeri_core_Object.h>
Public Member Functions
Object (const std::string &Label="Galeri::core::Object", const int ID=0)
Object (const Object &rhs)
Copy constructor.
Object & operator= (const Object &rhs)
Copies the object from rhs.
virtual void setLabel (const std::string &label)
Sets the label associated with this object.
virtual std::string getLabel () const
Gets the label associated with this object.
virtual void setID (const int &ID)
Sets the ID associated with this object.
virtual int getID () const
Gets the ID associated with this object.
virtual void print (ostream &os) const
Prints Object to the specified output stream.
Detailed Description
Basic class for all Galeri/pfem objects.
Constructor & Destructor Documentation
Object()
Galeri::core::Object::Object (const std::string & Label = "Galeri::core::Object", const int ID = 0) inline
ctor, dtor, and operator = Constructor with specified label and ID.
References setID(), and setLabel().
Member Function Documentation
print()
virtual void Galeri::core::Object::print (ostream & os) const inline virtual
Prints Object to the specified output stream.
Other Methods
To be customized by derived classes. Operator << uses this method. Default implementation prints the object label to os.
Reimplemented in Galeri::grid::Element, Galeri::grid::Loadable, and Galeri::quadrature::Element.
References getID(), and getLabel().
setLabel()
virtual void Galeri::core::Object::setLabel (const std::string & label) inline virtual
Sets the label associated with this object.
Set and Get Methods
Referenced by Galeri::grid::Element::Element(), Object(), Object(), Galeri::grid::Element::operator=(), operator=(), and Galeri::grid::Point::Point().
The documentation for this class was generated from the following file:
Galeri_core_Object.h