Galeri: Galeri::FiniteElements::AbstractVariational Class Reference
Galeri::FiniteElements::AbstractVariational Class Reference abstract
Pure virtual class that defines the variational form.
#include <Galeri_AbstractVariational.h>
Public Member Functions
virtual ~AbstractVariational ()
Destructor.
virtual double LHS (const double Phi, const double Psi, const double PhiX, const double PsiX, const double PhiY, const double PsiY, const double PhiZ, const double PsiZ, const double x, const double y, const double z) const =0
Evaluates the bilinear form (without integral) at point (x,y,z).
virtual double RHS (const double Psi, const double PsiX, const double PsiY, const double PsiZ, const double x, const double y, const double z) const =0
Returns the value of the right-hand side (without integral) at point (x, y, z).
virtual int BC (const int PatchID) const =0
Returns an integer identifying the boundary condition assigned to the specified patch.
virtual double BC (const double x, const double y, const double z, const int PatchID) const =0
Returns the value of the boundary condition at point (x, y, z).
virtual int IntegrateOverElement (const AbstractVariational &Variational, const double *x, const double *y, const double *z, const double *data, double *ElementMatrix, double *ElementRHS) const =0
Integrates the bilinear form and the right-hand side over the element.
virtual int ElementNorm (const double *LocalSol, const double *x, const double *y, const double *z, double *Norm) const =0
Computes the norm of the computed solution over the element.
virtual int ElementNorm (int(*ExactSolution)(double, double, double, double *), const double *x, const double *y, const double *z, double *Norm) const =0
Computed the norm of the exact solution over the element.
virtual int ElementNorm (const double *LocalSol, int(*ExactSolution)(double, double, double, double *), const double *x, const double *y, const double *z, double *Norm) const =0
Computed the norm of the computed and exact solution over the element.
Detailed Description
Pure virtual class that defines the variational form.
AbstractVariational is a pure virtual class, that specifies a set of abstract interfaces, required to integrate the variational form and the right-hand side over an element, and to compute the norm of compute solution, exact solution, and error over the element. A concrete implementation of this class also defined how boundary conditions are resolved.
The element on which the integration is performed is specified by providing the coordinates of the local vertices.
Author
Marzio Sala, SNL 9214.
Date
Last updated on Apr-05.
Member Function Documentation
BC() [1/2]
virtual double Galeri::FiniteElements::AbstractVariational::BC (const double x, const double y, const double z, const int PatchID) const pure virtual
Returns the value of the boundary condition at point (x, y, z).
Implemented in Galeri::FiniteElements::SUPGVariational< T >, and Galeri::FiniteElements::GalerkinVariational< T >.
BC() [2/2]
virtual int Galeri::FiniteElements::AbstractVariational::BC (const int PatchID) const pure virtual
Returns an integer identifying the boundary condition assigned to the specified patch.
Implemented in Galeri::FiniteElements::GalerkinVariational< T >, and Galeri::FiniteElements::SUPGVariational< T >.
Referenced by Galeri::FiniteElements::LinearProblem::Compute().
ElementNorm() [1/3]
virtual int Galeri::FiniteElements::AbstractVariational::ElementNorm (const double * LocalSol, const double * x, const double * y, const double * z, double * Norm) const pure virtual
Computes the norm of the computed solution over the element.
Implemented in Galeri::FiniteElements::GalerkinVariational< T >, and Galeri::FiniteElements::SUPGVariational< T >.
Referenced by Galeri::FiniteElements::LinearProblem::ComputeNorms().
ElementNorm() [2/3]
virtual int Galeri::FiniteElements::AbstractVariational::ElementNorm (const double * LocalSol, int(*)(double, double, double, double *) ExactSolution, const double * x, const double * y, const double * z, double * Norm) const pure virtual
Computed the norm of the computed and exact solution over the element.
Implemented in Galeri::FiniteElements::GalerkinVariational< T >, and Galeri::FiniteElements::SUPGVariational< T >.
ElementNorm() [3/3]
virtual int Galeri::FiniteElements::AbstractVariational::ElementNorm (int(*)(double, double, double, double *) ExactSolution, const double * x, const double * y, const double * z, double * Norm) const pure virtual
Computed the norm of the exact solution over the element.
Implemented in Galeri::FiniteElements::GalerkinVariational< T >, and Galeri::FiniteElements::SUPGVariational< T >.
IntegrateOverElement()
virtual int Galeri::FiniteElements::AbstractVariational::IntegrateOverElement (const AbstractVariational & Variational, const double * x, const double * y, const double * z, const double * data, double * ElementMatrix, double * ElementRHS) const pure virtual
Integrates the bilinear form and the right-hand side over the element.
Implemented in Galeri::FiniteElements::GalerkinVariational< T >, and Galeri::FiniteElements::SUPGVariational< T >.
Referenced by Galeri::FiniteElements::LinearProblem::Compute().
LHS()
virtual double Galeri::FiniteElements::AbstractVariational::LHS (const double Phi, const double Psi, const double PhiX, const double PsiX, const double PhiY, const double PsiY, const double PhiZ, const double PsiZ, const double x, const double y, const double z) const pure virtual
Evaluates the bilinear form (without integral) at point (x,y,z).
Implemented in Galeri::FiniteElements::GalerkinVariational< T >, and Galeri::FiniteElements::SUPGVariational< T >.
Referenced by Galeri::FiniteElements::GalerkinVariational< T >::IntegrateOverElement(), and Galeri::FiniteElements::SUPGVariational< T >::IntegrateOverElement().
RHS()
virtual double Galeri::FiniteElements::AbstractVariational::RHS (const double Psi, const double PsiX, const double PsiY, const double PsiZ, const double x, const double y, const double z) const pure virtual
Returns the value of the right-hand side (without integral) at point (x, y, z).
Implemented in Galeri::FiniteElements::GalerkinVariational< T >, and Galeri::FiniteElements::SUPGVariational< T >.
Referenced by Galeri::FiniteElements::GalerkinVariational< T >::IntegrateOverElement(), and Galeri::FiniteElements::SUPGVariational< T >::IntegrateOverElement().
The documentation for this class was generated from the following file:
Galeri_AbstractVariational.h