Galeri: Galeri::FiniteElements::MEDITInterface Class Reference
Galeri::FiniteElements::MEDITInterface Class Reference
Public Member Functions
MEDITInterface (Epetra_Comm &Comm)
const Epetra_Comm & Comm () const
void Write (const AbstractGrid &data, const std::string &BaseName, const Epetra_MultiVector &Field)
Member Function Documentation
Write()
void Galeri::FiniteElements::MEDITInterface::Write (const AbstractGrid & data, const std::string & BaseName, const Epetra_MultiVector & Field) inline
int zzz = data.NumMyVertices();
References Galeri::FiniteElements::AbstractGrid::ElementType(), Galeri::FiniteElements::AbstractGrid::ElementVertices(), Galeri::FiniteElements::AbstractGrid::NumDimensions(), Galeri::FiniteElements::AbstractGrid::NumGlobalElements(), Galeri::FiniteElements::AbstractGrid::NumGlobalVertices(), Galeri::FiniteElements::AbstractGrid::NumMyElements(), Galeri::FiniteElements::AbstractGrid::NumMyVertices(), Galeri::FiniteElements::AbstractGrid::NumVerticesPerElement(), Galeri::FiniteElements::AbstractGrid::RowMap(), Galeri::FiniteElements::AbstractGrid::VertexCoord(), and Galeri::FiniteElements::AbstractGrid::VertexMap().
The documentation for this class was generated from the following file:
Galeri_MEDITInterface.h