TriUtils: Trilinos_Util_ReadHb2Epetra.cpp File Reference
Trilinos_Util_ReadHb2Epetra.cpp File Reference
#include "Trilinos_Util.h"
#include "Trilinos_Util_iohb.h"
#include "Epetra_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "Epetra_Map.h"
#include "Epetra_Vector.h"
#include "Epetra_CrsMatrix.h"
#include <vector>
#include <algorithm>
Functions
void Trilinos_Util_ReadHb2Epetra_internal (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact, bool FakeLongLong)
void Trilinos_Util_ReadHb2Epetra (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
void Trilinos_Util_ReadHb2Epetra64 (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
Function Documentation
Trilinos_Util_ReadHb2Epetra()
void Trilinos_Util_ReadHb2Epetra (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
References Trilinos_Util_ReadHb2Epetra_internal().
Referenced by Trilinos_Util::CrsMatrixGallery::TReadMatrix().
Trilinos_Util_ReadHb2Epetra64()
void Trilinos_Util_ReadHb2Epetra64 (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
References Trilinos_Util_ReadHb2Epetra_internal().
Referenced by Trilinos_Util::CrsMatrixGallery::TReadMatrix().
Trilinos_Util_ReadHb2Epetra_internal()
void Trilinos_Util_ReadHb2Epetra_internal (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact, bool FakeLongLong)
References Epetra_Comm::Broadcast(), Copy, Epetra_CrsMatrix::FillComplete(), Epetra_CrsMatrix::InsertGlobalValues(), Epetra_CrsMatrix::Multiply(), Epetra_Comm::MyPID(), Epetra_MultiVector::Norm2(), readHB_aux_double(), readHB_header(), readHB_mat_double(), Trilinos_Util_csrcsc(), Trilinos_Util_scscmv(), Trilinos_Util_scscres(), Trilinos_Util_ssrcsr(), and Epetra_MultiVector::Update().
Referenced by Trilinos_Util_ReadHb2Epetra(), and Trilinos_Util_ReadHb2Epetra64().