TriUtils: Trilinos_Util_iohb.cpp File Reference
Trilinos_Util_iohb.cpp File Reference
#include "Trilinos_Util_iohb.h"
#include <cstring>
#include <cmath>
#include <cstdlib>
#include <cctype>
Macros
#define _SP_base 1
Functions
char * substr (const char *S, const int pos, const int len)
void upcase (char *S)
void IOHBTerminate (const char *message)
int readHB_info (const char *filename, int *M, int *N, int *nz, char **Type, int *Nrhs)
int readHB_header (std::FILE *in_file, char *Title, char *Key, char *Type, int *Nrow, int *Ncol, int *Nnzero, int *Nrhs, char *Ptrfmt, char *Indfmt, char *Valfmt, char *Rhsfmt, int *Ptrcrd, int *Indcrd, int *Valcrd, int *Rhscrd, char *Rhstype)
int readHB_mat_double (const char *filename, int colptr[], int rowind[], double val[])
int readHB_newmat_double (const char *filename, int *M, int *N, int *nonzeros, int **colptr, int **rowind, double **val)
int readHB_aux_double (const char *filename, const char AuxType, double b[])
int readHB_newaux_double (const char *filename, const char AuxType, double **b)
int writeHB_mat_double (const char *filename, int M, int N, int nz, const int colptr[], const int rowind[], const double val[], int Nrhs, const double rhs[], const double guess[], const double exact[], const char *Title, const char *Key, const char *Type, char *Ptrfmt, char *Indfmt, char *Valfmt, char *Rhsfmt, const char *Rhstype)
int readHB_mat_char (const char *filename, int colptr[], int rowind[], char val[], char *Valfmt)
int readHB_newmat_char (const char *filename, int *M, int *N, int *nonzeros, int **colptr, int **rowind, char **val, char **Valfmt)
int readHB_aux_char (const char *filename, const char AuxType, char b[])
int readHB_newaux_char (const char *filename, const char AuxType, char **b, char **Rhsfmt)
int writeHB_mat_char (const char *filename, int M, int N, int nz, const int colptr[], const int rowind[], const char val[], int Nrhs, const char rhs[], const char guess[], const char exact[], const char *Title, const char *Key, const char *Type, char *Ptrfmt, char *Indfmt, char *Valfmt, char *Rhsfmt, const char *Rhstype)
int ParseIfmt (char *fmt, int *perline, int *width)
int ParseRfmt (char *fmt, int *perline, int *width, int *prec, int *flag)
Macro Definition Documentation
_SP_base
#define _SP_base 1
Function Documentation
IOHBTerminate()
void IOHBTerminate (const char * message)
Referenced by readHB_aux_char(), readHB_aux_double(), readHB_header(), readHB_info(), readHB_mat_char(), readHB_mat_double(), readHB_newaux_char(), readHB_newaux_double(), readHB_newmat_char(), readHB_newmat_double(), and substr().
ParseIfmt()
int ParseIfmt (char * fmt, int * perline, int * width)
References substr(), and upcase().
Referenced by readHB_mat_char(), readHB_mat_double(), writeHB_mat_char(), and writeHB_mat_double().
ParseRfmt()
int ParseRfmt (char * fmt, int * perline, int * width, int * prec, int * flag)
References substr(), and upcase().
Referenced by readHB_aux_char(), readHB_aux_double(), readHB_mat_char(), readHB_mat_double(), readHB_newaux_char(), readHB_newmat_char(), writeHB_mat_char(), and writeHB_mat_double().
readHB_aux_char()
int readHB_aux_char (const char * filename, const char AuxType, char b[])
References IOHBTerminate(), ParseRfmt(), and readHB_header().
Referenced by readHB_newaux_char().
readHB_aux_double()
int readHB_aux_double (const char * filename, const char AuxType, double b[])
References IOHBTerminate(), ParseRfmt(), and readHB_header().
Referenced by readHB_newaux_double(), Trilinos_Util_read_hb(), and Trilinos_Util_ReadHb2Epetra_internal().
readHB_header()
int readHB_header (std::FILE * in_file, char * Title, char * Key, char * Type, int * Nrow, int * Ncol, int * Nnzero, int * Nrhs, char * Ptrfmt, char * Indfmt, char * Valfmt, char * Rhsfmt, int * Ptrcrd, int * Indcrd, int * Valcrd, int * Rhscrd, char * Rhstype)
References IOHBTerminate(), and upcase().
Referenced by readHB_aux_char(), readHB_aux_double(), readHB_info(), readHB_mat_char(), readHB_mat_double(), readHB_newaux_char(), readHB_newmat_char(), Trilinos_Util_read_hb(), Trilinos_Util_read_hb(), and Trilinos_Util_ReadHb2Epetra_internal().
readHB_info()
int readHB_info (const char * filename, int * M, int * N, int * nz, char ** Type, int * Nrhs)
References IOHBTerminate(), and readHB_header().
Referenced by readHB_newaux_double(), and readHB_newmat_double().
readHB_mat_char()
int readHB_mat_char (const char * filename, int colptr[], int rowind[], char val[], char * Valfmt)
References _SP_base, IOHBTerminate(), ParseIfmt(), ParseRfmt(), and readHB_header().
Referenced by readHB_newmat_char().
readHB_mat_double()
int readHB_mat_double (const char * filename, int colptr[], int rowind[], double val[])
References _SP_base, IOHBTerminate(), ParseIfmt(), ParseRfmt(), and readHB_header().
Referenced by readHB_newmat_double(), Trilinos_Util_read_hb(), Trilinos_Util_read_hb(), and Trilinos_Util_ReadHb2Epetra_internal().
readHB_newaux_char()
int readHB_newaux_char (const char * filename, const char AuxType, char ** b, char ** Rhsfmt)
References IOHBTerminate(), ParseRfmt(), readHB_aux_char(), and readHB_header().
readHB_newaux_double()
int readHB_newaux_double (const char * filename, const char AuxType, double ** b)
References IOHBTerminate(), readHB_aux_double(), and readHB_info().
readHB_newmat_char()
int readHB_newmat_char (const char * filename, int * M, int * N, int * nonzeros, int ** colptr, int ** rowind, char ** val, char ** Valfmt)
References IOHBTerminate(), ParseRfmt(), readHB_header(), and readHB_mat_char().
readHB_newmat_double()
int readHB_newmat_double (const char * filename, int * M, int * N, int * nonzeros, int ** colptr, int ** rowind, double ** val)
References IOHBTerminate(), readHB_info(), and readHB_mat_double().
substr()
char * substr (const char * S, const int pos, const int len)
References IOHBTerminate().
Referenced by ParseIfmt(), and ParseRfmt().
upcase()
void upcase (char * S)
Referenced by ParseIfmt(), ParseRfmt(), and readHB_header().
writeHB_mat_char()
int writeHB_mat_char (const char * filename, int M, int N, int nz, const int colptr[], const int rowind[], const char val[], int Nrhs, const char rhs[], const char guess[], const char exact[], const char * Title, const char * Key, const char * Type, char * Ptrfmt, char * Indfmt, char * Valfmt, char * Rhsfmt, const char * Rhstype)
References _SP_base, ParseIfmt(), and ParseRfmt().
writeHB_mat_double()
int writeHB_mat_double (const char * filename, int M, int N, int nz, const int colptr[], const int rowind[], const double val[], int Nrhs, const double rhs[], const double guess[], const double exact[], const char * Title, const char * Key, const char * Type, char * Ptrfmt, char * Indfmt, char * Valfmt, char * Rhsfmt, const char * Rhstype)
References _SP_base, ParseIfmt(), and ParseRfmt().