TriUtils: Trilinos_Util.h File Reference
Trilinos_Util.h File Reference
#include "Triutils_config.h"
#include <stdlib.h>
#include <stdio.h>
#include <iostream.h>
#include <string.h>
#include <math.h>
#include <map.h>
Classes
struct SPBLASMAT_STRUCT
Macros
#define Trilinos_Util_max(x, y) ((x > y) ? x : y) /* max function */
#define Trilinos_Util_min(x, y) ((x < y) ? x : y) /* min function */
#define MAXNRHS 1
Typedefs
typedef struct SPBLASMAT_STRUCT SPBLASMAT
Functions
void Trilinos_Util_read_hb (const char *data_file, int MyPID, int *N_global, int *n_nonzeros, double **val, int **bindx, double **x, double **b, double **xexact)
void Trilinos_Util_read_hb (const char *data_file, int MyPID, int *N_global, int *n_nonzeros, double **val, int **bindx)
void Trilinos_Util_read_coo (const char *data_file, int MyPID, int *N_global, int *n_nonzeros, double **val, int **bindx, double **x, double **b, double **xexact)
double Trilinos_Util_smsrres (int m, int n, double *val, int *indx, double *xlocal, double *x, double *b)
double Trilinos_Util_scscres (int isym, int m, int n, double *val, int *indx, int *pntr, double *x, double *b)
void Trilinos_Util_scscmv (int isym, int m, int n, double *val, int *indx, int *pntr, double *x, double *b)
double Trilinos_Util_svbrres (int m, int n, int m_blk, double *val, int *indx, int *bindx, int *rpntr, int *cpntr, int *bpntrb, int *bpntre, double *x, double *b)
void Trilinos_Util_msr2vbr (double val[], int indx[], int rnptr[], int cnptr[], int bnptr[], int bindx[], int msr_bindx[], double msr_val[], int total_blk_rows, int total_blk_cols, int blk_space, int nz_space, int blk_type)
int Trilinos_Util_find_block_col (int cnptr[], int column, int max_blocks, int blk_size)
int Trilinos_Util_find_block_in_row (int bindx[], int bnptr[], int blk_row, int blk_col, int indx[], int no_elements, double val[], int blk_space, int nz_space)
void Trilinos_Util_add_new_ele (int cnptr[], int col, int blk_row, int bindx[], int bnptr[], int indx[], double val[], int row, double new_ele, int maxcols, int blk_space, int nz_space, int blk_type)
int Trilinos_Util_find_closest_not_larger (int key, int list[], int length)
void Trilinos_Util_convert_values_to_ptrs (int array[], int length, int start)
int Trilinos_Util_csrcsc (int n, int n2, int job, int ipos, double *a, int *ja, int *ia, double *ao, int *jao, int *iao)
int Trilinos_Util_csrmsr (int n, double *a, int *ja, int *ia, double *ao, int *jao, double *wk, int *iwk)
int Trilinos_Util_ssrcsr (int job, int value2, int nrow, double *a, int *ja, int *ia, int nzmax, double *ao, int *jao, int *iao, int *indu, int *iwk)
int Trilinos_Util_coocsr (int nrow, int nnz, double *a, int *ir, int *jc, double *ao, int *jao, int *iao)
void Trilinos_Util_duscr_vbr (int n, double *val, int *indx, int *bindx, int *rpntr, int *cpntr, int *bpntrb, int *bpntre, SPBLASMAT *A)
void Trilinos_Util_dusmm (int m, int nrhs, int k, double alpha, SPBLASMAT *A, double *x, int xstride, double beta, double *b, int bstride)
void Trilinos_Util_dusds_vbr (SPBLASMAT *A)
void Trilinos_Util_write_vec (const char *filename, int n_equations, double *x)
void Trilinos_Util_read_vec (const char *filename, int n_equations, double *x)
Macro Definition Documentation
MAXNRHS
#define MAXNRHS 1
Trilinos_Util_max
#define Trilinos_Util_max (x, y) ((x > y) ? x : y) /* max function */
Trilinos_Util_min
#define Trilinos_Util_min (x, y) ((x < y) ? x : y) /* min function */
Typedef Documentation
SPBLASMAT
typedef struct SPBLASMAT_STRUCT SPBLASMAT
Function Documentation
Trilinos_Util_add_new_ele()
void Trilinos_Util_add_new_ele (int cnptr[], int col, int blk_row, int bindx[], int bnptr[], int indx[], double val[], int row, double new_ele, int maxcols, int blk_space, int nz_space, int blk_type)
References Trilinos_Util_find_block_col(), and Trilinos_Util_find_block_in_row().
Referenced by Trilinos_Util_msr2vbr().
Trilinos_Util_convert_values_to_ptrs()
void Trilinos_Util_convert_values_to_ptrs (int array[], int length, int start)
Referenced by Trilinos_Util_msr2vbr().
Trilinos_Util_coocsr()
int Trilinos_Util_coocsr (int nrow, int nnz, double * a, int * ir, int * jc, double * ao, int * jao, int * iao)
Referenced by Trilinos_Util_read_coo().
Trilinos_Util_csrcsc()
int Trilinos_Util_csrcsc (int n, int n2, int job, int ipos, double * a, int * ja, int * ia, double * ao, int * jao, int * iao)
Referenced by Trilinos_Util_read_coo(), Trilinos_Util_read_hb(), Trilinos_Util_read_hb(), and Trilinos_Util_ReadHb2Epetra_internal().
Trilinos_Util_csrmsr()
int Trilinos_Util_csrmsr (int n, double * a, int * ja, int * ia, double * ao, int * jao, double * wk, int * iwk)
Referenced by Trilinos_Util_read_coo(), Trilinos_Util_read_hb(), and Trilinos_Util_read_hb().
Trilinos_Util_duscr_vbr()
void Trilinos_Util_duscr_vbr (int n, double * val, int * indx, int * bindx, int * rpntr, int * cpntr, int * bpntrb, int * bpntre, SPBLASMAT * A)
References SPBLASMAT_STRUCT::bindx, SPBLASMAT_STRUCT::bpntrb, SPBLASMAT_STRUCT::bpntre, SPBLASMAT_STRUCT::buffer, SPBLASMAT_STRUCT::buffersize, SPBLASMAT_STRUCT::bufferstride, SPBLASMAT_STRUCT::cpntr, SPBLASMAT_STRUCT::indx, SPBLASMAT_STRUCT::maxblocksize, MAXNRHS, SPBLASMAT_STRUCT::minblocksize, SPBLASMAT_STRUCT::n, SPBLASMAT_STRUCT::ncolvec, SPBLASMAT_STRUCT::nops_per_rhs, SPBLASMAT_STRUCT::rpntr, Trilinos_Util_max, Trilinos_Util_min, and SPBLASMAT_STRUCT::val.
Referenced by Trilinos_Util_svbrres().
Trilinos_Util_dusds_vbr()
void Trilinos_Util_dusds_vbr (SPBLASMAT * A)
References SPBLASMAT_STRUCT::buffer, and SPBLASMAT_STRUCT::ncolvec.
Referenced by Trilinos_Util_svbrres().
Trilinos_Util_dusmm()
void Trilinos_Util_dusmm (int m, int nrhs, int k, double alpha, SPBLASMAT * A, double * x, int xstride, double beta, double * b, int bstride)
References SPBLASMAT_STRUCT::bindx, SPBLASMAT_STRUCT::bpntrb, SPBLASMAT_STRUCT::bpntre, SPBLASMAT_STRUCT::buffer, SPBLASMAT_STRUCT::cpntr, Epetra_BLAS::GEMM(), SPBLASMAT_STRUCT::indx, SPBLASMAT_STRUCT::maxblocksize, MAXNRHS, SPBLASMAT_STRUCT::minblocksize, SPBLASMAT_STRUCT::ncolvec, SPBLASMAT_STRUCT::rpntr, Trilinos_Util_min, and SPBLASMAT_STRUCT::val.
Referenced by Trilinos_Util_svbrres().
Trilinos_Util_find_block_col()
int Trilinos_Util_find_block_col (int cnptr[], int column, int max_blocks, int blk_size)
References Trilinos_Util_find_closest_not_larger().
Referenced by Trilinos_Util_add_new_ele().
Trilinos_Util_find_block_in_row()
int Trilinos_Util_find_block_in_row (int bindx[], int bnptr[], int blk_row, int blk_col, int indx[], int no_elements, double val[], int blk_space, int nz_space)
Referenced by Trilinos_Util_add_new_ele().
Trilinos_Util_find_closest_not_larger()
int Trilinos_Util_find_closest_not_larger (int key, int list[], int length)
Referenced by Trilinos_Util_find_block_col().
Trilinos_Util_msr2vbr()
void Trilinos_Util_msr2vbr (double val[], int indx[], int rnptr[], int cnptr[], int bnptr[], int bindx[], int msr_bindx[], double msr_val[], int total_blk_rows, int total_blk_cols, int blk_space, int nz_space, int blk_type)
References Trilinos_Util_add_new_ele(), and Trilinos_Util_convert_values_to_ptrs().
Referenced by Trilinos_Util_create_vbr().
Trilinos_Util_read_coo()
void Trilinos_Util_read_coo (const char * data_file, int MyPID, int * N_global, int * n_nonzeros, double ** val, int ** bindx, double ** x, double ** b, double ** xexact)
References Trilinos_Util_coocsr(), Trilinos_Util_csrcsc(), Trilinos_Util_csrmsr(), and Trilinos_Util_max.
Trilinos_Util_read_hb() [1/2]
void Trilinos_Util_read_hb (const char * data_file, int MyPID, int * N_global, int * n_nonzeros, double ** val, int ** bindx)
References readHB_header(), readHB_mat_double(), TEUCHOS_TEST_FOR_EXCEPT_MSG, Trilinos_Util_csrcsc(), Trilinos_Util_csrmsr(), and Trilinos_Util_ssrcsr().
Trilinos_Util_read_hb() [2/2]
void Trilinos_Util_read_hb (const char * data_file, int MyPID, int * N_global, int * n_nonzeros, double ** val, int ** bindx, double ** x, double ** b, double ** xexact)
References readHB_aux_double(), readHB_header(), readHB_mat_double(), TEUCHOS_TEST_FOR_EXCEPT_MSG, Trilinos_Util_csrcsc(), Trilinos_Util_csrmsr(), Trilinos_Util_scscmv(), Trilinos_Util_scscres(), Trilinos_Util_smsrres(), and Trilinos_Util_ssrcsr().
Referenced by Trilinos_Util_ReadHb2EpetraVbr().
Trilinos_Util_read_vec()
void Trilinos_Util_read_vec (const char * filename, int n_equations, double * x)
Trilinos_Util_scscmv()
void Trilinos_Util_scscmv (int isym, int m, int n, double * val, int * indx, int * pntr, double * x, double * b)
Referenced by Trilinos_Util_read_hb(), and Trilinos_Util_ReadHb2Epetra_internal().
Trilinos_Util_scscres()
double Trilinos_Util_scscres (int isym, int m, int n, double * val, int * indx, int * pntr, double * x, double * b)
References Trilinos_Util_max.
Referenced by Trilinos_Util_read_hb(), and Trilinos_Util_ReadHb2Epetra_internal().
Trilinos_Util_smsrres()
double Trilinos_Util_smsrres (int m, int n, double * val, int * indx, double * xlocal, double * x, double * b)
References Trilinos_Util_max.
Referenced by Trilinos_Util_distrib_msr_matrix(), and Trilinos_Util_read_hb().
Trilinos_Util_ssrcsr()
int Trilinos_Util_ssrcsr (int job, int value2, int nrow, double * a, int * ja, int * ia, int nzmax, double * ao, int * jao, int * iao, int * indu, int * iwk)
Referenced by Trilinos_Util_read_hb(), Trilinos_Util_read_hb(), and Trilinos_Util_ReadHb2Epetra_internal().
Trilinos_Util_svbrres()
double Trilinos_Util_svbrres (int m, int n, int m_blk, double * val, int * indx, int * bindx, int * rpntr, int * cpntr, int * bpntrb, int * bpntre, double * x, double * b)
References Trilinos_Util_duscr_vbr(), Trilinos_Util_dusds_vbr(), Trilinos_Util_dusmm(), and Trilinos_Util_max.
Referenced by Trilinos_Util_distrib_vbr_matrix().
Trilinos_Util_write_vec()
void Trilinos_Util_write_vec (const char * filename, int n_equations, double * x)