TriUtils: Trilinos_Util_ReadMatrixMarket2Epetra.h File Reference
Trilinos_Util_ReadMatrixMarket2Epetra.h File Reference
#include "Epetra_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "Epetra_Map.h"
#include "Epetra_Vector.h"
Functions
template<typename int_type >
int Trilinos_Util_ReadMatrixMarket2Epetra_internal (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
int Trilinos_Util_ReadMatrixMarket2Epetra (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
int Trilinos_Util_ReadMatrixMarket2Epetra64 (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
Function Documentation
Trilinos_Util_ReadMatrixMarket2Epetra()
int Trilinos_Util_ReadMatrixMarket2Epetra (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
Referenced by Trilinos_Util::CrsMatrixGallery::TReadMatrix().
Trilinos_Util_ReadMatrixMarket2Epetra64()
int Trilinos_Util_ReadMatrixMarket2Epetra64 (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
Referenced by Trilinos_Util::CrsMatrixGallery::TReadMatrix().
Trilinos_Util_ReadMatrixMarket2Epetra_internal()
template<typename int_type > int Trilinos_Util_ReadMatrixMarket2Epetra_internal (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
References Copy, Epetra_CrsMatrix::ExtractDiagonalCopy(), Epetra_CrsMatrix::FillComplete(), Epetra_CrsMatrix::InsertGlobalValues(), Epetra_CrsMatrix::Multiply(), Epetra_Comm::MyPID(), Epetra_CrsMatrix::NoDiagonal(), Epetra_MultiVector::PutScalar(), Epetra_MultiVector::Random(), Epetra_CrsMatrix::RowMap(), Epetra_BlockMap::SameAs(), and Trilinos_Util_CountMatrixMarket().