TriUtils: Trilinos_Util_GenerateVbrProblem.cpp File Reference
Trilinos_Util_GenerateVbrProblem.cpp File Reference
#include "Trilinos_Util.h"
#include "Epetra_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "Epetra_BlockMap.h"
#include "Epetra_Map.h"
#include "Epetra_LocalMap.h"
#include "Epetra_Vector.h"
#include "Epetra_IntVector.h"
#include "Epetra_MultiVector.h"
#include "Epetra_VbrMatrix.h"
Functions
void Trilinos_Util_GenerateVbrProblem (int nx, int ny, int npoints, int *xoff, int *yoff, int nsizes, int *sizes, const Epetra_Comm &comm, Epetra_BlockMap *&map, Epetra_VbrMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
void Trilinos_Util_GenerateVbrProblem (int nx, int ny, int npoints, int *xoff, int *yoff, int nsizes, int *sizes, int nrhs, const Epetra_Comm &comm, Epetra_BlockMap *&map, Epetra_VbrMatrix *&A, Epetra_MultiVector *&x, Epetra_MultiVector *&b, Epetra_MultiVector *&xexact)
Function Documentation
Trilinos_Util_GenerateVbrProblem() [1/2]
void Trilinos_Util_GenerateVbrProblem (int nx, int ny, int npoints, int * xoff, int * yoff, int nsizes, int * sizes, const Epetra_Comm & comm, Epetra_BlockMap *& map, Epetra_VbrMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
References Trilinos_Util_GenerateVbrProblem().
Referenced by Trilinos_Util_GenerateVbrProblem().
Trilinos_Util_GenerateVbrProblem() [2/2]
void Trilinos_Util_GenerateVbrProblem (int nx, int ny, int npoints, int * xoff, int * yoff, int nsizes, int * sizes, int nrhs, const Epetra_Comm & comm, Epetra_BlockMap *& map, Epetra_VbrMatrix *& A, Epetra_MultiVector *& x, Epetra_MultiVector *& b, Epetra_MultiVector *& xexact)
References Epetra_VbrMatrix::BeginExtractBlockDiagonalView(), Epetra_VbrMatrix::BeginInsertGlobalValues(), Epetra_BlockMap::Comm(), Copy, Epetra_BlockMap::ElementSize(), Epetra_VbrMatrix::EndSubmitEntries(), Epetra_VbrMatrix::ExtractBlockDiagonalEntryView(), Epetra_VbrMatrix::FillComplete(), Epetra_BlockMap::FirstPointInElementList(), Epetra_BlockMap::GID(), Epetra_BlockMap::IndexBase(), Epetra_VbrMatrix::InvRowSums(), Epetra_VbrMatrix::Multiply(), Epetra_BlockMap::MyGlobalElements(), Epetra_BlockMap::NumMyElements(), Epetra_MultiVector::Random(), Epetra_MultiVector::Reciprocal(), Epetra_VbrMatrix::RowMap(), Epetra_MultiVector::Scale(), Epetra_VbrMatrix::SubmitBlockEntry(), and Epetra_IntVector::Values().