TriUtils: Trilinos_Util_GenerateCrsProblem.cpp File Reference
Trilinos_Util_GenerateCrsProblem.cpp File Reference
#include "Trilinos_Util.h"
#include "Epetra_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "Epetra_Map.h"
#include "Epetra_Vector.h"
#include "Epetra_MultiVector.h"
#include "Epetra_CrsMatrix.h"
Functions
void Trilinos_Util_GenerateCrsProblem (int nx, int ny, int npoints, int *xoff, int *yoff, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact, int indexBase)
void Trilinos_Util_GenerateCrsProblem64 (int nx, int ny, int npoints, int *xoff, int *yoff, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact, long long indexBase)
template<typename int_type >
void TTrilinos_Util_GenerateCrsProblem (int nx, int ny, int npoints, int *xoff, int *yoff, int nrhs, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_MultiVector *&x, Epetra_MultiVector *&b, Epetra_MultiVector *&xexact, int_type indexBase)
void Trilinos_Util_GenerateCrsProblem (int nx, int ny, int npoints, int *xoff, int *yoff, int nrhs, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_MultiVector *&x, Epetra_MultiVector *&b, Epetra_MultiVector *&xexact, int indexBase)
void Trilinos_Util_GenerateCrsProblem64 (int nx, int ny, int npoints, int *xoff, int *yoff, int nrhs, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_MultiVector *&x, Epetra_MultiVector *&b, Epetra_MultiVector *&xexact, long long indexBase)
Function Documentation
Trilinos_Util_GenerateCrsProblem() [1/2]
void Trilinos_Util_GenerateCrsProblem (int nx, int ny, int npoints, int * xoff, int * yoff, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact, int indexBase)
References Trilinos_Util_GenerateCrsProblem().
Referenced by Trilinos_Util_GenerateCrsProblem().
Trilinos_Util_GenerateCrsProblem() [2/2]
void Trilinos_Util_GenerateCrsProblem (int nx, int ny, int npoints, int * xoff, int * yoff, int nrhs, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_MultiVector *& x, Epetra_MultiVector *& b, Epetra_MultiVector *& xexact, int indexBase)
Trilinos_Util_GenerateCrsProblem64() [1/2]
void Trilinos_Util_GenerateCrsProblem64 (int nx, int ny, int npoints, int * xoff, int * yoff, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact, long long indexBase)
References Trilinos_Util_GenerateCrsProblem64().
Referenced by Trilinos_Util_GenerateCrsProblem64().
Trilinos_Util_GenerateCrsProblem64() [2/2]
void Trilinos_Util_GenerateCrsProblem64 (int nx, int ny, int npoints, int * xoff, int * yoff, int nrhs, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_MultiVector *& x, Epetra_MultiVector *& b, Epetra_MultiVector *& xexact, long long indexBase)
TTrilinos_Util_GenerateCrsProblem()
template<typename int_type > void TTrilinos_Util_GenerateCrsProblem (int nx, int ny, int npoints, int * xoff, int * yoff, int nrhs, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_MultiVector *& x, Epetra_MultiVector *& b, Epetra_MultiVector *& xexact, int_type indexBase)
References Copy, Epetra_CrsMatrix::FillComplete(), Epetra_CrsMatrix::InsertGlobalValues(), Epetra_CrsMatrix::Multiply(), Epetra_BlockMap::NumMyElements(), and Epetra_MultiVector::Random().