TriUtils: Trilinos_Util_create_vbr.cpp File Reference
Trilinos_Util_create_vbr.cpp File Reference
#include "Trilinos_Util.h"
#include "Epetra_Comm.h"
Functions
void Trilinos_Util_create_vbr (const Epetra_Comm &Comm, const char *partition_file, int *N_global, int *N_blk_global, int *n_nonzeros, int *n_blk_nonzeros, int *N_update, int **update, int *bindx_msr, double *val_msr, double **val, int **indx, int **rpntr, int **cpntr, int **bpntr, int **bindx)
Function Documentation
Trilinos_Util_create_vbr()
void Trilinos_Util_create_vbr (const Epetra_Comm & Comm, const char * partition_file, int * N_global, int * N_blk_global, int * n_nonzeros, int * n_blk_nonzeros, int * N_update, int ** update, int * bindx_msr, double * val_msr, double ** val, int ** indx, int ** rpntr, int ** cpntr, int ** bpntr, int ** bindx)
References Epetra_Comm::MyPID(), Trilinos_Util_min, and Trilinos_Util_msr2vbr().
Referenced by Trilinos_Util_ReadHb2EpetraVbr().