TriUtils: Trilinos_Util_CountTriples.cpp File Reference
Trilinos_Util_CountTriples.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <vector>
#include "Epetra_ConfigDefs.h"
#include "Epetra_Object.h"
#include "Epetra_Comm.h"
Functions
template<typename int_type >
void Trilinos_Util_CountTriples_internal (const char *data_file, bool symmetric, std::vector< int > &non_zeros, int_type &N_rows, int_type &nnz, const Epetra_Comm &comm, bool TimDavisHeader=false, bool ZeroBased=false)
void Trilinos_Util_CountTriples (const char *data_file, bool symmetric, std::vector< int > &non_zeros, int &N_rows, int &nnz, const Epetra_Comm &comm, bool TimDavisHeader=false, bool ZeroBased=false)
void Trilinos_Util_CountTriples (const char *data_file, bool symmetric, std::vector< int > &non_zeros, long long &N_rows, long long &nnz, const Epetra_Comm &comm, bool TimDavisHeader=false, bool ZeroBased=false)
Function Documentation
Trilinos_Util_CountTriples() [1/2]
void Trilinos_Util_CountTriples (const char * data_file, bool symmetric, std::vector< int > & non_zeros, int & N_rows, int & nnz, const Epetra_Comm & comm, bool TimDavisHeader = false, bool ZeroBased = false)
Referenced by Trilinos_Util_ReadTriples2Epetra_internal().
Trilinos_Util_CountTriples() [2/2]
void Trilinos_Util_CountTriples (const char * data_file, bool symmetric, std::vector< int > & non_zeros, long long & N_rows, long long & nnz, const Epetra_Comm & comm, bool TimDavisHeader = false, bool ZeroBased = false)
Trilinos_Util_CountTriples_internal()
template<typename int_type > void Trilinos_Util_CountTriples_internal (const char * data_file, bool symmetric, std::vector< int > & non_zeros, int_type & N_rows, int_type & nnz, const Epetra_Comm & comm, bool TimDavisHeader = false, bool ZeroBased = false)
References Epetra_Comm::Broadcast(), and Epetra_Comm::MyPID().