TriUtils: Trilinos_Util_msr2vbr.cpp File Reference
Trilinos_Util_msr2vbr.cpp File Reference
#include "Trilinos_Util.h"
Functions
void Trilinos_Util_msr2vbr (double val[], int indx[], int rnptr[], int cnptr[], int bnptr[], int bindx[], int msr_bindx[], double msr_val[], int total_blk_rows, int total_blk_cols, int blk_space, int nz_space, int blk_type)
int Trilinos_Util_find_block_col (int cnptr[], int column, int max_blocks, int blk_size)
int Trilinos_Util_find_block_in_row (int bindx[], int bnptr[], int blk_row, int blk_col, int indx[], int no_elements, double val[], int blk_space, int nz_space)
void Trilinos_Util_add_new_ele (int cnptr[], int col, int blk_row, int bindx[], int bnptr[], int indx[], double val[], int row, double new_ele, int maxcols, int blk_space, int nz_space, int blk_type)
int Trilinos_Util_find_closest_not_larger (int key, int list[], int length)
void Trilinos_Util_convert_values_to_ptrs (int array[], int length, int start)
Function Documentation
Trilinos_Util_add_new_ele()
void Trilinos_Util_add_new_ele (int cnptr[], int col, int blk_row, int bindx[], int bnptr[], int indx[], double val[], int row, double new_ele, int maxcols, int blk_space, int nz_space, int blk_type)
References Trilinos_Util_find_block_col(), and Trilinos_Util_find_block_in_row().
Referenced by Trilinos_Util_msr2vbr().
Trilinos_Util_convert_values_to_ptrs()
void Trilinos_Util_convert_values_to_ptrs (int array[], int length, int start)
Referenced by Trilinos_Util_msr2vbr().
Trilinos_Util_find_block_col()
int Trilinos_Util_find_block_col (int cnptr[], int column, int max_blocks, int blk_size)
References Trilinos_Util_find_closest_not_larger().
Referenced by Trilinos_Util_add_new_ele().
Trilinos_Util_find_block_in_row()
int Trilinos_Util_find_block_in_row (int bindx[], int bnptr[], int blk_row, int blk_col, int indx[], int no_elements, double val[], int blk_space, int nz_space)
Referenced by Trilinos_Util_add_new_ele().
Trilinos_Util_find_closest_not_larger()
int Trilinos_Util_find_closest_not_larger (int key, int list[], int length)
Referenced by Trilinos_Util_find_block_col().
Trilinos_Util_msr2vbr()
void Trilinos_Util_msr2vbr (double val[], int indx[], int rnptr[], int cnptr[], int bnptr[], int bindx[], int msr_bindx[], double msr_val[], int total_blk_rows, int total_blk_cols, int blk_space, int nz_space, int blk_type)
References Trilinos_Util_add_new_ele(), and Trilinos_Util_convert_values_to_ptrs().
Referenced by Trilinos_Util_create_vbr().