TriUtils: Trilinos_Util_ReadTriples2Epetra.cpp File Reference
Trilinos_Util_ReadTriples2Epetra.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <vector>
#include <limits>
#include "Trilinos_Util_CountTriples.h"
#include "Epetra_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "Epetra_Map.h"
#include "Epetra_Vector.h"
#include "Epetra_CrsMatrix.h"
Functions
template<typename int_type >
int Trilinos_Util_ReadTriples2Epetra_internal (const char *data_file, bool symmetric, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact, bool NonUniformMap=false, bool TimDavisHeader=false, bool ZeroBased=false)
int Trilinos_Util_ReadTriples2Epetra (const char *data_file, bool symmetric, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact, bool NonUniformMap=false, bool TimDavisHeader=false, bool ZeroBased=false)
int Trilinos_Util_ReadTriples2Epetra64 (const char *data_file, bool symmetric, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact, bool NonUniformMap=false, bool TimDavisHeader=false, bool ZeroBased=false)
Function Documentation
Trilinos_Util_ReadTriples2Epetra()
int Trilinos_Util_ReadTriples2Epetra (const char * data_file, bool symmetric, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact, bool NonUniformMap = false, bool TimDavisHeader = false, bool ZeroBased = false)
Referenced by Trilinos_Util::CrsMatrixGallery::TReadMatrix().
Trilinos_Util_ReadTriples2Epetra64()
int Trilinos_Util_ReadTriples2Epetra64 (const char * data_file, bool symmetric, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact, bool NonUniformMap = false, bool TimDavisHeader = false, bool ZeroBased = false)
Referenced by Trilinos_Util::CrsMatrixGallery::TReadMatrix().
Trilinos_Util_ReadTriples2Epetra_internal()
template<typename int_type > int Trilinos_Util_ReadTriples2Epetra_internal (const char * data_file, bool symmetric, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact, bool NonUniformMap = false, bool TimDavisHeader = false, bool ZeroBased = false)
References Epetra_Comm::Barrier(), Epetra_Comm::Broadcast(), Copy, Epetra_CrsMatrix::FillComplete(), Epetra_CrsMatrix::InsertGlobalValues(), Epetra_CrsMatrix::Multiply(), Epetra_Comm::MyPID(), Epetra_MultiVector::PutScalar(), Epetra_MultiVector::Random(), and Trilinos_Util_CountTriples().