TriUtils: Trilinos_Util_csrmsr.cpp File Reference
Trilinos_Util_csrmsr.cpp File Reference
#include "Trilinos_Util.h"
Functions
int Trilinos_Util_csrmsr (int n, double *a, int *ja, int *ia, double *ao, int *jao, double *wk, int *iwk)
Function Documentation
Trilinos_Util_csrmsr()
int Trilinos_Util_csrmsr (int n, double * a, int * ja, int * ia, double * ao, int * jao, double * wk, int * iwk)
Referenced by Trilinos_Util_read_coo(), Trilinos_Util_read_hb(), and Trilinos_Util_read_hb().