TriUtils: Trilinos_Util_CountMatrixMarket.cpp File Reference
Trilinos_Util_CountMatrixMarket.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <vector>
#include "Epetra_ConfigDefs.h"
#include "Epetra_Object.h"
#include "Epetra_Comm.h"
Functions
template<typename int_type >
void TTrilinos_Util_CountMatrixMarket (const char *data_file, std::vector< int > &non_zeros, int_type &N_rows, int_type &nnz, const Epetra_Comm &comm)
void Trilinos_Util_CountMatrixMarket (const char *data_file, std::vector< int > &non_zeros, int &N_rows, int &nnz, const Epetra_Comm &comm)
void Trilinos_Util_CountMatrixMarket (const char *data_file, std::vector< int > &non_zeros, long long &N_rows, long long &nnz, const Epetra_Comm &comm)
Function Documentation
Trilinos_Util_CountMatrixMarket() [1/2]
void Trilinos_Util_CountMatrixMarket (const char * data_file, std::vector< int > & non_zeros, int & N_rows, int & nnz, const Epetra_Comm & comm)
Referenced by Trilinos_Util_ReadMatrixMarket2Epetra_internal().
Trilinos_Util_CountMatrixMarket() [2/2]
void Trilinos_Util_CountMatrixMarket (const char * data_file, std::vector< int > & non_zeros, long long & N_rows, long long & nnz, const Epetra_Comm & comm)
TTrilinos_Util_CountMatrixMarket()
template<typename int_type > void TTrilinos_Util_CountMatrixMarket (const char * data_file, std::vector< int > & non_zeros, int_type & N_rows, int_type & nnz, const Epetra_Comm & comm)
References Epetra_Comm::Broadcast(), and Epetra_Comm::MyPID().