TriUtils: Trilinos_Util_ReadHpc2Epetra.cpp File Reference
Trilinos_Util_ReadHpc2Epetra.cpp File Reference
#include "Trilinos_Util.h"
#include "Trilinos_Util_iohb.h"
#include "Epetra_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "Epetra_Map.h"
#include "Epetra_Vector.h"
#include "Epetra_CrsMatrix.h"
Functions
template<typename int_type >
void Trilinos_Util_ReadHpc2Epetra_internal (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
void Trilinos_Util_ReadHpc2Epetra (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
void Trilinos_Util_ReadHpc2Epetra64 (const char *data_file, const Epetra_Comm &comm, Epetra_Map *&map, Epetra_CrsMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
Function Documentation
Trilinos_Util_ReadHpc2Epetra()
void Trilinos_Util_ReadHpc2Epetra (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
Trilinos_Util_ReadHpc2Epetra64()
void Trilinos_Util_ReadHpc2Epetra64 (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
Trilinos_Util_ReadHpc2Epetra_internal()
template<typename int_type > void Trilinos_Util_ReadHpc2Epetra_internal (const char * data_file, const Epetra_Comm & comm, Epetra_Map *& map, Epetra_CrsMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
References Copy, Epetra_CrsMatrix::FillComplete(), Epetra_CrsMatrix::InsertGlobalValues(), Epetra_BlockMap::LID(), Epetra_CrsMatrix::Multiply(), Epetra_BlockMap::MyGID(), Epetra_Comm::MyPID(), Epetra_MultiVector::Norm2(), Epetra_CrsMatrix::NumMyNonzeros(), Epetra_BlockMap::NumMyPoints(), Epetra_Comm::NumProc(), and Epetra_MultiVector::Update().