TriUtils: Trilinos_Util_read_hb.cpp File Reference
Trilinos_Util_read_hb.cpp File Reference
#include "Trilinos_Util.h"
#include "Trilinos_Util_iohb.h"
#include "Teuchos_TestForException.hpp"
Functions
void Trilinos_Util_read_hb (const char *data_file, int MyPID, int *N_global, int *n_nonzeros, double **val, int **bindx, double **x, double **b, double **xexact)
void Trilinos_Util_read_hb (const char *data_file, int MyPID, int *N_global, int *n_nonzeros, double **val, int **bindx)
Function Documentation
Trilinos_Util_read_hb() [1/2]
void Trilinos_Util_read_hb (const char * data_file, int MyPID, int * N_global, int * n_nonzeros, double ** val, int ** bindx)
References readHB_header(), readHB_mat_double(), TEUCHOS_TEST_FOR_EXCEPT_MSG, Trilinos_Util_csrcsc(), Trilinos_Util_csrmsr(), and Trilinos_Util_ssrcsr().
Trilinos_Util_read_hb() [2/2]
void Trilinos_Util_read_hb (const char * data_file, int MyPID, int * N_global, int * n_nonzeros, double ** val, int ** bindx, double ** x, double ** b, double ** xexact)
References readHB_aux_double(), readHB_header(), readHB_mat_double(), TEUCHOS_TEST_FOR_EXCEPT_MSG, Trilinos_Util_csrcsc(), Trilinos_Util_csrmsr(), Trilinos_Util_scscmv(), Trilinos_Util_scscres(), Trilinos_Util_smsrres(), and Trilinos_Util_ssrcsr().
Referenced by Trilinos_Util_ReadHb2EpetraVbr().