TriUtils: Trilinos_Util_read_coo.cpp File Reference
Trilinos_Util_read_coo.cpp File Reference
#include "Trilinos_Util.h"
Functions
void Trilinos_Util_read_coo (const char *data_file, int MyPID, int *N_global, int *n_nonzeros, double **val, int **bindx, double **x, double **b, double **)
Function Documentation
Trilinos_Util_read_coo()
void Trilinos_Util_read_coo (const char * data_file, int MyPID, int * N_global, int * n_nonzeros, double ** val, int ** bindx, double ** x, double ** b, double ** xexact)
References Trilinos_Util_coocsr(), Trilinos_Util_csrcsc(), Trilinos_Util_csrmsr(), and Trilinos_Util_max.