TriUtils: Trilinos_Util_svbrres.cpp File Reference
Trilinos_Util_svbrres.cpp File Reference
#include "Trilinos_Util.h"
Functions
double Trilinos_Util_svbrres (int m, int n, int m_blk, double *val, int *indx, int *bindx, int *rpntr, int *cpntr, int *bpntrb, int *bpntre, double *x, double *b)
Function Documentation
Trilinos_Util_svbrres()
double Trilinos_Util_svbrres (int m, int n, int m_blk, double * val, int * indx, int * bindx, int * rpntr, int * cpntr, int * bpntrb, int * bpntre, double * x, double * b)
References Trilinos_Util_duscr_vbr(), Trilinos_Util_dusds_vbr(), Trilinos_Util_dusmm(), and Trilinos_Util_max.
Referenced by Trilinos_Util_distrib_vbr_matrix().