TriUtils: Trilinos_Util_ReadHb2EpetraVbr.cpp File Reference
Trilinos_Util_ReadHb2EpetraVbr.cpp File Reference
#include "Trilinos_Util.h"
#include "Trilinos_Util_iohb.h"
#include "Epetra_ConfigDefs.h"
#include "Epetra_Comm.h"
#include "Epetra_BlockMap.h"
#include "Epetra_Vector.h"
#include "Epetra_VbrMatrix.h"
Functions
void Trilinos_Util_ReadHb2EpetraVbr (const char *data_file, const char *partitioning, const Epetra_Comm &comm, Epetra_BlockMap *&map, Epetra_VbrMatrix *&A, Epetra_Vector *&x, Epetra_Vector *&b, Epetra_Vector *&xexact)
Function Documentation
Trilinos_Util_ReadHb2EpetraVbr()
void Trilinos_Util_ReadHb2EpetraVbr (const char * data_file, const char * partitioning, const Epetra_Comm & comm, Epetra_BlockMap *& map, Epetra_VbrMatrix *& A, Epetra_Vector *& x, Epetra_Vector *& b, Epetra_Vector *& xexact)
References Epetra_VbrMatrix::BeginInsertGlobalValues(), Copy, Epetra_VbrMatrix::EndSubmitEntries(), Epetra_VbrMatrix::FillComplete(), Epetra_Comm::MyPID(), Epetra_VbrMatrix::SubmitBlockEntry(), Trilinos_Util_create_vbr(), and Trilinos_Util_read_hb().