Stokhos: Stokhos::AdaptivityManager Class Reference
Stokhos::AdaptivityManager Class Reference
#include <Stokhos_AdaptivityManager.hpp>
Public Member Functions
AdaptivityManager (const Teuchos::RCP< const Stokhos::ProductBasis< int, double > > &sg_master_basis, const std::vector< Teuchos::RCP< const Stokhos::ProductBasis< int, double > > > &sg_basis_row_dof, const Epetra_CrsGraph &determ_graph, bool onlyUseLinear, int kExpOrder, bool scaleOp=true)
AdaptivityManager (const Teuchos::RCP< const Stokhos::ProductBasis< int, double > > &sg_master_basis, const std::vector< Teuchos::RCP< const Stokhos::ProductBasis< int, double > > > &sg_basis_row_dof, const Epetra_Comm &comm, bool scaleOp=true)
int getGlobalColId (int determLid, int basisIndex) const
int getGlobalRowId (int determLid, int basisIndex) const
Teuchos::RCP< Epetra_CrsMatrix > buildMatrixFromGraph () const
void setupWithGraph (const Epetra_CrsGraph &graph, bool onlyUseLinear, int kExpOrder)
Teuchos::RCP< const Epetra_Map > getAdaptedMap () const
void setupOperator (Epetra_CrsMatrix &A, const Sparse3Tensor< int, double > &Cijk, Stokhos::EpetraOperatorOrthogPoly &poly, bool onlyUseLinear=false, bool includeMean=true) const
void sumInOperator (Epetra_CrsMatrix &A, const Stokhos::Sparse3Tensor< int, double > &Cijk, int k, const Epetra_CrsMatrix &J_k) const
void copyToAdaptiveVector (const Stokhos::EpetraVectorOrthogPoly &x_sg, Epetra_Vector &x) const
void copyFromAdaptiveVector (const Epetra_Vector &x, Stokhos::EpetraVectorOrthogPoly &x_sg) const
int getRowStochasticBasisSize (int determLid) const
int getColStochasticBasisSize (int determLid) const
Teuchos::RCP< const Stokhos::ProductBasis< int, double > > getMasterStochasticBasis () const
Teuchos::RCP< const Stokhos::ProductBasis< int, double > > getRowStochasticBasis (int determLid) const
const std::vector< Teuchos::RCP< const Stokhos::ProductBasis< int, double > > > & getRowStochasticBasis () const
Teuchos::RCP< const Stokhos::ProductBasis< int, double > > getColStochasticBasis (int determLid) const
bool isScaled ()
Detailed Description
Describes and constructs all things needed for adaptivity.
Member Function Documentation
buildMatrixFromGraph()
Teuchos::RCP< Epetra_CrsMatrix > Stokhos::AdaptivityManager::buildMatrixFromGraph () const
Build a CRS matrix from the internally constructed graph
copyFromAdaptiveVector()
void Stokhos::AdaptivityManager::copyFromAdaptiveVector (const Epetra_Vector & x, Stokhos::EpetraVectorOrthogPoly & x_sg) const
Copy from an adaptive vector to a set of blocked vectors
References Stokhos::ProductEpetraVector::getBlockVector(), and Stokhos::ProductContainer< coeff_type >::size().
copyToAdaptiveVector()
void Stokhos::AdaptivityManager::copyToAdaptiveVector (const Stokhos::EpetraVectorOrthogPoly & x_sg, Epetra_Vector & x) const
Copy to an adaptive vector from a set of blocked vectors
References Stokhos::ProductEpetraVector::getBlockVector().
getAdaptedMap()
Teuchos::RCP< const Epetra_Map > Stokhos::AdaptivityManager::getAdaptedMap () const inline
Get map associated with this set of adaptive indices
getColStochasticBasis()
Teuchos::RCP< const Stokhos::ProductBasis< int, double > > Stokhos::AdaptivityManager::getColStochasticBasis (int determLid) const inline
Get stochastic basis associated with a particular deterministic column local id.
getColStochasticBasisSize()
int Stokhos::AdaptivityManager::getColStochasticBasisSize (int determLid) const inline
How many stochastic degrees of freedom are associated with a particular deterministic row degree of freedom.
getGlobalColId()
int Stokhos::AdaptivityManager::getGlobalColId (int determLid, int basisIndex) const inline
Given a deterministic local column ID and a basis index determine the global column ID in the fully assembled system.
Parameters
[in] determLid Deterministic local column ID
[in] basisIndex Index into the stochastic basis associated with this column ID.
Returns
Associated index in the global system.
Note
basisIndex must be less than getRowStochasticBasisSize(determLid)
getGlobalRowId()
int Stokhos::AdaptivityManager::getGlobalRowId (int determLid, int basisIndex) const inline
Given a deterministic local row ID and a basis index determine the global row ID in the fully assembled system.
Parameters
[in] determLid Deterministic local row ID
[in] basisIndex Index into the stochastic basis associated with this row ID.
Returns
Associated index in the global system.
Note
basisIndex must be less than getRowStochasticBasisSize(determLid)
getMasterStochasticBasis()
Teuchos::RCP< const Stokhos::ProductBasis< int, double > > Stokhos::AdaptivityManager::getMasterStochasticBasis () const inline
Get master stochastic basis
getRowStochasticBasis() [1/2]
const std::vector< Teuchos::RCP< const Stokhos::ProductBasis< int, double > > > & Stokhos::AdaptivityManager::getRowStochasticBasis () const inline
Get the vector of row stochastic basis functions.
getRowStochasticBasis() [2/2]
Teuchos::RCP< const Stokhos::ProductBasis< int, double > > Stokhos::AdaptivityManager::getRowStochasticBasis (int determLid) const inline
Get stochastic basis associated with a particular deterministic row local id.
getRowStochasticBasisSize()
int Stokhos::AdaptivityManager::getRowStochasticBasisSize (int determLid) const inline
How many stochastic degrees of freedom are associated with a particular deterministic row degree of freedom.
setupOperator()
void Stokhos::AdaptivityManager::setupOperator (Epetra_CrsMatrix & A, const Sparse3Tensor< int, double > & Cijk, Stokhos::EpetraOperatorOrthogPoly & poly, bool onlyUseLinear = false, bool includeMean = true) const
Setup operator
References Stokhos::Sparse3Tensor< ordinal_type, value_type >::find_k(), Stokhos::ProductContainer< coeff_type >::getCoeffPtr(), Stokhos::Sparse3Tensor< ordinal_type, value_type >::k_begin(), and Stokhos::Sparse3Tensor< ordinal_type, value_type >::k_end().
setupWithGraph()
void Stokhos::AdaptivityManager::setupWithGraph (const Epetra_CrsGraph & graph, bool onlyUseLinear, int kExpOrder)
Build a CRS graph from a determinstic graph
sumInOperator()
void Stokhos::AdaptivityManager::sumInOperator (Epetra_CrsMatrix & A, const Stokhos::Sparse3Tensor< int, double > & Cijk, int k, const Epetra_CrsMatrix & J_k) const
Sum into a matrix constructed from buildMatrixFromGraph using the Cjik tensor a matrix J_k
The documentation for this class was generated from the following files:
Stokhos_AdaptivityManager.hpp
Stokhos_AdaptivityManager.cpp