Stokhos: Stokhos::StieltjesPCEBasis< ordinal_type, value_type > Class Template Reference
Stokhos::StieltjesPCEBasis< ordinal_type, value_type > Class Template Reference
Generates three-term recurrence using the Discretized Stieltjes procedure applied to a polynomial chaos expansion in another basis.
#include <Stokhos_StieltjesPCEBasis.hpp>
Public Member Functions
StieltjesPCEBasis (ordinal_type p, const Teuchos::RCP< const Stokhos::OrthogPolyApprox< ordinal_type, value_type > > &pce, const Teuchos::RCP< const Stokhos::Quadrature< ordinal_type, value_type > > &quad, bool use_pce_quad_points, bool normalize=false, bool project_integrals=false, const Teuchos::RCP< const Stokhos::Sparse3Tensor< ordinal_type, value_type > > &Cijk=Teuchos::null)
Constructor.
~StieltjesPCEBasis ()
Destructor.
Implementation of Stokhos::OneDOrthogPolyBasis methods
virtual void getQuadPoints (ordinal_type quad_order, Teuchos::Array< value_type > &points, Teuchos::Array< value_type > &weights, Teuchos::Array< Teuchos::Array< value_type > > &values) const
Get Gauss quadrature points, weights, and values of basis at points.
virtual Teuchos::RCP< OneDOrthogPolyBasis< ordinal_type, value_type > > cloneWithOrder (ordinal_type p) const
Clone this object with the option of building a higher order basis.
void transformCoeffsFromStieltjes (const value_type *in, value_type *out) const
Map expansion coefficients from this basis to original.
Public Member Functions inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
virtual ~RecurrenceBasis ()
Destructor.
virtual ordinal_type order () const
Return order of basis (largest monomial degree).
virtual ordinal_type size () const
Return total size of basis (given by order() + 1).
virtual const Teuchos::Array< value_type > & norm_squared () const
Return array storing norm-squared of each basis polynomial.
virtual const value_type & norm_squared (ordinal_type i) const
Return norm squared of basis polynomial i.
virtual Teuchos::RCP< Stokhos::Dense3Tensor< ordinal_type, value_type > > computeTripleProductTensor () const
Compute triple product tensor.
virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > computeSparseTripleProductTensor (ordinal_type order) const
Compute triple product tensor.
virtual Teuchos::RCP< Teuchos::SerialDenseMatrix< ordinal_type, value_type > > computeDerivDoubleProductTensor () const
Compute derivative double product tensor.
virtual void evaluateBases (const value_type &point, Teuchos::Array< value_type > &basis_pts) const
Evaluate each basis polynomial at given point point.
virtual value_type evaluate (const value_type &point, ordinal_type order) const
Evaluate basis polynomial given by order order at given point point.
virtual void print (std::ostream &os) const
Print basis to stream os.
virtual const std::string & getName () const
Return string name of basis.
virtual ordinal_type quadDegreeOfExactness (ordinal_type n) const
virtual ordinal_type coefficientGrowth (ordinal_type n) const
Evaluate coefficient growth rule for Smolyak-type bases.
virtual ordinal_type pointGrowth (ordinal_type n) const
Evaluate point growth rule for Smolyak-type bases.
virtual LevelToOrderFnPtr getSparseGridGrowthRule () const
Get sparse grid level_to_order mapping function.
virtual void setSparseGridGrowthRule (LevelToOrderFnPtr ptr)
Set sparse grid rule.
virtual void getRecurrenceCoefficients (Teuchos::Array< value_type > &alpha, Teuchos::Array< value_type > &beta, Teuchos::Array< value_type > &delta, Teuchos::Array< value_type > &gamma) const
Return recurrence coefficients defined by above formula.
virtual void evaluateBasesAndDerivatives (const value_type &point, Teuchos::Array< value_type > &vals, Teuchos::Array< value_type > &derivs) const
Evaluate basis polynomials and their derivatives at given point point.
virtual void setQuadZeroTol (value_type tol)
Set tolerance for zero in quad point generation.
Public Member Functions inherited from Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type >
OneDOrthogPolyBasis ()
Default constructor.
virtual ~OneDOrthogPolyBasis ()
Destructor.
virtual void setSparseGridGrowthRule (LevelToOrderFnPtr ptr)=0
Set sparse grid rule.
Implementation of Stokhos::RecurrenceBasis methods
typedef Stokhos::Sparse3Tensor< ordinal_type, value_type > Cijk_type
Short-hand for triple product.
Teuchos::RCP< const Stokhos::OrthogPolyApprox< ordinal_type, value_type > > pce
PC expansion.
Teuchos::RCP< const Stokhos::Quadrature< ordinal_type, value_type > > quad
Quadrature object.
const Teuchos::Array< value_type > & pce_weights
PCE quadrature weights.
const Teuchos::Array< Teuchos::Array< value_type > > & basis_values
Values of PCE basis functions at quadrature points.
Teuchos::Array< value_type > pce_vals
Values of PCE at quadrature points.
Teuchos::Array< Teuchos::Array< value_type > > phi_vals
Values of generated polynomials at PCE quadrature points.
bool use_pce_quad_points
Use underlying pce's quadrature data.
Teuchos::SerialDenseMatrix< ordinal_type, value_type > fromStieltjesMat
Matrix mapping coefficients in Stieltjes basis back to original basis.
bool project_integrals
Project Stieltjes integrals to original PCE basis.
Teuchos::RCP< const Stokhos::OrthogPolyBasis< ordinal_type, value_type > > basis
PCE basis (needed for integral projection method)
Teuchos::RCP< const Cijk_type > Cijk
Triple product tensor (needed for integral projection method)
Teuchos::Array< value_type > phi_pce_coeffs
Array store PC expansion of generated orthogonal polynomials.
virtual bool computeRecurrenceCoefficients (ordinal_type n, Teuchos::Array< value_type > &alpha, Teuchos::Array< value_type > &beta, Teuchos::Array< value_type > &delta, Teuchos::Array< value_type > &gamma) const
Compute recurrence coefficients.
virtual void setup ()
Setup basis after computing recurrence coefficients.
void stieltjes (ordinal_type nstart, ordinal_type nfinish, const Teuchos::Array< value_type > &weights, const Teuchos::Array< value_type > &points, Teuchos::Array< value_type > &a, Teuchos::Array< value_type > &b, Teuchos::Array< value_type > &nrm, Teuchos::Array< Teuchos::Array< value_type > > &phi_vals) const
Compute 3-term recurrence using Stieljtes procedure.
void integrateBasisSquared (ordinal_type k, const Teuchos::Array< value_type > &a, const Teuchos::Array< value_type > &b, const Teuchos::Array< value_type > &weights, const Teuchos::Array< value_type > &points, Teuchos::Array< Teuchos::Array< value_type > > &phi_vals, value_type &val1, value_type &val2) const
Compute and .
void integrateBasisSquaredProj (ordinal_type k, const Teuchos::Array< value_type > &a, const Teuchos::Array< value_type > &b, const Teuchos::Array< value_type > &weights, const Teuchos::Array< value_type > &points, Teuchos::Array< Teuchos::Array< value_type > > &phi_vals, value_type &val1, value_type &val2) const
Compute and by projecting onto original PCE basis.
void evaluateRecurrence (ordinal_type k, const Teuchos::Array< value_type > &a, const Teuchos::Array< value_type > &b, const Teuchos::Array< value_type > &points, Teuchos::Array< Teuchos::Array< value_type > > &values) const
Evaluate polynomials via 3-term recurrence.
StieltjesPCEBasis (ordinal_type p, const StieltjesPCEBasis &basis)
Copy constructor with specified order.
Additional Inherited Members
Public Types inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
typedef OneDOrthogPolyBasis< ordinal_type, value_type >::LevelToOrderFnPtr LevelToOrderFnPtr
Function pointer needed for level_to_order mappings.
Public Types inherited from Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type >
typedef int(* LevelToOrderFnPtr) (int level, int growth)
Function pointer needed for level_to_order mappings.
Protected Member Functions inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
RecurrenceBasis (const std::string &name, ordinal_type p, bool normalize, GrowthPolicy growth=SLOW_GROWTH)
Constructor to be called by derived classes.
RecurrenceBasis (ordinal_type p, const RecurrenceBasis &basis)
Copy constructor with specified order.
void normalizeRecurrenceCoefficients (Teuchos::Array< value_type > &alpha, Teuchos::Array< value_type > &beta, Teuchos::Array< value_type > &delta, Teuchos::Array< value_type > &gamma) const
Normalize coefficients.
Protected Attributes inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
std::string name
Name of basis.
ordinal_type p
Order of basis.
bool normalize
Normalize basis.
GrowthPolicy growth
Smolyak growth policy.
value_type quad_zero_tol
Tolerance for quadrature points near zero.
LevelToOrderFnPtr sparse_grid_growth_rule
Sparse grid growth rule (as determined by Pecos)
Teuchos::Array< value_type > alpha
Recurrence coefficients.
Teuchos::Array< value_type > beta
Recurrence coefficients.
Teuchos::Array< value_type > delta
Recurrence coefficients.
Teuchos::Array< value_type > gamma
Recurrence coefficients.
Teuchos::Array< value_type > norms
Norms.
Detailed Description
template<typename ordinal_type, typename value_type>
class Stokhos::StieltjesPCEBasis< ordinal_type, value_type >
Generates three-term recurrence using the Discretized Stieltjes procedure applied to a polynomial chaos expansion in another basis.
Constructor & Destructor Documentation
StieltjesPCEBasis()
template<typename ordinal_type , typename value_type > Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::StieltjesPCEBasis (ordinal_type p, const Teuchos::RCP< const Stokhos::OrthogPolyApprox< ordinal_type, value_type > > & pce, const Teuchos::RCP< const Stokhos::Quadrature< ordinal_type, value_type > > & quad, bool use_pce_quad_points, bool normalize = false, bool project_integrals = false, const Teuchos::RCP< const Stokhos::Sparse3Tensor< ordinal_type, value_type > > & Cijk = Teuchos::null)
Constructor.
Parameters
p order of the basis
pce polynomial chaos expansion defining new density function
quad quadrature data for basis of PC expansion
use_pce_quad_points whether to use quad to define quadrature points for the new basis, or whether to use the Golub-Welsch system.
normalize whether polynomials should be given unit norm
References Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::setup().
Member Function Documentation
cloneWithOrder()
template<typename ordinal_type , typename value_type > Teuchos::RCP< Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type > > Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::cloneWithOrder (ordinal_type p) const virtual
Clone this object with the option of building a higher order basis.
This method is following the Prototype pattern (see Design Pattern's textbook). The slight variation is that it allows the order of the polynomial to be modified, otherwise an exact copy is formed. The use case for this is creating basis functions for column indices in a spatially varying adaptive refinement context.
Implements Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type >.
computeRecurrenceCoefficients()
template<typename ordinal_type , typename value_type > bool Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::computeRecurrenceCoefficients (ordinal_type n, Teuchos::Array< value_type > & alpha, Teuchos::Array< value_type > & beta, Teuchos::Array< value_type > & delta, Teuchos::Array< value_type > & gamma) const protected virtual
Compute recurrence coefficients.
Implements Stokhos::RecurrenceBasis< ordinal_type, value_type >.
getQuadPoints()
template<typename ordinal_type , typename value_type > void Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::getQuadPoints (ordinal_type quad_order, Teuchos::Array< value_type > & points, Teuchos::Array< value_type > & weights, Teuchos::Array< Teuchos::Array< value_type > > & values) const virtual
Get Gauss quadrature points, weights, and values of basis at points.
Reimplemented from Stokhos::RecurrenceBasis< ordinal_type, value_type >.
References Stokhos::RecurrenceBasis< ordinal_type, value_type >::getQuadPoints().
setup()
template<typename ordinal_type , typename value_type > void Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::setup () protected virtual
Setup basis after computing recurrence coefficients.
Reimplemented from Stokhos::RecurrenceBasis< ordinal_type, value_type >.
References Stokhos::RecurrenceBasis< ordinal_type, value_type >::setup().
Referenced by Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::StieltjesPCEBasis(), and Stokhos::StieltjesPCEBasis< ordinal_type, value_type >::StieltjesPCEBasis().
The documentation for this class was generated from the following files:
Stokhos_StieltjesPCEBasis.hpp
Stokhos_StieltjesPCEBasisImp.hpp