Stokhos: Stokhos::Quadrature< ordinal_type, value_type > Class Template Reference
Stokhos::Quadrature< ordinal_type, value_type > Class Template Reference abstract
Abstract base class for quadrature methods.
#include <Stokhos_Quadrature.hpp>
Public Member Functions
Quadrature ()
Constructor.
virtual ~Quadrature ()
Destructor.
virtual ordinal_type size () const =0
Get number of quadrature points.
virtual const Teuchos::Array< Teuchos::Array< value_type > > & getQuadPoints () const =0
Get quadrature points.
virtual const Teuchos::Array< value_type > & getQuadWeights () const =0
Get quadrature weights.
virtual const Teuchos::Array< Teuchos::Array< value_type > > & getBasisAtQuadPoints () const =0
Get values of basis at quadrature points.
virtual std::ostream & print (std::ostream &os) const =0
Print quadrature data.
Detailed Description
template<typename ordinal_type, typename value_type>
class Stokhos::Quadrature< ordinal_type, value_type >
Abstract base class for quadrature methods.
Member Function Documentation
getBasisAtQuadPoints()
template<typename ordinal_type , typename value_type > virtual const Teuchos::Array< Teuchos::Array< value_type > > & Stokhos::Quadrature< ordinal_type, value_type >::getBasisAtQuadPoints () const pure virtual
Get values of basis at quadrature points.
Array is dimensioned Q-by-P where Q is the number of quadrature points and P is the size of the basis.
Implemented in Stokhos::AnisoSparseGridQuadrature< ordinal_type, value_type >, Stokhos::SmolyakSparseGridQuadrature< ordinal_type, value_type, point_compare_type >, Stokhos::SparseGridQuadrature< ordinal_type, value_type >, Stokhos::TensorProductQuadrature< ordinal_type, value_type >, and Stokhos::UserDefinedQuadrature< ordinal_type, value_type >.
Referenced by Stokhos::MonoProjPCEBasis< ordinal_type, value_type >::MonoProjPCEBasis(), and Stokhos::QuadraturePseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::QuadraturePseudoSpectralOperator().
getQuadPoints()
template<typename ordinal_type , typename value_type > virtual const Teuchos::Array< Teuchos::Array< value_type > > & Stokhos::Quadrature< ordinal_type, value_type >::getQuadPoints () const pure virtual
Get quadrature points.
Array is dimensioned Q-by-d where Q is the number of quadrature points and d is the dimension of the basis.
Implemented in Stokhos::AnisoSparseGridQuadrature< ordinal_type, value_type >, Stokhos::SmolyakSparseGridQuadrature< ordinal_type, value_type, point_compare_type >, Stokhos::SparseGridQuadrature< ordinal_type, value_type >, Stokhos::TensorProductQuadrature< ordinal_type, value_type >, and Stokhos::UserDefinedQuadrature< ordinal_type, value_type >.
Referenced by Stokhos::MonoProjPCEBasis< ordinal_type, value_type >::MonoProjPCEBasis(), and Stokhos::QuadraturePseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::QuadraturePseudoSpectralOperator().
getQuadWeights()
template<typename ordinal_type , typename value_type > virtual const Teuchos::Array< value_type > & Stokhos::Quadrature< ordinal_type, value_type >::getQuadWeights () const pure virtual
Get quadrature weights.
Array is of size Q where Q is the number of quadrature points.
Implemented in Stokhos::AnisoSparseGridQuadrature< ordinal_type, value_type >, Stokhos::SmolyakSparseGridQuadrature< ordinal_type, value_type, point_compare_type >, Stokhos::SparseGridQuadrature< ordinal_type, value_type >, Stokhos::TensorProductQuadrature< ordinal_type, value_type >, and Stokhos::UserDefinedQuadrature< ordinal_type, value_type >.
Referenced by Stokhos::MonoProjPCEBasis< ordinal_type, value_type >::MonoProjPCEBasis(), and Stokhos::QuadraturePseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::QuadraturePseudoSpectralOperator().
print()
template<typename ordinal_type , typename value_type > virtual std::ostream & Stokhos::Quadrature< ordinal_type, value_type >::print (std::ostream & os) const pure virtual
Print quadrature data.
Implemented in Stokhos::SmolyakSparseGridQuadrature< ordinal_type, value_type, point_compare_type >, Stokhos::SparseGridQuadrature< ordinal_type, value_type >, Stokhos::TensorProductQuadrature< ordinal_type, value_type >, and Stokhos::UserDefinedQuadrature< ordinal_type, value_type >.
Referenced by Stokhos::operator<<().
size()
template<typename ordinal_type , typename value_type > virtual ordinal_type Stokhos::Quadrature< ordinal_type, value_type >::size () const pure virtual
Get number of quadrature points.
Implemented in Stokhos::SmolyakSparseGridQuadrature< ordinal_type, value_type, point_compare_type >, Stokhos::SparseGridQuadrature< ordinal_type, value_type >, Stokhos::TensorProductQuadrature< ordinal_type, value_type >, and Stokhos::UserDefinedQuadrature< ordinal_type, value_type >.
Referenced by Stokhos::MonoProjPCEBasis< ordinal_type, value_type >::MonoProjPCEBasis(), and Stokhos::QuadraturePseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::QuadraturePseudoSpectralOperator().
The documentation for this class was generated from the following file:
Stokhos_Quadrature.hpp