Stokhos: Stokhos::OrthogPolyBasis< ordinal_type, value_type > Class Template Reference
Stokhos::OrthogPolyBasis< ordinal_type, value_type > Class Template Reference abstract
Abstract base class for multivariate orthogonal polynomials.
#include <Stokhos_OrthogPolyBasis.hpp>
Public Member Functions
OrthogPolyBasis ()
Constructor.
virtual ~OrthogPolyBasis ()
Destructor.
virtual ordinal_type order () const =0
Return order of basis.
virtual ordinal_type dimension () const =0
Return dimension of basis.
virtual ordinal_type size () const =0
Return total size of basis.
virtual const Teuchos::Array< value_type > & norm_squared () const =0
Return array storing norm-squared of each basis polynomial.
virtual const value_type & norm_squared (ordinal_type i) const =0
Return norm squared of basis polynomial i.
virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > computeTripleProductTensor () const =0
Compute triple product tensor.
virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > computeLinearTripleProductTensor () const =0
Compute linear triple product tensor where k = 0,1.
virtual value_type evaluateZero (ordinal_type i) const =0
Evaluate basis polynomial i at zero.
virtual void evaluateBases (const Teuchos::ArrayView< const value_type > &point, Teuchos::Array< value_type > &basis_vals) const =0
Evaluate basis polynomials at given point point.
virtual void print (std::ostream &os) const =0
Print basis to stream os.
virtual const std::string & getName () const =0
Return string name of basis.
Detailed Description
template<typename ordinal_type, typename value_type>
class Stokhos::OrthogPolyBasis< ordinal_type, value_type >
Abstract base class for multivariate orthogonal polynomials.
This class provides an abstract interface for multivariate orthogonal polynomials. Orthogonality is defined by the inner product
where is the density function of the measure associated with the orthogonal polynomials and is the dimension of the domain.
Like most classes in Stokhos, the class is templated on the ordinal and value types. Typically ordinal_type = int and value_type = double.
Member Function Documentation
computeLinearTripleProductTensor()
template<typename ordinal_type , typename value_type > virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > Stokhos::OrthogPolyBasis< ordinal_type, value_type >::computeLinearTripleProductTensor () const pure virtual
Compute linear triple product tensor where k = 0,1.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
computeTripleProductTensor()
template<typename ordinal_type , typename value_type > virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > Stokhos::OrthogPolyBasis< ordinal_type, value_type >::computeTripleProductTensor () const pure virtual
Compute triple product tensor.
The entry of the tensor is given by where represents basis polynomial and where is size()-1.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
dimension()
template<typename ordinal_type , typename value_type > virtual ordinal_type Stokhos::OrthogPolyBasis< ordinal_type, value_type >::dimension () const pure virtual
Return dimension of basis.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
Referenced by Stokhos::BasisInteractionGraph::initialize(), and Stokhos::QuadraturePseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::QuadraturePseudoSpectralOperator().
evaluateBases()
template<typename ordinal_type , typename value_type > virtual void Stokhos::OrthogPolyBasis< ordinal_type, value_type >::evaluateBases (const Teuchos::ArrayView< const value_type > & point, Teuchos::Array< value_type > & basis_vals) const pure virtual
Evaluate basis polynomials at given point point.
Size of returned array is given by size(), and coefficients are ordered from order 0 up to size size()-1.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
evaluateZero()
template<typename ordinal_type , typename value_type > virtual value_type Stokhos::OrthogPolyBasis< ordinal_type, value_type >::evaluateZero (ordinal_type i) const pure virtual
Evaluate basis polynomial i at zero.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
getName()
template<typename ordinal_type , typename value_type > virtual const std::string & Stokhos::OrthogPolyBasis< ordinal_type, value_type >::getName () const pure virtual
Return string name of basis.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::MonomialGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
norm_squared() [1/2]
template<typename ordinal_type , typename value_type > virtual const Teuchos::Array< value_type > & Stokhos::OrthogPolyBasis< ordinal_type, value_type >::norm_squared () const pure virtual
Return array storing norm-squared of each basis polynomial.
Entry of returned array is given by for where is size()-1.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
Referenced by Stokhos::QuadraturePseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::QuadraturePseudoSpectralOperator().
norm_squared() [2/2]
template<typename ordinal_type , typename value_type > virtual const value_type & Stokhos::OrthogPolyBasis< ordinal_type, value_type >::norm_squared (ordinal_type i) const pure virtual
Return norm squared of basis polynomial i.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
order()
template<typename ordinal_type , typename value_type > virtual ordinal_type Stokhos::OrthogPolyBasis< ordinal_type, value_type >::order () const pure virtual
Return order of basis.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
print()
template<typename ordinal_type , typename value_type > virtual void Stokhos::OrthogPolyBasis< ordinal_type, value_type >::print (std::ostream & os) const pure virtual
Print basis to stream os.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
size()
template<typename ordinal_type , typename value_type > virtual ordinal_type Stokhos::OrthogPolyBasis< ordinal_type, value_type >::size () const pure virtual
Return total size of basis.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::GSReducedPCEBasisBase< ordinal_type, value_type >, Stokhos::MonomialProjGramSchmidtPCEBasis2< ordinal_type, value_type >, Stokhos::ProductLanczosGramSchmidtPCEBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
Referenced by Stokhos::BasisInteractionGraph::initialize(), Stokhos::BasisInteractionGraph::initialize(), Stokhos::PCECovarianceOp::PCECovarianceOp(), Stokhos::QuadraturePseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::QuadraturePseudoSpectralOperator(), Stokhos::sparse3Tensor2CrsGraph(), and Stokhos::TensorProductPseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::TensorProductPseudoSpectralOperator().
The documentation for this class was generated from the following file:
Stokhos_OrthogPolyBasis.hpp