Stokhos: Stokhos::ProductBasis< ordinal_type, value_type > Class Template Reference
Stokhos::ProductBasis< ordinal_type, value_type > Class Template Reference abstract
Abstract base class for multivariate orthogonal polynomials generated from tensor products of univariate polynomials.
#include <Stokhos_ProductBasis.hpp>
Public Member Functions
ProductBasis ()
Constructor.
virtual ~ProductBasis ()
Destructor.
virtual const MultiIndex< ordinal_type > & term (ordinal_type i) const =0
Get orders of each coordinate polynomial given an index i.
virtual ordinal_type index (const MultiIndex< ordinal_type > &term) const =0
Get index of the multivariate polynomial given orders of each coordinate.
virtual Teuchos::Array< Teuchos::RCP< const OneDOrthogPolyBasis< ordinal_type, value_type > > > getCoordinateBases () const =0
Return array of coordinate bases.
virtual MultiIndex< ordinal_type > getMaxOrders () const =0
Return maximum order allowable for each coordinate basis.
Public Member Functions inherited from Stokhos::OrthogPolyBasis< ordinal_type, value_type >
OrthogPolyBasis ()
Constructor.
virtual ~OrthogPolyBasis ()
Destructor.
virtual ordinal_type order () const =0
Return order of basis.
virtual ordinal_type dimension () const =0
Return dimension of basis.
virtual ordinal_type size () const =0
Return total size of basis.
virtual const Teuchos::Array< value_type > & norm_squared () const =0
Return array storing norm-squared of each basis polynomial.
virtual const value_type & norm_squared (ordinal_type i) const =0
Return norm squared of basis polynomial i.
virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > computeTripleProductTensor () const =0
Compute triple product tensor.
virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > computeLinearTripleProductTensor () const =0
Compute linear triple product tensor where k = 0,1.
virtual value_type evaluateZero (ordinal_type i) const =0
Evaluate basis polynomial i at zero.
virtual void evaluateBases (const Teuchos::ArrayView< const value_type > &point, Teuchos::Array< value_type > &basis_vals) const =0
Evaluate basis polynomials at given point point.
virtual void print (std::ostream &os) const =0
Print basis to stream os.
virtual const std::string & getName () const =0
Return string name of basis.
Detailed Description
template<typename ordinal_type, typename value_type>
class Stokhos::ProductBasis< ordinal_type, value_type >
Abstract base class for multivariate orthogonal polynomials generated from tensor products of univariate polynomials.
The multivariate polynomials are given by
where is the dimension of the basis. This class adds methods for indexing the multivariate polynomial and getting the coordinate bases.
Member Function Documentation
getCoordinateBases()
template<typename ordinal_type , typename value_type > virtual Teuchos::Array< Teuchos::RCP< const OneDOrthogPolyBasis< ordinal_type, value_type > > > Stokhos::ProductBasis< ordinal_type, value_type >::getCoordinateBases () const pure virtual
Return array of coordinate bases.
Array is of size dimension().
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
Referenced by Stokhos::TensorProductPseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::TensorProductPseudoSpectralOperator().
getMaxOrders()
template<typename ordinal_type , typename value_type > virtual MultiIndex< ordinal_type > Stokhos::ProductBasis< ordinal_type, value_type >::getMaxOrders () const pure virtual
Return maximum order allowable for each coordinate basis.
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
Referenced by Stokhos::TensorProductPseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::TensorProductPseudoSpectralOperator().
index()
template<typename ordinal_type , typename value_type > virtual ordinal_type Stokhos::ProductBasis< ordinal_type, value_type >::index (const MultiIndex< ordinal_type > & term) const pure virtual
Get index of the multivariate polynomial given orders of each coordinate.
Given the array term storing , returns the index such that .
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
Referenced by Stokhos::BasisInteractionGraph::initialize().
term()
template<typename ordinal_type , typename value_type > virtual const MultiIndex< ordinal_type > & Stokhos::ProductBasis< ordinal_type, value_type >::term (ordinal_type i) const pure virtual
Get orders of each coordinate polynomial given an index i.
The returned array is of size , where is the dimension of the basis, and entry is given by where .
Implemented in Stokhos::CompletePolynomialBasis< ordinal_type, value_type >, Stokhos::ProductLanczosPCEBasis< ordinal_type, value_type >, Stokhos::SmolyakBasis< ordinal_type, value_type, coeff_compare_type >, Stokhos::TensorProductBasis< ordinal_type, value_type, coeff_compare_type >, and Stokhos::TotalOrderBasis< ordinal_type, value_type, coeff_compare_type >.
Referenced by Stokhos::BasisInteractionGraph::initialize(), and Stokhos::TensorProductPseudoSpectralOperator< ordinal_t, value_t, point_compare_type >::TensorProductPseudoSpectralOperator().
The documentation for this class was generated from the following file:
Stokhos_ProductBasis.hpp