Stokhos: Stokhos::LegendreBasis< ordinal_type, value_type > Class Template Reference
Stokhos::LegendreBasis< ordinal_type, value_type > Class Template Reference
Legendre polynomial basis.
#include <Stokhos_LegendreBasis.hpp>
Public Member Functions
LegendreBasis (ordinal_type p, bool normalize=false, GrowthPolicy growth=SLOW_GROWTH)
Constructor.
~LegendreBasis ()
Destructor.
Implementation of Stokhos::OneDOrthogPolyBasis methods
virtual Teuchos::RCP< OneDOrthogPolyBasis< ordinal_type, value_type > > cloneWithOrder (ordinal_type p) const
Clone this object with the option of building a higher order basis.
Public Member Functions inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
virtual ~RecurrenceBasis ()
Destructor.
virtual ordinal_type order () const
Return order of basis (largest monomial degree).
virtual ordinal_type size () const
Return total size of basis (given by order() + 1).
virtual const Teuchos::Array< value_type > & norm_squared () const
Return array storing norm-squared of each basis polynomial.
virtual const value_type & norm_squared (ordinal_type i) const
Return norm squared of basis polynomial i.
virtual Teuchos::RCP< Stokhos::Dense3Tensor< ordinal_type, value_type > > computeTripleProductTensor () const
Compute triple product tensor.
virtual Teuchos::RCP< Stokhos::Sparse3Tensor< ordinal_type, value_type > > computeSparseTripleProductTensor (ordinal_type order) const
Compute triple product tensor.
virtual Teuchos::RCP< Teuchos::SerialDenseMatrix< ordinal_type, value_type > > computeDerivDoubleProductTensor () const
Compute derivative double product tensor.
virtual void evaluateBases (const value_type &point, Teuchos::Array< value_type > &basis_pts) const
Evaluate each basis polynomial at given point point.
virtual value_type evaluate (const value_type &point, ordinal_type order) const
Evaluate basis polynomial given by order order at given point point.
virtual void print (std::ostream &os) const
Print basis to stream os.
virtual const std::string & getName () const
Return string name of basis.
virtual void getQuadPoints (ordinal_type quad_order, Teuchos::Array< value_type > &points, Teuchos::Array< value_type > &weights, Teuchos::Array< Teuchos::Array< value_type > > &values) const
Compute quadrature points, weights, and values of basis polynomials at given set of points points.
virtual ordinal_type quadDegreeOfExactness (ordinal_type n) const
virtual ordinal_type coefficientGrowth (ordinal_type n) const
Evaluate coefficient growth rule for Smolyak-type bases.
virtual ordinal_type pointGrowth (ordinal_type n) const
Evaluate point growth rule for Smolyak-type bases.
virtual LevelToOrderFnPtr getSparseGridGrowthRule () const
Get sparse grid level_to_order mapping function.
virtual void setSparseGridGrowthRule (LevelToOrderFnPtr ptr)
Set sparse grid rule.
virtual void getRecurrenceCoefficients (Teuchos::Array< value_type > &alpha, Teuchos::Array< value_type > &beta, Teuchos::Array< value_type > &delta, Teuchos::Array< value_type > &gamma) const
Return recurrence coefficients defined by above formula.
virtual void evaluateBasesAndDerivatives (const value_type &point, Teuchos::Array< value_type > &vals, Teuchos::Array< value_type > &derivs) const
Evaluate basis polynomials and their derivatives at given point point.
virtual void setQuadZeroTol (value_type tol)
Set tolerance for zero in quad point generation.
Public Member Functions inherited from Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type >
OneDOrthogPolyBasis ()
Default constructor.
virtual ~OneDOrthogPolyBasis ()
Destructor.
virtual void setSparseGridGrowthRule (LevelToOrderFnPtr ptr)=0
Set sparse grid rule.
Implementation of Stokhos::RecurrenceBasis methods
virtual bool computeRecurrenceCoefficients (ordinal_type n, Teuchos::Array< value_type > &alpha, Teuchos::Array< value_type > &beta, Teuchos::Array< value_type > &delta, Teuchos::Array< value_type > &gamma) const
Compute recurrence coefficients.
LegendreBasis (ordinal_type p, const LegendreBasis &basis)
Copy constructor with specified order.
Additional Inherited Members
Public Types inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
typedef OneDOrthogPolyBasis< ordinal_type, value_type >::LevelToOrderFnPtr LevelToOrderFnPtr
Function pointer needed for level_to_order mappings.
Public Types inherited from Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type >
typedef int(* LevelToOrderFnPtr) (int level, int growth)
Function pointer needed for level_to_order mappings.
Protected Member Functions inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
RecurrenceBasis (const std::string &name, ordinal_type p, bool normalize, GrowthPolicy growth=SLOW_GROWTH)
Constructor to be called by derived classes.
RecurrenceBasis (ordinal_type p, const RecurrenceBasis &basis)
Copy constructor with specified order.
virtual void setup ()
Setup basis after computing recurrence coefficients.
void normalizeRecurrenceCoefficients (Teuchos::Array< value_type > &alpha, Teuchos::Array< value_type > &beta, Teuchos::Array< value_type > &delta, Teuchos::Array< value_type > &gamma) const
Normalize coefficients.
Protected Attributes inherited from Stokhos::RecurrenceBasis< ordinal_type, value_type >
std::string name
Name of basis.
ordinal_type p
Order of basis.
bool normalize
Normalize basis.
GrowthPolicy growth
Smolyak growth policy.
value_type quad_zero_tol
Tolerance for quadrature points near zero.
LevelToOrderFnPtr sparse_grid_growth_rule
Sparse grid growth rule (as determined by Pecos)
Teuchos::Array< value_type > alpha
Recurrence coefficients.
Teuchos::Array< value_type > beta
Recurrence coefficients.
Teuchos::Array< value_type > delta
Recurrence coefficients.
Teuchos::Array< value_type > gamma
Recurrence coefficients.
Teuchos::Array< value_type > norms
Norms.
Detailed Description
template<typename ordinal_type, typename value_type>
class Stokhos::LegendreBasis< ordinal_type, value_type >
Legendre polynomial basis.
Legendre polynomials are defined by the recurrence relationship
with and . The corresponding density function is
This class implements computeRecurrenceCoefficients() using the above formula.
Constructor & Destructor Documentation
LegendreBasis()
template<typename ordinal_type , typename value_type > Stokhos::LegendreBasis< ordinal_type, value_type >::LegendreBasis (ordinal_type p, bool normalize = false, Stokhos::GrowthPolicy agrowth = SLOW_GROWTH)
Constructor.
Parameters
p order of the basis
normalize whether polynomials should be given unit norm
References Stokhos::RecurrenceBasis< ordinal_type, value_type >::setSparseGridGrowthRule(), and Stokhos::RecurrenceBasis< ordinal_type, value_type >::setup().
Member Function Documentation
cloneWithOrder()
template<typename ordinal_type , typename value_type > Teuchos::RCP< Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type > > Stokhos::LegendreBasis< ordinal_type, value_type >::cloneWithOrder (ordinal_type p) const virtual
Clone this object with the option of building a higher order basis.
This method is following the Prototype pattern (see Design Pattern's textbook). The slight variation is that it allows the order of the polynomial to be modified, otherwise an exact copy is formed. The use case for this is creating basis functions for column indices in a spatially varying adaptive refinement context.
Implements Stokhos::OneDOrthogPolyBasis< ordinal_type, value_type >.
Reimplemented in Stokhos::ClenshawCurtisLegendreBasis< ordinal_type, value_type >, and Stokhos::GaussPattersonLegendreBasis< ordinal_type, value_type >.
computeRecurrenceCoefficients()
template<typename ordinal_type , typename value_type > bool Stokhos::LegendreBasis< ordinal_type, value_type >::computeRecurrenceCoefficients (ordinal_type n, Teuchos::Array< value_type > & alpha, Teuchos::Array< value_type > & beta, Teuchos::Array< value_type > & delta, Teuchos::Array< value_type > & gamma) const protected virtual
Compute recurrence coefficients.
Implements Stokhos::RecurrenceBasis< ordinal_type, value_type >.
Referenced by Stokhos::LegendreBasis< ordinal_type, value_type >::LegendreBasis().
The documentation for this class was generated from the following files:
Stokhos_LegendreBasis.hpp
Stokhos_LegendreBasisImp.hpp