Sacado: Sacado::Fad::VectorDynamicStorage< T, U > Class Template Reference
Sacado::Fad::VectorDynamicStorage< T, U > Class Template Reference
Derivative array storage class using dynamic memory allocation.
#include <Sacado_Fad_VectorDynamicStorage.hpp>
Public Types
typedef T value_type
Public Member Functions
template<typename S >
VectorDynamicStorage (const S &x, SACADO_ENABLE_VALUE_CTOR_DECL)
Default constructor.
VectorDynamicStorage (const int sz, const T &x, const DerivInit zero_out=InitDerivArray)
Constructor with size sz.
VectorDynamicStorage (const int sz, T *x, U *dx_p, const int stride, bool zero_out)
Constructor with supplied memory.
VectorDynamicStorage (const VectorDynamicStorage &x)
Copy constructor.
~VectorDynamicStorage ()
Destructor.
VectorDynamicStorage & operator= (const VectorDynamicStorage &x)
Assignment.
int size () const
Returns number of derivative components.
int length () const
Returns array length.
void resize (int sz)
Resize the derivative array to sz.
void resizeAndZero (int sz)
Resize the derivative array to sz.
void expand (int sz)
Expand derivative array to size sz.
void zero ()
Zero out derivative array.
void setMemory (int sz, T *x, U *dx_p, int stride)
Set value/derivative array memory.
const T & val () const
Returns value.
T & val ()
Returns value.
const U * dx () const
Returns derivative array.
U dx (int i) const
Returns derivative component i with bounds checking.
U & fastAccessDx (int i)
Returns derivative component i without bounds checking.
const U & fastAccessDx (int i) const
Returns derivative component i without bounds checking.
Detailed Description
template<typename T, typename U = T>
class Sacado::Fad::VectorDynamicStorage< T, U >
Derivative array storage class using dynamic memory allocation.
Constructor & Destructor Documentation
VectorDynamicStorage()
template<typename T , typename U = T> Sacado::Fad::VectorDynamicStorage< T, U >::VectorDynamicStorage (const int sz, const T & x, const DerivInit zero_out = InitDerivArray) inline
Constructor with size sz.
Initializes derivative array 0 of length sz
References Sacado::ds_array< T, isScalar >::get(), and Sacado::ds_array< T, isScalar >::get_and_fill().
Member Function Documentation
expand()
template<typename T , typename U = T> void Sacado::Fad::VectorDynamicStorage< T, U >::expand (int sz) inline
Expand derivative array to size sz.
This method preserves any existing derivative components and sets any that are added to zero.
References Sacado::ds_array< T, isScalar >::copy(), Sacado::ds_array< T, isScalar >::destroy_and_release(), Sacado::ds_array< T, isScalar >::get_and_fill(), and Sacado::ds_array< T, isScalar >::strided_zero().
resize()
template<typename T , typename U = T> void Sacado::Fad::VectorDynamicStorage< T, U >::resize (int sz) inline
Resize the derivative array to sz.
Note: This does not necessarily preserve derivative components.
References Sacado::ds_array< T, isScalar >::destroy_and_release(), and Sacado::ds_array< T, isScalar >::get_and_fill().
resizeAndZero()
template<typename T , typename U = T> void Sacado::Fad::VectorDynamicStorage< T, U >::resizeAndZero (int sz) inline
Resize the derivative array to sz.
This method doest not preserve any existing derivative components but sets any that are added to zero.
References Sacado::ds_array< T, isScalar >::destroy_and_release(), Sacado::ds_array< T, isScalar >::get_and_fill(), and Sacado::ds_array< T, isScalar >::strided_zero().
The documentation for this class was generated from the following file:
Sacado_Fad_VectorDynamicStorage.hpp