Sacado: Sacado::Fad::DynamicStorage< T, U > Class Template Reference
Sacado::Fad::DynamicStorage< T, U > Class Template Reference
Derivative array storage class using dynamic memory allocation.
#include <Sacado_Fad_DynamicStorage.hpp>
Public Types
typedef T value_type
Public Member Functions
template<typename S >
DynamicStorage (const S &x, SACADO_ENABLE_VALUE_CTOR_DECL)
Default constructor.
DynamicStorage (const int sz, const T &x, const DerivInit zero_out=InitDerivArray)
Constructor with size sz.
DynamicStorage (const DynamicStorage &x)
Copy constructor.
~DynamicStorage ()
Destructor.
DynamicStorage & operator= (const DynamicStorage &x)
Assignment.
int size () const
Returns number of derivative components.
int length () const
Returns array length.
void resize (int sz)
Resize the derivative array to sz.
void resizeAndZero (int sz)
Resize the derivative array to sz.
void expand (int sz)
Expand derivative array to size sz.
void zero ()
Zero out derivative array.
const T & val () const
Returns value.
T & val ()
Returns value.
const U * dx () const
Returns derivative array.
U dx (int i) const
Returns derivative component i with bounds checking.
U & fastAccessDx (int i)
Returns derivative component i without bounds checking.
const U & fastAccessDx (int i) const
Returns derivative component i without bounds checking.
Protected Attributes
T val_
Value.
int sz_
Derivative array size.
int len_
Derivative array length.
U * dx_
Derivative array.
Detailed Description
template<typename T, typename U = T>
class Sacado::Fad::DynamicStorage< T, U >
Derivative array storage class using dynamic memory allocation.
Constructor & Destructor Documentation
DynamicStorage()
template<typename T , typename U = T> Sacado::Fad::DynamicStorage< T, U >::DynamicStorage (const int sz, const T & x, const DerivInit zero_out = InitDerivArray) inline
Constructor with size sz.
Initializes derivative array 0 of length sz
References Sacado::Fad::DynamicStorage< T, U >::dx_, Sacado::ds_array< T, isScalar >::get(), Sacado::ds_array< T, isScalar >::get_and_fill(), and Sacado::Fad::DynamicStorage< T, U >::sz_.
Member Function Documentation
expand()
template<typename T , typename U = T> void Sacado::Fad::DynamicStorage< T, U >::expand (int sz) inline
Expand derivative array to size sz.
This method preserves any existing derivative components and sets any that are added to zero.
References Sacado::ds_array< T, isScalar >::copy(), Sacado::ds_array< T, isScalar >::destroy_and_release(), Sacado::Fad::DynamicStorage< T, U >::dx_, Sacado::ds_array< T, isScalar >::get_and_fill(), Sacado::Fad::DynamicStorage< T, U >::len_, Sacado::Fad::DynamicStorage< T, U >::sz_, and Sacado::ds_array< T, isScalar >::zero().
resize()
template<typename T , typename U = T> void Sacado::Fad::DynamicStorage< T, U >::resize (int sz) inline
Resize the derivative array to sz.
Note: This does not necessarily preserve derivative components.
References Sacado::ds_array< T, isScalar >::destroy_and_release(), Sacado::Fad::DynamicStorage< T, U >::dx_, Sacado::ds_array< T, isScalar >::get_and_fill(), Sacado::Fad::DynamicStorage< T, U >::len_, and Sacado::Fad::DynamicStorage< T, U >::sz_.
resizeAndZero()
template<typename T , typename U = T> void Sacado::Fad::DynamicStorage< T, U >::resizeAndZero (int sz) inline
Resize the derivative array to sz.
This method doest not preserve any existing derivative components but sets any that are added to zero.
References Sacado::ds_array< T, isScalar >::destroy_and_release(), Sacado::Fad::DynamicStorage< T, U >::dx_, Sacado::ds_array< T, isScalar >::get_and_fill(), Sacado::Fad::DynamicStorage< T, U >::len_, Sacado::Fad::DynamicStorage< T, U >::sz_, and Sacado::ds_array< T, isScalar >::zero().
The documentation for this class was generated from the following file:
Sacado_Fad_DynamicStorage.hpp