Sacado: Sacado::LFad::LogicalSparseImp< ValT, LogT > Class Template Reference
Sacado::LFad::LogicalSparseImp< ValT, LogT > Class Template Reference
Implementation class for computing the logical sparsity of a derivative using forward-mode AD.
#include <Sacado_LFad_LogicalSparse.hpp>
Public Types
typedef ValT value_type
Typename of values (e.g., double)
typedef ScalarType< value_type >::type scalar_type
Typename of scalar's (which may be different from ValT)
typedef LogT logical_type
Logical type (i.e., type for derivative array components (e.g., bool)
Public Types inherited from Sacado::Fad::DynamicStorage< ValT, LogT >
typedef ValT value_type
Public Member Functions
Initialization methods
LogicalSparseImp ()
Default constructor.
template<typename S >
LogicalSparseImp (const S &x, SACADO_ENABLE_VALUE_CTOR_DECL)
Constructor with supplied value x.
LogicalSparseImp (const int sz, const value_type &x)
Constructor with size sz and value x.
LogicalSparseImp (const int sz, const int i, const value_type &x)
Constructor with size sz, index i, and value x.
LogicalSparseImp (const LogicalSparseImp &x)
Copy constructor.
template<typename S >
LogicalSparseImp (const Expr< S > &x, SACADO_ENABLE_EXPR_CTOR_DECL)
Copy constructor from any Expression object.
~LogicalSparseImp ()
Destructor.
void diff (const int ith, const int n)
Set LogicalSparseImp object as the ith independent variable.
template<typename S >
SACADO_ENABLE_EXPR_FUNC (bool) isEqualTo(const Expr< S > &x) const
Returns whether two Fad objects have the same values.
Derivative accessor methods
bool hasFastAccess () const
Returns true if derivative array is not empty.
bool isPassive () const
Returns true if derivative array is empty.
void setIsConstant (bool is_const)
Set whether variable is constant.
Public Member Functions inherited from Sacado::Fad::DynamicStorage< ValT, LogT >
DynamicStorage (const S &x, SACADO_ENABLE_VALUE_CTOR_DECL)
Default constructor.
DynamicStorage (const int sz, const ValT &x, const DerivInit zero_out=InitDerivArray)
Constructor with size sz.
DynamicStorage (const DynamicStorage &x)
Copy constructor.
~DynamicStorage ()
Destructor.
DynamicStorage & operator= (const DynamicStorage &x)
Assignment.
int size () const
Returns number of derivative components.
int length () const
Returns array length.
void resize (int sz)
Resize the derivative array to sz.
void resizeAndZero (int sz)
Resize the derivative array to sz.
void expand (int sz)
Expand derivative array to size sz.
void zero ()
Zero out derivative array.
const ValT & val () const
Returns value.
ValT & val ()
Returns value.
const LogT * dx () const
Returns derivative array.
LogT dx (int i) const
Returns derivative component i with bounds checking.
LogT & fastAccessDx (int i)
Returns derivative component i without bounds checking.
const LogT & fastAccessDx (int i) const
Returns derivative component i without bounds checking.
Additional Inherited Members
Protected Attributes inherited from Sacado::Fad::DynamicStorage< ValT, LogT >
ValT val_
Value.
int sz_
Derivative array size.
int len_
Derivative array length.
LogT * dx_
Derivative array.
Detailed Description
template<typename ValT, typename LogT>
class Sacado::LFad::LogicalSparseImp< ValT, LogT >
Implementation class for computing the logical sparsity of a derivative using forward-mode AD.
Constructor & Destructor Documentation
LogicalSparseImp() [1/3]
template<typename ValT , typename LogT > template<typename S > Sacado::LFad::LogicalSparseImp< ValT, LogT >::LogicalSparseImp (const S & x, SACADO_ENABLE_VALUE_CTOR_DECL) inline
Constructor with supplied value x.
Initializes value to x and derivative array is empty
LogicalSparseImp() [2/3]
template<typename ValT , typename LogT > Sacado::LFad::LogicalSparseImp< ValT, LogT >::LogicalSparseImp (const int sz, const value_type & x) inline
Constructor with size sz and value x.
Initializes value to x and derivative array 0 of length sz
LogicalSparseImp() [3/3]
template<typename ValT , typename LogT > Sacado::LFad::LogicalSparseImp< ValT, LogT >::LogicalSparseImp (const int sz, const int i, const value_type & x) inline
Constructor with size sz, index i, and value x.
Initializes value to x and derivative array of length sz as row i of the identity matrix, i.e., sets derivative component i to 1 and all other's to zero.
References Sacado::Fad::DynamicStorage< ValT, LogT >::fastAccessDx().
Member Function Documentation
diff()
template<typename ValT , typename LogT > void Sacado::LFad::LogicalSparseImp< ValT, LogT >::diff (const int ith, const int n) inline
Set LogicalSparseImp object as the ith independent variable.
Sets the derivative array of length n to the ith row of the identity matrix and has the same affect as the Implementation(const int sz, const int i, const T & x) constructor.
References Sacado::Fad::DynamicStorage< ValT, LogT >::fastAccessDx(), Sacado::Fad::DynamicStorage< ValT, LogT >::resize(), Sacado::Fad::DynamicStorage< ValT, LogT >::size(), and Sacado::Fad::DynamicStorage< ValT, LogT >::zero().
The documentation for this class was generated from the following file:
Sacado_LFad_LogicalSparse.hpp