Sacado: Sacado::Fad::StaticStorage< T, Num > Class Template Reference
Sacado::Fad::StaticStorage< T, Num > Class Template Reference
Derivative array storage class using static memory allocation.
#include <Sacado_Fad_StaticStorage.hpp>
Public Types
typedef T value_type
Public Member Functions
template<typename S >
StaticStorage (const S &x, SACADO_ENABLE_VALUE_CTOR_DECL)
Default constructor.
StaticStorage (const int sz, const T &x, const DerivInit zero_out=InitDerivArray)
Constructor with size sz.
StaticStorage (const StaticStorage &x)
Copy constructor.
~StaticStorage ()
Destructor.
StaticStorage & operator= (const StaticStorage &x)
Assignment.
int size () const
Returns number of derivative components.
int length () const
Returns array length.
void resize (int sz)
Resize the derivative array to sz.
void resizeAndZero (int sz)
Resize the derivative array to sz.
void expand (int sz)
Expand derivative array to size sz.
void zero ()
Zero out derivative array.
const T & val () const
Returns value.
T & val ()
Returns value.
const T * dx () const
Returns derivative array.
T dx (int i) const
Returns derivative component i with bounds checking.
T & fastAccessDx (int i)
Returns derivative component i without bounds checking.
const T & fastAccessDx (int i) const
Returns derivative component i without bounds checking.
Protected Attributes
T val_
Value.
T dx_ [Num]
Derivative array.
int sz_
Size of derivative array.
Detailed Description
template<typename T, int Num>
class Sacado::Fad::StaticStorage< T, Num >
Derivative array storage class using static memory allocation.
This class uses a statically allocated array whose dimension is fixed by the template parameter Num.
Constructor & Destructor Documentation
StaticStorage()
template<typename T , int Num> Sacado::Fad::StaticStorage< T, Num >::StaticStorage (const int sz, const T & x, const DerivInit zero_out = InitDerivArray) inline
Constructor with size sz.
Initializes derivative array 0 of length sz
References Sacado::Fad::StaticStorage< T, Num >::dx_, Sacado::Fad::StaticStorage< T, Num >::sz_, and Sacado::ss_array< T, isScalar >::zero().
Member Function Documentation
expand()
template<typename T , int Num> void Sacado::Fad::StaticStorage< T, Num >::expand (int sz) inline
Expand derivative array to size sz.
This method preserves any existing derivative components and sets any that are added to zero.
References Sacado::Fad::StaticStorage< T, Num >::dx_, Sacado::Fad::StaticStorage< T, Num >::sz_, and Sacado::ss_array< T, isScalar >::zero().
resizeAndZero()
template<typename T , int Num> void Sacado::Fad::StaticStorage< T, Num >::resizeAndZero (int sz) inline
Resize the derivative array to sz.
This method doest not preserve any existing derivative components but sets any that are added to zero.
References Sacado::Fad::StaticStorage< T, Num >::dx_, Sacado::Fad::StaticStorage< T, Num >::sz_, and Sacado::ss_array< T, isScalar >::zero().
The documentation for this class was generated from the following file:
Sacado_Fad_StaticStorage.hpp