Amesos: Amesos_Lapack Class Reference
Amesos_Lapack Class Reference
Amesos_Lapack: an interface to LAPACK.
#include <Amesos_Lapack.h>
Public Member Functions
Amesos_Lapack (const Epetra_LinearProblem &LinearProblem)
Amesos_Lapack Constructor.
~Amesos_Lapack (void)
Amesos_Lapack Destructor.
int SymbolicFactorization ()
Performs SymbolicFactorization on the matrix A.
int NumericFactorization ()
Performs NumericFactorization on the matrix A.
int Solve ()
Solves A X = B (or AT x = B)
const Epetra_LinearProblem * GetProblem () const
Returns the Epetra_LinearProblem.
bool MatrixShapeOK () const
Returns true if the solver can handle this matrix shape.
int SetUseTranspose (bool UseTranspose_in)
If set true, X will be set to the solution of AT X = B (not A X = B)
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
void setParameterList (Teuchos::RCP< Teuchos::ParameterList > const &paramList)
Use this parameter list to read values from
Teuchos::RCP< Teuchos::ParameterList > unsetParameterList ()
This is an empty stub.
int SetParameters (Teuchos::ParameterList &ParameterList)
Deprecated - Sets parameters.
int GEEV (Epetra_Vector &Er, Epetra_Vector &Ei)
Computes the eigenvalues of the linear system matrix using DGEEV.
int NumSymbolicFact () const
Returns the number of symbolic factorizations performed by this object.
int NumNumericFact () const
Returns the number of numeric factorizations performed by this object.
int NumSolve () const
Returns the number of solves performed by this object.
void PrintTiming () const
Print timing information.
void PrintStatus () const
Print information about the factorization and solution phases.
void GetTiming (Teuchos::ParameterList &TimingParameterList) const
Extracts timing information from the current solver and places it in the parameter list.
Public Member Functions inherited from Amesos_BaseSolver
virtual ~Amesos_BaseSolver ()
Destructor.
virtual Teuchos::RCP< Teuchos::ParameterList > getNonconstParameterList ()
This is an empty stub.
Protected Member Functions
const Epetra_RowMatrix * Matrix () const
Returns a pointer to the linear system matrix.
int NumGlobalRows () const
Returns the number of global rows, or -1 if Matrix() returns 0.
long long NumGlobalRows64 () const
int NumMyRows () const
Returns the number of local rows, or -1 if Matrix() returns 0.
const Epetra_Map & SerialMap ()
Returns a reference to serial map (that with all elements on process 0).
Epetra_RowMatrix & SerialMatrix ()
Returns a reference to serial matrix (that with all rows on process 0).
Epetra_CrsMatrix & SerialCrsMatrix ()
const Epetra_Import & MatrixImporter ()
Returns a reference to the matrix importer (from row map to serial map).
const Epetra_Export & RhsExporter ()
Returns a reference to the rhs exporter (from range map to serial map).
const Epetra_Import & SolutionImporter ()
Returns a reference to the solution importer (to domain map from serial map).
int SolveSerial (Epetra_MultiVector &X, const Epetra_MultiVector &B)
Solves the linear system, when only one process is used.
int SolveDistributed (Epetra_MultiVector &X, const Epetra_MultiVector &B)
Solves the linear system, when more than one process is used.
int DistributedToSerial ()
Converts a distributed matrix to serial matrix.
int SerialToDense ()
Converts a serial matrix to dense format.
int DenseToFactored ()
Factors the matrix using LAPACK.
Protected Attributes
Teuchos::RCP< Teuchos::ParameterList > pl_
Teuchos::RCP< Epetra_RowMatrix > SerialMatrix_
Teuchos::RCP< Epetra_CrsMatrix > SerialCrsMatrix_
Teuchos::RCP< Epetra_Map > SerialMap_
Teuchos::RCP< Epetra_Import > MatrixImporter_
Teuchos::RCP< Epetra_Export > RhsExporter_
Teuchos::RCP< Epetra_Import > SolutionImporter_
Epetra_SerialDenseMatrix DenseMatrix_
Dense matrix.
Epetra_SerialDenseMatrix DenseLHS_
Dense LHS.
Epetra_SerialDenseMatrix DenseRHS_
Dense RHS.
Epetra_SerialDenseSolver DenseSolver_
Linear problem for dense matrix and vectors.
bool UseTranspose_
If true, the linear system with the transpose will be solved.
const Epetra_LinearProblem * Problem_
Pointer to the linear problem.
int MtxRedistTime_
Quick access ids for the individual timings.
int MtxConvTime_
int VecRedistTime_
int SymFactTime_
int NumFactTime_
int SolveTime_
long long NumGlobalRows_
long long NumGlobalNonzeros_
Teuchos::RCP< Teuchos::ParameterList > ParameterList_
Detailed Description
Amesos_Lapack: an interface to LAPACK.
Class Amesos_Lapack enables the solution of the distributed linear system, defined by an Epetra_LinearProblem, using LAPACK.
Amesos_Lapack stores the lineaar system matrix as an Epetra_SerialDensMatrix. The linear problem is an Epetra_SerialDenseProblem. Amesos_Lapack factorizes the matrix using DGETRF().
Date
Last updated on 16-Mar-05.
Author
Marzio Sala, 9214.
Constructor & Destructor Documentation
Amesos_Lapack()
Amesos_Lapack::Amesos_Lapack (const Epetra_LinearProblem & LinearProblem)
Amesos_Lapack Constructor.
Creates an Amesos_Lapack instance, using an Epetra_LinearProblem, passing in an already-defined Epetra_LinearProblem object.
Note: The operator in LinearProblem must be an Epetra_RowMatrix.
References unsetParameterList().
~Amesos_Lapack()
Amesos_Lapack::~Amesos_Lapack (void)
Amesos_Lapack Destructor.
Completely deletes an Amesos_Lapack object.
References PrintStatus(), Amesos_Status::PrintStatus_, PrintTiming(), Amesos_Status::PrintTiming_, and Amesos_Status::verbose_.
Member Function Documentation
Comm()
const Epetra_Comm & Amesos_Lapack::Comm () const inline virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Amesos_BaseSolver.
References Comm(), and GetProblem().
Referenced by Comm(), and SymbolicFactorization().
GEEV()
int Amesos_Lapack::GEEV (Epetra_Vector & Er, Epetra_Vector & Ei)
Computes the eigenvalues of the linear system matrix using DGEEV.
Parameters
Er - (Out) On processor zero only, it will contain the real component of the eigenvalues.
Ei - (Out) On processor zero only, it will contain the imaginary component of the eigenvalues.
Note
Er and Ei must have been allocated so that the local length on processor 0 equals the global size of the matrix.
References DenseMatrix_, DistributedToSerial(), Amesos_Status::IsSymbolicFactorizationOK_, SerialMap(), SerialToDense(), and SymbolicFactorization().
GetProblem()
const Epetra_LinearProblem * Amesos_Lapack::GetProblem () const inline virtual
Returns the Epetra_LinearProblem.
Warning! Do not call return->SetOperator(...) to attempt to change the Epetra_Operator object (even if the new matrix has the same structure). This new operator matrix will be ignored!
Implements Amesos_BaseSolver.
References Problem_.
Referenced by Comm(), MatrixShapeOK(), and SymbolicFactorization().
GetTiming()
void Amesos_Lapack::GetTiming (Teuchos::ParameterList & TimingParameterList) const inline virtual
Extracts timing information from the current solver and places it in the parameter list.
Reimplemented from Amesos_BaseSolver.
References Amesos_Time::GetTiming().
MatrixShapeOK()
bool Amesos_Lapack::MatrixShapeOK () const virtual
Returns true if the solver can handle this matrix shape.
Returns true if the matrix shape is one that the underlying sparse direct solver can handle. Classes that work only on square matrices should return false for rectangular matrices. Classes that work only on symmetric matrices whould return false for non-symmetric matrices.
Implements Amesos_BaseSolver.
References GetProblem().
NumericFactorization()
int Amesos_Lapack::NumericFactorization () virtual
Performs NumericFactorization on the matrix A.
In addition to performing numeric factorization on the matrix A, the call to NumericFactorization() implies that no change will be made to the underlying matrix without a subsequent call to NumericFactorization().
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
The non-zero structure of the matrix should not have changed since the last call to SymbolicFactorization().
(return -2 if the number of non-zeros changes) Other changes can have arbitrary consequences.
The distribution of the matrix should not have changed since the last call to SymbolicFactorization()
The matrix should be indexed from 0 to n-1, unless the parameter "Reindex" was set to "true" prior to the call to SymbolicFactorization().
(return -3 - if caught)
The paremeter "Reindex" should not be set to "true" except on CrsMatrices. (return -4)
The paremeter "Reindex" should not be set to "true" unless Amesos was built with EpetraExt, i.e. with –enable-epetraext on the configure line. (return -4)
Internal errors retur -5.
<br >Postconditions:
Numeric Factorization will be performed (or marked to be performed) allowing Solve() to be performed correctly despite a potential change in in the matrix values (though not in the non-zero structure).
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References DenseMatrix_, DenseToFactored(), DistributedToSerial(), Amesos_Status::IsNumericFactorizationOK_, Amesos_Status::IsSymbolicFactorizationOK_, Amesos_Status::NumNumericFact_, SerialToDense(), and SymbolicFactorization().
Referenced by Solve().
NumNumericFact()
int Amesos_Lapack::NumNumericFact () const inline virtual
Returns the number of numeric factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumNumericFact_.
NumSolve()
int Amesos_Lapack::NumSolve () const inline virtual
Returns the number of solves performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSolve_.
NumSymbolicFact()
int Amesos_Lapack::NumSymbolicFact () const inline virtual
Returns the number of symbolic factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSymbolicFact_.
PrintStatus()
void Amesos_Lapack::PrintStatus () const virtual
Print information about the factorization and solution phases.
Implements Amesos_BaseSolver.
References Amesos_Utils::PrintLine(), and UseTranspose_.
Referenced by ~Amesos_Lapack().
PrintTiming()
void Amesos_Lapack::PrintTiming () const virtual
Print timing information.
Implements Amesos_BaseSolver.
References Amesos_Time::GetTime(), MtxRedistTime_, Amesos_Status::NumNumericFact_, Amesos_Status::NumSolve_, Amesos_Status::NumSymbolicFact_, and Amesos_Utils::PrintLine().
Referenced by ~Amesos_Lapack().
setParameterList()
void Amesos_Lapack::setParameterList (Teuchos::RCP< Teuchos::ParameterList > const & paramList) virtual
Use this parameter list to read values from
Redefined from Teuchos::ParameterListAcceptor
Reimplemented from Amesos_BaseSolver.
References Amesos_Control::AddToDiag_, Amesos_Control::AddZeroToDiag_, and DenseSolver_.
Referenced by unsetParameterList().
SetParameters()
int Amesos_Lapack::SetParameters (Teuchos::ParameterList & ParameterList) virtual
Deprecated - Sets parameters.
Implements Amesos_BaseSolver.
References DenseSolver_.
SetUseTranspose()
int Amesos_Lapack::SetUseTranspose (bool UseTranspose) inline virtual
If set true, X will be set to the solution of AT X = B (not A X = B)
If the implementation of this interface does not support transpose use, this method should return a value of -1.
<br >Preconditions:
SetUseTranspose() should be called prior to the call to SymbolicFactorization() If NumericFactorization() or Solve() is called after SetUseTranspose() without an intervening call to SymbolicFactorization() the result is implementation dependent.
<br >Postconditions:
The next factorization and solve will be performed with the new value of UseTranspose.
Parameters
UseTranspose – (In) If true, solve AT X = B, otherwise solve A X = B.
Returns
Integer error code, set to 0 if successful. Set to -1 if this implementation does not support transpose.
Implements Amesos_BaseSolver.
References UseTranspose_.
Solve()
int Amesos_Lapack::Solve () virtual
Solves A X = B (or AT x = B)
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
GetProblem()->CheckInput (see Epetra_LinearProblem::CheckInput() for return values)
The non-zero structure of the matrix should not have changed since the last call to SymbolicFactorization().
The distribution of the matrix should not have changed since the last call to SymbolicFactorization()
The matrix should not have changed since the last call to NumericFactorization().
<br >Postconditions:
X will be set such that A X = B (or AT X = B), within the limits of the accuracy of the underlying solver.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References Amesos_Status::IsNumericFactorizationOK_, NumericFactorization(), Problem_, SolveDistributed(), and SolveSerial().
SymbolicFactorization()
int Amesos_Lapack::SymbolicFactorization () virtual
Performs SymbolicFactorization on the matrix A.
In addition to performing symbolic factorization on the matrix A, the call to SymbolicFactorization() implies that no change will be made to the non-zero structure of the underlying matrix without a subsequent call to SymbolicFactorization().
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
<br >Postconditions:
Symbolic Factorization will be performed (or marked to be performed) allowing NumericFactorization() and Solve() to be called.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References Amesos_Time::AddTime(), Comm(), Amesos_Time::CreateTimer(), GetProblem(), Amesos_Status::IsNumericFactorizationOK_, Amesos_Status::IsSymbolicFactorizationOK_, Matrix(), Amesos_Status::NumSymbolicFact_, Amesos_Time::ResetTimer(), SerialMap(), and UseTranspose_.
Referenced by GEEV(), and NumericFactorization().
unsetParameterList()
Teuchos::RCP< Teuchos::ParameterList > Amesos_Lapack::unsetParameterList () virtual
This is an empty stub.
Reimplemented from Amesos_BaseSolver.
References setParameterList().
Referenced by Amesos_Lapack().
UseTranspose()
bool Amesos_Lapack::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Amesos_BaseSolver.
References UseTranspose_.
Referenced by SolveDistributed(), and SolveSerial().
The documentation for this class was generated from the following files:
Amesos_Lapack.h
Amesos_Lapack.cpp