Amesos: Amesos_Pardiso Class Reference
Amesos_Pardiso Class Reference
Amesos_Pardiso: Interface to the PARDISO package.
#include <Amesos_Pardiso.h>
Public Member Functions
Amesos_Pardiso (const Epetra_LinearProblem &LinearProblem)
Constructor.
~Amesos_Pardiso ()
Destructor.
int SymbolicFactorization ()
Performs SymbolicFactorization on the matrix A.
int NumericFactorization ()
Performs NumericFactorization on the matrix A.
int Solve ()
Solves A X = B (or AT X = B)
const Epetra_LinearProblem * GetProblem () const
Get a pointer to the Problem.
bool MatrixShapeOK () const
Returns true if PARDISO can handle this matrix shape.
int SetUseTranspose (bool UseTranspose)
SetUseTranpose()
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this matrix.
int SetParameters (Teuchos::ParameterList &ParameterList)
Set parameters from the input parameters list, returns 0 if successful.
int NumSymbolicFact () const
Returns the number of symbolic factorizations performed by this object.
int NumNumericFact () const
Returns the number of numeric factorizations performed by this object.
int NumSolve () const
Returns the number of solves performed by this object.
void PrintTiming () const
Prints timing information.
void PrintStatus () const
Prints information about the factorization and solution phases.
void GetTiming (Teuchos::ParameterList &TimingParameterList) const
Extracts timing information from the current solver and places it in the parameter list.
Public Member Functions inherited from Amesos_BaseSolver
virtual ~Amesos_BaseSolver ()
Destructor.
virtual void setParameterList (Teuchos::RCP< Teuchos::ParameterList > const &paramList)
Redefined from Teuchos::ParameterListAcceptor (Does Not Work)
virtual Teuchos::RCP< Teuchos::ParameterList > getNonconstParameterList ()
This is an empty stub.
virtual Teuchos::RCP< Teuchos::ParameterList > unsetParameterList ()
This is an empty stub.
Detailed Description
Amesos_Pardiso: Interface to the PARDISO package.
Author
Marzio Sala, SNL 9214
Date
Last updated on June 2005
Member Function Documentation
Comm()
const Epetra_Comm & Amesos_Pardiso::Comm () const inline virtual
Returns a pointer to the Epetra_Comm communicator associated with this matrix.
Implements Amesos_BaseSolver.
References Comm(), and GetProblem().
Referenced by Comm(), PrintStatus(), PrintTiming(), Solve(), and SymbolicFactorization().
GetProblem()
const Epetra_LinearProblem * Amesos_Pardiso::GetProblem () const inline virtual
Get a pointer to the Problem.
Implements Amesos_BaseSolver.
Referenced by Comm(), and MatrixShapeOK().
GetTiming()
void Amesos_Pardiso::GetTiming (Teuchos::ParameterList & TimingParameterList) const inline virtual
Extracts timing information from the current solver and places it in the parameter list.
Reimplemented from Amesos_BaseSolver.
References Amesos_Time::GetTiming().
MatrixShapeOK()
bool Amesos_Pardiso::MatrixShapeOK () const virtual
Returns true if PARDISO can handle this matrix shape.
Returns true if the matrix shape is one that PARDISO can handle. PARDISO only works with square matrices.
Implements Amesos_BaseSolver.
References GetProblem().
NumericFactorization()
int Amesos_Pardiso::NumericFactorization () virtual
Performs NumericFactorization on the matrix A.
Implements Amesos_BaseSolver.
References Amesos_Status::IsNumericFactorizationOK_, Amesos_Status::IsSymbolicFactorizationOK_, Amesos_Status::NumNumericFact_, and SymbolicFactorization().
Referenced by Solve().
NumNumericFact()
int Amesos_Pardiso::NumNumericFact () const inline virtual
Returns the number of numeric factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumNumericFact_.
NumSolve()
int Amesos_Pardiso::NumSolve () const inline virtual
Returns the number of solves performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSolve_.
NumSymbolicFact()
int Amesos_Pardiso::NumSymbolicFact () const inline virtual
Returns the number of symbolic factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSymbolicFact_.
PrintStatus()
void Amesos_Pardiso::PrintStatus () const virtual
Prints information about the factorization and solution phases.
Implements Amesos_BaseSolver.
References Comm(), and Amesos_Utils::PrintLine().
Referenced by ~Amesos_Pardiso().
PrintTiming()
void Amesos_Pardiso::PrintTiming () const virtual
Prints timing information.
Implements Amesos_BaseSolver.
References Comm(), Amesos_Time::GetTime(), Amesos_Status::NumNumericFact_, Amesos_Status::NumSolve_, Amesos_Status::NumSymbolicFact_, and Amesos_Utils::PrintLine().
Referenced by ~Amesos_Pardiso().
SetParameters()
int Amesos_Pardiso::SetParameters (Teuchos::ParameterList & ParameterList) virtual
Set parameters from the input parameters list, returns 0 if successful.
Implements Amesos_BaseSolver.
References Amesos_Status::debug_.
SetUseTranspose()
int Amesos_Pardiso::SetUseTranspose (bool UseTranspose) inline virtual
SetUseTranpose()
If SetUseTranspose() is set to true, is computed.
Implements Amesos_BaseSolver.
References UseTranspose().
Solve()
int Amesos_Pardiso::Solve () virtual
Solves A X = B (or AT X = B)
Implements Amesos_BaseSolver.
References Amesos_Time::AddTime(), Comm(), Amesos_Utils::ComputeTrueResidual(), Amesos_Status::ComputeTrueResidual_, Amesos_Utils::ComputeVectorNorms(), Amesos_Status::ComputeVectorNorms_, Amesos_Status::IsNumericFactorizationOK_, NumericFactorization(), Amesos_Status::NumSolve_, Amesos_Time::ResetTimer(), and UseTranspose().
SymbolicFactorization()
int Amesos_Pardiso::SymbolicFactorization () virtual
Performs SymbolicFactorization on the matrix A.
Implements Amesos_BaseSolver.
References Comm(), Amesos_Time::CreateTimer(), Amesos_Status::IsNumericFactorizationOK_, Amesos_Status::IsSymbolicFactorizationOK_, and Amesos_Status::NumSymbolicFact_.
Referenced by NumericFactorization().
UseTranspose()
bool Amesos_Pardiso::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Amesos_BaseSolver.
Referenced by SetUseTranspose(), and Solve().
The documentation for this class was generated from the following files:
Amesos_Pardiso.h
Amesos_Pardiso.cpp