Amesos: Amesos_Superlu Class Reference
Amesos_Superlu Class Reference
Amesos_Superlu: Amesos interface to Xioye Li's SuperLU 3.0 serial code.
#include <Amesos_Superlu.h>
Public Member Functions
Amesos_Superlu (const Epetra_LinearProblem &LinearProblem)
Amesos_Superlu Constructor.
~Amesos_Superlu ()
Amesos_Superlu Destructor.
int SymbolicFactorization ()
Performs SymbolicFactorization on the matrix A.
int NumericFactorization ()
Performs NumericFactorization on the matrix A.
int Solve ()
Solves A X = B (or AT x = B)
const Epetra_LinearProblem * GetProblem () const
Returns the Epetra_LinearProblem.
bool MatrixShapeOK () const
Returns true if the solver can handle this matrix shape.
int SetUseTranspose (bool useTheTranspose)
If set true, X will be set to the solution of AT X = B (not A X = B)
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
int SetParameters (Teuchos::ParameterList &ParameterList)
Updates internal variables.
int NumSymbolicFact () const
Returns the number of symbolic factorizations performed by this object.
int NumNumericFact () const
Returns the number of numeric factorizations performed by this object.
int NumSolve () const
Returns the number of solves performed by this object.
void PrintTiming () const
Prints timing information.
void PrintStatus () const
Prints status information.
void GetTiming (Teuchos::ParameterList &TimingParameterList) const
Extracts timing information from the current solver and places it in the parameter list.
Public Member Functions inherited from Amesos_BaseSolver
virtual ~Amesos_BaseSolver ()
Destructor.
virtual void setParameterList (Teuchos::RCP< Teuchos::ParameterList > const &paramList)
Redefined from Teuchos::ParameterListAcceptor (Does Not Work)
virtual Teuchos::RCP< Teuchos::ParameterList > getNonconstParameterList ()
This is an empty stub.
virtual Teuchos::RCP< Teuchos::ParameterList > unsetParameterList ()
This is an empty stub.
Detailed Description
Amesos_Superlu: Amesos interface to Xioye Li's SuperLU 3.0 serial code.
Class Amesos_Superlu solves the linear systems of equations A X = B, where A is defined as an Epetra_RowMatrix, and X and B are two Epetra_MultiVector's.
Date
Last updated on 28-Apr-05.
Constructor & Destructor Documentation
Amesos_Superlu()
Amesos_Superlu::Amesos_Superlu (const Epetra_LinearProblem & LinearProblem)
Amesos_Superlu Constructor.
Creates an Amesos_Superlu instance, using an Epetra_LinearProblem, passing in an already-defined Epetra_LinearProblem object.
Note: The operator in LinearProblem must be an Epetra_RowMatrix.
Member Function Documentation
Comm()
const Epetra_Comm & Amesos_Superlu::Comm () const inline virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Amesos_BaseSolver.
References Comm(), and GetProblem().
Referenced by Comm(), NumericFactorization(), PrintStatus(), PrintTiming(), and Solve().
GetProblem()
const Epetra_LinearProblem * Amesos_Superlu::GetProblem () const inline virtual
Returns the Epetra_LinearProblem.
Warning! Do not call return->SetOperator(...) to attempt to change the Epetra_Operator object (even if the new matrix has the same structure). This new operator matrix will be ignored!
Implements Amesos_BaseSolver.
Referenced by Comm(), MatrixShapeOK(), PrintStatus(), and Solve().
GetTiming()
void Amesos_Superlu::GetTiming (Teuchos::ParameterList & TimingParameterList) const inline virtual
Extracts timing information from the current solver and places it in the parameter list.
Reimplemented from Amesos_BaseSolver.
References Amesos_Time::GetTiming().
MatrixShapeOK()
bool Amesos_Superlu::MatrixShapeOK () const virtual
Returns true if the solver can handle this matrix shape.
Returns true if the matrix shape is one that the underlying sparse direct solver can handle. Classes that work only on square matrices should return false for rectangular matrices. Classes that work only on symmetric matrices whould return false for non-symmetric matrices.
Implements Amesos_BaseSolver.
References GetProblem().
NumericFactorization()
int Amesos_Superlu::NumericFactorization () virtual
Performs NumericFactorization on the matrix A.
In addition to performing numeric factorization on the matrix A, the call to NumericFactorization() implies that no change will be made to the underlying matrix without a subsequent call to NumericFactorization().
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
The non-zero structure of the matrix should not have changed since the last call to SymbolicFactorization().
(return -2 if the number of non-zeros changes) Other changes can have arbitrary consequences.
The distribution of the matrix should not have changed since the last call to SymbolicFactorization()
The matrix should be indexed from 0 to n-1, unless the parameter "Reindex" was set to "true" prior to the call to SymbolicFactorization().
(return -3 - if caught)
The paremeter "Reindex" should not be set to "true" except on CrsMatrices. (return -4)
The paremeter "Reindex" should not be set to "true" unless Amesos was built with EpetraExt, i.e. with –enable-epetraext on the configure line. (return -4)
Internal errors retur -5.
<br >Postconditions:
Numeric Factorization will be performed (or marked to be performed) allowing Solve() to be performed correctly despite a potential change in in the matrix values (though not in the non-zero structure).
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References Amesos_Time::AddTime(), Comm(), Amesos_Time::CreateTimer(), Amesos_Status::NumNumericFact_, Amesos_Time::ResetTimer(), and UseTranspose().
Referenced by Solve().
NumNumericFact()
int Amesos_Superlu::NumNumericFact () const inline virtual
Returns the number of numeric factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumNumericFact_.
NumSolve()
int Amesos_Superlu::NumSolve () const inline virtual
Returns the number of solves performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSolve_.
NumSymbolicFact()
int Amesos_Superlu::NumSymbolicFact () const inline virtual
Returns the number of symbolic factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSymbolicFact_.
PrintStatus()
void Amesos_Superlu::PrintStatus () const virtual
Prints status information.
Implements Amesos_BaseSolver.
References Comm(), GetProblem(), and Amesos_Utils::PrintLine().
Referenced by ~Amesos_Superlu().
PrintTiming()
void Amesos_Superlu::PrintTiming () const virtual
Prints timing information.
Implements Amesos_BaseSolver.
References Comm(), Amesos_Time::GetTime(), Amesos_Status::NumNumericFact_, Amesos_Status::NumSolve_, and Amesos_Utils::PrintLine().
Referenced by ~Amesos_Superlu().
SetParameters()
int Amesos_Superlu::SetParameters (Teuchos::ParameterList & ParameterList) virtual
Updates internal variables.
  <br \>Preconditions:<ul>
  <li>None.</li>
  </ul>
  <br \>Postconditions:<ul>
  <li>Internal variables controlling the factorization and solve will
  be updated and take effect on all subseuent calls to NumericFactorization()
  and Solve().</li>
  <li>All parameters whose value are to differ from the default values must
be included in ParameterList. Parameters not specified in ParameterList revert to their default values.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
SetUseTranspose()
int Amesos_Superlu::SetUseTranspose (bool UseTranspose) inline virtual
If set true, X will be set to the solution of AT X = B (not A X = B)
If the implementation of this interface does not support transpose use, this method should return a value of -1.
<br >Preconditions:
SetUseTranspose() should be called prior to the call to SymbolicFactorization() If NumericFactorization() or Solve() is called after SetUseTranspose() without an intervening call to SymbolicFactorization() the result is implementation dependent.
<br >Postconditions:
The next factorization and solve will be performed with the new value of UseTranspose.
Parameters
UseTranspose – (In) If true, solve AT X = B, otherwise solve A X = B.
Returns
Integer error code, set to 0 if successful. Set to -1 if this implementation does not support transpose.
Implements Amesos_BaseSolver.
Solve()
int Amesos_Superlu::Solve () virtual
Solves A X = B (or AT x = B)
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
GetProblem()->CheckInput (see Epetra_LinearProblem::CheckInput() for return values)
The non-zero structure of the matrix should not have changed since the last call to SymbolicFactorization().
The distribution of the matrix should not have changed since the last call to SymbolicFactorization()
The matrix should not have changed since the last call to NumericFactorization().
<br >Postconditions:
X will be set such that A X = B (or AT X = B), within the limits of the accuracy of the underlying solver.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References Amesos_Time::AddTime(), Comm(), Amesos_Utils::ComputeTrueResidual(), Amesos_Status::ComputeTrueResidual_, Amesos_Utils::ComputeVectorNorms(), Amesos_Status::ComputeVectorNorms_, GetProblem(), NumericFactorization(), Amesos_Status::NumSolve_, Amesos_Time::ResetTimer(), and UseTranspose().
SymbolicFactorization()
int Amesos_Superlu::SymbolicFactorization () virtual
Performs SymbolicFactorization on the matrix A.
In addition to performing symbolic factorization on the matrix A, the call to SymbolicFactorization() implies that no change will be made to the non-zero structure of the underlying matrix without a subsequent call to SymbolicFactorization().
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
<br >Postconditions:
Symbolic Factorization will be performed (or marked to be performed) allowing NumericFactorization() and Solve() to be called.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
UseTranspose()
bool Amesos_Superlu::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Amesos_BaseSolver.
Referenced by NumericFactorization(), and Solve().
The documentation for this class was generated from the following files:
Amesos_Superlu.h
Amesos_Superlu.cpp