Amesos: Amesos_Umfpack Class Reference
Amesos_Umfpack Class Reference
Class Amesos_Umfpack: An object-oriented wrapper for UMFPACK.
#include <Amesos_Umfpack.h>
Public Member Functions
Amesos_Umfpack (const Epetra_LinearProblem &LinearProblem)
Amesos_Umfpack Constructor.
~Amesos_Umfpack (void)
Amesos_Umfpack Destructor.
int SymbolicFactorization ()
Performs SymbolicFactorization on the matrix A.
int NumericFactorization ()
Performs NumericFactorization on the matrix A.
int Solve ()
Solves A X = B (or AT x = B)
const Epetra_LinearProblem * GetProblem () const
Returns the Epetra_LinearProblem.
bool MatrixShapeOK () const
Returns true if UMFPACK can handle this matrix shape.
int SetUseTranspose (bool UseTranspose_in)
If set true, X will be set to the solution of AT X = B (not A X = B)
bool UseTranspose () const
Returns the current UseTranspose setting.
const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
double GetRcond () const
Returns an estimate of the reciprocal of the condition number.
int SetParameters (Teuchos::ParameterList &ParameterList)
Updates internal variables.
int NumSymbolicFact () const
Returns the number of symbolic factorizations performed by this object.
int NumNumericFact () const
Returns the number of numeric factorizations performed by this object.
int NumSolve () const
Returns the number of solves performed by this object.
void PrintTiming () const
Prints timing information.
void PrintStatus () const
Prints information about the factorization and solution phases.
void GetTiming (Teuchos::ParameterList &TimingParameterList) const
Extracts timing information from the current solver and places it in the parameter list.
Public Member Functions inherited from Amesos_BaseSolver
virtual ~Amesos_BaseSolver ()
Destructor.
virtual void setParameterList (Teuchos::RCP< Teuchos::ParameterList > const &paramList)
Redefined from Teuchos::ParameterListAcceptor (Does Not Work)
virtual Teuchos::RCP< Teuchos::ParameterList > getNonconstParameterList ()
This is an empty stub.
virtual Teuchos::RCP< Teuchos::ParameterList > unsetParameterList ()
This is an empty stub.
Detailed Description
Class Amesos_Umfpack: An object-oriented wrapper for UMFPACK.
Amesos_Umfpack will solve a linear systems of equations: A X = B using Epetra objects and the UMFPACK solver library, where A is an Epetra_RowMatrix and X and B are Epetra_MultiVector objects.
Constructor & Destructor Documentation
Amesos_Umfpack()
Amesos_Umfpack::Amesos_Umfpack (const Epetra_LinearProblem & LinearProblem)
Amesos_Umfpack Constructor.
Creates an Amesos_Umfpack instance, using an Epetra_LinearProblem, passing in an already-defined Epetra_LinearProblem object.
Note: The operator in LinearProblem must be an Epetra_RowMatrix.
References SetParameters().
~Amesos_Umfpack()
Amesos_Umfpack::~Amesos_Umfpack (void)
Amesos_Umfpack Destructor.
Completely deletes an Amesos_Umfpack object.
References PrintStatus(), Amesos_Status::PrintStatus_, PrintTiming(), Amesos_Status::PrintTiming_, and Amesos_Status::verbose_.
Member Function Documentation
Comm()
const Epetra_Comm & Amesos_Umfpack::Comm () const inline virtual
Returns a pointer to the Epetra_Comm communicator associated with this operator.
Implements Amesos_BaseSolver.
References Comm(), and GetProblem().
Referenced by Comm(), GetRcond(), NumericFactorization(), and SymbolicFactorization().
GetProblem()
const Epetra_LinearProblem * Amesos_Umfpack::GetProblem () const inline virtual
Returns the Epetra_LinearProblem.
Warning! Do not call return->SetOperator(...) to attempt to change the Epetra_Operator object (even if the new matrix has the same structure). This new operator matrix will be ignored!
Implements Amesos_BaseSolver.
Referenced by Comm(), and MatrixShapeOK().
GetTiming()
void Amesos_Umfpack::GetTiming (Teuchos::ParameterList & TimingParameterList) const inline virtual
Extracts timing information from the current solver and places it in the parameter list.
Reimplemented from Amesos_BaseSolver.
References Amesos_Time::GetTiming().
MatrixShapeOK()
bool Amesos_Umfpack::MatrixShapeOK () const virtual
Returns true if UMFPACK can handle this matrix shape.
Returns true if the matrix shape is one that UMFPACK can handle. UMFPACK only works with square matrices.
Implements Amesos_BaseSolver.
References GetProblem().
NumericFactorization()
int Amesos_Umfpack::NumericFactorization () virtual
Performs NumericFactorization on the matrix A.
In addition to performing numeric factorization on the matrix A, the call to NumericFactorization() implies that no change will be made to the underlying matrix without a subsequent call to NumericFactorization().
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
The non-zero structure of the matrix should not have changed since the last call to SymbolicFactorization().
(return -2 if the number of non-zeros changes) Other changes can have arbitrary consequences.
The distribution of the matrix should not have changed since the last call to SymbolicFactorization()
The matrix should be indexed from 0 to n-1, unless the parameter "Reindex" was set to "true" prior to the call to SymbolicFactorization().
(return -3 - if caught)
The paremeter "Reindex" should not be set to "true" except on CrsMatrices. (return -4)
The paremeter "Reindex" should not be set to "true" unless Amesos was built with EpetraExt, i.e. with –enable-epetraext on the configure line. (return -4)
Internal errors retur -5.
<br >Postconditions:
Numeric Factorization will be performed (or marked to be performed) allowing Solve() to be performed correctly despite a potential change in in the matrix values (though not in the non-zero structure).
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References Comm(), Amesos_Time::CreateTimer(), Amesos_Status::IsNumericFactorizationOK_, Amesos_Status::IsSymbolicFactorizationOK_, Amesos_Status::NumNumericFact_, and Amesos_Status::NumSymbolicFact_.
Referenced by Solve().
NumNumericFact()
int Amesos_Umfpack::NumNumericFact () const inline virtual
Returns the number of numeric factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumNumericFact_.
NumSolve()
int Amesos_Umfpack::NumSolve () const inline virtual
Returns the number of solves performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSolve_.
NumSymbolicFact()
int Amesos_Umfpack::NumSymbolicFact () const inline virtual
Returns the number of symbolic factorizations performed by this object.
Implements Amesos_BaseSolver.
References Amesos_Status::NumSymbolicFact_.
PrintStatus()
void Amesos_Umfpack::PrintStatus () const virtual
Prints information about the factorization and solution phases.
Implements Amesos_BaseSolver.
References Amesos_Utils::PrintLine().
Referenced by ~Amesos_Umfpack().
PrintTiming()
void Amesos_Umfpack::PrintTiming () const virtual
Prints timing information.
Implements Amesos_BaseSolver.
References Amesos_Time::GetTime(), Amesos_Status::NumNumericFact_, Amesos_Status::NumSolve_, Amesos_Status::NumSymbolicFact_, and Amesos_Utils::PrintLine().
Referenced by ~Amesos_Umfpack().
SetParameters()
int Amesos_Umfpack::SetParameters (Teuchos::ParameterList & ParameterList) virtual
Updates internal variables.
  <br \>Preconditions:<ul>
  <li>None.</li>
  </ul>
  <br \>Postconditions:<ul>
  <li>Internal variables controlling the factorization and solve will
  be updated and take effect on all subseuent calls to NumericFactorization()
  and Solve().</li>
  <li>All parameters whose value are to differ from the default values must
be included in ParameterList. Parameters not specified in ParameterList revert to their default values.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
Referenced by Amesos_Umfpack().
SetUseTranspose()
int Amesos_Umfpack::SetUseTranspose (bool UseTranspose) inline virtual
If set true, X will be set to the solution of AT X = B (not A X = B)
If the implementation of this interface does not support transpose use, this method should return a value of -1.
<br >Preconditions:
SetUseTranspose() should be called prior to the call to SymbolicFactorization() If NumericFactorization() or Solve() is called after SetUseTranspose() without an intervening call to SymbolicFactorization() the result is implementation dependent.
<br >Postconditions:
The next factorization and solve will be performed with the new value of UseTranspose.
Parameters
UseTranspose – (In) If true, solve AT X = B, otherwise solve A X = B.
Returns
Integer error code, set to 0 if successful. Set to -1 if this implementation does not support transpose.
Implements Amesos_BaseSolver.
Solve()
int Amesos_Umfpack::Solve () virtual
Solves A X = B (or AT x = B)
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
GetProblem()->CheckInput (see Epetra_LinearProblem::CheckInput() for return values)
The non-zero structure of the matrix should not have changed since the last call to SymbolicFactorization().
The distribution of the matrix should not have changed since the last call to SymbolicFactorization()
The matrix should not have changed since the last call to NumericFactorization().
<br >Postconditions:
X will be set such that A X = B (or AT X = B), within the limits of the accuracy of the underlying solver.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References Amesos_Time::AddTime(), Amesos_Utils::ComputeTrueResidual(), Amesos_Status::ComputeTrueResidual_, Amesos_Utils::ComputeVectorNorms(), Amesos_Status::ComputeVectorNorms_, Amesos_Status::IsNumericFactorizationOK_, NumericFactorization(), Amesos_Status::NumSolve_, Amesos_Time::ResetTimer(), and UseTranspose().
SymbolicFactorization()
int Amesos_Umfpack::SymbolicFactorization () virtual
Performs SymbolicFactorization on the matrix A.
In addition to performing symbolic factorization on the matrix A, the call to SymbolicFactorization() implies that no change will be made to the non-zero structure of the underlying matrix without a subsequent call to SymbolicFactorization().
<br >Preconditions:
GetProblem().GetOperator() != 0 (return -1)
MatrixShapeOk(GetProblem().GetOperator()) == true (return -6)
<br >Postconditions:
Symbolic Factorization will be performed (or marked to be performed) allowing NumericFactorization() and Solve() to be called.
Returns
Integer error code, set to 0 if successful.
Implements Amesos_BaseSolver.
References Comm(), Amesos_Time::CreateTimer(), Amesos_Status::IsNumericFactorizationOK_, Amesos_Status::IsSymbolicFactorizationOK_, and Amesos_Status::NumSymbolicFact_.
UseTranspose()
bool Amesos_Umfpack::UseTranspose () const inline virtual
Returns the current UseTranspose setting.
Implements Amesos_BaseSolver.
Referenced by Solve().
The documentation for this class was generated from the following files:
Amesos_Umfpack.h
Amesos_Umfpack.cpp