Amesos: Amesos_TestRowMatrix Class Reference
Amesos_TestRowMatrix Class Reference
Amesos_TestRowMatrix: a class to test Epetra_RowMatrix based codes.
#include <Amesos_TestRowMatrix.h>
Public Member Functions
Amesos_TestRowMatrix (Epetra_RowMatrix *Matrix_in)
Constructor.
virtual ~Amesos_TestRowMatrix ()
Destructor.
virtual int NumMyRowEntries (int MyRow, int &NumEntries) const
Returns the number of nonzero entries in MyRow.
virtual int MaxNumEntries () const
Returns the maximum of NumMyRowEntries() over all rows.
virtual int ExtractMyRowCopy (int MyRow, int Length, int &NumEntries, double *Values, int *Indices) const
Returns a copy of the specified local row in user-provided arrays.
virtual int ExtractDiagonalCopy (Epetra_Vector &Diagonal) const
Returns a copy of the main diagonal in a user-provided vector.
virtual int Multiply (bool TransA, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_RowMatrix multiplied by a Epetra_MultiVector X in Y.
virtual int Solve (bool Upper, bool Trans, bool UnitDiagonal, const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns result of a local-only solve using a triangular Epetra_RowMatrix with Epetra_MultiVectors X and Y (NOT IMPLEMENTED).
virtual int Apply (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
virtual int InvRowSums (Epetra_Vector &x) const
Computes the sum of absolute values of the rows of the Epetra_RowMatrix, results returned in x (NOT IMPLEMENTED).
virtual int LeftScale (const Epetra_Vector &x)
Scales the Epetra_RowMatrix on the left with a Epetra_Vector x (NOT IMPLEMENTED).
virtual int InvColSums (Epetra_Vector &x) const
Computes the sum of absolute values of the columns of the Epetra_RowMatrix, results returned in x (NOT IMPLEMENTED).
virtual int RightScale (const Epetra_Vector &x)
Scales the Epetra_RowMatrix on the right with a Epetra_Vector x (NOT IMPLEMENTED).
virtual bool Filled () const
If FillComplete() has been called, this query returns true, otherwise it returns false.
virtual double NormInf () const
Returns the infinity norm of the global matrix.
virtual double NormOne () const
Returns the one norm of the global matrix.
virtual int NumGlobalNonzeros () const
Returns the number of nonzero entries in the global matrix.
virtual int NumGlobalRows () const
Returns the number of global matrix rows.
virtual int NumGlobalCols () const
Returns the number of global matrix columns.
virtual int NumGlobalDiagonals () const
Returns the number of global nonzero diagonal entries, based on global row/column index comparisons.
virtual long long NumGlobalNonzeros64 () const
Returns the number of nonzero entries in the global matrix.
virtual long long NumGlobalRows64 () const
Returns the number of global matrix rows.
virtual long long NumGlobalCols64 () const
Returns the number of global matrix columns.
virtual long long NumGlobalDiagonals64 () const
Returns the number of global nonzero diagonal entries, based on global row/column index comparisons.
virtual int NumMyNonzeros () const
Returns the number of nonzero entries in the calling processor's portion of the matrix.
virtual int NumMyRows () const
Returns the number of matrix rows owned by the calling processor.
virtual int NumMyCols () const
Returns the number of matrix columns owned by the calling processor.
virtual int NumMyDiagonals () const
Returns the number of local nonzero diagonal entries, based on global row/column index comparisons.
virtual bool LowerTriangular () const
If matrix is lower triangular in local index space, this query returns true, otherwise it returns false.
virtual bool UpperTriangular () const
If matrix is upper triangular in local index space, this query returns true, otherwise it returns false.
virtual const Epetra_Map & RowMatrixRowMap () const
Returns the Epetra_Map object associated with the rows of this matrix.
virtual const Epetra_Map & RowMatrixColMap () const
Returns the Epetra_Map object associated with the columns of this matrix.
virtual const Epetra_Import * RowMatrixImporter () const
Returns the Epetra_Import object that contains the import operations for distributed operations.
int SetUseTranspose (bool UseTranspose_in)
Sets use transpose (not implemented).
bool UseTranspose () const
Returns the current UseTranspose setting.
bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
const Epetra_Comm & Comm () const
Returns a pointer to the Epetra_Comm communicator associated with this operator.
const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this operator.
const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this operator.
const Epetra_BlockMap & Map () const
const char * Label () const
Detailed Description
Amesos_TestRowMatrix: a class to test Epetra_RowMatrix based codes.
Class Amesos_TestRowMatrix enables the creation of a Epetra_RowMatrix derived class for testing purposed. This class requires another Epetra_RowMatrix as input, and minimic the behavior of this matrix. However, as it this object is not derived from Epetra_CrsMatrix or Epetra_VbrMatrix, a dynamic_cast will not result in any Epetra_CrsMatrix or Epetra_VrbMatrix object.
Author
Marzio Sala, SNL 9214
Date
Sep-04
Member Function Documentation
ExtractDiagonalCopy()
virtual int Amesos_TestRowMatrix::ExtractDiagonalCopy (Epetra_Vector & Diagonal) const inline virtual
Returns a copy of the main diagonal in a user-provided vector.
Parameters
Diagonal - (Out) Extracted main diagonal.
Returns
Integer error code, set to 0 if successful.
References ExtractDiagonalCopy().
Referenced by ExtractDiagonalCopy().
ExtractMyRowCopy()
virtual int Amesos_TestRowMatrix::ExtractMyRowCopy (int MyRow, int Length, int & NumEntries, double * Values, int * Indices) const inline virtual
Returns a copy of the specified local row in user-provided arrays.
Parameters
MyRow - (In) Local row to extract.
Length - (In) Length of Values and Indices.
NumEntries - (Out) Number of nonzero entries extracted.
Values - (Out) Extracted values for this row.
Indices - (Out) Extracted global column indices for the corresponding values.
Returns
Integer error code, set to 0 if successful.
References ExtractMyRowCopy().
Referenced by ExtractMyRowCopy().
Multiply()
virtual int Amesos_TestRowMatrix::Multiply (bool TransA, const Epetra_MultiVector & X, Epetra_MultiVector & Y) const inline virtual
Returns the result of a Epetra_RowMatrix multiplied by a Epetra_MultiVector X in Y.
Parameters
TransA -(In) If true, multiply by the transpose of matrix, otherwise just use matrix.
X - (In) A Epetra_MultiVector of dimension NumVectors to multiply with matrix.
Y -(Out) A Epetra_MultiVector of dimension NumVectorscontaining result.
Returns
Integer error code, set to 0 if successful.
References Multiply().
Referenced by Multiply().
NumMyRowEntries()
virtual int Amesos_TestRowMatrix::NumMyRowEntries (int MyRow, int & NumEntries) const inline virtual
Returns the number of nonzero entries in MyRow.
Parameters
MyRow - (In) Local row.
NumEntries - (Out) Number of nonzero values present.
Returns
Integer error code, set to 0 if successful.
References NumMyRowEntries().
Referenced by NumMyRowEntries().
The documentation for this class was generated from the following file:
Amesos_TestRowMatrix.h