Intrepid2: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Shared/Intrepid2_DataDimensionInfo.hpp File Reference
Intrepid2_DataDimensionInfo.hpp File Reference
Defines DimensionInfo struct that allows specification of a dimension within a Data object.
#include "Intrepid2_DataVariationType.hpp"
Classes
struct Intrepid2::DimensionInfo
Struct expressing all variation information about a Data object in a single dimension, including its logical extent and storage extent.
Functions
KOKKOS_INLINE_FUNCTION DimensionInfo Intrepid2::combinedDimensionInfo (const DimensionInfo &myData, const DimensionInfo &otherData)
Returns DimensionInfo for a Data container that combines (through multiplication, say, or addition) the two specified DimensionInfo specifications in one of its dimensions.
Detailed Description
Defines DimensionInfo struct that allows specification of a dimension within a Data object.
Author
Created by N.V. Roberts.
Definition in file Intrepid2_DataDimensionInfo.hpp.
Function Documentation
combinedDimensionInfo()
KOKKOS_INLINE_FUNCTION DimensionInfo Intrepid2::combinedDimensionInfo (const DimensionInfo & myData, const DimensionInfo & otherData)
Returns DimensionInfo for a Data container that combines (through multiplication, say, or addition) the two specified DimensionInfo specifications in one of its dimensions.
Definition at line 42 of file Intrepid2_DataDimensionInfo.hpp.
References Intrepid2::BLOCK_PLUS_DIAGONAL, Intrepid2::combinedDimensionInfo(), Intrepid2::CONSTANT, Intrepid2::GENERAL, INTREPID2_TEST_FOR_EXCEPTION_DEVICE_SAFE, and Intrepid2::MODULAR.
Referenced by Intrepid2::IntegrationTools< DeviceType >::allocateIntegralData(), Intrepid2::Data< DataScalar, DeviceType >::combinedDataDimensionInfo(), and Intrepid2::combinedDimensionInfo().