Intrepid2: Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType > Class Template Reference
Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType > Class Template Reference
Defines cubature (integration) rules over control volumes.
#include <Intrepid2_CubatureControlVolume.hpp>
Classes
struct Functor
Public Types
typedef Cubature< DeviceType, pointValueType, weightValueType >::PointViewType PointViewType
typedef Cubature< DeviceType, pointValueType, weightValueType >::weightViewType weightViewType
Public Types inherited from Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >
using ExecSpaceType = typename DeviceType::execution_space
using PointViewType = Kokkos::DynRankView< pointValueType, Kokkos::LayoutStride, DeviceType >
using weightViewType = Kokkos::DynRankView< weightValueType, Kokkos::LayoutStride, DeviceType >
using PointViewTypeAllocatable = Kokkos::DynRankView< pointValueType, DeviceType >
using WeightViewTypeAllocatable = Kokkos::DynRankView< weightValueType, DeviceType >
using TensorPointDataType = TensorPoints< pointValueType, DeviceType >
using TensorWeightDataType = TensorData< weightValueType, DeviceType >
Public Member Functions
virtual void getCubature (PointViewType cubPoints, weightViewType cubWeights, PointViewType cellCoords) const override
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
virtual ordinal_type getNumPoints () const override
Returns the number of cubature points.
virtual ordinal_type getDimension () const override
Returns dimension of integration domain.
virtual const char * getName () const override
Returns cubature name.
CubatureControlVolume (const shards::CellTopology cellTopology)
Public Member Functions inherited from Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >
virtual TensorPointDataType allocateCubaturePoints () const
Returns a points container appropriate for passing to getCubature().
virtual TensorWeightDataType allocateCubatureWeights () const
Returns a weight container appropriate for passing to getCubature().
virtual void getCubature (PointViewType, weightViewType) const
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
virtual void getCubature (const TensorPointDataType &tensorCubPoints, const TensorWeightDataType &tensorCubWeights) const
Returns tensor cubature points and weights. For non-tensor cubatures, the tensor structures are trivial, thin wrappers around the data returned by getCubature(). The provided containers should be pre-allocated through calls to allocateCubaturePoints() and allocateCubatureWeights().
virtual ordinal_type getAccuracy () const
Returns dimension of the integration domain.
Protected Attributes
shards::CellTopology primaryCellTopo_
The topology of the primary cell.
shards::CellTopology subcvCellTopo_
The topology of the sub-control volume.
ordinal_type degree_
The degree of the polynomials that are integrated exactly.
Kokkos::DynRankView< pointValueType, DeviceType > subcvCubaturePoints_
Kokkos::DynRankView< weightValueType, DeviceType > subcvCubatureWeights_
Detailed Description
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double>
class Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >
Defines cubature (integration) rules over control volumes.
Each primary cell contains one sub-control volume per node and there is one integration point per sub-control volume.
Definition at line 37 of file Intrepid2_CubatureControlVolume.hpp.
Member Typedef Documentation
PointViewType
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> typedef Cubature<DeviceType,pointValueType,weightValueType>::PointViewType Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::PointViewType
Definition at line 109 of file Intrepid2_CubatureControlVolume.hpp.
weightViewType
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> typedef Cubature<DeviceType,pointValueType,weightValueType>::weightViewType Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::weightViewType
Definition at line 110 of file Intrepid2_CubatureControlVolume.hpp.
Constructor & Destructor Documentation
CubatureControlVolume()
template<typename DT , typename PT , typename WT > Intrepid2::CubatureControlVolume< DT, PT, WT >::CubatureControlVolume (const shards::CellTopology cellTopology)
brief Constructor.
Parameters
cellTopology [in] - The topology of the primary cell.
Definition at line 22 of file Intrepid2_CubatureControlVolumeDef.hpp.
~CubatureControlVolume()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::~CubatureControlVolume () inline virtual
Definition at line 155 of file Intrepid2_CubatureControlVolume.hpp.
Member Function Documentation
getCubature()
template<typename DT , typename PT , typename WT > void Intrepid2::CubatureControlVolume< DT, PT, WT >::getCubature (PointViewType cubPoints, weightViewType cubWeights, PointViewType cellCoords) const override virtual
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
cellCoords [in] - Array of cell coordinates
Reimplemented from Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >.
Definition at line 59 of file Intrepid2_CubatureControlVolumeDef.hpp.
References Intrepid2::CellTools< DeviceType >::getSubcvCoords(), Intrepid2::CellTools< DeviceType >::setJacobian(), and Intrepid2::CellTools< DeviceType >::setJacobianDet().
getDimension()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual ordinal_type Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::getDimension () const inline override virtual
Returns dimension of integration domain.
Reimplemented from Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >.
Definition at line 139 of file Intrepid2_CubatureControlVolume.hpp.
References Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::primaryCellTopo_.
getName()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual const char * Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::getName () const inline override virtual
Returns cubature name.
Reimplemented from Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >.
Definition at line 147 of file Intrepid2_CubatureControlVolume.hpp.
getNumPoints()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual ordinal_type Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::getNumPoints () const inline override virtual
Returns the number of cubature points.
Reimplemented from Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >.
Definition at line 131 of file Intrepid2_CubatureControlVolume.hpp.
References Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::primaryCellTopo_.
Member Data Documentation
degree_
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> ordinal_type Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::degree_ protected
The degree of the polynomials that are integrated exactly.
Definition at line 102 of file Intrepid2_CubatureControlVolume.hpp.
primaryCellTopo_
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> shards::CellTopology Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::primaryCellTopo_ protected
The topology of the primary cell.
Definition at line 94 of file Intrepid2_CubatureControlVolume.hpp.
Referenced by Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::getDimension(), and Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::getNumPoints().
subcvCellTopo_
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> shards::CellTopology Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::subcvCellTopo_ protected
The topology of the sub-control volume.
Definition at line 98 of file Intrepid2_CubatureControlVolume.hpp.
subcvCubaturePoints_
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> Kokkos::DynRankView<pointValueType, DeviceType> Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::subcvCubaturePoints_ protected
Definition at line 105 of file Intrepid2_CubatureControlVolume.hpp.
subcvCubatureWeights_
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> Kokkos::DynRankView<weightValueType,DeviceType> Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >::subcvCubatureWeights_ protected
Definition at line 106 of file Intrepid2_CubatureControlVolume.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Integration/Intrepid2_CubatureControlVolume.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Integration/Intrepid2_CubatureControlVolumeDef.hpp