Intrepid2: Intrepid2::ProjectionStruct< DeviceType, ValueType > Class Template Reference
Intrepid2::ProjectionStruct< DeviceType, ValueType > Class Template Reference
An helper class to compute the evaluation points and weights needed for performing projections.
#include <Intrepid2_ProjectionStruct.hpp>
Public Types
enum EvalPointsType { BASIS , TARGET }
using range_type = Kokkos::pair< ordinal_type, ordinal_type >
using HostExecutionSpaceType = Kokkos::DefaultHostExecutionSpace
using HostMemorySpaceType = Kokkos::HostSpace
using MemSpaceType = typename DeviceType::memory_space
using HostDeviceType = Kokkos::Device< HostExecutionSpaceType, HostMemorySpaceType >
using view_type = Kokkos::DynRankView< ValueType, DeviceType >
using host_view_type = Kokkos::DynRankView< ValueType, HostDeviceType >
using range_tag = Kokkos::View< range_type **, HostDeviceType >
using view_tag = std::array< std::array< host_view_type, maxSubCellsCount >, numberSubCellDims >
using key_tag = Kokkos::View< unsigned **, HostDeviceType >
Public Member Functions
ordinal_type getNumBasisEvalPoints ()
Returns number of basis evaluation points.
ordinal_type getNumBasisDerivEvalPoints ()
Returns number of evaluation points for basis derivatives.
ordinal_type getNumTargetEvalPoints ()
Returns number of points where to evaluate the target function.
ordinal_type getNumTargetDerivEvalPoints ()
Returns number of points where to evaluate the derivatives of the target function.
ordinal_type getMaxNumDerivPoints (const EvalPointsType type) const
Returns the maximum number of derivative evaluation points across all the subcells.
ordinal_type getMaxNumEvalPoints (const EvalPointsType type) const
Returns the maximum number of evaluation points across all the subcells.
host_view_type getBasisEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the basis evaluation points on a subcell.
host_view_type getBasisDerivEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the evaluation points for basis derivatives on a subcell.
host_view_type getTargetEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the points where to evaluate the target function on a subcell.
host_view_type getTargetDerivEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the points where to evaluate the derivatives of the target function on a subcell.
host_view_type getEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId, EvalPointsType type) const
Returns the basis/target evaluation points on a subcell.
view_type getAllEvalPoints (EvalPointsType type=TARGET) const
Returns the basis/target evaluation points in the cell.
host_view_type getDerivEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId, EvalPointsType type) const
Returns the evaluation points for basis/target derivatives on a subcell.
view_type getAllDerivEvalPoints (EvalPointsType type=TARGET) const
Returns all the evaluation points for basis/target derivatives in the cell.
host_view_type getBasisEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the basis evaluation weights on a subcell.
host_view_type getBasisDerivEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the basis derivatives evaluation weights on a subcell.
host_view_type getTargetEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the function evaluation weights on a subcell.
host_view_type getTargetDerivEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId)
Returns the function derivatives evaluation weights on a subcell.
const range_tag getBasisPointsRange () const
Returns the range tag of the basis evaluation points subcells.
const range_tag getPointsRange (const EvalPointsType type) const
Returns the range tag of the basis/target evaluation points in subcells.
const range_tag getBasisDerivPointsRange () const
Returns the range tag of the derivative evaluation points on subcell.
const range_tag getDerivPointsRange (const EvalPointsType type) const
Returns the range tag of the basis/target derivative evaluation points on subcells.
const range_tag getTargetPointsRange () const
Returns the range of the target function evaluation points on subcells.
const range_tag getTargetDerivPointsRange () const
Returns the range tag of the target function derivative evaluation points on subcells.
const key_tag getTopologyKey () const
Returns the key tag for subcells.
template<typename BasisPtrType >
void createL2ProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree)
Initialize the ProjectionStruct for L2 projections.
template<typename BasisPtrType >
void createL2DGProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree)
Initialize the ProjectionStruct for (discontinuous local-L2) projection.
template<typename BasisPtrType >
void createHGradProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree, const ordinal_type targetGradCubDegre)
Initialize the ProjectionStruct for HGRAD projections.
template<typename BasisPtrType >
void createHCurlProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree, const ordinal_type targetCurlCubDegre)
Initialize the ProjectionStruct for HCURL projections.
template<typename BasisPtrType >
void createHDivProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree, const ordinal_type targetDivCubDegre)
Initialize the ProjectionStruct for HDIV projections.
template<typename BasisPtrType >
void createHVolProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree)
Initialize the ProjectionStruct for HVOL (local-L2) projection.
Public Attributes
key_tag subCellTopologyKey
range_tag basisPointsRange
range_tag basisDerivPointsRange
range_tag targetPointsRange
range_tag targetDerivPointsRange
view_tag basisCubPoints
view_tag basisCubWeights
view_tag basisDerivCubPoints
view_tag basisDerivCubWeights
view_tag targetCubPoints
view_tag targetCubWeights
view_tag targetDerivCubPoints
view_tag targetDerivCubWeights
view_type allBasisEPoints
view_type allBasisDerivEPoints
view_type allTargetEPoints
view_type allTargetDerivEPoints
ordinal_type numBasisEvalPoints
ordinal_type numBasisDerivEvalPoints
ordinal_type numTargetEvalPoints
ordinal_type numTargetDerivEvalPoints
ordinal_type maxNumBasisEvalPoints
ordinal_type maxNumTargetEvalPoints
ordinal_type maxNumBasisDerivEvalPoints
ordinal_type maxNumTargetDerivEvalPoints
Static Public Attributes
static constexpr int numberSubCellDims = 4
static constexpr int maxSubCellsCount = 12
Detailed Description
template<typename DeviceType, typename ValueType>
class Intrepid2::ProjectionStruct< DeviceType, ValueType >
An helper class to compute the evaluation points and weights needed for performing projections.
In order to perform projections, the basis functions and the target function need to be evaluated at several sets of evaluation points (cubature points) defined on subcell entities (edges, faces, volumes). Depending on the projection, the evaluation of derivatives of the basis functions and of the target function may be needed as well. This class provides a struct to store the evaluation points/weights on the reference cell.
Use: create the proper ProjectionStruct rule by calling one of the functions: createL2ProjectionStruct, createHGradProjectionStruct, createHCurlProjectionStruct, createHDivProjectionStruct, createHVolProjectionStruct, depending on the type of projection wanted.
The created class is then used with the Projection Tools. See ProjectionTools class for more info.
Definition at line 54 of file Intrepid2_ProjectionStruct.hpp.
Member Typedef Documentation
host_view_type
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::host_view_type = Kokkos::DynRankView<ValueType,HostDeviceType >
Definition at line 65 of file Intrepid2_ProjectionStruct.hpp.
HostDeviceType
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::HostDeviceType = Kokkos::Device<HostExecutionSpaceType,HostMemorySpaceType>
Definition at line 63 of file Intrepid2_ProjectionStruct.hpp.
HostExecutionSpaceType
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::HostExecutionSpaceType = Kokkos::DefaultHostExecutionSpace
Definition at line 60 of file Intrepid2_ProjectionStruct.hpp.
HostMemorySpaceType
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::HostMemorySpaceType = Kokkos::HostSpace
Definition at line 61 of file Intrepid2_ProjectionStruct.hpp.
key_tag
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::key_tag = Kokkos::View<unsigned**,HostDeviceType >
Definition at line 73 of file Intrepid2_ProjectionStruct.hpp.
MemSpaceType
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::MemSpaceType = typename DeviceType::memory_space
Definition at line 62 of file Intrepid2_ProjectionStruct.hpp.
range_tag
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::range_tag = Kokkos::View<range_type**,HostDeviceType>
Definition at line 66 of file Intrepid2_ProjectionStruct.hpp.
range_type
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::range_type = Kokkos::pair<ordinal_type,ordinal_type>
Definition at line 59 of file Intrepid2_ProjectionStruct.hpp.
view_tag
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::view_tag = std::array<std::array<host_view_type, maxSubCellsCount>, numberSubCellDims>
Definition at line 72 of file Intrepid2_ProjectionStruct.hpp.
view_type
template<typename DeviceType , typename ValueType > using Intrepid2::ProjectionStruct< DeviceType, ValueType >::view_type = Kokkos::DynRankView<ValueType,DeviceType >
Definition at line 64 of file Intrepid2_ProjectionStruct.hpp.
Member Enumeration Documentation
EvalPointsType
template<typename DeviceType , typename ValueType > enum Intrepid2::ProjectionStruct::EvalPointsType
Definition at line 57 of file Intrepid2_ProjectionStruct.hpp.
Member Function Documentation
createHCurlProjectionStruct()
template<typename DeviceType , typename ValueType > template<typename BasisPtrType > void Intrepid2::ProjectionStruct< DeviceType, ValueType >::createHCurlProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree, const ordinal_type targetCurlCubDegre)
Initialize the ProjectionStruct for HCURL projections.
Parameters
cellBasis [in] - HCURL basis functions for the projection
targetCubDegree [in] - degree of the cubature needed to integrate the target function
targetGradCubDegre [in] - degree of the cubature needed to integrate the derivative of target function
Definition at line 357 of file Intrepid2_ProjectionStructDef.hpp.
References Intrepid2::DefaultCubatureFactory::create(), Intrepid2::RefSubcellParametrization< DeviceType >::get(), and Intrepid2::CellTools< DeviceType >::mapToReferenceSubcell().
createHDivProjectionStruct()
template<typename DeviceType , typename ValueType > template<typename BasisPtrType > void Intrepid2::ProjectionStruct< DeviceType, ValueType >::createHDivProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree, const ordinal_type targetDivCubDegre)
Initialize the ProjectionStruct for HDIV projections.
Parameters
cellBasis [in] - HDIV basis functions for the projection
targetCubDegree [in] - degree of the cubature needed to integrate the target function
targetGradCubDegre [in] - degree of the cubature needed to integrate the derivative of target function
Definition at line 531 of file Intrepid2_ProjectionStructDef.hpp.
References Intrepid2::DefaultCubatureFactory::create(), Intrepid2::RefSubcellParametrization< DeviceType >::get(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCount(), and Intrepid2::CellTools< DeviceType >::mapToReferenceSubcell().
createHGradProjectionStruct()
template<typename DeviceType , typename ValueType > template<typename BasisPtrType > void Intrepid2::ProjectionStruct< DeviceType, ValueType >::createHGradProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree, const ordinal_type targetGradCubDegre)
Initialize the ProjectionStruct for HGRAD projections.
Parameters
cellBasis [in] - HGRAD basis functions for the projection
targetCubDegree [in] - degree of the cubature needed to integrate the target function
targetGradCubDegre [in] - degree of the cubature needed to integrate the derivative of target function
Definition at line 201 of file Intrepid2_ProjectionStructDef.hpp.
References Intrepid2::DefaultCubatureFactory::create(), Intrepid2::RefSubcellParametrization< DeviceType >::get(), Intrepid2::CellTools< DeviceType >::getReferenceVertex(), and Intrepid2::CellTools< DeviceType >::mapToReferenceSubcell().
Referenced by Intrepid2::ProjectedGeometry< spaceDim, PointScalar, DeviceType >::projectOntoHGRADBasis().
createHVolProjectionStruct()
template<typename DeviceType , typename ValueType > template<typename BasisPtrType > void Intrepid2::ProjectionStruct< DeviceType, ValueType >::createHVolProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree)
Initialize the ProjectionStruct for HVOL (local-L2) projection.
Parameters
cellBasis [in] - HVOL basis functions for the projection
targetCubDegree [in] - degree of the cubature needed to integrate the target function
Definition at line 683 of file Intrepid2_ProjectionStructDef.hpp.
References Intrepid2::DefaultCubatureFactory::create().
Referenced by Intrepid2::ProjectionStruct< DeviceType, ValueType >::createL2DGProjectionStruct().
createL2DGProjectionStruct()
template<typename DeviceType , typename ValueType > template<typename BasisPtrType > void Intrepid2::ProjectionStruct< DeviceType, ValueType >::createL2DGProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree) inline
Initialize the ProjectionStruct for (discontinuous local-L2) projection.
Parameters
cellBasis [in] - basis functions for the projection
targetCubDegree [in] - degree of the cubature needed to integrate the target function
Definition at line 422 of file Intrepid2_ProjectionStruct.hpp.
References Intrepid2::ProjectionStruct< DeviceType, ValueType >::createHVolProjectionStruct().
createL2ProjectionStruct()
template<typename DeviceType , typename ValueType > template<typename BasisPtrType > void Intrepid2::ProjectionStruct< DeviceType, ValueType >::createL2ProjectionStruct (const BasisPtrType cellBasis, const ordinal_type targetCubDegree)
Initialize the ProjectionStruct for L2 projections.
Parameters
cellBasis [in] - basis functions for the projection
targetCubDegree [in] - degree of the cubature needed to integrate the target function
Definition at line 33 of file Intrepid2_ProjectionStructDef.hpp.
References Intrepid2::DefaultCubatureFactory::create(), Intrepid2::RefSubcellParametrization< DeviceType >::get(), Intrepid2::CellTools< DeviceType >::getReferenceVertex(), and Intrepid2::CellTools< DeviceType >::mapToReferenceSubcell().
Referenced by Intrepid2::ProjectionTools< DeviceType >::projectField().
getAllDerivEvalPoints()
template<typename DeviceType , typename ValueType > view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllDerivEvalPoints (EvalPointsType type = TARGET) const inline
Returns all the evaluation points for basis/target derivatives in the cell.
P  - num. evaluation points
D  - spatial dimension of the cell
Parameters
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
a rank-2 view (P,D) containing the basis/target derivatives evaluation points in the cell
Definition at line 267 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs(), and Intrepid2::ProjectedGeometry< spaceDim, PointScalar, DeviceType >::projectOntoHGRADBasis().
getAllEvalPoints()
template<typename DeviceType , typename ValueType > view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllEvalPoints (EvalPointsType type = TARGET) const inline
Returns the basis/target evaluation points in the cell.
P  - num. evaluation points
D  - spatial dimension of the cell
Parameters
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
a rank-2 view (P,D) containing the basis/target function evaluation points in the cell
Definition at line 227 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHVolBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::projectField(), and Intrepid2::ProjectedGeometry< spaceDim, PointScalar, DeviceType >::projectOntoHGRADBasis().
getBasisDerivEvalPoints()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the evaluation points for basis derivatives on a subcell.
P  - num. evaluation points
D  - spatial dimension
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-2 view (P,D) containing the basis derivatives evaluation points on the selected subcell
Definition at line 155 of file Intrepid2_ProjectionStruct.hpp.
getBasisDerivEvalWeights()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the basis derivatives evaluation weights on a subcell.
P  - num. evaluation points
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-1 view (P) containing the basis derivatives evaluation weights on the selected subcell
Definition at line 302 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs().
getBasisDerivPointsRange()
template<typename DeviceType , typename ValueType > const range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivPointsRange () const inline
Returns the range tag of the derivative evaluation points on subcell.
Returns
the range tag of the basis derivative evaluation points corresponding on subcell
Definition at line 365 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs().
getBasisEvalPoints()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the basis evaluation points on a subcell.
P  - num. evaluation points
D  - spatial dimension
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-2 view (P,D) containing the basis evaluation points on the selected subcell
Definition at line 138 of file Intrepid2_ProjectionStruct.hpp.
getBasisEvalWeights()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the basis evaluation weights on a subcell.
P  - num. evaluation points
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-1 view (P) containing the basis evaluation weights on the selected subcell
Definition at line 286 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHVolBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getL2DGBasisCoeffs().
getBasisPointsRange()
template<typename DeviceType , typename ValueType > const range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisPointsRange () const inline
Returns the range tag of the basis evaluation points subcells.
Returns
the range tag of the basis evaluation points on subcells
Definition at line 343 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHVolBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs().
getDerivEvalPoints()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getDerivEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId, EvalPointsType type) const inline
Returns the evaluation points for basis/target derivatives on a subcell.
P  - num. evaluation points
D  - spatial dimension
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
a rank-2 view (P,D) containing the basis/target derivatives evaluation points on the selected subcell
Definition at line 248 of file Intrepid2_ProjectionStruct.hpp.
getDerivPointsRange()
template<typename DeviceType , typename ValueType > const range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::getDerivPointsRange (const EvalPointsType type) const inline
Returns the range tag of the basis/target derivative evaluation points on subcells.
Parameters
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
the range tag of the basis/target derivative evaluation points on subcells
Definition at line 375 of file Intrepid2_ProjectionStruct.hpp.
getEvalPoints()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId, EvalPointsType type) const inline
Returns the basis/target evaluation points on a subcell.
P  - num. evaluation points
D  - spatial dimension
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
a rank-2 view (P,D) containing the basis/target function evaluation points on the selected subcell
Definition at line 208 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getL2DGBasisCoeffs().
getMaxNumDerivPoints()
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getMaxNumDerivPoints (const EvalPointsType type) const inline
Returns the maximum number of derivative evaluation points across all the subcells.
Parameters
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
the maximum number of the derivative evaluation points across all the subcells
Definition at line 106 of file Intrepid2_ProjectionStruct.hpp.
getMaxNumEvalPoints()
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getMaxNumEvalPoints (const EvalPointsType type) const inline
Returns the maximum number of evaluation points across all the subcells.
Parameters
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
the maximum number of the evaluation points across all the subcells
Definition at line 119 of file Intrepid2_ProjectionStruct.hpp.
getNumBasisDerivEvalPoints()
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisDerivEvalPoints () inline
Returns number of evaluation points for basis derivatives.
Definition at line 84 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs().
getNumBasisEvalPoints()
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisEvalPoints () inline
Returns number of basis evaluation points.
Definition at line 78 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getL2DGBasisCoeffs().
getNumTargetDerivEvalPoints()
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetDerivEvalPoints () inline
Returns number of points where to evaluate the derivatives of the target function.
Definition at line 96 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs().
getNumTargetEvalPoints()
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetEvalPoints () inline
Returns number of points where to evaluate the target function.
Definition at line 90 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs().
getPointsRange()
template<typename DeviceType , typename ValueType > const range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::getPointsRange (const EvalPointsType type) const inline
Returns the range tag of the basis/target evaluation points in subcells.
Parameters
evalPointType [in] - enum selecting whether the points should be computed for the basis functions or for the target function
Returns
the range tag of the basis/target evaluation points on subcells
Definition at line 353 of file Intrepid2_ProjectionStruct.hpp.
getTargetDerivEvalPoints()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the points where to evaluate the derivatives of the target function on a subcell.
P  - num. evaluation points
D  - spatial dimension
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-2 view (P,D) containing the target derivatives evaluation points on the selected subcell
Definition at line 189 of file Intrepid2_ProjectionStruct.hpp.
getTargetDerivEvalWeights()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the function derivatives evaluation weights on a subcell.
P  - num. evaluation points
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-1 view (P) containing the target derivatives evaluation weights on the selected subcell
Definition at line 334 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs().
getTargetDerivPointsRange()
template<typename DeviceType , typename ValueType > const range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivPointsRange () const inline
Returns the range tag of the target function derivative evaluation points on subcells.
Returns
the range of the target function derivative evaluation points corresponding on subcells
Definition at line 396 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs().
getTargetEvalPoints()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetEvalPoints (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the points where to evaluate the target function on a subcell.
P  - num. evaluation points
D  - spatial dimension
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-2 view (P,D) containing the target evaluation points on the selected subcell
Definition at line 172 of file Intrepid2_ProjectionStruct.hpp.
getTargetEvalWeights()
template<typename DeviceType , typename ValueType > host_view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetEvalWeights (const ordinal_type subCellDim, const ordinal_type subCellId) inline
Returns the function evaluation weights on a subcell.
P  - num. evaluation points
Parameters
subCellDim [in] - dimension of the subcell
subCellId [in] - ordinal of the subcell defined by cell topology
Returns
a rank-1 view (P) containing the target evaluation weights on the selected subcell
Definition at line 318 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHVolBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getL2DGBasisCoeffs().
getTargetPointsRange()
template<typename DeviceType , typename ValueType > const range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetPointsRange () const inline
Returns the range of the target function evaluation points on subcells.
Returns
the range of the target function evaluation points corresponding on subcells
Definition at line 387 of file Intrepid2_ProjectionStruct.hpp.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHVolBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs().
getTopologyKey()
template<typename DeviceType , typename ValueType > const key_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTopologyKey () const inline
Returns the key tag for subcells.
Returns
the key tag of the selected subcells
Definition at line 404 of file Intrepid2_ProjectionStruct.hpp.
Member Data Documentation
allBasisDerivEPoints
template<typename DeviceType , typename ValueType > view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::allBasisDerivEPoints
Definition at line 482 of file Intrepid2_ProjectionStruct.hpp.
allBasisEPoints
template<typename DeviceType , typename ValueType > view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::allBasisEPoints
Definition at line 481 of file Intrepid2_ProjectionStruct.hpp.
allTargetDerivEPoints
template<typename DeviceType , typename ValueType > view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::allTargetDerivEPoints
Definition at line 484 of file Intrepid2_ProjectionStruct.hpp.
allTargetEPoints
template<typename DeviceType , typename ValueType > view_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::allTargetEPoints
Definition at line 483 of file Intrepid2_ProjectionStruct.hpp.
basisCubPoints
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::basisCubPoints
Definition at line 473 of file Intrepid2_ProjectionStruct.hpp.
basisCubWeights
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::basisCubWeights
Definition at line 474 of file Intrepid2_ProjectionStruct.hpp.
basisDerivCubPoints
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::basisDerivCubPoints
Definition at line 475 of file Intrepid2_ProjectionStruct.hpp.
basisDerivCubWeights
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::basisDerivCubWeights
Definition at line 476 of file Intrepid2_ProjectionStruct.hpp.
basisDerivPointsRange
template<typename DeviceType , typename ValueType > range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::basisDerivPointsRange
Definition at line 470 of file Intrepid2_ProjectionStruct.hpp.
basisPointsRange
template<typename DeviceType , typename ValueType > range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::basisPointsRange
Definition at line 469 of file Intrepid2_ProjectionStruct.hpp.
maxNumBasisDerivEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::maxNumBasisDerivEvalPoints
Definition at line 491 of file Intrepid2_ProjectionStruct.hpp.
maxNumBasisEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::maxNumBasisEvalPoints
Definition at line 489 of file Intrepid2_ProjectionStruct.hpp.
maxNumTargetDerivEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::maxNumTargetDerivEvalPoints
Definition at line 492 of file Intrepid2_ProjectionStruct.hpp.
maxNumTargetEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::maxNumTargetEvalPoints
Definition at line 490 of file Intrepid2_ProjectionStruct.hpp.
maxSubCellsCount
template<typename DeviceType , typename ValueType > constexpr int Intrepid2::ProjectionStruct< DeviceType, ValueType >::maxSubCellsCount = 12 static constexpr
Definition at line 71 of file Intrepid2_ProjectionStruct.hpp.
numBasisDerivEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::numBasisDerivEvalPoints
Definition at line 486 of file Intrepid2_ProjectionStruct.hpp.
numBasisEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::numBasisEvalPoints
Definition at line 485 of file Intrepid2_ProjectionStruct.hpp.
numberSubCellDims
template<typename DeviceType , typename ValueType > constexpr int Intrepid2::ProjectionStruct< DeviceType, ValueType >::numberSubCellDims = 4 static constexpr
Definition at line 67 of file Intrepid2_ProjectionStruct.hpp.
numTargetDerivEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::numTargetDerivEvalPoints
Definition at line 488 of file Intrepid2_ProjectionStruct.hpp.
numTargetEvalPoints
template<typename DeviceType , typename ValueType > ordinal_type Intrepid2::ProjectionStruct< DeviceType, ValueType >::numTargetEvalPoints
Definition at line 487 of file Intrepid2_ProjectionStruct.hpp.
subCellTopologyKey
template<typename DeviceType , typename ValueType > key_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::subCellTopologyKey
Definition at line 468 of file Intrepid2_ProjectionStruct.hpp.
targetCubPoints
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::targetCubPoints
Definition at line 477 of file Intrepid2_ProjectionStruct.hpp.
targetCubWeights
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::targetCubWeights
Definition at line 478 of file Intrepid2_ProjectionStruct.hpp.
targetDerivCubPoints
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::targetDerivCubPoints
Definition at line 479 of file Intrepid2_ProjectionStruct.hpp.
targetDerivCubWeights
template<typename DeviceType , typename ValueType > view_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::targetDerivCubWeights
Definition at line 480 of file Intrepid2_ProjectionStruct.hpp.
targetDerivPointsRange
template<typename DeviceType , typename ValueType > range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::targetDerivPointsRange
Definition at line 472 of file Intrepid2_ProjectionStruct.hpp.
targetPointsRange
template<typename DeviceType , typename ValueType > range_tag Intrepid2::ProjectionStruct< DeviceType, ValueType >::targetPointsRange
Definition at line 471 of file Intrepid2_ProjectionStruct.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionStruct.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionStructDef.hpp