Intrepid2: Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType > Class Template Reference
Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType > Class Template Reference
Implementation of the default H(div)-compatible Raviart-Thomas basis of arbitrary degree on Tetrahedral cells.
#include <Intrepid2_HDIV_TET_In_FEM.hpp>
Public Types
using BasisBase = Basis< DeviceType, outputValueType, pointValueType >
using OrdinalTypeArray1DHost = typename BasisBase::OrdinalTypeArray1DHost
using OrdinalTypeArray2DHost = typename BasisBase::OrdinalTypeArray2DHost
using OrdinalTypeArray3DHost = typename BasisBase::OrdinalTypeArray3DHost
using OutputViewType = typename BasisBase::OutputViewType
using PointViewType = typename BasisBase::PointViewType
using ScalarViewType = typename BasisBase::ScalarViewType
using scalarType = typename BasisBase::scalarType
Public Types inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
using DeviceType = Device
(Kokkos) Device type on which Basis is templated. Does not necessarily return true for Kokkos::is_device (may be Kokkos::Serial, for example).
using ExecutionSpace = typename DeviceType::execution_space
(Kokkos) Execution space for basis.
using OutputValueType = outputValueType
Output value type for basis; default is double.
using PointValueType = pointValueType
Point value type for basis; default is double.
using OrdinalViewType = Kokkos::View< ordinal_type, DeviceType >
View type for ordinal.
using EBasisViewType = Kokkos::View< EBasis, DeviceType >
View for basis type.
using ECoordinatesViewType = Kokkos::View< ECoordinates, DeviceType >
View for coordinate system type.
using OrdinalTypeArray1DHost = Kokkos::View< ordinal_type *, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 1d host array.
using OrdinalTypeArray2DHost = Kokkos::View< ordinal_type **, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 2d host array.
using OrdinalTypeArray3DHost = Kokkos::View< ordinal_type ***, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 3d host array.
using OrdinalTypeArrayStride1DHost = Kokkos::View< ordinal_type *, Kokkos::LayoutStride, Kokkos::HostSpace >
View type for 1d host array.
using OrdinalTypeArray1D = Kokkos::View< ordinal_type *, DeviceType >
View type for 1d device array.
using OrdinalTypeArray2D = Kokkos::View< ordinal_type **, DeviceType >
View type for 2d device array.
using OrdinalTypeArray3D = Kokkos::View< ordinal_type ***, DeviceType >
View type for 3d device array.
using OrdinalTypeArrayStride1D = Kokkos::View< ordinal_type *, Kokkos::LayoutStride, DeviceType >
View type for 1d device array.
typedef ScalarTraits< pointValueType >::scalar_type scalarType
Scalar type for point values.
using OutputViewType = Kokkos::DynRankView< OutputValueType, Kokkos::LayoutStride, DeviceType >
View type for basis value output.
using PointViewType = Kokkos::DynRankView< PointValueType, Kokkos::LayoutStride, DeviceType >
View type for input points.
using ScalarViewType = Kokkos::DynRankView< scalarType, Kokkos::LayoutStride, DeviceType >
View type for scalars.
Public Member Functions
Basis_HDIV_TET_In_FEM (const ordinal_type order, const EPointType pointType=POINTTYPE_EQUISPACED)
Constructor.
virtual void getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const override
virtual void getScratchSpaceSize (ordinal_type &perTeamSpaceSize, ordinal_type &perThreadSpaceSize, const PointViewType inputPointsconst, const EOperator operatorType=OPERATOR_VALUE) const override
virtual KOKKOS_INLINE_FUNCTION void getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType, const typename Kokkos::TeamPolicy< typename DeviceType::execution_space >::member_type &team_member, const typename DeviceType::execution_space::scratch_memory_space &scratchStorage, const ordinal_type subcellDim=-1, const ordinal_type subcellOrdinal=-1) const override
virtual void getDofCoords (ScalarViewType dofCoords) const override
Returns spatial locations (coordinates) of degrees of freedom on the reference cell.
virtual void getDofCoeffs (ScalarViewType dofCoeffs) const override
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords(i)) \cdot dofCoeffs(i) are the nodal coefficients associated to basis function i.
void getExpansionCoeffs (ScalarViewType coeffs) const
virtual const char * getName () const override
Returns basis name.
virtual bool requireOrientation () const override
True if orientation is required.
BasisPtr< DeviceType, outputValueType, pointValueType > getSubCellRefBasis (const ordinal_type subCellDim, const ordinal_type subCellOrd) const override
returns the basis associated to a subCell.
BasisPtr< typename Kokkos::HostSpace::device_type, outputValueType, pointValueType > getHostBasis () const override
Creates and returns a Basis object whose DeviceType template argument is Kokkos::HostSpace::device_type, but is otherwise identical to this.
Public Member Functions inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
OutputValueType getDummyOutputValue ()
Dummy array to receive input arguments.
PointValueType getDummyPointValue ()
Dummy array to receive input arguments.
Kokkos::DynRankView< OutputValueType, DeviceType > allocateOutputView (const int numPoints, const EOperator operatorType=OPERATOR_VALUE) const
Allocate a View container suitable for passing to the getValues() variant that accepts Kokkos DynRankViews as arguments (as opposed to the Intrepid2 BasisValues and PointValues containers).
virtual BasisValues< OutputValueType, DeviceType > allocateBasisValues (TensorPoints< PointValueType, DeviceType > points, const EOperator operatorType=OPERATOR_VALUE) const
Allocate BasisValues container suitable for passing to the getValues() variant that takes a TensorPoints container as argument.
virtual void getScratchSpaceSize (ordinal_type &perTeamSpaceSize, ordinal_type &perThreadSpaceSize, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
Return the size of the scratch space, in bytes, needed for using the team-level implementation of getValues.
virtual KOKKOS_INLINE_FUNCTION void getValues (OutputViewType, const PointViewType, const EOperator, const typename Kokkos::TeamPolicy< ExecutionSpace >::member_type &teamMember, const typename ExecutionSpace::scratch_memory_space &scratchStorage, const ordinal_type subcellDim=-1, const ordinal_type subcellOrdinal=-1) const
Team-level evaluation of basis functions on a reference cell.
virtual void getValues (const ExecutionSpace &, OutputViewType, const PointViewType, const EOperator=OPERATOR_VALUE) const
Evaluation of a FEM basis on a reference cell.
virtual void getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
virtual void getValues (BasisValues< OutputValueType, DeviceType > outputValues, const TensorPoints< PointValueType, DeviceType > inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
Evaluation of a FEM basis on a reference cell, using point and output value containers that allow preservation of tensor-product structure.
virtual void getValues (OutputViewType, const PointViewType, const PointViewType, const EOperator=OPERATOR_VALUE) const
Evaluation of an FVD basis evaluation on a physical cell.
OrdinalTypeArray1DHost getFieldOrdinalsForDegree (OrdinalTypeArray1DHost &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
OrdinalTypeArray1DHost getFieldOrdinalsForH1Degree (OrdinalTypeArray1DHost &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
std::vector< int > getFieldOrdinalsForDegree (std::vector< int > &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
std::vector< int > getFieldOrdinalsForH1Degree (std::vector< int > &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
OrdinalTypeArray1DHost getPolynomialDegreeOfField (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
OrdinalTypeArray1DHost getH1PolynomialDegreeOfField (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
std::vector< int > getPolynomialDegreeOfFieldAsVector (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
std::vector< int > getH1PolynomialDegreeOfFieldAsVector (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
int getPolynomialDegreeLength () const
For hierarchical bases, returns the number of entries required to specify the polynomial degree of a basis function.
ordinal_type getCardinality () const
Returns cardinality of the basis.
ordinal_type getDegree () const
Returns the degree of the basis.
EFunctionSpace getFunctionSpace () const
Returns the function space for the basis.
shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation https://trilinos.org/packages/shards for definition of base cell topology.
EBasis getBasisType () const
Returns the basis type.
ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
ordinal_type getDofCount (const ordinal_type subcDim, const ordinal_type subcOrd) const
DoF count for specified subcell.
ordinal_type getDofOrdinal (const ordinal_type subcDim, const ordinal_type subcOrd, const ordinal_type subcDofOrd) const
DoF tag to ordinal lookup.
virtual int getNumTensorialExtrusions () const
returns the number of tensorial extrusions relative to the cell topology returned by getBaseCellTopology(). Base class returns 0; overridden by TensorBasis.
const OrdinalTypeArray3DHost getAllDofOrdinal () const
DoF tag to ordinal data structure.
const OrdinalTypeArrayStride1DHost getDofTag (const ordinal_type dofOrd) const
DoF ordinal to DoF tag lookup.
const OrdinalTypeArray2DHost getAllDofTags () const
Retrieves all DoF tags.
ordinal_type getDomainDimension () const
Returns the spatial dimension of the domain of the basis; this is equal to getBaseCellTopology().getDimension() + getNumTensorialExtrusions().
Private Attributes
Kokkos::DynRankView< scalarType, DeviceType > coeffs_
expansion coefficients of the nodal basis in terms of the orthgonal one
EPointType pointType_
type of lattice used for creating the DoF coordinates
Additional Inherited Members
Protected Member Functions inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
template<typename OrdinalTypeView3D , typename OrdinalTypeView2D , typename OrdinalTypeView1D >
void setOrdinalTagData (OrdinalTypeView3D &tagToOrdinal, OrdinalTypeView2D &ordinalToTag, const OrdinalTypeView1D tags, const ordinal_type basisCard, const ordinal_type tagSize, const ordinal_type posScDim, const ordinal_type posScOrd, const ordinal_type posDfOrd)
Fills ordinalToTag_ and tagToOrdinal_ by basis-specific tag data.
Protected Attributes inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
ordinal_type basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
ordinal_type basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
unsigned basisCellTopologyKey_
Identifier of the base topology of the cells for which the basis is defined. See the Shards package for definition of base cell topology. For TensorBasis subclasses, by default this the cell topology that is extruded (i.e., it is a lower-dimensional CellTopology than the space on which the tensor basis is defined). This allows tensor bases to be defined in higher dimensions than shards::CellTopology supports. TensorBasis subclasses can opt to use an equivalent shards CellTopology for base topology, as well as using Intrepid2's tagging for tensor bases in dimensions up to 3, by calling TensorBasis::setShardsTopologyAndTags().
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
EFunctionSpace functionSpace_ = FUNCTION_SPACE_MAX
The function space in which the basis is defined.
OrdinalTypeArray2DHost ordinalToTag_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
OrdinalTypeArray3DHost tagToOrdinal_
DoF tag to ordinal lookup table.
Kokkos::DynRankView< scalarType, DeviceType > dofCoords_
Coordinates of degrees-of-freedom for basis functions defined in physical space.
Kokkos::DynRankView< scalarType, DeviceType > dofCoeffs_
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords_(i)) \cdot dofCoeffs_(i) are the nodal coefficients associated to basis functions i.
OrdinalTypeArray2DHost fieldOrdinalPolynomialDegree_
Polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
OrdinalTypeArray2DHost fieldOrdinalH1PolynomialDegree_
H^1 polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
Detailed Description
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double>
class Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >
Implementation of the default H(div)-compatible Raviart-Thomas basis of arbitrary degree on Tetrahedral cells.
Implements nodal basis of degree n (n>=1) on the reference Tetrahedron cell. The basis has cardinality n(n+1)(n+3)/2 and spans an INCOMPLETE polynomial space of degree n. Basis functions are dual to a unisolvent set of degrees-of-freedom (DoF) defined and enumerated as follows:
The normal component on a lattice of order n+1 and offset 1 on each edge (see PointTools). This gives one point per edge in the lowest-order case. These are the first 4 * (n*(n+1)/2) degrees of freedom
If n > 1, the x, y and z components at a lattice of order n+2 on the interior of the tetrahedron. These are the rest of the degrees of freedom.
If the pointType argument to the constructor specifies equispaced points, the the face and interior points will be equispaced. If the pointType argument specifies warp-blend points, the interior of a warp-blend lattice will be used on each face and also for the cell interior.
Definition at line 166 of file Intrepid2_HDIV_TET_In_FEM.hpp.
Member Typedef Documentation
BasisBase
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::BasisBase = Basis<DeviceType, outputValueType, pointValueType>
Definition at line 169 of file Intrepid2_HDIV_TET_In_FEM.hpp.
OrdinalTypeArray1DHost
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::OrdinalTypeArray1DHost = typename BasisBase::OrdinalTypeArray1DHost
Definition at line 170 of file Intrepid2_HDIV_TET_In_FEM.hpp.
OrdinalTypeArray2DHost
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::OrdinalTypeArray2DHost = typename BasisBase::OrdinalTypeArray2DHost
Definition at line 171 of file Intrepid2_HDIV_TET_In_FEM.hpp.
OrdinalTypeArray3DHost
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::OrdinalTypeArray3DHost = typename BasisBase::OrdinalTypeArray3DHost
Definition at line 172 of file Intrepid2_HDIV_TET_In_FEM.hpp.
OutputViewType
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::OutputViewType = typename BasisBase::OutputViewType
Definition at line 179 of file Intrepid2_HDIV_TET_In_FEM.hpp.
PointViewType
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::PointViewType = typename BasisBase::PointViewType
Definition at line 180 of file Intrepid2_HDIV_TET_In_FEM.hpp.
scalarType
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::scalarType = typename BasisBase::scalarType
Definition at line 182 of file Intrepid2_HDIV_TET_In_FEM.hpp.
ScalarViewType
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::ScalarViewType = typename BasisBase::ScalarViewType
Definition at line 181 of file Intrepid2_HDIV_TET_In_FEM.hpp.
Constructor & Destructor Documentation
Basis_HDIV_TET_In_FEM()
template<typename DT , typename OT , typename PT > Intrepid2::Basis_HDIV_TET_In_FEM< DT, OT, PT >::Basis_HDIV_TET_In_FEM (const ordinal_type order, const EPointType pointType = POINTTYPE_EQUISPACED)
Constructor.
Definition at line 155 of file Intrepid2_HDIV_TET_In_FEMDef.hpp.
References Intrepid2::CubatureDirect< DeviceType, pointValueType, weightValueType >::getCubature(), Intrepid2::PointTools::getLattice(), Intrepid2::PointTools::getLatticeSize(), Intrepid2::CubatureDirect< DeviceType, pointValueType, weightValueType >::getNumPoints(), Intrepid2::CellTools< DeviceType >::getReferenceSideNormal(), Intrepid2::CellTools< DeviceType >::mapToReferenceSubcell(), and Intrepid2::Parameters::MaxOrder.
Member Function Documentation
getDofCoeffs()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual void Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs (ScalarViewType) const inline override virtual
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords(i)) \cdot dofCoeffs(i) are the nodal coefficients associated to basis function i.
Rank-1 array for scalar basis with dimension (cardinality) Rank-2 array for vector basis with dimensions (cardinality, cell dimension)
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 241 of file Intrepid2_HDIV_TET_In_FEM.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::dofCoeffs_.
getDofCoords()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual void Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords (ScalarViewType) const inline override virtual
Returns spatial locations (coordinates) of degrees of freedom on the reference cell.
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 224 of file Intrepid2_HDIV_TET_In_FEM.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::dofCoords_.
getExpansionCoeffs()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> void Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getExpansionCoeffs (ScalarViewType coeffs) const inline
Definition at line 257 of file Intrepid2_HDIV_TET_In_FEM.hpp.
getHostBasis()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> BasisPtr< typename Kokkos::HostSpace::device_type, outputValueType, pointValueType > Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis () const inline override virtual
Creates and returns a Basis object whose DeviceType template argument is Kokkos::HostSpace::device_type, but is otherwise identical to this.
Returns
Pointer to the new Basis object.
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 295 of file Intrepid2_HDIV_TET_In_FEM.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisDegree_, and Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::pointType_.
getName()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual const char * Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getName () const inline override virtual
Returns basis name.
Returns
the name of the basis
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 264 of file Intrepid2_HDIV_TET_In_FEM.hpp.
getScratchSpaceSize()
template<typename DT , typename OT , typename PT > void Intrepid2::Basis_HDIV_TET_In_FEM< DT, OT, PT >::getScratchSpaceSize (ordinal_type & perTeamSpaceSize, ordinal_type & perThreadSpaceSize, const PointViewType inputPointsconst, const EOperator operatorType = OPERATOR_VALUE) const override virtual
Definition at line 456 of file Intrepid2_HDIV_TET_In_FEMDef.hpp.
getSubCellRefBasis()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> BasisPtr< DeviceType, outputValueType, pointValueType > Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis (const ordinal_type subCellDim, const ordinal_type subCellOrd) const inline override virtual
returns the basis associated to a subCell.
The bases of the subCell are the restriction to the subCell of the bases of the parent cell, projected along normal to the subCell.
Parameters
[in] subCellDim - dimension of subCell
[in] subCellOrd - position of the subCell among of the subCells having the same dimension
Returns
pointer to the subCell basis of dimension subCellDim and position subCellOrd
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 284 of file Intrepid2_HDIV_TET_In_FEM.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisDegree_, and Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::pointType_.
getValues()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual void Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType = OPERATOR_VALUE) const inline override virtual
Definition at line 187 of file Intrepid2_HDIV_TET_In_FEM.hpp.
requireOrientation()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual bool Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::requireOrientation () const inline override virtual
True if orientation is required.
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 270 of file Intrepid2_HDIV_TET_In_FEM.hpp.
Member Data Documentation
coeffs_
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> Kokkos::DynRankView<scalarType,DeviceType> Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::coeffs_ private
expansion coefficients of the nodal basis in terms of the orthgonal one
Definition at line 301 of file Intrepid2_HDIV_TET_In_FEM.hpp.
pointType_
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> EPointType Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::pointType_ private
type of lattice used for creating the DoF coordinates
Definition at line 304 of file Intrepid2_HDIV_TET_In_FEM.hpp.
Referenced by Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), and Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TET_In_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TET_In_FEMDef.hpp