Intrepid2: Intrepid2::Basis_DirectSumBasis< BasisBaseClass > Class Template Reference
Intrepid2::Basis_DirectSumBasis< BasisBaseClass > Class Template Reference
A basis that is the direct sum of two other bases.
#include <Intrepid2_DirectSumBasis.hpp>
Public Types
using BasisBase = BasisBaseClass
using BasisPtr = Teuchos::RCP< BasisBase >
using DeviceType = typename BasisBase::DeviceType
using ExecutionSpace = typename BasisBase::ExecutionSpace
using OutputValueType = typename BasisBase::OutputValueType
using PointValueType = typename BasisBase::PointValueType
using OrdinalTypeArray1DHost = typename BasisBase::OrdinalTypeArray1DHost
using OrdinalTypeArray2DHost = typename BasisBase::OrdinalTypeArray2DHost
using OutputViewType = typename BasisBase::OutputViewType
using PointViewType = typename BasisBase::PointViewType
using ScalarViewType = typename BasisBase::ScalarViewType
Public Member Functions
Basis_DirectSumBasis (BasisPtr basis1, BasisPtr basis2)
Constructor.
virtual BasisValues< OutputValueType, DeviceType > allocateBasisValues (TensorPoints< PointValueType, DeviceType > points, const EOperator operatorType=OPERATOR_VALUE) const override
Allocate BasisValues container suitable for passing to the getValues() variant that takes a TensorPoints container as argument.
virtual void getDofCoords (ScalarViewType dofCoords) const override
Fills in spatial locations (coordinates) of degrees of freedom (nodes) on the reference cell.
virtual void getDofCoeffs (ScalarViewType dofCoeffs) const override
Fills in coefficients of degrees of freedom for Lagrangian basis on the reference cell.
virtual const char * getName () const override
Returns basis name.
virtual void getValues (BasisValues< OutputValueType, DeviceType > outputValues, const TensorPoints< PointValueType, DeviceType > inputPoints, const EOperator operatorType=OPERATOR_VALUE) const override
Evaluation of a FEM basis on a reference cell, using point and output value containers that allow preservation of tensor-product structure.
virtual void getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const override
Evaluation of a FEM basis on a reference cell.
virtual int getNumTensorialExtrusions () const override
Protected Attributes
BasisPtr basis1_
BasisPtr basis2_
std::string name_
Detailed Description
template<typename BasisBaseClass>
class Intrepid2::Basis_DirectSumBasis< BasisBaseClass >
A basis that is the direct sum of two other bases.
The direct-sum basis is ordered such that the Basis1 members come first (and in the same order as they exist in Basis1), followed by the members of Basis2, in the same order as they exist in Basis2.
The two bases must agree in their BasisType (the return value of getBasisType()).
Definition at line 33 of file Intrepid2_DirectSumBasis.hpp.
Member Typedef Documentation
BasisBase
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::BasisBase = BasisBaseClass
Definition at line 36 of file Intrepid2_DirectSumBasis.hpp.
BasisPtr
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::BasisPtr = Teuchos::RCP<BasisBase>
Definition at line 37 of file Intrepid2_DirectSumBasis.hpp.
DeviceType
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::DeviceType = typename BasisBase::DeviceType
Definition at line 39 of file Intrepid2_DirectSumBasis.hpp.
ExecutionSpace
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::ExecutionSpace = typename BasisBase::ExecutionSpace
Definition at line 40 of file Intrepid2_DirectSumBasis.hpp.
OrdinalTypeArray1DHost
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::OrdinalTypeArray1DHost = typename BasisBase::OrdinalTypeArray1DHost
Definition at line 44 of file Intrepid2_DirectSumBasis.hpp.
OrdinalTypeArray2DHost
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::OrdinalTypeArray2DHost = typename BasisBase::OrdinalTypeArray2DHost
Definition at line 45 of file Intrepid2_DirectSumBasis.hpp.
OutputValueType
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::OutputValueType = typename BasisBase::OutputValueType
Definition at line 41 of file Intrepid2_DirectSumBasis.hpp.
OutputViewType
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::OutputViewType = typename BasisBase::OutputViewType
Definition at line 46 of file Intrepid2_DirectSumBasis.hpp.
PointValueType
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::PointValueType = typename BasisBase::PointValueType
Definition at line 42 of file Intrepid2_DirectSumBasis.hpp.
PointViewType
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::PointViewType = typename BasisBase::PointViewType
Definition at line 47 of file Intrepid2_DirectSumBasis.hpp.
ScalarViewType
template<typename BasisBaseClass > using Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::ScalarViewType = typename BasisBase::ScalarViewType
Definition at line 48 of file Intrepid2_DirectSumBasis.hpp.
Constructor & Destructor Documentation
Basis_DirectSumBasis()
template<typename BasisBaseClass > Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::Basis_DirectSumBasis (BasisPtr basis1, BasisPtr basis2) inline
Constructor.
Parameters
[in] basis1 - the instance of Basis1
[in] basis2 - the instance of Basis2
Definition at line 59 of file Intrepid2_DirectSumBasis.hpp.
Member Function Documentation
allocateBasisValues()
template<typename BasisBaseClass > virtual BasisValues< OutputValueType, DeviceType > Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::allocateBasisValues (TensorPoints< PointValueType, DeviceType > points, const EOperator operatorType = OPERATOR_VALUE) const inline override virtual
Allocate BasisValues container suitable for passing to the getValues() variant that takes a TensorPoints container as argument.
The default implementation employs a trivial tensor-product structure, for compatibility across all bases. Subclasses that have tensor-product structure should override. Note that only the basic exact-sequence operators are supported at the moment: VALUE, GRAD, DIV, CURL.
Definition at line 182 of file Intrepid2_DirectSumBasis.hpp.
References Intrepid2::VectorData< Scalar, DeviceType >::isValid(), Intrepid2::VectorData< Scalar, DeviceType >::numFamilies(), Intrepid2::BasisValues< Scalar, DeviceType >::tensorData(), and Intrepid2::BasisValues< Scalar, DeviceType >::vectorData().
getDofCoeffs()
template<typename BasisBaseClass > virtual void Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::getDofCoeffs (ScalarViewType dofCoeffs) const inline override virtual
Fills in coefficients of degrees of freedom for Lagrangian basis on the reference cell.
Parameters
[out] dofCoeffs - the container into which to place the degrees of freedom.
dofCoeffs have shape (F,D) or (F) if D=1, field dimension matches the cardinality of the basis, and D is the basis dimension.
Degrees of freedom coefficients are such that \phi_i(dofCoords_(j)) \cdot dofCoeffs_(j) = \delta_ij, where \phi_i are the basis and \delta_ij the Kronecker delta. Note that getDofCoeffs() is supported only for Lagrangian bases.
Definition at line 271 of file Intrepid2_DirectSumBasis.hpp.
getDofCoords()
template<typename BasisBaseClass > virtual void Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::getDofCoords (ScalarViewType dofCoords) const inline override virtual
Fills in spatial locations (coordinates) of degrees of freedom (nodes) on the reference cell.
Parameters
[out] dofCoords - the container into which to place the degrees of freedom.
dofCoords should have shape (F,D), where the field dimension matches the cardinality of the basis, and D is the spatial dimension of the topology on which the basis is defined.
Note that getDofCoords() is not supported by all bases; in particular, hierarchical bases do not generally support this.
Definition at line 248 of file Intrepid2_DirectSumBasis.hpp.
getName()
template<typename BasisBaseClass > virtual const char * Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::getName () const inline override virtual
Returns basis name.
Returns
the name of the basis
Reimplemented in Intrepid2::Basis_Derived_HCURL_HEX< HGRAD_LINE, HVOL_LINE >, Intrepid2::Basis_Derived_HCURL_QUAD< HGRAD_LINE, HVOL_LINE >, Intrepid2::Basis_Derived_HCURL_WEDGE< HGRAD_TRI, HCURL_TRI, HGRAD_LINE, HVOL_LINE >, Intrepid2::Basis_Derived_HDIV_HEX< HGRAD_LINE, HVOL_LINE >, Intrepid2::Basis_Derived_HDIV_QUAD< HGRAD_LINE, HVOL_LINE >, and Intrepid2::Basis_Derived_HDIV_WEDGE< HDIV_TRI, HVOL_TRI, HGRAD_LINE, HVOL_LINE >.
Definition at line 290 of file Intrepid2_DirectSumBasis.hpp.
Referenced by Intrepid2::Basis_Derived_HCURL_HEX< HGRAD_LINE, HVOL_LINE >::Basis_Derived_HCURL_HEX(), Intrepid2::Basis_Derived_HCURL_QUAD< HGRAD_LINE, HVOL_LINE >::Basis_Derived_HCURL_QUAD(), Intrepid2::Basis_Derived_HCURL_WEDGE< HGRAD_TRI, HCURL_TRI, HGRAD_LINE, HVOL_LINE >::Basis_Derived_HCURL_WEDGE(), Intrepid2::Basis_Derived_HDIV_HEX< HGRAD_LINE, HVOL_LINE >::Basis_Derived_HDIV_HEX(), Intrepid2::Basis_Derived_HDIV_QUAD< HGRAD_LINE, HVOL_LINE >::Basis_Derived_HDIV_QUAD(), and Intrepid2::Basis_Derived_HDIV_WEDGE< HDIV_TRI, HVOL_TRI, HGRAD_LINE, HVOL_LINE >::Basis_Derived_HDIV_WEDGE().
getNumTensorialExtrusions()
template<typename BasisBaseClass > virtual int Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::getNumTensorialExtrusions () const inline override virtual
Definition at line 408 of file Intrepid2_DirectSumBasis.hpp.
getValues() [1/2]
template<typename BasisBaseClass > virtual void Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::getValues (BasisValues< OutputValueType, DeviceType > outputValues, const TensorPoints< PointValueType, DeviceType > inputPoints, const EOperator operatorType = OPERATOR_VALUE) const inline override virtual
Evaluation of a FEM basis on a reference cell, using point and output value containers that allow preservation of tensor-product structure.
Returns values of operatorType acting on FEM basis functions for a set of points in the reference cell for which the basis is defined.
Parameters
outputValues [out] - variable rank array with the basis values. Should be allocated using Basis::allocateBasisValues().
inputPoints [in] - rank-2 array (P,D) with the evaluation points. This should be allocated using Cubature::allocateCubaturePoints() and filled using Cubature::getCubature().
operatorType [in] - the operator acting on the basis function
This is the preferred getValues() method for TensorBasis and DirectSumBasis and their subclasses. It allows a reduced memory footprint and optimized integration, etc.
Definition at line 312 of file Intrepid2_DirectSumBasis.hpp.
References Intrepid2::BasisValues< Scalar, DeviceType >::basisValuesForFields().
getValues() [2/2]
template<typename BasisBaseClass > virtual void Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType = OPERATOR_VALUE) const inline override virtual
Evaluation of a FEM basis on a reference cell.
Returns values of operatorType acting on FEM basis functions for a set of points in the reference cell for which the basis is defined.
Parameters
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-2 array (P,D) with the evaluation points
operatorType [in] - the operator acting on the basis functions
Remarks
For rank and dimension specifications of the output array see Section MD array template arguments for basis methods. Dimensions of ArrayScalar arguments are checked at runtime if HAVE_INTREPID2_DEBUG is defined.
A FEM basis spans a COMPLETE or INCOMPLETE polynomial space on the reference cell which is a smooth function space. Thus, all operator types that are meaningful for the approximated function space are admissible. When the order of the operator exceeds the degree of the basis, the output array is filled with the appropriate number of zeros.
Definition at line 346 of file Intrepid2_DirectSumBasis.hpp.
Member Data Documentation
basis1_
template<typename BasisBaseClass > BasisPtr Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::basis1_ protected
Definition at line 50 of file Intrepid2_DirectSumBasis.hpp.
basis2_
template<typename BasisBaseClass > BasisPtr Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::basis2_ protected
Definition at line 51 of file Intrepid2_DirectSumBasis.hpp.
name_
template<typename BasisBaseClass > std::string Intrepid2::Basis_DirectSumBasis< BasisBaseClass >::name_ protected
Definition at line 53 of file Intrepid2_DirectSumBasis.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_DirectSumBasis.hpp