Intrepid2: Intrepid2::Basis< Device, outputValueType, pointValueType > Class Template Reference
Intrepid2::Basis< Device, outputValueType, pointValueType > Class Template Reference
An abstract base class that defines interface for concrete basis implementations for Finite Element (FEM) and Finite Volume/Finite Difference (FVD) discrete spaces.
#include <Intrepid2_Basis.hpp>
Public Types
using DeviceType = Device
(Kokkos) Device type on which Basis is templated. Does not necessarily return true for Kokkos::is_device (may be Kokkos::Serial, for example).
using ExecutionSpace = typename DeviceType::execution_space
(Kokkos) Execution space for basis.
using OutputValueType = outputValueType
Output value type for basis; default is double.
using PointValueType = pointValueType
Point value type for basis; default is double.
using OrdinalViewType = Kokkos::View< ordinal_type, DeviceType >
View type for ordinal.
using EBasisViewType = Kokkos::View< EBasis, DeviceType >
View for basis type.
using ECoordinatesViewType = Kokkos::View< ECoordinates, DeviceType >
View for coordinate system type.
using OrdinalTypeArray1DHost = Kokkos::View< ordinal_type *, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 1d host array.
using OrdinalTypeArray2DHost = Kokkos::View< ordinal_type **, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 2d host array.
using OrdinalTypeArray3DHost = Kokkos::View< ordinal_type ***, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 3d host array.
using OrdinalTypeArrayStride1DHost = Kokkos::View< ordinal_type *, Kokkos::LayoutStride, Kokkos::HostSpace >
View type for 1d host array.
using OrdinalTypeArray1D = Kokkos::View< ordinal_type *, DeviceType >
View type for 1d device array.
using OrdinalTypeArray2D = Kokkos::View< ordinal_type **, DeviceType >
View type for 2d device array.
using OrdinalTypeArray3D = Kokkos::View< ordinal_type ***, DeviceType >
View type for 3d device array.
using OrdinalTypeArrayStride1D = Kokkos::View< ordinal_type *, Kokkos::LayoutStride, DeviceType >
View type for 1d device array.
typedef ScalarTraits< pointValueType >::scalar_type scalarType
Scalar type for point values.
using OutputViewType = Kokkos::DynRankView< OutputValueType, Kokkos::LayoutStride, DeviceType >
View type for basis value output.
using PointViewType = Kokkos::DynRankView< PointValueType, Kokkos::LayoutStride, DeviceType >
View type for input points.
using ScalarViewType = Kokkos::DynRankView< scalarType, Kokkos::LayoutStride, DeviceType >
View type for scalars.
Public Member Functions
OutputValueType getDummyOutputValue ()
Dummy array to receive input arguments.
PointValueType getDummyPointValue ()
Dummy array to receive input arguments.
Kokkos::DynRankView< OutputValueType, DeviceType > allocateOutputView (const int numPoints, const EOperator operatorType=OPERATOR_VALUE) const
Allocate a View container suitable for passing to the getValues() variant that accepts Kokkos DynRankViews as arguments (as opposed to the Intrepid2 BasisValues and PointValues containers).
virtual BasisValues< OutputValueType, DeviceType > allocateBasisValues (TensorPoints< PointValueType, DeviceType > points, const EOperator operatorType=OPERATOR_VALUE) const
Allocate BasisValues container suitable for passing to the getValues() variant that takes a TensorPoints container as argument.
virtual void getScratchSpaceSize (ordinal_type &perTeamSpaceSize, ordinal_type &perThreadSpaceSize, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
Return the size of the scratch space, in bytes, needed for using the team-level implementation of getValues.
virtual KOKKOS_INLINE_FUNCTION void getValues (OutputViewType, const PointViewType, const EOperator, const typename Kokkos::TeamPolicy< ExecutionSpace >::member_type &teamMember, const typename ExecutionSpace::scratch_memory_space &scratchStorage, const ordinal_type subcellDim=-1, const ordinal_type subcellOrdinal=-1) const
Team-level evaluation of basis functions on a reference cell.
virtual void getValues (const ExecutionSpace &, OutputViewType, const PointViewType, const EOperator=OPERATOR_VALUE) const
Evaluation of a FEM basis on a reference cell.
virtual void getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
virtual void getValues (BasisValues< OutputValueType, DeviceType > outputValues, const TensorPoints< PointValueType, DeviceType > inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
Evaluation of a FEM basis on a reference cell, using point and output value containers that allow preservation of tensor-product structure.
virtual void getValues (OutputViewType, const PointViewType, const PointViewType, const EOperator=OPERATOR_VALUE) const
Evaluation of an FVD basis evaluation on a physical cell.
virtual void getDofCoords (ScalarViewType) const
Returns spatial locations (coordinates) of degrees of freedom on the reference cell.
virtual void getDofCoeffs (ScalarViewType) const
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords(i)) \cdot dofCoeffs(i) are the nodal coefficients associated to basis function i.
OrdinalTypeArray1DHost getFieldOrdinalsForDegree (OrdinalTypeArray1DHost &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
OrdinalTypeArray1DHost getFieldOrdinalsForH1Degree (OrdinalTypeArray1DHost &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
std::vector< int > getFieldOrdinalsForDegree (std::vector< int > &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
std::vector< int > getFieldOrdinalsForH1Degree (std::vector< int > &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
OrdinalTypeArray1DHost getPolynomialDegreeOfField (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
OrdinalTypeArray1DHost getH1PolynomialDegreeOfField (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
std::vector< int > getPolynomialDegreeOfFieldAsVector (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
std::vector< int > getH1PolynomialDegreeOfFieldAsVector (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
int getPolynomialDegreeLength () const
For hierarchical bases, returns the number of entries required to specify the polynomial degree of a basis function.
virtual const char * getName () const
Returns basis name.
virtual bool requireOrientation () const
True if orientation is required.
ordinal_type getCardinality () const
Returns cardinality of the basis.
ordinal_type getDegree () const
Returns the degree of the basis.
EFunctionSpace getFunctionSpace () const
Returns the function space for the basis.
shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation https://trilinos.org/packages/shards for definition of base cell topology.
EBasis getBasisType () const
Returns the basis type.
ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
ordinal_type getDofCount (const ordinal_type subcDim, const ordinal_type subcOrd) const
DoF count for specified subcell.
ordinal_type getDofOrdinal (const ordinal_type subcDim, const ordinal_type subcOrd, const ordinal_type subcDofOrd) const
DoF tag to ordinal lookup.
virtual int getNumTensorialExtrusions () const
returns the number of tensorial extrusions relative to the cell topology returned by getBaseCellTopology(). Base class returns 0; overridden by TensorBasis.
const OrdinalTypeArray3DHost getAllDofOrdinal () const
DoF tag to ordinal data structure.
const OrdinalTypeArrayStride1DHost getDofTag (const ordinal_type dofOrd) const
DoF ordinal to DoF tag lookup.
const OrdinalTypeArray2DHost getAllDofTags () const
Retrieves all DoF tags.
virtual BasisPtr< DeviceType, OutputValueType, PointValueType > getSubCellRefBasis (const ordinal_type subCellDim, const ordinal_type subCellOrd) const
returns the basis associated to a subCell.
ordinal_type getDomainDimension () const
Returns the spatial dimension of the domain of the basis; this is equal to getBaseCellTopology().getDimension() + getNumTensorialExtrusions().
virtual HostBasisPtr< OutputValueType, PointValueType > getHostBasis () const
Creates and returns a Basis object whose DeviceType template argument is Kokkos::HostSpace::device_type, but is otherwise identical to this.
Protected Member Functions
template<typename OrdinalTypeView3D , typename OrdinalTypeView2D , typename OrdinalTypeView1D >
void setOrdinalTagData (OrdinalTypeView3D &tagToOrdinal, OrdinalTypeView2D &ordinalToTag, const OrdinalTypeView1D tags, const ordinal_type basisCard, const ordinal_type tagSize, const ordinal_type posScDim, const ordinal_type posScOrd, const ordinal_type posDfOrd)
Fills ordinalToTag_ and tagToOrdinal_ by basis-specific tag data.
Protected Attributes
ordinal_type basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
ordinal_type basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
unsigned basisCellTopologyKey_
Identifier of the base topology of the cells for which the basis is defined. See the Shards package for definition of base cell topology. For TensorBasis subclasses, by default this the cell topology that is extruded (i.e., it is a lower-dimensional CellTopology than the space on which the tensor basis is defined). This allows tensor bases to be defined in higher dimensions than shards::CellTopology supports. TensorBasis subclasses can opt to use an equivalent shards CellTopology for base topology, as well as using Intrepid2's tagging for tensor bases in dimensions up to 3, by calling TensorBasis::setShardsTopologyAndTags().
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
EFunctionSpace functionSpace_ = FUNCTION_SPACE_MAX
The function space in which the basis is defined.
OrdinalTypeArray2DHost ordinalToTag_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
OrdinalTypeArray3DHost tagToOrdinal_
DoF tag to ordinal lookup table.
Kokkos::DynRankView< scalarType, DeviceType > dofCoords_
Coordinates of degrees-of-freedom for basis functions defined in physical space.
Kokkos::DynRankView< scalarType, DeviceType > dofCoeffs_
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords_(i)) \cdot dofCoeffs_(i) are the nodal coefficients associated to basis functions i.
OrdinalTypeArray2DHost fieldOrdinalPolynomialDegree_
Polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
OrdinalTypeArray2DHost fieldOrdinalH1PolynomialDegree_
H^1 polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
Detailed Description
template<typename Device, typename outputValueType, typename pointValueType>
class Intrepid2::Basis< Device, outputValueType, pointValueType >
An abstract base class that defines interface for concrete basis implementations for Finite Element (FEM) and Finite Volume/Finite Difference (FVD) discrete spaces.
A FEM basis spans a discrete space whose type can be either COMPLETE or INCOMPLETE. FEM basis functions are always defined on a reference cell and are dual to a unisolvent set of degrees-of-freedom (DoF). FEM basis requires cell topology with a reference cell.
An FVD basis spans a discrete space whose type is typically BROKEN. The basis functions are defined directly on the physical cell and are dual to a set of DoFs on that cell. As a result, FVD bases require the vertex coordinates of the physical cell but the cell itself is not required to have a reference cell.
Every DoF and its corresponding basis function from a given FEM or FVD basis set is assigned an ordinal number which which specifies its numerical position in the DoF set, and a 4-field DoF tag whose first 3 fields establish association between the DoF and a subcell of particular dimension, and the last field gives the total number of basis functions associated with that subcell; see Section Degree of freedom ordinals and tags for details.
Note the use of Kokkos::LayoutStride as the layout for various View definitions (including the argument for getValues()). A method expecting a LayoutStride view can accept, thanks to some conversion mechanisms defined elsewhere, a LayoutLeft view (the default for Cuda views in Kokkos) or a LayoutRight view (the default on most other platforms). This does introduce some additional complexity when Views need to be allocated for temporary storage; see the method getMatchingViewWithLabel() provided in Intrepid_Utils.hpp.
Remarks
To limit memory use by factory-type objects (basis factories will be included in future releases of Intrepid2), tag data is not initialized by basis ctors, instead, whenever a function that requires tag data is invoked for a first time, it calls initializeTags() to fill ordinalToTag_ and tagToOrdinal_. Because tag data is basis-specific, every concrete basis class requires its own implementation of initializeTags().
Todo:
restore test for inclusion of reference points in their resective reference cells in getValues_HGRAD_Args, getValues_CURL_Args, getValues_DIV_Args
Definition at line 89 of file Intrepid2_Basis.hpp.
Member Typedef Documentation
DeviceType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::DeviceType = Device
(Kokkos) Device type on which Basis is templated. Does not necessarily return true for Kokkos::is_device (may be Kokkos::Serial, for example).
Definition at line 93 of file Intrepid2_Basis.hpp.
EBasisViewType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::EBasisViewType = Kokkos::View<EBasis,DeviceType>
View for basis type.
Definition at line 114 of file Intrepid2_Basis.hpp.
ECoordinatesViewType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::ECoordinatesViewType = Kokkos::View<ECoordinates,DeviceType>
View for coordinate system type.
Definition at line 118 of file Intrepid2_Basis.hpp.
ExecutionSpace
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::ExecutionSpace = typename DeviceType::execution_space
(Kokkos) Execution space for basis.
Definition at line 97 of file Intrepid2_Basis.hpp.
OrdinalTypeArray1D
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArray1D = Kokkos::View<ordinal_type*,DeviceType>
View type for 1d device array.
Definition at line 141 of file Intrepid2_Basis.hpp.
OrdinalTypeArray1DHost
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArray1DHost = Kokkos::View<ordinal_type*,typename ExecutionSpace::array_layout,Kokkos::HostSpace>
View type for 1d host array.
Definition at line 125 of file Intrepid2_Basis.hpp.
OrdinalTypeArray2D
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArray2D = Kokkos::View<ordinal_type**,DeviceType>
View type for 2d device array.
Definition at line 145 of file Intrepid2_Basis.hpp.
OrdinalTypeArray2DHost
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArray2DHost = Kokkos::View<ordinal_type**,typename ExecutionSpace::array_layout,Kokkos::HostSpace>
View type for 2d host array.
Definition at line 129 of file Intrepid2_Basis.hpp.
OrdinalTypeArray3D
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArray3D = Kokkos::View<ordinal_type***,DeviceType>
View type for 3d device array.
Definition at line 149 of file Intrepid2_Basis.hpp.
OrdinalTypeArray3DHost
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArray3DHost = Kokkos::View<ordinal_type***,typename ExecutionSpace::array_layout,Kokkos::HostSpace>
View type for 3d host array.
Definition at line 133 of file Intrepid2_Basis.hpp.
OrdinalTypeArrayStride1D
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArrayStride1D = Kokkos::View<ordinal_type*, Kokkos::LayoutStride, DeviceType>
View type for 1d device array.
Definition at line 153 of file Intrepid2_Basis.hpp.
OrdinalTypeArrayStride1DHost
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalTypeArrayStride1DHost = Kokkos::View<ordinal_type*, Kokkos::LayoutStride, Kokkos::HostSpace>
View type for 1d host array.
Definition at line 137 of file Intrepid2_Basis.hpp.
OrdinalViewType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OrdinalViewType = Kokkos::View<ordinal_type,DeviceType>
View type for ordinal.
Definition at line 110 of file Intrepid2_Basis.hpp.
OutputValueType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OutputValueType = outputValueType
Output value type for basis; default is double.
Definition at line 102 of file Intrepid2_Basis.hpp.
OutputViewType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::OutputViewType = Kokkos::DynRankView<OutputValueType,Kokkos::LayoutStride,DeviceType>
View type for basis value output.
Definition at line 334 of file Intrepid2_Basis.hpp.
PointValueType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::PointValueType = pointValueType
Point value type for basis; default is double.
Definition at line 106 of file Intrepid2_Basis.hpp.
PointViewType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::PointViewType = Kokkos::DynRankView<PointValueType,Kokkos::LayoutStride,DeviceType>
View type for input points.
Definition at line 338 of file Intrepid2_Basis.hpp.
scalarType
template<typename Device , typename outputValueType , typename pointValueType > typedef ScalarTraits<pointValueType>::scalar_type Intrepid2::Basis< Device, outputValueType, pointValueType >::scalarType
Scalar type for point values.
Definition at line 157 of file Intrepid2_Basis.hpp.
ScalarViewType
template<typename Device , typename outputValueType , typename pointValueType > using Intrepid2::Basis< Device, outputValueType, pointValueType >::ScalarViewType = Kokkos::DynRankView<scalarType,Kokkos::LayoutStride,DeviceType>
View type for scalars.
Definition at line 342 of file Intrepid2_Basis.hpp.
Member Function Documentation
allocateBasisValues()
template<typename Device , typename outputValueType , typename pointValueType > virtual BasisValues< OutputValueType, DeviceType > Intrepid2::Basis< Device, outputValueType, pointValueType >::allocateBasisValues (TensorPoints< PointValueType, DeviceType > points, const EOperator operatorType = OPERATOR_VALUE) const inline virtual
Allocate BasisValues container suitable for passing to the getValues() variant that takes a TensorPoints container as argument.
The default implementation employs a trivial tensor-product structure, for compatibility across all bases. Subclasses that have non-trivial tensor-product structure should override. The basic exact-sequence operators are supported (VALUE, GRAD, DIV, CURL), as are the Dn operators (OPERATOR_D1 through OPERATOR_D10).
Definition at line 355 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::allocateOutputView(), and Intrepid2::TensorPoints< PointScalar, DeviceType >::extent_int().
allocateOutputView()
template<typename Device , typename outputValueType , typename pointValueType > Kokkos::DynRankView< outputValueType, Device > Intrepid2::Basis< Device, outputValueType, pointValueType >::allocateOutputView (const int numPoints, const EOperator operatorType = OPERATOR_VALUE) const
Allocate a View container suitable for passing to the getValues() variant that accepts Kokkos DynRankViews as arguments (as opposed to the Intrepid2 BasisValues and PointValues containers).
Note that only the basic exact-sequence operators are supported at the moment: VALUE, GRAD, DIV, CURL.
Definition at line 827 of file Intrepid2_BasisDef.hpp.
References Intrepid2::getDkCardinality().
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::allocateBasisValues().
getAllDofOrdinal()
template<typename Device , typename outputValueType , typename pointValueType > const OrdinalTypeArray3DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::getAllDofOrdinal () const inline
DoF tag to ordinal data structure.
Definition at line 925 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::tagToOrdinal_.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs().
getAllDofTags()
template<typename Device , typename outputValueType , typename pointValueType > const OrdinalTypeArray2DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::getAllDofTags () const inline
Retrieves all DoF tags.
Returns
reference to a vector of vectors with dimensions (basisCardinality_, 4) such that
element [DofOrd][0] = tag field 0 for the DoF with the specified ordinal
element [DofOrd][1] = tag field 1 for the DoF with the specified ordinal
element [DofOrd][2] = tag field 2 for the DoF with the specified ordinal
element [DofOrd][3] = tag field 3 for the DoF with the specified ordinal
Definition at line 959 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::ordinalToTag_.
getBaseCellTopology()
template<typename Device , typename outputValueType , typename pointValueType > shards::CellTopology Intrepid2::Basis< Device, outputValueType, pointValueType >::getBaseCellTopology () const inline
Returns the base cell topology for which the basis is defined. See Shards documentation https://trilinos.org/packages/shards for definition of base cell topology.
Returns
Base cell topology
Definition at line 834 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisCellTopologyKey_.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getDomainDimension(), Intrepid2::Basis_HVOL_C0_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_Cn_FEM_JACOBI< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_COMP12_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), and Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI().
getBasisType()
template<typename Device , typename outputValueType , typename pointValueType > EBasis Intrepid2::Basis< Device, outputValueType, pointValueType >::getBasisType () const inline
Returns the basis type.
Returns
Basis type
Definition at line 844 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_.
getCardinality()
template<typename Device , typename outputValueType , typename pointValueType > ordinal_type Intrepid2::Basis< Device, outputValueType, pointValueType >::getCardinality () const inline
Returns cardinality of the basis.
Returns
the number of basis functions in the basis
Definition at line 805 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisCardinality_.
Referenced by Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HCURL_HEX_In_FEM(), Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HCURL_QUAD_In_FEM(), Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HDIV_HEX_In_FEM(), Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HDIV_QUAD_In_FEM(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HGRAD_HEX_Cn_FEM(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HGRAD_QUAD_Cn_FEM(), Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HVOL_HEX_Cn_FEM(), Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HVOL_QUAD_Cn_FEM(), Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_LINE_Cn_FEM_JACOBI< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_COMP12_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), and Intrepid2::Basis_HGRAD_TRI_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >::getValues().
getCoordinateSystem()
template<typename Device , typename outputValueType , typename pointValueType > ECoordinates Intrepid2::Basis< Device, outputValueType, pointValueType >::getCoordinateSystem () const inline
Returns the type of coordinate system for which the basis is defined.
Returns
Type of the coordinate system (Cartesian, polar, R-Z, etc.).
Definition at line 854 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisCoordinates_.
getDegree()
template<typename Device , typename outputValueType , typename pointValueType > ordinal_type Intrepid2::Basis< Device, outputValueType, pointValueType >::getDegree () const inline
Returns the degree of the basis.
Returns
max. degree of the complete polynomials that can be represented by the basis.
Definition at line 815 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisDegree_.
Referenced by Intrepid2::Basis_HGRAD_LINE_Cn_FEM_JACOBI< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TET_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::requireOrientation(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::requireOrientation(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::requireOrientation(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::requireOrientation(), Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::requireOrientation(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::requireOrientation(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::requireOrientation(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::requireOrientation(), and Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::requireOrientation().
getDofCoeffs()
template<typename Device , typename outputValueType , typename pointValueType > virtual void Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCoeffs (ScalarViewType) const inline virtual
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords(i)) \cdot dofCoeffs(i) are the nodal coefficients associated to basis function i.
Rank-1 array for scalar basis with dimension (cardinality) Rank-2 array for vector basis with dimensions (cardinality, cell dimension)
Reimplemented in Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, and Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >.
Definition at line 561 of file Intrepid2_Basis.hpp.
getDofCoords()
template<typename Device , typename outputValueType , typename pointValueType > virtual void Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCoords (ScalarViewType) const inline virtual
Returns spatial locations (coordinates) of degrees of freedom on the reference cell.
Reimplemented in Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_COMP12_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, and Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >.
Definition at line 546 of file Intrepid2_Basis.hpp.
getDofCount()
template<typename Device , typename outputValueType , typename pointValueType > ordinal_type Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCount (const ordinal_type subcDim, const ordinal_type subcOrd) const inline
DoF count for specified subcell.
Parameters
subcDim [in] - tag field 0: dimension of the subcell associated with the DoFs
subcOrd [in] - tag field 1: ordinal of the subcell defined by cell topology
Returns
the number of DoFs associated with the specified subcell.
Definition at line 866 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofTag(), and Intrepid2::Basis< Device, outputValueType, pointValueType >::tagToOrdinal_.
Referenced by Intrepid2::ProjectionStruct< DeviceType, ValueType >::createHDivProjectionStruct(), Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), and Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs().
getDofOrdinal()
template<typename Device , typename outputValueType , typename pointValueType > ordinal_type Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofOrdinal (const ordinal_type subcDim, const ordinal_type subcOrd, const ordinal_type subcDofOrd) const inline
DoF tag to ordinal lookup.
Parameters
subcDim [in] - tag field 0: dimension of the subcell associated with the DoF
subcOrd [in] - tag field 1: ordinal of the subcell defined by cell topology
subcDofOrd [in] - tag field 2: ordinal of the DoF relative to the subcell.
Returns
the DoF ordinal corresponding to the specified DoF tag data.
Definition at line 892 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::tagToOrdinal_.
getDofTag()
template<typename Device , typename outputValueType , typename pointValueType > const OrdinalTypeArrayStride1DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofTag (const ordinal_type dofOrd) const inline
DoF ordinal to DoF tag lookup.
Parameters
dofOrd [in] - ordinal of the DoF whose tag is being retrieved
Returns
reference to a vector with dimension (4) such that
element [0] = tag field 0 -> dim. of the subcell associated with the specified DoF
element [1] = tag field 1 -> ordinal of the subcell defined by cell topology
element [2] = tag field 2 -> ordinal of the specified DoF relative to the subcell
element [3] = tag field 3 -> total number of DoFs associated with the subcell
Definition at line 941 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::ordinalToTag_.
Referenced by Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HCURL_HEX_In_FEM(), Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HCURL_QUAD_In_FEM(), Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HDIV_HEX_In_FEM(), Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HDIV_QUAD_In_FEM(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HGRAD_HEX_Cn_FEM(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HGRAD_QUAD_Cn_FEM(), Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HVOL_HEX_Cn_FEM(), Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HVOL_QUAD_Cn_FEM(), and Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCount().
getDomainDimension()
template<typename Device , typename outputValueType , typename pointValueType > ordinal_type Intrepid2::Basis< Device, outputValueType, pointValueType >::getDomainDimension () const inline
Returns the spatial dimension of the domain of the basis; this is equal to getBaseCellTopology().getDimension() + getNumTensorialExtrusions().
Returns
The spatial dimension of the domain.
Definition at line 987 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::getBaseCellTopology(), and Intrepid2::Basis< Device, outputValueType, pointValueType >::getNumTensorialExtrusions().
getDummyOutputValue()
template<typename Device , typename outputValueType , typename pointValueType > OutputValueType Intrepid2::Basis< Device, outputValueType, pointValueType >::getDummyOutputValue () inline
Dummy array to receive input arguments.
Definition at line 326 of file Intrepid2_Basis.hpp.
getDummyPointValue()
template<typename Device , typename outputValueType , typename pointValueType > PointValueType Intrepid2::Basis< Device, outputValueType, pointValueType >::getDummyPointValue () inline
Dummy array to receive input arguments.
Definition at line 330 of file Intrepid2_Basis.hpp.
getFieldOrdinalsForDegree() [1/2]
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray1DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForDegree (OrdinalTypeArray1DHost & degrees) const inline
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
Parameters
degrees [in] - 1D host ordinal array of length specified by getPolynomialDegreeLength(), indicating what the maximum degree in each dimension should be
Returns
a 1D host ordinal array containing the ordinals of matching basis functions
Definition at line 573 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::fieldOrdinalPolynomialDegree_.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForDegree().
getFieldOrdinalsForDegree() [2/2]
template<typename Device , typename outputValueType , typename pointValueType > std::vector< int > Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForDegree (std::vector< int > & degrees) const inline
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
This variant takes a std::vector of polynomial degrees and returns a std::vector of field ordinals. It calls the other variant, which uses Kokkos Views on the host.
Parameters
degrees [in] - std::vector<int> of length specified by getPolynomialDegreeLength(), indicating what the maximum degree in each dimension should be
Returns
a std::vector<int> containing the ordinals of matching basis functions
Definition at line 641 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForDegree().
getFieldOrdinalsForH1Degree() [1/2]
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray1DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForH1Degree (OrdinalTypeArray1DHost & degrees) const inline
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
Parameters
degrees [in] - 1D host ordinal array of length specified by getPolynomialDegreeLength(), indicating what the maximum degree in each dimension should be
Returns
a 1D host ordinal array containing the ordinals of matching basis functions
Definition at line 605 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::fieldOrdinalH1PolynomialDegree_.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForH1Degree().
getFieldOrdinalsForH1Degree() [2/2]
template<typename Device , typename outputValueType , typename pointValueType > std::vector< int > Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForH1Degree (std::vector< int > & degrees) const inline
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
This variant takes a std::vector of polynomial degrees and returns a std::vector of field ordinals. It calls the other variant, which uses Kokkos Views on the host.
Parameters
degrees [in] - std::vector<int> of length specified by getPolynomialDegreeLength(), indicating what the maximum degree in each dimension should be
Returns
a std::vector<int> containing the ordinals of matching basis functions
Definition at line 669 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForH1Degree().
getFunctionSpace()
template<typename Device , typename outputValueType , typename pointValueType > EFunctionSpace Intrepid2::Basis< Device, outputValueType, pointValueType >::getFunctionSpace () const inline
Returns the function space for the basis.
Returns
the function space.
Definition at line 824 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::functionSpace_.
getH1PolynomialDegreeOfField()
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray1DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfField (int fieldOrdinal) const inline
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
Parameters
fieldOrdinal [in] - ordinal of the basis function whose polynomial degree is requested.
Returns
a 1D host array of length matching getPolynomialDegreeLength(), with the H^1 polynomial degree of the basis function in each dimension.
Definition at line 715 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, Intrepid2::Basis< Device, outputValueType, pointValueType >::fieldOrdinalH1PolynomialDegree_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeLength().
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfFieldAsVector().
getH1PolynomialDegreeOfFieldAsVector()
template<typename Device , typename outputValueType , typename pointValueType > std::vector< int > Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfFieldAsVector (int fieldOrdinal) const inline
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
Parameters
fieldOrdinal [in] - ordinal of the basis function whose polynomial degree is requested.
Returns
a std::vector<int> of length matching getPolynomialDegreeLength(), with the polynomial degree of the basis function in each dimension.
Definition at line 759 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfField().
getHostBasis()
template<typename Device , typename outputValueType , typename pointValueType > virtual HostBasisPtr< OutputValueType, PointValueType > Intrepid2::Basis< Device, outputValueType, pointValueType >::getHostBasis () const inline virtual
Creates and returns a Basis object whose DeviceType template argument is Kokkos::HostSpace::device_type, but is otherwise identical to this.
Returns
Pointer to the new Basis object.
Reimplemented in Intrepid2::Basis_HCURL_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_PYR_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_PYR_I2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_WEDGE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_WEDGE_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::Basis_HVOL_C0_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 997 of file Intrepid2_Basis.hpp.
getName()
template<typename Device , typename outputValueType , typename pointValueType > virtual const char * Intrepid2::Basis< Device, outputValueType, pointValueType >::getName () const inline virtual
Returns basis name.
Returns
the name of the basis
Reimplemented in Intrepid2::Basis_HCURL_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_PYR_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_PYR_I2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_COMP12_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_WEDGE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_WEDGE_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::Basis_HVOL_C0_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 788 of file Intrepid2_Basis.hpp.
getNumTensorialExtrusions()
template<typename Device , typename outputValueType , typename pointValueType > virtual int Intrepid2::Basis< Device, outputValueType, pointValueType >::getNumTensorialExtrusions () const inline virtual
returns the number of tensorial extrusions relative to the cell topology returned by getBaseCellTopology(). Base class returns 0; overridden by TensorBasis.
Definition at line 918 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getDomainDimension().
getPolynomialDegreeLength()
template<typename Device , typename outputValueType , typename pointValueType > int Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeLength () const inline
For hierarchical bases, returns the number of entries required to specify the polynomial degree of a basis function.
Definition at line 775 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::fieldOrdinalPolynomialDegree_.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfField(), and Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfField().
getPolynomialDegreeOfField()
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray1DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfField (int fieldOrdinal) const inline
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
Parameters
fieldOrdinal [in] - ordinal of the basis function whose polynomial degree is requested.
Returns
a 1D host array of length matching getPolynomialDegreeLength(), with the polynomial degree of the basis function in each dimension.
Definition at line 693 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, Intrepid2::Basis< Device, outputValueType, pointValueType >::fieldOrdinalPolynomialDegree_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeLength().
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfFieldAsVector().
getPolynomialDegreeOfFieldAsVector()
template<typename Device , typename outputValueType , typename pointValueType > std::vector< int > Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfFieldAsVector (int fieldOrdinal) const inline
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
Parameters
fieldOrdinal [in] - ordinal of the basis function whose polynomial degree is requested.
Returns
a std::vector<int> of length matching getPolynomialDegreeLength(), with the polynomial degree of the basis function in each dimension.
Definition at line 738 of file Intrepid2_Basis.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_, and Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfField().
getScratchSpaceSize()
template<typename Device , typename outputValueType , typename pointValueType > virtual void Intrepid2::Basis< Device, outputValueType, pointValueType >::getScratchSpaceSize (ordinal_type & perTeamSpaceSize, ordinal_type & perThreadSpaceSize, const PointViewType inputPoints, const EOperator operatorType = OPERATOR_VALUE) const inline virtual
Return the size of the scratch space, in bytes, needed for using the team-level implementation of getValues.
Warning, inputPoints is only used to deduce the type of the points where to evaluate basis functions. The rank of inputPoints and its size are not relevant, however, when using DFAD types, inputPoints cannot be empty, otherwise the size of the scracth space needed won't be deduced correctly.
Parameters
space [in] - inputPoints
perTeamSpaceSize [out] - size of the scratch space needed per team
perThreadeSize [out] - size of the scratch space beeded per thread
Reimplemented in Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_COMP12_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >, and Intrepid2::Basis_HVOL_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >.
Definition at line 395 of file Intrepid2_Basis.hpp.
References INTREPID2_TEST_FOR_EXCEPTION_DEVICE_SAFE.
getSubCellRefBasis()
template<typename Device , typename outputValueType , typename pointValueType > virtual BasisPtr< DeviceType, OutputValueType, PointValueType > Intrepid2::Basis< Device, outputValueType, pointValueType >::getSubCellRefBasis (const ordinal_type subCellDim, const ordinal_type subCellOrd) const inline virtual
returns the basis associated to a subCell.
HGRAD case: The bases of the subCell are the restriction to the subCell of the bases of the parent cell. HCURL case: The bases of the subCell are the restriction to the subCell of the bases of the parent cell, projected onto the manifold tangent to the subCell HDIV case: The bases of the subCell are the restriction to the subCell of the bases of the parent cell, projected along the normal of the subCell
This method is not supported by all bases (e.g. bases defined on a line and HVOL bases).
Parameters
[in] subCellDim - dimension of subCell
[in] subCellOrd - position of the subCell among of the subCells having the same dimension
Returns
pointer to the subCell basis of dimension subCellDim and position subCellOrd
Reimplemented in Intrepid2::Basis_HCURL_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_PYR_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_PYR_I2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_WEDGE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_WEDGE_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 978 of file Intrepid2_Basis.hpp.
getValues() [1/5]
template<typename Device , typename outputValueType , typename pointValueType > virtual void Intrepid2::Basis< Device, outputValueType, pointValueType >::getValues (BasisValues< OutputValueType, DeviceType > outputValues, const TensorPoints< PointValueType, DeviceType > inputPoints, const EOperator operatorType = OPERATOR_VALUE) const inline virtual
Evaluation of a FEM basis on a reference cell, using point and output value containers that allow preservation of tensor-product structure.
Returns values of operatorType acting on FEM basis functions for a set of points in the reference cell for which the basis is defined.
Parameters
outputValues [out] - variable rank array with the basis values. Should be allocated using Basis::allocateBasisValues().
inputPoints [in] - rank-2 array (P,D) with the evaluation points. This should be allocated using Cubature::allocateCubaturePoints() and filled using Cubature::getCubature().
operatorType [in] - the operator acting on the basis function
The default implementation does not take advantage of any tensor-product structure; subclasses with tensor-product support must override allocateBasisValues() and this getValues() method.
Reimplemented in Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 488 of file Intrepid2_Basis.hpp.
getValues() [2/5]
template<typename Device , typename outputValueType , typename pointValueType > virtual void Intrepid2::Basis< Device, outputValueType, pointValueType >::getValues (const ExecutionSpace & , OutputViewType , const PointViewType , const EOperator = OPERATOR_VALUE) const inline virtual
Evaluation of a FEM basis on a reference cell.
Returns values of operatorType acting on FEM basis functions for a set of points in the reference cell for which the basis is defined.
Parameters
space [in] - execution space instance
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-2 array (P,D) with the evaluation points
operatorType [in] - the operator acting on the basis functions
Remarks
For rank and dimension specifications of the output array see Section MD array template arguments for basis methods. Dimensions of ArrayScalar arguments are checked at runtime if HAVE_INTREPID2_DEBUG is defined.
A FEM basis spans a COMPLETE or INCOMPLETE polynomial space on the reference cell which is a smooth function space. Thus, all operator types that are meaningful for the approximated function space are admissible. When the order of the operator exceeds the degree of the basis, the output array is filled with the appropriate number of zeros.
Reimplemented in Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_LINE_Cn_FEM_JACOBI< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_DEG2_FEM< serendipity, DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_COMP12_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, and Intrepid2::Basis_HGRAD_TRI_Cn_FEM_ORTH< DeviceType, outputValueType, pointValueType >.
Definition at line 458 of file Intrepid2_Basis.hpp.
getValues() [3/5]
template<typename Device , typename outputValueType , typename pointValueType > virtual void Intrepid2::Basis< Device, outputValueType, pointValueType >::getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType = OPERATOR_VALUE) const inline virtual
Reimplemented in Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 467 of file Intrepid2_Basis.hpp.
getValues() [4/5]
template<typename Device , typename outputValueType , typename pointValueType > virtual KOKKOS_INLINE_FUNCTION void Intrepid2::Basis< Device, outputValueType, pointValueType >::getValues (OutputViewType , const PointViewType , const EOperator , const typename Kokkos::TeamPolicy< ExecutionSpace >::member_type & teamMember, const typename ExecutionSpace::scratch_memory_space & scratchStorage, const ordinal_type subcellDim = -1, const ordinal_type subcellOrdinal = -1) const inline virtual
Team-level evaluation of basis functions on a reference cell.
Returns values of operatorType acting on basis functions for a set of points in the reference cell for which the basis is defined.
The interface allow also to select basis functions associated to a particular entity. As an example, if subcellDim==1 (edges) and subcellOrdinal==0, outputValues will contain all the basis functions associated with the first edge. outputValues will contain all the cell basis functions when the default value (-1) is used for subcellDim and subcellOrdinal
Parameters
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-2 array (P,D) with the evaluation points
operatorType [in] - the operator acting on the basis functions
teamMember [in] - team member of the Kokkos::TemaPolicy
scratchStorage [in] - scratch space to use by each team
subcellDim [in] - the dimension of the subcells, the default values of -1 returns basis functions associated to subcells of all dimensions
subcellOrdinal [in] - the ordinal of the subcell, the default values of -1 returns basis functions associated to subcells of all ordinals
Remarks
This function is supposed to be called within a TeamPolicy kernel. The size of the required scratch space is determined by the getScratchSpaceSize function.
Reimplemented in Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 426 of file Intrepid2_Basis.hpp.
References INTREPID2_TEST_FOR_EXCEPTION_DEVICE_SAFE.
Referenced by Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs(), Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs(), and Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::getValues().
getValues() [5/5]
template<typename Device , typename outputValueType , typename pointValueType > virtual void Intrepid2::Basis< Device, outputValueType, pointValueType >::getValues (OutputViewType , const PointViewType , const PointViewType , const EOperator = OPERATOR_VALUE) const inline virtual
Evaluation of an FVD basis evaluation on a physical cell.
Returns values of operatorType acting on FVD basis functions for a set of points in the physical cell for which the FVD basis is defined.
Parameters
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-2 array (P,D) with the evaluation points
cellVertices [in] - rank-2 array (V,D) with the vertices of the physical cell
operatorType [in] - the operator acting on the basis functions
Remarks
For rank and dimension specifications of the output array see Section MD array template arguments for basis methods. Dimensions of ArrayScalar arguments are checked at runtime if HAVE_INTREPID2_DEBUG is defined.
A typical FVD basis spans a BROKEN discrete space which is only piecewise smooth. For example, it could be a piecewise constant space defined with respect to a partition of the cell into simplices. Because differential operators are not meaningful for such spaces, the default operator type in this method is set to OPERATOR_VALUE.
Reimplemented in Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 532 of file Intrepid2_Basis.hpp.
requireOrientation()
template<typename Device , typename outputValueType , typename pointValueType > virtual bool Intrepid2::Basis< Device, outputValueType, pointValueType >::requireOrientation () const inline virtual
True if orientation is required.
Reimplemented in Intrepid2::Basis_HCURL_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HCURL_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HDIV_WEDGE_I1_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, double, double, true >, Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >, Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >, Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >, Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >, Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >, Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >, and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >.
Definition at line 796 of file Intrepid2_Basis.hpp.
setOrdinalTagData()
template<typename Device , typename outputValueType , typename pointValueType > template<typename OrdinalTypeView3D , typename OrdinalTypeView2D , typename OrdinalTypeView1D > void Intrepid2::Basis< Device, outputValueType, pointValueType >::setOrdinalTagData (OrdinalTypeView3D & tagToOrdinal, OrdinalTypeView2D & ordinalToTag, const OrdinalTypeView1D tags, const ordinal_type basisCard, const ordinal_type tagSize, const ordinal_type posScDim, const ordinal_type posScOrd, const ordinal_type posDfOrd) inline protected
Fills ordinalToTag_ and tagToOrdinal_ by basis-specific tag data.
Parameters
tagToOrdinal [out] - Lookup table for the DoF's ordinal by its tag
ordinalToTag [out] - Lookup table for the DoF's tag by its ordinal
tags [in] - a set of basis-dependent tags in flat (rank-1) array format.
basisCard [in] - cardinality of the basis
tagSize [in] - number of fields in a DoF tag
posScDim [in] - position in the tag, counting from 0, of the subcell dim
posScOrd [in] - position in the tag, counting from 0, of the subcell ordinal
posDfOrd [in] - position in the tag, counting from 0, of DoF ordinal relative to the subcell
Definition at line 233 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
Member Data Documentation
basisCardinality_
template<typename Device , typename outputValueType , typename pointValueType > ordinal_type Intrepid2::Basis< Device, outputValueType, pointValueType >::basisCardinality_ protected
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
Definition at line 162 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getCardinality(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
basisCellTopologyKey_
template<typename Device , typename outputValueType , typename pointValueType > unsigned Intrepid2::Basis< Device, outputValueType, pointValueType >::basisCellTopologyKey_ protected
Identifier of the base topology of the cells for which the basis is defined. See the Shards package for definition of base cell topology. For TensorBasis subclasses, by default this the cell topology that is extruded (i.e., it is a lower-dimensional CellTopology than the space on which the tensor basis is defined). This allows tensor bases to be defined in higher dimensions than shards::CellTopology supports. TensorBasis subclasses can opt to use an equivalent shards CellTopology for base topology, as well as using Intrepid2's tagging for tensor bases in dimensions up to 3, by calling TensorBasis::setShardsTopologyAndTags().
Definition at line 175 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getBaseCellTopology(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
basisCoordinates_
template<typename Device , typename outputValueType , typename pointValueType > ECoordinates Intrepid2::Basis< Device, outputValueType, pointValueType >::basisCoordinates_ protected
The coordinate system for which the basis is defined.
Definition at line 183 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getCoordinateSystem(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
basisDegree_
template<typename Device , typename outputValueType , typename pointValueType > ordinal_type Intrepid2::Basis< Device, outputValueType, pointValueType >::basisDegree_ protected
Degree of the largest complete polynomial space that can be represented by the basis.
Definition at line 166 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getDegree(), Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HVOL_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis(), Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getSubCellRefBasis(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::getSubCellRefBasis(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::getSubCellRefBasis(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::getSubCellRefBasis(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::getSubCellRefBasis(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::getSubCellRefBasis(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::getSubCellRefBasis(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::getSubCellRefBasis(), Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::requireOrientation(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::requireOrientation(), Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::requireOrientation(), and Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::requireOrientation().
basisType_
template<typename Device , typename outputValueType , typename pointValueType > EBasis Intrepid2::Basis< Device, outputValueType, pointValueType >::basisType_ protected
Type of the basis.
Definition at line 179 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getBasisType(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForDegree(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForDegree(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForH1Degree(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForH1Degree(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfField(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfFieldAsVector(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeLength(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfField(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfFieldAsVector(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
dofCoeffs_
template<typename Device , typename outputValueType , typename pointValueType > Kokkos::DynRankView<scalarType,DeviceType> Intrepid2::Basis< Device, outputValueType, pointValueType >::dofCoeffs_ protected
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords_(i)) \cdot dofCoeffs_(i) are the nodal coefficients associated to basis functions i.
Rank-1 array for scalar basis with dimension (cardinality) Rank-2 array for vector basis with dimensions (cardinality, cell dimension)
Definition at line 295 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs(), and Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs().
dofCoords_
template<typename Device , typename outputValueType , typename pointValueType > Kokkos::DynRankView<scalarType,DeviceType> Intrepid2::Basis< Device, outputValueType, pointValueType >::dofCoords_ protected
Coordinates of degrees-of-freedom for basis functions defined in physical space.
Definition at line 285 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HCURL_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HCURL_TET_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HCURL_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HCURL_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HCURL_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HDIV_QUAD_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HDIV_TET_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HDIV_TET_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HDIV_TRI_I1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HDIV_TRI_In_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_HEX_C1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_LINE_C1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_LINE_C2_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_QUAD_C1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_TET_C1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_TET_C2_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_TET_COMP12_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_TRI_C1_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_TRI_C2_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HGRAD_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HVOL_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HVOL_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HVOL_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), Intrepid2::Basis_HVOL_TET_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords(), and Intrepid2::Basis_HVOL_TRI_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords().
fieldOrdinalH1PolynomialDegree_
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray2DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::fieldOrdinalH1PolynomialDegree_ protected
H^1 polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
The H^1 polynomial degree is identical to the polynomial degree for H(grad) bases. For H(vol) bases, it is one higher than the polynomial degree. Since H(div) and H(curl) bases are constructed as products of H(vol) and H(grad) bases, the H^1 degree in a given dimension is the H^1 degree for the multiplicand in that dimension.
Rank-2 array with dimensions (cardinality, cell dimension)
Definition at line 317 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForH1Degree(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getH1PolynomialDegreeOfField(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
fieldOrdinalPolynomialDegree_
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray2DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::fieldOrdinalPolynomialDegree_ protected
Polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
Rank-2 array with dimensions (cardinality, cell dimension)
Definition at line 304 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getFieldOrdinalsForDegree(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeLength(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getPolynomialDegreeOfField(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
functionSpace_
template<typename Device , typename outputValueType , typename pointValueType > EFunctionSpace Intrepid2::Basis< Device, outputValueType, pointValueType >::functionSpace_ = FUNCTION_SPACE_MAX protected
The function space in which the basis is defined.
Definition at line 187 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getFunctionSpace(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::HierarchicalBasis_HDIV_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TRI(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
ordinalToTag_
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray2DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::ordinalToTag_ protected
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
DoF ordinal to tag lookup table.
Rank-2 array with dimensions (basisCardinality_, 4) containing the DoF tags. This array is left empty at instantiation and filled by initializeTags() only when tag data is requested.
ordinalToTag_[DofOrd][0] = dim. of the subcell associated with the specified DoF
ordinalToTag_[DofOrd][1] = ordinal of the subcell defined in the cell topology
ordinalToTag_[DodOrd][2] = ordinal of the specified DoF relative to the subcell
ordinalToTag_[DofOrd][3] = total number of DoFs associated with the subcell
Definition at line 204 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getAllDofTags(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofTag(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
tagToOrdinal_
template<typename Device , typename outputValueType , typename pointValueType > OrdinalTypeArray3DHost Intrepid2::Basis< Device, outputValueType, pointValueType >::tagToOrdinal_ protected
DoF tag to ordinal lookup table.
Rank-3 array with dimensions (maxScDim + 1, maxScOrd + 1, maxDfOrd + 1), i.e., the columnwise maximums of the 1st three columns in the DoF tag table for the basis plus 1. For every triple (subscDim, subcOrd, subcDofOrd) that is valid DoF tag data this array stores the corresponding DoF ordinal. If the triple does not correspond to tag data, the array stores -1. This array is left empty at instantiation and filled by initializeTags() only when tag data is requested.
tagToOrdinal_[subcDim][subcOrd][subcDofOrd] = Degree-of-freedom ordinal
Definition at line 217 of file Intrepid2_Basis.hpp.
Referenced by Intrepid2::Basis< Device, outputValueType, pointValueType >::getAllDofOrdinal(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCount(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofOrdinal(), Intrepid2::HierarchicalBasis_HCURL_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TET(), Intrepid2::HierarchicalBasis_HCURL_TRI< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HCURL_TRI(), Intrepid2::HierarchicalBasis_HDIV_PYR< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_PYR(), Intrepid2::HierarchicalBasis_HDIV_TET< DeviceType, OutputScalar, PointScalar, useCGBasis >::HierarchicalBasis_HDIV_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_LINE< DeviceType, OutputScalar, PointScalar, defineVertexFunctions, useMinusOneToOneReferenceElement >::IntegratedLegendreBasis_HGRAD_LINE(), Intrepid2::IntegratedLegendreBasis_HGRAD_PYR< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_PYR(), Intrepid2::IntegratedLegendreBasis_HGRAD_TET< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TET(), Intrepid2::IntegratedLegendreBasis_HGRAD_TRI< DeviceType, OutputScalar, PointScalar, defineVertexFunctions >::IntegratedLegendreBasis_HGRAD_TRI(), Intrepid2::LegendreBasis_HVOL_LINE< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_LINE(), Intrepid2::LegendreBasis_HVOL_PYR< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_PYR(), Intrepid2::LegendreBasis_HVOL_TET< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TET(), and Intrepid2::LegendreBasis_HVOL_TRI< DeviceType, OutputScalar, PointScalar >::LegendreBasis_HVOL_TRI().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_BasisDef.hpp