Intrepid2: Intrepid2::ProjectionTools< DeviceType > Class Template Reference
Intrepid2::ProjectionTools< DeviceType > Class Template Reference
A class providing static members to perform projection-based interpolations:
#include <Intrepid2_ProjectionTools.hpp>
Classes
struct ElemSystem
Class to solve a square system A x = b on each cell A is expected to be saddle a point (KKT) matrix of the form [C B; B^T 0], where C has size nxn and B nxm, with n>0, m>=0. B^T is copied from B, so one does not have to define the B^T portion of A. b will contain the solution x. The first n-entries of x are copied into the provided basis coefficients using the provided indexing. The system is solved either with a QR factorization implemented in KokkosKernels or with Lapack GELS function.
Public Types
using ExecSpaceType = typename DeviceType::execution_space
using MemSpaceType = typename DeviceType::memory_space
using EvalPointsType = typename ProjectionStruct< DeviceType, double >::EvalPointsType
Static Public Member Functions
template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties>
static void getL2BasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType *cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > *projStruct)
Computes the basis coefficients of the L2 projection of the target function.
template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties>
static void getL2DGBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType *cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > *projStruct)
Computes evaluation points for local L2 projection for broken HGRAD HCURL HDIV and HVOL spaces.
template<typename basisViewType , typename targetViewType , typename BasisType >
static void getL2DGBasisCoeffs (basisViewType basisCoeffs, const targetViewType targetAtTargetEPoints, const BasisType *cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > *projStruct)
Computes evaluation points for local L2 projection for broken HGRAD HCURL HDIV and HVOL spaces.
template<class BasisCoeffsViewType , class TargetValueViewType , class TargetGradViewType , class BasisType , class OrientationViewType >
static void getHGradBasisCoeffs (BasisCoeffsViewType basisCoeffs, const TargetValueViewType targetAtEvalPoints, const TargetGradViewType targetGradAtGradEvalPoints, const OrientationViewType cellOrientations, const BasisType *cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > *projStruct)
Computes the basis coefficients of the HGrad projection of the target function.
template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties>
static void getHCurlBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetCurlAtCurlEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType *cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > *projStruct)
Computes the basis coefficients of the HCurl projection of the target function.
template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties>
static void getHDivBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetDivAtDivEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType *cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > *projStruct)
Computes the basis coefficients of the HDiv projection of the target function.
template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties>
static void getHVolBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType *cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > *projStruct)
Computes the basis coefficients of the HVol projection of the target function.
template<typename dstViewType , typename dstBasisType , typename srcViewType , typename srcBasisType , typename OrientationViewType >
static void projectField (dstViewType dstCoeffs, const dstBasisType *dstBasis, const srcViewType srcCoeffs, const srcBasisType *srcBasis, const OrientationViewType cellOrientations)
Computes the L2 projection of a finite element field into a compatible finite element space.
Detailed Description
template<typename DeviceType>
class Intrepid2::ProjectionTools< DeviceType >
A class providing static members to perform projection-based interpolations:
This class provides tools to perform projection-based interpolations of a target function that satisfy the commutativity property of the De Rham complex and that have optimal accuracy w.r.t. the corresponding norms (, , ,).
The projection-based interpolation of the target function reads
where is the basis of the finite element, are the basisCoeffs.
It also provides tools to perform a local L2 projection into HGrad, HCurl, HDiv and L2 fields. This projection does not satisfy the properties of the projection-based interpolations, but it is simpler and does not require to evaluate the derivatives of the target functions.
Use:
create a ProjectionStruct object
get the evaluation points where to evaluate the target function and its derivative using the ProjectionStruct methods getAllEvalPoints and getAllDerivEvalPoints
Map to the physical elements the evaluation points, evaluate the target function and its derivatives at these points and map them back (inverse of pullback operator) to the reference points. Note: if the target function is defined at reference element (e.g. in case the target function is a combination of basis functions) there is no need to map points and functions between the reference and physical spaces, but one needs to simply evaluate the target function and its derivatives at the evaluation points
Evaluate the basis coefficients using one of the methods getHGradBasisCoeffs, getHCURLBasisCoeffs, getHDivBasisCoeffs, getHVolBasisCoeffs, or getL2BasisCoeffs
Remarks
The projections are performed at the oriented reference element. Therefore, the target function , which is contravariant, needs to be mapped back to the reference element (using inverse of pullback operator) before calling getXXXBasisCoeffs.
The projections are implemented as in "Demkowics et al., Computing with Hp-Adaptive Finite Elements, Vol. 2, Chapman & Hall/CRC 2007". However, the projections along edges for HGrad and HCurl elements have been performed on the seminorm and the norm respectively, instead of on the and and norms. This requires more regularity of the target function.
Todo:
There is room for improvement. One could separate the computation of the basis function values and derivatives from the functions getXXXBasisCoeffs, so that they can be stored and reused for projecting other target functions. Similarly one could store all the QR factorizations and reuse them for other target functions.
Definition at line 116 of file Intrepid2_ProjectionTools.hpp.
Member Typedef Documentation
EvalPointsType
template<typename DeviceType > using Intrepid2::ProjectionTools< DeviceType >::EvalPointsType = typename ProjectionStruct<DeviceType, double>::EvalPointsType
Definition at line 120 of file Intrepid2_ProjectionTools.hpp.
ExecSpaceType
template<typename DeviceType > using Intrepid2::ProjectionTools< DeviceType >::ExecSpaceType = typename DeviceType::execution_space
Definition at line 118 of file Intrepid2_ProjectionTools.hpp.
MemSpaceType
template<typename DeviceType > using Intrepid2::ProjectionTools< DeviceType >::MemSpaceType = typename DeviceType::memory_space
Definition at line 119 of file Intrepid2_ProjectionTools.hpp.
Member Function Documentation
getHCurlBasisCoeffs()
template<typename DeviceType > template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties> void Intrepid2::ProjectionTools< DeviceType >::getHCurlBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetCurlAtCurlEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType * cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > * projStruct) static
Computes the basis coefficients of the HCurl projection of the target function.
C  - num. cells
F  - num. fields
P1 - num. evaluation points
P2 - num. evaluation points for derivatives
D  - spatial dimension
Parameters
basisCoeffs [out] - rank-2 view (C,F) containing the basis coefficients
targetAtEvalPoints [in] - rank-3 view (C,P1,D) containing the values of the target function evaluated at the evaluation points given by projStruct->getAllEvalPoints()
targetcurlAtCurlEvalPoints [in] - variable rank view containing the values of the curl of the target function evaluated at the evaluation points given by projStruct->getAllDerivEvalPoints()
cellOrientations [in] - 1-rank view (C) containing the Orientation objects at each cell
cellBasis [in] - pointer to the HCURL basis for the projection
projStruct [in] - pointer to ProjectionStruct object
Remarks
targetAtCurlEvalPoints has rank 2 (C,P2) in 2D, and rank 3 (C,P2,D) in 3D
Definition at line 400 of file Intrepid2_ProjectionToolsDefHCURL.hpp.
References Intrepid2::RealSpaceTools< DeviceType >::clone(), Intrepid2::RefSubcellParametrization< DeviceType >::get(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllDerivEvalPoints(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getAllDofOrdinal(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisPointsRange(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getCardinality(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCount(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisDerivEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetDerivEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetEvalPoints(), Intrepid2::CellTools< DeviceType >::getReferenceEdgeTangent(), Intrepid2::CellTools< DeviceType >::getReferenceFaceNormal(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetPointsRange(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getValues(), Intrepid2::FunctionSpaceTools< DeviceType >::integrate(), Intrepid2::OrientationTools< DeviceType >::modifyBasisByOrientationInverse(), and Intrepid2::ProjectionTools< DeviceType >::ElemSystem::solve().
getHDivBasisCoeffs()
template<typename DeviceType > template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties> void Intrepid2::ProjectionTools< DeviceType >::getHDivBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetDivAtDivEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType * cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > * projStruct) static
Computes the basis coefficients of the HDiv projection of the target function.
C  - num. cells
F  - num. fields
P1 - num. evaluation points
P2 - num. evaluation points for derivatives
D  - spatial dimension
Parameters
basisCoeffs [out] - rank-2 view (C,F) containing the basis coefficients
targetAtEvalPoints [in] - rank-3 view (C,P1,D) containing the values of the target function evaluated at the evaluation points given by projStruct->getAllEvalPoints()
targetDivAtDivEvalPoints [in] - rank-2 view (C,P2) view containing the values of the divergence of the target function evaluated at the evaluation points given by projStruct->getAllDerivEvalPoints()
cellOrientations [in] - 1-rank view (C) containing the Orientation objects at each cell
cellBasis [in] - pointer to the HDIV basis for the projection
projStruct [in] - pointer to ProjectionStruct object
Definition at line 235 of file Intrepid2_ProjectionToolsDefHDIV.hpp.
References Intrepid2::RealSpaceTools< DeviceType >::clone(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllDerivEvalPoints(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getAllDofOrdinal(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisPointsRange(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getCardinality(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getDofCount(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisDerivEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetDerivEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetEvalPoints(), Intrepid2::CellTools< DeviceType >::getReferenceSideNormal(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetPointsRange(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getValues(), Intrepid2::FunctionSpaceTools< DeviceType >::integrate(), Intrepid2::OrientationTools< DeviceType >::modifyBasisByOrientationInverse(), and Intrepid2::ProjectionTools< DeviceType >::ElemSystem::solve().
getHGradBasisCoeffs()
template<typename DeviceType > template<class BasisCoeffsViewType , class TargetValueViewType , class TargetGradViewType , class BasisType , class OrientationViewType > void Intrepid2::ProjectionTools< DeviceType >::getHGradBasisCoeffs (BasisCoeffsViewType basisCoeffs, const TargetValueViewType targetAtEvalPoints, const TargetGradViewType targetGradAtGradEvalPoints, const OrientationViewType cellOrientations, const BasisType * cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > * projStruct) static
Computes the basis coefficients of the HGrad projection of the target function.
C  - num. cells
F  - num. fields
P1 - num. evaluation points
P2 - num. evaluation points for derivatives
D  - spatial dimension
Parameters
basisCoeffs [out] - rank-2 view (C,F) containing the basis coefficients
targetAtEvalPoints [in] - rank-2 view (C,P1) containing the values of the target function evaluated at the evaluation points given by projStruct->getAllEvalPoints()
targetGradAtGradEvalPoints [in] - rank-3 view (C,P2,D) view containing the values of the gradient of the target function evaluated at the evaluation points given by projStruct->getAllDerivEvalPoints()
cellOrientations [in] - 1-rank view (C) containing the Orientation objects at each cell
cellBasis [in] - pointer to the HGRAD basis for the projection
projStruct [in] - pointer to ProjectionStruct object
Definition at line 288 of file Intrepid2_ProjectionToolsDefHGRAD.hpp.
References Intrepid2::RefSubcellParametrization< DeviceType >::get(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllDerivEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisDerivPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisDerivEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetDerivEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetEvalPoints(), Intrepid2::CellTools< DeviceType >::getReferenceEdgeTangent(), Intrepid2::CellTools< DeviceType >::getReferenceFaceNormal(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetDerivPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetPointsRange(), Intrepid2::FunctionSpaceTools< DeviceType >::integrate(), Intrepid2::OrientationTools< DeviceType >::modifyBasisByOrientationInverse(), and Intrepid2::ProjectionTools< DeviceType >::ElemSystem::solve().
Referenced by Intrepid2::ProjectedGeometry< spaceDim, PointScalar, DeviceType >::projectOntoHGRADBasis().
getHVolBasisCoeffs()
template<typename DeviceType > template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties> void Intrepid2::ProjectionTools< DeviceType >::getHVolBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType * cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > * projStruct) static
Computes the basis coefficients of the HVol projection of the target function.
C  - num. cells
F  - num. fields
P  - num. evaluation points
D  - spatial dimension
Parameters
basisCoeffs [out] - rank-2 view (C,F) containing the basis coefficients
targetAtEvalPoints [in] - rank-2 view (C,P) containing the values of the target function evaluated at the evaluation points given by projStruct->getAllEvalPoints()
cellOrientations [in] - 1-rank view (C) containing the Orientation objects at each cell
cellBasis [in] - pointer to the HGRAD basis for the projection
projStruct [in] - pointer to ProjectionStruct object
Definition at line 32 of file Intrepid2_ProjectionToolsDefHVOL.hpp.
References Intrepid2::RealSpaceTools< DeviceType >::clone(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetPointsRange(), Intrepid2::FunctionSpaceTools< DeviceType >::integrate(), and Intrepid2::ProjectionTools< DeviceType >::ElemSystem::solve().
getL2BasisCoeffs()
template<typename DeviceType > template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties> void Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType * cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > * projStruct) static
Computes the basis coefficients of the L2 projection of the target function.
C  - num. cells
F  - num. fields
P  - num. evaluation points
D  - spatial dimension
Parameters
basisCoeffs [out] - rank-2 view (C,F) containing the basis coefficients
targetAtEvalPoints [in] - variable rank view containing the values of the target function evaluated at the evaluation points given by projStruct->getAllEvalPoints()
cellOrientations [in] - 1-rank view (C) containing the Orientation objects at each cell
cellBasis [in] - pointer to the basis for the projection
projStruct [in] - pointer to ProjectionStruct object
Remarks
targetAtEvalPoints has rank 2 (C,P) for HGRAD and HVOL elements, and rank 3 (C,P,D) for HCURL and HDIV elements
Definition at line 358 of file Intrepid2_ProjectionToolsDefL2.hpp.
References Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisPointsRange(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumTargetEvalPoints(), Intrepid2::CellTools< DeviceType >::getReferenceEdgeTangent(), Intrepid2::CellTools< DeviceType >::getReferenceSideNormal(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetPointsRange(), Intrepid2::FunctionSpaceTools< DeviceType >::integrate(), Intrepid2::OrientationTools< DeviceType >::modifyBasisByOrientationInverse(), and Intrepid2::ProjectionTools< DeviceType >::ElemSystem::solve().
Referenced by Intrepid2::ProjectionTools< DeviceType >::projectField().
getL2DGBasisCoeffs() [1/2]
template<typename DeviceType > template<typename basisViewType , typename targetViewType , typename BasisType > void Intrepid2::ProjectionTools< DeviceType >::getL2DGBasisCoeffs (basisViewType basisCoeffs, const targetViewType targetAtTargetEPoints, const BasisType * cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > * projStruct) static
Computes evaluation points for local L2 projection for broken HGRAD HCURL HDIV and HVOL spaces.
This function simply perform an L2 projection in each cell with no guarantee of preserving continuity across cells. It also does not account for orientation.
C  - num. cells
F  - num. fields
P  - num. evaluation points
D  - spatial dimension
Parameters
basisCoeffs [out] - rank-2 view (C,F) containing the basis coefficients
targetAtEvalPoints [in] - variable rank view containing the values of the target function evaluated at the evaluation points
cellBasis [in] - pointer to the basis for the projection
projStruct [in] - pointer to ProjectionStruct object
Remarks
targetAtEvalPoints has rank 2 (C,P) for HGRAD and HVOL elements, and rank 3 (C,P,D) for HCURL and HDIV elements
Definition at line 639 of file Intrepid2_ProjectionToolsDefL2.hpp.
References Intrepid2::RealSpaceTools< DeviceType >::clone(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getBasisEvalWeights(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getNumBasisEvalPoints(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getTargetEvalWeights(), Intrepid2::FunctionSpaceTools< DeviceType >::integrate(), and Intrepid2::ProjectionTools< DeviceType >::ElemSystem::solve().
getL2DGBasisCoeffs() [2/2]
template<typename DeviceType > template<typename basisCoeffsValueType , class ... basisCoeffsProperties, typename funValsValueType , class ... funValsProperties, typename BasisType , typename ortValueType , class ... ortProperties> void Intrepid2::ProjectionTools< DeviceType >::getL2DGBasisCoeffs (Kokkos::DynRankView< basisCoeffsValueType, basisCoeffsProperties... > basisCoeffs, const Kokkos::DynRankView< funValsValueType, funValsProperties... > targetAtEvalPoints, const Kokkos::DynRankView< ortValueType, ortProperties... > cellOrientations, const BasisType * cellBasis, ProjectionStruct< DeviceType, typename BasisType::scalarType > * projStruct) static
Computes evaluation points for local L2 projection for broken HGRAD HCURL HDIV and HVOL spaces.
This function simply perform an L2 projection in each cell with no guarantee of preserving continuity across cells
C  - num. cells
F  - num. fields
P  - num. evaluation points
D  - spatial dimension
Parameters
basisCoeffs [out] - rank-2 view (C,F) containing the basis coefficients
targetAtEvalPoints [in] - variable rank view containing the values of the target function evaluated at the evaluation points
cellOrientations [in] - 1-rank view (C) containing the Orientation objects at each cell
cellBasis [in] - pointer to the basis for the projection
projStruct [in] - pointer to ProjectionStruct object
Remarks
targetAtEvalPoints has rank 2 (C,P) for HGRAD and HVOL elements, and rank 3 (C,P,D) for HCURL and HDIV elements
Definition at line 623 of file Intrepid2_ProjectionToolsDefL2.hpp.
References Intrepid2::OrientationTools< DeviceType >::modifyBasisByOrientationInverse().
projectField()
template<typename DeviceType > template<typename dstViewType , typename dstBasisType , typename srcViewType , typename srcBasisType , typename OrientationViewType > static void Intrepid2::ProjectionTools< DeviceType >::projectField (dstViewType dstCoeffs, const dstBasisType * dstBasis, const srcViewType srcCoeffs, const srcBasisType * srcBasis, const OrientationViewType cellOrientations) inline static
Computes the L2 projection of a finite element field into a compatible finite element space.
C  - num. cells
F  - num. fields
P  - num. evaluation points
D  - spatial dimension
Parameters
dstCoeffs [out] - rank-2 view (C,F) containing the basis coefficients of the projected field over the space generated by dstBasis
dstBasis [in] - pointer to the basis we want to project to
srcCoeffs [in] - rank-2 view (C,F) containing the basis coefficients of the field w.r.t. the original basis
srcBasis [in] - original basis
cellOrientations [in] - rank-1 view (C) containing the Orientation objects at each cell
Definition at line 370 of file Intrepid2_ProjectionTools.hpp.
References Intrepid2::ProjectionStruct< DeviceType, ValueType >::createL2ProjectionStruct(), Intrepid2::ProjectionStruct< DeviceType, ValueType >::getAllEvalPoints(), Intrepid2::ProjectionTools< DeviceType >::getL2BasisCoeffs(), and Intrepid2::OrientationTools< DeviceType >::modifyBasisByOrientation().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionTools.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHCURL.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHDIV.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHGRAD.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHVOL.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefL2.hpp