Intrepid2: Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType > Class Template Reference
Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType > Class Template Reference
Implementation of the locally H(grad)-compatible FEM basis of variable order on the [-1,1] reference line cell, using Lagrange polynomials.
#include <Intrepid2_HGRAD_LINE_Cn_FEM.hpp>
Public Types
using BasisBase = Basis< DeviceType, outputValueType, pointValueType >
using HostBasis = Basis_HGRAD_LINE_Cn_FEM< typename Kokkos::HostSpace::device_type, outputValueType, pointValueType >
Public Types inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
using DeviceType = Device
(Kokkos) Device type on which Basis is templated. Does not necessarily return true for Kokkos::is_device (may be Kokkos::Serial, for example).
using ExecutionSpace = typename DeviceType::execution_space
(Kokkos) Execution space for basis.
using OutputValueType = outputValueType
Output value type for basis; default is double.
using PointValueType = pointValueType
Point value type for basis; default is double.
using OrdinalViewType = Kokkos::View< ordinal_type, DeviceType >
View type for ordinal.
using EBasisViewType = Kokkos::View< EBasis, DeviceType >
View for basis type.
using ECoordinatesViewType = Kokkos::View< ECoordinates, DeviceType >
View for coordinate system type.
using OrdinalTypeArray1DHost = Kokkos::View< ordinal_type *, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 1d host array.
using OrdinalTypeArray2DHost = Kokkos::View< ordinal_type **, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 2d host array.
using OrdinalTypeArray3DHost = Kokkos::View< ordinal_type ***, typename ExecutionSpace::array_layout, Kokkos::HostSpace >
View type for 3d host array.
using OrdinalTypeArrayStride1DHost = Kokkos::View< ordinal_type *, Kokkos::LayoutStride, Kokkos::HostSpace >
View type for 1d host array.
using OrdinalTypeArray1D = Kokkos::View< ordinal_type *, DeviceType >
View type for 1d device array.
using OrdinalTypeArray2D = Kokkos::View< ordinal_type **, DeviceType >
View type for 2d device array.
using OrdinalTypeArray3D = Kokkos::View< ordinal_type ***, DeviceType >
View type for 3d device array.
using OrdinalTypeArrayStride1D = Kokkos::View< ordinal_type *, Kokkos::LayoutStride, DeviceType >
View type for 1d device array.
typedef ScalarTraits< pointValueType >::scalar_type scalarType
Scalar type for point values.
using OutputViewType = Kokkos::DynRankView< OutputValueType, Kokkos::LayoutStride, DeviceType >
View type for basis value output.
using PointViewType = Kokkos::DynRankView< PointValueType, Kokkos::LayoutStride, DeviceType >
View type for input points.
using ScalarViewType = Kokkos::DynRankView< scalarType, Kokkos::LayoutStride, DeviceType >
View type for scalars.
Public Member Functions
Basis_HGRAD_LINE_Cn_FEM (const ordinal_type order, const EPointType pointType=POINTTYPE_EQUISPACED)
Constructor.
virtual void getValues (const ExecutionSpace &space, OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const override
Evaluation of a FEM basis on a reference cell.
virtual void getScratchSpaceSize (ordinal_type &perTeamSpaceSize, ordinal_type &perThreadSpaceSize, const PointViewType inputPointsconst, const EOperator operatorType=OPERATOR_VALUE) const override
Return the size of the scratch space, in bytes, needed for using the team-level implementation of getValues.
virtual KOKKOS_INLINE_FUNCTION void getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType, const typename Kokkos::TeamPolicy< typename DeviceType::execution_space >::member_type &team_member, const typename DeviceType::execution_space::scratch_memory_space &scratchStorage, const ordinal_type subcellDim=-1, const ordinal_type subcellOrdinal=-1) const override
virtual void getDofCoords (ScalarViewType dofCoords) const override
Returns spatial locations (coordinates) of degrees of freedom on the reference cell.
virtual void getDofCoeffs (ScalarViewType dofCoeffs) const override
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords(i)) \cdot dofCoeffs(i) are the nodal coefficients associated to basis function i.
virtual const char * getName () const override
Returns basis name.
void getVandermondeInverse (ScalarViewType vinv) const
Kokkos::DynRankView< typename ScalarViewType::const_value_type, DeviceType > getVandermondeInverse () const
ordinal_type getWorkSizePerPoint (const EOperator operatorType) const
virtual HostBasisPtr< outputValueType, pointValueType > getHostBasis () const override
Creates and returns a Basis object whose DeviceType template argument is Kokkos::HostSpace::device_type, but is otherwise identical to this.
Public Member Functions inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
OutputValueType getDummyOutputValue ()
Dummy array to receive input arguments.
PointValueType getDummyPointValue ()
Dummy array to receive input arguments.
Kokkos::DynRankView< OutputValueType, DeviceType > allocateOutputView (const int numPoints, const EOperator operatorType=OPERATOR_VALUE) const
Allocate a View container suitable for passing to the getValues() variant that accepts Kokkos DynRankViews as arguments (as opposed to the Intrepid2 BasisValues and PointValues containers).
virtual BasisValues< OutputValueType, DeviceType > allocateBasisValues (TensorPoints< PointValueType, DeviceType > points, const EOperator operatorType=OPERATOR_VALUE) const
Allocate BasisValues container suitable for passing to the getValues() variant that takes a TensorPoints container as argument.
virtual KOKKOS_INLINE_FUNCTION void getValues (OutputViewType, const PointViewType, const EOperator, const typename Kokkos::TeamPolicy< ExecutionSpace >::member_type &teamMember, const typename ExecutionSpace::scratch_memory_space &scratchStorage, const ordinal_type subcellDim=-1, const ordinal_type subcellOrdinal=-1) const
Team-level evaluation of basis functions on a reference cell.
virtual void getValues (OutputViewType outputValues, const PointViewType inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
virtual void getValues (BasisValues< OutputValueType, DeviceType > outputValues, const TensorPoints< PointValueType, DeviceType > inputPoints, const EOperator operatorType=OPERATOR_VALUE) const
Evaluation of a FEM basis on a reference cell, using point and output value containers that allow preservation of tensor-product structure.
virtual void getValues (OutputViewType, const PointViewType, const PointViewType, const EOperator=OPERATOR_VALUE) const
Evaluation of an FVD basis evaluation on a physical cell.
OrdinalTypeArray1DHost getFieldOrdinalsForDegree (OrdinalTypeArray1DHost &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
OrdinalTypeArray1DHost getFieldOrdinalsForH1Degree (OrdinalTypeArray1DHost &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
std::vector< int > getFieldOrdinalsForDegree (std::vector< int > &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
std::vector< int > getFieldOrdinalsForH1Degree (std::vector< int > &degrees) const
For hierarchical bases, returns the field ordinals that have at most the specified H^1 degree in each dimension. Assuming that these are less than or equal to the polynomial orders provided at Basis construction, the corresponding polynomials will form a superset of the Basis of the same type constructed with polynomial orders corresponding to the specified degrees.
OrdinalTypeArray1DHost getPolynomialDegreeOfField (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
OrdinalTypeArray1DHost getH1PolynomialDegreeOfField (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
std::vector< int > getPolynomialDegreeOfFieldAsVector (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
std::vector< int > getH1PolynomialDegreeOfFieldAsVector (int fieldOrdinal) const
For hierarchical bases, returns the polynomial degree (which may have multiple values in higher spatial dimensions) for the specified basis ordinal as a host array.
int getPolynomialDegreeLength () const
For hierarchical bases, returns the number of entries required to specify the polynomial degree of a basis function.
virtual bool requireOrientation () const
True if orientation is required.
ordinal_type getCardinality () const
Returns cardinality of the basis.
ordinal_type getDegree () const
Returns the degree of the basis.
EFunctionSpace getFunctionSpace () const
Returns the function space for the basis.
shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation https://trilinos.org/packages/shards for definition of base cell topology.
EBasis getBasisType () const
Returns the basis type.
ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
ordinal_type getDofCount (const ordinal_type subcDim, const ordinal_type subcOrd) const
DoF count for specified subcell.
ordinal_type getDofOrdinal (const ordinal_type subcDim, const ordinal_type subcOrd, const ordinal_type subcDofOrd) const
DoF tag to ordinal lookup.
virtual int getNumTensorialExtrusions () const
returns the number of tensorial extrusions relative to the cell topology returned by getBaseCellTopology(). Base class returns 0; overridden by TensorBasis.
const OrdinalTypeArray3DHost getAllDofOrdinal () const
DoF tag to ordinal data structure.
const OrdinalTypeArrayStride1DHost getDofTag (const ordinal_type dofOrd) const
DoF ordinal to DoF tag lookup.
const OrdinalTypeArray2DHost getAllDofTags () const
Retrieves all DoF tags.
virtual BasisPtr< DeviceType, OutputValueType, PointValueType > getSubCellRefBasis (const ordinal_type subCellDim, const ordinal_type subCellOrd) const
returns the basis associated to a subCell.
ordinal_type getDomainDimension () const
Returns the spatial dimension of the domain of the basis; this is equal to getBaseCellTopology().getDimension() + getNumTensorialExtrusions().
Private Attributes
Kokkos::DynRankView< typename ScalarViewType::value_type, DeviceType > vinv_
inverse of Generalized Vandermonde matrix, whose columns store the expansion coefficients of the nodal basis in terms of phis_
EPointType pointType_
Additional Inherited Members
Protected Member Functions inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
template<typename OrdinalTypeView3D , typename OrdinalTypeView2D , typename OrdinalTypeView1D >
void setOrdinalTagData (OrdinalTypeView3D &tagToOrdinal, OrdinalTypeView2D &ordinalToTag, const OrdinalTypeView1D tags, const ordinal_type basisCard, const ordinal_type tagSize, const ordinal_type posScDim, const ordinal_type posScOrd, const ordinal_type posDfOrd)
Fills ordinalToTag_ and tagToOrdinal_ by basis-specific tag data.
Protected Attributes inherited from Intrepid2::Basis< Device, outputValueType, pointValueType >
ordinal_type basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
ordinal_type basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
unsigned basisCellTopologyKey_
Identifier of the base topology of the cells for which the basis is defined. See the Shards package for definition of base cell topology. For TensorBasis subclasses, by default this the cell topology that is extruded (i.e., it is a lower-dimensional CellTopology than the space on which the tensor basis is defined). This allows tensor bases to be defined in higher dimensions than shards::CellTopology supports. TensorBasis subclasses can opt to use an equivalent shards CellTopology for base topology, as well as using Intrepid2's tagging for tensor bases in dimensions up to 3, by calling TensorBasis::setShardsTopologyAndTags().
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
EFunctionSpace functionSpace_ = FUNCTION_SPACE_MAX
The function space in which the basis is defined.
OrdinalTypeArray2DHost ordinalToTag_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
OrdinalTypeArray3DHost tagToOrdinal_
DoF tag to ordinal lookup table.
Kokkos::DynRankView< scalarType, DeviceType > dofCoords_
Coordinates of degrees-of-freedom for basis functions defined in physical space.
Kokkos::DynRankView< scalarType, DeviceType > dofCoeffs_
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords_(i)) \cdot dofCoeffs_(i) are the nodal coefficients associated to basis functions i.
OrdinalTypeArray2DHost fieldOrdinalPolynomialDegree_
Polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
OrdinalTypeArray2DHost fieldOrdinalH1PolynomialDegree_
H^1 polynomial degree for each degree of freedom. Only defined for hierarchical bases right now. The number of entries per degree of freedom in this table depends on the basis type. For hypercubes, this will be the spatial dimension. We have not yet determined what this will be for simplices beyond 1D; there are not yet hierarchical simplicial bases beyond 1D in Intrepid2.
Detailed Description
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double>
class Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >
Implementation of the locally H(grad)-compatible FEM basis of variable order on the [-1,1] reference line cell, using Lagrange polynomials.
Implements Lagrange basis of variable order on the reference [-1,1] line cell. The distribution of the points may be equispaced points with our without the endpoints, the Gauss-Legendre or Gauss-Lobatto points. These points are {x_i}_{i=0}^n. with x_i < x_{i+1}
The basis has cardinality and spans a COMPLETE linear polynomial space. Basis functions are dual to a unisolvent set of degrees of freedom (DoF) n_i(psi) = psi(x_i). The DoF are ordered by i. The DoF at points -1 and 1 (if included in {x_i} are attached to the vertices, and the rest of the DoF are attached to the edge itself.
Definition at line 143 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
Member Typedef Documentation
BasisBase
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::BasisBase = Basis<DeviceType,outputValueType,pointValueType>
Definition at line 146 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
HostBasis
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> using Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::HostBasis = Basis_HGRAD_LINE_Cn_FEM<typename Kokkos::HostSpace::device_type,outputValueType,pointValueType>
Definition at line 149 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
Constructor & Destructor Documentation
Basis_HGRAD_LINE_Cn_FEM()
template<typename DT , typename OT , typename PT > Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DT, OT, PT >::Basis_HGRAD_LINE_Cn_FEM (const ordinal_type order, const EPointType pointType = POINTTYPE_EQUISPACED)
Constructor.
Definition at line 164 of file Intrepid2_HGRAD_LINE_Cn_FEMDef.hpp.
References Intrepid2::PointTools::getLattice(), Intrepid2::isValidPointType(), and Intrepid2::Parameters::MaxOrder.
Member Function Documentation
getDofCoeffs()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual void Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoeffs (ScalarViewType) const inline override virtual
Coefficients for computing degrees of freedom for Lagrangian basis If P is an element of the space spanned by the basis, \alpha_i := P(dofCoords(i)) \cdot dofCoeffs(i) are the nodal coefficients associated to basis function i.
Rank-1 array for scalar basis with dimension (cardinality) Rank-2 array for vector basis with dimensions (cardinality, cell dimension)
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 231 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
getDofCoords()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual void Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getDofCoords (ScalarViewType) const inline override virtual
Returns spatial locations (coordinates) of degrees of freedom on the reference cell.
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 214 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::dofCoords_.
Referenced by Intrepid2::Basis_HCURL_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HCURL_HEX_In_FEM(), Intrepid2::Basis_HCURL_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HCURL_QUAD_In_FEM(), Intrepid2::Basis_HDIV_HEX_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HDIV_HEX_In_FEM(), Intrepid2::Basis_HDIV_QUAD_In_FEM< DeviceType, outputValueType, pointValueType >::Basis_HDIV_QUAD_In_FEM(), Intrepid2::Basis_HGRAD_HEX_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HGRAD_HEX_Cn_FEM(), and Intrepid2::Basis_HGRAD_QUAD_Cn_FEM< DeviceType, outputValueType, pointValueType >::Basis_HGRAD_QUAD_Cn_FEM().
getHostBasis()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual HostBasisPtr< outputValueType, pointValueType > Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getHostBasis () const inline override virtual
Creates and returns a Basis object whose DeviceType template argument is Kokkos::HostSpace::device_type, but is otherwise identical to this.
Returns
Pointer to the new Basis object.
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 270 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::basisDegree_.
getName()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual const char * Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getName () const inline override virtual
Returns basis name.
Returns
the name of the basis
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 245 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
getScratchSpaceSize()
template<typename DT , typename OT , typename PT > void Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DT, OT, PT >::getScratchSpaceSize (ordinal_type & perTeamSpaceSize, ordinal_type & perThreadSpaceSize, const PointViewType inputPoints, const EOperator operatorType = OPERATOR_VALUE) const override virtual
Return the size of the scratch space, in bytes, needed for using the team-level implementation of getValues.
Warning, inputPoints is only used to deduce the type of the points where to evaluate basis functions. The rank of inputPoints and its size are not relevant, however, when using DFAD types, inputPoints cannot be empty, otherwise the size of the scracth space needed won't be deduced correctly.
Parameters
space [in] - inputPoints
perTeamSpaceSize [out] - size of the scratch space needed per team
perThreadeSize [out] - size of the scratch space beeded per thread
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 332 of file Intrepid2_HGRAD_LINE_Cn_FEMDef.hpp.
getValues()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> virtual void Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getValues (const ExecutionSpace & , OutputViewType , const PointViewType , const EOperator = OPERATOR_VALUE) const inline override virtual
Evaluation of a FEM basis on a reference cell.
Returns values of operatorType acting on FEM basis functions for a set of points in the reference cell for which the basis is defined.
Parameters
space [in] - execution space instance
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-2 array (P,D) with the evaluation points
operatorType [in] - the operator acting on the basis functions
Remarks
For rank and dimension specifications of the output array see Section MD array template arguments for basis methods. Dimensions of ArrayScalar arguments are checked at runtime if HAVE_INTREPID2_DEBUG is defined.
A FEM basis spans a COMPLETE or INCOMPLETE polynomial space on the reference cell which is a smooth function space. Thus, all operator types that are meaningful for the approximated function space are admissible. When the order of the operator exceeds the degree of the basis, the output array is filled with the appropriate number of zeros.
Reimplemented from Intrepid2::Basis< Device, outputValueType, pointValueType >.
Definition at line 175 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
References Intrepid2::Basis< Device, outputValueType, pointValueType >::getBaseCellTopology(), Intrepid2::Basis< Device, outputValueType, pointValueType >::getCardinality(), and Intrepid2::getValues_HGRAD_Args().
getVandermondeInverse() [1/2]
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> Kokkos::DynRankView< typename ScalarViewType::const_value_type, DeviceType > Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getVandermondeInverse () const inline
Definition at line 256 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
getVandermondeInverse() [2/2]
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> void Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getVandermondeInverse (ScalarViewType vinv) const inline
Definition at line 250 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
getWorkSizePerPoint()
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> ordinal_type Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::getWorkSizePerPoint (const EOperator operatorType) const inline
Definition at line 261 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
Member Data Documentation
pointType_
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> EPointType Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::pointType_ private
Definition at line 164 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
vinv_
template<typename DeviceType = void, typename outputValueType = double, typename pointValueType = double> Kokkos::DynRankView<typename ScalarViewType::value_type,DeviceType> Intrepid2::Basis_HGRAD_LINE_Cn_FEM< DeviceType, outputValueType, pointValueType >::vinv_ private
inverse of Generalized Vandermonde matrix, whose columns store the expansion coefficients of the nodal basis in terms of phis_
Definition at line 163 of file Intrepid2_HGRAD_LINE_Cn_FEM.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_LINE_Cn_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_LINE_Cn_FEMDef.hpp