Intrepid2: Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator > Class Template Reference
Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator > Class Template Reference
Static Public Member Functions
template<class PolicyType , class ThisUnderlyingViewType , class AUnderlyingViewType , class BUnderlyingViewType , class ArgExtractorThis , class ArgExtractorA , class ArgExtractorB >
static void storeInPlaceCombination (PolicyType &policy, ThisUnderlyingViewType &this_underlying, AUnderlyingViewType &A_underlying, BUnderlyingViewType &B_underlying, BinaryOperator &binaryOperator, ArgExtractorThis argThis, ArgExtractorA argA, ArgExtractorB argB)
storeInPlaceCombination implementation for rank < 7, with compile-time underlying views and argument interpretation. Intended for internal and expert use.
template<int rank>
static enable_if_t< rank !=7, void > storeInPlaceCombination (Data< DataScalar, DeviceType > &thisData, const Data< DataScalar, DeviceType > &A, const Data< DataScalar, DeviceType > &B, BinaryOperator binaryOperator)
storeInPlaceCombination with compile-time rank – implementation for rank < 7.
template<int rank>
static enable_if_t< rank==7, void > storeInPlaceCombination (Data< DataScalar, DeviceType > &thisData, const Data< DataScalar, DeviceType > &A, const Data< DataScalar, DeviceType > &B, BinaryOperator binaryOperator)
storeInPlaceCombination with compile-time rank – implementation for rank of 7. (Not optimized; expectation is this case will be rarely used.)
static void storeInPlaceCombination (Data< DataScalar, DeviceType > &thisData, const Data< DataScalar, DeviceType > &A, const Data< DataScalar, DeviceType > &B, BinaryOperator binaryOperator)
Private Types
using reference_type = typename ScalarView< DataScalar, DeviceType >::reference_type
using const_reference_type = typename ScalarView< const DataScalar, DeviceType >::reference_type
Detailed Description
template<class DataScalar, typename DeviceType, class BinaryOperator>
class Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >
Definition at line 157 of file Intrepid2_DataCombiners.hpp.
Member Typedef Documentation
const_reference_type
template<class DataScalar , typename DeviceType , class BinaryOperator > using Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::const_reference_type = typename ScalarView<const DataScalar,DeviceType>::reference_type private
Definition at line 160 of file Intrepid2_DataCombiners.hpp.
reference_type
template<class DataScalar , typename DeviceType , class BinaryOperator > using Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::reference_type = typename ScalarView<DataScalar,DeviceType>::reference_type private
Definition at line 159 of file Intrepid2_DataCombiners.hpp.
Member Function Documentation
storeInPlaceCombination() [1/4]
template<class DataScalar , typename DeviceType , class BinaryOperator > template<int rank> static enable_if_t< rank !=7, void > Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::storeInPlaceCombination (Data< DataScalar, DeviceType > & thisData, const Data< DataScalar, DeviceType > & A, const Data< DataScalar, DeviceType > & B, BinaryOperator binaryOperator) inline static
storeInPlaceCombination with compile-time rank – implementation for rank < 7.
Definition at line 178 of file Intrepid2_DataCombiners.hpp.
References Intrepid2::GENERAL, Intrepid2::Data< DataScalar, DeviceType >::getUnderlyingViewRank(), Intrepid2::Data< DataScalar, DeviceType >::getUnderlyingViewSize(), Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::storeInPlaceCombination(), and Intrepid2::Data< DataScalar, DeviceType >::underlyingMatchesLogical().
storeInPlaceCombination() [2/4]
template<class DataScalar , typename DeviceType , class BinaryOperator > template<int rank> static enable_if_t< rank==7, void > Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::storeInPlaceCombination (Data< DataScalar, DeviceType > & thisData, const Data< DataScalar, DeviceType > & A, const Data< DataScalar, DeviceType > & B, BinaryOperator binaryOperator) inline static
storeInPlaceCombination with compile-time rank – implementation for rank of 7. (Not optimized; expectation is this case will be rarely used.)
Definition at line 499 of file Intrepid2_DataCombiners.hpp.
References Intrepid2::Data< DataScalar, DeviceType >::getDataExtent().
storeInPlaceCombination() [3/4]
template<class DataScalar , typename DeviceType , class BinaryOperator > static void Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::storeInPlaceCombination (Data< DataScalar, DeviceType > & thisData, const Data< DataScalar, DeviceType > & A, const Data< DataScalar, DeviceType > & B, BinaryOperator binaryOperator) inline static
Definition at line 515 of file Intrepid2_DataCombiners.hpp.
storeInPlaceCombination() [4/4]
template<class DataScalar , typename DeviceType , class BinaryOperator > template<class PolicyType , class ThisUnderlyingViewType , class AUnderlyingViewType , class BUnderlyingViewType , class ArgExtractorThis , class ArgExtractorA , class ArgExtractorB > static void Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::storeInPlaceCombination (PolicyType & policy, ThisUnderlyingViewType & this_underlying, AUnderlyingViewType & A_underlying, BUnderlyingViewType & B_underlying, BinaryOperator & binaryOperator, ArgExtractorThis argThis, ArgExtractorA argA, ArgExtractorB argB) inline static
storeInPlaceCombination implementation for rank < 7, with compile-time underlying views and argument interpretation. Intended for internal and expert use.
Definition at line 165 of file Intrepid2_DataCombiners.hpp.
Referenced by Intrepid2::DataCombiner< DataScalar, DeviceType, BinaryOperator >::storeInPlaceCombination().
The documentation for this class was generated from the following file:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Shared/Intrepid2_DataCombiners.hpp