Intrepid2: Intrepid2::Cubature< DeviceType, pointValueType, weightValueType > Class Template Reference
Intrepid2::Cubature< DeviceType, pointValueType, weightValueType > Class Template Reference
Defines the base class for cubature (integration) rules in Intrepid.
#include <Intrepid2_Cubature.hpp>
Public Types
using ExecSpaceType = typename DeviceType::execution_space
using PointViewType = Kokkos::DynRankView< pointValueType, Kokkos::LayoutStride, DeviceType >
using weightViewType = Kokkos::DynRankView< weightValueType, Kokkos::LayoutStride, DeviceType >
using PointViewTypeAllocatable = Kokkos::DynRankView< pointValueType, DeviceType >
using WeightViewTypeAllocatable = Kokkos::DynRankView< weightValueType, DeviceType >
using TensorPointDataType = TensorPoints< pointValueType, DeviceType >
using TensorWeightDataType = TensorData< weightValueType, DeviceType >
Public Member Functions
virtual TensorPointDataType allocateCubaturePoints () const
Returns a points container appropriate for passing to getCubature().
virtual TensorWeightDataType allocateCubatureWeights () const
Returns a weight container appropriate for passing to getCubature().
virtual void getCubature (PointViewType, weightViewType) const
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
virtual void getCubature (PointViewType, weightViewType, PointViewType) const
Returns cubature points and weights on physical cells (return arrays must be pre-sized/pre-allocated).
virtual void getCubature (const TensorPointDataType &tensorCubPoints, const TensorWeightDataType &tensorCubWeights) const
Returns tensor cubature points and weights. For non-tensor cubatures, the tensor structures are trivial, thin wrappers around the data returned by getCubature(). The provided containers should be pre-allocated through calls to allocateCubaturePoints() and allocateCubatureWeights().
virtual ordinal_type getNumPoints () const
Returns the number of cubature points.
virtual ordinal_type getDimension () const
Returns dimension of the integration domain.
virtual ordinal_type getAccuracy () const
Returns dimension of the integration domain.
virtual const char * getName () const
Returns cubature name.
Detailed Description
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double>
class Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >
Defines the base class for cubature (integration) rules in Intrepid.
Cubature template (rule) consists of cubature points and cubature weights. Intrepid provides a small collection of frequently used cubature rule templates for FEM reconstructions on simplices (edge, tri, tet) and the pyramid cell, defined in the derived classes of CubatureDirect.
For quad, hex, and triprism cells cubature templates are tensor products of CubatureDirect templates. The tensor-product cubatures are defined in the derived class CubatureTensor.
Definition at line 91 of file Intrepid2_Cubature.hpp.
Member Typedef Documentation
ExecSpaceType
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> using Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::ExecSpaceType = typename DeviceType::execution_space
Definition at line 93 of file Intrepid2_Cubature.hpp.
PointViewType
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> using Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::PointViewType = Kokkos::DynRankView<pointValueType,Kokkos::LayoutStride,DeviceType>
Definition at line 94 of file Intrepid2_Cubature.hpp.
PointViewTypeAllocatable
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> using Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::PointViewTypeAllocatable = Kokkos::DynRankView<pointValueType,DeviceType>
Definition at line 97 of file Intrepid2_Cubature.hpp.
TensorPointDataType
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> using Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::TensorPointDataType = TensorPoints<pointValueType,DeviceType>
Definition at line 99 of file Intrepid2_Cubature.hpp.
TensorWeightDataType
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> using Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::TensorWeightDataType = TensorData<weightValueType,DeviceType>
Definition at line 100 of file Intrepid2_Cubature.hpp.
weightViewType
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> using Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::weightViewType = Kokkos::DynRankView<weightValueType,Kokkos::LayoutStride,DeviceType>
Definition at line 95 of file Intrepid2_Cubature.hpp.
WeightViewTypeAllocatable
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> using Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::WeightViewTypeAllocatable = Kokkos::DynRankView<weightValueType,DeviceType>
Definition at line 98 of file Intrepid2_Cubature.hpp.
Constructor & Destructor Documentation
~Cubature()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::~Cubature () inline virtual
Definition at line 218 of file Intrepid2_Cubature.hpp.
Member Function Documentation
allocateCubaturePoints()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual TensorPointDataType Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::allocateCubaturePoints () const inline virtual
Returns a points container appropriate for passing to getCubature().
Returns
cubPoints - Data structure sized for the cubature points.
Reimplemented in Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureTensor< void, double, double >, and Intrepid2::CubatureTensorPyr< DeviceType, pointValueType, weightValueType >.
Definition at line 106 of file Intrepid2_Cubature.hpp.
References Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getDimension(), and Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getNumPoints().
allocateCubatureWeights()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual TensorWeightDataType Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::allocateCubatureWeights () const inline virtual
Returns a weight container appropriate for passing to getCubature().
Returns
cubWeights - Data structure sized for the cubature weights.
Reimplemented in Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureTensor< void, double, double >, and Intrepid2::CubatureTensorPyr< DeviceType, pointValueType, weightValueType >.
Definition at line 119 of file Intrepid2_Cubature.hpp.
References Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getNumPoints().
getAccuracy()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual ordinal_type Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getAccuracy () const inline virtual
Returns dimension of the integration domain.
Reimplemented in Intrepid2::CubatureDirect< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirect< void, double, double >, Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, and Intrepid2::CubatureTensor< void, double, double >.
Definition at line 203 of file Intrepid2_Cubature.hpp.
getCubature() [1/3]
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual void Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getCubature (const TensorPointDataType & tensorCubPoints, const TensorWeightDataType & tensorCubWeights) const inline virtual
Returns tensor cubature points and weights. For non-tensor cubatures, the tensor structures are trivial, thin wrappers around the data returned by getCubature(). The provided containers should be pre-allocated through calls to allocateCubaturePoints() and allocateCubatureWeights().
Parameters
cubPoints [out] - TensorPoints structure containing the cubature points.
cubWeights [out] - TensorData structure containing cubature weights.
Reimplemented in Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, and Intrepid2::CubatureTensorPyr< DeviceType, pointValueType, weightValueType >.
Definition at line 166 of file Intrepid2_Cubature.hpp.
References Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getCubature(), Intrepid2::TensorData< Scalar, DeviceType >::getTensorComponent(), Intrepid2::TensorPoints< PointScalar, DeviceType >::getTensorComponent(), Intrepid2::Data< DataScalar, DeviceType >::getUnderlyingView(), Intrepid2::TensorData< Scalar, DeviceType >::numTensorComponents(), and Intrepid2::TensorPoints< PointScalar, DeviceType >::numTensorComponents().
getCubature() [2/3]
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual void Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getCubature (PointViewType , weightViewType) const inline virtual
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
Reimplemented in Intrepid2::CubatureDirect< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, and Intrepid2::CubatureTensorPyr< DeviceType, pointValueType, weightValueType >.
Definition at line 137 of file Intrepid2_Cubature.hpp.
Referenced by Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getCubature().
getCubature() [3/3]
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual void Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getCubature (PointViewType , weightViewType , PointViewType) const inline virtual
Returns cubature points and weights on physical cells (return arrays must be pre-sized/pre-allocated).
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
cellVertices [in] - Array containing the cell vertices.
Reimplemented in Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureControlVolumeBoundary< DeviceType, pointValueType, weightValueType >, and Intrepid2::CubatureControlVolumeSide< DeviceType, pointValueType, weightValueType >.
Definition at line 152 of file Intrepid2_Cubature.hpp.
getDimension()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual ordinal_type Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getDimension () const inline virtual
Returns dimension of the integration domain.
Reimplemented in Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureControlVolumeBoundary< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureControlVolumeSide< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirect< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirect< void, double, double >, Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, and Intrepid2::CubatureTensor< void, double, double >.
Definition at line 193 of file Intrepid2_Cubature.hpp.
Referenced by Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::allocateCubaturePoints().
getName()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual const char * Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getName () const inline virtual
Returns cubature name.
Reimplemented in Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureControlVolumeBoundary< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureControlVolumeSide< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirect< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirect< void, double, double >, Intrepid2::CubatureDirectLineGauss< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirectLineGaussJacobi20< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirectTetDefault< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirectTetSymmetric< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirectTriDefault< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirectTriSymmetric< DeviceType, pointValueType, weightValueType >, Intrepid2::CubaturePolylib< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, and Intrepid2::CubatureTensor< void, double, double >.
Definition at line 213 of file Intrepid2_Cubature.hpp.
getNumPoints()
template<typename DeviceType = void, typename pointValueType = double, typename weightValueType = double> virtual ordinal_type Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::getNumPoints () const inline virtual
Returns the number of cubature points.
Reimplemented in Intrepid2::CubatureControlVolume< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureControlVolumeBoundary< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureControlVolumeSide< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirect< DeviceType, pointValueType, weightValueType >, Intrepid2::CubatureDirect< void, double, double >, Intrepid2::CubatureTensor< DeviceType, pointValueType, weightValueType >, and Intrepid2::CubatureTensor< void, double, double >.
Definition at line 182 of file Intrepid2_Cubature.hpp.
Referenced by Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::allocateCubaturePoints(), and Intrepid2::Cubature< DeviceType, pointValueType, weightValueType >::allocateCubatureWeights().
The documentation for this class was generated from the following file:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Integration/Intrepid2_Cubature.hpp