Intrepid2: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Shared/Intrepid2_DeviceAssert.hpp File Reference
Intrepid2_DeviceAssert.hpp File Reference
Implementation of an assert that can safely be called from device code.
#include <Kokkos_Core_fwd.hpp>
#include <impl/Kokkos_Error.hpp>
#include <cstdio>
#include <cassert>
Functions
KOKKOS_INLINE_FUNCTION void Intrepid2::device_assert (bool val)
Detailed Description
Implementation of an assert that can safely be called from device code.
Author
Created by N.V. Roberts.
Definition in file Intrepid2_DeviceAssert.hpp.
Function Documentation
device_assert()
KOKKOS_INLINE_FUNCTION void Intrepid2::device_assert (bool val)
KK: this assert header does not need to be separated from utils.hpp
Definition at line 31 of file Intrepid2_DeviceAssert.hpp.
References Intrepid2::device_assert().
Referenced by Intrepid2::device_assert(), Intrepid2::TensorViewIterator< TensorViewType, ViewType1, ViewType2, ScalarType >::increment(), and Intrepid2::TensorViewIterator< TensorViewType, ViewType1, ViewType2, ScalarType >::setLocation().