Intrepid2: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefValidateArguments.hpp File Reference
Intrepid2_CellToolsDefValidateArguments.hpp File Reference
Definition file for the validate arguments functions of the Intrepid2::CellTools class.
Functions
template<typename jacobianViewType , typename PointViewType , typename worksetCellViewType >
void Intrepid2::CellTools_setJacobianArgs (const jacobianViewType jacobian, const PointViewType points, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo, const int startCell, const int endCell)
template<typename jacobianInvViewType , typename jacobianViewType >
void Intrepid2::CellTools_setJacobianInvArgs (const jacobianInvViewType jacobianInv, const jacobianViewType jacobian)
Validates arguments to Intrepid2::CellTools::setJacobianInv.
template<typename jacobianDetViewType , typename jacobianViewType >
void Intrepid2::CellTools_setJacobianDetArgs (const jacobianDetViewType jacobianDet, const jacobianViewType jacobian)
Validates arguments to Intrepid2::CellTools::setJacobianDet.
template<typename physPointViewType , typename refPointViewType , typename worksetCellViewType >
void Intrepid2::CellTools_mapToPhysicalFrameArgs (const physPointViewType physPoints, const refPointViewType refPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::mapToPhysicalFrame.
template<typename refPointViewType , typename physPointViewType , typename worksetCellViewType >
void Intrepid2::CellTools_mapToReferenceFrameArgs (const refPointViewType refPoints, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::mapToReferenceFrame with default initial guess.
template<typename refPointViewType , typename initGuessViewType , typename physPointViewType , typename worksetCellViewType >
void Intrepid2::CellTools_mapToReferenceFrameInitGuessArgs (const refPointViewType refPoints, const initGuessViewType initGuess, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Detailed Description
Definition file for the validate arguments functions of the Intrepid2::CellTools class.
Author
Created by P. Bochev and D. Ridzal. Kokkorized by Kyungjoo Kim
Definition in file Intrepid2_CellToolsDefValidateArguments.hpp.
Function Documentation
CellTools_mapToPhysicalFrameArgs()
template<typename physPointViewType , typename refPointViewType , typename worksetCellViewType > void Intrepid2::CellTools_mapToPhysicalFrameArgs (const physPointViewType physPoints, const refPointViewType refPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::mapToPhysicalFrame.
Parameters
physPoints [in] - rank-3 (C,P,D) array array required
refPoints [in] - rank-3 (C,P,D) array or rank-2 (P,D) array required
cellWorkset [in] - rank-3 (C,N,D) array required
cellTopo [in] - cell topology with a reference cell required
Definition at line 190 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_mapToPhysicalFrameArgs().
Referenced by Intrepid2::CellTools_mapToPhysicalFrameArgs(), and Intrepid2::CellTools_setJacobianArgs().
CellTools_mapToReferenceFrameArgs()
template<typename refPointViewType , typename physPointViewType , typename worksetCellViewType > void Intrepid2::CellTools_mapToReferenceFrameArgs (const refPointViewType refPoints, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::mapToReferenceFrame with default initial guess.
Parameters
physPoints [in] - rank-3 (C,P,D) array required
refPoints [in] - rank-3 (C,P,D) array or rank-2 (P,D) array required
cellWorkset [in] - rank-3 (C,N,D) array required
cellTopo [in] - cell topology with a reference cell required
Definition at line 262 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_mapToReferenceFrameArgs().
Referenced by Intrepid2::CellTools_mapToReferenceFrameArgs(), Intrepid2::CellTools_setJacobianArgs(), and Intrepid2::CellTools< DeviceType >::mapToReferenceFrame().
CellTools_mapToReferenceFrameInitGuessArgs()
template<typename refPointViewType , typename initGuessViewType , typename physPointViewType , typename worksetCellViewType > void Intrepid2::CellTools_mapToReferenceFrameInitGuessArgs (const refPointViewType refPoints, const initGuessViewType initGuess, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Definition at line 299 of file Intrepid2_CellToolsDefValidateArguments.hpp.
CellTools_setJacobianArgs()
template<typename jacobianViewType , typename PointViewType , typename worksetCellViewType > void Intrepid2::CellTools_setJacobianArgs (const jacobianViewType jacobian, const PointViewType points, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo, const int startCell, const int endCell)
Definition at line 36 of file Intrepid2_CellToolsDefValidateArguments.hpp.
CellTools_setJacobianDetArgs()
template<typename jacobianDetViewType , typename jacobianViewType > void Intrepid2::CellTools_setJacobianDetArgs (const jacobianDetViewType jacobianDet, const jacobianViewType jacobian)
Validates arguments to Intrepid2::CellTools::setJacobianDet.
Parameters
jacobianDet [in] - rank = (jacobian rank - 2) required
jacobian [in] - rank-4 (C,P,D,D) array required
Definition at line 154 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_setJacobianDetArgs().
Referenced by Intrepid2::CellTools_setJacobianArgs(), Intrepid2::CellTools_setJacobianDetArgs(), and Intrepid2::CellTools< DeviceType >::setJacobianDet().
CellTools_setJacobianInvArgs()
template<typename jacobianInvViewType , typename jacobianViewType > void Intrepid2::CellTools_setJacobianInvArgs (const jacobianInvViewType jacobianInv, const jacobianViewType jacobian)
Validates arguments to Intrepid2::CellTools::setJacobianInv.
Parameters
jacobianInv [in] - rank and dimensions must match jacobian array
jacobian [in] - rank-4 (C,P,D,D) array required
Definition at line 122 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_setJacobianInvArgs().
Referenced by Intrepid2::CellTools_setJacobianArgs(), Intrepid2::CellTools_setJacobianInvArgs(), and Intrepid2::CellTools< DeviceType >::setJacobianInv().