Intrepid2: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasisFamily.hpp File Reference
Intrepid2_DerivedBasisFamily.hpp File Reference
Stateless class representing a family of basis functions, templated on H(vol) and H(grad) on the line. Only hypercube topologies are supported at the moment, but the intent is ultimately to support all standard topologies.
#include "Intrepid2_Basis.hpp"
#include "Intrepid2_DerivedBasis_HGRAD_QUAD.hpp"
#include "Intrepid2_DerivedBasis_HCURL_QUAD.hpp"
#include "Intrepid2_DerivedBasis_HDIV_QUAD.hpp"
#include "Intrepid2_DerivedBasis_HVOL_QUAD.hpp"
#include "Intrepid2_DerivedBasis_HGRAD_HEX.hpp"
#include "Intrepid2_DerivedBasis_HCURL_HEX.hpp"
#include "Intrepid2_DerivedBasis_HDIV_HEX.hpp"
#include "Intrepid2_DerivedBasis_HVOL_HEX.hpp"
#include "Intrepid2_DerivedBasis_HGRAD_WEDGE.hpp"
#include "Intrepid2_DerivedBasis_HCURL_WEDGE.hpp"
#include "Intrepid2_DerivedBasis_HDIV_WEDGE.hpp"
#include "Intrepid2_DerivedBasis_HVOL_WEDGE.hpp"
#include "Intrepid2_SerendipityBasis.hpp"
Classes
class Intrepid2::EmptyBasisFamily
EmptyBasisFamily allows us to set a default void family for a given topology.
class Intrepid2::DerivedBasisFamily< LineBasisHGRAD, LineBasisHVOL, TriangleBasisFamily, TetrahedronBasisFamily, PyramidBasisFamily >
A family of basis functions, constructed from H(vol) and H(grad) bases on the line.
Functions
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getLineBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for line bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getQuadrilateralBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic quadrilateral bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getQuadrilateralBasis (Intrepid2::EFunctionSpace fs, int polyOrder_x, int polyOrder_y, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for potentially anisotropic quadrilateral bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getHexahedronBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic bases on the hexahedron in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getHypercubeBasis_HGRAD (int polyOrder, int spaceDim, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic HGRAD bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getHypercubeBasis_HVOL (int polyOrder, int spaceDim, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic HVOL bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getHexahedronBasis (Intrepid2::EFunctionSpace fs, int polyOrder_x, int polyOrder_y, int polyOrder_z, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for potentially anisotropic hexahedron bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getSerendipityBasis_HGRAD (int polyOrder, int spaceDim)
Factory method for isotropic HGRAD Serendipity bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology. Note also that the family must use hierarchical bases.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getSerendipityBasis_HVOL (int polyOrder, int spaceDim)
Factory method for isotropic HGRAD Serendipity bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology. Note also that the family must use hierarchical bases.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getTetrahedronBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic tetrahedron bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getTriangleBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic triangle bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getWedgeBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic wedge bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getWedgeBasis (Intrepid2::EFunctionSpace fs, ordinal_type polyOrder_xy, ordinal_type polyOrder_z, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for anisotropic wedge bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getPyramidBasis (Intrepid2::EFunctionSpace fs, ordinal_type polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for pyramid bases in the given family.
template<class BasisFamily >
static BasisFamily::BasisPtr Intrepid2::getBasis (const shards::CellTopology &cellTopo, Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType=POINTTYPE_DEFAULT)
Factory method for isotropic bases in the given family on the specified cell topology.
Detailed Description
Stateless class representing a family of basis functions, templated on H(vol) and H(grad) on the line. Only hypercube topologies are supported at the moment, but the intent is ultimately to support all standard topologies.
Author
Created by N.V. Roberts.
Definition in file Intrepid2_DerivedBasisFamily.hpp.
Function Documentation
getBasis()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getBasis (const shards::CellTopology & cellTopo, Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic bases in the given family on the specified cell topology.
Parameters
[in] cellTopo - the cell topology on which the basis is defined.
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
At present, only hypercube topologies are supported. Once basis families support other element types, this method can be updated so that it also supports other element types.
Definition at line 396 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getBasis().
Referenced by Intrepid2::getBasis().
getHexahedronBasis() [1/2]
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getHexahedronBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic bases on the hexahedron in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 172 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getHexahedronBasis().
Referenced by Intrepid2::getHexahedronBasis(), and Intrepid2::getHexahedronBasis().
getHexahedronBasis() [2/2]
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getHexahedronBasis (Intrepid2::EFunctionSpace fs, int polyOrder_x, int polyOrder_y, int polyOrder_z, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for potentially anisotropic hexahedron bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder_x - the polynomial order of the basis in the x dimension.
[in] polyOrder_y - the polynomial order of the basis in the y dimension.
[in] polyOrder_z - the polynomial order of the basis in the z dimension.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 242 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getHexahedronBasis().
getHypercubeBasis_HGRAD()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getHypercubeBasis_HGRAD (int polyOrder, int spaceDim, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic HGRAD bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology.
Parameters
[in] polyOrder - the polynomial order of the basis.
[in] spaceDim - the number of dimensions for the hypercube on which the basis is defined.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 192 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getHypercubeBasis_HGRAD().
Referenced by Intrepid2::getHypercubeBasis_HGRAD().
getHypercubeBasis_HVOL()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getHypercubeBasis_HVOL (int polyOrder, int spaceDim, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic HVOL bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology.
Parameters
[in] polyOrder - the polynomial order of the basis.
[in] spaceDim - the number of dimensions for the hypercube on which the basis is defined.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 216 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getHypercubeBasis_HVOL().
Referenced by Intrepid2::getHypercubeBasis_HVOL().
getLineBasis()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getLineBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for line bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 113 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getLineBasis().
Referenced by Intrepid2::getLineBasis().
getPyramidBasis()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getPyramidBasis (Intrepid2::EFunctionSpace fs, ordinal_type polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for pyramid bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 372 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getPyramidBasis().
Referenced by Intrepid2::getPyramidBasis().
getQuadrilateralBasis() [1/2]
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getQuadrilateralBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic quadrilateral bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 131 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getQuadrilateralBasis().
Referenced by Intrepid2::getQuadrilateralBasis(), and Intrepid2::getQuadrilateralBasis().
getQuadrilateralBasis() [2/2]
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getQuadrilateralBasis (Intrepid2::EFunctionSpace fs, int polyOrder_x, int polyOrder_y, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for potentially anisotropic quadrilateral bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder_x - the polynomial order of the basis in the x dimension.
[in] polyOrder_y - the polynomial order of the basis in the y dimension.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 152 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getQuadrilateralBasis().
getSerendipityBasis_HGRAD()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getSerendipityBasis_HGRAD (int polyOrder, int spaceDim) static
Factory method for isotropic HGRAD Serendipity bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology. Note also that the family must use hierarchical bases.
Parameters
[in] polyOrder - the polynomial order of the basis.
[in] spaceDim - the number of dimensions for the hypercube on which the basis is defined.
Definition at line 261 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getSerendipityBasis_HGRAD().
Referenced by Intrepid2::getSerendipityBasis_HGRAD().
getSerendipityBasis_HVOL()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getSerendipityBasis_HVOL (int polyOrder, int spaceDim) static
Factory method for isotropic HGRAD Serendipity bases on a hypercube for the given family. Note that this will return a Line<2> for its base cell topology. Note also that the family must use hierarchical bases.
Parameters
[in] polyOrder - the polynomial order of the basis.
[in] spaceDim - the number of dimensions for the hypercube on which the basis is defined.
Definition at line 276 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getSerendipityBasis_HVOL().
Referenced by Intrepid2::getSerendipityBasis_HVOL().
getTetrahedronBasis()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getTetrahedronBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic tetrahedron bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 292 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getTetrahedronBasis().
Referenced by Intrepid2::getTetrahedronBasis().
getTriangleBasis()
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getTriangleBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic triangle bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 312 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getTriangleBasis().
Referenced by Intrepid2::getTriangleBasis().
getWedgeBasis() [1/2]
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getWedgeBasis (Intrepid2::EFunctionSpace fs, int polyOrder, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for isotropic wedge bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 332 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getWedgeBasis().
Referenced by Intrepid2::getWedgeBasis(), and Intrepid2::getWedgeBasis().
getWedgeBasis() [2/2]
template<class BasisFamily > static BasisFamily::BasisPtr Intrepid2::getWedgeBasis (Intrepid2::EFunctionSpace fs, ordinal_type polyOrder_xy, ordinal_type polyOrder_z, const EPointType pointType = POINTTYPE_DEFAULT) static
Factory method for anisotropic wedge bases in the given family.
Parameters
[in] fs - the function space for the basis.
[in] polyOrder - the polynomial order of the basis.
[in] pointType - type of lattice used for creating the DoF coordinates.
Definition at line 352 of file Intrepid2_DerivedBasisFamily.hpp.
References Intrepid2::getWedgeBasis().