Intrepid2: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid2/src/Cell/Intrepid2_CellTools.hpp File Reference
Intrepid2_CellTools.hpp File Reference
Header file for the Intrepid2::CellTools class.
#include "Intrepid2_ConfigDefs.hpp"
#include "Shards_CellTopology.hpp"
#include "Shards_BasicTopologies.hpp"
#include "Teuchos_RCP.hpp"
#include "Intrepid2_Types.hpp"
#include "Intrepid2_Utils.hpp"
#include "Intrepid2_RealSpaceTools.hpp"
#include "Intrepid2_Basis.hpp"
#include "Intrepid2_HGRAD_LINE_C1_FEM.hpp"
#include "Intrepid2_HGRAD_LINE_C2_FEM.hpp"
#include "Intrepid2_HGRAD_TRI_C1_FEM.hpp"
#include "Intrepid2_HGRAD_TRI_C2_FEM.hpp"
#include "Intrepid2_HGRAD_QUAD_C1_FEM.hpp"
#include "Intrepid2_HGRAD_QUAD_C2_FEM.hpp"
#include "Intrepid2_HGRAD_TET_C1_FEM.hpp"
#include "Intrepid2_HGRAD_TET_C2_FEM.hpp"
#include "Intrepid2_HGRAD_TET_COMP12_FEM.hpp"
#include "Intrepid2_HGRAD_HEX_C1_FEM.hpp"
#include "Intrepid2_HGRAD_HEX_C2_FEM.hpp"
#include "Intrepid2_HGRAD_WEDGE_C1_FEM.hpp"
#include "Intrepid2_HGRAD_WEDGE_C2_FEM.hpp"
#include "Intrepid2_HGRAD_PYR_C1_FEM.hpp"
#include "Intrepid2_HGRAD_PYR_I2_FEM.hpp"
#include "Intrepid2_Data.hpp"
#include "Intrepid2_CellData.hpp"
#include "Intrepid2_CellToolsDocumentation.hpp"
#include "Intrepid2_CellToolsDefValidateArguments.hpp"
#include "Intrepid2_CellToolsDefNodeInfo.hpp"
#include "Intrepid2_CellToolsDefJacobian.hpp"
#include "Intrepid2_CellToolsDefRefToPhys.hpp"
#include "Intrepid2_CellToolsDefPhysToRef.hpp"
#include "Intrepid2_CellToolsDefControlVolume.hpp"
#include "Intrepid2_CellToolsDefInclusion.hpp"
Classes
class Intrepid2::CellTools< DeviceType >
A stateless class for operations on cell data. Provides methods for:
Functions
template<typename jacobianViewType , typename PointViewType , typename worksetCellViewType >
static void Intrepid2::CellTools_setJacobianArgs (const jacobianViewType jacobian, const PointViewType points, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::setJacobian.
template<typename jacobianInvViewType , typename jacobianViewType >
static void Intrepid2::CellTools_setJacobianInvArgs (const jacobianInvViewType jacobianInv, const jacobianViewType jacobian)
Validates arguments to Intrepid2::CellTools::setJacobianInv.
template<typename jacobianDetViewType , typename jacobianViewType >
static void Intrepid2::CellTools_setJacobianDetArgs (const jacobianDetViewType jacobianDet, const jacobianViewType jacobian)
Validates arguments to Intrepid2::CellTools::setJacobianDet.
template<typename physPointViewType , typename refPointViewType , typename worksetCellViewType >
static void Intrepid2::CellTools_mapToPhysicalFrameArgs (const physPointViewType physPoints, const refPointViewType refPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::mapToPhysicalFrame.
template<typename refPointViewType , typename physPointViewType , typename worksetCellViewType >
static void Intrepid2::CellTools_mapToReferenceFrameArgs (const refPointViewType refPoints, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::mapToReferenceFrame with default initial guess.
template<typename refPointViewType , typename initGuessViewType , typename physPointViewType , typename worksetCellViewType >
static void Intrepid2::CellTools_mapToReferenceFrameInitGuess (const refPointViewType refPoints, const initGuessViewType initGuess, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo)
Validates arguments to Intrepid2::CellTools::mapToReferenceFrame with user-defined initial guess.
Detailed Description
Header file for the Intrepid2::CellTools class.
Author
Created by P. Bochev and D. Ridzal. Kokkorized by Kyungjoo Kim
Definition in file Intrepid2_CellTools.hpp.
Function Documentation
CellTools_mapToPhysicalFrameArgs()
template<typename physPointViewType , typename refPointViewType , typename worksetCellViewType > static void Intrepid2::CellTools_mapToPhysicalFrameArgs (const physPointViewType physPoints, const refPointViewType refPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo) static
Validates arguments to Intrepid2::CellTools::mapToPhysicalFrame.
Parameters
physPoints [in] - rank-3 (C,P,D) array array required
refPoints [in] - rank-3 (C,P,D) array or rank-2 (P,D) array required
cellWorkset [in] - rank-3 (C,N,D) array required
cellTopo [in] - cell topology with a reference cell required
Definition at line 190 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_mapToPhysicalFrameArgs().
Referenced by Intrepid2::CellTools_mapToPhysicalFrameArgs(), and Intrepid2::CellTools_setJacobianArgs().
CellTools_mapToReferenceFrameArgs()
template<typename refPointViewType , typename physPointViewType , typename worksetCellViewType > static void Intrepid2::CellTools_mapToReferenceFrameArgs (const refPointViewType refPoints, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo) static
Validates arguments to Intrepid2::CellTools::mapToReferenceFrame with default initial guess.
Parameters
physPoints [in] - rank-3 (C,P,D) array required
refPoints [in] - rank-3 (C,P,D) array or rank-2 (P,D) array required
cellWorkset [in] - rank-3 (C,N,D) array required
cellTopo [in] - cell topology with a reference cell required
Definition at line 262 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_mapToReferenceFrameArgs().
Referenced by Intrepid2::CellTools_mapToReferenceFrameArgs(), Intrepid2::CellTools_setJacobianArgs(), and Intrepid2::CellTools< DeviceType >::mapToReferenceFrame().
CellTools_mapToReferenceFrameInitGuess()
template<typename refPointViewType , typename initGuessViewType , typename physPointViewType , typename worksetCellViewType > static void Intrepid2::CellTools_mapToReferenceFrameInitGuess (const refPointViewType refPoints, const initGuessViewType initGuess, const physPointViewType physPoints, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo) static
Validates arguments to Intrepid2::CellTools::mapToReferenceFrame with user-defined initial guess.
Parameters
physPoints [in] - rank-3 (C,P,D) array required
initGuess [in] - rank and dimensions must match those of physPoints
refPoints [in] - rank-3 (C,P,D) array required
cellWorkset [in] - rank-3 (C,N,D) array required
cellTopo [in] - cell topology with a reference cell required
References Intrepid2::CellTools_mapToReferenceFrameInitGuess().
Referenced by Intrepid2::CellTools_mapToReferenceFrameInitGuess().
CellTools_setJacobianArgs()
template<typename jacobianViewType , typename PointViewType , typename worksetCellViewType > static void Intrepid2::CellTools_setJacobianArgs (const jacobianViewType jacobian, const PointViewType points, const worksetCellViewType worksetCell, const shards::CellTopology cellTopo) static
Validates arguments to Intrepid2::CellTools::setJacobian.
Parameters
jacobian [in] - rank-4 (C,P,D,D) array array required
points [in] - rank-2 (P,D) or rank-3 (C,P,D) array required
cellWorkset [in] - rank-3 (C,N,D) array required
cellTopo [in] - cell topology with a reference cell required
References Intrepid2::CellTools_mapToPhysicalFrameArgs(), Intrepid2::CellTools_mapToReferenceFrameArgs(), Intrepid2::CellTools_setJacobianArgs(), Intrepid2::CellTools_setJacobianDetArgs(), and Intrepid2::CellTools_setJacobianInvArgs().
Referenced by Intrepid2::CellTools_setJacobianArgs().
CellTools_setJacobianDetArgs()
template<typename jacobianDetViewType , typename jacobianViewType > static void Intrepid2::CellTools_setJacobianDetArgs (const jacobianDetViewType jacobianDet, const jacobianViewType jacobian) static
Validates arguments to Intrepid2::CellTools::setJacobianDet.
Parameters
jacobianDet [in] - rank = (jacobian rank - 2) required
jacobian [in] - rank-4 (C,P,D,D) array required
Definition at line 154 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_setJacobianDetArgs().
Referenced by Intrepid2::CellTools_setJacobianArgs(), Intrepid2::CellTools_setJacobianDetArgs(), and Intrepid2::CellTools< DeviceType >::setJacobianDet().
CellTools_setJacobianInvArgs()
template<typename jacobianInvViewType , typename jacobianViewType > static void Intrepid2::CellTools_setJacobianInvArgs (const jacobianInvViewType jacobianInv, const jacobianViewType jacobian) static
Validates arguments to Intrepid2::CellTools::setJacobianInv.
Parameters
jacobianInv [in] - rank and dimensions must match jacobian array
jacobian [in] - rank-4 (C,P,D,D) array required
Definition at line 122 of file Intrepid2_CellToolsDefValidateArguments.hpp.
References Intrepid2::CellTools_setJacobianInvArgs().
Referenced by Intrepid2::CellTools_setJacobianArgs(), Intrepid2::CellTools_setJacobianInvArgs(), and Intrepid2::CellTools< DeviceType >::setJacobianInv().