Amesos2 - Direct Sparse Solver Interfaces: Amesos2::SolverCore< ConcreteSolver, Matrix, Vector > Class Template Reference
Amesos2::SolverCore< ConcreteSolver, Matrix, Vector > Class Template Reference
Amesos2 Solvers » Amesos2 Solver Framework
Amesos2::SolverCore: A templated interface for interaction with third-party direct sparse solvers.
#include <Amesos2_SolverCore_decl.hpp>
Public Types
typedef SolverCore< ConcreteSolver, Matrix, Vector > type
typedef Solver< Matrix, Vector > super_type
typedef ConcreteSolver< Matrix, Vector > solver_type
typedef Matrix matrix_type
typedef Vector vector_type
typedef MatrixAdapter< matrix_type >::scalar_t scalar_type
typedef MatrixAdapter< matrix_type >::local_ordinal_t local_ordinal_type
typedef MatrixAdapter< matrix_type >::global_ordinal_t global_ordinal_type
typedef MatrixAdapter< matrix_type >::global_size_t global_size_type
typedef MatrixAdapter< matrix_type >::node_t node_type
Public Member Functions
Constructor/Destructor methods
SolverCore (Teuchos::RCP< const Matrix > A, Teuchos::RCP< Vector > X, Teuchos::RCP< const Vector > B)
Initialize a Solver instance.
~SolverCore ()
Destructor.
SolverCore (const solver_type &rhs)
Do not allow copying of this Solver object.
super_type & operator= (const solver_type *rhs)
Do not allow copying of this Solver by assignment.
Mathematical functions
super_type & preOrdering () override
Pre-orders the matrix A for minimal fill-in.
super_type & symbolicFactorization () override
Performs symbolic factorization on the matrix A.
super_type & numericFactorization () override
Performs numeric factorization on the matrix A.
void solve () override
Solves (or)
void solve (const Teuchos::Ptr< Vector > X, const Teuchos::Ptr< const Vector > B) const override
Solve using the given X and B vectors.
void solve (Vector *X, const Vector *B) const override
Solve using the given X and B vectors.
int solve_ir (const Teuchos::Ptr< Vector > X, const Teuchos::Ptr< const Vector > B, const int maxNumIters, const bool verbose) const
int solve_ir (Vector *X, const Vector *B, const int maxNumIters, const bool verbose) const
int solve_ir (const int maxNumIters, const bool verbose)
bool matrixShapeOK () override
Returns true if the solver can handle this matrix shape.
void setA (const Teuchos::RCP< const Matrix > a, EPhase keep_phase=CLEAN) override
Sets the matrix A of this solver.
void setA (const Matrix *a, EPhase keep_phase=CLEAN) override
Sets the matrix A of this solver.
void setX (const Teuchos::RCP< Vector > x) override
Sets the LHS vector X.
void setX (Vector *x) override
Sets the LHS vector X using a raw pointer.
const Teuchos::RCP< Vector > getX () override
Returns the vector that is the LHS of the linear system.
Vector * getXRaw () override
Returns a raw pointer to the LHS of the linear system.
void setB (const Teuchos::RCP< const Vector > b) override
Sets the RHS vector B.
void setB (const Vector *b) override
Sets the RHS vector B using a raw pointer.
const Teuchos::RCP< const Vector > getB () override
Returns the vector that is the RHS of the linear system.
const Vector * getBRaw () override
Returns a raw pointer to the RHS of the linear system.
Parameter methods
super_type & setParameters (const Teuchos::RCP< Teuchos::ParameterList > &parameterList) override
Set/update internal variables and solver options.
Teuchos::RCP< const Teuchos::ParameterList > getValidParameters () const override
Return a const parameter list of all of the valid parameters that this->setParameterList(...) will accept.
void setParameterList (const Teuchos::RCP< Teuchos::ParameterList > &parameterList)
Set or update internal variables and solver options.
Teuchos::RCP< Teuchos::ParameterList > getNonconstParameterList ()
This is a empty stub.
Teuchos::RCP< Teuchos::ParameterList > unsetParameterList ()
This is an empty stub.
Accessor methods
typedef Tpetra::Map< local_ordinal_type, global_ordinal_type, node_type > map_type
Contiguous GID map for reindex.
typedef Kokkos::DefaultHostExecutionSpace HostExecSpaceType
Communication pattern for gather.
typedef Kokkos::View< local_ordinal_type *, HostExecSpaceType > host_ordinal_type_array
typedef Kokkos::View< scalar_type *, HostExecSpaceType > host_scalar_type_array
Teuchos::RCP< const MatrixAdapter< Matrix > > matrixA_
The LHS operator.
bool matrix_loaded_
Teuchos::RCP< Vector > multiVecX_
The LHS vector/multi-vector.
Teuchos::RCP< const Vector > multiVecB_
The RHS vector/multi-vector.
global_size_type globalNumRows_
Number of global rows in matrixA_.
global_size_type globalNumCols_
Number of global columns in matrixA_.
global_size_type globalNumNonZeros_
Number of global non-zero values in matrixA_.
global_size_type rowIndexBase_
Index base of rowmap of matrixA_.
global_size_type columnIndexBase_
Index base of column map of matrixA_.
Status status_
Holds status information about a solver.
Control control_
Parameters for solving.
Timers timers_
Various timing statistics.
int rank_
The MPI rank of this image.
bool root_
If true, then this is the root processor.
int nprocs_
Number of process images in the matrix communicator.
Teuchos::RCP< const map_type > contig_rowmap_
Teuchos::RCP< const map_type > contig_colmap_
host_ordinal_type_array perm_g2l
host_ordinal_type_array recvCountRows
host_ordinal_type_array recvDisplRows
host_ordinal_type_array recvCounts
host_ordinal_type_array recvDispls
host_ordinal_type_array transpose_map
host_scalar_type_array nzvals_t
Teuchos::RCP< const Teuchos::Comm< int > > getComm () const override
Returns a pointer to the Teuchos::Comm communicator with this operator.
Status & getStatus () const override
Returns a reference to this solver's internal status object.
std::string description () const override
Returns a short description of this Solver.
void describe (Teuchos::FancyOStream &out, const Teuchos::EVerbosityLevel verbLevel=Teuchos::Describable::verbLevel_default) const override
void printTiming (Teuchos::FancyOStream &out, const Teuchos::EVerbosityLevel verbLevel) const override
Prints timing information about the current solver.
void getTiming (Teuchos::ParameterList &timingParameterList) const override
Extracts timing information from the current solver.
std::string name () const override
Return the name of this solver.
void loadA (EPhase current_phase)
Refresh this solver's internal data about A.
void setNnzLU (size_t nnz)
Set the number of non-zero values in the and factors.
Detailed Description
template<template< class, class > class ConcreteSolver, class Matrix, class Vector>
class Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >
Amesos2::SolverCore: A templated interface for interaction with third-party direct sparse solvers.
Templated core-functionality class for Amesos2 solvers. Definitions.
The Amesos2::SolverCore class is the statically polymorphic parent class of each Amesos2 class named Amesos2_SolverName which interfaces with the third-party solver named SolverName.
Each concrete solver interface implements several private "sub-functions" that are called within common code for that function.
This static base class also provides a convenient way to handle the template parameters and private typedef'ing (with the help of the Matrix and MultiVector adapter classes) of the ordinal and scalar types that can be used elsewhere in the concrete solver code.
Author
Eric T Bavier etbav.nosp@m.ie@s.nosp@m.andia.nosp@m..gov
Date
Thu May 27 14:02:35 CDT 2010
Constructor & Destructor Documentation
SolverCore()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::SolverCore (Teuchos::RCP< const Matrix > A, Teuchos::RCP< Vector > X, Teuchos::RCP< const Vector > B)
Initialize a Solver instance.
A single constructor is supported, which accepts Teuchos::RCP objects that point to a matrix-esque \x A, and vector-esque LHS object \X and RHS object \x B. This is the only constructor used by Amesos2::create.
Exceptions
std::invalid_argument The shape of the matrix A is not supported by the underlying solver.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::matrixShapeOK().
Member Function Documentation
preOrdering()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Solver< Matrix, Vector > & Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::preOrdering (void) override virtual
Pre-orders the matrix A for minimal fill-in.
Rearranges the rows and columns of the matrix A to minimize the amount of fill-in of the non-zero entries of the matrix. Pre-ordering may or may not be supported by the underlying solver. If not supported, a call to this method simply does nothing.
Returns
a reference to this .
See also
symbolicFactorization(), numericFactorization(), and solve()
Implements Amesos2::Solver< Matrix, Vector >.
symbolicFactorization()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Solver< Matrix, Vector > & Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::symbolicFactorization (void) override virtual
Performs symbolic factorization on the matrix A.
In addition to performing symbolic factorization on the matrix A, the call to symbolicFactorization() implies that no change will be made to the non-zero structure of the underlying matrix without a subsequent call to symbolicFactorization().
Precondition
Postcondition
Symbolic factorization will be performed (or marked to be performed) allowing numericFactorization() and solve() to be called.
Returns
a reference to this .
See also
preOrdering(), numericFactorization(), and solve()
Implements Amesos2::Solver< Matrix, Vector >.
numericFactorization()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Solver< Matrix, Vector > & Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::numericFactorization (void) override virtual
Performs numeric factorization on the matrix A.
In addition to performing numeric factorization on the matrix A, the call to numericFactorization() implies that no change will be made to the underlying matrix values without a subsequent call to numericFactorization().
Precondition
The non-zero structure of the matrix should not have changed since the last call to symbolicFactorization(). Other changes can have arbitrary consequences.
The distribution of the matrix should not have changed since the last call to symbolicFactorization().
Postcondition
Numeric factorization will be performed (or marked to be performed) allowing solve() to be performed correctly despite a potential change in the matrix values (though not in the non-zero structure).
Returns
a reference to this
See also
preOrdering(), symbolicFactorization(), and solve()
Implements Amesos2::Solver< Matrix, Vector >.
solve() [1/3]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::solve (void) override virtual
Solves (or)
Precondition
The non-zero structure of the matrix should not have changed since the last call to symbolicFactorization().
The distribution of the matrix should not have changed since the last call to symbolicFactorization().
The matrix should not have changed since the last call to numericFactorization().
Postcondition
X will be set such that (or), within the limits of the accuracy of the underlying solver.
Returns
void
See also
preOrdering(), symbolicFactorization(), and numericFactorization()
Implements Amesos2::Solver< Matrix, Vector >.
solve() [2/3]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::solve (const Teuchos::Ptr< Vector > X, const Teuchos::Ptr< const Vector > B) const override virtual
Solve using the given X and B vectors.
This overload of solve uses the given X and B vectors when solving. This X and B are used in place of any X and B that were given upon construction of the Amesos2 solver instance and are used only for this solve.
If a permanent change of X and B are required, see the setX() and setB() methods.
Postcondition
The (multi)vector X contains the solution to the system
The X and B given at construction time (if any) are unchanged.
Implements Amesos2::Solver< Matrix, Vector >.
solve() [3/3]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::solve (Vector * X, const Vector * B) const override virtual
Solve using the given X and B vectors.
This overload of solve uses the given X and B vectors when solving. This X and B are used in place of any X and B that were given upon construction of the Amesos2 solver instance and are used only for this solve.
If a permanent change of X and B are required, see the setX() and setB() methods.
Postcondition
The (multi)vector X contains the solution to the system
The X and B given at construction time (if any) are unchanged.
Implements Amesos2::Solver< Matrix, Vector >.
matrixShapeOK()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > bool Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::matrixShapeOK (void) override virtual
Returns true if the solver can handle this matrix shape.
Returns true if the matrix shape is one that the underlying concrete sparse direct solver can handle. Classes that work only on square matrices should return false for rectangular matrices. Classes that work only on symmetric matrices would return false for non-symmetric matrices. etc.
Implements Amesos2::Solver< Matrix, Vector >.
Referenced by Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::SolverCore().
setA() [1/2]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setA (const Teuchos::RCP< const Matrix > a, EPhase keep_phase = CLEAN) override virtual
Sets the matrix A of this solver.
Parameters
[in] a An RCP to a matrix will will be used for future computation steps
[in] keep_phase This parameter tells the solver what state it should keep. For example, you may want to replace the matrix but keep the symbolic factorization because you know the structure of the new matrix is the same as the structure of the old matrix. In this case you would pass Amesos2::SYMBFACT as this parameter.
The default value for the second parameter is Amesos2::CLEAN, which means that the internal state of the solver will be completely reset. It will be as if no previous computational steps were performed.
Implements Amesos2::Solver< Matrix, Vector >.
setA() [2/2]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setA (const Matrix * a, EPhase keep_phase = CLEAN) inline override virtual
Sets the matrix A of this solver.
Parameters
[in] a An raw C pointer to a matrix will will be used for future computation steps.
[in] keep_phase This parameter tells the solver what state it should keep. For example, you may want to replace the matrix but keep the symbolic factorization because you know the structure of the new matrix is the same as the structure of the old matrix. In this case you would pass Amesos2::SYMBFACT as this parameter.
The default value for the second parameter is Amesos2::CLEAN, which means that the internal state of the solver will be completely reset. It will be as if no previous computational steps were performed.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setA().
Referenced by Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setA().
setX() [1/2]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setX (const Teuchos::RCP< Vector > x) inline override virtual
Sets the LHS vector X.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecX_.
setX() [2/2]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setX (Vector * x) inline override virtual
Sets the LHS vector X using a raw pointer.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecX_.
getX()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > const Teuchos::RCP< Vector > Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getX () inline override virtual
Returns the vector that is the LHS of the linear system.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecX_.
getXRaw()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Vector * Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getXRaw () inline override virtual
Returns a raw pointer to the LHS of the linear system.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecX_.
setB() [1/2]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setB (const Teuchos::RCP< const Vector > b) inline override virtual
Sets the RHS vector B.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecB_.
setB() [2/2]
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setB (const Vector * b) inline override virtual
Sets the RHS vector B using a raw pointer.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecB_.
getB()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > const Teuchos::RCP< const Vector > Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getB () inline override virtual
Returns the vector that is the RHS of the linear system.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecB_.
getBRaw()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > const Vector * Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getBRaw () inline override virtual
Returns a raw pointer to the RHS of the linear system.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecB_.
setParameters()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Solver< Matrix, Vector > & Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setParameters (const Teuchos::RCP< Teuchos::ParameterList > & parameterList) override virtual
Set/update internal variables and solver options.
The setParameters method is consistent over all concrete solvers. It accepts general status and control parameters, as well as parameters specific to a given solver. If the solver does not recognize the parameter, then it will simply be ignored
Note
The ParameterList must be named "Amesos2". A list with any other name will be ignored.
Postcondition
Internal variables controlling the factorization and solve will be updated and take effect on all subsequent calls to numericFactorization() and solve().
All parameters whose value is to differ from the default values must be included in parameterList. Parameters not specified in parameterList revert to their default values.
Returns
a reference to this
Implements Amesos2::Solver< Matrix, Vector >.
Referenced by Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setParameterList().
getValidParameters()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Teuchos::RCP< const Teuchos::ParameterList > Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getValidParameters (void) const override virtual
Return a const parameter list of all of the valid parameters that this->setParameterList(...) will accept.
Note
Check the documentation for your concrete solver to see a complete list of the values that each parameter may take. A solver may also recognize multiple data types as arguments for a particular parameters (eg. recognizing "YES" and "NO" as well as true and false).
Implements Amesos2::Solver< Matrix, Vector >.
setParameterList()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setParameterList (const Teuchos::RCP< Teuchos::ParameterList > & parameterList) inline
Set or update internal variables and solver options.
Redefined from Teuchos::ParameterListAcceptor
Note
Alias for setParameters()
Parameters
[in] parameterList
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setParameters().
getNonconstParameterList()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Teuchos::RCP< Teuchos::ParameterList > Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getNonconstParameterList () inline
This is a empty stub.
Returns
unsetParameterList()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Teuchos::RCP< Teuchos::ParameterList > Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::unsetParameterList () inline
This is an empty stub.
Returns
getComm()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Teuchos::RCP< const Teuchos::Comm< int > > Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getComm (void) const inline override virtual
Returns a pointer to the Teuchos::Comm communicator with this operator.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::matrixA_.
Referenced by Amesos2::CssMKL< Matrix, Vector >::CssMKL().
getStatus()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Status & Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getStatus () const inline override virtual
Returns a reference to this solver's internal status object.
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::status_.
description()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > std::string Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::description (void) const override virtual
Returns a short description of this Solver.
Implements Amesos2::Solver< Matrix, Vector >.
Reimplemented in Amesos2::Umfpack< Matrix, Vector >, Amesos2::Superlu< Matrix, Vector >, and Amesos2::TachoSolver< Matrix, Vector >.
describe()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::describe (Teuchos::FancyOStream & out, const Teuchos::EVerbosityLevel verbLevel = Teuchos::Describable::verbLevel_default) const override virtual
Prints the status information about the current solver with some level of verbosity
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::Util::printLine().
printTiming()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::printTiming (Teuchos::FancyOStream & out, const Teuchos::EVerbosityLevel verbLevel) const override virtual
Prints timing information about the current solver.
The Amesos2::SolverCore base class takes care of tracking total time spent in the Amesos2 interface. Concrete solver interface class are responsible for reporting other timing statistics, which include time spent in:
Redistribution of matrix objects,
Conversion of matrix objects to solver-specific formats,
Redistribution of multi-vector objects,
Conversion of multi-vector objects to solver formats,
TPL symbolic factorizations,
TPL numeric factorizations, and
TPL solves
Implements Amesos2::Solver< Matrix, Vector >.
References Amesos2::Util::printLine().
getTiming()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getTiming (Teuchos::ParameterList & timingParameterList) const override virtual
Extracts timing information from the current solver.
Results are placed into the parameter list timingParameterList.
Parameters
[out] timingParameterList Accepts timing information from the current solver
Implements Amesos2::Solver< Matrix, Vector >.
name()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > std::string Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::name (void) const override virtual
Return the name of this solver.
The name is given by the underlying concrete solver instance
Returns
A std::string which is the name of this solver
Implements Amesos2::Solver< Matrix, Vector >.
loadA()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::loadA (EPhase current_phase) private
Refresh this solver's internal data about A.
Called whenever it would be necessary to refresh a solver's internal storage of the matrix A, which is whenever a phase is called that is equal to or below the current call.
For example, say a user has just previously called solve(), then calls numericFactorization(). Since the solve phase is greater than the numericFactorization phase, this is an indication that the internal store of A needs refreshing, since the user (assuming the user know what she's doing) wouldn't otherwise need to call numericFactorization following a solve.
setNnzLU()
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > void Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setNnzLU (size_t nnz) inline protected
Set the number of non-zero values in the and factors.
Concrete solver classes may call this method if they wish to (or are able to) report the number of conbined non-zero count for the and factors.
References Amesos2::Status::lu_nnz_, and Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::status_.
Member Data Documentation
matrix_loaded_
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > bool Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::matrix_loaded_ protected
If true indicates that the current matrix A has been loaded into internal solver structures.
multiVecB_
template<template< class, class > class ConcreteSolver, class Matrix , class Vector > Teuchos::RCP<const Vector> Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::multiVecB_ protected
The RHS vector/multi-vector.
We point to a const Vector because Amesos2 should never directly modify B.
Referenced by Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getB(), Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::getBRaw(), Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setB(), and Amesos2::SolverCore< ConcreteSolver, Matrix, Vector >::setB().
The documentation for this class was generated from the following files:
Amesos2_SolverCore_decl.hpp
Amesos2_SolverCore_def.hpp