ROL: example_02.cpp File Reference
example_02.cpp File Reference
Shows how to solve a steady Burgers' optimal control problem using the SimOpt interface. We solve the control problem using Composite Step and trust regions.
#include "ROL_TypeU_TrustRegionAlgorithm.hpp"
#include "ROL_TypeE_CompositeStepAlgorithm.hpp"
#include "ROL_Reduced_Objective_SimOpt.hpp"
#include "ROL_Stream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "Teuchos_LAPACK.hpp"
#include <iostream>
#include <algorithm>
#include "example_02.hpp"
Typedefs
typedef double RealT
Functions
int main (int argc, char *argv[])
Detailed Description
Shows how to solve a steady Burgers' optimal control problem using the SimOpt interface. We solve the control problem using Composite Step and trust regions.
Definition in file burgers-control/example_02.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 29 of file burgers-control/example_02.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 31 of file burgers-control/example_02.cpp.
References ROL::Constraint< Real >::checkApplyAdjointHessian(), ROL::Constraint< Real >::checkApplyAdjointJacobian(), ROL::Constraint< Real >::checkApplyJacobian(), ROL::Objective< Real >::checkGradient(), ROL::Objective< Real >::checkHessVec(), ROL::StdVector< Real, Element >::clone(), ROL::Vector< Real >::dual(), ROL::TypeE::CompositeStepAlgorithm< Real >::run(), ROL::TypeU::TrustRegionAlgorithm< Real >::run(), ROL::Constraint_SimOpt< Real >::setSolveParameters(), Constraint_BurgersControl< Real >::solve(), and ROL::Vector< Real >::zero().