ROL: example_03.cpp File Reference
example_03.cpp File Reference
Shows how to solve an optimal control problem constrained by unsteady Burgers' equation with the SimOpt interface.
#include "example_03.hpp"
Typedefs
typedef double RealT
Functions
int main (int argc, char *argv[])
Detailed Description
Shows how to solve an optimal control problem constrained by unsteady Burgers' equation with the SimOpt interface.
Shows how to solve a steady Burgers' optimal control problem using full-space methods.
Definition in file burgers-control/example_03.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 17 of file burgers-control/example_03.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 19 of file burgers-control/example_03.cpp.
References ROL::Vector_SimOpt< Real >::applyUnary(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), ROL::Constraint< Real >::checkApplyAdjointHessian(), ROL::Constraint< Real >::checkApplyJacobian(), ROL::Objective< Real >::checkGradient(), ROL::Objective< Real >::checkHessVec(), ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1(), ROL::Constraint_SimOpt< Real >::checkSolve(), ROL::StdVector< Real, Element >::clone(), and ROL::Vector< Real >::zero().