ROL: ROL::CoherentEntropicRisk< Real > Class Template Reference
ROL::CoherentEntropicRisk< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides the interface for the coherent entropic risk measure.
#include <ROL_CoherentEntropicRisk.hpp>
Public Member Functions
CoherentEntropicRisk (void)
void initialize (const Vector< Real > &x)
Initialize temporary variables.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Attributes
Real dval1_
Real dval2_
Real dval3_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::CoherentEntropicRisk< Real >
Provides the interface for the coherent entropic risk measure.
The coherent entropic risk measure is
\[ \mathcal{R}(X) = \inf_{\lambda > 0} \left\{ \lambda \log\mathbb{E}\left[\exp\left(\frac{X}{\lambda}\right)\right] \right\}. \]
\(\mathcal{R}\) is a law-invariant coherent risk measure. ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(\lambda\), then minimizes jointly for \((x_0,\lambda)\).
Definition at line 33 of file ROL_CoherentEntropicRisk.hpp.
Constructor & Destructor Documentation
CoherentEntropicRisk()
template<class Real > ROL::CoherentEntropicRisk< Real >::CoherentEntropicRisk (void) inline
Definition at line 53 of file ROL_CoherentEntropicRisk.hpp.
Member Function Documentation
initialize()
template<class Real > void ROL::CoherentEntropicRisk< Real >::initialize (const Vector< Real > & x) inline virtual
Initialize temporary variables.
   @param[in]   x  is a vector used for initializing storage
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 56 of file ROL_CoherentEntropicRisk.hpp.
References ROL::CoherentEntropicRisk< Real >::dval1_, ROL::CoherentEntropicRisk< Real >::dval2_, ROL::CoherentEntropicRisk< Real >::dval3_, ROL::RandVarFunctional< Real >::initialize(), and zero.
updateValue()
template<class Real > void ROL::CoherentEntropicRisk< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 62 of file ROL_CoherentEntropicRisk.hpp.
References ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::CoherentEntropicRisk< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 70 of file ROL_CoherentEntropicRisk.hpp.
References ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateGradient()
template<class Real > void ROL::CoherentEntropicRisk< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 78 of file ROL_CoherentEntropicRisk.hpp.
References ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getGradient()
template<class Real > void ROL::CoherentEntropicRisk< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 90 of file ROL_CoherentEntropicRisk.hpp.
References ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateHessVec()
template<class Real > void ROL::CoherentEntropicRisk< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 107 of file ROL_CoherentEntropicRisk.hpp.
References ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::CoherentEntropicRisk< Real >::dval1_, ROL::CoherentEntropicRisk< Real >::dval2_, ROL::CoherentEntropicRisk< Real >::dval3_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::RandVarFunctional< Real >::hv_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getHessVec()
template<class Real > void ROL::CoherentEntropicRisk< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 130 of file ROL_CoherentEntropicRisk.hpp.
References ROL::Vector< Real >::axpy(), ROL::RandVarFunctional< Real >::dualVector_, ROL::CoherentEntropicRisk< Real >::dval1_, ROL::CoherentEntropicRisk< Real >::dval2_, ROL::CoherentEntropicRisk< Real >::dval3_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::RandVarFunctional< Real >::hv_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
Member Data Documentation
dval1_
template<class Real > Real ROL::CoherentEntropicRisk< Real >::dval1_ private
Definition at line 35 of file ROL_CoherentEntropicRisk.hpp.
Referenced by ROL::CoherentEntropicRisk< Real >::getHessVec(), ROL::CoherentEntropicRisk< Real >::initialize(), and ROL::CoherentEntropicRisk< Real >::updateHessVec().
dval2_
template<class Real > Real ROL::CoherentEntropicRisk< Real >::dval2_ private
Definition at line 36 of file ROL_CoherentEntropicRisk.hpp.
Referenced by ROL::CoherentEntropicRisk< Real >::getHessVec(), ROL::CoherentEntropicRisk< Real >::initialize(), and ROL::CoherentEntropicRisk< Real >::updateHessVec().
dval3_
template<class Real > Real ROL::CoherentEntropicRisk< Real >::dval3_ private
Definition at line 37 of file ROL_CoherentEntropicRisk.hpp.
Referenced by ROL::CoherentEntropicRisk< Real >::getHessVec(), ROL::CoherentEntropicRisk< Real >::initialize(), and ROL::CoherentEntropicRisk< Real >::updateHessVec().
The documentation for this class was generated from the following file:
ROL_CoherentEntropicRisk.hpp