ROL: ROL::TypeP::InexactNewtonAlgorithm< Real > Class Template Reference
ROL::TypeP::InexactNewtonAlgorithm< Real > Class Template Reference
Provides an interface to run the inexact proximal Newton algorithm.
#include <ROL_TypeP_InexactNewtonAlgorithm.hpp>
Classes
class NewtonObj
Public Member Functions
InexactNewtonAlgorithm (ParameterList &list)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout) override
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeP::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, Vector< Real > &dg, Vector< Real > &px, std::ostream &outStream=std::cout)
Private Attributes
Real t0_
bool initProx_
int maxit_
Maximum number of line search steps (default: 20)
Real rhodec_
Backtracking rate (default: 0.5)
Real c1_
Sufficient Decrease Parameter (default: 1e-4)
Real sigma1_
Lower safeguard for quadratic line search (default: 0.1)
Real sigma2_
Upper safeguard for quadratic line search (default: 0.9)
Real sp_tol1_
Real sp_tol2_
Real sp_exp_
Real sp_tol_min_
std::string algoName_
ParameterList list_
int ls_nfval_
int spgIter_
int nhess_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeP::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void pgstep (Vector< Real > &pgiter, Vector< Real > &pgstep, Objective< Real > &nobj, const Vector< Real > &x, const Vector< Real > &dg, Real t, Real &tol) const
Protected Attributes inherited from ROL::TypeP::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeP::InexactNewtonAlgorithm< Real >
Provides an interface to run the inexact proximal Newton algorithm.
Definition at line 23 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Constructor & Destructor Documentation
InexactNewtonAlgorithm()
template<typename Real > ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm (ParameterList & list)
Definition at line 22 of file ROL_TypeP_InexactNewtonAlgorithm_Def.hpp.
References ROL::TypeP::InexactNewtonAlgorithm< Real >::algoName_, ROL::TypeP::InexactNewtonAlgorithm< Real >::c1_, ROL::TypeP::InexactNewtonAlgorithm< Real >::initProx_, ROL::TypeP::InexactNewtonAlgorithm< Real >::list_, ROL::TypeP::InexactNewtonAlgorithm< Real >::maxit_, ROL::TypeP::InexactNewtonAlgorithm< Real >::rhodec_, ROL::TypeP::InexactNewtonAlgorithm< Real >::sigma1_, ROL::TypeP::InexactNewtonAlgorithm< Real >::sigma2_, ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_exp_, ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_tol1_, ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_tol2_, ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_tol_min_, ROL::TypeP::Algorithm< Real >::status_, ROL::TypeP::InexactNewtonAlgorithm< Real >::t0_, ROL::TypeP::InexactNewtonAlgorithm< Real >::verbosity_, and ROL::TypeP::InexactNewtonAlgorithm< Real >::writeHeader_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeP::InexactNewtonAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, Vector< Real > & dg, Vector< Real > & px, std::ostream & outStream = std::cout) private
Definition at line 53 of file ROL_TypeP_InexactNewtonAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeP::Algorithm< Real >::initialize(), ROL::Vector< Real >::norm(), ROL::Objective< Real >::prox(), ROL::Vector< Real >::set(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeP::InexactNewtonAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, std::ostream & outStream = std::cout) override virtual
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeP::Algorithm< Real >.
Definition at line 84 of file ROL_TypeP_InexactNewtonAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeP::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeP::InexactNewtonAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 208 of file ROL_TypeP_InexactNewtonAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeP::InexactNewtonAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 247 of file ROL_TypeP_InexactNewtonAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeP::InexactNewtonAlgorithm< Real >::writeOutput (std::ostream & os, bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 254 of file ROL_TypeP_InexactNewtonAlgorithm_Def.hpp.
Member Data Documentation
t0_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::t0_ private
Definition at line 25 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
initProx_
template<typename Real > bool ROL::TypeP::InexactNewtonAlgorithm< Real >::initProx_ private
Definition at line 26 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
maxit_
template<typename Real > int ROL::TypeP::InexactNewtonAlgorithm< Real >::maxit_ private
Maximum number of line search steps (default: 20)
Definition at line 28 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
rhodec_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::rhodec_ private
Backtracking rate (default: 0.5)
Definition at line 29 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
c1_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::c1_ private
Sufficient Decrease Parameter (default: 1e-4)
Definition at line 30 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
sigma1_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::sigma1_ private
Lower safeguard for quadratic line search (default: 0.1)
Definition at line 31 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
sigma2_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::sigma2_ private
Upper safeguard for quadratic line search (default: 0.9)
Definition at line 32 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
sp_tol1_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_tol1_ private
Definition at line 33 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
sp_tol2_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_tol2_ private
Definition at line 34 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
sp_exp_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_exp_ private
Definition at line 35 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
sp_tol_min_
template<typename Real > Real ROL::TypeP::InexactNewtonAlgorithm< Real >::sp_tol_min_ private
Definition at line 36 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
algoName_
template<typename Real > std::string ROL::TypeP::InexactNewtonAlgorithm< Real >::algoName_ private
Definition at line 37 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
list_
template<typename Real > ParameterList ROL::TypeP::InexactNewtonAlgorithm< Real >::list_ private
Definition at line 39 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
ls_nfval_
template<typename Real > int ROL::TypeP::InexactNewtonAlgorithm< Real >::ls_nfval_ private
Definition at line 41 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
spgIter_
template<typename Real > int ROL::TypeP::InexactNewtonAlgorithm< Real >::spgIter_ private
Definition at line 41 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
nhess_
template<typename Real > int ROL::TypeP::InexactNewtonAlgorithm< Real >::nhess_ private
Definition at line 41 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeP::InexactNewtonAlgorithm< Real >::verbosity_ private
Definition at line 42 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
writeHeader_
template<typename Real > bool ROL::TypeP::InexactNewtonAlgorithm< Real >::writeHeader_ private
Definition at line 43 of file ROL_TypeP_InexactNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::InexactNewtonAlgorithm< Real >::InexactNewtonAlgorithm().
The documentation for this class was generated from the following files:
ROL_TypeP_InexactNewtonAlgorithm.hpp
ROL_TypeP_InexactNewtonAlgorithm_Def.hpp