ROL: ROL::lSR1< Real > Class Template Reference
ROL::lSR1< Real > Class Template Reference
Provides definitions for limited-memory SR1 operators.
#include <ROL_lSR1.hpp>
Public Member Functions
lSR1 (int M, bool useDefaultScaling=true, Real Bscaling=Real(1), ESecantMode mode=SECANTMODE_BOTH)
void updateStorage (const Vector< Real > &x, const Vector< Real > &grad, const Vector< Real > &gp, const Vector< Real > &s, const Real snorm, const int iter)
virtual void applyH0 (Vector< Real > &Hv, const Vector< Real > &v) const
void applyH (Vector< Real > &Hv, const Vector< Real > &v) const
virtual void applyB0 (Vector< Real > &Bv, const Vector< Real > &v) const
void applyB (Vector< Real > &Bv, const Vector< Real > &v) const
Public Member Functions inherited from ROL::Secant< Real >
virtual ~Secant ()
Secant (int M=10, bool useDefaultScaling=true, Real Bscaling=Real(1), ESecantMode mode=SECANTMODE_BOTH)
Ptr< SecantState< Real > > & get_state ()
const Ptr< SecantState< Real > > & get_state () const
void test (std::ostream &stream=std::cout) const
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Attributes
bool isInitialized_
bool H0called_
bool B0called_
Ptr< Vector< Real > > Bs_
Ptr< Vector< Real > > Hy_
Ptr< Vector< Real > > prim_
Ptr< Vector< Real > > dual_
Additional Inherited Members
Protected Attributes inherited from ROL::Secant< Real >
const Ptr< SecantState< Real > > state_
Ptr< Vector< Real > > y_
bool useDefaultScaling_
Real Bscaling_
Detailed Description
template<class Real>
class ROL::lSR1< Real >
Provides definitions for limited-memory SR1 operators.
Definition at line 23 of file ROL_lSR1.hpp.
Constructor & Destructor Documentation
lSR1()
template<class Real > ROL::lSR1< Real >::lSR1 (int M, bool useDefaultScaling = true, Real Bscaling = Real(1), ESecantMode mode = SECANTMODE_BOTH) inline
Definition at line 37 of file ROL_lSR1.hpp.
References ROL::Secant< Real >::Bscaling_, and ROL::Secant< Real >::useDefaultScaling_.
Member Function Documentation
updateStorage()
template<class Real > void ROL::lSR1< Real >::updateStorage (const Vector< Real > & x, const Vector< Real > & grad, const Vector< Real > & gp, const Vector< Real > & s, const Real snorm, const int iter) inline virtual
Reimplemented from ROL::Secant< Real >.
Definition at line 45 of file ROL_lSR1.hpp.
References ROL::Vector< Real >::apply(), ROL::lSR1< Real >::applyB(), ROL::lSR1< Real >::applyH(), ROL::lSR1< Real >::Bs_, ROL::Secant< Real >::Bscaling_, ROL::Vector< Real >::clone(), ROL::lSR1< Real >::dual_, ROL::lSR1< Real >::Hy_, ROL::lSR1< Real >::isInitialized_, ROL::lSR1< Real >::prim_, ROL::SECANTMODE_BOTH, ROL::SECANTMODE_FORWARD, ROL::SECANTMODE_INVERSE, ROL::Secant< Real >::state_, ROL::Secant< Real >::useDefaultScaling_, and ROL::Secant< Real >::y_.
applyH0()
template<class Real > virtual void ROL::lSR1< Real >::applyH0 (Vector< Real > & Hv, const Vector< Real > & v) const inline virtual
Reimplemented from ROL::Secant< Real >.
Definition at line 161 of file ROL_lSR1.hpp.
References ROL::Secant< Real >::Bscaling_, ROL::Vector< Real >::dual(), ROL::lSR1< Real >::H0called_, ROL::lSR1< Real >::prim_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and ROL::Secant< Real >::state_.
Referenced by ROL::lSR1< Real >::applyH().
applyH()
template<class Real > void ROL::lSR1< Real >::applyH (Vector< Real > & Hv, const Vector< Real > & v) const inline virtual
Implements ROL::Secant< Real >.
Definition at line 174 of file ROL_lSR1.hpp.
References ROL::lSR1< Real >::applyH0(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dual(), ROL::lSR1< Real >::H0called_, ROL::lSR1< Real >::prim_, ROL::SECANTMODE_BOTH, ROL::SECANTMODE_INVERSE, and ROL::Secant< Real >::state_.
Referenced by ROL::lSR1< Real >::updateStorage().
applyB0()
template<class Real > virtual void ROL::lSR1< Real >::applyB0 (Vector< Real > & Bv, const Vector< Real > & v) const inline virtual
Reimplemented from ROL::Secant< Real >.
Definition at line 227 of file ROL_lSR1.hpp.
References ROL::lSR1< Real >::B0called_, ROL::Secant< Real >::Bscaling_, ROL::Vector< Real >::dual(), ROL::lSR1< Real >::dual_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and ROL::Secant< Real >::state_.
Referenced by ROL::lSR1< Real >::applyB().
applyB()
template<class Real > void ROL::lSR1< Real >::applyB (Vector< Real > & Bv, const Vector< Real > & v) const inline virtual
Implements ROL::Secant< Real >.
Definition at line 240 of file ROL_lSR1.hpp.
References ROL::lSR1< Real >::applyB0(), ROL::Vector< Real >::axpy(), ROL::lSR1< Real >::B0called_, ROL::Vector< Real >::dual(), ROL::lSR1< Real >::dual_, ROL::SECANTMODE_BOTH, ROL::SECANTMODE_FORWARD, and ROL::Secant< Real >::state_.
Referenced by ROL::lSR1< Real >::updateStorage().
Member Data Documentation
isInitialized_
template<class Real > bool ROL::lSR1< Real >::isInitialized_ private
Definition at line 27 of file ROL_lSR1.hpp.
Referenced by ROL::lSR1< Real >::updateStorage().
H0called_
template<class Real > bool ROL::lSR1< Real >::H0called_ mutable private
Definition at line 28 of file ROL_lSR1.hpp.
Referenced by ROL::lSR1< Real >::applyH(), and ROL::lSR1< Real >::applyH0().
B0called_
template<class Real > bool ROL::lSR1< Real >::B0called_ private
Definition at line 28 of file ROL_lSR1.hpp.
Referenced by ROL::lSR1< Real >::applyB(), and ROL::lSR1< Real >::applyB0().
Bs_
template<class Real > Ptr<Vector<Real> > ROL::lSR1< Real >::Bs_ private
Definition at line 29 of file ROL_lSR1.hpp.
Referenced by ROL::lSR1< Real >::updateStorage().
Hy_
template<class Real > Ptr<Vector<Real> > ROL::lSR1< Real >::Hy_ private
Definition at line 29 of file ROL_lSR1.hpp.
Referenced by ROL::lSR1< Real >::updateStorage().
prim_
template<class Real > Ptr<Vector<Real> > ROL::lSR1< Real >::prim_ private
Definition at line 29 of file ROL_lSR1.hpp.
Referenced by ROL::lSR1< Real >::applyH(), ROL::lSR1< Real >::applyH0(), and ROL::lSR1< Real >::updateStorage().
dual_
template<class Real > Ptr<Vector<Real> > ROL::lSR1< Real >::dual_ private
Definition at line 29 of file ROL_lSR1.hpp.
Referenced by ROL::lSR1< Real >::applyB(), ROL::lSR1< Real >::applyB0(), and ROL::lSR1< Real >::updateStorage().
The documentation for this class was generated from the following file:
ROL_lSR1.hpp