ROL: ROL::TypeU::BundleAlgorithm< Real > Class Template Reference
ROL::TypeU::BundleAlgorithm< Real > Class Template Reference
Provides an interface to run trust-bundle methods for unconstrained optimization algorithms.
#include <ROL_TypeU_BundleAlgorithm.hpp>
Public Member Functions
BundleAlgorithm (ParameterList &parlist, const Ptr< LineSearch_U< Real > > &lineSearch=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, std::ostream &outStream=std::cout) override
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool print_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeU::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &linear_con, Vector< Real > &linear_mul, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems with explicit linear equality constraints (Type-U). This is the primary Type-U with explicit linear equality constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &linear_con, Vector< Real > &linear_mul, const Vector< Real > &linear_c, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems with explicit linear equality constraints (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (const Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, std::ostream &outStream=std::cout)
Private Attributes
Ptr< Bundle_U< Real > > bundle_
Ptr< LineSearch_U< Real > > lineSearch_
unsigned QPiter_
unsigned QPmaxit_
Real QPtol_
int step_flag_
Real T_
Real tol_
Real m1_
Real m2_
Real m3_
Real nu_
int ls_maxit_
bool first_print_
bool isConvex_
int verbosity_
bool printHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeU::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Protected Attributes inherited from ROL::TypeU::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeU::BundleAlgorithm< Real >
Provides an interface to run trust-bundle methods for unconstrained optimization algorithms.
Definition at line 26 of file ROL_TypeU_BundleAlgorithm.hpp.
Constructor & Destructor Documentation
BundleAlgorithm()
template<typename Real > ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm (ParameterList & parlist, const Ptr< LineSearch_U< Real > > & lineSearch = nullPtr)
Definition at line 23 of file ROL_TypeU_BundleAlgorithm_Def.hpp.
References ROL::TypeU::BundleAlgorithm< Real >::bundle_, ROL::TypeU::BundleAlgorithm< Real >::isConvex_, ROL::TypeU::BundleAlgorithm< Real >::lineSearch_, ROL::TypeU::BundleAlgorithm< Real >::ls_maxit_, ROL::TypeU::BundleAlgorithm< Real >::m1_, ROL::TypeU::BundleAlgorithm< Real >::m2_, ROL::TypeU::BundleAlgorithm< Real >::m3_, ROL::TypeU::BundleAlgorithm< Real >::nu_, ROL::TypeU::BundleAlgorithm< Real >::printHeader_, ROL::TypeU::BundleAlgorithm< Real >::QPmaxit_, ROL::TypeU::BundleAlgorithm< Real >::QPtol_, ROL::TypeU::Algorithm< Real >::reset(), ROL::TypeU::Algorithm< Real >::state_, ROL::TypeU::Algorithm< Real >::status_, ROL::TypeU::BundleAlgorithm< Real >::T_, ROL::TypeU::BundleAlgorithm< Real >::tol_, ROL::TypeU::BundleAlgorithm< Real >::verbosity_, and zero.
Member Function Documentation
run()
template<typename Real > void ROL::TypeU::BundleAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, std::ostream & outStream = std::cout) override virtual
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeU::Algorithm< Real >.
Definition at line 98 of file ROL_TypeU_BundleAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::plus(), ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), ROL::TypeU::Algorithm< Real >::writeExitStatus(), and zero.
writeHeader()
template<typename Real > void ROL::TypeU::BundleAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeU::Algorithm< Real >.
Definition at line 353 of file ROL_TypeU_BundleAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeU::BundleAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeU::Algorithm< Real >.
Definition at line 371 of file ROL_TypeU_BundleAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeU::BundleAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeU::Algorithm< Real >.
Definition at line 378 of file ROL_TypeU_BundleAlgorithm_Def.hpp.
initialize()
template<typename Real > void ROL::TypeU::BundleAlgorithm< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, std::ostream & outStream = std::cout) private
Definition at line 77 of file ROL_TypeU_BundleAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeU::Algorithm< Real >::initialize(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
Member Data Documentation
bundle_
template<typename Real > Ptr<Bundle_U<Real> > ROL::TypeU::BundleAlgorithm< Real >::bundle_ private
Definition at line 29 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
lineSearch_
template<typename Real > Ptr<LineSearch_U<Real> > ROL::TypeU::BundleAlgorithm< Real >::lineSearch_ private
Definition at line 30 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
QPiter_
template<typename Real > unsigned ROL::TypeU::BundleAlgorithm< Real >::QPiter_ private
Definition at line 33 of file ROL_TypeU_BundleAlgorithm.hpp.
QPmaxit_
template<typename Real > unsigned ROL::TypeU::BundleAlgorithm< Real >::QPmaxit_ private
Definition at line 34 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
QPtol_
template<typename Real > Real ROL::TypeU::BundleAlgorithm< Real >::QPtol_ private
Definition at line 35 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
step_flag_
template<typename Real > int ROL::TypeU::BundleAlgorithm< Real >::step_flag_ private
Definition at line 38 of file ROL_TypeU_BundleAlgorithm.hpp.
T_
template<typename Real > Real ROL::TypeU::BundleAlgorithm< Real >::T_ private
Definition at line 43 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
tol_
template<typename Real > Real ROL::TypeU::BundleAlgorithm< Real >::tol_ private
Definition at line 44 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
m1_
template<typename Real > Real ROL::TypeU::BundleAlgorithm< Real >::m1_ private
Definition at line 45 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
m2_
template<typename Real > Real ROL::TypeU::BundleAlgorithm< Real >::m2_ private
Definition at line 46 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
m3_
template<typename Real > Real ROL::TypeU::BundleAlgorithm< Real >::m3_ private
Definition at line 47 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
nu_
template<typename Real > Real ROL::TypeU::BundleAlgorithm< Real >::nu_ private
Definition at line 48 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
ls_maxit_
template<typename Real > int ROL::TypeU::BundleAlgorithm< Real >::ls_maxit_ private
Definition at line 51 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
first_print_
template<typename Real > bool ROL::TypeU::BundleAlgorithm< Real >::first_print_ private
Definition at line 53 of file ROL_TypeU_BundleAlgorithm.hpp.
isConvex_
template<typename Real > bool ROL::TypeU::BundleAlgorithm< Real >::isConvex_ private
Definition at line 54 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
verbosity_
template<typename Real > int ROL::TypeU::BundleAlgorithm< Real >::verbosity_ private
Definition at line 56 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
printHeader_
template<typename Real > bool ROL::TypeU::BundleAlgorithm< Real >::printHeader_ private
Definition at line 57 of file ROL_TypeU_BundleAlgorithm.hpp.
Referenced by ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm().
The documentation for this class was generated from the following files:
ROL_TypeU_BundleAlgorithm.hpp
ROL_TypeU_BundleAlgorithm_Def.hpp