ROL: ROL::BrentsProjection< Real > Class Template Reference
ROL::BrentsProjection< Real > Class Template Reference
#include <ROL_BrentsProjection.hpp>
Public Member Functions
BrentsProjection (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res)
BrentsProjection (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res, ParameterList &list)
void project (Vector< Real > &x, std::ostream &stream=std::cout) override
Public Member Functions inherited from ROL::PolyhedralProjection< Real >
virtual ~PolyhedralProjection ()
PolyhedralProjection (const Ptr< BoundConstraint< Real > > &bnd)
PolyhedralProjection (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res)
const Ptr< Constraint< Real > > getLinearConstraint (void) const
const Ptr< BoundConstraint< Real > > getBoundConstraint (void) const
const Ptr< Vector< Real > > getMultiplier (void) const
const Ptr< Vector< Real > > getResidual (void) const
Private Member Functions
void initialize (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res)
Real residual (const Vector< Real > &x) const
void update_primal (Vector< Real > &y, const Vector< Real > &x, const Real lam) const
void project_df (Vector< Real > &x, Real &lam, Real &dlam, std::ostream &stream=std::cout) const
Private Attributes
int dim_
Ptr< Vector< Real > > xnew_
Ptr< Vector< Real > > Px_
Real b_
Real mul1_
Real dlam1_
Real cdot_
Real DEFAULT_atol_
Real DEFAULT_rtol_
Real DEFAULT_ltol_
int DEFAULT_maxit_
int DEFAULT_verbosity_
Real atol_
Real rtol_
Real ltol_
int maxit_
int verbosity_
Real ctol_
Additional Inherited Members
Protected Attributes inherited from ROL::PolyhedralProjection< Real >
const Ptr< BoundConstraint< Real > > bnd_
const Ptr< Constraint< Real > > con_
Ptr< Vector< Real > > xprim_
Ptr< Vector< Real > > xdual_
Ptr< Vector< Real > > mul_
Ptr< Vector< Real > > res_
Detailed Description
template<typename Real>
class ROL::BrentsProjection< Real >
Definition at line 19 of file ROL_BrentsProjection.hpp.
Constructor & Destructor Documentation
BrentsProjection() [1/2]
template<typename Real > ROL::BrentsProjection< Real >::BrentsProjection (const Vector< Real > & xprim, const Vector< Real > & xdual, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & con, const Vector< Real > & mul, const Vector< Real > & res)
Definition at line 16 of file ROL_BrentsProjection_Def.hpp.
References ROL::BrentsProjection< Real >::initialize().
BrentsProjection() [2/2]
template<typename Real > ROL::BrentsProjection< Real >::BrentsProjection (const Vector< Real > & xprim, const Vector< Real > & xdual, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & con, const Vector< Real > & mul, const Vector< Real > & res, ParameterList & list)
Definition at line 37 of file ROL_BrentsProjection_Def.hpp.
References ROL::BrentsProjection< Real >::atol_, ROL::BrentsProjection< Real >::DEFAULT_atol_, ROL::BrentsProjection< Real >::DEFAULT_ltol_, ROL::BrentsProjection< Real >::DEFAULT_maxit_, ROL::BrentsProjection< Real >::DEFAULT_rtol_, ROL::BrentsProjection< Real >::DEFAULT_verbosity_, ROL::BrentsProjection< Real >::initialize(), ROL::BrentsProjection< Real >::ltol_, ROL::BrentsProjection< Real >::maxit_, ROL::BrentsProjection< Real >::rtol_, and ROL::BrentsProjection< Real >::verbosity_.
Member Function Documentation
initialize()
template<typename Real > void ROL::BrentsProjection< Real >::initialize (const Vector< Real > & xprim, const Vector< Real > & xdual, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & con, const Vector< Real > & mul, const Vector< Real > & res) private
Definition at line 64 of file ROL_BrentsProjection_Def.hpp.
References ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), and ROL::Temp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection(), and ROL::BrentsProjection< Real >::BrentsProjection().
project()
template<typename Real > void ROL::BrentsProjection< Real >::project (Vector< Real > & x, std::ostream & stream = std::cout) override virtual
Reimplemented from ROL::PolyhedralProjection< Real >.
Definition at line 100 of file ROL_BrentsProjection_Def.hpp.
residual()
template<typename Real > Real ROL::BrentsProjection< Real >::residual (const Vector< Real > & x) const private
Definition at line 115 of file ROL_BrentsProjection_Def.hpp.
update_primal()
template<typename Real > void ROL::BrentsProjection< Real >::update_primal (Vector< Real > & y, const Vector< Real > & x, const Real lam) const private
Definition at line 120 of file ROL_BrentsProjection_Def.hpp.
References ROL::Vector< Real >::axpy(), and ROL::Vector< Real >::set().
project_df()
template<typename Real > void ROL::BrentsProjection< Real >::project_df (Vector< Real > & x, Real & lam, Real & dlam, std::ostream & stream = std::cout) const private
Definition at line 127 of file ROL_BrentsProjection_Def.hpp.
References ROL::Vector< Real >::set(), and zero.
Member Data Documentation
dim_
template<typename Real > int ROL::BrentsProjection< Real >::dim_ private
Definition at line 21 of file ROL_BrentsProjection.hpp.
xnew_
template<typename Real > Ptr<Vector<Real> > ROL::BrentsProjection< Real >::xnew_ private
Definition at line 22 of file ROL_BrentsProjection.hpp.
Px_
template<typename Real > Ptr<Vector<Real> > ROL::BrentsProjection< Real >::Px_ private
Definition at line 22 of file ROL_BrentsProjection.hpp.
b_
template<typename Real > Real ROL::BrentsProjection< Real >::b_ private
Definition at line 23 of file ROL_BrentsProjection.hpp.
mul1_
template<typename Real > Real ROL::BrentsProjection< Real >::mul1_ private
Definition at line 23 of file ROL_BrentsProjection.hpp.
dlam1_
template<typename Real > Real ROL::BrentsProjection< Real >::dlam1_ private
Definition at line 23 of file ROL_BrentsProjection.hpp.
cdot_
template<typename Real > Real ROL::BrentsProjection< Real >::cdot_ private
Definition at line 23 of file ROL_BrentsProjection.hpp.
DEFAULT_atol_
template<typename Real > Real ROL::BrentsProjection< Real >::DEFAULT_atol_ private
Definition at line 25 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
DEFAULT_rtol_
template<typename Real > Real ROL::BrentsProjection< Real >::DEFAULT_rtol_ private
Definition at line 25 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
DEFAULT_ltol_
template<typename Real > Real ROL::BrentsProjection< Real >::DEFAULT_ltol_ private
Definition at line 25 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
DEFAULT_maxit_
template<typename Real > int ROL::BrentsProjection< Real >::DEFAULT_maxit_ private
Definition at line 26 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
DEFAULT_verbosity_
template<typename Real > int ROL::BrentsProjection< Real >::DEFAULT_verbosity_ private
Definition at line 26 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
atol_
template<typename Real > Real ROL::BrentsProjection< Real >::atol_ private
Definition at line 28 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
rtol_
template<typename Real > Real ROL::BrentsProjection< Real >::rtol_ private
Definition at line 28 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
ltol_
template<typename Real > Real ROL::BrentsProjection< Real >::ltol_ private
Definition at line 28 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
maxit_
template<typename Real > int ROL::BrentsProjection< Real >::maxit_ private
Definition at line 29 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
verbosity_
template<typename Real > int ROL::BrentsProjection< Real >::verbosity_ private
Definition at line 29 of file ROL_BrentsProjection.hpp.
Referenced by ROL::BrentsProjection< Real >::BrentsProjection().
ctol_
template<typename Real > Real ROL::BrentsProjection< Real >::ctol_ private
Definition at line 31 of file ROL_BrentsProjection.hpp.
The documentation for this class was generated from the following files:
ROL_BrentsProjection.hpp
ROL_BrentsProjection_Def.hpp