ROL: ROL::Distribution< Real > Class Template Reference
ROL::Distribution< Real > Class Template Reference
#include <ROL_Distribution.hpp>
Public Member Functions
virtual ~Distribution (void)
virtual Real evaluatePDF (const Real input) const
virtual Real evaluateCDF (const Real input) const
virtual Real integrateCDF (const Real input) const
virtual Real invertCDF (const Real input) const
virtual Real moment (const size_t m) const
virtual Real lowerBound (void) const
virtual Real upperBound (void) const
virtual void test (std::ostream &outStream=std::cout) const
Protected Member Functions
void test (const std::vector< Real > &X, const std::vector< int > &T, std::ostream &outStream=std::cout) const
Private Member Functions
void test_onesided (const Real x, std::ostream &outStream=std::cout) const
void test_centered (const Real x, std::ostream &outStream=std::cout) const
void test_moment (const size_t order, std::ostream &outStream=std::cout) const
Detailed Description
template<class Real>
class ROL::Distribution< Real >
Definition at line 21 of file ROL_Distribution.hpp.
Constructor & Destructor Documentation
~Distribution()
template<class Real > virtual ROL::Distribution< Real >::~Distribution (void) inline virtual
Definition at line 23 of file ROL_Distribution.hpp.
Member Function Documentation
evaluatePDF()
template<class Real > virtual Real ROL::Distribution< Real >::evaluatePDF (const Real input) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 25 of file ROL_Distribution.hpp.
Referenced by ROL::Distribution< Real >::test_centered(), and ROL::Distribution< Real >::test_onesided().
evaluateCDF()
template<class Real > virtual Real ROL::Distribution< Real >::evaluateCDF (const Real input) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 30 of file ROL_Distribution.hpp.
Referenced by ROL::Distribution< Real >::test_centered(), and ROL::Distribution< Real >::test_onesided().
integrateCDF()
template<class Real > virtual Real ROL::Distribution< Real >::integrateCDF (const Real input) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 35 of file ROL_Distribution.hpp.
Referenced by ROL::Distribution< Real >::test_centered(), and ROL::Distribution< Real >::test_onesided().
invertCDF()
template<class Real > virtual Real ROL::Distribution< Real >::invertCDF (const Real input) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 40 of file ROL_Distribution.hpp.
Referenced by ROL::Distribution< Real >::test_centered(), ROL::Distribution< Real >::test_moment(), and ROL::Distribution< Real >::test_onesided().
moment()
template<class Real > virtual Real ROL::Distribution< Real >::moment (const size_t m) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 45 of file ROL_Distribution.hpp.
Referenced by ROL::Distribution< Real >::test_moment().
lowerBound()
template<class Real > virtual Real ROL::Distribution< Real >::lowerBound (void) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 50 of file ROL_Distribution.hpp.
upperBound()
template<class Real > virtual Real ROL::Distribution< Real >::upperBound (void) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 55 of file ROL_Distribution.hpp.
test() [1/2]
template<class Real > virtual void ROL::Distribution< Real >::test (std::ostream & outStream = std::cout) const inline virtual
Reimplemented in ROL::Arcsine< Real >, ROL::Beta< Real >, ROL::Cauchy< Real >, ROL::Dirac< Real >, ROL::Exponential< Real >, ROL::Gamma< Real >, ROL::Gaussian< Real >, ROL::Gumbel< Real >, ROL::Kumaraswamy< Real >, ROL::Laplace< Real >, ROL::Logistic< Real >, ROL::Parabolic< Real >, ROL::RaisedCosine< Real >, ROL::Smale< Real >, ROL::Triangle< Real >, ROL::TruncatedExponential< Real >, ROL::TruncatedGaussian< Real >, and ROL::Uniform< Real >.
Definition at line 60 of file ROL_Distribution.hpp.
Referenced by ROL::Arcsine< Real >::test(), ROL::Beta< Real >::test(), ROL::Cauchy< Real >::test(), ROL::Dirac< Real >::test(), ROL::Exponential< Real >::test(), ROL::Gamma< Real >::test(), ROL::Gaussian< Real >::test(), ROL::Gumbel< Real >::test(), ROL::Kumaraswamy< Real >::test(), ROL::Laplace< Real >::test(), ROL::Logistic< Real >::test(), ROL::Parabolic< Real >::test(), ROL::RaisedCosine< Real >::test(), ROL::Smale< Real >::test(), ROL::Triangle< Real >::test(), ROL::TruncatedExponential< Real >::test(), ROL::TruncatedGaussian< Real >::test(), and ROL::Uniform< Real >::test().
test() [2/2]
template<class Real > void ROL::Distribution< Real >::test (const std::vector< Real > & X, const std::vector< int > & T, std::ostream & outStream = std::cout) const inline protected
Definition at line 66 of file ROL_Distribution.hpp.
References ROL::Distribution< Real >::test_centered(), ROL::Distribution< Real >::test_moment(), and ROL::Distribution< Real >::test_onesided().
test_onesided()
template<class Real > void ROL::Distribution< Real >::test_onesided (const Real x, std::ostream & outStream = std::cout) const inline private
Definition at line 82 of file ROL_Distribution.hpp.
References ROL::Distribution< Real >::evaluateCDF(), ROL::Distribution< Real >::evaluatePDF(), ROL::Distribution< Real >::integrateCDF(), and ROL::Distribution< Real >::invertCDF().
Referenced by ROL::Distribution< Real >::test().
test_centered()
template<class Real > void ROL::Distribution< Real >::test_centered (const Real x, std::ostream & outStream = std::cout) const inline private
Definition at line 175 of file ROL_Distribution.hpp.
References ROL::Distribution< Real >::evaluateCDF(), ROL::Distribution< Real >::evaluatePDF(), ROL::Distribution< Real >::integrateCDF(), and ROL::Distribution< Real >::invertCDF().
Referenced by ROL::Distribution< Real >::test().
test_moment()
template<class Real > void ROL::Distribution< Real >::test_moment (const size_t order, std::ostream & outStream = std::cout) const inline private
Definition at line 270 of file ROL_Distribution.hpp.
References ROL::Distribution< Real >::invertCDF(), and ROL::Distribution< Real >::moment().
Referenced by ROL::Distribution< Real >::test().
The documentation for this class was generated from the following file:
ROL_Distribution.hpp