ROL: ROL::LinearOperator< Real > Class Template Reference
ROL::LinearOperator< Real > Class Template Reference abstract
User Interface » Functional Interface
Provides the interface to apply a linear operator.
#include <ROL_LinearOperator.hpp>
Public Member Functions
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const =0
Apply linear operator.
virtual void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Detailed Description
template<class Real>
class ROL::LinearOperator< Real >
Provides the interface to apply a linear operator.
ROL's linear operator interface is designed to interface with ROL's Krylov methods. These linear operators often represent projected Hessians or preconditioners.
The basic operator interace, to be implemented by the user, requires:
apply – apply operator to a vector.
The user may also implement:
update – update the state of the linear operator.
applyInverse – apply the inverse operator to a vector.
applyAdjoint – apply the adjoint of the operator to a vector.
applyAdjointInverse – apply the adjoint of the inverse operator to a vector.
Definition at line 37 of file ROL_LinearOperator.hpp.
Constructor & Destructor Documentation
~LinearOperator()
template<class Real > virtual ROL::LinearOperator< Real >::~LinearOperator () inline virtual
Definition at line 40 of file ROL_LinearOperator.hpp.
Member Function Documentation
update()
template<class Real > virtual void ROL::LinearOperator< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update linear operator.
This function updates the linear operator at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented in ROL::InteriorPoint::PrimalDualSymmetrizer< Real >, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >, ROL::BlockOperator2Determinant< Real >, ROL::DiagonalOperator< Real >, ROL::LinearOperatorProduct< Real >, ROL::LinearOperatorSum< Real >, ROL::NullSpaceOperator< Real >, ROL::RangeSpaceOperator< Real >, ROL::StdLinearOperator< Real >, ROL::PrimalDualInteriorPointBlock11< Real >, ROL::PrimalDualInteriorPointBlock22< Real >, and ROL::PrimalDualInteriorPointBlock21< Real >.
Definition at line 49 of file ROL_LinearOperator.hpp.
apply()
template<class Real > virtual void ROL::LinearOperator< Real >::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const pure virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implemented in IdentityOperator< Real >, ROL::BlockOperator< Real >, ROL::BlockOperator2< Real >, ROL::DyadicOperator< Real >, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >, Identity< Real >, TridiagonalToeplitzOperator< Real >, Identity< Real >, TridiagonalToeplitzOperator< Real >, ROL::TypeB::NewtonKrylovAlgorithm< Real >::HessianPNK, ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::HessianPDAS, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::HessianPDAS_Poly, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly, ROL::FletcherObjectiveE< Real >::AugSystem, ROL::FletcherObjectiveE< Real >::AugSystemPrecond, ROL::NewtonKrylov_U< Real >::HessianNK, ROL::NewtonKrylov_U< Real >::PrecondNK, ROL::AugmentedSystemOperator< Real >, ROL::AugmentedSystemPrecOperator< Real >, ROL::BlockOperator2Determinant< Real >, ROL::DiagonalOperator< Real >, ROL::HouseholderReflector< Real >, ROL::IdentityOperator< Real >, ROL::LinearOperatorFromConstraint< Real >, ROL::LinearOperatorProduct< Real >, ROL::LinearOperatorSum< Real >, ROL::NullOperator< Real >, ROL::NullSpaceOperator< Real >, ROL::RangeSpaceOperator< Real >, ROL::SemismoothNewtonProjection< Real >::Precond, ROL::StdLinearOperator< Real >, ROL::BoundFletcher< Real >::AugSystemSym, ROL::BoundFletcher< Real >::AugSystemNonSym, ROL::BoundFletcher< Real >::AugSystemPrecond, ROL::Fletcher< Real >::AugSystem, ROL::Fletcher< Real >::AugSystemPrecond, ROL::PrimalDualInteriorPointBlock11< Real >, ROL::PrimalDualInteriorPointBlock12< Real >, ROL::PrimalDualInteriorPointBlock21< Real >, ROL::PrimalDualInteriorPointBlock22< Real >, ROL::NewtonKrylovStep< Real >::HessianNK, ROL::NewtonKrylovStep< Real >::PrecondNK, ROL::PrimalDualActiveSetStep< Real >::HessianPD, ROL::PrimalDualActiveSetStep< Real >::PrecondPD, ROL::ProjectedNewtonKrylovStep< Real >::HessianPNK, ROL::ProjectedNewtonKrylovStep< Real >::PrecondPNK, ROL::Secant< Real >, and ROL::SemismoothNewtonProjection< Real >::Jacobian.
Referenced by ROL::LinearOperator< Real >::applyAdjoint(), ROL::Lanczos< Real >::iterate(), ROL::details::MINRES< Real >::run(), ROL::BiCGSTAB< Real >::run(), ROL::ConjugateGradients< Real >::run(), ROL::ConjugateResiduals< Real >::run(), and ROL::GMRES< Real >::run().
applyInverse()
template<class Real > virtual void ROL::LinearOperator< Real >::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented in ROL::BlockOperator2< Real >, ROL::DyadicOperator< Real >, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >, TridiagonalToeplitzOperator< Real >, TridiagonalToeplitzOperator< Real >, ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly, ROL::FletcherObjectiveE< Real >::AugSystemPrecond, ROL::NewtonKrylov_U< Real >::PrecondNK, ROL::AugmentedSystemOperator< Real >, ROL::AugmentedSystemPrecOperator< Real >, ROL::BlockOperator2Determinant< Real >, ROL::DiagonalOperator< Real >, ROL::HouseholderReflector< Real >, ROL::IdentityOperator< Real >, ROL::LinearOperatorFromConstraint< Real >, ROL::LinearOperatorProduct< Real >, ROL::LinearOperatorSum< Real >, ROL::NullOperator< Real >, ROL::NullSpaceOperator< Real >, ROL::RangeSpaceOperator< Real >, ROL::SemismoothNewtonProjection< Real >::Precond, ROL::StdLinearOperator< Real >, ROL::BoundFletcher< Real >::AugSystemPrecond, ROL::Fletcher< Real >::AugSystemPrecond, ROL::PrimalDualInteriorPointBlock11< Real >, ROL::PrimalDualInteriorPointBlock12< Real >, ROL::PrimalDualInteriorPointBlock21< Real >, ROL::PrimalDualInteriorPointBlock22< Real >, ROL::NewtonKrylovStep< Real >::PrecondNK, ROL::PrimalDualActiveSetStep< Real >::PrecondPD, ROL::ProjectedNewtonKrylovStep< Real >::PrecondPNK, and ROL::Secant< Real >.
Definition at line 67 of file ROL_LinearOperator.hpp.
References ROL::Vector< Real >::set().
Referenced by ROL::LinearOperator< Real >::applyAdjointInverse(), ROL::BiCGSTAB< Real >::run(), ROL::ConjugateGradients< Real >::run(), ROL::ConjugateResiduals< Real >::run(), and ROL::GMRES< Real >::run().
applyAdjoint()
template<class Real > virtual void ROL::LinearOperator< Real >::applyAdjoint (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of linear operator.
This function applies the adjoint of a linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented in ROL::AugmentedSystemOperator< Real >, ROL::AugmentedSystemPrecOperator< Real >, ROL::NullSpaceOperator< Real >, ROL::RangeSpaceOperator< Real >, and ROL::StdLinearOperator< Real >.
Definition at line 80 of file ROL_LinearOperator.hpp.
References ROL::LinearOperator< Real >::apply().
applyAdjointInverse()
template<class Real > virtual void ROL::LinearOperator< Real >::applyAdjointInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of the inverse linear operator.
This function applies the adjoint of the inverse linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented in ROL::AugmentedSystemOperator< Real >, ROL::AugmentedSystemPrecOperator< Real >, ROL::NullSpaceOperator< Real >, ROL::RangeSpaceOperator< Real >, and ROL::StdLinearOperator< Real >.
Definition at line 93 of file ROL_LinearOperator.hpp.
References ROL::LinearOperator< Real >::applyInverse().
The documentation for this class was generated from the following file:
ROL_LinearOperator.hpp