ROL: ROL::SerialConstraint< Real > Class Template Reference
ROL::SerialConstraint< Real > Class Template Reference
User Interface » Functional Interface
Evaluates ROL::DynamicConstraint over a sequential set of time intervals.
#include <ROL_SerialConstraint.hpp>
Public Types
using size_type = typename std::vector< Real >::size_type
Public Types inherited from ROL::SerialFunction< Real >
using size_type = typename std::vector< Real >::size_type
Public Member Functions
SerialConstraint (const Ptr< DynamicConstraint< Real > > &con, const Vector< Real > &u_initial, const TimeStampsPtr< Real > &timeStampsPtr)
virtual void solve (Vector< Real > &c, Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Given \(z\), solve \(c(u,z)=0\) for \(u\).
virtual void update (const Vector< Real > &u, const Vector< Real > &z, bool flag=true, int iter=-1) override
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void value (Vector< Real > &c, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Evaluate the constraint operator \(c:\mathcal{U}\times\mathcal{Z} \rightarrow \mathcal{C}\) at \((u,z)\).
virtual void applyJacobian_1 (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the partial constraint Jacobian at \((u,z)\), \(c_u(u,z) \in L(\mathcal{U}, \mathcal{C})\), to the vector \(v\).
virtual void applyInverseJacobian_1 (Vector< Real > &ijv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the inverse partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-1} \in L(\mathcal{C}, \mathcal{U})\), to the vector \(v\).
virtual void applyAdjointJacobian_1 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualv, Real &tol) override
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
void applyInverseAdjointJacobian_1 (Vector< Real > &iajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the inverse of the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-*} \in L(\mathcal{U}^*, \mathcal{C}^*)\), to the vector \(v\).
virtual void applyJacobian_2 (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the partial constraint Jacobian at \((u,z)\), \(c_z(u,z) \in L(\mathcal{Z}, \mathcal{C})\), to the vector \(v\).
virtual void applyAdjointJacobian_2 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the primary interface.
virtual void applyAdjointHessian_11 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_12 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the optimization-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uz}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_21 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the simulation-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_22 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
Apply the optimization-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zz}(u,z)(v,\cdot)^*w\).
Public Member Functions inherited from ROL::Constraint_SimOpt< Real >
Constraint_SimOpt ()
virtual void update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
virtual void update_1 (const Vector< Real > &u, bool flag=true, int iter=-1)
Update constraint functions with respect to Sim variable.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_1 (const Vector< Real > &u, UpdateType type, int iter=-1)
virtual void update_2 (const Vector< Real > &z, bool flag=true, int iter=-1)
Update constraint functions with respect to Opt variable. x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_2 (const Vector< Real > &z, UpdateType type, int iter=-1)
virtual void solve_update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
Update SimOpt constraint during solve (disconnected from optimization updates).
virtual void setSolveParameters (ParameterList &parlist)
Set solve parameters.
virtual void applyAdjointJacobian_1 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the primary interface.
virtual void applyAdjointJacobian_2 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol)
Approximately solves the augmented system
virtual void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C})\), to vector \(v\). In general, this preconditioner satisfies the following relationship:
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update constraint function.
virtual void value (Vector< Real > &c, const Vector< Real > &x, Real &tol)
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
virtual void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual void applyAdjointHessian (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
virtual Real checkSolve (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &c, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian_1 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
virtual Real checkAdjointConsistencyJacobian_1 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual Real checkAdjointConsistencyJacobian_2 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
virtual Real checkAdjointConsistencyJacobian_2 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual Real checkInverseJacobian_1 (const Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkInverseAdjointJacobian_1 (const Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
std::vector< std::vector< Real > > checkApplyJacobian_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Public Member Functions inherited from ROL::SerialFunction< Real >
SerialFunction (const Vector< Real > &u_initial, const TimeStampsPtr< Real > &timeStampsPtr)
size_type numTimeSteps () const
const Vector< Real > & getInitialCondition () const
void setInitialCondition (const Vector< Real > &u_initial)
const Vector< Real > & getZeroState () const
bool getSkipInitialCondition () const
void setSkipInitialCondition (bool skip)
TimeStampsPtr< Real > getTimeStampsPtr () const
void setTimeStampsPtr (const TimeStampsPtr< Real > &timeStampsPtr)
TimeStamp< Real > & getTimeStamp (size_type i)
const TimeStamp< Real > & getTimeStamp (size_type i) const
void setTimeStamp (size_type i, const TimeStamp< Real > &timeStamp)
Private Types
using PV = PartitionedVector< Real >
Private Attributes
Ptr< DynamicConstraint< Real > > con_
Additional Inherited Members
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Protected Member Functions inherited from ROL::SerialFunction< Real >
const TimeStamp< Real > & ts (size_type i) const
Ptr< Vector< Real > > clone (const Vector< Real > &x)
Protected Attributes inherited from ROL::Constraint_SimOpt< Real >
Real atol_
Real rtol_
Real stol_
Real factor_
Real decr_
int maxit_
bool print_
bool zero_
int solverType_
bool firstSolve_
Detailed Description
template<typename Real>
class ROL::SerialConstraint< Real >
Evaluates ROL::DynamicConstraint over a sequential set of time intervals.
Definition at line 30 of file ROL_SerialConstraint.hpp.
Member Typedef Documentation
PV
template<typename Real > using ROL::SerialConstraint< Real >::PV = PartitionedVector<Real> private
Definition at line 34 of file ROL_SerialConstraint.hpp.
size_type
template<typename Real > using ROL::SerialConstraint< Real >::size_type = typename std::vector<Real>::size_type
Definition at line 42 of file ROL_SerialConstraint.hpp.
Constructor & Destructor Documentation
SerialConstraint()
template<typename Real > ROL::SerialConstraint< Real >::SerialConstraint (const Ptr< DynamicConstraint< Real > > & con, const Vector< Real > & u_initial, const TimeStampsPtr< Real > & timeStampsPtr) inline
Definition at line 48 of file ROL_SerialConstraint.hpp.
Member Function Documentation
solve()
template<typename Real > virtual void ROL::SerialConstraint< Real >::solve (Vector< Real > & c, Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Given \(z\), solve \(c(u,z)=0\) for \(u\).
   @param[out]      c   is the result of evaluating the constraint operator at @b \f$(u,z)\f$; a constraint-space vector
   @param[in,out]   u   is the solution vector; a simulation-space vector
   @param[in]       z   is the constraint argument; an optimization-space vector
   @param[in,out]   tol is a tolerance for inexact evaluations; currently unused
   The defualt implementation is Newton's method globalized with a backtracking line search.
   ---
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 54 of file ROL_SerialConstraint.hpp.
References ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getInitialCondition(), ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
update()
template<typename Real > virtual void ROL::SerialConstraint< Real >::update (const Vector< Real > & u, const Vector< Real > & z, bool flag = true, int iter = -1) inline override virtual
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 71 of file ROL_SerialConstraint.hpp.
References ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getInitialCondition(), ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
value()
template<typename Real > virtual void ROL::SerialConstraint< Real >::value (Vector< Real > & c, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Evaluate the constraint operator \(c:\mathcal{U}\times\mathcal{Z} \rightarrow \mathcal{C}\) at \((u,z)\).
Parameters
[out] c is the result of evaluating the constraint operator at \((u,z)\); a constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(u,z)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{u} \in \mathcal{U}\), and $ \(\mathsf{z} \in\mathcal{Z}\).
Implements ROL::Constraint_SimOpt< Real >.
Definition at line 84 of file ROL_SerialConstraint.hpp.
References ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getInitialCondition(), ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyJacobian_1()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyJacobian_1 (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the partial constraint Jacobian at \((u,z)\), \(c_u(u,z) \in L(\mathcal{U}, \mathcal{C})\), to the vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at \((u,z)\); a constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; an simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c_u(u,z)v\), where \(v \in \mathcal{U}\), \(\mathsf{jv} \in \mathcal{C}\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 102 of file ROL_SerialConstraint.hpp.
References ROL::SerialFunction< Real >::clone(), ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::getZeroState(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyInverseJacobian_1()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyInverseJacobian_1 (Vector< Real > & ijv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the inverse partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-1} \in L(\mathcal{C}, \mathcal{U})\), to the vector \(v\).
Parameters
[out] ijv is the result of applying the inverse constraint Jacobian to v at \((u,z)\); a simulation-space vector
[in] v is a constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ijv} = c_u(u,z)^{-1}v\), where \(v \in \mathcal{C}\), \(\mathsf{ijv} \in \mathcal{U}\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 128 of file ROL_SerialConstraint.hpp.
References ROL::SerialFunction< Real >::clone(), ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::getZeroState(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyAdjointJacobian_1()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyAdjointJacobian_1 (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & dualv, Real & tol) inline override virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at (u,z); a dual simulation-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] dualv is a vector used for temporary variables; a constraint-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_u(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 157 of file ROL_SerialConstraint.hpp.
References ROL::SerialFunction< Real >::clone(), ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::getZeroState(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyInverseAdjointJacobian_1()
template<typename Real > void ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1 (Vector< Real > & iajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the inverse of the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-*} \in L(\mathcal{U}^*, \mathcal{C}^*)\), to the vector \(v\).
Parameters
[out] iajv is the result of applying the inverse adjoint of the constraint Jacobian to v at (u,z); a dual constraint-space vector
[in] v is a dual simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{iajv} = c_u(u,z)^{-*}v\), where \(v \in \mathcal{U}^*\), \(\mathsf{iajv} \in \mathcal{C}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 183 of file ROL_SerialConstraint.hpp.
References ROL::SerialFunction< Real >::clone(), ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::getZeroState(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyJacobian_2()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyJacobian_2 (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the partial constraint Jacobian at \((u,z)\), \(c_z(u,z) \in L(\mathcal{Z}, \mathcal{C})\), to the vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at \((u,z)\); a constraint-space vector
[in] v is an optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c_z(u,z)v\), where \(v \in \mathcal{Z}\), \(\mathsf{jv} \in \mathcal{C}\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 221 of file ROL_SerialConstraint.hpp.
References ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getInitialCondition(), ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyAdjointJacobian_2()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyAdjointJacobian_2 (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the primary interface.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at \((u,z)\); a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_z(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{Z}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 240 of file ROL_SerialConstraint.hpp.
References ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getInitialCondition(), ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyAdjointHessian_11()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyAdjointHessian_11 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 259 of file ROL_SerialConstraint.hpp.
References ROL::SerialFunction< Real >::clone(), ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getSkipInitialCondition(), ROL::SerialFunction< Real >::getZeroState(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
applyAdjointHessian_12()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyAdjointHessian_12 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the optimization-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uz}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the optimization-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual optimization-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uz}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{Z}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 301 of file ROL_SerialConstraint.hpp.
applyAdjointHessian_21()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyAdjointHessian_21 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the simulation-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{zu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{Z}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 310 of file ROL_SerialConstraint.hpp.
applyAdjointHessian_22()
template<typename Real > virtual void ROL::SerialConstraint< Real >::applyAdjointHessian_22 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline override virtual
Apply the optimization-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zz}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the optimization-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual optimization-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{zz}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{Z}\), and \(\mathsf{ahwv} \in \mathcal{Z}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 318 of file ROL_SerialConstraint.hpp.
References ROL::SerialConstraint< Real >::con_, ROL::SerialFunction< Real >::getInitialCondition(), ROL::SerialFunction< Real >::numTimeSteps(), ROL::partition(), and ROL::SerialFunction< Real >::ts().
Member Data Documentation
con_
template<typename Real > Ptr<DynamicConstraint<Real> > ROL::SerialConstraint< Real >::con_ private
Definition at line 38 of file ROL_SerialConstraint.hpp.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_11(), ROL::SerialConstraint< Real >::applyAdjointHessian_22(), ROL::SerialConstraint< Real >::applyAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyAdjointJacobian_2(), ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_2(), ROL::SerialConstraint< Real >::solve(), ROL::SerialConstraint< Real >::update(), and ROL::SerialConstraint< Real >::value().
The documentation for this class was generated from the following file:
ROL_SerialConstraint.hpp