ROL: ROL::SemismoothNewtonProjection< Real >::Precond Class Reference
ROL::SemismoothNewtonProjection< Real >::Precond Class Reference
Public Member Functions
Precond (Real alpha=1e-4)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Attributes
const Real alpha_
Detailed Description
template<typename Real>
class ROL::SemismoothNewtonProjection< Real >::Precond
Definition at line 90 of file ROL_SemismoothNewtonProjection.hpp.
Constructor & Destructor Documentation
Precond()
template<typename Real > ROL::SemismoothNewtonProjection< Real >::Precond::Precond (Real alpha = 1e-4) inline
Definition at line 94 of file ROL_SemismoothNewtonProjection.hpp.
Member Function Documentation
apply()
template<typename Real > void ROL::SemismoothNewtonProjection< Real >::Precond::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 95 of file ROL_SemismoothNewtonProjection.hpp.
References ROL::SemismoothNewtonProjection< Real >::Precond::alpha_, ROL::Vector< Real >::dual(), ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
applyInverse()
template<typename Real > void ROL::SemismoothNewtonProjection< Real >::Precond::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 100 of file ROL_SemismoothNewtonProjection.hpp.
References ROL::SemismoothNewtonProjection< Real >::Precond::alpha_, ROL::Vector< Real >::dual(), ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
Member Data Documentation
alpha_
template<typename Real > const Real ROL::SemismoothNewtonProjection< Real >::Precond::alpha_ private
Definition at line 92 of file ROL_SemismoothNewtonProjection.hpp.
Referenced by ROL::SemismoothNewtonProjection< Real >::Precond::apply(), and ROL::SemismoothNewtonProjection< Real >::Precond::applyInverse().
The documentation for this class was generated from the following file:
ROL_SemismoothNewtonProjection.hpp