ROL: ROL::AtomVector< Real > Class Template Reference
ROL::AtomVector< Real > Class Template Reference
Provides the std::vector implementation of the ROL::Vector interface.
#include <ROL_AtomVector.hpp>
Public Member Functions
AtomVector (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BatchManager< Real > > &bman, const int numMySamples, const int dimension)
ROL::Ptr< const std::vector< Real > > getAtom (const int i) const
void setAtom (const int i, const std::vector< Real > &pt)
int getNumMyAtoms (void) const
int getDimension (void) const
Public Member Functions inherited from ROL::BatchStdVector< Real >
BatchStdVector (const Ptr< std::vector< Real > > &vec, const Ptr< BatchManager< Real > > &bman)
virtual Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
virtual Ptr< Vector< Real > > clone (void) const
Clone to make a new (uninitialized) vector.
int dimension (void) const
Return dimension of the vector space.
Real reduce (const Elementwise::ReductionOp< Real > &r) const
const Ptr< BatchManager< Real > > getBatchManager (void) const
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual const Vector & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Real >::size_type uint
Private Attributes
const int numMySamples_
const int dimension_
Detailed Description
template<class Real>
class ROL::AtomVector< Real >
Provides the std::vector implementation of the ROL::Vector interface.
Definition at line 29 of file ROL_AtomVector.hpp.
Member Typedef Documentation
uint
template<class Real > typedef std::vector<Real>::size_type ROL::AtomVector< Real >::uint private
Definition at line 30 of file ROL_AtomVector.hpp.
Constructor & Destructor Documentation
AtomVector()
template<class Real > ROL::AtomVector< Real >::AtomVector (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BatchManager< Real > > & bman, const int numMySamples, const int dimension) inline
Definition at line 36 of file ROL_AtomVector.hpp.
Member Function Documentation
getAtom()
template<class Real > ROL::Ptr< const std::vector< Real > > ROL::AtomVector< Real >::getAtom (const int i) const inline
Definition at line 42 of file ROL_AtomVector.hpp.
References dim, ROL::AtomVector< Real >::dimension_, ROL::StdVector< Real, Element >::getVector(), and ROL::AtomVector< Real >::numMySamples_.
Referenced by ROL::CDFObjective< Real >::gradientCDF(), ROL::CDFObjective< Real >::hessVecCDF(), ROL::MomentObjective< Real >::momentGradient(), ROL::MomentObjective< Real >::momentHessVec(), ROL::MomentObjective< Real >::momentValue(), ROL::SROMGenerator< Real >::pruneSamples(), and ROL::CDFObjective< Real >::valueCDF().
setAtom()
template<class Real > void ROL::AtomVector< Real >::setAtom (const int i, const std::vector< Real > & pt) inline
Definition at line 54 of file ROL_AtomVector.hpp.
References dim, ROL::AtomVector< Real >::dimension_, ROL::StdVector< Real, Element >::getVector(), and ROL::AtomVector< Real >::numMySamples_.
Referenced by ROL::CDFObjective< Real >::gradient(), ROL::MomentObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), and ROL::MomentObjective< Real >::hessVec().
getNumMyAtoms()
template<class Real > int ROL::AtomVector< Real >::getNumMyAtoms (void) const inline
Definition at line 64 of file ROL_AtomVector.hpp.
References ROL::AtomVector< Real >::numMySamples_.
Referenced by ROL::PrimalAtomVector< Real >::clone(), ROL::DualAtomVector< Real >::clone(), ROL::PrimalAtomVector< Real >::dot(), ROL::DualAtomVector< Real >::dot(), ROL::PrimalAtomVector< Real >::dual(), and ROL::DualAtomVector< Real >::dual().
getDimension()
template<class Real > int ROL::AtomVector< Real >::getDimension (void) const inline
Definition at line 68 of file ROL_AtomVector.hpp.
References ROL::AtomVector< Real >::dimension_.
Referenced by ROL::PrimalAtomVector< Real >::clone(), ROL::DualAtomVector< Real >::clone(), ROL::PrimalAtomVector< Real >::dot(), ROL::DualAtomVector< Real >::dot(), ROL::PrimalAtomVector< Real >::dual(), and ROL::DualAtomVector< Real >::dual().
Member Data Documentation
numMySamples_
template<class Real > const int ROL::AtomVector< Real >::numMySamples_ private
Definition at line 32 of file ROL_AtomVector.hpp.
Referenced by ROL::AtomVector< Real >::getAtom(), ROL::AtomVector< Real >::getNumMyAtoms(), and ROL::AtomVector< Real >::setAtom().
dimension_
template<class Real > const int ROL::AtomVector< Real >::dimension_ private
Definition at line 33 of file ROL_AtomVector.hpp.
Referenced by ROL::AtomVector< Real >::getAtom(), ROL::AtomVector< Real >::getDimension(), and ROL::AtomVector< Real >::setAtom().
The documentation for this class was generated from the following file:
ROL_AtomVector.hpp