ROL: ROL::StdObjective< Real > Class Template Reference
ROL::StdObjective< Real > Class Template Reference abstract
User Interface » Functional Interface
Specializes the ROL::Objective interface for objective functions that operate on ROL::StdVector's.
#include <ROL_StdObjective.hpp>
Public Member Functions
virtual void update (const std::vector< Real > &x, bool flag=true, int iter=-1)
void update (const Vector< Real > &x, bool flag=true, int iter=-1) override
Update objective function.
virtual void update (const std::vector< Real > &x, UpdateType type, int iter=-1)
void update (const Vector< Real > &x, UpdateType type, int iter=-1) override
Update objective function.
virtual Real value (const std::vector< Real > &x, Real &tol)=0
Real value (const Vector< Real > &x, Real &tol) override
Compute value.
virtual void gradient (std::vector< Real > &g, const std::vector< Real > &x, Real &tol)
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol) override
Compute gradient.
virtual Real dirDeriv (const std::vector< Real > &x, const std::vector< Real > &d, Real &tol)
Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol) override
Compute directional derivative.
virtual void hessVec (std::vector< Real > &hv, const std::vector< Real > &v, const std::vector< Real > &x, Real &tol)
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply Hessian approximation to vector.
virtual void invHessVec (std::vector< Real > &hv, const std::vector< Real > &v, const std::vector< Real > &x, Real &tol)
void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply inverse Hessian approximation to vector.
virtual void precond (std::vector< Real > &Pv, const std::vector< Real > &v, const std::vector< Real > &x, Real &tol)
void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply preconditioner to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Member Functions
Real sgn (Real x) const
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::StdObjective< Real >
Specializes the ROL::Objective interface for objective functions that operate on ROL::StdVector's.
Definition at line 26 of file ROL_StdObjective.hpp.
Member Function Documentation
update() [1/4]
template<typename Real > virtual void ROL::StdObjective< Real >::update (const std::vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Definition at line 28 of file ROL_StdObjective.hpp.
update() [2/4]
template<typename Real > void ROL::StdObjective< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 16 of file ROL_StdObjective_Def.hpp.
References ROL::StdVector< Real, Element >::getVector(), and ROL::update().
update() [3/4]
template<typename Real > virtual void ROL::StdObjective< Real >::update (const std::vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Definition at line 33 of file ROL_StdObjective.hpp.
update() [4/4]
template<typename Real > void ROL::StdObjective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 22 of file ROL_StdObjective_Def.hpp.
References ROL::StdVector< Real, Element >::getVector(), and ROL::update().
value() [1/2]
template<typename Real > virtual Real ROL::StdObjective< Real >::value (const std::vector< Real > & x, Real & tol) pure virtual
Implemented in ROL::RegressionError< Real >, ROL::ZOO::Objective_Cantilever< Real >, ROL::ZOO::Objective_CantileverBeam< Real >, ROL::ZOO::Objective_Cubic< Real >, ROL::ZOO::Objective_CylinderHead< Real >, ROL::ZOO::Objective_HS14< Real >, ROL::ZOO::Objective_HS21< Real >, ROL::ZOO::Objective_HS28< Real >, ROL::ZOO::Objective_HS41< Real >, ROL::ZOO::Objective_HS42< Real >, ROL::ZOO::Objective_HS48< Real >, ROL::ZOO::Objective_HS49< Real >, ROL::ZOO::Objective_HS50< Real >, ROL::ZOO::Objective_HS51< Real >, ROL::ZOO::Objective_HS52< Real >, ROL::ZOO::Objective_HS53< Real >, ROL::ZOO::Objective_HS55< Real >, ROL::ZOO::Objective_HS63< Real >, ROL::ZOO::Objective_HS9< Real >, ROL::ZOO::Objective_Quartic< Real >, ObjectiveFunctionTest06< Real >, ObjectiveFunctionTest07_1< Real >, ObjectiveFunctionTest07_2< Real >, ObjectiveFunctionTest07_scalarize< Real >, and ObjectiveFunctionTest08_scalarize< Real >.
value() [2/2]
template<typename Real > Real ROL::StdObjective< Real >::value (const Vector< Real > & x, Real & tol) override virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 28 of file ROL_StdObjective_Def.hpp.
References ROL::StdVector< Real, Element >::getVector(), and ROL::value().
gradient() [1/2]
template<typename Real > void ROL::StdObjective< Real >::gradient (std::vector< Real > & g, const std::vector< Real > & x, Real & tol) virtual
Reimplemented in ROL::RegressionError< Real >, ROL::ZOO::Objective_Cantilever< Real >, ROL::ZOO::Objective_CantileverBeam< Real >, ROL::ZOO::Objective_Cubic< Real >, ROL::ZOO::Objective_CylinderHead< Real >, ROL::ZOO::Objective_HS14< Real >, ROL::ZOO::Objective_HS21< Real >, ROL::ZOO::Objective_HS28< Real >, ROL::ZOO::Objective_HS41< Real >, ROL::ZOO::Objective_HS42< Real >, ROL::ZOO::Objective_HS48< Real >, ROL::ZOO::Objective_HS49< Real >, ROL::ZOO::Objective_HS50< Real >, ROL::ZOO::Objective_HS51< Real >, ROL::ZOO::Objective_HS52< Real >, ROL::ZOO::Objective_HS53< Real >, ROL::ZOO::Objective_HS55< Real >, ROL::ZOO::Objective_HS63< Real >, ROL::ZOO::Objective_HS9< Real >, ROL::ZOO::Objective_Quartic< Real >, ObjectiveFunctionTest06< Real >, ObjectiveFunctionTest07_1< Real >, ObjectiveFunctionTest07_2< Real >, ObjectiveFunctionTest07_scalarize< Real >, and ObjectiveFunctionTest08_scalarize< Real >.
Definition at line 34 of file ROL_StdObjective_Def.hpp.
References ROL::update(), and ROL::value().
gradient() [2/2]
template<typename Real > void ROL::StdObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) override virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 53 of file ROL_StdObjective_Def.hpp.
References ROL::StdVector< Real, Element >::getVector().
dirDeriv() [1/2]
template<typename Real > Real ROL::StdObjective< Real >::dirDeriv (const std::vector< Real > & x, const std::vector< Real > & d, Real & tol) virtual
Definition at line 60 of file ROL_StdObjective_Def.hpp.
dirDeriv() [2/2]
template<typename Real > Real ROL::StdObjective< Real >::dirDeriv (const Vector< Real > & x, const Vector< Real > & d, Real & tol) override virtual
Compute directional derivative.
This function returns the directional derivative of the objective function in the \(d\) direction.
Parameters
[in] x is the current iterate.
[in] d is the direction.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 66 of file ROL_StdObjective_Def.hpp.
References ROL::Objective< Real >::dirDeriv(), and ROL::StdVector< Real, Element >::getVector().
hessVec() [1/2]
template<typename Real > void ROL::StdObjective< Real >::hessVec (std::vector< Real > & hv, const std::vector< Real > & v, const std::vector< Real > & x, Real & tol) virtual
Reimplemented in ROL::RegressionError< Real >, ROL::ZOO::Objective_CantileverBeam< Real >, ROL::ZOO::Objective_HS14< Real >, ROL::ZOO::Objective_HS21< Real >, ROL::ZOO::Objective_HS28< Real >, ROL::ZOO::Objective_HS41< Real >, ROL::ZOO::Objective_HS42< Real >, ROL::ZOO::Objective_HS48< Real >, ROL::ZOO::Objective_HS49< Real >, ROL::ZOO::Objective_HS50< Real >, ROL::ZOO::Objective_HS51< Real >, ROL::ZOO::Objective_HS52< Real >, ROL::ZOO::Objective_HS53< Real >, ROL::ZOO::Objective_HS55< Real >, ROL::ZOO::Objective_HS63< Real >, ROL::ZOO::Objective_HS9< Real >, ObjectiveFunctionTest06< Real >, ObjectiveFunctionTest07_1< Real >, ObjectiveFunctionTest07_2< Real >, ObjectiveFunctionTest07_scalarize< Real >, and ObjectiveFunctionTest08_scalarize< Real >.
Definition at line 78 of file ROL_StdObjective_Def.hpp.
hessVec() [2/2]
template<typename Real > void ROL::StdObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 84 of file ROL_StdObjective_Def.hpp.
References ROL::StdVector< Real, Element >::getVector(), and ROL::Objective< Real >::hessVec().
invHessVec() [1/2]
template<typename Real > void ROL::StdObjective< Real >::invHessVec (std::vector< Real > & hv, const std::vector< Real > & v, const std::vector< Real > & x, Real & tol) virtual
Reimplemented in ROL::ZOO::Objective_Cubic< Real >.
Definition at line 97 of file ROL_StdObjective_Def.hpp.
invHessVec() [2/2]
template<typename Real > void ROL::StdObjective< Real >::invHessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 103 of file ROL_StdObjective_Def.hpp.
References ROL::StdVector< Real, Element >::getVector().
precond() [1/2]
template<typename Real > void ROL::StdObjective< Real >::precond (std::vector< Real > & Pv, const std::vector< Real > & v, const std::vector< Real > & x, Real & tol) virtual
Definition at line 111 of file ROL_StdObjective_Def.hpp.
precond() [2/2]
template<typename Real > void ROL::StdObjective< Real >::precond (Vector< Real > & Pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 116 of file ROL_StdObjective_Def.hpp.
References ROL::StdVector< Real, Element >::getVector().
sgn()
template<typename Real > Real ROL::StdObjective< Real >::sgn (Real x) const private
Definition at line 124 of file ROL_StdObjective_Def.hpp.
References zero.
The documentation for this class was generated from the following files:
ROL_StdObjective.hpp
ROL_StdObjective_Def.hpp