ROL: ROL::LineSearch_U< Real > Class Template Reference
ROL::LineSearch_U< Real > Class Template Reference abstract
Provides interface for and implements line searches.
#include <ROL_LineSearch_U.hpp>
Public Member Functions
virtual ~LineSearch_U ()
LineSearch_U (ParameterList &parlist)
virtual void initialize (const Vector< Real > &x, const Vector< Real > &g)
virtual void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj)=0
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Protected Member Functions
virtual bool status (const ELineSearchU type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj)
void setNextInitialAlpha (Real alpha)
bool useLocalMinimizer ()
bool takeNoStep ()
Private Member Functions
Real dirDeriv (const Vector< Real > &x, const Vector< Real > &s, const Real alpha, const Real fnew, Objective< Real > &obj)
Private Attributes
ECurvatureConditionU econd_
EDescentU edesc_
bool useralpha_
bool usePrevAlpha_
Real alpha0_
Real alpha0bnd_
int maxit_
Real c1_
Real c2_
Real c3_
Real eps_
Real fmin_
Real alphaMin_
bool acceptMin_
bool itcond_
bool FDdirDeriv_
Ptr< Vector< Real > > xtst_
Detailed Description
template<typename Real>
class ROL::LineSearch_U< Real >
Provides interface for and implements line searches.
Definition at line 27 of file ROL_LineSearch_U.hpp.
Constructor & Destructor Documentation
~LineSearch_U()
template<typename Real > virtual ROL::LineSearch_U< Real >::~LineSearch_U () inline virtual
Definition at line 78 of file ROL_LineSearch_U.hpp.
LineSearch_U()
template<typename Real > ROL::LineSearch_U< Real >::LineSearch_U (ParameterList & parlist) inline
Definition at line 81 of file ROL_LineSearch_U.hpp.
References ROL::LineSearch_U< Real >::acceptMin_, ROL::LineSearch_U< Real >::alpha0_, ROL::LineSearch_U< Real >::alpha0bnd_, ROL::LineSearch_U< Real >::alphaMin_, ROL::LineSearch_U< Real >::c1_, ROL::LineSearch_U< Real >::c2_, ROL::LineSearch_U< Real >::c3_, ROL::DESCENT_U_NONLINEARCG, ROL::LineSearch_U< Real >::econd_, ROL::LineSearch_U< Real >::edesc_, ROL::LineSearch_U< Real >::FDdirDeriv_, ROL::LineSearch_U< Real >::fmin_, ROL::LineSearch_U< Real >::itcond_, ROL::LineSearch_U< Real >::maxit_, ROL::StringToECurvatureConditionU(), ROL::StringToEDescentU(), ROL::LineSearch_U< Real >::usePrevAlpha_, ROL::LineSearch_U< Real >::useralpha_, and zero.
Member Function Documentation
dirDeriv()
template<typename Real > Real ROL::LineSearch_U< Real >::dirDeriv (const Vector< Real > & x, const Vector< Real > & s, const Real alpha, const Real fnew, Objective< Real > & obj) inline private
Definition at line 50 of file ROL_LineSearch_U.hpp.
References ROL::Objective< Real >::dirDeriv(), ROL::LineSearch_U< Real >::FDdirDeriv_, ROL::Vector< Real >::norm(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::LineSearch_U< Real >::xtst_.
Referenced by ROL::LineSearch_U< Real >::status().
initialize()
template<typename Real > virtual void ROL::LineSearch_U< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g) inline virtual
Reimplemented in ROL::BackTracking_U< Real >, ROL::CubicInterp_U< Real >, ROL::IterationScaling_U< Real >, ROL::PathBasedTargetLevel_U< Real >, and ROL::ScalarMinimizationLineSearch_U< Real >.
Definition at line 117 of file ROL_LineSearch_U.hpp.
References ROL::Vector< Real >::clone(), and ROL::LineSearch_U< Real >::xtst_.
Referenced by ROL::BackTracking_U< Real >::initialize(), ROL::CubicInterp_U< Real >::initialize(), ROL::IterationScaling_U< Real >::initialize(), ROL::PathBasedTargetLevel_U< Real >::initialize(), and ROL::ScalarMinimizationLineSearch_U< Real >::initialize().
run()
template<typename Real > virtual void ROL::LineSearch_U< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj) pure virtual
Implemented in ROL::BackTracking_U< Real >, ROL::CubicInterp_U< Real >, ROL::IterationScaling_U< Real >, ROL::PathBasedTargetLevel_U< Real >, and ROL::ScalarMinimizationLineSearch_U< Real >.
setMaxitUpdate()
template<typename Real > void ROL::LineSearch_U< Real >::setMaxitUpdate (Real & alpha, Real & fnew, const Real & fold) inline
Definition at line 127 of file ROL_LineSearch_U.hpp.
References ROL::LineSearch_U< Real >::acceptMin_, ROL::LineSearch_U< Real >::alphaMin_, ROL::LineSearch_U< Real >::fmin_, ROL::LineSearch_U< Real >::itcond_, and ROL::LineSearch_U< Real >::setNextInitialAlpha().
status()
template<typename Real > virtual bool ROL::LineSearch_U< Real >::status (const ELineSearchU type, int & ls_neval, int & ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj) inline protected virtual
Definition at line 142 of file ROL_LineSearch_U.hpp.
References ROL::LineSearch_U< Real >::alphaMin_, ROL::LineSearch_U< Real >::c1_, ROL::LineSearch_U< Real >::c2_, ROL::LineSearch_U< Real >::c3_, ROL::CURVATURECONDITION_U_APPROXIMATEWOLFE, ROL::CURVATURECONDITION_U_GENERALIZEDWOLFE, ROL::CURVATURECONDITION_U_GOLDSTEIN, ROL::CURVATURECONDITION_U_NULL, ROL::CURVATURECONDITION_U_STRONGWOLFE, ROL::CURVATURECONDITION_U_WOLFE, ROL::DESCENT_U_NONLINEARCG, ROL::LineSearch_U< Real >::dirDeriv(), ROL::LineSearch_U< Real >::econd_, ROL::LineSearch_U< Real >::edesc_, ROL::LineSearch_U< Real >::fmin_, ROL::LineSearch_U< Real >::itcond_, ROL::LINESEARCH_U_BACKTRACKING, ROL::LINESEARCH_U_CUBICINTERP, and ROL::LineSearch_U< Real >::maxit_.
Referenced by ROL::BackTracking_U< Real >::run(), and ROL::CubicInterp_U< Real >::run().
getInitialAlpha()
template<typename Real > virtual Real ROL::LineSearch_U< Real >::getInitialAlpha (int & ls_neval, int & ls_ngrad, const Real fval, const Real gs, const Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj) inline protected virtual
Definition at line 205 of file ROL_LineSearch_U.hpp.
References ROL::LineSearch_U< Real >::alpha0_, ROL::LineSearch_U< Real >::alpha0bnd_, ROL::DESCENT_U_NONLINEARCG, ROL::DESCENT_U_STEEPEST, ROL::LineSearch_U< Real >::edesc_, ROL::Trial, ROL::Objective< Real >::update(), ROL::LineSearch_U< Real >::usePrevAlpha_, ROL::LineSearch_U< Real >::useralpha_, ROL::Objective< Real >::value(), and ROL::LineSearch_U< Real >::xtst_.
Referenced by ROL::BackTracking_U< Real >::run(), ROL::CubicInterp_U< Real >::run(), ROL::IterationScaling_U< Real >::run(), and ROL::ScalarMinimizationLineSearch_U< Real >::run().
setNextInitialAlpha()
template<typename Real > void ROL::LineSearch_U< Real >::setNextInitialAlpha (Real alpha) inline protected
Definition at line 233 of file ROL_LineSearch_U.hpp.
References ROL::LineSearch_U< Real >::alpha0_, and ROL::LineSearch_U< Real >::usePrevAlpha_.
Referenced by ROL::ScalarMinimizationLineSearch_U< Real >::run(), and ROL::LineSearch_U< Real >::setMaxitUpdate().
useLocalMinimizer()
template<typename Real > bool ROL::LineSearch_U< Real >::useLocalMinimizer () inline protected
Definition at line 239 of file ROL_LineSearch_U.hpp.
References ROL::LineSearch_U< Real >::acceptMin_, and ROL::LineSearch_U< Real >::itcond_.
takeNoStep()
template<typename Real > bool ROL::LineSearch_U< Real >::takeNoStep () inline protected
Definition at line 243 of file ROL_LineSearch_U.hpp.
References ROL::LineSearch_U< Real >::acceptMin_, and ROL::LineSearch_U< Real >::itcond_.
Member Data Documentation
econd_
template<typename Real > ECurvatureConditionU ROL::LineSearch_U< Real >::econd_ private
Definition at line 30 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::status().
edesc_
template<typename Real > EDescentU ROL::LineSearch_U< Real >::edesc_ private
Definition at line 31 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::getInitialAlpha(), ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::status().
useralpha_
template<typename Real > bool ROL::LineSearch_U< Real >::useralpha_ private
Definition at line 33 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::getInitialAlpha(), and ROL::LineSearch_U< Real >::LineSearch_U().
usePrevAlpha_
template<typename Real > bool ROL::LineSearch_U< Real >::usePrevAlpha_ private
Definition at line 34 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::getInitialAlpha(), ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::setNextInitialAlpha().
alpha0_
template<typename Real > Real ROL::LineSearch_U< Real >::alpha0_ private
Definition at line 35 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::getInitialAlpha(), ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::setNextInitialAlpha().
alpha0bnd_
template<typename Real > Real ROL::LineSearch_U< Real >::alpha0bnd_ private
Definition at line 36 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::getInitialAlpha(), and ROL::LineSearch_U< Real >::LineSearch_U().
maxit_
template<typename Real > int ROL::LineSearch_U< Real >::maxit_ private
Definition at line 37 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::status().
c1_
template<typename Real > Real ROL::LineSearch_U< Real >::c1_ private
Definition at line 38 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::status().
c2_
template<typename Real > Real ROL::LineSearch_U< Real >::c2_ private
Definition at line 39 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::status().
c3_
template<typename Real > Real ROL::LineSearch_U< Real >::c3_ private
Definition at line 40 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), and ROL::LineSearch_U< Real >::status().
eps_
template<typename Real > Real ROL::LineSearch_U< Real >::eps_ private
Definition at line 41 of file ROL_LineSearch_U.hpp.
fmin_
template<typename Real > Real ROL::LineSearch_U< Real >::fmin_ private
Definition at line 42 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), ROL::LineSearch_U< Real >::setMaxitUpdate(), and ROL::LineSearch_U< Real >::status().
alphaMin_
template<typename Real > Real ROL::LineSearch_U< Real >::alphaMin_ private
Definition at line 43 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), ROL::LineSearch_U< Real >::setMaxitUpdate(), and ROL::LineSearch_U< Real >::status().
acceptMin_
template<typename Real > bool ROL::LineSearch_U< Real >::acceptMin_ private
Definition at line 44 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), ROL::LineSearch_U< Real >::setMaxitUpdate(), ROL::LineSearch_U< Real >::takeNoStep(), and ROL::LineSearch_U< Real >::useLocalMinimizer().
itcond_
template<typename Real > bool ROL::LineSearch_U< Real >::itcond_ private
Definition at line 45 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), ROL::LineSearch_U< Real >::setMaxitUpdate(), ROL::LineSearch_U< Real >::status(), ROL::LineSearch_U< Real >::takeNoStep(), and ROL::LineSearch_U< Real >::useLocalMinimizer().
FDdirDeriv_
template<typename Real > bool ROL::LineSearch_U< Real >::FDdirDeriv_ private
Definition at line 46 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::dirDeriv(), and ROL::LineSearch_U< Real >::LineSearch_U().
xtst_
template<typename Real > Ptr<Vector<Real> > ROL::LineSearch_U< Real >::xtst_ private
Definition at line 48 of file ROL_LineSearch_U.hpp.
Referenced by ROL::LineSearch_U< Real >::dirDeriv(), ROL::LineSearch_U< Real >::getInitialAlpha(), and ROL::LineSearch_U< Real >::initialize().
The documentation for this class was generated from the following file:
ROL_LineSearch_U.hpp