ROL: ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual > Class Template Reference
ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual > Class Template Reference
#include <ROL_SimpleEqConstrained.hpp>
Public Member Functions
getSimpleEqConstrained (void)
Ptr< Objective< Real > > getObjective (void) const
Ptr< Vector< Real > > getInitialGuess (void) const
Ptr< Vector< Real > > getSolution (const int i=0) const
Ptr< Constraint< Real > > getEqualityConstraint (void) const
Ptr< Vector< Real > > getEqualityMultiplier (void) const
Public Member Functions inherited from ROL::TestProblem< Real >
virtual ~TestProblem (void)
TestProblem (void)
virtual int getNumSolutions (void) const
virtual Ptr< BoundConstraint< Real > > getBoundConstraint (void) const
virtual Ptr< Constraint< Real > > getInequalityConstraint (void) const
virtual Ptr< Vector< Real > > getInequalityMultiplier (void) const
virtual Ptr< BoundConstraint< Real > > getSlackBoundConstraint (void) const
void get (Ptr< OptimizationProblem< Real > > &problem, Ptr< Vector< Real > > &x0, std::vector< Ptr< Vector< Real > > > &x) const
Private Types
typedef std::vector< Real > vector
typedef vector::size_type uint
Detailed Description
template<class Real, class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>>
class ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >
Definition at line 409 of file ROL_SimpleEqConstrained.hpp.
Member Typedef Documentation
vector
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> typedef std::vector<Real> ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::vector private
Definition at line 410 of file ROL_SimpleEqConstrained.hpp.
uint
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> typedef vector::size_type ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::uint private
Definition at line 411 of file ROL_SimpleEqConstrained.hpp.
Constructor & Destructor Documentation
getSimpleEqConstrained()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::getSimpleEqConstrained (void) inline
Definition at line 413 of file ROL_SimpleEqConstrained.hpp.
Member Function Documentation
getObjective()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> Ptr< Objective< Real > > ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::getObjective (void) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 415 of file ROL_SimpleEqConstrained.hpp.
Referenced by main().
getInitialGuess()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> Ptr< Vector< Real > > ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::getInitialGuess (void) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 420 of file ROL_SimpleEqConstrained.hpp.
Referenced by main().
getSolution()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> Ptr< Vector< Real > > ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::getSolution (const int i = 0) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 432 of file ROL_SimpleEqConstrained.hpp.
Referenced by main().
getEqualityConstraint()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> Ptr< Constraint< Real > > ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::getEqualityConstraint (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 444 of file ROL_SimpleEqConstrained.hpp.
Referenced by main().
getEqualityMultiplier()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>, class CPrim = StdVector<Real>, class CDual = StdVector<Real>> Ptr< Vector< Real > > ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >::getEqualityMultiplier (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 449 of file ROL_SimpleEqConstrained.hpp.
The documentation for this class was generated from the following file:
ROL_SimpleEqConstrained.hpp