ROL: ROL::IterationScaling_U< Real > Class Template Reference
ROL::IterationScaling_U< Real > Class Template Reference
Provides an implementation of iteration scaled line search.
#include <ROL_IterationScaling_U.hpp>
Public Member Functions
IterationScaling_U (ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &g) override
void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj) override
Public Member Functions inherited from ROL::LineSearch_U< Real >
virtual ~LineSearch_U ()
LineSearch_U (ParameterList &parlist)
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Private Attributes
int algo_iter_
Ptr< Vector< Real > > xnew_
Additional Inherited Members
Protected Member Functions inherited from ROL::LineSearch_U< Real >
virtual bool status (const ELineSearchU type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj)
void setNextInitialAlpha (Real alpha)
bool useLocalMinimizer ()
bool takeNoStep ()
Detailed Description
template<typename Real>
class ROL::IterationScaling_U< Real >
Provides an implementation of iteration scaled line search.
Definition at line 22 of file ROL_IterationScaling_U.hpp.
Constructor & Destructor Documentation
IterationScaling_U()
template<typename Real > ROL::IterationScaling_U< Real >::IterationScaling_U (ParameterList & parlist) inline
Definition at line 31 of file ROL_IterationScaling_U.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::IterationScaling_U< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g) inline override virtual
Reimplemented from ROL::LineSearch_U< Real >.
Definition at line 33 of file ROL_IterationScaling_U.hpp.
References ROL::Vector< Real >::clone(), ROL::LineSearch_U< Real >::initialize(), and ROL::IterationScaling_U< Real >::xnew_.
run()
template<typename Real > void ROL::IterationScaling_U< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj) inline override virtual
Implements ROL::LineSearch_U< Real >.
Definition at line 39 of file ROL_IterationScaling_U.hpp.
References ROL::IterationScaling_U< Real >::algo_iter_, ROL::LineSearch_U< Real >::getInitialAlpha(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::IterationScaling_U< Real >::xnew_.
Member Data Documentation
algo_iter_
template<typename Real > int ROL::IterationScaling_U< Real >::algo_iter_ private
Definition at line 24 of file ROL_IterationScaling_U.hpp.
Referenced by ROL::IterationScaling_U< Real >::run().
xnew_
template<typename Real > Ptr<Vector<Real> > ROL::IterationScaling_U< Real >::xnew_ private
Definition at line 25 of file ROL_IterationScaling_U.hpp.
Referenced by ROL::IterationScaling_U< Real >::initialize(), and ROL::IterationScaling_U< Real >::run().
The documentation for this class was generated from the following file:
ROL_IterationScaling_U.hpp