ROL: H1BoundConstraint< Real > Class Template Reference
H1BoundConstraint< Real > Class Template Reference
#include <example_04.hpp>
Public Member Functions
H1BoundConstraint (std::vector< Real > &l, std::vector< Real > &u, const ROL::Ptr< BurgersFEM< Real > > &fem, Real scale=1.0)
bool isFeasible (const ROL::Vector< Real > &x)
Check if the vector, v, is feasible.
void project (ROL::Vector< Real > &x)
Project optimization variables onto the bounds.
void pruneLowerActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
void pruneUpperActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
void pruneActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
void pruneLowerActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
void pruneUpperActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
void pruneActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
const ROL::Ptr< const ROL::Vector< Real > > getLowerBound (void) const
Return the ref count pointer to the lower bound vector.
const ROL::Ptr< const ROL::Vector< Real > > getUpperBound (void) const
Return the ref count pointer to the upper bound vector.
H1BoundConstraint (std::vector< Real > &l, std::vector< Real > &u, const ROL::Ptr< BurgersFEM< Real > > &fem, Real scale=1.0)
bool isFeasible (const ROL::Vector< Real > &x)
Check if the vector, v, is feasible.
void project (ROL::Vector< Real > &x)
Project optimization variables onto the bounds.
void pruneLowerActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
void pruneUpperActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
void pruneActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
void pruneLowerActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
void pruneUpperActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
void pruneActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
const ROL::Ptr< const ROL::Vector< Real > > getLowerBound (void) const
Return the ref count pointer to the lower bound vector.
const ROL::Ptr< const ROL::Vector< Real > > getUpperBound (void) const
Return the ref count pointer to the upper bound vector.
H1BoundConstraint (std::vector< Real > &l, std::vector< Real > &u, const ROL::Ptr< BurgersFEM< Real > > &fem, Real scale=1.0)
bool isFeasible (const ROL::Vector< Real > &x)
Check if the vector, v, is feasible.
void project (ROL::Vector< Real > &x)
Project optimization variables onto the bounds.
void pruneLowerActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
void pruneUpperActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
void pruneActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &x, Real eps=Real(0))
void pruneLowerActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
void pruneUpperActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
void pruneActive (ROL::Vector< Real > &v, const ROL::Vector< Real > &g, const ROL::Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
const ROL::Ptr< const ROL::Vector< Real > > getLowerBound (void) const
Return the ref count pointer to the lower bound vector.
const ROL::Ptr< const ROL::Vector< Real > > getUpperBound (void) const
Return the ref count pointer to the upper bound vector.
Public Member Functions inherited from ROL::BoundConstraint< Real >
virtual ~BoundConstraint ()
BoundConstraint (void)
BoundConstraint (const Vector< Real > &x)
virtual void projectInterior (Vector< Real > &x)
Project optimization variables into the interior of the feasible set.
virtual void applyInverseScalingFunction (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const
Apply inverse scaling function.
virtual void applyScalingFunctionJacobian (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const
Apply scaling function Jacobian.
void activateLower (void)
Turn on lower bound.
void activateUpper (void)
Turn on upper bound.
void activate (void)
Turn on bounds.
void deactivateLower (void)
Turn off lower bound.
void deactivateUpper (void)
Turn off upper bound.
void deactivate (void)
Turn off bounds.
bool isLowerActivated (void) const
Check if lower bound are on.
bool isUpperActivated (void) const
Check if upper bound are on.
bool isActivated (void) const
Check if bounds are on.
void pruneActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-active set.
void pruneActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void computeProjectedGradient (Vector< Real > &g, const Vector< Real > &x)
Compute projected gradient.
void computeProjectedStep (Vector< Real > &v, const Vector< Real > &x)
Compute projected step.
Private Member Functions
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
void cast_const_vector (ROL::Ptr< const std::vector< Real > > &xvec, const ROL::Vector< Real > &x) const
void axpy (std::vector< Real > &out, const Real a, const std::vector< Real > &x, const std::vector< Real > &y) const
void projection (std::vector< Real > &x)
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
void cast_const_vector (ROL::Ptr< const std::vector< Real > > &xvec, const ROL::Vector< Real > &x) const
void axpy (std::vector< Real > &out, const Real a, const std::vector< Real > &x, const std::vector< Real > &y) const
void projection (std::vector< Real > &x)
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
void cast_const_vector (ROL::Ptr< const std::vector< Real > > &xvec, const ROL::Vector< Real > &x) const
void axpy (std::vector< Real > &out, const Real a, const std::vector< Real > &x, const std::vector< Real > &y) const
void projection (std::vector< Real > &x)
Private Attributes
int dim_
std::vector< Real > x_lo_
std::vector< Real > x_up_
Real min_diff_
Real scale_
ROL::Ptr< BurgersFEM< Real > > fem_
ROL::Ptr< ROL::Vector< Real > > l_
ROL::Ptr< ROL::Vector< Real > > u_
Additional Inherited Members
Protected Member Functions inherited from ROL::BoundConstraint< Real >
Real computeInf (const Vector< Real > &x) const
Protected Attributes inherited from ROL::BoundConstraint< Real >
Ptr< Vector< Real > > lower_
Ptr< Vector< Real > > upper_
Detailed Description
template<class Real>
class H1BoundConstraint< Real >
Definition at line 1302 of file example_04.hpp.
Constructor & Destructor Documentation
H1BoundConstraint() [1/3]
template<class Real > H1BoundConstraint< Real >::H1BoundConstraint (std::vector< Real > & l, std::vector< Real > & u, const ROL::Ptr< BurgersFEM< Real > > & fem, Real scale = 1.0) inline
Definition at line 1348 of file example_04.hpp.
References H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::l_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::u_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
H1BoundConstraint() [2/3]
template<class Real > H1BoundConstraint< Real >::H1BoundConstraint (std::vector< Real > & l, std::vector< Real > & u, const ROL::Ptr< BurgersFEM< Real > > & fem, Real scale = 1.0) inline
Definition at line 1429 of file example_07.hpp.
References H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::l_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::u_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
H1BoundConstraint() [3/3]
template<class Real > H1BoundConstraint< Real >::H1BoundConstraint (std::vector< Real > & l, std::vector< Real > & u, const ROL::Ptr< BurgersFEM< Real > > & fem, Real scale = 1.0) inline
Definition at line 1213 of file example_08.hpp.
References H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::l_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::u_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
Member Function Documentation
cast_vector() [1/3]
template<class Real > void H1BoundConstraint< Real >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1313 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::project(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneUpperActive(), and H1BoundConstraint< Real >::pruneUpperActive().
cast_const_vector() [1/3]
template<class Real > void H1BoundConstraint< Real >::cast_const_vector (ROL::Ptr< const std::vector< Real > > & xvec, const ROL::Vector< Real > & x) const inline private
Definition at line 1323 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::isFeasible(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneUpperActive(), and H1BoundConstraint< Real >::pruneUpperActive().
axpy() [1/3]
template<class Real > void H1BoundConstraint< Real >::axpy (std::vector< Real > & out, const Real a, const std::vector< Real > & x, const std::vector< Real > & y) const inline private
Definition at line 1333 of file example_04.hpp.
References H1BoundConstraint< Real >::dim_.
projection() [1/3]
template<class Real > void H1BoundConstraint< Real >::projection (std::vector< Real > & x) inline private
Definition at line 1341 of file example_04.hpp.
References H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
Referenced by H1BoundConstraint< Real >::project().
isFeasible() [1/3]
template<class Real > bool H1BoundConstraint< Real >::isFeasible (const ROL::Vector< Real > & v) inline virtual
Check if the vector, v, is feasible.
This function returns true if \(v = P_{[a,b]}(v)\).
Parameters
[in] v is the vector to be checked.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1367 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
project() [1/3]
template<class Real > void H1BoundConstraint< Real >::project (ROL::Vector< Real > & x) inline virtual
Project optimization variables onto the bounds.
This function implements the projection of \(x\) onto the bounds, i.e.,
\[ (P_{[a,b]}(x))(\xi) = \min\{b(\xi),\max\{a(\xi),x(\xi)\}\} \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1379 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_vector(), and H1BoundConstraint< Real >::projection().
pruneLowerActive() [1/6]
template<class Real > void H1BoundConstraint< Real >::pruneLowerActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-active set is defined as
\[ \mathcal{A}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1384 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_lo_.
pruneUpperActive() [1/6]
template<class Real > void H1BoundConstraint< Real >::pruneUpperActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-active set is defined as
\[ \mathcal{A}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1395 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_up_.
pruneActive() [1/6]
template<class Real > void H1BoundConstraint< Real >::pruneActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline
Definition at line 1406 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
pruneLowerActive() [2/6]
template<class Real > void H1BoundConstraint< Real >::pruneLowerActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon,\; g(\xi) > 0 \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1418 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_lo_.
pruneUpperActive() [2/6]
template<class Real > void H1BoundConstraint< Real >::pruneUpperActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon_x,\; g(\xi) < -\epsilon_g \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1430 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_up_.
pruneActive() [2/6]
template<class Real > void H1BoundConstraint< Real >::pruneActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline
Definition at line 1442 of file example_04.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
getLowerBound() [1/3]
template<class Real > const ROL::Ptr< const ROL::Vector< Real > > H1BoundConstraint< Real >::getLowerBound (void) const inline virtual
Return the ref count pointer to the lower bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1455 of file example_04.hpp.
References H1BoundConstraint< Real >::l_.
getUpperBound() [1/3]
template<class Real > const ROL::Ptr< const ROL::Vector< Real > > H1BoundConstraint< Real >::getUpperBound (void) const inline virtual
Return the ref count pointer to the upper bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1459 of file example_04.hpp.
References H1BoundConstraint< Real >::u_.
cast_vector() [2/3]
template<class Real > void H1BoundConstraint< Real >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1390 of file example_07.hpp.
cast_const_vector() [2/3]
template<class Real > void H1BoundConstraint< Real >::cast_const_vector (ROL::Ptr< const std::vector< Real > > & xvec, const ROL::Vector< Real > & x) const inline private
Definition at line 1402 of file example_07.hpp.
axpy() [2/3]
template<class Real > void H1BoundConstraint< Real >::axpy (std::vector< Real > & out, const Real a, const std::vector< Real > & x, const std::vector< Real > & y) const inline private
Definition at line 1414 of file example_07.hpp.
References H1BoundConstraint< Real >::dim_.
projection() [2/3]
template<class Real > void H1BoundConstraint< Real >::projection (std::vector< Real > & x) inline private
Definition at line 1422 of file example_07.hpp.
References H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
isFeasible() [2/3]
template<class Real > bool H1BoundConstraint< Real >::isFeasible (const ROL::Vector< Real > & v) inline virtual
Check if the vector, v, is feasible.
This function returns true if \(v = P_{[a,b]}(v)\).
Parameters
[in] v is the vector to be checked.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1448 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
project() [2/3]
template<class Real > void H1BoundConstraint< Real >::project (ROL::Vector< Real > & x) inline virtual
Project optimization variables onto the bounds.
This function implements the projection of \(x\) onto the bounds, i.e.,
\[ (P_{[a,b]}(x))(\xi) = \min\{b(\xi),\max\{a(\xi),x(\xi)\}\} \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1460 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_vector(), and H1BoundConstraint< Real >::projection().
pruneLowerActive() [3/6]
template<class Real > void H1BoundConstraint< Real >::pruneLowerActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-active set is defined as
\[ \mathcal{A}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1465 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_lo_.
pruneUpperActive() [3/6]
template<class Real > void H1BoundConstraint< Real >::pruneUpperActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-active set is defined as
\[ \mathcal{A}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1476 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_up_.
pruneActive() [3/6]
template<class Real > void H1BoundConstraint< Real >::pruneActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline
Definition at line 1487 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
pruneLowerActive() [4/6]
template<class Real > void H1BoundConstraint< Real >::pruneLowerActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon,\; g(\xi) > 0 \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1499 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_lo_.
pruneUpperActive() [4/6]
template<class Real > void H1BoundConstraint< Real >::pruneUpperActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon_x,\; g(\xi) < -\epsilon_g \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1511 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_up_.
pruneActive() [4/6]
template<class Real > void H1BoundConstraint< Real >::pruneActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline
Definition at line 1523 of file example_07.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
getLowerBound() [2/3]
template<class Real > const ROL::Ptr< const ROL::Vector< Real > > H1BoundConstraint< Real >::getLowerBound (void) const inline virtual
Return the ref count pointer to the lower bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1536 of file example_07.hpp.
References H1BoundConstraint< Real >::l_.
getUpperBound() [2/3]
template<class Real > const ROL::Ptr< const ROL::Vector< Real > > H1BoundConstraint< Real >::getUpperBound (void) const inline virtual
Return the ref count pointer to the upper bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1540 of file example_07.hpp.
References H1BoundConstraint< Real >::u_.
cast_vector() [3/3]
template<class Real > void H1BoundConstraint< Real >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1176 of file example_08.hpp.
cast_const_vector() [3/3]
template<class Real > void H1BoundConstraint< Real >::cast_const_vector (ROL::Ptr< const std::vector< Real > > & xvec, const ROL::Vector< Real > & x) const inline private
Definition at line 1188 of file example_08.hpp.
axpy() [3/3]
template<class Real > void H1BoundConstraint< Real >::axpy (std::vector< Real > & out, const Real a, const std::vector< Real > & x, const std::vector< Real > & y) const inline private
Definition at line 1198 of file example_08.hpp.
References H1BoundConstraint< Real >::dim_.
projection() [3/3]
template<class Real > void H1BoundConstraint< Real >::projection (std::vector< Real > & x) inline private
Definition at line 1206 of file example_08.hpp.
References H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
isFeasible() [3/3]
template<class Real > bool H1BoundConstraint< Real >::isFeasible (const ROL::Vector< Real > & v) inline virtual
Check if the vector, v, is feasible.
This function returns true if \(v = P_{[a,b]}(v)\).
Parameters
[in] v is the vector to be checked.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1232 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
project() [3/3]
template<class Real > void H1BoundConstraint< Real >::project (ROL::Vector< Real > & x) inline virtual
Project optimization variables onto the bounds.
This function implements the projection of \(x\) onto the bounds, i.e.,
\[ (P_{[a,b]}(x))(\xi) = \min\{b(\xi),\max\{a(\xi),x(\xi)\}\} \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1244 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_vector(), and H1BoundConstraint< Real >::projection().
pruneLowerActive() [5/6]
template<class Real > void H1BoundConstraint< Real >::pruneLowerActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-active set is defined as
\[ \mathcal{A}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1249 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_lo_.
pruneUpperActive() [5/6]
template<class Real > void H1BoundConstraint< Real >::pruneUpperActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-active set is defined as
\[ \mathcal{A}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1260 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_up_.
pruneActive() [5/6]
template<class Real > void H1BoundConstraint< Real >::pruneActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real eps = Real(0)) inline
Definition at line 1271 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
pruneLowerActive() [6/6]
template<class Real > void H1BoundConstraint< Real >::pruneLowerActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon,\; g(\xi) > 0 \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1283 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_lo_.
pruneUpperActive() [6/6]
template<class Real > void H1BoundConstraint< Real >::pruneUpperActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon_x,\; g(\xi) < -\epsilon_g \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1295 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, and H1BoundConstraint< Real >::x_up_.
pruneActive() [6/6]
template<class Real > void H1BoundConstraint< Real >::pruneActive (ROL::Vector< Real > & v, const ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline
Definition at line 1307 of file example_08.hpp.
References H1BoundConstraint< Real >::cast_const_vector(), H1BoundConstraint< Real >::cast_vector(), H1BoundConstraint< Real >::dim_, H1BoundConstraint< Real >::min_diff_, H1BoundConstraint< Real >::scale_, H1BoundConstraint< Real >::x_lo_, and H1BoundConstraint< Real >::x_up_.
getLowerBound() [3/3]
template<class Real > const ROL::Ptr< const ROL::Vector< Real > > H1BoundConstraint< Real >::getLowerBound (void) const inline virtual
Return the ref count pointer to the lower bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1320 of file example_08.hpp.
References H1BoundConstraint< Real >::l_.
getUpperBound() [3/3]
template<class Real > const ROL::Ptr< const ROL::Vector< Real > > H1BoundConstraint< Real >::getUpperBound (void) const inline virtual
Return the ref count pointer to the upper bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 1324 of file example_08.hpp.
References H1BoundConstraint< Real >::u_.
Member Data Documentation
dim_
template<class Real > int H1BoundConstraint< Real >::dim_ private
Definition at line 1304 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::axpy(), H1BoundConstraint< Real >::H1BoundConstraint(), H1BoundConstraint< Real >::isFeasible(), H1BoundConstraint< Real >::projection(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneUpperActive(), and H1BoundConstraint< Real >::pruneUpperActive().
x_lo_
template<class Real > std::vector< Real > H1BoundConstraint< Real >::x_lo_ private
Definition at line 1305 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::H1BoundConstraint(), H1BoundConstraint< Real >::isFeasible(), H1BoundConstraint< Real >::projection(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneLowerActive(), and H1BoundConstraint< Real >::pruneLowerActive().
x_up_
template<class Real > std::vector< Real > H1BoundConstraint< Real >::x_up_ private
Definition at line 1306 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::H1BoundConstraint(), H1BoundConstraint< Real >::isFeasible(), H1BoundConstraint< Real >::projection(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneUpperActive(), and H1BoundConstraint< Real >::pruneUpperActive().
min_diff_
template<class Real > Real H1BoundConstraint< Real >::min_diff_ private
Definition at line 1307 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::H1BoundConstraint(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneUpperActive(), and H1BoundConstraint< Real >::pruneUpperActive().
scale_
template<class Real > Real H1BoundConstraint< Real >::scale_ private
Definition at line 1308 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneLowerActive(), H1BoundConstraint< Real >::pruneUpperActive(), and H1BoundConstraint< Real >::pruneUpperActive().
fem_
template<class Real > ROL::Ptr< BurgersFEM< Real > > H1BoundConstraint< Real >::fem_ private
Definition at line 1309 of file example_04.hpp.
l_
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1BoundConstraint< Real >::l_ private
Definition at line 1310 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::getLowerBound(), and H1BoundConstraint< Real >::H1BoundConstraint().
u_
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1BoundConstraint< Real >::u_ private
Definition at line 1311 of file example_04.hpp.
Referenced by H1BoundConstraint< Real >::getUpperBound(), and H1BoundConstraint< Real >::H1BoundConstraint().
The documentation for this class was generated from the following files:
example_04.hpp
example_07.hpp
example_08.hpp