ROL: ROL::RieszPrimalVector< Real > Class Template Reference
ROL::RieszPrimalVector< Real > Class Template Reference
#include <ROL_RieszVector.hpp>
Public Member Functions
RieszPrimalVector (const ROL::Ptr< V > &v, const ROL::Ptr< OP > &op, Real tol=std::sqrt(ROL_EPSILON< Real >()))
virtual ~RieszPrimalVector ()
virtual Real dot (const V &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
virtual ROL::Ptr< V > clone () const
Clone to make a new (uninitialized) vector.
virtual const V & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const V &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
ROL::Ptr< V > getVector (void)
ROL::Ptr< const V > getVector (void) const
Public Member Functions inherited from ROL::ElementwiseVector< Real >
virtual ~ElementwiseVector ()
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
virtual Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void zero ()
Set to zero vector.
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual ROL::Ptr< Vector > basis (const int i) const
Return i-th basis vector.
virtual int dimension () const
Return dimension of the vector space.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual void print (std::ostream &outStream) const
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
using V = Vector< Real >
using DualVector = RieszDualVector< Real >
using OP = LinearOperator< Real >
Private Member Functions
void initialize_dual (void) const
Private Attributes
const ROL::Ptr< V > v_
ROL::Ptr< DualVector > dual_
const ROL::Ptr< OP > op_
Real tol_
bool isDualInitialized_
Detailed Description
template<class Real>
class ROL::RieszPrimalVector< Real >
Definition at line 43 of file ROL_RieszVector.hpp.
Member Typedef Documentation
V
template<class Real > using ROL::RieszPrimalVector< Real >::V = Vector<Real> private
Definition at line 45 of file ROL_RieszVector.hpp.
DualVector
template<class Real > using ROL::RieszPrimalVector< Real >::DualVector = RieszDualVector<Real> private
Definition at line 46 of file ROL_RieszVector.hpp.
OP
template<class Real > using ROL::RieszPrimalVector< Real >::OP = LinearOperator<Real> private
Definition at line 47 of file ROL_RieszVector.hpp.
Constructor & Destructor Documentation
RieszPrimalVector()
template<class Real > ROL::RieszPrimalVector< Real >::RieszPrimalVector (const ROL::Ptr< V > & v, const ROL::Ptr< OP > & op, Real tol = std::sqrt(ROL_EPSILON<Real>())) inline
Definition at line 67 of file ROL_RieszVector.hpp.
~RieszPrimalVector()
template<class Real > virtual ROL::RieszPrimalVector< Real >::~RieszPrimalVector () inline virtual
Definition at line 73 of file ROL_RieszVector.hpp.
Member Function Documentation
initialize_dual()
template<class Real > void ROL::RieszPrimalVector< Real >::initialize_dual (void) const inline private
Definition at line 58 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::dual_, ROL::RieszPrimalVector< Real >::isDualInitialized_, ROL::RieszPrimalVector< Real >::op_, ROL::RieszPrimalVector< Real >::tol_, and ROL::RieszPrimalVector< Real >::v_.
Referenced by ROL::RieszPrimalVector< Real >::dot(), and ROL::RieszPrimalVector< Real >::dual().
dot()
template<class Real > virtual Real ROL::RieszPrimalVector< Real >::dot (const V & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::ElementwiseVector< Real >.
Definition at line 75 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::dual_, ROL::RieszPrimalVector< Real >::getVector(), ROL::RieszPrimalVector< Real >::initialize_dual(), and ROL::RieszPrimalVector< Real >::isDualInitialized_.
clone()
template<class Real > virtual ROL::Ptr< V > ROL::RieszPrimalVector< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 84 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::op_, ROL::RieszPrimalVector< Real >::tol_, and ROL::RieszPrimalVector< Real >::v_.
dual()
template<class Real > virtual const V & ROL::RieszPrimalVector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 88 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::dual_, ROL::RieszPrimalVector< Real >::initialize_dual(), and ROL::RieszPrimalVector< Real >::isDualInitialized_.
applyUnary()
template<class Real > void ROL::RieszPrimalVector< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Implements ROL::ElementwiseVector< Real >.
Definition at line 95 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::v_.
applyBinary()
template<class Real > void ROL::RieszPrimalVector< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const V & x) inline virtual
Implements ROL::ElementwiseVector< Real >.
Definition at line 99 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::applyBinary(), ROL::RieszPrimalVector< Real >::getVector(), and ROL::RieszPrimalVector< Real >::v_.
Referenced by ROL::RieszPrimalVector< Real >::applyBinary().
reduce()
template<class Real > Real ROL::RieszPrimalVector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Implements ROL::ElementwiseVector< Real >.
Definition at line 104 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::v_.
setScalar()
template<class Real > void ROL::RieszPrimalVector< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 108 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::v_.
randomize()
template<class Real > void ROL::RieszPrimalVector< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 112 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::v_.
getVector() [1/2]
template<class Real > ROL::Ptr< V > ROL::RieszPrimalVector< Real >::getVector (void) inline
Definition at line 116 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::v_.
Referenced by ROL::RieszPrimalVector< Real >::applyBinary(), and ROL::RieszPrimalVector< Real >::dot().
getVector() [2/2]
template<class Real > ROL::Ptr< const V > ROL::RieszPrimalVector< Real >::getVector (void) const inline
Definition at line 120 of file ROL_RieszVector.hpp.
References ROL::RieszPrimalVector< Real >::v_.
Member Data Documentation
v_
template<class Real > const ROL::Ptr<V> ROL::RieszPrimalVector< Real >::v_ private
Definition at line 51 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszPrimalVector< Real >::applyBinary(), ROL::RieszPrimalVector< Real >::applyUnary(), ROL::RieszPrimalVector< Real >::clone(), ROL::RieszPrimalVector< Real >::getVector(), ROL::RieszPrimalVector< Real >::getVector(), ROL::RieszPrimalVector< Real >::initialize_dual(), ROL::RieszPrimalVector< Real >::randomize(), ROL::RieszPrimalVector< Real >::reduce(), and ROL::RieszPrimalVector< Real >::setScalar().
dual_
template<class Real > ROL::Ptr<DualVector> ROL::RieszPrimalVector< Real >::dual_ mutable private
Definition at line 52 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszPrimalVector< Real >::dot(), ROL::RieszPrimalVector< Real >::dual(), and ROL::RieszPrimalVector< Real >::initialize_dual().
op_
template<class Real > const ROL::Ptr<OP> ROL::RieszPrimalVector< Real >::op_ private
Definition at line 53 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszPrimalVector< Real >::clone(), and ROL::RieszPrimalVector< Real >::initialize_dual().
tol_
template<class Real > Real ROL::RieszPrimalVector< Real >::tol_ mutable private
Definition at line 54 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszPrimalVector< Real >::clone(), and ROL::RieszPrimalVector< Real >::initialize_dual().
isDualInitialized_
template<class Real > bool ROL::RieszPrimalVector< Real >::isDualInitialized_ mutable private
Definition at line 56 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszPrimalVector< Real >::dot(), ROL::RieszPrimalVector< Real >::dual(), and ROL::RieszPrimalVector< Real >::initialize_dual().
The documentation for this class was generated from the following file:
ROL_RieszVector.hpp