ROL: ROL::InteriorPointStep< Real > Class Template Reference
ROL::InteriorPointStep< Real > Class Template Reference
#include <ROL_InteriorPointStep.hpp>
Public Member Functions
~InteriorPointStep ()
InteriorPointStep (ROL::ParameterList &parlist)
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with no equality constraint.
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool pHeader=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Types
typedef InteriorPoint::PenalizedObjective< Real > IPOBJ
typedef Constraint_Partitioned< Real > IPCON
Private Attributes
ROL::Ptr< StatusTest< Real > > status_
ROL::Ptr< Step< Real > > step_
ROL::Ptr< Algorithm< Real > > algo_
ROL::Ptr< BoundConstraint< Real > > bnd_
ROL::ParameterList parlist_
ROL::Ptr< Vector< Real > > x_
ROL::Ptr< Vector< Real > > g_
ROL::Ptr< Vector< Real > > l_
ROL::Ptr< Vector< Real > > c_
Real mu_
Real mumin_
Real mumax_
Real rho_
int subproblemIter_
int verbosity_
bool print_
bool hasEquality_
EStep stepType_
std::string stepname_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::InteriorPointStep< Real >
Definition at line 33 of file ROL_InteriorPointStep.hpp.
Member Typedef Documentation
IPOBJ
template<class Real > typedef InteriorPoint::PenalizedObjective<Real> ROL::InteriorPointStep< Real >::IPOBJ private
Definition at line 35 of file ROL_InteriorPointStep.hpp.
IPCON
template<class Real > typedef Constraint_Partitioned<Real> ROL::InteriorPointStep< Real >::IPCON private
Definition at line 36 of file ROL_InteriorPointStep.hpp.
Constructor & Destructor Documentation
~InteriorPointStep()
template<class Real > ROL::InteriorPointStep< Real >::~InteriorPointStep () inline
Definition at line 74 of file ROL_InteriorPointStep.hpp.
InteriorPointStep()
template<class Real > ROL::InteriorPointStep< Real >::InteriorPointStep (ROL::ParameterList & parlist) inline
Definition at line 76 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::mu_, ROL::InteriorPointStep< Real >::mumax_, ROL::InteriorPointStep< Real >::mumin_, ROL::InteriorPointStep< Real >::parlist_, ROL::InteriorPointStep< Real >::print_, ROL::InteriorPointStep< Real >::rho_, ROL::InteriorPointStep< Real >::stepname_, ROL::InteriorPointStep< Real >::stepType_, ROL::StringToEStep(), and ROL::InteriorPointStep< Real >::verbosity_.
Member Function Documentation
initialize() [1/3]
template<class Real > void ROL::InteriorPointStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 118 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::c_, ROL::Vector< Real >::clone(), ROL::AlgorithmState< Real >::cnorm, ROL::InteriorPointStep< Real >::g_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::InteriorPointStep< Real >::hasEquality_, ROL::AlgorithmState< Real >::iter, ROL::InteriorPointStep< Real >::l_, ROL::InteriorPointStep< Real >::mu_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), ROL::Constraint< Real >::value(), ROL::AlgorithmState< Real >::value, and ROL::InteriorPointStep< Real >::x_.
Referenced by ROL::InteriorPointStep< Real >::initialize().
initialize() [2/3]
template<class Real > void ROL::InteriorPointStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 165 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::initialize(), and ROL::BoundConstraint< Real >::projectInterior().
initialize() [3/3]
template<class Real > void ROL::InteriorPointStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with no equality constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 175 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::bnd_, ROL::Vector< Real >::clone(), ROL::AlgorithmState< Real >::cnorm, ROL::InteriorPointStep< Real >::g_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::InteriorPointStep< Real >::mu_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::BoundConstraint< Real >::projectInterior(), ROL::Objective< Real >::update(), ROL::InteriorPoint::PenalizedObjective< Real >::updatePenalty(), ROL::Objective< Real >::value(), ROL::AlgorithmState< Real >::value, and ROL::InteriorPointStep< Real >::x_.
compute() [1/3]
template<class Real > void ROL::InteriorPointStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 216 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::algo_, ROL::Vector< Real >::axpy(), ROL::InteriorPointStep< Real >::c_, ROL::InteriorPointStep< Real >::g_, ROL::Step< Real >::getState(), ROL::InteriorPointStep< Real >::l_, ROL::InteriorPointStep< Real >::parlist_, ROL::InteriorPointStep< Real >::print_, ROL::Vector< Real >::set(), ROL::InteriorPointStep< Real >::status_, ROL::InteriorPointStep< Real >::step_, ROL::STEP_AUGMENTEDLAGRANGIAN, ROL::STEP_COMPOSITESTEP, ROL::STEP_FLETCHER, ROL::InteriorPointStep< Real >::stepname_, ROL::InteriorPointStep< Real >::stepType_, ROL::InteriorPointStep< Real >::subproblemIter_, and ROL::InteriorPointStep< Real >::x_.
Referenced by ROL::InteriorPointStep< Real >::compute().
compute() [2/3]
template<class Real > void ROL::InteriorPointStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 261 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::compute().
compute() [3/3]
template<class Real > void ROL::InteriorPointStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 272 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::algo_, ROL::Vector< Real >::axpy(), ROL::InteriorPointStep< Real >::bnd_, ROL::InteriorPointStep< Real >::g_, ROL::InteriorPointStep< Real >::parlist_, ROL::InteriorPointStep< Real >::print_, ROL::Vector< Real >::set(), ROL::InteriorPointStep< Real >::status_, ROL::InteriorPointStep< Real >::step_, ROL::STEP_BUNDLE, ROL::STEP_LINESEARCH, ROL::InteriorPointStep< Real >::stepType_, ROL::InteriorPointStep< Real >::subproblemIter_, and ROL::InteriorPointStep< Real >::x_.
update() [1/3]
template<class Real > void ROL::InteriorPointStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 308 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::c_, ROL::AlgorithmState< Real >::cnorm, ROL::InteriorPointStep< Real >::g_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::InteriorPointStep< Real >::l_, ROL::InteriorPointStep< Real >::mu_, ROL::InteriorPointStep< Real >::mumax_, ROL::InteriorPointStep< Real >::mumin_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::InteriorPointStep< Real >::rho_, ROL::AlgorithmState< Real >::snorm, ROL::InteriorPointStep< Real >::subproblemIter_, and ROL::AlgorithmState< Real >::value.
Referenced by ROL::InteriorPointStep< Real >::update().
update() [2/3]
template<class Real > void ROL::InteriorPointStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 359 of file ROL_InteriorPointStep.hpp.
References ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::BoundConstraint< Real >::project(), ROL::InteriorPointStep< Real >::update(), and ROL::InteriorPointStep< Real >::x_.
update() [3/3]
template<class Real > void ROL::InteriorPointStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 376 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::g_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::InteriorPointStep< Real >::mu_, ROL::InteriorPointStep< Real >::mumax_, ROL::InteriorPointStep< Real >::mumin_, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::BoundConstraint< Real >::project(), ROL::InteriorPointStep< Real >::rho_, ROL::AlgorithmState< Real >::snorm, ROL::InteriorPoint::PenalizedObjective< Real >::updatePenalty(), ROL::AlgorithmState< Real >::value, and ROL::InteriorPointStep< Real >::x_.
printHeader()
template<class Real > std::string ROL::InteriorPointStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 422 of file ROL_InteriorPointStep.hpp.
References ROL::InteriorPointStep< Real >::hasEquality_, and ROL::InteriorPointStep< Real >::verbosity_.
Referenced by ROL::InteriorPointStep< Real >::print().
printName()
template<class Real > std::string ROL::InteriorPointStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 475 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::print().
print()
template<class Real > std::string ROL::InteriorPointStep< Real >::print (AlgorithmState< Real > & algo_state, bool pHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 483 of file ROL_InteriorPointStep.hpp.
References ROL::AlgorithmState< Real >::cnorm, ROL::AlgorithmState< Real >::gnorm, ROL::InteriorPointStep< Real >::hasEquality_, ROL::AlgorithmState< Real >::iter, ROL::InteriorPointStep< Real >::mu_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::InteriorPointStep< Real >::printHeader(), ROL::InteriorPointStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, ROL::InteriorPointStep< Real >::subproblemIter_, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
status_
template<class Real > ROL::Ptr<StatusTest<Real> > ROL::InteriorPointStep< Real >::status_ private
Definition at line 40 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::compute().
step_
template<class Real > ROL::Ptr<Step<Real> > ROL::InteriorPointStep< Real >::step_ private
Definition at line 41 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::compute().
algo_
template<class Real > ROL::Ptr<Algorithm<Real> > ROL::InteriorPointStep< Real >::algo_ private
Definition at line 42 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::compute().
bnd_
template<class Real > ROL::Ptr<BoundConstraint<Real> > ROL::InteriorPointStep< Real >::bnd_ private
Definition at line 43 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::initialize().
parlist_
template<class Real > ROL::ParameterList ROL::InteriorPointStep< Real >::parlist_ private
Definition at line 44 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::InteriorPointStep().
x_
template<class Real > ROL::Ptr<Vector<Real> > ROL::InteriorPointStep< Real >::x_ private
Definition at line 47 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::InteriorPointStep< Real >::update(), and ROL::InteriorPointStep< Real >::update().
g_
template<class Real > ROL::Ptr<Vector<Real> > ROL::InteriorPointStep< Real >::g_ private
Definition at line 48 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::InteriorPointStep< Real >::update(), and ROL::InteriorPointStep< Real >::update().
l_
template<class Real > ROL::Ptr<Vector<Real> > ROL::InteriorPointStep< Real >::l_ private
Definition at line 49 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::initialize(), and ROL::InteriorPointStep< Real >::update().
c_
template<class Real > ROL::Ptr<Vector<Real> > ROL::InteriorPointStep< Real >::c_ private
Definition at line 50 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::initialize(), and ROL::InteriorPointStep< Real >::update().
mu_
template<class Real > Real ROL::InteriorPointStep< Real >::mu_ private
Definition at line 52 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::InteriorPointStep< Real >::InteriorPointStep(), ROL::InteriorPointStep< Real >::print(), ROL::InteriorPointStep< Real >::update(), and ROL::InteriorPointStep< Real >::update().
mumin_
template<class Real > Real ROL::InteriorPointStep< Real >::mumin_ private
Definition at line 53 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::InteriorPointStep(), ROL::InteriorPointStep< Real >::update(), and ROL::InteriorPointStep< Real >::update().
mumax_
template<class Real > Real ROL::InteriorPointStep< Real >::mumax_ private
Definition at line 54 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::InteriorPointStep(), ROL::InteriorPointStep< Real >::update(), and ROL::InteriorPointStep< Real >::update().
rho_
template<class Real > Real ROL::InteriorPointStep< Real >::rho_ private
Definition at line 55 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::InteriorPointStep(), ROL::InteriorPointStep< Real >::update(), and ROL::InteriorPointStep< Real >::update().
subproblemIter_
template<class Real > int ROL::InteriorPointStep< Real >::subproblemIter_ private
Definition at line 58 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::print(), and ROL::InteriorPointStep< Real >::update().
verbosity_
template<class Real > int ROL::InteriorPointStep< Real >::verbosity_ private
Definition at line 60 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::InteriorPointStep(), and ROL::InteriorPointStep< Real >::printHeader().
print_
template<class Real > bool ROL::InteriorPointStep< Real >::print_ private
Definition at line 61 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::InteriorPointStep().
hasEquality_
template<class Real > bool ROL::InteriorPointStep< Real >::hasEquality_ private
Definition at line 63 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::initialize(), ROL::InteriorPointStep< Real >::print(), and ROL::InteriorPointStep< Real >::printHeader().
stepType_
template<class Real > EStep ROL::InteriorPointStep< Real >::stepType_ private
Definition at line 65 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::InteriorPointStep().
stepname_
template<class Real > std::string ROL::InteriorPointStep< Real >::stepname_ private
Definition at line 66 of file ROL_InteriorPointStep.hpp.
Referenced by ROL::InteriorPointStep< Real >::compute(), and ROL::InteriorPointStep< Real >::InteriorPointStep().
The documentation for this class was generated from the following files:
ROL_AugmentedLagrangianStep.hpp
ROL_InteriorPointStep.hpp