ROL: ROL::CompositeObjective< Real > Class Template Reference
ROL::CompositeObjective< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate composite objective functions.
#include <ROL_CompositeObjective.hpp>
Public Member Functions
CompositeObjective (const std::vector< Ptr< Objective< Real > > > &obj_vec, const Ptr< StdObjective< Real > > &std_obj)
void update (const Vector< Real > &x, UpdateType type, int iter=-1) override
Update objective function.
void update (const Vector< Real > &x, bool flag=true, int iter=-1) override
Update objective function.
Real value (const Vector< Real > &x, Real &tol) override
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol) override
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply Hessian approximation to vector.
void setParameter (const std::vector< Real > &param) override
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
Private Member Functions
void initialize (const Vector< Real > &x)
void computeValue (const Vector< Real > &x, Real &tol)
void computeGradient (const Vector< Real > &x, Real &tol)
void computeHessVec (const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Private Attributes
const std::vector< Ptr< Objective< Real > > > obj_vec_
const Ptr< StdObjective< Real > > std_obj_
Ptr< std::vector< Real > > obj_value_
Ptr< std::vector< Real > > obj_grad_
Ptr< std::vector< Real > > obj_gv_
Ptr< std::vector< Real > > obj_hess_
Ptr< StdVector< Real > > obj_value_vec_
Ptr< StdVector< Real > > obj_grad_vec_
Ptr< StdVector< Real > > obj_gv_vec_
Ptr< StdVector< Real > > obj_hess_vec_
std::vector< Ptr< Vector< Real > > > vec_grad_
std::vector< Ptr< Vector< Real > > > vec_hess_
bool isInitialized_
bool isValueComputed_
bool isGradientComputed_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::CompositeObjective< Real >
Provides the interface to evaluate composite objective functions.
Definition at line 24 of file ROL_CompositeObjective.hpp.
Constructor & Destructor Documentation
CompositeObjective()
template<typename Real > ROL::CompositeObjective< Real >::CompositeObjective (const std::vector< Ptr< Objective< Real > > > & obj_vec, const Ptr< StdObjective< Real > > & std_obj)
Definition at line 16 of file ROL_CompositeObjective_Def.hpp.
References ROL::CompositeObjective< Real >::obj_grad_, ROL::CompositeObjective< Real >::obj_grad_vec_, ROL::CompositeObjective< Real >::obj_gv_, ROL::CompositeObjective< Real >::obj_gv_vec_, ROL::CompositeObjective< Real >::obj_hess_, ROL::CompositeObjective< Real >::obj_hess_vec_, ROL::CompositeObjective< Real >::obj_value_, ROL::CompositeObjective< Real >::obj_value_vec_, and ROL::CompositeObjective< Real >::obj_vec_.
Member Function Documentation
update() [1/2]
template<typename Real > void ROL::CompositeObjective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 31 of file ROL_CompositeObjective_Def.hpp.
References ROL::Revert, and ROL::Trial.
update() [2/2]
template<typename Real > void ROL::CompositeObjective< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 41 of file ROL_CompositeObjective_Def.hpp.
value()
template<typename Real > Real ROL::CompositeObjective< Real >::value (const Vector< Real > & x, Real & tol) override virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 51 of file ROL_CompositeObjective_Def.hpp.
gradient()
template<typename Real > void ROL::CompositeObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) override virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 57 of file ROL_CompositeObjective_Def.hpp.
References ROL::Vector< Real >::axpy(), and ROL::Vector< Real >::zero().
hessVec()
template<typename Real > void ROL::CompositeObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 67 of file ROL_CompositeObjective_Def.hpp.
References ROL::Vector< Real >::axpy(), and ROL::Vector< Real >::zero().
setParameter()
template<typename Real > void ROL::CompositeObjective< Real >::setParameter (const std::vector< Real > & param) override virtual
Reimplemented from ROL::Objective< Real >.
Definition at line 78 of file ROL_CompositeObjective_Def.hpp.
References ROL::Objective< Real >::setParameter().
initialize()
template<typename Real > void ROL::CompositeObjective< Real >::initialize (const Vector< Real > & x) private
Definition at line 90 of file ROL_CompositeObjective_Def.hpp.
References ROL::Vector< Real >::clone(), and ROL::Vector< Real >::dual().
computeValue()
template<typename Real > void ROL::CompositeObjective< Real >::computeValue (const Vector< Real > & x, Real & tol) private
Definition at line 104 of file ROL_CompositeObjective_Def.hpp.
computeGradient()
template<typename Real > void ROL::CompositeObjective< Real >::computeGradient (const Vector< Real > & x, Real & tol) private
Definition at line 116 of file ROL_CompositeObjective_Def.hpp.
computeHessVec()
template<typename Real > void ROL::CompositeObjective< Real >::computeHessVec (const Vector< Real > & v, const Vector< Real > & x, Real & tol) private
Definition at line 129 of file ROL_CompositeObjective_Def.hpp.
Member Data Documentation
obj_vec_
template<typename Real > const std::vector<Ptr<Objective<Real> > > ROL::CompositeObjective< Real >::obj_vec_ private
Definition at line 26 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
std_obj_
template<typename Real > const Ptr<StdObjective<Real> > ROL::CompositeObjective< Real >::std_obj_ private
Definition at line 27 of file ROL_CompositeObjective.hpp.
obj_value_
template<typename Real > Ptr<std::vector<Real> > ROL::CompositeObjective< Real >::obj_value_ private
Definition at line 29 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
obj_grad_
template<typename Real > Ptr<std::vector<Real> > ROL::CompositeObjective< Real >::obj_grad_ private
Definition at line 29 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
obj_gv_
template<typename Real > Ptr<std::vector<Real> > ROL::CompositeObjective< Real >::obj_gv_ private
Definition at line 29 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
obj_hess_
template<typename Real > Ptr<std::vector<Real> > ROL::CompositeObjective< Real >::obj_hess_ private
Definition at line 29 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
obj_value_vec_
template<typename Real > Ptr<StdVector<Real> > ROL::CompositeObjective< Real >::obj_value_vec_ private
Definition at line 30 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
obj_grad_vec_
template<typename Real > Ptr<StdVector<Real> > ROL::CompositeObjective< Real >::obj_grad_vec_ private
Definition at line 30 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
obj_gv_vec_
template<typename Real > Ptr<StdVector<Real> > ROL::CompositeObjective< Real >::obj_gv_vec_ private
Definition at line 30 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
obj_hess_vec_
template<typename Real > Ptr<StdVector<Real> > ROL::CompositeObjective< Real >::obj_hess_vec_ private
Definition at line 30 of file ROL_CompositeObjective.hpp.
Referenced by ROL::CompositeObjective< Real >::CompositeObjective().
vec_grad_
template<typename Real > std::vector<Ptr<Vector<Real> > > ROL::CompositeObjective< Real >::vec_grad_ private
Definition at line 31 of file ROL_CompositeObjective.hpp.
vec_hess_
template<typename Real > std::vector<Ptr<Vector<Real> > > ROL::CompositeObjective< Real >::vec_hess_ private
Definition at line 31 of file ROL_CompositeObjective.hpp.
isInitialized_
template<typename Real > bool ROL::CompositeObjective< Real >::isInitialized_ private
Definition at line 33 of file ROL_CompositeObjective.hpp.
isValueComputed_
template<typename Real > bool ROL::CompositeObjective< Real >::isValueComputed_ private
Definition at line 33 of file ROL_CompositeObjective.hpp.
isGradientComputed_
template<typename Real > bool ROL::CompositeObjective< Real >::isGradientComputed_ private
Definition at line 33 of file ROL_CompositeObjective.hpp.
The documentation for this class was generated from the following files:
ROL_CompositeObjective.hpp
ROL_CompositeObjective_Def.hpp