ROL: OptDualStdVector< Real, Element > Class Template Reference
OptDualStdVector< Real, Element > Class Template Reference
#include <example_02.hpp>
Public Member Functions
OptDualStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
OptDualStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
void applyUnary (const ROL::Elementwise::UnaryFunction< Real > &f)
void applyBinary (const ROL::Elementwise::BinaryFunction< Real > &f, const ROL::Vector< Real > &x)
Real reduce (const ROL::Elementwise::ReductionOp< Real > &r) const
OptDualStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
OptDualStdVector (const ROL::Ptr< std::vector< Element > > &std_vec, ROL::Ptr< FiniteDifference< Real > >fd)
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void axpy (const Real alpha, const Vector &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
virtual void zero ()
Set to zero vector.
virtual void set (const Vector &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
virtual void applyUnary (const Elementwise::UnaryFunction< Real > &f)
virtual void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector &x)
virtual Real reduce (const Elementwise::ReductionOp< Real > &r) const
virtual void print (std::ostream &outStream) const
virtual void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
virtual void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef vector::size_type uint
Private Attributes
ROL::Ptr< std::vector< Element > > std_vec_
ROL::Ptr< OptStdVector< Real > > dual_vec_
ROL::Ptr< FiniteDifference< Real > > fd_
Detailed Description
template<class Real, class Element>
class OptDualStdVector< Real, Element >
Definition at line 175 of file gross-pitaevskii/example_02.hpp.
Member Typedef Documentation
vector [1/4]
template<class Real , class Element > typedef std::vector<Element> OptDualStdVector< Real, Element >::vector private
Definition at line 135 of file dual-spaces/rosenbrock-1/example_01.cpp.
V [1/3]
template<class Real , class Element > typedef ROL::Vector<Real> OptDualStdVector< Real, Element >::V private
Definition at line 136 of file dual-spaces/rosenbrock-1/example_01.cpp.
uint [1/4]
template<class Real , class Element > typedef vector::size_type OptDualStdVector< Real, Element >::uint private
Definition at line 138 of file dual-spaces/rosenbrock-1/example_01.cpp.
vector [2/4]
template<class Real , class Element > typedef std::vector<Element> OptDualStdVector< Real, Element >::vector private
Definition at line 157 of file dual-spaces/rosenbrock-1/example_02.cpp.
V [2/3]
template<class Real , class Element > typedef ROL::Vector<Real> OptDualStdVector< Real, Element >::V private
Definition at line 158 of file dual-spaces/rosenbrock-1/example_02.cpp.
uint [2/4]
template<class Real , class Element > typedef vector::size_type OptDualStdVector< Real, Element >::uint private
Definition at line 160 of file dual-spaces/rosenbrock-1/example_02.cpp.
vector [3/4]
template<class Real , class Element > typedef std::vector<Element> OptDualStdVector< Real, Element >::vector private
Definition at line 142 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
V [3/3]
template<class Real , class Element > typedef ROL::Vector<Real> OptDualStdVector< Real, Element >::V private
Definition at line 143 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
uint [3/4]
template<class Real , class Element > typedef vector::size_type OptDualStdVector< Real, Element >::uint private
Definition at line 144 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
vector [4/4]
template<class Real , class Element > typedef std::vector<Element> OptDualStdVector< Real, Element >::vector private
Definition at line 177 of file gross-pitaevskii/example_02.hpp.
uint [4/4]
template<class Real , class Element > typedef vector::size_type OptDualStdVector< Real, Element >::uint private
Definition at line 178 of file gross-pitaevskii/example_02.hpp.
Constructor & Destructor Documentation
OptDualStdVector() [1/4]
template<class Real , class Element > OptDualStdVector< Real, Element >::OptDualStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 146 of file dual-spaces/rosenbrock-1/example_01.cpp.
OptDualStdVector() [2/4]
template<class Real , class Element > OptDualStdVector< Real, Element >::OptDualStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 168 of file dual-spaces/rosenbrock-1/example_02.cpp.
OptDualStdVector() [3/4]
template<class Real , class Element > OptDualStdVector< Real, Element >::OptDualStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 152 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
OptDualStdVector() [4/4]
template<class Real , class Element > OptDualStdVector< Real, Element >::OptDualStdVector (const ROL::Ptr< std::vector< Element > > & std_vec, ROL::Ptr< FiniteDifference< Real > > fd) inline
Definition at line 187 of file gross-pitaevskii/example_02.hpp.
Member Function Documentation
plus() [1/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 148 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
scale() [1/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 158 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), and OptDualStdVector< Real, Element >::std_vec_.
dot() [1/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 165 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
Referenced by OptDualStdVector< Real, Element >::norm().
norm() [1/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 176 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dot().
clone() [1/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptDualStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 182 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
getVector() [1/8]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > OptDualStdVector< Real, Element >::getVector () const inline
Definition at line 186 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
Referenced by OptDualStdVector< Real, Element >::apply(), OptDualStdVector< Real, Element >::applyBinary(), OptDualStdVector< Real, Element >::dot(), OptDualStdVector< Real, Element >::dot(), OptDualStdVector< Real, Element >::plus(), and OptDualStdVector< Real, Element >::plus().
getVector() [2/8]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptDualStdVector< Real, Element >::getVector () inline
Definition at line 190 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
basis() [1/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptDualStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 194 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
dimension() [1/4]
template<class Real , class Element > int OptDualStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 203 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
Referenced by OptDualStdVector< Real, Element >::apply(), OptDualStdVector< Real, Element >::dot(), OptDualStdVector< Real, Element >::dot(), OptDualStdVector< Real, Element >::plus(), OptDualStdVector< Real, Element >::plus(), and OptDualStdVector< Real, Element >::scale().
dual() [1/4]
template<class Real , class Element > const ROL::Vector< Real > & OptDualStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 205 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dual_vec_.
apply() [1/3]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 210 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
Referenced by OptDualStdVector< Real, Element >::applyBinary().
plus() [2/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 170 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
scale() [2/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 180 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::dimension(), and OptDualStdVector< Real, Element >::std_vec_.
dot() [2/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 187 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
norm() [2/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 198 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::dot().
clone() [2/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptDualStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 204 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
getVector() [3/8]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > OptDualStdVector< Real, Element >::getVector () const inline
Definition at line 208 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
getVector() [4/8]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptDualStdVector< Real, Element >::getVector () inline
Definition at line 212 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
basis() [2/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptDualStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 216 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
dimension() [2/4]
template<class Real , class Element > int OptDualStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 225 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
dual() [2/4]
template<class Real , class Element > const ROL::Vector< Real > & OptDualStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 227 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::dual_vec_.
apply() [2/3]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 232 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
applyUnary()
template<class Real , class Element > void OptDualStdVector< Real, Element >::applyUnary (const ROL::Elementwise::UnaryFunction< Real > & f) inline
Definition at line 243 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
applyBinary()
template<class Real , class Element > void OptDualStdVector< Real, Element >::applyBinary (const ROL::Elementwise::BinaryFunction< Real > & f, const ROL::Vector< Real > & x) inline
Definition at line 247 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptDualStdVector< Real, Element >::apply(), dim, OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
reduce()
template<class Real , class Element > Real OptDualStdVector< Real, Element >::reduce (const ROL::Elementwise::ReductionOp< Real > & r) const inline
Definition at line 255 of file dual-spaces/rosenbrock-1/example_02.cpp.
References dim, and OptDualStdVector< Real, Element >::std_vec_.
plus() [3/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 154 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
scale() [3/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 163 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), and OptDualStdVector< Real, Element >::std_vec_.
dot() [3/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 170 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
norm() [3/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 181 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dot().
clone() [3/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptDualStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 187 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
getVector() [5/8]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > OptDualStdVector< Real, Element >::getVector () const inline
Definition at line 191 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
getVector() [6/8]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptDualStdVector< Real, Element >::getVector () inline
Definition at line 195 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
basis() [3/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptDualStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 199 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
dimension() [3/4]
template<class Real , class Element > int OptDualStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 207 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::std_vec_.
dual() [3/4]
template<class Real , class Element > const ROL::Vector< Real > & OptDualStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 209 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dual_vec_.
apply() [3/3]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 214 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
plus() [4/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::plus (const Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 190 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
scale() [4/4]
template<class Real , class Element > void OptDualStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 199 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::dimension(), and OptDualStdVector< Real, Element >::std_vec_.
dot() [4/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 206 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::fd_, OptDualStdVector< Real, Element >::getVector(), and OptDualStdVector< Real, Element >::std_vec_.
norm() [4/4]
template<class Real , class Element > Real OptDualStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 220 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::dot().
clone() [4/4]
template<class Real , class Element > ROL::Ptr< Vector< Real > > OptDualStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 226 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::fd_, and OptDualStdVector< Real, Element >::std_vec_.
getVector() [7/8]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > OptDualStdVector< Real, Element >::getVector () const inline
Definition at line 230 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::std_vec_.
getVector() [8/8]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptDualStdVector< Real, Element >::getVector () inline
Definition at line 234 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::std_vec_.
basis() [4/4]
template<class Real , class Element > ROL::Ptr< Vector< Real > > OptDualStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 238 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::fd_, and OptDualStdVector< Real, Element >::std_vec_.
dimension() [4/4]
template<class Real , class Element > int OptDualStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 245 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::std_vec_.
dual() [4/4]
template<class Real , class Element > const Vector< Real > & OptDualStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 247 of file gross-pitaevskii/example_02.hpp.
References OptDualStdVector< Real, Element >::dual_vec_, OptDualStdVector< Real, Element >::fd_, and OptDualStdVector< Real, Element >::std_vec_.
Member Data Documentation
std_vec_
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptDualStdVector< Real, Element >::std_vec_ private
Definition at line 141 of file dual-spaces/rosenbrock-1/example_01.cpp.
Referenced by OptDualStdVector< Real, Element >::apply(), OptDualStdVector< Real, Element >::applyBinary(), OptDualStdVector< Real, Element >::applyUnary(), OptDualStdVector< Real, Element >::basis(), OptDualStdVector< Real, Element >::clone(), OptDualStdVector< Real, Element >::dimension(), OptDualStdVector< Real, Element >::dot(), OptDualStdVector< Real, Element >::dot(), OptDualStdVector< Real, Element >::dual(), OptDualStdVector< Real, Element >::getVector(), OptDualStdVector< Real, Element >::getVector(), OptDualStdVector< Real, Element >::plus(), OptDualStdVector< Real, Element >::plus(), OptDualStdVector< Real, Element >::reduce(), and OptDualStdVector< Real, Element >::scale().
dual_vec_
template<class Real , class Element > ROL::Ptr< OptStdVector< Real > > OptDualStdVector< Real, Element >::dual_vec_ mutable private
Definition at line 142 of file dual-spaces/rosenbrock-1/example_01.cpp.
Referenced by OptDualStdVector< Real, Element >::dual().
fd_
template<class Real , class Element > ROL::Ptr<FiniteDifference<Real> > OptDualStdVector< Real, Element >::fd_ private
Definition at line 183 of file gross-pitaevskii/example_02.hpp.
Referenced by OptDualStdVector< Real, Element >::basis(), OptDualStdVector< Real, Element >::clone(), OptDualStdVector< Real, Element >::dot(), and OptDualStdVector< Real, Element >::dual().
The documentation for this class was generated from the following files:
dual-spaces/rosenbrock-1/example_01.cpp
dual-spaces/rosenbrock-1/example_02.cpp
dual-spaces/simple-eq-constr-1/example_01.cpp
gross-pitaevskii/example_02.hpp