ROL: ROL::AugmentedLagrangianStep< Real > Class Template Reference
ROL::AugmentedLagrangianStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute augmented Lagrangian steps.
#include <ROL_AugmentedLagrangianStep.hpp>
Public Member Functions
~AugmentedLagrangianStep ()
AugmentedLagrangianStep (ROL::ParameterList &parlist)
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality and bound constraints.
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraint).
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality and bound constraints).
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraint).
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality and bound constraints).
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool pHeader=false) const
Print iterate status.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Member Functions
Real computeGradient (Vector< Real > &g, const Vector< Real > &x, const Real mu, Objective< Real > &obj, BoundConstraint< Real > &bnd)
Private Attributes
ROL::Ptr< StatusTest< Real > > status_
ROL::Ptr< Step< Real > > step_
ROL::Ptr< Algorithm< Real > > algo_
ROL::Ptr< Vector< Real > > x_
ROL::Ptr< BoundConstraint< Real > > bnd_
ROL::ParameterList parlist_
bool useDefaultInitPen_
bool scaleLagrangian_
Real minPenaltyReciprocal_
Real minPenaltyLowerBound_
Real penaltyUpdate_
Real maxPenaltyParam_
Real optIncreaseExponent_
Real optDecreaseExponent_
Real optToleranceInitial_
Real optTolerance_
Real feasIncreaseExponent_
Real feasDecreaseExponent_
Real feasToleranceInitial_
Real feasTolerance_
bool print_
int maxit_
int subproblemIter_
std::string subStep_
Real outerOptTolerance_
Real outerFeasTolerance_
Real outerStepTolerance_
bool useDefaultScaling_
Real fscale_
Real cscale_
int verbosity_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::AugmentedLagrangianStep< Real >
Provides the interface to compute augmented Lagrangian steps.
The Augmented Lagrangian algorithm is used to solve Type-EB problems. This algorithm solves the scaled problem
\[ \min_{x} w_J J(x) \quad\text{subject to}\quad w_c c(x) = 0,\quad \ell \le x \le u \]
for some positive consants \(w_J,\, w_c\). These constants are either input by the user or automatically estimated. To solve this scaled problem, the Augmented Lagrangian algorithm minimizes the so-called Augmented Lagrangian functional
\[ L(x,\lambda,r) := w_J J(x) + w_c \langle \lambda, c(x)\rangle_{X^*,X} + \frac{w_c^2 r}{2} \|c(x)\|_X^2 \]
subject to the bound constraints \(\ell \le x \le u\). The multiplier estimate \(\lambda\) is updated as
\[ \lambda \leftarrow \lambda + r w_c c(x). \]
The penalty parameter \(r>0\) is also updated based on the progress of the algorithm. The initial penalty parameter is either input by the user or automatically computed.
User Input Parameters: bool Step -> Augmented Lagrangian -> Use Default initial Penalty Parameter Use automatically determined initial penalty parameter. Default: true
Real Step -> Augmented Lagrangian -> Initial Penalty Parameter Initial penalty parameter. Default: 10
Real Step -> Augmented Lagrangian -> Use Scaled Augmented Lagrangian Use Augmented Lagrangian scaled by the reciprocal of the penalty parameter. Default: false
Real Step -> Augmented Lagrangian -> Penalty Parameter Reciprocal Lower Bound Minimum penalty parameter reciprocal for tolerance updates. Default: 0.1
Real Step -> Augmented Lagrangian -> Penalty Parameter Growth Factor Rate of growth for penalty parameter. Default: 10
Real Step -> Augmented Lagrangian -> Maximum Penalty Parameter Maximum penalty parameter size. Default: 1e8
Real Step -> Augmented Lagrangian -> Optimality Tolerance Update Exponent Rate at which to update optimality tolerance. Default: 1
Real Step -> Augmented Lagrangian -> Optimality Tolerance Decrease Exponent Rate at which to decrease optimality tolerance. Default: 1
Real Step -> Augmented Lagrangian -> Initial Optimality Tolerance Initial tolerance for optimality. Default: 1
Real Step -> Augmented Lagrangian -> Feasibility Tolerance Update Exponent Rate at which to update feasibility tolerance. Default: 0.1
Real Step -> Augmented Lagrangian -> Feasibility Tolerance Decrease Exponent Rate at which to decrease feasibility tolerance. Default: 0.9
Real Step -> Augmented Lagrangian -> Initial Feasibility Tolerance Initial tolerance for equality constraint feasibility. Default: 1
bool Step -> Augmented Lagrangian -> Print Intermediate Optimization History Print iteration history for subproblem solve. Default: false
int Step -> Augmented Lagrangian -> Subproblem Iteration Limit Subproblem iteration limit. Default: 1000
string Step -> Augmented Lagrangian -> Subproblem Step Type Subproblem (bound constrained) solver type. Default: Trust Region
bool Step -> Augmented Lagrangian -> Use Default Problem Scaling Use automatic constraint and objective scaling. Default: true
Real Step -> Augmented Lagrangian -> Objective Scaling Positive scaling constant for objective. Default: 1
Real Step -> Augmented Lagrangian -> Constraint Scaling Positive scaling constant for constraint. Default: 1
int General -> Print Verbosity Print additional information to screen for debugging purposes. Default: 0
Definition at line 126 of file ROL_AugmentedLagrangianStep.hpp.
Constructor & Destructor Documentation
~AugmentedLagrangianStep()
template<class Real > ROL::AugmentedLagrangianStep< Real >::~AugmentedLagrangianStep () inline
Definition at line 197 of file ROL_AugmentedLagrangianStep.hpp.
AugmentedLagrangianStep()
template<class Real > ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep (ROL::ParameterList & parlist) inline
Definition at line 199 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::cscale_, ROL::AugmentedLagrangianStep< Real >::feasDecreaseExponent_, ROL::AugmentedLagrangianStep< Real >::feasIncreaseExponent_, ROL::AugmentedLagrangianStep< Real >::feasToleranceInitial_, ROL::AugmentedLagrangianStep< Real >::fscale_, ROL::Step< Real >::getState(), ROL::AugmentedLagrangianStep< Real >::maxit_, ROL::AugmentedLagrangianStep< Real >::maxPenaltyParam_, ROL::AugmentedLagrangianStep< Real >::minPenaltyLowerBound_, ROL::AugmentedLagrangianStep< Real >::minPenaltyReciprocal_, ROL::AugmentedLagrangianStep< Real >::optDecreaseExponent_, ROL::AugmentedLagrangianStep< Real >::optIncreaseExponent_, ROL::AugmentedLagrangianStep< Real >::optToleranceInitial_, ROL::AugmentedLagrangianStep< Real >::outerFeasTolerance_, ROL::AugmentedLagrangianStep< Real >::outerOptTolerance_, ROL::AugmentedLagrangianStep< Real >::outerStepTolerance_, ROL::AugmentedLagrangianStep< Real >::parlist_, ROL::AugmentedLagrangianStep< Real >::penaltyUpdate_, ROL::AugmentedLagrangianStep< Real >::print_, ROL::AugmentedLagrangianStep< Real >::scaleLagrangian_, ROL::AugmentedLagrangianStep< Real >::subStep_, ROL::AugmentedLagrangianStep< Real >::useDefaultInitPen_, ROL::AugmentedLagrangianStep< Real >::useDefaultScaling_, and ROL::AugmentedLagrangianStep< Real >::verbosity_.
Member Function Documentation
computeGradient()
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::computeGradient (Vector< Real > & g, const Vector< Real > & x, const Real mu, Objective< Real > & obj, BoundConstraint< Real > & bnd) inline private
Definition at line 167 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::Vector< Real >::dual(), ROL::AugmentedLagrangian< Real >::gradient(), ROL::BoundConstraint< Real >::isActivated(), ROL::Vector< Real >::norm(), ROL::BoundConstraint< Real >::project(), ROL::Vector< Real >::scale(), ROL::AugmentedLagrangianStep< Real >::scaleLagrangian_, and ROL::AugmentedLagrangianStep< Real >::x_.
Referenced by ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
initialize() [1/2]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 241 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::bnd_, and ROL::AugmentedLagrangianStep< Real >::initialize().
Referenced by ROL::AugmentedLagrangianStep< Real >::initialize().
initialize() [2/2]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality and bound constraints.
Reimplemented from ROL::Step< Real >.
Definition at line 251 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::AlgorithmState< Real >::cnorm, ROL::AugmentedLagrangianStep< Real >::computeGradient(), ROL::AugmentedLagrangianStep< Real >::cscale_, ROL::Vector< Real >::dimension(), ROL::AugmentedLagrangianStep< Real >::feasDecreaseExponent_, ROL::AugmentedLagrangianStep< Real >::feasTolerance_, ROL::AugmentedLagrangianStep< Real >::feasToleranceInitial_, ROL::AugmentedLagrangianStep< Real >::fscale_, ROL::AugmentedLagrangian< Real >::getConstraintVec(), ROL::AugmentedLagrangian< Real >::getNumberConstraintEvaluations(), ROL::AugmentedLagrangian< Real >::getNumberFunctionEvaluations(), ROL::AugmentedLagrangian< Real >::getNumberGradientEvaluations(), ROL::AugmentedLagrangian< Real >::getObjectiveGradient(), ROL::AugmentedLagrangian< Real >::getObjectiveValue(), ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::BoundConstraint< Real >::isActivated(), ROL::AlgorithmState< Real >::iter, ROL::AugmentedLagrangianStep< Real >::maxPenaltyParam_, ROL::AugmentedLagrangianStep< Real >::minPenaltyLowerBound_, ROL::AugmentedLagrangianStep< Real >::minPenaltyReciprocal_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::AugmentedLagrangianStep< Real >::optDecreaseExponent_, ROL::AugmentedLagrangianStep< Real >::optTolerance_, ROL::AugmentedLagrangianStep< Real >::optToleranceInitial_, ROL::AugmentedLagrangianStep< Real >::outerFeasTolerance_, ROL::AugmentedLagrangianStep< Real >::outerOptTolerance_, ROL::BoundConstraint< Real >::project(), ROL::AugmentedLagrangian< Real >::setScaling(), ROL::AugmentedLagrangian< Real >::update(), ROL::AugmentedLagrangianStep< Real >::useDefaultInitPen_, ROL::AugmentedLagrangianStep< Real >::useDefaultScaling_, ROL::AlgorithmState< Real >::value, ROL::AugmentedLagrangianStep< Real >::verbosity_, and ROL::AugmentedLagrangianStep< Real >::x_.
compute() [1/3]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality constraint).
Reimplemented from ROL::Step< Real >.
Definition at line 325 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::bnd_, and ROL::AugmentedLagrangianStep< Real >::compute().
Referenced by ROL::AugmentedLagrangianStep< Real >::compute().
compute() [2/3]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality and bound constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 333 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::algo_, ROL::Vector< Real >::axpy(), ROL::AugmentedLagrangianStep< Real >::bnd_, ROL::BoundConstraint< Real >::isActivated(), ROL::AugmentedLagrangianStep< Real >::optTolerance_, ROL::AugmentedLagrangianStep< Real >::parlist_, ROL::AugmentedLagrangianStep< Real >::print_, ROL::Vector< Real >::set(), ROL::AugmentedLagrangianStep< Real >::status_, ROL::AugmentedLagrangianStep< Real >::step_, ROL::AugmentedLagrangianStep< Real >::subproblemIter_, ROL::AugmentedLagrangianStep< Real >::subStep_, and ROL::AugmentedLagrangianStep< Real >::x_.
update() [1/3]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality constraint).
Reimplemented from ROL::Step< Real >.
Definition at line 394 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::bnd_, and ROL::AugmentedLagrangianStep< Real >::update().
Referenced by ROL::AugmentedLagrangianStep< Real >::update().
update() [2/3]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality and bound constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 402 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::algo_, ROL::Vector< Real >::axpy(), ROL::AlgorithmState< Real >::cnorm, ROL::AugmentedLagrangianStep< Real >::computeGradient(), ROL::AugmentedLagrangianStep< Real >::cscale_, ROL::EXITSTATUS_CONVERGED, ROL::AugmentedLagrangianStep< Real >::feasDecreaseExponent_, ROL::AugmentedLagrangianStep< Real >::feasIncreaseExponent_, ROL::AugmentedLagrangianStep< Real >::feasTolerance_, ROL::AugmentedLagrangianStep< Real >::feasToleranceInitial_, ROL::AugmentedLagrangianStep< Real >::fscale_, ROL::AugmentedLagrangian< Real >::getConstraintVec(), ROL::AugmentedLagrangian< Real >::getNumberConstraintEvaluations(), ROL::AugmentedLagrangian< Real >::getNumberFunctionEvaluations(), ROL::AugmentedLagrangian< Real >::getNumberGradientEvaluations(), ROL::AugmentedLagrangian< Real >::getObjectiveValue(), ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::AlgorithmState< Real >::lagmultVec, ROL::AugmentedLagrangianStep< Real >::maxPenaltyParam_, ROL::AugmentedLagrangianStep< Real >::minPenaltyLowerBound_, ROL::AugmentedLagrangianStep< Real >::minPenaltyReciprocal_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::AugmentedLagrangianStep< Real >::optDecreaseExponent_, ROL::AugmentedLagrangianStep< Real >::optIncreaseExponent_, ROL::AugmentedLagrangianStep< Real >::optTolerance_, ROL::AugmentedLagrangianStep< Real >::optToleranceInitial_, ROL::AugmentedLagrangianStep< Real >::outerFeasTolerance_, ROL::AugmentedLagrangianStep< Real >::outerOptTolerance_, ROL::AugmentedLagrangianStep< Real >::penaltyUpdate_, ROL::Vector< Real >::plus(), ROL::AugmentedLagrangian< Real >::reset(), ROL::AlgorithmState< Real >::snorm, ROL::AugmentedLagrangianStep< Real >::subproblemIter_, ROL::AugmentedLagrangian< Real >::update(), ROL::Objective< Real >::update(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::AugmentedLagrangianStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 458 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::verbosity_.
Referenced by ROL::AugmentedLagrangianStep< Real >::print().
printName()
template<class Real > std::string ROL::AugmentedLagrangianStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 497 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AugmentedLagrangianStep< Real >::subStep_.
Referenced by ROL::AugmentedLagrangianStep< Real >::print().
print()
template<class Real > std::string ROL::AugmentedLagrangianStep< Real >::print (AlgorithmState< Real > & algo_state, bool pHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 507 of file ROL_AugmentedLagrangianStep.hpp.
References ROL::AlgorithmState< Real >::cnorm, ROL::AugmentedLagrangianStep< Real >::feasTolerance_, ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::AugmentedLagrangianStep< Real >::optTolerance_, ROL::AugmentedLagrangianStep< Real >::outerFeasTolerance_, ROL::AugmentedLagrangianStep< Real >::outerOptTolerance_, ROL::AugmentedLagrangianStep< Real >::printHeader(), ROL::AugmentedLagrangianStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, ROL::AugmentedLagrangianStep< Real >::subproblemIter_, and ROL::AlgorithmState< Real >::value.
compute() [3/3]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Reimplemented from ROL::Step< Real >.
Definition at line 553 of file ROL_AugmentedLagrangianStep.hpp.
update() [3/3]
template<class Real > void ROL::AugmentedLagrangianStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Reimplemented from ROL::Step< Real >.
Definition at line 560 of file ROL_AugmentedLagrangianStep.hpp.
Member Data Documentation
status_
template<class Real > ROL::Ptr<StatusTest<Real> > ROL::AugmentedLagrangianStep< Real >::status_ private
Definition at line 128 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::compute().
step_
template<class Real > ROL::Ptr<Step<Real> > ROL::AugmentedLagrangianStep< Real >::step_ private
Definition at line 129 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::compute().
algo_
template<class Real > ROL::Ptr<Algorithm<Real> > ROL::AugmentedLagrangianStep< Real >::algo_ private
Definition at line 130 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::compute(), and ROL::AugmentedLagrangianStep< Real >::update().
x_
template<class Real > ROL::Ptr<Vector<Real> > ROL::AugmentedLagrangianStep< Real >::x_ private
Definition at line 131 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::computeGradient(), and ROL::AugmentedLagrangianStep< Real >::initialize().
bnd_
template<class Real > ROL::Ptr<BoundConstraint<Real> > ROL::AugmentedLagrangianStep< Real >::bnd_ private
Definition at line 132 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
parlist_
template<class Real > ROL::ParameterList ROL::AugmentedLagrangianStep< Real >::parlist_ private
Definition at line 134 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::compute().
useDefaultInitPen_
template<class Real > bool ROL::AugmentedLagrangianStep< Real >::useDefaultInitPen_ private
Definition at line 136 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::initialize().
scaleLagrangian_
template<class Real > bool ROL::AugmentedLagrangianStep< Real >::scaleLagrangian_ private
Definition at line 137 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::computeGradient().
minPenaltyReciprocal_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::minPenaltyReciprocal_ private
Definition at line 138 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
minPenaltyLowerBound_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::minPenaltyLowerBound_ private
Definition at line 139 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
penaltyUpdate_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::penaltyUpdate_ private
Definition at line 140 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::update().
maxPenaltyParam_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::maxPenaltyParam_ private
Definition at line 141 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
optIncreaseExponent_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::optIncreaseExponent_ private
Definition at line 143 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::update().
optDecreaseExponent_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::optDecreaseExponent_ private
Definition at line 144 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
optToleranceInitial_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::optToleranceInitial_ private
Definition at line 145 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
optTolerance_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::optTolerance_ private
Definition at line 146 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::print(), and ROL::AugmentedLagrangianStep< Real >::update().
feasIncreaseExponent_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::feasIncreaseExponent_ private
Definition at line 148 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::update().
feasDecreaseExponent_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::feasDecreaseExponent_ private
Definition at line 149 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
feasToleranceInitial_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::feasToleranceInitial_ private
Definition at line 150 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
feasTolerance_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::feasTolerance_ private
Definition at line 151 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::print(), and ROL::AugmentedLagrangianStep< Real >::update().
print_
template<class Real > bool ROL::AugmentedLagrangianStep< Real >::print_ private
Definition at line 153 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::compute().
maxit_
template<class Real > int ROL::AugmentedLagrangianStep< Real >::maxit_ private
Definition at line 154 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep().
subproblemIter_
template<class Real > int ROL::AugmentedLagrangianStep< Real >::subproblemIter_ private
Definition at line 155 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::print(), and ROL::AugmentedLagrangianStep< Real >::update().
subStep_
template<class Real > std::string ROL::AugmentedLagrangianStep< Real >::subStep_ private
Definition at line 156 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::compute(), and ROL::AugmentedLagrangianStep< Real >::printName().
outerOptTolerance_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::outerOptTolerance_ private
Definition at line 157 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::print(), and ROL::AugmentedLagrangianStep< Real >::update().
outerFeasTolerance_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::outerFeasTolerance_ private
Definition at line 158 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::print(), and ROL::AugmentedLagrangianStep< Real >::update().
outerStepTolerance_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::outerStepTolerance_ private
Definition at line 159 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep().
useDefaultScaling_
template<class Real > bool ROL::AugmentedLagrangianStep< Real >::useDefaultScaling_ private
Definition at line 161 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), and ROL::AugmentedLagrangianStep< Real >::initialize().
fscale_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::fscale_ private
Definition at line 162 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
cscale_
template<class Real > Real ROL::AugmentedLagrangianStep< Real >::cscale_ private
Definition at line 163 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::update().
verbosity_
template<class Real > int ROL::AugmentedLagrangianStep< Real >::verbosity_ private
Definition at line 165 of file ROL_AugmentedLagrangianStep.hpp.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::AugmentedLagrangianStep< Real >::initialize(), and ROL::AugmentedLagrangianStep< Real >::printHeader().
The documentation for this class was generated from the following file:
ROL_AugmentedLagrangianStep.hpp