ROL: ROL::RiskNeutralConstraint< Real > Class Template Reference
ROL::RiskNeutralConstraint< Real > Class Template Reference
#include <ROL_RiskNeutralConstraint.hpp>
Public Member Functions
RiskNeutralConstraint (const Ptr< Constraint< Real > > &con, const Ptr< SampleGenerator< Real > > &xsampler, const Ptr< BatchManager< Real > > &cbman)
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update constraint function.
void value (Vector< Real > &c, const Vector< Real > &x, Real &tol)
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void applyAdjointHessian (Vector< Real > &ahuv, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol)
Approximately solves the augmented system
virtual void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Private Member Functions
void init (const Vector< Real > &c, const Vector< Real > &x)
Private Attributes
const Ptr< Constraint< Real > > con_
const Ptr< SampleGenerator< Real > > xsampler_
const Ptr< BatchManager< Real > > cbman_
Ptr< Vector< Real > > conVec_
Ptr< Vector< Real > > optVec_
bool initialized_
Additional Inherited Members
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::RiskNeutralConstraint< Real >
Definition at line 21 of file ROL_RiskNeutralConstraint.hpp.
Constructor & Destructor Documentation
RiskNeutralConstraint()
template<class Real > ROL::RiskNeutralConstraint< Real >::RiskNeutralConstraint (const Ptr< Constraint< Real > > & con, const Ptr< SampleGenerator< Real > > & xsampler, const Ptr< BatchManager< Real > > & cbman) inline
Definition at line 41 of file ROL_RiskNeutralConstraint.hpp.
Member Function Documentation
init()
template<class Real > void ROL::RiskNeutralConstraint< Real >::init (const Vector< Real > & c, const Vector< Real > & x) inline private
Definition at line 32 of file ROL_RiskNeutralConstraint.hpp.
References ROL::Vector< Real >::clone(), ROL::RiskNeutralConstraint< Real >::conVec_, ROL::Vector< Real >::dual(), ROL::RiskNeutralConstraint< Real >::initialized_, and ROL::RiskNeutralConstraint< Real >::optVec_.
Referenced by ROL::RiskNeutralConstraint< Real >::applyAdjointHessian(), ROL::RiskNeutralConstraint< Real >::applyAdjointJacobian(), ROL::RiskNeutralConstraint< Real >::applyJacobian(), and ROL::RiskNeutralConstraint< Real >::value().
update() [1/2]
template<class Real > void ROL::RiskNeutralConstraint< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 46 of file ROL_RiskNeutralConstraint.hpp.
References ROL::RiskNeutralConstraint< Real >::con_.
update() [2/2]
template<class Real > void ROL::RiskNeutralConstraint< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update constraint function.
This function updates the constraint function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 50 of file ROL_RiskNeutralConstraint.hpp.
References ROL::RiskNeutralConstraint< Real >::con_.
value()
template<class Real > void ROL::RiskNeutralConstraint< Real >::value (Vector< Real > & c, const Vector< Real > & x, Real & tol) inline virtual
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
Parameters
[out] c is the result of evaluating the constraint operator at x; a constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(x)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{x} \in \mathcal{X}\).
Implements ROL::Constraint< Real >.
Definition at line 54 of file ROL_RiskNeutralConstraint.hpp.
References ROL::RiskNeutralConstraint< Real >::cbman_, ROL::RiskNeutralConstraint< Real >::con_, ROL::RiskNeutralConstraint< Real >::conVec_, ROL::RiskNeutralConstraint< Real >::init(), ROL::RiskNeutralConstraint< Real >::xsampler_, and ROL::Vector< Real >::zero().
applyJacobian()
template<class Real > void ROL::RiskNeutralConstraint< Real >::applyJacobian (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at x; a constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c'(x)v\), where \(v \in \mathcal{X}\), \(\mathsf{jv} \in \mathcal{C}\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 66 of file ROL_RiskNeutralConstraint.hpp.
References ROL::RiskNeutralConstraint< Real >::cbman_, ROL::RiskNeutralConstraint< Real >::con_, ROL::RiskNeutralConstraint< Real >::conVec_, ROL::RiskNeutralConstraint< Real >::init(), ROL::RiskNeutralConstraint< Real >::xsampler_, and ROL::Vector< Real >::zero().
applyAdjointJacobian()
template<class Real > void ROL::RiskNeutralConstraint< Real >::applyAdjointJacobian (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at x; a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c'(x)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 78 of file ROL_RiskNeutralConstraint.hpp.
References ROL::RiskNeutralConstraint< Real >::con_, ROL::Vector< Real >::dual(), ROL::RiskNeutralConstraint< Real >::init(), ROL::RiskNeutralConstraint< Real >::optVec_, ROL::RiskNeutralConstraint< Real >::xsampler_, and ROL::Vector< Real >::zero().
applyAdjointHessian()
template<class Real > void ROL::RiskNeutralConstraint< Real >::applyAdjointHessian (Vector< Real > & ahuv, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
Parameters
[out] ahuv is the result of applying the derivative of the adjoint of the constraint Jacobian at x to vector u in direction v; a dual optimization-space vector
[in] u is the direction vector; a dual constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahuv} = c''(x)(v,\cdot)^*u \), where \(u \in \mathcal{C}^*\), \(v \in \mathcal{X}\), and \(\mathsf{ahuv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation based on the adjoint Jacobian.
Reimplemented from ROL::Constraint< Real >.
Definition at line 90 of file ROL_RiskNeutralConstraint.hpp.
References ROL::RiskNeutralConstraint< Real >::con_, ROL::Vector< Real >::dual(), ROL::RiskNeutralConstraint< Real >::init(), ROL::RiskNeutralConstraint< Real >::optVec_, ROL::RiskNeutralConstraint< Real >::xsampler_, and ROL::Vector< Real >::zero().
Member Data Documentation
con_
template<class Real > const Ptr<Constraint<Real> > ROL::RiskNeutralConstraint< Real >::con_ private
Definition at line 23 of file ROL_RiskNeutralConstraint.hpp.
Referenced by ROL::RiskNeutralConstraint< Real >::applyAdjointHessian(), ROL::RiskNeutralConstraint< Real >::applyAdjointJacobian(), ROL::RiskNeutralConstraint< Real >::applyJacobian(), ROL::RiskNeutralConstraint< Real >::update(), ROL::RiskNeutralConstraint< Real >::update(), and ROL::RiskNeutralConstraint< Real >::value().
xsampler_
template<class Real > const Ptr<SampleGenerator<Real> > ROL::RiskNeutralConstraint< Real >::xsampler_ private
Definition at line 24 of file ROL_RiskNeutralConstraint.hpp.
Referenced by ROL::RiskNeutralConstraint< Real >::applyAdjointHessian(), ROL::RiskNeutralConstraint< Real >::applyAdjointJacobian(), ROL::RiskNeutralConstraint< Real >::applyJacobian(), and ROL::RiskNeutralConstraint< Real >::value().
cbman_
template<class Real > const Ptr<BatchManager<Real> > ROL::RiskNeutralConstraint< Real >::cbman_ private
Definition at line 25 of file ROL_RiskNeutralConstraint.hpp.
Referenced by ROL::RiskNeutralConstraint< Real >::applyJacobian(), and ROL::RiskNeutralConstraint< Real >::value().
conVec_
template<class Real > Ptr<Vector<Real> > ROL::RiskNeutralConstraint< Real >::conVec_ private
Definition at line 27 of file ROL_RiskNeutralConstraint.hpp.
Referenced by ROL::RiskNeutralConstraint< Real >::applyJacobian(), ROL::RiskNeutralConstraint< Real >::init(), and ROL::RiskNeutralConstraint< Real >::value().
optVec_
template<class Real > Ptr<Vector<Real> > ROL::RiskNeutralConstraint< Real >::optVec_ private
Definition at line 28 of file ROL_RiskNeutralConstraint.hpp.
Referenced by ROL::RiskNeutralConstraint< Real >::applyAdjointHessian(), ROL::RiskNeutralConstraint< Real >::applyAdjointJacobian(), and ROL::RiskNeutralConstraint< Real >::init().
initialized_
template<class Real > bool ROL::RiskNeutralConstraint< Real >::initialized_ private
Definition at line 30 of file ROL_RiskNeutralConstraint.hpp.
Referenced by ROL::RiskNeutralConstraint< Real >::init().
The documentation for this class was generated from the following file:
ROL_RiskNeutralConstraint.hpp