ROL: ROL::BackTracking_U< Real > Class Template Reference
ROL::BackTracking_U< Real > Class Template Reference
Implements a simple back tracking line search.
#include <ROL_BackTracking_U.hpp>
Public Member Functions
BackTracking_U (ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &g) override
void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj) override
Public Member Functions inherited from ROL::LineSearch_U< Real >
virtual ~LineSearch_U ()
LineSearch_U (ParameterList &parlist)
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Private Attributes
Real rho_
Ptr< Vector< Real > > xnew_
Additional Inherited Members
Protected Member Functions inherited from ROL::LineSearch_U< Real >
virtual bool status (const ELineSearchU type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj)
void setNextInitialAlpha (Real alpha)
bool useLocalMinimizer ()
bool takeNoStep ()
Detailed Description
template<typename Real>
class ROL::BackTracking_U< Real >
Implements a simple back tracking line search.
Definition at line 22 of file ROL_BackTracking_U.hpp.
Constructor & Destructor Documentation
BackTracking_U()
template<typename Real > ROL::BackTracking_U< Real >::BackTracking_U (ParameterList & parlist) inline
Definition at line 32 of file ROL_BackTracking_U.hpp.
References ROL::BackTracking_U< Real >::rho_.
Member Function Documentation
initialize()
template<typename Real > void ROL::BackTracking_U< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g) inline override virtual
Reimplemented from ROL::LineSearch_U< Real >.
Definition at line 37 of file ROL_BackTracking_U.hpp.
References ROL::Vector< Real >::clone(), ROL::LineSearch_U< Real >::initialize(), and ROL::BackTracking_U< Real >::xnew_.
run()
template<typename Real > void ROL::BackTracking_U< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj) inline override virtual
Implements ROL::LineSearch_U< Real >.
Definition at line 42 of file ROL_BackTracking_U.hpp.
References ROL::LineSearch_U< Real >::getInitialAlpha(), ROL::LINESEARCH_U_BACKTRACKING, ROL::BackTracking_U< Real >::rho_, ROL::LineSearch_U< Real >::status(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::BackTracking_U< Real >::xnew_.
Member Data Documentation
rho_
template<typename Real > Real ROL::BackTracking_U< Real >::rho_ private
Definition at line 24 of file ROL_BackTracking_U.hpp.
Referenced by ROL::BackTracking_U< Real >::BackTracking_U(), and ROL::BackTracking_U< Real >::run().
xnew_
template<typename Real > Ptr<Vector<Real> > ROL::BackTracking_U< Real >::xnew_ private
Definition at line 25 of file ROL_BackTracking_U.hpp.
Referenced by ROL::BackTracking_U< Real >::initialize(), and ROL::BackTracking_U< Real >::run().
The documentation for this class was generated from the following file:
ROL_BackTracking_U.hpp