ROL: ROL::EntropicRisk< Real > Class Template Reference
ROL::EntropicRisk< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for the entropic risk.
#include <ROL_EntropicRisk.hpp>
Public Member Functions
EntropicRisk (const Real coeff=1)
Constructor.
EntropicRisk (ROL::ParameterList &parlist)
Constructor.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void initialize (const Vector< Real > &x)
Initialize temporary variables.
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Member Functions
void checkInputs (void) const
Private Attributes
Real coeff_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::EntropicRisk< Real >
Provides an interface for the entropic risk.
The entropic risk measure (also called the exponential utility and the log-exponential risk measure) is
\[ \mathcal{R}(X) = \lambda \log\mathbb{E}\left[\exp\left(\frac{X}{\lambda}\right)\right] \]
for \(\lambda > 0\). The entropic risk is convex, translation equivariant and monotonic.
Definition at line 32 of file ROL_EntropicRisk.hpp.
Constructor & Destructor Documentation
EntropicRisk() [1/2]
template<class Real > ROL::EntropicRisk< Real >::EntropicRisk (const Real coeff = 1) inline
Constructor.
Parameters
[in] coeff is the scale parameter \(\lambda\)
Definition at line 61 of file ROL_EntropicRisk.hpp.
References ROL::EntropicRisk< Real >::checkInputs().
EntropicRisk() [2/2]
template<class Real > ROL::EntropicRisk< Real >::EntropicRisk (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measures"->"Entropic Risk" and withing the "Entropic Risk" sublist should have
"Rate" (greater than 0).
Definition at line 74 of file ROL_EntropicRisk.hpp.
References ROL::EntropicRisk< Real >::checkInputs(), and ROL::EntropicRisk< Real >::coeff_.
Member Function Documentation
checkInputs()
template<class Real > void ROL::EntropicRisk< Real >::checkInputs (void) const inline private
Definition at line 50 of file ROL_EntropicRisk.hpp.
References ROL::EntropicRisk< Real >::coeff_, and zero.
Referenced by ROL::EntropicRisk< Real >::EntropicRisk(), and ROL::EntropicRisk< Real >::EntropicRisk().
updateValue()
template<class Real > void ROL::EntropicRisk< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 82 of file ROL_EntropicRisk.hpp.
References ROL::EntropicRisk< Real >::coeff_, ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::EntropicRisk< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 90 of file ROL_EntropicRisk.hpp.
References ROL::EntropicRisk< Real >::coeff_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateGradient()
template<class Real > void ROL::EntropicRisk< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 98 of file ROL_EntropicRisk.hpp.
References ROL::EntropicRisk< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getGradient()
template<class Real > void ROL::EntropicRisk< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 109 of file ROL_EntropicRisk.hpp.
References ROL::RandVarFunctional< Real >::g_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateHessVec()
template<class Real > void ROL::EntropicRisk< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 120 of file ROL_EntropicRisk.hpp.
References ROL::EntropicRisk< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::RandVarFunctional< Real >::hv_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getHessVec()
template<class Real > void ROL::EntropicRisk< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 137 of file ROL_EntropicRisk.hpp.
References ROL::Vector< Real >::axpy(), ROL::EntropicRisk< Real >::coeff_, ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::RandVarFunctional< Real >::hv_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
Member Data Documentation
coeff_
template<class Real > Real ROL::EntropicRisk< Real >::coeff_ private
Definition at line 34 of file ROL_EntropicRisk.hpp.
Referenced by ROL::EntropicRisk< Real >::checkInputs(), ROL::EntropicRisk< Real >::EntropicRisk(), ROL::EntropicRisk< Real >::getHessVec(), ROL::EntropicRisk< Real >::getValue(), ROL::EntropicRisk< Real >::updateGradient(), ROL::EntropicRisk< Real >::updateHessVec(), and ROL::EntropicRisk< Real >::updateValue().
The documentation for this class was generated from the following file:
ROL_EntropicRisk.hpp