ROL: ROL::Constraint_SimOpt< Real > Class Template Reference
ROL::Constraint_SimOpt< Real > Class Template Reference abstract
User Interface » Functional Interface
Defines the constraint operator interface for simulation-based optimization.
#include <ROL_Constraint_SimOpt.hpp>
Public Member Functions
Constraint_SimOpt ()
virtual void update (const Vector< Real > &u, const Vector< Real > &z, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
virtual void update_1 (const Vector< Real > &u, bool flag=true, int iter=-1)
Update constraint functions with respect to Sim variable.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_1 (const Vector< Real > &u, UpdateType type, int iter=-1)
virtual void update_2 (const Vector< Real > &z, bool flag=true, int iter=-1)
Update constraint functions with respect to Opt variable. x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_2 (const Vector< Real > &z, UpdateType type, int iter=-1)
virtual void solve_update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
Update SimOpt constraint during solve (disconnected from optimization updates).
virtual void value (Vector< Real > &c, const Vector< Real > &u, const Vector< Real > &z, Real &tol)=0
Evaluate the constraint operator \(c:\mathcal{U}\times\mathcal{Z} \rightarrow \mathcal{C}\) at \((u,z)\).
virtual void solve (Vector< Real > &c, Vector< Real > &u, const Vector< Real > &z, Real &tol)
Given \(z\), solve \(c(u,z)=0\) for \(u\).
virtual void setSolveParameters (ParameterList &parlist)
Set solve parameters.
virtual void applyJacobian_1 (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the partial constraint Jacobian at \((u,z)\), \(c_u(u,z) \in L(\mathcal{U}, \mathcal{C})\), to the vector \(v\).
virtual void applyJacobian_2 (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the partial constraint Jacobian at \((u,z)\), \(c_z(u,z) \in L(\mathcal{Z}, \mathcal{C})\), to the vector \(v\).
virtual void applyInverseJacobian_1 (Vector< Real > &ijv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the inverse partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-1} \in L(\mathcal{C}, \mathcal{U})\), to the vector \(v\).
virtual void applyAdjointJacobian_1 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the primary interface.
virtual void applyAdjointJacobian_1 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual void applyAdjointJacobian_2 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the primary interface.
virtual void applyAdjointJacobian_2 (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual void applyInverseAdjointJacobian_1 (Vector< Real > &iajv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the inverse of the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-*} \in L(\mathcal{U}^*, \mathcal{C}^*)\), to the vector \(v\).
virtual void applyAdjointHessian_11 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_12 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the optimization-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uz}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_21 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the simulation-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_22 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the optimization-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zz}(u,z)(v,\cdot)^*w\).
virtual std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol)
Approximately solves the augmented system
virtual void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C})\), to vector \(v\). In general, this preconditioner satisfies the following relationship:
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update constraint function.
virtual void value (Vector< Real > &c, const Vector< Real > &x, Real &tol)
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
virtual void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual void applyAdjointHessian (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
virtual Real checkSolve (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &c, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian_1 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
virtual Real checkAdjointConsistencyJacobian_1 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual Real checkAdjointConsistencyJacobian_2 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
virtual Real checkAdjointConsistencyJacobian_2 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual Real checkInverseJacobian_1 (const Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkInverseAdjointJacobian_1 (const Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
std::vector< std::vector< Real > > checkApplyJacobian_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Protected Attributes
Real atol_
Real rtol_
Real stol_
Real factor_
Real decr_
int maxit_
bool print_
bool zero_
int solverType_
bool firstSolve_
Private Attributes
Ptr< Vector< Real > > unew_
Ptr< Vector< Real > > jv_
const Real DEFAULT_atol_
const Real DEFAULT_rtol_
const Real DEFAULT_stol_
const Real DEFAULT_factor_
const Real DEFAULT_decr_
const int DEFAULT_maxit_
const bool DEFAULT_print_
const bool DEFAULT_zero_
const int DEFAULT_solverType_
Additional Inherited Members
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::Constraint_SimOpt< Real >
Defines the constraint operator interface for simulation-based optimization.
This constraint interface inherits from ROL_Constraint, for the use case when \(\mathcal{X}=\mathcal{U}\times\mathcal{Z}\) where \(\mathcal{U}\) and \(\mathcal{Z}\) are Banach spaces. \(\mathcal{U}\) denotes the "simulation space" and \(\mathcal{Z}\) denotes the "optimization space" (of designs, controls, parameters). The simulation-based constraints are of the form
\[ c(u,z) = 0 \,. \]
The basic operator interface, to be implemented by the user, requires:
value – constraint evaluation.
applyJacobian_1 – action of the partial constraint Jacobian –derivatives are with respect to the first component \(\mathcal{U}\);
applyJacobian_2 – action of the partial constraint Jacobian –derivatives are with respect to the second component \(\mathcal{Z}\);
applyAdjointJacobian_1 – action of the adjoint of the partial constraint Jacobian –derivatives are with respect to the first component \(\mathcal{U}\);
applyAdjointJacobian_2 – action of the adjoint of the partial constraint Jacobian –derivatives are with respect to the second component \(\mathcal{Z}\);
The user may also overload:
applyAdjointHessian_11 – action of the adjoint of the partial constraint Hessian –derivatives are with respect to the first component only;
applyAdjointHessian_12 – action of the adjoint of the partial constraint Hessian –derivatives are with respect to the first and second components;
applyAdjointHessian_21 – action of the adjoint of the partial constraint Hessian –derivatives are with respect to the second and first components;
applyAdjointHessian_22 – action of the adjoint of the partial constraint Hessian –derivatives are with respect to the second component only;
solveAugmentedSystem – solution of the augmented system –the default is an iterative scheme based on the action of the Jacobian and its adjoint.
applyPreconditioner – action of a constraint preconditioner –the default is null-op.
Definition at line 74 of file ROL_Constraint_SimOpt.hpp.
Constructor & Destructor Documentation
Constraint_SimOpt()
template<class Real > ROL::Constraint_SimOpt< Real >::Constraint_SimOpt () inline
Definition at line 108 of file ROL_Constraint_SimOpt.hpp.
Member Function Documentation
update() [1/4]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update (const Vector< Real > & u, const Vector< Real > & z, bool flag = true, int iter = -1) inline virtual
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented in ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 129 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::update_1(), and ROL::Constraint_SimOpt< Real >::update_2().
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22(), ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2(), ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1(), ROL::Constraint_SimOpt< Real >::checkSolve(), ROL::Constraint_SimOpt< Real >::update(), and ROL::Constraint_SimOpt< Real >::update().
update() [2/4]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update (const Vector< Real > & u, const Vector< Real > & z, UpdateType type, int iter = -1) inline virtual
Reimplemented in ROL::CompositeConstraint_SimOpt< Real >.
Definition at line 133 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::update_1(), and ROL::Constraint_SimOpt< Real >::update_2().
update_1() [1/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update_1 (const Vector< Real > & u, bool flag = true, int iter = -1) inline virtual
Update constraint functions with respect to Sim variable.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented in ROL::CompositeConstraint_SimOpt< Real >.
Definition at line 143 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::update(), and ROL::Constraint_SimOpt< Real >::update().
update_1() [2/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update_1 (const Vector< Real > & u, UpdateType type, int iter = -1) inline virtual
Reimplemented in ROL::CompositeConstraint_SimOpt< Real >.
Definition at line 144 of file ROL_Constraint_SimOpt.hpp.
update_2() [1/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update_2 (const Vector< Real > & z, bool flag = true, int iter = -1) inline virtual
Update constraint functions with respect to Opt variable. x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented in ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 151 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::update(), and ROL::Constraint_SimOpt< Real >::update().
update_2() [2/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update_2 (const Vector< Real > & z, UpdateType type, int iter = -1) inline virtual
Reimplemented in ROL::CompositeConstraint_SimOpt< Real >.
Definition at line 152 of file ROL_Constraint_SimOpt.hpp.
solve_update()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::solve_update (const Vector< Real > & u, const Vector< Real > & z, UpdateType type, int iter = -1) inline virtual
Update SimOpt constraint during solve (disconnected from optimization updates).
      @param[in]    x is the optimization variable
      @param[in] type is the update type
      @param[in] iter is the solver iteration count
Reimplemented in ROL::CompositeConstraint_SimOpt< Real >.
Definition at line 160 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::solve().
value() [1/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::value (Vector< Real > & c, const Vector< Real > & u, const Vector< Real > & z, Real & tol) pure virtual
Evaluate the constraint operator \(c:\mathcal{U}\times\mathcal{Z} \rightarrow \mathcal{C}\) at \((u,z)\).
Parameters
[out] c is the result of evaluating the constraint operator at \((u,z)\); a constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(u,z)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{u} \in \mathcal{U}\), and $ \(\mathsf{z} \in\mathcal{Z}\).
Implemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2(), ROL::Constraint_SimOpt< Real >::checkSolve(), ROL::Constraint_SimOpt< Real >::solve(), and ROL::Constraint_SimOpt< Real >::value().
solve()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::solve (Vector< Real > & c, Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Given \(z\), solve \(c(u,z)=0\) for \(u\).
   @param[out]      c   is the result of evaluating the constraint operator at @b \f$(u,z)\f$; a constraint-space vector
   @param[in,out]   u   is the solution vector; a simulation-space vector
   @param[in]       z   is the constraint argument; an optimization-space vector
   @param[in,out]   tol is a tolerance for inexact evaluations; currently unused
   The defualt implementation is Newton's method globalized with a backtracking line search.
   ---
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, constraint1< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 191 of file ROL_Constraint_SimOpt.hpp.
References ROL::Accept, ROL::Constraint_SimOpt< Real >::applyInverseJacobian_1(), ROL::Constraint_SimOpt< Real >::atol_, ROL::Vector< Real >::clone(), ROL::Constraint_SimOpt< Real >::decr_, ROL::Vector< Real >::dual(), ROL::Constraint_SimOpt< Real >::factor_, ROL::Constraint_SimOpt< Real >::firstSolve_, ROL::Initial, ROL::Constraint_SimOpt< Real >::jv_, ROL::Constraint_SimOpt< Real >::maxit_, ROL::Vector< Real >::norm(), ROL::Constraint_SimOpt< Real >::print_, ROL::Constraint_SimOpt< Real >::rtol_, ROL::Vector< Real >::set(), ROL::Constraint_SimOpt< Real >::solve_update(), ROL::Constraint_SimOpt< Real >::solverType_, ROL::Constraint_SimOpt< Real >::stol_, ROL::Trial, ROL::Constraint_SimOpt< Real >::unew_, ROL::Constraint_SimOpt< Real >::value(), ROL::Vector< Real >::zero(), and ROL::Constraint_SimOpt< Real >::zero_.
Referenced by ROL::Constraint_SimOpt< Real >::checkSolve(), and Constraint_BurgersControl< Real >::solve().
setSolveParameters()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::setSolveParameters (ParameterList & parlist) inline virtual
Set solve parameters.
   @param[in]       parlist   ParameterList containing solve parameters
   For the default implementation, parlist has two sublist ("SimOpt"
   and "Solve") and the "Solve" sublist has six input parameters.
      - "Residual Tolerance": Absolute tolerance for the norm of the residual (Real)
      - "Iteration Limit": Maximum number of Newton iterations (int)
      - "Sufficient Decrease Tolerance": Tolerance signifying sufficient decrease in the residual norm, between 0 and 1 (Real)
      - "Step Tolerance": Absolute tolerance for the step size parameter (Real)
      - "Backtracking Factor": Rate for decreasing step size during backtracking, between 0 and 1 (Real)
      - "Output Iteration History": Set to true in order to print solve iteration history (bool)
      - "Zero Initial Guess": Use a vector of zeros as an initial guess for the solve (bool)
      - "Solver Type": Determine which solver to use (0: Newton with line search, 1: Levenberg-Marquardt, 2: SQP) (int)
   These parameters are accessed as parlist.sublist("SimOpt").sublist("Solve").get(...).
   ---
Definition at line 303 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::atol_, ROL::Constraint_SimOpt< Real >::decr_, ROL::Constraint_SimOpt< Real >::DEFAULT_atol_, ROL::Constraint_SimOpt< Real >::DEFAULT_decr_, ROL::Constraint_SimOpt< Real >::DEFAULT_factor_, ROL::Constraint_SimOpt< Real >::DEFAULT_maxit_, ROL::Constraint_SimOpt< Real >::DEFAULT_print_, ROL::Constraint_SimOpt< Real >::DEFAULT_rtol_, ROL::Constraint_SimOpt< Real >::DEFAULT_solverType_, ROL::Constraint_SimOpt< Real >::DEFAULT_stol_, ROL::Constraint_SimOpt< Real >::DEFAULT_zero_, ROL::Constraint_SimOpt< Real >::factor_, ROL::Constraint_SimOpt< Real >::maxit_, ROL::Constraint_SimOpt< Real >::print_, ROL::Constraint_SimOpt< Real >::rtol_, ROL::Constraint_SimOpt< Real >::solverType_, ROL::Constraint_SimOpt< Real >::stol_, and ROL::Constraint_SimOpt< Real >::zero_.
Referenced by main().
applyJacobian_1()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyJacobian_1 (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the partial constraint Jacobian at \((u,z)\), \(c_u(u,z) \in L(\mathcal{U}, \mathcal{C})\), to the vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at \((u,z)\); a constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; an simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c_u(u,z)v\), where \(v \in \mathcal{U}\), \(\mathsf{jv} \in \mathcal{C}\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 331 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), and ROL::Constraint_SimOpt< Real >::value().
Referenced by ROL::Constraint_SimOpt< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1(), and ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1().
applyJacobian_2()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyJacobian_2 (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the partial constraint Jacobian at \((u,z)\), \(c_z(u,z) \in L(\mathcal{Z}, \mathcal{C})\), to the vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at \((u,z)\); a constraint-space vector
[in] v is an optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c_z(u,z)v\), where \(v \in \mathcal{Z}\), \(\mathsf{jv} \in \mathcal{C}\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 374 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), and ROL::Constraint_SimOpt< Real >::value().
Referenced by ROL::Constraint_SimOpt< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), and ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2().
applyInverseJacobian_1()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyInverseJacobian_1 (Vector< Real > & ijv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the inverse partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-1} \in L(\mathcal{C}, \mathcal{U})\), to the vector \(v\).
Parameters
[out] ijv is the result of applying the inverse constraint Jacobian to v at \((u,z)\); a simulation-space vector
[in] v is a constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ijv} = c_u(u,z)^{-1}v\), where \(v \in \mathcal{C}\), \(\mathsf{ijv} \in \mathcal{U}\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, redConstraint< Real >, constraint1< Real >, DiffusionConstraint< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 416 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::applyPreconditioner(), ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1(), and ROL::Constraint_SimOpt< Real >::solve().
applyAdjointJacobian_1() [1/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1 (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the primary interface.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at (u,z); a dual simulation-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_u(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{U}^*\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, DiffusionConstraint< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 440 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), and ROL::Vector< Real >::dual().
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21(), and ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1().
applyAdjointJacobian_1() [2/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1 (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & dualv, Real & tol) inline virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at (u,z); a dual simulation-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] dualv is a vector used for temporary variables; a constraint-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_u(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{U}^*\).
Reimplemented in ROL::Constraint_SerialSimOpt< Real >, and ROL::SerialConstraint< Real >.
Definition at line 466 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::norm(), ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), ROL::Constraint_SimOpt< Real >::value(), and ROL::Vector< Real >::zero().
applyAdjointJacobian_2() [1/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2 (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the primary interface.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at \((u,z)\); a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_z(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{Z}^*\).
Reimplemented in valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 511 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), and ROL::Vector< Real >::dual().
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12(), and ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22().
applyAdjointJacobian_2() [2/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2 (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & dualv, Real & tol) inline virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at \((u,z)\); a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] dualv is a vector used for temporary variables; a constraint-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_z(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{Z}^*\).
Reimplemented in ROL::Constraint_SerialSimOpt< Real >.
Definition at line 537 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::norm(), ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), ROL::Constraint_SimOpt< Real >::value(), and ROL::Vector< Real >::zero().
applyInverseAdjointJacobian_1()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyInverseAdjointJacobian_1 (Vector< Real > & iajv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the inverse of the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-*} \in L(\mathcal{U}^*, \mathcal{C}^*)\), to the vector \(v\).
Parameters
[out] iajv is the result of applying the inverse adjoint of the constraint Jacobian to v at (u,z); a dual constraint-space vector
[in] v is a dual simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{iajv} = c_u(u,z)^{-*}v\), where \(v \in \mathcal{U}^*\), \(\mathsf{iajv} \in \mathcal{C}^*\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, constraint1< Real >, Constraint_BurgersControl< Real >, redConstraint< Real >, DiffusionConstraint< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::Constraint_TimeSimOpt< Real >, and ROL::CompositeConstraint_SimOpt< Real >.
Definition at line 581 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::applyPreconditioner(), and ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1().
applyAdjointHessian_11()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, Constraint_BurgersControl< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::Constraint_SerialSimOpt< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 607 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), and ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11().
applyAdjointHessian_12()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the optimization-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uz}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the optimization-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual optimization-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uz}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{Z}^*\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 652 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), and ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12().
applyAdjointHessian_21()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the simulation-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{zu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{Z}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 697 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), and ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21().
applyAdjointHessian_22()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22 (Vector< Real > & ahwv, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply the optimization-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zz}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the optimization-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual optimization-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{zz}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{Z}\), and \(\mathsf{ahwv} \in \mathcal{Z}^*\).
Reimplemented in Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, Constraint_BurgersControl< Real >, DiffusionConstraint< Real >, Constraint_BurgersControl< Real >, valConstraint< Real >, redConstraint< Real >, constraint1< Real >, constraint2< Real >, ROL::SerialConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, and ROL::Constraint_TimeSimOpt< Real >.
Definition at line 741 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), and ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22().
solveAugmentedSystem()
template<class Real > virtual std::vector< Real > ROL::Constraint_SimOpt< Real >::solveAugmentedSystem (Vector< Real > & v1, Vector< Real > & v2, const Vector< Real > & b1, const Vector< Real > & b2, const Vector< Real > & x, Real & tol) inline virtual
Approximately solves the augmented system
\[ \begin{pmatrix} I & c'(x)^* \\ c'(x) & 0 \end{pmatrix} \begin{pmatrix} v_{1} \\ v_{2} \end{pmatrix} = \begin{pmatrix} b_{1} \\ b_{2} \end{pmatrix} \]
where \(v_{1} \in \mathcal{X}\), \(v_{2} \in \mathcal{C}^*\), \(b_{1} \in \mathcal{X}^*\), \(b_{2} \in \mathcal{C}\), \(I : \mathcal{X} \rightarrow \mathcal{X}^*\) is an identity operator, and \(0 : \mathcal{C}^* \rightarrow \mathcal{C}\) is a zero operator.
Parameters
[out] v1 is the optimization-space component of the result
[out] v2 is the dual constraint-space component of the result
[in] b1 is the dual optimization-space component of the right-hand side
[in] b2 is the constraint-space component of the right-hand side
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is the nominal relative residual tolerance
On return, \([\mathsf{v1} \,\, \mathsf{v2}] \) approximately solves the augmented system, where the size of the residual is governed by special stopping conditions.
The default implementation is the preconditioned generalized minimal residual (GMRES) method, which enables the use of nonsymmetric preconditioners.
Reimplemented from ROL::Constraint< Real >.
Definition at line 806 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint< Real >::solveAugmentedSystem().
applyPreconditioner()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyPreconditioner (Vector< Real > & pv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g, Real & tol) inline virtual
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C})\), to vector \(v\). In general, this preconditioner satisfies the following relationship:
\[ c'(x) c'(x)^* P(x) v \approx v \,. \]
It is used by the solveAugmentedSystem method.
Parameters
[out] pv is the result of applying the constraint preconditioner to v at x; a constraint-space vector
[in] v is a constraint-space vector
[in] x is the preconditioner argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations
On return, \(\mathsf{pv} = P(x)v\), where \(v \in \mathcal{C}\), \(\mathsf{pv} \in \mathcal{C}\).
The default implementation is a null-op.
Reimplemented from ROL::Constraint< Real >.
Definition at line 834 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyInverseAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyInverseJacobian_1(), ROL::Constraint< Real >::applyPreconditioner(), ROL::Vector_SimOpt< Real >::dual(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Vector< Real >::set().
update() [3/4]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 869 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Constraint_SimOpt< Real >::update().
update() [4/4]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update constraint function.
This function updates the constraint function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 874 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Constraint_SimOpt< Real >::update().
value() [2/2]
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::value (Vector< Real > & c, const Vector< Real > & x, Real & tol) inline virtual
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
Parameters
[out] c is the result of evaluating the constraint operator at x; a constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(x)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{x} \in \mathcal{X}\).
Implements ROL::Constraint< Real >.
Definition at line 880 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Constraint_SimOpt< Real >::value().
applyJacobian()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyJacobian (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at x; a constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c'(x)v\), where \(v \in \mathcal{X}\), \(\mathsf{jv} \in \mathcal{C}\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 889 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Vector< Real >::clone(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Vector< Real >::plus().
applyAdjointJacobian()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointJacobian (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at x; a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c'(x)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 905 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::set_1(), and ROL::Vector_SimOpt< Real >::set_2().
applyAdjointHessian()
template<class Real > virtual void ROL::Constraint_SimOpt< Real >::applyAdjointHessian (Vector< Real > & ahuv, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
Parameters
[out] ahuv is the result of applying the derivative of the adjoint of the constraint Jacobian at x to vector u in direction v; a dual optimization-space vector
[in] u is the direction vector; a dual constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahuv} = c''(x)(v,\cdot)^*u \), where \(u \in \mathcal{C}^*\), \(v \in \mathcal{X}\), and \(\mathsf{ahuv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation based on the adjoint Jacobian.
Reimplemented from ROL::Constraint< Real >.
Definition at line 922 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::set_1(), and ROL::Vector_SimOpt< Real >::set_2().
checkSolve()
template<class Real > virtual Real ROL::Constraint_SimOpt< Real >::checkSolve (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & c, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Reimplemented in ROL::Constraint_TimeSimOpt< Real >.
Definition at line 951 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector< Real >::clone(), ROL::Constraint_SimOpt< Real >::solve(), ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), and ROL::Constraint_SimOpt< Real >::value().
Referenced by main().
checkAdjointConsistencyJacobian_1() [1/2]
template<class Real > virtual Real ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1 (const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
Parameters
[out] w is a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] printToStream is is a flag that turns on/off output
[in] outStream is the output stream
Definition at line 992 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), and ROL::Vector< Real >::dual().
Referenced by ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), and main().
checkAdjointConsistencyJacobian_1() [2/2]
template<class Real > virtual Real ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1 (const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & dualw, const Vector< Real > & dualv, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
Parameters
[out] w is a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] dualw is a constraint-space vector
[in] dualv is a dual simulation-space vector
[in] printToStream is is a flag that turns on/off output
[in] outStream is the output stream
Definition at line 1017 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector< Real >::apply(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Vector< Real >::clone(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
checkAdjointConsistencyJacobian_2() [1/2]
template<class Real > virtual Real ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2 (const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
Parameters
[out] w is a dual constraint-space vector
[in] v is an optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] printToStream is is a flag that turns on/off output
[in] outStream is the output stream
Definition at line 1062 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), and ROL::Vector< Real >::dual().
Referenced by ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), and main().
checkAdjointConsistencyJacobian_2() [2/2]
template<class Real > virtual Real ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2 (const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & dualw, const Vector< Real > & dualv, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
Parameters
[out] w is a dual constraint-space vector
[in] v is an optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] dualw is a constraint-space vector
[in] dualv is a dual optimization-space vector
[in] printToStream is is a flag that turns on/off output
[in] outStream is the output stream
Definition at line 1086 of file ROL_Constraint_SimOpt.hpp.
References ROL::Vector< Real >::apply(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Vector< Real >::clone(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
checkInverseJacobian_1()
template<class Real > virtual Real ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1 (const Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Definition at line 1118 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyInverseJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
Referenced by main().
checkInverseAdjointJacobian_1()
template<class Real > virtual Real ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1 (const Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Definition at line 1148 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyInverseAdjointJacobian_1(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Temp, and ROL::Constraint_SimOpt< Real >::update().
Referenced by main().
checkApplyJacobian_1() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const Vector< Real > & jv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1180 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1().
Referenced by ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1(), and main().
checkApplyJacobian_1() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const Vector< Real > & jv, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 1199 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), ROL::Constraint_SimOpt< Real >::value(), and ROL::Finite_Difference_Arrays::weights.
checkApplyJacobian_2() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const Vector< Real > & jv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1305 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2().
Referenced by ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2(), and main().
checkApplyJacobian_2() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const Vector< Real > & jv, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 1324 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), ROL::Constraint_SimOpt< Real >::value(), and ROL::Finite_Difference_Arrays::weights.
checkApplyAdjointHessian_11() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1431 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11().
Referenced by ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11(), and main().
checkApplyAdjointHessian_11() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 1449 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
checkApplyAdjointHessian_21() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
Definition at line 1554 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21().
Referenced by ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21(), and main().
checkApplyAdjointHessian_21() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
Definition at line 1575 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
checkApplyAdjointHessian_12() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
Definition at line 1680 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12().
Referenced by ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12(), and main().
checkApplyAdjointHessian_12() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 1699 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
checkApplyAdjointHessian_22() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1801 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22().
Referenced by ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22(), and main().
checkApplyAdjointHessian_22() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & p, const Vector< Real > & v, const Vector< Real > & hv, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 1819 of file ROL_Constraint_SimOpt.hpp.
References ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Constraint_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
Member Data Documentation
unew_
template<class Real > Ptr<Vector<Real> > ROL::Constraint_SimOpt< Real >::unew_ private
Definition at line 77 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::solve().
jv_
template<class Real > Ptr<Vector<Real> > ROL::Constraint_SimOpt< Real >::jv_ private
Definition at line 78 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::solve().
DEFAULT_atol_
template<class Real > const Real ROL::Constraint_SimOpt< Real >::DEFAULT_atol_ private
Definition at line 81 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_rtol_
template<class Real > const Real ROL::Constraint_SimOpt< Real >::DEFAULT_rtol_ private
Definition at line 82 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_stol_
template<class Real > const Real ROL::Constraint_SimOpt< Real >::DEFAULT_stol_ private
Definition at line 83 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_factor_
template<class Real > const Real ROL::Constraint_SimOpt< Real >::DEFAULT_factor_ private
Definition at line 84 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_decr_
template<class Real > const Real ROL::Constraint_SimOpt< Real >::DEFAULT_decr_ private
Definition at line 85 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_maxit_
template<class Real > const int ROL::Constraint_SimOpt< Real >::DEFAULT_maxit_ private
Definition at line 86 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_print_
template<class Real > const bool ROL::Constraint_SimOpt< Real >::DEFAULT_print_ private
Definition at line 87 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_zero_
template<class Real > const bool ROL::Constraint_SimOpt< Real >::DEFAULT_zero_ private
Definition at line 88 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
DEFAULT_solverType_
template<class Real > const int ROL::Constraint_SimOpt< Real >::DEFAULT_solverType_ private
Definition at line 89 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters().
atol_
template<class Real > Real ROL::Constraint_SimOpt< Real >::atol_ protected
Definition at line 94 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
rtol_
template<class Real > Real ROL::Constraint_SimOpt< Real >::rtol_ protected
Definition at line 95 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
stol_
template<class Real > Real ROL::Constraint_SimOpt< Real >::stol_ protected
Definition at line 96 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
factor_
template<class Real > Real ROL::Constraint_SimOpt< Real >::factor_ protected
Definition at line 97 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
decr_
template<class Real > Real ROL::Constraint_SimOpt< Real >::decr_ protected
Definition at line 98 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
maxit_
template<class Real > int ROL::Constraint_SimOpt< Real >::maxit_ protected
Definition at line 99 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
print_
template<class Real > bool ROL::Constraint_SimOpt< Real >::print_ protected
Definition at line 100 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
zero_
template<class Real > bool ROL::Constraint_SimOpt< Real >::zero_ protected
Definition at line 101 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
solverType_
template<class Real > int ROL::Constraint_SimOpt< Real >::solverType_ protected
Definition at line 102 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::setSolveParameters(), and ROL::Constraint_SimOpt< Real >::solve().
firstSolve_
template<class Real > bool ROL::Constraint_SimOpt< Real >::firstSolve_ protected
Definition at line 105 of file ROL_Constraint_SimOpt.hpp.
Referenced by ROL::Constraint_SimOpt< Real >::solve().
The documentation for this class was generated from the following file:
ROL_Constraint_SimOpt.hpp