ROL: ROL::SingletonVector< Real > Class Template Reference
ROL::SingletonVector< Real > Class Template Reference
#include <ROL_SingletonVector.hpp>
Public Member Functions
SingletonVector (Real value=Real(0))
Real getValue () const
void setValue (Real v)
void set (const V &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const V &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const V &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const V &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< V > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< V > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const V &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
void print (std::ostream &os) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual const Vector & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
using V = Vector< Real >
Private Member Functions
Real getValueX (const V &x) const
Private Attributes
Real value_
Detailed Description
template<class Real>
class ROL::SingletonVector< Real >
Definition at line 25 of file ROL_SingletonVector.hpp.
Member Typedef Documentation
V
template<class Real > using ROL::SingletonVector< Real >::V = Vector<Real> private
Definition at line 27 of file ROL_SingletonVector.hpp.
Constructor & Destructor Documentation
SingletonVector()
template<class Real > ROL::SingletonVector< Real >::SingletonVector (Real value = Real(0)) inline
Definition at line 39 of file ROL_SingletonVector.hpp.
Member Function Documentation
getValueX()
template<class Real > Real ROL::SingletonVector< Real >::getValueX (const V & x) const inline private
Definition at line 33 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::getValue().
Referenced by ROL::SingletonVector< Real >::applyBinary(), ROL::SingletonVector< Real >::axpy(), ROL::SingletonVector< Real >::dot(), ROL::SingletonVector< Real >::plus(), and ROL::SingletonVector< Real >::set().
getValue()
template<class Real > Real ROL::SingletonVector< Real >::getValue () const inline
Definition at line 41 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
Referenced by ROL::ScalarLinearConstraint< Real >::applyAdjointJacobian(), ROL::ScalarController< Real, Key >::get(), ROL::SingletonVector< Real >::getValueX(), and ROL::ScalarLinearConstraint< Real >::solveAugmentedSystem().
setValue()
template<class Real > void ROL::SingletonVector< Real >::setValue (Real v) inline
Definition at line 42 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
Referenced by ROL::ScalarLinearConstraint< Real >::applyJacobian(), ROL::ScalarLinearConstraint< Real >::solveAugmentedSystem(), and ROL::ScalarLinearConstraint< Real >::value().
set()
template<class Real > void ROL::SingletonVector< Real >::set (const V & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 44 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::getValueX(), and ROL::SingletonVector< Real >::value_.
plus()
template<class Real > void ROL::SingletonVector< Real >::plus (const V & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 48 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::getValueX(), and ROL::SingletonVector< Real >::value_.
axpy()
template<class Real > void ROL::SingletonVector< Real >::axpy (const Real alpha, const V & x) inline virtual
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of @b x.
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = \mathtt{*this} + \alpha x \f$.
   Uses #clone, #set, #scale and #plus for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 52 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::getValueX(), and ROL::SingletonVector< Real >::value_.
scale()
template<class Real > void ROL::SingletonVector< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 56 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
dot()
template<class Real > Real ROL::SingletonVector< Real >::dot (const V & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 60 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::getValueX(), and ROL::SingletonVector< Real >::value_.
norm()
template<class Real > Real ROL::SingletonVector< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 66 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
clone()
template<class Real > ROL::Ptr< V > ROL::SingletonVector< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 70 of file ROL_SingletonVector.hpp.
basis()
template<class Real > ROL::Ptr< V > ROL::SingletonVector< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 74 of file ROL_SingletonVector.hpp.
dimension()
template<class Real > int ROL::SingletonVector< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 81 of file ROL_SingletonVector.hpp.
applyUnary()
template<class Real > void ROL::SingletonVector< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 83 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
applyBinary()
template<class Real > void ROL::SingletonVector< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const V & x) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 87 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::getValueX(), and ROL::SingletonVector< Real >::value_.
reduce()
template<class Real > Real ROL::SingletonVector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 91 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
setScalar()
template<class Real > void ROL::SingletonVector< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 95 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
randomize()
template<class Real > void ROL::SingletonVector< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 99 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
print()
template<class Real > void ROL::SingletonVector< Real >::print (std::ostream & os) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 106 of file ROL_SingletonVector.hpp.
References ROL::SingletonVector< Real >::value_.
Member Data Documentation
value_
template<class Real > Real ROL::SingletonVector< Real >::value_ private
Definition at line 31 of file ROL_SingletonVector.hpp.
Referenced by ROL::SingletonVector< Real >::applyBinary(), ROL::SingletonVector< Real >::applyUnary(), ROL::SingletonVector< Real >::axpy(), ROL::SingletonVector< Real >::dot(), ROL::SingletonVector< Real >::getValue(), ROL::SingletonVector< Real >::norm(), ROL::SingletonVector< Real >::plus(), ROL::SingletonVector< Real >::print(), ROL::SingletonVector< Real >::randomize(), ROL::SingletonVector< Real >::reduce(), ROL::SingletonVector< Real >::scale(), ROL::SingletonVector< Real >::set(), ROL::SingletonVector< Real >::setScalar(), and ROL::SingletonVector< Real >::setValue().
The documentation for this class was generated from the following file:
ROL_SingletonVector.hpp