ROL: ROL::PartitionedVector< Real > Class Template Reference
ROL::PartitionedVector< Real > Class Template Reference
User Interface » Linear Algebra Interface
Defines the linear algebra of vector space on a generic partitioned vector.
#include <ROL_PartitionedVector.hpp>
Public Types
typedef std::vector< PV >::size_type size_type
Public Member Functions
PartitionedVector (const std::vector< Vp > &vecs)
void set (const V &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const V &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const V &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
Real dot (const V &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Vp clone () const
Clone to make a new (uninitialized) vector.
const V & dual (void) const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Vp basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void zero ()
Set to zero vector.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const V &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
void print (std::ostream &outStream) const
const Vector< Real > & operator[] (size_type i) const
Vector< Real > & operator[] (size_type i)
ROL::Ptr< const Vector< Real > > get (size_type i) const
ROL::Ptr< Vector< Real > > get (size_type i)
void set (size_type i, const V &x)
void zero (size_type i)
size_type numVectors () const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Static Public Member Functions
static Ptr< PartitionedVector > create (std::initializer_list< Vp > vs)
static Ptr< PartitionedVector > create (const V &x, size_type N)
Private Types
typedef Vector< Real > V
typedef ROL::Ptr< V > Vp
typedef PartitionedVector< Real > PV
Private Attributes
const std::vector< Vp > vecs_
std::vector< Vp > dual_vecs_
ROL::Ptr< PV > dual_pvec_
Detailed Description
template<class Real>
class ROL::PartitionedVector< Real >
Defines the linear algebra of vector space on a generic partitioned vector.
Definition at line 26 of file ROL_PartitionedVector.hpp.
Member Typedef Documentation
V
template<class Real > typedef Vector<Real> ROL::PartitionedVector< Real >::V private
Definition at line 28 of file ROL_PartitionedVector.hpp.
Vp
template<class Real > typedef ROL::Ptr<V> ROL::PartitionedVector< Real >::Vp private
Definition at line 29 of file ROL_PartitionedVector.hpp.
PV
template<class Real > typedef PartitionedVector<Real> ROL::PartitionedVector< Real >::PV private
Definition at line 30 of file ROL_PartitionedVector.hpp.
size_type
template<class Real > typedef std::vector<PV>::size_type ROL::PartitionedVector< Real >::size_type
Definition at line 38 of file ROL_PartitionedVector.hpp.
Constructor & Destructor Documentation
PartitionedVector()
template<class Real > ROL::PartitionedVector< Real >::PartitionedVector (const std::vector< Vp > & vecs) inline
Definition at line 40 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::clone(), ROL::PartitionedVector< Real >::dual(), ROL::PartitionedVector< Real >::dual_vecs_, and ROL::PartitionedVector< Real >::vecs_.
Member Function Documentation
set() [1/2]
template<class Real > void ROL::PartitionedVector< Real >::set (const V & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 46 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::numVectors(), and ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::HessianPDAS_Poly::apply(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse(), ROL::FletcherObjectiveE< Real >::AugSystemPrecond::applyInverse(), ROL::AugmentedSystemPrecOperator< Real >::applyInverse(), ROL::BoundFletcher< Real >::AugSystemPrecond::applyInverse(), ROL::Fletcher< Real >::AugSystemPrecond::applyInverse(), and ROL::PartitionedVector< Real >::basis().
plus()
template<class Real > void ROL::PartitionedVector< Real >::plus (const V & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 56 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::numVectors(), and ROL::PartitionedVector< Real >::vecs_.
scale()
template<class Real > void ROL::PartitionedVector< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 66 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
axpy()
template<class Real > void ROL::PartitionedVector< Real >::axpy (const Real alpha, const V & x) inline virtual
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of @b x.
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = \mathtt{*this} + \alpha x \f$.
   Uses #clone, #set, #scale and #plus for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 72 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::numVectors(), and ROL::PartitionedVector< Real >::vecs_.
dot()
template<class Real > Real ROL::PartitionedVector< Real >::dot (const V & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 83 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::numVectors(), and ROL::PartitionedVector< Real >::vecs_.
norm()
template<class Real > Real ROL::PartitionedVector< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 95 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::norm(), and ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::PartitionedVector< Real >::norm().
clone()
template<class Real > Vp ROL::PartitionedVector< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 103 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::clone(), and ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::PartitionedVector< Real >::basis(), ROL::PartitionedVector< Real >::clone(), and ROL::PartitionedVector< Real >::PartitionedVector().
dual()
template<class Real > const V & ROL::PartitionedVector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 111 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::dual(), ROL::PartitionedVector< Real >::dual_pvec_, ROL::PartitionedVector< Real >::dual_vecs_, ROL::Vector< Real >::set(), and ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::AugmentedSystemOperator< Real >::apply(), ROL::PartitionedVector< Real >::dual(), and ROL::PartitionedVector< Real >::PartitionedVector().
apply()
template<class Real > Real ROL::PartitionedVector< Real >::apply (const Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 119 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::numVectors(), and ROL::PartitionedVector< Real >::vecs_.
basis()
template<class Real > Vp ROL::PartitionedVector< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 131 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::basis(), ROL::PartitionedVector< Real >::clone(), ROL::PartitionedVector< Real >::dimension(), ROL::PartitionedVector< Real >::set(), ROL::PartitionedVector< Real >::vecs_, and ROL::PartitionedVector< Real >::zero().
Referenced by ROL::PartitionedVector< Real >::basis().
dimension()
template<class Real > int ROL::PartitionedVector< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 154 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::PartitionedVector< Real >::basis().
zero() [1/2]
template<class Real > void ROL::PartitionedVector< Real >::zero () inline virtual
Set to zero vector.
   Uses #scale by zero for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 162 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::Constraint_Partitioned< Real >::applyAdjointHessian(), ROL::Constraint_Partitioned< Real >::applyAdjointJacobian(), and ROL::PartitionedVector< Real >::basis().
applyUnary()
template<class Real > void ROL::PartitionedVector< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 169 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
applyBinary()
template<class Real > void ROL::PartitionedVector< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const V & x) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 176 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::applyBinary(), ROL::PartitionedVector< Real >::get(), and ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::PartitionedVector< Real >::applyBinary().
reduce()
template<class Real > Real ROL::PartitionedVector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 184 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::reduce(), and ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::PartitionedVector< Real >::reduce().
setScalar()
template<class Real > void ROL::PartitionedVector< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 193 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
randomize()
template<class Real > void ROL::PartitionedVector< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 199 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
print()
template<class Real > void ROL::PartitionedVector< Real >::print (std::ostream & outStream) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 205 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
operator[]() [1/2]
template<class Real > const Vector< Real > & ROL::PartitionedVector< Real >::operator[] (size_type i) const inline
Definition at line 213 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
operator[]() [2/2]
template<class Real > Vector< Real > & ROL::PartitionedVector< Real >::operator[] (size_type i) inline
Definition at line 217 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
get() [1/2]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::PartitionedVector< Real >::get (size_type i) const inline
Definition at line 221 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::PartitionedVector< Real >::apply(), ROL::BlockOperator< Real >::apply(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::HessianPDAS_Poly::apply(), ROL::FletcherObjectiveE< Real >::AugSystem::apply(), ROL::AugmentedSystemOperator< Real >::apply(), ROL::BoundFletcher< Real >::AugSystemSym::apply(), ROL::BoundFletcher< Real >::AugSystemNonSym::apply(), ROL::Fletcher< Real >::AugSystem::apply(), ROL::PrimalDualInteriorPointBlock11< Real >::apply(), ROL::PrimalDualInteriorPointBlock12< Real >::apply(), ROL::PrimalDualInteriorPointBlock21< Real >::apply(), ROL::PrimalDualInteriorPointBlock22< Real >::apply(), ROL::Constraint_Partitioned< Real >::applyAdjointHessian(), ROL::Constraint_Partitioned< Real >::applyAdjointJacobian(), ROL::PartitionedVector< Real >::applyBinary(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse(), ROL::FletcherObjectiveE< Real >::AugSystemPrecond::applyInverse(), ROL::AugmentedSystemPrecOperator< Real >::applyInverse(), ROL::BoundFletcher< Real >::AugSystemPrecond::applyInverse(), ROL::Fletcher< Real >::AugSystemPrecond::applyInverse(), ROL::PrimalDualInteriorPointBlock22< Real >::applyInverse(), ROL::BoundConstraint_Partitioned< Real >::applyInverseScalingFunction(), ROL::InteriorPoint::PrimalDualResidual< Real >::applyJacobian(), ROL::PrimalDualInteriorPointResidual< Real >::applyJacobian(), ROL::Constraint_Partitioned< Real >::applyJacobian(), ROL::Constraint_Partitioned< Real >::applyPreconditioner(), ROL::BoundConstraint_Partitioned< Real >::applyScalingFunctionJacobian(), ROL::PartitionedVector< Real >::axpy(), ROL::InteriorPoint::MeritFunction< Real >::dirDeriv(), ROL::PartitionedVector< Real >::dot(), ROL::Problem< Real >::finalizeIteration(), ROL::Constraint_TimeSimOpt< Real >::getNewVector(), ROL::Constraint_TimeSimOpt< Real >::getNewVector(), ROL::Constraint_TimeSimOpt< Real >::getOldVector(), ROL::Constraint_TimeSimOpt< Real >::getOldVector(), ROL::PrimalDualInteriorPointResidual< Real >::getOptMult(), ROL::PrimalDualInteriorPointResidual< Real >::getOptMult(), ROL::ReducedDynamicObjective< Real >::gradient(), ROL::ReducedDynamicObjective< Real >::hessVec(), ROL::SlacklessObjective< Real >::invHessVec(), ROL::BoundConstraint_Partitioned< Real >::isFeasible(), ROL::InteriorPoint::MeritFunction< Real >::MeritFunction(), ROL::PartitionedVector< Real >::plus(), ROL::SlacklessObjective< Real >::precond(), ROL::PrimalDualInteriorPointBlock11< Real >::PrimalDualInteriorPointBlock11(), ROL::PrimalDualInteriorPointBlock21< Real >::PrimalDualInteriorPointBlock21(), ROL::PrimalDualInteriorPointBlock22< Real >::PrimalDualInteriorPointBlock22(), ROL::PrimalDualInteriorPointResidual< Real >::PrimalDualInteriorPointResidual(), ROL::PrimalDualInteriorPointResidual< Real >::PrimalDualInteriorPointResidual(), ROL::InteriorPoint::PrimalDualResidual< Real >::PrimalDualResidual(), ROL::BoundConstraint_Partitioned< Real >::project(), ROL::BoundConstraint_Partitioned< Real >::projectInterior(), ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive(), ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive(), ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive(), ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive(), ROL::PrimalDualSystemStep< Real >::repartition(), ROL::PrimalDualSystemStep< Real >::repartition(), ROL::PartitionedVector< Real >::set(), ROL::ReducedDynamicObjective< Real >::solveAdjoint(), ROL::ReducedDynamicObjective< Real >::solveState(), ROL::PrimalDualInteriorPointBlock11< Real >::update(), ROL::PrimalDualInteriorPointBlock22< Real >::update(), ROL::PrimalDualInteriorPointResidual< Real >::update(), ROL::PrimalDualInteriorPointBlock21< Real >::update(), ROL::ReducedDynamicObjective< Real >::updateSketch(), ROL::InteriorPoint::MeritFunction< Real >::value(), ROL::ReducedDynamicObjective< Real >::value(), ROL::InteriorPoint::PrimalDualResidual< Real >::value(), ROL::PrimalDualInteriorPointResidual< Real >::value(), ROL::Constraint_Partitioned< Real >::value(), ROL::SlacklessConstraint< Real >::zeroSlack(), and ROL::SlacklessObjective< Real >::zeroSlack().
get() [2/2]
template<class Real > ROL::Ptr< Vector< Real > > ROL::PartitionedVector< Real >::get (size_type i) inline
Definition at line 225 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
set() [2/2]
template<class Real > void ROL::PartitionedVector< Real >::set (size_type i, const V & x) inline
Definition at line 229 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
zero() [2/2]
template<class Real > void ROL::PartitionedVector< Real >::zero (size_type i) inline
Definition at line 233 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
numVectors()
template<class Real > size_type ROL::PartitionedVector< Real >::numVectors () const inline
Definition at line 237 of file ROL_PartitionedVector.hpp.
References ROL::PartitionedVector< Real >::vecs_.
Referenced by ROL::PartitionedVector< Real >::apply(), ROL::BlockOperator< Real >::apply(), ROL::PartitionedVector< Real >::axpy(), ROL::PartitionedVector< Real >::dot(), ROL::SlacklessObjective< Real >::invHessVec(), ROL::PartitionedVector< Real >::plus(), ROL::SlacklessObjective< Real >::precond(), print_vector(), ROL::PartitionedVector< Real >::set(), ROL::SlacklessConstraint< Real >::zeroSlack(), and ROL::SlacklessObjective< Real >::zeroSlack().
create() [1/2]
template<class Real > static Ptr< PartitionedVector > ROL::PartitionedVector< Real >::create (std::initializer_list< Vp > vs) inline static
Definition at line 244 of file ROL_PartitionedVector.hpp.
Referenced by main(), ROL::ReducedDynamicObjective< Real >::makeDynamicVector(), and ROL::ReducedDynamicStationaryControlsObjective< Real >::ReducedDynamicStationaryControlsObjective().
create() [2/2]
template<class Real > static Ptr< PartitionedVector > ROL::PartitionedVector< Real >::create (const V & x, size_type N) inline static
Definition at line 250 of file ROL_PartitionedVector.hpp.
References ROL::Vector< Real >::clone().
Member Data Documentation
vecs_
template<class Real > const std::vector<Vp> ROL::PartitionedVector< Real >::vecs_ private
Definition at line 33 of file ROL_PartitionedVector.hpp.
Referenced by ROL::PartitionedVector< Real >::apply(), ROL::PartitionedVector< Real >::applyBinary(), ROL::PartitionedVector< Real >::applyUnary(), ROL::PartitionedVector< Real >::axpy(), ROL::PartitionedVector< Real >::basis(), ROL::PartitionedVector< Real >::clone(), ROL::PartitionedVector< Real >::dimension(), ROL::PartitionedVector< Real >::dot(), ROL::PartitionedVector< Real >::dual(), ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::norm(), ROL::PartitionedVector< Real >::numVectors(), ROL::PartitionedVector< Real >::operator[](), ROL::PartitionedVector< Real >::operator[](), ROL::PartitionedVector< Real >::PartitionedVector(), ROL::PartitionedVector< Real >::plus(), ROL::PartitionedVector< Real >::print(), ROL::PartitionedVector< Real >::randomize(), ROL::PartitionedVector< Real >::reduce(), ROL::PartitionedVector< Real >::scale(), ROL::PartitionedVector< Real >::set(), ROL::PartitionedVector< Real >::set(), ROL::PartitionedVector< Real >::setScalar(), ROL::PartitionedVector< Real >::zero(), and ROL::PartitionedVector< Real >::zero().
dual_vecs_
template<class Real > std::vector<Vp> ROL::PartitionedVector< Real >::dual_vecs_ mutable private
Definition at line 34 of file ROL_PartitionedVector.hpp.
Referenced by ROL::PartitionedVector< Real >::dual(), and ROL::PartitionedVector< Real >::PartitionedVector().
dual_pvec_
template<class Real > ROL::Ptr<PV> ROL::PartitionedVector< Real >::dual_pvec_ mutable private
Definition at line 35 of file ROL_PartitionedVector.hpp.
Referenced by ROL::PartitionedVector< Real >::dual().
The documentation for this class was generated from the following file:
ROL_PartitionedVector.hpp