ROL: ROL::QuantileQuadrangle< Real > Class Template Reference
ROL::QuantileQuadrangle< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for a convex combination of the expected value and the conditional value-at-risk using the expectation risk quadrangle.
#include <ROL_QuantileQuadrangle.hpp>
Public Member Functions
QuantileQuadrangle (Real prob, Real eps, ROL::Ptr< PlusFunction< Real > > &pf)
Constructor.
QuantileQuadrangle (Real prob, Real lam, Real eps, ROL::Ptr< PlusFunction< Real > > &pf)
Constructor.
QuantileQuadrangle (ROL::ParameterList &parlist)
Constructor.
Real error (Real x, int deriv=0)
Evaluate the scalar error function at x.
Real regret (Real x, int deriv=0)
Evaluate the scalar regret function at x.
void check (void)
Run default derivative tests for the scalar regret function.
Public Member Functions inherited from ROL::ExpectationQuad< Real >
virtual ~ExpectationQuad (void)
ExpectationQuad (void)
Private Member Functions
void parseParameterList (ROL::ParameterList &parlist)
void checkInputs (void) const
void setParameters (void)
Private Attributes
ROL::Ptr< PlusFunction< Real > > pf_
Real prob_
Real lam_
Real eps_
Real alpha_
Real beta_
Detailed Description
template<class Real>
class ROL::QuantileQuadrangle< Real >
Provides an interface for a convex combination of the expected value and the conditional value-at-risk using the expectation risk quadrangle.
The conditional value-at-risk (also called the average value-at-risk or the expected shortfall) with confidence level \(0\le \beta < 1\) is
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \frac{1}{1-\beta} \mathbb{E}\left[(X-t)_+\right] \right\} \]
where \((x)_+ = \max\{0,x\}\). If the distribution of \(X\) is continuous, then \(\mathcal{R}\) is the conditional expectation of \(X\) exceeding the \(\beta\)-quantile of \(X\) and the optimal \(t\) is the \(\beta\)-quantile. Additionally, \(\mathcal{R}\) is a law-invariant coherent risk measure.
This class defines a convex combination of expected value and the conditional value-at-risk using the expectation risk quadrangle. In this case, the scalar regret function is
\[ v(x) = \alpha (x)_+ - \lambda (-x)_+ \]
for \(\alpha > 1\) and \(0 \le \lambda < 1\). The associated confidence level for the conditional value-at-risk is
\[ \beta = \frac{\alpha-1}{\alpha-\lambda}. \]
This convex combination of expected value and the conditional value-at-risk is then realized as
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}}\left\{ t + \mathbb{E}[v(X-t)] \right\}. \]
ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
When using derivative-based optimization, the user can provide a smooth approximation of \((\cdot)_+\) using the ROL::PlusFunction class.
Definition at line 63 of file ROL_QuantileQuadrangle.hpp.
Constructor & Destructor Documentation
QuantileQuadrangle() [1/3]
template<class Real > ROL::QuantileQuadrangle< Real >::QuantileQuadrangle (Real prob, Real eps, ROL::Ptr< PlusFunction< Real > > & pf) inline
Constructor.
Parameters
[in] prob is the confidence level
[in] eps is the smoothing parameter for the plus function approximation
[in] pf is the plus function or an approximation
Definition at line 123 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::checkInputs(), and ROL::QuantileQuadrangle< Real >::setParameters().
QuantileQuadrangle() [2/3]
template<class Real > ROL::QuantileQuadrangle< Real >::QuantileQuadrangle (Real prob, Real lam, Real eps, ROL::Ptr< PlusFunction< Real > > & pf) inline
Constructor.
Parameters
[in] prob is the confidence level
[in] lam is the convex combination parameter (coeff=0 corresponds to the expected value whereas coeff=1 corresponds to the conditional value-at-risk)
[in] eps is the smoothing parameter for the plus function approximation
[in] pf is the plus function or an approximation
Definition at line 138 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::checkInputs(), and ROL::QuantileQuadrangle< Real >::setParameters().
QuantileQuadrangle() [3/3]
template<class Real > ROL::QuantileQuadrangle< Real >::QuantileQuadrangle (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measure"->"CVaR" and within the "CVaR" sublist should have the following parameters
"Confidence Level" (between 0 and 1)
"Convex Combination Parameter" (between 0 and 1)
"Smoothing Parameter" (must be positive)
A sublist for plus function information.
Definition at line 156 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::checkInputs(), ROL::QuantileQuadrangle< Real >::parseParameterList(), and ROL::QuantileQuadrangle< Real >::setParameters().
Member Function Documentation
parseParameterList()
template<class Real > void ROL::QuantileQuadrangle< Real >::parseParameterList (ROL::ParameterList & parlist) inline private
Definition at line 75 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::eps_, ROL::QuantileQuadrangle< Real >::lam_, ROL::QuantileQuadrangle< Real >::pf_, and ROL::QuantileQuadrangle< Real >::prob_.
Referenced by ROL::QuantileQuadrangle< Real >::QuantileQuadrangle().
checkInputs()
template<class Real > void ROL::QuantileQuadrangle< Real >::checkInputs (void) const inline private
Definition at line 98 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::eps_, ROL::QuantileQuadrangle< Real >::lam_, ROL::QuantileQuadrangle< Real >::pf_, ROL::QuantileQuadrangle< Real >::prob_, and zero.
Referenced by ROL::QuantileQuadrangle< Real >::QuantileQuadrangle(), ROL::QuantileQuadrangle< Real >::QuantileQuadrangle(), and ROL::QuantileQuadrangle< Real >::QuantileQuadrangle().
setParameters()
template<class Real > void ROL::QuantileQuadrangle< Real >::setParameters (void) inline private
Definition at line 110 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::alpha_, ROL::QuantileQuadrangle< Real >::beta_, ROL::QuantileQuadrangle< Real >::lam_, and ROL::QuantileQuadrangle< Real >::prob_.
Referenced by ROL::QuantileQuadrangle< Real >::QuantileQuadrangle(), ROL::QuantileQuadrangle< Real >::QuantileQuadrangle(), and ROL::QuantileQuadrangle< Real >::QuantileQuadrangle().
error()
template<class Real > Real ROL::QuantileQuadrangle< Real >::error (Real x, int deriv = 0) inline virtual
Evaluate the scalar error function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(e(x)\) or a derivative of \(e(x)\).
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 163 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::alpha_, ROL::QuantileQuadrangle< Real >::beta_, and ROL::QuantileQuadrangle< Real >::pf_.
Referenced by ROL::QuantileQuadrangle< Real >::regret().
regret()
template<class Real > Real ROL::QuantileQuadrangle< Real >::regret (Real x, int deriv = 0) inline virtual
Evaluate the scalar regret function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(v(x)\) or a derivative of \(v(x)\).
Implements ROL::ExpectationQuad< Real >.
Definition at line 170 of file ROL_QuantileQuadrangle.hpp.
References ROL::QuantileQuadrangle< Real >::error(), and zero.
Referenced by ROL::QuantileQuadrangle< Real >::check().
check()
template<class Real > void ROL::QuantileQuadrangle< Real >::check (void) inline virtual
Run default derivative tests for the scalar regret function.
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 177 of file ROL_QuantileQuadrangle.hpp.
References ROL::ExpectationQuad< Real >::check(), ROL::QuantileQuadrangle< Real >::eps_, ROL::QuantileQuadrangle< Real >::regret(), and zero.
Member Data Documentation
pf_
template<class Real > ROL::Ptr<PlusFunction<Real> > ROL::QuantileQuadrangle< Real >::pf_ private
Definition at line 66 of file ROL_QuantileQuadrangle.hpp.
Referenced by ROL::QuantileQuadrangle< Real >::checkInputs(), ROL::QuantileQuadrangle< Real >::error(), and ROL::QuantileQuadrangle< Real >::parseParameterList().
prob_
template<class Real > Real ROL::QuantileQuadrangle< Real >::prob_ private
Definition at line 68 of file ROL_QuantileQuadrangle.hpp.
Referenced by ROL::QuantileQuadrangle< Real >::checkInputs(), ROL::QuantileQuadrangle< Real >::parseParameterList(), and ROL::QuantileQuadrangle< Real >::setParameters().
lam_
template<class Real > Real ROL::QuantileQuadrangle< Real >::lam_ private
Definition at line 69 of file ROL_QuantileQuadrangle.hpp.
Referenced by ROL::QuantileQuadrangle< Real >::checkInputs(), ROL::QuantileQuadrangle< Real >::parseParameterList(), and ROL::QuantileQuadrangle< Real >::setParameters().
eps_
template<class Real > Real ROL::QuantileQuadrangle< Real >::eps_ private
Definition at line 70 of file ROL_QuantileQuadrangle.hpp.
Referenced by ROL::QuantileQuadrangle< Real >::check(), ROL::QuantileQuadrangle< Real >::checkInputs(), and ROL::QuantileQuadrangle< Real >::parseParameterList().
alpha_
template<class Real > Real ROL::QuantileQuadrangle< Real >::alpha_ private
Definition at line 72 of file ROL_QuantileQuadrangle.hpp.
Referenced by ROL::QuantileQuadrangle< Real >::error(), and ROL::QuantileQuadrangle< Real >::setParameters().
beta_
template<class Real > Real ROL::QuantileQuadrangle< Real >::beta_ private
Definition at line 73 of file ROL_QuantileQuadrangle.hpp.
Referenced by ROL::QuantileQuadrangle< Real >::error(), and ROL::QuantileQuadrangle< Real >::setParameters().
The documentation for this class was generated from the following file:
ROL_QuantileQuadrangle.hpp