ROL: ROL::RieszDualVector< Real > Class Template Reference
ROL::RieszDualVector< Real > Class Template Reference
#include <ROL_RieszVector.hpp>
Public Member Functions
RieszDualVector (const ROL::Ptr< V > &v, const ROL::Ptr< OP > &op, Real tol=std::sqrt(ROL_EPSILON< Real >()))
virtual ~RieszDualVector ()
virtual Real dot (const V &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
virtual ROL::Ptr< V > clone () const
Clone to make a new (uninitialized) vector.
virtual const V & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const V &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
ROL::Ptr< V > getVector (void)
ROL::Ptr< const V > getVector (void) const
Public Member Functions inherited from ROL::ElementwiseVector< Real >
virtual ~ElementwiseVector ()
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
virtual Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void zero ()
Set to zero vector.
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual ROL::Ptr< Vector > basis (const int i) const
Return i-th basis vector.
virtual int dimension () const
Return dimension of the vector space.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual void print (std::ostream &outStream) const
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
using V = Vector< Real >
using PrimalVector = RieszPrimalVector< Real >
using OP = LinearOperator< Real >
Private Member Functions
void initialize_primal (void) const
Private Attributes
const ROL::Ptr< V > v_
ROL::Ptr< PrimalVector > primal_
const ROL::Ptr< OP > op_
Real tol_
bool isPrimalInitialized_
Detailed Description
template<class Real>
class ROL::RieszDualVector< Real >
Definition at line 129 of file ROL_RieszVector.hpp.
Member Typedef Documentation
V
template<class Real > using ROL::RieszDualVector< Real >::V = Vector<Real> private
Definition at line 131 of file ROL_RieszVector.hpp.
PrimalVector
template<class Real > using ROL::RieszDualVector< Real >::PrimalVector = RieszPrimalVector<Real> private
Definition at line 132 of file ROL_RieszVector.hpp.
OP
template<class Real > using ROL::RieszDualVector< Real >::OP = LinearOperator<Real> private
Definition at line 133 of file ROL_RieszVector.hpp.
Constructor & Destructor Documentation
RieszDualVector()
template<class Real > ROL::RieszDualVector< Real >::RieszDualVector (const ROL::Ptr< V > & v, const ROL::Ptr< OP > & op, Real tol = std::sqrt(ROL_EPSILON<Real>())) inline
Definition at line 153 of file ROL_RieszVector.hpp.
~RieszDualVector()
template<class Real > virtual ROL::RieszDualVector< Real >::~RieszDualVector () inline virtual
Definition at line 159 of file ROL_RieszVector.hpp.
Member Function Documentation
initialize_primal()
template<class Real > void ROL::RieszDualVector< Real >::initialize_primal (void) const inline private
Definition at line 144 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::isPrimalInitialized_, ROL::RieszDualVector< Real >::op_, ROL::RieszDualVector< Real >::primal_, ROL::RieszDualVector< Real >::tol_, and ROL::RieszDualVector< Real >::v_.
Referenced by ROL::RieszDualVector< Real >::dot(), and ROL::RieszDualVector< Real >::dual().
dot()
template<class Real > virtual Real ROL::RieszDualVector< Real >::dot (const V & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::ElementwiseVector< Real >.
Definition at line 161 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::getVector(), ROL::RieszDualVector< Real >::initialize_primal(), ROL::RieszDualVector< Real >::isPrimalInitialized_, and ROL::RieszDualVector< Real >::primal_.
clone()
template<class Real > virtual ROL::Ptr< V > ROL::RieszDualVector< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 170 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::op_, ROL::RieszDualVector< Real >::tol_, and ROL::RieszDualVector< Real >::v_.
dual()
template<class Real > virtual const V & ROL::RieszDualVector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 174 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::initialize_primal(), ROL::RieszDualVector< Real >::isPrimalInitialized_, and ROL::RieszDualVector< Real >::primal_.
applyUnary()
template<class Real > void ROL::RieszDualVector< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Implements ROL::ElementwiseVector< Real >.
Definition at line 181 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::v_.
applyBinary()
template<class Real > void ROL::RieszDualVector< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const V & x) inline virtual
Implements ROL::ElementwiseVector< Real >.
Definition at line 185 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::applyBinary(), ROL::RieszDualVector< Real >::getVector(), and ROL::RieszDualVector< Real >::v_.
Referenced by ROL::RieszDualVector< Real >::applyBinary().
reduce()
template<class Real > Real ROL::RieszDualVector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Implements ROL::ElementwiseVector< Real >.
Definition at line 190 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::v_.
setScalar()
template<class Real > void ROL::RieszDualVector< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 194 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::v_.
randomize()
template<class Real > void ROL::RieszDualVector< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 198 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::v_.
getVector() [1/2]
template<class Real > ROL::Ptr< V > ROL::RieszDualVector< Real >::getVector (void) inline
Definition at line 202 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::v_.
Referenced by ROL::RieszDualVector< Real >::applyBinary(), and ROL::RieszDualVector< Real >::dot().
getVector() [2/2]
template<class Real > ROL::Ptr< const V > ROL::RieszDualVector< Real >::getVector (void) const inline
Definition at line 206 of file ROL_RieszVector.hpp.
References ROL::RieszDualVector< Real >::v_.
Member Data Documentation
v_
template<class Real > const ROL::Ptr<V> ROL::RieszDualVector< Real >::v_ private
Definition at line 137 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszDualVector< Real >::applyBinary(), ROL::RieszDualVector< Real >::applyUnary(), ROL::RieszDualVector< Real >::clone(), ROL::RieszDualVector< Real >::getVector(), ROL::RieszDualVector< Real >::getVector(), ROL::RieszDualVector< Real >::initialize_primal(), ROL::RieszDualVector< Real >::randomize(), ROL::RieszDualVector< Real >::reduce(), and ROL::RieszDualVector< Real >::setScalar().
primal_
template<class Real > ROL::Ptr<PrimalVector> ROL::RieszDualVector< Real >::primal_ mutable private
Definition at line 138 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszDualVector< Real >::dot(), ROL::RieszDualVector< Real >::dual(), and ROL::RieszDualVector< Real >::initialize_primal().
op_
template<class Real > const ROL::Ptr<OP> ROL::RieszDualVector< Real >::op_ private
Definition at line 139 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszDualVector< Real >::clone(), and ROL::RieszDualVector< Real >::initialize_primal().
tol_
template<class Real > Real ROL::RieszDualVector< Real >::tol_ mutable private
Definition at line 140 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszDualVector< Real >::clone(), and ROL::RieszDualVector< Real >::initialize_primal().
isPrimalInitialized_
template<class Real > bool ROL::RieszDualVector< Real >::isPrimalInitialized_ mutable private
Definition at line 142 of file ROL_RieszVector.hpp.
Referenced by ROL::RieszDualVector< Real >::dot(), ROL::RieszDualVector< Real >::dual(), and ROL::RieszDualVector< Real >::initialize_primal().
The documentation for this class was generated from the following file:
ROL_RieszVector.hpp