ROL: ROL::ExpectationQuad< Real > Class Template Reference
ROL::ExpectationQuad< Real > Class Template Reference abstract
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides a general interface for risk and error measures generated through the expectation risk quadrangle.
#include <ROL_ExpectationQuad.hpp>
Public Member Functions
virtual ~ExpectationQuad (void)
ExpectationQuad (void)
virtual Real regret (Real x, int deriv=0)=0
Evaluate the scalar regret function at x.
virtual Real error (Real x, int deriv=0)
Evaluate the scalar error function at x.
virtual void check (void)
Run default derivative tests for the scalar regret function.
Detailed Description
template<class Real>
class ROL::ExpectationQuad< Real >
Provides a general interface for risk and error measures generated through the expectation risk quadrangle.
Provides a general interface for risk measures generated through the expectation risk quadrangle.
Provides a general interface for deviation measures generated through the expectation risk quadrangle.
The expectation risk quadrangle is a specialization of the general risk quadrangle that provides a rigorous connection between risk-averse optimization and statistical estimation. The risk quadrangle provides fundamental relationships between measures of risk, regret, error and deviation. An expectation risk quadrangle is defined through scalar regret and error functions. The scalar regret function, \(v:\mathbb{R}\to(-\infty,\infty]\), must be proper, closed, convex and satisfy \(v(0)=0\) and \(v(x) > x\) for all \(x\neq 0\). Similarly, the scalar error function, \(e:\mathbb{R}\to[0,\infty]\), must be proper, closed, convex and satisfy \(e(0)=0\) and \(e(x) > 0\) for all \(x\neq 0\). \(v\) and \(e\) are obtained from one another through the relations
\[ v(x) = e(x) + x \quad\text{and}\quad e(x) = v(x) - x. \]
Given \(v\) (or equivalently \(e\)), the associated risk measure is
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \mathbb{E}\left[v(X-t)\right] \right\}. \]
In general, \(\mathcal{R}\) is convex and translation equivariant. Moreover, \(\mathcal{R}\) is monotonic if \(v\) is increasing and \(\mathcal{R}\) is positive homogeneous if \(v\) is. ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
The expectation risk quadrangle is a specialization of the general risk quadrangle that provides a rigorous connection between risk-averse optimization and statistical estimation. The risk quadrangle provides fundamental relationships between measures of risk, regret, error and deviation. An expectation risk quadrangle is defined through scalar regret and error functions. The scalar regret function, \(v:\mathbb{R}\to(-\infty,\infty]\), must be proper, closed, convex and satisfy \(v(0)=0\) and \(v(x) > x\) for all \(x\neq 0\). Similarly, the scalar error function, \(e:\mathbb{R}\to[0,\infty]\), must be proper, closed, convex and satisfy \(e(0)=0\) and \(e(x) > 0\) for all \(x\neq 0\). \(v\) and \(e\) are obtained from one another through the relations
\[ v(x) = e(x) + x \quad\text{and}\quad e(x) = v(x) - x. \]
Given \(v\) (or equivalently \(e\)), the associated risk measure is
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \mathbb{E}\left[v(X-t)\right] \right\}. \]
In general, \(\mathcal{R}\) is convex and translation equivariant. Moreover, \(\mathcal{R}\) is monotonic if \(v\) is increasing and \(\mathcal{R}\) is positive homogeneous if \(v\) is. ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
Definition at line 53 of file ROL_ExpectationQuad.hpp.
Constructor & Destructor Documentation
~ExpectationQuad()
template<class Real > virtual ROL::ExpectationQuad< Real >::~ExpectationQuad (void) inline virtual
Definition at line 55 of file ROL_ExpectationQuad.hpp.
ExpectationQuad()
template<class Real > ROL::ExpectationQuad< Real >::ExpectationQuad (void) inline
Definition at line 56 of file ROL_ExpectationQuad.hpp.
Member Function Documentation
regret()
template<class Real > virtual Real ROL::ExpectationQuad< Real >::regret (Real x, int deriv = 0) pure virtual
Evaluate the scalar regret function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(v(x)\) or a derivative of \(v(x)\).
Implemented in ROL::GenMoreauYosidaCVaR< Real >, ROL::LogExponentialQuadrangle< Real >, ROL::LogQuantileQuadrangle< Real >, ROL::MeanVarianceQuadrangle< Real >, ROL::MoreauYosidaCVaR< Real >, ROL::QuantileQuadrangle< Real >, ROL::SmoothedWorstCaseQuadrangle< Real >, and ROL::TruncatedMeanQuadrangle< Real >.
Referenced by ROL::ExpectationQuad< Real >::check(), and ROL::ExpectationQuad< Real >::error().
error()
template<class Real > virtual Real ROL::ExpectationQuad< Real >::error (Real x, int deriv = 0) inline virtual
Evaluate the scalar error function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(e(x)\) or a derivative of \(e(x)\).
Reimplemented in ROL::GenMoreauYosidaCVaR< Real >, ROL::LogExponentialQuadrangle< Real >, ROL::LogQuantileQuadrangle< Real >, ROL::MeanVarianceQuadrangle< Real >, ROL::MoreauYosidaCVaR< Real >, ROL::QuantileQuadrangle< Real >, ROL::SmoothedWorstCaseQuadrangle< Real >, and ROL::TruncatedMeanQuadrangle< Real >.
Definition at line 74 of file ROL_ExpectationQuad.hpp.
References ROL::ExpectationQuad< Real >::regret(), and zero.
check()
template<class Real > virtual void ROL::ExpectationQuad< Real >::check (void) inline virtual
Run default derivative tests for the scalar regret function.
Reimplemented in ROL::GenMoreauYosidaCVaR< Real >, ROL::LogQuantileQuadrangle< Real >, ROL::MoreauYosidaCVaR< Real >, ROL::QuantileQuadrangle< Real >, ROL::SmoothedWorstCaseQuadrangle< Real >, and ROL::TruncatedMeanQuadrangle< Real >.
Definition at line 82 of file ROL_ExpectationQuad.hpp.
References ROL::ExpectationQuad< Real >::regret(), and zero.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::check(), ROL::LogQuantileQuadrangle< Real >::check(), ROL::MoreauYosidaCVaR< Real >::check(), ROL::QuantileQuadrangle< Real >::check(), ROL::SmoothedWorstCaseQuadrangle< Real >::check(), and ROL::TruncatedMeanQuadrangle< Real >::check().
The documentation for this class was generated from the following file:
ROL_ExpectationQuad.hpp