ROL: ROL::PrimalSimulatedVector< Real > Class Template Reference
ROL::PrimalSimulatedVector< Real > Class Template Reference
#include <ROL_SimulatedVector.hpp>
Public Member Functions
PrimalSimulatedVector (const std::vector< ROL::Ptr< Vector< Real > > > &vecs, const ROL::Ptr< BatchManager< Real > > &bman, const ROL::Ptr< SampleGenerator< Real > > &sampler)
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< Vector< Real > > clone (void) const
Clone to make a new (uninitialized) vector.
const Vector< Real > & dual (void) const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::SimulatedVector< Real >
SimulatedVector (const std::vector< Vp > &vecs, const VBMp &bman)
void set (const V &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const V &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const V &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Vp basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void zero ()
Set to zero vector.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const V &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
ROL::Ptr< const Vector< Real > > get (size_type i) const
ROL::Ptr< Vector< Real > > get (size_type i)
void set (size_type i, const V &x)
void zero (size_type i)
size_type numVectors () const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual void print (std::ostream &outStream) const
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Attributes
const std::vector< ROL::Ptr< Vector< Real > > > vecs_
const ROL::Ptr< BatchManager< Real > > bman_
const ROL::Ptr< SampleGenerator< Real > > sampler_
std::vector< ROL::Ptr< Vector< Real > > > dual_vecs_
ROL::Ptr< DualSimulatedVector< Real > > dual_pvec_
bool isDualInitialized_
Additional Inherited Members
Public Types inherited from ROL::SimulatedVector< Real >
typedef std::vector< PV >::size_type size_type
Detailed Description
template<class Real>
class ROL::PrimalSimulatedVector< Real >
Definition at line 267 of file ROL_SimulatedVector.hpp.
Constructor & Destructor Documentation
PrimalSimulatedVector()
template<class Real > ROL::PrimalSimulatedVector< Real >::PrimalSimulatedVector (const std::vector< ROL::Ptr< Vector< Real > > > & vecs, const ROL::Ptr< BatchManager< Real > > & bman, const ROL::Ptr< SampleGenerator< Real > > & sampler) inline
Definition at line 277 of file ROL_SimulatedVector.hpp.
References ROL::PrimalSimulatedVector< Real >::clone(), ROL::PrimalSimulatedVector< Real >::dual(), ROL::PrimalSimulatedVector< Real >::dual_vecs_, ROL::PrimalSimulatedVector< Real >::sampler_, and ROL::PrimalSimulatedVector< Real >::vecs_.
Member Function Documentation
dot()
template<class Real > Real ROL::PrimalSimulatedVector< Real >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::SimulatedVector< Real >.
Definition at line 287 of file ROL_SimulatedVector.hpp.
References ROL::PrimalSimulatedVector< Real >::bman_, ROL::SimulatedVector< Real >::get(), ROL::SimulatedVector< Real >::numVectors(), ROL::PrimalSimulatedVector< Real >::sampler_, and ROL::PrimalSimulatedVector< Real >::vecs_.
clone()
template<class Real > ROL::Ptr< Vector< Real > > ROL::PrimalSimulatedVector< Real >::clone (void) const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::SimulatedVector< Real >.
Definition at line 311 of file ROL_SimulatedVector.hpp.
References ROL::PrimalSimulatedVector< Real >::bman_, ROL::PrimalSimulatedVector< Real >::clone(), ROL::PrimalSimulatedVector< Real >::sampler_, and ROL::PrimalSimulatedVector< Real >::vecs_.
Referenced by ROL::PrimalSimulatedVector< Real >::clone(), and ROL::PrimalSimulatedVector< Real >::PrimalSimulatedVector().
dual()
template<class Real > const Vector< Real > & ROL::PrimalSimulatedVector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::SimulatedVector< Real >.
Definition at line 319 of file ROL_SimulatedVector.hpp.
References ROL::PrimalSimulatedVector< Real >::bman_, ROL::PrimalSimulatedVector< Real >::dual(), ROL::PrimalSimulatedVector< Real >::dual_pvec_, ROL::PrimalSimulatedVector< Real >::dual_vecs_, ROL::PrimalSimulatedVector< Real >::isDualInitialized_, ROL::PrimalSimulatedVector< Real >::sampler_, and ROL::PrimalSimulatedVector< Real >::vecs_.
Referenced by ROL::PrimalSimulatedVector< Real >::dual(), and ROL::PrimalSimulatedVector< Real >::PrimalSimulatedVector().
Member Data Documentation
vecs_
template<class Real > const std::vector<ROL::Ptr<Vector<Real> > > ROL::PrimalSimulatedVector< Real >::vecs_ private
Definition at line 269 of file ROL_SimulatedVector.hpp.
Referenced by ROL::PrimalSimulatedVector< Real >::clone(), ROL::PrimalSimulatedVector< Real >::dot(), ROL::PrimalSimulatedVector< Real >::dual(), and ROL::PrimalSimulatedVector< Real >::PrimalSimulatedVector().
bman_
template<class Real > const ROL::Ptr<BatchManager<Real> > ROL::PrimalSimulatedVector< Real >::bman_ private
Definition at line 270 of file ROL_SimulatedVector.hpp.
Referenced by ROL::PrimalSimulatedVector< Real >::clone(), ROL::PrimalSimulatedVector< Real >::dot(), and ROL::PrimalSimulatedVector< Real >::dual().
sampler_
template<class Real > const ROL::Ptr<SampleGenerator<Real> > ROL::PrimalSimulatedVector< Real >::sampler_ private
Definition at line 271 of file ROL_SimulatedVector.hpp.
Referenced by ROL::PrimalSimulatedVector< Real >::clone(), ROL::PrimalSimulatedVector< Real >::dot(), ROL::PrimalSimulatedVector< Real >::dual(), and ROL::PrimalSimulatedVector< Real >::PrimalSimulatedVector().
dual_vecs_
template<class Real > std::vector<ROL::Ptr<Vector<Real> > > ROL::PrimalSimulatedVector< Real >::dual_vecs_ mutable private
Definition at line 272 of file ROL_SimulatedVector.hpp.
Referenced by ROL::PrimalSimulatedVector< Real >::dual(), and ROL::PrimalSimulatedVector< Real >::PrimalSimulatedVector().
dual_pvec_
template<class Real > ROL::Ptr<DualSimulatedVector<Real> > ROL::PrimalSimulatedVector< Real >::dual_pvec_ mutable private
Definition at line 273 of file ROL_SimulatedVector.hpp.
Referenced by ROL::PrimalSimulatedVector< Real >::dual().
isDualInitialized_
template<class Real > bool ROL::PrimalSimulatedVector< Real >::isDualInitialized_ mutable private
Definition at line 274 of file ROL_SimulatedVector.hpp.
Referenced by ROL::PrimalSimulatedVector< Real >::dual().
The documentation for this class was generated from the following file:
ROL_SimulatedVector.hpp