ROL: ROL::Problem< Real > Class Template Reference
ROL::Problem< Real > Class Template Reference
#include <ROL_Problem.hpp>
Public Member Functions
virtual ~Problem ()
Problem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< Vector< Real > > &g=nullPtr)
Default constructor for OptimizationProblem.
Problem (const Problem &problem)
Copy constructor for OptimizationProblem.
void addBoundConstraint (const Ptr< BoundConstraint< Real > > &bnd)
Add a bound constraint.
void removeBoundConstraint ()
Remove an existing bound constraint.
void addProxObjective (const Ptr< ProxObjective< Real > > &prox)
Add a prox objective.
void removeProxObjective ()
Remove an existing prox objective.
void addConstraint (std::string name, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul, const Ptr< Vector< Real > > &eres=nullPtr, bool reset=false)
Add an equality constraint.
void addConstraint (std::string name, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd, const Ptr< Vector< Real > > &ires=nullPtr, bool reset=false)
Add an inequality constraint.
void removeConstraint (std::string name)
Remove an existing constraint.
void addLinearConstraint (std::string name, const Ptr< Constraint< Real > > &linear_econ, const Ptr< Vector< Real > > &linear_emul, const Ptr< Vector< Real > > &linear_eres=nullPtr, bool reset=false)
Add a linear equality constraint.
void addLinearConstraint (std::string name, const Ptr< Constraint< Real > > &linear_icon, const Ptr< Vector< Real > > &linear_imul, const Ptr< BoundConstraint< Real > > &linear_ibnd, const Ptr< Vector< Real > > &linear_ires=nullPtr, bool reset=false)
Add a linear inequality constraint.
void removeLinearConstraint (std::string name)
Remove an existing linear constraint.
void setProjectionAlgorithm (ParameterList &parlist)
Set polyhedral projection algorithm.
const Ptr< Objective< Real > > & getObjective ()
Get the objective function.
const Ptr< Vector< Real > > & getPrimalOptimizationVector ()
Get the primal optimization space vector.
const Ptr< Vector< Real > > & getDualOptimizationVector ()
Get the dual optimization space vector.
const Ptr< BoundConstraint< Real > > & getBoundConstraint ()
Get the bound constraint.
const Ptr< Constraint< Real > > & getConstraint ()
Get the equality constraint.
const Ptr< Vector< Real > > & getMultiplierVector ()
Get the dual constraint space vector.
const Ptr< Vector< Real > > & getResidualVector ()
Get the primal constraint space vector.
const Ptr< PolyhedralProjection< Real > > & getPolyhedralProjection ()
Get the polyhedral projection object. This is a null pointer if no linear constraints and/or bounds are present.
EProblem getProblemType ()
Get the optimization problem type (U, B, E, or G).
Real checkLinearity (bool printToStream=false, std::ostream &outStream=std::cout) const
Check if user-supplied linear constraints are affine.
void checkVectors (bool printToStream=false, std::ostream &outStream=std::cout) const
Run vector checks for user-supplied vectors.
void checkDerivatives (bool printToStream=false, std::ostream &outStream=std::cout) const
Run derivative checks for user-supplied objective function and constraints.
void check (bool printToStream=false, std::ostream &outStream=std::cout) const
Run vector, linearity and derivative checks for user-supplied vectors, objective function and constraints.
virtual void finalize (bool lumpConstraints=false, bool printToStream=false, std::ostream &outStream=std::cout)
Tranform user-supplied constraints to consist of only bounds and equalities. Optimization problem cannot be modified after finalize has been called without calling the edit function.
bool isFinalized () const
Indicate whether or no finalize has been called.
virtual void edit ()
Resume editting optimization problem after finalize has been called.
void finalizeIteration ()
Transform the optimization variables to the native parameterization after an optimization algorithm has finished.
virtual ~Problem ()
Problem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< Vector< Real > > &g=nullPtr)
Default constructor for OptimizationProblem.
Problem (const Problem &problem)
Copy constructor for OptimizationProblem.
void addBoundConstraint (const Ptr< BoundConstraint< Real > > &bnd)
Add a bound constraint.
void removeBoundConstraint ()
Remove an existing bound constraint.
void addConstraint (std::string name, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul, const Ptr< Vector< Real > > &eres=nullPtr, bool reset=false)
Add an equality constraint.
void addConstraint (std::string name, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd, const Ptr< Vector< Real > > &ires=nullPtr, bool reset=false)
Add an inequality constraint.
void removeConstraint (std::string name)
Remove an existing constraint.
void addLinearConstraint (std::string name, const Ptr< Constraint< Real > > &linear_econ, const Ptr< Vector< Real > > &linear_emul, const Ptr< Vector< Real > > &linear_eres=nullPtr, bool reset=false)
Add a linear equality constraint.
void addLinearConstraint (std::string name, const Ptr< Constraint< Real > > &linear_icon, const Ptr< Vector< Real > > &linear_imul, const Ptr< BoundConstraint< Real > > &linear_ibnd, const Ptr< Vector< Real > > &linear_ires=nullPtr, bool reset=false)
Add a linear inequality constraint.
void removeLinearConstraint (std::string name)
Remove an existing linear constraint.
void setProjectionAlgorithm (ParameterList &parlist)
Set polyhedral projection algorithm.
void addProximableObjective (const Ptr< Objective< Real > > &nobj)
void removeProximableObjective ()
const Ptr< Objective< Real > > & getObjective ()
Get the objective function.
const Ptr< Objective< Real > > & getProximableObjective ()
Get proximable objective.
const Ptr< Vector< Real > > & getPrimalOptimizationVector ()
Get the primal optimization space vector.
const Ptr< Vector< Real > > & getDualOptimizationVector ()
Get the dual optimization space vector.
const Ptr< BoundConstraint< Real > > & getBoundConstraint ()
Get the bound constraint.
const Ptr< Constraint< Real > > & getConstraint ()
Get the equality constraint.
const Ptr< Vector< Real > > & getMultiplierVector ()
Get the dual constraint space vector.
const Ptr< Vector< Real > > & getResidualVector ()
Get the primal constraint space vector.
const Ptr< PolyhedralProjection< Real > > & getPolyhedralProjection ()
Get the polyhedral projection object. This is a null pointer if no linear constraints and/or bounds are present.
EProblem getProblemType ()
Get the optimization problem type (U, B, E, G, or P).
Real checkLinearity (bool printToStream=false, std::ostream &outStream=std::cout) const
Check if user-supplied linear constraints are affine.
void checkVectors (bool printToStream=false, std::ostream &outStream=std::cout) const
Run vector checks for user-supplied vectors.
void checkDerivatives (bool printToStream=false, std::ostream &outStream=std::cout, const Ptr< Vector< Real > > &x0=nullPtr, Real scale=Real(1)) const
Run derivative checks for user-supplied objective function and constraints.
void check (bool printToStream=false, std::ostream &outStream=std::cout, const Ptr< Vector< Real > > &x0=nullPtr, Real scale=Real(1)) const
Run vector, linearity and derivative checks for user-supplied vectors, objective function and constraints.
virtual void finalize (bool lumpConstraints=false, bool printToStream=false, std::ostream &outStream=std::cout)
Tranform user-supplied constraints to consist of only bounds and equalities. Optimization problem cannot be modified after finalize has been called without calling the edit function.
bool isFinalized () const
Indicate whether or no finalize has been called.
virtual void edit ()
Resume editting optimization problem after finalize has been called.
void finalizeIteration ()
Transform the optimization variables to the native parameterization after an optimization algorithm has finished.
Protected Attributes
Ptr< Objective< Real > > INPUT_obj_
Ptr< Vector< Real > > INPUT_xprim_
Ptr< Vector< Real > > INPUT_xdual_
Ptr< BoundConstraint< Real > > INPUT_bnd_
std::unordered_map< std::string, ConstraintData< Real > > INPUT_con_
std::unordered_map< std::string, ConstraintData< Real > > INPUT_linear_con_
Ptr< ProxObjective< Real > > INPUT_prox_
Ptr< Objective< Real > > INPUT_nobj_
Private Attributes
bool isFinalized_
bool hasBounds_
bool hasEquality_
bool hasInequality_
bool hasLinearEquality_
bool hasLinearInequality_
bool hasProx_
unsigned cnt_econ_
unsigned cnt_icon_
unsigned cnt_linear_econ_
unsigned cnt_linear_icon_
ParameterList ppa_list_
Ptr< Objective< Real > > obj_
Ptr< Vector< Real > > xprim_
Ptr< Vector< Real > > xdual_
Ptr< BoundConstraint< Real > > bnd_
Ptr< Constraint< Real > > con_
Ptr< Vector< Real > > mul_
Ptr< Vector< Real > > res_
Ptr< PolyhedralProjection< Real > > proj_
Ptr< ProxObjective< Real > > prox_
Ptr< Vector< Real > > xfeas_
Ptr< ReduceLinearConstraint< Real > > rlc_
EProblem problemType_
bool hasProximableObjective_
Ptr< Objective< Real > > nobj_
Detailed Description
template<typename Real>
class ROL::Problem< Real >
Definition at line 27 of file function/prox/ROL_Problem.hpp.
Constructor & Destructor Documentation
~Problem() [1/2]
template<typename Real > virtual ROL::Problem< Real >::~Problem () inline virtual
Definition at line 69 of file function/prox/ROL_Problem.hpp.
Problem() [1/4]
template<typename Real > ROL::Problem< Real >::Problem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< Vector< Real > > & g = nullPtr)
Default constructor for OptimizationProblem.
Parameters
[in] obj objective function object
[in] x primal optimization space vector
[in] g dual optimization space vector
Definition at line 18 of file function/prox/ROL_Problem_Def.hpp.
References ROL::Problem< Real >::INPUT_bnd_, ROL::Problem< Real >::INPUT_con_, ROL::Problem< Real >::INPUT_linear_con_, ROL::Problem< Real >::INPUT_obj_, ROL::Problem< Real >::INPUT_xdual_, and ROL::Problem< Real >::INPUT_xprim_.
Problem() [2/4]
template<typename Real > ROL::Problem< Real >::Problem (const Problem< Real > & problem) inline
Copy constructor for OptimizationProblem.
Parameters
[in] problem objective function object
Definition at line 85 of file function/prox/ROL_Problem.hpp.
~Problem() [2/2]
template<typename Real > virtual ROL::Problem< Real >::~Problem () inline virtual
Definition at line 68 of file algorithm/ROL_Problem.hpp.
Problem() [3/4]
template<typename Real > ROL::Problem< Real >::Problem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< Vector< Real > > & g = nullPtr)
Default constructor for OptimizationProblem.
Parameters
[in] obj objective function object
[in] x primal optimization space vector
[in] g dual optimization space vector
Problem() [4/4]
template<typename Real > ROL::Problem< Real >::Problem (const Problem< Real > & problem) inline
Copy constructor for OptimizationProblem.
Parameters
[in] problem objective function object
Definition at line 84 of file algorithm/ROL_Problem.hpp.
Member Function Documentation
addBoundConstraint() [1/2]
template<typename Real > void ROL::Problem< Real >::addBoundConstraint (const Ptr< BoundConstraint< Real > > & bnd)
Add a bound constraint.
Parameters
[in] bnd bound constraint object
Definition at line 38 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), and ROL::TypeG::Algorithm< Real >::run().
removeBoundConstraint() [1/2]
template<typename Real > void ROL::Problem< Real >::removeBoundConstraint ()
Remove an existing bound constraint.
Definition at line 47 of file function/prox/ROL_Problem_Def.hpp.
addProxObjective()
template<typename Real > void ROL::Problem< Real >::addProxObjective (const Ptr< ProxObjective< Real > > & prox)
Add a prox objective.
Parameters
[in] prox prox objective object
Definition at line 56 of file function/prox/ROL_Problem_Def.hpp.
removeProxObjective()
template<typename Real > void ROL::Problem< Real >::removeProxObjective ()
Remove an existing prox objective.
Definition at line 65 of file function/prox/ROL_Problem_Def.hpp.
addConstraint() [1/4]
template<typename Real > void ROL::Problem< Real >::addConstraint (std::string name, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul, const Ptr< Vector< Real > > & eres = nullPtr, bool reset = false)
Add an equality constraint.
Parameters
[in] name the unique constraint identifier
[in] econ constraint object
[in] emul dual constraint space vector
[in] eres primal constraint space vector
[in] reset whether or not to clear constraint container
Definition at line 74 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::StochasticProblem< Real >::finalize(), ROL::StochasticProblem< Real >::makeConstraintStochastic(), ROL::StochasticProblem< Real >::resetStochasticConstraint(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), and ROL::TypeG::Algorithm< Real >::run().
addConstraint() [2/4]
template<typename Real > void ROL::Problem< Real >::addConstraint (std::string name, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd, const Ptr< Vector< Real > > & ires = nullPtr, bool reset = false)
Add an inequality constraint.
Parameters
[in] name the unique constraint identifier
[in] icon constraint object
[in] imul dual constraint space vector
[in] ibnd bound constraint
[in] ires primal constraint space vector
[in] reset whether or not to clear constraint container
Definition at line 94 of file function/prox/ROL_Problem_Def.hpp.
removeConstraint() [1/2]
template<typename Real > void ROL::Problem< Real >::removeConstraint (std::string name)
Remove an existing constraint.
Parameters
[in] name the unique constraint identifier
Definition at line 115 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::StochasticProblem< Real >::finalize(), ROL::StochasticProblem< Real >::makeConstraintStochastic(), and ROL::StochasticProblem< Real >::resetStochasticConstraint().
addLinearConstraint() [1/4]
template<typename Real > void ROL::Problem< Real >::addLinearConstraint (std::string name, const Ptr< Constraint< Real > > & linear_econ, const Ptr< Vector< Real > > & linear_emul, const Ptr< Vector< Real > > & linear_eres = nullPtr, bool reset = false)
Add a linear equality constraint.
Parameters
[in] name the unique constraint identifier
[in] linear_econ constraint object
[in] linear_emul dual constraint space vector
[in] linear_eres primal constraint space vector
[in] reset whether or not to clear linear constraint container
Definition at line 130 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::StochasticProblem< Real >::finalize(), ROL::StochasticProblem< Real >::makeLinearConstraintStochastic(), ROL::StochasticProblem< Real >::resetStochasticLinearConstraint(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), and ROL::TypeG::Algorithm< Real >::run().
addLinearConstraint() [2/4]
template<typename Real > void ROL::Problem< Real >::addLinearConstraint (std::string name, const Ptr< Constraint< Real > > & linear_icon, const Ptr< Vector< Real > > & linear_imul, const Ptr< BoundConstraint< Real > > & linear_ibnd, const Ptr< Vector< Real > > & linear_ires = nullPtr, bool reset = false)
Add a linear inequality constraint.
Parameters
[in] name the unique constraint identifier
[in] linear_icon constraint object
[in] linear_imul dual constraint space vector
[in] linear_ibnd bound constraint
[in] linear_ires primal constraint space vector
[in] reset whether or not to clear linear constraint container
Definition at line 150 of file function/prox/ROL_Problem_Def.hpp.
removeLinearConstraint() [1/2]
template<typename Real > void ROL::Problem< Real >::removeLinearConstraint (std::string name)
Remove an existing linear constraint.
Parameters
[in] name the unique constraint identifier
Definition at line 171 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::StochasticProblem< Real >::finalize(), ROL::StochasticProblem< Real >::makeLinearConstraintStochastic(), and ROL::StochasticProblem< Real >::resetStochasticLinearConstraint().
setProjectionAlgorithm() [1/2]
template<typename Real > void ROL::Problem< Real >::setProjectionAlgorithm (ParameterList & parlist)
Set polyhedral projection algorithm.
Parameters
[in] ppa polyhedral projection algorithm
Definition at line 186 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getObjective() [1/2]
template<typename Real > const Ptr< Objective< Real > > & ROL::Problem< Real >::getObjective ()
Get the objective function.
Definition at line 441 of file function/prox/ROL_Problem_Def.hpp.
References obj_.
Referenced by ROL::TypeB::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeP::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getPrimalOptimizationVector() [1/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getPrimalOptimizationVector ()
Get the primal optimization space vector.
Definition at line 447 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeB::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeP::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getDualOptimizationVector() [1/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getDualOptimizationVector ()
Get the dual optimization space vector.
Definition at line 453 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeB::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeP::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getBoundConstraint() [1/2]
template<typename Real > const Ptr< BoundConstraint< Real > > & ROL::Problem< Real >::getBoundConstraint ()
Get the bound constraint.
Definition at line 459 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeB::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getConstraint() [1/2]
template<typename Real > const Ptr< Constraint< Real > > & ROL::Problem< Real >::getConstraint ()
Get the equality constraint.
Definition at line 465 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getMultiplierVector() [1/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getMultiplierVector ()
Get the dual constraint space vector.
Definition at line 471 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getResidualVector() [1/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getResidualVector ()
Get the primal constraint space vector.
Definition at line 477 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getPolyhedralProjection() [1/2]
template<typename Real > const Ptr< PolyhedralProjection< Real > > & ROL::Problem< Real >::getPolyhedralProjection ()
Get the polyhedral projection object. This is a null pointer if no linear constraints and/or bounds are present.
Definition at line 483 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeB::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
getProblemType() [1/2]
template<typename Real > EProblem ROL::Problem< Real >::getProblemType ()
Get the optimization problem type (U, B, E, or G).
Definition at line 489 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeB::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeP::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
checkLinearity() [1/2]
template<typename Real > Real ROL::Problem< Real >::checkLinearity (bool printToStream = false, std::ostream & outStream = std::cout) const
Check if user-supplied linear constraints are affine.
This function computes the error
\[ \|c(x+\alpha y) - (c(x)+\alpha (c(y)-c(0)))\| \]
for each user-supplied linear constraint and returns the maximum.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Definition at line 495 of file function/prox/ROL_Problem_Def.hpp.
References ROL::Temp.
checkVectors() [1/2]
template<typename Real > void ROL::Problem< Real >::checkVectors (bool printToStream = false, std::ostream & outStream = std::cout) const
Run vector checks for user-supplied vectors.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Definition at line 544 of file function/prox/ROL_Problem_Def.hpp.
checkDerivatives() [1/2]
template<typename Real > void ROL::Problem< Real >::checkDerivatives (bool printToStream = false, std::ostream & outStream = std::cout) const
Run derivative checks for user-supplied objective function and constraints.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Definition at line 603 of file function/prox/ROL_Problem_Def.hpp.
check() [1/2]
template<typename Real > void ROL::Problem< Real >::check (bool printToStream = false, std::ostream & outStream = std::cout) const
Run vector, linearity and derivative checks for user-supplied vectors, objective function and constraints.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Definition at line 644 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
finalize() [1/2]
template<typename Real > void ROL::Problem< Real >::finalize (bool lumpConstraints = false, bool printToStream = false, std::ostream & outStream = std::cout) virtual
Tranform user-supplied constraints to consist of only bounds and equalities. Optimization problem cannot be modified after finalize has been called without calling the edit function.
Parameters
[in] lumpConstraints combine both linear and nonlinear constraints
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Reimplemented in ROL::StochasticProblem< Real >.
Definition at line 194 of file function/prox/ROL_Problem_Def.hpp.
References ROL::ConstraintAssembler< Real >::getBoundConstraint(), ROL::ConstraintAssembler< Real >::getConstraint(), ROL::ConstraintAssembler< Real >::getDualOptVector(), ROL::ConstraintAssembler< Real >::getLinearConstraint(), ROL::ConstraintAssembler< Real >::getLinearMultiplier(), ROL::ConstraintAssembler< Real >::getLinearResidual(), ROL::ConstraintAssembler< Real >::getMultiplier(), ROL::ConstraintAssembler< Real >::getOptVector(), ROL::ConstraintAssembler< Real >::getResidual(), ROL::ConstraintAssembler< Real >::hasInequality(), obj_, ROL::TYPE_B, ROL::TYPE_E, ROL::TYPE_EB, and ROL::TYPE_U.
Referenced by ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), and ROL::TypeG::Algorithm< Real >::run().
isFinalized() [1/2]
template<typename Real > bool ROL::Problem< Real >::isFinalized () const
Indicate whether or no finalize has been called.
Definition at line 653 of file function/prox/ROL_Problem_Def.hpp.
edit() [1/2]
template<typename Real > void ROL::Problem< Real >::edit (void) virtual
Resume editting optimization problem after finalize has been called.
Reimplemented in ROL::StochasticProblem< Real >.
Definition at line 658 of file function/prox/ROL_Problem_Def.hpp.
Referenced by ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
finalizeIteration() [1/2]
template<typename Real > void ROL::Problem< Real >::finalizeIteration ()
Transform the optimization variables to the native parameterization after an optimization algorithm has finished.
Definition at line 665 of file function/prox/ROL_Problem_Def.hpp.
References ROL::PartitionedVector< Real >::get().
Referenced by ROL::TypeB::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeP::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
addBoundConstraint() [2/2]
template<typename Real > void ROL::Problem< Real >::addBoundConstraint (const Ptr< BoundConstraint< Real > > & bnd)
Add a bound constraint.
Parameters
[in] bnd bound constraint object
removeBoundConstraint() [2/2]
template<typename Real > void ROL::Problem< Real >::removeBoundConstraint ()
Remove an existing bound constraint.
addConstraint() [3/4]
template<typename Real > void ROL::Problem< Real >::addConstraint (std::string name, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul, const Ptr< Vector< Real > > & eres = nullPtr, bool reset = false)
Add an equality constraint.
Parameters
[in] name the unique constraint identifier
[in] econ constraint object
[in] emul dual constraint space vector
[in] eres primal constraint space vector
[in] reset whether or not to clear constraint container
addConstraint() [4/4]
template<typename Real > void ROL::Problem< Real >::addConstraint (std::string name, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd, const Ptr< Vector< Real > > & ires = nullPtr, bool reset = false)
Add an inequality constraint.
Parameters
[in] name the unique constraint identifier
[in] icon constraint object
[in] imul dual constraint space vector
[in] ibnd bound constraint
[in] ires primal constraint space vector
[in] reset whether or not to clear constraint container
removeConstraint() [2/2]
template<typename Real > void ROL::Problem< Real >::removeConstraint (std::string name)
Remove an existing constraint.
Parameters
[in] name the unique constraint identifier
addLinearConstraint() [3/4]
template<typename Real > void ROL::Problem< Real >::addLinearConstraint (std::string name, const Ptr< Constraint< Real > > & linear_econ, const Ptr< Vector< Real > > & linear_emul, const Ptr< Vector< Real > > & linear_eres = nullPtr, bool reset = false)
Add a linear equality constraint.
Parameters
[in] name the unique constraint identifier
[in] linear_econ constraint object
[in] linear_emul dual constraint space vector
[in] linear_eres primal constraint space vector
[in] reset whether or not to clear linear constraint container
addLinearConstraint() [4/4]
template<typename Real > void ROL::Problem< Real >::addLinearConstraint (std::string name, const Ptr< Constraint< Real > > & linear_icon, const Ptr< Vector< Real > > & linear_imul, const Ptr< BoundConstraint< Real > > & linear_ibnd, const Ptr< Vector< Real > > & linear_ires = nullPtr, bool reset = false)
Add a linear inequality constraint.
Parameters
[in] name the unique constraint identifier
[in] linear_icon constraint object
[in] linear_imul dual constraint space vector
[in] linear_ibnd bound constraint
[in] linear_ires primal constraint space vector
[in] reset whether or not to clear linear constraint container
removeLinearConstraint() [2/2]
template<typename Real > void ROL::Problem< Real >::removeLinearConstraint (std::string name)
Remove an existing linear constraint.
Parameters
[in] name the unique constraint identifier
setProjectionAlgorithm() [2/2]
template<typename Real > void ROL::Problem< Real >::setProjectionAlgorithm (ParameterList & parlist)
Set polyhedral projection algorithm.
Parameters
[in] ppa polyhedral projection algorithm
addProximableObjective()
template<typename Real > void ROL::Problem< Real >::addProximableObjective (const Ptr< Objective< Real > > & nobj)
Set Proximable objective function
Definition at line 58 of file algorithm/ROL_Problem_Def.hpp.
removeProximableObjective()
template<typename Real > void ROL::Problem< Real >::removeProximableObjective ()
Remove Proximable objective function
Definition at line 67 of file algorithm/ROL_Problem_Def.hpp.
getObjective() [2/2]
template<typename Real > const Ptr< Objective< Real > > & ROL::Problem< Real >::getObjective ()
Get the objective function.
getProximableObjective()
template<typename Real > const Ptr< Objective< Real > > & ROL::Problem< Real >::getProximableObjective ()
Get proximable objective.
Definition at line 455 of file algorithm/ROL_Problem_Def.hpp.
Referenced by ROL::TypeP::Algorithm< Real >::run().
getPrimalOptimizationVector() [2/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getPrimalOptimizationVector ()
Get the primal optimization space vector.
getDualOptimizationVector() [2/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getDualOptimizationVector ()
Get the dual optimization space vector.
getBoundConstraint() [2/2]
template<typename Real > const Ptr< BoundConstraint< Real > > & ROL::Problem< Real >::getBoundConstraint ()
Get the bound constraint.
getConstraint() [2/2]
template<typename Real > const Ptr< Constraint< Real > > & ROL::Problem< Real >::getConstraint ()
Get the equality constraint.
getMultiplierVector() [2/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getMultiplierVector ()
Get the dual constraint space vector.
getResidualVector() [2/2]
template<typename Real > const Ptr< Vector< Real > > & ROL::Problem< Real >::getResidualVector ()
Get the primal constraint space vector.
getPolyhedralProjection() [2/2]
template<typename Real > const Ptr< PolyhedralProjection< Real > > & ROL::Problem< Real >::getPolyhedralProjection ()
Get the polyhedral projection object. This is a null pointer if no linear constraints and/or bounds are present.
getProblemType() [2/2]
template<typename Real > EProblem ROL::Problem< Real >::getProblemType ()
Get the optimization problem type (U, B, E, G, or P).
checkLinearity() [2/2]
template<typename Real > Real ROL::Problem< Real >::checkLinearity (bool printToStream = false, std::ostream & outStream = std::cout) const
Check if user-supplied linear constraints are affine.
This function computes the error
\[ \|c(x+\alpha y) - (c(x)+\alpha (c(y)-c(0)))\| \]
for each user-supplied linear constraint and returns the maximum.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
checkVectors() [2/2]
template<typename Real > void ROL::Problem< Real >::checkVectors (bool printToStream = false, std::ostream & outStream = std::cout) const
Run vector checks for user-supplied vectors.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
checkDerivatives() [2/2]
template<typename Real > void ROL::Problem< Real >::checkDerivatives (bool printToStream = false, std::ostream & outStream = std::cout, const Ptr< Vector< Real > > & x0 = nullPtr, Real scale = Real(1)) const
Run derivative checks for user-supplied objective function and constraints.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Definition at line 617 of file algorithm/ROL_Problem_Def.hpp.
check() [2/2]
template<typename Real > void ROL::Problem< Real >::check (bool printToStream = false, std::ostream & outStream = std::cout, const Ptr< Vector< Real > > & x0 = nullPtr, Real scale = Real(1)) const
Run vector, linearity and derivative checks for user-supplied vectors, objective function and constraints.
Parameters
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Definition at line 656 of file algorithm/ROL_Problem_Def.hpp.
finalize() [2/2]
template<typename Real > virtual void ROL::Problem< Real >::finalize (bool lumpConstraints = false, bool printToStream = false, std::ostream & outStream = std::cout) virtual
Tranform user-supplied constraints to consist of only bounds and equalities. Optimization problem cannot be modified after finalize has been called without calling the edit function.
Parameters
[in] lumpConstraints combine both linear and nonlinear constraints
[in] printToStream determines whether to print to the supplied std::ostream
[in,out] outStream user supplied std::ostream
Reimplemented in ROL::StochasticProblem< Real >.
isFinalized() [2/2]
template<typename Real > bool ROL::Problem< Real >::isFinalized () const
Indicate whether or no finalize has been called.
edit() [2/2]
template<typename Real > virtual void ROL::Problem< Real >::edit () virtual
Resume editting optimization problem after finalize has been called.
Reimplemented in ROL::StochasticProblem< Real >.
finalizeIteration() [2/2]
template<typename Real > void ROL::Problem< Real >::finalizeIteration ()
Transform the optimization variables to the native parameterization after an optimization algorithm has finished.
Member Data Documentation
isFinalized_
template<typename Real > bool ROL::Problem< Real >::isFinalized_ private
Definition at line 29 of file function/prox/ROL_Problem.hpp.
hasBounds_
template<typename Real > bool ROL::Problem< Real >::hasBounds_ private
Definition at line 30 of file function/prox/ROL_Problem.hpp.
hasEquality_
template<typename Real > bool ROL::Problem< Real >::hasEquality_ private
Definition at line 31 of file function/prox/ROL_Problem.hpp.
hasInequality_
template<typename Real > bool ROL::Problem< Real >::hasInequality_ private
Definition at line 32 of file function/prox/ROL_Problem.hpp.
hasLinearEquality_
template<typename Real > bool ROL::Problem< Real >::hasLinearEquality_ private
Definition at line 33 of file function/prox/ROL_Problem.hpp.
hasLinearInequality_
template<typename Real > bool ROL::Problem< Real >::hasLinearInequality_ private
Definition at line 34 of file function/prox/ROL_Problem.hpp.
hasProx_
template<typename Real > bool ROL::Problem< Real >::hasProx_ private
Definition at line 35 of file function/prox/ROL_Problem.hpp.
cnt_econ_
template<typename Real > unsigned ROL::Problem< Real >::cnt_econ_ private
Definition at line 36 of file function/prox/ROL_Problem.hpp.
cnt_icon_
template<typename Real > unsigned ROL::Problem< Real >::cnt_icon_ private
Definition at line 37 of file function/prox/ROL_Problem.hpp.
cnt_linear_econ_
template<typename Real > unsigned ROL::Problem< Real >::cnt_linear_econ_ private
Definition at line 38 of file function/prox/ROL_Problem.hpp.
cnt_linear_icon_
template<typename Real > unsigned ROL::Problem< Real >::cnt_linear_icon_ private
Definition at line 39 of file function/prox/ROL_Problem.hpp.
ppa_list_
template<typename Real > ParameterList ROL::Problem< Real >::ppa_list_ private
Definition at line 41 of file function/prox/ROL_Problem.hpp.
obj_
template<typename Real > Ptr< Objective< Real > > ROL::Problem< Real >::obj_ private
Definition at line 43 of file function/prox/ROL_Problem.hpp.
xprim_
template<typename Real > Ptr< Vector< Real > > ROL::Problem< Real >::xprim_ private
Definition at line 44 of file function/prox/ROL_Problem.hpp.
xdual_
template<typename Real > Ptr< Vector< Real > > ROL::Problem< Real >::xdual_ private
Definition at line 45 of file function/prox/ROL_Problem.hpp.
bnd_
template<typename Real > Ptr< BoundConstraint< Real > > ROL::Problem< Real >::bnd_ private
Definition at line 46 of file function/prox/ROL_Problem.hpp.
con_
template<typename Real > Ptr< Constraint< Real > > ROL::Problem< Real >::con_ private
Definition at line 47 of file function/prox/ROL_Problem.hpp.
mul_
template<typename Real > Ptr< Vector< Real > > ROL::Problem< Real >::mul_ private
Definition at line 48 of file function/prox/ROL_Problem.hpp.
res_
template<typename Real > Ptr< Vector< Real > > ROL::Problem< Real >::res_ private
Definition at line 49 of file function/prox/ROL_Problem.hpp.
proj_
template<typename Real > Ptr< PolyhedralProjection< Real > > ROL::Problem< Real >::proj_ private
Definition at line 50 of file function/prox/ROL_Problem.hpp.
prox_
template<typename Real > Ptr<ProxObjective<Real> > ROL::Problem< Real >::prox_ private
Definition at line 51 of file function/prox/ROL_Problem.hpp.
xfeas_
template<typename Real > Ptr< Vector< Real > > ROL::Problem< Real >::xfeas_ private
Definition at line 53 of file function/prox/ROL_Problem.hpp.
rlc_
template<typename Real > Ptr< ReduceLinearConstraint< Real > > ROL::Problem< Real >::rlc_ private
Definition at line 54 of file function/prox/ROL_Problem.hpp.
problemType_
template<typename Real > EProblem ROL::Problem< Real >::problemType_ private
Definition at line 56 of file function/prox/ROL_Problem.hpp.
INPUT_obj_
template<typename Real > Ptr< Objective< Real > > ROL::Problem< Real >::INPUT_obj_ protected
Definition at line 60 of file function/prox/ROL_Problem.hpp.
Referenced by ROL::Problem< Real >::Problem().
INPUT_xprim_
template<typename Real > Ptr< Vector< Real > > ROL::Problem< Real >::INPUT_xprim_ protected
Definition at line 61 of file function/prox/ROL_Problem.hpp.
Referenced by ROL::Problem< Real >::Problem().
INPUT_xdual_
template<typename Real > Ptr< Vector< Real > > ROL::Problem< Real >::INPUT_xdual_ protected
Definition at line 62 of file function/prox/ROL_Problem.hpp.
Referenced by ROL::Problem< Real >::Problem().
INPUT_bnd_
template<typename Real > Ptr< BoundConstraint< Real > > ROL::Problem< Real >::INPUT_bnd_ protected
Definition at line 63 of file function/prox/ROL_Problem.hpp.
Referenced by ROL::Problem< Real >::Problem().
INPUT_con_
template<typename Real > std::unordered_map< std::string, ConstraintData< Real > > ROL::Problem< Real >::INPUT_con_ protected
Definition at line 64 of file function/prox/ROL_Problem.hpp.
Referenced by ROL::Problem< Real >::Problem().
INPUT_linear_con_
template<typename Real > std::unordered_map< std::string, ConstraintData< Real > > ROL::Problem< Real >::INPUT_linear_con_ protected
Definition at line 65 of file function/prox/ROL_Problem.hpp.
Referenced by ROL::Problem< Real >::Problem().
INPUT_prox_
template<typename Real > Ptr<ProxObjective<Real> > ROL::Problem< Real >::INPUT_prox_ protected
Definition at line 66 of file function/prox/ROL_Problem.hpp.
hasProximableObjective_
template<typename Real > bool ROL::Problem< Real >::hasProximableObjective_ private
Definition at line 34 of file algorithm/ROL_Problem.hpp.
nobj_
template<typename Real > Ptr<Objective<Real> > ROL::Problem< Real >::nobj_ private
Definition at line 43 of file algorithm/ROL_Problem.hpp.
INPUT_nobj_
template<typename Real > Ptr<Objective<Real> > ROL::Problem< Real >::INPUT_nobj_ protected
Definition at line 60 of file algorithm/ROL_Problem.hpp.
The documentation for this class was generated from the following files:
function/prox/ROL_Problem.hpp
algorithm/ROL_Problem.hpp
function/prox/ROL_Problem_Def.hpp
algorithm/ROL_Problem_Def.hpp