ROL: ROL::Secant< Real > Class Template Reference
ROL::Secant< Real > Class Template Reference abstract
Provides interface for and implements limited-memory secant operators.
#include <ROL_Secant.hpp>
Public Member Functions
virtual ~Secant ()
Secant (int M=10, bool useDefaultScaling=true, Real Bscaling=Real(1), ESecantMode mode=SECANTMODE_BOTH)
Ptr< SecantState< Real > > & get_state ()
const Ptr< SecantState< Real > > & get_state () const
virtual void updateStorage (const Vector< Real > &x, const Vector< Real > &grad, const Vector< Real > &gp, const Vector< Real > &s, const Real snorm, const int iter)
virtual void applyH (Vector< Real > &Hv, const Vector< Real > &v) const =0
virtual void applyH0 (Vector< Real > &Hv, const Vector< Real > &v) const
virtual void applyB (Vector< Real > &Bv, const Vector< Real > &v) const =0
virtual void applyB0 (Vector< Real > &Bv, const Vector< Real > &v) const
void test (std::ostream &stream=std::cout) const
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Protected Attributes
const Ptr< SecantState< Real > > state_
Ptr< Vector< Real > > y_
bool useDefaultScaling_
Real Bscaling_
Private Attributes
bool isInitialized_
Detailed Description
template<class Real>
class ROL::Secant< Real >
Provides interface for and implements limited-memory secant operators.
Definition at line 45 of file ROL_Secant.hpp.
Constructor & Destructor Documentation
~Secant()
template<class Real > virtual ROL::Secant< Real >::~Secant () inline virtual
Definition at line 59 of file ROL_Secant.hpp.
Secant()
template<class Real > ROL::Secant< Real >::Secant (int M = 10, bool useDefaultScaling = true, Real Bscaling = Real(1), ESecantMode mode = SECANTMODE_BOTH) inline
Definition at line 62 of file ROL_Secant.hpp.
Member Function Documentation
get_state() [1/2]
template<class Real > Ptr< SecantState< Real > > & ROL::Secant< Real >::get_state () inline
Definition at line 67 of file ROL_Secant.hpp.
References ROL::Secant< Real >::state_.
get_state() [2/2]
template<class Real > const Ptr< SecantState< Real > > & ROL::Secant< Real >::get_state () const inline
Definition at line 68 of file ROL_Secant.hpp.
References ROL::Secant< Real >::state_.
updateStorage()
template<class Real > virtual void ROL::Secant< Real >::updateStorage (const Vector< Real > & x, const Vector< Real > & grad, const Vector< Real > & gp, const Vector< Real > & s, const Real snorm, const int iter) inline virtual
Reimplemented in ROL::lSR1< Real >.
Definition at line 71 of file ROL_Secant.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::clone(), ROL::Secant< Real >::isInitialized_, ROL::Secant< Real >::state_, and ROL::Secant< Real >::y_.
applyH()
template<class Real > virtual void ROL::Secant< Real >::applyH (Vector< Real > & Hv, const Vector< Real > & v) const pure virtual
Implemented in ROL::lBFGS< Real >, ROL::lDFP< Real >, and ROL::lSR1< Real >.
Referenced by ROL::TypeB::LSecantBAlgorithm< Real >::applyFreePrecond(), ROL::Secant< Real >::applyInverse(), and ROL::Secant< Real >::test().
applyH0()
template<class Real > virtual void ROL::Secant< Real >::applyH0 (Vector< Real > & Hv, const Vector< Real > & v) const inline virtual
Reimplemented in ROL::lDFP< Real >, and ROL::lSR1< Real >.
Definition at line 110 of file ROL_Secant.hpp.
References ROL::Secant< Real >::Bscaling_, ROL::Vector< Real >::dual(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::Secant< Real >::state_, and ROL::Secant< Real >::useDefaultScaling_.
Referenced by ROL::lBFGS< Real >::applyH().
applyB()
template<class Real > virtual void ROL::Secant< Real >::applyB (Vector< Real > & Bv, const Vector< Real > & v) const pure virtual
Implemented in ROL::lBFGS< Real >, ROL::lDFP< Real >, and ROL::lSR1< Real >.
Referenced by ROL::Secant< Real >::apply(), ROL::TypeB::LSecantBAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LSecantBAlgorithm< Real >::dcauchy(), and ROL::Secant< Real >::test().
applyB0()
template<class Real > virtual void ROL::Secant< Real >::applyB0 (Vector< Real > & Bv, const Vector< Real > & v) const inline virtual
Reimplemented in ROL::lDFP< Real >, and ROL::lSR1< Real >.
Definition at line 127 of file ROL_Secant.hpp.
References ROL::Secant< Real >::Bscaling_, ROL::Vector< Real >::dual(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::Secant< Real >::state_, and ROL::Secant< Real >::useDefaultScaling_.
Referenced by ROL::lBFGS< Real >::applyB().
test()
template<class Real > void ROL::Secant< Real >::test (std::ostream & stream = std::cout) const inline
Definition at line 141 of file ROL_Secant.hpp.
References ROL::Secant< Real >::applyB(), ROL::Secant< Real >::applyH(), ROL::Secant< Real >::isInitialized_, and ROL::Secant< Real >::state_.
apply()
template<class Real > void ROL::Secant< Real >::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 164 of file ROL_Secant.hpp.
References ROL::Secant< Real >::applyB().
Referenced by ROL::lBFGS< Real >::applyB().
applyInverse()
template<class Real > void ROL::Secant< Real >::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 168 of file ROL_Secant.hpp.
References ROL::Secant< Real >::applyH().
Member Data Documentation
state_
template<class Real > const Ptr<SecantState<Real> > ROL::Secant< Real >::state_ protected
Definition at line 48 of file ROL_Secant.hpp.
Referenced by ROL::lBFGS< Real >::applyB(), ROL::lDFP< Real >::applyB(), ROL::lSR1< Real >::applyB(), ROL::lDFP< Real >::applyB0(), ROL::lSR1< Real >::applyB0(), ROL::Secant< Real >::applyB0(), ROL::lBFGS< Real >::applyH(), ROL::lDFP< Real >::applyH(), ROL::lSR1< Real >::applyH(), ROL::lDFP< Real >::applyH0(), ROL::lSR1< Real >::applyH0(), ROL::Secant< Real >::applyH0(), ROL::Secant< Real >::get_state(), ROL::Secant< Real >::get_state(), ROL::Secant< Real >::test(), ROL::lSR1< Real >::updateStorage(), and ROL::Secant< Real >::updateStorage().
y_
template<class Real > Ptr<Vector<Real> > ROL::Secant< Real >::y_ protected
Definition at line 49 of file ROL_Secant.hpp.
Referenced by ROL::lSR1< Real >::updateStorage(), and ROL::Secant< Real >::updateStorage().
useDefaultScaling_
template<class Real > bool ROL::Secant< Real >::useDefaultScaling_ protected
Definition at line 50 of file ROL_Secant.hpp.
Referenced by ROL::lDFP< Real >::applyB0(), ROL::Secant< Real >::applyB0(), ROL::lDFP< Real >::applyH0(), ROL::Secant< Real >::applyH0(), ROL::lSR1< Real >::lSR1(), and ROL::lSR1< Real >::updateStorage().
Bscaling_
template<class Real > Real ROL::Secant< Real >::Bscaling_ protected
Definition at line 51 of file ROL_Secant.hpp.
Referenced by ROL::lDFP< Real >::applyB0(), ROL::lSR1< Real >::applyB0(), ROL::Secant< Real >::applyB0(), ROL::lDFP< Real >::applyH0(), ROL::lSR1< Real >::applyH0(), ROL::Secant< Real >::applyH0(), ROL::lSR1< Real >::lSR1(), and ROL::lSR1< Real >::updateStorage().
isInitialized_
template<class Real > bool ROL::Secant< Real >::isInitialized_ private
Definition at line 55 of file ROL_Secant.hpp.
Referenced by ROL::Secant< Real >::test(), and ROL::Secant< Real >::updateStorage().
The documentation for this class was generated from the following file:
ROL_Secant.hpp