ROL: ROL::NonlinearCGStep< Real > Class Template Reference
ROL::NonlinearCGStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with nonlinear CG.
#include <ROL_NonlinearCGStep.hpp>
Public Member Functions
NonlinearCGStep (ROL::ParameterList &parlist, const ROL::Ptr< NonlinearCG< Real > > &nlcg=ROL::nullPtr, const bool computeObj=true)
Constructor.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool print_header=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Attributes
ROL::Ptr< NonlinearCG< Real > > nlcg_
NonlinearCG object (used for quasi-Newton)
ENonlinearCG enlcg_
int verbosity_
Verbosity setting.
const bool computeObj_
std::string ncgName_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::NonlinearCGStep< Real >
Provides the interface to compute optimization steps with nonlinear CG.
Definition at line 26 of file ROL_NonlinearCGStep.hpp.
Constructor & Destructor Documentation
NonlinearCGStep()
template<class Real > ROL::NonlinearCGStep< Real >::NonlinearCGStep (ROL::ParameterList & parlist, const ROL::Ptr< NonlinearCG< Real > > & nlcg = ROL::nullPtr, const bool computeObj = true) inline
Constructor.
Constructor to build a NonlinearCGStep object with a user-defined nonlinear CG object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
[in] nlcg is a user-defined NonlinearCG object
Definition at line 51 of file ROL_NonlinearCGStep.hpp.
References ROL::NonlinearCGStep< Real >::enlcg_, ROL::NonlinearCGStep< Real >::ncgName_, ROL::NonlinearCGStep< Real >::nlcg_, ROL::StringToENonlinearCG(), and ROL::NonlinearCGStep< Real >::verbosity_.
Member Function Documentation
compute()
template<class Real > void ROL::NonlinearCGStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 72 of file ROL_NonlinearCGStep.hpp.
References ROL::Step< Real >::getState(), ROL::NonlinearCGStep< Real >::nlcg_, and ROL::Vector< Real >::scale().
update()
template<class Real > void ROL::NonlinearCGStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 83 of file ROL_NonlinearCGStep.hpp.
References ROL::NonlinearCGStep< Real >::computeObj_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::AlgorithmState< Real >::snorm, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::NonlinearCGStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 108 of file ROL_NonlinearCGStep.hpp.
References ROL::DESCENT_NONLINEARCG, ROL::EDescentToString(), and ROL::NonlinearCGStep< Real >::verbosity_.
Referenced by ROL::NonlinearCGStep< Real >::print().
printName()
template<class Real > std::string ROL::NonlinearCGStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 134 of file ROL_NonlinearCGStep.hpp.
References ROL::DESCENT_NONLINEARCG, ROL::EDescentToString(), and ROL::NonlinearCGStep< Real >::ncgName_.
Referenced by ROL::NonlinearCGStep< Real >::print().
print()
template<class Real > std::string ROL::NonlinearCGStep< Real >::print (AlgorithmState< Real > & algo_state, bool printHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 140 of file ROL_NonlinearCGStep.hpp.
References ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::NonlinearCGStep< Real >::printHeader(), ROL::NonlinearCGStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
nlcg_
template<class Real > ROL::Ptr<NonlinearCG<Real> > ROL::NonlinearCGStep< Real >::nlcg_ private
NonlinearCG object (used for quasi-Newton)
Definition at line 29 of file ROL_NonlinearCGStep.hpp.
Referenced by ROL::NonlinearCGStep< Real >::compute(), and ROL::NonlinearCGStep< Real >::NonlinearCGStep().
enlcg_
template<class Real > ENonlinearCG ROL::NonlinearCGStep< Real >::enlcg_ private
Definition at line 30 of file ROL_NonlinearCGStep.hpp.
Referenced by ROL::NonlinearCGStep< Real >::NonlinearCGStep().
verbosity_
template<class Real > int ROL::NonlinearCGStep< Real >::verbosity_ private
Verbosity setting.
Definition at line 31 of file ROL_NonlinearCGStep.hpp.
Referenced by ROL::NonlinearCGStep< Real >::NonlinearCGStep(), and ROL::NonlinearCGStep< Real >::printHeader().
computeObj_
template<class Real > const bool ROL::NonlinearCGStep< Real >::computeObj_ private
Definition at line 32 of file ROL_NonlinearCGStep.hpp.
Referenced by ROL::NonlinearCGStep< Real >::update().
ncgName_
template<class Real > std::string ROL::NonlinearCGStep< Real >::ncgName_ private
Definition at line 34 of file ROL_NonlinearCGStep.hpp.
Referenced by ROL::NonlinearCGStep< Real >::NonlinearCGStep(), and ROL::NonlinearCGStep< Real >::printName().
The documentation for this class was generated from the following file:
ROL_NonlinearCGStep.hpp