ROL: ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly Class Reference
ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly Class Reference
Public Member Functions
PrecondPDAS_Poly (const Ptr< Objective< Real > > &obj, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< const Vector< Real > > &x, const Ptr< const Vector< Real > > &xlam, Real eps, const Ptr< Secant< Real > > &secant, bool useSecant, const Ptr< Vector< Real > > &dwa)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Attributes
const Ptr< Objective< Real > > obj_
const Ptr< BoundConstraint< Real > > bnd_
const Ptr< const Vector< Real > > x_
const Ptr< const Vector< Real > > xlam_
const Real eps_
const Ptr< Secant< Real > > secant_
const bool useSecant_
const Ptr< Vector< Real > > dwa_
Detailed Description
template<typename Real>
class ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly
Definition at line 163 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Constructor & Destructor Documentation
PrecondPDAS_Poly()
template<typename Real > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::PrecondPDAS_Poly (const Ptr< Objective< Real > > & obj, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< const Vector< Real > > & x, const Ptr< const Vector< Real > > & xlam, Real eps, const Ptr< Secant< Real > > & secant, bool useSecant, const Ptr< Vector< Real > > & dwa) inline
Definition at line 174 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Member Function Documentation
apply()
template<typename Real > void ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 184 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
References ROL::Vector< Real >::dual(), and ROL::Vector< Real >::set().
applyInverse()
template<typename Real > void ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 187 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
References ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::bnd_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::dwa_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::eps_, ROL::PartitionedVector< Real >::get(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::obj_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::secant_, ROL::PartitionedVector< Real >::set(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::useSecant_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::x_, and ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::xlam_.
Member Data Documentation
obj_
template<typename Real > const Ptr<Objective<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::obj_ private
Definition at line 165 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
bnd_
template<typename Real > const Ptr<BoundConstraint<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::bnd_ private
Definition at line 166 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
x_
template<typename Real > const Ptr<const Vector<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::x_ private
Definition at line 167 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
xlam_
template<typename Real > const Ptr<const Vector<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::xlam_ private
Definition at line 168 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
eps_
template<typename Real > const Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::eps_ private
Definition at line 169 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::secant_ private
Definition at line 170 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
useSecant_
template<typename Real > const bool ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::useSecant_ private
Definition at line 171 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
dwa_
template<typename Real > const Ptr<Vector<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::dwa_ private
Definition at line 172 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::applyInverse().
The documentation for this class was generated from the following file:
ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp