ROL: ROL::TypeE::FletcherAlgorithm< Real > Class Template Reference
ROL::TypeE::FletcherAlgorithm< Real > Class Template Reference
Provides an interface to run equality constrained optimization algorithms using Fletcher's exact penalty.
#include <ROL_TypeE_FletcherAlgorithm.hpp>
Public Member Functions
FletcherAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void initialize (Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &l, const Vector< Real > &c, FletcherObjectiveE< Real > &fobj, Constraint< Real > &con, std::ostream &outStream)
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, std::ostream &outStream=std::cout) override
Run algorithm on equality constrained problems (Type-E). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeHeader (std::ostream &os) const override
Print iterate header.
virtual void writeName (std::ostream &os) const override
Print step name.
virtual void writeOutput (std::ostream &os, const bool print_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeE::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems (Type-E). This is the primary Type-E interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems (Type-E). This is the primary Type-E interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems with explicit linear equality constraints (Type-E). This is the primary Type-E with explicit linear equality constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems with explicit linear equality constraints (Type-E). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Attributes
const Ptr< Secant< Real > > secant_
ParameterList list_
std::string subStep_
Real merit_
Real gpnorm_
Real sigma_
Real delta_
Real minSigma_
Real maxSigma_
Real sigmaUpdate_
Real minDelta_
Real deltaUpdate_
bool modifySigma_
int subproblemIter_
int verbosity_
bool printHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeE::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &mul, const Vector< Real > &c)
Protected Attributes inherited from ROL::TypeE::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeE::FletcherAlgorithm< Real >
Provides an interface to run equality constrained optimization algorithms using Fletcher's exact penalty.
Definition at line 26 of file ROL_TypeE_FletcherAlgorithm.hpp.
Constructor & Destructor Documentation
FletcherAlgorithm()
template<typename Real > ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 19 of file ROL_TypeE_FletcherAlgorithm_Def.hpp.
References ROL::TypeE::FletcherAlgorithm< Real >::delta_, ROL::TypeE::FletcherAlgorithm< Real >::deltaUpdate_, ROL::TypeE::FletcherAlgorithm< Real >::list_, ROL::TypeE::FletcherAlgorithm< Real >::maxSigma_, ROL::TypeE::FletcherAlgorithm< Real >::minDelta_, ROL::TypeE::FletcherAlgorithm< Real >::minSigma_, ROL::TypeE::FletcherAlgorithm< Real >::modifySigma_, ROL::TypeE::FletcherAlgorithm< Real >::printHeader_, ROL::TypeE::Algorithm< Real >::reset(), ROL::TypeE::FletcherAlgorithm< Real >::sigma_, ROL::TypeE::FletcherAlgorithm< Real >::sigmaUpdate_, ROL::TypeE::Algorithm< Real >::status_, ROL::TypeE::FletcherAlgorithm< Real >::subStep_, and ROL::TypeE::FletcherAlgorithm< Real >::verbosity_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeE::FletcherAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & l, const Vector< Real > & c, FletcherObjectiveE< Real > & fobj, Constraint< Real > & con, std::ostream & outStream)
Definition at line 47 of file ROL_TypeE_FletcherAlgorithm_Def.hpp.
References ROL::FletcherObjectiveBase< Real >::getConstraintVec(), ROL::FletcherObjectiveBase< Real >::getLagrangianGradient(), ROL::FletcherObjectiveBase< Real >::getNumberConstraintEvaluations(), ROL::FletcherObjectiveBase< Real >::getNumberFunctionEvaluations(), ROL::FletcherObjectiveBase< Real >::getNumberGradientEvaluations(), ROL::FletcherObjectiveBase< Real >::getObjectiveValue(), ROL::FletcherObjectiveE< Real >::gradient(), ROL::Initial, ROL::TypeE::Algorithm< Real >::initialize(), ROL::FletcherObjectiveBase< Real >::reset(), ROL::FletcherObjectiveBase< Real >::update(), and ROL::FletcherObjectiveE< Real >::value().
run()
template<typename Real > void ROL::TypeE::FletcherAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, std::ostream & outStream = std::cout) override virtual
Run algorithm on equality constrained problems (Type-E). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeE::Algorithm< Real >.
Definition at line 83 of file ROL_TypeE_FletcherAlgorithm_Def.hpp.
References ROL::Vector< Real >::clone(), ROL::EXITSTATUS_CONVERGED, ROL::FletcherObjectiveBase< Real >::getConstraintVec(), ROL::FletcherObjectiveBase< Real >::getLagrangianGradient(), ROL::FletcherObjectiveBase< Real >::getMultiplierVec(), ROL::FletcherObjectiveBase< Real >::getNumberConstraintEvaluations(), ROL::FletcherObjectiveBase< Real >::getNumberFunctionEvaluations(), ROL::FletcherObjectiveBase< Real >::getNumberGradientEvaluations(), ROL::FletcherObjectiveBase< Real >::getObjectiveValue(), ROL::FletcherObjectiveE< Real >::gradient(), ROL::FletcherObjectiveBase< Real >::reset(), ROL::Vector< Real >::set(), ROL::FletcherObjectiveE< Real >::value(), and ROL::TypeE::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeE::FletcherAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeE::Algorithm< Real >.
Definition at line 169 of file ROL_TypeE_FletcherAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeE::FletcherAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeE::Algorithm< Real >.
Definition at line 208 of file ROL_TypeE_FletcherAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeE::FletcherAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeE::Algorithm< Real >.
Definition at line 217 of file ROL_TypeE_FletcherAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeE::FletcherAlgorithm< Real >::secant_ private
Definition at line 29 of file ROL_TypeE_FletcherAlgorithm.hpp.
list_
template<typename Real > ParameterList ROL::TypeE::FletcherAlgorithm< Real >::list_ private
Definition at line 30 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
subStep_
template<typename Real > std::string ROL::TypeE::FletcherAlgorithm< Real >::subStep_ private
Definition at line 31 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
merit_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::merit_ private
Definition at line 33 of file ROL_TypeE_FletcherAlgorithm.hpp.
gpnorm_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::gpnorm_ private
Definition at line 33 of file ROL_TypeE_FletcherAlgorithm.hpp.
sigma_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::sigma_ private
Definition at line 34 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
delta_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::delta_ private
Definition at line 34 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
minSigma_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::minSigma_ private
Definition at line 35 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
maxSigma_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::maxSigma_ private
Definition at line 35 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
sigmaUpdate_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::sigmaUpdate_ private
Definition at line 35 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
minDelta_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::minDelta_ private
Definition at line 36 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
deltaUpdate_
template<typename Real > Real ROL::TypeE::FletcherAlgorithm< Real >::deltaUpdate_ private
Definition at line 36 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
modifySigma_
template<typename Real > bool ROL::TypeE::FletcherAlgorithm< Real >::modifySigma_ private
Definition at line 37 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
subproblemIter_
template<typename Real > int ROL::TypeE::FletcherAlgorithm< Real >::subproblemIter_ private
Definition at line 38 of file ROL_TypeE_FletcherAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeE::FletcherAlgorithm< Real >::verbosity_ private
Definition at line 40 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
printHeader_
template<typename Real > bool ROL::TypeE::FletcherAlgorithm< Real >::printHeader_ private
Definition at line 41 of file ROL_TypeE_FletcherAlgorithm.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm().
The documentation for this class was generated from the following files:
ROL_TypeE_FletcherAlgorithm.hpp
ROL_TypeE_FletcherAlgorithm_Def.hpp