ROL: ROL::SmoothedPOE< Real > Class Template Reference
ROL::SmoothedPOE< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization
Provides the implementation of the smoothed probability of exceedance.
#include <ROL_SmoothedPOE.hpp>
Public Member Functions
SmoothedPOE (const Real threshold, const Real eps)
SmoothedPOE (ROL::ParameterList &parlist)
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void initialize (const Vector< Real > &x)
Initialize temporary variables.
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Member Functions
Real smoothHeaviside (const Real x, const int deriv=0) const
Private Attributes
Real threshold_
Real eps_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::SmoothedPOE< Real >
Provides the implementation of the smoothed probability of exceedance.
Let \((\Omega,\mathcal{F},\mathbb{P})\) be a complete space. Here, \(\Omega\) is the set of outcomes, \(\mathcal{F}\subseteq 2^\Omega\) is a \(\sigma\)-algebra of events and \(\mathbb{P}:\mathcal{F}\to[0,1]\) is a probability measure. Moreover, let \(\mathcal{X}\) be a class of random variables.
ROL's SmoothedPOE class inherits from ROL::RandVarFunctional which is written in a way to exploit parallel sampling.
Definition at line 32 of file ROL_SmoothedPOE.hpp.
Constructor & Destructor Documentation
SmoothedPOE() [1/2]
template<class Real > ROL::SmoothedPOE< Real >::SmoothedPOE (const Real threshold, const Real eps) inline
Definition at line 70 of file ROL_SmoothedPOE.hpp.
SmoothedPOE() [2/2]
template<class Real > ROL::SmoothedPOE< Real >::SmoothedPOE (ROL::ParameterList & parlist) inline
Definition at line 74 of file ROL_SmoothedPOE.hpp.
References ROL::SmoothedPOE< Real >::eps_, and ROL::SmoothedPOE< Real >::threshold_.
Member Function Documentation
smoothHeaviside()
template<class Real > Real ROL::SmoothedPOE< Real >::smoothHeaviside (const Real x, const int deriv = 0) const inline private
Definition at line 51 of file ROL_SmoothedPOE.hpp.
References ROL::SmoothedPOE< Real >::eps_.
Referenced by ROL::SmoothedPOE< Real >::updateGradient(), ROL::SmoothedPOE< Real >::updateHessVec(), and ROL::SmoothedPOE< Real >::updateValue().
updateValue()
template<class Real > void ROL::SmoothedPOE< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 81 of file ROL_SmoothedPOE.hpp.
References ROL::RandVarFunctional< Real >::computeValue(), ROL::SmoothedPOE< Real >::smoothHeaviside(), ROL::SmoothedPOE< Real >::threshold_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::SmoothedPOE< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 92 of file ROL_SmoothedPOE.hpp.
References ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateGradient()
template<class Real > void ROL::SmoothedPOE< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 100 of file ROL_SmoothedPOE.hpp.
References ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::SmoothedPOE< Real >::smoothHeaviside(), ROL::SmoothedPOE< Real >::threshold_, and ROL::RandVarFunctional< Real >::weight_.
getGradient()
template<class Real > void ROL::SmoothedPOE< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 112 of file ROL_SmoothedPOE.hpp.
References ROL::RandVarFunctional< Real >::g_, and ROL::SampleGenerator< Real >::sumAll().
updateHessVec()
template<class Real > void ROL::SmoothedPOE< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 120 of file ROL_SmoothedPOE.hpp.
References ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::hv_, ROL::SmoothedPOE< Real >::smoothHeaviside(), ROL::SmoothedPOE< Real >::threshold_, and ROL::RandVarFunctional< Real >::weight_.
getHessVec()
template<class Real > void ROL::SmoothedPOE< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 141 of file ROL_SmoothedPOE.hpp.
References ROL::RandVarFunctional< Real >::hv_, and ROL::SampleGenerator< Real >::sumAll().
Member Data Documentation
threshold_
template<class Real > Real ROL::SmoothedPOE< Real >::threshold_ private
Definition at line 34 of file ROL_SmoothedPOE.hpp.
Referenced by ROL::SmoothedPOE< Real >::SmoothedPOE(), ROL::SmoothedPOE< Real >::updateGradient(), ROL::SmoothedPOE< Real >::updateHessVec(), and ROL::SmoothedPOE< Real >::updateValue().
eps_
template<class Real > Real ROL::SmoothedPOE< Real >::eps_ private
Definition at line 35 of file ROL_SmoothedPOE.hpp.
Referenced by ROL::SmoothedPOE< Real >::SmoothedPOE(), and ROL::SmoothedPOE< Real >::smoothHeaviside().
The documentation for this class was generated from the following file:
ROL_SmoothedPOE.hpp