ROL: ConStdVector< Real, Element > Class Template Reference
ConStdVector< Real, Element > Class Template Reference
#include <example_02.hpp>
Public Member Functions
ConStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
ConStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void axpy (const Real alpha, const Vector &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
virtual void zero ()
Set to zero vector.
virtual void set (const Vector &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
virtual void applyUnary (const Elementwise::UnaryFunction< Real > &f)
virtual void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector &x)
virtual Real reduce (const Elementwise::ReductionOp< Real > &r) const
virtual void print (std::ostream &outStream) const
virtual void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
virtual void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef vector::size_type uint
Private Attributes
ROL::Ptr< std::vector< Element > > std_vec_
ROL::Ptr< ConDualStdVector< Real > > dual_vec_
Detailed Description
template<class Real, class Element>
class ConStdVector< Real, Element >
Definition at line 262 of file gross-pitaevskii/example_02.hpp.
Member Typedef Documentation
vector [1/2]
template<class Real , class Element > typedef std::vector<Element> ConStdVector< Real, Element >::vector private
Definition at line 232 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
V
template<class Real , class Element > typedef ROL::Vector<Real> ConStdVector< Real, Element >::V private
Definition at line 233 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
uint [1/2]
template<class Real , class Element > typedef vector::size_type ConStdVector< Real, Element >::uint private
Definition at line 234 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
vector [2/2]
template<class Real , class Element > typedef std::vector<Element> ConStdVector< Real, Element >::vector private
Definition at line 264 of file gross-pitaevskii/example_02.hpp.
uint [2/2]
template<class Real , class Element > typedef vector::size_type ConStdVector< Real, Element >::uint private
Definition at line 265 of file gross-pitaevskii/example_02.hpp.
Constructor & Destructor Documentation
ConStdVector() [1/2]
template<class Real , class Element > ConStdVector< Real, Element >::ConStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 242 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
ConStdVector() [2/2]
template<class Real , class Element > ConStdVector< Real, Element >::ConStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 273 of file gross-pitaevskii/example_02.hpp.
Member Function Documentation
plus() [1/2]
template<class Real , class Element > void ConStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 244 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::dimension(), ConStdVector< Real, Element >::getVector(), and ConStdVector< Real, Element >::std_vec_.
scale() [1/2]
template<class Real , class Element > void ConStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 253 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::dimension(), and ConStdVector< Real, Element >::std_vec_.
dot() [1/2]
template<class Real , class Element > Real ConStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 260 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::dimension(), ConStdVector< Real, Element >::getVector(), and ConStdVector< Real, Element >::std_vec_.
Referenced by ConStdVector< Real, Element >::norm().
norm() [1/2]
template<class Real , class Element > Real ConStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 271 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::dot().
clone() [1/2]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > ConStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 277 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::std_vec_.
getVector() [1/4]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > ConStdVector< Real, Element >::getVector () const inline
Definition at line 281 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::std_vec_.
Referenced by ConStdVector< Real, Element >::apply(), ConStdVector< Real, Element >::dot(), ConStdVector< Real, Element >::dot(), ConStdVector< Real, Element >::plus(), and ConStdVector< Real, Element >::plus().
getVector() [2/4]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > ConStdVector< Real, Element >::getVector () inline
Definition at line 285 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::std_vec_.
basis() [1/2]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > ConStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 289 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::std_vec_.
dimension() [1/2]
template<class Real , class Element > int ConStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 297 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::std_vec_.
Referenced by ConStdVector< Real, Element >::apply(), ConStdVector< Real, Element >::dot(), ConStdVector< Real, Element >::dot(), ConStdVector< Real, Element >::plus(), ConStdVector< Real, Element >::plus(), and ConStdVector< Real, Element >::scale().
dual() [1/2]
template<class Real , class Element > const ROL::Vector< Real > & ConStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 299 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::dual_vec_.
apply()
template<class Real , class Element > Real ConStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 304 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConStdVector< Real, Element >::dimension(), ConStdVector< Real, Element >::getVector(), and ConStdVector< Real, Element >::std_vec_.
plus() [2/2]
template<class Real , class Element > void ConStdVector< Real, Element >::plus (const Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 275 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::dimension(), ConStdVector< Real, Element >::getVector(), and ConStdVector< Real, Element >::std_vec_.
scale() [2/2]
template<class Real , class Element > void ConStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 284 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::dimension(), and ConStdVector< Real, Element >::std_vec_.
dot() [2/2]
template<class Real , class Element > Real ConStdVector< Real, Element >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 291 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::dimension(), ConStdVector< Real, Element >::getVector(), and ConStdVector< Real, Element >::std_vec_.
norm() [2/2]
template<class Real , class Element > Real ConStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 303 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::dot().
clone() [2/2]
template<class Real , class Element > ROL::Ptr< Vector< Real > > ConStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 309 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::std_vec_.
getVector() [3/4]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > ConStdVector< Real, Element >::getVector () const inline
Definition at line 313 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::std_vec_.
getVector() [4/4]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > ConStdVector< Real, Element >::getVector () inline
Definition at line 317 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::std_vec_.
basis() [2/2]
template<class Real , class Element > ROL::Ptr< Vector< Real > > ConStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 321 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::std_vec_.
dimension() [2/2]
template<class Real , class Element > int ConStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 328 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::std_vec_.
dual() [2/2]
template<class Real , class Element > const Vector< Real > & ConStdVector< Real, Element >::dual () const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 330 of file gross-pitaevskii/example_02.hpp.
References ConStdVector< Real, Element >::dual_vec_.
Member Data Documentation
std_vec_
template<class Real , class Element > ROL::Ptr< std::vector< Element > > ConStdVector< Real, Element >::std_vec_ private
Definition at line 237 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
Referenced by ConStdVector< Real, Element >::apply(), ConStdVector< Real, Element >::basis(), ConStdVector< Real, Element >::clone(), ConStdVector< Real, Element >::dimension(), ConStdVector< Real, Element >::dot(), ConStdVector< Real, Element >::dot(), ConStdVector< Real, Element >::getVector(), ConStdVector< Real, Element >::getVector(), ConStdVector< Real, Element >::plus(), ConStdVector< Real, Element >::plus(), and ConStdVector< Real, Element >::scale().
dual_vec_
template<class Real , class Element > ROL::Ptr< ConDualStdVector< Real > > ConStdVector< Real, Element >::dual_vec_ mutable private
Definition at line 238 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
Referenced by ConStdVector< Real, Element >::dual().
The documentation for this class was generated from the following files:
dual-spaces/simple-eq-constr-1/example_01.cpp
gross-pitaevskii/example_02.hpp