ROL: ROL::BatchStdVector< Real > Class Template Reference
ROL::BatchStdVector< Real > Class Template Reference
Provides the std::vector implementation of the ROL::Vector interface.
#include <ROL_BatchStdVector.hpp>
Public Member Functions
BatchStdVector (const Ptr< std::vector< Real > > &vec, const Ptr< BatchManager< Real > > &bman)
virtual Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
virtual Ptr< Vector< Real > > clone (void) const
Clone to make a new (uninitialized) vector.
int dimension (void) const
Return dimension of the vector space.
Real reduce (const Elementwise::ReductionOp< Real > &r) const
const Ptr< BatchManager< Real > > getBatchManager (void) const
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual const Vector & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Real >::size_type uint
Private Attributes
const Ptr< BatchManager< Real > > bman_
Detailed Description
template<class Real>
class ROL::BatchStdVector< Real >
Provides the std::vector implementation of the ROL::Vector interface.
Definition at line 24 of file ROL_BatchStdVector.hpp.
Member Typedef Documentation
uint
template<class Real > typedef std::vector<Real>::size_type ROL::BatchStdVector< Real >::uint private
Definition at line 25 of file ROL_BatchStdVector.hpp.
Constructor & Destructor Documentation
BatchStdVector()
template<class Real > ROL::BatchStdVector< Real >::BatchStdVector (const Ptr< std::vector< Real > > & vec, const Ptr< BatchManager< Real > > & bman) inline
Definition at line 30 of file ROL_BatchStdVector.hpp.
Member Function Documentation
dot()
template<class Real > virtual Real ROL::BatchStdVector< Real >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Reimplemented in ROL::PrimalAtomVector< Real >, ROL::DualAtomVector< Real >, ROL::PrimalProbabilityVector< Real >, and ROL::DualProbabilityVector< Real >.
Definition at line 34 of file ROL_BatchStdVector.hpp.
References ROL::BatchStdVector< Real >::bman_, and ROL::StdVector< Real, Element >::getVector().
clone()
template<class Real > virtual Ptr< Vector< Real > > ROL::BatchStdVector< Real >::clone (void) const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Reimplemented in ROL::PrimalAtomVector< Real >, ROL::DualAtomVector< Real >, ROL::ProbabilityVector< Real >, ROL::PrimalProbabilityVector< Real >, and ROL::DualProbabilityVector< Real >.
Definition at line 49 of file ROL_BatchStdVector.hpp.
References ROL::BatchStdVector< Real >::bman_, and ROL::StdVector< Real, Element >::getVector().
dimension()
template<class Real > int ROL::BatchStdVector< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 56 of file ROL_BatchStdVector.hpp.
References ROL::BatchStdVector< Real >::bman_, and dim.
Referenced by ROL::PrimalAtomVector< Real >::clone(), ROL::DualAtomVector< Real >::clone(), ROL::PrimalAtomVector< Real >::dot(), ROL::DualAtomVector< Real >::dot(), ROL::PrimalAtomVector< Real >::dual(), and ROL::DualAtomVector< Real >::dual().
reduce()
template<class Real > Real ROL::BatchStdVector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 63 of file ROL_BatchStdVector.hpp.
References ROL::BatchStdVector< Real >::bman_, and ROL::StdVector< Real, Element >::getVector().
getBatchManager()
template<class Real > const Ptr< BatchManager< Real > > ROL::BatchStdVector< Real >::getBatchManager (void) const inline
Definition at line 76 of file ROL_BatchStdVector.hpp.
References ROL::BatchStdVector< Real >::bman_.
Referenced by ROL::PrimalAtomVector< Real >::dot(), ROL::DualAtomVector< Real >::dot(), ROL::PrimalProbabilityVector< Real >::dot(), and ROL::DualProbabilityVector< Real >::dot().
Member Data Documentation
bman_
template<class Real > const Ptr<BatchManager<Real> > ROL::BatchStdVector< Real >::bman_ private
Definition at line 27 of file ROL_BatchStdVector.hpp.
Referenced by ROL::BatchStdVector< Real >::clone(), ROL::BatchStdVector< Real >::dimension(), ROL::BatchStdVector< Real >::dot(), ROL::BatchStdVector< Real >::getBatchManager(), and ROL::BatchStdVector< Real >::reduce().
The documentation for this class was generated from the following file:
ROL_BatchStdVector.hpp