ROL: ROL::details::DynamicObjective_CheckInterface< Real > Class Template Reference
ROL::details::DynamicObjective_CheckInterface< Real > Class Template Reference
#include <ROL_DynamicObjective_CheckInterface.hpp>
Public Member Functions
DynamicObjective_CheckInterface (Obj &obj)
DynamicObjective_CheckInterface (Obj &obj, TimeStamp< Real > &ts)
f_update_t< Real > update_uo (const V &un, const V &z)
f_update_t< Real > update_un (const V &uo, const V &z)
f_update_t< Real > update_z (const V &uo, const V &un)
f_scalar_t< Real > value_uo (const V &un, const V &z)
f_scalar_t< Real > value_un (const V &uo, const V &z)
f_scalar_t< Real > value_z (const V &uo, const V &un)
f_vector_t< Real > gradient_uo (const V &un, const V &z)
f_vector_t< Real > gradient_un (const V &uo, const V &z)
f_vector_t< Real > gradient_z (const V &uo, const V &un)
f_vector_t< Real > gradient_uo_uo (const V &un, const V &z)
f_vector_t< Real > gradient_uo_un (const V &uo, const V &z)
f_vector_t< Real > gradient_uo_z (const V &uo, const V &un)
f_vector_t< Real > gradient_un_uo (const V &un, const V &z)
f_vector_t< Real > gradient_un_un (const V &uo, const V &z)
f_vector_t< Real > gradient_un_z (const V &uo, const V &un)
f_vector_t< Real > gradient_z_uo (const V &un, const V &z)
f_vector_t< Real > gradient_z_un (const V &uo, const V &z)
f_vector_t< Real > gradient_z_z (const V &uo, const V &un)
f_dderiv_t< Real > hessVec_uo_uo (const V &un, const V &z)
f_dderiv_t< Real > hessVec_uo_un (const V &uo, const V &z)
f_dderiv_t< Real > hessVec_uo_z (const V &uo, const V &un)
f_dderiv_t< Real > hessVec_un_uo (const V &un, const V &z)
f_dderiv_t< Real > hessVec_un_un (const V &uo, const V &z)
f_dderiv_t< Real > hessVec_un_z (const V &uo, const V &un)
f_dderiv_t< Real > hessVec_z_uo (const V &un, const V &z)
f_dderiv_t< Real > hessVec_z_un (const V &uo, const V &z)
f_dderiv_t< Real > hessVec_z_z (const V &uo, const V &un)
Private Types
using V = Vector< Real >
using Obj = DynamicObjective< Real >
Private Attributes
Obj & obj_
Real tol_
TimeStamp< Real > ts_
Detailed Description
template<typename Real>
class ROL::details::DynamicObjective_CheckInterface< Real >
Definition at line 26 of file ROL_DynamicObjective_CheckInterface.hpp.
Member Typedef Documentation
V
template<typename Real > using ROL::details::DynamicObjective_CheckInterface< Real >::V = Vector<Real> private
Definition at line 29 of file ROL_DynamicObjective_CheckInterface.hpp.
Obj
template<typename Real > using ROL::details::DynamicObjective_CheckInterface< Real >::Obj = DynamicObjective<Real> private
Definition at line 30 of file ROL_DynamicObjective_CheckInterface.hpp.
Constructor & Destructor Documentation
DynamicObjective_CheckInterface() [1/2]
template<typename Real > ROL::details::DynamicObjective_CheckInterface< Real >::DynamicObjective_CheckInterface (Obj & obj) inline
Definition at line 38 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
DynamicObjective_CheckInterface() [2/2]
template<typename Real > ROL::details::DynamicObjective_CheckInterface< Real >::DynamicObjective_CheckInterface (Obj & obj, TimeStamp< Real > & ts) inline
Definition at line 45 of file ROL_DynamicObjective_CheckInterface.hpp.
Member Function Documentation
update_uo()
template<typename Real > f_update_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::update_uo (const V & un, const V & z) inline
Definition at line 49 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::details::DynamicObjective_CheckInterface< Real >::obj_, ROL::details::DynamicObjective_CheckInterface< Real >::ts_, and ROL::DynamicObjective< Real >::update().
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
update_un()
template<typename Real > f_update_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::update_un (const V & uo, const V & z) inline
Definition at line 53 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::details::DynamicObjective_CheckInterface< Real >::obj_, ROL::details::DynamicObjective_CheckInterface< Real >::ts_, and ROL::DynamicObjective< Real >::update().
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
update_z()
template<typename Real > f_update_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::update_z (const V & uo, const V & un) inline
Definition at line 57 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::details::DynamicObjective_CheckInterface< Real >::obj_, ROL::details::DynamicObjective_CheckInterface< Real >::ts_, and ROL::DynamicObjective< Real >::update().
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
value_uo()
template<typename Real > f_scalar_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::value_uo (const V & un, const V & z) inline
Definition at line 63 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::details::DynamicObjective_CheckInterface< Real >::obj_, ROL::details::DynamicObjective_CheckInterface< Real >::ts_, and ROL::DynamicObjective< Real >::value().
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
value_un()
template<typename Real > f_scalar_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::value_un (const V & uo, const V & z) inline
Definition at line 67 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::details::DynamicObjective_CheckInterface< Real >::obj_, ROL::details::DynamicObjective_CheckInterface< Real >::ts_, and ROL::DynamicObjective< Real >::value().
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
value_z()
template<typename Real > f_scalar_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::value_z (const V & uo, const V & un) inline
Definition at line 71 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::details::DynamicObjective_CheckInterface< Real >::obj_, ROL::details::DynamicObjective_CheckInterface< Real >::ts_, and ROL::DynamicObjective< Real >::value().
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_uo()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo (const V & un, const V & z) inline
Definition at line 77 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_un()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un (const V & uo, const V & z) inline
Definition at line 81 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_un(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_z()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z (const V & uo, const V & un) inline
Definition at line 85 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_z(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_uo_uo()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_uo (const V & un, const V & z) inline
Definition at line 90 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_uo_un()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_un (const V & uo, const V & z) inline
Definition at line 94 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_uo_z()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_z (const V & uo, const V & un) inline
Definition at line 98 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_un_uo()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_uo (const V & un, const V & z) inline
Definition at line 102 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_un(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_un_un()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_un (const V & uo, const V & z) inline
Definition at line 106 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_un(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_un_z()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_z (const V & uo, const V & un) inline
Definition at line 110 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_un(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_z_uo()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_uo (const V & un, const V & z) inline
Definition at line 114 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_z(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_z_un()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_un (const V & uo, const V & z) inline
Definition at line 118 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_z(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
gradient_z_z()
template<typename Real > f_vector_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_z (const V & uo, const V & un) inline
Definition at line 122 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::gradient_z(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_uo_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_uo (const V & un, const V & z) inline
Definition at line 128 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_uo_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_uo_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_un (const V & uo, const V & z) inline
Definition at line 132 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_uo_un(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_uo_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_z (const V & uo, const V & un) inline
Definition at line 136 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_uo_z(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_un_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_uo (const V & un, const V & z) inline
Definition at line 142 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_un_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_un_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_un (const V & uo, const V & z) inline
Definition at line 146 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_un_un(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_un_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_z (const V & uo, const V & un) inline
Definition at line 150 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_un_z(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_z_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_uo (const V & un, const V & z) inline
Definition at line 156 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_z_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_z_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_un (const V & uo, const V & z) inline
Definition at line 160 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_z_un(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
hessVec_z_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_z (const V & uo, const V & un) inline
Definition at line 164 of file ROL_DynamicObjective_CheckInterface.hpp.
References ROL::DynamicObjective< Real >::hessVec_z_z(), ROL::details::DynamicObjective_CheckInterface< Real >::obj_, and ROL::details::DynamicObjective_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicObjectiveCheck< Real >::check().
Member Data Documentation
obj_
template<typename Real > Obj& ROL::details::DynamicObjective_CheckInterface< Real >::obj_ private
Definition at line 32 of file ROL_DynamicObjective_CheckInterface.hpp.
Referenced by ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_z(), ROL::details::DynamicObjective_CheckInterface< Real >::update_un(), ROL::details::DynamicObjective_CheckInterface< Real >::update_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::update_z(), ROL::details::DynamicObjective_CheckInterface< Real >::value_un(), ROL::details::DynamicObjective_CheckInterface< Real >::value_uo(), and ROL::details::DynamicObjective_CheckInterface< Real >::value_z().
tol_
template<typename Real > Real ROL::details::DynamicObjective_CheckInterface< Real >::tol_ private
Definition at line 33 of file ROL_DynamicObjective_CheckInterface.hpp.
ts_
template<typename Real > TimeStamp<Real> ROL::details::DynamicObjective_CheckInterface< Real >::ts_ private
Definition at line 34 of file ROL_DynamicObjective_CheckInterface.hpp.
Referenced by ROL::details::DynamicObjective_CheckInterface< Real >::DynamicObjective_CheckInterface(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_z(), ROL::details::DynamicObjective_CheckInterface< Real >::update_un(), ROL::details::DynamicObjective_CheckInterface< Real >::update_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::update_z(), ROL::details::DynamicObjective_CheckInterface< Real >::value_un(), ROL::details::DynamicObjective_CheckInterface< Real >::value_uo(), and ROL::details::DynamicObjective_CheckInterface< Real >::value_z().
The documentation for this class was generated from the following file:
ROL_DynamicObjective_CheckInterface.hpp