ROL: ROL::RiskVector< Real > Class Template Reference
ROL::RiskVector< Real > Class Template Reference
#include <ROL_RiskVector.hpp>
Public Member Functions
RiskVector (Ptr< ParameterList > &parlist, const Ptr< Vector< Real > > &vec, const Real stat=0)
RiskVector (std::vector< Ptr< ParameterList > > &parlist, const Ptr< Vector< Real > > &vec, const Real stat=0)
RiskVector (Ptr< ParameterList > &parlistObj, std::vector< Ptr< ParameterList > > &parlistCon, const Ptr< Vector< Real > > &vec, const Real stat=0)
RiskVector (const Ptr< Vector< Real > > &vec, const Ptr< std::vector< Real > > &statObj, const std::vector< Ptr< std::vector< Real > > > &statCon)
RiskVector (const Ptr< Vector< Real > > &vec)
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm (void) const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< Vector< Real > > clone (void) const
Clone to make a new (uninitialized) vector.
const Vector< Real > & dual (void) const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
int dimension (void) const
Return dimension of the vector space.
Ptr< const StdVector< Real > > getStatisticVector (const int comp, const int index=0) const
Ptr< StdVector< Real > > getStatisticVector (const int comp, const int index=0)
Ptr< const Vector< Real > > getVector (void) const
Ptr< Vector< Real > > getVector (void)
Ptr< std::vector< Real > > getStatistic (const int comp=0, const int index=0)
Ptr< const std::vector< Real > > getStatistic (const int comp=0, const int index=0) const
void setStatistic (const Real stat, const int comp=0, const int index=0)
void setStatistic (const std::vector< Real > &stat, const int comp=0, const int index=0)
void setVector (const Vector< Real > &vec)
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual void print (std::ostream &outStream) const
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Member Functions
void initializeObj (Ptr< ParameterList > &parlist, const Real stat=1)
void initializeCon (std::vector< Ptr< ParameterList > > &parlist, const Real stat=1)
Private Attributes
Ptr< std::vector< Real > > statObj_
Ptr< StdVector< Real > > statObj_vec_
bool augmentedObj_
int nStatObj_
std::vector< Ptr< std::vector< Real > > > statCon_
std::vector< Ptr< StdVector< Real > > > statCon_vec_
bool augmentedCon_
std::vector< int > nStatCon_
Ptr< Vector< Real > > vec_
bool isDualInitialized_
Ptr< std::vector< Real > > dualObj_
std::vector< Ptr< std::vector< Real > > > dualCon_
Ptr< Vector< Real > > dual_vec1_
Ptr< RiskVector< Real > > dual_vec_
Detailed Description
template<class Real>
class ROL::RiskVector< Real >
Definition at line 20 of file ROL_RiskVector.hpp.
Constructor & Destructor Documentation
RiskVector() [1/5]
template<class Real > ROL::RiskVector< Real >::RiskVector (Ptr< ParameterList > & parlist, const Ptr< Vector< Real > > & vec, const Real stat = 0) inline
Definition at line 93 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::initializeObj().
RiskVector() [2/5]
template<class Real > ROL::RiskVector< Real >::RiskVector (std::vector< Ptr< ParameterList > > & parlist, const Ptr< Vector< Real > > & vec, const Real stat = 0) inline
Definition at line 104 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::initializeCon().
RiskVector() [3/5]
template<class Real > ROL::RiskVector< Real >::RiskVector (Ptr< ParameterList > & parlistObj, std::vector< Ptr< ParameterList > > & parlistCon, const Ptr< Vector< Real > > & vec, const Real stat = 0) inline
Definition at line 115 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::initializeCon(), and ROL::RiskVector< Real >::initializeObj().
RiskVector() [4/5]
template<class Real > ROL::RiskVector< Real >::RiskVector (const Ptr< Vector< Real > > & vec, const Ptr< std::vector< Real > > & statObj, const std::vector< Ptr< std::vector< Real > > > & statCon) inline
Definition at line 128 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::nStatCon_, ROL::RiskVector< Real >::nStatObj_, ROL::RiskVector< Real >::statCon_, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_, and ROL::RiskVector< Real >::statObj_vec_.
RiskVector() [5/5]
template<class Real > ROL::RiskVector< Real >::RiskVector (const Ptr< Vector< Real > > & vec) inline
Definition at line 156 of file ROL_RiskVector.hpp.
Member Function Documentation
initializeObj()
template<class Real > void ROL::RiskVector< Real >::initializeObj (Ptr< ParameterList > & parlist, const Real stat = 1) inline private
Definition at line 40 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::nStatObj_, ROL::RiskVector< Real >::statObj_, and ROL::RiskVector< Real >::statObj_vec_.
Referenced by ROL::RiskVector< Real >::RiskVector(), and ROL::RiskVector< Real >::RiskVector().
initializeCon()
template<class Real > void ROL::RiskVector< Real >::initializeCon (std::vector< Ptr< ParameterList > > & parlist, const Real stat = 1) inline private
Definition at line 61 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::nStatCon_, ROL::RiskVector< Real >::statCon_, and ROL::RiskVector< Real >::statCon_vec_.
Referenced by ROL::RiskVector< Real >::RiskVector(), and ROL::RiskVector< Real >::RiskVector().
set()
template<class Real > void ROL::RiskVector< Real >::set (const Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 161 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::getVector(), ROL::RiskVector< Real >::set(), ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
Referenced by ROL::RiskVector< Real >::set().
plus()
template<class Real > void ROL::RiskVector< Real >::plus (const Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 177 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::getVector(), ROL::RiskVector< Real >::plus(), ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
Referenced by ROL::RiskVector< Real >::plus().
scale()
template<class Real > void ROL::RiskVector< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 193 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
axpy()
template<class Real > void ROL::RiskVector< Real >::axpy (const Real alpha, const Vector< Real > & x) inline virtual
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of @b x.
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = \mathtt{*this} + \alpha x \f$.
   Uses #clone, #set, #scale and #plus for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 208 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::getVector(), ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
Referenced by ROL::RiskVector< Real >::axpy().
dot()
template<class Real > Real ROL::RiskVector< Real >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 224 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::dot(), ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::getVector(), ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
Referenced by ROL::RiskVector< Real >::dot(), and ROL::RiskVector< Real >::norm().
norm()
template<class Real > Real ROL::RiskVector< Real >::norm (void) const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 241 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::dot().
clone()
template<class Real > Ptr< Vector< Real > > ROL::RiskVector< Real >::clone (void) const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 245 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::nStatCon_, ROL::RiskVector< Real >::nStatObj_, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
dual()
template<class Real > const Vector< Real > & ROL::RiskVector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 260 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::dual_vec1_, ROL::RiskVector< Real >::dual_vec_, ROL::RiskVector< Real >::dualCon_, ROL::RiskVector< Real >::dualObj_, ROL::RiskVector< Real >::isDualInitialized_, ROL::RiskVector< Real >::setStatistic(), ROL::RiskVector< Real >::statCon_, ROL::RiskVector< Real >::statObj_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
basis()
template<class Real > Ptr< Vector< Real > > ROL::RiskVector< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 296 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::nStatCon_, ROL::RiskVector< Real >::nStatObj_, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
applyUnary()
template<class Real > void ROL::RiskVector< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 340 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
applyBinary()
template<class Real > void ROL::RiskVector< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const Vector< Real > & x) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 355 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::applyBinary(), ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::getVector(), ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
Referenced by ROL::RiskVector< Real >::applyBinary().
reduce()
template<class Real > Real ROL::RiskVector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 371 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::reduce(), ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
Referenced by ROL::RiskVector< Real >::reduce().
setScalar()
template<class Real > void ROL::RiskVector< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 388 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
randomize()
template<class Real > void ROL::RiskVector< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 403 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
dimension()
template<class Real > int ROL::RiskVector< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 418 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, dim, ROL::RiskVector< Real >::statCon_vec_, ROL::RiskVector< Real >::statObj_vec_, and ROL::RiskVector< Real >::vec_.
getStatisticVector() [1/2]
template<class Real > Ptr< const StdVector< Real > > ROL::RiskVector< Real >::getStatisticVector (const int comp, const int index = 0) const inline
Definition at line 438 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::statCon_vec_, and ROL::RiskVector< Real >::statObj_vec_.
Referenced by ROL::RiskVector< Real >::applyBinary(), ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::dot(), ROL::RiskVector< Real >::plus(), and ROL::RiskVector< Real >::set().
getStatisticVector() [2/2]
template<class Real > Ptr< StdVector< Real > > ROL::RiskVector< Real >::getStatisticVector (const int comp, const int index = 0) inline
Definition at line 451 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::statCon_vec_, and ROL::RiskVector< Real >::statObj_vec_.
getVector() [1/2]
template<class Real > Ptr< const Vector< Real > > ROL::RiskVector< Real >::getVector (void) const inline
Definition at line 463 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::vec_.
Referenced by ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::RiskVector< Real >::applyBinary(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::dot(), ROL::PH_bPOEObjective< Real >::getConstVector(), ROL::PH_DeviationObjective< Real >::getConstVector(), ROL::PH_RiskObjective< Real >::getConstVector(), ROL::StochasticObjective< Real >::getConstVector(), ROL::PH_bPOEObjective< Real >::getVector(), ROL::PH_DeviationObjective< Real >::getVector(), ROL::PH_RiskObjective< Real >::getVector(), ROL::StochasticObjective< Real >::getVector(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), ROL::RiskVector< Real >::plus(), ROL::PrimalDualRisk< Real >::run(), ROL::RiskVector< Real >::set(), ROL::SimulatedObjectiveCVaR< Real >::value(), and ROL::SimulatedConstraint< Real >::value().
getVector() [2/2]
template<class Real > Ptr< Vector< Real > > ROL::RiskVector< Real >::getVector (void) inline
Definition at line 467 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::vec_.
getStatistic() [1/2]
template<class Real > Ptr< std::vector< Real > > ROL::RiskVector< Real >::getStatistic (const int comp = 0, const int index = 0) inline
Definition at line 475 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::statCon_, and ROL::RiskVector< Real >::statObj_.
Referenced by ROL::PH_bPOEObjective< Real >::getConstStat(), ROL::PH_DeviationObjective< Real >::getConstStat(), ROL::PH_RiskObjective< Real >::getConstStat(), ROL::StochasticObjective< Real >::getConstStat(), ROL::PH_bPOEObjective< Real >::getStat(), ROL::PH_DeviationObjective< Real >::getStat(), ROL::PH_RiskObjective< Real >::getStat(), ROL::StochasticObjective< Real >::getStat(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), and ROL::SimulatedObjectiveCVaR< Real >::value().
getStatistic() [2/2]
template<class Real > Ptr< const std::vector< Real > > ROL::RiskVector< Real >::getStatistic (const int comp = 0, const int index = 0) const inline
Definition at line 493 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::statCon_, and ROL::RiskVector< Real >::statObj_.
setStatistic() [1/2]
template<class Real > void ROL::RiskVector< Real >::setStatistic (const Real stat, const int comp = 0, const int index = 0) inline
Definition at line 510 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::nStatCon_, ROL::RiskVector< Real >::nStatObj_, ROL::RiskVector< Real >::statCon_, and ROL::RiskVector< Real >::statObj_.
Referenced by ROL::RiskVector< Real >::dual(), and ROL::SimulatedObjectiveCVaR< Real >::gradient().
setStatistic() [2/2]
template<class Real > void ROL::RiskVector< Real >::setStatistic (const std::vector< Real > & stat, const int comp = 0, const int index = 0) inline
Definition at line 526 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::augmentedCon_, ROL::RiskVector< Real >::augmentedObj_, ROL::RiskVector< Real >::nStatCon_, ROL::RiskVector< Real >::nStatObj_, ROL::RiskVector< Real >::statCon_, and ROL::RiskVector< Real >::statObj_.
setVector()
template<class Real > void ROL::RiskVector< Real >::setVector (const Vector< Real > & vec) inline
Definition at line 548 of file ROL_RiskVector.hpp.
References ROL::RiskVector< Real >::vec_.
Member Data Documentation
statObj_
template<class Real > Ptr<std::vector<Real> > ROL::RiskVector< Real >::statObj_ private
Definition at line 22 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::dual(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::initializeObj(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::setStatistic(), and ROL::RiskVector< Real >::setStatistic().
statObj_vec_
template<class Real > Ptr<StdVector<Real> > ROL::RiskVector< Real >::statObj_vec_ private
Definition at line 23 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::applyBinary(), ROL::RiskVector< Real >::applyUnary(), ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::basis(), ROL::RiskVector< Real >::clone(), ROL::RiskVector< Real >::dimension(), ROL::RiskVector< Real >::dot(), ROL::RiskVector< Real >::dual(), ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::initializeObj(), ROL::RiskVector< Real >::plus(), ROL::RiskVector< Real >::randomize(), ROL::RiskVector< Real >::reduce(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::scale(), ROL::RiskVector< Real >::set(), and ROL::RiskVector< Real >::setScalar().
augmentedObj_
template<class Real > bool ROL::RiskVector< Real >::augmentedObj_ private
Definition at line 24 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::applyBinary(), ROL::RiskVector< Real >::applyUnary(), ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::basis(), ROL::RiskVector< Real >::clone(), ROL::RiskVector< Real >::dimension(), ROL::RiskVector< Real >::dot(), ROL::RiskVector< Real >::dual(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::initializeObj(), ROL::RiskVector< Real >::plus(), ROL::RiskVector< Real >::randomize(), ROL::RiskVector< Real >::reduce(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::scale(), ROL::RiskVector< Real >::set(), ROL::RiskVector< Real >::setScalar(), ROL::RiskVector< Real >::setStatistic(), and ROL::RiskVector< Real >::setStatistic().
nStatObj_
template<class Real > int ROL::RiskVector< Real >::nStatObj_ private
Definition at line 25 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::basis(), ROL::RiskVector< Real >::clone(), ROL::RiskVector< Real >::initializeObj(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::setStatistic(), and ROL::RiskVector< Real >::setStatistic().
statCon_
template<class Real > std::vector<Ptr<std::vector<Real> > > ROL::RiskVector< Real >::statCon_ private
Definition at line 27 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::dual(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::initializeCon(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::setStatistic(), and ROL::RiskVector< Real >::setStatistic().
statCon_vec_
template<class Real > std::vector<Ptr<StdVector<Real> > > ROL::RiskVector< Real >::statCon_vec_ private
Definition at line 28 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::applyBinary(), ROL::RiskVector< Real >::applyUnary(), ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::basis(), ROL::RiskVector< Real >::clone(), ROL::RiskVector< Real >::dimension(), ROL::RiskVector< Real >::dot(), ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::getStatisticVector(), ROL::RiskVector< Real >::initializeCon(), ROL::RiskVector< Real >::plus(), ROL::RiskVector< Real >::randomize(), ROL::RiskVector< Real >::reduce(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::scale(), ROL::RiskVector< Real >::set(), and ROL::RiskVector< Real >::setScalar().
augmentedCon_
template<class Real > bool ROL::RiskVector< Real >::augmentedCon_ private
Definition at line 29 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::applyBinary(), ROL::RiskVector< Real >::applyUnary(), ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::dimension(), ROL::RiskVector< Real >::dot(), ROL::RiskVector< Real >::dual(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::getStatistic(), ROL::RiskVector< Real >::initializeCon(), ROL::RiskVector< Real >::plus(), ROL::RiskVector< Real >::randomize(), ROL::RiskVector< Real >::reduce(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::scale(), ROL::RiskVector< Real >::set(), ROL::RiskVector< Real >::setScalar(), ROL::RiskVector< Real >::setStatistic(), and ROL::RiskVector< Real >::setStatistic().
nStatCon_
template<class Real > std::vector<int> ROL::RiskVector< Real >::nStatCon_ private
Definition at line 30 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::basis(), ROL::RiskVector< Real >::clone(), ROL::RiskVector< Real >::initializeCon(), ROL::RiskVector< Real >::RiskVector(), ROL::RiskVector< Real >::setStatistic(), and ROL::RiskVector< Real >::setStatistic().
vec_
template<class Real > Ptr<Vector<Real> > ROL::RiskVector< Real >::vec_ private
Definition at line 32 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::applyBinary(), ROL::RiskVector< Real >::applyUnary(), ROL::RiskVector< Real >::axpy(), ROL::RiskVector< Real >::basis(), ROL::RiskVector< Real >::clone(), ROL::RiskVector< Real >::dimension(), ROL::RiskVector< Real >::dot(), ROL::RiskVector< Real >::dual(), ROL::RiskVector< Real >::getVector(), ROL::RiskVector< Real >::getVector(), ROL::RiskVector< Real >::plus(), ROL::RiskVector< Real >::randomize(), ROL::RiskVector< Real >::reduce(), ROL::RiskVector< Real >::scale(), ROL::RiskVector< Real >::set(), ROL::RiskVector< Real >::setScalar(), and ROL::RiskVector< Real >::setVector().
isDualInitialized_
template<class Real > bool ROL::RiskVector< Real >::isDualInitialized_ mutable private
Definition at line 34 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::dual().
dualObj_
template<class Real > Ptr<std::vector<Real> > ROL::RiskVector< Real >::dualObj_ mutable private
Definition at line 35 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::dual().
dualCon_
template<class Real > std::vector<Ptr<std::vector<Real> > > ROL::RiskVector< Real >::dualCon_ mutable private
Definition at line 36 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::dual().
dual_vec1_
template<class Real > Ptr<Vector<Real> > ROL::RiskVector< Real >::dual_vec1_ mutable private
Definition at line 37 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::dual().
dual_vec_
template<class Real > Ptr<RiskVector<Real> > ROL::RiskVector< Real >::dual_vec_ mutable private
Definition at line 38 of file ROL_RiskVector.hpp.
Referenced by ROL::RiskVector< Real >::dual().
The documentation for this class was generated from the following file:
ROL_RiskVector.hpp