ROL: ROL::PrimalScaledStdVector< Real, Element > Class Template Reference
ROL::PrimalScaledStdVector< Real, Element > Class Template Reference
Provides the std::vector implementation of the ROL::Vector interface that handles scalings in the inner product. Also see ROL::DualScaledStdVector.
#include <ROL_ScaledStdVector.hpp>
Public Member Functions
PrimalScaledStdVector (const Ptr< std::vector< Element > > &std_vec, const Ptr< std::vector< Element > > &scaling_vec)
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Ptr< Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
const Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Element >::size_type uint
Private Attributes
Ptr< std::vector< Element > > scaling_vec_
Ptr< DualScaledStdVector< Real > > dual_vec_
bool isDualInitialized_
Detailed Description
template<class Real, class Element>
class ROL::PrimalScaledStdVector< Real, Element >
Provides the std::vector implementation of the ROL::Vector interface that handles scalings in the inner product. Also see ROL::DualScaledStdVector.
Definition at line 34 of file ROL_ScaledStdVector.hpp.
Member Typedef Documentation
uint
template<class Real , class Element > typedef std::vector<Element>::size_type ROL::PrimalScaledStdVector< Real, Element >::uint private
Definition at line 36 of file ROL_ScaledStdVector.hpp.
Constructor & Destructor Documentation
PrimalScaledStdVector()
template<class Real , class Element > ROL::PrimalScaledStdVector< Real, Element >::PrimalScaledStdVector (const Ptr< std::vector< Element > > & std_vec, const Ptr< std::vector< Element > > & scaling_vec) inline
Definition at line 46 of file ROL_ScaledStdVector.hpp.
Member Function Documentation
dot()
template<class Real , class Element > Real ROL::PrimalScaledStdVector< Real, Element >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 51 of file ROL_ScaledStdVector.hpp.
References ROL::StdVector< Real, Element >::dimension(), and ROL::StdVector< Real, Element >::getVector().
Referenced by main().
clone()
template<class Real , class Element > Ptr< Vector< Real > > ROL::PrimalScaledStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 63 of file ROL_ScaledStdVector.hpp.
References ROL::StdVector< Real, Element >::dimension(), ROL::StdVector< Real, Element >::getVector(), and ROL::PrimalScaledStdVector< Real, Element >::scaling_vec_.
Referenced by main().
dual()
template<class Real , class Element > const Vector< Real > & ROL::PrimalScaledStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 69 of file ROL_ScaledStdVector.hpp.
References ROL::PrimalScaledStdVector< Real, Element >::dual_vec_, ROL::StdVector< Real, Element >::getVector(), ROL::PrimalScaledStdVector< Real, Element >::isDualInitialized_, and ROL::PrimalScaledStdVector< Real, Element >::scaling_vec_.
Referenced by main().
apply()
template<class Real , class Element > Real ROL::PrimalScaledStdVector< Real, Element >::apply (const Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 84 of file ROL_ScaledStdVector.hpp.
References ROL::StdVector< Real, Element >::dot().
Referenced by main().
Member Data Documentation
scaling_vec_
template<class Real , class Element > Ptr<std::vector<Element> > ROL::PrimalScaledStdVector< Real, Element >::scaling_vec_ private
Definition at line 40 of file ROL_ScaledStdVector.hpp.
Referenced by ROL::PrimalScaledStdVector< Real, Element >::clone(), and ROL::PrimalScaledStdVector< Real, Element >::dual().
dual_vec_
template<class Real , class Element > Ptr<DualScaledStdVector<Real> > ROL::PrimalScaledStdVector< Real, Element >::dual_vec_ mutable private
Definition at line 41 of file ROL_ScaledStdVector.hpp.
Referenced by ROL::PrimalScaledStdVector< Real, Element >::dual().
isDualInitialized_
template<class Real , class Element > bool ROL::PrimalScaledStdVector< Real, Element >::isDualInitialized_ mutable private
Definition at line 42 of file ROL_ScaledStdVector.hpp.
Referenced by ROL::PrimalScaledStdVector< Real, Element >::dual().
The documentation for this class was generated from the following file:
ROL_ScaledStdVector.hpp