ROL: ROL::ScaledObjective< Real > Class Template Reference
ROL::ScaledObjective< Real > Class Template Reference
#include <ROL_ScaledObjective.hpp>
Public Member Functions
ScaledObjective (const Ptr< Objective< Real > > &obj, Real scale)
void update (const Vector< Real > &x, UpdateType type, int iter=-1) override
Update objective function.
void setParameter (const std::vector< Real > &param) override
Real value (const Vector< Real > &x, Real &tol) override
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol) override
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply Hessian approximation to vector.
void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply inverse Hessian approximation to vector.
void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply preconditioner to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
Private Attributes
const Ptr< Objective< Real > > obj_
const Real scale_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::ScaledObjective< Real >
Definition at line 18 of file ROL_ScaledObjective.hpp.
Constructor & Destructor Documentation
ScaledObjective()
template<typename Real > ROL::ScaledObjective< Real >::ScaledObjective (const Ptr< Objective< Real > > & obj, Real scale) inline
Definition at line 24 of file ROL_ScaledObjective.hpp.
Member Function Documentation
update()
template<typename Real > void ROL::ScaledObjective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 16 of file ROL_ScaledObjective_Def.hpp.
References obj_.
setParameter()
template<typename Real > void ROL::ScaledObjective< Real >::setParameter (const std::vector< Real > & param) override virtual
Reimplemented from ROL::Objective< Real >.
Definition at line 21 of file ROL_ScaledObjective_Def.hpp.
References obj_, and ROL::Objective< Real >::setParameter().
value()
template<typename Real > Real ROL::ScaledObjective< Real >::value (const Vector< Real > & x, Real & tol) override virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 27 of file ROL_ScaledObjective_Def.hpp.
References obj_.
gradient()
template<typename Real > void ROL::ScaledObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) override virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 32 of file ROL_ScaledObjective_Def.hpp.
References obj_, and ROL::Vector< Real >::scale().
hessVec()
template<typename Real > void ROL::ScaledObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 38 of file ROL_ScaledObjective_Def.hpp.
References obj_, and ROL::Vector< Real >::scale().
invHessVec()
template<typename Real > void ROL::ScaledObjective< Real >::invHessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 44 of file ROL_ScaledObjective_Def.hpp.
References obj_, and ROL::Vector< Real >::scale().
precond()
template<typename Real > void ROL::ScaledObjective< Real >::precond (Vector< Real > & Pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 50 of file ROL_ScaledObjective_Def.hpp.
References obj_, and ROL::Vector< Real >::scale().
Member Data Documentation
obj_
template<typename Real > const Ptr<Objective<Real> > ROL::ScaledObjective< Real >::obj_ private
Definition at line 20 of file ROL_ScaledObjective.hpp.
scale_
template<typename Real > const Real ROL::ScaledObjective< Real >::scale_ private
Definition at line 21 of file ROL_ScaledObjective.hpp.
The documentation for this class was generated from the following files:
ROL_ScaledObjective.hpp
ROL_ScaledObjective_Def.hpp