ROL: ROL::Vector< Real > Class Template Reference
ROL::Vector< Real > Class Template Reference abstract
User Interface » Linear Algebra Interface
Defines the linear algebra or vector space interface.
#include <ROL_Vector.hpp>
Public Member Functions
virtual ~Vector ()
virtual void plus (const Vector &x)=0
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
virtual void scale (const Real alpha)=0
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
virtual Real dot (const Vector &x) const =0
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
virtual Real norm () const =0
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
virtual ROL::Ptr< Vector > clone () const =0
Clone to make a new (uninitialized) vector.
virtual void axpy (const Real alpha, const Vector &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
virtual void zero ()
Set to zero vector.
virtual ROL::Ptr< Vector > basis (const int i) const
Return i-th basis vector.
virtual int dimension () const
Return dimension of the vector space.
virtual void set (const Vector &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
virtual const Vector & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual void applyUnary (const Elementwise::UnaryFunction< Real > &f)
virtual void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector &x)
virtual Real reduce (const Elementwise::ReductionOp< Real > &r) const
virtual void print (std::ostream &outStream) const
virtual void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
virtual void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Detailed Description
template<class Real>
class ROL::Vector< Real >
Defines the linear algebra or vector space interface.
The basic linear algebra interface, to be implemented by the user, includes:
plus – vector addition;
scale – scalar multiplication;
dot – dot (scalar) product of vectors;
norm – vector norm;
clone – cloning of existing vectors.
The dot product can represent an inner product (in Hilbert space) or a duality pairing (in general Banach space).
There are additional virtual member functions that can be overloaded for computational efficiency.
Definition at line 46 of file ROL_Vector.hpp.
Constructor & Destructor Documentation
~Vector()
template<class Real > virtual ROL::Vector< Real >::~Vector () inline virtual
Definition at line 53 of file ROL_Vector.hpp.
Member Function Documentation
plus()
template<class Real > virtual void ROL::Vector< Real >::plus (const Vector< Real > & x) pure virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::SingletonVector< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::ElementwiseVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::ReducedDynamicObjective< Real >::addAdjointSens(), ROL::ReducedDynamicObjective< Real >::addMixedHessLag(), ROL::ReducedDynamicObjective< Real >::advanceAdjoint(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::HessianPNK::apply(), ROL::LinearOperatorSum< Real >::apply(), ROL::ProjectedNewtonKrylovStep< Real >::HessianPNK::apply(), ROL::ChainRuleConstraint< Real >::applyAdjointHessian(), ROL::Reduced_Constraint_SimOpt< Real >::applyAdjointHessian(), ROL::CompositeConstraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::BoundToConstraint< Real >::applyAdjointJacobian(), ROL::Reduced_Constraint_SimOpt< Real >::applyAdjointJacobian(), ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::ColemanLiAlgorithm< Real >::applyHessian(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS::applyInverse(), ROL::ProjectedNewtonKrylovStep< Real >::PrecondPNK::applyInverse(), ROL::Constraint_SimOpt< Real >::applyJacobian(), ROL::ElasticLinearConstraint< Real >::applyJacobian(), ROL::Reduced_Constraint_SimOpt< Real >::applyJacobian(), ROL::Bounds< Real >::applyScalingFunctionJacobian(), ROL::Vector< Real >::axpy(), ROL::Bounds< Real >::buildScalingFunction(), ROL::LineSearchStep< Real >::compute(), ROL::ProjectedNewtonStep< Real >::compute(), ROL::ProjectedSecantStep< Real >::compute(), ROL::PrimalDualActiveSetStep< Real >::compute(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeLagrangeMultiplier(), ROL::ReducedDynamicObjective< Real >::computeNewMixedHessLag(), ROL::ReducedDynamicObjective< Real >::computeNewStateHessLag(), ROL::ReducedDynamicObjective< Real >::computeOldMixedHessLag(), ROL::ReducedDynamicObjective< Real >::computeOldStateHessLag(), ROL::BoundConstraint< Real >::computeProjectedStep(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::LinMore< Real >::dprsrch(), ROL::TypeB::LinMoreAlgorithm< Real >::dprsrch(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TypeB::LSecantBAlgorithm< Real >::dsrch(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::MeanVariance< Real >::getGradient(), ROL::PD_MeanSemiDeviation< Real >::getHessVec(), ROL::MeanVariance< Real >::getHessVec(), ROL::ConicApproximationModel< Real >::gradient(), ROL::ColemanLiModel< Real >::gradient(), ROL::KelleySachsModel< Real >::gradient(), ROL::TrustRegionModel< Real >::gradient(), ROL::TrustRegionModel_U< Real >::gradient(), ROL::TypeP::InexactNewtonAlgorithm< Real >::NewtonObj::gradient(), ROL::ObjectiveMMA< Real >::gradient(), ROL::PH_Objective< Real >::gradient(), ROL::AugmentedLagrangian< Real >::gradient(), ROL::InteriorPoint::PenalizedObjective< Real >::gradient(), ROL::PQNObjective< Real >::gradient(), ROL::FletcherObjectiveE< Real >::gradient(), ROL::QuadraticObjective< Real >::gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::gradient(), ROL::Reduced_Objective_SimOpt< Real >::gradient(), ROL::AugmentedLagrangian_SimOpt< Real >::gradient_1(), ROL::gradient_1(), ROL::AugmentedLagrangian_SimOpt< Real >::gradient_2(), ROL::ColemanLiModel< Real >::hessVec(), ROL::KelleySachsModel< Real >::hessVec(), ROL::NonlinearLeastSquaresObjective_Dynamic< Real >::hessVec(), ROL::ChainRuleObjective< Real >::hessVec(), ROL::ObjectiveMMA< Real >::hessVec(), ROL::AugmentedLagrangian< Real >::hessVec(), ROL::QuadraticPenalty< Real >::hessVec(), ROL::BoundFletcher< Real >::hessVec(), ROL::Fletcher< Real >::hessVec(), ROL::InteriorPoint::PenalizedObjective< Real >::hessVec(), ROL::FletcherObjectiveE< Real >::hessVec(), ROL::NonlinearLeastSquaresObjective< Real >::hessVec(), ROL::Reduced_Objective_SimOpt< Real >::hessVec(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_11(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_11(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_12(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_12(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_21(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_21(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_22(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_22(), ROL::KelleySachsModel< Real >::invHessVec(), ROL::KelleySachsModel< Real >::precond(), ROL::KelleySachsModel< Real >::primalTransform(), ROL::DouglasRachfordProjection< Real >::project_con(), ROL::DykstraProjection< Real >::project_con(), ROL::l1Objective< Real >::prox(), ROL::ShiftedProxObjective< Real >::prox(), ROL::RandomizeFeasibleVector(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), ROL::ProjectedObjective< Real >::reducedPrecond(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::LinMoreAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeU::BundleAlgorithm< Real >::run(), ROL::TypeU::LineSearchAlgorithm< Real >::run(), ROL::TypeU::TrustRegionAlgorithm< Real >::run(), ROL::TypeP::TrustRegionAlgorithm< Real >::run(), ROL::GMRES< Real >::run(), ROL::Vector< Real >::set(), Normalization_Constraint< Real >::solveAugmentedSystem(), ROL::BoundFletcher< Real >::solveAugmentedSystem(), ROL::Fletcher< Real >::solveAugmentedSystem(), ROL::FletcherObjectiveE< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::InteriorPointStep< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::NewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonStep< Real >::update(), ROL::ProjectedSecantStep< Real >::update(), ROL::BundleStep< Real >::update(), ROL::GradientStep< Real >::update(), ROL::NewtonStep< Real >::update(), ROL::NonlinearCGStep< Real >::update(), ROL::PrimalDualActiveSetStep< Real >::update(), ROL::SecantStep< Real >::update(), ROL::TrustRegion< Real >::update(), ROL::CompositeStep< Real >::update(), ROL::InteriorPointStep< Real >::update(), ROL::AugmentedLagrangianStep< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::SemismoothNewtonProjection< Real >::update_primal(), ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius(), ROL::ElasticLinearConstraint< Real >::value(), and ROL::LinearConstraint< Real >::value().
scale()
template<class Real > virtual void ROL::Vector< Real >::scale (const Real alpha) pure virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::SimulatedVector< Real >, ROL::ElementwiseVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::SingletonVector< Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Referenced by ROL::DyadicOperator< Real >::apply(), ROL::SemismoothNewtonProjection< Real >::Precond::apply(), ROL::BinaryConstraint< Real >::applyAdjointHessian(), ROL::ConstraintFromObjective< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::ConstraintFromObjective< Real >::applyAdjointJacobian(), ROL::ScalarLinearConstraint< Real >::applyAdjointJacobian(), ROL::UpperBoundToConstraint< Real >::applyAdjointJacobian(), ROL::CompositeConstraint_SimOpt< Real >::applyAdjointSens(), ROL::lDFP< Real >::applyB0(), ROL::lSR1< Real >::applyB0(), ROL::Secant< Real >::applyB0(), ROL::lDFP< Real >::applyH0(), ROL::lSR1< Real >::applyH0(), ROL::Secant< Real >::applyH0(), ROL::SemismoothNewtonProjection< Real >::Precond::applyInverse(), ROL::Constraint< Real >::applyJacobian(), ROL::BinaryConstraint< Real >::applyJacobian(), ROL::UpperBoundToConstraint< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::CompositeConstraint_SimOpt< Real >::applySens(), ROL::GradientStep< Real >::compute(), ROL::LineSearchStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::compute(), ROL::NewtonStep< Real >::compute(), ROL::NonlinearCGStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonStep< Real >::compute(), ROL::ProjectedSecantStep< Real >::compute(), ROL::SecantStep< Real >::compute(), ROL::BundleStep< Real >::compute(), ROL::Gradient_U< Real >::compute(), ROL::Newton_U< Real >::compute(), ROL::NewtonKrylov_U< Real >::compute(), ROL::NonlinearCG_U< Real >::compute(), ROL::QuasiNewton_U< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::computeGradient(), ROL::ReducedDynamicObjective< Real >::computeNewStateJacobian(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), ROL::LinMore< Real >::dcauchy(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dproj(), ROL::TypeP::TrustRegionAlgorithm< Real >::dprox(), ROL::TypeB::LSecantBAlgorithm< Real >::dsrch(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::PD_HMCR2< Real >::getGradient(), ROL::BPOE< Real >::getGradient(), ROL::CoherentEntropicRisk< Real >::getGradient(), ROL::EntropicRisk< Real >::getGradient(), ROL::HMCR< Real >::getGradient(), ROL::KLDivergence< Real >::getGradient(), ROL::MeanVariance< Real >::getGradient(), ROL::PD_HMCR2< Real >::getHessVec(), ROL::BPOE< Real >::getHessVec(), ROL::CoherentEntropicRisk< Real >::getHessVec(), ROL::EntropicRisk< Real >::getHessVec(), ROL::HMCR< Real >::getHessVec(), ROL::KLDivergence< Real >::getHessVec(), ROL::MeanVariance< Real >::getHessVec(), ROL::ConicApproximationModel< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::PH_ErrorObjective< Real >::gradient(), ROL::PH_ProbObjective< Real >::gradient(), ROL::PH_RegretObjective< Real >::gradient(), ROL::AugmentedLagrangian< Real >::gradient(), ROL::LogBarrierObjective< Real >::gradient(), ROL::ZOO::Objective_SumOfSquares< Real >::gradient(), ROL::ZOO::Objective_Zakharov< Real >::gradient(), ROL::ScaledObjective< Real >::gradient(), ROL::AugmentedLagrangian_SimOpt< Real >::gradient_1(), ROL::AugmentedLagrangian_SimOpt< Real >::gradient_2(), ROL::DynamicTrackingFEMObjective< Real >::gradient_un(), ROL::DynamicTrackingObjective< Real >::gradient_un(), ROL::DynamicTrackingObjective< Real >::gradient_uo(), ROL::DynamicTrackingFEMObjective< Real >::gradient_z(), ROL::DynamicTrackingObjective< Real >::gradient_z(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::Objective< Real >::hessVec(), ROL::PH_ErrorObjective< Real >::hessVec(), ROL::PH_ProbObjective< Real >::hessVec(), ROL::PH_RegretObjective< Real >::hessVec(), ROL::AugmentedLagrangian< Real >::hessVec(), ROL::QuadraticPenalty< Real >::hessVec(), ROL::Fletcher< Real >::hessVec(), ROL::ZOO::Objective_HS24< Real >::hessVec(), ROL::FletcherObjectiveE< Real >::hessVec(), ROL::ScaledObjective< Real >::hessVec(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_11(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_11(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_12(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_12(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_21(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_21(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::AugmentedLagrangian_SimOpt< Real >::hessVec_22(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_22(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_un_un(), ROL::DynamicTrackingObjective< Real >::hessVec_un_un(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_uo_uo(), ROL::DynamicTrackingObjective< Real >::hessVec_uo_uo(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_z_z(), ROL::DynamicTrackingObjective< Real >::hessVec_z_z(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ZOO::Objective_SumOfSquares< Real >::invHessVec(), ROL::ScaledObjective< Real >::invHessVec(), ROL::ZOO::Objective_Zakharov< Real >::invHessVec(), ROL::ConicApproximationModel< Real >::precond(), ROL::ScaledObjective< Real >::precond(), ROL::ColemanLiModel< Real >::primalTransform(), ROL::DouglasRachfordProjection< Real >::project_con(), ROL::DykstraProjection< Real >::project_con(), ROL::l1Objective< Real >::prox(), ROL::Objective< Real >::proxJacVec(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), ROL::DogLeg< Real >::run(), ROL::DoubleDogLeg< Real >::run(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run(), ROL::CauchyPoint_U< Real >::solve(), ROL::DogLeg_U< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::SPGTrustRegion_U< Real >::solve(), Normalization_Constraint< Real >::solveAugmentedSystem(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::BinaryConstraint< Real >::value(), and ROL::Vector< Real >::zero().
dot()
template<class Real > virtual Real ROL::Vector< Real >::dot (const Vector< Real > & x) const pure virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::SingletonVector< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::PrimalAtomVector< Real >, ROL::DualAtomVector< Real >, ROL::BatchStdVector< Real >, ROL::PrimalProbabilityVector< Real >, ROL::DualProbabilityVector< Real >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::PrimalSimulatedVector< Real >, ROL::DualSimulatedVector< Real >, ROL::ElementwiseVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::PrimalScaledStdVector< Real, Element >, ROL::DualScaledStdVector< Real, Element >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::Sketch< Real >::advance(), ROL::Vector< Real >::apply(), ROL::DyadicOperator< Real >::apply(), ROL::NullSpaceOperator< Real >::apply(), ROL::Vector< Real >::checkVector(), ROL::BundleStep< Real >::compute(), ROL::LinMore< Real >::dcauchy(), ROL::TypeB::LinMoreAlgorithm< Real >::dcauchy(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dcauchy(), ROL::TypeB::LSecantBAlgorithm< Real >::dcauchy(), ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy(), ROL::ZOO::Objective_Zakharov< Real >::dirDeriv(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::Bundle_U< Real >::dotGi(), ROL::Bundle< Real >::dotGi(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::LinMore< Real >::dprsrch(), ROL::TypeB::LinMoreAlgorithm< Real >::dprsrch(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::LineSearchStep< Real >::GradDotStep(), ROL::Objective< Real >::gradient(), ROL::ZOO::Objective_Zakharov< Real >::gradient(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::TRUtils::initialRadius(), ROL::ZOO::Objective_Zakharov< Real >::invHessVec(), ROL::SemismoothNewtonProjection< Real >::project_ssn(), ROL::DoubleDogLeg< Real >::run(), ROL::LinMore< Real >::run(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), ROL::LineSearch< Real >::status(), ROL::TrustRegion< Real >::update(), ROL::DynamicTrackingFEMObjective< Real >::value(), ROL::DynamicTrackingObjective< Real >::value(), ROL::Objective_FSsolver< Real >::value(), ROL::PH_Objective< Real >::value(), ROL::ZOO::Objective_SumOfSquares< Real >::value(), ROL::ZOO::Objective_Zakharov< Real >::value(), and ROL::LinearObjective< Real >::value().
norm()
template<class Real > virtual Real ROL::Vector< Real >::norm () const pure virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::SROMVector< Real >, ROL::SimulatedVector< Real >, ROL::ElementwiseVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::SingletonVector< Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, ROL::Vector_SimOpt< Real >, and ROL::RiskVector< Real >.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::Sketch< Real >::advance(), ROL::Constraint< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1(), ROL::Constraint_TimeSimOpt< Real >::checkInverseAdjointJacobian_1_new(), ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1(), ROL::Constraint_TimeSimOpt< Real >::checkInverseJacobian_1_new(), ROL::PrimalDualActiveSetStep< Real >::compute(), ROL::Gradient_U< Real >::compute(), ROL::Newton_U< Real >::compute(), ROL::NewtonKrylov_U< Real >::compute(), ROL::NonlinearCG_U< Real >::compute(), ROL::QuasiNewton_U< Real >::compute(), ROL::TrustRegionStep< Real >::computeCriticalityMeasure(), ROL::TypeP::TrustRegionAlgorithm< Real >::computeGradient(), ROL::AugmentedLagrangianStep< Real >::computeGradient(), ROL::FletcherObjectiveBase< Real >::computeMultipliers(), ROL::FletcherStep< Real >::computeProjGradientNorm(), ROL::LinMore< Real >::dbreakpt(), ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy(), ROL::TypeB::ColemanLiAlgorithm< Real >::dgpstep(), ROL::TypeB::LinMoreAlgorithm< Real >::dgpstep(), ROL::TypeB::LSecantBAlgorithm< Real >::dgpstep(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dgpstep(), ROL::LinMore< Real >::dgpstep(), ROL::LineSearch_U< Real >::dirDeriv(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dproj(), ROL::TypeP::TrustRegionAlgorithm< Real >::dprox(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TypeB::LSecantBAlgorithm< Real >::dsrch(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::ColemanLiModel< Real >::getScalarBounds(), ROL::InteriorPoint::PenalizedObjective< Real >::gradient(), ROL::Objective< Real >::hessVec(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::TypeU::TrustRegionAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeP::InexactNewtonAlgorithm< Real >::initialize(), ROL::TypeB::Algorithm< Real >::optimalityCriterion(), ROL::DouglasRachfordProjection< Real >::project_DouglasRachford(), ROL::DykstraProjection< Real >::project_Dykstra(), ROL::Objective< Real >::proxJacVec(), ROL::Sketch< Real >::reconstruct(), ROL::SemismoothNewtonProjection< Real >::residual(), ROL::DogLeg< Real >::run(), ROL::DoubleDogLeg< Real >::run(), ROL::LinMore< Real >::run(), ROL::TruncatedCG< Real >::run(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::BiCGSTAB< Real >::run(), ROL::ConjugateGradients< Real >::run(), ROL::ConjugateResiduals< Real >::run(), Constraint_BurgersControl< Real >::solve(), ROL::DynamicConstraint< Real >::solve(), ROL::Constraint_SimOpt< Real >::solve(), ROL::CauchyPoint_U< Real >::solve(), ROL::DogLeg_U< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::SPGTrustRegion_U< Real >::solve(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::InteriorPointStep< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::NewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonStep< Real >::update(), ROL::ProjectedSecantStep< Real >::update(), ROL::GradientStep< Real >::update(), ROL::NewtonStep< Real >::update(), ROL::NonlinearCGStep< Real >::update(), ROL::PrimalDualActiveSetStep< Real >::update(), ROL::SecantStep< Real >::update(), ROL::InteriorPointStep< Real >::update(), ROL::AugmentedLagrangianStep< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::TypeG::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateState(), ROL::TypeB::InteriorPointAlgorithm< Real >::updateState(), and ROL::TypeB::MoreauYosidaAlgorithm< Real >::updateState().
clone()
template<class Real > virtual ROL::Ptr< Vector > ROL::Vector< Real >::clone () const pure virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::PrimalScaledStdVector< Real, Element >, ROL::DualScaledStdVector< Real, Element >, ROL::SingletonVector< Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, ROL::Vector_SimOpt< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, ROL::PrimalAtomVector< Real >, ROL::DualAtomVector< Real >, ROL::BatchStdVector< Real >, ROL::ProbabilityVector< Real >, ROL::PrimalProbabilityVector< Real >, ROL::DualProbabilityVector< Real >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::PrimalSimulatedVector< Real >, and ROL::DualSimulatedVector< Real >.
Referenced by ROL::AffineTransformConstraint< Real >::AffineTransformConstraint(), ROL::AffineTransformObjective< Real >::AffineTransformObjective(), ROL::VectorController< Real, Key >::allocate(), ROL::Constraint< Real >::applyAdjointHessian(), ROL::AlmostSureConstraint< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::AlmostSureConstraint< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::lBFGS< Real >::applyB(), ROL::lDFP< Real >::applyB(), ROL::lBFGS< Real >::applyH(), ROL::lDFP< Real >::applyH(), ROL::Constraint< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::applyJacobian(), ROL::ConstraintFromObjective< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Constraint_DynamicState< Real >::applyPreconditioner(), ROL::SimConstraint< Real >::applyPreconditioner(), ROL::AugmentedLagrangian< Real >::AugmentedLagrangian(), ROL::AugmentedLagrangian< Real >::AugmentedLagrangian(), ROL::AugmentedLagrangian_SimOpt< Real >::AugmentedLagrangian_SimOpt(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::Vector< Real >::axpy(), ROL::BoundConstraint< Real >::BoundConstraint(), ROL::BoundFletcher< Real >::BoundFletcher(), ROL::Bounds< Real >::Bounds(), ROL::BoundToConstraint< Real >::BoundToConstraint(), ROL::DynamicConstraintCheck< Real >::check(), ROL::DynamicObjectiveCheck< Real >::check(), ROL::Constraint< Real >::checkAdjointConsistencyJacobian(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), ROL::Constraint< Real >::checkApplyAdjointHessian(), ROL::Constraint< RealT >::checkApplyAdjointHessian(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::checkApplyAdjointHessian_22(), ROL::Constraint< Real >::checkApplyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::checkApplyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkApplyJacobian_2(), ROL::Objective< Real >::checkGradient(), ROL::Objective_SimOpt< Real >::checkGradient_1(), ROL::Objective_SimOpt< Real >::checkGradient_2(), ROL::Objective< Real >::checkHessSym(), ROL::Objective< Real >::checkHessVec(), ROL::Objective_SimOpt< Real >::checkHessVec_11(), ROL::Objective_SimOpt< Real >::checkHessVec_12(), ROL::Objective_SimOpt< Real >::checkHessVec_21(), ROL::Objective_SimOpt< Real >::checkHessVec_22(), ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1(), ROL::Objective< Real >::checkProxJacVec(), ROL::Constraint_SimOpt< Real >::checkSolve(), ROL::Vector< Real >::checkVector(), ROL::details::VectorWorkspace< Real >::VectorStack::clone(), ROL::CompositeConstraint_SimOpt< Real >::CompositeConstraint_SimOpt(), ROL::computeDenseHessian(), ROL::computeDotMatrix(), ROL::BoundConstraint< Real >::computeProjectedGradient(), ROL::computeScaledDenseHessian(), ROL::PartitionedVector< Real >::create(), createDiagonalQuadraticObjective(), ROL::Objective< Real >::dirDeriv(), ROL::LogBarrierObjective< Real >::dirDeriv(), ROL::ElementwiseVector< Real >::dot(), ROL::DouglasRachfordProjection< Real >::DouglasRachfordProjection(), ROL::DykstraProjection< Real >::DykstraProjection(), ROL::ElasticObjective< Real >::ElasticObjective(), ROL::ElasticObjective< Real >::ElasticObjective(), ROL::Fletcher< Real >::Fletcher(), ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase(), ROL::FletcherObjectiveE< Real >::FletcherObjectiveE(), ROL::SampledVector< Real, Key >::get(), ROL::VectorController< Real, Key >::get(), ROL::PH_bPOEObjective< Real >::getGradient(), ROL::PH_DeviationObjective< Real >::getGradient(), ROL::PH_ErrorObjective< Real >::getGradient(), ROL::PH_ProbObjective< Real >::getGradient(), ROL::PH_RegretObjective< Real >::getGradient(), ROL::PH_RiskObjective< Real >::getGradient(), Objective_GrossPitaevskii< Real >::gradient(), ROL::Objective< Real >::gradient(), ROL::LinearCombinationObjective< Real >::gradient(), ROL::LinearCombinationObjective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::LinearCombinationObjective_SimOpt< Real >::gradient_2(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Objective< Real >::hessVec(), ROL::LinearCombinationObjective< Real >::hessVec(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_11(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_12(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_21(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_22(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::RiskNeutralConstraint< Real >::init(), ROL::MoreauYosidaPenalty< Real >::initialize(), ROL::IterationScaling< Real >::initialize(), ROL::Bundle_U< Real >::initialize(), ROL::Bundle_U_AS< Real >::initialize(), ROL::Bundle< Real >::initialize(), ROL::Bundle_AS< Real >::initialize(), ROL::TrustRegionModel< Real >::initialize(), ROL::CompositeObjective_SimOpt< Real >::initialize(), ROL::CompositeObjective< Real >::initialize(), ROL::TypeBIndicatorObjective< Real >::initialize(), ROL::BPOE< Real >::initialize(), ROL::HMCR< Real >::initialize(), ROL::KLDivergence< Real >::initialize(), ROL::MeanDeviationFromTarget< Real >::initialize(), ROL::RandVarFunctional< Real >::initialize(), ROL::TypeB::Algorithm< Real >::initialize(), ROL::InteriorPointObjective< Real >::initialize(), ROL::MoreauYosidaObjective< Real >::initialize(), ROL::TypeP::Algorithm< Real >::initialize(), ROL::LineSearch_U< Real >::initialize(), ROL::TypeU::Algorithm< Real >::initialize(), ROL::CauchyPoint_U< Real >::initialize(), ROL::DogLeg_U< Real >::initialize(), ROL::DoubleDogLeg_U< Real >::initialize(), ROL::SPGTrustRegion_U< Real >::initialize(), ROL::TruncatedCG_U< Real >::initialize(), ROL::TrustRegionModel_U< Real >::initialize(), ROL::ColemanLiModel< Real >::initialize(), ROL::BackTracking_U< Real >::initialize(), ROL::CubicInterp_U< Real >::initialize(), ROL::IterationScaling_U< Real >::initialize(), ROL::PathBasedTargetLevel_U< Real >::initialize(), ROL::ScalarMinimizationLineSearch_U< Real >::initialize(), ROL::TypeE::Algorithm< Real >::initialize(), ROL::TypeG::Algorithm< Real >::initialize(), ROL::DogLeg< Real >::initialize(), ROL::DoubleDogLeg< Real >::initialize(), ROL::LinMore< Real >::initialize(), ROL::TruncatedCG< Real >::initialize(), ROL::TrustRegion< Real >::initialize(), ROL::BackTracking< Real >::initialize(), ROL::Bisection< Real >::initialize(), ROL::Brents< Real >::initialize(), ROL::CubicInterp< Real >::initialize(), ROL::GoldenSection< Real >::initialize(), ROL::LineSearch< Real >::initialize(), ROL::PathBasedTargetLevel< Real >::initialize(), ROL::ScalarMinimizationLineSearch< Real >::initialize(), ROL::BrentsProjection< Real >::initialize(), ROL::DaiFletcherProjection< Real >::initialize(), ROL::RiddersProjection< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::BundleStep< Real >::initialize(), ROL::CompositeStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::FletcherStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::TypeE::CompositeStepAlgorithm< Real >::initialize(), ROL::LineSearchStep< Real >::initialize(), ROL::NewtonKrylovStep< Real >::initialize(), ROL::ProjectedNewtonKrylovStep< Real >::initialize(), ROL::ProjectedNewtonStep< Real >::initialize(), ROL::ProjectedSecantStep< Real >::initialize(), ROL::TrustRegionStep< Real >::initialize(), ROL::PrimalDualActiveSetStep< Real >::initialize(), ROL::SecantStep< Real >::initialize(), ROL::Step< Real >::initialize(), ROL::TRUtils::initialRadius(), ROL::BoundConstraint< Real >::isFeasible(), ROL::KelleySachsModel< Real >::KelleySachsModel(), ROL::LinMoreModel< Real >::LinMoreModel(), ROL::LowerBoundToConstraint< Real >::LowerBoundToConstraint(), ROL::NonlinearLeastSquaresObjective< Real >::NonlinearLeastSquaresObjective(), ROL::NonlinearLeastSquaresObjective_Dynamic< Real >::NonlinearLeastSquaresObjective_Dynamic(), ROL::normL1(), ROL::normLinf(), ROL::normLp(), ROL::NullSpaceOperator< Real >::NullSpaceOperator(), ROL::ObjectiveMMA< Real >::ObjectiveMMA(), ROL::details::VectorClone< Real >::operator()(), ROL::InteriorPoint::PenalizedObjective< Real >::PenalizedObjective(), ROL::PH_StatusTest< Real >::PH_StatusTest(), ROL::PolyhedralProjection< Real >::PolyhedralProjection(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::PrimalDualSymmetrizer(), ROL::Objective< Real >::proxJacVec(), ROL::BoundConstraint< Real >::pruneInactive(), ROL::BoundConstraint< Real >::pruneInactive(), ROL::BoundConstraint< Real >::pruneLowerInactive(), ROL::BoundConstraint< Real >::pruneLowerInactive(), ROL::BoundConstraint< Real >::pruneUpperInactive(), ROL::BoundConstraint< Real >::pruneUpperInactive(), ROL::QuadraticPenalty< Real >::QuadraticPenalty(), ROL::QuadraticPenalty_SimOpt< Real >::QuadraticPenalty_SimOpt(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), ROL::ProjectedObjective< Real >::reducedPrecond(), ROL::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::InteriorPointAlgorithm< Real >::run(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::GradientAlgorithm< Real >::run(), ROL::TypeB::InteriorPointAlgorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::LinMoreAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::TypeB::MoreauYosidaAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeB::SpectralGradientAlgorithm< Real >::run(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeE::Algorithm< Real >::run(), ROL::TypeE::CompositeStepAlgorithm< Real >::run(), ROL::TypeE::FletcherAlgorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeG::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeU::BundleAlgorithm< Real >::run(), ROL::TypeU::LineSearchAlgorithm< Real >::run(), ROL::TypeU::TrustRegionAlgorithm< Real >::run(), ROL::TypeP::InexactNewtonAlgorithm< Real >::run(), ROL::TypeP::iPianoAlgorithm< Real >::run(), ROL::TypeP::ProxGradientAlgorithm< Real >::run(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeP::SpectralGradientAlgorithm< Real >::run(), ROL::TypeP::TrustRegionAlgorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::BiCGSTAB< Real >::run(), ROL::ConjugateGradients< Real >::run(), ROL::ConjugateResiduals< Real >::run(), ROL::GMRES< Real >::run(), ROL::SemismoothNewtonProjection< Real >::SemismoothNewtonProjection(), ROL::SemismoothNewtonProjection< Real >::SemismoothNewtonProjection(), ROL::SampledVector< Real, Key >::set(), ROL::VectorController< Real, Key >::set(), ROL::Sketch< Real >::Sketch(), ROL::DynamicConstraint< Real >::solve(), ROL::Constraint_SimOpt< Real >::solve(), ROL::Constraint< RealT >::solveAugmentedSystem(), Objective_PoissonInversion< Real >::update(), ROL::lSR1< Real >::updateStorage(), ROL::Secant< Real >::updateStorage(), ROL::UpperBoundToConstraint< Real >::UpperBoundToConstraint(), ROL::TrustRegionModel_U< Real >::validate(), CLExactModel< Real >::value(), Objective_GrossPitaevskii< Real >::value(), and ROL::LogBarrierObjective< Real >::value().
axpy()
template<class Real > virtual void ROL::Vector< Real >::axpy (const Real alpha, const Vector< Real > & x) inline virtual
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of @b x.
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = \mathtt{*this} + \alpha x \f$.
   Uses #clone, #set, #scale and #plus for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented in ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::SingletonVector< Real >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::ElementwiseVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Definition at line 119 of file ROL_Vector.hpp.
References ROL::Vector< Real >::clone(), and ROL::Vector< Real >::plus().
Referenced by ROL::Bundle_U< Real >::addGi(), ROL::Bundle< Real >::addGi(), ROL::ReducedDynamicObjective< Real >::addMixedHessLag(), ROL::BlockOperator2Determinant< Real >::apply(), ROL::HouseholderReflector< Real >::apply(), ROL::NullSpaceOperator< Real >::apply(), ROL::SemismoothNewtonProjection< Real >::Jacobian::apply(), ROL::BinaryConstraint< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_11(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_12(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_21(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::CompositeConstraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::lBFGS< Real >::applyB(), ROL::lDFP< Real >::applyB(), ROL::lSR1< Real >::applyB(), ROL::lBFGS< Real >::applyH(), ROL::lDFP< Real >::applyH(), ROL::lSR1< Real >::applyH(), ROL::Constraint< Real >::applyJacobian(), ROL::ElasticLinearConstraint< Real >::applyJacobian(), ROL::BinaryConstraint< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::applyJacobian_1(), ROL::Constraint_TimeSimOpt< Real >::applyJacobian_1(), ROL::Constraint_SimOpt< Real >::applyJacobian_2(), ROL::Bounds< Real >::applyScalingFunctionJacobian(), ROL::Bounds< Real >::buildScalingFunction(), calcError(), ROL::InteriorPointStep< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), ROL::LineSearchStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::ReducedDynamicObjective< Real >::computeAdjointRHS(), ROL::ReducedDynamicObjective< Real >::computeControlHessLag(), ROL::ReducedDynamicObjective< Real >::computeNewMixedHessLag(), ROL::ReducedDynamicObjective< Real >::computeNewStateHessLag(), ROL::ReducedDynamicObjective< Real >::computeNewStateJacobian(), ROL::ReducedDynamicObjective< Real >::computeOldMixedHessLag(), ROL::ReducedDynamicObjective< Real >::computeOldStateHessLag(), ROL::BoundConstraint< Real >::computeProjectedStep(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), ROL::TypeP::TrustRegionAlgorithm< Real >::dbls(), ROL::LinMore< Real >::dbreakpt(), ROL::TypeB::ColemanLiAlgorithm< Real >::dgpstep(), ROL::TypeB::LinMoreAlgorithm< Real >::dgpstep(), ROL::TypeB::LSecantBAlgorithm< Real >::dgpstep(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dgpstep(), ROL::LinMore< Real >::dgpstep(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dproj(), ROL::TypeP::TrustRegionAlgorithm< Real >::dprox(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TypeB::LSecantBAlgorithm< Real >::dsrch(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::ConvexCombinationRiskMeasure< Real >::getGradient(), ROL::HMCR< Real >::getGradient(), ROL::MeanDeviationFromTarget< Real >::getGradient(), ROL::PD_HMCR2< Real >::getHessVec(), ROL::BPOE< Real >::getHessVec(), ROL::CoherentEntropicRisk< Real >::getHessVec(), ROL::ConvexCombinationRiskMeasure< Real >::getHessVec(), ROL::EntropicRisk< Real >::getHessVec(), ROL::HMCR< Real >::getHessVec(), ROL::KLDivergence< Real >::getHessVec(), ROL::MeanDeviationFromTarget< Real >::getHessVec(), ROL::MeanVariance< Real >::getHessVec(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::InteriorPointObjective< Real >::gradient(), ROL::MoreauYosidaObjective< Real >::gradient(), ROL::l1Objective< Real >::gradient(), ROL::Objective< Real >::gradient(), ROL::InteriorPointPenalty< Real >::gradient(), ROL::MoreauYosidaPenalty< Real >::gradient(), ROL::ZOO::Objective_Zakharov< Real >::gradient(), ROL::FletcherObjectiveE< Real >::gradient(), ROL::ReducedDynamicStationaryControlsObjective< Real >::gradient(), ROL::CompositeObjective< Real >::gradient(), ROL::LinearCombinationObjective< Real >::gradient(), ROL::CompositeObjective_SimOpt< Real >::gradient_1(), ROL::LinearCombinationObjective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::CompositeObjective_SimOpt< Real >::gradient_2(), ROL::LinearCombinationObjective_SimOpt< Real >::gradient_2(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::DynamicTrackingFEMObjective< Real >::gradient_un(), ROL::DynamicTrackingObjective< Real >::gradient_un(), ROL::DynamicTrackingObjective< Real >::gradient_uo(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::InteriorPointObjective< Real >::hessVec(), ROL::MoreauYosidaObjective< Real >::hessVec(), ROL::Objective< Real >::hessVec(), ROL::PH_ErrorObjective< Real >::hessVec(), ROL::PH_Objective< Real >::hessVec(), ROL::PH_ProbObjective< Real >::hessVec(), ROL::PH_RegretObjective< Real >::hessVec(), ROL::BoundFletcher< Real >::hessVec(), ROL::Fletcher< Real >::hessVec(), ROL::InteriorPointPenalty< Real >::hessVec(), ROL::MoreauYosidaPenalty< Real >::hessVec(), ROL::FletcherObjectiveE< Real >::hessVec(), ROL::ReducedDynamicStationaryControlsObjective< Real >::hessVec(), ROL::CompositeObjective< Real >::hessVec(), ROL::LinearCombinationObjective< Real >::hessVec(), ROL::CompositeObjective_SimOpt< Real >::hessVec_11(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_11(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::CompositeObjective_SimOpt< Real >::hessVec_12(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_12(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::CompositeObjective_SimOpt< Real >::hessVec_21(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_21(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::CompositeObjective_SimOpt< Real >::hessVec_22(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_22(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_uo_uo(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ZOO::Objective_Zakharov< Real >::invHessVec(), ROL::TypeB::Algorithm< Real >::optimalityCriterion(), ROL::TypeP::Algorithm< Real >::pgstep(), ROL::ConicApproximationModel< Real >::precond(), ROL::KelleySachsModel< Real >::primalTransform(), ROL::DouglasRachfordProjection< Real >::project_con(), ROL::DykstraProjection< Real >::project_con(), ROL::SemismoothNewtonProjection< Real >::project_ssn(), ROL::BallIndicatorObjective< Real >::prox(), ROL::l1Objective< Real >::prox(), ROL::ShiftedProxObjective< Real >::prox(), ROL::Objective< Real >::proxJacVec(), ROL::BoundConstraint< Real >::pruneInactive(), ROL::BoundConstraint< Real >::pruneInactive(), ROL::BoundConstraint< Real >::pruneLowerInactive(), ROL::BoundConstraint< Real >::pruneLowerInactive(), ROL::BoundConstraint< Real >::pruneUpperInactive(), ROL::BoundConstraint< Real >::pruneUpperInactive(), ROL::RandomizeFeasibleVector(), ROL::Sketch< Real >::reconstruct(), ROL::details::MINRES< Real >::run(), ROL::DogLeg< Real >::run(), ROL::DoubleDogLeg< Real >::run(), ROL::LinMore< Real >::run(), ROL::TruncatedCG< Real >::run(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeP::InexactNewtonAlgorithm< Real >::run(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::run(), ROL::BiCGSTAB< Real >::run(), ROL::ConjugateGradients< Real >::run(), ROL::ConjugateResiduals< Real >::run(), ROL::DogLeg_U< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::SPGTrustRegion_U< Real >::solve(), ROL::TruncatedCG_U< Real >::solve(), ROL::ScalarLinearConstraint< Real >::solveAugmentedSystem(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::AugmentedLagrangianStep< Real >::update(), ROL::BrentsProjection< Real >::update_primal(), ROL::DaiFletcherProjection< Real >::update_primal(), ROL::RiddersProjection< Real >::update_primal(), ROL::ReducedDynamicObjective< Real >::updateGradient(), ROL::LineSearch< Real >::updateIterate(), ROL::TypeG::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateState(), ROL::TypeB::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeB::MoreauYosidaAlgorithm< Real >::updateState(), ROL::ElasticLinearConstraint< Real >::value(), ROL::BinaryConstraint< Real >::value(), ROL::LowerBoundToConstraint< Real >::value(), and ROL::UpperBoundToConstraint< Real >::value().
zero()
template<class Real > virtual void ROL::Vector< Real >::zero () inline virtual
Set to zero vector.
   Uses #scale by zero for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented in ROL::SimulatedVector< Real >, ROL::ElementwiseVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, and ROL::StdArray< Real, array_size, pool_size >.
Definition at line 133 of file ROL_Vector.hpp.
References ROL::Vector< Real >::scale().
Referenced by ROL::Bundle_U< Real >::aggregate(), ROL::Bundle< Real >::aggregate(), ROL::NullOperator< Real >::apply(), ROL::Constraint< Real >::applyAdjointHessian(), ROL::AlmostSureConstraint< Real >::applyAdjointHessian(), ROL::RiskNeutralConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::ZOO::Constraint_HS24< Real >::applyAdjointHessian(), ROL::ZOO::EqualityConstraint_HS32< Real >::applyAdjointHessian(), ROL::ElasticLinearConstraint< Real >::applyAdjointHessian(), ROL::BoundToConstraint< Real >::applyAdjointHessian(), ROL::LinearConstraint< Real >::applyAdjointHessian(), ROL::LowerBoundToConstraint< Real >::applyAdjointHessian(), ROL::ReducedLinearConstraint< Real >::applyAdjointHessian(), ROL::ScalarLinearConstraint< Real >::applyAdjointHessian(), ROL::UpperBoundToConstraint< Real >::applyAdjointHessian(), Constraint_BurgersControl< Real >::applyAdjointHessian_11(), DiffusionConstraint< Real >::applyAdjointHessian_11(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointHessian_11(), Constraint_BurgersControl< Real >::applyAdjointHessian_12(), DiffusionConstraint< Real >::applyAdjointHessian_12(), ROL::Constraint_TimeSimOpt< Real >::applyAdjointHessian_12(), Constraint_BurgersControl< Real >::applyAdjointHessian_21(), DiffusionConstraint< Real >::applyAdjointHessian_21(), ROL::Constraint_TimeSimOpt< Real >::applyAdjointHessian_21(), Constraint_BurgersControl< Real >::applyAdjointHessian_22(), DiffusionConstraint< Real >::applyAdjointHessian_22(), ROL::CompositeConstraint_SimOpt< Real >::applyAdjointHessian_22(), ROL::Constraint_TimeSimOpt< Real >::applyAdjointHessian_22(), ROL::DynamicConstraint< Real >::applyAdjointHessian_un_un(), ROL::DynamicConstraint< Real >::applyAdjointHessian_un_uo(), ROL::DynamicConstraint< Real >::applyAdjointHessian_un_z(), ROL::DynamicConstraint< Real >::applyAdjointHessian_uo_un(), ROL::DynamicConstraint< Real >::applyAdjointHessian_uo_uo(), ROL::DynamicConstraint< Real >::applyAdjointHessian_uo_z(), ROL::DynamicConstraint< Real >::applyAdjointHessian_z_un(), ROL::DynamicConstraint< Real >::applyAdjointHessian_z_uo(), ROL::DynamicConstraint< Real >::applyAdjointHessian_z_z(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::AlmostSureConstraint< Real >::applyAdjointJacobian(), ROL::RiskNeutralConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::InteriorPoint::PrimalDualResidual< Real >::applyJacobian(), ROL::Constraint< Real >::applyJacobian(), ROL::AlmostSureConstraint< Real >::applyJacobian(), ROL::RiskNeutralConstraint< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::AlmostSureConstraint< Real >::applyPreconditioner(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), ROL::Vector< Real >::checkVector(), ROL::BundleStep< Real >::compute(), ROL::PrimalDualActiveSetStep< Real >::compute(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::BPOE< Real >::getGradient(), NullObjective< Real >::gradient(), ROL::Objective< Real >::gradient(), ROL::PH_ProbObjective< Real >::gradient(), ROL::StochasticObjective< Real >::gradient(), ROL::RiskNeutralObjective< Real >::gradient(), ROL::SimulatedObjective< Real >::gradient(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), ROL::CDFObjective< Real >::gradient(), ROL::MomentObjective< Real >::gradient(), ROL::ZOO::Objective_BVP< Real >::gradient(), ROL::ZOO::Objective_HS25< Real >::gradient(), ROL::ReducedDynamicStationaryControlsObjective< Real >::gradient(), ROL::CompositeObjective< Real >::gradient(), ROL::LinearCombinationObjective< Real >::gradient(), ROL::ZeroProxObjective< Real >::gradient(), Objective_BurgersControl< Real >::gradient_1(), ROL::CompositeObjective_SimOpt< Real >::gradient_1(), ROL::LinearCombinationObjective_SimOpt< Real >::gradient_1(), ROL::LinearObjective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_1(), Objective_BurgersControl< Real >::gradient_2(), ROL::CompositeObjective_SimOpt< Real >::gradient_2(), ROL::LinearCombinationObjective_SimOpt< Real >::gradient_2(), ROL::LinearObjective_SimOpt< Real >::gradient_2(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::DynamicTrackingFEMObjective< Real >::gradient_uo(), ROL::DynamicTrackingObjective< Real >::gradient_uo(), NullObjective< Real >::hessVec(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::Objective< Real >::hessVec(), ROL::PH_ProbObjective< Real >::hessVec(), ROL::StochasticObjective< Real >::hessVec(), ROL::RiskNeutralObjective< Real >::hessVec(), ROL::SimulatedObjective< Real >::hessVec(), ROL::CDFObjective< Real >::hessVec(), ROL::MomentObjective< Real >::hessVec(), ROL::QuadraticPenalty< Real >::hessVec(), ROL::ZOO::Objective_HS39< Real >::hessVec(), ROL::ReducedDynamicStationaryControlsObjective< Real >::hessVec(), ROL::CompositeObjective< Real >::hessVec(), ROL::LinearCombinationObjective< Real >::hessVec(), ROL::LinearObjective< Real >::hessVec(), Objective_BurgersControl< Real >::hessVec_11(), ObjectiveFunctionTest08_2< Real >::hessVec_11(), ROL::CompositeObjective_SimOpt< Real >::hessVec_11(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_11(), ROL::LinearObjective_SimOpt< Real >::hessVec_11(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_11(), Objective_BurgersControl< Real >::hessVec_12(), DiffusionObjective< Real >::hessVec_12(), ObjectiveFunctionTest08_1< Real >::hessVec_12(), ObjectiveFunctionTest08_2< Real >::hessVec_12(), ROL::CompositeObjective_SimOpt< Real >::hessVec_12(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_12(), ROL::LinearObjective_SimOpt< Real >::hessVec_12(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_12(), ROL::hessVec_12(), Objective_BurgersControl< Real >::hessVec_21(), DiffusionObjective< Real >::hessVec_21(), ObjectiveFunctionTest08_1< Real >::hessVec_21(), ObjectiveFunctionTest08_2< Real >::hessVec_21(), ROL::CompositeObjective_SimOpt< Real >::hessVec_21(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_21(), ROL::LinearObjective_SimOpt< Real >::hessVec_21(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_21(), ROL::hessVec_21(), Objective_BurgersControl< Real >::hessVec_22(), ObjectiveFunctionTest08_2< Real >::hessVec_22(), ROL::CompositeObjective_SimOpt< Real >::hessVec_22(), ROL::LinearCombinationObjective_SimOpt< Real >::hessVec_22(), ROL::LinearObjective_SimOpt< Real >::hessVec_22(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_22(), ROL::hessVec_22(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_un_uo(), ROL::DynamicTrackingObjective< Real >::hessVec_un_uo(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_un_z(), ROL::DynamicTrackingObjective< Real >::hessVec_un_z(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_uo_un(), ROL::DynamicTrackingObjective< Real >::hessVec_uo_un(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_uo_uo(), ROL::DynamicTrackingObjective< Real >::hessVec_uo_uo(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_uo_z(), ROL::DynamicTrackingObjective< Real >::hessVec_uo_z(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_z_un(), ROL::DynamicTrackingObjective< Real >::hessVec_z_un(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_z_uo(), ROL::DynamicTrackingObjective< Real >::hessVec_z_uo(), main(), main(), ROL::Objective< Real >::proxJacVec(), ROL::Sketch< Real >::reconstruct(), ROL::TruncatedCG< Real >::run(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::run(), ROL::BiCGSTAB< Real >::run(), ROL::ConjugateGradients< Real >::run(), ROL::ConjugateResiduals< Real >::run(), ROL::GMRES< Real >::run(), ROL::Vector< Real >::set(), ROL::DynamicConstraint< Real >::solve(), ROL::Constraint_SimOpt< Real >::solve(), ROL::TruncatedCG_U< Real >::solve(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::InteriorPoint::PrimalDualResidual< Real >::value(), ROL::AlmostSureConstraint< Real >::value(), ROL::RiskNeutralConstraint< Real >::value(), and ROL::SimulatedConstraint< Real >::value().
basis()
template<class Real > virtual ROL::Ptr< Vector > ROL::Vector< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::RiskVector< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::SingletonVector< Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Definition at line 148 of file ROL_Vector.hpp.
References ROL_UNUSED.
Referenced by ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint< Real >::checkApplyAdjointJacobian(), ROL::computeDenseHessian(), ROL::computeDotMatrix(), ROL::Objective< Real >::gradient(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::initialize(), and Objective_PoissonInversion< Real >::update().
dimension()
template<class Real > virtual int ROL::Vector< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::SingletonVector< Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, ROL::Vector_SimOpt< Real >, ROL::BatchStdVector< Real >, ROL::SROMVector< Real >, and ROL::RiskVector< Real >.
Definition at line 162 of file ROL_Vector.hpp.
Referenced by constraint1< Real >::applyAdjointHessian_11(), constraint2< Real >::applyAdjointHessian_11(), constraint1< Real >::applyAdjointHessian_12(), constraint2< Real >::applyAdjointHessian_12(), constraint1< Real >::applyAdjointHessian_21(), constraint2< Real >::applyAdjointHessian_21(), constraint1< Real >::applyAdjointHessian_22(), constraint2< Real >::applyAdjointHessian_22(), ROL::Constraint< Real >::applyAdjointJacobian(), constraint2< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), constraint1< Real >::applyAdjointJacobian_2(), constraint2< Real >::applyAdjointJacobian_2(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::StdVector< Real, Element >::applyBinary(), constraint1< Real >::applyInverseJacobian_1(), constraint1< Real >::applyJacobian_1(), constraint2< Real >::applyJacobian_1(), constraint1< Real >::applyJacobian_2(), constraint2< Real >::applyJacobian_2(), ROL::StdVector< Real, Element >::axpy(), ROL::Constraint< Real >::checkApplyAdjointJacobian(), ROL::computeDenseHessian(), ROL::computeDotMatrix(), ROL::BoundConstraint< Real >::computeInf(), ROL::computeScaledDenseHessian(), ROL::StdVector< Real, Element >::dot(), ROL::DouglasRachfordProjection< Real >::DouglasRachfordProjection(), ROL::DykstraProjection< Real >::DykstraProjection(), ROL::Objective< Real >::gradient(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::BrentsProjection< Real >::initialize(), ROL::DaiFletcherProjection< Real >::initialize(), ROL::RiddersProjection< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::NullSpaceOperator< Real >::NullSpaceOperator(), ROL::details::VectorClone< Real >::operator()(), ROL::StdVector< Real, Element >::plus(), ROL::LinMore< Real >::run(), ROL::SemismoothNewtonProjection< Real >::SemismoothNewtonProjection(), ROL::SemismoothNewtonProjection< Real >::SemismoothNewtonProjection(), ROL::StdVector< Real, Element >::set(), ROL::Sketch< Real >::Sketch(), constraint1< Real >::solve(), constraint1< Real >::value(), and constraint2< Real >::value().
set()
template<class Real > virtual void ROL::Vector< Real >::set (const Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::SingletonVector< Real >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::ElementwiseVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::StdArray< Real, array_size, pool_size >, and ROL::StdVector< Real, Element >.
Definition at line 175 of file ROL_Vector.hpp.
References ROL::Vector< Real >::plus(), and ROL::Vector< Real >::zero().
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::Bundle_U< Real >::aggregate(), ROL::Bundle< Real >::aggregate(), IdentityOperator< Real >::apply(), ROL::DyadicOperator< Real >::apply(), Identity< Real >::apply(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::HessianPNK::apply(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::apply(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS::apply(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::apply(), ROL::FletcherObjectiveE< Real >::AugSystemPrecond::apply(), ROL::NewtonKrylov_U< Real >::PrecondNK::apply(), ROL::DiagonalOperator< Real >::apply(), ROL::HouseholderReflector< Real >::apply(), ROL::IdentityOperator< Real >::apply(), ROL::LinearOperatorProduct< Real >::apply(), ROL::NullSpaceOperator< Real >::apply(), ROL::SemismoothNewtonProjection< Real >::Precond::apply(), ROL::BoundFletcher< Real >::AugSystemPrecond::apply(), ROL::Fletcher< Real >::AugSystemPrecond::apply(), ROL::NewtonKrylovStep< Real >::PrecondNK::apply(), ROL::PrimalDualActiveSetStep< Real >::PrecondPD::apply(), ROL::ProjectedNewtonKrylovStep< Real >::PrecondPNK::apply(), ROL::BinaryConstraint< Real >::applyAdjointHessian(), ROL::LowerBoundToConstraint< Real >::applyAdjointJacobian(), ROL::ScalarLinearConstraint< Real >::applyAdjointJacobian(), ROL::UpperBoundToConstraint< Real >::applyAdjointJacobian(), ROL::lDFP< Real >::applyB(), ROL::lDFP< Real >::applyB0(), ROL::lSR1< Real >::applyB0(), ROL::Secant< Real >::applyB0(), ROL::ColemanLiModel< Real >::applyC(), ROL::ColemanLiModel< Real >::applyD(), ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LSecantBAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::LSecantBAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreePrecond(), ROL::lDFP< Real >::applyH0(), ROL::lSR1< Real >::applyH0(), ROL::Secant< Real >::applyH0(), TridiagonalToeplitzOperator< Real >::applyInverse(), ROL::DiagonalOperator< Real >::applyInverse(), ROL::IdentityOperator< Real >::applyInverse(), ROL::LinearOperator< Real >::applyInverse(), ROL::LinearOperatorFromConstraint< Real >::applyInverse(), ROL::LinearOperatorProduct< Real >::applyInverse(), ROL::SemismoothNewtonProjection< Real >::Precond::applyInverse(), ROL::ColemanLiModel< Real >::applyInverseD(), ROL::BinaryConstraint< Real >::applyJacobian(), ROL::LowerBoundToConstraint< Real >::applyJacobian(), ROL::UpperBoundToConstraint< Real >::applyJacobian(), ROL::Constraint< Real >::applyPreconditioner(), ROL::Constraint_SimOpt< Real >::applyPreconditioner(), ROL::Bounds< Real >::buildScalingFunction(), ROL::InteriorPointStep< Real >::compute(), ROL::AugmentedLagrangianStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::GradientStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), ROL::LineSearchStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::BundleStep< Real >::compute(), ROL::Gradient_U< Real >::compute(), ROL::Newton_U< Real >::compute(), ROL::NewtonKrylov_U< Real >::compute(), ROL::NonlinearCG_U< Real >::compute(), ROL::QuasiNewton_U< Real >::compute(), ROL::ColemanLiModel< Real >::computeFullReflectiveStep(), ROL::TypeP::TrustRegionAlgorithm< Real >::computeGradient(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), ROL::ColemanLiModel< Real >::computeReflectiveStep(), ROL::TypeP::TrustRegionAlgorithm< Real >::dbls(), ROL::LinMore< Real >::dbreakpt(), ROL::LinMore< Real >::dcauchy(), ROL::TypeB::LinMoreAlgorithm< Real >::dcauchy(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dcauchy(), ROL::TypeB::LSecantBAlgorithm< Real >::dcauchy(), ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy(), ROL::TypeB::ColemanLiAlgorithm< Real >::dgpstep(), ROL::TypeB::LinMoreAlgorithm< Real >::dgpstep(), ROL::TypeB::LSecantBAlgorithm< Real >::dgpstep(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dgpstep(), ROL::LinMore< Real >::dgpstep(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dproj(), ROL::TypeP::TrustRegionAlgorithm< Real >::dprox(), ROL::LinMore< Real >::dprsrch(), ROL::TypeB::LinMoreAlgorithm< Real >::dprsrch(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TypeB::LSecantBAlgorithm< Real >::dsrch(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::SimulatedVector< Real >::dual(), ROL::PartitionedVector< Real >::dual(), ROL::KelleySachsModel< Real >::dualTransform(), ROL::TrustRegionModel< Real >::dualTransform(), ROL::SampledVector< Real, Key >::get(), ROL::VectorController< Real, Key >::get(), ROL::QuadraticPenalty_SimOpt< Real >::getConstraintVec(), ROL::QuadraticPenalty< Real >::getConstraintVec(), ROL::InteriorPoint::PenalizedObjective< Real >::getObjectiveGradient(), ROL::ConicApproximationModel< Real >::gradient(), ROL::Objective_FSsolver< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::InteriorPointObjective< Real >::gradient(), ROL::TypeP::InexactNewtonAlgorithm< Real >::NewtonObj::gradient(), ROL::l1Objective< Real >::gradient(), ROL::ObjectiveMMA< Real >::gradient(), ROL::PH_ErrorObjective< Real >::gradient(), ROL::PH_ProbObjective< Real >::gradient(), ROL::PH_RegretObjective< Real >::gradient(), ROL::RiskNeutralObjective< Real >::gradient(), ROL::AugmentedLagrangian< Real >::gradient(), ROL::BoundFletcher< Real >::gradient(), ROL::Fletcher< Real >::gradient(), ROL::InteriorPointPenalty< Real >::gradient(), ROL::LogBarrierObjective< Real >::gradient(), ROL::MoreauYosidaPenalty< Real >::gradient(), ROL::ZOO::Objective_SumOfSquares< Real >::gradient(), ROL::ZOO::Objective_Zakharov< Real >::gradient(), ROL::LinearObjective< Real >::gradient(), ROL::LinearObjective_SimOpt< Real >::gradient_1(), ROL::AugmentedLagrangian_SimOpt< Real >::gradient_1(), ROL::LinearObjective_SimOpt< Real >::gradient_2(), ROL::AugmentedLagrangian_SimOpt< Real >::gradient_2(), ROL::DynamicTrackingFEMObjective< Real >::gradient_un(), ROL::DynamicTrackingObjective< Real >::gradient_un(), ROL::DynamicTrackingObjective< Real >::gradient_uo(), ROL::DynamicTrackingFEMObjective< Real >::gradient_z(), ROL::DynamicTrackingObjective< Real >::gradient_z(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::Objective_FSsolver< Real >::hessVec(), ROL::ObjectiveMMA< Real >::hessVec(), ROL::BoundFletcher< Real >::hessVec(), ROL::LogBarrierObjective< Real >::hessVec(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_un_un(), ROL::DynamicTrackingObjective< Real >::hessVec_un_un(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_uo_uo(), ROL::DynamicTrackingObjective< Real >::hessVec_uo_uo(), ROL::DynamicTrackingFEMObjective< Real >::hessVec_z_z(), ROL::DynamicTrackingObjective< Real >::hessVec_z_z(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeP::InexactNewtonAlgorithm< Real >::initialize(), ROL::TypeP::iPianoAlgorithm< Real >::initialize(), ROL::TypeP::ProxGradientAlgorithm< Real >::initialize(), ROL::TypeP::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeP::TrustRegionAlgorithm< Real >::initialize(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ZOO::Objective_SumOfSquares< Real >::invHessVec(), ROL::ZOO::Objective_Zakharov< Real >::invHessVec(), main(), ROL::TypeB::Algorithm< Real >::optimalityCriterion(), ROL::TypeP::Algorithm< Real >::pgstep(), ROL::ConicApproximationModel< Real >::precond(), ROL::Objective< Real >::precond(), ROL::StochasticObjective< Real >::precond(), ROL::RiskNeutralObjective< Real >::precond(), ROL::Reduced_Objective_SimOpt< Real >::precond(), ROL::ColemanLiModel< Real >::primalTransform(), ROL::KelleySachsModel< Real >::primalTransform(), ROL::TrustRegionModel< Real >::primalTransform(), ROL::DouglasRachfordProjection< Real >::project_bnd(), ROL::DykstraProjection< Real >::project_bnd(), ROL::DouglasRachfordProjection< Real >::project_con(), ROL::DykstraProjection< Real >::project_con(), ROL::BrentsProjection< Real >::project_df(), ROL::DaiFletcherProjection< Real >::project_df(), ROL::RiddersProjection< Real >::project_df(), ROL::DouglasRachfordProjection< Real >::project_DouglasRachford(), ROL::SemismoothNewtonProjection< Real >::project_ssn(), ROL::BallIndicatorObjective< Real >::prox(), ROL::l1Objective< Real >::prox(), ROL::TypeBIndicatorObjective< Real >::prox(), ROL::RandomizeFeasibleVector(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), ROL::DogLeg< Real >::run(), ROL::DoubleDogLeg< Real >::run(), ROL::LinMore< Real >::run(), ROL::TruncatedCG< Real >::run(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::GradientAlgorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::LinMoreAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeB::SpectralGradientAlgorithm< Real >::run(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::run(), ROL::TypeE::FletcherAlgorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeU::TrustRegionAlgorithm< Real >::run(), ROL::TypeP::InexactNewtonAlgorithm< Real >::run(), ROL::TypeP::iPianoAlgorithm< Real >::run(), ROL::TypeP::ProxGradientAlgorithm< Real >::run(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeP::SpectralGradientAlgorithm< Real >::run(), ROL::TypeP::TrustRegionAlgorithm< Real >::run(), ROL::BiCGSTAB< Real >::run(), BoundConstraint_BurgersControl< Real >::setVectorToLowerBound(), BoundConstraint_BurgersControl< Real >::setVectorToUpperBound(), ROL::DynamicConstraint< Real >::solve(), ROL::Constraint_SimOpt< Real >::solve(), ROL::CauchyPoint_U< Real >::solve(), ROL::DogLeg_U< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::SPGTrustRegion_U< Real >::solve(), ROL::TruncatedCG_U< Real >::solve(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson(), Normalization_Constraint< Real >::solveAugmentedSystem(), ROL::ScalarLinearConstraint< Real >::solveAugmentedSystem(), ROL::BoundFletcher< Real >::solveAugmentedSystem(), ROL::Fletcher< Real >::solveAugmentedSystem(), ROL::FletcherObjectiveE< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), ROL::BatchManager< Real >::sumAll(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::TrustRegion< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::BrentsProjection< Real >::update_primal(), ROL::DaiFletcherProjection< Real >::update_primal(), ROL::RiddersProjection< Real >::update_primal(), ROL::SemismoothNewtonProjection< Real >::update_primal(), ROL::LineSearch< Real >::updateIterate(), ROL::TypeG::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateState(), ROL::TypeB::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeB::MoreauYosidaAlgorithm< Real >::updateState(), ROL::BinaryConstraint< Real >::value(), ROL::LowerBoundToConstraint< Real >::value(), and ROL::UpperBoundToConstraint< Real >::value().
dual()
template<class Real > virtual const Vector & ROL::Vector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::ProfiledVector< Ordinal, Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::PrimalScaledStdVector< Real, Element >, ROL::DualScaledStdVector< Real, Element >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, ROL::PrimalAtomVector< Real >, ROL::DualAtomVector< Real >, ROL::PrimalProbabilityVector< Real >, ROL::DualProbabilityVector< Real >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::SimulatedVector< Real >, ROL::PrimalSimulatedVector< Real >, ROL::DualSimulatedVector< Real >, ROL::PartitionedVector< Real >, and ROL::Vector_SimOpt< Real >.
Definition at line 192 of file ROL_Vector.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::AffineTransformConstraint< Real >::AffineTransformConstraint(), ROL::AffineTransformObjective< Real >::AffineTransformObjective(), ROL::Vector< Real >::apply(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::HessianPNK::apply(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::apply(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS::apply(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrecondPDAS_Poly::apply(), ROL::FletcherObjectiveE< Real >::AugSystemPrecond::apply(), ROL::NewtonKrylov_U< Real >::PrecondNK::apply(), ROL::NullSpaceOperator< Real >::apply(), ROL::SemismoothNewtonProjection< Real >::Precond::apply(), ROL::BoundFletcher< Real >::AugSystemPrecond::apply(), ROL::Fletcher< Real >::AugSystemPrecond::apply(), ROL::NewtonKrylovStep< Real >::PrecondNK::apply(), ROL::PrimalDualActiveSetStep< Real >::PrecondPD::apply(), ROL::ProjectedNewtonKrylovStep< Real >::PrecondPNK::apply(), ROL::SemismoothNewtonProjection< Real >::Jacobian::apply(), ROL::RiskNeutralConstraint< Real >::applyAdjointHessian(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::RiskNeutralConstraint< Real >::applyAdjointJacobian(), ROL::ElasticLinearConstraint< Real >::applyAdjointJacobian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian_2(), ROL::lDFP< Real >::applyB(), ROL::lSR1< Real >::applyB(), ROL::lDFP< Real >::applyB0(), ROL::lSR1< Real >::applyB0(), ROL::Secant< Real >::applyB0(), ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LSecantBAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::LSecantBAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreePrecond(), ROL::lSR1< Real >::applyH(), ROL::lDFP< Real >::applyH0(), ROL::lSR1< Real >::applyH0(), ROL::Secant< Real >::applyH0(), ROL::TypeB::ColemanLiAlgorithm< Real >::applyHessian(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse(), ROL::SemismoothNewtonProjection< Real >::Precond::applyInverse(), ROL::ConstraintFromObjective< Real >::applyJacobian(), ROL::Constraint_DynamicState< Real >::applyPreconditioner(), ROL::SimConstraint< Real >::applyPreconditioner(), ROL::Constraint< Real >::applyPreconditioner(), ROL::AugmentedLagrangian< Real >::AugmentedLagrangian(), ROL::AugmentedLagrangian< Real >::AugmentedLagrangian(), ROL::AugmentedLagrangian_SimOpt< Real >::AugmentedLagrangian_SimOpt(), ROL::BoundFletcher< Real >::BoundFletcher(), ROL::DynamicConstraintCheck< Real >::check(), ROL::DynamicObjectiveCheck< Real >::check(), ROL::Constraint< Real >::checkAdjointConsistencyJacobian(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), ROL::Objective< Real >::checkGradient(), ROL::Objective< Real >::checkGradient(), ROL::Objective_SimOpt< Real >::checkGradient_1(), ROL::Objective_SimOpt< Real >::checkGradient_2(), ROL::Objective< Real >::checkHessSym(), ROL::Objective< Real >::checkHessVec(), ROL::Objective< Real >::checkHessVec(), ROL::Objective_SimOpt< Real >::checkHessVec_11(), ROL::Objective_SimOpt< Real >::checkHessVec_11(), ROL::Objective_SimOpt< Real >::checkHessVec_12(), ROL::Objective_SimOpt< Real >::checkHessVec_12(), ROL::Objective_SimOpt< Real >::checkHessVec_21(), ROL::Objective_SimOpt< Real >::checkHessVec_21(), ROL::Objective_SimOpt< Real >::checkHessVec_22(), ROL::Objective_SimOpt< Real >::checkHessVec_22(), ROL::Vector< Real >::checkVector(), ROL::CompositeConstraint_SimOpt< Real >::CompositeConstraint_SimOpt(), ROL::Gradient_U< Real >::compute(), ROL::Newton_U< Real >::compute(), ROL::NewtonKrylov_U< Real >::compute(), ROL::NonlinearCG_U< Real >::compute(), ROL::QuasiNewton_U< Real >::compute(), ROL::TrustRegionStep< Real >::computeCriticalityMeasure(), ROL::computeDenseHessian(), ROL::TypeP::TrustRegionAlgorithm< Real >::computeGradient(), ROL::AugmentedLagrangianStep< Real >::computeGradient(), ROL::FletcherStep< Real >::computeProjGradientNorm(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), ROL::computeScaledDenseHessian(), ROL::LinMore< Real >::dcauchy(), ROL::Objective< Real >::dirDeriv(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::LinMore< Real >::dprsrch(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::LinMore< Real >::dtrpcg(), ROL::PrimalScaledVector< Real >::dual(), ROL::Fletcher< Real >::Fletcher(), ROL::PH_bPOEObjective< Real >::getGradient(), ROL::PH_DeviationObjective< Real >::getGradient(), ROL::PH_ErrorObjective< Real >::getGradient(), ROL::PH_ProbObjective< Real >::getGradient(), ROL::PH_RegretObjective< Real >::getGradient(), ROL::PH_RiskObjective< Real >::getGradient(), ROL::InteriorPointObjective< Real >::getObjectiveGradient(), ROL::LineSearchStep< Real >::GradDotStep(), ROL::Objective_FSsolver< Real >::gradient(), ROL::NonlinearLeastSquaresObjective_Dynamic< Real >::hessVec(), ROL::Objective_FSsolver< Real >::hessVec(), ROL::PH_Objective< Real >::hessVec(), ROL::QuadraticPenalty< Real >::hessVec(), ROL::FletcherObjectiveE< Real >::hessVec(), ROL::NonlinearLeastSquaresObjective< Real >::hessVec(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_11(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_12(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_21(), ROL::QuadraticPenalty_SimOpt< Real >::hessVec_22(), ROL::RiskNeutralConstraint< Real >::init(), ROL::MoreauYosidaPenalty< Real >::initialize(), ROL::TrustRegionModel< Real >::initialize(), ROL::CompositeObjective_SimOpt< Real >::initialize(), ROL::CompositeObjective< Real >::initialize(), ROL::BPOE< Real >::initialize(), ROL::HMCR< Real >::initialize(), ROL::KLDivergence< Real >::initialize(), ROL::MeanDeviationFromTarget< Real >::initialize(), ROL::RandVarFunctional< Real >::initialize(), ROL::RiskNeutralObjective< Real >::initialize(), ROL::TRUtils::initialRadius(), main(), ROL::ColemanLiModel< Real >::minimize1D(), ROL::NonlinearLeastSquaresObjective< Real >::NonlinearLeastSquaresObjective(), ROL::NonlinearLeastSquaresObjective_Dynamic< Real >::NonlinearLeastSquaresObjective_Dynamic(), ROL::NullSpaceOperator< Real >::NullSpaceOperator(), ROL::TypeB::Algorithm< Real >::optimalityCriterion(), ROL::InteriorPoint::PenalizedObjective< Real >::PenalizedObjective(), ROL::NonlinearLeastSquaresObjective_Dynamic< Real >::precond(), ROL::Objective< Real >::precond(), ROL::StochasticObjective< Real >::precond(), ROL::RiskNeutralObjective< Real >::precond(), ROL::NonlinearLeastSquaresObjective< Real >::precond(), ROL::Reduced_Objective_SimOpt< Real >::precond(), ROL::QuadraticPenalty< Real >::QuadraticPenalty(), ROL::QuadraticPenalty_SimOpt< Real >::QuadraticPenalty_SimOpt(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), ROL::ProjectedObjective< Real >::reducedPrecond(), ROL::DogLeg< Real >::run(), ROL::DoubleDogLeg< Real >::run(), ROL::TypeB::LinMoreAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeU::Algorithm< Real >::run(), ROL::TypeP::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::DynamicConstraint< Real >::solve(), ROL::Constraint_SimOpt< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::ScalarLinearConstraint< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), ROL::Bundle< Real >::update(), ROL::TrustRegion< Real >::update(), ROL::ColemanLiModel< Real >::value(), ROL::KelleySachsModel< Real >::value(), and ROL::TrustRegionModel< Real >::value().
apply()
template<class Real > virtual Real ROL::Vector< Real >::apply (const Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, OptStdVector< Real, Element >, OptDualStdVector< Real, Element >, ConStdVector< Real, Element >, ConDualStdVector< Real, Element >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::PrimalScaledStdVector< Real, Element >, ROL::DualScaledStdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Definition at line 204 of file ROL_Vector.hpp.
References ROL::Vector< Real >::dot(), and ROL::Vector< Real >::dual().
Referenced by ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::lBFGS< Real >::applyB(), ROL::lBFGS< Real >::applyH(), ROL::ConstraintFromObjective< Real >::applyJacobian(), ROL::Constraint< Real >::checkAdjointConsistencyJacobian(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), ROL::Objective< Real >::checkGradient(), ROL::Objective_SimOpt< Real >::checkGradient_1(), ROL::Objective_SimOpt< Real >::checkGradient_2(), ROL::Objective< Real >::checkHessSym(), ROL::Gradient_U< Real >::compute(), ROL::Newton_U< Real >::compute(), ROL::NewtonKrylov_U< Real >::compute(), ROL::NonlinearCG_U< Real >::compute(), ROL::QuasiNewton_U< Real >::compute(), ROL::RandVarFunctional< Real >::computeGradVec(), ROL::TypeB::LinMoreAlgorithm< Real >::dcauchy(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dcauchy(), ROL::TypeB::LSecantBAlgorithm< Real >::dcauchy(), ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy(), ROL::Objective< Real >::dirDeriv(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dprsrch(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::PH_ErrorObjective< Real >::hessVec(), ROL::PH_ProbObjective< Real >::hessVec(), ROL::PH_RegretObjective< Real >::hessVec(), ROL::TRUtils::interpolateRadius(), ROL::SemismoothNewtonProjection< Real >::project_ssn(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::lSR1< Real >::updateStorage(), ROL::Secant< Real >::updateStorage(), ROL::LinearObjective_SimOpt< Real >::value(), and ROL::QuadraticObjective< Real >::value().
applyUnary()
template<class Real > virtual void ROL::Vector< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Reimplemented in ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::SingletonVector< Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, ROL::Vector_SimOpt< Real >, and ROL::ElementwiseVector< Real >.
Definition at line 208 of file ROL_Vector.hpp.
References ROL_UNUSED.
Referenced by calcError(), ROL::l1Objective< Real >::gradient(), ROL::LogBarrierObjective< Real >::gradient(), ROL::Vector< Real >::randomize(), ROL::RandomizeFeasibleVector(), ROL::RandomizeVector(), ROL::Vector< Real >::setScalar(), and testRandomInputs().
applyBinary()
template<class Real > virtual void ROL::Vector< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const Vector< Real > & x) inline virtual
Reimplemented in ROL::ElementwiseVector< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::SingletonVector< Real >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Definition at line 214 of file ROL_Vector.hpp.
References ROL_UNUSED.
Referenced by ROL::DiagonalOperator< Real >::apply(), ROL::BinaryConstraint< Real >::applyAdjointHessian(), ROL::ColemanLiModel< Real >::applyC(), ROL::ColemanLiModel< Real >::applyD(), ROL::DiagonalOperator< Real >::applyInverse(), ROL::ColemanLiModel< Real >::applyInverseD(), ROL::Bounds< Real >::applyInverseScalingFunction(), ROL::BinaryConstraint< Real >::applyJacobian(), ROL::Bounds< Real >::applyScalingFunctionJacobian(), ROL::Bounds< Real >::buildScalingFunction(), ROL::ColemanLiModel< Real >::computeFullReflectiveStep(), ROL::ColemanLiModel< Real >::computeReflectiveStep(), ROL::LinMore< Real >::dbreakpt(), ROL::l1Objective< Real >::gradient(), ROL::ObjectiveMMA< Real >::hessVec(), ROL::LogBarrierObjective< Real >::hessVec(), ROL::Bounds< Real >::project(), ROL::Bounds< Real >::projectInterior(), ROL::l1Objective< Real >::prox(), ROL::Bounds< Real >::pruneLowerActive(), ROL::Bounds< Real >::pruneLowerActive(), ROL::Bounds< Real >::pruneUpperActive(), ROL::Bounds< Real >::pruneUpperActive(), testRandomInputs(), and ROL::BinaryConstraint< Real >::value().
reduce()
template<class Real > virtual Real ROL::Vector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented in ROL::BatchStdVector< Real >, ROL::SROMVector< Real >, ROL::RiskVector< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::SingletonVector< Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, ROL::Vector_SimOpt< Real >, and ROL::ElementwiseVector< Real >.
Definition at line 221 of file ROL_Vector.hpp.
References ROL_UNUSED.
Referenced by calcError(), and ROL::LinMore< Real >::dbreakpt().
print()
template<class Real > virtual void ROL::Vector< Real >::print (std::ostream & outStream) const inline virtual
Reimplemented in ROL::SingletonVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::StdArray< Real, array_size, pool_size >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Definition at line 227 of file ROL_Vector.hpp.
Referenced by ROL::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::ReducedDynamicObjective< Real >::update(), and ROL::ReducedDynamicObjective< Real >::update().
setScalar()
template<class Real > virtual void ROL::Vector< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented in ROL::StdArray< Real, array_size, pool_size >, ROL::RiskVector< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::SingletonVector< Real >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Definition at line 241 of file ROL_Vector.hpp.
References ROL::Vector< Real >::applyUnary().
Referenced by ROL::Bounds< Real >::applyScalingFunctionJacobian(), and ROL::Bounds< Real >::buildScalingFunction().
randomize()
template<class Real > virtual void ROL::Vector< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented in ROL::StdArray< Real, array_size, pool_size >, ROL::RiskVector< Real >, ROL::SimulatedVector< Real >, ROL::PartitionedVector< Real >, ROL::ProfiledVector< Ordinal, Real >, ROL::RieszPrimalVector< Real >, ROL::RieszDualVector< Real >, ROL::SingletonVector< Real >, ROL::StdVector< Real, Element >, and ROL::Vector_SimOpt< Real >.
Definition at line 258 of file ROL_Vector.hpp.
References ROL::Vector< Real >::applyUnary().
checkVector()
template<class Real > virtual std::vector< Real > ROL::Vector< Real >::checkVector (const Vector< Real > & x, const Vector< Real > & y, const bool printToStream = true, std::ostream & outStream = std::cout) const inline virtual
Verify vector-space methods.
   @param[in]      x     is a vector.
   @param[in]      y     is a vector.
   Returns a vector of Reals, all of which should be close to zero.
   They represent consistency errors in the vector space properties,
   as follows:
   - Commutativity of addition: \f$\mathtt{*this} + x = x + \mathtt{*this}\f$.
   - Associativity of addition: \f$\mathtt{*this} + (x + y) = (\mathtt{*this} + x) + y\f$.
   - Identity element of addition: \f$0 + x = x\f$.
   - Inverse elements of addition: \f$\mathtt{*this} + (- \mathtt{*this}) = 0\f$.
   - Identity element of scalar multiplication: \f$ 1 \cdot \mathtt{*this} = \mathtt{*this} \f$.
   - Consistency of scalar multiplication with field multiplication: \f$a (b \cdot \mathtt{*this}) = (a b) \cdot \mathtt{*this}\f$.
   - Distributivity of scalar multiplication with respect to field addition: \f$(a+b) \cdot \mathtt{*this} = a \cdot \mathtt{*this} + b \cdot \mathtt{*this}\f$.
   - Distributivity of scalar multiplication with respect to vector addition: \f$a \cdot (\mathtt{*this} + x) = a \cdot \mathtt{*this} + a \cdot x\f$.
   - Commutativity of dot (inner) product over the field of reals: \f$(\mathtt{*this}, x)  = (x, \mathtt{*this})\f$.
   - Additivity of dot (inner) product: \f$(\mathtt{*this}, x+y)  = (\mathtt{*this}, x) + (\mathtt{*this}, y)\f$.
   - Consistency of scalar multiplication and norm: \f$\|{\mathtt{*this}} / {\|\mathtt{*this}\|} \| = 1\f$.
   - Reflexivity: \f$\mbox{dual}(\mbox{dual}(\mathtt{*this})) = \mathtt{*this}\f$ .
   - Consistency of apply and dual: \f$\langle \mathtt{*this}, x\rangle = (\mbox{dual}(\mathtt{*this}),x) = (\mathtt{*this},\mbox{dual}(x))\f$.
   The consistency errors are defined as the norms or absolute values of the differences between the left-hand
   side and the right-hand side terms in the above equalities.
   ---
Definition at line 291 of file ROL_Vector.hpp.
References ROL::Vector< Real >::clone(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), and ROL::Vector< Real >::zero().
Referenced by ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkSolutionVector(), and main().
The documentation for this class was generated from the following file:
ROL_Vector.hpp