ROL: ROL::PathBasedTargetLevel< Real > Class Template Reference
ROL::PathBasedTargetLevel< Real > Class Template Reference
Provides an implementation of path-based target leve line search.
#include <ROL_PathBasedTargetLevel.hpp>
Public Member Functions
virtual ~PathBasedTargetLevel ()
PathBasedTargetLevel (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con)
void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con)
Public Member Functions inherited from ROL::LineSearch< Real >
virtual ~LineSearch ()
LineSearch (ROL::ParameterList &parlist)
void setData (Real &eps, const Vector< Real > &g)
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Private Attributes
ROL::Ptr< Vector< Real > > xnew_
Real min_value_
Real rec_value_
Real target_
Real delta_
Real sigma_
Real bound_
Additional Inherited Members
Protected Member Functions inherited from ROL::LineSearch< Real >
virtual bool status (const ELineSearch type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
void setNextInitialAlpha (Real alpha)
void updateIterate (Vector< Real > &xnew, const Vector< Real > &x, const Vector< Real > &s, Real alpha, BoundConstraint< Real > &con)
bool useLocalMinimizer ()
bool takeNoStep ()
Detailed Description
template<class Real>
class ROL::PathBasedTargetLevel< Real >
Provides an implementation of path-based target leve line search.
Definition at line 22 of file ROL_PathBasedTargetLevel.hpp.
Constructor & Destructor Documentation
~PathBasedTargetLevel()
template<class Real > virtual ROL::PathBasedTargetLevel< Real >::~PathBasedTargetLevel () inline virtual
Definition at line 35 of file ROL_PathBasedTargetLevel.hpp.
PathBasedTargetLevel()
template<class Real > ROL::PathBasedTargetLevel< Real >::PathBasedTargetLevel (ROL::ParameterList & parlist) inline
Definition at line 38 of file ROL_PathBasedTargetLevel.hpp.
References ROL::PathBasedTargetLevel< Real >::bound_, and ROL::PathBasedTargetLevel< Real >::delta_.
Member Function Documentation
initialize()
template<class Real > void ROL::PathBasedTargetLevel< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Reimplemented from ROL::LineSearch< Real >.
Definition at line 46 of file ROL_PathBasedTargetLevel.hpp.
References ROL::Vector< Real >::clone(), ROL::LineSearch< Real >::initialize(), and ROL::PathBasedTargetLevel< Real >::xnew_.
run()
template<class Real > void ROL::PathBasedTargetLevel< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Implements ROL::LineSearch< Real >.
Definition at line 53 of file ROL_PathBasedTargetLevel.hpp.
References ROL::PathBasedTargetLevel< Real >::bound_, ROL::PathBasedTargetLevel< Real >::delta_, ROL::PathBasedTargetLevel< Real >::min_value_, ROL::PathBasedTargetLevel< Real >::rec_value_, ROL::PathBasedTargetLevel< Real >::sigma_, ROL::PathBasedTargetLevel< Real >::target_, ROL::Objective< Real >::update(), ROL::LineSearch< Real >::updateIterate(), ROL::Objective< Real >::value(), ROL::PathBasedTargetLevel< Real >::xnew_, and zero.
Member Data Documentation
xnew_
template<class Real > ROL::Ptr<Vector<Real> > ROL::PathBasedTargetLevel< Real >::xnew_ private
Definition at line 24 of file ROL_PathBasedTargetLevel.hpp.
Referenced by ROL::PathBasedTargetLevel< Real >::initialize(), and ROL::PathBasedTargetLevel< Real >::run().
min_value_
template<class Real > Real ROL::PathBasedTargetLevel< Real >::min_value_ private
Definition at line 26 of file ROL_PathBasedTargetLevel.hpp.
Referenced by ROL::PathBasedTargetLevel< Real >::run().
rec_value_
template<class Real > Real ROL::PathBasedTargetLevel< Real >::rec_value_ private
Definition at line 27 of file ROL_PathBasedTargetLevel.hpp.
Referenced by ROL::PathBasedTargetLevel< Real >::run().
target_
template<class Real > Real ROL::PathBasedTargetLevel< Real >::target_ private
Definition at line 28 of file ROL_PathBasedTargetLevel.hpp.
Referenced by ROL::PathBasedTargetLevel< Real >::run().
delta_
template<class Real > Real ROL::PathBasedTargetLevel< Real >::delta_ private
Definition at line 29 of file ROL_PathBasedTargetLevel.hpp.
Referenced by ROL::PathBasedTargetLevel< Real >::PathBasedTargetLevel(), and ROL::PathBasedTargetLevel< Real >::run().
sigma_
template<class Real > Real ROL::PathBasedTargetLevel< Real >::sigma_ private
Definition at line 30 of file ROL_PathBasedTargetLevel.hpp.
Referenced by ROL::PathBasedTargetLevel< Real >::run().
bound_
template<class Real > Real ROL::PathBasedTargetLevel< Real >::bound_ private
Definition at line 31 of file ROL_PathBasedTargetLevel.hpp.
Referenced by ROL::PathBasedTargetLevel< Real >::PathBasedTargetLevel(), and ROL::PathBasedTargetLevel< Real >::run().
The documentation for this class was generated from the following file:
ROL_PathBasedTargetLevel.hpp