ROL: ROL::Objective_SimOpt< Real > Class Template Reference
ROL::Objective_SimOpt< Real > Class Template Reference abstract
User Interface » Functional Interface
Provides the interface to evaluate simulation-based objective functions.
#include <ROL_Objective_SimOpt.hpp>
Public Member Functions
virtual void update (const Vector< Real > &u, const Vector< Real > &z, bool flag=true, int iter=-1)
Update objective function.
u is an iterate, z is an iterate, flag = true if the iterate has changed, iter is the outer algorithm iterations count.
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual Real value (const Vector< Real > &u, const Vector< Real > &z, Real &tol)=0
Compute value.
Real value (const Vector< Real > &x, Real &tol)
Compute value.
virtual void gradient_1 (Vector< Real > &g, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
virtual void gradient_2 (Vector< Real > &g, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
virtual void hessVec_11 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
virtual void hessVec_12 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
virtual void hessVec_21 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
virtual void hessVec_22 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::Objective_SimOpt< Real >
Provides the interface to evaluate simulation-based objective functions.
Definition at line 25 of file ROL_Objective_SimOpt.hpp.
Member Function Documentation
update() [1/4]
template<class Real > virtual void ROL::Objective_SimOpt< Real >::update (const Vector< Real > & u, const Vector< Real > & z, bool flag = true, int iter = -1) inline virtual
Update objective function.
u is an iterate, z is an iterate, flag = true if the iterate has changed, iter is the outer algorithm iterations count.
Reimplemented in ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, and ROL::QuadraticPenalty_SimOpt< Real >.
Definition at line 34 of file ROL_Objective_SimOpt.hpp.
Referenced by ROL::Objective_SimOpt< Real >::checkGradient_1(), ROL::Objective_SimOpt< Real >::checkGradient_2(), ROL::Objective_SimOpt< Real >::checkHessVec_11(), ROL::Objective_SimOpt< Real >::checkHessVec_12(), ROL::Objective_SimOpt< Real >::checkHessVec_21(), ROL::Objective_SimOpt< Real >::checkHessVec_22(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::Objective_SimOpt< Real >::update(), and ROL::Objective_SimOpt< Real >::update().
update() [2/4]
template<class Real > void ROL::Objective_SimOpt< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 36 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Objective_SimOpt< Real >::update().
update() [3/4]
template<class Real > virtual void ROL::Objective_SimOpt< Real >::update (const Vector< Real > & u, const Vector< Real > & z, UpdateType type, int iter = -1) inline virtual
Reimplemented in ROL::CompositeObjective_SimOpt< Real >, and ROL::LinearCombinationObjective_SimOpt< Real >.
Definition at line 42 of file ROL_Objective_SimOpt.hpp.
update() [4/4]
template<class Real > void ROL::Objective_SimOpt< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 44 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Objective_SimOpt< Real >::update().
value() [1/2]
template<class Real > virtual Real ROL::Objective_SimOpt< Real >::value (const Vector< Real > & u, const Vector< Real > & z, Real & tol) pure virtual
Compute value.
Implemented in Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, DiffusionObjective< Real >, ObjectiveFunctionTest08_1< Real >, ObjectiveFunctionTest08_2< Real >, ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::LinearObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, ROL::QuadraticPenalty_SimOpt< Real >, and ROL::SerialObjective< Real >.
Referenced by ROL::Objective_SimOpt< Real >::checkGradient_1(), ROL::Objective_SimOpt< Real >::checkGradient_2(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_2(), and ROL::Objective_SimOpt< Real >::value().
value() [2/2]
template<class Real > Real ROL::Objective_SimOpt< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 55 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), and ROL::Objective_SimOpt< Real >::value().
gradient_1()
template<class Real > virtual void ROL::Objective_SimOpt< Real >::gradient_1 (Vector< Real > & g, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented in Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, DiffusionObjective< Real >, ObjectiveFunctionTest08_1< Real >, ObjectiveFunctionTest08_2< Real >, ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::LinearObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, ROL::QuadraticPenalty_SimOpt< Real >, and ROL::SerialObjective< Real >.
Definition at line 64 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dot(), ROL::Temp, ROL::Objective_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::value(), and ROL::Vector< Real >::zero().
Referenced by ROL::Objective_SimOpt< Real >::checkGradient_1(), ROL::Objective_SimOpt< Real >::checkHessVec_11(), ROL::Objective_SimOpt< Real >::checkHessVec_12(), ROL::Objective_SimOpt< Real >::gradient(), ROL::Objective_SimOpt< Real >::hessVec_11(), and ROL::Objective_SimOpt< Real >::hessVec_12().
gradient_2()
template<class Real > virtual void ROL::Objective_SimOpt< Real >::gradient_2 (Vector< Real > & g, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented in Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, DiffusionObjective< Real >, ObjectiveFunctionTest08_1< Real >, ObjectiveFunctionTest08_2< Real >, ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::LinearObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, ROL::QuadraticPenalty_SimOpt< Real >, and ROL::SerialObjective< Real >.
Definition at line 84 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dot(), ROL::Temp, ROL::Objective_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::value(), and ROL::Vector< Real >::zero().
Referenced by ROL::Objective_SimOpt< Real >::checkGradient_2(), ROL::Objective_SimOpt< Real >::checkHessVec_21(), ROL::Objective_SimOpt< Real >::checkHessVec_22(), ROL::Objective_SimOpt< Real >::gradient(), ROL::Objective_SimOpt< Real >::hessVec_21(), and ROL::Objective_SimOpt< Real >::hessVec_22().
gradient()
template<class Real > void ROL::Objective_SimOpt< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 103 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Vector_SimOpt< Real >::set_1(), and ROL::Vector_SimOpt< Real >::set_2().
hessVec_11()
template<class Real > virtual void ROL::Objective_SimOpt< Real >::hessVec_11 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented in Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, DiffusionObjective< Real >, ObjectiveFunctionTest08_1< Real >, ObjectiveFunctionTest08_2< Real >, ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::LinearObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, ROL::QuadraticPenalty_SimOpt< Real >, and ROL::SerialObjective< Real >.
Definition at line 119 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Vector< Real >::zero().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_11(), and ROL::Objective_SimOpt< Real >::hessVec().
hessVec_12()
template<class Real > virtual void ROL::Objective_SimOpt< Real >::hessVec_12 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Reimplemented in Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, DiffusionObjective< Real >, ObjectiveFunctionTest08_1< Real >, ObjectiveFunctionTest08_2< Real >, ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::LinearObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, ROL::QuadraticPenalty_SimOpt< Real >, and ROL::SerialObjective< Real >.
Definition at line 143 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Vector< Real >::zero().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_12(), and ROL::Objective_SimOpt< Real >::hessVec().
hessVec_21()
template<class Real > virtual void ROL::Objective_SimOpt< Real >::hessVec_21 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Reimplemented in Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, DiffusionObjective< Real >, ObjectiveFunctionTest08_1< Real >, ObjectiveFunctionTest08_2< Real >, ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::LinearObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, ROL::QuadraticPenalty_SimOpt< Real >, and ROL::SerialObjective< Real >.
Definition at line 167 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Vector< Real >::zero().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_21(), and ROL::Objective_SimOpt< Real >::hessVec().
hessVec_22()
template<class Real > virtual void ROL::Objective_SimOpt< Real >::hessVec_22 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Reimplemented in Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, Objective_BurgersControl< Real >, DiffusionObjective< Real >, ObjectiveFunctionTest08_1< Real >, ObjectiveFunctionTest08_2< Real >, ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::LinearObjective_SimOpt< Real >, ROL::AugmentedLagrangian_SimOpt< Real >, ROL::QuadraticPenalty_SimOpt< Real >, and ROL::SerialObjective< Real >.
Definition at line 191 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Vector< Real >::zero().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_22(), and ROL::Objective_SimOpt< Real >::hessVec().
hessVec()
template<class Real > void ROL::Objective_SimOpt< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 215 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::Vector_SimOpt< Real >::set_1(), and ROL::Vector_SimOpt< Real >::set_2().
checkGradient_1() [1/3]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkGradient_1 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & d, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 236 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkGradient_1(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective_SimOpt< Real >::checkGradient_1(), and ROL::Objective_SimOpt< Real >::checkGradient_1().
checkGradient_1() [2/3]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkGradient_1 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & g, const Vector< Real > & d, const bool printToStream, std::ostream & outStream, const int numSteps, const int order) inline
Definition at line 246 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkGradient_1().
checkGradient_1() [3/3]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkGradient_1 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & g, const Vector< Real > & d, const std::vector< Real > & steps, const bool printToStream, std::ostream & outStream, const int order) inline
Definition at line 262 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Objective_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::value(), and ROL::Finite_Difference_Arrays::weights.
checkGradient_2() [1/3]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkGradient_2 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & d, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 357 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkGradient_2(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective_SimOpt< Real >::checkGradient_2(), and ROL::Objective_SimOpt< Real >::checkGradient_2().
checkGradient_2() [2/3]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkGradient_2 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & g, const Vector< Real > & d, const bool printToStream, std::ostream & outStream, const int numSteps, const int order) inline
Definition at line 367 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkGradient_2().
checkGradient_2() [3/3]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkGradient_2 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & g, const Vector< Real > & d, const std::vector< Real > & steps, const bool printToStream, std::ostream & outStream, const int order) inline
Definition at line 383 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Objective_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::value(), and ROL::Finite_Difference_Arrays::weights.
checkHessVec_11() [1/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_11 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 478 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_11(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_11(), ROL::Objective_SimOpt< Real >::checkHessVec_11(), and ROL::Objective_SimOpt< Real >::checkHessVec_11().
checkHessVec_11() [2/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_11 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 490 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_11(), and ROL::Vector< Real >::dual().
checkHessVec_11() [3/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_11 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const bool printToStream, std::ostream & outStream, const int numSteps, const int order) inline
Definition at line 502 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_11().
checkHessVec_11() [4/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_11 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream, std::ostream & outStream, const int order) inline
Definition at line 519 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::hessVec_11(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
checkHessVec_12() [1/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_12 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 625 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_12(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_12(), ROL::Objective_SimOpt< Real >::checkHessVec_12(), and ROL::Objective_SimOpt< Real >::checkHessVec_12().
checkHessVec_12() [2/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_12 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 635 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_12(), and ROL::Vector< Real >::dual().
checkHessVec_12() [3/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_12 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const bool printToStream, std::ostream & outStream, const int numSteps, const int order) inline
Definition at line 646 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_12().
checkHessVec_12() [4/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_12 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream, std::ostream & outStream, const int order) inline
Definition at line 663 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_1(), ROL::Objective_SimOpt< Real >::hessVec_12(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
checkHessVec_21() [1/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_21 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 769 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_21(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_21(), ROL::Objective_SimOpt< Real >::checkHessVec_21(), and ROL::Objective_SimOpt< Real >::checkHessVec_21().
checkHessVec_21() [2/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_21 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 781 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_21(), and ROL::Vector< Real >::dual().
checkHessVec_21() [3/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_21 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const bool printToStream, std::ostream & outStream, const int numSteps, const int order) inline
Definition at line 793 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_21().
checkHessVec_21() [4/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_21 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream, std::ostream & outStream, const int order) inline
Definition at line 810 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Objective_SimOpt< Real >::hessVec_21(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
checkHessVec_22() [1/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_22 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 916 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_22(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective_SimOpt< Real >::checkHessVec_22(), ROL::Objective_SimOpt< Real >::checkHessVec_22(), and ROL::Objective_SimOpt< Real >::checkHessVec_22().
checkHessVec_22() [2/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_22 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline
Definition at line 928 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_22(), and ROL::Vector< Real >::dual().
checkHessVec_22() [3/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_22 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const bool printToStream, std::ostream & outStream, const int numSteps, const int order) inline
Definition at line 940 of file ROL_Objective_SimOpt.hpp.
References ROL::Objective_SimOpt< Real >::checkHessVec_22().
checkHessVec_22() [4/4]
template<class Real > std::vector< std::vector< Real > > ROL::Objective_SimOpt< Real >::checkHessVec_22 (const Vector< Real > & u, const Vector< Real > & z, const Vector< Real > & hv, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream, std::ostream & outStream, const int order) inline
Definition at line 957 of file ROL_Objective_SimOpt.hpp.
References ROL::Vector< Real >::clone(), ROL::Objective_SimOpt< Real >::gradient_2(), ROL::Objective_SimOpt< Real >::hessVec_22(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::Objective_SimOpt< Real >::update(), and ROL::Finite_Difference_Arrays::weights.
The documentation for this class was generated from the following file:
ROL_Objective_SimOpt.hpp