ROL: ROL::IterationScaling< Real > Class Template Reference
ROL::IterationScaling< Real > Class Template Reference
Provides an implementation of iteration scaled line search.
#include <ROL_IterationScaling.hpp>
Public Member Functions
virtual ~IterationScaling ()
IterationScaling (ROL::ParameterList &parlist)
void initialize (const ROL::Vector< Real > &x, const ROL::Vector< Real > &s, const ROL::Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con)
void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con)
Public Member Functions inherited from ROL::LineSearch< Real >
virtual ~LineSearch ()
LineSearch (ROL::ParameterList &parlist)
void setData (Real &eps, const Vector< Real > &g)
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Private Attributes
int algo_iter_
ROL::Ptr< Vector< Real > > xnew_
Additional Inherited Members
Protected Member Functions inherited from ROL::LineSearch< Real >
virtual bool status (const ELineSearch type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
void setNextInitialAlpha (Real alpha)
void updateIterate (Vector< Real > &xnew, const Vector< Real > &x, const Vector< Real > &s, Real alpha, BoundConstraint< Real > &con)
bool useLocalMinimizer ()
bool takeNoStep ()
Detailed Description
template<class Real>
class ROL::IterationScaling< Real >
Provides an implementation of iteration scaled line search.
Definition at line 22 of file ROL_IterationScaling.hpp.
Constructor & Destructor Documentation
~IterationScaling()
template<class Real > virtual ROL::IterationScaling< Real >::~IterationScaling () inline virtual
Definition at line 29 of file ROL_IterationScaling.hpp.
IterationScaling()
template<class Real > ROL::IterationScaling< Real >::IterationScaling (ROL::ParameterList & parlist) inline
Definition at line 32 of file ROL_IterationScaling.hpp.
Member Function Documentation
initialize()
template<class Real > void ROL::IterationScaling< Real >::initialize (const ROL::Vector< Real > & x, const ROL::Vector< Real > & s, const ROL::Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Reimplemented from ROL::LineSearch< Real >.
Definition at line 34 of file ROL_IterationScaling.hpp.
References ROL::Vector< Real >::clone(), ROL::LineSearch< Real >::initialize(), and ROL::IterationScaling< Real >::xnew_.
run()
template<class Real > void ROL::IterationScaling< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Implements ROL::LineSearch< Real >.
Definition at line 41 of file ROL_IterationScaling.hpp.
References ROL::IterationScaling< Real >::algo_iter_, ROL::LineSearch< Real >::getInitialAlpha(), ROL::Objective< Real >::update(), ROL::LineSearch< Real >::updateIterate(), ROL::Objective< Real >::value(), and ROL::IterationScaling< Real >::xnew_.
Member Data Documentation
algo_iter_
template<class Real > int ROL::IterationScaling< Real >::algo_iter_ private
Definition at line 24 of file ROL_IterationScaling.hpp.
Referenced by ROL::IterationScaling< Real >::run().
xnew_
template<class Real > ROL::Ptr<Vector<Real> > ROL::IterationScaling< Real >::xnew_ private
Definition at line 25 of file ROL_IterationScaling.hpp.
Referenced by ROL::IterationScaling< Real >::initialize(), and ROL::IterationScaling< Real >::run().
The documentation for this class was generated from the following file:
ROL_IterationScaling.hpp