ROL: ROL::CauchyPoint_U< Real > Class Template Reference
ROL::CauchyPoint_U< Real > Class Template Reference
Provides interface for the Cauchy point trust-region subproblem solver.
#include <ROL_CauchyPoint_U.hpp>
Public Member Functions
CauchyPoint_U ()
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void solve (Vector< Real > &s, Real &snorm, Real &pRed, int &iflag, int &iter, const Real del, TrustRegionModel_U< Real > &model)
Public Member Functions inherited from ROL::TrustRegion_U< Real >
virtual ~TrustRegion_U ()
Private Attributes
Ptr< Vector< Real > > dual_
Detailed Description
template<class Real>
class ROL::CauchyPoint_U< Real >
Provides interface for the Cauchy point trust-region subproblem solver.
Definition at line 23 of file ROL_CauchyPoint_U.hpp.
Constructor & Destructor Documentation
CauchyPoint_U()
template<class Real > ROL::CauchyPoint_U< Real >::CauchyPoint_U () inline
Definition at line 30 of file ROL_CauchyPoint_U.hpp.
Member Function Documentation
initialize()
template<class Real > void ROL::CauchyPoint_U< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g) inline virtual
Reimplemented from ROL::TrustRegion_U< Real >.
Definition at line 32 of file ROL_CauchyPoint_U.hpp.
References ROL::Vector< Real >::clone(), and ROL::CauchyPoint_U< Real >::dual_.
solve()
template<class Real > void ROL::CauchyPoint_U< Real >::solve (Vector< Real > & s, Real & snorm, Real & pRed, int & iflag, int & iter, const Real del, TrustRegionModel_U< Real > & model) inline virtual
Implements ROL::TrustRegion_U< Real >.
Definition at line 36 of file ROL_CauchyPoint_U.hpp.
References ROL::CauchyPoint_U< Real >::dual_, ROL::TrustRegionModel_U< Real >::getGradient(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and zero.
Member Data Documentation
dual_
template<class Real > Ptr<Vector<Real> > ROL::CauchyPoint_U< Real >::dual_ private
Definition at line 26 of file ROL_CauchyPoint_U.hpp.
Referenced by ROL::CauchyPoint_U< Real >::initialize(), and ROL::CauchyPoint_U< Real >::solve().
The documentation for this class was generated from the following file:
ROL_CauchyPoint_U.hpp