ROL: ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual > Class Template Reference
ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual > Class Template Reference
Objective function: f(x) = exp(x1*x2*x3*x4*x5) + 0.5*(x1^3+x2^3+1)^2.
#include <ROL_SimpleEqConstrained.hpp>
Public Member Functions
Objective_SimpleEqConstrained ()
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Types
typedef std::vector< Real > vector
typedef Vector< Real > V
typedef vector::size_type uint
Private Member Functions
template<class VectorType >
ROL::Ptr< const vector > getVector (const V &x)
template<class VectorType >
ROL::Ptr< vector > getVector (V &x)
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real, class XPrim = StdVector<Real>, class XDual = StdVector<Real>>
class ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >
Objective function: f(x) = exp(x1*x2*x3*x4*x5) + 0.5*(x1^3+x2^3+1)^2.
Definition at line 32 of file ROL_SimpleEqConstrained.hpp.
Member Typedef Documentation
vector
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> typedef std::vector<Real> ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::vector private
Definition at line 34 of file ROL_SimpleEqConstrained.hpp.
V
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> typedef Vector<Real> ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::V private
Definition at line 35 of file ROL_SimpleEqConstrained.hpp.
uint
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> typedef vector::size_type ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::uint private
Definition at line 37 of file ROL_SimpleEqConstrained.hpp.
Constructor & Destructor Documentation
Objective_SimpleEqConstrained()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::Objective_SimpleEqConstrained () inline
Definition at line 55 of file ROL_SimpleEqConstrained.hpp.
Member Function Documentation
getVector() [1/2]
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> template<class VectorType > ROL::Ptr< const vector > ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::getVector (const V & x) inline private
Definition at line 43 of file ROL_SimpleEqConstrained.hpp.
References ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::getVector().
Referenced by ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::getVector(), and ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::getVector().
getVector() [2/2]
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> template<class VectorType > ROL::Ptr< vector > ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::getVector (V & x) inline private
Definition at line 49 of file ROL_SimpleEqConstrained.hpp.
References ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::getVector().
value()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> Real ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 57 of file ROL_SimpleEqConstrained.hpp.
gradient()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> void ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 81 of file ROL_SimpleEqConstrained.hpp.
hessVec()
template<class Real , class XPrim = StdVector<Real>, class XDual = StdVector<Real>> void ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 110 of file ROL_SimpleEqConstrained.hpp.
The documentation for this class was generated from the following file:
ROL_SimpleEqConstrained.hpp