ROL: ROL::ProjectedNewtonStep< Real > Class Template Reference
ROL::ProjectedNewtonStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with projected Newton's method using line search.
#include <ROL_ProjectedNewtonStep.hpp>
Public Member Functions
ProjectedNewtonStep (ROL::ParameterList &parlist, const bool computeObj=true)
Constructor.
void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool print_header=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Attributes
ROL::Ptr< Vector< Real > > gp_
Additional vector storage.
ROL::Ptr< Vector< Real > > d_
Additional vector storage.
int verbosity_
Verbosity level.
const bool computeObj_
bool useProjectedGrad_
Whether or not to use to the projected gradient criticality measure.
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::ProjectedNewtonStep< Real >
Provides the interface to compute optimization steps with projected Newton's method using line search.
Definition at line 25 of file ROL_ProjectedNewtonStep.hpp.
Constructor & Destructor Documentation
ProjectedNewtonStep()
template<class Real > ROL::ProjectedNewtonStep< Real >::ProjectedNewtonStep (ROL::ParameterList & parlist, const bool computeObj = true) inline
Constructor.
Standard constructor to build a ProjectedNewtonStep object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
Definition at line 47 of file ROL_ProjectedNewtonStep.hpp.
References ROL::ProjectedNewtonStep< Real >::useProjectedGrad_, and ROL::ProjectedNewtonStep< Real >::verbosity_.
Member Function Documentation
initialize()
template<class Real > void ROL::ProjectedNewtonStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with bound constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 56 of file ROL_ProjectedNewtonStep.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedNewtonStep< Real >::d_, ROL::ProjectedNewtonStep< Real >::gp_, and ROL::Step< Real >::initialize().
compute()
template<class Real > void ROL::ProjectedNewtonStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 64 of file ROL_ProjectedNewtonStep.hpp.
References ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::ProjectedNewtonStep< Real >::gp_, ROL::Objective< Real >::invHessVec(), ROL::Vector< Real >::plus(), ROL::BoundConstraint< Real >::pruneActive(), ROL::BoundConstraint< Real >::pruneInactive(), and ROL::Vector< Real >::scale().
update()
template<class Real > void ROL::ProjectedNewtonStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 83 of file ROL_ProjectedNewtonStep.hpp.
References ROL::ProjectedNewtonStep< Real >::computeObj_, ROL::BoundConstraint< Real >::computeProjectedGradient(), ROL::ProjectedNewtonStep< Real >::d_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::ProjectedNewtonStep< Real >::gp_, ROL::Objective< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::BoundConstraint< Real >::project(), ROL::AlgorithmState< Real >::snorm, ROL::Objective< Real >::update(), ROL::ProjectedNewtonStep< Real >::useProjectedGrad_, ROL::Objective< Real >::value(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::ProjectedNewtonStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 123 of file ROL_ProjectedNewtonStep.hpp.
References ROL::DESCENT_NEWTON, ROL::EDescentToString(), and ROL::ProjectedNewtonStep< Real >::verbosity_.
Referenced by ROL::ProjectedNewtonStep< Real >::print().
printName()
template<class Real > std::string ROL::ProjectedNewtonStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 149 of file ROL_ProjectedNewtonStep.hpp.
References ROL::DESCENT_NEWTON, and ROL::EDescentToString().
Referenced by ROL::ProjectedNewtonStep< Real >::print().
print()
template<class Real > std::string ROL::ProjectedNewtonStep< Real >::print (AlgorithmState< Real > & algo_state, bool printHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 154 of file ROL_ProjectedNewtonStep.hpp.
References ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::ProjectedNewtonStep< Real >::printHeader(), ROL::ProjectedNewtonStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
gp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ProjectedNewtonStep< Real >::gp_ private
Additional vector storage.
Definition at line 28 of file ROL_ProjectedNewtonStep.hpp.
Referenced by ROL::ProjectedNewtonStep< Real >::compute(), ROL::ProjectedNewtonStep< Real >::initialize(), and ROL::ProjectedNewtonStep< Real >::update().
d_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ProjectedNewtonStep< Real >::d_ private
Additional vector storage.
Definition at line 29 of file ROL_ProjectedNewtonStep.hpp.
Referenced by ROL::ProjectedNewtonStep< Real >::initialize(), and ROL::ProjectedNewtonStep< Real >::update().
verbosity_
template<class Real > int ROL::ProjectedNewtonStep< Real >::verbosity_ private
Verbosity level.
Definition at line 30 of file ROL_ProjectedNewtonStep.hpp.
Referenced by ROL::ProjectedNewtonStep< Real >::printHeader(), and ROL::ProjectedNewtonStep< Real >::ProjectedNewtonStep().
computeObj_
template<class Real > const bool ROL::ProjectedNewtonStep< Real >::computeObj_ private
Definition at line 31 of file ROL_ProjectedNewtonStep.hpp.
Referenced by ROL::ProjectedNewtonStep< Real >::update().
useProjectedGrad_
template<class Real > bool ROL::ProjectedNewtonStep< Real >::useProjectedGrad_ private
Whether or not to use to the projected gradient criticality measure.
Definition at line 32 of file ROL_ProjectedNewtonStep.hpp.
Referenced by ROL::ProjectedNewtonStep< Real >::ProjectedNewtonStep(), and ROL::ProjectedNewtonStep< Real >::update().
The documentation for this class was generated from the following file:
ROL_ProjectedNewtonStep.hpp