ROL: ROL::QuasiNewton_U< Real > Class Template Reference
ROL::QuasiNewton_U< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with a secant method.
#include <ROL_QuasiNewton_U.hpp>
Public Member Functions
QuasiNewton_U (ParameterList &parlist, const Ptr< Secant< Real > > &secant=nullPtr)
Constructor.
void compute (Vector< Real > &s, Real &snorm, Real &sdotg, int &iter, int &flag, const Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj) override
void update (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &gold, const Vector< Real > &gnew, const Real snorm, const int iter) override
std::string printName (void) const override
Public Member Functions inherited from ROL::DescentDirection_U< Real >
virtual ~DescentDirection_U ()
virtual void initialize (const Vector< Real > &x, const Vector< Real > &g)
Private Attributes
Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ESecant esec_
Secant type.
std::string secantName_
Secant name.
Detailed Description
template<typename Real>
class ROL::QuasiNewton_U< Real >
Provides the interface to compute optimization steps with a secant method.
Definition at line 27 of file ROL_QuasiNewton_U.hpp.
Constructor & Destructor Documentation
QuasiNewton_U()
template<typename Real > ROL::QuasiNewton_U< Real >::QuasiNewton_U (ParameterList & parlist, const Ptr< Secant< Real > > & secant = nullPtr) inline
Constructor.
Constructor to build a QuasiNewton object with a user-defined secant object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
[in] secant is a user-defined secant object
Definition at line 45 of file ROL_QuasiNewton_U.hpp.
References ROL::QuasiNewton_U< Real >::esec_, ROL::QuasiNewton_U< Real >::secant_, ROL::QuasiNewton_U< Real >::secantName_, and ROL::StringToESecant().
Member Function Documentation
compute()
template<typename Real > void ROL::QuasiNewton_U< Real >::compute (Vector< Real > & s, Real & snorm, Real & sdotg, int & iter, int & flag, const Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj) inline override virtual
Implements ROL::DescentDirection_U< Real >.
Definition at line 60 of file ROL_QuasiNewton_U.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::QuasiNewton_U< Real >::secant_, and ROL::Vector< Real >::set().
update()
template<typename Real > void ROL::QuasiNewton_U< Real >::update (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & gold, const Vector< Real > & gnew, const Real snorm, const int iter) inline override virtual
Reimplemented from ROL::DescentDirection_U< Real >.
Definition at line 76 of file ROL_QuasiNewton_U.hpp.
References ROL::QuasiNewton_U< Real >::secant_.
printName()
template<typename Real > std::string ROL::QuasiNewton_U< Real >::printName (void) const inline override virtual
Reimplemented from ROL::DescentDirection_U< Real >.
Definition at line 83 of file ROL_QuasiNewton_U.hpp.
References ROL::QuasiNewton_U< Real >::secantName_.
Member Data Documentation
secant_
template<typename Real > Ptr<Secant<Real> > ROL::QuasiNewton_U< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 30 of file ROL_QuasiNewton_U.hpp.
Referenced by ROL::QuasiNewton_U< Real >::compute(), ROL::QuasiNewton_U< Real >::QuasiNewton_U(), and ROL::QuasiNewton_U< Real >::update().
esec_
template<typename Real > ESecant ROL::QuasiNewton_U< Real >::esec_ private
Secant type.
Definition at line 31 of file ROL_QuasiNewton_U.hpp.
Referenced by ROL::QuasiNewton_U< Real >::QuasiNewton_U().
secantName_
template<typename Real > std::string ROL::QuasiNewton_U< Real >::secantName_ private
Secant name.
Definition at line 32 of file ROL_QuasiNewton_U.hpp.
Referenced by ROL::QuasiNewton_U< Real >::printName(), and ROL::QuasiNewton_U< Real >::QuasiNewton_U().
The documentation for this class was generated from the following file:
ROL_QuasiNewton_U.hpp