ROL: ROL::ProjectedNewtonKrylovStep< Real > Class Template Reference
ROL::ProjectedNewtonKrylovStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with projected inexact ProjectedNewton's method using line search.
#include <ROL_ProjectedNewtonKrylovStep.hpp>
Classes
class HessianPNK
class PrecondPNK
Public Member Functions
ProjectedNewtonKrylovStep (ROL::ParameterList &parlist, const bool computeObj=true)
Constructor.
ProjectedNewtonKrylovStep (ROL::ParameterList &parlist, const ROL::Ptr< Krylov< Real > > &krylov, const ROL::Ptr< Secant< Real > > &secant, const bool computeObj=true)
Constructor.
void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool print_header=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Attributes
ROL::Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ROL::Ptr< Krylov< Real > > krylov_
Krylov solver object (used for inexact Newton)
EKrylov ekv_
ESecant esec_
ROL::Ptr< Vector< Real > > gp_
ROL::Ptr< Vector< Real > > d_
int iterKrylov_
Number of Krylov iterations (used for inexact Newton)
int flagKrylov_
Termination flag for Krylov method (used for inexact Newton)
int verbosity_
Verbosity level.
const bool computeObj_
bool useSecantPrecond_
Whether or not a secant approximation is used for preconditioning inexact Newton.
bool useProjectedGrad_
Whether or not to use to the projected gradient criticality measure.
std::string krylovName_
std::string secantName_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::ProjectedNewtonKrylovStep< Real >
Provides the interface to compute optimization steps with projected inexact ProjectedNewton's method using line search.
Definition at line 33 of file ROL_ProjectedNewtonKrylovStep.hpp.
Constructor & Destructor Documentation
ProjectedNewtonKrylovStep() [1/2]
template<class Real > ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep (ROL::ParameterList & parlist, const bool computeObj = true) inline
Constructor.
Standard constructor to build a ProjectedNewtonKrylovStep object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
Definition at line 143 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::ProjectedNewtonKrylovStep< Real >::ekv_, ROL::ProjectedNewtonKrylovStep< Real >::esec_, ROL::ProjectedNewtonKrylovStep< Real >::krylov_, ROL::ProjectedNewtonKrylovStep< Real >::krylovName_, ROL::ProjectedNewtonKrylovStep< Real >::secant_, ROL::ProjectedNewtonKrylovStep< Real >::secantName_, ROL::StringToEKrylov(), ROL::StringToESecant(), ROL::ProjectedNewtonKrylovStep< Real >::useProjectedGrad_, ROL::ProjectedNewtonKrylovStep< Real >::useSecantPrecond_, and ROL::ProjectedNewtonKrylovStep< Real >::verbosity_.
ProjectedNewtonKrylovStep() [2/2]
template<class Real > ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep (ROL::ParameterList & parlist, const ROL::Ptr< Krylov< Real > > & krylov, const ROL::Ptr< Secant< Real > > & secant, const bool computeObj = true) inline
Constructor.
Constructor to build a ProjectedNewtonKrylovStep object with user-defined secant and Krylov objects. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
[in] krylov is a user-defined Krylov object
[in] secant is a user-defined secant object
Definition at line 175 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::ProjectedNewtonKrylovStep< Real >::ekv_, ROL::ProjectedNewtonKrylovStep< Real >::esec_, ROL::ProjectedNewtonKrylovStep< Real >::krylov_, ROL::ProjectedNewtonKrylovStep< Real >::krylovName_, ROL::ProjectedNewtonKrylovStep< Real >::secant_, ROL::ProjectedNewtonKrylovStep< Real >::secantName_, ROL::StringToEKrylov(), ROL::StringToESecant(), ROL::ProjectedNewtonKrylovStep< Real >::useProjectedGrad_, ROL::ProjectedNewtonKrylovStep< Real >::useSecantPrecond_, and ROL::ProjectedNewtonKrylovStep< Real >::verbosity_.
Member Function Documentation
initialize()
template<class Real > void ROL::ProjectedNewtonKrylovStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with bound constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 209 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedNewtonKrylovStep< Real >::d_, ROL::ProjectedNewtonKrylovStep< Real >::gp_, and ROL::Step< Real >::initialize().
compute()
template<class Real > void ROL::ProjectedNewtonKrylovStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 217 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::ProjectedNewtonKrylovStep< Real >::flagKrylov_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iterateVec, ROL::ProjectedNewtonKrylovStep< Real >::iterKrylov_, ROL::ProjectedNewtonKrylovStep< Real >::krylov_, ROL::Vector< Real >::scale(), ROL::ProjectedNewtonKrylovStep< Real >::secant_, ROL::Vector< Real >::set(), and ROL::ProjectedNewtonKrylovStep< Real >::useSecantPrecond_.
update()
template<class Real > void ROL::ProjectedNewtonKrylovStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 250 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::ProjectedNewtonKrylovStep< Real >::computeObj_, ROL::BoundConstraint< Real >::computeProjectedGradient(), ROL::ProjectedNewtonKrylovStep< Real >::d_, ROL::ProjectedNewtonKrylovStep< Real >::flagKrylov_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::ProjectedNewtonKrylovStep< Real >::gp_, ROL::Objective< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::ProjectedNewtonKrylovStep< Real >::iterKrylov_, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::BoundConstraint< Real >::project(), ROL::ProjectedNewtonKrylovStep< Real >::secant_, ROL::AlgorithmState< Real >::snorm, ROL::Objective< Real >::update(), ROL::ProjectedNewtonKrylovStep< Real >::useProjectedGrad_, ROL::ProjectedNewtonKrylovStep< Real >::useSecantPrecond_, ROL::Objective< Real >::value(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::ProjectedNewtonKrylovStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 300 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::DESCENT_NEWTONKRYLOV, ROL::EDescentToString(), and ROL::ProjectedNewtonKrylovStep< Real >::verbosity_.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::print().
printName()
template<class Real > std::string ROL::ProjectedNewtonKrylovStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 330 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::DESCENT_NEWTONKRYLOV, ROL::EDescentToString(), ROL::ProjectedNewtonKrylovStep< Real >::krylovName_, ROL::ProjectedNewtonKrylovStep< Real >::secantName_, and ROL::ProjectedNewtonKrylovStep< Real >::useSecantPrecond_.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::print().
print()
template<class Real > std::string ROL::ProjectedNewtonKrylovStep< Real >::print (AlgorithmState< Real > & algo_state, bool printHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 340 of file ROL_ProjectedNewtonKrylovStep.hpp.
References ROL::ProjectedNewtonKrylovStep< Real >::flagKrylov_, ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::ProjectedNewtonKrylovStep< Real >::iterKrylov_, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::ProjectedNewtonKrylovStep< Real >::printHeader(), ROL::ProjectedNewtonKrylovStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
secant_
template<class Real > ROL::Ptr<Secant<Real> > ROL::ProjectedNewtonKrylovStep< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 36 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::update().
krylov_
template<class Real > ROL::Ptr<Krylov<Real> > ROL::ProjectedNewtonKrylovStep< Real >::krylov_ private
Krylov solver object (used for inexact Newton)
Definition at line 37 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep().
ekv_
template<class Real > EKrylov ROL::ProjectedNewtonKrylovStep< Real >::ekv_ private
Definition at line 39 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep().
esec_
template<class Real > ESecant ROL::ProjectedNewtonKrylovStep< Real >::esec_ private
Definition at line 40 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep().
gp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ProjectedNewtonKrylovStep< Real >::gp_ private
Definition at line 42 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::initialize(), and ROL::ProjectedNewtonKrylovStep< Real >::update().
d_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ProjectedNewtonKrylovStep< Real >::d_ private
Definition at line 43 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::initialize(), and ROL::ProjectedNewtonKrylovStep< Real >::update().
iterKrylov_
template<class Real > int ROL::ProjectedNewtonKrylovStep< Real >::iterKrylov_ private
Number of Krylov iterations (used for inexact Newton)
Definition at line 45 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::print(), and ROL::ProjectedNewtonKrylovStep< Real >::update().
flagKrylov_
template<class Real > int ROL::ProjectedNewtonKrylovStep< Real >::flagKrylov_ private
Termination flag for Krylov method (used for inexact Newton)
Definition at line 46 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::print(), and ROL::ProjectedNewtonKrylovStep< Real >::update().
verbosity_
template<class Real > int ROL::ProjectedNewtonKrylovStep< Real >::verbosity_ private
Verbosity level.
Definition at line 47 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::printHeader(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep().
computeObj_
template<class Real > const bool ROL::ProjectedNewtonKrylovStep< Real >::computeObj_ private
Definition at line 48 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::update().
useSecantPrecond_
template<class Real > bool ROL::ProjectedNewtonKrylovStep< Real >::useSecantPrecond_ private
Whether or not a secant approximation is used for preconditioning inexact Newton.
Definition at line 50 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::printName(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::update().
useProjectedGrad_
template<class Real > bool ROL::ProjectedNewtonKrylovStep< Real >::useProjectedGrad_ private
Whether or not to use to the projected gradient criticality measure.
Definition at line 51 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::update().
krylovName_
template<class Real > std::string ROL::ProjectedNewtonKrylovStep< Real >::krylovName_ private
Definition at line 53 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::printName(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep().
secantName_
template<class Real > std::string ROL::ProjectedNewtonKrylovStep< Real >::secantName_ private
Definition at line 54 of file ROL_ProjectedNewtonKrylovStep.hpp.
Referenced by ROL::ProjectedNewtonKrylovStep< Real >::printName(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep().
The documentation for this class was generated from the following file:
ROL_ProjectedNewtonKrylovStep.hpp