ROL: ROL::SimulatedVector< Real > Class Template Reference
ROL::SimulatedVector< Real > Class Template Reference
User Interface » Linear Algebra Interface
Defines the linear algebra of a vector space on a generic partitioned vector where the individual vectors are distributed in batches defined by ROL::BatchManager. This is a batch-distributed version of ROL::PartitionedVector.
#include <ROL_SimulatedVector.hpp>
Public Types
typedef std::vector< PV >::size_type size_type
Public Member Functions
SimulatedVector (const std::vector< Vp > &vecs, const VBMp &bman)
void set (const V &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const V &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const V &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
virtual Real dot (const V &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
virtual Vp clone () const
Clone to make a new (uninitialized) vector.
virtual const V & dual (void) const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Vp basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void zero ()
Set to zero vector.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const V &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
ROL::Ptr< const Vector< Real > > get (size_type i) const
ROL::Ptr< Vector< Real > > get (size_type i)
void set (size_type i, const V &x)
void zero (size_type i)
size_type numVectors () const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual void print (std::ostream &outStream) const
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef Vector< Real > V
typedef ROL::Ptr< V > Vp
typedef ROL::Ptr< BatchManager< Real > > VBMp
typedef SimulatedVector< Real > PV
Private Attributes
const std::vector< Vp > vecs_
ROL::Ptr< BatchManager< Real > > bman_
std::vector< Vp > dual_vecs_
ROL::Ptr< PV > dual_pvec_
Detailed Description
template<class Real>
class ROL::SimulatedVector< Real >
Defines the linear algebra of a vector space on a generic partitioned vector where the individual vectors are distributed in batches defined by ROL::BatchManager. This is a batch-distributed version of ROL::PartitionedVector.
Definition at line 34 of file ROL_SimulatedVector.hpp.
Member Typedef Documentation
V
template<class Real > typedef Vector<Real> ROL::SimulatedVector< Real >::V private
Definition at line 36 of file ROL_SimulatedVector.hpp.
Vp
template<class Real > typedef ROL::Ptr<V> ROL::SimulatedVector< Real >::Vp private
Definition at line 37 of file ROL_SimulatedVector.hpp.
VBMp
template<class Real > typedef ROL::Ptr<BatchManager<Real> > ROL::SimulatedVector< Real >::VBMp private
Definition at line 38 of file ROL_SimulatedVector.hpp.
PV
template<class Real > typedef SimulatedVector<Real> ROL::SimulatedVector< Real >::PV private
Definition at line 39 of file ROL_SimulatedVector.hpp.
size_type
template<class Real > typedef std::vector<PV>::size_type ROL::SimulatedVector< Real >::size_type
Definition at line 48 of file ROL_SimulatedVector.hpp.
Constructor & Destructor Documentation
SimulatedVector()
template<class Real > ROL::SimulatedVector< Real >::SimulatedVector (const std::vector< Vp > & vecs, const VBMp & bman) inline
Definition at line 50 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::clone(), ROL::SimulatedVector< Real >::dual(), ROL::SimulatedVector< Real >::dual_vecs_, and ROL::SimulatedVector< Real >::vecs_.
Member Function Documentation
set() [1/2]
template<class Real > void ROL::SimulatedVector< Real >::set (const V & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 56 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::SimulatedVector< Real >::numVectors(), and ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedVector< Real >::basis().
plus()
template<class Real > void ROL::SimulatedVector< Real >::plus (const V & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 69 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::SimulatedVector< Real >::numVectors(), and ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::AlmostSureConstraint< Real >::applyAdjointHessian(), and ROL::AlmostSureConstraint< Real >::applyAdjointJacobian().
scale()
template<class Real > void ROL::SimulatedVector< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 82 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
axpy()
template<class Real > void ROL::SimulatedVector< Real >::axpy (const Real alpha, const V & x) inline virtual
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of @b x.
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = \mathtt{*this} + \alpha x \f$.
   Uses #clone, #set, #scale and #plus for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 88 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::SimulatedVector< Real >::numVectors(), and ROL::SimulatedVector< Real >::vecs_.
dot()
template<class Real > virtual Real ROL::SimulatedVector< Real >::dot (const V & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Reimplemented in ROL::PrimalSimulatedVector< Real >, and ROL::DualSimulatedVector< Real >.
Definition at line 101 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::bman_, ROL::SimulatedVector< Real >::get(), ROL::SimulatedVector< Real >::numVectors(), and ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedVector< Real >::norm().
norm()
template<class Real > Real ROL::SimulatedVector< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 120 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::dot().
clone()
template<class Real > virtual Vp ROL::SimulatedVector< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Reimplemented in ROL::PrimalSimulatedVector< Real >, and ROL::DualSimulatedVector< Real >.
Definition at line 124 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::bman_, ROL::SimulatedVector< Real >::clone(), and ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedVector< Real >::basis(), ROL::SimulatedVector< Real >::clone(), and ROL::SimulatedVector< Real >::SimulatedVector().
dual()
template<class Real > virtual const V & ROL::SimulatedVector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Reimplemented in ROL::PrimalSimulatedVector< Real >, and ROL::DualSimulatedVector< Real >.
Definition at line 135 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::bman_, ROL::SimulatedVector< Real >::dual(), ROL::SimulatedVector< Real >::dual_pvec_, ROL::SimulatedVector< Real >::dual_vecs_, ROL::Vector< Real >::set(), and ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedVector< Real >::dual(), and ROL::SimulatedVector< Real >::SimulatedVector().
basis()
template<class Real > Vp ROL::SimulatedVector< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 145 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::basis(), ROL::SimulatedVector< Real >::clone(), ROL::SimulatedVector< Real >::dimension(), ROL::SimulatedVector< Real >::set(), ROL::SimulatedVector< Real >::vecs_, and ROL::SimulatedVector< Real >::zero().
Referenced by ROL::SimulatedVector< Real >::basis().
dimension()
template<class Real > int ROL::SimulatedVector< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 176 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedVector< Real >::basis().
zero() [1/2]
template<class Real > void ROL::SimulatedVector< Real >::zero () inline virtual
Set to zero vector.
   Uses #scale by zero for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 184 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::AlmostSureConstraint< Real >::applyAdjointHessian(), ROL::AlmostSureConstraint< Real >::applyAdjointJacobian(), ROL::AlmostSureConstraint< Real >::applyPreconditioner(), and ROL::SimulatedVector< Real >::basis().
applyUnary()
template<class Real > void ROL::SimulatedVector< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 191 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
applyBinary()
template<class Real > void ROL::SimulatedVector< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const V & x) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 198 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::applyBinary(), ROL::SimulatedVector< Real >::get(), and ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedVector< Real >::applyBinary().
reduce()
template<class Real > Real ROL::SimulatedVector< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 206 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::reduce(), and ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedVector< Real >::reduce().
setScalar()
template<class Real > void ROL::SimulatedVector< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 215 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
randomize()
template<class Real > void ROL::SimulatedVector< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 221 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
get() [1/2]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::SimulatedVector< Real >::get (size_type i) const inline
Definition at line 231 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::AlmostSureConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::AlmostSureConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedVector< Real >::applyBinary(), ROL::AlmostSureConstraint< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::AlmostSureConstraint< Real >::applyPreconditioner(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), ROL::SimulatedVector< Real >::axpy(), ROL::SimulatedVector< Real >::dot(), ROL::PrimalSimulatedVector< Real >::dot(), ROL::DualSimulatedVector< Real >::dot(), ROL::SimulatedObjective< Real >::gradient(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), ROL::SimulatedObjective< Real >::hessVec(), ROL::SimulatedVector< Real >::plus(), ROL::SimulatedVector< Real >::set(), ROL::SimulatedObjective< Real >::value(), ROL::SimulatedObjectiveCVaR< Real >::value(), ROL::AlmostSureConstraint< Real >::value(), and ROL::SimulatedConstraint< Real >::value().
get() [2/2]
template<class Real > ROL::Ptr< Vector< Real > > ROL::SimulatedVector< Real >::get (size_type i) inline
Definition at line 235 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
set() [2/2]
template<class Real > void ROL::SimulatedVector< Real >::set (size_type i, const V & x) inline
Definition at line 239 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
zero() [2/2]
template<class Real > void ROL::SimulatedVector< Real >::zero (size_type i) inline
Definition at line 243 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
numVectors()
template<class Real > size_type ROL::SimulatedVector< Real >::numVectors () const inline
Definition at line 247 of file ROL_SimulatedVector.hpp.
References ROL::SimulatedVector< Real >::vecs_.
Referenced by ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), ROL::SimulatedVector< Real >::axpy(), ROL::SimulatedVector< Real >::dot(), ROL::PrimalSimulatedVector< Real >::dot(), ROL::DualSimulatedVector< Real >::dot(), ROL::SimulatedObjective< Real >::gradient(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), ROL::SimulatedObjective< Real >::hessVec(), ROL::SimulatedVector< Real >::plus(), ROL::SimulatedVector< Real >::set(), ROL::SimulatedObjective< Real >::value(), ROL::SimulatedObjectiveCVaR< Real >::value(), and ROL::SimulatedConstraint< Real >::value().
Member Data Documentation
vecs_
template<class Real > const std::vector<Vp> ROL::SimulatedVector< Real >::vecs_ private
Definition at line 42 of file ROL_SimulatedVector.hpp.
Referenced by ROL::SimulatedVector< Real >::applyBinary(), ROL::SimulatedVector< Real >::applyUnary(), ROL::SimulatedVector< Real >::axpy(), ROL::SimulatedVector< Real >::basis(), ROL::SimulatedVector< Real >::clone(), ROL::SimulatedVector< Real >::dimension(), ROL::SimulatedVector< Real >::dot(), ROL::SimulatedVector< Real >::dual(), ROL::SimulatedVector< Real >::get(), ROL::SimulatedVector< Real >::get(), ROL::SimulatedVector< Real >::numVectors(), ROL::SimulatedVector< Real >::plus(), ROL::SimulatedVector< Real >::randomize(), ROL::SimulatedVector< Real >::reduce(), ROL::SimulatedVector< Real >::scale(), ROL::SimulatedVector< Real >::set(), ROL::SimulatedVector< Real >::set(), ROL::SimulatedVector< Real >::setScalar(), ROL::SimulatedVector< Real >::SimulatedVector(), ROL::SimulatedVector< Real >::zero(), and ROL::SimulatedVector< Real >::zero().
bman_
template<class Real > ROL::Ptr<BatchManager<Real> > ROL::SimulatedVector< Real >::bman_ private
Definition at line 43 of file ROL_SimulatedVector.hpp.
Referenced by ROL::SimulatedVector< Real >::clone(), ROL::SimulatedVector< Real >::dot(), and ROL::SimulatedVector< Real >::dual().
dual_vecs_
template<class Real > std::vector<Vp> ROL::SimulatedVector< Real >::dual_vecs_ mutable private
Definition at line 44 of file ROL_SimulatedVector.hpp.
Referenced by ROL::SimulatedVector< Real >::dual(), and ROL::SimulatedVector< Real >::SimulatedVector().
dual_pvec_
template<class Real > ROL::Ptr<PV> ROL::SimulatedVector< Real >::dual_pvec_ mutable private
Definition at line 45 of file ROL_SimulatedVector.hpp.
Referenced by ROL::SimulatedVector< Real >::dual().
The documentation for this class was generated from the following file:
ROL_SimulatedVector.hpp