ROL: Objective_GrossPitaevskii< Real > Class Template Reference
Objective_GrossPitaevskii< Real > Class Template Reference
#include <example_01.hpp>
Public Member Functions
Objective_GrossPitaevskii (const Real &g, const Vector< Real > &pV)
Real value (const Vector< Real > &psi, Real &tol)
Evaluate \(J[\psi]\).
void gradient (Vector< Real > &g, const Vector< Real > &psi, Real &tol)
Evaluate \(\nabla J[\psi]\).
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &psi, Real &tol)
Evaluate \(\nabla^2 J[\psi] v\).
Objective_GrossPitaevskii (const Real &g, const Vector< Real > &V, ROL::Ptr< FiniteDifference< Real > > fd)
Real value (const Vector< Real > &psi, Real &tol)
Evaluate \(J[\psi]\).
void gradient (Vector< Real > &g, const Vector< Real > &psi, Real &tol)
Evaluate \(\nabla J[\psi]\).
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &psi, Real &tol)
Evaluate \(\nabla^2 J[\psi] v\).
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Types
typedef std::vector< Real > vector
typedef Vector< Real > V
typedef StdVector< Real > SV
typedef vector::size_type uint
typedef std::vector< Real > vector
typedef vector::size_type uint
Private Member Functions
ROL::Ptr< const vector > getVector (const V &x)
ROL::Ptr< vector > getVector (V &x)
void applyK (const Vector< Real > &v, Vector< Real > &kv)
Apply finite difference operator.
void applyK (const Vector< Real > &v, Vector< Real > &kv)
Apply finite difference operator.
Private Attributes
Real g_
uint nx_
Real dx_
ROL::Ptr< const vector > Vp_
ROL::Ptr< const std::vector< Real > > Vp_
ROL::Ptr< FiniteDifference< Real > > fd_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class Objective_GrossPitaevskii< Real >
Objective Function Class
Definition at line 53 of file gross-pitaevskii/example_01.hpp.
Member Typedef Documentation
vector [1/2]
template<class Real > ptr Vp_ Pointer to potential Objective_GrossPitaevskii< Real >::vector private
Definition at line 55 of file gross-pitaevskii/example_01.hpp.
V
template<class Real > typedef Vector<Real> Objective_GrossPitaevskii< Real >::V private
Definition at line 56 of file gross-pitaevskii/example_01.hpp.
SV
template<class Real > typedef StdVector<Real> Objective_GrossPitaevskii< Real >::SV private
Definition at line 57 of file gross-pitaevskii/example_01.hpp.
uint [1/2]
template<class Real > typedef vector::size_type Objective_GrossPitaevskii< Real >::uint private
Definition at line 59 of file gross-pitaevskii/example_01.hpp.
vector [2/2]
template<class Real > typedef std::vector<Real> Objective_GrossPitaevskii< Real >::vector private
Definition at line 423 of file gross-pitaevskii/example_02.hpp.
uint [2/2]
template<class Real > typedef vector::size_type Objective_GrossPitaevskii< Real >::uint private
Definition at line 424 of file gross-pitaevskii/example_02.hpp.
Constructor & Destructor Documentation
Objective_GrossPitaevskii() [1/2]
template<class Real > Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii (const Real & g, const Vector< Real > & pV) inline
Definition at line 114 of file gross-pitaevskii/example_01.hpp.
References Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::nx_, and Objective_GrossPitaevskii< Real >::Vp_.
Objective_GrossPitaevskii() [2/2]
template<class Real > Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii (const Real & g, const Vector< Real > & V, ROL::Ptr< FiniteDifference< Real > > fd) inline
Definition at line 469 of file gross-pitaevskii/example_02.hpp.
References Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::nx_, and Objective_GrossPitaevskii< Real >::Vp_.
Member Function Documentation
getVector() [1/2]
template<class Real > ROL::Ptr< const vector > Objective_GrossPitaevskii< Real >::getVector (const V & x) inline private
Definition at line 76 of file gross-pitaevskii/example_01.hpp.
References Objective_GrossPitaevskii< Real >::getVector().
Referenced by Objective_GrossPitaevskii< Real >::applyK(), Objective_GrossPitaevskii< Real >::getVector(), Objective_GrossPitaevskii< Real >::getVector(), Objective_GrossPitaevskii< Real >::gradient(), Objective_GrossPitaevskii< Real >::hessVec(), and Objective_GrossPitaevskii< Real >::value().
getVector() [2/2]
template<class Real > ROL::Ptr< vector > Objective_GrossPitaevskii< Real >::getVector (V & x) inline private
Definition at line 81 of file gross-pitaevskii/example_01.hpp.
References Objective_GrossPitaevskii< Real >::getVector().
applyK() [1/2]
template<class Real > void Objective_GrossPitaevskii< Real >::applyK (const Vector< Real > & v, Vector< Real > & kv) inline private
Apply finite difference operator.
Compute \(K\psi\), where \(K\) is the finite difference approximation of \(-D_x^2\)
Definition at line 91 of file gross-pitaevskii/example_01.hpp.
References Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
Referenced by Objective_GrossPitaevskii< Real >::gradient(), Objective_GrossPitaevskii< Real >::hessVec(), and Objective_GrossPitaevskii< Real >::value().
value() [1/2]
template<class Real > Real Objective_GrossPitaevskii< Real >::value (const Vector< Real > & psi, Real & tol) inline virtual
Evaluate \(J[\psi]\).
\[ J[\psi]=\frac{1}{2} \int\limits_0^1 |\psi'|^2 + V(x)|\psi|^2+g|\psi|^4\,\mathrm{d}x \]
where the integral is approximated with the trapezoidal rule and the derivative is approximated using finite differences
Implements ROL::Objective< Real >.
Definition at line 125 of file gross-pitaevskii/example_01.hpp.
References Objective_GrossPitaevskii< Real >::applyK(), ROL::Vector< Real >::clone(), Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::g_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
gradient() [1/2]
template<class Real > void Objective_GrossPitaevskii< Real >::gradient (Vector< Real > & g, const Vector< Real > & psi, Real & tol) inline virtual
Evaluate \(\nabla J[\psi]\).
\[ \nabla J[\psi] = -\psi'' + V(x)\psi+2g|\psi|^3 \]
Reimplemented from ROL::Objective< Real >.
Definition at line 152 of file gross-pitaevskii/example_01.hpp.
References Objective_GrossPitaevskii< Real >::applyK(), ROL::Vector< Real >::clone(), Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::g_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
hessVec() [1/2]
template<class Real > void Objective_GrossPitaevskii< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & psi, Real & tol) inline virtual
Evaluate \(\nabla^2 J[\psi] v\).
\[ \nabla^2 J[\psi]v = -v'' + V(x)v+6g|\psi|^2 v \]
Reimplemented from ROL::Objective< Real >.
Definition at line 178 of file gross-pitaevskii/example_01.hpp.
References Objective_GrossPitaevskii< Real >::applyK(), Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::g_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
applyK() [2/2]
template<class Real > void Objective_GrossPitaevskii< Real >::applyK (const Vector< Real > & v, Vector< Real > & kv) inline private
Apply finite difference operator.
Compute \(K\psi\), where \(K\) is the finite difference approximation of \(-D_x^2\)
Definition at line 445 of file gross-pitaevskii/example_02.hpp.
References Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
value() [2/2]
template<class Real > Real Objective_GrossPitaevskii< Real >::value (const Vector< Real > & psi, Real & tol) inline virtual
Evaluate \(J[\psi]\).
\[ J[\psi]=\frac{1}{2} \int\limits_0^1 |\psi'|^2 + V(x)|\psi|^2+g|\psi|^4\,\mathrm{d}x \]
where the integral is approximated with the trapezoidal rule and the derivative is approximated using finite differences
Implements ROL::Objective< Real >.
Definition at line 481 of file gross-pitaevskii/example_02.hpp.
References Objective_GrossPitaevskii< Real >::applyK(), Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::fd_, Objective_GrossPitaevskii< Real >::g_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
gradient() [2/2]
template<class Real > void Objective_GrossPitaevskii< Real >::gradient (Vector< Real > & g, const Vector< Real > & psi, Real & tol) inline virtual
Evaluate \(\nabla J[\psi]\).
\[ \nabla J[\psi] = -\psi'' + V(x)\psi+2g|\psi|^3 \]
Reimplemented from ROL::Objective< Real >.
Definition at line 508 of file gross-pitaevskii/example_02.hpp.
References Objective_GrossPitaevskii< Real >::applyK(), Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::fd_, Objective_GrossPitaevskii< Real >::g_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
hessVec() [2/2]
template<class Real > void Objective_GrossPitaevskii< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & psi, Real & tol) inline virtual
Evaluate \(\nabla^2 J[\psi] v\).
\[ \nabla^2 J[\psi]v = -v'' + V(x)v+6g|\psi|^2 v \]
Reimplemented from ROL::Objective< Real >.
Definition at line 534 of file gross-pitaevskii/example_02.hpp.
References Objective_GrossPitaevskii< Real >::applyK(), Objective_GrossPitaevskii< Real >::dx_, Objective_GrossPitaevskii< Real >::g_, Objective_GrossPitaevskii< Real >::getVector(), and Objective_GrossPitaevskii< Real >::nx_.
Member Data Documentation
g_
template<class Real > Real Objective_GrossPitaevskii< Real >::g_ private
Definition at line 65 of file gross-pitaevskii/example_01.hpp.
Referenced by Objective_GrossPitaevskii< Real >::gradient(), Objective_GrossPitaevskii< Real >::hessVec(), and Objective_GrossPitaevskii< Real >::value().
nx_
template<class Real > uint Objective_GrossPitaevskii< Real >::nx_ private
Definition at line 68 of file gross-pitaevskii/example_01.hpp.
Referenced by Objective_GrossPitaevskii< Real >::applyK(), Objective_GrossPitaevskii< Real >::gradient(), Objective_GrossPitaevskii< Real >::hessVec(), Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii(), Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii(), and Objective_GrossPitaevskii< Real >::value().
dx_
template<class Real > Real Objective_GrossPitaevskii< Real >::dx_ private
Definition at line 71 of file gross-pitaevskii/example_01.hpp.
Referenced by Objective_GrossPitaevskii< Real >::applyK(), Objective_GrossPitaevskii< Real >::gradient(), Objective_GrossPitaevskii< Real >::hessVec(), Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii(), Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii(), and Objective_GrossPitaevskii< Real >::value().
Vp_ [1/2]
template<class Real > ROL::Ptr<const vector> Objective_GrossPitaevskii< Real >::Vp_ private
Definition at line 74 of file gross-pitaevskii/example_01.hpp.
Referenced by Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii(), and Objective_GrossPitaevskii< Real >::Objective_GrossPitaevskii().
Vp_ [2/2]
template<class Real > ROL::Ptr<const std::vector<Real> > Objective_GrossPitaevskii< Real >::Vp_ private
Definition at line 438 of file gross-pitaevskii/example_02.hpp.
fd_
template<class Real > ROL::Ptr<FiniteDifference<Real> > Objective_GrossPitaevskii< Real >::fd_ private
Definition at line 440 of file gross-pitaevskii/example_02.hpp.
Referenced by Objective_GrossPitaevskii< Real >::gradient(), and Objective_GrossPitaevskii< Real >::value().
The documentation for this class was generated from the following files:
gross-pitaevskii/example_01.hpp
gross-pitaevskii/example_02.hpp