ROL: ROL::TypeP::SpectralGradientAlgorithm< Real > Class Template Reference
ROL::TypeP::SpectralGradientAlgorithm< Real > Class Template Reference
Provides an interface to run the proximal gradient algorithm.
#include <ROL_TypeP_SpectralGradientAlgorithm.hpp>
Public Member Functions
SpectralGradientAlgorithm (ParameterList &list)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout) override
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeP::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, Vector< Real > &px, Vector< Real > &dg, std::ostream &outStream=std::cout)
Private Attributes
int maxit_
int maxSize_
Real lambda_
Real lambdaMin_
Real lambdaMax_
Real sigma1_
Real sigma2_
Real rhodec_
Real gamma_
Real t0_
bool initProx_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeP::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void pgstep (Vector< Real > &pgiter, Vector< Real > &pgstep, Objective< Real > &nobj, const Vector< Real > &x, const Vector< Real > &dg, Real t, Real &tol) const
Protected Attributes inherited from ROL::TypeP::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeP::SpectralGradientAlgorithm< Real >
Provides an interface to run the proximal gradient algorithm.
Definition at line 23 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
Constructor & Destructor Documentation
SpectralGradientAlgorithm()
template<typename Real > ROL::TypeP::SpectralGradientAlgorithm< Real >::SpectralGradientAlgorithm (ParameterList & list)
Definition at line 17 of file ROL_TypeP_SpectralGradientAlgorithm_Def.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeP::SpectralGradientAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, Vector< Real > & px, Vector< Real > & dg, std::ostream & outStream = std::cout) private
Definition at line 40 of file ROL_TypeP_SpectralGradientAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeP::Algorithm< Real >::initialize(), ROL::Objective< Real >::prox(), ROL::Vector< Real >::set(), ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and zero.
run()
template<typename Real > void ROL::TypeP::SpectralGradientAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, std::ostream & outStream = std::cout) override virtual
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeP::Algorithm< Real >.
Definition at line 71 of file ROL_TypeP_SpectralGradientAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeP::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeP::SpectralGradientAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 189 of file ROL_TypeP_SpectralGradientAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeP::SpectralGradientAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 224 of file ROL_TypeP_SpectralGradientAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeP::SpectralGradientAlgorithm< Real >::writeOutput (std::ostream & os, bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 231 of file ROL_TypeP_SpectralGradientAlgorithm_Def.hpp.
Member Data Documentation
maxit_
template<typename Real > int ROL::TypeP::SpectralGradientAlgorithm< Real >::maxit_ private
Definition at line 25 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
maxSize_
template<typename Real > int ROL::TypeP::SpectralGradientAlgorithm< Real >::maxSize_ private
Definition at line 25 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
lambda_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::lambda_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
lambdaMin_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::lambdaMin_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
lambdaMax_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::lambdaMax_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
sigma1_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::sigma1_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
sigma2_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::sigma2_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
rhodec_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::rhodec_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
gamma_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::gamma_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
t0_
template<typename Real > Real ROL::TypeP::SpectralGradientAlgorithm< Real >::t0_ private
Definition at line 26 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
initProx_
template<typename Real > bool ROL::TypeP::SpectralGradientAlgorithm< Real >::initProx_ private
Definition at line 27 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeP::SpectralGradientAlgorithm< Real >::verbosity_ private
Definition at line 28 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeP::SpectralGradientAlgorithm< Real >::writeHeader_ private
Definition at line 29 of file ROL_TypeP_SpectralGradientAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeP_SpectralGradientAlgorithm.hpp
ROL_TypeP_SpectralGradientAlgorithm_Def.hpp