ROL: ROL::GenMoreauYosidaCVaR< Real > Class Template Reference
ROL::GenMoreauYosidaCVaR< Real > Class Template Reference
#include <ROL_GenMoreauYosidaCVaR.hpp>
Public Member Functions
GenMoreauYosidaCVaR (Real prob, Real eps)
Constructor.
GenMoreauYosidaCVaR (Real prob, Real lam, Real eps)
Constructor.
GenMoreauYosidaCVaR (ROL::ParameterList &parlist)
Constructor.
Real error (Real x, int deriv=0)
Evaluate the scalar error function at x.
Real regret (Real x, int deriv=0)
Evaluate the scalar regret function at x.
void check (void)
Run default derivative tests for the scalar regret function.
Public Member Functions inherited from ROL::ExpectationQuad< Real >
virtual ~ExpectationQuad (void)
ExpectationQuad (void)
Private Member Functions
void parseParameterList (ROL::ParameterList &parlist)
void checkInputs (void) const
void setParameters (void)
Private Attributes
Real prob_
Real lam_
Real eps_
Real alpha_
Real beta_
Real omp_
Real oma_
Real bmo_
Real lb_
Real ub_
Detailed Description
template<class Real>
class ROL::GenMoreauYosidaCVaR< Real >
Definition at line 71 of file ROL_GenMoreauYosidaCVaR.hpp.
Constructor & Destructor Documentation
GenMoreauYosidaCVaR() [1/3]
template<class Real > ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR (Real prob, Real eps) inline
Constructor.
Parameters
[in] prob is the confidence level
[in] eps is the regularization parameter
Definition at line 134 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::checkInputs(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
GenMoreauYosidaCVaR() [2/3]
template<class Real > ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR (Real prob, Real lam, Real eps) inline
Constructor.
Parameters
[in] prob is the confidence level
[in] lam is the convex combination parameter
[in] eps is the regularization parameter
Definition at line 146 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::checkInputs(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
GenMoreauYosidaCVaR() [3/3]
template<class Real > ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measure"->"Moreau-Yosida CVaR" and within the "Moreau-Yosida CVaR" sublist should have the following parameters
"Confidence Level" (between 0 and 1)
"Convex Combination Parameter" (between 0 and 1)
"Smoothing Parameter" (must be positive)
Definition at line 162 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::checkInputs(), ROL::GenMoreauYosidaCVaR< Real >::parseParameterList(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
Member Function Documentation
parseParameterList()
template<class Real > void ROL::GenMoreauYosidaCVaR< Real >::parseParameterList (ROL::ParameterList & parlist) inline private
Definition at line 87 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::eps_, ROL::GenMoreauYosidaCVaR< Real >::lam_, and ROL::GenMoreauYosidaCVaR< Real >::prob_.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR().
checkInputs()
template<class Real > void ROL::GenMoreauYosidaCVaR< Real >::checkInputs (void) const inline private
Definition at line 107 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::eps_, ROL::GenMoreauYosidaCVaR< Real >::lam_, ROL::GenMoreauYosidaCVaR< Real >::prob_, and zero.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR(), ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR(), and ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR().
setParameters()
template<class Real > void ROL::GenMoreauYosidaCVaR< Real >::setParameters (void) inline private
Definition at line 117 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::alpha_, ROL::GenMoreauYosidaCVaR< Real >::beta_, ROL::GenMoreauYosidaCVaR< Real >::bmo_, ROL::GenMoreauYosidaCVaR< Real >::eps_, ROL::GenMoreauYosidaCVaR< Real >::lam_, ROL::GenMoreauYosidaCVaR< Real >::lb_, ROL::GenMoreauYosidaCVaR< Real >::oma_, ROL::GenMoreauYosidaCVaR< Real >::omp_, ROL::GenMoreauYosidaCVaR< Real >::prob_, and ROL::GenMoreauYosidaCVaR< Real >::ub_.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR(), ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR(), and ROL::GenMoreauYosidaCVaR< Real >::GenMoreauYosidaCVaR().
error()
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::error (Real x, int deriv = 0) inline virtual
Evaluate the scalar error function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(e(x)\) or a derivative of \(e(x)\).
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 169 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::regret(), and zero.
regret()
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::regret (Real x, int deriv = 0) inline virtual
Evaluate the scalar regret function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(v(x)\) or a derivative of \(v(x)\).
Implements ROL::ExpectationQuad< Real >.
Definition at line 175 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::GenMoreauYosidaCVaR< Real >::alpha_, ROL::GenMoreauYosidaCVaR< Real >::beta_, ROL::GenMoreauYosidaCVaR< Real >::bmo_, ROL::GenMoreauYosidaCVaR< Real >::eps_, ROL::GenMoreauYosidaCVaR< Real >::lb_, ROL::GenMoreauYosidaCVaR< Real >::oma_, ROL::GenMoreauYosidaCVaR< Real >::ub_, and zero.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::check(), and ROL::GenMoreauYosidaCVaR< Real >::error().
check()
template<class Real > void ROL::GenMoreauYosidaCVaR< Real >::check (void) inline virtual
Run default derivative tests for the scalar regret function.
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 192 of file ROL_GenMoreauYosidaCVaR.hpp.
References ROL::ExpectationQuad< Real >::check(), ROL::GenMoreauYosidaCVaR< Real >::lb_, ROL::GenMoreauYosidaCVaR< Real >::regret(), ROL::GenMoreauYosidaCVaR< Real >::ub_, and zero.
Member Data Documentation
prob_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::prob_ private
Definition at line 74 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::checkInputs(), ROL::GenMoreauYosidaCVaR< Real >::parseParameterList(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
lam_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::lam_ private
Definition at line 75 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::checkInputs(), ROL::GenMoreauYosidaCVaR< Real >::parseParameterList(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
eps_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::eps_ private
Definition at line 76 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::checkInputs(), ROL::GenMoreauYosidaCVaR< Real >::parseParameterList(), ROL::GenMoreauYosidaCVaR< Real >::regret(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
alpha_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::alpha_ private
Definition at line 78 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::regret(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
beta_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::beta_ private
Definition at line 79 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::regret(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
omp_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::omp_ private
Definition at line 81 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::setParameters().
oma_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::oma_ private
Definition at line 82 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::regret(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
bmo_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::bmo_ private
Definition at line 83 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::regret(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
lb_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::lb_ private
Definition at line 84 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::check(), ROL::GenMoreauYosidaCVaR< Real >::regret(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
ub_
template<class Real > Real ROL::GenMoreauYosidaCVaR< Real >::ub_ private
Definition at line 85 of file ROL_GenMoreauYosidaCVaR.hpp.
Referenced by ROL::GenMoreauYosidaCVaR< Real >::check(), ROL::GenMoreauYosidaCVaR< Real >::regret(), and ROL::GenMoreauYosidaCVaR< Real >::setParameters().
The documentation for this class was generated from the following file:
ROL_GenMoreauYosidaCVaR.hpp