ROL: ROL::SecondOrderCVaR< Real > Class Template Reference
ROL::SecondOrderCVaR< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for the risk measure associated with the super quantile quadrangle.
#include <ROL_SecondOrderCVaR.hpp>
Public Member Functions
SecondOrderCVaR (ROL::ParameterList &parlist)
SecondOrderCVaR (const Real alpha, const int nQuad, const ROL::Ptr< PlusFunction< Real > > &pf, const bool useGauss=true)
Public Member Functions inherited from ROL::SpectralRisk< Real >
SpectralRisk (void)
SpectralRisk (const ROL::Ptr< Distribution< Real > > &dist, const int nQuad, const ROL::Ptr< PlusFunction< Real > > &pf)
SpectralRisk (ROL::ParameterList &parlist)
SpectralRisk (const std::vector< Real > &pts, const std::vector< Real > &wts, const ROL::Ptr< PlusFunction< Real > > &pf)
void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage) override
void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage) override
void setSample (const std::vector< Real > &point, const Real weight) override
void resetStorage (bool flag=true) override
Reset internal storage.
void resetStorage (UpdateType type) override
void initialize (const Vector< Real > &x) override
Initialize temporary variables.
Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const override
Compute statistic.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal storage for value computation.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal risk measure storage for gradient computation.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal risk measure storage for Hessian-time-a-vector computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure value.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure (sub)gradient.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
Private Member Functions
void checkInputs (void) const
void initializeQuad (void)
Private Attributes
ROL::Ptr< PlusFunction< Real > > plusFunction_
Real alpha_
int nQuad_
bool useGauss_
std::vector< Real > wts_
std::vector< Real > pts_
Additional Inherited Members
Protected Member Functions inherited from ROL::SpectralRisk< Real >
void buildMixedQuantile (const std::vector< Real > &pts, const std::vector< Real > &wts, const ROL::Ptr< PlusFunction< Real > > &pf)
void buildQuadFromDist (std::vector< Real > &pts, std::vector< Real > &wts, const int nQuad, const ROL::Ptr< Distribution< Real > > &dist) const
void printQuad (const std::vector< Real > &pts, const std::vector< Real > &wts, const bool print=false) const
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::SecondOrderCVaR< Real >
Provides an interface for the risk measure associated with the super quantile quadrangle.
The risk measure associated with the super quantile quadrangle is defined as
\[ \mathcal{R}(X) = \frac{1}{1-\beta}\int_\beta^1\mathrm{CVaR}_{\alpha}(X) \,\mathrm{d}\alpha \]
where \(0 \le \beta < 1\) and the conditional value-at-risk (CVaR) with confidence level \(0\le \alpha < 1\) is
\[ \mathrm{CVaR}_\alpha(X) = \inf_{t\in\mathbb{R}} \left\{ t + \frac{1}{1-\alpha} \mathbb{E}\left[(X-t)_+\right] \right\} \]
where \((x)_+ = \max\{0,x\}\). If the distribution of \(X\) is continuous, then \(\mathrm{CVaR}_{\alpha}(X)\) is the conditional expectation of \(X\) exceeding the \(\alpha\)-quantile of \(X\) and the optimal \(t\) is the \(\alpha\)-quantile. Additionally, \(\mathcal{R}\) is a law-invariant coherent risk measure.
ROL implements \(\mathcal{R}\) by approximating the integral with Gauss-Legendre or Fejer 2 quadrature. The corresponding quadrature points and weights are then used to construct a ROL::MixedQuantileQuadrangle risk measure. When using derivative-based optimization, the user can provide a smooth approximation of \((\cdot)_+\) using the ROL::PlusFunction class.
Definition at line 51 of file ROL_SecondOrderCVaR.hpp.
Constructor & Destructor Documentation
SecondOrderCVaR() [1/2]
template<class Real > ROL::SecondOrderCVaR< Real >::SecondOrderCVaR (ROL::ParameterList & parlist) inline
Definition at line 92 of file ROL_SecondOrderCVaR.hpp.
References ROL::SecondOrderCVaR< Real >::alpha_, ROL::SecondOrderCVaR< Real >::checkInputs(), ROL::SecondOrderCVaR< Real >::initializeQuad(), ROL::SecondOrderCVaR< Real >::nQuad_, ROL::SecondOrderCVaR< Real >::plusFunction_, and ROL::SecondOrderCVaR< Real >::useGauss_.
SecondOrderCVaR() [2/2]
template<class Real > ROL::SecondOrderCVaR< Real >::SecondOrderCVaR (const Real alpha, const int nQuad, const ROL::Ptr< PlusFunction< Real > > & pf, const bool useGauss = true) inline
Definition at line 106 of file ROL_SecondOrderCVaR.hpp.
References ROL::SecondOrderCVaR< Real >::checkInputs(), and ROL::SecondOrderCVaR< Real >::initializeQuad().
Member Function Documentation
checkInputs()
template<class Real > void ROL::SecondOrderCVaR< Real >::checkInputs (void) const inline private
Definition at line 62 of file ROL_SecondOrderCVaR.hpp.
References ROL::SecondOrderCVaR< Real >::plusFunction_.
Referenced by ROL::SecondOrderCVaR< Real >::SecondOrderCVaR(), and ROL::SecondOrderCVaR< Real >::SecondOrderCVaR().
initializeQuad()
template<class Real > void ROL::SecondOrderCVaR< Real >::initializeQuad (void) inline private
Definition at line 69 of file ROL_SecondOrderCVaR.hpp.
References ROL::SecondOrderCVaR< Real >::alpha_, ROL::SpectralRisk< Real >::buildMixedQuantile(), ROL::SecondOrderCVaR< Real >::nQuad_, ROL::SecondOrderCVaR< Real >::plusFunction_, ROL::SecondOrderCVaR< Real >::pts_, ROL::SecondOrderCVaR< Real >::useGauss_, and ROL::SecondOrderCVaR< Real >::wts_.
Referenced by ROL::SecondOrderCVaR< Real >::SecondOrderCVaR(), and ROL::SecondOrderCVaR< Real >::SecondOrderCVaR().
Member Data Documentation
plusFunction_
template<class Real > ROL::Ptr<PlusFunction<Real> > ROL::SecondOrderCVaR< Real >::plusFunction_ private
Definition at line 53 of file ROL_SecondOrderCVaR.hpp.
Referenced by ROL::SecondOrderCVaR< Real >::checkInputs(), ROL::SecondOrderCVaR< Real >::initializeQuad(), and ROL::SecondOrderCVaR< Real >::SecondOrderCVaR().
alpha_
template<class Real > Real ROL::SecondOrderCVaR< Real >::alpha_ private
Definition at line 55 of file ROL_SecondOrderCVaR.hpp.
Referenced by ROL::SecondOrderCVaR< Real >::initializeQuad(), and ROL::SecondOrderCVaR< Real >::SecondOrderCVaR().
nQuad_
template<class Real > int ROL::SecondOrderCVaR< Real >::nQuad_ private
Definition at line 56 of file ROL_SecondOrderCVaR.hpp.
Referenced by ROL::SecondOrderCVaR< Real >::initializeQuad(), and ROL::SecondOrderCVaR< Real >::SecondOrderCVaR().
useGauss_
template<class Real > bool ROL::SecondOrderCVaR< Real >::useGauss_ private
Definition at line 57 of file ROL_SecondOrderCVaR.hpp.
Referenced by ROL::SecondOrderCVaR< Real >::initializeQuad(), and ROL::SecondOrderCVaR< Real >::SecondOrderCVaR().
wts_
template<class Real > std::vector<Real> ROL::SecondOrderCVaR< Real >::wts_ private
Definition at line 59 of file ROL_SecondOrderCVaR.hpp.
Referenced by ROL::SecondOrderCVaR< Real >::initializeQuad().
pts_
template<class Real > std::vector<Real> ROL::SecondOrderCVaR< Real >::pts_ private
Definition at line 60 of file ROL_SecondOrderCVaR.hpp.
Referenced by ROL::SecondOrderCVaR< Real >::initializeQuad().
The documentation for this class was generated from the following file:
ROL_SecondOrderCVaR.hpp