ROL: ROL::SimConstraint< Real > Class Template Reference
ROL::SimConstraint< Real > Class Template Reference
#include <ROL_SimConstraint.hpp>
Public Member Functions
SimConstraint (const Ptr< Constraint_SimOpt< Real > > &con, const Ptr< const Vector< Real > > &z, bool inSolve=false)
void update (const Vector< Real > &u, bool flag=true, int iter=-1) override
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
void update (const Vector< Real > &u, UpdateType type, int iter=-1) override
Update constraint function.
void value (Vector< Real > &c, const Vector< Real > &u, Real &tol) override
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, Real &tol) override
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &u, Real &tol) override
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void applyAdjointHessian (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, Real &tol) override
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &g, Real &tol) override
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
void setParameter (const std::vector< Real > &param) override
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol)
Approximately solves the augmented system
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
Private Attributes
const Ptr< Constraint_SimOpt< Real > > con_
const Ptr< const Vector< Real > > z_
const bool inSolve_
Ptr< Vector< Real > > ijv_
bool init_
Additional Inherited Members
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::SimConstraint< Real >
Definition at line 18 of file ROL_SimConstraint.hpp.
Constructor & Destructor Documentation
SimConstraint()
template<typename Real > ROL::SimConstraint< Real >::SimConstraint (const Ptr< Constraint_SimOpt< Real > > & con, const Ptr< const Vector< Real > > & z, bool inSolve = false)
Definition at line 16 of file ROL_SimConstraint_Def.hpp.
Member Function Documentation
update() [1/2]
template<typename Real > void ROL::SimConstraint< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) override virtual
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 21 of file ROL_SimConstraint_Def.hpp.
update() [2/2]
template<typename Real > void ROL::SimConstraint< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) override virtual
Update constraint function.
This function updates the constraint function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 27 of file ROL_SimConstraint_Def.hpp.
value()
template<typename Real > void ROL::SimConstraint< Real >::value (Vector< Real > & c, const Vector< Real > & x, Real & tol) override virtual
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
Parameters
[out] c is the result of evaluating the constraint operator at x; a constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(x)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{x} \in \mathcal{X}\).
Implements ROL::Constraint< Real >.
Definition at line 33 of file ROL_SimConstraint_Def.hpp.
applyJacobian()
template<typename Real > void ROL::SimConstraint< Real >::applyJacobian (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at x; a constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c'(x)v\), where \(v \in \mathcal{X}\), \(\mathsf{jv} \in \mathcal{C}\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 38 of file ROL_SimConstraint_Def.hpp.
applyAdjointJacobian()
template<typename Real > void ROL::SimConstraint< Real >::applyAdjointJacobian (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at x; a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c'(x)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 43 of file ROL_SimConstraint_Def.hpp.
applyAdjointHessian()
template<typename Real > void ROL::SimConstraint< Real >::applyAdjointHessian (Vector< Real > & ahuv, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
Parameters
[out] ahuv is the result of applying the derivative of the adjoint of the constraint Jacobian at x to vector u in direction v; a dual optimization-space vector
[in] u is the direction vector; a dual constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahuv} = c''(x)(v,\cdot)^*u \), where \(u \in \mathcal{C}^*\), \(v \in \mathcal{X}\), and \(\mathsf{ahuv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation based on the adjoint Jacobian.
Reimplemented from ROL::Constraint< Real >.
Definition at line 48 of file ROL_SimConstraint_Def.hpp.
applyPreconditioner()
template<typename Real > void ROL::SimConstraint< Real >::applyPreconditioner (Vector< Real > & pv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g, Real & tol) override virtual
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
\[ \left[c'(x) \circ R \circ c'(x)^* \circ P(x)\right] v = v \,, \]
where R is the appropriate Riesz map in \(L(\mathcal{X}^*, \mathcal{X})\). It is used by the solveAugmentedSystem method.
Parameters
[out] pv is the result of applying the constraint preconditioner to v at x; a dual constraint-space vector
[in] v is a constraint-space vector
[in] x is the preconditioner argument; an optimization-space vector
[in] g is the preconditioner argument; a dual optimization-space vector, unused
[in,out] tol is a tolerance for inexact evaluations
On return, \(\mathsf{pv} = P(x)v\), where \(v \in \mathcal{C}\), \(\mathsf{pv} \in \mathcal{C}^*\).
The default implementation is the Riesz map in \(L(\mathcal{C}, \mathcal{C}^*)\).
Reimplemented from ROL::Constraint< Real >.
Definition at line 53 of file ROL_SimConstraint_Def.hpp.
References ROL::Vector< Real >::clone(), and ROL::Vector< Real >::dual().
setParameter()
template<typename Real > void ROL::SimConstraint< Real >::setParameter (const std::vector< Real > & param) override virtual
Reimplemented from ROL::Constraint< Real >.
Definition at line 63 of file ROL_SimConstraint_Def.hpp.
References ROL::Constraint< Real >::setParameter().
Member Data Documentation
con_
template<typename Real > const Ptr<Constraint_SimOpt<Real> > ROL::SimConstraint< Real >::con_ private
Definition at line 20 of file ROL_SimConstraint.hpp.
z_
template<typename Real > const Ptr<const Vector<Real> > ROL::SimConstraint< Real >::z_ private
Definition at line 21 of file ROL_SimConstraint.hpp.
inSolve_
template<typename Real > const bool ROL::SimConstraint< Real >::inSolve_ private
Definition at line 22 of file ROL_SimConstraint.hpp.
ijv_
template<typename Real > Ptr<Vector<Real> > ROL::SimConstraint< Real >::ijv_ private
Definition at line 23 of file ROL_SimConstraint.hpp.
init_
template<typename Real > bool ROL::SimConstraint< Real >::init_ private
Definition at line 24 of file ROL_SimConstraint.hpp.
The documentation for this class was generated from the following files:
ROL_SimConstraint.hpp
ROL_SimConstraint_Def.hpp