ROL: ROL::TypeG::StabilizedLCLAlgorithm< Real > Class Template Reference
ROL::TypeG::StabilizedLCLAlgorithm< Real > Class Template Reference
Provides an interface to run general constrained optimization algorithms using Stabilized LCL.
#include <ROL_TypeG_StabilizedLCLAlgorithm.hpp>
Public Member Functions
StabilizedLCLAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout) override
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, std::ostream &outStream=std::cout) override
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void writeHeader (std::ostream &os) const override
Print iterate header.
virtual void writeName (std::ostream &os) const override
Print step name.
virtual void writeOutput (std::ostream &os, const bool print_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeG::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &l, const Vector< Real > &c, ElasticObjective< Real > &alobj, BoundConstraint< Real > &bnd, Constraint< Real > &con, std::ostream &outStream=std::cout)
Private Attributes
const Ptr< Secant< Real > > secant_
ParameterList list_
bool useDefaultInitPen_
bool scaleLagrangian_
Real penaltyUpdate_
Real maxPenaltyParam_
Real sigma_
Real sigmaMax_
Real sigmaUpdate_
Real optIncreaseExponent_
Real optDecreaseExponent_
Real optToleranceInitial_
Real optTolerance_
Real feasIncreaseExponent_
Real feasDecreaseExponent_
Real feasToleranceInitial_
Real feasTolerance_
int maxit_
int subproblemIter_
std::string subStep_
int HessianApprox_
Real outerOptTolerance_
Real outerFeasTolerance_
Real outerStepTolerance_
bool useDefaultScaling_
Real fscale_
Real cscale_
int verbosity_
bool printHeader_
bool hasPolyProj_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeG::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &mul, const Vector< Real > &c)
Protected Attributes inherited from ROL::TypeG::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeG::StabilizedLCLAlgorithm< Real >
Provides an interface to run general constrained optimization algorithms using Stabilized LCL.
Definition at line 28 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Constructor & Destructor Documentation
StabilizedLCLAlgorithm()
template<typename Real > ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 20 of file ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp.
References ROL::TypeG::StabilizedLCLAlgorithm< Real >::cscale_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::feasDecreaseExponent_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::feasIncreaseExponent_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::feasToleranceInitial_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::fscale_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::HessianApprox_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::list_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::maxit_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::maxPenaltyParam_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::optDecreaseExponent_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::optIncreaseExponent_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::optToleranceInitial_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::outerFeasTolerance_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::outerOptTolerance_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::outerStepTolerance_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::penaltyUpdate_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::printHeader_, ROL::TypeG::Algorithm< Real >::reset(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::scaleLagrangian_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::sigma_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::sigmaMax_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::sigmaUpdate_, ROL::TypeG::Algorithm< Real >::state_, ROL::TypeG::Algorithm< Real >::status_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::subStep_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::useDefaultInitPen_, ROL::TypeG::StabilizedLCLAlgorithm< Real >::useDefaultScaling_, and ROL::TypeG::StabilizedLCLAlgorithm< Real >::verbosity_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & l, const Vector< Real > & c, ElasticObjective< Real > & alobj, BoundConstraint< Real > & bnd, Constraint< Real > & con, std::ostream & outStream = std::cout) private
(one+std::pow(state_->searchSize,optDecreaseExponent_)));
(one+std::pow(state_->searchSize,feasDecreaseExponent_)));
Definition at line 67 of file ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::ElasticObjective< Real >::getAugmentedLagrangian(), ROL::ElasticObjective< Real >::getConstraintVec(), ROL::ElasticObjective< Real >::getNumberConstraintEvaluations(), ROL::ElasticObjective< Real >::getNumberFunctionEvaluations(), ROL::ElasticObjective< Real >::getNumberGradientEvaluations(), ROL::ElasticObjective< Real >::getObjectiveGradient(), ROL::ElasticObjective< Real >::getObjectiveValue(), ROL::Initial, ROL::TypeG::Algorithm< Real >::initialize(), ROL::Vector< Real >::norm(), ROL::ElasticObjective< Real >::reset(), ROL::Vector< Real >::set(), and ROL::ElasticObjective< Real >::setScaling().
run() [1/2]
template<typename Real > void ROL::TypeG::StabilizedLCLAlgorithm< Real >::run (Problem< Real > & problem, std::ostream & outStream = std::cout) override virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 159 of file ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp.
References ROL::Problem< Real >::edit(), ROL::Problem< Real >::finalize(), ROL::Problem< Real >::finalizeIteration(), ROL::Problem< Real >::getBoundConstraint(), ROL::Problem< Real >::getConstraint(), ROL::Problem< Real >::getDualOptimizationVector(), ROL::Problem< Real >::getMultiplierVector(), ROL::Problem< Real >::getObjective(), ROL::Problem< Real >::getPrimalOptimizationVector(), ROL::Problem< Real >::getProblemType(), ROL::Problem< Real >::getResidualVector(), and ROL::TYPE_EB.
run() [2/2]
template<typename Real > void ROL::TypeG::StabilizedLCLAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, std::ostream & outStream = std::cout) override virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Implements ROL::TypeG::Algorithm< Real >.
Definition at line 180 of file ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Vector< Real >::axpy(), ROL::Problem< Real >::check(), ROL::Vector< Real >::clone(), ROL::EXITSTATUS_CONVERGED, ROL::Problem< Real >::finalize(), ROL::ElasticObjective< Real >::getAugmentedLagrangian(), ROL::ElasticObjective< Real >::getConstraintVec(), ROL::ElasticObjective< Real >::getNumberConstraintEvaluations(), ROL::ElasticObjective< Real >::getNumberFunctionEvaluations(), ROL::ElasticObjective< Real >::getNumberGradientEvaluations(), ROL::ElasticObjective< Real >::getObjectiveValue(), ROL::Problem< Real >::getPolyhedralProjection(), ROL::Vector< Real >::norm(), ROL::ElasticObjective< Real >::reset(), ROL::Vector< Real >::set(), ROL::Problem< Real >::setProjectionAlgorithm(), and ROL::TypeG::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeG::StabilizedLCLAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 309 of file ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeG::StabilizedLCLAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 348 of file ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeG::StabilizedLCLAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 357 of file ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeG::StabilizedLCLAlgorithm< Real >::secant_ private
Definition at line 30 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
list_
template<typename Real > ParameterList ROL::TypeG::StabilizedLCLAlgorithm< Real >::list_ private
Definition at line 31 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
useDefaultInitPen_
template<typename Real > bool ROL::TypeG::StabilizedLCLAlgorithm< Real >::useDefaultInitPen_ private
Definition at line 33 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
scaleLagrangian_
template<typename Real > bool ROL::TypeG::StabilizedLCLAlgorithm< Real >::scaleLagrangian_ private
Definition at line 34 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
penaltyUpdate_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::penaltyUpdate_ private
Definition at line 35 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
maxPenaltyParam_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::maxPenaltyParam_ private
Definition at line 36 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
sigma_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::sigma_ private
Definition at line 37 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
sigmaMax_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::sigmaMax_ private
Definition at line 38 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
sigmaUpdate_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::sigmaUpdate_ private
Definition at line 39 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
optIncreaseExponent_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::optIncreaseExponent_ private
Definition at line 41 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
optDecreaseExponent_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::optDecreaseExponent_ private
Definition at line 42 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
optToleranceInitial_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::optToleranceInitial_ private
Definition at line 43 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
optTolerance_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::optTolerance_ private
Definition at line 44 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
feasIncreaseExponent_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::feasIncreaseExponent_ private
Definition at line 46 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
feasDecreaseExponent_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::feasDecreaseExponent_ private
Definition at line 47 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
feasToleranceInitial_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::feasToleranceInitial_ private
Definition at line 48 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
feasTolerance_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::feasTolerance_ private
Definition at line 49 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
maxit_
template<typename Real > int ROL::TypeG::StabilizedLCLAlgorithm< Real >::maxit_ private
Definition at line 51 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
subproblemIter_
template<typename Real > int ROL::TypeG::StabilizedLCLAlgorithm< Real >::subproblemIter_ private
Definition at line 52 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
subStep_
template<typename Real > std::string ROL::TypeG::StabilizedLCLAlgorithm< Real >::subStep_ private
Definition at line 53 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
HessianApprox_
template<typename Real > int ROL::TypeG::StabilizedLCLAlgorithm< Real >::HessianApprox_ private
Definition at line 54 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
outerOptTolerance_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::outerOptTolerance_ private
Definition at line 55 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
outerFeasTolerance_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::outerFeasTolerance_ private
Definition at line 56 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
outerStepTolerance_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::outerStepTolerance_ private
Definition at line 57 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
useDefaultScaling_
template<typename Real > bool ROL::TypeG::StabilizedLCLAlgorithm< Real >::useDefaultScaling_ private
Definition at line 59 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
fscale_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::fscale_ private
Definition at line 60 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
cscale_
template<typename Real > Real ROL::TypeG::StabilizedLCLAlgorithm< Real >::cscale_ private
Definition at line 61 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
verbosity_
template<typename Real > int ROL::TypeG::StabilizedLCLAlgorithm< Real >::verbosity_ private
Definition at line 63 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
printHeader_
template<typename Real > bool ROL::TypeG::StabilizedLCLAlgorithm< Real >::printHeader_ private
Definition at line 64 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
hasPolyProj_
template<typename Real > bool ROL::TypeG::StabilizedLCLAlgorithm< Real >::hasPolyProj_ private
Definition at line 65 of file ROL_TypeG_StabilizedLCLAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeG_StabilizedLCLAlgorithm.hpp
ROL_TypeG_StabilizedLCLAlgorithm_Def.hpp