ROL: ROL::Newton_U< Real > Class Template Reference
ROL::Newton_U< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with Newton's method globalized using line search.
#include <ROL_Newton_U.hpp>
Public Member Functions
Newton_U ()
void compute (Vector< Real > &s, Real &snorm, Real &sdotg, int &iter, int &flag, const Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj) override
std::string printName (void) const override
Public Member Functions inherited from ROL::DescentDirection_U< Real >
virtual ~DescentDirection_U ()
virtual void initialize (const Vector< Real > &x, const Vector< Real > &g)
virtual void update (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &gold, const Vector< Real > &gnew, const Real snorm, const int iter)
Detailed Description
template<typename Real>
class ROL::Newton_U< Real >
Provides the interface to compute optimization steps with Newton's method globalized using line search.
Definition at line 25 of file ROL_Newton_U.hpp.
Constructor & Destructor Documentation
Newton_U()
template<typename Real > ROL::Newton_U< Real >::Newton_U () inline
Definition at line 27 of file ROL_Newton_U.hpp.
Member Function Documentation
compute()
template<typename Real > void ROL::Newton_U< Real >::compute (Vector< Real > & s, Real & snorm, Real & sdotg, int & iter, int & flag, const Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj) inline override virtual
Implements ROL::DescentDirection_U< Real >.
Definition at line 29 of file ROL_Newton_U.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::dual(), ROL::Objective< Real >::invHessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
printName()
template<typename Real > std::string ROL::Newton_U< Real >::printName (void) const inline override virtual
Reimplemented from ROL::DescentDirection_U< Real >.
Definition at line 47 of file ROL_Newton_U.hpp.
The documentation for this class was generated from the following file:
ROL_Newton_U.hpp