ROL: ROL::ZOO::Objective_PoissonInversion< Real > Class Template Reference
ROL::ZOO::Objective_PoissonInversion< Real > Class Template Reference
Poisson material inversion.
#include <ROL_PoissonInversion.hpp>
Public Member Functions
Objective_PoissonInversion (uint nz=32, Real alpha=1.e-4)
Real reg_value (const Vector< Real > &z)
void reg_gradient (Vector< Real > &g, const Vector< Real > &z)
void reg_hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &z)
void apply_mass (Vector< Real > &Mf, const Vector< Real > &f)
void solve_poisson (Vector< Real > &u, const Vector< Real > &z, Vector< Real > &b)
Real evaluate_target (Real x)
void apply_linearized_control_operator (Vector< Real > &Bd, const Vector< Real > &z, const Vector< Real > &d, const Vector< Real > &u)
void apply_transposed_linearized_control_operator (Vector< Real > &Bd, const Vector< Real > &z, const Vector< Real > &d, const Vector< Real > &u)
void apply_transposed_linearized_control_operator_2 (Vector< Real > &Bd, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &d, const Vector< Real > &u)
void solve_state_equation (Vector< Real > &u, const Vector< Real > &z)
void solve_adjoint_equation (Vector< Real > &p, const Vector< Real > &u, const Vector< Real > &z)
void solve_state_sensitivity_equation (Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z)
void solve_adjoint_sensitivity_equation (Vector< Real > &q, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &p, const Vector< Real > &u, const Vector< Real > &z)
Real value (const Vector< Real > &z, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &z, Real &tol)
Compute gradient.
void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Types
typedef std::vector< Real > vector
typedef Vector< Real > V
typedef StdVector< Real > SV
typedef vector::size_type uint
Private Member Functions
ROL::Ptr< const vector > getVector (const V &x)
ROL::Ptr< vector > getVector (V &x)
Private Attributes
uint nu_
uint nz_
Real hu_
Real hz_
Real alpha_
Real eps_
int reg_type_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::ZOO::Objective_PoissonInversion< Real >
Poisson material inversion.
Definition at line 34 of file ROL_PoissonInversion.hpp.
Member Typedef Documentation
vector
template<class Real > typedef std::vector<Real> ROL::ZOO::Objective_PoissonInversion< Real >::vector private
Definition at line 36 of file ROL_PoissonInversion.hpp.
V
template<class Real > typedef Vector<Real> ROL::ZOO::Objective_PoissonInversion< Real >::V private
Definition at line 37 of file ROL_PoissonInversion.hpp.
SV
template<class Real > typedef StdVector<Real> ROL::ZOO::Objective_PoissonInversion< Real >::SV private
Definition at line 38 of file ROL_PoissonInversion.hpp.
uint
template<class Real > typedef vector::size_type ROL::ZOO::Objective_PoissonInversion< Real >::uint private
Definition at line 40 of file ROL_PoissonInversion.hpp.
Constructor & Destructor Documentation
Objective_PoissonInversion()
template<class Real > ROL::ZOO::Objective_PoissonInversion< Real >::Objective_PoissonInversion (uint nz = 32, Real alpha = 1.e-4) inline
Definition at line 67 of file ROL_PoissonInversion.hpp.
Member Function Documentation
getVector() [1/2]
template<class Real > ROL::Ptr< const vector > ROL::ZOO::Objective_PoissonInversion< Real >::getVector (const V & x) inline private
Definition at line 54 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::getVector().
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::apply_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_mass(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator_2(), ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::invHessVec(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_value(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson().
getVector() [2/2]
template<class Real > ROL::Ptr< vector > ROL::ZOO::Objective_PoissonInversion< Real >::getVector (V & x) inline private
Definition at line 59 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::getVector().
reg_value()
template<class Real > Real ROL::ZOO::Objective_PoissonInversion< Real >::reg_value (const Vector< Real > & z) inline
Definition at line 72 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::alpha_, ROL::ZOO::Objective_PoissonInversion< Real >::eps_, ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hz_, ROL::ZOO::Objective_PoissonInversion< Real >::nz_, and ROL::ZOO::Objective_PoissonInversion< Real >::reg_type_.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::value().
reg_gradient()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient (Vector< Real > & g, const Vector< Real > & z) inline
Definition at line 94 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::alpha_, ROL::ZOO::Objective_PoissonInversion< Real >::eps_, ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hz_, ROL::ZOO::Objective_PoissonInversion< Real >::nz_, ROL::ZOO::Objective_PoissonInversion< Real >::reg_type_, ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::gradient().
reg_hessVec()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & z) inline
Definition at line 133 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::alpha_, ROL::ZOO::Objective_PoissonInversion< Real >::eps_, ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hz_, ROL::ZOO::Objective_PoissonInversion< Real >::nz_, ROL::ZOO::Objective_PoissonInversion< Real >::reg_type_, ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
apply_mass()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::apply_mass (Vector< Real > & Mf, const Vector< Real > & f) inline
Definition at line 180 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hu_, and ROL::ZOO::Objective_PoissonInversion< Real >::nu_.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_sensitivity_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::value().
solve_poisson()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson (Vector< Real > & u, const Vector< Real > & z, Vector< Real > & b) inline
Definition at line 199 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hu_, ROL::ZOO::Objective_PoissonInversion< Real >::nu_, and ROL::Vector< Real >::set().
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_sensitivity_equation(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_sensitivity_equation().
evaluate_target()
template<class Real > Real ROL::ZOO::Objective_PoissonInversion< Real >::evaluate_target (Real x) inline
Definition at line 226 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::value().
apply_linearized_control_operator()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::apply_linearized_control_operator (Vector< Real > & Bd, const Vector< Real > & z, const Vector< Real > & d, const Vector< Real > & u) inline
Definition at line 230 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hu_, and ROL::ZOO::Objective_PoissonInversion< Real >::nu_.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_sensitivity_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_sensitivity_equation().
apply_transposed_linearized_control_operator()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator (Vector< Real > & Bd, const Vector< Real > & z, const Vector< Real > & d, const Vector< Real > & u) inline
Definition at line 256 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hu_, and ROL::ZOO::Objective_PoissonInversion< Real >::nz_.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::gradient().
apply_transposed_linearized_control_operator_2()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator_2 (Vector< Real > & Bd, const Vector< Real > & z, const Vector< Real > & v, const Vector< Real > & d, const Vector< Real > & u) inline
Definition at line 278 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hu_, and ROL::ZOO::Objective_PoissonInversion< Real >::nz_.
solve_state_equation()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_equation (Vector< Real > & u, const Vector< Real > & z) inline
Definition at line 301 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::hu_, ROL::ZOO::Objective_PoissonInversion< Real >::nu_, and ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson().
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::gradient(), and ROL::ZOO::Objective_PoissonInversion< Real >::value().
solve_adjoint_equation()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation (Vector< Real > & p, const Vector< Real > & u, const Vector< Real > & z) inline
Definition at line 327 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::apply_mass(), ROL::ZOO::Objective_PoissonInversion< Real >::evaluate_target(), ROL::ZOO::Objective_PoissonInversion< Real >::getVector(), ROL::ZOO::Objective_PoissonInversion< Real >::hu_, ROL::ZOO::Objective_PoissonInversion< Real >::nu_, and ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson().
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::gradient().
solve_state_sensitivity_equation()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_sensitivity_equation (Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z) inline
Definition at line 344 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::apply_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::nu_, and ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson().
solve_adjoint_sensitivity_equation()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_sensitivity_equation (Vector< Real > & q, const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & p, const Vector< Real > & u, const Vector< Real > & z) inline
Definition at line 353 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::apply_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_mass(), ROL::StdVector< Real, Element >::axpy(), ROL::ZOO::Objective_PoissonInversion< Real >::nu_, and ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson().
value()
template<class Real > Real ROL::ZOO::Objective_PoissonInversion< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 367 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::apply_mass(), ROL::StdVector< Real, Element >::clone(), ROL::ZOO::Objective_PoissonInversion< Real >::evaluate_target(), ROL::ZOO::Objective_PoissonInversion< Real >::hu_, ROL::ZOO::Objective_PoissonInversion< Real >::nu_, ROL::ZOO::Objective_PoissonInversion< Real >::reg_value(), and ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_equation().
gradient()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 391 of file ROL_PoissonInversion.hpp.
References ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::nu_, ROL::ZOO::Objective_PoissonInversion< Real >::nz_, ROL::Vector< Real >::plus(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_equation().
invHessVec()
template<class Real > void ROL::ZOO::Objective_PoissonInversion< Real >::invHessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 456 of file ROL_PoissonInversion.hpp.
References dim, and ROL::ZOO::Objective_PoissonInversion< Real >::getVector().
Member Data Documentation
nu_
template<class Real > uint ROL::ZOO::Objective_PoissonInversion< Real >::nu_ private
Definition at line 43 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::apply_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_mass(), ROL::ZOO::Objective_PoissonInversion< Real >::gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_sensitivity_equation(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_equation(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_sensitivity_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::value().
nz_
template<class Real > uint ROL::ZOO::Objective_PoissonInversion< Real >::nz_ private
Definition at line 44 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator_2(), ROL::ZOO::Objective_PoissonInversion< Real >::gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), and ROL::ZOO::Objective_PoissonInversion< Real >::reg_value().
hu_
template<class Real > Real ROL::ZOO::Objective_PoissonInversion< Real >::hu_ private
Definition at line 46 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::apply_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_mass(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator(), ROL::ZOO::Objective_PoissonInversion< Real >::apply_transposed_linearized_control_operator_2(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_equation(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_poisson(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_state_equation(), and ROL::ZOO::Objective_PoissonInversion< Real >::value().
hz_
template<class Real > Real ROL::ZOO::Objective_PoissonInversion< Real >::hz_ private
Definition at line 47 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), and ROL::ZOO::Objective_PoissonInversion< Real >::reg_value().
alpha_
template<class Real > Real ROL::ZOO::Objective_PoissonInversion< Real >::alpha_ private
Definition at line 49 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), and ROL::ZOO::Objective_PoissonInversion< Real >::reg_value().
eps_
template<class Real > Real ROL::ZOO::Objective_PoissonInversion< Real >::eps_ private
Definition at line 51 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), and ROL::ZOO::Objective_PoissonInversion< Real >::reg_value().
reg_type_
template<class Real > int ROL::ZOO::Objective_PoissonInversion< Real >::reg_type_ private
Definition at line 52 of file ROL_PoissonInversion.hpp.
Referenced by ROL::ZOO::Objective_PoissonInversion< Real >::reg_gradient(), ROL::ZOO::Objective_PoissonInversion< Real >::reg_hessVec(), and ROL::ZOO::Objective_PoissonInversion< Real >::reg_value().
The documentation for this class was generated from the following file:
ROL_PoissonInversion.hpp