ROL: ROL::PH_RiskObjective< Real > Class Template Reference
ROL::PH_RiskObjective< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface for the progressive hedging risk objective.
#include <ROL_PH_RiskObjective.hpp>
Public Member Functions
PH_RiskObjective (const Ptr< Objective< Real > > &obj, ParameterList &parlist)
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
void setParameter (const std::vector< Real > &param)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
Private Member Functions
void getValue (const Vector< Real > &x, Real &tol)
void getGradient (const Vector< Real > &x, Real &tol)
Ptr< const Vector< Real > > getConstVector (const Vector< Real > &x) const
Ptr< Vector< Real > > getVector (Vector< Real > &x) const
Ptr< const std::vector< Real > > getConstStat (const Vector< Real > &x) const
Ptr< std::vector< Real > > getStat (Vector< Real > &x) const
Private Attributes
const Ptr< Objective< Real > > obj_
Ptr< ExpectationQuad< Real > > quad_
bool isValueComputed_
Real val_
bool isGradientInitialized_
bool isGradientComputed_
Ptr< Vector< Real > > g_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::PH_RiskObjective< Real >
Provides the interface for the progressive hedging risk objective.
Definition at line 25 of file ROL_PH_RiskObjective.hpp.
Constructor & Destructor Documentation
PH_RiskObjective()
template<class Real > ROL::PH_RiskObjective< Real >::PH_RiskObjective (const Ptr< Objective< Real > > & obj, ParameterList & parlist) inline
Definition at line 85 of file ROL_PH_RiskObjective.hpp.
References ROL::PH_RiskObjective< Real >::quad_, ROL::RISKMEASURE_CVAR, ROL::RISKMEASURE_GENMOREAUYOSIDACVAR, ROL::RISKMEASURE_LOGEXPONENTIAL, ROL::RISKMEASURE_LOGQUANTILE, ROL::RISKMEASURE_MOREAUYOSIDACVAR, ROL::RISKMEASURE_SAFETYMARGIN, ROL::RISKMEASURE_SMOOTHEDWORSTCASE, ROL::RISKMEASURE_TRUNCATEDMEAN, and ROL::StringToERiskMeasure().
Member Function Documentation
getValue()
template<class Real > void ROL::PH_RiskObjective< Real >::getValue (const Vector< Real > & x, Real & tol) inline private
Definition at line 37 of file ROL_PH_RiskObjective.hpp.
References ROL::PH_RiskObjective< Real >::isValueComputed_, ROL::PH_RiskObjective< Real >::obj_, and ROL::PH_RiskObjective< Real >::val_.
Referenced by ROL::PH_RiskObjective< Real >::gradient(), ROL::PH_RiskObjective< Real >::hessVec(), and ROL::PH_RiskObjective< Real >::value().
getGradient()
template<class Real > void ROL::PH_RiskObjective< Real >::getGradient (const Vector< Real > & x, Real & tol) inline private
Definition at line 44 of file ROL_PH_RiskObjective.hpp.
References ROL::Vector< Real >::clone(), ROL::Vector< Real >::dual(), ROL::PH_RiskObjective< Real >::g_, ROL::PH_RiskObjective< Real >::isGradientComputed_, ROL::PH_RiskObjective< Real >::isGradientInitialized_, and ROL::PH_RiskObjective< Real >::obj_.
Referenced by ROL::PH_RiskObjective< Real >::gradient(), and ROL::PH_RiskObjective< Real >::hessVec().
getConstVector()
template<class Real > Ptr< const Vector< Real > > ROL::PH_RiskObjective< Real >::getConstVector (const Vector< Real > & x) const inline private
Definition at line 55 of file ROL_PH_RiskObjective.hpp.
References ROL::RiskVector< Real >::getVector().
Referenced by ROL::PH_RiskObjective< Real >::gradient(), ROL::PH_RiskObjective< Real >::hessVec(), ROL::PH_RiskObjective< Real >::update(), and ROL::PH_RiskObjective< Real >::value().
getVector()
template<class Real > Ptr< Vector< Real > > ROL::PH_RiskObjective< Real >::getVector (Vector< Real > & x) const inline private
Definition at line 60 of file ROL_PH_RiskObjective.hpp.
References ROL::RiskVector< Real >::getVector().
Referenced by ROL::PH_RiskObjective< Real >::gradient(), and ROL::PH_RiskObjective< Real >::hessVec().
getConstStat()
template<class Real > Ptr< const std::vector< Real > > ROL::PH_RiskObjective< Real >::getConstStat (const Vector< Real > & x) const inline private
Definition at line 65 of file ROL_PH_RiskObjective.hpp.
References ROL::RiskVector< Real >::getStatistic().
Referenced by ROL::PH_RiskObjective< Real >::gradient(), ROL::PH_RiskObjective< Real >::hessVec(), and ROL::PH_RiskObjective< Real >::value().
getStat()
template<class Real > Ptr< std::vector< Real > > ROL::PH_RiskObjective< Real >::getStat (Vector< Real > & x) const inline private
Definition at line 74 of file ROL_PH_RiskObjective.hpp.
References ROL::RiskVector< Real >::getStatistic().
Referenced by ROL::PH_RiskObjective< Real >::gradient(), and ROL::PH_RiskObjective< Real >::hessVec().
update()
template<class Real > void ROL::PH_RiskObjective< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 120 of file ROL_PH_RiskObjective.hpp.
References ROL::PH_RiskObjective< Real >::getConstVector(), ROL::PH_RiskObjective< Real >::isGradientComputed_, ROL::PH_RiskObjective< Real >::isValueComputed_, and ROL::PH_RiskObjective< Real >::obj_.
value()
template<class Real > Real ROL::PH_RiskObjective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 127 of file ROL_PH_RiskObjective.hpp.
References ROL::PH_RiskObjective< Real >::getConstStat(), ROL::PH_RiskObjective< Real >::getConstVector(), ROL::PH_RiskObjective< Real >::getValue(), ROL::PH_RiskObjective< Real >::quad_, and ROL::PH_RiskObjective< Real >::val_.
gradient()
template<class Real > void ROL::PH_RiskObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 135 of file ROL_PH_RiskObjective.hpp.
References ROL::PH_RiskObjective< Real >::g_, ROL::PH_RiskObjective< Real >::getConstStat(), ROL::PH_RiskObjective< Real >::getConstVector(), ROL::PH_RiskObjective< Real >::getGradient(), ROL::PH_RiskObjective< Real >::getStat(), ROL::PH_RiskObjective< Real >::getValue(), ROL::PH_RiskObjective< Real >::getVector(), ROL::PH_RiskObjective< Real >::quad_, and ROL::PH_RiskObjective< Real >::val_.
hessVec()
template<class Real > void ROL::PH_RiskObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 147 of file ROL_PH_RiskObjective.hpp.
References ROL::PH_RiskObjective< Real >::g_, ROL::PH_RiskObjective< Real >::getConstStat(), ROL::PH_RiskObjective< Real >::getConstVector(), ROL::PH_RiskObjective< Real >::getGradient(), ROL::PH_RiskObjective< Real >::getStat(), ROL::PH_RiskObjective< Real >::getValue(), ROL::PH_RiskObjective< Real >::getVector(), ROL::PH_RiskObjective< Real >::obj_, ROL::PH_RiskObjective< Real >::quad_, and ROL::PH_RiskObjective< Real >::val_.
setParameter()
template<class Real > void ROL::PH_RiskObjective< Real >::setParameter (const std::vector< Real > & param) inline virtual
Reimplemented from ROL::Objective< Real >.
Definition at line 165 of file ROL_PH_RiskObjective.hpp.
References ROL::PH_RiskObjective< Real >::obj_, and ROL::Objective< Real >::setParameter().
Member Data Documentation
obj_
template<class Real > const Ptr<Objective<Real> > ROL::PH_RiskObjective< Real >::obj_ private
Definition at line 27 of file ROL_PH_RiskObjective.hpp.
Referenced by ROL::PH_RiskObjective< Real >::getGradient(), ROL::PH_RiskObjective< Real >::getValue(), ROL::PH_RiskObjective< Real >::hessVec(), ROL::PH_RiskObjective< Real >::setParameter(), and ROL::PH_RiskObjective< Real >::update().
quad_
template<class Real > Ptr<ExpectationQuad<Real> > ROL::PH_RiskObjective< Real >::quad_ private
Definition at line 28 of file ROL_PH_RiskObjective.hpp.
Referenced by ROL::PH_RiskObjective< Real >::gradient(), ROL::PH_RiskObjective< Real >::hessVec(), ROL::PH_RiskObjective< Real >::PH_RiskObjective(), and ROL::PH_RiskObjective< Real >::value().
isValueComputed_
template<class Real > bool ROL::PH_RiskObjective< Real >::isValueComputed_ private
Definition at line 30 of file ROL_PH_RiskObjective.hpp.
Referenced by ROL::PH_RiskObjective< Real >::getValue(), and ROL::PH_RiskObjective< Real >::update().
val_
template<class Real > Real ROL::PH_RiskObjective< Real >::val_ private
Definition at line 31 of file ROL_PH_RiskObjective.hpp.
Referenced by ROL::PH_RiskObjective< Real >::getValue(), ROL::PH_RiskObjective< Real >::gradient(), ROL::PH_RiskObjective< Real >::hessVec(), and ROL::PH_RiskObjective< Real >::value().
isGradientInitialized_
template<class Real > bool ROL::PH_RiskObjective< Real >::isGradientInitialized_ private
Definition at line 33 of file ROL_PH_RiskObjective.hpp.
Referenced by ROL::PH_RiskObjective< Real >::getGradient().
isGradientComputed_
template<class Real > bool ROL::PH_RiskObjective< Real >::isGradientComputed_ private
Definition at line 34 of file ROL_PH_RiskObjective.hpp.
Referenced by ROL::PH_RiskObjective< Real >::getGradient(), and ROL::PH_RiskObjective< Real >::update().
g_
template<class Real > Ptr<Vector<Real> > ROL::PH_RiskObjective< Real >::g_ private
Definition at line 35 of file ROL_PH_RiskObjective.hpp.
Referenced by ROL::PH_RiskObjective< Real >::getGradient(), ROL::PH_RiskObjective< Real >::gradient(), and ROL::PH_RiskObjective< Real >::hessVec().
The documentation for this class was generated from the following file:
ROL_PH_RiskObjective.hpp