ROL: ROL::ZOO::getHS24< Real > Class Template Reference
ROL::ZOO::getHS24< Real > Class Template Reference
#include <ROL_HS24.hpp>
Public Member Functions
getHS24 (void)
Ptr< Objective< Real > > getObjective (void) const
Ptr< Constraint< Real > > getInequalityConstraint (void) const
Ptr< BoundConstraint< Real > > getBoundConstraint (void) const
Ptr< Vector< Real > > getInitialGuess (void) const
Ptr< Vector< Real > > getSolution (const int i=0) const
Ptr< Vector< Real > > getInequalityMultiplier (void) const
Ptr< BoundConstraint< Real > > getSlackBoundConstraint (void) const
Public Member Functions inherited from ROL::TestProblem< Real >
virtual ~TestProblem (void)
TestProblem (void)
virtual int getNumSolutions (void) const
virtual Ptr< Constraint< Real > > getEqualityConstraint (void) const
virtual Ptr< Vector< Real > > getEqualityMultiplier (void) const
void get (Ptr< OptimizationProblem< Real > > &problem, Ptr< Vector< Real > > &x0, std::vector< Ptr< Vector< Real > > > &x) const
Detailed Description
template<class Real>
class ROL::ZOO::getHS24< Real >
Definition at line 135 of file ROL_HS24.hpp.
Constructor & Destructor Documentation
getHS24()
template<class Real > ROL::ZOO::getHS24< Real >::getHS24 (void) inline
Definition at line 137 of file ROL_HS24.hpp.
Member Function Documentation
getObjective()
template<class Real > Ptr< Objective< Real > > ROL::ZOO::getHS24< Real >::getObjective (void) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 139 of file ROL_HS24.hpp.
Referenced by main().
getInequalityConstraint()
template<class Real > Ptr< Constraint< Real > > ROL::ZOO::getHS24< Real >::getInequalityConstraint (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 143 of file ROL_HS24.hpp.
Referenced by main().
getBoundConstraint()
template<class Real > Ptr< BoundConstraint< Real > > ROL::ZOO::getHS24< Real >::getBoundConstraint (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 147 of file ROL_HS24.hpp.
Referenced by main().
getInitialGuess()
template<class Real > Ptr< Vector< Real > > ROL::ZOO::getHS24< Real >::getInitialGuess (void) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 160 of file ROL_HS24.hpp.
Referenced by main().
getSolution()
template<class Real > Ptr< Vector< Real > > ROL::ZOO::getHS24< Real >::getSolution (const int i = 0) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 168 of file ROL_HS24.hpp.
Referenced by main().
getInequalityMultiplier()
template<class Real > Ptr< Vector< Real > > ROL::ZOO::getHS24< Real >::getInequalityMultiplier (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 176 of file ROL_HS24.hpp.
Referenced by main().
getSlackBoundConstraint()
template<class Real > Ptr< BoundConstraint< Real > > ROL::ZOO::getHS24< Real >::getSlackBoundConstraint (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 181 of file ROL_HS24.hpp.
Referenced by main().
The documentation for this class was generated from the following file:
ROL_HS24.hpp