ROL: ROL::TypeB::LinMoreAlgorithm< Real > Class Template Reference
ROL::TypeB::LinMoreAlgorithm< Real > Class Template Reference
Provides an interface to run the trust-region algorithm of Lin and More.
#include <ROL_TypeB_LinMoreAlgorithm.hpp>
Public Member Functions
LinMoreAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Real computeValue (Real inTol, Real &outTol, Real pRed, Real &fold, int iter, const Vector< Real > &x, const Vector< Real > &xold, Objective< Real > &obj)
void computeGradient (const Vector< Real > &x, Vector< Real > &g, Vector< Real > &pwa, Real del, Objective< Real > &obj, bool accept, Real &gtol, Real &gnorm, std::ostream &outStream=std::cout) const
Real dgpstep (Vector< Real > &s, const Vector< Real > &w, const Vector< Real > &x, const Real alpha, std::ostream &outStream=std::cout) const
Real dcauchy (Vector< Real > &s, Real &alpha, Real &q, const Vector< Real > &x, const Vector< Real > &g, const Real del, TrustRegionModel_U< Real > &model, Vector< Real > &dwa, Vector< Real > &dwa1, std::ostream &outStream=std::cout)
Real dprsrch (Vector< Real > &x, Vector< Real > &s, Real &q, const Vector< Real > &g, TrustRegionModel_U< Real > &model, BoundConstraint< Real > &bnd, Vector< Real > &pwa, Vector< Real > &dwa, std::ostream &outStream=std::cout)
Real dtrqsol (const Real xtx, const Real ptp, const Real ptx, const Real del) const
Real dtrpcg (Vector< Real > &w, int &iflag, int &iter, const Vector< Real > &g, const Vector< Real > &x, const Real del, TrustRegionModel_U< Real > &model, BoundConstraint< Real > &bnd, const Real tol, const Real stol, const int itermax, Vector< Real > &p, Vector< Real > &q, Vector< Real > &r, Vector< Real > &t, Vector< Real > &pwa, Vector< Real > &dwa, std::ostream &outStream=std::cout) const
void applyFreeHessian (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, TrustRegionModel_U< Real > &model, BoundConstraint< Real > &bnd, Real &tol, Vector< Real > &pwa) const
void applyFreePrecond (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, TrustRegionModel_U< Real > &model, BoundConstraint< Real > &bnd, Real &tol, Vector< Real > &dwa, Vector< Real > &pwa) const
Private Attributes
Ptr< TrustRegionModel_U< Real > > model_
Container for trust-region model.
Real delMax_
Maximum trust-region radius (default: ROL_INF)
Real eta0_
Step acceptance threshold (default: 0.05)
Real eta1_
Radius decrease threshold (default: 0.05)
Real eta2_
Radius increase threshold (default: 0.9)
Real gamma0_
Radius decrease rate (negative rho) (default: 0.0625)
Real gamma1_
Radius decrease rate (positive rho) (default: 0.25)
Real gamma2_
Radius increase rate (default: 2.5)
Real TRsafe_
Safeguard size for numerically evaluating ratio (default: 1e2)
Real eps_
Safeguard for numerically evaluating ratio.
bool interpRad_
Interpolate the trust-region radius if ratio is negative (default: false)
bool useNM_
int storageNM_
TRUtils::ETRFlag TRflag_
Trust-region exit flag.
int SPflag_
Subproblem solver termination flag.
int SPiter_
Subproblem solver iteration count.
ESecant esec_
Secant type (default: Limited-Memory BFGS)
bool useSecantPrecond_
Flag to use secant as a preconditioner (default: false)
bool useSecantHessVec_
Flag to use secant as Hessian (default: false)
Real tol1_
Absolute tolerance for truncated CG (default: 1e-4)
Real tol2_
Relative tolerance for truncated CG (default: 1e-2)
int maxit_
Maximum number of CG iterations (default: 20)
int minit_
Maximum number of minor (subproblem solve) iterations (default: 10)
Real mu0_
Sufficient decrease parameter (default: 1e-2)
Real spexp_
Relative tolerance exponent for subproblem solve (default: 1, range: [1,2])
int redlim_
Maximum number of Cauchy point reduction steps (default: 10)
int explim_
Maximum number of Cauchy point expansion steps (default: 10)
Real alpha_
Initial Cauchy point step length (default: 1.0)
bool normAlpha_
Normalize initial Cauchy point step length (default: false)
Real interpf_
Backtracking rate for Cauchy point computation (default: 1e-1)
Real extrapf_
Extrapolation rate for Cauchy point computation (default: 1e1)
Real qtol_
Relative tolerance for computed decrease in Cauchy point computation (default: 1-8)
Real interpfPS_
Backtracking rate for projected search (default: 0.5)
int pslim_
Maximum number of projected search steps (default: 20)
std::vector< bool > useInexact_
Real scale0_
Real scale1_
Real scale_
Real omega_
Real force_
int updateIter_
Real forceFactor_
Real gtol_
int nhess_
Number of Hessian applications.
unsigned verbosity_
Output level (default: 0)
bool writeHeader_
Flag to write header at every iteration.
bool hasEcon_
Flag signifies if equality constraints exist.
Ptr< ReducedLinearConstraint< Real > > rcon_
Equality constraint restricted to current active variables.
Ptr< NullSpaceOperator< Real > > ns_
Null space projection onto reduced equality constraint Jacobian.
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::LinMoreAlgorithm< Real >
Provides an interface to run the trust-region algorithm of Lin and More.
Definition at line 27 of file ROL_TypeB_LinMoreAlgorithm.hpp.
Constructor & Destructor Documentation
LinMoreAlgorithm()
template<typename Real > ROL::TypeB::LinMoreAlgorithm< Real >::LinMoreAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 17 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::SECANTMODE_BOTH, ROL::SECANTMODE_FORWARD, ROL::SECANTMODE_INVERSE, and ROL::StringToESecant().
Member Function Documentation
run()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 247 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::Vector< Real >::dual(), ROL::TRUtils::NPOSPREDNEG, ROL::Vector< Real >::plus(), ROL::TRUtils::POSPREDNEG, ROL::BoundConstraint< Real >::pruneActive(), ROL::Revert, ROL::Vector< Real >::set(), ROL::TRUtils::SUCCESS, ROL::TRUtils::TRNAN, ROL::Objective< Real >::update(), ROL::TypeB::Algorithm< Real >::writeExitStatus(), and zero.
Referenced by main().
writeHeader()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 740 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::CG_FLAG_SUCCESS, ROL::CG_FLAG_UNDEFINED, ROL::ECGFlagToString(), ROL::TRUtils::ETRFlagToString(), ROL::NumberToString(), ROL::TRUtils::SUCCESS, and ROL::TRUtils::UNDEFINED.
writeName()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 791 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 798 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
initialize()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) private
Definition at line 93 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Initial, ROL::TypeB::Algorithm< Real >::initialize(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
computeValue()
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::computeValue (Real inTol, Real & outTol, Real pRed, Real & fold, int iter, const Vector< Real > & x, const Vector< Real > & xold, Objective< Real > & obj) private
Definition at line 139 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Trial, ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
computeGradient()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::computeGradient (const Vector< Real > & x, Vector< Real > & g, Vector< Real > & pwa, Real del, Objective< Real > & obj, bool accept, Real & gtol, Real & gnorm, std::ostream & outStream = std::cout) const private
Definition at line 162 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), and ROL::TypeB::Algorithm< Real >::optimalityCriterion().
dgpstep()
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::dgpstep (Vector< Real > & s, const Vector< Real > & w, const Vector< Real > & x, const Real alpha, std::ostream & outStream = std::cout) const private
Definition at line 448 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::norm(), and ROL::Vector< Real >::set().
dcauchy()
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::dcauchy (Vector< Real > & s, Real & alpha, Real & q, const Vector< Real > & x, const Vector< Real > & g, const Real del, TrustRegionModel_U< Real > & model, Vector< Real > & dwa, Vector< Real > & dwa1, std::ostream & outStream = std::cout) private
Definition at line 458 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::dot(), ROL::TrustRegionModel_U< Real >::hessVec(), and ROL::Vector< Real >::set().
dprsrch()
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::dprsrch (Vector< Real > & x, Vector< Real > & s, Real & q, const Vector< Real > & g, TrustRegionModel_U< Real > & model, BoundConstraint< Real > & bnd, Vector< Real > & pwa, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 547 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::dot(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::set(), and zero.
dtrqsol()
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::dtrqsol (const Real xtx, const Real ptp, const Real ptx, const Real del) const private
Definition at line 587 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References zero.
dtrpcg()
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg (Vector< Real > & w, int & iflag, int & iter, const Vector< Real > & g, const Vector< Real > & x, const Real del, TrustRegionModel_U< Real > & model, BoundConstraint< Real > & bnd, const Real tol, const Real stol, const int itermax, Vector< Real > & p, Vector< Real > & q, Vector< Real > & r, Vector< Real > & t, Vector< Real > & pwa, Vector< Real > & dwa, std::ostream & outStream = std::cout) const private
Definition at line 609 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), zero, and ROL::Vector< Real >::zero().
applyFreeHessian()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::applyFreeHessian (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, TrustRegionModel_U< Real > & model, BoundConstraint< Real > & bnd, Real & tol, Vector< Real > & pwa) const private
Definition at line 689 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::BoundConstraint< Real >::pruneActive(), ROL::Vector< Real >::set(), and zero.
applyFreePrecond()
template<typename Real > void ROL::TypeB::LinMoreAlgorithm< Real >::applyFreePrecond (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, TrustRegionModel_U< Real > & model, BoundConstraint< Real > & bnd, Real & tol, Vector< Real > & dwa, Vector< Real > & pwa) const private
Definition at line 710 of file ROL_TypeB_LinMoreAlgorithm_Def.hpp.
References ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::precond(), ROL::BoundConstraint< Real >::pruneActive(), ROL::Vector< Real >::set(), and zero.
Member Data Documentation
model_
template<typename Real > Ptr<TrustRegionModel_U<Real> > ROL::TypeB::LinMoreAlgorithm< Real >::model_ private
Container for trust-region model.
Definition at line 29 of file ROL_TypeB_LinMoreAlgorithm.hpp.
delMax_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::delMax_ private
Maximum trust-region radius (default: ROL_INF)
Definition at line 32 of file ROL_TypeB_LinMoreAlgorithm.hpp.
eta0_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::eta0_ private
Step acceptance threshold (default: 0.05)
Definition at line 33 of file ROL_TypeB_LinMoreAlgorithm.hpp.
eta1_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::eta1_ private
Radius decrease threshold (default: 0.05)
Definition at line 34 of file ROL_TypeB_LinMoreAlgorithm.hpp.
eta2_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::eta2_ private
Radius increase threshold (default: 0.9)
Definition at line 35 of file ROL_TypeB_LinMoreAlgorithm.hpp.
gamma0_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::gamma0_ private
Radius decrease rate (negative rho) (default: 0.0625)
Definition at line 36 of file ROL_TypeB_LinMoreAlgorithm.hpp.
gamma1_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::gamma1_ private
Radius decrease rate (positive rho) (default: 0.25)
Definition at line 37 of file ROL_TypeB_LinMoreAlgorithm.hpp.
gamma2_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::gamma2_ private
Radius increase rate (default: 2.5)
Definition at line 38 of file ROL_TypeB_LinMoreAlgorithm.hpp.
TRsafe_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::TRsafe_ private
Safeguard size for numerically evaluating ratio (default: 1e2)
Definition at line 39 of file ROL_TypeB_LinMoreAlgorithm.hpp.
eps_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::eps_ private
Safeguard for numerically evaluating ratio.
Definition at line 40 of file ROL_TypeB_LinMoreAlgorithm.hpp.
interpRad_
template<typename Real > bool ROL::TypeB::LinMoreAlgorithm< Real >::interpRad_ private
Interpolate the trust-region radius if ratio is negative (default: false)
Definition at line 41 of file ROL_TypeB_LinMoreAlgorithm.hpp.
useNM_
template<typename Real > bool ROL::TypeB::LinMoreAlgorithm< Real >::useNM_ private
Definition at line 44 of file ROL_TypeB_LinMoreAlgorithm.hpp.
storageNM_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::storageNM_ private
Definition at line 45 of file ROL_TypeB_LinMoreAlgorithm.hpp.
TRflag_
template<typename Real > TRUtils::ETRFlag ROL::TypeB::LinMoreAlgorithm< Real >::TRflag_ private
Trust-region exit flag.
Definition at line 48 of file ROL_TypeB_LinMoreAlgorithm.hpp.
SPflag_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::SPflag_ private
Subproblem solver termination flag.
Definition at line 49 of file ROL_TypeB_LinMoreAlgorithm.hpp.
SPiter_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::SPiter_ private
Subproblem solver iteration count.
Definition at line 50 of file ROL_TypeB_LinMoreAlgorithm.hpp.
esec_
template<typename Real > ESecant ROL::TypeB::LinMoreAlgorithm< Real >::esec_ private
Secant type (default: Limited-Memory BFGS)
Definition at line 53 of file ROL_TypeB_LinMoreAlgorithm.hpp.
useSecantPrecond_
template<typename Real > bool ROL::TypeB::LinMoreAlgorithm< Real >::useSecantPrecond_ private
Flag to use secant as a preconditioner (default: false)
Definition at line 54 of file ROL_TypeB_LinMoreAlgorithm.hpp.
useSecantHessVec_
template<typename Real > bool ROL::TypeB::LinMoreAlgorithm< Real >::useSecantHessVec_ private
Flag to use secant as Hessian (default: false)
Definition at line 55 of file ROL_TypeB_LinMoreAlgorithm.hpp.
tol1_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::tol1_ private
Absolute tolerance for truncated CG (default: 1e-4)
Definition at line 58 of file ROL_TypeB_LinMoreAlgorithm.hpp.
tol2_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::tol2_ private
Relative tolerance for truncated CG (default: 1e-2)
Definition at line 59 of file ROL_TypeB_LinMoreAlgorithm.hpp.
maxit_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::maxit_ private
Maximum number of CG iterations (default: 20)
Definition at line 60 of file ROL_TypeB_LinMoreAlgorithm.hpp.
minit_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::minit_ private
Maximum number of minor (subproblem solve) iterations (default: 10)
Definition at line 63 of file ROL_TypeB_LinMoreAlgorithm.hpp.
mu0_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::mu0_ private
Sufficient decrease parameter (default: 1e-2)
Definition at line 64 of file ROL_TypeB_LinMoreAlgorithm.hpp.
spexp_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::spexp_ private
Relative tolerance exponent for subproblem solve (default: 1, range: [1,2])
Definition at line 65 of file ROL_TypeB_LinMoreAlgorithm.hpp.
redlim_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::redlim_ private
Maximum number of Cauchy point reduction steps (default: 10)
Definition at line 66 of file ROL_TypeB_LinMoreAlgorithm.hpp.
explim_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::explim_ private
Maximum number of Cauchy point expansion steps (default: 10)
Definition at line 67 of file ROL_TypeB_LinMoreAlgorithm.hpp.
alpha_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::alpha_ private
Initial Cauchy point step length (default: 1.0)
Definition at line 68 of file ROL_TypeB_LinMoreAlgorithm.hpp.
normAlpha_
template<typename Real > bool ROL::TypeB::LinMoreAlgorithm< Real >::normAlpha_ private
Normalize initial Cauchy point step length (default: false)
Definition at line 69 of file ROL_TypeB_LinMoreAlgorithm.hpp.
interpf_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::interpf_ private
Backtracking rate for Cauchy point computation (default: 1e-1)
Definition at line 70 of file ROL_TypeB_LinMoreAlgorithm.hpp.
extrapf_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::extrapf_ private
Extrapolation rate for Cauchy point computation (default: 1e1)
Definition at line 71 of file ROL_TypeB_LinMoreAlgorithm.hpp.
qtol_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::qtol_ private
Relative tolerance for computed decrease in Cauchy point computation (default: 1-8)
Definition at line 72 of file ROL_TypeB_LinMoreAlgorithm.hpp.
interpfPS_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::interpfPS_ private
Backtracking rate for projected search (default: 0.5)
Definition at line 73 of file ROL_TypeB_LinMoreAlgorithm.hpp.
pslim_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::pslim_ private
Maximum number of projected search steps (default: 20)
Definition at line 74 of file ROL_TypeB_LinMoreAlgorithm.hpp.
useInexact_
template<typename Real > std::vector<bool> ROL::TypeB::LinMoreAlgorithm< Real >::useInexact_ private
Definition at line 77 of file ROL_TypeB_LinMoreAlgorithm.hpp.
scale0_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::scale0_ private
Definition at line 78 of file ROL_TypeB_LinMoreAlgorithm.hpp.
scale1_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::scale1_ private
Definition at line 79 of file ROL_TypeB_LinMoreAlgorithm.hpp.
scale_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::scale_ private
Definition at line 80 of file ROL_TypeB_LinMoreAlgorithm.hpp.
omega_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::omega_ private
Definition at line 81 of file ROL_TypeB_LinMoreAlgorithm.hpp.
force_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::force_ private
Definition at line 82 of file ROL_TypeB_LinMoreAlgorithm.hpp.
updateIter_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::updateIter_ private
Definition at line 83 of file ROL_TypeB_LinMoreAlgorithm.hpp.
forceFactor_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::forceFactor_ private
Definition at line 84 of file ROL_TypeB_LinMoreAlgorithm.hpp.
gtol_
template<typename Real > Real ROL::TypeB::LinMoreAlgorithm< Real >::gtol_ private
Definition at line 85 of file ROL_TypeB_LinMoreAlgorithm.hpp.
nhess_
template<typename Real > int ROL::TypeB::LinMoreAlgorithm< Real >::nhess_ mutable private
Number of Hessian applications.
Definition at line 87 of file ROL_TypeB_LinMoreAlgorithm.hpp.
verbosity_
template<typename Real > unsigned ROL::TypeB::LinMoreAlgorithm< Real >::verbosity_ private
Output level (default: 0)
Definition at line 88 of file ROL_TypeB_LinMoreAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeB::LinMoreAlgorithm< Real >::writeHeader_ private
Flag to write header at every iteration.
Definition at line 89 of file ROL_TypeB_LinMoreAlgorithm.hpp.
hasEcon_
template<typename Real > bool ROL::TypeB::LinMoreAlgorithm< Real >::hasEcon_ private
Flag signifies if equality constraints exist.
Definition at line 91 of file ROL_TypeB_LinMoreAlgorithm.hpp.
rcon_
template<typename Real > Ptr<ReducedLinearConstraint<Real> > ROL::TypeB::LinMoreAlgorithm< Real >::rcon_ private
Equality constraint restricted to current active variables.
Definition at line 92 of file ROL_TypeB_LinMoreAlgorithm.hpp.
ns_
template<typename Real > Ptr<NullSpaceOperator<Real> > ROL::TypeB::LinMoreAlgorithm< Real >::ns_ private
Null space projection onto reduced equality constraint Jacobian.
Definition at line 93 of file ROL_TypeB_LinMoreAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_LinMoreAlgorithm.hpp
ROL_TypeB_LinMoreAlgorithm_Def.hpp