ROL: ROL::BPOE< Real > Class Template Reference
ROL::BPOE< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization
Provides the implementation of the buffered probability of exceedance.
#include <ROL_BPOE.hpp>
Public Member Functions
BPOE (const Real threshold, const Real order=1)
BPOE (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x)
Initialize temporary variables.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Attributes
Real threshold_
Real order_
std::vector< Real > hvec_
ROL::Ptr< Vector< Real > > dualVec1_
ROL::Ptr< Vector< Real > > dualVec2_
bool firstResetBPOE_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::BPOE< Real >
Provides the implementation of the buffered probability of exceedance.
Let \((\Omega,\mathcal{F},\mathbb{P})\) be a complete space. Here, \(\Omega\) is the set of outcomes, \(\mathcal{F}\subseteq 2^\Omega\) is a \(\sigma\)-algebra of events and \(\mathbb{P}:\mathcal{F}\to[0,1]\) is a probability measure. Moreover, let \(\mathcal{X}\) be a class of random variables.
ROL's BPOE class inherits from ROL::RandVarFunctional which is written in a way to exploit parallel sampling.
Definition at line 32 of file ROL_BPOE.hpp.
Constructor & Destructor Documentation
BPOE() [1/2]
template<class Real > ROL::BPOE< Real >::BPOE (const Real threshold, const Real order = 1) inline
Definition at line 57 of file ROL_BPOE.hpp.
References ROL::BPOE< Real >::hvec_.
BPOE() [2/2]
template<class Real > ROL::BPOE< Real >::BPOE (ROL::ParameterList & parlist) inline
Definition at line 62 of file ROL_BPOE.hpp.
References ROL::BPOE< Real >::hvec_, ROL::BPOE< Real >::order_, and ROL::BPOE< Real >::threshold_.
Member Function Documentation
initialize()
template<class Real > void ROL::BPOE< Real >::initialize (const Vector< Real > & x) inline virtual
Initialize temporary variables.
   @param[in]   x  is a vector used for initializing storage
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 69 of file ROL_BPOE.hpp.
References ROL::Vector< Real >::clone(), ROL::Vector< Real >::dual(), ROL::BPOE< Real >::dualVec1_, ROL::BPOE< Real >::dualVec2_, ROL::BPOE< Real >::firstResetBPOE_, ROL::BPOE< Real >::hvec_, and ROL::RandVarFunctional< Real >::initialize().
updateValue()
template<class Real > void ROL::BPOE< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 81 of file ROL_BPOE.hpp.
References ROL::RandVarFunctional< Real >::computeValue(), ROL::BPOE< Real >::order_, ROL::BPOE< Real >::threshold_, ROL::RandVarFunctional< Real >::val_, ROL::RandVarFunctional< Real >::weight_, and zero.
getValue()
template<class Real > Real ROL::BPOE< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 93 of file ROL_BPOE.hpp.
References ROL::BPOE< Real >::order_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateGradient()
template<class Real > void ROL::BPOE< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 102 of file ROL_BPOE.hpp.
References ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::BPOE< Real >::order_, ROL::BPOE< Real >::threshold_, ROL::RandVarFunctional< Real >::val_, ROL::RandVarFunctional< Real >::weight_, and zero.
getGradient()
template<class Real > void ROL::BPOE< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 119 of file ROL_BPOE.hpp.
References ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::BPOE< Real >::order_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::sumAll(), ROL::RandVarFunctional< Real >::val_, zero, and ROL::Vector< Real >::zero().
updateHessVec()
template<class Real > void ROL::BPOE< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 140 of file ROL_BPOE.hpp.
References ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::BPOE< Real >::dualVec1_, ROL::BPOE< Real >::dualVec2_, ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::hv_, ROL::BPOE< Real >::hvec_, ROL::BPOE< Real >::order_, ROL::BPOE< Real >::threshold_, ROL::RandVarFunctional< Real >::weight_, and zero.
getHessVec()
template<class Real > void ROL::BPOE< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 172 of file ROL_BPOE.hpp.
References ROL::Vector< Real >::axpy(), ROL::BPOE< Real >::dualVec1_, ROL::BPOE< Real >::dualVec2_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::hv_, ROL::BPOE< Real >::hvec_, ROL::BPOE< Real >::order_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::sumAll(), and zero.
Member Data Documentation
threshold_
template<class Real > Real ROL::BPOE< Real >::threshold_ private
Definition at line 34 of file ROL_BPOE.hpp.
Referenced by ROL::BPOE< Real >::BPOE(), ROL::BPOE< Real >::updateGradient(), ROL::BPOE< Real >::updateHessVec(), and ROL::BPOE< Real >::updateValue().
order_
template<class Real > Real ROL::BPOE< Real >::order_ private
Definition at line 35 of file ROL_BPOE.hpp.
Referenced by ROL::BPOE< Real >::BPOE(), ROL::BPOE< Real >::getGradient(), ROL::BPOE< Real >::getHessVec(), ROL::BPOE< Real >::getValue(), ROL::BPOE< Real >::updateGradient(), ROL::BPOE< Real >::updateHessVec(), and ROL::BPOE< Real >::updateValue().
hvec_
template<class Real > std::vector<Real> ROL::BPOE< Real >::hvec_ private
Definition at line 37 of file ROL_BPOE.hpp.
Referenced by ROL::BPOE< Real >::BPOE(), ROL::BPOE< Real >::BPOE(), ROL::BPOE< Real >::getHessVec(), ROL::BPOE< Real >::initialize(), and ROL::BPOE< Real >::updateHessVec().
dualVec1_
template<class Real > ROL::Ptr<Vector<Real> > ROL::BPOE< Real >::dualVec1_ private
Definition at line 38 of file ROL_BPOE.hpp.
Referenced by ROL::BPOE< Real >::getHessVec(), ROL::BPOE< Real >::initialize(), and ROL::BPOE< Real >::updateHessVec().
dualVec2_
template<class Real > ROL::Ptr<Vector<Real> > ROL::BPOE< Real >::dualVec2_ private
Definition at line 38 of file ROL_BPOE.hpp.
Referenced by ROL::BPOE< Real >::getHessVec(), ROL::BPOE< Real >::initialize(), and ROL::BPOE< Real >::updateHessVec().
firstResetBPOE_
template<class Real > bool ROL::BPOE< Real >::firstResetBPOE_ private
Definition at line 40 of file ROL_BPOE.hpp.
Referenced by ROL::BPOE< Real >::initialize().
The documentation for this class was generated from the following file:
ROL_BPOE.hpp