ROL: ROL::TypeG::InteriorPointAlgorithm< Real > Class Template Reference
ROL::TypeG::InteriorPointAlgorithm< Real > Class Template Reference
Provides an interface to run the interior point algorithm.
#include <ROL_TypeG_InteriorPointAlgorithm.hpp>
Public Member Functions
InteriorPointAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant_=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, std::ostream &outStream=std::cout) override
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool print_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeG::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &l, const Vector< Real > &c, InteriorPointObjective< Real > &ipobj, BoundConstraint< Real > &bnd, Constraint< Real > &con, Vector< Real > &pwa, Vector< Real > &dwa, std::ostream &outStream=std::cout)
void updateState (const Vector< Real > &x, const Vector< Real > &l, InteriorPointObjective< Real > &ipobj, BoundConstraint< Real > &bnd, Constraint< Real > &con, Vector< Real > &pwa, Vector< Real > &dwa, std::ostream &outStream=std::cout)
Private Attributes
const Ptr< Secant< Real > > secant_
Real mumin_
Real mumax_
Real rho_
bool useLinearDamping_
Real kappaD_
Real gtol_
Real ctol_
Real stol_
Real gtolrate_
Real ctolrate_
Real mingtol_
Real minctol_
ROL::ParameterList list_
int subproblemIter_
std::string stepname_
bool print_
int verbosity_
bool printHeader_
bool hasPolyProj_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeG::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &mul, const Vector< Real > &c)
Protected Attributes inherited from ROL::TypeG::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeG::InteriorPointAlgorithm< Real >
Provides an interface to run the interior point algorithm.
Definition at line 25 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Constructor & Destructor Documentation
InteriorPointAlgorithm()
template<typename Real > ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant_ = nullPtr)
Definition at line 19 of file ROL_TypeG_InteriorPointAlgorithm_Def.hpp.
References ROL::TypeG::InteriorPointAlgorithm< Real >::ctol_, ROL::TypeG::InteriorPointAlgorithm< Real >::ctolrate_, ROL::TypeG::InteriorPointAlgorithm< Real >::gtol_, ROL::TypeG::InteriorPointAlgorithm< Real >::gtolrate_, ROL::TypeG::InteriorPointAlgorithm< Real >::kappaD_, ROL::TypeG::InteriorPointAlgorithm< Real >::list_, ROL::TypeG::InteriorPointAlgorithm< Real >::minctol_, ROL::TypeG::InteriorPointAlgorithm< Real >::mingtol_, ROL::TypeG::InteriorPointAlgorithm< Real >::mumax_, ROL::TypeG::InteriorPointAlgorithm< Real >::mumin_, ROL::TypeG::InteriorPointAlgorithm< Real >::print_, ROL::TypeG::InteriorPointAlgorithm< Real >::printHeader_, ROL::TypeG::Algorithm< Real >::reset(), ROL::TypeG::InteriorPointAlgorithm< Real >::rho_, ROL::TypeG::Algorithm< Real >::state_, ROL::TypeG::Algorithm< Real >::status_, ROL::TypeG::InteriorPointAlgorithm< Real >::stepname_, ROL::TypeG::InteriorPointAlgorithm< Real >::stol_, ROL::TypeG::InteriorPointAlgorithm< Real >::useLinearDamping_, and ROL::TypeG::InteriorPointAlgorithm< Real >::verbosity_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeG::InteriorPointAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & l, const Vector< Real > & c, InteriorPointObjective< Real > & ipobj, BoundConstraint< Real > & bnd, Constraint< Real > & con, Vector< Real > & pwa, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 57 of file ROL_TypeG_InteriorPointAlgorithm_Def.hpp.
References ROL::TypeG::Algorithm< Real >::initialize(), and ROL::BoundConstraint< Real >::projectInterior().
updateState()
template<typename Real > void ROL::TypeG::InteriorPointAlgorithm< Real >::updateState (const Vector< Real > & x, const Vector< Real > & l, InteriorPointObjective< Real > & ipobj, BoundConstraint< Real > & bnd, Constraint< Real > & con, Vector< Real > & pwa, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 85 of file ROL_TypeG_InteriorPointAlgorithm_Def.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Vector< Real >::axpy(), ROL::InteriorPointObjective< Real >::getObjectiveValue(), ROL::InteriorPointObjective< Real >::gradient(), ROL::Initial, ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), ROL::InteriorPointObjective< Real >::update(), ROL::Constraint< Real >::update(), and ROL::Constraint< Real >::value().
run()
template<typename Real > void ROL::TypeG::InteriorPointAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, std::ostream & outStream = std::cout) override virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Implements ROL::TypeG::Algorithm< Real >.
Definition at line 126 of file ROL_TypeG_InteriorPointAlgorithm_Def.hpp.
References ROL::Vector< Real >::clone(), ROL::EXITSTATUS_CONVERGED, ROL::InteriorPointObjective< Real >::updatePenalty(), and ROL::TypeG::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeG::InteriorPointAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 197 of file ROL_TypeG_InteriorPointAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeG::InteriorPointAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 236 of file ROL_TypeG_InteriorPointAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeG::InteriorPointAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 245 of file ROL_TypeG_InteriorPointAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeG::InteriorPointAlgorithm< Real >::secant_ private
Definition at line 27 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
mumin_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::mumin_ private
Definition at line 29 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
mumax_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::mumax_ private
Definition at line 30 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
rho_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::rho_ private
Definition at line 31 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
useLinearDamping_
template<typename Real > bool ROL::TypeG::InteriorPointAlgorithm< Real >::useLinearDamping_ private
Definition at line 32 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
kappaD_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::kappaD_ private
Definition at line 33 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
gtol_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::gtol_ private
Definition at line 34 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
ctol_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::ctol_ private
Definition at line 35 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
stol_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::stol_ private
Definition at line 36 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
gtolrate_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::gtolrate_ private
Definition at line 37 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
ctolrate_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::ctolrate_ private
Definition at line 38 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
mingtol_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::mingtol_ private
Definition at line 39 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
minctol_
template<typename Real > Real ROL::TypeG::InteriorPointAlgorithm< Real >::minctol_ private
Definition at line 40 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
list_
template<typename Real > ROL::ParameterList ROL::TypeG::InteriorPointAlgorithm< Real >::list_ private
Definition at line 42 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
subproblemIter_
template<typename Real > int ROL::TypeG::InteriorPointAlgorithm< Real >::subproblemIter_ private
Definition at line 43 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
stepname_
template<typename Real > std::string ROL::TypeG::InteriorPointAlgorithm< Real >::stepname_ private
Definition at line 45 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
print_
template<typename Real > bool ROL::TypeG::InteriorPointAlgorithm< Real >::print_ private
Definition at line 47 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
verbosity_
template<typename Real > int ROL::TypeG::InteriorPointAlgorithm< Real >::verbosity_ private
Definition at line 48 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
printHeader_
template<typename Real > bool ROL::TypeG::InteriorPointAlgorithm< Real >::printHeader_ private
Definition at line 49 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
hasPolyProj_
template<typename Real > bool ROL::TypeG::InteriorPointAlgorithm< Real >::hasPolyProj_ private
Definition at line 51 of file ROL_TypeG_InteriorPointAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeG_InteriorPointAlgorithm.hpp
ROL_TypeG_InteriorPointAlgorithm_Def.hpp