ROL: ROL::Objective< Real > Class Template Reference
ROL::Objective< Real > Class Template Reference abstract
User Interface » Functional Interface
Provides the interface to evaluate objective functions.
#include <ROL_Objective.hpp>
Public Member Functions
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real value (const Vector< Real > &x, Real &tol)=0
Compute value.
virtual void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Protected Member Functions
const std::vector< Real > getParameter (void) const
Private Attributes
Ptr< Vector< Real > > prim_
Ptr< Vector< Real > > dual_
Ptr< Vector< Real > > basis_
std::vector< Real > param_
Detailed Description
template<typename Real>
class ROL::Objective< Real >
Provides the interface to evaluate objective functions.
Provides the definition of the objective function interface.
ROL's objective function interface is designed for Fr$eacute;chet differentiable functionals \(f:\mathcal{X}\to\mathbb{R}\), where \(\mathcal{X}\) is a Banach space. The basic operator interace, to be implemented by the user, requires:
value – objective function evaluation.
It is strongly recommended that the user additionally overload:
gradient – the objective function gradient – the default is a finite-difference approximation;
hessVec – the action of the Hessian – the default is a finite-difference approximation.
The user may also overload:
update – update the objective function at each new iteration;
dirDeriv – compute the directional derivative – the default is a finite-difference approximation;
invHessVec – the action of the inverse Hessian;
precond – the action of a preconditioner for the Hessian.
Definition at line 44 of file ROL_Objective.hpp.
Constructor & Destructor Documentation
~Objective()
template<typename Real > virtual ROL::Objective< Real >::~Objective () inline virtual
Definition at line 51 of file ROL_Objective.hpp.
Objective()
template<typename Real > ROL::Objective< Real >::Objective () inline
Definition at line 53 of file ROL_Objective.hpp.
Member Function Documentation
update() [1/2]
template<typename Real > virtual void ROL::Objective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented in ROL::TypeP::InexactNewtonAlgorithm< Real >::NewtonObj, ROL::AugmentedLagrangianObjective< Real >, ROL::InteriorPointObjective< Real >, ROL::MoreauYosidaObjective< Real >, ROL::ReducedDynamicObjective< Real >, ROL::ChainRuleObjective< Real >, ROL::Objective_SimOpt< Real >, ROL::StochasticObjective< Real >, ROL::RiskNeutralObjective< Real >, ROL::SimulatedObjective< Real >, ROL::SimulatedObjectiveCVaR< Real >, ROL::FletcherObjectiveBase< Real >, ROL::ElasticObjective< Real >, ROL::ReducedDynamicStationaryControlsObjective< Real >, ROL::NonlinearLeastSquaresObjective< Real >, ROL::AffineTransformObjective< Real >, ROL::CompositeObjective< Real >, ROL::LinearCombinationObjective< Real >, ROL::ObjectiveFromConstraint< Real >, ROL::ScaledObjective< Real >, ROL::SlacklessObjective< Real >, ROL::StdObjective< Real >, ROL::MeanValueObjective< Real >, ROL::RiskLessObjective< Real >, and ROL::Reduced_Objective_SimOpt< Real >.
Definition at line 62 of file ROL_Objective.hpp.
References ROL_UNUSED.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::BundleStep< Real >::compute(), ROL::TypeU::TrustRegionAlgorithm< Real >::computeValue(), ROL::TypeB::LinMoreAlgorithm< Real >::computeValue(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::computeValue(), ROL::TypeP::TrustRegionAlgorithm< Real >::computeValue(), ROL::TypeP::TrustRegionAlgorithm< Real >::dbls(), ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy(), ROL::LineSearch_U< Real >::dirDeriv(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TypeB::LSecantBAlgorithm< Real >::dsrch(), ROL::LineSearch_U< Real >::getInitialAlpha(), ROL::LineSearch< Real >::getInitialAlpha(), ROL::TypeU::BundleAlgorithm< Real >::initialize(), ROL::TypeU::LineSearchAlgorithm< Real >::initialize(), ROL::TypeU::TrustRegionAlgorithm< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::TypeB::ColemanLiAlgorithm< Real >::initialize(), ROL::TypeB::GradientAlgorithm< Real >::initialize(), ROL::TypeB::KelleySachsAlgorithm< Real >::initialize(), ROL::TypeB::LinMoreAlgorithm< Real >::initialize(), ROL::TypeB::LSecantBAlgorithm< Real >::initialize(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::initialize(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::initialize(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeB::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeP::InexactNewtonAlgorithm< Real >::initialize(), ROL::TypeP::iPianoAlgorithm< Real >::initialize(), ROL::TypeP::ProxGradientAlgorithm< Real >::initialize(), ROL::TypeP::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::initialize(), ROL::TypeP::TrustRegionAlgorithm< Real >::initialize(), ROL::CompositeStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::TypeE::CompositeStepAlgorithm< Real >::initialize(), ROL::TrustRegionStep< Real >::initialize(), ROL::PrimalDualActiveSetStep< Real >::initialize(), ROL::Step< Real >::initialize(), ROL::TRUtils::initialRadius(), ROL::BackTracking_U< Real >::run(), ROL::CubicInterp_U< Real >::run(), ROL::IterationScaling_U< Real >::run(), ROL::PathBasedTargetLevel_U< Real >::run(), ROL::BackTracking< Real >::run(), ROL::Bisection< Real >::run(), ROL::CubicInterp< Real >::run(), ROL::GoldenSection< Real >::run(), ROL::IterationScaling< Real >::run(), ROL::PathBasedTargetLevel< Real >::run(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::GradientAlgorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::LinMoreAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeB::SpectralGradientAlgorithm< Real >::run(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::run(), ROL::TypeU::BundleAlgorithm< Real >::run(), ROL::TypeU::LineSearchAlgorithm< Real >::run(), ROL::TypeU::TrustRegionAlgorithm< Real >::run(), ROL::TypeP::InexactNewtonAlgorithm< Real >::run(), ROL::TypeP::iPianoAlgorithm< Real >::run(), ROL::TypeP::ProxGradientAlgorithm< Real >::run(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeP::SpectralGradientAlgorithm< Real >::run(), ROL::TypeP::TrustRegionAlgorithm< Real >::run(), ROL::LineSearch< Real >::status(), ROL::LinearCombinationObjective< Real >::update(), ROL::NewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonStep< Real >::update(), ROL::ProjectedSecantStep< Real >::update(), ROL::GradientStep< Real >::update(), ROL::NewtonStep< Real >::update(), ROL::NonlinearCGStep< Real >::update(), ROL::PrimalDualActiveSetStep< Real >::update(), ROL::SecantStep< Real >::update(), ROL::TrustRegion< Real >::update(), ROL::CompositeStep< Real >::update(), ROL::AugmentedLagrangianStep< Real >::update(), and ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius().
update() [2/2]
template<typename Real > virtual void ROL::Objective< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented in CLExactModel< Real >, Objective_PoissonInversion< Real >, ROL::ConicApproximationModel< Real >, ROL::ConicApproximationModel< Real >, ROL::NonlinearLeastSquaresObjective_Dynamic< Real >, ROL::ReducedDynamicObjective< Real >, ROL::ChainRuleObjective< Real >, ROL::ObjectiveMMA< Real >, ROL::Objective_SimOpt< Real >, ROL::PH_bPOEObjective< Real >, ROL::PH_DeviationObjective< Real >, ROL::PH_ErrorObjective< Real >, ROL::PH_Objective< Real >, ROL::PH_ProbObjective< Real >, ROL::PH_RegretObjective< Real >, ROL::PH_RiskObjective< Real >, ROL::StochasticObjective< Real >, ROL::RiskNeutralObjective< Real >, ROL::SimulatedObjective< Real >, ROL::SimulatedObjectiveCVaR< Real >, ROL::AugmentedLagrangian< Real >, ROL::QuadraticPenalty< Real >, ROL::Reduced_AugmentedLagrangian_SimOpt< Real >, ROL::BoundFletcher< Real >, ROL::Fletcher< Real >, ROL::InteriorPoint::PenalizedObjective< Real >, ROL::InteriorPointPenalty< Real >, ROL::MoreauYosidaPenalty< Real >, ROL::ProjectedObjective< Real >, ROL::ReducedDynamicStationaryControlsObjective< Real >, ROL::NonlinearLeastSquaresObjective< Real >, ROL::AffineTransformObjective< Real >, ROL::CompositeObjective< Real >, ROL::LinearCombinationObjective< Real >, ROL::ObjectiveFromConstraint< Real >, ROL::SlacklessObjective< Real >, ROL::StdObjective< Real >, ROL::MeanValueObjective< Real >, ROL::RiskLessObjective< Real >, and ROL::Reduced_Objective_SimOpt< Real >.
Definition at line 75 of file ROL_Objective.hpp.
References ROL_UNUSED.
value()
template<typename Real > virtual Real ROL::Objective< Real >::value (const Vector< Real > & x, Real & tol) pure virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implemented in CLExactModel< Real >, CLTestObjective< Real >, Objective_BurgersControl< Real >, Objective_PoissonInversion< Real >, ROL::ConicApproximationModel< Real >, ROL::ConicApproximationModel< Real >, ROL::InteriorPoint::MeritFunction< Real >, NullObjective< Real >, Objective_GrossPitaevskii< Real >, Objective_GrossPitaevskii< Real >, ROL::ColemanLiModel< Real >, ROL::KelleySachsModel< Real >, ROL::TrustRegionModel< Real >, ROL::ZOO::Objective_DiodeCircuit< Real >, ROL::TrustRegionModel_U< Real >, ROL::Objective_FSsolver< Real >, Zakharov_Sacado_Objective< Real >, ROL::AugmentedLagrangianObjective< Real >, ROL::InteriorPointObjective< Real >, ROL::MoreauYosidaObjective< Real >, ROL::TypeP::InexactNewtonAlgorithm< Real >::NewtonObj, ROL::NonlinearLeastSquaresObjective_Dynamic< Real >, ROL::ReducedDynamicObjective< Real >, ROL::BallIndicatorObjective< Real >, ROL::ChainRuleObjective< Real >, ROL::l1Objective< Real >, ROL::TypeBIndicatorObjective< Real >, ROL::ObjectiveMMA< Real >, ROL::Objective_SimOpt< Real >, ROL::PH_bPOEObjective< Real >, ROL::PH_DeviationObjective< Real >, ROL::PH_ErrorObjective< Real >, ROL::PH_Objective< Real >, ROL::PH_ProbObjective< Real >, ROL::PH_RegretObjective< Real >, ROL::PH_RiskObjective< Real >, ROL::StochasticObjective< Real >, ROL::RiskNeutralObjective< Real >, ROL::SimulatedObjective< Real >, ROL::SimulatedObjectiveCVaR< Real >, ROL::CDFObjective< Real >, ROL::MomentObjective< Real >, ROL::PointwiseCDFObjective< Real >, ROL::AugmentedLagrangian< Real >, ROL::QuadraticPenalty< Real >, ROL::Reduced_AugmentedLagrangian_SimOpt< Real >, ROL::BoundFletcher< Real >, ROL::Fletcher< Real >, ROL::InteriorPoint::PenalizedObjective< Real >, ROL::InteriorPointPenalty< Real >, ROL::LogBarrierObjective< Real >, ROL::ObjectiveFromBoundConstraint< Real >, ROL::MoreauYosidaPenalty< Real >, ROL::ProjectedObjective< Real >, ROL::ZOO::Objective_Beale< Real >, ROL::ZOO::Objective_BVP< Real >, ROL::ZOO::Objective_FreudensteinRoth< Real >, ROL::ZOO::Objective_HS1< Real >, ROL::ZOO::Objective_HS2< Real >, ROL::ZOO::Objective_HS24< Real >, ROL::ZOO::Objective_HS25< Real >, ROL::ZOO::Objective_HS29< Real >, ROL::ZOO::Objective_HS3< Real >, ROL::ZOO::Objective_HS32< Real >, ROL::ZOO::Objective_HS38< Real >, ROL::ZOO::Objective_HS39< Real >, ROL::ZOO::Objective_HS4< Real >, ROL::ZOO::Objective_HS45< Real >, ROL::ZOO::Objective_HS5< Real >, ROL::ZOO::Objective_LeastSquares< Real >, ROL::ZOO::Minimax1< Real >, ROL::ZOO::Minimax2< Real >, ROL::ZOO::Minimax3< Real >, ROL::ZOO::Objective_ParaboloidCircle< Real, XPrim, XDual >, ROL::ZOO::Objective_Powell< Real >, ROL::ZOO::Objective_Rosenbrock< Real, XPrim, XDual >, ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >, ROL::ZOO::Objective_SumOfSquares< Real >, ROL::ZOO::Objective_Zakharov< Real >, ROL::PQNObjective< Real >, ROL::FletcherObjectiveE< Real >, ROL::ElasticObjective< Real >, ROL::ReducedDynamicStationaryControlsObjective< Real >, ROL::NonlinearLeastSquaresObjective< Real >, ROL::AffineTransformObjective< Real >, ROL::CompositeObjective< Real >, ROL::LinearCombinationObjective< Real >, ROL::LinearObjective< Real >, ROL::ObjectiveFromConstraint< Real >, ROL::QuadraticObjective< Real >, ROL::ScaledObjective< Real >, ROL::SlacklessObjective< Real >, ROL::StdObjective< Real >, ROL::MeanValueObjective< Real >, ROL::RiskLessObjective< Real >, ROL::ZOO::Objective_PoissonControl< Real >, ROL::ZOO::Objective_PoissonInversion< Real >, and ROL::Reduced_Objective_SimOpt< Real >.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::CompositeStep< Real >::compute(), ROL::BundleStep< Real >::compute(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeTrial(), ROL::TypeU::TrustRegionAlgorithm< Real >::computeValue(), ROL::RandVarFunctional< Real >::computeValue(), ROL::TypeB::LinMoreAlgorithm< Real >::computeValue(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::computeValue(), ROL::TypeP::TrustRegionAlgorithm< Real >::computeValue(), ROL::TypeP::TrustRegionAlgorithm< Real >::dbls(), ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy(), ROL::LineSearch_U< Real >::dirDeriv(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TypeB::LSecantBAlgorithm< Real >::dsrch(), ROL::LineSearch_U< Real >::getInitialAlpha(), ROL::LineSearch< Real >::getInitialAlpha(), ROL::TypeU::BundleAlgorithm< Real >::initialize(), ROL::TypeU::LineSearchAlgorithm< Real >::initialize(), ROL::TypeU::TrustRegionAlgorithm< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::TypeB::ColemanLiAlgorithm< Real >::initialize(), ROL::TypeB::GradientAlgorithm< Real >::initialize(), ROL::TypeB::KelleySachsAlgorithm< Real >::initialize(), ROL::TypeB::LinMoreAlgorithm< Real >::initialize(), ROL::TypeB::LSecantBAlgorithm< Real >::initialize(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::initialize(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::initialize(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeB::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeP::InexactNewtonAlgorithm< Real >::initialize(), ROL::TypeP::iPianoAlgorithm< Real >::initialize(), ROL::TypeP::ProxGradientAlgorithm< Real >::initialize(), ROL::TypeP::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::initialize(), ROL::TypeP::TrustRegionAlgorithm< Real >::initialize(), ROL::CompositeStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::TypeE::CompositeStepAlgorithm< Real >::initialize(), ROL::TrustRegionStep< Real >::initialize(), ROL::PrimalDualActiveSetStep< Real >::initialize(), ROL::Step< Real >::initialize(), ROL::TRUtils::initialRadius(), ROL::BackTracking_U< Real >::run(), ROL::CubicInterp_U< Real >::run(), ROL::IterationScaling_U< Real >::run(), ROL::PathBasedTargetLevel_U< Real >::run(), ROL::BackTracking< Real >::run(), ROL::Bisection< Real >::run(), ROL::CubicInterp< Real >::run(), ROL::GoldenSection< Real >::run(), ROL::IterationScaling< Real >::run(), ROL::PathBasedTargetLevel< Real >::run(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::GradientAlgorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeB::SpectralGradientAlgorithm< Real >::run(), ROL::TypeU::BundleAlgorithm< Real >::run(), ROL::TypeU::LineSearchAlgorithm< Real >::run(), ROL::TypeP::InexactNewtonAlgorithm< Real >::run(), ROL::TypeP::iPianoAlgorithm< Real >::run(), ROL::TypeP::ProxGradientAlgorithm< Real >::run(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeP::SpectralGradientAlgorithm< Real >::run(), ROL::NewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonStep< Real >::update(), ROL::ProjectedSecantStep< Real >::update(), ROL::GradientStep< Real >::update(), ROL::NewtonStep< Real >::update(), ROL::NonlinearCGStep< Real >::update(), ROL::PrimalDualActiveSetStep< Real >::update(), ROL::SecantStep< Real >::update(), ROL::TrustRegion< Real >::update(), ROL::CompositeStep< Real >::update(), ROL::FletcherStep< Real >::update(), and ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius().
gradient()
template<typename Real > void ROL::Objective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented in CLExactModel< Real >, CLTestObjective< Real >, Objective_BurgersControl< Real >, Objective_PoissonInversion< Real >, ROL::ConicApproximationModel< Real >, ROL::ConicApproximationModel< Real >, NullObjective< Real >, Objective_GrossPitaevskii< Real >, Objective_GrossPitaevskii< Real >, ROL::ColemanLiModel< Real >, ROL::KelleySachsModel< Real >, ROL::TrustRegionModel< Real >, ROL::ZOO::Objective_DiodeCircuit< Real >, ROL::TrustRegionModel_U< Real >, ROL::NonlinearLeastSquaresObjective_Dynamic< Real >, ROL::Objective_FSsolver< Real >, Zakharov_Sacado_Objective< Real >, ROL::AugmentedLagrangianObjective< Real >, ROL::InteriorPointObjective< Real >, ROL::MoreauYosidaObjective< Real >, ROL::TypeP::InexactNewtonAlgorithm< Real >::NewtonObj, ROL::ReducedDynamicObjective< Real >, ROL::ChainRuleObjective< Real >, ROL::l1Objective< Real >, ROL::ObjectiveMMA< Real >, ROL::Objective_SimOpt< Real >, ROL::PH_bPOEObjective< Real >, ROL::PH_DeviationObjective< Real >, ROL::PH_ErrorObjective< Real >, ROL::PH_Objective< Real >, ROL::PH_ProbObjective< Real >, ROL::PH_RegretObjective< Real >, ROL::PH_RiskObjective< Real >, ROL::StochasticObjective< Real >, ROL::RiskNeutralObjective< Real >, ROL::SimulatedObjective< Real >, ROL::SimulatedObjectiveCVaR< Real >, ROL::CDFObjective< Real >, ROL::MomentObjective< Real >, ROL::PointwiseCDFObjective< Real >, ROL::AugmentedLagrangian< Real >, ROL::QuadraticPenalty< Real >, ROL::Reduced_AugmentedLagrangian_SimOpt< Real >, ROL::BoundFletcher< Real >, ROL::Fletcher< Real >, ROL::InteriorPoint::PenalizedObjective< Real >, ROL::InteriorPointPenalty< Real >, ROL::LogBarrierObjective< Real >, ROL::ObjectiveFromBoundConstraint< Real >, ROL::MoreauYosidaPenalty< Real >, ROL::ProjectedObjective< Real >, ROL::ZOO::Objective_Beale< Real >, ROL::ZOO::Objective_BVP< Real >, ROL::ZOO::Objective_FreudensteinRoth< Real >, ROL::ZOO::Objective_HS1< Real >, ROL::ZOO::Objective_HS2< Real >, ROL::ZOO::Objective_HS24< Real >, ROL::ZOO::Objective_HS25< Real >, ROL::ZOO::Objective_HS29< Real >, ROL::ZOO::Objective_HS3< Real >, ROL::ZOO::Objective_HS32< Real >, ROL::ZOO::Objective_HS38< Real >, ROL::ZOO::Objective_HS39< Real >, ROL::ZOO::Objective_HS4< Real >, ROL::ZOO::Objective_HS45< Real >, ROL::ZOO::Objective_HS5< Real >, ROL::ZOO::Objective_LeastSquares< Real >, ROL::ZOO::Minimax1< Real >, ROL::ZOO::Minimax2< Real >, ROL::ZOO::Minimax3< Real >, ROL::ZOO::Objective_ParaboloidCircle< Real, XPrim, XDual >, ROL::ZOO::Objective_Powell< Real >, ROL::ZOO::Objective_Rosenbrock< Real, XPrim, XDual >, ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >, ROL::ZOO::Objective_SumOfSquares< Real >, ROL::ZOO::Objective_Zakharov< Real >, ROL::PQNObjective< Real >, ROL::FletcherObjectiveE< Real >, ROL::ElasticObjective< Real >, ROL::ReducedDynamicStationaryControlsObjective< Real >, ROL::NonlinearLeastSquaresObjective< Real >, ROL::AffineTransformObjective< Real >, ROL::CompositeObjective< Real >, ROL::LinearCombinationObjective< Real >, ROL::LinearObjective< Real >, ROL::ObjectiveFromConstraint< Real >, ROL::QuadraticObjective< Real >, ROL::ScaledObjective< Real >, ROL::SlacklessObjective< Real >, ROL::ShiftedProxObjective< Real >, ROL::ZeroProxObjective< Real >, ROL::StdObjective< Real >, ROL::MeanValueObjective< Real >, ROL::RiskLessObjective< Real >, ROL::ZOO::Objective_PoissonControl< Real >, ROL::ZOO::Objective_PoissonInversion< Real >, and ROL::Reduced_Objective_SimOpt< Real >.
Definition at line 40 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dot(), ROL::Revert, ROL::Temp, ROL::update(), ROL::value(), zero, and ROL::Vector< Real >::zero().
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::CompositeStep< Real >::compute(), ROL::BundleStep< Real >::compute(), ROL::PrimalDualActiveSetStep< Real >::computeCriticalityMeasure(), ROL::TypeU::TrustRegionAlgorithm< Real >::computeGradient(), ROL::TypeB::LinMoreAlgorithm< Real >::computeGradient(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::computeGradient(), ROL::TypeP::TrustRegionAlgorithm< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeGradient(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeTrial(), ROL::FletcherBase< Real >::getGradient(), ROL::TypeU::BundleAlgorithm< Real >::initialize(), ROL::TypeU::LineSearchAlgorithm< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::TypeB::ColemanLiAlgorithm< Real >::initialize(), ROL::TypeB::GradientAlgorithm< Real >::initialize(), ROL::TypeB::KelleySachsAlgorithm< Real >::initialize(), ROL::TypeB::LSecantBAlgorithm< Real >::initialize(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::initialize(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::initialize(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeB::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeP::InexactNewtonAlgorithm< Real >::initialize(), ROL::TypeP::iPianoAlgorithm< Real >::initialize(), ROL::TypeP::ProxGradientAlgorithm< Real >::initialize(), ROL::TypeP::SpectralGradientAlgorithm< Real >::initialize(), ROL::CompositeStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::TypeE::CompositeStepAlgorithm< Real >::initialize(), ROL::Step< Real >::initialize(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::GradientAlgorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeB::SpectralGradientAlgorithm< Real >::run(), ROL::TypeU::BundleAlgorithm< Real >::run(), ROL::TypeU::LineSearchAlgorithm< Real >::run(), ROL::TypeP::InexactNewtonAlgorithm< Real >::run(), ROL::TypeP::iPianoAlgorithm< Real >::run(), ROL::TypeP::ProxGradientAlgorithm< Real >::run(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeP::SpectralGradientAlgorithm< Real >::run(), ROL::LineSearch< Real >::status(), ROL::NewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonStep< Real >::update(), ROL::ProjectedSecantStep< Real >::update(), ROL::GradientStep< Real >::update(), ROL::NewtonStep< Real >::update(), ROL::NonlinearCGStep< Real >::update(), ROL::SecantStep< Real >::update(), ROL::TrustRegion< Real >::update(), ROL::CompositeStep< Real >::update(), ROL::FletcherStep< Real >::update(), ROL::TrustRegionStep< Real >::updateGradient(), and ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius().
dirDeriv()
template<typename Real > Real ROL::Objective< Real >::dirDeriv (const Vector< Real > & x, const Vector< Real > & d, Real & tol) virtual
Compute directional derivative.
This function returns the directional derivative of the objective function in the \(d\) direction.
Parameters
[in] x is the current iterate.
[in] d is the direction.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented in ROL::l1Objective< Real >, ROL::LogBarrierObjective< Real >, ROL::ProjectedObjective< Real >, ROL::ZOO::Objective_Zakharov< Real >, ROL::SlacklessObjective< Real >, and ROL::StdObjective< Real >.
Definition at line 20 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::clone(), and ROL::Vector< Real >::dual().
Referenced by ROL::StdObjective< Real >::dirDeriv(), and ROL::LineSearch_U< Real >::dirDeriv().
hessVec()
template<typename Real > void ROL::Objective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented in CLExactModel< Real >, CLTestObjective< Real >, Objective_BurgersControl< Real >, Objective_PoissonInversion< Real >, ROL::ConicApproximationModel< Real >, ROL::ConicApproximationModel< Real >, NullObjective< Real >, Objective_GrossPitaevskii< Real >, Objective_GrossPitaevskii< Real >, ROL::ColemanLiModel< Real >, ROL::KelleySachsModel< Real >, ROL::TrustRegionModel< Real >, ROL::ZOO::Objective_DiodeCircuit< Real >, ROL::TrustRegionModel_U< Real >, ROL::NonlinearLeastSquaresObjective_Dynamic< Real >, ROL::Objective_FSsolver< Real >, Zakharov_Sacado_Objective< Real >, ROL::AugmentedLagrangianObjective< Real >, ROL::InteriorPointObjective< Real >, ROL::MoreauYosidaObjective< Real >, ROL::TypeP::InexactNewtonAlgorithm< Real >::NewtonObj, ROL::ReducedDynamicObjective< Real >, ROL::ChainRuleObjective< Real >, ROL::ObjectiveMMA< Real >, ROL::Objective_SimOpt< Real >, ROL::PH_bPOEObjective< Real >, ROL::PH_DeviationObjective< Real >, ROL::PH_ErrorObjective< Real >, ROL::PH_Objective< Real >, ROL::PH_ProbObjective< Real >, ROL::PH_RegretObjective< Real >, ROL::PH_RiskObjective< Real >, ROL::StochasticObjective< Real >, ROL::RiskNeutralObjective< Real >, ROL::SimulatedObjective< Real >, ROL::CDFObjective< Real >, ROL::MomentObjective< Real >, ROL::AugmentedLagrangian< Real >, ROL::QuadraticPenalty< Real >, ROL::Reduced_AugmentedLagrangian_SimOpt< Real >, ROL::BoundFletcher< Real >, ROL::Fletcher< Real >, ROL::InteriorPoint::PenalizedObjective< Real >, ROL::InteriorPointPenalty< Real >, ROL::LogBarrierObjective< Real >, ROL::ObjectiveFromBoundConstraint< Real >, ROL::MoreauYosidaPenalty< Real >, ROL::ProjectedObjective< Real >, ROL::ZOO::Objective_HS24< Real >, ROL::ZOO::Objective_HS29< Real >, ROL::ZOO::Objective_HS32< Real >, ROL::ZOO::Objective_HS39< Real >, ROL::ZOO::Objective_ParaboloidCircle< Real, XPrim, XDual >, ROL::ZOO::Objective_SimpleEqConstrained< Real, XPrim, XDual >, ROL::PQNObjective< Real >, ROL::FletcherObjectiveE< Real >, ROL::ElasticObjective< Real >, ROL::ReducedDynamicStationaryControlsObjective< Real >, ROL::NonlinearLeastSquaresObjective< Real >, ROL::AffineTransformObjective< Real >, ROL::CompositeObjective< Real >, ROL::LinearCombinationObjective< Real >, ROL::LinearObjective< Real >, ROL::ObjectiveFromConstraint< Real >, ROL::QuadraticObjective< Real >, ROL::ScaledObjective< Real >, ROL::SlacklessObjective< Real >, ROL::StdObjective< Real >, ROL::MeanValueObjective< Real >, ROL::RiskLessObjective< Real >, and ROL::Reduced_Objective_SimOpt< Real >.
Definition at line 61 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Revert, ROL::Vector< Real >::scale(), ROL::Temp, ROL::update(), zero, and ROL::Vector< Real >::zero().
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::PrimalDualActiveSetStep< Real >::compute(), ROL::computeDenseHessian(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::computeScaledDenseHessian(), ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), ROL::ReducedDynamicObjective< Real >::hessVec(), ROL::StdObjective< Real >::hessVec(), ROL::Reduced_Objective_SimOpt< Real >::hessVec(), ROL::TrustRegionStep< Real >::initialize(), main(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), and ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem().
invHessVec()
template<typename Real > virtual void ROL::Objective< Real >::invHessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented in ROL::ConicApproximationModel< Real >, ROL::ConicApproximationModel< Real >, ROL::ObjectiveMMA< Real >, ROL::KelleySachsModel< Real >, ROL::TrustRegionModel< Real >, ROL::TrustRegionModel_U< Real >, ROL::ProjectedObjective< Real >, ROL::ZOO::Objective_Beale< Real >, ROL::ZOO::Objective_FreudensteinRoth< Real >, ROL::ZOO::Objective_HS1< Real >, ROL::ZOO::Objective_HS2< Real >, ROL::ZOO::Objective_HS3< Real >, ROL::ZOO::Objective_HS5< Real >, ROL::ZOO::Objective_PoissonInversion< Real >, ROL::ZOO::Objective_Powell< Real >, ROL::ZOO::Objective_Rosenbrock< Real, XPrim, XDual >, ROL::ZOO::Objective_SumOfSquares< Real >, ROL::QuadraticObjective< Real >, ROL::ScaledObjective< Real >, ROL::StdObjective< Real >, ROL::ZOO::Objective_Zakharov< Real >, and ROL::SlacklessObjective< Real >.
Definition at line 131 of file ROL_Objective.hpp.
References ROL_UNUSED.
Referenced by ROL::NewtonStep< Real >::compute(), ROL::ProjectedNewtonStep< Real >::compute(), ROL::Newton_U< Real >::compute(), ROL::TrustRegionStep< Real >::initialize(), and ROL::TrustRegionModel_U< Real >::validate().
precond()
template<typename Real > virtual void ROL::Objective< Real >::precond (Vector< Real > & Pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented in ROL::ConicApproximationModel< Real >, ROL::ConicApproximationModel< Real >, ROL::KelleySachsModel< Real >, ROL::ProjectedObjective< Real >, ROL::TrustRegionModel< Real >, ROL::TrustRegionModel_U< Real >, ROL::NonlinearLeastSquaresObjective_Dynamic< Real >, ROL::StochasticObjective< Real >, ROL::RiskNeutralObjective< Real >, ROL::NonlinearLeastSquaresObjective< Real >, ROL::ScaledObjective< Real >, ROL::SlacklessObjective< Real >, ROL::StdObjective< Real >, ROL::MeanValueObjective< Real >, ROL::RiskLessObjective< Real >, and ROL::Reduced_Objective_SimOpt< Real >.
Definition at line 149 of file ROL_Objective.hpp.
References ROL::Vector< Real >::dual(), ROL_UNUSED, and ROL::Vector< Real >::set().
prox()
template<typename Real > virtual void ROL::Objective< Real >::prox (Vector< Real > & Pv, const Vector< Real > & v, Real t, Real & tol) inline virtual
Compute the proximity operator.
This function returns the proximity operator.
Parameters
[out] Pv is the proximity operator applied to \(v\) (primal optimization vector).
[in] v is the input to the proximity operator (primal optimization vector).
[in] t is the proximity operator parameter (positive scalar).
[in] tol is a tolerance for inexact objective function computation.
Reimplemented in ROL::BallIndicatorObjective< Real >, ROL::l1Objective< Real >, and ROL::TypeBIndicatorObjective< Real >.
Definition at line 163 of file ROL_Objective.hpp.
References ROL_UNUSED.
Referenced by ROL::TypeP::TrustRegionAlgorithm< Real >::dprox(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeP::InexactNewtonAlgorithm< Real >::initialize(), ROL::TypeP::iPianoAlgorithm< Real >::initialize(), ROL::TypeP::ProxGradientAlgorithm< Real >::initialize(), ROL::TypeP::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeP::TrustRegionAlgorithm< Real >::initialize(), ROL::TypeP::Algorithm< Real >::pgstep(), and ROL::TypeP::iPianoAlgorithm< Real >::run().
proxJacVec()
template<typename Real > void ROL::Objective< Real >::proxJacVec (Vector< Real > & Jv, const Vector< Real > & v, const Vector< Real > & x, Real t, Real & tol) virtual
Apply the Jacobian of the proximity operator.
This function applies the Jacobian of the proximity operator.
Parameters
[out] Jv is the Jacobian of the proximity operator at \(x\) applied to \(v\) (primal optimization vector).
[in] v is the direction vector (primal optimization vector).
[in] x is the input to the proximity operator (primal optimization vector).
[in] t is the proximity operator parameter (positive scalar).
[in] tol is a tolerance for inexact objective function computation.
Definition at line 85 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), zero, and ROL::Vector< Real >::zero().
checkGradient() [1/4]
template<typename Real > virtual std::vector< std::vector< Real > > ROL::Objective< Real >::checkGradient (const Vector< Real > & x, const Vector< Real > & d, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline virtual
Finite-difference gradient check.
This function computes a sequence of one-sided finite-difference checks for the gradient.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left| \frac{f(x+td) - f(x)}{t} - \langle \nabla f(x),d\rangle_{\mathcal{X}^*,\mathcal{X}}\right|. \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i f(x+t c_i d) \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] d is a direction vector.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] numSteps is a parameter which dictates the number of finite difference steps.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 204 of file ROL_Objective.hpp.
References ROL::Objective< Real >::checkGradient(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective< Real >::checkGradient(), ROL::Objective< Real >::checkGradient(), and main().
checkGradient() [2/4]
template<typename Real > std::vector< std::vector< Real > > ROL::Objective< Real >::checkGradient (const Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & d, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) virtual
Finite-difference gradient check.
This function computes a sequence of one-sided finite-difference checks for the gradient.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left| \frac{f(x+td) - f(x)}{t} - \langle \nabla f(x),d\rangle_{\mathcal{X}^*,\mathcal{X}}\right|. \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i f(x+t c_i d) \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] g is used to create a temporary gradient vector.
[in] d is a direction vector.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] numSteps is a parameter which dictates the number of finite difference steps.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 107 of file ROL_ObjectiveDef.hpp.
checkGradient() [3/4]
template<typename Real > virtual std::vector< std::vector< Real > > ROL::Objective< Real >::checkGradient (const Vector< Real > & x, const Vector< Real > & d, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline virtual
Finite-difference gradient check with specified step sizes.
This function computes a sequence of one-sided finite-difference checks for the gradient.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left| \frac{f(x+td) - f(x)}{t} - \langle \nabla f(x),d\rangle_{\mathcal{X}^*,\mathcal{X}}\right|. \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i f(x+t c_i d) \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] d is a direction vector.
[in] steps is vector of steps of user-specified size.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 264 of file ROL_Objective.hpp.
References ROL::Objective< Real >::checkGradient(), and ROL::Vector< Real >::dual().
checkGradient() [4/4]
template<typename Real > std::vector< std::vector< Real > > ROL::Objective< Real >::checkGradient (const Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & d, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) virtual
Finite-difference gradient check with specified step sizes.
This function computes a sequence of one-sided finite-difference checks for the gradient.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left| \frac{f(x+td) - f(x)}{t} - \langle \nabla f(x),d\rangle_{\mathcal{X}^*,\mathcal{X}}\right|. \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i f(x+t c_i d) \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] g is used to create a temporary gradient vector.
[in] d is a direction vector.
[in] steps is vector of steps of user-specified size.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 126 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::update(), ROL::value(), and ROL::Finite_Difference_Arrays::weights.
checkHessVec() [1/4]
template<typename Real > virtual std::vector< std::vector< Real > > ROL::Objective< Real >::checkHessVec (const Vector< Real > & x, const Vector< Real > & v, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline virtual
Finite-difference Hessian-applied-to-vector check.
This function computes a sequence of one-sided finite-difference checks for the Hessian.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left\| \frac{\nabla f(x+tv) - \nabla f(x)}{t} - \nabla^2 f(x)v\right\|_{\mathcal{X}^*}, \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i \nabla f(x+t c_i v), \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] v is a direction vector.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] numSteps is a parameter which dictates the number of finite difference steps.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 326 of file ROL_Objective.hpp.
References ROL::Objective< Real >::checkHessVec(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective< Real >::checkHessVec(), ROL::Objective< Real >::checkHessVec(), and main().
checkHessVec() [2/4]
template<typename Real > std::vector< std::vector< Real > > ROL::Objective< Real >::checkHessVec (const Vector< Real > & x, const Vector< Real > & hv, const Vector< Real > & v, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) virtual
Finite-difference Hessian-applied-to-vector check.
This function computes a sequence of one-sided finite-difference checks for the Hessian.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left\| \frac{\nabla f(x+tv) - \nabla f(x)}{t} - \nabla^2 f(x)v\right\|_{\mathcal{X}^*}, \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i \nabla f(x+t c_i v), \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] hv is used to create temporary gradient and Hessian-times-vector vectors.
[in] v is a direction vector.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] numSteps is a parameter which dictates the number of finite difference steps.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 222 of file ROL_ObjectiveDef.hpp.
checkHessVec() [3/4]
template<typename Real > virtual std::vector< std::vector< Real > > ROL::Objective< Real >::checkHessVec (const Vector< Real > & x, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) inline virtual
Finite-difference Hessian-applied-to-vector check with specified step sizes.
This function computes a sequence of one-sided finite-difference checks for the Hessian.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left\| \frac{\nabla f(x+tv) - \nabla f(x)}{t} - \nabla^2 f(x)v\right\|_{\mathcal{X}^*}, \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i \nabla f(x+t c_i v), \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] v is a direction vector.
[in] steps is vector of steps of user-specified size.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 387 of file ROL_Objective.hpp.
References ROL::Objective< Real >::checkHessVec(), and ROL::Vector< Real >::dual().
checkHessVec() [4/4]
template<typename Real > std::vector< std::vector< Real > > ROL::Objective< Real >::checkHessVec (const Vector< Real > & x, const Vector< Real > & hv, const Vector< Real > & v, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) virtual
Finite-difference Hessian-applied-to-vector check with specified step sizes.
This function computes a sequence of one-sided finite-difference checks for the Hessian.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left\| \frac{\nabla f(x+tv) - \nabla f(x)}{t} - \nabla^2 f(x)v\right\|_{\mathcal{X}^*}, \]
if the approximation is first order. More generally, difference approximation is
\[ \frac{1}{t} \sum\limits_{i=1}^m w_i \nabla f(x+t c_i v), \]
where m = order+1, \(w_i\) are the difference weights and \(c_i\) are the difference steps
Parameters
[in] x is an optimization variable.
[in] hv is used to create temporary gradient and Hessian-times-vector vectors.
[in] v is a direction vector.
[in] steps is vector of steps of user-specified size.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] order is the order of the finite difference approximation (1,2,3,4)
Definition at line 241 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::update(), and ROL::Finite_Difference_Arrays::weights.
checkHessSym() [1/2]
template<typename Real > virtual std::vector< Real > ROL::Objective< Real >::checkHessSym (const Vector< Real > & x, const Vector< Real > & v, const Vector< Real > & w, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Hessian symmetry check.
This function checks the symmetry of the Hessian by comparing
\[ \langle \nabla^2f(x)v,w\rangle_{\mathcal{X}^*,\mathcal{X}} \quad\text{and}\quad \langle \nabla^2f(x)w,v\rangle_{\mathcal{X}^*,\mathcal{X}}. \]
Parameters
[in] x is an optimization variable.
[in] v is a direction vector.
[in] w is a direction vector.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
Definition at line 442 of file ROL_Objective.hpp.
References ROL::Objective< Real >::checkHessSym(), and ROL::Vector< Real >::dual().
Referenced by ROL::Objective< Real >::checkHessSym(), and main().
checkHessSym() [2/2]
template<typename Real > std::vector< Real > ROL::Objective< Real >::checkHessSym (const Vector< Real > & x, const Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & w, const bool printToStream = true, std::ostream & outStream = std::cout) virtual
Hessian symmetry check.
This function checks the symmetry of the Hessian by comparing
\[ \langle \nabla^2f(x)v,w\rangle_{\mathcal{X}^*,\mathcal{X}} \quad\text{and}\quad \langle \nabla^2f(x)w,v\rangle_{\mathcal{X}^*,\mathcal{X}}. \]
Parameters
[in] x is an optimization variable.
[in] hv is used to create temporary Hessian-times-vector vectors.
[in] v is a direction vector.
[in] w is a direction vector.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
Definition at line 338 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::clone(), ROL::Temp, and ROL::update().
checkProxJacVec()
template<typename Real > std::vector< std::vector< Real > > ROL::Objective< Real >::checkProxJacVec (const Vector< Real > & x, const Vector< Real > & v, Real t = Real(1), bool printToStream = true, std::ostream & outStream = std::cout, int numSteps = ROL_NUM_CHECKDERIV_STEPS) virtual
Finite-difference proximity operator Jacobian-applied-to-vector check.
This function computes a sequence of one-sided finite-difference checks for the proximity operator Jacobian.
At each step of the sequence, the finite difference step size is decreased. The output compares the error
\[ \left\| \frac{\mathrm{prox}_{t f}(x+tv) - \mathrm{prox}_{t f}(x)}{t} - J_{t f}(x+tv)v\right\|_{\mathcal{X}}, \]
if the approximation is first order. Note that in some cases the proximity operator is semismooth, which motivates the evaluation of \(J_{t f}\) at \(x+tv\).
Parameters
[in] x is an optimization vector.
[in] v is a direction vector.
[in] t is the proximity operator parameter.
[in] printToStream is a flag that turns on/off output.
[out] outStream is the output stream.
[in] numSteps is a parameter which dictates the number of finite difference steps.
Definition at line 389 of file ROL_ObjectiveDef.hpp.
References ROL::Vector< Real >::clone().
getParameter()
template<typename Real > const std::vector< Real > ROL::Objective< Real >::getParameter (void) const inline protected
Definition at line 504 of file ROL_Objective.hpp.
References ROL::Objective< Real >::param_.
Referenced by ROL::RegressionError< Real >::checkSize(), ROL::RegressionError< Real >::gradient(), DiffusionObjective< Real >::gradient_1(), DiffusionObjective< Real >::hessVec_11(), DiffusionObjective< Real >::value(), and ROL::RegressionError< Real >::value().
setParameter()
template<typename Real > virtual void ROL::Objective< Real >::setParameter (const std::vector< Real > & param) inline virtual
Reimplemented in ROL::CompositeObjective_SimOpt< Real >, ROL::LinearCombinationObjective_SimOpt< Real >, ROL::PH_bPOEObjective< Real >, ROL::PH_DeviationObjective< Real >, ROL::PH_ErrorObjective< Real >, ROL::PH_Objective< Real >, ROL::PH_ProbObjective< Real >, ROL::PH_RegretObjective< Real >, ROL::PH_RiskObjective< Real >, ROL::Reduced_AugmentedLagrangian_SimOpt< Real >, ROL::MoreauYosidaPenalty< Real >, ROL::NonlinearLeastSquaresObjective< Real >, ROL::AffineTransformObjective< Real >, ROL::CompositeObjective< Real >, ROL::LinearCombinationObjective< Real >, ROL::ScaledObjective< Real >, ROL::SlacklessObjective< Real >, ROL::Reduced_Objective_SimOpt< Real >, and ROL::RiskLessObjective< Real >.
Definition at line 509 of file ROL_Objective.hpp.
References ROL::Objective< Real >::param_.
Referenced by ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::CompositeObjective_SimOpt< Real >::setParameter(), ROL::LinearCombinationObjective_SimOpt< Real >::setParameter(), ROL::PH_bPOEObjective< Real >::setParameter(), ROL::PH_DeviationObjective< Real >::setParameter(), ROL::PH_ErrorObjective< Real >::setParameter(), ROL::PH_Objective< Real >::setParameter(), ROL::PH_ProbObjective< Real >::setParameter(), ROL::PH_RegretObjective< Real >::setParameter(), ROL::PH_RiskObjective< Real >::setParameter(), ROL::Reduced_AugmentedLagrangian_SimOpt< Real >::setParameter(), ROL::MoreauYosidaPenalty< Real >::setParameter(), ROL::NonlinearLeastSquaresObjective< Real >::setParameter(), ROL::AffineTransformObjective< Real >::setParameter(), ROL::CompositeObjective< Real >::setParameter(), ROL::LinearCombinationObjective< Real >::setParameter(), ROL::ScaledObjective< Real >::setParameter(), ROL::SlacklessObjective< Real >::setParameter(), ROL::Reduced_Objective_SimOpt< Real >::setParameter(), and ROL::RiskLessObjective< Real >::setParameter().
Member Data Documentation
prim_
template<typename Real > Ptr<Vector<Real> > ROL::Objective< Real >::prim_ private
Definition at line 47 of file ROL_Objective.hpp.
dual_
template<typename Real > Ptr<Vector<Real> > ROL::Objective< Real >::dual_ private
Definition at line 47 of file ROL_Objective.hpp.
basis_
template<typename Real > Ptr<Vector<Real> > ROL::Objective< Real >::basis_ private
Definition at line 47 of file ROL_Objective.hpp.
param_
template<typename Real > std::vector<Real> ROL::Objective< Real >::param_ private
Definition at line 501 of file ROL_Objective.hpp.
Referenced by ROL::Objective< Real >::getParameter(), and ROL::Objective< Real >::setParameter().
The documentation for this class was generated from the following files:
ROL_Objective.hpp
ROL_ObjectiveDef.hpp