ROL: ROL::CDFObjective< Real > Class Template Reference
ROL::CDFObjective< Real > Class Template Reference
#include <ROL_CDFObjective.hpp>
Public Member Functions
CDFObjective (const std::vector< ROL::Ptr< Distribution< Real > > > &dist, const ROL::Ptr< BatchManager< Real > > &bman, const Real scale=1.e-2, const bool optProb=true, const bool optAtom=true)
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Member Functions
void initializeQuadrature (void)
Real valueCDF (const int dim, const Real loc, const ProbabilityVector< Real > &prob, const AtomVector< Real > &atom) const
Real gradientCDF (std::vector< Real > &gradx, std::vector< Real > &gradp, const int dim, const Real loc, const ProbabilityVector< Real > &prob, const AtomVector< Real > &atom) const
Real hessVecCDF (std::vector< Real > &hvxx, std::vector< Real > &hvxp, std::vector< Real > &hvpx, std::vector< Real > &gradx, std::vector< Real > &gradp, Real &sumx, Real &sump, const int dim, const Real loc, const ProbabilityVector< Real > &prob, const AtomVector< Real > &atom, const ProbabilityVector< Real > &vprob, const AtomVector< Real > &vatom) const
Private Attributes
ROL::Ptr< BatchManager< Real > > bman_
std::vector< ROL::Ptr< Distribution< Real > > > dist_
std::vector< Real > lowerBound_
std::vector< Real > upperBound_
int dimension_
const Real scale_
const Real sqrt2_
const Real sqrtpi_
const bool optProb_
const bool optAtom_
std::vector< Real > pts_
std::vector< Real > wts_
int numPoints_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::CDFObjective< Real >
Definition at line 23 of file ROL_CDFObjective.hpp.
Constructor & Destructor Documentation
CDFObjective()
template<class Real > ROL::CDFObjective< Real >::CDFObjective (const std::vector< ROL::Ptr< Distribution< Real > > > & dist, const ROL::Ptr< BatchManager< Real > > & bman, const Real scale = 1.e-2, const bool optProb = true, const bool optAtom = true) inline
Definition at line 145 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::dimension_, ROL::CDFObjective< Real >::initializeQuadrature(), ROL::CDFObjective< Real >::lowerBound_, and ROL::CDFObjective< Real >::upperBound_.
Member Function Documentation
initializeQuadrature()
template<class Real > void ROL::CDFObjective< Real >::initializeQuadrature (void) inline private
Definition at line 47 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::numPoints_, ROL::CDFObjective< Real >::pts_, and ROL::CDFObjective< Real >::wts_.
Referenced by ROL::CDFObjective< Real >::CDFObjective().
valueCDF()
template<class Real > Real ROL::CDFObjective< Real >::valueCDF (const int dim, const Real loc, const ProbabilityVector< Real > & prob, const AtomVector< Real > & atom) const inline private
Definition at line 77 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::bman_, dim, ROL::AtomVector< Real >::getAtom(), ROL::ProbabilityVector< Real >::getNumMyAtoms(), ROL::ProbabilityVector< Real >::getProbability(), ROL::CDFObjective< Real >::scale_, and ROL::CDFObjective< Real >::sqrt2_.
Referenced by ROL::CDFObjective< Real >::value().
gradientCDF()
template<class Real > Real ROL::CDFObjective< Real >::gradientCDF (std::vector< Real > & gradx, std::vector< Real > & gradp, const int dim, const Real loc, const ProbabilityVector< Real > & prob, const AtomVector< Real > & atom) const inline private
Definition at line 91 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::bman_, dim, ROL::AtomVector< Real >::getAtom(), ROL::ProbabilityVector< Real >::getNumMyAtoms(), ROL::ProbabilityVector< Real >::getProbability(), ROL::CDFObjective< Real >::scale_, ROL::CDFObjective< Real >::sqrt2_, and ROL::CDFObjective< Real >::sqrtpi_.
Referenced by ROL::CDFObjective< Real >::gradient().
hessVecCDF()
template<class Real > Real ROL::CDFObjective< Real >::hessVecCDF (std::vector< Real > & hvxx, std::vector< Real > & hvxp, std::vector< Real > & hvpx, std::vector< Real > & gradx, std::vector< Real > & gradp, Real & sumx, Real & sump, const int dim, const Real loc, const ProbabilityVector< Real > & prob, const AtomVector< Real > & atom, const ProbabilityVector< Real > & vprob, const AtomVector< Real > & vatom) const inline private
Definition at line 110 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::bman_, dim, ROL::AtomVector< Real >::getAtom(), ROL::ProbabilityVector< Real >::getNumMyAtoms(), ROL::ProbabilityVector< Real >::getProbability(), ROL::CDFObjective< Real >::scale_, ROL::CDFObjective< Real >::sqrt2_, and ROL::CDFObjective< Real >::sqrtpi_.
Referenced by ROL::CDFObjective< Real >::hessVec().
value()
template<class Real > Real ROL::CDFObjective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 161 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::dimension_, ROL::CDFObjective< Real >::dist_, ROL::SROMVector< Real >::getAtomVector(), ROL::SROMVector< Real >::getProbabilityVector(), ROL::CDFObjective< Real >::lowerBound_, ROL::CDFObjective< Real >::numPoints_, ROL::CDFObjective< Real >::pts_, ROL::CDFObjective< Real >::upperBound_, ROL::CDFObjective< Real >::valueCDF(), and ROL::CDFObjective< Real >::wts_.
gradient()
template<class Real > void ROL::CDFObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 180 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::dimension_, ROL::CDFObjective< Real >::dist_, ROL::SROMVector< Real >::getAtomVector(), ROL::SROMVector< Real >::getProbabilityVector(), ROL::CDFObjective< Real >::gradientCDF(), ROL::CDFObjective< Real >::lowerBound_, ROL::CDFObjective< Real >::numPoints_, ROL::CDFObjective< Real >::optAtom_, ROL::CDFObjective< Real >::optProb_, ROL::CDFObjective< Real >::pts_, ROL::AtomVector< Real >::setAtom(), ROL::CDFObjective< Real >::upperBound_, ROL::CDFObjective< Real >::wts_, and ROL::Vector< Real >::zero().
hessVec()
template<class Real > void ROL::CDFObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 218 of file ROL_CDFObjective.hpp.
References ROL::CDFObjective< Real >::dimension_, ROL::CDFObjective< Real >::dist_, ROL::SROMVector< Real >::getAtomVector(), ROL::SROMVector< Real >::getProbabilityVector(), ROL::CDFObjective< Real >::hessVecCDF(), ROL::CDFObjective< Real >::lowerBound_, ROL::CDFObjective< Real >::numPoints_, ROL::CDFObjective< Real >::optAtom_, ROL::CDFObjective< Real >::optProb_, ROL::CDFObjective< Real >::pts_, ROL::AtomVector< Real >::setAtom(), ROL::CDFObjective< Real >::upperBound_, ROL::CDFObjective< Real >::wts_, and ROL::Vector< Real >::zero().
Member Data Documentation
bman_
template<class Real > ROL::Ptr<BatchManager<Real> > ROL::CDFObjective< Real >::bman_ private
Definition at line 26 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradientCDF(), ROL::CDFObjective< Real >::hessVecCDF(), and ROL::CDFObjective< Real >::valueCDF().
dist_
template<class Real > std::vector<ROL::Ptr<Distribution<Real> > > ROL::CDFObjective< Real >::dist_ private
Definition at line 29 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), and ROL::CDFObjective< Real >::value().
lowerBound_
template<class Real > std::vector<Real> ROL::CDFObjective< Real >::lowerBound_ private
Definition at line 30 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::CDFObjective(), ROL::CDFObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), and ROL::CDFObjective< Real >::value().
upperBound_
template<class Real > std::vector<Real> ROL::CDFObjective< Real >::upperBound_ private
Definition at line 31 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::CDFObjective(), ROL::CDFObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), and ROL::CDFObjective< Real >::value().
dimension_
template<class Real > int ROL::CDFObjective< Real >::dimension_ private
Definition at line 32 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::CDFObjective(), ROL::CDFObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), and ROL::CDFObjective< Real >::value().
scale_
template<class Real > const Real ROL::CDFObjective< Real >::scale_ private
Definition at line 34 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradientCDF(), ROL::CDFObjective< Real >::hessVecCDF(), and ROL::CDFObjective< Real >::valueCDF().
sqrt2_
template<class Real > const Real ROL::CDFObjective< Real >::sqrt2_ private
Definition at line 35 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradientCDF(), ROL::CDFObjective< Real >::hessVecCDF(), and ROL::CDFObjective< Real >::valueCDF().
sqrtpi_
template<class Real > const Real ROL::CDFObjective< Real >::sqrtpi_ private
Definition at line 36 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradientCDF(), and ROL::CDFObjective< Real >::hessVecCDF().
optProb_
template<class Real > const bool ROL::CDFObjective< Real >::optProb_ private
Definition at line 38 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradient(), and ROL::CDFObjective< Real >::hessVec().
optAtom_
template<class Real > const bool ROL::CDFObjective< Real >::optAtom_ private
Definition at line 39 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradient(), and ROL::CDFObjective< Real >::hessVec().
pts_
template<class Real > std::vector<Real> ROL::CDFObjective< Real >::pts_ private
Definition at line 41 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), ROL::CDFObjective< Real >::initializeQuadrature(), and ROL::CDFObjective< Real >::value().
wts_
template<class Real > std::vector<Real> ROL::CDFObjective< Real >::wts_ private
Definition at line 42 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), ROL::CDFObjective< Real >::initializeQuadrature(), and ROL::CDFObjective< Real >::value().
numPoints_
template<class Real > int ROL::CDFObjective< Real >::numPoints_ private
Definition at line 45 of file ROL_CDFObjective.hpp.
Referenced by ROL::CDFObjective< Real >::gradient(), ROL::CDFObjective< Real >::hessVec(), ROL::CDFObjective< Real >::initializeQuadrature(), and ROL::CDFObjective< Real >::value().
The documentation for this class was generated from the following file:
ROL_CDFObjective.hpp