ROL: ROL::details::VectorCloneMap< Real, KeyType > Class Template Reference
ROL::details::VectorCloneMap< Real, KeyType > Class Template Reference
#include <ROL_VectorClone.hpp>
Public Member Functions
template<typename... Keys>
VectorCloneMap (Keys &&...keys)
Preallocate keys if desired.
Ptr< Vector< Real > > operator() (const Vector< Real > &x, KeyType key)
Ptr< Vector< Real > > operator() (const Ptr< const Vector< Real > > &x, KeyType key)
Private Member Functions
template<typename First , typename... Rest>
void Constructor_Impl (First first, Rest... rest)
template<typename First >
void Constructor_Impl (First first)
Private Attributes
std::map< KeyType, VectorClone< Real > > clones_
Detailed Description
template<typename Real, typename KeyType = const char*>
class ROL::details::VectorCloneMap< Real, KeyType >
Definition at line 83 of file ROL_VectorClone.hpp.
Constructor & Destructor Documentation
VectorCloneMap()
template<typename Real , typename KeyType = const char*> template<typename... Keys> ROL::details::VectorCloneMap< Real, KeyType >::VectorCloneMap (Keys &&... keys) inline
Preallocate keys if desired.
Definition at line 102 of file ROL_VectorClone.hpp.
References ROL::details::VectorCloneMap< Real, KeyType >::Constructor_Impl().
Member Function Documentation
Constructor_Impl() [1/2]
template<typename Real , typename KeyType = const char*> template<typename First , typename... Rest> void ROL::details::VectorCloneMap< Real, KeyType >::Constructor_Impl (First first, Rest... rest) inline private
Definition at line 88 of file ROL_VectorClone.hpp.
References ROL::details::VectorCloneMap< Real, KeyType >::clones_, and ROL::details::VectorCloneMap< Real, KeyType >::Constructor_Impl().
Referenced by ROL::details::VectorCloneMap< Real, KeyType >::Constructor_Impl(), and ROL::details::VectorCloneMap< Real, KeyType >::VectorCloneMap().
Constructor_Impl() [2/2]
template<typename Real , typename KeyType = const char*> template<typename First > void ROL::details::VectorCloneMap< Real, KeyType >::Constructor_Impl (First first) inline private
Definition at line 94 of file ROL_VectorClone.hpp.
References ROL::details::VectorCloneMap< Real, KeyType >::clones_.
operator()() [1/2]
template<typename Real , typename KeyType = const char*> Ptr< Vector< Real > > ROL::details::VectorCloneMap< Real, KeyType >::operator() (const Vector< Real > & x, KeyType key) inline
Definition at line 106 of file ROL_VectorClone.hpp.
References ROL::details::VectorCloneMap< Real, KeyType >::clones_.
operator()() [2/2]
template<typename Real , typename KeyType = const char*> Ptr< Vector< Real > > ROL::details::VectorCloneMap< Real, KeyType >::operator() (const Ptr< const Vector< Real > > & x, KeyType key) inline
Definition at line 110 of file ROL_VectorClone.hpp.
References ROL::details::VectorCloneMap< Real, KeyType >::clones_.
Member Data Documentation
clones_
template<typename Real , typename KeyType = const char*> std::map<KeyType, VectorClone<Real> > ROL::details::VectorCloneMap< Real, KeyType >::clones_ private
Definition at line 85 of file ROL_VectorClone.hpp.
Referenced by ROL::details::VectorCloneMap< Real, KeyType >::Constructor_Impl(), ROL::details::VectorCloneMap< Real, KeyType >::Constructor_Impl(), ROL::details::VectorCloneMap< Real, KeyType >::operator()(), and ROL::details::VectorCloneMap< Real, KeyType >::operator()().
The documentation for this class was generated from the following file:
ROL_VectorClone.hpp