ROL: ROL::TypeB::QuasiNewtonAlgorithm< Real > Class Template Reference
ROL::TypeB::QuasiNewtonAlgorithm< Real > Class Template Reference
Provides an interface to run the projected secant algorithm.
#include <ROL_TypeB_QuasiNewtonAlgorithm.hpp>
Public Member Functions
QuasiNewtonAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Private Attributes
Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ESecant esec_
Secant type.
std::string secantName_
Secant name.
int maxit_
Maximum number of line search steps (default: 20)
Real rhodec_
Backtracking rate (default: 0.5)
Real c1_
Sufficient Decrease Parameter (default: 1e-4)
Real sigma1_
Lower safeguard for quadratic line search (default: 0.1)
Real sigma2_
Upper safeguard for quadratic line search (default: 0.9)
Real sp_tol1_
Real sp_tol2_
Real sp_tol_min_
std::string algoName_
ParameterList list_
bool hasLEC_
int ls_nfval_
int spgIter_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::QuasiNewtonAlgorithm< Real >
Provides an interface to run the projected secant algorithm.
Definition at line 24 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Constructor & Destructor Documentation
QuasiNewtonAlgorithm()
template<typename Real > ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 25 of file ROL_TypeB_QuasiNewtonAlgorithm_Def.hpp.
References ROL::TypeB::QuasiNewtonAlgorithm< Real >::algoName_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::c1_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::esec_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::list_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::maxit_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::rhodec_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::secant_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::secantName_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::sigma1_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::sigma2_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::sp_tol1_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::sp_tol2_, ROL::TypeB::QuasiNewtonAlgorithm< Real >::sp_tol_min_, ROL::TypeB::Algorithm< Real >::status_, ROL::StringToESecant(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::verbosity_, and ROL::TypeB::QuasiNewtonAlgorithm< Real >::writeHeader_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::QuasiNewtonAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) private
Definition at line 64 of file ROL_TypeB_QuasiNewtonAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeB::Algorithm< Real >::initialize(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeB::QuasiNewtonAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 92 of file ROL_TypeB_QuasiNewtonAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeB::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeB::QuasiNewtonAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 207 of file ROL_TypeB_QuasiNewtonAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeB::QuasiNewtonAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 242 of file ROL_TypeB_QuasiNewtonAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::QuasiNewtonAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 249 of file ROL_TypeB_QuasiNewtonAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > Ptr<Secant<Real> > ROL::TypeB::QuasiNewtonAlgorithm< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 26 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
esec_
template<typename Real > ESecant ROL::TypeB::QuasiNewtonAlgorithm< Real >::esec_ private
Secant type.
Definition at line 27 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
secantName_
template<typename Real > std::string ROL::TypeB::QuasiNewtonAlgorithm< Real >::secantName_ private
Secant name.
Definition at line 28 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
maxit_
template<typename Real > int ROL::TypeB::QuasiNewtonAlgorithm< Real >::maxit_ private
Maximum number of line search steps (default: 20)
Definition at line 30 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
rhodec_
template<typename Real > Real ROL::TypeB::QuasiNewtonAlgorithm< Real >::rhodec_ private
Backtracking rate (default: 0.5)
Definition at line 31 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
c1_
template<typename Real > Real ROL::TypeB::QuasiNewtonAlgorithm< Real >::c1_ private
Sufficient Decrease Parameter (default: 1e-4)
Definition at line 32 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sigma1_
template<typename Real > Real ROL::TypeB::QuasiNewtonAlgorithm< Real >::sigma1_ private
Lower safeguard for quadratic line search (default: 0.1)
Definition at line 33 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sigma2_
template<typename Real > Real ROL::TypeB::QuasiNewtonAlgorithm< Real >::sigma2_ private
Upper safeguard for quadratic line search (default: 0.9)
Definition at line 34 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sp_tol1_
template<typename Real > Real ROL::TypeB::QuasiNewtonAlgorithm< Real >::sp_tol1_ private
Definition at line 35 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sp_tol2_
template<typename Real > Real ROL::TypeB::QuasiNewtonAlgorithm< Real >::sp_tol2_ private
Definition at line 36 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sp_tol_min_
template<typename Real > Real ROL::TypeB::QuasiNewtonAlgorithm< Real >::sp_tol_min_ private
Definition at line 37 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
algoName_
template<typename Real > std::string ROL::TypeB::QuasiNewtonAlgorithm< Real >::algoName_ private
Definition at line 38 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
list_
template<typename Real > ParameterList ROL::TypeB::QuasiNewtonAlgorithm< Real >::list_ private
Definition at line 40 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
hasLEC_
template<typename Real > bool ROL::TypeB::QuasiNewtonAlgorithm< Real >::hasLEC_ private
Definition at line 42 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
ls_nfval_
template<typename Real > int ROL::TypeB::QuasiNewtonAlgorithm< Real >::ls_nfval_ private
Definition at line 43 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
spgIter_
template<typename Real > int ROL::TypeB::QuasiNewtonAlgorithm< Real >::spgIter_ private
Definition at line 43 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeB::QuasiNewtonAlgorithm< Real >::verbosity_ private
Definition at line 44 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
writeHeader_
template<typename Real > bool ROL::TypeB::QuasiNewtonAlgorithm< Real >::writeHeader_ private
Definition at line 45 of file ROL_TypeB_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
The documentation for this class was generated from the following files:
ROL_TypeB_QuasiNewtonAlgorithm.hpp
ROL_TypeB_QuasiNewtonAlgorithm_Def.hpp