ROL: ROL::StochasticObjective< Real > Class Template Reference
ROL::StochasticObjective< Real > Class Template Reference
#include <ROL_StochasticObjective.hpp>
Public Member Functions
virtual ~StochasticObjective ()
StochasticObjective (const Ptr< Objective< Real > > &obj, const Ptr< RandVarFunctional< Real > > &rvf, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler, const Ptr< SampleGenerator< Real > > &hsampler, const bool storage=true, const int comp=0, const int index=0)
StochasticObjective (const Ptr< Objective< Real > > &obj, const Ptr< RandVarFunctional< Real > > &rvf, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler, const bool storage=true, const int comp=0, const int index=0)
StochasticObjective (const Ptr< Objective< Real > > &obj, const Ptr< RandVarFunctional< Real > > &rvf, const Ptr< SampleGenerator< Real > > &sampler, const bool storage=true, const int comp=0, const int index=0)
StochasticObjective (const Ptr< Objective< Real > > &obj, ParameterList &parlist, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler, const Ptr< SampleGenerator< Real > > &hsampler, const int comp=0, const int index=0)
StochasticObjective (const Ptr< Objective< Real > > &obj, ROL::ParameterList &parlist, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler, const int comp=0, const int index=0)
StochasticObjective (const Ptr< Objective< Real > > &obj, ROL::ParameterList &parlist, const Ptr< SampleGenerator< Real > > &sampler, const int comp=0, const int index=0)
Real computeStatistic (const Vector< Real > &x) const
void setIndex (int ind)
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Member Functions
Ptr< const Vector< Real > > getConstVector (const Vector< Real > &x) const
Ptr< Vector< Real > > getVector (Vector< Real > &x) const
Ptr< const std::vector< Real > > getConstStat (const Vector< Real > &x) const
Ptr< std::vector< Real > > getStat (Vector< Real > &x) const
Private Attributes
Ptr< Objective< Real > > obj_
Ptr< RandVarFunctional< Real > > rvf_
Ptr< SampleGenerator< Real > > vsampler_
Ptr< SampleGenerator< Real > > gsampler_
Ptr< SampleGenerator< Real > > hsampler_
const int comp_
int index_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::StochasticObjective< Real >
Definition at line 22 of file ROL_StochasticObjective.hpp.
Constructor & Destructor Documentation
~StochasticObjective()
template<class Real > virtual ROL::StochasticObjective< Real >::~StochasticObjective () inline virtual
Definition at line 65 of file ROL_StochasticObjective.hpp.
StochasticObjective() [1/6]
template<class Real > ROL::StochasticObjective< Real >::StochasticObjective (const Ptr< Objective< Real > > & obj, const Ptr< RandVarFunctional< Real > > & rvf, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler, const Ptr< SampleGenerator< Real > > & hsampler, const bool storage = true, const int comp = 0, const int index = 0) inline
Definition at line 67 of file ROL_StochasticObjective.hpp.
StochasticObjective() [2/6]
template<class Real > ROL::StochasticObjective< Real >::StochasticObjective (const Ptr< Objective< Real > > & obj, const Ptr< RandVarFunctional< Real > > & rvf, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler, const bool storage = true, const int comp = 0, const int index = 0) inline
Definition at line 80 of file ROL_StochasticObjective.hpp.
StochasticObjective() [3/6]
template<class Real > ROL::StochasticObjective< Real >::StochasticObjective (const Ptr< Objective< Real > > & obj, const Ptr< RandVarFunctional< Real > > & rvf, const Ptr< SampleGenerator< Real > > & sampler, const bool storage = true, const int comp = 0, const int index = 0) inline
Definition at line 88 of file ROL_StochasticObjective.hpp.
StochasticObjective() [4/6]
template<class Real > ROL::StochasticObjective< Real >::StochasticObjective (const Ptr< Objective< Real > > & obj, ParameterList & parlist, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler, const Ptr< SampleGenerator< Real > > & hsampler, const int comp = 0, const int index = 0) inline
Definition at line 95 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::rvf_.
StochasticObjective() [5/6]
template<class Real > ROL::StochasticObjective< Real >::StochasticObjective (const Ptr< Objective< Real > > & obj, ROL::ParameterList & parlist, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler, const int comp = 0, const int index = 0) inline
Definition at line 117 of file ROL_StochasticObjective.hpp.
StochasticObjective() [6/6]
template<class Real > ROL::StochasticObjective< Real >::StochasticObjective (const Ptr< Objective< Real > > & obj, ROL::ParameterList & parlist, const Ptr< SampleGenerator< Real > > & sampler, const int comp = 0, const int index = 0) inline
Definition at line 124 of file ROL_StochasticObjective.hpp.
Member Function Documentation
getConstVector()
template<class Real > Ptr< const Vector< Real > > ROL::StochasticObjective< Real >::getConstVector (const Vector< Real > & x) const inline private
Definition at line 36 of file ROL_StochasticObjective.hpp.
References ROL::RiskVector< Real >::getVector().
Referenced by ROL::StochasticObjective< Real >::gradient(), ROL::StochasticObjective< Real >::hessVec(), ROL::StochasticObjective< Real >::update(), ROL::StochasticObjective< Real >::update(), and ROL::StochasticObjective< Real >::value().
getVector()
template<class Real > Ptr< Vector< Real > > ROL::StochasticObjective< Real >::getVector (Vector< Real > & x) const inline private
Definition at line 41 of file ROL_StochasticObjective.hpp.
References ROL::RiskVector< Real >::getVector().
Referenced by ROL::StochasticObjective< Real >::gradient(), and ROL::StochasticObjective< Real >::hessVec().
getConstStat()
template<class Real > Ptr< const std::vector< Real > > ROL::StochasticObjective< Real >::getConstStat (const Vector< Real > & x) const inline private
Definition at line 46 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::comp_, ROL::RiskVector< Real >::getStatistic(), and ROL::StochasticObjective< Real >::index_.
Referenced by ROL::StochasticObjective< Real >::computeStatistic(), ROL::StochasticObjective< Real >::gradient(), ROL::StochasticObjective< Real >::hessVec(), and ROL::StochasticObjective< Real >::value().
getStat()
template<class Real > Ptr< std::vector< Real > > ROL::StochasticObjective< Real >::getStat (Vector< Real > & x) const inline private
Definition at line 55 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::comp_, ROL::RiskVector< Real >::getStatistic(), and ROL::StochasticObjective< Real >::index_.
Referenced by ROL::StochasticObjective< Real >::gradient(), and ROL::StochasticObjective< Real >::hessVec().
computeStatistic()
template<class Real > Real ROL::StochasticObjective< Real >::computeStatistic (const Vector< Real > & x) const inline
Definition at line 130 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::getConstStat(), and ROL::StochasticObjective< Real >::rvf_.
setIndex()
template<class Real > void ROL::StochasticObjective< Real >::setIndex (int ind) inline
Definition at line 135 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::index_.
update() [1/2]
template<class Real > void ROL::StochasticObjective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 139 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::getConstVector(), ROL::StochasticObjective< Real >::gsampler_, ROL::StochasticObjective< Real >::hsampler_, ROL::StochasticObjective< Real >::obj_, ROL::Revert, ROL::StochasticObjective< Real >::rvf_, ROL::Trial, and ROL::StochasticObjective< Real >::vsampler_.
update() [2/2]
template<class Real > void ROL::StochasticObjective< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 153 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::getConstVector(), ROL::StochasticObjective< Real >::gsampler_, ROL::StochasticObjective< Real >::hsampler_, ROL::StochasticObjective< Real >::obj_, ROL::StochasticObjective< Real >::rvf_, and ROL::StochasticObjective< Real >::vsampler_.
value()
template<class Real > Real ROL::StochasticObjective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 167 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::getConstStat(), ROL::StochasticObjective< Real >::getConstVector(), ROL::StochasticObjective< Real >::obj_, ROL::StochasticObjective< Real >::rvf_, and ROL::StochasticObjective< Real >::vsampler_.
gradient()
template<class Real > void ROL::StochasticObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 180 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::getConstStat(), ROL::StochasticObjective< Real >::getConstVector(), ROL::StochasticObjective< Real >::getStat(), ROL::StochasticObjective< Real >::getVector(), ROL::StochasticObjective< Real >::gsampler_, ROL::StochasticObjective< Real >::obj_, ROL::StochasticObjective< Real >::rvf_, and ROL::Vector< Real >::zero().
hessVec()
template<class Real > void ROL::StochasticObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 194 of file ROL_StochasticObjective.hpp.
References ROL::StochasticObjective< Real >::getConstStat(), ROL::StochasticObjective< Real >::getConstVector(), ROL::StochasticObjective< Real >::getStat(), ROL::StochasticObjective< Real >::getVector(), ROL::StochasticObjective< Real >::hsampler_, ROL::StochasticObjective< Real >::obj_, ROL::StochasticObjective< Real >::rvf_, and ROL::Vector< Real >::zero().
precond()
template<class Real > virtual void ROL::StochasticObjective< Real >::precond (Vector< Real > & Pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 211 of file ROL_StochasticObjective.hpp.
References ROL::Vector< Real >::dual(), and ROL::Vector< Real >::set().
Member Data Documentation
obj_
template<class Real > Ptr<Objective<Real> > ROL::StochasticObjective< Real >::obj_ private
Definition at line 25 of file ROL_StochasticObjective.hpp.
Referenced by ROL::StochasticObjective< Real >::gradient(), ROL::StochasticObjective< Real >::hessVec(), ROL::StochasticObjective< Real >::update(), ROL::StochasticObjective< Real >::update(), and ROL::StochasticObjective< Real >::value().
rvf_
template<class Real > Ptr<RandVarFunctional<Real> > ROL::StochasticObjective< Real >::rvf_ private
Definition at line 26 of file ROL_StochasticObjective.hpp.
Referenced by ROL::StochasticObjective< Real >::computeStatistic(), ROL::StochasticObjective< Real >::gradient(), ROL::StochasticObjective< Real >::hessVec(), ROL::StochasticObjective< Real >::StochasticObjective(), ROL::StochasticObjective< Real >::update(), ROL::StochasticObjective< Real >::update(), and ROL::StochasticObjective< Real >::value().
vsampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::StochasticObjective< Real >::vsampler_ private
Definition at line 29 of file ROL_StochasticObjective.hpp.
Referenced by ROL::StochasticObjective< Real >::update(), ROL::StochasticObjective< Real >::update(), and ROL::StochasticObjective< Real >::value().
gsampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::StochasticObjective< Real >::gsampler_ private
Definition at line 30 of file ROL_StochasticObjective.hpp.
Referenced by ROL::StochasticObjective< Real >::gradient(), ROL::StochasticObjective< Real >::update(), and ROL::StochasticObjective< Real >::update().
hsampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::StochasticObjective< Real >::hsampler_ private
Definition at line 31 of file ROL_StochasticObjective.hpp.
Referenced by ROL::StochasticObjective< Real >::hessVec(), ROL::StochasticObjective< Real >::update(), and ROL::StochasticObjective< Real >::update().
comp_
template<class Real > const int ROL::StochasticObjective< Real >::comp_ private
Definition at line 33 of file ROL_StochasticObjective.hpp.
Referenced by ROL::StochasticObjective< Real >::getConstStat(), and ROL::StochasticObjective< Real >::getStat().
index_
template<class Real > int ROL::StochasticObjective< Real >::index_ private
Definition at line 34 of file ROL_StochasticObjective.hpp.
Referenced by ROL::StochasticObjective< Real >::getConstStat(), ROL::StochasticObjective< Real >::getStat(), and ROL::StochasticObjective< Real >::setIndex().
The documentation for this class was generated from the following file:
ROL_StochasticObjective.hpp