ROL: ROL::QuantileRadius< Real > Class Template Reference
ROL::QuantileRadius< Real > Class Template Reference
#include <ROL_QuantileRadius.hpp>
Public Member Functions
QuantileRadius (ROL::ParameterList &parlist)
QuantileRadius (const Real prob, const Real coeff, const Ptr< PlusFunction< Real > > &pf)
void initialize (const Vector< Real > &x) override
Initialize temporary variables.
Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const override
Compute statistic.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal storage for value computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure value.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal risk measure storage for gradient computation.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure (sub)gradient.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal risk measure storage for Hessian-time-a-vector computation.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void setSample (const std::vector< Real > &point, const Real weight)
Private Member Functions
void initializeQR (void)
void checkInputs (void)
Private Attributes
Ptr< PlusFunction< Real > > plusFunction_
Real prob_
Real coeff_
std::vector< Real > vec_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::QuantileRadius< Real >
Definition at line 21 of file ROL_QuantileRadius.hpp.
Constructor & Destructor Documentation
QuantileRadius() [1/2]
template<class Real > ROL::QuantileRadius< Real >::QuantileRadius (ROL::ParameterList & parlist) inline
Definition at line 60 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::checkInputs(), ROL::QuantileRadius< Real >::coeff_, ROL::QuantileRadius< Real >::plusFunction_, and ROL::QuantileRadius< Real >::prob_.
QuantileRadius() [2/2]
template<class Real > ROL::QuantileRadius< Real >::QuantileRadius (const Real prob, const Real coeff, const Ptr< PlusFunction< Real > > & pf) inline
Definition at line 72 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::checkInputs().
Member Function Documentation
initializeQR()
template<class Real > void ROL::QuantileRadius< Real >::initializeQR (void) inline private
Definition at line 42 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::vec_, and zero.
Referenced by ROL::QuantileRadius< Real >::checkInputs().
checkInputs()
template<class Real > void ROL::QuantileRadius< Real >::checkInputs (void) inline private
Definition at line 48 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::coeff_, ROL::QuantileRadius< Real >::initializeQR(), ROL::QuantileRadius< Real >::prob_, and zero.
Referenced by ROL::QuantileRadius< Real >::QuantileRadius(), and ROL::QuantileRadius< Real >::QuantileRadius().
initialize()
template<class Real > void ROL::QuantileRadius< Real >::initialize (const Vector< Real > & x) inline override virtual
Initialize temporary variables.
   @param[in]   x  is a vector used for initializing storage
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 78 of file ROL_QuantileRadius.hpp.
References ROL::RandVarFunctional< Real >::initialize(), and ROL::QuantileRadius< Real >::vec_.
computeStatistic()
template<class Real > Real ROL::QuantileRadius< Real >::computeStatistic (const Ptr< const std::vector< Real > > & xstat) const inline override virtual
Compute statistic.
Parameters
[in] xstat is a ROL::Ptr to a std::vector containing the statistic vector
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 83 of file ROL_QuantileRadius.hpp.
updateValue()
template<class Real > void ROL::QuantileRadius< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline override virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 91 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::coeff_, ROL::RandVarFunctional< Real >::computeValue(), ROL::QuantileRadius< Real >::plusFunction_, ROL::QuantileRadius< Real >::prob_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::QuantileRadius< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline override virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 102 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::coeff_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateGradient()
template<class Real > void ROL::QuantileRadius< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline override virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 112 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::QuantileRadius< Real >::plusFunction_, ROL::QuantileRadius< Real >::prob_, ROL::QuantileRadius< Real >::vec_, and ROL::RandVarFunctional< Real >::weight_.
getGradient()
template<class Real > void ROL::QuantileRadius< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline override virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 127 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::coeff_, ROL::RandVarFunctional< Real >::g_, ROL::SampleGenerator< Real >::sumAll(), and ROL::QuantileRadius< Real >::vec_.
updateHessVec()
template<class Real > void ROL::QuantileRadius< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline override virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 139 of file ROL_QuantileRadius.hpp.
References ROL::QuantileRadius< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::hv_, ROL::QuantileRadius< Real >::plusFunction_, ROL::QuantileRadius< Real >::prob_, ROL::QuantileRadius< Real >::vec_, and ROL::RandVarFunctional< Real >::weight_.
getHessVec()
template<class Real > void ROL::QuantileRadius< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline override virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 160 of file ROL_QuantileRadius.hpp.
References ROL::RandVarFunctional< Real >::hv_, ROL::SampleGenerator< Real >::sumAll(), and ROL::QuantileRadius< Real >::vec_.
Member Data Documentation
plusFunction_
template<class Real > Ptr<PlusFunction<Real> > ROL::QuantileRadius< Real >::plusFunction_ private
Definition at line 23 of file ROL_QuantileRadius.hpp.
Referenced by ROL::QuantileRadius< Real >::QuantileRadius(), ROL::QuantileRadius< Real >::updateGradient(), ROL::QuantileRadius< Real >::updateHessVec(), and ROL::QuantileRadius< Real >::updateValue().
prob_
template<class Real > Real ROL::QuantileRadius< Real >::prob_ private
Definition at line 24 of file ROL_QuantileRadius.hpp.
Referenced by ROL::QuantileRadius< Real >::checkInputs(), ROL::QuantileRadius< Real >::QuantileRadius(), ROL::QuantileRadius< Real >::updateGradient(), ROL::QuantileRadius< Real >::updateHessVec(), and ROL::QuantileRadius< Real >::updateValue().
coeff_
template<class Real > Real ROL::QuantileRadius< Real >::coeff_ private
Definition at line 25 of file ROL_QuantileRadius.hpp.
Referenced by ROL::QuantileRadius< Real >::checkInputs(), ROL::QuantileRadius< Real >::getGradient(), ROL::QuantileRadius< Real >::getValue(), ROL::QuantileRadius< Real >::QuantileRadius(), ROL::QuantileRadius< Real >::updateGradient(), ROL::QuantileRadius< Real >::updateHessVec(), and ROL::QuantileRadius< Real >::updateValue().
vec_
template<class Real > std::vector<Real> ROL::QuantileRadius< Real >::vec_ private
Definition at line 26 of file ROL_QuantileRadius.hpp.
Referenced by ROL::QuantileRadius< Real >::getGradient(), ROL::QuantileRadius< Real >::getHessVec(), ROL::QuantileRadius< Real >::initialize(), ROL::QuantileRadius< Real >::initializeQR(), ROL::QuantileRadius< Real >::updateGradient(), and ROL::QuantileRadius< Real >::updateHessVec().
The documentation for this class was generated from the following file:
ROL_QuantileRadius.hpp