ROL: ROL::Vector_SimOpt< Real > Class Template Reference
ROL::Vector_SimOpt< Real > Class Template Reference
User Interface » Linear Algebra Interface
Defines the linear algebra or vector space interface for simulation-based optimization.
#include <ROL_Vector_SimOpt.hpp>
Public Member Functions
Vector_SimOpt (const ROL::Ptr< Vector< Real > > &vec1, const ROL::Ptr< Vector< Real > > &vec2)
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
const Vector< Real > & dual (void) const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
ROL::Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
int dimension () const
Return dimension of the vector space.
ROL::Ptr< const Vector< Real > > get_1 () const
ROL::Ptr< const Vector< Real > > get_2 () const
ROL::Ptr< Vector< Real > > get_1 ()
ROL::Ptr< Vector< Real > > get_2 ()
void set_1 (const Vector< Real > &vec)
void set_2 (const Vector< Real > &vec)
void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual void set (const Vector &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Attributes
ROL::Ptr< Vector< Real > > vec1_
ROL::Ptr< Vector< Real > > vec2_
ROL::Ptr< Vector< Real > > dual_vec1_
ROL::Ptr< Vector< Real > > dual_vec2_
ROL::Ptr< Vector_SimOpt< Real > > dual_vec_
Detailed Description
template<class Real>
class ROL::Vector_SimOpt< Real >
Defines the linear algebra or vector space interface for simulation-based optimization.
Definition at line 23 of file ROL_Vector_SimOpt.hpp.
Constructor & Destructor Documentation
Vector_SimOpt()
template<class Real > ROL::Vector_SimOpt< Real >::Vector_SimOpt (const ROL::Ptr< Vector< Real > > & vec1, const ROL::Ptr< Vector< Real > > & vec2) inline
Definition at line 32 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::clone(), ROL::Vector_SimOpt< Real >::dual_vec1_, ROL::Vector_SimOpt< Real >::dual_vec2_, ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Member Function Documentation
plus()
template<class Real > void ROL::Vector_SimOpt< Real >::plus (const Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 38 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
scale()
template<class Real > void ROL::Vector_SimOpt< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 45 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedObjective< Real >::gradient(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), and ROL::SimulatedObjective< Real >::hessVec().
axpy()
template<class Real > void ROL::Vector_SimOpt< Real >::axpy (const Real alpha, const Vector< Real > & x) inline virtual
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of @b x.
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = \mathtt{*this} + \alpha x \f$.
   Uses #clone, #set, #scale and #plus for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 50 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
dot()
template<class Real > Real ROL::Vector_SimOpt< Real >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 57 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
norm()
template<class Real > Real ROL::Vector_SimOpt< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 63 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by main().
clone()
template<class Real > ROL::Ptr< Vector< Real > > ROL::Vector_SimOpt< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 69 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::Vector_SimOpt< Real >::basis(), main(), and ROL::Vector_SimOpt< Real >::Vector_SimOpt().
dual()
template<class Real > const Vector< Real > & ROL::Vector_SimOpt< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 73 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::dual_vec1_, ROL::Vector_SimOpt< Real >::dual_vec2_, ROL::Vector_SimOpt< Real >::dual_vec_, ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::Constraint_SimOpt< Real >::applyPreconditioner().
apply()
template<class Real > Real ROL::Vector_SimOpt< Real >::apply (const Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 80 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
basis()
template<class Real > ROL::Ptr< Vector< Real > > ROL::Vector_SimOpt< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 86 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::basis(), ROL::Vector_SimOpt< Real >::clone(), ROL::Vector_SimOpt< Real >::dimension(), ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::Vector_SimOpt< Real >::basis().
applyUnary()
template<class Real > void ROL::Vector_SimOpt< Real >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 102 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by main().
applyBinary()
template<class Real > void ROL::Vector_SimOpt< Real >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const Vector< Real > & x) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 109 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::applyBinary(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::Vector_SimOpt< Real >::applyBinary().
reduce()
template<class Real > Real ROL::Vector_SimOpt< Real >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 117 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
setScalar()
template<class Real > void ROL::Vector_SimOpt< Real >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 125 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
randomize()
template<class Real > void ROL::Vector_SimOpt< Real >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 130 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
dimension()
template<class Real > int ROL::Vector_SimOpt< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 136 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::dimension(), ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::Vector_SimOpt< Real >::basis(), and ROL::Vector_SimOpt< Real >::dimension().
get_1() [1/2]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::Vector_SimOpt< Real >::get_1 () const inline
Definition at line 140 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_.
Referenced by ROL::Vector_SimOpt< Real >::apply(), ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::Vector_SimOpt< Real >::applyBinary(), ROL::BoundConstraint_SimOpt< Real >::applyInverseScalingFunction(), ROL::Constraint_SimOpt< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::applyPreconditioner(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), ROL::BoundConstraint_SimOpt< Real >::applyScalingFunctionJacobian(), ROL::Vector_SimOpt< Real >::axpy(), ROL::Vector_SimOpt< Real >::dot(), ROL::Objective_SimOpt< Real >::gradient(), ROL::SimulatedObjective< Real >::gradient(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), ROL::Objective_SimOpt< Real >::hessVec(), ROL::SimulatedObjective< Real >::hessVec(), ROL::BoundConstraint_SimOpt< Real >::isFeasible(), ROL::Vector_SimOpt< Real >::plus(), ROL::BoundConstraint_SimOpt< Real >::project(), ROL::BoundConstraint_SimOpt< Real >::projectInterior(), ROL::BoundConstraint_SimOpt< Real >::pruneActive(), ROL::BoundConstraint_SimOpt< Real >::pruneActive(), ROL::BoundConstraint_SimOpt< Real >::pruneLowerActive(), ROL::BoundConstraint_SimOpt< Real >::pruneLowerActive(), ROL::BoundConstraint_SimOpt< Real >::pruneUpperActive(), ROL::BoundConstraint_SimOpt< Real >::pruneUpperActive(), ROL::Constraint_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::update(), ROL::Constraint_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::value(), ROL::SimulatedObjective< Real >::value(), ROL::SimulatedObjectiveCVaR< Real >::value(), and ROL::Constraint_SimOpt< Real >::value().
get_2() [1/2]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::Vector_SimOpt< Real >::get_2 () const inline
Definition at line 144 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::Vector_SimOpt< Real >::apply(), ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::Vector_SimOpt< Real >::applyBinary(), ROL::BoundConstraint_SimOpt< Real >::applyInverseScalingFunction(), ROL::Constraint_SimOpt< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::Constraint_SimOpt< Real >::applyPreconditioner(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), ROL::BoundConstraint_SimOpt< Real >::applyScalingFunctionJacobian(), ROL::Vector_SimOpt< Real >::axpy(), ROL::Vector_SimOpt< Real >::dot(), ROL::Objective_SimOpt< Real >::gradient(), ROL::SimulatedObjective< Real >::gradient(), ROL::SimulatedObjectiveCVaR< Real >::gradient(), ROL::Objective_SimOpt< Real >::hessVec(), ROL::SimulatedObjective< Real >::hessVec(), ROL::BoundConstraint_SimOpt< Real >::isFeasible(), ROL::Vector_SimOpt< Real >::plus(), ROL::BoundConstraint_SimOpt< Real >::project(), ROL::BoundConstraint_SimOpt< Real >::projectInterior(), ROL::BoundConstraint_SimOpt< Real >::pruneActive(), ROL::BoundConstraint_SimOpt< Real >::pruneActive(), ROL::BoundConstraint_SimOpt< Real >::pruneLowerActive(), ROL::BoundConstraint_SimOpt< Real >::pruneLowerActive(), ROL::BoundConstraint_SimOpt< Real >::pruneUpperActive(), ROL::BoundConstraint_SimOpt< Real >::pruneUpperActive(), ROL::Constraint_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::update(), ROL::Constraint_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::update(), ROL::Objective_SimOpt< Real >::value(), ROL::SimulatedObjective< Real >::value(), ROL::SimulatedObjectiveCVaR< Real >::value(), and ROL::Constraint_SimOpt< Real >::value().
get_1() [2/2]
template<class Real > ROL::Ptr< Vector< Real > > ROL::Vector_SimOpt< Real >::get_1 () inline
Definition at line 148 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_.
get_2() [2/2]
template<class Real > ROL::Ptr< Vector< Real > > ROL::Vector_SimOpt< Real >::get_2 () inline
Definition at line 152 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec2_.
set_1()
template<class Real > void ROL::Vector_SimOpt< Real >::set_1 (const Vector< Real > & vec) inline
Definition at line 156 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_.
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian(), ROL::Objective_SimOpt< Real >::gradient(), and ROL::Objective_SimOpt< Real >::hessVec().
set_2()
template<class Real > void ROL::Vector_SimOpt< Real >::set_2 (const Vector< Real > & vec) inline
Definition at line 160 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec2_.
Referenced by ROL::Constraint_SimOpt< Real >::applyAdjointHessian(), ROL::Constraint_SimOpt< Real >::applyAdjointJacobian(), ROL::Objective_SimOpt< Real >::gradient(), and ROL::Objective_SimOpt< Real >::hessVec().
print()
template<class Real > void ROL::Vector_SimOpt< Real >::print (std::ostream & outStream) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 164 of file ROL_Vector_SimOpt.hpp.
References ROL::Vector_SimOpt< Real >::vec1_, and ROL::Vector_SimOpt< Real >::vec2_.
Member Data Documentation
vec1_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Vector_SimOpt< Real >::vec1_ private
Definition at line 25 of file ROL_Vector_SimOpt.hpp.
Referenced by ROL::Vector_SimOpt< Real >::apply(), ROL::Vector_SimOpt< Real >::applyBinary(), ROL::Vector_SimOpt< Real >::applyUnary(), ROL::Vector_SimOpt< Real >::axpy(), ROL::Vector_SimOpt< Real >::basis(), ROL::Vector_SimOpt< Real >::clone(), ROL::Vector_SimOpt< Real >::dimension(), ROL::Vector_SimOpt< Real >::dot(), ROL::Vector_SimOpt< Real >::dual(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::norm(), ROL::Vector_SimOpt< Real >::plus(), ROL::Vector_SimOpt< Real >::print(), ROL::Vector_SimOpt< Real >::randomize(), ROL::Vector_SimOpt< Real >::reduce(), ROL::Vector_SimOpt< Real >::scale(), ROL::Vector_SimOpt< Real >::set_1(), ROL::Vector_SimOpt< Real >::setScalar(), and ROL::Vector_SimOpt< Real >::Vector_SimOpt().
vec2_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Vector_SimOpt< Real >::vec2_ private
Definition at line 26 of file ROL_Vector_SimOpt.hpp.
Referenced by ROL::Vector_SimOpt< Real >::apply(), ROL::Vector_SimOpt< Real >::applyBinary(), ROL::Vector_SimOpt< Real >::applyUnary(), ROL::Vector_SimOpt< Real >::axpy(), ROL::Vector_SimOpt< Real >::basis(), ROL::Vector_SimOpt< Real >::clone(), ROL::Vector_SimOpt< Real >::dimension(), ROL::Vector_SimOpt< Real >::dot(), ROL::Vector_SimOpt< Real >::dual(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::get_2(), ROL::Vector_SimOpt< Real >::norm(), ROL::Vector_SimOpt< Real >::plus(), ROL::Vector_SimOpt< Real >::print(), ROL::Vector_SimOpt< Real >::randomize(), ROL::Vector_SimOpt< Real >::reduce(), ROL::Vector_SimOpt< Real >::scale(), ROL::Vector_SimOpt< Real >::set_2(), ROL::Vector_SimOpt< Real >::setScalar(), and ROL::Vector_SimOpt< Real >::Vector_SimOpt().
dual_vec1_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Vector_SimOpt< Real >::dual_vec1_ mutable private
Definition at line 27 of file ROL_Vector_SimOpt.hpp.
Referenced by ROL::Vector_SimOpt< Real >::dual(), and ROL::Vector_SimOpt< Real >::Vector_SimOpt().
dual_vec2_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Vector_SimOpt< Real >::dual_vec2_ mutable private
Definition at line 28 of file ROL_Vector_SimOpt.hpp.
Referenced by ROL::Vector_SimOpt< Real >::dual(), and ROL::Vector_SimOpt< Real >::Vector_SimOpt().
dual_vec_
template<class Real > ROL::Ptr<Vector_SimOpt<Real> > ROL::Vector_SimOpt< Real >::dual_vec_ mutable private
Definition at line 29 of file ROL_Vector_SimOpt.hpp.
Referenced by ROL::Vector_SimOpt< Real >::dual().
The documentation for this class was generated from the following file:
ROL_Vector_SimOpt.hpp