ROL: ROL::ConjugateResiduals< Real > Class Template Reference
ROL::ConjugateResiduals< Real > Class Template Reference
Provides definition of the Conjugate Residual solver.
#include <ROL_ConjugateResiduals.hpp>
Public Member Functions
ConjugateResiduals (Real absTol=1.e-4, Real relTol=1.e-2, int maxit=100, bool useInexact=false)
Real run (Vector< Real > &x, LinearOperator< Real > &A, const Vector< Real > &b, LinearOperator< Real > &M, int &iter, int &flag)
Public Member Functions inherited from ROL::Krylov< Real >
virtual ~Krylov (void)
Krylov (Real absTol=1.e-4, Real relTol=1.e-2, unsigned maxit=100)
Krylov (ROL::ParameterList &parlist)
void resetAbsoluteTolerance (const Real absTol)
void resetRelativeTolerance (const Real relTol)
void resetMaximumIteration (const unsigned maxit)
Real getAbsoluteTolerance (void) const
Real getRelativeTolerance (void) const
unsigned getMaximumIteration (void) const
Private Attributes
bool isInitialized_
bool useInexact_
ROL::Ptr< Vector< Real > > r_
ROL::Ptr< Vector< Real > > v_
ROL::Ptr< Vector< Real > > p_
ROL::Ptr< Vector< Real > > Ap_
ROL::Ptr< Vector< Real > > MAp_
Detailed Description
template<class Real>
class ROL::ConjugateResiduals< Real >
Provides definition of the Conjugate Residual solver.
Definition at line 23 of file ROL_ConjugateResiduals.hpp.
Constructor & Destructor Documentation
ConjugateResiduals()
template<class Real > ROL::ConjugateResiduals< Real >::ConjugateResiduals (Real absTol = 1.e-4, Real relTol = 1.e-2, int maxit = 100, bool useInexact = false) inline
Definition at line 34 of file ROL_ConjugateResiduals.hpp.
Member Function Documentation
run()
template<class Real > Real ROL::ConjugateResiduals< Real >::run (Vector< Real > & x, LinearOperator< Real > & A, const Vector< Real > & b, LinearOperator< Real > & M, int & iter, int & flag) inline virtual
Implements ROL::Krylov< Real >.
Definition at line 38 of file ROL_ConjugateResiduals.hpp.
References ROL::ConjugateResiduals< Real >::Ap_, ROL::LinearOperator< Real >::apply(), ROL::LinearOperator< Real >::applyInverse(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Krylov< Real >::getMaximumIteration(), ROL::ConjugateResiduals< Real >::isInitialized_, ROL::ConjugateResiduals< Real >::MAp_, ROL::Vector< Real >::norm(), ROL::ConjugateResiduals< Real >::p_, ROL::ConjugateResiduals< Real >::r_, ROL::ConjugateResiduals< Real >::useInexact_, ROL::ConjugateResiduals< Real >::v_, and ROL::Vector< Real >::zero().
Member Data Documentation
isInitialized_
template<class Real > bool ROL::ConjugateResiduals< Real >::isInitialized_ private
Definition at line 25 of file ROL_ConjugateResiduals.hpp.
Referenced by ROL::ConjugateResiduals< Real >::run().
useInexact_
template<class Real > bool ROL::ConjugateResiduals< Real >::useInexact_ private
Definition at line 26 of file ROL_ConjugateResiduals.hpp.
Referenced by ROL::ConjugateResiduals< Real >::run().
r_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateResiduals< Real >::r_ private
Definition at line 27 of file ROL_ConjugateResiduals.hpp.
Referenced by ROL::ConjugateResiduals< Real >::run().
v_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateResiduals< Real >::v_ private
Definition at line 28 of file ROL_ConjugateResiduals.hpp.
Referenced by ROL::ConjugateResiduals< Real >::run().
p_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateResiduals< Real >::p_ private
Definition at line 29 of file ROL_ConjugateResiduals.hpp.
Referenced by ROL::ConjugateResiduals< Real >::run().
Ap_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateResiduals< Real >::Ap_ private
Definition at line 30 of file ROL_ConjugateResiduals.hpp.
Referenced by ROL::ConjugateResiduals< Real >::run().
MAp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateResiduals< Real >::MAp_ private
Definition at line 31 of file ROL_ConjugateResiduals.hpp.
Referenced by ROL::ConjugateResiduals< Real >::run().
The documentation for this class was generated from the following file:
ROL_ConjugateResiduals.hpp