ROL: ROL::TypeBIndicatorObjective< Real > Class Template Reference
ROL::TypeBIndicatorObjective< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate the indicator function of linear constraints.
#include <ROL_TypeBIndicatorObjective.hpp>
Public Member Functions
TypeBIndicatorObjective (const Ptr< BoundConstraint< Real > > &bnd)
TypeBIndicatorObjective (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res, ParameterList &list)
TypeBIndicatorObjective (const Ptr< PolyhedralProjection< Real > > &proj)
void initialize (const Vector< Real > &x)
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
const Ptr< PolyhedralProjection< Real > > proj_
const Ptr< Vector< Real > > res_
bool isInit_
Real tol_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::TypeBIndicatorObjective< Real >
Provides the interface to evaluate the indicator function of linear constraints.
Definition at line 27 of file ROL_TypeBIndicatorObjective.hpp.
Constructor & Destructor Documentation
TypeBIndicatorObjective() [1/3]
template<typename Real > ROL::TypeBIndicatorObjective< Real >::TypeBIndicatorObjective (const Ptr< BoundConstraint< Real > > & bnd) inline
Definition at line 36 of file ROL_TypeBIndicatorObjective.hpp.
TypeBIndicatorObjective() [2/3]
template<typename Real > ROL::TypeBIndicatorObjective< Real >::TypeBIndicatorObjective (const Vector< Real > & xprim, const Vector< Real > & xdual, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & con, const Vector< Real > & mul, const Vector< Real > & res, ParameterList & list) inline
Definition at line 40 of file ROL_TypeBIndicatorObjective.hpp.
TypeBIndicatorObjective() [3/3]
template<typename Real > ROL::TypeBIndicatorObjective< Real >::TypeBIndicatorObjective (const Ptr< PolyhedralProjection< Real > > & proj) inline
Definition at line 50 of file ROL_TypeBIndicatorObjective.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeBIndicatorObjective< Real >::initialize (const Vector< Real > & x) inline
Definition at line 53 of file ROL_TypeBIndicatorObjective.hpp.
References ROL::Vector< Real >::clone(), ROL::TypeBIndicatorObjective< Real >::isInit_, ROL::TypeBIndicatorObjective< Real >::proj_, ROL::TypeBIndicatorObjective< Real >::res_, and ROL::TypeBIndicatorObjective< Real >::tol_.
Referenced by ROL::TypeBIndicatorObjective< Real >::value().
value()
template<typename Real > Real ROL::TypeBIndicatorObjective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 65 of file ROL_TypeBIndicatorObjective.hpp.
References ROL::TypeBIndicatorObjective< Real >::initialize(), ROL::TypeBIndicatorObjective< Real >::proj_, ROL::TypeBIndicatorObjective< Real >::res_, ROL::TypeBIndicatorObjective< Real >::tol_, and zero.
prox()
template<typename Real > void ROL::TypeBIndicatorObjective< Real >::prox (Vector< Real > & Pv, const Vector< Real > & v, Real t, Real & tol) inline virtual
Compute the proximity operator.
This function returns the proximity operator.
Parameters
[out] Pv is the proximity operator applied to \(v\) (primal optimization vector).
[in] v is the input to the proximity operator (primal optimization vector).
[in] t is the proximity operator parameter (positive scalar).
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 77 of file ROL_TypeBIndicatorObjective.hpp.
References ROL::TypeBIndicatorObjective< Real >::proj_, and ROL::Vector< Real >::set().
Member Data Documentation
proj_
template<typename Real > const Ptr<PolyhedralProjection<Real> > ROL::TypeBIndicatorObjective< Real >::proj_ private
Definition at line 29 of file ROL_TypeBIndicatorObjective.hpp.
Referenced by ROL::TypeBIndicatorObjective< Real >::initialize(), ROL::TypeBIndicatorObjective< Real >::prox(), and ROL::TypeBIndicatorObjective< Real >::value().
res_
template<typename Real > const Ptr<Vector<Real> > ROL::TypeBIndicatorObjective< Real >::res_ private
Definition at line 30 of file ROL_TypeBIndicatorObjective.hpp.
Referenced by ROL::TypeBIndicatorObjective< Real >::initialize(), and ROL::TypeBIndicatorObjective< Real >::value().
isInit_
template<typename Real > bool ROL::TypeBIndicatorObjective< Real >::isInit_ private
Definition at line 31 of file ROL_TypeBIndicatorObjective.hpp.
Referenced by ROL::TypeBIndicatorObjective< Real >::initialize().
tol_
template<typename Real > Real ROL::TypeBIndicatorObjective< Real >::tol_ private
Definition at line 32 of file ROL_TypeBIndicatorObjective.hpp.
Referenced by ROL::TypeBIndicatorObjective< Real >::initialize(), and ROL::TypeBIndicatorObjective< Real >::value().
The documentation for this class was generated from the following file:
ROL_TypeBIndicatorObjective.hpp