ROL: ROL::Krylov< Real > Class Template Reference
ROL::Krylov< Real > Class Template Reference abstract
Provides definitions for Krylov solvers.
#include <ROL_Krylov.hpp>
Public Member Functions
virtual ~Krylov (void)
Krylov (Real absTol=1.e-4, Real relTol=1.e-2, unsigned maxit=100)
Krylov (ROL::ParameterList &parlist)
virtual Real run (Vector< Real > &x, LinearOperator< Real > &A, const Vector< Real > &b, LinearOperator< Real > &M, int &iter, int &flag)=0
void resetAbsoluteTolerance (const Real absTol)
void resetRelativeTolerance (const Real relTol)
void resetMaximumIteration (const unsigned maxit)
Real getAbsoluteTolerance (void) const
Real getRelativeTolerance (void) const
unsigned getMaximumIteration (void) const
Private Attributes
Real absTol_
Real relTol_
unsigned maxit_
Detailed Description
template<class Real>
class ROL::Krylov< Real >
Provides definitions for Krylov solvers.
Definition at line 24 of file ROL_Krylov.hpp.
Constructor & Destructor Documentation
~Krylov()
template<class Real > virtual ROL::Krylov< Real >::~Krylov (void) inline virtual
Definition at line 31 of file ROL_Krylov.hpp.
Krylov() [1/2]
template<class Real > ROL::Krylov< Real >::Krylov (Real absTol = 1.e-4, Real relTol = 1.e-2, unsigned maxit = 100) inline
Definition at line 33 of file ROL_Krylov.hpp.
Krylov() [2/2]
template<class Real > ROL::Krylov< Real >::Krylov (ROL::ParameterList & parlist) inline
Definition at line 36 of file ROL_Krylov.hpp.
References ROL::Krylov< Real >::absTol_, ROL::Krylov< Real >::maxit_, and ROL::Krylov< Real >::relTol_.
Member Function Documentation
run()
template<class Real > virtual Real ROL::Krylov< Real >::run (Vector< Real > & x, LinearOperator< Real > & A, const Vector< Real > & b, LinearOperator< Real > & M, int & iter, int & flag) pure virtual
Implemented in ROL::details::MINRES< Real >, ROL::BiCGSTAB< Real >, ROL::ConjugateGradients< Real >, ROL::ConjugateResiduals< Real >, and ROL::GMRES< Real >.
resetAbsoluteTolerance()
template<class Real > void ROL::Krylov< Real >::resetAbsoluteTolerance (const Real absTol) inline
Definition at line 48 of file ROL_Krylov.hpp.
References ROL::Krylov< Real >::absTol_.
resetRelativeTolerance()
template<class Real > void ROL::Krylov< Real >::resetRelativeTolerance (const Real relTol) inline
Definition at line 51 of file ROL_Krylov.hpp.
References ROL::Krylov< Real >::relTol_.
resetMaximumIteration()
template<class Real > void ROL::Krylov< Real >::resetMaximumIteration (const unsigned maxit) inline
Definition at line 54 of file ROL_Krylov.hpp.
References ROL::Krylov< Real >::maxit_.
getAbsoluteTolerance()
template<class Real > Real ROL::Krylov< Real >::getAbsoluteTolerance (void) const inline
Definition at line 57 of file ROL_Krylov.hpp.
References ROL::Krylov< Real >::absTol_.
Referenced by ROL::GMRES< Real >::run().
getRelativeTolerance()
template<class Real > Real ROL::Krylov< Real >::getRelativeTolerance (void) const inline
Definition at line 60 of file ROL_Krylov.hpp.
References ROL::Krylov< Real >::relTol_.
Referenced by ROL::GMRES< Real >::run().
getMaximumIteration()
template<class Real > unsigned ROL::Krylov< Real >::getMaximumIteration (void) const inline
Definition at line 63 of file ROL_Krylov.hpp.
References ROL::Krylov< Real >::maxit_.
Referenced by ROL::GMRES< Real >::GMRES(), ROL::BiCGSTAB< Real >::run(), ROL::ConjugateResiduals< Real >::run(), and ROL::GMRES< Real >::run().
Member Data Documentation
absTol_
template<class Real > Real ROL::Krylov< Real >::absTol_ private
Definition at line 26 of file ROL_Krylov.hpp.
Referenced by ROL::Krylov< Real >::getAbsoluteTolerance(), ROL::Krylov< Real >::Krylov(), and ROL::Krylov< Real >::resetAbsoluteTolerance().
relTol_
template<class Real > Real ROL::Krylov< Real >::relTol_ private
Definition at line 27 of file ROL_Krylov.hpp.
Referenced by ROL::Krylov< Real >::getRelativeTolerance(), ROL::Krylov< Real >::Krylov(), and ROL::Krylov< Real >::resetRelativeTolerance().
maxit_
template<class Real > unsigned ROL::Krylov< Real >::maxit_ private
Definition at line 28 of file ROL_Krylov.hpp.
Referenced by ROL::Krylov< Real >::getMaximumIteration(), ROL::Krylov< Real >::Krylov(), and ROL::Krylov< Real >::resetMaximumIteration().
The documentation for this class was generated from the following file:
ROL_Krylov.hpp