ROL: ROL::LogQuantileQuadrangle< Real > Class Template Reference
ROL::LogQuantileQuadrangle< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for the conditioanl entropic risk using the expectation risk quadrangle.
#include <ROL_LogQuantileQuadrangle.hpp>
Public Member Functions
LogQuantileQuadrangle (Real alpha, Real rate, Real eps, ROL::Ptr< PlusFunction< Real > > &pf)
Constructor.
LogQuantileQuadrangle (ROL::ParameterList &parlist)
Constructor.
Real error (Real x, int deriv=0)
Evaluate the scalar error function at x.
Real regret (Real x, int deriv=0)
Evaluate the scalar regret function at x.
void check (void)
Run default derivative tests for the scalar regret function.
Public Member Functions inherited from ROL::ExpectationQuad< Real >
virtual ~ExpectationQuad (void)
ExpectationQuad (void)
Private Member Functions
void parseParameterList (ROL::ParameterList &parlist)
void checkInputs (void) const
Private Attributes
ROL::Ptr< PlusFunction< Real > > pf_
Real alpha_
Real rate_
Real eps_
Detailed Description
template<class Real>
class ROL::LogQuantileQuadrangle< Real >
Provides an interface for the conditioanl entropic risk using the expectation risk quadrangle.
This class defines the conditional entropic risk measure using the framework of the expectation risk quadrangle. In this case, the scalar regret function is
\[ v(x) = \lambda(\exp\left(\frac{x}{\lambda}\right)-1)_+ - \alpha (-x)_+ \]
for \(\lambda > 0\) and \(0 \le \alpha < 1\). The entropic risk measure is then implemented as
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}}\left\{ t + \mathbb{E}[v(X-t)] \right\}. \]
The conditional entropic risk is convex, translation equivariant and monotonic. ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
Definition at line 42 of file ROL_LogQuantileQuadrangle.hpp.
Constructor & Destructor Documentation
LogQuantileQuadrangle() [1/2]
template<class Real > ROL::LogQuantileQuadrangle< Real >::LogQuantileQuadrangle (Real alpha, Real rate, Real eps, ROL::Ptr< PlusFunction< Real > > & pf) inline
Constructor.
Parameters
[in] alpha is the scale parameter for the negative branch of the scalar regret
[in] rate is the rate parameter for the positive branch of the scalar regret
[in] eps is the smoothing parameter for the approximate plus function
[in] pf is the plus function or an approximation
Definition at line 94 of file ROL_LogQuantileQuadrangle.hpp.
References ROL::LogQuantileQuadrangle< Real >::checkInputs().
LogQuantileQuadrangle() [2/2]
template<class Real > ROL::LogQuantileQuadrangle< Real >::LogQuantileQuadrangle (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measures"->"Log-Quantile Quadrangle" and withing the "Log-Quantile Quadrangle" sublist should have
"Slope for Linear Growth" (between 0 and 1)
"Rate for Exponential Growth" (must be positive)
"Smoothing Parameter" (must be positive)
A sublist for plus function information.
Definition at line 111 of file ROL_LogQuantileQuadrangle.hpp.
References ROL::LogQuantileQuadrangle< Real >::checkInputs(), and ROL::LogQuantileQuadrangle< Real >::parseParameterList().
Member Function Documentation
parseParameterList()
template<class Real > void ROL::LogQuantileQuadrangle< Real >::parseParameterList (ROL::ParameterList & parlist) inline private
Definition at line 51 of file ROL_LogQuantileQuadrangle.hpp.
References ROL::LogQuantileQuadrangle< Real >::alpha_, ROL::LogQuantileQuadrangle< Real >::eps_, ROL::LogQuantileQuadrangle< Real >::pf_, and ROL::LogQuantileQuadrangle< Real >::rate_.
Referenced by ROL::LogQuantileQuadrangle< Real >::LogQuantileQuadrangle().
checkInputs()
template<class Real > void ROL::LogQuantileQuadrangle< Real >::checkInputs (void) const inline private
Definition at line 74 of file ROL_LogQuantileQuadrangle.hpp.
References ROL::LogQuantileQuadrangle< Real >::alpha_, ROL::LogQuantileQuadrangle< Real >::eps_, ROL::LogQuantileQuadrangle< Real >::pf_, ROL::LogQuantileQuadrangle< Real >::rate_, and zero.
Referenced by ROL::LogQuantileQuadrangle< Real >::LogQuantileQuadrangle(), and ROL::LogQuantileQuadrangle< Real >::LogQuantileQuadrangle().
error()
template<class Real > Real ROL::LogQuantileQuadrangle< Real >::error (Real x, int deriv = 0) inline virtual
Evaluate the scalar error function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(e(x)\) or a derivative of \(e(x)\).
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 117 of file ROL_LogQuantileQuadrangle.hpp.
References ROL::LogQuantileQuadrangle< Real >::regret(), and zero.
regret()
template<class Real > Real ROL::LogQuantileQuadrangle< Real >::regret (Real x, int deriv = 0) inline virtual
Evaluate the scalar regret function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(v(x)\) or a derivative of \(v(x)\).
Implements ROL::ExpectationQuad< Real >.
Definition at line 128 of file ROL_LogQuantileQuadrangle.hpp.
References ROL::LogQuantileQuadrangle< Real >::alpha_, ROL::LogQuantileQuadrangle< Real >::pf_, ROL::LogQuantileQuadrangle< Real >::rate_, and zero.
Referenced by ROL::LogQuantileQuadrangle< Real >::check(), and ROL::LogQuantileQuadrangle< Real >::error().
check()
template<class Real > void ROL::LogQuantileQuadrangle< Real >::check (void) inline virtual
Run default derivative tests for the scalar regret function.
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 144 of file ROL_LogQuantileQuadrangle.hpp.
References ROL::ExpectationQuad< Real >::check(), ROL::LogQuantileQuadrangle< Real >::eps_, ROL::LogQuantileQuadrangle< Real >::regret(), and zero.
Member Data Documentation
pf_
template<class Real > ROL::Ptr<PlusFunction<Real> > ROL::LogQuantileQuadrangle< Real >::pf_ private
Definition at line 45 of file ROL_LogQuantileQuadrangle.hpp.
Referenced by ROL::LogQuantileQuadrangle< Real >::checkInputs(), ROL::LogQuantileQuadrangle< Real >::parseParameterList(), and ROL::LogQuantileQuadrangle< Real >::regret().
alpha_
template<class Real > Real ROL::LogQuantileQuadrangle< Real >::alpha_ private
Definition at line 47 of file ROL_LogQuantileQuadrangle.hpp.
Referenced by ROL::LogQuantileQuadrangle< Real >::checkInputs(), ROL::LogQuantileQuadrangle< Real >::parseParameterList(), and ROL::LogQuantileQuadrangle< Real >::regret().
rate_
template<class Real > Real ROL::LogQuantileQuadrangle< Real >::rate_ private
Definition at line 48 of file ROL_LogQuantileQuadrangle.hpp.
Referenced by ROL::LogQuantileQuadrangle< Real >::checkInputs(), ROL::LogQuantileQuadrangle< Real >::parseParameterList(), and ROL::LogQuantileQuadrangle< Real >::regret().
eps_
template<class Real > Real ROL::LogQuantileQuadrangle< Real >::eps_ private
Definition at line 49 of file ROL_LogQuantileQuadrangle.hpp.
Referenced by ROL::LogQuantileQuadrangle< Real >::check(), ROL::LogQuantileQuadrangle< Real >::checkInputs(), and ROL::LogQuantileQuadrangle< Real >::parseParameterList().
The documentation for this class was generated from the following file:
ROL_LogQuantileQuadrangle.hpp