ROL: ROL::ZOO::Objective_DiodeCircuit< Real > Class Template Reference
ROL::ZOO::Objective_DiodeCircuit< Real > Class Template Reference
The diode circuit problem.
#include <ROL_DiodeCircuit.hpp>
Public Member Functions
Objective_DiodeCircuit (Real Vth, Real Vsrc_min, Real Vsrc_max, Real Vsrc_step, Real true_Is, Real true_Rs, bool lambertw, Real noise, bool use_adjoint, int use_hessvec)
A constructor generating data.
Objective_DiodeCircuit (Real Vth, std::ifstream &input_file, bool lambertw, Real noise, bool use_adjoint, int use_hessvec)
A constructor using data from given file.
void set_method (bool lambertw)
Change the method for solving the circuit if needed.
void solve_circuit (Vector< Real > &I, const Vector< Real > &S)
Solve circuit given optimization parameters Is and Rs.
Real value (const Vector< Real > &S, Real &tol)
Evaluate objective function.
void gradient (Vector< Real > &g, const Vector< Real > &S, Real &tol)
Compute the gradient of the reduced objective function either using adjoint or using sensitivities.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &S, Real &tol)
Compute the Hessian-vector product of the reduced objective function.
void generate_plot (Real Is_lo, Real Is_up, Real Is_step, Real Rs_lo, Real Rs_up, Real Rs_step)
Generate data to plot objective function.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Types
typedef std::vector< Real > vector
typedef Vector< Real > V
typedef StdVector< Real > STDV
typedef PrimalScaledStdVector< Real > PSV
typedef DualScaledStdVector< Real > DSV
typedef vector::size_type uint
Private Member Functions
ROL::Ptr< const vector > getVector (const V &x)
ROL::Ptr< vector > getVector (V &x)
Real random (const Real left, const Real right) const
Real diode (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Diode equation.
Real diodeI (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Derivative of diode equation wrt I.
Real diodeIs (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Derivative of diode equation wrt Is.
Real diodeRs (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Derivative of diode equation wrt Rs
Real diodeII (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Second derivative of diode equation wrt I^2.
Real diodeIIs (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Second derivative of diode equation wrt I and Is.
Real diodeIRs (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Second derivative of diode equation wrt I and Rs.
Real diodeIsIs (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Second derivative of diode equation wrt Is^2.
Real diodeIsRs (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Second derivative of diode equation wrt Is and Rs.
Real diodeRsRs (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Second derivative of diode equation wrt Rs^2.
Real Newton (const Real I, const Real Vsrc, const Real Is, const Real Rs)
Newton's method with line search.
void lambertw (Real x, Real &w, int &ierr, Real &xi)
Lambert-W function for diodes.
Real lambertWCurrent (Real Is, Real Rs, Real Vsrc)
Find currents using Lambert-W function.
void solve_adjoint (Vector< Real > &lambda, const Vector< Real > &I, const Vector< Real > &S)
Solve the adjoint equation.
void solve_sensitivity_Is (Vector< Real > &sens, const Vector< Real > &I, const Vector< Real > &S)
Solve the sensitivity equation wrt Is.
void solve_sensitivity_Rs (Vector< Real > &sens, const Vector< Real > &I, const Vector< Real > &S)
Solve the sensitivity equation wrt Rs.
Private Attributes
Real Vth_
Thermal voltage (constant)
ROL::Ptr< std::vector< Real > > Imeas_
Vector of measured currents in DC analysis (data)
ROL::Ptr< std::vector< Real > > Vsrc_
Vector of source voltages in DC analysis (input)
bool lambertw_
If true, use Lambert-W function to solve circuit, else use Newton's method.
Real noise_
Percentage of noise to add to measurements; if 0.0 - no noise.
bool use_adjoint_
If true, use adjoint gradient computation, else compute gradient using sensitivities.
int use_hessvec_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::ZOO::Objective_DiodeCircuit< Real >
The diode circuit problem.
The diode circuit problem:
\begin{eqnarray*} \min_{I_S,R_S} \,\, \frac{1}{2}\sum\limits_{n=1}^N (I_n-I_n^{meas})^2 \\ \text{s.t.}\;\;\begin{cases}c(I_S,R_S,I_1,V^{src}_1)=0\\ \dots \\c(I_S,R_S,I_N,V^{src}_N)=0\end{cases} \end{eqnarray*}
where
\[c(I_S,R_S,I_n,V^{src}_n)=I_n - I_S\left(\exp\left(\frac{-I_n R_S+V^{src}_n}{V_{th}}\right)-1\right)\]
.
Definition at line 33 of file ROL_DiodeCircuit.hpp.
Member Typedef Documentation
vector
template<class Real > typedef std::vector<Real> ROL::ZOO::Objective_DiodeCircuit< Real >::vector private
Definition at line 35 of file ROL_DiodeCircuit.hpp.
V
template<class Real > typedef Vector<Real> ROL::ZOO::Objective_DiodeCircuit< Real >::V private
Definition at line 36 of file ROL_DiodeCircuit.hpp.
STDV
template<class Real > typedef StdVector<Real> ROL::ZOO::Objective_DiodeCircuit< Real >::STDV private
Definition at line 37 of file ROL_DiodeCircuit.hpp.
PSV
template<class Real > typedef PrimalScaledStdVector<Real> ROL::ZOO::Objective_DiodeCircuit< Real >::PSV private
Definition at line 38 of file ROL_DiodeCircuit.hpp.
DSV
template<class Real > typedef DualScaledStdVector<Real> ROL::ZOO::Objective_DiodeCircuit< Real >::DSV private
Definition at line 39 of file ROL_DiodeCircuit.hpp.
uint
template<class Real > typedef vector::size_type ROL::ZOO::Objective_DiodeCircuit< Real >::uint private
Definition at line 40 of file ROL_DiodeCircuit.hpp.
Constructor & Destructor Documentation
Objective_DiodeCircuit() [1/2]
template<class Real > ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit (Real Vth, Real Vsrc_min, Real Vsrc_max, Real Vsrc_step, Real true_Is, Real true_Rs, bool lambertw, Real noise, bool use_adjoint, int use_hessvec) inline
A constructor generating data.
Given thermal voltage, minimum and maximum values of source voltages and a step size, values of Is and Rs generates vector of source voltages and solves nonlinear diode equation to populate the vector of measured currents, which is later used as data. If noise is nonzero, adds random perturbation to data on the order of the magnitude of the components. Sets the flag to use Lambert-W function or Newton's method to solve circuit. Sets the flags to use adjoint gradient computation and one of three Hessian-vector implementations.
Definition at line 76 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Imeas_, ROL::ZOO::Objective_DiodeCircuit< Real >::lambertw_, ROL::ZOO::Objective_DiodeCircuit< Real >::lambertWCurrent(), ROL::ZOO::Objective_DiodeCircuit< Real >::Newton(), ROL::ZOO::Objective_DiodeCircuit< Real >::random(), and ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_.
Objective_DiodeCircuit() [2/2]
template<class Real > ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit (Real Vth, std::ifstream & input_file, bool lambertw, Real noise, bool use_adjoint, int use_hessvec) inline
A constructor using data from given file.
Given thermal voltage and a file with two columns - one for source voltages, another for corresponding currents - populates vectors of source voltages and measured currents. If noise is nonzero, adds random perturbation to data on the order of the magnitude of the components. Sets the flag to use Lambert-W function or Newton's method to solve circuit. Sets the flags to use adjoint gradient computation and one of three Hessian-vector implementations.
Definition at line 126 of file ROL_DiodeCircuit.hpp.
References dim, ROL::ZOO::Objective_DiodeCircuit< Real >::Imeas_, and ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_.
Member Function Documentation
set_method()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::set_method (bool lambertw) inline
Change the method for solving the circuit if needed.
Definition at line 151 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::lambertw(), and ROL::ZOO::Objective_DiodeCircuit< Real >::lambertw_.
solve_circuit()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit (Vector< Real > & I, const Vector< Real > & S) inline
Solve circuit given optimization parameters Is and Rs.
Definition at line 156 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), ROL::ZOO::Objective_DiodeCircuit< Real >::lambertw_, ROL::ZOO::Objective_DiodeCircuit< Real >::lambertWCurrent(), ROL::ZOO::Objective_DiodeCircuit< Real >::Newton(), and ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), and ROL::ZOO::Objective_DiodeCircuit< Real >::value().
value()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::value (const Vector< Real > & S, Real & tol) inline virtual
Evaluate objective function.
\(\frac{1}{2}\sum\limits_{i=1}^{N}(I_i-I^{meas}_i)^2\)
Implements ROL::Objective< Real >.
Definition at line 187 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), ROL::ZOO::Objective_DiodeCircuit< Real >::Imeas_, and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit().
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::generate_plot().
gradient()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::gradient (Vector< Real > & g, const Vector< Real > & S, Real & tol) inline virtual
Compute the gradient of the reduced objective function either using adjoint or using sensitivities.
Reimplemented from ROL::Objective< Real >.
Definition at line 205 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), ROL::ZOO::Objective_DiodeCircuit< Real >::Imeas_, ROL::ZOO::Objective_DiodeCircuit< Real >::solve_adjoint(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Is(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Rs(), ROL::ZOO::Objective_DiodeCircuit< Real >::use_adjoint_, and ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_.
hessVec()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & S, Real & tol) inline virtual
Compute the Hessian-vector product of the reduced objective function.
Hessian-times-vector computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 269 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::diodeI(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeII(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIIs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIsIs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIsRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRsRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), ROL::Objective< Real >::hessVec(), ROL::ZOO::Objective_DiodeCircuit< Real >::Imeas_, ROL::ZOO::Objective_DiodeCircuit< Real >::solve_adjoint(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Is(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Rs(), ROL::ZOO::Objective_DiodeCircuit< Real >::use_hessvec_, and ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_.
generate_plot()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::generate_plot (Real Is_lo, Real Is_up, Real Is_step, Real Rs_lo, Real Rs_up, Real Rs_step) inline
Generate data to plot objective function.
Generates a file with three columns - Is value, Rs value, objective value. To plot with gnuplot type: gnuplot; set dgrid3d 100,100; set hidden3d; splot "Objective.dat" u 1:2:3 with lines;
Definition at line 381 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::value().
getVector() [1/2]
template<class Real > ROL::Ptr< const vector > ROL::ZOO::Objective_DiodeCircuit< Real >::getVector (const V & x) inline private
Definition at line 409 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::getVector().
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_adjoint(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Is(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Rs(), and ROL::ZOO::Objective_DiodeCircuit< Real >::value().
getVector() [2/2]
template<class Real > ROL::Ptr< vector > ROL::ZOO::Objective_DiodeCircuit< Real >::getVector (V & x) inline private
Definition at line 423 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::getVector().
random()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::random (const Real left, const Real right) const inline private
Definition at line 438 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit().
diode()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diode (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Diode equation.
Diode equation formula: \(I-I_S\left(\exp\left(\frac{V_{src}-IR_S}{V_{th}}\right)-1\right) \).
Definition at line 452 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::Newton().
diodeI()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeI (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Derivative of diode equation wrt I.
Definition at line 457 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), ROL::ZOO::Objective_DiodeCircuit< Real >::Newton(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_adjoint(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Is(), and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Rs().
diodeIs()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIs (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Derivative of diode equation wrt Is.
Definition at line 462 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Is().
diodeRs()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRs (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Derivative of diode equation wrt Rs
Definition at line 467 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Rs().
diodeII()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeII (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Second derivative of diode equation wrt I^2.
Definition at line 472 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
diodeIIs()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIIs (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Second derivative of diode equation wrt I and Is.
Definition at line 477 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
diodeIRs()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIRs (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Second derivative of diode equation wrt I and Rs.
Definition at line 482 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
diodeIsIs()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIsIs (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Second derivative of diode equation wrt Is^2.
Definition at line 487 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
diodeIsRs()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIsRs (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Second derivative of diode equation wrt Is and Rs.
Definition at line 492 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
diodeRsRs()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRsRs (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Second derivative of diode equation wrt Rs^2.
Definition at line 497 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
Newton()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::Newton (const Real I, const Real Vsrc, const Real Is, const Real Rs) inline private
Newton's method with line search.
Solves the diode equation for the current using Newton's method.
Definition at line 508 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::diode(), and ROL::ZOO::Objective_DiodeCircuit< Real >::diodeI().
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit(), and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit().
lambertw()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::lambertw (Real x, Real & w, int & ierr, Real & xi) inline private
Lambert-W function for diodes.
Function : DeviceSupport::lambertw Purpose : provides a lambert-w function for diodes and BJT's. Special Notes :
Purpose. Evaluate principal branch of Lambert W function at x.
w = w(x) is the value of Lambert's function. ierr = 0 indicates a safe return. ierr = 1 if x is not in the domain. ierr = 2 if the computer arithmetic contains a bug. xi may be disregarded (it is the error).
Prototype: void lambertw(Real, Real, int, Real);
Reference: T.C. Banwell Bipolar transistor circuit analysis using the Lambert W-function, IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications
vol. 47, pp. 1621-1633, Nov. 2000.
Scope : public Creator : David Day, SNL Creation Date : 04/16/02
Definition at line 581 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::lambertWCurrent(), and ROL::ZOO::Objective_DiodeCircuit< Real >::set_method().
lambertWCurrent()
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::lambertWCurrent (Real Is, Real Rs, Real Vsrc) inline private
Find currents using Lambert-W function.
Reference: T.C. Banwell Bipolar transistor circuit analysis using the Lambert W-function, IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications vol. 47, pp. 1621-1633, Nov. 2000.
Definition at line 657 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::lambertw(), and ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit(), and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit().
solve_adjoint()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::solve_adjoint (Vector< Real > & lambda, const Vector< Real > & I, const Vector< Real > & S) inline private
Solve the adjoint equation.
\(\lambda_i = \frac{(I^{meas}_i-I_i)}{\frac{\partial c}{\partial I}(I_i,V^{src}_i,I_S,R_S)}\)
Definition at line 684 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::diodeI(), and ROL::ZOO::Objective_DiodeCircuit< Real >::getVector().
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), and ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
solve_sensitivity_Is()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Is (Vector< Real > & sens, const Vector< Real > & I, const Vector< Real > & S) inline private
Solve the sensitivity equation wrt Is.
Computes sensitivity
\[\frac{\partial I}{\partial Is}\]
Definition at line 705 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::diodeI(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIs(), ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), and ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), and ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
solve_sensitivity_Rs()
template<class Real > void ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Rs (Vector< Real > & sens, const Vector< Real > & I, const Vector< Real > & S) inline private
Solve the sensitivity equation wrt Rs.
Computes sensitivity
\[\frac{\partial I}{\partial Rs}\]
Definition at line 726 of file ROL_DiodeCircuit.hpp.
References ROL::ZOO::Objective_DiodeCircuit< Real >::diodeI(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::getVector(), and ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), and ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
Member Data Documentation
Vth_
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::Vth_ private
Thermal voltage (constant)
Definition at line 44 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::diode(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeI(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeII(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIIs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeIsRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRs(), ROL::ZOO::Objective_DiodeCircuit< Real >::diodeRsRs(), and ROL::ZOO::Objective_DiodeCircuit< Real >::lambertWCurrent().
Imeas_
template<class Real > ROL::Ptr<std::vector<Real> > ROL::ZOO::Objective_DiodeCircuit< Real >::Imeas_ private
Vector of measured currents in DC analysis (data)
Definition at line 46 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit(), and ROL::ZOO::Objective_DiodeCircuit< Real >::value().
Vsrc_
template<class Real > ROL::Ptr<std::vector<Real> > ROL::ZOO::Objective_DiodeCircuit< Real >::Vsrc_ private
Vector of source voltages in DC analysis (input)
Definition at line 48 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient(), ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec(), ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Is(), and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_sensitivity_Rs().
lambertw_
template<class Real > bool ROL::ZOO::Objective_DiodeCircuit< Real >::lambertw_ private
If true, use Lambert-W function to solve circuit, else use Newton's method.
Definition at line 50 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::Objective_DiodeCircuit(), ROL::ZOO::Objective_DiodeCircuit< Real >::set_method(), and ROL::ZOO::Objective_DiodeCircuit< Real >::solve_circuit().
noise_
template<class Real > Real ROL::ZOO::Objective_DiodeCircuit< Real >::noise_ private
Percentage of noise to add to measurements; if 0.0 - no noise.
Definition at line 52 of file ROL_DiodeCircuit.hpp.
use_adjoint_
template<class Real > bool ROL::ZOO::Objective_DiodeCircuit< Real >::use_adjoint_ private
If true, use adjoint gradient computation, else compute gradient using sensitivities.
Definition at line 54 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::gradient().
use_hessvec_
template<class Real > int ROL::ZOO::Objective_DiodeCircuit< Real >::use_hessvec_ private
0 - use FD(with scaling), 1 - use exact implementation (with second order derivatives), 2 - use Gauss-Newton approximation (first order derivatives only)
Definition at line 58 of file ROL_DiodeCircuit.hpp.
Referenced by ROL::ZOO::Objective_DiodeCircuit< Real >::hessVec().
The documentation for this class was generated from the following file:
ROL_DiodeCircuit.hpp