ROL: ROL::TypeB::InteriorPointAlgorithm< Real > Class Template Reference
ROL::TypeB::InteriorPointAlgorithm< Real > Class Template Reference
Provides an interface to run the Moreau-Yosida algorithm.
#include <ROL_TypeB_InteriorPointAlgorithm.hpp>
Public Member Functions
InteriorPointAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, InteriorPointObjective< Real > &ipobj, BoundConstraint< Real > &bnd, Vector< Real > &pwa, std::ostream &outStream=std::cout)
void updateState (const Vector< Real > &x, InteriorPointObjective< Real > &ipobj, BoundConstraint< Real > &bnd, Vector< Real > &pwa, std::ostream &outStream=std::cout)
Private Attributes
const Ptr< Secant< Real > > secant_
Real mumin_
Real mumax_
Real rho_
bool useLinearDamping_
Real kappaD_
Real gtol_
Real stol_
Real gtolrate_
Real mingtol_
ROL::ParameterList list_
int subproblemIter_
std::string stepname_
bool print_
int verbosity_
bool writeHeader_
bool hasPolyProj_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::InteriorPointAlgorithm< Real >
Provides an interface to run the Moreau-Yosida algorithm.
Definition at line 25 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Constructor & Destructor Documentation
InteriorPointAlgorithm()
template<typename Real > ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 19 of file ROL_TypeB_InteriorPointAlgorithm_Def.hpp.
References ROL::TypeB::InteriorPointAlgorithm< Real >::gtol_, ROL::TypeB::InteriorPointAlgorithm< Real >::gtolrate_, ROL::TypeB::InteriorPointAlgorithm< Real >::kappaD_, ROL::TypeB::InteriorPointAlgorithm< Real >::list_, ROL::TypeB::InteriorPointAlgorithm< Real >::mingtol_, ROL::TypeB::InteriorPointAlgorithm< Real >::mumax_, ROL::TypeB::InteriorPointAlgorithm< Real >::mumin_, ROL::TypeB::InteriorPointAlgorithm< Real >::print_, ROL::TypeB::Algorithm< Real >::reset(), ROL::TypeB::InteriorPointAlgorithm< Real >::rho_, ROL::TypeB::Algorithm< Real >::state_, ROL::TypeB::Algorithm< Real >::status_, ROL::TypeB::InteriorPointAlgorithm< Real >::stepname_, ROL::TypeB::InteriorPointAlgorithm< Real >::stol_, ROL::TypeB::InteriorPointAlgorithm< Real >::useLinearDamping_, ROL::TypeB::InteriorPointAlgorithm< Real >::verbosity_, and ROL::TypeB::InteriorPointAlgorithm< Real >::writeHeader_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::InteriorPointAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, InteriorPointObjective< Real > & ipobj, BoundConstraint< Real > & bnd, Vector< Real > & pwa, std::ostream & outStream = std::cout) private
Definition at line 54 of file ROL_TypeB_InteriorPointAlgorithm_Def.hpp.
References ROL::TypeB::Algorithm< Real >::initialize(), and ROL::BoundConstraint< Real >::projectInterior().
updateState()
template<typename Real > void ROL::TypeB::InteriorPointAlgorithm< Real >::updateState (const Vector< Real > & x, InteriorPointObjective< Real > & ipobj, BoundConstraint< Real > & bnd, Vector< Real > & pwa, std::ostream & outStream = std::cout) private
Definition at line 77 of file ROL_TypeB_InteriorPointAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::InteriorPointObjective< Real >::getObjectiveValue(), ROL::InteriorPointObjective< Real >::gradient(), ROL::Initial, ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), and ROL::InteriorPointObjective< Real >::update().
run()
template<typename Real > void ROL::TypeB::InteriorPointAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 107 of file ROL_TypeB_InteriorPointAlgorithm_Def.hpp.
References ROL::Vector< Real >::clone(), ROL::EXITSTATUS_CONVERGED, ROL::InteriorPointObjective< Real >::updatePenalty(), and ROL::TypeB::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeB::InteriorPointAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 169 of file ROL_TypeB_InteriorPointAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeB::InteriorPointAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 202 of file ROL_TypeB_InteriorPointAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::InteriorPointAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 211 of file ROL_TypeB_InteriorPointAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeB::InteriorPointAlgorithm< Real >::secant_ private
Definition at line 27 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
mumin_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::mumin_ private
Definition at line 29 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
mumax_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::mumax_ private
Definition at line 30 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
rho_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::rho_ private
Definition at line 31 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
useLinearDamping_
template<typename Real > bool ROL::TypeB::InteriorPointAlgorithm< Real >::useLinearDamping_ private
Definition at line 32 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
kappaD_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::kappaD_ private
Definition at line 33 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
gtol_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::gtol_ private
Definition at line 34 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
stol_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::stol_ private
Definition at line 35 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
gtolrate_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::gtolrate_ private
Definition at line 36 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
mingtol_
template<typename Real > Real ROL::TypeB::InteriorPointAlgorithm< Real >::mingtol_ private
Definition at line 37 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
list_
template<typename Real > ROL::ParameterList ROL::TypeB::InteriorPointAlgorithm< Real >::list_ private
Definition at line 39 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
subproblemIter_
template<typename Real > int ROL::TypeB::InteriorPointAlgorithm< Real >::subproblemIter_ private
Definition at line 40 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
stepname_
template<typename Real > std::string ROL::TypeB::InteriorPointAlgorithm< Real >::stepname_ private
Definition at line 42 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
print_
template<typename Real > bool ROL::TypeB::InteriorPointAlgorithm< Real >::print_ private
Definition at line 44 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
verbosity_
template<typename Real > int ROL::TypeB::InteriorPointAlgorithm< Real >::verbosity_ private
Definition at line 45 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
writeHeader_
template<typename Real > bool ROL::TypeB::InteriorPointAlgorithm< Real >::writeHeader_ private
Definition at line 46 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm().
hasPolyProj_
template<typename Real > bool ROL::TypeB::InteriorPointAlgorithm< Real >::hasPolyProj_ private
Definition at line 48 of file ROL_TypeB_InteriorPointAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_InteriorPointAlgorithm.hpp
ROL_TypeB_InteriorPointAlgorithm_Def.hpp