ROL: ROL::AugmentedSystemPrecOperator< Real > Class Template Reference
ROL::AugmentedSystemPrecOperator< Real > Class Template Reference
User Interface » Functional Interface
Implements a preconditioner for the augmented system.
#include <ROL_AugmentedSystemPrecOperator.hpp>
Public Member Functions
virtual ~AugmentedSystemPrecOperator ()
AugmentedSystemPrecOperator (const Ptr< Constraint< Real > > &con, const Ptr< const Vector< Real > > &x)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
Private Attributes
const Ptr< Constraint< Real > > con_
const Ptr< const Vector< Real > > x_
Detailed Description
template<class Real>
class ROL::AugmentedSystemPrecOperator< Real >
Implements a preconditioner for the augmented system.
Definition at line 26 of file ROL_AugmentedSystemPrecOperator.hpp.
Constructor & Destructor Documentation
~AugmentedSystemPrecOperator()
template<class Real > virtual ROL::AugmentedSystemPrecOperator< Real >::~AugmentedSystemPrecOperator () inline virtual
Definition at line 32 of file ROL_AugmentedSystemPrecOperator.hpp.
AugmentedSystemPrecOperator()
template<class Real > ROL::AugmentedSystemPrecOperator< Real >::AugmentedSystemPrecOperator (const Ptr< Constraint< Real > > & con, const Ptr< const Vector< Real > > & x) inline
Definition at line 33 of file ROL_AugmentedSystemPrecOperator.hpp.
Member Function Documentation
apply()
template<class Real > void ROL::AugmentedSystemPrecOperator< Real >::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 37 of file ROL_AugmentedSystemPrecOperator.hpp.
applyAdjoint()
template<class Real > void ROL::AugmentedSystemPrecOperator< Real >::applyAdjoint (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of linear operator.
This function applies the adjoint of a linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 41 of file ROL_AugmentedSystemPrecOperator.hpp.
applyInverse()
template<class Real > void ROL::AugmentedSystemPrecOperator< Real >::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 45 of file ROL_AugmentedSystemPrecOperator.hpp.
References ROL::AugmentedSystemPrecOperator< Real >::con_, ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::set(), ROL::AugmentedSystemPrecOperator< Real >::x_, and zero.
Referenced by ROL::AugmentedSystemPrecOperator< Real >::applyAdjointInverse().
applyAdjointInverse()
template<class Real > void ROL::AugmentedSystemPrecOperator< Real >::applyAdjointInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of the inverse linear operator.
This function applies the adjoint of the inverse linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 55 of file ROL_AugmentedSystemPrecOperator.hpp.
References ROL::AugmentedSystemPrecOperator< Real >::applyInverse().
Member Data Documentation
con_
template<class Real > const Ptr<Constraint<Real> > ROL::AugmentedSystemPrecOperator< Real >::con_ private
Definition at line 28 of file ROL_AugmentedSystemPrecOperator.hpp.
Referenced by ROL::AugmentedSystemPrecOperator< Real >::applyInverse().
x_
template<class Real > const Ptr<const Vector<Real> > ROL::AugmentedSystemPrecOperator< Real >::x_ private
Definition at line 29 of file ROL_AugmentedSystemPrecOperator.hpp.
Referenced by ROL::AugmentedSystemPrecOperator< Real >::applyInverse().
The documentation for this class was generated from the following file:
ROL_AugmentedSystemPrecOperator.hpp