ROL: ROL::TypeP::QuasiNewtonAlgorithm< Real > Class Template Reference
ROL::TypeP::QuasiNewtonAlgorithm< Real > Class Template Reference
Provides an interface to run the projected secant algorithm.
#include <ROL_TypeP_QuasiNewtonAlgorithm.hpp>
Public Member Functions
QuasiNewtonAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout) override
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeP::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, Vector< Real > &dg, std::ostream &outStream=std::cout)
Private Attributes
Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ESecant esec_
Secant type.
std::string secantName_
Secant name.
Real t0_
bool initProx_
int maxit_
Maximum number of line search steps (default: 20)
Real rhodec_
Backtracking rate (default: 0.5)
Real c1_
Sufficient Decrease Parameter (default: 1e-4)
Real sigma1_
Lower safeguard for quadratic line search (default: 0.1)
Real sigma2_
Upper safeguard for quadratic line search (default: 0.9)
Real sp_tol1_
Real sp_tol2_
Real sp_tol_min_
std::string algoName_
ParameterList list_
bool hasLEC_
int ls_nfval_
int spgIter_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeP::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void pgstep (Vector< Real > &pgiter, Vector< Real > &pgstep, Objective< Real > &nobj, const Vector< Real > &x, const Vector< Real > &dg, Real t, Real &tol) const
Protected Attributes inherited from ROL::TypeP::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeP::QuasiNewtonAlgorithm< Real >
Provides an interface to run the projected secant algorithm.
Definition at line 24 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Constructor & Destructor Documentation
QuasiNewtonAlgorithm()
template<typename Real > ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 22 of file ROL_TypeP_QuasiNewtonAlgorithm_Def.hpp.
References ROL::TypeP::QuasiNewtonAlgorithm< Real >::algoName_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::c1_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::esec_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::initProx_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::list_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::maxit_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::rhodec_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::secant_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::secantName_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::sigma1_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::sigma2_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::sp_tol1_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::sp_tol2_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::sp_tol_min_, ROL::TypeP::Algorithm< Real >::status_, ROL::StringToESecant(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::t0_, ROL::TypeP::QuasiNewtonAlgorithm< Real >::verbosity_, and ROL::TypeP::QuasiNewtonAlgorithm< Real >::writeHeader_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeP::QuasiNewtonAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, Vector< Real > & dg, std::ostream & outStream = std::cout) private
Definition at line 63 of file ROL_TypeP_QuasiNewtonAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeP::Algorithm< Real >::initialize(), ROL::Objective< Real >::prox(), ROL::Vector< Real >::set(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeP::QuasiNewtonAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, std::ostream & outStream = std::cout) override virtual
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeP::Algorithm< Real >.
Definition at line 92 of file ROL_TypeP_QuasiNewtonAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeP::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeP::QuasiNewtonAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 206 of file ROL_TypeP_QuasiNewtonAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeP::QuasiNewtonAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 243 of file ROL_TypeP_QuasiNewtonAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeP::QuasiNewtonAlgorithm< Real >::writeOutput (std::ostream & os, bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 250 of file ROL_TypeP_QuasiNewtonAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > Ptr<Secant<Real> > ROL::TypeP::QuasiNewtonAlgorithm< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 26 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
esec_
template<typename Real > ESecant ROL::TypeP::QuasiNewtonAlgorithm< Real >::esec_ private
Secant type.
Definition at line 27 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
secantName_
template<typename Real > std::string ROL::TypeP::QuasiNewtonAlgorithm< Real >::secantName_ private
Secant name.
Definition at line 28 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
t0_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::t0_ private
Definition at line 30 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
initProx_
template<typename Real > bool ROL::TypeP::QuasiNewtonAlgorithm< Real >::initProx_ private
Definition at line 31 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
maxit_
template<typename Real > int ROL::TypeP::QuasiNewtonAlgorithm< Real >::maxit_ private
Maximum number of line search steps (default: 20)
Definition at line 33 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
rhodec_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::rhodec_ private
Backtracking rate (default: 0.5)
Definition at line 34 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
c1_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::c1_ private
Sufficient Decrease Parameter (default: 1e-4)
Definition at line 35 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sigma1_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::sigma1_ private
Lower safeguard for quadratic line search (default: 0.1)
Definition at line 36 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sigma2_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::sigma2_ private
Upper safeguard for quadratic line search (default: 0.9)
Definition at line 37 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sp_tol1_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::sp_tol1_ private
Definition at line 38 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sp_tol2_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::sp_tol2_ private
Definition at line 39 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
sp_tol_min_
template<typename Real > Real ROL::TypeP::QuasiNewtonAlgorithm< Real >::sp_tol_min_ private
Definition at line 40 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
algoName_
template<typename Real > std::string ROL::TypeP::QuasiNewtonAlgorithm< Real >::algoName_ private
Definition at line 41 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
list_
template<typename Real > ParameterList ROL::TypeP::QuasiNewtonAlgorithm< Real >::list_ private
Definition at line 43 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
hasLEC_
template<typename Real > bool ROL::TypeP::QuasiNewtonAlgorithm< Real >::hasLEC_ private
Definition at line 45 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
ls_nfval_
template<typename Real > int ROL::TypeP::QuasiNewtonAlgorithm< Real >::ls_nfval_ private
Definition at line 46 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
spgIter_
template<typename Real > int ROL::TypeP::QuasiNewtonAlgorithm< Real >::spgIter_ private
Definition at line 46 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeP::QuasiNewtonAlgorithm< Real >::verbosity_ private
Definition at line 47 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
writeHeader_
template<typename Real > bool ROL::TypeP::QuasiNewtonAlgorithm< Real >::writeHeader_ private
Definition at line 48 of file ROL_TypeP_QuasiNewtonAlgorithm.hpp.
Referenced by ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
The documentation for this class was generated from the following files:
ROL_TypeP_QuasiNewtonAlgorithm.hpp
ROL_TypeP_QuasiNewtonAlgorithm_Def.hpp