ROL: ROL::l1Objective< Real > Class Template Reference
ROL::l1Objective< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate the weighted/shifted l1 objective function.
#include <ROL_l1Objective.hpp>
Classes
struct ProjSymBnd
Public Member Functions
l1Objective (const Ptr< Vector< Real > > &weights)
l1Objective (const Ptr< Vector< Real > > &weights, const Ptr< Vector< Real > > &shift)
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
const Ptr< Vector< Real > > weights_
const Ptr< Vector< Real > > shift_
Ptr< Vector< Real > > tmp_
ROL::l1Objective::ProjSymBnd psb_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::l1Objective< Real >
Provides the interface to evaluate the weighted/shifted l1 objective function.
Definition at line 26 of file ROL_l1Objective.hpp.
Constructor & Destructor Documentation
l1Objective() [1/2]
template<typename Real > ROL::l1Objective< Real >::l1Objective (const Ptr< Vector< Real > > & weights) inline
Definition at line 37 of file ROL_l1Objective.hpp.
References ROL::l1Objective< Real >::shift_, and ROL::l1Objective< Real >::tmp_.
l1Objective() [2/2]
template<typename Real > ROL::l1Objective< Real >::l1Objective (const Ptr< Vector< Real > > & weights, const Ptr< Vector< Real > > & shift) inline
Definition at line 43 of file ROL_l1Objective.hpp.
References ROL::l1Objective< Real >::shift_, and ROL::l1Objective< Real >::tmp_.
Member Function Documentation
value()
template<typename Real > Real ROL::l1Objective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 48 of file ROL_l1Objective.hpp.
References ROL::l1Objective< Real >::shift_, ROL::l1Objective< Real >::tmp_, and ROL::l1Objective< Real >::weights_.
gradient()
template<typename Real > void ROL::l1Objective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 55 of file ROL_l1Objective.hpp.
References ROL::Vector< Real >::applyBinary(), ROL::Vector< Real >::applyUnary(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::set(), ROL::l1Objective< Real >::shift_, and ROL::l1Objective< Real >::weights_.
Referenced by ROL::l1Objective< Real >::dirDeriv().
dirDeriv()
template<typename Real > Real ROL::l1Objective< Real >::dirDeriv (const Vector< Real > & x, const Vector< Real > & d, Real & tol) inline virtual
Compute directional derivative.
This function returns the directional derivative of the objective function in the \(d\) direction.
Parameters
[in] x is the current iterate.
[in] d is the direction.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 62 of file ROL_l1Objective.hpp.
References ROL::l1Objective< Real >::gradient(), and ROL::l1Objective< Real >::tmp_.
prox()
template<typename Real > void ROL::l1Objective< Real >::prox (Vector< Real > & Pv, const Vector< Real > & v, Real t, Real & tol) inline virtual
Compute the proximity operator.
This function returns the proximity operator.
Parameters
[out] Pv is the proximity operator applied to \(v\) (primal optimization vector).
[in] v is the input to the proximity operator (primal optimization vector).
[in] t is the proximity operator parameter (positive scalar).
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 67 of file ROL_l1Objective.hpp.
References ROL::Vector< Real >::applyBinary(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::plus(), ROL::l1Objective< Real >::psb_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::l1Objective< Real >::shift_, and ROL::l1Objective< Real >::weights_.
Member Data Documentation
weights_
template<typename Real > const Ptr<Vector<Real> > ROL::l1Objective< Real >::weights_ private
Definition at line 28 of file ROL_l1Objective.hpp.
Referenced by ROL::l1Objective< Real >::gradient(), ROL::l1Objective< Real >::prox(), and ROL::l1Objective< Real >::value().
shift_
template<typename Real > const Ptr<Vector<Real> > ROL::l1Objective< Real >::shift_ private
Definition at line 28 of file ROL_l1Objective.hpp.
Referenced by ROL::l1Objective< Real >::gradient(), ROL::l1Objective< Real >::l1Objective(), ROL::l1Objective< Real >::l1Objective(), ROL::l1Objective< Real >::prox(), and ROL::l1Objective< Real >::value().
tmp_
template<typename Real > Ptr<Vector<Real> > ROL::l1Objective< Real >::tmp_ private
Definition at line 29 of file ROL_l1Objective.hpp.
Referenced by ROL::l1Objective< Real >::dirDeriv(), ROL::l1Objective< Real >::l1Objective(), ROL::l1Objective< Real >::l1Objective(), and ROL::l1Objective< Real >::value().
psb_
template<typename Real > ROL::l1Objective::ProjSymBnd ROL::l1Objective< Real >::psb_ private
Referenced by ROL::l1Objective< Real >::prox().
The documentation for this class was generated from the following file:
ROL_l1Objective.hpp