ROL: ROL::Bundle_AS< Real > Class Template Reference
ROL::Bundle_AS< Real > Class Template Reference
Provides the interface for and implements an active set bundle.
#include <ROL_Bundle_AS.hpp>
Public Member Functions
Bundle_AS (const unsigned maxSize=10, const Real coeff=0.0, const Real omega=2.0, const unsigned remSize=2)
void initialize (const Vector< Real > &g)
unsigned solveDual (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
Public Member Functions inherited from ROL::Bundle< Real >
virtual ~Bundle (void)
Bundle (const unsigned maxSize=10, const Real coeff=0.0, const Real omega=2.0, const unsigned remSize=2)
const Real linearizationError (const unsigned i) const
const Real distanceMeasure (const unsigned i) const
const Vector< Real > & subgradient (const unsigned i) const
const Real getDualVariable (const unsigned i) const
void setDualVariable (const unsigned i, const Real val)
void resetDualVariables (void)
const Real computeAlpha (const Real dm, const Real le) const
const Real alpha (const unsigned i) const
unsigned size (void) const
void aggregate (Vector< Real > &aggSubGrad, Real &aggLinErr, Real &aggDistMeas) const
void reset (const Vector< Real > &g, const Real le, const Real dm)
void update (const bool flag, const Real linErr, const Real distMeas, const Vector< Real > &g, const Vector< Real > &s)
Private Member Functions
void initializeDualSolver (void)
void computeLagMult (std::vector< Real > &lam, const Real mu, const std::vector< Real > &g) const
bool isNonnegative (unsigned &ind, const std::vector< Real > &x) const
Real computeStepSize (unsigned &ind, const std::vector< Real > &x, const std::vector< Real > &p) const
unsigned solveEQPsubproblem (std::vector< Real > &s, Real &mu, const std::vector< Real > &g, const Real tol) const
void applyPreconditioner (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG (std::vector< Real > &Gx, const std::vector< Real > &x) const
void applyPreconditioner_Identity (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG_Identity (std::vector< Real > &Gx, const std::vector< Real > &x) const
void applyPreconditioner_Jacobi (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG_Jacobi (std::vector< Real > &Gx, const std::vector< Real > &x) const
void applyPreconditioner_SymGS (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG_SymGS (std::vector< Real > &Gx, const std::vector< Real > &x) const
void computeResidualUpdate (std::vector< Real > &r, std::vector< Real > &g) const
void applyFullMatrix (std::vector< Real > &Hx, const std::vector< Real > &x) const
void applyMatrix (std::vector< Real > &Hx, const std::vector< Real > &x) const
unsigned projectedCG (std::vector< Real > &x, Real &mu, const std::vector< Real > &b, const Real tol) const
Real dot (const std::vector< Real > &x, const std::vector< Real > &y) const
Real norm (const std::vector< Real > &x) const
void axpy (const Real a, const std::vector< Real > &x, std::vector< Real > &y) const
void scale (std::vector< Real > &x, const Real a) const
void scale (std::vector< Real > &x, const Real a, const std::vector< Real > &y) const
unsigned solveDual_arbitrary (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
void project (std::vector< Real > &x, const std::vector< Real > &v) const
Real computeCriticality (const std::vector< Real > &g, const std::vector< Real > &sol)
Private Attributes
ROL::Ptr< Vector< Real > > tG_
ROL::Ptr< Vector< Real > > eG_
ROL::Ptr< Vector< Real > > yG_
ROL::Ptr< Vector< Real > > gx_
ROL::Ptr< Vector< Real > > ge_
std::set< unsigned > workingSet_
std::set< unsigned > nworkingSet_
bool isInitialized_
Additional Inherited Members
Protected Member Functions inherited from ROL::Bundle< Real >
const Real GiGj (const unsigned i, const unsigned j) const
const Real dotGi (const unsigned i, const Vector< Real > &x) const
void addGi (const unsigned i, const Real a, Vector< Real > &x) const
Real evaluateObjective (std::vector< Real > &g, const std::vector< Real > &x, const Real t) const
unsigned solveDual_dim1 (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
unsigned solveDual_dim2 (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
Detailed Description
template<class Real>
class ROL::Bundle_AS< Real >
Provides the interface for and implements an active set bundle.
Definition at line 22 of file ROL_Bundle_AS.hpp.
Constructor & Destructor Documentation
Bundle_AS()
template<class Real > ROL::Bundle_AS< Real >::Bundle_AS (const unsigned maxSize = 10, const Real coeff = 0.0, const Real omega = 2.0, const unsigned remSize = 2) inline
Definition at line 43 of file ROL_Bundle_AS.hpp.
Member Function Documentation
initialize()
template<class Real > void ROL::Bundle_AS< Real >::initialize (const Vector< Real > & g) inline virtual
Reimplemented from ROL::Bundle< Real >.
Definition at line 49 of file ROL_Bundle_AS.hpp.
References ROL::Vector< Real >::clone(), ROL::Bundle_AS< Real >::eG_, ROL::Bundle_AS< Real >::ge_, ROL::Bundle_AS< Real >::gx_, ROL::Bundle< Real >::initialize(), ROL::Bundle_AS< Real >::isInitialized_, ROL::Bundle_AS< Real >::tG_, and ROL::Bundle_AS< Real >::yG_.
solveDual()
template<class Real > unsigned ROL::Bundle_AS< Real >::solveDual (const Real t, const unsigned maxit = 1000, const Real tol = 1.e-8) inline virtual
Implements ROL::Bundle< Real >.
Definition at line 61 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::solveDual_arbitrary(), ROL::Bundle< Real >::solveDual_dim1(), and ROL::Bundle< Real >::solveDual_dim2().
initializeDualSolver()
template<class Real > void ROL::Bundle_AS< Real >::initializeDualSolver (void) inline private
Definition at line 79 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::getDualVariable(), ROL::Bundle_AS< Real >::nworkingSet_, ROL::Bundle< Real >::setDualVariable(), ROL::Bundle_AS< Real >::workingSet_, and zero.
Referenced by ROL::Bundle_AS< Real >::solveDual_arbitrary().
computeLagMult()
template<class Real > void ROL::Bundle_AS< Real >::computeLagMult (std::vector< Real > & lam, const Real mu, const std::vector< Real > & g) const inline private
Definition at line 105 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::workingSet_, and zero.
Referenced by ROL::Bundle_AS< Real >::solveDual_arbitrary().
isNonnegative()
template<class Real > bool ROL::Bundle_AS< Real >::isNonnegative (unsigned & ind, const std::vector< Real > & x) const inline private
Definition at line 120 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::size(), and ROL::Bundle_AS< Real >::workingSet_.
Referenced by ROL::Bundle_AS< Real >::solveDual_arbitrary().
computeStepSize()
template<class Real > Real ROL::Bundle_AS< Real >::computeStepSize (unsigned & ind, const std::vector< Real > & x, const std::vector< Real > & p) const inline private
Definition at line 138 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::alpha(), ROL::Bundle_AS< Real >::nworkingSet_, ROL::Bundle< Real >::size(), and zero.
Referenced by ROL::Bundle_AS< Real >::solveDual_arbitrary().
solveEQPsubproblem()
template<class Real > unsigned ROL::Bundle_AS< Real >::solveEQPsubproblem (std::vector< Real > & s, Real & mu, const std::vector< Real > & g, const Real tol) const inline private
Definition at line 153 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::nworkingSet_, ROL::Bundle_AS< Real >::projectedCG(), and zero.
Referenced by ROL::Bundle_AS< Real >::solveDual_arbitrary().
applyPreconditioner()
template<class Real > void ROL::Bundle_AS< Real >::applyPreconditioner (std::vector< Real > & Px, const std::vector< Real > & x) const inline private
Definition at line 176 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::applyPreconditioner_Identity(), ROL::Bundle_AS< Real >::applyPreconditioner_Jacobi(), ROL::Bundle_AS< Real >::applyPreconditioner_SymGS(), and zero.
Referenced by ROL::Bundle_AS< Real >::computeResidualUpdate().
applyG()
template<class Real > void ROL::Bundle_AS< Real >::applyG (std::vector< Real > & Gx, const std::vector< Real > & x) const inline private
Definition at line 188 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::applyG_Identity(), ROL::Bundle_AS< Real >::applyG_Jacobi(), and ROL::Bundle_AS< Real >::applyG_SymGS().
Referenced by ROL::Bundle_AS< Real >::computeResidualUpdate().
applyPreconditioner_Identity()
template<class Real > void ROL::Bundle_AS< Real >::applyPreconditioner_Identity (std::vector< Real > & Px, const std::vector< Real > & x) const inline private
Definition at line 197 of file ROL_Bundle_AS.hpp.
References dim, and ROL::Bundle_AS< Real >::nworkingSet_.
Referenced by ROL::Bundle_AS< Real >::applyPreconditioner().
applyG_Identity()
template<class Real > void ROL::Bundle_AS< Real >::applyG_Identity (std::vector< Real > & Gx, const std::vector< Real > & x) const inline private
Definition at line 214 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::applyG().
applyPreconditioner_Jacobi()
template<class Real > void ROL::Bundle_AS< Real >::applyPreconditioner_Jacobi (std::vector< Real > & Px, const std::vector< Real > & x) const inline private
Definition at line 218 of file ROL_Bundle_AS.hpp.
References dim, ROL::Bundle_AS< Real >::nworkingSet_, and zero.
Referenced by ROL::Bundle_AS< Real >::applyPreconditioner().
applyG_Jacobi()
template<class Real > void ROL::Bundle_AS< Real >::applyG_Jacobi (std::vector< Real > & Gx, const std::vector< Real > & x) const inline private
Definition at line 245 of file ROL_Bundle_AS.hpp.
References dim, and ROL::Bundle_AS< Real >::nworkingSet_.
Referenced by ROL::Bundle_AS< Real >::applyG().
applyPreconditioner_SymGS()
template<class Real > void ROL::Bundle_AS< Real >::applyPreconditioner_SymGS (std::vector< Real > & Px, const std::vector< Real > & x) const inline private
Definition at line 253 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::addGi(), dim, ROL::Bundle< Real >::dotGi(), ROL::Bundle_AS< Real >::ge_, ROL::Bundle< Real >::GiGj(), ROL::Bundle_AS< Real >::gx_, and ROL::Bundle_AS< Real >::nworkingSet_.
Referenced by ROL::Bundle_AS< Real >::applyPreconditioner().
applyG_SymGS()
template<class Real > void ROL::Bundle_AS< Real >::applyG_SymGS (std::vector< Real > & Gx, const std::vector< Real > & x) const inline private
Definition at line 301 of file ROL_Bundle_AS.hpp.
References dim, and ROL::Bundle_AS< Real >::nworkingSet_.
Referenced by ROL::Bundle_AS< Real >::applyG().
computeResidualUpdate()
template<class Real > void ROL::Bundle_AS< Real >::computeResidualUpdate (std::vector< Real > & r, std::vector< Real > & g) const inline private
Definition at line 309 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::applyG(), and ROL::Bundle_AS< Real >::applyPreconditioner().
Referenced by ROL::Bundle_AS< Real >::projectedCG().
applyFullMatrix()
template<class Real > void ROL::Bundle_AS< Real >::applyFullMatrix (std::vector< Real > & Hx, const std::vector< Real > & x) const inline private
Definition at line 330 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::dotGi(), ROL::Bundle_AS< Real >::eG_, ROL::Bundle_AS< Real >::gx_, ROL::Bundle_AS< Real >::tG_, and ROL::Bundle_AS< Real >::yG_.
Referenced by ROL::Bundle_AS< Real >::solveDual_arbitrary().
applyMatrix()
template<class Real > void ROL::Bundle_AS< Real >::applyMatrix (std::vector< Real > & Hx, const std::vector< Real > & x) const inline private
Definition at line 347 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::dotGi(), ROL::Bundle_AS< Real >::eG_, ROL::Bundle_AS< Real >::gx_, ROL::Bundle_AS< Real >::nworkingSet_, ROL::Bundle_AS< Real >::tG_, and ROL::Bundle_AS< Real >::yG_.
Referenced by ROL::Bundle_AS< Real >::projectedCG().
projectedCG()
template<class Real > unsigned ROL::Bundle_AS< Real >::projectedCG (std::vector< Real > & x, Real & mu, const std::vector< Real > & b, const Real tol) const inline private
Definition at line 368 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::alpha(), ROL::Bundle_AS< Real >::applyMatrix(), ROL::Bundle_AS< Real >::axpy(), ROL::Bundle_AS< Real >::computeResidualUpdate(), ROL::Bundle_AS< Real >::dot(), ROL::Bundle_AS< Real >::nworkingSet_, ROL::Bundle_AS< Real >::scale(), and zero.
Referenced by ROL::Bundle_AS< Real >::solveEQPsubproblem().
dot()
template<class Real > Real ROL::Bundle_AS< Real >::dot (const std::vector< Real > & x, const std::vector< Real > & y) const inline private
Definition at line 414 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::norm(), and ROL::Bundle_AS< Real >::projectedCG().
norm()
template<class Real > Real ROL::Bundle_AS< Real >::norm (const std::vector< Real > & x) const inline private
Definition at line 428 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::dot().
Referenced by ROL::Bundle_AS< Real >::computeCriticality(), and ROL::Bundle_AS< Real >::solveDual_arbitrary().
axpy()
template<class Real > void ROL::Bundle_AS< Real >::axpy (const Real a, const std::vector< Real > & x, std::vector< Real > & y) const inline private
Definition at line 432 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::computeCriticality(), ROL::Bundle_AS< Real >::projectedCG(), and ROL::Bundle_AS< Real >::solveDual_arbitrary().
scale() [1/2]
template<class Real > void ROL::Bundle_AS< Real >::scale (std::vector< Real > & x, const Real a) const inline private
Definition at line 439 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::computeCriticality(), and ROL::Bundle_AS< Real >::projectedCG().
scale() [2/2]
template<class Real > void ROL::Bundle_AS< Real >::scale (std::vector< Real > & x, const Real a, const std::vector< Real > & y) const inline private
Definition at line 445 of file ROL_Bundle_AS.hpp.
solveDual_arbitrary()
template<class Real > unsigned ROL::Bundle_AS< Real >::solveDual_arbitrary (const Real t, const unsigned maxit = 1000, const Real tol = 1.e-8) inline private
Definition at line 452 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::alpha(), ROL::Bundle_AS< Real >::applyFullMatrix(), ROL::Bundle_AS< Real >::axpy(), ROL::Bundle_AS< Real >::computeLagMult(), ROL::Bundle_AS< Real >::computeStepSize(), ROL::Bundle< Real >::evaluateObjective(), ROL::Bundle< Real >::getDualVariable(), ROL::Bundle_AS< Real >::initializeDualSolver(), ROL::Bundle_AS< Real >::isNonnegative(), ROL::Bundle_AS< Real >::norm(), ROL::Bundle_AS< Real >::nworkingSet_, ROL::Bundle< Real >::setDualVariable(), ROL::Bundle_AS< Real >::solveEQPsubproblem(), ROL::Bundle_AS< Real >::workingSet_, and zero.
Referenced by ROL::Bundle_AS< Real >::solveDual().
project()
template<class Real > void ROL::Bundle_AS< Real >::project (std::vector< Real > & x, const std::vector< Real > & v) const inline private
Definition at line 508 of file ROL_Bundle_AS.hpp.
References ROL::Bundle< Real >::size(), and zero.
Referenced by ROL::Bundle_AS< Real >::computeCriticality().
computeCriticality()
template<class Real > Real ROL::Bundle_AS< Real >::computeCriticality (const std::vector< Real > & g, const std::vector< Real > & sol) inline private
Definition at line 528 of file ROL_Bundle_AS.hpp.
References ROL::Bundle_AS< Real >::axpy(), ROL::Bundle_AS< Real >::norm(), ROL::Bundle_AS< Real >::project(), ROL::Bundle_AS< Real >::scale(), and zero.
Member Data Documentation
tG_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle_AS< Real >::tG_ private
Definition at line 28 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::applyFullMatrix(), ROL::Bundle_AS< Real >::applyMatrix(), and ROL::Bundle_AS< Real >::initialize().
eG_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle_AS< Real >::eG_ private
Definition at line 29 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::applyFullMatrix(), ROL::Bundle_AS< Real >::applyMatrix(), and ROL::Bundle_AS< Real >::initialize().
yG_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle_AS< Real >::yG_ private
Definition at line 30 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::applyFullMatrix(), ROL::Bundle_AS< Real >::applyMatrix(), and ROL::Bundle_AS< Real >::initialize().
gx_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle_AS< Real >::gx_ private
Definition at line 31 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::applyFullMatrix(), ROL::Bundle_AS< Real >::applyMatrix(), ROL::Bundle_AS< Real >::applyPreconditioner_SymGS(), and ROL::Bundle_AS< Real >::initialize().
ge_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle_AS< Real >::ge_ private
Definition at line 32 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::applyPreconditioner_SymGS(), and ROL::Bundle_AS< Real >::initialize().
workingSet_
template<class Real > std::set<unsigned> ROL::Bundle_AS< Real >::workingSet_ private
Definition at line 34 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::computeLagMult(), ROL::Bundle_AS< Real >::initializeDualSolver(), ROL::Bundle_AS< Real >::isNonnegative(), and ROL::Bundle_AS< Real >::solveDual_arbitrary().
nworkingSet_
template<class Real > std::set<unsigned> ROL::Bundle_AS< Real >::nworkingSet_ private
Definition at line 35 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::applyG_Jacobi(), ROL::Bundle_AS< Real >::applyG_SymGS(), ROL::Bundle_AS< Real >::applyMatrix(), ROL::Bundle_AS< Real >::applyPreconditioner_Identity(), ROL::Bundle_AS< Real >::applyPreconditioner_Jacobi(), ROL::Bundle_AS< Real >::applyPreconditioner_SymGS(), ROL::Bundle_AS< Real >::computeStepSize(), ROL::Bundle_AS< Real >::initializeDualSolver(), ROL::Bundle_AS< Real >::projectedCG(), ROL::Bundle_AS< Real >::solveDual_arbitrary(), and ROL::Bundle_AS< Real >::solveEQPsubproblem().
isInitialized_
template<class Real > bool ROL::Bundle_AS< Real >::isInitialized_ private
Definition at line 37 of file ROL_Bundle_AS.hpp.
Referenced by ROL::Bundle_AS< Real >::initialize().
The documentation for this class was generated from the following file:
ROL_Bundle_AS.hpp