ROL: ROL::NewtonKrylovStep< Real > Class Template Reference
ROL::NewtonKrylovStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with projected inexact Newton's method using line search.
#include <ROL_NewtonKrylovStep.hpp>
Classes
class HessianNK
class PrecondNK
Public Member Functions
NewtonKrylovStep (ROL::ParameterList &parlist, const bool computeObj=true)
Constructor.
NewtonKrylovStep (ROL::ParameterList &parlist, const ROL::Ptr< Krylov< Real > > &krylov, const ROL::Ptr< Secant< Real > > &secant, const bool computeObj=true)
Constructor.
void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool print_header=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Attributes
ROL::Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ROL::Ptr< Krylov< Real > > krylov_
Krylov solver object (used for inexact Newton)
EKrylov ekv_
ESecant esec_
ROL::Ptr< Vector< Real > > gp_
int iterKrylov_
Number of Krylov iterations (used for inexact Newton)
int flagKrylov_
Termination flag for Krylov method (used for inexact Newton)
int verbosity_
Verbosity level.
const bool computeObj_
bool useSecantPrecond_
Whether or not a secant approximation is used for preconditioning inexact Newton.
std::string krylovName_
std::string secantName_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::NewtonKrylovStep< Real >
Provides the interface to compute optimization steps with projected inexact Newton's method using line search.
Definition at line 32 of file ROL_NewtonKrylovStep.hpp.
Constructor & Destructor Documentation
NewtonKrylovStep() [1/2]
template<class Real > ROL::NewtonKrylovStep< Real >::NewtonKrylovStep (ROL::ParameterList & parlist, const bool computeObj = true) inline
Constructor.
Standard constructor to build a NewtonKrylovStep object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
Definition at line 94 of file ROL_NewtonKrylovStep.hpp.
References ROL::NewtonKrylovStep< Real >::ekv_, ROL::NewtonKrylovStep< Real >::esec_, ROL::NewtonKrylovStep< Real >::krylov_, ROL::NewtonKrylovStep< Real >::krylovName_, ROL::NewtonKrylovStep< Real >::secant_, ROL::NewtonKrylovStep< Real >::secantName_, ROL::StringToEKrylov(), ROL::StringToESecant(), ROL::NewtonKrylovStep< Real >::useSecantPrecond_, and ROL::NewtonKrylovStep< Real >::verbosity_.
NewtonKrylovStep() [2/2]
template<class Real > ROL::NewtonKrylovStep< Real >::NewtonKrylovStep (ROL::ParameterList & parlist, const ROL::Ptr< Krylov< Real > > & krylov, const ROL::Ptr< Secant< Real > > & secant, const bool computeObj = true) inline
Constructor.
Constructor to build a NewtonKrylovStep object with user-defined secant and Krylov objects. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
[in] krylov is a user-defined Krylov object
[in] secant is a user-defined secant object
Definition at line 124 of file ROL_NewtonKrylovStep.hpp.
References ROL::NewtonKrylovStep< Real >::ekv_, ROL::NewtonKrylovStep< Real >::esec_, ROL::NewtonKrylovStep< Real >::krylov_, ROL::NewtonKrylovStep< Real >::krylovName_, ROL::NewtonKrylovStep< Real >::secant_, ROL::NewtonKrylovStep< Real >::secantName_, ROL::StringToEKrylov(), ROL::StringToESecant(), ROL::NewtonKrylovStep< Real >::useSecantPrecond_, and ROL::NewtonKrylovStep< Real >::verbosity_.
Member Function Documentation
initialize()
template<class Real > void ROL::NewtonKrylovStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with bound constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 160 of file ROL_NewtonKrylovStep.hpp.
References ROL::Vector< Real >::clone(), ROL::NewtonKrylovStep< Real >::gp_, ROL::Step< Real >::initialize(), and ROL::NewtonKrylovStep< Real >::useSecantPrecond_.
compute()
template<class Real > void ROL::NewtonKrylovStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 169 of file ROL_NewtonKrylovStep.hpp.
References ROL::NewtonKrylovStep< Real >::flagKrylov_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::iterateVec, ROL::NewtonKrylovStep< Real >::iterKrylov_, ROL::NewtonKrylovStep< Real >::krylov_, ROL::Vector< Real >::scale(), ROL::NewtonKrylovStep< Real >::secant_, ROL::Vector< Real >::set(), and ROL::NewtonKrylovStep< Real >::useSecantPrecond_.
update()
template<class Real > void ROL::NewtonKrylovStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 198 of file ROL_NewtonKrylovStep.hpp.
References ROL::NewtonKrylovStep< Real >::computeObj_, ROL::NewtonKrylovStep< Real >::flagKrylov_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::NewtonKrylovStep< Real >::gp_, ROL::Objective< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::NewtonKrylovStep< Real >::iterKrylov_, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::NewtonKrylovStep< Real >::secant_, ROL::AlgorithmState< Real >::snorm, ROL::Objective< Real >::update(), ROL::NewtonKrylovStep< Real >::useSecantPrecond_, ROL::Objective< Real >::value(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::NewtonKrylovStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 234 of file ROL_NewtonKrylovStep.hpp.
References ROL::DESCENT_NEWTONKRYLOV, ROL::EDescentToString(), and ROL::NewtonKrylovStep< Real >::verbosity_.
Referenced by ROL::NewtonKrylovStep< Real >::print().
printName()
template<class Real > std::string ROL::NewtonKrylovStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 264 of file ROL_NewtonKrylovStep.hpp.
References ROL::DESCENT_NEWTONKRYLOV, ROL::EDescentToString(), ROL::NewtonKrylovStep< Real >::esec_, ROL::ESecantToString(), ROL::NewtonKrylovStep< Real >::krylovName_, and ROL::NewtonKrylovStep< Real >::useSecantPrecond_.
Referenced by ROL::NewtonKrylovStep< Real >::print().
print()
template<class Real > std::string ROL::NewtonKrylovStep< Real >::print (AlgorithmState< Real > & algo_state, bool printHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 274 of file ROL_NewtonKrylovStep.hpp.
References ROL::NewtonKrylovStep< Real >::flagKrylov_, ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::NewtonKrylovStep< Real >::iterKrylov_, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::NewtonKrylovStep< Real >::printHeader(), ROL::NewtonKrylovStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
secant_
template<class Real > ROL::Ptr<Secant<Real> > ROL::NewtonKrylovStep< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 35 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), and ROL::NewtonKrylovStep< Real >::update().
krylov_
template<class Real > ROL::Ptr<Krylov<Real> > ROL::NewtonKrylovStep< Real >::krylov_ private
Krylov solver object (used for inexact Newton)
Definition at line 36 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), and ROL::NewtonKrylovStep< Real >::NewtonKrylovStep().
ekv_
template<class Real > EKrylov ROL::NewtonKrylovStep< Real >::ekv_ private
Definition at line 38 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), and ROL::NewtonKrylovStep< Real >::NewtonKrylovStep().
esec_
template<class Real > ESecant ROL::NewtonKrylovStep< Real >::esec_ private
Definition at line 39 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), and ROL::NewtonKrylovStep< Real >::printName().
gp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::NewtonKrylovStep< Real >::gp_ private
Definition at line 41 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::initialize(), and ROL::NewtonKrylovStep< Real >::update().
iterKrylov_
template<class Real > int ROL::NewtonKrylovStep< Real >::iterKrylov_ private
Number of Krylov iterations (used for inexact Newton)
Definition at line 43 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::print(), and ROL::NewtonKrylovStep< Real >::update().
flagKrylov_
template<class Real > int ROL::NewtonKrylovStep< Real >::flagKrylov_ private
Termination flag for Krylov method (used for inexact Newton)
Definition at line 44 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::print(), and ROL::NewtonKrylovStep< Real >::update().
verbosity_
template<class Real > int ROL::NewtonKrylovStep< Real >::verbosity_ private
Verbosity level.
Definition at line 45 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), and ROL::NewtonKrylovStep< Real >::printHeader().
computeObj_
template<class Real > const bool ROL::NewtonKrylovStep< Real >::computeObj_ private
Definition at line 46 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::update().
useSecantPrecond_
template<class Real > bool ROL::NewtonKrylovStep< Real >::useSecantPrecond_ private
Whether or not a secant approximation is used for preconditioning inexact Newton.
Definition at line 48 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::initialize(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::printName(), and ROL::NewtonKrylovStep< Real >::update().
krylovName_
template<class Real > std::string ROL::NewtonKrylovStep< Real >::krylovName_ private
Definition at line 50 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), and ROL::NewtonKrylovStep< Real >::printName().
secantName_
template<class Real > std::string ROL::NewtonKrylovStep< Real >::secantName_ private
Definition at line 51 of file ROL_NewtonKrylovStep.hpp.
Referenced by ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), and ROL::NewtonKrylovStep< Real >::NewtonKrylovStep().
The documentation for this class was generated from the following file:
ROL_NewtonKrylovStep.hpp