ROL: ROL::ProjectedSecantStep< Real > Class Template Reference
ROL::ProjectedSecantStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with projected secant method using line search.
#include <ROL_ProjectedSecantStep.hpp>
Public Member Functions
ProjectedSecantStep (ROL::ParameterList &parlist, const ROL::Ptr< Secant< Real > > &secant=ROL::nullPtr, const bool computeObj=true)
Constructor.
void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool print_header=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Attributes
ROL::Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ESecant esec_
ROL::Ptr< Vector< Real > > d_
Additional vector storage.
ROL::Ptr< Vector< Real > > gp_
Additional vector storage.
int verbosity_
Verbosity level.
const bool computeObj_
bool useProjectedGrad_
Whether or not to use to the projected gradient criticality measure.
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::ProjectedSecantStep< Real >
Provides the interface to compute optimization steps with projected secant method using line search.
Definition at line 26 of file ROL_ProjectedSecantStep.hpp.
Constructor & Destructor Documentation
ProjectedSecantStep()
template<class Real > ROL::ProjectedSecantStep< Real >::ProjectedSecantStep (ROL::ParameterList & parlist, const ROL::Ptr< Secant< Real > > & secant = ROL::nullPtr, const bool computeObj = true) inline
Constructor.
Standard constructor to build a ProjectedSecantStep object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
[in] secant is a user-defined secant object
Definition at line 51 of file ROL_ProjectedSecantStep.hpp.
References ROL::ProjectedSecantStep< Real >::esec_, ROL::ProjectedSecantStep< Real >::secant_, ROL::StringToESecant(), ROL::ProjectedSecantStep< Real >::useProjectedGrad_, and ROL::ProjectedSecantStep< Real >::verbosity_.
Member Function Documentation
initialize()
template<class Real > void ROL::ProjectedSecantStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with bound constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 68 of file ROL_ProjectedSecantStep.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedSecantStep< Real >::d_, ROL::ProjectedSecantStep< Real >::gp_, and ROL::Step< Real >::initialize().
compute()
template<class Real > void ROL::ProjectedSecantStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 76 of file ROL_ProjectedSecantStep.hpp.
References ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::ProjectedSecantStep< Real >::gp_, ROL::Vector< Real >::plus(), ROL::BoundConstraint< Real >::pruneActive(), ROL::BoundConstraint< Real >::pruneInactive(), ROL::Vector< Real >::scale(), and ROL::ProjectedSecantStep< Real >::secant_.
update()
template<class Real > void ROL::ProjectedSecantStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 95 of file ROL_ProjectedSecantStep.hpp.
References ROL::ProjectedSecantStep< Real >::computeObj_, ROL::BoundConstraint< Real >::computeProjectedGradient(), ROL::ProjectedSecantStep< Real >::d_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::ProjectedSecantStep< Real >::gp_, ROL::Objective< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::BoundConstraint< Real >::project(), ROL::ProjectedSecantStep< Real >::secant_, ROL::AlgorithmState< Real >::snorm, ROL::Objective< Real >::update(), ROL::ProjectedSecantStep< Real >::useProjectedGrad_, ROL::Objective< Real >::value(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::ProjectedSecantStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 139 of file ROL_ProjectedSecantStep.hpp.
References ROL::DESCENT_SECANT, ROL::EDescentToString(), and ROL::ProjectedSecantStep< Real >::verbosity_.
Referenced by ROL::ProjectedSecantStep< Real >::print().
printName()
template<class Real > std::string ROL::ProjectedSecantStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 165 of file ROL_ProjectedSecantStep.hpp.
References ROL::DESCENT_SECANT, ROL::EDescentToString(), ROL::ProjectedSecantStep< Real >::esec_, and ROL::ESecantToString().
Referenced by ROL::ProjectedSecantStep< Real >::print().
print()
template<class Real > std::string ROL::ProjectedSecantStep< Real >::print (AlgorithmState< Real > & algo_state, bool printHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 171 of file ROL_ProjectedSecantStep.hpp.
References ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::ProjectedSecantStep< Real >::printHeader(), ROL::ProjectedSecantStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
secant_
template<class Real > ROL::Ptr<Secant<Real> > ROL::ProjectedSecantStep< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 29 of file ROL_ProjectedSecantStep.hpp.
Referenced by ROL::ProjectedSecantStep< Real >::compute(), ROL::ProjectedSecantStep< Real >::ProjectedSecantStep(), and ROL::ProjectedSecantStep< Real >::update().
esec_
template<class Real > ESecant ROL::ProjectedSecantStep< Real >::esec_ private
Definition at line 30 of file ROL_ProjectedSecantStep.hpp.
Referenced by ROL::ProjectedSecantStep< Real >::printName(), and ROL::ProjectedSecantStep< Real >::ProjectedSecantStep().
d_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ProjectedSecantStep< Real >::d_ private
Additional vector storage.
Definition at line 31 of file ROL_ProjectedSecantStep.hpp.
Referenced by ROL::ProjectedSecantStep< Real >::initialize(), and ROL::ProjectedSecantStep< Real >::update().
gp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ProjectedSecantStep< Real >::gp_ private
Additional vector storage.
Definition at line 32 of file ROL_ProjectedSecantStep.hpp.
Referenced by ROL::ProjectedSecantStep< Real >::compute(), ROL::ProjectedSecantStep< Real >::initialize(), and ROL::ProjectedSecantStep< Real >::update().
verbosity_
template<class Real > int ROL::ProjectedSecantStep< Real >::verbosity_ private
Verbosity level.
Definition at line 33 of file ROL_ProjectedSecantStep.hpp.
Referenced by ROL::ProjectedSecantStep< Real >::printHeader(), and ROL::ProjectedSecantStep< Real >::ProjectedSecantStep().
computeObj_
template<class Real > const bool ROL::ProjectedSecantStep< Real >::computeObj_ private
Definition at line 34 of file ROL_ProjectedSecantStep.hpp.
Referenced by ROL::ProjectedSecantStep< Real >::update().
useProjectedGrad_
template<class Real > bool ROL::ProjectedSecantStep< Real >::useProjectedGrad_ private
Whether or not to use to the projected gradient criticality measure.
Definition at line 35 of file ROL_ProjectedSecantStep.hpp.
Referenced by ROL::ProjectedSecantStep< Real >::ProjectedSecantStep(), and ROL::ProjectedSecantStep< Real >::update().
The documentation for this class was generated from the following file:
ROL_ProjectedSecantStep.hpp