ROL: ROL::DualScaledVector< Real > Class Template Reference
ROL::DualScaledVector< Real > Class Template Reference
User Interface » Linear Algebra Interface
Provides the implementation of the ROL::Vector interface that handles scalings in the inner product. A more generic version of ROL::PrimalScaledStdVector.
#include <ROL_ScaledVector.hpp>
Public Member Functions
DualScaledVector (const Ptr< V > &vec, const Ptr< V > &scaling_vec)
virtual ~DualScaledVector ()
virtual Real dot (const V &x) const override
virtual Ptr< V > clone () const override
virtual Ptr< V > basis (const int i) const override
virtual void const V & dual () const override
const Ptr< V > & getScalingVector ()
const Ptr< const V > & getScalingVector () const
void setScalingVector (const Ptr< const V & > &scaling_vec) const
Protected Member Functions
VectorWorkspace< Real > & getWorkspace () const
void divide_scaling (const < V > &y) const
Private Types
using V = Vector< Real >
using VPrim = PrimalScaledVector< Real >
using VDual = DualScaledVector< Real >
Private Attributes
Ptv< V > scaling_vec_
VectorWorkspace< Real > workspace_
Elementwise::Divide< Real > div_
Detailed Description
template<typename Real>
class ROL::DualScaledVector< Real >
Provides the implementation of the ROL::Vector interface that handles scalings in the inner product. A more generic version of ROL::PrimalScaledStdVector.
Definition at line 99 of file ROL_ScaledVector.hpp.
Member Typedef Documentation
V
template<typename Real > using ROL::DualScaledVector< Real >::V = Vector<Real> private
Definition at line 101 of file ROL_ScaledVector.hpp.
VPrim
template<typename Real > using ROL::DualScaledVector< Real >::VPrim = PrimalScaledVector<Real> private
Definition at line 102 of file ROL_ScaledVector.hpp.
VDual
template<typename Real > using ROL::DualScaledVector< Real >::VDual = DualScaledVector<Real> private
Definition at line 103 of file ROL_ScaledVector.hpp.
Constructor & Destructor Documentation
DualScaledVector()
template<typename Real > ROL::DualScaledVector< Real >::DualScaledVector (const Ptr< V > & vec, const Ptr< V > & scaling_vec) inline
Definition at line 123 of file ROL_ScaledVector.hpp.
~DualScaledVector()
template<typename Real > virtual ROL::DualScaledVector< Real >::~DualScaledVector () inline virtual
Definition at line 126 of file ROL_ScaledVector.hpp.
Member Function Documentation
getWorkspace()
template<typename Real > VectorWorkspace< Real > & ROL::DualScaledVector< Real >::getWorkspace () const inline protected
Definition at line 114 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::workspace_.
Referenced by ROL::InactiveSet_DualVector< Real >::dot(), and ROL::InactiveSet_DualVector< Real >::dual().
divide_scaling()
template<typename Real > void ROL::DualScaledVector< Real >::divide_scaling (const < V > & y) const inline protected
Definition at line 117 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::div_, and ROL::DualScaledVector< Real >::scaling_vec_.
Referenced by ROL::InactiveSet_DualVector< Real >::dot(), ROL::DualScaledVector< Real >::dot(), and ROL::DualScaledVector< Real >::dual().
dot()
template<typename Real > virtual Real ROL::DualScaledVector< Real >::dot (const V & x) const inline override virtual
Reimplemented in ROL::InactiveSet_DualVector< Real >.
Definition at line 128 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::divide_scaling(), and ROL::DualScaledVector< Real >::workspace_.
clone()
template<typename Real > virtual Ptr< V > ROL::DualScaledVector< Real >::clone () const inline override virtual
Reimplemented in ROL::InactiveSet_DualVector< Real >.
Definition at line 134 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::clone(), and ROL::DualScaledVector< Real >::scaling_vec_.
Referenced by ROL::DualScaledVector< Real >::clone().
basis()
template<typename Real > virtual Ptr< V > ROL::DualScaledVector< Real >::basis (const int i) const inline override virtual
Reimplemented in ROL::InactiveSet_DualVector< Real >.
Definition at line 138 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::basis(), and ROL::DualScaledVector< Real >::scaling_vec_.
Referenced by ROL::DualScaledVector< Real >::basis().
dual()
template<typename Real > virtual void const V & ROL::DualScaledVector< Real >::dual () const inline override virtual
Reimplemented in ROL::InactiveSet_DualVector< Real >.
Definition at line 142 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::divide_scaling(), and ROL::DualScaledVector< Real >::workspace_.
getScalingVector() [1/2]
template<typename Real > const Ptr< V > & ROL::DualScaledVector< Real >::getScalingVector () inline
Definition at line 148 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::scaling_vec_.
Referenced by ROL::InactiveSet_DualVector< Real >::basis(), ROL::InactiveSet_DualVector< Real >::clone(), ROL::InactiveSet_DualVector< Real >::dot(), and ROL::InactiveSet_DualVector< Real >::dual().
getScalingVector() [2/2]
template<typename Real > const Ptr< const V > & ROL::DualScaledVector< Real >::getScalingVector () const inline
Definition at line 149 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::scaling_vec_.
setScalingVector()
template<typename Real > void ROL::DualScaledVector< Real >::setScalingVector (const Ptr< const V & > & scaling_vec) const inline
Definition at line 151 of file ROL_ScaledVector.hpp.
References ROL::DualScaledVector< Real >::scaling_vec_.
Member Data Documentation
scaling_vec_
template<typename Real > Ptv<V> ROL::DualScaledVector< Real >::scaling_vec_ mutable private
Definition at line 107 of file ROL_ScaledVector.hpp.
Referenced by ROL::DualScaledVector< Real >::basis(), ROL::DualScaledVector< Real >::clone(), ROL::DualScaledVector< Real >::divide_scaling(), ROL::DualScaledVector< Real >::getScalingVector(), ROL::DualScaledVector< Real >::getScalingVector(), and ROL::DualScaledVector< Real >::setScalingVector().
workspace_
template<typename Real > VectorWorkspace<Real> ROL::DualScaledVector< Real >::workspace_ mutable private
Definition at line 108 of file ROL_ScaledVector.hpp.
Referenced by ROL::DualScaledVector< Real >::dot(), ROL::DualScaledVector< Real >::dual(), and ROL::DualScaledVector< Real >::getWorkspace().
div_
template<typename Real > Elementwise::Divide<Real> ROL::DualScaledVector< Real >::div_ private
Definition at line 110 of file ROL_ScaledVector.hpp.
Referenced by ROL::DualScaledVector< Real >::divide_scaling().
The documentation for this class was generated from the following file:
ROL_ScaledVector.hpp