ROL: ROL::LogExponentialQuadrangle< Real > Class Template Reference
ROL::LogExponentialQuadrangle< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for the entropic risk using the expectation risk quadrangle.
#include <ROL_LogExponentialQuadrangle.hpp>
Public Member Functions
LogExponentialQuadrangle (const Real coeff=1)
Constructor.
LogExponentialQuadrangle (ROL::ParameterList &parlist)
Constructor.
Real error (Real x, int deriv=0)
Evaluate the scalar error function at x.
Real regret (Real x, int deriv=0)
Evaluate the scalar regret function at x.
Public Member Functions inherited from ROL::ExpectationQuad< Real >
virtual ~ExpectationQuad (void)
ExpectationQuad (void)
virtual void check (void)
Run default derivative tests for the scalar regret function.
Private Member Functions
void parseParameterList (ROL::ParameterList &parlist)
void checkInputs (void) const
Private Attributes
Real coeff_
Detailed Description
template<class Real>
class ROL::LogExponentialQuadrangle< Real >
Provides an interface for the entropic risk using the expectation risk quadrangle.
The entropic risk measure (also called the exponential utility and the log-exponential risk measure) is
\[ \mathcal{R}(X) = \lambda \log\mathbb{E}\left[\exp\left(\frac{X}{\lambda}\right)\right] \]
for \(\lambda > 0\). The entropic risk is convex, translation equivariant and monotonic.
This class defines the entropic risk measure using the framework of the expectation risk quadrangle. In this case, the scalar regret function is
\[ v(x) = \lambda(\exp\left(\frac{x}{\lambda}\right)-1). \]
The entropic risk measure is then implemented as
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}}\left\{ t + \mathbb{E}[v(X-t)] \right\}. \]
ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
Definition at line 47 of file ROL_LogExponentialQuadrangle.hpp.
Constructor & Destructor Documentation
LogExponentialQuadrangle() [1/2]
template<class Real > ROL::LogExponentialQuadrangle< Real >::LogExponentialQuadrangle (const Real coeff = 1) inline
Constructor.
Parameters
[in] coeff is the scale parameter \(\lambda\)
Definition at line 80 of file ROL_LogExponentialQuadrangle.hpp.
References ROL::LogExponentialQuadrangle< Real >::checkInputs().
LogExponentialQuadrangle() [2/2]
template<class Real > ROL::LogExponentialQuadrangle< Real >::LogExponentialQuadrangle (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measures"->"Log-Exponential Quadrangle" and withing the "Log-Exponential Quadrangle" sublist should have
"Rate" (greater than 0).
Definition at line 93 of file ROL_LogExponentialQuadrangle.hpp.
References ROL::LogExponentialQuadrangle< Real >::checkInputs(), and ROL::LogExponentialQuadrangle< Real >::parseParameterList().
Member Function Documentation
parseParameterList()
template<class Real > void ROL::LogExponentialQuadrangle< Real >::parseParameterList (ROL::ParameterList & parlist) inline private
Definition at line 51 of file ROL_LogExponentialQuadrangle.hpp.
References ROL::LogExponentialQuadrangle< Real >::coeff_.
Referenced by ROL::LogExponentialQuadrangle< Real >::LogExponentialQuadrangle().
checkInputs()
template<class Real > void ROL::LogExponentialQuadrangle< Real >::checkInputs (void) const inline private
Definition at line 69 of file ROL_LogExponentialQuadrangle.hpp.
References ROL::LogExponentialQuadrangle< Real >::coeff_, and zero.
Referenced by ROL::LogExponentialQuadrangle< Real >::LogExponentialQuadrangle(), and ROL::LogExponentialQuadrangle< Real >::LogExponentialQuadrangle().
error()
template<class Real > Real ROL::LogExponentialQuadrangle< Real >::error (Real x, int deriv = 0) inline virtual
Evaluate the scalar error function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(e(x)\) or a derivative of \(e(x)\).
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 99 of file ROL_LogExponentialQuadrangle.hpp.
References ROL::LogExponentialQuadrangle< Real >::coeff_.
Referenced by ROL::LogExponentialQuadrangle< Real >::regret().
regret()
template<class Real > Real ROL::LogExponentialQuadrangle< Real >::regret (Real x, int deriv = 0) inline virtual
Evaluate the scalar regret function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(v(x)\) or a derivative of \(v(x)\).
Implements ROL::ExpectationQuad< Real >.
Definition at line 113 of file ROL_LogExponentialQuadrangle.hpp.
References ROL::LogExponentialQuadrangle< Real >::error(), and zero.
Member Data Documentation
coeff_
template<class Real > Real ROL::LogExponentialQuadrangle< Real >::coeff_ private
Definition at line 49 of file ROL_LogExponentialQuadrangle.hpp.
Referenced by ROL::LogExponentialQuadrangle< Real >::checkInputs(), ROL::LogExponentialQuadrangle< Real >::error(), and ROL::LogExponentialQuadrangle< Real >::parseParameterList().
The documentation for this class was generated from the following file:
ROL_LogExponentialQuadrangle.hpp