ROL: ROL::DykstraProjection< Real > Class Template Reference
ROL::DykstraProjection< Real > Class Template Reference
#include <ROL_DykstraProjection.hpp>
Public Member Functions
DykstraProjection (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res)
DykstraProjection (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res, ParameterList &list)
void project (Vector< Real > &x, std::ostream &stream=std::cout) override
Public Member Functions inherited from ROL::PolyhedralProjection< Real >
virtual ~PolyhedralProjection ()
PolyhedralProjection (const Ptr< BoundConstraint< Real > > &bnd)
PolyhedralProjection (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res)
const Ptr< Constraint< Real > > getLinearConstraint (void) const
const Ptr< BoundConstraint< Real > > getBoundConstraint (void) const
const Ptr< Vector< Real > > getMultiplier (void) const
const Ptr< Vector< Real > > getResidual (void) const
Private Member Functions
Real residual_1d (const Vector< Real > &x) const
void residual_nd (Vector< Real > &r, const Vector< Real > &y) const
void project_bnd (Vector< Real > &x, const Vector< Real > &y) const
void project_con (Vector< Real > &x, const Vector< Real > &y) const
void project_Dykstra (Vector< Real > &x, std::ostream &stream=std::cout) const
Private Attributes
int dim_
Ptr< Vector< Real > > tmp_
Ptr< Vector< Real > > p_
Ptr< Vector< Real > > q_
Ptr< Vector< Real > > y_
Ptr< Vector< Real > > z_
Real b_
Real cdot_
Real DEFAULT_atol_
Real DEFAULT_rtol_
int DEFAULT_maxit_
int DEFAULT_verbosity_
Real atol_
Real rtol_
int maxit_
int verbosity_
Additional Inherited Members
Protected Attributes inherited from ROL::PolyhedralProjection< Real >
const Ptr< BoundConstraint< Real > > bnd_
const Ptr< Constraint< Real > > con_
Ptr< Vector< Real > > xprim_
Ptr< Vector< Real > > xdual_
Ptr< Vector< Real > > mul_
Ptr< Vector< Real > > res_
Detailed Description
template<typename Real>
class ROL::DykstraProjection< Real >
Definition at line 19 of file ROL_DykstraProjection.hpp.
Constructor & Destructor Documentation
DykstraProjection() [1/2]
template<typename Real > ROL::DykstraProjection< Real >::DykstraProjection (const Vector< Real > & xprim, const Vector< Real > & xdual, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & con, const Vector< Real > & mul, const Vector< Real > & res)
Definition at line 16 of file ROL_DykstraProjection_Def.hpp.
References ROL::DykstraProjection< Real >::b_, ROL::DykstraProjection< Real >::cdot_, ROL::Vector< Real >::clone(), ROL::PolyhedralProjection< Real >::con_, ROL::DykstraProjection< Real >::dim_, ROL::Vector< Real >::dimension(), ROL::PolyhedralProjection< Real >::mul_, ROL::DykstraProjection< Real >::p_, ROL::DykstraProjection< Real >::q_, ROL::PolyhedralProjection< Real >::res_, ROL::Temp, ROL::DykstraProjection< Real >::tmp_, ROL::PolyhedralProjection< Real >::xprim_, ROL::DykstraProjection< Real >::y_, and ROL::DykstraProjection< Real >::z_.
DykstraProjection() [2/2]
template<typename Real > ROL::DykstraProjection< Real >::DykstraProjection (const Vector< Real > & xprim, const Vector< Real > & xdual, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & con, const Vector< Real > & mul, const Vector< Real > & res, ParameterList & list)
Definition at line 52 of file ROL_DykstraProjection_Def.hpp.
References ROL::DykstraProjection< Real >::atol_, ROL::DykstraProjection< Real >::DEFAULT_atol_, ROL::DykstraProjection< Real >::DEFAULT_maxit_, ROL::DykstraProjection< Real >::DEFAULT_rtol_, ROL::DykstraProjection< Real >::DEFAULT_verbosity_, ROL::DykstraProjection< Real >::maxit_, ROL::DykstraProjection< Real >::rtol_, and ROL::DykstraProjection< Real >::verbosity_.
Member Function Documentation
project()
template<typename Real > void ROL::DykstraProjection< Real >::project (Vector< Real > & x, std::ostream & stream = std::cout) override virtual
Reimplemented from ROL::PolyhedralProjection< Real >.
Definition at line 67 of file ROL_DykstraProjection_Def.hpp.
References ROL::DykstraProjection< Real >::project().
Referenced by ROL::DykstraProjection< Real >::project().
residual_1d()
template<typename Real > Real ROL::DykstraProjection< Real >::residual_1d (const Vector< Real > & x) const private
Definition at line 77 of file ROL_DykstraProjection_Def.hpp.
residual_nd()
template<typename Real > void ROL::DykstraProjection< Real >::residual_nd (Vector< Real > & r, const Vector< Real > & y) const private
Definition at line 82 of file ROL_DykstraProjection_Def.hpp.
References ROL::Temp.
project_bnd()
template<typename Real > void ROL::DykstraProjection< Real >::project_bnd (Vector< Real > & x, const Vector< Real > & y) const private
Definition at line 89 of file ROL_DykstraProjection_Def.hpp.
References ROL::Vector< Real >::set().
project_con()
template<typename Real > void ROL::DykstraProjection< Real >::project_con (Vector< Real > & x, const Vector< Real > & y) const private
Definition at line 95 of file ROL_DykstraProjection_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
project_Dykstra()
template<typename Real > void ROL::DykstraProjection< Real >::project_Dykstra (Vector< Real > & x, std::ostream & stream = std::cout) const private
Definition at line 112 of file ROL_DykstraProjection_Def.hpp.
References ROL::Vector< Real >::norm().
Member Data Documentation
dim_
template<typename Real > int ROL::DykstraProjection< Real >::dim_ private
Definition at line 21 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
tmp_
template<typename Real > Ptr<Vector<Real> > ROL::DykstraProjection< Real >::tmp_ private
Definition at line 22 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
p_
template<typename Real > Ptr<Vector<Real> > ROL::DykstraProjection< Real >::p_ private
Definition at line 22 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
q_
template<typename Real > Ptr<Vector<Real> > ROL::DykstraProjection< Real >::q_ private
Definition at line 22 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
y_
template<typename Real > Ptr<Vector<Real> > ROL::DykstraProjection< Real >::y_ private
Definition at line 22 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
z_
template<typename Real > Ptr<Vector<Real> > ROL::DykstraProjection< Real >::z_ private
Definition at line 22 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
b_
template<typename Real > Real ROL::DykstraProjection< Real >::b_ private
Definition at line 23 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
cdot_
template<typename Real > Real ROL::DykstraProjection< Real >::cdot_ private
Definition at line 23 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
DEFAULT_atol_
template<typename Real > Real ROL::DykstraProjection< Real >::DEFAULT_atol_ private
Definition at line 25 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
DEFAULT_rtol_
template<typename Real > Real ROL::DykstraProjection< Real >::DEFAULT_rtol_ private
Definition at line 25 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
DEFAULT_maxit_
template<typename Real > int ROL::DykstraProjection< Real >::DEFAULT_maxit_ private
Definition at line 26 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
DEFAULT_verbosity_
template<typename Real > int ROL::DykstraProjection< Real >::DEFAULT_verbosity_ private
Definition at line 26 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
atol_
template<typename Real > Real ROL::DykstraProjection< Real >::atol_ private
Definition at line 28 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
rtol_
template<typename Real > Real ROL::DykstraProjection< Real >::rtol_ private
Definition at line 28 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
maxit_
template<typename Real > int ROL::DykstraProjection< Real >::maxit_ private
Definition at line 29 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
verbosity_
template<typename Real > int ROL::DykstraProjection< Real >::verbosity_ private
Definition at line 29 of file ROL_DykstraProjection.hpp.
Referenced by ROL::DykstraProjection< Real >::DykstraProjection().
The documentation for this class was generated from the following files:
ROL_DykstraProjection.hpp
ROL_DykstraProjection_Def.hpp