ROL: ROL::Constraint< Real > Class Template Reference
ROL::Constraint< Real > Class Template Reference abstract
User Interface » Functional Interface
Defines the general constraint operator interface.
#include <ROL_Constraint.hpp>
Public Member Functions
virtual ~Constraint (void)
Constraint (void)
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update constraint function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void value (Vector< Real > &c, const Vector< Real > &x, Real &tol)=0
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
virtual void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual void applyAdjointHessian (Vector< Real > &ahuv, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
virtual std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol)
Approximately solves the augmented system
virtual void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Protected Member Functions
const std::vector< Real > getParameter (void) const
Private Attributes
bool activated_
std::vector< Real > param_
Detailed Description
template<class Real>
class ROL::Constraint< Real >
Defines the general constraint operator interface.
ROL's constraint interface is designed for Fréchet differentiable operators \(c:\mathcal{X} \rightarrow \mathcal{C}\), where \(\mathcal{X}\) and \(\mathcal{C}\) are Banach spaces. The constraints are of the form
\[ c(x) = 0 \,. \]
The basic operator interface, to be implemented by the user, requires:
value – constraint evaluation.
It is strongly recommended that the user additionally overload:
applyJacobian – action of the constraint Jacobian –the default is a finite-difference approximation;
applyAdjointJacobian – action of the adjoint of the constraint Jacobian –the default is a finite-difference approximation.
The user may also overload:
applyAdjointHessian – action of the adjoint of the constraint Hessian –the default is a finite-difference approximation based on the adjoint Jacobian;
solveAugmentedSystem – solution of the augmented system –the default is an iterative scheme based on the action of the Jacobian and its adjoint.
applyPreconditioner – action of a constraint preconditioner –the default is null-op.
Definition at line 52 of file ROL_Constraint.hpp.
Constructor & Destructor Documentation
~Constraint()
template<class Real > virtual ROL::Constraint< Real >::~Constraint (void) inline virtual
Definition at line 57 of file ROL_Constraint.hpp.
Constraint()
template<class Real > ROL::Constraint< Real >::Constraint (void) inline
Definition at line 59 of file ROL_Constraint.hpp.
Member Function Documentation
update() [1/2]
template<class Real > virtual void ROL::Constraint< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update constraint function.
This function updates the constraint function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented in ROL::SimConstraint< Real >, ROL::ChainRuleConstraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::StochasticConstraint< Real >, ROL::AlmostSureConstraint< Real >, ROL::RiskNeutralConstraint< Real >, ROL::SimulatedConstraint< Real >, ROL::ElasticLinearConstraint< Real >, ROL::AffineTransformConstraint< Real >, ROL::Constraint_Partitioned< Real >, ROL::ConstraintFromObjective< Real >, ROL::LinearConstraint< Real >, ROL::SlacklessConstraint< Real >, ROL::StdConstraint< Real >, ROL::MeanValueConstraint< Real >, ROL::RiskLessConstraint< Real >, ROL::Reduced_Constraint_SimOpt< Real >, and ROL::StdConstraint< RealT >.
Definition at line 68 of file ROL_Constraint.hpp.
References ROL_UNUSED.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::CompositeStep< Real >::initialize(), ROL::TypeE::CompositeStepAlgorithm< Real >::initialize(), ROL::CompositeStep< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius(), ROL::TypeG::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
update() [2/2]
template<class Real > virtual void ROL::Constraint< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented in ROL::Constraint_DynamicState< Real >, ROL::SimConstraint< Real >, ROL::ChainRuleConstraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::StochasticConstraint< Real >, ROL::AlmostSureConstraint< Real >, ROL::RiskNeutralConstraint< Real >, ROL::SimulatedConstraint< Real >, ROL::PrimalDualInteriorPointResidual< Real >, ROL::PrimalDualInteriorPointResidual< Real >, ROL::ElasticLinearConstraint< Real >, ROL::AffineTransformConstraint< Real >, ROL::Constraint_Partitioned< Real >, ROL::ConstraintFromObjective< Real >, ROL::LinearConstraint< Real >, ROL::SlacklessConstraint< Real >, ROL::StdConstraint< Real >, ROL::MeanValueConstraint< Real >, ROL::RiskLessConstraint< Real >, ROL::Reduced_Constraint_SimOpt< Real >, and ROL::StdConstraint< RealT >.
Definition at line 79 of file ROL_Constraint.hpp.
value()
template<class Real > virtual void ROL::Constraint< Real >::value (Vector< Real > & c, const Vector< Real > & x, Real & tol) pure virtual
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
Parameters
[out] c is the result of evaluating the constraint operator at x; a constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(x)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{x} \in \mathcal{X}\).
Implemented in ROL::InteriorPoint::PrimalDualResidual< Real >, ROL::PrimalDualInteriorPointResidual< Real >, ROL::PrimalDualInteriorPointResidual< Real >, ROL::InteriorPoint::PrimalDualResidual< Real >, Normalization_Constraint< Real >, Normalization_Constraint< Real >, ROL::Constraint_DynamicState< Real >, ROL::SimConstraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::StochasticConstraint< Real >, ROL::AlmostSureConstraint< Real >, ROL::RiskNeutralConstraint< Real >, ROL::SimulatedConstraint< Real >, ROL::ZOO::Constraint_HS24< Real >, ROL::ZOO::InequalityConstraint_HS29< Real >, ROL::ZOO::EqualityConstraint_HS32< Real >, ROL::ZOO::InequalityConstraint_HS32< Real >, ROL::ZOO::Constraint_HS39a< Real >, ROL::ZOO::Constraint_HS39b< Real >, ROL::ZOO::Constraint_ParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::EqualityConstraint_SimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >, ROL::ElasticLinearConstraint< Real >, ROL::AffineTransformConstraint< Real >, ROL::BinaryConstraint< Real >, ROL::BoundToConstraint< Real >, ROL::ChainRuleConstraint< Real >, ROL::Constraint_Partitioned< Real >, ROL::ConstraintFromObjective< Real >, ROL::LinearConstraint< Real >, ROL::LowerBoundToConstraint< Real >, ROL::ReducedLinearConstraint< Real >, ROL::ScalarLinearConstraint< Real >, ROL::SlacklessConstraint< Real >, ROL::UpperBoundToConstraint< Real >, ROL::StdConstraint< Real >, ROL::MeanValueConstraint< Real >, ROL::RiskLessConstraint< Real >, ROL::Reduced_Constraint_SimOpt< Real >, and ROL::StdConstraint< RealT >.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::CompositeStep< Real >::compute(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeTrial(), ROL::CompositeStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::TypeE::CompositeStepAlgorithm< Real >::initialize(), testRandomInputs(), ROL::CompositeStep< Real >::update(), ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius(), ROL::TypeG::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
applyJacobian()
template<class Real > void ROL::Constraint< Real >::applyJacobian (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) virtual
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at x; a constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c'(x)v\), where \(v \in \mathcal{X}\), \(\mathsf{jv} \in \mathcal{C}\).
The default implementation is a finite-difference approximation.
Reimplemented in ROL::InteriorPoint::PrimalDualResidual< Real >, ROL::PrimalDualInteriorPointResidual< Real >, ROL::PrimalDualInteriorPointResidual< Real >, ROL::InteriorPoint::PrimalDualResidual< Real >, Normalization_Constraint< Real >, Normalization_Constraint< Real >, ROL::Constraint_DynamicState< Real >, ROL::SimConstraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::StochasticConstraint< Real >, ROL::AlmostSureConstraint< Real >, ROL::RiskNeutralConstraint< Real >, ROL::SimulatedConstraint< Real >, ROL::ZOO::Constraint_HS24< Real >, ROL::ZOO::InequalityConstraint_HS29< Real >, ROL::ZOO::EqualityConstraint_HS32< Real >, ROL::ZOO::InequalityConstraint_HS32< Real >, ROL::ZOO::Constraint_HS39a< Real >, ROL::ZOO::Constraint_HS39b< Real >, ROL::ZOO::Constraint_ParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::EqualityConstraint_SimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >, ROL::ElasticLinearConstraint< Real >, ROL::AffineTransformConstraint< Real >, ROL::BinaryConstraint< Real >, ROL::BoundToConstraint< Real >, ROL::ChainRuleConstraint< Real >, ROL::Constraint_Partitioned< Real >, ROL::ConstraintFromObjective< Real >, ROL::LinearConstraint< Real >, ROL::LowerBoundToConstraint< Real >, ROL::ReducedLinearConstraint< Real >, ROL::ScalarLinearConstraint< Real >, ROL::SlacklessConstraint< Real >, ROL::UpperBoundToConstraint< Real >, ROL::StdConstraint< Real >, ROL::MeanValueConstraint< Real >, ROL::RiskLessConstraint< Real >, ROL::Reduced_Constraint_SimOpt< Real >, and ROL::StdConstraint< RealT >.
Definition at line 19 of file ROL_ConstraintDef.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Temp, ROL::update(), ROL::value(), and ROL::Vector< Real >::zero().
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), and testRandomInputs().
applyAdjointJacobian() [1/2]
template<class Real > void ROL::Constraint< Real >::applyAdjointJacobian (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) virtual
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at x; a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c'(x)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation.
Reimplemented in ROL::ChainRuleConstraint< Real >, Normalization_Constraint< Real >, Normalization_Constraint< Real >, ROL::Constraint_DynamicState< Real >, ROL::SimConstraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::StochasticConstraint< Real >, ROL::AlmostSureConstraint< Real >, ROL::RiskNeutralConstraint< Real >, ROL::SimulatedConstraint< Real >, ROL::ZOO::Constraint_HS24< Real >, ROL::ZOO::InequalityConstraint_HS29< Real >, ROL::ZOO::EqualityConstraint_HS32< Real >, ROL::ZOO::InequalityConstraint_HS32< Real >, ROL::ZOO::Constraint_HS39a< Real >, ROL::ZOO::Constraint_HS39b< Real >, ROL::ZOO::Constraint_ParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::EqualityConstraint_SimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >, ROL::ElasticLinearConstraint< Real >, ROL::AffineTransformConstraint< Real >, ROL::BinaryConstraint< Real >, ROL::BoundToConstraint< Real >, ROL::Constraint_Partitioned< Real >, ROL::ConstraintFromObjective< Real >, ROL::LinearConstraint< Real >, ROL::LowerBoundToConstraint< Real >, ROL::ScalarLinearConstraint< Real >, ROL::UpperBoundToConstraint< Real >, ROL::StdConstraint< Real >, ROL::MeanValueConstraint< Real >, ROL::RiskLessConstraint< Real >, ROL::Reduced_Constraint_SimOpt< Real >, ROL::ReducedLinearConstraint< Real >, and ROL::StdConstraint< RealT >.
Definition at line 52 of file ROL_ConstraintDef.hpp.
References ROL::Vector< Real >::dual().
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::StdConstraint< RealT >::applyPreconditioner(), ROL::CompositeStep< Real >::compute(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeTrial(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::CompositeStep< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::TypeE::CompositeStepAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::run(), ROL::CompositeStep< Real >::update(), ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius(), ROL::TypeG::InteriorPointAlgorithm< Real >::updateState(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
applyAdjointJacobian() [2/2]
template<class Real > void ROL::Constraint< Real >::applyAdjointJacobian (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & dualv, Real & tol) virtual
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at x; a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in] dualv is a vector used for temporary variables; a constraint-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c'(x)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation.
Reimplemented in ROL::ElasticLinearConstraint< Real >, ROL::LinearConstraint< Real >, and ROL::SlacklessConstraint< Real >.
Definition at line 64 of file ROL_ConstraintDef.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::Vector< Real >::norm(), ROL::Temp, ROL::update(), ROL::value(), and ROL::Vector< Real >::zero().
applyAdjointHessian()
template<class Real > void ROL::Constraint< Real >::applyAdjointHessian (Vector< Real > & ahuv, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & x, Real & tol) virtual
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
Parameters
[out] ahuv is the result of applying the derivative of the adjoint of the constraint Jacobian at x to vector u in direction v; a dual optimization-space vector
[in] u is the direction vector; a dual constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahuv} = c''(x)(v,\cdot)^*u \), where \(u \in \mathcal{C}^*\), \(v \in \mathcal{X}\), and \(\mathsf{ahuv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation based on the adjoint Jacobian.
Reimplemented in ROL::ChainRuleConstraint< Real >, Normalization_Constraint< Real >, Normalization_Constraint< Real >, ROL::StochasticConstraint< Real >, ROL::AlmostSureConstraint< Real >, ROL::RiskNeutralConstraint< Real >, ROL::SimulatedConstraint< Real >, ROL::ZOO::Constraint_HS24< Real >, ROL::ZOO::InequalityConstraint_HS29< Real >, ROL::ZOO::EqualityConstraint_HS32< Real >, ROL::ZOO::InequalityConstraint_HS32< Real >, ROL::ZOO::Constraint_HS39a< Real >, ROL::ZOO::Constraint_HS39b< Real >, ROL::ZOO::Constraint_ParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::EqualityConstraint_SimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >, ROL::ElasticLinearConstraint< Real >, ROL::AffineTransformConstraint< Real >, ROL::BinaryConstraint< Real >, ROL::BoundToConstraint< Real >, ROL::Constraint_Partitioned< Real >, ROL::ConstraintFromObjective< Real >, ROL::LinearConstraint< Real >, ROL::LowerBoundToConstraint< Real >, ROL::ReducedLinearConstraint< Real >, ROL::ScalarLinearConstraint< Real >, ROL::SlacklessConstraint< Real >, ROL::UpperBoundToConstraint< Real >, ROL::StdConstraint< Real >, ROL::MeanValueConstraint< Real >, ROL::RiskLessConstraint< Real >, ROL::Constraint_DynamicState< Real >, ROL::SimConstraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::Reduced_Constraint_SimOpt< Real >, and ROL::StdConstraint< RealT >.
Definition at line 132 of file ROL_ConstraintDef.hpp.
References ROL::Vector< Real >::clone(), ROL::Vector< Real >::norm(), ROL::Temp, ROL::update(), and ROL::Vector< Real >::zero().
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::ZOO::Constraint_ParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >::applyAdjointHessian(), ROL::StdConstraint< Real >::applyAdjointHessian(), ROL::Reduced_Constraint_SimOpt< Real >::applyAdjointHessian(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), and ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem().
solveAugmentedSystem()
template<class Real > std::vector< Real > ROL::Constraint< Real >::solveAugmentedSystem (Vector< Real > & v1, Vector< Real > & v2, const Vector< Real > & b1, const Vector< Real > & b2, const Vector< Real > & x, Real & tol) virtual
Approximately solves the augmented system
\[ \begin{pmatrix} I & c'(x)^* \\ c'(x) & 0 \end{pmatrix} \begin{pmatrix} v_{1} \\ v_{2} \end{pmatrix} = \begin{pmatrix} b_{1} \\ b_{2} \end{pmatrix} \]
where \(v_{1} \in \mathcal{X}\), \(v_{2} \in \mathcal{C}^*\), \(b_{1} \in \mathcal{X}^*\), \(b_{2} \in \mathcal{C}\), \(I : \mathcal{X} \rightarrow \mathcal{X}^*\) is an identity or Riesz operator, and \(0 : \mathcal{C}^* \rightarrow \mathcal{C}\) is a zero operator.
Parameters
[out] v1 is the optimization-space component of the result
[out] v2 is the dual constraint-space component of the result
[in] b1 is the dual optimization-space component of the right-hand side
[in] b2 is the constraint-space component of the right-hand side
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is the nominal relative residual tolerance
On return, \([\mathsf{v1} \,\, \mathsf{v2}] \) approximately solves the augmented system, where the size of the residual is governed by special stopping conditions.
The default implementation is the preconditioned generalized minimal residual (GMRES) method, which enables the use of nonsymmetric preconditioners.
Reimplemented in Normalization_Constraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::ScalarLinearConstraint< Real >, ROL::StdConstraint< Real >, and ROL::StdConstraint< RealT >.
Definition at line 161 of file ROL_ConstraintDef.hpp.
References zero.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), Normalization_Constraint< Real >::solveAugmentedSystem(), ROL::Constraint_SimOpt< Real >::solveAugmentedSystem(), ROL::StdConstraint< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), and ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem().
applyPreconditioner()
template<class Real > virtual void ROL::Constraint< Real >::applyPreconditioner (Vector< Real > & pv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g, Real & tol) inline virtual
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
\[ \left[c'(x) \circ R \circ c'(x)^* \circ P(x)\right] v = v \,, \]
where R is the appropriate Riesz map in \(L(\mathcal{X}^*, \mathcal{X})\). It is used by the solveAugmentedSystem method.
Parameters
[out] pv is the result of applying the constraint preconditioner to v at x; a dual constraint-space vector
[in] v is a constraint-space vector
[in] x is the preconditioner argument; an optimization-space vector
[in] g is the preconditioner argument; a dual optimization-space vector, unused
[in,out] tol is a tolerance for inexact evaluations
On return, \(\mathsf{pv} = P(x)v\), where \(v \in \mathcal{C}\), \(\mathsf{pv} \in \mathcal{C}^*\).
The default implementation is the Riesz map in \(L(\mathcal{C}, \mathcal{C}^*)\).
Reimplemented in ROL::Constraint_DynamicState< Real >, ROL::SimConstraint< Real >, ROL::Constraint_SimOpt< Real >, ROL::AlmostSureConstraint< Real >, ROL::SimulatedConstraint< Real >, ROL::Constraint_Partitioned< Real >, ROL::StdConstraint< Real >, and ROL::StdConstraint< RealT >.
Definition at line 249 of file ROL_Constraint.hpp.
References ROL::Vector< Real >::dual(), and ROL::Vector< Real >::set().
Referenced by ROL::Constraint_SimOpt< Real >::applyPreconditioner(), and ROL::StdConstraint< Real >::applyPreconditioner().
activate()
template<class Real > void ROL::Constraint< Real >::activate (void) inline
Turn on constraints.
Definition at line 259 of file ROL_Constraint.hpp.
References ROL::Constraint< Real >::activated_.
deactivate()
template<class Real > void ROL::Constraint< Real >::deactivate (void) inline
Turn off constraints.
Definition at line 263 of file ROL_Constraint.hpp.
References ROL::Constraint< Real >::activated_.
isActivated()
template<class Real > bool ROL::Constraint< Real >::isActivated (void) inline
Check if constraints are on.
Definition at line 267 of file ROL_Constraint.hpp.
References ROL::Constraint< Real >::activated_.
checkApplyJacobian() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint< Real >::checkApplyJacobian (const Vector< Real > & x, const Vector< Real > & v, const Vector< Real > & jv, const std::vector< Real > & steps, const bool printToStream = true, std::ostream & outStream = std::cout, const int order = 1) virtual
Finite-difference check for the constraint Jacobian application.
Details here.
Definition at line 351 of file ROL_ConstraintDef.hpp.
Referenced by main().
checkApplyJacobian() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint< Real >::checkApplyJacobian (const Vector< Real > & x, const Vector< Real > & v, const Vector< Real > & jv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) virtual
Finite-difference check for the constraint Jacobian application.
Details here.
Definition at line 332 of file ROL_ConstraintDef.hpp.
checkApplyAdjointJacobian()
template<class Real > std::vector< std::vector< Real > > ROL::Constraint< Real >::checkApplyAdjointJacobian (const Vector< Real > & x, const Vector< Real > & v, const Vector< Real > & c, const Vector< Real > & ajv, const bool printToStream = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS) virtual
Finite-difference check for the application of the adjoint of constraint Jacobian.
Details here. (This function should be deprecated)
Definition at line 456 of file ROL_ConstraintDef.hpp.
References ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::Temp, ROL::update(), and ROL::value().
Referenced by main().
checkAdjointConsistencyJacobian() [1/2]
template<class Real > virtual Real ROL::Constraint< Real >::checkAdjointConsistencyJacobian (const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & x, const bool printToStream = true, std::ostream & outStream = std::cout) inline virtual
Definition at line 320 of file ROL_Constraint.hpp.
References ROL::Constraint< Real >::checkAdjointConsistencyJacobian(), and ROL::Vector< Real >::dual().
Referenced by ROL::Constraint< Real >::checkAdjointConsistencyJacobian(), and main().
checkAdjointConsistencyJacobian() [2/2]
template<class Real > Real ROL::Constraint< Real >::checkAdjointConsistencyJacobian (const Vector< Real > & w, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & dualw, const Vector< Real > & dualv, const bool printToStream = true, std::ostream & outStream = std::cout) virtual
Definition at line 552 of file ROL_ConstraintDef.hpp.
References ROL::Vector< Real >::apply(), applyJacobian(), ROL::Vector< Real >::clone(), ROL::Temp, and ROL::update().
checkApplyAdjointHessian() [1/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint< Real >::checkApplyAdjointHessian (const Vector< Real > & x, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & hv, const std::vector< Real > & step, const bool printToScreen = true, std::ostream & outStream = std::cout, const int order = 1) virtual
Finite-difference check for the application of the adjoint of constraint Hessian.
Details here.
Definition at line 606 of file ROL_ConstraintDef.hpp.
References ROL::Vector< Real >::clone(), ROL::Finite_Difference_Arrays::shifts, ROL::Temp, ROL::update(), and ROL::Finite_Difference_Arrays::weights.
Referenced by main().
checkApplyAdjointHessian() [2/2]
template<class Real > std::vector< std::vector< Real > > ROL::Constraint< Real >::checkApplyAdjointHessian (const Vector< Real > & x, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & hv, const bool printToScreen = true, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) virtual
Finite-difference check for the application of the adjoint of constraint Hessian.
Details here.
Definition at line 588 of file ROL_ConstraintDef.hpp.
getParameter()
template<class Real > const std::vector< Real > ROL::Constraint< Real >::getParameter (void) const inline protected
Definition at line 369 of file ROL_Constraint.hpp.
References ROL::Constraint< Real >::param_.
Referenced by Constraint_BurgersControl< Real >::applyAdjointHessian_11(), Constraint_BurgersControl< Real >::applyAdjointHessian_12(), Constraint_BurgersControl< Real >::applyAdjointHessian_21(), Constraint_BurgersControl< Real >::applyAdjointHessian_22(), Constraint_BurgersControl< Real >::applyAdjointJacobian_1(), Constraint_BurgersControl< Real >::applyAdjointJacobian_2(), DiffusionConstraint< Real >::applyAdjointJacobian_2(), Constraint_BurgersControl< Real >::applyInverseAdjointJacobian_1(), Constraint_BurgersControl< Real >::applyInverseJacobian_1(), DiffusionConstraint< Real >::applyInverseJacobian_1(), Constraint_BurgersControl< Real >::applyJacobian_1(), DiffusionConstraint< Real >::applyJacobian_1(), Constraint_BurgersControl< Real >::applyJacobian_2(), DiffusionConstraint< Real >::applyJacobian_2(), Constraint_BurgersControl< Real >::compute_pde_jacobian(), Constraint_BurgersControl< Real >::compute_residual(), DiffusionConstraint< Real >::solve(), ROL::CompositeConstraint_SimOpt< Real >::solveConRed(), Constraint_BurgersControl< Real >::value(), and DiffusionConstraint< Real >::value().
setParameter()
template<class Real > virtual void ROL::Constraint< Real >::setParameter (const std::vector< Real > & param) inline virtual
Reimplemented in ROL::Reduced_Constraint_SimOpt< Real >, ROL::Constraint_Partitioned< Real >, ROL::ConstraintFromObjective< Real >, ROL::SlacklessConstraint< Real >, ROL::CompositeConstraint_SimOpt< Real >, ROL::SimConstraint< Real >, and ROL::RiskLessConstraint< Real >.
Definition at line 374 of file ROL_Constraint.hpp.
References ROL::Constraint< Real >::param_.
Referenced by ROL::Reduced_Constraint_SimOpt< Real >::setParameter(), ROL::Constraint_Partitioned< Real >::setParameter(), ROL::ConstraintFromObjective< Real >::setParameter(), ROL::SlacklessConstraint< Real >::setParameter(), ROL::CompositeConstraint_SimOpt< Real >::setParameter(), ROL::SimConstraint< Real >::setParameter(), and ROL::RiskLessConstraint< Real >::setParameter().
Member Data Documentation
activated_
template<class Real > bool ROL::Constraint< Real >::activated_ private
Definition at line 54 of file ROL_Constraint.hpp.
Referenced by ROL::Constraint< Real >::activate(), ROL::Constraint< Real >::deactivate(), and ROL::Constraint< Real >::isActivated().
param_
template<class Real > std::vector<Real> ROL::Constraint< Real >::param_ private
Definition at line 366 of file ROL_Constraint.hpp.
Referenced by ROL::Constraint< Real >::getParameter(), and ROL::Constraint< Real >::setParameter().
The documentation for this class was generated from the following files:
ROL_Constraint.hpp
ROL_ConstraintDef.hpp