ROL: H1VectorBatchManager< Real, Ordinal > Class Template Reference
H1VectorBatchManager< Real, Ordinal > Class Template Reference
#include <example_06.hpp>
Public Member Functions
H1VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > &comm)
void sumAll (ROL::Vector< Real > &input, ROL::Vector< Real > &output)
H1VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > &comm)
void sumAll (ROL::Vector< Real > &input, ROL::Vector< Real > &output)
H1VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > &comm)
void sumAll (ROL::Vector< Real > &input, ROL::Vector< Real > &output)
Private Member Functions
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
Detailed Description
template<class Real, class Ordinal>
class H1VectorBatchManager< Real, Ordinal >
Definition at line 1231 of file example_06.hpp.
Constructor & Destructor Documentation
H1VectorBatchManager() [1/3]
template<class Real , class Ordinal > H1VectorBatchManager< Real, Ordinal >::H1VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > & comm) inline
Definition at line 1244 of file example_06.hpp.
H1VectorBatchManager() [2/3]
template<class Real , class Ordinal > H1VectorBatchManager< Real, Ordinal >::H1VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > & comm) inline
Definition at line 1596 of file example_07.hpp.
H1VectorBatchManager() [3/3]
template<class Real , class Ordinal > H1VectorBatchManager< Real, Ordinal >::H1VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > & comm) inline
Definition at line 1376 of file example_08.hpp.
Member Function Documentation
cast_vector() [1/3]
template<class Real , class Ordinal > void H1VectorBatchManager< Real, Ordinal >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1233 of file example_06.hpp.
Referenced by H1VectorBatchManager< Real, Ordinal >::sumAll().
sumAll() [1/3]
template<class Real , class Ordinal > void H1VectorBatchManager< Real, Ordinal >::sumAll (ROL::Vector< Real > & input, ROL::Vector< Real > & output) inline
Definition at line 1246 of file example_06.hpp.
References H1VectorBatchManager< Real, Ordinal >::cast_vector().
cast_vector() [2/3]
template<class Real , class Ordinal > void H1VectorBatchManager< Real, Ordinal >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1583 of file example_07.hpp.
sumAll() [2/3]
template<class Real , class Ordinal > void H1VectorBatchManager< Real, Ordinal >::sumAll (ROL::Vector< Real > & input, ROL::Vector< Real > & output) inline
Definition at line 1598 of file example_07.hpp.
References H1VectorBatchManager< Real, Ordinal >::cast_vector().
cast_vector() [3/3]
template<class Real , class Ordinal > void H1VectorBatchManager< Real, Ordinal >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1365 of file example_08.hpp.
sumAll() [3/3]
template<class Real , class Ordinal > void H1VectorBatchManager< Real, Ordinal >::sumAll (ROL::Vector< Real > & input, ROL::Vector< Real > & output) inline
Definition at line 1378 of file example_08.hpp.
References H1VectorBatchManager< Real, Ordinal >::cast_vector().
The documentation for this class was generated from the following files:
example_06.hpp
example_07.hpp
example_08.hpp