ROL: ROL::MeanVariance< Real > Class Template Reference
ROL::MeanVariance< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for the mean plus a sum of arbitrary order variances.
#include <ROL_MeanVariance.hpp>
Public Member Functions
MeanVariance (const Real order, const Real coeff, const Ptr< PositiveFunction< Real > > &pf)
Constructor.
MeanVariance (const std::vector< Real > &order, const std::vector< Real > &coeff, const Ptr< PositiveFunction< Real > > &pf)
Constructor.
MeanVariance (ROL::ParameterList &parlist)
Constructor.
void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void initialize (const Vector< Real > &x)
Initialize temporary variables.
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Types
typedef std::vector< Real >::size_type uint
Private Member Functions
void initializeMV (void)
void checkInputs (void)
Private Attributes
Ptr< PositiveFunction< Real > > positiveFunction_
std::vector< Real > order_
std::vector< Real > coeff_
uint NumMoments_
Ptr< ScalarController< Real > > values_
Ptr< ScalarController< Real > > gradvecs_
Ptr< VectorController< Real > > gradients_
Ptr< VectorController< Real > > hessvecs_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::MeanVariance< Real >
Provides an interface for the mean plus a sum of arbitrary order variances.
The mean plus variances risk measure is
\[ \mathcal{R}(X) = \mathbb{E}[X] + \sum_{k=1}^n c_k \mathbb{E}[\wp(X-\mathbb{E}[X])^{p_k}] \]
where \(\wp:\mathbb{R}\to[0,\infty)\) is either the absolute value or \((x)_+ = \max\{0,x\}\), \(c_k > 0\) and \(p_k\in\mathbb{N}\). \(\mathcal{R}\) is law-invariant, but not coherent since it violates positive homogeneity. When \(\wp(x) = |x|\), \(\mathcal{R}\) also violates monotonicity.
When using derivative-based optimization, the user can provide a smooth approximation of \((\cdot)_+\) using the ROL::PositiveFunction class.
Definition at line 44 of file ROL_MeanVariance.hpp.
Member Typedef Documentation
uint
template<class Real > typedef std::vector<Real>::size_type ROL::MeanVariance< Real >::uint private
Definition at line 45 of file ROL_MeanVariance.hpp.
Constructor & Destructor Documentation
MeanVariance() [1/3]
template<class Real > ROL::MeanVariance< Real >::MeanVariance (const Real order, const Real coeff, const Ptr< PositiveFunction< Real > > & pf) inline
Constructor.
Parameters
[in] order is the variance order
[in] coeff is the weight for variance term
[in] pf is the plus function or an approximation
This constructor produces a mean plus variance risk measure with a single variance.
Definition at line 107 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::checkInputs(), ROL::MeanVariance< Real >::coeff_, ROL::MeanVariance< Real >::NumMoments_, and ROL::MeanVariance< Real >::order_.
MeanVariance() [2/3]
template<class Real > ROL::MeanVariance< Real >::MeanVariance (const std::vector< Real > & order, const std::vector< Real > & coeff, const Ptr< PositiveFunction< Real > > & pf) inline
Constructor.
Parameters
[in] order is a vector of variance orders
[in] coeff is a vector of weights for the variance terms
[in] pf is the plus function or an approximation
This constructor produces a mean plus variance risk measure with an arbitrary number of variances.
Definition at line 125 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::checkInputs(), ROL::MeanVariance< Real >::coeff_, ROL::MeanVariance< Real >::NumMoments_, and ROL::MeanVariance< Real >::order_.
MeanVariance() [3/3]
template<class Real > ROL::MeanVariance< Real >::MeanVariance (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measure"->"Mean Plus Variance" and within the "Mean Plus Variance" sublist should have the following parameters
"Orders" (array of unsigned integers)
"Coefficients" (array of positive scalars)
"Deviation Type" (eighter "Upper" or "Absolute")
A sublist for positive function information.
Definition at line 151 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::checkInputs(), ROL::MeanVariance< Real >::coeff_, ROL::MeanVariance< Real >::NumMoments_, ROL::MeanVariance< Real >::order_, and ROL::MeanVariance< Real >::positiveFunction_.
Member Function Documentation
initializeMV()
template<class Real > void ROL::MeanVariance< Real >::initializeMV (void) inline private
Definition at line 71 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::gradients_, ROL::MeanVariance< Real >::gradvecs_, ROL::MeanVariance< Real >::hessvecs_, ROL::RandVarFunctional< Real >::setHessVecStorage(), ROL::RandVarFunctional< Real >::setStorage(), and ROL::MeanVariance< Real >::values_.
Referenced by ROL::MeanVariance< Real >::checkInputs().
checkInputs()
template<class Real > void ROL::MeanVariance< Real >::checkInputs (void) inline private
Definition at line 81 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::coeff_, ROL::MeanVariance< Real >::initializeMV(), ROL::MeanVariance< Real >::order_, ROL::MeanVariance< Real >::positiveFunction_, and zero.
Referenced by ROL::MeanVariance< Real >::MeanVariance(), ROL::MeanVariance< Real >::MeanVariance(), and ROL::MeanVariance< Real >::MeanVariance().
setStorage()
template<class Real > void ROL::MeanVariance< Real >::setStorage (const Ptr< ScalarController< Real > > & value_storage, const Ptr< VectorController< Real > > & gradient_storage) inline virtual
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 175 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::gradients_, ROL::RandVarFunctional< Real >::setStorage(), and ROL::MeanVariance< Real >::values_.
setHessVecStorage()
template<class Real > void ROL::MeanVariance< Real >::setHessVecStorage (const Ptr< ScalarController< Real > > & gradvec_storage, const Ptr< VectorController< Real > > & hessvec_storage) inline virtual
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 182 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::gradvecs_, ROL::MeanVariance< Real >::hessvecs_, and ROL::RandVarFunctional< Real >::setHessVecStorage().
updateValue()
template<class Real > void ROL::MeanVariance< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 189 of file ROL_MeanVariance.hpp.
References ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::MeanVariance< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 197 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::coeff_, ROL::SampleGenerator< Real >::getMyPoint(), ROL::SampleGenerator< Real >::getMyWeight(), ROL::MeanVariance< Real >::NumMoments_, ROL::SampleGenerator< Real >::numMySamples(), ROL::MeanVariance< Real >::order_, ROL::MeanVariance< Real >::positiveFunction_, ROL::SampleGenerator< Real >::start(), ROL::SampleGenerator< Real >::sumAll(), ROL::RandVarFunctional< Real >::val_, and ROL::MeanVariance< Real >::values_.
updateGradient()
template<class Real > void ROL::MeanVariance< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 219 of file ROL_MeanVariance.hpp.
References ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getGradient()
template<class Real > void ROL::MeanVariance< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 229 of file ROL_MeanVariance.hpp.
References ROL::MeanVariance< Real >::coeff_, ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::SampleGenerator< Real >::getMyPoint(), ROL::SampleGenerator< Real >::getMyWeight(), ROL::MeanVariance< Real >::gradients_, ROL::MeanVariance< Real >::NumMoments_, ROL::SampleGenerator< Real >::numMySamples(), ROL::MeanVariance< Real >::order_, ROL::Vector< Real >::plus(), ROL::MeanVariance< Real >::positiveFunction_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::start(), ROL::SampleGenerator< Real >::sumAll(), ROL::RandVarFunctional< Real >::val_, ROL::MeanVariance< Real >::values_, and zero.
updateHessVec()
template<class Real > void ROL::MeanVariance< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 262 of file ROL_MeanVariance.hpp.
References ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::gv_, ROL::RandVarFunctional< Real >::hv_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getHessVec()
template<class Real > void ROL::MeanVariance< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 277 of file ROL_MeanVariance.hpp.
References ROL::Vector< Real >::axpy(), ROL::MeanVariance< Real >::coeff_, ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::SampleGenerator< Real >::getMyPoint(), ROL::SampleGenerator< Real >::getMyWeight(), ROL::MeanVariance< Real >::gradients_, ROL::MeanVariance< Real >::gradvecs_, ROL::RandVarFunctional< Real >::gv_, ROL::MeanVariance< Real >::hessvecs_, ROL::RandVarFunctional< Real >::hv_, ROL::MeanVariance< Real >::NumMoments_, ROL::SampleGenerator< Real >::numMySamples(), ROL::MeanVariance< Real >::order_, ROL::Vector< Real >::plus(), ROL::MeanVariance< Real >::positiveFunction_, ROL::Vector< Real >::scale(), ROL::SampleGenerator< Real >::start(), ROL::SampleGenerator< Real >::sumAll(), ROL::RandVarFunctional< Real >::val_, ROL::MeanVariance< Real >::values_, and zero.
Member Data Documentation
positiveFunction_
template<class Real > Ptr<PositiveFunction<Real> > ROL::MeanVariance< Real >::positiveFunction_ private
Definition at line 47 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::checkInputs(), ROL::MeanVariance< Real >::getGradient(), ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::getValue(), and ROL::MeanVariance< Real >::MeanVariance().
order_
template<class Real > std::vector<Real> ROL::MeanVariance< Real >::order_ private
Definition at line 48 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::checkInputs(), ROL::MeanVariance< Real >::getGradient(), ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::getValue(), ROL::MeanVariance< Real >::MeanVariance(), ROL::MeanVariance< Real >::MeanVariance(), and ROL::MeanVariance< Real >::MeanVariance().
coeff_
template<class Real > std::vector<Real> ROL::MeanVariance< Real >::coeff_ private
Definition at line 49 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::checkInputs(), ROL::MeanVariance< Real >::getGradient(), ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::getValue(), ROL::MeanVariance< Real >::MeanVariance(), ROL::MeanVariance< Real >::MeanVariance(), and ROL::MeanVariance< Real >::MeanVariance().
NumMoments_
template<class Real > uint ROL::MeanVariance< Real >::NumMoments_ private
Definition at line 50 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::getGradient(), ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::getValue(), ROL::MeanVariance< Real >::MeanVariance(), ROL::MeanVariance< Real >::MeanVariance(), and ROL::MeanVariance< Real >::MeanVariance().
values_
template<class Real > Ptr<ScalarController<Real> > ROL::MeanVariance< Real >::values_ private
Definition at line 52 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::getGradient(), ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::getValue(), ROL::MeanVariance< Real >::initializeMV(), and ROL::MeanVariance< Real >::setStorage().
gradvecs_
template<class Real > Ptr<ScalarController<Real> > ROL::MeanVariance< Real >::gradvecs_ private
Definition at line 53 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::initializeMV(), and ROL::MeanVariance< Real >::setHessVecStorage().
gradients_
template<class Real > Ptr<VectorController<Real> > ROL::MeanVariance< Real >::gradients_ private
Definition at line 54 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::getGradient(), ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::initializeMV(), and ROL::MeanVariance< Real >::setStorage().
hessvecs_
template<class Real > Ptr<VectorController<Real> > ROL::MeanVariance< Real >::hessvecs_ private
Definition at line 55 of file ROL_MeanVariance.hpp.
Referenced by ROL::MeanVariance< Real >::getHessVec(), ROL::MeanVariance< Real >::initializeMV(), and ROL::MeanVariance< Real >::setHessVecStorage().
The documentation for this class was generated from the following file:
ROL_MeanVariance.hpp