ROL: ROL::NewtonStep< Real > Class Template Reference
ROL::NewtonStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with Newton's method globalized using line search.
#include <ROL_NewtonStep.hpp>
Public Member Functions
NewtonStep (ROL::ParameterList &parlist, const bool computeObj=true)
Constructor.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool print_header=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Attributes
int verbosity_
const bool computeObj_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::NewtonStep< Real >
Provides the interface to compute optimization steps with Newton's method globalized using line search.
Definition at line 25 of file ROL_NewtonStep.hpp.
Constructor & Destructor Documentation
NewtonStep()
template<class Real > ROL::NewtonStep< Real >::NewtonStep (ROL::ParameterList & parlist, const bool computeObj = true) inline
Constructor.
Standard constructor to build a NewtonStep object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
Definition at line 44 of file ROL_NewtonStep.hpp.
References ROL::NewtonStep< Real >::verbosity_.
Member Function Documentation
compute()
template<class Real > void ROL::NewtonStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 50 of file ROL_NewtonStep.hpp.
References ROL::Step< Real >::getState(), ROL::Objective< Real >::invHessVec(), and ROL::Vector< Real >::scale().
update()
template<class Real > void ROL::NewtonStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 61 of file ROL_NewtonStep.hpp.
References ROL::NewtonStep< Real >::computeObj_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::AlgorithmState< Real >::snorm, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::NewtonStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 86 of file ROL_NewtonStep.hpp.
References ROL::DESCENT_NEWTON, ROL::EDescentToString(), and ROL::NewtonStep< Real >::verbosity_.
Referenced by ROL::NewtonStep< Real >::print().
printName()
template<class Real > std::string ROL::NewtonStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 112 of file ROL_NewtonStep.hpp.
References ROL::DESCENT_NEWTON, and ROL::EDescentToString().
Referenced by ROL::NewtonStep< Real >::print().
print()
template<class Real > std::string ROL::NewtonStep< Real >::print (AlgorithmState< Real > & algo_state, bool printHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 117 of file ROL_NewtonStep.hpp.
References ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::NewtonStep< Real >::printHeader(), ROL::NewtonStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
verbosity_
template<class Real > int ROL::NewtonStep< Real >::verbosity_ private
Definition at line 28 of file ROL_NewtonStep.hpp.
Referenced by ROL::NewtonStep< Real >::NewtonStep(), and ROL::NewtonStep< Real >::printHeader().
computeObj_
template<class Real > const bool ROL::NewtonStep< Real >::computeObj_ private
Definition at line 29 of file ROL_NewtonStep.hpp.
Referenced by ROL::NewtonStep< Real >::update().
The documentation for this class was generated from the following file:
ROL_NewtonStep.hpp