ROL: ROL::Beta< Real > Class Template Reference
ROL::Beta< Real > Class Template Reference
#include <ROL_Beta.hpp>
Public Member Functions
Beta (const Real shape1=2., const Real shape2=2.)
Beta (ROL::ParameterList &parlist)
Real evaluatePDF (const Real input) const
Real evaluateCDF (const Real input) const
Real integrateCDF (const Real input) const
Real invertCDF (const Real input) const
Real moment (const size_t m) const
Real lowerBound (void) const
Real upperBound (void) const
void test (std::ostream &outStream=std::cout) const
Public Member Functions inherited from ROL::Distribution< Real >
virtual ~Distribution (void)
Private Member Functions
void initializeQuadrature (void)
Real ibeta (const Real x) const
Private Attributes
Real shape1_
Real shape2_
Real coeff_
std::vector< Real > pts_
std::vector< Real > wts_
Additional Inherited Members
Protected Member Functions inherited from ROL::Distribution< Real >
void test (const std::vector< Real > &X, const std::vector< int > &T, std::ostream &outStream=std::cout) const
Detailed Description
template<class Real>
class ROL::Beta< Real >
Definition at line 21 of file ROL_Beta.hpp.
Constructor & Destructor Documentation
Beta() [1/2]
template<class Real > ROL::Beta< Real >::Beta (const Real shape1 = 2., const Real shape2 = 2.) inline
Definition at line 69 of file ROL_Beta.hpp.
References ROL::Beta< Real >::coeff_, ROL::Beta< Real >::initializeQuadrature(), ROL::Beta< Real >::shape1_, and ROL::Beta< Real >::shape2_.
Beta() [2/2]
template<class Real > ROL::Beta< Real >::Beta (ROL::ParameterList & parlist) inline
Definition at line 75 of file ROL_Beta.hpp.
References ROL::Beta< Real >::coeff_, ROL::Beta< Real >::initializeQuadrature(), ROL::Beta< Real >::shape1_, and ROL::Beta< Real >::shape2_.
Member Function Documentation
initializeQuadrature()
template<class Real > void ROL::Beta< Real >::initializeQuadrature (void) inline private
Definition at line 30 of file ROL_Beta.hpp.
References ROL::Beta< Real >::pts_, and ROL::Beta< Real >::wts_.
Referenced by ROL::Beta< Real >::Beta(), and ROL::Beta< Real >::Beta().
ibeta()
template<class Real > Real ROL::Beta< Real >::ibeta (const Real x) const inline private
Definition at line 58 of file ROL_Beta.hpp.
References ROL::Beta< Real >::pts_, ROL::Beta< Real >::shape1_, ROL::Beta< Real >::shape2_, and ROL::Beta< Real >::wts_.
Referenced by ROL::Beta< Real >::evaluateCDF().
evaluatePDF()
template<class Real > Real ROL::Beta< Real >::evaluatePDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 84 of file ROL_Beta.hpp.
References ROL::Beta< Real >::coeff_, ROL::Beta< Real >::shape1_, and ROL::Beta< Real >::shape2_.
evaluateCDF()
template<class Real > Real ROL::Beta< Real >::evaluateCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 89 of file ROL_Beta.hpp.
References ROL::Beta< Real >::coeff_, and ROL::Beta< Real >::ibeta().
Referenced by ROL::Beta< Real >::invertCDF().
integrateCDF()
template<class Real > Real ROL::Beta< Real >::integrateCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 93 of file ROL_Beta.hpp.
invertCDF()
template<class Real > Real ROL::Beta< Real >::invertCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 98 of file ROL_Beta.hpp.
References ROL::Beta< Real >::evaluateCDF().
moment()
template<class Real > Real ROL::Beta< Real >::moment (const size_t m) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 123 of file ROL_Beta.hpp.
References ROL::Beta< Real >::shape1_, and ROL::Beta< Real >::shape2_.
lowerBound()
template<class Real > Real ROL::Beta< Real >::lowerBound (void) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 137 of file ROL_Beta.hpp.
upperBound()
template<class Real > Real ROL::Beta< Real >::upperBound (void) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 141 of file ROL_Beta.hpp.
test()
template<class Real > void ROL::Beta< Real >::test (std::ostream & outStream = std::cout) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 145 of file ROL_Beta.hpp.
References ROL::Distribution< Real >::test().
Member Data Documentation
shape1_
template<class Real > Real ROL::Beta< Real >::shape1_ private
Definition at line 23 of file ROL_Beta.hpp.
Referenced by ROL::Beta< Real >::Beta(), ROL::Beta< Real >::Beta(), ROL::Beta< Real >::evaluatePDF(), ROL::Beta< Real >::ibeta(), and ROL::Beta< Real >::moment().
shape2_
template<class Real > Real ROL::Beta< Real >::shape2_ private
Definition at line 24 of file ROL_Beta.hpp.
Referenced by ROL::Beta< Real >::Beta(), ROL::Beta< Real >::Beta(), ROL::Beta< Real >::evaluatePDF(), ROL::Beta< Real >::ibeta(), and ROL::Beta< Real >::moment().
coeff_
template<class Real > Real ROL::Beta< Real >::coeff_ private
Definition at line 25 of file ROL_Beta.hpp.
Referenced by ROL::Beta< Real >::Beta(), ROL::Beta< Real >::Beta(), ROL::Beta< Real >::evaluateCDF(), and ROL::Beta< Real >::evaluatePDF().
pts_
template<class Real > std::vector<Real> ROL::Beta< Real >::pts_ private
Definition at line 27 of file ROL_Beta.hpp.
Referenced by ROL::Beta< Real >::ibeta(), and ROL::Beta< Real >::initializeQuadrature().
wts_
template<class Real > std::vector<Real> ROL::Beta< Real >::wts_ private
Definition at line 28 of file ROL_Beta.hpp.
Referenced by ROL::Beta< Real >::ibeta(), and ROL::Beta< Real >::initializeQuadrature().
The documentation for this class was generated from the following file:
ROL_Beta.hpp