ROL: ROL::DogLeg< Real > Class Template Reference
ROL::DogLeg< Real > Class Template Reference
Provides interface for dog leg trust-region subproblem solver.
#include <ROL_DogLeg.hpp>
Public Member Functions
DogLeg (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g)
void run (Vector< Real > &s, Real &snorm, int &iflag, int &iter, const Real del, TrustRegionModel< Real > &model)
Public Member Functions inherited from ROL::TrustRegion< Real >
virtual ~TrustRegion ()
TrustRegion (ROL::ParameterList &parlist)
virtual void update (Vector< Real > &x, Real &fnew, Real &del, int &nfval, int &ngrad, ETrustRegionFlag &flagTR, const Vector< Real > &s, const Real snorm, const Real fold, const Vector< Real > &g, int iter, Objective< Real > &obj, BoundConstraint< Real > &bnd, TrustRegionModel< Real > &model)
void setPredictedReduction (const Real pRed)
Real getPredictedReduction (void) const
Private Attributes
ROL::Ptr< CauchyPoint< Real > > cpt_
ROL::Ptr< Vector< Real > > s_
ROL::Ptr< Vector< Real > > Hp_
Real pRed_
Detailed Description
template<class Real>
class ROL::DogLeg< Real >
Provides interface for dog leg trust-region subproblem solver.
Definition at line 23 of file ROL_DogLeg.hpp.
Constructor & Destructor Documentation
DogLeg()
template<class Real > ROL::DogLeg< Real >::DogLeg (ROL::ParameterList & parlist) inline
Definition at line 36 of file ROL_DogLeg.hpp.
References ROL::DogLeg< Real >::cpt_.
Member Function Documentation
initialize()
template<class Real > void ROL::DogLeg< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g) inline virtual
Reimplemented from ROL::TrustRegion< Real >.
Definition at line 40 of file ROL_DogLeg.hpp.
References ROL::Vector< Real >::clone(), ROL::DogLeg< Real >::cpt_, ROL::DogLeg< Real >::Hp_, ROL::TrustRegion< Real >::initialize(), and ROL::DogLeg< Real >::s_.
run()
template<class Real > void ROL::DogLeg< Real >::run (Vector< Real > & s, Real & snorm, int & iflag, int & iter, const Real del, TrustRegionModel< Real > & model) inline virtual
Implements ROL::TrustRegion< Real >.
Definition at line 47 of file ROL_DogLeg.hpp.
References ROL::Vector< Real >::axpy(), ROL::DogLeg< Real >::cpt_, ROL::Vector< Real >::dual(), ROL::TrustRegionModel< Real >::dualTransform(), ROL::TrustRegionModel< Real >::getGradient(), ROL::TrustRegionModel< Real >::hessVec(), ROL::DogLeg< Real >::Hp_, ROL::TrustRegionModel< Real >::invHessVec(), ROL::Vector< Real >::norm(), ROL::DogLeg< Real >::pRed_, ROL::TrustRegionModel< Real >::primalTransform(), ROL::DogLeg< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::TrustRegion< Real >::setPredictedReduction(), and zero.
Member Data Documentation
cpt_
template<class Real > ROL::Ptr<CauchyPoint<Real> > ROL::DogLeg< Real >::cpt_ private
Definition at line 26 of file ROL_DogLeg.hpp.
Referenced by ROL::DogLeg< Real >::DogLeg(), ROL::DogLeg< Real >::initialize(), and ROL::DogLeg< Real >::run().
s_
template<class Real > ROL::Ptr<Vector<Real> > ROL::DogLeg< Real >::s_ private
Definition at line 28 of file ROL_DogLeg.hpp.
Referenced by ROL::DogLeg< Real >::initialize(), and ROL::DogLeg< Real >::run().
Hp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::DogLeg< Real >::Hp_ private
Definition at line 29 of file ROL_DogLeg.hpp.
Referenced by ROL::DogLeg< Real >::initialize(), and ROL::DogLeg< Real >::run().
pRed_
template<class Real > Real ROL::DogLeg< Real >::pRed_ private
Definition at line 31 of file ROL_DogLeg.hpp.
Referenced by ROL::DogLeg< Real >::run().
The documentation for this class was generated from the following file:
ROL_DogLeg.hpp