ROL: ROL::details::DynamicConstraint_CheckInterface< Real > Class Template Reference
ROL::details::DynamicConstraint_CheckInterface< Real > Class Template Reference
#include <ROL_DynamicConstraint_CheckInterface.hpp>
Public Member Functions
DynamicConstraint_CheckInterface (Con &con)
DynamicConstraint_CheckInterface (Con &con, TimeStamp< Real > &ts)
f_update_t< Real > update_uo (const V &un, const V &z)
f_update_t< Real > update_un (const V &uo, const V &z)
f_update_t< Real > update_z (const V &uo, const V &un)
f_vector_t< Real > value_uo (const V &un, const V &z)
f_vector_t< Real > value_un (const V &uo, const V &z)
f_vector_t< Real > value_z (const V &uo, const V &un)
f_solve_t< Real > solve_un (const V &uo, const V &z)
f_dderiv_t< Real > jacobian_uo (const V &un, const V &z)
f_dderiv_t< Real > jacobian_un (const V &uo, const V &z)
f_dderiv_t< Real > inverseJacobian_un (const V &uo, const V &z)
f_dderiv_t< Real > jacobian_z (const V &uo, const V &un)
f_dderiv_t< Real > adjointJacobian_uo (const V &un, const V &z)
f_dderiv_t< Real > adjointJacobian_un (const V &uo, const V &z)
f_dderiv_t< Real > inverseAdjointJacobian_un (const V &uo, const V &z)
f_dderiv_t< Real > adjointJacobian_z (const V &uo, const V &un)
f_dderiv_t< Real > adjointJacobian_uo_uo (const V &un, const V &z)
f_dderiv_t< Real > adjointJacobian_uo_un (const V &uo, const V &z)
f_dderiv_t< Real > adjointJacobian_uo_z (const V &uo, const V &un)
f_dderiv_t< Real > adjointJacobian_un_uo (const V &un, const V &z)
f_dderiv_t< Real > adjointJacobian_un_un (const V &uo, const V &z)
f_dderiv_t< Real > adjointJacobian_un_z (const V &uo, const V &un)
f_dderiv_t< Real > adjointJacobian_z_uo (const V &un, const V &z)
f_dderiv_t< Real > adjointJacobian_z_un (const V &uo, const V &z)
f_dderiv_t< Real > adjointJacobian_z_z (const V &uo, const V &un)
f_dderiv_t< Real > adjointHessian_un_un (const V &uo, const V &z, const V &l)
f_dderiv_t< Real > adjointHessian_un_uo (const V &uo, const V &z, const V &l)
f_dderiv_t< Real > adjointHessian_un_z (const V &uo, const V &z, const V &l)
f_dderiv_t< Real > adjointHessian_uo_un (const V &un, const V &z, const V &l)
f_dderiv_t< Real > adjointHessian_uo_uo (const V &un, const V &z, const V &l)
f_dderiv_t< Real > adjointHessian_uo_z (const V &un, const V &z, const V &l)
f_dderiv_t< Real > adjointHessian_z_un (const V &uo, const V &un, const V &l)
f_dderiv_t< Real > adjointHessian_z_uo (const V &uo, const V &un, const V &l)
f_dderiv_t< Real > adjointHessian_z_z (const V &uo, const V &un, const V &l)
Private Types
using V = Vector< Real >
using Con = DynamicConstraint< Real >
Private Attributes
Con & con_
Real tol_
TimeStamp< Real > ts_
Detailed Description
template<typename Real>
class ROL::details::DynamicConstraint_CheckInterface< Real >
Definition at line 21 of file ROL_DynamicConstraint_CheckInterface.hpp.
Member Typedef Documentation
V
template<typename Real > using ROL::details::DynamicConstraint_CheckInterface< Real >::V = Vector<Real> private
Definition at line 24 of file ROL_DynamicConstraint_CheckInterface.hpp.
Con
template<typename Real > using ROL::details::DynamicConstraint_CheckInterface< Real >::Con = DynamicConstraint<Real> private
Definition at line 25 of file ROL_DynamicConstraint_CheckInterface.hpp.
Constructor & Destructor Documentation
DynamicConstraint_CheckInterface() [1/2]
template<typename Real > ROL::details::DynamicConstraint_CheckInterface< Real >::DynamicConstraint_CheckInterface (Con & con) inline
Definition at line 33 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
DynamicConstraint_CheckInterface() [2/2]
template<typename Real > ROL::details::DynamicConstraint_CheckInterface< Real >::DynamicConstraint_CheckInterface (Con & con, TimeStamp< Real > & ts) inline
Definition at line 40 of file ROL_DynamicConstraint_CheckInterface.hpp.
Member Function Documentation
update_uo()
template<typename Real > f_update_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::update_uo (const V & un, const V & z) inline
Definition at line 43 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::con_, ROL::details::DynamicConstraint_CheckInterface< Real >::ts_, and ROL::DynamicConstraint< Real >::update().
Referenced by ROL::DynamicConstraintCheck< Real >::check().
update_un()
template<typename Real > f_update_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::update_un (const V & uo, const V & z) inline
Definition at line 47 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::con_, ROL::details::DynamicConstraint_CheckInterface< Real >::ts_, and ROL::DynamicConstraint< Real >::update().
Referenced by ROL::DynamicConstraintCheck< Real >::check().
update_z()
template<typename Real > f_update_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::update_z (const V & uo, const V & un) inline
Definition at line 51 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::con_, ROL::details::DynamicConstraint_CheckInterface< Real >::ts_, and ROL::DynamicConstraint< Real >::update().
Referenced by ROL::DynamicConstraintCheck< Real >::check().
value_uo()
template<typename Real > f_vector_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::value_uo (const V & un, const V & z) inline
Definition at line 57 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::con_, ROL::details::DynamicConstraint_CheckInterface< Real >::ts_, and ROL::DynamicConstraint< Real >::value().
Referenced by ROL::DynamicConstraintCheck< Real >::check().
value_un()
template<typename Real > f_vector_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::value_un (const V & uo, const V & z) inline
Definition at line 62 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::con_, ROL::details::DynamicConstraint_CheckInterface< Real >::ts_, and ROL::DynamicConstraint< Real >::value().
Referenced by ROL::DynamicConstraintCheck< Real >::check().
value_z()
template<typename Real > f_vector_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::value_z (const V & uo, const V & un) inline
Definition at line 67 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::con_, ROL::details::DynamicConstraint_CheckInterface< Real >::ts_, and ROL::DynamicConstraint< Real >::value().
Referenced by ROL::DynamicConstraintCheck< Real >::check().
solve_un()
template<typename Real > f_solve_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::solve_un (const V & uo, const V & z) inline
Definition at line 72 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::con_, ROL::DynamicConstraint< Real >::solve(), and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
jacobian_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_uo (const V & un, const V & z) inline
Definition at line 79 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
jacobian_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_un (const V & uo, const V & z) inline
Definition at line 84 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
inverseJacobian_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::inverseJacobian_un (const V & uo, const V & z) inline
Definition at line 89 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyInverseJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
jacobian_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_z (const V & uo, const V & un) inline
Definition at line 94 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo (const V & un, const V & z) inline
Definition at line 101 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un (const V & uo, const V & z) inline
Definition at line 106 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
inverseAdjointJacobian_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::inverseAdjointJacobian_un (const V & uo, const V & z) inline
Definition at line 111 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyInverseAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z (const V & uo, const V & un) inline
Definition at line 116 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_uo_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_uo (const V & un, const V & z) inline
Definition at line 123 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_uo_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_un (const V & uo, const V & z) inline
Definition at line 128 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_uo_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_z (const V & uo, const V & un) inline
Definition at line 133 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_un_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_uo (const V & un, const V & z) inline
Definition at line 138 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_un_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_un (const V & uo, const V & z) inline
Definition at line 143 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_un_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_z (const V & uo, const V & un) inline
Definition at line 148 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_z_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_uo (const V & un, const V & z) inline
Definition at line 153 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_z_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_un (const V & uo, const V & z) inline
Definition at line 158 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointJacobian_z_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_z (const V & uo, const V & un) inline
Definition at line 163 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_un_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_un (const V & uo, const V & z, const V & l) inline
Definition at line 170 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_un_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_un_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_uo (const V & uo, const V & z, const V & l) inline
Definition at line 175 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_un_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_un_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_z (const V & uo, const V & z, const V & l) inline
Definition at line 180 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_un_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_uo_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_un (const V & un, const V & z, const V & l) inline
Definition at line 187 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_uo_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_uo_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_uo (const V & un, const V & z, const V & l) inline
Definition at line 192 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_uo_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_uo_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_z (const V & un, const V & z, const V & l) inline
Definition at line 197 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_uo_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_z_un()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_un (const V & uo, const V & un, const V & l) inline
Definition at line 204 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_z_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_z_uo()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_uo (const V & uo, const V & un, const V & l) inline
Definition at line 209 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_z_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
adjointHessian_z_z()
template<typename Real > f_dderiv_t< Real > ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_z (const V & uo, const V & un, const V & l) inline
Definition at line 214 of file ROL_DynamicConstraint_CheckInterface.hpp.
References ROL::DynamicConstraint< Real >::applyAdjointHessian_z_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::con_, and ROL::details::DynamicConstraint_CheckInterface< Real >::ts_.
Referenced by ROL::DynamicConstraintCheck< Real >::check().
Member Data Documentation
con_
template<typename Real > Con& ROL::details::DynamicConstraint_CheckInterface< Real >::con_ private
Definition at line 27 of file ROL_DynamicConstraint_CheckInterface.hpp.
Referenced by ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::inverseAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::inverseJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::solve_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::value_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::value_uo(), and ROL::details::DynamicConstraint_CheckInterface< Real >::value_z().
tol_
template<typename Real > Real ROL::details::DynamicConstraint_CheckInterface< Real >::tol_ private
Definition at line 28 of file ROL_DynamicConstraint_CheckInterface.hpp.
ts_
template<typename Real > TimeStamp<Real> ROL::details::DynamicConstraint_CheckInterface< Real >::ts_ private
Definition at line 29 of file ROL_DynamicConstraint_CheckInterface.hpp.
Referenced by ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::DynamicConstraint_CheckInterface(), ROL::details::DynamicConstraint_CheckInterface< Real >::inverseAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::inverseJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::solve_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::value_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::value_uo(), and ROL::details::DynamicConstraint_CheckInterface< Real >::value_z().
The documentation for this class was generated from the following file:
ROL_DynamicConstraint_CheckInterface.hpp