ROL: ROL::Smale< Real > Class Template Reference
ROL::Smale< Real > Class Template Reference
#include <ROL_Smale.hpp>
Public Member Functions
Smale (const Real a=0., const Real b=1.)
Smale (ROL::ParameterList &parlist)
Real evaluatePDF (const Real input) const
Real evaluateCDF (const Real input) const
Real integrateCDF (const Real input) const
Real invertCDF (const Real input) const
Real moment (const size_t m) const
Real lowerBound (void) const
Real upperBound (void) const
void test (std::ostream &outStream=std::cout) const
Public Member Functions inherited from ROL::Distribution< Real >
virtual ~Distribution (void)
Private Attributes
Real a_
Real b_
Additional Inherited Members
Protected Member Functions inherited from ROL::Distribution< Real >
void test (const std::vector< Real > &X, const std::vector< int > &T, std::ostream &outStream=std::cout) const
Detailed Description
template<class Real>
class ROL::Smale< Real >
Definition at line 19 of file ROL_Smale.hpp.
Constructor & Destructor Documentation
Smale() [1/2]
template<class Real > ROL::Smale< Real >::Smale (const Real a = 0., const Real b = 1.) inline
Definition at line 25 of file ROL_Smale.hpp.
Smale() [2/2]
template<class Real > ROL::Smale< Real >::Smale (ROL::ParameterList & parlist) inline
Definition at line 28 of file ROL_Smale.hpp.
References ROL::Smale< Real >::a_, and ROL::Smale< Real >::b_.
Member Function Documentation
evaluatePDF()
template<class Real > Real ROL::Smale< Real >::evaluatePDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 36 of file ROL_Smale.hpp.
References ROL::Smale< Real >::a_, and ROL::Smale< Real >::b_.
Referenced by ROL::Smale< Real >::invertCDF().
evaluateCDF()
template<class Real > Real ROL::Smale< Real >::evaluateCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 42 of file ROL_Smale.hpp.
References ROL::Smale< Real >::a_, and ROL::Smale< Real >::b_.
Referenced by ROL::Smale< Real >::invertCDF().
integrateCDF()
template<class Real > Real ROL::Smale< Real >::integrateCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 48 of file ROL_Smale.hpp.
References ROL::Smale< Real >::a_, and ROL::Smale< Real >::b_.
invertCDF()
template<class Real > Real ROL::Smale< Real >::invertCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 54 of file ROL_Smale.hpp.
References ROL::Smale< Real >::a_, ROL::Smale< Real >::evaluateCDF(), and ROL::Smale< Real >::evaluatePDF().
moment()
template<class Real > Real ROL::Smale< Real >::moment (const size_t m) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 78 of file ROL_Smale.hpp.
lowerBound()
template<class Real > Real ROL::Smale< Real >::lowerBound (void) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 83 of file ROL_Smale.hpp.
upperBound()
template<class Real > Real ROL::Smale< Real >::upperBound (void) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 87 of file ROL_Smale.hpp.
test()
template<class Real > void ROL::Smale< Real >::test (std::ostream & outStream = std::cout) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 91 of file ROL_Smale.hpp.
References ROL::Distribution< Real >::test().
Member Data Documentation
a_
template<class Real > Real ROL::Smale< Real >::a_ private
Definition at line 21 of file ROL_Smale.hpp.
Referenced by ROL::Smale< Real >::evaluateCDF(), ROL::Smale< Real >::evaluatePDF(), ROL::Smale< Real >::integrateCDF(), ROL::Smale< Real >::invertCDF(), and ROL::Smale< Real >::Smale().
b_
template<class Real > Real ROL::Smale< Real >::b_ private
Definition at line 22 of file ROL_Smale.hpp.
Referenced by ROL::Smale< Real >::evaluateCDF(), ROL::Smale< Real >::evaluatePDF(), ROL::Smale< Real >::integrateCDF(), and ROL::Smale< Real >::Smale().
The documentation for this class was generated from the following file:
ROL_Smale.hpp