ROL: ROL::ExpectationQuadRisk< Real > Class Template Reference
ROL::ExpectationQuadRisk< Real > Class Template Reference
#include <ROL_ExpectationQuadRisk.hpp>
Public Member Functions
ExpectationQuadRisk (const Ptr< ExpectationQuad< Real > > &eq)
void checkRegret (void)
Run derivative tests for the scalar regret function.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void initialize (const Vector< Real > &x)
Initialize temporary variables.
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Attributes
Ptr< ExpectationQuad< Real > > eq_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::ExpectationQuadRisk< Real >
Definition at line 55 of file ROL_ExpectationQuadRisk.hpp.
Constructor & Destructor Documentation
ExpectationQuadRisk()
template<class Real > ROL::ExpectationQuadRisk< Real >::ExpectationQuadRisk (const Ptr< ExpectationQuad< Real > > & eq) inline
Definition at line 74 of file ROL_ExpectationQuadRisk.hpp.
Member Function Documentation
checkRegret()
template<class Real > void ROL::ExpectationQuadRisk< Real >::checkRegret (void) inline
Run derivative tests for the scalar regret function.
Definition at line 79 of file ROL_ExpectationQuadRisk.hpp.
References ROL::ExpectationQuadRisk< Real >::eq_.
updateValue()
template<class Real > void ROL::ExpectationQuadRisk< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 83 of file ROL_ExpectationQuadRisk.hpp.
References ROL::RandVarFunctional< Real >::computeValue(), ROL::ExpectationQuadRisk< Real >::eq_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
updateGradient()
template<class Real > void ROL::ExpectationQuadRisk< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 92 of file ROL_ExpectationQuadRisk.hpp.
References ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::ExpectationQuadRisk< Real >::eq_, ROL::RandVarFunctional< Real >::g_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
updateHessVec()
template<class Real > void ROL::ExpectationQuadRisk< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 105 of file ROL_ExpectationQuadRisk.hpp.
References ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::ExpectationQuadRisk< Real >::eq_, ROL::RandVarFunctional< Real >::hv_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::ExpectationQuadRisk< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 125 of file ROL_ExpectationQuadRisk.hpp.
References ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
getGradient()
template<class Real > void ROL::ExpectationQuadRisk< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 134 of file ROL_ExpectationQuadRisk.hpp.
References ROL::RandVarFunctional< Real >::g_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
getHessVec()
template<class Real > void ROL::ExpectationQuadRisk< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 146 of file ROL_ExpectationQuadRisk.hpp.
References ROL::RandVarFunctional< Real >::hv_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
Member Data Documentation
eq_
template<class Real > Ptr<ExpectationQuad<Real> > ROL::ExpectationQuadRisk< Real >::eq_ private
Definition at line 57 of file ROL_ExpectationQuadRisk.hpp.
Referenced by ROL::ExpectationQuadRisk< Real >::checkRegret(), ROL::ExpectationQuadRisk< Real >::updateGradient(), ROL::ExpectationQuadRisk< Real >::updateHessVec(), and ROL::ExpectationQuadRisk< Real >::updateValue().
The documentation for this class was generated from the following file:
ROL_ExpectationQuadRisk.hpp