ROL: ROL::TruncatedMeanQuadrangle< Real > Class Template Reference
ROL::TruncatedMeanQuadrangle< Real > Class Template Reference
#include <ROL_TruncatedMeanQuadrangle.hpp>
Public Member Functions
TruncatedMeanQuadrangle (Real beta)
TruncatedMeanQuadrangle (ROL::ParameterList &parlist)
Real error (Real x, int deriv=0)
Evaluate the scalar error function at x.
Real regret (Real x, int deriv=0)
Evaluate the scalar regret function at x.
void check (void)
Run default derivative tests for the scalar regret function.
Public Member Functions inherited from ROL::ExpectationQuad< Real >
virtual ~ExpectationQuad (void)
ExpectationQuad (void)
Private Member Functions
void parseParameterList (ROL::ParameterList &parlist)
void checkInputs (void) const
Private Attributes
Real beta_
Detailed Description
template<class Real>
class ROL::TruncatedMeanQuadrangle< Real >
Definition at line 18 of file ROL_TruncatedMeanQuadrangle.hpp.
Constructor & Destructor Documentation
TruncatedMeanQuadrangle() [1/2]
template<class Real > ROL::TruncatedMeanQuadrangle< Real >::TruncatedMeanQuadrangle (Real beta) inline
Definition at line 49 of file ROL_TruncatedMeanQuadrangle.hpp.
References ROL::TruncatedMeanQuadrangle< Real >::checkInputs().
TruncatedMeanQuadrangle() [2/2]
template<class Real > ROL::TruncatedMeanQuadrangle< Real >::TruncatedMeanQuadrangle (ROL::ParameterList & parlist) inline
Definition at line 54 of file ROL_TruncatedMeanQuadrangle.hpp.
References ROL::TruncatedMeanQuadrangle< Real >::checkInputs(), and ROL::TruncatedMeanQuadrangle< Real >::parseParameterList().
Member Function Documentation
parseParameterList()
template<class Real > void ROL::TruncatedMeanQuadrangle< Real >::parseParameterList (ROL::ParameterList & parlist) inline private
Definition at line 23 of file ROL_TruncatedMeanQuadrangle.hpp.
References ROL::TruncatedMeanQuadrangle< Real >::beta_.
Referenced by ROL::TruncatedMeanQuadrangle< Real >::TruncatedMeanQuadrangle().
checkInputs()
template<class Real > void ROL::TruncatedMeanQuadrangle< Real >::checkInputs (void) const inline private
Definition at line 41 of file ROL_TruncatedMeanQuadrangle.hpp.
References ROL::TruncatedMeanQuadrangle< Real >::beta_, and zero.
Referenced by ROL::TruncatedMeanQuadrangle< Real >::TruncatedMeanQuadrangle(), and ROL::TruncatedMeanQuadrangle< Real >::TruncatedMeanQuadrangle().
error()
template<class Real > Real ROL::TruncatedMeanQuadrangle< Real >::error (Real x, int deriv = 0) inline virtual
Evaluate the scalar error function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(e(x)\) or a derivative of \(e(x)\).
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 60 of file ROL_TruncatedMeanQuadrangle.hpp.
References ROL::TruncatedMeanQuadrangle< Real >::beta_, and zero.
Referenced by ROL::TruncatedMeanQuadrangle< Real >::regret().
regret()
template<class Real > Real ROL::TruncatedMeanQuadrangle< Real >::regret (Real x, int deriv = 0) inline virtual
Evaluate the scalar regret function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(v(x)\) or a derivative of \(v(x)\).
Implements ROL::ExpectationQuad< Real >.
Definition at line 75 of file ROL_TruncatedMeanQuadrangle.hpp.
References ROL::TruncatedMeanQuadrangle< Real >::error(), and zero.
Referenced by ROL::TruncatedMeanQuadrangle< Real >::check().
check()
template<class Real > void ROL::TruncatedMeanQuadrangle< Real >::check (void) inline virtual
Run default derivative tests for the scalar regret function.
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 82 of file ROL_TruncatedMeanQuadrangle.hpp.
References ROL::TruncatedMeanQuadrangle< Real >::beta_, ROL::ExpectationQuad< Real >::check(), ROL::TruncatedMeanQuadrangle< Real >::regret(), and zero.
Member Data Documentation
beta_
template<class Real > Real ROL::TruncatedMeanQuadrangle< Real >::beta_ private
Definition at line 21 of file ROL_TruncatedMeanQuadrangle.hpp.
Referenced by ROL::TruncatedMeanQuadrangle< Real >::check(), ROL::TruncatedMeanQuadrangle< Real >::checkInputs(), ROL::TruncatedMeanQuadrangle< Real >::error(), and ROL::TruncatedMeanQuadrangle< Real >::parseParameterList().
The documentation for this class was generated from the following file:
ROL_TruncatedMeanQuadrangle.hpp