ROL: ROL::RaisedCosine< Real > Class Template Reference
ROL::RaisedCosine< Real > Class Template Reference
#include <ROL_RaisedCosine.hpp>
Public Member Functions
RaisedCosine (const Real mean=0.5, const Real var=0.5)
RaisedCosine (ROL::ParameterList &parlist)
Real evaluatePDF (const Real input) const
Real evaluateCDF (const Real input) const
Real integrateCDF (const Real input) const
Real invertCDF (const Real input) const
Real moment (const size_t m) const
Real lowerBound (void) const
Real upperBound (void) const
void test (std::ostream &outStream=std::cout) const
Public Member Functions inherited from ROL::Distribution< Real >
virtual ~Distribution (void)
Private Member Functions
size_t factorial (const size_t m) const
Private Attributes
Real mean_
Real var_
Additional Inherited Members
Protected Member Functions inherited from ROL::Distribution< Real >
void test (const std::vector< Real > &X, const std::vector< int > &T, std::ostream &outStream=std::cout) const
Detailed Description
template<class Real>
class ROL::RaisedCosine< Real >
Definition at line 19 of file ROL_RaisedCosine.hpp.
Constructor & Destructor Documentation
RaisedCosine() [1/2]
template<class Real > ROL::RaisedCosine< Real >::RaisedCosine (const Real mean = 0.5, const Real var = 0.5) inline
Definition at line 29 of file ROL_RaisedCosine.hpp.
RaisedCosine() [2/2]
template<class Real > ROL::RaisedCosine< Real >::RaisedCosine (ROL::ParameterList & parlist) inline
Definition at line 32 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::mean_, and ROL::RaisedCosine< Real >::var_.
Member Function Documentation
factorial()
template<class Real > size_t ROL::RaisedCosine< Real >::factorial (const size_t m) const inline private
Definition at line 24 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::factorial().
Referenced by ROL::RaisedCosine< Real >::factorial(), and ROL::RaisedCosine< Real >::moment().
evaluatePDF()
template<class Real > Real ROL::RaisedCosine< Real >::evaluatePDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 38 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::mean_, and ROL::RaisedCosine< Real >::var_.
evaluateCDF()
template<class Real > Real ROL::RaisedCosine< Real >::evaluateCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 44 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::mean_, ROL::ScalarTraits< Real >::pi(), and ROL::RaisedCosine< Real >::var_.
Referenced by ROL::RaisedCosine< Real >::invertCDF().
integrateCDF()
template<class Real > Real ROL::RaisedCosine< Real >::integrateCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 49 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::mean_, ROL::ScalarTraits< Real >::pi(), and ROL::RaisedCosine< Real >::var_.
invertCDF()
template<class Real > Real ROL::RaisedCosine< Real >::invertCDF (const Real input) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 56 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::evaluateCDF(), ROL::RaisedCosine< Real >::mean_, and ROL::RaisedCosine< Real >::var_.
moment()
template<class Real > Real ROL::RaisedCosine< Real >::moment (const size_t m) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 75 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::factorial(), ROL::RaisedCosine< Real >::mean_, ROL::ScalarTraits< Real >::pi(), and ROL::RaisedCosine< Real >::var_.
lowerBound()
template<class Real > Real ROL::RaisedCosine< Real >::lowerBound (void) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 91 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::mean_, and ROL::RaisedCosine< Real >::var_.
upperBound()
template<class Real > Real ROL::RaisedCosine< Real >::upperBound (void) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 95 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::mean_, and ROL::RaisedCosine< Real >::var_.
test()
template<class Real > void ROL::RaisedCosine< Real >::test (std::ostream & outStream = std::cout) const inline virtual
Reimplemented from ROL::Distribution< Real >.
Definition at line 99 of file ROL_RaisedCosine.hpp.
References ROL::RaisedCosine< Real >::mean_, ROL::Distribution< Real >::test(), and ROL::RaisedCosine< Real >::var_.
Member Data Documentation
mean_
template<class Real > Real ROL::RaisedCosine< Real >::mean_ private
Definition at line 21 of file ROL_RaisedCosine.hpp.
Referenced by ROL::RaisedCosine< Real >::evaluateCDF(), ROL::RaisedCosine< Real >::evaluatePDF(), ROL::RaisedCosine< Real >::integrateCDF(), ROL::RaisedCosine< Real >::invertCDF(), ROL::RaisedCosine< Real >::lowerBound(), ROL::RaisedCosine< Real >::moment(), ROL::RaisedCosine< Real >::RaisedCosine(), ROL::RaisedCosine< Real >::test(), and ROL::RaisedCosine< Real >::upperBound().
var_
template<class Real > Real ROL::RaisedCosine< Real >::var_ private
Definition at line 22 of file ROL_RaisedCosine.hpp.
Referenced by ROL::RaisedCosine< Real >::evaluateCDF(), ROL::RaisedCosine< Real >::evaluatePDF(), ROL::RaisedCosine< Real >::integrateCDF(), ROL::RaisedCosine< Real >::invertCDF(), ROL::RaisedCosine< Real >::lowerBound(), ROL::RaisedCosine< Real >::moment(), ROL::RaisedCosine< Real >::RaisedCosine(), ROL::RaisedCosine< Real >::test(), and ROL::RaisedCosine< Real >::upperBound().
The documentation for this class was generated from the following file:
ROL_RaisedCosine.hpp