ROL: ROL::FletcherObjectiveBase< Real > Class Template Reference
ROL::FletcherObjectiveBase< Real > Class Template Reference abstract
#include <ROL_FletcherObjectiveBase.hpp>
Public Member Functions
FletcherObjectiveBase (const Ptr< Objective< Real > > &obj, const Ptr< Constraint< Real > > &con, const Vector< Real > &xprim, const Vector< Real > &xdual, const Vector< Real > &cprim, const Vector< Real > &cdual, ParameterList &parlist)
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1) override
Update objective function.
Ptr< const Vector< Real > > getLagrangianGradient (const Vector< Real > &x)
Ptr< const Vector< Real > > getConstraintVec (const Vector< Real > &x)
Ptr< const Vector< Real > > getMultiplierVec (const Vector< Real > &x)
Ptr< const Vector< Real > > getGradient (const Vector< Real > &x)
Real getObjectiveValue (const Vector< Real > &x)
int getNumberFunctionEvaluations () const
int getNumberGradientEvaluations () const
int getNumberConstraintEvaluations () const
void reset (Real sigma, Real delta)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real value (const Vector< Real > &x, Real &tol)=0
Compute value.
virtual void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Protected Member Functions
Real objValue (const Vector< Real > &x, Real &tol)
void objGrad (Vector< Real > &g, const Vector< Real > &x, Real &tol)
void conValue (Vector< Real > &c, const Vector< Real > &x, Real &tol)
void computeMultipliers (Vector< Real > &y, Vector< Real > &gL, const Vector< Real > &x, Vector< Real > &g, Vector< Real > &c, Real tol)
virtual void solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &multSolverError_, bool refine)=0
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Protected Attributes
const Ptr< Objective< Real > > obj_
const Ptr< Constraint< Real > > con_
Real sigma_
Real delta_
Real quadPenaltyParameter_
bool useInexact_
int HessianApprox_
int nfval_
int ngval_
int ncval_
Ptr< ScalarController< Real, int > > fPhi_
Ptr< VectorController< Real, int > > gPhi_
Ptr< VectorController< Real, int > > y_
Ptr< ScalarController< Real, int > > fval_
Ptr< VectorController< Real, int > > g_
Ptr< VectorController< Real, int > > c_
Ptr< Vector< Real > > scaledc_
Ptr< Vector< Real > > gL_
Ptr< Vector< Real > > gLdual_
Ptr< Vector< Real > > xprim_
Ptr< Vector< Real > > xdual_
Ptr< Vector< Real > > cprim_
Ptr< Vector< Real > > cdual_
Real cnorm_
Real multSolverError_
Real gradSolveError_
Ptr< Krylov< Real > > krylov_
int iterKrylov_
int flagKrylov_
Ptr< Vector< Real > > v1_
Ptr< Vector< Real > > v2_
Ptr< Vector< Real > > b1_
Ptr< Vector< Real > > b2_
Ptr< Vector< Real > > w1_
Ptr< Vector< Real > > w2_
Ptr< PartitionedVector< Real > > vv_
Ptr< PartitionedVector< Real > > bb_
Ptr< PartitionedVector< Real > > ww_
Detailed Description
template<typename Real>
class ROL::FletcherObjectiveBase< Real >
Definition at line 25 of file ROL_FletcherObjectiveBase.hpp.
Constructor & Destructor Documentation
FletcherObjectiveBase()
template<typename Real > ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase (const Ptr< Objective< Real > > & obj, const Ptr< Constraint< Real > > & con, const Vector< Real > & xprim, const Vector< Real > & xdual, const Vector< Real > & cprim, const Vector< Real > & cdual, ParameterList & parlist)
Definition at line 16 of file ROL_FletcherObjectiveBase_Def.hpp.
References ROL::FletcherObjectiveBase< Real >::b1_, ROL::FletcherObjectiveBase< Real >::b2_, ROL::FletcherObjectiveBase< Real >::bb_, ROL::FletcherObjectiveBase< Real >::cdual_, ROL::Vector< Real >::clone(), ROL::FletcherObjectiveBase< Real >::cprim_, ROL::FletcherObjectiveBase< Real >::gL_, ROL::FletcherObjectiveBase< Real >::gLdual_, ROL::FletcherObjectiveBase< Real >::HessianApprox_, ROL::FletcherObjectiveBase< Real >::krylov_, ROL::FletcherObjectiveBase< Real >::quadPenaltyParameter_, ROL::FletcherObjectiveBase< Real >::scaledc_, ROL::FletcherObjectiveBase< Real >::useInexact_, ROL::FletcherObjectiveBase< Real >::v1_, ROL::FletcherObjectiveBase< Real >::v2_, ROL::FletcherObjectiveBase< Real >::vv_, ROL::FletcherObjectiveBase< Real >::w1_, ROL::FletcherObjectiveBase< Real >::w2_, ROL::FletcherObjectiveBase< Real >::ww_, ROL::FletcherObjectiveBase< Real >::xdual_, and ROL::FletcherObjectiveBase< Real >::xprim_.
Member Function Documentation
update()
template<typename Real > void ROL::FletcherObjectiveBase< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 68 of file ROL_FletcherObjectiveBase_Def.hpp.
References obj_.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize().
getLagrangianGradient()
template<typename Real > Ptr< const Vector< Real > > ROL::FletcherObjectiveBase< Real >::getLagrangianGradient (const Vector< Real > & x)
Definition at line 81 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::FletcherAlgorithm< Real >::run().
getConstraintVec()
template<typename Real > Ptr< const Vector< Real > > ROL::FletcherObjectiveBase< Real >::getConstraintVec (const Vector< Real > & x)
Definition at line 90 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::FletcherAlgorithm< Real >::run().
getMultiplierVec()
template<typename Real > Ptr< const Vector< Real > > ROL::FletcherObjectiveBase< Real >::getMultiplierVec (const Vector< Real > & x)
Definition at line 97 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::run().
getGradient()
template<typename Real > Ptr< const Vector< Real > > ROL::FletcherObjectiveBase< Real >::getGradient (const Vector< Real > & x)
Definition at line 105 of file ROL_FletcherObjectiveBase_Def.hpp.
getObjectiveValue()
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::getObjectiveValue (const Vector< Real > & x)
Definition at line 113 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::FletcherAlgorithm< Real >::run().
getNumberFunctionEvaluations()
template<typename Real > int ROL::FletcherObjectiveBase< Real >::getNumberFunctionEvaluations () const
Definition at line 119 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::FletcherAlgorithm< Real >::run().
getNumberGradientEvaluations()
template<typename Real > int ROL::FletcherObjectiveBase< Real >::getNumberGradientEvaluations () const
Definition at line 124 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::FletcherAlgorithm< Real >::run().
getNumberConstraintEvaluations()
template<typename Real > int ROL::FletcherObjectiveBase< Real >::getNumberConstraintEvaluations () const
Definition at line 129 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::FletcherAlgorithm< Real >::run().
reset()
template<typename Real > void ROL::FletcherObjectiveBase< Real >::reset (Real sigma, Real delta)
Definition at line 134 of file ROL_FletcherObjectiveBase_Def.hpp.
Referenced by ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::FletcherAlgorithm< Real >::run().
objValue()
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::objValue (const Vector< Real > & x, Real & tol) protected
Definition at line 142 of file ROL_FletcherObjectiveBase_Def.hpp.
References obj_.
Referenced by ROL::FletcherObjectiveE< Real >::value().
objGrad()
template<typename Real > void ROL::FletcherObjectiveBase< Real >::objGrad (Vector< Real > & g, const Vector< Real > & x, Real & tol) protected
Definition at line 154 of file ROL_FletcherObjectiveBase_Def.hpp.
References obj_.
conValue()
template<typename Real > void ROL::FletcherObjectiveBase< Real >::conValue (Vector< Real > & c, const Vector< Real > & x, Real & tol) protected
Definition at line 164 of file ROL_FletcherObjectiveBase_Def.hpp.
computeMultipliers()
template<typename Real > void ROL::FletcherObjectiveBase< Real >::computeMultipliers (Vector< Real > & y, Vector< Real > & gL, const Vector< Real > & x, Vector< Real > & g, Vector< Real > & c, Real tol) protected
Definition at line 174 of file ROL_FletcherObjectiveBase_Def.hpp.
References ROL::Vector< Real >::norm().
Referenced by ROL::FletcherObjectiveE< Real >::gradient(), ROL::FletcherObjectiveE< Real >::hessVec(), and ROL::FletcherObjectiveE< Real >::value().
solveAugmentedSystem()
template<typename Real > virtual void ROL::FletcherObjectiveBase< Real >::solveAugmentedSystem (Vector< Real > & v1, Vector< Real > & v2, const Vector< Real > & b1, const Vector< Real > & b2, const Vector< Real > & x, Real & multSolverError_, bool refine) protected pure virtual
Implemented in ROL::FletcherObjectiveE< Real >.
Member Data Documentation
obj_
template<typename Real > const Ptr<Objective<Real> > ROL::FletcherObjectiveBase< Real >::obj_ protected
Definition at line 27 of file ROL_FletcherObjectiveBase.hpp.
con_
template<typename Real > const Ptr<Constraint<Real> > ROL::FletcherObjectiveBase< Real >::con_ protected
Definition at line 28 of file ROL_FletcherObjectiveBase.hpp.
sigma_
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::sigma_ protected
Definition at line 30 of file ROL_FletcherObjectiveBase.hpp.
delta_
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::delta_ protected
Definition at line 31 of file ROL_FletcherObjectiveBase.hpp.
quadPenaltyParameter_
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::quadPenaltyParameter_ protected
Definition at line 32 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
useInexact_
template<typename Real > bool ROL::FletcherObjectiveBase< Real >::useInexact_ protected
Definition at line 33 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
HessianApprox_
template<typename Real > int ROL::FletcherObjectiveBase< Real >::HessianApprox_ protected
Definition at line 34 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
nfval_
template<typename Real > int ROL::FletcherObjectiveBase< Real >::nfval_ protected
Definition at line 37 of file ROL_FletcherObjectiveBase.hpp.
ngval_
template<typename Real > int ROL::FletcherObjectiveBase< Real >::ngval_ protected
Definition at line 37 of file ROL_FletcherObjectiveBase.hpp.
ncval_
template<typename Real > int ROL::FletcherObjectiveBase< Real >::ncval_ protected
Definition at line 37 of file ROL_FletcherObjectiveBase.hpp.
fPhi_
template<typename Real > Ptr<ScalarController<Real,int> > ROL::FletcherObjectiveBase< Real >::fPhi_ protected
Definition at line 39 of file ROL_FletcherObjectiveBase.hpp.
gPhi_
template<typename Real > Ptr<VectorController<Real,int> > ROL::FletcherObjectiveBase< Real >::gPhi_ protected
Definition at line 40 of file ROL_FletcherObjectiveBase.hpp.
y_
template<typename Real > Ptr<VectorController<Real,int> > ROL::FletcherObjectiveBase< Real >::y_ protected
Definition at line 41 of file ROL_FletcherObjectiveBase.hpp.
fval_
template<typename Real > Ptr<ScalarController<Real,int> > ROL::FletcherObjectiveBase< Real >::fval_ protected
Definition at line 42 of file ROL_FletcherObjectiveBase.hpp.
g_
template<typename Real > Ptr<VectorController<Real,int> > ROL::FletcherObjectiveBase< Real >::g_ protected
Definition at line 43 of file ROL_FletcherObjectiveBase.hpp.
c_
template<typename Real > Ptr<VectorController<Real,int> > ROL::FletcherObjectiveBase< Real >::c_ protected
Definition at line 44 of file ROL_FletcherObjectiveBase.hpp.
scaledc_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::scaledc_ protected
Definition at line 46 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
gL_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::gL_ protected
Definition at line 47 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
gLdual_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::gLdual_ protected
Definition at line 48 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
xprim_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::xprim_ protected
Definition at line 49 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
xdual_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::xdual_ protected
Definition at line 49 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
cprim_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::cprim_ protected
Definition at line 49 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
cdual_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::cdual_ protected
Definition at line 49 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
cnorm_
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::cnorm_ protected
Definition at line 51 of file ROL_FletcherObjectiveBase.hpp.
multSolverError_
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::multSolverError_ protected
Definition at line 53 of file ROL_FletcherObjectiveBase.hpp.
gradSolveError_
template<typename Real > Real ROL::FletcherObjectiveBase< Real >::gradSolveError_ protected
Definition at line 54 of file ROL_FletcherObjectiveBase.hpp.
krylov_
template<typename Real > Ptr<Krylov<Real> > ROL::FletcherObjectiveBase< Real >::krylov_ protected
Definition at line 57 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
iterKrylov_
template<typename Real > int ROL::FletcherObjectiveBase< Real >::iterKrylov_ protected
Definition at line 58 of file ROL_FletcherObjectiveBase.hpp.
flagKrylov_
template<typename Real > int ROL::FletcherObjectiveBase< Real >::flagKrylov_ protected
Definition at line 58 of file ROL_FletcherObjectiveBase.hpp.
v1_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::v1_ protected
Definition at line 59 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
v2_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::v2_ protected
Definition at line 59 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
b1_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::b1_ protected
Definition at line 59 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
b2_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::b2_ protected
Definition at line 59 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
w1_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::w1_ protected
Definition at line 59 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
w2_
template<typename Real > Ptr<Vector<Real> > ROL::FletcherObjectiveBase< Real >::w2_ protected
Definition at line 59 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
vv_
template<typename Real > Ptr<PartitionedVector<Real> > ROL::FletcherObjectiveBase< Real >::vv_ protected
Definition at line 60 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
bb_
template<typename Real > Ptr<PartitionedVector<Real> > ROL::FletcherObjectiveBase< Real >::bb_ protected
Definition at line 60 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
ww_
template<typename Real > Ptr<PartitionedVector<Real> > ROL::FletcherObjectiveBase< Real >::ww_ protected
Definition at line 60 of file ROL_FletcherObjectiveBase.hpp.
Referenced by ROL::FletcherObjectiveBase< Real >::FletcherObjectiveBase().
The documentation for this class was generated from the following files:
ROL_FletcherObjectiveBase.hpp
ROL_FletcherObjectiveBase_Def.hpp