ROL: ROL::LinearObjective_SimOpt< Real > Class Template Reference
ROL::LinearObjective_SimOpt< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate linear objective functions.
#include <ROL_LinearObjective_SimOpt.hpp>
Public Member Functions
LinearObjective_SimOpt (const Ptr< const Vector< Real > > &simcost=nullPtr, const Ptr< const Vector< Real > > &optcost=nullPtr)
Real value (const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (Vector< Real > &g, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (Vector< Real > &g, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
void hessVec_21 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
void hessVec_22 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Public Member Functions inherited from ROL::Objective_SimOpt< Real >
virtual void update (const Vector< Real > &u, const Vector< Real > &z, bool flag=true, int iter=-1)
Update objective function.
u is an iterate, z is an iterate, flag = true if the iterate has changed, iter is the outer algorithm iterations count.
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
const Ptr< const Vector< Real > > simcost_
const Ptr< const Vector< Real > > optcost_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::LinearObjective_SimOpt< Real >
Provides the interface to evaluate linear objective functions.
This class implements the linear objective function
\[ f(x) = \langle c, x\rangle_{\mathcal{X}^*,\mathcal{X}} \]
for fixed \(c\in\mathcal{X}^*\).
Definition at line 32 of file ROL_LinearObjective_SimOpt.hpp.
Constructor & Destructor Documentation
LinearObjective_SimOpt()
template<class Real > ROL::LinearObjective_SimOpt< Real >::LinearObjective_SimOpt (const Ptr< const Vector< Real > > & simcost = nullPtr, const Ptr< const Vector< Real > > & optcost = nullPtr) inline
Definition at line 37 of file ROL_LinearObjective_SimOpt.hpp.
Member Function Documentation
value()
template<class Real > Real ROL::LinearObjective_SimOpt< Real >::value (const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 41 of file ROL_LinearObjective_SimOpt.hpp.
References ROL::Vector< Real >::apply(), ROL::LinearObjective_SimOpt< Real >::optcost_, and ROL::LinearObjective_SimOpt< Real >::simcost_.
gradient_1()
template<class Real > void ROL::LinearObjective_SimOpt< Real >::gradient_1 (Vector< Real > & g, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 54 of file ROL_LinearObjective_SimOpt.hpp.
References ROL::Vector< Real >::set(), ROL::LinearObjective_SimOpt< Real >::simcost_, and ROL::Vector< Real >::zero().
gradient_2()
template<class Real > void ROL::LinearObjective_SimOpt< Real >::gradient_2 (Vector< Real > & g, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 63 of file ROL_LinearObjective_SimOpt.hpp.
References ROL::LinearObjective_SimOpt< Real >::optcost_, ROL::Vector< Real >::set(), and ROL::Vector< Real >::zero().
hessVec_11()
template<class Real > void ROL::LinearObjective_SimOpt< Real >::hessVec_11 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 72 of file ROL_LinearObjective_SimOpt.hpp.
References ROL::Vector< Real >::zero().
hessVec_12()
template<class Real > void ROL::LinearObjective_SimOpt< Real >::hessVec_12 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 76 of file ROL_LinearObjective_SimOpt.hpp.
References ROL::Vector< Real >::zero().
hessVec_21()
template<class Real > void ROL::LinearObjective_SimOpt< Real >::hessVec_21 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 80 of file ROL_LinearObjective_SimOpt.hpp.
References ROL::Vector< Real >::zero().
hessVec_22()
template<class Real > void ROL::LinearObjective_SimOpt< Real >::hessVec_22 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 84 of file ROL_LinearObjective_SimOpt.hpp.
References ROL::Vector< Real >::zero().
Member Data Documentation
simcost_
template<class Real > const Ptr<const Vector<Real> > ROL::LinearObjective_SimOpt< Real >::simcost_ private
Definition at line 34 of file ROL_LinearObjective_SimOpt.hpp.
Referenced by ROL::LinearObjective_SimOpt< Real >::gradient_1(), and ROL::LinearObjective_SimOpt< Real >::value().
optcost_
template<class Real > const Ptr<const Vector<Real> > ROL::LinearObjective_SimOpt< Real >::optcost_ private
Definition at line 34 of file ROL_LinearObjective_SimOpt.hpp.
Referenced by ROL::LinearObjective_SimOpt< Real >::gradient_2(), and ROL::LinearObjective_SimOpt< Real >::value().
The documentation for this class was generated from the following file:
ROL_LinearObjective_SimOpt.hpp