ROL: ROL::ConjugateGradients< Real > Class Template Reference
ROL::ConjugateGradients< Real > Class Template Reference
Provides definitions of the Conjugate Gradient solver.
#include <ROL_ConjugateGradients.hpp>
Public Member Functions
ConjugateGradients (Real absTol=1.e-4, Real relTol=1.e-2, unsigned maxit=100, bool useInexact=false)
Real run (Vector< Real > &x, LinearOperator< Real > &A, const Vector< Real > &b, LinearOperator< Real > &M, int &iter, int &flag)
Public Member Functions inherited from ROL::Krylov< Real >
virtual ~Krylov (void)
Krylov (Real absTol=1.e-4, Real relTol=1.e-2, unsigned maxit=100)
Krylov (ROL::ParameterList &parlist)
void resetAbsoluteTolerance (const Real absTol)
void resetRelativeTolerance (const Real relTol)
void resetMaximumIteration (const unsigned maxit)
Real getAbsoluteTolerance (void) const
Real getRelativeTolerance (void) const
unsigned getMaximumIteration (void) const
Private Attributes
bool isInitialized_
bool useInexact_
ROL::Ptr< Vector< Real > > r_
ROL::Ptr< Vector< Real > > v_
ROL::Ptr< Vector< Real > > p_
ROL::Ptr< Vector< Real > > Ap_
Detailed Description
template<class Real>
class ROL::ConjugateGradients< Real >
Provides definitions of the Conjugate Gradient solver.
Definition at line 23 of file ROL_ConjugateGradients.hpp.
Constructor & Destructor Documentation
ConjugateGradients()
template<class Real > ROL::ConjugateGradients< Real >::ConjugateGradients (Real absTol = 1.e-4, Real relTol = 1.e-2, unsigned maxit = 100, bool useInexact = false) inline
Definition at line 33 of file ROL_ConjugateGradients.hpp.
Member Function Documentation
run()
template<class Real > Real ROL::ConjugateGradients< Real >::run (Vector< Real > & x, LinearOperator< Real > & A, const Vector< Real > & b, LinearOperator< Real > & M, int & iter, int & flag) inline virtual
Implements ROL::Krylov< Real >.
Definition at line 36 of file ROL_ConjugateGradients.hpp.
References ROL::ConjugateGradients< Real >::Ap_, ROL::LinearOperator< Real >::apply(), ROL::LinearOperator< Real >::applyInverse(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::ConjugateGradients< Real >::isInitialized_, ROL::Vector< Real >::norm(), ROL::ConjugateGradients< Real >::p_, ROL::ConjugateGradients< Real >::r_, ROL::ConjugateGradients< Real >::useInexact_, ROL::ConjugateGradients< Real >::v_, zero, and ROL::Vector< Real >::zero().
Member Data Documentation
isInitialized_
template<class Real > bool ROL::ConjugateGradients< Real >::isInitialized_ private
Definition at line 25 of file ROL_ConjugateGradients.hpp.
Referenced by ROL::ConjugateGradients< Real >::run().
useInexact_
template<class Real > bool ROL::ConjugateGradients< Real >::useInexact_ private
Definition at line 26 of file ROL_ConjugateGradients.hpp.
Referenced by ROL::ConjugateGradients< Real >::run().
r_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateGradients< Real >::r_ private
Definition at line 27 of file ROL_ConjugateGradients.hpp.
Referenced by ROL::ConjugateGradients< Real >::run().
v_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateGradients< Real >::v_ private
Definition at line 28 of file ROL_ConjugateGradients.hpp.
Referenced by ROL::ConjugateGradients< Real >::run().
p_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateGradients< Real >::p_ private
Definition at line 29 of file ROL_ConjugateGradients.hpp.
Referenced by ROL::ConjugateGradients< Real >::run().
Ap_
template<class Real > ROL::Ptr<Vector<Real> > ROL::ConjugateGradients< Real >::Ap_ private
Definition at line 30 of file ROL_ConjugateGradients.hpp.
Referenced by ROL::ConjugateGradients< Real >::run().
The documentation for this class was generated from the following file:
ROL_ConjugateGradients.hpp