ROL: ROL::OptimizationProblem< Real > Class Template Reference
ROL::OptimizationProblem< Real > Class Template Reference
#include <ROL_OptimizationProblem.hpp>
Public Member Functions
virtual ~OptimizationProblem (void)
OptimizationProblem (void)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const std::vector< Ptr< Constraint< Real > > > &econ, const std::vector< Ptr< Vector< Real > > > &emul, const std::vector< Ptr< Constraint< Real > > > &icon, const std::vector< Ptr< Vector< Real > > > &imul, const std::vector< Ptr< BoundConstraint< Real > > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul, const std::vector< Ptr< Constraint< Real > > > &icon, const std::vector< Ptr< Vector< Real > > > &imul, const std::vector< Ptr< BoundConstraint< Real > > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const std::vector< Ptr< Constraint< Real > > > &econ, const std::vector< Ptr< Vector< Real > > > &emul, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const std::vector< Ptr< Constraint< Real > > > &econ, const std::vector< Ptr< Vector< Real > > > &emul, const std::vector< Ptr< Constraint< Real > > > &icon, const std::vector< Ptr< Vector< Real > > > &imul, const std::vector< Ptr< BoundConstraint< Real > > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul, const std::vector< Ptr< Constraint< Real > > > &icon, const std::vector< Ptr< Vector< Real > > > &imul, const std::vector< Ptr< BoundConstraint< Real > > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const std::vector< Ptr< Constraint< Real > > > &econ, const std::vector< Ptr< Vector< Real > > > &emul, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const std::vector< Ptr< Constraint< Real > > > &econ, const std::vector< Ptr< Vector< Real > > > &emul)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const std::vector< Ptr< Constraint< Real > > > &icon, const std::vector< Ptr< Vector< Real > > > &imul, const std::vector< Ptr< BoundConstraint< Real > > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const std::vector< Ptr< Constraint< Real > > > &econ, const std::vector< Ptr< Vector< Real > > > &emul)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< Constraint< Real > > &econ, const Ptr< Vector< Real > > &emul)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const std::vector< Ptr< Constraint< Real > > > &icon, const std::vector< Ptr< Vector< Real > > > &imul, const std::vector< Ptr< BoundConstraint< Real > > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< Constraint< Real > > &icon, const Ptr< Vector< Real > > &imul, const Ptr< BoundConstraint< Real > > &ibnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd)
OptimizationProblem (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x)
virtual Ptr< Objective< Real > > getObjective (void)
virtual Ptr< Vector< Real > > getSolutionVector (void)
virtual Ptr< BoundConstraint< Real > > getBoundConstraint (void)
virtual Ptr< Constraint< Real > > getConstraint (void)
virtual Ptr< Vector< Real > > getMultiplierVector (void)
EProblem getProblemType (void)
void setMeanValueObjective (const Ptr< SampleGenerator< Real > > &sampler)
Set objective function to mean value objective.
void setRiskNeutralObjective (const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler=nullPtr, const Ptr< SampleGenerator< Real > > &hsampler=nullPtr, const bool storage=true)
Set objective function to risk neutral objective.
void setRiskAverseObjective (ParameterList &parlist, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler=nullPtr, const Ptr< SampleGenerator< Real > > &hsampler=nullPtr)
Set objective function to risk averse objective.
void setStochasticObjective (ParameterList &parlist, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler=nullPtr, const Ptr< SampleGenerator< Real > > &hsampler=nullPtr)
void setMeanValueEquality (const Ptr< SampleGenerator< Real > > &sampler, const int index=0)
void setRiskNeutralEquality (const Ptr< SampleGenerator< Real > > &xsampler, const Ptr< BatchManager< Real > > &cbman, const int index=0)
void setAlmostSureEquality (const Ptr< SampleGenerator< Real > > &sampler, const int index=0)
void setStochasticEquality (std::vector< ParameterList > &parlist, const std::vector< Ptr< SampleGenerator< Real > > > &xsampler, const std::vector< Ptr< BatchManager< Real > > > &cbman)
void setStochasticEquality (ParameterList &parlist, const Ptr< SampleGenerator< Real > > &xsampler, const Ptr< BatchManager< Real > > &cbman)
void setMeanValueInequality (const Ptr< SampleGenerator< Real > > &sampler, const int index=0)
void setRiskNeutralInequality (const Ptr< SampleGenerator< Real > > &xsampler, const Ptr< BatchManager< Real > > &cbman, const int index=0)
void setRiskAverseInequality (ParameterList &parlist, const Ptr< SampleGenerator< Real > > &sampler, const int index=0)
void setAlmostSureInequality (const Ptr< SampleGenerator< Real > > &sampler, const int index=0)
void setStochasticInequality (std::vector< ParameterList > &parlist, const std::vector< Ptr< SampleGenerator< Real > > > &xsampler, const std::vector< Ptr< BatchManager< Real > > > &cbman)
void setStochasticInequality (ParameterList &parlist, const Ptr< SampleGenerator< Real > > &xsampler, const Ptr< BatchManager< Real > > &cbman)
Real getSolutionStatistic (int comp=0, int index=0)
Returns the statistic from the soluton vector.
std::vector< Real > getObjectiveStatistic (void) const
std::vector< Real > getConstraintStatistic (const int index=0) const
void reset (void)
void checkSolutionVector (Vector< Real > &x, Vector< Real > &y, Vector< Real > &u, std::ostream &outStream=std::cout)
void checkSolutionVector (OptimizationProblemCheckData< Real > &data, Vector< Real > &x, Vector< Real > &y, Vector< Real > &u, std::ostream &outStream=std::cout)
void checkObjective (Vector< Real > &x, Vector< Real > &u, Vector< Real > &v, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
void checkObjective (OptimizationProblemCheckData< Real > &data, Vector< Real > &x, Vector< Real > &u, Vector< Real > &v, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
void checkMultiplierVector (Vector< Real > &w, Vector< Real > &q, Vector< Real > &l, std::ostream &outStream=std::cout)
void checkMultiplierVector (OptimizationProblemCheckData< Real > &data, Vector< Real > &w, Vector< Real > &q, Vector< Real > &l, std::ostream &outStream=std::cout)
void checkConstraint (Vector< Real > &x, Vector< Real > &u, Vector< Real > &v, Vector< Real > &c, Vector< Real > &l, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
void checkConstraint (OptimizationProblemCheckData< Real > &data, Vector< Real > &x, Vector< Real > &u, Vector< Real > &v, Vector< Real > &c, Vector< Real > &l, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
void check (std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
void check (OptimizationProblemCheckData< Real > &data, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Private Member Functions
void initialize (const Ptr< Objective< Real > > &obj, const Ptr< Vector< Real > > &x, const Ptr< BoundConstraint< Real > > &bnd, const std::vector< Ptr< Constraint< Real > > > &econ, const std::vector< Ptr< Vector< Real > > > &emul, const std::vector< Ptr< Constraint< Real > > > &icon, const std::vector< Ptr< Vector< Real > > > &imul, const std::vector< Ptr< BoundConstraint< Real > > > &ibnd)
const Ptr< Constraint< Real > > setRiskLessCon (const Ptr< Constraint< Real > > &con, const bool needRiskLess) const
const Ptr< Objective< Real > > setRiskLessObj (const Ptr< Objective< Real > > &obj, const bool needRiskLess) const
std::vector< Real > computeSampleMean (const Ptr< SampleGenerator< Real > > &sampler) const
void initStochastic (void)
void buildRiskVec (Ptr< Vector< Real > > &x)
void buildRiskBnd (Ptr< BoundConstraint< Real > > &bnd)
Private Attributes
Ptr< Objective< Real > > INPUT_obj_
Ptr< Vector< Real > > INPUT_sol_
Ptr< BoundConstraint< Real > > INPUT_bnd_
std::vector< Ptr< Constraint< Real > > > INPUT_econ_
std::vector< Ptr< Vector< Real > > > INPUT_emul_
std::vector< Ptr< Constraint< Real > > > INPUT_icon_
std::vector< Ptr< Vector< Real > > > INPUT_imul_
std::vector< Ptr< BoundConstraint< Real > > > INPUT_ibnd_
Ptr< Objective< Real > > INTERMEDIATE_obj_
Ptr< Vector< Real > > INTERMEDIATE_sol_
Ptr< BoundConstraint< Real > > INTERMEDIATE_bnd_
std::vector< Ptr< Constraint< Real > > > INTERMEDIATE_econ_
std::vector< Ptr< Vector< Real > > > INTERMEDIATE_emul_
std::vector< Ptr< Constraint< Real > > > INTERMEDIATE_icon_
std::vector< Ptr< Vector< Real > > > INTERMEDIATE_imul_
std::vector< Ptr< BoundConstraint< Real > > > INTERMEDIATE_ibnd_
Ptr< SampleGenerator< Real > > vsampler_
Ptr< SampleGenerator< Real > > gsampler_
Ptr< SampleGenerator< Real > > hsampler_
std::vector< Ptr< SampleGenerator< Real > > > exsampler_
std::vector< Ptr< BatchManager< Real > > > ecbman_
std::vector< Ptr< SampleGenerator< Real > > > ixsampler_
std::vector< Ptr< BatchManager< Real > > > icbman_
Ptr< ParameterList > parlistObj_
std::vector< Ptr< ParameterList > > parlistCon_
Ptr< Objective< Real > > obj_
Ptr< Vector< Real > > sol_
Ptr< BoundConstraint< Real > > bnd_
Ptr< Constraint< Real > > con_
Ptr< Vector< Real > > mul_
Ptr< ConstraintManager< Real > > conManager_
EProblem problemType_
bool isInitialized_
bool needRiskLessObj_
std::vector< bool > needRiskLessEcon_
std::vector< bool > needRiskLessIcon_
bool isStochastic_
Detailed Description
template<class Real>
class ROL::OptimizationProblem< Real >
Definition at line 54 of file ROL_OptimizationProblem.hpp.
Constructor & Destructor Documentation
~OptimizationProblem()
template<class Real > virtual ROL::OptimizationProblem< Real >::~OptimizationProblem (void) inline virtual
Definition at line 259 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [1/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (void) inline
Definition at line 262 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [2/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const std::vector< Ptr< Constraint< Real > > > & econ, const std::vector< Ptr< Vector< Real > > > & emul, const std::vector< Ptr< Constraint< Real > > > & icon, const std::vector< Ptr< Vector< Real > > > & imul, const std::vector< Ptr< BoundConstraint< Real > > > & ibnd) inline
Definition at line 266 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [3/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul, const std::vector< Ptr< Constraint< Real > > > & icon, const std::vector< Ptr< Vector< Real > > > & imul, const std::vector< Ptr< BoundConstraint< Real > > > & ibnd) inline
Definition at line 282 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INPUT_econ_, ROL::OptimizationProblem< Real >::INPUT_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_.
OptimizationProblem() [4/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const std::vector< Ptr< Constraint< Real > > > & econ, const std::vector< Ptr< Vector< Real > > > & emul, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd) inline
Definition at line 303 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INPUT_ibnd_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INPUT_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_.
OptimizationProblem() [5/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd) inline
Definition at line 327 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INPUT_econ_, ROL::OptimizationProblem< Real >::INPUT_emul_, ROL::OptimizationProblem< Real >::INPUT_ibnd_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INPUT_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_.
OptimizationProblem() [6/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const std::vector< Ptr< Constraint< Real > > > & econ, const std::vector< Ptr< Vector< Real > > > & emul, const std::vector< Ptr< Constraint< Real > > > & icon, const std::vector< Ptr< Vector< Real > > > & imul, const std::vector< Ptr< BoundConstraint< Real > > > & ibnd) inline
Definition at line 356 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [7/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul, const std::vector< Ptr< Constraint< Real > > > & icon, const std::vector< Ptr< Vector< Real > > > & imul, const std::vector< Ptr< BoundConstraint< Real > > > & ibnd) inline
Definition at line 365 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [8/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const std::vector< Ptr< Constraint< Real > > > & econ, const std::vector< Ptr< Vector< Real > > > & emul, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd) inline
Definition at line 374 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [9/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd) inline
Definition at line 383 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [10/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const std::vector< Ptr< Constraint< Real > > > & econ, const std::vector< Ptr< Vector< Real > > > & emul) inline
Definition at line 393 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [11/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul) inline
Definition at line 400 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [12/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const std::vector< Ptr< Constraint< Real > > > & icon, const std::vector< Ptr< Vector< Real > > > & imul, const std::vector< Ptr< BoundConstraint< Real > > > & ibnd) inline
Definition at line 408 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [13/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd) inline
Definition at line 416 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [14/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const std::vector< Ptr< Constraint< Real > > > & econ, const std::vector< Ptr< Vector< Real > > > & emul) inline
Definition at line 425 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [15/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< Constraint< Real > > & econ, const Ptr< Vector< Real > > & emul) inline
Definition at line 431 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [16/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const std::vector< Ptr< Constraint< Real > > > & icon, const std::vector< Ptr< Vector< Real > > > & imul, const std::vector< Ptr< BoundConstraint< Real > > > & ibnd) inline
Definition at line 438 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [17/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< Constraint< Real > > & icon, const Ptr< Vector< Real > > & imul, const Ptr< BoundConstraint< Real > > & ibnd) inline
Definition at line 445 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [18/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd) inline
Definition at line 453 of file ROL_OptimizationProblem.hpp.
OptimizationProblem() [19/19]
template<class Real > ROL::OptimizationProblem< Real >::OptimizationProblem (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x) inline
Definition at line 459 of file ROL_OptimizationProblem.hpp.
Member Function Documentation
initialize()
template<class Real > void ROL::OptimizationProblem< Real >::initialize (const Ptr< Objective< Real > > & obj, const Ptr< Vector< Real > > & x, const Ptr< BoundConstraint< Real > > & bnd, const std::vector< Ptr< Constraint< Real > > > & econ, const std::vector< Ptr< Vector< Real > > > & emul, const std::vector< Ptr< Constraint< Real > > > & icon, const std::vector< Ptr< Vector< Real > > > & imul, const std::vector< Ptr< BoundConstraint< Real > > > & ibnd) inline private
Definition at line 102 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::bnd_, ROL::OptimizationProblem< Real >::con_, ROL::OptimizationProblem< Real >::conManager_, ROL::OptimizationProblem< Real >::isInitialized_, ROL::OptimizationProblem< Real >::isStochastic_, ROL::OptimizationProblem< Real >::mul_, ROL::OptimizationProblem< Real >::needRiskLessEcon_, ROL::OptimizationProblem< Real >::needRiskLessIcon_, ROL::OptimizationProblem< Real >::needRiskLessObj_, ROL::OptimizationProblem< Real >::obj_, ROL::OptimizationProblem< Real >::problemType_, ROL::OptimizationProblem< Real >::setRiskLessCon(), ROL::OptimizationProblem< Real >::setRiskLessObj(), ROL::OptimizationProblem< Real >::sol_, ROL::TYPE_B, ROL::TYPE_E, ROL::TYPE_EB, and ROL::TYPE_U.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionVector(), and ROL::OptimizationProblem< Real >::reset().
setRiskLessCon()
template<class Real > const Ptr< Constraint< Real > > ROL::OptimizationProblem< Real >::setRiskLessCon (const Ptr< Constraint< Real > > & con, const bool needRiskLess) const inline private
Definition at line 180 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize().
setRiskLessObj()
template<class Real > const Ptr< Objective< Real > > ROL::OptimizationProblem< Real >::setRiskLessObj (const Ptr< Objective< Real > > & obj, const bool needRiskLess) const inline private
Definition at line 189 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize().
computeSampleMean()
template<class Real > std::vector< Real > ROL::OptimizationProblem< Real >::computeSampleMean (const Ptr< SampleGenerator< Real > > & sampler) const inline private
Definition at line 198 of file ROL_OptimizationProblem.hpp.
References dim.
Referenced by ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), and ROL::OptimizationProblem< Real >::setMeanValueObjective().
initStochastic()
template<class Real > void ROL::OptimizationProblem< Real >::initStochastic (void) inline private
Definition at line 214 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::ecbman_, ROL::OptimizationProblem< Real >::exsampler_, ROL::OptimizationProblem< Real >::icbman_, ROL::OptimizationProblem< Real >::INPUT_econ_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::isStochastic_, ROL::OptimizationProblem< Real >::ixsampler_, ROL::OptimizationProblem< Real >::needRiskLessEcon_, ROL::OptimizationProblem< Real >::needRiskLessIcon_, ROL::OptimizationProblem< Real >::needRiskLessObj_, ROL::OptimizationProblem< Real >::parlistCon_, and ROL::OptimizationProblem< Real >::parlistObj_.
Referenced by ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralObjective(), ROL::OptimizationProblem< Real >::setStochasticEquality(), and ROL::OptimizationProblem< Real >::setStochasticInequality().
buildRiskVec()
template<class Real > void ROL::OptimizationProblem< Real >::buildRiskVec (Ptr< Vector< Real > > & x) inline private
Definition at line 234 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, ROL::OptimizationProblem< Real >::parlistCon_, and ROL::OptimizationProblem< Real >::parlistObj_.
Referenced by ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralObjective(), ROL::OptimizationProblem< Real >::setStochasticEquality(), ROL::OptimizationProblem< Real >::setStochasticInequality(), and ROL::OptimizationProblem< Real >::setStochasticObjective().
buildRiskBnd()
template<class Real > void ROL::OptimizationProblem< Real >::buildRiskBnd (Ptr< BoundConstraint< Real > > & bnd) inline private
Definition at line 251 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::parlistCon_, and ROL::OptimizationProblem< Real >::parlistObj_.
Referenced by ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralObjective(), ROL::OptimizationProblem< Real >::setStochasticEquality(), ROL::OptimizationProblem< Real >::setStochasticInequality(), and ROL::OptimizationProblem< Real >::setStochasticObjective().
getObjective()
template<class Real > virtual Ptr< Objective< Real > > ROL::OptimizationProblem< Real >::getObjective (void) inline virtual
Definition at line 465 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, and ROL::OptimizationProblem< Real >::obj_.
Referenced by main(), and ROL::OptimizationSolver< Real >::OptimizationSolver().
getSolutionVector()
template<class Real > virtual Ptr< Vector< Real > > ROL::OptimizationProblem< Real >::getSolutionVector (void) inline virtual
Definition at line 475 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, and ROL::OptimizationProblem< Real >::sol_.
Referenced by main(), and ROL::OptimizationSolver< Real >::OptimizationSolver().
getBoundConstraint()
template<class Real > virtual Ptr< BoundConstraint< Real > > ROL::OptimizationProblem< Real >::getBoundConstraint (void) inline virtual
Definition at line 485 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::bnd_, ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
Referenced by main(), and ROL::OptimizationSolver< Real >::OptimizationSolver().
getConstraint()
template<class Real > virtual Ptr< Constraint< Real > > ROL::OptimizationProblem< Real >::getConstraint (void) inline virtual
Definition at line 492 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::con_, ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
Referenced by main(), and ROL::OptimizationSolver< Real >::OptimizationSolver().
getMultiplierVector()
template<class Real > virtual Ptr< Vector< Real > > ROL::OptimizationProblem< Real >::getMultiplierVector (void) inline virtual
Definition at line 499 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, and ROL::OptimizationProblem< Real >::mul_.
Referenced by main(), and ROL::OptimizationSolver< Real >::OptimizationSolver().
getProblemType()
template<class Real > EProblem ROL::OptimizationProblem< Real >::getProblemType (void) inline
Definition at line 506 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, and ROL::OptimizationProblem< Real >::problemType_.
Referenced by ROL::OptimizationSolver< Real >::OptimizationSolver().
setMeanValueObjective()
template<class Real > void ROL::OptimizationProblem< Real >::setMeanValueObjective (const Ptr< SampleGenerator< Real > > & sampler) inline
Set objective function to mean value objective.
We assume the objective function is parametrized by an additional variable (other than the optimization variable). This variable could, e.g., be random. The mean value objective function evaluates the the parametrized objective function at the sample average of the auxiliary variable.
Parameters
[in] sampler is the SampleGenerator defining the distribution of the auxiliary parameter
Definition at line 526 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::computeSampleMean(), ROL::OptimizationProblem< Real >::gsampler_, ROL::OptimizationProblem< Real >::hsampler_, ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_obj_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::isInitialized_, and ROL::OptimizationProblem< Real >::vsampler_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticObjective().
setRiskNeutralObjective()
template<class Real > void ROL::OptimizationProblem< Real >::setRiskNeutralObjective (const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler = nullPtr, const Ptr< SampleGenerator< Real > > & hsampler = nullPtr, const bool storage = true) inline
Set objective function to risk neutral objective.
We assume the objective function is parametrized by an additional variable (other than the optimization variable). This variable could, e.g., be random. The risk neutral objective function evaluates the the average of parametrized objective function.
Parameters
[in] vsampler is the SampleGenerator defining the distribution of the auxiliary parameter for the value
[in] gsampler is the SampleGenerator defining the distribution of the auxiliary parameter for the gradient
[in] hsampler is the SampleGenerator defining the distribution of the auxiliary parameter for the Hessian
[in] storage whether or not to store the sampled value and gradient
Definition at line 560 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::gsampler_, ROL::OptimizationProblem< Real >::hsampler_, ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_obj_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::isInitialized_, and ROL::OptimizationProblem< Real >::vsampler_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticObjective().
setRiskAverseObjective()
template<class Real > void ROL::OptimizationProblem< Real >::setRiskAverseObjective (ParameterList & parlist, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler = nullPtr, const Ptr< SampleGenerator< Real > > & hsampler = nullPtr) inline
Set objective function to risk averse objective.
We assume the objective function is parametrized by an additional variable (other than the optimization variable). This variable could, e.g., be random. The risk averse objective function evaluates the the `‘risk’' of parametrized objective function.
Parameters
[in] parlist contains the information defining the risk measure
[in] vsampler is the SampleGenerator defining the distribution of the auxiliary parameter for the value
[in] gsampler is the SampleGenerator defining the distribution of the auxiliary parameter for the gradient
[in] hsampler is the SampleGenerator defining the distribution of the auxiliary parameter for the Hessian
Definition at line 602 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::gsampler_, ROL::OptimizationProblem< Real >::hsampler_, ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_obj_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::isInitialized_, ROL::OptimizationProblem< Real >::needRiskLessObj_, ROL::OptimizationProblem< Real >::parlistObj_, and ROL::OptimizationProblem< Real >::vsampler_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticObjective().
setStochasticObjective()
template<class Real > void ROL::OptimizationProblem< Real >::setStochasticObjective (ParameterList & parlist, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler = nullPtr, const Ptr< SampleGenerator< Real > > & hsampler = nullPtr) inline
Definition at line 634 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::isInitialized_, ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), and ROL::OptimizationProblem< Real >::setRiskNeutralObjective().
Referenced by main().
setMeanValueEquality()
template<class Real > void ROL::OptimizationProblem< Real >::setMeanValueEquality (const Ptr< SampleGenerator< Real > > & sampler, const int index = 0) inline
Definition at line 665 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::computeSampleMean(), ROL::OptimizationProblem< Real >::exsampler_, ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_econ_, ROL::OptimizationProblem< Real >::INPUT_emul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, and ROL::OptimizationProblem< Real >::isInitialized_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticEquality().
setRiskNeutralEquality()
template<class Real > void ROL::OptimizationProblem< Real >::setRiskNeutralEquality (const Ptr< SampleGenerator< Real > > & xsampler, const Ptr< BatchManager< Real > > & cbman, const int index = 0) inline
Definition at line 684 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::ecbman_, ROL::OptimizationProblem< Real >::exsampler_, ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_econ_, ROL::OptimizationProblem< Real >::INPUT_emul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, and ROL::OptimizationProblem< Real >::isInitialized_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticEquality().
setAlmostSureEquality()
template<class Real > void ROL::OptimizationProblem< Real >::setAlmostSureEquality (const Ptr< SampleGenerator< Real > > & sampler, const int index = 0) inline
Definition at line 707 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::exsampler_, ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_econ_, ROL::OptimizationProblem< Real >::INPUT_emul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, and ROL::OptimizationProblem< Real >::isInitialized_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticEquality().
setStochasticEquality() [1/2]
template<class Real > void ROL::OptimizationProblem< Real >::setStochasticEquality (std::vector< ParameterList > & parlist, const std::vector< Ptr< SampleGenerator< Real > > > & xsampler, const std::vector< Ptr< BatchManager< Real > > > & cbman) inline
Definition at line 734 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_econ_, ROL::OptimizationProblem< Real >::INPUT_emul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::isInitialized_, ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), and ROL::OptimizationProblem< Real >::setRiskNeutralEquality().
Referenced by ROL::OptimizationProblem< Real >::setStochasticEquality().
setStochasticEquality() [2/2]
template<class Real > void ROL::OptimizationProblem< Real >::setStochasticEquality (ParameterList & parlist, const Ptr< SampleGenerator< Real > > & xsampler, const Ptr< BatchManager< Real > > & cbman) inline
Definition at line 770 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::setStochasticEquality().
setMeanValueInequality()
template<class Real > void ROL::OptimizationProblem< Real >::setMeanValueInequality (const Ptr< SampleGenerator< Real > > & sampler, const int index = 0) inline
Definition at line 780 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::computeSampleMean(), ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_ibnd_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INPUT_imul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::isInitialized_, and ROL::OptimizationProblem< Real >::ixsampler_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticInequality().
setRiskNeutralInequality()
template<class Real > void ROL::OptimizationProblem< Real >::setRiskNeutralInequality (const Ptr< SampleGenerator< Real > > & xsampler, const Ptr< BatchManager< Real > > & cbman, const int index = 0) inline
Definition at line 801 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::icbman_, ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_ibnd_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INPUT_imul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::isInitialized_, and ROL::OptimizationProblem< Real >::ixsampler_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticInequality().
setRiskAverseInequality()
template<class Real > void ROL::OptimizationProblem< Real >::setRiskAverseInequality (ParameterList & parlist, const Ptr< SampleGenerator< Real > > & sampler, const int index = 0) inline
Definition at line 825 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_ibnd_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INPUT_imul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::isInitialized_, ROL::OptimizationProblem< Real >::ixsampler_, ROL::OptimizationProblem< Real >::needRiskLessIcon_, and ROL::OptimizationProblem< Real >::parlistCon_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticInequality().
setAlmostSureInequality()
template<class Real > void ROL::OptimizationProblem< Real >::setAlmostSureInequality (const Ptr< SampleGenerator< Real > > & sampler, const int index = 0) inline
Definition at line 848 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_ibnd_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INPUT_imul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::isInitialized_, and ROL::OptimizationProblem< Real >::ixsampler_.
Referenced by ROL::OptimizationProblem< Real >::setStochasticInequality().
setStochasticInequality() [1/2]
template<class Real > void ROL::OptimizationProblem< Real >::setStochasticInequality (std::vector< ParameterList > & parlist, const std::vector< Ptr< SampleGenerator< Real > > > & xsampler, const std::vector< Ptr< BatchManager< Real > > > & cbman) inline
Definition at line 876 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::INPUT_bnd_, ROL::OptimizationProblem< Real >::INPUT_ibnd_, ROL::OptimizationProblem< Real >::INPUT_icon_, ROL::OptimizationProblem< Real >::INPUT_imul_, ROL::OptimizationProblem< Real >::INPUT_sol_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::isInitialized_, ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), and ROL::OptimizationProblem< Real >::setRiskNeutralInequality().
Referenced by ROL::OptimizationProblem< Real >::setStochasticInequality().
setStochasticInequality() [2/2]
template<class Real > void ROL::OptimizationProblem< Real >::setStochasticInequality (ParameterList & parlist, const Ptr< SampleGenerator< Real > > & xsampler, const Ptr< BatchManager< Real > > & cbman) inline
Definition at line 920 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::setStochasticInequality().
getSolutionStatistic()
template<class Real > Real ROL::OptimizationProblem< Real >::getSolutionStatistic (int comp = 0, int index = 0) inline
Returns the statistic from the soluton vector.
Parameters
[in] comp is the component of the risk vector (0 for objective, 1 for inequality constraint)
[in] index is the inequality constraint index
Definition at line 934 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
Referenced by main().
getObjectiveStatistic()
template<class Real > std::vector< Real > ROL::OptimizationProblem< Real >::getObjectiveStatistic (void) const inline
Definition at line 962 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
getConstraintStatistic()
template<class Real > std::vector< Real > ROL::OptimizationProblem< Real >::getConstraintStatistic (const int index = 0) const inline
Definition at line 980 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
reset()
template<class Real > void ROL::OptimizationProblem< Real >::reset (void) inline
Definition at line 998 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::conManager_, ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
checkSolutionVector() [1/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkSolutionVector (Vector< Real > & x, Vector< Real > & y, Vector< Real > & u, std::ostream & outStream = std::cout) inline
Definition at line 1006 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::checkSolutionVector().
Referenced by ROL::OptimizationProblem< Real >::check(), and ROL::OptimizationProblem< Real >::checkSolutionVector().
checkSolutionVector() [2/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkSolutionVector (OptimizationProblemCheckData< Real > & data, Vector< Real > & x, Vector< Real > & y, Vector< Real > & u, std::ostream & outStream = std::cout) inline
Definition at line 1015 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblemCheckData< Real >::checkSolutionVector, ROL::Vector< Real >::checkVector(), ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, and ROL::OptimizationProblem< Real >::obj_.
checkObjective() [1/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkObjective (Vector< Real > & x, Vector< Real > & u, Vector< Real > & v, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1031 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::checkObjective().
Referenced by ROL::OptimizationProblem< Real >::check(), and ROL::OptimizationProblem< Real >::checkObjective().
checkObjective() [2/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkObjective (OptimizationProblemCheckData< Real > & data, Vector< Real > & x, Vector< Real > & u, Vector< Real > & v, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1041 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblemCheckData< Real >::checkGradient, ROL::OptimizationProblemCheckData< Real >::checkHessSym, ROL::OptimizationProblemCheckData< Real >::checkHessVec, ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, and ROL::OptimizationProblem< Real >::obj_.
checkMultiplierVector() [1/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkMultiplierVector (Vector< Real > & w, Vector< Real > & q, Vector< Real > & l, std::ostream & outStream = std::cout) inline
Definition at line 1064 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::checkMultiplierVector().
Referenced by ROL::OptimizationProblem< Real >::check(), and ROL::OptimizationProblem< Real >::checkMultiplierVector().
checkMultiplierVector() [2/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkMultiplierVector (OptimizationProblemCheckData< Real > & data, Vector< Real > & w, Vector< Real > & q, Vector< Real > & l, std::ostream & outStream = std::cout) inline
Definition at line 1072 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblemCheckData< Real >::checkMultiplierVector, ROL::Vector< Real >::checkVector(), ROL::OptimizationProblem< Real >::con_, ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
checkConstraint() [1/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkConstraint (Vector< Real > & x, Vector< Real > & u, Vector< Real > & v, Vector< Real > & c, Vector< Real > & l, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1088 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::checkConstraint().
Referenced by ROL::OptimizationProblem< Real >::check(), and ROL::OptimizationProblem< Real >::checkConstraint().
checkConstraint() [2/2]
template<class Real > void ROL::OptimizationProblem< Real >::checkConstraint (OptimizationProblemCheckData< Real > & data, Vector< Real > & x, Vector< Real > & u, Vector< Real > & v, Vector< Real > & c, Vector< Real > & l, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1100 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblemCheckData< Real >::checkAdjointConsistencyJacobian, ROL::OptimizationProblemCheckData< Real >::checkApplyAdjointHessian, ROL::OptimizationProblemCheckData< Real >::checkApplyJacobian, ROL::OptimizationProblem< Real >::con_, ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, and ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_.
check() [1/2]
template<class Real > void ROL::OptimizationProblem< Real >::check (std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1126 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::check().
Referenced by ROL::OptimizationProblem< Real >::check(), main(), and ROL::SROMGenerator< Real >::SROMGenerator().
check() [2/2]
template<class Real > void ROL::OptimizationProblem< Real >::check (OptimizationProblemCheckData< Real > & data, std::ostream & outStream = std::cout, const int numSteps = ROL_NUM_CHECKDERIV_STEPS, const int order = 1) inline
Definition at line 1133 of file ROL_OptimizationProblem.hpp.
References ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::con_, ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_, ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_, ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_, ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_, ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_, ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_, ROL::OptimizationProblem< Real >::mul_, and ROL::OptimizationProblem< Real >::sol_.
Member Data Documentation
INPUT_obj_
template<class Real > Ptr<Objective<Real> > ROL::OptimizationProblem< Real >::INPUT_obj_ private
Definition at line 56 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), and ROL::OptimizationProblem< Real >::setRiskNeutralObjective().
INPUT_sol_
template<class Real > Ptr<Vector<Real> > ROL::OptimizationProblem< Real >::INPUT_sol_ private
Definition at line 57 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralObjective(), ROL::OptimizationProblem< Real >::setStochasticEquality(), ROL::OptimizationProblem< Real >::setStochasticInequality(), and ROL::OptimizationProblem< Real >::setStochasticObjective().
INPUT_bnd_
template<class Real > Ptr<BoundConstraint<Real> > ROL::OptimizationProblem< Real >::INPUT_bnd_ private
Definition at line 58 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralObjective(), ROL::OptimizationProblem< Real >::setStochasticEquality(), ROL::OptimizationProblem< Real >::setStochasticInequality(), and ROL::OptimizationProblem< Real >::setStochasticObjective().
INPUT_econ_
template<class Real > std::vector<Ptr<Constraint<Real> > > ROL::OptimizationProblem< Real >::INPUT_econ_ private
Definition at line 59 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), and ROL::OptimizationProblem< Real >::setStochasticEquality().
INPUT_emul_
template<class Real > std::vector<Ptr<Vector<Real> > > ROL::OptimizationProblem< Real >::INPUT_emul_ private
Definition at line 60 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), and ROL::OptimizationProblem< Real >::setStochasticEquality().
INPUT_icon_
template<class Real > std::vector<Ptr<Constraint<Real> > > ROL::OptimizationProblem< Real >::INPUT_icon_ private
Definition at line 61 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), and ROL::OptimizationProblem< Real >::setStochasticInequality().
INPUT_imul_
template<class Real > std::vector<Ptr<Vector<Real> > > ROL::OptimizationProblem< Real >::INPUT_imul_ private
Definition at line 62 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), and ROL::OptimizationProblem< Real >::setStochasticInequality().
INPUT_ibnd_
template<class Real > std::vector<Ptr<BoundConstraint<Real> > > ROL::OptimizationProblem< Real >::INPUT_ibnd_ private
Definition at line 63 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), and ROL::OptimizationProblem< Real >::setStochasticInequality().
INTERMEDIATE_obj_
template<class Real > Ptr<Objective<Real> > ROL::OptimizationProblem< Real >::INTERMEDIATE_obj_ private
Definition at line 65 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionStatistic(), ROL::OptimizationProblem< Real >::getSolutionVector(), ROL::OptimizationProblem< Real >::reset(), ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), and ROL::OptimizationProblem< Real >::setRiskNeutralObjective().
INTERMEDIATE_sol_
template<class Real > Ptr<Vector<Real> > ROL::OptimizationProblem< Real >::INTERMEDIATE_sol_ private
Definition at line 66 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getConstraintStatistic(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getObjectiveStatistic(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionStatistic(), ROL::OptimizationProblem< Real >::getSolutionVector(), and ROL::OptimizationProblem< Real >::reset().
INTERMEDIATE_bnd_
template<class Real > Ptr<BoundConstraint<Real> > ROL::OptimizationProblem< Real >::INTERMEDIATE_bnd_ private
Definition at line 67 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionVector(), and ROL::OptimizationProblem< Real >::reset().
INTERMEDIATE_econ_
template<class Real > std::vector<Ptr<Constraint<Real> > > ROL::OptimizationProblem< Real >::INTERMEDIATE_econ_ private
Definition at line 68 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionVector(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::reset(), ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), and ROL::OptimizationProblem< Real >::setStochasticEquality().
INTERMEDIATE_emul_
template<class Real > std::vector<Ptr<Vector<Real> > > ROL::OptimizationProblem< Real >::INTERMEDIATE_emul_ private
Definition at line 69 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionVector(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::reset(), ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), and ROL::OptimizationProblem< Real >::setStochasticEquality().
INTERMEDIATE_icon_
template<class Real > std::vector<Ptr<Constraint<Real> > > ROL::OptimizationProblem< Real >::INTERMEDIATE_icon_ private
Definition at line 70 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionStatistic(), ROL::OptimizationProblem< Real >::getSolutionVector(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::reset(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), and ROL::OptimizationProblem< Real >::setStochasticInequality().
INTERMEDIATE_imul_
template<class Real > std::vector<Ptr<Vector<Real> > > ROL::OptimizationProblem< Real >::INTERMEDIATE_imul_ private
Definition at line 71 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionVector(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::reset(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), and ROL::OptimizationProblem< Real >::setStochasticInequality().
INTERMEDIATE_ibnd_
template<class Real > std::vector<Ptr<BoundConstraint<Real> > > ROL::OptimizationProblem< Real >::INTERMEDIATE_ibnd_ private
Definition at line 72 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getBoundConstraint(), ROL::OptimizationProblem< Real >::getConstraint(), ROL::OptimizationProblem< Real >::getMultiplierVector(), ROL::OptimizationProblem< Real >::getObjective(), ROL::OptimizationProblem< Real >::getProblemType(), ROL::OptimizationProblem< Real >::getSolutionVector(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::OptimizationProblem(), ROL::OptimizationProblem< Real >::reset(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), and ROL::OptimizationProblem< Real >::setStochasticInequality().
vsampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::OptimizationProblem< Real >::vsampler_ private
Definition at line 74 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), and ROL::OptimizationProblem< Real >::setRiskNeutralObjective().
gsampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::OptimizationProblem< Real >::gsampler_ private
Definition at line 75 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), and ROL::OptimizationProblem< Real >::setRiskNeutralObjective().
hsampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::OptimizationProblem< Real >::hsampler_ private
Definition at line 76 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), and ROL::OptimizationProblem< Real >::setRiskNeutralObjective().
exsampler_
template<class Real > std::vector<Ptr<SampleGenerator<Real> > > ROL::OptimizationProblem< Real >::exsampler_ private
Definition at line 77 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), and ROL::OptimizationProblem< Real >::setRiskNeutralEquality().
ecbman_
template<class Real > std::vector<Ptr<BatchManager<Real> > > ROL::OptimizationProblem< Real >::ecbman_ private
Definition at line 78 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initStochastic(), and ROL::OptimizationProblem< Real >::setRiskNeutralEquality().
ixsampler_
template<class Real > std::vector<Ptr<SampleGenerator<Real> > > ROL::OptimizationProblem< Real >::ixsampler_ private
Definition at line 79 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initStochastic(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), and ROL::OptimizationProblem< Real >::setRiskNeutralInequality().
icbman_
template<class Real > std::vector<Ptr<BatchManager<Real> > > ROL::OptimizationProblem< Real >::icbman_ private
Definition at line 80 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initStochastic(), and ROL::OptimizationProblem< Real >::setRiskNeutralInequality().
parlistObj_
template<class Real > Ptr<ParameterList> ROL::OptimizationProblem< Real >::parlistObj_ private
Definition at line 82 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::initStochastic(), and ROL::OptimizationProblem< Real >::setRiskAverseObjective().
parlistCon_
template<class Real > std::vector<Ptr<ParameterList> > ROL::OptimizationProblem< Real >::parlistCon_ private
Definition at line 83 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::buildRiskBnd(), ROL::OptimizationProblem< Real >::buildRiskVec(), ROL::OptimizationProblem< Real >::initStochastic(), and ROL::OptimizationProblem< Real >::setRiskAverseInequality().
obj_
template<class Real > Ptr<Objective<Real> > ROL::OptimizationProblem< Real >::obj_ private
Definition at line 85 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::checkObjective(), ROL::OptimizationProblem< Real >::checkSolutionVector(), ROL::OptimizationProblem< Real >::getObjective(), and ROL::OptimizationProblem< Real >::initialize().
sol_
template<class Real > Ptr<Vector<Real> > ROL::OptimizationProblem< Real >::sol_ private
Definition at line 86 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::getSolutionVector(), and ROL::OptimizationProblem< Real >::initialize().
bnd_
template<class Real > Ptr<BoundConstraint<Real> > ROL::OptimizationProblem< Real >::bnd_ private
Definition at line 87 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::getBoundConstraint(), and ROL::OptimizationProblem< Real >::initialize().
con_
template<class Real > Ptr<Constraint<Real> > ROL::OptimizationProblem< Real >::con_ private
Definition at line 88 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::checkConstraint(), ROL::OptimizationProblem< Real >::checkMultiplierVector(), ROL::OptimizationProblem< Real >::getConstraint(), and ROL::OptimizationProblem< Real >::initialize().
mul_
template<class Real > Ptr<Vector<Real> > ROL::OptimizationProblem< Real >::mul_ private
Definition at line 89 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::check(), ROL::OptimizationProblem< Real >::getMultiplierVector(), and ROL::OptimizationProblem< Real >::initialize().
conManager_
template<class Real > Ptr<ConstraintManager<Real> > ROL::OptimizationProblem< Real >::conManager_ private
Definition at line 91 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize(), and ROL::OptimizationProblem< Real >::reset().
problemType_
template<class Real > EProblem ROL::OptimizationProblem< Real >::problemType_ private
Definition at line 93 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::getProblemType(), and ROL::OptimizationProblem< Real >::initialize().
isInitialized_
template<class Real > bool ROL::OptimizationProblem< Real >::isInitialized_ private
Definition at line 95 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::setAlmostSureEquality(), ROL::OptimizationProblem< Real >::setAlmostSureInequality(), ROL::OptimizationProblem< Real >::setMeanValueEquality(), ROL::OptimizationProblem< Real >::setMeanValueInequality(), ROL::OptimizationProblem< Real >::setMeanValueObjective(), ROL::OptimizationProblem< Real >::setRiskAverseInequality(), ROL::OptimizationProblem< Real >::setRiskAverseObjective(), ROL::OptimizationProblem< Real >::setRiskNeutralEquality(), ROL::OptimizationProblem< Real >::setRiskNeutralInequality(), ROL::OptimizationProblem< Real >::setRiskNeutralObjective(), ROL::OptimizationProblem< Real >::setStochasticEquality(), ROL::OptimizationProblem< Real >::setStochasticInequality(), and ROL::OptimizationProblem< Real >::setStochasticObjective().
needRiskLessObj_
template<class Real > bool ROL::OptimizationProblem< Real >::needRiskLessObj_ private
Definition at line 97 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::initStochastic(), and ROL::OptimizationProblem< Real >::setRiskAverseObjective().
needRiskLessEcon_
template<class Real > std::vector<bool> ROL::OptimizationProblem< Real >::needRiskLessEcon_ private
Definition at line 98 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize(), and ROL::OptimizationProblem< Real >::initStochastic().
needRiskLessIcon_
template<class Real > std::vector<bool> ROL::OptimizationProblem< Real >::needRiskLessIcon_ private
Definition at line 99 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize(), ROL::OptimizationProblem< Real >::initStochastic(), and ROL::OptimizationProblem< Real >::setRiskAverseInequality().
isStochastic_
template<class Real > bool ROL::OptimizationProblem< Real >::isStochastic_ private
Definition at line 100 of file ROL_OptimizationProblem.hpp.
Referenced by ROL::OptimizationProblem< Real >::initialize(), and ROL::OptimizationProblem< Real >::initStochastic().
The documentation for this class was generated from the following file:
ROL_OptimizationProblem.hpp