ROL: ROL::TypeB::GradientAlgorithm< Real > Class Template Reference
ROL::TypeB::GradientAlgorithm< Real > Class Template Reference
Provides an interface to run the projected gradient algorithm.
#include <ROL_TypeB_GradientAlgorithm.hpp>
Public Member Functions
GradientAlgorithm (ParameterList &list)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Private Attributes
int maxit_
Real alpha0_
Real alpha0bnd_
Real rhodec_
Real rhoinc_
Real c1_
Real maxAlpha_
bool useralpha_
bool usePrevAlpha_
bool useAdapt_
bool normAlpha_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::GradientAlgorithm< Real >
Provides an interface to run the projected gradient algorithm.
Definition at line 23 of file ROL_TypeB_GradientAlgorithm.hpp.
Constructor & Destructor Documentation
GradientAlgorithm()
template<typename Real > ROL::TypeB::GradientAlgorithm< Real >::GradientAlgorithm (ParameterList & list)
Definition at line 17 of file ROL_TypeB_GradientAlgorithm_Def.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::GradientAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) private
Definition at line 40 of file ROL_TypeB_GradientAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeB::Algorithm< Real >::initialize(), ROL::Revert, ROL::Trial, ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeB::GradientAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 92 of file ROL_TypeB_GradientAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Revert, ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeB::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeB::GradientAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 232 of file ROL_TypeB_GradientAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeB::GradientAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 261 of file ROL_TypeB_GradientAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::GradientAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 268 of file ROL_TypeB_GradientAlgorithm_Def.hpp.
Member Data Documentation
maxit_
template<typename Real > int ROL::TypeB::GradientAlgorithm< Real >::maxit_ private
Definition at line 25 of file ROL_TypeB_GradientAlgorithm.hpp.
alpha0_
template<typename Real > Real ROL::TypeB::GradientAlgorithm< Real >::alpha0_ private
Definition at line 26 of file ROL_TypeB_GradientAlgorithm.hpp.
alpha0bnd_
template<typename Real > Real ROL::TypeB::GradientAlgorithm< Real >::alpha0bnd_ private
Definition at line 26 of file ROL_TypeB_GradientAlgorithm.hpp.
rhodec_
template<typename Real > Real ROL::TypeB::GradientAlgorithm< Real >::rhodec_ private
Definition at line 26 of file ROL_TypeB_GradientAlgorithm.hpp.
rhoinc_
template<typename Real > Real ROL::TypeB::GradientAlgorithm< Real >::rhoinc_ private
Definition at line 26 of file ROL_TypeB_GradientAlgorithm.hpp.
c1_
template<typename Real > Real ROL::TypeB::GradientAlgorithm< Real >::c1_ private
Definition at line 26 of file ROL_TypeB_GradientAlgorithm.hpp.
maxAlpha_
template<typename Real > Real ROL::TypeB::GradientAlgorithm< Real >::maxAlpha_ private
Definition at line 26 of file ROL_TypeB_GradientAlgorithm.hpp.
useralpha_
template<typename Real > bool ROL::TypeB::GradientAlgorithm< Real >::useralpha_ private
Definition at line 27 of file ROL_TypeB_GradientAlgorithm.hpp.
usePrevAlpha_
template<typename Real > bool ROL::TypeB::GradientAlgorithm< Real >::usePrevAlpha_ private
Definition at line 27 of file ROL_TypeB_GradientAlgorithm.hpp.
useAdapt_
template<typename Real > bool ROL::TypeB::GradientAlgorithm< Real >::useAdapt_ private
Definition at line 27 of file ROL_TypeB_GradientAlgorithm.hpp.
normAlpha_
template<typename Real > bool ROL::TypeB::GradientAlgorithm< Real >::normAlpha_ private
Definition at line 27 of file ROL_TypeB_GradientAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeB::GradientAlgorithm< Real >::verbosity_ private
Definition at line 28 of file ROL_TypeB_GradientAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeB::GradientAlgorithm< Real >::writeHeader_ private
Definition at line 29 of file ROL_TypeB_GradientAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_GradientAlgorithm.hpp
ROL_TypeB_GradientAlgorithm_Def.hpp