ROL: TestMulti< Real > Class Template Reference
TestMulti< Real > Class Template Reference
Public Member Functions
TestMulti ()
Real value_x (const ROL::Vector< Real > &x) const
Real value_y (const ROL::Vector< Real > &y) const
Real value_z (const ROL::Vector< Real > &z) const
Private Attributes
ROL::VectorCloneMap< Real > clones_
Detailed Description
template<typename Real>
class TestMulti< Real >
Definition at line 44 of file vector/test_09.cpp.
Constructor & Destructor Documentation
TestMulti()
template<typename Real > TestMulti< Real >::TestMulti () inline
Definition at line 48 of file vector/test_09.cpp.
Member Function Documentation
value_x()
template<typename Real > Real TestMulti< Real >::value_x (const ROL::Vector< Real > & x) const inline
Definition at line 50 of file vector/test_09.cpp.
References TestMulti< Real >::clones_.
Referenced by main().
value_y()
template<typename Real > Real TestMulti< Real >::value_y (const ROL::Vector< Real > & y) const inline
Definition at line 56 of file vector/test_09.cpp.
References TestMulti< Real >::clones_.
Referenced by main().
value_z()
template<typename Real > Real TestMulti< Real >::value_z (const ROL::Vector< Real > & z) const inline
Definition at line 62 of file vector/test_09.cpp.
References TestMulti< Real >::clones_.
Referenced by main().
Member Data Documentation
clones_
template<typename Real > ROL::VectorCloneMap<Real> TestMulti< Real >::clones_ mutable private
Definition at line 46 of file vector/test_09.cpp.
Referenced by TestMulti< Real >::value_x(), TestMulti< Real >::value_y(), and TestMulti< Real >::value_z().
The documentation for this class was generated from the following file:
vector/test_09.cpp