ROL: OptStdVector< Real, Element > Class Template Reference
OptStdVector< Real, Element > Class Template Reference
#include <example_02.hpp>
Public Member Functions
OptStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
OptStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
void applyUnary (const ROL::Elementwise::UnaryFunction< Real > &f)
void applyBinary (const ROL::Elementwise::BinaryFunction< Real > &f, const ROL::Vector< Real > &x)
Real reduce (const ROL::Elementwise::ReductionOp< Real > &r) const
OptStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
OptStdVector (const ROL::Ptr< std::vector< Element > > &std_vec, ROL::Ptr< FiniteDifference< Real > >fd)
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const Vector< Real > &x) const
Modify the dot product between primal variables to be \((u,v)=\int\limits_0^1 \dot u \dot v\,\mathrm{d}x \).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const vector > getVector () const
ROL::Ptr< vector > getVector ()
ROL::Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const Vector< Real > & dual () const
Modify the dual of vector u to be \(\tilde u = -\ddot u\).
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void axpy (const Real alpha, const Vector &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
virtual void zero ()
Set to zero vector.
virtual void set (const Vector &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
virtual void applyUnary (const Elementwise::UnaryFunction< Real > &f)
virtual void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector &x)
virtual Real reduce (const Elementwise::ReductionOp< Real > &r) const
virtual void print (std::ostream &outStream) const
virtual void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
virtual void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef vector::size_type uint
Private Attributes
ROL::Ptr< std::vector< Element > > std_vec_
ROL::Ptr< OptDualStdVector< Real > > dual_vec_
ROL::Ptr< FiniteDifference< Real > > fd_
Detailed Description
template<class Real, class Element>
class OptStdVector< Real, Element >
Definition at line 83 of file gross-pitaevskii/example_02.hpp.
Member Typedef Documentation
vector [1/4]
template<class Real , class Element > typedef std::vector<Element> OptStdVector< Real, Element >::vector private
Definition at line 42 of file dual-spaces/rosenbrock-1/example_01.cpp.
V [1/3]
template<class Real , class Element > typedef ROL::Vector<Real> OptStdVector< Real, Element >::V private
Definition at line 43 of file dual-spaces/rosenbrock-1/example_01.cpp.
uint [1/4]
template<class Real , class Element > typedef vector::size_type OptStdVector< Real, Element >::uint private
Definition at line 45 of file dual-spaces/rosenbrock-1/example_01.cpp.
vector [2/4]
template<class Real , class Element > typedef std::vector<Element> OptStdVector< Real, Element >::vector private
Definition at line 43 of file dual-spaces/rosenbrock-1/example_02.cpp.
V [2/3]
template<class Real , class Element > typedef ROL::Vector<Real> OptStdVector< Real, Element >::V private
Definition at line 44 of file dual-spaces/rosenbrock-1/example_02.cpp.
uint [2/4]
template<class Real , class Element > typedef vector::size_type OptStdVector< Real, Element >::uint private
Definition at line 46 of file dual-spaces/rosenbrock-1/example_02.cpp.
vector [3/4]
template<class Real , class Element > typedef std::vector<Element> OptStdVector< Real, Element >::vector private
Definition at line 47 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
V [3/3]
template<class Real , class Element > typedef ROL::Vector<Real> OptStdVector< Real, Element >::V private
Definition at line 48 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
uint [3/4]
template<class Real , class Element > typedef vector::size_type OptStdVector< Real, Element >::uint private
Definition at line 49 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
vector [4/4]
template<class Real , class Element > typedef std::vector<Element> OptStdVector< Real, Element >::vector private
Definition at line 85 of file gross-pitaevskii/example_02.hpp.
uint [4/4]
template<class Real , class Element > typedef vector::size_type OptStdVector< Real, Element >::uint private
Definition at line 86 of file gross-pitaevskii/example_02.hpp.
Constructor & Destructor Documentation
OptStdVector() [1/4]
template<class Real , class Element > OptStdVector< Real, Element >::OptStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 53 of file dual-spaces/rosenbrock-1/example_01.cpp.
OptStdVector() [2/4]
template<class Real , class Element > OptStdVector< Real, Element >::OptStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 54 of file dual-spaces/rosenbrock-1/example_02.cpp.
OptStdVector() [3/4]
template<class Real , class Element > OptStdVector< Real, Element >::OptStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 57 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
OptStdVector() [4/4]
template<class Real , class Element > OptStdVector< Real, Element >::OptStdVector (const ROL::Ptr< std::vector< Element > > & std_vec, ROL::Ptr< FiniteDifference< Real > > fd) inline
Definition at line 97 of file gross-pitaevskii/example_02.hpp.
Member Function Documentation
plus() [1/4]
template<class Real , class Element > void OptStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 55 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
scale() [1/4]
template<class Real , class Element > void OptStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 64 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), and OptStdVector< Real, Element >::std_vec_.
dot() [1/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 71 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
Referenced by OptStdVector< Real, Element >::norm().
norm() [1/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 82 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::dot().
clone() [1/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 88 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
getVector() [1/8]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > OptStdVector< Real, Element >::getVector () const inline
Definition at line 92 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
Referenced by OptStdVector< Real, Element >::apply(), OptStdVector< Real, Element >::applyBinary(), OptStdVector< Real, Element >::dot(), OptStdVector< Real, Element >::dot(), OptStdVector< Real, Element >::plus(), and OptStdVector< Real, Element >::plus().
getVector() [2/8]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptStdVector< Real, Element >::getVector () inline
Definition at line 96 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
basis() [1/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 100 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
dimension() [1/4]
template<class Real , class Element > int OptStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 110 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
Referenced by OptStdVector< Real, Element >::apply(), OptStdVector< Real, Element >::dot(), OptStdVector< Real, Element >::dot(), OptStdVector< Real, Element >::plus(), OptStdVector< Real, Element >::plus(), and OptStdVector< Real, Element >::scale().
dual() [1/4]
template<class Real , class Element > const ROL::Vector< Real > & OptStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 112 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::dual_vec_.
apply() [1/3]
template<class Real , class Element > Real OptStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 117 of file dual-spaces/rosenbrock-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
Referenced by OptStdVector< Real, Element >::applyBinary().
plus() [2/4]
template<class Real , class Element > void OptStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 56 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
scale() [2/4]
template<class Real , class Element > void OptStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 65 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::dimension(), and OptStdVector< Real, Element >::std_vec_.
dot() [2/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 72 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
norm() [2/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 83 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::dot().
clone() [2/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 89 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::std_vec_.
getVector() [3/8]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > OptStdVector< Real, Element >::getVector () const inline
Definition at line 93 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::std_vec_.
getVector() [4/8]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptStdVector< Real, Element >::getVector () inline
Definition at line 97 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::std_vec_.
basis() [2/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 101 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::std_vec_.
dimension() [2/4]
template<class Real , class Element > int OptStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 111 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::std_vec_.
dual() [2/4]
template<class Real , class Element > const ROL::Vector< Real > & OptStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 113 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::dual_vec_.
apply() [2/3]
template<class Real , class Element > Real OptStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 118 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
applyUnary()
template<class Real , class Element > void OptStdVector< Real, Element >::applyUnary (const ROL::Elementwise::UnaryFunction< Real > & f) inline
Definition at line 129 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::std_vec_.
applyBinary()
template<class Real , class Element > void OptStdVector< Real, Element >::applyBinary (const ROL::Elementwise::BinaryFunction< Real > & f, const ROL::Vector< Real > & x) inline
Definition at line 133 of file dual-spaces/rosenbrock-1/example_02.cpp.
References OptStdVector< Real, Element >::apply(), dim, OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
reduce()
template<class Real , class Element > Real OptStdVector< Real, Element >::reduce (const ROL::Elementwise::ReductionOp< Real > & r) const inline
Definition at line 141 of file dual-spaces/rosenbrock-1/example_02.cpp.
References dim, and OptStdVector< Real, Element >::std_vec_.
plus() [3/4]
template<class Real , class Element > void OptStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 59 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
scale() [3/4]
template<class Real , class Element > void OptStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 70 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), and OptStdVector< Real, Element >::std_vec_.
dot() [3/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 77 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
norm() [3/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 91 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::dot().
clone() [3/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 97 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
getVector() [5/8]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > OptStdVector< Real, Element >::getVector () const inline
Definition at line 101 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
getVector() [6/8]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptStdVector< Real, Element >::getVector () inline
Definition at line 105 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
basis() [3/4]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > OptStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 109 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
dimension() [3/4]
template<class Real , class Element > int OptStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 117 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::std_vec_.
dual() [3/4]
template<class Real , class Element > const ROL::Vector< Real > & OptStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 119 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::dual_vec_.
apply() [3/3]
template<class Real , class Element > Real OptStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 124 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
plus() [4/4]
template<class Real , class Element > void OptStdVector< Real, Element >::plus (const Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 100 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
scale() [4/4]
template<class Real , class Element > void OptStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 109 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::dimension(), and OptStdVector< Real, Element >::std_vec_.
dot() [4/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::dot (const Vector< Real > & x) const inline virtual
Modify the dot product between primal variables to be \((u,v)=\int\limits_0^1 \dot u \dot v\,\mathrm{d}x \).
Implements ROL::Vector< Real >.
Definition at line 118 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::fd_, OptStdVector< Real, Element >::getVector(), and OptStdVector< Real, Element >::std_vec_.
norm() [4/4]
template<class Real , class Element > Real OptStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 134 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::dot().
clone() [4/4]
template<class Real , class Element > ROL::Ptr< Vector< Real > > OptStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 140 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::fd_, and OptStdVector< Real, Element >::std_vec_.
getVector() [7/8]
template<class Real , class Element > ROL::Ptr< const vector > OptStdVector< Real, Element >::getVector () const inline
Definition at line 144 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::std_vec_.
getVector() [8/8]
template<class Real , class Element > ROL::Ptr< vector > OptStdVector< Real, Element >::getVector () inline
Definition at line 148 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::std_vec_.
basis() [4/4]
template<class Real , class Element > ROL::Ptr< Vector< Real > > OptStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 152 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::fd_, and OptStdVector< Real, Element >::std_vec_.
dimension() [4/4]
template<class Real , class Element > int OptStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 159 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::std_vec_.
dual() [4/4]
template<class Real , class Element > const Vector< Real > & OptStdVector< Real, Element >::dual (void) const inline virtual
Modify the dual of vector u to be \(\tilde u = -\ddot u\).
Reimplemented from ROL::Vector< Real >.
Definition at line 163 of file gross-pitaevskii/example_02.hpp.
References OptStdVector< Real, Element >::dual_vec_, OptStdVector< Real, Element >::fd_, and OptStdVector< Real, Element >::std_vec_.
Member Data Documentation
std_vec_
template<class Real , class Element > ROL::Ptr< std::vector< Element > > OptStdVector< Real, Element >::std_vec_ private
Definition at line 48 of file dual-spaces/rosenbrock-1/example_01.cpp.
Referenced by OptStdVector< Real, Element >::apply(), OptStdVector< Real, Element >::applyBinary(), OptStdVector< Real, Element >::applyUnary(), OptStdVector< Real, Element >::basis(), OptStdVector< Real, Element >::clone(), OptStdVector< Real, Element >::dimension(), OptStdVector< Real, Element >::dot(), OptStdVector< Real, Element >::dot(), OptStdVector< Real, Element >::dual(), OptStdVector< Real, Element >::getVector(), OptStdVector< Real, Element >::getVector(), OptStdVector< Real, Element >::plus(), OptStdVector< Real, Element >::plus(), OptStdVector< Real, Element >::reduce(), and OptStdVector< Real, Element >::scale().
dual_vec_
template<class Real , class Element > ROL::Ptr< OptDualStdVector< Real > > OptStdVector< Real, Element >::dual_vec_ mutable private
Definition at line 49 of file dual-spaces/rosenbrock-1/example_01.cpp.
Referenced by OptStdVector< Real, Element >::dual().
fd_
template<class Real , class Element > ROL::Ptr<FiniteDifference<Real> > OptStdVector< Real, Element >::fd_ private
Definition at line 92 of file gross-pitaevskii/example_02.hpp.
Referenced by OptStdVector< Real, Element >::basis(), OptStdVector< Real, Element >::clone(), OptStdVector< Real, Element >::dot(), and OptStdVector< Real, Element >::dual().
The documentation for this class was generated from the following files:
dual-spaces/rosenbrock-1/example_01.cpp
dual-spaces/rosenbrock-1/example_02.cpp
dual-spaces/simple-eq-constr-1/example_01.cpp
gross-pitaevskii/example_02.hpp