ROL: ROL::MeanSemiDeviationFromTarget< Real > Class Template Reference
ROL::MeanSemiDeviationFromTarget< Real > Class Template Reference
#include <ROL_MeanSemiDeviationFromTarget.hpp>
Public Member Functions
MeanSemiDeviationFromTarget (const Real coeff, const Real target, const Ptr< PlusFunction< Real > > &pf)
Constructor.
MeanSemiDeviationFromTarget (ROL::ParameterList &parlist)
Constructor.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void initialize (const Vector< Real > &x)
Initialize temporary variables.
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Member Functions
void checkInputs (void) const
Private Attributes
Ptr< PlusFunction< Real > > plusFunction_
Real coeff_
Real target_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::MeanSemiDeviationFromTarget< Real >
Definition at line 37 of file ROL_MeanSemiDeviationFromTarget.hpp.
Constructor & Destructor Documentation
MeanSemiDeviationFromTarget() [1/2]
template<class Real > ROL::MeanSemiDeviationFromTarget< Real >::MeanSemiDeviationFromTarget (const Real coeff, const Real target, const Ptr< PlusFunction< Real > > & pf) inline
Constructor.
Parameters
[in] coeff is the coefficient scaling the semideviation
[in] target is the target scalar
[in] pf is the plus function or an approximation
Definition at line 72 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::MeanSemiDeviationFromTarget< Real >::checkInputs().
MeanSemiDeviationFromTarget() [2/2]
template<class Real > ROL::MeanSemiDeviationFromTarget< Real >::MeanSemiDeviationFromTarget (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measure"->"Mean Plus Semi-Deviation" and within the "Mean Plus Semi-Deviation" sublist should have the following parameters
"Coefficient" (between 0 and 1)
"Target"
A sublist for plus function information.
Definition at line 88 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::MeanSemiDeviationFromTarget< Real >::checkInputs(), ROL::MeanSemiDeviationFromTarget< Real >::coeff_, ROL::MeanSemiDeviationFromTarget< Real >::plusFunction_, and ROL::MeanSemiDeviationFromTarget< Real >::target_.
Member Function Documentation
checkInputs()
template<class Real > void ROL::MeanSemiDeviationFromTarget< Real >::checkInputs (void) const inline private
Definition at line 56 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::MeanSemiDeviationFromTarget< Real >::coeff_, ROL::MeanSemiDeviationFromTarget< Real >::plusFunction_, and zero.
Referenced by ROL::MeanSemiDeviationFromTarget< Real >::MeanSemiDeviationFromTarget(), and ROL::MeanSemiDeviationFromTarget< Real >::MeanSemiDeviationFromTarget().
updateValue()
template<class Real > void ROL::MeanSemiDeviationFromTarget< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 101 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::MeanSemiDeviationFromTarget< Real >::coeff_, ROL::RandVarFunctional< Real >::computeValue(), ROL::MeanSemiDeviationFromTarget< Real >::plusFunction_, ROL::MeanSemiDeviationFromTarget< Real >::target_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::MeanSemiDeviationFromTarget< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 110 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
updateGradient()
template<class Real > void ROL::MeanSemiDeviationFromTarget< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 118 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::MeanSemiDeviationFromTarget< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::MeanSemiDeviationFromTarget< Real >::plusFunction_, ROL::MeanSemiDeviationFromTarget< Real >::target_, and ROL::RandVarFunctional< Real >::weight_.
getGradient()
template<class Real > void ROL::MeanSemiDeviationFromTarget< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 129 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::RandVarFunctional< Real >::g_, and ROL::SampleGenerator< Real >::sumAll().
updateHessVec()
template<class Real > void ROL::MeanSemiDeviationFromTarget< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 137 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::MeanSemiDeviationFromTarget< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::hv_, ROL::MeanSemiDeviationFromTarget< Real >::plusFunction_, ROL::MeanSemiDeviationFromTarget< Real >::target_, and ROL::RandVarFunctional< Real >::weight_.
getHessVec()
template<class Real > void ROL::MeanSemiDeviationFromTarget< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 153 of file ROL_MeanSemiDeviationFromTarget.hpp.
References ROL::RandVarFunctional< Real >::hv_, and ROL::SampleGenerator< Real >::sumAll().
Member Data Documentation
plusFunction_
template<class Real > Ptr<PlusFunction<Real> > ROL::MeanSemiDeviationFromTarget< Real >::plusFunction_ private
Definition at line 39 of file ROL_MeanSemiDeviationFromTarget.hpp.
Referenced by ROL::MeanSemiDeviationFromTarget< Real >::checkInputs(), ROL::MeanSemiDeviationFromTarget< Real >::MeanSemiDeviationFromTarget(), ROL::MeanSemiDeviationFromTarget< Real >::updateGradient(), ROL::MeanSemiDeviationFromTarget< Real >::updateHessVec(), and ROL::MeanSemiDeviationFromTarget< Real >::updateValue().
coeff_
template<class Real > Real ROL::MeanSemiDeviationFromTarget< Real >::coeff_ private
Definition at line 40 of file ROL_MeanSemiDeviationFromTarget.hpp.
Referenced by ROL::MeanSemiDeviationFromTarget< Real >::checkInputs(), ROL::MeanSemiDeviationFromTarget< Real >::MeanSemiDeviationFromTarget(), ROL::MeanSemiDeviationFromTarget< Real >::updateGradient(), ROL::MeanSemiDeviationFromTarget< Real >::updateHessVec(), and ROL::MeanSemiDeviationFromTarget< Real >::updateValue().
target_
template<class Real > Real ROL::MeanSemiDeviationFromTarget< Real >::target_ private
Definition at line 40 of file ROL_MeanSemiDeviationFromTarget.hpp.
Referenced by ROL::MeanSemiDeviationFromTarget< Real >::MeanSemiDeviationFromTarget(), ROL::MeanSemiDeviationFromTarget< Real >::updateGradient(), ROL::MeanSemiDeviationFromTarget< Real >::updateHessVec(), and ROL::MeanSemiDeviationFromTarget< Real >::updateValue().
The documentation for this class was generated from the following file:
ROL_MeanSemiDeviationFromTarget.hpp