ROL: ROL::ScalarLinearConstraint< Real > Class Template Reference
ROL::ScalarLinearConstraint< Real > Class Template Reference
User Interface » Functional Interface
This equality constraint defines an affine hyperplane.
#include <ROL_ScalarLinearConstraint.hpp>
Public Member Functions
ScalarLinearConstraint (const Ptr< const Vector< Real > > &a, const Real b)
void value (Vector< Real > &c, const Vector< Real > &x, Real &tol) override
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void applyAdjointHessian (Vector< Real > &ahuv, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol) override
Approximately solves the augmented system
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update constraint function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
const Ptr< const Vector< Real > > a_
Dual vector defining hyperplane.
const Real b_
Affine shift.
Additional Inherited Members
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::ScalarLinearConstraint< Real >
This equality constraint defines an affine hyperplane.
ROL's scalar linear equality constraint interface implements
\[ c(x) := \langle a, x\rangle_{\mathcal{X}^*,\mathcal{X}} - b = 0 \]
where \(a\in\mathcal{X}^*\) and \(b\in\mathbb{R}\). The range space of \(c\) is an ROL::SingletonVector with dimension 1.
Note: If \(a\neq 0\) then there exists an explicit solution of the augmented system. Namely,
\[ v_1 = I^{-1}(b_1-av_2) \quad\text{and}\quad v_2 = \frac{(\langle a,I^{-1}b_1\rangle_{\mathcal{X}^*,\mathcal{X}} - b_2)}{\|a\|_{\mathcal{X}^*}^2}\,. \]
Moreover, note that \(I^{-1}v\) for any \(v\in\mathcal{X}^*\) is implemented in ROL as v.dual().
Definition at line 46 of file ROL_ScalarLinearConstraint.hpp.
Constructor & Destructor Documentation
ScalarLinearConstraint()
template<typename Real > ROL::ScalarLinearConstraint< Real >::ScalarLinearConstraint (const Ptr< const Vector< Real > > & a, const Real b)
Definition at line 16 of file ROL_ScalarLinearConstraint_Def.hpp.
Member Function Documentation
value()
template<typename Real > void ROL::ScalarLinearConstraint< Real >::value (Vector< Real > & c, const Vector< Real > & x, Real & tol) override virtual
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
Parameters
[out] c is the result of evaluating the constraint operator at x; a constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(x)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{x} \in \mathcal{X}\).
Implements ROL::Constraint< Real >.
Definition at line 21 of file ROL_ScalarLinearConstraint_Def.hpp.
References ROL::SingletonVector< Real >::setValue().
applyJacobian()
template<typename Real > void ROL::ScalarLinearConstraint< Real >::applyJacobian (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at x; a constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c'(x)v\), where \(v \in \mathcal{X}\), \(\mathsf{jv} \in \mathcal{C}\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 28 of file ROL_ScalarLinearConstraint_Def.hpp.
References ROL::SingletonVector< Real >::setValue().
applyAdjointJacobian()
template<typename Real > void ROL::ScalarLinearConstraint< Real >::applyAdjointJacobian (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at x; a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c'(x)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 37 of file ROL_ScalarLinearConstraint_Def.hpp.
References ROL::SingletonVector< Real >::getValue(), ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
applyAdjointHessian()
template<typename Real > void ROL::ScalarLinearConstraint< Real >::applyAdjointHessian (Vector< Real > & ahuv, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
Parameters
[out] ahuv is the result of applying the derivative of the adjoint of the constraint Jacobian at x to vector u in direction v; a dual optimization-space vector
[in] u is the direction vector; a dual constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahuv} = c''(x)(v,\cdot)^*u \), where \(u \in \mathcal{C}^*\), \(v \in \mathcal{X}\), and \(\mathsf{ahuv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation based on the adjoint Jacobian.
Reimplemented from ROL::Constraint< Real >.
Definition at line 46 of file ROL_ScalarLinearConstraint_Def.hpp.
References ROL::Vector< Real >::zero().
solveAugmentedSystem()
template<typename Real > std::vector< Real > ROL::ScalarLinearConstraint< Real >::solveAugmentedSystem (Vector< Real > & v1, Vector< Real > & v2, const Vector< Real > & b1, const Vector< Real > & b2, const Vector< Real > & x, Real & tol) override virtual
Approximately solves the augmented system
\[ \begin{pmatrix} I & c'(x)^* \\ c'(x) & 0 \end{pmatrix} \begin{pmatrix} v_{1} \\ v_{2} \end{pmatrix} = \begin{pmatrix} b_{1} \\ b_{2} \end{pmatrix} \]
where \(v_{1} \in \mathcal{X}\), \(v_{2} \in \mathcal{C}^*\), \(b_{1} \in \mathcal{X}^*\), \(b_{2} \in \mathcal{C}\), \(I : \mathcal{X} \rightarrow \mathcal{X}^*\) is an identity or Riesz operator, and \(0 : \mathcal{C}^* \rightarrow \mathcal{C}\) is a zero operator.
Parameters
[out] v1 is the optimization-space component of the result
[out] v2 is the dual constraint-space component of the result
[in] b1 is the dual optimization-space component of the right-hand side
[in] b2 is the constraint-space component of the right-hand side
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is the nominal relative residual tolerance
On return, \([\mathsf{v1} \,\, \mathsf{v2}] \) approximately solves the augmented system, where the size of the residual is governed by special stopping conditions.
The default implementation is the preconditioned generalized minimal residual (GMRES) method, which enables the use of nonsymmetric preconditioners.
Reimplemented from ROL::Constraint< Real >.
Definition at line 54 of file ROL_ScalarLinearConstraint_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dual(), ROL::SingletonVector< Real >::getValue(), ROL::Vector< Real >::set(), and ROL::SingletonVector< Real >::setValue().
Member Data Documentation
a_
template<typename Real > const Ptr<const Vector<Real> > ROL::ScalarLinearConstraint< Real >::a_ private
Dual vector defining hyperplane.
Definition at line 48 of file ROL_ScalarLinearConstraint.hpp.
b_
template<typename Real > const Real ROL::ScalarLinearConstraint< Real >::b_ private
Affine shift.
Definition at line 49 of file ROL_ScalarLinearConstraint.hpp.
The documentation for this class was generated from the following files:
ROL_ScalarLinearConstraint.hpp
ROL_ScalarLinearConstraint_Def.hpp