ROL: ROL::TypeB::TrustRegionSPGAlgorithm< Real > Class Template Reference
ROL::TypeB::TrustRegionSPGAlgorithm< Real > Class Template Reference
Provides an interface to run the trust-region algorithm.
#include <ROL_TypeB_TrustRegionSPGAlgorithm.hpp>
Public Member Functions
TrustRegionSPGAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Real ftol, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Real computeValue (Real inTol, Real &outTol, Real pRed, Real &fold, int iter, const Vector< Real > &x, const Vector< Real > &xold, Objective< Real > &obj)
void computeGradient (const Vector< Real > &x, Vector< Real > &g, Vector< Real > &pwa, Real del, Objective< Real > &obj, bool accept, Real &gtol, Real &gnorm, std::ostream &outStream=std::cout) const
Real dgpstep (Vector< Real > &s, const Vector< Real > &w, const Vector< Real > &x, const Real alpha, std::ostream &outStream=std::cout) const
Real dcauchy (Vector< Real > &s, Real &alpha, Real &q, const Vector< Real > &x, const Vector< Real > &g, const Real del, TrustRegionModel_U< Real > &model, Vector< Real > &dwa, Vector< Real > &dwa1, std::ostream &outStream=std::cout)
void dpsg_simple (Vector< Real > &y, Real &q, Vector< Real > &gmod, const Vector< Real > &x, Real del, TrustRegionModel_U< Real > &model, Vector< Real > &pwa, Vector< Real > &pwa1, Vector< Real > &dwa, std::ostream &outStream=std::cout)
void dpsg (Vector< Real > &y, Real &q, Vector< Real > &gmod, const Vector< Real > &x, Real del, TrustRegionModel_U< Real > &model, Vector< Real > &ymin, Vector< Real > &pwa, Vector< Real > &pwa1, Vector< Real > &pwa2, Vector< Real > &pwa3, Vector< Real > &pwa4, Vector< Real > &pwa5, Vector< Real > &dwa, std::ostream &outStream=std::cout)
void dproj (Vector< Real > &x, const Vector< Real > &x0, Real del, Vector< Real > &y0, Vector< Real > &y1, Vector< Real > &yc, Vector< Real > &pwa, std::ostream &outStream=std::cout) const
Private Attributes
Ptr< TrustRegionModel_U< Real > > model_
Container for trust-region model.
Real delMax_
Maximum trust-region radius (default: ROL_INF)
Real eta0_
Step acceptance threshold (default: 0.05)
Real eta1_
Radius decrease threshold (default: 0.05)
Real eta2_
Radius increase threshold (default: 0.9)
Real gamma0_
Radius decrease rate (negative rho) (default: 0.0625)
Real gamma1_
Radius decrease rate (positive rho) (default: 0.25)
Real gamma2_
Radius increase rate (default: 2.5)
Real TRsafe_
Safeguard size for numerically evaluating ratio (default: 1e2)
Real eps_
Safeguard for numerically evaluating ratio.
bool interpRad_
Interpolate the trust-region radius if ratio is negative (default: false)
TRUtils::ETRFlag TRflag_
Trust-region exit flag.
int SPflag_
Subproblem solver termination flag.
int SPiter_
Subproblem solver iteration count.
ESecant esec_
Secant type (default: Limited-Memory BFGS)
bool useSecantPrecond_
Flag to use secant as a preconditioner (default: false)
bool useSecantHessVec_
Flag to use secant as Hessian (default: false)
Real tol1_
Absolute tolerance for truncated CG (default: 1e-4)
Real tol2_
Relative tolerance for truncated CG (default: 1e-2)
int maxit_
Maximum number of CG iterations (default: 25)
bool useNM_
int storageNM_
Real mu0_
Sufficient decrease parameter (default: 1e-2)
Real spexp_
Relative tolerance exponent for subproblem solve (default: 1, range: [1,2])
int redlim_
Maximum number of Cauchy point reduction steps (default: 10)
int explim_
Maximum number of Cauchy point expansion steps (default: 10)
Real alpha_
Initial Cauchy point step length (default: 1.0)
bool normAlpha_
Normalize initial Cauchy point step length (default: false)
Real interpf_
Backtracking rate for Cauchy point computation (default: 1e-1)
Real extrapf_
Extrapolation rate for Cauchy point computation (default: 1e1)
Real qtol_
Relative tolerance for computed decrease in Cauchy point computation (default: 1-8)
Real lambdaMin_
Real lambdaMax_
Real gamma_
int maxSize_
bool useMin_
bool useNMSP_
bool useSimpleSPG_
std::vector< bool > useInexact_
Real scale0_
Real scale1_
Real scale_
Real omega_
Real force_
int updateIter_
Real forceFactor_
Real gtol_
int nhess_
Number of Hessian applications.
unsigned verbosity_
Output level (default: 0)
bool writeHeader_
Flag to write header at every iteration.
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::TrustRegionSPGAlgorithm< Real >
Provides an interface to run the trust-region algorithm.
Definition at line 25 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
Constructor & Destructor Documentation
TrustRegionSPGAlgorithm()
template<typename Real > ROL::TypeB::TrustRegionSPGAlgorithm< Real >::TrustRegionSPGAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 19 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::SECANTMODE_BOTH, ROL::SECANTMODE_FORWARD, ROL::SECANTMODE_INVERSE, and ROL::StringToESecant().
Member Function Documentation
run()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 191 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::TRUtils::NPOSPREDNEG, ROL::Vector< Real >::plus(), ROL::TRUtils::POSPREDNEG, ROL::Revert, ROL::Vector< Real >::set(), ROL::TRUtils::SUCCESS, ROL::TRUtils::TRNAN, ROL::Objective< Real >::update(), ROL::TypeB::Algorithm< Real >::writeExitStatus(), and zero.
writeHeader()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 890 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::TRUtils::ETRFlagToString(), ROL::NumberToString(), ROL::TRUtils::SUCCESS, and ROL::TRUtils::UNDEFINED.
writeName()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 935 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 942 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
initialize()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Real ftol, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) private
Definition at line 102 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Initial, ROL::TypeB::Algorithm< Real >::initialize(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
computeValue()
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::computeValue (Real inTol, Real & outTol, Real pRed, Real & fold, int iter, const Vector< Real > & x, const Vector< Real > & xold, Objective< Real > & obj) private
Definition at line 137 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Trial, ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
computeGradient()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::computeGradient (const Vector< Real > & x, Vector< Real > & g, Vector< Real > & pwa, Real del, Objective< Real > & obj, bool accept, Real & gtol, Real & gnorm, std::ostream & outStream = std::cout) const private
Definition at line 160 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), and ROL::TypeB::Algorithm< Real >::optimalityCriterion().
dgpstep()
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dgpstep (Vector< Real > & s, const Vector< Real > & w, const Vector< Real > & x, const Real alpha, std::ostream & outStream = std::cout) const private
Definition at line 311 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::norm(), and ROL::Vector< Real >::set().
dcauchy()
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dcauchy (Vector< Real > & s, Real & alpha, Real & q, const Vector< Real > & x, const Vector< Real > & g, const Real del, TrustRegionModel_U< Real > & model, Vector< Real > & dwa, Vector< Real > & dwa1, std::ostream & outStream = std::cout) private
Definition at line 321 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::dot(), ROL::TrustRegionModel_U< Real >::hessVec(), and ROL::Vector< Real >::set().
dpsg_simple()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple (Vector< Real > & y, Real & q, Vector< Real > & gmod, const Vector< Real > & x, Real del, TrustRegionModel_U< Real > & model, Vector< Real > & pwa, Vector< Real > & pwa1, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 410 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), and ROL::Vector< Real >::zero().
dpsg()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg (Vector< Real > & y, Real & q, Vector< Real > & gmod, const Vector< Real > & x, Real del, TrustRegionModel_U< Real > & model, Vector< Real > & ymin, Vector< Real > & pwa, Vector< Real > & pwa1, Vector< Real > & pwa2, Vector< Real > & pwa3, Vector< Real > & pwa4, Vector< Real > & pwa5, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 509 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), and zero.
dproj()
template<typename Real > void ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dproj (Vector< Real > & x, const Vector< Real > & x0, Real del, Vector< Real > & y0, Vector< Real > & y1, Vector< Real > & yc, Vector< Real > & pwa, std::ostream & outStream = std::cout) const private
Definition at line 621 of file ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and zero.
Member Data Documentation
model_
template<typename Real > Ptr<TrustRegionModel_U<Real> > ROL::TypeB::TrustRegionSPGAlgorithm< Real >::model_ private
Container for trust-region model.
Definition at line 27 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
delMax_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::delMax_ private
Maximum trust-region radius (default: ROL_INF)
Definition at line 30 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
eta0_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::eta0_ private
Step acceptance threshold (default: 0.05)
Definition at line 31 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
eta1_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::eta1_ private
Radius decrease threshold (default: 0.05)
Definition at line 32 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
eta2_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::eta2_ private
Radius increase threshold (default: 0.9)
Definition at line 33 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
gamma0_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::gamma0_ private
Radius decrease rate (negative rho) (default: 0.0625)
Definition at line 34 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
gamma1_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::gamma1_ private
Radius decrease rate (positive rho) (default: 0.25)
Definition at line 35 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
gamma2_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::gamma2_ private
Radius increase rate (default: 2.5)
Definition at line 36 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
TRsafe_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::TRsafe_ private
Safeguard size for numerically evaluating ratio (default: 1e2)
Definition at line 37 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
eps_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::eps_ private
Safeguard for numerically evaluating ratio.
Definition at line 38 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
interpRad_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::interpRad_ private
Interpolate the trust-region radius if ratio is negative (default: false)
Definition at line 39 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
TRflag_
template<typename Real > TRUtils::ETRFlag ROL::TypeB::TrustRegionSPGAlgorithm< Real >::TRflag_ private
Trust-region exit flag.
Definition at line 42 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
SPflag_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::SPflag_ private
Subproblem solver termination flag.
Definition at line 43 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
SPiter_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::SPiter_ private
Subproblem solver iteration count.
Definition at line 44 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
esec_
template<typename Real > ESecant ROL::TypeB::TrustRegionSPGAlgorithm< Real >::esec_ private
Secant type (default: Limited-Memory BFGS)
Definition at line 47 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
useSecantPrecond_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::useSecantPrecond_ private
Flag to use secant as a preconditioner (default: false)
Definition at line 48 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
useSecantHessVec_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::useSecantHessVec_ private
Flag to use secant as Hessian (default: false)
Definition at line 49 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
tol1_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::tol1_ private
Absolute tolerance for truncated CG (default: 1e-4)
Definition at line 52 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
tol2_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::tol2_ private
Relative tolerance for truncated CG (default: 1e-2)
Definition at line 53 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
maxit_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::maxit_ private
Maximum number of CG iterations (default: 25)
Definition at line 54 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
useNM_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::useNM_ private
Definition at line 57 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
storageNM_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::storageNM_ private
Definition at line 58 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
mu0_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::mu0_ private
Sufficient decrease parameter (default: 1e-2)
Definition at line 59 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
spexp_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::spexp_ private
Relative tolerance exponent for subproblem solve (default: 1, range: [1,2])
Definition at line 60 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
redlim_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::redlim_ private
Maximum number of Cauchy point reduction steps (default: 10)
Definition at line 61 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
explim_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::explim_ private
Maximum number of Cauchy point expansion steps (default: 10)
Definition at line 62 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
alpha_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::alpha_ private
Initial Cauchy point step length (default: 1.0)
Definition at line 63 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
normAlpha_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::normAlpha_ private
Normalize initial Cauchy point step length (default: false)
Definition at line 64 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
interpf_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::interpf_ private
Backtracking rate for Cauchy point computation (default: 1e-1)
Definition at line 65 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
extrapf_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::extrapf_ private
Extrapolation rate for Cauchy point computation (default: 1e1)
Definition at line 66 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
qtol_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::qtol_ private
Relative tolerance for computed decrease in Cauchy point computation (default: 1-8)
Definition at line 67 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
lambdaMin_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::lambdaMin_ private
Definition at line 68 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
lambdaMax_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::lambdaMax_ private
Definition at line 69 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
gamma_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::gamma_ private
Definition at line 70 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
maxSize_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::maxSize_ private
Definition at line 71 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
useMin_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::useMin_ private
Definition at line 72 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
useNMSP_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::useNMSP_ private
Definition at line 73 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
useSimpleSPG_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::useSimpleSPG_ private
Definition at line 74 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
useInexact_
template<typename Real > std::vector<bool> ROL::TypeB::TrustRegionSPGAlgorithm< Real >::useInexact_ private
Definition at line 77 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
scale0_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::scale0_ private
Definition at line 78 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
scale1_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::scale1_ private
Definition at line 79 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
scale_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::scale_ private
Definition at line 80 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
omega_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::omega_ private
Definition at line 81 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
force_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::force_ private
Definition at line 82 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
updateIter_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::updateIter_ private
Definition at line 83 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
forceFactor_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::forceFactor_ private
Definition at line 84 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
gtol_
template<typename Real > Real ROL::TypeB::TrustRegionSPGAlgorithm< Real >::gtol_ private
Definition at line 85 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
nhess_
template<typename Real > int ROL::TypeB::TrustRegionSPGAlgorithm< Real >::nhess_ mutable private
Number of Hessian applications.
Definition at line 87 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
verbosity_
template<typename Real > unsigned ROL::TypeB::TrustRegionSPGAlgorithm< Real >::verbosity_ private
Output level (default: 0)
Definition at line 88 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeB::TrustRegionSPGAlgorithm< Real >::writeHeader_ private
Flag to write header at every iteration.
Definition at line 89 of file ROL_TypeB_TrustRegionSPGAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_TrustRegionSPGAlgorithm.hpp
ROL_TypeB_TrustRegionSPGAlgorithm_Def.hpp