ROL: ROL::AugmentedLagrangianObjective< Real > Class Template Reference
ROL::AugmentedLagrangianObjective< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate the augmented Lagrangian.
#include <ROL_AugmentedLagrangianObjective.hpp>
Public Member Functions
AugmentedLagrangianObjective (const Ptr< Objective< Real > > &obj, const Ptr< Constraint< Real > > &con, const Real penaltyParameter, const Vector< Real > &dualOptVec, const Vector< Real > &primConVec, const Vector< Real > &dualConVec, ParameterList &parlist)
AugmentedLagrangianObjective (const Ptr< Objective< Real > > &obj, const Ptr< Constraint< Real > > &con, const Real penaltyParameter, const Vector< Real > &dualOptVec, const Vector< Real > &primConVec, const Vector< Real > &dualConVec, const bool scaleLagrangian, const int HessianApprox)
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
void setScaling (const Real fscale=1.0, const Real cscale=1.0)
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
Real getObjectiveValue (const Vector< Real > &x, Real &tol)
const Ptr< const Vector< Real > > getObjectiveGradient (const Vector< Real > &x, Real &tol)
const Ptr< const Vector< Real > > getConstraintVec (const Vector< Real > &x, Real &tol)
int getNumberConstraintEvaluations (void) const
int getNumberFunctionEvaluations (void) const
int getNumberGradientEvaluations (void) const
void reset (const Vector< Real > &multiplier, const Real penaltyParameter)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
const Ptr< Objective< Real > > obj_
const Ptr< Constraint< Real > > con_
Real penaltyParameter_
Ptr< Vector< Real > > multiplier_
Ptr< Vector< Real > > dualOptVector_
Ptr< Vector< Real > > dualConVector_
Ptr< Vector< Real > > primConVector_
Ptr< ScalarController< Real, int > > fval_
Ptr< VectorController< Real, int > > gradient_
Ptr< VectorController< Real, int > > conValue_
Real fscale_
Real cscale_
int nfval_
int ngval_
int ncval_
bool scaleLagrangian_
int HessianApprox_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::AugmentedLagrangianObjective< Real >
Provides the interface to evaluate the augmented Lagrangian.
This class implements the augmented Lagrangian functional for use with ROL::AugmentedLagrangianAlgorithm. Given a function \(f:\mathcal{X}\to\mathbb{R}\) and an equality constraint \(c:\mathcal{X}\to\mathcal{C}\), the augmented Lagrangian functional is
\[ L_A(x,\lambda,\mu) = f(x) + \langle \lambda, c(x)\rangle_{\mathcal{C}^*,\mathcal{C}} + \frac{\mu}{2} \langle \mathfrak{R}c(x),c(x)\rangle_{\mathcal{C}^*,\mathcal{C}} \]
where \(\lambda\in\mathcal{C}^*\) denotes the Lagrange multiplier estimate, \(\mu > 0\) is the penalty parameter and \(\mathfrak{R}\in\mathcal{L}(\mathcal{C},\mathcal{C}^*)\) is the Riesz operator on the constraint space.
This implementation permits the scaling of \(L_A\) by \(\mu^{-1}\) and also permits the Hessian approximation
\[ \nabla^2_x L_A(x,\lambda,\mu)v \approx \nabla^2 f(x) v + \mu c'(x)^*\mathfrak{R} c'(x)v. \]
Definition at line 54 of file ROL_AugmentedLagrangianObjective.hpp.
Constructor & Destructor Documentation
AugmentedLagrangianObjective() [1/2]
template<class Real > ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective (const Ptr< Objective< Real > > & obj, const Ptr< Constraint< Real > > & con, const Real penaltyParameter, const Vector< Real > & dualOptVec, const Vector< Real > & primConVec, const Vector< Real > & dualConVec, ParameterList & parlist) inline
Definition at line 87 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::Vector< Real >::clone(), ROL::AugmentedLagrangianObjective< Real >::conValue_, ROL::AugmentedLagrangianObjective< Real >::dualConVector_, ROL::AugmentedLagrangianObjective< Real >::dualOptVector_, ROL::AugmentedLagrangianObjective< Real >::fval_, ROL::AugmentedLagrangianObjective< Real >::gradient_, ROL::AugmentedLagrangianObjective< Real >::HessianApprox_, ROL::AugmentedLagrangianObjective< Real >::multiplier_, ROL::AugmentedLagrangianObjective< Real >::primConVector_, and ROL::AugmentedLagrangianObjective< Real >::scaleLagrangian_.
AugmentedLagrangianObjective() [2/2]
template<class Real > ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective (const Ptr< Objective< Real > > & obj, const Ptr< Constraint< Real > > & con, const Real penaltyParameter, const Vector< Real > & dualOptVec, const Vector< Real > & primConVec, const Vector< Real > & dualConVec, const bool scaleLagrangian, const int HessianApprox) inline
Definition at line 111 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::Vector< Real >::clone(), ROL::AugmentedLagrangianObjective< Real >::conValue_, ROL::AugmentedLagrangianObjective< Real >::dualConVector_, ROL::AugmentedLagrangianObjective< Real >::dualOptVector_, ROL::AugmentedLagrangianObjective< Real >::fval_, ROL::AugmentedLagrangianObjective< Real >::gradient_, ROL::AugmentedLagrangianObjective< Real >::multiplier_, and ROL::AugmentedLagrangianObjective< Real >::primConVector_.
Member Function Documentation
update()
template<class Real > void ROL::AugmentedLagrangianObjective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 133 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::con_, ROL::AugmentedLagrangianObjective< Real >::conValue_, ROL::AugmentedLagrangianObjective< Real >::fval_, ROL::AugmentedLagrangianObjective< Real >::gradient_, and ROL::AugmentedLagrangianObjective< Real >::obj_.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize().
setScaling()
template<class Real > void ROL::AugmentedLagrangianObjective< Real >::setScaling (const Real fscale = 1.0, const Real cscale = 1.0) inline
Definition at line 141 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::cscale_, and ROL::AugmentedLagrangianObjective< Real >::fscale_.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize().
value()
template<class Real > Real ROL::AugmentedLagrangianObjective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 146 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::cscale_, ROL::AugmentedLagrangianObjective< Real >::dualConVector_, ROL::AugmentedLagrangianObjective< Real >::fscale_, ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveValue(), ROL::AugmentedLagrangianObjective< Real >::multiplier_, ROL::AugmentedLagrangianObjective< Real >::penaltyParameter_, and ROL::AugmentedLagrangianObjective< Real >::scaleLagrangian_.
gradient()
template<class Real > void ROL::AugmentedLagrangianObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 161 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::Vector< Real >::axpy(), ROL::AugmentedLagrangianObjective< Real >::con_, ROL::AugmentedLagrangianObjective< Real >::cscale_, ROL::AugmentedLagrangianObjective< Real >::dualConVector_, ROL::AugmentedLagrangianObjective< Real >::dualOptVector_, ROL::AugmentedLagrangianObjective< Real >::fscale_, ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveGradient(), ROL::AugmentedLagrangianObjective< Real >::multiplier_, ROL::AugmentedLagrangianObjective< Real >::penaltyParameter_, ROL::Vector< Real >::scale(), ROL::AugmentedLagrangianObjective< Real >::scaleLagrangian_, and ROL::Vector< Real >::set().
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run().
hessVec()
template<class Real > void ROL::AugmentedLagrangianObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 174 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::Vector< Real >::axpy(), ROL::AugmentedLagrangianObjective< Real >::con_, ROL::AugmentedLagrangianObjective< Real >::cscale_, ROL::AugmentedLagrangianObjective< Real >::dualConVector_, ROL::AugmentedLagrangianObjective< Real >::dualOptVector_, ROL::AugmentedLagrangianObjective< Real >::fscale_, ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), ROL::AugmentedLagrangianObjective< Real >::HessianApprox_, ROL::AugmentedLagrangianObjective< Real >::multiplier_, ROL::AugmentedLagrangianObjective< Real >::obj_, ROL::AugmentedLagrangianObjective< Real >::penaltyParameter_, ROL::AugmentedLagrangianObjective< Real >::primConVector_, ROL::Vector< Real >::scale(), ROL::AugmentedLagrangianObjective< Real >::scaleLagrangian_, and ROL::Vector< Real >::zero().
getObjectiveValue()
template<class Real > Real ROL::AugmentedLagrangianObjective< Real >::getObjectiveValue (const Vector< Real > & x, Real & tol) inline
Definition at line 203 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::fval_, ROL::AugmentedLagrangianObjective< Real >::nfval_, and ROL::AugmentedLagrangianObjective< Real >::obj_.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run(), and ROL::AugmentedLagrangianObjective< Real >::value().
getObjectiveGradient()
template<class Real > const Ptr< const Vector< Real > > ROL::AugmentedLagrangianObjective< Real >::getObjectiveGradient (const Vector< Real > & x, Real & tol) inline
Definition at line 215 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::dualOptVector_, ROL::AugmentedLagrangianObjective< Real >::gradient_, ROL::AugmentedLagrangianObjective< Real >::ngval_, and ROL::AugmentedLagrangianObjective< Real >::obj_.
Referenced by ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize().
getConstraintVec()
template<class Real > const Ptr< const Vector< Real > > ROL::AugmentedLagrangianObjective< Real >::getConstraintVec (const Vector< Real > & x, Real & tol) inline
Definition at line 225 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::con_, ROL::AugmentedLagrangianObjective< Real >::conValue_, ROL::AugmentedLagrangianObjective< Real >::ncval_, and ROL::AugmentedLagrangianObjective< Real >::primConVector_.
Referenced by ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run(), and ROL::AugmentedLagrangianObjective< Real >::value().
getNumberConstraintEvaluations()
template<class Real > int ROL::AugmentedLagrangianObjective< Real >::getNumberConstraintEvaluations (void) const inline
Definition at line 235 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::ncval_.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run().
getNumberFunctionEvaluations()
template<class Real > int ROL::AugmentedLagrangianObjective< Real >::getNumberFunctionEvaluations (void) const inline
Definition at line 240 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::nfval_.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run().
getNumberGradientEvaluations()
template<class Real > int ROL::AugmentedLagrangianObjective< Real >::getNumberGradientEvaluations (void) const inline
Definition at line 245 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::ngval_.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run().
reset()
template<class Real > void ROL::AugmentedLagrangianObjective< Real >::reset (const Vector< Real > & multiplier, const Real penaltyParameter) inline
Definition at line 250 of file ROL_AugmentedLagrangianObjective.hpp.
References ROL::AugmentedLagrangianObjective< Real >::multiplier_, ROL::AugmentedLagrangianObjective< Real >::ncval_, ROL::AugmentedLagrangianObjective< Real >::nfval_, ROL::AugmentedLagrangianObjective< Real >::ngval_, and ROL::AugmentedLagrangianObjective< Real >::penaltyParameter_.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), and ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run().
Member Data Documentation
obj_
template<class Real > const Ptr<Objective<Real> > ROL::AugmentedLagrangianObjective< Real >::obj_ private
Definition at line 57 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::getObjectiveGradient(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveValue(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), and ROL::AugmentedLagrangianObjective< Real >::update().
con_
template<class Real > const Ptr<Constraint<Real> > ROL::AugmentedLagrangianObjective< Real >::con_ private
Definition at line 58 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), and ROL::AugmentedLagrangianObjective< Real >::update().
penaltyParameter_
template<class Real > Real ROL::AugmentedLagrangianObjective< Real >::penaltyParameter_ private
Definition at line 60 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::AugmentedLagrangianObjective< Real >::reset(), and ROL::AugmentedLagrangianObjective< Real >::value().
multiplier_
template<class Real > Ptr<Vector<Real> > ROL::AugmentedLagrangianObjective< Real >::multiplier_ private
Definition at line 61 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::AugmentedLagrangianObjective< Real >::reset(), and ROL::AugmentedLagrangianObjective< Real >::value().
dualOptVector_
template<class Real > Ptr<Vector<Real> > ROL::AugmentedLagrangianObjective< Real >::dualOptVector_ private
Definition at line 64 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveGradient(), ROL::AugmentedLagrangianObjective< Real >::gradient(), and ROL::AugmentedLagrangianObjective< Real >::hessVec().
dualConVector_
template<class Real > Ptr<Vector<Real> > ROL::AugmentedLagrangianObjective< Real >::dualConVector_ private
Definition at line 65 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), and ROL::AugmentedLagrangianObjective< Real >::value().
primConVector_
template<class Real > Ptr<Vector<Real> > ROL::AugmentedLagrangianObjective< Real >::primConVector_ private
Definition at line 66 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), and ROL::AugmentedLagrangianObjective< Real >::hessVec().
fval_
template<class Real > Ptr<ScalarController<Real,int> > ROL::AugmentedLagrangianObjective< Real >::fval_ private
Definition at line 69 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveValue(), and ROL::AugmentedLagrangianObjective< Real >::update().
gradient_
template<class Real > Ptr<VectorController<Real,int> > ROL::AugmentedLagrangianObjective< Real >::gradient_ private
Definition at line 70 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveGradient(), and ROL::AugmentedLagrangianObjective< Real >::update().
conValue_
template<class Real > Ptr<VectorController<Real,int> > ROL::AugmentedLagrangianObjective< Real >::conValue_ private
Definition at line 71 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), and ROL::AugmentedLagrangianObjective< Real >::update().
fscale_
template<class Real > Real ROL::AugmentedLagrangianObjective< Real >::fscale_ private
Definition at line 74 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::AugmentedLagrangianObjective< Real >::setScaling(), and ROL::AugmentedLagrangianObjective< Real >::value().
cscale_
template<class Real > Real ROL::AugmentedLagrangianObjective< Real >::cscale_ private
Definition at line 75 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), ROL::AugmentedLagrangianObjective< Real >::setScaling(), and ROL::AugmentedLagrangianObjective< Real >::value().
nfval_
template<class Real > int ROL::AugmentedLagrangianObjective< Real >::nfval_ private
Definition at line 78 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::getNumberFunctionEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveValue(), and ROL::AugmentedLagrangianObjective< Real >::reset().
ngval_
template<class Real > int ROL::AugmentedLagrangianObjective< Real >::ngval_ private
Definition at line 79 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::getNumberGradientEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveGradient(), and ROL::AugmentedLagrangianObjective< Real >::reset().
ncval_
template<class Real > int ROL::AugmentedLagrangianObjective< Real >::ncval_ private
Definition at line 80 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), ROL::AugmentedLagrangianObjective< Real >::getNumberConstraintEvaluations(), and ROL::AugmentedLagrangianObjective< Real >::reset().
scaleLagrangian_
template<class Real > bool ROL::AugmentedLagrangianObjective< Real >::scaleLagrangian_ private
Definition at line 83 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::AugmentedLagrangianObjective< Real >::hessVec(), and ROL::AugmentedLagrangianObjective< Real >::value().
HessianApprox_
template<class Real > int ROL::AugmentedLagrangianObjective< Real >::HessianApprox_ private
Definition at line 84 of file ROL_AugmentedLagrangianObjective.hpp.
Referenced by ROL::AugmentedLagrangianObjective< Real >::AugmentedLagrangianObjective(), and ROL::AugmentedLagrangianObjective< Real >::hessVec().
The documentation for this class was generated from the following file:
ROL_AugmentedLagrangianObjective.hpp