ROL: ROL::TypeG::MoreauYosidaAlgorithm< Real > Class Template Reference
ROL::TypeG::MoreauYosidaAlgorithm< Real > Class Template Reference
Provides an interface to run the Moreau-Yosida algorithm.
#include <ROL_TypeG_MoreauYosidaAlgorithm.hpp>
Public Member Functions
MoreauYosidaAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, std::ostream &outStream=std::cout) override
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool print_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeG::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &l, const Vector< Real > &c, MoreauYosidaObjective< Real > &myobj, BoundConstraint< Real > &bnd, Constraint< Real > &con, Vector< Real > &pwa, Vector< Real > &dwa, std::ostream &outStream=std::cout)
void updateState (const Vector< Real > &x, const Vector< Real > &l, MoreauYosidaObjective< Real > &myobj, BoundConstraint< Real > &bnd, Constraint< Real > &con, Vector< Real > &pwa, Vector< Real > &dwa, std::ostream &outStream=std::cout)
Private Attributes
const Ptr< Secant< Real > > secant_
Real compViolation_
Real gnorm_
Real maxPenalty_
Real tau_
bool print_
bool updatePenalty_
bool updateMultiplier_
ROL::ParameterList list_
int subproblemIter_
std::string stepname_
int verbosity_
bool printHeader_
bool hasPolyProj_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeG::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &mul, const Vector< Real > &c)
Protected Attributes inherited from ROL::TypeG::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeG::MoreauYosidaAlgorithm< Real >
Provides an interface to run the Moreau-Yosida algorithm.
Definition at line 25 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Constructor & Destructor Documentation
MoreauYosidaAlgorithm()
template<typename Real > ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 19 of file ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp.
References ROL::TypeG::MoreauYosidaAlgorithm< Real >::list_, ROL::TypeG::MoreauYosidaAlgorithm< Real >::maxPenalty_, ROL::TypeG::MoreauYosidaAlgorithm< Real >::print_, ROL::TypeG::MoreauYosidaAlgorithm< Real >::printHeader_, ROL::TypeG::Algorithm< Real >::reset(), ROL::TypeG::Algorithm< Real >::state_, ROL::TypeG::Algorithm< Real >::status_, ROL::TypeG::MoreauYosidaAlgorithm< Real >::stepname_, ROL::TypeG::MoreauYosidaAlgorithm< Real >::tau_, ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateMultiplier_, ROL::TypeG::MoreauYosidaAlgorithm< Real >::updatePenalty_, and ROL::TypeG::MoreauYosidaAlgorithm< Real >::verbosity_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeG::MoreauYosidaAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & l, const Vector< Real > & c, MoreauYosidaObjective< Real > & myobj, BoundConstraint< Real > & bnd, Constraint< Real > & con, Vector< Real > & pwa, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 58 of file ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp.
References ROL::TypeG::Algorithm< Real >::initialize().
updateState()
template<typename Real > void ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateState (const Vector< Real > & x, const Vector< Real > & l, MoreauYosidaObjective< Real > & myobj, BoundConstraint< Real > & bnd, Constraint< Real > & con, Vector< Real > & pwa, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 85 of file ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Vector< Real >::axpy(), ROL::MoreauYosidaObjective< Real >::getObjectiveGradient(), ROL::MoreauYosidaObjective< Real >::getObjectiveValue(), ROL::Initial, ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), ROL::MoreauYosidaObjective< Real >::testComplementarity(), ROL::MoreauYosidaObjective< Real >::update(), ROL::Constraint< Real >::update(), and ROL::Constraint< Real >::value().
run()
template<typename Real > void ROL::TypeG::MoreauYosidaAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, std::ostream & outStream = std::cout) override virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Implements ROL::TypeG::Algorithm< Real >.
Definition at line 128 of file ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp.
References ROL::Vector< Real >::clone(), ROL::MoreauYosidaObjective< Real >::updateMultipliers(), ROL::TypeG::Algorithm< Real >::writeExitStatus(), and ROL::Vector< Real >::zero().
writeHeader()
template<typename Real > void ROL::TypeG::MoreauYosidaAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 191 of file ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeG::MoreauYosidaAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 228 of file ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeG::MoreauYosidaAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 237 of file ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeG::MoreauYosidaAlgorithm< Real >::secant_ private
Definition at line 27 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
compViolation_
template<typename Real > Real ROL::TypeG::MoreauYosidaAlgorithm< Real >::compViolation_ private
Definition at line 29 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
gnorm_
template<typename Real > Real ROL::TypeG::MoreauYosidaAlgorithm< Real >::gnorm_ private
Definition at line 30 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
maxPenalty_
template<typename Real > Real ROL::TypeG::MoreauYosidaAlgorithm< Real >::maxPenalty_ private
Definition at line 31 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
tau_
template<typename Real > Real ROL::TypeG::MoreauYosidaAlgorithm< Real >::tau_ private
Definition at line 32 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
print_
template<typename Real > bool ROL::TypeG::MoreauYosidaAlgorithm< Real >::print_ private
Definition at line 33 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
updatePenalty_
template<typename Real > bool ROL::TypeG::MoreauYosidaAlgorithm< Real >::updatePenalty_ private
Definition at line 34 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
updateMultiplier_
template<typename Real > bool ROL::TypeG::MoreauYosidaAlgorithm< Real >::updateMultiplier_ private
Definition at line 35 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
list_
template<typename Real > ROL::ParameterList ROL::TypeG::MoreauYosidaAlgorithm< Real >::list_ private
Definition at line 37 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
subproblemIter_
template<typename Real > int ROL::TypeG::MoreauYosidaAlgorithm< Real >::subproblemIter_ private
Definition at line 38 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
stepname_
template<typename Real > std::string ROL::TypeG::MoreauYosidaAlgorithm< Real >::stepname_ private
Definition at line 40 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
verbosity_
template<typename Real > int ROL::TypeG::MoreauYosidaAlgorithm< Real >::verbosity_ private
Definition at line 42 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
printHeader_
template<typename Real > bool ROL::TypeG::MoreauYosidaAlgorithm< Real >::printHeader_ private
Definition at line 43 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
hasPolyProj_
template<typename Real > bool ROL::TypeG::MoreauYosidaAlgorithm< Real >::hasPolyProj_ private
Definition at line 45 of file ROL_TypeG_MoreauYosidaAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeG_MoreauYosidaAlgorithm.hpp
ROL_TypeG_MoreauYosidaAlgorithm_Def.hpp