ROL: ROL::ProjectedObjective< Real > Class Template Reference
ROL::ProjectedObjective< Real > Class Template Reference
#include <ROL_HelperFunctions.hpp>
Public Member Functions
ProjectedObjective (Objective< Real > &obj, BoundConstraint< Real > &con, ROL::Ptr< Secant< Real > > &secant, bool useSecantPrecond=false, bool useSecantHessVec=false, Real eps=0.0)
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
void hessVec (Vector< Real > &Hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
void invHessVec (Vector< Real > &Hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
void precond (Vector< Real > &Mv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
void reducedHessVec (Vector< Real > &Hv, const Vector< Real > &v, const Vector< Real > &p, const Vector< Real > &d, const Vector< Real > &x, Real &tol)
Apply the reduced Hessian to a vector, v. The reduced Hessian first removes elements of v corresponding to the feasible indices from the point p in the direction -d. Hv the Hessian times a vector v input vector p starting point for tangent cone d negative of search direction x current iteration vector tol objective function tolerance.
void reducedHessVec (Vector< Real > &Hv, const Vector< Real > &v, const Vector< Real > &p, const Vector< Real > &x, Real &tol)
Apply the reduced Hessian to a vector, v. The reduced Hessian first removes elements of v corresponding to the feasible indices from the point p. Hv the Hessian times a vector v input vector p starting point for tangent cone x current iteration vector tol objective function tolerance.
void reducedInvHessVec (Vector< Real > &Hv, const Vector< Real > &v, const Vector< Real > &p, const Vector< Real > &d, const Vector< Real > &x, Real &tol)
Apply the reduced inverse Hessian to a vector, v.
The reduced inverse Hessian first removes elements of v corresponding to the feasible indices from the point p in the direction -d. Hv the inverse Hessian times a vector v input vector p starting point for tangent cone d negative of search direction x current iteration vector tol objective function tolerance.
void reducedInvHessVec (Vector< Real > &Hv, const Vector< Real > &v, const Vector< Real > &p, const Vector< Real > &x, Real &tol)
Apply the reduced inverse Hessian to a vector, v.
The reduced inverse Hessian first removes elements of v corresponding to the feasible indices from the point p. Hv the inverse Hessian times a vector v input vector p starting point for tangent cone x current iteration vector tol objective function tolerance.
void reducedPrecond (Vector< Real > &Mv, const Vector< Real > &v, const Vector< Real > &p, const Vector< Real > &d, const Vector< Real > &x, Real &tol)
Apply the reduced preconditioner to a vector, v.
The reduced preconditioner first removes elements of v corresponding to the feasible indices from the point p in the direction -d. Hv the preconditioner times a vector v input vector p starting point for tangent cone d negative of search direction x current iteration vector tol objective function tolerance.
void reducedPrecond (Vector< Real > &Mv, const Vector< Real > &v, const Vector< Real > &p, const Vector< Real > &x, Real &tol)
Apply the reduced preconditioner to a vector, v.
The reduced preconditioner first removes elements of v corresponding to the feasible indices from the point p. Hv the preconditioner times a vector v input vector p starting point for tangent cone x current iteration vector tol objective function tolerance.
void project (Vector< Real > &x)
void pruneActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x)
void pruneActive (Vector< Real > &v, const Vector< Real > &x)
void pruneInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x)
void pruneInactive (Vector< Real > &v, const Vector< Real > &x)
bool isFeasible (const Vector< Real > &v)
bool isConActivated (void)
void computeProjectedStep (Vector< Real > &v, const Vector< Real > &x)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
ROL::Ptr< Objective< Real > > obj_
ROL::Ptr< BoundConstraint< Real > > con_
ROL::Ptr< Secant< Real > > secant_
ROL::Ptr< ROL::Vector< Real > > primalV_
ROL::Ptr< ROL::Vector< Real > > dualV_
bool isInitialized_
bool useSecantPrecond_
bool useSecantHessVec_
Real eps_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::ProjectedObjective< Real >
Definition at line 213 of file ROL_HelperFunctions.hpp.
Constructor & Destructor Documentation
ProjectedObjective()
template<class Real > ROL::ProjectedObjective< Real >::ProjectedObjective (Objective< Real > & obj, BoundConstraint< Real > & con, ROL::Ptr< Secant< Real > > & secant, bool useSecantPrecond = false, bool useSecantHessVec = false, Real eps = 0.0) inline
Definition at line 228 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_, ROL::ProjectedObjective< Real >::obj_, and ROL::ProjectedObjective< Real >::secant_.
Member Function Documentation
update()
template<class Real > void ROL::ProjectedObjective< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 240 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_, and ROL::ProjectedObjective< Real >::obj_.
value()
template<class Real > Real ROL::ProjectedObjective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 245 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::obj_.
gradient()
template<class Real > void ROL::ProjectedObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 249 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::obj_.
dirDeriv()
template<class Real > Real ROL::ProjectedObjective< Real >::dirDeriv (const Vector< Real > & x, const Vector< Real > & d, Real & tol) inline virtual
Compute directional derivative.
This function returns the directional derivative of the objective function in the \(d\) direction.
Parameters
[in] x is the current iterate.
[in] d is the direction.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 253 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::obj_.
hessVec()
template<class Real > void ROL::ProjectedObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 257 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::obj_, ROL::ProjectedObjective< Real >::secant_, and ROL::ProjectedObjective< Real >::useSecantHessVec_.
Referenced by ROL::ProjectedObjective< Real >::reducedHessVec(), and ROL::ProjectedObjective< Real >::reducedHessVec().
invHessVec()
template<class Real > void ROL::ProjectedObjective< Real >::invHessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 266 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::obj_, ROL::ProjectedObjective< Real >::secant_, and ROL::ProjectedObjective< Real >::useSecantHessVec_.
Referenced by ROL::ProjectedObjective< Real >::reducedInvHessVec(), and ROL::ProjectedObjective< Real >::reducedInvHessVec().
precond()
template<class Real > void ROL::ProjectedObjective< Real >::precond (Vector< Real > & Pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 275 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::obj_, ROL::ProjectedObjective< Real >::secant_, and ROL::ProjectedObjective< Real >::useSecantPrecond_.
Referenced by ROL::ProjectedObjective< Real >::reducedPrecond(), and ROL::ProjectedObjective< Real >::reducedPrecond().
reducedHessVec() [1/2]
template<class Real > void ROL::ProjectedObjective< Real >::reducedHessVec (Vector< Real > & Hv, const Vector< Real > & v, const Vector< Real > & p, const Vector< Real > & d, const Vector< Real > & x, Real & tol) inline
Apply the reduced Hessian to a vector, v. The reduced Hessian first removes elements of v corresponding to the feasible indices from the point p in the direction -d. Hv the Hessian times a vector v input vector p starting point for tangent cone d negative of search direction x current iteration vector tol objective function tolerance.
Definition at line 295 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedObjective< Real >::con_, ROL::Vector< Real >::dual(), ROL::ProjectedObjective< Real >::dualV_, ROL::ProjectedObjective< Real >::eps_, ROL::ProjectedObjective< Real >::hessVec(), ROL::ProjectedObjective< Real >::isInitialized_, ROL::Vector< Real >::plus(), and ROL::ProjectedObjective< Real >::primalV_.
reducedHessVec() [2/2]
template<class Real > void ROL::ProjectedObjective< Real >::reducedHessVec (Vector< Real > & Hv, const Vector< Real > & v, const Vector< Real > & p, const Vector< Real > & x, Real & tol) inline
Apply the reduced Hessian to a vector, v. The reduced Hessian first removes elements of v corresponding to the feasible indices from the point p. Hv the Hessian times a vector v input vector p starting point for tangent cone x current iteration vector tol objective function tolerance.
Definition at line 335 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedObjective< Real >::con_, ROL::Vector< Real >::dual(), ROL::ProjectedObjective< Real >::dualV_, ROL::ProjectedObjective< Real >::eps_, ROL::ProjectedObjective< Real >::hessVec(), ROL::ProjectedObjective< Real >::isInitialized_, ROL::Vector< Real >::plus(), and ROL::ProjectedObjective< Real >::primalV_.
reducedInvHessVec() [1/2]
template<class Real > void ROL::ProjectedObjective< Real >::reducedInvHessVec (Vector< Real > & Hv, const Vector< Real > & v, const Vector< Real > & p, const Vector< Real > & d, const Vector< Real > & x, Real & tol) inline
Apply the reduced inverse Hessian to a vector, v.
The reduced inverse Hessian first removes elements of v corresponding to the feasible indices from the point p in the direction -d. Hv the inverse Hessian times a vector v input vector p starting point for tangent cone d negative of search direction x current iteration vector tol objective function tolerance.
Definition at line 376 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedObjective< Real >::con_, ROL::Vector< Real >::dual(), ROL::ProjectedObjective< Real >::dualV_, ROL::ProjectedObjective< Real >::eps_, ROL::ProjectedObjective< Real >::invHessVec(), ROL::ProjectedObjective< Real >::isInitialized_, ROL::Vector< Real >::plus(), and ROL::ProjectedObjective< Real >::primalV_.
reducedInvHessVec() [2/2]
template<class Real > void ROL::ProjectedObjective< Real >::reducedInvHessVec (Vector< Real > & Hv, const Vector< Real > & v, const Vector< Real > & p, const Vector< Real > & x, Real & tol) inline
Apply the reduced inverse Hessian to a vector, v.
The reduced inverse Hessian first removes elements of v corresponding to the feasible indices from the point p. Hv the inverse Hessian times a vector v input vector p starting point for tangent cone x current iteration vector tol objective function tolerance.
Definition at line 416 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedObjective< Real >::con_, ROL::Vector< Real >::dual(), ROL::ProjectedObjective< Real >::dualV_, ROL::ProjectedObjective< Real >::eps_, ROL::ProjectedObjective< Real >::invHessVec(), ROL::ProjectedObjective< Real >::isInitialized_, ROL::Vector< Real >::plus(), and ROL::ProjectedObjective< Real >::primalV_.
reducedPrecond() [1/2]
template<class Real > void ROL::ProjectedObjective< Real >::reducedPrecond (Vector< Real > & Mv, const Vector< Real > & v, const Vector< Real > & p, const Vector< Real > & d, const Vector< Real > & x, Real & tol) inline
Apply the reduced preconditioner to a vector, v.
The reduced preconditioner first removes elements of v corresponding to the feasible indices from the point p in the direction -d. Hv the preconditioner times a vector v input vector p starting point for tangent cone d negative of search direction x current iteration vector tol objective function tolerance.
Definition at line 457 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedObjective< Real >::con_, ROL::Vector< Real >::dual(), ROL::ProjectedObjective< Real >::dualV_, ROL::ProjectedObjective< Real >::eps_, ROL::ProjectedObjective< Real >::isInitialized_, ROL::Vector< Real >::plus(), ROL::ProjectedObjective< Real >::precond(), and ROL::ProjectedObjective< Real >::primalV_.
reducedPrecond() [2/2]
template<class Real > void ROL::ProjectedObjective< Real >::reducedPrecond (Vector< Real > & Mv, const Vector< Real > & v, const Vector< Real > & p, const Vector< Real > & x, Real & tol) inline
Apply the reduced preconditioner to a vector, v.
The reduced preconditioner first removes elements of v corresponding to the feasible indices from the point p. Hv the preconditioner times a vector v input vector p starting point for tangent cone x current iteration vector tol objective function tolerance.
Definition at line 497 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::clone(), ROL::ProjectedObjective< Real >::con_, ROL::Vector< Real >::dual(), ROL::ProjectedObjective< Real >::dualV_, ROL::ProjectedObjective< Real >::eps_, ROL::ProjectedObjective< Real >::isInitialized_, ROL::Vector< Real >::plus(), ROL::ProjectedObjective< Real >::precond(), and ROL::ProjectedObjective< Real >::primalV_.
project()
template<class Real > void ROL::ProjectedObjective< Real >::project (Vector< Real > & x) inline
Definition at line 527 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_.
pruneActive() [1/2]
template<class Real > void ROL::ProjectedObjective< Real >::pruneActive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x) inline
Definition at line 531 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_, and ROL::ProjectedObjective< Real >::eps_.
pruneActive() [2/2]
template<class Real > void ROL::ProjectedObjective< Real >::pruneActive (Vector< Real > & v, const Vector< Real > & x) inline
Definition at line 535 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_, and ROL::ProjectedObjective< Real >::eps_.
pruneInactive() [1/2]
template<class Real > void ROL::ProjectedObjective< Real >::pruneInactive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x) inline
Definition at line 539 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_, and ROL::ProjectedObjective< Real >::eps_.
pruneInactive() [2/2]
template<class Real > void ROL::ProjectedObjective< Real >::pruneInactive (Vector< Real > & v, const Vector< Real > & x) inline
Definition at line 543 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_, and ROL::ProjectedObjective< Real >::eps_.
isFeasible()
template<class Real > bool ROL::ProjectedObjective< Real >::isFeasible (const Vector< Real > & v) inline
Definition at line 547 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_.
isConActivated()
template<class Real > bool ROL::ProjectedObjective< Real >::isConActivated (void) inline
Definition at line 551 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_.
computeProjectedStep()
template<class Real > void ROL::ProjectedObjective< Real >::computeProjectedStep (Vector< Real > & v, const Vector< Real > & x) inline
Definition at line 555 of file ROL_HelperFunctions.hpp.
References ROL::ProjectedObjective< Real >::con_.
Member Data Documentation
obj_
template<class Real > ROL::Ptr<Objective<Real> > ROL::ProjectedObjective< Real >::obj_ private
Definition at line 215 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::dirDeriv(), ROL::ProjectedObjective< Real >::gradient(), ROL::ProjectedObjective< Real >::hessVec(), ROL::ProjectedObjective< Real >::invHessVec(), ROL::ProjectedObjective< Real >::precond(), ROL::ProjectedObjective< Real >::ProjectedObjective(), ROL::ProjectedObjective< Real >::update(), and ROL::ProjectedObjective< Real >::value().
con_
template<class Real > ROL::Ptr<BoundConstraint<Real> > ROL::ProjectedObjective< Real >::con_ private
Definition at line 216 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::computeProjectedStep(), ROL::ProjectedObjective< Real >::isConActivated(), ROL::ProjectedObjective< Real >::isFeasible(), ROL::ProjectedObjective< Real >::project(), ROL::ProjectedObjective< Real >::ProjectedObjective(), ROL::ProjectedObjective< Real >::pruneActive(), ROL::ProjectedObjective< Real >::pruneActive(), ROL::ProjectedObjective< Real >::pruneInactive(), ROL::ProjectedObjective< Real >::pruneInactive(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), ROL::ProjectedObjective< Real >::reducedPrecond(), and ROL::ProjectedObjective< Real >::update().
secant_
template<class Real > ROL::Ptr<Secant<Real> > ROL::ProjectedObjective< Real >::secant_ private
Definition at line 217 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::hessVec(), ROL::ProjectedObjective< Real >::invHessVec(), ROL::ProjectedObjective< Real >::precond(), and ROL::ProjectedObjective< Real >::ProjectedObjective().
primalV_
template<class Real > ROL::Ptr<ROL::Vector<Real> > ROL::ProjectedObjective< Real >::primalV_ private
Definition at line 219 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), and ROL::ProjectedObjective< Real >::reducedPrecond().
dualV_
template<class Real > ROL::Ptr<ROL::Vector<Real> > ROL::ProjectedObjective< Real >::dualV_ private
Definition at line 220 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), and ROL::ProjectedObjective< Real >::reducedPrecond().
isInitialized_
template<class Real > bool ROL::ProjectedObjective< Real >::isInitialized_ private
Definition at line 221 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), and ROL::ProjectedObjective< Real >::reducedPrecond().
useSecantPrecond_
template<class Real > bool ROL::ProjectedObjective< Real >::useSecantPrecond_ private
Definition at line 223 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::precond().
useSecantHessVec_
template<class Real > bool ROL::ProjectedObjective< Real >::useSecantHessVec_ private
Definition at line 224 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::hessVec(), and ROL::ProjectedObjective< Real >::invHessVec().
eps_
template<class Real > Real ROL::ProjectedObjective< Real >::eps_ private
Definition at line 225 of file ROL_HelperFunctions.hpp.
Referenced by ROL::ProjectedObjective< Real >::pruneActive(), ROL::ProjectedObjective< Real >::pruneActive(), ROL::ProjectedObjective< Real >::pruneInactive(), ROL::ProjectedObjective< Real >::pruneInactive(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedInvHessVec(), ROL::ProjectedObjective< Real >::reducedPrecond(), and ROL::ProjectedObjective< Real >::reducedPrecond().
The documentation for this class was generated from the following file:
ROL_HelperFunctions.hpp