ROL: ROL::TypeG::Algorithm< Real > Class Template Reference
ROL::TypeG::Algorithm< Real > Class Template Reference abstract
Provides an interface to run general constrained optimization algorithms.
#include <ROL_TypeG_Algorithm.hpp>
Public Member Functions
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, std::ostream &outStream=std::cout)=0
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void writeHeader (std::ostream &os) const
Print iterate header.
virtual void writeName (std::ostream &os) const
Print step name.
virtual void writeOutput (std::ostream &os, const bool write_header=false) const
Print iterate status.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Protected Member Functions
void initialize (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &mul, const Vector< Real > &c)
Protected Attributes
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeG::Algorithm< Real >
Provides an interface to run general constrained optimization algorithms.
Definition at line 56 of file ROL_TypeG_Algorithm.hpp.
Constructor & Destructor Documentation
~Algorithm()
template<typename Real > virtual ROL::TypeG::Algorithm< Real >::~Algorithm () inline virtual
Definition at line 69 of file ROL_TypeG_Algorithm.hpp.
Algorithm()
template<typename Real > ROL::TypeG::Algorithm< Real >::Algorithm ()
Constructor, given a step and a status test.
Definition at line 23 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::TypeG::Algorithm< Real >::status_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeG::Algorithm< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & mul, const Vector< Real > & c) protected
Definition at line 32 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Vector< Real >::clone().
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::InteriorPointAlgorithm< Real >::initialize(), and ROL::TypeG::MoreauYosidaAlgorithm< Real >::initialize().
setStatusTest()
template<typename Real > void ROL::TypeG::Algorithm< Real >::setStatusTest (const Ptr< StatusTest< Real > > & status, bool combineStatus = false)
Definition at line 65 of file ROL_TypeG_Algorithm_Def.hpp.
run() [1/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Problem< Real > & problem, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Reimplemented in ROL::TypeG::StabilizedLCLAlgorithm< Real >.
Definition at line 74 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::finalizeIteration(), ROL::Problem< Real >::getBoundConstraint(), ROL::Problem< Real >::getConstraint(), ROL::Problem< Real >::getDualOptimizationVector(), ROL::Problem< Real >::getMultiplierVector(), ROL::Problem< Real >::getObjective(), ROL::Problem< Real >::getPolyhedralProjection(), ROL::Problem< Real >::getPrimalOptimizationVector(), ROL::Problem< Real >::getProblemType(), ROL::Problem< Real >::getResidualVector(), and ROL::TYPE_EB.
run() [2/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 94 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), and ROL::Problem< Real >::finalize().
run() [3/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 111 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), and ROL::Problem< Real >::finalize().
run() [4/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 127 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), and ROL::Problem< Real >::finalize().
run() [5/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 145 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), and ROL::Problem< Real >::finalize().
run() [6/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 165 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), and ROL::Problem< Real >::finalize().
run() [7/21]
template<typename Real > virtual void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, std::ostream & outStream = std::cout) pure virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Implemented in ROL::TypeG::AugmentedLagrangianAlgorithm< Real >, ROL::TypeG::InteriorPointAlgorithm< Real >, ROL::TypeG::MoreauYosidaAlgorithm< Real >, and ROL::TypeG::StabilizedLCLAlgorithm< Real >.
run() [8/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 189 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [9/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 216 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [10/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 246 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [11/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 283 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [12/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 324 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), and ROL::Problem< Real >::finalize().
run() [13/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 347 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), and ROL::Problem< Real >::finalize().
run() [14/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 369 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), and ROL::Problem< Real >::finalize().
run() [15/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 393 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), and ROL::Problem< Real >::finalize().
run() [16/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 419 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), and ROL::Problem< Real >::finalize().
run() [17/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 449 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [18/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 478 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [19/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 512 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [20/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 551 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [21/21]
template<typename Real > void ROL::TypeG::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, Constraint< Real > & icon, Vector< Real > & imul, BoundConstraint< Real > & ibnd, const Vector< Real > & ires, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Definition at line 591 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
writeHeader()
template<typename Real > void ROL::TypeG::Algorithm< Real >::writeHeader (std::ostream & os) const virtual
Print iterate header.
Reimplemented in ROL::TypeG::AugmentedLagrangianAlgorithm< Real >, ROL::TypeG::InteriorPointAlgorithm< Real >, ROL::TypeG::MoreauYosidaAlgorithm< Real >, and ROL::TypeG::StabilizedLCLAlgorithm< Real >.
Definition at line 638 of file ROL_TypeG_Algorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeG::Algorithm< Real >::writeName (std::ostream & os) const virtual
Print step name.
Reimplemented in ROL::TypeG::AugmentedLagrangianAlgorithm< Real >, ROL::TypeG::InteriorPointAlgorithm< Real >, ROL::TypeG::MoreauYosidaAlgorithm< Real >, and ROL::TypeG::StabilizedLCLAlgorithm< Real >.
Definition at line 652 of file ROL_TypeG_Algorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeG::Algorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const virtual
Print iterate status.
Reimplemented in ROL::TypeG::AugmentedLagrangianAlgorithm< Real >, ROL::TypeG::InteriorPointAlgorithm< Real >, ROL::TypeG::MoreauYosidaAlgorithm< Real >, and ROL::TypeG::StabilizedLCLAlgorithm< Real >.
Definition at line 657 of file ROL_TypeG_Algorithm_Def.hpp.
writeExitStatus()
template<typename Real > void ROL::TypeG::Algorithm< Real >::writeExitStatus (std::ostream & os) const virtual
Definition at line 682 of file ROL_TypeG_Algorithm_Def.hpp.
References ROL::EExitStatusToString().
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeG::InteriorPointAlgorithm< Real >::run(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::run(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::run().
getState()
template<typename Real > Ptr< const AlgorithmState< Real > > ROL::TypeG::Algorithm< Real >::getState () const
Definition at line 691 of file ROL_TypeG_Algorithm_Def.hpp.
reset()
template<typename Real > void ROL::TypeG::Algorithm< Real >::reset ()
Definition at line 697 of file ROL_TypeG_Algorithm_Def.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm(), ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
Member Data Documentation
status_
template<typename Real > const Ptr<CombinedStatusTest<Real> > ROL::TypeG::Algorithm< Real >::status_ protected
Definition at line 58 of file ROL_TypeG_Algorithm.hpp.
Referenced by ROL::TypeG::Algorithm< Real >::Algorithm(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm(), ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
state_
template<typename Real > const Ptr<AlgorithmState<Real> > ROL::TypeG::Algorithm< Real >::state_ protected
Definition at line 59 of file ROL_TypeG_Algorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm(), ROL::TypeG::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm(), ROL::TypeG::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm(), and ROL::TypeG::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
proj_
template<typename Real > Ptr<PolyhedralProjection<Real> > ROL::TypeG::Algorithm< Real >::proj_ protected
Definition at line 60 of file ROL_TypeG_Algorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeG_Algorithm.hpp
ROL_TypeG_Algorithm_Def.hpp