ROL: ROL::BiCGSTAB< Real > Class Template Reference
ROL::BiCGSTAB< Real > Class Template Reference
#include <ROL_BiCGSTAB.hpp>
Public Member Functions
BiCGSTAB (Real absTol=1.e-4, Real relTol=1.e-2, unsigned maxit=100, bool useInexact=false)
BiCGSTAB (ParameterList &parlist, bool useInexact=false)
Real run (Vector< Real > &x, LinearOperator< Real > &A, const Vector< Real > &b, LinearOperator< Real > &M, int &iter, int &flag)
Public Member Functions inherited from ROL::Krylov< Real >
virtual ~Krylov (void)
Krylov (Real absTol=1.e-4, Real relTol=1.e-2, unsigned maxit=100)
Krylov (ROL::ParameterList &parlist)
void resetAbsoluteTolerance (const Real absTol)
void resetRelativeTolerance (const Real relTol)
void resetMaximumIteration (const unsigned maxit)
Real getAbsoluteTolerance (void) const
Real getRelativeTolerance (void) const
unsigned getMaximumIteration (void) const
Private Attributes
bool isInitialized_
const bool useInexact_
Ptr< Vector< Real > > r_
Ptr< Vector< Real > > r1_
Ptr< Vector< Real > > p_
Ptr< Vector< Real > > v_
Ptr< Vector< Real > > s_
Ptr< Vector< Real > > t_
Ptr< Vector< Real > > h_
Ptr< Vector< Real > > y_
Ptr< Vector< Real > > z_
Detailed Description
template<class Real>
class ROL::BiCGSTAB< Real >
Definition at line 57 of file ROL_BiCGSTAB.hpp.
Constructor & Destructor Documentation
BiCGSTAB() [1/2]
template<class Real > ROL::BiCGSTAB< Real >::BiCGSTAB (Real absTol = 1.e-4, Real relTol = 1.e-2, unsigned maxit = 100, bool useInexact = false) inline
Definition at line 64 of file ROL_BiCGSTAB.hpp.
BiCGSTAB() [2/2]
template<class Real > ROL::BiCGSTAB< Real >::BiCGSTAB (ParameterList & parlist, bool useInexact = false) inline
Definition at line 67 of file ROL_BiCGSTAB.hpp.
Member Function Documentation
run()
template<class Real > Real ROL::BiCGSTAB< Real >::run (Vector< Real > & x, LinearOperator< Real > & A, const Vector< Real > & b, LinearOperator< Real > & M, int & iter, int & flag) inline virtual
Implements ROL::Krylov< Real >.
Definition at line 70 of file ROL_BiCGSTAB.hpp.
References ROL::LinearOperator< Real >::apply(), ROL::LinearOperator< Real >::applyInverse(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Krylov< Real >::getMaximumIteration(), ROL::BiCGSTAB< Real >::h_, ROL::BiCGSTAB< Real >::isInitialized_, ROL::Vector< Real >::norm(), ROL::BiCGSTAB< Real >::p_, ROL::BiCGSTAB< Real >::r1_, ROL::BiCGSTAB< Real >::r_, ROL::BiCGSTAB< Real >::s_, ROL::Vector< Real >::set(), ROL::BiCGSTAB< Real >::t_, ROL::BiCGSTAB< Real >::useInexact_, ROL::BiCGSTAB< Real >::v_, ROL::BiCGSTAB< Real >::y_, ROL::BiCGSTAB< Real >::z_, and ROL::Vector< Real >::zero().
Member Data Documentation
isInitialized_
template<class Real > bool ROL::BiCGSTAB< Real >::isInitialized_ private
Definition at line 59 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
useInexact_
template<class Real > const bool ROL::BiCGSTAB< Real >::useInexact_ private
Definition at line 60 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
r_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::r_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
r1_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::r1_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
p_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::p_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
v_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::v_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
s_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::s_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
t_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::t_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
h_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::h_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
y_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::y_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
z_
template<class Real > Ptr<Vector<Real> > ROL::BiCGSTAB< Real >::z_ private
Definition at line 61 of file ROL_BiCGSTAB.hpp.
Referenced by ROL::BiCGSTAB< Real >::run().
The documentation for this class was generated from the following file:
ROL_BiCGSTAB.hpp