ROL: ROL::AugmentedSystemOperator< Real > Class Template Reference
ROL::AugmentedSystemOperator< Real > Class Template Reference
User Interface » Functional Interface
Apply the augmented system operator.
#include <ROL_AugmentedSystemOperator.hpp>
Public Member Functions
virtual ~AugmentedSystemOperator ()
AugmentedSystemOperator (const Ptr< Constraint< Real > > &con, const Ptr< const Vector< Real > > &x, const Real delta=0.0)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
Private Attributes
const Ptr< Constraint< Real > > con_
const Ptr< const Vector< Real > > x_
const Real delta_
Detailed Description
template<class Real>
class ROL::AugmentedSystemOperator< Real >
Apply the augmented system operator.
Definition at line 26 of file ROL_AugmentedSystemOperator.hpp.
Constructor & Destructor Documentation
~AugmentedSystemOperator()
template<class Real > virtual ROL::AugmentedSystemOperator< Real >::~AugmentedSystemOperator () inline virtual
Definition at line 33 of file ROL_AugmentedSystemOperator.hpp.
AugmentedSystemOperator()
template<class Real > ROL::AugmentedSystemOperator< Real >::AugmentedSystemOperator (const Ptr< Constraint< Real > > & con, const Ptr< const Vector< Real > > & x, const Real delta = 0.0) inline
Definition at line 34 of file ROL_AugmentedSystemOperator.hpp.
Member Function Documentation
apply()
template<class Real > void ROL::AugmentedSystemOperator< Real >::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 39 of file ROL_AugmentedSystemOperator.hpp.
References ROL::AugmentedSystemOperator< Real >::con_, ROL::AugmentedSystemOperator< Real >::delta_, ROL::PartitionedVector< Real >::dual(), ROL::PartitionedVector< Real >::get(), and ROL::AugmentedSystemOperator< Real >::x_.
Referenced by ROL::AugmentedSystemOperator< Real >::applyAdjoint().
applyAdjoint()
template<class Real > void ROL::AugmentedSystemOperator< Real >::applyAdjoint (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of linear operator.
This function applies the adjoint of a linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 55 of file ROL_AugmentedSystemOperator.hpp.
References ROL::AugmentedSystemOperator< Real >::apply().
applyInverse()
template<class Real > void ROL::AugmentedSystemOperator< Real >::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 59 of file ROL_AugmentedSystemOperator.hpp.
applyAdjointInverse()
template<class Real > void ROL::AugmentedSystemOperator< Real >::applyAdjointInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of the inverse linear operator.
This function applies the adjoint of the inverse linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 63 of file ROL_AugmentedSystemOperator.hpp.
Member Data Documentation
con_
template<class Real > const Ptr<Constraint<Real> > ROL::AugmentedSystemOperator< Real >::con_ private
Definition at line 28 of file ROL_AugmentedSystemOperator.hpp.
Referenced by ROL::AugmentedSystemOperator< Real >::apply().
x_
template<class Real > const Ptr<const Vector<Real> > ROL::AugmentedSystemOperator< Real >::x_ private
Definition at line 29 of file ROL_AugmentedSystemOperator.hpp.
Referenced by ROL::AugmentedSystemOperator< Real >::apply().
delta_
template<class Real > const Real ROL::AugmentedSystemOperator< Real >::delta_ private
Definition at line 30 of file ROL_AugmentedSystemOperator.hpp.
Referenced by ROL::AugmentedSystemOperator< Real >::apply().
The documentation for this class was generated from the following file:
ROL_AugmentedSystemOperator.hpp