ROL: ROL::Bundle_U_AS< Real > Class Template Reference
ROL::Bundle_U_AS< Real > Class Template Reference
Provides the interface for and implements an active set bundle.
#include <ROL_Bundle_U_AS.hpp>
Public Member Functions
Bundle_U_AS (const unsigned maxSize=10, const Real coeff=0.0, const Real omega=2.0, const unsigned remSize=2)
void initialize (const Vector< Real > &g)
unsigned solveDual (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
Public Member Functions inherited from ROL::Bundle_U< Real >
virtual ~Bundle_U (void)
Bundle_U (const unsigned maxSize=10, const Real coeff=0.0, const Real omega=2.0, const unsigned remSize=2)
const Real linearizationError (const unsigned i) const
const Real distanceMeasure (const unsigned i) const
const Vector< Real > & subgradient (const unsigned i) const
const Real getDualVariable (const unsigned i) const
void setDualVariable (const unsigned i, const Real val)
void resetDualVariables (void)
const Real computeAlpha (const Real dm, const Real le) const
const Real alpha (const unsigned i) const
unsigned size (void) const
void aggregate (Vector< Real > &aggSubGrad, Real &aggLinErr, Real &aggDistMeas) const
void reset (const Vector< Real > &g, const Real le, const Real dm)
void update (const bool flag, const Real linErr, const Real distMeas, const Vector< Real > &g, const Vector< Real > &s)
Private Member Functions
void initializeDualSolver (void)
void computeLagMult (std::vector< Real > &lam, const Real mu, const std::vector< Real > &g) const
bool isNonnegative (unsigned &ind, const std::vector< Real > &x) const
Real computeStepSize (unsigned &ind, const std::vector< Real > &x, const std::vector< Real > &p) const
unsigned solveEQPsubproblem (std::vector< Real > &s, Real &mu, const std::vector< Real > &g, const Real tol) const
void applyPreconditioner (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG (std::vector< Real > &Gx, const std::vector< Real > &x) const
void applyPreconditioner_Identity (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG_Identity (std::vector< Real > &Gx, const std::vector< Real > &x) const
void applyPreconditioner_Jacobi (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG_Jacobi (std::vector< Real > &Gx, const std::vector< Real > &x) const
void applyPreconditioner_SymGS (std::vector< Real > &Px, const std::vector< Real > &x) const
void applyG_SymGS (std::vector< Real > &Gx, const std::vector< Real > &x) const
void computeResidualUpdate (std::vector< Real > &r, std::vector< Real > &g) const
void applyFullMatrix (std::vector< Real > &Hx, const std::vector< Real > &x) const
void applyMatrix (std::vector< Real > &Hx, const std::vector< Real > &x) const
unsigned projectedCG (std::vector< Real > &x, Real &mu, const std::vector< Real > &b, const Real tol) const
Real dot (const std::vector< Real > &x, const std::vector< Real > &y) const
Real norm (const std::vector< Real > &x) const
void axpy (const Real a, const std::vector< Real > &x, std::vector< Real > &y) const
void scale (std::vector< Real > &x, const Real a) const
void scale (std::vector< Real > &x, const Real a, const std::vector< Real > &y) const
unsigned solveDual_arbitrary (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
void project (std::vector< Real > &x, const std::vector< Real > &v) const
Real computeCriticality (const std::vector< Real > &g, const std::vector< Real > &sol) const
Private Attributes
Ptr< Vector< Real > > tG_
Ptr< Vector< Real > > eG_
Ptr< Vector< Real > > yG_
Ptr< Vector< Real > > gx_
Ptr< Vector< Real > > ge_
std::set< unsigned > workingSet_
std::set< unsigned > nworkingSet_
bool isInitialized_
Additional Inherited Members
Protected Member Functions inherited from ROL::Bundle_U< Real >
const Real GiGj (const unsigned i, const unsigned j) const
const Real dotGi (const unsigned i, const Vector< Real > &x) const
void addGi (const unsigned i, const Real a, Vector< Real > &x) const
Real evaluateObjective (std::vector< Real > &g, const std::vector< Real > &x, const Real t) const
unsigned solveDual_dim1 (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
unsigned solveDual_dim2 (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
Detailed Description
template<typename Real>
class ROL::Bundle_U_AS< Real >
Provides the interface for and implements an active set bundle.
Definition at line 22 of file ROL_Bundle_U_AS.hpp.
Constructor & Destructor Documentation
Bundle_U_AS()
template<typename Real > ROL::Bundle_U_AS< Real >::Bundle_U_AS (const unsigned maxSize = 10, const Real coeff = 0.0, const Real omega = 2.0, const unsigned remSize = 2)
Definition at line 16 of file ROL_Bundle_U_AS_Def.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::Bundle_U_AS< Real >::initialize (const Vector< Real > & g) virtual
Reimplemented from ROL::Bundle_U< Real >.
Definition at line 23 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Vector< Real >::clone(), and ROL::Bundle_U< Real >::initialize().
solveDual()
template<typename Real > unsigned ROL::Bundle_U_AS< Real >::solveDual (const Real t, const unsigned maxit = 1000, const Real tol = 1.e-8) virtual
Implements ROL::Bundle_U< Real >.
Definition at line 36 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::solveDual_dim1(), and ROL::Bundle_U< Real >::solveDual_dim2().
initializeDualSolver()
template<typename Real > void ROL::Bundle_U_AS< Real >::initializeDualSolver (void) private
Definition at line 51 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::getDualVariable(), ROL::Bundle_U< Real >::setDualVariable(), and zero.
computeLagMult()
template<typename Real > void ROL::Bundle_U_AS< Real >::computeLagMult (std::vector< Real > & lam, const Real mu, const std::vector< Real > & g) const private
Definition at line 79 of file ROL_Bundle_U_AS_Def.hpp.
References zero.
isNonnegative()
template<typename Real > bool ROL::Bundle_U_AS< Real >::isNonnegative (unsigned & ind, const std::vector< Real > & x) const private
Definition at line 95 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::size().
computeStepSize()
template<typename Real > Real ROL::Bundle_U_AS< Real >::computeStepSize (unsigned & ind, const std::vector< Real > & x, const std::vector< Real > & p) const private
Definition at line 115 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::size(), and zero.
solveEQPsubproblem()
template<typename Real > unsigned ROL::Bundle_U_AS< Real >::solveEQPsubproblem (std::vector< Real > & s, Real & mu, const std::vector< Real > & g, const Real tol) const private
Definition at line 133 of file ROL_Bundle_U_AS_Def.hpp.
References zero.
applyPreconditioner()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyPreconditioner (std::vector< Real > & Px, const std::vector< Real > & x) const private
Definition at line 157 of file ROL_Bundle_U_AS_Def.hpp.
References zero.
applyG()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyG (std::vector< Real > & Gx, const std::vector< Real > & x) const private
Definition at line 170 of file ROL_Bundle_U_AS_Def.hpp.
applyPreconditioner_Identity()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyPreconditioner_Identity (std::vector< Real > & Px, const std::vector< Real > & x) const private
Definition at line 180 of file ROL_Bundle_U_AS_Def.hpp.
References dim.
applyG_Identity()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyG_Identity (std::vector< Real > & Gx, const std::vector< Real > & x) const private
Definition at line 198 of file ROL_Bundle_U_AS_Def.hpp.
applyPreconditioner_Jacobi()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyPreconditioner_Jacobi (std::vector< Real > & Px, const std::vector< Real > & x) const private
Definition at line 203 of file ROL_Bundle_U_AS_Def.hpp.
References dim, and zero.
applyG_Jacobi()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyG_Jacobi (std::vector< Real > & Gx, const std::vector< Real > & x) const private
Definition at line 232 of file ROL_Bundle_U_AS_Def.hpp.
References dim.
applyPreconditioner_SymGS()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyPreconditioner_SymGS (std::vector< Real > & Px, const std::vector< Real > & x) const private
Definition at line 241 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::addGi(), dim, ROL::Bundle_U< Real >::dotGi(), and ROL::Bundle_U< Real >::GiGj().
applyG_SymGS()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyG_SymGS (std::vector< Real > & Gx, const std::vector< Real > & x) const private
Definition at line 290 of file ROL_Bundle_U_AS_Def.hpp.
References dim.
computeResidualUpdate()
template<typename Real > void ROL::Bundle_U_AS< Real >::computeResidualUpdate (std::vector< Real > & r, std::vector< Real > & g) const private
Definition at line 299 of file ROL_Bundle_U_AS_Def.hpp.
applyFullMatrix()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyFullMatrix (std::vector< Real > & Hx, const std::vector< Real > & x) const private
Definition at line 321 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::dotGi().
applyMatrix()
template<typename Real > void ROL::Bundle_U_AS< Real >::applyMatrix (std::vector< Real > & Hx, const std::vector< Real > & x) const private
Definition at line 339 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::dotGi().
projectedCG()
template<typename Real > unsigned ROL::Bundle_U_AS< Real >::projectedCG (std::vector< Real > & x, Real & mu, const std::vector< Real > & b, const Real tol) const private
Definition at line 361 of file ROL_Bundle_U_AS_Def.hpp.
References zero.
dot()
template<typename Real > Real ROL::Bundle_U_AS< Real >::dot (const std::vector< Real > & x, const std::vector< Real > & y) const private
Definition at line 408 of file ROL_Bundle_U_AS_Def.hpp.
norm()
template<typename Real > Real ROL::Bundle_U_AS< Real >::norm (const std::vector< Real > & x) const private
Definition at line 423 of file ROL_Bundle_U_AS_Def.hpp.
axpy()
template<typename Real > void ROL::Bundle_U_AS< Real >::axpy (const Real a, const std::vector< Real > & x, std::vector< Real > & y) const private
Definition at line 428 of file ROL_Bundle_U_AS_Def.hpp.
scale() [1/2]
template<typename Real > void ROL::Bundle_U_AS< Real >::scale (std::vector< Real > & x, const Real a) const private
Definition at line 436 of file ROL_Bundle_U_AS_Def.hpp.
scale() [2/2]
template<typename Real > void ROL::Bundle_U_AS< Real >::scale (std::vector< Real > & x, const Real a, const std::vector< Real > & y) const private
Definition at line 443 of file ROL_Bundle_U_AS_Def.hpp.
solveDual_arbitrary()
template<typename Real > unsigned ROL::Bundle_U_AS< Real >::solveDual_arbitrary (const Real t, const unsigned maxit = 1000, const Real tol = 1.e-8) private
Definition at line 451 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::evaluateObjective(), ROL::Bundle_U< Real >::getDualVariable(), ROL::Bundle_U< Real >::setDualVariable(), and zero.
project()
template<typename Real > void ROL::Bundle_U_AS< Real >::project (std::vector< Real > & x, const std::vector< Real > & v) const private
Definition at line 506 of file ROL_Bundle_U_AS_Def.hpp.
References ROL::Bundle_U< Real >::size(), and zero.
computeCriticality()
template<typename Real > Real ROL::Bundle_U_AS< Real >::computeCriticality (const std::vector< Real > & g, const std::vector< Real > & sol) const private
Definition at line 528 of file ROL_Bundle_U_AS_Def.hpp.
References zero.
Member Data Documentation
tG_
template<typename Real > Ptr<Vector<Real> > ROL::Bundle_U_AS< Real >::tG_ private
Definition at line 28 of file ROL_Bundle_U_AS.hpp.
eG_
template<typename Real > Ptr<Vector<Real> > ROL::Bundle_U_AS< Real >::eG_ private
Definition at line 29 of file ROL_Bundle_U_AS.hpp.
yG_
template<typename Real > Ptr<Vector<Real> > ROL::Bundle_U_AS< Real >::yG_ private
Definition at line 30 of file ROL_Bundle_U_AS.hpp.
gx_
template<typename Real > Ptr<Vector<Real> > ROL::Bundle_U_AS< Real >::gx_ private
Definition at line 31 of file ROL_Bundle_U_AS.hpp.
ge_
template<typename Real > Ptr<Vector<Real> > ROL::Bundle_U_AS< Real >::ge_ private
Definition at line 32 of file ROL_Bundle_U_AS.hpp.
workingSet_
template<typename Real > std::set<unsigned> ROL::Bundle_U_AS< Real >::workingSet_ private
Definition at line 34 of file ROL_Bundle_U_AS.hpp.
nworkingSet_
template<typename Real > std::set<unsigned> ROL::Bundle_U_AS< Real >::nworkingSet_ private
Definition at line 35 of file ROL_Bundle_U_AS.hpp.
isInitialized_
template<typename Real > bool ROL::Bundle_U_AS< Real >::isInitialized_ private
Definition at line 37 of file ROL_Bundle_U_AS.hpp.
The documentation for this class was generated from the following files:
ROL_Bundle_U_AS.hpp
ROL_Bundle_U_AS_Def.hpp