ROL: ROL::ReduceLinearConstraint< Real > Class Template Reference
ROL::ReduceLinearConstraint< Real > Class Template Reference
User Interface » Functional Interface
Performs null-space transformation for reducible linear equality constraints.
#include <ROL_ReduceLinearConstraint.hpp>
Public Member Functions
virtual ~ReduceLinearConstraint (void)
ReduceLinearConstraint (const Ptr< Constraint< Real > > &lcon, const Ptr< Vector< Real > > &x, const Ptr< const Vector< Real > > &c)
Ptr< Objective< Real > > transform (const Ptr< Objective< Real > > &obj) const
Ptr< Constraint< Real > > transform (const Ptr< Constraint< Real > > &con) const
Ptr< Constraint< Real > > getLinearConstraint (void) const
Ptr< const Vector< Real > > getFeasibleVector (void) const
void project (Vector< Real > &x, const Vector< Real > &y) const
void project (const Ptr< Vector< Real > > &x, const Ptr< const Vector< Real > > &y) const
Private Member Functions
void feasible (const Ptr< const Vector< Real > > &c)
Private Attributes
const Ptr< Constraint< Real > > lcon_
const Ptr< Vector< Real > > x_
const Ptr< VectorController< Real > > storage_
const Ptr< NullSpaceOperator< Real > > nsop_
Detailed Description
template<typename Real>
class ROL::ReduceLinearConstraint< Real >
Performs null-space transformation for reducible linear equality constraints.
Definition at line 29 of file ROL_ReduceLinearConstraint.hpp.
Constructor & Destructor Documentation
~ReduceLinearConstraint()
template<typename Real > virtual ROL::ReduceLinearConstraint< Real >::~ReduceLinearConstraint (void) inline virtual
Definition at line 37 of file ROL_ReduceLinearConstraint.hpp.
ReduceLinearConstraint()
template<typename Real > ROL::ReduceLinearConstraint< Real >::ReduceLinearConstraint (const Ptr< Constraint< Real > > & lcon, const Ptr< Vector< Real > > & x, const Ptr< const Vector< Real > > & c)
Definition at line 16 of file ROL_ReduceLinearConstraint_Def.hpp.
References ROL::ReduceLinearConstraint< Real >::feasible().
Member Function Documentation
transform() [1/2]
template<typename Real > Ptr< Objective< Real > > ROL::ReduceLinearConstraint< Real >::transform (const Ptr< Objective< Real > > & obj) const
Definition at line 26 of file ROL_ReduceLinearConstraint_Def.hpp.
Referenced by ROL::TypeU::Algorithm< Real >::run().
transform() [2/2]
template<typename Real > Ptr< Constraint< Real > > ROL::ReduceLinearConstraint< Real >::transform (const Ptr< Constraint< Real > > & con) const
Definition at line 31 of file ROL_ReduceLinearConstraint_Def.hpp.
getLinearConstraint()
template<typename Real > Ptr< Constraint< Real > > ROL::ReduceLinearConstraint< Real >::getLinearConstraint (void) const
Definition at line 36 of file ROL_ReduceLinearConstraint_Def.hpp.
getFeasibleVector()
template<typename Real > Ptr< const Vector< Real > > ROL::ReduceLinearConstraint< Real >::getFeasibleVector (void) const
Definition at line 41 of file ROL_ReduceLinearConstraint_Def.hpp.
Referenced by ROL::TypeU::Algorithm< Real >::run().
project() [1/2]
template<typename Real > void ROL::ReduceLinearConstraint< Real >::project (Vector< Real > & x, const Vector< Real > & y) const
Definition at line 46 of file ROL_ReduceLinearConstraint_Def.hpp.
Referenced by ROL::TypeU::Algorithm< Real >::run().
project() [2/2]
template<typename Real > void ROL::ReduceLinearConstraint< Real >::project (const Ptr< Vector< Real > > & x, const Ptr< const Vector< Real > > & y) const
Definition at line 52 of file ROL_ReduceLinearConstraint_Def.hpp.
feasible()
template<typename Real > void ROL::ReduceLinearConstraint< Real >::feasible (const Ptr< const Vector< Real > > & c) private
Definition at line 57 of file ROL_ReduceLinearConstraint_Def.hpp.
References ROL::RangeSpaceOperator< Real >::apply().
Referenced by ROL::ReduceLinearConstraint< Real >::ReduceLinearConstraint().
Member Data Documentation
lcon_
template<typename Real > const Ptr<Constraint<Real> > ROL::ReduceLinearConstraint< Real >::lcon_ private
Definition at line 31 of file ROL_ReduceLinearConstraint.hpp.
x_
template<typename Real > const Ptr<Vector<Real> > ROL::ReduceLinearConstraint< Real >::x_ private
Definition at line 32 of file ROL_ReduceLinearConstraint.hpp.
storage_
template<typename Real > const Ptr<VectorController<Real> > ROL::ReduceLinearConstraint< Real >::storage_ private
Definition at line 33 of file ROL_ReduceLinearConstraint.hpp.
nsop_
template<typename Real > const Ptr<NullSpaceOperator<Real> > ROL::ReduceLinearConstraint< Real >::nsop_ private
Definition at line 34 of file ROL_ReduceLinearConstraint.hpp.
The documentation for this class was generated from the following files:
ROL_ReduceLinearConstraint.hpp
ROL_ReduceLinearConstraint_Def.hpp