ROL: H1VectorDual< Real > Class Template Reference
H1VectorDual< Real > Class Template Reference
#include <test_04.hpp>
Public Member Functions
H1VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
Real dot (const ROL::Vector< Real > &x) const override
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const override
Clone to make a new (uninitialized) vector.
const ROL::Vector< Real > & dual () const override
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
H1VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
H1VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
H1VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
H1VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Attributes
ROL::Ptr< BurgersFEM< Real > > fem_
ROL::Ptr< H1VectorPrimal< Real > > dual_vec_
bool isDualInitialized_
ROL::Ptr< std::vector< Real > > vec_
ROL::Ptr< H1VectorPrimal< Real > > prim_vec_
bool isPrimalInitialized_
Detailed Description
template<class Real>
class H1VectorDual< Real >
Definition at line 615 of file example_08.hpp.
Constructor & Destructor Documentation
H1VectorDual() [1/5]
template<class Real > H1VectorDual< Real >::H1VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 631 of file test_04.hpp.
H1VectorDual() [2/5]
template<class Real > H1VectorDual< Real >::H1VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 766 of file example_04.hpp.
H1VectorDual() [3/5]
template<class Real > H1VectorDual< Real >::H1VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 770 of file example_06.hpp.
H1VectorDual() [4/5]
template<class Real > H1VectorDual< Real >::H1VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 774 of file example_07.hpp.
H1VectorDual() [5/5]
template<class Real > H1VectorDual< Real >::H1VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 622 of file example_08.hpp.
Member Function Documentation
dot() [1/5]
template<class Real > Real H1VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline override virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 636 of file test_04.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::fem_, H1VectorDual< Real >::getVector(), and ROL::StdVector< Real, Element >::getVector().
Referenced by H1VectorDual< Real >::norm().
clone() [1/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::clone () const inline override virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 650 of file test_04.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::fem_, and ROL::StdVector< Real, Element >::getVector().
dual() [1/5]
template<class Real > const ROL::Vector< Real > & H1VectorDual< Real >::dual (void) const inline override virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 656 of file test_04.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::dual_vec_, H1VectorDual< Real >::fem_, ROL::StdVector< Real, Element >::getVector(), and H1VectorDual< Real >::isDualInitialized_.
set() [1/3]
template<class Real > void H1VectorDual< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 770 of file example_04.hpp.
References H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
plus() [1/3]
template<class Real > void H1VectorDual< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 776 of file example_04.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
scale() [1/3]
template<class Real > void H1VectorDual< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 785 of file example_04.hpp.
References H1VectorDual< Real >::dimension(), and H1VectorDual< Real >::vec_.
dot() [2/5]
template<class Real > Real H1VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 792 of file example_04.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::fem_, H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
norm() [1/3]
template<class Real > Real H1VectorDual< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 805 of file example_04.hpp.
References H1VectorDual< Real >::dot().
clone() [2/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 811 of file example_04.hpp.
References H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
getVector() [1/6]
template<class Real > ROL::Ptr< const std::vector< Real > > H1VectorDual< Real >::getVector () const inline
Definition at line 815 of file example_04.hpp.
References H1VectorDual< Real >::vec_.
Referenced by H1VectorPrimal< Real >::apply(), H1VectorDual< Real >::dot(), H1VectorDual< Real >::dot(), H1VectorDual< Real >::plus(), and H1VectorDual< Real >::set().
getVector() [2/6]
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorDual< Real >::getVector () inline
Definition at line 819 of file example_04.hpp.
References H1VectorDual< Real >::vec_.
basis() [1/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 823 of file example_04.hpp.
References H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
dimension() [1/3]
template<class Real > int H1VectorDual< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 830 of file example_04.hpp.
References H1VectorDual< Real >::vec_.
Referenced by H1VectorDual< Real >::clone(), H1VectorDual< Real >::dot(), H1VectorDual< Real >::dot(), H1VectorDual< Real >::dual(), H1VectorDual< Real >::plus(), and H1VectorDual< Real >::scale().
dual() [2/5]
template<class Real > const ROL::Vector< Real > & H1VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 834 of file example_04.hpp.
References H1VectorDual< Real >::dual_vec_, H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
apply() [1/3]
template<class Real > Real H1VectorDual< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 842 of file example_04.hpp.
References H1VectorPrimal< Real >::getVector(), and H1VectorDual< Real >::vec_.
set() [2/3]
template<class Real > void H1VectorDual< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 774 of file example_06.hpp.
References H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
plus() [2/3]
template<class Real > void H1VectorDual< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 780 of file example_06.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
scale() [2/3]
template<class Real > void H1VectorDual< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 789 of file example_06.hpp.
References H1VectorDual< Real >::dimension(), and H1VectorDual< Real >::vec_.
dot() [3/5]
template<class Real > Real H1VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 796 of file example_06.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::fem_, H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
norm() [2/3]
template<class Real > Real H1VectorDual< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 809 of file example_06.hpp.
References H1VectorDual< Real >::dot().
clone() [3/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 815 of file example_06.hpp.
References H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
getVector() [3/6]
template<class Real > ROL::Ptr< const std::vector< Real > > H1VectorDual< Real >::getVector () const inline
Definition at line 819 of file example_06.hpp.
References H1VectorDual< Real >::vec_.
getVector() [4/6]
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorDual< Real >::getVector () inline
Definition at line 823 of file example_06.hpp.
References H1VectorDual< Real >::vec_.
basis() [2/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 827 of file example_06.hpp.
References H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
dimension() [2/3]
template<class Real > int H1VectorDual< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 834 of file example_06.hpp.
References H1VectorDual< Real >::vec_.
dual() [3/5]
template<class Real > const ROL::Vector< Real > & H1VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 838 of file example_06.hpp.
References H1VectorDual< Real >::dual_vec_, H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
apply() [2/3]
template<class Real > Real H1VectorDual< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 846 of file example_06.hpp.
References H1VectorPrimal< Real >::getVector(), and H1VectorDual< Real >::vec_.
set() [3/3]
template<class Real > void H1VectorDual< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 778 of file example_07.hpp.
References H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
plus() [3/3]
template<class Real > void H1VectorDual< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 784 of file example_07.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
scale() [3/3]
template<class Real > void H1VectorDual< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 793 of file example_07.hpp.
References H1VectorDual< Real >::dimension(), and H1VectorDual< Real >::vec_.
dot() [4/5]
template<class Real > Real H1VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 800 of file example_07.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::fem_, H1VectorDual< Real >::getVector(), and H1VectorDual< Real >::vec_.
norm() [3/3]
template<class Real > Real H1VectorDual< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 813 of file example_07.hpp.
References H1VectorDual< Real >::dot().
clone() [4/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 819 of file example_07.hpp.
References H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
getVector() [5/6]
template<class Real > ROL::Ptr< const std::vector< Real > > H1VectorDual< Real >::getVector () const inline
Definition at line 823 of file example_07.hpp.
References H1VectorDual< Real >::vec_.
getVector() [6/6]
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorDual< Real >::getVector () inline
Definition at line 827 of file example_07.hpp.
References H1VectorDual< Real >::vec_.
basis() [3/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 831 of file example_07.hpp.
References H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
dimension() [3/3]
template<class Real > int H1VectorDual< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 838 of file example_07.hpp.
References H1VectorDual< Real >::vec_.
dual() [4/5]
template<class Real > const ROL::Vector< Real > & H1VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 842 of file example_07.hpp.
References H1VectorDual< Real >::dual_vec_, H1VectorDual< Real >::fem_, and H1VectorDual< Real >::vec_.
apply() [3/3]
template<class Real > Real H1VectorDual< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 850 of file example_07.hpp.
References H1VectorPrimal< Real >::getVector(), and H1VectorDual< Real >::vec_.
dot() [5/5]
template<class Real > Real H1VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 627 of file example_08.hpp.
References H1VectorDual< Real >::dimension(), H1VectorDual< Real >::fem_, H1VectorDual< Real >::getVector(), and ROL::StdVector< Real, Element >::getVector().
clone() [5/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 641 of file example_08.hpp.
References H1VectorDual< Real >::fem_.
dual() [5/5]
template<class Real > const ROL::Vector< Real > & H1VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 646 of file example_08.hpp.
References ROL::StdVector< Real, Element >::dimension(), H1VectorDual< Real >::fem_, H1VectorDual< Real >::isPrimalInitialized_, and H1VectorDual< Real >::prim_vec_.
Member Data Documentation
fem_
template<class Real > ROL::Ptr< BurgersFEM< Real > > H1VectorDual< Real >::fem_ private
Definition at line 626 of file test_04.hpp.
Referenced by H1VectorDual< Real >::basis(), H1VectorDual< Real >::clone(), H1VectorDual< Real >::clone(), H1VectorDual< Real >::dot(), H1VectorDual< Real >::dot(), H1VectorDual< Real >::dual(), and H1VectorDual< Real >::dual().
dual_vec_
template<class Real > ROL::Ptr< H1VectorPrimal< Real > > H1VectorDual< Real >::dual_vec_ mutable private
Definition at line 627 of file test_04.hpp.
Referenced by H1VectorDual< Real >::dual(), and H1VectorDual< Real >::dual().
isDualInitialized_
template<class Real > bool H1VectorDual< Real >::isDualInitialized_ mutable private
Definition at line 628 of file test_04.hpp.
Referenced by H1VectorDual< Real >::dual().
vec_
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorDual< Real >::vec_ private
Definition at line 760 of file example_04.hpp.
Referenced by H1VectorDual< Real >::apply(), H1VectorDual< Real >::basis(), H1VectorDual< Real >::clone(), H1VectorDual< Real >::dimension(), H1VectorDual< Real >::dot(), H1VectorDual< Real >::dual(), H1VectorDual< Real >::getVector(), H1VectorDual< Real >::getVector(), H1VectorDual< Real >::plus(), H1VectorDual< Real >::scale(), and H1VectorDual< Real >::set().
prim_vec_
template<class Real > ROL::Ptr<H1VectorPrimal<Real> > H1VectorDual< Real >::prim_vec_ mutable private
Definition at line 618 of file example_08.hpp.
Referenced by H1VectorDual< Real >::dual().
isPrimalInitialized_
template<class Real > bool H1VectorDual< Real >::isPrimalInitialized_ mutable private
Definition at line 619 of file example_08.hpp.
Referenced by H1VectorDual< Real >::dual().
The documentation for this class was generated from the following files:
test_04.hpp
example_04.hpp
example_06.hpp
example_07.hpp
example_08.hpp