ROL: ROL::TypeP::ProxGradientAlgorithm< Real > Class Template Reference
ROL::TypeP::ProxGradientAlgorithm< Real > Class Template Reference
Provides an interface to run the proximal gradient algorithm.
#include <ROL_TypeP_ProxGradientAlgorithm.hpp>
Public Member Functions
ProxGradientAlgorithm (ParameterList &list)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout) override
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeP::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, Vector< Real > &px, Vector< Real > &dg, std::ostream &outStream=std::cout)
Private Attributes
int maxit_
Real alpha0_
Real alpha0bnd_
Real rhodec_
Real rhoinc_
Real c1_
Real maxAlpha_
Real t0_
bool useralpha_
bool usePrevAlpha_
bool useAdapt_
bool normAlpha_
bool initProx_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeP::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void pgstep (Vector< Real > &pgiter, Vector< Real > &pgstep, Objective< Real > &nobj, const Vector< Real > &x, const Vector< Real > &dg, Real t, Real &tol) const
Protected Attributes inherited from ROL::TypeP::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeP::ProxGradientAlgorithm< Real >
Provides an interface to run the proximal gradient algorithm.
Definition at line 23 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
Constructor & Destructor Documentation
ProxGradientAlgorithm()
template<typename Real > ROL::TypeP::ProxGradientAlgorithm< Real >::ProxGradientAlgorithm (ParameterList & list)
Definition at line 17 of file ROL_TypeP_ProxGradientAlgorithm_Def.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeP::ProxGradientAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, Vector< Real > & px, Vector< Real > & dg, std::ostream & outStream = std::cout) private
Definition at line 42 of file ROL_TypeP_ProxGradientAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeP::Algorithm< Real >::initialize(), ROL::Objective< Real >::prox(), ROL::Revert, ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeP::ProxGradientAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, std::ostream & outStream = std::cout) override virtual
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeP::Algorithm< Real >.
Definition at line 95 of file ROL_TypeP_ProxGradientAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Revert, ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeP::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeP::ProxGradientAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 260 of file ROL_TypeP_ProxGradientAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeP::ProxGradientAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 293 of file ROL_TypeP_ProxGradientAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeP::ProxGradientAlgorithm< Real >::writeOutput (std::ostream & os, bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 300 of file ROL_TypeP_ProxGradientAlgorithm_Def.hpp.
Member Data Documentation
maxit_
template<typename Real > int ROL::TypeP::ProxGradientAlgorithm< Real >::maxit_ private
Definition at line 25 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
alpha0_
template<typename Real > Real ROL::TypeP::ProxGradientAlgorithm< Real >::alpha0_ private
Definition at line 26 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
alpha0bnd_
template<typename Real > Real ROL::TypeP::ProxGradientAlgorithm< Real >::alpha0bnd_ private
Definition at line 26 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
rhodec_
template<typename Real > Real ROL::TypeP::ProxGradientAlgorithm< Real >::rhodec_ private
Definition at line 26 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
rhoinc_
template<typename Real > Real ROL::TypeP::ProxGradientAlgorithm< Real >::rhoinc_ private
Definition at line 26 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
c1_
template<typename Real > Real ROL::TypeP::ProxGradientAlgorithm< Real >::c1_ private
Definition at line 26 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
maxAlpha_
template<typename Real > Real ROL::TypeP::ProxGradientAlgorithm< Real >::maxAlpha_ private
Definition at line 26 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
t0_
template<typename Real > Real ROL::TypeP::ProxGradientAlgorithm< Real >::t0_ private
Definition at line 26 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
useralpha_
template<typename Real > bool ROL::TypeP::ProxGradientAlgorithm< Real >::useralpha_ private
Definition at line 27 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
usePrevAlpha_
template<typename Real > bool ROL::TypeP::ProxGradientAlgorithm< Real >::usePrevAlpha_ private
Definition at line 27 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
useAdapt_
template<typename Real > bool ROL::TypeP::ProxGradientAlgorithm< Real >::useAdapt_ private
Definition at line 27 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
normAlpha_
template<typename Real > bool ROL::TypeP::ProxGradientAlgorithm< Real >::normAlpha_ private
Definition at line 27 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
initProx_
template<typename Real > bool ROL::TypeP::ProxGradientAlgorithm< Real >::initProx_ private
Definition at line 27 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeP::ProxGradientAlgorithm< Real >::verbosity_ private
Definition at line 28 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeP::ProxGradientAlgorithm< Real >::writeHeader_ private
Definition at line 29 of file ROL_TypeP_ProxGradientAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeP_ProxGradientAlgorithm.hpp
ROL_TypeP_ProxGradientAlgorithm_Def.hpp