ROL: ROL::Step< Real > Class Template Reference
ROL::Step< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps.
#include <ROL_Step.hpp>
Public Member Functions
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step.
virtual void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
virtual std::string printHeader (void) const
Print iterate header.
virtual std::string printName (void) const
Print step name.
virtual std::string print (AlgorithmState< Real > &algo_state, bool printHeader=false) const
Print iterate status.
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Protected Member Functions
ROL::Ptr< StepState< Real > > getState (void)
Private Attributes
ROL::Ptr< StepState< Real > > state_
Detailed Description
template<class Real>
class ROL::Step< Real >
Provides the interface to compute optimization steps.
Definition at line 34 of file ROL_Step.hpp.
Constructor & Destructor Documentation
~Step()
template<class Real > virtual ROL::Step< Real >::~Step () inline virtual
Definition at line 45 of file ROL_Step.hpp.
Step()
template<class Real > ROL::Step< Real >::Step (void) inline
Definition at line 47 of file ROL_Step.hpp.
References ROL::Step< Real >::state_.
Member Function Documentation
getState()
template<class Real > ROL::Ptr< StepState< Real > > ROL::Step< Real >::getState (void) inline protected
Definition at line 39 of file ROL_Step.hpp.
References ROL::Step< Real >::state_.
Referenced by ROL::AugmentedLagrangianStep< Real >::AugmentedLagrangianStep(), ROL::BundleStep< Real >::BundleStep(), ROL::PrimalDualSystemStep< Real >::compute(), ROL::InteriorPointStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::GradientStep< Real >::compute(), ROL::LineSearchStep< Real >::compute(), ROL::NewtonKrylovStep< Real >::compute(), ROL::NewtonStep< Real >::compute(), ROL::NonlinearCGStep< Real >::compute(), ROL::ProjectedNewtonKrylovStep< Real >::compute(), ROL::ProjectedNewtonStep< Real >::compute(), ROL::ProjectedSecantStep< Real >::compute(), ROL::SecantStep< Real >::compute(), ROL::TrustRegionStep< Real >::compute(), ROL::BundleStep< Real >::compute(), ROL::PrimalDualActiveSetStep< Real >::compute(), ROL::PrimalDualActiveSetStep< Real >::computeCriticalityMeasure(), ROL::FletcherStep< Real >::FletcherStep(), ROL::InteriorPointStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::BundleStep< Real >::initialize(), ROL::CompositeStep< Real >::initialize(), ROL::InteriorPointStep< Real >::initialize(), ROL::AugmentedLagrangianStep< Real >::initialize(), ROL::FletcherStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::TrustRegionStep< Real >::initialize(), ROL::PrimalDualActiveSetStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep(), ROL::TrustRegionStep< Real >::parseParameterList(), ROL::PrimalDualSystemStep< Real >::update(), ROL::InteriorPointStep< Real >::update(), ROL::LineSearchStep< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::NewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonKrylovStep< Real >::update(), ROL::ProjectedNewtonStep< Real >::update(), ROL::ProjectedSecantStep< Real >::update(), ROL::TrustRegionStep< Real >::update(), ROL::BundleStep< Real >::update(), ROL::GradientStep< Real >::update(), ROL::NewtonStep< Real >::update(), ROL::NonlinearCGStep< Real >::update(), ROL::PrimalDualActiveSetStep< Real >::update(), ROL::SecantStep< Real >::update(), ROL::CompositeStep< Real >::update(), ROL::InteriorPointStep< Real >::update(), ROL::AugmentedLagrangianStep< Real >::update(), ROL::FletcherStep< Real >::update(), ROL::InteriorPointStep< Real >::update(), ROL::MoreauYosidaPenaltyStep< Real >::update(), ROL::TrustRegionStep< Real >::updateGradient(), ROL::MoreauYosidaPenaltyStep< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
initialize() [1/4]
template<class Real > virtual void ROL::Step< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with bound constraint.
Reimplemented in ROL::InteriorPointStep< Real >, ROL::MoreauYosidaPenaltyStep< Real >, and ROL::BundleStep< Real >.
Definition at line 54 of file ROL_Step.hpp.
References ROL::Step< Real >::initialize().
Referenced by ROL::PrimalDualSystemStep< Real >::initialize(), ROL::BundleStep< Real >::initialize(), ROL::Step< Real >::initialize(), ROL::NewtonKrylovStep< Real >::initialize(), ROL::ProjectedNewtonKrylovStep< Real >::initialize(), ROL::ProjectedNewtonStep< Real >::initialize(), ROL::ProjectedSecantStep< Real >::initialize(), and ROL::SecantStep< Real >::initialize().
initialize() [2/4]
template<class Real > virtual void ROL::Step< Real >::initialize (Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with bound constraint.
Reimplemented in ROL::LineSearchStep< Real >, ROL::NewtonKrylovStep< Real >, ROL::ProjectedNewtonKrylovStep< Real >, ROL::ProjectedNewtonStep< Real >, ROL::ProjectedSecantStep< Real >, ROL::TrustRegionStep< Real >, ROL::PrimalDualActiveSetStep< Real >, and ROL::SecantStep< Real >.
Definition at line 62 of file ROL_Step.hpp.
References ROL::Vector< Real >::clone(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::BoundConstraint< Real >::isActivated(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::BoundConstraint< Real >::project(), ROL::Step< Real >::state_, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), ROL::AlgorithmState< Real >::value, and zero.
initialize() [3/4]
template<class Real > virtual void ROL::Step< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality constraint.
Reimplemented in ROL::AugmentedLagrangianStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, and ROL::InteriorPointStep< Real >.
Definition at line 95 of file ROL_Step.hpp.
initialize() [4/4]
template<class Real > virtual void ROL::Step< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality constraint.
Reimplemented in ROL::PrimalDualSystemStep< Real >, ROL::AugmentedLagrangianStep< Real >, ROL::FletcherStep< Real >, ROL::InteriorPointStep< Real >, and ROL::MoreauYosidaPenaltyStep< Real >.
Definition at line 102 of file ROL_Step.hpp.
compute() [1/3]
template<class Real > virtual void ROL::Step< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented in ROL::GradientStep< Real >, ROL::InteriorPointStep< Real >, ROL::LineSearchStep< Real >, ROL::MoreauYosidaPenaltyStep< Real >, ROL::NewtonKrylovStep< Real >, ROL::NewtonStep< Real >, ROL::NonlinearCGStep< Real >, ROL::ProjectedNewtonKrylovStep< Real >, ROL::ProjectedNewtonStep< Real >, ROL::ProjectedSecantStep< Real >, ROL::SecantStep< Real >, ROL::TrustRegionStep< Real >, ROL::AugmentedLagrangianStep< Real >, ROL::BundleStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, and ROL::PrimalDualActiveSetStep< Real >.
Definition at line 109 of file ROL_Step.hpp.
Referenced by main().
update() [1/3]
template<class Real > virtual void ROL::Step< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented in ROL::InteriorPointStep< Real >, ROL::LineSearchStep< Real >, ROL::MoreauYosidaPenaltyStep< Real >, ROL::NewtonKrylovStep< Real >, ROL::ProjectedNewtonKrylovStep< Real >, ROL::ProjectedNewtonStep< Real >, ROL::ProjectedSecantStep< Real >, ROL::TrustRegionStep< Real >, ROL::AugmentedLagrangianStep< Real >, ROL::BundleStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, ROL::GradientStep< Real >, ROL::NewtonStep< Real >, ROL::NonlinearCGStep< Real >, ROL::PrimalDualActiveSetStep< Real >, and ROL::SecantStep< Real >.
Definition at line 117 of file ROL_Step.hpp.
Referenced by main().
compute() [2/3]
template<class Real > virtual void ROL::Step< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality constraints).
Reimplemented in ROL::AugmentedLagrangianStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, and ROL::InteriorPointStep< Real >.
Definition at line 125 of file ROL_Step.hpp.
update() [2/3]
template<class Real > virtual void ROL::Step< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality constraints).
Reimplemented in ROL::AugmentedLagrangianStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, and ROL::InteriorPointStep< Real >.
Definition at line 133 of file ROL_Step.hpp.
compute() [3/3]
template<class Real > virtual void ROL::Step< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality constraints).
Reimplemented in ROL::PrimalDualSystemStep< Real >, ROL::AugmentedLagrangianStep< Real >, ROL::FletcherStep< Real >, ROL::InteriorPointStep< Real >, and ROL::MoreauYosidaPenaltyStep< Real >.
Definition at line 141 of file ROL_Step.hpp.
update() [3/3]
template<class Real > virtual void ROL::Step< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality constraints).
Reimplemented in ROL::PrimalDualSystemStep< Real >, ROL::AugmentedLagrangianStep< Real >, ROL::FletcherStep< Real >, ROL::InteriorPointStep< Real >, and ROL::MoreauYosidaPenaltyStep< Real >.
Definition at line 150 of file ROL_Step.hpp.
printHeader()
template<class Real > virtual std::string ROL::Step< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented in ROL::AugmentedLagrangianStep< Real >, ROL::BundleStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, ROL::GradientStep< Real >, ROL::InteriorPointStep< Real >, ROL::LineSearchStep< Real >, ROL::MoreauYosidaPenaltyStep< Real >, ROL::NewtonKrylovStep< Real >, ROL::NewtonStep< Real >, ROL::NonlinearCGStep< Real >, ROL::PrimalDualActiveSetStep< Real >, ROL::ProjectedNewtonKrylovStep< Real >, ROL::ProjectedNewtonStep< Real >, ROL::ProjectedSecantStep< Real >, ROL::SecantStep< Real >, and ROL::TrustRegionStep< Real >.
Definition at line 159 of file ROL_Step.hpp.
Referenced by main().
printName()
template<class Real > virtual std::string ROL::Step< Real >::printName (void) const inline virtual
Print step name.
Reimplemented in ROL::AugmentedLagrangianStep< Real >, ROL::BundleStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, ROL::GradientStep< Real >, ROL::InteriorPointStep< Real >, ROL::LineSearchStep< Real >, ROL::MoreauYosidaPenaltyStep< Real >, ROL::NewtonKrylovStep< Real >, ROL::NewtonStep< Real >, ROL::NonlinearCGStep< Real >, ROL::PrimalDualActiveSetStep< Real >, ROL::ProjectedNewtonKrylovStep< Real >, ROL::ProjectedNewtonStep< Real >, ROL::ProjectedSecantStep< Real >, ROL::SecantStep< Real >, and ROL::TrustRegionStep< Real >.
Definition at line 165 of file ROL_Step.hpp.
Referenced by main().
print()
template<class Real > virtual std::string ROL::Step< Real >::print (AlgorithmState< Real > & algo_state, bool printHeader = false) const inline virtual
Print iterate status.
Reimplemented in ROL::AugmentedLagrangianStep< Real >, ROL::CompositeStep< Real >, ROL::FletcherStep< Real >, ROL::InteriorPointStep< Real >, ROL::MoreauYosidaPenaltyStep< Real >, ROL::BundleStep< Real >, ROL::GradientStep< Real >, ROL::LineSearchStep< Real >, ROL::NewtonKrylovStep< Real >, ROL::NewtonStep< Real >, ROL::NonlinearCGStep< Real >, ROL::PrimalDualActiveSetStep< Real >, ROL::ProjectedNewtonKrylovStep< Real >, ROL::ProjectedNewtonStep< Real >, ROL::ProjectedSecantStep< Real >, ROL::SecantStep< Real >, and ROL::TrustRegionStep< Real >.
Definition at line 171 of file ROL_Step.hpp.
Referenced by main().
getStepState()
template<class Real > const ROL::Ptr< const StepState< Real > > ROL::Step< Real >::getStepState (void) const inline
Get state for step object.
Definition at line 177 of file ROL_Step.hpp.
References ROL::Step< Real >::state_.
Referenced by ROL::BundleStep< Real >::print(), ROL::LineSearchStep< Real >::print(), ROL::TrustRegionStep< Real >::print(), and ROL::FletcherStep< Real >::update().
reset()
template<class Real > void ROL::Step< Real >::reset (const Real searchSize = 1.0) inline
Get state for step object.
Definition at line 183 of file ROL_Step.hpp.
References ROL::Step< Real >::state_.
Member Data Documentation
state_
template<class Real > ROL::Ptr<StepState<Real> > ROL::Step< Real >::state_ private
Definition at line 36 of file ROL_Step.hpp.
Referenced by ROL::Step< Real >::getState(), ROL::Step< Real >::getStepState(), ROL::Step< Real >::initialize(), ROL::Step< Real >::reset(), and ROL::Step< Real >::Step().
The documentation for this class was generated from the following file:
ROL_Step.hpp