ROL: ROL::MoreauYosidaPenaltyStep< Real > Class Template Reference
ROL::MoreauYosidaPenaltyStep< Real > Class Template Reference
Optimization Steps
Implements the computation of optimization steps using Moreau-Yosida regularized bound constraints.
#include <ROL_MoreauYosidaPenaltyStep.hpp>
Public Member Functions
~MoreauYosidaPenaltyStep ()
MoreauYosidaPenaltyStep (ROL::ParameterList &parlist)
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step without equality constraint.
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality and bound constraints).
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step for bound constraints.
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality and bound constraints).
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, for bound constraints.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool pHeader=false) const
Print iterate status.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Member Functions
void updateState (const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
void updateState (const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Private Attributes
ROL::Ptr< StatusTest< Real > > status_
ROL::Ptr< Step< Real > > step_
ROL::Ptr< Algorithm< Real > > algo_
ROL::Ptr< Vector< Real > > x_
ROL::Ptr< Vector< Real > > g_
ROL::Ptr< Vector< Real > > l_
ROL::Ptr< BoundConstraint< Real > > bnd_
Real compViolation_
Real gLnorm_
Real tau_
bool print_
bool updatePenalty_
ROL::ParameterList parlist_
int subproblemIter_
bool hasEquality_
EStep stepType_
std::string stepname_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::MoreauYosidaPenaltyStep< Real >
Implements the computation of optimization steps using Moreau-Yosida regularized bound constraints.
To describe the generalized Moreau-Yosida penalty method, we consider the following abstract setting. Suppose \(\mathcal{X}\) is a Hilbert space of functions mapping \(\Xi\) to \(\mathbb{R}\). For example, \(\Xi\subset\mathbb{R}^n\) and \(\mathcal{X}=L^2(\Xi)\) or \(\Xi = \{1,\ldots,n\}\) and \(\mathcal{X}=\mathbb{R}^n\). We assume \(f:\mathcal{X}\to\mathbb{R}\) is twice-continuously Fréchet differentiable and \(a,\,b\in\mathcal{X}\) with \(a\le b\) almost everywhere in \(\Xi\). Note that the generalized Moreau-Yosida penalty method will also work with secant approximations of the Hessian.
The generalized Moreau-Yosida penalty method is a proveably convergent algorithm for convex optimization problems and may not converge for general nonlinear, nonconvex problems. The algorithm solves
\[ \min_x \quad f(x) \quad \text{s.t.} \quad c(x) = 0, \quad a \le x \le b. \]
We can respresent the bound constraints using the indicator function \(\iota_{[a,b]}(x) = 0\) if \(a \le x \le b\) and equals \(\infty\) otherwise. Using this indicator function, we can write our optimization problem as the (nonsmooth) equality constrained program
\[ \min_x \quad f(x) + \iota_{[a,b]}(x) \quad \text{s.t.}\quad c(x) = 0. \]
Since the indicator function is not continuously Fréchet differentiable, we cannot apply our existing algorithms (such as, Composite Step SQP) to the above equality constrained problem. To circumvent this issue, we smooth the indicator function using generalized Moreau-Yosida regularization, i.e., we replace \(\iota_{[a,b]}\) in the objective function with
\[ \varphi(x,\mu,c) = \inf_y\; \{\; \iota_{[a,b]}(x-y) + \langle \mu, y\rangle_{\mathcal{X}} + \frac{c}{2}\|y\|_{\mathcal{X}}^2 \;\}. \]
One can show that \(\varphi(\cdot,\mu,c)\) for any \(\mu\in\mathcal{X}\) and \(c > 0\) is continuously Fréchet differentiable with respect to \(x\). Thus, using this penalty, Step::compute solves the following subproblem: given \(c_k>0\) and \(\mu_k\in\mathcal{X}\), determine \(x_k\in\mathcal{X}\) that solves
\[ \min_{x} \quad f(x) + \varphi(x,\mu_k,c_k)\quad\text{s.t.} c(x) = 0. \]
The multipliers \(\mu_k\) are then updated in Step::update as \(\mu_{k+1} = \nabla_x\varphi(x_k,\mu_k,c_k)\) and \(c_k\) is potentially increased (although this is not always necessary).
For more information on this method see:
D. P. Bertsekas. "Approximations Procedures Based on the Method of Multipliers." Journal of Optimization Theory and Applications, Vol. 23(4), 1977.
K. Ito, K. Kunisch. "Augmented Lagrangian Methods for Nonsmooth, Convex, Optimization in Hilbert Space." Nonlinear Analysis, 2000.
Definition at line 94 of file ROL_MoreauYosidaPenaltyStep.hpp.
Constructor & Destructor Documentation
~MoreauYosidaPenaltyStep()
template<class Real > ROL::MoreauYosidaPenaltyStep< Real >::~MoreauYosidaPenaltyStep () inline
Definition at line 174 of file ROL_MoreauYosidaPenaltyStep.hpp.
MoreauYosidaPenaltyStep()
template<class Real > ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep (ROL::ParameterList & parlist) inline
Definition at line 176 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::Step< Real >::getState(), ROL::MoreauYosidaPenaltyStep< Real >::parlist_, ROL::MoreauYosidaPenaltyStep< Real >::print_, ROL::MoreauYosidaPenaltyStep< Real >::stepname_, ROL::MoreauYosidaPenaltyStep< Real >::stepType_, ROL::StringToEStep(), ROL::MoreauYosidaPenaltyStep< Real >::tau_, and ROL::MoreauYosidaPenaltyStep< Real >::updatePenalty_.
Member Function Documentation
updateState() [1/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::updateState (const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline private
Definition at line 117 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::AlgorithmState< Real >::cnorm, ROL::MoreauYosidaPenaltyStep< Real >::compViolation_, ROL::MoreauYosidaPenaltyStep< Real >::g_, ROL::Step< Real >::getState(), ROL::MoreauYosidaPenaltyStep< Real >::gLnorm_, ROL::AlgorithmState< Real >::gnorm, ROL::MoreauYosidaPenalty< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::MoreauYosidaPenalty< Real >::testComplementarity(), ROL::MoreauYosidaPenalty< Real >::update(), ROL::Constraint< Real >::update(), ROL::MoreauYosidaPenalty< Real >::value(), ROL::Constraint< Real >::value(), and ROL::AlgorithmState< Real >::value.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::update(), and ROL::MoreauYosidaPenaltyStep< Real >::update().
updateState() [2/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::updateState (const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline private
Definition at line 145 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::AlgorithmState< Real >::cnorm, ROL::MoreauYosidaPenaltyStep< Real >::compViolation_, ROL::Step< Real >::getState(), ROL::MoreauYosidaPenaltyStep< Real >::gLnorm_, ROL::AlgorithmState< Real >::gnorm, ROL::MoreauYosidaPenalty< Real >::gradient(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::MoreauYosidaPenalty< Real >::testComplementarity(), ROL::MoreauYosidaPenalty< Real >::update(), ROL::MoreauYosidaPenalty< Real >::value(), and ROL::AlgorithmState< Real >::value.
initialize() [1/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 204 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::Vector< Real >::clone(), ROL::MoreauYosidaPenaltyStep< Real >::g_, ROL::Step< Real >::getState(), ROL::MoreauYosidaPenaltyStep< Real >::hasEquality_, ROL::BoundConstraint< Real >::isActivated(), ROL::MoreauYosidaPenaltyStep< Real >::l_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::BoundConstraint< Real >::project(), ROL::MoreauYosidaPenaltyStep< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::x_.
initialize() [2/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Initialize step without equality constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 230 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::MoreauYosidaPenaltyStep< Real >::bnd_, ROL::Vector< Real >::clone(), ROL::MoreauYosidaPenaltyStep< Real >::g_, ROL::Step< Real >::getState(), ROL::BoundConstraint< Real >::isActivated(), ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::BoundConstraint< Real >::project(), ROL::MoreauYosidaPenaltyStep< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::x_.
compute() [1/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality and bound constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 256 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::MoreauYosidaPenaltyStep< Real >::algo_, ROL::Vector< Real >::axpy(), ROL::Step< Real >::getState(), ROL::MoreauYosidaPenaltyStep< Real >::l_, ROL::MoreauYosidaPenaltyStep< Real >::parlist_, ROL::MoreauYosidaPenaltyStep< Real >::print_, ROL::Vector< Real >::set(), ROL::MoreauYosidaPenaltyStep< Real >::status_, ROL::MoreauYosidaPenaltyStep< Real >::step_, ROL::STEP_AUGMENTEDLAGRANGIAN, ROL::STEP_COMPOSITESTEP, ROL::STEP_FLETCHER, ROL::MoreauYosidaPenaltyStep< Real >::stepname_, ROL::MoreauYosidaPenaltyStep< Real >::stepType_, ROL::MoreauYosidaPenaltyStep< Real >::subproblemIter_, and ROL::MoreauYosidaPenaltyStep< Real >::x_.
compute() [2/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step for bound constraints.
Reimplemented from ROL::Step< Real >.
Definition at line 294 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::MoreauYosidaPenaltyStep< Real >::algo_, ROL::Vector< Real >::axpy(), ROL::MoreauYosidaPenaltyStep< Real >::bnd_, ROL::MoreauYosidaPenaltyStep< Real >::parlist_, ROL::MoreauYosidaPenaltyStep< Real >::print_, ROL::Vector< Real >::set(), ROL::MoreauYosidaPenaltyStep< Real >::status_, ROL::MoreauYosidaPenaltyStep< Real >::step_, ROL::STEP_BUNDLE, ROL::STEP_LINESEARCH, ROL::MoreauYosidaPenaltyStep< Real >::stepType_, ROL::MoreauYosidaPenaltyStep< Real >::subproblemIter_, and ROL::MoreauYosidaPenaltyStep< Real >::x_.
update() [1/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality and bound constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 322 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::MoreauYosidaPenaltyStep< Real >::algo_, ROL::MoreauYosidaPenalty< Real >::getNumberFunctionEvaluations(), ROL::MoreauYosidaPenalty< Real >::getNumberGradientEvaluations(), ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::MoreauYosidaPenaltyStep< Real >::l_, ROL::AlgorithmState< Real >::lagmultVec, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::set(), ROL::AlgorithmState< Real >::snorm, ROL::MoreauYosidaPenaltyStep< Real >::subproblemIter_, ROL::MoreauYosidaPenaltyStep< Real >::tau_, ROL::MoreauYosidaPenalty< Real >::update(), ROL::Constraint< Real >::update(), ROL::MoreauYosidaPenalty< Real >::updateMultipliers(), ROL::MoreauYosidaPenaltyStep< Real >::updatePenalty_, and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
update() [2/2]
template<class Real > void ROL::MoreauYosidaPenaltyStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, for bound constraints.
Reimplemented from ROL::Step< Real >.
Definition at line 355 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::MoreauYosidaPenaltyStep< Real >::algo_, ROL::MoreauYosidaPenalty< Real >::getNumberFunctionEvaluations(), ROL::MoreauYosidaPenalty< Real >::getNumberGradientEvaluations(), ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::AlgorithmState< Real >::snorm, ROL::MoreauYosidaPenaltyStep< Real >::tau_, ROL::MoreauYosidaPenalty< Real >::update(), ROL::MoreauYosidaPenalty< Real >::updateMultipliers(), ROL::MoreauYosidaPenaltyStep< Real >::updatePenalty_, and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
printHeader()
template<class Real > std::string ROL::MoreauYosidaPenaltyStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 382 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::MoreauYosidaPenaltyStep< Real >::hasEquality_.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::print().
printName()
template<class Real > std::string ROL::MoreauYosidaPenaltyStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 406 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::print().
print()
template<class Real > std::string ROL::MoreauYosidaPenaltyStep< Real >::print (AlgorithmState< Real > & algo_state, bool pHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 415 of file ROL_MoreauYosidaPenaltyStep.hpp.
References ROL::AlgorithmState< Real >::cnorm, ROL::MoreauYosidaPenaltyStep< Real >::compViolation_, ROL::MoreauYosidaPenaltyStep< Real >::gLnorm_, ROL::MoreauYosidaPenaltyStep< Real >::hasEquality_, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::MoreauYosidaPenaltyStep< Real >::printHeader(), ROL::MoreauYosidaPenaltyStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, ROL::MoreauYosidaPenaltyStep< Real >::subproblemIter_, and ROL::AlgorithmState< Real >::value.
Member Data Documentation
status_
template<class Real > ROL::Ptr<StatusTest<Real> > ROL::MoreauYosidaPenaltyStep< Real >::status_ private
Definition at line 96 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), and ROL::MoreauYosidaPenaltyStep< Real >::compute().
step_
template<class Real > ROL::Ptr<Step<Real> > ROL::MoreauYosidaPenaltyStep< Real >::step_ private
Definition at line 97 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), and ROL::MoreauYosidaPenaltyStep< Real >::compute().
algo_
template<class Real > ROL::Ptr<Algorithm<Real> > ROL::MoreauYosidaPenaltyStep< Real >::algo_ private
Definition at line 98 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::update(), and ROL::MoreauYosidaPenaltyStep< Real >::update().
x_
template<class Real > ROL::Ptr<Vector<Real> > ROL::MoreauYosidaPenaltyStep< Real >::x_ private
Definition at line 99 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), and ROL::MoreauYosidaPenaltyStep< Real >::initialize().
g_
template<class Real > ROL::Ptr<Vector<Real> > ROL::MoreauYosidaPenaltyStep< Real >::g_ private
Definition at line 100 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
l_
template<class Real > ROL::Ptr<Vector<Real> > ROL::MoreauYosidaPenaltyStep< Real >::l_ private
Definition at line 101 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::initialize(), and ROL::MoreauYosidaPenaltyStep< Real >::update().
bnd_
template<class Real > ROL::Ptr<BoundConstraint<Real> > ROL::MoreauYosidaPenaltyStep< Real >::bnd_ private
Definition at line 102 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), and ROL::MoreauYosidaPenaltyStep< Real >::initialize().
compViolation_
template<class Real > Real ROL::MoreauYosidaPenaltyStep< Real >::compViolation_ private
Definition at line 104 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::print(), ROL::MoreauYosidaPenaltyStep< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
gLnorm_
template<class Real > Real ROL::MoreauYosidaPenaltyStep< Real >::gLnorm_ private
Definition at line 105 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::print(), ROL::MoreauYosidaPenaltyStep< Real >::updateState(), and ROL::MoreauYosidaPenaltyStep< Real >::updateState().
tau_
template<class Real > Real ROL::MoreauYosidaPenaltyStep< Real >::tau_ private
Definition at line 106 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep(), ROL::MoreauYosidaPenaltyStep< Real >::update(), and ROL::MoreauYosidaPenaltyStep< Real >::update().
print_
template<class Real > bool ROL::MoreauYosidaPenaltyStep< Real >::print_ private
Definition at line 107 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), and ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep().
updatePenalty_
template<class Real > bool ROL::MoreauYosidaPenaltyStep< Real >::updatePenalty_ private
Definition at line 108 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep(), ROL::MoreauYosidaPenaltyStep< Real >::update(), and ROL::MoreauYosidaPenaltyStep< Real >::update().
parlist_
template<class Real > ROL::ParameterList ROL::MoreauYosidaPenaltyStep< Real >::parlist_ private
Definition at line 110 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), and ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep().
subproblemIter_
template<class Real > int ROL::MoreauYosidaPenaltyStep< Real >::subproblemIter_ private
Definition at line 111 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::print(), and ROL::MoreauYosidaPenaltyStep< Real >::update().
hasEquality_
template<class Real > bool ROL::MoreauYosidaPenaltyStep< Real >::hasEquality_ private
Definition at line 112 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::initialize(), ROL::MoreauYosidaPenaltyStep< Real >::print(), and ROL::MoreauYosidaPenaltyStep< Real >::printHeader().
stepType_
template<class Real > EStep ROL::MoreauYosidaPenaltyStep< Real >::stepType_ private
Definition at line 114 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), ROL::MoreauYosidaPenaltyStep< Real >::compute(), and ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep().
stepname_
template<class Real > std::string ROL::MoreauYosidaPenaltyStep< Real >::stepname_ private
Definition at line 115 of file ROL_MoreauYosidaPenaltyStep.hpp.
Referenced by ROL::MoreauYosidaPenaltyStep< Real >::compute(), and ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep().
The documentation for this class was generated from the following files:
ROL_AugmentedLagrangianStep.hpp
ROL_MoreauYosidaPenaltyStep.hpp