ROL: ROL::RiskNeutralObjective< Real > Class Template Reference
ROL::RiskNeutralObjective< Real > Class Template Reference
#include <ROL_RiskNeutralObjective.hpp>
Public Member Functions
RiskNeutralObjective (const Ptr< Objective< Real > > &pObj, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler, const Ptr< SampleGenerator< Real > > &hsampler, const bool storage=true)
RiskNeutralObjective (const Ptr< Objective< Real > > &pObj, const Ptr< SampleGenerator< Real > > &vsampler, const Ptr< SampleGenerator< Real > > &gsampler, const bool storage=true)
RiskNeutralObjective (const Ptr< Objective< Real > > &pObj, const Ptr< SampleGenerator< Real > > &sampler, const bool storage=true)
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Member Functions
void initialize (const Vector< Real > &x)
void getValue (Real &val, const Vector< Real > &x, const std::vector< Real > &param, Real &tol)
void getGradient (Vector< Real > &g, const Vector< Real > &x, const std::vector< Real > &param, Real &tol)
void getHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, const std::vector< Real > &param, Real &tol)
Private Attributes
Ptr< Objective< Real > > ParametrizedObjective_
Ptr< SampleGenerator< Real > > ValueSampler_
Ptr< SampleGenerator< Real > > GradientSampler_
Ptr< SampleGenerator< Real > > HessianSampler_
Real value_
Ptr< Vector< Real > > gradient_
Ptr< Vector< Real > > pointDual_
Ptr< Vector< Real > > sumDual_
bool firstUpdate_
bool storage_
Ptr< ScalarController< Real > > value_storage_
Ptr< VectorController< Real > > gradient_storage_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::RiskNeutralObjective< Real >
Definition at line 22 of file ROL_RiskNeutralObjective.hpp.
Constructor & Destructor Documentation
RiskNeutralObjective() [1/3]
template<class Real > ROL::RiskNeutralObjective< Real >::RiskNeutralObjective (const Ptr< Objective< Real > > & pObj, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler, const Ptr< SampleGenerator< Real > > & hsampler, const bool storage = true) inline
Definition at line 89 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::gradient_storage_, and ROL::RiskNeutralObjective< Real >::value_storage_.
RiskNeutralObjective() [2/3]
template<class Real > ROL::RiskNeutralObjective< Real >::RiskNeutralObjective (const Ptr< Objective< Real > > & pObj, const Ptr< SampleGenerator< Real > > & vsampler, const Ptr< SampleGenerator< Real > > & gsampler, const bool storage = true) inline
Definition at line 101 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::gradient_storage_, and ROL::RiskNeutralObjective< Real >::value_storage_.
RiskNeutralObjective() [3/3]
template<class Real > ROL::RiskNeutralObjective< Real >::RiskNeutralObjective (const Ptr< Objective< Real > > & pObj, const Ptr< SampleGenerator< Real > > & sampler, const bool storage = true) inline
Definition at line 112 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::gradient_storage_, and ROL::RiskNeutralObjective< Real >::value_storage_.
Member Function Documentation
initialize()
template<class Real > void ROL::RiskNeutralObjective< Real >::initialize (const Vector< Real > & x) inline private
Definition at line 42 of file ROL_RiskNeutralObjective.hpp.
References ROL::Vector< Real >::dual(), ROL::RiskNeutralObjective< Real >::firstUpdate_, ROL::RiskNeutralObjective< Real >::gradient_, ROL::RiskNeutralObjective< Real >::pointDual_, and ROL::RiskNeutralObjective< Real >::sumDual_.
Referenced by ROL::RiskNeutralObjective< Real >::gradient(), ROL::RiskNeutralObjective< Real >::hessVec(), ROL::RiskNeutralObjective< Real >::update(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::value().
getValue()
template<class Real > void ROL::RiskNeutralObjective< Real >::getValue (Real & val, const Vector< Real > & x, const std::vector< Real > & param, Real & tol) inline private
Definition at line 51 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::ParametrizedObjective_, ROL::RiskNeutralObjective< Real >::storage_, and ROL::RiskNeutralObjective< Real >::value_storage_.
Referenced by ROL::RiskNeutralObjective< Real >::value().
getGradient()
template<class Real > void ROL::RiskNeutralObjective< Real >::getGradient (Vector< Real > & g, const Vector< Real > & x, const std::vector< Real > & param, Real & tol) inline private
Definition at line 66 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::gradient_storage_, ROL::RiskNeutralObjective< Real >::ParametrizedObjective_, and ROL::RiskNeutralObjective< Real >::storage_.
Referenced by ROL::RiskNeutralObjective< Real >::gradient().
getHessVec()
template<class Real > void ROL::RiskNeutralObjective< Real >::getHessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, const std::vector< Real > & param, Real & tol) inline private
Definition at line 81 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::ParametrizedObjective_.
Referenced by ROL::RiskNeutralObjective< Real >::hessVec().
update() [1/2]
template<class Real > void ROL::RiskNeutralObjective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 122 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::gradient_, ROL::RiskNeutralObjective< Real >::gradient_storage_, ROL::RiskNeutralObjective< Real >::GradientSampler_, ROL::RiskNeutralObjective< Real >::HessianSampler_, ROL::RiskNeutralObjective< Real >::initialize(), ROL::RiskNeutralObjective< Real >::ParametrizedObjective_, ROL::Revert, ROL::RiskNeutralObjective< Real >::storage_, ROL::Trial, ROL::RiskNeutralObjective< Real >::value_, ROL::RiskNeutralObjective< Real >::value_storage_, and ROL::RiskNeutralObjective< Real >::ValueSampler_.
update() [2/2]
template<class Real > void ROL::RiskNeutralObjective< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 139 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::gradient_, ROL::RiskNeutralObjective< Real >::gradient_storage_, ROL::RiskNeutralObjective< Real >::GradientSampler_, ROL::RiskNeutralObjective< Real >::HessianSampler_, ROL::RiskNeutralObjective< Real >::initialize(), ROL::RiskNeutralObjective< Real >::ParametrizedObjective_, ROL::RiskNeutralObjective< Real >::storage_, ROL::RiskNeutralObjective< Real >::value_, ROL::RiskNeutralObjective< Real >::value_storage_, and ROL::RiskNeutralObjective< Real >::ValueSampler_.
value()
template<class Real > Real ROL::RiskNeutralObjective< Real >::value (const Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 158 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::getValue(), ROL::RiskNeutralObjective< Real >::initialize(), ROL::RiskNeutralObjective< Real >::value_, and ROL::RiskNeutralObjective< Real >::ValueSampler_.
gradient()
template<class Real > void ROL::RiskNeutralObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 179 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::getGradient(), ROL::RiskNeutralObjective< Real >::gradient_, ROL::RiskNeutralObjective< Real >::GradientSampler_, ROL::RiskNeutralObjective< Real >::initialize(), ROL::RiskNeutralObjective< Real >::pointDual_, ROL::Vector< Real >::set(), ROL::RiskNeutralObjective< Real >::sumDual_, and ROL::Vector< Real >::zero().
hessVec()
template<class Real > void ROL::RiskNeutralObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 205 of file ROL_RiskNeutralObjective.hpp.
References ROL::RiskNeutralObjective< Real >::getHessVec(), ROL::RiskNeutralObjective< Real >::HessianSampler_, ROL::RiskNeutralObjective< Real >::initialize(), ROL::RiskNeutralObjective< Real >::pointDual_, ROL::RiskNeutralObjective< Real >::sumDual_, and ROL::Vector< Real >::zero().
precond()
template<class Real > void ROL::RiskNeutralObjective< Real >::precond (Vector< Real > & Pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 216 of file ROL_RiskNeutralObjective.hpp.
References ROL::Vector< Real >::dual(), and ROL::Vector< Real >::set().
Member Data Documentation
ParametrizedObjective_
template<class Real > Ptr<Objective<Real> > ROL::RiskNeutralObjective< Real >::ParametrizedObjective_ private
Definition at line 24 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::getGradient(), ROL::RiskNeutralObjective< Real >::getHessVec(), ROL::RiskNeutralObjective< Real >::getValue(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::update().
ValueSampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::RiskNeutralObjective< Real >::ValueSampler_ private
Definition at line 25 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::update(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::value().
GradientSampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::RiskNeutralObjective< Real >::GradientSampler_ private
Definition at line 26 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::gradient(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::update().
HessianSampler_
template<class Real > Ptr<SampleGenerator<Real> > ROL::RiskNeutralObjective< Real >::HessianSampler_ private
Definition at line 27 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::hessVec(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::update().
value_
template<class Real > Real ROL::RiskNeutralObjective< Real >::value_ private
Definition at line 29 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::update(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::value().
gradient_
template<class Real > Ptr<Vector<Real> > ROL::RiskNeutralObjective< Real >::gradient_ private
Definition at line 30 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::gradient(), ROL::RiskNeutralObjective< Real >::initialize(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::update().
pointDual_
template<class Real > Ptr<Vector<Real> > ROL::RiskNeutralObjective< Real >::pointDual_ private
Definition at line 31 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::gradient(), ROL::RiskNeutralObjective< Real >::hessVec(), and ROL::RiskNeutralObjective< Real >::initialize().
sumDual_
template<class Real > Ptr<Vector<Real> > ROL::RiskNeutralObjective< Real >::sumDual_ private
Definition at line 32 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::gradient(), ROL::RiskNeutralObjective< Real >::hessVec(), and ROL::RiskNeutralObjective< Real >::initialize().
firstUpdate_
template<class Real > bool ROL::RiskNeutralObjective< Real >::firstUpdate_ private
Definition at line 34 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::initialize().
storage_
template<class Real > bool ROL::RiskNeutralObjective< Real >::storage_ private
Definition at line 35 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::getGradient(), ROL::RiskNeutralObjective< Real >::getValue(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::update().
value_storage_
template<class Real > Ptr<ScalarController<Real> > ROL::RiskNeutralObjective< Real >::value_storage_ private
Definition at line 39 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::getValue(), ROL::RiskNeutralObjective< Real >::RiskNeutralObjective(), ROL::RiskNeutralObjective< Real >::RiskNeutralObjective(), ROL::RiskNeutralObjective< Real >::RiskNeutralObjective(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::update().
gradient_storage_
template<class Real > Ptr<VectorController<Real> > ROL::RiskNeutralObjective< Real >::gradient_storage_ private
Definition at line 40 of file ROL_RiskNeutralObjective.hpp.
Referenced by ROL::RiskNeutralObjective< Real >::getGradient(), ROL::RiskNeutralObjective< Real >::RiskNeutralObjective(), ROL::RiskNeutralObjective< Real >::RiskNeutralObjective(), ROL::RiskNeutralObjective< Real >::RiskNeutralObjective(), ROL::RiskNeutralObjective< Real >::update(), and ROL::RiskNeutralObjective< Real >::update().
The documentation for this class was generated from the following file:
ROL_RiskNeutralObjective.hpp