ROL: ROL::UserInputGenerator< Real > Class Template Reference
ROL::UserInputGenerator< Real > Class Template Reference
#include <ROL_UserInputGenerator.hpp>
Public Member Functions
UserInputGenerator (ROL::ParameterList &parlist, const ROL::Ptr< BatchManager< Real > > &bman)
UserInputGenerator (std::string file_pt, std::string file_wt, int n, int dim, const ROL::Ptr< BatchManager< Real > > &bman)
void refine (void)
int numGlobalSamples (void) const
Public Member Functions inherited from ROL::SampleGenerator< Real >
virtual ~SampleGenerator ()
SampleGenerator (const ROL::Ptr< BatchManager< Real > > &bman)
SampleGenerator (const SampleGenerator< Real > &sampler)
virtual void update (const Vector< Real > &x)
virtual int start (void)
virtual Real computeError (std::vector< Real > &vals)
virtual Real computeError (std::vector< ROL::Ptr< Vector< Real > > > &vals, const Vector< Real > &x)
virtual void setSamples (bool inConstructor=false)
virtual int numMySamples (void) const
virtual std::vector< Real > getMyPoint (const int i) const
virtual Real getMyWeight (const int i) const
int batchID (void) const
int numBatches (void) const
void sumAll (Real *input, Real *output, int dim) const
void sumAll (Vector< Real > &input, Vector< Real > &output) const
void broadcast (Real *input, int cnt, int root) const
void barrier (void) const
const ROL::Ptr< BatchManager< Real > > getBatchManager (void) const
void print (const std::string &filename="samples", const int prec=12) const
Private Member Functions
void sample (std::string file_pt, std::string file_wt, int n, int dim, const ROL::Ptr< BatchManager< Real > > &bman)
Private Attributes
int nSamp_
Additional Inherited Members
Protected Member Functions inherited from ROL::SampleGenerator< Real >
void setPoints (std::vector< std::vector< Real > > &p)
void setWeights (std::vector< Real > &w)
Detailed Description
template<typename Real>
class ROL::UserInputGenerator< Real >
Definition at line 23 of file ROL_UserInputGenerator.hpp.
Constructor & Destructor Documentation
UserInputGenerator() [1/2]
template<typename Real > ROL::UserInputGenerator< Real >::UserInputGenerator (ROL::ParameterList & parlist, const ROL::Ptr< BatchManager< Real > > & bman) inline
Definition at line 82 of file ROL_UserInputGenerator.hpp.
References dim, and ROL::UserInputGenerator< Real >::sample().
UserInputGenerator() [2/2]
template<typename Real > ROL::UserInputGenerator< Real >::UserInputGenerator (std::string file_pt, std::string file_wt, int n, int dim, const ROL::Ptr< BatchManager< Real > > & bman) inline
Definition at line 103 of file ROL_UserInputGenerator.hpp.
References dim, and ROL::UserInputGenerator< Real >::sample().
Member Function Documentation
sample()
template<typename Real > void ROL::UserInputGenerator< Real >::sample (std::string file_pt, std::string file_wt, int n, int dim, const ROL::Ptr< BatchManager< Real > > & bman) inline private
Definition at line 27 of file ROL_UserInputGenerator.hpp.
References dim, ROL::UserInputGenerator< Real >::nSamp_, ROL::SampleGenerator< Real >::setPoints(), and ROL::SampleGenerator< Real >::setWeights().
Referenced by ROL::UserInputGenerator< Real >::UserInputGenerator(), and ROL::UserInputGenerator< Real >::UserInputGenerator().
refine()
template<typename Real > void ROL::UserInputGenerator< Real >::refine (void) inline virtual
Reimplemented from ROL::SampleGenerator< Real >.
Definition at line 112 of file ROL_UserInputGenerator.hpp.
numGlobalSamples()
template<typename Real > int ROL::UserInputGenerator< Real >::numGlobalSamples (void) const inline virtual
Reimplemented from ROL::SampleGenerator< Real >.
Definition at line 114 of file ROL_UserInputGenerator.hpp.
References ROL::UserInputGenerator< Real >::nSamp_.
Member Data Documentation
nSamp_
template<typename Real > int ROL::UserInputGenerator< Real >::nSamp_ private
Definition at line 25 of file ROL_UserInputGenerator.hpp.
Referenced by ROL::UserInputGenerator< Real >::numGlobalSamples(), and ROL::UserInputGenerator< Real >::sample().
The documentation for this class was generated from the following file:
ROL_UserInputGenerator.hpp