ROL: ROL::StdVector< Real, Element > Class Template Reference
ROL::StdVector< Real, Element > Class Template Reference
Provides the ROL::Vector interface for scalar values, to be used, for example, with scalar constraints.
#include <ROL_StdVector.hpp>
Public Member Functions
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
virtual Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
virtual Ptr< Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual const Vector & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
using size_type = typename std::vector< Real >::size_type
Private Attributes
Ptr< std::vector< Element > > std_vec_
Detailed Description
template<class Real, class Element = Real>
class ROL::StdVector< Real, Element >
Provides the ROL::Vector interface for scalar values, to be used, for example, with scalar constraints.
Provides the std::vector implementation of the ROL::Vector interface.
Definition at line 27 of file ROL_StdVector.hpp.
Member Typedef Documentation
size_type
template<class Real , class Element = Real> using ROL::StdVector< Real, Element >::size_type = typename std::vector<Real>::size_type private
Definition at line 29 of file ROL_StdVector.hpp.
Constructor & Destructor Documentation
StdVector() [1/3]
template<class Real , class Element = Real> ROL::StdVector< Real, Element >::StdVector (const Ptr< std::vector< Element > > & std_vec) inline
Definition at line 33 of file ROL_StdVector.hpp.
StdVector() [2/3]
template<class Real , class Element = Real> ROL::StdVector< Real, Element >::StdVector (const int dim, const Element val = 0.0) inline
Definition at line 35 of file ROL_StdVector.hpp.
References dim, and ROL::StdVector< Real, Element >::std_vec_.
StdVector() [3/3]
template<class Real , class Element = Real> ROL::StdVector< Real, Element >::StdVector (std::initializer_list< Element > ilist) inline
Definition at line 39 of file ROL_StdVector.hpp.
Member Function Documentation
operator[]() [1/2]
template<class Real , class Element = Real> Real & ROL::StdVector< Real, Element >::operator[] (int i) inline
Definition at line 42 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
operator[]() [2/2]
template<class Real , class Element = Real> const Real & ROL::StdVector< Real, Element >::operator[] (int i) const inline
Definition at line 43 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
set()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::set (const Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 45 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::dimension(), ROL::Vector< Real >::dimension(), ROL::StdVector< Real, Element >::getVector(), and ROL::StdVector< Real, Element >::std_vec_.
Referenced by main(), and testRandomInputs().
plus()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::plus (const Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 56 of file ROL_StdVector.hpp.
References dim, ROL::StdVector< Real, Element >::dimension(), ROL::Vector< Real >::dimension(), ROL::StdVector< Real, Element >::getVector(), and ROL::StdVector< Real, Element >::std_vec_.
axpy()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::axpy (const Real alpha, const Vector< Real > & x) inline virtual
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of @b x.
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = \mathtt{*this} + \alpha x \f$.
   Uses #clone, #set, #scale and #plus for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 70 of file ROL_StdVector.hpp.
References dim, ROL::StdVector< Real, Element >::dimension(), ROL::Vector< Real >::dimension(), ROL::StdVector< Real, Element >::getVector(), and ROL::StdVector< Real, Element >::std_vec_.
Referenced by main(), main(), ROL::ZOO::Objective_PoissonInversion< Real >::solve_adjoint_sensitivity_equation(), and testRandomInputs().
scale()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 84 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
Referenced by main(), and testRandomInputs().
dot()
template<class Real , class Element = Real> virtual Real ROL::StdVector< Real, Element >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Reimplemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, ROL::PrimalAtomVector< Real >, ROL::DualAtomVector< Real >, ROL::BatchStdVector< Real >, ROL::PrimalProbabilityVector< Real >, ROL::DualProbabilityVector< Real >, ROL::PrimalScaledStdVector< Real, Element >, and ROL::DualScaledStdVector< Real, Element >.
Definition at line 92 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::dimension(), ROL::Vector< Real >::dimension(), ROL::StdVector< Real, Element >::getVector(), and ROL::StdVector< Real, Element >::std_vec_.
Referenced by ROL::PrimalScaledStdVector< Real, Element >::apply(), ROL::DualScaledStdVector< Real, Element >::apply(), and ROL::StdVector< Real, Element >::norm().
norm()
template<class Real , class Element = Real> Real ROL::StdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 109 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::dot().
Referenced by main(), and main().
clone()
template<class Real , class Element = Real> virtual Ptr< Vector< Real > > ROL::StdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Reimplemented in L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, ROL::PrimalScaledStdVector< Real, Element >, ROL::DualScaledStdVector< Real, Element >, L2VectorPrimal< Real >, L2VectorDual< Real >, H1VectorPrimal< Real >, H1VectorDual< Real >, ROL::PrimalAtomVector< Real >, ROL::DualAtomVector< Real >, ROL::BatchStdVector< Real >, ROL::ProbabilityVector< Real >, ROL::PrimalProbabilityVector< Real >, and ROL::DualProbabilityVector< Real >.
Definition at line 115 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
Referenced by ROL::StdVector< Real, Element >::basis(), main(), and ROL::ZOO::Objective_PoissonInversion< Real >::value().
getVector() [1/2]
template<class Real , class Element = Real> Ptr< const std::vector< Element > > ROL::StdVector< Real, Element >::getVector () const inline
Definition at line 119 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
Referenced by TridiagonalToeplitzOperator< Real >::apply(), ROL::StdConstraint< Real >::applyAdjointHessian(), constraint1< Real >::applyAdjointHessian_11(), constraint2< Real >::applyAdjointHessian_11(), constraint1< Real >::applyAdjointHessian_12(), constraint2< Real >::applyAdjointHessian_12(), constraint1< Real >::applyAdjointHessian_21(), constraint2< Real >::applyAdjointHessian_21(), constraint1< Real >::applyAdjointHessian_22(), constraint2< Real >::applyAdjointHessian_22(), constraint2< Real >::applyAdjointJacobian_1(), constraint1< Real >::applyAdjointJacobian_2(), constraint2< Real >::applyAdjointJacobian_2(), ROL::StdVector< Real, Element >::applyBinary(), TridiagonalToeplitzOperator< Real >::applyInverse(), constraint1< Real >::applyInverseJacobian_1(), constraint1< Real >::applyJacobian_1(), constraint2< Real >::applyJacobian_1(), constraint1< Real >::applyJacobian_2(), constraint2< Real >::applyJacobian_2(), ROL::StdConstraint< Real >::applyPreconditioner(), ROL::StdVector< Real, Element >::axpy(), ROL::PrimalScaledStdVector< Real, Element >::clone(), ROL::DualScaledStdVector< Real, Element >::clone(), L2VectorPrimal< Real >::clone(), L2VectorDual< Real >::clone(), H1VectorPrimal< Real >::clone(), H1VectorDual< Real >::clone(), ROL::BatchStdVector< Real >::clone(), ROL::ProbabilityVector< Real >::clone(), ROL::PrimalProbabilityVector< Real >::clone(), ROL::DualProbabilityVector< Real >::clone(), ROL::StdObjective< Real >::dirDeriv(), L2VectorPrimal< Real >::dot(), L2VectorDual< Real >::dot(), H1VectorPrimal< Real >::dot(), H1VectorDual< Real >::dot(), L2VectorPrimal< Real >::dot(), L2VectorDual< Real >::dot(), H1VectorPrimal< Real >::dot(), H1VectorDual< Real >::dot(), ROL::PrimalAtomVector< Real >::dot(), ROL::DualAtomVector< Real >::dot(), ROL::BatchStdVector< Real >::dot(), ROL::PrimalProbabilityVector< Real >::dot(), ROL::DualProbabilityVector< Real >::dot(), ROL::PrimalScaledStdVector< Real, Element >::dot(), ROL::DualScaledStdVector< Real, Element >::dot(), ROL::StdVector< Real, Element >::dot(), ROL::PrimalScaledStdVector< Real, Element >::dual(), ROL::DualScaledStdVector< Real, Element >::dual(), L2VectorPrimal< Real >::dual(), L2VectorDual< Real >::dual(), H1VectorPrimal< Real >::dual(), H1VectorDual< Real >::dual(), ROL::PrimalAtomVector< Real >::dual(), ROL::DualAtomVector< Real >::dual(), ROL::PrimalProbabilityVector< Real >::dual(), ROL::DualProbabilityVector< Real >::dual(), ROL::AtomVector< Real >::getAtom(), ROL::ProbabilityVector< Real >::getNumMyAtoms(), ROL::ProbabilityVector< Real >::getProbability(), ROL::StdObjective< Real >::gradient(), ROL::StdObjective< Real >::hessVec(), ROL::StdObjective< Real >::invHessVec(), ROL::StdVector< Real, Element >::plus(), ROL::StdObjective< Real >::precond(), ROL::BatchStdVector< Real >::reduce(), ROL::StdVector< Real, Element >::set(), ROL::AtomVector< Real >::setAtom(), ROL::ProbabilityVector< Real >::setProbability(), constraint1< Real >::solve(), ROL::StdConstraint< RealT >::solveAugmentedSystem(), ROL::StdConstraint< Real >::solveAugmentedSystem(), ROL::StdConstraint< Real >::update(), ROL::StdObjective< Real >::update(), ROL::StdConstraint< Real >::update(), ROL::StdObjective< Real >::update(), ROL::StdObjective< Real >::value(), constraint1< Real >::value(), and constraint2< Real >::value().
getVector() [2/2]
template<class Real , class Element = Real> Ptr< std::vector< Element > > ROL::StdVector< Real, Element >::getVector () inline
Definition at line 123 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
basis()
template<class Real , class Element = Real> Ptr< Vector< Real > > ROL::StdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 127 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::clone(), and ROL::StdVector< Real, Element >::dimension().
Referenced by main().
dimension()
template<class Real , class Element = Real> int ROL::StdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 137 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
Referenced by ROL::StdVector< Real, Element >::applyBinary(), ROL::StdVector< Real, Element >::axpy(), ROL::StdVector< Real, Element >::basis(), ROL::PrimalScaledStdVector< Real, Element >::clone(), ROL::DualScaledStdVector< Real, Element >::clone(), ROL::PrimalScaledStdVector< Real, Element >::dot(), ROL::DualScaledStdVector< Real, Element >::dot(), ROL::StdVector< Real, Element >::dot(), L2VectorPrimal< Real >::dual(), L2VectorDual< Real >::dual(), H1VectorPrimal< Real >::dual(), H1VectorDual< Real >::dual(), main(), ROL::StdVector< Real, Element >::plus(), and ROL::StdVector< Real, Element >::set().
applyUnary()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::applyUnary (const Elementwise::UnaryFunction< Real > & f) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 141 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
Referenced by testRandomInputs().
applyBinary()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::applyBinary (const Elementwise::BinaryFunction< Real > & f, const Vector< Real > & x) inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 149 of file ROL_StdVector.hpp.
References dim, ROL::StdVector< Real, Element >::dimension(), ROL::Vector< Real >::dimension(), ROL::StdVector< Real, Element >::getVector(), and ROL::StdVector< Real, Element >::std_vec_.
Referenced by testCases().
reduce()
template<class Real , class Element = Real> Real ROL::StdVector< Real, Element >::reduce (const Elementwise::ReductionOp< Real > & r) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 164 of file ROL_StdVector.hpp.
References dim, and ROL::StdVector< Real, Element >::std_vec_.
setScalar()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::setScalar (const Real C) inline virtual
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
   @param[in]      C     is a scalar.
   On return \f$\mathtt{*this} = C\f$.
   Uses #applyUnary methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 173 of file ROL_StdVector.hpp.
References dim, and ROL::StdVector< Real, Element >::std_vec_.
Referenced by testRandomInputs().
randomize()
template<class Real , class Element = Real> void ROL::StdVector< Real, Element >::randomize (const Real l = 0.0, const Real u = 1.0) inline virtual
Set vector to be uniform random between [l,u].
   @param[in]      l     is a the lower bound.
   @param[in]      u     is a the upper bound.
   On return the components of \f$\mathtt{*this}\f$ are uniform
   random numbers on the interval \f$[l,u]\f$.
         The default implementation uses #applyUnary methods for the
         computation. Please overload if a more efficient implementation is
   needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 178 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
Referenced by main(), and testRandomInputs().
print()
template<class Real , class Element = Real> virtual void ROL::StdVector< Real, Element >::print (std::ostream & outStream) const inline virtual
Reimplemented from ROL::Vector< Real >.
Definition at line 194 of file ROL_StdVector.hpp.
References ROL::StdVector< Real, Element >::std_vec_.
Member Data Documentation
std_vec_
template<class Real , class Element = Real> Ptr<std::vector<Element> > ROL::StdVector< Real, Element >::std_vec_ private
Definition at line 205 of file ROL_StdVector.hpp.
Referenced by ROL::StdVector< Real, Element >::applyBinary(), ROL::StdVector< Real, Element >::applyUnary(), ROL::StdVector< Real, Element >::axpy(), ROL::StdVector< Real, Element >::clone(), ROL::StdVector< Real, Element >::dimension(), ROL::StdVector< Real, Element >::dot(), ROL::StdVector< Real, Element >::getVector(), ROL::StdVector< Real, Element >::getVector(), ROL::StdVector< Real, Element >::operator[](), ROL::StdVector< Real, Element >::operator[](), ROL::StdVector< Real, Element >::plus(), ROL::StdVector< Real, Element >::print(), ROL::StdVector< Real, Element >::randomize(), ROL::StdVector< Real, Element >::reduce(), ROL::StdVector< Real, Element >::scale(), ROL::StdVector< Real, Element >::set(), ROL::StdVector< Real, Element >::setScalar(), and ROL::StdVector< Real, Element >::StdVector().
The documentation for this class was generated from the following file:
ROL_StdVector.hpp