ROL: ROL::LinMoreModel< Real > Class Template Reference
ROL::LinMoreModel< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate projected trust-region model functions from the Kelley-Sachs bound constrained trust-region algorithm.
#include <ROL_LinMoreModel.hpp>
Public Member Functions
LinMoreModel (Objective< Real > &obj, BoundConstraint< Real > &bnd, const Vector< Real > &x, const Vector< Real > &g, const Ptr< Secant< Real > > &secant=nullPtr, const bool useSecantPrecond=false, const bool useSecantHessVec=false)
void applyFullHessian (Vector< Real > &hv, const Vector< Real > &v, Real &tol)
void applyFreeHessian (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void applyFullPrecond (Vector< Real > &pv, const Vector< Real > &v, Real &tol)
void applyFreePrecond (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Public Member Functions inherited from ROL::TrustRegionModel< Real >
virtual ~TrustRegionModel ()
TrustRegionModel (Objective< Real > &obj, BoundConstraint< Real > &bnd, const Vector< Real > &x, const Vector< Real > &g, const Ptr< Secant< Real > > &secant=nullPtr, const bool useSecantPrecond=false, const bool useSecantHessVec=false)
virtual void update (Objective< Real > &obj, BoundConstraint< Real > &bnd, const Vector< Real > &x, const Vector< Real > &g, const Ptr< Secant< Real > > &secant=nullPtr)
virtual Real value (const Vector< Real > &s, Real &tol)
Compute value.
virtual void gradient (Vector< Real > &g, const Vector< Real > &s, Real &tol)
Compute gradient.
virtual void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &s, Real &tol)
Apply Hessian approximation to vector.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &s, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &s, Real &tol)
Apply preconditioner to vector.
virtual const Ptr< const Vector< Real > > getGradient (void) const
virtual const Ptr< const Vector< Real > > getIterate (void) const
virtual const Ptr< Objective< Real > > getObjective (void) const
virtual const Ptr< BoundConstraint< Real > > getBoundConstraint (void) const
virtual void dualTransform (Vector< Real > &tv, const Vector< Real > &v)
virtual void primalTransform (Vector< Real > &tv, const Vector< Real > &v)
virtual void updatePredictedReduction (Real &pred, const Vector< Real > &s)
virtual void updateActualReduction (Real &ared, const Vector< Real > &s)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
Ptr< Vector< Real > > pwa_
Ptr< Vector< Real > > dwa_
Additional Inherited Members
Protected Member Functions inherited from ROL::TrustRegionModel< Real >
void applyHessian (Vector< Real > &hv, const Vector< Real > &v, Real &tol)
void applyInvHessian (Vector< Real > &hv, const Vector< Real > &v, Real &tol)
void applyPrecond (Vector< Real > &Pv, const Vector< Real > &v, Real &tol)
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::LinMoreModel< Real >
Provides the interface to evaluate projected trust-region model functions from the Kelley-Sachs bound constrained trust-region algorithm.
Definition at line 27 of file ROL_LinMoreModel.hpp.
Constructor & Destructor Documentation
LinMoreModel()
template<class Real > ROL::LinMoreModel< Real >::LinMoreModel (Objective< Real > & obj, BoundConstraint< Real > & bnd, const Vector< Real > & x, const Vector< Real > & g, const Ptr< Secant< Real > > & secant = nullPtr, const bool useSecantPrecond = false, const bool useSecantHessVec = false) inline
Definition at line 33 of file ROL_LinMoreModel.hpp.
References ROL::Vector< Real >::clone(), ROL::LinMoreModel< Real >::dwa_, and ROL::LinMoreModel< Real >::pwa_.
Member Function Documentation
applyFullHessian()
template<class Real > void ROL::LinMoreModel< Real >::applyFullHessian (Vector< Real > & hv, const Vector< Real > & v, Real & tol) inline
Definition at line 42 of file ROL_LinMoreModel.hpp.
References ROL::TrustRegionModel< Real >::applyHessian().
Referenced by ROL::LinMoreModel< Real >::applyFreeHessian().
applyFreeHessian()
template<class Real > void ROL::LinMoreModel< Real >::applyFreeHessian (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline
Definition at line 46 of file ROL_LinMoreModel.hpp.
References ROL::LinMoreModel< Real >::applyFullHessian(), ROL::TrustRegionModel< Real >::getBoundConstraint(), ROL::LinMoreModel< Real >::pwa_, and zero.
applyFullPrecond()
template<class Real > void ROL::LinMoreModel< Real >::applyFullPrecond (Vector< Real > & pv, const Vector< Real > & v, Real & tol) inline
Definition at line 54 of file ROL_LinMoreModel.hpp.
References ROL::TrustRegionModel< Real >::applyPrecond().
Referenced by ROL::LinMoreModel< Real >::applyFreePrecond().
applyFreePrecond()
template<class Real > void ROL::LinMoreModel< Real >::applyFreePrecond (Vector< Real > & pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline
Definition at line 58 of file ROL_LinMoreModel.hpp.
References ROL::LinMoreModel< Real >::applyFullPrecond(), ROL::LinMoreModel< Real >::dwa_, ROL::TrustRegionModel< Real >::getBoundConstraint(), and zero.
Member Data Documentation
pwa_
template<class Real > Ptr<Vector<Real> > ROL::LinMoreModel< Real >::pwa_ private
Definition at line 29 of file ROL_LinMoreModel.hpp.
Referenced by ROL::LinMoreModel< Real >::applyFreeHessian(), and ROL::LinMoreModel< Real >::LinMoreModel().
dwa_
template<class Real > Ptr<Vector<Real> > ROL::LinMoreModel< Real >::dwa_ private
Definition at line 29 of file ROL_LinMoreModel.hpp.
Referenced by ROL::LinMoreModel< Real >::applyFreePrecond(), and ROL::LinMoreModel< Real >::LinMoreModel().
The documentation for this class was generated from the following file:
ROL_LinMoreModel.hpp