ROL: ROL::ZOO::Constraint_CylinderHead< Real > Class Template Reference
ROL::ZOO::Constraint_CylinderHead< Real > Class Template Reference
#include <ROL_CylinderHead.hpp>
Public Member Functions
Constraint_CylinderHead ()
void value (std::vector< Real > &c, const std::vector< Real > &x, Real &tol)
void applyJacobian (std::vector< Real > &jv, const std::vector< Real > &v, const std::vector< Real > &x, Real &tol)
void applyAdjointJacobian (std::vector< Real > &ajv, const std::vector< Real > &v, const std::vector< Real > &x, Real &tol)
Public Member Functions inherited from ROL::StdConstraint< Real >
virtual ~StdConstraint ()
void update (const Vector< Real > &x, bool flag=true, int iter=-1) override
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update (const std::vector< Real > &x, bool flag=true, int iter=-1)
void update (const Vector< Real > &x, UpdateType type, int iter=-1) override
Update constraint function.
virtual void update (const std::vector< Real > &x, UpdateType type, int iter=-1)
void value (Vector< Real > &c, const Vector< Real > &x, Real &tol) override
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void applyAdjointHessian (Vector< Real > &ahuv, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
virtual void applyAdjointHessian (std::vector< Real > &ahuv, const std::vector< Real > &u, const std::vector< Real > &v, const std::vector< Real > &x, Real &tol)
std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol) override
Approximately solves the augmented system
virtual std::vector< Real > solveAugmentedSystem (std::vector< Real > &v1, std::vector< Real > &v2, const std::vector< Real > &b1, const std::vector< Real > &b2, const std::vector< Real > &x, Real tol)
void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol) override
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
virtual void applyPreconditioner (std::vector< Real > &pv, const std::vector< Real > &v, const std::vector< Real > &x, const std::vector< Real > &g, Real &tol)
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Private Member Functions
Real warranty (const Real flatness, const int deriv=0) const
Real tcycle (const Real flatness, const int deriv=0) const
Real twall (const Real dintake, const int deriv=0) const
Real smax (const Real tw, const int deriv=0) const
Additional Inherited Members
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::ZOO::Constraint_CylinderHead< Real >
Definition at line 68 of file ROL_CylinderHead.hpp.
Constructor & Destructor Documentation
Constraint_CylinderHead()
template<class Real > ROL::ZOO::Constraint_CylinderHead< Real >::Constraint_CylinderHead () inline
Definition at line 97 of file ROL_CylinderHead.hpp.
Member Function Documentation
warranty()
template<class Real > Real ROL::ZOO::Constraint_CylinderHead< Real >::warranty (const Real flatness, const int deriv = 0) const inline private
Definition at line 70 of file ROL_CylinderHead.hpp.
References zero.
Referenced by ROL::ZOO::Constraint_CylinderHead< Real >::applyAdjointJacobian(), ROL::ZOO::Constraint_CylinderHead< Real >::applyJacobian(), and ROL::ZOO::Constraint_CylinderHead< Real >::value().
tcycle()
template<class Real > Real ROL::ZOO::Constraint_CylinderHead< Real >::tcycle (const Real flatness, const int deriv = 0) const inline private
Definition at line 76 of file ROL_CylinderHead.hpp.
Referenced by ROL::ZOO::Constraint_CylinderHead< Real >::applyAdjointJacobian(), ROL::ZOO::Constraint_CylinderHead< Real >::applyJacobian(), and ROL::ZOO::Constraint_CylinderHead< Real >::value().
twall()
template<class Real > Real ROL::ZOO::Constraint_CylinderHead< Real >::twall (const Real dintake, const int deriv = 0) const inline private
Definition at line 83 of file ROL_CylinderHead.hpp.
References zero.
Referenced by ROL::ZOO::Constraint_CylinderHead< Real >::applyAdjointJacobian(), ROL::ZOO::Constraint_CylinderHead< Real >::applyJacobian(), and ROL::ZOO::Constraint_CylinderHead< Real >::value().
smax()
template<class Real > Real ROL::ZOO::Constraint_CylinderHead< Real >::smax (const Real tw, const int deriv = 0) const inline private
Definition at line 89 of file ROL_CylinderHead.hpp.
Referenced by ROL::ZOO::Constraint_CylinderHead< Real >::applyAdjointJacobian(), ROL::ZOO::Constraint_CylinderHead< Real >::applyJacobian(), and ROL::ZOO::Constraint_CylinderHead< Real >::value().
value()
template<class Real > void ROL::ZOO::Constraint_CylinderHead< Real >::value (std::vector< Real > & c, const std::vector< Real > & x, Real & tol) inline virtual
Implements ROL::StdConstraint< Real >.
Definition at line 99 of file ROL_CylinderHead.hpp.
References ROL::ZOO::Constraint_CylinderHead< Real >::smax(), ROL::ZOO::Constraint_CylinderHead< Real >::tcycle(), ROL::ZOO::Constraint_CylinderHead< Real >::twall(), and ROL::ZOO::Constraint_CylinderHead< Real >::warranty().
applyJacobian()
template<class Real > void ROL::ZOO::Constraint_CylinderHead< Real >::applyJacobian (std::vector< Real > & jv, const std::vector< Real > & v, const std::vector< Real > & x, Real & tol) inline virtual
Reimplemented from ROL::StdConstraint< Real >.
Definition at line 106 of file ROL_CylinderHead.hpp.
References ROL::ZOO::Constraint_CylinderHead< Real >::smax(), ROL::ZOO::Constraint_CylinderHead< Real >::tcycle(), ROL::ZOO::Constraint_CylinderHead< Real >::twall(), and ROL::ZOO::Constraint_CylinderHead< Real >::warranty().
applyAdjointJacobian()
template<class Real > void ROL::ZOO::Constraint_CylinderHead< Real >::applyAdjointJacobian (std::vector< Real > & ajv, const std::vector< Real > & v, const std::vector< Real > & x, Real & tol) inline virtual
Reimplemented from ROL::StdConstraint< Real >.
Definition at line 113 of file ROL_CylinderHead.hpp.
References ROL::ZOO::Constraint_CylinderHead< Real >::smax(), ROL::ZOO::Constraint_CylinderHead< Real >::tcycle(), ROL::ZOO::Constraint_CylinderHead< Real >::twall(), and ROL::ZOO::Constraint_CylinderHead< Real >::warranty().
The documentation for this class was generated from the following file:
ROL_CylinderHead.hpp