ROL: H1VectorPrimal< Real > Class Template Reference
H1VectorPrimal< Real > Class Template Reference
#include <test_04.hpp>
Public Member Functions
H1VectorPrimal (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
Real dot (const ROL::Vector< Real > &x) const override
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const override
Clone to make a new (uninitialized) vector.
const ROL::Vector< Real > & dual () const override
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
H1VectorPrimal (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
H1VectorPrimal (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
H1VectorPrimal (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
H1VectorPrimal (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Attributes
ROL::Ptr< BurgersFEM< Real > > fem_
ROL::Ptr< H1VectorDual< Real > > dual_vec_
bool isDualInitialized_
ROL::Ptr< std::vector< Real > > vec_
Detailed Description
template<class Real>
class H1VectorPrimal< Real >
Definition at line 578 of file example_08.hpp.
Constructor & Destructor Documentation
H1VectorPrimal() [1/5]
template<class Real > H1VectorPrimal< Real >::H1VectorPrimal (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 592 of file test_04.hpp.
H1VectorPrimal() [2/5]
template<class Real > H1VectorPrimal< Real >::H1VectorPrimal (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 680 of file example_04.hpp.
H1VectorPrimal() [3/5]
template<class Real > H1VectorPrimal< Real >::H1VectorPrimal (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 684 of file example_06.hpp.
H1VectorPrimal() [4/5]
template<class Real > H1VectorPrimal< Real >::H1VectorPrimal (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 688 of file example_07.hpp.
H1VectorPrimal() [5/5]
template<class Real > H1VectorPrimal< Real >::H1VectorPrimal (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 585 of file example_08.hpp.
Member Function Documentation
dot() [1/5]
template<class Real > Real H1VectorPrimal< Real >::dot (const ROL::Vector< Real > & x) const inline override virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 597 of file test_04.hpp.
References H1VectorPrimal< Real >::fem_, H1VectorPrimal< Real >::getVector(), and ROL::StdVector< Real, Element >::getVector().
Referenced by H1VectorPrimal< Real >::norm().
clone() [1/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::clone () const inline override virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 604 of file test_04.hpp.
References H1VectorPrimal< Real >::dimension(), H1VectorPrimal< Real >::fem_, and ROL::StdVector< Real, Element >::getVector().
dual() [1/5]
template<class Real > const ROL::Vector< Real > & H1VectorPrimal< Real >::dual (void) const inline override virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 610 of file test_04.hpp.
References H1VectorPrimal< Real >::dimension(), H1VectorPrimal< Real >::dual_vec_, H1VectorPrimal< Real >::fem_, ROL::StdVector< Real, Element >::getVector(), and H1VectorPrimal< Real >::isDualInitialized_.
set() [1/3]
template<class Real > void H1VectorPrimal< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 684 of file example_04.hpp.
References H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
plus() [1/3]
template<class Real > void H1VectorPrimal< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 690 of file example_04.hpp.
References H1VectorPrimal< Real >::dimension(), H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
scale() [1/3]
template<class Real > void H1VectorPrimal< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 699 of file example_04.hpp.
References H1VectorPrimal< Real >::dimension(), and H1VectorPrimal< Real >::vec_.
dot() [2/5]
template<class Real > Real H1VectorPrimal< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 706 of file example_04.hpp.
References H1VectorPrimal< Real >::fem_, H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
norm() [1/3]
template<class Real > Real H1VectorPrimal< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 712 of file example_04.hpp.
References H1VectorPrimal< Real >::dot().
clone() [2/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 718 of file example_04.hpp.
References H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
getVector() [1/6]
template<class Real > ROL::Ptr< const std::vector< Real > > H1VectorPrimal< Real >::getVector () const inline
Definition at line 722 of file example_04.hpp.
References H1VectorPrimal< Real >::vec_.
Referenced by H1VectorDual< Real >::apply(), H1VectorPrimal< Real >::dot(), H1VectorPrimal< Real >::dot(), H1VectorPrimal< Real >::plus(), and H1VectorPrimal< Real >::set().
getVector() [2/6]
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorPrimal< Real >::getVector () inline
Definition at line 726 of file example_04.hpp.
References H1VectorPrimal< Real >::vec_.
basis() [1/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 730 of file example_04.hpp.
References H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
dimension() [1/3]
template<class Real > int H1VectorPrimal< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 737 of file example_04.hpp.
References H1VectorPrimal< Real >::vec_.
Referenced by H1VectorPrimal< Real >::clone(), H1VectorPrimal< Real >::dual(), H1VectorPrimal< Real >::plus(), and H1VectorPrimal< Real >::scale().
dual() [2/5]
template<class Real > const ROL::Vector< Real > & H1VectorPrimal< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 741 of file example_04.hpp.
References H1VectorPrimal< Real >::dual_vec_, H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
apply() [1/3]
template<class Real > Real H1VectorPrimal< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 749 of file example_04.hpp.
References H1VectorDual< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
set() [2/3]
template<class Real > void H1VectorPrimal< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 688 of file example_06.hpp.
References H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
plus() [2/3]
template<class Real > void H1VectorPrimal< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 694 of file example_06.hpp.
References H1VectorPrimal< Real >::dimension(), H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
scale() [2/3]
template<class Real > void H1VectorPrimal< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 703 of file example_06.hpp.
References H1VectorPrimal< Real >::dimension(), and H1VectorPrimal< Real >::vec_.
dot() [3/5]
template<class Real > Real H1VectorPrimal< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 710 of file example_06.hpp.
References H1VectorPrimal< Real >::fem_, H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
norm() [2/3]
template<class Real > Real H1VectorPrimal< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 716 of file example_06.hpp.
References H1VectorPrimal< Real >::dot().
clone() [3/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 722 of file example_06.hpp.
References H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
getVector() [3/6]
template<class Real > ROL::Ptr< const std::vector< Real > > H1VectorPrimal< Real >::getVector () const inline
Definition at line 726 of file example_06.hpp.
References H1VectorPrimal< Real >::vec_.
getVector() [4/6]
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorPrimal< Real >::getVector () inline
Definition at line 730 of file example_06.hpp.
References H1VectorPrimal< Real >::vec_.
basis() [2/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 734 of file example_06.hpp.
References H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
dimension() [2/3]
template<class Real > int H1VectorPrimal< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 741 of file example_06.hpp.
References H1VectorPrimal< Real >::vec_.
dual() [3/5]
template<class Real > const ROL::Vector< Real > & H1VectorPrimal< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 745 of file example_06.hpp.
References H1VectorPrimal< Real >::dual_vec_, H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
apply() [2/3]
template<class Real > Real H1VectorPrimal< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 753 of file example_06.hpp.
References H1VectorDual< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
set() [3/3]
template<class Real > void H1VectorPrimal< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 692 of file example_07.hpp.
References H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
plus() [3/3]
template<class Real > void H1VectorPrimal< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 698 of file example_07.hpp.
References H1VectorPrimal< Real >::dimension(), H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
scale() [3/3]
template<class Real > void H1VectorPrimal< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 707 of file example_07.hpp.
References H1VectorPrimal< Real >::dimension(), and H1VectorPrimal< Real >::vec_.
dot() [4/5]
template<class Real > Real H1VectorPrimal< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 714 of file example_07.hpp.
References H1VectorPrimal< Real >::fem_, H1VectorPrimal< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
norm() [3/3]
template<class Real > Real H1VectorPrimal< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 720 of file example_07.hpp.
References H1VectorPrimal< Real >::dot().
clone() [4/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 726 of file example_07.hpp.
References H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
getVector() [5/6]
template<class Real > ROL::Ptr< const std::vector< Real > > H1VectorPrimal< Real >::getVector () const inline
Definition at line 730 of file example_07.hpp.
References H1VectorPrimal< Real >::vec_.
getVector() [6/6]
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorPrimal< Real >::getVector () inline
Definition at line 734 of file example_07.hpp.
References H1VectorPrimal< Real >::vec_.
basis() [3/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 738 of file example_07.hpp.
References H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
dimension() [3/3]
template<class Real > int H1VectorPrimal< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 745 of file example_07.hpp.
References H1VectorPrimal< Real >::vec_.
dual() [4/5]
template<class Real > const ROL::Vector< Real > & H1VectorPrimal< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 749 of file example_07.hpp.
References H1VectorPrimal< Real >::dual_vec_, H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::vec_.
apply() [3/3]
template<class Real > Real H1VectorPrimal< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 757 of file example_07.hpp.
References H1VectorDual< Real >::getVector(), and H1VectorPrimal< Real >::vec_.
dot() [5/5]
template<class Real > Real H1VectorPrimal< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 590 of file example_08.hpp.
References H1VectorPrimal< Real >::fem_, H1VectorPrimal< Real >::getVector(), and ROL::StdVector< Real, Element >::getVector().
clone() [5/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > H1VectorPrimal< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 597 of file example_08.hpp.
References H1VectorPrimal< Real >::fem_.
dual() [5/5]
template<class Real > const ROL::Vector< Real > & H1VectorPrimal< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 602 of file example_08.hpp.
References ROL::StdVector< Real, Element >::dimension(), H1VectorPrimal< Real >::dual_vec_, H1VectorPrimal< Real >::fem_, and H1VectorPrimal< Real >::isDualInitialized_.
Member Data Documentation
fem_
template<class Real > ROL::Ptr< BurgersFEM< Real > > H1VectorPrimal< Real >::fem_ private
Definition at line 587 of file test_04.hpp.
Referenced by H1VectorPrimal< Real >::basis(), H1VectorPrimal< Real >::clone(), H1VectorPrimal< Real >::clone(), H1VectorPrimal< Real >::dot(), H1VectorPrimal< Real >::dot(), H1VectorPrimal< Real >::dual(), and H1VectorPrimal< Real >::dual().
dual_vec_
template<class Real > ROL::Ptr< H1VectorDual< Real > > H1VectorPrimal< Real >::dual_vec_ mutable private
Definition at line 588 of file test_04.hpp.
Referenced by H1VectorPrimal< Real >::dual(), and H1VectorPrimal< Real >::dual().
isDualInitialized_
template<class Real > bool H1VectorPrimal< Real >::isDualInitialized_ mutable private
Definition at line 589 of file test_04.hpp.
Referenced by H1VectorPrimal< Real >::dual(), and H1VectorPrimal< Real >::dual().
vec_
template<class Real > ROL::Ptr< std::vector< Real > > H1VectorPrimal< Real >::vec_ private
Definition at line 674 of file example_04.hpp.
Referenced by H1VectorPrimal< Real >::apply(), H1VectorPrimal< Real >::basis(), H1VectorPrimal< Real >::clone(), H1VectorPrimal< Real >::dimension(), H1VectorPrimal< Real >::dot(), H1VectorPrimal< Real >::dual(), H1VectorPrimal< Real >::getVector(), H1VectorPrimal< Real >::getVector(), H1VectorPrimal< Real >::plus(), H1VectorPrimal< Real >::scale(), and H1VectorPrimal< Real >::set().
The documentation for this class was generated from the following files:
test_04.hpp
example_04.hpp
example_06.hpp
example_07.hpp
example_08.hpp