ROL: ROL::TypeB::MoreauYosidaAlgorithm< Real > Class Template Reference
ROL::TypeB::MoreauYosidaAlgorithm< Real > Class Template Reference
Provides an interface to run the Moreau-Yosida algorithm.
#include <ROL_TypeB_MoreauYosidaAlgorithm.hpp>
Public Member Functions
MoreauYosidaAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, MoreauYosidaObjective< Real > &myobj, BoundConstraint< Real > &bnd, Vector< Real > &pwa, std::ostream &outStream=std::cout)
void updateState (const Vector< Real > &x, MoreauYosidaObjective< Real > &myobj, BoundConstraint< Real > &bnd, Vector< Real > &pwa, std::ostream &outStream=std::cout)
Private Attributes
const Ptr< Secant< Real > > secant_
Real compViolation_
Real gnorm_
Real maxPenalty_
Real tau_
bool print_
bool updatePenalty_
bool updateMultiplier_
ROL::ParameterList list_
int subproblemIter_
std::string stepname_
int verbosity_
bool writeHeader_
bool hasEcon_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::MoreauYosidaAlgorithm< Real >
Provides an interface to run the Moreau-Yosida algorithm.
Definition at line 25 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Constructor & Destructor Documentation
MoreauYosidaAlgorithm()
template<typename Real > ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 19 of file ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp.
References ROL::TypeB::MoreauYosidaAlgorithm< Real >::list_, ROL::TypeB::MoreauYosidaAlgorithm< Real >::maxPenalty_, ROL::TypeB::MoreauYosidaAlgorithm< Real >::print_, ROL::TypeB::Algorithm< Real >::reset(), ROL::TypeB::Algorithm< Real >::state_, ROL::TypeB::Algorithm< Real >::status_, ROL::TypeB::MoreauYosidaAlgorithm< Real >::stepname_, ROL::TypeB::MoreauYosidaAlgorithm< Real >::tau_, ROL::TypeB::MoreauYosidaAlgorithm< Real >::updateMultiplier_, ROL::TypeB::MoreauYosidaAlgorithm< Real >::updatePenalty_, ROL::TypeB::MoreauYosidaAlgorithm< Real >::verbosity_, and ROL::TypeB::MoreauYosidaAlgorithm< Real >::writeHeader_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::MoreauYosidaAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, MoreauYosidaObjective< Real > & myobj, BoundConstraint< Real > & bnd, Vector< Real > & pwa, std::ostream & outStream = std::cout) private
Definition at line 58 of file ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp.
References ROL::TypeB::Algorithm< Real >::initialize().
updateState()
template<typename Real > void ROL::TypeB::MoreauYosidaAlgorithm< Real >::updateState (const Vector< Real > & x, MoreauYosidaObjective< Real > & myobj, BoundConstraint< Real > & bnd, Vector< Real > & pwa, std::ostream & outStream = std::cout) private
Definition at line 79 of file ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::MoreauYosidaObjective< Real >::getObjectiveGradient(), ROL::MoreauYosidaObjective< Real >::getObjectiveValue(), ROL::Initial, ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), ROL::MoreauYosidaObjective< Real >::testComplementarity(), and ROL::MoreauYosidaObjective< Real >::update().
run()
template<typename Real > void ROL::TypeB::MoreauYosidaAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 112 of file ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp.
References ROL::Vector< Real >::clone(), ROL::MoreauYosidaObjective< Real >::getNumberFunctionEvaluations(), ROL::MoreauYosidaObjective< Real >::getNumberGradientEvaluations(), ROL::MoreauYosidaObjective< Real >::updateMultipliers(), and ROL::TypeB::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeB::MoreauYosidaAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 169 of file ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeB::MoreauYosidaAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 202 of file ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::MoreauYosidaAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 210 of file ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeB::MoreauYosidaAlgorithm< Real >::secant_ private
Definition at line 27 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
compViolation_
template<typename Real > Real ROL::TypeB::MoreauYosidaAlgorithm< Real >::compViolation_ private
Definition at line 28 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
gnorm_
template<typename Real > Real ROL::TypeB::MoreauYosidaAlgorithm< Real >::gnorm_ private
Definition at line 29 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
maxPenalty_
template<typename Real > Real ROL::TypeB::MoreauYosidaAlgorithm< Real >::maxPenalty_ private
Definition at line 30 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
tau_
template<typename Real > Real ROL::TypeB::MoreauYosidaAlgorithm< Real >::tau_ private
Definition at line 31 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
print_
template<typename Real > bool ROL::TypeB::MoreauYosidaAlgorithm< Real >::print_ private
Definition at line 32 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
updatePenalty_
template<typename Real > bool ROL::TypeB::MoreauYosidaAlgorithm< Real >::updatePenalty_ private
Definition at line 33 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
updateMultiplier_
template<typename Real > bool ROL::TypeB::MoreauYosidaAlgorithm< Real >::updateMultiplier_ private
Definition at line 34 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
list_
template<typename Real > ROL::ParameterList ROL::TypeB::MoreauYosidaAlgorithm< Real >::list_ private
Definition at line 36 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
subproblemIter_
template<typename Real > int ROL::TypeB::MoreauYosidaAlgorithm< Real >::subproblemIter_ private
Definition at line 37 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
stepname_
template<typename Real > std::string ROL::TypeB::MoreauYosidaAlgorithm< Real >::stepname_ private
Definition at line 39 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
verbosity_
template<typename Real > int ROL::TypeB::MoreauYosidaAlgorithm< Real >::verbosity_ private
Definition at line 41 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
writeHeader_
template<typename Real > bool ROL::TypeB::MoreauYosidaAlgorithm< Real >::writeHeader_ private
Definition at line 42 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
Referenced by ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
hasEcon_
template<typename Real > bool ROL::TypeB::MoreauYosidaAlgorithm< Real >::hasEcon_ private
Definition at line 44 of file ROL_TypeB_MoreauYosidaAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_MoreauYosidaAlgorithm.hpp
ROL_TypeB_MoreauYosidaAlgorithm_Def.hpp