ROL: ROL::LinMore< Real > Class Template Reference
ROL::LinMore< Real > Class Template Reference
Provides interface for truncated CG trust-region subproblem solver.
#include <ROL_LinMore.hpp>
Classes
class LowerBreakPoint
class PositiveMax
class PositiveMin
class UpperBreakPoint
Public Member Functions
LinMore (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g)
void run (Vector< Real > &s, Real &snorm, int &iflag, int &iter, const Real del, TrustRegionModel< Real > &model)
Public Member Functions inherited from ROL::TrustRegion< Real >
virtual ~TrustRegion ()
TrustRegion (ROL::ParameterList &parlist)
virtual void update (Vector< Real > &x, Real &fnew, Real &del, int &nfval, int &ngrad, ETrustRegionFlag &flagTR, const Vector< Real > &s, const Real snorm, const Real fold, const Vector< Real > &g, int iter, Objective< Real > &obj, BoundConstraint< Real > &bnd, TrustRegionModel< Real > &model)
void setPredictedReduction (const Real pRed)
Real getPredictedReduction (void) const
Private Member Functions
Real dgpstep (Vector< Real > &s, const Vector< Real > &w, const Vector< Real > &x, const Real alpha, TrustRegionModel< Real > &model) const
void dbreakpt (const Vector< Real > &x, const Vector< Real > &s, TrustRegionModel< Real > &model, Real &bpmin, Real &bpmax, Vector< Real > &pwa)
Real dcauchy (Vector< Real > &s, Real &alpha, const Vector< Real > &x, const Vector< Real > &g, const Real del, TrustRegionModel< Real > &model, Vector< Real > &pwa1, Vector< Real > &pwa2, Vector< Real > &dwa)
Real dprsrch (Vector< Real > &x, Vector< Real > &s, const Vector< Real > &g, TrustRegionModel< Real > &model, Vector< Real > &pwa, Vector< Real > &dwa)
Real dtrqsol (const Real xtx, const Real ptp, const Real ptx, const Real del)
Real dtrpcg (Vector< Real > &w, int &iflag, int &iter, const Vector< Real > &g, const Vector< Real > &x, const Real del, TrustRegionModel< Real > &model, const Real tol, const Real stol, const int itermax, Vector< Real > &p, Vector< Real > &q, Vector< Real > &r, Vector< Real > &t)
Private Attributes
Ptr< Vector< Real > > x_
Ptr< Vector< Real > > s_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > pwa1_
Ptr< Vector< Real > > pwa2_
Ptr< Vector< Real > > dwa1_
Ptr< Vector< Real > > dwa2_
Real tol1_
Real tol2_
Real alpha_
int maxit_
unsigned verbosity_
ROL::LinMore::LowerBreakPoint lbp_
ROL::LinMore::UpperBreakPoint ubp_
ROL::LinMore::PositiveMin pmin_
ROL::LinMore::PositiveMax pmax_
Detailed Description
template<class Real>
class ROL::LinMore< Real >
Provides interface for truncated CG trust-region subproblem solver.
Definition at line 25 of file ROL_LinMore.hpp.
Constructor & Destructor Documentation
LinMore()
template<class Real > ROL::LinMore< Real >::LinMore (ROL::ParameterList & parlist) inline
Definition at line 91 of file ROL_LinMore.hpp.
References ROL::LinMore< Real >::maxit_, ROL::LinMore< Real >::tol1_, ROL::LinMore< Real >::tol2_, and ROL::LinMore< Real >::verbosity_.
Member Function Documentation
initialize()
template<class Real > void ROL::LinMore< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g) inline virtual
Reimplemented from ROL::TrustRegion< Real >.
Definition at line 101 of file ROL_LinMore.hpp.
References ROL::Vector< Real >::clone(), ROL::LinMore< Real >::dwa1_, ROL::LinMore< Real >::dwa2_, ROL::LinMore< Real >::g_, ROL::TrustRegion< Real >::initialize(), ROL::LinMore< Real >::pwa1_, ROL::LinMore< Real >::pwa2_, ROL::LinMore< Real >::s_, and ROL::LinMore< Real >::x_.
run()
template<class Real > void ROL::LinMore< Real >::run (Vector< Real > & s, Real & snorm, int & iflag, int & iter, const Real del, TrustRegionModel< Real > & model) inline virtual
Implements ROL::TrustRegion< Real >.
Definition at line 108 of file ROL_LinMore.hpp.
References ROL::LinMore< Real >::alpha_, ROL::Vector< Real >::axpy(), ROL::LinMore< Real >::dcauchy(), dim, ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dot(), ROL::LinMore< Real >::dprsrch(), ROL::LinMore< Real >::dtrpcg(), ROL::LinMore< Real >::dwa1_, ROL::LinMore< Real >::dwa2_, ROL::LinMore< Real >::g_, ROL::TrustRegionModel< Real >::getBoundConstraint(), ROL::TrustRegionModel< Real >::getGradient(), ROL::TrustRegionModel< Real >::getIterate(), ROL::LinMore< Real >::maxit_, ROL::Vector< Real >::norm(), ROL::LinMore< Real >::pwa1_, ROL::LinMore< Real >::pwa2_, ROL::LinMore< Real >::s_, ROL::Vector< Real >::set(), ROL::TrustRegion< Real >::setPredictedReduction(), ROL::LinMore< Real >::tol2_, ROL::LinMore< Real >::verbosity_, ROL::LinMore< Real >::x_, and zero.
dgpstep()
template<class Real > Real ROL::LinMore< Real >::dgpstep (Vector< Real > & s, const Vector< Real > & w, const Vector< Real > & x, const Real alpha, TrustRegionModel< Real > & model) const inline private
Definition at line 224 of file ROL_LinMore.hpp.
References ROL::Vector< Real >::axpy(), ROL::TrustRegionModel< Real >::getBoundConstraint(), ROL::Vector< Real >::norm(), and ROL::Vector< Real >::set().
Referenced by ROL::LinMore< Real >::dcauchy(), and ROL::LinMore< Real >::dprsrch().
dbreakpt()
template<class Real > void ROL::LinMore< Real >::dbreakpt (const Vector< Real > & x, const Vector< Real > & s, TrustRegionModel< Real > & model, Real & bpmin, Real & bpmax, Vector< Real > & pwa) inline private
Definition at line 241 of file ROL_LinMore.hpp.
References ROL::Vector< Real >::applyBinary(), ROL::Vector< Real >::axpy(), ROL::TrustRegionModel< Real >::getBoundConstraint(), ROL::LinMore< Real >::lbp_, ROL::Vector< Real >::norm(), ROL::LinMore< Real >::pmax_, ROL::LinMore< Real >::pmin_, ROL::Vector< Real >::reduce(), ROL::Vector< Real >::set(), ROL::LinMore< Real >::ubp_, ROL::LinMore< Real >::verbosity_, and zero.
Referenced by ROL::LinMore< Real >::dcauchy(), and ROL::LinMore< Real >::dprsrch().
dcauchy()
template<class Real > Real ROL::LinMore< Real >::dcauchy (Vector< Real > & s, Real & alpha, const Vector< Real > & x, const Vector< Real > & g, const Real del, TrustRegionModel< Real > & model, Vector< Real > & pwa1, Vector< Real > & pwa2, Vector< Real > & dwa) inline private
Definition at line 293 of file ROL_LinMore.hpp.
References ROL::LinMore< Real >::dbreakpt(), ROL::LinMore< Real >::dgpstep(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
Referenced by ROL::LinMore< Real >::run().
dprsrch()
template<class Real > Real ROL::LinMore< Real >::dprsrch (Vector< Real > & x, Vector< Real > & s, const Vector< Real > & g, TrustRegionModel< Real > & model, Vector< Real > & pwa, Vector< Real > & dwa) inline private
Definition at line 363 of file ROL_LinMore.hpp.
References ROL::LinMore< Real >::dbreakpt(), ROL::LinMore< Real >::dgpstep(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::set(), and ROL::LinMore< Real >::verbosity_.
Referenced by ROL::LinMore< Real >::run().
dtrqsol()
template<class Real > Real ROL::LinMore< Real >::dtrqsol (const Real xtx, const Real ptp, const Real ptx, const Real del) inline private
Definition at line 408 of file ROL_LinMore.hpp.
References zero.
Referenced by ROL::LinMore< Real >::dtrpcg().
dtrpcg()
template<class Real > Real ROL::LinMore< Real >::dtrpcg (Vector< Real > & w, int & iflag, int & iter, const Vector< Real > & g, const Vector< Real > & x, const Real del, TrustRegionModel< Real > & model, const Real tol, const Real stol, const int itermax, Vector< Real > & p, Vector< Real > & q, Vector< Real > & r, Vector< Real > & t) inline private
Definition at line 441 of file ROL_LinMore.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::LinMore< Real >::dtrqsol(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), zero, and ROL::Vector< Real >::zero().
Referenced by ROL::LinMore< Real >::run().
Member Data Documentation
x_
template<class Real > Ptr<Vector<Real> > ROL::LinMore< Real >::x_ private
Definition at line 28 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::initialize(), and ROL::LinMore< Real >::run().
s_
template<class Real > Ptr<Vector<Real> > ROL::LinMore< Real >::s_ private
Definition at line 28 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::initialize(), and ROL::LinMore< Real >::run().
g_
template<class Real > Ptr<Vector<Real> > ROL::LinMore< Real >::g_ private
Definition at line 28 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::initialize(), and ROL::LinMore< Real >::run().
pwa1_
template<class Real > Ptr<Vector<Real> > ROL::LinMore< Real >::pwa1_ private
Definition at line 29 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::initialize(), and ROL::LinMore< Real >::run().
pwa2_
template<class Real > Ptr<Vector<Real> > ROL::LinMore< Real >::pwa2_ private
Definition at line 29 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::initialize(), and ROL::LinMore< Real >::run().
dwa1_
template<class Real > Ptr<Vector<Real> > ROL::LinMore< Real >::dwa1_ private
Definition at line 29 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::initialize(), and ROL::LinMore< Real >::run().
dwa2_
template<class Real > Ptr<Vector<Real> > ROL::LinMore< Real >::dwa2_ private
Definition at line 29 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::initialize(), and ROL::LinMore< Real >::run().
tol1_
template<class Real > Real ROL::LinMore< Real >::tol1_ private
Definition at line 31 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::LinMore().
tol2_
template<class Real > Real ROL::LinMore< Real >::tol2_ private
Definition at line 31 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::LinMore(), and ROL::LinMore< Real >::run().
alpha_
template<class Real > Real ROL::LinMore< Real >::alpha_ private
Definition at line 31 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::run().
maxit_
template<class Real > int ROL::LinMore< Real >::maxit_ private
Definition at line 32 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::LinMore(), and ROL::LinMore< Real >::run().
verbosity_
template<class Real > unsigned ROL::LinMore< Real >::verbosity_ private
Definition at line 34 of file ROL_LinMore.hpp.
Referenced by ROL::LinMore< Real >::dbreakpt(), ROL::LinMore< Real >::dprsrch(), ROL::LinMore< Real >::LinMore(), and ROL::LinMore< Real >::run().
lbp_
template<class Real > ROL::LinMore::LowerBreakPoint ROL::LinMore< Real >::lbp_ private
Referenced by ROL::LinMore< Real >::dbreakpt().
ubp_
template<class Real > ROL::LinMore::UpperBreakPoint ROL::LinMore< Real >::ubp_ private
Referenced by ROL::LinMore< Real >::dbreakpt().
pmin_
template<class Real > ROL::LinMore::PositiveMin ROL::LinMore< Real >::pmin_ private
Referenced by ROL::LinMore< Real >::dbreakpt().
pmax_
template<class Real > ROL::LinMore::PositiveMax ROL::LinMore< Real >::pmax_ private
Referenced by ROL::LinMore< Real >::dbreakpt().
The documentation for this class was generated from the following file:
ROL_LinMore.hpp