ROL: ROL::TypeP::TrustRegionAlgorithm< Real > Class Template Reference
ROL::TypeP::TrustRegionAlgorithm< Real > Class Template Reference
Provides an interface to run the trust-region algorithm.
#include <ROL_TypeP_TrustRegionAlgorithm.hpp>
Public Member Functions
TrustRegionAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout) override
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeP::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Real ftol, Objective< Real > &sobj, Objective< Real > &nobj, Vector< Real > &px, Vector< Real > &dg, std::ostream &outStream=std::cout)
Real computeValue (Real inTol, Real &outTol, Real pRed, Real &fold, int iter, const Vector< Real > &x, const Vector< Real > &xold, Objective< Real > &obj)
void computeGradient (const Vector< Real > &x, Vector< Real > &g, Vector< Real > &px, Vector< Real > &dg, Vector< Real > &pwa, Real del, Objective< Real > &sobj, Objective< Real > &nobj, bool accept, Real &gtol, Real &gnorm, std::ostream &outStream=std::cout) const
Real dcauchy (Vector< Real > &s, Real &alpha, Real &sval, Real &nval, const Vector< Real > &x, const Vector< Real > &g, Real del, TrustRegionModel_U< Real > &model, Objective< Real > &nobj, Vector< Real > &px, Vector< Real > &dwa, Vector< Real > &dwa1, std::ostream &outStream=std::cout)
void dspg2 (Vector< Real > &y, Real &sval, Real &nval, Real &pRed, Vector< Real > &gmod, const Vector< Real > &x, Real del, TrustRegionModel_U< Real > &model, Objective< Real > &nobj, Vector< Real > &pwa, Vector< Real > &pwa1, Vector< Real > &pwa2, Vector< Real > &dwa, std::ostream &outStream=std::cout)
void dspg (Vector< Real > &y, Real &sval, Real &nval, Vector< Real > &gmod, const Vector< Real > &x, Real del, TrustRegionModel_U< Real > &model, Objective< Real > &nobj, Vector< Real > &ymin, Vector< Real > &pwa, Vector< Real > &pwa1, Vector< Real > &pwa2, Vector< Real > &pwa3, Vector< Real > &pwa4, Vector< Real > &pwa5, Vector< Real > &dwa, std::ostream &outStream=std::cout)
void dncg (Vector< Real > &y, Real &sval, Real &nval, Vector< Real > &gmod, const Vector< Real > &x, Real del, TrustRegionModel_U< Real > &model, Objective< Real > &nobj, Vector< Real > &s, Vector< Real > &pwa1, Vector< Real > &pwa2, Vector< Real > &pwa3, Vector< Real > &pwa4, Vector< Real > &pwa5, Vector< Real > &dwa, std::ostream &outStream=std::cout)
void dprox (Vector< Real > &x, const Vector< Real > &x0, Real t, Real del, Objective< Real > &nobj, Vector< Real > &y0, Vector< Real > &y1, Vector< Real > &yc, Vector< Real > &pwa, std::ostream &outStream=std::cout) const
void dbls (Real &alpha, Real &nval, Real &pred, const Vector< Real > &y, const Vector< Real > &s, Real lambda, Real tmax, Real kappa, Real gs, Objective< Real > &nobj, Vector< Real > &pwa)
Private Attributes
Ptr< TrustRegionModel_U< Real > > model_
Container for trust-region model.
Real delMax_
Maximum trust-region radius (default: ROL_INF)
Real eta0_
Step acceptance threshold (default: 0.05)
Real eta1_
Radius decrease threshold (default: 0.05)
Real eta2_
Radius increase threshold (default: 0.9)
Real gamma0_
Radius decrease rate (negative rho) (default: 0.0625)
Real gamma1_
Radius decrease rate (positive rho) (default: 0.25)
Real gamma2_
Radius increase rate (default: 2.5)
Real TRsafe_
Safeguard size for numerically evaluating ratio (default: 1e2)
Real eps_
Safeguard for numerically evaluating ratio.
bool interpRad_
Interpolate the trust-region radius if ratio is negative (default: false)
TRUtils::ETRFlag TRflag_
Trust-region exit flag.
int SPflag_
Subproblem solver termination flag.
int SPiter_
Subproblem solver iteration count.
ESecant esec_
Secant type (default: Limited-Memory BFGS)
bool useSecantPrecond_
Flag to use secant as a preconditioner (default: false)
bool useSecantHessVec_
Flag to use secant as Hessian (default: false)
Real tol1_
Absolute tolerance for truncated CG (default: 1e-4)
Real tol2_
Relative tolerance for truncated CG (default: 1e-2)
int maxit_
Maximum number of CG iterations (default: 25)
bool useNM_
int storageNM_
Real mu0_
Sufficient decrease parameter (default: 1e-2)
Real spexp_
Relative tolerance exponent for subproblem solve (default: 1, range: [1,2])
int redlim_
Maximum number of Cauchy point reduction steps (default: 10)
int explim_
Maximum number of Cauchy point expansion steps (default: 10)
Real alpha_
Initial Cauchy point step length (default: 1.0)
bool normAlpha_
Normalize initial Cauchy point step length (default: false)
Real interpf_
Backtracking rate for Cauchy point computation (default: 1e-1)
Real extrapf_
Extrapolation rate for Cauchy point computation (default: 1e1)
Real qtol_
Relative tolerance for computed decrease in Cauchy point computation (default: 1-8)
Real lambdaMin_
Real lambdaMax_
Real gamma_
int maxSize_
bool useMin_
bool useNMSP_
ETrustRegionP algSelect_
int ncgType_
Real etaNCG_
Real desPar_
std::vector< bool > useInexact_
Real scale0_
Real scale1_
Real scale_
Real omega_
Real force_
int updateIter_
Real forceFactor_
Real gtol_
bool initProx_
Real t0_
int nhess_
Number of Hessian applications.
unsigned verbosity_
Output level (default: 0)
bool writeHeader_
Flag to write header at every iteration.
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeP::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void pgstep (Vector< Real > &pgiter, Vector< Real > &pgstep, Objective< Real > &nobj, const Vector< Real > &x, const Vector< Real > &dg, Real t, Real &tol) const
Protected Attributes inherited from ROL::TypeP::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeP::TrustRegionAlgorithm< Real >
Provides an interface to run the trust-region algorithm.
Definition at line 83 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
Constructor & Destructor Documentation
TrustRegionAlgorithm()
template<typename Real > ROL::TypeP::TrustRegionAlgorithm< Real >::TrustRegionAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 20 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::SECANTMODE_BOTH, ROL::SECANTMODE_FORWARD, ROL::SECANTMODE_INVERSE, ROL::StringToESecant(), and ROL::TypeP::StringToETrustRegionP().
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Real ftol, Objective< Real > & sobj, Objective< Real > & nobj, Vector< Real > & px, Vector< Real > & dg, std::ostream & outStream = std::cout) private
Definition at line 109 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Initial, ROL::TypeP::Algorithm< Real >::initialize(), ROL::Objective< Real >::prox(), ROL::Vector< Real >::set(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, std::ostream & outStream = std::cout) override virtual
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeP::Algorithm< Real >.
Definition at line 205 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::TRUtils::NPOSPREDNEG, ROL::Vector< Real >::plus(), ROL::TRUtils::POSPREDNEG, ROL::Revert, ROL::Vector< Real >::set(), ROL::TRUtils::SUCCESS, ROL::TRUtils::TRNAN, ROL::TypeP::TRUSTREGION_P_NCG, ROL::TypeP::TRUSTREGION_P_SPG, ROL::TypeP::TRUSTREGION_P_SPG2, ROL::Objective< Real >::update(), ROL::TypeP::Algorithm< Real >::writeExitStatus(), and zero.
writeHeader()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 1139 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::TRUtils::ETRFlagToString(), ROL::NumberToString(), ROL::TRUtils::SUCCESS, ROL::TypeP::TRUSTREGION_P_NCG, ROL::TypeP::TRUSTREGION_P_SPG, ROL::TypeP::TRUSTREGION_P_SPG2, and ROL::TRUtils::UNDEFINED.
writeName()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 1192 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::TypeP::TRUSTREGION_P_NCG, ROL::TypeP::TRUSTREGION_P_SPG, and ROL::TypeP::TRUSTREGION_P_SPG2.
writeOutput()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::writeOutput (std::ostream & os, bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 1206 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
computeValue()
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::computeValue (Real inTol, Real & outTol, Real pRed, Real & fold, int iter, const Vector< Real > & x, const Vector< Real > & xold, Objective< Real > & obj) private
Definition at line 143 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Trial, ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
computeGradient()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::computeGradient (const Vector< Real > & x, Vector< Real > & g, Vector< Real > & px, Vector< Real > & dg, Vector< Real > & pwa, Real del, Objective< Real > & sobj, Objective< Real > & nobj, bool accept, Real & gtol, Real & gnorm, std::ostream & outStream = std::cout) const private
Definition at line 168 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Vector< Real >::dual(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::norm(), and ROL::Vector< Real >::set().
dcauchy()
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy (Vector< Real > & s, Real & alpha, Real & sval, Real & nval, const Vector< Real > & x, const Vector< Real > & g, Real del, TrustRegionModel_U< Real > & model, Objective< Real > & nobj, Vector< Real > & px, Vector< Real > & dwa, Vector< Real > & dwa1, std::ostream & outStream = std::cout) private
Definition at line 345 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::dot(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
dspg2()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2 (Vector< Real > & y, Real & sval, Real & nval, Real & pRed, Vector< Real > & gmod, const Vector< Real > & x, Real del, TrustRegionModel_U< Real > & model, Objective< Real > & nobj, Vector< Real > & pwa, Vector< Real > & pwa1, Vector< Real > & pwa2, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 452 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::Vector< Real >::zero().
dspg()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::dspg (Vector< Real > & y, Real & sval, Real & nval, Vector< Real > & gmod, const Vector< Real > & x, Real del, TrustRegionModel_U< Real > & model, Objective< Real > & nobj, Vector< Real > & ymin, Vector< Real > & pwa, Vector< Real > & pwa1, Vector< Real > & pwa2, Vector< Real > & pwa3, Vector< Real > & pwa4, Vector< Real > & pwa5, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 567 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::apply(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
dncg()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::dncg (Vector< Real > & y, Real & sval, Real & nval, Vector< Real > & gmod, const Vector< Real > & x, Real del, TrustRegionModel_U< Real > & model, Objective< Real > & nobj, Vector< Real > & s, Vector< Real > & pwa1, Vector< Real > & pwa2, Vector< Real > & pwa3, Vector< Real > & pwa4, Vector< Real > & pwa5, Vector< Real > & dwa, std::ostream & outStream = std::cout) private
Definition at line 951 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), zero, and ROL::Vector< Real >::zero().
dprox()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::dprox (Vector< Real > & x, const Vector< Real > & x0, Real t, Real del, Objective< Real > & nobj, Vector< Real > & y0, Vector< Real > & y1, Vector< Real > & yc, Vector< Real > & pwa, std::ostream & outStream = std::cout) const private
Definition at line 718 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::norm(), ROL::Objective< Real >::prox(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and zero.
dbls()
template<typename Real > void ROL::TypeP::TrustRegionAlgorithm< Real >::dbls (Real & alpha, Real & nval, Real & pred, const Vector< Real > & y, const Vector< Real > & s, Real lambda, Real tmax, Real kappa, Real gs, Objective< Real > & nobj, Vector< Real > & pwa) private
Definition at line 814 of file ROL_TypeP_TrustRegionAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and zero.
Member Data Documentation
model_
template<typename Real > Ptr<TrustRegionModel_U<Real> > ROL::TypeP::TrustRegionAlgorithm< Real >::model_ private
Container for trust-region model.
Definition at line 85 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
delMax_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::delMax_ private
Maximum trust-region radius (default: ROL_INF)
Definition at line 88 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
eta0_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::eta0_ private
Step acceptance threshold (default: 0.05)
Definition at line 89 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
eta1_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::eta1_ private
Radius decrease threshold (default: 0.05)
Definition at line 90 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
eta2_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::eta2_ private
Radius increase threshold (default: 0.9)
Definition at line 91 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
gamma0_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::gamma0_ private
Radius decrease rate (negative rho) (default: 0.0625)
Definition at line 92 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
gamma1_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::gamma1_ private
Radius decrease rate (positive rho) (default: 0.25)
Definition at line 93 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
gamma2_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::gamma2_ private
Radius increase rate (default: 2.5)
Definition at line 94 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
TRsafe_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::TRsafe_ private
Safeguard size for numerically evaluating ratio (default: 1e2)
Definition at line 95 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
eps_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::eps_ private
Safeguard for numerically evaluating ratio.
Definition at line 96 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
interpRad_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::interpRad_ private
Interpolate the trust-region radius if ratio is negative (default: false)
Definition at line 97 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
TRflag_
template<typename Real > TRUtils::ETRFlag ROL::TypeP::TrustRegionAlgorithm< Real >::TRflag_ private
Trust-region exit flag.
Definition at line 100 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
SPflag_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::SPflag_ private
Subproblem solver termination flag.
Definition at line 101 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
SPiter_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::SPiter_ private
Subproblem solver iteration count.
Definition at line 102 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
esec_
template<typename Real > ESecant ROL::TypeP::TrustRegionAlgorithm< Real >::esec_ private
Secant type (default: Limited-Memory BFGS)
Definition at line 105 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
useSecantPrecond_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::useSecantPrecond_ private
Flag to use secant as a preconditioner (default: false)
Definition at line 106 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
useSecantHessVec_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::useSecantHessVec_ private
Flag to use secant as Hessian (default: false)
Definition at line 107 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
tol1_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::tol1_ private
Absolute tolerance for truncated CG (default: 1e-4)
Definition at line 110 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
tol2_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::tol2_ private
Relative tolerance for truncated CG (default: 1e-2)
Definition at line 111 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
maxit_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::maxit_ private
Maximum number of CG iterations (default: 25)
Definition at line 112 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
useNM_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::useNM_ private
Definition at line 115 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
storageNM_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::storageNM_ private
Definition at line 116 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
mu0_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::mu0_ private
Sufficient decrease parameter (default: 1e-2)
Definition at line 117 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
spexp_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::spexp_ private
Relative tolerance exponent for subproblem solve (default: 1, range: [1,2])
Definition at line 118 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
redlim_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::redlim_ private
Maximum number of Cauchy point reduction steps (default: 10)
Definition at line 119 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
explim_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::explim_ private
Maximum number of Cauchy point expansion steps (default: 10)
Definition at line 120 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
alpha_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::alpha_ private
Initial Cauchy point step length (default: 1.0)
Definition at line 121 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
normAlpha_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::normAlpha_ private
Normalize initial Cauchy point step length (default: false)
Definition at line 122 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
interpf_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::interpf_ private
Backtracking rate for Cauchy point computation (default: 1e-1)
Definition at line 123 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
extrapf_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::extrapf_ private
Extrapolation rate for Cauchy point computation (default: 1e1)
Definition at line 124 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
qtol_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::qtol_ private
Relative tolerance for computed decrease in Cauchy point computation (default: 1-8)
Definition at line 125 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
lambdaMin_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::lambdaMin_ private
Definition at line 126 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
lambdaMax_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::lambdaMax_ private
Definition at line 127 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
gamma_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::gamma_ private
Definition at line 128 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
maxSize_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::maxSize_ private
Definition at line 129 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
useMin_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::useMin_ private
Definition at line 130 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
useNMSP_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::useNMSP_ private
Definition at line 131 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
algSelect_
template<typename Real > ETrustRegionP ROL::TypeP::TrustRegionAlgorithm< Real >::algSelect_ private
Definition at line 132 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
ncgType_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::ncgType_ private
Definition at line 133 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
etaNCG_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::etaNCG_ private
Definition at line 134 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
desPar_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::desPar_ private
Definition at line 135 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
useInexact_
template<typename Real > std::vector<bool> ROL::TypeP::TrustRegionAlgorithm< Real >::useInexact_ private
Definition at line 138 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
scale0_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::scale0_ private
Definition at line 139 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
scale1_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::scale1_ private
Definition at line 140 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
scale_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::scale_ private
Definition at line 141 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
omega_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::omega_ private
Definition at line 142 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
force_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::force_ private
Definition at line 143 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
updateIter_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::updateIter_ private
Definition at line 144 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
forceFactor_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::forceFactor_ private
Definition at line 145 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
gtol_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::gtol_ private
Definition at line 146 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
initProx_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::initProx_ private
Definition at line 148 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
t0_
template<typename Real > Real ROL::TypeP::TrustRegionAlgorithm< Real >::t0_ private
Definition at line 149 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
nhess_
template<typename Real > int ROL::TypeP::TrustRegionAlgorithm< Real >::nhess_ mutable private
Number of Hessian applications.
Definition at line 151 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
verbosity_
template<typename Real > unsigned ROL::TypeP::TrustRegionAlgorithm< Real >::verbosity_ private
Output level (default: 0)
Definition at line 152 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeP::TrustRegionAlgorithm< Real >::writeHeader_ private
Flag to write header at every iteration.
Definition at line 153 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeP_TrustRegionAlgorithm.hpp
ROL_TypeP_TrustRegionAlgorithm_Def.hpp