ROL: ROL::TypeE::Algorithm< Real > Class Template Reference
ROL::TypeE::Algorithm< Real > Class Template Reference abstract
#include <ROL_TypeE_Algorithm.hpp>
Public Member Functions
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems (Type-E). This is the primary Type-E interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems (Type-E). This is the primary Type-E interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, std::ostream &outStream=std::cout)=0
Run algorithm on equality constrained problems (Type-E). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems with explicit linear equality constraints (Type-E). This is the primary Type-E with explicit linear equality constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on equality constrained problems with explicit linear equality constraints (Type-E). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeHeader (std::ostream &os) const
Print iterate header.
virtual void writeName (std::ostream &os) const
Print step name.
virtual void writeOutput (std::ostream &os, const bool write_header=false) const
Print iterate status.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Protected Member Functions
void initialize (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &mul, const Vector< Real > &c)
Protected Attributes
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeE::Algorithm< Real >
Definition at line 54 of file ROL_TypeE_Algorithm.hpp.
Constructor & Destructor Documentation
~Algorithm()
template<typename Real > virtual ROL::TypeE::Algorithm< Real >::~Algorithm () inline virtual
Definition at line 66 of file ROL_TypeE_Algorithm.hpp.
Algorithm()
template<typename Real > ROL::TypeE::Algorithm< Real >::Algorithm ()
Constructor, given a step and a status test.
Definition at line 22 of file ROL_TypeE_Algorithm_Def.hpp.
References ROL::TypeE::Algorithm< Real >::status_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeE::Algorithm< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & mul, const Vector< Real > & c) protected
Definition at line 30 of file ROL_TypeE_Algorithm_Def.hpp.
References ROL::Vector< Real >::clone().
Referenced by ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::FletcherAlgorithm< Real >::initialize(), and ROL::TypeE::CompositeStepAlgorithm< Real >::initialize().
setStatusTest()
template<typename Real > void ROL::TypeE::Algorithm< Real >::setStatusTest (const Ptr< StatusTest< Real > > & status, bool combineStatus = false)
Definition at line 63 of file ROL_TypeE_Algorithm_Def.hpp.
run() [1/5]
template<typename Real > void ROL::TypeE::Algorithm< Real >::run (Problem< Real > & problem, std::ostream & outStream = std::cout) virtual
Run algorithm on equality constrained problems (Type-E). This is the primary Type-E interface.
Reimplemented in ROL::TypeE::StabilizedLCLAlgorithm< Real >.
Definition at line 72 of file ROL_TypeE_Algorithm_Def.hpp.
References ROL::Problem< Real >::finalizeIteration(), ROL::Problem< Real >::getConstraint(), ROL::Problem< Real >::getDualOptimizationVector(), ROL::Problem< Real >::getMultiplierVector(), ROL::Problem< Real >::getObjective(), ROL::Problem< Real >::getPrimalOptimizationVector(), ROL::Problem< Real >::getProblemType(), ROL::Problem< Real >::getResidualVector(), and ROL::TYPE_E.
run() [2/5]
template<typename Real > void ROL::TypeE::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, std::ostream & outStream = std::cout) virtual
Run algorithm on equality constrained problems (Type-E). This is the primary Type-E interface.
Definition at line 90 of file ROL_TypeE_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), and ROL::Problem< Real >::finalize().
run() [3/5]
template<typename Real > virtual void ROL::TypeE::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, std::ostream & outStream = std::cout) pure virtual
Run algorithm on equality constrained problems (Type-E). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implemented in ROL::TypeE::AugmentedLagrangianAlgorithm< Real >, ROL::TypeE::CompositeStepAlgorithm< Real >, ROL::TypeE::FletcherAlgorithm< Real >, and ROL::TypeE::StabilizedLCLAlgorithm< Real >.
run() [4/5]
template<typename Real > void ROL::TypeE::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, std::ostream & outStream = std::cout) virtual
Run algorithm on equality constrained problems with explicit linear equality constraints (Type-E). This is the primary Type-E with explicit linear equality constraints interface.
Definition at line 103 of file ROL_TypeE_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), and ROL::Problem< Real >::finalize().
run() [5/5]
template<typename Real > void ROL::TypeE::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) virtual
Run algorithm on equality constrained problems with explicit linear equality constraints (Type-E). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Definition at line 119 of file ROL_TypeE_Algorithm_Def.hpp.
References ROL::Problem< Real >::addConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
writeHeader()
template<typename Real > void ROL::TypeE::Algorithm< Real >::writeHeader (std::ostream & os) const virtual
Print iterate header.
Reimplemented in ROL::TypeE::AugmentedLagrangianAlgorithm< Real >, ROL::TypeE::CompositeStepAlgorithm< Real >, ROL::TypeE::FletcherAlgorithm< Real >, and ROL::TypeE::StabilizedLCLAlgorithm< Real >.
Definition at line 146 of file ROL_TypeE_Algorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeE::Algorithm< Real >::writeName (std::ostream & os) const virtual
Print step name.
Reimplemented in ROL::TypeE::AugmentedLagrangianAlgorithm< Real >, ROL::TypeE::CompositeStepAlgorithm< Real >, ROL::TypeE::FletcherAlgorithm< Real >, and ROL::TypeE::StabilizedLCLAlgorithm< Real >.
Definition at line 161 of file ROL_TypeE_Algorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeE::Algorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const virtual
Print iterate status.
Reimplemented in ROL::TypeE::AugmentedLagrangianAlgorithm< Real >, ROL::TypeE::CompositeStepAlgorithm< Real >, ROL::TypeE::FletcherAlgorithm< Real >, and ROL::TypeE::StabilizedLCLAlgorithm< Real >.
Definition at line 166 of file ROL_TypeE_Algorithm_Def.hpp.
writeExitStatus()
template<typename Real > void ROL::TypeE::Algorithm< Real >::writeExitStatus (std::ostream & os) const virtual
Definition at line 193 of file ROL_TypeE_Algorithm_Def.hpp.
References ROL::EExitStatusToString().
Referenced by ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::run(), ROL::TypeE::CompositeStepAlgorithm< Real >::run(), ROL::TypeE::FletcherAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
getState()
template<typename Real > Ptr< const AlgorithmState< Real > > ROL::TypeE::Algorithm< Real >::getState () const
Definition at line 202 of file ROL_TypeE_Algorithm_Def.hpp.
reset()
template<typename Real > void ROL::TypeE::Algorithm< Real >::reset ()
Definition at line 208 of file ROL_TypeE_Algorithm_Def.hpp.
Referenced by ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm(), ROL::TypeE::CompositeStepAlgorithm< Real >::CompositeStepAlgorithm(), ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
Member Data Documentation
status_
template<typename Real > const Ptr<CombinedStatusTest<Real> > ROL::TypeE::Algorithm< Real >::status_ protected
Definition at line 56 of file ROL_TypeE_Algorithm.hpp.
Referenced by ROL::TypeE::Algorithm< Real >::Algorithm(), ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm(), ROL::TypeE::CompositeStepAlgorithm< Real >::CompositeStepAlgorithm(), ROL::TypeE::FletcherAlgorithm< Real >::FletcherAlgorithm(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
state_
template<typename Real > const Ptr<AlgorithmState<Real> > ROL::TypeE::Algorithm< Real >::state_ protected
Definition at line 57 of file ROL_TypeE_Algorithm.hpp.
Referenced by ROL::TypeE::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::StabilizedLCLAlgorithm().
The documentation for this class was generated from the following files:
ROL_TypeE_Algorithm.hpp
ROL_TypeE_Algorithm_Def.hpp