ROL: ROL::Bounds< Real > Class Template Reference
ROL::Bounds< Real > Class Template Reference
User Interface » Functional Interface
Provides the elementwise interface to apply upper and lower bound constraints.
#include <ROL_Bounds.hpp>
Classes
class Active
class BuildC
class isGreater
class LowerBinding
class PruneBinding
class SetZeroEntry
class UpperBinding
Public Member Functions
Bounds (const Vector< Real > &x, bool isLower=true, Real scale=1, Real feasTol=std::sqrt(ROL_EPSILON< Real >()))
Bounds (const Ptr< Vector< Real > > &x_lo, const Ptr< Vector< Real > > &x_up, const Real scale=1, const Real feasTol=std::sqrt(ROL_EPSILON< Real >()))
void project (Vector< Real > &x) override
Project optimization variables onto the bounds.
void projectInterior (Vector< Real > &x) override
Project optimization variables into the interior of the feasible set.
void pruneUpperActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0)) override
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
void pruneUpperActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0)) override
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
void pruneLowerActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0)) override
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
void pruneLowerActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0)) override
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
bool isFeasible (const Vector< Real > &v) override
Check if the vector, v, is feasible.
void applyInverseScalingFunction (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const override
Apply inverse scaling function.
void applyScalingFunctionJacobian (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const override
Apply scaling function Jacobian.
Public Member Functions inherited from ROL::BoundConstraint< Real >
virtual ~BoundConstraint ()
BoundConstraint (void)
BoundConstraint (const Vector< Real > &x)
virtual const Ptr< const Vector< Real > > getLowerBound (void) const
Return the ref count pointer to the lower bound vector.
virtual const Ptr< const Vector< Real > > getUpperBound (void) const
Return the ref count pointer to the upper bound vector.
void activateLower (void)
Turn on lower bound.
void activateUpper (void)
Turn on upper bound.
void activate (void)
Turn on bounds.
void deactivateLower (void)
Turn off lower bound.
void deactivateUpper (void)
Turn off upper bound.
void deactivate (void)
Turn off bounds.
bool isLowerActivated (void) const
Check if lower bound are on.
bool isUpperActivated (void) const
Check if upper bound are on.
bool isActivated (void) const
Check if bounds are on.
void pruneActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-active set.
void pruneActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void computeProjectedGradient (Vector< Real > &g, const Vector< Real > &x)
Compute projected gradient.
void computeProjectedStep (Vector< Real > &v, const Vector< Real > &x)
Compute projected step.
Private Member Functions
void buildScalingFunction (Vector< Real > &d, const Vector< Real > &x, const Vector< Real > &g) const
Private Attributes
const Real scale_
const Real feasTol_
Ptr< Vector< Real > > mask_
Real min_diff_
Elementwise::ReductionMin< Real > minimum_
Elementwise::ReductionMax< Real > maximum_
ROL::Bounds::isGreater isGreater_
ROL::Bounds::PruneBinding prune_
ROL::Bounds::BuildC buildC_
ROL::Bounds::SetZeroEntry setZeroEntry_
Additional Inherited Members
Protected Member Functions inherited from ROL::BoundConstraint< Real >
Real computeInf (const Vector< Real > &x) const
Protected Attributes inherited from ROL::BoundConstraint< Real >
Ptr< Vector< Real > > lower_
Ptr< Vector< Real > > upper_
Detailed Description
template<typename Real>
class ROL::Bounds< Real >
Provides the elementwise interface to apply upper and lower bound constraints.
Definition at line 25 of file ROL_Bounds.hpp.
Constructor & Destructor Documentation
Bounds() [1/2]
template<typename Real > Bounds::Bounds (const Vector< Real > & x, bool isLower = true, Real scale = 1, Real feasTol = std::sqrt(ROL_EPSILON<Real>()))
Definition at line 25 of file ROL_Bounds_Def.hpp.
References ROL::BoundConstraint< Real >::activateLower(), ROL::BoundConstraint< Real >::activateUpper(), ROL::Vector< Real >::clone(), ROL::BoundConstraint< Real >::lower_, and ROL::BoundConstraint< Real >::upper_.
Bounds() [2/2]
template<typename Real > Bounds::Bounds (const Ptr< Vector< Real > > & x_lo, const Ptr< Vector< Real > > & x_up, const Real scale = 1, const Real feasTol = std::sqrt(ROL_EPSILON<Real>()))
Definition at line 42 of file ROL_Bounds_Def.hpp.
References ROL::BoundConstraint< Real >::lower_, ROL::Bounds< Real >::mask_, ROL::Bounds< Real >::min_diff_, ROL::Bounds< Real >::minimum_, and ROL::BoundConstraint< Real >::upper_.
Member Function Documentation
buildScalingFunction()
template<typename Real > void Bounds::buildScalingFunction (Vector< Real > & d, const Vector< Real > & x, const Vector< Real > & g) const private
Definition at line 195 of file ROL_Bounds_Def.hpp.
References ROL::Vector< Real >::applyBinary(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::plus(), ROL::Vector< Real >::set(), ROL::Vector< Real >::setScalar(), and zero.
Referenced by ROL::Bounds< Real >::applyInverseScalingFunction(), and ROL::Bounds< Real >::applyScalingFunctionJacobian().
project()
template<typename Real > void Bounds::project (Vector< Real > & x) override virtual
Project optimization variables onto the bounds.
This function implements the projection of \(x\) onto the bounds, i.e.,
\[ (P_{[a,b]}(x))(\xi) = \min\{b(\xi),\max\{a(\xi),x(\xi)\}\} \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 57 of file ROL_Bounds_Def.hpp.
References ROL::apply(), and ROL::Vector< Real >::applyBinary().
projectInterior()
template<typename Real > void Bounds::projectInterior (Vector< Real > & x) override virtual
Project optimization variables into the interior of the feasible set.
This function implements the projection of \(x\) into the interior of the feasible set, i.e.,
\[ (\bar{P}_{[a,b]}(x))(\xi) \in (a(\xi),b(\xi)) \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 75 of file ROL_Bounds_Def.hpp.
References ROL::apply(), and ROL::Vector< Real >::applyBinary().
Referenced by testRandomInputs().
pruneUpperActive() [1/2]
template<typename Real > void Bounds::pruneUpperActive (Vector< Real > & v, const Vector< Real > & x, Real eps = Real(0)) override virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-active set is defined as
\[ \mathcal{A}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 122 of file ROL_Bounds_Def.hpp.
References ROL::Vector< Real >::applyBinary().
pruneUpperActive() [2/2]
template<typename Real > void Bounds::pruneUpperActive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) override virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon_x,\; g(\xi) < -\epsilon_g \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 135 of file ROL_Bounds_Def.hpp.
References ROL::Vector< Real >::applyBinary().
pruneLowerActive() [1/2]
template<typename Real > void Bounds::pruneLowerActive (Vector< Real > & v, const Vector< Real > & x, Real eps = Real(0)) override virtual
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-active set is defined as
\[ \mathcal{A}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 150 of file ROL_Bounds_Def.hpp.
References ROL::Vector< Real >::applyBinary().
pruneLowerActive() [2/2]
template<typename Real > void Bounds::pruneLowerActive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) override virtual
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon,\; g(\xi) > 0 \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 163 of file ROL_Bounds_Def.hpp.
References ROL::Vector< Real >::applyBinary().
isFeasible()
template<typename Real > bool Bounds::isFeasible (const Vector< Real > & v) override virtual
Check if the vector, v, is feasible.
This function returns true if \(v = P_{[a,b]}(v)\).
Parameters
[in] v is the vector to be checked.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 178 of file ROL_Bounds_Def.hpp.
applyInverseScalingFunction()
template<typename Real > void Bounds::applyInverseScalingFunction (Vector< Real > & dv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g) const override virtual
Apply inverse scaling function.
This function applies the inverse scaling function \(d(x,g)\) to a vector \(v\), i.e., the output is \(\mathrm{diag}(d(x,g)^{-1})v\). The scaling function must satisfy: (i) \(d(x,g)_i = 0\) if \(x_i = a_i\) and \(g_i \ge 0\); (ii) \(d(x,g)_i = 0\) if \(x_i = b_i\) and \(g_i \le 0\); and (iii) \(d(x,g)_i > 0\) otherwise.
Parameters
[out] dv is the inverse scaling function applied to v.
[in] v is the vector being scaled.
[in] x is the primal vector at which the scaling function is evaluated.
[in] g is the dual vector at which the scaling function is evaluated.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 255 of file ROL_Bounds_Def.hpp.
References ROL::Vector< Real >::applyBinary(), and ROL::Bounds< Real >::buildScalingFunction().
Referenced by testCases(), and testRandomInputs().
applyScalingFunctionJacobian()
template<typename Real > void Bounds::applyScalingFunctionJacobian (Vector< Real > & dv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g) const override virtual
Apply scaling function Jacobian.
This function applies the Jacobian of the scaling function \(d(x,g)\) to a vector \(v\). The output is \(\mathrm{diag}(d_x(x,g)g)v\). The scaling function must satisfy: (i) \(d(x,g)_i = 0\) if \(x_i = a_i\) and \(g_i \ge 0\); (ii) \(d(x,g)_i = 0\) if \(x_i = b_i\) and \(g_i \le 0\); and (iii) \(d(x,g)_i > 0\) otherwise.
Parameters
[out] dv is the scaling function Jacobian applied to v.
[in] v is the vector being scaled.
[in] x is the primal vector at which the scaling function is evaluated.
[in] g is the dual vector at which the scaling function is evaluated.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 261 of file ROL_Bounds_Def.hpp.
References ROL::Vector< Real >::applyBinary(), ROL::Vector< Real >::axpy(), ROL::Bounds< Real >::buildScalingFunction(), ROL::Vector< Real >::plus(), and ROL::Vector< Real >::setScalar().
Referenced by testCases(), and testRandomInputs().
Member Data Documentation
scale_
template<typename Real > const Real ROL::Bounds< Real >::scale_ private
Definition at line 27 of file ROL_Bounds.hpp.
feasTol_
template<typename Real > const Real ROL::Bounds< Real >::feasTol_ private
Definition at line 28 of file ROL_Bounds.hpp.
mask_
template<typename Real > Ptr<Vector<Real> > ROL::Bounds< Real >::mask_ private
Definition at line 33 of file ROL_Bounds.hpp.
Referenced by ROL::Bounds< Real >::Bounds().
min_diff_
template<typename Real > Real ROL::Bounds< Real >::min_diff_ private
Definition at line 35 of file ROL_Bounds.hpp.
Referenced by ROL::Bounds< Real >::Bounds().
minimum_
template<typename Real > Elementwise::ReductionMin<Real> ROL::Bounds< Real >::minimum_ private
Definition at line 37 of file ROL_Bounds.hpp.
Referenced by ROL::Bounds< Real >::Bounds().
maximum_
template<typename Real > Elementwise::ReductionMax<Real> ROL::Bounds< Real >::maximum_ private
Definition at line 38 of file ROL_Bounds.hpp.
isGreater_
template<typename Real > ROL::Bounds::isGreater ROL::Bounds< Real >::isGreater_ private
prune_
template<typename Real > ROL::Bounds::PruneBinding ROL::Bounds< Real >::prune_ private
buildC_
template<typename Real > ROL::Bounds::BuildC ROL::Bounds< Real >::buildC_ private
setZeroEntry_
template<typename Real > ROL::Bounds::SetZeroEntry ROL::Bounds< Real >::setZeroEntry_ private
The documentation for this class was generated from the following files:
ROL_Bounds.hpp
ROL_Bounds_Def.hpp