ROL: ROL::DyadicOperator< Real > Class Template Reference
ROL::DyadicOperator< Real > Class Template Reference
User Interface » Functional Interface
Interface to apply a dyadic operator to a vector.
#include <ROL_DyadicOperator.hpp>
Public Member Functions
DyadicOperator (const ROL::Ptr< const V > &x, const ROL::Ptr< const V > &y)
void apply (V &Hv, const V &v, Real &tol) const
Apply linear operator.
void applyInverse (V &Hv, const V &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Types
typedef ROL::Vector< Real > V
Private Attributes
const ROL::Ptr< const V > x_
const ROL::Ptr< const V > y_
Detailed Description
template<class Real>
class ROL::DyadicOperator< Real >
Interface to apply a dyadic operator to a vector.
Definition at line 25 of file ROL_DyadicOperator.hpp.
Member Typedef Documentation
V
template<class Real > typedef ROL::Vector<Real> ROL::DyadicOperator< Real >::V private
Definition at line 27 of file ROL_DyadicOperator.hpp.
Constructor & Destructor Documentation
DyadicOperator()
template<class Real > ROL::DyadicOperator< Real >::DyadicOperator (const ROL::Ptr< const V > & x, const ROL::Ptr< const V > & y) inline
Definition at line 36 of file ROL_DyadicOperator.hpp.
Member Function Documentation
apply()
template<class Real > void ROL::DyadicOperator< Real >::apply (V & Hv, const V & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 39 of file ROL_DyadicOperator.hpp.
References ROL::Vector< Real >::dot(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::DyadicOperator< Real >::x_, and ROL::DyadicOperator< Real >::y_.
applyInverse()
template<class Real > void ROL::DyadicOperator< Real >::applyInverse (V & Hv, const V & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 44 of file ROL_DyadicOperator.hpp.
Member Data Documentation
x_
template<class Real > const ROL::Ptr<const V> ROL::DyadicOperator< Real >::x_ private
Definition at line 31 of file ROL_DyadicOperator.hpp.
Referenced by ROL::DyadicOperator< Real >::apply().
y_
template<class Real > const ROL::Ptr<const V> ROL::DyadicOperator< Real >::y_ private
Definition at line 32 of file ROL_DyadicOperator.hpp.
Referenced by ROL::DyadicOperator< Real >::apply().
The documentation for this class was generated from the following file:
ROL_DyadicOperator.hpp