ROL: ROL::InteriorPoint::PrimalDualSymmetrizer< Real > Class Template Reference
ROL::InteriorPoint::PrimalDualSymmetrizer< Real > Class Template Reference
#include <ROL_InteriorPointPrimalDualResidual.hpp>
Public Member Functions
PrimalDualSymmetrizer (const V &s)
void update (const V &s, bool flag=true, int iter=-1)
Update linear operator.
void apply (V &Hv, const V &v, Real &tol) const
Apply linear operator.
void applyInverse (V &Hv, const V &v, Real &tol) const
Apply inverse of linear operator.
PrimalDualSymmetrizer (const V &s)
void update (const V &s, bool flag=true, int iter=-1)
Update linear operator.
void apply (V &Hv, const V &v, Real &tol) const
Apply linear operator.
void applyInverse (V &Hv, const V &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Types
typedef Vector< Real > V
typedef PartitionedVector< Real > PV
typedef PV::size_type size_type
typedef Vector< Real > V
typedef PartitionedVector< Real > PV
typedef PV::size_type size_type
Private Attributes
ROL::Ptr< V > s_
Static Private Attributes
static const size_type OPT = 0
static const size_type SLACK = 1
static const size_type EQUAL = 2
static const size_type INEQ = 3
Detailed Description
template<class Real>
class ROL::InteriorPoint::PrimalDualSymmetrizer< Real >
Definition at line 233 of file ROL_InteriorPointPrimalDualResidual.hpp.
Member Typedef Documentation
V [1/2]
template<class Real > typedef Vector<Real> ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::V private
Definition at line 237 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
PV [1/2]
template<class Real > typedef PartitionedVector<Real> ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::PV private
Definition at line 238 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
size_type [1/2]
template<class Real > typedef PV::size_type ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::size_type private
Definition at line 240 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
V [2/2]
template<class Real > typedef Vector<Real> ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::V private
Definition at line 235 of file ROL_InteriorPointPrimalDualResidual.hpp.
PV [2/2]
template<class Real > typedef PartitionedVector<Real> ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::PV private
Definition at line 236 of file ROL_InteriorPointPrimalDualResidual.hpp.
size_type [2/2]
template<class Real > typedef PV::size_type ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::size_type private
Definition at line 238 of file ROL_InteriorPointPrimalDualResidual.hpp.
Constructor & Destructor Documentation
PrimalDualSymmetrizer() [1/2]
template<class Real > ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::PrimalDualSymmetrizer (const V & s) inline
Definition at line 252 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::Vector< Real >::clone(), and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_.
PrimalDualSymmetrizer() [2/2]
template<class Real > ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::PrimalDualSymmetrizer (const V & s) inline
Definition at line 250 of file ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::Vector< Real >::clone(), and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_.
Member Function Documentation
update() [1/2]
template<class Real > void ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::update (const V & x, bool flag = true, int iter = -1) inline virtual
Update linear operator.
This function updates the linear operator at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 257 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_.
apply() [1/2]
template<class Real > void ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply (V & Hv, const V & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 261 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::EQUAL, ROL::PartitionedVector< Real >::get(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::INEQ, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::OPT, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_, and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::SLACK.
applyInverse() [1/2]
template<class Real > void ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse (V & Hv, const V & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 293 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::EQUAL, ROL::PartitionedVector< Real >::get(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::INEQ, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::OPT, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_, and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::SLACK.
update() [2/2]
template<class Real > void ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::update (const V & x, bool flag = true, int iter = -1) inline virtual
Update linear operator.
This function updates the linear operator at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 255 of file ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_.
apply() [2/2]
template<class Real > void ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply (V & Hv, const V & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 259 of file ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::EQUAL, ROL::PartitionedVector< Real >::get(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::INEQ, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::OPT, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_, and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::SLACK.
applyInverse() [2/2]
template<class Real > void ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse (V & Hv, const V & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 291 of file ROL_InteriorPointPrimalDualResidual.hpp.
References ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::EQUAL, ROL::PartitionedVector< Real >::get(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::INEQ, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::OPT, ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_, and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::SLACK.
Member Data Documentation
s_
template<class Real > ROL::Ptr< V > ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::s_ private
Definition at line 243 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
Referenced by ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse(), ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::PrimalDualSymmetrizer(), and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::update().
OPT
template<class Real > static const size_type ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::OPT = 0 static private
Definition at line 245 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
Referenced by ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply(), and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse().
SLACK
template<class Real > static const size_type ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::SLACK = 1 static private
Definition at line 246 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
Referenced by ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply(), and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse().
EQUAL
template<class Real > static const size_type ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::EQUAL = 2 static private
Definition at line 247 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
Referenced by ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply(), and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse().
INEQ
template<class Real > static const size_type ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::INEQ = 3 static private
Definition at line 248 of file interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp.
Referenced by ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::apply(), and ROL::InteriorPoint::PrimalDualSymmetrizer< Real >::applyInverse().
The documentation for this class was generated from the following files:
interiorpoint/ROL_InteriorPointPrimalDualResidual.hpp
ROL_InteriorPointPrimalDualResidual.hpp