ROL: FunctionZakharov< ScalarT > Class Template Reference
FunctionZakharov< ScalarT > Class Template Reference
#include <example_01b.hpp>
Public Member Functions
ScalarT eval (const std::vector< ScalarT > &x)
A Sacado-accessible version of the Zakharov function to differentiate.
Detailed Description
template<class ScalarT>
class FunctionZakharov< ScalarT >
Definition at line 26 of file example_01b.hpp.
Member Function Documentation
eval()
template<class ScalarT > ScalarT FunctionZakharov< ScalarT >::eval (const std::vector< ScalarT > & x)
A Sacado-accessible version of the Zakharov function to differentiate.
\[f(\mathbf{x}) = \mathbf{x}^\top\mathbf{x} + \frac{1}{4}(\mathbf{k}^\top \mathbf{x})^2 + \frac{1}{16}(\mathbf{k}^\top \mathbf{x})^4 \]
Where \(\mathbf{k}=(1,\cdots,n)\)
Parameters
[in] x is the optimization vector
Returns the value of the objective function.
Definition at line 47 of file example_01b.hpp.
Referenced by Zakharov_Sacado_Objective< Real >::gradient(), Zakharov_Sacado_Objective< Real >::hessVec(), and Zakharov_Sacado_Objective< Real >::value().
The documentation for this class was generated from the following file:
example_01b.hpp