ROL: ROL::TestProblem< Real > Class Template Reference
ROL::TestProblem< Real > Class Template Reference abstract
#include <ROL_TestProblem.hpp>
Public Member Functions
virtual ~TestProblem (void)
TestProblem (void)
virtual Ptr< Objective< Real > > getObjective (void) const =0
virtual Ptr< Vector< Real > > getInitialGuess (void) const =0
virtual Ptr< Vector< Real > > getSolution (const int i=0) const =0
virtual int getNumSolutions (void) const
virtual Ptr< BoundConstraint< Real > > getBoundConstraint (void) const
virtual Ptr< Constraint< Real > > getEqualityConstraint (void) const
virtual Ptr< Vector< Real > > getEqualityMultiplier (void) const
virtual Ptr< Constraint< Real > > getInequalityConstraint (void) const
virtual Ptr< Vector< Real > > getInequalityMultiplier (void) const
virtual Ptr< BoundConstraint< Real > > getSlackBoundConstraint (void) const
void get (Ptr< OptimizationProblem< Real > > &problem, Ptr< Vector< Real > > &x0, std::vector< Ptr< Vector< Real > > > &x) const
Detailed Description
template<class Real>
class ROL::TestProblem< Real >
Definition at line 23 of file ROL_TestProblem.hpp.
Constructor & Destructor Documentation
~TestProblem()
template<class Real > virtual ROL::TestProblem< Real >::~TestProblem (void) inline virtual
Definition at line 25 of file ROL_TestProblem.hpp.
TestProblem()
template<class Real > ROL::TestProblem< Real >::TestProblem (void) inline
Definition at line 26 of file ROL_TestProblem.hpp.
Member Function Documentation
getObjective()
template<class Real > virtual Ptr< Objective< Real > > ROL::TestProblem< Real >::getObjective (void) const pure virtual
Implemented in ROL::ZOO::getBeale< Real >, ROL::ZOO::getBVP< Real >, ROL::ZOO::getCantilever< Real >, ROL::ZOO::getCantileverBeam< Real >, ROL::ZOO::getCubic< Real >, ROL::ZOO::getCylinderHead< Real >, ROL::ZOO::getFreudensteinRoth< Real >, ROL::ZOO::getHS1< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS2< Real >, ROL::ZOO::getHS21< Real >, ROL::ZOO::getHS24< Real >, ROL::ZOO::getHS25< Real >, ROL::ZOO::getHS28< Real >, ROL::ZOO::getHS29< Real >, ROL::ZOO::getHS3< Real >, ROL::ZOO::getHS32< Real >, ROL::ZOO::getHS38< Real >, ROL::ZOO::getHS39< Real >, ROL::ZOO::getHS4< Real >, ROL::ZOO::getHS41< Real >, ROL::ZOO::getHS42< Real >, ROL::ZOO::getHS45< Real >, ROL::ZOO::getHS48< Real >, ROL::ZOO::getHS49< Real >, ROL::ZOO::getHS5< Real >, ROL::ZOO::getHS50< Real >, ROL::ZOO::getHS51< Real >, ROL::ZOO::getHS52< Real >, ROL::ZOO::getHS53< Real >, ROL::ZOO::getHS55< Real >, ROL::ZOO::getHS63< Real >, ROL::ZOO::getHS9< Real >, ROL::ZOO::getLeastSquares< Real >, ROL::ZOO::getMinimax1< Real >, ROL::ZOO::getMinimax2< Real >, ROL::ZOO::getMinimax3< Real >, ROL::ZOO::getParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::getPoissonControl< Real >, ROL::ZOO::getPoissonInversion< Real >, ROL::ZOO::getPowell< Real >, ROL::ZOO::getQuartic< Real >, ROL::ZOO::getRosenbrock< Real >, ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::getSumOfSquares< Real >, and ROL::ZOO::getZakharov< Real >.
Referenced by ROL::TestProblem< Real >::get().
getInitialGuess()
template<class Real > virtual Ptr< Vector< Real > > ROL::TestProblem< Real >::getInitialGuess (void) const pure virtual
Implemented in ROL::ZOO::getBeale< Real >, ROL::ZOO::getBVP< Real >, ROL::ZOO::getCantilever< Real >, ROL::ZOO::getCantileverBeam< Real >, ROL::ZOO::getCubic< Real >, ROL::ZOO::getCylinderHead< Real >, ROL::ZOO::getFreudensteinRoth< Real >, ROL::ZOO::getHS1< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS2< Real >, ROL::ZOO::getHS21< Real >, ROL::ZOO::getHS24< Real >, ROL::ZOO::getHS25< Real >, ROL::ZOO::getHS28< Real >, ROL::ZOO::getHS29< Real >, ROL::ZOO::getHS3< Real >, ROL::ZOO::getHS32< Real >, ROL::ZOO::getHS38< Real >, ROL::ZOO::getHS39< Real >, ROL::ZOO::getHS4< Real >, ROL::ZOO::getHS41< Real >, ROL::ZOO::getHS42< Real >, ROL::ZOO::getHS45< Real >, ROL::ZOO::getHS48< Real >, ROL::ZOO::getHS49< Real >, ROL::ZOO::getHS5< Real >, ROL::ZOO::getHS50< Real >, ROL::ZOO::getHS51< Real >, ROL::ZOO::getHS52< Real >, ROL::ZOO::getHS53< Real >, ROL::ZOO::getHS55< Real >, ROL::ZOO::getHS63< Real >, ROL::ZOO::getHS9< Real >, ROL::ZOO::getLeastSquares< Real >, ROL::ZOO::getMinimax1< Real >, ROL::ZOO::getMinimax2< Real >, ROL::ZOO::getMinimax3< Real >, ROL::ZOO::getParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::getPoissonControl< Real >, ROL::ZOO::getPoissonInversion< Real >, ROL::ZOO::getPowell< Real >, ROL::ZOO::getQuartic< Real >, ROL::ZOO::getRosenbrock< Real >, ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::getSumOfSquares< Real >, and ROL::ZOO::getZakharov< Real >.
Referenced by ROL::TestProblem< Real >::get().
getSolution()
template<class Real > virtual Ptr< Vector< Real > > ROL::TestProblem< Real >::getSolution (const int i = 0) const pure virtual
Implemented in ROL::ZOO::getBeale< Real >, ROL::ZOO::getBVP< Real >, ROL::ZOO::getCantilever< Real >, ROL::ZOO::getCantileverBeam< Real >, ROL::ZOO::getCubic< Real >, ROL::ZOO::getCylinderHead< Real >, ROL::ZOO::getFreudensteinRoth< Real >, ROL::ZOO::getHS1< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS2< Real >, ROL::ZOO::getHS21< Real >, ROL::ZOO::getHS24< Real >, ROL::ZOO::getHS25< Real >, ROL::ZOO::getHS28< Real >, ROL::ZOO::getHS29< Real >, ROL::ZOO::getHS3< Real >, ROL::ZOO::getHS32< Real >, ROL::ZOO::getHS38< Real >, ROL::ZOO::getHS39< Real >, ROL::ZOO::getHS4< Real >, ROL::ZOO::getHS41< Real >, ROL::ZOO::getHS42< Real >, ROL::ZOO::getHS45< Real >, ROL::ZOO::getHS48< Real >, ROL::ZOO::getHS49< Real >, ROL::ZOO::getHS5< Real >, ROL::ZOO::getHS50< Real >, ROL::ZOO::getHS51< Real >, ROL::ZOO::getHS52< Real >, ROL::ZOO::getHS53< Real >, ROL::ZOO::getHS55< Real >, ROL::ZOO::getHS63< Real >, ROL::ZOO::getHS9< Real >, ROL::ZOO::getLeastSquares< Real >, ROL::ZOO::getMinimax1< Real >, ROL::ZOO::getMinimax2< Real >, ROL::ZOO::getMinimax3< Real >, ROL::ZOO::getParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::getPoissonControl< Real >, ROL::ZOO::getPoissonInversion< Real >, ROL::ZOO::getPowell< Real >, ROL::ZOO::getQuartic< Real >, ROL::ZOO::getRosenbrock< Real >, ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >, ROL::ZOO::getSumOfSquares< Real >, and ROL::ZOO::getZakharov< Real >.
Referenced by ROL::TestProblem< Real >::get().
getNumSolutions()
template<class Real > virtual int ROL::TestProblem< Real >::getNumSolutions (void) const inline virtual
Reimplemented in ROL::ZOO::getFreudensteinRoth< Real >, and ROL::ZOO::getHS29< Real >.
Definition at line 30 of file ROL_TestProblem.hpp.
Referenced by ROL::TestProblem< Real >::get().
getBoundConstraint()
template<class Real > virtual Ptr< BoundConstraint< Real > > ROL::TestProblem< Real >::getBoundConstraint (void) const inline virtual
Reimplemented in ROL::ZOO::getBVP< Real >, ROL::ZOO::getCantilever< Real >, ROL::ZOO::getCantileverBeam< Real >, ROL::ZOO::getCubic< Real >, ROL::ZOO::getCylinderHead< Real >, ROL::ZOO::getHS1< Real >, ROL::ZOO::getHS2< Real >, ROL::ZOO::getHS21< Real >, ROL::ZOO::getHS24< Real >, ROL::ZOO::getHS25< Real >, ROL::ZOO::getHS29< Real >, ROL::ZOO::getHS3< Real >, ROL::ZOO::getHS32< Real >, ROL::ZOO::getHS38< Real >, ROL::ZOO::getHS4< Real >, ROL::ZOO::getHS41< Real >, ROL::ZOO::getHS45< Real >, ROL::ZOO::getHS5< Real >, ROL::ZOO::getHS53< Real >, ROL::ZOO::getHS55< Real >, ROL::ZOO::getHS63< Real >, and ROL::ZOO::getQuartic< Real >.
Definition at line 33 of file ROL_TestProblem.hpp.
Referenced by ROL::TestProblem< Real >::get().
getEqualityConstraint()
template<class Real > virtual Ptr< Constraint< Real > > ROL::TestProblem< Real >::getEqualityConstraint (void) const inline virtual
Reimplemented in ROL::ZOO::getCubic< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS28< Real >, ROL::ZOO::getHS32< Real >, ROL::ZOO::getHS39< Real >, ROL::ZOO::getHS41< Real >, ROL::ZOO::getHS42< Real >, ROL::ZOO::getHS48< Real >, ROL::ZOO::getHS49< Real >, ROL::ZOO::getHS50< Real >, ROL::ZOO::getHS51< Real >, ROL::ZOO::getHS52< Real >, ROL::ZOO::getHS53< Real >, ROL::ZOO::getHS55< Real >, ROL::ZOO::getHS63< Real >, ROL::ZOO::getHS9< Real >, ROL::ZOO::getParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, and ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >.
Definition at line 36 of file ROL_TestProblem.hpp.
Referenced by ROL::TestProblem< Real >::get().
getEqualityMultiplier()
template<class Real > virtual Ptr< Vector< Real > > ROL::TestProblem< Real >::getEqualityMultiplier (void) const inline virtual
Reimplemented in ROL::ZOO::getCubic< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS28< Real >, ROL::ZOO::getHS32< Real >, ROL::ZOO::getHS39< Real >, ROL::ZOO::getHS41< Real >, ROL::ZOO::getHS42< Real >, ROL::ZOO::getHS48< Real >, ROL::ZOO::getHS49< Real >, ROL::ZOO::getHS50< Real >, ROL::ZOO::getHS51< Real >, ROL::ZOO::getHS52< Real >, ROL::ZOO::getHS53< Real >, ROL::ZOO::getHS55< Real >, ROL::ZOO::getHS63< Real >, ROL::ZOO::getHS9< Real >, ROL::ZOO::getParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >, and ROL::ZOO::getSimpleEqConstrained< Real, XPrim, XDual, CPrim, CDual >.
Definition at line 39 of file ROL_TestProblem.hpp.
Referenced by ROL::TestProblem< Real >::get().
getInequalityConstraint()
template<class Real > virtual Ptr< Constraint< Real > > ROL::TestProblem< Real >::getInequalityConstraint (void) const inline virtual
Reimplemented in ROL::ZOO::getCantilever< Real >, ROL::ZOO::getCantileverBeam< Real >, ROL::ZOO::getCubic< Real >, ROL::ZOO::getCylinderHead< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS21< Real >, ROL::ZOO::getHS24< Real >, ROL::ZOO::getHS29< Real >, ROL::ZOO::getHS32< Real >, and ROL::ZOO::getQuartic< Real >.
Definition at line 42 of file ROL_TestProblem.hpp.
Referenced by ROL::TestProblem< Real >::get().
getInequalityMultiplier()
template<class Real > virtual Ptr< Vector< Real > > ROL::TestProblem< Real >::getInequalityMultiplier (void) const inline virtual
Reimplemented in ROL::ZOO::getCantilever< Real >, ROL::ZOO::getCantileverBeam< Real >, ROL::ZOO::getCubic< Real >, ROL::ZOO::getCylinderHead< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS21< Real >, ROL::ZOO::getHS24< Real >, ROL::ZOO::getHS29< Real >, ROL::ZOO::getHS32< Real >, and ROL::ZOO::getQuartic< Real >.
Definition at line 45 of file ROL_TestProblem.hpp.
Referenced by ROL::TestProblem< Real >::get().
getSlackBoundConstraint()
template<class Real > virtual Ptr< BoundConstraint< Real > > ROL::TestProblem< Real >::getSlackBoundConstraint (void) const inline virtual
Reimplemented in ROL::ZOO::getCantilever< Real >, ROL::ZOO::getCantileverBeam< Real >, ROL::ZOO::getCubic< Real >, ROL::ZOO::getCylinderHead< Real >, ROL::ZOO::getHS14< Real >, ROL::ZOO::getHS21< Real >, ROL::ZOO::getHS24< Real >, ROL::ZOO::getHS29< Real >, ROL::ZOO::getHS32< Real >, and ROL::ZOO::getQuartic< Real >.
Definition at line 48 of file ROL_TestProblem.hpp.
Referenced by ROL::TestProblem< Real >::get().
get()
template<class Real > void ROL::TestProblem< Real >::get (Ptr< OptimizationProblem< Real > > & problem, Ptr< Vector< Real > > & x0, std::vector< Ptr< Vector< Real > > > & x) const inline
Definition at line 52 of file ROL_TestProblem.hpp.
References ROL::TestProblem< Real >::getBoundConstraint(), ROL::TestProblem< Real >::getEqualityConstraint(), ROL::TestProblem< Real >::getEqualityMultiplier(), ROL::TestProblem< Real >::getInequalityConstraint(), ROL::TestProblem< Real >::getInequalityMultiplier(), ROL::TestProblem< Real >::getInitialGuess(), ROL::TestProblem< Real >::getNumSolutions(), ROL::TestProblem< Real >::getObjective(), ROL::TestProblem< Real >::getSlackBoundConstraint(), and ROL::TestProblem< Real >::getSolution().
Referenced by main().
The documentation for this class was generated from the following file:
ROL_TestProblem.hpp