ROL: ROL::SerialFunction< Real > Class Template Reference
ROL::SerialFunction< Real > Class Template Reference
User Interface » Functional Interface
Provides behavior common to SerialObjective as SerialConstaint.
#include <ROL_SerialFunction.hpp>
Public Types
using size_type = typename std::vector< Real >::size_type
Public Member Functions
SerialFunction (const Vector< Real > &u_initial, const TimeStampsPtr< Real > &timeStampsPtr)
size_type numTimeSteps () const
const Vector< Real > & getInitialCondition () const
void setInitialCondition (const Vector< Real > &u_initial)
const Vector< Real > & getZeroState () const
bool getSkipInitialCondition () const
void setSkipInitialCondition (bool skip)
TimeStampsPtr< Real > getTimeStampsPtr () const
void setTimeStampsPtr (const TimeStampsPtr< Real > &timeStampsPtr)
TimeStamp< Real > & getTimeStamp (size_type i)
const TimeStamp< Real > & getTimeStamp (size_type i) const
void setTimeStamp (size_type i, const TimeStamp< Real > &timeStamp)
Protected Member Functions
const TimeStamp< Real > & ts (size_type i) const
Ptr< Vector< Real > > clone (const Vector< Real > &x)
Private Types
using PV = PartitionedVector< Real >
Private Attributes
Ptr< Vector< Real > > u_initial_
Ptr< Vector< Real > > u_zero_
TimeStampsPtr< Real > timeStampsPtr_
VectorWorkspace< Real > workspace_
size_type Nt_
bool skipInitialCond_ = false
Detailed Description
template<typename Real>
class ROL::SerialFunction< Real >
Provides behavior common to SerialObjective as SerialConstaint.
Definition at line 26 of file ROL_SerialFunction.hpp.
Member Typedef Documentation
size_type
template<typename Real > using ROL::SerialFunction< Real >::size_type = typename std::vector<Real>::size_type
Definition at line 28 of file ROL_SerialFunction.hpp.
PV
template<typename Real > using ROL::SerialFunction< Real >::PV = PartitionedVector<Real> private
Definition at line 31 of file ROL_SerialFunction.hpp.
Constructor & Destructor Documentation
SerialFunction()
template<typename Real > ROL::SerialFunction< Real >::SerialFunction (const Vector< Real > & u_initial, const TimeStampsPtr< Real > & timeStampsPtr) inline
Definition at line 47 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::u_initial_, and ROL::SerialFunction< Real >::u_zero_.
Member Function Documentation
ts()
template<typename Real > const TimeStamp< Real > & ROL::SerialFunction< Real >::ts (size_type i) const inline protected
Definition at line 42 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::timeStampsPtr_.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_11(), ROL::SerialConstraint< Real >::applyAdjointHessian_22(), ROL::SerialConstraint< Real >::applyAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyAdjointJacobian_2(), ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_2(), ROL::SerialObjective< Real >::gradient_1(), ROL::SerialObjective< Real >::gradient_2(), ROL::SerialObjective< Real >::hessVec_11(), ROL::SerialObjective< Real >::hessVec_12(), ROL::SerialObjective< Real >::hessVec_21(), ROL::SerialObjective< Real >::hessVec_22(), ROL::SerialConstraint< Real >::solve(), ROL::SerialConstraint< Real >::update(), ROL::SerialObjective< Real >::value(), and ROL::SerialConstraint< Real >::value().
clone()
template<typename Real > Ptr< Vector< Real > > ROL::SerialFunction< Real >::clone (const Vector< Real > & x) inline protected
Definition at line 43 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::workspace_.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_11(), ROL::SerialConstraint< Real >::applyAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_1(), ROL::SerialObjective< Real >::gradient_1(), ROL::SerialObjective< Real >::hessVec_11(), ROL::SerialObjective< Real >::hessVec_12(), and ROL::SerialObjective< Real >::hessVec_21().
numTimeSteps()
template<typename Real > size_type ROL::SerialFunction< Real >::numTimeSteps () const inline
Definition at line 57 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::Nt_.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_11(), ROL::SerialConstraint< Real >::applyAdjointHessian_22(), ROL::SerialConstraint< Real >::applyAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyAdjointJacobian_2(), ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_2(), ROL::SerialObjective< Real >::gradient_1(), ROL::SerialObjective< Real >::gradient_2(), ROL::SerialObjective< Real >::hessVec_11(), ROL::SerialObjective< Real >::hessVec_12(), ROL::SerialObjective< Real >::hessVec_21(), ROL::SerialObjective< Real >::hessVec_22(), ROL::SerialConstraint< Real >::solve(), ROL::SerialConstraint< Real >::update(), ROL::SerialObjective< Real >::value(), and ROL::SerialConstraint< Real >::value().
getInitialCondition()
template<typename Real > const Vector< Real > & ROL::SerialFunction< Real >::getInitialCondition () const inline
Definition at line 59 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::u_initial_.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_22(), ROL::SerialConstraint< Real >::applyAdjointJacobian_2(), ROL::SerialConstraint< Real >::applyJacobian_2(), ROL::SerialObjective< Real >::gradient_1(), ROL::SerialObjective< Real >::gradient_2(), ROL::SerialObjective< Real >::hessVec_11(), ROL::SerialObjective< Real >::hessVec_12(), ROL::SerialObjective< Real >::hessVec_21(), ROL::SerialObjective< Real >::hessVec_22(), ROL::SerialConstraint< Real >::solve(), ROL::SerialConstraint< Real >::update(), ROL::SerialObjective< Real >::value(), and ROL::SerialConstraint< Real >::value().
setInitialCondition()
template<typename Real > void ROL::SerialFunction< Real >::setInitialCondition (const Vector< Real > & u_initial) inline
Definition at line 60 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::u_initial_.
getZeroState()
template<typename Real > const Vector< Real > & ROL::SerialFunction< Real >::getZeroState () const inline
Definition at line 62 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::u_zero_.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_11(), ROL::SerialConstraint< Real >::applyAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseJacobian_1(), and ROL::SerialConstraint< Real >::applyJacobian_1().
getSkipInitialCondition()
template<typename Real > bool ROL::SerialFunction< Real >::getSkipInitialCondition () const inline
Definition at line 64 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::skipInitialCond_.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_11(), ROL::SerialConstraint< Real >::applyAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyAdjointJacobian_2(), ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_2(), ROL::SerialObjective< Real >::gradient_2(), ROL::SerialObjective< Real >::hessVec_22(), ROL::SerialConstraint< Real >::solve(), ROL::SerialConstraint< Real >::update(), ROL::SerialObjective< Real >::value(), and ROL::SerialConstraint< Real >::value().
setSkipInitialCondition()
template<typename Real > void ROL::SerialFunction< Real >::setSkipInitialCondition (bool skip) inline
Definition at line 65 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::skipInitialCond_.
getTimeStampsPtr()
template<typename Real > TimeStampsPtr< Real > ROL::SerialFunction< Real >::getTimeStampsPtr () const inline
Definition at line 68 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::timeStampsPtr_.
setTimeStampsPtr()
template<typename Real > void ROL::SerialFunction< Real >::setTimeStampsPtr (const TimeStampsPtr< Real > & timeStampsPtr) inline
Definition at line 70 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::Nt_, and ROL::SerialFunction< Real >::timeStampsPtr_.
getTimeStamp() [1/2]
template<typename Real > TimeStamp< Real > & ROL::SerialFunction< Real >::getTimeStamp (size_type i) inline
Definition at line 76 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::timeStampsPtr_.
getTimeStamp() [2/2]
template<typename Real > const TimeStamp< Real > & ROL::SerialFunction< Real >::getTimeStamp (size_type i) const inline
Definition at line 77 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::timeStampsPtr_.
setTimeStamp()
template<typename Real > void ROL::SerialFunction< Real >::setTimeStamp (size_type i, const TimeStamp< Real > & timeStamp) inline
Definition at line 79 of file ROL_SerialFunction.hpp.
References ROL::SerialFunction< Real >::timeStampsPtr_.
Member Data Documentation
u_initial_
template<typename Real > Ptr<Vector<Real> > ROL::SerialFunction< Real >::u_initial_ private
Definition at line 33 of file ROL_SerialFunction.hpp.
Referenced by ROL::SerialFunction< Real >::getInitialCondition(), ROL::SerialFunction< Real >::SerialFunction(), and ROL::SerialFunction< Real >::setInitialCondition().
u_zero_
template<typename Real > Ptr<Vector<Real> > ROL::SerialFunction< Real >::u_zero_ private
Definition at line 34 of file ROL_SerialFunction.hpp.
Referenced by ROL::SerialFunction< Real >::getZeroState(), and ROL::SerialFunction< Real >::SerialFunction().
timeStampsPtr_
template<typename Real > TimeStampsPtr<Real> ROL::SerialFunction< Real >::timeStampsPtr_ private
Definition at line 35 of file ROL_SerialFunction.hpp.
Referenced by ROL::SerialFunction< Real >::getTimeStamp(), ROL::SerialFunction< Real >::getTimeStamp(), ROL::SerialFunction< Real >::getTimeStampsPtr(), ROL::SerialFunction< Real >::setTimeStamp(), ROL::SerialFunction< Real >::setTimeStampsPtr(), and ROL::SerialFunction< Real >::ts().
workspace_
template<typename Real > VectorWorkspace<Real> ROL::SerialFunction< Real >::workspace_ mutable private
Definition at line 36 of file ROL_SerialFunction.hpp.
Referenced by ROL::SerialFunction< Real >::clone().
Nt_
template<typename Real > size_type ROL::SerialFunction< Real >::Nt_ private
Definition at line 37 of file ROL_SerialFunction.hpp.
Referenced by ROL::SerialFunction< Real >::numTimeSteps(), and ROL::SerialFunction< Real >::setTimeStampsPtr().
skipInitialCond_
template<typename Real > bool ROL::SerialFunction< Real >::skipInitialCond_ = false private
Definition at line 38 of file ROL_SerialFunction.hpp.
Referenced by ROL::SerialFunction< Real >::getSkipInitialCondition(), and ROL::SerialFunction< Real >::setSkipInitialCondition().
The documentation for this class was generated from the following file:
ROL_SerialFunction.hpp