ROL: ROL::Constraint_SerialSimOpt< Real > Class Template Reference
ROL::Constraint_SerialSimOpt< Real > Class Template Reference
User Interface » Functional Interface
Unifies the constraint defined on a single time step that are defined through the Constraint_TimeSimOpt interface into a SimOpt constraint for all time. Primarily intended for use in testing the parallel-in-time implementation.
#include <ROL_Constraint_SerialSimOpt.hpp>
Public Member Functions
Constraint_SerialSimOpt (const Ptr< Con > &con, const V &ui, const V &zi)
virtual void value (V &c, const V &u, const V &z, Real &tol) override
Evaluate the constraint operator \(c:\mathcal{U}\times\mathcal{Z} \rightarrow \mathcal{C}\) at \((u,z)\).
virtual void solve (V &c, V &u, const V &z, Real &tol) override
Given \(z\), solve \(c(u,z)=0\) for \(u\).
virtual void applyJacobian_1 (V &jv, const V &v, const V &u, const V &z, Real &tol) override
Apply the partial constraint Jacobian at \((u,z)\), \(c_u(u,z) \in L(\mathcal{U}, \mathcal{C})\), to the vector \(v\).
virtual void applyJacobian_2 (V &jv, const V &v, const V &u, const V &z, Real &tol) override
Apply the partial constraint Jacobian at \((u,z)\), \(c_z(u,z) \in L(\mathcal{Z}, \mathcal{C})\), to the vector \(v\).
virtual void applyInverseJacobian_1 (V &ijv, const V &v, const V &u, const V &z, Real &tol) override
Apply the inverse partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-1} \in L(\mathcal{C}, \mathcal{U})\), to the vector \(v\).
virtual void applyAdjointJacobian_1 (V &ajv, const V &v, const V &u, const V &z, Real &tol) override
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the primary interface.
virtual void applyAdjointJacobian_1 (V &ajv, const V &v, const V &u, const V &z, const V &dualv, Real &tol) override
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual void applyAdjointJacobian_2 (V &ajv, const V &v, const V &u, const V &z, Real &tol) override
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the primary interface.
virtual void applyAdjointJacobian_2 (V &ajv, const V &v, const V &u, const V &z, const V &dualv, Real &tol) override
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual void applyInverseAdjointJacobian_1 (V &iajv, const V &v, const V &u, const V &z, Real &tol) override
Apply the inverse of the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-*} \in L(\mathcal{U}^*, \mathcal{C}^*)\), to the vector \(v\).
virtual void applyAdjointHessian_11 (V &ahwv, const V &w, const V &v, const V &u, const V &z, Real &tol) override
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_11 (V &ahwv, const V &w, const V &v, const V &u, const V &z, Real &tol) override
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_11 (V &ahwv, const V &w, const V &v, const V &u, const V &z, Real &tol) override
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_11 (V &ahwv, const V &w, const V &v, const V &u, const V &z, Real &tol) override
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
Public Member Functions inherited from ROL::Constraint_SimOpt< Real >
Constraint_SimOpt ()
virtual void update (const Vector< Real > &u, const Vector< Real > &z, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
virtual void update_1 (const Vector< Real > &u, bool flag=true, int iter=-1)
Update constraint functions with respect to Sim variable.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_1 (const Vector< Real > &u, UpdateType type, int iter=-1)
virtual void update_2 (const Vector< Real > &z, bool flag=true, int iter=-1)
Update constraint functions with respect to Opt variable. x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_2 (const Vector< Real > &z, UpdateType type, int iter=-1)
virtual void solve_update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
Update SimOpt constraint during solve (disconnected from optimization updates).
virtual void setSolveParameters (ParameterList &parlist)
Set solve parameters.
virtual void applyAdjointHessian_12 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the optimization-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uz}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_21 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the simulation-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zu}(u,z)(v,\cdot)^*w\).
virtual void applyAdjointHessian_22 (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol)
Apply the optimization-space derivative of the adjoint of the constraint optimization-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{zz}(u,z)(v,\cdot)^*w\).
virtual std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol)
Approximately solves the augmented system
virtual void applyPreconditioner (Vector< Real > &pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C})\), to vector \(v\). In general, this preconditioner satisfies the following relationship:
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update constraint function.
virtual void value (Vector< Real > &c, const Vector< Real > &x, Real &tol)
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
virtual void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual void applyAdjointHessian (Vector< Real > &ahwv, const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
virtual Real checkSolve (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &c, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian_1 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
virtual Real checkAdjointConsistencyJacobian_1 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual Real checkAdjointConsistencyJacobian_2 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the primary interface.
virtual Real checkAdjointConsistencyJacobian_2 (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
Check the consistency of the Jacobian and its adjoint. This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
virtual Real checkInverseJacobian_1 (const Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkInverseAdjointJacobian_1 (const Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, const bool printToStream=true, std::ostream &outStream=std::cout)
std::vector< std::vector< Real > > checkApplyJacobian_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyJacobian_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
\(u\in U \), \(z\in Z \), \(p\in C^\ast \), \(v \in U \), \(hv \in U^\ast \)
std::vector< std::vector< Real > > checkApplyAdjointHessian_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkApplyAdjointHessian_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &p, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Protected Member Functions
PV & partition (V &x) const
const V & partition (const V &x) const
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Private Types
using V = Vector< Real >
using PV = PartitionedVector< Real >
using Con = Constraint_TimeSimOpt< Real >
using size_type = typename PV< Real >::size_type
Private Attributes
const Ptr< Con > con_
const Ptr< V > ui_
Ptr< V > u0_
Pre< V > z0_
VectorWorkspace< Real > workspace_
Additional Inherited Members
Protected Attributes inherited from ROL::Constraint_SimOpt< Real >
Real atol_
Real rtol_
Real stol_
Real factor_
Real decr_
int maxit_
bool print_
bool zero_
int solverType_
bool firstSolve_
Detailed Description
template<typename Real>
class ROL::Constraint_SerialSimOpt< Real >
Unifies the constraint defined on a single time step that are defined through the Constraint_TimeSimOpt interface into a SimOpt constraint for all time. Primarily intended for use in testing the parallel-in-time implementation.
In contrast to Constraint_PinTSimOpt, where the argument vectors are PartitionedVectors with Vector_SimOpt, the approach here is to consider the state and control to be of PartitionedVector type directly.
NOTE: This class does not address non-autonomous systems as constraints. The formulas involving adjoint Jacobians are almost certainly incorrect in such cases. This will need to be fixed if the Constraint_TimeSimOpt interface can accommodate explicit functions of time. Additionally, opt vectors are assumed to be constant in time on a time step.
Definition at line 44 of file ROL_Constraint_SerialSimOpt.hpp.
Member Typedef Documentation
V
template<typename Real > using ROL::Constraint_SerialSimOpt< Real >::V = Vector<Real> private
Definition at line 46 of file ROL_Constraint_SerialSimOpt.hpp.
PV
template<typename Real > using ROL::Constraint_SerialSimOpt< Real >::PV = PartitionedVector<Real> private
Definition at line 47 of file ROL_Constraint_SerialSimOpt.hpp.
Con
template<typename Real > using ROL::Constraint_SerialSimOpt< Real >::Con = Constraint_TimeSimOpt<Real> private
Definition at line 48 of file ROL_Constraint_SerialSimOpt.hpp.
size_type
template<typename Real > using ROL::Constraint_SerialSimOpt< Real >::size_type = typename PV<Real>::size_type private
Definition at line 50 of file ROL_Constraint_SerialSimOpt.hpp.
Constructor & Destructor Documentation
Constraint_SerialSimOpt()
template<typename Real > ROL::Constraint_SerialSimOpt< Real >::Constraint_SerialSimOpt (const Ptr< Con > & con, const V & ui, const V & zi) inline
Definition at line 70 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::u0_, and ROL::Constraint_SerialSimOpt< Real >::z0_.
Member Function Documentation
partition() [1/2]
template<typename Real > PV & ROL::Constraint_SerialSimOpt< Real >::partition (V & x) const inline protected
Definition at line 63 of file ROL_Constraint_SerialSimOpt.hpp.
Referenced by ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SerialSimOpt< Real >::applyInverseAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyInverseJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyJacobian_2(), ROL::Constraint_SerialSimOpt< Real >::solve(), and ROL::Constraint_SerialSimOpt< Real >::value().
partition() [2/2]
template<typename Real > const V & ROL::Constraint_SerialSimOpt< Real >::partition (const V & x) const inline protected
Definition at line 65 of file ROL_Constraint_SerialSimOpt.hpp.
value()
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::value (V & c, const V & u, const V & z, Real & tol) inline override virtual
Evaluate the constraint operator \(c:\mathcal{U}\times\mathcal{Z} \rightarrow \mathcal{C}\) at \((u,z)\).
Parameters
[out] c is the result of evaluating the constraint operator at \((u,z)\); a constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(u,z)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{u} \in \mathcal{U}\), and $ \(\mathsf{z} \in\mathcal{Z}\).
Implements ROL::Constraint_SimOpt< Real >.
Definition at line 86 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, ROL::Constraint_SerialSimOpt< Real >::partition(), and ROL::Constraint_SerialSimOpt< Real >::ui_.
solve()
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::solve (V & c, V & u, const V & z, Real & tol) inline override virtual
Given \(z\), solve \(c(u,z)=0\) for \(u\).
   @param[out]      c   is the result of evaluating the constraint operator at @b \f$(u,z)\f$; a constraint-space vector
   @param[in,out]   u   is the solution vector; a simulation-space vector
   @param[in]       z   is the constraint argument; an optimization-space vector
   @param[in,out]   tol is a tolerance for inexact evaluations; currently unused
   The defualt implementation is Newton's method globalized with a backtracking line search.
   ---
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 100 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, ROL::Constraint_SerialSimOpt< Real >::partition(), and ROL::Constraint_SerialSimOpt< Real >::ui_.
applyJacobian_1()
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyJacobian_1 (V & jv, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the partial constraint Jacobian at \((u,z)\), \(c_u(u,z) \in L(\mathcal{U}, \mathcal{C})\), to the vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at \((u,z)\); a constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; an simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c_u(u,z)v\), where \(v \in \mathcal{U}\), \(\mathsf{jv} \in \mathcal{C}\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 114 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, ROL::Constraint_SerialSimOpt< Real >::partition(), ROL::Constraint_SerialSimOpt< Real >::u0_, and ROL::Constraint_SerialSimOpt< Real >::workspace_.
applyJacobian_2()
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyJacobian_2 (V & jv, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the partial constraint Jacobian at \((u,z)\), \(c_z(u,z) \in L(\mathcal{Z}, \mathcal{C})\), to the vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at \((u,z)\); a constraint-space vector
[in] v is an optimization-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c_z(u,z)v\), where \(v \in \mathcal{Z}\), \(\mathsf{jv} \in \mathcal{C}\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 130 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, and ROL::Constraint_SerialSimOpt< Real >::partition().
applyInverseJacobian_1()
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyInverseJacobian_1 (V & ijv, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the inverse partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-1} \in L(\mathcal{C}, \mathcal{U})\), to the vector \(v\).
Parameters
[out] ijv is the result of applying the inverse constraint Jacobian to v at \((u,z)\); a simulation-space vector
[in] v is a constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ijv} = c_u(u,z)^{-1}v\), where \(v \in \mathcal{C}\), \(\mathsf{ijv} \in \mathcal{U}\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 141 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, ROL::Constraint_SerialSimOpt< Real >::partition(), and ROL::Constraint_SerialSimOpt< Real >::u0_.
applyAdjointJacobian_1() [1/2]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1 (V & ajv, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the primary interface.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at (u,z); a dual simulation-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_u(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 164 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, ROL::Constraint_SerialSimOpt< Real >::partition(), and ROL::Constraint_SerialSimOpt< Real >::u0_.
applyAdjointJacobian_1() [2/2]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1 (V & ajv, const V & v, const V & u, const V & z, const V & dualv, Real & tol) inline override virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^* \in L(\mathcal{C}^*, \mathcal{U}^*)\), to the vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at (u,z); a dual simulation-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] dualv is a vector used for temporary variables; a constraint-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_u(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 191 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, ROL::Constraint_SerialSimOpt< Real >::partition(), and ROL::Constraint_SerialSimOpt< Real >::u0_.
applyAdjointJacobian_2() [1/2]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_2 (V & ajv, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the primary interface.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at \((u,z)\); a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_z(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{Z}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 217 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, and ROL::Constraint_SerialSimOpt< Real >::partition().
applyAdjointJacobian_2() [2/2]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_2 (V & ajv, const V & v, const V & u, const V & z, const V & dualv, Real & tol) inline override virtual
Apply the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_z(u,z)^* \in L(\mathcal{C}^*, \mathcal{Z}^*)\), to vector \(v\). This is the secondary interface, for use with dual spaces where the user does not define the dual() operation.
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at \((u,z)\); a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in] dualv is a vector used for temporary variables; a constraint-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c_z(u,z)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{Z}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 228 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, and ROL::Constraint_SerialSimOpt< Real >::partition().
applyInverseAdjointJacobian_1()
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyInverseAdjointJacobian_1 (V & iajv, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the inverse of the adjoint of the partial constraint Jacobian at \((u,z)\), \(c_u(u,z)^{-*} \in L(\mathcal{U}^*, \mathcal{C}^*)\), to the vector \(v\).
Parameters
[out] iajv is the result of applying the inverse adjoint of the constraint Jacobian to v at (u,z); a dual constraint-space vector
[in] v is a dual simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{iajv} = c_u(u,z)^{-*}v\), where \(v \in \mathcal{U}^*\), \(\mathsf{iajv} \in \mathcal{C}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 240 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Constraint_SerialSimOpt< Real >::con_, ROL::Constraint_SerialSimOpt< Real >::partition(), ROL::Constraint_SerialSimOpt< Real >::u0_, and ROL::Constraint_SerialSimOpt< Real >::workspace_.
applyAdjointHessian_11() [1/4]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointHessian_11 (V & ahwv, const V & w, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 272 of file ROL_Constraint_SerialSimOpt.hpp.
applyAdjointHessian_11() [2/4]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointHessian_11 (V & ahwv, const V & w, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 278 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Vector< Real >::zero().
applyAdjointHessian_11() [3/4]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointHessian_11 (V & ahwv, const V & w, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 283 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Vector< Real >::zero().
applyAdjointHessian_11() [4/4]
template<typename Real > virtual void ROL::Constraint_SerialSimOpt< Real >::applyAdjointHessian_11 (V & ahwv, const V & w, const V & v, const V & u, const V & z, Real & tol) inline override virtual
Apply the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in the direction \(v\), according to \(v\mapsto c_{uu}(u,z)(v,\cdot)^*w\).
Parameters
[out] ahwv is the result of applying the simulation-space derivative of the adjoint of the constraint simulation-space Jacobian at \((u,z)\) to the vector \(w\) in direction \(w\); a dual simulation-space vector
[in] w is the direction vector; a dual constraint-space vector
[in] v is a simulation-space vector
[in] u is the constraint argument; a simulation-space vector
[in] z is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahwv} = c_{uu}(u,z)(v,\cdot)^*w\), where \(w \in \mathcal{C}^*\), \(v \in \mathcal{U}\), and \(\mathsf{ahwv} \in \mathcal{U}^*\).
Reimplemented from ROL::Constraint_SimOpt< Real >.
Definition at line 288 of file ROL_Constraint_SerialSimOpt.hpp.
References ROL::Vector< Real >::zero().
Member Data Documentation
con_
template<typename Real > const Ptr<Con> ROL::Constraint_SerialSimOpt< Real >::con_ private
Definition at line 54 of file ROL_Constraint_SerialSimOpt.hpp.
Referenced by ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_2(), ROL::Constraint_SerialSimOpt< Real >::applyInverseAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyInverseJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyJacobian_2(), ROL::Constraint_SerialSimOpt< Real >::solve(), and ROL::Constraint_SerialSimOpt< Real >::value().
ui_
template<typename Real > const Ptr<V> ROL::Constraint_SerialSimOpt< Real >::ui_ private
Definition at line 55 of file ROL_Constraint_SerialSimOpt.hpp.
Referenced by ROL::Constraint_SerialSimOpt< Real >::solve(), and ROL::Constraint_SerialSimOpt< Real >::value().
u0_
template<typename Real > Ptr<V> ROL::Constraint_SerialSimOpt< Real >::u0_ private
Definition at line 56 of file ROL_Constraint_SerialSimOpt.hpp.
Referenced by ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyInverseAdjointJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyInverseJacobian_1(), ROL::Constraint_SerialSimOpt< Real >::applyJacobian_1(), and ROL::Constraint_SerialSimOpt< Real >::Constraint_SerialSimOpt().
z0_
template<typename Real > Pre<V> ROL::Constraint_SerialSimOpt< Real >::z0_ private
Definition at line 57 of file ROL_Constraint_SerialSimOpt.hpp.
Referenced by ROL::Constraint_SerialSimOpt< Real >::Constraint_SerialSimOpt().
workspace_
template<typename Real > VectorWorkspace<Real> ROL::Constraint_SerialSimOpt< Real >::workspace_ private
Definition at line 59 of file ROL_Constraint_SerialSimOpt.hpp.
Referenced by ROL::Constraint_SerialSimOpt< Real >::applyInverseAdjointJacobian_1(), and ROL::Constraint_SerialSimOpt< Real >::applyJacobian_1().
The documentation for this class was generated from the following file:
ROL_Constraint_SerialSimOpt.hpp