ROL: ROL::details::VectorWorkspace< Real > Class Template Reference
ROL::details::VectorWorkspace< Real > Class Template Reference
#include <ROL_VectorWorkspace.hpp>
Classes
struct VectorKey
struct VectorStack
Public Member Functions
Ptr< V > clone (const V &x)
Ptr< V > clone (const Ptr< const V > &x)
Ptr< V > copy (const V &x)
Ptr< V > copy (const Ptr< const V > &x)
void status (std::ostream &os) const
Private Types
using V = ROL::Vector< Real >
using size_type = typename std::vector< Real >::size_type
Private Attributes
std::map< VectorKey, Ptr< VectorStack > > workspace_
Detailed Description
template<typename Real>
class ROL::details::VectorWorkspace< Real >
Definition at line 64 of file ROL_VectorWorkspace.hpp.
Member Typedef Documentation
V
template<typename Real > using ROL::details::VectorWorkspace< Real >::V = ROL::Vector<Real> private
Definition at line 66 of file ROL_VectorWorkspace.hpp.
size_type
template<typename Real > using ROL::details::VectorWorkspace< Real >::size_type = typename std::vector<Real>::size_type private
Definition at line 67 of file ROL_VectorWorkspace.hpp.
Member Function Documentation
clone() [1/2]
template<typename Real > Ptr< V > ROL::details::VectorWorkspace< Real >::clone (const V & x) inline
Definition at line 163 of file ROL_VectorWorkspace.hpp.
References ROL::details::VectorWorkspace< Real >::workspace_.
Referenced by ROL::details::VectorWorkspace< Real >::copy().
clone() [2/2]
template<typename Real > Ptr< V > ROL::details::VectorWorkspace< Real >::clone (const Ptr< const V > & x) inline
Definition at line 180 of file ROL_VectorWorkspace.hpp.
References ROL::details::VectorWorkspace< Real >::clone().
Referenced by ROL::details::VectorWorkspace< Real >::clone().
copy() [1/2]
template<typename Real > Ptr< V > ROL::details::VectorWorkspace< Real >::copy (const V & x) inline
Definition at line 183 of file ROL_VectorWorkspace.hpp.
References ROL::details::VectorWorkspace< Real >::clone().
copy() [2/2]
template<typename Real > Ptr< V > ROL::details::VectorWorkspace< Real >::copy (const Ptr< const V > & x) inline
Definition at line 189 of file ROL_VectorWorkspace.hpp.
References ROL::details::VectorWorkspace< Real >::copy().
Referenced by ROL::details::VectorWorkspace< Real >::copy().
status()
template<typename Real > void ROL::details::VectorWorkspace< Real >::status (std::ostream & os) const inline
Definition at line 191 of file ROL_VectorWorkspace.hpp.
References ROL::details::VectorWorkspace< Real >::workspace_.
Member Data Documentation
workspace_
template<typename Real > std::map<VectorKey,Ptr<VectorStack> > ROL::details::VectorWorkspace< Real >::workspace_ private
Definition at line 159 of file ROL_VectorWorkspace.hpp.
Referenced by ROL::details::VectorWorkspace< Real >::clone(), and ROL::details::VectorWorkspace< Real >::status().
The documentation for this class was generated from the following file:
ROL_VectorWorkspace.hpp