ROL: ROL::TypeP::iPianoAlgorithm< Real > Class Template Reference
ROL::TypeP::iPianoAlgorithm< Real > Class Template Reference
Provides an interface to run the proximal gradient algorithm.
#include <ROL_TypeP_iPianoAlgorithm.hpp>
Public Member Functions
iPianoAlgorithm (ParameterList &list)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout) override
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeP::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void run (Vector< Real > &x, Objective< Real > &sobj, Objective< Real > &nobj, std::ostream &outStream=std::cout)
Run algorithm on unconstrained problems (Type-U). This is the primary Type-U interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &sobj, Objective< Real > &nobj, Vector< Real > &px, Vector< Real > &dg, std::ostream &outStream=std::cout)
Private Attributes
int maxit_
Real t0_
Real alpha_
Real beta_
Real rhodec_
Real rhoinc_
Real c1_
Real c2_
Real L_
bool useConstBeta_
bool initProx_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeP::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void pgstep (Vector< Real > &pgiter, Vector< Real > &pgstep, Objective< Real > &nobj, const Vector< Real > &x, const Vector< Real > &dg, Real t, Real &tol) const
Protected Attributes inherited from ROL::TypeP::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Detailed Description
template<typename Real>
class ROL::TypeP::iPianoAlgorithm< Real >
Provides an interface to run the proximal gradient algorithm.
Definition at line 23 of file ROL_TypeP_iPianoAlgorithm.hpp.
Constructor & Destructor Documentation
iPianoAlgorithm()
template<typename Real > ROL::TypeP::iPianoAlgorithm< Real >::iPianoAlgorithm (ParameterList & list)
Definition at line 17 of file ROL_TypeP_iPianoAlgorithm_Def.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeP::iPianoAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, Vector< Real > & px, Vector< Real > & dg, std::ostream & outStream = std::cout) private
Definition at line 39 of file ROL_TypeP_iPianoAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeP::Algorithm< Real >::initialize(), ROL::Objective< Real >::prox(), ROL::Vector< Real >::set(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeP::iPianoAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & sobj, Objective< Real > & nobj, std::ostream & outStream = std::cout) override virtual
Run algorithm on unconstrained problems (Type-U). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeP::Algorithm< Real >.
Definition at line 67 of file ROL_TypeP_iPianoAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Objective< Real >::prox(), ROL::Revert, ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeP::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeP::iPianoAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 208 of file ROL_TypeP_iPianoAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeP::iPianoAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 245 of file ROL_TypeP_iPianoAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeP::iPianoAlgorithm< Real >::writeOutput (std::ostream & os, bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeP::Algorithm< Real >.
Definition at line 252 of file ROL_TypeP_iPianoAlgorithm_Def.hpp.
Member Data Documentation
maxit_
template<typename Real > int ROL::TypeP::iPianoAlgorithm< Real >::maxit_ private
Definition at line 25 of file ROL_TypeP_iPianoAlgorithm.hpp.
t0_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::t0_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
alpha_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::alpha_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
beta_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::beta_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
rhodec_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::rhodec_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
rhoinc_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::rhoinc_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
c1_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::c1_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
c2_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::c2_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
L_
template<typename Real > Real ROL::TypeP::iPianoAlgorithm< Real >::L_ private
Definition at line 26 of file ROL_TypeP_iPianoAlgorithm.hpp.
useConstBeta_
template<typename Real > bool ROL::TypeP::iPianoAlgorithm< Real >::useConstBeta_ private
Definition at line 27 of file ROL_TypeP_iPianoAlgorithm.hpp.
initProx_
template<typename Real > bool ROL::TypeP::iPianoAlgorithm< Real >::initProx_ private
Definition at line 27 of file ROL_TypeP_iPianoAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeP::iPianoAlgorithm< Real >::verbosity_ private
Definition at line 28 of file ROL_TypeP_iPianoAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeP::iPianoAlgorithm< Real >::writeHeader_ private
Definition at line 29 of file ROL_TypeP_iPianoAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeP_iPianoAlgorithm.hpp
ROL_TypeP_iPianoAlgorithm_Def.hpp