ROL: ROL::PrimalAtomVector< Real > Class Template Reference
ROL::PrimalAtomVector< Real > Class Template Reference
#include <ROL_AtomVector.hpp>
Public Member Functions
PrimalAtomVector (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BatchManager< Real > > &bman, const int numMySamples, const int dimension, const ROL::Ptr< std::vector< Real > > &scale)
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< Vector< Real > > clone (void) const
Clone to make a new (uninitialized) vector.
const Vector< Real > & dual (void) const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::AtomVector< Real >
AtomVector (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BatchManager< Real > > &bman, const int numMySamples, const int dimension)
ROL::Ptr< const std::vector< Real > > getAtom (const int i) const
void setAtom (const int i, const std::vector< Real > &pt)
int getNumMyAtoms (void) const
int getDimension (void) const
Public Member Functions inherited from ROL::BatchStdVector< Real >
BatchStdVector (const Ptr< std::vector< Real > > &vec, const Ptr< BatchManager< Real > > &bman)
int dimension (void) const
Return dimension of the vector space.
Real reduce (const Elementwise::ReductionOp< Real > &r) const
const Ptr< BatchManager< Real > > getBatchManager (void) const
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Real >::size_type uint
Private Attributes
const ROL::Ptr< std::vector< Real > > scale_
ROL::Ptr< DualAtomVector< Real > > dual_vec_
bool isDualInitialized_
Detailed Description
template<class Real>
class ROL::PrimalAtomVector< Real >
Definition at line 74 of file ROL_AtomVector.hpp.
Member Typedef Documentation
uint
template<class Real > typedef std::vector<Real>::size_type ROL::PrimalAtomVector< Real >::uint private
Definition at line 75 of file ROL_AtomVector.hpp.
Constructor & Destructor Documentation
PrimalAtomVector()
template<class Real > ROL::PrimalAtomVector< Real >::PrimalAtomVector (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BatchManager< Real > > & bman, const int numMySamples, const int dimension, const ROL::Ptr< std::vector< Real > > & scale) inline
Definition at line 82 of file ROL_AtomVector.hpp.
Member Function Documentation
dot()
template<class Real > Real ROL::PrimalAtomVector< Real >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::BatchStdVector< Real >.
Definition at line 89 of file ROL_AtomVector.hpp.
References ROL::BatchStdVector< Real >::dimension(), ROL::BatchStdVector< Real >::getBatchManager(), ROL::AtomVector< Real >::getDimension(), ROL::AtomVector< Real >::getNumMyAtoms(), and ROL::StdVector< Real, Element >::getVector().
clone()
template<class Real > ROL::Ptr< Vector< Real > > ROL::PrimalAtomVector< Real >::clone (void) const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::BatchStdVector< Real >.
Definition at line 110 of file ROL_AtomVector.hpp.
References ROL::BatchStdVector< Real >::dimension(), ROL::AtomVector< Real >::getDimension(), ROL::AtomVector< Real >::getNumMyAtoms(), and ROL::PrimalAtomVector< Real >::scale_.
dual()
template<class Real > const Vector< Real > & ROL::PrimalAtomVector< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 119 of file ROL_AtomVector.hpp.
References ROL::BatchStdVector< Real >::dimension(), ROL::PrimalAtomVector< Real >::dual_vec_, ROL::AtomVector< Real >::getDimension(), ROL::AtomVector< Real >::getNumMyAtoms(), ROL::StdVector< Real, Element >::getVector(), ROL::PrimalAtomVector< Real >::isDualInitialized_, and ROL::PrimalAtomVector< Real >::scale_.
Member Data Documentation
scale_
template<class Real > const ROL::Ptr<std::vector<Real> > ROL::PrimalAtomVector< Real >::scale_ private
Definition at line 77 of file ROL_AtomVector.hpp.
Referenced by ROL::PrimalAtomVector< Real >::clone(), and ROL::PrimalAtomVector< Real >::dual().
dual_vec_
template<class Real > ROL::Ptr<DualAtomVector<Real> > ROL::PrimalAtomVector< Real >::dual_vec_ mutable private
Definition at line 78 of file ROL_AtomVector.hpp.
Referenced by ROL::PrimalAtomVector< Real >::dual().
isDualInitialized_
template<class Real > bool ROL::PrimalAtomVector< Real >::isDualInitialized_ mutable private
Definition at line 79 of file ROL_AtomVector.hpp.
Referenced by ROL::PrimalAtomVector< Real >::dual().
The documentation for this class was generated from the following file:
ROL_AtomVector.hpp