ROL: ROL::SimulatedBoundConstraint< Real > Class Template Reference
ROL::SimulatedBoundConstraint< Real > Class Template Reference
User Interface » Functional Interface
A BoundConstraint formed from a single bound constraint replacated according to a SampleGenerator.
#include <ROL_SimulatedBoundConstraint.hpp>
Public Member Functions
~SimulatedBoundConstraint ()
SimulatedBoundConstraint (const Ptr< SampleGenerator< Real > > &sampler, const Ptr< BoundConstraint< Real > > &bnd)
void project (Vector< Real > &x)
Project optimization variables onto the bounds.
void projectInterior (Vector< Real > &x)
Project optimization variables into the interior of the feasible set.
void pruneUpperActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
void pruneUpperActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
void pruneLowerActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
void pruneLowerActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
const Ptr< const Vector< Real > > getLowerBound (void) const
Return the ref count pointer to the lower bound vector.
const Ptr< const Vector< Real > > getUpperBound (void) const
Return the ref count pointer to the upper bound vector.
bool isFeasible (const Vector< Real > &v)
Check if the vector, v, is feasible.
void applyInverseScalingFunction (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const
Apply inverse scaling function.
void applyScalingFunctionJacobian (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const
Apply scaling function Jacobian.
Public Member Functions inherited from ROL::BoundConstraint< Real >
virtual ~BoundConstraint ()
BoundConstraint (void)
BoundConstraint (const Vector< Real > &x)
void activateLower (void)
Turn on lower bound.
void activateUpper (void)
Turn on upper bound.
void activate (void)
Turn on bounds.
void deactivateLower (void)
Turn off lower bound.
void deactivateUpper (void)
Turn off upper bound.
void deactivate (void)
Turn off bounds.
bool isLowerActivated (void) const
Check if lower bound are on.
bool isUpperActivated (void) const
Check if upper bound are on.
bool isActivated (void) const
Check if bounds are on.
void pruneActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-active set.
void pruneActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void computeProjectedGradient (Vector< Real > &g, const Vector< Real > &x)
Compute projected gradient.
void computeProjectedStep (Vector< Real > &v, const Vector< Real > &x)
Compute projected step.
Private Member Functions
const Vector< Real > & getVector (const Vector< Real > &x, int k) const
Vector< Real > & getVector (Vector< Real > &x, int k) const
Private Attributes
const Ptr< SampleGenerator< Real > > sampler_
const Ptr< BoundConstraint< Real > > bnd_
Ptr< Vector< Real > > l_
Ptr< Vector< Real > > u_
Additional Inherited Members
Protected Member Functions inherited from ROL::BoundConstraint< Real >
Real computeInf (const Vector< Real > &x) const
Protected Attributes inherited from ROL::BoundConstraint< Real >
Ptr< Vector< Real > > lower_
Ptr< Vector< Real > > upper_
Detailed Description
template<class Real>
class ROL::SimulatedBoundConstraint< Real >
A BoundConstraint formed from a single bound constraint replacated according to a SampleGenerator.
Definition at line 25 of file ROL_SimulatedBoundConstraint.hpp.
Constructor & Destructor Documentation
~SimulatedBoundConstraint()
template<class Real > ROL::SimulatedBoundConstraint< Real >::~SimulatedBoundConstraint () inline
Definition at line 51 of file ROL_SimulatedBoundConstraint.hpp.
SimulatedBoundConstraint()
template<class Real > ROL::SimulatedBoundConstraint< Real >::SimulatedBoundConstraint (const Ptr< SampleGenerator< Real > > & sampler, const Ptr< BoundConstraint< Real > > & bnd) inline
Definition at line 53 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::l_, ROL::SimulatedBoundConstraint< Real >::sampler_, and ROL::SimulatedBoundConstraint< Real >::u_.
Member Function Documentation
getVector() [1/2]
template<class Real > const Vector< Real > & ROL::SimulatedBoundConstraint< Real >::getVector (const Vector< Real > & x, int k) const inline private
Definition at line 32 of file ROL_SimulatedBoundConstraint.hpp.
Referenced by ROL::SimulatedBoundConstraint< Real >::applyInverseScalingFunction(), ROL::SimulatedBoundConstraint< Real >::applyScalingFunctionJacobian(), ROL::SimulatedBoundConstraint< Real >::isFeasible(), ROL::SimulatedBoundConstraint< Real >::project(), ROL::SimulatedBoundConstraint< Real >::projectInterior(), ROL::SimulatedBoundConstraint< Real >::pruneLowerActive(), ROL::SimulatedBoundConstraint< Real >::pruneLowerActive(), ROL::SimulatedBoundConstraint< Real >::pruneUpperActive(), and ROL::SimulatedBoundConstraint< Real >::pruneUpperActive().
getVector() [2/2]
template<class Real > Vector< Real > & ROL::SimulatedBoundConstraint< Real >::getVector (Vector< Real > & x, int k) const inline private
Definition at line 41 of file ROL_SimulatedBoundConstraint.hpp.
project()
template<class Real > void ROL::SimulatedBoundConstraint< Real >::project (Vector< Real > & x) inline virtual
Project optimization variables onto the bounds.
This function implements the projection of \(x\) onto the bounds, i.e.,
\[ (P_{[a,b]}(x))(\xi) = \min\{b(\xi),\max\{a(\xi),x(\xi)\}\} \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 68 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
projectInterior()
template<class Real > void ROL::SimulatedBoundConstraint< Real >::projectInterior (Vector< Real > & x) inline virtual
Project optimization variables into the interior of the feasible set.
This function implements the projection of \(x\) into the interior of the feasible set, i.e.,
\[ (\bar{P}_{[a,b]}(x))(\xi) \in (a(\xi),b(\xi)) \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 76 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
pruneUpperActive() [1/2]
template<class Real > void ROL::SimulatedBoundConstraint< Real >::pruneUpperActive (Vector< Real > & v, const Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-active set is defined as
\[ \mathcal{A}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 84 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
pruneUpperActive() [2/2]
template<class Real > void ROL::SimulatedBoundConstraint< Real >::pruneUpperActive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon_x,\; g(\xi) < -\epsilon_g \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 92 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
pruneLowerActive() [1/2]
template<class Real > void ROL::SimulatedBoundConstraint< Real >::pruneLowerActive (Vector< Real > & v, const Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-active set is defined as
\[ \mathcal{A}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 100 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
pruneLowerActive() [2/2]
template<class Real > void ROL::SimulatedBoundConstraint< Real >::pruneLowerActive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon,\; g(\xi) > 0 \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 108 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
getLowerBound()
template<class Real > const Ptr< const Vector< Real > > ROL::SimulatedBoundConstraint< Real >::getLowerBound (void) const inline virtual
Return the ref count pointer to the lower bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 116 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::l_.
getUpperBound()
template<class Real > const Ptr< const Vector< Real > > ROL::SimulatedBoundConstraint< Real >::getUpperBound (void) const inline virtual
Return the ref count pointer to the upper bound vector.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 120 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::u_.
isFeasible()
template<class Real > bool ROL::SimulatedBoundConstraint< Real >::isFeasible (const Vector< Real > & v) inline virtual
Check if the vector, v, is feasible.
This function returns true if \(v = P_{[a,b]}(v)\).
Parameters
[in] v is the vector to be checked.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 124 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
applyInverseScalingFunction()
template<class Real > void ROL::SimulatedBoundConstraint< Real >::applyInverseScalingFunction (Vector< Real > & dv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g) const inline virtual
Apply inverse scaling function.
This function applies the inverse scaling function \(d(x,g)\) to a vector \(v\), i.e., the output is \(\mathrm{diag}(d(x,g)^{-1})v\). The scaling function must satisfy: (i) \(d(x,g)_i = 0\) if \(x_i = a_i\) and \(g_i \ge 0\); (ii) \(d(x,g)_i = 0\) if \(x_i = b_i\) and \(g_i \le 0\); and (iii) \(d(x,g)_i > 0\) otherwise.
Parameters
[out] dv is the inverse scaling function applied to v.
[in] v is the vector being scaled.
[in] x is the primal vector at which the scaling function is evaluated.
[in] g is the dual vector at which the scaling function is evaluated.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 134 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
applyScalingFunctionJacobian()
template<class Real > void ROL::SimulatedBoundConstraint< Real >::applyScalingFunctionJacobian (Vector< Real > & dv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g) const inline virtual
Apply scaling function Jacobian.
This function applies the Jacobian of the scaling function \(d(x,g)\) to a vector \(v\). The output is \(\mathrm{diag}(d_x(x,g)g)v\). The scaling function must satisfy: (i) \(d(x,g)_i = 0\) if \(x_i = a_i\) and \(g_i \ge 0\); (ii) \(d(x,g)_i = 0\) if \(x_i = b_i\) and \(g_i \le 0\); and (iii) \(d(x,g)_i > 0\) otherwise.
Parameters
[out] dv is the scaling function Jacobian applied to v.
[in] v is the vector being scaled.
[in] x is the primal vector at which the scaling function is evaluated.
[in] g is the dual vector at which the scaling function is evaluated.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 142 of file ROL_SimulatedBoundConstraint.hpp.
References ROL::SimulatedBoundConstraint< Real >::bnd_, ROL::SimulatedBoundConstraint< Real >::getVector(), and ROL::SimulatedBoundConstraint< Real >::sampler_.
Member Data Documentation
sampler_
template<class Real > const Ptr<SampleGenerator<Real> > ROL::SimulatedBoundConstraint< Real >::sampler_ private
Definition at line 27 of file ROL_SimulatedBoundConstraint.hpp.
Referenced by ROL::SimulatedBoundConstraint< Real >::applyInverseScalingFunction(), ROL::SimulatedBoundConstraint< Real >::applyScalingFunctionJacobian(), ROL::SimulatedBoundConstraint< Real >::isFeasible(), ROL::SimulatedBoundConstraint< Real >::project(), ROL::SimulatedBoundConstraint< Real >::projectInterior(), ROL::SimulatedBoundConstraint< Real >::pruneLowerActive(), ROL::SimulatedBoundConstraint< Real >::pruneLowerActive(), ROL::SimulatedBoundConstraint< Real >::pruneUpperActive(), ROL::SimulatedBoundConstraint< Real >::pruneUpperActive(), and ROL::SimulatedBoundConstraint< Real >::SimulatedBoundConstraint().
bnd_
template<class Real > const Ptr<BoundConstraint<Real> > ROL::SimulatedBoundConstraint< Real >::bnd_ private
Definition at line 28 of file ROL_SimulatedBoundConstraint.hpp.
Referenced by ROL::SimulatedBoundConstraint< Real >::applyInverseScalingFunction(), ROL::SimulatedBoundConstraint< Real >::applyScalingFunctionJacobian(), ROL::SimulatedBoundConstraint< Real >::isFeasible(), ROL::SimulatedBoundConstraint< Real >::project(), ROL::SimulatedBoundConstraint< Real >::projectInterior(), ROL::SimulatedBoundConstraint< Real >::pruneLowerActive(), ROL::SimulatedBoundConstraint< Real >::pruneLowerActive(), ROL::SimulatedBoundConstraint< Real >::pruneUpperActive(), ROL::SimulatedBoundConstraint< Real >::pruneUpperActive(), and ROL::SimulatedBoundConstraint< Real >::SimulatedBoundConstraint().
l_
template<class Real > Ptr<Vector<Real> > ROL::SimulatedBoundConstraint< Real >::l_ private
Definition at line 29 of file ROL_SimulatedBoundConstraint.hpp.
Referenced by ROL::SimulatedBoundConstraint< Real >::getLowerBound(), and ROL::SimulatedBoundConstraint< Real >::SimulatedBoundConstraint().
u_
template<class Real > Ptr<Vector<Real> > ROL::SimulatedBoundConstraint< Real >::u_ private
Definition at line 30 of file ROL_SimulatedBoundConstraint.hpp.
Referenced by ROL::SimulatedBoundConstraint< Real >::getUpperBound(), and ROL::SimulatedBoundConstraint< Real >::SimulatedBoundConstraint().
The documentation for this class was generated from the following file:
ROL_SimulatedBoundConstraint.hpp