ROL: ROL::StdLinearOperator< Real > Class Template Reference
ROL::StdLinearOperator< Real > Class Template Reference
User Interface » Functional Interface
Provides the std::vector implementation to apply a linear operator, which is a std::vector representation of column-stacked matrix.
#include <ROL_StdLinearOperator.hpp>
Public Member Functions
StdLinearOperator ()
StdLinearOperator (ROL::Ptr< std::vector< Real > > &A)
virtual ~StdLinearOperator ()
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void update (const std::vector< Real > &x, bool flag=true, int iter=-1)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
virtual void apply (std::vector< Real > &Hv, const std::vector< Real > &v, Real &tol) const
void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjoint (std::vector< Real > &Hv, const std::vector< Real > &v, Real &tol) const
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
virtual void applyInverse (std::vector< Real > &Hv, const std::vector< Real > &v, Real &tol) const
void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
virtual void applyAdjointInverse (std::vector< Real > &Hv, const std::vector< Real > &v, Real &tol) const
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
Private Types
typedef StdVector< Real > SV
typedef std::vector< Real > vector
Private Attributes
ROL::Ptr< std::vector< Real > > A_
int N_
int INFO_
vector PLU_
std::vector< int > ipiv_
ROL::LAPACK< int, Real > lapack_
Detailed Description
template<class Real>
class ROL::StdLinearOperator< Real >
Provides the std::vector implementation to apply a linear operator, which is a std::vector representation of column-stacked matrix.
Currently, this interface requires that the underlying matrix be square
Definition at line 31 of file ROL_StdLinearOperator.hpp.
Member Typedef Documentation
SV
template<class Real > typedef StdVector<Real> ROL::StdLinearOperator< Real >::SV private
Definition at line 33 of file ROL_StdLinearOperator.hpp.
vector
template<class Real > typedef std::vector<Real> ROL::StdLinearOperator< Real >::vector private
Definition at line 35 of file ROL_StdLinearOperator.hpp.
Constructor & Destructor Documentation
StdLinearOperator() [1/2]
template<class Real > ROL::StdLinearOperator< Real >::StdLinearOperator () inline
Definition at line 50 of file ROL_StdLinearOperator.hpp.
StdLinearOperator() [2/2]
template<class Real > ROL::StdLinearOperator< Real >::StdLinearOperator (ROL::Ptr< std::vector< Real > > & A) inline
Definition at line 52 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::A_, ROL::StdLinearOperator< Real >::ipiv_, and ROL::StdLinearOperator< Real >::N_.
~StdLinearOperator()
template<class Real > virtual ROL::StdLinearOperator< Real >::~StdLinearOperator () inline virtual
Definition at line 62 of file ROL_StdLinearOperator.hpp.
Member Function Documentation
update() [1/2]
template<class Real > void ROL::StdLinearOperator< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update linear operator.
This function updates the linear operator at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 65 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::update().
Referenced by ROL::StdLinearOperator< Real >::update().
update() [2/2]
template<class Real > virtual void ROL::StdLinearOperator< Real >::update (const std::vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Definition at line 70 of file ROL_StdLinearOperator.hpp.
apply() [1/2]
template<class Real > void ROL::StdLinearOperator< Real >::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 74 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::apply().
Referenced by ROL::StdLinearOperator< Real >::apply().
apply() [2/2]
template<class Real > virtual void ROL::StdLinearOperator< Real >::apply (std::vector< Real > & Hv, const std::vector< Real > & v, Real & tol) const inline virtual
Definition at line 81 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::A_, and ROL::StdLinearOperator< Real >::N_.
applyAdjoint() [1/2]
template<class Real > void ROL::StdLinearOperator< Real >::applyAdjoint (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of linear operator.
This function applies the adjoint of a linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 92 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::applyAdjoint().
Referenced by ROL::StdLinearOperator< Real >::applyAdjoint().
applyAdjoint() [2/2]
template<class Real > virtual void ROL::StdLinearOperator< Real >::applyAdjoint (std::vector< Real > & Hv, const std::vector< Real > & v, Real & tol) const inline virtual
Definition at line 99 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::A_, and ROL::StdLinearOperator< Real >::N_.
applyInverse() [1/2]
template<class Real > void ROL::StdLinearOperator< Real >::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 112 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::applyInverse().
Referenced by ROL::StdLinearOperator< Real >::applyInverse().
applyInverse() [2/2]
template<class Real > virtual void ROL::StdLinearOperator< Real >::applyInverse (std::vector< Real > & Hv, const std::vector< Real > & v, Real & tol) const inline virtual
Definition at line 119 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::A_, ROL::StdLinearOperator< Real >::ipiv_, ROL::StdLinearOperator< Real >::lapack_, ROL::StdLinearOperator< Real >::N_, and ROL::StdLinearOperator< Real >::PLU_.
applyAdjointInverse() [1/2]
template<class Real > void ROL::StdLinearOperator< Real >::applyAdjointInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply adjoint of the inverse linear operator.
This function applies the adjoint of the inverse linear operator to a vector. Default behavior assumes operator is self-adjoint.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 149 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::applyAdjointInverse().
Referenced by ROL::StdLinearOperator< Real >::applyAdjointInverse().
applyAdjointInverse() [2/2]
template<class Real > virtual void ROL::StdLinearOperator< Real >::applyAdjointInverse (std::vector< Real > & Hv, const std::vector< Real > & v, Real & tol) const inline virtual
Definition at line 156 of file ROL_StdLinearOperator.hpp.
References ROL::StdLinearOperator< Real >::A_, ROL::StdLinearOperator< Real >::ipiv_, ROL::StdLinearOperator< Real >::lapack_, ROL::StdLinearOperator< Real >::N_, and ROL::StdLinearOperator< Real >::PLU_.
Member Data Documentation
A_
template<class Real > ROL::Ptr<std::vector<Real> > ROL::StdLinearOperator< Real >::A_ private
Definition at line 39 of file ROL_StdLinearOperator.hpp.
Referenced by ROL::StdLinearOperator< Real >::apply(), ROL::StdLinearOperator< Real >::applyAdjoint(), ROL::StdLinearOperator< Real >::applyAdjointInverse(), ROL::StdLinearOperator< Real >::applyInverse(), and ROL::StdLinearOperator< Real >::StdLinearOperator().
N_
template<class Real > int ROL::StdLinearOperator< Real >::N_ private
Definition at line 40 of file ROL_StdLinearOperator.hpp.
Referenced by ROL::StdLinearOperator< Real >::apply(), ROL::StdLinearOperator< Real >::applyAdjoint(), ROL::StdLinearOperator< Real >::applyAdjointInverse(), ROL::StdLinearOperator< Real >::applyInverse(), and ROL::StdLinearOperator< Real >::StdLinearOperator().
INFO_
template<class Real > int ROL::StdLinearOperator< Real >::INFO_ private
Definition at line 41 of file ROL_StdLinearOperator.hpp.
PLU_
template<class Real > vector ROL::StdLinearOperator< Real >::PLU_ mutable private
Definition at line 43 of file ROL_StdLinearOperator.hpp.
Referenced by ROL::StdLinearOperator< Real >::applyAdjointInverse(), and ROL::StdLinearOperator< Real >::applyInverse().
ipiv_
template<class Real > std::vector<int> ROL::StdLinearOperator< Real >::ipiv_ mutable private
Definition at line 44 of file ROL_StdLinearOperator.hpp.
Referenced by ROL::StdLinearOperator< Real >::applyAdjointInverse(), ROL::StdLinearOperator< Real >::applyInverse(), and ROL::StdLinearOperator< Real >::StdLinearOperator().
lapack_
template<class Real > ROL::LAPACK<int,Real> ROL::StdLinearOperator< Real >::lapack_ private
Definition at line 46 of file ROL_StdLinearOperator.hpp.
Referenced by ROL::StdLinearOperator< Real >::applyAdjointInverse(), and ROL::StdLinearOperator< Real >::applyInverse().
The documentation for this class was generated from the following file:
ROL_StdLinearOperator.hpp