ROL: ROL::Bundle< Real > Class Template Reference
ROL::Bundle< Real > Class Template Reference abstract
Provides the interface for and implements a bundle.
#include <ROL_Bundle.hpp>
Public Member Functions
virtual ~Bundle (void)
Bundle (const unsigned maxSize=10, const Real coeff=0.0, const Real omega=2.0, const unsigned remSize=2)
virtual void initialize (const Vector< Real > &g)
virtual unsigned solveDual (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)=0
const Real linearizationError (const unsigned i) const
const Real distanceMeasure (const unsigned i) const
const Vector< Real > & subgradient (const unsigned i) const
const Real getDualVariable (const unsigned i) const
void setDualVariable (const unsigned i, const Real val)
void resetDualVariables (void)
const Real computeAlpha (const Real dm, const Real le) const
const Real alpha (const unsigned i) const
unsigned size (void) const
void aggregate (Vector< Real > &aggSubGrad, Real &aggLinErr, Real &aggDistMeas) const
void reset (const Vector< Real > &g, const Real le, const Real dm)
void update (const bool flag, const Real linErr, const Real distMeas, const Vector< Real > &g, const Vector< Real > &s)
Protected Member Functions
const Real GiGj (const unsigned i, const unsigned j) const
const Real dotGi (const unsigned i, const Vector< Real > &x) const
void addGi (const unsigned i, const Real a, Vector< Real > &x) const
Real evaluateObjective (std::vector< Real > &g, const std::vector< Real > &x, const Real t) const
unsigned solveDual_dim1 (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
unsigned solveDual_dim2 (const Real t, const unsigned maxit=1000, const Real tol=1.e-8)
Private Member Functions
void remove (const std::vector< unsigned > &ind)
void add (const Vector< Real > &g, const Real le, const Real dm)
Private Attributes
std::vector< ROL::Ptr< Vector< Real > > > subgradients_
std::vector< Real > linearizationErrors_
std::vector< Real > distanceMeasures_
std::vector< Real > dualVariables_
ROL::Ptr< Vector< Real > > tG_
ROL::Ptr< Vector< Real > > eG_
ROL::Ptr< Vector< Real > > yG_
ROL::Ptr< Vector< Real > > gx_
ROL::Ptr< Vector< Real > > ge_
unsigned size_
unsigned maxSize_
unsigned remSize_
Real coeff_
Real omega_
bool isInitialized_
Detailed Description
template<class Real>
class ROL::Bundle< Real >
Provides the interface for and implements a bundle.
Definition at line 28 of file ROL_Bundle.hpp.
Constructor & Destructor Documentation
~Bundle()
template<class Real > virtual ROL::Bundle< Real >::~Bundle (void) inline virtual
Definition at line 90 of file ROL_Bundle.hpp.
Bundle()
template<class Real > ROL::Bundle< Real >::Bundle (const unsigned maxSize = 10, const Real coeff = 0.0, const Real omega = 2.0, const unsigned remSize = 2) inline
Definition at line 92 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::coeff_, ROL::Bundle< Real >::distanceMeasures_, ROL::Bundle< Real >::dualVariables_, ROL::Bundle< Real >::linearizationErrors_, ROL::Bundle< Real >::maxSize_, ROL::Bundle< Real >::omega_, ROL::Bundle< Real >::remSize_, ROL::Bundle< Real >::subgradients_, and zero.
Member Function Documentation
remove()
template<class Real > void ROL::Bundle< Real >::remove (const std::vector< unsigned > & ind) inline private
Definition at line 54 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::distanceMeasures_, ROL::Bundle< Real >::dualVariables_, ROL::Bundle< Real >::linearizationErrors_, ROL::Bundle< Real >::size_, ROL::Bundle< Real >::subgradients_, and zero.
Referenced by ROL::Bundle< Real >::reset().
add()
template<class Real > void ROL::Bundle< Real >::add (const Vector< Real > & g, const Real le, const Real dm) inline private
Definition at line 77 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::distanceMeasures_, ROL::Bundle< Real >::dualVariables_, ROL::Bundle< Real >::linearizationErrors_, ROL::Bundle< Real >::size_, ROL::Bundle< Real >::subgradients_, and zero.
Referenced by ROL::Bundle< Real >::reset().
initialize()
template<class Real > virtual void ROL::Bundle< Real >::initialize (const Vector< Real > & g) inline virtual
Reimplemented in ROL::Bundle_AS< Real >.
Definition at line 112 of file ROL_Bundle.hpp.
References ROL::Vector< Real >::clone(), ROL::Bundle< Real >::distanceMeasures_, ROL::Bundle< Real >::dualVariables_, ROL::Bundle< Real >::eG_, ROL::Bundle< Real >::ge_, ROL::Bundle< Real >::gx_, ROL::Bundle< Real >::isInitialized_, ROL::Bundle< Real >::linearizationErrors_, ROL::Bundle< Real >::maxSize_, ROL::Bundle< Real >::size_, ROL::Bundle< Real >::subgradients_, ROL::Bundle< Real >::tG_, ROL::Bundle< Real >::yG_, and zero.
Referenced by ROL::Bundle_AS< Real >::initialize().
solveDual()
template<class Real > virtual unsigned ROL::Bundle< Real >::solveDual (const Real t, const unsigned maxit = 1000, const Real tol = 1.e-8) pure virtual
Implemented in ROL::Bundle_AS< Real >, and ROL::Bundle_TT< Real >.
linearizationError()
template<class Real > const Real ROL::Bundle< Real >::linearizationError (const unsigned i) const inline
Definition at line 134 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::linearizationErrors_.
distanceMeasure()
template<class Real > const Real ROL::Bundle< Real >::distanceMeasure (const unsigned i) const inline
Definition at line 138 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::distanceMeasures_.
subgradient()
template<class Real > const Vector< Real > & ROL::Bundle< Real >::subgradient (const unsigned i) const inline
Definition at line 142 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::subgradients_.
Referenced by ROL::Bundle< Real >::addGi(), ROL::Bundle< Real >::dotGi(), ROL::Bundle< Real >::evaluateObjective(), ROL::Bundle< Real >::GiGj(), and ROL::Bundle< Real >::solveDual_dim2().
getDualVariable()
template<class Real > const Real ROL::Bundle< Real >::getDualVariable (const unsigned i) const inline
Definition at line 146 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::dualVariables_.
Referenced by ROL::Bundle_AS< Real >::initializeDualSolver(), ROL::Bundle_AS< Real >::solveDual_arbitrary(), ROL::Bundle< Real >::solveDual_dim2(), and ROL::Bundle_TT< Real >::solveDual_TT().
setDualVariable()
template<class Real > void ROL::Bundle< Real >::setDualVariable (const unsigned i, const Real val) inline
Definition at line 150 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::dualVariables_.
Referenced by ROL::Bundle_AS< Real >::initializeDualSolver(), ROL::Bundle_AS< Real >::solveDual_arbitrary(), ROL::Bundle< Real >::solveDual_dim1(), ROL::Bundle< Real >::solveDual_dim2(), and ROL::Bundle_TT< Real >::solveDual_TT().
resetDualVariables()
template<class Real > void ROL::Bundle< Real >::resetDualVariables (void) inline
Definition at line 154 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::dualVariables_, ROL::Bundle< Real >::size_, and zero.
Referenced by ROL::Bundle_TT< Real >::solveDual_TT().
computeAlpha()
template<class Real > const Real ROL::Bundle< Real >::computeAlpha (const Real dm, const Real le) const inline
Definition at line 159 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::alpha(), ROL::Bundle< Real >::coeff_, and ROL::Bundle< Real >::omega_.
Referenced by ROL::Bundle< Real >::alpha().
alpha()
template<class Real > const Real ROL::Bundle< Real >::alpha (const unsigned i) const inline
Definition at line 167 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::computeAlpha(), ROL::Bundle< Real >::distanceMeasures_, and ROL::Bundle< Real >::linearizationErrors_.
Referenced by ROL::Bundle_TT< Real >::addSubgradToBase(), ROL::Bundle< Real >::computeAlpha(), ROL::Bundle_AS< Real >::computeStepSize(), ROL::Bundle< Real >::evaluateObjective(), ROL::Bundle_AS< Real >::projectedCG(), ROL::Bundle_AS< Real >::solveDual_arbitrary(), ROL::Bundle< Real >::solveDual_dim2(), and ROL::Bundle_TT< Real >::solveDual_TT().
size()
template<class Real > unsigned ROL::Bundle< Real >::size (void) const inline
Definition at line 171 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::size_.
Referenced by ROL::Bundle_AS< Real >::computeStepSize(), ROL::Bundle< Real >::evaluateObjective(), ROL::Bundle_AS< Real >::isNonnegative(), ROL::Bundle_AS< Real >::project(), and ROL::Bundle_TT< Real >::solveSystem().
aggregate()
template<class Real > void ROL::Bundle< Real >::aggregate (Vector< Real > & aggSubGrad, Real & aggLinErr, Real & aggDistMeas) const inline
Definition at line 175 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::distanceMeasures_, ROL::Bundle< Real >::dualVariables_, ROL::Bundle< Real >::eG_, ROL::Bundle< Real >::linearizationErrors_, ROL::Vector< Real >::set(), ROL::Bundle< Real >::size_, ROL::Bundle< Real >::subgradients_, ROL::Bundle< Real >::tG_, ROL::Bundle< Real >::yG_, zero, and ROL::Vector< Real >::zero().
reset()
template<class Real > void ROL::Bundle< Real >::reset (const Vector< Real > & g, const Real le, const Real dm) inline
Definition at line 201 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::add(), ROL::Bundle< Real >::linearizationErrors_, ROL::Bundle< Real >::maxSize_, ROL::Bundle< Real >::remove(), ROL::Bundle< Real >::remSize_, and ROL::Bundle< Real >::size_.
update()
template<class Real > void ROL::Bundle< Real >::update (const bool flag, const Real linErr, const Real distMeas, const Vector< Real > & g, const Vector< Real > & s) inline
Definition at line 228 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::distanceMeasures_, ROL::Vector< Real >::dual(), ROL::Bundle< Real >::dualVariables_, ROL::Bundle< Real >::linearizationErrors_, ROL::Bundle< Real >::size_, ROL::Bundle< Real >::subgradients_, and zero.
GiGj()
template<class Real > const Real ROL::Bundle< Real >::GiGj (const unsigned i, const unsigned j) const inline protected
Definition at line 254 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::subgradient().
Referenced by ROL::Bundle_AS< Real >::applyPreconditioner_SymGS().
dotGi()
template<class Real > const Real ROL::Bundle< Real >::dotGi (const unsigned i, const Vector< Real > & x) const inline protected
Definition at line 258 of file ROL_Bundle.hpp.
References ROL::Vector< Real >::dot(), and ROL::Bundle< Real >::subgradient().
Referenced by ROL::Bundle_AS< Real >::applyFullMatrix(), ROL::Bundle_AS< Real >::applyMatrix(), ROL::Bundle_AS< Real >::applyPreconditioner_SymGS(), ROL::Bundle< Real >::evaluateObjective(), and ROL::Bundle< Real >::solveDual_dim2().
addGi()
template<class Real > void ROL::Bundle< Real >::addGi (const unsigned i, const Real a, Vector< Real > & x) const inline protected
Definition at line 262 of file ROL_Bundle.hpp.
References ROL::Vector< Real >::axpy(), and ROL::Bundle< Real >::subgradient().
Referenced by ROL::Bundle_AS< Real >::applyPreconditioner_SymGS(), and ROL::Bundle< Real >::solveDual_dim2().
evaluateObjective()
template<class Real > Real ROL::Bundle< Real >::evaluateObjective (std::vector< Real > & g, const std::vector< Real > & x, const Real t) const inline protected
Definition at line 266 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::alpha(), ROL::Bundle< Real >::dotGi(), ROL::Bundle< Real >::eG_, ROL::Bundle< Real >::gx_, ROL::Bundle< Real >::size(), ROL::Bundle< Real >::subgradient(), ROL::Bundle< Real >::tG_, and ROL::Bundle< Real >::yG_.
Referenced by ROL::Bundle_AS< Real >::solveDual_arbitrary().
solveDual_dim1()
template<class Real > unsigned ROL::Bundle< Real >::solveDual_dim1 (const Real t, const unsigned maxit = 1000, const Real tol = 1.e-8) inline protected
Definition at line 293 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::setDualVariable().
Referenced by ROL::Bundle_AS< Real >::solveDual(), and ROL::Bundle_TT< Real >::solveDual().
solveDual_dim2()
template<class Real > unsigned ROL::Bundle< Real >::solveDual_dim2 (const Real t, const unsigned maxit = 1000, const Real tol = 1.e-8) inline protected
Definition at line 299 of file ROL_Bundle.hpp.
References ROL::Bundle< Real >::addGi(), ROL::Bundle< Real >::alpha(), ROL::Bundle< Real >::dotGi(), ROL::Bundle< Real >::getDualVariable(), ROL::Bundle< Real >::gx_, ROL::Bundle< Real >::setDualVariable(), ROL::Bundle< Real >::subgradient(), and zero.
Referenced by ROL::Bundle_AS< Real >::solveDual(), and ROL::Bundle_TT< Real >::solveDual().
Member Data Documentation
subgradients_
template<class Real > std::vector<ROL::Ptr<Vector<Real> > > ROL::Bundle< Real >::subgradients_ private
Definition at line 33 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::add(), ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::Bundle(), ROL::Bundle< Real >::initialize(), ROL::Bundle< Real >::remove(), ROL::Bundle< Real >::subgradient(), and ROL::Bundle< Real >::update().
linearizationErrors_
template<class Real > std::vector<Real> ROL::Bundle< Real >::linearizationErrors_ private
Definition at line 34 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::add(), ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::alpha(), ROL::Bundle< Real >::Bundle(), ROL::Bundle< Real >::initialize(), ROL::Bundle< Real >::linearizationError(), ROL::Bundle< Real >::remove(), ROL::Bundle< Real >::reset(), and ROL::Bundle< Real >::update().
distanceMeasures_
template<class Real > std::vector<Real> ROL::Bundle< Real >::distanceMeasures_ private
Definition at line 35 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::add(), ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::alpha(), ROL::Bundle< Real >::Bundle(), ROL::Bundle< Real >::distanceMeasure(), ROL::Bundle< Real >::initialize(), ROL::Bundle< Real >::remove(), and ROL::Bundle< Real >::update().
dualVariables_
template<class Real > std::vector<Real> ROL::Bundle< Real >::dualVariables_ private
Definition at line 37 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::add(), ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::Bundle(), ROL::Bundle< Real >::getDualVariable(), ROL::Bundle< Real >::initialize(), ROL::Bundle< Real >::remove(), ROL::Bundle< Real >::resetDualVariables(), ROL::Bundle< Real >::setDualVariable(), and ROL::Bundle< Real >::update().
tG_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle< Real >::tG_ private
Definition at line 39 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::evaluateObjective(), and ROL::Bundle< Real >::initialize().
eG_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle< Real >::eG_ private
Definition at line 40 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::evaluateObjective(), and ROL::Bundle< Real >::initialize().
yG_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle< Real >::yG_ private
Definition at line 41 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::evaluateObjective(), and ROL::Bundle< Real >::initialize().
gx_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle< Real >::gx_ private
Definition at line 42 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::evaluateObjective(), ROL::Bundle< Real >::initialize(), and ROL::Bundle< Real >::solveDual_dim2().
ge_
template<class Real > ROL::Ptr<Vector<Real> > ROL::Bundle< Real >::ge_ private
Definition at line 43 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::initialize().
size_
template<class Real > unsigned ROL::Bundle< Real >::size_ private
Definition at line 45 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::add(), ROL::Bundle< Real >::aggregate(), ROL::Bundle< Real >::initialize(), ROL::Bundle< Real >::remove(), ROL::Bundle< Real >::reset(), ROL::Bundle< Real >::resetDualVariables(), ROL::Bundle< Real >::size(), and ROL::Bundle< Real >::update().
maxSize_
template<class Real > unsigned ROL::Bundle< Real >::maxSize_ private
Definition at line 47 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::Bundle(), ROL::Bundle< Real >::initialize(), and ROL::Bundle< Real >::reset().
remSize_
template<class Real > unsigned ROL::Bundle< Real >::remSize_ private
Definition at line 48 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::Bundle(), and ROL::Bundle< Real >::reset().
coeff_
template<class Real > Real ROL::Bundle< Real >::coeff_ private
Definition at line 49 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::Bundle(), and ROL::Bundle< Real >::computeAlpha().
omega_
template<class Real > Real ROL::Bundle< Real >::omega_ private
Definition at line 50 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::Bundle(), and ROL::Bundle< Real >::computeAlpha().
isInitialized_
template<class Real > bool ROL::Bundle< Real >::isInitialized_ private
Definition at line 52 of file ROL_Bundle.hpp.
Referenced by ROL::Bundle< Real >::initialize().
The documentation for this class was generated from the following file:
ROL_Bundle.hpp