ROL: ROL::BoundConstraint_Partitioned< Real > Class Template Reference
ROL::BoundConstraint_Partitioned< Real > Class Template Reference
User Interface » Functional Interface
A composite composite BoundConstraint formed from bound constraints on subvectors of a PartitionedVector.
#include <ROL_BoundConstraint_Partitioned.hpp>
Public Member Functions
~BoundConstraint_Partitioned ()
BoundConstraint_Partitioned (const std::vector< Ptr< BoundConstraint< Real > > > &bnd, const std::vector< Ptr< Vector< Real > > > &x)
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
void project (Vector< Real > &x)
Project optimization variables onto the bounds.
void projectInterior (Vector< Real > &x)
Project optimization variables into the interior of the feasible set.
void pruneUpperActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
void pruneUpperActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
void pruneLowerActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
void pruneLowerActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
bool isFeasible (const Vector< Real > &v)
Check if the vector, v, is feasible.
void applyInverseScalingFunction (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const
Apply inverse scaling function.
void applyScalingFunctionJacobian (Vector< Real > &dv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g) const
Apply scaling function Jacobian.
Public Member Functions inherited from ROL::BoundConstraint< Real >
virtual ~BoundConstraint ()
BoundConstraint (void)
BoundConstraint (const Vector< Real > &x)
virtual const Ptr< const Vector< Real > > getLowerBound (void) const
Return the ref count pointer to the lower bound vector.
virtual const Ptr< const Vector< Real > > getUpperBound (void) const
Return the ref count pointer to the upper bound vector.
void activateLower (void)
Turn on lower bound.
void activateUpper (void)
Turn on upper bound.
void activate (void)
Turn on bounds.
void deactivateLower (void)
Turn off lower bound.
void deactivateUpper (void)
Turn off upper bound.
void deactivate (void)
Turn off bounds.
bool isLowerActivated (void) const
Check if lower bound are on.
bool isUpperActivated (void) const
Check if upper bound are on.
bool isActivated (void) const
Check if bounds are on.
void pruneActive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-active set.
void pruneActive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneLowerInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneUpperInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &x, Real eps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-inactive set.
void pruneInactive (Vector< Real > &v, const Vector< Real > &g, const Vector< Real > &x, Real xeps=Real(0), Real geps=Real(0))
Set variables to zero if they correspond to the \(\epsilon\)-nonbinding set.
void computeProjectedGradient (Vector< Real > &g, const Vector< Real > &x)
Compute projected gradient.
void computeProjectedStep (Vector< Real > &v, const Vector< Real > &x)
Compute projected step.
Private Types
typedef Vector< Real > V
typedef PartitionedVector< Real > PV
typedef std::vector< Real >::size_type uint
Private Attributes
std::vector< Ptr< BoundConstraint< Real > > > bnd_
Ptr< V > l_
Ptr< V > u_
uint dim_
bool hasLvec_
bool hasUvec_
Additional Inherited Members
Protected Member Functions inherited from ROL::BoundConstraint< Real >
Real computeInf (const Vector< Real > &x) const
Protected Attributes inherited from ROL::BoundConstraint< Real >
Ptr< Vector< Real > > lower_
Ptr< Vector< Real > > upper_
Detailed Description
template<typename Real>
class ROL::BoundConstraint_Partitioned< Real >
A composite composite BoundConstraint formed from bound constraints on subvectors of a PartitionedVector.
Definition at line 27 of file ROL_BoundConstraint_Partitioned.hpp.
Member Typedef Documentation
V
template<typename Real > typedef Vector<Real> ROL::BoundConstraint_Partitioned< Real >::V private
Definition at line 29 of file ROL_BoundConstraint_Partitioned.hpp.
PV
template<typename Real > typedef PartitionedVector<Real> ROL::BoundConstraint_Partitioned< Real >::PV private
Definition at line 30 of file ROL_BoundConstraint_Partitioned.hpp.
uint
template<typename Real > typedef std::vector<Real>::size_type ROL::BoundConstraint_Partitioned< Real >::uint private
Definition at line 31 of file ROL_BoundConstraint_Partitioned.hpp.
Constructor & Destructor Documentation
~BoundConstraint_Partitioned()
template<typename Real > ROL::BoundConstraint_Partitioned< Real >::~BoundConstraint_Partitioned () inline
Definition at line 47 of file ROL_BoundConstraint_Partitioned.hpp.
BoundConstraint_Partitioned()
template<typename Real > ROL::BoundConstraint_Partitioned< Real >::BoundConstraint_Partitioned (const std::vector< Ptr< BoundConstraint< Real > > > & bnd, const std::vector< Ptr< Vector< Real > > > & x) inline
Definition at line 49 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint< Real >::activate(), ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint< Real >::deactivate(), ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::BoundConstraint< Real >::getLowerBound(), ROL::BoundConstraint< Real >::getUpperBound(), ROL::BoundConstraint_Partitioned< Real >::hasLvec_, ROL::BoundConstraint_Partitioned< Real >::hasUvec_, ROL::BoundConstraint< Real >::isActivated(), ROL::BoundConstraint< Real >::isLowerActivated(), ROL::BoundConstraint< Real >::isUpperActivated(), ROL::BoundConstraint< Real >::lower_, and ROL::BoundConstraint< Real >::upper_.
Member Function Documentation
update()
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline
Definition at line 109 of file ROL_BoundConstraint_Partitioned.hpp.
project()
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::project (Vector< Real > & x) inline virtual
Project optimization variables onto the bounds.
This function implements the projection of \(x\) onto the bounds, i.e.,
\[ (P_{[a,b]}(x))(\xi) = \min\{b(\xi),\max\{a(\xi),x(\xi)\}\} \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 112 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
projectInterior()
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::projectInterior (Vector< Real > & x) inline virtual
Project optimization variables into the interior of the feasible set.
This function implements the projection of \(x\) into the interior of the feasible set, i.e.,
\[ (\bar{P}_{[a,b]}(x))(\xi) \in (a(\xi),b(\xi)) \quad \text{for almost every }\xi\in\Xi. \]
Parameters
[in,out] x is the optimization variable.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 121 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
pruneUpperActive() [1/2]
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive (Vector< Real > & v, const Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-active set is defined as
\[ \mathcal{A}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 130 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
pruneUpperActive() [2/2]
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the upper \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^+_\epsilon(x)\). Here, the upper \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^+_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \ge b(\xi)-\epsilon_x,\; g(\xi) < -\epsilon_g \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 140 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
pruneLowerActive() [1/2]
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive (Vector< Real > & v, const Vector< Real > & x, Real eps = Real(0)) inline virtual
Set variables to zero if they correspond to the lower \(\epsilon\)-active set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{A}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-active set is defined as
\[ \mathcal{A}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon\,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] x is the current optimization variable.
[in] eps is the active-set tolerance \(\epsilon\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 151 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
pruneLowerActive() [2/2]
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive (Vector< Real > & v, const Vector< Real > & g, const Vector< Real > & x, Real xeps = Real(0), Real geps = Real(0)) inline virtual
Set variables to zero if they correspond to the \(\epsilon\)-binding set.
This function sets \(v(\xi)=0\) if \(\xi\in\mathcal{B}^-_\epsilon(x)\). Here, the lower \(\epsilon\)-binding set is defined as
\[ \mathcal{B}^-_\epsilon(x) = \{\,\xi\in\Xi\,:\,x(\xi) \le a(\xi)+\epsilon,\; g(\xi) > 0 \,\}. \]
Parameters
[out] v is the variable to be pruned.
[in] g is the negative search direction.
[in] x is the current optimization variable.
[in] xeps is the active-set tolerance \(\epsilon_x\).
[in] geps is the binding-set tolerance \(\epsilon_g\).
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 161 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
isFeasible()
template<typename Real > bool ROL::BoundConstraint_Partitioned< Real >::isFeasible (const Vector< Real > & v) inline virtual
Check if the vector, v, is feasible.
This function returns true if \(v = P_{[a,b]}(v)\).
Parameters
[in] v is the vector to be checked.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 172 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
applyInverseScalingFunction()
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::applyInverseScalingFunction (Vector< Real > & dv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g) const inline virtual
Apply inverse scaling function.
This function applies the inverse scaling function \(d(x,g)\) to a vector \(v\), i.e., the output is \(\mathrm{diag}(d(x,g)^{-1})v\). The scaling function must satisfy: (i) \(d(x,g)_i = 0\) if \(x_i = a_i\) and \(g_i \ge 0\); (ii) \(d(x,g)_i = 0\) if \(x_i = b_i\) and \(g_i \le 0\); and (iii) \(d(x,g)_i > 0\) otherwise.
Parameters
[out] dv is the inverse scaling function applied to v.
[in] v is the vector being scaled.
[in] x is the primal vector at which the scaling function is evaluated.
[in] g is the dual vector at which the scaling function is evaluated.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 183 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
applyScalingFunctionJacobian()
template<typename Real > void ROL::BoundConstraint_Partitioned< Real >::applyScalingFunctionJacobian (Vector< Real > & dv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g) const inline virtual
Apply scaling function Jacobian.
This function applies the Jacobian of the scaling function \(d(x,g)\) to a vector \(v\). The output is \(\mathrm{diag}(d_x(x,g)g)v\). The scaling function must satisfy: (i) \(d(x,g)_i = 0\) if \(x_i = a_i\) and \(g_i \ge 0\); (ii) \(d(x,g)_i = 0\) if \(x_i = b_i\) and \(g_i \le 0\); and (iii) \(d(x,g)_i > 0\) otherwise.
Parameters
[out] dv is the scaling function Jacobian applied to v.
[in] v is the vector being scaled.
[in] x is the primal vector at which the scaling function is evaluated.
[in] g is the dual vector at which the scaling function is evaluated.
Reimplemented from ROL::BoundConstraint< Real >.
Definition at line 195 of file ROL_BoundConstraint_Partitioned.hpp.
References ROL::BoundConstraint_Partitioned< Real >::bnd_, ROL::BoundConstraint_Partitioned< Real >::dim_, ROL::PartitionedVector< Real >::get(), and ROL::BoundConstraint< Real >::isActivated().
Member Data Documentation
bnd_
template<typename Real > std::vector<Ptr<BoundConstraint<Real> > > ROL::BoundConstraint_Partitioned< Real >::bnd_ private
Definition at line 34 of file ROL_BoundConstraint_Partitioned.hpp.
Referenced by ROL::BoundConstraint_Partitioned< Real >::applyInverseScalingFunction(), ROL::BoundConstraint_Partitioned< Real >::applyScalingFunctionJacobian(), ROL::BoundConstraint_Partitioned< Real >::BoundConstraint_Partitioned(), ROL::BoundConstraint_Partitioned< Real >::isFeasible(), ROL::BoundConstraint_Partitioned< Real >::project(), ROL::BoundConstraint_Partitioned< Real >::projectInterior(), ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive(), ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive(), ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive(), and ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive().
l_
template<typename Real > Ptr<V> ROL::BoundConstraint_Partitioned< Real >::l_ private
Definition at line 38 of file ROL_BoundConstraint_Partitioned.hpp.
u_
template<typename Real > Ptr<V> ROL::BoundConstraint_Partitioned< Real >::u_ private
Definition at line 39 of file ROL_BoundConstraint_Partitioned.hpp.
dim_
template<typename Real > uint ROL::BoundConstraint_Partitioned< Real >::dim_ private
Definition at line 41 of file ROL_BoundConstraint_Partitioned.hpp.
Referenced by ROL::BoundConstraint_Partitioned< Real >::applyInverseScalingFunction(), ROL::BoundConstraint_Partitioned< Real >::applyScalingFunctionJacobian(), ROL::BoundConstraint_Partitioned< Real >::BoundConstraint_Partitioned(), ROL::BoundConstraint_Partitioned< Real >::isFeasible(), ROL::BoundConstraint_Partitioned< Real >::project(), ROL::BoundConstraint_Partitioned< Real >::projectInterior(), ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive(), ROL::BoundConstraint_Partitioned< Real >::pruneLowerActive(), ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive(), and ROL::BoundConstraint_Partitioned< Real >::pruneUpperActive().
hasLvec_
template<typename Real > bool ROL::BoundConstraint_Partitioned< Real >::hasLvec_ private
Definition at line 43 of file ROL_BoundConstraint_Partitioned.hpp.
Referenced by ROL::BoundConstraint_Partitioned< Real >::BoundConstraint_Partitioned().
hasUvec_
template<typename Real > bool ROL::BoundConstraint_Partitioned< Real >::hasUvec_ private
Definition at line 44 of file ROL_BoundConstraint_Partitioned.hpp.
Referenced by ROL::BoundConstraint_Partitioned< Real >::BoundConstraint_Partitioned().
The documentation for this class was generated from the following file:
ROL_BoundConstraint_Partitioned.hpp