ROL: ROL::ChebyshevSpectral< Real > Class Template Reference
ROL::ChebyshevSpectral< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for the Chebyshev-Spectral risk measure.
#include <ROL_ChebyshevSpectral.hpp>
Public Member Functions
ChebyshevSpectral (ROL::ParameterList &parlist)
Constructor.
ChebyshevSpectral (const Real lower, const Real upper, const int nQuad, const int wType, const ROL::Ptr< PlusFunction< Real > > &pf)
Constructor.
Public Member Functions inherited from ROL::SpectralRisk< Real >
SpectralRisk (void)
SpectralRisk (const ROL::Ptr< Distribution< Real > > &dist, const int nQuad, const ROL::Ptr< PlusFunction< Real > > &pf)
SpectralRisk (ROL::ParameterList &parlist)
SpectralRisk (const std::vector< Real > &pts, const std::vector< Real > &wts, const ROL::Ptr< PlusFunction< Real > > &pf)
void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage) override
void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage) override
void setSample (const std::vector< Real > &point, const Real weight) override
void resetStorage (bool flag=true) override
Reset internal storage.
void resetStorage (UpdateType type) override
void initialize (const Vector< Real > &x) override
Initialize temporary variables.
Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const override
Compute statistic.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal storage for value computation.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal risk measure storage for gradient computation.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol) override
Update internal risk measure storage for Hessian-time-a-vector computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure value.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure (sub)gradient.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler) override
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
Private Member Functions
void checkInputs (void) const
void initializeQuad (void)
Private Attributes
ROL::Ptr< PlusFunction< Real > > plusFunction_
Real lower_
Real upper_
int nQuad_
int wType_
std::vector< Real > wts_
std::vector< Real > pts_
Additional Inherited Members
Protected Member Functions inherited from ROL::SpectralRisk< Real >
void buildMixedQuantile (const std::vector< Real > &pts, const std::vector< Real > &wts, const ROL::Ptr< PlusFunction< Real > > &pf)
void buildQuadFromDist (std::vector< Real > &pts, std::vector< Real > &wts, const int nQuad, const ROL::Ptr< Distribution< Real > > &dist) const
void printQuad (const std::vector< Real > &pts, const std::vector< Real > &wts, const bool print=false) const
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::ChebyshevSpectral< Real >
Provides an interface for the Chebyshev-Spectral risk measure.
The Chebyshev-Spectral risk measure is defined as
\[ \mathcal{R}(X) = \int_{\alpha_0}^{\alpha_1} w(\alpha) \mathrm{CVaR}_{\alpha}(X) \,\mathrm{d}\alpha \]
where \(0\le \alpha_0 < \alpha_1 < 1\) and the conditional value-at-risk (CVaR) with confidence level \(0\le \alpha < 1\) is
\[ \mathrm{CVaR}_\alpha(X) = \inf_{t\in\mathbb{R}} \left\{ t + \frac{1}{1-\alpha} \mathbb{E}\left[(X-t)_+\right] \right\}, \quad (x)_+ = \max\{0,x\}. \]
There are three choices of weight functions \(w\): (i) the first weight function generates the Chebyshev polynomials of the first kind and has the specific form
\[ w(x) = \frac{1}{\sqrt{(x-\alpha_0)(\alpha_1-x)}}; \]
(ii) the second weight function generates the Chebyshev polynomials of the second kind and has the specific form
\[ w(x) = \sqrt{(x-\alpha_0)(\alpha_1-x)}; \]
and (iii) the third weight function is related again to the Chebyshev polynomials of the first kind and has the specific form
\[ w(x) = \sqrt{\frac{x-\alpha_0}{\alpha_1-x}}. \]
As defined, \(\mathcal{R}\) is a law-invariant coherent risk measure.
ROL implements \(\mathcal{R}\) by approximating the integral with the appropriate Gauss-Chebyshev quadrature rule. The corresponding quadrature points and weights are then used to construct a ROL::MixedQuantileQuadrangle risk measure. When using derivative-based optimization, the user can provide a smooth approximation of \((\cdot)_+\) using the ROL::PlusFunction class.
Definition at line 63 of file ROL_ChebyshevSpectral.hpp.
Constructor & Destructor Documentation
ChebyshevSpectral() [1/2]
template<class Real > ROL::ChebyshevSpectral< Real >::ChebyshevSpectral (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measure"->"Chebyshev-Spectral" and the "Chebyshev-Spectral" sublist should have the following parameters
"Lower Bound" (between 0 and 1)
"Upper Bound" (between 0 and 1, greater than "Lower Bound")
"Weight Type" (either 1, 2, or 3)
"Number of Quadrature Points"
A sublist for plus function information.
Definition at line 124 of file ROL_ChebyshevSpectral.hpp.
References ROL::ChebyshevSpectral< Real >::checkInputs(), ROL::ChebyshevSpectral< Real >::initializeQuad(), ROL::ChebyshevSpectral< Real >::lower_, ROL::ChebyshevSpectral< Real >::nQuad_, ROL::ChebyshevSpectral< Real >::plusFunction_, ROL::ChebyshevSpectral< Real >::upper_, and ROL::ChebyshevSpectral< Real >::wType_.
ChebyshevSpectral() [2/2]
template<class Real > ROL::ChebyshevSpectral< Real >::ChebyshevSpectral (const Real lower, const Real upper, const int nQuad, const int wType, const ROL::Ptr< PlusFunction< Real > > & pf) inline
Constructor.
Parameters
[in] lower is the lower confidence level (between 0 and 1)
[in] upper is the upper confidence level (between 0 and 1, greater than lower)
[in] nQuad is the number of quadrature points
[in] wType is the weight type (either 1, 2, or 3)
[in] pf is the plus function or an approximation
Definition at line 147 of file ROL_ChebyshevSpectral.hpp.
References ROL::ChebyshevSpectral< Real >::checkInputs(), and ROL::ChebyshevSpectral< Real >::initializeQuad().
Member Function Documentation
checkInputs()
template<class Real > void ROL::ChebyshevSpectral< Real >::checkInputs (void) const inline private
Definition at line 74 of file ROL_ChebyshevSpectral.hpp.
References ROL::ChebyshevSpectral< Real >::lower_, ROL::ChebyshevSpectral< Real >::plusFunction_, and ROL::ChebyshevSpectral< Real >::upper_.
Referenced by ROL::ChebyshevSpectral< Real >::ChebyshevSpectral(), and ROL::ChebyshevSpectral< Real >::ChebyshevSpectral().
initializeQuad()
template<class Real > void ROL::ChebyshevSpectral< Real >::initializeQuad (void) inline private
Definition at line 87 of file ROL_ChebyshevSpectral.hpp.
References ROL::SpectralRisk< Real >::buildMixedQuantile(), ROL::ChebyshevSpectral< Real >::lower_, ROL::ChebyshevSpectral< Real >::nQuad_, ROL::ChebyshevSpectral< Real >::plusFunction_, ROL::ChebyshevSpectral< Real >::pts_, ROL::ChebyshevSpectral< Real >::upper_, ROL::ChebyshevSpectral< Real >::wts_, and ROL::ChebyshevSpectral< Real >::wType_.
Referenced by ROL::ChebyshevSpectral< Real >::ChebyshevSpectral(), and ROL::ChebyshevSpectral< Real >::ChebyshevSpectral().
Member Data Documentation
plusFunction_
template<class Real > ROL::Ptr<PlusFunction<Real> > ROL::ChebyshevSpectral< Real >::plusFunction_ private
Definition at line 65 of file ROL_ChebyshevSpectral.hpp.
Referenced by ROL::ChebyshevSpectral< Real >::ChebyshevSpectral(), ROL::ChebyshevSpectral< Real >::checkInputs(), and ROL::ChebyshevSpectral< Real >::initializeQuad().
lower_
template<class Real > Real ROL::ChebyshevSpectral< Real >::lower_ private
Definition at line 67 of file ROL_ChebyshevSpectral.hpp.
Referenced by ROL::ChebyshevSpectral< Real >::ChebyshevSpectral(), ROL::ChebyshevSpectral< Real >::checkInputs(), and ROL::ChebyshevSpectral< Real >::initializeQuad().
upper_
template<class Real > Real ROL::ChebyshevSpectral< Real >::upper_ private
Definition at line 67 of file ROL_ChebyshevSpectral.hpp.
Referenced by ROL::ChebyshevSpectral< Real >::ChebyshevSpectral(), ROL::ChebyshevSpectral< Real >::checkInputs(), and ROL::ChebyshevSpectral< Real >::initializeQuad().
nQuad_
template<class Real > int ROL::ChebyshevSpectral< Real >::nQuad_ private
Definition at line 68 of file ROL_ChebyshevSpectral.hpp.
Referenced by ROL::ChebyshevSpectral< Real >::ChebyshevSpectral(), and ROL::ChebyshevSpectral< Real >::initializeQuad().
wType_
template<class Real > int ROL::ChebyshevSpectral< Real >::wType_ private
Definition at line 69 of file ROL_ChebyshevSpectral.hpp.
Referenced by ROL::ChebyshevSpectral< Real >::ChebyshevSpectral(), and ROL::ChebyshevSpectral< Real >::initializeQuad().
wts_
template<class Real > std::vector<Real> ROL::ChebyshevSpectral< Real >::wts_ private
Definition at line 71 of file ROL_ChebyshevSpectral.hpp.
Referenced by ROL::ChebyshevSpectral< Real >::initializeQuad().
pts_
template<class Real > std::vector<Real> ROL::ChebyshevSpectral< Real >::pts_ private
Definition at line 72 of file ROL_ChebyshevSpectral.hpp.
Referenced by ROL::ChebyshevSpectral< Real >::initializeQuad().
The documentation for this class was generated from the following file:
ROL_ChebyshevSpectral.hpp