ROL: ROL::FletcherStep< Real > Class Template Reference
ROL::FletcherStep< Real > Class Template Reference
Optimization Steps
Provides the interface to compute Fletcher steps.
#include <ROL_FletcherStep.hpp>
Public Member Functions
~FletcherStep ()
FletcherStep (ROL::ParameterList &parlist)
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality and bound constraints.
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step (equality constraint).
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality and bound constraints).
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraint).
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality and bound constraints).
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool pHeader=false) const
Print iterate status.
std::string getValueString (const Real value, const bool print) const
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Member Functions
Real computeProjGradientNorm (const Vector< Real > &g, const Vector< Real > &x, BoundConstraint< Real > &bnd)
Private Attributes
ROL::Ptr< Step< Real > > step_
ROL::Ptr< BoundConstraint< Real > > bnd_
ROL::ParameterList parlist_
ROL::Ptr< Vector< Real > > x_
Real penaltyUpdate_
bool modifyPenalty_
Real maxPenaltyParam_
Real minPenaltyParam_
bool print_
std::string subStep_
Real delta_
Real deltaMin_
Real deltaUpdate_
ETrustRegion etr_
bool bnd_activated_
ROL::Ptr< Vector< Real > > g_
int numSuccessSteps_
bool isDeltaChanged_
bool isPenaltyChanged_
AlgorithmState< Real > tr_algo_state_
int stepHeaderLength_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::FletcherStep< Real >
Provides the interface to compute Fletcher steps.
Definition at line 28 of file ROL_FletcherStep.hpp.
Constructor & Destructor Documentation
~FletcherStep()
template<class Real > ROL::FletcherStep< Real >::~FletcherStep () inline
Definition at line 88 of file ROL_FletcherStep.hpp.
FletcherStep()
template<class Real > ROL::FletcherStep< Real >::FletcherStep (ROL::ParameterList & parlist) inline
Definition at line 90 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::delta_, ROL::FletcherStep< Real >::deltaMin_, ROL::FletcherStep< Real >::deltaUpdate_, ROL::Step< Real >::getState(), ROL::FletcherStep< Real >::maxPenaltyParam_, ROL::FletcherStep< Real >::minPenaltyParam_, ROL::FletcherStep< Real >::modifyPenalty_, ROL::FletcherStep< Real >::parlist_, ROL::FletcherStep< Real >::penaltyUpdate_, ROL::FletcherStep< Real >::subStep_, and zero.
Member Function Documentation
computeProjGradientNorm()
template<class Real > Real ROL::FletcherStep< Real >::computeProjGradientNorm (const Vector< Real > & g, const Vector< Real > & x, BoundConstraint< Real > & bnd) inline private
Definition at line 65 of file ROL_FletcherStep.hpp.
References ROL::Vector< Real >::dual(), ROL::BoundConstraint< Real >::isActivated(), ROL::Vector< Real >::norm(), ROL::BoundConstraint< Real >::project(), and ROL::FletcherStep< Real >::x_.
Referenced by ROL::FletcherStep< Real >::initialize(), and ROL::FletcherStep< Real >::update().
initialize() [1/2]
template<class Real > void ROL::FletcherStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality constraint.
Reimplemented from ROL::Step< Real >.
Definition at line 113 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::bnd_, and ROL::FletcherStep< Real >::initialize().
Referenced by ROL::FletcherStep< Real >::initialize().
initialize() [2/2]
template<class Real > void ROL::FletcherStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Initialize step with equality and bound constraints.
Reimplemented from ROL::Step< Real >.
Definition at line 123 of file ROL_FletcherStep.hpp.
References ROL::AlgorithmState< Real >::aggregateGradientNorm, ROL::FletcherStep< Real >::bnd_activated_, ROL::Vector< Real >::clone(), ROL::AlgorithmState< Real >::cnorm, ROL::FletcherStep< Real >::computeProjGradientNorm(), ROL::FletcherStep< Real >::etr_, ROL::FletcherStep< Real >::g_, ROL::FletcherBase< Real >::getConstraintVec(), ROL::FletcherBase< Real >::getLagrangianGradient(), ROL::FletcherBase< Real >::getNumberConstraintEvaluations(), ROL::FletcherBase< Real >::getNumberFunctionEvaluations(), ROL::FletcherBase< Real >::getNumberGradientEvaluations(), ROL::FletcherBase< Real >::getObjectiveValue(), ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::BoundConstraint< Real >::isActivated(), ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::FletcherStep< Real >::parlist_, ROL::FletcherStep< Real >::step_, ROL::StringToETrustRegion(), ROL::FletcherStep< Real >::subStep_, ROL::FletcherStep< Real >::tr_algo_state_, ROL::AlgorithmState< Real >::value, and ROL::FletcherStep< Real >::x_.
compute() [1/3]
template<class Real > void ROL::FletcherStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality constraint).
Reimplemented from ROL::Step< Real >.
Definition at line 186 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::bnd_, and ROL::FletcherStep< Real >::compute().
Referenced by ROL::FletcherStep< Real >::compute().
compute() [2/3]
template<class Real > void ROL::FletcherStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Compute step (equality and bound constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 194 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::step_, and ROL::FletcherStep< Real >::tr_algo_state_.
update() [1/3]
template<class Real > void ROL::FletcherStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality constraint).
Reimplemented from ROL::Step< Real >.
Definition at line 202 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::bnd_, and ROL::FletcherStep< Real >::update().
Referenced by ROL::FletcherStep< Real >::update().
update() [2/3]
template<class Real > void ROL::FletcherStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, BoundConstraint< Real > & bnd, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful (equality and bound constraints).
Reimplemented from ROL::Step< Real >.
Definition at line 210 of file ROL_FletcherStep.hpp.
References ROL::AlgorithmState< Real >::aggregateGradientNorm, ROL::AlgorithmState< Real >::cnorm, ROL::FletcherStep< Real >::computeProjGradientNorm(), ROL::FletcherStep< Real >::delta_, ROL::FletcherStep< Real >::deltaMin_, ROL::FletcherStep< Real >::deltaUpdate_, ROL::AlgorithmState< Real >::flag, ROL::FletcherStep< Real >::g_, ROL::FletcherBase< Real >::getConstraintVec(), ROL::FletcherBase< Real >::getLagrangianGradient(), ROL::FletcherBase< Real >::getMultiplierVec(), ROL::FletcherBase< Real >::getNumberConstraintEvaluations(), ROL::FletcherBase< Real >::getNumberFunctionEvaluations(), ROL::FletcherBase< Real >::getNumberGradientEvaluations(), ROL::FletcherBase< Real >::getObjectiveValue(), ROL::Step< Real >::getState(), ROL::Step< Real >::getStepState(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::FletcherStep< Real >::isDeltaChanged_, ROL::FletcherStep< Real >::isPenaltyChanged_, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::iterateVec, ROL::AlgorithmState< Real >::lagmultVec, ROL::FletcherStep< Real >::maxPenaltyParam_, ROL::FletcherStep< Real >::minPenaltyParam_, ROL::FletcherStep< Real >::modifyPenalty_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::FletcherStep< Real >::numSuccessSteps_, ROL::FletcherStep< Real >::penaltyUpdate_, ROL::FletcherBase< Real >::setDelta(), ROL::FletcherBase< Real >::setPenaltyParameter(), ROL::AlgorithmState< Real >::snorm, ROL::FletcherStep< Real >::step_, ROL::FletcherStep< Real >::tr_algo_state_, ROL::Objective< Real >::value(), and ROL::AlgorithmState< Real >::value.
printHeader()
template<class Real > std::string ROL::FletcherStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 315 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::etr_, ROL::FletcherStep< Real >::step_, ROL::FletcherStep< Real >::stepHeaderLength_, ROL::FletcherStep< Real >::subStep_, and ROL::TRUSTREGION_TRUNCATEDCG.
Referenced by ROL::FletcherStep< Real >::print().
printName()
template<class Real > std::string ROL::FletcherStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 356 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::subStep_.
Referenced by ROL::FletcherStep< Real >::print().
print()
template<class Real > std::string ROL::FletcherStep< Real >::print (AlgorithmState< Real > & algo_state, bool pHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 365 of file ROL_FletcherStep.hpp.
References ROL::AlgorithmState< Real >::cnorm, ROL::FletcherStep< Real >::delta_, ROL::FletcherStep< Real >::etr_, ROL::FletcherStep< Real >::getValueString(), ROL::AlgorithmState< Real >::gnorm, ROL::FletcherStep< Real >::isDeltaChanged_, ROL::FletcherStep< Real >::isPenaltyChanged_, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::ncval, ROL::FletcherStep< Real >::printHeader(), ROL::FletcherStep< Real >::printName(), ROL::FletcherStep< Real >::step_, ROL::FletcherStep< Real >::stepHeaderLength_, ROL::FletcherStep< Real >::subStep_, ROL::FletcherStep< Real >::tr_algo_state_, ROL::TRUSTREGION_TRUNCATEDCG, and ROL::AlgorithmState< Real >::value.
Referenced by ROL::FletcherStep< Real >::getValueString().
getValueString()
template<class Real > std::string ROL::FletcherStep< Real >::getValueString (const Real value, const bool print) const inline
Definition at line 421 of file ROL_FletcherStep.hpp.
References ROL::FletcherStep< Real >::print(), and ROL::value().
Referenced by ROL::FletcherStep< Real >::print().
compute() [3/3]
template<class Real > void ROL::FletcherStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Reimplemented from ROL::Step< Real >.
Definition at line 435 of file ROL_FletcherStep.hpp.
update() [3/3]
template<class Real > void ROL::FletcherStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Reimplemented from ROL::Step< Real >.
Definition at line 442 of file ROL_FletcherStep.hpp.
Member Data Documentation
step_
template<class Real > ROL::Ptr<Step<Real> > ROL::FletcherStep< Real >::step_ private
Definition at line 30 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::compute(), ROL::FletcherStep< Real >::initialize(), ROL::FletcherStep< Real >::print(), ROL::FletcherStep< Real >::printHeader(), and ROL::FletcherStep< Real >::update().
bnd_
template<class Real > ROL::Ptr<BoundConstraint<Real> > ROL::FletcherStep< Real >::bnd_ private
Definition at line 31 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::compute(), ROL::FletcherStep< Real >::initialize(), and ROL::FletcherStep< Real >::update().
parlist_
template<class Real > ROL::ParameterList ROL::FletcherStep< Real >::parlist_ private
Definition at line 33 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), and ROL::FletcherStep< Real >::initialize().
x_
template<class Real > ROL::Ptr<Vector<Real> > ROL::FletcherStep< Real >::x_ private
Definition at line 35 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::computeProjGradientNorm(), and ROL::FletcherStep< Real >::initialize().
penaltyUpdate_
template<class Real > Real ROL::FletcherStep< Real >::penaltyUpdate_ private
Definition at line 38 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), and ROL::FletcherStep< Real >::update().
modifyPenalty_
template<class Real > bool ROL::FletcherStep< Real >::modifyPenalty_ private
Definition at line 39 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), and ROL::FletcherStep< Real >::update().
maxPenaltyParam_
template<class Real > Real ROL::FletcherStep< Real >::maxPenaltyParam_ private
Definition at line 40 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), and ROL::FletcherStep< Real >::update().
minPenaltyParam_
template<class Real > Real ROL::FletcherStep< Real >::minPenaltyParam_ private
Definition at line 41 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), and ROL::FletcherStep< Real >::update().
print_
template<class Real > bool ROL::FletcherStep< Real >::print_ private
Definition at line 43 of file ROL_FletcherStep.hpp.
subStep_
template<class Real > std::string ROL::FletcherStep< Real >::subStep_ private
Definition at line 44 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), ROL::FletcherStep< Real >::initialize(), ROL::FletcherStep< Real >::print(), ROL::FletcherStep< Real >::printHeader(), and ROL::FletcherStep< Real >::printName().
delta_
template<class Real > Real ROL::FletcherStep< Real >::delta_ private
Definition at line 46 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), ROL::FletcherStep< Real >::print(), and ROL::FletcherStep< Real >::update().
deltaMin_
template<class Real > Real ROL::FletcherStep< Real >::deltaMin_ private
Definition at line 47 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), and ROL::FletcherStep< Real >::update().
deltaUpdate_
template<class Real > Real ROL::FletcherStep< Real >::deltaUpdate_ private
Definition at line 48 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::FletcherStep(), and ROL::FletcherStep< Real >::update().
etr_
template<class Real > ETrustRegion ROL::FletcherStep< Real >::etr_ private
Definition at line 49 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::initialize(), ROL::FletcherStep< Real >::print(), and ROL::FletcherStep< Real >::printHeader().
bnd_activated_
template<class Real > bool ROL::FletcherStep< Real >::bnd_activated_ private
Definition at line 51 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::initialize().
g_
template<class Real > ROL::Ptr<Vector<Real> > ROL::FletcherStep< Real >::g_ private
Definition at line 53 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::initialize(), and ROL::FletcherStep< Real >::update().
numSuccessSteps_
template<class Real > int ROL::FletcherStep< Real >::numSuccessSteps_ private
Definition at line 55 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::update().
isDeltaChanged_
template<class Real > bool ROL::FletcherStep< Real >::isDeltaChanged_ mutable private
Definition at line 58 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::print(), and ROL::FletcherStep< Real >::update().
isPenaltyChanged_
template<class Real > bool ROL::FletcherStep< Real >::isPenaltyChanged_ mutable private
Definition at line 59 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::print(), and ROL::FletcherStep< Real >::update().
tr_algo_state_
template<class Real > AlgorithmState<Real> ROL::FletcherStep< Real >::tr_algo_state_ mutable private
Definition at line 61 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::compute(), ROL::FletcherStep< Real >::initialize(), ROL::FletcherStep< Real >::print(), and ROL::FletcherStep< Real >::update().
stepHeaderLength_
template<class Real > int ROL::FletcherStep< Real >::stepHeaderLength_ mutable private
Definition at line 63 of file ROL_FletcherStep.hpp.
Referenced by ROL::FletcherStep< Real >::print(), and ROL::FletcherStep< Real >::printHeader().
The documentation for this class was generated from the following file:
ROL_FletcherStep.hpp