ROL: ROL::GoldenSection< Real > Class Template Reference
ROL::GoldenSection< Real > Class Template Reference
Implements a golden section line search.
#include <ROL_GoldenSection.hpp>
Public Member Functions
virtual ~GoldenSection ()
GoldenSection (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con)
void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con)
Public Member Functions inherited from ROL::LineSearch< Real >
virtual ~LineSearch ()
LineSearch (ROL::ParameterList &parlist)
void setData (Real &eps, const Vector< Real > &g)
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Private Attributes
Real tol_
ROL::Ptr< Vector< Real > > xnew_
ROL::Ptr< LineSearch< Real > > btls_
Additional Inherited Members
Protected Member Functions inherited from ROL::LineSearch< Real >
virtual bool status (const ELineSearch type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
void setNextInitialAlpha (Real alpha)
void updateIterate (Vector< Real > &xnew, const Vector< Real > &x, const Vector< Real > &s, Real alpha, BoundConstraint< Real > &con)
bool useLocalMinimizer ()
bool takeNoStep ()
Detailed Description
template<class Real>
class ROL::GoldenSection< Real >
Implements a golden section line search.
Definition at line 23 of file ROL_GoldenSection.hpp.
Constructor & Destructor Documentation
~GoldenSection()
template<class Real > virtual ROL::GoldenSection< Real >::~GoldenSection () inline virtual
Definition at line 31 of file ROL_GoldenSection.hpp.
GoldenSection()
template<class Real > ROL::GoldenSection< Real >::GoldenSection (ROL::ParameterList & parlist) inline
Definition at line 34 of file ROL_GoldenSection.hpp.
References ROL::GoldenSection< Real >::btls_, and ROL::GoldenSection< Real >::tol_.
Member Function Documentation
initialize()
template<class Real > void ROL::GoldenSection< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Reimplemented from ROL::LineSearch< Real >.
Definition at line 40 of file ROL_GoldenSection.hpp.
References ROL::GoldenSection< Real >::btls_, ROL::Vector< Real >::clone(), ROL::LineSearch< Real >::initialize(), and ROL::GoldenSection< Real >::xnew_.
run()
template<class Real > void ROL::GoldenSection< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Implements ROL::LineSearch< Real >.
Definition at line 47 of file ROL_GoldenSection.hpp.
References ROL::GoldenSection< Real >::btls_, ROL::LineSearch< Real >::getInitialAlpha(), ROL::LINESEARCH_GOLDENSECTION, ROL::GoldenSection< Real >::tol_, ROL::Objective< Real >::update(), ROL::LineSearch< Real >::updateIterate(), ROL::Objective< Real >::value(), ROL::GoldenSection< Real >::xnew_, and zero.
Member Data Documentation
tol_
template<class Real > Real ROL::GoldenSection< Real >::tol_ private
Definition at line 25 of file ROL_GoldenSection.hpp.
Referenced by ROL::GoldenSection< Real >::GoldenSection(), and ROL::GoldenSection< Real >::run().
xnew_
template<class Real > ROL::Ptr<Vector<Real> > ROL::GoldenSection< Real >::xnew_ private
Definition at line 26 of file ROL_GoldenSection.hpp.
Referenced by ROL::GoldenSection< Real >::initialize(), and ROL::GoldenSection< Real >::run().
btls_
template<class Real > ROL::Ptr<LineSearch<Real> > ROL::GoldenSection< Real >::btls_ private
Definition at line 27 of file ROL_GoldenSection.hpp.
Referenced by ROL::GoldenSection< Real >::GoldenSection(), ROL::GoldenSection< Real >::initialize(), and ROL::GoldenSection< Real >::run().
The documentation for this class was generated from the following file:
ROL_GoldenSection.hpp