ROL: ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK Class Reference
ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK Class Reference
Public Member Functions
PrecondPNK (const Ptr< Objective< Real > > &obj, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< const Vector< Real > > &x, const Ptr< const Vector< Real > > &g, Real eps, const Ptr< Secant< Real > > &secant, bool useSecant, const Ptr< Vector< Real > > &pwa)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Attributes
const Ptr< Objective< Real > > obj_
const Ptr< BoundConstraint< Real > > bnd_
const Ptr< const Vector< Real > > x_
const Ptr< const Vector< Real > > g_
const Real eps_
const Ptr< Secant< Real > > secant_
const bool useSecant_
const Ptr< Vector< Real > > v_
Detailed Description
template<typename Real>
class ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK
Definition at line 87 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Constructor & Destructor Documentation
PrecondPNK()
template<typename Real > ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::PrecondPNK (const Ptr< Objective< Real > > & obj, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< const Vector< Real > > & x, const Ptr< const Vector< Real > > & g, Real eps, const Ptr< Secant< Real > > & secant, bool useSecant, const Ptr< Vector< Real > > & pwa) inline
Definition at line 98 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Member Function Documentation
apply()
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 108 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
References ROL::Vector< Real >::dual(), and ROL::Vector< Real >::set().
applyInverse()
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 111 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
References ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::bnd_, ROL::Vector< Real >::dual(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::eps_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::g_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::obj_, ROL::Vector< Real >::plus(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::secant_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::useSecant_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::v_, and ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::x_.
Member Data Documentation
obj_
template<typename Real > const Ptr<Objective<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::obj_ private
Definition at line 89 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
bnd_
template<typename Real > const Ptr<BoundConstraint<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::bnd_ private
Definition at line 90 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
x_
template<typename Real > const Ptr<const Vector<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::x_ private
Definition at line 91 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
g_
template<typename Real > const Ptr<const Vector<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::g_ private
Definition at line 92 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
eps_
template<typename Real > const Real ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::eps_ private
Definition at line 93 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::secant_ private
Definition at line 94 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
useSecant_
template<typename Real > const bool ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::useSecant_ private
Definition at line 95 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
v_
template<typename Real > const Ptr<Vector<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::v_ private
Definition at line 96 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::PrecondPNK::applyInverse().
The documentation for this class was generated from the following file:
ROL_TypeB_NewtonKrylovAlgorithm.hpp