ROL: ROL::ZOO::getHS55< Real > Class Template Reference
ROL::ZOO::getHS55< Real > Class Template Reference
#include <ROL_HS55.hpp>
Public Member Functions
getHS55 (void)
Ptr< Objective< Real > > getObjective (void) const
Ptr< Vector< Real > > getInitialGuess (void) const
Ptr< Vector< Real > > getSolution (const int i=0) const
Ptr< Constraint< Real > > getEqualityConstraint (void) const
Ptr< Vector< Real > > getEqualityMultiplier (void) const
Ptr< BoundConstraint< Real > > getBoundConstraint (void) const
Public Member Functions inherited from ROL::TestProblem< Real >
virtual ~TestProblem (void)
TestProblem (void)
virtual int getNumSolutions (void) const
virtual Ptr< Constraint< Real > > getInequalityConstraint (void) const
virtual Ptr< Vector< Real > > getInequalityMultiplier (void) const
virtual Ptr< BoundConstraint< Real > > getSlackBoundConstraint (void) const
void get (Ptr< OptimizationProblem< Real > > &problem, Ptr< Vector< Real > > &x0, std::vector< Ptr< Vector< Real > > > &x) const
Detailed Description
template<class Real>
class ROL::ZOO::getHS55< Real >
Definition at line 109 of file ROL_HS55.hpp.
Constructor & Destructor Documentation
getHS55()
template<class Real > ROL::ZOO::getHS55< Real >::getHS55 (void) inline
Definition at line 111 of file ROL_HS55.hpp.
Member Function Documentation
getObjective()
template<class Real > Ptr< Objective< Real > > ROL::ZOO::getHS55< Real >::getObjective (void) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 113 of file ROL_HS55.hpp.
Referenced by main().
getInitialGuess()
template<class Real > Ptr< Vector< Real > > ROL::ZOO::getHS55< Real >::getInitialGuess (void) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 117 of file ROL_HS55.hpp.
Referenced by main().
getSolution()
template<class Real > Ptr< Vector< Real > > ROL::ZOO::getHS55< Real >::getSolution (const int i = 0) const inline virtual
Implements ROL::TestProblem< Real >.
Definition at line 129 of file ROL_HS55.hpp.
getEqualityConstraint()
template<class Real > Ptr< Constraint< Real > > ROL::ZOO::getHS55< Real >::getEqualityConstraint (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 141 of file ROL_HS55.hpp.
Referenced by main().
getEqualityMultiplier()
template<class Real > Ptr< Vector< Real > > ROL::ZOO::getHS55< Real >::getEqualityMultiplier (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 145 of file ROL_HS55.hpp.
Referenced by main().
getBoundConstraint()
template<class Real > Ptr< BoundConstraint< Real > > ROL::ZOO::getHS55< Real >::getBoundConstraint (void) const inline virtual
Reimplemented from ROL::TestProblem< Real >.
Definition at line 150 of file ROL_HS55.hpp.
Referenced by main().
The documentation for this class was generated from the following file:
ROL_HS55.hpp