ROL: ROL::TypeB::SpectralGradientAlgorithm< Real > Class Template Reference
ROL::TypeB::SpectralGradientAlgorithm< Real > Class Template Reference
Provides an interface to run the spectral projected gradient algorithm.
#include <ROL_TypeB_SpectralGradientAlgorithm.hpp>
Public Member Functions
SpectralGradientAlgorithm (ParameterList &list)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Private Attributes
int maxit_
int maxSize_
Real lambda_
Real lambdaMin_
Real lambdaMax_
Real sigma1_
Real sigma2_
Real rhodec_
Real gamma_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::SpectralGradientAlgorithm< Real >
Provides an interface to run the spectral projected gradient algorithm.
Definition at line 23 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
Constructor & Destructor Documentation
SpectralGradientAlgorithm()
template<typename Real > ROL::TypeB::SpectralGradientAlgorithm< Real >::SpectralGradientAlgorithm (ParameterList & list)
Definition at line 19 of file ROL_TypeB_SpectralGradientAlgorithm_Def.hpp.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::SpectralGradientAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) private
Definition at line 40 of file ROL_TypeB_SpectralGradientAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeB::Algorithm< Real >::initialize(), ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and zero.
run()
template<typename Real > void ROL::TypeB::SpectralGradientAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 67 of file ROL_TypeB_SpectralGradientAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeB::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeB::SpectralGradientAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 178 of file ROL_TypeB_SpectralGradientAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeB::SpectralGradientAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 211 of file ROL_TypeB_SpectralGradientAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::SpectralGradientAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 218 of file ROL_TypeB_SpectralGradientAlgorithm_Def.hpp.
Member Data Documentation
maxit_
template<typename Real > int ROL::TypeB::SpectralGradientAlgorithm< Real >::maxit_ private
Definition at line 25 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
maxSize_
template<typename Real > int ROL::TypeB::SpectralGradientAlgorithm< Real >::maxSize_ private
Definition at line 25 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
lambda_
template<typename Real > Real ROL::TypeB::SpectralGradientAlgorithm< Real >::lambda_ private
Definition at line 26 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
lambdaMin_
template<typename Real > Real ROL::TypeB::SpectralGradientAlgorithm< Real >::lambdaMin_ private
Definition at line 26 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
lambdaMax_
template<typename Real > Real ROL::TypeB::SpectralGradientAlgorithm< Real >::lambdaMax_ private
Definition at line 26 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
sigma1_
template<typename Real > Real ROL::TypeB::SpectralGradientAlgorithm< Real >::sigma1_ private
Definition at line 26 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
sigma2_
template<typename Real > Real ROL::TypeB::SpectralGradientAlgorithm< Real >::sigma2_ private
Definition at line 26 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
rhodec_
template<typename Real > Real ROL::TypeB::SpectralGradientAlgorithm< Real >::rhodec_ private
Definition at line 26 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
gamma_
template<typename Real > Real ROL::TypeB::SpectralGradientAlgorithm< Real >::gamma_ private
Definition at line 26 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeB::SpectralGradientAlgorithm< Real >::verbosity_ private
Definition at line 27 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeB::SpectralGradientAlgorithm< Real >::writeHeader_ private
Definition at line 28 of file ROL_TypeB_SpectralGradientAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_SpectralGradientAlgorithm.hpp
ROL_TypeB_SpectralGradientAlgorithm_Def.hpp