ROL: ROL::CubicInterp< Real > Class Template Reference
ROL::CubicInterp< Real > Class Template Reference
Implements cubic interpolation back tracking line search.
#include <ROL_CubicInterp.hpp>
Public Member Functions
virtual ~CubicInterp ()
CubicInterp (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con)
void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con)
Public Member Functions inherited from ROL::LineSearch< Real >
virtual ~LineSearch ()
LineSearch (ROL::ParameterList &parlist)
void setData (Real &eps, const Vector< Real > &g)
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Private Attributes
Real rho_
ROL::Ptr< Vector< Real > > xnew_
Additional Inherited Members
Protected Member Functions inherited from ROL::LineSearch< Real >
virtual bool status (const ELineSearch type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
void setNextInitialAlpha (Real alpha)
void updateIterate (Vector< Real > &xnew, const Vector< Real > &x, const Vector< Real > &s, Real alpha, BoundConstraint< Real > &con)
bool useLocalMinimizer ()
bool takeNoStep ()
Detailed Description
template<class Real>
class ROL::CubicInterp< Real >
Implements cubic interpolation back tracking line search.
Definition at line 22 of file ROL_CubicInterp.hpp.
Constructor & Destructor Documentation
~CubicInterp()
template<class Real > virtual ROL::CubicInterp< Real >::~CubicInterp () inline virtual
Definition at line 29 of file ROL_CubicInterp.hpp.
CubicInterp()
template<class Real > ROL::CubicInterp< Real >::CubicInterp (ROL::ParameterList & parlist) inline
Definition at line 32 of file ROL_CubicInterp.hpp.
References ROL::CubicInterp< Real >::rho_.
Member Function Documentation
initialize()
template<class Real > void ROL::CubicInterp< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Reimplemented from ROL::LineSearch< Real >.
Definition at line 37 of file ROL_CubicInterp.hpp.
References ROL::Vector< Real >::clone(), ROL::LineSearch< Real >::initialize(), and ROL::CubicInterp< Real >::xnew_.
run()
template<class Real > void ROL::CubicInterp< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Implements ROL::LineSearch< Real >.
Definition at line 43 of file ROL_CubicInterp.hpp.
References ROL::LineSearch< Real >::getInitialAlpha(), ROL::LINESEARCH_CUBICINTERP, ROL::Objective< Real >::update(), ROL::LineSearch< Real >::updateIterate(), ROL::Objective< Real >::value(), and ROL::CubicInterp< Real >::xnew_.
Member Data Documentation
rho_
template<class Real > Real ROL::CubicInterp< Real >::rho_ private
Definition at line 24 of file ROL_CubicInterp.hpp.
Referenced by ROL::CubicInterp< Real >::CubicInterp().
xnew_
template<class Real > ROL::Ptr<Vector<Real> > ROL::CubicInterp< Real >::xnew_ private
Definition at line 25 of file ROL_CubicInterp.hpp.
Referenced by ROL::CubicInterp< Real >::initialize(), and ROL::CubicInterp< Real >::run().
The documentation for this class was generated from the following file:
ROL_CubicInterp.hpp