ROL: ROL::CVaR< Real > Class Template Reference
ROL::CVaR< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for a convex combination of the expected value and the conditional value-at-risk.
#include <ROL_CVaR.hpp>
Public Member Functions
CVaR (const Real prob, const Real coeff, const Ptr< PlusFunction< Real > > &pf)
Constructor.
CVaR (ROL::ParameterList &parlist)
Constructor.
void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void initialize (const Vector< Real > &x)
Initialize temporary variables.
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
Private Member Functions
void checkInputs (void) const
Private Attributes
Ptr< PlusFunction< Real > > plusFunction_
Real prob_
Real coeff_
Additional Inherited Members
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::CVaR< Real >
Provides an interface for a convex combination of the expected value and the conditional value-at-risk.
The conditional value-at-risk (also called the average value-at-risk or the expected shortfall) with confidence level \(0\le \beta < 1\) is
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \frac{1}{1-\beta} \mathbb{E}\left[(X-t)_+\right] \right\} \]
where \((x)_+ = \max\{0,x\}\). If the distribution of \(X\) is continuous, then \(\mathcal{R}\) is the conditional expectation of \(X\) exceeding the \(\beta\)-quantile of \(X\) and the optimal \(t\) is the \(\beta\)-quantile. Additionally, \(\mathcal{R}\) is a law-invariant coherent risk measure. ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
When using derivative-based optimization, the user can provide a smooth approximation of \((\cdot)_+\) using the ROL::PlusFunction class.
Definition at line 44 of file ROL_CVaR.hpp.
Constructor & Destructor Documentation
CVaR() [1/2]
template<class Real > ROL::CVaR< Real >::CVaR (const Real prob, const Real coeff, const Ptr< PlusFunction< Real > > & pf) inline
Constructor.
Parameters
[in] prob is the confidence level
[in] coeff is the convex combination parameter (coeff=0 corresponds to the expected value whereas coeff=1 corresponds to the conditional value-at-risk)
[in] pf is the plus function or an approximation
Definition at line 84 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::checkInputs().
CVaR() [2/2]
template<class Real > ROL::CVaR< Real >::CVaR (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measure"->"CVaR" and within the "CVaR" sublist should have the following parameters
"Confidence Level" (between 0 and 1)
"Convex Combination Parameter" (between 0 and 1)
A sublist for plus function information.
Definition at line 100 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::checkInputs(), ROL::CVaR< Real >::coeff_, ROL::CVaR< Real >::plusFunction_, and ROL::CVaR< Real >::prob_.
Member Function Documentation
checkInputs()
template<class Real > void ROL::CVaR< Real >::checkInputs (void) const inline private
Definition at line 64 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::coeff_, ROL::CVaR< Real >::plusFunction_, ROL::CVaR< Real >::prob_, and zero.
Referenced by ROL::CVaR< Real >::CVaR(), and ROL::CVaR< Real >::CVaR().
updateValue()
template<class Real > void ROL::CVaR< Real >::updateValue (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal storage for value computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 113 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::coeff_, ROL::RandVarFunctional< Real >::computeValue(), ROL::CVaR< Real >::plusFunction_, ROL::CVaR< Real >::prob_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
updateGradient()
template<class Real > void ROL::CVaR< Real >::updateGradient (Objective< Real > & obj, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for gradient computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 123 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradient(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::g_, ROL::CVaR< Real >::plusFunction_, ROL::CVaR< Real >::prob_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
updateHessVec()
template<class Real > void ROL::CVaR< Real >::updateHessVec (Objective< Real > & obj, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, Real & tol) inline virtual
Update internal risk measure storage for Hessian-time-a-vector computation.
Parameters
[in] val is the value of the random variable objective function at the current sample point
[in] g is the gradient of the random variable objective function at the current sample point
[in] gv is the gradient of the random variable objective function at the current sample point applied to the vector v0
[in] hv is the Hessian of the random variable objective function at the current sample point applied to the vector v0
[in] weight is the weight associated with the current sample point
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 138 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::coeff_, ROL::RandVarFunctional< Real >::computeGradVec(), ROL::RandVarFunctional< Real >::computeHessVec(), ROL::RandVarFunctional< Real >::computeValue(), ROL::RandVarFunctional< Real >::dualVector_, ROL::RandVarFunctional< Real >::hv_, ROL::CVaR< Real >::plusFunction_, ROL::CVaR< Real >::prob_, ROL::RandVarFunctional< Real >::val_, and ROL::RandVarFunctional< Real >::weight_.
getValue()
template<class Real > Real ROL::CVaR< Real >::getValue (const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure value.
Parameters
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getValue returns \(\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 162 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::coeff_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
getGradient()
template<class Real > void ROL::CVaR< Real >::getGradient (Vector< Real > & g, std::vector< Real > & gstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure (sub)gradient.
Parameters
[out] g is the (sub)gradient of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getGradient returns \(\theta\in\partial\mathcal{R}(f(x_0))\) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\) and \(\partial\mathcal{R}(X)\) denotes the subdifferential of \(\mathcal{R}\) at \(X\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 171 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::coeff_, ROL::RandVarFunctional< Real >::g_, ROL::CVaR< Real >::prob_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
getHessVec()
template<class Real > void ROL::CVaR< Real >::getHessVec (Vector< Real > & hv, std::vector< Real > & hvstat, const Vector< Real > & v, const std::vector< Real > & vstat, const Vector< Real > & x, const std::vector< Real > & xstat, SampleGenerator< Real > & sampler) inline virtual
Return risk measure Hessian-times-a-vector.
Parameters
[out] hv is the Hessian-times-a-vector of the risk measure
[in] sampler is the ROL::SampleGenerator used to sample the objective function
Upon return, getHessVec returns \(\nabla^2 \mathcal{R}(f(x_0))v_0\) (if available) where \(f(x_0)\) denotes the random variable objective function evaluated at \(x_0\).
Reimplemented from ROL::RandVarFunctional< Real >.
Definition at line 184 of file ROL_CVaR.hpp.
References ROL::CVaR< Real >::coeff_, ROL::RandVarFunctional< Real >::hv_, ROL::CVaR< Real >::prob_, ROL::SampleGenerator< Real >::sumAll(), and ROL::RandVarFunctional< Real >::val_.
Member Data Documentation
plusFunction_
template<class Real > Ptr<PlusFunction<Real> > ROL::CVaR< Real >::plusFunction_ private
Definition at line 46 of file ROL_CVaR.hpp.
Referenced by ROL::CVaR< Real >::checkInputs(), ROL::CVaR< Real >::CVaR(), ROL::CVaR< Real >::updateGradient(), ROL::CVaR< Real >::updateHessVec(), and ROL::CVaR< Real >::updateValue().
prob_
template<class Real > Real ROL::CVaR< Real >::prob_ private
Definition at line 47 of file ROL_CVaR.hpp.
Referenced by ROL::CVaR< Real >::checkInputs(), ROL::CVaR< Real >::CVaR(), ROL::CVaR< Real >::getGradient(), ROL::CVaR< Real >::getHessVec(), ROL::CVaR< Real >::updateGradient(), ROL::CVaR< Real >::updateHessVec(), and ROL::CVaR< Real >::updateValue().
coeff_
template<class Real > Real ROL::CVaR< Real >::coeff_ private
Definition at line 48 of file ROL_CVaR.hpp.
Referenced by ROL::CVaR< Real >::checkInputs(), ROL::CVaR< Real >::CVaR(), ROL::CVaR< Real >::getGradient(), ROL::CVaR< Real >::getHessVec(), ROL::CVaR< Real >::getValue(), ROL::CVaR< Real >::updateGradient(), ROL::CVaR< Real >::updateHessVec(), and ROL::CVaR< Real >::updateValue().
The documentation for this class was generated from the following file:
ROL_CVaR.hpp