ROL: ROL::TypeB::PrimalDualActiveSetAlgorithm< Real > Class Template Reference
ROL::TypeB::PrimalDualActiveSetAlgorithm< Real > Class Template Reference
Provides an interface to run the projected secant algorithm.
#include <ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp>
Classes
class HessianPDAS
class HessianPDAS_Poly
class PrecondPDAS
class PrecondPDAS_Poly
Public Member Functions
PrimalDualActiveSetAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Private Attributes
Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ESecant esec_
Secant type.
std::string secantName_
Secant name.
Ptr< Krylov< Real > > krylov_
Krylov solver object (used for inexact Newton)
EKrylov ekv_
Krylov type.
std::string krylovName_
Krylov name.
int totalKrylov_
Total number of Krylov iterations per PDAS iteration.
int iterKrylov_
Number of Krylov iterations (used for inexact Newton)
int flagKrylov_
Termination flag for Krylov method (used for inexact Newton)
bool useSecantHessVec_
Whether or not to use to a secant approximation as the Hessian.
bool useSecantPrecond_
Whether or not to use a secant approximation to precondition inexact Newton.
int maxit_
Maximum number of PDAS steps (default: 10)
int iter_
PDAS iteration counter.
int flag_
PDAS termination flag.
Real stol_
PDAS minimum step size stopping tolerance (default: 1e-8)
Real gtol_
PDAS gradient stopping tolerance (default: 1e-6)
Real scale_
Scale for dual variables in the active set, \(c\) (default: 1)
Real neps_
\(\epsilon\)-active set parameter
Real itol_
Inexact Krylov tolerance.
Real atolKrylov_
Absolute tolerance for Krylov solve (default: 1e-4)
Real rtolKrylov_
Relative tolerance for Krylov solve (default: 1e-2)
int maxitKrylov_
Maximum number of Krylov iterations (default: 100)
bool feasible_
Flag whether the current iterate is feasible or not.
int verbosity_
bool writeHeader_
bool hasPoly_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >
Provides an interface to run the projected secant algorithm.
Definition at line 25 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Constructor & Destructor Documentation
PrimalDualActiveSetAlgorithm()
template<typename Real > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 17 of file ROL_TypeB_PrimalDualActiveSetAlgorithm_Def.hpp.
References ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::atolKrylov_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::esec_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::gtol_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::maxit_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::maxitKrylov_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::rtolKrylov_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::scale_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::secant_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::secantName_, ROL::TypeB::Algorithm< Real >::status_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::stol_, ROL::StringToESecant(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::useSecantHessVec_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::useSecantPrecond_, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::verbosity_, and ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::writeHeader_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) private
Definition at line 53 of file ROL_TypeB_PrimalDualActiveSetAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeB::Algorithm< Real >::initialize(), ROL::StringToEKrylov(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
run()
template<typename Real > void ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 96 of file ROL_TypeB_PrimalDualActiveSetAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::clone(), ROL::BoundConstraint< Real >::getLowerBound(), ROL::BoundConstraint< Real >::getUpperBound(), ROL::Objective< Real >::gradient(), ROL::Objective< Real >::hessVec(), ROL::BoundConstraint< Real >::isFeasible(), ROL::Vector< Real >::norm(), ROL::Vector< Real >::plus(), ROL::BoundConstraint< Real >::project(), ROL::BoundConstraint< Real >::pruneActive(), ROL::BoundConstraint< Real >::pruneInactive(), ROL::BoundConstraint< Real >::pruneLowerInactive(), ROL::BoundConstraint< Real >::pruneUpperInactive(), ROL::Vector< Real >::set(), ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), ROL::TypeB::Algorithm< Real >::writeExitStatus(), and zero.
Referenced by main().
writeHeader()
template<typename Real > void ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 270 of file ROL_TypeB_PrimalDualActiveSetAlgorithm_Def.hpp.
References ROL::CG_FLAG_SUCCESS, ROL::CG_FLAG_UNDEFINED, ROL::ECGFlagToString(), and ROL::NumberToString().
writeName()
template<typename Real > void ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 326 of file ROL_TypeB_PrimalDualActiveSetAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 339 of file ROL_TypeB_PrimalDualActiveSetAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > Ptr<Secant<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 27 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
esec_
template<typename Real > ESecant ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::esec_ private
Secant type.
Definition at line 28 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
secantName_
template<typename Real > std::string ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::secantName_ private
Secant name.
Definition at line 29 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
krylov_
template<typename Real > Ptr<Krylov<Real> > ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::krylov_ private
Krylov solver object (used for inexact Newton)
Definition at line 31 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
ekv_
template<typename Real > EKrylov ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::ekv_ private
Krylov type.
Definition at line 32 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
krylovName_
template<typename Real > std::string ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::krylovName_ private
Krylov name.
Definition at line 33 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
totalKrylov_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::totalKrylov_ private
Total number of Krylov iterations per PDAS iteration.
Definition at line 35 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
iterKrylov_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::iterKrylov_ private
Number of Krylov iterations (used for inexact Newton)
Definition at line 36 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
flagKrylov_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::flagKrylov_ private
Termination flag for Krylov method (used for inexact Newton)
Definition at line 37 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
useSecantHessVec_
template<typename Real > bool ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::useSecantHessVec_ private
Whether or not to use to a secant approximation as the Hessian.
Definition at line 39 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
useSecantPrecond_
template<typename Real > bool ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::useSecantPrecond_ private
Whether or not to use a secant approximation to precondition inexact Newton.
Definition at line 40 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
maxit_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::maxit_ private
Maximum number of PDAS steps (default: 10)
Definition at line 42 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
iter_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::iter_ private
PDAS iteration counter.
Definition at line 43 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
flag_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::flag_ private
PDAS termination flag.
Definition at line 44 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
stol_
template<typename Real > Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::stol_ private
PDAS minimum step size stopping tolerance (default: 1e-8)
Definition at line 45 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
gtol_
template<typename Real > Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::gtol_ private
PDAS gradient stopping tolerance (default: 1e-6)
Definition at line 46 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
scale_
template<typename Real > Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::scale_ private
Scale for dual variables in the active set, \(c\) (default: 1)
Definition at line 47 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
neps_
template<typename Real > Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::neps_ private
\(\epsilon\)-active set parameter
Definition at line 48 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
itol_
template<typename Real > Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::itol_ private
Inexact Krylov tolerance.
Definition at line 49 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
atolKrylov_
template<typename Real > Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::atolKrylov_ private
Absolute tolerance for Krylov solve (default: 1e-4)
Definition at line 50 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
rtolKrylov_
template<typename Real > Real ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::rtolKrylov_ private
Relative tolerance for Krylov solve (default: 1e-2)
Definition at line 51 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
maxitKrylov_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::maxitKrylov_ private
Maximum number of Krylov iterations (default: 100)
Definition at line 52 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
feasible_
template<typename Real > bool ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::feasible_ private
Flag whether the current iterate is feasible or not.
Definition at line 53 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::verbosity_ private
Definition at line 55 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
writeHeader_
template<typename Real > bool ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::writeHeader_ private
Definition at line 56 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm().
hasPoly_
template<typename Real > bool ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::hasPoly_ private
Definition at line 57 of file ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_PrimalDualActiveSetAlgorithm.hpp
ROL_TypeB_PrimalDualActiveSetAlgorithm_Def.hpp