ROL: ROL::NonlinearCG_U< Real > Class Template Reference
ROL::NonlinearCG_U< Real > Class Template Reference
Optimization Steps
Provides the interface to compute optimization steps with nonlinear CG.
#include <ROL_NonlinearCG_U.hpp>
Public Member Functions
NonlinearCG_U (ParameterList &parlist, const Ptr< NonlinearCG< Real > > &nlcg=nullPtr)
Constructor.
void compute (Vector< Real > &s, Real &snorm, Real &sdotg, int &iter, int &flag, const Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj) override
std::string printName (void) const override
Public Member Functions inherited from ROL::DescentDirection_U< Real >
virtual ~DescentDirection_U ()
virtual void initialize (const Vector< Real > &x, const Vector< Real > &g)
virtual void update (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &gold, const Vector< Real > &gnew, const Real snorm, const int iter)
Private Attributes
Ptr< NonlinearCG< Real > > nlcg_
NonlinearCG object (used for quasi-Newton)
ENonlinearCG enlcg_
std::string ncgName_
Detailed Description
template<typename Real>
class ROL::NonlinearCG_U< Real >
Provides the interface to compute optimization steps with nonlinear CG.
Definition at line 28 of file ROL_NonlinearCG_U.hpp.
Constructor & Destructor Documentation
NonlinearCG_U()
template<typename Real > ROL::NonlinearCG_U< Real >::NonlinearCG_U (ParameterList & parlist, const Ptr< NonlinearCG< Real > > & nlcg = nullPtr) inline
Constructor.
Constructor to build a NonlinearCG object with a user-defined nonlinear CG object. Algorithmic specifications are passed in through a ROL::ParameterList.
Parameters
[in] parlist is a parameter list containing algorithmic specifications
[in] nlcg is a user-defined NonlinearCG object
Definition at line 46 of file ROL_NonlinearCG_U.hpp.
References ROL::NonlinearCG_U< Real >::enlcg_, ROL::NonlinearCG_U< Real >::ncgName_, ROL::NonlinearCG_U< Real >::nlcg_, and ROL::StringToENonlinearCG().
Member Function Documentation
compute()
template<typename Real > void ROL::NonlinearCG_U< Real >::compute (Vector< Real > & s, Real & snorm, Real & sdotg, int & iter, int & flag, const Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj) inline override virtual
Implements ROL::DescentDirection_U< Real >.
Definition at line 63 of file ROL_NonlinearCG_U.hpp.
References ROL::Vector< Real >::apply(), ROL::Vector< Real >::dual(), ROL::NonlinearCG_U< Real >::nlcg_, ROL::Vector< Real >::norm(), ROL::Vector< Real >::scale(), and ROL::Vector< Real >::set().
printName()
template<typename Real > std::string ROL::NonlinearCG_U< Real >::printName (void) const inline override virtual
Reimplemented from ROL::DescentDirection_U< Real >.
Definition at line 79 of file ROL_NonlinearCG_U.hpp.
References ROL::NonlinearCG_U< Real >::ncgName_.
Member Data Documentation
nlcg_
template<typename Real > Ptr<NonlinearCG<Real> > ROL::NonlinearCG_U< Real >::nlcg_ private
NonlinearCG object (used for quasi-Newton)
Definition at line 31 of file ROL_NonlinearCG_U.hpp.
Referenced by ROL::NonlinearCG_U< Real >::compute(), and ROL::NonlinearCG_U< Real >::NonlinearCG_U().
enlcg_
template<typename Real > ENonlinearCG ROL::NonlinearCG_U< Real >::enlcg_ private
Definition at line 32 of file ROL_NonlinearCG_U.hpp.
Referenced by ROL::NonlinearCG_U< Real >::NonlinearCG_U().
ncgName_
template<typename Real > std::string ROL::NonlinearCG_U< Real >::ncgName_ private
Definition at line 33 of file ROL_NonlinearCG_U.hpp.
Referenced by ROL::NonlinearCG_U< Real >::NonlinearCG_U(), and ROL::NonlinearCG_U< Real >::printName().
The documentation for this class was generated from the following file:
ROL_NonlinearCG_U.hpp