ROL: ROL::FletcherObjectiveE< Real >::AugSystemPrecond Class Reference
ROL::FletcherObjectiveE< Real >::AugSystemPrecond Class Reference
Public Member Functions
AugSystemPrecond (const Ptr< Constraint< Real > > con, const Ptr< const Vector< Real > > x, const Ptr< const Vector< Real > > g)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Attributes
const Ptr< Constraint< Real > > con_
const Ptr< const Vector< Real > > x_
const Ptr< const Vector< Real > > g_
Detailed Description
template<typename Real>
class ROL::FletcherObjectiveE< Real >::AugSystemPrecond
Definition at line 92 of file ROL_FletcherObjectiveE.hpp.
Constructor & Destructor Documentation
AugSystemPrecond()
template<typename Real > ROL::FletcherObjectiveE< Real >::AugSystemPrecond::AugSystemPrecond (const Ptr< Constraint< Real > > con, const Ptr< const Vector< Real > > x, const Ptr< const Vector< Real > > g) inline
Definition at line 98 of file ROL_FletcherObjectiveE.hpp.
Member Function Documentation
apply()
template<typename Real > void ROL::FletcherObjectiveE< Real >::AugSystemPrecond::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 102 of file ROL_FletcherObjectiveE.hpp.
References ROL::Vector< Real >::dual(), and ROL::Vector< Real >::set().
applyInverse()
template<typename Real > void ROL::FletcherObjectiveE< Real >::AugSystemPrecond::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 105 of file ROL_FletcherObjectiveE.hpp.
References ROL::FletcherObjectiveE< Real >::AugSystemPrecond::con_, ROL::FletcherObjectiveE< Real >::AugSystemPrecond::g_, ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::set(), and ROL::FletcherObjectiveE< Real >::AugSystemPrecond::x_.
Member Data Documentation
con_
template<typename Real > const Ptr<Constraint<Real> > ROL::FletcherObjectiveE< Real >::AugSystemPrecond::con_ private
Definition at line 94 of file ROL_FletcherObjectiveE.hpp.
Referenced by ROL::FletcherObjectiveE< Real >::AugSystemPrecond::applyInverse().
x_
template<typename Real > const Ptr<const Vector<Real> > ROL::FletcherObjectiveE< Real >::AugSystemPrecond::x_ private
Definition at line 95 of file ROL_FletcherObjectiveE.hpp.
Referenced by ROL::FletcherObjectiveE< Real >::AugSystemPrecond::applyInverse().
g_
template<typename Real > const Ptr<const Vector<Real> > ROL::FletcherObjectiveE< Real >::AugSystemPrecond::g_ private
Definition at line 96 of file ROL_FletcherObjectiveE.hpp.
Referenced by ROL::FletcherObjectiveE< Real >::AugSystemPrecond::applyInverse().
The documentation for this class was generated from the following file:
ROL_FletcherObjectiveE.hpp