ROL: ROL::DoubleDogLeg_U< Real > Class Template Reference
ROL::DoubleDogLeg_U< Real > Class Template Reference
Provides interface for the double dog leg trust-region subproblem solver.
#include <ROL_DoubleDogLeg_U.hpp>
Public Member Functions
DoubleDogLeg_U ()
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void solve (Vector< Real > &s, Real &snorm, Real &pRed, int &iflag, int &iter, const Real del, TrustRegionModel_U< Real > &model)
Public Member Functions inherited from ROL::TrustRegion_U< Real >
virtual ~TrustRegion_U ()
Private Attributes
Ptr< Vector< Real > > primal_
Ptr< Vector< Real > > dual_
Detailed Description
template<class Real>
class ROL::DoubleDogLeg_U< Real >
Provides interface for the double dog leg trust-region subproblem solver.
Definition at line 23 of file ROL_DoubleDogLeg_U.hpp.
Constructor & Destructor Documentation
DoubleDogLeg_U()
template<class Real > ROL::DoubleDogLeg_U< Real >::DoubleDogLeg_U () inline
Definition at line 30 of file ROL_DoubleDogLeg_U.hpp.
Member Function Documentation
initialize()
template<class Real > void ROL::DoubleDogLeg_U< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g) inline virtual
Reimplemented from ROL::TrustRegion_U< Real >.
Definition at line 32 of file ROL_DoubleDogLeg_U.hpp.
References ROL::Vector< Real >::clone(), ROL::DoubleDogLeg_U< Real >::dual_, and ROL::DoubleDogLeg_U< Real >::primal_.
solve()
template<class Real > void ROL::DoubleDogLeg_U< Real >::solve (Vector< Real > & s, Real & snorm, Real & pRed, int & iflag, int & iter, const Real del, TrustRegionModel_U< Real > & model) inline virtual
Implements ROL::TrustRegion_U< Real >.
Definition at line 37 of file ROL_DoubleDogLeg_U.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::DoubleDogLeg_U< Real >::dual_, ROL::TrustRegionModel_U< Real >::getGradient(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::TrustRegionModel_U< Real >::invHessVec(), ROL::Vector< Real >::norm(), ROL::DoubleDogLeg_U< Real >::primal_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and zero.
Member Data Documentation
primal_
template<class Real > Ptr<Vector<Real> > ROL::DoubleDogLeg_U< Real >::primal_ private
Definition at line 26 of file ROL_DoubleDogLeg_U.hpp.
Referenced by ROL::DoubleDogLeg_U< Real >::initialize(), and ROL::DoubleDogLeg_U< Real >::solve().
dual_
template<class Real > Ptr<Vector<Real> > ROL::DoubleDogLeg_U< Real >::dual_ private
Definition at line 26 of file ROL_DoubleDogLeg_U.hpp.
Referenced by ROL::DoubleDogLeg_U< Real >::initialize(), and ROL::DoubleDogLeg_U< Real >::solve().
The documentation for this class was generated from the following file:
ROL_DoubleDogLeg_U.hpp