ROL: ROL::ScalarController< Real, Key > Class Template Reference
ROL::ScalarController< Real, Key > Class Template Reference
#include <ROL_ScalarController.hpp>
Public Member Functions
ScalarController (void)
bool get (Real &x, const Key &param)
void set (Real x, const Key &param)
Public Member Functions inherited from ROL::VectorController< Real, Key >
VectorController (void)
Constructor.
void reset (bool flag=true)
void objectiveUpdate (bool flag=true)
Objective function update for VectorController storage.
void constraintUpdate (bool flag=true)
Equality constraint update for VectorController storage.
void objectiveUpdate (UpdateType type)
Objective function update for VectorController storage.
void constraintUpdate (UpdateType type)
Constraint update for VectorController storage.
bool isNull (const Key &param) const
Check if vector associated with provided key is allocated.
bool isComputed (const Key &param) const
Check if vector has been computed.
void allocate (const Vector< Real > &x, const Key &param)
Allocate the vector associated with provided key.
const Ptr< Vector< Real > > set (const Key &param)
Set the vector associated with provided key. This assumes the vector data will be changed.
const Ptr< const Vector< Real > > get (const Key &param) const
Return the vector associated with provided key.
bool get (Vector< Real > &x, const Key &param)
Return vector corresponding to input parameter.
void set (const Vector< Real > &x, const Key &param)
Set vector corresponding to input parameter.
void push (VectorController< Real, Key > &to) const
Push the contents of *this into another VectorController.
Detailed Description
template<class Real, class Key = std::vector<Real>>
class ROL::ScalarController< Real, Key >
Definition at line 19 of file ROL_ScalarController.hpp.
Constructor & Destructor Documentation
ScalarController()
template<class Real , class Key > ROL::ScalarController< Real, Key >::ScalarController (void)
Definition at line 16 of file ROL_ScalarController_Def.hpp.
Member Function Documentation
get()
template<class Real , class Key > bool ROL::ScalarController< Real, Key >::get (Real & x, const Key & param)
Definition at line 19 of file ROL_ScalarController_Def.hpp.
References ROL::VectorController< Real, Key >::get(), and ROL::SingletonVector< Real >::getValue().
set()
template<class Real , class Key > void ROL::ScalarController< Real, Key >::set (Real x, const Key & param)
Definition at line 27 of file ROL_ScalarController_Def.hpp.
References ROL::VectorController< Real, Key >::set().
The documentation for this class was generated from the following files:
ROL_ScalarController.hpp
ROL_ScalarController_Def.hpp