ROL: TridiagonalToeplitzOperator< Real > Class Template Reference
TridiagonalToeplitzOperator< Real > Class Template Reference
Public Member Functions
TridiagonalToeplitzOperator (Real &a, Real &b, Real &c)
void apply (V &Hv, const V &v, Real &tol) const
Apply linear operator.
void applyInverse (V &Hv, const V &v, Real &tol) const
Apply inverse of linear operator.
TridiagonalToeplitzOperator (Real &a, Real &b, Real &c)
void apply (V &Hv, const V &v, Real &tol) const
Apply linear operator.
void applyInverse (V &Hv, const V &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Types
typedef std::vector< Real > vector
typedef ROL::Vector< Real > V
typedef ROL::StdVector< Real > SV
typedef vector::size_type uint
typedef std::vector< Real > vector
typedef ROL::Vector< Real > V
typedef ROL::StdVector< Real > SV
typedef vector::size_type uint
Private Attributes
Real a_
Real b_
Real c_
ROL::LAPACK< int, Real > lapack_
Detailed Description
template<class Real>
class TridiagonalToeplitzOperator< Real >
Definition at line 38 of file step/krylov/test_01.cpp.
Member Typedef Documentation
vector [1/2]
template<class Real > typedef std::vector<Real> TridiagonalToeplitzOperator< Real >::vector private
Definition at line 40 of file step/krylov/test_01.cpp.
V [1/2]
template<class Real > typedef ROL::Vector<Real> TridiagonalToeplitzOperator< Real >::V private
Definition at line 41 of file step/krylov/test_01.cpp.
SV [1/2]
template<class Real > typedef ROL::StdVector<Real> TridiagonalToeplitzOperator< Real >::SV private
Definition at line 42 of file step/krylov/test_01.cpp.
uint [1/2]
template<class Real > typedef vector::size_type TridiagonalToeplitzOperator< Real >::uint private
Definition at line 44 of file step/krylov/test_01.cpp.
vector [2/2]
template<class Real > typedef std::vector<Real> TridiagonalToeplitzOperator< Real >::vector private
Definition at line 39 of file step/krylov/test_03.cpp.
V [2/2]
template<class Real > typedef ROL::Vector<Real> TridiagonalToeplitzOperator< Real >::V private
Definition at line 40 of file step/krylov/test_03.cpp.
SV [2/2]
template<class Real > typedef ROL::StdVector<Real> TridiagonalToeplitzOperator< Real >::SV private
Definition at line 41 of file step/krylov/test_03.cpp.
uint [2/2]
template<class Real > typedef vector::size_type TridiagonalToeplitzOperator< Real >::uint private
Definition at line 43 of file step/krylov/test_03.cpp.
Constructor & Destructor Documentation
TridiagonalToeplitzOperator() [1/2]
template<class Real > TridiagonalToeplitzOperator< Real >::TridiagonalToeplitzOperator (Real & a, Real & b, Real & c) inline
Definition at line 56 of file step/krylov/test_01.cpp.
TridiagonalToeplitzOperator() [2/2]
template<class Real > TridiagonalToeplitzOperator< Real >::TridiagonalToeplitzOperator (Real & a, Real & b, Real & c) inline
Definition at line 55 of file step/krylov/test_03.cpp.
Member Function Documentation
apply() [1/2]
template<class Real > void TridiagonalToeplitzOperator< Real >::apply (V & Hv, const V & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 59 of file step/krylov/test_01.cpp.
References TridiagonalToeplitzOperator< Real >::a_, TridiagonalToeplitzOperator< Real >::b_, TridiagonalToeplitzOperator< Real >::c_, and ROL::StdVector< Real, Element >::getVector().
Referenced by main().
applyInverse() [1/2]
template<class Real > void TridiagonalToeplitzOperator< Real >::applyInverse (V & Hv, const V & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 82 of file step/krylov/test_01.cpp.
References TridiagonalToeplitzOperator< Real >::a_, TridiagonalToeplitzOperator< Real >::b_, TridiagonalToeplitzOperator< Real >::c_, ROL::StdVector< Real, Element >::getVector(), TridiagonalToeplitzOperator< Real >::lapack_, and ROL::Vector< Real >::set().
Referenced by main().
apply() [2/2]
template<class Real > void TridiagonalToeplitzOperator< Real >::apply (V & Hv, const V & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 58 of file step/krylov/test_03.cpp.
References TridiagonalToeplitzOperator< Real >::a_, TridiagonalToeplitzOperator< Real >::b_, TridiagonalToeplitzOperator< Real >::c_, and ROL::StdVector< Real, Element >::getVector().
applyInverse() [2/2]
template<class Real > void TridiagonalToeplitzOperator< Real >::applyInverse (V & Hv, const V & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 79 of file step/krylov/test_03.cpp.
References TridiagonalToeplitzOperator< Real >::a_, TridiagonalToeplitzOperator< Real >::b_, TridiagonalToeplitzOperator< Real >::c_, ROL::StdVector< Real, Element >::getVector(), TridiagonalToeplitzOperator< Real >::lapack_, and ROL::Vector< Real >::set().
Member Data Documentation
a_
template<class Real > Real TridiagonalToeplitzOperator< Real >::a_ private
Definition at line 48 of file step/krylov/test_01.cpp.
Referenced by TridiagonalToeplitzOperator< Real >::apply(), and TridiagonalToeplitzOperator< Real >::applyInverse().
b_
template<class Real > Real TridiagonalToeplitzOperator< Real >::b_ private
Definition at line 49 of file step/krylov/test_01.cpp.
Referenced by TridiagonalToeplitzOperator< Real >::apply(), and TridiagonalToeplitzOperator< Real >::applyInverse().
c_
template<class Real > Real TridiagonalToeplitzOperator< Real >::c_ private
Definition at line 50 of file step/krylov/test_01.cpp.
Referenced by TridiagonalToeplitzOperator< Real >::apply(), and TridiagonalToeplitzOperator< Real >::applyInverse().
lapack_
template<class Real > ROL::LAPACK< int, Real > TridiagonalToeplitzOperator< Real >::lapack_ private
Definition at line 52 of file step/krylov/test_01.cpp.
Referenced by TridiagonalToeplitzOperator< Real >::applyInverse().
The documentation for this class was generated from the following files:
step/krylov/test_01.cpp
step/krylov/test_03.cpp