ROL: ROL::ElasticObjective< Real > Class Template Reference
ROL::ElasticObjective< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate the elastic augmented Lagrangian.
#include <ROL_ElasticObjective.hpp>
Public Member Functions
ElasticObjective (const Ptr< Objective< Real > > &obj, const Ptr< Constraint< Real > > &con, const Real penaltyParameter, const Real sigma, const Vector< Real > &dualOptVec, const Vector< Real > &primConVec, const Vector< Real > &dualConVec, ParameterList &parlist)
ElasticObjective (const Ptr< Objective< Real > > &obj, const Ptr< Constraint< Real > > &con, const Real penaltyParameter, const Real sigma, const Vector< Real > &dualOptVec, const Vector< Real > &primConVec, const Vector< Real > &dualConVec, const bool scaleLagrangian, const int HessianApprox)
void update (const Vector< Real > &x, UpdateType type, int iter=-1) override
Update objective function.
Real value (const Vector< Real > &x, Real &tol) override
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol) override
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol) override
Apply Hessian approximation to vector.
void setScaling (const Real fscale=1.0, const Real cscale=1.0)
Real getObjectiveValue (const Vector< Real > &x, Real &tol)
const Ptr< const Vector< Real > > getObjectiveGradient (const Vector< Real > &x, Real &tol)
const Ptr< const Vector< Real > > getConstraintVec (const Vector< Real > &x, Real &tol)
int getNumberConstraintEvaluations (void) const
int getNumberFunctionEvaluations (void) const
int getNumberGradientEvaluations (void) const
void reset (const Vector< Real > &multiplier, Real penaltyParameter, Real sigma)
const Ptr< AugmentedLagrangianObjective< Real > > getAugmentedLagrangian (void) const
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
Ptr< AugmentedLagrangianObjective< Real > > alobj_
Ptr< Vector< Real > > e_
Ptr< Vector< Real > > tmp_
Real sigma_
Real cscale_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<typename Real>
class ROL::ElasticObjective< Real >
Provides the interface to evaluate the elastic augmented Lagrangian.
This class implements the elastic augmented Lagrangian functional for use with ROL::StablizedLCLAlgorithm. Given a function \(f:\mathcal{X}\to\mathbb{R}\) and an equality constraint \(c:\mathcal{X}\to\mathcal{C}\), the augmented Lagrangian functional is
\[ L_A(x,\lambda,\mu) = f(x) + \langle \lambda, c(x)\rangle_{\mathcal{C}^*,\mathcal{C}} + \frac{\mu}{2} \langle \mathfrak{R}c(x),c(x)\rangle_{\mathcal{C}^*,\mathcal{C}} + \sigma\langle \mathfrak{R} e, u-v\rangle_{\mathcal{C}^*,\mathcal{C}} \]
where \(\lambda\in\mathcal{C}^*\) denotes the Lagrange multiplier estimate, \(\mu > 0\) and \(\sigma>0\) are penalty parameters, \(e\in\mathcal{C}\) is the constant one vector, and \(\mathfrak{R}\in\mathcal{L}(\mathcal{C},\mathcal{C}^*)\) is the Riesz operator on the constraint space.
This implementation permits the scaling of \(L_A\) by \(\mu^{-1}\) and also permits the Hessian approximation
\[ \nabla^2_x L_A(x,\lambda,\mu)v \approx \nabla^2 f(x) v + \mu c'(x)^*\mathfrak{R} c'(x)v. \]
Definition at line 49 of file ROL_ElasticObjective.hpp.
Constructor & Destructor Documentation
ElasticObjective() [1/2]
template<typename Real > ROL::ElasticObjective< Real >::ElasticObjective (const Ptr< Objective< Real > > & obj, const Ptr< Constraint< Real > > & con, const Real penaltyParameter, const Real sigma, const Vector< Real > & dualOptVec, const Vector< Real > & primConVec, const Vector< Real > & dualConVec, ParameterList & parlist)
Definition at line 17 of file ROL_ElasticObjective_Def.hpp.
References ROL::ElasticObjective< Real >::alobj_, ROL::Vector< Real >::clone(), ROL::ElasticObjective< Real >::e_, and ROL::ElasticObjective< Real >::tmp_.
ElasticObjective() [2/2]
template<typename Real > ROL::ElasticObjective< Real >::ElasticObjective (const Ptr< Objective< Real > > & obj, const Ptr< Constraint< Real > > & con, const Real penaltyParameter, const Real sigma, const Vector< Real > & dualOptVec, const Vector< Real > & primConVec, const Vector< Real > & dualConVec, const bool scaleLagrangian, const int HessianApprox)
Definition at line 32 of file ROL_ElasticObjective_Def.hpp.
References ROL::ElasticObjective< Real >::alobj_, ROL::Vector< Real >::clone(), ROL::ElasticObjective< Real >::e_, and ROL::ElasticObjective< Real >::tmp_.
Member Function Documentation
update()
template<typename Real > void ROL::ElasticObjective< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 48 of file ROL_ElasticObjective_Def.hpp.
value()
template<typename Real > Real ROL::ElasticObjective< Real >::value (const Vector< Real > & x, Real & tol) override virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 60 of file ROL_ElasticObjective_Def.hpp.
gradient()
template<typename Real > void ROL::ElasticObjective< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) override virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 71 of file ROL_ElasticObjective_Def.hpp.
hessVec()
template<typename Real > void ROL::ElasticObjective< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) override virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 82 of file ROL_ElasticObjective_Def.hpp.
setScaling()
template<typename Real > void ROL::ElasticObjective< Real >::setScaling (const Real fscale = 1.0, const Real cscale = 1.0)
Definition at line 54 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize().
getObjectiveValue()
template<typename Real > Real ROL::ElasticObjective< Real >::getObjectiveValue (const Vector< Real > & x, Real & tol)
Definition at line 94 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
getObjectiveGradient()
template<typename Real > const Ptr< const Vector< Real > > ROL::ElasticObjective< Real >::getObjectiveGradient (const Vector< Real > & x, Real & tol)
Definition at line 99 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize().
getConstraintVec()
template<typename Real > const Ptr< const Vector< Real > > ROL::ElasticObjective< Real >::getConstraintVec (const Vector< Real > & x, Real & tol)
Definition at line 104 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
getNumberConstraintEvaluations()
template<typename Real > int ROL::ElasticObjective< Real >::getNumberConstraintEvaluations (void) const
Definition at line 109 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
getNumberFunctionEvaluations()
template<typename Real > int ROL::ElasticObjective< Real >::getNumberFunctionEvaluations (void) const
Definition at line 114 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
getNumberGradientEvaluations()
template<typename Real > int ROL::ElasticObjective< Real >::getNumberGradientEvaluations (void) const
Definition at line 119 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
reset()
template<typename Real > void ROL::ElasticObjective< Real >::reset (const Vector< Real > & multiplier, Real penaltyParameter, Real sigma)
Definition at line 124 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
getAugmentedLagrangian()
template<typename Real > const Ptr< AugmentedLagrangianObjective< Real > > ROL::ElasticObjective< Real >::getAugmentedLagrangian (void) const
Definition at line 130 of file ROL_ElasticObjective_Def.hpp.
Referenced by ROL::TypeG::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeE::StabilizedLCLAlgorithm< Real >::initialize(), ROL::TypeG::StabilizedLCLAlgorithm< Real >::run(), and ROL::TypeE::StabilizedLCLAlgorithm< Real >::run().
Member Data Documentation
alobj_
template<typename Real > Ptr<AugmentedLagrangianObjective<Real> > ROL::ElasticObjective< Real >::alobj_ private
Definition at line 52 of file ROL_ElasticObjective.hpp.
Referenced by ROL::ElasticObjective< Real >::ElasticObjective(), and ROL::ElasticObjective< Real >::ElasticObjective().
e_
template<typename Real > Ptr<Vector<Real> > ROL::ElasticObjective< Real >::e_ private
Definition at line 53 of file ROL_ElasticObjective.hpp.
Referenced by ROL::ElasticObjective< Real >::ElasticObjective(), and ROL::ElasticObjective< Real >::ElasticObjective().
tmp_
template<typename Real > Ptr<Vector<Real> > ROL::ElasticObjective< Real >::tmp_ private
Definition at line 53 of file ROL_ElasticObjective.hpp.
Referenced by ROL::ElasticObjective< Real >::ElasticObjective(), and ROL::ElasticObjective< Real >::ElasticObjective().
sigma_
template<typename Real > Real ROL::ElasticObjective< Real >::sigma_ private
Definition at line 54 of file ROL_ElasticObjective.hpp.
cscale_
template<typename Real > Real ROL::ElasticObjective< Real >::cscale_ private
Definition at line 54 of file ROL_ElasticObjective.hpp.
The documentation for this class was generated from the following files:
ROL_ElasticObjective.hpp
ROL_ElasticObjective_Def.hpp