ROL: ROL::AbsoluteValue< Real > Class Template Reference
ROL::AbsoluteValue< Real > Class Template Reference
#include <ROL_AbsoluteValue.hpp>
Public Member Functions
AbsoluteValue (Real param=1., EAbsoluteValue eav=ABSOLUTEVALUE_TRUE)
AbsoluteValue (ROL::ParameterList &parlist)
Real evaluate (Real input, int deriv)
Public Member Functions inherited from ROL::PositiveFunction< Real >
virtual ~PositiveFunction ()
Private Member Functions
Real true_absolute_value (Real input, int deriv)
Real sqrt_absolute_value (Real input, int deriv)
Real sqrtd_absolute_value (Real input, int deriv)
Real c2_absolute_value (Real input, int deriv)
Private Attributes
Real param_
EAbsoluteValue eav_
Detailed Description
template<class Real>
class ROL::AbsoluteValue< Real >
Definition at line 28 of file ROL_AbsoluteValue.hpp.
Constructor & Destructor Documentation
AbsoluteValue() [1/2]
template<class Real > ROL::AbsoluteValue< Real >::AbsoluteValue (Real param = 1., EAbsoluteValue< Real > eav = ABSOLUTEVALUE_TRUE) inline
Definition at line 34 of file ROL_AbsoluteValue.hpp.
References ROL::ABSOLUTEVALUE_TRUE, and ROL::AbsoluteValue< Real >::param_.
AbsoluteValue() [2/2]
template<class Real > ROL::AbsoluteValue< Real >::AbsoluteValue (ROL::ParameterList & parlist) inline
Definition at line 39 of file ROL_AbsoluteValue.hpp.
References ROL::ABSOLUTEVALUE_C2, ROL::ABSOLUTEVALUE_SQRTDENOM, ROL::ABSOLUTEVALUE_SQUAREROOT, ROL::ABSOLUTEVALUE_TRUE, ROL::AbsoluteValue< Real >::eav_, and ROL::AbsoluteValue< Real >::param_.
Member Function Documentation
evaluate()
template<class Real > Real ROL::AbsoluteValue< Real >::evaluate (Real input, int deriv) inline virtual
Implements ROL::PositiveFunction< Real >.
Definition at line 50 of file ROL_AbsoluteValue.hpp.
References ROL::ABSOLUTEVALUE_C2, ROL::ABSOLUTEVALUE_SQRTDENOM, ROL::ABSOLUTEVALUE_SQUAREROOT, ROL::ABSOLUTEVALUE_TRUE, ROL::AbsoluteValue< Real >::c2_absolute_value(), ROL::AbsoluteValue< Real >::eav_, ROL::AbsoluteValue< Real >::sqrt_absolute_value(), ROL::AbsoluteValue< Real >::sqrtd_absolute_value(), and ROL::AbsoluteValue< Real >::true_absolute_value().
true_absolute_value()
template<class Real > Real ROL::AbsoluteValue< Real >::true_absolute_value (Real input, int deriv) inline private
Definition at line 65 of file ROL_AbsoluteValue.hpp.
References ROL::AbsoluteValue< Real >::param_.
Referenced by ROL::AbsoluteValue< Real >::evaluate().
sqrt_absolute_value()
template<class Real > Real ROL::AbsoluteValue< Real >::sqrt_absolute_value (Real input, int deriv) inline private
Definition at line 83 of file ROL_AbsoluteValue.hpp.
References ROL::AbsoluteValue< Real >::param_.
Referenced by ROL::AbsoluteValue< Real >::evaluate().
sqrtd_absolute_value()
template<class Real > Real ROL::AbsoluteValue< Real >::sqrtd_absolute_value (Real input, int deriv) inline private
Definition at line 91 of file ROL_AbsoluteValue.hpp.
References ROL::AbsoluteValue< Real >::param_.
Referenced by ROL::AbsoluteValue< Real >::evaluate().
c2_absolute_value()
template<class Real > Real ROL::AbsoluteValue< Real >::c2_absolute_value (Real input, int deriv) inline private
Definition at line 101 of file ROL_AbsoluteValue.hpp.
References ROL::AbsoluteValue< Real >::param_.
Referenced by ROL::AbsoluteValue< Real >::evaluate().
Member Data Documentation
param_
template<class Real > Real ROL::AbsoluteValue< Real >::param_ private
Definition at line 30 of file ROL_AbsoluteValue.hpp.
Referenced by ROL::AbsoluteValue< Real >::AbsoluteValue(), ROL::AbsoluteValue< Real >::AbsoluteValue(), ROL::AbsoluteValue< Real >::c2_absolute_value(), ROL::AbsoluteValue< Real >::sqrt_absolute_value(), ROL::AbsoluteValue< Real >::sqrtd_absolute_value(), and ROL::AbsoluteValue< Real >::true_absolute_value().
eav_
template<class Real > EAbsoluteValue ROL::AbsoluteValue< Real >::eav_ private
Definition at line 31 of file ROL_AbsoluteValue.hpp.
Referenced by ROL::AbsoluteValue< Real >::AbsoluteValue(), and ROL::AbsoluteValue< Real >::evaluate().
The documentation for this class was generated from the following file:
ROL_AbsoluteValue.hpp