ROL: ROL::lDFP< Real > Class Template Reference
ROL::lDFP< Real > Class Template Reference
Provides definitions for limited-memory DFP operators.
#include <ROL_lDFP.hpp>
Public Member Functions
lDFP (int M, bool useDefaultScaling=true, Real Bscaling=Real(1))
void applyH (Vector< Real > &Hv, const Vector< Real > &v) const
virtual void applyH0 (Vector< Real > &Hv, const Vector< Real > &v) const
void applyB (Vector< Real > &Bv, const Vector< Real > &v) const
virtual void applyB0 (Vector< Real > &Bv, const Vector< Real > &v) const
Public Member Functions inherited from ROL::Secant< Real >
virtual ~Secant ()
Secant (int M=10, bool useDefaultScaling=true, Real Bscaling=Real(1), ESecantMode mode=SECANTMODE_BOTH)
Ptr< SecantState< Real > > & get_state ()
const Ptr< SecantState< Real > > & get_state () const
virtual void updateStorage (const Vector< Real > &x, const Vector< Real > &grad, const Vector< Real > &gp, const Vector< Real > &s, const Real snorm, const int iter)
void test (std::ostream &stream=std::cout) const
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Additional Inherited Members
Protected Attributes inherited from ROL::Secant< Real >
const Ptr< SecantState< Real > > state_
Ptr< Vector< Real > > y_
bool useDefaultScaling_
Real Bscaling_
Detailed Description
template<class Real>
class ROL::lDFP< Real >
Provides definitions for limited-memory DFP operators.
Definition at line 22 of file ROL_lDFP.hpp.
Constructor & Destructor Documentation
lDFP()
template<class Real > ROL::lDFP< Real >::lDFP (int M, bool useDefaultScaling = true, Real Bscaling = Real(1)) inline
Definition at line 29 of file ROL_lDFP.hpp.
Member Function Documentation
applyH()
template<class Real > void ROL::lDFP< Real >::applyH (Vector< Real > & Hv, const Vector< Real > & v) const inline virtual
Implements ROL::Secant< Real >.
Definition at line 33 of file ROL_lDFP.hpp.
References ROL::lDFP< Real >::applyH0(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), and ROL::Secant< Real >::state_.
applyH0()
template<class Real > virtual void ROL::lDFP< Real >::applyH0 (Vector< Real > & Hv, const Vector< Real > & v) const inline virtual
Reimplemented from ROL::Secant< Real >.
Definition at line 71 of file ROL_lDFP.hpp.
References ROL::Secant< Real >::Bscaling_, ROL::Vector< Real >::dual(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::Secant< Real >::state_, and ROL::Secant< Real >::useDefaultScaling_.
Referenced by ROL::lDFP< Real >::applyH().
applyB()
template<class Real > void ROL::lDFP< Real >::applyB (Vector< Real > & Bv, const Vector< Real > & v) const inline virtual
Implements ROL::Secant< Real >.
Definition at line 85 of file ROL_lDFP.hpp.
References ROL::lDFP< Real >::applyB0(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::set(), ROL::Secant< Real >::state_, and zero.
applyB0()
template<class Real > virtual void ROL::lDFP< Real >::applyB0 (Vector< Real > & Bv, const Vector< Real > & v) const inline virtual
Reimplemented from ROL::Secant< Real >.
Definition at line 111 of file ROL_lDFP.hpp.
References ROL::Secant< Real >::Bscaling_, ROL::Vector< Real >::dual(), ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::Secant< Real >::state_, and ROL::Secant< Real >::useDefaultScaling_.
Referenced by ROL::lDFP< Real >::applyB().
The documentation for this class was generated from the following file:
ROL_lDFP.hpp