ROL: ROL::VectorArray< Real > Class Template Reference
ROL::VectorArray< Real > Class Template Reference
#include <ROL_GMRES.hpp>
Public Member Functions
VectorArray ()
void allocate (const Vector< Real > &x, unsigned numVec)
const Ptr< Vector< Real > > get (const Vector< Real > &x, unsigned ind)
const Ptr< Vector< Real > > get (unsigned ind)
Private Attributes
std::vector< Ptr< Vector< Real > > > data_
unsigned size_
Detailed Description
template<class Real>
class ROL::VectorArray< Real >
Definition at line 26 of file ROL_GMRES.hpp.
Constructor & Destructor Documentation
VectorArray()
template<class Real > ROL::VectorArray< Real >::VectorArray () inline
Definition at line 32 of file ROL_GMRES.hpp.
Member Function Documentation
allocate()
template<class Real > void ROL::VectorArray< Real >::allocate (const Vector< Real > & x, unsigned numVec) inline
Definition at line 34 of file ROL_GMRES.hpp.
References ROL::Vector< Real >::clone(), ROL::VectorArray< Real >::data_, and ROL::VectorArray< Real >::size_.
get() [1/2]
template<class Real > const Ptr< Vector< Real > > ROL::VectorArray< Real >::get (const Vector< Real > & x, unsigned ind) inline
Definition at line 41 of file ROL_GMRES.hpp.
References ROL::Vector< Real >::clone(), ROL::VectorArray< Real >::data_, and ROL::VectorArray< Real >::size_.
Referenced by ROL::VectorArray< Real >::get().
get() [2/2]
template<class Real > const Ptr< Vector< Real > > ROL::VectorArray< Real >::get (unsigned ind) inline
Definition at line 56 of file ROL_GMRES.hpp.
References ROL::VectorArray< Real >::data_, ROL::VectorArray< Real >::get(), and ROL::VectorArray< Real >::size_.
Member Data Documentation
data_
template<class Real > std::vector<Ptr<Vector<Real> > > ROL::VectorArray< Real >::data_ private
Definition at line 28 of file ROL_GMRES.hpp.
Referenced by ROL::VectorArray< Real >::allocate(), ROL::VectorArray< Real >::get(), and ROL::VectorArray< Real >::get().
size_
template<class Real > unsigned ROL::VectorArray< Real >::size_ private
Definition at line 29 of file ROL_GMRES.hpp.
Referenced by ROL::VectorArray< Real >::allocate(), ROL::VectorArray< Real >::get(), and ROL::VectorArray< Real >::get().
The documentation for this class was generated from the following file:
ROL_GMRES.hpp