ROL: ROL::PD_RandVarFunctional< Real > Class Template Reference
ROL::PD_RandVarFunctional< Real > Class Template Reference
#include <ROL_PD_RandVarFunctional.hpp>
Public Member Functions
PD_RandVarFunctional (void)
void setData (SampleGenerator< Real > &sampler, const Real pen, const Real lam=0.0)
virtual Real computeDual (SampleGenerator< Real > &sampler)
void updateDual (SampleGenerator< Real > &sampler)
void updatePenalty (const Real pen)
virtual void setStorage (const Ptr< ScalarController< Real > > &value_storage, const Ptr< VectorController< Real > > &gradient_storage)
virtual void setHessVecStorage (const Ptr< ScalarController< Real > > &gradvec_storage, const Ptr< VectorController< Real > > &hessvec_storage)
virtual void initialize (const Vector< Real > &x)
Initialize temporary variables.
Public Member Functions inherited from ROL::RandVarFunctional< Real >
virtual ~RandVarFunctional ()
RandVarFunctional (void)
void useStorage (bool storage)
void useHessVecStorage (bool storage)
virtual void resetStorage (bool flag=true)
Reset internal storage.
virtual void resetStorage (UpdateType type)
virtual void setSample (const std::vector< Real > &point, const Real weight)
virtual Real computeStatistic (const Ptr< const std::vector< Real > > &xstat) const
Compute statistic.
virtual void updateValue (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal storage for value computation.
virtual void updateGradient (Objective< Real > &obj, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for gradient computation.
virtual void updateHessVec (Objective< Real > &obj, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, Real &tol)
Update internal risk measure storage for Hessian-time-a-vector computation.
virtual Real getValue (const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure value.
virtual void getGradient (Vector< Real > &g, std::vector< Real > &gstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure (sub)gradient.
virtual void getHessVec (Vector< Real > &hv, std::vector< Real > &hvstat, const Vector< Real > &v, const std::vector< Real > &vstat, const Vector< Real > &x, const std::vector< Real > &xstat, SampleGenerator< Real > &sampler)
Return risk measure Hessian-times-a-vector.
Protected Member Functions
void setValue (const Real val, const std::vector< Real > &pt)
void getMultiplier (Real &lam, const std::vector< Real > &pt) const
void setMultiplier (Real &lam, const std::vector< Real > &pt)
Real getPenaltyParameter (void) const
Real ppf (const Real x, const Real t, const Real r, const int deriv=0) const
Protected Member Functions inherited from ROL::RandVarFunctional< Real >
Real computeValue (Objective< Real > &obj, const Vector< Real > &x, Real &tol)
void computeGradient (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &x, Real &tol)
Real computeGradVec (Vector< Real > &g, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
void computeHessVec (Vector< Real > &hv, Objective< Real > &obj, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Private Types
typedef std::vector< Real >::size_type uint
Private Attributes
Real pen_
int update_
bool setData_
Ptr< ScalarController< Real > > values_
Ptr< ScalarController< Real > > multipliers_
Ptr< ScalarController< Real > > multipliers_new_
Additional Inherited Members
Protected Attributes inherited from ROL::RandVarFunctional< Real >
Real val_
Real gv_
Ptr< Vector< Real > > g_
Ptr< Vector< Real > > hv_
Ptr< Vector< Real > > dualVector_
bool firstReset_
std::vector< Real > point_
Real weight_
Detailed Description
template<class Real>
class ROL::PD_RandVarFunctional< Real >
Definition at line 18 of file ROL_PD_RandVarFunctional.hpp.
Member Typedef Documentation
uint
template<class Real > typedef std::vector<Real>::size_type ROL::PD_RandVarFunctional< Real >::uint private
Definition at line 19 of file ROL_PD_RandVarFunctional.hpp.
Constructor & Destructor Documentation
PD_RandVarFunctional()
template<class Real > ROL::PD_RandVarFunctional< Real >::PD_RandVarFunctional (void) inline
Definition at line 68 of file ROL_PD_RandVarFunctional.hpp.
References ROL::PD_RandVarFunctional< Real >::multipliers_, ROL::PD_RandVarFunctional< Real >::multipliers_new_, and ROL::PD_RandVarFunctional< Real >::values_.
Member Function Documentation
setValue()
template<class Real > void ROL::PD_RandVarFunctional< Real >::setValue (const Real val, const std::vector< Real > & pt) inline protected
Definition at line 31 of file ROL_PD_RandVarFunctional.hpp.
References ROL::PD_RandVarFunctional< Real >::values_.
Referenced by ROL::PD_MeanSemiDeviation< Real >::getValue(), ROL::PD_BPOE< Real >::updateValue(), ROL::PD_CVaR< Real >::updateValue(), ROL::PD_HMCR2< Real >::updateValue(), and ROL::PD_MeanSemiDeviationFromTarget< Real >::updateValue().
getMultiplier()
template<class Real > void ROL::PD_RandVarFunctional< Real >::getMultiplier (Real & lam, const std::vector< Real > & pt) const inline protected
Definition at line 36 of file ROL_PD_RandVarFunctional.hpp.
References ROL::PD_RandVarFunctional< Real >::multipliers_.
Referenced by ROL::PD_HMCR2< Real >::computeDual(), ROL::PD_MeanSemiDeviation< Real >::getGradient(), ROL::PD_MeanSemiDeviation< Real >::getHessVec(), ROL::PD_MeanSemiDeviation< Real >::getValue(), ROL::PD_BPOE< Real >::updateGradient(), ROL::PD_CVaR< Real >::updateGradient(), ROL::PD_HMCR2< Real >::updateGradient(), ROL::PD_MeanSemiDeviationFromTarget< Real >::updateGradient(), ROL::PD_BPOE< Real >::updateHessVec(), ROL::PD_CVaR< Real >::updateHessVec(), ROL::PD_HMCR2< Real >::updateHessVec(), ROL::PD_MeanSemiDeviationFromTarget< Real >::updateHessVec(), ROL::PD_BPOE< Real >::updateValue(), ROL::PD_CVaR< Real >::updateValue(), ROL::PD_HMCR2< Real >::updateValue(), and ROL::PD_MeanSemiDeviationFromTarget< Real >::updateValue().
setMultiplier()
template<class Real > void ROL::PD_RandVarFunctional< Real >::setMultiplier (Real & lam, const std::vector< Real > & pt) inline protected
Definition at line 40 of file ROL_PD_RandVarFunctional.hpp.
References ROL::PD_RandVarFunctional< Real >::multipliers_new_.
Referenced by ROL::PD_HMCR2< Real >::computeDual().
getPenaltyParameter()
template<class Real > Real ROL::PD_RandVarFunctional< Real >::getPenaltyParameter (void) const inline protected
Definition at line 45 of file ROL_PD_RandVarFunctional.hpp.
References ROL::PD_RandVarFunctional< Real >::pen_.
Referenced by ROL::PD_HMCR2< Real >::computeDual(), ROL::PD_HMCR2< Real >::getGradient(), ROL::PD_MeanSemiDeviation< Real >::getGradient(), ROL::PD_HMCR2< Real >::getHessVec(), ROL::PD_MeanSemiDeviation< Real >::getHessVec(), ROL::PD_HMCR2< Real >::getValue(), ROL::PD_MeanSemiDeviation< Real >::getValue(), ROL::PD_BPOE< Real >::updateGradient(), ROL::PD_CVaR< Real >::updateGradient(), ROL::PD_HMCR2< Real >::updateGradient(), ROL::PD_MeanSemiDeviationFromTarget< Real >::updateGradient(), ROL::PD_BPOE< Real >::updateHessVec(), ROL::PD_CVaR< Real >::updateHessVec(), ROL::PD_HMCR2< Real >::updateHessVec(), ROL::PD_MeanSemiDeviationFromTarget< Real >::updateHessVec(), ROL::PD_BPOE< Real >::updateValue(), ROL::PD_CVaR< Real >::updateValue(), ROL::PD_HMCR2< Real >::updateValue(), and ROL::PD_MeanSemiDeviationFromTarget< Real >::updateValue().
ppf()
template<class Real > Real ROL::PD_RandVarFunctional< Real >::ppf (const Real x, const Real t, const Real r, const int deriv = 0) const inline protected
Definition at line 50 of file ROL_PD_RandVarFunctional.hpp.
References zero.
Referenced by ROL::PD_MeanSemiDeviation< Real >::getGradient(), ROL::PD_MeanSemiDeviation< Real >::getHessVec(), ROL::PD_MeanSemiDeviation< Real >::getValue(), ROL::PD_BPOE< Real >::updateGradient(), ROL::PD_CVaR< Real >::updateGradient(), ROL::PD_MeanSemiDeviationFromTarget< Real >::updateGradient(), ROL::PD_BPOE< Real >::updateHessVec(), ROL::PD_CVaR< Real >::updateHessVec(), ROL::PD_MeanSemiDeviationFromTarget< Real >::updateHessVec(), ROL::PD_BPOE< Real >::updateValue(), ROL::PD_CVaR< Real >::updateValue(), and ROL::PD_MeanSemiDeviationFromTarget< Real >::updateValue().
setData()
template<class Real > void ROL::PD_RandVarFunctional< Real >::setData (SampleGenerator< Real > & sampler, const Real pen, const Real lam = 0.0) inline
Definition at line 75 of file ROL_PD_RandVarFunctional.hpp.
References ROL::SampleGenerator< Real >::getMyPoint(), ROL::PD_RandVarFunctional< Real >::multipliers_, ROL::SampleGenerator< Real >::numMySamples(), ROL::PD_RandVarFunctional< Real >::pen_, ROL::PD_RandVarFunctional< Real >::setData_, and ROL::SampleGenerator< Real >::start().
computeDual()
template<class Real > virtual Real ROL::PD_RandVarFunctional< Real >::computeDual (SampleGenerator< Real > & sampler) inline virtual
Reimplemented in ROL::PD_HMCR2< Real >.
Definition at line 85 of file ROL_PD_RandVarFunctional.hpp.
References ROL::SampleGenerator< Real >::getMyPoint(), ROL::SampleGenerator< Real >::getMyWeight(), ROL::PD_RandVarFunctional< Real >::multipliers_, ROL::PD_RandVarFunctional< Real >::multipliers_new_, ROL::SampleGenerator< Real >::numMySamples(), ROL::PD_RandVarFunctional< Real >::pen_, ROL::SampleGenerator< Real >::start(), ROL::SampleGenerator< Real >::sumAll(), ROL::PD_RandVarFunctional< Real >::update_, ROL::PD_RandVarFunctional< Real >::values_, and zero.
updateDual()
template<class Real > void ROL::PD_RandVarFunctional< Real >::updateDual (SampleGenerator< Real > & sampler) inline
Definition at line 106 of file ROL_PD_RandVarFunctional.hpp.
References ROL::SampleGenerator< Real >::getMyPoint(), ROL::PD_RandVarFunctional< Real >::multipliers_, ROL::PD_RandVarFunctional< Real >::multipliers_new_, ROL::SampleGenerator< Real >::numMySamples(), and ROL::SampleGenerator< Real >::start().
updatePenalty()
template<class Real > void ROL::PD_RandVarFunctional< Real >::updatePenalty (const Real pen) inline
Definition at line 114 of file ROL_PD_RandVarFunctional.hpp.
References ROL::PD_RandVarFunctional< Real >::pen_.
setStorage()
template<class Real > virtual void ROL::PD_RandVarFunctional< Real >::setStorage (const Ptr< ScalarController< Real > > & value_storage, const Ptr< VectorController< Real > > & gradient_storage) inline virtual
Reimplemented from ROL::RandVarFunctional< Real >.
Reimplemented in ROL::PD_BPOE< Real >, ROL::PD_CVaR< Real >, ROL::PD_HMCR2< Real >, ROL::PD_MeanSemiDeviation< Real >, and ROL::PD_MeanSemiDeviationFromTarget< Real >.
Definition at line 118 of file ROL_PD_RandVarFunctional.hpp.
References ROL::RandVarFunctional< Real >::setStorage().
Referenced by ROL::PD_BPOE< Real >::setStorage(), ROL::PD_CVaR< Real >::setStorage(), ROL::PD_HMCR2< Real >::setStorage(), ROL::PD_MeanSemiDeviation< Real >::setStorage(), and ROL::PD_MeanSemiDeviationFromTarget< Real >::setStorage().
setHessVecStorage()
template<class Real > virtual void ROL::PD_RandVarFunctional< Real >::setHessVecStorage (const Ptr< ScalarController< Real > > & gradvec_storage, const Ptr< VectorController< Real > > & hessvec_storage) inline virtual
Reimplemented from ROL::RandVarFunctional< Real >.
Reimplemented in ROL::PD_BPOE< Real >, ROL::PD_CVaR< Real >, ROL::PD_HMCR2< Real >, ROL::PD_MeanSemiDeviation< Real >, and ROL::PD_MeanSemiDeviationFromTarget< Real >.
Definition at line 123 of file ROL_PD_RandVarFunctional.hpp.
References ROL::RandVarFunctional< Real >::setHessVecStorage().
Referenced by ROL::PD_BPOE< Real >::setHessVecStorage(), ROL::PD_CVaR< Real >::setHessVecStorage(), ROL::PD_HMCR2< Real >::setHessVecStorage(), ROL::PD_MeanSemiDeviation< Real >::setHessVecStorage(), and ROL::PD_MeanSemiDeviationFromTarget< Real >::setHessVecStorage().
initialize()
template<class Real > virtual void ROL::PD_RandVarFunctional< Real >::initialize (const Vector< Real > & x) inline virtual
Initialize temporary variables.
   @param[in]   x  is a vector used for initializing storage
Reimplemented from ROL::RandVarFunctional< Real >.
Reimplemented in ROL::PD_BPOE< Real >, ROL::PD_CVaR< Real >, ROL::PD_HMCR2< Real >, ROL::PD_MeanSemiDeviation< Real >, and ROL::PD_MeanSemiDeviationFromTarget< Real >.
Definition at line 128 of file ROL_PD_RandVarFunctional.hpp.
References ROL::RandVarFunctional< Real >::initialize().
Referenced by ROL::PD_BPOE< Real >::initialize(), ROL::PD_CVaR< Real >::initialize(), ROL::PD_HMCR2< Real >::initialize(), ROL::PD_MeanSemiDeviation< Real >::initialize(), and ROL::PD_MeanSemiDeviationFromTarget< Real >::initialize().
Member Data Documentation
pen_
template<class Real > Real ROL::PD_RandVarFunctional< Real >::pen_ private
Definition at line 21 of file ROL_PD_RandVarFunctional.hpp.
Referenced by ROL::PD_RandVarFunctional< Real >::computeDual(), ROL::PD_RandVarFunctional< Real >::getPenaltyParameter(), ROL::PD_RandVarFunctional< Real >::setData(), and ROL::PD_RandVarFunctional< Real >::updatePenalty().
update_
template<class Real > int ROL::PD_RandVarFunctional< Real >::update_ private
Definition at line 22 of file ROL_PD_RandVarFunctional.hpp.
Referenced by ROL::PD_RandVarFunctional< Real >::computeDual().
setData_
template<class Real > bool ROL::PD_RandVarFunctional< Real >::setData_ private
Definition at line 23 of file ROL_PD_RandVarFunctional.hpp.
Referenced by ROL::PD_RandVarFunctional< Real >::setData().
values_
template<class Real > Ptr<ScalarController<Real> > ROL::PD_RandVarFunctional< Real >::values_ private
Definition at line 25 of file ROL_PD_RandVarFunctional.hpp.
Referenced by ROL::PD_RandVarFunctional< Real >::computeDual(), ROL::PD_RandVarFunctional< Real >::PD_RandVarFunctional(), and ROL::PD_RandVarFunctional< Real >::setValue().
multipliers_
template<class Real > Ptr<ScalarController<Real> > ROL::PD_RandVarFunctional< Real >::multipliers_ private
Definition at line 26 of file ROL_PD_RandVarFunctional.hpp.
Referenced by ROL::PD_RandVarFunctional< Real >::computeDual(), ROL::PD_RandVarFunctional< Real >::getMultiplier(), ROL::PD_RandVarFunctional< Real >::PD_RandVarFunctional(), ROL::PD_RandVarFunctional< Real >::setData(), and ROL::PD_RandVarFunctional< Real >::updateDual().
multipliers_new_
template<class Real > Ptr<ScalarController<Real> > ROL::PD_RandVarFunctional< Real >::multipliers_new_ private
Definition at line 27 of file ROL_PD_RandVarFunctional.hpp.
Referenced by ROL::PD_RandVarFunctional< Real >::computeDual(), ROL::PD_RandVarFunctional< Real >::PD_RandVarFunctional(), ROL::PD_RandVarFunctional< Real >::setMultiplier(), and ROL::PD_RandVarFunctional< Real >::updateDual().
The documentation for this class was generated from the following file:
ROL_PD_RandVarFunctional.hpp