ROL: L2VectorDual< Real > Class Template Reference
L2VectorDual< Real > Class Template Reference
#include <test_04.hpp>
Public Member Functions
L2VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
Real dot (const ROL::Vector< Real > &x) const override
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const override
Clone to make a new (uninitialized) vector.
const ROL::Vector< Real > & dual () const override
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
L2VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
L2VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
L2VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
void set (const ROL::Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Real > > getVector () const
ROL::Ptr< std::vector< Real > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
L2VectorDual (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BurgersFEM< Real > > &fem)
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Attributes
ROL::Ptr< BurgersFEM< Real > > fem_
ROL::Ptr< L2VectorPrimal< Real > > dual_vec_
bool isDualInitialized_
ROL::Ptr< std::vector< Real > > vec_
ROL::Ptr< L2VectorPrimal< Real > > prim_vec_
bool isPrimalInitialized_
Detailed Description
template<class Real>
class L2VectorDual< Real >
Definition at line 534 of file example_08.hpp.
Constructor & Destructor Documentation
L2VectorDual() [1/5]
template<class Real > L2VectorDual< Real >::L2VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 546 of file test_04.hpp.
L2VectorDual() [2/5]
template<class Real > L2VectorDual< Real >::L2VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 587 of file example_04.hpp.
L2VectorDual() [3/5]
template<class Real > L2VectorDual< Real >::L2VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 591 of file example_06.hpp.
L2VectorDual() [4/5]
template<class Real > L2VectorDual< Real >::L2VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 595 of file example_07.hpp.
L2VectorDual() [5/5]
template<class Real > L2VectorDual< Real >::L2VectorDual (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BurgersFEM< Real > > & fem) inline
Definition at line 541 of file example_08.hpp.
Member Function Documentation
dot() [1/5]
template<class Real > Real L2VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline override virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 551 of file test_04.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::fem_, L2VectorDual< Real >::getVector(), and ROL::StdVector< Real, Element >::getVector().
Referenced by L2VectorDual< Real >::norm().
clone() [1/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::clone () const inline override virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 565 of file test_04.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::fem_, and ROL::StdVector< Real, Element >::getVector().
dual() [1/5]
template<class Real > const ROL::Vector< Real > & L2VectorDual< Real >::dual (void) const inline override virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 571 of file test_04.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::dual_vec_, L2VectorDual< Real >::fem_, ROL::StdVector< Real, Element >::getVector(), and L2VectorDual< Real >::isDualInitialized_.
set() [1/3]
template<class Real > void L2VectorDual< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 591 of file example_04.hpp.
References L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
plus() [1/3]
template<class Real > void L2VectorDual< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 597 of file example_04.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
scale() [1/3]
template<class Real > void L2VectorDual< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 606 of file example_04.hpp.
References L2VectorDual< Real >::dimension(), and L2VectorDual< Real >::vec_.
dot() [2/5]
template<class Real > Real L2VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 613 of file example_04.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::fem_, L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
norm() [1/3]
template<class Real > Real L2VectorDual< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 626 of file example_04.hpp.
References L2VectorDual< Real >::dot().
clone() [2/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 632 of file example_04.hpp.
References L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
getVector() [1/6]
template<class Real > ROL::Ptr< const std::vector< Real > > L2VectorDual< Real >::getVector () const inline
Definition at line 636 of file example_04.hpp.
References L2VectorDual< Real >::vec_.
Referenced by L2VectorPrimal< Real >::apply(), L2VectorDual< Real >::dot(), L2VectorDual< Real >::dot(), L2VectorDual< Real >::plus(), and L2VectorDual< Real >::set().
getVector() [2/6]
template<class Real > ROL::Ptr< std::vector< Real > > L2VectorDual< Real >::getVector () inline
Definition at line 640 of file example_04.hpp.
References L2VectorDual< Real >::vec_.
basis() [1/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 644 of file example_04.hpp.
References L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
dimension() [1/3]
template<class Real > int L2VectorDual< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 651 of file example_04.hpp.
References L2VectorDual< Real >::vec_.
Referenced by L2VectorDual< Real >::clone(), L2VectorDual< Real >::dot(), L2VectorDual< Real >::dot(), L2VectorDual< Real >::dual(), L2VectorDual< Real >::plus(), and L2VectorDual< Real >::scale().
dual() [2/5]
template<class Real > const ROL::Vector< Real > & L2VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 655 of file example_04.hpp.
References L2VectorDual< Real >::dual_vec_, L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
apply() [1/3]
template<class Real > Real L2VectorDual< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 663 of file example_04.hpp.
References L2VectorPrimal< Real >::getVector(), and L2VectorDual< Real >::vec_.
set() [2/3]
template<class Real > void L2VectorDual< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 595 of file example_06.hpp.
References L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
plus() [2/3]
template<class Real > void L2VectorDual< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 601 of file example_06.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
scale() [2/3]
template<class Real > void L2VectorDual< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 610 of file example_06.hpp.
References L2VectorDual< Real >::dimension(), and L2VectorDual< Real >::vec_.
dot() [3/5]
template<class Real > Real L2VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 617 of file example_06.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::fem_, L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
norm() [2/3]
template<class Real > Real L2VectorDual< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 630 of file example_06.hpp.
References L2VectorDual< Real >::dot().
clone() [3/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 636 of file example_06.hpp.
References L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
getVector() [3/6]
template<class Real > ROL::Ptr< const std::vector< Real > > L2VectorDual< Real >::getVector () const inline
Definition at line 640 of file example_06.hpp.
References L2VectorDual< Real >::vec_.
getVector() [4/6]
template<class Real > ROL::Ptr< std::vector< Real > > L2VectorDual< Real >::getVector () inline
Definition at line 644 of file example_06.hpp.
References L2VectorDual< Real >::vec_.
basis() [2/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 648 of file example_06.hpp.
References L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
dimension() [2/3]
template<class Real > int L2VectorDual< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 655 of file example_06.hpp.
References L2VectorDual< Real >::vec_.
dual() [3/5]
template<class Real > const ROL::Vector< Real > & L2VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 659 of file example_06.hpp.
References L2VectorDual< Real >::dual_vec_, L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
apply() [2/3]
template<class Real > Real L2VectorDual< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 667 of file example_06.hpp.
References L2VectorPrimal< Real >::getVector(), and L2VectorDual< Real >::vec_.
set() [3/3]
template<class Real > void L2VectorDual< Real >::set (const ROL::Vector< Real > & x) inline virtual
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
   @param[in]      x     is a vector.
   On return \f$\mathtt{*this} = x\f$.
   Uses #zero and #plus methods for the computation.
   Please overload if a more efficient implementation is needed.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 599 of file example_07.hpp.
References L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
plus() [3/3]
template<class Real > void L2VectorDual< Real >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 605 of file example_07.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
scale() [3/3]
template<class Real > void L2VectorDual< Real >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 614 of file example_07.hpp.
References L2VectorDual< Real >::dimension(), and L2VectorDual< Real >::vec_.
dot() [4/5]
template<class Real > Real L2VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 621 of file example_07.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::fem_, L2VectorDual< Real >::getVector(), and L2VectorDual< Real >::vec_.
norm() [3/3]
template<class Real > Real L2VectorDual< Real >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 634 of file example_07.hpp.
References L2VectorDual< Real >::dot().
clone() [4/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 640 of file example_07.hpp.
References L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
getVector() [5/6]
template<class Real > ROL::Ptr< const std::vector< Real > > L2VectorDual< Real >::getVector () const inline
Definition at line 644 of file example_07.hpp.
References L2VectorDual< Real >::vec_.
getVector() [6/6]
template<class Real > ROL::Ptr< std::vector< Real > > L2VectorDual< Real >::getVector () inline
Definition at line 648 of file example_07.hpp.
References L2VectorDual< Real >::vec_.
basis() [3/3]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 652 of file example_07.hpp.
References L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
dimension() [3/3]
template<class Real > int L2VectorDual< Real >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 659 of file example_07.hpp.
References L2VectorDual< Real >::vec_.
dual() [4/5]
template<class Real > const ROL::Vector< Real > & L2VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 663 of file example_07.hpp.
References L2VectorDual< Real >::dual_vec_, L2VectorDual< Real >::fem_, and L2VectorDual< Real >::vec_.
apply() [3/3]
template<class Real > Real L2VectorDual< Real >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 671 of file example_07.hpp.
References L2VectorPrimal< Real >::getVector(), and L2VectorDual< Real >::vec_.
dot() [5/5]
template<class Real > Real L2VectorDual< Real >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 546 of file example_08.hpp.
References L2VectorDual< Real >::dimension(), L2VectorDual< Real >::fem_, L2VectorDual< Real >::getVector(), and ROL::StdVector< Real, Element >::getVector().
clone() [5/5]
template<class Real > ROL::Ptr< ROL::Vector< Real > > L2VectorDual< Real >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::StdVector< Real, Element >.
Definition at line 560 of file example_08.hpp.
References L2VectorDual< Real >::fem_.
dual() [5/5]
template<class Real > const ROL::Vector< Real > & L2VectorDual< Real >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 565 of file example_08.hpp.
References ROL::StdVector< Real, Element >::dimension(), L2VectorDual< Real >::fem_, L2VectorDual< Real >::isPrimalInitialized_, and L2VectorDual< Real >::prim_vec_.
Member Data Documentation
fem_
template<class Real > ROL::Ptr< BurgersFEM< Real > > L2VectorDual< Real >::fem_ private
Definition at line 541 of file test_04.hpp.
Referenced by L2VectorDual< Real >::basis(), L2VectorDual< Real >::clone(), L2VectorDual< Real >::clone(), L2VectorDual< Real >::dot(), L2VectorDual< Real >::dot(), L2VectorDual< Real >::dual(), and L2VectorDual< Real >::dual().
dual_vec_
template<class Real > ROL::Ptr< L2VectorPrimal< Real > > L2VectorDual< Real >::dual_vec_ mutable private
Definition at line 542 of file test_04.hpp.
Referenced by L2VectorDual< Real >::dual(), and L2VectorDual< Real >::dual().
isDualInitialized_
template<class Real > bool L2VectorDual< Real >::isDualInitialized_ mutable private
Definition at line 543 of file test_04.hpp.
Referenced by L2VectorDual< Real >::dual().
vec_
template<class Real > ROL::Ptr< std::vector< Real > > L2VectorDual< Real >::vec_ private
Definition at line 581 of file example_04.hpp.
Referenced by L2VectorDual< Real >::apply(), L2VectorDual< Real >::basis(), L2VectorDual< Real >::clone(), L2VectorDual< Real >::dimension(), L2VectorDual< Real >::dot(), L2VectorDual< Real >::dual(), L2VectorDual< Real >::getVector(), L2VectorDual< Real >::getVector(), L2VectorDual< Real >::plus(), L2VectorDual< Real >::scale(), and L2VectorDual< Real >::set().
prim_vec_
template<class Real > ROL::Ptr<L2VectorPrimal<Real> > L2VectorDual< Real >::prim_vec_ mutable private
Definition at line 537 of file example_08.hpp.
Referenced by L2VectorDual< Real >::dual().
isPrimalInitialized_
template<class Real > bool L2VectorDual< Real >::isPrimalInitialized_ mutable private
Definition at line 538 of file example_08.hpp.
Referenced by L2VectorDual< Real >::dual().
The documentation for this class was generated from the following files:
test_04.hpp
example_04.hpp
example_06.hpp
example_07.hpp
example_08.hpp