ROL: ROL::BoundFletcher< Real >::AugSystemPrecond Class Reference
ROL::BoundFletcher< Real >::AugSystemPrecond Class Reference
Public Member Functions
AugSystemPrecond (const Ptr< Constraint< Real > > con, const Ptr< const Vector< Real > > x)
void apply (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply linear operator.
void applyInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply inverse of linear operator.
Public Member Functions inherited from ROL::LinearOperator< Real >
virtual ~LinearOperator ()
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update linear operator.
virtual void applyAdjoint (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of linear operator.
virtual void applyAdjointInverse (Vector< Real > &Hv, const Vector< Real > &v, Real &tol) const
Apply adjoint of the inverse linear operator.
Private Attributes
const Ptr< Constraint< Real > > con_
const Ptr< const Vector< Real > > x_
Detailed Description
template<class Real>
class ROL::BoundFletcher< Real >::AugSystemPrecond
Definition at line 234 of file ROL_BoundFletcher.hpp.
Constructor & Destructor Documentation
AugSystemPrecond()
template<class Real > ROL::BoundFletcher< Real >::AugSystemPrecond::AugSystemPrecond (const Ptr< Constraint< Real > > con, const Ptr< const Vector< Real > > x) inline
Definition at line 239 of file ROL_BoundFletcher.hpp.
Member Function Documentation
apply()
template<class Real > void ROL::BoundFletcher< Real >::AugSystemPrecond::apply (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply linear operator.
This function applies the linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Implements ROL::LinearOperator< Real >.
Definition at line 242 of file ROL_BoundFletcher.hpp.
References ROL::Vector< Real >::dual(), and ROL::Vector< Real >::set().
applyInverse()
template<class Real > void ROL::BoundFletcher< Real >::AugSystemPrecond::applyInverse (Vector< Real > & Hv, const Vector< Real > & v, Real & tol) const inline virtual
Apply inverse of linear operator.
This function applies the inverse of linear operator to a vector.
Parameters
[out] Hv is the output vector.
[in] v is the input vector.
[in] tol is a tolerance for inexact linear operator application.
Reimplemented from ROL::LinearOperator< Real >.
Definition at line 245 of file ROL_BoundFletcher.hpp.
References ROL::BoundFletcher< Real >::AugSystemPrecond::con_, ROL::PartitionedVector< Real >::get(), ROL::PartitionedVector< Real >::set(), ROL::BoundFletcher< Real >::AugSystemPrecond::x_, and zero.
Member Data Documentation
con_
template<class Real > const Ptr<Constraint<Real> > ROL::BoundFletcher< Real >::AugSystemPrecond::con_ private
Definition at line 236 of file ROL_BoundFletcher.hpp.
Referenced by ROL::BoundFletcher< Real >::AugSystemPrecond::applyInverse().
x_
template<class Real > const Ptr<const Vector<Real> > ROL::BoundFletcher< Real >::AugSystemPrecond::x_ private
Definition at line 237 of file ROL_BoundFletcher.hpp.
Referenced by ROL::BoundFletcher< Real >::AugSystemPrecond::applyInverse().
The documentation for this class was generated from the following file:
ROL_BoundFletcher.hpp