ROL: ROL::LineSearch< Real > Class Template Reference
ROL::LineSearch< Real > Class Template Reference abstract
Provides interface for and implements line searches.
#include <ROL_LineSearch.hpp>
Public Member Functions
virtual ~LineSearch ()
LineSearch (ROL::ParameterList &parlist)
virtual void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con)
virtual void run (Real &alpha, Real &fval, int &ls_neval, int &ls_ngrad, const Real &gs, const Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con)=0
void setData (Real &eps, const Vector< Real > &g)
void setMaxitUpdate (Real &alpha, Real &fnew, const Real &fold)
Protected Member Functions
virtual bool status (const ELineSearch type, int &ls_neval, int &ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
virtual Real getInitialAlpha (int &ls_neval, int &ls_ngrad, const Real fval, const Real gs, const Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con)
void setNextInitialAlpha (Real alpha)
void updateIterate (Vector< Real > &xnew, const Vector< Real > &x, const Vector< Real > &s, Real alpha, BoundConstraint< Real > &con)
bool useLocalMinimizer ()
bool takeNoStep ()
Private Attributes
ECurvatureCondition econd_
EDescent edesc_
bool useralpha_
bool usePrevAlpha_
Real alpha0_
Real alpha0bnd_
int maxit_
Real c1_
Real c2_
Real c3_
Real eps_
Real fmin_
Real alphaMin_
bool acceptMin_
bool itcond_
ROL::Ptr< Vector< Real > > xtst_
ROL::Ptr< Vector< Real > > d_
ROL::Ptr< Vector< Real > > g_
ROL::Ptr< Vector< Real > > grad_
Detailed Description
template<class Real>
class ROL::LineSearch< Real >
Provides interface for and implements line searches.
Definition at line 28 of file ROL_LineSearch.hpp.
Constructor & Destructor Documentation
~LineSearch()
template<class Real > virtual ROL::LineSearch< Real >::~LineSearch () inline virtual
Definition at line 57 of file ROL_LineSearch.hpp.
LineSearch()
template<class Real > ROL::LineSearch< Real >::LineSearch (ROL::ParameterList & parlist) inline
Definition at line 60 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::acceptMin_, ROL::LineSearch< Real >::alpha0_, ROL::LineSearch< Real >::alpha0bnd_, ROL::LineSearch< Real >::alphaMin_, ROL::LineSearch< Real >::c1_, ROL::LineSearch< Real >::c2_, ROL::LineSearch< Real >::c3_, ROL::DESCENT_NONLINEARCG, ROL::LineSearch< Real >::econd_, ROL::LineSearch< Real >::edesc_, ROL::LineSearch< Real >::fmin_, ROL::LineSearch< Real >::itcond_, ROL::LineSearch< Real >::maxit_, ROL::StringToECurvatureCondition(), ROL::StringToEDescent(), ROL::LineSearch< Real >::usePrevAlpha_, ROL::LineSearch< Real >::useralpha_, and zero.
Member Function Documentation
initialize()
template<class Real > virtual void ROL::LineSearch< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & con) inline virtual
Reimplemented in ROL::IterationScaling< Real >, ROL::BackTracking< Real >, ROL::Bisection< Real >, ROL::Brents< Real >, ROL::CubicInterp< Real >, ROL::GoldenSection< Real >, ROL::PathBasedTargetLevel< Real >, and ROL::ScalarMinimizationLineSearch< Real >.
Definition at line 97 of file ROL_LineSearch.hpp.
References ROL::Vector< Real >::clone(), ROL::LineSearch< Real >::d_, ROL::LineSearch< Real >::g_, ROL::LineSearch< Real >::grad_, and ROL::LineSearch< Real >::xtst_.
Referenced by ROL::IterationScaling< Real >::initialize(), ROL::BackTracking< Real >::initialize(), ROL::Bisection< Real >::initialize(), ROL::Brents< Real >::initialize(), ROL::CubicInterp< Real >::initialize(), ROL::GoldenSection< Real >::initialize(), ROL::PathBasedTargetLevel< Real >::initialize(), and ROL::ScalarMinimizationLineSearch< Real >::initialize().
run()
template<class Real > virtual void ROL::LineSearch< Real >::run (Real & alpha, Real & fval, int & ls_neval, int & ls_ngrad, const Real & gs, const Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con) pure virtual
Implemented in ROL::BackTracking< Real >, ROL::Bisection< Real >, ROL::Brents< Real >, ROL::CubicInterp< Real >, ROL::GoldenSection< Real >, ROL::IterationScaling< Real >, ROL::PathBasedTargetLevel< Real >, and ROL::ScalarMinimizationLineSearch< Real >.
setData()
template<class Real > void ROL::LineSearch< Real >::setData (Real & eps, const Vector< Real > & g) inline
Definition at line 110 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::eps_, and ROL::LineSearch< Real >::grad_.
setMaxitUpdate()
template<class Real > void ROL::LineSearch< Real >::setMaxitUpdate (Real & alpha, Real & fnew, const Real & fold) inline
Definition at line 117 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::acceptMin_, ROL::LineSearch< Real >::alphaMin_, ROL::LineSearch< Real >::fmin_, ROL::LineSearch< Real >::itcond_, and ROL::LineSearch< Real >::setNextInitialAlpha().
status()
template<class Real > virtual bool ROL::LineSearch< Real >::status (const ELineSearch< Real > type, int & ls_neval, int & ls_ngrad, const Real alpha, const Real fold, const Real sgold, const Real fnew, const Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & con) inline protected virtual
Definition at line 133 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::alphaMin_, ROL::LineSearch< Real >::c1_, ROL::LineSearch< Real >::c2_, ROL::LineSearch< Real >::c3_, ROL::CURVATURECONDITION_APPROXIMATEWOLFE, ROL::CURVATURECONDITION_GENERALIZEDWOLFE, ROL::CURVATURECONDITION_GOLDSTEIN, ROL::CURVATURECONDITION_NULL, ROL::CURVATURECONDITION_STRONGWOLFE, ROL::CURVATURECONDITION_WOLFE, ROL::LineSearch< Real >::d_, ROL::DESCENT_NONLINEARCG, ROL::DESCENT_STEEPEST, ROL::Vector< Real >::dot(), ROL::LineSearch< Real >::econd_, ROL::LineSearch< Real >::edesc_, ROL::LineSearch< Real >::eps_, ROL::LineSearch< Real >::fmin_, ROL::LineSearch< Real >::g_, ROL::LineSearch< Real >::grad_, ROL::Objective< Real >::gradient(), ROL::BoundConstraint< Real >::isActivated(), ROL::LineSearch< Real >::itcond_, ROL::LINESEARCH_BACKTRACKING, ROL::LINESEARCH_CUBICINTERP, ROL::LineSearch< Real >::maxit_, ROL::BoundConstraint< Real >::pruneActive(), ROL::BoundConstraint< Real >::pruneInactive(), ROL::Objective< Real >::update(), ROL::LineSearch< Real >::updateIterate(), and ROL::LineSearch< Real >::xtst_.
getInitialAlpha()
template<class Real > virtual Real ROL::LineSearch< Real >::getInitialAlpha (int & ls_neval, int & ls_ngrad, const Real fval, const Real gs, const Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & con) inline protected virtual
Definition at line 236 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::alpha0_, ROL::LineSearch< Real >::alpha0bnd_, ROL::LineSearch< Real >::d_, ROL::DESCENT_NONLINEARCG, ROL::DESCENT_STEEPEST, ROL::LineSearch< Real >::edesc_, ROL::Objective< Real >::update(), ROL::LineSearch< Real >::updateIterate(), ROL::LineSearch< Real >::usePrevAlpha_, ROL::LineSearch< Real >::useralpha_, and ROL::Objective< Real >::value().
Referenced by ROL::BackTracking< Real >::run(), ROL::Bisection< Real >::run(), ROL::Brents< Real >::run(), ROL::CubicInterp< Real >::run(), ROL::GoldenSection< Real >::run(), ROL::IterationScaling< Real >::run(), and ROL::ScalarMinimizationLineSearch< Real >::run().
setNextInitialAlpha()
template<class Real > void ROL::LineSearch< Real >::setNextInitialAlpha (Real alpha) inline protected
Definition at line 263 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::alpha0_, and ROL::LineSearch< Real >::usePrevAlpha_.
Referenced by ROL::ScalarMinimizationLineSearch< Real >::run(), and ROL::LineSearch< Real >::setMaxitUpdate().
updateIterate()
template<class Real > void ROL::LineSearch< Real >::updateIterate (Vector< Real > & xnew, const Vector< Real > & x, const Vector< Real > & s, Real alpha, BoundConstraint< Real > & con) inline protected
Definition at line 269 of file ROL_LineSearch.hpp.
References ROL::Vector< Real >::axpy(), ROL::BoundConstraint< Real >::isActivated(), ROL::BoundConstraint< Real >::project(), and ROL::Vector< Real >::set().
Referenced by ROL::LineSearch< Real >::getInitialAlpha(), ROL::BackTracking< Real >::run(), ROL::Bisection< Real >::run(), ROL::CubicInterp< Real >::run(), ROL::GoldenSection< Real >::run(), ROL::IterationScaling< Real >::run(), ROL::PathBasedTargetLevel< Real >::run(), and ROL::LineSearch< Real >::status().
useLocalMinimizer()
template<class Real > bool ROL::LineSearch< Real >::useLocalMinimizer () inline protected
Definition at line 281 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::acceptMin_, and ROL::LineSearch< Real >::itcond_.
takeNoStep()
template<class Real > bool ROL::LineSearch< Real >::takeNoStep () inline protected
Definition at line 285 of file ROL_LineSearch.hpp.
References ROL::LineSearch< Real >::acceptMin_, and ROL::LineSearch< Real >::itcond_.
Member Data Documentation
econd_
template<class Real > ECurvatureCondition ROL::LineSearch< Real >::econd_ private
Definition at line 31 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::status().
edesc_
template<class Real > EDescent ROL::LineSearch< Real >::edesc_ private
Definition at line 32 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::getInitialAlpha(), ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::status().
useralpha_
template<class Real > bool ROL::LineSearch< Real >::useralpha_ private
Definition at line 34 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::getInitialAlpha(), and ROL::LineSearch< Real >::LineSearch().
usePrevAlpha_
template<class Real > bool ROL::LineSearch< Real >::usePrevAlpha_ private
Definition at line 35 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::getInitialAlpha(), ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::setNextInitialAlpha().
alpha0_
template<class Real > Real ROL::LineSearch< Real >::alpha0_ private
Definition at line 36 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::getInitialAlpha(), ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::setNextInitialAlpha().
alpha0bnd_
template<class Real > Real ROL::LineSearch< Real >::alpha0bnd_ private
Definition at line 37 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::getInitialAlpha(), and ROL::LineSearch< Real >::LineSearch().
maxit_
template<class Real > int ROL::LineSearch< Real >::maxit_ private
Definition at line 38 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::status().
c1_
template<class Real > Real ROL::LineSearch< Real >::c1_ private
Definition at line 39 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::status().
c2_
template<class Real > Real ROL::LineSearch< Real >::c2_ private
Definition at line 40 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::status().
c3_
template<class Real > Real ROL::LineSearch< Real >::c3_ private
Definition at line 41 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), and ROL::LineSearch< Real >::status().
eps_
template<class Real > Real ROL::LineSearch< Real >::eps_ private
Definition at line 42 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::setData(), and ROL::LineSearch< Real >::status().
fmin_
template<class Real > Real ROL::LineSearch< Real >::fmin_ private
Definition at line 43 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), ROL::LineSearch< Real >::setMaxitUpdate(), and ROL::LineSearch< Real >::status().
alphaMin_
template<class Real > Real ROL::LineSearch< Real >::alphaMin_ private
Definition at line 44 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), ROL::LineSearch< Real >::setMaxitUpdate(), and ROL::LineSearch< Real >::status().
acceptMin_
template<class Real > bool ROL::LineSearch< Real >::acceptMin_ private
Definition at line 45 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), ROL::LineSearch< Real >::setMaxitUpdate(), ROL::LineSearch< Real >::takeNoStep(), and ROL::LineSearch< Real >::useLocalMinimizer().
itcond_
template<class Real > bool ROL::LineSearch< Real >::itcond_ private
Definition at line 46 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::LineSearch(), ROL::LineSearch< Real >::setMaxitUpdate(), ROL::LineSearch< Real >::status(), ROL::LineSearch< Real >::takeNoStep(), and ROL::LineSearch< Real >::useLocalMinimizer().
xtst_
template<class Real > ROL::Ptr<Vector<Real> > ROL::LineSearch< Real >::xtst_ private
Definition at line 48 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::initialize(), and ROL::LineSearch< Real >::status().
d_
template<class Real > ROL::Ptr<Vector<Real> > ROL::LineSearch< Real >::d_ private
Definition at line 49 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::getInitialAlpha(), ROL::LineSearch< Real >::initialize(), and ROL::LineSearch< Real >::status().
g_
template<class Real > ROL::Ptr<Vector<Real> > ROL::LineSearch< Real >::g_ private
Definition at line 50 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::initialize(), and ROL::LineSearch< Real >::status().
grad_
template<class Real > ROL::Ptr<Vector<Real> > ROL::LineSearch< Real >::grad_ private
Definition at line 51 of file ROL_LineSearch.hpp.
Referenced by ROL::LineSearch< Real >::initialize(), ROL::LineSearch< Real >::setData(), and ROL::LineSearch< Real >::status().
The documentation for this class was generated from the following file:
ROL_LineSearch.hpp