ROL: ROL::TypeB::Algorithm< Real > Class Template Reference
ROL::TypeB::Algorithm< Real > Class Template Reference abstract
Provides an interface to run bound constrained optimization algorithms.
#include <ROL_TypeB_Algorithm.hpp>
Public Member Functions
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)=0
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeHeader (std::ostream &os) const
Print iterate header.
virtual void writeName (std::ostream &os) const
Print step name.
virtual void writeOutput (std::ostream &os, const bool write_header=false) const
Print iterate status.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Protected Member Functions
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::Algorithm< Real >
Provides an interface to run bound constrained optimization algorithms.
Definition at line 50 of file ROL_TypeB_Algorithm.hpp.
Constructor & Destructor Documentation
~Algorithm()
template<typename Real > virtual ROL::TypeB::Algorithm< Real >::~Algorithm () inline virtual
Definition at line 63 of file ROL_TypeB_Algorithm.hpp.
Algorithm()
template<typename Real > ROL::TypeB::Algorithm< Real >::Algorithm ()
Constructor, given a step and a status test.
Definition at line 20 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::TypeB::Algorithm< Real >::status_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::Algorithm< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g) protected
Definition at line 29 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Vector< Real >::clone().
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::initialize(), ROL::TypeB::MoreauYosidaAlgorithm< Real >::initialize(), ROL::TypeB::ColemanLiAlgorithm< Real >::initialize(), ROL::TypeB::GradientAlgorithm< Real >::initialize(), ROL::TypeB::KelleySachsAlgorithm< Real >::initialize(), ROL::TypeB::LinMoreAlgorithm< Real >::initialize(), ROL::TypeB::LSecantBAlgorithm< Real >::initialize(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::initialize(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::initialize(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::initialize(), ROL::TypeB::SpectralGradientAlgorithm< Real >::initialize(), and ROL::TypeB::TrustRegionSPGAlgorithm< Real >::initialize().
optimalityCriterion()
template<typename Real > Real ROL::TypeB::Algorithm< Real >::optimalityCriterion (const Vector< Real > & x, const Vector< Real > & g, Vector< Real > & primal, std::ostream & outStream = std::cout) const protected
Definition at line 51 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::Vector< Real >::dual(), ROL::Vector< Real >::norm(), and ROL::Vector< Real >::set().
Referenced by ROL::TypeB::LinMoreAlgorithm< Real >::computeGradient(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::computeGradient(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), and ROL::TypeB::LSecantBAlgorithm< Real >::run().
setStatusTest()
template<typename Real > void ROL::TypeB::Algorithm< Real >::setStatusTest (const Ptr< StatusTest< Real > > & status, const bool combineStatus = false)
Definition at line 64 of file ROL_TypeB_Algorithm_Def.hpp.
run() [1/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Problem< Real > & problem, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
Reimplemented in ROL::TypeB::KelleySachsAlgorithm< Real >, and ROL::TypeB::NewtonKrylovAlgorithm< Real >.
Definition at line 73 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Problem< Real >::finalizeIteration(), ROL::Problem< Real >::getBoundConstraint(), ROL::Problem< Real >::getDualOptimizationVector(), ROL::Problem< Real >::getObjective(), ROL::Problem< Real >::getPolyhedralProjection(), ROL::Problem< Real >::getPrimalOptimizationVector(), ROL::Problem< Real >::getProblemType(), and ROL::TYPE_B.
Referenced by ROL::TypeB::KelleySachsAlgorithm< Real >::run(), and ROL::TypeB::NewtonKrylovAlgorithm< Real >::run().
run() [2/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
Definition at line 90 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Vector< Real >::dual().
run() [3/9]
template<typename Real > virtual void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) pure virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implemented in ROL::TypeB::ColemanLiAlgorithm< Real >, ROL::TypeB::GradientAlgorithm< Real >, ROL::TypeB::InteriorPointAlgorithm< Real >, ROL::TypeB::KelleySachsAlgorithm< Real >, ROL::TypeB::LinMoreAlgorithm< Real >, ROL::TypeB::LSecantBAlgorithm< Real >, ROL::TypeB::MoreauYosidaAlgorithm< Real >, ROL::TypeB::NewtonKrylovAlgorithm< Real >, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >, ROL::TypeB::QuasiNewtonAlgorithm< Real >, ROL::TypeB::SpectralGradientAlgorithm< Real >, and ROL::TypeB::TrustRegionSPGAlgorithm< Real >.
run() [4/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
Definition at line 98 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Vector< Real >::dual().
run() [5/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Reimplemented in ROL::TypeB::KelleySachsAlgorithm< Real >, and ROL::TypeB::NewtonKrylovAlgorithm< Real >.
Definition at line 108 of file ROL_TypeB_Algorithm_Def.hpp.
run() [6/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & linear_icon, Vector< Real > & linear_imul, BoundConstraint< Real > & linear_ibnd, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
Definition at line 122 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Vector< Real >::dual().
run() [7/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & linear_icon, Vector< Real > & linear_imul, BoundConstraint< Real > & linear_ibnd, const Vector< Real > & linear_ires, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Definition at line 133 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
run() [8/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, Constraint< Real > & linear_icon, Vector< Real > & linear_imul, BoundConstraint< Real > & linear_ibnd, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
Definition at line 166 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Vector< Real >::dual().
run() [9/9]
template<typename Real > void ROL::TypeB::Algorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, Constraint< Real > & linear_icon, Vector< Real > & linear_imul, BoundConstraint< Real > & linear_ibnd, const Vector< Real > & linear_ires, std::ostream & outStream = std::cout) virtual
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Definition at line 180 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::Problem< Real >::addBoundConstraint(), ROL::Problem< Real >::addLinearConstraint(), ROL::Vector< Real >::clone(), and ROL::Problem< Real >::finalize().
writeHeader()
template<typename Real > void ROL::TypeB::Algorithm< Real >::writeHeader (std::ostream & os) const virtual
Print iterate header.
Reimplemented in ROL::TypeB::ColemanLiAlgorithm< Real >, ROL::TypeB::GradientAlgorithm< Real >, ROL::TypeB::InteriorPointAlgorithm< Real >, ROL::TypeB::KelleySachsAlgorithm< Real >, ROL::TypeB::LinMoreAlgorithm< Real >, ROL::TypeB::LSecantBAlgorithm< Real >, ROL::TypeB::MoreauYosidaAlgorithm< Real >, ROL::TypeB::NewtonKrylovAlgorithm< Real >, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >, ROL::TypeB::QuasiNewtonAlgorithm< Real >, ROL::TypeB::SpectralGradientAlgorithm< Real >, and ROL::TypeB::TrustRegionSPGAlgorithm< Real >.
Definition at line 226 of file ROL_TypeB_Algorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeB::Algorithm< Real >::writeName (std::ostream & os) const virtual
Print step name.
Reimplemented in ROL::TypeB::ColemanLiAlgorithm< Real >, ROL::TypeB::GradientAlgorithm< Real >, ROL::TypeB::InteriorPointAlgorithm< Real >, ROL::TypeB::KelleySachsAlgorithm< Real >, ROL::TypeB::LinMoreAlgorithm< Real >, ROL::TypeB::LSecantBAlgorithm< Real >, ROL::TypeB::MoreauYosidaAlgorithm< Real >, ROL::TypeB::NewtonKrylovAlgorithm< Real >, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >, ROL::TypeB::QuasiNewtonAlgorithm< Real >, ROL::TypeB::SpectralGradientAlgorithm< Real >, and ROL::TypeB::TrustRegionSPGAlgorithm< Real >.
Definition at line 240 of file ROL_TypeB_Algorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::Algorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const virtual
Print iterate status.
Reimplemented in ROL::TypeB::ColemanLiAlgorithm< Real >, ROL::TypeB::GradientAlgorithm< Real >, ROL::TypeB::InteriorPointAlgorithm< Real >, ROL::TypeB::KelleySachsAlgorithm< Real >, ROL::TypeB::LinMoreAlgorithm< Real >, ROL::TypeB::LSecantBAlgorithm< Real >, ROL::TypeB::MoreauYosidaAlgorithm< Real >, ROL::TypeB::NewtonKrylovAlgorithm< Real >, ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >, ROL::TypeB::QuasiNewtonAlgorithm< Real >, ROL::TypeB::SpectralGradientAlgorithm< Real >, and ROL::TypeB::TrustRegionSPGAlgorithm< Real >.
Definition at line 245 of file ROL_TypeB_Algorithm_Def.hpp.
writeExitStatus()
template<typename Real > void ROL::TypeB::Algorithm< Real >::writeExitStatus (std::ostream & os) const virtual
Definition at line 270 of file ROL_TypeB_Algorithm_Def.hpp.
References ROL::EExitStatusToString().
Referenced by ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::GradientAlgorithm< Real >::run(), ROL::TypeB::InteriorPointAlgorithm< Real >::run(), ROL::TypeB::KelleySachsAlgorithm< Real >::run(), ROL::TypeB::LinMoreAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::TypeB::MoreauYosidaAlgorithm< Real >::run(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::run(), ROL::TypeB::SpectralGradientAlgorithm< Real >::run(), and ROL::TypeB::TrustRegionSPGAlgorithm< Real >::run().
getState()
template<typename Real > Ptr< const AlgorithmState< Real > > ROL::TypeB::Algorithm< Real >::getState () const
Definition at line 280 of file ROL_TypeB_Algorithm_Def.hpp.
reset()
template<typename Real > void ROL::TypeB::Algorithm< Real >::reset ()
Definition at line 285 of file ROL_TypeB_Algorithm_Def.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm(), and ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
Member Data Documentation
status_
template<typename Real > const Ptr<CombinedStatusTest<Real> > ROL::TypeB::Algorithm< Real >::status_ protected
Definition at line 52 of file ROL_TypeB_Algorithm.hpp.
Referenced by ROL::TypeB::Algorithm< Real >::Algorithm(), ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm(), ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm(), and ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm().
state_
template<typename Real > const Ptr<AlgorithmState<Real> > ROL::TypeB::Algorithm< Real >::state_ protected
Definition at line 53 of file ROL_TypeB_Algorithm.hpp.
Referenced by ROL::TypeB::InteriorPointAlgorithm< Real >::InteriorPointAlgorithm(), and ROL::TypeB::MoreauYosidaAlgorithm< Real >::MoreauYosidaAlgorithm().
proj_
template<typename Real > Ptr<PolyhedralProjection<Real> > ROL::TypeB::Algorithm< Real >::proj_ protected
Definition at line 54 of file ROL_TypeB_Algorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_Algorithm.hpp
ROL_TypeB_Algorithm_Def.hpp