ROL: ROL::CompositeStep< Real > Class Template Reference
ROL::CompositeStep< Real > Class Template Reference
Implements the computation of optimization steps with composite-step trust-region methods.
#include <ROL_CompositeStep.hpp>
Public Member Functions
virtual ~CompositeStep ()
CompositeStep (ROL::ParameterList &parlist)
void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step.
void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step.
void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, if successful.
void compute (Vector< Real > &s, const Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Compute step for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
void update (Vector< Real > &x, const Vector< Real > &s, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Update step, for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
std::string printHeader (void) const
Print iterate header.
std::string printName (void) const
Print step name.
std::string print (AlgorithmState< Real > &algo_state, bool pHeader=false) const
Print iterate status.
void computeLagrangeMultiplier (Vector< Real > &l, const Vector< Real > &x, const Vector< Real > &gf, Constraint< Real > &con)
Compute Lagrange multipliers by solving the least-squares problem minimizing the gradient of the Lagrangian, via the augmented system formulation.
void computeQuasinormalStep (Vector< Real > &n, const Vector< Real > &c, const Vector< Real > &x, Real delta, Constraint< Real > &con)
Compute quasi-normal step by minimizing the norm of the linearized constraint.
void solveTangentialSubproblem (Vector< Real > &t, Vector< Real > &tCP, Vector< Real > &Wg, const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &n, const Vector< Real > &l, Real delta, Objective< Real > &obj, Constraint< Real > &con)
Solve tangential subproblem.
void accept (Vector< Real > &s, Vector< Real > &n, Vector< Real > &t, Real f_new, Vector< Real > &c_new, Vector< Real > &gf_new, Vector< Real > &l_new, Vector< Real > &g_new, const Vector< Real > &x, const Vector< Real > &l, Real f, const Vector< Real > &gf, const Vector< Real > &c, const Vector< Real > &g, Vector< Real > &tCP, Vector< Real > &Wg, Objective< Real > &obj, Constraint< Real > &con, AlgorithmState< Real > &algo_state)
Check acceptance of subproblem solutions, adjust merit function penalty parameter, ensure global convergence.
Public Member Functions inherited from ROL::Step< Real >
virtual ~Step ()
Step (void)
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &con, AlgorithmState< Real > &algo_state)
Initialize step with bound constraint.
virtual void initialize (Vector< Real > &x, const Vector< Real > &g, Vector< Real > &l, const Vector< Real > &c, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Initialize step with equality constraint.
virtual void compute (Vector< Real > &s, const Vector< Real > &x, const Vector< Real > &l, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Compute step (equality constraints).
virtual void update (Vector< Real > &x, Vector< Real > &l, const Vector< Real > &s, Objective< Real > &obj, Constraint< Real > &con, BoundConstraint< Real > &bnd, AlgorithmState< Real > &algo_state)
Update step, if successful (equality constraints).
const ROL::Ptr< const StepState< Real > > getStepState (void) const
Get state for step object.
void reset (const Real searchSize=1.0)
Get state for step object.
Private Member Functions
template<typename T >
int sgn (T val)
void printInfoLS (const std::vector< Real > &res) const
Real setTolOSS (const Real intol) const
Private Attributes
ROL::Ptr< Vector< Real > > xvec_
ROL::Ptr< Vector< Real > > gvec_
ROL::Ptr< Vector< Real > > cvec_
ROL::Ptr< Vector< Real > > lvec_
int flagCG_
int flagAC_
int iterCG_
int maxiterCG_
int maxiterOSS_
Real tolCG_
Real tolOSS_
bool tolOSSfixed_
Real lmhtol_
Real qntol_
Real pgtol_
Real projtol_
Real tangtol_
Real tntmax_
Real zeta_
Real Delta_
Real penalty_
Real eta_
bool useConHess_
Real ared_
Real pred_
Real snorm_
Real nnorm_
Real tnorm_
bool infoQN_
bool infoLM_
bool infoTS_
bool infoAC_
bool infoLS_
bool infoALL_
int totalIterCG_
int totalProj_
int totalNegCurv_
int totalRef_
int totalCallLS_
int totalIterLS_
Additional Inherited Members
Protected Member Functions inherited from ROL::Step< Real >
ROL::Ptr< StepState< Real > > getState (void)
Detailed Description
template<class Real>
class ROL::CompositeStep< Real >
Implements the computation of optimization steps with composite-step trust-region methods.
Definition at line 29 of file ROL_CompositeStep.hpp.
Constructor & Destructor Documentation
~CompositeStep()
template<class Real > virtual ROL::CompositeStep< Real >::~CompositeStep () inline virtual
Definition at line 114 of file ROL_CompositeStep.hpp.
CompositeStep()
template<class Real > ROL::CompositeStep< Real >::CompositeStep (ROL::ParameterList & parlist) inline
Definition at line 116 of file ROL_CompositeStep.hpp.
References ROL::CompositeStep< Real >::Delta_, ROL::CompositeStep< Real >::eta_, ROL::CompositeStep< Real >::flagAC_, ROL::CompositeStep< Real >::flagCG_, ROL::CompositeStep< Real >::infoAC_, ROL::CompositeStep< Real >::infoALL_, ROL::CompositeStep< Real >::infoLM_, ROL::CompositeStep< Real >::infoLS_, ROL::CompositeStep< Real >::infoQN_, ROL::CompositeStep< Real >::infoTS_, ROL::CompositeStep< Real >::iterCG_, ROL::CompositeStep< Real >::lmhtol_, ROL::CompositeStep< Real >::maxiterCG_, ROL::CompositeStep< Real >::nnorm_, ROL::CompositeStep< Real >::penalty_, ROL::CompositeStep< Real >::pgtol_, ROL::CompositeStep< Real >::projtol_, ROL::CompositeStep< Real >::qntol_, ROL::CompositeStep< Real >::snorm_, ROL::CompositeStep< Real >::tangtol_, ROL::CompositeStep< Real >::tnorm_, ROL::CompositeStep< Real >::tntmax_, ROL::CompositeStep< Real >::tolCG_, ROL::CompositeStep< Real >::tolOSS_, ROL::CompositeStep< Real >::tolOSSfixed_, ROL::CompositeStep< Real >::totalCallLS_, ROL::CompositeStep< Real >::totalIterCG_, ROL::CompositeStep< Real >::totalIterLS_, ROL::CompositeStep< Real >::totalNegCurv_, ROL::CompositeStep< Real >::totalProj_, ROL::CompositeStep< Real >::totalRef_, ROL::CompositeStep< Real >::useConHess_, and ROL::CompositeStep< Real >::zeta_.
Member Function Documentation
sgn()
template<class Real > template<typename T > int ROL::CompositeStep< Real >::sgn (T val) inline private
Definition at line 87 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::solveTangentialSubproblem().
printInfoLS()
template<class Real > void ROL::CompositeStep< Real >::printInfoLS (const std::vector< Real > & res) const inline private
Definition at line 91 of file ROL_CompositeStep.hpp.
References ROL::CompositeStep< Real >::infoLS_.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
setTolOSS()
template<class Real > Real ROL::CompositeStep< Real >::setTolOSS (const Real intol) const inline private
Definition at line 105 of file ROL_CompositeStep.hpp.
References ROL::CompositeStep< Real >::tolOSS_, and ROL::CompositeStep< Real >::tolOSSfixed_.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
initialize()
template<class Real > void ROL::CompositeStep< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Vector< Real > & l, const Vector< Real > & c, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Initialize step.
Reimplemented from ROL::Step< Real >.
Definition at line 175 of file ROL_CompositeStep.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Vector< Real >::clone(), ROL::AlgorithmState< Real >::cnorm, ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::cvec_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::CompositeStep< Real >::gvec_, ROL::AlgorithmState< Real >::iter, ROL::CompositeStep< Real >::lvec_, ROL::AlgorithmState< Real >::ncval, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::Constraint< Real >::update(), ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), ROL::Constraint< Real >::value(), ROL::AlgorithmState< Real >::value, and ROL::CompositeStep< Real >::xvec_.
compute() [1/2]
template<class Real > void ROL::CompositeStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, const Vector< Real > & l, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step.
Reimplemented from ROL::Step< Real >.
Definition at line 218 of file ROL_CompositeStep.hpp.
References ROL::CompositeStep< Real >::accept(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::cvec_, ROL::CompositeStep< Real >::Delta_, ROL::Objective< Real >::gradient(), ROL::CompositeStep< Real >::gvec_, ROL::CompositeStep< Real >::iterCG_, ROL::CompositeStep< Real >::lvec_, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::CompositeStep< Real >::totalIterCG_, ROL::Objective< Real >::value(), ROL::Constraint< Real >::value(), ROL::CompositeStep< Real >::xvec_, and ROL::CompositeStep< Real >::zeta_.
update() [1/2]
template<class Real > void ROL::CompositeStep< Real >::update (Vector< Real > & x, Vector< Real > & l, const Vector< Real > & s, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, if successful.
Reimplemented from ROL::Step< Real >.
Definition at line 266 of file ROL_CompositeStep.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::CompositeStep< Real >::ared_, ROL::AlgorithmState< Real >::cnorm, ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::cvec_, ROL::CompositeStep< Real >::Delta_, ROL::CompositeStep< Real >::eta_, ROL::CompositeStep< Real >::flagAC_, ROL::Step< Real >::getState(), ROL::AlgorithmState< Real >::gnorm, ROL::Objective< Real >::gradient(), ROL::CompositeStep< Real >::gvec_, ROL::AlgorithmState< Real >::iter, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::CompositeStep< Real >::nnorm_, ROL::Vector< Real >::plus(), ROL::CompositeStep< Real >::pred_, ROL::AlgorithmState< Real >::snorm, ROL::CompositeStep< Real >::snorm_, ROL::CompositeStep< Real >::tnorm_, ROL::Constraint< Real >::update(), ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), ROL::Constraint< Real >::value(), ROL::AlgorithmState< Real >::value, and zero.
compute() [2/2]
template<class Real > void ROL::CompositeStep< Real >::compute (Vector< Real > & s, const Vector< Real > & x, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Compute step for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Reimplemented from ROL::Step< Real >.
Definition at line 338 of file ROL_CompositeStep.hpp.
update() [2/2]
template<class Real > void ROL::CompositeStep< Real >::update (Vector< Real > & x, const Vector< Real > & s, Objective< Real > & obj, BoundConstraint< Real > & con, AlgorithmState< Real > & algo_state) inline virtual
Update step, for bound constraints; here only to satisfy the interface requirements, does nothing, needs refactoring.
Reimplemented from ROL::Step< Real >.
Definition at line 345 of file ROL_CompositeStep.hpp.
printHeader()
template<class Real > std::string ROL::CompositeStep< Real >::printHeader (void) const inline virtual
Print iterate header.
Reimplemented from ROL::Step< Real >.
Definition at line 351 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::print().
printName()
template<class Real > std::string ROL::CompositeStep< Real >::printName (void) const inline virtual
Print step name.
Reimplemented from ROL::Step< Real >.
Definition at line 372 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::print().
print()
template<class Real > std::string ROL::CompositeStep< Real >::print (AlgorithmState< Real > & algo_state, bool pHeader = false) const inline virtual
Print iterate status.
Reimplemented from ROL::Step< Real >.
Definition at line 381 of file ROL_CompositeStep.hpp.
References ROL::AlgorithmState< Real >::cnorm, ROL::CompositeStep< Real >::Delta_, ROL::CompositeStep< Real >::flagAC_, ROL::CompositeStep< Real >::flagCG_, ROL::AlgorithmState< Real >::gnorm, ROL::AlgorithmState< Real >::iter, ROL::CompositeStep< Real >::iterCG_, ROL::AlgorithmState< Real >::nfval, ROL::AlgorithmState< Real >::ngrad, ROL::CompositeStep< Real >::nnorm_, ROL::CompositeStep< Real >::printHeader(), ROL::CompositeStep< Real >::printName(), ROL::AlgorithmState< Real >::snorm, ROL::CompositeStep< Real >::tnorm_, ROL::CompositeStep< Real >::totalCallLS_, ROL::CompositeStep< Real >::totalIterLS_, and ROL::AlgorithmState< Real >::value.
computeLagrangeMultiplier()
template<class Real > void ROL::CompositeStep< Real >::computeLagrangeMultiplier (Vector< Real > & l, const Vector< Real > & x, const Vector< Real > & gf, Constraint< Real > & con) inline
Compute Lagrange multipliers by solving the least-squares problem minimizing the gradient of the Lagrangian, via the augmented system formulation.
Parameters
[out] l is the updated Lagrange multiplier; a dual constraint-space vector
[in] x is the current iterate; an optimization-space vector
[in] gf is the gradient of the objective function; a dual optimization-space vector
[in] con is the equality constraint object
On return ... fill the blanks.
Definition at line 434 of file ROL_CompositeStep.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::CompositeStep< Real >::cvec_, ROL::CompositeStep< Real >::gvec_, ROL::CompositeStep< Real >::infoLM_, ROL::CompositeStep< Real >::lmhtol_, ROL::CompositeStep< Real >::lvec_, ROL::Vector< Real >::plus(), ROL::CompositeStep< Real >::printInfoLS(), ROL::CompositeStep< Real >::setTolOSS(), ROL::Constraint< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::totalCallLS_, ROL::CompositeStep< Real >::totalIterLS_, and ROL::CompositeStep< Real >::xvec_.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::initialize(), and ROL::CompositeStep< Real >::update().
computeQuasinormalStep()
template<class Real > void ROL::CompositeStep< Real >::computeQuasinormalStep (Vector< Real > & n, const Vector< Real > & c, const Vector< Real > & x, Real delta, Constraint< Real > & con) inline
Compute quasi-normal step by minimizing the norm of the linearized constraint.
Compute an approximate solution of the problem
\[ \begin{array}{rl} \min_{n} & \|c'(x_k)n + c(x_k)\|^2_{\mathcal{X}} \\ \mbox{subject to} & \|n\|_{\mathcal{X}} \le \delta \end{array} \]
The approximate solution is computed using Powell's dogleg method. The dogleg path is computed using the Cauchy point and a full Newton step. The path's intersection with the trust-region constraint gives the quasi-normal step.
Parameters
[out] n is the quasi-normal step; an optimization-space vector
[in] c is the value of equality constraints; a constraint-space vector
[in] x is the current iterate; an optimization-space vector
[in] delta is the trust-region radius for the quasi-normal step
[in] con is the equality constraint object
Definition at line 501 of file ROL_CompositeStep.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Constraint< Real >::applyJacobian(), ROL::Vector< Real >::axpy(), ROL::CompositeStep< Real >::cvec_, ROL::Vector< Real >::dual(), ROL::CompositeStep< Real >::gvec_, ROL::CompositeStep< Real >::infoQN_, ROL::CompositeStep< Real >::lvec_, ROL::CompositeStep< Real >::printInfoLS(), ROL::CompositeStep< Real >::qntol_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::CompositeStep< Real >::setTolOSS(), ROL::Constraint< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::totalCallLS_, ROL::CompositeStep< Real >::totalIterLS_, ROL::CompositeStep< Real >::xvec_, and zero.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::compute().
solveTangentialSubproblem()
template<class Real > void ROL::CompositeStep< Real >::solveTangentialSubproblem (Vector< Real > & t, Vector< Real > & tCP, Vector< Real > & Wg, const Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & n, const Vector< Real > & l, Real delta, Objective< Real > & obj, Constraint< Real > & con) inline
Solve tangential subproblem.
   @param[out]      t     is the solution of the tangential subproblem; an optimization-space vector
   @param[out]      tCP   is the Cauchy point for the tangential subproblem; an optimization-space vector
   @param[out]      Wg    is the dual of the projected gradient of the Lagrangian; an optimization-space vector
   @param[in]       x     is the current iterate; an optimization-space vector
   @param[in]       g     is the gradient of the Lagrangian; a dual optimization-space vector
   @param[in]       n     is the quasi-normal step; an optimization-space vector
   @param[in]       l     is the Lagrange multiplier; a dual constraint-space vector
   @param[in]       delta is the trust-region radius for the tangential subproblem
   @param[in]       con   is the equality constraint object
Definition at line 611 of file ROL_CompositeStep.hpp.
References ROL::Constraint< Real >::applyAdjointHessian(), ROL::Constraint< Real >::applyJacobian(), ROL::CompositeStep< Real >::cvec_, ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::CompositeStep< Real >::flagCG_, ROL::CompositeStep< Real >::gvec_, ROL::Objective< Real >::hessVec(), ROL::CompositeStep< Real >::infoTS_, ROL::CompositeStep< Real >::iterCG_, ROL::CompositeStep< Real >::lvec_, ROL::CompositeStep< Real >::maxiterCG_, ROL::Vector< Real >::norm(), ROL::CompositeStep< Real >::pgtol_, ROL::Vector< Real >::plus(), ROL::CompositeStep< Real >::printInfoLS(), ROL::CompositeStep< Real >::projtol_, ROL::Vector< Real >::set(), ROL::CompositeStep< Real >::setTolOSS(), ROL::CompositeStep< Real >::sgn(), ROL::Constraint< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::tolCG_, ROL::CompositeStep< Real >::totalCallLS_, ROL::CompositeStep< Real >::totalIterLS_, ROL::CompositeStep< Real >::useConHess_, ROL::CompositeStep< Real >::xvec_, zero, and ROL::Vector< Real >::zero().
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::compute().
accept()
template<class Real > void ROL::CompositeStep< Real >::accept (Vector< Real > & s, Vector< Real > & n, Vector< Real > & t, Real f_new, Vector< Real > & c_new, Vector< Real > & gf_new, Vector< Real > & l_new, Vector< Real > & g_new, const Vector< Real > & x, const Vector< Real > & l, Real f, const Vector< Real > & gf, const Vector< Real > & c, const Vector< Real > & g, Vector< Real > & tCP, Vector< Real > & Wg, Objective< Real > & obj, Constraint< Real > & con, AlgorithmState< Real > & algo_state) inline
Check acceptance of subproblem solutions, adjust merit function penalty parameter, ensure global convergence.
Definition at line 938 of file ROL_CompositeStep.hpp.
References ROL::Constraint< Real >::applyAdjointHessian(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Constraint< Real >::applyJacobian(), ROL::CompositeStep< Real >::ared_, ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::cvec_, ROL::CompositeStep< Real >::Delta_, ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::CompositeStep< Real >::eta_, ROL::CompositeStep< Real >::flagCG_, ROL::Objective< Real >::gradient(), ROL::CompositeStep< Real >::gvec_, ROL::Objective< Real >::hessVec(), ROL::CompositeStep< Real >::infoAC_, ROL::AlgorithmState< Real >::iter, ROL::CompositeStep< Real >::iterCG_, ROL::CompositeStep< Real >::lmhtol_, ROL::CompositeStep< Real >::lvec_, ROL::CompositeStep< Real >::nnorm_, ROL::Vector< Real >::norm(), ROL::CompositeStep< Real >::penalty_, ROL::CompositeStep< Real >::pgtol_, ROL::Vector< Real >::plus(), ROL::CompositeStep< Real >::pred_, ROL::CompositeStep< Real >::printInfoLS(), ROL::CompositeStep< Real >::projtol_, ROL::CompositeStep< Real >::qntol_, ROL::Vector< Real >::set(), ROL::CompositeStep< Real >::setTolOSS(), ROL::CompositeStep< Real >::snorm_, ROL::Constraint< Real >::solveAugmentedSystem(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::CompositeStep< Real >::tangtol_, ROL::CompositeStep< Real >::tnorm_, ROL::CompositeStep< Real >::tntmax_, ROL::CompositeStep< Real >::tolOSSfixed_, ROL::CompositeStep< Real >::totalCallLS_, ROL::CompositeStep< Real >::totalIterCG_, ROL::CompositeStep< Real >::totalIterLS_, ROL::CompositeStep< Real >::totalNegCurv_, ROL::CompositeStep< Real >::totalProj_, ROL::CompositeStep< Real >::totalRef_, ROL::Constraint< Real >::update(), ROL::Objective< Real >::update(), ROL::CompositeStep< Real >::useConHess_, ROL::Objective< Real >::value(), ROL::Constraint< Real >::value(), ROL::CompositeStep< Real >::xvec_, zero, and ROL::CompositeStep< Real >::zeta_.
Referenced by ROL::CompositeStep< Real >::compute().
Member Data Documentation
xvec_
template<class Real > ROL::Ptr<Vector<Real> > ROL::CompositeStep< Real >::xvec_ private
Definition at line 33 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::compute(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::initialize(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
gvec_
template<class Real > ROL::Ptr<Vector<Real> > ROL::CompositeStep< Real >::gvec_ private
Definition at line 34 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::compute(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::initialize(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), and ROL::CompositeStep< Real >::update().
cvec_
template<class Real > ROL::Ptr<Vector<Real> > ROL::CompositeStep< Real >::cvec_ private
Definition at line 35 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::compute(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::initialize(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), and ROL::CompositeStep< Real >::update().
lvec_
template<class Real > ROL::Ptr<Vector<Real> > ROL::CompositeStep< Real >::lvec_ private
Definition at line 36 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::compute(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::initialize(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
flagCG_
template<class Real > int ROL::CompositeStep< Real >::flagCG_ private
Definition at line 39 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
flagAC_
template<class Real > int ROL::CompositeStep< Real >::flagAC_ private
Definition at line 40 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::update().
iterCG_
template<class Real > int ROL::CompositeStep< Real >::iterCG_ private
Definition at line 41 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::compute(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
maxiterCG_
template<class Real > int ROL::CompositeStep< Real >::maxiterCG_ private
Definition at line 44 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
maxiterOSS_
template<class Real > int ROL::CompositeStep< Real >::maxiterOSS_ private
Definition at line 45 of file ROL_CompositeStep.hpp.
tolCG_
template<class Real > Real ROL::CompositeStep< Real >::tolCG_ private
Definition at line 46 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
tolOSS_
template<class Real > Real ROL::CompositeStep< Real >::tolOSS_ private
Definition at line 47 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::setTolOSS().
tolOSSfixed_
template<class Real > bool ROL::CompositeStep< Real >::tolOSSfixed_ private
Definition at line 48 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::setTolOSS().
lmhtol_
template<class Real > Real ROL::CompositeStep< Real >::lmhtol_ private
Definition at line 51 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::computeLagrangeMultiplier().
qntol_
template<class Real > Real ROL::CompositeStep< Real >::qntol_ private
Definition at line 52 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::computeQuasinormalStep().
pgtol_
template<class Real > Real ROL::CompositeStep< Real >::pgtol_ private
Definition at line 53 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
projtol_
template<class Real > Real ROL::CompositeStep< Real >::projtol_ private
Definition at line 54 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
tangtol_
template<class Real > Real ROL::CompositeStep< Real >::tangtol_ private
Definition at line 55 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::CompositeStep().
tntmax_
template<class Real > Real ROL::CompositeStep< Real >::tntmax_ private
Definition at line 56 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::CompositeStep().
zeta_
template<class Real > Real ROL::CompositeStep< Real >::zeta_ private
Definition at line 59 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::compute().
Delta_
template<class Real > Real ROL::CompositeStep< Real >::Delta_ private
Definition at line 60 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::compute(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::update().
penalty_
template<class Real > Real ROL::CompositeStep< Real >::penalty_ private
Definition at line 61 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::CompositeStep().
eta_
template<class Real > Real ROL::CompositeStep< Real >::eta_ private
Definition at line 62 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::update().
useConHess_
template<class Real > bool ROL::CompositeStep< Real >::useConHess_ private
Definition at line 63 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
ared_
template<class Real > Real ROL::CompositeStep< Real >::ared_ private
Definition at line 65 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::update().
pred_
template<class Real > Real ROL::CompositeStep< Real >::pred_ private
Definition at line 66 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::update().
snorm_
template<class Real > Real ROL::CompositeStep< Real >::snorm_ private
Definition at line 67 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::update().
nnorm_
template<class Real > Real ROL::CompositeStep< Real >::nnorm_ private
Definition at line 68 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::update().
tnorm_
template<class Real > Real ROL::CompositeStep< Real >::tnorm_ private
Definition at line 69 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::update().
infoQN_
template<class Real > bool ROL::CompositeStep< Real >::infoQN_ private
Definition at line 72 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::computeQuasinormalStep().
infoLM_
template<class Real > bool ROL::CompositeStep< Real >::infoLM_ private
Definition at line 73 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::computeLagrangeMultiplier().
infoTS_
template<class Real > bool ROL::CompositeStep< Real >::infoTS_ private
Definition at line 74 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
infoAC_
template<class Real > bool ROL::CompositeStep< Real >::infoAC_ private
Definition at line 75 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::CompositeStep().
infoLS_
template<class Real > bool ROL::CompositeStep< Real >::infoLS_ private
Definition at line 76 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::printInfoLS().
infoALL_
template<class Real > bool ROL::CompositeStep< Real >::infoALL_ private
Definition at line 77 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::CompositeStep().
totalIterCG_
template<class Real > int ROL::CompositeStep< Real >::totalIterCG_ private
Definition at line 80 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), and ROL::CompositeStep< Real >::compute().
totalProj_
template<class Real > int ROL::CompositeStep< Real >::totalProj_ private
Definition at line 81 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::CompositeStep().
totalNegCurv_
template<class Real > int ROL::CompositeStep< Real >::totalNegCurv_ private
Definition at line 82 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::CompositeStep().
totalRef_
template<class Real > int ROL::CompositeStep< Real >::totalRef_ private
Definition at line 83 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), and ROL::CompositeStep< Real >::CompositeStep().
totalCallLS_
template<class Real > int ROL::CompositeStep< Real >::totalCallLS_ private
Definition at line 84 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
totalIterLS_
template<class Real > int ROL::CompositeStep< Real >::totalIterLS_ private
Definition at line 85 of file ROL_CompositeStep.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::CompositeStep< Real >::CompositeStep(), ROL::CompositeStep< Real >::computeLagrangeMultiplier(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::CompositeStep< Real >::print(), and ROL::CompositeStep< Real >::solveTangentialSubproblem().
The documentation for this class was generated from the following file:
ROL_CompositeStep.hpp