ROL: ROL::TypeB::NewtonKrylovAlgorithm< Real > Class Template Reference
ROL::TypeB::NewtonKrylovAlgorithm< Real > Class Template Reference
Provides an interface to run the projected secant algorithm.
#include <ROL_TypeB_NewtonKrylovAlgorithm.hpp>
Classes
class HessianPNK
class PrecondPNK
Public Member Functions
NewtonKrylovAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
NewtonKrylovAlgorithm (ParameterList &list, const Ptr< Krylov< Real > > &krylov, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void run (Problem< Real > &problem, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout) override
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool write_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeB::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, const bool combineStatus=false)
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This is the primary Type-B with explicit linear constraints interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, Constraint< Real > &linear_icon, Vector< Real > &linear_imul, BoundConstraint< Real > &linear_ibnd, const Vector< Real > &linear_ires, std::ostream &outStream=std::cout)
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, std::ostream &outStream=std::cout)
void parseParameterList (ParameterList &list)
Private Attributes
Ptr< Secant< Real > > secant_
Secant object (used for quasi-Newton)
ESecant esec_
Secant type.
std::string secantName_
Secant name.
Ptr< Krylov< Real > > krylov_
Krylov solver object (used for inexact Newton)
EKrylov ekv_
Krylov type.
std::string krylovName_
Krylov name.
int iterKrylov_
Number of Krylov iterations (used for inexact Newton)
int flagKrylov_
Termination flag for Krylov method (used for inexact Newton)
bool useSecantHessVec_
Whether or not to use to a secant approximation as the Hessian.
bool useSecantPrecond_
Whether or not to use a secant approximation to precondition inexact Newton.
int maxit_
Maximum number of line search steps (default: 20)
Real alpha0_
Initial line search step size (default: 1.0)
Real rhodec_
Backtracking rate (default: 0.5)
Real c1_
Sufficient Decrease Parameter (default: 1e-4)
bool useralpha_
Flag to use user-defined initial step size (default: false)
bool usePrevAlpha_
Flag to use previous step size as next initial step size (default: false)
int ls_nfval_
int verbosity_
bool writeHeader_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeB::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g)
Real optimalityCriterion (const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &primal, std::ostream &outStream=std::cout) const
Protected Attributes inherited from ROL::TypeB::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeB::NewtonKrylovAlgorithm< Real >
Provides an interface to run the projected secant algorithm.
Definition at line 25 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Constructor & Destructor Documentation
NewtonKrylovAlgorithm() [1/2]
template<typename Real > ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 17 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
References ROL::TypeB::NewtonKrylovAlgorithm< Real >::ekv_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::esec_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::krylov_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::krylovName_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::parseParameterList(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::secant_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::secantName_, ROL::StringToEKrylov(), and ROL::StringToESecant().
NewtonKrylovAlgorithm() [2/2]
template<typename Real > ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm (ParameterList & list, const Ptr< Krylov< Real > > & krylov, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 38 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
References ROL::TypeB::NewtonKrylovAlgorithm< Real >::esec_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::krylovName_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::parseParameterList(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::secant_, ROL::TypeB::NewtonKrylovAlgorithm< Real >::secantName_, and ROL::StringToESecant().
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) private
Definition at line 81 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
References ROL::Objective< Real >::gradient(), ROL::Initial, ROL::TypeB::Algorithm< Real >::initialize(), ROL::Objective< Real >::update(), and ROL::Objective< Real >::value().
parseParameterList()
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::parseParameterList (ParameterList & list) private
Definition at line 59 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), and ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm().
run() [1/3]
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Implements ROL::TypeB::Algorithm< Real >.
Definition at line 110 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
References ROL::Accept, ROL::Vector< Real >::axpy(), ROL::Vector< Real >::clone(), ROL::Objective< Real >::gradient(), ROL::Vector< Real >::set(), ROL::Trial, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and ROL::TypeB::Algorithm< Real >::writeExitStatus().
run() [2/3]
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::run (Problem< Real > & problem, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems (Type-B). This is the primary Type-B interface.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 213 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
References ROL::Problem< Real >::getPolyhedralProjection(), and ROL::TypeB::Algorithm< Real >::run().
run() [3/3]
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & linear_econ, Vector< Real > & linear_emul, const Vector< Real > & linear_eres, std::ostream & outStream = std::cout) override virtual
Run algorithm on bound constrained problems with explicit linear constraints (Type-B). This general interface supports the use of dual optimization vector spaces, where the user does not define the dual() method.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 224 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
writeHeader()
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 236 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
References ROL::CG_FLAG_SUCCESS, ROL::CG_FLAG_UNDEFINED, ROL::ECGFlagToString(), and ROL::NumberToString().
writeName()
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 280 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeB::NewtonKrylovAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeB::Algorithm< Real >.
Definition at line 293 of file ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > Ptr<Secant<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::secant_ private
Secant object (used for quasi-Newton)
Definition at line 27 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), and ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm().
esec_
template<typename Real > ESecant ROL::TypeB::NewtonKrylovAlgorithm< Real >::esec_ private
Secant type.
Definition at line 28 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), and ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm().
secantName_
template<typename Real > std::string ROL::TypeB::NewtonKrylovAlgorithm< Real >::secantName_ private
Secant name.
Definition at line 29 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), and ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm().
krylov_
template<typename Real > Ptr<Krylov<Real> > ROL::TypeB::NewtonKrylovAlgorithm< Real >::krylov_ private
Krylov solver object (used for inexact Newton)
Definition at line 31 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm().
ekv_
template<typename Real > EKrylov ROL::TypeB::NewtonKrylovAlgorithm< Real >::ekv_ private
Krylov type.
Definition at line 32 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm().
krylovName_
template<typename Real > std::string ROL::TypeB::NewtonKrylovAlgorithm< Real >::krylovName_ private
Krylov name.
Definition at line 33 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
Referenced by ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), and ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm().
iterKrylov_
template<typename Real > int ROL::TypeB::NewtonKrylovAlgorithm< Real >::iterKrylov_ private
Number of Krylov iterations (used for inexact Newton)
Definition at line 35 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
flagKrylov_
template<typename Real > int ROL::TypeB::NewtonKrylovAlgorithm< Real >::flagKrylov_ private
Termination flag for Krylov method (used for inexact Newton)
Definition at line 36 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
useSecantHessVec_
template<typename Real > bool ROL::TypeB::NewtonKrylovAlgorithm< Real >::useSecantHessVec_ private
Whether or not to use to a secant approximation as the Hessian.
Definition at line 38 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
useSecantPrecond_
template<typename Real > bool ROL::TypeB::NewtonKrylovAlgorithm< Real >::useSecantPrecond_ private
Whether or not to use a secant approximation to precondition inexact Newton.
Definition at line 39 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
maxit_
template<typename Real > int ROL::TypeB::NewtonKrylovAlgorithm< Real >::maxit_ private
Maximum number of line search steps (default: 20)
Definition at line 41 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
alpha0_
template<typename Real > Real ROL::TypeB::NewtonKrylovAlgorithm< Real >::alpha0_ private
Initial line search step size (default: 1.0)
Definition at line 42 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
rhodec_
template<typename Real > Real ROL::TypeB::NewtonKrylovAlgorithm< Real >::rhodec_ private
Backtracking rate (default: 0.5)
Definition at line 43 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
c1_
template<typename Real > Real ROL::TypeB::NewtonKrylovAlgorithm< Real >::c1_ private
Sufficient Decrease Parameter (default: 1e-4)
Definition at line 44 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
useralpha_
template<typename Real > bool ROL::TypeB::NewtonKrylovAlgorithm< Real >::useralpha_ private
Flag to use user-defined initial step size (default: false)
Definition at line 45 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
usePrevAlpha_
template<typename Real > bool ROL::TypeB::NewtonKrylovAlgorithm< Real >::usePrevAlpha_ private
Flag to use previous step size as next initial step size (default: false)
Definition at line 46 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
ls_nfval_
template<typename Real > int ROL::TypeB::NewtonKrylovAlgorithm< Real >::ls_nfval_ private
Definition at line 48 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
verbosity_
template<typename Real > int ROL::TypeB::NewtonKrylovAlgorithm< Real >::verbosity_ private
Definition at line 49 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
writeHeader_
template<typename Real > bool ROL::TypeB::NewtonKrylovAlgorithm< Real >::writeHeader_ private
Definition at line 50 of file ROL_TypeB_NewtonKrylovAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeB_NewtonKrylovAlgorithm.hpp
ROL_TypeB_NewtonKrylovAlgorithm_Def.hpp