ROL: ROL::TypeG::AugmentedLagrangianAlgorithm< Real > Class Template Reference
ROL::TypeG::AugmentedLagrangianAlgorithm< Real > Class Template Reference
Provides an interface to run general constrained optimization algorithms using Augmented Lagrangians.
#include <ROL_TypeG_AugmentedLagrangianAlgorithm.hpp>
Public Member Functions
AugmentedLagrangianAlgorithm (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr)
void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, std::ostream &outStream=std::cout) override
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
void writeHeader (std::ostream &os) const override
Print iterate header.
void writeName (std::ostream &os) const override
Print step name.
void writeOutput (std::ostream &os, const bool print_header=false) const override
Print iterate status.
Public Member Functions inherited from ROL::TypeG::Algorithm< Real >
virtual ~Algorithm ()
Algorithm ()
Constructor, given a step and a status test.
void setStatusTest (const Ptr< StatusTest< Real > > &status, bool combineStatus=false)
virtual void run (Problem< Real > &problem, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void run (Vector< Real > &x, const Vector< Real > &g, Objective< Real > &obj, BoundConstraint< Real > &bnd, Constraint< Real > &econ, Vector< Real > &emul, const Vector< Real > &eres, Constraint< Real > &icon, Vector< Real > &imul, BoundConstraint< Real > &ibnd, const Vector< Real > &ires, Constraint< Real > &linear_econ, Vector< Real > &linear_emul, const Vector< Real > &linear_eres, std::ostream &outStream=std::cout)
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
virtual void writeExitStatus (std::ostream &os) const
Ptr< const AlgorithmState< Real > > getState () const
void reset ()
Private Member Functions
void initialize (Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &l, const Vector< Real > &c, AugmentedLagrangianObjective< Real > &alobj, BoundConstraint< Real > &bnd, Constraint< Real > &con, std::ostream &outStream=std::cout)
Private Attributes
const Ptr< Secant< Real > > secant_
ParameterList list_
bool useRelTol_
bool useDefaultInitPen_
bool scaleLagrangian_
Real minPenaltyReciprocal_
Real minPenaltyLowerBound_
Real penaltyUpdate_
Real maxPenaltyParam_
Real optIncreaseExponent_
Real optDecreaseExponent_
Real optToleranceInitial_
Real optTolerance_
Real feasIncreaseExponent_
Real feasDecreaseExponent_
Real feasToleranceInitial_
Real feasTolerance_
bool print_
int maxit_
int subproblemIter_
std::string subStep_
int HessianApprox_
Real outerOptTolerance_
Real outerFeasTolerance_
Real outerStepTolerance_
bool useDefaultScaling_
Real fscale_
Real cscale_
int verbosity_
bool printHeader_
bool hasPolyProj_
Additional Inherited Members
Protected Member Functions inherited from ROL::TypeG::Algorithm< Real >
void initialize (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &mul, const Vector< Real > &c)
Protected Attributes inherited from ROL::TypeG::Algorithm< Real >
const Ptr< CombinedStatusTest< Real > > status_
const Ptr< AlgorithmState< Real > > state_
Ptr< PolyhedralProjection< Real > > proj_
Detailed Description
template<typename Real>
class ROL::TypeG::AugmentedLagrangianAlgorithm< Real >
Provides an interface to run general constrained optimization algorithms using Augmented Lagrangians.
Definition at line 27 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Constructor & Destructor Documentation
AugmentedLagrangianAlgorithm()
template<typename Real > ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr)
Definition at line 19 of file ROL_TypeG_AugmentedLagrangianAlgorithm_Def.hpp.
References ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::cscale_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::feasDecreaseExponent_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::feasIncreaseExponent_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::feasToleranceInitial_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::fscale_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::HessianApprox_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::list_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::maxit_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::maxPenaltyParam_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::minPenaltyLowerBound_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::minPenaltyReciprocal_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::optDecreaseExponent_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::optIncreaseExponent_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::optToleranceInitial_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::outerFeasTolerance_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::outerOptTolerance_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::outerStepTolerance_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::penaltyUpdate_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::print_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::printHeader_, ROL::TypeG::Algorithm< Real >::reset(), ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::scaleLagrangian_, ROL::TypeG::Algorithm< Real >::state_, ROL::TypeG::Algorithm< Real >::status_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::subStep_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::useDefaultInitPen_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::useDefaultScaling_, ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::useRelTol_, and ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::verbosity_.
Member Function Documentation
initialize()
template<typename Real > void ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::initialize (Vector< Real > & x, const Vector< Real > & g, const Vector< Real > & l, const Vector< Real > & c, AugmentedLagrangianObjective< Real > & alobj, BoundConstraint< Real > & bnd, Constraint< Real > & con, std::ostream & outStream = std::cout) private
Definition at line 68 of file ROL_TypeG_AugmentedLagrangianAlgorithm_Def.hpp.
References ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Vector< Real >::axpy(), ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dimension(), ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), ROL::AugmentedLagrangianObjective< Real >::getNumberConstraintEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getNumberFunctionEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getNumberGradientEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveGradient(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveValue(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::Initial, ROL::TypeG::Algorithm< Real >::initialize(), ROL::Vector< Real >::norm(), ROL::AugmentedLagrangianObjective< Real >::reset(), ROL::Vector< Real >::set(), ROL::AugmentedLagrangianObjective< Real >::setScaling(), and ROL::AugmentedLagrangianObjective< Real >::update().
run()
template<typename Real > void ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::run (Vector< Real > & x, const Vector< Real > & g, Objective< Real > & obj, BoundConstraint< Real > & bnd, Constraint< Real > & econ, Vector< Real > & emul, const Vector< Real > & eres, std::ostream & outStream = std::cout) override virtual
Run algorithm on general constrained problems (Type-G). This is the primary Type-G interface.
Implements ROL::TypeG::Algorithm< Real >.
Definition at line 162 of file ROL_TypeG_AugmentedLagrangianAlgorithm_Def.hpp.
References ROL::Vector< Real >::axpy(), ROL::EXITSTATUS_CONVERGED, ROL::AugmentedLagrangianObjective< Real >::getConstraintVec(), ROL::AugmentedLagrangianObjective< Real >::getNumberConstraintEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getNumberFunctionEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getNumberGradientEvaluations(), ROL::AugmentedLagrangianObjective< Real >::getObjectiveValue(), ROL::AugmentedLagrangianObjective< Real >::gradient(), ROL::Vector< Real >::norm(), ROL::AugmentedLagrangianObjective< Real >::reset(), ROL::Vector< Real >::set(), and ROL::TypeG::Algorithm< Real >::writeExitStatus().
writeHeader()
template<typename Real > void ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::writeHeader (std::ostream & os) const override virtual
Print iterate header.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 250 of file ROL_TypeG_AugmentedLagrangianAlgorithm_Def.hpp.
writeName()
template<typename Real > void ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::writeName (std::ostream & os) const override virtual
Print step name.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 287 of file ROL_TypeG_AugmentedLagrangianAlgorithm_Def.hpp.
writeOutput()
template<typename Real > void ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::writeOutput (std::ostream & os, const bool write_header = false) const override virtual
Print iterate status.
Reimplemented from ROL::TypeG::Algorithm< Real >.
Definition at line 296 of file ROL_TypeG_AugmentedLagrangianAlgorithm_Def.hpp.
Member Data Documentation
secant_
template<typename Real > const Ptr<Secant<Real> > ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::secant_ private
Definition at line 29 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
list_
template<typename Real > ParameterList ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::list_ private
Definition at line 30 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
useRelTol_
template<typename Real > bool ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::useRelTol_ private
Definition at line 31 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
useDefaultInitPen_
template<typename Real > bool ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::useDefaultInitPen_ private
Definition at line 33 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
scaleLagrangian_
template<typename Real > bool ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::scaleLagrangian_ private
Definition at line 34 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
minPenaltyReciprocal_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::minPenaltyReciprocal_ private
Definition at line 35 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
minPenaltyLowerBound_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::minPenaltyLowerBound_ private
Definition at line 36 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
penaltyUpdate_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::penaltyUpdate_ private
Definition at line 37 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
maxPenaltyParam_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::maxPenaltyParam_ private
Definition at line 38 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
optIncreaseExponent_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::optIncreaseExponent_ private
Definition at line 40 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
optDecreaseExponent_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::optDecreaseExponent_ private
Definition at line 41 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
optToleranceInitial_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::optToleranceInitial_ private
Definition at line 42 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
optTolerance_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::optTolerance_ private
Definition at line 43 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
feasIncreaseExponent_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::feasIncreaseExponent_ private
Definition at line 45 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
feasDecreaseExponent_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::feasDecreaseExponent_ private
Definition at line 46 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
feasToleranceInitial_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::feasToleranceInitial_ private
Definition at line 47 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
feasTolerance_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::feasTolerance_ private
Definition at line 48 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
print_
template<typename Real > bool ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::print_ private
Definition at line 50 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
maxit_
template<typename Real > int ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::maxit_ private
Definition at line 51 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
subproblemIter_
template<typename Real > int ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::subproblemIter_ private
Definition at line 52 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
subStep_
template<typename Real > std::string ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::subStep_ private
Definition at line 53 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
HessianApprox_
template<typename Real > int ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::HessianApprox_ private
Definition at line 54 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
outerOptTolerance_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::outerOptTolerance_ private
Definition at line 55 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
outerFeasTolerance_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::outerFeasTolerance_ private
Definition at line 56 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
outerStepTolerance_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::outerStepTolerance_ private
Definition at line 57 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
useDefaultScaling_
template<typename Real > bool ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::useDefaultScaling_ private
Definition at line 59 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
fscale_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::fscale_ private
Definition at line 60 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
cscale_
template<typename Real > Real ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::cscale_ private
Definition at line 61 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
verbosity_
template<typename Real > int ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::verbosity_ private
Definition at line 63 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
printHeader_
template<typename Real > bool ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::printHeader_ private
Definition at line 64 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
Referenced by ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::AugmentedLagrangianAlgorithm().
hasPolyProj_
template<typename Real > bool ROL::TypeG::AugmentedLagrangianAlgorithm< Real >::hasPolyProj_ private
Definition at line 65 of file ROL_TypeG_AugmentedLagrangianAlgorithm.hpp.
The documentation for this class was generated from the following files:
ROL_TypeG_AugmentedLagrangianAlgorithm.hpp
ROL_TypeG_AugmentedLagrangianAlgorithm_Def.hpp