ROL: ROL::SimulatedConstraint< Real > Class Template Reference
ROL::SimulatedConstraint< Real > Class Template Reference
#include <ROL_SimulatedConstraint.hpp>
Public Member Functions
virtual ~SimulatedConstraint ()
SimulatedConstraint (const ROL::Ptr< SampleGenerator< Real > > &sampler, const ROL::Ptr< Constraint_SimOpt< Real > > &pcon, const bool useWeights=true)
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update constraint function.
void value (Vector< Real > &c, const Vector< Real > &x, Real &tol)
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
virtual void applyJacobian (Vector< Real > &jv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual void applyAdjointHessian (Vector< Real > &ahuv, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
virtual void applyPreconditioner (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
Public Member Functions inherited from ROL::Constraint< Real >
virtual ~Constraint (void)
Constraint (void)
virtual void applyAdjointJacobian (Vector< Real > &ajv, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualv, Real &tol)
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
virtual std::vector< Real > solveAugmentedSystem (Vector< Real > &v1, Vector< Real > &v2, const Vector< Real > &b1, const Vector< Real > &b2, const Vector< Real > &x, Real &tol)
Approximately solves the augmented system
void activate (void)
Turn on constraints.
void deactivate (void)
Turn off constraints.
bool isActivated (void)
Check if constraints are on.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &jv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the constraint Jacobian application.
virtual std::vector< std::vector< Real > > checkApplyAdjointJacobian (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &c, const Vector< Real > &ajv, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference check for the application of the adjoint of constraint Jacobian.
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual Real checkAdjointConsistencyJacobian (const Vector< Real > &w, const Vector< Real > &v, const Vector< Real > &x, const Vector< Real > &dualw, const Vector< Real > &dualv, const bool printToStream=true, std::ostream &outStream=std::cout)
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const std::vector< Real > &step, const bool printToScreen=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual std::vector< std::vector< Real > > checkApplyAdjointHessian (const Vector< Real > &x, const Vector< Real > &u, const Vector< Real > &v, const Vector< Real > &hv, const bool printToScreen=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference check for the application of the adjoint of constraint Hessian.
virtual void setParameter (const std::vector< Real > &param)
Private Attributes
const ROL::Ptr< SampleGenerator< Real > > sampler_
const ROL::Ptr< Constraint_SimOpt< Real > > pcon_
const bool useWeights_
Additional Inherited Members
Protected Member Functions inherited from ROL::Constraint< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::SimulatedConstraint< Real >
Definition at line 20 of file ROL_SimulatedConstraint.hpp.
Constructor & Destructor Documentation
~SimulatedConstraint()
template<class Real > virtual ROL::SimulatedConstraint< Real >::~SimulatedConstraint () inline virtual
Definition at line 28 of file ROL_SimulatedConstraint.hpp.
SimulatedConstraint()
template<class Real > ROL::SimulatedConstraint< Real >::SimulatedConstraint (const ROL::Ptr< SampleGenerator< Real > > & sampler, const ROL::Ptr< Constraint_SimOpt< Real > > & pcon, const bool useWeights = true) inline
Definition at line 30 of file ROL_SimulatedConstraint.hpp.
Member Function Documentation
update() [1/2]
template<class Real > void ROL::SimulatedConstraint< Real >::update (const Vector< Real > & x, bool flag = true, int iter = -1) inline virtual
Update constraint functions.
x is the optimization variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 35 of file ROL_SimulatedConstraint.hpp.
References ROL::SimulatedConstraint< Real >::pcon_.
update() [2/2]
template<class Real > void ROL::SimulatedConstraint< Real >::update (const Vector< Real > & x, UpdateType type, int iter = -1) inline virtual
Update constraint function.
This function updates the constraint function at new iterations.
Parameters
[in] x is the new iterate.
[in] type is the type of update requested.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Constraint< Real >.
Definition at line 38 of file ROL_SimulatedConstraint.hpp.
References ROL::SimulatedConstraint< Real >::pcon_.
value()
template<class Real > void ROL::SimulatedConstraint< Real >::value (Vector< Real > & c, const Vector< Real > & x, Real & tol) inline virtual
Evaluate the constraint operator \(c:\mathcal{X} \rightarrow \mathcal{C}\) at \(x\).
Parameters
[out] c is the result of evaluating the constraint operator at x; a constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{c} = c(x)\), where \(\mathsf{c} \in \mathcal{C}\), \(\mathsf{x} \in \mathcal{X}\).
Implements ROL::Constraint< Real >.
Definition at line 42 of file ROL_SimulatedConstraint.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::RiskVector< Real >::getVector(), ROL::SimulatedVector< Real >::numVectors(), ROL::SimulatedConstraint< Real >::pcon_, ROL::SimulatedConstraint< Real >::sampler_, ROL::SimulatedConstraint< Real >::useWeights_, and ROL::Vector< Real >::zero().
applyJacobian()
template<class Real > virtual void ROL::SimulatedConstraint< Real >::applyJacobian (Vector< Real > & jv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the constraint Jacobian at \(x\), \(c'(x) \in L(\mathcal{X}, \mathcal{C})\), to vector \(v\).
Parameters
[out] jv is the result of applying the constraint Jacobian to v at x; a constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{jv} = c'(x)v\), where \(v \in \mathcal{X}\), \(\mathsf{jv} \in \mathcal{C}\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 72 of file ROL_SimulatedConstraint.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::RiskVector< Real >::getVector(), ROL::SimulatedVector< Real >::numVectors(), ROL::SimulatedConstraint< Real >::pcon_, ROL::SimulatedConstraint< Real >::sampler_, ROL::SimulatedConstraint< Real >::useWeights_, and ROL::Vector< Real >::zero().
applyAdjointJacobian()
template<class Real > virtual void ROL::SimulatedConstraint< Real >::applyAdjointJacobian (Vector< Real > & ajv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the adjoint of the the constraint Jacobian at \(x\), \(c'(x)^* \in L(\mathcal{C}^*, \mathcal{X}^*)\), to vector \(v\).
Parameters
[out] ajv is the result of applying the adjoint of the constraint Jacobian to v at x; a dual optimization-space vector
[in] v is a dual constraint-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ajv} = c'(x)^*v\), where \(v \in \mathcal{C}^*\), \(\mathsf{ajv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation.
Reimplemented from ROL::Constraint< Real >.
Definition at line 116 of file ROL_SimulatedConstraint.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::RiskVector< Real >::getVector(), ROL::SimulatedVector< Real >::numVectors(), ROL::SimulatedConstraint< Real >::pcon_, ROL::SimulatedConstraint< Real >::sampler_, ROL::Vector_SimOpt< Real >::scale(), ROL::SimulatedConstraint< Real >::useWeights_, and ROL::Vector< Real >::zero().
applyAdjointHessian()
template<class Real > virtual void ROL::SimulatedConstraint< Real >::applyAdjointHessian (Vector< Real > & ahuv, const Vector< Real > & u, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline virtual
Apply the derivative of the adjoint of the constraint Jacobian at \(x\) to vector \(u\) in direction \(v\), according to \(v \mapsto c''(x)(v,\cdot)^*u \).
Parameters
[out] ahuv is the result of applying the derivative of the adjoint of the constraint Jacobian at x to vector u in direction v; a dual optimization-space vector
[in] u is the direction vector; a dual constraint-space vector
[in] v is an optimization-space vector
[in] x is the constraint argument; an optimization-space vector
[in,out] tol is a tolerance for inexact evaluations; currently unused
On return, \(\mathsf{ahuv} = c''(x)(v,\cdot)^*u \), where \(u \in \mathcal{C}^*\), \(v \in \mathcal{X}\), and \(\mathsf{ahuv} \in \mathcal{X}^*\).
The default implementation is a finite-difference approximation based on the adjoint Jacobian.
Reimplemented from ROL::Constraint< Real >.
Definition at line 165 of file ROL_SimulatedConstraint.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::RiskVector< Real >::getVector(), ROL::SimulatedVector< Real >::numVectors(), ROL::SimulatedConstraint< Real >::pcon_, ROL::SimulatedConstraint< Real >::sampler_, ROL::Vector_SimOpt< Real >::scale(), ROL::SimulatedConstraint< Real >::useWeights_, and ROL::Vector< Real >::zero().
applyPreconditioner()
template<class Real > virtual void ROL::SimulatedConstraint< Real >::applyPreconditioner (Vector< Real > & pv, const Vector< Real > & v, const Vector< Real > & x, const Vector< Real > & g, Real & tol) inline virtual
Apply a constraint preconditioner at \(x\), \(P(x) \in L(\mathcal{C}, \mathcal{C}^*)\), to vector \(v\). Ideally, this preconditioner satisfies the following relationship:
\[ \left[c'(x) \circ R \circ c'(x)^* \circ P(x)\right] v = v \,, \]
where R is the appropriate Riesz map in \(L(\mathcal{X}^*, \mathcal{X})\). It is used by the solveAugmentedSystem method.
Parameters
[out] pv is the result of applying the constraint preconditioner to v at x; a dual constraint-space vector
[in] v is a constraint-space vector
[in] x is the preconditioner argument; an optimization-space vector
[in] g is the preconditioner argument; a dual optimization-space vector, unused
[in,out] tol is a tolerance for inexact evaluations
On return, \(\mathsf{pv} = P(x)v\), where \(v \in \mathcal{C}\), \(\mathsf{pv} \in \mathcal{C}^*\).
The default implementation is the Riesz map in \(L(\mathcal{C}, \mathcal{C}^*)\).
Reimplemented from ROL::Constraint< Real >.
Definition at line 225 of file ROL_SimulatedConstraint.hpp.
References ROL::SimulatedVector< Real >::get(), ROL::Vector_SimOpt< Real >::get_1(), ROL::Vector_SimOpt< Real >::get_2(), ROL::RiskVector< Real >::getVector(), ROL::SimulatedVector< Real >::numVectors(), ROL::SimulatedConstraint< Real >::pcon_, ROL::SimulatedConstraint< Real >::sampler_, ROL::SimulatedConstraint< Real >::useWeights_, and ROL::Vector< Real >::zero().
Member Data Documentation
sampler_
template<class Real > const ROL::Ptr<SampleGenerator<Real> > ROL::SimulatedConstraint< Real >::sampler_ private
Definition at line 22 of file ROL_SimulatedConstraint.hpp.
Referenced by ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), and ROL::SimulatedConstraint< Real >::value().
pcon_
template<class Real > const ROL::Ptr<Constraint_SimOpt<Real> > ROL::SimulatedConstraint< Real >::pcon_ private
Definition at line 23 of file ROL_SimulatedConstraint.hpp.
Referenced by ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), ROL::SimulatedConstraint< Real >::update(), ROL::SimulatedConstraint< Real >::update(), and ROL::SimulatedConstraint< Real >::value().
useWeights_
template<class Real > const bool ROL::SimulatedConstraint< Real >::useWeights_ private
Definition at line 24 of file ROL_SimulatedConstraint.hpp.
Referenced by ROL::SimulatedConstraint< Real >::applyAdjointHessian(), ROL::SimulatedConstraint< Real >::applyAdjointJacobian(), ROL::SimulatedConstraint< Real >::applyJacobian(), ROL::SimulatedConstraint< Real >::applyPreconditioner(), and ROL::SimulatedConstraint< Real >::value().
The documentation for this class was generated from the following file:
ROL_SimulatedConstraint.hpp