ROL: ROL::MoreauYosidaCVaR< Real > Class Template Reference
ROL::MoreauYosidaCVaR< Real > Class Template Reference
Algorithmic Extensions » Stochastic Optimization » Risk Measures
Provides an interface for a smooth approximation of the conditional value-at-risk.
#include <ROL_MoreauYosidaCVaR.hpp>
Public Member Functions
MoreauYosidaCVaR (Real prob, Real eps)
Constructor.
MoreauYosidaCVaR (ROL::ParameterList &parlist)
Constructor.
Real error (Real x, int deriv=0)
Evaluate the scalar error function at x.
Real regret (Real x, int deriv=0)
Evaluate the scalar regret function at x.
void check (void)
Run default derivative tests for the scalar regret function.
Public Member Functions inherited from ROL::ExpectationQuad< Real >
virtual ~ExpectationQuad (void)
ExpectationQuad (void)
Private Member Functions
void parseParameterList (ROL::ParameterList &parlist)
void checkInputs (void) const
void setParameters (void)
Private Attributes
Real prob_
Real eps_
Real omp_
Real ub_
Detailed Description
template<class Real>
class ROL::MoreauYosidaCVaR< Real >
Provides an interface for a smooth approximation of the conditional value-at-risk.
The conditional value-at-risk (also called the average value-at-risk or the expected shortfall) with confidence level \(0\le \beta < 1\) is
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \frac{1}{1-\beta} \mathbb{E}\left[(X-t)_+\right] \right\} \]
where \((x)_+ = \max\{0,x\}\). If the distribution of \(X\) is continuous, then \(\mathcal{R}\) is the conditional expectation of \(X\) exceeding the \(\beta\)-quantile of \(X\) and the optimal \(t\) is the \(\beta\)-quantile. Additionally, \(\mathcal{R}\) is a law-invariant coherent risk measure.
The conditional value-at-risk is in general not smooth due to \((\cdot)_+\). One approach to smoothing the conditional-value-at-risk is to regularize its biconjugate form. That is, since \(\mathcal{R}\) is coherent, we have that
\[ \mathcal{R}(X) = \sup_{\vartheta\in\mathfrak{A}}\mathbb{E}[\vartheta X] \]
where \(\mathfrak{A}\) is the effective domain of the conjugate of \(\mathcal{R}\), i.e.,
\[ \mathfrak{A} = \mathrm{dom}\,\mathcal{R}^* = \{\vartheta\in\mathcal{X}^*\,:\, \mathcal{R}^*(\vartheta) < \infty\} \]
where \(\mathcal{R}^*\) denotes the Legendre-Fenchel transformation of \(\mathcal{R}\). This risk measure implements the penalized conditional value-at-risk
\[ \mathcal{R}(X) = \sup_{\vartheta\in\mathfrak{A}} \left\{\mathbb{E}[\vartheta X] - \frac{\gamma}{2}\mathbb{E}[(\vartheta-1)^2]\right\} \]
for \(\gamma > 0\). This is implemented using the expectation risk quadrangle interface. Thus, we represent \(\mathcal{R}\) as
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \mathbb{E}\left[v(X-t)\right] \right\} \]
for an appropriately defined scalar regret function \(v\). ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
The conditional value-at-risk (also called the average value-at-risk or the expected shortfall) with confidence level \(0\le \beta < 1\) is
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \frac{1}{1-\beta} \mathbb{E}\left[(X-t)_+\right] \right\} \]
where \((x)_+ = \max\{0,x\}\). If the distribution of \(X\) is continuous, then \(\mathcal{R}\) is the conditional expectation of \(X\) exceeding the \(\beta\)-quantile of \(X\) and the optimal \(t\) is the \(\beta\)-quantile. Additionally, \(\mathcal{R}\) is a law-invariant coherent risk measure.
The conditional value-at-risk is in general not smooth due to \((\cdot)_+\). One approach to smoothing the conditional-value-at-risk is to regularize its biconjugate form. That is, since \(\mathcal{R}\) is coherent, we have that
\[ \mathcal{R}(X) = \sup_{\vartheta\in\mathfrak{A}}\mathbb{E}[\vartheta X] \]
where \(\mathfrak{A}\) is the effective domain of the conjugate of \(\mathcal{R}\), i.e.,
\[ \mathfrak{A} = \mathrm{dom}\,\mathcal{R}^* = \{\vartheta\in\mathcal{X}^*\,:\, \mathcal{R}^*(\vartheta) < \infty\} \]
where \(\mathcal{R}^*\) denotes the Legendre-Fenchel transformation of \(\mathcal{R}\). This risk measure implements the penalized conditional value-at-risk
\[ \mathcal{R}(X) = \sup_{\vartheta\in\mathfrak{A}} \left\{\mathbb{E}[\vartheta X] - \frac{\gamma}{2}\mathbb{E}[\vartheta^2]\right\} \]
for \(\gamma > 0\). This is implemented using the expectation risk quadrangle interface. Thus, we represent \(\mathcal{R}\) as
\[ \mathcal{R}(X) = \inf_{t\in\mathbb{R}} \left\{ t + \mathbb{E}\left[v(X-t)\right] \right\} \]
for an appropriately defined scalar regret function \(v\). ROL implements this by augmenting the optimization vector \(x_0\) with the parameter \(t\), then minimizes jointly for \((x_0,t)\).
Definition at line 71 of file ROL_MoreauYosidaCVaR.hpp.
Constructor & Destructor Documentation
MoreauYosidaCVaR() [1/2]
template<class Real > ROL::MoreauYosidaCVaR< Real >::MoreauYosidaCVaR (Real prob, Real eps) inline
Constructor.
Parameters
[in] prob is the confidence level
[in] eps is the regularization parameter
Definition at line 119 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::MoreauYosidaCVaR< Real >::checkInputs(), and ROL::MoreauYosidaCVaR< Real >::setParameters().
MoreauYosidaCVaR() [2/2]
template<class Real > ROL::MoreauYosidaCVaR< Real >::MoreauYosidaCVaR (ROL::ParameterList & parlist) inline
Constructor.
Parameters
[in] parlist is a parameter list specifying inputs
parlist should contain sublists "SOL"->"Risk Measure"->"Moreau-Yosida CVaR" and within the "Moreau-Yosida CVaR" sublist should have the following parameters
"Confidence Level" (between 0 and 1)
"Smoothing Parameter" (must be positive)
Definition at line 134 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::MoreauYosidaCVaR< Real >::checkInputs(), ROL::MoreauYosidaCVaR< Real >::parseParameterList(), and ROL::MoreauYosidaCVaR< Real >::setParameters().
Member Function Documentation
parseParameterList()
template<class Real > void ROL::MoreauYosidaCVaR< Real >::parseParameterList (ROL::ParameterList & parlist) inline private
Definition at line 80 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::MoreauYosidaCVaR< Real >::eps_, and ROL::MoreauYosidaCVaR< Real >::prob_.
Referenced by ROL::MoreauYosidaCVaR< Real >::MoreauYosidaCVaR().
checkInputs()
template<class Real > void ROL::MoreauYosidaCVaR< Real >::checkInputs (void) const inline private
Definition at line 99 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::MoreauYosidaCVaR< Real >::eps_, ROL::MoreauYosidaCVaR< Real >::prob_, and zero.
Referenced by ROL::MoreauYosidaCVaR< Real >::MoreauYosidaCVaR(), and ROL::MoreauYosidaCVaR< Real >::MoreauYosidaCVaR().
setParameters()
template<class Real > void ROL::MoreauYosidaCVaR< Real >::setParameters (void) inline private
Definition at line 107 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::MoreauYosidaCVaR< Real >::eps_, ROL::MoreauYosidaCVaR< Real >::omp_, ROL::MoreauYosidaCVaR< Real >::prob_, and ROL::MoreauYosidaCVaR< Real >::ub_.
Referenced by ROL::MoreauYosidaCVaR< Real >::MoreauYosidaCVaR(), and ROL::MoreauYosidaCVaR< Real >::MoreauYosidaCVaR().
error()
template<class Real > Real ROL::MoreauYosidaCVaR< Real >::error (Real x, int deriv = 0) inline virtual
Evaluate the scalar error function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(e(x)\) or a derivative of \(e(x)\).
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 141 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::MoreauYosidaCVaR< Real >::regret(), and zero.
regret()
template<class Real > Real ROL::MoreauYosidaCVaR< Real >::regret (Real x, int deriv = 0) inline virtual
Evaluate the scalar regret function at x.
Parameters
[in] x is the scalar input
[in] deriv is the derivative order
This function returns \(v(x)\) or a derivative of \(v(x)\).
Implements ROL::ExpectationQuad< Real >.
Definition at line 147 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::MoreauYosidaCVaR< Real >::eps_, ROL::MoreauYosidaCVaR< Real >::omp_, ROL::MoreauYosidaCVaR< Real >::ub_, and zero.
Referenced by ROL::MoreauYosidaCVaR< Real >::check(), and ROL::MoreauYosidaCVaR< Real >::error().
check()
template<class Real > void ROL::MoreauYosidaCVaR< Real >::check (void) inline virtual
Run default derivative tests for the scalar regret function.
Reimplemented from ROL::ExpectationQuad< Real >.
Definition at line 163 of file ROL_MoreauYosidaCVaR.hpp.
References ROL::ExpectationQuad< Real >::check(), ROL::MoreauYosidaCVaR< Real >::eps_, ROL::MoreauYosidaCVaR< Real >::regret(), and zero.
Member Data Documentation
prob_
template<class Real > Real ROL::MoreauYosidaCVaR< Real >::prob_ private
Definition at line 74 of file ROL_MoreauYosidaCVaR.hpp.
Referenced by ROL::MoreauYosidaCVaR< Real >::checkInputs(), ROL::MoreauYosidaCVaR< Real >::parseParameterList(), and ROL::MoreauYosidaCVaR< Real >::setParameters().
eps_
template<class Real > Real ROL::MoreauYosidaCVaR< Real >::eps_ private
Definition at line 75 of file ROL_MoreauYosidaCVaR.hpp.
Referenced by ROL::MoreauYosidaCVaR< Real >::check(), ROL::MoreauYosidaCVaR< Real >::checkInputs(), ROL::MoreauYosidaCVaR< Real >::parseParameterList(), ROL::MoreauYosidaCVaR< Real >::regret(), and ROL::MoreauYosidaCVaR< Real >::setParameters().
omp_
template<class Real > Real ROL::MoreauYosidaCVaR< Real >::omp_ private
Definition at line 77 of file ROL_MoreauYosidaCVaR.hpp.
Referenced by ROL::MoreauYosidaCVaR< Real >::regret(), and ROL::MoreauYosidaCVaR< Real >::setParameters().
ub_
template<class Real > Real ROL::MoreauYosidaCVaR< Real >::ub_ private
Definition at line 78 of file ROL_MoreauYosidaCVaR.hpp.
Referenced by ROL::MoreauYosidaCVaR< Real >::regret(), and ROL::MoreauYosidaCVaR< Real >::setParameters().
The documentation for this class was generated from the following file:
ROL_MoreauYosidaCVaR.hpp