ROL: L2VectorBatchManager< Real, Ordinal > Class Template Reference
L2VectorBatchManager< Real, Ordinal > Class Template Reference
#include <example_06.hpp>
Public Member Functions
L2VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > &comm)
void sumAll (ROL::Vector< Real > &input, ROL::Vector< Real > &output)
L2VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > &comm)
void sumAll (ROL::Vector< Real > &input, ROL::Vector< Real > &output)
L2VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > &comm)
void sumAll (ROL::Vector< Real > &input, ROL::Vector< Real > &output)
Private Member Functions
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
void cast_vector (ROL::Ptr< std::vector< Real > > &xvec, ROL::Vector< Real > &x) const
Detailed Description
template<class Real, class Ordinal>
class L2VectorBatchManager< Real, Ordinal >
Definition at line 1198 of file example_06.hpp.
Constructor & Destructor Documentation
L2VectorBatchManager() [1/3]
template<class Real , class Ordinal > L2VectorBatchManager< Real, Ordinal >::L2VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > & comm) inline
Definition at line 1211 of file example_06.hpp.
L2VectorBatchManager() [2/3]
template<class Real , class Ordinal > L2VectorBatchManager< Real, Ordinal >::L2VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > & comm) inline
Definition at line 1561 of file example_07.hpp.
L2VectorBatchManager() [3/3]
template<class Real , class Ordinal > L2VectorBatchManager< Real, Ordinal >::L2VectorBatchManager (const ROL::Ptr< const Teuchos::Comm< int > > & comm) inline
Definition at line 1343 of file example_08.hpp.
Member Function Documentation
cast_vector() [1/3]
template<class Real , class Ordinal > void L2VectorBatchManager< Real, Ordinal >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1200 of file example_06.hpp.
Referenced by L2VectorBatchManager< Real, Ordinal >::sumAll().
sumAll() [1/3]
template<class Real , class Ordinal > void L2VectorBatchManager< Real, Ordinal >::sumAll (ROL::Vector< Real > & input, ROL::Vector< Real > & output) inline
Definition at line 1213 of file example_06.hpp.
References L2VectorBatchManager< Real, Ordinal >::cast_vector().
cast_vector() [2/3]
template<class Real , class Ordinal > void L2VectorBatchManager< Real, Ordinal >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1548 of file example_07.hpp.
sumAll() [2/3]
template<class Real , class Ordinal > void L2VectorBatchManager< Real, Ordinal >::sumAll (ROL::Vector< Real > & input, ROL::Vector< Real > & output) inline
Definition at line 1563 of file example_07.hpp.
References L2VectorBatchManager< Real, Ordinal >::cast_vector().
cast_vector() [3/3]
template<class Real , class Ordinal > void L2VectorBatchManager< Real, Ordinal >::cast_vector (ROL::Ptr< std::vector< Real > > & xvec, ROL::Vector< Real > & x) const inline private
Definition at line 1332 of file example_08.hpp.
sumAll() [3/3]
template<class Real , class Ordinal > void L2VectorBatchManager< Real, Ordinal >::sumAll (ROL::Vector< Real > & input, ROL::Vector< Real > & output) inline
Definition at line 1345 of file example_08.hpp.
References L2VectorBatchManager< Real, Ordinal >::cast_vector().
The documentation for this class was generated from the following files:
example_06.hpp
example_07.hpp
example_08.hpp