ROL: ROL::ConicApproximationModel< Real > Class Template Reference
ROL::ConicApproximationModel< Real > Class Template Reference
#include <ROL_ConicApproximationModel.hpp>
Public Member Functions
virtual ~ConicApproximationModel ()
ConicApproximationModel (const Ptr< Obj > &obj, const Ptr< const V > &x, const Ptr< V > &s, const Ptr< const V > &a)
virtual void update (const V &s, bool flag=true, int iter=-1) override
Update objective function.
virtual Real value (const V &s, Real &tol) override
Compute value.
virtual void gradient (V &g, const V &s, Real &tol) override
Compute gradient.
virtual void hessVec (V &hv, const V &v, const V &s, Real &tol) override
Apply Hessian approximation to vector.
virtual void invHessVec (V &hv, const V &v, const V &s, Real &tol) override
Apply inverse Hessian approximation to vector.
virtual void precond (V &Pv, const V &v, const V &s, Real &tol) override
Apply preconditioner to vector.
virtual ~ConicApproximationModel ()
ConicApproximationModel (const Ptr< Obj > &obj, const Ptr< const V > &x, const Ptr< V > &s, const Ptr< const V > &a)
virtual void update (const V &s, bool flag=true, int iter=-1) override
Update objective function.
virtual Real value (const V &s, Real &tol) override
Compute value.
virtual void gradient (V &g, const V &s, Real &tol) override
Compute gradient.
virtual void hessVec (V &hv, const V &v, const V &s, Real &tol) override
Apply Hessian approximation to vector.
virtual void invHessVec (V &hv, const V &v, const V &s, Real &tol) override
Apply inverse Hessian approximation to vector.
virtual void precond (V &Pv, const V &v, const V &s, Real &tol) override
Apply preconditioner to vector.
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Private Types
using V = Vector< Real >
using Obj = Objective< Real >
using V = Vector< Real >
using Obj = Objective< Real >
Private Attributes
Ptr< Obj > obj_
const Ptr< const V > x_
const Ptr< const V > a_
Ptr< V > g_
Ptr< V > s_
Ptr< V > Hs_
Real f_
Real gamma_
Real sHs_
VectorWorkspace< Real > workspace_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class ROL::ConicApproximationModel< Real >
Definition at line 32 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Member Typedef Documentation
V [1/2]
template<class Real > using ROL::ConicApproximationModel< Real >::V = Vector<Real> private
Definition at line 34 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Obj [1/2]
template<class Real > using ROL::ConicApproximationModel< Real >::Obj = Objective<Real> private
Definition at line 35 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
V [2/2]
template<class Real > using ROL::ConicApproximationModel< Real >::V = Vector<Real> private
Definition at line 34 of file step/trustregion/ROL_ConicApproximationModel.hpp.
Obj [2/2]
template<class Real > using ROL::ConicApproximationModel< Real >::Obj = Objective<Real> private
Definition at line 35 of file step/trustregion/ROL_ConicApproximationModel.hpp.
Constructor & Destructor Documentation
~ConicApproximationModel() [1/2]
template<class Real > virtual ROL::ConicApproximationModel< Real >::~ConicApproximationModel () inline virtual
Definition at line 47 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
ConicApproximationModel() [1/2]
template<class Real > ROL::ConicApproximationModel< Real >::ConicApproximationModel (const Ptr< Obj > & obj, const Ptr< const V > & x, const Ptr< V > & s, const Ptr< const V > & a) inline
Definition at line 49 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::ConicApproximationModel< Real >::f_, ROL::ConicApproximationModel< Real >::g_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::Hs_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, and ROL::ConicApproximationModel< Real >::x_.
~ConicApproximationModel() [2/2]
template<class Real > virtual ROL::ConicApproximationModel< Real >::~ConicApproximationModel () inline virtual
Definition at line 47 of file step/trustregion/ROL_ConicApproximationModel.hpp.
ConicApproximationModel() [2/2]
template<class Real > ROL::ConicApproximationModel< Real >::ConicApproximationModel (const Ptr< Obj > & obj, const Ptr< const V > & x, const Ptr< V > & s, const Ptr< const V > & a) inline
Definition at line 49 of file step/trustregion/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::ConicApproximationModel< Real >::f_, ROL::ConicApproximationModel< Real >::g_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::Hs_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, and ROL::ConicApproximationModel< Real >::x_.
Member Function Documentation
update() [1/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::update (const V & x, bool flag = true, int iter = -1) inline override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 60 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::Hs_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, and ROL::ConicApproximationModel< Real >::x_.
value() [1/2]
template<class Real > virtual Real ROL::ConicApproximationModel< Real >::value (const V & x, Real & tol) inline override virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 67 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::f_, ROL::ConicApproximationModel< Real >::g_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::s_, and ROL::ConicApproximationModel< Real >::sHs_.
gradient() [1/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::gradient (V & g, const V & x, Real & tol) inline override virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 71 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::ConicApproximationModel< Real >::g_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::Hs_, ROL::Vector< Real >::plus(), ROL::ConicApproximationModel< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and ROL::ConicApproximationModel< Real >::workspace_.
hessVec() [1/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::hessVec (V & hv, const V & v, const V & x, Real & tol) inline override virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 85 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::Vector< Real >::axpy(), ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::obj_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::ConicApproximationModel< Real >::workspace_, and ROL::ConicApproximationModel< Real >::x_.
invHessVec() [1/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::invHessVec (V & hv, const V & v, const V & x, Real & tol) inline override virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 98 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::Vector< Real >::axpy(), ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::ConicApproximationModel< Real >::workspace_, and ROL::ConicApproximationModel< Real >::x_.
precond() [1/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::precond (V & Pv, const V & v, const V & x, Real & tol) inline override virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 109 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::Vector< Real >::axpy(), ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::ConicApproximationModel< Real >::workspace_, and ROL::ConicApproximationModel< Real >::x_.
update() [2/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::update (const V & x, bool flag = true, int iter = -1) inline override virtual
Update objective function.
This function updates the objective function at new iterations.
Parameters
[in] x is the new iterate.
[in] flag is true if the iterate has changed.
[in] iter is the outer algorithm iterations count.
Reimplemented from ROL::Objective< Real >.
Definition at line 60 of file step/trustregion/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::Hs_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, and ROL::ConicApproximationModel< Real >::x_.
value() [2/2]
template<class Real > virtual Real ROL::ConicApproximationModel< Real >::value (const V & x, Real & tol) inline override virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 67 of file step/trustregion/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::f_, ROL::ConicApproximationModel< Real >::g_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::s_, and ROL::ConicApproximationModel< Real >::sHs_.
gradient() [2/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::gradient (V & g, const V & x, Real & tol) inline override virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 71 of file step/trustregion/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::ConicApproximationModel< Real >::g_, ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::Hs_, ROL::Vector< Real >::plus(), ROL::ConicApproximationModel< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), and ROL::ConicApproximationModel< Real >::workspace_.
hessVec() [2/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::hessVec (V & hv, const V & v, const V & x, Real & tol) inline override virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 85 of file step/trustregion/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::Vector< Real >::axpy(), ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::obj_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::ConicApproximationModel< Real >::workspace_, and ROL::ConicApproximationModel< Real >::x_.
invHessVec() [2/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::invHessVec (V & hv, const V & v, const V & x, Real & tol) inline override virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 98 of file step/trustregion/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::Vector< Real >::axpy(), ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::ConicApproximationModel< Real >::workspace_, and ROL::ConicApproximationModel< Real >::x_.
precond() [2/2]
template<class Real > virtual void ROL::ConicApproximationModel< Real >::precond (V & Pv, const V & v, const V & x, Real & tol) inline override virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 109 of file step/trustregion/ROL_ConicApproximationModel.hpp.
References ROL::ConicApproximationModel< Real >::a_, ROL::Vector< Real >::axpy(), ROL::ConicApproximationModel< Real >::gamma_, ROL::ConicApproximationModel< Real >::obj_, ROL::ConicApproximationModel< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::ConicApproximationModel< Real >::workspace_, and ROL::ConicApproximationModel< Real >::x_.
Member Data Documentation
obj_
template<class Real > Ptr< Obj > ConicApproximationModel::obj_ private
Definition at line 38 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ConicApproximationModel< Real >::precond(), and ROL::ConicApproximationModel< Real >::update().
x_
template<class Real > const Ptr< const V > ConicApproximationModel::x_ private
Definition at line 39 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ConicApproximationModel< Real >::precond(), and ROL::ConicApproximationModel< Real >::update().
a_
template<class Real > const Ptr< const V > ConicApproximationModel::a_ private
Definition at line 39 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), ROL::ConicApproximationModel< Real >::gradient(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ConicApproximationModel< Real >::precond(), and ROL::ConicApproximationModel< Real >::update().
g_
template<class Real > Ptr< V > ConicApproximationModel::g_ private
Definition at line 40 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), ROL::ConicApproximationModel< Real >::gradient(), and ROL::ConicApproximationModel< Real >::value().
s_
template<class Real > Ptr< V > ConicApproximationModel::s_ private
Definition at line 40 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), ROL::ConicApproximationModel< Real >::gradient(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ConicApproximationModel< Real >::precond(), ROL::ConicApproximationModel< Real >::update(), and ROL::ConicApproximationModel< Real >::value().
Hs_
template<class Real > Ptr< V > ConicApproximationModel::Hs_ private
Definition at line 40 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), ROL::ConicApproximationModel< Real >::gradient(), and ROL::ConicApproximationModel< Real >::update().
f_
template<class Real > Real ConicApproximationModel::f_ private
Definition at line 41 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), and ROL::ConicApproximationModel< Real >::value().
gamma_
template<class Real > Real ConicApproximationModel::gamma_ private
Definition at line 41 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::ConicApproximationModel(), ROL::ConicApproximationModel< Real >::gradient(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::ConicApproximationModel< Real >::invHessVec(), ROL::ConicApproximationModel< Real >::precond(), ROL::ConicApproximationModel< Real >::update(), and ROL::ConicApproximationModel< Real >::value().
sHs_
template<class Real > Real ConicApproximationModel::sHs_ private
Definition at line 41 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::value().
workspace_
template<class Real > VectorWorkspace< Real > ConicApproximationModel::workspace_ private
Definition at line 43 of file algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp.
Referenced by ROL::ConicApproximationModel< Real >::gradient(), ROL::ConicApproximationModel< Real >::hessVec(), ROL::ConicApproximationModel< Real >::invHessVec(), and ROL::ConicApproximationModel< Real >::precond().
The documentation for this class was generated from the following files:
algorithm/TypeU/trustregion/other/ROL_ConicApproximationModel.hpp
step/trustregion/ROL_ConicApproximationModel.hpp