ROL: ROL::TrustRegionModel_U< Real > Class Template Reference
ROL::TrustRegionModel_U< Real > Class Template Reference
User Interface » Functional Interface
Provides the interface to evaluate trust-region model functions.
#include <ROL_TrustRegionModel_U.hpp>
Public Member Functions
virtual ~TrustRegionModel_U ()
TrustRegionModel_U (ParameterList &list, const Ptr< Secant< Real > > &secant=nullPtr, ESecantMode mode=SECANTMODE_BOTH)
void initialize (const Vector< Real > &x, const Vector< Real > &g)
void validate (Objective< Real > &obj, const Vector< Real > &x, const Vector< Real > &g, ETrustRegionU etr)
virtual void setData (Objective< Real > &obj, const Vector< Real > &x, const Vector< Real > &g, Real &tol)
void update (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &gold, const Vector< Real > &gnew, const Real snorm, const int iter)
virtual Real value (const Vector< Real > &s, Real &tol) override
Compute value.
virtual void gradient (Vector< Real > &g, const Vector< Real > &s, Real &tol) override
Compute gradient.
virtual void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &s, Real &tol) override
Apply Hessian approximation to vector.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &s, Real &tol) override
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &s, Real &tol) override
Apply preconditioner to vector.
virtual const Ptr< const Vector< Real > > getGradient (void) const
virtual const Ptr< const Vector< Real > > getIterate (void) const
virtual const Ptr< Objective< Real > > getObjective (void) const
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Protected Member Functions
void applyHessian (Vector< Real > &hv, const Vector< Real > &v, Real &tol)
void applyInvHessian (Vector< Real > &hv, const Vector< Real > &v, Real &tol)
void applyPrecond (Vector< Real > &Pv, const Vector< Real > &v, Real &tol)
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Private Attributes
Ptr< Objective< Real > > obj_
Ptr< const Vector< Real > > x_
Ptr< const Vector< Real > > g_
Ptr< Vector< Real > > dual_
Real tol_
Ptr< Secant< Real > > secant_
bool useSecantPrecond_
bool useSecantHessVec_
Detailed Description
template<typename Real>
class ROL::TrustRegionModel_U< Real >
Provides the interface to evaluate trust-region model functions.
ROL::TrustRegionModel_U provides the interface to implement a number of trust-region models for unconstrained and constrained optimization. The default implementation is the standard quadratic trust region model for unconstrained optimization.
Definition at line 32 of file ROL_TrustRegionModel_U.hpp.
Constructor & Destructor Documentation
~TrustRegionModel_U()
template<typename Real > virtual ROL::TrustRegionModel_U< Real >::~TrustRegionModel_U () inline virtual
Definition at line 79 of file ROL_TrustRegionModel_U.hpp.
TrustRegionModel_U()
template<typename Real > ROL::TrustRegionModel_U< Real >::TrustRegionModel_U (ParameterList & list, const Ptr< Secant< Real > > & secant = nullPtr, ESecantMode mode = SECANTMODE_BOTH) inline
Definition at line 81 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::secant_, ROL::TrustRegionModel_U< Real >::useSecantHessVec_, and ROL::TrustRegionModel_U< Real >::useSecantPrecond_.
Member Function Documentation
applyHessian()
template<typename Real > void ROL::TrustRegionModel_U< Real >::applyHessian (Vector< Real > & hv, const Vector< Real > & v, Real & tol) inline protected
Definition at line 47 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::obj_, ROL::TrustRegionModel_U< Real >::secant_, ROL::TrustRegionModel_U< Real >::tol_, ROL::TrustRegionModel_U< Real >::useSecantHessVec_, and ROL::TrustRegionModel_U< Real >::x_.
Referenced by ROL::TrustRegionModel_U< Real >::gradient(), ROL::TrustRegionModel_U< Real >::hessVec(), and ROL::TrustRegionModel_U< Real >::value().
applyInvHessian()
template<typename Real > void ROL::TrustRegionModel_U< Real >::applyInvHessian (Vector< Real > & hv, const Vector< Real > & v, Real & tol) inline protected
Definition at line 56 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::obj_, ROL::TrustRegionModel_U< Real >::secant_, ROL::TrustRegionModel_U< Real >::tol_, ROL::TrustRegionModel_U< Real >::useSecantHessVec_, and ROL::TrustRegionModel_U< Real >::x_.
Referenced by ROL::TrustRegionModel_U< Real >::invHessVec().
applyPrecond()
template<typename Real > void ROL::TrustRegionModel_U< Real >::applyPrecond (Vector< Real > & Pv, const Vector< Real > & v, Real & tol) inline protected
Definition at line 65 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::obj_, ROL::TrustRegionModel_U< Real >::secant_, ROL::TrustRegionModel_U< Real >::tol_, ROL::TrustRegionModel_U< Real >::useSecantPrecond_, and ROL::TrustRegionModel_U< Real >::x_.
Referenced by ROL::TrustRegionModel_U< Real >::precond().
initialize()
template<typename Real > void ROL::TrustRegionModel_U< Real >::initialize (const Vector< Real > & x, const Vector< Real > & g) inline
Definition at line 91 of file ROL_TrustRegionModel_U.hpp.
References ROL::Vector< Real >::clone(), and ROL::TrustRegionModel_U< Real >::dual_.
validate()
template<typename Real > void ROL::TrustRegionModel_U< Real >::validate (Objective< Real > & obj, const Vector< Real > & x, const Vector< Real > & g, ETrustRegionU etr) inline
Definition at line 99 of file ROL_TrustRegionModel_U.hpp.
References ROL::Vector< Real >::clone(), ROL::Objective< Real >::invHessVec(), ROL::TRUSTREGION_U_DOGLEG, ROL::TRUSTREGION_U_DOUBLEDOGLEG, and ROL::TrustRegionModel_U< Real >::useSecantHessVec_.
setData()
template<typename Real > virtual void ROL::TrustRegionModel_U< Real >::setData (Objective< Real > & obj, const Vector< Real > & x, const Vector< Real > & g, Real & tol) inline virtual
Definition at line 117 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::g_, ROL::TrustRegionModel_U< Real >::obj_, ROL::TrustRegionModel_U< Real >::tol_, and ROL::TrustRegionModel_U< Real >::x_.
Referenced by ROL::TRUtils::initialRadius().
update()
template<typename Real > void ROL::TrustRegionModel_U< Real >::update (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & gold, const Vector< Real > & gnew, const Real snorm, const int iter) inline
Definition at line 127 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::secant_, ROL::TrustRegionModel_U< Real >::useSecantHessVec_, and ROL::TrustRegionModel_U< Real >::useSecantPrecond_.
value()
template<typename Real > virtual Real ROL::TrustRegionModel_U< Real >::value (const Vector< Real > & x, Real & tol) inline override virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 138 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::applyHessian(), ROL::TrustRegionModel_U< Real >::dual_, and ROL::TrustRegionModel_U< Real >::g_.
gradient()
template<typename Real > virtual void ROL::TrustRegionModel_U< Real >::gradient (Vector< Real > & g, const Vector< Real > & x, Real & tol) inline override virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 145 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::applyHessian(), ROL::TrustRegionModel_U< Real >::g_, and ROL::Vector< Real >::plus().
hessVec()
template<typename Real > virtual void ROL::TrustRegionModel_U< Real >::hessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline override virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 150 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::applyHessian().
Referenced by ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::ColemanLiAlgorithm< Real >::applyHessian(), ROL::TypeB::LinMoreAlgorithm< Real >::dcauchy(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dcauchy(), ROL::TypeP::TrustRegionAlgorithm< Real >::dcauchy(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LinMoreAlgorithm< Real >::dprsrch(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg_simple(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg(), ROL::TypeP::TrustRegionAlgorithm< Real >::dspg2(), ROL::TRUtils::initialRadius(), ROL::CauchyPoint_U< Real >::solve(), ROL::DogLeg_U< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::SPGTrustRegion_U< Real >::solve(), and ROL::TruncatedCG_U< Real >::solve().
invHessVec()
template<typename Real > virtual void ROL::TrustRegionModel_U< Real >::invHessVec (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline override virtual
Apply inverse Hessian approximation to vector.
This function applies the inverse Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the action of the inverse Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 154 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::applyInvHessian().
Referenced by ROL::DogLeg_U< Real >::solve(), and ROL::DoubleDogLeg_U< Real >::solve().
precond()
template<typename Real > virtual void ROL::TrustRegionModel_U< Real >::precond (Vector< Real > & Pv, const Vector< Real > & v, const Vector< Real > & x, Real & tol) inline override virtual
Apply preconditioner to vector.
This function applies a preconditioner for the Hessian of the objective function to the vector \(v\).
Parameters
[out] Pv is the action of the Hessian preconditioner on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 158 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::applyPrecond().
Referenced by ROL::TypeB::KelleySachsAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::ColemanLiAlgorithm< Real >::applyPrecond(), and ROL::TruncatedCG_U< Real >::solve().
getGradient()
template<typename Real > virtual const Ptr< const Vector< Real > > ROL::TrustRegionModel_U< Real >::getGradient (void) const inline virtual
Definition at line 168 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::g_.
Referenced by ROL::CauchyPoint_U< Real >::solve(), ROL::DogLeg_U< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::SPGTrustRegion_U< Real >::solve(), and ROL::TruncatedCG_U< Real >::solve().
getIterate()
template<typename Real > virtual const Ptr< const Vector< Real > > ROL::TrustRegionModel_U< Real >::getIterate (void) const inline virtual
Definition at line 172 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::x_.
getObjective()
template<typename Real > virtual const Ptr< Objective< Real > > ROL::TrustRegionModel_U< Real >::getObjective (void) const inline virtual
Definition at line 176 of file ROL_TrustRegionModel_U.hpp.
References ROL::TrustRegionModel_U< Real >::obj_.
Member Data Documentation
obj_
template<typename Real > Ptr<Objective<Real> > ROL::TrustRegionModel_U< Real >::obj_ private
Definition at line 34 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::applyHessian(), ROL::TrustRegionModel_U< Real >::applyInvHessian(), ROL::TrustRegionModel_U< Real >::applyPrecond(), ROL::TrustRegionModel_U< Real >::getObjective(), and ROL::TrustRegionModel_U< Real >::setData().
x_
template<typename Real > Ptr<const Vector<Real> > ROL::TrustRegionModel_U< Real >::x_ private
Definition at line 35 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::applyHessian(), ROL::TrustRegionModel_U< Real >::applyInvHessian(), ROL::TrustRegionModel_U< Real >::applyPrecond(), ROL::TrustRegionModel_U< Real >::getIterate(), and ROL::TrustRegionModel_U< Real >::setData().
g_
template<typename Real > Ptr<const Vector<Real> > ROL::TrustRegionModel_U< Real >::g_ private
Definition at line 35 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::getGradient(), ROL::TrustRegionModel_U< Real >::gradient(), ROL::TrustRegionModel_U< Real >::setData(), and ROL::TrustRegionModel_U< Real >::value().
dual_
template<typename Real > Ptr<Vector<Real> > ROL::TrustRegionModel_U< Real >::dual_ private
Definition at line 36 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::initialize(), and ROL::TrustRegionModel_U< Real >::value().
tol_
template<typename Real > Real ROL::TrustRegionModel_U< Real >::tol_ private
Definition at line 37 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::applyHessian(), ROL::TrustRegionModel_U< Real >::applyInvHessian(), ROL::TrustRegionModel_U< Real >::applyPrecond(), and ROL::TrustRegionModel_U< Real >::setData().
secant_
template<typename Real > Ptr<Secant<Real> > ROL::TrustRegionModel_U< Real >::secant_ private
Definition at line 39 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::applyHessian(), ROL::TrustRegionModel_U< Real >::applyInvHessian(), ROL::TrustRegionModel_U< Real >::applyPrecond(), ROL::TrustRegionModel_U< Real >::TrustRegionModel_U(), and ROL::TrustRegionModel_U< Real >::update().
useSecantPrecond_
template<typename Real > bool ROL::TrustRegionModel_U< Real >::useSecantPrecond_ private
Definition at line 40 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::applyPrecond(), ROL::TrustRegionModel_U< Real >::TrustRegionModel_U(), and ROL::TrustRegionModel_U< Real >::update().
useSecantHessVec_
template<typename Real > bool ROL::TrustRegionModel_U< Real >::useSecantHessVec_ private
Definition at line 41 of file ROL_TrustRegionModel_U.hpp.
Referenced by ROL::TrustRegionModel_U< Real >::applyHessian(), ROL::TrustRegionModel_U< Real >::applyInvHessian(), ROL::TrustRegionModel_U< Real >::TrustRegionModel_U(), ROL::TrustRegionModel_U< Real >::update(), and ROL::TrustRegionModel_U< Real >::validate().
The documentation for this class was generated from the following file:
ROL_TrustRegionModel_U.hpp