ROL: ROL::SROMGenerator< Real > Class Template Reference
ROL::SROMGenerator< Real > Class Template Reference
#include <ROL_SROMGenerator.hpp>
Public Member Functions
SROMGenerator (ROL::ParameterList &parlist, const Ptr< BatchManager< Real > > &bman, const std::vector< Ptr< Distribution< Real > > > &dist, std::ostream &outStream=std::cout)
void refine (void)
Public Member Functions inherited from ROL::SampleGenerator< Real >
virtual ~SampleGenerator ()
SampleGenerator (const ROL::Ptr< BatchManager< Real > > &bman)
SampleGenerator (const SampleGenerator< Real > &sampler)
virtual void update (const Vector< Real > &x)
virtual int start (void)
virtual Real computeError (std::vector< Real > &vals)
virtual Real computeError (std::vector< ROL::Ptr< Vector< Real > > > &vals, const Vector< Real > &x)
virtual void setSamples (bool inConstructor=false)
virtual int numMySamples (void) const
virtual std::vector< Real > getMyPoint (const int i) const
virtual Real getMyWeight (const int i) const
int batchID (void) const
int numBatches (void) const
void sumAll (Real *input, Real *output, int dim) const
void sumAll (Vector< Real > &input, Vector< Real > &output) const
void broadcast (Real *input, int cnt, int root) const
void barrier (void) const
const ROL::Ptr< BatchManager< Real > > getBatchManager (void) const
void print (const std::string &filename="samples", const int prec=12) const
Private Member Functions
void pruneSamples (const ProbabilityVector< Real > &prob, const AtomVector< Real > &atom)
void get_scaling_vectors (std::vector< Real > &typw, std::vector< Real > &typx) const
void initialize_vectors (Ptr< ProbabilityVector< Real > > &prob, Ptr< ProbabilityVector< Real > > &prob_lo, Ptr< ProbabilityVector< Real > > &prob_hi, Ptr< ProbabilityVector< Real > > &prob_eq, Ptr< AtomVector< Real > > &atom, Ptr< AtomVector< Real > > &atom_lo, Ptr< AtomVector< Real > > &atom_hi, Ptr< AtomVector< Real > > &atom_eq, Ptr< Vector< Real > > &vec, Ptr< Vector< Real > > &vec_lo, Ptr< Vector< Real > > &vec_hi, Ptr< Vector< Real > > &vec_eq, const Ptr< BatchManager< Real > > &bman) const
Ptr< Objective< Real > > initialize_objective (const std::vector< Ptr< Distribution< Real > > > &dist, const Ptr< BatchManager< Real > > &bman, const bool optProb, const bool optAtom, ROL::ParameterList &list) const
int numGlobalSamples (void) const
Private Attributes
ROL::ParameterList parlist_
std::vector< Ptr< Distribution< Real > > > dist_
const int dimension_
int numSamples_
int numMySamples_
int numNewSamples_
bool adaptive_
Real ptol_
Real atol_
Additional Inherited Members
Protected Member Functions inherited from ROL::SampleGenerator< Real >
void setPoints (std::vector< std::vector< Real > > &p)
void setWeights (std::vector< Real > &w)
Detailed Description
template<class Real>
class ROL::SROMGenerator< Real >
Definition at line 27 of file ROL_SROMGenerator.hpp.
Constructor & Destructor Documentation
SROMGenerator()
template<class Real > ROL::SROMGenerator< Real >::SROMGenerator (ROL::ParameterList & parlist, const Ptr< BatchManager< Real > > & bman, const std::vector< Ptr< Distribution< Real > > > & dist, std::ostream & outStream = std::cout) inline
Definition at line 102 of file ROL_SROMGenerator.hpp.
References ROL::SROMGenerator< Real >::adaptive_, ROL::SROMGenerator< Real >::atol_, ROL::OptimizationProblem< Real >::check(), ROL::SROMGenerator< Real >::initialize_objective(), ROL::SROMGenerator< Real >::initialize_vectors(), ROL::SROMGenerator< Real >::numMySamples_, ROL::SROMGenerator< Real >::numNewSamples_, ROL::SROMGenerator< Real >::numSamples_, ROL::SROMGenerator< Real >::pruneSamples(), ROL::SROMGenerator< Real >::ptol_, and ROL::OptimizationSolver< Real >::solve().
Member Function Documentation
pruneSamples()
template<class Real > void ROL::SROMGenerator< Real >::pruneSamples (const ProbabilityVector< Real > & prob, const AtomVector< Real > & atom) inline private
Definition at line 43 of file ROL_SROMGenerator.hpp.
References ROL::SROMGenerator< Real >::atol_, ROL::SROMGenerator< Real >::dimension_, ROL::AtomVector< Real >::getAtom(), ROL::ProbabilityVector< Real >::getProbability(), ROL::SROMGenerator< Real >::numMySamples_, ROL::SROMGenerator< Real >::ptol_, ROL::SampleGenerator< Real >::setPoints(), ROL::SampleGenerator< Real >::setWeights(), and ROL::SampleGenerator< Real >::sumAll().
Referenced by ROL::SROMGenerator< Real >::SROMGenerator().
refine()
template<class Real > void ROL::SROMGenerator< Real >::refine (void) inline virtual
Reimplemented from ROL::SampleGenerator< Real >.
Definition at line 149 of file ROL_SROMGenerator.hpp.
get_scaling_vectors()
template<class Real > void ROL::SROMGenerator< Real >::get_scaling_vectors (std::vector< Real > & typw, std::vector< Real > & typx) const inline private
Definition at line 153 of file ROL_SROMGenerator.hpp.
References ROL::SROMGenerator< Real >::dimension_, ROL::SROMGenerator< Real >::dist_, ROL::SROMGenerator< Real >::numMySamples_, and ROL::SROMGenerator< Real >::numSamples_.
Referenced by ROL::SROMGenerator< Real >::initialize_vectors().
initialize_vectors()
template<class Real > void ROL::SROMGenerator< Real >::initialize_vectors (Ptr< ProbabilityVector< Real > > & prob, Ptr< ProbabilityVector< Real > > & prob_lo, Ptr< ProbabilityVector< Real > > & prob_hi, Ptr< ProbabilityVector< Real > > & prob_eq, Ptr< AtomVector< Real > > & atom, Ptr< AtomVector< Real > > & atom_lo, Ptr< AtomVector< Real > > & atom_hi, Ptr< AtomVector< Real > > & atom_eq, Ptr< Vector< Real > > & vec, Ptr< Vector< Real > > & vec_lo, Ptr< Vector< Real > > & vec_hi, Ptr< Vector< Real > > & vec_eq, const Ptr< BatchManager< Real > > & bman) const inline private
Definition at line 169 of file ROL_SROMGenerator.hpp.
References ROL::SROMGenerator< Real >::dimension_, ROL::SROMGenerator< Real >::dist_, ROL::SROMGenerator< Real >::get_scaling_vectors(), ROL::SROMGenerator< Real >::numMySamples_, and ROL::SROMGenerator< Real >::numSamples_.
Referenced by ROL::SROMGenerator< Real >::SROMGenerator().
initialize_objective()
template<class Real > Ptr< Objective< Real > > ROL::SROMGenerator< Real >::initialize_objective (const std::vector< Ptr< Distribution< Real > > > & dist, const Ptr< BatchManager< Real > > & bman, const bool optProb, const bool optAtom, ROL::ParameterList & list) const inline private
Definition at line 237 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::SROMGenerator().
numGlobalSamples()
template<class Real > int ROL::SROMGenerator< Real >::numGlobalSamples (void) const inline private virtual
Reimplemented from ROL::SampleGenerator< Real >.
Definition at line 261 of file ROL_SROMGenerator.hpp.
References ROL::SROMGenerator< Real >::numSamples_.
Member Data Documentation
parlist_
template<class Real > ROL::ParameterList ROL::SROMGenerator< Real >::parlist_ private
Definition at line 30 of file ROL_SROMGenerator.hpp.
dist_
template<class Real > std::vector<Ptr<Distribution<Real> > > ROL::SROMGenerator< Real >::dist_ private
Definition at line 32 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::get_scaling_vectors(), and ROL::SROMGenerator< Real >::initialize_vectors().
dimension_
template<class Real > const int ROL::SROMGenerator< Real >::dimension_ private
Definition at line 34 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::get_scaling_vectors(), ROL::SROMGenerator< Real >::initialize_vectors(), and ROL::SROMGenerator< Real >::pruneSamples().
numSamples_
template<class Real > int ROL::SROMGenerator< Real >::numSamples_ private
Definition at line 35 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::get_scaling_vectors(), ROL::SROMGenerator< Real >::initialize_vectors(), ROL::SROMGenerator< Real >::numGlobalSamples(), and ROL::SROMGenerator< Real >::SROMGenerator().
numMySamples_
template<class Real > int ROL::SROMGenerator< Real >::numMySamples_ private
Definition at line 36 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::get_scaling_vectors(), ROL::SROMGenerator< Real >::initialize_vectors(), ROL::SROMGenerator< Real >::pruneSamples(), and ROL::SROMGenerator< Real >::SROMGenerator().
numNewSamples_
template<class Real > int ROL::SROMGenerator< Real >::numNewSamples_ private
Definition at line 37 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::SROMGenerator().
adaptive_
template<class Real > bool ROL::SROMGenerator< Real >::adaptive_ private
Definition at line 38 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::SROMGenerator().
ptol_
template<class Real > Real ROL::SROMGenerator< Real >::ptol_ private
Definition at line 40 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::pruneSamples(), and ROL::SROMGenerator< Real >::SROMGenerator().
atol_
template<class Real > Real ROL::SROMGenerator< Real >::atol_ private
Definition at line 41 of file ROL_SROMGenerator.hpp.
Referenced by ROL::SROMGenerator< Real >::pruneSamples(), and ROL::SROMGenerator< Real >::SROMGenerator().
The documentation for this class was generated from the following file:
ROL_SROMGenerator.hpp