ROL: Objective_BurgersControl< Real > Class Template Reference
Objective_BurgersControl< Real > Class Template Reference
#include <example_01.hpp>
Public Member Functions
Objective_BurgersControl (Real alpha=1.e-4, int nx=128)
void solve_state (std::vector< Real > &u, const std::vector< Real > &z, const std::vector< Real > &param)
void solve_adjoint (std::vector< Real > &p, const std::vector< Real > &u, const std::vector< Real > &param)
void solve_state_sensitivity (std::vector< Real > &v, const std::vector< Real > &u, const std::vector< Real > &z, const std::vector< Real > &param)
void solve_adjoint_sensitivity (std::vector< Real > &q, const std::vector< Real > &u, const std::vector< Real > &p, const std::vector< Real > &v, const std::vector< Real > &z, const std::vector< Real > &param)
Real value (const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient (ROL::Vector< Real > &g, const ROL::Vector< Real > &z, Real &tol)
Compute gradient.
void hessVec (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
Objective_BurgersControl (Real alpha=1.e-4, int nx=128)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Objective_BurgersControl (Real alpha=1.e-4, int nx=128, int nt=100, Real T=1.0)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > &fem, const ROL::Ptr< ROL::Vector< Real > > &ud, Real alpha=1.e-4)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Objective_BurgersControl (Real alpha=1.e-4, int nx=128)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > &fem, const ROL::Ptr< ROL::Vector< Real > > &ud, Real alpha=1.e-4)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > &fem, Real x=0.0)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > &fem, const ROL::Ptr< ROL::Vector< Real > > &ud, Real alpha=1.e-4)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Objective_BurgersControl (Real alpha=1.e-4, int nx=128)
Real value (const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute value.
void gradient_1 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to first component.
void gradient_2 (ROL::Vector< Real > &g, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Compute gradient with respect to second component.
void hessVec_11 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Apply Hessian approximation to vector.
void hessVec_12 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_21 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
void hessVec_22 (ROL::Vector< Real > &hv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &u, const ROL::Vector< Real > &z, Real &tol)
Public Member Functions inherited from ROL::Objective< Real >
virtual ~Objective ()
Objective ()
virtual Real dirDeriv (const Vector< Real > &x, const Vector< Real > &d, Real &tol)
Compute directional derivative.
virtual void invHessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply inverse Hessian approximation to vector.
virtual void precond (Vector< Real > &Pv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply preconditioner to vector.
virtual void prox (Vector< Real > &Pv, const Vector< Real > &v, Real t, Real &tol)
Compute the proximity operator.
virtual void proxJacVec (Vector< Real > &Jv, const Vector< Real > &v, const Vector< Real > &x, Real t, Real &tol)
Apply the Jacobian of the proximity operator.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference gradient check.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkGradient (const Vector< Real > &x, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference gradient check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
Finite-difference Hessian-applied-to-vector check.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< std::vector< Real > > checkHessVec (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
Finite-difference Hessian-applied-to-vector check with specified step sizes.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< Real > checkHessSym (const Vector< Real > &x, const Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &w, const bool printToStream=true, std::ostream &outStream=std::cout)
Hessian symmetry check.
virtual std::vector< std::vector< Real > > checkProxJacVec (const Vector< Real > &x, const Vector< Real > &v, Real t=Real(1), bool printToStream=true, std::ostream &outStream=std::cout, int numSteps=ROL_NUM_CHECKDERIV_STEPS)
Finite-difference proximity operator Jacobian-applied-to-vector check.
virtual void setParameter (const std::vector< Real > &param)
Public Member Functions inherited from ROL::Objective_SimOpt< Real >
virtual void update (const Vector< Real > &u, const Vector< Real > &z, bool flag=true, int iter=-1)
Update objective function.
u is an iterate, z is an iterate, flag = true if the iterate has changed, iter is the outer algorithm iterations count.
void update (const Vector< Real > &x, bool flag=true, int iter=-1)
Update objective function.
virtual void update (const Vector< Real > &u, const Vector< Real > &z, UpdateType type, int iter=-1)
void update (const Vector< Real > &x, UpdateType type, int iter=-1)
Update objective function.
Real value (const Vector< Real > &x, Real &tol)
Compute value.
void gradient (Vector< Real > &g, const Vector< Real > &x, Real &tol)
Compute gradient.
void hessVec (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &x, Real &tol)
Apply Hessian approximation to vector.
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkGradient_1 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &d, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkGradient_2 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &g, const Vector< Real > &d, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_11 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_12 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_21 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const bool printToStream=true, std::ostream &outStream=std::cout, const int numSteps=ROL_NUM_CHECKDERIV_STEPS, const int order=1)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream=true, std::ostream &outStream=std::cout, const int order=1)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const bool printToStream, std::ostream &outStream, const int numSteps, const int order)
std::vector< std::vector< Real > > checkHessVec_22 (const Vector< Real > &u, const Vector< Real > &z, const Vector< Real > &hv, const Vector< Real > &v, const std::vector< Real > &steps, const bool printToStream, std::ostream &outStream, const int order)
Private Types
typedef H1VectorPrimal< Real > PrimalStateVector
typedef H1VectorDual< Real > DualStateVector
typedef L2VectorPrimal< Real > PrimalControlVector
typedef L2VectorDual< Real > DualControlVector
typedef H1VectorPrimal< Real > PrimalStateVector
typedef H1VectorDual< Real > DualStateVector
typedef L2VectorPrimal< Real > PrimalControlVector
typedef L2VectorDual< Real > DualControlVector
typedef H1VectorPrimal< Real > PrimalStateVector
typedef H1VectorDual< Real > DualStateVector
typedef L2VectorPrimal< Real > PrimalControlVector
typedef L2VectorDual< Real > DualControlVector
typedef std::vector< Real >::size_type uint
typedef H1VectorPrimal< Real > PrimalStateVector
typedef H1VectorDual< Real > DualStateVector
typedef L2VectorPrimal< Real > PrimalControlVector
typedef L2VectorDual< Real > DualControlVector
Private Member Functions
Real evaluate_target (Real x)
Real compute_norm (const std::vector< Real > &r)
Real dot (const std::vector< Real > &x, const std::vector< Real > &y)
void update (std::vector< Real > &u, const std::vector< Real > &s, const Real alpha=1.0)
void scale (std::vector< Real > &u, const Real alpha=0.0)
void apply_mass (std::vector< Real > &Mu, const std::vector< Real > &u)
void compute_residual (std::vector< Real > &r, const std::vector< Real > &u, const std::vector< Real > &z, const std::vector< Real > &param)
void compute_pde_jacobian (std::vector< Real > &dl, std::vector< Real > &d, std::vector< Real > &du, const std::vector< Real > &u, const std::vector< Real > &param)
void add_pde_hessian (std::vector< Real > &r, const std::vector< Real > &u, const std::vector< Real > &p, const std::vector< Real > &s, Real alpha=1.0)
void linear_solve (std::vector< Real > &u, std::vector< Real > &dl, std::vector< Real > &d, std::vector< Real > &du, const std::vector< Real > &r, const bool transpose=false)
void run_newton (std::vector< Real > &u, const std::vector< Real > &z, const std::vector< Real > &param)
Real evaluate_target (Real x)
Real dot (const std::vector< Real > &x, const std::vector< Real > &y)
void apply_mass (std::vector< Real > &Mu, const std::vector< Real > &u)
Real evaluate_target (Real x)
Real dot (const std::vector< Real > &x, const std::vector< Real > &y)
void apply_mass (std::vector< Real > &Mu, const std::vector< Real > &u)
Real evaluate_target (Real x)
Real dot (const std::vector< Real > &x, const std::vector< Real > &y)
void apply_mass (std::vector< Real > &Mu, const std::vector< Real > &u)
Real evaluate_target (Real x)
Real dot (const std::vector< Real > &x, const std::vector< Real > &y)
void apply_mass (std::vector< Real > &Mu, const std::vector< Real > &u)
Private Attributes
Real alpha_
int nx_
Real dx_
unsigned nx_
unsigned nt_
Real dt_
Real T_
ROL::Ptr< BurgersFEM< Real > > fem_
ROL::Ptr< ROL::Vector< Real > > ud_
ROL::Ptr< ROL::Vector< Real > > diff_
Real x_
std::vector< int > indices_
Additional Inherited Members
Protected Member Functions inherited from ROL::Objective< Real >
const std::vector< Real > getParameter (void) const
Detailed Description
template<class Real>
class Objective_BurgersControl< Real >
Definition at line 20 of file burgers-control/example_01.hpp.
Member Typedef Documentation
PrimalStateVector [1/4]
template<class Real > typedef H1VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalStateVector private
Definition at line 1044 of file example_04.hpp.
DualStateVector [1/4]
template<class Real > typedef H1VectorDual<Real> Objective_BurgersControl< Real >::DualStateVector private
Definition at line 1045 of file example_04.hpp.
PrimalControlVector [1/4]
template<class Real > typedef L2VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalControlVector private
Definition at line 1047 of file example_04.hpp.
DualControlVector [1/4]
template<class Real > typedef L2VectorDual<Real> Objective_BurgersControl< Real >::DualControlVector private
Definition at line 1048 of file example_04.hpp.
PrimalStateVector [2/4]
template<class Real > typedef H1VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalStateVector private
Definition at line 1101 of file example_06.hpp.
DualStateVector [2/4]
template<class Real > typedef H1VectorDual<Real> Objective_BurgersControl< Real >::DualStateVector private
Definition at line 1102 of file example_06.hpp.
PrimalControlVector [2/4]
template<class Real > typedef L2VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalControlVector private
Definition at line 1104 of file example_06.hpp.
DualControlVector [2/4]
template<class Real > typedef L2VectorDual<Real> Objective_BurgersControl< Real >::DualControlVector private
Definition at line 1105 of file example_06.hpp.
PrimalStateVector [3/4]
template<class Real > typedef H1VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalStateVector private
Definition at line 1107 of file example_07.hpp.
DualStateVector [3/4]
template<class Real > typedef H1VectorDual<Real> Objective_BurgersControl< Real >::DualStateVector private
Definition at line 1108 of file example_07.hpp.
PrimalControlVector [3/4]
template<class Real > typedef L2VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalControlVector private
Definition at line 1110 of file example_07.hpp.
DualControlVector [3/4]
template<class Real > typedef L2VectorDual<Real> Objective_BurgersControl< Real >::DualControlVector private
Definition at line 1111 of file example_07.hpp.
uint
template<class Real > typedef std::vector<Real>::size_type Objective_BurgersControl< Real >::uint private
Definition at line 1113 of file example_07.hpp.
PrimalStateVector [4/4]
template<class Real > typedef H1VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalStateVector private
Definition at line 905 of file example_08.hpp.
DualStateVector [4/4]
template<class Real > typedef H1VectorDual<Real> Objective_BurgersControl< Real >::DualStateVector private
Definition at line 906 of file example_08.hpp.
PrimalControlVector [4/4]
template<class Real > typedef L2VectorPrimal<Real> Objective_BurgersControl< Real >::PrimalControlVector private
Definition at line 908 of file example_08.hpp.
DualControlVector [4/4]
template<class Real > typedef L2VectorDual<Real> Objective_BurgersControl< Real >::DualControlVector private
Definition at line 909 of file example_08.hpp.
Constructor & Destructor Documentation
Objective_BurgersControl() [1/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (Real alpha = 1.e-4, int nx = 128) inline
Definition at line 237 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::dx_.
Objective_BurgersControl() [2/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (Real alpha = 1.e-4, int nx = 128) inline
Definition at line 397 of file burgers-control/example_02.hpp.
References Objective_BurgersControl< Real >::dx_.
Objective_BurgersControl() [3/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (Real alpha = 1.e-4, int nx = 128, int nt = 100, Real T = 1.0) inline
Definition at line 771 of file example_03.hpp.
References Objective_BurgersControl< Real >::dt_, and Objective_BurgersControl< Real >::dx_.
Objective_BurgersControl() [4/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > & fem, const ROL::Ptr< ROL::Vector< Real > > & ud, Real alpha = 1.e-4) inline
Definition at line 1056 of file example_04.hpp.
References Objective_BurgersControl< Real >::diff_, and Objective_BurgersControl< Real >::ud_.
Objective_BurgersControl() [5/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (Real alpha = 1.e-4, int nx = 128) inline
Definition at line 422 of file example_05.hpp.
References Objective_BurgersControl< Real >::dx_.
Objective_BurgersControl() [6/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > & fem, const ROL::Ptr< ROL::Vector< Real > > & ud, Real alpha = 1.e-4) inline
Definition at line 1113 of file example_06.hpp.
References Objective_BurgersControl< Real >::diff_, and Objective_BurgersControl< Real >::ud_.
Objective_BurgersControl() [7/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > & fem, Real x = 0.0) inline
Definition at line 1121 of file example_07.hpp.
References Objective_BurgersControl< Real >::fem_, Objective_BurgersControl< Real >::indices_, and Objective_BurgersControl< Real >::x_.
Objective_BurgersControl() [8/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (const ROL::Ptr< BurgersFEM< Real > > & fem, const ROL::Ptr< ROL::Vector< Real > > & ud, Real alpha = 1.e-4) inline
Definition at line 917 of file example_08.hpp.
References Objective_BurgersControl< Real >::diff_, and Objective_BurgersControl< Real >::ud_.
Objective_BurgersControl() [9/9]
template<class Real > Objective_BurgersControl< Real >::Objective_BurgersControl (Real alpha = 1.e-4, int nx = 128) inline
Definition at line 424 of file example_10.hpp.
References Objective_BurgersControl< Real >::dx_.
Member Function Documentation
evaluate_target() [1/5]
template<class Real > Real Objective_BurgersControl< Real >::evaluate_target (Real x) inline private
Definition at line 30 of file burgers-control/example_01.hpp.
Referenced by Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::solve_adjoint(), Objective_BurgersControl< Real >::value(), and Objective_BurgersControl< Real >::value().
compute_norm()
template<class Real > Real Objective_BurgersControl< Real >::compute_norm (const std::vector< Real > & r) inline private
Definition at line 42 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::dot().
Referenced by Objective_BurgersControl< Real >::run_newton().
dot() [1/5]
template<class Real > Real Objective_BurgersControl< Real >::dot (const std::vector< Real > & x, const std::vector< Real > & y) inline private
Definition at line 46 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::compute_norm(), Objective_BurgersControl< Real >::value(), and Objective_BurgersControl< Real >::value().
update()
template<class Real > void Objective_BurgersControl< Real >::update (std::vector< Real > & u, const std::vector< Real > & s, const Real alpha = 1.0) inline private
Definition at line 65 of file burgers-control/example_01.hpp.
Referenced by Objective_BurgersControl< Real >::run_newton().
scale()
template<class Real > void Objective_BurgersControl< Real >::scale (std::vector< Real > & u, const Real alpha = 0.0) inline private
Definition at line 71 of file burgers-control/example_01.hpp.
Referenced by Objective_BurgersControl< Real >::solve_adjoint_sensitivity().
apply_mass() [1/5]
template<class Real > void Objective_BurgersControl< Real >::apply_mass (std::vector< Real > & Mu, const std::vector< Real > & u) inline private
Definition at line 77 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::gradient_2(), Objective_BurgersControl< Real >::hessVec_11(), Objective_BurgersControl< Real >::hessVec_22(), Objective_BurgersControl< Real >::solve_adjoint(), and Objective_BurgersControl< Real >::solve_adjoint_sensitivity().
compute_residual()
template<class Real > void Objective_BurgersControl< Real >::compute_residual (std::vector< Real > & r, const std::vector< Real > & u, const std::vector< Real > & z, const std::vector< Real > & param) inline private
Definition at line 93 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::run_newton().
compute_pde_jacobian()
template<class Real > void Objective_BurgersControl< Real >::compute_pde_jacobian (std::vector< Real > & dl, std::vector< Real > & d, std::vector< Real > & du, const std::vector< Real > & u, const std::vector< Real > & param) inline private
Definition at line 129 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::run_newton(), Objective_BurgersControl< Real >::solve_adjoint(), Objective_BurgersControl< Real >::solve_adjoint_sensitivity(), and Objective_BurgersControl< Real >::solve_state_sensitivity().
add_pde_hessian()
template<class Real > void Objective_BurgersControl< Real >::add_pde_hessian (std::vector< Real > & r, const std::vector< Real > & u, const std::vector< Real > & p, const std::vector< Real > & s, Real alpha = 1.0) inline private
Definition at line 157 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::solve_adjoint_sensitivity().
linear_solve()
template<class Real > void Objective_BurgersControl< Real >::linear_solve (std::vector< Real > & u, std::vector< Real > & dl, std::vector< Real > & d, std::vector< Real > & du, const std::vector< Real > & r, const bool transpose = false) inline private
Definition at line 170 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::run_newton(), Objective_BurgersControl< Real >::solve_adjoint(), Objective_BurgersControl< Real >::solve_adjoint_sensitivity(), and Objective_BurgersControl< Real >::solve_state_sensitivity().
run_newton()
template<class Real > void Objective_BurgersControl< Real >::run_newton (std::vector< Real > & u, const std::vector< Real > & z, const std::vector< Real > & param) inline private
Definition at line 188 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::compute_norm(), Objective_BurgersControl< Real >::compute_pde_jacobian(), Objective_BurgersControl< Real >::compute_residual(), Objective_BurgersControl< Real >::linear_solve(), and Objective_BurgersControl< Real >::update().
Referenced by Objective_BurgersControl< Real >::solve_state().
solve_state()
template<class Real > void Objective_BurgersControl< Real >::solve_state (std::vector< Real > & u, const std::vector< Real > & z, const std::vector< Real > & param) inline
Definition at line 241 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::run_newton().
Referenced by Objective_BurgersControl< Real >::gradient(), Objective_BurgersControl< Real >::hessVec(), main(), and Objective_BurgersControl< Real >::value().
solve_adjoint()
template<class Real > void Objective_BurgersControl< Real >::solve_adjoint (std::vector< Real > & p, const std::vector< Real > & u, const std::vector< Real > & param) inline
Definition at line 247 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::compute_pde_jacobian(), Objective_BurgersControl< Real >::evaluate_target(), Objective_BurgersControl< Real >::linear_solve(), and Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::gradient(), and Objective_BurgersControl< Real >::hessVec().
solve_state_sensitivity()
template<class Real > void Objective_BurgersControl< Real >::solve_state_sensitivity (std::vector< Real > & v, const std::vector< Real > & u, const std::vector< Real > & z, const std::vector< Real > & param) inline
Definition at line 267 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::compute_pde_jacobian(), Objective_BurgersControl< Real >::linear_solve(), and Objective_BurgersControl< Real >::nx_.
Referenced by Objective_BurgersControl< Real >::hessVec().
solve_adjoint_sensitivity()
template<class Real > void Objective_BurgersControl< Real >::solve_adjoint_sensitivity (std::vector< Real > & q, const std::vector< Real > & u, const std::vector< Real > & p, const std::vector< Real > & v, const std::vector< Real > & z, const std::vector< Real > & param) inline
Definition at line 286 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::add_pde_hessian(), Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::compute_pde_jacobian(), Objective_BurgersControl< Real >::linear_solve(), and Objective_BurgersControl< Real >::scale().
Referenced by Objective_BurgersControl< Real >::hessVec().
value() [1/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & x, Real & tol) inline virtual
Compute value.
This function returns the objective function value.
Parameters
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Implements ROL::Objective< Real >.
Definition at line 306 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::dot(), Objective_BurgersControl< Real >::evaluate_target(), Objective_BurgersControl< Real >::nx_, and Objective_BurgersControl< Real >::solve_state().
gradient()
template<class Real > void Objective_BurgersControl< Real >::gradient (ROL::Vector< Real > & g, const ROL::Vector< Real > & x, Real & tol) inline virtual
Compute gradient.
This function returns the objective function gradient.
Parameters
[out] g is the gradient.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
The default implementation is a finite-difference approximation based on the function value. This requires the definition of a basis \(\{\phi_i\}\) for the optimization vectors x and the definition of a basis \(\{\psi_j\}\) for the dual optimization vectors (gradient vectors g). The bases must be related through the Riesz map, i.e., \(R \{\phi_i\} = \{\psi_j\}\), and this must be reflected in the implementation of the ROL::Vector::dual() method.
Reimplemented from ROL::Objective< Real >.
Definition at line 338 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::solve_adjoint(), and Objective_BurgersControl< Real >::solve_state().
hessVec()
template<class Real > void Objective_BurgersControl< Real >::hessVec (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & x, Real & tol) inline virtual
Apply Hessian approximation to vector.
This function applies the Hessian of the objective function to the vector \(v\).
Parameters
[out] hv is the the action of the Hessian on \(v\).
[in] v is the direction vector.
[in] x is the current iterate.
[in] tol is a tolerance for inexact objective function computation.
Reimplemented from ROL::Objective< Real >.
Definition at line 375 of file burgers-control/example_01.hpp.
References Objective_BurgersControl< Real >::solve_adjoint(), Objective_BurgersControl< Real >::solve_adjoint_sensitivity(), Objective_BurgersControl< Real >::solve_state(), and Objective_BurgersControl< Real >::solve_state_sensitivity().
evaluate_target() [2/5]
template<class Real > Real Objective_BurgersControl< Real >::evaluate_target (Real x) inline private
Definition at line 347 of file burgers-control/example_02.hpp.
dot() [2/5]
template<class Real > Real Objective_BurgersControl< Real >::dot (const std::vector< Real > & x, const std::vector< Real > & y) inline private
Definition at line 359 of file burgers-control/example_02.hpp.
References Objective_BurgersControl< Real >::nx_.
apply_mass() [2/5]
template<class Real > void Objective_BurgersControl< Real >::apply_mass (std::vector< Real > & Mu, const std::vector< Real > & u) inline private
Definition at line 376 of file burgers-control/example_02.hpp.
References Objective_BurgersControl< Real >::nx_.
value() [2/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 401 of file burgers-control/example_02.hpp.
References Objective_BurgersControl< Real >::dot(), Objective_BurgersControl< Real >::evaluate_target(), and Objective_BurgersControl< Real >::nx_.
gradient_1() [1/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 430 of file burgers-control/example_02.hpp.
References Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::evaluate_target(), and Objective_BurgersControl< Real >::nx_.
gradient_2() [1/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 447 of file burgers-control/example_02.hpp.
hessVec_11() [1/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 470 of file burgers-control/example_02.hpp.
References Objective_BurgersControl< Real >::apply_mass().
hessVec_12() [1/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 481 of file burgers-control/example_02.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [1/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 486 of file burgers-control/example_02.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [1/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 491 of file burgers-control/example_02.hpp.
evaluate_target() [3/5]
template<class Real > Real Objective_BurgersControl< Real >::evaluate_target (Real x) inline private
Definition at line 721 of file example_03.hpp.
dot() [3/5]
template<class Real > Real Objective_BurgersControl< Real >::dot (const std::vector< Real > & x, const std::vector< Real > & y) inline private
Definition at line 733 of file example_03.hpp.
References Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
apply_mass() [3/5]
template<class Real > void Objective_BurgersControl< Real >::apply_mass (std::vector< Real > & Mu, const std::vector< Real > & u) inline private
Definition at line 750 of file example_03.hpp.
References Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
value() [3/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 777 of file example_03.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::dot(), Objective_BurgersControl< Real >::dt_, Objective_BurgersControl< Real >::dx_, Objective_BurgersControl< Real >::evaluate_target(), Objective_BurgersControl< Real >::nt_, and Objective_BurgersControl< Real >::nx_.
gradient_1() [2/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 807 of file example_03.hpp.
References Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::dt_, Objective_BurgersControl< Real >::dx_, Objective_BurgersControl< Real >::evaluate_target(), Objective_BurgersControl< Real >::nt_, and Objective_BurgersControl< Real >::nx_.
gradient_2() [2/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 828 of file example_03.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::dt_, Objective_BurgersControl< Real >::nt_, and Objective_BurgersControl< Real >::nx_.
hessVec_11() [2/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 849 of file example_03.hpp.
References Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::dt_, Objective_BurgersControl< Real >::nt_, and Objective_BurgersControl< Real >::nx_.
hessVec_12() [2/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 871 of file example_03.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [2/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 876 of file example_03.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [2/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 881 of file example_03.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::dt_, Objective_BurgersControl< Real >::nt_, and Objective_BurgersControl< Real >::nx_.
value() [4/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 1062 of file example_04.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::fem_, and L2VectorPrimal< Real >::getVector().
gradient_1() [3/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1077 of file example_04.hpp.
References Objective_BurgersControl< Real >::fem_, and L2VectorPrimal< Real >::getVector().
gradient_2() [3/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1092 of file example_04.hpp.
References Objective_BurgersControl< Real >::alpha_, and Objective_BurgersControl< Real >::fem_.
hessVec_11() [3/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1104 of file example_04.hpp.
References Objective_BurgersControl< Real >::fem_.
hessVec_12() [3/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1114 of file example_04.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [3/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1119 of file example_04.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [3/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1124 of file example_04.hpp.
References Objective_BurgersControl< Real >::alpha_, and Objective_BurgersControl< Real >::fem_.
evaluate_target() [4/5]
template<class Real > Real Objective_BurgersControl< Real >::evaluate_target (Real x) inline private
Definition at line 372 of file example_05.hpp.
dot() [4/5]
template<class Real > Real Objective_BurgersControl< Real >::dot (const std::vector< Real > & x, const std::vector< Real > & y) inline private
Definition at line 384 of file example_05.hpp.
References Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
apply_mass() [4/5]
template<class Real > void Objective_BurgersControl< Real >::apply_mass (std::vector< Real > & Mu, const std::vector< Real > & u) inline private
Definition at line 401 of file example_05.hpp.
References Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
value() [5/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 428 of file example_05.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::dot(), Objective_BurgersControl< Real >::dx_, Objective_BurgersControl< Real >::evaluate_target(), and Objective_BurgersControl< Real >::nx_.
gradient_1() [4/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 457 of file example_05.hpp.
References Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::dx_, Objective_BurgersControl< Real >::evaluate_target(), and Objective_BurgersControl< Real >::nx_.
gradient_2() [4/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 474 of file example_05.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
hessVec_11() [4/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 497 of file example_05.hpp.
References Objective_BurgersControl< Real >::apply_mass().
hessVec_12() [4/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 508 of file example_05.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [4/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 513 of file example_05.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [4/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 518 of file example_05.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
value() [6/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 1121 of file example_06.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::fem_, and L2VectorPrimal< Real >::getVector().
gradient_1() [5/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1136 of file example_06.hpp.
References Objective_BurgersControl< Real >::fem_, and L2VectorPrimal< Real >::getVector().
gradient_2() [5/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1151 of file example_06.hpp.
References Objective_BurgersControl< Real >::alpha_, and Objective_BurgersControl< Real >::fem_.
hessVec_11() [5/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1163 of file example_06.hpp.
References Objective_BurgersControl< Real >::fem_.
hessVec_12() [5/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1173 of file example_06.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [5/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1178 of file example_06.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [5/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1183 of file example_06.hpp.
References Objective_BurgersControl< Real >::alpha_, and Objective_BurgersControl< Real >::fem_.
value() [7/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 1132 of file example_07.hpp.
References Objective_BurgersControl< Real >::fem_, Objective_BurgersControl< Real >::indices_, and Objective_BurgersControl< Real >::x_.
gradient_1() [6/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1152 of file example_07.hpp.
References Objective_BurgersControl< Real >::fem_, Objective_BurgersControl< Real >::indices_, Objective_BurgersControl< Real >::x_, and ROL::Vector< Real >::zero().
gradient_2() [6/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1177 of file example_07.hpp.
References ROL::Vector< Real >::zero().
hessVec_11() [6/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1181 of file example_07.hpp.
References ROL::Vector< Real >::zero().
hessVec_12() [6/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1199 of file example_07.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [6/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1204 of file example_07.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [6/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 1209 of file example_07.hpp.
References ROL::Vector< Real >::zero().
value() [8/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 925 of file example_08.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::fem_, and L2VectorPrimal< Real >::getVector().
gradient_1() [7/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 940 of file example_08.hpp.
References Objective_BurgersControl< Real >::fem_, and L2VectorPrimal< Real >::getVector().
gradient_2() [7/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 955 of file example_08.hpp.
References Objective_BurgersControl< Real >::alpha_, and Objective_BurgersControl< Real >::fem_.
hessVec_11() [7/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 967 of file example_08.hpp.
References Objective_BurgersControl< Real >::fem_.
hessVec_12() [7/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 977 of file example_08.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [7/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 982 of file example_08.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [7/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 987 of file example_08.hpp.
References Objective_BurgersControl< Real >::alpha_, and Objective_BurgersControl< Real >::fem_.
evaluate_target() [5/5]
template<class Real > Real Objective_BurgersControl< Real >::evaluate_target (Real x) inline private
Definition at line 374 of file example_10.hpp.
dot() [5/5]
template<class Real > Real Objective_BurgersControl< Real >::dot (const std::vector< Real > & x, const std::vector< Real > & y) inline private
Definition at line 386 of file example_10.hpp.
References Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
apply_mass() [5/5]
template<class Real > void Objective_BurgersControl< Real >::apply_mass (std::vector< Real > & Mu, const std::vector< Real > & u) inline private
Definition at line 403 of file example_10.hpp.
References Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
value() [9/9]
template<class Real > Real Objective_BurgersControl< Real >::value (const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute value.
Implements ROL::Objective_SimOpt< Real >.
Definition at line 430 of file example_10.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::dot(), Objective_BurgersControl< Real >::dx_, Objective_BurgersControl< Real >::evaluate_target(), and Objective_BurgersControl< Real >::nx_.
gradient_1() [8/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_1 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to first component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 459 of file example_10.hpp.
References Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::dx_, Objective_BurgersControl< Real >::evaluate_target(), and Objective_BurgersControl< Real >::nx_.
gradient_2() [8/8]
template<class Real > void Objective_BurgersControl< Real >::gradient_2 (ROL::Vector< Real > & g, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Compute gradient with respect to second component.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 476 of file example_10.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
hessVec_11() [8/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_11 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Apply Hessian approximation to vector.
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 499 of file example_10.hpp.
References Objective_BurgersControl< Real >::apply_mass().
hessVec_12() [8/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_12 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 510 of file example_10.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [8/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_21 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 515 of file example_10.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [8/8]
template<class Real > void Objective_BurgersControl< Real >::hessVec_22 (ROL::Vector< Real > & hv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & u, const ROL::Vector< Real > & z, Real & tol) inline virtual
Reimplemented from ROL::Objective_SimOpt< Real >.
Definition at line 520 of file example_10.hpp.
References Objective_BurgersControl< Real >::alpha_, Objective_BurgersControl< Real >::dx_, and Objective_BurgersControl< Real >::nx_.
Member Data Documentation
alpha_
template<class Real > Real Objective_BurgersControl< Real >::alpha_ private
Definition at line 22 of file burgers-control/example_01.hpp.
Referenced by Objective_BurgersControl< Real >::gradient_2(), Objective_BurgersControl< Real >::hessVec_22(), and Objective_BurgersControl< Real >::value().
nx_ [1/2]
template<class Real > int Objective_BurgersControl< Real >::nx_ private
Definition at line 24 of file burgers-control/example_01.hpp.
Referenced by Objective_BurgersControl< Real >::add_pde_hessian(), Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::compute_pde_jacobian(), Objective_BurgersControl< Real >::compute_residual(), Objective_BurgersControl< Real >::dot(), Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::gradient_2(), Objective_BurgersControl< Real >::hessVec_11(), Objective_BurgersControl< Real >::hessVec_22(), Objective_BurgersControl< Real >::linear_solve(), Objective_BurgersControl< Real >::solve_adjoint(), Objective_BurgersControl< Real >::solve_state_sensitivity(), Objective_BurgersControl< Real >::value(), and Objective_BurgersControl< Real >::value().
dx_
template<class Real > Real Objective_BurgersControl< Real >::dx_ private
Definition at line 25 of file burgers-control/example_01.hpp.
Referenced by Objective_BurgersControl< Real >::apply_mass(), Objective_BurgersControl< Real >::compute_residual(), Objective_BurgersControl< Real >::dot(), Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::gradient_2(), Objective_BurgersControl< Real >::hessVec_22(), Objective_BurgersControl< Real >::Objective_BurgersControl(), Objective_BurgersControl< Real >::Objective_BurgersControl(), and Objective_BurgersControl< Real >::value().
nx_ [2/2]
template<class Real > unsigned Objective_BurgersControl< Real >::nx_ private
Definition at line 712 of file example_03.hpp.
nt_
template<class Real > unsigned Objective_BurgersControl< Real >::nt_ private
Definition at line 714 of file example_03.hpp.
Referenced by Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::gradient_2(), Objective_BurgersControl< Real >::hessVec_11(), Objective_BurgersControl< Real >::hessVec_22(), and Objective_BurgersControl< Real >::value().
dt_
template<class Real > Real Objective_BurgersControl< Real >::dt_ private
Definition at line 715 of file example_03.hpp.
Referenced by Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::gradient_2(), Objective_BurgersControl< Real >::hessVec_11(), Objective_BurgersControl< Real >::hessVec_22(), Objective_BurgersControl< Real >::Objective_BurgersControl(), and Objective_BurgersControl< Real >::value().
T_
template<class Real > Real Objective_BurgersControl< Real >::T_ private
Definition at line 716 of file example_03.hpp.
fem_
template<class Real > ROL::Ptr< BurgersFEM< Real > > Objective_BurgersControl< Real >::fem_ private
Definition at line 1051 of file example_04.hpp.
Referenced by Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::gradient_2(), Objective_BurgersControl< Real >::hessVec_11(), Objective_BurgersControl< Real >::hessVec_22(), Objective_BurgersControl< Real >::Objective_BurgersControl(), and Objective_BurgersControl< Real >::value().
ud_
template<class Real > ROL::Ptr< ROL::Vector< Real > > Objective_BurgersControl< Real >::ud_ private
Definition at line 1052 of file example_04.hpp.
Referenced by Objective_BurgersControl< Real >::Objective_BurgersControl().
diff_
template<class Real > ROL::Ptr< ROL::Vector< Real > > Objective_BurgersControl< Real >::diff_ private
Definition at line 1053 of file example_04.hpp.
Referenced by Objective_BurgersControl< Real >::Objective_BurgersControl().
x_
template<class Real > Real Objective_BurgersControl< Real >::x_ private
Definition at line 1117 of file example_07.hpp.
Referenced by Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::Objective_BurgersControl(), and Objective_BurgersControl< Real >::value().
indices_
template<class Real > std::vector<int> Objective_BurgersControl< Real >::indices_ private
Definition at line 1118 of file example_07.hpp.
Referenced by Objective_BurgersControl< Real >::gradient_1(), Objective_BurgersControl< Real >::Objective_BurgersControl(), and Objective_BurgersControl< Real >::value().
The documentation for this class was generated from the following files:
burgers-control/example_01.hpp
example_04.hpp
example_06.hpp
example_07.hpp
example_08.hpp
burgers-control/example_02.hpp
example_03.hpp
example_05.hpp
example_10.hpp