ROL: ROL::DoubleDogLeg< Real > Class Template Reference
ROL::DoubleDogLeg< Real > Class Template Reference
Provides interface for the double dog leg trust-region subproblem solver.
#include <ROL_DoubleDogLeg.hpp>
Public Member Functions
DoubleDogLeg (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g)
void run (Vector< Real > &s, Real &snorm, int &iflag, int &iter, const Real del, TrustRegionModel< Real > &model)
Public Member Functions inherited from ROL::TrustRegion< Real >
virtual ~TrustRegion ()
TrustRegion (ROL::ParameterList &parlist)
virtual void update (Vector< Real > &x, Real &fnew, Real &del, int &nfval, int &ngrad, ETrustRegionFlag &flagTR, const Vector< Real > &s, const Real snorm, const Real fold, const Vector< Real > &g, int iter, Objective< Real > &obj, BoundConstraint< Real > &bnd, TrustRegionModel< Real > &model)
void setPredictedReduction (const Real pRed)
Real getPredictedReduction (void) const
Private Attributes
ROL::Ptr< CauchyPoint< Real > > cpt_
ROL::Ptr< Vector< Real > > s_
ROL::Ptr< Vector< Real > > v_
ROL::Ptr< Vector< Real > > Hp_
Real pRed_
Detailed Description
template<class Real>
class ROL::DoubleDogLeg< Real >
Provides interface for the double dog leg trust-region subproblem solver.
Definition at line 23 of file ROL_DoubleDogLeg.hpp.
Constructor & Destructor Documentation
DoubleDogLeg()
template<class Real > ROL::DoubleDogLeg< Real >::DoubleDogLeg (ROL::ParameterList & parlist) inline
Definition at line 37 of file ROL_DoubleDogLeg.hpp.
References ROL::DoubleDogLeg< Real >::cpt_.
Member Function Documentation
initialize()
template<class Real > void ROL::DoubleDogLeg< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g) inline virtual
Reimplemented from ROL::TrustRegion< Real >.
Definition at line 41 of file ROL_DoubleDogLeg.hpp.
References ROL::Vector< Real >::clone(), ROL::DoubleDogLeg< Real >::cpt_, ROL::DoubleDogLeg< Real >::Hp_, ROL::TrustRegion< Real >::initialize(), ROL::DoubleDogLeg< Real >::s_, and ROL::DoubleDogLeg< Real >::v_.
run()
template<class Real > void ROL::DoubleDogLeg< Real >::run (Vector< Real > & s, Real & snorm, int & iflag, int & iter, const Real del, TrustRegionModel< Real > & model) inline virtual
Implements ROL::TrustRegion< Real >.
Definition at line 49 of file ROL_DoubleDogLeg.hpp.
References ROL::Vector< Real >::axpy(), ROL::DoubleDogLeg< Real >::cpt_, ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::TrustRegionModel< Real >::dualTransform(), ROL::TrustRegionModel< Real >::getGradient(), ROL::TrustRegionModel< Real >::hessVec(), ROL::DoubleDogLeg< Real >::Hp_, ROL::TrustRegionModel< Real >::invHessVec(), ROL::Vector< Real >::norm(), ROL::DoubleDogLeg< Real >::pRed_, ROL::TrustRegionModel< Real >::primalTransform(), ROL::DoubleDogLeg< Real >::s_, ROL::Vector< Real >::scale(), ROL::Vector< Real >::set(), ROL::TrustRegion< Real >::setPredictedReduction(), ROL::DoubleDogLeg< Real >::v_, and zero.
Member Data Documentation
cpt_
template<class Real > ROL::Ptr<CauchyPoint<Real> > ROL::DoubleDogLeg< Real >::cpt_ private
Definition at line 26 of file ROL_DoubleDogLeg.hpp.
Referenced by ROL::DoubleDogLeg< Real >::DoubleDogLeg(), ROL::DoubleDogLeg< Real >::initialize(), and ROL::DoubleDogLeg< Real >::run().
s_
template<class Real > ROL::Ptr<Vector<Real> > ROL::DoubleDogLeg< Real >::s_ private
Definition at line 28 of file ROL_DoubleDogLeg.hpp.
Referenced by ROL::DoubleDogLeg< Real >::initialize(), and ROL::DoubleDogLeg< Real >::run().
v_
template<class Real > ROL::Ptr<Vector<Real> > ROL::DoubleDogLeg< Real >::v_ private
Definition at line 29 of file ROL_DoubleDogLeg.hpp.
Referenced by ROL::DoubleDogLeg< Real >::initialize(), and ROL::DoubleDogLeg< Real >::run().
Hp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::DoubleDogLeg< Real >::Hp_ private
Definition at line 30 of file ROL_DoubleDogLeg.hpp.
Referenced by ROL::DoubleDogLeg< Real >::initialize(), and ROL::DoubleDogLeg< Real >::run().
pRed_
template<class Real > Real ROL::DoubleDogLeg< Real >::pRed_ private
Definition at line 32 of file ROL_DoubleDogLeg.hpp.
Referenced by ROL::DoubleDogLeg< Real >::run().
The documentation for this class was generated from the following file:
ROL_DoubleDogLeg.hpp