ROL: ROL::ProbabilityVector< Real > Class Template Reference
ROL::ProbabilityVector< Real > Class Template Reference
Provides the std::vector implementation of the ROL::Vector interface.
#include <ROL_ProbabilityVector.hpp>
Public Member Functions
ProbabilityVector (const ROL::Ptr< std::vector< Real > > &vec, const ROL::Ptr< BatchManager< Real > > &bman)
const Real getProbability (const int i) const
void setProbability (const int i, const Real wt)
int getNumMyAtoms (void) const
ROL::Ptr< Vector< Real > > clone (void) const
Clone to make a new (uninitialized) vector.
Public Member Functions inherited from ROL::BatchStdVector< Real >
BatchStdVector (const Ptr< std::vector< Real > > &vec, const Ptr< BatchManager< Real > > &bman)
virtual Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
int dimension (void) const
Return dimension of the vector space.
Real reduce (const Elementwise::ReductionOp< Real > &r) const
const Ptr< BatchManager< Real > > getBatchManager (void) const
Public Member Functions inherited from ROL::StdVector< Real, Element >
StdVector (const Ptr< std::vector< Element > > &std_vec)
StdVector (const int dim, const Element val=0.0)
StdVector (std::initializer_list< Element > ilist)
Real & operator[] (int i)
const Real & operator[] (int i) const
void set (const Vector< Real > &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void axpy (const Real alpha, const Vector< Real > &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
Ptr< const std::vector< Element > > getVector () const
Ptr< std::vector< Element > > getVector ()
Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
void applyUnary (const Elementwise::UnaryFunction< Real > &f)
void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector< Real > &x)
Real reduce (const Elementwise::ReductionOp< Real > &r) const
void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual void print (std::ostream &outStream) const
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void zero ()
Set to zero vector.
virtual const Vector & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
virtual Real apply (const Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Real >::size_type uint
Detailed Description
template<class Real>
class ROL::ProbabilityVector< Real >
Provides the std::vector implementation of the ROL::Vector interface.
Definition at line 29 of file ROL_ProbabilityVector.hpp.
Member Typedef Documentation
uint
template<class Real > typedef std::vector<Real>::size_type ROL::ProbabilityVector< Real >::uint private
Definition at line 30 of file ROL_ProbabilityVector.hpp.
Constructor & Destructor Documentation
ProbabilityVector()
template<class Real > ROL::ProbabilityVector< Real >::ProbabilityVector (const ROL::Ptr< std::vector< Real > > & vec, const ROL::Ptr< BatchManager< Real > > & bman) inline
Definition at line 32 of file ROL_ProbabilityVector.hpp.
Member Function Documentation
getProbability()
template<class Real > const Real ROL::ProbabilityVector< Real >::getProbability (const int i) const inline
Definition at line 36 of file ROL_ProbabilityVector.hpp.
References ROL::StdVector< Real, Element >::getVector().
Referenced by ROL::CDFObjective< Real >::gradientCDF(), ROL::CDFObjective< Real >::hessVecCDF(), ROL::MomentObjective< Real >::momentGradient(), ROL::MomentObjective< Real >::momentHessVec(), ROL::MomentObjective< Real >::momentValue(), ROL::SROMGenerator< Real >::pruneSamples(), and ROL::CDFObjective< Real >::valueCDF().
setProbability()
template<class Real > void ROL::ProbabilityVector< Real >::setProbability (const int i, const Real wt) inline
Definition at line 44 of file ROL_ProbabilityVector.hpp.
References ROL::StdVector< Real, Element >::getVector().
getNumMyAtoms()
template<class Real > int ROL::ProbabilityVector< Real >::getNumMyAtoms (void) const inline
Definition at line 52 of file ROL_ProbabilityVector.hpp.
References ROL::StdVector< Real, Element >::getVector().
Referenced by ROL::CDFObjective< Real >::gradientCDF(), ROL::CDFObjective< Real >::hessVecCDF(), ROL::MomentObjective< Real >::momentGradient(), ROL::MomentObjective< Real >::momentHessVec(), ROL::MomentObjective< Real >::momentValue(), and ROL::CDFObjective< Real >::valueCDF().
clone()
template<class Real > ROL::Ptr< Vector< Real > > ROL::ProbabilityVector< Real >::clone (void) const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Reimplemented from ROL::BatchStdVector< Real >.
Definition at line 57 of file ROL_ProbabilityVector.hpp.
References ROL::StdVector< Real, Element >::getVector().
The documentation for this class was generated from the following file:
ROL_ProbabilityVector.hpp