ROL: ConDualStdVector< Real, Element > Class Template Reference
ConDualStdVector< Real, Element > Class Template Reference
#include <example_02.hpp>
Public Member Functions
ConDualStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const ROL::Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const ROL::Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< ROL::Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< ROL::Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const ROL::Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Real apply (const ROL::Vector< Real > &x) const
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
ConDualStdVector (const ROL::Ptr< std::vector< Element > > &std_vec)
void plus (const Vector< Real > &x)
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
void scale (const Real alpha)
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
Real dot (const Vector< Real > &x) const
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
Real norm () const
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
ROL::Ptr< Vector< Real > > clone () const
Clone to make a new (uninitialized) vector.
ROL::Ptr< const std::vector< Element > > getVector () const
ROL::Ptr< std::vector< Element > > getVector ()
ROL::Ptr< Vector< Real > > basis (const int i) const
Return i-th basis vector.
int dimension () const
Return dimension of the vector space.
const Vector< Real > & dual () const
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Public Member Functions inherited from ROL::Vector< Real >
virtual ~Vector ()
virtual void axpy (const Real alpha, const Vector &x)
Compute \(y \leftarrow \alpha x + y\) where \(y = \mathtt{*this}\).
virtual void zero ()
Set to zero vector.
virtual void set (const Vector &x)
Set \(y \leftarrow x\) where \(y = \mathtt{*this}\).
virtual void applyUnary (const Elementwise::UnaryFunction< Real > &f)
virtual void applyBinary (const Elementwise::BinaryFunction< Real > &f, const Vector &x)
virtual Real reduce (const Elementwise::ReductionOp< Real > &r) const
virtual void print (std::ostream &outStream) const
virtual void setScalar (const Real C)
Set \(y \leftarrow C\) where \(C\in\mathbb{R}\).
virtual void randomize (const Real l=0.0, const Real u=1.0)
Set vector to be uniform random between [l,u].
virtual std::vector< Real > checkVector (const Vector< Real > &x, const Vector< Real > &y, const bool printToStream=true, std::ostream &outStream=std::cout) const
Verify vector-space methods.
Private Types
typedef std::vector< Element > vector
typedef ROL::Vector< Real > V
typedef vector::size_type uint
typedef std::vector< Element > vector
typedef vector::size_type uint
Private Attributes
ROL::Ptr< std::vector< Element > > std_vec_
ROL::Ptr< ConStdVector< Real > > dual_vec_
Detailed Description
template<class Real, class Element>
class ConDualStdVector< Real, Element >
Definition at line 340 of file gross-pitaevskii/example_02.hpp.
Member Typedef Documentation
vector [1/2]
template<class Real , class Element > typedef std::vector<Element> ConDualStdVector< Real, Element >::vector private
Definition at line 322 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
V
template<class Real , class Element > typedef ROL::Vector<Real> ConDualStdVector< Real, Element >::V private
Definition at line 323 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
uint [1/2]
template<class Real , class Element > typedef vector::size_type ConDualStdVector< Real, Element >::uint private
Definition at line 324 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
vector [2/2]
template<class Real , class Element > typedef std::vector<Element> ConDualStdVector< Real, Element >::vector private
Definition at line 342 of file gross-pitaevskii/example_02.hpp.
uint [2/2]
template<class Real , class Element > typedef vector::size_type ConDualStdVector< Real, Element >::uint private
Definition at line 343 of file gross-pitaevskii/example_02.hpp.
Constructor & Destructor Documentation
ConDualStdVector() [1/2]
template<class Real , class Element > ConDualStdVector< Real, Element >::ConDualStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 333 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
ConDualStdVector() [2/2]
template<class Real , class Element > ConDualStdVector< Real, Element >::ConDualStdVector (const ROL::Ptr< std::vector< Element > > & std_vec) inline
Definition at line 352 of file gross-pitaevskii/example_02.hpp.
Member Function Documentation
plus() [1/2]
template<class Real , class Element > void ConDualStdVector< Real, Element >::plus (const ROL::Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 335 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::dimension(), ConDualStdVector< Real, Element >::getVector(), and ConDualStdVector< Real, Element >::std_vec_.
scale() [1/2]
template<class Real , class Element > void ConDualStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 344 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::dimension(), and ConDualStdVector< Real, Element >::std_vec_.
dot() [1/2]
template<class Real , class Element > Real ConDualStdVector< Real, Element >::dot (const ROL::Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 351 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::dimension(), ConDualStdVector< Real, Element >::getVector(), and ConDualStdVector< Real, Element >::std_vec_.
Referenced by ConDualStdVector< Real, Element >::norm().
norm() [1/2]
template<class Real , class Element > Real ConDualStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 362 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::dot().
clone() [1/2]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > ConDualStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 368 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::std_vec_.
getVector() [1/4]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > ConDualStdVector< Real, Element >::getVector () const inline
Definition at line 372 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::std_vec_.
Referenced by ConDualStdVector< Real, Element >::apply(), ConDualStdVector< Real, Element >::dot(), ConDualStdVector< Real, Element >::dot(), ConDualStdVector< Real, Element >::plus(), and ConDualStdVector< Real, Element >::plus().
getVector() [2/4]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > ConDualStdVector< Real, Element >::getVector () inline
Definition at line 376 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::std_vec_.
basis() [1/2]
template<class Real , class Element > ROL::Ptr< ROL::Vector< Real > > ConDualStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 380 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::std_vec_.
dimension() [1/2]
template<class Real , class Element > int ConDualStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 388 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::std_vec_.
Referenced by ConDualStdVector< Real, Element >::apply(), ConDualStdVector< Real, Element >::dot(), ConDualStdVector< Real, Element >::dot(), ConDualStdVector< Real, Element >::plus(), ConDualStdVector< Real, Element >::plus(), and ConDualStdVector< Real, Element >::scale().
dual() [1/2]
template<class Real , class Element > const ROL::Vector< Real > & ConDualStdVector< Real, Element >::dual (void) const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 390 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::dual_vec_.
apply()
template<class Real , class Element > Real ConDualStdVector< Real, Element >::apply (const ROL::Vector< Real > & x) const inline virtual
Apply \(\mathtt{*this}\) to a dual vector. This is equivalent to the call \(\mathtt{this->dot(x.dual())}\).
Parameters
[in] x is a vector
Returns
The number equal to \(\langle \mathtt{*this}, x \rangle\).
Reimplemented from ROL::Vector< Real >.
Definition at line 395 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
References ConDualStdVector< Real, Element >::dimension(), ConDualStdVector< Real, Element >::getVector(), and ConDualStdVector< Real, Element >::std_vec_.
plus() [2/2]
template<class Real , class Element > void ConDualStdVector< Real, Element >::plus (const Vector< Real > & x) inline virtual
Compute \(y \leftarrow y + x\), where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector to be added to \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \mathtt{*this} + x\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 354 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::dimension(), ConDualStdVector< Real, Element >::getVector(), and ConDualStdVector< Real, Element >::std_vec_.
scale() [2/2]
template<class Real , class Element > void ConDualStdVector< Real, Element >::scale (const Real alpha) inline virtual
Compute \(y \leftarrow \alpha y\) where \(y = \mathtt{*this}\).
   @param[in]      alpha is the scaling of \f$\mathtt{*this}\f$.
   On return \f$\mathtt{*this} = \alpha (\mathtt{*this}) \f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 363 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::dimension(), and ConDualStdVector< Real, Element >::std_vec_.
dot() [2/2]
template<class Real , class Element > Real ConDualStdVector< Real, Element >::dot (const Vector< Real > & x) const inline virtual
Compute \(\langle y,x \rangle \) where \(y = \mathtt{*this}\).
   @param[in]      x  is the vector that forms the dot product with \f$\mathtt{*this}\f$.
   @return         The number equal to \f$\langle \mathtt{*this}, x \rangle\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 370 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::dimension(), ConDualStdVector< Real, Element >::getVector(), and ConDualStdVector< Real, Element >::std_vec_.
norm() [2/2]
template<class Real , class Element > Real ConDualStdVector< Real, Element >::norm () const inline virtual
Returns \(\| y \| \) where \(y = \mathtt{*this}\).
   @return         A nonnegative number equal to the norm of \f$\mathtt{*this}\f$.
   ---
Implements ROL::Vector< Real >.
Definition at line 381 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::dot().
clone() [2/2]
template<class Real , class Element > ROL::Ptr< Vector< Real > > ConDualStdVector< Real, Element >::clone () const inline virtual
Clone to make a new (uninitialized) vector.
   @return         A reference-counted pointer to the cloned vector.
   Provides the means of allocating temporary memory in ROL.
   ---
Implements ROL::Vector< Real >.
Definition at line 387 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::std_vec_.
getVector() [3/4]
template<class Real , class Element > ROL::Ptr< const std::vector< Element > > ConDualStdVector< Real, Element >::getVector () const inline
Definition at line 391 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::std_vec_.
getVector() [4/4]
template<class Real , class Element > ROL::Ptr< std::vector< Element > > ConDualStdVector< Real, Element >::getVector () inline
Definition at line 395 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::std_vec_.
basis() [2/2]
template<class Real , class Element > ROL::Ptr< Vector< Real > > ConDualStdVector< Real, Element >::basis (const int i) const inline virtual
Return i-th basis vector.
   @param[in] i is the index of the basis function.
   @return A reference-counted pointer to the basis vector with index @b i.
   Overloading the basis is only required if the default gradient implementation
   is used, which computes a finite-difference approximation.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 399 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::std_vec_.
dimension() [2/2]
template<class Real , class Element > int ConDualStdVector< Real, Element >::dimension (void) const inline virtual
Return dimension of the vector space.
   @return The dimension of the vector space, i.e., the total number of basis vectors.
   Overload if the basis is overloaded.
   ---
Reimplemented from ROL::Vector< Real >.
Definition at line 406 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::std_vec_.
dual() [2/2]
template<class Real , class Element > const Vector< Real > & ConDualStdVector< Real, Element >::dual () const inline virtual
Return dual representation of \(\mathtt{*this}\), for example, the result of applying a Riesz map, or change of basis, or change of memory layout.
Returns
A const reference to dual representation.
By default, returns the current object. Please overload if you need a dual representation.
Reimplemented from ROL::Vector< Real >.
Definition at line 408 of file gross-pitaevskii/example_02.hpp.
References ConDualStdVector< Real, Element >::dual_vec_.
Member Data Documentation
std_vec_
template<class Real , class Element > ROL::Ptr< std::vector< Element > > ConDualStdVector< Real, Element >::std_vec_ private
Definition at line 328 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
Referenced by ConDualStdVector< Real, Element >::apply(), ConDualStdVector< Real, Element >::basis(), ConDualStdVector< Real, Element >::clone(), ConDualStdVector< Real, Element >::dimension(), ConDualStdVector< Real, Element >::dot(), ConDualStdVector< Real, Element >::dot(), ConDualStdVector< Real, Element >::getVector(), ConDualStdVector< Real, Element >::getVector(), ConDualStdVector< Real, Element >::plus(), ConDualStdVector< Real, Element >::plus(), and ConDualStdVector< Real, Element >::scale().
dual_vec_
template<class Real , class Element > ROL::Ptr< ConStdVector< Real > > ConDualStdVector< Real, Element >::dual_vec_ mutable private
Definition at line 329 of file dual-spaces/simple-eq-constr-1/example_01.cpp.
Referenced by ConDualStdVector< Real, Element >::dual().
The documentation for this class was generated from the following files:
dual-spaces/simple-eq-constr-1/example_01.cpp
gross-pitaevskii/example_02.hpp