ROL: ROL::TruncatedCG< Real > Class Template Reference
ROL::TruncatedCG< Real > Class Template Reference
Provides interface for truncated CG trust-region subproblem solver.
#include <ROL_TruncatedCG.hpp>
Public Member Functions
TruncatedCG (ROL::ParameterList &parlist)
void initialize (const Vector< Real > &x, const Vector< Real > &s, const Vector< Real > &g)
void run (Vector< Real > &s, Real &snorm, int &iflag, int &iter, const Real del, TrustRegionModel< Real > &model)
Public Member Functions inherited from ROL::TrustRegion< Real >
virtual ~TrustRegion ()
TrustRegion (ROL::ParameterList &parlist)
virtual void update (Vector< Real > &x, Real &fnew, Real &del, int &nfval, int &ngrad, ETrustRegionFlag &flagTR, const Vector< Real > &s, const Real snorm, const Real fold, const Vector< Real > &g, int iter, Objective< Real > &obj, BoundConstraint< Real > &bnd, TrustRegionModel< Real > &model)
void setPredictedReduction (const Real pRed)
Real getPredictedReduction (void) const
Private Attributes
ROL::Ptr< Vector< Real > > primalVector_
ROL::Ptr< Vector< Real > > s_
ROL::Ptr< Vector< Real > > g_
ROL::Ptr< Vector< Real > > v_
ROL::Ptr< Vector< Real > > p_
ROL::Ptr< Vector< Real > > Hp_
int maxit_
Real tol1_
Real tol2_
Real pRed_
Detailed Description
template<class Real>
class ROL::TruncatedCG< Real >
Provides interface for truncated CG trust-region subproblem solver.
Definition at line 23 of file ROL_TruncatedCG.hpp.
Constructor & Destructor Documentation
TruncatedCG()
template<class Real > ROL::TruncatedCG< Real >::TruncatedCG (ROL::ParameterList & parlist) inline
Definition at line 42 of file ROL_TruncatedCG.hpp.
References ROL::TruncatedCG< Real >::maxit_, ROL::TruncatedCG< Real >::tol1_, and ROL::TruncatedCG< Real >::tol2_.
Member Function Documentation
initialize()
template<class Real > void ROL::TruncatedCG< Real >::initialize (const Vector< Real > & x, const Vector< Real > & s, const Vector< Real > & g) inline virtual
Reimplemented from ROL::TrustRegion< Real >.
Definition at line 50 of file ROL_TruncatedCG.hpp.
References ROL::Vector< Real >::clone(), ROL::TruncatedCG< Real >::g_, ROL::TruncatedCG< Real >::Hp_, ROL::TrustRegion< Real >::initialize(), ROL::TruncatedCG< Real >::p_, ROL::TruncatedCG< Real >::primalVector_, ROL::TruncatedCG< Real >::s_, and ROL::TruncatedCG< Real >::v_.
run()
template<class Real > void ROL::TruncatedCG< Real >::run (Vector< Real > & s, Real & snorm, int & iflag, int & iter, const Real del, TrustRegionModel< Real > & model) inline virtual
Implements ROL::TrustRegion< Real >.
Definition at line 62 of file ROL_TruncatedCG.hpp.
References ROL::Vector< Real >::axpy(), ROL::TrustRegionModel< Real >::dualTransform(), ROL::TruncatedCG< Real >::g_, ROL::TrustRegionModel< Real >::getGradient(), ROL::TrustRegionModel< Real >::hessVec(), ROL::TruncatedCG< Real >::Hp_, ROL::TruncatedCG< Real >::maxit_, ROL::Vector< Real >::norm(), ROL::TruncatedCG< Real >::p_, ROL::TrustRegionModel< Real >::precond(), ROL::TruncatedCG< Real >::pRed_, ROL::TrustRegionModel< Real >::primalTransform(), ROL::TruncatedCG< Real >::s_, ROL::Vector< Real >::set(), ROL::TrustRegion< Real >::setPredictedReduction(), ROL::TruncatedCG< Real >::tol1_, ROL::TruncatedCG< Real >::tol2_, ROL::TruncatedCG< Real >::v_, zero, and ROL::Vector< Real >::zero().
Member Data Documentation
primalVector_
template<class Real > ROL::Ptr<Vector<Real> > ROL::TruncatedCG< Real >::primalVector_ private
Definition at line 25 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::initialize().
s_
template<class Real > ROL::Ptr<Vector<Real> > ROL::TruncatedCG< Real >::s_ private
Definition at line 27 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::initialize(), and ROL::TruncatedCG< Real >::run().
g_
template<class Real > ROL::Ptr<Vector<Real> > ROL::TruncatedCG< Real >::g_ private
Definition at line 28 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::initialize(), and ROL::TruncatedCG< Real >::run().
v_
template<class Real > ROL::Ptr<Vector<Real> > ROL::TruncatedCG< Real >::v_ private
Definition at line 29 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::initialize(), and ROL::TruncatedCG< Real >::run().
p_
template<class Real > ROL::Ptr<Vector<Real> > ROL::TruncatedCG< Real >::p_ private
Definition at line 30 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::initialize(), and ROL::TruncatedCG< Real >::run().
Hp_
template<class Real > ROL::Ptr<Vector<Real> > ROL::TruncatedCG< Real >::Hp_ private
Definition at line 31 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::initialize(), and ROL::TruncatedCG< Real >::run().
maxit_
template<class Real > int ROL::TruncatedCG< Real >::maxit_ private
Definition at line 33 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::run(), and ROL::TruncatedCG< Real >::TruncatedCG().
tol1_
template<class Real > Real ROL::TruncatedCG< Real >::tol1_ private
Definition at line 34 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::run(), and ROL::TruncatedCG< Real >::TruncatedCG().
tol2_
template<class Real > Real ROL::TruncatedCG< Real >::tol2_ private
Definition at line 35 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::run(), and ROL::TruncatedCG< Real >::TruncatedCG().
pRed_
template<class Real > Real ROL::TruncatedCG< Real >::pRed_ private
Definition at line 37 of file ROL_TruncatedCG.hpp.
Referenced by ROL::TruncatedCG< Real >::run().
The documentation for this class was generated from the following file:
ROL_TruncatedCG.hpp