ROL: example_04.cpp File Reference
example_04.cpp File Reference
Shows how to solve a steady Burgers' optimal control problem using full-space methods.
#include "ROL_Algorithm.hpp"
#include "ROL_MoreauYosidaPenaltyStep.hpp"
#include "ROL_BoundConstraint_SimOpt.hpp"
#include "ROL_Vector_SimOpt.hpp"
#include "ROL_ParameterList.hpp"
#include "ROL_Stream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include <iostream>
#include <algorithm>
#include "example_04.hpp"
Typedefs
typedef double RealT
typedef H1VectorPrimal< RealT > PrimalStateVector
typedef H1VectorDual< RealT > DualStateVector
typedef L2VectorPrimal< RealT > PrimalControlVector
typedef L2VectorDual< RealT > DualControlVector
typedef H1VectorDual< RealT > PrimalConstraintVector
typedef H1VectorPrimal< RealT > DualConstraintVector
Functions
int main (int argc, char *argv[])
Detailed Description
Shows how to solve a steady Burgers' optimal control problem using full-space methods.
Definition in file example_04.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 29 of file example_04.cpp.
PrimalStateVector
typedef H1VectorPrimal<RealT> PrimalStateVector
Definition at line 30 of file example_04.cpp.
DualStateVector
typedef H1VectorDual<RealT> DualStateVector
Definition at line 31 of file example_04.cpp.
PrimalControlVector
typedef L2VectorPrimal<RealT> PrimalControlVector
Definition at line 32 of file example_04.cpp.
DualControlVector
typedef L2VectorDual<RealT> DualControlVector
Definition at line 33 of file example_04.cpp.
PrimalConstraintVector
typedef H1VectorDual<RealT> PrimalConstraintVector
Definition at line 34 of file example_04.cpp.
DualConstraintVector
typedef H1VectorPrimal<RealT> DualConstraintVector
Definition at line 35 of file example_04.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 37 of file example_04.cpp.
References Constraint_BurgersControl< Real >::applyInverseAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_1(), ROL::Constraint_SimOpt< Real >::checkAdjointConsistencyJacobian_2(), ROL::Constraint< Real >::checkApplyAdjointHessian(), ROL::Constraint< Real >::checkApplyJacobian(), ROL::Objective< Real >::checkGradient(), ROL::Objective< Real >::checkHessVec(), ROL::Constraint_SimOpt< Real >::checkInverseAdjointJacobian_1(), ROL::Constraint_SimOpt< Real >::checkInverseJacobian_1(), ROL::Constraint_SimOpt< Real >::checkSolve(), ROL::Vector_SimOpt< Real >::clone(), ROL::Vector_SimOpt< Real >::norm(), ROL::Algorithm< Real >::run(), Constraint_BurgersControl< Real >::solve(), and ROL::Vector< Real >::zero().