ROL: example_08.cpp File Reference
example_08.cpp File Reference
#include "ROL_Algorithm.hpp"
#include "ROL_Reduced_Objective_SimOpt.hpp"
#include "ROL_MonteCarloGenerator.hpp"
#include "ROL_OptimizationSolver.hpp"
#include "ROL_ParameterList.hpp"
#include "ROL_Stream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "Teuchos_Comm.hpp"
#include "Teuchos_DefaultComm.hpp"
#include "Teuchos_CommHelpers.hpp"
#include <iostream>
#include <fstream>
#include <algorithm>
#include "example_08.hpp"
Typedefs
typedef double RealT
typedef H1VectorPrimal< RealT > PrimalStateVector
typedef H1VectorDual< RealT > DualStateVector
typedef L2VectorPrimal< RealT > PrimalControlVector
typedef L2VectorDual< RealT > DualControlVector
typedef H1VectorDual< RealT > PrimalConstraintVector
typedef H1VectorPrimal< RealT > DualConstraintVector
Functions
int main (int argc, char *argv[])
Typedef Documentation
RealT
typedef double RealT
Definition at line 34 of file example_08.cpp.
PrimalStateVector
typedef H1VectorPrimal<RealT> PrimalStateVector
Definition at line 35 of file example_08.cpp.
DualStateVector
typedef H1VectorDual<RealT> DualStateVector
Definition at line 36 of file example_08.cpp.
PrimalControlVector
typedef L2VectorPrimal<RealT> PrimalControlVector
Definition at line 37 of file example_08.cpp.
DualControlVector
typedef L2VectorDual<RealT> DualControlVector
Definition at line 38 of file example_08.cpp.
PrimalConstraintVector
typedef H1VectorDual<RealT> PrimalConstraintVector
Definition at line 39 of file example_08.cpp.
DualConstraintVector
typedef H1VectorPrimal<RealT> DualConstraintVector
Definition at line 40 of file example_08.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 42 of file example_08.cpp.
References ROL::OptimizationProblem< Real >::check(), dim, ROL::OptimizationProblem< Real >::getSolutionStatistic(), ROL::OptimizationProblem< Real >::setStochasticObjective(), and ROL::OptimizationSolver< Real >::solve().