ROL: test_17.cpp File Reference
test_17.cpp File Reference
Checks that Coleman-Li BoundConstraint functions agree across implementations.
#include "ROL_Stream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "ROL_Bounds.hpp"
#include "ROL_Constraint.hpp"
#include "ROL_StdBoundConstraint.hpp"
#include "ROL_StdVector.hpp"
#include "ROL_UnaryFunctions.hpp"
Typedefs
typedef double RealT
Functions
RealT calcError (ROL::Vector< RealT > &a, const ROL::Vector< RealT > &b)
int testRandomInputs (int numPoints, RealT tol, ROL::Ptr< std::ostream > outStream)
int testCases (RealT tol, ROL::Ptr< std::ostream > outStream)
int main (int argc, char *argv[])
Detailed Description
Checks that Coleman-Li BoundConstraint functions agree across implementations.
Definition in file function/test_17.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 24 of file function/test_17.cpp.
Function Documentation
calcError()
RealT calcError (ROL::Vector< RealT > & a, const ROL::Vector< RealT > & b)
Definition at line 26 of file function/test_17.cpp.
References ROL::Vector< Real >::applyUnary(), ROL::Vector< Real >::axpy(), and ROL::Vector< Real >::reduce().
Referenced by testCases(), and testRandomInputs().
testRandomInputs()
int testRandomInputs (int numPoints, RealT tol, ROL::Ptr< std::ostream > outStream)
Definition at line 33 of file function/test_17.cpp.
References ROL::Vector< Real >::applyBinary(), ROL::Bounds< Real >::applyInverseScalingFunction(), ROL::StdBoundConstraint< Real >::applyInverseScalingFunction(), ROL::Constraint< Real >::applyJacobian(), ROL::Bounds< Real >::applyScalingFunctionJacobian(), ROL::StdBoundConstraint< Real >::applyScalingFunctionJacobian(), ROL::StdVector< Real, Element >::applyUnary(), ROL::Vector< Real >::applyUnary(), ROL::StdVector< Real, Element >::axpy(), calcError(), ROL::Bounds< Real >::projectInterior(), ROL::StdVector< Real, Element >::randomize(), ROL::StdVector< Real, Element >::scale(), ROL::StdVector< Real, Element >::set(), ROL::StdVector< Real, Element >::setScalar(), and ROL::Constraint< Real >::value().
Referenced by main().
testCases()
int testCases (RealT tol, ROL::Ptr< std::ostream > outStream)
Definition at line 172 of file function/test_17.cpp.
References ROL::StdVector< Real, Element >::applyBinary(), ROL::Bounds< Real >::applyInverseScalingFunction(), ROL::StdBoundConstraint< Real >::applyInverseScalingFunction(), ROL::Bounds< Real >::applyScalingFunctionJacobian(), ROL::StdBoundConstraint< Real >::applyScalingFunctionJacobian(), and calcError().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 267 of file function/test_17.cpp.
References testCases(), and testRandomInputs().