ROL: test_13.cpp File Reference
test_13.cpp File Reference
Validate BinaryConstraint class.
#include "ROL_OptimizationSolver.hpp"
#include "ROL_BinaryConstraint.hpp"
#include "ROL_DiagonalOperator.hpp"
#include "ROL_QuadraticObjective.hpp"
#include "ROL_RandomVector.hpp"
#include "ROL_StdVector.hpp"
#include "ROL_Bounds.hpp"
#include "ROL_Stream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
Typedefs
typedef double RealT
Functions
template<class Real >
ROL::Ptr< ROL::Objective< Real > > createDiagonalQuadraticObjective (const ROL::Vector< Real > &a, const ROL::Vector< Real > &b)
int main (int argc, char *argv[])
Detailed Description
Validate BinaryConstraint class.
Solve a bound constrained problem where a solution is sought on the surface of the bounding set by converting the bound constraint into an equality constraint.
Definition in file function/test_13.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 49 of file function/test_13.cpp.
Function Documentation
createDiagonalQuadraticObjective()
template<class Real > ROL::Ptr< ROL::Objective< Real > > createDiagonalQuadraticObjective (const ROL::Vector< Real > & a, const ROL::Vector< Real > & b)
Definition at line 39 of file function/test_13.cpp.
References ROL::Vector< Real >::clone().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 51 of file function/test_13.cpp.
References ROL::OptimizationProblem< Real >::check(), createDiagonalQuadraticObjective(), ROL::RandomizeVector(), and ROL::OptimizationSolver< Real >::solve().