ROL: Linear Algebra Interface
Linear Algebra Interface
User Interface
ROL's linear algebra or vector space interface.
Classes
class ROL::ElementwiseVector< Real >
Intermediate abstract class which does not require users implements plus, set, scale, axpy, norm, dot, or zero if they implement the three elementwise functions: applyUnary, applyBinary, and reduce.
class ROL::InactiveSet_PrimalVector< Real >
Defines the a Vector which has a diagonally scaled dot product that neglects active set elements Used to simplify Semi-smooth Newton method implementation.
class ROL::PartitionedVector< Real >
Defines the linear algebra of vector space on a generic partitioned vector.
class ROL::PrimalScaledVector< Real >
Provides the implementation of the ROL::Vector interface that handles scalings in the inner product. A more generic version of ROL::PrimalScaledStdVector.
class ROL::DualScaledVector< Real >
Provides the implementation of the ROL::Vector interface that handles scalings in the inner product. A more generic version of ROL::PrimalScaledStdVector.
class ROL::Vector< Real >
Defines the linear algebra or vector space interface.
class ROL::Vector_SimOpt< Real >
Defines the linear algebra or vector space interface for simulation-based optimization.
class VectorClone
Container for wrapping a reusable cloned vector. Declaring an object of this type as a class member variable will decrease the number of clones needed as memory need only be allocated once in the lifetime of the host object. Verifies that member and argument types and dimensions agree when called.
class VectorCloneMap
Container for wrapping a collection of uniquely-named reusable cloned vectors, which in are stored in a map. Uses string-valued ids for keys by default.
class VectorWorkspace
Provides a "smart" cloning manager to be used a member variable in a class and called in the member function of the same class.
class WrappedVector
Provides an interface layer which encapulates a pointer to a ROL::Vector and has the default behavior of calling its member Ptr<Vector> object. Makes creating derived classes with this idiom simpler as they need only override the methods where the desired implementation differs from the member Ptr<Vector>. For example, vectors which have a diagonal scaling that defines their inner product and dual spaces can derive from this class need overload only the methods basis, clone, dual, and dot.
class ROL::SimulatedVector< Real >
Defines the linear algebra of a vector space on a generic partitioned vector where the individual vectors are distributed in batches defined by ROL::BatchManager. This is a batch-distributed version of ROL::PartitionedVector.
Functions
template<class Real >
void ROL::RandomizeVector (Vector< Real > &x, const Real &lower=0.0, const Real &upper=1.0)
Fill a ROL::Vector with uniformly-distributed random numbers in the interval [lower,upper].
template<class Real >
void ROL::RandomizeFeasibleVector (Vector< Real > &x, BoundConstraint< Real > &bnd)
Fill a ROL::Vector with uniformly-distributed random numbers which satisfy the supplied bound constraint.
Detailed Description
ROL's linear algebra or vector space interface.
Function Documentation
RandomizeVector()
template<class Real > void ROL::RandomizeVector (Vector< Real > & x, const Real & lower = 0.0, const Real & upper = 1.0)
Fill a ROL::Vector with uniformly-distributed random numbers in the interval [lower,upper].
\function RandomizeVector
\[ x_i \in \mathcal{U}(l,u)\;\forall\l i \]
Definition at line 30 of file ROL_RandomVector.hpp.
References ROL::Vector< Real >::applyUnary().
Referenced by main().
RandomizeFeasibleVector()
template<class Real > void ROL::RandomizeFeasibleVector (Vector< Real > & x, BoundConstraint< Real > & bnd)
Fill a ROL::Vector with uniformly-distributed random numbers which satisfy the supplied bound constraint.
\function RandomizeFeasibleVector
\[ x_i \in \mathcal{U}(l_i,u_i)\;\forall\l i \]
Definition at line 45 of file ROL_RandomVector.hpp.
References ROL::Vector< Real >::applyUnary(), ROL::Vector< Real >::axpy(), ROL::BoundConstraint< Real >::getLowerBound(), ROL::BoundConstraint< Real >::getUpperBound(), ROL::Vector< Real >::plus(), and ROL::Vector< Real >::set().