ROL: ROL::TypeB Namespace Reference
ROL::TypeB Namespace Reference
Classes
class Algorithm
Provides an interface to run bound constrained optimization algorithms.
struct AlgorithmState
class ColemanLiAlgorithm
Provides an interface to run the affine-scaling trust-region algorithm of Coleman and Li.
class GradientAlgorithm
Provides an interface to run the projected gradient algorithm.
class InteriorPointAlgorithm
Provides an interface to run the Moreau-Yosida algorithm.
class KelleySachsAlgorithm
Provides an interface to run the trust-region algorithm of Kelley and Sachs.
class LinMoreAlgorithm
Provides an interface to run the trust-region algorithm of Lin and More.
class LSecantBAlgorithm
Provides an interface to run the line-search algorithm of Byrd, Lu, Nocedal and Zhu (similar to L-BFGS-B).
class MoreauYosidaAlgorithm
Provides an interface to run the Moreau-Yosida algorithm.
class NewtonKrylovAlgorithm
Provides an interface to run the projected secant algorithm.
class PrimalDualActiveSetAlgorithm
Provides an interface to run the projected secant algorithm.
class QuasiNewtonAlgorithm
Provides an interface to run the projected secant algorithm.
class SpectralGradientAlgorithm
Provides an interface to run the spectral projected gradient algorithm.
class TrustRegionSPGAlgorithm
Provides an interface to run the trust-region algorithm.
Enumerations
enum EAlgorithmB {
ALGORITHM_B_LINESEARCH = 0 , ALGORITHM_B_TRUSTREGION , ALGORITHM_B_MOREAUYOSIDA , ALGORITHM_B_PRIMALDUALACTIVESET ,
ALGORITHM_B_INTERIORPOINT , ALGORITHM_B_SPECTRALGRADIENT , ALGORITHM_B_LAST
}
Functions
std::string EAlgorithmBToString (EAlgorithmB alg)
int isValidAlgorithmB (EAlgorithmB alg)
Verifies validity of a AlgorithmB enum.
EAlgorithmB & operator++ (EAlgorithmB &type)
EAlgorithmB operator++ (EAlgorithmB &type, int)
EAlgorithmB & operator-- (EAlgorithmB &type)
EAlgorithmB operator-- (EAlgorithmB &type, int)
EAlgorithmB StringToEAlgorithmB (std::string s)
template<typename Real >
Ptr< Algorithm< Real > > AlgorithmFactory (ParameterList &parlist, const Ptr< Secant< Real > > &secant=nullPtr)
Enumeration Type Documentation
EAlgorithmB
enum ROL::TypeB::EAlgorithmB
Enumerator
ALGORITHM_B_LINESEARCH
ALGORITHM_B_TRUSTREGION
ALGORITHM_B_MOREAUYOSIDA
ALGORITHM_B_PRIMALDUALACTIVESET
ALGORITHM_B_INTERIORPOINT
ALGORITHM_B_SPECTRALGRADIENT
ALGORITHM_B_LAST
Definition at line 40 of file ROL_TypeB_AlgorithmFactory.hpp.
Function Documentation
EAlgorithmBToString()
std::string ROL::TypeB::EAlgorithmBToString (EAlgorithmB alg) inline
Definition at line 50 of file ROL_TypeB_AlgorithmFactory.hpp.
References ALGORITHM_B_INTERIORPOINT, ALGORITHM_B_LAST, ALGORITHM_B_LINESEARCH, ALGORITHM_B_MOREAUYOSIDA, ALGORITHM_B_PRIMALDUALACTIVESET, ALGORITHM_B_SPECTRALGRADIENT, and ALGORITHM_B_TRUSTREGION.
Referenced by StringToEAlgorithmB().
isValidAlgorithmB()
int ROL::TypeB::isValidAlgorithmB (EAlgorithmB alg) inline
Verifies validity of a AlgorithmB enum.
Parameters
ls [in] - enum of the AlgorithmB
Returns
1 if the argument is a valid AlgorithmB; 0 otherwise.
Definition at line 70 of file ROL_TypeB_AlgorithmFactory.hpp.
References ALGORITHM_B_INTERIORPOINT, ALGORITHM_B_LAST, ALGORITHM_B_LINESEARCH, ALGORITHM_B_MOREAUYOSIDA, ALGORITHM_B_PRIMALDUALACTIVESET, ALGORITHM_B_SPECTRALGRADIENT, and ALGORITHM_B_TRUSTREGION.
operator++() [1/2]
EAlgorithmB & ROL::TypeB::operator++ (EAlgorithmB & type) inline
Definition at line 81 of file ROL_TypeB_AlgorithmFactory.hpp.
operator++() [2/2]
EAlgorithmB ROL::TypeB::operator++ (EAlgorithmB & type, int) inline
Definition at line 85 of file ROL_TypeB_AlgorithmFactory.hpp.
operator--() [1/2]
EAlgorithmB & ROL::TypeB::operator-- (EAlgorithmB & type) inline
Definition at line 91 of file ROL_TypeB_AlgorithmFactory.hpp.
operator--() [2/2]
EAlgorithmB ROL::TypeB::operator-- (EAlgorithmB & type, int) inline
Definition at line 95 of file ROL_TypeB_AlgorithmFactory.hpp.
StringToEAlgorithmB()
EAlgorithmB ROL::TypeB::StringToEAlgorithmB (std::string s) inline
Definition at line 101 of file ROL_TypeB_AlgorithmFactory.hpp.
References ALGORITHM_B_LAST, ALGORITHM_B_LINESEARCH, ALGORITHM_B_TRUSTREGION, EAlgorithmBToString(), and ROL::removeStringFormat().
Referenced by AlgorithmFactory().
AlgorithmFactory()
template<typename Real > Ptr< Algorithm< Real > > ROL::TypeB::AlgorithmFactory (ParameterList & parlist, const Ptr< Secant< Real > > & secant = nullPtr) inline
Definition at line 112 of file ROL_TypeB_AlgorithmFactory.hpp.
References ALGORITHM_B_INTERIORPOINT, ALGORITHM_B_LINESEARCH, ALGORITHM_B_MOREAUYOSIDA, ALGORITHM_B_PRIMALDUALACTIVESET, ALGORITHM_B_SPECTRALGRADIENT, ALGORITHM_B_TRUSTREGION, and StringToEAlgorithmB().