ROL: ROL Namespace Reference
ROL Namespace Reference
Namespaces
namespace details
namespace Exception
namespace Finite_Difference_Arrays
namespace InteriorPoint
namespace StringList
namespace TRUtils
namespace TypeB
namespace TypeE
namespace TypeG
namespace TypeP
namespace TypeU
namespace ZOO
Classes
class AbsoluteValue
class AffineTransformConstraint
Compose a constraint operator with an affine transformation, i.e.,.
class AffineTransformObjective
Compose an objective function with an affine transformation, i.e.,.
class Algorithm
Provides an interface to run optimization algorithms.
struct AlgorithmState
State for algorithm class. Will be used for restarts.
class AlmostSureConstraint
class Arcsine
class AtomVector
Provides the std::vector implementation of the ROL::Vector interface.
class AugmentedLagrangian
Provides the interface to evaluate the augmented Lagrangian.
class AugmentedLagrangian_SimOpt
Provides the interface to evaluate the SimOpt augmented Lagrangian.
class AugmentedLagrangianObjective
Provides the interface to evaluate the augmented Lagrangian.
class AugmentedLagrangianStep
Provides the interface to compute augmented Lagrangian steps.
class AugmentedSystemOperator
Apply the augmented system operator.
class AugmentedSystemPrecOperator
Implements a preconditioner for the augmented system.
class BackTracking
Implements a simple back tracking line search.
class BackTracking_U
Implements a simple back tracking line search.
class BallIndicatorObjective
Provides the interface to evaluate the indicator function of norm constraints.
class BatchManager
class BatchStdVector
Provides the std::vector implementation of the ROL::Vector interface.
class Beta
class BiCGSTAB
class BinaryConstraint
Implements an equality constraint function that evaluates to zero on the surface of a bounded parallelpiped and is positive in the interior.
class Bisection
Implements a bisection line search.
class BlockOperator
Provides the interface to apply a block operator to a partitioned vector.
class BlockOperator2
Provides the interface to apply a 2x2 block operator to a partitioned vector.
class BlockOperator2Determinant
class BlockOperator2Diagonal
Provides the interface to apply a 2x2 block diagonal operator to a partitioned vector.
class BlockOperator2UnitLower
Provides the interface to apply a 2x2 block unit lower operator to a partitioned vector.
class BlockOperator2UnitUpper
Provides the interface to apply a 2x2 block unit upper operator to a partitioned vector.
class BoundConstraint
Provides the interface to apply upper and lower bound constraints.
class BoundConstraint_Partitioned
A composite composite BoundConstraint formed from bound constraints on subvectors of a PartitionedVector.
class BoundConstraint_SimOpt
class BoundFletcher
class Bounds
Provides the elementwise interface to apply upper and lower bound constraints.
class BoundToConstraint
Provides an implementation for bound constraints.
class BPOE
Provides the implementation of the buffered probability of exceedance.
class Brents
Implements a Brent's method line search.
class BrentsProjection
class Bundle
Provides the interface for and implements a bundle.
class Bundle_AS
Provides the interface for and implements an active set bundle.
class Bundle_TT
Provides the interface for and implements a bundle. The semidefinite quadratic subproblem is solved using TT algorithm by Antonio Frangioni (1996).
class Bundle_U
Provides the interface for and implements a bundle.
class Bundle_U_AS
Provides the interface for and implements an active set bundle.
class Bundle_U_TT
Provides the interface for and implements a bundle. The semidefinite quadratic subproblem is solved using TT algorithm by Antonio Frangioni (1996).
class BundleStatusTest
class BundleStep
Provides the interface to compute bundle trust-region steps.
class Cauchy
class CauchyPoint_U
Provides interface for the Cauchy point trust-region subproblem solver.
class CDFObjective
class ChainRuleConstraint
Defines a constaint formed through function composition \(c(x)=c_o(c_i(x))\).
class ChainRuleObjective
Defines an objective of the form f(g(x)) where.
class ChebyshevSpectral
Provides an interface for the Chebyshev-Spectral risk measure.
class Chi2Divergence
Provides an interface for the chi-squared-divergence distributionally robust expectation.
class CoherentEntropicRisk
Provides the interface for the coherent entropic risk measure.
class ColemanLiModel
Provides the interface to evaluate interior trust-region model functions from the Coleman-Li bound constrained trust-region algorithm.
class CombinedStatusTest
Provides an interface to check two status tests of optimization algorithms.
class CompositeConstraint_SimOpt
Defines a composite equality constraint operator interface for simulation-based optimization.
class CompositeObjective
Provides the interface to evaluate composite objective functions.
class CompositeObjective_SimOpt
Provides the interface to evaluate simulation-based composite objective functions.
class CompositeStep
Implements the computation of optimization steps with composite-step trust-region methods.
class ConicApproximationModel
class ConjugateGradients
Provides definitions of the Conjugate Gradient solver.
class ConjugateResiduals
Provides definition of the Conjugate Residual solver.
class Constraint
Defines the general constraint operator interface.
class Constraint_DynamicState
class Constraint_Partitioned
Has both inequality and equality constraints. Treat inequality constraint as equality with slack variable.
class Constraint_SerialSimOpt
Unifies the constraint defined on a single time step that are defined through the Constraint_TimeSimOpt interface into a SimOpt constraint for all time. Primarily intended for use in testing the parallel-in-time implementation.
class Constraint_SimOpt
Defines the constraint operator interface for simulation-based optimization.
class Constraint_TimeSimOpt
Defines the time dependent constraint operator interface for simulation-based optimization.
class ConstraintAssembler
Provides a wrapper for multiple constraints.
struct ConstraintData
class ConstraintFromObjective
Creates a constraint from an objective function and a offset value.
class ConstraintManager
Provides a wrapper for multiple constraints.
class ConstraintStatusTest
Provides an interface to check status of optimization algorithms for problems with equality constraints.
class ConvexCombinationRiskMeasure
Provides an interface for a convex combination of risk measures.
class CubicInterp
Implements cubic interpolation back tracking line search.
class CubicInterp_U
Implements cubic interpolation back tracking line search.
class CVaR
Provides an interface for a convex combination of the expected value and the conditional value-at-risk.
class DaiFletcherProjection
class DescentDirection_U
Provides the interface to compute unconstrained optimization steps for line search.
class DiagonalOperator
Provides the interface to apply a diagonal operator which acts like elementwise multiplication when apply() is used and elementwise division when applyInverse() is used.
class Dirac
class Distribution
class DogLeg
Provides interface for dog leg trust-region subproblem solver.
class DogLeg_U
Provides interface for dog leg trust-region subproblem solver.
class DoubleDogLeg
Provides interface for the double dog leg trust-region subproblem solver.
class DoubleDogLeg_U
Provides interface for the double dog leg trust-region subproblem solver.
class DouglasRachfordProjection
class DualAtomVector
class DualProbabilityVector
class DualScaledStdVector
Provides the std::vector implementation of the ROL::Vector interface that handles scalings in the inner product. Also see ROL::PrimalScaledStdVector.
class DualScaledVector
Provides the implementation of the ROL::Vector interface that handles scalings in the inner product. A more generic version of ROL::PrimalScaledStdVector.
class DualSimulatedVector
class DyadicOperator
Interface to apply a dyadic operator to a vector.
class DykstraProjection
class DynamicConstraint
Defines the time-dependent constraint operator interface for simulation-based optimization.
struct DynamicConstraintCheck
class DynamicFunction
Provides update interface, casting and vector management to DynamicConstraint and DynamicObjective.
class DynamicObjective
Defines the time-dependent objective function interface for simulation-based optimization. Computes time-local contributions of value, gradient, Hessian-vector product etc to a larger composite objective defined over the simulation time. In contrast to other objective classes Objective_TimeSimOpt has a default implementation of value which returns zero, as time-dependent simulation based optimization problems may have an objective value which depends only on the final state of the system.
struct DynamicObjectiveCheck
class DynamicTrackingFEMObjective
Defines the time-local contribution to a quadratic tracking objective.
class DynamicTrackingObjective
Defines the time-local contribution to a quadratic tracking objective.
class ElasticLinearConstraint
Defines the general affine constraint with the form \(c(x)=g(x) + g'(x)s + u - v\).
class ElasticObjective
Provides the interface to evaluate the elastic augmented Lagrangian.
class ElementwiseVector
Intermediate abstract class which does not require users implements plus, set, scale, axpy, norm, dot, or zero if they implement the three elementwise functions: applyUnary, applyBinary, and reduce.
class EntropicRisk
Provides an interface for the entropic risk.
class ExpectationQuad
Provides a general interface for risk and error measures generated through the expectation risk quadrangle.
class ExpectationQuadDeviation
class ExpectationQuadError
Provides a general interface for error measures generated through the expectation risk quadrangle.
class ExpectationQuadRegret
Provides a general interface for regret measures generated through the expectation risk quadrangle.
class ExpectationQuadRisk
class Exponential
class FDivergence
Provides a general interface for the F-divergence distributionally robust expectation.
class Fletcher
class FletcherBase
class FletcherObjectiveBase
class FletcherObjectiveE
class FletcherStatusTest
Provides an interface to check status of optimization algorithms for problems with equality constraints.
class FletcherStep
Provides the interface to compute Fletcher steps.
class Gamma
class Gaussian
class GenMoreauYosidaCVaR
class GMRES
Preconditioned GMRES solver.
class GoldenSection
Implements a golden section line search.
class Gradient_U
Provides the interface to compute optimization steps with the gradient descent method globalized using line search.
class GradientStep
Provides the interface to compute optimization steps with the gradient descent method globalized using line search.
class Gumbel
class HMCR
Provides an interface for a convex combination of the expected value and the higher moment coherent risk measure.
class HouseholderReflector
Provides the interface to create a Householder reflector operator, that when applied to a vector x, produces a vector parallel to y.
class IdentityOperator
Multiplication by unity.
class InactiveSet_DualVector
Defines the a Vector which has a diagonally scaled dot product that neglects active set elements Used to simplify Semi-smooth Newton method implementation.
class InactiveSet_PrimalVector
Defines the a Vector which has a diagonally scaled dot product that neglects active set elements Used to simplify Semi-smooth Newton method implementation.
class InteriorPointObjective
class InteriorPointPenalty
Provides the interface to evaluate the Interior Pointy log barrier penalty function with upper and lower bounds on some elements.
class InteriorPointStep
class IterationScaling
Provides an implementation of iteration scaled line search.
class IterationScaling_U
Provides an implementation of iteration scaled line search.
class KelleySachsModel
Provides the interface to evaluate projected trust-region model functions from the Kelley-Sachs bound constrained trust-region algorithm.
class KLDivergence
Provides an interface for the Kullback-Leibler distributionally robust expectation.
class Krylov
Provides definitions for Krylov solvers.
class Kumaraswamy
class l1Objective
Provides the interface to evaluate the weighted/shifted l1 objective function.
class Lanczos
Interface for computing the Lanczos vectors and approximate solutions to symmetric indefinite linear systems.
class Laplace
class lBFGS
Provides definitions for limited-memory BFGS operators.
class lDFP
Provides definitions for limited-memory DFP operators.
class LinearCombinationObjective
class LinearCombinationObjective_SimOpt
class LinearConstraint
Defines the general affine constraint with the form \(c(x)=Ax+b\).
class LinearObjective
Provides the interface to evaluate linear objective functions.
class LinearObjective_SimOpt
Provides the interface to evaluate linear objective functions.
class LinearOperator
Provides the interface to apply a linear operator.
class LinearOperatorFromConstraint
A simple wrapper which allows application of constraint Jacobians through the LinearOperator interface.
class LinearOperatorProduct
class LinearOperatorSum
class LinearRegression
Provides the interface to construct linear regression problem.
class LineSearch
Provides interface for and implements line searches.
class LineSearch_U
Provides interface for and implements line searches.
class LineSearchStep
Provides the interface to compute optimization steps with line search.
class LinMore
Provides interface for truncated CG trust-region subproblem solver.
class LinMoreModel
Provides the interface to evaluate projected trust-region model functions from the Kelley-Sachs bound constrained trust-region algorithm.
class LogBarrierObjective
Log barrier objective for interior point methods.
class LogExponentialQuadrangle
Provides an interface for the entropic risk using the expectation risk quadrangle.
class Logistic
class LogQuantileQuadrangle
Provides an interface for the conditioanl entropic risk using the expectation risk quadrangle.
class LowerBoundToConstraint
Provides an implementation for lower bound constraints.
class lSR1
Provides definitions for limited-memory SR1 operators.
class MeanDeviation
Provides an interface for the mean plus a sum of arbitrary order deviations.
class MeanDeviationFromTarget
Provides an interface for the mean plus a sum of arbitrary order deviations from targets.
class MeanSemiDeviation
Provides an interface for the mean plus upper semideviation of order 1.
class MeanSemiDeviationFromTarget
class MeanValueConstraint
class MeanValueObjective
class MeanVariance
Provides an interface for the mean plus a sum of arbitrary order variances.
class MeanVarianceFromTarget
Provides an interface for the mean plus a sum of arbitrary order variances from targets.
class MeanVarianceQuadrangle
Provides an interface for the mean plus variance risk measure using the expectation risk quadrangle.
class MixedCVaR
Provides an interface for a convex combination of conditional value-at-risks.
class MomentObjective
class MonteCarloGenerator
class MoreauYosidaCVaR
Provides an interface for a smooth approximation of the conditional value-at-risk.
class MoreauYosidaObjective
Provides the interface to evaluate the Moreau-Yosida penalty function.
class MoreauYosidaPenalty
Provides the interface to evaluate the Moreau-Yosida penalty function.
class MoreauYosidaPenaltyStep
Implements the computation of optimization steps using Moreau-Yosida regularized bound constraints.
class NewConstraintManager
Provides a wrapper for multiple constraints.
class Newton_U
Provides the interface to compute optimization steps with Newton's method globalized using line search.
class NewtonKrylov_U
Provides the interface to compute optimization steps with projected inexact Newton's method using line search.
class NewtonKrylovStep
Provides the interface to compute optimization steps with projected inexact Newton's method using line search.
class NewtonStep
Provides the interface to compute optimization steps with Newton's method globalized using line search.
class NonlinearCG_U
Provides the interface to compute optimization steps with nonlinear CG.
class NonlinearCGStep
Provides the interface to compute optimization steps with nonlinear CG.
class NonlinearLeastSquaresObjective
Provides the interface to evaluate nonlinear least squares objective functions.
class NonlinearLeastSquaresObjective_Dynamic
Provides the interface to evaluate nonlinear least squares objective functions.
class NullOperator
Multiplication by zero.
class NullSpaceOperator
Projects on to the null space of a linear constraint.
class Objective
Provides the interface to evaluate objective functions.
class Objective_FSsolver
class Objective_SerialSimOpt
class Objective_SimOpt
Provides the interface to evaluate simulation-based objective functions.
class Objective_TimeSimOpt
Defines the time-dependent objective function interface for simulation-based optimization. Computes time-local contributions of value, gradient, Hessian-vector product etc to a larger composite objective defined over the simulation time. In contrast to other objective classes Objective_TimeSimOpt has a default implementation of value which returns zero, as time-dependent simulation based optimization problems may have an objective value which depends only on the final state of the system.
class ObjectiveFromBoundConstraint
Create a penalty objective from upper and lower bound vectors.
class ObjectiveFromConstraint
class ObjectiveMMA
Provides the interface to to Method of Moving Asymptotes Objective function.
class OptimizationProblem
struct OptimizationProblemCheckData
class OptimizationSolver
Provides a simplified interface for solving a wide range of optimization problems.
class Parabolic
class PartitionedVector
Defines the linear algebra of vector space on a generic partitioned vector.
class PathBasedTargetLevel
Provides an implementation of path-based target leve line search.
class PathBasedTargetLevel_U
Provides an implementation of path-based target leve line search.
class PD_BPOE
class PD_CVaR
class PD_HMCR2
class PD_MeanSemiDeviation
class PD_MeanSemiDeviationFromTarget
class PD_RandVarFunctional
class PH_bPOEObjective
Provides the interface for the progressive hedging probability objective.
class PH_DeviationObjective
Provides the interface for the progressive hedging deviation objective.
class PH_ErrorObjective
Provides the interface for the progressive hedging error objective.
class PH_Objective
Provides the interface for the progressive hedging objective.
class PH_ProbObjective
Provides the interface for the progressive hedging probability objective.
class PH_RegretObjective
Provides the interface for the progressive hedging regret objective.
class PH_RiskObjective
Provides the interface for the progressive hedging risk objective.
class PH_StatusTest
Provides an interface to check status of the progressive hedging algorithm.
class PlusFunction
class PointwiseCDFObjective
class PolyhedralProjection
class PositiveFunction
class PQNObjective
Provides the interface to evaluate the quadratic quasi-Newton objective.
class PrimalAtomVector
class PrimalDualActiveSetStep
Implements the computation of optimization steps with the Newton primal-dual active set method.
class PrimalDualInteriorPointBlock11
class PrimalDualInteriorPointBlock12
class PrimalDualInteriorPointBlock21
class PrimalDualInteriorPointBlock22
class PrimalDualInteriorPointResidual
Symmetrized form of the KKT operator for the Type-EB problem with equality and bound multipliers.
class PrimalDualRisk
class PrimalDualSystemStep
Provides the interface to compute approximate solutions to 2x2 block systems arising from primal-dual interior point methods.
class PrimalProbabilityVector
class PrimalScaledStdVector
Provides the std::vector implementation of the ROL::Vector interface that handles scalings in the inner product. Also see ROL::DualScaledStdVector.
class PrimalScaledVector
Provides the implementation of the ROL::Vector interface that handles scalings in the inner product. A more generic version of ROL::PrimalScaledStdVector.
class PrimalSimulatedVector
class ProbabilityVector
Provides the std::vector implementation of the ROL::Vector interface.
class Problem
class ProfiledVector
By keeping a pointer to this in a derived Vector class, a tally of all methods is kept for profiling function calls.
class ProgressiveHedging
Provides the interface to solve a stochastic program using progressive hedging.
class ProjectedNewtonKrylovStep
Provides the interface to compute optimization steps with projected inexact ProjectedNewton's method using line search.
class ProjectedNewtonStep
Provides the interface to compute optimization steps with projected Newton's method using line search.
class ProjectedObjective
class ProjectedSecantStep
Provides the interface to compute optimization steps with projected secant method using line search.
class ProxObjective
class QuadraticObjective
Provides the interface to evaluate quadratic objective functions.
class QuadraticPenalty
Provides the interface to evaluate the quadratic constraint penalty.
class QuadraticPenalty_SimOpt
Provides the interface to evaluate the quadratic SimOpt constraint penalty.
class QuantileQuadrangle
Provides an interface for a convex combination of the expected value and the conditional value-at-risk using the expectation risk quadrangle.
class QuantileRadius
class QuasiNewton_U
Provides the interface to compute optimization steps with a secant method.
class RaisedCosine
class RandVarFunctional
Provides the interface to implement any functional that maps a random variable to a (extended) real number.
class RangeSpaceOperator
Projects on to the null space of a linear constraint.
class Reduced_AugmentedLagrangian_SimOpt
Provides the interface to evaluate the reduced SimOpt augmented Lagrangian.
class Reduced_Constraint_SimOpt
class Reduced_Objective_SimOpt
class ReducedDynamicObjective
Defines the reduced time-dependent objective function interface for simulation-based optimization.
class ReducedDynamicStationaryControlsObjective
Defines the reduced time-dependent objective function interface for simulation-based optimization when the controls are stationary (i.e., not time-dependent).
class ReducedDynamicStationaryControlsObjectiveHook
class ReducedLinearConstraint
Reduce the input of a linear constraint based on the active set associated with a vector \(x\), i.e., let \(\mathcal{I}\) denote the inactive set associated with \(x\) and the bounds \(\ell\le u\), then.
class ReduceLinearConstraint
Performs null-space transformation for reducible linear equality constraints.
class RegressionError
Provides the interface to evaluate linear regression error.
struct removeSpecialCharacters
class RiddersProjection
class RieszDualVector
class RieszPrimalVector
class RiskBoundConstraint
class RiskLessConstraint
class RiskLessObjective
class RiskMeasure
Provides the interface to implement risk measures.
class RiskNeutralConstraint
class RiskNeutralObjective
class RiskVector
class SampledScalar
class SampledVector
class SampleGenerator
class ScalarController
class ScalarLinearConstraint
This equality constraint defines an affine hyperplane.
class ScalarMinimizationLineSearch
Implements line search methods that attempt to minimize the scalar function \(\phi(t) := f(x+ts)\).
class ScalarMinimizationLineSearch_U
Implements line search methods that attempt to minimize the scalar function \(\phi(t) := f(x+ts)\).
struct ScalarTraits
struct ScalarTraits_Magnitude
struct ScalarTraits_Magnitude< std::complex< Real > >
class ScaledObjective
class SchurComplement
Given a 2x2 block operator, perform the Schur reduction and return the decoupled system components.
class Secant
Provides interface for and implements limited-memory secant operators.
struct SecantState
class SecantStep
Provides the interface to compute optimization steps with a secant method.
class SecondOrderCVaR
Provides an interface for the risk measure associated with the super quantile quadrangle.
class SemismoothNewtonProjection
class SerialConstraint
Evaluates ROL::DynamicConstraint over a sequential set of time intervals.
class SerialFunction
Provides behavior common to SerialObjective as SerialConstaint.
class SerialObjective
Evaluates ROL::DynamicObjective over a sequential set of time intervals.
class ShiftedProxObjective
class SimConstraint
class SimulatedBoundConstraint
A BoundConstraint formed from a single bound constraint replacated according to a SampleGenerator.
class SimulatedConstraint
class SimulatedObjective
class SimulatedObjectiveCVaR
class SimulatedVector
Defines the linear algebra of a vector space on a generic partitioned vector where the individual vectors are distributed in batches defined by ROL::BatchManager. This is a batch-distributed version of ROL::PartitionedVector.
class SingletonVector
class Sketch
Provides an interface for randomized sketching.
class SlacklessConstraint
This class strips out the slack variables from constraint evaluations to create the new constraint \(C(x,s) = c(x) \).
class SlacklessObjective
This class strips out the slack variables from objective evaluations to create the new objective \(F(x,s) = f(x) \).
class Smale
class SmoothedPOE
Provides the implementation of the smoothed probability of exceedance.
class SmoothedWorstCaseQuadrangle
Provides an interface for a smoothed version of the worst-case scenario risk measure using the expectation risk quadrangle.
class Solver
Provides a simplified interface for solving a wide range of optimization problems.
class SpectralRisk
Provides an interface for spectral risk measures.
class SPGTrustRegion_U
Provides interface for truncated CG trust-region subproblem solver.
class SROMGenerator
class SROMVector
Provides the std::vector implementation of the ROL::Vector interface.
class StatusTest
Provides an interface to check status of optimization algorithms.
class StatusTestFactory
class StdArray
Provides the std::array implementation of the ROL::Vector interface.
class StdBoundConstraint
class StdConstraint
Defines the equality constraint operator interface for StdVectors.
class StdLinearOperator
Provides the std::vector implementation to apply a linear operator, which is a std::vector representation of column-stacked matrix.
class StdObjective
Specializes the ROL::Objective interface for objective functions that operate on ROL::StdVector's.
class StdTridiagonalOperator
Provides the std::vector implementation to apply a linear operator, which encapsulates a tridiagonal matrix.
class StdVector
Provides the ROL::Vector interface for scalar values, to be used, for example, with scalar constraints.
class Step
Provides the interface to compute optimization steps.
class StepFactory
struct StepState
State for step class. Will be used for restarts.
class StochasticConstraint
class StochasticObjective
class StochasticProblem
class TestProblem
class TimeStamp
Contains local time step information.
class Triangle
class TruncatedCG
Provides interface for truncated CG trust-region subproblem solver.
class TruncatedCG_U
Provides interface for truncated CG trust-region subproblem solver.
class TruncatedExponential
class TruncatedGaussian
class TruncatedMeanQuadrangle
class TrustRegion
Provides interface for and implements trust-region subproblem solvers.
class TrustRegion_U
Provides interface for and implements trust-region subproblem solvers.
class TrustRegionModel
Provides the interface to evaluate trust-region model functions.
class TrustRegionModel_U
Provides the interface to evaluate trust-region model functions.
class TrustRegionStep
Provides the interface to compute optimization steps with trust regions.
class TypeBIndicatorObjective
Provides the interface to evaluate the indicator function of linear constraints.
struct TypeCaster
struct TypeCaster< double, float >
struct TypeCaster< Real, std::complex< Real > >
class Uniform
class UpperBoundToConstraint
Provides an implementation for upper bound constraints.
class UserInputGenerator
class Vector
Defines the linear algebra or vector space interface.
class Vector_SimOpt
Defines the linear algebra or vector space interface for simulation-based optimization.
class VectorController
struct VectorFunctionCalls
class ZeroProxObjective
Typedefs
template<typename Real >
using TimeStampsPtr = Ptr< std::vector< TimeStamp< Real > > >
Enumerations
enum EPolyProjAlgo {
PPA_DAIFLETCHER = 0 , PPA_DYKSTRA , PPA_DOUGLASRACHFORD , PPA_NEWTON ,
PPA_RIDDERS , PPA_BRENTS , PPA_LAST
}
enum class UpdateType : std::uint8_t {
Initial = 0 , Accept , Revert , Trial ,
Temp
}
enum EDescentU {
DESCENT_U_STEEPEST = 0 , DESCENT_U_NONLINEARCG , DESCENT_U_SECANT , DESCENT_U_NEWTON ,
DESCENT_U_NEWTONKRYLOV , DESCENT_U_USERDEFINED , DESCENT_U_LAST
}
enum ELineSearchU {
LINESEARCH_U_ITERATIONSCALING = 0 , LINESEARCH_U_PATHBASEDTARGETLEVEL , LINESEARCH_U_BACKTRACKING , LINESEARCH_U_BISECTION ,
LINESEARCH_U_GOLDENSECTION , LINESEARCH_U_CUBICINTERP , LINESEARCH_U_BRENTS , LINESEARCH_U_USERDEFINED ,
LINESEARCH_U_LAST
}
enum ECurvatureConditionU {
CURVATURECONDITION_U_WOLFE = 0 , CURVATURECONDITION_U_STRONGWOLFE , CURVATURECONDITION_U_GENERALIZEDWOLFE , CURVATURECONDITION_U_APPROXIMATEWOLFE ,
CURVATURECONDITION_U_GOLDSTEIN , CURVATURECONDITION_U_NULL , CURVATURECONDITION_U_LAST
}
enum ETrustRegionU {
TRUSTREGION_U_CAUCHYPOINT = 0 , TRUSTREGION_U_TRUNCATEDCG , TRUSTREGION_U_SPG , TRUSTREGION_U_DOGLEG ,
TRUSTREGION_U_DOUBLEDOGLEG , TRUSTREGION_U_LAST
}
enum EKrylov {
KRYLOV_CG = 0 , KRYLOV_CR , KRYLOV_GMRES , KRYLOV_MINRES ,
KRYLOV_BICGSTAB , KRYLOV_USERDEFINED , KRYLOV_LAST
}
enum ESecantMode { SECANTMODE_FORWARD = 0 , SECANTMODE_INVERSE , SECANTMODE_BOTH }
enum ETrustRegion {
TRUSTREGION_CAUCHYPOINT = 0 , TRUSTREGION_TRUNCATEDCG , TRUSTREGION_DOGLEG , TRUSTREGION_DOUBLEDOGLEG ,
TRUSTREGION_LINMORE , TRUSTREGION_LAST
}
enum ETrustRegionModel { TRUSTREGION_MODEL_COLEMANLI = 0 , TRUSTREGION_MODEL_KELLEYSACHS , TRUSTREGION_MODEL_LINMORE , TRUSTREGION_MODEL_LAST }
enum ETrustRegionFlag {
TRUSTREGION_FLAG_SUCCESS = 0 , TRUSTREGION_FLAG_POSPREDNEG , TRUSTREGION_FLAG_NPOSPREDPOS , TRUSTREGION_FLAG_NPOSPREDNEG ,
TRUSTREGION_FLAG_QMINSUFDEC , TRUSTREGION_FLAG_NAN , TRUSTREGION_FLAG_UNDEFINED
}
enum EDistribution {
DISTRIBUTION_ARCSINE = 0 , DISTRIBUTION_BETA , DISTRIBUTION_CAUCHY , DISTRIBUTION_DIRAC ,
DISTRIBUTION_EXPONENTIAL , DISTRIBUTION_GAMMA , DISTRIBUTION_GAUSSIAN , DISTRIBUTION_KUMARASWAMY ,
DISTRIBUTION_LAPLACE , DISTRIBUTION_LOGISTIC , DISTRIBUTION_PARABOLIC , DISTRIBUTION_RAISEDCOSINE ,
DISTRIBUTION_SMALE , DISTRIBUTION_TRIANGLE , DISTRIBUTION_TRUNCATEDEXPONENTIAL , DISTRIBUTION_TRUNCATEDGAUSSIAN ,
DISTRIBUTION_UNIFORM , DISTRIBUTION_LAST
}
enum EDeviationMeasure {
DEVIATIONMEASURE_MEANVARIANCEQUADRANGLE = 0 , DEVIATIONMEASURE_TRUNCATEDMEANQUADRANGLE , DEVIATIONMEASURE_QUANTILEQUADRANGLE , DEVIATIONMEASURE_MOREAUYOSIDACVAR ,
DEVIATIONMEASURE_GENMOREAUYOSIDACVAR , DEVIATIONMEASURE_LOGEXPONENTIALQUADRANGLE , DEVIATIONMEASURE_LOGQUANTILEQUADRANGLE , DEVIATIONMEASURE_SMOOTHEDWORSTCASEQUADRANGLE ,
DEVIATIONMEASURE_LAST
}
enum EErrorMeasure {
ERRORMEASURE_MEANVARIANCEQUADRANGLE = 0 , ERRORMEASURE_TRUNCATEDMEANQUADRANGLE , ERRORMEASURE_QUANTILEQUADRANGLE , ERRORMEASURE_MOREAUYOSIDACVAR ,
ERRORMEASURE_GENMOREAUYOSIDACVAR , ERRORMEASURE_LOGEXPONENTIALQUADRANGLE , ERRORMEASURE_LOGQUANTILEQUADRANGLE , ERRORMEASURE_SMOOTHEDWORSTCASEQUADRANGLE ,
ERRORMEASURE_LAST
}
enum EProbability { PROBABILITY_BPOE = 0 , PROBABILITY_SMOOTHEDPOE , PROBABILITY_LAST }
enum ERegretMeasure {
REGRETMEASURE_MEANABSOLUTELOSS = 0 , REGRETMEASURE_MOREAUYOSIDAMEANABSOLUTELOSS , REGRETMEASURE_GENMOREAUYOSIDAMEANABSOLUTELOSS , REGRETMEASURE_EXPONENTIAL ,
REGRETMEASURE_MEANL2 , REGRETMEASURE_TRUNCATEDMEAN , REGRETMEASURE_LOGQUANTILE , REGRETMEASURE_SMOOTHEDWORSTCASE ,
REGRETMEASURE_LAST
}
enum ERiskMeasure {
RISKMEASURE_CVAR = 0 , RISKMEASURE_MOREAUYOSIDACVAR , RISKMEASURE_GENMOREAUYOSIDACVAR , RISKMEASURE_MIXEDCVAR ,
RISKMEASURE_SPECTRALRISK , RISKMEASURE_SECONDORDERCVAR , RISKMEASURE_CHEBYSHEVSPECTRAL , RISKMEASURE_QUANTILERADIUS ,
RISKMEASURE_HMCR , RISKMEASURE_ENTROPICRISK , RISKMEASURE_COHERENTENTROPICRISK , RISKMEASURE_MEANSEMIDEVIATION ,
RISKMEASURE_MEANSEMIDEVIATIONFROMTARGET , RISKMEASURE_MEANDEVIATIONFROMTARGET , RISKMEASURE_MEANDEVIATION , RISKMEASURE_MEANVARIANCEFROMTARGET ,
RISKMEASURE_MEANVARIANCE , RISKMEASURE_TRUNCATEDMEAN , RISKMEASURE_LOGQUANTILE , RISKMEASURE_SMOOTHEDWORSTCASE ,
RISKMEASURE_LOGEXPONENTIAL , RISKMEASURE_SAFETYMARGIN , RISKMEASURE_CHI2DIVERGENCE , RISKMEASURE_KLDIVERGENCE ,
RISKMEASURE_LAST
}
enum EAbsoluteValue {
ABSOLUTEVALUE_TRUE = 0 , ABSOLUTEVALUE_SQUAREROOT , ABSOLUTEVALUE_SQRTDENOM , ABSOLUTEVALUE_C2 ,
ABSOLUTEVALUE_LAST
}
enum EExitStatus {
EXITSTATUS_CONVERGED = 0 , EXITSTATUS_MAXITER , EXITSTATUS_STEPTOL , EXITSTATUS_NAN ,
EXITSTATUS_USERDEFINED , EXITSTATUS_LAST
}
Enum for algorithm termination.
enum EProblem {
TYPE_U = 0 , TYPE_P , TYPE_B , TYPE_E ,
TYPE_EB , TYPE_LAST
}
enum EStep {
STEP_AUGMENTEDLAGRANGIAN = 0 , STEP_BUNDLE , STEP_COMPOSITESTEP , STEP_LINESEARCH ,
STEP_MOREAUYOSIDAPENALTY , STEP_PRIMALDUALACTIVESET , STEP_TRUSTREGION , STEP_INTERIORPOINT ,
STEP_FLETCHER , STEP_LAST
}
enum EDescent {
DESCENT_STEEPEST = 0 , DESCENT_NONLINEARCG , DESCENT_SECANT , DESCENT_NEWTON ,
DESCENT_NEWTONKRYLOV , DESCENT_LAST
}
enum ESecant {
SECANT_LBFGS = 0 , SECANT_LDFP , SECANT_LSR1 , SECANT_BARZILAIBORWEIN ,
SECANT_USERDEFINED , SECANT_LAST
}
enum ENonlinearCG {
NONLINEARCG_HESTENES_STIEFEL = 0 , NONLINEARCG_FLETCHER_REEVES , NONLINEARCG_DANIEL , NONLINEARCG_POLAK_RIBIERE ,
NONLINEARCG_FLETCHER_CONJDESC , NONLINEARCG_LIU_STOREY , NONLINEARCG_DAI_YUAN , NONLINEARCG_HAGER_ZHANG ,
NONLINEARCG_OREN_LUENBERGER , NONLINEARCG_USERDEFINED , NONLINEARCG_LAST
}
enum ELineSearch {
LINESEARCH_ITERATIONSCALING = 0 , LINESEARCH_PATHBASEDTARGETLEVEL , LINESEARCH_BACKTRACKING , LINESEARCH_BISECTION ,
LINESEARCH_GOLDENSECTION , LINESEARCH_CUBICINTERP , LINESEARCH_BRENTS , LINESEARCH_USERDEFINED ,
LINESEARCH_LAST
}
enum ECurvatureCondition {
CURVATURECONDITION_WOLFE = 0 , CURVATURECONDITION_STRONGWOLFE , CURVATURECONDITION_GENERALIZEDWOLFE , CURVATURECONDITION_APPROXIMATEWOLFE ,
CURVATURECONDITION_GOLDSTEIN , CURVATURECONDITION_NULL , CURVATURECONDITION_LAST
}
enum ECGFlag {
CG_FLAG_SUCCESS = 0 , CG_FLAG_ITEREXCEED , CG_FLAG_NEGCURVE , CG_FLAG_TRRADEX ,
CG_FLAG_ZERORHS , CG_FLAG_UNDEFINED
}
enum ETestOptProblem {
TESTOPTPROBLEM_ROSENBROCK = 0 , TESTOPTPROBLEM_FREUDENSTEINANDROTH , TESTOPTPROBLEM_BEALE , TESTOPTPROBLEM_POWELL ,
TESTOPTPROBLEM_SUMOFSQUARES , TESTOPTPROBLEM_LEASTSQUARES , TESTOPTPROBLEM_POISSONCONTROL , TESTOPTPROBLEM_POISSONINVERSION ,
TESTOPTPROBLEM_ZAKHAROV , TESTOPTPROBLEM_HS1 , TESTOPTPROBLEM_HS2 , TESTOPTPROBLEM_HS3 ,
TESTOPTPROBLEM_HS4 , TESTOPTPROBLEM_HS5 , TESTOPTPROBLEM_HS9 , TESTOPTPROBLEM_HS14 ,
TESTOPTPROBLEM_HS21 , TESTOPTPROBLEM_HS24 , TESTOPTPROBLEM_HS25 , TESTOPTPROBLEM_HS28 ,
TESTOPTPROBLEM_HS29 , TESTOPTPROBLEM_HS32 , TESTOPTPROBLEM_HS38 , TESTOPTPROBLEM_HS39 ,
TESTOPTPROBLEM_HS41 , TESTOPTPROBLEM_HS42 , TESTOPTPROBLEM_HS45 , TESTOPTPROBLEM_HS48 ,
TESTOPTPROBLEM_HS49 , TESTOPTPROBLEM_HS50 , TESTOPTPROBLEM_HS51 , TESTOPTPROBLEM_HS52 ,
TESTOPTPROBLEM_HS53 , TESTOPTPROBLEM_HS55 , TESTOPTPROBLEM_HS63 , TESTOPTPROBLEM_BVP ,
TESTOPTPROBLEM_PARABOLOIDCIRCLE , TESTOPTPROBLEM_SIMPLEEQCONSTRAINED , TESTOPTPROBLEM_CANTILEVERBEAM , TESTOPTPROBLEM_CUBIC ,
TESTOPTPROBLEM_QUARTIC , TESTOPTPROBLEM_CYLINDERHEAD , TESTOPTPROBLEM_CANTILEVER , TESTOPTPROBLEM_MINIMAX1 ,
TESTOPTPROBLEM_MINIMAX2 , TESTOPTPROBLEM_MINIMAX3 , TESTOPTPROBLEM_LAST
}
Functions
template<typename Real >
PartitionedVector< Real > & partition (Vector< Real > &x)
template<typename Real >
const PartitionedVector< Real > & partition (const Vector< Real > &x)
template<typename Real >
Ptr< PartitionedVector< Real > > partition (const Ptr< Vector< Real > > &x)
template<typename Real >
Ptr< const PartitionedVector< Real > > partition (const Ptr< const Vector< Real > > &x)
template<class Real >
ROL::Ptr< Vector< Real > > CreatePartitionedVector (const ROL::Ptr< Vector< Real > > &a)
template<class Real >
ROL::Ptr< const Vector< Real > > CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > &a)
template<class Real >
ROL::Ptr< Vector< Real > > CreatePartitionedVector (const ROL::Ptr< Vector< Real > > &a, const ROL::Ptr< Vector< Real > > &b)
template<class Real >
ROL::Ptr< const Vector< Real > > CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > &a, const ROL::Ptr< const Vector< Real > > &b)
template<class Real >
ROL::Ptr< Vector< Real > > CreatePartitionedVector (const ROL::Ptr< Vector< Real > > &a, const ROL::Ptr< Vector< Real > > &b, const ROL::Ptr< Vector< Real > > &c)
template<class Real >
ROL::Ptr< const Vector< Real > > CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > &a, const ROL::Ptr< const Vector< Real > > &b, const ROL::Ptr< const Vector< Real > > &c)
template<class Real >
ROL::Ptr< Vector< Real > > CreatePartitionedVector (const ROL::Ptr< Vector< Real > > &a, const ROL::Ptr< Vector< Real > > &b, const ROL::Ptr< Vector< Real > > &c, const ROL::Ptr< Vector< Real > > &d)
template<class Real >
ROL::Ptr< const Vector< Real > > CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > &a, const ROL::Ptr< const Vector< Real > > &b, const ROL::Ptr< const Vector< Real > > &c, const ROL::Ptr< const Vector< Real > > &d)
template<class Ordinal , class Real >
VectorFunctionCalls< Ordinal > getVectorFunctionCalls (const ProfiledVector< Ordinal, Real > &x)
template<class Ordinal , class Real >
void printVectorFunctionCalls (const ProfiledVector< Ordinal, Real > &x, std::ostream &outStream=std::cout)
template<class Real >
void RandomizeVector (Vector< Real > &x, const Real &lower=0.0, const Real &upper=1.0)
Fill a ROL::Vector with uniformly-distributed random numbers in the interval [lower,upper].
template<class Real >
void RandomizeFeasibleVector (Vector< Real > &x, BoundConstraint< Real > &bnd)
Fill a ROL::Vector with uniformly-distributed random numbers which satisfy the supplied bound constraint.
template<template< typename > class V, typename Real , typename P = Ptr<Vector<Real>>>
std::enable_if< std::is_base_of< Vector< Real >, V< Real > >::value, P >::type make_Vector_SimOpt (const Ptr< V< Real > > &vsim, const Ptr< V< Real > > &vopt)
template<typename Real >
Ptr< BoundConstraint< Real > > CreateBoundConstraint_Partitioned (const Ptr< BoundConstraint< Real > > &bnd1, const Ptr< BoundConstraint< Real > > &bnd2)
template<typename Real >
DynamicConstraint_CheckInterface< Real > make_check (DynamicConstraint< Real > &con)
template<typename Real >
DynamicConstraint_CheckInterface< Real > make_check (DynamicConstraint< Real > &con, TimeStamp< Real > &timeStamp)
template<typename Real >
DynamicObjective_CheckInterface< Real > make_check (DynamicObjective< Real > &obj)
template<typename Real >
DynamicObjective_CheckInterface< Real > make_check (DynamicObjective< Real > &obj, TimeStamp< Real > &ts)
template<typename Real >
Ptr< DynamicObjective< Real > > make_DynamicTrackingFEMObjective (const Ptr< PartitionedVector< Real > > &target, Real alpha=0.0)
template<typename Real >
Ptr< DynamicObjective< Real > > make_DynamicTrackingObjective (const Ptr< PartitionedVector< Real > > &target, Real alpha=0.0)
template<typename DynCon , typename Real , typename P = Ptr<SerialConstraint<Real>>>
std::enable_if< std::is_base_of< DynamicConstraint< Real >, DynCon >::value, P >::type make_SerialConstraint (const Ptr< DynCon > &con, const Vector< Real > &u_initial, const TimeStampsPtr< Real > timeStampsPtr)
template<typename DynObj , typename Real , typename P = Ptr<SerialObjective<Real>>>
std::enable_if< std::is_base_of< DynamicObjective< Real >, DynObj >::value, P >::type make_SerialObjective (const Ptr< DynObj > &obj, const Vector< Real > &u_initial, const TimeStampsPtr< Real > timeStampsPtr)
template<class Real >
ROL::BlockOperator2Diagonal BlockOperator2 apply (V &Hv, const V &v, Real &tol) const
void applyInverse (V &Hv, const V &v Real &tol) const
ROL::Ptr< LinearOperator< Real > > getOperator (int row, int col) const
template<class Real >
ROL::BlockOperator2UnitLower LinearOperator apply (V &Hv, const V &v, Real &tol) const
template<class Real >
ROL::BlockOperator2UnitUpper LinearOperator apply (V &Hv, const V &v, Real &tol) const
std::string EPolyProjAlgoToString (EPolyProjAlgo alg)
int isValidPolyProjAlgo (EPolyProjAlgo alg)
Verifies validity of a PolyProjAlgo enum.
EPolyProjAlgo & operator++ (EPolyProjAlgo &type)
EPolyProjAlgo operator++ (EPolyProjAlgo &type, int)
EPolyProjAlgo & operator-- (EPolyProjAlgo &type)
EPolyProjAlgo operator-- (EPolyProjAlgo &type, int)
EPolyProjAlgo StringToEPolyProjAlgo (std::string s)
template<typename Real >
Ptr< PolyhedralProjection< Real > > PolyhedralProjectionFactory (const Vector< Real > &xprim, const Vector< Real > &xdual, const Ptr< BoundConstraint< Real > > &bnd, const Ptr< Constraint< Real > > &con, const Vector< Real > &mul, const Vector< Real > &res, ParameterList &list)
std::string UpdateTypeToString (const UpdateType &type)
template<class Real >
Real normL1 (const Vector< Real > &x)
template<class Real , class Exponent >
Real normLp (const Vector< Real > &x, Exponent p)
template<class Real >
Real normLinf (const Vector< Real > &x)
template<typename Real >
ROL::Objective_SerialSimOpt Objective_SimOpt value (const V &u, const V &z, Real &tol) override
virtual void gradient_1 (V &g, const V &u, const V &z, Real &tol) override
virtual void gradient_2 (V &g, const V &u, const V &z, Real &tol) override
virtual void hessVec_11 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
virtual void hessVec_12 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
virtual void hessVec_21 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
virtual void hessVec_22 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
virtual void update_1_old (const Vector< Real > &u_old, bool flag=true, int iter=-1)
Update constraint functions with respect to Sim variable.
u_old is the state variable flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_1_new (const Vector< Real > &u_new, bool flag=true, int iter=-1)
Update constraint functions with respect to Sim variable.
u_new is the state variable flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual void update_2 (const Vector< Real > &z, bool flag=true, int iter=-1) override
Update constraint functions with respect to Opt variable. z is the control variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
virtual Real value (const Vector< Real > &u_old, const Vector< Real > &u_new, const Vector< Real > &z, Real &tol)
Compute contribution to objective value from this time step.
virtual void gradient_1_old (Vector< Real > &g, const Vector< Real > &u_old, Vector< Real > &u_new, const Vector< Real > &z, Real &tol)
Compute contribution to simulation term gradient from this time step.
virtual void gradient_1_new (Vector< Real > &g, const Vector< Real > &u_old, Vector< Real > &u_new, const Vector< Real > &z, Real &tol)
Compute contribution to simulation term gradient from this time step.
virtual void gradient_2 (Vector< Real > &g, const Vector< Real > &u_old, Vector< Real > &u_new, const Vector< Real > &z, Real &tol) override
Compute contribution to optimization term gradient from this time step.
virtual void hessVec_11_old (Vector< Real > &hv, const Vector< Real > &v_old, const Vector< Real > &u_old, const Vector< Real > &u_new, const Vector< Real > &z, Real &tol)
virtual void hessVec_11_new (Vector< Real > &hv, const Vector< Real > &v_new, const Vector< Real > &u_old, const Vector< Real > &u_new, const Vector< Real > &z, Real &tol)
virtual void update (const Vector< Real > &u, const Vector< Real > &z, bool flag=true, int iter=-1) override
virtual Real value (const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
virtual void solve (Vector< Real > &c, Vector< Real > &u, const Vector< Real > &z) override
virtual void gradient_1 (Vector< Real > &g, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
virtual void gradient_2 (Vector< Real > &g, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
virtual void hessVec_11 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
virtual void hessVec_12 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
virtual void hessVec_21 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
virtual void hessVec_22 (Vector< Real > &hv, const Vector< Real > &v, const Vector< Real > &u, const Vector< Real > &z, Real &tol) override
template<template< typename > class V, template< typename > class Obj, typename Real , typename P = Ptr<OptimizationProblem<Real>>, typename... Args>
std::enable_if< std::is_base_of< Objective< Real >, Obj< Real > >::value &&std::is_base_of< Vector< Real >, V< Real > >::value, P >::type make_OptimizationProblem (const Ptr< Obj< Real > > &obj, const Ptr< V< Real > > &x, Args &&...args)
template<typename Real >
Ptr< OptimizationSolver< Real > > make_OptimizationSolver (OptimizationProblem< Real > &opt, ParameterList &parlist)
template<typename Real >
Ptr< OptimizationSolver< Real > > make_OptimizationSolver (const Ptr< OptimizationProblem< Real > > &opt, ParameterList &parlist)
template<typename Real >
Ptr< OptimizationSolver< Real > > make_OptimizationSolver (OptimizationProblem< Real > &opt, const Ptr< ParameterList > &parlist)
template<typename Real >
Ptr< OptimizationSolver< Real > > make_OptimizationSolver (const Ptr< OptimizationProblem< Real > > &opt, const Ptr< ParameterList > &parlist)
template<typename Real >
Ptr< DescentDirection_U< Real > > DescentDirectionUFactory (ParameterList &parlist, const Ptr< Secant< Real > > &secant=nullPtr)
template<typename Real >
Ptr< LineSearch_U< Real > > LineSearchUFactory (ParameterList &parlist)
std::string EDescentUToString (EDescentU tr)
int isValidDescentU (EDescentU d)
Verifies validity of a DescentU enum.
EDescentU & operator++ (EDescentU &type)
EDescentU operator++ (EDescentU &type, int)
EDescentU & operator-- (EDescentU &type)
EDescentU operator-- (EDescentU &type, int)
EDescentU StringToEDescentU (std::string s)
std::string ELineSearchUToString (ELineSearchU ls)
int isValidLineSearchU (ELineSearchU ls)
Verifies validity of a LineSearchU enum.
ELineSearchU & operator++ (ELineSearchU &type)
ELineSearchU operator++ (ELineSearchU &type, int)
ELineSearchU & operator-- (ELineSearchU &type)
ELineSearchU operator-- (ELineSearchU &type, int)
ELineSearchU StringToELineSearchU (std::string s)
std::string ECurvatureConditionUToString (ECurvatureConditionU ls)
int isValidCurvatureConditionU (ECurvatureConditionU ls)
Verifies validity of a CurvatureConditionU enum.
ECurvatureConditionU & operator++ (ECurvatureConditionU &type)
ECurvatureConditionU operator++ (ECurvatureConditionU &type, int)
ECurvatureConditionU & operator-- (ECurvatureConditionU &type)
ECurvatureConditionU operator-- (ECurvatureConditionU &type, int)
ECurvatureConditionU StringToECurvatureConditionU (std::string s)
template<typename Real >
Ptr< TrustRegion_U< Real > > TrustRegionUFactory (ParameterList &list)
std::string ETrustRegionUToString (ETrustRegionU tr)
int isValidTrustRegionU (ETrustRegionU ls)
Verifies validity of a TrustRegionU enum.
ETrustRegionU & operator++ (ETrustRegionU &type)
ETrustRegionU operator++ (ETrustRegionU &type, int)
ETrustRegionU & operator-- (ETrustRegionU &type)
ETrustRegionU operator-- (ETrustRegionU &type, int)
ETrustRegionU StringToETrustRegionU (std::string s)
std::string EKrylovToString (EKrylov type)
int isValidKrylov (EKrylov type)
Verifies validity of a Krylov enum.
EKrylov & operator++ (EKrylov &type)
EKrylov operator++ (EKrylov &type, int)
EKrylov & operator-- (EKrylov &type)
EKrylov operator-- (EKrylov &type, int)
EKrylov StringToEKrylov (std::string s)
template<class Real >
Ptr< Krylov< Real > > KrylovFactory (ParameterList &parlist)
template<class Real >
ROL::Ptr< LineSearch< Real > > LineSearchFactory (ROL::ParameterList &parlist)
template<class Real >
ROL::Ptr< Secant< Real > > getSecant (ESecant esec=SECANT_LBFGS, int L=10, int BBtype=1)
template<class Real >
ROL::Ptr< Secant< Real > > SecantFactory (ROL::ParameterList &parlist, ESecantMode mode=SECANTMODE_BOTH)
template<class Real >
ROL::Ptr< TrustRegion< Real > > TrustRegionFactory (ROL::ParameterList &parlist)
std::string ETrustRegionToString (ETrustRegion tr)
int isValidTrustRegion (ETrustRegion ls)
Verifies validity of a TrustRegion enum.
ETrustRegion & operator++ (ETrustRegion &type)
ETrustRegion operator++ (ETrustRegion &type, int)
ETrustRegion & operator-- (ETrustRegion &type)
ETrustRegion operator-- (ETrustRegion &type, int)
ETrustRegion StringToETrustRegion (std::string s)
std::string ETrustRegionModelToString (ETrustRegionModel tr)
int isValidTrustRegionModel (ETrustRegionModel ls)
Verifies validity of a TrustRegionModel enum.
ETrustRegionModel & operator++ (ETrustRegionModel &type)
ETrustRegionModel operator++ (ETrustRegionModel &type, int)
ETrustRegionModel & operator-- (ETrustRegionModel &type)
ETrustRegionModel operator-- (ETrustRegionModel &type, int)
ETrustRegionModel StringToETrustRegionModel (std::string s)
bool isValidTrustRegionSubproblem (ETrustRegion etr, ETrustRegionModel etrm, bool isBnd)
std::string ETrustRegionFlagToString (ETrustRegionFlag trf)
std::string EDistributionToString (EDistribution ed)
int isValidDistribution (EDistribution ed)
EDistribution & operator++ (EDistribution &type)
EDistribution operator++ (EDistribution &type, int)
EDistribution & operator-- (EDistribution &type)
EDistribution operator-- (EDistribution &type, int)
EDistribution StringToEDistribution (std::string s)
template<class Real >
ROL::Ptr< Distribution< Real > > DistributionFactory (ROL::ParameterList &parlist)
std::string EDeviationMeasureToString (EDeviationMeasure ed)
int isValidDeviationMeasure (EDeviationMeasure ed)
EDeviationMeasure & operator++ (EDeviationMeasure &type)
EDeviationMeasure operator++ (EDeviationMeasure &type, int)
EDeviationMeasure & operator-- (EDeviationMeasure &type)
EDeviationMeasure operator-- (EDeviationMeasure &type, int)
EDeviationMeasure StringToEDeviationMeasure (std::string s)
template<class Real >
Ptr< RandVarFunctional< Real > > DeviationMeasureFactory (ParameterList &parlist)
template<class Real >
void DeviationMeasureInfo (ROL::ParameterList &parlist, std::string &name, int &nStatistic, std::vector< Real > &lower, std::vector< Real > &upper, bool &isBoundActivated, const bool printToStream=false, std::ostream &outStream=std::cout)
std::string EErrorMeasureToString (EErrorMeasure ed)
int isValidErrorMeasure (EErrorMeasure ed)
EErrorMeasure & operator++ (EErrorMeasure &type)
EErrorMeasure operator++ (EErrorMeasure &type, int)
EErrorMeasure & operator-- (EErrorMeasure &type)
EErrorMeasure operator-- (EErrorMeasure &type, int)
EErrorMeasure StringToEErrorMeasure (std::string s)
template<class Real >
Ptr< RandVarFunctional< Real > > ErrorMeasureFactory (ParameterList &parlist)
template<class Real >
void ErrorMeasureInfo (ROL::ParameterList &parlist, std::string &name, int &nStatistic, std::vector< Real > &lower, std::vector< Real > &upper, bool &isBoundActivated, const bool printToStream=false, std::ostream &outStream=std::cout)
std::string EProbabilityToString (EProbability ed)
int isValidProbability (EProbability ed)
EProbability & operator++ (EProbability &type)
EProbability operator++ (EProbability &type, int)
EProbability & operator-- (EProbability &type)
EProbability operator-- (EProbability &type, int)
EProbability StringToEProbability (std::string s)
template<class Real >
Ptr< RandVarFunctional< Real > > ProbabilityFactory (ParameterList &parlist)
template<class Real >
void ProbabilityInfo (ROL::ParameterList &parlist, std::string &name, int &nStatistic, std::vector< Real > &lower, std::vector< Real > &upper, bool &isBoundActivated, const bool printToStream=false, std::ostream &outStream=std::cout)
std::string ERegretMeasureToString (ERegretMeasure ed)
int isValidRegretMeasure (ERegretMeasure ed)
ERegretMeasure & operator++ (ERegretMeasure &type)
ERegretMeasure operator++ (ERegretMeasure &type, int)
ERegretMeasure & operator-- (ERegretMeasure &type)
ERegretMeasure operator-- (ERegretMeasure &type, int)
ERegretMeasure StringToERegretMeasure (std::string s)
template<class Real >
Ptr< RandVarFunctional< Real > > RegretMeasureFactory (ParameterList &parlist)
template<class Real >
void RegretMeasureInfo (ROL::ParameterList &parlist, std::string &name, int &nStatistic, std::vector< Real > &lower, std::vector< Real > &upper, bool &isBoundActivated, const bool printToStream=false, std::ostream &outStream=std::cout)
std::string ERiskMeasureToString (ERiskMeasure ed)
int isValidRiskMeasure (ERiskMeasure ed)
ERiskMeasure & operator++ (ERiskMeasure &type)
ERiskMeasure operator++ (ERiskMeasure &type, int)
ERiskMeasure & operator-- (ERiskMeasure &type)
ERiskMeasure operator-- (ERiskMeasure &type, int)
ERiskMeasure StringToERiskMeasure (std::string s)
template<class Real >
Ptr< RandVarFunctional< Real > > RiskMeasureFactory (ParameterList &parlist)
template<class Real >
void RiskMeasureInfo (ROL::ParameterList &parlist, std::string &name, int &nStatistic, std::vector< Real > &lower, std::vector< Real > &upper, bool &isBoundActivated, const bool printToStream=false, std::ostream &outStream=std::cout)
template<class Real >
Ptr< RandVarFunctional< Real > > RandVarFunctionalFactory (ROL::ParameterList &parlist)
template<class Real >
void RandVarFunctionalInfo (ROL::ParameterList &parlist, std::string &name, int &nStatistic, std::vector< Real > &lower, std::vector< Real > &upper, bool &isBoundActivated, const bool printToStream=false, std::ostream &outStream=std::cout)
template<class Real >
ROL::Ptr< Vector< Real > > CreateSimulatedVector (const ROL::Ptr< Vector< Real > > &a, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
ROL::Ptr< const Vector< Real > > CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > &a, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
ROL::Ptr< Vector< Real > > CreateSimulatedVector (const ROL::Ptr< Vector< Real > > &a, const ROL::Ptr< Vector< Real > > &b, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
ROL::Ptr< const Vector< Real > > CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > &a, const ROL::Ptr< const Vector< Real > > &b, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
ROL::Ptr< Vector< Real > > CreateSimulatedVector (const ROL::Ptr< Vector< Real > > &a, const ROL::Ptr< Vector< Real > > &b, const ROL::Ptr< Vector< Real > > &c, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
ROL::Ptr< const Vector< Real > > CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > &a, const ROL::Ptr< const Vector< Real > > &b, const ROL::Ptr< const Vector< Real > > &c, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
ROL::Ptr< Vector< Real > > CreateSimulatedVector (const ROL::Ptr< Vector< Real > > &a, const ROL::Ptr< Vector< Real > > &b, const ROL::Ptr< Vector< Real > > &c, const ROL::Ptr< Vector< Real > > &d, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
ROL::Ptr< const Vector< Real > > CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > &a, const ROL::Ptr< const Vector< Real > > &b, const ROL::Ptr< const Vector< Real > > &c, const ROL::Ptr< const Vector< Real > > &d, const ROL::Ptr< BatchManager< Real > > &bman)
template<class Real >
Teuchos::SerialDenseMatrix< int, Real > computeDenseHessian (Objective< Real > &obj, const Vector< Real > &x)
template<class Real >
Teuchos::SerialDenseMatrix< int, Real > computeScaledDenseHessian (Objective< Real > &obj, const Vector< Real > &x)
template<class Real >
Teuchos::SerialDenseMatrix< int, Real > computeDotMatrix (const Vector< Real > &x)
template<class Real >
std::vector< std::vector< Real > > computeEigenvalues (const Teuchos::SerialDenseMatrix< int, Real > &mat)
template<class Real >
std::vector< std::vector< Real > > computeGenEigenvalues (const Teuchos::SerialDenseMatrix< int, Real > &A, const Teuchos::SerialDenseMatrix< int, Real > &B)
template<class Real >
Teuchos::SerialDenseMatrix< int, Real > computeInverse (const Teuchos::SerialDenseMatrix< int, Real > &mat)
template<class ParameterType >
void setParameter (ROL::ParameterList &parlist, const std::vector< std::string > &location, const std::vector< std::string >::iterator iter, ParameterType value)
void tierParameterList (ROL::ParameterList &outList, const ROL::ParameterList &inList)
Produce a heirarchical parameter list using the new names from a flat list of the old names.
template<class T >
std::string NumberToString (T Number)
template<class Real >
Real ROL_EPSILON (void)
Platform-dependent machine epsilon.
template<class Real >
Real ROL_THRESHOLD (void)
Tolerance for various equality tests.
template<class Real >
Real ROL_OVERFLOW (void)
Platform-dependent maximum double.
template<class Real >
Real ROL_INF (void)
template<class Real >
Real ROL_NINF (void)
template<class Real >
Real ROL_UNDERFLOW (void)
Platform-dependent minimum double.
std::string EExitStatusToString (EExitStatus tr)
std::string removeStringFormat (std::string s)
std::string EStepToString (EStep tr)
bool isCompatibleStep (EProblem p, EStep s)
std::string EProblemToString (EProblem p)
int isValidStep (EStep ls)
Verifies validity of a TrustRegion enum.
EStep & operator++ (EStep &type)
EStep operator++ (EStep &type, int)
EStep & operator-- (EStep &type)
EStep operator-- (EStep &type, int)
EStep StringToEStep (std::string s)
std::string EDescentToString (EDescent tr)
int isValidDescent (EDescent d)
Verifies validity of a Secant enum.
EDescent & operator++ (EDescent &type)
EDescent operator++ (EDescent &type, int)
EDescent & operator-- (EDescent &type)
EDescent operator-- (EDescent &type, int)
EDescent StringToEDescent (std::string s)
std::string ESecantToString (ESecant tr)
int isValidSecant (ESecant s)
Verifies validity of a Secant enum.
ESecant & operator++ (ESecant &type)
ESecant operator++ (ESecant &type, int)
ESecant & operator-- (ESecant &type)
ESecant operator-- (ESecant &type, int)
ESecant StringToESecant (std::string s)
std::string ENonlinearCGToString (ENonlinearCG tr)
int isValidNonlinearCG (ENonlinearCG s)
Verifies validity of a NonlinearCG enum.
ENonlinearCG & operator++ (ENonlinearCG &type)
ENonlinearCG operator++ (ENonlinearCG &type, int)
ENonlinearCG & operator-- (ENonlinearCG &type)
ENonlinearCG operator-- (ENonlinearCG &type, int)
ENonlinearCG StringToENonlinearCG (std::string s)
std::string ELineSearchToString (ELineSearch ls)
int isValidLineSearch (ELineSearch ls)
Verifies validity of a LineSearch enum.
ELineSearch & operator++ (ELineSearch &type)
ELineSearch operator++ (ELineSearch &type, int)
ELineSearch & operator-- (ELineSearch &type)
ELineSearch operator-- (ELineSearch &type, int)
ELineSearch StringToELineSearch (std::string s)
std::string ECurvatureConditionToString (ECurvatureCondition ls)
int isValidCurvatureCondition (ECurvatureCondition ls)
Verifies validity of a CurvatureCondition enum.
ECurvatureCondition & operator++ (ECurvatureCondition &type)
ECurvatureCondition operator++ (ECurvatureCondition &type, int)
ECurvatureCondition & operator-- (ECurvatureCondition &type)
ECurvatureCondition operator-- (ECurvatureCondition &type, int)
ECurvatureCondition StringToECurvatureCondition (std::string s)
std::string ECGFlagToString (ECGFlag cgf)
template<class Element , class Real >
Real rol_cast (const Element &val)
ROL::Ptr< const ROL::ParameterList > getValidROLParameters ()
ROL::Ptr< const ROL::ParameterList > getValidSOLParameters ()
std::string ETestOptProblemToString (ETestOptProblem to)
int isValidTestOptProblem (ETestOptProblem to)
Verifies validity of a TestOptProblem enum.
ETestOptProblem & operator++ (ETestOptProblem &type)
ETestOptProblem operator++ (ETestOptProblem &type, int)
ETestOptProblem & operator-- (ETestOptProblem &type)
ETestOptProblem operator-- (ETestOptProblem &type, int)
ETestOptProblem StringToETestOptProblem (std::string s)
template<class Real >
void GetTestProblem (Ptr< OptimizationProblem< Real > > &problem, Ptr< Vector< Real > > &x0, std::vector< Ptr< Vector< Real > > > &x, const ETestOptProblem test)
void addJSONBlockToPL (const Json::Value &block, ROL::ParameterList &parlist)
Iterate over a block and insert key-value pairs into the ROL::ParameterList.
void addJSONPairToPL (const Json::Value &block, const std::string &key, ROL::ParameterList &parlist)
Given a JSON block and a key, get the value and insert the key-value pair into a ROL::ParameterList. If the value is itself a block, recursively iterate.
void JSON_Parameters (const std::string &jsonFileName, ROL::ParameterList &parlist)
Read a JSON file and store all parameters in a ROL::ParameterList. Checks for a key called "Algorithm" which has a string value which can specify a Step Type (Linesearch or Trust-Region) and either a Descent Type or a Trust-Region Subproblem Solver Type.
template<class Real >
void stepFactory (ROL::ParameterList &parlist, ROL::Ptr< ROL::Step< Real > > &step)
A minimalist step factory which specializes the Step Type depending on whether a Trust-Region or Linesearch has been selected.
Typedef Documentation
TimeStampsPtr
template<typename Real > using ROL::TimeStampsPtr = typedef Ptr<std::vector<TimeStamp<Real> >>
Definition at line 31 of file ROL_TimeStamp.hpp.
Enumeration Type Documentation
EPolyProjAlgo
enum ROL::EPolyProjAlgo
Enumerator
PPA_DAIFLETCHER
PPA_DYKSTRA
PPA_DOUGLASRACHFORD
PPA_NEWTON
PPA_RIDDERS
PPA_BRENTS
PPA_LAST
Definition at line 30 of file ROL_PolyhedralProjectionFactory.hpp.
UpdateType
enum class ROL::UpdateType : std::uint8_t strong
Enumerator
Initial
Accept
Revert
Trial
Temp
Definition at line 18 of file ROL_UpdateType.hpp.
EDescentU
enum ROL::EDescentU
Enumerator
DESCENT_U_STEEPEST
DESCENT_U_NONLINEARCG
DESCENT_U_SECANT
DESCENT_U_NEWTON
DESCENT_U_NEWTONKRYLOV
DESCENT_U_USERDEFINED
DESCENT_U_LAST
Definition at line 30 of file ROL_LineSearch_U_Types.hpp.
ELineSearchU
enum ROL::ELineSearchU
Enumerator
LINESEARCH_U_ITERATIONSCALING
LINESEARCH_U_PATHBASEDTARGETLEVEL
LINESEARCH_U_BACKTRACKING
LINESEARCH_U_BISECTION
LINESEARCH_U_GOLDENSECTION
LINESEARCH_U_CUBICINTERP
LINESEARCH_U_BRENTS
LINESEARCH_U_USERDEFINED
LINESEARCH_U_LAST
Definition at line 110 of file ROL_LineSearch_U_Types.hpp.
ECurvatureConditionU
enum ROL::ECurvatureConditionU
Enumerator
CURVATURECONDITION_U_WOLFE
CURVATURECONDITION_U_STRONGWOLFE
CURVATURECONDITION_U_GENERALIZEDWOLFE
CURVATURECONDITION_U_APPROXIMATEWOLFE
CURVATURECONDITION_U_GOLDSTEIN
CURVATURECONDITION_U_NULL
CURVATURECONDITION_U_LAST
Definition at line 193 of file ROL_LineSearch_U_Types.hpp.
ETrustRegionU
enum ROL::ETrustRegionU
Enumerator
TRUSTREGION_U_CAUCHYPOINT
TRUSTREGION_U_TRUNCATEDCG
TRUSTREGION_U_SPG
TRUSTREGION_U_DOGLEG
TRUSTREGION_U_DOUBLEDOGLEG
TRUSTREGION_U_LAST
Definition at line 29 of file ROL_TrustRegion_U_Types.hpp.
EKrylov
enum ROL::EKrylov
Enumerator
KRYLOV_CG
KRYLOV_CR
KRYLOV_GMRES
KRYLOV_MINRES
KRYLOV_BICGSTAB
KRYLOV_USERDEFINED
KRYLOV_LAST
Definition at line 34 of file ROL_KrylovFactory.hpp.
ESecantMode
enum ROL::ESecantMode
Enumerator
SECANTMODE_FORWARD
SECANTMODE_INVERSE
SECANTMODE_BOTH
Definition at line 23 of file ROL_Secant.hpp.
ETrustRegion
enum ROL::ETrustRegion
Enumerator
TRUSTREGION_CAUCHYPOINT
TRUSTREGION_TRUNCATEDCG
TRUSTREGION_DOGLEG
TRUSTREGION_DOUBLEDOGLEG
TRUSTREGION_LINMORE
TRUSTREGION_LAST
Definition at line 30 of file ROL_TrustRegionTypes.hpp.
ETrustRegionModel
enum ROL::ETrustRegionModel
Enumerator
TRUSTREGION_MODEL_COLEMANLI
TRUSTREGION_MODEL_KELLEYSACHS
TRUSTREGION_MODEL_LINMORE
TRUSTREGION_MODEL_LAST
Definition at line 103 of file ROL_TrustRegionTypes.hpp.
ETrustRegionFlag
enum ROL::ETrustRegionFlag
Enumerator
TRUSTREGION_FLAG_SUCCESS
TRUSTREGION_FLAG_POSPREDNEG
TRUSTREGION_FLAG_NPOSPREDPOS
TRUSTREGION_FLAG_NPOSPREDNEG
TRUSTREGION_FLAG_QMINSUFDEC
TRUSTREGION_FLAG_NAN
TRUSTREGION_FLAG_UNDEFINED
Definition at line 198 of file ROL_TrustRegionTypes.hpp.
EDistribution
enum ROL::EDistribution
Enumerator
DISTRIBUTION_ARCSINE
DISTRIBUTION_BETA
DISTRIBUTION_CAUCHY
DISTRIBUTION_DIRAC
DISTRIBUTION_EXPONENTIAL
DISTRIBUTION_GAMMA
DISTRIBUTION_GAUSSIAN
DISTRIBUTION_KUMARASWAMY
DISTRIBUTION_LAPLACE
DISTRIBUTION_LOGISTIC
DISTRIBUTION_PARABOLIC
DISTRIBUTION_RAISEDCOSINE
DISTRIBUTION_SMALE
DISTRIBUTION_TRIANGLE
DISTRIBUTION_TRUNCATEDEXPONENTIAL
DISTRIBUTION_TRUNCATEDGAUSSIAN
DISTRIBUTION_UNIFORM
DISTRIBUTION_LAST
Definition at line 35 of file ROL_DistributionFactory.hpp.
EDeviationMeasure
enum ROL::EDeviationMeasure
Enumerator
DEVIATIONMEASURE_MEANVARIANCEQUADRANGLE
DEVIATIONMEASURE_TRUNCATEDMEANQUADRANGLE
DEVIATIONMEASURE_QUANTILEQUADRANGLE
DEVIATIONMEASURE_MOREAUYOSIDACVAR
DEVIATIONMEASURE_GENMOREAUYOSIDACVAR
DEVIATIONMEASURE_LOGEXPONENTIALQUADRANGLE
DEVIATIONMEASURE_LOGQUANTILEQUADRANGLE
DEVIATIONMEASURE_SMOOTHEDWORSTCASEQUADRANGLE
DEVIATIONMEASURE_LAST
Definition at line 30 of file ROL_DeviationMeasureFactory.hpp.
EErrorMeasure
enum ROL::EErrorMeasure
Enumerator
ERRORMEASURE_MEANVARIANCEQUADRANGLE
ERRORMEASURE_TRUNCATEDMEANQUADRANGLE
ERRORMEASURE_QUANTILEQUADRANGLE
ERRORMEASURE_MOREAUYOSIDACVAR
ERRORMEASURE_GENMOREAUYOSIDACVAR
ERRORMEASURE_LOGEXPONENTIALQUADRANGLE
ERRORMEASURE_LOGQUANTILEQUADRANGLE
ERRORMEASURE_SMOOTHEDWORSTCASEQUADRANGLE
ERRORMEASURE_LAST
Definition at line 30 of file ROL_ErrorMeasureFactory.hpp.
EProbability
enum ROL::EProbability
Enumerator
PROBABILITY_BPOE
PROBABILITY_SMOOTHEDPOE
PROBABILITY_LAST
Definition at line 21 of file ROL_ProbabilityFactory.hpp.
ERegretMeasure
enum ROL::ERegretMeasure
Enumerator
REGRETMEASURE_MEANABSOLUTELOSS
REGRETMEASURE_MOREAUYOSIDAMEANABSOLUTELOSS
REGRETMEASURE_GENMOREAUYOSIDAMEANABSOLUTELOSS
REGRETMEASURE_EXPONENTIAL
REGRETMEASURE_MEANL2
REGRETMEASURE_TRUNCATEDMEAN
REGRETMEASURE_LOGQUANTILE
REGRETMEASURE_SMOOTHEDWORSTCASE
REGRETMEASURE_LAST
Definition at line 27 of file ROL_RegretMeasureFactory.hpp.
ERiskMeasure
enum ROL::ERiskMeasure
Enumerator
RISKMEASURE_CVAR
RISKMEASURE_MOREAUYOSIDACVAR
RISKMEASURE_GENMOREAUYOSIDACVAR
RISKMEASURE_MIXEDCVAR
RISKMEASURE_SPECTRALRISK
RISKMEASURE_SECONDORDERCVAR
RISKMEASURE_CHEBYSHEVSPECTRAL
RISKMEASURE_QUANTILERADIUS
RISKMEASURE_HMCR
RISKMEASURE_ENTROPICRISK
RISKMEASURE_COHERENTENTROPICRISK
RISKMEASURE_MEANSEMIDEVIATION
RISKMEASURE_MEANSEMIDEVIATIONFROMTARGET
RISKMEASURE_MEANDEVIATIONFROMTARGET
RISKMEASURE_MEANDEVIATION
RISKMEASURE_MEANVARIANCEFROMTARGET
RISKMEASURE_MEANVARIANCE
RISKMEASURE_TRUNCATEDMEAN
RISKMEASURE_LOGQUANTILE
RISKMEASURE_SMOOTHEDWORSTCASE
RISKMEASURE_LOGEXPONENTIAL
RISKMEASURE_SAFETYMARGIN
RISKMEASURE_CHI2DIVERGENCE
RISKMEASURE_KLDIVERGENCE
RISKMEASURE_LAST
Definition at line 50 of file ROL_RiskMeasureFactory.hpp.
EAbsoluteValue
enum ROL::EAbsoluteValue
Enumerator
ABSOLUTEVALUE_TRUE
ABSOLUTEVALUE_SQUAREROOT
ABSOLUTEVALUE_SQRTDENOM
ABSOLUTEVALUE_C2
ABSOLUTEVALUE_LAST
Definition at line 19 of file ROL_AbsoluteValue.hpp.
EExitStatus
enum ROL::EExitStatus
Enum for algorithm termination.
Enumerator
EXITSTATUS_CONVERGED
EXITSTATUS_MAXITER
EXITSTATUS_STEPTOL
EXITSTATUS_NAN
EXITSTATUS_USERDEFINED
EXITSTATUS_LAST
Definition at line 83 of file ROL_Types.hpp.
EProblem
enum ROL::EProblem
Enumerator
TYPE_U
TYPE_P
TYPE_B
TYPE_E
TYPE_EB
TYPE_LAST
Definition at line 223 of file ROL_Types.hpp.
EStep
enum ROL::EStep
Enumerator
STEP_AUGMENTEDLAGRANGIAN
STEP_BUNDLE
STEP_COMPOSITESTEP
STEP_LINESEARCH
STEP_MOREAUYOSIDAPENALTY
STEP_PRIMALDUALACTIVESET
STEP_TRUSTREGION
STEP_INTERIORPOINT
STEP_FLETCHER
STEP_LAST
Definition at line 243 of file ROL_Types.hpp.
EDescent
enum ROL::EDescent
Enumerator
DESCENT_STEEPEST
DESCENT_NONLINEARCG
DESCENT_SECANT
DESCENT_NEWTON
DESCENT_NEWTONKRYLOV
DESCENT_LAST
Definition at line 381 of file ROL_Types.hpp.
ESecant
enum ROL::ESecant
Enumerator
SECANT_LBFGS
SECANT_LDFP
SECANT_LSR1
SECANT_BARZILAIBORWEIN
SECANT_USERDEFINED
SECANT_LAST
Definition at line 456 of file ROL_Types.hpp.
ENonlinearCG
enum ROL::ENonlinearCG
Enumerator
NONLINEARCG_HESTENES_STIEFEL
NONLINEARCG_FLETCHER_REEVES
NONLINEARCG_DANIEL
NONLINEARCG_POLAK_RIBIERE
NONLINEARCG_FLETCHER_CONJDESC
NONLINEARCG_LIU_STOREY
NONLINEARCG_DAI_YUAN
NONLINEARCG_HAGER_ZHANG
NONLINEARCG_OREN_LUENBERGER
NONLINEARCG_USERDEFINED
NONLINEARCG_LAST
Definition at line 536 of file ROL_Types.hpp.
ELineSearch
enum ROL::ELineSearch
Enumerator
LINESEARCH_ITERATIONSCALING
LINESEARCH_PATHBASEDTARGETLEVEL
LINESEARCH_BACKTRACKING
LINESEARCH_BISECTION
LINESEARCH_GOLDENSECTION
LINESEARCH_CUBICINTERP
LINESEARCH_BRENTS
LINESEARCH_USERDEFINED
LINESEARCH_LAST
Definition at line 628 of file ROL_Types.hpp.
ECurvatureCondition
enum ROL::ECurvatureCondition
Enumerator
CURVATURECONDITION_WOLFE
CURVATURECONDITION_STRONGWOLFE
CURVATURECONDITION_GENERALIZEDWOLFE
CURVATURECONDITION_APPROXIMATEWOLFE
CURVATURECONDITION_GOLDSTEIN
CURVATURECONDITION_NULL
CURVATURECONDITION_LAST
Definition at line 711 of file ROL_Types.hpp.
ECGFlag
enum ROL::ECGFlag
Enumerator
CG_FLAG_SUCCESS
CG_FLAG_ITEREXCEED
CG_FLAG_NEGCURVE
CG_FLAG_TRRADEX
CG_FLAG_ZERORHS
CG_FLAG_UNDEFINED
Definition at line 791 of file ROL_Types.hpp.
ETestOptProblem
enum ROL::ETestOptProblem
Enumerator
TESTOPTPROBLEM_ROSENBROCK
TESTOPTPROBLEM_FREUDENSTEINANDROTH
TESTOPTPROBLEM_BEALE
TESTOPTPROBLEM_POWELL
TESTOPTPROBLEM_SUMOFSQUARES
TESTOPTPROBLEM_LEASTSQUARES
TESTOPTPROBLEM_POISSONCONTROL
TESTOPTPROBLEM_POISSONINVERSION
TESTOPTPROBLEM_ZAKHAROV
TESTOPTPROBLEM_HS1
TESTOPTPROBLEM_HS2
TESTOPTPROBLEM_HS3
TESTOPTPROBLEM_HS4
TESTOPTPROBLEM_HS5
TESTOPTPROBLEM_HS9
TESTOPTPROBLEM_HS14
TESTOPTPROBLEM_HS21
TESTOPTPROBLEM_HS24
TESTOPTPROBLEM_HS25
TESTOPTPROBLEM_HS28
TESTOPTPROBLEM_HS29
TESTOPTPROBLEM_HS32
TESTOPTPROBLEM_HS38
TESTOPTPROBLEM_HS39
TESTOPTPROBLEM_HS41
TESTOPTPROBLEM_HS42
TESTOPTPROBLEM_HS45
TESTOPTPROBLEM_HS48
TESTOPTPROBLEM_HS49
TESTOPTPROBLEM_HS50
TESTOPTPROBLEM_HS51
TESTOPTPROBLEM_HS52
TESTOPTPROBLEM_HS53
TESTOPTPROBLEM_HS55
TESTOPTPROBLEM_HS63
TESTOPTPROBLEM_BVP
TESTOPTPROBLEM_PARABOLOIDCIRCLE
TESTOPTPROBLEM_SIMPLEEQCONSTRAINED
TESTOPTPROBLEM_CANTILEVERBEAM
TESTOPTPROBLEM_CUBIC
TESTOPTPROBLEM_QUARTIC
TESTOPTPROBLEM_CYLINDERHEAD
TESTOPTPROBLEM_CANTILEVER
TESTOPTPROBLEM_MINIMAX1
TESTOPTPROBLEM_MINIMAX2
TESTOPTPROBLEM_MINIMAX3
TESTOPTPROBLEM_LAST
Definition at line 119 of file ROL_GetTestProblems.hpp.
Function Documentation
partition() [1/4]
template<typename Real > PartitionedVector< Real > & ROL::partition (Vector< Real > & x) inline
Definition at line 261 of file ROL_PartitionedVector.hpp.
Referenced by ROL::SerialConstraint< Real >::applyAdjointHessian_11(), ROL::SerialConstraint< Real >::applyAdjointHessian_22(), ROL::SerialConstraint< Real >::applyAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyAdjointJacobian_2(), ROL::SerialConstraint< Real >::applyInverseAdjointJacobian_1(), ROL::SerialConstraint< Real >::applyInverseJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_1(), ROL::SerialConstraint< Real >::applyJacobian_2(), ROL::DynamicFunction< Real >::getNew(), ROL::DynamicFunction< Real >::getNew(), ROL::DynamicFunction< Real >::getOld(), ROL::DynamicFunction< Real >::getOld(), gradient_1(), ROL::SerialObjective< Real >::gradient_1(), gradient_2(), ROL::SerialObjective< Real >::gradient_2(), hessVec_11(), ROL::SerialObjective< Real >::hessVec_11(), hessVec_12(), ROL::SerialObjective< Real >::hessVec_12(), hessVec_21(), ROL::SerialObjective< Real >::hessVec_21(), hessVec_22(), ROL::SerialObjective< Real >::hessVec_22(), ROL::SerialConstraint< Real >::solve(), ROL::SerialConstraint< Real >::update(), ROL::SerialObjective< Real >::value(), and ROL::SerialConstraint< Real >::value().
partition() [2/4]
template<typename Real > const PartitionedVector< Real > & ROL::partition (const Vector< Real > & x) inline
Definition at line 266 of file ROL_PartitionedVector.hpp.
partition() [3/4]
template<typename Real > Ptr< PartitionedVector< Real > > ROL::partition (const Ptr< Vector< Real > > & x) inline
Definition at line 271 of file ROL_PartitionedVector.hpp.
partition() [4/4]
template<typename Real > Ptr< const PartitionedVector< Real > > ROL::partition (const Ptr< const Vector< Real > > & x) inline
Definition at line 276 of file ROL_PartitionedVector.hpp.
CreatePartitionedVector() [1/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< Vector< Real > > & a)
Definition at line 284 of file ROL_PartitionedVector.hpp.
Referenced by main(), ROL::PrimalDualSystemStep< Real >::repartition(), and ROL::PrimalDualSystemStep< Real >::repartition().
CreatePartitionedVector() [2/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > & a)
Definition at line 295 of file ROL_PartitionedVector.hpp.
CreatePartitionedVector() [3/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< Vector< Real > > & a, const ROL::Ptr< Vector< Real > > & b)
Definition at line 306 of file ROL_PartitionedVector.hpp.
CreatePartitionedVector() [4/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > & a, const ROL::Ptr< const Vector< Real > > & b)
Definition at line 317 of file ROL_PartitionedVector.hpp.
CreatePartitionedVector() [5/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< Vector< Real > > & a, const ROL::Ptr< Vector< Real > > & b, const ROL::Ptr< Vector< Real > > & c)
Definition at line 329 of file ROL_PartitionedVector.hpp.
CreatePartitionedVector() [6/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > & a, const ROL::Ptr< const Vector< Real > > & b, const ROL::Ptr< const Vector< Real > > & c)
Definition at line 342 of file ROL_PartitionedVector.hpp.
CreatePartitionedVector() [7/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< Vector< Real > > & a, const ROL::Ptr< Vector< Real > > & b, const ROL::Ptr< Vector< Real > > & c, const ROL::Ptr< Vector< Real > > & d)
Definition at line 355 of file ROL_PartitionedVector.hpp.
CreatePartitionedVector() [8/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreatePartitionedVector (const ROL::Ptr< const Vector< Real > > & a, const ROL::Ptr< const Vector< Real > > & b, const ROL::Ptr< const Vector< Real > > & c, const ROL::Ptr< const Vector< Real > > & d)
Definition at line 370 of file ROL_PartitionedVector.hpp.
getVectorFunctionCalls()
template<class Ordinal , class Real > VectorFunctionCalls< Ordinal > ROL::getVectorFunctionCalls (const ProfiledVector< Ordinal, Real > & x)
Definition at line 69 of file ROL_ProfiledVector.hpp.
printVectorFunctionCalls()
template<class Ordinal , class Real > void ROL::printVectorFunctionCalls (const ProfiledVector< Ordinal, Real > & x, std::ostream & outStream = std::cout)
Definition at line 74 of file ROL_ProfiledVector.hpp.
Referenced by main().
make_Vector_SimOpt()
template<template< typename > class V, typename Real , typename P = Ptr<Vector<Real>>> std::enable_if< std::is_base_of< Vector< Real >, V< Real > >::value, P >::type ROL::make_Vector_SimOpt (const Ptr< V< Real > > & vsim, const Ptr< V< Real > > & vopt) inline
Definition at line 174 of file ROL_Vector_SimOpt.hpp.
CreateBoundConstraint_Partitioned()
template<typename Real > Ptr< BoundConstraint< Real > > ROL::CreateBoundConstraint_Partitioned (const Ptr< BoundConstraint< Real > > & bnd1, const Ptr< BoundConstraint< Real > > & bnd2)
Definition at line 212 of file ROL_BoundConstraint_Partitioned.hpp.
make_check() [1/4]
template<typename Real > DynamicConstraint_CheckInterface< Real > ROL::make_check (DynamicConstraint< Real > & con)
Definition at line 226 of file ROL_DynamicConstraint_CheckInterface.hpp.
Referenced by ROL::DynamicConstraintCheck< Real >::check(), ROL::DynamicConstraintCheck< Real >::check(), ROL::DynamicObjectiveCheck< Real >::check(), and ROL::DynamicObjectiveCheck< Real >::check().
make_check() [2/4]
template<typename Real > DynamicConstraint_CheckInterface< Real > ROL::make_check (DynamicConstraint< Real > & con, TimeStamp< Real > & timeStamp)
Definition at line 231 of file ROL_DynamicConstraint_CheckInterface.hpp.
make_check() [3/4]
template<typename Real > DynamicObjective_CheckInterface< Real > ROL::make_check (DynamicObjective< Real > & obj)
Definition at line 177 of file ROL_DynamicObjective_CheckInterface.hpp.
make_check() [4/4]
template<typename Real > DynamicObjective_CheckInterface< Real > ROL::make_check (DynamicObjective< Real > & obj, TimeStamp< Real > & ts)
Definition at line 182 of file ROL_DynamicObjective_CheckInterface.hpp.
make_DynamicTrackingFEMObjective()
template<typename Real > Ptr< DynamicObjective< Real > > ROL::make_DynamicTrackingFEMObjective (const Ptr< PartitionedVector< Real > > & target, Real alpha = 0.0) inline
Definition at line 177 of file ROL_DynamicTrackingFEMObjective.hpp.
make_DynamicTrackingObjective()
template<typename Real > Ptr< DynamicObjective< Real > > ROL::make_DynamicTrackingObjective (const Ptr< PartitionedVector< Real > > & target, Real alpha = 0.0) inline
Definition at line 168 of file ROL_DynamicTrackingObjective.hpp.
make_SerialConstraint()
template<typename DynCon , typename Real , typename P = Ptr<SerialConstraint<Real>>> std::enable_if< std::is_base_of< DynamicConstraint< Real >, DynCon >::value, P >::type ROL::make_SerialConstraint (const Ptr< DynCon > & con, const Vector< Real > & u_initial, const TimeStampsPtr< Real > timeStampsPtr) inline
Definition at line 345 of file ROL_SerialConstraint.hpp.
make_SerialObjective()
template<typename DynObj , typename Real , typename P = Ptr<SerialObjective<Real>>> std::enable_if< std::is_base_of< DynamicObjective< Real >, DynObj >::value, P >::type ROL::make_SerialObjective (const Ptr< DynObj > & obj, const Vector< Real > & u_initial, const TimeStampsPtr< Real > timeStampsPtr) inline
Definition at line 235 of file ROL_SerialObjective.hpp.
apply() [1/3]
template<class Real > ROL::BlockOperator2Diagonal BlockOperator2 ROL::apply (V & Hv, const V & v, Real & tol) const
Definition at line 1 of file ROL_BlockOperator2Diagonal.hpp.
Referenced by ROL::ColemanLiModel< Real >::computeAlpha(), ROL::ColemanLiModel< Real >::computeFullReflectiveStep(), ROL::ColemanLiModel< Real >::computeReflectiveStep(), ROL::ColemanLiModel< Real >::constructC(), ROL::LogBarrierObjective< Real >::dirDeriv(), ROL::ColemanLiModel< Real >::getScalarBounds(), ROL::LogBarrierObjective< Real >::hessVec(), ROL::ColemanLiModel< Real >::isStrictlyFeasibleStep(), ROL::Bounds< Real >::project(), and ROL::Bounds< Real >::projectInterior().
applyInverse()
void ROL::applyInverse (V & Hv, const V &v Real & tol) const
Definition at line 61 of file ROL_BlockOperator2Diagonal.hpp.
References A_, and D_.
getOperator()
ROL::Ptr< LinearOperator< Real > > ROL::getOperator (int row, int col) const
Definition at line 77 of file ROL_BlockOperator2Diagonal.hpp.
References A_, and D_.
apply() [2/3]
template<class Real > ROL::BlockOperator2UnitLower LinearOperator ROL::apply (V & Hv, const V & v, Real & tol) const
Definition at line 1 of file ROL_BlockOperator2UnitLower.hpp.
apply() [3/3]
template<class Real > ROL::BlockOperator2UnitUpper LinearOperator ROL::apply (V & Hv, const V & v, Real & tol) const
Definition at line 1 of file ROL_BlockOperator2UnitUpper.hpp.
EPolyProjAlgoToString()
std::string ROL::EPolyProjAlgoToString (EPolyProjAlgo alg) inline
Definition at line 40 of file ROL_PolyhedralProjectionFactory.hpp.
References PPA_BRENTS, PPA_DAIFLETCHER, PPA_DOUGLASRACHFORD, PPA_DYKSTRA, PPA_LAST, PPA_NEWTON, and PPA_RIDDERS.
Referenced by StringToEPolyProjAlgo().
isValidPolyProjAlgo()
int ROL::isValidPolyProjAlgo (EPolyProjAlgo alg) inline
Verifies validity of a PolyProjAlgo enum.
Parameters
ls [in] - enum of the PolyProjAlgo
Returns
1 if the argument is a valid PolyProjAlgo; 0 otherwise.
Definition at line 60 of file ROL_PolyhedralProjectionFactory.hpp.
References PPA_BRENTS, PPA_DAIFLETCHER, PPA_DOUGLASRACHFORD, PPA_DYKSTRA, PPA_LAST, PPA_NEWTON, and PPA_RIDDERS.
operator++() [1/42]
EPolyProjAlgo & ROL::operator++ (EPolyProjAlgo & type) inline
Definition at line 71 of file ROL_PolyhedralProjectionFactory.hpp.
operator++() [2/42]
EPolyProjAlgo ROL::operator++ (EPolyProjAlgo & type, int) inline
Definition at line 75 of file ROL_PolyhedralProjectionFactory.hpp.
operator--() [1/42]
EPolyProjAlgo & ROL::operator-- (EPolyProjAlgo & type) inline
Definition at line 81 of file ROL_PolyhedralProjectionFactory.hpp.
operator--() [2/42]
EPolyProjAlgo ROL::operator-- (EPolyProjAlgo & type, int) inline
Definition at line 85 of file ROL_PolyhedralProjectionFactory.hpp.
StringToEPolyProjAlgo()
EPolyProjAlgo ROL::StringToEPolyProjAlgo (std::string s) inline
Definition at line 91 of file ROL_PolyhedralProjectionFactory.hpp.
References EPolyProjAlgoToString(), PPA_DAIFLETCHER, PPA_DYKSTRA, PPA_LAST, and removeStringFormat().
Referenced by PolyhedralProjectionFactory().
PolyhedralProjectionFactory()
template<typename Real > Ptr< PolyhedralProjection< Real > > ROL::PolyhedralProjectionFactory (const Vector< Real > & xprim, const Vector< Real > & xdual, const Ptr< BoundConstraint< Real > > & bnd, const Ptr< Constraint< Real > > & con, const Vector< Real > & mul, const Vector< Real > & res, ParameterList & list) inline
Definition at line 102 of file ROL_PolyhedralProjectionFactory.hpp.
References PPA_BRENTS, PPA_DAIFLETCHER, PPA_DOUGLASRACHFORD, PPA_DYKSTRA, PPA_NEWTON, PPA_RIDDERS, and StringToEPolyProjAlgo().
UpdateTypeToString()
std::string ROL::UpdateTypeToString (const UpdateType & type) inline
Definition at line 27 of file ROL_UpdateType.hpp.
References Accept, Initial, Revert, Temp, and Trial.
normL1()
template<class Real > Real ROL::normL1 (const Vector< Real > & x)
Definition at line 18 of file ROL_VectorNorms.hpp.
References ROL::Vector< Real >::clone().
normLp()
template<class Real , class Exponent > Real ROL::normLp (const Vector< Real > & x, Exponent p)
Definition at line 28 of file ROL_VectorNorms.hpp.
References ROL::Vector< Real >::clone().
normLinf()
template<class Real > Real ROL::normLinf (const Vector< Real > & x)
Definition at line 39 of file ROL_VectorNorms.hpp.
References ROL::Vector< Real >::clone().
value() [1/3]
template<typename Real > ROL::Objective_SerialSimOpt Objective_SimOpt ROL::value (const V & u, const V & z, Real & tol) override
Definition at line 1 of file ROL_Objective_SerialSimOpt.hpp.
Referenced by ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Constraint< Real >::applyJacobian(), ROL::DynamicObjectiveCheck< Real >::check(), ROL::Constraint< RealT >::checkApplyAdjointHessian(), ROL::Constraint< Real >::checkApplyAdjointJacobian(), ROL::Objective< Real >::checkGradient(), getValidROLParameters(), ROL::FletcherStep< Real >::getValueString(), ROL::StdObjective< Real >::gradient(), ROL::Objective< Real >::gradient(), setParameter(), tierParameterList(), value(), and ROL::StdObjective< Real >::value().
gradient_1() [1/2]
virtual void ROL::gradient_1 (V & g, const V & u, const V & z, Real & tol) override virtual
Definition at line 64 of file ROL_Objective_SerialSimOpt.hpp.
References partition().
gradient_2() [1/3]
virtual void ROL::gradient_2 (V & g, const V & u, const V & z, Real & tol) override virtual
Definition at line 78 of file ROL_Objective_SerialSimOpt.hpp.
References obj_, partition(), and ui_.
Referenced by gradient_2().
hessVec_11() [1/2]
virtual void ROL::hessVec_11 (V & hv, const V & v, const V & u, const V & z, Real & tol) override virtual
Definition at line 92 of file ROL_Objective_SerialSimOpt.hpp.
References obj_, partition(), and ui_.
Referenced by hessVec_11().
hessVec_12() [1/2]
virtual void ROL::hessVec_12 (V & hv, const V & v, const V & u, const V & z, Real & tol) override virtual
Definition at line 109 of file ROL_Objective_SerialSimOpt.hpp.
References obj_, partition(), and ui_.
hessVec_21() [1/2]
virtual void ROL::hessVec_21 (V & hv, const V & v, const V & u, const V & z, Real & tol) override virtual
Definition at line 125 of file ROL_Objective_SerialSimOpt.hpp.
References obj_, partition(), and ui_.
hessVec_22() [1/2]
virtual void ROL::hessVec_22 (V & hv, const V & v, const V & u, const V & z, Real & tol) override virtual
Definition at line 141 of file ROL_Objective_SerialSimOpt.hpp.
References obj_, partition(), and ui_.
update_1_old()
virtual void ROL::update_1_old (const Vector< Real > & u_old, bool flag = true, int iter = -1) virtual
Update constraint functions with respect to Sim variable.
u_old is the state variable flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Definition at line 94 of file ROL_Objective_TimeSimOpt.hpp.
Referenced by ROL::Objective_TimeSimOpt< Real >::update().
update_1_new()
virtual void ROL::update_1_new (const Vector< Real > & u_new, bool flag = true, int iter = -1) virtual
Update constraint functions with respect to Sim variable.
u_new is the state variable flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Definition at line 101 of file ROL_Objective_TimeSimOpt.hpp.
Referenced by ROL::Objective_TimeSimOpt< Real >::update().
update_2()
virtual void ROL::update_2 (const Vector< Real > & z, bool flag = true, int iter = -1) override virtual
Update constraint functions with respect to Opt variable. z is the control variable, flag = true if optimization variable is changed, iter is the outer algorithm iterations count.
Definition at line 108 of file ROL_Objective_TimeSimOpt.hpp.
Referenced by ROL::CompositeConstraint_SimOpt< Real >::update(), ROL::CompositeConstraint_SimOpt< Real >::update(), and ROL::Objective_TimeSimOpt< Real >::update().
value() [2/3]
virtual Real ROL::value (const Vector< Real > & u_old, const Vector< Real > & u_new, const Vector< Real > & z, Real & tol) virtual
Compute contribution to objective value from this time step.
Definition at line 112 of file ROL_Objective_TimeSimOpt.hpp.
gradient_1_old()
virtual void ROL::gradient_1_old (Vector< Real > & g, const Vector< Real > & u_old, Vector< Real > & u_new, const Vector< Real > & z, Real & tol) virtual
Compute contribution to simulation term gradient from this time step.
Definition at line 117 of file ROL_Objective_TimeSimOpt.hpp.
Referenced by gradient_1().
gradient_1_new()
virtual void ROL::gradient_1_new (Vector< Real > & g, const Vector< Real > & u_old, Vector< Real > & u_new, const Vector< Real > & z, Real & tol) virtual
Compute contribution to simulation term gradient from this time step.
Definition at line 121 of file ROL_Objective_TimeSimOpt.hpp.
Referenced by gradient_1().
gradient_2() [2/3]
virtual void ROL::gradient_2 (Vector< Real > & g, const Vector< Real > & u_old, Vector< Real > & u_new, const Vector< Real > & z, Real & tol) override virtual
Compute contribution to optimization term gradient from this time step.
Definition at line 126 of file ROL_Objective_TimeSimOpt.hpp.
hessVec_11_old()
virtual void ROL::hessVec_11_old (Vector< Real > & hv, const Vector< Real > & v_old, const Vector< Real > & u_old, const Vector< Real > & u_new, const Vector< Real > & z, Real & tol) virtual
Definition at line 129 of file ROL_Objective_TimeSimOpt.hpp.
hessVec_11_new()
virtual void ROL::hessVec_11_new (Vector< Real > & hv, const Vector< Real > & v_new, const Vector< Real > & u_old, const Vector< Real > & u_new, const Vector< Real > & z, Real & tol) virtual
Definition at line 133 of file ROL_Objective_TimeSimOpt.hpp.
update()
virtual void ROL::update (const Vector< Real > & u, const Vector< Real > & z, bool flag = true, int iter = -1) override virtual
Definition at line 140 of file ROL_Objective_TimeSimOpt.hpp.
References update().
Referenced by ROL::Constraint< Real >::applyAdjointHessian(), ROL::Constraint< Real >::applyAdjointJacobian(), ROL::Constraint< Real >::applyJacobian(), ROL::DynamicObjectiveCheck< Real >::check(), ROL::Constraint< Real >::checkAdjointConsistencyJacobian(), ROL::Constraint< Real >::checkApplyAdjointHessian(), ROL::Constraint< RealT >::checkApplyAdjointHessian(), ROL::Constraint< Real >::checkApplyAdjointJacobian(), ROL::Objective< Real >::checkGradient(), ROL::Objective< Real >::checkHessSym(), ROL::Objective< Real >::checkHessVec(), ROL::StdObjective< Real >::gradient(), ROL::Objective< Real >::gradient(), ROL::Objective< Real >::hessVec(), update(), ROL::StdConstraint< Real >::update(), ROL::StdObjective< Real >::update(), ROL::StdConstraint< Real >::update(), and ROL::StdObjective< Real >::update().
value() [3/3]
virtual Real ROL::value (const Vector< Real > & u, const Vector< Real > & z, Real & tol) override virtual
Definition at line 145 of file ROL_Objective_TimeSimOpt.hpp.
References value().
solve()
virtual void ROL::solve (Vector< Real > & c, Vector< Real > & u, const Vector< Real > & z) override virtual
Definition at line 150 of file ROL_Objective_TimeSimOpt.hpp.
References solve().
Referenced by ROL::Solver< Real >::solve(), and solve().
gradient_1() [2/2]
virtual void ROL::gradient_1 (Vector< Real > & g, const Vector< Real > & u, const Vector< Real > & z, Real & tol) override virtual
Definition at line 154 of file ROL_Objective_TimeSimOpt.hpp.
References gradient_1_new(), gradient_1_old(), ROL::Vector< Real >::plus(), and workspace_.
gradient_2() [3/3]
virtual void ROL::gradient_2 (Vector< Real > & g, const Vector< Real > & u, const Vector< Real > & z, Real & tol) override virtual
Definition at line 169 of file ROL_Objective_TimeSimOpt.hpp.
References gradient_2().
hessVec_11() [2/2]
virtual void ROL::hessVec_11 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) override virtual
Definition at line 177 of file ROL_Objective_TimeSimOpt.hpp.
References hessVec_11().
hessVec_12() [2/2]
virtual void ROL::hessVec_12 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) override virtual
Definition at line 193 of file ROL_Objective_TimeSimOpt.hpp.
References ROL::Vector< Real >::zero().
hessVec_21() [2/2]
virtual void ROL::hessVec_21 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) override virtual
Definition at line 197 of file ROL_Objective_TimeSimOpt.hpp.
References ROL::Vector< Real >::zero().
hessVec_22() [2/2]
virtual void ROL::hessVec_22 (Vector< Real > & hv, const Vector< Real > & v, const Vector< Real > & u, const Vector< Real > & z, Real & tol) override virtual
Definition at line 201 of file ROL_Objective_TimeSimOpt.hpp.
References ROL::Vector< Real >::zero().
make_OptimizationProblem()
template<template< typename > class V, template< typename > class Obj, typename Real , typename P = Ptr<OptimizationProblem<Real>>, typename... Args> std::enable_if< std::is_base_of< Objective< Real >, Obj< Real > >::value &&std::is_base_of< Vector< Real >, V< Real > >::value, P >::type ROL::make_OptimizationProblem (const Ptr< Obj< Real > > & obj, const Ptr< V< Real > > & x, Args &&... args) inline
Definition at line 1180 of file ROL_OptimizationProblem.hpp.
make_OptimizationSolver() [1/4]
template<typename Real > Ptr< OptimizationSolver< Real > > ROL::make_OptimizationSolver (OptimizationProblem< Real > & opt, ParameterList & parlist) inline
Definition at line 299 of file ROL_OptimizationSolver.hpp.
make_OptimizationSolver() [2/4]
template<typename Real > Ptr< OptimizationSolver< Real > > ROL::make_OptimizationSolver (const Ptr< OptimizationProblem< Real > > & opt, ParameterList & parlist) inline
Definition at line 306 of file ROL_OptimizationSolver.hpp.
make_OptimizationSolver() [3/4]
template<typename Real > Ptr< OptimizationSolver< Real > > ROL::make_OptimizationSolver (OptimizationProblem< Real > & opt, const Ptr< ParameterList > & parlist) inline
Definition at line 313 of file ROL_OptimizationSolver.hpp.
make_OptimizationSolver() [4/4]
template<typename Real > Ptr< OptimizationSolver< Real > > ROL::make_OptimizationSolver (const Ptr< OptimizationProblem< Real > > & opt, const Ptr< ParameterList > & parlist) inline
Definition at line 320 of file ROL_OptimizationSolver.hpp.
DescentDirectionUFactory()
template<typename Real > Ptr< DescentDirection_U< Real > > ROL::DescentDirectionUFactory (ParameterList & parlist, const Ptr< Secant< Real > > & secant = nullPtr) inline
Definition at line 22 of file ROL_DescentDirection_U_Factory.hpp.
References DESCENT_U_NEWTON, DESCENT_U_NEWTONKRYLOV, DESCENT_U_NONLINEARCG, DESCENT_U_SECANT, DESCENT_U_STEEPEST, and StringToEDescentU().
LineSearchUFactory()
template<typename Real > Ptr< LineSearch_U< Real > > ROL::LineSearchUFactory (ParameterList & parlist) inline
Definition at line 21 of file ROL_LineSearch_U_Factory.hpp.
References LINESEARCH_U_BACKTRACKING, LINESEARCH_U_BISECTION, LINESEARCH_U_BRENTS, LINESEARCH_U_CUBICINTERP, LINESEARCH_U_GOLDENSECTION, LINESEARCH_U_ITERATIONSCALING, LINESEARCH_U_PATHBASEDTARGETLEVEL, and StringToELineSearchU().
EDescentUToString()
std::string ROL::EDescentUToString (EDescentU tr) inline
Definition at line 40 of file ROL_LineSearch_U_Types.hpp.
References DESCENT_U_LAST, DESCENT_U_NEWTON, DESCENT_U_NEWTONKRYLOV, DESCENT_U_NONLINEARCG, DESCENT_U_SECANT, DESCENT_U_STEEPEST, and DESCENT_U_USERDEFINED.
Referenced by StringToEDescentU().
isValidDescentU()
int ROL::isValidDescentU (EDescentU d) inline
Verifies validity of a DescentU enum.
Parameters
tr [in] - enum of the DescentU
Returns
1 if the argument is a valid DescentU; 0 otherwise.
Definition at line 60 of file ROL_LineSearch_U_Types.hpp.
References DESCENT_U_NEWTON, DESCENT_U_NEWTONKRYLOV, DESCENT_U_NONLINEARCG, DESCENT_U_SECANT, DESCENT_U_STEEPEST, and DESCENT_U_USERDEFINED.
operator++() [3/42]
EDescentU & ROL::operator++ (EDescentU & type) inline
Definition at line 70 of file ROL_LineSearch_U_Types.hpp.
operator++() [4/42]
EDescentU ROL::operator++ (EDescentU & type, int) inline
Definition at line 74 of file ROL_LineSearch_U_Types.hpp.
operator--() [3/42]
EDescentU & ROL::operator-- (EDescentU & type) inline
Definition at line 80 of file ROL_LineSearch_U_Types.hpp.
operator--() [4/42]
EDescentU ROL::operator-- (EDescentU & type, int) inline
Definition at line 84 of file ROL_LineSearch_U_Types.hpp.
StringToEDescentU()
EDescentU ROL::StringToEDescentU (std::string s) inline
Definition at line 90 of file ROL_LineSearch_U_Types.hpp.
References DESCENT_U_LAST, DESCENT_U_SECANT, DESCENT_U_STEEPEST, EDescentUToString(), and removeStringFormat().
Referenced by DescentDirectionUFactory(), ROL::LineSearch_U< Real >::LineSearch_U(), ROL::TypeU::LineSearchAlgorithm< Real >::LineSearchAlgorithm(), and ROL::ScalarMinimizationLineSearch_U< Real >::ScalarMinimizationLineSearch_U().
ELineSearchUToString()
std::string ROL::ELineSearchUToString (ELineSearchU ls) inline
Definition at line 122 of file ROL_LineSearch_U_Types.hpp.
References LINESEARCH_U_BACKTRACKING, LINESEARCH_U_BISECTION, LINESEARCH_U_BRENTS, LINESEARCH_U_CUBICINTERP, LINESEARCH_U_GOLDENSECTION, LINESEARCH_U_ITERATIONSCALING, LINESEARCH_U_LAST, LINESEARCH_U_PATHBASEDTARGETLEVEL, and LINESEARCH_U_USERDEFINED.
Referenced by StringToELineSearchU().
isValidLineSearchU()
int ROL::isValidLineSearchU (ELineSearchU ls) inline
Verifies validity of a LineSearchU enum.
Parameters
ls [in] - enum of the linesearch
Returns
1 if the argument is a valid linesearch; 0 otherwise.
Definition at line 144 of file ROL_LineSearch_U_Types.hpp.
References LINESEARCH_U_BACKTRACKING, LINESEARCH_U_BISECTION, LINESEARCH_U_BRENTS, LINESEARCH_U_CUBICINTERP, LINESEARCH_U_GOLDENSECTION, LINESEARCH_U_ITERATIONSCALING, LINESEARCH_U_PATHBASEDTARGETLEVEL, and LINESEARCH_U_USERDEFINED.
operator++() [5/42]
ELineSearchU & ROL::operator++ (ELineSearchU & type) inline
Definition at line 156 of file ROL_LineSearch_U_Types.hpp.
operator++() [6/42]
ELineSearchU ROL::operator++ (ELineSearchU & type, int) inline
Definition at line 160 of file ROL_LineSearch_U_Types.hpp.
operator--() [5/42]
ELineSearchU & ROL::operator-- (ELineSearchU & type) inline
Definition at line 166 of file ROL_LineSearch_U_Types.hpp.
operator--() [6/42]
ELineSearchU ROL::operator-- (ELineSearchU & type, int) inline
Definition at line 170 of file ROL_LineSearch_U_Types.hpp.
StringToELineSearchU()
ELineSearchU ROL::StringToELineSearchU (std::string s) inline
Definition at line 176 of file ROL_LineSearch_U_Types.hpp.
References ELineSearchUToString(), LINESEARCH_U_ITERATIONSCALING, LINESEARCH_U_LAST, and removeStringFormat().
Referenced by ROL::TypeU::LineSearchAlgorithm< Real >::LineSearchAlgorithm(), and LineSearchUFactory().
ECurvatureConditionUToString()
std::string ROL::ECurvatureConditionUToString (ECurvatureConditionU ls) inline
Definition at line 203 of file ROL_LineSearch_U_Types.hpp.
References CURVATURECONDITION_U_APPROXIMATEWOLFE, CURVATURECONDITION_U_GENERALIZEDWOLFE, CURVATURECONDITION_U_GOLDSTEIN, CURVATURECONDITION_U_LAST, CURVATURECONDITION_U_NULL, CURVATURECONDITION_U_STRONGWOLFE, and CURVATURECONDITION_U_WOLFE.
Referenced by StringToECurvatureConditionU(), and ROL::TypeU::LineSearchAlgorithm< Real >::writeName().
isValidCurvatureConditionU()
int ROL::isValidCurvatureConditionU (ECurvatureConditionU ls) inline
Verifies validity of a CurvatureConditionU enum.
Parameters
ls [in] - enum of the Curvature Conditions
Returns
1 if the argument is a valid curvature condition; 0 otherwise.
Definition at line 223 of file ROL_LineSearch_U_Types.hpp.
References CURVATURECONDITION_U_APPROXIMATEWOLFE, CURVATURECONDITION_U_GENERALIZEDWOLFE, CURVATURECONDITION_U_GOLDSTEIN, CURVATURECONDITION_U_NULL, CURVATURECONDITION_U_STRONGWOLFE, and CURVATURECONDITION_U_WOLFE.
operator++() [7/42]
ECurvatureConditionU & ROL::operator++ (ECurvatureConditionU & type) inline
Definition at line 233 of file ROL_LineSearch_U_Types.hpp.
operator++() [8/42]
ECurvatureConditionU ROL::operator++ (ECurvatureConditionU & type, int) inline
Definition at line 237 of file ROL_LineSearch_U_Types.hpp.
operator--() [7/42]
ECurvatureConditionU & ROL::operator-- (ECurvatureConditionU & type) inline
Definition at line 243 of file ROL_LineSearch_U_Types.hpp.
operator--() [8/42]
ECurvatureConditionU ROL::operator-- (ECurvatureConditionU & type, int) inline
Definition at line 247 of file ROL_LineSearch_U_Types.hpp.
StringToECurvatureConditionU()
ECurvatureConditionU ROL::StringToECurvatureConditionU (std::string s) inline
Definition at line 253 of file ROL_LineSearch_U_Types.hpp.
References CURVATURECONDITION_U_LAST, CURVATURECONDITION_U_WOLFE, ECurvatureConditionUToString(), and removeStringFormat().
Referenced by ROL::LineSearch_U< Real >::LineSearch_U(), ROL::TypeU::LineSearchAlgorithm< Real >::LineSearchAlgorithm(), and ROL::ScalarMinimizationLineSearch_U< Real >::ScalarMinimizationLineSearch_U().
TrustRegionUFactory()
template<typename Real > Ptr< TrustRegion_U< Real > > ROL::TrustRegionUFactory (ParameterList & list) inline
Definition at line 27 of file ROL_TrustRegion_U_Factory.hpp.
References StringToETrustRegionU(), TRUSTREGION_U_CAUCHYPOINT, TRUSTREGION_U_DOGLEG, TRUSTREGION_U_DOUBLEDOGLEG, TRUSTREGION_U_SPG, and TRUSTREGION_U_TRUNCATEDCG.
ETrustRegionUToString()
std::string ROL::ETrustRegionUToString (ETrustRegionU tr) inline
Definition at line 38 of file ROL_TrustRegion_U_Types.hpp.
References TRUSTREGION_U_CAUCHYPOINT, TRUSTREGION_U_DOGLEG, TRUSTREGION_U_DOUBLEDOGLEG, TRUSTREGION_U_LAST, TRUSTREGION_U_SPG, and TRUSTREGION_U_TRUNCATEDCG.
Referenced by StringToETrustRegionU(), and ROL::TypeU::TrustRegionAlgorithm< Real >::writeName().
isValidTrustRegionU()
int ROL::isValidTrustRegionU (ETrustRegionU ls) inline
Verifies validity of a TrustRegionU enum.
Parameters
tr [in] - enum of the TrustRegionU
Returns
1 if the argument is a valid TrustRegionU; 0 otherwise.
Definition at line 57 of file ROL_TrustRegion_U_Types.hpp.
References TRUSTREGION_U_CAUCHYPOINT, TRUSTREGION_U_DOGLEG, TRUSTREGION_U_DOUBLEDOGLEG, TRUSTREGION_U_SPG, and TRUSTREGION_U_TRUNCATEDCG.
operator++() [9/42]
ETrustRegionU & ROL::operator++ (ETrustRegionU & type) inline
Definition at line 66 of file ROL_TrustRegion_U_Types.hpp.
operator++() [10/42]
ETrustRegionU ROL::operator++ (ETrustRegionU & type, int) inline
Definition at line 70 of file ROL_TrustRegion_U_Types.hpp.
operator--() [9/42]
ETrustRegionU & ROL::operator-- (ETrustRegionU & type) inline
Definition at line 76 of file ROL_TrustRegion_U_Types.hpp.
operator--() [10/42]
ETrustRegionU ROL::operator-- (ETrustRegionU & type, int) inline
Definition at line 80 of file ROL_TrustRegion_U_Types.hpp.
StringToETrustRegionU()
ETrustRegionU ROL::StringToETrustRegionU (std::string s) inline
Definition at line 86 of file ROL_TrustRegion_U_Types.hpp.
References ETrustRegionUToString(), removeStringFormat(), TRUSTREGION_U_CAUCHYPOINT, and TRUSTREGION_U_LAST.
Referenced by ROL::TypeU::TrustRegionAlgorithm< Real >::TrustRegionAlgorithm(), and TrustRegionUFactory().
EKrylovToString()
std::string ROL::EKrylovToString (EKrylov type) inline
Definition at line 44 of file ROL_KrylovFactory.hpp.
References KRYLOV_BICGSTAB, KRYLOV_CG, KRYLOV_CR, KRYLOV_GMRES, KRYLOV_LAST, KRYLOV_MINRES, and KRYLOV_USERDEFINED.
Referenced by StringToEKrylov().
isValidKrylov()
int ROL::isValidKrylov (EKrylov type) inline
Verifies validity of a Krylov enum.
Parameters
type [in] - enum of the Krylov
Returns
1 if the argument is a valid Secant; 0 otherwise.
Definition at line 64 of file ROL_KrylovFactory.hpp.
References KRYLOV_BICGSTAB, KRYLOV_CG, KRYLOV_CR, KRYLOV_GMRES, KRYLOV_MINRES, and KRYLOV_USERDEFINED.
operator++() [11/42]
EKrylov & ROL::operator++ (EKrylov & type) inline
Definition at line 73 of file ROL_KrylovFactory.hpp.
operator++() [12/42]
EKrylov ROL::operator++ (EKrylov & type, int) inline
Definition at line 77 of file ROL_KrylovFactory.hpp.
operator--() [11/42]
EKrylov & ROL::operator-- (EKrylov & type) inline
Definition at line 83 of file ROL_KrylovFactory.hpp.
operator--() [12/42]
EKrylov ROL::operator-- (EKrylov & type, int) inline
Definition at line 87 of file ROL_KrylovFactory.hpp.
StringToEKrylov()
EKrylov ROL::StringToEKrylov (std::string s) inline
Definition at line 93 of file ROL_KrylovFactory.hpp.
References EKrylovToString(), KRYLOV_CG, KRYLOV_LAST, and removeStringFormat().
Referenced by ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::initialize(), KrylovFactory(), ROL::NewtonKrylov_U< Real >::NewtonKrylov_U(), ROL::NewtonKrylov_U< Real >::NewtonKrylov_U(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), and ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep().
KrylovFactory()
template<class Real > Ptr< Krylov< Real > > ROL::KrylovFactory (ParameterList & parlist) inline
Definition at line 104 of file ROL_KrylovFactory.hpp.
References KRYLOV_BICGSTAB, KRYLOV_CG, KRYLOV_CR, KRYLOV_GMRES, KRYLOV_MINRES, and StringToEKrylov().
LineSearchFactory()
template<class Real > ROL::Ptr< LineSearch< Real > > ROL::LineSearchFactory (ROL::ParameterList & parlist) inline
Definition at line 30 of file ROL_LineSearchFactory.hpp.
References LINESEARCH_BACKTRACKING, LINESEARCH_BISECTION, LINESEARCH_BRENTS, LINESEARCH_CUBICINTERP, LINESEARCH_GOLDENSECTION, LINESEARCH_ITERATIONSCALING, LINESEARCH_PATHBASEDTARGETLEVEL, and StringToELineSearch().
getSecant()
template<class Real > ROL::Ptr< Secant< Real > > ROL::getSecant (ESecant esec = SECANT_LBFGS, int L = 10, int BBtype = 1) inline
Definition at line 26 of file ROL_SecantFactory.hpp.
References SECANT_BARZILAIBORWEIN, SECANT_LBFGS, SECANT_LDFP, and SECANT_LSR1.
SecantFactory()
template<class Real > ROL::Ptr< Secant< Real > > ROL::SecantFactory (ROL::ParameterList & parlist, ESecantMode mode = SECANTMODE_BOTH) inline
Definition at line 37 of file ROL_SecantFactory.hpp.
References SECANT_BARZILAIBORWEIN, SECANT_LBFGS, SECANT_LDFP, SECANT_LSR1, and StringToESecant().
TrustRegionFactory()
template<class Real > ROL::Ptr< TrustRegion< Real > > ROL::TrustRegionFactory (ROL::ParameterList & parlist) inline
Definition at line 27 of file ROL_TrustRegionFactory.hpp.
References StringToETrustRegion(), TRUSTREGION_CAUCHYPOINT, TRUSTREGION_DOGLEG, TRUSTREGION_DOUBLEDOGLEG, TRUSTREGION_LINMORE, and TRUSTREGION_TRUNCATEDCG.
ETrustRegionToString()
std::string ROL::ETrustRegionToString (ETrustRegion tr) inline
Definition at line 39 of file ROL_TrustRegionTypes.hpp.
References TRUSTREGION_CAUCHYPOINT, TRUSTREGION_DOGLEG, TRUSTREGION_DOUBLEDOGLEG, TRUSTREGION_LAST, TRUSTREGION_LINMORE, and TRUSTREGION_TRUNCATEDCG.
Referenced by main(), ROL::TrustRegionStep< Real >::printName(), and StringToETrustRegion().
isValidTrustRegion()
int ROL::isValidTrustRegion (ETrustRegion ls) inline
Verifies validity of a TrustRegion enum.
Parameters
tr [in] - enum of the TrustRegion
Returns
1 if the argument is a valid TrustRegion; 0 otherwise.
Definition at line 58 of file ROL_TrustRegionTypes.hpp.
References TRUSTREGION_CAUCHYPOINT, TRUSTREGION_DOGLEG, TRUSTREGION_DOUBLEDOGLEG, TRUSTREGION_LINMORE, and TRUSTREGION_TRUNCATEDCG.
operator++() [13/42]
ETrustRegion & ROL::operator++ (ETrustRegion & type) inline
Definition at line 67 of file ROL_TrustRegionTypes.hpp.
operator++() [14/42]
ETrustRegion ROL::operator++ (ETrustRegion & type, int) inline
Definition at line 71 of file ROL_TrustRegionTypes.hpp.
operator--() [13/42]
ETrustRegion & ROL::operator-- (ETrustRegion & type) inline
Definition at line 77 of file ROL_TrustRegionTypes.hpp.
operator--() [14/42]
ETrustRegion ROL::operator-- (ETrustRegion & type, int) inline
Definition at line 81 of file ROL_TrustRegionTypes.hpp.
StringToETrustRegion()
ETrustRegion ROL::StringToETrustRegion (std::string s) inline
Definition at line 87 of file ROL_TrustRegionTypes.hpp.
References ETrustRegionToString(), removeStringFormat(), TRUSTREGION_CAUCHYPOINT, and TRUSTREGION_LAST.
Referenced by ROL::FletcherStep< Real >::initialize(), ROL::TrustRegionStep< Real >::parseParameterList(), and TrustRegionFactory().
ETrustRegionModelToString()
std::string ROL::ETrustRegionModelToString (ETrustRegionModel tr) inline
Definition at line 110 of file ROL_TrustRegionTypes.hpp.
References TRUSTREGION_MODEL_COLEMANLI, TRUSTREGION_MODEL_KELLEYSACHS, TRUSTREGION_MODEL_LAST, and TRUSTREGION_MODEL_LINMORE.
Referenced by ROL::TrustRegionStep< Real >::printName(), and StringToETrustRegionModel().
isValidTrustRegionModel()
int ROL::isValidTrustRegionModel (ETrustRegionModel ls) inline
Verifies validity of a TrustRegionModel enum.
Parameters
tr [in] - enum of the TrustRegionModel
Returns
1 if the argument is a valid TrustRegionModel; 0 otherwise.
Definition at line 127 of file ROL_TrustRegionTypes.hpp.
References TRUSTREGION_MODEL_COLEMANLI, TRUSTREGION_MODEL_KELLEYSACHS, and TRUSTREGION_MODEL_LINMORE.
operator++() [15/42]
ETrustRegionModel & ROL::operator++ (ETrustRegionModel & type) inline
Definition at line 134 of file ROL_TrustRegionTypes.hpp.
operator++() [16/42]
ETrustRegionModel ROL::operator++ (ETrustRegionModel & type, int) inline
Definition at line 138 of file ROL_TrustRegionTypes.hpp.
operator--() [15/42]
ETrustRegionModel & ROL::operator-- (ETrustRegionModel & type) inline
Definition at line 144 of file ROL_TrustRegionTypes.hpp.
operator--() [16/42]
ETrustRegionModel ROL::operator-- (ETrustRegionModel & type, int) inline
Definition at line 148 of file ROL_TrustRegionTypes.hpp.
StringToETrustRegionModel()
ETrustRegionModel ROL::StringToETrustRegionModel (std::string s) inline
Definition at line 154 of file ROL_TrustRegionTypes.hpp.
References ETrustRegionModelToString(), removeStringFormat(), TRUSTREGION_MODEL_COLEMANLI, and TRUSTREGION_MODEL_LAST.
Referenced by ROL::TrustRegionStep< Real >::parseParameterList(), and ROL::TrustRegion< Real >::TrustRegion().
isValidTrustRegionSubproblem()
bool ROL::isValidTrustRegionSubproblem (ETrustRegion etr, ETrustRegionModel etrm, bool isBnd) inline
Definition at line 164 of file ROL_TrustRegionTypes.hpp.
References TRUSTREGION_CAUCHYPOINT, TRUSTREGION_DOGLEG, TRUSTREGION_DOUBLEDOGLEG, TRUSTREGION_LINMORE, TRUSTREGION_MODEL_LINMORE, and TRUSTREGION_TRUNCATEDCG.
Referenced by ROL::TrustRegionStep< Real >::initialize().
ETrustRegionFlagToString()
std::string ROL::ETrustRegionFlagToString (ETrustRegionFlag trf) inline
Definition at line 209 of file ROL_TrustRegionTypes.hpp.
References TRUSTREGION_FLAG_NAN, TRUSTREGION_FLAG_NPOSPREDNEG, TRUSTREGION_FLAG_NPOSPREDPOS, TRUSTREGION_FLAG_POSPREDNEG, TRUSTREGION_FLAG_QMINSUFDEC, and TRUSTREGION_FLAG_SUCCESS.
Referenced by ROL::TrustRegionStep< Real >::printHeader().
EDistributionToString()
std::string ROL::EDistributionToString (EDistribution ed) inline
Definition at line 56 of file ROL_DistributionFactory.hpp.
References DISTRIBUTION_ARCSINE, DISTRIBUTION_BETA, DISTRIBUTION_CAUCHY, DISTRIBUTION_DIRAC, DISTRIBUTION_EXPONENTIAL, DISTRIBUTION_GAMMA, DISTRIBUTION_GAUSSIAN, DISTRIBUTION_KUMARASWAMY, DISTRIBUTION_LAPLACE, DISTRIBUTION_LAST, DISTRIBUTION_LOGISTIC, DISTRIBUTION_PARABOLIC, DISTRIBUTION_RAISEDCOSINE, DISTRIBUTION_SMALE, DISTRIBUTION_TRIANGLE, DISTRIBUTION_TRUNCATEDEXPONENTIAL, DISTRIBUTION_TRUNCATEDGAUSSIAN, and DISTRIBUTION_UNIFORM.
Referenced by StringToEDistribution().
isValidDistribution()
int ROL::isValidDistribution (EDistribution ed) inline
Definition at line 82 of file ROL_DistributionFactory.hpp.
References DISTRIBUTION_ARCSINE, DISTRIBUTION_BETA, DISTRIBUTION_CAUCHY, DISTRIBUTION_DIRAC, DISTRIBUTION_EXPONENTIAL, DISTRIBUTION_GAMMA, DISTRIBUTION_GAUSSIAN, DISTRIBUTION_KUMARASWAMY, DISTRIBUTION_LAPLACE, DISTRIBUTION_LOGISTIC, DISTRIBUTION_PARABOLIC, DISTRIBUTION_RAISEDCOSINE, DISTRIBUTION_SMALE, DISTRIBUTION_TRIANGLE, DISTRIBUTION_TRUNCATEDEXPONENTIAL, DISTRIBUTION_TRUNCATEDGAUSSIAN, and DISTRIBUTION_UNIFORM.
operator++() [17/42]
EDistribution & ROL::operator++ (EDistribution & type) inline
Definition at line 102 of file ROL_DistributionFactory.hpp.
operator++() [18/42]
EDistribution ROL::operator++ (EDistribution & type, int) inline
Definition at line 106 of file ROL_DistributionFactory.hpp.
operator--() [17/42]
EDistribution & ROL::operator-- (EDistribution & type) inline
Definition at line 112 of file ROL_DistributionFactory.hpp.
operator--() [18/42]
EDistribution ROL::operator-- (EDistribution & type, int) inline
Definition at line 116 of file ROL_DistributionFactory.hpp.
StringToEDistribution()
EDistribution ROL::StringToEDistribution (std::string s) inline
Definition at line 122 of file ROL_DistributionFactory.hpp.
References DISTRIBUTION_ARCSINE, DISTRIBUTION_LAST, DISTRIBUTION_UNIFORM, EDistributionToString(), and removeStringFormat().
Referenced by DistributionFactory().
DistributionFactory()
template<class Real > ROL::Ptr< Distribution< Real > > ROL::DistributionFactory (ROL::ParameterList & parlist) inline
Definition at line 133 of file ROL_DistributionFactory.hpp.
References DISTRIBUTION_ARCSINE, DISTRIBUTION_BETA, DISTRIBUTION_CAUCHY, DISTRIBUTION_DIRAC, DISTRIBUTION_EXPONENTIAL, DISTRIBUTION_GAMMA, DISTRIBUTION_GAUSSIAN, DISTRIBUTION_KUMARASWAMY, DISTRIBUTION_LAPLACE, DISTRIBUTION_LOGISTIC, DISTRIBUTION_PARABOLIC, DISTRIBUTION_RAISEDCOSINE, DISTRIBUTION_SMALE, DISTRIBUTION_TRIANGLE, DISTRIBUTION_TRUNCATEDEXPONENTIAL, DISTRIBUTION_TRUNCATEDGAUSSIAN, DISTRIBUTION_UNIFORM, and StringToEDistribution().
EDeviationMeasureToString()
std::string ROL::EDeviationMeasureToString (EDeviationMeasure ed) inline
Definition at line 42 of file ROL_DeviationMeasureFactory.hpp.
References DEVIATIONMEASURE_GENMOREAUYOSIDACVAR, DEVIATIONMEASURE_LAST, DEVIATIONMEASURE_LOGEXPONENTIALQUADRANGLE, DEVIATIONMEASURE_LOGQUANTILEQUADRANGLE, DEVIATIONMEASURE_MEANVARIANCEQUADRANGLE, DEVIATIONMEASURE_MOREAUYOSIDACVAR, DEVIATIONMEASURE_QUANTILEQUADRANGLE, DEVIATIONMEASURE_SMOOTHEDWORSTCASEQUADRANGLE, and DEVIATIONMEASURE_TRUNCATEDMEANQUADRANGLE.
Referenced by StringToEDeviationMeasure().
isValidDeviationMeasure()
int ROL::isValidDeviationMeasure (EDeviationMeasure ed) inline
Definition at line 69 of file ROL_DeviationMeasureFactory.hpp.
References DEVIATIONMEASURE_GENMOREAUYOSIDACVAR, DEVIATIONMEASURE_LOGEXPONENTIALQUADRANGLE, DEVIATIONMEASURE_LOGQUANTILEQUADRANGLE, DEVIATIONMEASURE_MEANVARIANCEQUADRANGLE, DEVIATIONMEASURE_MOREAUYOSIDACVAR, DEVIATIONMEASURE_QUANTILEQUADRANGLE, DEVIATIONMEASURE_SMOOTHEDWORSTCASEQUADRANGLE, and DEVIATIONMEASURE_TRUNCATEDMEANQUADRANGLE.
operator++() [19/42]
EDeviationMeasure & ROL::operator++ (EDeviationMeasure & type) inline
Definition at line 80 of file ROL_DeviationMeasureFactory.hpp.
operator++() [20/42]
EDeviationMeasure ROL::operator++ (EDeviationMeasure & type, int) inline
Definition at line 84 of file ROL_DeviationMeasureFactory.hpp.
operator--() [19/42]
EDeviationMeasure & ROL::operator-- (EDeviationMeasure & type) inline
Definition at line 90 of file ROL_DeviationMeasureFactory.hpp.
operator--() [20/42]
EDeviationMeasure ROL::operator-- (EDeviationMeasure & type, int) inline
Definition at line 94 of file ROL_DeviationMeasureFactory.hpp.
StringToEDeviationMeasure()
EDeviationMeasure ROL::StringToEDeviationMeasure (std::string s) inline
Definition at line 100 of file ROL_DeviationMeasureFactory.hpp.
References DEVIATIONMEASURE_LAST, DEVIATIONMEASURE_MEANVARIANCEQUADRANGLE, EDeviationMeasureToString(), and removeStringFormat().
Referenced by DeviationMeasureFactory(), and ROL::PH_DeviationObjective< Real >::PH_DeviationObjective().
DeviationMeasureFactory()
template<class Real > Ptr< RandVarFunctional< Real > > ROL::DeviationMeasureFactory (ParameterList & parlist) inline
Definition at line 111 of file ROL_DeviationMeasureFactory.hpp.
References DEVIATIONMEASURE_GENMOREAUYOSIDACVAR, DEVIATIONMEASURE_LOGEXPONENTIALQUADRANGLE, DEVIATIONMEASURE_LOGQUANTILEQUADRANGLE, DEVIATIONMEASURE_MEANVARIANCEQUADRANGLE, DEVIATIONMEASURE_MOREAUYOSIDACVAR, DEVIATIONMEASURE_QUANTILEQUADRANGLE, DEVIATIONMEASURE_SMOOTHEDWORSTCASEQUADRANGLE, DEVIATIONMEASURE_TRUNCATEDMEANQUADRANGLE, and StringToEDeviationMeasure().
DeviationMeasureInfo()
template<class Real > void ROL::DeviationMeasureInfo (ROL::ParameterList & parlist, std::string & name, int & nStatistic, std::vector< Real > & lower, std::vector< Real > & upper, bool & isBoundActivated, const bool printToStream = false, std::ostream & outStream = std::cout) inline
Definition at line 19 of file ROL_DeviationMeasureInfo.hpp.
EErrorMeasureToString()
std::string ROL::EErrorMeasureToString (EErrorMeasure ed) inline
Definition at line 42 of file ROL_ErrorMeasureFactory.hpp.
References ERRORMEASURE_GENMOREAUYOSIDACVAR, ERRORMEASURE_LAST, ERRORMEASURE_LOGEXPONENTIALQUADRANGLE, ERRORMEASURE_LOGQUANTILEQUADRANGLE, ERRORMEASURE_MEANVARIANCEQUADRANGLE, ERRORMEASURE_MOREAUYOSIDACVAR, ERRORMEASURE_QUANTILEQUADRANGLE, ERRORMEASURE_SMOOTHEDWORSTCASEQUADRANGLE, and ERRORMEASURE_TRUNCATEDMEANQUADRANGLE.
Referenced by StringToEErrorMeasure().
isValidErrorMeasure()
int ROL::isValidErrorMeasure (EErrorMeasure ed) inline
Definition at line 69 of file ROL_ErrorMeasureFactory.hpp.
References ERRORMEASURE_GENMOREAUYOSIDACVAR, ERRORMEASURE_LOGEXPONENTIALQUADRANGLE, ERRORMEASURE_LOGQUANTILEQUADRANGLE, ERRORMEASURE_MEANVARIANCEQUADRANGLE, ERRORMEASURE_MOREAUYOSIDACVAR, ERRORMEASURE_QUANTILEQUADRANGLE, ERRORMEASURE_SMOOTHEDWORSTCASEQUADRANGLE, and ERRORMEASURE_TRUNCATEDMEANQUADRANGLE.
operator++() [21/42]
EErrorMeasure & ROL::operator++ (EErrorMeasure & type) inline
Definition at line 80 of file ROL_ErrorMeasureFactory.hpp.
operator++() [22/42]
EErrorMeasure ROL::operator++ (EErrorMeasure & type, int) inline
Definition at line 84 of file ROL_ErrorMeasureFactory.hpp.
operator--() [21/42]
EErrorMeasure & ROL::operator-- (EErrorMeasure & type) inline
Definition at line 90 of file ROL_ErrorMeasureFactory.hpp.
operator--() [22/42]
EErrorMeasure ROL::operator-- (EErrorMeasure & type, int) inline
Definition at line 94 of file ROL_ErrorMeasureFactory.hpp.
StringToEErrorMeasure()
EErrorMeasure ROL::StringToEErrorMeasure (std::string s) inline
Definition at line 100 of file ROL_ErrorMeasureFactory.hpp.
References EErrorMeasureToString(), ERRORMEASURE_LAST, ERRORMEASURE_MEANVARIANCEQUADRANGLE, and removeStringFormat().
Referenced by ErrorMeasureFactory(), and ROL::PH_ErrorObjective< Real >::PH_ErrorObjective().
ErrorMeasureFactory()
template<class Real > Ptr< RandVarFunctional< Real > > ROL::ErrorMeasureFactory (ParameterList & parlist) inline
Definition at line 111 of file ROL_ErrorMeasureFactory.hpp.
References ERRORMEASURE_GENMOREAUYOSIDACVAR, ERRORMEASURE_LOGEXPONENTIALQUADRANGLE, ERRORMEASURE_LOGQUANTILEQUADRANGLE, ERRORMEASURE_MEANVARIANCEQUADRANGLE, ERRORMEASURE_MOREAUYOSIDACVAR, ERRORMEASURE_QUANTILEQUADRANGLE, ERRORMEASURE_SMOOTHEDWORSTCASEQUADRANGLE, ERRORMEASURE_TRUNCATEDMEANQUADRANGLE, and StringToEErrorMeasure().
ErrorMeasureInfo()
template<class Real > void ROL::ErrorMeasureInfo (ROL::ParameterList & parlist, std::string & name, int & nStatistic, std::vector< Real > & lower, std::vector< Real > & upper, bool & isBoundActivated, const bool printToStream = false, std::ostream & outStream = std::cout) inline
Definition at line 19 of file ROL_ErrorMeasureInfo.hpp.
EProbabilityToString()
std::string ROL::EProbabilityToString (EProbability ed) inline
Definition at line 27 of file ROL_ProbabilityFactory.hpp.
References PROBABILITY_BPOE, PROBABILITY_LAST, and PROBABILITY_SMOOTHEDPOE.
Referenced by StringToEProbability().
isValidProbability()
int ROL::isValidProbability (EProbability ed) inline
Definition at line 42 of file ROL_ProbabilityFactory.hpp.
References PROBABILITY_BPOE, and PROBABILITY_SMOOTHEDPOE.
operator++() [23/42]
EProbability & ROL::operator++ (EProbability & type) inline
Definition at line 47 of file ROL_ProbabilityFactory.hpp.
operator++() [24/42]
EProbability ROL::operator++ (EProbability & type, int) inline
Definition at line 51 of file ROL_ProbabilityFactory.hpp.
operator--() [23/42]
EProbability & ROL::operator-- (EProbability & type) inline
Definition at line 57 of file ROL_ProbabilityFactory.hpp.
operator--() [24/42]
EProbability ROL::operator-- (EProbability & type, int) inline
Definition at line 61 of file ROL_ProbabilityFactory.hpp.
StringToEProbability()
EProbability ROL::StringToEProbability (std::string s) inline
Definition at line 67 of file ROL_ProbabilityFactory.hpp.
References EProbabilityToString(), PROBABILITY_BPOE, PROBABILITY_LAST, and removeStringFormat().
Referenced by ProbabilityFactory().
ProbabilityFactory()
template<class Real > Ptr< RandVarFunctional< Real > > ROL::ProbabilityFactory (ParameterList & parlist) inline
Definition at line 78 of file ROL_ProbabilityFactory.hpp.
References PROBABILITY_BPOE, PROBABILITY_SMOOTHEDPOE, and StringToEProbability().
ProbabilityInfo()
template<class Real > void ROL::ProbabilityInfo (ROL::ParameterList & parlist, std::string & name, int & nStatistic, std::vector< Real > & lower, std::vector< Real > & upper, bool & isBoundActivated, const bool printToStream = false, std::ostream & outStream = std::cout) inline
Definition at line 19 of file ROL_ProbabilityInfo.hpp.
References zero.
ERegretMeasureToString()
std::string ROL::ERegretMeasureToString (ERegretMeasure ed) inline
Definition at line 39 of file ROL_RegretMeasureFactory.hpp.
References REGRETMEASURE_EXPONENTIAL, REGRETMEASURE_GENMOREAUYOSIDAMEANABSOLUTELOSS, REGRETMEASURE_LAST, REGRETMEASURE_LOGQUANTILE, REGRETMEASURE_MEANABSOLUTELOSS, REGRETMEASURE_MEANL2, REGRETMEASURE_MOREAUYOSIDAMEANABSOLUTELOSS, REGRETMEASURE_SMOOTHEDWORSTCASE, and REGRETMEASURE_TRUNCATEDMEAN.
Referenced by StringToERegretMeasure().
isValidRegretMeasure()
int ROL::isValidRegretMeasure (ERegretMeasure ed) inline
Definition at line 66 of file ROL_RegretMeasureFactory.hpp.
References REGRETMEASURE_EXPONENTIAL, REGRETMEASURE_GENMOREAUYOSIDAMEANABSOLUTELOSS, REGRETMEASURE_LOGQUANTILE, REGRETMEASURE_MEANABSOLUTELOSS, REGRETMEASURE_MEANL2, REGRETMEASURE_MOREAUYOSIDAMEANABSOLUTELOSS, REGRETMEASURE_SMOOTHEDWORSTCASE, and REGRETMEASURE_TRUNCATEDMEAN.
operator++() [25/42]
ERegretMeasure & ROL::operator++ (ERegretMeasure & type) inline
Definition at line 77 of file ROL_RegretMeasureFactory.hpp.
operator++() [26/42]
ERegretMeasure ROL::operator++ (ERegretMeasure & type, int) inline
Definition at line 81 of file ROL_RegretMeasureFactory.hpp.
operator--() [25/42]
ERegretMeasure & ROL::operator-- (ERegretMeasure & type) inline
Definition at line 87 of file ROL_RegretMeasureFactory.hpp.
operator--() [26/42]
ERegretMeasure ROL::operator-- (ERegretMeasure & type, int) inline
Definition at line 91 of file ROL_RegretMeasureFactory.hpp.
StringToERegretMeasure()
ERegretMeasure ROL::StringToERegretMeasure (std::string s) inline
Definition at line 97 of file ROL_RegretMeasureFactory.hpp.
References ERegretMeasureToString(), REGRETMEASURE_LAST, REGRETMEASURE_MEANABSOLUTELOSS, and removeStringFormat().
Referenced by ROL::PH_RegretObjective< Real >::PH_RegretObjective(), and RegretMeasureFactory().
RegretMeasureFactory()
template<class Real > Ptr< RandVarFunctional< Real > > ROL::RegretMeasureFactory (ParameterList & parlist) inline
Definition at line 108 of file ROL_RegretMeasureFactory.hpp.
References REGRETMEASURE_EXPONENTIAL, REGRETMEASURE_GENMOREAUYOSIDAMEANABSOLUTELOSS, REGRETMEASURE_LOGQUANTILE, REGRETMEASURE_MEANABSOLUTELOSS, REGRETMEASURE_MEANL2, REGRETMEASURE_MOREAUYOSIDAMEANABSOLUTELOSS, REGRETMEASURE_SMOOTHEDWORSTCASE, REGRETMEASURE_TRUNCATEDMEAN, and StringToERegretMeasure().
RegretMeasureInfo()
template<class Real > void ROL::RegretMeasureInfo (ROL::ParameterList & parlist, std::string & name, int & nStatistic, std::vector< Real > & lower, std::vector< Real > & upper, bool & isBoundActivated, const bool printToStream = false, std::ostream & outStream = std::cout) inline
Definition at line 19 of file ROL_RegretMeasureInfo.hpp.
ERiskMeasureToString()
std::string ROL::ERiskMeasureToString (ERiskMeasure ed) inline
Definition at line 78 of file ROL_RiskMeasureFactory.hpp.
References RISKMEASURE_CHEBYSHEVSPECTRAL, RISKMEASURE_CHI2DIVERGENCE, RISKMEASURE_COHERENTENTROPICRISK, RISKMEASURE_CVAR, RISKMEASURE_ENTROPICRISK, RISKMEASURE_GENMOREAUYOSIDACVAR, RISKMEASURE_HMCR, RISKMEASURE_KLDIVERGENCE, RISKMEASURE_LAST, RISKMEASURE_LOGEXPONENTIAL, RISKMEASURE_LOGQUANTILE, RISKMEASURE_MEANDEVIATION, RISKMEASURE_MEANDEVIATIONFROMTARGET, RISKMEASURE_MEANSEMIDEVIATION, RISKMEASURE_MEANSEMIDEVIATIONFROMTARGET, RISKMEASURE_MEANVARIANCE, RISKMEASURE_MEANVARIANCEFROMTARGET, RISKMEASURE_MIXEDCVAR, RISKMEASURE_MOREAUYOSIDACVAR, RISKMEASURE_QUANTILERADIUS, RISKMEASURE_SAFETYMARGIN, RISKMEASURE_SECONDORDERCVAR, RISKMEASURE_SMOOTHEDWORSTCASE, RISKMEASURE_SPECTRALRISK, and RISKMEASURE_TRUNCATEDMEAN.
Referenced by StringToERiskMeasure().
isValidRiskMeasure()
int ROL::isValidRiskMeasure (ERiskMeasure ed) inline
Definition at line 137 of file ROL_RiskMeasureFactory.hpp.
References RISKMEASURE_CHEBYSHEVSPECTRAL, RISKMEASURE_CHI2DIVERGENCE, RISKMEASURE_COHERENTENTROPICRISK, RISKMEASURE_CVAR, RISKMEASURE_ENTROPICRISK, RISKMEASURE_GENMOREAUYOSIDACVAR, RISKMEASURE_HMCR, RISKMEASURE_KLDIVERGENCE, RISKMEASURE_LOGEXPONENTIAL, RISKMEASURE_LOGQUANTILE, RISKMEASURE_MEANDEVIATION, RISKMEASURE_MEANDEVIATIONFROMTARGET, RISKMEASURE_MEANSEMIDEVIATION, RISKMEASURE_MEANSEMIDEVIATIONFROMTARGET, RISKMEASURE_MEANVARIANCE, RISKMEASURE_MEANVARIANCEFROMTARGET, RISKMEASURE_MIXEDCVAR, RISKMEASURE_MOREAUYOSIDACVAR, RISKMEASURE_QUANTILERADIUS, RISKMEASURE_SAFETYMARGIN, RISKMEASURE_SECONDORDERCVAR, RISKMEASURE_SMOOTHEDWORSTCASE, RISKMEASURE_SPECTRALRISK, and RISKMEASURE_TRUNCATEDMEAN.
operator++() [27/42]
ERiskMeasure & ROL::operator++ (ERiskMeasure & type) inline
Definition at line 164 of file ROL_RiskMeasureFactory.hpp.
operator++() [28/42]
ERiskMeasure ROL::operator++ (ERiskMeasure & type, int) inline
Definition at line 168 of file ROL_RiskMeasureFactory.hpp.
operator--() [27/42]
ERiskMeasure & ROL::operator-- (ERiskMeasure & type) inline
Definition at line 174 of file ROL_RiskMeasureFactory.hpp.
operator--() [28/42]
ERiskMeasure ROL::operator-- (ERiskMeasure & type, int) inline
Definition at line 178 of file ROL_RiskMeasureFactory.hpp.
StringToERiskMeasure()
ERiskMeasure ROL::StringToERiskMeasure (std::string s) inline
Definition at line 184 of file ROL_RiskMeasureFactory.hpp.
References ERiskMeasureToString(), removeStringFormat(), RISKMEASURE_CVAR, and RISKMEASURE_LAST.
Referenced by ROL::PH_RiskObjective< Real >::PH_RiskObjective(), and RiskMeasureFactory().
RiskMeasureFactory()
template<class Real > Ptr< RandVarFunctional< Real > > ROL::RiskMeasureFactory (ParameterList & parlist) inline
Definition at line 195 of file ROL_RiskMeasureFactory.hpp.
References RISKMEASURE_CHEBYSHEVSPECTRAL, RISKMEASURE_CHI2DIVERGENCE, RISKMEASURE_COHERENTENTROPICRISK, RISKMEASURE_CVAR, RISKMEASURE_ENTROPICRISK, RISKMEASURE_GENMOREAUYOSIDACVAR, RISKMEASURE_HMCR, RISKMEASURE_KLDIVERGENCE, RISKMEASURE_LOGEXPONENTIAL, RISKMEASURE_LOGQUANTILE, RISKMEASURE_MEANDEVIATION, RISKMEASURE_MEANDEVIATIONFROMTARGET, RISKMEASURE_MEANSEMIDEVIATION, RISKMEASURE_MEANSEMIDEVIATIONFROMTARGET, RISKMEASURE_MEANVARIANCE, RISKMEASURE_MEANVARIANCEFROMTARGET, RISKMEASURE_MIXEDCVAR, RISKMEASURE_MOREAUYOSIDACVAR, RISKMEASURE_QUANTILERADIUS, RISKMEASURE_SAFETYMARGIN, RISKMEASURE_SECONDORDERCVAR, RISKMEASURE_SMOOTHEDWORSTCASE, RISKMEASURE_SPECTRALRISK, RISKMEASURE_TRUNCATEDMEAN, and StringToERiskMeasure().
RiskMeasureInfo()
template<class Real > void ROL::RiskMeasureInfo (ROL::ParameterList & parlist, std::string & name, int & nStatistic, std::vector< Real > & lower, std::vector< Real > & upper, bool & isBoundActivated, const bool printToStream = false, std::ostream & outStream = std::cout) inline
Definition at line 19 of file ROL_RiskMeasureInfo.hpp.
References zero.
Referenced by ROL::ConvexCombinationRiskMeasure< Real >::ConvexCombinationRiskMeasure().
RandVarFunctionalFactory()
template<class Real > Ptr< RandVarFunctional< Real > > ROL::RandVarFunctionalFactory (ROL::ParameterList & parlist) inline
Definition at line 22 of file ROL_RandVarFunctionalFactory.hpp.
RandVarFunctionalInfo()
template<class Real > void ROL::RandVarFunctionalInfo (ROL::ParameterList & parlist, std::string & name, int & nStatistic, std::vector< Real > & lower, std::vector< Real > & upper, bool & isBoundActivated, const bool printToStream = false, std::ostream & outStream = std::cout) inline
Definition at line 22 of file ROL_RandVarFunctionalInfo.hpp.
CreateSimulatedVector() [1/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< Vector< Real > > & a, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 256 of file ROL_SimulatedVector.hpp.
CreateSimulatedVector() [2/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > & a, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 403 of file ROL_SimulatedVector.hpp.
CreateSimulatedVector() [3/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< Vector< Real > > & a, const ROL::Ptr< Vector< Real > > & b, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 415 of file ROL_SimulatedVector.hpp.
CreateSimulatedVector() [4/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > & a, const ROL::Ptr< const Vector< Real > > & b, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 428 of file ROL_SimulatedVector.hpp.
CreateSimulatedVector() [5/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< Vector< Real > > & a, const ROL::Ptr< Vector< Real > > & b, const ROL::Ptr< Vector< Real > > & c, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 442 of file ROL_SimulatedVector.hpp.
CreateSimulatedVector() [6/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > & a, const ROL::Ptr< const Vector< Real > > & b, const ROL::Ptr< const Vector< Real > > & c, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 457 of file ROL_SimulatedVector.hpp.
CreateSimulatedVector() [7/8]
template<class Real > ROL::Ptr< Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< Vector< Real > > & a, const ROL::Ptr< Vector< Real > > & b, const ROL::Ptr< Vector< Real > > & c, const ROL::Ptr< Vector< Real > > & d, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 472 of file ROL_SimulatedVector.hpp.
CreateSimulatedVector() [8/8]
template<class Real > ROL::Ptr< const Vector< Real > > ROL::CreateSimulatedVector (const ROL::Ptr< const Vector< Real > > & a, const ROL::Ptr< const Vector< Real > > & b, const ROL::Ptr< const Vector< Real > > & c, const ROL::Ptr< const Vector< Real > > & d, const ROL::Ptr< BatchManager< Real > > & bman)
Definition at line 488 of file ROL_SimulatedVector.hpp.
computeDenseHessian()
template<class Real > Teuchos::SerialDenseMatrix< int, Real > ROL::computeDenseHessian (Objective< Real > & obj, const Vector< Real > & x)
Definition at line 29 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), dim, ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dual(), and ROL::Objective< Real >::hessVec().
Referenced by main().
computeScaledDenseHessian()
template<class Real > Teuchos::SerialDenseMatrix< int, Real > ROL::computeScaledDenseHessian (Objective< Real > & obj, const Vector< Real > & x)
Definition at line 55 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::clone(), dim, ROL::Vector< Real >::dimension(), ROL::Vector< Real >::dual(), and ROL::Objective< Real >::hessVec().
computeDotMatrix()
template<class Real > Teuchos::SerialDenseMatrix< int, Real > ROL::computeDotMatrix (const Vector< Real > & x)
Definition at line 81 of file ROL_HelperFunctions.hpp.
References ROL::Vector< Real >::basis(), ROL::Vector< Real >::clone(), dim, and ROL::Vector< Real >::dimension().
computeEigenvalues()
template<class Real > std::vector< std::vector< Real > > ROL::computeEigenvalues (const Teuchos::SerialDenseMatrix< int, Real > & mat)
Definition at line 102 of file ROL_HelperFunctions.hpp.
Referenced by main().
computeGenEigenvalues()
template<class Real > std::vector< std::vector< Real > > ROL::computeGenEigenvalues (const Teuchos::SerialDenseMatrix< int, Real > & A, const Teuchos::SerialDenseMatrix< int, Real > & B)
Definition at line 140 of file ROL_HelperFunctions.hpp.
computeInverse()
template<class Real > Teuchos::SerialDenseMatrix< int, Real > ROL::computeInverse (const Teuchos::SerialDenseMatrix< int, Real > & mat)
Definition at line 187 of file ROL_HelperFunctions.hpp.
setParameter()
template<class ParameterType > void ROL::setParameter (ROL::ParameterList & parlist, const std::vector< std::string > & location, const std::vector< std::string >::iterator iter, ParameterType value)
Definition at line 77 of file ROL_ParameterListConverters.hpp.
References setParameter(), and value().
Referenced by setParameter(), and tierParameterList().
tierParameterList()
void ROL::tierParameterList (ROL::ParameterList & outList, const ROL::ParameterList & inList) inline
Produce a heirarchical parameter list using the new names from a flat list of the old names.
Definition at line 96 of file ROL_ParameterListConverters.hpp.
References ROL::StringList::join(), removeStringFormat(), setParameter(), and value().
NumberToString()
template<class T > std::string ROL::NumberToString (T Number)
Definition at line 47 of file ROL_Types.hpp.
Referenced by ROL::TrustRegionStep< Real >::printHeader(), ROL::TypeB::ColemanLiAlgorithm< Real >::writeHeader(), ROL::TypeB::KelleySachsAlgorithm< Real >::writeHeader(), ROL::TypeB::LinMoreAlgorithm< Real >::writeHeader(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::writeHeader(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::writeHeader(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::writeHeader(), ROL::TypeP::TrustRegionAlgorithm< Real >::writeHeader(), and ROL::TypeU::TrustRegionAlgorithm< Real >::writeHeader().
ROL_EPSILON()
template<class Real > Real ROL::ROL_EPSILON (void) inline
Platform-dependent machine epsilon.
Definition at line 57 of file ROL_Types.hpp.
ROL_THRESHOLD()
template<class Real > Real ROL::ROL_THRESHOLD (void) inline
Tolerance for various equality tests.
Definition at line 63 of file ROL_Types.hpp.
ROL_OVERFLOW()
template<class Real > Real ROL::ROL_OVERFLOW (void) inline
Platform-dependent maximum double.
Definition at line 68 of file ROL_Types.hpp.
ROL_INF()
template<class Real > Real ROL::ROL_INF (void) inline
Definition at line 71 of file ROL_Types.hpp.
ROL_NINF()
template<class Real > Real ROL::ROL_NINF (void) inline
Definition at line 74 of file ROL_Types.hpp.
ROL_UNDERFLOW()
template<class Real > Real ROL::ROL_UNDERFLOW (void) inline
Platform-dependent minimum double.
Definition at line 79 of file ROL_Types.hpp.
EExitStatusToString()
std::string ROL::EExitStatusToString (EExitStatus tr) inline
Definition at line 92 of file ROL_Types.hpp.
References EXITSTATUS_CONVERGED, EXITSTATUS_LAST, EXITSTATUS_MAXITER, EXITSTATUS_NAN, EXITSTATUS_STEPTOL, and EXITSTATUS_USERDEFINED.
Referenced by ROL::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::Algorithm< Real >::run(), ROL::TypeB::Algorithm< Real >::writeExitStatus(), ROL::TypeE::Algorithm< Real >::writeExitStatus(), ROL::TypeG::Algorithm< Real >::writeExitStatus(), ROL::TypeP::Algorithm< Real >::writeExitStatus(), and ROL::TypeU::Algorithm< Real >::writeExitStatus().
removeStringFormat()
std::string ROL::removeStringFormat (std::string s) inline
Definition at line 215 of file ROL_Types.hpp.
Referenced by ROL::TypeB::StringToEAlgorithmB(), ROL::TypeE::StringToEAlgorithmE(), ROL::TypeG::StringToEAlgorithmG(), ROL::TypeP::StringToEAlgorithmP(), ROL::TypeU::StringToEAlgorithmU(), ROL::ObjectiveFromBoundConstraint< Real >::StringToEBarrierType(), StringToECurvatureCondition(), StringToECurvatureConditionU(), StringToEDescent(), StringToEDescentU(), StringToEDeviationMeasure(), StringToEDistribution(), StringToEErrorMeasure(), StringToEKrylov(), StringToELineSearch(), StringToELineSearchU(), StringToENonlinearCG(), StringToEPolyProjAlgo(), StringToEProbability(), StringToERegretMeasure(), StringToERiskMeasure(), StringToESecant(), StringToEStep(), StringToETestOptProblem(), StringToETrustRegion(), StringToETrustRegionModel(), ROL::TypeP::StringToETrustRegionP(), StringToETrustRegionU(), and tierParameterList().
EStepToString()
std::string ROL::EStepToString (EStep tr) inline
Definition at line 256 of file ROL_Types.hpp.
References STEP_AUGMENTEDLAGRANGIAN, STEP_BUNDLE, STEP_COMPOSITESTEP, STEP_FLETCHER, STEP_INTERIORPOINT, STEP_LAST, STEP_LINESEARCH, STEP_MOREAUYOSIDAPENALTY, STEP_PRIMALDUALACTIVESET, and STEP_TRUSTREGION.
Referenced by ROL::OptimizationSolver< Real >::OptimizationSolver(), and StringToEStep().
isCompatibleStep()
bool ROL::isCompatibleStep (EProblem p, EStep s) inline
Definition at line 274 of file ROL_Types.hpp.
References STEP_AUGMENTEDLAGRANGIAN, STEP_BUNDLE, STEP_COMPOSITESTEP, STEP_FLETCHER, STEP_INTERIORPOINT, STEP_LINESEARCH, STEP_MOREAUYOSIDAPENALTY, STEP_PRIMALDUALACTIVESET, STEP_TRUSTREGION, TYPE_B, TYPE_E, TYPE_EB, TYPE_LAST, TYPE_P, and TYPE_U.
Referenced by ROL::OptimizationSolver< Real >::OptimizationSolver().
EProblemToString()
std::string ROL::EProblemToString (EProblem p) inline
Definition at line 309 of file ROL_Types.hpp.
References TYPE_B, TYPE_E, TYPE_EB, TYPE_LAST, TYPE_P, and TYPE_U.
isValidStep()
int ROL::isValidStep (EStep ls) inline
Verifies validity of a TrustRegion enum.
Parameters
tr [in] - enum of the TrustRegion
Returns
1 if the argument is a valid TrustRegion; 0 otherwise.
Definition at line 329 of file ROL_Types.hpp.
References STEP_AUGMENTEDLAGRANGIAN, STEP_BUNDLE, STEP_COMPOSITESTEP, STEP_FLETCHER, STEP_INTERIORPOINT, STEP_LINESEARCH, STEP_MOREAUYOSIDAPENALTY, STEP_PRIMALDUALACTIVESET, and STEP_TRUSTREGION.
operator++() [29/42]
EStep & ROL::operator++ (EStep & type) inline
Definition at line 341 of file ROL_Types.hpp.
operator++() [30/42]
EStep ROL::operator++ (EStep & type, int) inline
Definition at line 345 of file ROL_Types.hpp.
operator--() [29/42]
EStep & ROL::operator-- (EStep & type) inline
Definition at line 351 of file ROL_Types.hpp.
operator--() [30/42]
EStep ROL::operator-- (EStep & type, int) inline
Definition at line 355 of file ROL_Types.hpp.
StringToEStep()
EStep ROL::StringToEStep (std::string s) inline
Definition at line 361 of file ROL_Types.hpp.
References EStepToString(), removeStringFormat(), STEP_AUGMENTEDLAGRANGIAN, and STEP_LAST.
Referenced by ROL::StatusTestFactory< Real >::getStatusTest(), ROL::StepFactory< Real >::getStep(), ROL::InteriorPointStep< Real >::InteriorPointStep(), ROL::MoreauYosidaPenaltyStep< Real >::MoreauYosidaPenaltyStep(), and ROL::OptimizationSolver< Real >::OptimizationSolver().
EDescentToString()
std::string ROL::EDescentToString (EDescent tr) inline
Definition at line 390 of file ROL_Types.hpp.
References DESCENT_LAST, DESCENT_NEWTON, DESCENT_NEWTONKRYLOV, DESCENT_NONLINEARCG, DESCENT_SECANT, and DESCENT_STEEPEST.
Referenced by main(), ROL::GradientStep< Real >::printHeader(), ROL::NewtonKrylovStep< Real >::printHeader(), ROL::NewtonStep< Real >::printHeader(), ROL::NonlinearCGStep< Real >::printHeader(), ROL::ProjectedNewtonKrylovStep< Real >::printHeader(), ROL::ProjectedNewtonStep< Real >::printHeader(), ROL::ProjectedSecantStep< Real >::printHeader(), ROL::SecantStep< Real >::printHeader(), ROL::GradientStep< Real >::printName(), ROL::NewtonKrylovStep< Real >::printName(), ROL::NewtonStep< Real >::printName(), ROL::NonlinearCGStep< Real >::printName(), ROL::ProjectedNewtonKrylovStep< Real >::printName(), ROL::ProjectedNewtonStep< Real >::printName(), ROL::ProjectedSecantStep< Real >::printName(), ROL::SecantStep< Real >::printName(), and StringToEDescent().
isValidDescent()
int ROL::isValidDescent (EDescent d) inline
Verifies validity of a Secant enum.
Parameters
tr [in] - enum of the Secant
Returns
1 if the argument is a valid Secant; 0 otherwise.
Definition at line 409 of file ROL_Types.hpp.
References DESCENT_NEWTON, DESCENT_NEWTONKRYLOV, DESCENT_NONLINEARCG, DESCENT_SECANT, and DESCENT_STEEPEST.
operator++() [31/42]
EDescent & ROL::operator++ (EDescent & type) inline
Definition at line 418 of file ROL_Types.hpp.
operator++() [32/42]
EDescent ROL::operator++ (EDescent & type, int) inline
Definition at line 422 of file ROL_Types.hpp.
operator--() [31/42]
EDescent & ROL::operator-- (EDescent & type) inline
Definition at line 428 of file ROL_Types.hpp.
operator--() [32/42]
EDescent ROL::operator-- (EDescent & type, int) inline
Definition at line 432 of file ROL_Types.hpp.
StringToEDescent()
EDescent ROL::StringToEDescent (std::string s) inline
Definition at line 438 of file ROL_Types.hpp.
References DESCENT_LAST, DESCENT_SECANT, DESCENT_STEEPEST, EDescentToString(), and removeStringFormat().
Referenced by ROL::LineSearchStep< Real >::initialize(), ROL::LineSearch< Real >::LineSearch(), and ROL::ScalarMinimizationLineSearch< Real >::ScalarMinimizationLineSearch().
ESecantToString()
std::string ROL::ESecantToString (ESecant tr) inline
Definition at line 465 of file ROL_Types.hpp.
References SECANT_BARZILAIBORWEIN, SECANT_LAST, SECANT_LBFGS, SECANT_LDFP, SECANT_LSR1, and SECANT_USERDEFINED.
Referenced by ROL::NewtonKrylovStep< Real >::printName(), ROL::ProjectedSecantStep< Real >::printName(), ROL::TrustRegionStep< Real >::printName(), StringToESecant(), and ROL::TypeU::TrustRegionAlgorithm< Real >::writeName().
isValidSecant()
int ROL::isValidSecant (ESecant s) inline
Verifies validity of a Secant enum.
Parameters
tr [in] - enum of the Secant
Returns
1 if the argument is a valid Secant; 0 otherwise.
Definition at line 484 of file ROL_Types.hpp.
References SECANT_BARZILAIBORWEIN, SECANT_LBFGS, SECANT_LDFP, SECANT_LSR1, and SECANT_USERDEFINED.
operator++() [33/42]
ESecant & ROL::operator++ (ESecant & type) inline
Definition at line 493 of file ROL_Types.hpp.
operator++() [34/42]
ESecant ROL::operator++ (ESecant & type, int) inline
Definition at line 497 of file ROL_Types.hpp.
operator--() [33/42]
ESecant & ROL::operator-- (ESecant & type) inline
Definition at line 503 of file ROL_Types.hpp.
operator--() [34/42]
ESecant ROL::operator-- (ESecant & type, int) inline
Definition at line 507 of file ROL_Types.hpp.
StringToESecant()
ESecant ROL::StringToESecant (std::string s) inline
Definition at line 513 of file ROL_Types.hpp.
References ESecantToString(), removeStringFormat(), SECANT_LAST, and SECANT_LBFGS.
Referenced by ROL::TypeB::ColemanLiAlgorithm< Real >::ColemanLiAlgorithm(), ROL::TypeB::KelleySachsAlgorithm< Real >::KelleySachsAlgorithm(), ROL::TypeB::LinMoreAlgorithm< Real >::LinMoreAlgorithm(), ROL::TypeB::LSecantBAlgorithm< Real >::LSecantBAlgorithm(), ROL::NewtonKrylov_U< Real >::NewtonKrylov_U(), ROL::NewtonKrylov_U< Real >::NewtonKrylov_U(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::NewtonKrylovAlgorithm(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::NewtonKrylovStep< Real >::NewtonKrylovStep(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::PrimalDualActiveSetAlgorithm(), ROL::PrimalDualActiveSetStep< Real >::PrimalDualActiveSetStep(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), ROL::ProjectedNewtonKrylovStep< Real >::ProjectedNewtonKrylovStep(), ROL::ProjectedSecantStep< Real >::ProjectedSecantStep(), ROL::QuasiNewton_U< Real >::QuasiNewton_U(), ROL::TypeB::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm(), ROL::TypeP::QuasiNewtonAlgorithm< Real >::QuasiNewtonAlgorithm(), SecantFactory(), ROL::SecantStep< Real >::SecantStep(), ROL::TypeP::TrustRegionAlgorithm< Real >::TrustRegionAlgorithm(), ROL::TypeU::TrustRegionAlgorithm< Real >::TrustRegionAlgorithm(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::TrustRegionSPGAlgorithm(), and ROL::TrustRegionStep< Real >::TrustRegionStep().
ENonlinearCGToString()
std::string ROL::ENonlinearCGToString (ENonlinearCG tr) inline
Definition at line 550 of file ROL_Types.hpp.
References NONLINEARCG_DAI_YUAN, NONLINEARCG_DANIEL, NONLINEARCG_FLETCHER_CONJDESC, NONLINEARCG_FLETCHER_REEVES, NONLINEARCG_HAGER_ZHANG, NONLINEARCG_HESTENES_STIEFEL, NONLINEARCG_LAST, NONLINEARCG_LIU_STOREY, NONLINEARCG_OREN_LUENBERGER, NONLINEARCG_POLAK_RIBIERE, and NONLINEARCG_USERDEFINED.
Referenced by StringToENonlinearCG().
isValidNonlinearCG()
int ROL::isValidNonlinearCG (ENonlinearCG s) inline
Verifies validity of a NonlinearCG enum.
Parameters
tr [in] - enum of the NonlinearCG
Returns
1 if the argument is a valid NonlinearCG; 0 otherwise.
Definition at line 574 of file ROL_Types.hpp.
References NONLINEARCG_DAI_YUAN, NONLINEARCG_DANIEL, NONLINEARCG_FLETCHER_CONJDESC, NONLINEARCG_FLETCHER_REEVES, NONLINEARCG_HAGER_ZHANG, NONLINEARCG_HESTENES_STIEFEL, NONLINEARCG_LIU_STOREY, NONLINEARCG_OREN_LUENBERGER, NONLINEARCG_POLAK_RIBIERE, and NONLINEARCG_USERDEFINED.
operator++() [35/42]
ENonlinearCG & ROL::operator++ (ENonlinearCG & type) inline
Definition at line 588 of file ROL_Types.hpp.
operator++() [36/42]
ENonlinearCG ROL::operator++ (ENonlinearCG & type, int) inline
Definition at line 592 of file ROL_Types.hpp.
operator--() [35/42]
ENonlinearCG & ROL::operator-- (ENonlinearCG & type) inline
Definition at line 598 of file ROL_Types.hpp.
operator--() [36/42]
ENonlinearCG ROL::operator-- (ENonlinearCG & type, int) inline
Definition at line 602 of file ROL_Types.hpp.
StringToENonlinearCG()
ENonlinearCG ROL::StringToENonlinearCG (std::string s) inline
Definition at line 608 of file ROL_Types.hpp.
References ENonlinearCGToString(), NONLINEARCG_HESTENES_STIEFEL, NONLINEARCG_LAST, and removeStringFormat().
Referenced by ROL::NonlinearCG_U< Real >::NonlinearCG_U(), and ROL::NonlinearCGStep< Real >::NonlinearCGStep().
ELineSearchToString()
std::string ROL::ELineSearchToString (ELineSearch ls) inline
Definition at line 640 of file ROL_Types.hpp.
References LINESEARCH_BACKTRACKING, LINESEARCH_BISECTION, LINESEARCH_BRENTS, LINESEARCH_CUBICINTERP, LINESEARCH_GOLDENSECTION, LINESEARCH_ITERATIONSCALING, LINESEARCH_LAST, LINESEARCH_PATHBASEDTARGETLEVEL, and LINESEARCH_USERDEFINED.
Referenced by main(), and StringToELineSearch().
isValidLineSearch()
int ROL::isValidLineSearch (ELineSearch ls) inline
Verifies validity of a LineSearch enum.
Parameters
ls [in] - enum of the linesearch
Returns
1 if the argument is a valid linesearch; 0 otherwise.
Definition at line 662 of file ROL_Types.hpp.
References LINESEARCH_BACKTRACKING, LINESEARCH_BISECTION, LINESEARCH_BRENTS, LINESEARCH_CUBICINTERP, LINESEARCH_GOLDENSECTION, LINESEARCH_ITERATIONSCALING, LINESEARCH_PATHBASEDTARGETLEVEL, and LINESEARCH_USERDEFINED.
operator++() [37/42]
ELineSearch & ROL::operator++ (ELineSearch & type) inline
Definition at line 674 of file ROL_Types.hpp.
operator++() [38/42]
ELineSearch ROL::operator++ (ELineSearch & type, int) inline
Definition at line 678 of file ROL_Types.hpp.
operator--() [37/42]
ELineSearch & ROL::operator-- (ELineSearch & type) inline
Definition at line 684 of file ROL_Types.hpp.
operator--() [38/42]
ELineSearch ROL::operator-- (ELineSearch & type, int) inline
Definition at line 688 of file ROL_Types.hpp.
StringToELineSearch()
ELineSearch ROL::StringToELineSearch (std::string s) inline
Definition at line 694 of file ROL_Types.hpp.
References ELineSearchToString(), LINESEARCH_ITERATIONSCALING, LINESEARCH_LAST, and removeStringFormat().
Referenced by LineSearchFactory(), and ROL::LineSearchStep< Real >::LineSearchStep().
ECurvatureConditionToString()
std::string ROL::ECurvatureConditionToString (ECurvatureCondition ls) inline
Definition at line 721 of file ROL_Types.hpp.
References CURVATURECONDITION_APPROXIMATEWOLFE, CURVATURECONDITION_GENERALIZEDWOLFE, CURVATURECONDITION_GOLDSTEIN, CURVATURECONDITION_LAST, CURVATURECONDITION_NULL, CURVATURECONDITION_STRONGWOLFE, and CURVATURECONDITION_WOLFE.
Referenced by ROL::LineSearchStep< Real >::printName(), and StringToECurvatureCondition().
isValidCurvatureCondition()
int ROL::isValidCurvatureCondition (ECurvatureCondition ls) inline
Verifies validity of a CurvatureCondition enum.
Parameters
ls [in] - enum of the Curvature Conditions
Returns
1 if the argument is a valid curvature condition; 0 otherwise.
Definition at line 741 of file ROL_Types.hpp.
References CURVATURECONDITION_APPROXIMATEWOLFE, CURVATURECONDITION_GENERALIZEDWOLFE, CURVATURECONDITION_GOLDSTEIN, CURVATURECONDITION_NULL, CURVATURECONDITION_STRONGWOLFE, and CURVATURECONDITION_WOLFE.
operator++() [39/42]
ECurvatureCondition & ROL::operator++ (ECurvatureCondition & type) inline
Definition at line 751 of file ROL_Types.hpp.
operator++() [40/42]
ECurvatureCondition ROL::operator++ (ECurvatureCondition & type, int) inline
Definition at line 755 of file ROL_Types.hpp.
operator--() [39/42]
ECurvatureCondition & ROL::operator-- (ECurvatureCondition & type) inline
Definition at line 761 of file ROL_Types.hpp.
operator--() [40/42]
ECurvatureCondition ROL::operator-- (ECurvatureCondition & type, int) inline
Definition at line 765 of file ROL_Types.hpp.
StringToECurvatureCondition()
ECurvatureCondition ROL::StringToECurvatureCondition (std::string s) inline
Definition at line 771 of file ROL_Types.hpp.
References CURVATURECONDITION_LAST, CURVATURECONDITION_WOLFE, ECurvatureConditionToString(), and removeStringFormat().
Referenced by ROL::LineSearch< Real >::LineSearch(), ROL::LineSearchStep< Real >::LineSearchStep(), and ROL::ScalarMinimizationLineSearch< Real >::ScalarMinimizationLineSearch().
ECGFlagToString()
std::string ROL::ECGFlagToString (ECGFlag cgf) inline
Definition at line 801 of file ROL_Types.hpp.
References CG_FLAG_ITEREXCEED, CG_FLAG_NEGCURVE, CG_FLAG_SUCCESS, CG_FLAG_TRRADEX, and CG_FLAG_ZERORHS.
Referenced by ROL::TrustRegionStep< Real >::printHeader(), ROL::TypeB::ColemanLiAlgorithm< Real >::writeHeader(), ROL::TypeB::KelleySachsAlgorithm< Real >::writeHeader(), ROL::TypeB::LinMoreAlgorithm< Real >::writeHeader(), ROL::TypeB::NewtonKrylovAlgorithm< Real >::writeHeader(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::writeHeader(), and ROL::TypeU::TrustRegionAlgorithm< Real >::writeHeader().
rol_cast()
template<class Element , class Real > Real ROL::rol_cast (const Element & val)
Definition at line 873 of file ROL_Types.hpp.
References ROL::TypeCaster< Real, Element >::ElementToReal().
getValidROLParameters()
ROL::Ptr< const ROL::ParameterList > ROL::getValidROLParameters () inline
Definition at line 20 of file ROL_ValidParameters.hpp.
References value().
getValidSOLParameters()
ROL::Ptr< const ROL::ParameterList > ROL::getValidSOLParameters () inline
Definition at line 255 of file ROL_ValidParameters.hpp.
ETestOptProblemToString()
std::string ROL::ETestOptProblemToString (ETestOptProblem to) inline
Definition at line 169 of file ROL_GetTestProblems.hpp.
References TESTOPTPROBLEM_BEALE, TESTOPTPROBLEM_BVP, TESTOPTPROBLEM_CANTILEVER, TESTOPTPROBLEM_CANTILEVERBEAM, TESTOPTPROBLEM_CUBIC, TESTOPTPROBLEM_CYLINDERHEAD, TESTOPTPROBLEM_FREUDENSTEINANDROTH, TESTOPTPROBLEM_HS1, TESTOPTPROBLEM_HS14, TESTOPTPROBLEM_HS2, TESTOPTPROBLEM_HS21, TESTOPTPROBLEM_HS24, TESTOPTPROBLEM_HS25, TESTOPTPROBLEM_HS28, TESTOPTPROBLEM_HS29, TESTOPTPROBLEM_HS3, TESTOPTPROBLEM_HS32, TESTOPTPROBLEM_HS38, TESTOPTPROBLEM_HS39, TESTOPTPROBLEM_HS4, TESTOPTPROBLEM_HS41, TESTOPTPROBLEM_HS42, TESTOPTPROBLEM_HS45, TESTOPTPROBLEM_HS48, TESTOPTPROBLEM_HS49, TESTOPTPROBLEM_HS5, TESTOPTPROBLEM_HS50, TESTOPTPROBLEM_HS51, TESTOPTPROBLEM_HS52, TESTOPTPROBLEM_HS53, TESTOPTPROBLEM_HS55, TESTOPTPROBLEM_HS63, TESTOPTPROBLEM_HS9, TESTOPTPROBLEM_LAST, TESTOPTPROBLEM_LEASTSQUARES, TESTOPTPROBLEM_MINIMAX1, TESTOPTPROBLEM_MINIMAX2, TESTOPTPROBLEM_MINIMAX3, TESTOPTPROBLEM_PARABOLOIDCIRCLE, TESTOPTPROBLEM_POISSONCONTROL, TESTOPTPROBLEM_POISSONINVERSION, TESTOPTPROBLEM_POWELL, TESTOPTPROBLEM_QUARTIC, TESTOPTPROBLEM_ROSENBROCK, TESTOPTPROBLEM_SIMPLEEQCONSTRAINED, TESTOPTPROBLEM_SUMOFSQUARES, and TESTOPTPROBLEM_ZAKHAROV.
Referenced by main(), and StringToETestOptProblem().
isValidTestOptProblem()
int ROL::isValidTestOptProblem (ETestOptProblem to) inline
Verifies validity of a TestOptProblem enum.
Parameters
to [in] - enum of the TestOptProblem
Returns
1 if the argument is a valid TestOptProblem; 0 otherwise.
Definition at line 229 of file ROL_GetTestProblems.hpp.
References TESTOPTPROBLEM_BEALE, TESTOPTPROBLEM_BVP, TESTOPTPROBLEM_CANTILEVER, TESTOPTPROBLEM_CANTILEVERBEAM, TESTOPTPROBLEM_CUBIC, TESTOPTPROBLEM_CYLINDERHEAD, TESTOPTPROBLEM_FREUDENSTEINANDROTH, TESTOPTPROBLEM_HS1, TESTOPTPROBLEM_HS14, TESTOPTPROBLEM_HS2, TESTOPTPROBLEM_HS21, TESTOPTPROBLEM_HS24, TESTOPTPROBLEM_HS25, TESTOPTPROBLEM_HS28, TESTOPTPROBLEM_HS29, TESTOPTPROBLEM_HS3, TESTOPTPROBLEM_HS32, TESTOPTPROBLEM_HS38, TESTOPTPROBLEM_HS39, TESTOPTPROBLEM_HS4, TESTOPTPROBLEM_HS41, TESTOPTPROBLEM_HS42, TESTOPTPROBLEM_HS45, TESTOPTPROBLEM_HS48, TESTOPTPROBLEM_HS49, TESTOPTPROBLEM_HS5, TESTOPTPROBLEM_HS50, TESTOPTPROBLEM_HS51, TESTOPTPROBLEM_HS52, TESTOPTPROBLEM_HS53, TESTOPTPROBLEM_HS55, TESTOPTPROBLEM_HS63, TESTOPTPROBLEM_HS9, TESTOPTPROBLEM_LEASTSQUARES, TESTOPTPROBLEM_MINIMAX1, TESTOPTPROBLEM_MINIMAX2, TESTOPTPROBLEM_MINIMAX3, TESTOPTPROBLEM_PARABOLOIDCIRCLE, TESTOPTPROBLEM_POISSONCONTROL, TESTOPTPROBLEM_POISSONINVERSION, TESTOPTPROBLEM_POWELL, TESTOPTPROBLEM_QUARTIC, TESTOPTPROBLEM_ROSENBROCK, TESTOPTPROBLEM_SIMPLEEQCONSTRAINED, TESTOPTPROBLEM_SUMOFSQUARES, and TESTOPTPROBLEM_ZAKHAROV.
operator++() [41/42]
ETestOptProblem & ROL::operator++ (ETestOptProblem & type) inline
Definition at line 278 of file ROL_GetTestProblems.hpp.
operator++() [42/42]
ETestOptProblem ROL::operator++ (ETestOptProblem & type, int) inline
Definition at line 282 of file ROL_GetTestProblems.hpp.
operator--() [41/42]
ETestOptProblem & ROL::operator-- (ETestOptProblem & type) inline
Definition at line 288 of file ROL_GetTestProblems.hpp.
operator--() [42/42]
ETestOptProblem ROL::operator-- (ETestOptProblem & type, int) inline
Definition at line 292 of file ROL_GetTestProblems.hpp.
StringToETestOptProblem()
ETestOptProblem ROL::StringToETestOptProblem (std::string s) inline
Definition at line 298 of file ROL_GetTestProblems.hpp.
References ETestOptProblemToString(), removeStringFormat(), TESTOPTPROBLEM_LAST, and TESTOPTPROBLEM_ROSENBROCK.
GetTestProblem()
template<class Real > void ROL::GetTestProblem (Ptr< OptimizationProblem< Real > > & problem, Ptr< Vector< Real > > & x0, std::vector< Ptr< Vector< Real > > > & x, const ETestOptProblem test)
Definition at line 309 of file ROL_GetTestProblems.hpp.
References TESTOPTPROBLEM_BEALE, TESTOPTPROBLEM_BVP, TESTOPTPROBLEM_CANTILEVER, TESTOPTPROBLEM_CANTILEVERBEAM, TESTOPTPROBLEM_CUBIC, TESTOPTPROBLEM_CYLINDERHEAD, TESTOPTPROBLEM_FREUDENSTEINANDROTH, TESTOPTPROBLEM_HS1, TESTOPTPROBLEM_HS14, TESTOPTPROBLEM_HS2, TESTOPTPROBLEM_HS21, TESTOPTPROBLEM_HS24, TESTOPTPROBLEM_HS25, TESTOPTPROBLEM_HS28, TESTOPTPROBLEM_HS29, TESTOPTPROBLEM_HS3, TESTOPTPROBLEM_HS32, TESTOPTPROBLEM_HS38, TESTOPTPROBLEM_HS39, TESTOPTPROBLEM_HS4, TESTOPTPROBLEM_HS41, TESTOPTPROBLEM_HS42, TESTOPTPROBLEM_HS45, TESTOPTPROBLEM_HS48, TESTOPTPROBLEM_HS49, TESTOPTPROBLEM_HS5, TESTOPTPROBLEM_HS50, TESTOPTPROBLEM_HS51, TESTOPTPROBLEM_HS52, TESTOPTPROBLEM_HS53, TESTOPTPROBLEM_HS55, TESTOPTPROBLEM_HS63, TESTOPTPROBLEM_HS9, TESTOPTPROBLEM_LAST, TESTOPTPROBLEM_LEASTSQUARES, TESTOPTPROBLEM_MINIMAX1, TESTOPTPROBLEM_MINIMAX2, TESTOPTPROBLEM_MINIMAX3, TESTOPTPROBLEM_PARABOLOIDCIRCLE, TESTOPTPROBLEM_POISSONCONTROL, TESTOPTPROBLEM_POISSONINVERSION, TESTOPTPROBLEM_POWELL, TESTOPTPROBLEM_QUARTIC, TESTOPTPROBLEM_ROSENBROCK, TESTOPTPROBLEM_SIMPLEEQCONSTRAINED, TESTOPTPROBLEM_SUMOFSQUARES, and TESTOPTPROBLEM_ZAKHAROV.
addJSONBlockToPL()
void ROL::addJSONBlockToPL (const Json::Value & block, ROL::ParameterList & parlist)
Iterate over a block and insert key-value pairs into the ROL::ParameterList.
Parameters
[in] block is a block from a JSON object
[in/out] parlist is a ROL::ParameterList
Definition at line 83 of file json/example_01.hpp.
References addJSONPairToPL().
Referenced by addJSONPairToPL(), and JSON_Parameters().
addJSONPairToPL()
void ROL::addJSONPairToPL (const Json::Value & block, const std::string & key, ROL::ParameterList & parlist)
Given a JSON block and a key, get the value and insert the key-value pair into a ROL::ParameterList. If the value is itself a block, recursively iterate.
Parameters
[in] block is a block from a JSON object
[in] key is a string key
[in/out] parlist is a ROL::ParameterList
Definition at line 52 of file json/example_01.hpp.
References addJSONBlockToPL().
Referenced by addJSONBlockToPL().
JSON_Parameters()
void ROL::JSON_Parameters (const std::string & jsonFileName, ROL::ParameterList & parlist)
Read a JSON file and store all parameters in a ROL::ParameterList. Checks for a key called "Algorithm" which has a string value which can specify a Step Type (Linesearch or Trust-Region) and either a Descent Type or a Trust-Region Subproblem Solver Type.
Parameters
[in] block is a block from a JSON object
[in/out] parlist is a ROL::ParameterList
Definition at line 102 of file json/example_01.hpp.
References addJSONBlockToPL().
Referenced by main().
stepFactory()
template<class Real > void ROL::stepFactory (ROL::ParameterList & parlist, ROL::Ptr< ROL::Step< Real > > & step)
A minimalist step factory which specializes the Step Type depending on whether a Trust-Region or Linesearch has been selected.
Parameters
[in] parlist is a ROL::ParameterList
[in/out] step is a ref count pointer to a ROL::Step
Definition at line 173 of file json/example_01.hpp.
Referenced by ROL::OptimizationSolver< Real >::OptimizationSolver().