ROL: ROL::TypeP Namespace Reference
ROL::TypeP Namespace Reference
Classes
class Algorithm
Provides an interface to run optimization algorithms to minimize composite optimization problems f+phi.
struct AlgorithmState
class InexactNewtonAlgorithm
Provides an interface to run the inexact proximal Newton algorithm.
class iPianoAlgorithm
Provides an interface to run the proximal gradient algorithm.
class ProxGradientAlgorithm
Provides an interface to run the proximal gradient algorithm.
class QuasiNewtonAlgorithm
Provides an interface to run the projected secant algorithm.
class SpectralGradientAlgorithm
Provides an interface to run the proximal gradient algorithm.
class TrustRegionAlgorithm
Provides an interface to run the trust-region algorithm.
Enumerations
enum EAlgorithmP {
ALGORITHM_P_LINESEARCH = 0 , ALGORITHM_P_TRUSTREGION , ALGORITHM_P_SPECTRALGRADIENT , ALGORITHM_P_IPIANO ,
ALGORITHM_P_LAST
}
enum ETrustRegionP { TRUSTREGION_P_SPG = 0 , TRUSTREGION_P_SPG2 , TRUSTREGION_P_NCG , TRUSTREGION_P_LAST }
Functions
std::string EAlgorithmPToString (EAlgorithmP alg)
int isValidAlgorithmP (EAlgorithmP alg)
Verifies validity of a AlgorithmP enum.
EAlgorithmP & operator++ (EAlgorithmP &type)
EAlgorithmP operator++ (EAlgorithmP &type, int)
EAlgorithmP & operator-- (EAlgorithmP &type)
EAlgorithmP operator-- (EAlgorithmP &type, int)
EAlgorithmP StringToEAlgorithmP (std::string s)
template<typename Real >
Ptr< Algorithm< Real > > AlgorithmFactory (ParameterList &parlist, const Ptr< Secant< Real > > &secant=nullPtr)
std::string ETrustRegionPToString (ETrustRegionP alg)
int isValidTrustRegionP (ETrustRegionP alg)
ETrustRegionP & operator++ (ETrustRegionP &type)
ETrustRegionP operator++ (ETrustRegionP &type, int)
ETrustRegionP & operator-- (ETrustRegionP &type)
ETrustRegionP operator-- (ETrustRegionP &type, int)
ETrustRegionP StringToETrustRegionP (std::string s)
Enumeration Type Documentation
EAlgorithmP
enum ROL::TypeP::EAlgorithmP
Enumerator
ALGORITHM_P_LINESEARCH
ALGORITHM_P_TRUSTREGION
ALGORITHM_P_SPECTRALGRADIENT
ALGORITHM_P_IPIANO
ALGORITHM_P_LAST
Definition at line 32 of file ROL_TypeP_AlgorithmFactory.hpp.
ETrustRegionP
enum ROL::TypeP::ETrustRegionP
Enumerator
TRUSTREGION_P_SPG
TRUSTREGION_P_SPG2
TRUSTREGION_P_NCG
TRUSTREGION_P_LAST
Definition at line 25 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
Function Documentation
EAlgorithmPToString()
std::string ROL::TypeP::EAlgorithmPToString (EAlgorithmP alg) inline
Definition at line 40 of file ROL_TypeP_AlgorithmFactory.hpp.
References ALGORITHM_P_IPIANO, ALGORITHM_P_LAST, ALGORITHM_P_LINESEARCH, ALGORITHM_P_SPECTRALGRADIENT, and ALGORITHM_P_TRUSTREGION.
Referenced by StringToEAlgorithmP().
isValidAlgorithmP()
int ROL::TypeP::isValidAlgorithmP (EAlgorithmP alg) inline
Verifies validity of a AlgorithmP enum.
Parameters
ls [in] - enum of the AlgorithmP
Returns
1 if the argument is a valid AlgorithmP; 0 otherwise.
Definition at line 58 of file ROL_TypeP_AlgorithmFactory.hpp.
References ALGORITHM_P_IPIANO, ALGORITHM_P_LAST, ALGORITHM_P_LINESEARCH, ALGORITHM_P_SPECTRALGRADIENT, and ALGORITHM_P_TRUSTREGION.
operator++() [1/4]
EAlgorithmP & ROL::TypeP::operator++ (EAlgorithmP & type) inline
Definition at line 67 of file ROL_TypeP_AlgorithmFactory.hpp.
operator++() [2/4]
EAlgorithmP ROL::TypeP::operator++ (EAlgorithmP & type, int) inline
Definition at line 71 of file ROL_TypeP_AlgorithmFactory.hpp.
operator--() [1/4]
EAlgorithmP & ROL::TypeP::operator-- (EAlgorithmP & type) inline
Definition at line 77 of file ROL_TypeP_AlgorithmFactory.hpp.
operator--() [2/4]
EAlgorithmP ROL::TypeP::operator-- (EAlgorithmP & type, int) inline
Definition at line 81 of file ROL_TypeP_AlgorithmFactory.hpp.
StringToEAlgorithmP()
EAlgorithmP ROL::TypeP::StringToEAlgorithmP (std::string s) inline
Definition at line 87 of file ROL_TypeP_AlgorithmFactory.hpp.
References ALGORITHM_P_LAST, ALGORITHM_P_LINESEARCH, ALGORITHM_P_TRUSTREGION, EAlgorithmPToString(), and ROL::removeStringFormat().
Referenced by AlgorithmFactory().
AlgorithmFactory()
template<typename Real > Ptr< Algorithm< Real > > ROL::TypeP::AlgorithmFactory (ParameterList & parlist, const Ptr< Secant< Real > > & secant = nullPtr) inline
Definition at line 98 of file ROL_TypeP_AlgorithmFactory.hpp.
References ALGORITHM_P_IPIANO, ALGORITHM_P_LINESEARCH, ALGORITHM_P_SPECTRALGRADIENT, ALGORITHM_P_TRUSTREGION, and StringToEAlgorithmP().
ETrustRegionPToString()
std::string ROL::TypeP::ETrustRegionPToString (ETrustRegionP alg) inline
Definition at line 32 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
References TRUSTREGION_P_LAST, TRUSTREGION_P_NCG, TRUSTREGION_P_SPG, and TRUSTREGION_P_SPG2.
Referenced by StringToETrustRegionP().
isValidTrustRegionP()
int ROL::TypeP::isValidTrustRegionP (ETrustRegionP alg) inline
Definition at line 44 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
References TRUSTREGION_P_LAST, TRUSTREGION_P_NCG, TRUSTREGION_P_SPG, and TRUSTREGION_P_SPG2.
operator++() [3/4]
ETrustRegionP & ROL::TypeP::operator++ (ETrustRegionP & type) inline
Definition at line 52 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
operator++() [4/4]
ETrustRegionP ROL::TypeP::operator++ (ETrustRegionP & type, int) inline
Definition at line 56 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
operator--() [3/4]
ETrustRegionP & ROL::TypeP::operator-- (ETrustRegionP & type) inline
Definition at line 62 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
operator--() [4/4]
ETrustRegionP ROL::TypeP::operator-- (ETrustRegionP & type, int) inline
Definition at line 66 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
StringToETrustRegionP()
ETrustRegionP ROL::TypeP::StringToETrustRegionP (std::string s) inline
Definition at line 72 of file ROL_TypeP_TrustRegionAlgorithm.hpp.
References ETrustRegionPToString(), ROL::removeStringFormat(), TRUSTREGION_P_LAST, and TRUSTREGION_P_SPG.
Referenced by ROL::TypeP::TrustRegionAlgorithm< Real >::TrustRegionAlgorithm().