ROL: ROL::TypeG Namespace Reference
ROL::TypeG Namespace Reference
Classes
class Algorithm
Provides an interface to run general constrained optimization algorithms.
struct AlgorithmState
class AugmentedLagrangianAlgorithm
Provides an interface to run general constrained optimization algorithms using Augmented Lagrangians.
class InteriorPointAlgorithm
Provides an interface to run the interior point algorithm.
class MoreauYosidaAlgorithm
Provides an interface to run the Moreau-Yosida algorithm.
class StabilizedLCLAlgorithm
Provides an interface to run general constrained optimization algorithms using Stabilized LCL.
Enumerations
enum EAlgorithmG {
ALGORITHM_G_AUGMENTEDLAGRANGIAN = 0 , ALGORITHM_G_MOREAUYOSIDA , ALGORITHM_G_INTERIORPOINT , ALGORITHM_G_STABILIZEDLCL ,
ALGORITHM_G_LAST
}
Functions
std::string EAlgorithmGToString (EAlgorithmG alg)
int isValidAlgorithmG (EAlgorithmG alg)
Verifies validity of a AlgorithmG enum.
EAlgorithmG & operator++ (EAlgorithmG &type)
EAlgorithmG operator++ (EAlgorithmG &type, int)
EAlgorithmG & operator-- (EAlgorithmG &type)
EAlgorithmG operator-- (EAlgorithmG &type, int)
EAlgorithmG StringToEAlgorithmG (std::string s)
template<typename Real >
Ptr< TypeG::Algorithm< Real > > AlgorithmFactory (ParameterList &parlist, const Ptr< Secant< Real > > &secant=nullPtr)
Enumeration Type Documentation
EAlgorithmG
enum ROL::TypeG::EAlgorithmG
Enumerator
ALGORITHM_G_AUGMENTEDLAGRANGIAN
ALGORITHM_G_MOREAUYOSIDA
ALGORITHM_G_INTERIORPOINT
ALGORITHM_G_STABILIZEDLCL
ALGORITHM_G_LAST
Definition at line 30 of file ROL_TypeG_AlgorithmFactory.hpp.
Function Documentation
EAlgorithmGToString()
std::string ROL::TypeG::EAlgorithmGToString (EAlgorithmG alg) inline
Definition at line 38 of file ROL_TypeG_AlgorithmFactory.hpp.
References ALGORITHM_G_AUGMENTEDLAGRANGIAN, ALGORITHM_G_INTERIORPOINT, ALGORITHM_G_LAST, ALGORITHM_G_MOREAUYOSIDA, and ALGORITHM_G_STABILIZEDLCL.
Referenced by StringToEAlgorithmG().
isValidAlgorithmG()
int ROL::TypeG::isValidAlgorithmG (EAlgorithmG alg) inline
Verifies validity of a AlgorithmG enum.
Parameters
ls [in] - enum of the AlgorithmG
Returns
1 if the argument is a valid AlgorithmG; 0 otherwise.
Definition at line 56 of file ROL_TypeG_AlgorithmFactory.hpp.
References ALGORITHM_G_AUGMENTEDLAGRANGIAN, ALGORITHM_G_INTERIORPOINT, ALGORITHM_G_LAST, ALGORITHM_G_MOREAUYOSIDA, and ALGORITHM_G_STABILIZEDLCL.
operator++() [1/2]
EAlgorithmG & ROL::TypeG::operator++ (EAlgorithmG & type) inline
Definition at line 65 of file ROL_TypeG_AlgorithmFactory.hpp.
operator++() [2/2]
EAlgorithmG ROL::TypeG::operator++ (EAlgorithmG & type, int) inline
Definition at line 69 of file ROL_TypeG_AlgorithmFactory.hpp.
operator--() [1/2]
EAlgorithmG & ROL::TypeG::operator-- (EAlgorithmG & type) inline
Definition at line 75 of file ROL_TypeG_AlgorithmFactory.hpp.
operator--() [2/2]
EAlgorithmG ROL::TypeG::operator-- (EAlgorithmG & type, int) inline
Definition at line 79 of file ROL_TypeG_AlgorithmFactory.hpp.
StringToEAlgorithmG()
EAlgorithmG ROL::TypeG::StringToEAlgorithmG (std::string s) inline
Definition at line 85 of file ROL_TypeG_AlgorithmFactory.hpp.
References ALGORITHM_G_AUGMENTEDLAGRANGIAN, ALGORITHM_G_LAST, EAlgorithmGToString(), and ROL::removeStringFormat().
Referenced by AlgorithmFactory().
AlgorithmFactory()
template<typename Real > Ptr< TypeG::Algorithm< Real > > ROL::TypeG::AlgorithmFactory (ParameterList & parlist, const Ptr< Secant< Real > > & secant = nullPtr) inline
Definition at line 96 of file ROL_TypeG_AlgorithmFactory.hpp.
References ALGORITHM_G_AUGMENTEDLAGRANGIAN, ALGORITHM_G_INTERIORPOINT, ALGORITHM_G_MOREAUYOSIDA, ALGORITHM_G_STABILIZEDLCL, and StringToEAlgorithmG().