ROL: ROL::TypeU Namespace Reference
ROL::TypeU Namespace Reference
Classes
class Algorithm
Provides an interface to run unconstrained optimization algorithms.
struct AlgorithmState
class BundleAlgorithm
Provides an interface to run trust-bundle methods for unconstrained optimization algorithms.
class LineSearchAlgorithm
Provides an interface to run unconstrained line search algorithms.
class TrustRegionAlgorithm
Provides an interface to run trust-region methods for unconstrained optimization algorithms.
Enumerations
enum EAlgorithmU { ALGORITHM_U_BUNDLE = 0 , ALGORITHM_U_LINESEARCH , ALGORITHM_U_TRUSTREGION , ALGORITHM_U_LAST }
Functions
std::string EAlgorithmUToString (EAlgorithmU alg)
int isValidAlgorithmU (EAlgorithmU alg)
Verifies validity of a AlgorithmU enum.
EAlgorithmU & operator++ (EAlgorithmU &type)
EAlgorithmU operator++ (EAlgorithmU &type, int)
EAlgorithmU & operator-- (EAlgorithmU &type)
EAlgorithmU operator-- (EAlgorithmU &type, int)
EAlgorithmU StringToEAlgorithmU (std::string s)
template<typename Real >
Ptr< Algorithm< Real > > AlgorithmFactory (ParameterList &parlist, const Ptr< Secant< Real > > &secant=nullPtr)
Enumeration Type Documentation
EAlgorithmU
enum ROL::TypeU::EAlgorithmU
Enumerator
ALGORITHM_U_BUNDLE
ALGORITHM_U_LINESEARCH
ALGORITHM_U_TRUSTREGION
ALGORITHM_U_LAST
Definition at line 28 of file ROL_TypeU_AlgorithmFactory.hpp.
Function Documentation
EAlgorithmUToString()
std::string ROL::TypeU::EAlgorithmUToString (EAlgorithmU alg) inline
Definition at line 35 of file ROL_TypeU_AlgorithmFactory.hpp.
References ALGORITHM_U_BUNDLE, ALGORITHM_U_LAST, ALGORITHM_U_LINESEARCH, and ALGORITHM_U_TRUSTREGION.
Referenced by StringToEAlgorithmU().
isValidAlgorithmU()
int ROL::TypeU::isValidAlgorithmU (EAlgorithmU alg) inline
Verifies validity of a AlgorithmU enum.
Parameters
ls [in] - enum of the AlgorithmU
Returns
1 if the argument is a valid AlgorithmU; 0 otherwise.
Definition at line 52 of file ROL_TypeU_AlgorithmFactory.hpp.
References ALGORITHM_U_BUNDLE, ALGORITHM_U_LAST, ALGORITHM_U_LINESEARCH, and ALGORITHM_U_TRUSTREGION.
operator++() [1/2]
EAlgorithmU & ROL::TypeU::operator++ (EAlgorithmU & type) inline
Definition at line 60 of file ROL_TypeU_AlgorithmFactory.hpp.
operator++() [2/2]
EAlgorithmU ROL::TypeU::operator++ (EAlgorithmU & type, int) inline
Definition at line 64 of file ROL_TypeU_AlgorithmFactory.hpp.
operator--() [1/2]
EAlgorithmU & ROL::TypeU::operator-- (EAlgorithmU & type) inline
Definition at line 70 of file ROL_TypeU_AlgorithmFactory.hpp.
operator--() [2/2]
EAlgorithmU ROL::TypeU::operator-- (EAlgorithmU & type, int) inline
Definition at line 74 of file ROL_TypeU_AlgorithmFactory.hpp.
StringToEAlgorithmU()
EAlgorithmU ROL::TypeU::StringToEAlgorithmU (std::string s) inline
Definition at line 80 of file ROL_TypeU_AlgorithmFactory.hpp.
References ALGORITHM_U_BUNDLE, ALGORITHM_U_LAST, ALGORITHM_U_TRUSTREGION, EAlgorithmUToString(), and ROL::removeStringFormat().
Referenced by AlgorithmFactory().
AlgorithmFactory()
template<typename Real > Ptr< Algorithm< Real > > ROL::TypeU::AlgorithmFactory (ParameterList & parlist, const Ptr< Secant< Real > > & secant = nullPtr) inline
Definition at line 91 of file ROL_TypeU_AlgorithmFactory.hpp.
References ALGORITHM_U_BUNDLE, ALGORITHM_U_LINESEARCH, ALGORITHM_U_TRUSTREGION, and StringToEAlgorithmU().