ROL: ROL::details Namespace Reference
ROL::details Namespace Reference
Classes
class basic_nullstream
class DynamicConstraint_CheckInterface
class DynamicObjective_CheckInterface
class MINRES
class VectorClone
class VectorCloneMap
class VectorWorkspace
Typedefs
using nullstream = basic_nullstream< char, std::char_traits< char > >
Functions
Ptr< std::ostream > makeStreamPtr (std::ostream &os, bool noSuppressOutput=true)
Ptr< std::ostream > makeStreamPtr (Ptr< std::ostream > os, bool noSuppressOutput=true)
Typedef Documentation
nullstream
using ROL::details::nullstream = typedef basic_nullstream<char, std::char_traits<char> >
Definition at line 36 of file ROL_Stream.hpp.
Function Documentation
makeStreamPtr() [1/2]
Ptr< std::ostream > ROL::details::makeStreamPtr (std::ostream & os, bool noSuppressOutput = true) inline
Definition at line 39 of file ROL_Stream.hpp.
References makeStreamPtr().
Referenced by makeStreamPtr(), and makeStreamPtr().
makeStreamPtr() [2/2]
Ptr< std::ostream > ROL::details::makeStreamPtr (Ptr< std::ostream > os, bool noSuppressOutput = true) inline
Definition at line 47 of file ROL_Stream.hpp.
References makeStreamPtr().