ROL: ROL::TRUtils Namespace Reference
ROL::TRUtils Namespace Reference
Enumerations
enum ETRFlag {
SUCCESS = 0 , POSPREDNEG , NPOSPREDPOS , NPOSPREDNEG ,
TRNAN , QMINSUFDEC , UNDEFINED
}
Functions
std::string ETRFlagToString (ETRFlag trf)
template<typename Real >
Real initialRadius (int &nfval, const Vector< Real > &x, const Vector< Real > &g, Vector< Real > &Bg, const Real fx, const Real gnorm, const Real gtol, Objective< Real > &obj, TrustRegionModel_U< Real > &model, const Real delMax, std::ostream &outStream, const bool print=false)
template<typename Real >
void analyzeRatio (Real &rho, ETRFlag &flag, const Real fold, const Real ftrial, const Real pRed, const Real epsi, std::ostream &outStream=std::cout, const bool print=false)
template<typename Real >
Real interpolateRadius (const Vector< Real > &g, const Vector< Real > &s, const Real snorm, const Real pRed, const Real fold, const Real ftrial, const Real del, const Real gamma0, const Real gamma1, const Real eta2, std::ostream &outStream=std::cout, const bool print=false)
Enumeration Type Documentation
ETRFlag
enum ROL::TRUtils::ETRFlag
Enumerator
SUCCESS
POSPREDNEG
NPOSPREDPOS
NPOSPREDNEG
TRNAN
QMINSUFDEC
UNDEFINED
Definition at line 28 of file ROL_TrustRegionUtilities.hpp.
Function Documentation
ETRFlagToString()
std::string ROL::TRUtils::ETRFlagToString (ETRFlag trf) inline
Definition at line 38 of file ROL_TrustRegionUtilities.hpp.
References NPOSPREDNEG, NPOSPREDPOS, POSPREDNEG, QMINSUFDEC, SUCCESS, and TRNAN.
Referenced by ROL::TypeB::ColemanLiAlgorithm< Real >::writeHeader(), ROL::TypeB::KelleySachsAlgorithm< Real >::writeHeader(), ROL::TypeB::LinMoreAlgorithm< Real >::writeHeader(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::writeHeader(), ROL::TypeP::TrustRegionAlgorithm< Real >::writeHeader(), and ROL::TypeU::TrustRegionAlgorithm< Real >::writeHeader().
initialRadius()
template<typename Real > Real ROL::TRUtils::initialRadius (int & nfval, const Vector< Real > & x, const Vector< Real > & g, Vector< Real > & Bg, const Real fx, const Real gnorm, const Real gtol, Objective< Real > & obj, TrustRegionModel_U< Real > & model, const Real delMax, std::ostream & outStream, const bool print = false) inline
Definition at line 66 of file ROL_TrustRegionUtilities.hpp.
References ROL::Vector< Real >::clone(), ROL::Vector< Real >::dot(), ROL::Vector< Real >::dual(), ROL::TrustRegionModel_U< Real >::hessVec(), ROL::Revert, ROL::TrustRegionModel_U< Real >::setData(), ROL::Temp, ROL::Objective< Real >::update(), ROL::Objective< Real >::value(), and zero.
analyzeRatio()
template<typename Real > void ROL::TRUtils::analyzeRatio (Real & rho, ETRFlag & flag, const Real fold, const Real ftrial, const Real pRed, const Real epsi, std::ostream & outStream = std::cout, const bool print = false) inline
Definition at line 135 of file ROL_TrustRegionUtilities.hpp.
References NPOSPREDNEG, NPOSPREDPOS, POSPREDNEG, SUCCESS, TRNAN, and zero.
interpolateRadius()
template<typename Real > Real ROL::TRUtils::interpolateRadius (const Vector< Real > & g, const Vector< Real > & s, const Real snorm, const Real pRed, const Real fold, const Real ftrial, const Real del, const Real gamma0, const Real gamma1, const Real eta2, std::ostream & outStream = std::cout, const bool print = false) inline
Definition at line 186 of file ROL_TrustRegionUtilities.hpp.
References ROL::Vector< Real >::apply().