ROL: ROL::TypeE Namespace Reference
ROL::TypeE Namespace Reference
Classes
class Algorithm
struct AlgorithmState
class AugmentedLagrangianAlgorithm
Provides an interface to run equality constrained optimization algorithms using Augmented Lagrangians.
class CompositeStepAlgorithm
Provides an interface to run equality constrained optimization algorithms using the Composite-Step Trust-Region Sequential Quadratic Programming (SQP) method.
class FletcherAlgorithm
Provides an interface to run equality constrained optimization algorithms using Fletcher's exact penalty.
class StabilizedLCLAlgorithm
Provides an interface to run equality constrained optimization algorithms using Stabilized LCL.
Enumerations
enum EAlgorithmE {
ALGORITHM_E_AUGMENTEDLAGRANGIAN = 0 , ALGORITHM_E_FLETCHER , ALGORITHM_E_COMPOSITESTEP , ALGORITHM_E_STABILIZEDLCL ,
ALGORITHM_E_LAST
}
Functions
std::string EAlgorithmEToString (EAlgorithmE alg)
int isValidAlgorithmE (EAlgorithmE alg)
Verifies validity of a AlgorithmE enum.
EAlgorithmE & operator++ (EAlgorithmE &type)
EAlgorithmE operator++ (EAlgorithmE &type, int)
EAlgorithmE & operator-- (EAlgorithmE &type)
EAlgorithmE operator-- (EAlgorithmE &type, int)
EAlgorithmE StringToEAlgorithmE (std::string s)
template<typename Real >
Ptr< TypeE::Algorithm< Real > > AlgorithmFactory (ParameterList &parlist, const Ptr< Secant< Real > > &secant=nullPtr)
Enumeration Type Documentation
EAlgorithmE
enum ROL::TypeE::EAlgorithmE
Enumerator
ALGORITHM_E_AUGMENTEDLAGRANGIAN
ALGORITHM_E_FLETCHER
ALGORITHM_E_COMPOSITESTEP
ALGORITHM_E_STABILIZEDLCL
ALGORITHM_E_LAST
Definition at line 25 of file ROL_TypeE_AlgorithmFactory.hpp.
Function Documentation
EAlgorithmEToString()
std::string ROL::TypeE::EAlgorithmEToString (EAlgorithmE alg) inline
Definition at line 33 of file ROL_TypeE_AlgorithmFactory.hpp.
References ALGORITHM_E_AUGMENTEDLAGRANGIAN, ALGORITHM_E_COMPOSITESTEP, ALGORITHM_E_FLETCHER, ALGORITHM_E_LAST, and ALGORITHM_E_STABILIZEDLCL.
Referenced by StringToEAlgorithmE().
isValidAlgorithmE()
int ROL::TypeE::isValidAlgorithmE (EAlgorithmE alg) inline
Verifies validity of a AlgorithmE enum.
Parameters
ls [in] - enum of the AlgorithmE
Returns
1 if the argument is a valid AlgorithmE; 0 otherwise.
Definition at line 51 of file ROL_TypeE_AlgorithmFactory.hpp.
References ALGORITHM_E_AUGMENTEDLAGRANGIAN, ALGORITHM_E_COMPOSITESTEP, ALGORITHM_E_FLETCHER, ALGORITHM_E_LAST, and ALGORITHM_E_STABILIZEDLCL.
operator++() [1/2]
EAlgorithmE & ROL::TypeE::operator++ (EAlgorithmE & type) inline
Definition at line 60 of file ROL_TypeE_AlgorithmFactory.hpp.
operator++() [2/2]
EAlgorithmE ROL::TypeE::operator++ (EAlgorithmE & type, int) inline
Definition at line 64 of file ROL_TypeE_AlgorithmFactory.hpp.
operator--() [1/2]
EAlgorithmE & ROL::TypeE::operator-- (EAlgorithmE & type) inline
Definition at line 70 of file ROL_TypeE_AlgorithmFactory.hpp.
operator--() [2/2]
EAlgorithmE ROL::TypeE::operator-- (EAlgorithmE & type, int) inline
Definition at line 74 of file ROL_TypeE_AlgorithmFactory.hpp.
StringToEAlgorithmE()
EAlgorithmE ROL::TypeE::StringToEAlgorithmE (std::string s) inline
Definition at line 80 of file ROL_TypeE_AlgorithmFactory.hpp.
References ALGORITHM_E_AUGMENTEDLAGRANGIAN, ALGORITHM_E_LAST, EAlgorithmEToString(), and ROL::removeStringFormat().
Referenced by AlgorithmFactory().
AlgorithmFactory()
template<typename Real > Ptr< TypeE::Algorithm< Real > > ROL::TypeE::AlgorithmFactory (ParameterList & parlist, const Ptr< Secant< Real > > & secant = nullPtr) inline
Definition at line 91 of file ROL_TypeE_AlgorithmFactory.hpp.
References ALGORITHM_E_AUGMENTEDLAGRANGIAN, ALGORITHM_E_COMPOSITESTEP, ALGORITHM_E_FLETCHER, ALGORITHM_E_STABILIZEDLCL, and StringToEAlgorithmE().