ROL: ROL_Objective_SerialSimOpt.hpp File Reference
ROL_Objective_SerialSimOpt.hpp File Reference
#include "ROL_Objective_TimeSimOpt.hpp"
Classes
class ROL::Objective_SerialSimOpt< Real >
Namespaces
namespace ROL
Macros
#define ROL_OBJECTIVE_SERIALSIMOPT_HPP
Typedefs
using V = Vector< Real >
using PV = PartitionedVector< Real >
using Obj = Objective_TimeSimOpt< Real >
using size_type = typename PV< Real >::size_type
Functions
template<typename Real >
ROL::Objective_SerialSimOpt Objective_SimOpt ROL::value (const V &u, const V &z, Real &tol) override
PV & partition (V &x) const
const PV & partition (const V &x) const
virtual void ROL::gradient_1 (V &g, const V &u, const V &z, Real &tol) override
virtual void ROL::gradient_2 (V &g, const V &u, const V &z, Real &tol) override
virtual void ROL::hessVec_11 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
virtual void ROL::hessVec_12 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
virtual void ROL::hessVec_21 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
virtual void ROL::hessVec_22 (V &hv, const V &v, const V &u, const V &z, Real &tol) override
Variables
const Ptr< Obj > obj_
const Ptr< V > ui_
VectorWorkspace< Real > workspace_
Objective_SerialSimOpt(const Ptr< Obj > &obj, const V &ui) z0_ zero ()
Macro Definition Documentation
ROL_OBJECTIVE_SERIALSIMOPT_HPP
#define ROL_OBJECTIVE_SERIALSIMOPT_HPP
Definition at line 12 of file ROL_Objective_SerialSimOpt.hpp.
Typedef Documentation
V
using V = Vector<Real>
Definition at line 52 of file ROL_Objective_SerialSimOpt.hpp.
PV
using PV = PartitionedVector<Real>
Definition at line 53 of file ROL_Objective_SerialSimOpt.hpp.
Obj
using Obj = Objective_TimeSimOpt<Real>
Definition at line 54 of file ROL_Objective_SerialSimOpt.hpp.
size_type
using size_type = typename PV<Real>::size_type
Definition at line 56 of file ROL_Objective_SerialSimOpt.hpp.
Function Documentation
partition() [1/2]
PV & value::partition (V & x) const protected
Definition at line 68 of file ROL_Objective_SerialSimOpt.hpp.
partition() [2/2]
const PV & value::partition (const V & x) const protected
Definition at line 70 of file ROL_Objective_SerialSimOpt.hpp.
References obj_.
Variable Documentation
obj_
const Ptr<Obj> obj_ private
Definition at line 60 of file ROL_Objective_SerialSimOpt.hpp.
Referenced by ROL::PrimalDualInteriorPointBlock11< Real >::apply(), ROL::ConstraintFromObjective< Real >::applyAdjointHessian(), ROL::ConstraintFromObjective< Real >::applyAdjointJacobian(), ROL::ConstraintFromObjective< Real >::applyJacobian(), ROL::SlacklessObjective< Real >::dirDeriv(), ROL::Problem< Real >::finalize(), ROL::Problem< Real >::getObjective(), ROL::ConstraintFromObjective< Real >::getObjective(), ROL::SlacklessObjective< Real >::getObjective(), ROL::FletcherObjectiveE< Real >::gradient(), ROL::AffineTransformObjective< Real >::gradient(), ROL::LinearCombinationObjective< Real >::gradient(), ROL::ScaledObjective< Real >::gradient(), ROL::SlacklessObjective< Real >::gradient(), ROL::MeanValueObjective< Real >::gradient(), ROL::RiskLessObjective< Real >::gradient(), ROL::Reduced_Objective_SimOpt< Real >::gradient(), ROL::gradient_2(), ROL::FletcherObjectiveE< Real >::hessVec(), ROL::AffineTransformObjective< Real >::hessVec(), ROL::LinearCombinationObjective< Real >::hessVec(), ROL::ScaledObjective< Real >::hessVec(), ROL::SlacklessObjective< Real >::hessVec(), ROL::MeanValueObjective< Real >::hessVec(), ROL::RiskLessObjective< Real >::hessVec(), ROL::Reduced_Objective_SimOpt< Real >::hessVec(), ROL::hessVec_11(), ROL::hessVec_12(), ROL::hessVec_21(), ROL::hessVec_22(), ROL::ScaledObjective< Real >::invHessVec(), ROL::SlacklessObjective< Real >::invHessVec(), ROL::FletcherObjectiveBase< Real >::objGrad(), ROL::FletcherObjectiveBase< Real >::objValue(), partition(), ROL::ScaledObjective< Real >::precond(), ROL::SlacklessObjective< Real >::precond(), ROL::MeanValueObjective< Real >::precond(), ROL::RiskLessObjective< Real >::precond(), ROL::ConstraintFromObjective< Real >::setParameter(), ROL::AffineTransformObjective< Real >::setParameter(), ROL::LinearCombinationObjective< Real >::setParameter(), ROL::ScaledObjective< Real >::setParameter(), ROL::SlacklessObjective< Real >::setParameter(), ROL::Reduced_Objective_SimOpt< Real >::setParameter(), ROL::RiskLessObjective< Real >::setParameter(), ROL::Reduced_Objective_SimOpt< Real >::solve_adjoint_equation(), ROL::Reduced_Objective_SimOpt< Real >::solve_adjoint_sensitivity(), ROL::Reduced_Objective_SimOpt< Real >::solve_state_equation(), ROL::PrimalDualInteriorPointBlock11< Real >::update(), ROL::ConstraintFromObjective< Real >::update(), ROL::AffineTransformObjective< Real >::update(), ROL::LinearCombinationObjective< Real >::update(), ROL::SlacklessObjective< Real >::update(), ROL::MeanValueObjective< Real >::update(), ROL::RiskLessObjective< Real >::update(), ROL::FletcherObjectiveBase< Real >::update(), ROL::ConstraintFromObjective< Real >::update(), ROL::AffineTransformObjective< Real >::update(), ROL::LinearCombinationObjective< Real >::update(), ROL::ScaledObjective< Real >::update(), ROL::SlacklessObjective< Real >::update(), ROL::MeanValueObjective< Real >::update(), ROL::RiskLessObjective< Real >::update(), ROL::AffineTransformObjective< Real >::value(), ROL::LinearCombinationObjective< Real >::value(), ROL::ScaledObjective< Real >::value(), ROL::SlacklessObjective< Real >::value(), ROL::MeanValueObjective< Real >::value(), ROL::RiskLessObjective< Real >::value(), ROL::Reduced_Objective_SimOpt< Real >::value(), and ROL::ConstraintFromObjective< Real >::value().
ui_
const Ptr<V> ui_ private
Definition at line 61 of file ROL_Objective_SerialSimOpt.hpp.
Referenced by ROL::gradient_2(), ROL::hessVec_11(), ROL::hessVec_12(), ROL::hessVec_21(), and ROL::hessVec_22().
workspace_
VectorWorkspace<Real> workspace_ private
Definition at line 63 of file ROL_Objective_SerialSimOpt.hpp.
Referenced by ROL::DynamicFunction< Real >::getVectorWorkspace(), and ROL::gradient_1().
zero
Objective_SerialSimOpt(const Ptr< Obj > &obj, const V &ui) z0_ zero() ()
Definition at line 77 of file ROL_Objective_SerialSimOpt.hpp.
Referenced by ROL::CompositeStep< Real >::accept(), ROL::TypeE::CompositeStepAlgorithm< Real >::accept(), ROL::Bundle_U< Real >::add(), ROL::Bundle< Real >::add(), ROL::Bundle_U< Real >::aggregate(), ROL::Bundle< Real >::aggregate(), ROL::TRUtils::analyzeRatio(), ROL::BinaryConstraint< Real >::BoundsCheck::apply(), ROL::InteriorPointObjective< Real >::ModifiedLogarithm::apply(), ROL::InteriorPointObjective< Real >::ModifiedReciprocal::apply(), ROL::InteriorPointObjective< Real >::ModifiedDivide::apply(), ROL::InteriorPointObjective< Real >::Mask::apply(), ROL::Bounds< Real >::SetZeroEntry::apply(), ROL::BoundFletcher< Real >::FormQ::apply(), ROL::BoundFletcher< Real >::FormDQ::apply(), ROL::KelleySachsModel< Real >::PruneBinding::apply(), ROL::KelleySachsModel< Real >::PruneNonbinding::apply(), ROL::LinMore< Real >::LowerBreakPoint::apply(), ROL::LinMore< Real >::UpperBreakPoint::apply(), ROL::ZOO::InequalityConstraint_HS32< Real >::applyAdjointHessian(), ROL::ReducedLinearConstraint< Real >::applyAdjointJacobian(), ROL::lDFP< Real >::applyB(), ROL::LinMoreModel< Real >::applyFreeHessian(), ROL::TypeB::LSecantBAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreeHessian(), ROL::TypeB::LSecantBAlgorithm< Real >::applyFreePrecond(), ROL::TypeB::LinMoreAlgorithm< Real >::applyFreePrecond(), ROL::LinMoreModel< Real >::applyFreePrecond(), ROL::lBFGS< Real >::applyH(), ROL::AugmentedSystemPrecOperator< Real >::applyInverse(), ROL::BoundFletcher< Real >::AugSystemPrecond::applyInverse(), ROL::Fletcher< Real >::AugSystemPrecond::applyInverse(), ROL::ReducedLinearConstraint< Real >::applyJacobian(), ROL::Bundle_U_AS< Real >::applyPreconditioner(), ROL::Bundle_AS< Real >::applyPreconditioner(), ROL::Bundle_U_AS< Real >::applyPreconditioner_Jacobi(), ROL::Bundle_AS< Real >::applyPreconditioner_Jacobi(), ROL::StdBoundConstraint< Real >::applyScalingFunctionJacobian(), ROL::Bounds< Real >::buildScalingFunction(), ROL::Bundle< Real >::Bundle(), ROL::Bundle_U< Real >::Bundle_U(), ROL::TypeU::BundleAlgorithm< Real >::BundleAlgorithm(), ROL::BundleStep< Real >::BundleStep(), ROL::ExpectationQuad< Real >::check(), ROL::GenMoreauYosidaCVaR< Real >::check(), ROL::LogQuantileQuadrangle< Real >::check(), ROL::MoreauYosidaCVaR< Real >::check(), ROL::QuantileQuadrangle< Real >::check(), ROL::SmoothedWorstCaseQuadrangle< Real >::check(), ROL::TruncatedMeanQuadrangle< Real >::check(), ROL::PD_CVaR< Real >::checkInputs(), ROL::PD_HMCR2< Real >::checkInputs(), ROL::PD_MeanSemiDeviation< Real >::checkInputs(), ROL::PD_MeanSemiDeviationFromTarget< Real >::checkInputs(), ROL::ConvexCombinationRiskMeasure< Real >::checkInputs(), ROL::MeanDeviation< Real >::checkInputs(), ROL::MeanDeviationFromTarget< Real >::checkInputs(), ROL::MeanSemiDeviation< Real >::checkInputs(), ROL::MeanVariance< Real >::checkInputs(), ROL::MixedCVaR< Real >::checkInputs(), ROL::QuantileRadius< Real >::checkInputs(), ROL::GenMoreauYosidaCVaR< Real >::checkInputs(), ROL::LogExponentialQuadrangle< Real >::checkInputs(), ROL::LogQuantileQuadrangle< Real >::checkInputs(), ROL::MeanVarianceQuadrangle< Real >::checkInputs(), ROL::MoreauYosidaCVaR< Real >::checkInputs(), ROL::QuantileQuadrangle< Real >::checkInputs(), ROL::SmoothedWorstCaseQuadrangle< Real >::checkInputs(), ROL::TruncatedMeanQuadrangle< Real >::checkInputs(), ROL::FDivergence< Real >::checkInputs(), ROL::CVaR< Real >::checkInputs(), ROL::EntropicRisk< Real >::checkInputs(), ROL::HMCR< Real >::checkInputs(), ROL::KLDivergence< Real >::checkInputs(), ROL::MeanSemiDeviationFromTarget< Real >::checkInputs(), ROL::MeanVarianceFromTarget< Real >::checkInputs(), ROL::MeanDeviation< Real >::clear(), ROL::TypeE::CompositeStepAlgorithm< Real >::CompositeStepAlgorithm(), ROL::LineSearchStep< Real >::compute(), ROL::BundleStep< Real >::compute(), ROL::PrimalDualActiveSetStep< Real >::compute(), ROL::ColemanLiModel< Real >::computeAlpha(), ROL::Sketch< Real >::computeC(), ROL::Bundle_AS< Real >::computeCriticality(), ROL::Bundle_U_AS< Real >::computeCriticality(), ROL::PD_HMCR2< Real >::computeDual(), ROL::PD_RandVarFunctional< Real >::computeDual(), ROL::MonteCarloGenerator< Real >::computeError(), ROL::MonteCarloGenerator< Real >::computeError(), ROL::Bundle_U_AS< Real >::computeLagMult(), ROL::Bundle_AS< Real >::computeLagMult(), ROL::CompositeStep< Real >::computeQuasinormalStep(), ROL::TypeE::CompositeStepAlgorithm< Real >::computeQuasinormalStep(), ROL::Bundle_U_AS< Real >::computeStepSize(), ROL::Bundle_AS< Real >::computeStepSize(), ROL::ColemanLiModel< Real >::constructC(), ROL::ColemanLiModel< Real >::constructInverseD(), ROL::TypeP::TrustRegionAlgorithm< Real >::dbls(), ROL::LinMore< Real >::dbreakpt(), ROL::Bundle_U_TT< Real >::deleteSubgradFromBase(), ROL::Bundle_TT< Real >::deleteSubgradFromBase(), ROL::TypeP::TrustRegionAlgorithm< Real >::dncg(), ROL::TypeB::LSecantBAlgorithm< Real >::dpcg(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dproj(), ROL::TypeP::TrustRegionAlgorithm< Real >::dprox(), ROL::TypeB::LinMoreAlgorithm< Real >::dprsrch(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::dpsg(), ROL::LinMore< Real >::dtrpcg(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrpcg(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrpcg(), ROL::LinMore< Real >::dtrqsol(), ROL::TypeB::ColemanLiAlgorithm< Real >::dtrqsol(), ROL::TypeB::LinMoreAlgorithm< Real >::dtrqsol(), ROL::Gaussian< Real >::erfi(), ROL::ExpectationQuad< Real >::error(), ROL::GenMoreauYosidaCVaR< Real >::error(), ROL::LogQuantileQuadrangle< Real >::error(), ROL::MoreauYosidaCVaR< Real >::error(), ROL::SmoothedWorstCaseQuadrangle< Real >::error(), ROL::TruncatedMeanQuadrangle< Real >::error(), ROL::TruncatedGaussian< Real >::evaluateCDF(), ROL::TruncatedGaussian< Real >::evaluatePDF(), ROL::Chi2Divergence< Real >::Fdual(), ROL::FletcherStep< Real >::FletcherStep(), ROL::Chi2Divergence< Real >::Fprimal(), ROL::BPOE< Real >::getGradient(), ROL::HMCR< Real >::getGradient(), ROL::MeanDeviation< Real >::getGradient(), ROL::MeanDeviationFromTarget< Real >::getGradient(), ROL::MeanVariance< Real >::getGradient(), ROL::BPOE< Real >::getHessVec(), ROL::HMCR< Real >::getHessVec(), ROL::MeanDeviation< Real >::getHessVec(), ROL::MeanDeviationFromTarget< Real >::getHessVec(), ROL::MeanVariance< Real >::getHessVec(), ROL::ZOO::getParaboloidCircle< Real, XPrim, XDual, CPrim, CDual >::getSolution(), ROL::details::MINRES< Real >::givens(), ROL::GMRES< Real >::GMRES(), ROL::Objective< Real >::gradient(), ROL::BoundFletcher< Real >::gradient(), ROL::Fletcher< Real >::gradient(), ROL::ObjectiveFromBoundConstraint< Real >::gradient(), ROL::Objective< Real >::hessVec(), ROL::BoundFletcher< Real >::hessVec(), ROL::Fletcher< Real >::hessVec(), ROL::ZOO::Objective_CylinderHead< Real >::horsepower(), ROL::MonteCarloGenerator< Real >::ierf(), ROL::Bundle_U< Real >::initialize(), ROL::Bundle< Real >::initialize(), ROL::CoherentEntropicRisk< Real >::initialize(), ROL::HMCR< Real >::initialize(), ROL::KLDivergence< Real >::initialize(), ROL::MeanDeviationFromTarget< Real >::initialize(), ROL::RandVarFunctional< Real >::initialize(), ROL::InteriorPointObjective< Real >::initialize(), ROL::TypeU::TrustRegionAlgorithm< Real >::initialize(), ROL::TypeB::SpectralGradientAlgorithm< Real >::initialize(), ROL::TypeP::SpectralGradientAlgorithm< Real >::initialize(), ROL::TrustRegionStep< Real >::initialize(), ROL::PrimalDualActiveSetStep< Real >::initialize(), ROL::Step< Real >::initialize(), ROL::Bundle_U_AS< Real >::initializeDualSolver(), ROL::Bundle_AS< Real >::initializeDualSolver(), ROL::QuantileRadius< Real >::initializeQR(), ROL::TRUtils::initialRadius(), ROL::InteriorPointPenalty< Real >::InteriorPointPenalty(), ROL::Gaussian< Real >::invertCDF(), ROL::LineSearch< Real >::LineSearch(), ROL::LineSearch_U< Real >::LineSearch_U(), ROL::Sketch< Real >::lowRankApprox(), main(), ROL::Sketch< Real >::mgs2(), ROL::MomentObjective< Real >::momentHessVec(), ROL::PlusFunction< Real >::PlusFunction(), ROL::PD_RandVarFunctional< Real >::ppf(), ROL::PH_bPOEObjective< Real >::pplus(), ROL::ProbabilityInfo(), ROL::Bundle_U_AS< Real >::project(), ROL::Bundle_AS< Real >::project(), ROL::BrentsProjection< Real >::project_df(), ROL::DaiFletcherProjection< Real >::project_df(), ROL::RiddersProjection< Real >::project_df(), ROL::SemismoothNewtonProjection< Real >::project_ssn(), ROL::Bundle_U_AS< Real >::projectedCG(), ROL::Bundle_AS< Real >::projectedCG(), ROL::Objective< Real >::proxJacVec(), ROL::Sketch< Real >::reconstruct(), ROL::LinMore< Real >::PositiveMin::reduce(), ROL::LinMore< Real >::PositiveMax::reduce(), ROL::LinMore< Real >::PositiveMin::reduce(), ROL::LinMore< Real >::PositiveMax::reduce(), ROL::GenMoreauYosidaCVaR< Real >::regret(), ROL::LogExponentialQuadrangle< Real >::regret(), ROL::LogQuantileQuadrangle< Real >::regret(), ROL::MeanVarianceQuadrangle< Real >::regret(), ROL::MoreauYosidaCVaR< Real >::regret(), ROL::QuantileQuadrangle< Real >::regret(), ROL::SmoothedWorstCaseQuadrangle< Real >::regret(), ROL::TruncatedMeanQuadrangle< Real >::regret(), ROL::Bundle_U< Real >::remove(), ROL::Bundle< Real >::remove(), ROL::Sketch< Real >::reset(), ROL::RiskMeasure< Real >::reset(), ROL::Bundle_U< Real >::resetDualVariables(), ROL::Bundle< Real >::resetDualVariables(), ROL::RiskMeasureInfo(), ROL::PathBasedTargetLevel_U< Real >::run(), ROL::GoldenSection< Real >::run(), ROL::PathBasedTargetLevel< Real >::run(), ROL::ProgressiveHedging< Real >::run(), ROL::DogLeg< Real >::run(), ROL::DoubleDogLeg< Real >::run(), ROL::LinMore< Real >::run(), ROL::TruncatedCG< Real >::run(), ROL::TypeB::ColemanLiAlgorithm< Real >::run(), ROL::TypeB::LinMoreAlgorithm< Real >::run(), ROL::TypeB::LSecantBAlgorithm< Real >::run(), ROL::TypeB::PrimalDualActiveSetAlgorithm< Real >::run(), ROL::TypeB::TrustRegionSPGAlgorithm< Real >::run(), ROL::TypeU::BundleAlgorithm< Real >::run(), ROL::TypeU::TrustRegionAlgorithm< Real >::run(), ROL::TypeP::TrustRegionAlgorithm< Real >::run(), ROL::ConjugateGradients< Real >::run(), ROL::GMRES< Real >::run(), ROL::Brents< Real >::run_brents(), ROL::MonteCarloGenerator< Real >::sample(), ROL::ScalarMinimizationLineSearch< Real >::ScalarMinimizationLineSearch(), ROL::ScalarMinimizationLineSearch_U< Real >::ScalarMinimizationLineSearch_U(), ROL::Bundle_U_TT< Real >::sgn(), ROL::Bundle_TT< Real >::sgn(), ROL::StdBoundConstraint< Real >::sgn(), ROL::StdObjective< Real >::sgn(), ROL::CauchyPoint_U< Real >::solve(), ROL::DogLeg_U< Real >::solve(), ROL::DoubleDogLeg_U< Real >::solve(), ROL::SPGTrustRegion_U< Real >::solve(), ROL::TruncatedCG_U< Real >::solve(), ROL::Constraint< Real >::solveAugmentedSystem(), ROL::Constraint< RealT >::solveAugmentedSystem(), ROL::Bundle_U_AS< Real >::solveDual_arbitrary(), ROL::Bundle_AS< Real >::solveDual_arbitrary(), ROL::Bundle_U< Real >::solveDual_dim2(), ROL::Bundle< Real >::solveDual_dim2(), ROL::Bundle_U_TT< Real >::solveDual_TT(), ROL::Bundle_TT< Real >::solveDual_TT(), ROL::Bundle_U_AS< Real >::solveEQPsubproblem(), ROL::Bundle_AS< Real >::solveEQPsubproblem(), ROL::CompositeStep< Real >::solveTangentialSubproblem(), ROL::TypeE::CompositeStepAlgorithm< Real >::solveTangentialSubproblem(), ROL::Bundle_U_TT< Real >::swapRowsL(), ROL::Bundle_TT< Real >::swapRowsL(), ROL::Brents< Real >::test_brents(), ROL::Sketch< Real >::testP(), ROL::TypeB::KelleySachsAlgorithm< Real >::trpcg(), ROL::TypeB::KelleySachsAlgorithm< Real >::trqsol(), ROL::TruncatedGaussian< Real >::TruncatedGaussian(), ROL::ZOO::Constraint_CylinderHead< Real >::twall(), ROL::Bundle_U< Real >::update(), ROL::Bundle< Real >::update(), ROL::ReducedDynamicObjective< Real >::update(), ROL::ReducedDynamicObjective< Real >::update(), ROL::TrustRegion< Real >::update(), ROL::CompositeStep< Real >::update(), ROL::PD_BPOE< Real >::updateGradient(), ROL::PD_CVaR< Real >::updateGradient(), ROL::PD_HMCR2< Real >::updateGradient(), ROL::BPOE< Real >::updateGradient(), ROL::PD_BPOE< Real >::updateHessVec(), ROL::PD_CVaR< Real >::updateHessVec(), ROL::PD_HMCR2< Real >::updateHessVec(), ROL::PD_MeanSemiDeviationFromTarget< Real >::updateHessVec(), ROL::BPOE< Real >::updateHessVec(), ROL::TypeE::CompositeStepAlgorithm< Real >::updateRadius(), ROL::PD_HMCR2< Real >::updateValue(), ROL::BPOE< Real >::updateValue(), ROL::InteriorPointObjective< Real >::value(), ROL::BallIndicatorObjective< Real >::value(), ROL::TypeBIndicatorObjective< Real >::value(), ROL::BoundFletcher< Real >::value(), ROL::Fletcher< Real >::value(), ROL::ObjectiveFromBoundConstraint< Real >::value(), ROL::ReducedLinearConstraint< Real >::value(), ROL::ZOO::Objective_CylinderHead< Real >::warranty(), and ROL::ZOO::Constraint_CylinderHead< Real >::warranty().