ROL: test_02.cpp File Reference
test_02.cpp File Reference
Perform a finite difference check on for the Hessian of the Lagrangian resulting from a Type-EB problem. Note that this test has a required dependence on Sacado. NOTE: The finite difference check can only be expected to pass if the system is not symmetrized and all bounds are finite.
#include "Teuchos_GlobalMPISession.hpp"
#include "ROL_RandomVector.hpp"
#include "ROL_StdVector.hpp"
#include "ROL_NonlinearProgram.hpp"
#include "ROL_OptimizationProblem.hpp"
#include "ROL_InteriorPointPenalty.hpp"
#include "ROL_PrimalDualInteriorPointResidual.hpp"
#include "HS_Problem_041.hpp"
#include <iomanip>
Macros
#define OPTIMIZATION_PROBLEM_REFACTOR
Typedefs
typedef double RealT
Functions
template<class Real >
void printVector (const ROL::Vector< Real > &x, std::ostream &outStream)
template<class Real >
void value (ROL::Vector< Real > &c, const ROL::Vector< Real > &sol, const Real &mu)
template<class Real >
void applyJacobian (ROL::Vector< Real > &jv, const ROL::Vector< Real > &v, const ROL::Vector< Real > &sol)
int main (int argc, char *argv[])
Detailed Description
Perform a finite difference check on for the Hessian of the Lagrangian resulting from a Type-EB problem. Note that this test has a required dependence on Sacado. NOTE: The finite difference check can only be expected to pass if the system is not symmetrized and all bounds are finite.
Definition in file step/interiorpoint/test_02.cpp.
Macro Definition Documentation
OPTIMIZATION_PROBLEM_REFACTOR
#define OPTIMIZATION_PROBLEM_REFACTOR
Definition at line 10 of file step/interiorpoint/test_02.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 173 of file step/interiorpoint/test_02.cpp.
Function Documentation
printVector()
template<class Real > void printVector (const ROL::Vector< Real > & x, std::ostream & outStream)
Definition at line 36 of file step/interiorpoint/test_02.cpp.
References printVector().
Referenced by main(), and printVector().
value()
template<class Real > void value (ROL::Vector< Real > & c, const ROL::Vector< Real > & sol, const Real & mu)
Definition at line 67 of file step/interiorpoint/test_02.cpp.
Referenced by main().
applyJacobian()
template<class Real > void applyJacobian (ROL::Vector< Real > & jv, const ROL::Vector< Real > & v, const ROL::Vector< Real > & sol)
Definition at line 118 of file step/interiorpoint/test_02.cpp.
Referenced by ROL::BinaryConstraint< Real >::applyAdjointJacobian(), ROL::Constraint< Real >::checkAdjointConsistencyJacobian(), ROL::Constraint< RealT >::checkApplyAdjointHessian(), main(), and ROL::Constraint< RealT >::solveAugmentedSystem().
main()
int main (int argc, char * argv[])
Definition at line 175 of file step/interiorpoint/test_02.cpp.
References applyJacobian(), printVector(), ROL::RandomizeVector(), and value().