ROL: test_05.cpp File Reference
test_05.cpp File Reference
#include "ROL_GetTestProblems.hpp"
#include "ROL_OptimizationSolver.hpp"
#include "ROL_Stream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include <iostream>
Macros
#define USE_HESSVEC 1
Typedefs
typedef double RealT
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
USE_HESSVEC
#define USE_HESSVEC 1
Definition at line 14 of file step/test_05.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 24 of file step/test_05.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 26 of file step/test_05.cpp.
References dim, ROL::ETestOptProblemToString(), ROL::OptimizationSolver< Real >::getAlgorithmState(), ROL::OptimizationSolver< Real >::solve(), ROL::TESTOPTPROBLEM_BVP, ROL::TESTOPTPROBLEM_HS1, ROL::TESTOPTPROBLEM_HS2, ROL::TESTOPTPROBLEM_HS25, ROL::TESTOPTPROBLEM_HS3, ROL::TESTOPTPROBLEM_HS38, ROL::TESTOPTPROBLEM_HS4, ROL::TESTOPTPROBLEM_HS45, ROL::TESTOPTPROBLEM_HS5, ROL::TESTOPTPROBLEM_LAST, ROL::TESTOPTPROBLEM_ROSENBROCK, and ROL::TYPE_B.