ROL: test_01.cpp File Reference
test_01.cpp File Reference
Verify that the interior point log-barrier penalized objective passes gradient and Hessian checks.
#include "Teuchos_GlobalMPISession.hpp"
#include "ROL_InteriorPointPenalty.hpp"
#include "ROL_RandomVector.hpp"
#include "ROL_StdVector.hpp"
#include "ROL_Bounds.hpp"
#include "ROL_ParameterList.hpp"
#include <iomanip>
Classes
class NullObjective< Real >
Typedefs
typedef double RealT
Functions
template<class Real >
void printVector (const ROL::Vector< Real > &x, std::ostream &outStream)
int main (int argc, char *argv[])
Detailed Description
Verify that the interior point log-barrier penalized objective passes gradient and Hessian checks.
Definition in file step/interiorpoint/test_01.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 56 of file step/interiorpoint/test_01.cpp.
Function Documentation
printVector()
template<class Real > void printVector (const ROL::Vector< Real > & x, std::ostream & outStream)
Definition at line 44 of file step/interiorpoint/test_01.cpp.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 58 of file step/interiorpoint/test_01.cpp.
References dim, printVector(), and ROL::RandomizeVector().