ROL: ROL::ScalarTraits< Real > Struct Template Reference
ROL::ScalarTraits< Real > Struct Template Reference
#include <ROL_ScalarTraits.hpp>
Public Types
using magnitudeType = typename ScalarTraits_Magnitude< Real >::type
Static Public Member Functions
static constexpr Real zero () noexcept
static constexpr Real half () noexcept
static constexpr Real one () noexcept
static constexpr Real two () noexcept
static constexpr Real eps () noexcept
static constexpr Real rmin () noexcept
static constexpr Real rmax () noexcept
static constexpr Real two_pi () noexcept
static constexpr Real pi () noexcept
static constexpr Real half_pi () noexcept
static constexpr Real quarter_pi () noexcept
static constexpr Real sqrt_two_pi () noexcept
static constexpr Real sqrt_pi () noexcept
static constexpr Real sqrt_half_pi () noexcept
static constexpr Real sqrt_two () noexcept
Detailed Description
template<typename Real>
struct ROL::ScalarTraits< Real >
Definition at line 32 of file ROL_ScalarTraits.hpp.
Member Typedef Documentation
magnitudeType
template<typename Real > using ROL::ScalarTraits< Real >::magnitudeType = typename ScalarTraits_Magnitude<Real>::type
Definition at line 34 of file ROL_ScalarTraits.hpp.
Member Function Documentation
zero()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::zero () inline static constexpr noexcept
Definition at line 36 of file ROL_ScalarTraits.hpp.
half()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::half () inline static constexpr noexcept
Definition at line 37 of file ROL_ScalarTraits.hpp.
one()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::one () inline static constexpr noexcept
Definition at line 38 of file ROL_ScalarTraits.hpp.
two()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::two () inline static constexpr noexcept
Definition at line 39 of file ROL_ScalarTraits.hpp.
eps()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::eps () inline static constexpr noexcept
Definition at line 41 of file ROL_ScalarTraits.hpp.
rmin()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::rmin () inline static constexpr noexcept
Definition at line 45 of file ROL_ScalarTraits.hpp.
rmax()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::rmax () inline static constexpr noexcept
Definition at line 49 of file ROL_ScalarTraits.hpp.
two_pi()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::two_pi () inline static constexpr noexcept
Definition at line 53 of file ROL_ScalarTraits.hpp.
pi()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::pi () inline static constexpr noexcept
Definition at line 57 of file ROL_ScalarTraits.hpp.
Referenced by ROL::Arcsine< Real >::evaluateCDF(), ROL::Cauchy< Real >::evaluateCDF(), ROL::RaisedCosine< Real >::evaluateCDF(), ROL::Arcsine< Real >::evaluatePDF(), ROL::Cauchy< Real >::evaluatePDF(), ROL::ZOO::getHS5< Real >::getSolution(), ROL::MonteCarloGenerator< Real >::ierf(), ROL::RaisedCosine< Real >::integrateCDF(), and ROL::RaisedCosine< Real >::moment().
half_pi()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::half_pi () inline static constexpr noexcept
Definition at line 61 of file ROL_ScalarTraits.hpp.
quarter_pi()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::quarter_pi () inline static constexpr noexcept
Definition at line 65 of file ROL_ScalarTraits.hpp.
sqrt_two_pi()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::sqrt_two_pi () inline static constexpr noexcept
Definition at line 69 of file ROL_ScalarTraits.hpp.
sqrt_pi()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::sqrt_pi () inline static constexpr noexcept
Definition at line 73 of file ROL_ScalarTraits.hpp.
sqrt_half_pi()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::sqrt_half_pi () inline static constexpr noexcept
Definition at line 77 of file ROL_ScalarTraits.hpp.
sqrt_two()
template<typename Real > static constexpr Real ROL::ScalarTraits< Real >::sqrt_two () inline static constexpr noexcept
Definition at line 81 of file ROL_ScalarTraits.hpp.
The documentation for this struct was generated from the following file:
ROL_ScalarTraits.hpp