ROL: ROL::DynamicObjectiveCheck< Real > Struct Template Reference
ROL::DynamicObjectiveCheck< Real > Struct Template Reference
#include <ROL_DynamicObjectiveCheck.hpp>
Static Public Member Functions
static void check (DynamicObjective< Real > &obj, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, const std::vector< std::string > &methods)
static void check (DynamicObjective< Real > &obj, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, TimeStamp< Real > &timeStamp, const std::vector< std::string > &methods)
static void check (DynamicObjective_CheckInterface< Real > &obj_check, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, const std::vector< std::string > &methods)
static void check (DynamicObjective< Real > &obj, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z)
static void check (DynamicObjective< Real > &obj, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, TimeStamp< Real > &ts)
Detailed Description
template<typename Real>
struct ROL::DynamicObjectiveCheck< Real >
Definition at line 24 of file ROL_DynamicObjectiveCheck.hpp.
Member Function Documentation
check() [1/5]
template<typename Real > static void ROL::DynamicObjectiveCheck< Real >::check (DynamicObjective< Real > & obj, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, const std::vector< std::string > & methods) inline static
Definition at line 26 of file ROL_DynamicObjectiveCheck.hpp.
References ROL::DynamicObjectiveCheck< Real >::check(), and ROL::make_check().
Referenced by ROL::DynamicObjectiveCheck< Real >::check(), ROL::DynamicObjectiveCheck< Real >::check(), ROL::DynamicObjectiveCheck< Real >::check(), and ROL::DynamicObjectiveCheck< Real >::check().
check() [2/5]
template<typename Real > static void ROL::DynamicObjectiveCheck< Real >::check (DynamicObjective< Real > & obj, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, TimeStamp< Real > & timeStamp, const std::vector< std::string > & methods) inline static
Definition at line 37 of file ROL_DynamicObjectiveCheck.hpp.
References ROL::DynamicObjectiveCheck< Real >::check(), and ROL::make_check().
check() [3/5]
template<typename Real > static void ROL::DynamicObjectiveCheck< Real >::check (DynamicObjective_CheckInterface< Real > & obj_check, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, const std::vector< std::string > & methods) inline static
Definition at line 49 of file ROL_DynamicObjectiveCheck.hpp.
References ROL::Vector< Real >::clone(), ROL::Vector< Real >::dual(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_un_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_uo_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_un(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::gradient_z_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_un_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_uo_z(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_un(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::hessVec_z_z(), ROL::update(), ROL::details::DynamicObjective_CheckInterface< Real >::update_un(), ROL::details::DynamicObjective_CheckInterface< Real >::update_uo(), ROL::details::DynamicObjective_CheckInterface< Real >::update_z(), ROL::value(), ROL::details::DynamicObjective_CheckInterface< Real >::value_un(), ROL::details::DynamicObjective_CheckInterface< Real >::value_uo(), and ROL::details::DynamicObjective_CheckInterface< Real >::value_z().
check() [4/5]
template<typename Real > static void ROL::DynamicObjectiveCheck< Real >::check (DynamicObjective< Real > & obj, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z) inline static
Definition at line 157 of file ROL_DynamicObjectiveCheck.hpp.
References ROL::DynamicObjectiveCheck< Real >::check().
check() [5/5]
template<typename Real > static void ROL::DynamicObjectiveCheck< Real >::check (DynamicObjective< Real > & obj, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, TimeStamp< Real > & ts) inline static
Definition at line 177 of file ROL_DynamicObjectiveCheck.hpp.
References ROL::DynamicObjectiveCheck< Real >::check().
The documentation for this struct was generated from the following file:
ROL_DynamicObjectiveCheck.hpp