ROL: ROL::DynamicConstraintCheck< Real > Struct Template Reference
ROL::DynamicConstraintCheck< Real > Struct Template Reference
#include <ROL_DynamicConstraintCheck.hpp>
Static Public Member Functions
static void check (DynamicConstraint< Real > &con, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, const std::vector< std::string > &methods)
static void check (DynamicConstraint< Real > &con, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, TimeStamp< Real > &timeStamp, const std::vector< std::string > &methods)
static void check (DynamicConstraint_CheckInterface< Real > &con_check, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, const std::vector< std::string > &methods)
static void check (DynamicConstraint< Real > &con, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z)
static void check (DynamicConstraint< Real > &con, ValidateFunction< Real > &validator, const Vector< Real > &uo, const Vector< Real > &un, const Vector< Real > &z, TimeStamp< Real > &ts)
Detailed Description
template<typename Real>
struct ROL::DynamicConstraintCheck< Real >
Definition at line 23 of file ROL_DynamicConstraintCheck.hpp.
Member Function Documentation
check() [1/5]
template<typename Real > static void ROL::DynamicConstraintCheck< Real >::check (DynamicConstraint< Real > & con, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, const std::vector< std::string > & methods) inline static
Definition at line 25 of file ROL_DynamicConstraintCheck.hpp.
References ROL::DynamicConstraintCheck< Real >::check(), and ROL::make_check().
Referenced by ROL::DynamicConstraintCheck< Real >::check(), ROL::DynamicConstraintCheck< Real >::check(), ROL::DynamicConstraintCheck< Real >::check(), and ROL::DynamicConstraintCheck< Real >::check().
check() [2/5]
template<typename Real > static void ROL::DynamicConstraintCheck< Real >::check (DynamicConstraint< Real > & con, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, TimeStamp< Real > & timeStamp, const std::vector< std::string > & methods) inline static
Definition at line 36 of file ROL_DynamicConstraintCheck.hpp.
References ROL::DynamicConstraintCheck< Real >::check(), and ROL::make_check().
check() [3/5]
template<typename Real > static void ROL::DynamicConstraintCheck< Real >::check (DynamicConstraint_CheckInterface< Real > & con_check, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, const std::vector< std::string > & methods) inline static
Definition at line 48 of file ROL_DynamicConstraintCheck.hpp.
References ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_un_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_uo_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointHessian_z_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_un_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_uo_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::adjointJacobian_z_z(), ROL::Vector< Real >::clone(), ROL::Vector< Real >::dual(), ROL::details::DynamicConstraint_CheckInterface< Real >::inverseAdjointJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::inverseJacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::jacobian_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::solve_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_uo(), ROL::details::DynamicConstraint_CheckInterface< Real >::update_z(), ROL::details::DynamicConstraint_CheckInterface< Real >::value_un(), ROL::details::DynamicConstraint_CheckInterface< Real >::value_uo(), and ROL::details::DynamicConstraint_CheckInterface< Real >::value_z().
check() [4/5]
template<typename Real > static void ROL::DynamicConstraintCheck< Real >::check (DynamicConstraint< Real > & con, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z) inline static
Definition at line 210 of file ROL_DynamicConstraintCheck.hpp.
References ROL::DynamicConstraintCheck< Real >::check().
check() [5/5]
template<typename Real > static void ROL::DynamicConstraintCheck< Real >::check (DynamicConstraint< Real > & con, ValidateFunction< Real > & validator, const Vector< Real > & uo, const Vector< Real > & un, const Vector< Real > & z, TimeStamp< Real > & ts) inline static
Definition at line 236 of file ROL_DynamicConstraintCheck.hpp.
References ROL::DynamicConstraintCheck< Real >::check().
The documentation for this struct was generated from the following file:
ROL_DynamicConstraintCheck.hpp