ROL: test_01.cpp File Reference
test_01.cpp File Reference
Test std::vector interface.
#include "ROL_StdVector.hpp"
#include "ROL_Types.hpp"
#include "ROL_Stream.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include <iostream>
Typedefs
typedef double RealT
typedef double ElementT
Functions
int main (int argc, char *argv[])
Detailed Description
Test std::vector interface.
Definition in file vector/test_01.cpp.
Typedef Documentation
RealT
typedef double RealT
Definition at line 21 of file vector/test_01.cpp.
ElementT
typedef double ElementT
Definition at line 22 of file vector/test_01.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file vector/test_01.cpp.
References ROL::StdVector< Real, Element >::basis(), ROL::Vector< Real >::checkVector(), dim, ROL::StdVector< Real, Element >::norm(), ROL::StdVector< Real, Element >::randomize(), and ROL::StdVector< Real, Element >::scale().