Intrepid: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/example/CellTools/example_04.cpp File Reference
example_04.cpp File Reference
Example of the CellTools class.
#include "Intrepid_CellTools.hpp"
#include "Intrepid_FieldContainer.hpp"
#include "Intrepid_DefaultCubatureFactory.hpp"
#include "Shards_CellTopology.hpp"
#include "Teuchos_GlobalMPISession.hpp"
Functions
void vField (double &v1, double &v2, double &v3, const double &x, const double &y, const double &z)
Evaluation of a 3D vector field in physical coordinate frame.
int main (int argc, char *argv[])
Detailed Description
Example of the CellTools class.
Author
Created by P. Bochev, D. Ridzal and K. Peterson, March 20, 2009
Definition in file example_04.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Given a vector field u(x,y,z) and a face workset we want to compute the flux of u on every face in this workset. A face workset is a set of faces that are images of the same reference face. It is defined by the following items:
cell topology of a parent cell
a set of nodes in physical frame defining the parenct cells in the workset
subcell dimension and ordinal, relative to the reference cell in 1)
Given a face workset, the key steps to accomplish the task, , are as follows:
Obtain cubature points on workset faces, i.e., in physical frame;
Obtain (non-normalized) face normals at cubature points on workset faces
Evaluate the vector field u(x,y,z) at cubature points on workset faces
Compute dot product of u(x,y,z) and the face normals, times the cubature weights
Definition at line 65 of file example_04.cpp.
References Intrepid::DefaultCubatureFactory< Scalar, ArrayPoint, ArrayWeight >::create(), Intrepid::RealSpaceTools< Scalar >::dot(), Intrepid::CellTools< Scalar >::getPhysicalFaceTangents(), Intrepid::CellTools< Scalar >::mapToPhysicalFrame(), Intrepid::CellTools< Scalar >::mapToReferenceSubcell(), Intrepid::CellTools< Scalar >::printWorksetSubcell(), Intrepid::FieldContainer< Scalar, ArrayTypeId >::resize(), Intrepid::RealSpaceTools< Scalar >::vecprod(), and vField().
vField()
void vField (double & v1, double & v2, double & v3, const double & x, const double & y, const double & z)
Evaluation of a 3D vector field in physical coordinate frame.
Parameters
v1,v2,v3 [out] - vector mfield evaluated at the argument point
x,y,z [in] - argument, a point in 3D Euclidean space
Definition at line 371 of file example_04.cpp.
Referenced by main().