Intrepid: Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar > Class Template Reference
Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar > Class Template Reference
Implementation of the default H(grad)-compatible FEM basis of degree 2 on Tetrahedron cell.
#include <Intrepid_HGRAD_TET_C2_FEM.hpp>
Public Member Functions
Basis_HGRAD_TET_C2_FEM ()
Constructor.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType) const
FEM basis evaluation on a reference Tetrahedron cell.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const ArrayScalar &cellVertices, const EOperator operatorType=OPERATOR_VALUE) const
FVD basis evaluation: invocation of this method throws an exception.
void getDofCoords (ArrayScalar &DofCoords) const
Returns spatial locations (coordinates) of degrees of freedom on a reference Tetrahedron.
Public Member Functions inherited from Intrepid::Basis< Scalar, ArrayScalar >
virtual ~Basis ()
Destructor.
virtual int getCardinality () const
Returns cardinality of the basis.
virtual int getDegree () const
Returns the degree of the basis.
virtual const shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
virtual EBasis getBasisType () const
Returns the basis type.
virtual ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
virtual int getDofOrdinal (const int subcDim, const int subcOrd, const int subcDofOrd)
DoF tag to ordinal lookup.
virtual const std::vector< std::vector< std::vector< int > > > & getDofOrdinalData ()
DoF tag to ordinal data structure.
virtual const std::vector< int > & getDofTag (const int dofOrd)
DoF ordinal to DoF tag lookup.
virtual const std::vector< std::vector< int > > & getAllDofTags ()
Retrieves all DoF tags.
Public Member Functions inherited from Intrepid::DofCoordsInterface< ArrayScalar >
virtual ~DofCoordsInterface ()=0
Pure virtual destructor (gives warnings if not included). Following "Effective C++: 3rd Ed." item 7 the implementation is included in the definition file.
Private Member Functions
void initializeTags ()
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Additional Inherited Members
Protected Attributes inherited from Intrepid::Basis< Scalar, ArrayScalar >
int basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
int basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
shards::CellTopology basisCellTopology_
Base topology of the cells for which the basis is defined. See the Shards package http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
bool basisTagsAreSet_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
std::vector< std::vector< int > > ordinalToTag_
DoF ordinal to tag lookup table.
std::vector< std::vector< std::vector< int > > > tagToOrdinal_
DoF tag to ordinal lookup table.
Detailed Description
template<class Scalar, class ArrayScalar>
class Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >
Implementation of the default H(grad)-compatible FEM basis of degree 2 on Tetrahedron cell.
    Implements Lagrangian basis of degree 2 on the reference Tetrahedron cell. The basis has
    cardinality 10 and spans a COMPLETE quadratic polynomial space. Basis functions are dual
    to a unisolvent set of degrees-of-freedom (DoF) defined and enumerated as follows:
=================================================================================================
|         |           degree-of-freedom-tag table                    |                           |
|   DoF   |----------------------------------------------------------|      DoF definition       |
| ordinal |  subc dim    | subc ordinal | subc DoF ord |subc num DoF |                           |
|=========|==============|==============|==============|=============|===========================|
|    0    |       0      |       0      |       0      |      1      |   L_0(u) = u(0,0,0)       |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    1    |       0      |       1      |       0      |      1      |   L_1(u) = u(1,0,0)       |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    2    |       0      |       2      |       0      |      1      |   L_2(u) = u(0,1,0)       |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    3    |       0      |       3      |       0      |      1      |   L_3(u) = u(0,0,1)       |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    4    |       1      |       0      |       0      |      1      |   L_4(u) = u(1/2,0,0)     |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    5    |       1      |       1      |       0      |      1      |   L_5(u) = u(1/2,1/2,0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    6    |       1      |       2      |       0      |      1      |   L_6(u) = u(0,1/2,0)     |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    7    |       1      |       3      |       0      |      1      |   L_7(u) = u(0,0,1/2)     |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    8    |       1      |       4      |       0      |      1      |   L_8(u) = u(1/2,0,1/2)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    9    |       1      |       5      |       0      |      1      |   L_9(u) = u(0,1/2,1/2)   |
|=========|==============|==============|==============|=============|===========================|
|   MAX   |  maxScDim=0  |  maxScOrd=3  |  maxDfOrd=0  |     -       |                           |
|=========|==============|==============|==============|=============|===========================|
Remarks
Ordering of DoFs follows the node order in Tetrahedron<10> topology. Note that node order in this topology follows the natural order of k-subcells where the nodes are located, i.e., L_0 to L_3 correspond to 0-subcells (vertices) 0 to 3 and L_4 to L_9 correspond to 1-subcells (edges) 0 to 5.
Definition at line 99 of file Intrepid_HGRAD_TET_C2_FEM.hpp.
Constructor & Destructor Documentation
Basis_HGRAD_TET_C2_FEM()
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >::Basis_HGRAD_TET_C2_FEM ()
Constructor.
Definition at line 54 of file Intrepid_HGRAD_TET_C2_FEMDef.hpp.
Member Function Documentation
getDofCoords()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >::getDofCoords (ArrayScalar & DofCoords) const virtual
Returns spatial locations (coordinates) of degrees of freedom on a reference Tetrahedron.
Parameters
DofCoords [out] - array with the coordinates of degrees of freedom, dimensioned (F,D)
Implements Intrepid::DofCoordsInterface< ArrayScalar >.
Definition at line 324 of file Intrepid_HGRAD_TET_C2_FEMDef.hpp.
getValues() [1/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const ArrayScalar & cellVertices, const EOperator operatorType = OPERATOR_VALUE) const virtual
FVD basis evaluation: invocation of this method throws an exception.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 313 of file Intrepid_HGRAD_TET_C2_FEMDef.hpp.
getValues() [2/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType) const virtual
FEM basis evaluation on a reference Tetrahedron cell.
    Returns values of <var>operatorType</var> acting on FEM basis functions for a set of
    points in the <strong>reference Tetrahedron</strong> cell. For rank and dimensions of
    I/O array arguments see Section \ref basis_md_array_sec .
Parameters
outputValues [out] - rank-2 or 3 array with the computed basis values
inputPoints [in] - rank-2 array with dimensions (P,D) containing reference points
operatorType [in] - operator applied to basis functions
For rank and dimension specifications of ArrayScalar arguments see basis_array_specs
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 101 of file Intrepid_HGRAD_TET_C2_FEMDef.hpp.
References Intrepid::getDkCardinality(), and Intrepid::isValidOperator().
initializeTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >::initializeTags () private virtual
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 66 of file Intrepid_HGRAD_TET_C2_FEMDef.hpp.
References Intrepid::setOrdinalTagData().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_TET_C2_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_TET_C2_FEMDef.hpp