Intrepid: Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar > Class Template Reference
Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar > Class Template Reference
Implementation of the default H(grad)-compatible FEM basis of degree 1 on Wedge cell.
#include <Intrepid_HGRAD_WEDGE_C1_FEM.hpp>
Public Member Functions
Basis_HGRAD_WEDGE_C1_FEM ()
Constructor.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType) const
FEM basis evaluation on a reference Wedge cell.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const ArrayScalar &cellVertices, const EOperator operatorType=OPERATOR_VALUE) const
FVD basis evaluation: invocation of this method throws an exception.
Public Member Functions inherited from Intrepid::Basis< Scalar, ArrayScalar >
virtual ~Basis ()
Destructor.
virtual int getCardinality () const
Returns cardinality of the basis.
virtual int getDegree () const
Returns the degree of the basis.
virtual const shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
virtual EBasis getBasisType () const
Returns the basis type.
virtual ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
virtual int getDofOrdinal (const int subcDim, const int subcOrd, const int subcDofOrd)
DoF tag to ordinal lookup.
virtual const std::vector< std::vector< std::vector< int > > > & getDofOrdinalData ()
DoF tag to ordinal data structure.
virtual const std::vector< int > & getDofTag (const int dofOrd)
DoF ordinal to DoF tag lookup.
virtual const std::vector< std::vector< int > > & getAllDofTags ()
Retrieves all DoF tags.
Private Member Functions
void initializeTags ()
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Additional Inherited Members
Protected Attributes inherited from Intrepid::Basis< Scalar, ArrayScalar >
int basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
int basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
shards::CellTopology basisCellTopology_
Base topology of the cells for which the basis is defined. See the Shards package http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
bool basisTagsAreSet_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
std::vector< std::vector< int > > ordinalToTag_
DoF ordinal to tag lookup table.
std::vector< std::vector< std::vector< int > > > tagToOrdinal_
DoF tag to ordinal lookup table.
Detailed Description
template<class Scalar, class ArrayScalar>
class Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar >
Implementation of the default H(grad)-compatible FEM basis of degree 1 on Wedge cell.
    Implements Lagrangian basis of degree 1 on the reference Wedge cell. The basis has
    cardinality 6 and spans a COMPLETE bi-linear polynomial space. Basis functions are dual
    to a unisolvent set of degrees-of-freedom (DoF) defined and enumerated as follows:
=================================================================================================
|         |           degree-of-freedom-tag table                    |                           |
|   DoF   |----------------------------------------------------------|      DoF definition       |
| ordinal |  subc dim    | subc ordinal | subc DoF ord |subc num DoF |                           |
|=========|==============|==============|==============|=============|===========================|
|    0    |       0      |       0      |       0      |      1      |   L_0(u) = u(0, 0,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    1    |       0      |       1      |       0      |      1      |   L_1(u) = u(1, 0,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    2    |       0      |       2      |       0      |      1      |   L_2(u) = u(0, 1,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    3    |       0      |       3      |       0      |      1      |   L_3(u) = u(0, 0, 1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    4    |       0      |       4      |       0      |      1      |   L_4(u) = u(1, 0, 1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    5    |       0      |       5      |       0      |      1      |   L_5(u) = u(0, 1, 1)    |
|=========|==============|==============|==============|=============|===========================|
|   MAX   |  maxScDim=0  |  maxScOrd=5  |  maxDfOrd=0  |      -      |                           |
|=========|==============|==============|==============|=============|===========================|
Definition at line 85 of file Intrepid_HGRAD_WEDGE_C1_FEM.hpp.
Constructor & Destructor Documentation
Basis_HGRAD_WEDGE_C1_FEM()
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar >::Basis_HGRAD_WEDGE_C1_FEM ()
Constructor.
Definition at line 54 of file Intrepid_HGRAD_WEDGE_C1_FEMDef.hpp.
Member Function Documentation
getValues() [1/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const ArrayScalar & cellVertices, const EOperator operatorType = OPERATOR_VALUE) const virtual
FVD basis evaluation: invocation of this method throws an exception.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 236 of file Intrepid_HGRAD_WEDGE_C1_FEMDef.hpp.
getValues() [2/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType) const virtual
FEM basis evaluation on a reference Wedge cell.
    Returns values of <var>operatorType</var> acting on FEM basis functions for a set of
    points in the <strong>reference Wedge</strong> cell. For rank and dimensions of
    I/O array arguments see Section \ref basis_md_array_sec .
Parameters
outputValues [out] - rank-2 or 3 array with the computed basis values
inputPoints [in] - rank-2 array with dimensions (P,D) containing reference points
operatorType [in] - operator applied to basis functions
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 96 of file Intrepid_HGRAD_WEDGE_C1_FEMDef.hpp.
References Intrepid::getDkCardinality(), and Intrepid::isValidOperator().
initializeTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar >::initializeTags () private virtual
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 66 of file Intrepid_HGRAD_WEDGE_C1_FEMDef.hpp.
References Intrepid::setOrdinalTagData().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_WEDGE_C1_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_WEDGE_C1_FEMDef.hpp