Intrepid: Intrepid::IntrepidBurkardtRules Class Reference
Intrepid::IntrepidBurkardtRules Class Reference
Providing integration rules, created by John Burkardt, Scientific Computing, Florida State University, modified and redistributed by D. Kouri.
#include <Intrepid_BurkardtRules.hpp>
Static Public Member Functions
template<class Scalar >
static void imtqlx (int n, Scalar d[], Scalar e[], Scalar z[])
template<class Scalar >
static Scalar r8_epsilon (Scalar one)
template<class Scalar >
static Scalar r8_sign (Scalar x)
template<class Scalar >
static void chebyshev1_compute (int order, Scalar x[], Scalar w[])
Gauss-Chebyshev of Type 1; returns points and weights.
template<class Scalar >
static void chebyshev1_compute_points (int order, Scalar x[])
Gauss-Chebyshev of Type 1; returns points.
template<class Scalar >
static void chebyshev1_compute_weights (int order, Scalar w[])
Gauss-Chebyshev of Type 1; returns weights.
template<class Scalar >
static void chebyshev2_compute (int order, Scalar x[], Scalar w[])
Gauss-Chebyshev of Type 2; returns points and weights.
template<class Scalar >
static void chebyshev2_compute_points (int order, Scalar x[])
Gauss-Chebyshev of Type 2; returns points.
template<class Scalar >
static void chebyshev2_compute_weights (int order, Scalar w[])
Gauss-Chebyshev of Type 2; returns weights.
template<class Scalar >
static void clenshaw_curtis_compute (int order, Scalar x[], Scalar w[])
Clenshaw-Curtis; returns points and weights.
template<class Scalar >
static void clenshaw_curtis_compute_points (int order, Scalar x[])
Clenshaw-Curtis; returns points.
template<class Scalar >
static void clenshaw_curtis_compute_weights (int order, Scalar w[])
Clenshaw-Curtis; returns weights.
template<class Scalar >
static void fejer2_compute (int order, Scalar x[], Scalar w[])
Fejer type 2; returns points and weights.
template<class Scalar >
static void fejer2_compute_points (int order, Scalar x[])
Fejer type 2; returns points.
template<class Scalar >
static void fejer2_compute_weights (int order, Scalar w[])
Fejer type 2; returns weights.
template<class Scalar >
static void hermite_compute (int order, Scalar x[], Scalar w[])
Gauss-Hermite; returns points and weights.
template<class Scalar >
static void hermite_compute_points (int order, Scalar x[])
Gauss-Hermite; returns points.
template<class Scalar >
static void hermite_compute_weights (int order, Scalar w[])
Gauss-Hermite; returns weights.
template<class Scalar >
static void hermite_lookup (int n, Scalar x[], Scalar w[])
Gauss-Hermite; returns points and weights.
template<class Scalar >
static void hermite_lookup_points (int n, Scalar x[])
Gauss-Hermite; returns points.
template<class Scalar >
static void hermite_lookup_weights (int n, Scalar w[])
Gauss-Hermite; returns weights.
template<class Scalar >
static void hermite_genz_keister_lookup (int n, Scalar x[], Scalar w[])
Hermite-Genz-Keister; returns points and weights.
template<class Scalar >
static void hermite_genz_keister_lookup_points (int n, Scalar x[])
Hermite-Genz-Keister; returns points.
template<class Scalar >
static void hermite_genz_keister_lookup_weights (int n, Scalar w[])
Hermite-Genz-Keister; returns weights.
template<class Scalar >
static void laguerre_compute (int n, Scalar x[], Scalar w[])
Gauss-Laguerre; returns points and weights.
template<class Scalar >
static void laguerre_compute_points (int order, Scalar x[])
Gauss-Laguerre; returns points.
template<class Scalar >
static void laguerre_compute_weights (int order, Scalar w[])
Gauss-Laguerre; returns weights.
template<class Scalar >
static void laguerre_lookup (int n, Scalar x[], Scalar w[])
Gauss-Laguerre; returns points and weights.
template<class Scalar >
static void laguerre_lookup_points (int n, Scalar x[])
Gauss-Laguerre; returns points.
template<class Scalar >
static void laguerre_lookup_weights (int n, Scalar w[])
Gauss-Laguerre; returns weights.
template<class Scalar >
static void legendre_compute (int n, Scalar x[], Scalar w[])
Gauss-Legendre; returns points and weights.
template<class Scalar >
static void legendre_compute_points (int order, Scalar x[])
Gauss-Legendre; returns points.
template<class Scalar >
static void legendre_compute_weights (int order, Scalar w[])
Gauss-Legendre; returns weights.
template<class Scalar >
static void legendre_lookup (int n, Scalar x[], Scalar w[])
Gauss-Legendre; returns points and weights.
template<class Scalar >
static void legendre_lookup_points (int n, Scalar x[])
Gauss-Legendre; returns points.
template<class Scalar >
static void legendre_lookup_weights (int n, Scalar w[])
Gauss-Legendre; returns weights.
template<class Scalar >
static void patterson_lookup (int n, Scalar x[], Scalar w[])
Gauss-Patterson; returns points and weights.
template<class Scalar >
static void patterson_lookup_points (int n, Scalar x[])
Gauss-Patterson; returns points.
template<class Scalar >
static void patterson_lookup_weights (int n, Scalar w[])
Gauss-Patterson; returns weights.
template<class Scalar >
static void trapezoidal_compute (int n, Scalar x[], Scalar w[])
Trapezoidal rule; returns points and weights.
template<class Scalar >
static void trapezoidal_compute_points (int order, Scalar x[])
Trapezoidal rule; returns points.
template<class Scalar >
static void trapezoidal_compute_weights (int order, Scalar w[])
Trapezoidal rule; returns weights.
Detailed Description
Providing integration rules, created by John Burkardt, Scientific Computing, Florida State University, modified and redistributed by D. Kouri.
See <\A>
Definition at line 115 of file Intrepid_BurkardtRules.hpp.
Member Function Documentation
chebyshev1_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::chebyshev1_compute (int order, Scalar x[], Scalar w[]) static
Gauss-Chebyshev of Type 1; returns points and weights.
Definition at line 62 of file Intrepid_BurkardtRulesDef.hpp.
chebyshev1_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::chebyshev1_compute_points (int order, Scalar x[]) static
Gauss-Chebyshev of Type 1; returns points.
Definition at line 132 of file Intrepid_BurkardtRulesDef.hpp.
chebyshev1_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::chebyshev1_compute_weights (int order, Scalar w[]) static
Gauss-Chebyshev of Type 1; returns weights.
Definition at line 187 of file Intrepid_BurkardtRulesDef.hpp.
chebyshev2_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::chebyshev2_compute (int order, Scalar x[], Scalar w[]) static
Gauss-Chebyshev of Type 2; returns points and weights.
Definition at line 239 of file Intrepid_BurkardtRulesDef.hpp.
chebyshev2_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::chebyshev2_compute_points (int order, Scalar x[]) static
Gauss-Chebyshev of Type 2; returns points.
Definition at line 311 of file Intrepid_BurkardtRulesDef.hpp.
chebyshev2_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::chebyshev2_compute_weights (int order, Scalar w[]) static
Gauss-Chebyshev of Type 2; returns weights.
Definition at line 370 of file Intrepid_BurkardtRulesDef.hpp.
clenshaw_curtis_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::clenshaw_curtis_compute (int order, Scalar x[], Scalar w[]) static
Clenshaw-Curtis; returns points and weights.
Definition at line 425 of file Intrepid_BurkardtRulesDef.hpp.
clenshaw_curtis_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::clenshaw_curtis_compute_points (int order, Scalar x[]) static
Clenshaw-Curtis; returns points.
Definition at line 516 of file Intrepid_BurkardtRulesDef.hpp.
clenshaw_curtis_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::clenshaw_curtis_compute_weights (int order, Scalar w[]) static
Clenshaw-Curtis; returns weights.
Definition at line 574 of file Intrepid_BurkardtRulesDef.hpp.
fejer2_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::fejer2_compute (int order, Scalar x[], Scalar w[]) static
Fejer type 2; returns points and weights.
Definition at line 653 of file Intrepid_BurkardtRulesDef.hpp.
fejer2_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::fejer2_compute_points (int order, Scalar x[]) static
Fejer type 2; returns points.
Definition at line 734 of file Intrepid_BurkardtRulesDef.hpp.
fejer2_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::fejer2_compute_weights (int order, Scalar w[]) static
Fejer type 2; returns weights.
Definition at line 791 of file Intrepid_BurkardtRulesDef.hpp.
hermite_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_compute (int order, Scalar x[], Scalar w[]) static
Gauss-Hermite; returns points and weights.
Definition at line 877 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by hermite_compute_points(), and hermite_compute_weights().
hermite_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_compute_points (int order, Scalar x[]) static
Gauss-Hermite; returns points.
Definition at line 972 of file Intrepid_BurkardtRulesDef.hpp.
References hermite_compute().
hermite_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_compute_weights (int order, Scalar w[]) static
Gauss-Hermite; returns weights.
Definition at line 1007 of file Intrepid_BurkardtRulesDef.hpp.
References hermite_compute().
hermite_genz_keister_lookup()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_genz_keister_lookup (int n, Scalar x[], Scalar w[]) static
Hermite-Genz-Keister; returns points and weights.
Definition at line 1042 of file Intrepid_BurkardtRulesDef.hpp.
References hermite_genz_keister_lookup_points(), and hermite_genz_keister_lookup_weights().
hermite_genz_keister_lookup_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_genz_keister_lookup_points (int n, Scalar x[]) static
Hermite-Genz-Keister; returns points.
Definition at line 1114 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by hermite_genz_keister_lookup().
hermite_genz_keister_lookup_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_genz_keister_lookup_weights (int n, Scalar w[]) static
Hermite-Genz-Keister; returns weights.
Definition at line 1405 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by hermite_genz_keister_lookup().
hermite_lookup()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_lookup (int n, Scalar x[], Scalar w[]) static
Gauss-Hermite; returns points and weights.
Definition at line 1696 of file Intrepid_BurkardtRulesDef.hpp.
References hermite_lookup_points(), and hermite_lookup_weights().
hermite_lookup_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_lookup_points (int n, Scalar x[]) static
Gauss-Hermite; returns points.
Definition at line 1766 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by hermite_lookup().
hermite_lookup_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::hermite_lookup_weights (int n, Scalar w[]) static
Gauss-Hermite; returns weights.
Definition at line 2104 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by hermite_lookup().
imtqlx()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::imtqlx (int n, Scalar d[], Scalar e[], Scalar z[]) static
Definition at line 2442 of file Intrepid_BurkardtRulesDef.hpp.
laguerre_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::laguerre_compute (int n, Scalar x[], Scalar w[]) static
Gauss-Laguerre; returns points and weights.
Definition at line 2605 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by laguerre_compute_points(), and laguerre_compute_weights().
laguerre_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::laguerre_compute_points (int order, Scalar x[]) static
Gauss-Laguerre; returns points.
Definition at line 2683 of file Intrepid_BurkardtRulesDef.hpp.
References laguerre_compute().
laguerre_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::laguerre_compute_weights (int order, Scalar w[]) static
Gauss-Laguerre; returns weights.
Definition at line 2718 of file Intrepid_BurkardtRulesDef.hpp.
References laguerre_compute().
laguerre_lookup()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::laguerre_lookup (int n, Scalar x[], Scalar w[]) static
Gauss-Laguerre; returns points and weights.
Definition at line 2753 of file Intrepid_BurkardtRulesDef.hpp.
References laguerre_lookup_points(), and laguerre_lookup_weights().
laguerre_lookup_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::laguerre_lookup_points (int n, Scalar x[]) static
Gauss-Laguerre; returns points.
Definition at line 2847 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by laguerre_lookup().
laguerre_lookup_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::laguerre_lookup_weights (int n, Scalar w[]) static
Gauss-Laguerre; returns weights.
Definition at line 3169 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by laguerre_lookup().
legendre_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::legendre_compute (int n, Scalar x[], Scalar w[]) static
Gauss-Legendre; returns points and weights.
Definition at line 3491 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by legendre_compute_points(), and legendre_compute_weights().
legendre_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::legendre_compute_points (int order, Scalar x[]) static
Gauss-Legendre; returns points.
Definition at line 3576 of file Intrepid_BurkardtRulesDef.hpp.
References legendre_compute().
legendre_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::legendre_compute_weights (int order, Scalar w[]) static
Gauss-Legendre; returns weights.
Definition at line 3611 of file Intrepid_BurkardtRulesDef.hpp.
References legendre_compute().
legendre_lookup()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::legendre_lookup (int n, Scalar x[], Scalar w[]) static
Gauss-Legendre; returns points and weights.
Definition at line 3646 of file Intrepid_BurkardtRulesDef.hpp.
References legendre_lookup_points(), and legendre_lookup_weights().
legendre_lookup_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::legendre_lookup_points (int n, Scalar x[]) static
Gauss-Legendre; returns points.
Definition at line 3716 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by legendre_lookup().
legendre_lookup_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::legendre_lookup_weights (int n, Scalar w[]) static
Gauss-Legendre; returns weights.
Definition at line 4415 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by legendre_lookup().
patterson_lookup()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::patterson_lookup (int n, Scalar x[], Scalar w[]) static
Gauss-Patterson; returns points and weights.
Definition at line 5114 of file Intrepid_BurkardtRulesDef.hpp.
References patterson_lookup_points(), and patterson_lookup_weights().
patterson_lookup_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::patterson_lookup_points (int n, Scalar x[]) static
Gauss-Patterson; returns points.
Definition at line 5170 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by patterson_lookup().
patterson_lookup_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::patterson_lookup_weights (int n, Scalar w[]) static
Gauss-Patterson; returns weights.
Definition at line 5745 of file Intrepid_BurkardtRulesDef.hpp.
Referenced by patterson_lookup().
r8_epsilon()
template<class Scalar > Scalar Intrepid::IntrepidBurkardtRules::r8_epsilon (Scalar one) static
Definition at line 6385 of file Intrepid_BurkardtRulesDef.hpp.
r8_sign()
template<class Scalar > Scalar Intrepid::IntrepidBurkardtRules::r8_sign (Scalar x) static
Definition at line 6430 of file Intrepid_BurkardtRulesDef.hpp.
trapezoidal_compute()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::trapezoidal_compute (int n, Scalar x[], Scalar w[]) static
Trapezoidal rule; returns points and weights.
Definition at line 6322 of file Intrepid_BurkardtRulesDef.hpp.
trapezoidal_compute_points()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::trapezoidal_compute_points (int order, Scalar x[]) static
Trapezoidal rule; returns points.
Definition at line 6346 of file Intrepid_BurkardtRulesDef.hpp.
trapezoidal_compute_weights()
template<class Scalar > void Intrepid::IntrepidBurkardtRules::trapezoidal_compute_weights (int order, Scalar w[]) static
Trapezoidal rule; returns weights.
Definition at line 6363 of file Intrepid_BurkardtRulesDef.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Shared/Intrepid_BurkardtRules.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Shared/Intrepid_BurkardtRulesDef.hpp