Intrepid: Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar > Class Template Reference
Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar > Class Template Reference
Implements Hermite interpolant basis of degree n on the reference Line cell. The basis has cardinality 2n and spans a COMPLETE linear polynomial space.
#include <Intrepid_HGRAD_LINE_Hermite_FEM.hpp>
Public Member Functions
Basis_HGRAD_LINE_Hermite_FEM ()
Default Constructor assumes the two interpolation points are the cell vertices. Cubic Hermite Interpolation.
Basis_HGRAD_LINE_Hermite_FEM (const ArrayScalar &pts)
Constructor.
Basis_HGRAD_LINE_Hermite_FEM (int numPoints, const EPointType &pointType)
Constructor.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType) const
Evaluation of a FEM basis on a reference Line cell.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const ArrayScalar &cellVertices, const EOperator operatorType=OPERATOR_VALUE) const
FVD basis evaluation: invocation of this method throws an exception.
virtual void getDofCoords (ArrayScalar &DofCoords) const
implements the dofcoords interface
void printTags (std::ostream &os)
Public Member Functions inherited from Intrepid::Basis< Scalar, ArrayScalar >
virtual ~Basis ()
Destructor.
virtual int getCardinality () const
Returns cardinality of the basis.
virtual int getDegree () const
Returns the degree of the basis.
virtual const shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
virtual EBasis getBasisType () const
Returns the basis type.
virtual ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
virtual int getDofOrdinal (const int subcDim, const int subcOrd, const int subcDofOrd)
DoF tag to ordinal lookup.
virtual const std::vector< std::vector< std::vector< int > > > & getDofOrdinalData ()
DoF tag to ordinal data structure.
virtual const std::vector< int > & getDofTag (const int dofOrd)
DoF ordinal to DoF tag lookup.
virtual const std::vector< std::vector< int > > & getAllDofTags ()
Retrieves all DoF tags.
Private Types
template<typename T >
using RCP = Teuchos::RCP< T >
using SerialDenseMatrix = Teuchos::SerialDenseMatrix< int, Scalar >
using TAGS = std::vector< int >
Private Member Functions
void initializeTags ()
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
void recurrence (ArrayScalar &P, ArrayScalar &Px, const Scalar x) const
Evaluates and at a particular point .
void legendre_d (ArrayScalar &Pm, ArrayScalar &Pm1, const int m, const Scalar pt) const
Evaluates and at a particular point .
void setupVandermonde (bool factor=true)
Form the Legendre/Derivative Vandermonde matrix at the given lattice points and have the linear solver factor with equilibration.
Private Attributes
FieldContainer< Scalar > latticePts_
Holds the points defining the Hermite basis.
SerialDenseMatrix V_
Contains the values of the Legendre polynomials and their derivatives.
Teuchos::SerialDenseSolver< int, Scalar > solver_
TAGS tags_
bool isFactored_
Additional Inherited Members
Protected Attributes inherited from Intrepid::Basis< Scalar, ArrayScalar >
int basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
int basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
shards::CellTopology basisCellTopology_
Base topology of the cells for which the basis is defined. See the Shards package http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
bool basisTagsAreSet_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
std::vector< std::vector< int > > ordinalToTag_
DoF ordinal to tag lookup table.
std::vector< std::vector< std::vector< int > > > tagToOrdinal_
DoF tag to ordinal lookup table.
Detailed Description
template<class Scalar, class ArrayScalar>
class Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >
Implements Hermite interpolant basis of degree n on the reference Line cell. The basis has cardinality 2n and spans a COMPLETE linear polynomial space.
The Hermite interpolant approximation space is where
The basis functions determined by the interpolation points which satisfy the ordering property
while the basis functions satisfy
Basis functions and their derivatives are evaluated from the Legendre polynomials and their derivatives evaluated on the interpolation points and the input points in the getValues() method. Legendre polynomials and their derivatives are computed using the relations
Definition at line 93 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
Member Typedef Documentation
RCP
template<class Scalar , class ArrayScalar > template<typename T > using Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::RCP = Teuchos::RCP<T> private
Definition at line 95 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
SerialDenseMatrix
template<class Scalar , class ArrayScalar > using Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::SerialDenseMatrix = Teuchos::SerialDenseMatrix<int,Scalar> private
Definition at line 96 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
TAGS
template<class Scalar , class ArrayScalar > using Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::TAGS = std::vector<int> private
Definition at line 98 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
Constructor & Destructor Documentation
Basis_HGRAD_LINE_Hermite_FEM() [1/3]
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM ()
Default Constructor assumes the two interpolation points are the cell vertices. Cubic Hermite Interpolation.
Definition at line 60 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
References Intrepid::Basis< Scalar, ArrayScalar >::basisCardinality_, Intrepid::Basis< Scalar, ArrayScalar >::basisCellTopology_, Intrepid::Basis< Scalar, ArrayScalar >::basisCoordinates_, Intrepid::Basis< Scalar, ArrayScalar >::basisDegree_, Intrepid::Basis< Scalar, ArrayScalar >::basisTagsAreSet_, Intrepid::Basis< Scalar, ArrayScalar >::basisType_, Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::latticePts_, and Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::setupVandermonde().
Basis_HGRAD_LINE_Hermite_FEM() [2/3]
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM (const ArrayScalar & pts)
Constructor.
Parameters
int pointType: [in] array containing interpolation points
Definition at line 80 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
References Intrepid::Basis< Scalar, ArrayScalar >::basisCardinality_, Intrepid::Basis< Scalar, ArrayScalar >::basisCellTopology_, Intrepid::Basis< Scalar, ArrayScalar >::basisCoordinates_, Intrepid::Basis< Scalar, ArrayScalar >::basisDegree_, Intrepid::Basis< Scalar, ArrayScalar >::basisTagsAreSet_, Intrepid::Basis< Scalar, ArrayScalar >::basisType_, Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::latticePts_, and Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::setupVandermonde().
Basis_HGRAD_LINE_Hermite_FEM() [3/3]
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM (int numPoints, const EPointType & pointType)
Constructor.
Parameters
int numPoints: [in] number of interpolation points
int pointType: [in] type of points, either POINTTYPE_EQUISPACED or POINTTYPE_SPECTRAL
Definition at line 121 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
References Intrepid::Basis< Scalar, ArrayScalar >::basisCardinality_, Intrepid::Basis< Scalar, ArrayScalar >::basisCellTopology_, Intrepid::Basis< Scalar, ArrayScalar >::basisCoordinates_, Intrepid::Basis< Scalar, ArrayScalar >::basisDegree_, Intrepid::Basis< Scalar, ArrayScalar >::basisTagsAreSet_, Intrepid::Basis< Scalar, ArrayScalar >::basisType_, Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::latticePts_, and Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::setupVandermonde().
Member Function Documentation
getDofCoords()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::getDofCoords (ArrayScalar & DofCoords) const virtual
implements the dofcoords interface
Definition at line 549 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
getValues() [1/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const ArrayScalar & cellVertices, const EOperator operatorType = OPERATOR_VALUE) const virtual
FVD basis evaluation: invocation of this method throws an exception.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 539 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
getValues() [2/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType) const virtual
Evaluation of a FEM basis on a reference Line cell.
    Returns values of <var>operatorType</var> acting on FEM basis functions for a set of
    points in the <strong>reference Line</strong> cell. For rank and dimensions of
    I/O array arguments see Section \ref basis_md_array_sec .
Parameters
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-n array (P,D) with the evaluation points
operatorType [in] - the operator acting on the basis functions
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 252 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
References Intrepid::isValidOperator().
initializeTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::initializeTags () private virtual
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 377 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
References Intrepid::setOrdinalTagData().
legendre_d()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::legendre_d (ArrayScalar & Pm, ArrayScalar & Pm1, const int m, const Scalar pt) const private
Evaluates and at a particular point .
Definition at line 222 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
printTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::printTags (std::ostream & os)
Definition at line 490 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
recurrence()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::recurrence (ArrayScalar & P, ArrayScalar & Px, const Scalar x) const private
Evaluates and at a particular point .
Definition at line 201 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
setupVandermonde()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::setupVandermonde (bool factor = true) private
Form the Legendre/Derivative Vandermonde matrix at the given lattice points and have the linear solver factor with equilibration.
Definition at line 160 of file Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp.
Referenced by Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM(), Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM(), and Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM().
Member Data Documentation
isFactored_
template<class Scalar , class ArrayScalar > bool Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::isFactored_ mutable private
Definition at line 112 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
latticePts_
template<class Scalar , class ArrayScalar > FieldContainer<Scalar> Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::latticePts_ private
Holds the points defining the Hermite basis.
Definition at line 103 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
Referenced by Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM(), Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM(), and Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::Basis_HGRAD_LINE_Hermite_FEM().
solver_
template<class Scalar , class ArrayScalar > Teuchos::SerialDenseSolver<int,Scalar> Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::solver_ mutable private
Definition at line 108 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
tags_
template<class Scalar , class ArrayScalar > TAGS Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::tags_ mutable private
Definition at line 110 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
V_
template<class Scalar , class ArrayScalar > SerialDenseMatrix Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::V_ mutable private
Contains the values of the Legendre polynomials and their derivatives.
Definition at line 106 of file Intrepid_HGRAD_LINE_Hermite_FEM.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_LINE_Hermite_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_LINE_Hermite_FEMDef.hpp