Intrepid: Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar > Class Template Reference
Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar > Class Template Reference
Implementation of the default H(grad)-compatible FEM basis of degree 2 on Hexahedron cell.
#include <Intrepid_HGRAD_HEX_Cn_FEM.hpp>
Public Member Functions
virtual ~Basis_HGRAD_HEX_Cn_FEM ()
Destructor.
Basis_HGRAD_HEX_Cn_FEM (const int orderx, const int ordery, const int orderz, const ArrayScalar &pts_x, const ArrayScalar &pts_y, const ArrayScalar &pts_z)
Constructor.
Basis_HGRAD_HEX_Cn_FEM (const int order, const EPointType &pointType)
streamlined constructor giving two choices: equispaced lattice points or spectral (i.e. Lobatto)
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType) const
Evaluation of a FEM basis on a reference Hexahedron cell.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const ArrayScalar &cellVertices, const EOperator operatorType=OPERATOR_VALUE) const
FVD basis evaluation: invocation of this method throws an exception.
virtual void getDofCoords (ArrayScalar &DofCoords) const
implement the DofCoordsInterface interface
Public Member Functions inherited from Intrepid::TensorBasis< Scalar, ArrayScalar >
Array< Array< RCP< Basis< Scalar, ArrayScalar > > > > & getBases ()
virtual ~TensorBasis ()
Destructor.
Public Member Functions inherited from Intrepid::Basis< Scalar, ArrayScalar >
virtual ~Basis ()
Destructor.
virtual int getCardinality () const
Returns cardinality of the basis.
virtual int getDegree () const
Returns the degree of the basis.
virtual const shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
virtual EBasis getBasisType () const
Returns the basis type.
virtual ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
virtual int getDofOrdinal (const int subcDim, const int subcOrd, const int subcDofOrd)
DoF tag to ordinal lookup.
virtual const std::vector< std::vector< std::vector< int > > > & getDofOrdinalData ()
DoF tag to ordinal data structure.
virtual const std::vector< int > & getDofTag (const int dofOrd)
DoF ordinal to DoF tag lookup.
virtual const std::vector< std::vector< int > > & getAllDofTags ()
Retrieves all DoF tags.
Public Member Functions inherited from Intrepid::DofCoordsInterface< ArrayScalar >
virtual ~DofCoordsInterface ()=0
Pure virtual destructor (gives warnings if not included). Following "Effective C++: 3rd Ed." item 7 the implementation is included in the definition file.
Private Member Functions
void initializeTags ()
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Private Attributes
FieldContainer< double > ptsx_
FieldContainer< double > ptsy_
FieldContainer< double > ptsz_
Additional Inherited Members
Protected Member Functions inherited from Intrepid::TensorBasis< Scalar, ArrayScalar >
void setBases (Array< Array< RCP< Basis< Scalar, ArrayScalar > > > > &bases)
Protected Attributes inherited from Intrepid::TensorBasis< Scalar, ArrayScalar >
Array< Array< RCP< Basis< Scalar, ArrayScalar > > > > bases_
Protected Attributes inherited from Intrepid::Basis< Scalar, ArrayScalar >
int basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
int basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
shards::CellTopology basisCellTopology_
Base topology of the cells for which the basis is defined. See the Shards package http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
bool basisTagsAreSet_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
std::vector< std::vector< int > > ordinalToTag_
DoF ordinal to tag lookup table.
std::vector< std::vector< std::vector< int > > > tagToOrdinal_
DoF tag to ordinal lookup table.
Detailed Description
template<class Scalar, class ArrayScalar>
class Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >
Implementation of the default H(grad)-compatible FEM basis of degree 2 on Hexahedron cell.
    Implements Lagrangian basis of degree n on the reference Hexahedron cell. The basis has
    cardinality (n+1)^3 and spans a COMPLETE polynomial space. Basis functions are dual
    to a unisolvent set of degrees-of-freedom (DoF) defined lexicographically on an
    array of input points.
Definition at line 72 of file Intrepid_HGRAD_HEX_Cn_FEM.hpp.
Constructor & Destructor Documentation
~Basis_HGRAD_HEX_Cn_FEM()
template<class Scalar , class ArrayScalar > virtual Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::~Basis_HGRAD_HEX_Cn_FEM () inline virtual
Destructor.
Definition at line 89 of file Intrepid_HGRAD_HEX_Cn_FEM.hpp.
Basis_HGRAD_HEX_Cn_FEM() [1/2]
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::Basis_HGRAD_HEX_Cn_FEM (const int orderx, const int ordery, const int orderz, const ArrayScalar & pts_x, const ArrayScalar & pts_y, const ArrayScalar & pts_z)
Constructor.
Definition at line 53 of file Intrepid_HGRAD_HEX_Cn_FEMDef.hpp.
References Intrepid::Basis< Scalar, ArrayScalar >::basisCardinality_, Intrepid::Basis< Scalar, ArrayScalar >::basisCellTopology_, Intrepid::Basis< Scalar, ArrayScalar >::basisCoordinates_, Intrepid::Basis< Scalar, ArrayScalar >::basisDegree_, Intrepid::Basis< Scalar, ArrayScalar >::basisTagsAreSet_, and Intrepid::Basis< Scalar, ArrayScalar >::basisType_.
Basis_HGRAD_HEX_Cn_FEM() [2/2]
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::Basis_HGRAD_HEX_Cn_FEM (const int order, const EPointType & pointType)
streamlined constructor giving two choices: equispaced lattice points or spectral (i.e. Lobatto)
Definition at line 102 of file Intrepid_HGRAD_HEX_Cn_FEMDef.hpp.
References Intrepid::Basis< Scalar, ArrayScalar >::basisCardinality_, Intrepid::Basis< Scalar, ArrayScalar >::basisCellTopology_, Intrepid::Basis< Scalar, ArrayScalar >::basisCoordinates_, Intrepid::Basis< Scalar, ArrayScalar >::basisDegree_, Intrepid::Basis< Scalar, ArrayScalar >::basisTagsAreSet_, and Intrepid::Basis< Scalar, ArrayScalar >::basisType_.
Member Function Documentation
getDofCoords()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::getDofCoords (ArrayScalar & DofCoords) const virtual
implement the DofCoordsInterface interface
Implements Intrepid::DofCoordsInterface< ArrayScalar >.
Definition at line 412 of file Intrepid_HGRAD_HEX_Cn_FEMDef.hpp.
getValues() [1/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const ArrayScalar & cellVertices, const EOperator operatorType = OPERATOR_VALUE) const virtual
FVD basis evaluation: invocation of this method throws an exception.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 403 of file Intrepid_HGRAD_HEX_Cn_FEMDef.hpp.
getValues() [2/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType) const virtual
Evaluation of a FEM basis on a reference Hexahedron cell.
    Returns values of <var>operatorType</var> acting on FEM basis functions for a set of
    points in the <strong>reference Hexahedron</strong> cell. For rank and dimensions of
    I/O array arguments see Section \ref basis_md_array_sec.
Parameters
outputValues [out] - rank-2 or 3 array with the computed basis values
inputPoints [in] - rank-2 array with dimensions (P,D) containing reference points
operatorType [in] - operator applied to basis functions
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 248 of file Intrepid_HGRAD_HEX_Cn_FEMDef.hpp.
References Intrepid::FieldContainer< Scalar, ArrayTypeId >::dimension(), Intrepid::Basis< Scalar, ArrayScalar >::getCardinality(), Intrepid::getDkCardinality(), Intrepid::getDkMultiplicities(), Intrepid::Basis< Scalar, ArrayScalar >::getValues(), and Intrepid::FieldContainer< Scalar, ArrayTypeId >::resize().
initializeTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::initializeTags () private virtual
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 141 of file Intrepid_HGRAD_HEX_Cn_FEMDef.hpp.
References Intrepid::Basis< Scalar, ArrayScalar >::getAllDofTags(), Intrepid::Basis< Scalar, ArrayScalar >::getCardinality(), Intrepid::ProductTopology::lineProduct3d(), and Intrepid::setOrdinalTagData().
Member Data Documentation
ptsx_
template<class Scalar , class ArrayScalar > FieldContainer<double> Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::ptsx_ private
Definition at line 77 of file Intrepid_HGRAD_HEX_Cn_FEM.hpp.
ptsy_
template<class Scalar , class ArrayScalar > FieldContainer<double> Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::ptsy_ private
Definition at line 78 of file Intrepid_HGRAD_HEX_Cn_FEM.hpp.
ptsz_
template<class Scalar , class ArrayScalar > FieldContainer<double> Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::ptsz_ private
Definition at line 79 of file Intrepid_HGRAD_HEX_Cn_FEM.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_HEX_Cn_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_HEX_Cn_FEMDef.hpp