Intrepid: Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight > Class Template Reference
Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight > Class Template Reference
Defines tensor-product cubature (integration) rules in Intrepid.
#include <Intrepid_CubatureTensorPyr.hpp>
Public Member Functions
CubatureTensorPyr (std::vector< Teuchos::RCP< Cubature< Scalar, ArrayPoint, ArrayWeight > > > cubatures)
Constructor.
CubatureTensorPyr (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature1, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature2)
Constructor.
CubatureTensorPyr (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature1, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature2, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature3)
Constructor.
CubatureTensorPyr (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature, int n)
Constructor.
void getCubature (ArrayPoint &cubPoints, ArrayWeight &cubWeights) const
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
void getCubature (ArrayPoint &cubPoints, ArrayWeight &cubWeights, ArrayPoint &cellCoords) const
Returns cubature points and weights. Method for physical space cubature, throws an exception.
virtual int getNumPoints () const
Returns the number of cubature points.
virtual int getDimension () const
Returns dimension of integration domain.
virtual void getAccuracy (std::vector< int > &degree) const
Returns max. degree of polynomials that are integrated exactly. The return vector has the size of the degree_ vector.
Public Member Functions inherited from Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >
CubatureTensor (std::vector< Teuchos::RCP< Cubature< Scalar, ArrayPoint, ArrayWeight > > > cubatures)
Constructor.
CubatureTensor (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature1, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature2)
Constructor.
CubatureTensor (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature1, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature2, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature3)
Constructor.
CubatureTensor (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature, int n)
Constructor.
Detailed Description
template<class Scalar, class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint>
class Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >
Defines tensor-product cubature (integration) rules in Intrepid.
Definition at line 60 of file Intrepid_CubatureTensorPyr.hpp.
Constructor & Destructor Documentation
~CubatureTensorPyr()
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> virtual Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::~CubatureTensorPyr () inline virtual
Definition at line 64 of file Intrepid_CubatureTensorPyr.hpp.
CubatureTensorPyr() [1/4]
template<class Scalar , class ArrayPoint , class ArrayWeight > Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::CubatureTensorPyr (std::vector< Teuchos::RCP< Cubature< Scalar, ArrayPoint, ArrayWeight > > > cubatures)
Constructor.
Parameters
cubatures [in] - Array of cubatures that represent the building blocks of the tensor product.
Definition at line 52 of file Intrepid_CubatureTensorPyrDef.hpp.
CubatureTensorPyr() [2/4]
template<class Scalar , class ArrayPoint , class ArrayWeight > Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::CubatureTensorPyr (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature1, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature2)
Constructor.
Parameters
cubature1 [in] - First direct cubature rule.
cubature2 [in] - Second direct cubature rule.
Definition at line 57 of file Intrepid_CubatureTensorPyrDef.hpp.
CubatureTensorPyr() [3/4]
template<class Scalar , class ArrayPoint , class ArrayWeight > Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::CubatureTensorPyr (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature1, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature2, Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature3)
Constructor.
Parameters
cubature1 [in] - First direct cubature rule.
cubature2 [in] - Second direct cubature rule.
cubature3 [in] - Third direct cubature rule.
Definition at line 63 of file Intrepid_CubatureTensorPyrDef.hpp.
CubatureTensorPyr() [4/4]
template<class Scalar , class ArrayPoint , class ArrayWeight > Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::CubatureTensorPyr (Teuchos::RCP< CubatureDirect< Scalar, ArrayPoint, ArrayWeight > > cubature, int n)
Constructor.
Parameters
cubature [in] - Direct cubature rule.
n [in] - Number of copies of the cubature rule in the tensor product.
Definition at line 70 of file Intrepid_CubatureTensorPyrDef.hpp.
Member Function Documentation
getAccuracy()
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::getAccuracy (std::vector< int > & degree) const virtual
Returns max. degree of polynomials that are integrated exactly. The return vector has the size of the degree_ vector.
Reimplemented from Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 114 of file Intrepid_CubatureTensorPyrDef.hpp.
References Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >::getAccuracy().
getCubature() [1/2]
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::getCubature (ArrayPoint & cubPoints, ArrayWeight & cubWeights) const virtual
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
Parameters
cubPoints [out] - Vector containing the cubature points.
cubWeights [out] - Vector of corresponding cubature weights.
Reimplemented from Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 75 of file Intrepid_CubatureTensorPyrDef.hpp.
References Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >::getCubature().
getCubature() [2/2]
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::getCubature (ArrayPoint & cubPoints, ArrayWeight & cubWeights, ArrayPoint & cellCoords) const virtual
Returns cubature points and weights. Method for physical space cubature, throws an exception.
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
cellCoords [in] - Array of cell coordinates
Reimplemented from Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 93 of file Intrepid_CubatureTensorPyrDef.hpp.
getDimension()
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::getDimension () const virtual
Returns dimension of integration domain.
Reimplemented from Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 108 of file Intrepid_CubatureTensorPyrDef.hpp.
References Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >::getDimension().
getNumPoints()
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureTensorPyr< Scalar, ArrayPoint, ArrayWeight >::getNumPoints () const virtual
Returns the number of cubature points.
Reimplemented from Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 102 of file Intrepid_CubatureTensorPyrDef.hpp.
References Intrepid::CubatureTensor< Scalar, ArrayPoint, ArrayWeight >::getNumPoints().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Integration/Intrepid_CubatureTensorPyr.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Integration/Intrepid_CubatureTensorPyrDef.hpp