Intrepid: Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar > Class Template Reference
Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar > Class Template Reference
Public Member Functions
Basis_HGRAD_POLY_C1_FEM (const shards::CellTopology &cellTopology)
Constructor.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType) const
FEM reference basis evaluation: invocation of this method throws an exception.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const ArrayScalar &cellVertices, const EOperator operatorType=OPERATOR_VALUE) const
Evaluation of a FEM basis on a physical polygon cell.
Public Member Functions inherited from Intrepid::Basis< Scalar, ArrayScalar >
virtual ~Basis ()
Destructor.
virtual int getCardinality () const
Returns cardinality of the basis.
virtual int getDegree () const
Returns the degree of the basis.
virtual const shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
virtual EBasis getBasisType () const
Returns the basis type.
virtual ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
virtual int getDofOrdinal (const int subcDim, const int subcOrd, const int subcDofOrd)
DoF tag to ordinal lookup.
virtual const std::vector< std::vector< std::vector< int > > > & getDofOrdinalData ()
DoF tag to ordinal data structure.
virtual const std::vector< int > & getDofTag (const int dofOrd)
DoF ordinal to DoF tag lookup.
virtual const std::vector< std::vector< int > > & getAllDofTags ()
Retrieves all DoF tags.
Private Member Functions
void initializeTags ()
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
template<class Scalar1 , class ArrayScalar1 >
Scalar1 computeArea (const ArrayScalar1 &p1, const ArrayScalar1 &p2, const ArrayScalar1 &p3) const
Helper function to compute area of triangle formed by 3 points.
template<class Scalar1 , class ArrayScalar1 >
void evaluateWeightFunctions (ArrayScalar1 &outputValues, const ArrayScalar1 &inputValues, const ArrayScalar1 &cellVertices) const
Evaluation of the Wachspress weight functions.
template<class Scalar1 , class ArrayScalar1 >
void shapeFunctions (ArrayScalar1 &outputValues, const ArrayScalar1 &inputValues, const ArrayScalar1 &cellVertices) const
Evaluation of Wachspress shape functions.
Additional Inherited Members
Protected Attributes inherited from Intrepid::Basis< Scalar, ArrayScalar >
int basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
int basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
shards::CellTopology basisCellTopology_
Base topology of the cells for which the basis is defined. See the Shards package http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
bool basisTagsAreSet_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
std::vector< std::vector< int > > ordinalToTag_
DoF ordinal to tag lookup table.
std::vector< std::vector< std::vector< int > > > tagToOrdinal_
DoF tag to ordinal lookup table.
Detailed Description
template<class Scalar, class ArrayScalar>
class Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >
Definition at line 49 of file Intrepid_HGRAD_POLY_C1_FEM.hpp.
Constructor & Destructor Documentation
Basis_HGRAD_POLY_C1_FEM()
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::Basis_HGRAD_POLY_C1_FEM (const shards::CellTopology & cellTopology)
Constructor.
Parameters
cellTopology [in] - the topology of the polygon
Definition at line 8 of file Intrepid_HGRAD_POLY_C1_FEMDef.hpp.
Member Function Documentation
computeArea()
template<class Scalar , class ArrayScalar > template<class Scalar1 , class ArrayScalar1 > Scalar1 Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::computeArea (const ArrayScalar1 & p1, const ArrayScalar1 & p2, const ArrayScalar1 & p3) const private
Helper function to compute area of triangle formed by 3 points.
Definition at line 152 of file Intrepid_HGRAD_POLY_C1_FEMDef.hpp.
evaluateWeightFunctions()
template<class Scalar , class ArrayScalar > template<class Scalar1 , class ArrayScalar1 > void Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::evaluateWeightFunctions (ArrayScalar1 & outputValues, const ArrayScalar1 & inputValues, const ArrayScalar1 & cellVertices) const private
Evaluation of the Wachspress weight functions.
Definition at line 164 of file Intrepid_HGRAD_POLY_C1_FEMDef.hpp.
getValues() [1/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const ArrayScalar & cellVertices, const EOperator operatorType = OPERATOR_VALUE) const virtual
Evaluation of a FEM basis on a physical polygon cell.
Parameters
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-2 array (P,D) with the evaluation points
cellVertices [in] - rank-2 array (V,D) with the vertices of the polygon
operatorType [in] - the operator acting on the basis functions
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 62 of file Intrepid_HGRAD_POLY_C1_FEMDef.hpp.
References Intrepid::isValidOperator().
getValues() [2/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType) const virtual
FEM reference basis evaluation: invocation of this method throws an exception.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 53 of file Intrepid_HGRAD_POLY_C1_FEMDef.hpp.
initializeTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::initializeTags () private virtual
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 19 of file Intrepid_HGRAD_POLY_C1_FEMDef.hpp.
References Intrepid::setOrdinalTagData().
shapeFunctions()
template<class Scalar , class ArrayScalar > template<class Scalar1 , class ArrayScalar1 > void Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::shapeFunctions (ArrayScalar1 & outputValues, const ArrayScalar1 & inputValues, const ArrayScalar1 & cellVertices) const private
Evaluation of Wachspress shape functions.
Definition at line 130 of file Intrepid_HGRAD_POLY_C1_FEMDef.hpp.
References Intrepid::FieldContainer< Scalar, ArrayTypeId >::dimension().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_POLY_C1_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_POLY_C1_FEMDef.hpp