Intrepid: Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar > Class Template Reference
Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar > Class Template Reference
Implementation of the default H(div)-compatible Raviart-Thomas basis of arbitrary degree on Triangle cell.
#include <Intrepid_HDIV_TRI_In_FEM.hpp>
Public Member Functions
Basis_HDIV_TRI_In_FEM (const int n, const EPointType pointType)
Constructor.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType) const
Evaluation of a FEM basis on a reference Triangle cell.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const ArrayScalar &cellVertices, const EOperator operatorType=OPERATOR_VALUE) const
FVD basis evaluation: invocation of this method throws an exception.
Public Member Functions inherited from Intrepid::Basis< Scalar, ArrayScalar >
virtual ~Basis ()
Destructor.
virtual int getCardinality () const
Returns cardinality of the basis.
virtual int getDegree () const
Returns the degree of the basis.
virtual const shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
virtual EBasis getBasisType () const
Returns the basis type.
virtual ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
virtual int getDofOrdinal (const int subcDim, const int subcOrd, const int subcDofOrd)
DoF tag to ordinal lookup.
virtual const std::vector< std::vector< std::vector< int > > > & getDofOrdinalData ()
DoF tag to ordinal data structure.
virtual const std::vector< int > & getDofTag (const int dofOrd)
DoF ordinal to DoF tag lookup.
virtual const std::vector< std::vector< int > > & getAllDofTags ()
Retrieves all DoF tags.
Private Member Functions
virtual void initializeTags ()
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Private Attributes
Basis_HGRAD_TRI_Cn_FEM_ORTH< Scalar, FieldContainer< Scalar > > Phis
Orthogonal basis out of which the nodal basis is constructed.
FieldContainer< Scalar > coeffs
expansion coefficients of the nodal basis in terms of the orthgonal one
Additional Inherited Members
Protected Attributes inherited from Intrepid::Basis< Scalar, ArrayScalar >
int basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
int basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
shards::CellTopology basisCellTopology_
Base topology of the cells for which the basis is defined. See the Shards package http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
bool basisTagsAreSet_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
std::vector< std::vector< int > > ordinalToTag_
DoF ordinal to tag lookup table.
std::vector< std::vector< std::vector< int > > > tagToOrdinal_
DoF tag to ordinal lookup table.
Detailed Description
template<class Scalar, class ArrayScalar>
class Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >
Implementation of the default H(div)-compatible Raviart-Thomas basis of arbitrary degree on Triangle cell.
    Implements nodal basis of degree n (n>=1) on the reference Triangle cell. The basis has
    cardinality n(n+2) and spans an INCOMPLETE polynomial
    space of degree n. Basis functions are dual to a
    unisolvent set of degrees-of-freedom (DoF) defined and
    enumerated as
    \li The normal component on a lattice of order n+1 and
    offset 1 on each edge (see PointTools). This gives one point per edge in
    the lowest-order case.  These are the first
    3 * n degrees of freedom
    \li If n > 1, the x and y components at a lattice of
    order n+1 and offset on the triangle.  These are the rest
    of the degrees of freedom.
    If the pointType argument to the constructor specifies equispaced points, then the edge points
    will be equispaced on each edge and the interior points equispaced also.  If
    the pointType argument specifies warp-blend points, then Gauss-Lobatto points of order n
    are chosen on each edge and the interior of warp-blend lattice of order n+1 is chosen for
    the interior points.
Definition at line 93 of file Intrepid_HDIV_TRI_In_FEM.hpp.
Constructor & Destructor Documentation
Basis_HDIV_TRI_In_FEM()
template<class Scalar , class ArrayScalar > Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::Basis_HDIV_TRI_In_FEM (const int n, const EPointType pointType)
Constructor.
Definition at line 53 of file Intrepid_HDIV_TRI_In_FEMDef.hpp.
References Intrepid::Basis< Scalar, ArrayScalar >::basisCardinality_, Intrepid::Basis< Scalar, ArrayScalar >::basisCellTopology_, Intrepid::Basis< Scalar, ArrayScalar >::basisCoordinates_, Intrepid::Basis< Scalar, ArrayScalar >::basisDegree_, Intrepid::Basis< Scalar, ArrayScalar >::basisTagsAreSet_, Intrepid::Basis< Scalar, ArrayScalar >::basisType_, Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::coeffs, Intrepid::Basis< Scalar, ArrayScalar >::getBaseCellTopology(), Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getCubature(), Intrepid::PointTools::getLatticeSize(), Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getNumPoints(), Intrepid::CellTools< Scalar >::mapToReferenceSubcell(), and Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::Phis.
Member Function Documentation
getValues() [1/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const ArrayScalar & cellVertices, const EOperator operatorType = OPERATOR_VALUE) const virtual
FVD basis evaluation: invocation of this method throws an exception.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 355 of file Intrepid_HDIV_TRI_In_FEMDef.hpp.
getValues() [2/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType) const virtual
Evaluation of a FEM basis on a reference Triangle cell.
    Returns values of <var>operatorType</var> acting on FEM basis functions for a set of
    points in the <strong>reference Triangle</strong> cell. For rank and dimensions of
    I/O array arguments see Section \ref basis_md_array_sec .
Parameters
outputValues [out] - variable rank array with the basis values
inputPoints [in] - rank-2 array (P,D) with the evaluation points
operatorType [in] - the operator acting on the basis functions
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 285 of file Intrepid_HDIV_TRI_In_FEMDef.hpp.
Referenced by main().
initializeTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::initializeTags () private virtual
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 235 of file Intrepid_HDIV_TRI_In_FEMDef.hpp.
References Intrepid::setOrdinalTagData().
Member Data Documentation
coeffs
template<class Scalar , class ArrayScalar > FieldContainer<Scalar> Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::coeffs private
expansion coefficients of the nodal basis in terms of the orthgonal one
Definition at line 105 of file Intrepid_HDIV_TRI_In_FEM.hpp.
Referenced by Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::Basis_HDIV_TRI_In_FEM().
Phis
template<class Scalar , class ArrayScalar > Basis_HGRAD_TRI_Cn_FEM_ORTH<Scalar,FieldContainer<Scalar> > Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::Phis private
Orthogonal basis out of which the nodal basis is constructed.
Definition at line 102 of file Intrepid_HDIV_TRI_In_FEM.hpp.
Referenced by Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::Basis_HDIV_TRI_In_FEM().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HDIV_TRI_In_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HDIV_TRI_In_FEMDef.hpp