Intrepid: ASGdata< Scalar, UserVector > Class Template Reference
ASGdata< Scalar, UserVector > Class Template Reference
Public Member Functions
ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized)
void eval_integrand (UserVector &output, std::vector< Scalar > &input)
Evaluate the integrand function.
Scalar error_indicator (UserVector &input)
User defined error indicator function.
ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized)
void eval_integrand (UserVector &output, std::vector< Scalar > &input)
Evaluate the integrand function.
Scalar error_indicator (UserVector &input)
User defined error indicator function.
ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized)
void eval_integrand (UserVector &output, std::vector< Scalar > &input)
Evaluate the integrand function.
Scalar error_indicator (UserVector &input)
User defined error indicator function.
ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized)
void eval_integrand (UserVector &output, std::vector< Scalar > &input)
Evaluate the integrand function.
Scalar error_indicator (UserVector &input)
User defined error indicator function.
ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized)
void eval_integrand (UserVector &output, std::vector< Scalar > &input)
Evaluate the integrand function.
Scalar error_indicator (UserVector &input)
User defined error indicator function.
ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized)
void eval_integrand (UserVector &output, std::vector< Scalar > &input)
Evaluate the integrand function.
Scalar error_indicator (UserVector &input)
User defined error indicator function.
Public Member Functions inherited from Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >
virtual ~AdaptiveSparseGridInterface ()
Destructor.
AdaptiveSparseGridInterface (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized)
Constructor starts with index [1,...,1].
virtual void eval_cubature (UserVector &output, CubatureTensorSorted< Scalar > &cubRule)
Evaluate the cubature rule.
virtual bool max_level (std::vector< int > index)
User defined test for maximum level of cubature.
void init (UserVector &output)
Compute initial quantities for sparse grid adaptation.
void getRule (std::vector< EIntrepidBurkardt > &rule1D)
Return user defined 1D quadrature rules.
void getGrowth (std::vector< EIntrepidGrowth > &growth1D)
Return user defined 1D growth rules.
int getDimension ()
Return dimension of integration domain.
Scalar getInitialDiff ()
Return initial error indicator.
bool isNormalized ()
Return whether or not cubature weights are normalized.
Additional Inherited Members
Protected Attributes inherited from Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >
int dimension_
The dimension of the integration domain.
int maxLevel_
The maximum allowable level of quadrature.
Scalar initialDiff_
The initial contribution to the integral.
bool isNormalized_
Whether or not to normalize the weights.
std::vector< EIntrepidBurkardt > rule1D_
The user defined 1D cubature rules.
std::vector< EIntrepidGrowth > growth1D_
The user defined 1D growth rules.
Detailed Description
template<class Scalar, class UserVector>
class ASGdata< Scalar, UserVector >
Definition at line 113 of file test_17.cpp.
Constructor & Destructor Documentation
~ASGdata() [1/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::~ASGdata () inline
Definition at line 116 of file test_17.cpp.
ASGdata() [1/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized) inline
Definition at line 118 of file test_17.cpp.
~ASGdata() [2/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::~ASGdata () inline
Definition at line 117 of file test_18.cpp.
ASGdata() [2/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized) inline
Definition at line 119 of file test_18.cpp.
~ASGdata() [3/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::~ASGdata () inline
Definition at line 116 of file test_19.cpp.
ASGdata() [3/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized) inline
Definition at line 118 of file test_19.cpp.
~ASGdata() [4/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::~ASGdata () inline
Definition at line 115 of file test_20.cpp.
ASGdata() [4/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized) inline
Definition at line 117 of file test_20.cpp.
~ASGdata() [5/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::~ASGdata () inline
Definition at line 115 of file test_21.cpp.
ASGdata() [5/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized) inline
Definition at line 117 of file test_21.cpp.
~ASGdata() [6/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::~ASGdata () inline
Definition at line 116 of file test_23.cpp.
ASGdata() [6/6]
template<class Scalar , class UserVector > ASGdata< Scalar, UserVector >::ASGdata (int dimension, std::vector< EIntrepidBurkardt > rule1D, std::vector< EIntrepidGrowth > growth1D, int maxLevel, bool isNormalized) inline
Definition at line 118 of file test_23.cpp.
Member Function Documentation
error_indicator() [1/6]
template<class Scalar , class UserVector > Scalar ASGdata< Scalar, UserVector >::error_indicator (UserVector & input) inline virtual
User defined error indicator function.
Parameters
input [in] - Reduction of high dimensional integral value to a Scalar.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 155 of file test_17.cpp.
References Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >::getInitialDiff().
error_indicator() [2/6]
template<class Scalar , class UserVector > Scalar ASGdata< Scalar, UserVector >::error_indicator (UserVector & input) inline virtual
User defined error indicator function.
Parameters
input [in] - Reduction of high dimensional integral value to a Scalar.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 136 of file test_18.cpp.
References Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >::getInitialDiff().
error_indicator() [3/6]
template<class Scalar , class UserVector > Scalar ASGdata< Scalar, UserVector >::error_indicator (UserVector & input) inline virtual
User defined error indicator function.
Parameters
input [in] - Reduction of high dimensional integral value to a Scalar.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 134 of file test_19.cpp.
References Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >::getInitialDiff().
error_indicator() [4/6]
template<class Scalar , class UserVector > Scalar ASGdata< Scalar, UserVector >::error_indicator (UserVector & input) inline virtual
User defined error indicator function.
Parameters
input [in] - Reduction of high dimensional integral value to a Scalar.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 126 of file test_20.cpp.
References Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >::getInitialDiff().
error_indicator() [5/6]
template<class Scalar , class UserVector > Scalar ASGdata< Scalar, UserVector >::error_indicator (UserVector & input) inline virtual
User defined error indicator function.
Parameters
input [in] - Reduction of high dimensional integral value to a Scalar.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 126 of file test_21.cpp.
References Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >::getInitialDiff().
error_indicator() [6/6]
template<class Scalar , class UserVector > Scalar ASGdata< Scalar, UserVector >::error_indicator (UserVector & input) inline virtual
User defined error indicator function.
Parameters
input [in] - Reduction of high dimensional integral value to a Scalar.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 126 of file test_23.cpp.
References Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >::getInitialDiff().
eval_integrand() [1/6]
template<class Scalar , class UserVector > void ASGdata< Scalar, UserVector >::eval_integrand (UserVector & output, std::vector< Scalar > & input) inline virtual
Evaluate the integrand function.
Parameters
output [out] - Output of integrand evaluation.
input [in] - Evaluation points.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 123 of file test_17.cpp.
eval_integrand() [2/6]
template<class Scalar , class UserVector > void ASGdata< Scalar, UserVector >::eval_integrand (UserVector & output, std::vector< Scalar > & input) inline virtual
Evaluate the integrand function.
Parameters
output [out] - Output of integrand evaluation.
input [in] - Evaluation points.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 124 of file test_18.cpp.
eval_integrand() [3/6]
template<class Scalar , class UserVector > void ASGdata< Scalar, UserVector >::eval_integrand (UserVector & output, std::vector< Scalar > & input) inline virtual
Evaluate the integrand function.
Parameters
output [out] - Output of integrand evaluation.
input [in] - Evaluation points.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 123 of file test_19.cpp.
eval_integrand() [4/6]
template<class Scalar , class UserVector > void ASGdata< Scalar, UserVector >::eval_integrand (UserVector & output, std::vector< Scalar > & input) inline virtual
Evaluate the integrand function.
Parameters
output [out] - Output of integrand evaluation.
input [in] - Evaluation points.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 122 of file test_20.cpp.
eval_integrand() [5/6]
template<class Scalar , class UserVector > void ASGdata< Scalar, UserVector >::eval_integrand (UserVector & output, std::vector< Scalar > & input) inline virtual
Evaluate the integrand function.
Parameters
output [out] - Output of integrand evaluation.
input [in] - Evaluation points.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 122 of file test_21.cpp.
eval_integrand() [6/6]
template<class Scalar , class UserVector > void ASGdata< Scalar, UserVector >::eval_integrand (UserVector & output, std::vector< Scalar > & input) inline virtual
Evaluate the integrand function.
Parameters
output [out] - Output of integrand evaluation.
input [in] - Evaluation points.
Implements Intrepid::AdaptiveSparseGridInterface< Scalar, UserVector >.
Definition at line 123 of file test_23.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Integration/test_17.cpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Integration/test_18.cpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Integration/test_19.cpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Integration/test_20.cpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Integration/test_21.cpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Integration/test_23.cpp