Intrepid: Intrepid::ProductTopology Class Reference
Intrepid::ProductTopology Class Reference
Utility class that provides methods for calculating distributions of points on different cells.
#include <Intrepid_ProductTopology.hpp>
Static Public Member Functions
static void lineProduct2d (const int dim0, const int entity0, const int dim1, const int entity1, int &resultdim, int &resultentity)
static void lineProduct3d (const int dim0, const int entity0, const int dim1, const int entity1, const int dim2, const int entity2, int &resultdim, int &resultentity)
Detailed Description
Utility class that provides methods for calculating distributions of points on different cells.
Definition at line 65 of file Intrepid_ProductTopology.hpp.
Member Function Documentation
lineProduct2d()
void Intrepid::ProductTopology::lineProduct2d (const int dim0, const int entity0, const int dim1, const int entity1, int & resultdim, int & resultentity) inline static
Parameters
dim0 [in] - dimension of first term in cartesian product
entity0 [in] - entity id of first term in cartesian product
dim1 [in] - dimension of second term in cartesian product
entity1 [in] - entity id of second term in cartesian product
resultdim [out] - dimension of resulting entity
resultentity [out] - id of resulting entity
Definition at line 75 of file Intrepid_ProductTopology.hpp.
Referenced by Intrepid::Basis_HCURL_QUAD_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_QUAD_In_FEM< Scalar, ArrayScalar >::initializeTags(), and Intrepid::Basis_HGRAD_QUAD_Cn_FEM< Scalar, ArrayScalar >::initializeTags().
lineProduct3d()
void Intrepid::ProductTopology::lineProduct3d (const int dim0, const int entity0, const int dim1, const int entity1, const int dim2, const int entity2, int & resultdim, int & resultentity) inline static
Parameters
dim0 [in] - dimension of first term in cartesian product
entity0 [in] - entity id of first term in cartesian product
dim1 [in] - dimension of second term in cartesian product
entity1 [in] - entity id of second term in cartesian product
dim2 [in] - dimension of third term in cartesian product
entity2 [in] - entity id of third term in cartesian product
resultdim [out] - dimension of resulting entity
resultentity [out] - id of resulting entity
Definition at line 173 of file Intrepid_ProductTopology.hpp.
Referenced by Intrepid::Basis_HCURL_HEX_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_HEX_In_FEM< Scalar, ArrayScalar >::initializeTags(), and Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::initializeTags().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_ProductTopology.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_ProductTopologyDef.hpp