Intrepid: Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar > Class Template Reference
Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar > Class Template Reference
Implementation of the default H(grad)-compatible FEM basis of degree 2 on Hexahedron cell.
#include <Intrepid_HGRAD_HEX_C2_FEM.hpp>
Public Member Functions
Basis_HGRAD_HEX_C2_FEM ()
Constructor.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType) const
Evaluation of a FEM basis on a reference Hexahedron cell.
void getValues (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const ArrayScalar &cellVertices, const EOperator operatorType=OPERATOR_VALUE) const
FVD basis evaluation: invocation of this method throws an exception.
void getDofCoords (ArrayScalar &DofCoords) const
Returns spatial locations (coordinates) of degrees of freedom on a reference Quadrilateral.
Public Member Functions inherited from Intrepid::Basis< Scalar, ArrayScalar >
virtual ~Basis ()
Destructor.
virtual int getCardinality () const
Returns cardinality of the basis.
virtual int getDegree () const
Returns the degree of the basis.
virtual const shards::CellTopology getBaseCellTopology () const
Returns the base cell topology for which the basis is defined. See Shards documentation http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
virtual EBasis getBasisType () const
Returns the basis type.
virtual ECoordinates getCoordinateSystem () const
Returns the type of coordinate system for which the basis is defined.
virtual int getDofOrdinal (const int subcDim, const int subcOrd, const int subcDofOrd)
DoF tag to ordinal lookup.
virtual const std::vector< std::vector< std::vector< int > > > & getDofOrdinalData ()
DoF tag to ordinal data structure.
virtual const std::vector< int > & getDofTag (const int dofOrd)
DoF ordinal to DoF tag lookup.
virtual const std::vector< std::vector< int > > & getAllDofTags ()
Retrieves all DoF tags.
Public Member Functions inherited from Intrepid::DofCoordsInterface< ArrayScalar >
virtual ~DofCoordsInterface ()=0
Pure virtual destructor (gives warnings if not included). Following "Effective C++: 3rd Ed." item 7 the implementation is included in the definition file.
Private Member Functions
void initializeTags ()
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Additional Inherited Members
Protected Attributes inherited from Intrepid::Basis< Scalar, ArrayScalar >
int basisCardinality_
Cardinality of the basis, i.e., the number of basis functions/degrees-of-freedom.
int basisDegree_
Degree of the largest complete polynomial space that can be represented by the basis.
shards::CellTopology basisCellTopology_
Base topology of the cells for which the basis is defined. See the Shards package http://trilinos.sandia.gov/packages/shards for definition of base cell topology.
EBasis basisType_
Type of the basis.
ECoordinates basisCoordinates_
The coordinate system for which the basis is defined.
bool basisTagsAreSet_
"true" if tagToOrdinal_ and ordinalToTag_ have been initialized
std::vector< std::vector< int > > ordinalToTag_
DoF ordinal to tag lookup table.
std::vector< std::vector< std::vector< int > > > tagToOrdinal_
DoF tag to ordinal lookup table.
Detailed Description
template<class Scalar, class ArrayScalar>
class Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >
Implementation of the default H(grad)-compatible FEM basis of degree 2 on Hexahedron cell.
    Implements Lagrangian basis of degree 2 on the reference Hexahedron cell. The basis has
    cardinality 27 and spans a COMPLETE tri-quadratic polynomial space. Basis functions are dual
    to a unisolvent set of degrees-of-freedom (DoF) defined and enumerated as follows:
=================================================================================================
|         |           degree-of-freedom-tag table                    |                           |
|   DoF   |----------------------------------------------------------|      DoF definition       |
| ordinal |  subc dim    | subc ordinal | subc DoF ord |subc num DoF |                           |
|=========|==============|==============|==============|=============|===========================|
|    0    |       0      |       0      |       0      |      1      |   L_0(u) = u(-1,-1,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    1    |       0      |       1      |       0      |      1      |   L_1(u) = u(1,-1,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    2    |       0      |       2      |       0      |      1      |   L_2(u) = u(1, 1,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    3    |       0      |       3      |       0      |      1      |   L_3(u) = u(-1, 1,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    4    |       0      |       4      |       0      |      1      |   L_4(u) = u(-1,-1, 1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    5    |       0      |       5      |       0      |      1      |   L_5(u) = u(1,-1, 1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    6    |       0      |       6      |       0      |      1      |   L_6(u) = u(1, 1, 1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    7    |       0      |       7      |       0      |      1      |   L_7(u) = u(-1, 1, 1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    8    |       1      |       0      |       0      |      1      |   L_8(u) = u(0,-1,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|    9    |       1      |       1      |       0      |      1      |   L_9(u) = u(1, 0,-1)    |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   10    |       1      |       2      |       0      |      1      |   L_10(u) = u(0, 1,-1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   11    |       1      |       3      |       0      |      1      |   L_11(u) = u(-1, 0,-1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   12    |       1      |       8      |       0      |      1      |   L_12(u) = u(-1,-1, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   13    |       1      |       9      |       0      |      1      |   L_13(u) = u(1,-1, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   14    |       1      |      10      |       0      |      1      |   L_14(u) = u(1, 1, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   15    |       1      |      11      |       0      |      1      |   L_15(u) = u(-1, 1, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   16    |       1      |       4      |       0      |      1      |   L_16(u) = u(0,-1, 1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   17    |       1      |       5      |       0      |      1      |   L_17(u) = u(1, 0, 1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   18    |       1      |       6      |       0      |      1      |   L_18(u) = u(0, 1, 1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   19    |       1      |       7      |       0      |      1      |   L_19(u) = u(-1, 0, 1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   20    |       3      |       0      |       0      |      1      |   L_20(u) = u(0, 0, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   21    |       2      |       4      |       0      |      1      |   L_21(u) = u(0, 0,-1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   22    |       2      |       5      |       0      |      1      |   L_22(u) = u(0, 0, 1)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   23    |       2      |       3      |       0      |      1      |   L_23(u) = u(-1, 0, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   24    |       2      |       1      |       0      |      1      |   L_24(u) = u(1, 0, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   25    |       2      |       0      |       0      |      1      |   L_25(u) = u(0,-1, 0)   |
|---------|--------------|--------------|--------------|-------------|---------------------------|
|   26    |       2      |       2      |       0      |      1      |   L_26(u) = u(0, 1, 0)   |
|=========|==============|==============|==============|=============|===========================|
|   MAX   |  maxScDim=2  |  maxScOrd=12 |  maxDfOrd=0  |      -      |                           |
|=========|==============|==============|==============|=============|===========================|
Remarks
Ordering of DoFs follows the node order in Hexahedron<27> topology. Note that node order in this topology does not follow the natural oder of k-subcells where the nodes are located, except for nodes 0 to 7 which coincide with the vertices of the base Hexahedrn <8> topology. As a result, L_0 to L_7 are associated with nodes 0 to 7, but L_8 to L_19 are not associated with edges 0 to 12 in that order.
Definition at line 138 of file Intrepid_HGRAD_HEX_C2_FEM.hpp.
Constructor & Destructor Documentation
Basis_HGRAD_HEX_C2_FEM()
template<class Scalar , class ArrayScalar > Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >::Basis_HGRAD_HEX_C2_FEM ()
Constructor.
Definition at line 55 of file Intrepid_HGRAD_HEX_C2_FEMDef.hpp.
Member Function Documentation
getDofCoords()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >::getDofCoords (ArrayScalar & DofCoords) const virtual
Returns spatial locations (coordinates) of degrees of freedom on a reference Quadrilateral.
Parameters
DofCoords [out] - array with the coordinates of degrees of freedom, dimensioned (F,D)
Implements Intrepid::DofCoordsInterface< ArrayScalar >.
Definition at line 1063 of file Intrepid_HGRAD_HEX_C2_FEMDef.hpp.
getValues() [1/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const ArrayScalar & cellVertices, const EOperator operatorType = OPERATOR_VALUE) const virtual
FVD basis evaluation: invocation of this method throws an exception.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 1054 of file Intrepid_HGRAD_HEX_C2_FEMDef.hpp.
getValues() [2/2]
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >::getValues (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType) const virtual
Evaluation of a FEM basis on a reference Hexahedron cell.
    Returns values of <var>operatorType</var> acting on FEM basis functions for a set of
    points in the <strong>reference Hexahedron</strong> cell. For rank and dimensions of
    I/O array arguments see Section \ref basis_md_array_sec.
Parameters
outputValues [out] - rank-2 or 3 array with the computed basis values
inputPoints [in] - rank-2 array with dimensions (P,D) containing reference points
operatorType [in] - operator applied to basis functions
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 120 of file Intrepid_HGRAD_HEX_C2_FEMDef.hpp.
References Intrepid::getDkCardinality(), and Intrepid::isValidOperator().
initializeTags()
template<class Scalar , class ArrayScalar > void Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >::initializeTags () private virtual
Initializes tagToOrdinal_ and ordinalToTag_ lookup arrays.
Implements Intrepid::Basis< Scalar, ArrayScalar >.
Definition at line 68 of file Intrepid_HGRAD_HEX_C2_FEMDef.hpp.
References Intrepid::setOrdinalTagData().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_HEX_C2_FEM.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_HEX_C2_FEMDef.hpp