Intrepid: Intrepid::OrthogonalBases Class Reference
Intrepid::OrthogonalBases Class Reference
Static Public Member Functions
template<class Scalar , class ScalarArray1 , class ScalarArray2 >
static void tabulateTriangle (const ScalarArray1 &z, const int n, ScalarArray2 &poly_val)
Calculates triangular orthogonal expansions (e.g. Dubiner basis) at a range of input points.
template<class Scalar , class ScalarArray1 , class ScalarArray2 >
static void tabulateTetrahedron (const ScalarArray1 &z, const int n, ScalarArray2 &poly_val)
Calculates triangular orthogonal expansions (e.g. Dubiner basis) at a range of input points.
Static Private Member Functions
template<class Scalar >
static void jrc (const Scalar &alpha, const Scalar &beta, const int &n, Scalar &an, Scalar &bn, Scalar &cn)
computes Jacobi recurrence coefficients of order n with weights a,b so that P^{alpha,beta}_{n+1}(x) = (an x + bn) P^{alpha,beta}_n(x) - cn P^{alpha,beta}_{n-1}(x)
static int idxtri (int p, int q)
Given indices p,q, computes the linear index of the Dubiner polynomial D^{p,q}.
static int idxtet (int p, int q, int r)
Given indices p,q,r, computes the linear index of the tetrahedral polynomial D^{p,q,r}.
Detailed Description
Definition at line 80 of file Intrepid_OrthogonalBases.hpp.
Constructor & Destructor Documentation
OrthogonalBases()
Intrepid::OrthogonalBases::OrthogonalBases () inline
Definition at line 82 of file Intrepid_OrthogonalBases.hpp.
~OrthogonalBases()
Intrepid::OrthogonalBases::~OrthogonalBases () inline
Definition at line 83 of file Intrepid_OrthogonalBases.hpp.
Member Function Documentation
idxtet()
static int Intrepid::OrthogonalBases::idxtet (int p, int q, int r) inline static private
Given indices p,q,r, computes the linear index of the tetrahedral polynomial D^{p,q,r}.
Definition at line 139 of file Intrepid_OrthogonalBases.hpp.
Referenced by tabulateTetrahedron().
idxtri()
static int Intrepid::OrthogonalBases::idxtri (int p, int q) inline static private
Given indices p,q, computes the linear index of the Dubiner polynomial D^{p,q}.
Definition at line 132 of file Intrepid_OrthogonalBases.hpp.
Referenced by tabulateTriangle().
jrc()
template<class Scalar > void Intrepid::OrthogonalBases::jrc (const Scalar & alpha, const Scalar & beta, const int & n, Scalar & an, Scalar & bn, Scalar & cn) static private
computes Jacobi recurrence coefficients of order n with weights a,b so that P^{alpha,beta}_{n+1}(x) = (an x + bn) P^{alpha,beta}_n(x) - cn P^{alpha,beta}_{n-1}(x)
Definition at line 49 of file Intrepid_OrthogonalBasesDef.hpp.
Referenced by tabulateTetrahedron(), and tabulateTriangle().
tabulateTetrahedron()
template<class Scalar , class ScalarArray1 , class ScalarArray2 > void Intrepid::OrthogonalBases::tabulateTetrahedron (const ScalarArray1 & z, const int n, ScalarArray2 & poly_val) static
Calculates triangular orthogonal expansions (e.g. Dubiner basis) at a range of input points.
Parameters
np [in] - number of input points
z [in] - 2d array of points z(pt,3)
n [in] - the maximum polynomial degree tabulated
poly_val [out] - 2d array poly_val((n+1)(n+2)(n+3)/6,np)
The ScalarArray types must support (i,j) indexing and a dimension(i) operation.
Definition at line 142 of file Intrepid_OrthogonalBasesDef.hpp.
References idxtet(), and jrc().
tabulateTriangle()
template<class Scalar , class ScalarArray1 , class ScalarArray2 > void Intrepid::OrthogonalBases::tabulateTriangle (const ScalarArray1 & z, const int n, ScalarArray2 & poly_val) static
Calculates triangular orthogonal expansions (e.g. Dubiner basis) at a range of input points.
Parameters
np [in] - number of input points
z [in] - 2d array of points z(pt,2)
n [in] - the maximum polynomial degree tabulated
poly_val [out] - 2d array poly_val((n+1)(n+2)/2,np)
The ScalarArray types must support (i,j) indexing and a dimension(i) operation.
Definition at line 65 of file Intrepid_OrthogonalBasesDef.hpp.
References idxtri(), and jrc().
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_OrthogonalBases.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_OrthogonalBasesDef.hpp