Intrepid: Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight > Class Template Reference
Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight > Class Template Reference
Defines cubature (integration) rules over control volumes.
#include <Intrepid_CubatureControlVolume.hpp>
Public Member Functions
CubatureControlVolume (const Teuchos::RCP< const shards::CellTopology > &cellTopology)
void getCubature (ArrayPoint &cubPoints, ArrayWeight &cubWeights) const
Returns cubature points and weights Method for reference space cubature - throws an exception.
void getCubature (ArrayPoint &cubPoints, ArrayWeight &cubWeights, ArrayPoint &cellCoords) const
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
int getNumPoints () const
Returns the number of cubature points.
int getDimension () const
Returns dimension of integration domain.
void getAccuracy (std::vector< int > &accuracy) const
Returns max. degree of polynomials that are integrated exactly. The return vector has size 1.
Private Attributes
Teuchos::RCP< const shards::CellTopology > primaryCellTopo_
The topology of the primary cell.
Teuchos::RCP< const shards::CellTopology > subCVCellTopo_
The topology of the sub-control volume.
int degree_
The degree of the polynomials that are integrated exactly.
int numPoints_
The number of cubature points.
int cubDimension_
Dimension of integration domain.
Detailed Description
template<class Scalar, class ArrayPoint, class ArrayWeight>
class Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >
Defines cubature (integration) rules over control volumes.
Each primary cell contains one sub-control volume per node and there is one integration point per sub-control volume.
Definition at line 67 of file Intrepid_CubatureControlVolume.hpp.
Constructor & Destructor Documentation
CubatureControlVolume()
template<class Scalar , class ArrayPoint , class ArrayWeight > Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::CubatureControlVolume (const Teuchos::RCP< const shards::CellTopology > & cellTopology)
brief Constructor.
Parameters
cellTopology [in] - The topology of the primary cell.
Definition at line 55 of file Intrepid_CubatureControlVolumeDef.hpp.
~CubatureControlVolume()
template<class Scalar , class ArrayPoint , class ArrayWeight > virtual Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::~CubatureControlVolume () inline virtual
Definition at line 110 of file Intrepid_CubatureControlVolume.hpp.
Member Function Documentation
getAccuracy()
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::getAccuracy (std::vector< int > & accuracy) const virtual
Returns max. degree of polynomials that are integrated exactly. The return vector has size 1.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 160 of file Intrepid_CubatureControlVolumeDef.hpp.
getCubature() [1/2]
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::getCubature (ArrayPoint & cubPoints, ArrayWeight & cubWeights) const virtual
Returns cubature points and weights Method for reference space cubature - throws an exception.
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 76 of file Intrepid_CubatureControlVolumeDef.hpp.
getCubature() [2/2]
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::getCubature (ArrayPoint & cubPoints, ArrayWeight & cubWeights, ArrayPoint & cellCoords) const virtual
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
cellCoords [in] - Array of cell coordinates
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 84 of file Intrepid_CubatureControlVolumeDef.hpp.
References Intrepid::DefaultCubatureFactory< Scalar, ArrayPoint, ArrayWeight >::create(), Intrepid::CellTools< Scalar >::getSubCVCoords(), and Intrepid::CellTools< Scalar >::setJacobianDet().
getDimension()
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::getDimension () const virtual
Returns dimension of integration domain.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 155 of file Intrepid_CubatureControlVolumeDef.hpp.
getNumPoints()
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::getNumPoints () const virtual
Returns the number of cubature points.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 150 of file Intrepid_CubatureControlVolumeDef.hpp.
Member Data Documentation
cubDimension_
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::cubDimension_ private
Dimension of integration domain.
Definition at line 133 of file Intrepid_CubatureControlVolume.hpp.
degree_
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::degree_ private
The degree of the polynomials that are integrated exactly.
Definition at line 125 of file Intrepid_CubatureControlVolume.hpp.
numPoints_
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::numPoints_ private
The number of cubature points.
Definition at line 129 of file Intrepid_CubatureControlVolume.hpp.
primaryCellTopo_
template<class Scalar , class ArrayPoint , class ArrayWeight > Teuchos::RCP<const shards::CellTopology> Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::primaryCellTopo_ private
The topology of the primary cell.
Definition at line 117 of file Intrepid_CubatureControlVolume.hpp.
subCVCellTopo_
template<class Scalar , class ArrayPoint , class ArrayWeight > Teuchos::RCP<const shards::CellTopology> Intrepid::CubatureControlVolume< Scalar, ArrayPoint, ArrayWeight >::subCVCellTopo_ private
The topology of the sub-control volume.
Definition at line 121 of file Intrepid_CubatureControlVolume.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Integration/Intrepid_CubatureControlVolume.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Integration/Intrepid_CubatureControlVolumeDef.hpp