Intrepid: Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight > Class Template Reference
Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight > Class Template Reference abstract
Defines direct cubature (integration) rules in Intrepid.
#include <Intrepid_CubatureDirect.hpp>
Public Member Functions
virtual void getCubatureData (ArrayPoint &cubPoints, ArrayWeight &cubWeights, const CubatureTemplate *cubData) const
Extracts points and weights from cubData.
virtual void getCubature (ArrayPoint &cubPoints, ArrayWeight &cubWeights) const
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
virtual void getCubature (ArrayPoint &cubPoints, ArrayWeight &cubWeights, ArrayPoint &cellCoords) const
Returns cubature points and weights. Method for physical space cubature, throws an exception.
virtual int getNumPoints () const
Returns the number of cubature points.
virtual int getDimension () const
Returns dimension of integration domain.
virtual void getAccuracy (std::vector< int > &accuracy) const
Returns max. degree of polynomials that are integrated exactly. The return vector has size 1.
virtual const char * getName () const =0
Returns cubature name.
virtual const CubatureTemplate * exposeCubatureData () const =0
Exposes cubature data.
virtual int getMaxAccuracy () const =0
Returns maximum cubature accuracy.
Protected Attributes
int degree_
The degree of polynomials that are integrated exactly by this cubature rule.
int dimension_
Dimension of integration domain.
Detailed Description
template<class Scalar, class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint>
class Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >
Defines direct cubature (integration) rules in Intrepid.
Cubature template (rule) consists of cubature points and cubature weights. Intrepid provides a small collection of frequently used cubature rule templates for FEM reconstructions on simplices (edge, tri, tet) and pyramid cells.
For quad, hex, and triprism rules, see tensor-product rules defined in the class CubatureTensor, and its derived classes.
Cubature rules for simplices and the pyramid are stored in the cubature_data_ array.
All templates are defined on a reference cell and can be mapped to physical space cells by the methods available in the MultiCell class.
Definition at line 76 of file Intrepid_CubatureDirect.hpp.
Constructor & Destructor Documentation
~CubatureDirect()
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> virtual Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::~CubatureDirect () inline virtual
Definition at line 93 of file Intrepid_CubatureDirect.hpp.
CubatureDirect()
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::CubatureDirect () inline
Definition at line 95 of file Intrepid_CubatureDirect.hpp.
Member Function Documentation
exposeCubatureData()
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> virtual const CubatureTemplate * Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::exposeCubatureData () const pure virtual
Exposes cubature data.
Implemented in Intrepid::CubatureCompositeTet< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectLineGauss< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectLineGaussJacobi20< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectTetDefault< Scalar, ArrayPoint, ArrayWeight >, and Intrepid::CubatureDirectTriDefault< Scalar, ArrayPoint, ArrayWeight >.
getAccuracy()
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getAccuracy (std::vector< int > & accuracy) const virtual
Returns max. degree of polynomials that are integrated exactly. The return vector has size 1.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 104 of file Intrepid_CubatureDirectDef.hpp.
getCubature() [1/2]
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getCubature (ArrayPoint & cubPoints, ArrayWeight & cubWeights) const virtual
Returns cubature points and weights (return arrays must be pre-sized/pre-allocated).
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 73 of file Intrepid_CubatureDirectDef.hpp.
Referenced by Intrepid::Basis_HCURL_TET_In_FEM< Scalar, ArrayScalar >::Basis_HCURL_TET_In_FEM(), Intrepid::Basis_HCURL_TRI_In_FEM< Scalar, ArrayScalar >::Basis_HCURL_TRI_In_FEM(), Intrepid::Basis_HDIV_TET_In_FEM< Scalar, ArrayScalar >::Basis_HDIV_TET_In_FEM(), Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::Basis_HDIV_TRI_In_FEM(), Intrepid::CubaturePolygon< Scalar, ArrayPoint, ArrayWeight >::CubaturePolygon(), and main().
getCubature() [2/2]
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getCubature (ArrayPoint & cubPoints, ArrayWeight & cubWeights, ArrayPoint & cellCoords) const virtual
Returns cubature points and weights. Method for physical space cubature, throws an exception.
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
cellCoords [in] - Array of cell coordinates
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 79 of file Intrepid_CubatureDirectDef.hpp.
getCubatureData()
template<class Scalar , class ArrayPoint , class ArrayWeight > void Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getCubatureData (ArrayPoint & cubPoints, ArrayWeight & cubWeights, const CubatureTemplate * cubData) const virtual
Extracts points and weights from cubData.
Parameters
cubPoints [out] - Array containing the cubature points.
cubWeights [out] - Array of corresponding cubature weights.
cubData [in] - Pointer to raw cubature data.
Definition at line 52 of file Intrepid_CubatureDirectDef.hpp.
References Intrepid::CubatureTemplate::points_, and Intrepid::CubatureTemplate::weights_.
getDimension()
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getDimension () const virtual
Returns dimension of integration domain.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 97 of file Intrepid_CubatureDirectDef.hpp.
Referenced by Intrepid::CubaturePolygon< Scalar, ArrayPoint, ArrayWeight >::CubaturePolygon().
getMaxAccuracy()
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> virtual int Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getMaxAccuracy () const pure virtual
Returns maximum cubature accuracy.
Implemented in Intrepid::CubatureCompositeTet< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectLineGauss< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectLineGaussJacobi20< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectTetDefault< Scalar, ArrayPoint, ArrayWeight >, and Intrepid::CubatureDirectTriDefault< Scalar, ArrayPoint, ArrayWeight >.
getName()
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> virtual const char * Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getName () const pure virtual
Returns cubature name.
Implemented in Intrepid::CubatureCompositeTet< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectLineGauss< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectLineGaussJacobi20< Scalar, ArrayPoint, ArrayWeight >, Intrepid::CubatureDirectTetDefault< Scalar, ArrayPoint, ArrayWeight >, and Intrepid::CubatureDirectTriDefault< Scalar, ArrayPoint, ArrayWeight >.
getNumPoints()
template<class Scalar , class ArrayPoint , class ArrayWeight > int Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getNumPoints () const virtual
Returns the number of cubature points.
Implements Intrepid::Cubature< Scalar, ArrayPoint, ArrayWeight >.
Definition at line 90 of file Intrepid_CubatureDirectDef.hpp.
Referenced by Intrepid::Basis_HCURL_TET_In_FEM< Scalar, ArrayScalar >::Basis_HCURL_TET_In_FEM(), Intrepid::Basis_HCURL_TRI_In_FEM< Scalar, ArrayScalar >::Basis_HCURL_TRI_In_FEM(), Intrepid::Basis_HDIV_TET_In_FEM< Scalar, ArrayScalar >::Basis_HDIV_TET_In_FEM(), Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::Basis_HDIV_TRI_In_FEM(), Intrepid::CubaturePolygon< Scalar, ArrayPoint, ArrayWeight >::CubaturePolygon(), and main().
Member Data Documentation
degree_
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> int Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::degree_ protected
The degree of polynomials that are integrated exactly by this cubature rule.
Definition at line 84 of file Intrepid_CubatureDirect.hpp.
dimension_
template<class Scalar , class ArrayPoint = FieldContainer<Scalar>, class ArrayWeight = ArrayPoint> int Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::dimension_ protected
Dimension of integration domain.
Definition at line 88 of file Intrepid_CubatureDirect.hpp.
The documentation for this class was generated from the following files:
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Integration/Intrepid_CubatureDirect.hpp
/home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Integration/Intrepid_CubatureDirectDef.hpp