Intrepid: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Basis/HCURL_TET_In_FEM/test_01.cpp File Reference
test_01.cpp File Reference
Unit test of Nedelec class for tetrahedra.
#include "Intrepid_FieldContainer.hpp"
#include "Teuchos_oblackholestream.hpp"
#include "Teuchos_RCP.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "Intrepid_PointTools.hpp"
#include "Intrepid_HCURL_TET_In_FEM.hpp"
#include "Shards_CellTopology.hpp"
#include <iostream>
Functions
int main (int argc, char *argv[])
Performs a code-code comparison to FIAT for Nedelec bases on tets (values and curls)
Detailed Description
Unit test of Nedelec class for tetrahedra.
Author
Created by R. Kirby
Definition in file test_01.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Performs a code-code comparison to FIAT for Nedelec bases on tets (values and curls)
Parameters
argc [in] - number of command-line arguments
argv [in] - command-line arguments
Definition at line 65 of file test_01.cpp.
References Intrepid::FieldContainer< Scalar, ArrayTypeId >::dimension(), Intrepid::Basis< Scalar, ArrayScalar >::getBaseCellTopology(), Intrepid::Basis< Scalar, ArrayScalar >::getCardinality(), Intrepid::PointTools::getLatticeSize(), and Intrepid::Basis_HCURL_TET_In_FEM< Scalar, ArrayScalar >::getValues().