Intrepid: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Basis/HGRAD_TET_Cn_FEM_ORTH/test_01.cpp File Reference
test_01.cpp File Reference
Unit test of orthogonal tetrahedral polynomial basis class.
#include "Intrepid_FieldContainer.hpp"
#include "Teuchos_oblackholestream.hpp"
#include "Teuchos_RCP.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "Intrepid_HGRAD_TET_Cn_FEM_ORTH.hpp"
#include "Intrepid_CubatureDirectTetDefault.hpp"
#include "Shards_CellTopology.hpp"
#include "Intrepid_PointTools.hpp"
#include <iostream>
Functions
int main (int argc, char *argv[])
Tests for orthogonal basis on tets. Tests diagonality of mass matrices and does a code comparison to FIAT for values of derivatives.
Detailed Description
Unit test of orthogonal tetrahedral polynomial basis class.
Author
Created by R. Kirby
Definition in file test_01.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Tests for orthogonal basis on tets. Tests diagonality of mass matrices and does a code comparison to FIAT for values of derivatives.
Parameters
argc [in] - number of command-line arguments
argv [in] - command-line arguments
Definition at line 68 of file test_01.cpp.
References Intrepid::Basis< Scalar, ArrayScalar >::getCardinality(), Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getCubature(), Intrepid::PointTools::getLatticeSize(), Intrepid::CubatureDirect< Scalar, ArrayPoint, ArrayWeight >::getNumPoints(), and Intrepid::Basis_HGRAD_TET_Cn_FEM_ORTH< Scalar, ArrayScalar >::getValues().