Intrepid: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/test/Discretization/Basis/HGRAD_TET_C2_FEM/test_02.cpp File Reference
test_02.cpp File Reference
Patch test for the Intrepid::Basis_HGRAD_TET_C2_FEM class.
#include "Intrepid_FieldContainer.hpp"
#include "Intrepid_HGRAD_TET_C2_FEM.hpp"
#include "Intrepid_DefaultCubatureFactory.hpp"
#include "Intrepid_RealSpaceTools.hpp"
#include "Intrepid_ArrayTools.hpp"
#include "Intrepid_FunctionSpaceTools.hpp"
#include "Intrepid_CellTools.hpp"
#include "Teuchos_oblackholestream.hpp"
#include "Teuchos_RCP.hpp"
#include "Teuchos_GlobalMPISession.hpp"
#include "Teuchos_SerialDenseMatrix.hpp"
#include "Teuchos_SerialDenseVector.hpp"
#include "Teuchos_LAPACK.hpp"
Functions
void rhsFunc (FieldContainer< double > &result, const FieldContainer< double > &points, int xd, int yd, int zd)
right-hand side function
void neumann (FieldContainer< double > &result, const FieldContainer< double > &points, const FieldContainer< double > &jacs, const shards::CellTopology &parentCell, int sideOrdinal, int xd, int yd, int zd)
neumann boundary conditions
void u_exact (FieldContainer< double > &result, const FieldContainer< double > &points, int xd, int yd, int zd)
exact solution
int main (int argc, char *argv[])
Detailed Description
Patch test for the Intrepid::Basis_HGRAD_TET_C2_FEM class.
Author
Created by P. Bochev, D. Ridzal, K. Peterson.
Definition in file test_02.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 192 of file test_02.cpp.
neumann()
void neumann (FieldContainer< double > & result, const FieldContainer< double > & points, const FieldContainer< double > & jacs, const shards::CellTopology & parentCell, int sideOrdinal, int xd, int yd, int zd)
neumann boundary conditions
Definition at line 124 of file test_02.cpp.
References Intrepid::FieldContainer< Scalar, ArrayTypeId >::dimension(), Intrepid::CellTools< Scalar >::getPhysicalSideNormals(), and Intrepid::RealSpaceTools< Scalar >::vectorNorm().
rhsFunc()
void rhsFunc (FieldContainer< double > & result, const FieldContainer< double > & points, int xd, int yd, int zd)
right-hand side function
Definition at line 75 of file test_02.cpp.
References Intrepid::FieldContainer< Scalar, ArrayTypeId >::dimension().
u_exact()
void u_exact (FieldContainer< double > & result, const FieldContainer< double > & points, int xd, int yd, int zd)
exact solution
Definition at line 180 of file test_02.cpp.
References Intrepid::FieldContainer< Scalar, ArrayTypeId >::dimension().