Intrepid: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_Basis.hpp File Reference
Intrepid_Basis.hpp File Reference
Header file for the abstract base class Intrepid::Basis.
#include "Intrepid_ConfigDefs.hpp"
#include "Intrepid_Types.hpp"
#include "Intrepid_Utils.hpp"
#include "Shards_CellTopology.hpp"
#include <Intrepid_BasisDef.hpp>
Classes
class Intrepid::Basis< Scalar, ArrayScalar >
An abstract base class that defines interface for concrete basis implementations for Finite Element (FEM) and Finite Volume/Finite Difference (FVD) discrete spaces.
class Intrepid::DofCoordsInterface< ArrayScalar >
This is an interface class for bases whose degrees of freedom can be associated with spatial locations in a reference element (typically interpolation points for interpolatory bases).
Functions
template<class Scalar , class ArrayScalar >
void Intrepid::getValues_HGRAD_Args (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType, const shards::CellTopology &cellTopo, const int basisCard)
Runtime check of the arguments for the getValues method in an HGRAD-conforming FEM basis. Verifies that ranks and dimensions of ArrayScalar input and output arrays are consistent with the specified operatorType.
template<class Scalar , class ArrayScalar >
void Intrepid::getValues_HCURL_Args (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType, const shards::CellTopology &cellTopo, const int basisCard)
Runtime check of the arguments for the getValues method in an HCURL-conforming FEM basis. Verifies that ranks and dimensions of ArrayScalar input and output arrays are consistent with the specified operatorType.
template<class Scalar , class ArrayScalar >
void Intrepid::getValues_HDIV_Args (ArrayScalar &outputValues, const ArrayScalar &inputPoints, const EOperator operatorType, const shards::CellTopology &cellTopo, const int basisCard)
Runtime check of the arguments for the getValues method in an HDIV-conforming FEM basis. Verifies that ranks and dimensions of ArrayScalar input and output arrays are consistent with the specified operatorType.
Detailed Description
Header file for the abstract base class Intrepid::Basis.
Author
Created by P. Bochev and D. Ridzal.
Definition in file Intrepid_Basis.hpp.
Function Documentation
getValues_HCURL_Args()
template<class Scalar , class ArrayScalar > void Intrepid::getValues_HCURL_Args (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType, const shards::CellTopology & cellTopo, const int basisCard)
Runtime check of the arguments for the getValues method in an HCURL-conforming FEM basis. Verifies that ranks and dimensions of ArrayScalar input and output arrays are consistent with the specified operatorType.
\param  outputValues     [in]  - array of variable rank for the output basis values
\param  inputPoints      [in]  - rank-2 array with dimensions (P,D) containing the points
\param  operatorType     [in]  - operator applied to basis functions
\param  cellTopo         [in]  - base cell topology on which the basis is defined
\param  basisCard        [in]  - cardinality of the basis
References Intrepid::getValues_HCURL_Args().
Referenced by Intrepid::Basis< Scalar, Intrepid::FieldContainer< Scalar > >::getDofOrdinalData(), and Intrepid::getValues_HCURL_Args().
getValues_HDIV_Args()
template<class Scalar , class ArrayScalar > void Intrepid::getValues_HDIV_Args (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType, const shards::CellTopology & cellTopo, const int basisCard)
Runtime check of the arguments for the getValues method in an HDIV-conforming FEM basis. Verifies that ranks and dimensions of ArrayScalar input and output arrays are consistent with the specified operatorType.
\param  outputValues     [in]  - array of variable rank for the output basis values
\param  inputPoints      [in]  - rank-2 array with dimensions (P,D) containing the points
\param  operatorType     [in]  - operator applied to basis functions
\param  cellTopo         [in]  - base cell topology on which the basis is defined
\param  basisCard        [in]  - cardinality of the basis
References Intrepid::getValues_HDIV_Args().
Referenced by Intrepid::getValues_HDIV_Args().
getValues_HGRAD_Args()
template<class Scalar , class ArrayScalar > void Intrepid::getValues_HGRAD_Args (ArrayScalar & outputValues, const ArrayScalar & inputPoints, const EOperator operatorType, const shards::CellTopology & cellTopo, const int basisCard)
Runtime check of the arguments for the getValues method in an HGRAD-conforming FEM basis. Verifies that ranks and dimensions of ArrayScalar input and output arrays are consistent with the specified operatorType.
\param  outputValues     [in]  - array of variable rank for the output basis values
\param  inputPoints      [in]  - rank-2 array with dimensions (P,D) containing the points
\param  operatorType     [in]  - operator applied to basis functions
\param  cellTopo         [in]  - base cell topology on which the basis is defined
\param  basisCard        [in]  - cardinality of the basis
References Intrepid::getValues_HGRAD_Args().
Referenced by Intrepid::getValues_HGRAD_Args().