Intrepid: /home/runner/work/trilinos.github.io/trilinos.github.io/Trilinos/packages/intrepid/src/Shared/Intrepid_Utils.hpp File Reference
Intrepid_Utils.hpp File Reference
Intrepid utilities.
#include "Intrepid_ConfigDefs.hpp"
#include "Intrepid_Rank.hpp"
#include "Intrepid_Types.hpp"
#include "Teuchos_Array.hpp"
#include "Teuchos_oblackholestream.hpp"
#include "Teuchos_RCP.hpp"
Enumerations
enum TypeOfExactData { INTREPID_UTILS_FRACTION =0 , INTREPID_UTILS_SCALAR }
Functions
int Intrepid::getFieldRank (const EFunctionSpace spaceType)
Returns the rank of fields in a function space of the specified type.
int Intrepid::getOperatorRank (const EFunctionSpace spaceType, const EOperator operatorType, const int spaceDim)
Returns rank of an operator.
int Intrepid::getOperatorOrder (const EOperator operatorType)
Returns order of an operator.
int Intrepid::getDkEnumeration (const int xMult, const int yMult=-1, const int zMult=-1)
Returns the ordinal of a partial derivative of order k based on the multiplicities of the partials dx, dy, and dz.
void Intrepid::getDkMultiplicities (Teuchos::Array< int > &partialMult, const int derivativeEnum, const EOperator operatorType, const int spaceDim)
Returns multiplicities of dx, dy, and dz based on the enumeration of the partial derivative, its order and the space dimension. Inverse of the getDkEnumeration() method.
int Intrepid::getDkCardinality (const EOperator operatorType, const int spaceDim)
Returns cardinality of Dk, i.e., the number of all derivatives of order k.
void Intrepid::setOrdinalTagData (std::vector< std::vector< std::vector< int > > > &tagToOrdinal, std::vector< std::vector< int > > &ordinalToTag, const int *tags, const int basisCard, const int tagSize, const int posScDim, const int posScOrd, const int posDfOrd)
Fills ordinalToTag_ and tagToOrdinal_ by basis-specific tag data.
template<class Scalar >
int Intrepid::compareToAnalytic (const Teuchos::Array< Teuchos::Array< Scalar > > testMat, std::ifstream &inputFile, Scalar reltol, int iprint, TypeOfExactData analyticDataType=INTREPID_UTILS_FRACTION)
Compares the values in the test matrix testMat to precomputed analytic values stored in a file, where the input matrix is an array of arrays.
template<class Scalar >
int Intrepid::compareToAnalytic (const Scalar *testMat, std::ifstream &inputFile, Scalar reltol, int iprint, TypeOfExactData analyticDataType=INTREPID_UTILS_FRACTION)
Compares the values in the test matrix testMat to precomputed analytic values stored in a file, where the input matrix is a single contiguous array.
template<class Scalar >
void Intrepid::getAnalytic (Teuchos::Array< Teuchos::Array< Scalar > > &testMat, std::ifstream &inputFile, TypeOfExactData analyticDataType=INTREPID_UTILS_FRACTION)
Loads analytic values stored in a file into the matrix testMat, where the output matrix is an array of arrays.
template<class Scalar >
void Intrepid::getAnalytic (Scalar *testMat, std::ifstream &inputFile, TypeOfExactData analyticDataType=INTREPID_UTILS_FRACTION)
Loads analytic values stored in a file into the matrix testMat, where the output matrix is a single contiguous array.
template<class Array >
bool Intrepid::requireRankRange (std::string &errmsg, const Array &array, const int lowerBound, const int upperBound)
Checks if the rank of the array argument is in the required range.
template<class Array1 , class Array2 >
bool Intrepid::requireRankMatch (std::string &errmsg, const Array1 &array1, const Array2 &array2)
Checks if two arrays have matching ranks.
template<class Array >
bool Intrepid::requireDimensionRange (std::string &errmsg, const Array &array, const int dim, const int lowerBound, const int upperBound)
Checks if the specified array dimension is in the required range.
template<class Array1 , class Array2 >
bool Intrepid::requireDimensionMatch (std::string &errmsg, const Array1 &array1, const int a1_dim0, const Array2 &array2, const int a2_dim0)
Checks arrays for a single matching dimension.
template<class Array1 , class Array2 >
bool Intrepid::requireDimensionMatch (std::string &errmsg, const Array1 &array1, const int a1_dim0, const int a1_dim1, const Array2 &array2, const int a2_dim0, const int a2_dim1)
Checks arrays for two matching dimensions.
template<class Array1 , class Array2 >
bool Intrepid::requireDimensionMatch (std::string &errmsg, const Array1 &array1, const int a1_dim0, const int a1_dim1, const int a1_dim2, const Array2 &array2, const int a2_dim0, const int a2_dim1, const int a2_dim2)
Checks arrays for three matching dimensions.
template<class Array1 , class Array2 >
bool Intrepid::requireDimensionMatch (std::string &errmsg, const Array1 &array1, const int a1_dim0, const int a1_dim1, const int a1_dim2, const int a1_dim3, const Array2 &array2, const int a2_dim0, const int a2_dim1, const int a2_dim2, const int a2_dim3)
Checks arrays for four matching dimensions.
template<class Array1 , class Array2 >
bool Intrepid::requireDimensionMatch (std::string &errmsg, const Array1 &array1, const int a1_dim0, const int a1_dim1, const int a1_dim2, const int a1_dim3, const int a1_dim4, const Array2 &array2, const int a2_dim0, const int a2_dim1, const int a2_dim2, const int a2_dim3, const int a2_dim4)
Checks arrays for five matching dimensions.
template<class Array1 , class Array2 >
bool Intrepid::requireDimensionMatch (std::string &errmsg, const Array1 &array1, const Array2 &array2)
Checks arrays for all their dimensions match. Arrays with equal ranks required.
Detailed Description
Intrepid utilities.
Author
Created by P. Bochev and D. Ridzal.
Definition in file Intrepid_Utils.hpp.
Enumeration Type Documentation
TypeOfExactData
enum Intrepid::TypeOfExactData
Definition at line 240 of file Intrepid_Utils.hpp.
Function Documentation
compareToAnalytic() [1/2]
template<class Scalar > int Intrepid::compareToAnalytic (const Scalar * testMat, std::ifstream & inputFile, Scalar reltol, int iprint, TypeOfExactData analyticDataType = INTREPID_UTILS_FRACTION)
Compares the values in the test matrix testMat to precomputed analytic values stored in a file, where the input matrix is a single contiguous array.
Parameters
testMat [in] - test matrix
inputFile [in] - input file
reltol [in] - relative tolerance for equality comparisons
iprint [in] - if 0, no output; if 1, details are printed
analyticDataType [in] - type of analytic data for comparison:
if INTREPID_UTILS_FRACTION, analytic fractions are parsed and computed
if INTREPID_UTILS_SCALAR, high-precision scalar data is read
Returns
0 if pass; error code otherwise
Definition at line 612 of file Intrepid_Utils.hpp.
References Intrepid::compareToAnalytic().
compareToAnalytic() [2/2]
template<class Scalar > int Intrepid::compareToAnalytic (const Teuchos::Array< Teuchos::Array< Scalar > > testMat, std::ifstream & inputFile, Scalar reltol, int iprint, TypeOfExactData analyticDataType = INTREPID_UTILS_FRACTION)
Compares the values in the test matrix testMat to precomputed analytic values stored in a file, where the input matrix is an array of arrays.
Parameters
testMat [in] - test matrix
inputFile [in] - input file
reltol [in] - relative tolerance for equality comparisons
iprint [in] - if 0, no output; if 1, details are printed
analyticDataType [in] - type of analytic data for comparison:
if INTREPID_UTILS_FRACTION, analytic fractions are parsed and computed
if INTREPID_UTILS_SCALAR, high-precision scalar data is read
Returns
0 if pass; error code otherwise
Definition at line 528 of file Intrepid_Utils.hpp.
References Intrepid::compareToAnalytic().
Referenced by Intrepid::compareToAnalytic(), and Intrepid::compareToAnalytic().
getAnalytic() [1/2]
template<class Scalar > void Intrepid::getAnalytic (Scalar * testMat, std::ifstream & inputFile, TypeOfExactData analyticDataType = INTREPID_UTILS_FRACTION)
Loads analytic values stored in a file into the matrix testMat, where the output matrix is a single contiguous array.
Parameters
testMat [in] - test matrix
inputFile [in] - input file
analyticDataType [in] - type of analytic data for comparison:
if INTREPID_UTILS_FRACTION, analytic fractions are parsed and computed
if INTREPID_UTILS_SCALAR, high-precision scalar data is read
Definition at line 749 of file Intrepid_Utils.hpp.
References Intrepid::getAnalytic().
getAnalytic() [2/2]
template<class Scalar > void Intrepid::getAnalytic (Teuchos::Array< Teuchos::Array< Scalar > > & testMat, std::ifstream & inputFile, TypeOfExactData analyticDataType = INTREPID_UTILS_FRACTION)
Loads analytic values stored in a file into the matrix testMat, where the output matrix is an array of arrays.
Parameters
testMat [in] - test matrix
inputFile [in] - input file
analyticDataType [in] - type of analytic data for comparison:
if INTREPID_UTILS_FRACTION, analytic fractions are parsed and computed
if INTREPID_UTILS_SCALAR, high-precision scalar data is read
Definition at line 697 of file Intrepid_Utils.hpp.
References Intrepid::getAnalytic().
Referenced by Intrepid::getAnalytic(), and Intrepid::getAnalytic().
getDkCardinality()
int Intrepid::getDkCardinality (const EOperator operatorType, const int spaceDim)
Returns cardinality of Dk, i.e., the number of all derivatives of order k.
The set of all partial derivatives of order k is isomorphic to the set of all multisets of cardinality k with elements taken from the sets {x}, {x,y}, and {x,y,z} in 1D, 2D, and 3D respectively. For example, the partial derivative maps to the multiset with multiplicities . The number of all such multisets is given by the binomial coefficient
Therefore:
in 1D: cardinality = 1
in 2D: cardinality = k + 1
in 3D: cardinality = (k + 1)*(k + 2)/2
Parameters
operatorType [in] - k-th derivative operator Dk
spaceDim [in] - space dimension
Returns
the number of all partial derivatives of order k
Definition at line 400 of file Intrepid_Utils.cpp.
References Intrepid::getDkCardinality(), and Intrepid::getOperatorOrder().
Referenced by Intrepid::getDkCardinality(), Intrepid::getDkMultiplicities(), Intrepid::Basis_HGRAD_HEX_C1_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_HEX_I2_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_LINE_C1_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_LINE_Cn_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_PYR_C1_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_PYR_I2_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_QUAD_C1_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_QUAD_C2_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_QUAD_Cn_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_TET_C1_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_TET_Cn_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_TET_COMP12_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_TRI_C1_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_TRI_C2_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_WEDGE_C2_FEM< Scalar, ArrayScalar >::getValues(), Intrepid::Basis_HGRAD_WEDGE_I2_FEM< Scalar, ArrayScalar >::getValues(), and Intrepid::FieldContainer< Scalar, ArrayTypeId >::resize().
getDkEnumeration()
int Intrepid::getDkEnumeration (const int xMult, const int yMult = -1, const int zMult = -1)
Returns the ordinal of a partial derivative of order k based on the multiplicities of the partials dx, dy, and dz.
By default, any implementation of Intrepid::Basis method returns partials of order k (specified by OPERATOR_Dk) as a multiset ordered by the lexicographical order of the partial derivatives multiplicities. For example, the 10 derivatives of order 3 in 3D are enumerated as:
  D3={(3,0,0),(2,1,0),(2,0,1),(1,2,0),(1,1,1),(1,0,2),(0,3,0),(0,2,1),(0,1,2),(0,0,3)}
The enumeration formula for this lexicographical order is
in 1D (only 1 derivative)
in 2D
in 3D
where the order k of Dk is implicitly defined by xMult + yMult + zMult. Space dimension is implicitly defined by the default values of the multiplicities of y and z derivatives.
Parameters
xMult [in] - multiplicity of dx
yMult [in] - multiplicity of dy (default = -1)
zMult [in] - multiplicity of dz (default = -1)
Returns
the ordinal of partial derivative of order k as function of dx, dy, dz multiplicities
Definition at line 234 of file Intrepid_Utils.cpp.
References Intrepid::getDkEnumeration(), and INTREPID_MAX_DERIVATIVE.
Referenced by Intrepid::getDkEnumeration().
getDkMultiplicities()
void Intrepid::getDkMultiplicities (Teuchos::Array< int > & partialMult, const int derivativeEnum, const EOperator operatorType, const int spaceDim)
Returns multiplicities of dx, dy, and dz based on the enumeration of the partial derivative, its order and the space dimension. Inverse of the getDkEnumeration() method.
Parameters
partialMult [out] - array with the multiplicities f dx, dy and dz
derivativeEnum [in] - enumeration of the partial derivative
operatorType [in] - k-th partial derivative Dk
spaceDim [in] - space dimension
Definition at line 284 of file Intrepid_Utils.cpp.
References Intrepid::getDkCardinality(), Intrepid::getDkMultiplicities(), and Intrepid::getOperatorOrder().
Referenced by Intrepid::getDkMultiplicities(), Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::getValues(), and Intrepid::Basis_HGRAD_QUAD_Cn_FEM< Scalar, ArrayScalar >::getValues().
getFieldRank()
int Intrepid::getFieldRank (const EFunctionSpace spaceType)
Returns the rank of fields in a function space of the specified type.
Field rank is defined as the number of indices needed to specify function value and equals 0, 1,or 2 for scalars, vectors and tensors, respectively. The scalar field spaces in Intrepid are FUNCTION_SPACE_HGRAD and FUNCTION_SPACE_HVOL. The vector field spaces are FUNCTION_SPACE_HCURL, FUNCTION_SPACE_HDIV and FUNCTION_SPACE_VECTOR_HGRAD. FUNCTION_SPACE_TENSOR_HGRAD contains rank-2 tensors.
Parameters
spaceType [in] - function space type
Returns
rank of the fields in the specified function space
Definition at line 62 of file Intrepid_Utils.cpp.
References Intrepid::getFieldRank(), and Intrepid::isValidFunctionSpace().
Referenced by Intrepid::getFieldRank(), Intrepid::getOperatorRank(), and Intrepid::FieldContainer< Scalar, ArrayTypeId >::resize().
getOperatorOrder()
int Intrepid::getOperatorOrder (const EOperator operatorType)
Returns order of an operator.
Parameters
operatorType [in] - type of the operator whose order we want to know
Returns
result ranges from 0 (for OPERATOR_VALUE) to 10 (OPERATOR_D10)
Definition at line 196 of file Intrepid_Utils.cpp.
References Intrepid::getOperatorOrder(), and Intrepid::isValidOperator().
Referenced by Intrepid::getDkCardinality(), Intrepid::getDkMultiplicities(), Intrepid::getOperatorOrder(), and Intrepid::Basis_HGRAD_LINE_Cn_FEM_JACOBI< Scalar, ArrayScalar >::getValues().
getOperatorRank()
int Intrepid::getOperatorRank (const EFunctionSpace spaceType, const EOperator operatorType, const int spaceDim)
Returns rank of an operator.
When an operator acts on a field of a certain rank, the result can be a field with the same or a different rank. Operator rank is defined the difference between the ranks of the output field and the input field:
Rank(OPERATOR) = Rank(OPERATOR(FIELD)) - Rank(FIELD)
Therefore, operator rank allows us to figure out the rank of the result:
Rank(OPERATOR(FIELD)) = Rank(FIELD) + Rank(OPERATOR)
and provides means to size properly arrays for output results. The following table summarizes operator ranks (~ denotes undefined, below slash means 3D). By default, in 1D any operator other than VALUE has rank 1, i.e., GRAD, CURL and DIV reduce to d/dx and Dk are the higher-order derivatives d^k/dx^k. Only scalar functions are allowed in 1D.
|========|======|============================|=========|==========|==========|==========|
| field  | rank |  FUNCTION_SPACE_[type]     |  VALUE  | GRAD, Dk |   CURL   |    DIV   |
|--------|------|----------------------------|---------|----------|----------|----------|
| scalar |   0  |  HGRAD, HVOL               |    0    |     1    | 3-dim/~  |     ~    |
| vector |   1  |  HCURL, HDIV, VECTOR_HGRAD |    0    |     1    | dim - 3  |    -1    |
| tensor |   2  |  TENSOR_HGRAD              |    0    |     1    | dim - 3  |    -1    |
|--------|------|----------------------------|---------|----------|----------|----------|
|   1D   |   0  |  HGRAD, HVOL only          |    0    |     1    |     1    |     1    |
|=======================================================================================|
Parameters
spaceType [in] - function space type
operatorType [in] - the operator acting on the specified function space
spaceDim [in] - spatial dimension
Returns
rank of the operator as defined in the table
Definition at line 91 of file Intrepid_Utils.cpp.
References Intrepid::getFieldRank(), Intrepid::getOperatorRank(), and Intrepid::isValidOperator().
Referenced by Intrepid::getOperatorRank(), and Intrepid::FieldContainer< Scalar, ArrayTypeId >::resize().
requireDimensionMatch() [1/6]
template<class Array1 , class Array2 > bool Intrepid::requireDimensionMatch (std::string & errmsg, const Array1 & array1, const Array2 & array2)
Checks arrays for all their dimensions match. Arrays with equal ranks required.
Parameters
errmsg [out] - error message
array1 [in] - first array argument
array2 [in] - second array argument
Returns
true if array1.dimension(i) == array2.dimension(i), 0 <= i < rank, false otherwise.
Definition at line 1115 of file Intrepid_Utils.hpp.
References Intrepid::requireDimensionMatch(), and Intrepid::requireRankMatch().
requireDimensionMatch() [2/6]
template<class Array1 , class Array2 > bool Intrepid::requireDimensionMatch (std::string & errmsg, const Array1 & array1, const int a1_dim0, const Array2 & array2, const int a2_dim0)
Checks arrays for a single matching dimension.
Parameters
errmsg [out] - error message
array1 [in] - first array argument
a1_dim0 [in] - dimension ordinal for first array
array2 [in] - second array argument
a2_dim0 [in] - dimension ordinal for second array
Returns
true if array1.dimension(a1_dim0) == array2.dimension(a2_dim0), false otherwise
Definition at line 903 of file Intrepid_Utils.hpp.
References Intrepid::requireDimensionMatch().
Referenced by Intrepid::CellTools< Scalar >::checkPointwiseInclusion(), Intrepid::ArrayTools::crossProductDataData(), Intrepid::ArrayTools::crossProductDataField(), Intrepid::CellTools< Scalar >::getPhysicalEdgeTangents(), Intrepid::CellTools< Scalar >::getPhysicalFaceNormals(), Intrepid::CellTools< Scalar >::getPhysicalFaceTangents(), Intrepid::CellTools< Scalar >::mapToReferenceSubcell(), Intrepid::ArrayTools::matmatProductDataData(), Intrepid::ArrayTools::matmatProductDataField(), Intrepid::ArrayTools::matvecProductDataData(), Intrepid::ArrayTools::matvecProductDataField(), Intrepid::ArrayTools::outerProductDataData(), Intrepid::ArrayTools::outerProductDataField(), Intrepid::requireDimensionMatch(), Intrepid::requireDimensionMatch(), Intrepid::requireDimensionMatch(), Intrepid::requireDimensionMatch(), Intrepid::requireDimensionMatch(), Intrepid::requireDimensionMatch(), Intrepid::CellTools< Scalar >::validateArguments_mapToPhysicalFrame(), Intrepid::CellTools< Scalar >::validateArguments_mapToReferenceFrame(), Intrepid::CellTools< Scalar >::validateArguments_mapToReferenceFrame(), Intrepid::CellTools< Scalar >::validateArguments_setJacobianInv(), and Intrepid::RealSpaceTools< Scalar >::vecprod().
requireDimensionMatch() [3/6]
template<class Array1 , class Array2 > bool Intrepid::requireDimensionMatch (std::string & errmsg, const Array1 & array1, const int a1_dim0, const int a1_dim1, const Array2 & array2, const int a2_dim0, const int a2_dim1)
Checks arrays for two matching dimensions.
Parameters
errmsg [out] - error message
array1 [in] - first array argument
a1_dim0 [in] - 1st dimension ordinal for first array
a1_dim1 [in] - 2nd dimension ordinal for first array
array2 [in] - second array argument
a2_dim0 [in] - 1st dimension ordinal for second array
a2_dim1 [in] - 2nd dimension ordinal for second array
Returns
true if array1.dimension(a1_dim*) == array2.dimension(a2_dim*) for *={0,1}, false otherwise
Definition at line 931 of file Intrepid_Utils.hpp.
References Intrepid::requireDimensionMatch().
requireDimensionMatch() [4/6]
template<class Array1 , class Array2 > bool Intrepid::requireDimensionMatch (std::string & errmsg, const Array1 & array1, const int a1_dim0, const int a1_dim1, const int a1_dim2, const Array2 & array2, const int a2_dim0, const int a2_dim1, const int a2_dim2)
Checks arrays for three matching dimensions.
Parameters
errmsg [out] - error message
array1 [in] - first array argument
a1_dim0 [in] - 1st dimension ordinal for first array
a1_dim1 [in] - 2nd dimension ordinal for first array
a1_dim2 [in] - 3rd dimension ordinal for first array
array2 [in] - second array argument
a2_dim0 [in] - 1st dimension ordinal for second array
a2_dim1 [in] - 2nd dimension ordinal for second array
a2_dim2 [in] - 3rd dimension ordinal for second array
Returns
true if array1.dimension(a1_dim*) == array2.dimension(a2_dim*) for *={0,1,2}, false otherwise
Definition at line 963 of file Intrepid_Utils.hpp.
References Intrepid::requireDimensionMatch().
requireDimensionMatch() [5/6]
template<class Array1 , class Array2 > bool Intrepid::requireDimensionMatch (std::string & errmsg, const Array1 & array1, const int a1_dim0, const int a1_dim1, const int a1_dim2, const int a1_dim3, const Array2 & array2, const int a2_dim0, const int a2_dim1, const int a2_dim2, const int a2_dim3)
Checks arrays for four matching dimensions.
Parameters
errmsg [out] - error message
array1 [in] - first array argument
a1_dim0 [in] - 1st dimension ordinal for first array
a1_dim1 [in] - 2nd dimension ordinal for first array
a1_dim2 [in] - 3rd dimension ordinal for first array
a1_dim3 [in] - 4th dimension ordinal for first array
array2 [in] - second array argument
a2_dim0 [in] - 1st dimension ordinal for second array
a2_dim1 [in] - 2nd dimension ordinal for second array
a2_dim2 [in] - 3rd dimension ordinal for second array
a2_dim3 [in] - 4th dimension ordinal for second array
Returns
true if array1.dimension(a1_dim*) == array2.dimension(a2_dim*) for *={0,1,2,3}, false otherwise
Definition at line 1005 of file Intrepid_Utils.hpp.
References Intrepid::requireDimensionMatch().
requireDimensionMatch() [6/6]
template<class Array1 , class Array2 > bool Intrepid::requireDimensionMatch (std::string & errmsg, const Array1 & array1, const int a1_dim0, const int a1_dim1, const int a1_dim2, const int a1_dim3, const int a1_dim4, const Array2 & array2, const int a2_dim0, const int a2_dim1, const int a2_dim2, const int a2_dim3, const int a2_dim4)
Checks arrays for five matching dimensions.
Parameters
errmsg [out] - error message
array1 [in] - first array argument
a1_dim0 [in] - 1st dimension ordinal for first array
a1_dim1 [in] - 2nd dimension ordinal for first array
a1_dim2 [in] - 3rd dimension ordinal for first array
a1_dim3 [in] - 4th dimension ordinal for first array
a1_dim4 [in] - 5th dimension ordinal for first array
array2 [in] - second array argument
a2_dim0 [in] - 1st dimension ordinal for second array
a2_dim1 [in] - 2nd dimension ordinal for second array
a2_dim2 [in] - 3rd dimension ordinal for second array
a2_dim3 [in] - 4th dimension ordinal for second array
a2_dim4 [in] - 5th dimension ordinal for second array
Returns
true if array1.dimension(a1_dim*) == array2.dimension(a2_dim*) for *={0,1,2,3,4}, false otherwise
Definition at line 1054 of file Intrepid_Utils.hpp.
References Intrepid::requireDimensionMatch().
requireDimensionRange()
template<class Array > bool Intrepid::requireDimensionRange (std::string & errmsg, const Array & array, const int dim, const int lowerBound, const int upperBound)
Checks if the specified array dimension is in the required range.
Parameters
errmsg [out] - error message
array [in] - array argument
dim [in] - dimension ordinal, 0 <= dim < array
lowerBound [in] - lower bound for dimension dim
upperBound [in] - upper bound for dimension dim
Returns
true if lowerBound <= array.dimension(dim) <= upperBound, false otherwise
Definition at line 853 of file Intrepid_Utils.hpp.
References Intrepid::requireDimensionRange().
Referenced by Intrepid::ArrayTools::crossProductDataData(), Intrepid::ArrayTools::crossProductDataField(), Intrepid::CellTools< Scalar >::getPhysicalEdgeTangents(), Intrepid::CellTools< Scalar >::getPhysicalFaceNormals(), Intrepid::CellTools< Scalar >::getPhysicalFaceTangents(), Intrepid::CellTools< Scalar >::getReferenceSubcellNodes(), Intrepid::CellTools< Scalar >::getReferenceSubcellVertices(), Intrepid::CellTools< Scalar >::mapToReferenceSubcell(), Intrepid::ArrayTools::matmatProductDataData(), Intrepid::ArrayTools::matmatProductDataField(), Intrepid::ArrayTools::matvecProductDataData(), Intrepid::ArrayTools::matvecProductDataField(), Intrepid::ArrayTools::outerProductDataData(), Intrepid::ArrayTools::outerProductDataField(), Intrepid::requireDimensionRange(), and Intrepid::RealSpaceTools< Scalar >::vecprod().
requireRankMatch()
template<class Array1 , class Array2 > bool Intrepid::requireRankMatch (std::string & errmsg, const Array1 & array1, const Array2 & array2)
Checks if two arrays have matching ranks.
Parameters
errmsg [out] - error message
array1 [in] - first array argument
array2 [in] - second array argument
Returns
true if array.rank1() == array2.rank(), false otherwise
Definition at line 840 of file Intrepid_Utils.hpp.
References Intrepid::requireRankMatch().
Referenced by Intrepid::requireDimensionMatch(), Intrepid::requireRankMatch(), Intrepid::CellTools< Scalar >::validateArguments_mapToPhysicalFrame(), Intrepid::CellTools< Scalar >::validateArguments_mapToReferenceFrame(), and Intrepid::CellTools< Scalar >::validateArguments_setJacobianInv().
requireRankRange()
template<class Array > bool Intrepid::requireRankRange (std::string & errmsg, const Array & array, const int lowerBound, const int upperBound)
Checks if the rank of the array argument is in the required range.
Parameters
errmsg [out] - error message
array [in] - array argument
lowerBound [in] - lower bound for the rank of the array
upperBound [in] - upper bound for the rank of the array
Returns
true if lowerBound <= array.rank() <= rankR, false otherwise
Definition at line 808 of file Intrepid_Utils.hpp.
References Intrepid::requireRankRange().
Referenced by Intrepid::ArrayTools::crossProductDataData(), Intrepid::ArrayTools::crossProductDataField(), Intrepid::CellTools< Scalar >::getPhysicalEdgeTangents(), Intrepid::CellTools< Scalar >::getPhysicalFaceNormals(), Intrepid::CellTools< Scalar >::getPhysicalFaceTangents(), Intrepid::CellTools< Scalar >::getReferenceSubcellNodes(), Intrepid::CellTools< Scalar >::getReferenceSubcellVertices(), Intrepid::CellTools< Scalar >::mapToReferenceSubcell(), Intrepid::ArrayTools::matmatProductDataData(), Intrepid::ArrayTools::matmatProductDataField(), Intrepid::ArrayTools::matvecProductDataData(), Intrepid::ArrayTools::matvecProductDataField(), Intrepid::ArrayTools::outerProductDataData(), Intrepid::ArrayTools::outerProductDataField(), Intrepid::requireRankRange(), Intrepid::CellTools< Scalar >::validateArguments_mapToReferenceFrame(), Intrepid::CellTools< Scalar >::validateArguments_setJacobian(), and Intrepid::RealSpaceTools< Scalar >::vecprod().
setOrdinalTagData()
void Intrepid::setOrdinalTagData (std::vector< std::vector< std::vector< int > > > & tagToOrdinal, std::vector< std::vector< int > > & ordinalToTag, const int * tags, const int basisCard, const int tagSize, const int posScDim, const int posScOrd, const int posDfOrd)
Fills ordinalToTag_ and tagToOrdinal_ by basis-specific tag data.
Parameters
tagToOrdinal [out] - Lookup table for the DoF's ordinal by its tag
ordinalToTag [out] - Lookup table for the DoF's tag by its ordinal
tags [in] - a set of basis-dependent tags in flat (rank-1) array format.
basisCard [in] - cardinality of the basis
tagSize [in] - number of fields in a DoF tag
posScDim [in] - position in the tag, counting from 0, of the subcell dim
posScOrd [in] - position in the tag, counting from 0, of the subcell ordinal
posDfOrd [in] - position in the tag, counting from 0, of DoF ordinal relative to the subcell
Definition at line 455 of file Intrepid_Utils.cpp.
References Intrepid::setOrdinalTagData().
Referenced by Intrepid::Basis_HCURL_HEX_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_HEX_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_QUAD_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_QUAD_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_TET_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_TET_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_TRI_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_TRI_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HCURL_WEDGE_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_HEX_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_HEX_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_QUAD_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_QUAD_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_TET_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_TET_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_TRI_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_TRI_In_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HDIV_WEDGE_I1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_HEX_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_HEX_C2_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_HEX_Cn_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_HEX_I2_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_LINE_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_LINE_Cn_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_LINE_Cn_FEM_JACOBI< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_LINE_Hermite_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_POLY_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_PYR_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_PYR_I2_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_QUAD_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_QUAD_C2_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_QUAD_Cn_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_TET_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_TET_C2_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_TET_Cn_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_TET_COMP12_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_TRI_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_TRI_C2_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_WEDGE_C1_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_WEDGE_C2_FEM< Scalar, ArrayScalar >::initializeTags(), Intrepid::Basis_HGRAD_WEDGE_I2_FEM< Scalar, ArrayScalar >::initializeTags(), and Intrepid::setOrdinalTagData().