NOX: LOCA::MultiContinuation::ConstraintModelEvaluator Class Reference
LOCA::MultiContinuation::ConstraintModelEvaluator Class Reference
Generic object that provides constraints through model evaluator responses.
#include <LOCA_Tpetra_ConstraintModelEvaluator.hpp>
Public Member Functions
ConstraintModelEvaluator (const Teuchos::RCP<::Thyra::ModelEvaluator< double > > &model, const LOCA::ParameterVector &pVec, const std::vector< std::string > &constraintResponseNames, const NOX::Abstract::Vector &cloneVec)
ConstraintModelEvaluator (const LOCA::MultiContinuation::ConstraintModelEvaluator &cme, NOX::CopyType type=NOX::DeepCopy)
void copy (const ConstraintInterface &source)
Copy.
Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > clone (NOX::CopyType type=NOX::DeepCopy) const
Cloning function.
int numConstraints () const
Return number of constraints.
void setX (const NOX::Abstract::Vector &x)
Set the solution vector to x.
void setParam (int paramID, double val)
Set parameter value given a parameter indices corresponding to the LOCA::ParameterVector.
void setParams (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Set parameter value given a parameter indices corresponding to the LOCA::ParameterVector.
NOX::Abstract::Group::ReturnType computeConstraints ()
Compute constraint residuals.
NOX::Abstract::Group::ReturnType computeDX ()
Compute derivative of constraints w.r.t. solution vector x.
NOX::Abstract::Group::ReturnType computeDP (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector::DenseMatrix &dgdp, bool isValidG)
Compute derivative of constraints w.r.t. supplied parameters.
bool isConstraints () const
Return true if constraint residuals are valid.
bool isDX () const
Return true if derivative of constraint w.r.t. x is valid.
const NOX::Abstract::MultiVector::DenseMatrix & getConstraints () const
Return constraint residuals.
bool isDXZero () const
Return true if solution component of constraint derivatives is zero.
NOX::Abstract::MultiVector * getDX () const
Return solution component of constraint derivatives.
const LOCA::ParameterVector getParams () const
Public Member Functions inherited from LOCA::MultiContinuation::ConstraintInterfaceMVDX
ConstraintInterfaceMVDX ()
Constructor.
virtual ~ConstraintInterfaceMVDX ()
Destructor.
virtual NOX::Abstract::Group::ReturnType multiplyDX (double alpha, const NOX::Abstract::MultiVector &input_x, NOX::Abstract::MultiVector::DenseMatrix &result_p) const
Compute result_p = alpha * dg/dx * input_x.
virtual NOX::Abstract::Group::ReturnType addDX (Teuchos::ETransp transb, double alpha, const NOX::Abstract::MultiVector::DenseMatrix &b, double beta, NOX::Abstract::MultiVector &result_x) const
Compute result_x = alpha * dg/dx^T * op(b) + beta * result_x.
Public Member Functions inherited from LOCA::MultiContinuation::ConstraintInterface
ConstraintInterface ()
Constructor.
virtual ~ConstraintInterface ()
Destructor.
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus)
Perform any postprocessing after a continuation step finishes.
Detailed Description
Generic object that provides constraints through model evaluator responses.
Constructor & Destructor Documentation
ConstraintModelEvaluator()
LOCA::MultiContinuation::ConstraintModelEvaluator::ConstraintModelEvaluator (const Teuchos::RCP<::Thyra::ModelEvaluator< double > > & model, const LOCA::ParameterVector & pVec, const std::vector< std::string > & constraintResponseNames, const NOX::Abstract::Vector & cloneVec)
Constructor
Parameters
model Model evaluator that provides constraints as responses.
pVec The independent parameters for constraints.
constrantResponseNames The names of the responses used as constraint equations.
cloneVec NOX vector used to clone data structures with same space/map.
References NOX::Abstract::Vector::clone(), NOX::Abstract::Vector::createMultiVector(), LOCA::ParameterVector::getNamesVector(), LOCA::ParameterVector::length(), and NOX::ShapeCopy.
Member Function Documentation
clone()
Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > LOCA::MultiContinuation::ConstraintModelEvaluator::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Cloning function.
Implements LOCA::MultiContinuation::ConstraintInterface.
computeConstraints()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstraintModelEvaluator::computeConstraints () virtual
Compute constraint residuals.
Implements LOCA::MultiContinuation::ConstraintInterface.
References LOCA::ParameterVector::length(), and NOX::Abstract::Group::Ok.
Referenced by computeDP().
computeDP()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstraintModelEvaluator::computeDP (const std::vector< int > & paramIDs, NOX::Abstract::MultiVector::DenseMatrix & dgdp, bool isValidG) virtual
Compute derivative of constraints w.r.t. supplied parameters.
The first column of dgdp should be filled with the constraint residuals if isValidG is false. If isValidG is true, then the dgdp contains on input.
Implements LOCA::MultiContinuation::ConstraintInterface.
References computeConstraints(), isConstraints(), LOCA::ParameterVector::length(), and NOX::Abstract::Group::Ok.
computeDX()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstraintModelEvaluator::computeDX () virtual
Compute derivative of constraints w.r.t. solution vector x.
Implements LOCA::MultiContinuation::ConstraintInterface.
References LOCA::ParameterVector::length(), and NOX::Abstract::Group::Ok.
copy()
void LOCA::MultiContinuation::ConstraintModelEvaluator::copy (const ConstraintInterface & source) virtual
Copy.
Implements LOCA::MultiContinuation::ConstraintInterface.
References LOCA::ParameterVector::length().
getConstraints()
const NOX::Abstract::MultiVector::DenseMatrix & LOCA::MultiContinuation::ConstraintModelEvaluator::getConstraints () const virtual
Return constraint residuals.
Implements LOCA::MultiContinuation::ConstraintInterface.
getDX()
NOX::Abstract::MultiVector * LOCA::MultiContinuation::ConstraintModelEvaluator::getDX () const virtual
Return solution component of constraint derivatives.
May return NULL if constraint derivative is zero
Implements LOCA::MultiContinuation::ConstraintInterfaceMVDX.
isConstraints()
bool LOCA::MultiContinuation::ConstraintModelEvaluator::isConstraints () const virtual
Return true if constraint residuals are valid.
Implements LOCA::MultiContinuation::ConstraintInterface.
Referenced by computeDP().
isDX()
bool LOCA::MultiContinuation::ConstraintModelEvaluator::isDX () const virtual
Return true if derivative of constraint w.r.t. x is valid.
Implements LOCA::MultiContinuation::ConstraintInterface.
isDXZero()
bool LOCA::MultiContinuation::ConstraintModelEvaluator::isDXZero () const virtual
Return true if solution component of constraint derivatives is zero.
Implements LOCA::MultiContinuation::ConstraintInterface.
numConstraints()
int LOCA::MultiContinuation::ConstraintModelEvaluator::numConstraints () const virtual
Return number of constraints.
Implements LOCA::MultiContinuation::ConstraintInterface.
setParam()
void LOCA::MultiContinuation::ConstraintModelEvaluator::setParam (int paramID, double val) virtual
Set parameter value given a parameter indices corresponding to the LOCA::ParameterVector.
Implements LOCA::MultiContinuation::ConstraintInterface.
setParams()
void LOCA::MultiContinuation::ConstraintModelEvaluator::setParams (const std::vector< int > & paramIDs, const NOX::Abstract::MultiVector::DenseMatrix & vals) virtual
Set parameter value given a parameter indices corresponding to the LOCA::ParameterVector.
Implements LOCA::MultiContinuation::ConstraintInterface.
setX()
void LOCA::MultiContinuation::ConstraintModelEvaluator::setX (const NOX::Abstract::Vector & x) virtual
Set the solution vector to x.
Implements LOCA::MultiContinuation::ConstraintInterface.
The documentation for this class was generated from the following files:
LOCA_Tpetra_ConstraintModelEvaluator.hpp
LOCA_Tpetra_ConstraintModelEvaluator.cpp