NOX: NOX::Solver::InexactTrustRegionBased Class Reference
NOX::Solver::InexactTrustRegionBased Class Reference
Newton-like solver using a trust region.
#include <NOX_Solver_InexactTrustRegionBased.H>
Public Member Functions
InexactTrustRegionBased (const Teuchos::RCP< NOX::Abstract::Group > &grp, const Teuchos::RCP< NOX::StatusTest::Generic > &tests, const Teuchos::RCP< Teuchos::ParameterList > &params)
Constructor.
virtual ~InexactTrustRegionBased ()
Destructor.
virtual void reset (const NOX::Abstract::Vector &initialGuess, const Teuchos::RCP< NOX::StatusTest::Generic > &tests)
Resets the solver, sets a new status test, and sets a new initial guess.
virtual void reset (const NOX::Abstract::Vector &initialGuess)
Resets the solver and sets a new initial guess.
virtual void reset ()
Resets the solver for another solve. This resets the counters and status only. Uses the final solution from the last solve as the initial guess for the next solve.
virtual NOX::StatusTest::StatusType step ()
Do one nonlinear step in the iteration sequence and return status.
virtual NOX::StatusTest::StatusType solve ()
Solve the nonlinear problem and return final status.
virtual const NOX::Abstract::Group & getSolutionGroup () const
Return a reference to the current solution group.
virtual const NOX::Abstract::Group & getPreviousSolutionGroup () const
Return a reference to the previous solution group.
virtual NOX::StatusTest::StatusType getStatus () const
Returns the current status of the solver.
virtual int getNumIterations () const
Get number of iterations.
virtual const Teuchos::ParameterList & getList () const
Return a reference to the solver parameters.
virtual Teuchos::RCP< const NOX::Abstract::Group > getSolutionGroupPtr () const
Return a RCP to the solution group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getPreviousSolutionGroupPtr () const
Return a RCP to the previous solution group.
virtual Teuchos::RCP< const Teuchos::ParameterList > getListPtr () const
Return a RCP to the solver parameters.
virtual Teuchos::RCP< const NOX::SolverStats > getSolverStatistics () const
Return a RCP to the solver statistics.
Public Member Functions inherited from NOX::Solver::Generic
Generic ()
Constructor (does nothing)
virtual ~Generic ()
Destructor (does nothing)
Protected Types
enum TrustRegionType { Standard , Inexact }
Type of Trust Region algorithm to use.
enum InnerIterationReturnType { Converged , Unconverged , Failed }
Return types for inner iteration status test.
enum StepType { Newton , Cauchy , Dogleg }
Enumerated list for each direction that may be required in the Trust region computation.
Protected Member Functions
virtual NOX::StatusTest::StatusType iterateStandard ()
"Standard" trust region implementation
virtual NOX::StatusTest::StatusType iterateInexact ()
"Inexact Trust Region"
virtual void init ()
Print out initialization information and calcuation the RHS.
virtual void printUpdate ()
Prints the current iteration information.
virtual void invalid (const std::string &param, double value) const
Print an error message and throw an error during parameter reads.
virtual void throwError (const std::string &method, const std::string &mesage) const
Print an error message and throw an error.
NOX::StatusTest::StatusType checkStep (const NOX::Abstract::Vector &step, double &radius)
Check to see if the current step is acceptable. If not, it reduces the trust region radius accordingly.
virtual double computeNorm (const NOX::Abstract::Vector &v)
Computes the norm of a given vector.
Protected Attributes
TrustRegionType method
Type of trust region algorithm to use.
Teuchos::RCP< NOX::GlobalData > globalDataPtr
Pointer to the global data object.
Teuchos::RCP< NOX::Utils > utils
Utils.
InnerIterationReturnType innerIterationStatus
Current status of the trust region inner iteration.
Teuchos::RCP< NOX::Abstract::Group > solnPtr
Current solution.
Teuchos::RCP< NOX::Abstract::Group > oldSolnPtr
Previous solution pointer.
Teuchos::RCP< NOX::Abstract::Vector > newtonVecPtr
Current newton direction pointer.
Teuchos::RCP< NOX::Abstract::Vector > cauchyVecPtr
Current cauchy direction pointer.
Teuchos::RCP< NOX::Abstract::Vector > rCauchyVecPtr
Extra vector used in computations.
Teuchos::RCP< NOX::Abstract::Vector > residualVecPtr
Extra vector used in computations.
Teuchos::RCP< NOX::Abstract::Vector > aVecPtr
Extra vector used in computations.
Teuchos::RCP< NOX::Abstract::Vector > bVecPtr
Extra vector used in computations.
Teuchos::RCP< NOX::StatusTest::Generic > testPtr
Stopping test.
Teuchos::RCP< Teuchos::ParameterList > paramsPtr
Input parameters.
NOX::Direction::Utils::InexactNewton inNewtonUtils
Inexact Newton utitilities.
Teuchos::RCP< NOX::Direction::Generic > newtonPtr
Newton Search Direction.
Teuchos::RCP< NOX::Direction::Generic > cauchyPtr
Cauchy Search Direction.
double radius
Radius of the trust region.
double minRatio
Minimum improvement ratio to accept step.
double minRadius
Minimum trust region radius.
double maxRadius
Maximum trust region radius.
double contractTriggerRatio
ratio < alpha triggers contraction
double expandTriggerRatio
ratio > beta triggers expansion
double expandFactor
Expansion factor.
double contractFactor
Constraction factor.
double recoveryStep
double newF
Value of at current solution.
double oldF
Value of at previous solution.
double dx
norm(xnew - xold)
int nIter
Number of nonlinear iterations.
double eta
Current linear solve tolerance (inexact only).
double eta_last
Linear solve tolerance used in last iteration (inexact only).
NOX::StatusTest::StatusType status
Status of nonlinear solver.
NOX::StatusTest::CheckType checkType
Type of check to use for status tests. See NOX::StatusTest for more details.
StepType stepType
Type of step to be taken.
Teuchos::RCP< NOX::MeritFunction::Generic > meritFuncPtr
Stores merit function supplied by global data.
bool useCauchyInNewtonDirection
If set to true, the initial guess for the Newton direction computation will use the Cauchy direction as the initial guess.
bool writeOutputParamsToList
If set to true, statistics/counters will be output to the output list.
bool useCounters
If set to true, counters will be stored by the solver.
NOX::SolverStats::TrustRegionStats * counters
Counters for the algorithm.
bool useAredPredRatio
If set to true, the minimum improvement ratio condition uses an Ared/Pred approach.
bool useDoglegMinimization
If set to true, the parameter is minimized over the dogleg line segments instead of being computed at the trust regioin radius.
Teuchos::RCP< NOX::Observer > observer
Pointer to a user defined NOX::Observer object.
Detailed Description
Newton-like solver using a trust region.
Our goal is to solve: where . Alternatively, we might say that we wish to solve
The trust region subproblem (TRSP) at iteration is given by
where
,
,
,
is the Jacobian of at , and
is the trust region radius.
The "improvement ratio" for a given step is defined as
An iteration consists of the following steps.
Compute Newton-like direction:
Compute Cauchy-like direction:
If this is the first iteration, initialize as follows: If , then ; else, .
Initialize
While and , do the following.
Compute the direction as follows:
If , then take a Newton step by setting
Otherwise if , then take a Cauchy step by setting
Otherwise, take a Dog Leg step by setting where with .
Set and calculate
If , then Otherwise
Update the solution:
Update trust region:
If and , then shrink the trust region to the size of the Newton step: .
Otherwise if , then shrink the trust region: .
Otherwise if and , then expand the trust region: .
Input Paramters
The following parameters should be specified in the "Trust Region" sublist based to the solver.
"Inner Iteration Method" - Choice of trust region algorithm to use. Choices are:
"Standard Trust Region"
"Inexact Trust Region"
"Direction" - Sublist of the direction parameters for the Newton point, passed to the NOX::Direction::Manager constructor. If this sublist does not exist, it is created by default. Furthermore, if "Method" is not specified in this sublist, it is added with a value of "Newton".
"Cauchy %Direction" - Sublist of the direction parameters for the Cauchy point, passed to the NOX::Direction::Manager constructor. If this sublist does not exist, it is created by default. Furthermore, if "Method" is not specified in this sublist, it is added with a value of "Steepest Descent" Finally, if the sub-sublist "Steepest Descent" does not exist, it is created and the parameter "Scaling Type" is added and set to "Quadratic Min Model".
"Minimum Trust Region Radius" () - Minimum allowable trust region radius. Defaults to 1.0e-6.
"Maximum Trust Region Radius" () - Minimum allowable trust region radius. Defaults to 1.0e+10.
"Minimum Improvement Ratio" () - Minimum improvement ratio to accept the step. Defaults to 1.0e-4.
"Contraction Trigger Ratio" () - If the improvement ratio is less than this value, then the trust region is contracted by the amount specified by the "Contraction Factor". Must be larger than "Minimum Improvement Ratio". Defaults to 0.1.
"Contraction Factor" () - See above. Defaults to 0.25.
"Expansion Trigger Ratio" () - If the improvement ratio is greater than this value, then the trust region is contracted by the amount specified by the "Expansion Factor". Defaults to 0.75.
"Expansion Factor" () - See above. Defaults to 4.0.
"Recovery Step" - Defaults to 1.0.
"Use Ared/Pred Ratio Calculation" (boolean) - Defaults to false. If set to true, this option replaces the algorithm used to compute the improvement ratio, , as described above. The improvement ratio is replaced by an "Ared/Pred" sufficient decrease criteria similar to that used in line search algorithms (see Eisenstat and Walker, SIAM Journal on Optimization V4 no. 2 (1994) pp 393-422):
"Use Cauchy in Newton Direction" - Boolean. Used only by the "Inexact Trust Region" algorithm. If set to true, the initial guess for the Newton direction computation will use the Cauchy direction as the initial guess. Defaults to false.
"Use Dogleg Segment Minimization" - Boolean. Used only by the "Inexact Trust Region" algorithm. If set to true, the parameter is minimized over the dogleg line segments instead of being computed at the trust regioin radius. Used only by the "Inexact Trust Region" algorithm. Defaults to false.
"Use Counters" - Boolean. If set to true, solver statistics will be stored. Defaults to true.
"Write Output Parameters" - Boolean. If set to true, the solver statistics will be written to the relevant "Output" sublists (see Output Parameters). Defaults to true.
"Solver Options" - Sublist of general solver options.
"User Defined Pre/Post Operator" is supported. See NOX::Parameter::PrePostOperator for more details.
Output Paramters
A sublist called "Output" will be created at the top level of the parameter list and contain the following general solver parameters:
"Nonlinear Iterations" - Number of nonlinear iterations
"2-Norm or Residual" - Two-norm of final residual
A sublist called "Output" will be created in the "Trust Region" sublist and contain the following trust region specific output parameters:
"Number of Cauchy Steps" - Number of cauchy steps taken during the solve.
"Number of Newton Steps" - Number of Newton steps taken during the solve.
"Number of Dogleg Steps" - Number of Dogleg steps taken during the solve.
"Number of Trust Region Inner Iterations" - Number of inner iterations required to adjust the trust region radius.
"Dogleg Steps: Average Fraction of Newton Step Length" - Average value of the fraction a dogleg step took compared to the full Newton step. The fractional value is computed as .
"Dogleg Steps: Average Fraction Between Cauchy and Newton Direction" - Average value of the fraction a dogleg step took between the Cauchy and Newton directions. This is the variable in the standard dogleg algorithm and the parameter in the inexact dogleg algorithm. A value of 0.0 is a full step in the Cauchy direction and a value of 1.0 is a full step in the Newton direction.
Author
Tammy Kolda (SNL 8950), Roger Pawlowski (SNL 9233)
Member Enumeration Documentation
InnerIterationReturnType
enum NOX::Solver::InexactTrustRegionBased::InnerIterationReturnType protected
Return types for inner iteration status test.
Enumerator
Converged
Converged.
Unconverged
Unconverged.
Failed
Failed by hitting minimum radius bound.
StepType
enum NOX::Solver::InexactTrustRegionBased::StepType protected
Enumerated list for each direction that may be required in the Trust region computation.
Enumerator
Newton
Use the Newton direction.
Cauchy
Use the Cauchy direction.
Dogleg
Use the doglog direction.
TrustRegionType
enum NOX::Solver::InexactTrustRegionBased::TrustRegionType protected
Type of Trust Region algorithm to use.
Enumerator
Standard
Basic trust region method for nonlinear systems (Nocedal and Wright?).
Inexact
Inexact Trust region WITHOUT minimization of the local linear model over the line segments.
Constructor & Destructor Documentation
InexactTrustRegionBased()
NOX::Solver::InexactTrustRegionBased::InexactTrustRegionBased (const Teuchos::RCP< NOX::Abstract::Group > & grp, const Teuchos::RCP< NOX::StatusTest::Generic > & tests, const Teuchos::RCP< Teuchos::ParameterList > & params)
Constructor.
See reset() for description.
References counters, globalDataPtr, init(), inNewtonUtils, meritFuncPtr, observer, paramsPtr, NOX::Solver::parseObserver(), NOX::Direction::Utils::InexactNewton::reset(), utils, and NOX::Solver::validateSolverOptionsSublist().
Member Function Documentation
computeNorm()
double NOX::Solver::InexactTrustRegionBased::computeNorm (const NOX::Abstract::Vector & v) protected virtual
Computes the norm of a given vector.
Defaults to the L-2 norm but could use a user defined norm also.
References NOX::Abstract::Vector::norm().
getList()
const Teuchos::ParameterList & NOX::Solver::InexactTrustRegionBased::getList () const virtual
Return a reference to the solver parameters.
Implements NOX::Solver::Generic.
getListPtr()
virtual Teuchos::RCP< const Teuchos::ParameterList > NOX::Solver::InexactTrustRegionBased::getListPtr () const inline virtual
Return a RCP to the solver parameters.
Implements NOX::Solver::Generic.
References paramsPtr.
getNumIterations()
int NOX::Solver::InexactTrustRegionBased::getNumIterations () const virtual
Get number of iterations.
Implements NOX::Solver::Generic.
getPreviousSolutionGroup()
const Abstract::Group & NOX::Solver::InexactTrustRegionBased::getPreviousSolutionGroup () const virtual
Return a reference to the previous solution group.
Implements NOX::Solver::Generic.
getPreviousSolutionGroupPtr()
virtual Teuchos::RCP< const NOX::Abstract::Group > NOX::Solver::InexactTrustRegionBased::getPreviousSolutionGroupPtr () const inline virtual
Return a RCP to the previous solution group.
Implements NOX::Solver::Generic.
References oldSolnPtr.
getSolutionGroup()
const Abstract::Group & NOX::Solver::InexactTrustRegionBased::getSolutionGroup () const virtual
Return a reference to the current solution group.
Implements NOX::Solver::Generic.
getSolutionGroupPtr()
virtual Teuchos::RCP< const NOX::Abstract::Group > NOX::Solver::InexactTrustRegionBased::getSolutionGroupPtr () const inline virtual
Return a RCP to the solution group.
Implements NOX::Solver::Generic.
References solnPtr.
getSolverStatistics()
Teuchos::RCP< const NOX::SolverStats > NOX::Solver::InexactTrustRegionBased::getSolverStatistics () const virtual
Return a RCP to the solver statistics.
Implements NOX::Solver::Generic.
getStatus()
NOX::StatusTest::StatusType NOX::Solver::InexactTrustRegionBased::getStatus () const virtual
Returns the current status of the solver.
Implements NOX::Solver::Generic.
reset() [1/3]
void NOX::Solver::InexactTrustRegionBased::reset () virtual
Resets the solver for another solve. This resets the counters and status only. Uses the final solution from the last solve as the initial guess for the next solve.
NOTE: All NOX solvers will call reset() automatically at teh beginning of the solve() method. We add the reset() method to the solver interface for the application to call in case the application needs to reset counters and status manually before the next call to solve() is made.
Implements NOX::Solver::Generic.
References NOX::Utils::fill(), NOX::Utils::Parameters, and NOX::StatusTest::Unconverged.
reset() [2/3]
void NOX::Solver::InexactTrustRegionBased::reset (const NOX::Abstract::Vector & initial_guess) virtual
Resets the solver and sets a new initial guess.
Implements NOX::Solver::Generic.
References NOX::Utils::fill(), NOX::Utils::Parameters, and NOX::StatusTest::Unconverged.
reset() [3/3]
void NOX::Solver::InexactTrustRegionBased::reset (const NOX::Abstract::Vector & initial_guess, const Teuchos::RCP< NOX::StatusTest::Generic > & test) virtual
Resets the solver, sets a new status test, and sets a new initial guess.
Implements NOX::Solver::Generic.
References NOX::Utils::fill(), NOX::Utils::Parameters, and NOX::StatusTest::Unconverged.
solve()
NOX::StatusTest::StatusType NOX::Solver::InexactTrustRegionBased::solve () virtual
Solve the nonlinear problem and return final status.
By "solve", we call iterate() until the NOX::StatusTest value is either NOX::StatusTest::Converged or NOX::StatusTest::Failed.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Unconverged.
step()
NOX::StatusTest::StatusType NOX::Solver::InexactTrustRegionBased::step () virtual
Do one nonlinear step in the iteration sequence and return status.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Unconverged.
Member Data Documentation
recoveryStep
double NOX::Solver::InexactTrustRegionBased::recoveryStep protected
Take a step of this length in the Newton direction if the trust-region search fails
The documentation for this class was generated from the following files:
NOX_Solver_InexactTrustRegionBased.H
NOX_Solver_InexactTrustRegionBased.C