NOX: LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup Class Reference
LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup Class Reference
A group representing the minimally augemented turning point equations.
#include <LOCA_TurningPoint_MinimallyAugmented_ExtendedGroup.H>
Public Member Functions
ExtendedGroup (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > &topParams, const Teuchos::RCP< Teuchos::ParameterList > &tpParams, const Teuchos::RCP< LOCA::TurningPoint::MinimallyAugmented::AbstractGroup > &g)
Constructor with initial data passed through parameter lists.
ExtendedGroup (const ExtendedGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~ExtendedGroup ()
Destructor.
Implementation of NOX::Abstract::Group virtual methods
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Assignment operator.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const
Cloning function.
virtual void setX (const NOX::Abstract::Vector &y)
Set the solution vector, x, to y.
virtual void computeX (const NOX::Abstract::Group &g, const NOX::Abstract::Vector &d, double step)
Compute this.x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()
Compute the turning point equation residual .
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute the blocks of the Jacobian derivative of .
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Gradient computation is not defined for this group.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute Newton direction using applyJacobianInverse().
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Computes the extended Jacobian vector product.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Computes the extended Jacobian transpose vector product.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the extended Jacobian matrix.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Jacobian transpose for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian inverse for extended system.
virtual bool isF () const
Return true if the extended residual is valid.
virtual bool isJacobian () const
Return true if the extended Jacobian is valid.
virtual bool isGradient () const
Always returns false.
virtual bool isNewton () const
Return true if the extended Newton direction is valid.
virtual const NOX::Abstract::Vector & getX () const
Return extended solution vector .
virtual const NOX::Abstract::Vector & getF () const
Return extended equation residual .
virtual double getNormF () const
Return 2-norm of .
virtual const NOX::Abstract::Vector & getGradient () const
Vector returned is not valid.
virtual const NOX::Abstract::Vector & getNewton () const
Return extended Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const
Return RCP to extended solution vector .
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const
Return RCP to extended equation residual .
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const
Vector returned is not valid.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const
Return RCP to extended Newton direction.
virtual double getNormNewtonSolveResidual () const
Return the norm of the Newton solve residual.
Implementation of LOCA::Extended::MultiAbstractGroup
virtual methods
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup () const
Return underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup ()
Return underlying group.
Implementation of LOCA::MultiContinuation::AbstractGroup
virtual methods
virtual void copy (const NOX::Abstract::Group &source)
Assignment operator.
virtual void setParamsMulti (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Set parameters indexed by (integer) paramIDs.
virtual void setParams (const ParameterVector &p)
Set the parameter vector in the group to p.
virtual void setParam (std::string paramID, double val)
Set parameter indexed by paramID.
virtual void setParam (int paramID, double val)
Set parameter indexed by paramID.
virtual const ParameterVector & getParams () const
Return a const reference to the paramter vector owned by the group.
virtual double getParam (int paramID) const
Return copy of parameter indexed by paramID.
virtual double getParam (std::string paramID) const
Return copy of parameter indexed by paramID.
virtual NOX::Abstract::Group::ReturnType computeDfDpMulti (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector &dfdp, bool isValidF)
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any postprocessing after a continuation step finishes.
virtual void projectToDraw (const NOX::Abstract::Vector &x, double *px) const
Projects solution to a few scalars for multiparameter continuation.
virtual int projectToDrawDimension () const
Returns the dimension of the project to draw array.
virtual void printSolution (const double conParam) const
Function to print out extended solution and continuation parameter after successful continuation step.
virtual void printSolution (const NOX::Abstract::Vector &x_, const double conParam) const
Function to print out extended solution and continuation parameter after successful continuation step.
Implementation of
LOCA::BorderedSystem::AbstractGroup virtual methods
virtual int getBorderedWidth () const
Return the total width of the bordered rows/columns.
virtual Teuchos::RCP< const NOX::Abstract::Group > getUnborderedGroup () const
Get bottom-level unbordered group.
virtual bool isCombinedAZero () const
Indicates whether combined A block is zero.
virtual bool isCombinedBZero () const
Indicates whether combined B block is zero.
virtual bool isCombinedCZero () const
Indicates whether combined C block is zero.
virtual void extractSolutionComponent (const NOX::Abstract::MultiVector &v, NOX::Abstract::MultiVector &v_x) const
virtual void extractParameterComponent (bool use_transpose, const NOX::Abstract::MultiVector &v, NOX::Abstract::MultiVector::DenseMatrix &v_p) const
virtual void loadNestedComponents (const NOX::Abstract::MultiVector &v_x, const NOX::Abstract::MultiVector::DenseMatrix &v_p, NOX::Abstract::MultiVector &v) const
virtual void fillA (NOX::Abstract::MultiVector &A) const
Fill the combined A block as described above.
virtual void fillB (NOX::Abstract::MultiVector &B) const
Fill the combined B block as described above.
virtual void fillC (NOX::Abstract::MultiVector::DenseMatrix &C) const
Fill the combined C block as described above.
Public Member Functions inherited from LOCA::Extended::MultiAbstractGroup
MultiAbstractGroup ()
Default constructor.
virtual ~MultiAbstractGroup ()
Destructor.
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup () const
Return base-level underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup ()
Return base-level underlying group.
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual ~Group ()
Destructor.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual const NOX::Abstract::Vector & getScaledX () const
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
Public Member Functions inherited from LOCA::MultiContinuation::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
virtual double computeScaledDotProduct (const NOX::Abstract::Vector &a, const NOX::Abstract::Vector &b) const
Compute a scaled dot product.
virtual void scaleVector (NOX::Abstract::Vector &x) const
Scales a vector using scaling vector.
Public Member Functions inherited from LOCA::BorderedSystem::AbstractGroup
AbstractGroup ()
Constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::Abstract::TransposeSolveGroup
TransposeSolveGroup ()
Constructor.
virtual ~TransposeSolveGroup ()
Destructor.
Implementation of LOCA::Abstract::TransposeSolveGroup
virtual methods
Teuchos::RCP< LOCA::GlobalData > globalData
Pointer LOCA global data object.
Teuchos::RCP< LOCA::Parameter::SublistParser > parsedParams
Parsed top-level parameters.
Teuchos::RCP< Teuchos::ParameterList > turningPointParams
Bifurcation parameter list.
Teuchos::RCP< LOCA::TurningPoint::MinimallyAugmented::AbstractGroup > grpPtr
Pointer to base group that defines .
Teuchos::RCP< LOCA::TurningPoint::MinimallyAugmented::Constraint > constraint
Pointer to the constraint equation.
Teuchos::RCP< LOCA::MultiContinuation::ConstrainedGroup > conGroup
Pointer to constrained group implementation.
int bifParamID
Stores the bifurcation parameter index.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Solve Jacobian-tranpose system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Solve Jacobian-tranpose system with multiple right-hand sides.
double getBifParam () const
Get bifurcation parameter.
Teuchos::RCP< const NOX::Abstract::Vector > getLeftNullVec () const
Returns left null vector.
Teuchos::RCP< const NOX::Abstract::Vector > getRightNullVec () const
Returns right null vector v.
Teuchos::RCP< const NOX::Abstract::Vector > getAVec () const
Returns "A" vector.
Teuchos::RCP< const NOX::Abstract::Vector > getBVec () const
Returns "B".
void setBifParam (double param)
Set bifurcation parameter.
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
A group representing the minimally augemented turning point equations.
The LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup is a concrete implementation of the NOX::Abstract::Group, LOCA::MultiContinuation::AbstractGroup and LOCA::Extended::MultiAbstractGroup that defines the following extended set of equations that are regular at a generic turning point:
where , is the solution vector, is the bifurcation parameter, is the Jacobian of , and is a measure of the singularity of and is defined via
for any vectors and in . Using these relationships, it is easy to show
The group stores an underlying group of type LOCA::TurningPoint::MinimallyAugmented::AbstractGroup to represent the equations and to manipulate the underlying Jacobian . This interface defines methods for computing the derivatives and as well.
This class implements all of the NOX::Abstract::Group, LOCA::MultiContinuation::AbstractGroup, and LOCA::Extended::MultiAbstractGroup methods for this extended set of equations and therefore is a complete group which can be passed to most NOX solvers to locate a single turning point or to the LOCA::Stepper to compute a family of turning points in a second parameter.
The class is intialized via the tpParams parameter list argument to the constructor. The parameters this class recognizes are:
"Bifurcation Parameter" – [string] (Must be supplied) - Name of the bifurcation parameter
"Bordered Solver Method" – [string] (default "Bordering") Method for solving bordered systems of equations. See LOCA::BorderedSolver::Factory for a description.
"Symmetric Jacobian" – [bool] (default: false) - Flag indicating whether Jacobian matrix is symmetric, in which case we force and therefore the second tranpose solve for is unnecessary
"Constraint Method" – [string] (default: "Default") - Type of constraint method to use. Valid choices are
"Default" (LOCA::TurningPoint::MinimallyAugmented::Constraint) Default method described above.
"Modified" (LOCA::TurningPoint::MinimallyAugmented::ModifiedConstraint) A modified method that computes updates to the null vectors every nonlinear interation, instead of directly solving for them
"Initial Null Vector Compuation" – [string] (default: "User Provided") - Method to compute initial and vectors. Valid choices are:
"User Provided" - Initial vectors are provided in the parameter list, in which case the following parameters are relevant:
"Initial A Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied) - Vector storing initial value for vector
"Initial B Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied for nonsymmetric Jacobians) - Vector storing initial value for vector
"Solve df/dp" - Compute and where is the bifurcation parameter.
"Constant" - Entries of $a$ and $b$ are set to 1.0
"Null Vector Scaling Method" – [string] (default: "Order N") - Method to scale and . This determines the norm of these vectors and the scaling of . Valid choices are:
"None" – Use initial scaling
"Order 1" – Scale to unit norm
"Order N" – Use vector length scaling
"Update Null Vectors Every Continuation Step" – [bool] (default: true) - Flag indicating whether to update and vectors via and every continuation step
"Update Null Vectors Every Nonlinear Iteration" – [bool] (default: false) - Flag indicating whether to update and vectors via and every nonlinear iteration
"Multiply Null Vectors by Mass Matrix" – [bool] (default: false) - Flag indicating whether to multiply and vectors by the mass matrix at the strart of a turning point calculation, and each time and are updated. This can improve the scaling of these vectors, and may orthogonalize them against structural null spaces (i.e., pressure null space for incompressible Navier-Stokes).
Member Function Documentation
applyJacobian()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobian (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Computes the extended Jacobian vector product.
Reimplemented from NOX::Abstract::Group.
applyJacobianInverse()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobianInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies the inverse of the extended Jacobian matrix.
Reimplemented from NOX::Abstract::Group.
applyJacobianInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobianInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian inverse for extended system.
Reimplemented from NOX::Abstract::Group.
applyJacobianMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobianMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian for extended system.
Reimplemented from NOX::Abstract::Group.
applyJacobianTranspose()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobianTranspose (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Computes the extended Jacobian transpose vector product.
Reimplemented from NOX::Abstract::Group.
applyJacobianTransposeInverse()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobianTransposeInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Solve Jacobian-tranpose system.
Implements LOCA::Abstract::TransposeSolveGroup.
applyJacobianTransposeInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobianTransposeInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Solve Jacobian-tranpose system with multiple right-hand sides.
Implements LOCA::Abstract::TransposeSolveGroup.
applyJacobianTransposeMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Jacobian transpose for extended system.
Reimplemented from NOX::Abstract::Group.
clone()
Teuchos::RCP< NOX::Abstract::Group > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Cloning function.
Implements NOX::Abstract::Group.
computeDfDpMulti()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::computeDfDpMulti (const std::vector< int > & paramIDs, NOX::Abstract::MultiVector & dfdp, bool isValidF) virtual
Compute for each parameter indexed by paramIDs. The first column of dfdp holds F, which is valid if isValidF is true. Otherwise F must be computed.
Implements LOCA::MultiContinuation::AbstractGroup.
computeF()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::computeF () virtual
Compute the turning point equation residual .
This method fills the extended residual
Implements NOX::Abstract::Group.
computeGradient()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::computeGradient () virtual
Gradient computation is not defined for this group.
Reimplemented from NOX::Abstract::Group.
computeJacobian()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::computeJacobian () virtual
Compute the blocks of the Jacobian derivative of .
This method computes the , , and blocks of the extended Jacobian:
Reimplemented from NOX::Abstract::Group.
computeNewton()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::computeNewton (Teuchos::ParameterList & params) virtual
Compute Newton direction using applyJacobianInverse().
Reimplemented from NOX::Abstract::Group.
computeX()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::computeX (const NOX::Abstract::Group & g, const NOX::Abstract::Vector & d, double step) virtual
Compute this.x = grp.x + step * d.
Implements NOX::Abstract::Group.
References conGroup, LOCA::Extended::Vector::getScalar(), and LOCA::MultiContinuation::ExtendedVector::getXVec().
copy()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::copy (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements LOCA::MultiContinuation::AbstractGroup.
References bifParamID, conGroup, globalData, parsedParams, and turningPointParams.
extractParameterComponent()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::extractParameterComponent (bool use_transpose, const NOX::Abstract::MultiVector & v, NOX::Abstract::MultiVector::DenseMatrix & v_p) const virtual
Given the vector v, extract the parameter components of all of the nested subvectors in v down to the solution component for the unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
extractSolutionComponent()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::extractSolutionComponent (const NOX::Abstract::MultiVector & v, NOX::Abstract::MultiVector & v_x) const virtual
Given the vector v, extract the underlying solution component corresponding to the unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
fillA()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::fillA (NOX::Abstract::MultiVector & A) const virtual
Fill the combined A block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
fillB()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::fillB (NOX::Abstract::MultiVector & B) const virtual
Fill the combined B block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
fillC()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::fillC (NOX::Abstract::MultiVector::DenseMatrix & C) const virtual
Fill the combined C block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
getBorderedWidth()
int LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getBorderedWidth () const virtual
Return the total width of the bordered rows/columns.
Implements LOCA::BorderedSystem::AbstractGroup.
getF()
const NOX::Abstract::Vector & LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getF () const virtual
Return extended equation residual .
Implements NOX::Abstract::Group.
getFPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getFPtr () const virtual
Return RCP to extended equation residual .
Implements NOX::Abstract::Group.
getGradient()
const NOX::Abstract::Vector & LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getGradient () const virtual
Vector returned is not valid.
Implements NOX::Abstract::Group.
getGradientPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getGradientPtr () const virtual
Vector returned is not valid.
Implements NOX::Abstract::Group.
getNewton()
const NOX::Abstract::Vector & LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getNewton () const virtual
Return extended Newton direction.
Implements NOX::Abstract::Group.
getNewtonPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getNewtonPtr () const virtual
Return RCP to extended Newton direction.
Implements NOX::Abstract::Group.
getNormF()
double LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getNormF () const virtual
Return 2-norm of .
Implements NOX::Abstract::Group.
getParam() [1/2]
double LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getParam (int paramID) const virtual
Return copy of parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParam() [2/2]
double LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getParam (std::string paramID) const virtual
Return copy of parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParams()
const LOCA::ParameterVector & LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getParams () const virtual
Return a const reference to the paramter vector owned by the group.
Implements LOCA::MultiContinuation::AbstractGroup.
getUnborderedGroup()
Teuchos::RCP< const NOX::Abstract::Group > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getUnborderedGroup () const virtual
Get bottom-level unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
getUnderlyingGroup() [1/2]
Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getUnderlyingGroup () virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getUnderlyingGroup() [2/2]
Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getUnderlyingGroup () const virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getX()
const NOX::Abstract::Vector & LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getX () const virtual
Return extended solution vector .
Implements NOX::Abstract::Group.
getXPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::getXPtr () const virtual
Return RCP to extended solution vector .
Implements NOX::Abstract::Group.
isCombinedAZero()
bool LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::isCombinedAZero () const virtual
Indicates whether combined A block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isCombinedBZero()
bool LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::isCombinedBZero () const virtual
Indicates whether combined B block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isCombinedCZero()
bool LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::isCombinedCZero () const virtual
Indicates whether combined C block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isF()
bool LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::isF () const virtual
Return true if the extended residual is valid.
Implements NOX::Abstract::Group.
isGradient()
bool LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::isGradient () const virtual
Always returns false.
Reimplemented from NOX::Abstract::Group.
isJacobian()
bool LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::isJacobian () const virtual
Return true if the extended Jacobian is valid.
Reimplemented from NOX::Abstract::Group.
isNewton()
bool LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::isNewton () const virtual
Return true if the extended Newton direction is valid.
Reimplemented from NOX::Abstract::Group.
loadNestedComponents()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::loadNestedComponents (const NOX::Abstract::MultiVector & v_x, const NOX::Abstract::MultiVector::DenseMatrix & v_p, NOX::Abstract::MultiVector & v) const virtual
Given the solution component v_x and combined parameter components v_p, distribute these components through the nested sub-vectors in v.
Implements LOCA::BorderedSystem::AbstractGroup.
operator=()
NOX::Abstract::Group & LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::operator= (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements NOX::Abstract::Group.
postProcessContinuationStep()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any postprocessing after a continuation step finishes.
The stepStatus argument indicates whether the step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
preProcessContinuationStep()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any preprocessing before a continuation step starts.
The stepStatus argument indicates whether the previous step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
printSolution() [1/2]
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::printSolution (const double conParam) const virtual
Function to print out extended solution and continuation parameter after successful continuation step.
This method prints the solution, null-vector, and parameter components of the extended solution vector using the printSolution method of the underlying group.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References NOX::Utils::StepperDetails.
printSolution() [2/2]
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::printSolution (const NOX::Abstract::Vector & x_, const double conParam) const virtual
Function to print out extended solution and continuation parameter after successful continuation step.
This method prints the solution, null-vector, and parameter components of the extended solution vector using the printSolution method of the underlying group.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::Vector::getScalar(), LOCA::MultiContinuation::ExtendedVector::getXVec(), and NOX::Utils::StepperDetails.
projectToDraw()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::projectToDraw (const NOX::Abstract::Vector & x, double * px) const virtual
Projects solution to a few scalars for multiparameter continuation.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
projectToDrawDimension()
int LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::projectToDrawDimension () const virtual
Returns the dimension of the project to draw array.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
setParam() [1/2]
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::setParam (int paramID, double val) virtual
Set parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
setParam() [2/2]
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::setParam (std::string paramID, double val) virtual
Set parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
setParams()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::setParams (const ParameterVector & p) virtual
Set the parameter vector in the group to p.
Implements LOCA::MultiContinuation::AbstractGroup.
setParamsMulti()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::setParamsMulti (const std::vector< int > & paramIDs, const NOX::Abstract::MultiVector::DenseMatrix & vals) virtual
Set parameters indexed by (integer) paramIDs.
Implements LOCA::MultiContinuation::AbstractGroup.
setX()
void LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector, x, to y.
Implements NOX::Abstract::Group.
The documentation for this class was generated from the following files:
LOCA_TurningPoint_MinimallyAugmented_ExtendedGroup.H
LOCA_TurningPoint_MinimallyAugmented_ExtendedGroup.C