NOX: LOCA::Parameter::Entry< ValueType > Class Template Reference
LOCA::Parameter::Entry< ValueType > Class Template Reference abstract
Parameter entry interface class templated on ValueType.
#include <LOCA_Parameter_Entry.H>
Public Member Functions
Entry ()
Default constructor.
virtual ~Entry ()
Destructor.
virtual void setValue (const ValueType &value)=0
Set parameter this object represents to value.
virtual ValueType getValue () const =0
Get parameter value this object represents.
virtual void setIsInLibrary ()=0
Informs entry that it is now stored in the library.
Public Member Functions inherited from LOCA::Parameter::AbstractEntry
AbstractEntry ()
Default contructor.
virtual ~AbstractEntry ()
Destructor.
Detailed Description
template<class ValueType>
class LOCA::Parameter::Entry< ValueType >
Parameter entry interface class templated on ValueType.
This class provides the interface that all parameter entry classes should implement. It is templated on the ValueType, which is the type that the underlying parameter is stored as.
Member Function Documentation
getValue()
template<class ValueType > virtual ValueType LOCA::Parameter::Entry< ValueType >::getValue () const pure virtual
Get parameter value this object represents.
Implemented in LOCA::Parameter::StandardEntry< FunctorType, ValueType >.
Referenced by LOCA::Parameter::Library::getValue().
setIsInLibrary()
template<class ValueType > virtual void LOCA::Parameter::Entry< ValueType >::setIsInLibrary () pure virtual
Informs entry that it is now stored in the library.
This is used primarily for informing the entry on how to delete itself when deleting the library.
Implemented in LOCA::Parameter::StandardEntry< FunctorType, ValueType >.
Referenced by LOCA::Parameter::Library::addParameterEntry().
setValue()
template<class ValueType > virtual void LOCA::Parameter::Entry< ValueType >::setValue (const ValueType & value) pure virtual
Set parameter this object represents to value.
Implemented in LOCA::Parameter::StandardEntry< FunctorType, ValueType >.
Referenced by LOCA::Parameter::Library::setValue().
The documentation for this class was generated from the following file:
LOCA_Parameter_Entry.H