NOX: LOCA::Pitchfork::MooreSpence::SalingerBordering Class Reference
LOCA::Pitchfork::MooreSpence::SalingerBordering Class Reference
Moore-Spence pitchfork solver strategy based on "Salinger" bordering. This is the classic 6-solve bordering method.
#include <LOCA_Pitchfork_MooreSpence_SalingerBordering.H>
Public Member Functions
SalingerBordering (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > &topParams, const Teuchos::RCP< Teuchos::ParameterList > &solverParams)
Constructor.
virtual ~SalingerBordering ()
Destructor.
virtual void setBlocks (const Teuchos::RCP< LOCA::Pitchfork::MooreSpence::AbstractGroup > &group, const Teuchos::RCP< LOCA::Pitchfork::MooreSpence::ExtendedGroup > &pfGroup, const Teuchos::RCP< const NOX::Abstract::MultiVector > &asymMultiVector, const Teuchos::RCP< const NOX::Abstract::Vector > &nullVector, const Teuchos::RCP< const NOX::Abstract::Vector > &JnVector, const Teuchos::RCP< const NOX::Abstract::Vector > &dfdp, const Teuchos::RCP< const NOX::Abstract::Vector > &dJndp)
Set blocks in extended linear system.
virtual NOX::Abstract::Group::ReturnType solve (Teuchos::ParameterList &params, const LOCA::Pitchfork::MooreSpence::ExtendedMultiVector &input, LOCA::Pitchfork::MooreSpence::ExtendedMultiVector &result) const
Solves the extended system as defined above.
Public Member Functions inherited from LOCA::Pitchfork::MooreSpence::SolverStrategy
SolverStrategy ()
Constructor.
virtual ~SolverStrategy ()
Destructor.
Protected Member Functions
NOX::Abstract::Group::ReturnType solveContiguous (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input_x, const NOX::Abstract::MultiVector &input_null, const NOX::Abstract::MultiVector::DenseMatrix &input_slack, const NOX::Abstract::MultiVector::DenseMatrix &input_param, NOX::Abstract::MultiVector &result_x, NOX::Abstract::MultiVector &result_null, NOX::Abstract::MultiVector::DenseMatrix &result_slack, NOX::Abstract::MultiVector::DenseMatrix &result_param) const
Solves equations with contiguous arguments.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data object.
Teuchos::RCP< Teuchos::ParameterList > solverParams
Solver parameters.
Teuchos::RCP< LOCA::Pitchfork::MooreSpence::AbstractGroup > group
Underlying group.
Teuchos::RCP< LOCA::Pitchfork::MooreSpence::ExtendedGroup > pfGroup
Turning point group.
Teuchos::RCP< const NOX::Abstract::MultiVector > asymMultiVector
Antisymmetric vector (psi)
Teuchos::RCP< const NOX::Abstract::Vector > asymVector
Antisymmetric vector (psi)
Teuchos::RCP< const NOX::Abstract::Vector > nullVector
Null vector.
Teuchos::RCP< const NOX::Abstract::Vector > JnVector
Jacobian times null vector.
Teuchos::RCP< const NOX::Abstract::Vector > dfdp
df/dp
Teuchos::RCP< const NOX::Abstract::Vector > dJndp
d(Jn)/dp
Detailed Description
Moore-Spence pitchfork solver strategy based on "Salinger" bordering. This is the classic 6-solve bordering method.
This class solves the Moore-Spence pitchfork Newton equations:
via the following block elimination scheme:
Constructor & Destructor Documentation
SalingerBordering()
LOCA::Pitchfork::MooreSpence::SalingerBordering::SalingerBordering (const Teuchos::RCP< LOCA::GlobalData > & global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > & topParams, const Teuchos::RCP< Teuchos::ParameterList > & solverParams)
Constructor.
Parameters
global_data [in] Global data object
topParams [in] Parsed top-level parameter list
solverParams [in] Bordered solver parameters. Currently none are referenced.
Member Function Documentation
setBlocks()
void LOCA::Pitchfork::MooreSpence::SalingerBordering::setBlocks (const Teuchos::RCP< LOCA::Pitchfork::MooreSpence::AbstractGroup > & group, const Teuchos::RCP< LOCA::Pitchfork::MooreSpence::ExtendedGroup > & pfGroup, const Teuchos::RCP< const NOX::Abstract::MultiVector > & asymMultiVector, const Teuchos::RCP< const NOX::Abstract::Vector > & nullVector, const Teuchos::RCP< const NOX::Abstract::Vector > & JnVector, const Teuchos::RCP< const NOX::Abstract::Vector > & dfdp, const Teuchos::RCP< const NOX::Abstract::Vector > & dJndp) virtual
Set blocks in extended linear system.
Parameters
group [in] Underlying group representing J
pfGroup [in] Pitchfork group representing the pitchfork equations.
asymMultiVector [in] Multivector representing the asymmetric vector
nullVector [in] Vector representing v
JnVector [in] Vector representing Jv
dfdp [in] Vector representing df/dp
dJndp [in] Vector representing d(Jv)/dp
Implements LOCA::Pitchfork::MooreSpence::SolverStrategy.
solve()
NOX::Abstract::Group::ReturnType LOCA::Pitchfork::MooreSpence::SalingerBordering::solve (Teuchos::ParameterList & params, const LOCA::Pitchfork::MooreSpence::ExtendedMultiVector & input, LOCA::Pitchfork::MooreSpence::ExtendedMultiVector & result) const virtual
Solves the extended system as defined above.
The params argument is the linear solver parameters.
Implements LOCA::Pitchfork::MooreSpence::SolverStrategy.
References LOCA::Pitchfork::MooreSpence::ExtendedMultiVector::getBifParams(), LOCA::Pitchfork::MooreSpence::ExtendedMultiVector::getNullMultiVec(), LOCA::Pitchfork::MooreSpence::ExtendedMultiVector::getSlacks(), LOCA::Pitchfork::MooreSpence::ExtendedMultiVector::getXMultiVec(), and LOCA::Extended::MultiVector::numVectors().
The documentation for this class was generated from the following files:
LOCA_Pitchfork_MooreSpence_SalingerBordering.H
LOCA_Pitchfork_MooreSpence_SalingerBordering.C