NOX: NOX::Thyra::WeightedMeritFunction Class Reference
NOX::Thyra::WeightedMeritFunction Class Reference
Implementation of merit function for implicitly weighted norm.
#include <NOX_MeritFunction_Weighted.hpp>
Public Member Functions
WeightedMeritFunction (const Teuchos::RCP< const ::Thyra::VectorBase< double > > weights, bool optimizeSlopeCalc=true)
Constructor.
WeightedMeritFunction (const WeightedMeritFunction &source)
Copy constructor.
~WeightedMeritFunction ()
Destructor.
virtual const std::string & name () const
Returns the name of the merit function.
virtual std::ostream & print (std::ostream &os, int indent=0) const
virtual double computef (const NOX::Abstract::Group &group) const
Computes the merit function, .
virtual void computeGradient (const NOX::Abstract::Group &group, NOX::Abstract::Vector &result) const
Computes the gradient of the merit function, , and returns the result in the result vector.
virtual double computeSlope (const NOX::Abstract::Vector &dir, const NOX::Abstract::Group &group) const
Computes the inner product of the given direction and the gradient associated with the merit function. Returns the steepest descent direction in the result vector.
virtual double computeQuadraticModel (const NOX::Abstract::Vector &dir, const NOX::Abstract::Group &group) const
Compute the quadratic model, , for the given merit function.
virtual void computeQuadraticMinimizer (const NOX::Abstract::Group &grp, NOX::Abstract::Vector &result) const
Computes the vector in the steepest descent direction that minimizes the quadratic model.
virtual bool computeSteepestDescentDir (const NOX::Abstract::Group &group, NOX::Abstract::Vector &result) const
Public Member Functions inherited from NOX::MeritFunction::Generic
Generic ()
Default Constructor.
virtual ~Generic ()
Destructor.
Detailed Description
Implementation of merit function for implicitly weighted norm.
NOTE: The nox vectors in this object are always unweighted (we always apply the weights explicitly)! Be careful about using norms and innerProducts from incoming nox objects as these will have the implicit weighting attached.
Member Function Documentation
computef()
double NOX::Thyra::WeightedMeritFunction::computef (const NOX::Abstract::Group & grp) const virtual
Computes the merit function, .
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::getFPtr(), and NOX::Abstract::Group::isF().
computeGradient()
void NOX::Thyra::WeightedMeritFunction::computeGradient (const NOX::Abstract::Group & group, NOX::Abstract::Vector & result) const virtual
Computes the gradient of the merit function, , and returns the result in the result vector.
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::applyJacobianTranspose(), NOX::Abstract::Group::getF(), NOX::Thyra::Vector::getThyraVector(), NOX::Abstract::Group::isF(), NOX::Abstract::Group::isJacobian(), and NOX::Abstract::Group::Ok.
computeQuadraticMinimizer()
void NOX::Thyra::WeightedMeritFunction::computeQuadraticMinimizer (const NOX::Abstract::Group & grp, NOX::Abstract::Vector & result) const virtual
Computes the vector in the steepest descent direction that minimizes the quadratic model.
The quadratic model is defined as:
where is ideally the Hessian of the merit function, , but can be approximated with the restriction that it is a symmetric and has uniform boundedness in the iterate sequence (see J. Nocedal and S. J. Wright, "Numerical Optimization", Springer, 1999. Chapters 4 and 6).
The result vector should be computed as:
Implements NOX::MeritFunction::Generic.
computeQuadraticModel()
double NOX::Thyra::WeightedMeritFunction::computeQuadraticModel (const NOX::Abstract::Vector & dir, const NOX::Abstract::Group & grp) const virtual
Compute the quadratic model, , for the given merit function.
Computes and returns :
Here represents the input parameter dir. is the Hessian of the merit function, , but can be approximated with the restriction that it is a symmetric and has uniform boundedness in the iterate sequence (see J. Nocedal and S. J. Wright, "Numerical Optimization", Springer, 1999. Chapters 4 and 6).
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::applyJacobian().
computeSlope()
double NOX::Thyra::WeightedMeritFunction::computeSlope (const NOX::Abstract::Vector & dir, const NOX::Abstract::Group & grp) const virtual
Computes the inner product of the given direction and the gradient associated with the merit function. Returns the steepest descent direction in the result vector.
Calculates and returns :
Here represents the input parameter dir and is the gradient of the merit function.
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::applyJacobian(), NOX::Abstract::Group::clone(), NOX::Abstract::Group::getF(), NOX::Abstract::Group::getX(), NOX::Abstract::Vector::norm(), NOX::Abstract::Vector::scale(), NOX::ShapeCopy, and NOX::Abstract::Vector::update().
name()
const std::string & NOX::Thyra::WeightedMeritFunction::name () const virtual
Returns the name of the merit function.
Implements NOX::MeritFunction::Generic.
The documentation for this class was generated from the following files:
NOX_MeritFunction_Weighted.hpp
NOX_MeritFunction_Weighted.cpp