NOX: LOCA::BorderedSolver::UpperTriangularBlockElimination Class Reference
LOCA::BorderedSolver::UpperTriangularBlockElimination Class Reference
Block elimination strategy for solving a block upper-triangular system.
#include <LOCA_BorderedSolver_UpperTriangularBlockElimination.H>
Public Member Functions
UpperTriangularBlockElimination (const Teuchos::RCP< LOCA::GlobalData > &global_data)
Constructor.
virtual ~UpperTriangularBlockElimination ()
Destructor.
NOX::Abstract::Group::ReturnType solve (Teuchos::ParameterList &params, const LOCA::BorderedSolver::AbstractOperator &op, const NOX::Abstract::MultiVector *A, const NOX::Abstract::MultiVector::DenseMatrix &C, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system as described above.
NOX::Abstract::Group::ReturnType solveTranspose (Teuchos::ParameterList &params, const LOCA::BorderedSolver::AbstractOperator &op, const NOX::Abstract::MultiVector *A, const NOX::Abstract::MultiVector::DenseMatrix &C, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system using the tranpose of J and C as described above.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data object.
Detailed Description
Block elimination strategy for solving a block upper-triangular system.
This class solves the extended system of equations
via block elimination:
where represents either the identity operation or the transpose. must be nonzero, while , or may be zero. The solve for the non-transposed system is implemented by the solve() method, while the solve for the transposed system is implemented by the solveTranspose() method.
Constructor & Destructor Documentation
UpperTriangularBlockElimination()
LOCA::BorderedSolver::UpperTriangularBlockElimination::UpperTriangularBlockElimination (const Teuchos::RCP< LOCA::GlobalData > & global_data)
Constructor.
Parameters
global_data [in] Global data object
Member Function Documentation
solve()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::UpperTriangularBlockElimination::solve (Teuchos::ParameterList & params, const LOCA::BorderedSolver::AbstractOperator & op, const NOX::Abstract::MultiVector * A, const NOX::Abstract::MultiVector::DenseMatrix & C, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const
Solves the extended system as described above.
Either A, F, or G may be zero by passing NULL.
References LOCA::BorderedSolver::AbstractOperator::applyInverse(), NOX::Abstract::MultiVector::clone(), NOX::DeepCopy, NOX::Abstract::Group::Failed, NOX::Abstract::MultiVector::init(), and NOX::Abstract::Group::Ok.
Referenced by LOCA::BorderedSolver::EpetraAugmented::applyInverse(), LOCA::BorderedSolver::EpetraHouseholder::applyInverse(), LOCA::BorderedSolver::TpetraHouseholder::applyInverse(), and LOCA::BorderedSolver::Bordering::applyInverse().
solveTranspose()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::UpperTriangularBlockElimination::solveTranspose (Teuchos::ParameterList & params, const LOCA::BorderedSolver::AbstractOperator & op, const NOX::Abstract::MultiVector * A, const NOX::Abstract::MultiVector::DenseMatrix & C, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const
Solves the extended system using the tranpose of J and C as described above.
Either A, F, or G may be zero by passing NULL.
References LOCA::BorderedSolver::AbstractOperator::applyInverseTranspose(), NOX::Abstract::MultiVector::clone(), NOX::DeepCopy, NOX::Abstract::Group::Failed, NOX::Abstract::MultiVector::init(), and NOX::Abstract::Group::Ok.
Referenced by LOCA::BorderedSolver::EpetraHouseholder::applyInverseTranspose(), LOCA::BorderedSolver::TpetraHouseholder::applyInverseTranspose(), and LOCA::BorderedSolver::Bordering::applyInverseTranspose().
The documentation for this class was generated from the following files:
LOCA_BorderedSolver_UpperTriangularBlockElimination.H
LOCA_BorderedSolver_UpperTriangularBlockElimination.C