NOX: NOX::Petsc::Group Class Reference
NOX::Petsc::Group Class Reference
Concrete implementation of NOX::Abstract::Group for Petsc.
#include <NOX_Petsc_Group.H>
Public Member Functions
Group (Interface &i, Vec &x, Mat &J)
Constructor.
Group (const Group &source, CopyType type=DeepCopy)
Copy constructor. If type is DeepCopy, takes ownership of valid shared Jacobian.
virtual ~Group ()
Destructor.
virtual Abstract::Group & operator= (const NOX::Abstract::Group &source)
Copies the source group into this group.
virtual Abstract::Group & operator= (const Group &source)
See above.
"Compute" functions.
virtual void setX (const Vector &y)
virtual void setX (const Abstract::Vector &y)
See above.
virtual void computeX (const Group &grp, const Vector &d, double step)
virtual void computeX (const Abstract::Group &grp, const Abstract::Vector &d, double step)
See above.
virtual Abstract::Group::ReturnType computeF ()
Compute and store F(x).
virtual Abstract::Group::ReturnType computeJacobian ()
Compute and store Jacobian.
virtual Abstract::Group::ReturnType computeGradient ()
Compute and store gradient.
virtual Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute the Newton direction, using parameters for the linear solve.
Jacobian operations.
Operations using the Jacobian matrix. These may not be defined in matrix-free scenarios.
virtual Abstract::Group::ReturnType applyJacobian (const Vector &input, Vector &result) const
virtual Abstract::Group::ReturnType applyJacobian (const Abstract::Vector &input, Abstract::Vector &result) const
See above.
virtual Abstract::Group::ReturnType applyJacobianTranspose (const Vector &input, Vector &result) const
virtual Abstract::Group::ReturnType applyJacobianTranspose (const Abstract::Vector &input, Abstract::Vector &result) const
See above.
virtual Abstract::Group::ReturnType applyRightPreconditioning (const Vector &input, Vector &result) const
Preconditions a vector using one of the available methods in Petsc.
virtual Abstract::Group::ReturnType applyRightPreconditioning (Teuchos::ParameterList &, const Abstract::Vector &input, Abstract::Vector &result) const
See above.
"Is" functions
Checks to see if various objects have been computed. Returns true if the corresponding "compute" function has been called since the last update to the solution vector (via instantiation or computeX).
virtual bool isF () const
Return true if F is valid.
virtual bool isJacobian () const
Return true if the Jacobian is valid.
virtual bool isGradient () const
Return true if the gradient is valid.
virtual bool isNewton () const
Return true if the Newton direction is valid.
virtual bool isPreconditioner () const
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobian for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianTranspose for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianInverse for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual const NOX::Abstract::Vector & getScaledX () const
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Return an internally stored group from this group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Return an internally stored group from this group.
Protected Attributes
Vectors
Vector xVector
Solution vector.
Vector RHSVector
Right-hand-side vector (function evaluation).
Vector gradVector
Gradient vector (steepest descent vector).
Vector NewtonVector
Newton direction vector.
IsValid flags
True if the current solution is up-to-date with respect to the currect xVector.
bool isValidRHS
bool isValidJacobian
bool isValidGrad
bool isValidNewton
bool isValidPreconditioner
double normRHS
Norm of RHS.
SharedJacobian * sharedJacobianPtr
Pointer to shared Jacobian matrix.
SharedJacobian & sharedJacobian
Reference to shared Jacobian matrix.
std::string jacType
Specification of Jacobian Type.
Interface & userInterface
Reference to the user supplied interface functions.
"Get" functions
Note that these function do not check whether or not the vectors are valid. Must use the "Is" functions for that purpose.
virtual const Abstract::Vector & getX () const
Return solution vector.
virtual const Abstract::Vector & getF () const
Return F(x)
virtual double getNormF () const
Return 2-norm of F(x).
virtual const Abstract::Vector & getGradient () const
Return gradient.
virtual const Abstract::Vector & getNewton () const
Return Newton direction.
virtual Teuchos::RCP< const Abstract::Vector > getXPtr () const
Return RCP to solution vector.
virtual Teuchos::RCP< const Abstract::Vector > getFPtr () const
Return RCP to F(x)
virtual Teuchos::RCP< const Abstract::Vector > getGradientPtr () const
Return RCP to gradient.
virtual Teuchos::RCP< const Abstract::Vector > getNewtonPtr () const
Return RCP to Newton direction.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (CopyType type=DeepCopy) const
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
virtual void resetIsValid ()
resets the isValid flags to false
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
Concrete implementation of NOX::Abstract::Group for Petsc.
Constructor & Destructor Documentation
~Group()
Group::~Group () virtual
Destructor.
Reimplemented from NOX::Abstract::Group.
References sharedJacobianPtr.
Member Function Documentation
applyJacobian()
Abstract::Group::ReturnType Group::applyJacobian (const Abstract::Vector & input, Abstract::Vector & result) const virtual
See above.
Reimplemented from NOX::Abstract::Group.
applyJacobianTranspose()
Abstract::Group::ReturnType Group::applyJacobianTranspose (const Abstract::Vector & input, Abstract::Vector & result) const virtual
See above.
Reimplemented from NOX::Abstract::Group.
applyRightPreconditioning()
Abstract::Group::ReturnType Group::applyRightPreconditioning (const Vector & input, Vector & result) const virtual
Preconditions a vector using one of the available methods in Petsc.
Currently, the preconditioning method corresponds to whatever is available in the user's Petsc installation and is specified in the local .petscrc file. For example, a direct solve can be accomplished by specifying -pc_type lu (serial only), whereas diagonal scaling can be achieved via -pc_type jacobi.
References NOX::Abstract::Group::BadDependency, NOX::Petsc::SharedJacobian::getJacobian(), NOX::Petsc::Vector::getPetscVector(), isJacobian(), NOX::Abstract::Group::Ok, and sharedJacobian.
Referenced by applyRightPreconditioning().
clone()
Teuchos::RCP< NOX::Abstract::Group > Group::clone (CopyType type = DeepCopy) const virtual
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
If type is NOX::DeepCopy, then we need to create an exact replica of "this". Otherwise, if type is NOX::ShapeCopy, we need only replicate the shape of "this" (only the memory is allocated, the values are not copied into the vectors and Jacobian). Returns NULL if clone is not supported.
Note
Any shared data should have its ownership transfered to this group from the source for a NOX::DeepCopy.
Implements NOX::Abstract::Group.
computeF()
Abstract::Group::ReturnType Group::computeF () virtual
Compute and store F(x).
Note
It's generally useful to also compute and store the 2-norm of F(x) at this point for later access by the getNormF() function.
Returns
NOX::Abstract::Group::Failed - If the computation fails in any way
NOX::Abstract::Group::Ok - Otherwise
Implements NOX::Abstract::Group.
References NOX::Petsc::Interface::computeF(), NOX::Petsc::Vector::getPetscVector(), isF(), NOX::Petsc::Vector::norm(), normRHS, NOX::Abstract::Group::Ok, RHSVector, userInterface, and xVector.
computeGradient()
Abstract::Group::ReturnType Group::computeGradient () virtual
Compute and store gradient.
We can pose the nonlinear equation problem as an optimization problem as follows:
In that case, the gradient (of) is defined as
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Petsc::SharedJacobian::getJacobian(), NOX::Petsc::Vector::getPetscVector(), gradVector, isF(), isGradient(), isJacobian(), NOX::Abstract::Group::Ok, RHSVector, and sharedJacobian.
computeJacobian()
Abstract::Group::ReturnType Group::computeJacobian () virtual
Compute and store Jacobian.
Recall that
The Jacobian is denoted by and defined by
Note
If this is a shared object, this group should take ownership of the Jacobian before it computes it.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Petsc::Interface::computeJacobian(), NOX::Petsc::SharedJacobian::getJacobian(), NOX::Petsc::Vector::getPetscVector(), isJacobian(), jacType, NOX::Abstract::Group::Ok, sharedJacobian, userInterface, and xVector.
computeNewton()
Abstract::Group::ReturnType Group::computeNewton (Teuchos::ParameterList & params) virtual
Compute the Newton direction, using parameters for the linear solve.
The Newton direction is the solution, s, of
The parameters are from the "Linear %Solver" sublist of the "Direction" sublist that is passed to solver during construction.
The "Tolerance" parameter may be added/modified in the sublist of "Linear Solver" parameters that is passed into this function. The solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Petsc::SharedJacobian::getJacobian(), NOX::Petsc::Vector::getPetscVector(), isF(), isJacobian(), isNewton(), NewtonVector, NOX::Abstract::Group::Ok, RHSVector, NOX::Petsc::Vector::scale(), and sharedJacobian.
computeX()
void Group::computeX (const Abstract::Group & grp, const Abstract::Vector & d, double step) virtual
See above.
Implements NOX::Abstract::Group.
getF()
const Abstract::Vector & Group::getF () const virtual
Return F(x)
Implements NOX::Abstract::Group.
References isF(), and RHSVector.
getFPtr()
Teuchos::RCP< const Abstract::Vector > Group::getFPtr () const virtual
Return RCP to F(x)
Implements NOX::Abstract::Group.
References isF(), and RHSVector.
getGradient()
const Abstract::Vector & Group::getGradient () const virtual
Return gradient.
Implements NOX::Abstract::Group.
References gradVector, and isGradient().
getGradientPtr()
Teuchos::RCP< const Abstract::Vector > Group::getGradientPtr () const virtual
Return RCP to gradient.
Implements NOX::Abstract::Group.
References gradVector, and isGradient().
getNewton()
const Abstract::Vector & Group::getNewton () const virtual
Return Newton direction.
Implements NOX::Abstract::Group.
References isNewton(), and NewtonVector.
getNewtonPtr()
Teuchos::RCP< const Abstract::Vector > Group::getNewtonPtr () const virtual
Return RCP to Newton direction.
Implements NOX::Abstract::Group.
References isNewton(), and NewtonVector.
getNormF()
double Group::getNormF () const virtual
Return 2-norm of F(x).
In other words,
Implements NOX::Abstract::Group.
References isF(), and normRHS.
getX()
const Abstract::Vector & Group::getX () const virtual
Return solution vector.
Implements NOX::Abstract::Group.
References xVector.
getXPtr()
Teuchos::RCP< const Abstract::Vector > Group::getXPtr () const virtual
Return RCP to solution vector.
Implements NOX::Abstract::Group.
References xVector.
isF()
bool Group::isF () const virtual
Return true if F is valid.
Implements NOX::Abstract::Group.
Referenced by computeF(), computeGradient(), computeNewton(), getF(), getFPtr(), and getNormF().
isGradient()
bool Group::isGradient () const virtual
Return true if the gradient is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
Referenced by computeGradient(), getGradient(), and getGradientPtr().
isJacobian()
bool Group::isJacobian () const virtual
Return true if the Jacobian is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
References NOX::Petsc::SharedJacobian::isOwner(), and sharedJacobian.
Referenced by applyRightPreconditioning(), computeGradient(), computeJacobian(), and computeNewton().
isNewton()
bool Group::isNewton () const virtual
Return true if the Newton direction is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
Referenced by computeNewton(), getNewton(), and getNewtonPtr().
operator=()
Abstract::Group & Group::operator= (const NOX::Abstract::Group & source) virtual
Copies the source group into this group.
Note
Any shared data owned by the source should have its ownership transfered to this group. This may result in a secret modification to the source object.
Implements NOX::Abstract::Group.
References operator=().
Referenced by operator=().
setX()
void Group::setX (const Abstract::Vector & y) virtual
See above.
Implements NOX::Abstract::Group.
The documentation for this class was generated from the following files:
NOX_Petsc_Group.H
NOX_Petsc_Group.C