NOX: NOX::StatusTest::RelativeNormF Class Reference
NOX::StatusTest::RelativeNormF Class Reference
Requires reduction in residual norm compared to initial norm.
#include <NOX_StatusTest_RelativeNormF.H>
Public Member Functions
RelativeNormF (double tolerance, bool scale_norms_by_vector_length=false, const NOX::Utils *u=NULL, NOX::Abstract::Vector::NormType ntype=NOX::Abstract::Vector::TwoNorm)
virtual NOX::StatusTest::StatusType checkStatus (const NOX::Solver::Generic &problem, NOX::StatusTest::CheckType checkType)
Test the stopping criterion
virtual NOX::StatusTest::StatusType getStatus () const
Return the result of the most recent checkStatus call.
virtual std::ostream & print (std::ostream &stream, int indent=0) const
Output formatted description of stopping test to output stream.
Public Member Functions inherited from NOX::StatusTest::Generic
Generic ()
Constructor.
virtual ~Generic ()
Destructor.
Detailed Description
Requires reduction in residual norm compared to initial norm.
At iteration zero, this computes and is unconverged.
Returns a converged status if , where is the nonlinear iteration number.
Member Function Documentation
checkStatus()
NOX::StatusTest::StatusType NOX::StatusTest::RelativeNormF::checkStatus (const NOX::Solver::Generic & problem, NOX::StatusTest::CheckType checkType) virtual
Test the stopping criterion
The test can (and should, if possible) be skipped if checkType is NOX::StatusType::None. If the test is skipped, then the status should be set to NOX::StatusTest::Unevaluated.
Implements NOX::StatusTest::Generic.
References NOX::StatusTest::Converged, NOX::Abstract::Group::getF(), NOX::Solver::Generic::getNumIterations(), NOX::Solver::Generic::getSolutionGroup(), NOX::Abstract::Vector::length(), NOX::StatusTest::None, NOX::Abstract::Vector::norm(), NOX::StatusTest::Unconverged, and NOX::StatusTest::Unevaluated.
getStatus()
NOX::StatusTest::StatusType NOX::StatusTest::RelativeNormF::getStatus () const virtual
Return the result of the most recent checkStatus call.
Implements NOX::StatusTest::Generic.
print()
std::ostream & NOX::StatusTest::RelativeNormF::print (std::ostream & stream, int indent = 0) const virtual
Output formatted description of stopping test to output stream.
Implements NOX::StatusTest::Generic.
References NOX::Utils::sciformat().
The documentation for this class was generated from the following files:
NOX_StatusTest_RelativeNormF.H
NOX_StatusTest_RelativeNormF.C