NOX: NOX::Direction::NonlinearCG Class Reference
NOX::Direction::NonlinearCG Class Reference
Calculates a search direction using the Nonlinear Conjugate Gradient method.
#include <NOX_Direction_NonlinearCG.H>
Public Member Functions
NonlinearCG (const Teuchos::RCP< NOX::GlobalData > &gd, Teuchos::ParameterList &params)
Constructor.
virtual ~NonlinearCG ()
Destructor.
virtual bool reset (const Teuchos::RCP< NOX::GlobalData > &gd, Teuchos::ParameterList &p)
derived
virtual bool compute (Abstract::Vector &dir, Abstract::Group &grp, const Solver::Generic &solver)
derived
virtual bool compute (NOX::Abstract::Vector &dir, NOX::Abstract::Group &grp, const NOX::Solver::LineSearchBased &solver)
Same as compute(NOX::Abstract::Vector&, NOX::Abstract::Group&, const NOX::Solver::Generic&)
Public Member Functions inherited from NOX::Direction::Generic
Generic ()
Constructor.
virtual ~Generic ()
Destructor.
Detailed Description
Calculates a search direction using the Nonlinear Conjugate Gradient method.
Calculates the direction
where is a preconditioner and is an orthogonalization parameter which can be computed in various ways (see below), and is the search direction from the previous nonlinear iteration.
This method provides a generalization of Linear CG to nonlinear problems. It does this by computing a search direction using an expression analogous to that of Linear CG. The negative of the current residual vector, is taken, allowed to be preconditioned, and then orthogonalized against the previous search direction. This direction can sometimes be used successfully with the various choices provided in NOX::Linesearch but is intended to be used with NOX::Linesearch::NonlinearCG. In fact, the expected convergence behavior of linear problems can only be achieved in this way.
To use this direction, specify that the "Method" is "NonlinearCG" in the "Direction" sublist of the parameters that are passed to the solver (see NOX::Direction::Manager for more information on choosing the search direction).
The following options may be specified in the "Nonlinear CG" sublist of the "Direction" sublist of the solver parameters.
"Orthogonalize" can be either of:
"Fletcher-Reeves" [default] -
"Polak-Ribiere" - ,
where
These comprise the two most popular choices for orthogonalization. Both reduce to the linear result for linear problems. "Polak-Ribiere" provides an implied restart capability by setting anytime the computed value is less than zero.
"Precondition" can be either "On" or "Off" [default]: determines whether or not to compute and apply preconditioner . If "Off" is selected, no preconditioner is computed and the behavior is equivalent to where is the identity matrix. If "On", is computed and applied as determined by the underlying implementation of the "applyRightPreconditioning" method in the Group.
"Restart Frequency" - An integer specification of the number of nonlinear iterations between restarts [default = 10]. Restart corresponds to setting . A good heuristic is to limit this value to the number of problem degrees of freedom. Setting this value to 1 forces for every nonlinear iteration which corresponds to suppressing orthogonalization against the previous search direction.
References
information about both linear and nonlinear conjugate gradient methods can be found in Chapter 5 of:
Nocedal & Wright, "Numerical Optimization", Springer-Verlag, New York, 1999. Though presented within the context of nonlinear optimization, the connection to nonlinear systems of equations is made by the correspondence (cf Algorithm 5.4).
Another useful useful reference is:
Jonathan Richard Shewchuk, "An Introduction to the Conjugate Gradient Method Without the Agonizing Pain</A>," 1994. Chapter 14 provides a summary of issues in generalizing linear CG to the nonlinear case. Correspondence to NOX notation is made by the equivalence (cd Section 14.1).
Member Function Documentation
compute() [1/2]
bool NonlinearCG::compute (Abstract::Vector & dir, Abstract::Group & grp, const Solver::Generic & solver) virtual
derived
Implements NOX::Direction::Generic.
References NOX::Abstract::Group::applyRightPreconditioning(), NOX::Abstract::Vector::clone(), NOX::Abstract::Group::computeF(), NOX::Abstract::Group::computeJacobian(), NOX::Abstract::Group::getF(), NOX::Solver::Generic::getNumIterations(), NOX::Solver::Generic::getPreviousSolutionGroup(), NOX::Abstract::Group::getX(), NOX::Abstract::Vector::innerProduct(), NOX::Abstract::Group::isJacobian(), NOX::Abstract::Group::Ok, NOX::Utils::OuterIteration, NOX::Abstract::Vector::scale(), NOX::ShapeCopy, NOX::Abstract::Vector::update(), and NOX::Utils::Warning.
compute() [2/2]
bool NonlinearCG::compute (NOX::Abstract::Vector & dir, NOX::Abstract::Group & grp, const NOX::Solver::LineSearchBased & solver) virtual
Same as compute(NOX::Abstract::Vector&, NOX::Abstract::Group&, const NOX::Solver::Generic&)
Enables direct support for line search based solvers for the purpose of efficiency since the LineSearchBased object has a getStep() function that some directions require.
If it is not redefined in the derived class, it will just call the compute with the NOX::Solver::Generic argument.
Reimplemented from NOX::Direction::Generic.
References NOX::Direction::Generic::compute().
reset()
bool NonlinearCG::reset (const Teuchos::RCP< NOX::GlobalData > & gd, Teuchos::ParameterList & p) virtual
derived
Implements NOX::Direction::Generic.
Referenced by NonlinearCG().
The documentation for this class was generated from the following files:
NOX_Direction_NonlinearCG.H
NOX_Direction_NonlinearCG.C