NOX: LOCA::MultiContinuation::CompositeConstraintMVDX Class Reference
LOCA::MultiContinuation::CompositeConstraintMVDX Class Reference
Implementation of LOCA::MultiContinuation::ConstraintInterfaceMVDX for composite constraints, i.e., a constraint comprised of multiple, separate constraints.
#include <LOCA_MultiContinuation_CompositeConstraintMVDX.H>
Public Member Functions
CompositeConstraintMVDX (const Teuchos::RCP< LOCA::GlobalData > &global_data, const std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterfaceMVDX > > &constraintObjects)
Constructor.
CompositeConstraintMVDX (const CompositeConstraintMVDX &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
~CompositeConstraintMVDX ()
Destructor.
Implementation of LOCA::MultiContinuation::ConstraintInterface
virtual methods
virtual void copy (const ConstraintInterface &source)
Copy.
virtual Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > clone (NOX::CopyType type=NOX::DeepCopy) const
Cloning function.
virtual NOX::Abstract::Group::ReturnType computeDX ()
Compute derivative of constraints w.r.t. solution vector x.
virtual NOX::Abstract::Group::ReturnType multiplyDX (double alpha, const NOX::Abstract::MultiVector &input_x, NOX::Abstract::MultiVector::DenseMatrix &result_p) const
Compute result_p = alpha * dg/dx * input_x.
virtual NOX::Abstract::Group::ReturnType addDX (Teuchos::ETransp transb, double alpha, const NOX::Abstract::MultiVector::DenseMatrix &b, double beta, NOX::Abstract::MultiVector &result_x) const
Compute result_x = alpha * dg/dx^T * op(b) + beta * result_x.
Public Member Functions inherited from LOCA::MultiContinuation::ConstraintInterfaceMVDX
ConstraintInterfaceMVDX ()
Constructor.
virtual ~ConstraintInterfaceMVDX ()
Destructor.
Public Member Functions inherited from LOCA::MultiContinuation::ConstraintInterface
ConstraintInterface ()
Constructor.
virtual ~ConstraintInterface ()
Destructor.
Public Member Functions inherited from LOCA::MultiContinuation::CompositeConstraint
CompositeConstraint (const Teuchos::RCP< LOCA::GlobalData > &global_data, const std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > > &constraintObjects)
Constructor.
CompositeConstraint (const CompositeConstraint &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
~CompositeConstraint ()
Destructor.
virtual int numConstraints () const
Return number of constraints.
virtual void setX (const NOX::Abstract::Vector &y)
Set the solution vector to y.
virtual void setParam (int paramID, double val)
Sets parameter indexed by paramID.
virtual void setParams (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Sets parameters indexed by paramIDs.
virtual NOX::Abstract::Group::ReturnType computeConstraints ()
Compute continuation constraint equations.
virtual NOX::Abstract::Group::ReturnType computeDP (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector::DenseMatrix &dgdp, bool isValidG)
Compute derivative of constraints w.r.t. supplied parameters.
virtual bool isConstraints () const
Return true if constraint residuals are valid.
virtual bool isDX () const
Return true if derivatives of constraints w.r.t. x are valid.
virtual const NOX::Abstract::MultiVector::DenseMatrix & getConstraints () const
Return constraint residuals.
virtual bool isDXZero () const
Return true if solution component of constraint derivatives is zero.
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any postprocessing after a continuation step finishes.
Implementation of LOCA::MultiContinuation::ConstraintInterfaceMVDX
virtual methods
std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterfaceMVDX > > constraintMVDXPtrs
Array of constraintMVDX pointers.
Teuchos::RCP< NOX::Abstract::MultiVector > compositeDX
Composite constraint derivative.
virtual const NOX::Abstract::MultiVector * getDX () const
Return solution component of constraint derivatives.
Additional Inherited Members
Protected Member Functions inherited from LOCA::MultiContinuation::CompositeConstraint
CompositeConstraint ()
Default constructor. Used by derived classes.
virtual void init (const Teuchos::RCP< LOCA::GlobalData > &global_data, const std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > > &constraintObjects)
Initialize object when using default constructor.
Protected Attributes inherited from LOCA::MultiContinuation::CompositeConstraint
Teuchos::RCP< LOCA::GlobalData > globalData
LOCA global data object.
int numConstraintObjects
Number of constraint objects.
std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > > constraintPtrs
Array of constraint pointers.
std::vector< std::vector< int > > indices
Indices of each sub-constraint in the composite constraint.
int totalNumConstraints
Total number of constraints.
NOX::Abstract::MultiVector::DenseMatrix constraints
Constraint values.
bool isValidConstraints
Flag indicating whether constraints are valid.
bool isValidDX
Flag indicating whether dg/dx is valid.
Detailed Description
Implementation of LOCA::MultiContinuation::ConstraintInterfaceMVDX for composite constraints, i.e., a constraint comprised of multiple, separate constraints.
Member Function Documentation
addDX()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraintMVDX::addDX (Teuchos::ETransp transb, double alpha, const NOX::Abstract::MultiVector::DenseMatrix & b, double beta, NOX::Abstract::MultiVector & result_x) const virtual
Compute result_x = alpha * dg/dx^T * op(b) + beta * result_x.
Note that this should be equivalent to
result_x.update(transb, alpha, dgdx, b, beta);
Reimplemented from LOCA::MultiContinuation::ConstraintInterfaceMVDX.
References LOCA::MultiContinuation::ConstraintInterfaceMVDX::addDX().
clone()
Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > LOCA::MultiContinuation::CompositeConstraintMVDX::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Cloning function.
Implements LOCA::MultiContinuation::ConstraintInterface.
computeDX()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraintMVDX::computeDX () virtual
Compute derivative of constraints w.r.t. solution vector x.
Implements LOCA::MultiContinuation::ConstraintInterface.
References NOX::Abstract::Group::Ok.
copy()
void LOCA::MultiContinuation::CompositeConstraintMVDX::copy (const ConstraintInterface & source) virtual
Copy.
Implements LOCA::MultiContinuation::ConstraintInterface.
References compositeDX, constraintMVDXPtrs, LOCA::MultiContinuation::CompositeConstraint::copy(), and NOX::DeepCopy.
getDX()
const NOX::Abstract::MultiVector * LOCA::MultiContinuation::CompositeConstraintMVDX::getDX () const virtual
Return solution component of constraint derivatives.
Implements LOCA::MultiContinuation::ConstraintInterfaceMVDX.
multiplyDX()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraintMVDX::multiplyDX (double alpha, const NOX::Abstract::MultiVector & input_x, NOX::Abstract::MultiVector::DenseMatrix & result_p) const virtual
Compute result_p = alpha * dg/dx * input_x.
Note that if there are n constraints and input_x has m columns, result_p should be a n by m matrix and is equivalent to
input_x.multiply(alpha, dgdx, result_p).
Reimplemented from LOCA::MultiContinuation::ConstraintInterfaceMVDX.
References LOCA::MultiContinuation::ConstraintInterfaceMVDX::multiplyDX().
The documentation for this class was generated from the following files:
LOCA_MultiContinuation_CompositeConstraintMVDX.H
LOCA_MultiContinuation_CompositeConstraintMVDX.C