NOX: NOX::LAPACK::Group Class Reference
NOX::LAPACK::Group Class Reference
A simple example of a group structure, based on BLAS/LAPACK.
#include <NOX_LAPACK_Group.H>
Public Member Functions
Group (Interface &i)
Constructor.
Group (const NOX::LAPACK::Group &source, NOX::CopyType type=DeepCopy)
Copy constructor.
~Group ()
Destructor.
NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Copies the source group into this group.
NOX::Abstract::Group & operator= (const NOX::LAPACK::Group &source)
See above.
"Compute" functions.
void setX (const NOX::Abstract::Vector &y)
Set the solution vector x to y.
void setX (const NOX::LAPACK::Vector &y)
See above.
void computeX (const NOX::Abstract::Group &grp, const NOX::Abstract::Vector &d, double step)
Compute x = grp.x + step * d.
void computeX (const NOX::LAPACK::Group &grp, const NOX::LAPACK::Vector &d, double step)
See above.
NOX::Abstract::Group::ReturnType computeF ()
Compute and store F(x).
NOX::Abstract::Group::ReturnType computeJacobian ()
Compute and store Jacobian.
NOX::Abstract::Group::ReturnType computeGradient ()
Compute and store gradient.
NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute the Newton direction, using parameters for the linear solve.
Jacobian operations.
Operations using the Jacobian matrix. These may not be defined in matrix-free scenarios.
NOX::Abstract::Group::ReturnType applyJacobian (const NOX::LAPACK::Vector &input, NOX::LAPACK::Vector &result) const
NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
See above.
NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::LAPACK::Vector &input, NOX::LAPACK::Vector &result) const
NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
See above.
NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::LAPACK::Vector &input, Vector &result) const
NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianInverse for multiple right-hand sides
"Is" functions
Checks to see if various objects have been computed. Returns true if the corresponding "compute" function has been called since the last update to the solution vector (via instantiation or computeX).
bool isF () const
Return true if F is valid.
bool isJacobian () const
Return true if the Jacobian is valid.
bool isGradient () const
Return true if the gradient is valid.
bool isNewton () const
Return true if the Newton direction is valid.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobian for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianTranspose for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual const NOX::Abstract::Vector & getScaledX () const
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Return an internally stored group from this group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Return an internally stored group from this group.
Protected Attributes
Vectors
NOX::LAPACK::Vector xVector
Solution vector.
NOX::LAPACK::Vector fVector
Right-hand-side vector (function evaluation).
NOX::LAPACK::Vector newtonVector
Newton direction vector.
NOX::LAPACK::Vector gradientVector
Gradient vector (steepest descent vector).
NOX::LAPACK::LinearSolver< double > jacSolver
Jacobian Matrix & LAPACK solver.
NOX::LAPACK::Interface & problemInterface
Problem interface.
IsValid flags
True if the current solution is up-to-date with respect to the currect xVector.
bool isValidF
bool isValidJacobian
bool isValidGradient
bool isValidNewton
"Get" functions
Note that these function do not check whether or not the vectors are valid. Must use the "Is" functions for that purpose.
const NOX::Abstract::Vector & getX () const
Return solution vector.
const NOX::Abstract::Vector & getF () const
Return F(x)
double getNormF () const
Return 2-norm of F(x).
const NOX::Abstract::Vector & getGradient () const
Return gradient.
const NOX::Abstract::Vector & getNewton () const
Return Newton direction.
Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const
Return RCP to solution vector.
Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const
Return RCP to F(x)
Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const
Return RCP to gradient.
Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const
Return RCP to Newton direction.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
void print () const
Print out the group.
void resetIsValid ()
resets the isValid flags to false
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
A simple example of a group structure, based on BLAS/LAPACK.
Constructor & Destructor Documentation
~Group()
NOX::LAPACK::Group::~Group () virtual
Destructor.
Reimplemented from NOX::Abstract::Group.
Member Function Documentation
applyJacobian()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::applyJacobian (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
See above.
Reimplemented from NOX::Abstract::Group.
applyJacobianInverse()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::applyJacobianInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
Computes
where is the Jacobian, is the input vector, and is the result vector.
The "Tolerance" parameter specifies that the solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If has not been computed
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
The parameter "Tolerance" may be added/modified in the list of parameters - this is the ideal solution tolerance for an iterative linear solve.
Reimplemented from NOX::Abstract::Group.
applyJacobianInverseMultiVector()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::applyJacobianInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyJacobianInverse for multiple right-hand sides
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Failed, NOX::Abstract::MultiVector::numVectors(), and NOX::Abstract::Group::Ok.
applyJacobianTranspose()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::applyJacobianTranspose (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
See above.
Reimplemented from NOX::Abstract::Group.
clone()
Teuchos::RCP< NOX::Abstract::Group > NOX::LAPACK::Group::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
If type is NOX::DeepCopy, then we need to create an exact replica of "this". Otherwise, if type is NOX::ShapeCopy, we need only replicate the shape of "this" (only the memory is allocated, the values are not copied into the vectors and Jacobian). Returns NULL if clone is not supported.
Note
Any shared data should have its ownership transfered to this group from the source for a NOX::DeepCopy.
Implements NOX::Abstract::Group.
Reimplemented in LOCA::LAPACK::Group.
computeF()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::computeF () virtual
Compute and store F(x).
Note
It's generally useful to also compute and store the 2-norm of F(x) at this point for later access by the getNormF() function.
Returns
NOX::Abstract::Group::Failed - If the computation fails in any way
NOX::Abstract::Group::Ok - Otherwise
Implements NOX::Abstract::Group.
References NOX::Abstract::Group::Failed, and NOX::Abstract::Group::Ok.
Referenced by LOCA::LAPACK::Group::computeF().
computeGradient()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::computeGradient () virtual
Compute and store gradient.
We can pose the nonlinear equation problem as an optimization problem as follows:
In that case, the gradient (of) is defined as
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::BadDependency, and NOX::Abstract::Group::Ok.
computeJacobian()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::computeJacobian () virtual
Compute and store Jacobian.
Recall that
The Jacobian is denoted by and defined by
Note
If this is a shared object, this group should take ownership of the Jacobian before it computes it.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Failed, and NOX::Abstract::Group::Ok.
Referenced by LOCA::LAPACK::Group::computeJacobian().
computeNewton()
NOX::Abstract::Group::ReturnType NOX::LAPACK::Group::computeNewton (Teuchos::ParameterList & params) virtual
Compute the Newton direction, using parameters for the linear solve.
The Newton direction is the solution, s, of
The parameters are from the "Linear %Solver" sublist of the "Direction" sublist that is passed to solver during construction.
The "Tolerance" parameter may be added/modified in the sublist of "Linear Solver" parameters that is passed into this function. The solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeX()
void NOX::LAPACK::Group::computeX (const NOX::Abstract::Group & grp, const NOX::Abstract::Vector & d, double step) virtual
Compute x = grp.x + step * d.
Let denote this group's solution vector. Let denote the result of grp.getX(). Then set
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implements NOX::Abstract::Group.
getF()
const NOX::Abstract::Vector & NOX::LAPACK::Group::getF () const virtual
Return F(x)
Implements NOX::Abstract::Group.
getFPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::LAPACK::Group::getFPtr () const virtual
Return RCP to F(x)
Implements NOX::Abstract::Group.
getGradient()
const NOX::Abstract::Vector & NOX::LAPACK::Group::getGradient () const virtual
Return gradient.
Implements NOX::Abstract::Group.
getGradientPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::LAPACK::Group::getGradientPtr () const virtual
Return RCP to gradient.
Implements NOX::Abstract::Group.
getNewton()
const NOX::Abstract::Vector & NOX::LAPACK::Group::getNewton () const virtual
Return Newton direction.
Implements NOX::Abstract::Group.
getNewtonPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::LAPACK::Group::getNewtonPtr () const virtual
Return RCP to Newton direction.
Implements NOX::Abstract::Group.
getNormF()
double NOX::LAPACK::Group::getNormF () const virtual
Return 2-norm of F(x).
In other words,
Implements NOX::Abstract::Group.
getX()
const NOX::Abstract::Vector & NOX::LAPACK::Group::getX () const virtual
Return solution vector.
Implements NOX::Abstract::Group.
getXPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::LAPACK::Group::getXPtr () const virtual
Return RCP to solution vector.
Implements NOX::Abstract::Group.
isF()
bool NOX::LAPACK::Group::isF () const virtual
Return true if F is valid.
Implements NOX::Abstract::Group.
isGradient()
bool NOX::LAPACK::Group::isGradient () const virtual
Return true if the gradient is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
isJacobian()
bool NOX::LAPACK::Group::isJacobian () const virtual
Return true if the Jacobian is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
isNewton()
bool NOX::LAPACK::Group::isNewton () const virtual
Return true if the Newton direction is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
operator=()
NOX::Abstract::Group & NOX::LAPACK::Group::operator= (const NOX::Abstract::Group & source) virtual
Copies the source group into this group.
Note
Any shared data owned by the source should have its ownership transfered to this group. This may result in a secret modification to the source object.
Implements NOX::Abstract::Group.
Referenced by LOCA::LAPACK::Group::operator=().
setX()
void NOX::LAPACK::Group::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector x to y.
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implements NOX::Abstract::Group.
The documentation for this class was generated from the following files:
NOX_LAPACK_Group.H
NOX_LAPACK_Group.C