NOX: NOX::Solver::AndersonAcceleration Class Reference
NOX::Solver::AndersonAcceleration Class Reference
Nonlinear solver based on Anderson Acceleration.
#include <NOX_Solver_AndersonAcceleration.H>
Public Member Functions
AndersonAcceleration (const Teuchos::RCP< NOX::Abstract::Group > &grp, const Teuchos::RCP< NOX::StatusTest::Generic > &tests, const Teuchos::RCP< Teuchos::ParameterList > &params)
Constructor.
virtual ~AndersonAcceleration ()
Destructor.
virtual void reset ()
Resets the solver for another solve. This resets the counters and status only. Uses the final solution from the last solve as the initial guess for the next solve.
virtual void reset (const NOX::Abstract::Vector &initialGuess)
Resets the solver and sets a new initial guess.
virtual void reset (const NOX::Abstract::Vector &initialGuess, const Teuchos::RCP< NOX::StatusTest::Generic > &tests)
Resets the solver, sets a new status test, and sets a new initial guess.
virtual NOX::StatusTest::StatusType step ()
Do one nonlinear step in the iteration sequence and return status.
virtual NOX::StatusTest::StatusType solve ()
Solve the nonlinear problem and return final status.
virtual const NOX::Abstract::Group & getSolutionGroup () const
Return a reference to the current solution group.
virtual const NOX::Abstract::Group & getPreviousSolutionGroup () const
Return a reference to the previous solution group.
virtual NOX::StatusTest::StatusType getStatus () const
Returns the current status of the solver.
virtual int getNumIterations () const
Get number of iterations.
virtual const Teuchos::ParameterList & getList () const
Return a reference to the solver parameters.
virtual double getStepSize () const
virtual Teuchos::RCP< const NOX::Abstract::Group > getSolutionGroupPtr () const
Return a RCP to the solution group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getPreviousSolutionGroupPtr () const
Return a RCP to the previous solution group.
virtual Teuchos::RCP< const Teuchos::ParameterList > getListPtr () const
Return a RCP to the solver parameters.
virtual Teuchos::RCP< const NOX::SolverStats > getSolverStatistics () const
Return a RCP to the solver statistics.
Public Member Functions inherited from NOX::Solver::Generic
Generic ()
Constructor (does nothing)
virtual ~Generic ()
Destructor (does nothing)
Protected Member Functions
virtual void init ()
Print out initialization information and calcuate the RHS.
virtual void printUpdate ()
Prints the current iteration information.
void qrAdd (NOX::Abstract::Vector &newCol)
Updates QR factors by addition of a column.
void qrDelete ()
Updates QR factors by deletion of a column.
void reorthogonalize ()
Reorthogonalized columns of Q and updates factorization.
Protected Attributes
Teuchos::RCP< NOX::GlobalData > globalDataPtr
Pointer to the global data object.
Teuchos::RCP< NOX::Utils > utilsPtr
Utils.
Teuchos::RCP< NOX::Abstract::Group > solnPtr
Current solution.
Teuchos::RCP< NOX::Abstract::Group > oldSolnPtr
Previous solution pointer.
Teuchos::RCP< NOX::StatusTest::Generic > testPtr
Stopping test.
Teuchos::RCP< Teuchos::ParameterList > paramsPtr
Input parameters.
Teuchos::RCP< NOX::LineSearch::Generic > lineSearchPtr
Linesearch.
bool precond
Flag for preconditioning.
bool recomputeJacobian
Flag to recompute Jacobian each iterate. Needed if Jacobian required to apply preconditioner.
Teuchos::RCP< NOX::Abstract::Vector > workVec
Vector for temporary storage.
Teuchos::RCP< NOX::Abstract::Vector > precF
Current preconditioned function value.
Teuchos::RCP< NOX::Abstract::Vector > oldPrecF
Previous preconditioned function value.
int storeParam
Maximum storage depth.
int nStore
Current storage depth.
double mixParam
Mixing parameter.
double stepSize
Current step.
std::vector< Teuchos::RCP< NOX::Abstract::Vector > > xMat
"Matrix" of successive iterate differences
std::vector< Teuchos::RCP< NOX::Abstract::Vector > > qMat
Q factor the for least-squares problem.
Teuchos::SerialDenseMatrix< int, double > rMat
R factor for the least-squares problem.
int nIter
Number of nonlinear iterations.
int orthoFrequency
Frequency for reorthogonalization of QR factors. If nonpositive, we never reorthogonalize.
NOX::StatusTest::StatusType status
Status of nonlinear solver.
NOX::StatusTest::CheckType checkType
Type of check to use for status tests. See NOX::StatusTest for more details.
Teuchos::RCP< NOX::Observer > observer
Pointer to a user defined NOX::Observer object.
std::vector< double > WORK
Scratch space for condition number estimation using LAPACK.
std::vector< int > IWORK
Scratch space for condition number estimation using LAPACK.
bool adjustForConditionNumber
If true, the QR matrix will be resized if the condiiton number is greater than the dropTolerance.
double dropTolerance
Value of the condition number above which the QR matrix is resized.
int accelerationStartIteration
The nonlinear iteration where Anderson Acceleration will start.
bool disableChecksForUnitTesting
Disables the storage depth size check - used for unit testing corner cases only.
Detailed Description
Nonlinear solver based on Anderson Acceleration.
Solves using Anderson Acceleration.
This method requires a mixing parameter and a preconditioner . If preconditioning is not supported, it is taken to be the identity.
For the first iteration, the solver computes .
Each iteration afterward, the solver does the following.
Set , where is a parameter that determines the maximum number of iterates for which we store iterate and function values in addition to the current iterate. represents the number of previous iterates stored currently.
Solve the least-squares problem: , such that . In this implementation, we solve an equivalent unconstrained problem for which the QR factors are stored and updated.
Calculate the new iterate: $x_{k+1} = \sum_{i=0}^{m_k} \alpha_i[x_{k-i} + \beta M(x_{k-i})F(x_{k-i})]$.
The iterations progress until the status tests (see NOX::StatusTest) determine either failure or convergence.
Input Parameters
The following parameter list entries are valid for this solver:
"Anderson Parameters" - Sublist of parameters specific to AA
"Line Search" - Sublist of the line search parameters, passed to the NOX::LineSearch::Manager constructor. Defaults to an empty list.
"Solver Options" - Sublist of general solver options.
"User Defined Pre/Post Operator" is supported. See NOX::Parameter::PrePostOperator for more details.
Output Parameters
Every time solve() is called, a sublist for output parameters called "Output" will be created and contain the following parameters.
"Output":
"Nonlinear Iterations" - Number of nonlinear iterations
"2-Norm of Residual" - Two-norm of final residual
Author
Alex Toth and Roger Pawlowski
Constructor & Destructor Documentation
AndersonAcceleration()
NOX::Solver::AndersonAcceleration::AndersonAcceleration (const Teuchos::RCP< NOX::Abstract::Group > & grp, const Teuchos::RCP< NOX::StatusTest::Generic > & tests, const Teuchos::RCP< Teuchos::ParameterList > & params)
Constructor.
See reset(NOX::Abstract::Group&, NOX::StatusTest::Generic&, Teuchos::ParameterList&) for description
References NOX::DeepCopy, globalDataPtr, init(), observer, NOX::Solver::parseObserver(), NOX::ShapeCopy, utilsPtr, and NOX::Solver::validateSolverOptionsSublist().
Member Function Documentation
getList()
const Teuchos::ParameterList & NOX::Solver::AndersonAcceleration::getList () const virtual
Return a reference to the solver parameters.
Implements NOX::Solver::Generic.
getListPtr()
virtual Teuchos::RCP< const Teuchos::ParameterList > NOX::Solver::AndersonAcceleration::getListPtr () const inline virtual
Return a RCP to the solver parameters.
Implements NOX::Solver::Generic.
References paramsPtr.
getNumIterations()
int NOX::Solver::AndersonAcceleration::getNumIterations () const virtual
Get number of iterations.
Implements NOX::Solver::Generic.
getPreviousSolutionGroup()
const NOX::Abstract::Group & NOX::Solver::AndersonAcceleration::getPreviousSolutionGroup () const virtual
Return a reference to the previous solution group.
Implements NOX::Solver::Generic.
getPreviousSolutionGroupPtr()
virtual Teuchos::RCP< const NOX::Abstract::Group > NOX::Solver::AndersonAcceleration::getPreviousSolutionGroupPtr () const inline virtual
Return a RCP to the previous solution group.
Implements NOX::Solver::Generic.
References oldSolnPtr.
getSolutionGroup()
const NOX::Abstract::Group & NOX::Solver::AndersonAcceleration::getSolutionGroup () const virtual
Return a reference to the current solution group.
Implements NOX::Solver::Generic.
getSolutionGroupPtr()
virtual Teuchos::RCP< const NOX::Abstract::Group > NOX::Solver::AndersonAcceleration::getSolutionGroupPtr () const inline virtual
Return a RCP to the solution group.
Implements NOX::Solver::Generic.
References solnPtr.
getSolverStatistics()
Teuchos::RCP< const NOX::SolverStats > NOX::Solver::AndersonAcceleration::getSolverStatistics () const virtual
Return a RCP to the solver statistics.
Implements NOX::Solver::Generic.
getStatus()
NOX::StatusTest::StatusType NOX::Solver::AndersonAcceleration::getStatus () const virtual
Returns the current status of the solver.
Implements NOX::Solver::Generic.
reset() [1/3]
void NOX::Solver::AndersonAcceleration::reset () virtual
Resets the solver for another solve. This resets the counters and status only. Uses the final solution from the last solve as the initial guess for the next solve.
NOTE: All NOX solvers will call reset() automatically at teh beginning of the solve() method. We add the reset() method to the solver interface for the application to call in case the application needs to reset counters and status manually before the next call to solve() is made.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Unconverged.
reset() [2/3]
void NOX::Solver::AndersonAcceleration::reset (const NOX::Abstract::Vector & initial_guess) virtual
Resets the solver and sets a new initial guess.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Unconverged.
reset() [3/3]
void NOX::Solver::AndersonAcceleration::reset (const NOX::Abstract::Vector & initial_guess, const Teuchos::RCP< NOX::StatusTest::Generic > & test) virtual
Resets the solver, sets a new status test, and sets a new initial guess.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Unconverged.
solve()
NOX::StatusTest::StatusType NOX::Solver::AndersonAcceleration::solve () virtual
Solve the nonlinear problem and return final status.
By "solve", we call iterate() until the NOX::StatusTest value is either NOX::StatusTest::Converged or NOX::StatusTest::Failed.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Unconverged.
step()
NOX::StatusTest::StatusType NOX::Solver::AndersonAcceleration::step () virtual
Do one nonlinear step in the iteration sequence and return status.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Converged, NOX::Utils::Details, NOX::StatusTest::Failed, NOX::Abstract::Group::Ok, NOX::StatusTest::Unconverged, and NOX::Utils::Warning.
The documentation for this class was generated from the following files:
NOX_Solver_AndersonAcceleration.H
NOX_Solver_AndersonAcceleration.C