NOX: NOX::StatusTest::Divergence Class Reference
NOX::StatusTest::Divergence Class Reference
Failure test based on a threshold value of the norm of F.
#include <NOX_StatusTest_Divergence.H>
Public Member Functions
Divergence (double thresh, int n=1)
Constructor.
virtual ~Divergence ()
Destructor.
virtual NOX::StatusTest::StatusType checkStatus (const NOX::Solver::Generic &problem, NOX::StatusTest::CheckType checkType)
Tests the stopping criterion.
virtual NOX::StatusTest::StatusType getStatus () const
Return the result of the most recent checkStatus call.
virtual std::ostream & print (std::ostream &stream, int indent=0) const
Output formatted description of stopping test to output stream.
virtual int getMaxNumSteps () const
Returns the user-specified number of steps that can consecutively fail the threshold test before the test returns a failed status.
virtual int getCurrentNumSteps () const
Returns the current number of steps that have consecutively failed the threshold test.
virtual double getThreshold () const
Returns the user-specified threshold.
Public Member Functions inherited from NOX::StatusTest::Generic
Generic ()
Constructor.
virtual ~Generic ()
Destructor.
Detailed Description
Failure test based on a threshold value of the norm of F.
This status test returns NOX::StatusTest::Failed if the norm of F exceeds a threshold value for n consecutive iterations, i.e.
for n consecutive iterations, the status is set to NOX::StatusTest::Failed and returned. Otherwise, the status is set to NOX::StatusTest::Uncoverged and returned. Both n and the threshold are specified in the constructor, by n and thresh, respectively. While a value for thresh must be provided, a default value of n = 1 is assumed.
Constructor & Destructor Documentation
Divergence()
NOX::StatusTest::Divergence::Divergence (double thresh, int n = 1)
Constructor.
Parameters
thresh - Threshold for divergence test
n - Number of consecutive nonlinear iterations
References NOX::StatusTest::Unevaluated.
Member Function Documentation
checkStatus()
NOX::StatusTest::StatusType NOX::StatusTest::Divergence::checkStatus (const NOX::Solver::Generic & problem, NOX::StatusTest::CheckType checkType) virtual
Tests the stopping criterion.
Note
The nature of this test is such that it must be executed at every nonlinear iteration, so we don't use the checkType argument.
Implements NOX::StatusTest::Generic.
References NOX::StatusTest::Failed, NOX::Abstract::Group::getNormF(), NOX::Solver::Generic::getNumIterations(), NOX::Solver::Generic::getSolutionGroup(), and NOX::StatusTest::Unconverged.
getStatus()
NOX::StatusTest::StatusType NOX::StatusTest::Divergence::getStatus () const virtual
Return the result of the most recent checkStatus call.
Implements NOX::StatusTest::Generic.
print()
std::ostream & NOX::StatusTest::Divergence::print (std::ostream & stream, int indent = 0) const virtual
Output formatted description of stopping test to output stream.
Implements NOX::StatusTest::Generic.
The documentation for this class was generated from the following files:
NOX_StatusTest_Divergence.H
NOX_StatusTest_Divergence.C