NOX: NOX::Multiphysics::Solver::FixedPointBased Class Reference
NOX::Multiphysics::Solver::FixedPointBased Class Reference
Nonlinear solver based on a line search (i.e., damping)
#include <NOX_Multiphysics_Solver_FixedPointBased.H>
Public Types
enum SOLVE_TYPE { JACOBI , SEIDEL }
Public Member Functions
FixedPointBased (const Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > &solvers, const Teuchos::RCP< NOX::Multiphysics::DataExchange::Interface > &interface, const Teuchos::RCP< NOX::StatusTest::Generic > &tests, const Teuchos::RCP< Teuchos::ParameterList > &params)
Constructor.
virtual ~FixedPointBased ()
Destructor.
virtual bool reset (const Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > &solvers, const Teuchos::RCP< NOX::Multiphysics::DataExchange::Interface > &interface, const Teuchos::RCP< NOX::StatusTest::Generic > &tests, const Teuchos::RCP< Teuchos::ParameterList > &params)
Reset the nonlinear solver for a new solve.
virtual void reset (const NOX::Abstract::Vector &initialGuess, const Teuchos::RCP< NOX::StatusTest::Generic > &tests)
virtual void reset (const NOX::Abstract::Vector &initialGuess)
Resets the solver and sets a new initial guess.
virtual void reset ()
reset methods inherited from NOX::Solver::Generic are needed here to avoid hiding this overloaded virtual method
virtual NOX::StatusTest::StatusType getStatus () const
Returns the current status of the solver.
virtual NOX::StatusTest::StatusType step ()
Do one nonlinear step in the iteration sequence and return status.
virtual NOX::StatusTest::StatusType solve ()
Solve the nonlinear problem and return final status.
virtual const NOX::Abstract::Group & getSolutionGroup () const
Return a reference to the current solution group.
virtual const NOX::Abstract::Group & getPreviousSolutionGroup () const
Return a reference to the previous solution group.
virtual int getNumIterations () const
Get number of iterations.
virtual const Teuchos::ParameterList & getList () const
Return a reference to the solver parameters.
virtual Teuchos::RCP< const NOX::Abstract::Group > getSolutionGroupPtr () const
Return a RCP to the solution group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getPreviousSolutionGroupPtr () const
Return a RCP to the previous solution group.
virtual Teuchos::RCP< const Teuchos::ParameterList > getListPtr () const
Return a RCP to the solver parameters.
virtual Teuchos::RCP< const NOX::SolverStats > getSolverStatistics () const
Return a RCP to the solver statistics.
Public Member Functions inherited from NOX::Multiphysics::Solver::Generic
Generic ()
Constructor (does nothing)
virtual ~Generic ()
Destructor (does nothing)
Public Member Functions inherited from NOX::Solver::Generic
Generic ()
Constructor (does nothing)
virtual void reset (const NOX::Abstract::Vector &initial_guess, const Teuchos::RCP< NOX::StatusTest::Generic > &test)=0
Resets the solver, sets a new status test, and sets a new initial guess.
Protected Member Functions
virtual void init ()
Print out initialization information and calcuate the RHS.
virtual void printUpdate ()
Prints the current iteration information.
Protected Attributes
SOLVE_TYPE solveType
Type of fixed-point solve to perform.
Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > solversVecPtr
Pointer to the container of solvers for each problem to be coupled.
Teuchos::RCP< NOX::Multiphysics::DataExchange::Interface > dataExInterface
Pointer to the callback interface needed to echange data among solvers.
Teuchos::RCP< NOX::GlobalData > globalDataPtr
Pointer to the global data object.
Teuchos::RCP< NOX::Utils > utilsPtr
Utils.
Teuchos::RCP< NOX::Multiphysics::Group > solnPtr
Current solution.
Teuchos::RCP< NOX::StatusTest::Generic > testPtr
Stopping test.
Teuchos::RCP< Teuchos::ParameterList > paramsPtr
Input parameters.
int nIter
Number of nonlinear iterations.
NOX::StatusTest::StatusType status
Status of nonlinear solver.
NOX::StatusTest::CheckType checkType
Type of check to use for status tests. See NOX::StatusTest for more details.
Teuchos::RCP< NOX::Observer > observer
Pointer to a user defined NOX::Observer object.
Detailed Description
Nonlinear solver based on a line search (i.e., damping)
Solves using an iterative line-search-based method.
Each iteration, the solver does the following.
Compute a search direction via a NOX::Direction method
Compute a step length and update as via a NOX::LineSearch method.
The iterations progress until the status tests (see NOX::StatusTest) determine either failure or convergence.
Note
To support several line searches and status tests, this version of the solver has a getStepSize() function that returns .
Input Parameters
The following parameter list entries are valid for this solver:
"Line Search" - Sublist of the line search parameters, passed to the NOX::LineSearch::Manager constructor. Defaults to an empty list.
"Direction" - Sublist of the direction parameters, passed to the NOX::Direction::Manager constructor. Defaults to an empty list.
"Solver Options" - Sublist of general solver options.
"User Defined Pre/Post Operator" is supported. See NOX::Parameter::PrePostOperator for more details.
Output Parameters
Every time solve() is called, a sublist for output parameters called "Output" will be created and contain the following parameters.
"Output":
"Nonlinear Iterations" - Number of nonlinear iterations
"2-Norm of Residual" - Two-norm of final residual
Author
Tammy Kolda (SNL 8950), Roger Pawlowski (SNL 9233)
Constructor & Destructor Documentation
FixedPointBased()
NOX::Multiphysics::Solver::FixedPointBased::FixedPointBased (const Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > & solvers, const Teuchos::RCP< NOX::Multiphysics::DataExchange::Interface > & interface, const Teuchos::RCP< NOX::StatusTest::Generic > & tests, const Teuchos::RCP< Teuchos::ParameterList > & params)
Constructor.
See reset(NOX::Abstract::Group&, NOX::StatusTest::Generic&, Teuchos::ParameterList&) for description
References init(), observer, paramsPtr, NOX::Solver::parseObserver(), and NOX::Solver::validateSolverOptionsSublist().
Member Function Documentation
getList()
const Teuchos::ParameterList & NOX::Multiphysics::Solver::FixedPointBased::getList () const virtual
Return a reference to the solver parameters.
Implements NOX::Solver::Generic.
getListPtr()
virtual Teuchos::RCP< const Teuchos::ParameterList > NOX::Multiphysics::Solver::FixedPointBased::getListPtr () const inline virtual
Return a RCP to the solver parameters.
Implements NOX::Solver::Generic.
References paramsPtr.
getNumIterations()
int NOX::Multiphysics::Solver::FixedPointBased::getNumIterations () const virtual
Get number of iterations.
Implements NOX::Solver::Generic.
getPreviousSolutionGroup()
const NOX::Abstract::Group & NOX::Multiphysics::Solver::FixedPointBased::getPreviousSolutionGroup () const virtual
Return a reference to the previous solution group.
Implements NOX::Solver::Generic.
getPreviousSolutionGroupPtr()
Teuchos::RCP< const NOX::Abstract::Group > NOX::Multiphysics::Solver::FixedPointBased::getPreviousSolutionGroupPtr () const virtual
Return a RCP to the previous solution group.
Implements NOX::Solver::Generic.
getSolutionGroup()
const NOX::Abstract::Group & NOX::Multiphysics::Solver::FixedPointBased::getSolutionGroup () const virtual
Return a reference to the current solution group.
Implements NOX::Solver::Generic.
getSolutionGroupPtr()
virtual Teuchos::RCP< const NOX::Abstract::Group > NOX::Multiphysics::Solver::FixedPointBased::getSolutionGroupPtr () const inline virtual
Return a RCP to the solution group.
Implements NOX::Solver::Generic.
References solnPtr.
getSolverStatistics()
Teuchos::RCP< const NOX::SolverStats > NOX::Multiphysics::Solver::FixedPointBased::getSolverStatistics () const virtual
Return a RCP to the solver statistics.
Implements NOX::Solver::Generic.
getStatus()
NOX::StatusTest::StatusType NOX::Multiphysics::Solver::FixedPointBased::getStatus () const virtual
Returns the current status of the solver.
Implements NOX::Solver::Generic.
reset() [1/4]
void NOX::Multiphysics::Solver::FixedPointBased::reset () virtual
reset methods inherited from NOX::Solver::Generic are needed here to avoid hiding this overloaded virtual method
Implements NOX::Multiphysics::Solver::Generic.
reset() [2/4]
void NOX::Multiphysics::Solver::FixedPointBased::reset (const NOX::Abstract::Vector & initial_guess) virtual
Resets the solver and sets a new initial guess.
Implements NOX::Multiphysics::Solver::Generic.
reset() [3/4]
void NOX::Multiphysics::Solver::FixedPointBased::reset (const NOX::Abstract::Vector & initialGuess, const Teuchos::RCP< NOX::StatusTest::Generic > & tests) virtual
Implements NOX::Multiphysics::Solver::Generic.
reset() [4/4]
bool NOX::Multiphysics::Solver::FixedPointBased::reset (const Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > & solvers, const Teuchos::RCP< NOX::Multiphysics::DataExchange::Interface > & interface, const Teuchos::RCP< NOX::StatusTest::Generic > & tests, const Teuchos::RCP< Teuchos::ParameterList > & params) virtual
Reset the nonlinear solver for a new solve.
Parameters
tests Status tests to check for convergence or failure. These tests will be modified by the solver.
params List of parameters. These parameters will be modified by the solver.
Note
All the objects passed to reset() will be modified.
The group object will be cloned via NOX::Abstract::Group::clone(), and the vectors within will also be individually cloned via NOX::Abstract::Vector::clone().
Warning
If the contents of grp, tests, or params are modified by the calling program after calling reset(), then the behavior of iterate() and solve() are completely undefined. To remedy this, call reset() again with the modified objects.
Implements NOX::Multiphysics::Solver::Generic.
References NOX::Solver::parseObserver(), and NOX::Solver::validateSolverOptionsSublist().
solve()
NOX::StatusTest::StatusType NOX::Multiphysics::Solver::FixedPointBased::solve () virtual
Solve the nonlinear problem and return final status.
By "solve", we call iterate() until the NOX::StatusTest value is either NOX::StatusTest::Converged or NOX::StatusTest::Failed.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Unconverged.
step()
NOX::StatusTest::StatusType NOX::Multiphysics::Solver::FixedPointBased::step () virtual
Do one nonlinear step in the iteration sequence and return status.
Implements NOX::Solver::Generic.
References NOX::StatusTest::Generic::checkStatus(), NOX::Abstract::Group::computeF(), NOX::StatusTest::Converged, NOX::StatusTest::Failed, NOX::Abstract::Group::Ok, NOX::StatusTest::Unconverged, and NOX::Utils::Warning.
The documentation for this class was generated from the following files:
NOX_Multiphysics_Solver_FixedPointBased.H
NOX_Multiphysics_Solver_FixedPointBased.C