NOX: LOCA::Epetra::AugmentedOp Class Reference
LOCA::Epetra::AugmentedOp Class Reference
Epetra operator representing a bordered matrix.
#include <LOCA_Epetra_AugmentedOp.H>
Public Member Functions
AugmentedOp (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< Epetra_Operator > &jac, const Teuchos::RCP< const Epetra_MultiVector > &a, const Teuchos::RCP< const Epetra_MultiVector > &b, const Teuchos::RCP< const NOX::Abstract::MultiVector::DenseMatrix > c)
Constructor.
virtual ~AugmentedOp ()
Destructor.
virtual int SetUseTranspose (bool UseTranspose)
If set true, transpose of this operator will be applied.
virtual int Apply (const Epetra_MultiVector &Input, Epetra_MultiVector &Result) const
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector Input in Result.
virtual int ApplyInverse (const Epetra_MultiVector &X, Epetra_MultiVector &Y) const
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector Input in Result.
virtual double NormInf () const
Returns the infinity norm of the bordered matrix.
virtual const char * Label () const
Returns a character std::string describing the operator.
virtual bool UseTranspose () const
Returns the current UseTranspose setting.
virtual bool HasNormInf () const
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
virtual const Epetra_Comm & Comm () const
Returns a reference to the Epetra_Comm communicator associated with this operator.
virtual const Epetra_Map & OperatorDomainMap () const
Returns the Epetra_Map object associated with the domain of this matrix operator.
virtual const Epetra_Map & OperatorRangeMap () const
Returns the Epetra_Map object associated with the range of this matrix operator.
virtual void init (const Epetra_MultiVector &x)
Initialiazes operator for a solve.
virtual Teuchos::RCP< Epetra_MultiVector > buildEpetraAugmentedMultiVec (const Epetra_MultiVector &x, const NOX::Abstract::MultiVector::DenseMatrix *y, bool doCopy) const
Builds an extended vector from components.
virtual void setEpetraAugmentedMultiVec (Epetra_MultiVector &x, NOX::Abstract::MultiVector::DenseMatrix &y, const Epetra_MultiVector &augMultiVec) const
Sets components from extended vector.
Protected Member Functions
void buildExtendedMap (const Epetra_BlockMap &map, Epetra_Map *&extMapPtr, bool buildImporter, bool haveParam)
Builds extended domain, range maps.
int blockMap2PointMap (const Epetra_BlockMap &BlockMap, Epetra_Map *&PointMap) const
Converts a block map to an equivalent point map.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
LOCA global data object.
std::string label
Label for operator.
Teuchos::RCP< Epetra_Operator > jacOperator
Stores operator representing .
const Epetra_BlockMap & underlyingMap
Stores underlying domain map.
const Epetra_Comm & underlyingComm
Stores comm.
Epetra_LocalMap localMap
Local map for generating Epetra matrices.
Teuchos::RCP< const Epetra_MultiVector > a
Stores pointer to a multivector.
Teuchos::RCP< const Epetra_MultiVector > b
Stores pointer to b multivector.
Epetra_MultiVector c
Stores c matrix.
int underlyingLength
Stores underlying vector local length.
int numConstraints
Number of constraints.
Epetra_Map * extendedMapPtr
Stores extended domain map.
Epetra_Map * extendedImportMapPtr
Stores extended turning point map for importing param component.
Epetra_Import * extendedImporter
Stores importer object for importing param component.
Epetra_MultiVector * importedInput
Stores imported input multivector.
Epetra_MultiVector * result_y
Stores parameter component of result multivector.
Epetra_MultiVector * tmp
Stores temporary multivector used in ApplyInverse()
bool haveParamComponent
Flag indicating whether we have the parameter component.
bool useTranspose
Flag indicating whether to use transpose of operator.
Teuchos::LAPACK< int, double > dlapack
LAPACK Wrappers.
Detailed Description
Epetra operator representing a bordered matrix.
The LOCA::Epetra::AugmentedOp is an Epetra_Operator representing the bordered matrix
where is an Epetra_Operator representing an matrix, and and are length Epetra_MultiVector's with columns, and is an dense matrix. It is assumed the Epetra_Map's for , , and are the same and the corresponding map for the bordered matrix is constructed from this map by storing the additional components on processor 0. The buildEpetraAugmentedMultiVec() method can be used to construct an Epetra_MultiVector using this map, a supplied length Epetra_MultiVector and an matrix, while setEpetraAugmentedMultiVec() splits an extended multivector into its length and components. The Apply() method performs the matrix multiplication while ApplyInverse() uses a block-elimination algorithm to compute the inverse using the ApplyInverse() method of the underlying operator . In this way, linear systems of the form
can be solved in a matrix-free mode using the Apply() method. This operator can also represent a preconditioner of the form
using the ApplyInvese() method, where is a preconditioner for . Note that if is nearly singular, the preconditioner should not be too good because otherwise the preconditining operation represented by ApplyInverse() becomes unstable.
Constructor & Destructor Documentation
AugmentedOp()
LOCA::Epetra::AugmentedOp::AugmentedOp (const Teuchos::RCP< LOCA::GlobalData > & global_data, const Teuchos::RCP< Epetra_Operator > & jac, const Teuchos::RCP< const Epetra_MultiVector > & a, const Teuchos::RCP< const Epetra_MultiVector > & b, const Teuchos::RCP< const NOX::Abstract::MultiVector::DenseMatrix > c)
Constructor.
Builds the bordered operator using the supplied operator jac and Epetra_Vector's a and b. It is assumed a, b, and jac all have the same map.
References buildExtendedMap(), extendedImporter, extendedImportMapPtr, extendedMapPtr, haveParamComponent, Epetra_Comm::MyPID(), underlyingComm, underlyingMap, and View.
Member Function Documentation
Apply()
int LOCA::Epetra::AugmentedOp::Apply (const Epetra_MultiVector & Input, Epetra_MultiVector & Result) const virtual
Returns the result of a Epetra_Operator applied to a Epetra_MultiVector Input in Result.
Computes the extended matrix-vector product
or its transpose if UseTranpose() is true.
Implements Epetra_Operator.
References Epetra_MultiVector::ExtractView(), Insert, Epetra_MultiVector::Multiply(), Epetra_MultiVector::NumVectors(), and View.
ApplyInverse()
int LOCA::Epetra::AugmentedOp::ApplyInverse (const Epetra_MultiVector & X, Epetra_MultiVector & Y) const virtual
Returns the result of a Epetra_Operator inverse applied to an Epetra_MultiVector Input in Result.
Solves the extended system
using the following block-elimination algorithm:
If UseTranpose() is true, the tranpose of the system is solved.
Implements Epetra_Operator.
References Epetra_MultiVector::ExtractView(), Insert, Epetra_MultiVector::Multiply(), Epetra_MultiVector::NumVectors(), and View.
buildEpetraAugmentedMultiVec()
Teuchos::RCP< Epetra_MultiVector > LOCA::Epetra::AugmentedOp::buildEpetraAugmentedMultiVec (const Epetra_MultiVector & x, const NOX::Abstract::MultiVector::DenseMatrix * y, bool doCopy) const virtual
Builds an extended vector from components.
Builds an extended vector using the map representing the bordered matrix. If doCopy is true, the contents of x are copied into the extended vector, otherwise only space for the extended vector is created.
References Epetra_MultiVector::NumVectors().
Referenced by LOCA::BorderedSolver::EpetraAugmented::applyInverse().
Comm()
const Epetra_Comm & LOCA::Epetra::AugmentedOp::Comm () const virtual
Returns a reference to the Epetra_Comm communicator associated with this operator.
Implements Epetra_Operator.
HasNormInf()
bool LOCA::Epetra::AugmentedOp::HasNormInf () const virtual
Returns true if the this object can provide an approximate Inf-norm, false otherwise.
Implements Epetra_Operator.
Label()
const char * LOCA::Epetra::AugmentedOp::Label () const virtual
Returns a character std::string describing the operator.
Implements Epetra_Operator.
NormInf()
double LOCA::Epetra::AugmentedOp::NormInf () const virtual
Returns the infinity norm of the bordered matrix.
This is defined only if NormInf() of the underlying operator is defined and is given by .
Implements Epetra_Operator.
OperatorDomainMap()
const Epetra_Map & LOCA::Epetra::AugmentedOp::OperatorDomainMap () const virtual
Returns the Epetra_Map object associated with the domain of this matrix operator.
Implements Epetra_Operator.
OperatorRangeMap()
const Epetra_Map & LOCA::Epetra::AugmentedOp::OperatorRangeMap () const virtual
Returns the Epetra_Map object associated with the range of this matrix operator.
Implements Epetra_Operator.
setEpetraAugmentedMultiVec()
void LOCA::Epetra::AugmentedOp::setEpetraAugmentedMultiVec (Epetra_MultiVector & x, NOX::Abstract::MultiVector::DenseMatrix & y, const Epetra_MultiVector & augMultiVec) const virtual
Sets components from extended vector.
Splits the extended vector augMultiVec into components x and y by copying values out of extVec.
References Epetra_DistObject::Import(), Insert, and Epetra_MultiVector::NumVectors().
Referenced by LOCA::BorderedSolver::EpetraAugmented::applyInverse().
SetUseTranspose()
int LOCA::Epetra::AugmentedOp::SetUseTranspose (bool UseTranspose) virtual
If set true, transpose of this operator will be applied.
Note that is only valid if the underlying operator supports a transpose.
Implements Epetra_Operator.
UseTranspose()
bool LOCA::Epetra::AugmentedOp::UseTranspose () const virtual
Returns the current UseTranspose setting.
Implements Epetra_Operator.
The documentation for this class was generated from the following files:
LOCA_Epetra_AugmentedOp.H
LOCA_Epetra_AugmentedOp.C