NOX: LOCA::MultiPredictor::Tangent Class Reference
LOCA::MultiPredictor::Tangent Class Reference
Tangent predictor strategy
#include <LOCA_MultiPredictor_Tangent.H>
Public Member Functions
Tangent (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< Teuchos::ParameterList > &predParams, const Teuchos::RCP< Teuchos::ParameterList > &solverParams)
Constructor.
virtual ~Tangent ()
Destructor.
Tangent (const Tangent &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual LOCA::MultiPredictor::AbstractStrategy & operator= (const LOCA::MultiPredictor::AbstractStrategy &source)
Assignment operator.
virtual Teuchos::RCP< LOCA::MultiPredictor::AbstractStrategy > clone (NOX::CopyType type=NOX::DeepCopy) const
Clone function.
virtual NOX::Abstract::Group::ReturnType compute (bool baseOnSecant, const std::vector< double > &stepSize, LOCA::MultiContinuation::ExtendedGroup &grp, const LOCA::MultiContinuation::ExtendedVector &prevXVec, const LOCA::MultiContinuation::ExtendedVector &xVec)
Compute the predictor given the current and previous solution vectors. Set baseOnSecant to false if the predictor orientation should not be based on the secant vector (first or last steps of a continuation run).
virtual NOX::Abstract::Group::ReturnType evaluate (const std::vector< double > &stepSize, const LOCA::MultiContinuation::ExtendedVector &xVec, LOCA::MultiContinuation::ExtendedMultiVector &result) const
Evaluate predictor with step size stepSize.
virtual NOX::Abstract::Group::ReturnType computeTangent (LOCA::MultiContinuation::ExtendedMultiVector &tangent)
Compute tangent to predictor and store in tangent.
virtual bool isTangentScalable () const
Is the tangent vector for this predictor scalable.
Public Member Functions inherited from LOCA::MultiPredictor::AbstractStrategy
AbstractStrategy ()
Constructor.
virtual ~AbstractStrategy ()
Destructor.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
LOCA global data object.
Teuchos::RCP< Teuchos::ParameterList > linSolverParams
Stores linear solver parameters.
Teuchos::RCP< NOX::Abstract::MultiVector > fdfdp
Stores derivative of residual w.r.t. parameters.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedMultiVector > tangent
Stores tangent vector.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > secant
Stores secant vector for setting orientation.
bool initialized
Flag indicating whether vectors have been initialized.
Additional Inherited Members
Protected Member Functions inherited from LOCA::MultiPredictor::AbstractStrategy
virtual void setPredictorOrientation (bool baseOnSecant, const std::vector< double > &stepSize, const LOCA::MultiContinuation::ExtendedGroup &grp, const LOCA::MultiContinuation::ExtendedVector &prevXVec, const LOCA::MultiContinuation::ExtendedVector &xVec, LOCA::MultiContinuation::ExtendedVector &secant, LOCA::MultiContinuation::ExtendedMultiVector &tangent)
Sets orientation of predictor based on parameter change from previous steps.
Detailed Description
Tangent predictor strategy
This class implements a predictor strategy based on computing the tangent to the continuation curve. If is the vector of continuation parameters, then the solution component of the tangent vectors are computed by solving
The parameter component is set to the identity matrix.
Constructor & Destructor Documentation
Tangent()
LOCA::MultiPredictor::Tangent::Tangent (const Teuchos::RCP< LOCA::GlobalData > & global_data, const Teuchos::RCP< Teuchos::ParameterList > & predParams, const Teuchos::RCP< Teuchos::ParameterList > & solverParams)
Constructor.
Parameters
global_data [in] Global data object
predParams [in] Predictor parameters. Currently no parameters are used by the Tangent predictor.
solverParams [in] Linear solver parameters used in linear solve to compute tangent vectors .
Member Function Documentation
clone()
Teuchos::RCP< LOCA::MultiPredictor::AbstractStrategy > LOCA::MultiPredictor::Tangent::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Clone function.
Implements LOCA::MultiPredictor::AbstractStrategy.
compute()
NOX::Abstract::Group::ReturnType LOCA::MultiPredictor::Tangent::compute (bool baseOnSecant, const std::vector< double > & stepSize, LOCA::MultiContinuation::ExtendedGroup & grp, const LOCA::MultiContinuation::ExtendedVector & prevXVec, const LOCA::MultiContinuation::ExtendedVector & xVec) virtual
Compute the predictor given the current and previous solution vectors. Set baseOnSecant to false if the predictor orientation should not be based on the secant vector (first or last steps of a continuation run).
This method actually implements the predictor solve described above
Implements LOCA::MultiPredictor::AbstractStrategy.
References LOCA::MultiContinuation::ExtendedVector::clone(), LOCA::Extended::Vector::createMultiVector(), LOCA::MultiContinuation::ExtendedGroup::getContinuationParameterIDs(), LOCA::MultiContinuation::ExtendedGroup::getUnderlyingGroup(), NOX::ShapeCopy, and NOX::Utils::StepperDetails.
computeTangent()
NOX::Abstract::Group::ReturnType LOCA::MultiPredictor::Tangent::computeTangent (LOCA::MultiContinuation::ExtendedMultiVector & tangent) virtual
Compute tangent to predictor and store in tangent.
Implements LOCA::MultiPredictor::AbstractStrategy.
References NOX::Abstract::Group::Ok.
evaluate()
NOX::Abstract::Group::ReturnType LOCA::MultiPredictor::Tangent::evaluate (const std::vector< double > & stepSize, const LOCA::MultiContinuation::ExtendedVector & xVec, LOCA::MultiContinuation::ExtendedMultiVector & result) const virtual
Evaluate predictor with step size stepSize.
This method computes result[i] = xVec[i] + stepSize[i] * v[i] for each i, where v[i] is the ith predictor direction.
Implements LOCA::MultiPredictor::AbstractStrategy.
References NOX::Abstract::Group::Ok.
isTangentScalable()
bool LOCA::MultiPredictor::Tangent::isTangentScalable () const virtual
Is the tangent vector for this predictor scalable.
For the tangent predictor, this always returns true.
Implements LOCA::MultiPredictor::AbstractStrategy.
operator=()
LOCA::MultiPredictor::AbstractStrategy & LOCA::MultiPredictor::Tangent::operator= (const LOCA::MultiPredictor::AbstractStrategy & source) virtual
Assignment operator.
Implements LOCA::MultiPredictor::AbstractStrategy.
References NOX::DeepCopy, fdfdp, globalData, initialized, linSolverParams, secant, and tangent.
The documentation for this class was generated from the following files:
LOCA_MultiPredictor_Tangent.H
LOCA_MultiPredictor_Tangent.C