NOX: LOCA::BorderedSolver::AbstractOperator Class Reference
LOCA::BorderedSolver::AbstractOperator Class Reference abstract
Abstract interface class representing an operator for solving bordered sets of linear equations.
#include <LOCA_BorderedSolver_AbstractOperator.H>
Public Member Functions
AbstractOperator ()
Constructor.
virtual ~AbstractOperator ()
Destructor.
virtual NOX::Abstract::Group::ReturnType apply (const NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector &Y) const =0
Apply the operator.
virtual NOX::Abstract::Group::ReturnType applyTranspose (const NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector &Y) const =0
Apply transpose of the operator.
virtual NOX::Abstract::Group::ReturnType applyInverse (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &B, NOX::Abstract::MultiVector &X) const =0
Apply inverse of the operator.
virtual NOX::Abstract::Group::ReturnType applyInverseTranspose (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &B, NOX::Abstract::MultiVector &X) const =0
Apply inverse transpose of the operator.
Detailed Description
Abstract interface class representing an operator for solving bordered sets of linear equations.
Member Function Documentation
apply()
virtual NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::AbstractOperator::apply (const NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector & Y) const pure virtual
Apply the operator.
Implemented in LOCA::BorderedSolver::BorderedOperator, LOCA::BorderedSolver::ComplexOperator, and LOCA::BorderedSolver::JacobianOperator.
applyInverse()
virtual NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::AbstractOperator::applyInverse (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & B, NOX::Abstract::MultiVector & X) const pure virtual
Apply inverse of the operator.
Implemented in LOCA::BorderedSolver::BorderedOperator, LOCA::BorderedSolver::ComplexOperator, and LOCA::BorderedSolver::JacobianOperator.
Referenced by LOCA::BorderedSolver::LowerTriangularBlockElimination::solve(), and LOCA::BorderedSolver::UpperTriangularBlockElimination::solve().
applyInverseTranspose()
virtual NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::AbstractOperator::applyInverseTranspose (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & B, NOX::Abstract::MultiVector & X) const pure virtual
Apply inverse transpose of the operator.
Implemented in LOCA::BorderedSolver::BorderedOperator, LOCA::BorderedSolver::ComplexOperator, and LOCA::BorderedSolver::JacobianOperator.
Referenced by LOCA::BorderedSolver::LowerTriangularBlockElimination::solveTranspose(), and LOCA::BorderedSolver::UpperTriangularBlockElimination::solveTranspose().
applyTranspose()
virtual NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::AbstractOperator::applyTranspose (const NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector & Y) const pure virtual
Apply transpose of the operator.
Implemented in LOCA::BorderedSolver::BorderedOperator, LOCA::BorderedSolver::ComplexOperator, and LOCA::BorderedSolver::JacobianOperator.
The documentation for this class was generated from the following file:
LOCA_BorderedSolver_AbstractOperator.H