NOX: LOCA::Extended::Vector Class Reference
LOCA::Extended::Vector Class Reference
Implemenatation of the NOX::Abstract::Vector class for extended vectors comprised of an arbitrary number of vectors and scalars.
#include <LOCA_Extended_Vector.H>
Public Member Functions
Vector (const Vector &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~Vector ()
Vector destructor.
virtual NOX::Abstract::Vector & operator= (const NOX::Abstract::Vector &y)
Assignment operator.
virtual Vector & operator= (const Vector &y)
Assignment operator.
virtual Teuchos::RCP< NOX::Abstract::Vector > clone (NOX::CopyType type=NOX::DeepCopy) const
Clone function. Applies clone to each stored vector.
virtual Teuchos::RCP< NOX::Abstract::MultiVector > createMultiVector (const NOX::Abstract::Vector *const *vecs, int numVecs, NOX::CopyType type=NOX::DeepCopy) const
Create a MultiVector with numVecs+1 columns out of an array of Vectors. The vector stored under this will be the first column with the remaining numVecs columns given by vecs.
virtual Teuchos::RCP< NOX::Abstract::MultiVector > createMultiVector (int numVecs, NOX::CopyType type=NOX::DeepCopy) const
Create a MultiVector with numVecs columns.
virtual NOX::Abstract::Vector & init (double gamma)
NOX::Abstract::Vector init function. Initializes each stored vector and scalar.
virtual NOX::Abstract::Vector & random (bool useSeed=false, int seed=1)
Initialize every element of this vector with random values.
virtual NOX::Abstract::Vector & abs (const NOX::Abstract::Vector &y)
NOX::Abstract::Vector abs function. Compues absolute value of each stored vector and scalar.
virtual NOX::Abstract::Vector & reciprocal (const NOX::Abstract::Vector &y)
NOX::Abstract::Vector reciprocal function. Computes reciprocal of each stored vector and scalar.
virtual NOX::Abstract::Vector & scale (double gamma)
NOX::Abstract::Vector scale function. Scales each stored vector and scalar.
virtual NOX::Abstract::Vector & scale (const NOX::Abstract::Vector &a)
NOX::Abstract::Vector scale function. Scales each stored vector and scalar.
virtual NOX::Abstract::Vector & update (double alpha, const NOX::Abstract::Vector &a, double gamma=0.0)
NOX::Abstract::Vector update function. Applies vector update to each stored vector and scalar.
virtual NOX::Abstract::Vector & update (double alpha, const NOX::Abstract::Vector &a, double beta, const NOX::Abstract::Vector &b, double gamma=0.0)
NOX::Abstract::Vector update function. Applies vector update to each stored vector and scalar.
virtual double norm (NormType type=TwoNorm) const
NOX::Abstract::Vector norm function. Computes norm of each stored vector and combines to compute appropriate norm.
virtual double norm (const NOX::Abstract::Vector &weights) const
NOX::Abstract::Vector weighted norm function. Computes weighted norm of each stored vector and combines to compute appropriate norm.
virtual double innerProduct (const NOX::Abstract::Vector &y) const
NOX::Abstract::Vector innerProduct function. Computes inner product * of each stored vector and combines to compute inner product.
virtual NOX::size_type length () const
NOX::Abstract::Vector length function. Computes sum of lengths of stored vectors plus number of scalars.
virtual void print (std::ostream &stream) const
NOX::Abstract::Vector print function. For debugging purposes.
virtual void setVector (int i, const NOX::Abstract::Vector &v)
Sets the ith vector.
virtual void setVectorView (int i, const Teuchos::RCP< NOX::Abstract::Vector > &v)
Sets the ith vector as a view.
virtual void setScalar (int i, double s)
Sets the ith scalar.
virtual void setScalarArray (double *sv)
Sets the scalar array.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getVector (int i) const
Returns const ref-count pointer to the ith vector.
virtual Teuchos::RCP< NOX::Abstract::Vector > getVector (int i)
Returns ref-count pointer to the ith vector.
virtual double getScalar (int i) const
Returns copy of the ith scalar.
virtual double & getScalar (int i)
Returns reference to the ith scalar.
virtual Teuchos::RCP< const NOX::Abstract::MultiVector::DenseMatrix > getScalars () const
Returns array of scalars.
virtual Teuchos::RCP< NOX::Abstract::MultiVector::DenseMatrix > getScalars ()
Returns array of scalars.
virtual int getNumScalars () const
Returns number of scalars.
virtual int getNumVectors () const
Returns number of vectors.
Public Member Functions inherited from NOX::Abstract::Vector
Vector ()
Abstract Vector constructor (does nothing)
Protected Member Functions
Vector (const Teuchos::RCP< LOCA::GlobalData > &global_data, int nvecs, int nscalars)
Vector constructor.
virtual Teuchos::RCP< LOCA::Extended::MultiVector > generateMultiVector (int nColumns, int nVectorRows, int nScalarRows) const
generate an extended multi-vector
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data.
std::vector< Teuchos::RCP< NOX::Abstract::Vector > > vectorPtrs
Array of vector pointers.
std::vector< bool > isView
Array indicating if each vector is a view.
int numScalars
Number of scalars.
Teuchos::RCP< NOX::Abstract::MultiVector::DenseMatrix > scalarsPtr
Scalars.
Friends
class LOCA::Extended::MultiVector
Declare LOCA::Extended::MultiVector as a friend class.
Additional Inherited Members
Public Types inherited from NOX::Abstract::Vector
enum NormType { TwoNorm , OneNorm , MaxNorm }
Norm types used in norm() calculations.
Detailed Description
Implemenatation of the NOX::Abstract::Vector class for extended vectors comprised of an arbitrary number of vectors and scalars.
Many continuation and bifurcation calculations can be viewed as the solution to an extended set of equations. For example, calculating a turning point can be viewed as computing a solution to where and
The extended vector is comprised of the two vectors and as well as the scalar . This class provides an implementation of the NOX::Abstract::Vector interface for such extended vectors. It stores an array of pointers to NOX::Abstract::Vector's as well as an array of scalars using the STL vector class.
The implementations of the NOX::Abstract::Vector methods are defined in terms of the implementations of each stored abstract vector.
Constructor & Destructor Documentation
~Vector()
LOCA::Extended::Vector::~Vector () virtual
Vector destructor.
Reimplemented from NOX::Abstract::Vector.
Member Function Documentation
abs()
NOX::Abstract::Vector & LOCA::Extended::Vector::abs (const NOX::Abstract::Vector & y) virtual
NOX::Abstract::Vector abs function. Compues absolute value of each stored vector and scalar.
Implements NOX::Abstract::Vector.
References scalarsPtr, and vectorPtrs.
clone()
Teuchos::RCP< NOX::Abstract::Vector > LOCA::Extended::Vector::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Clone function. Applies clone to each stored vector.
Implements NOX::Abstract::Vector.
Reimplemented in LOCA::Hopf::ComplexVector, LOCA::Hopf::MooreSpence::ExtendedVector, LOCA::MultiContinuation::ExtendedVector, LOCA::PhaseTransition::ExtendedVector, LOCA::Pitchfork::MooreSpence::ExtendedVector, and LOCA::TurningPoint::MooreSpence::ExtendedVector.
createMultiVector() [1/2]
Teuchos::RCP< NOX::Abstract::MultiVector > LOCA::Extended::Vector::createMultiVector (const NOX::Abstract::Vector *const * vecs, int numVecs, NOX::CopyType type = NOX::DeepCopy) const virtual
Create a MultiVector with numVecs+1 columns out of an array of Vectors. The vector stored under this will be the first column with the remaining numVecs columns given by vecs.
Reimplemented from NOX::Abstract::Vector.
References getScalar(), scalarsPtr, and vectorPtrs.
Referenced by LOCA::MultiPredictor::Constant::compute(), LOCA::MultiPredictor::Random::compute(), LOCA::MultiPredictor::Secant::compute(), and LOCA::MultiPredictor::Tangent::compute().
createMultiVector() [2/2]
Teuchos::RCP< NOX::Abstract::MultiVector > LOCA::Extended::Vector::createMultiVector (int numVecs, NOX::CopyType type = NOX::DeepCopy) const virtual
Create a MultiVector with numVecs columns.
Reimplemented from NOX::Abstract::Vector.
References NOX::DeepCopy.
generateMultiVector()
Teuchos::RCP< LOCA::Extended::MultiVector > LOCA::Extended::Vector::generateMultiVector (int nColumns, int nVectorRows, int nScalarRows) const protected virtual
generate an extended multi-vector
Extended vectors derived from this class should implement this method and return a multivector of the appropriate type so that the createMultiVectors method returns a multivector of the appropriate type.
Reimplemented in LOCA::Hopf::ComplexVector, LOCA::Hopf::MooreSpence::ExtendedVector, LOCA::MultiContinuation::ExtendedVector, LOCA::PhaseTransition::ExtendedVector, LOCA::Pitchfork::MooreSpence::ExtendedVector, and LOCA::TurningPoint::MooreSpence::ExtendedVector.
init()
NOX::Abstract::Vector & LOCA::Extended::Vector::init (double gamma) virtual
NOX::Abstract::Vector init function. Initializes each stored vector and scalar.
Implements NOX::Abstract::Vector.
Referenced by Vector().
innerProduct()
double LOCA::Extended::Vector::innerProduct (const NOX::Abstract::Vector & y) const virtual
NOX::Abstract::Vector innerProduct function. Computes inner product * of each stored vector and combines to compute inner product.
Implements NOX::Abstract::Vector.
References scalarsPtr, and vectorPtrs.
Referenced by LOCA::Pitchfork::MooreSpence::ExtendedGroup::lTransNorm(), and LOCA::MultiContinuation::ArcLengthGroup::scaleTangent().
length()
NOX::size_type LOCA::Extended::Vector::length () const virtual
NOX::Abstract::Vector length function. Computes sum of lengths of stored vectors plus number of scalars.
Implements NOX::Abstract::Vector.
norm() [1/2]
double LOCA::Extended::Vector::norm (const NOX::Abstract::Vector & weights) const virtual
NOX::Abstract::Vector weighted norm function. Computes weighted norm of each stored vector and combines to compute appropriate norm.
Implements NOX::Abstract::Vector.
References norm(), scalarsPtr, and vectorPtrs.
norm() [2/2]
double LOCA::Extended::Vector::norm (NormType type = TwoNorm) const virtual
NOX::Abstract::Vector norm function. Computes norm of each stored vector and combines to compute appropriate norm.
Implements NOX::Abstract::Vector.
References NOX::Abstract::Vector::MaxNorm, NOX::Abstract::Vector::OneNorm, and NOX::Abstract::Vector::TwoNorm.
Referenced by LOCA::Homotopy::DeflatedGroup::getNormNewtonSolveResidual(), LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::Hopf::MooreSpence::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::MultiContinuation::ConstrainedGroup::getNormNewtonSolveResidual(), LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::getNormNewtonSolveResidual(), and norm().
operator=() [1/2]
NOX::Abstract::Vector & LOCA::Extended::Vector::operator= (const NOX::Abstract::Vector & y) virtual
Assignment operator.
Implements NOX::Abstract::Vector.
Reimplemented in LOCA::Hopf::ComplexVector, LOCA::Hopf::MooreSpence::ExtendedVector, LOCA::MultiContinuation::ExtendedVector, LOCA::PhaseTransition::ExtendedVector, LOCA::Pitchfork::MooreSpence::ExtendedVector, and LOCA::TurningPoint::MooreSpence::ExtendedVector.
Referenced by LOCA::Hopf::ComplexVector::operator=(), LOCA::Hopf::MooreSpence::ExtendedVector::operator=(), LOCA::MultiContinuation::ExtendedVector::operator=(), LOCA::PhaseTransition::ExtendedVector::operator=(), LOCA::Pitchfork::MooreSpence::ExtendedVector::operator=(), and LOCA::TurningPoint::MooreSpence::ExtendedVector::operator=().
operator=() [2/2]
LOCA::Extended::Vector & LOCA::Extended::Vector::operator= (const Vector & y) virtual
Assignment operator.
Reimplemented in LOCA::Hopf::ComplexVector, LOCA::Hopf::MooreSpence::ExtendedVector, LOCA::MultiContinuation::ExtendedVector, LOCA::PhaseTransition::ExtendedVector, LOCA::Pitchfork::MooreSpence::ExtendedVector, and LOCA::TurningPoint::MooreSpence::ExtendedVector.
References globalData, numScalars, scalarsPtr, and vectorPtrs.
print()
void LOCA::Extended::Vector::print (std::ostream & stream) const virtual
NOX::Abstract::Vector print function. For debugging purposes.
Reimplemented from NOX::Abstract::Vector.
References print().
Referenced by print().
random()
NOX::Abstract::Vector & LOCA::Extended::Vector::random (bool useSeed = false, int seed = 1) virtual
Initialize every element of this vector with random values.
Implements NOX::Abstract::Vector.
References NOX::Random::setSeed().
reciprocal()
NOX::Abstract::Vector & LOCA::Extended::Vector::reciprocal (const NOX::Abstract::Vector & y) virtual
NOX::Abstract::Vector reciprocal function. Computes reciprocal of each stored vector and scalar.
Implements NOX::Abstract::Vector.
References scalarsPtr, and vectorPtrs.
scale() [1/2]
NOX::Abstract::Vector & LOCA::Extended::Vector::scale (const NOX::Abstract::Vector & a) virtual
NOX::Abstract::Vector scale function. Scales each stored vector and scalar.
Implements NOX::Abstract::Vector.
References scalarsPtr, scale(), and vectorPtrs.
scale() [2/2]
NOX::Abstract::Vector & LOCA::Extended::Vector::scale (double gamma) virtual
NOX::Abstract::Vector scale function. Scales each stored vector and scalar.
Implements NOX::Abstract::Vector.
References NOX::Abstract::Vector::scale().
Referenced by scale(), and LOCA::MultiContinuation::ArcLengthGroup::scaleTangent().
update() [1/2]
NOX::Abstract::Vector & LOCA::Extended::Vector::update (double alpha, const NOX::Abstract::Vector & a, double beta, const NOX::Abstract::Vector & b, double gamma = 0.0) virtual
NOX::Abstract::Vector update function. Applies vector update to each stored vector and scalar.
Implements NOX::Abstract::Vector.
References scalarsPtr, and vectorPtrs.
update() [2/2]
NOX::Abstract::Vector & LOCA::Extended::Vector::update (double alpha, const NOX::Abstract::Vector & a, double gamma = 0.0) virtual
NOX::Abstract::Vector update function. Applies vector update to each stored vector and scalar.
Implements NOX::Abstract::Vector.
References scalarsPtr, and vectorPtrs.
Referenced by LOCA::Homotopy::DeflatedGroup::computeX(), LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeX(), LOCA::Hopf::MooreSpence::ExtendedGroup::computeX(), LOCA::MultiContinuation::ConstrainedGroup::computeX(), LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup::computeX(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::computeX(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::computeX(), LOCA::Homotopy::DeflatedGroup::getNormNewtonSolveResidual(), LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::Hopf::MooreSpence::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::MultiContinuation::ConstrainedGroup::getNormNewtonSolveResidual(), LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::getNormNewtonSolveResidual(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::getNormNewtonSolveResidual(), and LOCA::MultiPredictor::AbstractStrategy::setPredictorOrientation().
The documentation for this class was generated from the following files:
LOCA_Extended_Vector.H
LOCA_Extended_Vector.C