NOX: LOCA::Eigensolver::DGGEVStrategy Class Reference
LOCA::Eigensolver::DGGEVStrategy Class Reference
LAPACK DGGEV eigensolver strategy.
#include <LOCA_Eigensolver_DGGEVStrategy.H>
Public Member Functions
DGGEVStrategy (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > &topParams, const Teuchos::RCP< Teuchos::ParameterList > &eigenParams)
Constructor.
virtual ~DGGEVStrategy ()
Destructor.
virtual NOX::Abstract::Group::ReturnType computeEigenvalues (NOX::Abstract::Group &group, Teuchos::RCP< std::vector< double > > &evals_r, Teuchos::RCP< std::vector< double > > &evals_i, Teuchos::RCP< NOX::Abstract::MultiVector > &evecs_r, Teuchos::RCP< NOX::Abstract::MultiVector > &evecs_i)
Compute eigenvalues/eigenvectors.
Public Member Functions inherited from LOCA::Eigensolver::AbstractStrategy
AbstractStrategy ()
Constructor.
virtual ~AbstractStrategy ()
Destructor.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data.
Teuchos::RCP< LOCA::Parameter::SublistParser > topParams
Parsed top-level parameter list.
Teuchos::RCP< Teuchos::ParameterList > eigenParams
Eigensolver parameter list.
int nev
The number of requested eigenvalues.
std::string which
Which eigenvalues are of interest.
Detailed Description
LAPACK DGGEV eigensolver strategy.
This class implements an eigensolver strategy using LAPACK routines DGGEV and DGEEV
Member Function Documentation
computeEigenvalues()
NOX::Abstract::Group::ReturnType LOCA::Eigensolver::DGGEVStrategy::computeEigenvalues (NOX::Abstract::Group & group, Teuchos::RCP< std::vector< double > > & evals_r, Teuchos::RCP< std::vector< double > > & evals_i, Teuchos::RCP< NOX::Abstract::MultiVector > & evecs_r, Teuchos::RCP< NOX::Abstract::MultiVector > & evecs_i) virtual
Compute eigenvalues/eigenvectors.
Implements LOCA::Eigensolver::AbstractStrategy.
References LOCA::LAPACK::Group::computeJacobian(), LOCA::LAPACK::Group::computeShiftedMatrix(), NOX::Abstract::Vector::createMultiVector(), NOX::Abstract::Group::Failed, LOCA::LAPACK::Group::getJacobianMatrix(), LOCA::LAPACK::Group::getShiftedMatrix(), NOX::Abstract::Group::getX(), NOX::LAPACK::Matrix< T >::numRows(), NOX::Abstract::Group::Ok, NOX::ShapeCopy, and NOX::Utils::StepperIteration.
The documentation for this class was generated from the following files:
LOCA_Eigensolver_DGGEVStrategy.H
LOCA_Eigensolver_DGGEVStrategy.C