NOX: NOX::MeritFunction::SumOfSquares Class Reference
NOX::MeritFunction::SumOfSquares Class Reference
Sum of squares merit function.
#include <NOX_MeritFunction_SumOfSquares.H>
Public Member Functions
SumOfSquares (const Teuchos::RCP< NOX::Utils > &u)
Constructor.
virtual ~SumOfSquares ()
Destructor.
virtual double computef (const NOX::Abstract::Group &grp) const
Computes the merit function, .
virtual void computeGradient (const NOX::Abstract::Group &group, NOX::Abstract::Vector &result) const
Computes the gradient, .
virtual double computeSlope (const NOX::Abstract::Vector &dir, const NOX::Abstract::Group &grp) const
Computes the slope, .
virtual double computeQuadraticModel (const NOX::Abstract::Vector &dir, const NOX::Abstract::Group &grp) const
Computes the quadratic model, .
virtual void computeQuadraticMinimizer (const NOX::Abstract::Group &grp, NOX::Abstract::Vector &result) const
Computes the vector in the steepest descent direction that minimizes, the quadratic model.
virtual const std::string & name () const
Returns the name of the merit function.
Public Member Functions inherited from NOX::MeritFunction::Generic
Generic ()
Default Constructor.
virtual ~Generic ()
Destructor.
Detailed Description
Sum of squares merit function.
A basic merit function used in many nonlinear equation solvers:
Where the norm is the 2-Norm using the NOX::Abstract::Vector's inner product.
This is the default merit function used in nox.
This merit function is taken from: J. E. Dennis Jr. and Robert B. Schnabel, "Numerical Methods for Unconstrained Optimization and Nonlinear Equations," Prentice Hall, 1983
Member Function Documentation
computef()
double NOX::MeritFunction::SumOfSquares::computef (const NOX::Abstract::Group & grp) const virtual
Computes the merit function, .
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::getNormF(), and NOX::Abstract::Group::isF().
computeGradient()
void NOX::MeritFunction::SumOfSquares::computeGradient (const NOX::Abstract::Group & group, NOX::Abstract::Vector & result) const virtual
Computes the gradient, .
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::applyJacobianTranspose(), NOX::Abstract::Group::getF(), NOX::Abstract::Group::isF(), NOX::Abstract::Group::isJacobian(), and NOX::Abstract::Group::Ok.
computeQuadraticMinimizer()
void NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer (const NOX::Abstract::Group & grp, NOX::Abstract::Vector & result) const virtual
Computes the vector in the steepest descent direction that minimizes, the quadratic model.
Computes the vector result:
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::applyJacobian(), NOX::Abstract::Vector::clone(), NOX::Abstract::Group::getF(), NOX::Abstract::Vector::innerProduct(), NOX::Abstract::Group::isF(), NOX::Abstract::Group::isJacobian(), NOX::Abstract::Group::Ok, NOX::Abstract::Vector::scale(), and NOX::ShapeCopy.
computeQuadraticModel()
double NOX::MeritFunction::SumOfSquares::computeQuadraticModel (const NOX::Abstract::Vector & dir, const NOX::Abstract::Group & grp) const virtual
Computes the quadratic model, .
We approximate :
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Group::applyJacobian(), NOX::Abstract::Vector::clone(), and NOX::Abstract::Group::getF().
computeSlope()
double NOX::MeritFunction::SumOfSquares::computeSlope (const NOX::Abstract::Vector & dir, const NOX::Abstract::Group & grp) const virtual
Computes the slope, .
If the Jacobian is not computed in the grp object, then the slope can be approximated using directional derivatives. More information can be found in the method computeSlopeWithoutJac.
Implements NOX::MeritFunction::Generic.
References NOX::Abstract::Vector::clone(), NOX::Abstract::Group::getF(), NOX::Abstract::Vector::innerProduct(), NOX::Abstract::Group::isGradient(), and NOX::Abstract::Group::isJacobian().
name()
const std::string & NOX::MeritFunction::SumOfSquares::name () const virtual
Returns the name of the merit function.
Implements NOX::MeritFunction::Generic.
The documentation for this class was generated from the following files:
NOX_MeritFunction_SumOfSquares.H
NOX_MeritFunction_SumOfSquares.C