NOX: NOX::Epetra::VectorSpaceL2 Class Reference
NOX::Epetra::VectorSpaceL2 Class Reference
Concrete class for an L2 vector space.
#include <NOX_Epetra_VectorSpace_L2.H>
Public Member Functions
VectorSpaceL2 ()
Constructor.
virtual ~VectorSpaceL2 ()
Destructor.
virtual double innerProduct (const Epetra_Vector &a, const Epetra_Vector &b) const
Computes the inner product: <a,b>.
virtual double norm (const Epetra_Vector &a, NOX::Abstract::Vector::NormType=NOX::Abstract::Vector::TwoNorm) const
Computes the norm.
Public Member Functions inherited from NOX::Epetra::VectorSpace
VectorSpace ()
Constructor.
virtual ~VectorSpace ()
Destructor.
Detailed Description
Concrete class for an L2 vector space.
This class allows users to override the inner product and norm used by the NOX::Epetra::Vector class. The most frequent use of this class is for introducing a weighted norm throughout NOX.
Member Function Documentation
innerProduct()
double NOX::Epetra::VectorSpaceL2::innerProduct (const Epetra_Vector & a, const Epetra_Vector & b) const virtual
Computes the inner product: <a,b>.
Implements NOX::Epetra::VectorSpace.
References Epetra_MultiVector::Dot().
norm()
double NOX::Epetra::VectorSpaceL2::norm (const Epetra_Vector & a, NOX::Abstract::Vector::NormType = NOX::Abstract::Vector::TwoNorm) const virtual
Computes the norm.
For an L2 norm, the computation is: sqrt(<a,a>).
Implements NOX::Epetra::VectorSpace.
References NOX::Abstract::Vector::MaxNorm, Epetra_MultiVector::Norm1(), Epetra_MultiVector::Norm2(), Epetra_MultiVector::NormInf(), NOX::Abstract::Vector::OneNorm, and NOX::Abstract::Vector::TwoNorm.
The documentation for this class was generated from the following files:
NOX_Epetra_VectorSpace_L2.H
NOX_Epetra_VectorSpace_L2.C