NOX: LOCA::Hopf::MinimallyAugmented::ExtendedGroup Class Reference
LOCA::Hopf::MinimallyAugmented::ExtendedGroup Class Reference
A group representing the minimally augemented Hopf equations.
#include <LOCA_Hopf_MinimallyAugmented_ExtendedGroup.H>
Public Member Functions
ExtendedGroup (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > &topParams, const Teuchos::RCP< Teuchos::ParameterList > &hpfParams, const Teuchos::RCP< LOCA::Hopf::MinimallyAugmented::AbstractGroup > &grp)
Constructor.
ExtendedGroup (const ExtendedGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~ExtendedGroup ()
Destructor.
double getBifParam () const
Get bifurcation parameter.
Implementation of NOX::Abstract::Group virtual methods
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Assignment operator.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const
Clone function.
virtual void setX (const NOX::Abstract::Vector &y)
Set the solution vector to y.
virtual void computeX (const NOX::Abstract::Group &g, const NOX::Abstract::Vector &d, double step)
Compute and return solution vector, x, where this.x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()
Compute extended continuation equations.
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute extended continuation jacobian.
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Gradient is not defined for this system.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute Newton direction for extended continuation system.
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Jacobian transpose not defined for this system.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian inverse for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Jacobian transpose not defined for this system.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian inverse for extended system.
virtual bool isF () const
Return true if extended residual is valid.
virtual bool isJacobian () const
Return true if the extended Jacobian is valid.
virtual bool isGradient () const
Always returns false.
virtual bool isNewton () const
Return true if the extended Newton direction is valid.
virtual const NOX::Abstract::Vector & getX () const
Return extended solution vector.
virtual const NOX::Abstract::Vector & getF () const
Return extended residual.
virtual double getNormF () const
Return 2-norm of extended residual.
virtual const NOX::Abstract::Vector & getGradient () const
Gradient is never valid.
virtual const NOX::Abstract::Vector & getNewton () const
Return extended Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const
Return RCP to extended solution vector.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const
Return RCP to extended residual.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const
Gradient is never valid.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const
Return RCP to extended Newton direction.
virtual double getNormNewtonSolveResidual () const
Returns 2-norm of extended Newton solve residual.
Implementation of LOCA::Extended::MultiAbstractGroup
virtual methods
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup () const
Return underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup ()
Return underlying group.
Implementation of LOCA::MultiContinuation::AbstractGroup
virtual methods
virtual void copy (const NOX::Abstract::Group &source)
Assignment operator.
virtual void setParamsMulti (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Set parameters indexed by (integer) paramIDs.
virtual void setParams (const ParameterVector &p)
Set the parameter vector in the group to p (pVector = p).
virtual void setParam (int paramID, double val)
Set parameter indexed by (integer) paramID.
virtual void setParam (std::string paramID, double val)
Set parameter indexed by (std::string) paramID.
virtual const ParameterVector & getParams () const
Return a const reference to the ParameterVector owned by the group.
virtual double getParam (int paramID) const
Return copy of parameter indexed by (integer) paramID.
virtual double getParam (std::string paramID) const
Return copy of parameter indexed by (std::string) paramID.
virtual NOX::Abstract::Group::ReturnType computeDfDpMulti (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector &dfdp, bool isValidF)
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any postprocessing after a continuation step finishes.
virtual void projectToDraw (const NOX::Abstract::Vector &x, double *px) const
Projects solution to a few scalars for multiparameter continuation.
virtual int projectToDrawDimension () const
Returns the dimension of the project to draw array.
virtual double computeScaledDotProduct (const NOX::Abstract::Vector &a, const NOX::Abstract::Vector &b) const
Compute a scaled dot product.
virtual void printSolution (const double conParam) const
Function to print out solution and parameter after successful step.
virtual void printSolution (const NOX::Abstract::Vector &x, const double conParam) const
Function to print out a vector and parameter after successful step.
virtual void scaleVector (NOX::Abstract::Vector &x) const
Scales a vector using scaling vector.
Public Member Functions inherited from LOCA::Extended::MultiAbstractGroup
MultiAbstractGroup ()
Default constructor.
virtual ~MultiAbstractGroup ()
Destructor.
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup () const
Return base-level underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup ()
Return base-level underlying group.
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual ~Group ()
Destructor.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual const NOX::Abstract::Vector & getScaledX () const
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
Public Member Functions inherited from LOCA::MultiContinuation::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::BorderedSystem::AbstractGroup
AbstractGroup ()
Constructor.
virtual ~AbstractGroup ()
Destructor.
Implementation of
LOCA::BorderedSystem::AbstractGroup virtual methods
Teuchos::RCP< LOCA::GlobalData > globalData
Pointer LOCA global data object.
Teuchos::RCP< LOCA::Parameter::SublistParser > parsedParams
Parsed top-level parameters.
Teuchos::RCP< Teuchos::ParameterList > hopfParams
Hopf parameter list.
Teuchos::RCP< LOCA::Hopf::MinimallyAugmented::AbstractGroup > grpPtr
Pointer to base group that defines .
Teuchos::RCP< LOCA::BorderedSystem::AbstractGroup > bordered_grp
Pointer to base group as a bordered group.
Teuchos::RCP< LOCA::Hopf::MinimallyAugmented::Constraint > constraintsPtr
Pointer to constraint object.
LOCA::MultiContinuation::ExtendedMultiVector xMultiVec
Stores the extended solution vector.
LOCA::MultiContinuation::ExtendedMultiVector fMultiVec
Stores the extended residual vector and df/dp.
LOCA::MultiContinuation::ExtendedMultiVector newtonMultiVec
Stores the extended Newton vector.
LOCA::MultiContinuation::ExtendedMultiVector gradientMultiVec
Stores the extended gradient vector.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > xVec
Stores view of first column of xMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > fVec
Stores view of first column of fMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedMultiVector > ffMultiVec
Stores view of first column of fMultiVec as a multivec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedMultiVector > dfdpMultiVec
Stores view of df/dp columns of fMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedMultiVector > fBifMultiVec
Stores view of f and first column of df/dp.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > newtonVec
Stores view of first column of newtonMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > gradientVec
Stores view of first column of gradientMultiVec.
Teuchos::RCP< LOCA::BorderedSolver::JacobianOperator > jacOp
Teuchos::RCP< LOCA::BorderedSolver::AbstractStrategy > borderedSolver
Stores bordered solver strategy.
std::vector< int > index_f
Stores indices for getting f part of fMultiVec.
std::vector< int > index_dfdp
Stores indices for getting df/dp part of fMultiVec.
int bifParamID
Stores the bifurcation parameter index.
bool isValidF
Is residual vector valid.
bool isValidJacobian
Is Jacobian matrix valid.
bool isValidNewton
Is Newton vector valid.
bool isValidGradient
Is Gradient vector valid.
bool isBordered
Flag that indicates whether underlying group is a bordered group.
virtual int getBorderedWidth () const
Return the total width of the bordered rows/columns.
virtual Teuchos::RCP< const NOX::Abstract::Group > getUnborderedGroup () const
Get bottom-level unbordered group.
virtual bool isCombinedAZero () const
Indicates whether combined A block is zero.
virtual bool isCombinedBZero () const
Indicates whether combined B block is zero.
virtual bool isCombinedCZero () const
Indicates whether combined C block is zero.
virtual void extractSolutionComponent (const NOX::Abstract::MultiVector &v, NOX::Abstract::MultiVector &v_x) const
virtual void extractParameterComponent (bool use_transpose, const NOX::Abstract::MultiVector &v, NOX::Abstract::MultiVector::DenseMatrix &v_p) const
virtual void loadNestedComponents (const NOX::Abstract::MultiVector &v_x, const NOX::Abstract::MultiVector::DenseMatrix &v_p, NOX::Abstract::MultiVector &v) const
virtual void fillA (NOX::Abstract::MultiVector &A) const
Fill the combined A block as described above.
virtual void fillB (NOX::Abstract::MultiVector &B) const
Fill the combined B block as described above.
virtual void fillC (NOX::Abstract::MultiVector::DenseMatrix &C) const
Fill the combined C block as described above.
virtual void resetIsValid ()
Resets all isValid flags to false.
virtual void setupViews ()
Sets up multivector views.
void setBifParam (double param)
Set bifurcation parameter.
void getInitialVectors (Teuchos::RCP< NOX::Abstract::Vector > &aVecPtr_real, Teuchos::RCP< NOX::Abstract::Vector > &aVecPtr_imag, Teuchos::RCP< NOX::Abstract::Vector > &bVecPtr_real, Teuchos::RCP< NOX::Abstract::Vector > &bVecPtr_imag, bool isSymmetric)
Computes initial "a" and "b" vectors.
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
A group representing the minimally augemented Hopf equations.
The LOCA::Hopf::MinimallyAugmented::ExtendedGroup is a concrete implementation of the NOX::Abstract::Group, LOCA::MultiContinuation::AbstractGroup and LOCA::Extended::MultiAbstractGroup that defines the following extended set of equations that are regular at a generic Hopf:
where , is the solution vector, is the bifurcation parameter, is the Hopf frequency and is a measure of the singularity of and is defined via
for any vectors and in . Using these relationships, it is easy to show
The group stores an underlying group of type LOCA::Hopf::MinimallyAugmented::AbstractGroup to represent the equations and to manipulate the underlying complex matrix . This interface defines methods for computing the derivatives and . Since LOCA is not able to deal with complex vectors and matrices directly, the real-equivalent formulation is used for all complex calculations.
This class implements all of the NOX::Abstract::Group, LOCA::MultiContinuation::AbstractGroup, and LOCA::Extended::MultiAbstractGroup methods for this extended set of equations and therefore is a complete group which can be passed to most NOX solvers to locate a single pitchfork or to the LOCA::Stepper to compute a family of pitchforks in a second parameter.
The class is intialized via the hpfParams parameter list argument to the constructor. The parameters this class recognizes are:
"Bifurcation Parameter" – [string] (Must be supplied) - Name of the bifurcation parameter
"Initial Frequency" – [double] (Must be supplied) Initial guess for the Hopf frequency .
"Bordered Solver Method" – [string] (default "Bordering") Method for solving bordered systems of equations. See LOCA::BorderedSolver::Factory for a description.
"Symmetric Jacobian" – [bool] (default: false) - Flag indicating whether Jacobian matrix is symmetric, in which case we force and therefore the second tranpose solve for is unnecessary
"Initial Null Vector Compuation" – [string] (default: "User Provided") - Method to compute initial and vectors. Valid choices are:
"User Provided" - Initial vectors are provided in the parameter list, in which case the following parameters are relevant:
"Initial Real A Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied) - Vector storing initial value for the real component of the vector
"Initial Imaginary A Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied) - Vector storing initial value for the imaginary component of the vector
"Initial Real B Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied for nonsymmetric Jacobians) - Vector storing initial value for the real component of the vector
"Initial Imaginary B Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied) - Vector storing initial value for the imaginary component of the vector
"Solve df/dp" - Compute and where is the bifurcation parameter.
"Update Null Vectors Every Continuation Step" – [bool] (default: true) - Flag indicating whether to update and vectors via and every continuation step
"Update Null Vectors Every Nonlinear Iteration" – [bool] (default: false) - Flag indicating whether to update and vectors via and every nonlinear iteration
Constructor & Destructor Documentation
ExtendedGroup()
LOCA::Hopf::MinimallyAugmented::ExtendedGroup::ExtendedGroup (const Teuchos::RCP< LOCA::GlobalData > & global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > & topParams, const Teuchos::RCP< Teuchos::ParameterList > & hpfParams, const Teuchos::RCP< LOCA::Hopf::MinimallyAugmented::AbstractGroup > & grp)
Constructor.
Parameters
global_data [in] Global data object
topParams [in] Parsed top-level parameter list.
hpfParams [in] Parameter list determining the bordered solver method.
grp [in] Group representing .
References bifParamID, bordered_grp, borderedSolver, constraintsPtr, LOCA::ParameterVector::getIndex(), getInitialVectors(), globalData, grpPtr, hopfParams, isBordered, parsedParams, setupViews(), and xVec.
Member Function Documentation
applyJacobian()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobian (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian for extended system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianInverse()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobianInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian inverse for extended system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobianInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian inverse for extended system.
Reimplemented from NOX::Abstract::Group.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
applyJacobianMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobianMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian for extended system.
Reimplemented from NOX::Abstract::Group.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
applyJacobianTranspose()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobianTranspose (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Jacobian transpose not defined for this system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianTransposeMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Jacobian transpose not defined for this system.
Reimplemented from NOX::Abstract::Group.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
clone()
Teuchos::RCP< NOX::Abstract::Group > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Clone function.
Implements NOX::Abstract::Group.
computeDfDpMulti()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeDfDpMulti (const std::vector< int > & paramIDs, NOX::Abstract::MultiVector & dfdp, bool isValidF) virtual
Compute for each parameter indexed by paramIDs. The first column of dfdp holds F, which is valid if isValidF is true. Otherwise F must be computed.
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::MultiVector::getScalars(), LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec(), and NOX::Abstract::Group::Ok.
computeF()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeF () virtual
Compute extended continuation equations.
Implements NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeGradient()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeGradient () virtual
Gradient is not defined for this system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeJacobian()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeJacobian () virtual
Compute extended continuation jacobian.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeNewton()
NOX::Abstract::Group::ReturnType LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeNewton (Teuchos::ParameterList & params) virtual
Compute Newton direction for extended continuation system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeScaledDotProduct()
double LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeScaledDotProduct (const NOX::Abstract::Vector & a, const NOX::Abstract::Vector & b) const virtual
Compute a scaled dot product.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::Vector::getScalar(), and LOCA::MultiContinuation::ExtendedVector::getXVec().
computeX()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::computeX (const NOX::Abstract::Group & g, const NOX::Abstract::Vector & d, double step) virtual
Compute and return solution vector, x, where this.x = grp.x + step * d.
Implements NOX::Abstract::Group.
References getX(), LOCA::MultiContinuation::ExtendedVector::getXVec(), grpPtr, and LOCA::Extended::Vector::update().
copy()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::copy (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements LOCA::MultiContinuation::AbstractGroup.
References bifParamID, constraintsPtr, fMultiVec, globalData, gradientMultiVec, grpPtr, hopfParams, index_dfdp, index_f, isValidF, isValidGradient, isValidJacobian, isValidNewton, newtonMultiVec, parsedParams, and xMultiVec.
extractParameterComponent()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::extractParameterComponent (bool use_transpose, const NOX::Abstract::MultiVector & v, NOX::Abstract::MultiVector::DenseMatrix & v_p) const virtual
Given the vector v, extract the parameter components of all of the nested subvectors in v down to the solution component for the unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
extractSolutionComponent()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::extractSolutionComponent (const NOX::Abstract::MultiVector & v, NOX::Abstract::MultiVector & v_x) const virtual
Given the vector v, extract the underlying solution component corresponding to the unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
References LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
fillA()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::fillA (NOX::Abstract::MultiVector & A) const virtual
Fill the combined A block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
References NOX::Abstract::MultiVector::subView().
fillB()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::fillB (NOX::Abstract::MultiVector & B) const virtual
Fill the combined B block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
References NOX::Abstract::MultiVector::subView().
fillC()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::fillC (NOX::Abstract::MultiVector::DenseMatrix & C) const virtual
Fill the combined C block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
getBorderedWidth()
int LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getBorderedWidth () const virtual
Return the total width of the bordered rows/columns.
Implements LOCA::BorderedSystem::AbstractGroup.
getF()
const NOX::Abstract::Vector & LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getF () const virtual
Return extended residual.
Implements NOX::Abstract::Group.
getFPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getFPtr () const virtual
Return RCP to extended residual.
Implements NOX::Abstract::Group.
getGradient()
const NOX::Abstract::Vector & LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getGradient () const virtual
Gradient is never valid.
Implements NOX::Abstract::Group.
getGradientPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getGradientPtr () const virtual
Gradient is never valid.
Implements NOX::Abstract::Group.
getNewton()
const NOX::Abstract::Vector & LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getNewton () const virtual
Return extended Newton direction.
Implements NOX::Abstract::Group.
getNewtonPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getNewtonPtr () const virtual
Return RCP to extended Newton direction.
Implements NOX::Abstract::Group.
getNormF()
double LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getNormF () const virtual
Return 2-norm of extended residual.
Implements NOX::Abstract::Group.
References NOX::Abstract::Vector::norm().
getParam() [1/2]
double LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getParam (int paramID) const virtual
Return copy of parameter indexed by (integer) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParam() [2/2]
double LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getParam (std::string paramID) const virtual
Return copy of parameter indexed by (std::string) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParams()
const LOCA::ParameterVector & LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getParams () const virtual
Return a const reference to the ParameterVector owned by the group.
Implements LOCA::MultiContinuation::AbstractGroup.
getUnborderedGroup()
Teuchos::RCP< const NOX::Abstract::Group > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getUnborderedGroup () const virtual
Get bottom-level unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
getUnderlyingGroup() [1/2]
Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getUnderlyingGroup () virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getUnderlyingGroup() [2/2]
Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getUnderlyingGroup () const virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getX()
const NOX::Abstract::Vector & LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getX () const virtual
Return extended solution vector.
Implements NOX::Abstract::Group.
Referenced by computeX().
getXPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getXPtr () const virtual
Return RCP to extended solution vector.
Implements NOX::Abstract::Group.
isCombinedAZero()
bool LOCA::Hopf::MinimallyAugmented::ExtendedGroup::isCombinedAZero () const virtual
Indicates whether combined A block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isCombinedBZero()
bool LOCA::Hopf::MinimallyAugmented::ExtendedGroup::isCombinedBZero () const virtual
Indicates whether combined B block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isCombinedCZero()
bool LOCA::Hopf::MinimallyAugmented::ExtendedGroup::isCombinedCZero () const virtual
Indicates whether combined C block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isF()
bool LOCA::Hopf::MinimallyAugmented::ExtendedGroup::isF () const virtual
Return true if extended residual is valid.
Implements NOX::Abstract::Group.
isGradient()
bool LOCA::Hopf::MinimallyAugmented::ExtendedGroup::isGradient () const virtual
Always returns false.
Reimplemented from NOX::Abstract::Group.
isJacobian()
bool LOCA::Hopf::MinimallyAugmented::ExtendedGroup::isJacobian () const virtual
Return true if the extended Jacobian is valid.
Reimplemented from NOX::Abstract::Group.
isNewton()
bool LOCA::Hopf::MinimallyAugmented::ExtendedGroup::isNewton () const virtual
Return true if the extended Newton direction is valid.
Reimplemented from NOX::Abstract::Group.
loadNestedComponents()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::loadNestedComponents (const NOX::Abstract::MultiVector & v_x, const NOX::Abstract::MultiVector::DenseMatrix & v_p, NOX::Abstract::MultiVector & v) const virtual
Given the solution component v_x and combined parameter components v_p, distribute these components through the nested sub-vectors in v.
Implements LOCA::BorderedSystem::AbstractGroup.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
operator=()
NOX::Abstract::Group & LOCA::Hopf::MinimallyAugmented::ExtendedGroup::operator= (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements NOX::Abstract::Group.
postProcessContinuationStep()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any postprocessing after a continuation step finishes.
The stepStatus argument indicates whether the step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
preProcessContinuationStep()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any preprocessing before a continuation step starts.
The stepStatus argument indicates whether the previous step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
printSolution() [1/2]
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::printSolution (const double conParam) const virtual
Function to print out solution and parameter after successful step.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References NOX::Utils::StepperDetails.
printSolution() [2/2]
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::printSolution (const NOX::Abstract::Vector & x, const double conParam) const virtual
Function to print out a vector and parameter after successful step.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::Vector::getScalar(), LOCA::MultiContinuation::ExtendedVector::getXVec(), and NOX::Utils::StepperDetails.
projectToDraw()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::projectToDraw (const NOX::Abstract::Vector & x, double * px) const virtual
Projects solution to a few scalars for multiparameter continuation.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::Vector::getScalar(), and LOCA::MultiContinuation::ExtendedVector::getXVec().
projectToDrawDimension()
int LOCA::Hopf::MinimallyAugmented::ExtendedGroup::projectToDrawDimension () const virtual
Returns the dimension of the project to draw array.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
scaleVector()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::scaleVector (NOX::Abstract::Vector & x) const virtual
Scales a vector using scaling vector.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::MultiContinuation::ExtendedVector::getXVec().
setParam() [1/2]
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::setParam (int paramID, double val) virtual
Set parameter indexed by (integer) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
setParam() [2/2]
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::setParam (std::string paramID, double val) virtual
Set parameter indexed by (std::string) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::ParameterVector::getIndex().
setParams()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::setParams (const ParameterVector & p) virtual
Set the parameter vector in the group to p (pVector = p).
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::ParameterVector::length().
setParamsMulti()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::setParamsMulti (const std::vector< int > & paramIDs, const NOX::Abstract::MultiVector::DenseMatrix & vals) virtual
Set parameters indexed by (integer) paramIDs.
Implements LOCA::MultiContinuation::AbstractGroup.
setX()
void LOCA::Hopf::MinimallyAugmented::ExtendedGroup::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector to y.
Implements NOX::Abstract::Group.
References LOCA::Extended::Vector::getScalar(), and LOCA::MultiContinuation::ExtendedVector::getXVec().
The documentation for this class was generated from the following files:
LOCA_Hopf_MinimallyAugmented_ExtendedGroup.H
LOCA_Hopf_MinimallyAugmented_ExtendedGroup.C