NOX: LOCA::Extended::MultiAbstractGroup Class Reference
LOCA::Extended::MultiAbstractGroup Class Reference abstract
LOCA abstract interface for extended groups, derived from the NOX::Abstract::Group, i.e., an abstract interface for "super" groups that have an underlying group component.
#include <LOCA_Extended_MultiAbstractGroup.H>
Public Member Functions
MultiAbstractGroup ()
Default constructor.
virtual ~MultiAbstractGroup ()
Destructor.
Pure virtual methods
These methods must be defined by any concrete implementation
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup () const =0
Return underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup ()=0
Return underlying group.
Virtual methods with default implementations
These methods should be overloaded in a concrete implementation if more appropriate/efficient approaches are available.
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup () const
Return base-level underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup ()
Return base-level underlying group.
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual ~Group ()
Destructor.
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)=0
Copies the source group into this group.
virtual void setX (const NOX::Abstract::Vector &y)=0
Set the solution vector x to y.
virtual void computeX (const NOX::Abstract::Group &grp, const NOX::Abstract::Vector &d, double step)=0
Compute x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()=0
Compute and store F(x).
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute and store Jacobian.
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Compute and store gradient.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute the Newton direction, using parameters for the linear solve.
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian-Transpose to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobian for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianTranspose for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianInverse for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual bool isF () const =0
Return true if F is valid.
virtual bool isJacobian () const
Return true if the Jacobian is valid.
virtual bool isGradient () const
Return true if the gradient is valid.
virtual bool isNewton () const
Return true if the Newton direction is valid.
virtual const NOX::Abstract::Vector & getX () const =0
Return solution vector.
virtual const NOX::Abstract::Vector & getScaledX () const
virtual const NOX::Abstract::Vector & getF () const =0
Return F(x)
virtual double getNormF () const =0
Return 2-norm of F(x).
virtual const NOX::Abstract::Vector & getGradient () const =0
Return gradient.
virtual const NOX::Abstract::Vector & getNewton () const =0
Return Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const =0
Return RCP to solution vector.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const =0
Return RCP to F(x)
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const =0
Return RCP to gradient.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const =0
Return RCP to Newton direction.
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const =0
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
LOCA abstract interface for extended groups, derived from the NOX::Abstract::Group, i.e., an abstract interface for "super" groups that have an underlying group component.
Concrete implemenations of this interface must provide implementations of all of the methods in the NOX::Abstract::Group interface as well as the additional interface defined here.
Member Function Documentation
getBaseLevelUnderlyingGroup() [1/2]
Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > LOCA::Extended::MultiAbstractGroup::getBaseLevelUnderlyingGroup () virtual
Return base-level underlying group.
This method is intended for composite groups (such as extended bifurcation groups) which have an underlying group as a data member. This method is supposed to return the base level group and has a default recursive implementation that should work in most cases.
getBaseLevelUnderlyingGroup() [2/2]
Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > LOCA::Extended::MultiAbstractGroup::getBaseLevelUnderlyingGroup () const virtual
Return base-level underlying group.
This method is intended for composite groups (such as extended bifurcation groups) which have an underlying group as a data member. This method is supposed to return the base level group and has a default recursive implementation that should work in most cases.
References getUnderlyingGroup().
getNestedGroup() [1/2]
Teuchos::RCP< NOX::Abstract::Group > LOCA::Extended::MultiAbstractGroup::getNestedGroup () virtual
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
Reimplemented from NOX::Abstract::Group.
getNestedGroup() [2/2]
Teuchos::RCP< const NOX::Abstract::Group > LOCA::Extended::MultiAbstractGroup::getNestedGroup () const virtual
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
Reimplemented from NOX::Abstract::Group.
getUnderlyingGroup() [1/2]
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > LOCA::Extended::MultiAbstractGroup::getUnderlyingGroup () const pure virtual
Return underlying group.
This method should the underlying group data member.
Implemented in LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, and LOCA::TurningPoint::MooreSpence::ExtendedGroup.
Referenced by LOCA::Solver::Wrapper::resetWrapper().
getUnderlyingGroup() [2/2]
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > LOCA::Extended::MultiAbstractGroup::getUnderlyingGroup () pure virtual
Return underlying group.
This method should the underlying group data member.
Implemented in LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, and LOCA::TurningPoint::MooreSpence::ExtendedGroup.
Referenced by getBaseLevelUnderlyingGroup().
The documentation for this class was generated from the following files:
LOCA_Extended_MultiAbstractGroup.H
LOCA_Extended_MultiAbstractGroup.C