NOX: LOCA::BorderedSolver::LowerTriangularBlockElimination Class Reference
LOCA::BorderedSolver::LowerTriangularBlockElimination Class Reference
Block elimination strategy for solving a block lower-triangular system.
#include <LOCA_BorderedSolver_LowerTriangularBlockElimination.H>
Public Member Functions
LowerTriangularBlockElimination (const Teuchos::RCP< LOCA::GlobalData > &global_data)
Constructor.
virtual ~LowerTriangularBlockElimination ()
Destructor.
NOX::Abstract::Group::ReturnType solve (Teuchos::ParameterList &params, const LOCA::BorderedSolver::AbstractOperator &op, const LOCA::MultiContinuation::ConstraintInterface &B, const NOX::Abstract::MultiVector::DenseMatrix &C, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system as described above with B specified as a LOCA::MultiContinuation::ConstraintInterface object.
NOX::Abstract::Group::ReturnType solve (Teuchos::ParameterList &params, const LOCA::BorderedSolver::AbstractOperator &op, const NOX::Abstract::MultiVector &B, const NOX::Abstract::MultiVector::DenseMatrix &C, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system as described above with B specified as a NOX::Abstract::MultiVector.
NOX::Abstract::Group::ReturnType solveTranspose (Teuchos::ParameterList &params, const LOCA::BorderedSolver::AbstractOperator &op, const LOCA::MultiContinuation::ConstraintInterface &B, const NOX::Abstract::MultiVector::DenseMatrix &C, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system using the tranpose of J and C as described above with B specified as a LOCA::MultiContinuation::ConstraintInterface object.
NOX::Abstract::Group::ReturnType solveTranspose (Teuchos::ParameterList &params, const LOCA::BorderedSolver::AbstractOperator &op, const NOX::Abstract::MultiVector &B, const NOX::Abstract::MultiVector::DenseMatrix &C, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system using the tranpose of J and C as described above with B specified as a NOX::Abstract::MultiVector object.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data object.
Detailed Description
Block elimination strategy for solving a block lower-triangular system.
This class solves the extended system of equations
via block elimination:
where represents either the identity operation or the transpose. must be nonzero, while , or may be zero. may be specified either as a NOX::Abstract::MultiVector or a LOCA::MultiContinuation::ConstraintInterface object. The solve for the non-transposed system is implemented by the solve() method, while the solve for the transposed system is implemented by the solveTranspose() method.
Constructor & Destructor Documentation
LowerTriangularBlockElimination()
LOCA::BorderedSolver::LowerTriangularBlockElimination::LowerTriangularBlockElimination (const Teuchos::RCP< LOCA::GlobalData > & global_data)
Constructor.
Parameters
global_data [in] Global data object
Member Function Documentation
solve() [1/2]
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::LowerTriangularBlockElimination::solve (Teuchos::ParameterList & params, const LOCA::BorderedSolver::AbstractOperator & op, const LOCA::MultiContinuation::ConstraintInterface & B, const NOX::Abstract::MultiVector::DenseMatrix & C, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const
Solves the extended system as described above with B specified as a LOCA::MultiContinuation::ConstraintInterface object.
Either F, or G may be zero by passing NULL.
References LOCA::BorderedSolver::AbstractOperator::applyInverse(), NOX::Abstract::Group::Failed, NOX::Abstract::MultiVector::init(), LOCA::MultiContinuation::ConstraintInterface::isDXZero(), LOCA::MultiContinuation::ConstraintInterface::multiplyDX(), and NOX::Abstract::Group::Ok.
Referenced by LOCA::BorderedSolver::EpetraAugmented::applyInverse(), LOCA::BorderedSolver::EpetraHouseholder::applyInverse(), LOCA::BorderedSolver::TpetraHouseholder::applyInverse(), and LOCA::BorderedSolver::Bordering::applyInverse().
solve() [2/2]
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::LowerTriangularBlockElimination::solve (Teuchos::ParameterList & params, const LOCA::BorderedSolver::AbstractOperator & op, const NOX::Abstract::MultiVector & B, const NOX::Abstract::MultiVector::DenseMatrix & C, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const
Solves the extended system as described above with B specified as a NOX::Abstract::MultiVector.
Either F, or G may be zero by passing NULL.
solveTranspose() [1/2]
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::LowerTriangularBlockElimination::solveTranspose (Teuchos::ParameterList & params, const LOCA::BorderedSolver::AbstractOperator & op, const LOCA::MultiContinuation::ConstraintInterface & B, const NOX::Abstract::MultiVector::DenseMatrix & C, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const
Solves the extended system using the tranpose of J and C as described above with B specified as a LOCA::MultiContinuation::ConstraintInterface object.
Either F, or G may be zero by passing NULL.
References LOCA::BorderedSolver::AbstractOperator::applyInverseTranspose(), NOX::Abstract::Group::Failed, NOX::Abstract::MultiVector::init(), LOCA::MultiContinuation::ConstraintInterface::isDXZero(), LOCA::MultiContinuation::ConstraintInterface::multiplyDX(), and NOX::Abstract::Group::Ok.
Referenced by LOCA::BorderedSolver::EpetraHouseholder::applyInverseTranspose(), LOCA::BorderedSolver::TpetraHouseholder::applyInverseTranspose(), and LOCA::BorderedSolver::Bordering::applyInverseTranspose().
solveTranspose() [2/2]
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::LowerTriangularBlockElimination::solveTranspose (Teuchos::ParameterList & params, const LOCA::BorderedSolver::AbstractOperator & op, const NOX::Abstract::MultiVector & B, const NOX::Abstract::MultiVector::DenseMatrix & C, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const
Solves the extended system using the tranpose of J and C as described above with B specified as a NOX::Abstract::MultiVector object.
Either F, or G may be zero by passing NULL.
The documentation for this class was generated from the following files:
LOCA_BorderedSolver_LowerTriangularBlockElimination.H
LOCA_BorderedSolver_LowerTriangularBlockElimination.C