NOX: NOX::Solver::TrustRegionBased Class Reference
NOX::Solver::TrustRegionBased Class Reference
Newton-like solver using a trust region.
#include <NOX_Solver_TrustRegionBased.H>
Public Member Functions
TrustRegionBased (const Teuchos::RCP< NOX::Abstract::Group > &grp, const Teuchos::RCP< NOX::StatusTest::Generic > &tests, const Teuchos::RCP< Teuchos::ParameterList > &params)
Constructor.
virtual ~TrustRegionBased ()
Destructor.
virtual void reset (const NOX::Abstract::Vector &initialGuess, const Teuchos::RCP< NOX::StatusTest::Generic > &tests)
Resets the solver, sets a new status test, and sets a new initial guess.
virtual void reset (const NOX::Abstract::Vector &initialGuess)
Resets the solver and sets a new initial guess.
virtual void reset ()
Resets the solver for another solve. This resets the counters and status only. Uses the final solution from the last solve as the initial guess for the next solve.
virtual NOX::StatusTest::StatusType step ()
Do one nonlinear step in the iteration sequence and return status.
virtual NOX::StatusTest::StatusType solve ()
Solve the nonlinear problem and return final status.
virtual const NOX::Abstract::Group & getSolutionGroup () const
Return a reference to the current solution group.
virtual const NOX::Abstract::Group & getPreviousSolutionGroup () const
Return a reference to the previous solution group.
virtual NOX::StatusTest::StatusType getStatus () const
Returns the current status of the solver.
virtual int getNumIterations () const
Get number of iterations.
virtual const Teuchos::ParameterList & getList () const
Return a reference to the solver parameters.
virtual Teuchos::RCP< const NOX::Abstract::Group > getSolutionGroupPtr () const
Return a RCP to the solution group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getPreviousSolutionGroupPtr () const
Return a RCP to the previous solution group.
virtual Teuchos::RCP< const Teuchos::ParameterList > getListPtr () const
Return a RCP to the solver parameters.
virtual Teuchos::RCP< const NOX::SolverStats > getSolverStatistics () const
Return a RCP to the solver statistics.
Public Member Functions inherited from NOX::Solver::Generic
Generic ()
Constructor (does nothing)
virtual ~Generic ()
Destructor (does nothing)
Protected Types
enum StepType { Newton , Cauchy , Dogleg }
Enumerated list for each direction that may be required in the Trust region computation.
Protected Member Functions
virtual void init ()
Print out initialization information and calcuation the RHS.
virtual void invalid (const std::string &param, double value) const
Print and error message and throw and error.
virtual void printUpdate ()
Prints the current iteration information.
Protected Attributes
Teuchos::RCP< NOX::GlobalData > globalDataPtr
Pointer to the global data object.
Teuchos::RCP< NOX::Utils > utilsPtr
Printing Utils.
Teuchos::RCP< NOX::Abstract::Group > solnPtr
Current solution.
Teuchos::RCP< NOX::Abstract::Group > oldSolnPtr
Previous solution pointer.
Teuchos::RCP< NOX::Abstract::Vector > newtonVecPtr
Current search direction.pointer.
Teuchos::RCP< NOX::Abstract::Vector > cauchyVecPtr
Current search direction.pointer.
Teuchos::RCP< NOX::Abstract::Vector > aVecPtr
Extra vector used in computations.
Teuchos::RCP< NOX::Abstract::Vector > bVecPtr
Extra vector used in computations.
Teuchos::RCP< NOX::StatusTest::Generic > testPtr
Stopping test.
NOX::StatusTest::CheckType checkType
Type of check to use for status tests. See NOX::StatusTest for more details.
Teuchos::RCP< Teuchos::ParameterList > paramsPtr
Input parameters.
Teuchos::RCP< NOX::Direction::Generic > newtonPtr
Newton Search Direction.
Teuchos::RCP< NOX::Direction::Generic > cauchyPtr
Cauchy Search Direction.
double radius
Radius of the trust region.
double minRatio
Minimum improvement ratio to accept step.
double initRadius
Initial trust region radius.
double minRadius
Minimum trust region radius.
double maxRadius
Maximum trust region radius.
double contractTriggerRatio
ratio < alpha triggers contraction
double expandTriggerRatio
ratio > beta triggers expansion
double expandFactor
Expansion factor.
double contractFactor
Constraction factor.
double recoveryStep
double newF
Value of at current solution.
double oldF
Value of at previous solution.
double dx
norm(xnew - xold)
int nIter
Number of nonlinear iterations.
NOX::StatusTest::StatusType status
Status of nonlinear solver.
StepType stepType
Type of step to be taken.
Teuchos::RCP< NOX::MeritFunction::Generic > meritFuncPtr
Stores a user supplied merit function if supplied in the parameter list.
bool useAredPredRatio
If set to true, the minimum improvement ratio condition uses an Ared/Pred approach.
Teuchos::RCP< NOX::Observer > observer
Pointer to a user defined NOX::Observer object.
Detailed Description
Newton-like solver using a trust region.
Our goal is to solve: where . Alternatively, we might say that we wish to solve
The trust region subproblem (TRSP) at iteration is given by
where
,
,
,
is the Jacobian of at , and
is the trust region radius.
The "improvement ratio" for a given step is defined as
An iteration consists of the following steps.
Compute Newton-like direction:
Compute Cauchy-like direction:
If this is the first iteration, initialize as follows: If , then ; else, .
Initialize
While and , do the following.
Compute the direction as follows:
If , then take a Newton step by setting
Otherwise if , then take a Cauchy step by setting
Otherwise, take a Dog Leg step by setting where with .
Set and calculate
If , then Otherwise
Update the solution:
Update trust region:
If and , then shrink the trust region to the size of the Newton step: .
Otherwise if , then shrink the trust region: .
Otherwise if and , then expand the trust region: .
Input Paramters
The following parameters should be specified in the "Trust Region" sublist based to the solver.
"Direction" - Sublist of the direction parameters for the Newton point, passed to the NOX::Direction::Manager constructor. If this sublist does not exist, it is created by default. Furthermore, if "Method" is not specified in this sublist, it is added with a value of "Newton".
"Cauchy %Direction" - Sublist of the direction parameters for the Cauchy point, passed to the NOX::Direction::Manager constructor. If this sublist does not exist, it is created by default. Furthremore, if "Method" is not specified in this sublist, it is added with a value of "Steepest Descent" Finally, if the sub-sublist "Steepest Descent" does not exist, it is created and the parameter "Scaling Type" is added and set to "Quadratic".
"Minimum Trust Region Radius" () - Minimum allowable trust region radius. Defaults to 1.0e-6.
"Maximum Trust Region Radius" () - Maximum allowable trust region radius. Defaults to 1.0e+10.
"Minimum Improvement Ratio" () - Minimum improvement ratio to accept the step. Defaults to 1.0e-4.
"Contraction Trigger Ratio" () - If the improvement ratio is less than this value, then the trust region is contracted by the amount specified by the "Contraction Factor". Must be larger than "Minimum Improvement Ratio". Defaults to 0.1.
"Contraction Factor" () - See above. Defaults to 0.25.
"Expansion Trigger Ratio" () - If the improvement ratio is greater than this value, then the trust region is contracted by the amount specified by the "Expansion Factor". Defaults to 0.75.
"Expansion Factor" () - See above. Defaults to 4.0.
"Recovery Step" - Defaults to 1.0.
"Use Ared/Pred Ratio Calculation" (boolean) - Defaults to false. If set to true, this option replaces the algorithm used to compute the improvement ratio, , as described above. The improvement ratio is replaced by an "Ared/Pred" sufficient decrease criteria similar to that used in line search algorithms (see Eisenstat and Walker, SIAM Journal on Optimization V4 no. 2 (1994) pp 393-422):
"Solver Options" - Sublist of general solver options.
"User Defined Pre/Post Operator" is supported. See NOX::Parameter::PrePostOperator for more details.
Output Paramters
A sublist for output parameters called "Output" will be created and contain the following parameters:
"Nonlinear Iterations" - Number of nonlinear iterations
"2-Norm or Residual" - Two-norm of final residual
Author
Tammy Kolda (SNL 8950), Roger Pawlowski (SNL 9233)
Member Enumeration Documentation
StepType
enum NOX::Solver::TrustRegionBased::StepType protected
Enumerated list for each direction that may be required in the Trust region computation.
Enumerator
Newton
Use the Newton direction.
Cauchy
Use the Cauchy direction.
Dogleg
Use the doglog direction.
Constructor & Destructor Documentation
TrustRegionBased()
TrustRegionBased::TrustRegionBased (const Teuchos::RCP< NOX::Abstract::Group > & grp, const Teuchos::RCP< NOX::StatusTest::Generic > & tests, const Teuchos::RCP< Teuchos::ParameterList > & params)
Constructor.
See reset() for description.
References globalDataPtr, init(), meritFuncPtr, observer, NOX::Solver::parseObserver(), utilsPtr, and NOX::Solver::validateSolverOptionsSublist().
Member Function Documentation
getList()
const Teuchos::ParameterList & TrustRegionBased::getList () const virtual
Return a reference to the solver parameters.
Implements NOX::Solver::Generic.
References paramsPtr.
getListPtr()
virtual Teuchos::RCP< const Teuchos::ParameterList > NOX::Solver::TrustRegionBased::getListPtr () const inline virtual
Return a RCP to the solver parameters.
Implements NOX::Solver::Generic.
References paramsPtr.
getNumIterations()
int TrustRegionBased::getNumIterations () const virtual
Get number of iterations.
Implements NOX::Solver::Generic.
References nIter.
getPreviousSolutionGroup()
const Abstract::Group & TrustRegionBased::getPreviousSolutionGroup () const virtual
Return a reference to the previous solution group.
Implements NOX::Solver::Generic.
References oldSolnPtr.
getPreviousSolutionGroupPtr()
virtual Teuchos::RCP< const NOX::Abstract::Group > NOX::Solver::TrustRegionBased::getPreviousSolutionGroupPtr () const inline virtual
Return a RCP to the previous solution group.
Implements NOX::Solver::Generic.
References oldSolnPtr.
getSolutionGroup()
const Abstract::Group & TrustRegionBased::getSolutionGroup () const virtual
Return a reference to the current solution group.
Implements NOX::Solver::Generic.
References solnPtr.
getSolutionGroupPtr()
virtual Teuchos::RCP< const NOX::Abstract::Group > NOX::Solver::TrustRegionBased::getSolutionGroupPtr () const inline virtual
Return a RCP to the solution group.
Implements NOX::Solver::Generic.
References solnPtr.
getSolverStatistics()
Teuchos::RCP< const NOX::SolverStats > NOX::Solver::TrustRegionBased::getSolverStatistics () const virtual
Return a RCP to the solver statistics.
Implements NOX::Solver::Generic.
getStatus()
NOX::StatusTest::StatusType TrustRegionBased::getStatus () const virtual
Returns the current status of the solver.
Implements NOX::Solver::Generic.
References status.
reset() [1/3]
void TrustRegionBased::reset () virtual
Resets the solver for another solve. This resets the counters and status only. Uses the final solution from the last solve as the initial guess for the next solve.
NOTE: All NOX solvers will call reset() automatically at teh beginning of the solve() method. We add the reset() method to the solver interface for the application to call in case the application needs to reset counters and status manually before the next call to solve() is made.
Implements NOX::Solver::Generic.
References dx, nIter, status, and NOX::StatusTest::Unconverged.
Referenced by solve().
reset() [2/3]
void TrustRegionBased::reset (const NOX::Abstract::Vector & initial_guess) virtual
Resets the solver and sets a new initial guess.
Implements NOX::Solver::Generic.
References dx, nIter, solnPtr, status, and NOX::StatusTest::Unconverged.
reset() [3/3]
void TrustRegionBased::reset (const NOX::Abstract::Vector & initial_guess, const Teuchos::RCP< NOX::StatusTest::Generic > & test) virtual
Resets the solver, sets a new status test, and sets a new initial guess.
Implements NOX::Solver::Generic.
References dx, nIter, solnPtr, status, testPtr, and NOX::StatusTest::Unconverged.
solve()
NOX::StatusTest::StatusType TrustRegionBased::solve () virtual
Solve the nonlinear problem and return final status.
By "solve", we call iterate() until the NOX::StatusTest value is either NOX::StatusTest::Converged or NOX::StatusTest::Failed.
Implements NOX::Solver::Generic.
References nIter, observer, paramsPtr, reset(), solnPtr, status, step(), and NOX::StatusTest::Unconverged.
step()
NOX::StatusTest::StatusType TrustRegionBased::step () virtual
Do one nonlinear step in the iteration sequence and return status.
Implements NOX::Solver::Generic.
References aVecPtr, bVecPtr, Cauchy, cauchyPtr, cauchyVecPtr, NOX::StatusTest::Generic::checkStatus(), checkType, NOX::Abstract::Group::computeF(), NOX::Abstract::Group::computeX(), contractFactor, contractTriggerRatio, NOX::Utils::Debug, Dogleg, dx, expandFactor, expandTriggerRatio, NOX::StatusTest::Failed, NOX::Utils::fill(), NOX::Abstract::Group::getNormF(), globalDataPtr, initRadius, NOX::Utils::InnerIteration, maxRadius, meritFuncPtr, minRadius, minRatio, newF, Newton, newtonPtr, newtonVecPtr, nIter, NOX::Abstract::Vector::norm(), observer, NOX::Abstract::Group::Ok, oldF, oldSolnPtr, printUpdate(), radius, recoveryStep, solnPtr, status, step(), stepType, testPtr, NOX::StatusTest::Unconverged, useAredPredRatio, and utilsPtr.
Referenced by solve(), and step().
Member Data Documentation
aVecPtr
Teuchos::RCP<NOX::Abstract::Vector> NOX::Solver::TrustRegionBased::aVecPtr protected
Extra vector used in computations.
We have both a pointer and a reference because we need to create a DERIVED object and then want to have a reference to it.
Referenced by step().
bVecPtr
Teuchos::RCP<NOX::Abstract::Vector> NOX::Solver::TrustRegionBased::bVecPtr protected
Extra vector used in computations.
We have both a pointer and a reference because we need to create a DERIVED object and then want to have a reference to it.
Referenced by step().
cauchyVecPtr
Teuchos::RCP<NOX::Abstract::Vector> NOX::Solver::TrustRegionBased::cauchyVecPtr protected
Current search direction.pointer.
We have both a pointer and a reference because we need to create a DERIVED object and then want to have a reference to it.
Referenced by step().
newtonVecPtr
Teuchos::RCP<NOX::Abstract::Vector> NOX::Solver::TrustRegionBased::newtonVecPtr protected
Current search direction.pointer.
We have both a pointer and a reference because we need to create a DERIVED object and then want to have a reference to it.
Referenced by step().
oldSolnPtr
Teuchos::RCP<NOX::Abstract::Group> NOX::Solver::TrustRegionBased::oldSolnPtr protected
Previous solution pointer.
We have both a pointer and a reference because we need to create a DERIVED object and then want to have a reference to it.
Referenced by getPreviousSolutionGroup(), getPreviousSolutionGroupPtr(), and step().
recoveryStep
double NOX::Solver::TrustRegionBased::recoveryStep protected
Take a step of this length in the Newton direction if the trust-region search fails
Referenced by init(), and step().
The documentation for this class was generated from the following files:
NOX_Solver_TrustRegionBased.H
NOX_Solver_TrustRegionBased.C