NOX: LOCA::TurningPoint::MooreSpence::ExtendedGroup Class Reference
LOCA::TurningPoint::MooreSpence::ExtendedGroup Class Reference
A group representing the Moore-Spence turning point equations.
#include <LOCA_TurningPoint_MooreSpence_ExtendedGroup.H>
Public Member Functions
ExtendedGroup (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > &topParams, const Teuchos::RCP< Teuchos::ParameterList > &tpParams, const Teuchos::RCP< LOCA::TurningPoint::MooreSpence::AbstractGroup > &g)
Constructor with initial data passed through parameter lists.
ExtendedGroup (const ExtendedGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~ExtendedGroup ()
Destructor.
Implementation of NOX::Abstract::Group virtual methods
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Assignment operator.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const
Cloning function.
virtual void setX (const NOX::Abstract::Vector &y)
Set the solution vector, x, to y.
virtual void computeX (const NOX::Abstract::Group &g, const NOX::Abstract::Vector &d, double step)
Compute this.x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()
Compute the turning point equation residual .
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute the blocks of the Jacobian derivative of .
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Gradient computation is not defined for this group.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute Newton direction using applyJacobianInverse().
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Computes the extended Jacobian vector product.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Jacobian transpose product is not defined by this group.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the extended Jacobian matrix using the bordering algorithm.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Jacobian transpose not defined for this system.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian inverse for extended system.
virtual bool isF () const
Return true if the extended residual is valid.
virtual bool isJacobian () const
Return true if the extended Jacobian is valid.
virtual bool isGradient () const
Always returns false.
virtual bool isNewton () const
Return true if the extended Newton direction is valid.
virtual const NOX::Abstract::Vector & getX () const
Return extended solution vector .
virtual const NOX::Abstract::Vector & getF () const
Return extended equation residual .
virtual double getNormF () const
Return 2-norm of .
virtual const NOX::Abstract::Vector & getGradient () const
Vector returned is not valid.
virtual const NOX::Abstract::Vector & getNewton () const
Return extended Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const
Return extended solution vector .
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const
Return extended equation residual .
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const
Vector returned is not valid.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const
Return extended Newton direction.
virtual double getNormNewtonSolveResidual () const
Return the norm of the Newton solve residual.
Implementation of LOCA::Extended::MultiAbstractGroup
virtual methods
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup () const
Return underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup ()
Return underlying group.
Implementation of LOCA::MultiContinuation::AbstractGroup
virtual methods
virtual void copy (const NOX::Abstract::Group &source)
Assignment operator.
virtual void setParamsMulti (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Set parameters indexed by (integer) paramIDs.
virtual void setParams (const ParameterVector &p)
Set the parameter vector in the group to p.
virtual void setParam (int paramID, double val)
Set parameter indexed by paramID.
virtual void setParam (std::string paramID, double val)
Set parameter indexed by paramID.
virtual const ParameterVector & getParams () const
Return a const reference to the paramter vector owned by the group.
virtual double getParam (int paramID) const
Return copy of parameter indexed by paramID.
virtual double getParam (std::string paramID) const
Return copy of parameter indexed by paramID.
virtual NOX::Abstract::Group::ReturnType computeDfDpMulti (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector &dfdp, bool isValidF)
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any postprocessing after a continuation step finishes.
virtual void projectToDraw (const NOX::Abstract::Vector &x, double *px) const
Projects solution to a few scalars for multiparameter continuation.
virtual int projectToDrawDimension () const
Returns the dimension of the project to draw array.
virtual void printSolution (const double conParam) const
Function to print out extended solution and continuation parameter after successful continuation step.
virtual void printSolution (const NOX::Abstract::Vector &x_, const double conParam) const
Function to print out extended solution and continuation parameter after successful continuation step.
Public Member Functions inherited from LOCA::Extended::MultiAbstractGroup
MultiAbstractGroup ()
Default constructor.
virtual ~MultiAbstractGroup ()
Destructor.
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup () const
Return base-level underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup ()
Return base-level underlying group.
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual ~Group ()
Destructor.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual const NOX::Abstract::Vector & getScaledX () const
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
Public Member Functions inherited from LOCA::MultiContinuation::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
virtual double computeScaledDotProduct (const NOX::Abstract::Vector &a, const NOX::Abstract::Vector &b) const
Compute a scaled dot product.
virtual void scaleVector (NOX::Abstract::Vector &x) const
Scales a vector using scaling vector.
Public Member Functions inherited from LOCA::Abstract::TransposeSolveGroup
TransposeSolveGroup ()
Constructor.
virtual ~TransposeSolveGroup ()
Destructor.
Implementation of LOCA::Abstract::TransposeSolveGroup
virtual methods
enum NullVectorScaling { NVS_None , NVS_OrderOne , NVS_OrderN }
Enumerated type determining type of scaling.
Teuchos::RCP< LOCA::GlobalData > globalData
Pointer LOCA global data object.
Teuchos::RCP< LOCA::Parameter::SublistParser > parsedParams
Parsed top-level parameters.
Teuchos::RCP< Teuchos::ParameterList > turningPointParams
Bifurcation parameter list.
Teuchos::RCP< LOCA::TurningPoint::MooreSpence::AbstractGroup > grpPtr
Pointer to base group that defines .
LOCA::TurningPoint::MooreSpence::ExtendedMultiVector xMultiVec
Stores the extended solution vector.
LOCA::TurningPoint::MooreSpence::ExtendedMultiVector fMultiVec
Stores the extended residual vector and df/dp.
LOCA::TurningPoint::MooreSpence::ExtendedMultiVector newtonMultiVec
Stores the extended Newton vector.
Teuchos::RCP< NOX::Abstract::MultiVector > lengthMultiVec
Stores the length normalization vector.
Teuchos::RCP< LOCA::TurningPoint::MooreSpence::ExtendedVector > xVec
Stores view of first column of xMultiVec.
Teuchos::RCP< LOCA::TurningPoint::MooreSpence::ExtendedVector > fVec
Stores view of first column of fMultiVec.
Teuchos::RCP< LOCA::TurningPoint::MooreSpence::ExtendedMultiVector > ffMultiVec
Stores view of first column of fMultiVec as a multivec.
Teuchos::RCP< LOCA::TurningPoint::MooreSpence::ExtendedMultiVector > dfdpMultiVec
Stores view of df/dp columns of fMultiVec.
Teuchos::RCP< LOCA::TurningPoint::MooreSpence::ExtendedVector > newtonVec
Stores view of first column of newtonMultiVec.
Teuchos::RCP< NOX::Abstract::Vector > lengthVec
Stores view of first column of lengthMultiVec.
Teuchos::RCP< LOCA::TurningPoint::MooreSpence::SolverStrategy > solverStrategy
Stores bordering strategy.
std::vector< int > index_f
Stores indices for getting f part of fMultiVec.
std::vector< int > index_dfdp
Stores indices for getting df/dp part of fMultiVec.
std::vector< int > bifParamID
Stores the bifurcation parameter index.
bool isValidF
Is residual vector valid.
bool isValidJacobian
Is Jacobian matrix valid.
bool isValidNewton
Is Newton vector valid.
bool updateVectorsEveryContinuationStep
Flag indicating whether to update every continuation step.
NullVectorScaling nullVecScaling
Null vector scaling method.
bool multiplyMass
Multiply null vectors by mass matrix.
Teuchos::RCP< LOCA::TimeDependent::AbstractGroup > tdGrp
Time dependent group interface for multiplying by mass matrix.
Teuchos::RCP< NOX::Abstract::Vector > tmp_mass
Temporary vector for mulplying null vectors by mass matrix.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Solve Jacobian-tranpose system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Solve Jacobian-tranpose system with multiple right-hand sides.
double getBifParam () const
Get bifurcation parameter.
double lTransNorm (const NOX::Abstract::Vector &n) const
Defines null vector normalization equation.
void lTransNorm (const NOX::Abstract::MultiVector &n, NOX::Abstract::MultiVector::DenseMatrix &result) const
null vector normalization for multivectors
Teuchos::RCP< NOX::Abstract::Vector > getLengthVector () const
Return length normalization vector.
void setBifParam (double param)
Set bifurcation parameter.
void setupViews ()
Sets up multivector views.
void init (bool perturbSoln=false, double perturbSize=0.0)
Initializes group.
void scaleNullVector (NOX::Abstract::Vector &a)
Scale null vector.
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
A group representing the Moore-Spence turning point equations.
The LOCA::TurningPoint::MooreSpence::ExtendedGroup is a concrete implementation of the NOX::Abstract::Group, LOCA::MultiContinuation::AbstractGroup and LOCA::Extended::MultiAbstractGroup that defines the following extended set of equations that are regular at a generic turning point:
where , is the solution vector, is the null vector, is the length normalization vector and is the Jacobian of F.
The group stores an underlying group of type LOCA::TurningPoint::MooreSpence AbstractGroup to represent the equations and to manipulate the underlying Jacobian . Note that the entire extended Jacobian is not stored in memory, rather a block-elimination algorithm (bordering algorithm) is used to compute linear solves of the extended Jacobian (see LOCA::TurningPoint::MooreSpence::SolverFactory for more details).
This class implements all of the NOX::Abstract::Group, LOCA::MultiContinuation::AbstractGroup, and LOCA::Extended::MultiAbstractGroup methods for this extended set of equations and therefore is a complete group which can be passed to most NOX solvers to locate a single turning point or to the LOCA::Stepper to compute a family of turning points in a second parameter.
However, Jacobian-tranpose operations and gradient calculations cannot be implemented efficiently and therefore gradient-base nonlinear solvers such as steepest descent and Trust region methods cannot be used to solve the extended turning point equations.
The class is intialized via the tpParams parameter list argument to the constructor. The parameters this class recognizes are:
"Bifurcation Parameter" – [string] (Must be supplied) Name of the bifurcation parameter
"Length Normalization Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied) Vector storing length normalization vector
"Initial Null Vector" – [Teuchos::RCP<NOX::Abstract::Vector>] (Must be supplied) - Vector storing initial guess for the null vector
"Perturb Initial Solution" – [bool] (default: false) Flag indicating whether to perturb the initial solution
"Relative Perturbation Size" – [double] (default: 1.0e-3) Relative perturbation size if perturbing the initial solution
"Null Vector Scaling" – [string] (default: "Order N") - Method to scale . This determines the norm of (and hence,). Valid choices are:
"None" – Use initial scaling
"Order 1" – Scale to unit norm
"Order N" – Use vector length scaling
"Update Null Vectors Every Continuation Step" – [bool] (default: false) - Flag indicating whether to update length normalization vector via every continuation step
"Multiply Null Vectors by Mass Matrix" – [bool] (default: false) - Flag indicating whether to multiply length scaling vector by the mass matrix at the start of a turning point calculation, and each time it is updated. This can improve the scaling of this vector, and may orthogonalize it against structural null spaces (i.e., pressure null space for incompressible Navier-Stokes).
Member Enumeration Documentation
NullVectorScaling
enum LOCA::TurningPoint::MooreSpence::ExtendedGroup::NullVectorScaling protected
Enumerated type determining type of scaling.
Enumerator
NVS_OrderOne
No scaling.
NVS_OrderN
Scale to O(1)
Scale to O(N) when N is the vector length
Member Function Documentation
applyJacobian()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobian (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Computes the extended Jacobian vector product.
This method computes the extended Jacobian vector product
using the applyJacobian and computeDJnDxa methods of the underlying group where , , and are the solution, null-vector, and paramter components of the given vector input. Vectors input and result must be of type LOCA::TurningPoint::MooreSpence::ExtendedVector, otherwise an error is thrown.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianInverse()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies the inverse of the extended Jacobian matrix using the bordering algorithm.
This method is a special case of applyJacobianInverseMultiVector() for a single right-hand-side.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian inverse for extended system.
Uses a LOCA::TurningPoint::MooreSpence::SolverStrategy instantiated by the LOCA::TurningPoint::MooreSpence::SolverFactory to implement the solve.
Reimplemented from NOX::Abstract::Group.
applyJacobianMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian for extended system.
Reimplemented from NOX::Abstract::Group.
References LOCA::TurningPoint::MooreSpence::ExtendedMultiVector::getNullMultiVec(), LOCA::Extended::MultiVector::getScalars(), LOCA::TurningPoint::MooreSpence::ExtendedMultiVector::getXMultiVec(), NOX::Abstract::Group::Ok, and NOX::ShapeCopy.
applyJacobianTranspose()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianTranspose (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Jacobian transpose product is not defined by this group.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianTransposeInverse()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianTransposeInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Solve Jacobian-tranpose system.
Implements LOCA::Abstract::TransposeSolveGroup.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianTransposeInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianTransposeInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Solve Jacobian-tranpose system with multiple right-hand sides.
Implements LOCA::Abstract::TransposeSolveGroup.
applyJacobianTransposeMultiVector()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Jacobian transpose not defined for this system.
Reimplemented from NOX::Abstract::Group.
References LOCA::TurningPoint::MooreSpence::ExtendedMultiVector::getNullMultiVec(), LOCA::Extended::MultiVector::getScalars(), LOCA::TurningPoint::MooreSpence::ExtendedMultiVector::getXMultiVec(), NOX::Abstract::Group::Ok, and NOX::ShapeCopy.
clone()
Teuchos::RCP< NOX::Abstract::Group > LOCA::TurningPoint::MooreSpence::ExtendedGroup::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Cloning function.
Implements NOX::Abstract::Group.
computeDfDpMulti()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::computeDfDpMulti (const std::vector< int > & paramIDs, NOX::Abstract::MultiVector & dfdp, bool isValidF) virtual
Compute for each parameter indexed by paramIDs. The first column of dfdp holds F, which is valid if isValidF is true. Otherwise F must be computed.
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::TurningPoint::MooreSpence::ExtendedMultiVector::getNullMultiVec(), LOCA::Extended::MultiVector::getScalar(), LOCA::TurningPoint::MooreSpence::ExtendedMultiVector::getXMultiVec(), NOX::Abstract::MultiVector::numVectors(), and NOX::Abstract::Group::Ok.
computeF()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::computeF () virtual
Compute the turning point equation residual .
This method fills the extended residual
The solution component residual and the null-vector residual are calculated via the computeF and applyJacobian methods of the underlying group.
Implements NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeGradient()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::computeGradient () virtual
Gradient computation is not defined for this group.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::NotDefined.
computeJacobian()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::computeJacobian () virtual
Compute the blocks of the Jacobian derivative of .
This method computes the , , and blocks of the extended Jacobian:
by calling the computeJacobian, computeDfDp, and computeDJnDp methods of the underlying group. The second derivative matrix is not calculated since only its action on vectors is needed for linear solves using the bordering algorithm.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeNewton()
NOX::Abstract::Group::ReturnType LOCA::TurningPoint::MooreSpence::ExtendedGroup::computeNewton (Teuchos::ParameterList & params) virtual
Compute Newton direction using applyJacobianInverse().
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeX()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::computeX (const NOX::Abstract::Group & g, const NOX::Abstract::Vector & d, double step) virtual
Compute this.x = grp.x + step * d.
Implements NOX::Abstract::Group.
References getX(), LOCA::TurningPoint::MooreSpence::ExtendedVector::getXVec(), grpPtr, and LOCA::Extended::Vector::update().
copy()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::copy (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements LOCA::MultiContinuation::AbstractGroup.
References bifParamID, fMultiVec, globalData, grpPtr, index_dfdp, index_f, isValidF, isValidJacobian, isValidNewton, lengthMultiVec, multiplyMass, newtonMultiVec, nullVecScaling, parsedParams, turningPointParams, updateVectorsEveryContinuationStep, and xMultiVec.
getF()
const NOX::Abstract::Vector & LOCA::TurningPoint::MooreSpence::ExtendedGroup::getF () const virtual
Return extended equation residual .
Implements NOX::Abstract::Group.
getFPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MooreSpence::ExtendedGroup::getFPtr () const virtual
Return extended equation residual .
Implements NOX::Abstract::Group.
getGradient()
const NOX::Abstract::Vector & LOCA::TurningPoint::MooreSpence::ExtendedGroup::getGradient () const virtual
Vector returned is not valid.
Implements NOX::Abstract::Group.
getGradientPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MooreSpence::ExtendedGroup::getGradientPtr () const virtual
Vector returned is not valid.
Implements NOX::Abstract::Group.
getNewton()
const NOX::Abstract::Vector & LOCA::TurningPoint::MooreSpence::ExtendedGroup::getNewton () const virtual
Return extended Newton direction.
Implements NOX::Abstract::Group.
getNewtonPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MooreSpence::ExtendedGroup::getNewtonPtr () const virtual
Return extended Newton direction.
Implements NOX::Abstract::Group.
getNormF()
double LOCA::TurningPoint::MooreSpence::ExtendedGroup::getNormF () const virtual
Return 2-norm of .
Implements NOX::Abstract::Group.
References NOX::Abstract::Vector::norm().
getParam() [1/2]
double LOCA::TurningPoint::MooreSpence::ExtendedGroup::getParam (int paramID) const virtual
Return copy of parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParam() [2/2]
double LOCA::TurningPoint::MooreSpence::ExtendedGroup::getParam (std::string paramID) const virtual
Return copy of parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParams()
const LOCA::ParameterVector & LOCA::TurningPoint::MooreSpence::ExtendedGroup::getParams () const virtual
Return a const reference to the paramter vector owned by the group.
Implements LOCA::MultiContinuation::AbstractGroup.
getUnderlyingGroup() [1/2]
Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > LOCA::TurningPoint::MooreSpence::ExtendedGroup::getUnderlyingGroup () virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getUnderlyingGroup() [2/2]
Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > LOCA::TurningPoint::MooreSpence::ExtendedGroup::getUnderlyingGroup () const virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getX()
const NOX::Abstract::Vector & LOCA::TurningPoint::MooreSpence::ExtendedGroup::getX () const virtual
Return extended solution vector .
Implements NOX::Abstract::Group.
Referenced by computeX().
getXPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::TurningPoint::MooreSpence::ExtendedGroup::getXPtr () const virtual
Return extended solution vector .
Implements NOX::Abstract::Group.
isF()
bool LOCA::TurningPoint::MooreSpence::ExtendedGroup::isF () const virtual
Return true if the extended residual is valid.
Implements NOX::Abstract::Group.
isGradient()
bool LOCA::TurningPoint::MooreSpence::ExtendedGroup::isGradient () const virtual
Always returns false.
Reimplemented from NOX::Abstract::Group.
isJacobian()
bool LOCA::TurningPoint::MooreSpence::ExtendedGroup::isJacobian () const virtual
Return true if the extended Jacobian is valid.
Reimplemented from NOX::Abstract::Group.
isNewton()
bool LOCA::TurningPoint::MooreSpence::ExtendedGroup::isNewton () const virtual
Return true if the extended Newton direction is valid.
Reimplemented from NOX::Abstract::Group.
lTransNorm()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::lTransNorm (const NOX::Abstract::MultiVector & n, NOX::Abstract::MultiVector::DenseMatrix & result) const
null vector normalization for multivectors
Note: result should have 1 row and n.numVectors() columns.
References NOX::Abstract::MultiVector::multiply().
operator=()
NOX::Abstract::Group & LOCA::TurningPoint::MooreSpence::ExtendedGroup::operator= (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements NOX::Abstract::Group.
postProcessContinuationStep()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any postprocessing after a continuation step finishes.
The stepStatus argument indicates whether the step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References NOX::Utils::StepperDetails, and LOCA::Abstract::Iterator::Successful.
preProcessContinuationStep()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any preprocessing before a continuation step starts.
The stepStatus argument indicates whether the previous step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References NOX::Utils::StepperDetails.
printSolution() [1/2]
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::printSolution (const double conParam) const virtual
Function to print out extended solution and continuation parameter after successful continuation step.
This method prints the solution, null-vector, and parameter components of the extended solution vector using the printSolution method of the underlying group.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References NOX::Utils::StepperDetails.
printSolution() [2/2]
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::printSolution (const NOX::Abstract::Vector & x_, const double conParam) const virtual
Function to print out extended solution and continuation parameter after successful continuation step.
This method prints the solution, null-vector, and parameter components of the extended solution vector using the printSolution method of the underlying group.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::TurningPoint::MooreSpence::ExtendedVector::getBifParam(), LOCA::TurningPoint::MooreSpence::ExtendedVector::getNullVec(), LOCA::TurningPoint::MooreSpence::ExtendedVector::getXVec(), and NOX::Utils::StepperDetails.
projectToDraw()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::projectToDraw (const NOX::Abstract::Vector & x, double * px) const virtual
Projects solution to a few scalars for multiparameter continuation.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::TurningPoint::MooreSpence::ExtendedVector::getBifParam(), and LOCA::TurningPoint::MooreSpence::ExtendedVector::getXVec().
projectToDrawDimension()
int LOCA::TurningPoint::MooreSpence::ExtendedGroup::projectToDrawDimension () const virtual
Returns the dimension of the project to draw array.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
setParam() [1/2]
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::setParam (int paramID, double val) virtual
Set parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
setParam() [2/2]
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::setParam (std::string paramID, double val) virtual
Set parameter indexed by paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::ParameterVector::getIndex().
setParams()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::setParams (const ParameterVector & p) virtual
Set the parameter vector in the group to p.
Implements LOCA::MultiContinuation::AbstractGroup.
setParamsMulti()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::setParamsMulti (const std::vector< int > & paramIDs, const NOX::Abstract::MultiVector::DenseMatrix & vals) virtual
Set parameters indexed by (integer) paramIDs.
Implements LOCA::MultiContinuation::AbstractGroup.
setX()
void LOCA::TurningPoint::MooreSpence::ExtendedGroup::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector, x, to y.
Implements NOX::Abstract::Group.
References LOCA::TurningPoint::MooreSpence::ExtendedVector::getXVec().
The documentation for this class was generated from the following files:
LOCA_TurningPoint_MooreSpence_ExtendedGroup.H
LOCA_TurningPoint_MooreSpence_ExtendedGroup.C