NOX: LOCA::SingularJacobianSolve::ItRef Class Reference
LOCA::SingularJacobianSolve::ItRef Class Reference
This class computes the solution to using one step of iterative refinement.
#include <LOCA_SingularJacobianSolve_ItRef.H>
Public Member Functions
ItRef (Teuchos::ParameterList &params)
Constructor.
ItRef (const ItRef &source)
Copy constructor.
virtual ~ItRef ()
Destructor.
virtual LOCA::SingularJacobianSolve::Generic * clone () const
Clone function.
virtual LOCA::SingularJacobianSolve::Generic & operator= (const LOCA::SingularJacobianSolve::Generic &source)
Assignment operator.
virtual ItRef & operator= (const ItRef &source)
Assignment operator.
virtual NOX::Abstract::Group::ReturnType reset (Teuchos::ParameterList &params)
Reset parameters.
virtual NOX::Abstract::Group::ReturnType compute (Teuchos::ParameterList &params, LOCA::Continuation::AbstractGroup &grp, const NOX::Abstract::Vector &input, const NOX::Abstract::Vector &approxNullVec, const NOX::Abstract::Vector &jacApproxNullVec, NOX::Abstract::Vector &result)
Computes the solution as described above.
virtual NOX::Abstract::Group::ReturnType computeMulti (Teuchos::ParameterList &params, LOCA::Continuation::AbstractGroup &grp, const NOX::Abstract::Vector *const *inputs, const NOX::Abstract::Vector &approxNullVec, const NOX::Abstract::Vector &jacApproxNullVec, NOX::Abstract::Vector **results, int nVecs)
Computes solution for multiple RHS.
Public Member Functions inherited from LOCA::SingularJacobianSolve::Generic
Generic ()
Constructor.
Generic (const Generic &source)
Copy constructor.
virtual ~Generic ()
Destructor.
Detailed Description
This class computes the solution to using one step of iterative refinement.
This singular solve method uses one step of iterative refinement to improve the accuracy of the solution to the linear system . In particular, the algorithm used here is
Both solves use the underlying group's applyJacobianInverse() method and therefore this is a generic technique for computing solutions to nearly singular system since it uses any supplied linear solver.
This algorithm is selected by setting the "Method" parameter of the "Singular Solve" sublist of the NOX linear solver parameter list to "Iterative Refinement".
Member Function Documentation
clone()
LOCA::SingularJacobianSolve::Generic * LOCA::SingularJacobianSolve::ItRef::clone () const virtual
Clone function.
Implements LOCA::SingularJacobianSolve::Generic.
compute()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::ItRef::compute (Teuchos::ParameterList & params, LOCA::Continuation::AbstractGroup & grp, const NOX::Abstract::Vector & input, const NOX::Abstract::Vector & approxNullVec, const NOX::Abstract::Vector & jacApproxNullVec, NOX::Abstract::Vector & result) virtual
Computes the solution as described above.
Implements LOCA::SingularJacobianSolve::Generic.
References LOCA::ErrorCheck::checkReturnType(), NOX::Abstract::Vector::clone(), LOCA::ErrorCheck::combineAndCheckReturnTypes(), NOX::ShapeCopy, and NOX::Abstract::Vector::update().
computeMulti()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::ItRef::computeMulti (Teuchos::ParameterList & params, LOCA::Continuation::AbstractGroup & grp, const NOX::Abstract::Vector *const * inputs, const NOX::Abstract::Vector & approxNullVec, const NOX::Abstract::Vector & jacApproxNullVec, NOX::Abstract::Vector ** results, int nVecs) virtual
Computes solution for multiple RHS.
Implements LOCA::SingularJacobianSolve::Generic.
References LOCA::ErrorCheck::checkReturnType(), NOX::Abstract::Vector::clone(), LOCA::ErrorCheck::combineAndCheckReturnTypes(), NOX::ShapeCopy, and NOX::Abstract::Vector::update().
operator=()
LOCA::SingularJacobianSolve::Generic & LOCA::SingularJacobianSolve::ItRef::operator= (const LOCA::SingularJacobianSolve::Generic & source) virtual
Assignment operator.
Implements LOCA::SingularJacobianSolve::Generic.
reset()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::ItRef::reset (Teuchos::ParameterList & params) virtual
Reset parameters.
There are no additional parameters for the Nic calculation.
Implements LOCA::SingularJacobianSolve::Generic.
References NOX::Abstract::Group::Ok.
Referenced by ItRef().
The documentation for this class was generated from the following files:
LOCA_SingularJacobianSolve_ItRef.H
LOCA_SingularJacobianSolve_ItRef.C