NOX: LOCA::ErrorCheck Class Reference
LOCA::ErrorCheck Class Reference
An Error checking algorithm for NOX/LOCA routines.
#include <LOCA_ErrorCheck.H>
Public Types
enum ActionType { ThrowError , PrintWarning }
Type for the action to be taken if the ReturnType is not Ok.
Public Member Functions
ErrorCheck (const Teuchos::RCP< LOCA::GlobalData > &global_data)
Constructor.
~ErrorCheck ()
Destructor.
void throwError (const std::string &callingFunction="<Unknown Method>", const std::string &message="", const std::string &throwLabel="LOCA Error")
Generic call to throw that prints info to the screen.
void printWarning (const std::string &callingFunction="<Unknown Method>", const std::string &message="")
Generic printing algorithm for sending warnings to the screen.
void checkReturnType (const NOX::Abstract::Group::ReturnType &status, const std::string &callingFunction=std::string("<Unknown Method>"))
Checks the supplied return type and performs an appropriate action.
void checkReturnType (const NOX::Abstract::Group::ReturnType &status, const ActionType &action, const std::string &callingFunction=std::string("<Unknown Method>"), const std::string &message=std::string(""))
Checks the return type for the NOX::AbstractGroup and may throw an error or print a warning to the screen based on the ActionType requested.
NOX::Abstract::Group::ReturnType combineReturnTypes (const NOX::Abstract::Group::ReturnType &status1, const NOX::Abstract::Group::ReturnType &status2)
Combines two return types.
NOX::Abstract::Group::ReturnType combineAndCheckReturnTypes (const NOX::Abstract::Group::ReturnType &status1, const NOX::Abstract::Group::ReturnType &status2, const std::string &callingFunction=std::string("<Unknown Method>"))
Combines two return types and checks the first.
Protected Member Functions
std::string getReturnTypeString (NOX::Abstract::Group::ReturnType status)
Converts the NOX::Abstract::Group::ReturnType to a std::string.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data.
Detailed Description
An Error checking algorithm for NOX/LOCA routines.
This object will check the return types on objects and print a warning or throw an error if appropriate
Member Enumeration Documentation
ActionType
enum LOCA::ErrorCheck::ActionType
Type for the action to be taken if the ReturnType is not Ok.
Enumerator
ThrowError
Throw an error.
PrintWarning
Print a warning.
Member Function Documentation
checkReturnType()
void LOCA::ErrorCheck::checkReturnType (const NOX::Abstract::Group::ReturnType & status, const std::string & callingFunction = std::string("<Unknown Method>"))
Checks the supplied return type and performs an appropriate action.
This routine performs the following actions depending on the value of status
NOX::Abstract::Group::Ok – nothing
NOX::Abstract::Group::Failed – print message and throw a std::string
NOX::Abstract::Group::NotDefined – print message and throw a std::string
NOX::Abstract::Group::BadDependency – print message and throw a std::string
NOX::Abstract::Group::NotConverged – print a warning message
References NOX::Abstract::Group::BadDependency, NOX::Abstract::Group::Failed, NOX::Abstract::Group::NotConverged, NOX::Abstract::Group::NotDefined, NOX::Abstract::Group::Ok, PrintWarning, and ThrowError.
Referenced by LOCA::SingularJacobianSolve::ItRef::compute(), LOCA::SingularJacobianSolve::Nic::compute(), LOCA::SingularJacobianSolve::NicDay::compute(), and LOCA::SingularJacobianSolve::ItRef::computeMulti().
combineAndCheckReturnTypes()
NOX::Abstract::Group::ReturnType LOCA::ErrorCheck::combineAndCheckReturnTypes (const NOX::Abstract::Group::ReturnType & status1, const NOX::Abstract::Group::ReturnType & status2, const std::string & callingFunction = std::string("<Unknown Method>"))
Combines two return types and checks the first.
First combines status1 and status2 using combineReturnTypes() and checks the first using checkReturnType().
Referenced by LOCA::SingularJacobianSolve::ItRef::compute(), LOCA::SingularJacobianSolve::ItRef::computeMulti(), LOCA::SingularJacobianSolve::Nic::computeMulti(), and LOCA::SingularJacobianSolve::NicDay::computeMulti().
combineReturnTypes()
NOX::Abstract::Group::ReturnType LOCA::ErrorCheck::combineReturnTypes (const NOX::Abstract::Group::ReturnType & status1, const NOX::Abstract::Group::ReturnType & status2)
Combines two return types.
If either return type is NOX::Abstract::Group::NotDefined, returns NotDefined. Otherwise if either is BadDependcy, returns BadDependency, if either is Failed, returns Failed, if either is NotConverged, returns NotConverged, and otherwise returns Ok.
References NOX::Abstract::Group::BadDependency, NOX::Abstract::Group::Failed, NOX::Abstract::Group::NotConverged, NOX::Abstract::Group::NotDefined, and NOX::Abstract::Group::Ok.
The documentation for this class was generated from the following files:
LOCA_ErrorCheck.H
LOCA_ErrorCheck.C