NOX: Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector > Class Reference
Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector > Class Reference
Implementation of the Anasazi::MultiVecTraits for NOX::Abstract::MultiVectors.
#include <Anasazi_LOCA_MultiVecTraits.H>
Public Types
typedef double ScalarType
Synony for double.
typedef NOX::Abstract::MultiVector MV
Synonym for NOX::Abstract::MultiVector.
Static Public Member Functions
static Teuchos::RCP< MV > Clone (const MV &mv, const int numvecs)
Creates a new empty MV containing numvecs columns.
static Teuchos::RCP< MV > CloneCopy (const MV &mv)
Creates a new MV and copies contents of mv into the new vector (deep copy).
static Teuchos::RCP< MV > CloneCopy (const MV &mv, const std::vector< int > &index)
Creates a new MV and copies the selected contents of mv into the new vector (deep copy).
static Teuchos::RCP< MV > CloneViewNonConst (MV &mv, const std::vector< int > &index)
Creates a new MV that shares the selected contents of mv (shallow copy).
static Teuchos::RCP< const MV > CloneView (const MV &mv, const std::vector< int > &index)
Creates a new const MV that shares the selected contents of mv (shallow copy).
static ptrdiff_t GetGlobalLength (const MV &mv)
Obtain the vector length of mv.
static int GetNumberVecs (const MV &mv)
Obtain the number of vectors in mv.
static void MvTimesMatAddMv (const ScalarType alpha, const MV &A, const Teuchos::SerialDenseMatrix< int, ScalarType > &B, const ScalarType beta, MV &mv)
Update mv with .
static void MvAddMv (const ScalarType alpha, const MV &A, const ScalarType beta, const MV &B, MV &mv)
Replace mv with .
static void MvTransMv (const ScalarType alpha, const MV &A, const MV &mv, Teuchos::SerialDenseMatrix< int, ScalarType > &B)
Compute a dense matrix B through the matrix-matrix multiply .
static void MvDot (const MV &mv, const MV &A, std::vector< ScalarType > &b)
Compute a vector b where the components are the individual dot-products of the i-th columns of A and mv, i.e. .
static void MvScale (MV &mv, const ScalarType alpha)
Scale each element of the vectors in *this with alpha.
static void MvScale (MV &mv, const std::vector< ScalarType > &alpha)
Scale each element of the i-th vector in *this with alpha[i].
static void MvNorm (const MV &mv, std::vector< double > &normvec)
Compute the 2-norm of each individual vector of mv. Upon return, normvec[i] holds the value of , the i-th column of mv.
static void SetBlock (const MV &A, const std::vector< int > &index, MV &mv)
Copy the vectors in A to a set of vectors in mv indicated by the indices given in index.
static void MvRandom (MV &mv)
Replace the vectors in mv with random vectors.
static void MvInit (MV &mv, const ScalarType alpha=0.0)
Replace each element of the vectors in mv with alpha.
static void MvPrint (const MV &mv, std::ostream &os)
Print the mv multi-vector to the os output stream.
Detailed Description
Implementation of the Anasazi::MultiVecTraits for NOX::Abstract::MultiVectors.
This class provides an implementation of the Anasazi::MultiVecTraits class for NOX::Abstract::MultiVector's, to be used in conjunction with the Anasazi::LOCA::Matrix class.
Member Function Documentation
Clone()
static Teuchos::RCP< MV > Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector >::Clone (const MV & mv, const int numvecs) inline static
Creates a new empty MV containing numvecs columns.
Returns
Reference-counted pointer to the new multivector of type MV.
References NOX::Abstract::MultiVector::clone().
CloneCopy() [1/2]
static Teuchos::RCP< MV > Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector >::CloneCopy (const MV & mv) inline static
Creates a new MV and copies contents of mv into the new vector (deep copy).
Returns
Reference-counted pointer to the new multivector of type MV.
References NOX::Abstract::MultiVector::clone(), and NOX::DeepCopy.
CloneCopy() [2/2]
static Teuchos::RCP< MV > Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector >::CloneCopy (const MV & mv, const std::vector< int > & index) inline static
Creates a new MV and copies the selected contents of mv into the new vector (deep copy).
The copied vectors from mv are indicated by the index.size() indices in index.
Returns
Reference-counted pointer to the new multivector of type MV.
References NOX::Abstract::MultiVector::subCopy().
CloneView()
static Teuchos::RCP< const MV > Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector >::CloneView (const MV & mv, const std::vector< int > & index) inline static
Creates a new const MV that shares the selected contents of mv (shallow copy).
The index of the numvecs vectors shallow copied from mv are indicated by the indices given in index.
Returns
Reference-counted pointer to the new const multivector of type MV.
References NOX::Abstract::MultiVector::subView().
CloneViewNonConst()
static Teuchos::RCP< MV > Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector >::CloneViewNonConst (MV & mv, const std::vector< int > & index) inline static
Creates a new MV that shares the selected contents of mv (shallow copy).
The index of the numvecs vectors shallow copied from mv are indicated by the indices given in index.
Returns
Reference-counted pointer to the new multivector of type MV.
References NOX::Abstract::MultiVector::subView().
SetBlock()
static void Anasazi::MultiVecTraits< double, NOX::Abstract::MultiVector >::SetBlock (const MV & A, const std::vector< int > & index, MV & mv) inline static
Copy the vectors in A to a set of vectors in mv indicated by the indices given in index.
The numvecs vectors in A are copied to a subset of vectors in mv indicated by the indices given in index, i.e. mv[index[i]] = A[i].
References NOX::Abstract::MultiVector::setBlock().
The documentation for this class was generated from the following file:
Anasazi_LOCA_MultiVecTraits.H