NOX: LOCA::BorderedSolver::Bordering Class Reference
LOCA::BorderedSolver::Bordering Class Reference
Bordered system solver strategy based on bordering.
#include <LOCA_BorderedSolver_Bordering.H>
Public Member Functions
Bordering (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > &topParams, const Teuchos::RCP< Teuchos::ParameterList > &solverParams)
Constructor.
virtual ~Bordering ()
Destructor.
virtual void setMatrixBlocks (const Teuchos::RCP< const LOCA::BorderedSolver::AbstractOperator > &op, const Teuchos::RCP< const NOX::Abstract::MultiVector > &blockA, const Teuchos::RCP< const LOCA::MultiContinuation::ConstraintInterface > &blockB, const Teuchos::RCP< const NOX::Abstract::MultiVector::DenseMatrix > &blockC)
Set blocks.
virtual NOX::Abstract::Group::ReturnType initForSolve ()
Intialize solver for a solve.
virtual NOX::Abstract::Group::ReturnType initForTransposeSolve ()
Intialize solver for a transpose solve.
virtual NOX::Abstract::Group::ReturnType apply (const NOX::Abstract::MultiVector &X, const NOX::Abstract::MultiVector::DenseMatrix &Y, NOX::Abstract::MultiVector &U, NOX::Abstract::MultiVector::DenseMatrix &V) const
Computed extended matrix-multivector product.
virtual NOX::Abstract::Group::ReturnType applyTranspose (const NOX::Abstract::MultiVector &X, const NOX::Abstract::MultiVector::DenseMatrix &Y, NOX::Abstract::MultiVector &U, NOX::Abstract::MultiVector::DenseMatrix &V) const
Computed extended matrix transpose-multivector product.
virtual NOX::Abstract::Group::ReturnType applyInverse (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system as defined above using bordering.
virtual NOX::Abstract::Group::ReturnType applyInverseTranspose (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the transpose of the extended system as defined above using bordering.
Public Member Functions inherited from LOCA::BorderedSolver::AbstractStrategy
AbstractStrategy ()
Constructor.
virtual ~AbstractStrategy ()
Destructor.
virtual void setMatrixBlocksMultiVecConstraint (const Teuchos::RCP< const LOCA::BorderedSolver::AbstractOperator > &op, const Teuchos::RCP< const NOX::Abstract::MultiVector > &blockA, const Teuchos::RCP< const NOX::Abstract::MultiVector > &blockB, const Teuchos::RCP< const NOX::Abstract::MultiVector::DenseMatrix > &blockC)
Set blocks with multivector constraint.
Protected Member Functions
NOX::Abstract::Group::ReturnType solveFZero (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector *AA, const LOCA::MultiContinuation::ConstraintInterface *BB, const NOX::Abstract::MultiVector::DenseMatrix *CC, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system when F = 0.
NOX::Abstract::Group::ReturnType solveContiguous (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector *AA, const LOCA::MultiContinuation::ConstraintInterface *BB, const NOX::Abstract::MultiVector::DenseMatrix *CC, std::vector< int > &indexF, std::vector< int > &indexA, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the extended system when F and A are contiguous.
NOX::Abstract::Group::ReturnType solveFZeroTrans (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector *AA, const NOX::Abstract::MultiVector *BB, const NOX::Abstract::MultiVector::DenseMatrix *CC, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the transpose of the extended system when F = 0.
NOX::Abstract::Group::ReturnType solveContiguousTrans (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector *AA, const NOX::Abstract::MultiVector *BB, const NOX::Abstract::MultiVector::DenseMatrix *CC, std::vector< int > &indexF, std::vector< int > &indexA, const NOX::Abstract::MultiVector *F, const NOX::Abstract::MultiVector::DenseMatrix *G, NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector::DenseMatrix &Y) const
Solves the transpose of the extended system when F and B are contiguous.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data object.
Teuchos::RCP< Teuchos::ParameterList > solverParams
Solver parameters.
Teuchos::RCP< const LOCA::BorderedSolver::AbstractOperator > op
Pointer to operator.
Teuchos::RCP< const NOX::Abstract::MultiVector > A
Pointer to A block.
Teuchos::RCP< const LOCA::MultiContinuation::ConstraintInterface > B
Pointer to B block.
Teuchos::RCP< const NOX::Abstract::MultiVector::DenseMatrix > C
Pointer to C block.
bool isZeroA
flag indicating whether A block is zero
bool isZeroB
flag indicating whether B block is zero
bool isZeroC
flag indicating whether C block is zero
bool isZeroF
flag indicating whether F block is zero
bool isZeroG
flag indicating whether G block is zero
Detailed Description
Bordered system solver strategy based on bordering.
This class solves the extended system of equations
via bordering (block elimination):
It takes advantage of any of the matrix blocks being zero and concatenates and into a contiguous multivector to compute and in one block solve.
To solve the transpose of the system, a similar bordering algorithm is implemented. Note however that for the transpose, the constraint object representing must implement the LOCA::MultiContinuation::ConstraintInterfaceMVDX since appears on the right-hand-side of a linear system.
Constructor & Destructor Documentation
Bordering()
LOCA::BorderedSolver::Bordering::Bordering (const Teuchos::RCP< LOCA::GlobalData > & global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > & topParams, const Teuchos::RCP< Teuchos::ParameterList > & solverParams)
Constructor.
Parameters
global_data [in] Global data object
topParams [in] Parsed top-level parameter list
solverParams [in] Bordered solver parameters. Currently none are referenced.
Member Function Documentation
apply()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::Bordering::apply (const NOX::Abstract::MultiVector & X, const NOX::Abstract::MultiVector::DenseMatrix & Y, NOX::Abstract::MultiVector & U, NOX::Abstract::MultiVector::DenseMatrix & V) const virtual
Computed extended matrix-multivector product.
Computes
Implements LOCA::BorderedSolver::AbstractStrategy.
References NOX::Abstract::Group::Failed, NOX::Abstract::MultiVector::multiply(), and NOX::Abstract::MultiVector::update().
applyInverse()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::Bordering::applyInverse (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const virtual
Solves the extended system as defined above using bordering.
The params argument is the linear solver parameters. If isZeroF or isZeroG is true, than the corresponding F or G pointers may be NULL.
Implements LOCA::BorderedSolver::AbstractStrategy.
References NOX::Abstract::MultiVector::clone(), NOX::Abstract::MultiVector::numVectors(), LOCA::BorderedSolver::LowerTriangularBlockElimination::solve(), and LOCA::BorderedSolver::UpperTriangularBlockElimination::solve().
applyInverseTranspose()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::Bordering::applyInverseTranspose (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector * F, const NOX::Abstract::MultiVector::DenseMatrix * G, NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector::DenseMatrix & Y) const virtual
Solves the transpose of the extended system as defined above using bordering.
The params argument is the linear solver parameters. If isZeroF or isZeroG is true, than the corresponding F or G pointers may be NULL. Note that for the transpose solve B must be of type LOCA::MultiContinuation::ConstraintInterfaceMVDX.
Implements LOCA::BorderedSolver::AbstractStrategy.
References NOX::Abstract::MultiVector::clone(), NOX::Abstract::MultiVector::numVectors(), LOCA::BorderedSolver::LowerTriangularBlockElimination::solveTranspose(), and LOCA::BorderedSolver::UpperTriangularBlockElimination::solveTranspose().
applyTranspose()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::Bordering::applyTranspose (const NOX::Abstract::MultiVector & X, const NOX::Abstract::MultiVector::DenseMatrix & Y, NOX::Abstract::MultiVector & U, NOX::Abstract::MultiVector::DenseMatrix & V) const virtual
Computed extended matrix transpose-multivector product.
Computes
Implements LOCA::BorderedSolver::AbstractStrategy.
References NOX::Abstract::Group::Failed, and NOX::Abstract::MultiVector::multiply().
initForSolve()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::Bordering::initForSolve () virtual
Intialize solver for a solve.
This should be called after setMatrixBlocks(), but before applyInverse().
Implements LOCA::BorderedSolver::AbstractStrategy.
References NOX::Abstract::Group::Ok.
initForTransposeSolve()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::Bordering::initForTransposeSolve () virtual
Intialize solver for a transpose solve.
This should be called after setMatrixBlocks(), but before applyInverseTranspose().
Implements LOCA::BorderedSolver::AbstractStrategy.
References NOX::Abstract::Group::Ok.
setMatrixBlocks()
void LOCA::BorderedSolver::Bordering::setMatrixBlocks (const Teuchos::RCP< const LOCA::BorderedSolver::AbstractOperator > & op, const Teuchos::RCP< const NOX::Abstract::MultiVector > & blockA, const Teuchos::RCP< const LOCA::MultiContinuation::ConstraintInterface > & blockB, const Teuchos::RCP< const NOX::Abstract::MultiVector::DenseMatrix > & blockC) virtual
Set blocks.
The blockA or blockC pointer may be null if either is zero. Whether block B is zero will be determined by querying blockB via ConstraintInterface::isConstraintDerivativesXZero.
Implements LOCA::BorderedSolver::AbstractStrategy.
The documentation for this class was generated from the following files:
LOCA_BorderedSolver_Bordering.H
LOCA_BorderedSolver_Bordering.C