NOX: LOCA::SingularJacobianSolve::Manager Class Reference
LOCA::SingularJacobianSolve::Manager Class Reference
Manager for all singular Jacobian solve computations
#include <LOCA_SingularJacobianSolve_Manager.H>
Public Member Functions
Manager (Teuchos::ParameterList &params)
Constructor.
Manager (const Teuchos::ParameterList &params=Teuchos::ParameterList())
Constructor.
Manager (const Manager &source)
Copy constructor.
virtual ~Manager ()
Destructor.
virtual LOCA::SingularJacobianSolve::Generic * clone () const
Clone function.
virtual LOCA::SingularJacobianSolve::Generic & operator= (const LOCA::SingularJacobianSolve::Generic &source)
Assignment operator.
virtual Manager & operator= (const Manager &source)
Assignment operator.
virtual NOX::Abstract::Group::ReturnType reset (Teuchos::ParameterList &params)
Reset parameters.
virtual NOX::Abstract::Group::ReturnType compute (Teuchos::ParameterList &params, LOCA::Continuation::AbstractGroup &grp, const NOX::Abstract::Vector &input, const NOX::Abstract::Vector &approxNullVec, const NOX::Abstract::Vector &jacApproxNullVec, NOX::Abstract::Vector &result)
Computes solution based on method parameter.
virtual NOX::Abstract::Group::ReturnType computeMulti (Teuchos::ParameterList &params, LOCA::Continuation::AbstractGroup &grp, const NOX::Abstract::Vector *const *inputs, const NOX::Abstract::Vector &approxNullVec, const NOX::Abstract::Vector &jacApproxNullVec, NOX::Abstract::Vector **results, int nVecs)
Computes solution based on method parameter for multiple RHS.
const std::string & getMethod () const
Returns current method.
Public Member Functions inherited from LOCA::SingularJacobianSolve::Generic
Generic ()
Constructor.
Generic (const Generic &source)
Copy constructor.
virtual ~Generic ()
Destructor.
Protected Attributes
std::string method
Stores predictor method name.
LOCA::SingularJacobianSolve::Generic * singularSolverPtr
Stores pointer to current singular solver object.
Detailed Description
Manager for all singular Jacobian solve computations
The parameters passed to the constructor or reset should specify the "Method", as described below, as well as any additional parameters for that particular method.
"Method" - Name of the singular jacobian solve method. Valid choices are
"Default" (LOCA::SingularJacobianSolve::Default) [Default]
"Nic" (LOCA::SingularJacobianSolve::Nic)
"Nic-Day" (LOCA::SingularJacobianSolve::NicDay)
"Iterative Refinement" (LOCA::SingularJacobianSolve::ItRef)
Member Function Documentation
clone()
LOCA::SingularJacobianSolve::Generic * LOCA::SingularJacobianSolve::Manager::clone () const virtual
Clone function.
Implements LOCA::SingularJacobianSolve::Generic.
compute()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::Manager::compute (Teuchos::ParameterList & params, LOCA::Continuation::AbstractGroup & grp, const NOX::Abstract::Vector & input, const NOX::Abstract::Vector & approxNullVec, const NOX::Abstract::Vector & jacApproxNullVec, NOX::Abstract::Vector & result) virtual
Computes solution based on method parameter.
Implements LOCA::SingularJacobianSolve::Generic.
References NOX::Abstract::Group::Failed, and LOCA::ErrorCheck::throwError().
computeMulti()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::Manager::computeMulti (Teuchos::ParameterList & params, LOCA::Continuation::AbstractGroup & grp, const NOX::Abstract::Vector *const * inputs, const NOX::Abstract::Vector & approxNullVec, const NOX::Abstract::Vector & jacApproxNullVec, NOX::Abstract::Vector ** results, int nVecs) virtual
Computes solution based on method parameter for multiple RHS.
Implements LOCA::SingularJacobianSolve::Generic.
References NOX::Abstract::Group::Failed, and LOCA::ErrorCheck::throwError().
operator=()
LOCA::SingularJacobianSolve::Generic & LOCA::SingularJacobianSolve::Manager::operator= (const LOCA::SingularJacobianSolve::Generic & source) virtual
Assignment operator.
Implements LOCA::SingularJacobianSolve::Generic.
reset()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::Manager::reset (Teuchos::ParameterList & params) virtual
Reset parameters.
Implements LOCA::SingularJacobianSolve::Generic.
References NOX::Abstract::Group::Failed, NOX::Abstract::Group::Ok, and LOCA::ErrorCheck::throwError().
Referenced by Manager(), and Manager().
The documentation for this class was generated from the following files:
LOCA_SingularJacobianSolve_Manager.H
LOCA_SingularJacobianSolve_Manager.C