NOX: NOX::Abstract::Vector Class Reference
NOX::Abstract::Vector Class Reference abstract
NOX's pure abstract vector interface for vectors that are used by the nonlinear solver.
#include <NOX_Abstract_Vector.H>
Public Types
enum NormType { TwoNorm , OneNorm , MaxNorm }
Norm types used in norm() calculations.
Public Member Functions
Vector ()
Abstract Vector constructor (does nothing)
virtual ~Vector ()
Abstract Vector destructor (does nothing)
virtual NOX::Abstract::Vector & init (double gamma)=0
Initialize every element of this vector with gamma.
virtual NOX::Abstract::Vector & random (bool useSeed=false, int seed=1)=0
Initialize each element of this vector with a random value.
virtual NOX::Abstract::Vector & abs (const NOX::Abstract::Vector &y)=0
Put element-wise absolute values of source vector y into this vector.
virtual NOX::Abstract::Vector & operator= (const NOX::Abstract::Vector &y)=0
Copy source vector y into this vector.
virtual NOX::Abstract::Vector & reciprocal (const NOX::Abstract::Vector &y)=0
Put element-wise reciprocal of source vector y into this vector.
virtual NOX::Abstract::Vector & scale (double gamma)=0
Scale each element of this vector by gamma.
virtual NOX::Abstract::Vector & scale (const NOX::Abstract::Vector &a)=0
Scale this vector element-by-element by the vector a.
virtual NOX::Abstract::Vector & update (double alpha, const NOX::Abstract::Vector &a, double gamma=0.0)=0
Compute x = (alpha * a) + (gamma * x) where x is this vector.
virtual NOX::Abstract::Vector & update (double alpha, const NOX::Abstract::Vector &a, double beta, const NOX::Abstract::Vector &b, double gamma=0.0)=0
Compute x = (alpha * a) + (beta * b) + (gamma * x) where x is this vector.
virtual Teuchos::RCP< NOX::Abstract::Vector > clone (NOX::CopyType type=NOX::DeepCopy) const =0
Create a new Vector of the same underlying type by cloning "this", and return a pointer to the new vector.
virtual Teuchos::RCP< NOX::Abstract::MultiVector > createMultiVector (const NOX::Abstract::Vector *const *vecs, int numVecs, NOX::CopyType type=NOX::DeepCopy) const
Create a MultiVector with numVecs+1 columns out of an array of Vectors. The vector stored under this will be the first column with the remaining numVecs columns given by vecs.
virtual Teuchos::RCP< NOX::Abstract::MultiVector > createMultiVector (int numVecs, NOX::CopyType type=NOX::DeepCopy) const
Create a MultiVector with numVecs columns.
virtual double norm (NOX::Abstract::Vector::NormType type=NOX::Abstract::Vector::TwoNorm) const =0
Norm.
virtual double norm (const NOX::Abstract::Vector &weights) const =0
Weighted 2-Norm.
virtual double innerProduct (const NOX::Abstract::Vector &y) const =0
Inner product with y.
virtual NOX::size_type length () const =0
Return the length of vector.
virtual void print (std::ostream &stream) const
Print the vector. To be used for debugging only.
Detailed Description
NOX's pure abstract vector interface for vectors that are used by the nonlinear solver.
This class is a member of the namespace NOX::Abstract.
The user should implement their own concrete implementation of this class or use one of the implementations provided by us.
Author
Tammy Kolda (SNL 8950), Roger Pawlowski (SNL 9233)
Member Enumeration Documentation
NormType
enum NOX::Abstract::Vector::NormType
Norm types used in norm() calculations.
Enumerator
TwoNorm
Use the 2-norm.
OneNorm
Use the 1-norm.
MaxNorm
Use the max-norm, a.k.a. the -norm.
Constructor & Destructor Documentation
~Vector()
virtual NOX::Abstract::Vector::~Vector () inline virtual
Abstract Vector destructor (does nothing)
Reimplemented in NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, NOX::Petsc::Vector, and NOX::Thyra::Vector.
Member Function Documentation
abs()
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::abs (const NOX::Abstract::Vector & y) pure virtual
Put element-wise absolute values of source vector y into this vector.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), and LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus().
clone()
virtual Teuchos::RCP< NOX::Abstract::Vector > NOX::Abstract::Vector::clone (NOX::CopyType type = NOX::DeepCopy) const pure virtual
Create a new Vector of the same underlying type by cloning "this", and return a pointer to the new vector.
If type is NOX::DeepCopy, then we need to create an exact replica of "this". Otherwise, if type is NOX::ShapeCopy, we need only replicate the shape of "this" (the memory is allocated for the objects, but the current values are not copied into the vector). Note that there is no assumption that a vector created by ShapeCopy is initialized to zeros.
Returns
Pointer to newly created vector or NULL if clone is not supported.
Implemented in NOX::Epetra::Vector, NOX::Petsc::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, LOCA::Hopf::ComplexVector, LOCA::Hopf::MooreSpence::ExtendedVector, LOCA::MultiContinuation::ExtendedVector, LOCA::PhaseTransition::ExtendedVector, LOCA::Pitchfork::MooreSpence::ExtendedVector, LOCA::TurningPoint::MooreSpence::ExtendedVector, and NOX::Thyra::Vector.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus(), NOX::StatusTest::NormUpdate::checkStatus(), NOX::StatusTest::NormWRMS::checkStatus(), NOX::Direction::NonlinearCG::compute(), LOCA::SingularJacobianSolve::ItRef::compute(), LOCA::SingularJacobianSolve::Nic::compute(), LOCA::SingularJacobianSolve::NicDay::compute(), LOCA::DerivUtils::computeDCeDxa(), LOCA::DerivUtils::computeDCeDxa(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDwtCeDp(), LOCA::DerivUtils::computeDwtCeDx(), LOCA::DerivUtils::computeDwtJnDp(), LOCA::DerivUtils::computeDwtJnDx(), LOCA::DerivUtils::computeDwtJnDx(), NOX::Direction::Utils::InexactNewton::computeForcingTerm(), LOCA::SingularJacobianSolve::ItRef::computeMulti(), LOCA::SingularJacobianSolve::Nic::computeMulti(), LOCA::SingularJacobianSolve::NicDay::computeMulti(), NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer(), NOX::MeritFunction::SumOfSquares::computeQuadraticModel(), LOCA::Epetra::Group::computeScaledDotProduct(), NOX::LineSearch::Utils::Slope::computeSlope(), NOX::MeritFunction::SumOfSquares::computeSlope(), NOX::LineSearch::Utils::Slope::computeSlopeWithOutJac(), LOCA::Hopf::MinimallyAugmented::Constraint::Constraint(), LOCA::MultiContinuation::ConstraintModelEvaluator::ConstraintModelEvaluator(), NOX::Solver::TensorBased::getDirectionalDerivative(), NOX::Solver::TensorBased::getNormModelResidual(), NOX::MultiVector::MultiVector(), NOX::MultiVector::MultiVector(), LOCA::DerivUtils::perturbXVec(), LOCA::Epetra::AnasaziOperator::Floquet::rayleighQuotient(), LOCA::AnasaziOperator::JacobianInverse::rayleighQuotient(), NOX::Direction::Broyden::BroydenMemoryUnit::reset(), NOX::Direction::Newton::resetForcingTerm(), LOCA::Epetra::Group::setScaleVector(), and LOCA::Extended::Vector::setVector().
createMultiVector() [1/2]
Teuchos::RCP< NOX::Abstract::MultiVector > NOX::Abstract::Vector::createMultiVector (const NOX::Abstract::Vector *const * vecs, int numVecs, NOX::CopyType type = NOX::DeepCopy) const virtual
Create a MultiVector with numVecs+1 columns out of an array of Vectors. The vector stored under this will be the first column with the remaining numVecs columns given by vecs.
The default implementation creates a generic NOX::MultiVector with either Shape or Deep copies of the supplied vectors.
Reimplemented in NOX::Epetra::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
Referenced by LOCA::Homotopy::DeflatedGroup::applyJacobian(), LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobian(), LOCA::Hopf::MooreSpence::ExtendedGroup::applyJacobian(), LOCA::MultiContinuation::ConstrainedGroup::applyJacobian(), LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup::applyJacobian(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::applyJacobian(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobian(), LOCA::Homotopy::DeflatedGroup::applyJacobianInverse(), LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobianInverse(), LOCA::Hopf::MooreSpence::ExtendedGroup::applyJacobianInverse(), LOCA::MultiContinuation::ConstrainedGroup::applyJacobianInverse(), LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup::applyJacobianInverse(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::applyJacobianInverse(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianInverse(), LOCA::Homotopy::DeflatedGroup::applyJacobianTranspose(), LOCA::Hopf::MinimallyAugmented::ExtendedGroup::applyJacobianTranspose(), LOCA::Hopf::MooreSpence::ExtendedGroup::applyJacobianTranspose(), LOCA::MultiContinuation::ConstrainedGroup::applyJacobianTranspose(), LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup::applyJacobianTranspose(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::applyJacobianTranspose(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianTranspose(), LOCA::MultiContinuation::ConstrainedGroup::applyJacobianTransposeInverse(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::applyJacobianTransposeInverse(), LOCA::Hopf::ComplexMultiVector::ComplexMultiVector(), LOCA::Eigensolver::DGGEVStrategy::computeEigenvalues(), LOCA::Eigensolver::AnasaziStrategy::computeEigenvalues(), LOCA::Hopf::MinimallyAugmented::Constraint::Constraint(), LOCA::MultiContinuation::ConstraintModelEvaluator::ConstraintModelEvaluator(), LOCA::Hopf::MooreSpence::ExtendedMultiVector::ExtendedMultiVector(), LOCA::PhaseTransition::ExtendedMultiVector::ExtendedMultiVector(), LOCA::Pitchfork::MooreSpence::ExtendedMultiVector::ExtendedMultiVector(), LOCA::TurningPoint::MooreSpence::ExtendedMultiVector::ExtendedMultiVector(), LOCA::MultiContinuation::ExtendedMultiVector::ExtendedMultiVector(), LOCA::Epetra::AnasaziOperator::Floquet::rayleighQuotient(), LOCA::AnasaziOperator::Cayley::rayleighQuotient(), LOCA::AnasaziOperator::Cayley2Matrix::rayleighQuotient(), LOCA::AnasaziOperator::ShiftInvert::rayleighQuotient(), and LOCA::AnasaziOperator::ShiftInvert2Matrix::rayleighQuotient().
createMultiVector() [2/2]
Teuchos::RCP< NOX::Abstract::MultiVector > NOX::Abstract::Vector::createMultiVector (int numVecs, NOX::CopyType type = NOX::DeepCopy) const virtual
Create a MultiVector with numVecs columns.
The default implementation creates a generic NOX::MultiVector with either Shape or Deep copies of the supplied vector.
Reimplemented in NOX::Epetra::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
init()
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::init (double gamma) pure virtual
Initialize every element of this vector with gamma.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Epetra::Vector, LOCA::Extended::Vector, NOX::Thyra::Vector, NOX::LAPACK::Vector, and NOX::Petsc::Vector.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus(), NOX::Solver::TensorBased::computeTensorDirection(), LOCA::TurningPoint::MinimallyAugmented::Constraint::getInitialVectors(), and NOX::Solver::InexactTrustRegionBased::iterateInexact().
innerProduct()
virtual double NOX::Abstract::Vector::innerProduct (const NOX::Abstract::Vector & y) const pure virtual
Inner product with y.
Here x represents this vector, and we compute its inner product with y as follows:
Returns
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
Referenced by NOX::Direction::NonlinearCG::compute(), NOX::LineSearch::NonlinearCG::compute(), NOX::Direction::Broyden::compute(), LOCA::SingularJacobianSolve::Nic::compute(), LOCA::SingularJacobianSolve::NicDay::compute(), NOX::Solver::TensorBased::computeCurvilinearStep(), LOCA::DerivUtils::computeDwtCeDp(), LOCA::DerivUtils::computeDwtJnDp(), LOCA::SingularJacobianSolve::Nic::computeMulti(), LOCA::SingularJacobianSolve::NicDay::computeMulti(), NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer(), LOCA::Epetra::Group::computeScaledDotProduct(), LOCA::LAPACK::Group::computeScaledDotProduct(), LOCA::Thyra::Group::computeScaledDotProduct(), LOCA::MultiContinuation::AbstractGroup::computeScaledDotProduct(), NOX::LineSearch::Utils::Slope::computeSlope(), NOX::MeritFunction::SumOfSquares::computeSlope(), LOCA::Pitchfork::MooreSpence::AbstractGroup::innerProduct(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), NOX::Solver::InexactTrustRegionBased::iterateStandard(), NOX::Solver::AndersonAcceleration::qrAdd(), LOCA::Epetra::AnasaziOperator::Floquet::rayleighQuotient(), LOCA::AnasaziOperator::Cayley::rayleighQuotient(), LOCA::AnasaziOperator::Cayley2Matrix::rayleighQuotient(), LOCA::AnasaziOperator::JacobianInverse::rayleighQuotient(), LOCA::AnasaziOperator::ShiftInvert::rayleighQuotient(), and LOCA::AnasaziOperator::ShiftInvert2Matrix::rayleighQuotient().
length()
virtual NOX::size_type NOX::Abstract::Vector::length () const pure virtual
Return the length of vector.
Returns
The length of this vector
Note
Even if the vector is distributed across processors, this should return the global length of the vector.
Implemented in NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, NOX::Petsc::Vector, and NOX::Thyra::Vector.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus(), NOX::StatusTest::NormUpdate::checkStatus(), NOX::StatusTest::NormWRMS::checkStatus(), NOX::StatusTest::RelativeNormF::checkStatus(), LOCA::Epetra::Group::computeScaledDotProduct(), LOCA::LAPACK::Group::computeScaledDotProduct(), LOCA::Thyra::Group::computeScaledDotProduct(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::scaleNullVector(), LOCA::Epetra::Group::scaleVector(), LOCA::LAPACK::Group::scaleVector(), and LOCA::Thyra::Group::scaleVector().
norm() [1/2]
virtual double NOX::Abstract::Vector::norm (const NOX::Abstract::Vector & weights) const pure virtual
Weighted 2-Norm.
Here x represents this vector, and we compute its weighted norm as follows:
Returns
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
norm() [2/2]
virtual double NOX::Abstract::Vector::norm (NOX::Abstract::Vector::NormType type = NOX::Abstract::Vector::TwoNorm) const pure virtual
Norm.
Here x represents this vector, and we compute its norm as follows: for each NOX::Abstract::Vector::NormType:
NOX::Abstract::Vector::TwoNorm
NOX::Abstract::Vector::OneNorm
NOX::Abstract::Vector::MaxNorm
Returns
Implemented in NOX::Petsc::Vector, LOCA::Extended::Vector, NOX::LAPACK::Vector, NOX::Thyra::Vector, and NOX::Epetra::Vector.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus(), NOX::StatusTest::FiniteValue::checkStatus(), NOX::StatusTest::RelativeNormF::checkStatus(), NOX::LineSearch::SafeguardedDirection::compute(), NOX::LineSearch::SafeguardedStep::compute(), NOX::Direction::SteepestDescent::compute(), NOX::Solver::InexactTrustRegionBased::computeNorm(), NOX::Thyra::WeightedMeritFunction::computeSlope(), NOX::LineSearch::Utils::Slope::computeSlopeWithOutJac(), NOX::Solver::TensorBased::computeTensorDirection(), LOCA::DerivUtils::epsVector(), LOCA::Homotopy::DeflatedGroup::getNormF(), LOCA::Homotopy::Group::getNormF(), LOCA::Hopf::MinimallyAugmented::ExtendedGroup::getNormF(), LOCA::Hopf::MooreSpence::ExtendedGroup::getNormF(), LOCA::MultiContinuation::ConstrainedGroup::getNormF(), LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup::getNormF(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::getNormF(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::getNormF(), NOX::Solver::TensorBased::printDirectionInfo(), LOCA::MultiContinuation::AbstractGroup::projectToDraw(), NOX::Solver::AndersonAcceleration::qrAdd(), NOX::Direction::Broyden::BroydenMemoryUnit::reset(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::scaleNullVector(), LOCA::TurningPoint::MinimallyAugmented::Constraint::scaleNullVectors(), and NOX::Solver::TrustRegionBased::step().
operator=()
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::operator= (const NOX::Abstract::Vector & y) pure virtual
Copy source vector y into this vector.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, LOCA::Hopf::ComplexVector, LOCA::Hopf::MooreSpence::ExtendedVector, LOCA::MultiContinuation::ExtendedVector, LOCA::PhaseTransition::ExtendedVector, LOCA::Pitchfork::MooreSpence::ExtendedVector, LOCA::TurningPoint::MooreSpence::ExtendedVector, and NOX::Thyra::Vector.
print()
void NOX::Abstract::Vector::print (std::ostream & stream) const virtual
Print the vector. To be used for debugging only.
Reimplemented in NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
Referenced by NOX::LineSearch::SafeguardedDirection::compute(), and NOX::LineSearch::SafeguardedStep::compute().
random()
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::random (bool useSeed = false, int seed = 1) pure virtual
Initialize each element of this vector with a random value.
If useSeed is true, uses the value of seed to seed the random number generator before filling the entries of this vector. So, if two calls are made where useSeed is true and seed is the same, then the vectors returned should be the same.
Default implementation throw an error. Only referenced by LOCA methods.
Returns
Reference to this object
Implemented in NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, NOX::Petsc::Vector, and NOX::Thyra::Vector.
reciprocal()
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::reciprocal (const NOX::Abstract::Vector & y) pure virtual
Put element-wise reciprocal of source vector y into this vector.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), and LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus().
scale() [1/2]
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::scale (const NOX::Abstract::Vector & a) pure virtual
Scale this vector element-by-element by the vector a.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
scale() [2/2]
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::scale (double gamma) pure virtual
Scale each element of this vector by gamma.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, NOX::Thyra::Vector, and NOX::Petsc::Vector.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus(), NOX::Direction::NonlinearCG::compute(), NOX::LineSearch::SafeguardedStep::compute(), NOX::Direction::SteepestDescent::compute(), NOX::Direction::Broyden::compute(), LOCA::DerivUtils::computeDCeDp(), LOCA::DerivUtils::computeDfDp(), LOCA::DerivUtils::computeDJnDp(), LOCA::DerivUtils::computeDwtCeDx(), LOCA::DerivUtils::computeDwtJDp(), LOCA::DerivUtils::computeDwtJnDx(), NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer(), NOX::Thyra::WeightedMeritFunction::computeSlope(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), NOX::Solver::AndersonAcceleration::qrAdd(), LOCA::AnasaziOperator::Cayley::rayleighQuotient(), LOCA::AnasaziOperator::Cayley2Matrix::rayleighQuotient(), LOCA::AnasaziOperator::ShiftInvert::rayleighQuotient(), LOCA::AnasaziOperator::ShiftInvert2Matrix::rayleighQuotient(), LOCA::Extended::Vector::scale(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::scaleNullVector(), LOCA::TurningPoint::MinimallyAugmented::Constraint::scaleNullVectors(), LOCA::Epetra::Group::scaleVector(), LOCA::LAPACK::Group::scaleVector(), and LOCA::Thyra::Group::scaleVector().
update() [1/2]
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::update (double alpha, const NOX::Abstract::Vector & a, double beta, const NOX::Abstract::Vector & b, double gamma = 0.0) pure virtual
Compute x = (alpha * a) + (beta * b) + (gamma * x) where x is this vector.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
update() [2/2]
virtual NOX::Abstract::Vector & NOX::Abstract::Vector::update (double alpha, const NOX::Abstract::Vector & a, double gamma = 0.0) pure virtual
Compute x = (alpha * a) + (gamma * x) where x is this vector.
Here x represents this vector, and we update it as
Returns
Reference to this object
Implemented in NOX::Petsc::Vector, NOX::Epetra::Vector, NOX::LAPACK::Vector, LOCA::Extended::Vector, and NOX::Thyra::Vector.
Referenced by LOCA::Homotopy::Group::applyJacobian(), LOCA::Homotopy::Group::applyJacobianTranspose(), LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus(), NOX::Direction::NonlinearCG::compute(), NOX::Direction::Broyden::compute(), LOCA::SingularJacobianSolve::ItRef::compute(), LOCA::SingularJacobianSolve::Nic::compute(), LOCA::SingularJacobianSolve::NicDay::compute(), NOX::Solver::TensorBased::computeCurvilinearStep(), LOCA::DerivUtils::computeDCeDp(), LOCA::DerivUtils::computeDfDp(), LOCA::DerivUtils::computeDJnDp(), LOCA::DerivUtils::computeDwtCeDx(), LOCA::DerivUtils::computeDwtJDp(), LOCA::DerivUtils::computeDwtJnDx(), LOCA::SingularJacobianSolve::ItRef::computeMulti(), LOCA::SingularJacobianSolve::Nic::computeMulti(), LOCA::SingularJacobianSolve::NicDay::computeMulti(), NOX::Thyra::WeightedMeritFunction::computeSlope(), NOX::Solver::TensorBased::computeTensorDirection(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), and NOX::Solver::AndersonAcceleration::qrAdd().
The documentation for this class was generated from the following files:
NOX_Abstract_Vector.H
NOX_Abstract_Vector.C