NOX: NOX::StatusTest::Combo Class Reference
NOX::StatusTest::Combo Class Reference
Arbitrary combination of status tests.
#include <NOX_StatusTest_Combo.H>
Public Types
enum ComboType { AND , OR }
The test can be either the AND of all the component tests, or the OR of all the component tests.
Public Member Functions
Combo (ComboType t, const NOX::Utils *u=NULL)
Constructor. Optional argument is the error stream for output.
Combo (ComboType t, const Teuchos::RCP< Generic > &a, const NOX::Utils *u=NULL)
Constructor with a single test.
Combo (ComboType t, const Teuchos::RCP< Generic > &a, const Teuchos::RCP< Generic > &b, const NOX::Utils *u=NULL)
Constructor with two tests.
virtual Combo & addStatusTest (const Teuchos::RCP< Generic > &a)
Add another test to this combination.
virtual ~Combo ()
Destructor.
virtual StatusType checkStatus (const NOX::Solver::Generic &problem, NOX::StatusTest::CheckType checkType)
Tests stopping criterion.
virtual StatusType getStatus () const
Return the result of the most recent checkStatus call.
virtual std::ostream & print (std::ostream &stream, int indent=0) const
Output formatted description of stopping test to output stream.
Public Member Functions inherited from NOX::StatusTest::Generic
Generic ()
Constructor.
virtual ~Generic ()
Destructor.
Protected Member Functions
virtual void orOp (const Solver::Generic &problem, NOX::StatusTest::CheckType checkType)
Use this for checkStatus when this is an OR type combo. Updates NOX::StatusTest::Combo::status.
virtual void andOp (const Solver::Generic &problem, NOX::StatusTest::CheckType checkType)
Use this for checkStatus when this is an AND type combo. Updates NOX::StatusTest::Combo::status.
bool isSafe (Generic &a)
Check whether or not it is safe to add a to this list of tests.
Detailed Description
Arbitrary combination of status tests.
In the AND (see NOX::StatusTest::Combo::ComboType) combination, the result is Unconverged (see NOX::StatusTest::StatusType) if any of the tests is Unconverged. Otherwise, the result is equal to the result of the first test in the list that is either Converged or Failed. It is not recommended to mix Converged and Failed tests in an AND combination.
In the OR combination, the result is Unconverged if all of the tests are Unconverged. Otherwise, it is the result of the first test in the list that is either Converged or Failed. Therefore, it will generally make sense to put the Failed -type tests at the end of the OR list.
Note
We call checkStatus on every convergence test, though some may be called with the NOX::StatusTest::None option.
Author
Tammy Kolda (SNL 8950) and Roger Pawlowski (SNL 1416)
Member Enumeration Documentation
ComboType
enum NOX::StatusTest::Combo::ComboType
The test can be either the AND of all the component tests, or the OR of all the component tests.
Enumerator
AND
Logically "AND" together the results of the tests in this combination.
OR
Logically "OR" together the results of the tests in this combination.
Member Function Documentation
addStatusTest()
NOX::StatusTest::Combo & NOX::StatusTest::Combo::addStatusTest (const Teuchos::RCP< Generic > & a) virtual
Add another test to this combination.
Calls isSafe() to determine if it is safe to add a to the combination.
Referenced by Combo().
andOp()
void NOX::StatusTest::Combo::andOp (const Solver::Generic & problem, NOX::StatusTest::CheckType checkType) protected virtual
Use this for checkStatus when this is an AND type combo. Updates NOX::StatusTest::Combo::status.
If any tests are NOX::StatusTest::Unconverged, then the status of this test is NOX::StatusTest::Unconverged. If there is a combination of NOX::StatusTest::Failed and NOX::StatusTest::Converged in the tests that are AND'd together, the value of status for this test is set to the status of the first test it encounters. The tests are evaluated in the order that they were added to the combination.
Note
We compute the status of all tests in the combination for the sake of completeness, even if we could determine the status of this combination test without that check.
References NOX::StatusTest::Minimal, NOX::StatusTest::None, NOX::StatusTest::Unconverged, and NOX::StatusTest::Unevaluated.
checkStatus()
NOX::StatusTest::StatusType NOX::StatusTest::Combo::checkStatus (const NOX::Solver::Generic & problem, NOX::StatusTest::CheckType checkType) virtual
Tests stopping criterion.
See addOp() and orOp() for details.
Implements NOX::StatusTest::Generic.
getStatus()
NOX::StatusTest::StatusType NOX::StatusTest::Combo::getStatus () const virtual
Return the result of the most recent checkStatus call.
Implements NOX::StatusTest::Generic.
isSafe()
bool NOX::StatusTest::Combo::isSafe (Generic & a) protected
Check whether or not it is safe to add a to this list of tests.
This is necessary to avoid any infinite recursions (i.e., a test cannot own a copy of itself).
References isSafe().
Referenced by isSafe().
orOp()
void NOX::StatusTest::Combo::orOp (const Solver::Generic & problem, NOX::StatusTest::CheckType checkType) protected virtual
Use this for checkStatus when this is an OR type combo. Updates NOX::StatusTest::Combo::status.
If there is a combination of NOX::StatusTest::Failed and NOX::StatusTest::Converged in the tests that are OR'd together, the value of status for this test is set to the status of the first test it encounters which is not NOX::Status::Unconvered. The tests are evaluated in the order that they were added to the combination.
Note
We compute the status of all tests in the combination for the sake of completeness, even if we could determine the status of this combination test without that check.
References NOX::StatusTest::Minimal, NOX::StatusTest::None, NOX::StatusTest::Unconverged, and NOX::StatusTest::Unevaluated.
print()
std::ostream & NOX::StatusTest::Combo::print (std::ostream & stream, int indent = 0) const virtual
Output formatted description of stopping test to output stream.
Implements NOX::StatusTest::Generic.
The documentation for this class was generated from the following files:
NOX_StatusTest_Combo.H
NOX_StatusTest_Combo.C