NOX: LOCA::LAPACK::Interface Class Reference
LOCA::LAPACK::Interface Class Reference abstract
Virtual interface for LOCA::LAPACK::Group to provide a link to the external code for RHS and Jacobian fills.
#include <LOCA_LAPACK_Interface.H>
Public Member Functions
Interface ()
Constructor.
virtual ~Interface ()
Destructor.
virtual void setParams (const ParameterVector &p)=0
Set the problem parameters.
virtual void printSolution (const NOX::LAPACK::Vector &, const double)
Call user's own print routine for vector-parameter pair.
virtual bool computeShiftedMatrix (double alpha, double beta, const NOX::LAPACK::Vector &x, NOX::LAPACK::Matrix< double > &A)
Compute shifted matrix alpha*J + beta*M where J is the Jacobian matrix and M is the mass matrix. Returns true if computation was successful.
virtual void projectToDraw (const NOX::LAPACK::Vector &x, double *px) const
Projects solution to a few scalars for multiparameter continuation.
virtual int projectToDrawDimension () const
Returns the dimension of the project to draw array.
Public Member Functions inherited from NOX::LAPACK::Interface
Interface ()
Constructor.
virtual const NOX::LAPACK::Vector & getInitialGuess ()=0
Get initial guess.
virtual bool computeF (NOX::LAPACK::Vector &rhs, const NOX::LAPACK::Vector &x)=0
Compute RHS given the specified input vector x. Returns true if computation was successful.
virtual bool computeJacobian (NOX::LAPACK::Matrix< double > &J, const NOX::LAPACK::Vector &x)=0
Compute Jacobian given the specified input vector x. Returns true if computation was successful.
Detailed Description
Virtual interface for LOCA::LAPACK::Group to provide a link to the external code for RHS and Jacobian fills.
This interface is derived from the NOX::LAPACK::Interface and and additionally provides a method for setting problem parameters.
Constructor & Destructor Documentation
~Interface()
virtual LOCA::LAPACK::Interface::~Interface () inline virtual
Destructor.
Reimplemented from NOX::LAPACK::Interface.
Member Function Documentation
computeShiftedMatrix()
virtual bool LOCA::LAPACK::Interface::computeShiftedMatrix (double alpha, double beta, const NOX::LAPACK::Vector & x, NOX::LAPACK::Matrix< double > & A) inline virtual
Compute shifted matrix alpha*J + beta*M where J is the Jacobian matrix and M is the mass matrix. Returns true if computation was successful.
The default implementation assumes the mass matrix is the identity matrix.
References NOX::LAPACK::Interface::computeJacobian(), NOX::LAPACK::Matrix< T >::numCols(), NOX::LAPACK::Matrix< T >::numRows(), and NOX::LAPACK::Matrix< T >::scale().
projectToDraw()
virtual void LOCA::LAPACK::Interface::projectToDraw (const NOX::LAPACK::Vector & x, double * px) const inline virtual
Projects solution to a few scalars for multiparameter continuation.
Default implementation is the max norm
References NOX::Abstract::Vector::MaxNorm, and NOX::LAPACK::Vector::norm().
The documentation for this class was generated from the following file:
LOCA_LAPACK_Interface.H