NOX: LOCA::MultiContinuation::ConstrainedGroup Class Reference
LOCA::MultiContinuation::ConstrainedGroup Class Reference
Extended group representing a constrained nonlinear problem.
#include <LOCA_MultiContinuation_ConstrainedGroup.H>
Public Member Functions
ConstrainedGroup (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > &topParams, const Teuchos::RCP< Teuchos::ParameterList > &constraintParams, const Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > &grp, const Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > &constraints, const std::vector< int > &paramIDs, bool skip_dfdp=false)
Constructor.
ConstrainedGroup (const ConstrainedGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~ConstrainedGroup ()
Destructor.
virtual void setConstraintParameter (int i, double val)
Set constraint parameter i to value val.
virtual double getConstraintParameter (int i) const
Get constraint parameter i.
virtual const std::vector< int > & getConstraintParamIDs () const
Get constraint parameter IDs.
Implementation of NOX::Abstract::Group virtual methods
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Assignment operator.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const
Clone function.
virtual void setX (const NOX::Abstract::Vector &y)
Set the solution vector to y.
virtual void computeX (const NOX::Abstract::Group &g, const NOX::Abstract::Vector &d, double step)
Compute and return solution vector, x, where this.x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()
Compute extended continuation equations.
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute extended continuation jacobian.
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Gradient is not defined for this system.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute Newton direction for extended continuation system.
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Jacobian transpose not defined for this system.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian inverse for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian for extended system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Jacobian transpose not defined for this system.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Applies Jacobian inverse for extended system.
virtual bool isF () const
Return true if extended residual is valid.
virtual bool isJacobian () const
Return true if the extended Jacobian is valid.
virtual bool isGradient () const
Always returns false.
virtual bool isNewton () const
Return true if the extended Newton direction is valid.
virtual const NOX::Abstract::Vector & getX () const
Return extended solution vector.
virtual const NOX::Abstract::Vector & getF () const
Return extended residual.
virtual double getNormF () const
Return 2-norm of extended residual.
virtual const NOX::Abstract::Vector & getGradient () const
Gradient is never valid.
virtual const NOX::Abstract::Vector & getNewton () const
Return extended Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const
Return RCP to extended solution vector.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const
Return RCP to extended residual.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const
Gradient is never valid.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const
Return RCP to extended Newton direction.
virtual double getNormNewtonSolveResidual () const
Returns 2-norm of extended Newton solve residual.
Implementation of LOCA::Extended::MultiAbstractGroup
virtual methods
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup () const
Return underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getUnderlyingGroup ()
Return underlying group.
Implementation of LOCA::MultiContinuation::AbstractGroup
virtual methods
virtual void copy (const NOX::Abstract::Group &source)
Assignment operator.
virtual void setParamsMulti (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Set parameters indexed by (integer) paramIDs.
virtual void setParams (const ParameterVector &p)
Set the parameter vector in the group to p (pVector = p).
virtual void setParam (int paramID, double val)
Set parameter indexed by (integer) paramID.
virtual void setParam (std::string paramID, double val)
Set parameter indexed by (std::string) paramID.
virtual const ParameterVector & getParams () const
Return a const reference to the ParameterVector owned by the group.
virtual double getParam (int paramID) const
Return copy of parameter indexed by (integer) paramID.
virtual double getParam (std::string paramID) const
Return copy of parameter indexed by (std::string) paramID.
virtual NOX::Abstract::Group::ReturnType computeDfDpMulti (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector &dfdp, bool isValidF)
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any postprocessing after a continuation step finishes.
virtual void projectToDraw (const NOX::Abstract::Vector &x, double *px) const
Projects solution to a few scalars for multiparameter continuation.
virtual int projectToDrawDimension () const
Returns the dimension of the project to draw array.
virtual double computeScaledDotProduct (const NOX::Abstract::Vector &a, const NOX::Abstract::Vector &b) const
Compute a scaled dot product.
virtual void printSolution (const double conParam) const
Function to print out solution and parameter after successful step.
virtual void printSolution (const NOX::Abstract::Vector &x, const double conParam) const
Function to print out a vector and parameter after successful step.
virtual void scaleVector (NOX::Abstract::Vector &x) const
Scales a vector using scaling vector.
Implementation of
LOCA::BorderedSystem::AbstractGroup virtual methods
virtual int getBorderedWidth () const
Return the total width of the bordered rows/columns.
virtual Teuchos::RCP< const NOX::Abstract::Group > getUnborderedGroup () const
Get bottom-level unbordered group.
virtual bool isCombinedAZero () const
Indicates whether combined A block is zero.
virtual bool isCombinedBZero () const
Indicates whether combined B block is zero.
virtual bool isCombinedCZero () const
Indicates whether combined C block is zero.
virtual void extractSolutionComponent (const NOX::Abstract::MultiVector &v, NOX::Abstract::MultiVector &v_x) const
virtual void extractParameterComponent (bool use_transpose, const NOX::Abstract::MultiVector &v, NOX::Abstract::MultiVector::DenseMatrix &v_p) const
virtual void loadNestedComponents (const NOX::Abstract::MultiVector &v_x, const NOX::Abstract::MultiVector::DenseMatrix &v_p, NOX::Abstract::MultiVector &v) const
virtual void fillA (NOX::Abstract::MultiVector &A) const
Fill the combined A block as described above.
virtual void fillB (NOX::Abstract::MultiVector &B) const
Fill the combined B block as described above.
virtual void fillC (NOX::Abstract::MultiVector::DenseMatrix &C) const
Fill the combined C block as described above.
Public Member Functions inherited from LOCA::Extended::MultiAbstractGroup
MultiAbstractGroup ()
Default constructor.
virtual ~MultiAbstractGroup ()
Destructor.
virtual Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup () const
Return base-level underlying group.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getBaseLevelUnderlyingGroup ()
Return base-level underlying group.
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Override from NOX::Abstract::Group base class. Calls getUnderlyingGroup() from this class.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual const NOX::Abstract::Vector & getScaledX () const
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
Public Member Functions inherited from LOCA::Abstract::Group
Group (const Teuchos::RCP< LOCA::GlobalData > &global_data)
Constructor.
Group (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::DerivUtils > &deriv)
Constructor.
Group (const Group &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~Group ()
Destructor.
virtual NOX::Abstract::Group::ReturnType augmentJacobianForHomotopy (double a, double b)
Replace Jacobian by where is the identity matrix and is a scalar.
virtual NOX::Abstract::Group::ReturnType computeShiftedMatrix (double alpha, double beta)
Compute the shifted matrix.
virtual NOX::Abstract::Group::ReturnType applyShiftedMatrix (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Multiply the shifted matrix by a vector.
virtual NOX::Abstract::Group::ReturnType applyShiftedMatrixMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Multiply the shifted matrix by a multi-vector.
virtual NOX::Abstract::Group::ReturnType applyShiftedMatrixInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Apply the inverse of the shifted matrix by a multi-vector, as needed by the shift-and-invert and generalized Cayley transformations.
virtual NOX::Abstract::Group::ReturnType computeSecondShiftedMatrix (double alpha, double beta)
Compute the second shifted matrix. Can avoid recomputing if two are stored.
virtual NOX::Abstract::Group::ReturnType applySecondShiftedMatrix (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Multiply the shifted matrix by a vector.
virtual NOX::Abstract::Group::ReturnType applySecondShiftedMatrixMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Multiply the shifted matrix by a multi-vector.
virtual bool isComplex () const
Is valid.
virtual NOX::Abstract::Group::ReturnType computeComplex (double frequency)
Compute .
virtual NOX::Abstract::Group::ReturnType applyComplex (const NOX::Abstract::Vector &input_real, const NOX::Abstract::Vector &input_imag, NOX::Abstract::Vector &result_real, NOX::Abstract::Vector &result_imag) const
Compute .
virtual NOX::Abstract::Group::ReturnType applyComplexMultiVector (const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
Compute .
virtual NOX::Abstract::Group::ReturnType applyComplexInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
Solve .
virtual NOX::Abstract::Group::ReturnType applyComplexTranspose (const NOX::Abstract::Vector &input_real, const NOX::Abstract::Vector &input_imag, NOX::Abstract::Vector &result_real, NOX::Abstract::Vector &result_imag) const
virtual NOX::Abstract::Group::ReturnType applyComplexTransposeMultiVector (const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
virtual NOX::Abstract::Group::ReturnType applyComplexTransposeInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
Solve .
virtual void notifyCompletedStep ()
virtual double computeFreeEnergy ()
Computes the free energy at the current solution and parameter values.
Public Member Functions inherited from LOCA::Homotopy::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::MultiContinuation::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::TurningPoint::MinimallyAugmented::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~FiniteDifferenceGroup ()
Destructor.
virtual NOX::Abstract::Group::ReturnType computeDwtJnDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &w, const NOX::Abstract::Vector &nullVector, NOX::Abstract::MultiVector::DenseMatrix &result, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDwtJDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &w, NOX::Abstract::MultiVector &result, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDwtJnDx (const NOX::Abstract::Vector &w, const NOX::Abstract::Vector &nullVector, NOX::Abstract::Vector &result)
Computes the derivative .
Public Member Functions inherited from LOCA::TurningPoint::MinimallyAugmented::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::TurningPoint::MooreSpence::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::TurningPoint::MooreSpence::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual NOX::Abstract::Group::ReturnType computeDJnDpMulti (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &nullVector, NOX::Abstract::MultiVector &result, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDJnDxaMulti (const NOX::Abstract::Vector &nullVector, const NOX::Abstract::MultiVector &aVector, NOX::Abstract::MultiVector &result)
Computes the directional derivative for the given direction .
virtual NOX::Abstract::Group::ReturnType computeDJnDxaMulti (const NOX::Abstract::Vector &nullVector, const NOX::Abstract::Vector &JnVector, const NOX::Abstract::MultiVector &aVector, NOX::Abstract::MultiVector &result)
Computes the directional derivative for the given direction .
virtual NOX::Abstract::Group::ReturnType computeDwtJnDxMulti (const NOX::Abstract::MultiVector &w, const NOX::Abstract::Vector &nullVector, NOX::Abstract::MultiVector &result)
Computes the derivative .
Public Member Functions inherited from LOCA::MultiContinuation::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual void setDerivUtils (const Teuchos::RCP< LOCA::DerivUtils > &deriv)
Set the LOCA::DerivUtils object.
Public Member Functions inherited from LOCA::Pitchfork::MinimallyAugmented::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::Pitchfork::MooreSpence::AbstractGroup
AbstractGroup ()
Default constructor.
virtual double innerProduct (const NOX::Abstract::Vector &a, const NOX::Abstract::Vector &b) const
Compute the inner product of a and b.
virtual void innerProduct (const NOX::Abstract::MultiVector &a, const NOX::Abstract::MultiVector &b, NOX::Abstract::MultiVector::DenseMatrix &c) const
Compute the inner product of a and b.
Public Member Functions inherited from LOCA::Hopf::MinimallyAugmented::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~FiniteDifferenceGroup ()
Destructor.
virtual NOX::Abstract::Group::ReturnType computeDwtCeDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &w1, const NOX::Abstract::Vector &w2, const NOX::Abstract::Vector &y, const NOX::Abstract::Vector &x, double omega, NOX::Abstract::MultiVector::DenseMatrix &result_real, NOX::Abstract::MultiVector::DenseMatrix &result_imag, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDwtCeDx (const NOX::Abstract::Vector &w1, const NOX::Abstract::Vector &w2, const NOX::Abstract::Vector &y, const NOX::Abstract::Vector &z, double omega, NOX::Abstract::Vector &result_real, NOX::Abstract::Vector &result_imag)
Computes the derivative .
Public Member Functions inherited from LOCA::Hopf::MinimallyAugmented::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::Hopf::MooreSpence::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::TimeDependent::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::Hopf::MooreSpence::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual NOX::Abstract::Group::ReturnType computeDCeDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &yVector, const NOX::Abstract::Vector &zVector, double w, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag, bool isValid)
Computes the derivative where is the parameter indexed by paramIDs.
virtual NOX::Abstract::Group::ReturnType computeDCeDxa (const NOX::Abstract::Vector &yVector, const NOX::Abstract::Vector &zVector, double w, const NOX::Abstract::MultiVector &aVector, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag)
Computes the directional derivative for the given direction .
virtual NOX::Abstract::Group::ReturnType computeDCeDxa (const NOX::Abstract::Vector &yVector, const NOX::Abstract::Vector &zVector, double w, const NOX::Abstract::MultiVector &aVector, const NOX::Abstract::Vector &Ce_real, const NOX::Abstract::Vector &Ce_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag)
Computes the directional derivative for the given direction . The arguments Ce_real and Ce_imag hold the real and imaginary components of .
Public Member Functions inherited from LOCA::PhaseTransition::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::BorderedSystem::AbstractGroup
AbstractGroup ()
Constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::Abstract::TransposeSolveGroup
TransposeSolveGroup ()
Constructor.
virtual ~TransposeSolveGroup ()
Destructor.
Implementation of LOCA::Abstract::TransposeSolveGroup
virtual methods
Teuchos::RCP< LOCA::GlobalData > globalData
Pointer LOCA global data object.
Teuchos::RCP< LOCA::Parameter::SublistParser > parsedParams
Parsed top-level parameters.
Teuchos::RCP< Teuchos::ParameterList > constraintParams
Constraint parameter list.
Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > grpPtr
Pointer to base group that defines .
Teuchos::RCP< LOCA::BorderedSystem::AbstractGroup > bordered_grp
Pointer to base group as a bordered group.
Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > constraintsPtr
Pointer to constraint object.
int numParams
Number of parameters.
LOCA::MultiContinuation::ExtendedMultiVector xMultiVec
Stores the extended solution vector.
LOCA::MultiContinuation::ExtendedMultiVector fMultiVec
Stores the extended residual vector and df/dp.
LOCA::MultiContinuation::ExtendedMultiVector newtonMultiVec
Stores the extended Newton vector.
LOCA::MultiContinuation::ExtendedMultiVector gradientMultiVec
Stores the extended gradient vector.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > xVec
Stores view of first column of xMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > fVec
Stores view of first column of fMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedMultiVector > ffMultiVec
Stores view of first column of fMultiVec as a multivec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedMultiVector > dfdpMultiVec
Stores view of df/dp columns of fMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > newtonVec
Stores view of first column of newtonMultiVec.
Teuchos::RCP< LOCA::MultiContinuation::ExtendedVector > gradientVec
Stores view of first column of gradientMultiVec.
Teuchos::RCP< LOCA::BorderedSolver::JacobianOperator > jacOp
Teuchos::RCP< LOCA::BorderedSolver::AbstractStrategy > borderedSolver
Stores bordered solver strategy.
std::vector< int > index_f
Stores indices for getting f part of fMultiVec.
std::vector< int > index_dfdp
Stores indices for getting df/dp part of fMultiVec.
std::vector< int > constraintParamIDs
integer id of constraint parameters
bool isValidF
Is residual vector valid.
bool isValidJacobian
Is Jacobian matrix valid.
bool isValidNewton
Is Newton vector valid.
bool isValidGradient
Is Gradient vector valid.
bool isBordered
Flag that indicates whether underlying group is a bordered group.
bool skipDfDp
Flag indicating whether to skip df/dp computations.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Solve Jacobian-tranpose system.
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Solve Jacobian-tranpose system with multiple right-hand sides.
virtual Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > getGroup ()
Get group.
virtual Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > getConstraints ()
Get constraints.
virtual void resetIsValid ()
Resets all isValid flags to false.
virtual void setupViews ()
Sets up multivector views.
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Protected Attributes inherited from LOCA::Abstract::Group
Teuchos::RCP< LOCA::GlobalData > globalData
Global data.
Protected Attributes inherited from LOCA::MultiContinuation::FiniteDifferenceGroup
Teuchos::RCP< DerivUtils > derivPtr
Pointer to current DerivUtils derivative computation object.
Detailed Description
Extended group representing a constrained nonlinear problem.
This class represents a constrained system of nonlinear equations:
where is the solution vector, is a set of constraint parameters, is represented by some LOCA::MultiContinuation::AbstractGroup, and is a constraint represented by a LOCA::MultiContinuation::ConstraintInterface object. Newton steps for this system are computed via some LOCA::BorderedSolver::AbstractStrategy which is specified via the constraintParams argument to the constructor.
Constructor & Destructor Documentation
ConstrainedGroup()
LOCA::MultiContinuation::ConstrainedGroup::ConstrainedGroup (const Teuchos::RCP< LOCA::GlobalData > & global_data, const Teuchos::RCP< LOCA::Parameter::SublistParser > & topParams, const Teuchos::RCP< Teuchos::ParameterList > & constraintParams, const Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > & grp, const Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > & constraints, const std::vector< int > & paramIDs, bool skip_dfdp = false)
Constructor.
Parameters
global_data [in] Global data object
topParams [in] Parsed top-level parameter list.
constraintParams [in] Parameter list determining the bordered solver method.
grp [in] Group representing .
constraints [in] Constraint object representing .
paramIDs [in] Parameter IDs of the constraint parameters
skip_dfdp [in] Whether to skip computation of df/dp when computing extended Jacobian.
References bordered_grp, borderedSolver, constraintParamIDs, constraintParams, constraintsPtr, globalData, grpPtr, isBordered, numParams, parsedParams, setupViews(), and xVec.
Member Function Documentation
applyJacobian()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobian (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian for extended system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianInverse()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobianInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian inverse for extended system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobianInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian inverse for extended system.
Reimplemented from NOX::Abstract::Group.
References LOCA::Extended::MultiVector::getScalars(), LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec(), and NOX::Abstract::Group::Ok.
applyJacobianMultiVector()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobianMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Applies Jacobian for extended system.
Reimplemented from NOX::Abstract::Group.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
applyJacobianTranspose()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobianTranspose (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Jacobian transpose not defined for this system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianTransposeInverse()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobianTransposeInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Solve Jacobian-tranpose system.
Implements LOCA::Abstract::TransposeSolveGroup.
References NOX::Abstract::Vector::createMultiVector(), and NOX::DeepCopy.
applyJacobianTransposeInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobianTransposeInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Solve Jacobian-tranpose system with multiple right-hand sides.
Implements LOCA::Abstract::TransposeSolveGroup.
References LOCA::Extended::MultiVector::getScalars(), LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec(), and NOX::Abstract::Group::Ok.
applyJacobianTransposeMultiVector()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Jacobian transpose not defined for this system.
Reimplemented from NOX::Abstract::Group.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
clone()
Teuchos::RCP< NOX::Abstract::Group > LOCA::MultiContinuation::ConstrainedGroup::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Clone function.
Implements NOX::Abstract::Group.
computeDfDpMulti()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::computeDfDpMulti (const std::vector< int > & paramIDs, NOX::Abstract::MultiVector & dfdp, bool isValidF) virtual
Compute for each parameter indexed by paramIDs. The first column of dfdp holds F, which is valid if isValidF is true. Otherwise F must be computed.
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::MultiVector::getScalars(), LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec(), and NOX::Abstract::Group::Ok.
computeF()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::computeF () virtual
Compute extended continuation equations.
Implements NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeGradient()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::computeGradient () virtual
Gradient is not defined for this system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeJacobian()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::computeJacobian () virtual
Compute extended continuation jacobian.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeNewton()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::ConstrainedGroup::computeNewton (Teuchos::ParameterList & params) virtual
Compute Newton direction for extended continuation system.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
computeScaledDotProduct()
double LOCA::MultiContinuation::ConstrainedGroup::computeScaledDotProduct (const NOX::Abstract::Vector & a, const NOX::Abstract::Vector & b) const virtual
Compute a scaled dot product.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::Vector::getScalar(), and LOCA::MultiContinuation::ExtendedVector::getXVec().
computeX()
void LOCA::MultiContinuation::ConstrainedGroup::computeX (const NOX::Abstract::Group & g, const NOX::Abstract::Vector & d, double step) virtual
Compute and return solution vector, x, where this.x = grp.x + step * d.
Implements NOX::Abstract::Group.
References getX(), LOCA::MultiContinuation::ExtendedVector::getXVec(), grpPtr, and LOCA::Extended::Vector::update().
copy()
void LOCA::MultiContinuation::ConstrainedGroup::copy (const NOX::Abstract::Group & source) virtual
Assignment operator.
Reimplemented from LOCA::Abstract::Group.
References constraintParamIDs, constraintParams, constraintsPtr, fMultiVec, globalData, gradientMultiVec, grpPtr, index_dfdp, index_f, isValidF, isValidGradient, isValidJacobian, isValidNewton, newtonMultiVec, numParams, parsedParams, skipDfDp, and xMultiVec.
extractParameterComponent()
void LOCA::MultiContinuation::ConstrainedGroup::extractParameterComponent (bool use_transpose, const NOX::Abstract::MultiVector & v, NOX::Abstract::MultiVector::DenseMatrix & v_p) const virtual
Given the vector v, extract the parameter components of all of the nested subvectors in v down to the solution component for the unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
extractSolutionComponent()
void LOCA::MultiContinuation::ConstrainedGroup::extractSolutionComponent (const NOX::Abstract::MultiVector & v, NOX::Abstract::MultiVector & v_x) const virtual
Given the vector v, extract the underlying solution component corresponding to the unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
References LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
fillA()
void LOCA::MultiContinuation::ConstrainedGroup::fillA (NOX::Abstract::MultiVector & A) const virtual
Fill the combined A block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
References NOX::Abstract::MultiVector::subView().
fillB()
void LOCA::MultiContinuation::ConstrainedGroup::fillB (NOX::Abstract::MultiVector & B) const virtual
Fill the combined B block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
References NOX::Abstract::MultiVector::init(), and NOX::Abstract::MultiVector::subView().
fillC()
void LOCA::MultiContinuation::ConstrainedGroup::fillC (NOX::Abstract::MultiVector::DenseMatrix & C) const virtual
Fill the combined C block as described above.
Implements LOCA::BorderedSystem::AbstractGroup.
getBorderedWidth()
int LOCA::MultiContinuation::ConstrainedGroup::getBorderedWidth () const virtual
Return the total width of the bordered rows/columns.
Implements LOCA::BorderedSystem::AbstractGroup.
getF()
const NOX::Abstract::Vector & LOCA::MultiContinuation::ConstrainedGroup::getF () const virtual
Return extended residual.
Implements NOX::Abstract::Group.
getFPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::MultiContinuation::ConstrainedGroup::getFPtr () const virtual
Return RCP to extended residual.
Implements NOX::Abstract::Group.
getGradient()
const NOX::Abstract::Vector & LOCA::MultiContinuation::ConstrainedGroup::getGradient () const virtual
Gradient is never valid.
Implements NOX::Abstract::Group.
getGradientPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::MultiContinuation::ConstrainedGroup::getGradientPtr () const virtual
Gradient is never valid.
Implements NOX::Abstract::Group.
getNewton()
const NOX::Abstract::Vector & LOCA::MultiContinuation::ConstrainedGroup::getNewton () const virtual
Return extended Newton direction.
Implements NOX::Abstract::Group.
getNewtonPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::MultiContinuation::ConstrainedGroup::getNewtonPtr () const virtual
Return RCP to extended Newton direction.
Implements NOX::Abstract::Group.
getNormF()
double LOCA::MultiContinuation::ConstrainedGroup::getNormF () const virtual
Return 2-norm of extended residual.
Implements NOX::Abstract::Group.
References NOX::Abstract::Vector::norm().
getParam() [1/2]
double LOCA::MultiContinuation::ConstrainedGroup::getParam (int paramID) const virtual
Return copy of parameter indexed by (integer) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParam() [2/2]
double LOCA::MultiContinuation::ConstrainedGroup::getParam (std::string paramID) const virtual
Return copy of parameter indexed by (std::string) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
getParams()
const LOCA::ParameterVector & LOCA::MultiContinuation::ConstrainedGroup::getParams () const virtual
Return a const reference to the ParameterVector owned by the group.
Implements LOCA::MultiContinuation::AbstractGroup.
getUnborderedGroup()
Teuchos::RCP< const NOX::Abstract::Group > LOCA::MultiContinuation::ConstrainedGroup::getUnborderedGroup () const virtual
Get bottom-level unbordered group.
Implements LOCA::BorderedSystem::AbstractGroup.
getUnderlyingGroup() [1/2]
Teuchos::RCP< LOCA::MultiContinuation::AbstractGroup > LOCA::MultiContinuation::ConstrainedGroup::getUnderlyingGroup () virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getUnderlyingGroup() [2/2]
Teuchos::RCP< const LOCA::MultiContinuation::AbstractGroup > LOCA::MultiContinuation::ConstrainedGroup::getUnderlyingGroup () const virtual
Return underlying group.
Implements LOCA::Extended::MultiAbstractGroup.
getX()
const NOX::Abstract::Vector & LOCA::MultiContinuation::ConstrainedGroup::getX () const virtual
Return extended solution vector.
Implements NOX::Abstract::Group.
Referenced by computeX().
getXPtr()
Teuchos::RCP< const NOX::Abstract::Vector > LOCA::MultiContinuation::ConstrainedGroup::getXPtr () const virtual
Return RCP to extended solution vector.
Implements NOX::Abstract::Group.
isCombinedAZero()
bool LOCA::MultiContinuation::ConstrainedGroup::isCombinedAZero () const virtual
Indicates whether combined A block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isCombinedBZero()
bool LOCA::MultiContinuation::ConstrainedGroup::isCombinedBZero () const virtual
Indicates whether combined B block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isCombinedCZero()
bool LOCA::MultiContinuation::ConstrainedGroup::isCombinedCZero () const virtual
Indicates whether combined C block is zero.
Implements LOCA::BorderedSystem::AbstractGroup.
isF()
bool LOCA::MultiContinuation::ConstrainedGroup::isF () const virtual
Return true if extended residual is valid.
Implements NOX::Abstract::Group.
isGradient()
bool LOCA::MultiContinuation::ConstrainedGroup::isGradient () const virtual
Always returns false.
Reimplemented from NOX::Abstract::Group.
isJacobian()
bool LOCA::MultiContinuation::ConstrainedGroup::isJacobian () const virtual
Return true if the extended Jacobian is valid.
Reimplemented from NOX::Abstract::Group.
isNewton()
bool LOCA::MultiContinuation::ConstrainedGroup::isNewton () const virtual
Return true if the extended Newton direction is valid.
Reimplemented from NOX::Abstract::Group.
loadNestedComponents()
void LOCA::MultiContinuation::ConstrainedGroup::loadNestedComponents (const NOX::Abstract::MultiVector & v_x, const NOX::Abstract::MultiVector::DenseMatrix & v_p, NOX::Abstract::MultiVector & v) const virtual
Given the solution component v_x and combined parameter components v_p, distribute these components through the nested sub-vectors in v.
Implements LOCA::BorderedSystem::AbstractGroup.
References LOCA::Extended::MultiVector::getScalars(), and LOCA::MultiContinuation::ExtendedMultiVector::getXMultiVec().
operator=()
NOX::Abstract::Group & LOCA::MultiContinuation::ConstrainedGroup::operator= (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements NOX::Abstract::Group.
postProcessContinuationStep()
void LOCA::MultiContinuation::ConstrainedGroup::postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any postprocessing after a continuation step finishes.
The stepStatus argument indicates whether the step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
preProcessContinuationStep()
void LOCA::MultiContinuation::ConstrainedGroup::preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any preprocessing before a continuation step starts.
The stepStatus argument indicates whether the previous step was successful.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
printSolution() [1/2]
void LOCA::MultiContinuation::ConstrainedGroup::printSolution (const double conParam) const virtual
Function to print out solution and parameter after successful step.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
printSolution() [2/2]
void LOCA::MultiContinuation::ConstrainedGroup::printSolution (const NOX::Abstract::Vector & x, const double conParam) const virtual
Function to print out a vector and parameter after successful step.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::ParameterVector::getLabel(), LOCA::Extended::Vector::getScalar(), LOCA::MultiContinuation::ExtendedVector::getXVec(), and NOX::Utils::StepperDetails.
projectToDraw()
void LOCA::MultiContinuation::ConstrainedGroup::projectToDraw (const NOX::Abstract::Vector & x, double * px) const virtual
Projects solution to a few scalars for multiparameter continuation.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::Extended::Vector::getScalar(), and LOCA::MultiContinuation::ExtendedVector::getXVec().
projectToDrawDimension()
int LOCA::MultiContinuation::ConstrainedGroup::projectToDrawDimension () const virtual
Returns the dimension of the project to draw array.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
scaleVector()
void LOCA::MultiContinuation::ConstrainedGroup::scaleVector (NOX::Abstract::Vector & x) const virtual
Scales a vector using scaling vector.
Reimplemented from LOCA::MultiContinuation::AbstractGroup.
References LOCA::MultiContinuation::ExtendedVector::getXVec().
setParam() [1/2]
void LOCA::MultiContinuation::ConstrainedGroup::setParam (int paramID, double val) virtual
Set parameter indexed by (integer) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
setParam() [2/2]
void LOCA::MultiContinuation::ConstrainedGroup::setParam (std::string paramID, double val) virtual
Set parameter indexed by (std::string) paramID.
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::ParameterVector::getIndex().
setParams()
void LOCA::MultiContinuation::ConstrainedGroup::setParams (const ParameterVector & p) virtual
Set the parameter vector in the group to p (pVector = p).
Implements LOCA::MultiContinuation::AbstractGroup.
References LOCA::ParameterVector::length().
setParamsMulti()
void LOCA::MultiContinuation::ConstrainedGroup::setParamsMulti (const std::vector< int > & paramIDs, const NOX::Abstract::MultiVector::DenseMatrix & vals) virtual
Set parameters indexed by (integer) paramIDs.
Reimplemented from LOCA::Abstract::Group.
setX()
void LOCA::MultiContinuation::ConstrainedGroup::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector to y.
Implements NOX::Abstract::Group.
References LOCA::Extended::Vector::getScalars(), and LOCA::MultiContinuation::ExtendedVector::getXVec().
The documentation for this class was generated from the following files:
LOCA_MultiContinuation_ConstrainedGroup.H
LOCA_MultiContinuation_ConstrainedGroup.C