NOX: NOX::Abstract::Group Class Reference
NOX::Abstract::Group Class Reference abstract
NOX pure abstract interface to a "group"; i.e., a solution vector and the corresponding F-vector, Jacobian matrix, gradient vector, and Newton vector.
#include <NOX_Abstract_Group.H>
Public Types
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Public Member Functions
Group ()
Constructor.
virtual ~Group ()
Destructor.
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)=0
Copies the source group into this group.
virtual void setX (const NOX::Abstract::Vector &y)=0
Set the solution vector x to y.
virtual void computeX (const NOX::Abstract::Group &grp, const NOX::Abstract::Vector &d, double step)=0
Compute x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()=0
Compute and store F(x).
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute and store Jacobian.
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Compute and store gradient.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute the Newton direction, using parameters for the linear solve.
Jacobian operations.
Operations using the Jacobian matrix.
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian-Transpose to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
Block Jacobian operations.
Operations using the Jacobian matrix.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobian for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianTranspose for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianInverse for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
"Is" functions.
Checks to see if various objects have been computed. Returns true if the corresponding "compute" function has been called since the last change to the solution vector.
virtual bool isF () const =0
Return true if F is valid.
virtual bool isJacobian () const
Return true if the Jacobian is valid.
virtual bool isGradient () const
Return true if the gradient is valid.
virtual bool isNewton () const
Return true if the Newton direction is valid.
"Get" functions.
Note that these function do not check whether or not the vectors are valid. Must use the "Is" functions for that purpose.
virtual const NOX::Abstract::Vector & getX () const =0
Return solution vector.
virtual const NOX::Abstract::Vector & getScaledX () const
virtual const NOX::Abstract::Vector & getF () const =0
Return F(x)
virtual double getNormF () const =0
Return 2-norm of F(x).
virtual const NOX::Abstract::Vector & getGradient () const =0
Return gradient.
virtual const NOX::Abstract::Vector & getNewton () const =0
Return Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const =0
Return RCP to solution vector.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const =0
Return RCP to F(x)
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const =0
Return RCP to gradient.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const =0
Return RCP to Newton direction.
"Linear Solve Statistics" functions.
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const =0
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Return an internally stored group from this group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Return an internally stored group from this group.
Detailed Description
NOX pure abstract interface to a "group"; i.e., a solution vector and the corresponding F-vector, Jacobian matrix, gradient vector, and Newton vector.
This class is a member of the namespace NOX::Abstract.
The user should implement their own concrete implementation of this class or use one of the implementations provided by us. Typically the implementation is also tied to a particular NOX::Abstract::Vector implementation.
Note
The group may be implemented so that multiple groups can share underlying memory space. This is particularly important when it comes to the Jacobian, which is often to big to be replicated for every group. Thus, we have included instructions on how shared data should be treated for the operator=() and clone() functions.
Member Enumeration Documentation
ReturnType
enum NOX::Abstract::Group::ReturnType
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Note
These return types may be expanded in future releases.
Enumerator
Ok
Computation completed successfully.
NotDefined
This function is not implemented.
BadDependency
Data dependencies not satisfied.
NotConverged
Unable to satisfy convergence criteria.
Failed
Any other type of failure.
Constructor & Destructor Documentation
Group()
NOX::Abstract::Group::Group () inline
Constructor.
Note
Constructors for any derived object should always define a default x-value so that getX() is always defined.
~Group()
virtual NOX::Abstract::Group::~Group () inline virtual
Destructor.
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Epetra::Group, LOCA::LAPACK::Group, LOCA::Thyra::Group, LOCA::Abstract::Group, LOCA::Homotopy::Group, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Member Function Documentation
applyJacobian()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyJacobian (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian to the given input vector and puts the answer in the result.
Computes
where is the Jacobian, is the input vector, and is the result vector.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If the Jacobian has not been computed
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
Reimplemented in NOX::Petsc::Group, NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, and NOX::Thyra::Group.
References NotDefined.
Referenced by LOCA::DerivUtils::computeDJnDp(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDwtJnDp(), NOX::Direction::Utils::InexactNewton::computeForcingTerm(), NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer(), NOX::Thyra::WeightedMeritFunction::computeQuadraticModel(), NOX::MeritFunction::SumOfSquares::computeQuadraticModel(), NOX::Thyra::WeightedMeritFunction::computeSlope(), NOX::LineSearch::Utils::Slope::computeSlope(), NOX::Solver::TensorBased::computeTensorDirection(), NOX::Solver::TensorBased::getDirectionalDerivative(), NOX::Solver::TensorBased::getNormModelResidual(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), and NOX::Direction::Newton::resetForcingTerm().
applyJacobianInverse()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyJacobianInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
Computes
where is the Jacobian, is the input vector, and is the result vector.
The "Tolerance" parameter specifies that the solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If has not been computed
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
The parameter "Tolerance" may be added/modified in the list of parameters - this is the ideal solution tolerance for an iterative linear solve.
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, and NOX::Thyra::Group.
References NotDefined.
Referenced by NOX::Solver::TensorBased::computeTensorDirection(), and NOX::Solver::InexactTrustRegionBased::iterateInexact().
applyJacobianInverseMultiVector()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyJacobianInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyJacobianInverse for multiple right-hand sides
The default implementation here calls applyJacobianInverse() for each right hand side serially but should be overloaded if a block solver is available.
Reimplemented in NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, and NOX::Thyra::Group.
References NOX::Abstract::MultiVector::numVectors(), and Ok.
applyJacobianMultiVector()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyJacobianMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyJacobian for multiple right-hand sides
The default implementation here calls applyJacobian() for each right hand side serially but should be overloaded if a block method is available.
Reimplemented in LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, and NOX::Thyra::Group.
References NOX::Abstract::MultiVector::numVectors(), and Ok.
applyJacobianTranspose()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyJacobianTranspose (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian-Transpose to the given input vector and puts the answer in the result.
Computes
where is the Jacobian, is the input vector, and is the result vector.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If has not been computed
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
Reimplemented in NOX::Petsc::Group, NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, and NOX::Thyra::Group.
References NotDefined.
Referenced by LOCA::DerivUtils::computeDwtJDp(), LOCA::DerivUtils::computeDwtJnDx(), NOX::Thyra::WeightedMeritFunction::computeGradient(), and NOX::MeritFunction::SumOfSquares::computeGradient().
applyJacobianTransposeMultiVector()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyJacobianTranspose for multiple right-hand sides
The default implementation here calls applyJacobianTranspose() for each right hand side serially but should be overloaded if a block method is available.
Reimplemented in LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, and NOX::Thyra::Group.
References NOX::Abstract::MultiVector::numVectors(), and Ok.
Referenced by LOCA::DerivUtils::computeDwtJnDx().
applyRightPreconditioning()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Apply right preconditiong to the given input vector.
Let be a right preconditioner for the Jacobian ; in other words, is a matrix such that
Compute
where is the input vector and is the result vector.
If useTranspose is true, then the transpose of the preconditioner is applied:
The transpose preconditioner is currently only required for Tensor methods.
The "Tolerance" parameter specifies that the solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
The parameters are from the "Linear %Solver" sublist of the "Direction" sublist that is passed to solver during construction.
Reimplemented in NOX::Epetra::Group, and NOX::Thyra::Group.
References NotDefined.
Referenced by NOX::Direction::NonlinearCG::compute().
applyRightPreconditioningMultiVector()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyRightPreconditioning for multiple right-hand sides
The default implementation here calls applyRightPreconditioning() for each right hand side serially but should be overloaded if a block method is available.
References NOX::Abstract::MultiVector::numVectors(), and Ok.
clone()
virtual Teuchos::RCP< NOX::Abstract::Group > NOX::Abstract::Group::clone (NOX::CopyType type = NOX::DeepCopy) const pure virtual
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
If type is NOX::DeepCopy, then we need to create an exact replica of "this". Otherwise, if type is NOX::ShapeCopy, we need only replicate the shape of "this" (only the memory is allocated, the values are not copied into the vectors and Jacobian). Returns NULL if clone is not supported.
Note
Any shared data should have its ownership transfered to this group from the source for a NOX::DeepCopy.
Implemented in NOX::Epetra::Group, NOX::Petsc::Group, NOX::LAPACK::Group, LOCA::Epetra::Group, LOCA::LAPACK::Group, LOCA::Thyra::Group, LOCA::Thyra::GroupWrapper, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ArcLengthGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::MultiContinuation::NaturalGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::Direction::Broyden::compute(), NOX::Thyra::WeightedMeritFunction::computeSlope(), NOX::LineSearch::Utils::Slope::computeSlopeWithOutJac(), NOX::Epetra::MatrixFree::setGroupForComputeF(), and NOX::Epetra::FiniteDifference::setGroupForComputeF().
computeF()
virtual NOX::Abstract::Group::ReturnType NOX::Abstract::Group::computeF () pure virtual
Compute and store F(x).
Note
It's generally useful to also compute and store the 2-norm of F(x) at this point for later access by the getNormF() function.
Returns
NOX::Abstract::Group::Failed - If the computation fails in any way
NOX::Abstract::Group::Ok - Otherwise
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Epetra::Group, LOCA::LAPACK::Group, LOCA::Thyra::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::Direction::NonlinearCG::compute(), NOX::LineSearch::Backtrack::compute(), NOX::LineSearch::NonlinearCG::compute(), NOX::Direction::Newton::compute(), NOX::Direction::SteepestDescent::compute(), NOX::Direction::Broyden::compute(), LOCA::DerivUtils::computeDfDp(), NOX::Solver::TensorBased::computeTensorDirection(), NOX::Solver::TensorBased::implementGlobalStrategy(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), NOX::Solver::InexactTrustRegionBased::iterateStandard(), NOX::Solver::TensorBased::performLinesearch(), NOX::Solver::PseudoTransient::step(), NOX::Multiphysics::Solver::FixedPointBased::step(), NOX::Solver::LineSearchBased::step(), NOX::Solver::TensorBased::step(), NOX::Solver::TrustRegionBased::step(), and NOX::LineSearch::Polynomial::updateGrp().
computeGradient()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::computeGradient () virtual
Compute and store gradient.
We can pose the nonlinear equation problem as an optimization problem as follows:
In that case, the gradient (of) is defined as
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, and NOX::Thyra::Group.
References NotDefined.
computeJacobian()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::computeJacobian () virtual
Compute and store Jacobian.
Recall that
The Jacobian is denoted by and defined by
Note
If this is a shared object, this group should take ownership of the Jacobian before it computes it.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Epetra::Group, LOCA::LAPACK::Group, LOCA::Thyra::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, and NOX::Thyra::Group.
References NotDefined.
Referenced by NOX::Direction::NonlinearCG::compute(), NOX::Direction::Newton::compute(), NOX::Direction::SteepestDescent::compute(), NOX::Direction::Broyden::compute(), LOCA::DerivUtils::computeDJnDp(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDwtJDp(), LOCA::DerivUtils::computeDwtJnDp(), LOCA::DerivUtils::computeDwtJnDx(), LOCA::DerivUtils::computeDwtJnDx(), NOX::Solver::TensorBased::computeTensorDirection(), and NOX::Solver::InexactTrustRegionBased::iterateInexact().
computeNewton()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::computeNewton (Teuchos::ParameterList & params) virtual
Compute the Newton direction, using parameters for the linear solve.
The Newton direction is the solution, s, of
The parameters are from the "Linear %Solver" sublist of the "Direction" sublist that is passed to solver during construction.
The "Tolerance" parameter may be added/modified in the sublist of "Linear Solver" parameters that is passed into this function. The solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, and NOX::Thyra::Group.
References NotDefined.
Referenced by NOX::Direction::Newton::compute(), and NOX::Solver::TensorBased::computeTensorDirection().
computeX()
virtual void NOX::Abstract::Group::computeX (const NOX::Abstract::Group & grp, const NOX::Abstract::Vector & d, double step) pure virtual
Compute x = grp.x + step * d.
Let denote this group's solution vector. Let denote the result of grp.getX(). Then set
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implemented in NOX::Petsc::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::PhaseTransition::ExtendedGroup, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::LineSearch::SafeguardedDirection::compute(), NOX::LineSearch::Backtrack::compute(), NOX::LineSearch::FullStep::compute(), NOX::LineSearch::NonlinearCG::compute(), NOX::LineSearch::SafeguardedStep::compute(), NOX::Solver::TensorBased::implementGlobalStrategy(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), NOX::Solver::InexactTrustRegionBased::iterateStandard(), NOX::Solver::TensorBased::performLinesearch(), NOX::Solver::TrustRegionBased::step(), and NOX::LineSearch::Polynomial::updateGrp().
getF()
virtual const NOX::Abstract::Vector & NOX::Abstract::Group::getF () const pure virtual
Return F(x)
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by LOCA::Continuation::StatusTest::ParameterResidualNorm::checkStatus(), NOX::StatusTest::FiniteValue::checkStatus(), NOX::StatusTest::RelativeNormF::checkStatus(), NOX::Direction::NonlinearCG::compute(), NOX::LineSearch::NonlinearCG::compute(), NOX::Direction::Broyden::compute(), LOCA::DerivUtils::computeDfDp(), NOX::Direction::Utils::InexactNewton::computeForcingTerm(), NOX::Thyra::WeightedMeritFunction::computeGradient(), NOX::MeritFunction::SumOfSquares::computeGradient(), NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer(), NOX::MeritFunction::SumOfSquares::computeQuadraticModel(), NOX::Thyra::WeightedMeritFunction::computeSlope(), NOX::LineSearch::Utils::Slope::computeSlope(), NOX::MeritFunction::SumOfSquares::computeSlope(), NOX::LineSearch::Utils::Slope::computeSlopeWithOutJac(), NOX::Solver::TensorBased::computeTensorDirection(), NOX::Solver::TensorBased::getDirectionalDerivative(), NOX::Solver::TensorBased::getNormModelResidual(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), NOX::Direction::Newton::resetForcingTerm(), and NOX::Epetra::BroydenOperator::runPostIterate().
getFPtr()
virtual Teuchos::RCP< const NOX::Abstract::Vector > NOX::Abstract::Group::getFPtr () const pure virtual
Return RCP to F(x)
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::Thyra::WeightedMeritFunction::computef().
getGradient()
virtual const NOX::Abstract::Vector & NOX::Abstract::Group::getGradient () const pure virtual
Return gradient.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::LineSearch::Utils::Slope::computeSlope().
getGradientPtr()
virtual Teuchos::RCP< const NOX::Abstract::Vector > NOX::Abstract::Group::getGradientPtr () const pure virtual
Return RCP to gradient.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
getNestedGroup() [1/2]
Teuchos::RCP< NOX::Abstract::Group > NOX::Abstract::Group::getNestedGroup () virtual
Return an internally stored group from this group.
This is typically used to access sub-block Groups from a bordered/blocked system Group. The returned sub-block group is chosen by outer Group.
Reimplemented in LOCA::Extended::MultiAbstractGroup.
getNestedGroup() [2/2]
Teuchos::RCP< const NOX::Abstract::Group > NOX::Abstract::Group::getNestedGroup () const virtual
Return an internally stored group from this group.
This is typically used to access sub-block Groups from a bordered/blocked system Group. The returned sub-block group is chosen by outer Group.
Reimplemented in LOCA::Extended::MultiAbstractGroup.
getNewton()
virtual const NOX::Abstract::Vector & NOX::Abstract::Group::getNewton () const pure virtual
Return Newton direction.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::Direction::Newton::compute(), and NOX::Solver::TensorBased::computeTensorDirection().
getNewtonPtr()
virtual Teuchos::RCP< const NOX::Abstract::Vector > NOX::Abstract::Group::getNewtonPtr () const pure virtual
Return RCP to Newton direction.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
getNormF()
virtual double NOX::Abstract::Group::getNormF () const pure virtual
Return 2-norm of F(x).
In other words,
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::StatusTest::Divergence::checkStatus(), NOX::StatusTest::FiniteValue::checkStatus(), NOX::StatusTest::Stagnation::checkStatus(), NOX::Direction::SteepestDescent::compute(), NOX::Multiphysics::Group::computeF(), NOX::MeritFunction::SumOfSquares::computef(), NOX::Direction::Utils::InexactNewton::computeForcingTerm(), NOX::Solver::TensorBased::computeTensorDirection(), NOX::LineSearch::Polynomial::computeValue(), NOX::Solver::TensorBased::implementGlobalStrategy(), NOX::Solver::TensorBased::performLinesearch(), NOX::Solver::TensorBased::printDirectionInfo(), NOX::Direction::Newton::resetForcingTerm(), and NOX::Solver::TrustRegionBased::step().
getNormLastLinearSolveResidual()
NOX::Abstract::Group::ReturnType NOX::Abstract::Group::getNormLastLinearSolveResidual (double & residual) const virtual
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If no linear solve has been calculated
NOX::Abstract::Group::Failed - Any other type of failure
NOX::Abstract::Group::Ok - Otherwise
Reimplemented in NOX::Epetra::Group.
References NotDefined.
getScaledX()
virtual const NOX::Abstract::Vector & NOX::Abstract::Group::getScaledX () const inline virtual
If right scaling vector exist, return a right scaled vector.
Note
Default to getX
Reimplemented in NOX::Thyra::Group.
References getX().
Referenced by NOX::StatusTest::NormWRMS::checkStatus().
getX()
virtual const NOX::Abstract::Vector & NOX::Abstract::Group::getX () const pure virtual
Return solution vector.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::PitchforkBord::StatusTest::ParameterUpdateNorm::checkStatus(), LOCA::Bifurcation::PitchforkBord::StatusTest::SlackUpdateNorm::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS::checkStatus(), LOCA::Bifurcation::TPBord::StatusTest::ParameterUpdateNorm::checkStatus(), LOCA::Continuation::StatusTest::ParameterUpdateNorm::checkStatus(), NOX::StatusTest::FiniteValue::checkStatus(), NOX::StatusTest::NormUpdate::checkStatus(), NOX::Direction::NonlinearCG::compute(), NOX::LineSearch::SafeguardedDirection::compute(), NOX::LineSearch::SafeguardedStep::compute(), LOCA::DerivUtils::computeDCeDxa(), LOCA::Epetra::ModelEvaluatorInterface::computeDfDp(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDwtCeDx(), LOCA::DerivUtils::computeDwtJnDx(), LOCA::DerivUtils::computeDwtJnDx(), LOCA::Eigensolver::DGGEVStrategy::computeEigenvalues(), LOCA::Eigensolver::AnasaziStrategy::computeEigenvalues(), NOX::Direction::Utils::InexactNewton::computeForcingTerm(), NOX::Thyra::WeightedMeritFunction::computeSlope(), NOX::LineSearch::Utils::Slope::computeSlopeWithOutJac(), NOX::Solver::TensorBased::computeTensorDirection(), LOCA::Hopf::MooreSpence::ExtendedGroup::ExtendedGroup(), LOCA::Pitchfork::MooreSpence::ExtendedGroup::ExtendedGroup(), LOCA::TurningPoint::MooreSpence::ExtendedGroup::ExtendedGroup(), getScaledX(), NOX::Direction::Newton::resetForcingTerm(), and NOX::Epetra::BroydenOperator::runPostIterate().
getXPtr()
virtual Teuchos::RCP< const NOX::Abstract::Vector > NOX::Abstract::Group::getXPtr () const pure virtual
Return RCP to solution vector.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
isF()
virtual bool NOX::Abstract::Group::isF () const pure virtual
Return true if F is valid.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by NOX::StatusTest::NormUpdate::checkStatus(), NOX::Thyra::WeightedMeritFunction::computef(), NOX::MeritFunction::SumOfSquares::computef(), NOX::Thyra::WeightedMeritFunction::computeGradient(), NOX::MeritFunction::SumOfSquares::computeGradient(), NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer(), NOX::LineSearch::Utils::Slope::computeSlope(), and NOX::LineSearch::Utils::Slope::computeSlopeWithOutJac().
isGradient()
bool NOX::Abstract::Group::isGradient () const virtual
Return true if the gradient is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, and NOX::Thyra::Group.
Referenced by NOX::LineSearch::Utils::Slope::computeSlope(), and NOX::MeritFunction::SumOfSquares::computeSlope().
isJacobian()
bool NOX::Abstract::Group::isJacobian () const virtual
Return true if the Jacobian is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, and NOX::Thyra::Group.
Referenced by NOX::Direction::NonlinearCG::compute(), LOCA::DerivUtils::computeDJnDxa(), NOX::Direction::Utils::InexactNewton::computeForcingTerm(), NOX::Thyra::WeightedMeritFunction::computeGradient(), NOX::MeritFunction::SumOfSquares::computeGradient(), NOX::MeritFunction::SumOfSquares::computeQuadraticMinimizer(), NOX::MeritFunction::SumOfSquares::computeSlope(), NOX::Solver::InexactTrustRegionBased::iterateInexact(), and NOX::Direction::Newton::resetForcingTerm().
isNewton()
bool NOX::Abstract::Group::isNewton () const virtual
Return true if the Newton direction is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, and NOX::Thyra::Group.
logLastLinearSolveStats()
void NOX::Abstract::Group::logLastLinearSolveStats (NOX::SolverStats & stats) const virtual
Adds statistics from last linear solve to the SovlerStats object.
Reimplemented in NOX::Epetra::Group, and NOX::Thyra::Group.
Referenced by NOX::Direction::Newton::compute(), and NOX::Solver::InexactTrustRegionBased::iterateInexact().
operator=()
virtual NOX::Abstract::Group & NOX::Abstract::Group::operator= (const NOX::Abstract::Group & source) pure virtual
Copies the source group into this group.
Note
Any shared data owned by the source should have its ownership transfered to this group. This may result in a secret modification to the source object.
Implemented in NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Epetra::Group, LOCA::LAPACK::Group, LOCA::Thyra::Group, LOCA::Thyra::GroupWrapper, LOCA::Abstract::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ArcLengthGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::MultiContinuation::FiniteDifferenceGroup, LOCA::MultiContinuation::NaturalGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Petsc::Group, NOX::Thyra::Group, and NOX::Multiphysics::Group.
setX()
virtual void NOX::Abstract::Group::setX (const NOX::Abstract::Vector & y) pure virtual
Set the solution vector x to y.
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implemented in NOX::Petsc::Group, NOX::Epetra::Group, NOX::LAPACK::Group, LOCA::Homotopy::DeflatedGroup, LOCA::Homotopy::Group, LOCA::Hopf::MinimallyAugmented::ExtendedGroup, LOCA::Hopf::MooreSpence::ExtendedGroup, LOCA::MultiContinuation::ConstrainedGroup, LOCA::MultiContinuation::ExtendedGroup, LOCA::PhaseTransition::ExtendedGroup, LOCA::Pitchfork::MinimallyAugmented::ExtendedGroup, LOCA::Pitchfork::MooreSpence::ExtendedGroup, LOCA::TurningPoint::MinimallyAugmented::ExtendedGroup, LOCA::TurningPoint::MooreSpence::ExtendedGroup, NOX::Thyra::Group, and NOX::Multiphysics::Group.
Referenced by LOCA::DerivUtils::computeDCeDxa(), LOCA::DerivUtils::computeDJnDxa(), LOCA::DerivUtils::computeDwtCeDx(), LOCA::DerivUtils::computeDwtJnDx(), LOCA::DerivUtils::computeDwtJnDx(), and LOCA::DerivUtils::perturbXVec().
The documentation for this class was generated from the following files:
NOX_Abstract_Group.H
NOX_Abstract_Group.C