NOX: LOCA::Epetra::TransposeLinearSystem::Factory Class Reference
LOCA::Epetra::TransposeLinearSystem::Factory Class Reference
Factory for creating transpose linear system strategy objects.
#include <LOCA_Epetra_TransposeLinearSystem_Factory.H>
Public Member Functions
Factory (const Teuchos::RCP< LOCA::GlobalData > &global_data)
Constructor.
virtual ~Factory ()
Destructor.
Teuchos::RCP< LOCA::Epetra::TransposeLinearSystem::AbstractStrategy > create (const Teuchos::RCP< Teuchos::ParameterList > &solverParams, const Teuchos::RCP< NOX::Epetra::LinearSystem > &linsys)
Create transpose solver strategy.
const std::string & strategyName (Teuchos::ParameterList &solverParams) const
Return strategy name given by solverParams.
Protected Attributes
Teuchos::RCP< LOCA::GlobalData > globalData
Global data object.
Detailed Description
Factory for creating transpose linear system strategy objects.
The parameters passed to the create() through the solverParams argument method should specify the "Transpose Solver Method" as described below, as well as any additional parameters for the particular strategy.
"Transpose Solver Method" - Name of the method. Valid choices are
"Tranpose Preconditioner" (NOX::Epetra::TransposeLinearSystem::TransposePreconditioner) [Default]
"Explicit Transpose" (NOX::Epetra::TransposeLinearSystem::ExplicitTranspose)
"Left Preconditioning" (NOX::Epetra::TransposeLinearSystem::LeftPreconditioning)
Member Function Documentation
create()
Teuchos::RCP< LOCA::Epetra::TransposeLinearSystem::AbstractStrategy > LOCA::Epetra::TransposeLinearSystem::Factory::create (const Teuchos::RCP< Teuchos::ParameterList > & solverParams, const Teuchos::RCP< NOX::Epetra::LinearSystem > & linsys)
Create transpose solver strategy.
Parameters
solverParams [in] Solver parameters as described above
linsys [in] Linear system solver
Referenced by LOCA::Epetra::Group::applyComplexTransposeInverseMultiVector(), LOCA::Epetra::Group::applyJacobianTransposeInverse(), LOCA::Epetra::Group::applyJacobianTransposeInverseMultiVector(), and LOCA::BorderedSolver::EpetraHouseholder::solveTranspose().
The documentation for this class was generated from the following files:
LOCA_Epetra_TransposeLinearSystem_Factory.H
LOCA_Epetra_TransposeLinearSystem_Factory.C