NOX: NOX::Thyra::Group Class Reference
NOX::Thyra::Group Class Reference
A concrete implementation of the NOX::Abstract::Group using Thyra.
#include <NOX_Thyra_Group.H>
Public Member Functions
Group (const NOX::Thyra::Vector &initialGuess, const Teuchos::RCP< const ::Thyra::ModelEvaluator< double > > &model, const Teuchos::RCP< const ::Thyra::VectorBase< double > > &weightVector=Teuchos::null, const Teuchos::RCP< const ::Thyra::VectorBase< double > > &rightWeightVector=Teuchos::null, const Teuchos::RCP<::Thyra::VectorBase< double > > &inv_rightWeightVector=Teuchos::null, const bool rightScalingFirst=false)
The default constructor that uses the linear solver from the ModelEvaluator.
Group (const NOX::Thyra::Vector &initialGuess, const Teuchos::RCP< const ::Thyra::ModelEvaluator< double > > &model, const Teuchos::RCP< ::Thyra::LinearOpBase< double > > &linearOp, const Teuchos::RCP< const ::Thyra::LinearOpWithSolveFactoryBase< double > > &lowsFactory, const Teuchos::RCP< ::Thyra::PreconditionerBase< double > > &precOp, const Teuchos::RCP< ::Thyra::PreconditionerFactoryBase< double > > &precFactory, const Teuchos::RCP< const ::Thyra::VectorBase< double > > &weightVector=Teuchos::null, const Teuchos::RCP< const ::Thyra::VectorBase< double > > &rightWeightVector=Teuchos::null, const Teuchos::RCP<::Thyra::VectorBase< double > > &inv_rightWeightVector=Teuchos::null, const bool rightScalingFirst=false, const bool updatePreconditioner=true, const bool jacobianIsEvaluated=false)
Power user constructor that takes explicit linear solver objects to handle different combinations.
Group (const NOX::Thyra::Group &source, NOX::CopyType type=DeepCopy)
Copy constructor.
~Group ()
Destructor.
NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Copies the source group into this group.
NOX::Abstract::Group & operator= (const NOX::Thyra::Group &source)
Teuchos::RCP< const ::Thyra::VectorBase< double > > get_current_x () const
Teuchos::RCP< ::Thyra::LinearOpBase< double > > getNonconstJacobianOperator ()
Teuchos::RCP< const ::Thyra::LinearOpBase< double > > getJacobianOperator () const
Teuchos::RCP< const ::Thyra::LinearOpBase< double > > getScaledJacobianOperator () const
void unscaleJacobianOperator () const
Teuchos::RCP< ::Thyra::LinearOpWithSolveBase< double > > getNonconstJacobian ()
Teuchos::RCP< const ::Thyra::LinearOpWithSolveBase< double > > getJacobian () const
Teuchos::RCP< ::Thyra::PreconditionerBase< double > > getNonconstPreconditioner ()
Teuchos::RCP< const ::Thyra::PreconditionerBase< double > > getPreconditioner () const
void setJacobianOperator (const Teuchos::RCP<::Thyra::LinearOpBase< double > > &op)
Dangerous power user function for LOCA Householder bordered algorithm.
void setPreconditionerMatrix (const Teuchos::RCP< const ::Thyra::DefaultLinearOpSource< double > > &op)
Dangerous power user function for LOCA Householder bordered algorithm. This is the Matrix M that is used to initialize a stratimikos preconditioner. NOTE: this sets the losb_ object used to update prec_!
"Compute" functions.
void setX (const NOX::Abstract::Vector &y)
Set the solution vector x to y.
void setX (const NOX::Thyra::Vector &y)
See above.
void computeX (const NOX::Abstract::Group &grp, const NOX::Abstract::Vector &d, double step)
Compute x = grp.x + step * d.
void computeX (const NOX::Thyra::Group &grp, const NOX::Thyra::Vector &d, double step)
See above.
NOX::Abstract::Group::ReturnType computeF ()
Compute and store F(x).
NOX::Abstract::Group::ReturnType computeJacobian ()
Compute and store Jacobian.
NOX::Abstract::Group::ReturnType computeGradient ()
Compute and store gradient.
NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute the Newton direction, using parameters for the linear solve.
Jacobian operations.
Operations using the Jacobian matrix. These may not be defined in matrix-free scenarios.
NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian to the given input vector and puts the answer in the result.
NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Thyra::Vector &input, NOX::Thyra::Vector &result) const
NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobian for multiple right-hand sides
NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian-Transpose to the given input vector and puts the answer in the result.
NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Thyra::Vector &input, NOX::Thyra::Vector &result) const
NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianTranspose for multiple right-hand sides
NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Thyra::Vector &input, NOX::Thyra::Vector &result) const
NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianInverse for multiple right-hand sides
NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
"Is" functions
Checks to see if various objects have been computed. Returns true if the corresponding "compute" function has been called since the last update to the solution vector (via instantiation or computeX).
bool isF () const
Return true if F is valid.
bool isJacobian () const
Return true if the Jacobian is valid.
bool isGradient () const
Return true if the gradient is valid.
bool isNewton () const
Return true if the Newton direction is valid.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Return an internally stored group from this group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Return an internally stored group from this group.
Protected Attributes
IsValid flags
True if the current solution is up-to-date with respect to the currect solution vector.
bool is_valid_f_
bool is_valid_jacobian_
bool is_valid_newton_dir_
bool is_valid_gradient_dir_
bool is_valid_lows_
Teuchos::RCP< NOX::Thyra::Vector > x_vec_
Solution vector.
Teuchos::RCP< NOX::Thyra::Vector > f_vec_
Residual vector.
Teuchos::RCP< NOX::Thyra::Vector > newton_vec_
Newton direction vector.
Teuchos::RCP< NOX::Thyra::Vector > gradient_vec_
Gradient direction vector.
Teuchos::RCP< NOX::SharedObject< ::Thyra::LinearOpWithSolveBase< double >, NOX::Thyra::Group > > shared_jacobian_
Shared Jacobian operator with solve.
Teuchos::RCP< ::Thyra::LinearOpBase< double > > lop_
Jacobian operator.
Teuchos::RCP< const ::Thyra::LinearOpWithSolveFactoryBase< double > > lows_factory_
Thyra LOWS factory for building Jacobians.
Teuchos::RCP< const ::Thyra::DefaultLinearOpSource< double > > losb_
Source base needed to create preconditioner.
Teuchos::RCP< ::Thyra::PreconditionerBase< double > > prec_
Preconditioner for Jacobian.
Teuchos::RCP< ::Thyra::PreconditionerFactoryBase< double > > prec_factory_
Preconditioner factory.
Teuchos::RCP< const ::Thyra::VectorBase< double > > weight_vec_
Optional wieghting vector for function scaling. NOX assumes that this vector can be updated in between nonlinear iterations.
Teuchos::RCP< const ::Thyra::VectorBase< double > > right_weight_vec_
Optional wieghting vector for solution (right) scaling.
Teuchos::RCP< ::Thyra::VectorBase< double > > inv_weight_vec_
Inverse of weight vector used to unscale function (left) scaling. NOX assumes that this vector can be updated in between nonlinear iterations.
Teuchos::RCP< ::Thyra::VectorBase< double > > inv_right_weight_vec_
Inverse of weight vector used to unscale solution (right) scaling.
Teuchos::RCP< NOX::Thyra::Vector > scaled_x_vec_
Scaled solution vector scaled by the.
bool rightScalingFirst_
Do right scaling before left scaling?
bool updatePreconditioner_
If set to true, the preconditioner matrix values will be automatically updated via precFactory or ModelEvalautor. If set to false, the user must manually handle updating the preconditioner.
NOX::Abstract::Group::ReturnType last_linear_solve_status_
The status of the last linear solve performed.
int last_linear_solve_num_iters_
Number of iterations for last linear solve performed.
double last_linear_solve_achieved_tol_
The tolerance achieved by the last linear solver.
bool use_pseudo_transient_terms_
Teuchos::RCP< const ::Thyra::VectorBase< double > > x_dot_
double alpha_
double beta_
double t_
bool use_base_point_
::Thyra::ModelEvaluatorBase::InArgs< double > base_point_
"Get" functions
Note that these function do not check whether or not the vectors are valid. Must use the "Is" functions for that purpose.
Teuchos::RCP< const ::Thyra::ModelEvaluator< double > > model_
Problem interface.
const NOX::Abstract::Vector & getX () const
Return solution vector.
const NOX::Abstract::Vector & getScaledX () const
const NOX::Abstract::Vector & getF () const
Return F(x)
double getNormF () const
Return 2-norm of F(x).
const NOX::Abstract::Vector & getGradient () const
Return gradient.
const NOX::Abstract::Vector & getNewton () const
Return Newton direction.
Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const
Return RCP to solution vector.
Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const
Return RCP to F(x)
Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const
Return RCP to gradient.
Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const
Return RCP to Newton direction.
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
void print () const
Print out the group.
Teuchos::RCP< const ::Thyra::ModelEvaluator< double > > getModel () const
void enablePseudoTransientTerms (const Teuchos::RCP< const ::Thyra::VectorBase< double > > &x_dot, const double alpha, const double beta, const double t)
Set the transient terms on the Group and use them in the underlying evalModelImpl() calls.
void disablePseudoTransientTerms ()
Disable the pseudo traansient terms in the underlying evalModel() calls. Sets x_dot, alpha, beta and t back to steady state values.
bool usingPseudoTransientTerms () const
Check for whether the pseudo transient support is enabled for residual and Jacobian evaluations.
void setBasePoint (const ::Thyra::ModelEvaluatorBase::InArgs< double > &base_point_params)
void unsetBasePoint ()
Unset the base point parameters so that they are not used internally.
bool usingBasePoint () const
Returns true if a base point has been set.
Teuchos::RCP< const ::Thyra::LinearOpWithSolveFactoryBase< double > > getLinearOpWithSolveFactory () const
Returns the thyra linear solver factory.
Teuchos::RCP<::Thyra::PreconditionerFactoryBase< double > > getPreconditionerFactory () const
Returns the thyra preconditioner factory.
void takeControlOfPreconditionerUpdates (const Teuchos::RCP< ::Thyra::PreconditionerBase< double > > &prec)
User will take control of updating an already registered preconditioner. Typically used with NOX::ObserverReusePreconditioner observer.
void resetIsValidFlags ()
resets the isValid flags to false
NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &p, const ::Thyra::MultiVectorBase< double > &input, ::Thyra::MultiVectorBase< double > &result) const
Apply Jacobian inverse using Thyra objects.
::Thyra::ESolveMeasureNormType getThyraNormType (const std::string &name) const
void updateLOWS () const
Finalizes LOWS to be a valid solver for the Jacobian.
void scaleResidualAndJacobian () const
void unscaleResidualAndJacobian () const
void computeScaledSolution ()
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
A concrete implementation of the NOX::Abstract::Group using Thyra.
NOTE: This Group supports row sum scaling of the function (residual and Jacobian). This is enabled by setting a weight vector on the initial guess vector in the Group constructor. The residual and Jacobian must be scaled before and then unscaled after calls to construct the preconditioner and solve the linear system. This follows the nox epetra group. This design should be changed in a future nox refactor, but requires significant changes to the Group object.
Constructor & Destructor Documentation
Group() [1/2]
NOX::Thyra::Group::Group (const NOX::Thyra::Vector & initialGuess, const Teuchos::RCP< const ::Thyra::ModelEvaluator< double > > & model, const Teuchos::RCP< const ::Thyra::VectorBase< double > > & weightVector = Teuchos::null, const Teuchos::RCP< const ::Thyra::VectorBase< double > > & rightWeightVector = Teuchos::null, const Teuchos::RCP<::Thyra::VectorBase< double > > & inv_rightWeightVector = Teuchos::null, const bool rightScalingFirst = false)
The default constructor that uses the linear solver from the ModelEvaluator.
Most users should use this constructor. It is meant to be used in conjunction with a stratimikos linear solver that is built as part of the input model evaluator. For finer grained control over the use of the preconditioner and for Jacobian-Free Newton-Krylov cases, the power user constructor should be used.
Parameters
[in] initialGuess Initial guess for the solution vector
[in] model ModelEvaluator
[in] weightVector Optional diagonal weighting vector for the model.
[in] rightWeightVector Optional solution vector weighting
[in] inv_rightWeightVector Optional inverse solution vector weighting
[in] rightScalingFirst Optional bool to select if right scaling should be applied before left scaling
References NOX::DeepCopy, f_vec_, gradient_vec_, inv_right_weight_vec_, lop_, losb_, lows_factory_, newton_vec_, prec_, prec_factory_, resetIsValidFlags(), right_weight_vec_, rightScalingFirst_, scaled_x_vec_, NOX::ShapeCopy, shared_jacobian_, weight_vec_, and x_vec_.
Group() [2/2]
NOX::Thyra::Group::Group (const NOX::Thyra::Vector & initialGuess, const Teuchos::RCP< const ::Thyra::ModelEvaluator< double > > & model, const Teuchos::RCP< ::Thyra::LinearOpBase< double > > & linearOp, const Teuchos::RCP< const ::Thyra::LinearOpWithSolveFactoryBase< double > > & lowsFactory, const Teuchos::RCP< ::Thyra::PreconditionerBase< double > > & precOp, const Teuchos::RCP< ::Thyra::PreconditionerFactoryBase< double > > & precFactory, const Teuchos::RCP< const ::Thyra::VectorBase< double > > & weightVector = Teuchos::null, const Teuchos::RCP< const ::Thyra::VectorBase< double > > & rightWeightVector = Teuchos::null, const Teuchos::RCP<::Thyra::VectorBase< double > > & inv_rightWeightVector = Teuchos::null, const bool rightScalingFirst = false, const bool updatePreconditioner = true, const bool jacobianIsEvaluated = false)
Power user constructor that takes explicit linear solver objects to handle different combinations.
This class allows the user to set user-defined linear operators and preconditioners (and corresponding factories). The user can set the linear_op to be a Jacobian-Free Newton Krylov operator (use the class NOX::Thyra::MatrixFreeJacobianOperator).
Parameters
[in] initialGuess (Required) Initial guess for the solution vector
[in] model (Required) ModelEvaluator
[in] linearOp (Optional) Forward operator for the Jacobian. Must be non-null for Newton-based solvers.
[in] lowsFactory (Optional) Factory for building and updating linear solver.
[in] precOp (Optional) Preconditioner operator. If set to Teuchos::null and a non-null prec_factory exists, the prec_op will be constructed using the preconditioner factory.
[in] precFactory (Optional) Factory for updating the precondiitoner. If set to Teuchos::null and there is a non-null prec_op, then the preconditioner will be updated using the model evaluator as long as the ModelEvaluator::outArgs supports W_prec.
[in] weightVector (Optional) diagonal weighting vector for the model.
[in] rightWeightVector Optional solution vector weighting
[in] inv_rightWeightVector Optional inverse solution vector weighting
[in] rightScalingFirst Optional bool to select if right scaling should be applied before left scaling
[in] updatePreconditioner Optional bool to select if the Group should auotmatically update the preconditioner matrix values between Newton iterations
[in] jacobianIsEvaluated Optional bool, if true this means that the input Jacobian operator (linearOp) has been evaluated externally and is consistent with the initialGuess. In this case, the isJacobian() flag is initialized to true.
References NOX::DeepCopy, f_vec_, gradient_vec_, inv_right_weight_vec_, lop_, losb_, lows_factory_, newton_vec_, prec_, prec_factory_, resetIsValidFlags(), right_weight_vec_, rightScalingFirst_, scaled_x_vec_, NOX::ShapeCopy, shared_jacobian_, weight_vec_, and x_vec_.
~Group()
NOX::Thyra::Group::~Group () virtual
Destructor.
Reimplemented from NOX::Abstract::Group.
Member Function Documentation
applyJacobian()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::applyJacobian (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian to the given input vector and puts the answer in the result.
Computes
where is the Jacobian, is the input vector, and is the result vector.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If the Jacobian has not been computed
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
applyJacobianInverse()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::applyJacobianInverse (Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
Computes
where is the Jacobian, is the input vector, and is the result vector.
The "Tolerance" parameter specifies that the solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If has not been computed
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
The parameter "Tolerance" may be added/modified in the list of parameters - this is the ideal solution tolerance for an iterative linear solve.
Reimplemented from NOX::Abstract::Group.
applyJacobianInverseMultiVector()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::applyJacobianInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyJacobianInverse for multiple right-hand sides
The default implementation here calls applyJacobianInverse() for each right hand side serially but should be overloaded if a block solver is available.
Reimplemented from NOX::Abstract::Group.
References NOX::Thyra::MultiVector::getThyraMultiVector().
applyJacobianMultiVector()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::applyJacobianMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyJacobian for multiple right-hand sides
The default implementation here calls applyJacobian() for each right hand side serially but should be overloaded if a block method is available.
Reimplemented from NOX::Abstract::Group.
References NOX::Thyra::MultiVector::getThyraMultiVector(), and NOX::Abstract::Group::Ok.
applyJacobianTranspose()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::applyJacobianTranspose (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Applies Jacobian-Transpose to the given input vector and puts the answer in the result.
Computes
where is the Jacobian, is the input vector, and is the result vector.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If has not been computed
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
applyJacobianTransposeMultiVector()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
applyJacobianTranspose for multiple right-hand sides
The default implementation here calls applyJacobianTranspose() for each right hand side serially but should be overloaded if a block method is available.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Failed, NOX::Thyra::MultiVector::getThyraMultiVector(), and NOX::Abstract::Group::Ok.
applyRightPreconditioning()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList & params, const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Apply right preconditiong to the given input vector.
Let be a right preconditioner for the Jacobian ; in other words, is a matrix such that
Compute
where is the input vector and is the result vector.
If useTranspose is true, then the transpose of the preconditioner is applied:
The transpose preconditioner is currently only required for Tensor methods.
The "Tolerance" parameter specifies that the solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails
NOX::Abstract::Group::Ok - Otherwise
The parameters are from the "Linear %Solver" sublist of the "Direction" sublist that is passed to solver during construction.
Reimplemented from NOX::Abstract::Group.
References NOX::Thyra::Vector::getThyraRCPVector(), and NOX::Abstract::Group::Ok.
clone()
Teuchos::RCP< NOX::Abstract::Group > NOX::Thyra::Group::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
If type is NOX::DeepCopy, then we need to create an exact replica of "this". Otherwise, if type is NOX::ShapeCopy, we need only replicate the shape of "this" (only the memory is allocated, the values are not copied into the vectors and Jacobian). Returns NULL if clone is not supported.
Note
Any shared data should have its ownership transfered to this group from the source for a NOX::DeepCopy.
Implements NOX::Abstract::Group.
Reimplemented in LOCA::Thyra::Group, and LOCA::Thyra::GroupWrapper.
computeF()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::computeF () virtual
Compute and store F(x).
Note
It's generally useful to also compute and store the 2-norm of F(x) at this point for later access by the getNormF() function.
Returns
NOX::Abstract::Group::Failed - If the computation fails in any way
NOX::Abstract::Group::Ok - Otherwise
Implements NOX::Abstract::Group.
References NOX::Abstract::Group::Failed, and NOX::Abstract::Group::Ok.
computeGradient()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::computeGradient () virtual
Compute and store gradient.
We can pose the nonlinear equation problem as an optimization problem as follows:
In that case, the gradient (of) is defined as
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Failed.
computeJacobian()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::computeJacobian () virtual
Compute and store Jacobian.
Recall that
The Jacobian is denoted by and defined by
Note
If this is a shared object, this group should take ownership of the Jacobian before it computes it.
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Failed, and NOX::Abstract::Group::Ok.
computeNewton()
NOX::Abstract::Group::ReturnType NOX::Thyra::Group::computeNewton (Teuchos::ParameterList & params) virtual
Compute the Newton direction, using parameters for the linear solve.
The Newton direction is the solution, s, of
The parameters are from the "Linear %Solver" sublist of the "Direction" sublist that is passed to solver during construction.
The "Tolerance" parameter may be added/modified in the sublist of "Linear Solver" parameters that is passed into this function. The solution should be such that
Returns
NOX::Abstract::Group::NotDefined - Returned by default implementation in NOX::Abstract::Group
NOX::Abstract::Group::BadDependency - If either or has not been computed
NOX::Abstract::Group::NotConverged - If the linear solve fails to satisfy the "Tolerance" specified in params
NOX::Abstract::Group::Failed - If the computation fails in any other way
NOX::Abstract::Group::Ok - Otherwise
Reimplemented from NOX::Abstract::Group.
computeX()
void NOX::Thyra::Group::computeX (const NOX::Abstract::Group & grp, const NOX::Abstract::Vector & d, double step) virtual
Compute x = grp.x + step * d.
Let denote this group's solution vector. Let denote the result of grp.getX(). Then set
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implements NOX::Abstract::Group.
enablePseudoTransientTerms()
void NOX::Thyra::Group::enablePseudoTransientTerms (const Teuchos::RCP< const ::Thyra::VectorBase< double > > & x_dot, const double alpha, const double beta, const double t)
Set the transient terms on the Group and use them in the underlying evalModelImpl() calls.
Parameters
x_dot Time derivative term. Can be set to null.
alpha Model evaluator transient timer derivative multiplier
beta Model evaluator transient Jacobian multiplier
t Current time value
getF()
const NOX::Abstract::Vector & NOX::Thyra::Group::getF () const virtual
Return F(x)
Implements NOX::Abstract::Group.
getFPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Thyra::Group::getFPtr () const virtual
Return RCP to F(x)
Implements NOX::Abstract::Group.
getGradient()
const NOX::Abstract::Vector & NOX::Thyra::Group::getGradient () const virtual
Return gradient.
Implements NOX::Abstract::Group.
getGradientPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Thyra::Group::getGradientPtr () const virtual
Return RCP to gradient.
Implements NOX::Abstract::Group.
getNewton()
const NOX::Abstract::Vector & NOX::Thyra::Group::getNewton () const virtual
Return Newton direction.
Implements NOX::Abstract::Group.
getNewtonPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Thyra::Group::getNewtonPtr () const virtual
Return RCP to Newton direction.
Implements NOX::Abstract::Group.
getNormF()
double NOX::Thyra::Group::getNormF () const virtual
Return 2-norm of F(x).
In other words,
Implements NOX::Abstract::Group.
getScaledX()
const NOX::Abstract::Vector & NOX::Thyra::Group::getScaledX () const virtual
If right scaling vector exist, return a right scaled vector.
Note
Default to getX
Reimplemented from NOX::Abstract::Group.
getX()
const NOX::Abstract::Vector & NOX::Thyra::Group::getX () const virtual
Return solution vector.
Implements NOX::Abstract::Group.
getXPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Thyra::Group::getXPtr () const virtual
Return RCP to solution vector.
Implements NOX::Abstract::Group.
isF()
bool NOX::Thyra::Group::isF () const virtual
Return true if F is valid.
Implements NOX::Abstract::Group.
isGradient()
bool NOX::Thyra::Group::isGradient () const virtual
Return true if the gradient is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
isJacobian()
bool NOX::Thyra::Group::isJacobian () const virtual
Return true if the Jacobian is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
Referenced by Group().
isNewton()
bool NOX::Thyra::Group::isNewton () const virtual
Return true if the Newton direction is valid.
Note
Default implementation in NOX::Abstract::Group returns false.
Reimplemented from NOX::Abstract::Group.
logLastLinearSolveStats()
void NOX::Thyra::Group::logLastLinearSolveStats (NOX::SolverStats & stats) const virtual
Adds statistics from last linear solve to the SovlerStats object.
Reimplemented from NOX::Abstract::Group.
References NOX::Abstract::Group::Ok.
operator=()
NOX::Abstract::Group & NOX::Thyra::Group::operator= (const NOX::Abstract::Group & source) virtual
Copies the source group into this group.
Note
Any shared data owned by the source should have its ownership transfered to this group. This may result in a secret modification to the source object.
Implements NOX::Abstract::Group.
Reimplemented in LOCA::Thyra::GroupWrapper.
Referenced by LOCA::Thyra::Group::operator=().
setBasePoint()
void NOX::Thyra::Group::setBasePoint (const ::Thyra::ModelEvaluatorBase::InArgs< double > & base_point_params)
Set default parameters to be used with inArgs. This is a hack to support a bad design in PIRO. PIRO wraps nox as a model evaluator. The PIRO inArgs suppots all inargs, but nox only knows about nonlinear solver realted inputs. It knows nothing about parameters. PIRO should have a model evaluator wrapper that populates the extra inArgs as needed to override nominal values. Instead, we have to hard code storage of all in arg parameters in nox groups. This is only used in the Thyra::NOXNonlinearSolver and only when wrapped within a PIRO model evaluator that calls the setBasePoint on Thyra::NOXNonlinearSolver. This function should eventually be deprecated in favor of addign a wrapper ME to the piro nox solver class.
setX()
void NOX::Thyra::Group::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector x to y.
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implements NOX::Abstract::Group.
Member Data Documentation
weight_vec_
Teuchos::RCP<const ::Thyra::VectorBase<double> > NOX::Thyra::Group::weight_vec_ protected
Optional wieghting vector for function scaling. NOX assumes that this vector can be updated in between nonlinear iterations.
This is pulled out of the initial guess vector
Referenced by Group(), Group(), and Group().
The documentation for this class was generated from the following files:
NOX_Thyra_Group.H
NOX_Thyra_Group.C