NOX: LOCA::SingularJacobianSolve::Nic Class Reference
LOCA::SingularJacobianSolve::Nic Class Reference
This class computes the solution to using the Nic method.
#include <LOCA_SingularJacobianSolve_Nic.H>
Public Member Functions
Nic (Teuchos::ParameterList &params)
Constructor.
Nic (const Nic &source)
Copy constructor.
virtual ~Nic ()
Destructor.
virtual LOCA::SingularJacobianSolve::Generic * clone () const
Clone function.
virtual LOCA::SingularJacobianSolve::Generic & operator= (const LOCA::SingularJacobianSolve::Generic &source)
Assignment operator.
virtual Nic & operator= (const Nic &source)
Assignment operator.
virtual NOX::Abstract::Group::ReturnType reset (Teuchos::ParameterList &params)
Reset parameters.
virtual NOX::Abstract::Group::ReturnType compute (Teuchos::ParameterList &params, LOCA::Continuation::AbstractGroup &grp, const NOX::Abstract::Vector &input, const NOX::Abstract::Vector &approxNullVec, const NOX::Abstract::Vector &jacApproxNullVec, NOX::Abstract::Vector &result)
Computes the solution as described above.
virtual NOX::Abstract::Group::ReturnType computeMulti (Teuchos::ParameterList &params, LOCA::Continuation::AbstractGroup &grp, const NOX::Abstract::Vector *const *inputs, const NOX::Abstract::Vector &approxNullVec, const NOX::Abstract::Vector &jacApproxNullVec, NOX::Abstract::Vector **results, int nVecs)
Computes solution for multiple RHS.
Public Member Functions inherited from LOCA::SingularJacobianSolve::Generic
Generic ()
Constructor.
Generic (const Generic &source)
Copy constructor.
virtual ~Generic ()
Destructor.
Detailed Description
This class computes the solution to using the Nic method.
The idea here is to use deflation of the right hand side to improve the conditioning of the linear system. Typically a solution to when is nearly singular will have a large component in the direction of the null vector . The idea then is to deflate out of the right hand side . The complete algorithm used here is:
The solve uses the underlying group's applyJacobianInverse() method and therefore this is a generic technique for computing solutions to nearly singular system since it uses any supplied linear solver.
This algorithm is selected by setting the "Method" parameter of the "Singular Solve" sublist of the NOX linear solver parameter list to "Nic". The idea for this algorithm is taken from: R. A. Nicolaides, "Deflation of Conjugate Gradients With Applications to Boundary Value Problems," SIAM J. Numer. Anal., 24(2), 1987.
Member Function Documentation
clone()
LOCA::SingularJacobianSolve::Generic * LOCA::SingularJacobianSolve::Nic::clone () const virtual
Clone function.
Implements LOCA::SingularJacobianSolve::Generic.
compute()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::Nic::compute (Teuchos::ParameterList & params, LOCA::Continuation::AbstractGroup & grp, const NOX::Abstract::Vector & input, const NOX::Abstract::Vector & approxNullVec, const NOX::Abstract::Vector & jacApproxNullVec, NOX::Abstract::Vector & result) virtual
Computes the solution as described above.
Implements LOCA::SingularJacobianSolve::Generic.
References LOCA::ErrorCheck::checkReturnType(), NOX::Abstract::Vector::clone(), NOX::DeepCopy, NOX::Abstract::Vector::innerProduct(), and NOX::Abstract::Vector::update().
computeMulti()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::Nic::computeMulti (Teuchos::ParameterList & params, LOCA::Continuation::AbstractGroup & grp, const NOX::Abstract::Vector *const * inputs, const NOX::Abstract::Vector & approxNullVec, const NOX::Abstract::Vector & jacApproxNullVec, NOX::Abstract::Vector ** results, int nVecs) virtual
Computes solution for multiple RHS.
Implements LOCA::SingularJacobianSolve::Generic.
References NOX::Abstract::Vector::clone(), LOCA::ErrorCheck::combineAndCheckReturnTypes(), NOX::DeepCopy, NOX::Abstract::Vector::innerProduct(), NOX::Abstract::Group::Ok, and NOX::Abstract::Vector::update().
operator=()
LOCA::SingularJacobianSolve::Generic & LOCA::SingularJacobianSolve::Nic::operator= (const LOCA::SingularJacobianSolve::Generic & source) virtual
Assignment operator.
Implements LOCA::SingularJacobianSolve::Generic.
reset()
NOX::Abstract::Group::ReturnType LOCA::SingularJacobianSolve::Nic::reset (Teuchos::ParameterList & params) virtual
Reset parameters.
There are no additional parameters for the Nic calculation.
Implements LOCA::SingularJacobianSolve::Generic.
References NOX::Abstract::Group::Ok.
Referenced by Nic().
The documentation for this class was generated from the following files:
LOCA_SingularJacobianSolve_Nic.H
LOCA_SingularJacobianSolve_Nic.C