NOX: LOCA::BorderedSolver::ComplexOperator Class Reference
LOCA::BorderedSolver::ComplexOperator Class Reference
Bordered solver operator representing the as implemented in the LOCA::Hopf::MooreSpence::AbstractGroup.
#include <LOCA_BorderedSolver_ComplexOperator.H>
Public Member Functions
ComplexOperator (const Teuchos::RCP< const LOCA::Hopf::MooreSpence::AbstractGroup > &grp, double omega)
Constructor.
virtual ~ComplexOperator ()
Destructor.
virtual Teuchos::RCP< const NOX::Abstract::Group > getGroup () const
Get group pointer.
virtual double getFrequency () const
Get frequency.
virtual NOX::Abstract::Group::ReturnType apply (const NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector &Y) const
Apply the operator.
virtual NOX::Abstract::Group::ReturnType applyTranspose (const NOX::Abstract::MultiVector &X, NOX::Abstract::MultiVector &Y) const
Apply transpose of the operator.
virtual NOX::Abstract::Group::ReturnType applyInverse (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &B, NOX::Abstract::MultiVector &X) const
Apply inverse of the operator.
virtual NOX::Abstract::Group::ReturnType applyInverseTranspose (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &B, NOX::Abstract::MultiVector &X) const
Apply inverse transpose of the operator.
Public Member Functions inherited from LOCA::BorderedSolver::AbstractOperator
AbstractOperator ()
Constructor.
virtual ~AbstractOperator ()
Destructor.
Protected Attributes
Teuchos::RCP< const LOCA::Hopf::MooreSpence::AbstractGroup > grpPtr
Pointer to group.
double omega
Complex frequency.
Detailed Description
Bordered solver operator representing the as implemented in the LOCA::Hopf::MooreSpence::AbstractGroup.
Member Function Documentation
apply()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::ComplexOperator::apply (const NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector & Y) const virtual
Apply the operator.
Implements LOCA::BorderedSolver::AbstractOperator.
References LOCA::Hopf::ComplexMultiVector::getImagMultiVec(), and LOCA::Hopf::ComplexMultiVector::getRealMultiVec().
applyInverse()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::ComplexOperator::applyInverse (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & B, NOX::Abstract::MultiVector & X) const virtual
Apply inverse of the operator.
Implements LOCA::BorderedSolver::AbstractOperator.
References LOCA::Hopf::ComplexMultiVector::getImagMultiVec(), and LOCA::Hopf::ComplexMultiVector::getRealMultiVec().
applyInverseTranspose()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::ComplexOperator::applyInverseTranspose (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & B, NOX::Abstract::MultiVector & X) const virtual
Apply inverse transpose of the operator.
Group must be of type LOCA::Hopf::MinimallyAugmented::AbstractGroup for this method to be implemented.
Implements LOCA::BorderedSolver::AbstractOperator.
References LOCA::Hopf::ComplexMultiVector::getImagMultiVec(), LOCA::Hopf::ComplexMultiVector::getRealMultiVec(), and NOX::Abstract::Group::NotDefined.
applyTranspose()
NOX::Abstract::Group::ReturnType LOCA::BorderedSolver::ComplexOperator::applyTranspose (const NOX::Abstract::MultiVector & X, NOX::Abstract::MultiVector & Y) const virtual
Apply transpose of the operator.
Group must be of type LOCA::Hopf::MinimallyAugmented::AbstractGroup for this method to be implemented.
Implements LOCA::BorderedSolver::AbstractOperator.
References LOCA::Hopf::ComplexMultiVector::getImagMultiVec(), LOCA::Hopf::ComplexMultiVector::getRealMultiVec(), and NOX::Abstract::Group::NotDefined.
The documentation for this class was generated from the following files:
LOCA_BorderedSolver_ComplexOperator.H
LOCA_BorderedSolver_ComplexOperator.C