NOX: LOCA::MultiContinuation::CompositeConstraint Class Reference
LOCA::MultiContinuation::CompositeConstraint Class Reference
Implementation of LOCA::MultiContinuation::ConstraintInterface for composite constraints, i.e., a constraint comprised of multiple, separate constraints.
#include <LOCA_MultiContinuation_CompositeConstraint.H>
Public Member Functions
CompositeConstraint (const Teuchos::RCP< LOCA::GlobalData > &global_data, const std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > > &constraintObjects)
Constructor.
CompositeConstraint (const CompositeConstraint &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
~CompositeConstraint ()
Destructor.
Public Member Functions inherited from LOCA::MultiContinuation::ConstraintInterface
ConstraintInterface ()
Constructor.
virtual ~ConstraintInterface ()
Destructor.
Implementation of LOCA::MultiContinuation::ConstraintInterface
virtual methods
Teuchos::RCP< LOCA::GlobalData > globalData
LOCA global data object.
int numConstraintObjects
Number of constraint objects.
std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > > constraintPtrs
Array of constraint pointers.
std::vector< std::vector< int > > indices
Indices of each sub-constraint in the composite constraint.
int totalNumConstraints
Total number of constraints.
NOX::Abstract::MultiVector::DenseMatrix constraints
Constraint values.
bool isValidConstraints
Flag indicating whether constraints are valid.
bool isValidDX
Flag indicating whether dg/dx is valid.
virtual void copy (const ConstraintInterface &source)
Copy.
virtual Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > clone (NOX::CopyType type=NOX::DeepCopy) const
Cloning function.
virtual int numConstraints () const
Return number of constraints.
virtual void setX (const NOX::Abstract::Vector &y)
Set the solution vector to y.
virtual void setParam (int paramID, double val)
Sets parameter indexed by paramID.
virtual void setParams (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Sets parameters indexed by paramIDs.
virtual NOX::Abstract::Group::ReturnType computeConstraints ()
Compute continuation constraint equations.
virtual NOX::Abstract::Group::ReturnType computeDX ()
Compute derivative of constraints w.r.t. solution vector x.
virtual NOX::Abstract::Group::ReturnType computeDP (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector::DenseMatrix &dgdp, bool isValidG)
Compute derivative of constraints w.r.t. supplied parameters.
virtual bool isConstraints () const
Return true if constraint residuals are valid.
virtual bool isDX () const
Return true if derivatives of constraints w.r.t. x are valid.
virtual const NOX::Abstract::MultiVector::DenseMatrix & getConstraints () const
Return constraint residuals.
virtual NOX::Abstract::Group::ReturnType multiplyDX (double alpha, const NOX::Abstract::MultiVector &input_x, NOX::Abstract::MultiVector::DenseMatrix &result_p) const
Compute result_p = alpha * dg/dx * input_x.
virtual NOX::Abstract::Group::ReturnType addDX (Teuchos::ETransp transb, double alpha, const NOX::Abstract::MultiVector::DenseMatrix &b, double beta, NOX::Abstract::MultiVector &result_x) const
Compute result_x = alpha * dg/dx^T * op(b) + beta * result_x.
virtual bool isDXZero () const
Return true if solution component of constraint derivatives is zero.
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any postprocessing after a continuation step finishes.
CompositeConstraint ()
Default constructor. Used by derived classes.
virtual void init (const Teuchos::RCP< LOCA::GlobalData > &global_data, const std::vector< Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > > &constraintObjects)
Initialize object when using default constructor.
Detailed Description
Implementation of LOCA::MultiContinuation::ConstraintInterface for composite constraints, i.e., a constraint comprised of multiple, separate constraints.
Member Function Documentation
addDX()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraint::addDX (Teuchos::ETransp transb, double alpha, const NOX::Abstract::MultiVector::DenseMatrix & b, double beta, NOX::Abstract::MultiVector & result_x) const virtual
Compute result_x = alpha * dg/dx^T * op(b) + beta * result_x.
Note that this should be equivalent to
result_x.update(transb, alpha, dgdx, b, beta);
Implements LOCA::MultiContinuation::ConstraintInterface.
Reimplemented in LOCA::MultiContinuation::CompositeConstraintMVDX.
References NOX::Abstract::MultiVector::numVectors(), NOX::Abstract::Group::Ok, and NOX::Abstract::MultiVector::scale().
clone()
Teuchos::RCP< LOCA::MultiContinuation::ConstraintInterface > LOCA::MultiContinuation::CompositeConstraint::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Cloning function.
Implements LOCA::MultiContinuation::ConstraintInterface.
Reimplemented in LOCA::MultiContinuation::CompositeConstraintMVDX.
computeConstraints()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraint::computeConstraints () virtual
Compute continuation constraint equations.
Implements LOCA::MultiContinuation::ConstraintInterface.
References NOX::Abstract::Group::Ok.
computeDP()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraint::computeDP (const std::vector< int > & paramIDs, NOX::Abstract::MultiVector::DenseMatrix & dgdp, bool isValidG) virtual
Compute derivative of constraints w.r.t. supplied parameters.
The first column of dgdp should be filled with the constraint residuals if isValidG is false. If isValidG is true, then the dgdp contains on input.
Implements LOCA::MultiContinuation::ConstraintInterface.
References NOX::Abstract::Group::Ok.
computeDX()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraint::computeDX () virtual
Compute derivative of constraints w.r.t. solution vector x.
Implements LOCA::MultiContinuation::ConstraintInterface.
Reimplemented in LOCA::MultiContinuation::CompositeConstraintMVDX.
References NOX::Abstract::Group::Ok.
copy()
void LOCA::MultiContinuation::CompositeConstraint::copy (const ConstraintInterface & source) virtual
Copy.
Implements LOCA::MultiContinuation::ConstraintInterface.
Reimplemented in LOCA::MultiContinuation::CompositeConstraintMVDX.
References constraintPtrs, constraints, globalData, indices, isValidConstraints, isValidDX, numConstraintObjects, and totalNumConstraints.
Referenced by LOCA::MultiContinuation::CompositeConstraintMVDX::copy().
getConstraints()
const NOX::Abstract::MultiVector::DenseMatrix & LOCA::MultiContinuation::CompositeConstraint::getConstraints () const virtual
Return constraint residuals.
Implements LOCA::MultiContinuation::ConstraintInterface.
isConstraints()
bool LOCA::MultiContinuation::CompositeConstraint::isConstraints () const virtual
Return true if constraint residuals are valid.
Implements LOCA::MultiContinuation::ConstraintInterface.
isDX()
bool LOCA::MultiContinuation::CompositeConstraint::isDX () const virtual
Return true if derivatives of constraints w.r.t. x are valid.
Implements LOCA::MultiContinuation::ConstraintInterface.
isDXZero()
bool LOCA::MultiContinuation::CompositeConstraint::isDXZero () const virtual
Return true if solution component of constraint derivatives is zero.
Implements LOCA::MultiContinuation::ConstraintInterface.
Referenced by LOCA::MultiContinuation::CompositeConstraintMVDX::CompositeConstraintMVDX().
multiplyDX()
NOX::Abstract::Group::ReturnType LOCA::MultiContinuation::CompositeConstraint::multiplyDX (double alpha, const NOX::Abstract::MultiVector & input_x, NOX::Abstract::MultiVector::DenseMatrix & result_p) const virtual
Compute result_p = alpha * dg/dx * input_x.
Note that if there are n constraints and input_x has m columns, result_p should be a n by m matrix and is equivalent to
input_x.multiply(alpha, dgdx, result_p).
Implements LOCA::MultiContinuation::ConstraintInterface.
Reimplemented in LOCA::MultiContinuation::CompositeConstraintMVDX.
References NOX::Abstract::Group::Ok.
numConstraints()
int LOCA::MultiContinuation::CompositeConstraint::numConstraints () const virtual
Return number of constraints.
Implements LOCA::MultiContinuation::ConstraintInterface.
postProcessContinuationStep()
void LOCA::MultiContinuation::CompositeConstraint::postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any postprocessing after a continuation step finishes.
The stepStatus argument indicates whether the step was successful. The default implementation is empty.
Reimplemented from LOCA::MultiContinuation::ConstraintInterface.
preProcessContinuationStep()
void LOCA::MultiContinuation::CompositeConstraint::preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus) virtual
Perform any preprocessing before a continuation step starts.
The stepStatus argument indicates whether the previous step was successful. The default implementation is empty.
Reimplemented from LOCA::MultiContinuation::ConstraintInterface.
setParam()
void LOCA::MultiContinuation::CompositeConstraint::setParam (int paramID, double val) virtual
Sets parameter indexed by paramID.
Implements LOCA::MultiContinuation::ConstraintInterface.
setParams()
void LOCA::MultiContinuation::CompositeConstraint::setParams (const std::vector< int > & paramIDs, const NOX::Abstract::MultiVector::DenseMatrix & vals) virtual
Sets parameters indexed by paramIDs.
Implements LOCA::MultiContinuation::ConstraintInterface.
setX()
void LOCA::MultiContinuation::CompositeConstraint::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector to y.
Implements LOCA::MultiContinuation::ConstraintInterface.
The documentation for this class was generated from the following files:
LOCA_MultiContinuation_CompositeConstraint.H
LOCA_MultiContinuation_CompositeConstraint.C