NOX: NOX::StatusTest::Generic Class Reference
NOX::StatusTest::Generic Class Reference abstract
Generic status test to check for convergence or failure of the nonlinear solver.
#include <NOX_StatusTest_Generic.H>
Public Member Functions
Generic ()
Constructor.
virtual ~Generic ()
Destructor.
virtual NOX::StatusTest::StatusType checkStatus (const NOX::Solver::Generic &problem, NOX::StatusTest::CheckType checkType)=0
Test the stopping criterion
virtual NOX::StatusTest::StatusType getStatus () const =0
Return the result of the most recent checkStatus call.
virtual std::ostream & print (std::ostream &stream, int indent=0) const =0
Output formatted description of stopping test to output stream.
Detailed Description
Generic status test to check for convergence or failure of the nonlinear solver.
Member Function Documentation
checkStatus()
virtual NOX::StatusTest::StatusType NOX::StatusTest::Generic::checkStatus (const NOX::Solver::Generic & problem, NOX::StatusTest::CheckType checkType) pure virtual
Test the stopping criterion
The test can (and should, if possible) be skipped if checkType is NOX::StatusType::None. If the test is skipped, then the status should be set to NOX::StatusTest::Unevaluated.
Implemented in LOCA::StatusTest::Wrapper, NOX::StatusTest::Combo, NOX::StatusTest::Divergence, NOX::StatusTest::FiniteValue, NOX::StatusTest::MaxIters, NOX::StatusTest::NormF, NOX::StatusTest::NormUpdate, NOX::StatusTest::NormWRMS, NOX::StatusTest::NStep, NOX::StatusTest::RelativeNormF, and NOX::StatusTest::Stagnation.
Referenced by NOX::Solver::InexactTrustRegionBased::iterateInexact(), NOX::Solver::InexactTrustRegionBased::iterateStandard(), NOX::Solver::PseudoTransient::step(), NOX::Multiphysics::Solver::FixedPointBased::step(), NOX::Solver::LineSearchBased::step(), NOX::Solver::TensorBased::step(), and NOX::Solver::TrustRegionBased::step().
getStatus()
virtual NOX::StatusTest::StatusType NOX::StatusTest::Generic::getStatus () const pure virtual
Return the result of the most recent checkStatus call.
Implemented in LOCA::Bifurcation::PitchforkBord::StatusTest::NullVectorNormWRMS, LOCA::Bifurcation::PitchforkBord::StatusTest::ParameterUpdateNorm, LOCA::Bifurcation::PitchforkBord::StatusTest::SlackUpdateNorm, LOCA::Bifurcation::TPBord::StatusTest::NullVectorNormWRMS, LOCA::Bifurcation::TPBord::StatusTest::ParameterUpdateNorm, LOCA::Continuation::StatusTest::ParameterResidualNorm, LOCA::Continuation::StatusTest::ParameterUpdateNorm, LOCA::StatusTest::Wrapper, NOX::StatusTest::Combo, NOX::StatusTest::Divergence, NOX::StatusTest::FiniteValue, NOX::StatusTest::MaxIters, NOX::StatusTest::NormF, NOX::StatusTest::NormUpdate, NOX::StatusTest::NormWRMS, NOX::StatusTest::NStep, NOX::StatusTest::RelativeNormF, and NOX::StatusTest::Stagnation.
print()
virtual std::ostream & NOX::StatusTest::Generic::print (std::ostream & stream, int indent = 0) const pure virtual
Output formatted description of stopping test to output stream.
Implemented in LOCA::StatusTest::Wrapper, NOX::StatusTest::Combo, NOX::StatusTest::Divergence, NOX::StatusTest::FiniteValue, NOX::StatusTest::MaxIters, NOX::StatusTest::NormF, NOX::StatusTest::NormUpdate, NOX::StatusTest::NormWRMS, NOX::StatusTest::NStep, NOX::StatusTest::RelativeNormF, and NOX::StatusTest::Stagnation.
The documentation for this class was generated from the following file:
NOX_StatusTest_Generic.H