NOX: NOX::Multiphysics::Group Class Reference
NOX::Multiphysics::Group Class Reference
NOX pure abstract interface to a "group"; i.e., a solution vector and the corresponding F-vector, Jacobian matrix, gradient vector, and Newton vector.
#include <NOX_Multiphysics_Group.H>
Public Member Functions
Group (const Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > &solvers, const Teuchos::RCP< NOX::StatusTest::Generic > &t, const Teuchos::RCP< Teuchos::ParameterList > &p)
Constructor.
Group (const Group &grp, NOX::CopyType typ)
Constructor.
virtual ~Group ()
Destructor.
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Copies the source group into this group.
virtual NOX::Abstract::Group & operator= (const NOX::Multiphysics::Group &source)
virtual void setX (const NOX::Abstract::Vector &y)
Set the solution vector x to y.
virtual void computeX (const NOX::Abstract::Group &grp, const NOX::Abstract::Vector &d, double step)
Compute x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()
Compute and store F(x).
"Is" functions.
Checks to see if various objects have been computed. Returns true if the corresponding "compute" function has been called since the last change to the solution vector.
virtual bool isF () const
Return true if F is valid.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute and store Jacobian.
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Compute and store gradient.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute the Newton direction, using parameters for the linear solve.
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian-Transpose to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobian for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianTranspose for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianInverse for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual bool isJacobian () const
Return true if the Jacobian is valid.
virtual bool isGradient () const
Return true if the gradient is valid.
virtual bool isNewton () const
Return true if the Newton direction is valid.
virtual const NOX::Abstract::Vector & getScaledX () const
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Return an internally stored group from this group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Return an internally stored group from this group.
Protected Attributes
IsValid flags
True if the current solution is up-to-date with respect to the currect xVector.
bool isValidRHS
double normRHS
2-Norm of RHS
"Get" functions.
Note that these function do not check whether or not the vectors are valid. Must use the "Is" functions for that purpose.
Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > solversVecPtr
Pointer to the container of solvers for each problem to be coupled.
virtual const NOX::Abstract::Vector & getX () const
Return solution vector.
virtual const NOX::Abstract::Vector & getF () const
Return F(x)
virtual double getNormF () const
Return 2-norm of F(x).
virtual const NOX::Abstract::Vector & getGradient () const
Return gradient.
virtual const NOX::Abstract::Vector & getNewton () const
Return Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const
Return RCP to solution vector.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const
Return RCP to F(x)
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const
Return RCP to gradient.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const
Return RCP to Newton direction.
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
virtual void resetIsValid ()
resets the isValid flags to false
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Detailed Description
NOX pure abstract interface to a "group"; i.e., a solution vector and the corresponding F-vector, Jacobian matrix, gradient vector, and Newton vector.
This class is a member of the namespace NOX::Abstract.
The user should implement their own concrete implementation of this class or use one of the implementations provided by us. Typically the implementation is also tied to a particular NOX::Abstract::Vector implementation.
Note
The group may be implemented so that multiple groups can share underlying memory space. This is particularly important when it comes to the Jacobian, which is often to big to be replicated for every group. Thus, we have included instructions on how shared data should be treated for the operator=() and clone() functions.
Constructor & Destructor Documentation
Group()
NOX::Multiphysics::Group::Group (const Teuchos::RCP< std::vector< Teuchos::RCP< NOX::Solver::Generic > > > & solvers, const Teuchos::RCP< NOX::StatusTest::Generic > & t, const Teuchos::RCP< Teuchos::ParameterList > & p)
Constructor.
Note
Constructors for any derived object should always define a default x-value so that getX() is always defined.
References getX(), and resetIsValid().
~Group()
NOX::Multiphysics::Group::~Group () virtual
Destructor.
Reimplemented from NOX::Abstract::Group.
Member Function Documentation
clone()
Teuchos::RCP< NOX::Abstract::Group > NOX::Multiphysics::Group::clone (NOX::CopyType type = NOX::DeepCopy) const virtual
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
If type is NOX::DeepCopy, then we need to create an exact replica of "this". Otherwise, if type is NOX::ShapeCopy, we need only replicate the shape of "this" (only the memory is allocated, the values are not copied into the vectors and Jacobian). Returns NULL if clone is not supported.
Note
Any shared data should have its ownership transfered to this group from the source for a NOX::DeepCopy.
Implements NOX::Abstract::Group.
computeF()
NOX::Abstract::Group::ReturnType NOX::Multiphysics::Group::computeF () virtual
Compute and store F(x).
Note
It's generally useful to also compute and store the 2-norm of F(x) at this point for later access by the getNormF() function.
Returns
NOX::Abstract::Group::Failed - If the computation fails in any way
NOX::Abstract::Group::Ok - Otherwise
Implements NOX::Abstract::Group.
References NOX::Abstract::Group::getNormF(), and NOX::Abstract::Group::Ok.
computeX()
void NOX::Multiphysics::Group::computeX (const NOX::Abstract::Group & grp, const NOX::Abstract::Vector & d, double step) virtual
Compute x = grp.x + step * d.
Let denote this group's solution vector. Let denote the result of grp.getX(). Then set
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implements NOX::Abstract::Group.
getF()
const NOX::Abstract::Vector & NOX::Multiphysics::Group::getF () const virtual
Return F(x)
Implements NOX::Abstract::Group.
getFPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Multiphysics::Group::getFPtr () const virtual
Return RCP to F(x)
Implements NOX::Abstract::Group.
getGradient()
const NOX::Abstract::Vector & NOX::Multiphysics::Group::getGradient () const virtual
Return gradient.
Implements NOX::Abstract::Group.
getGradientPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Multiphysics::Group::getGradientPtr () const virtual
Return RCP to gradient.
Implements NOX::Abstract::Group.
getNewton()
const NOX::Abstract::Vector & NOX::Multiphysics::Group::getNewton () const virtual
Return Newton direction.
Implements NOX::Abstract::Group.
getNewtonPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Multiphysics::Group::getNewtonPtr () const virtual
Return RCP to Newton direction.
Implements NOX::Abstract::Group.
getNormF()
double NOX::Multiphysics::Group::getNormF () const virtual
Return 2-norm of F(x).
In other words,
Implements NOX::Abstract::Group.
getX()
const NOX::Abstract::Vector & NOX::Multiphysics::Group::getX () const virtual
Return solution vector.
Implements NOX::Abstract::Group.
Referenced by Group().
getXPtr()
Teuchos::RCP< const NOX::Abstract::Vector > NOX::Multiphysics::Group::getXPtr () const virtual
Return RCP to solution vector.
Implements NOX::Abstract::Group.
isF()
bool NOX::Multiphysics::Group::isF () const virtual
Return true if F is valid.
Implements NOX::Abstract::Group.
operator=()
NOX::Abstract::Group & NOX::Multiphysics::Group::operator= (const NOX::Abstract::Group & source) virtual
Copies the source group into this group.
Note
Any shared data owned by the source should have its ownership transfered to this group. This may result in a secret modification to the source object.
Implements NOX::Abstract::Group.
setX()
void NOX::Multiphysics::Group::setX (const NOX::Abstract::Vector & y) virtual
Set the solution vector x to y.
Note
This should invalidate the function value, Jacobian, gradient, and Newton direction.
Throw an error if the copy fails.
Returns
Reference to this object
Implements NOX::Abstract::Group.
The documentation for this class was generated from the following files:
NOX_Multiphysics_Group.H
NOX_Multiphysics_Group.C