NOX: LOCA::Abstract::Group Class Reference
LOCA::Abstract::Group Class Reference
Compatiblity class for AbstractGroup hierarchy.
#include <LOCA_Abstract_Group.H>
Public Member Functions
Group (const Teuchos::RCP< LOCA::GlobalData > &global_data)
Constructor.
Group (const Teuchos::RCP< LOCA::GlobalData > &global_data, const Teuchos::RCP< LOCA::DerivUtils > &deriv)
Constructor.
Group (const Group &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~Group ()
Destructor.
Implementation of LOCA::Homotopy::AbstractGroup virtual methods.
virtual NOX::Abstract::Group::ReturnType augmentJacobianForHomotopy (double a, double b)
Replace Jacobian by where is the identity matrix and is a scalar.
Implementation of LOCA::TimeDependent::AbstractGroup virtual methods.
virtual NOX::Abstract::Group::ReturnType computeShiftedMatrix (double alpha, double beta)
Compute the shifted matrix.
virtual NOX::Abstract::Group::ReturnType applyShiftedMatrix (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Multiply the shifted matrix by a vector.
virtual NOX::Abstract::Group::ReturnType applyShiftedMatrixMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Multiply the shifted matrix by a multi-vector.
virtual NOX::Abstract::Group::ReturnType applyShiftedMatrixInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Apply the inverse of the shifted matrix by a multi-vector, as needed by the shift-and-invert and generalized Cayley transformations.
virtual NOX::Abstract::Group::ReturnType computeSecondShiftedMatrix (double alpha, double beta)
Compute the second shifted matrix. Can avoid recomputing if two are stored.
virtual NOX::Abstract::Group::ReturnType applySecondShiftedMatrix (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Multiply the shifted matrix by a vector.
virtual NOX::Abstract::Group::ReturnType applySecondShiftedMatrixMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
Multiply the shifted matrix by a multi-vector.
Implementation of LOCA::Hopf::Moorespence::AbstractGroup virtual methods.
virtual bool isComplex () const
Is valid.
virtual NOX::Abstract::Group::ReturnType computeComplex (double frequency)
Compute .
virtual NOX::Abstract::Group::ReturnType applyComplex (const NOX::Abstract::Vector &input_real, const NOX::Abstract::Vector &input_imag, NOX::Abstract::Vector &result_real, NOX::Abstract::Vector &result_imag) const
Compute .
virtual NOX::Abstract::Group::ReturnType applyComplexMultiVector (const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
Compute .
virtual NOX::Abstract::Group::ReturnType applyComplexInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
Solve .
Implementation of LOCA::Hopf::MinimallyAugmented::AbstractGroup virtual methods.
virtual NOX::Abstract::Group::ReturnType applyComplexTranspose (const NOX::Abstract::Vector &input_real, const NOX::Abstract::Vector &input_imag, NOX::Abstract::Vector &result_real, NOX::Abstract::Vector &result_imag) const
virtual NOX::Abstract::Group::ReturnType applyComplexTransposeMultiVector (const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
virtual NOX::Abstract::Group::ReturnType applyComplexTransposeInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input_real, const NOX::Abstract::MultiVector &input_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag) const
Solve .
Implementation of LOCA::MultiContinuation::AbstractGroup virtual methods.
virtual void copy (const NOX::Abstract::Group &source)
Assignment operator.
virtual void setParamsMulti (const std::vector< int > &paramIDs, const NOX::Abstract::MultiVector::DenseMatrix &vals)
Set parameters indexed by (integer) paramIDs.
virtual void notifyCompletedStep ()
Implementation of NOX::Abstract::Group virtual methods.
virtual NOX::Abstract::Group & operator= (const NOX::Abstract::Group &source)
Copies the source group into this group.
Public Member Functions inherited from LOCA::Homotopy::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::MultiContinuation::AbstractGroup
AbstractGroup ()
Default constructor.
virtual void setParams (const LOCA::ParameterVector &p)=0
Set the parameter vector in the group to p (pVector = p).
virtual void setParam (int paramID, double val)=0
Set parameter indexed by (integer) paramID.
virtual void setParam (std::string paramID, double val)=0
Set parameter indexed by (std::string) paramID.
virtual const LOCA::ParameterVector & getParams () const =0
Return a const reference to the ParameterVector owned by the group.
virtual double getParam (int paramID) const =0
Return copy of parameter indexed by (integer) paramID.
virtual double getParam (std::string paramID) const =0
Return copy of parameter indexed by (std::string) paramID.
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus stepStatus)
Perform any postprocessing after a continuation step finishes.
virtual void projectToDraw (const NOX::Abstract::Vector &x, double *px) const
Projects solution to a few scalars for multiparameter continuation.
virtual int projectToDrawDimension () const
Returns the dimension of the project to draw array.
virtual double computeScaledDotProduct (const NOX::Abstract::Vector &a, const NOX::Abstract::Vector &b) const
Compute a scaled dot product.
virtual void printSolution (const double) const
Function to print out solution and parameter after successful step.
virtual void printSolution (const NOX::Abstract::Vector &, const double) const
Function to print out a vector and parameter after successful step.
virtual void scaleVector (NOX::Abstract::Vector &x) const
Scales a vector using scaling vector.
Public Member Functions inherited from NOX::Abstract::Group
Group ()
Constructor.
virtual void setX (const NOX::Abstract::Vector &y)=0
Set the solution vector x to y.
virtual void computeX (const NOX::Abstract::Group &grp, const NOX::Abstract::Vector &d, double step)=0
Compute x = grp.x + step * d.
virtual NOX::Abstract::Group::ReturnType computeF ()=0
Compute and store F(x).
virtual NOX::Abstract::Group::ReturnType computeJacobian ()
Compute and store Jacobian.
virtual NOX::Abstract::Group::ReturnType computeGradient ()
Compute and store gradient.
virtual NOX::Abstract::Group::ReturnType computeNewton (Teuchos::ParameterList &params)
Compute the Newton direction, using parameters for the linear solve.
virtual NOX::Abstract::Group::ReturnType applyJacobian (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianTranspose (const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies Jacobian-Transpose to the given input vector and puts the answer in the result.
virtual NOX::Abstract::Group::ReturnType applyJacobianInverse (Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Applies the inverse of the Jacobian matrix to the given input vector and puts the answer in result.
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioning (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::Vector &input, NOX::Abstract::Vector &result) const
Apply right preconditiong to the given input vector.
virtual NOX::Abstract::Group::ReturnType applyJacobianMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobian for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianTransposeMultiVector (const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianTranspose for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyJacobianInverseMultiVector (Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyJacobianInverse for multiple right-hand sides
virtual NOX::Abstract::Group::ReturnType applyRightPreconditioningMultiVector (bool useTranspose, Teuchos::ParameterList &params, const NOX::Abstract::MultiVector &input, NOX::Abstract::MultiVector &result) const
applyRightPreconditioning for multiple right-hand sides
virtual bool isF () const =0
Return true if F is valid.
virtual bool isJacobian () const
Return true if the Jacobian is valid.
virtual bool isGradient () const
Return true if the gradient is valid.
virtual bool isNewton () const
Return true if the Newton direction is valid.
virtual const NOX::Abstract::Vector & getX () const =0
Return solution vector.
virtual const NOX::Abstract::Vector & getScaledX () const
virtual const NOX::Abstract::Vector & getF () const =0
Return F(x)
virtual double getNormF () const =0
Return 2-norm of F(x).
virtual const NOX::Abstract::Vector & getGradient () const =0
Return gradient.
virtual const NOX::Abstract::Vector & getNewton () const =0
Return Newton direction.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getXPtr () const =0
Return RCP to solution vector.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getFPtr () const =0
Return RCP to F(x)
virtual Teuchos::RCP< const NOX::Abstract::Vector > getGradientPtr () const =0
Return RCP to gradient.
virtual Teuchos::RCP< const NOX::Abstract::Vector > getNewtonPtr () const =0
Return RCP to Newton direction.
virtual void logLastLinearSolveStats (NOX::SolverStats &stats) const
Adds statistics from last linear solve to the SovlerStats object.
virtual NOX::Abstract::Group::ReturnType getNormLastLinearSolveResidual (double &residual) const
Return the norm of the last linear solve residual as the result of either a call to computeNewton() or applyJacobianInverse().
virtual Teuchos::RCP< NOX::Abstract::Group > clone (NOX::CopyType type=NOX::DeepCopy) const =0
Create a new Group of the same derived type as this one by cloning this one, and return a ref count pointer to the new group.
virtual Teuchos::RCP< NOX::Abstract::Group > getNestedGroup ()
Return an internally stored group from this group.
virtual Teuchos::RCP< const NOX::Abstract::Group > getNestedGroup () const
Return an internally stored group from this group.
Public Member Functions inherited from LOCA::TurningPoint::MinimallyAugmented::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~FiniteDifferenceGroup ()
Destructor.
virtual NOX::Abstract::Group::ReturnType computeDwtJnDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &w, const NOX::Abstract::Vector &nullVector, NOX::Abstract::MultiVector::DenseMatrix &result, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDwtJDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &w, NOX::Abstract::MultiVector &result, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDwtJnDx (const NOX::Abstract::Vector &w, const NOX::Abstract::Vector &nullVector, NOX::Abstract::Vector &result)
Computes the derivative .
Public Member Functions inherited from LOCA::TurningPoint::MinimallyAugmented::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::TurningPoint::MooreSpence::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::TurningPoint::MooreSpence::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual NOX::Abstract::Group::ReturnType computeDJnDpMulti (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &nullVector, NOX::Abstract::MultiVector &result, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDJnDxaMulti (const NOX::Abstract::Vector &nullVector, const NOX::Abstract::MultiVector &aVector, NOX::Abstract::MultiVector &result)
Computes the directional derivative for the given direction .
virtual NOX::Abstract::Group::ReturnType computeDJnDxaMulti (const NOX::Abstract::Vector &nullVector, const NOX::Abstract::Vector &JnVector, const NOX::Abstract::MultiVector &aVector, NOX::Abstract::MultiVector &result)
Computes the directional derivative for the given direction .
virtual NOX::Abstract::Group::ReturnType computeDwtJnDxMulti (const NOX::Abstract::MultiVector &w, const NOX::Abstract::Vector &nullVector, NOX::Abstract::MultiVector &result)
Computes the derivative .
Public Member Functions inherited from LOCA::MultiContinuation::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual void setDerivUtils (const Teuchos::RCP< LOCA::DerivUtils > &deriv)
Set the LOCA::DerivUtils object.
virtual NOX::Abstract::Group::ReturnType computeDfDpMulti (const std::vector< int > &paramIDs, NOX::Abstract::MultiVector &dfdp, bool isValidF)
Public Member Functions inherited from LOCA::Pitchfork::MinimallyAugmented::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::Pitchfork::MooreSpence::AbstractGroup
AbstractGroup ()
Default constructor.
virtual double innerProduct (const NOX::Abstract::Vector &a, const NOX::Abstract::Vector &b) const
Compute the inner product of a and b.
virtual void innerProduct (const NOX::Abstract::MultiVector &a, const NOX::Abstract::MultiVector &b, NOX::Abstract::MultiVector::DenseMatrix &c) const
Compute the inner product of a and b.
Public Member Functions inherited from LOCA::Hopf::MinimallyAugmented::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual ~FiniteDifferenceGroup ()
Destructor.
virtual NOX::Abstract::Group::ReturnType computeDwtCeDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &w1, const NOX::Abstract::Vector &w2, const NOX::Abstract::Vector &y, const NOX::Abstract::Vector &x, double omega, NOX::Abstract::MultiVector::DenseMatrix &result_real, NOX::Abstract::MultiVector::DenseMatrix &result_imag, bool isValid)
Computes the derivative .
virtual NOX::Abstract::Group::ReturnType computeDwtCeDx (const NOX::Abstract::Vector &w1, const NOX::Abstract::Vector &w2, const NOX::Abstract::Vector &y, const NOX::Abstract::Vector &z, double omega, NOX::Abstract::Vector &result_real, NOX::Abstract::Vector &result_imag)
Computes the derivative .
Public Member Functions inherited from LOCA::Hopf::MinimallyAugmented::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Public Member Functions inherited from LOCA::Hopf::MooreSpence::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::TimeDependent::AbstractGroup
AbstractGroup ()
Default constructor.
Public Member Functions inherited from LOCA::Hopf::MooreSpence::FiniteDifferenceGroup
FiniteDifferenceGroup ()
Constructor.
FiniteDifferenceGroup (const FiniteDifferenceGroup &source, NOX::CopyType type=NOX::DeepCopy)
Copy constructor.
virtual NOX::Abstract::Group::ReturnType computeDCeDp (const std::vector< int > &paramIDs, const NOX::Abstract::Vector &yVector, const NOX::Abstract::Vector &zVector, double w, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag, bool isValid)
Computes the derivative where is the parameter indexed by paramIDs.
virtual NOX::Abstract::Group::ReturnType computeDCeDxa (const NOX::Abstract::Vector &yVector, const NOX::Abstract::Vector &zVector, double w, const NOX::Abstract::MultiVector &aVector, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag)
Computes the directional derivative for the given direction .
virtual NOX::Abstract::Group::ReturnType computeDCeDxa (const NOX::Abstract::Vector &yVector, const NOX::Abstract::Vector &zVector, double w, const NOX::Abstract::MultiVector &aVector, const NOX::Abstract::Vector &Ce_real, const NOX::Abstract::Vector &Ce_imag, NOX::Abstract::MultiVector &result_real, NOX::Abstract::MultiVector &result_imag)
Computes the directional derivative for the given direction . The arguments Ce_real and Ce_imag hold the real and imaginary components of .
Public Member Functions inherited from LOCA::PhaseTransition::AbstractGroup
AbstractGroup ()
Default constructor.
virtual ~AbstractGroup ()
Destructor.
Implementation of LOCA::PhaseTransition::AbstractGroup virtual methods.
Teuchos::RCP< LOCA::GlobalData > globalData
Global data.
virtual double computeFreeEnergy ()
Computes the free energy at the current solution and parameter values.
Additional Inherited Members
Public Types inherited from NOX::Abstract::Group
enum ReturnType {
Ok , NotDefined , BadDependency , NotConverged ,
Failed
}
The computation of, say, the Newton direction in computeNewton() may fail in many different ways, so we have included a variety of return codes to describe the failures. Of course, we also have a code for success.
Protected Attributes inherited from LOCA::MultiContinuation::FiniteDifferenceGroup
Teuchos::RCP< DerivUtils > derivPtr
Pointer to current DerivUtils derivative computation object.
Detailed Description
Compatiblity class for AbstractGroup hierarchy.
This class is derived from all LOCA AbstractGroup abstract base classes as well as all FiniteDifference groups and any other groups that provided default implementations for AbstractGroup pure virtual methods. This class provides definitions for all needed assignment operators and provides definitions for some pure virtual methods by printing error messages. This class exists primarily for compatiblity to an older class hierarchy and will most likely be removed in the future.
Constructor & Destructor Documentation
~Group()
LOCA::Abstract::Group::~Group () virtual
Destructor.
Reimplemented from NOX::Abstract::Group.
Reimplemented in LOCA::Epetra::Group, LOCA::LAPACK::Group, and LOCA::Thyra::Group.
Member Function Documentation
applyComplex()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyComplex (const NOX::Abstract::Vector & input_real, const NOX::Abstract::Vector & input_imag, NOX::Abstract::Vector & result_real, NOX::Abstract::Vector & result_imag) const virtual
Compute .
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::Hopf::MooreSpence::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
applyComplexInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyComplexInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input_real, const NOX::Abstract::MultiVector & input_imag, NOX::Abstract::MultiVector & result_real, NOX::Abstract::MultiVector & result_imag) const virtual
Solve .
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::Hopf::MooreSpence::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
applyComplexMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyComplexMultiVector (const NOX::Abstract::MultiVector & input_real, const NOX::Abstract::MultiVector & input_imag, NOX::Abstract::MultiVector & result_real, NOX::Abstract::MultiVector & result_imag) const virtual
Compute .
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::Hopf::MooreSpence::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
applyComplexTranspose()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyComplexTranspose (const NOX::Abstract::Vector & input_real, const NOX::Abstract::Vector & input_imag, NOX::Abstract::Vector & result_real, NOX::Abstract::Vector & result_imag) const virtual
Computes conjugate-tranpose matrix vector product .
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::Hopf::MinimallyAugmented::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
applyComplexTransposeInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyComplexTransposeInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input_real, const NOX::Abstract::MultiVector & input_imag, NOX::Abstract::MultiVector & result_real, NOX::Abstract::MultiVector & result_imag) const virtual
Solve .
Implements LOCA::Hopf::MinimallyAugmented::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
applyComplexTransposeMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyComplexTransposeMultiVector (const NOX::Abstract::MultiVector & input_real, const NOX::Abstract::MultiVector & input_imag, NOX::Abstract::MultiVector & result_real, NOX::Abstract::MultiVector & result_imag) const virtual
Computes conjugate-tranpose matrix vector product .
Implements LOCA::Hopf::MinimallyAugmented::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
applySecondShiftedMatrix()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applySecondShiftedMatrix (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Multiply the shifted matrix by a vector.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::TimeDependent::AbstractGroup.
Reimplemented in LOCA::Epetra::Group.
References NOX::Abstract::Group::NotDefined.
applySecondShiftedMatrixMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applySecondShiftedMatrixMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Multiply the shifted matrix by a multi-vector.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::TimeDependent::AbstractGroup.
Reimplemented in LOCA::Epetra::Group.
References NOX::Abstract::Group::NotDefined.
applyShiftedMatrix()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyShiftedMatrix (const NOX::Abstract::Vector & input, NOX::Abstract::Vector & result) const virtual
Multiply the shifted matrix by a vector.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::TimeDependent::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, LOCA::LAPACK::Group, and LOCA::Thyra::Group.
References NOX::Abstract::Group::NotDefined.
applyShiftedMatrixInverseMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyShiftedMatrixInverseMultiVector (Teuchos::ParameterList & params, const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Apply the inverse of the shifted matrix by a multi-vector, as needed by the shift-and-invert and generalized Cayley transformations.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::TimeDependent::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, LOCA::LAPACK::Group, and LOCA::Thyra::Group.
References NOX::Abstract::Group::NotDefined.
applyShiftedMatrixMultiVector()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::applyShiftedMatrixMultiVector (const NOX::Abstract::MultiVector & input, NOX::Abstract::MultiVector & result) const virtual
Multiply the shifted matrix by a multi-vector.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::TimeDependent::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, LOCA::LAPACK::Group, and LOCA::Thyra::Group.
References NOX::Abstract::Group::NotDefined.
augmentJacobianForHomotopy()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::augmentJacobianForHomotopy (double a, double b) virtual
Replace Jacobian by where is the identity matrix and is a scalar.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::Homotopy::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
computeComplex()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::computeComplex (double frequency) virtual
Compute .
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::Hopf::MooreSpence::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
References NOX::Abstract::Group::NotDefined.
computeFreeEnergy()
double LOCA::Abstract::Group::computeFreeEnergy () virtual
Computes the free energy at the current solution and parameter values.
Implements LOCA::PhaseTransition::AbstractGroup.
Reimplemented in LOCA::Epetra::Group.
computeSecondShiftedMatrix()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::computeSecondShiftedMatrix (double alpha, double beta) virtual
Compute the second shifted matrix. Can avoid recomputing if two are stored.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::TimeDependent::AbstractGroup.
Reimplemented in LOCA::Epetra::Group.
References NOX::Abstract::Group::NotDefined.
computeShiftedMatrix()
NOX::Abstract::Group::ReturnType LOCA::Abstract::Group::computeShiftedMatrix (double alpha, double beta) virtual
Compute the shifted matrix.
Implementation here prints an error message and returns NOX::Abstract::Group::NotDefined.
Implements LOCA::TimeDependent::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, LOCA::LAPACK::Group, and LOCA::Thyra::Group.
References NOX::Abstract::Group::NotDefined.
copy()
void LOCA::Abstract::Group::copy (const NOX::Abstract::Group & source) virtual
Assignment operator.
Implements LOCA::MultiContinuation::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, LOCA::LAPACK::Group, LOCA::Thyra::Group, and LOCA::MultiContinuation::ConstrainedGroup.
References LOCA::MultiContinuation::FiniteDifferenceGroup::copy(), and globalData.
Referenced by Group(), LOCA::Epetra::Group::operator=(), LOCA::Thyra::Group::operator=(), and LOCA::LAPACK::Group::operator=().
isComplex()
bool LOCA::Abstract::Group::isComplex () const virtual
Is valid.
The implementation here always returns false.
Implements LOCA::Hopf::MooreSpence::AbstractGroup.
Reimplemented in LOCA::Epetra::Group, and LOCA::LAPACK::Group.
notifyCompletedStep()
void LOCA::Abstract::Group::notifyCompletedStep () virtual
Notify group that the continuation step is completed The default implementation here is to do nothing.
operator=()
NOX::Abstract::Group & LOCA::Abstract::Group::operator= (const NOX::Abstract::Group & source) virtual
Copies the source group into this group.
Note
Any shared data owned by the source should have its ownership transfered to this group. This may result in a secret modification to the source object.
Implements NOX::Abstract::Group.
Reimplemented in LOCA::Epetra::Group, LOCA::LAPACK::Group, LOCA::Thyra::Group, LOCA::Thyra::GroupWrapper, and LOCA::MultiContinuation::ConstrainedGroup.
setParamsMulti()
void LOCA::Abstract::Group::setParamsMulti (const std::vector< int > & paramIDs, const NOX::Abstract::MultiVector::DenseMatrix & vals) virtual
Set parameters indexed by (integer) paramIDs.
Implements LOCA::MultiContinuation::AbstractGroup.
Reimplemented in LOCA::MultiContinuation::ConstrainedGroup.
The documentation for this class was generated from the following files:
LOCA_Abstract_Group.H
LOCA_Abstract_Group.C