NOX: LOCAInterface Class Reference
LOCAInterface Class Reference
Public Member Functions
LOCAInterface (Teuchos::RCP< ProblemLOCAPrototype > &aProblem, Teuchos::RCP< ContinuationManager > aContinuationManager)
bool computeF (const Epetra_Vector &x, Epetra_Vector &f, const NOX::Epetra::Interface::Required::FillType F)
Compute the function, F, given the specified input vector x. Returns true if computation was successful.
bool computeJacobian (const Epetra_Vector &x, Epetra_Operator &Jac)
void setParameters (const LOCA::ParameterVector &params)
Set parameters in the user's application.
void printSolution (const Epetra_Vector &x, const double conParam)
Call user's own print routine for vector-parameter pair.
virtual bool computeShiftedMatrix (double alpha, double beta, const Epetra_Vector &x, Epetra_Operator &A)
Call user routine for computing the shifted matrix where is the Jacobian matrix and is the mass matrix.
virtual void setXdot (const Epetra_Vector &xdot, const double time)
Routine used in XYZT to set x_dot and time in the interface.
Public Member Functions inherited from LOCA::Epetra::Interface::TimeDependent
TimeDependent ()
Constructor.
virtual ~TimeDependent ()
Destructor.
Public Member Functions inherited from LOCA::Epetra::Interface::Required
Required ()
Constructor.
virtual ~Required ()
Destructor.
virtual void dataForPrintSolution (const int, const int, const int)
Provides data to application for output files.
virtual void setMultiPointParameter (const int)
Set multipoint parameter in the user's application.
virtual void preProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus, LOCA::Epetra::Group &)
Perform any preprocessing before a continuation step starts.
virtual void postProcessContinuationStep (LOCA::Abstract::Iterator::StepStatus, LOCA::Epetra::Group &)
Perform any postprocessing after a continuation step finishes.
virtual void projectToDraw (const NOX::Epetra::Vector &x, double *px) const
Projects solution to a few scalars for multiparameter continuation.
virtual int projectToDrawDimension () const
Returns the dimension of the projection to draw array.
Public Member Functions inherited from NOX::Epetra::Interface::Required
Required ()
Constructor.
Public Member Functions inherited from NOX::Epetra::Interface::Jacobian
Jacobian ()
Constructor.
virtual ~Jacobian ()
Destructor.
Additional Inherited Members
Public Types inherited from NOX::Epetra::Interface::Required
enum FillType {
Residual , Jac , Prec , FD_Res ,
MF_Res , MF_Jac , User
}
Type of fill that a computeF() method is used for.
Member Function Documentation
computeF()
bool LOCAInterface::computeF (const Epetra_Vector & x, Epetra_Vector & F, const NOX::Epetra::Interface::Required::FillType fillFlag) virtual
Compute the function, F, given the specified input vector x. Returns true if computation was successful.
Implements NOX::Epetra::Interface::Required.
computeJacobian()
bool LOCAInterface::computeJacobian (const Epetra_Vector & x, Epetra_Operator & Jac) virtual
Compute Jacobian given the specified input vector x. Returns true if computation was successful.
Implements NOX::Epetra::Interface::Jacobian.
computeShiftedMatrix()
bool LOCAInterface::computeShiftedMatrix (double alpha, double beta, const Epetra_Vector & x, Epetra_Operator & A) virtual
Call user routine for computing the shifted matrix where is the Jacobian matrix and is the mass matrix.
Implements LOCA::Epetra::Interface::TimeDependent.
printSolution()
void LOCAInterface::printSolution (const Epetra_Vector & , const double) virtual
Call user's own print routine for vector-parameter pair.
Reimplemented from LOCA::Epetra::Interface::Required.
setParameters()
void LOCAInterface::setParameters (const LOCA::ParameterVector & p) virtual
Set parameters in the user's application.
Should be called prior to calling one of the compute functions.
Implements LOCA::Epetra::Interface::Required.
References LOCA::ParameterVector::getLabel(), LOCA::ParameterVector::getValue(), and LOCA::ParameterVector::length().
setXdot()
void LOCAInterface::setXdot (const Epetra_Vector & , const double) virtual
Routine used in XYZT to set x_dot and time in the interface.
The computeF() routine for XYZT problems needs to be a function of x_dot, but th NOX/LOCA computeF() does not take x_dot as an argument. This is used to set x_dot in the application interface so the subsequent call to computeF has the correct x_dot value. The timeStep argument is sent so the use can set the global time, for cases when computeF, computeJacobian, computeMassMatrix fills are functions of time (nonautonomous systems).
Reimplemented from LOCA::Epetra::Interface::TimeDependent.
The documentation for this class was generated from the following files:
LOCAInterface.H
LOCAInterface.C