NOX: NOX::Solver Namespace Reference
NOX::Solver Namespace Reference
NOX nonlinear solvers namespace.
Classes
class AndersonAcceleration
Nonlinear solver based on Anderson Acceleration.
class Factory
Factory class to control the creation of solvers derived from the NOX::Solver::Generic object.
class Generic
Abstract nonlinear solver method interface.
class InexactTrustRegionBased
Newton-like solver using a trust region.
class LineSearchBased
Nonlinear solver based on a line search (i.e., damping)
class PseudoTransient
Pseudo-transient solver.
class SingleStep
Light wrapper over linear solver, executes exactly one iteration.
class TensorBased
Nonlinear solver based on a rank-1 tensor method.
class TrustRegionBased
Newton-like solver using a trust region.
Functions
NOX::StatusTest::CheckType parseStatusTestCheckType (Teuchos::ParameterList &solver_options_list)
Nonmember method that returns the status test check type.
Teuchos::RCP< NOX::Observer > parseObserver (Teuchos::ParameterList &solver_options_list)
Parses the "Solver Options" sublist for a user defined observer.
void validateSolverOptionsSublist (Teuchos::ParameterList &solver_options_list)
Nonmember method that validates and sets the defaults for the "Solver Options" sublist.
Detailed Description
NOX nonlinear solvers namespace.
The Generic class spells out the interface. The Manager class can instantiate any other concrete implementation. The remaining classes are concrete implementations.
Function Documentation
parseStatusTestCheckType()
NOX::StatusTest::CheckType NOX::Solver::parseStatusTestCheckType (Teuchos::ParameterList & solver_options_list)
Nonmember method that returns the status test check type.
This object parses the "Solver Options" parameter list for a key "Status Test Check Type" of type <std::string> with possible values:
"Complete"
"Minimal" (default)
"None"
These options correspond to the NOX::StatusTest::CheckType. Please follow the link for this object for more information.
Referenced by NOX::Solver::AndersonAcceleration::init(), NOX::Solver::InexactTrustRegionBased::init(), NOX::Solver::LineSearchBased::init(), NOX::Solver::TrustRegionBased::init(), and NOX::Solver::TensorBased::reset().